### ISSUE TITLE
Random crash. Not sure related

### ISSUE THREAD

**Issue by Punkred** [PaperMC/Paper#1]
Server randomly hangs after several hours of uptime. I noticed tps randomly dipped to 9 then went back up to 20 before this happened. Heres the only error i see other than one for a deathevent from mobstacker that happened once. http://pastebin.com/raw/CLPgscC8 It says to report to paperspigot so maybe you can guide me in the right direction.

**Comment by Techcable** [comment]
Deadlock with enjin.
This is their issue.

**Comment by Punkred** [comment]
Holy crap dude thanks for letting me know this has been bugging me for awhile

**Comment by Techcable** [comment]
Yup, no problem.
@Zbob750 please close
