### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1007]
I don't know
I have a crash every day

timings
https://timings.aikar.co/?id=efd2efc7e2c74187b1496f9a0d9e27a8

crash
https://gist.github.com/KonoromiHimaries/f4214444648ccac1444144823f492dd3

**Comment by electronicboy** [comment]
Your server took too long to tick, that's all we know; reducing the timeout inside spigot.yml might make it crash sooner at a point where it shows up the location of the holdup, but these types of crashes are generally down to plugins doing stuff and holding up the main thread.
