### ISSUE TITLE
Sound issue when closing inventory right after the sound played

### ISSUE THREAD

**Issue by Poline033** [PaperMC/Paper#1009]
**Issue Description**
When you close your inventory after you played a sound with Player#playSound it will play it again.
Video: https://streamable.com/tk77x

Code: https://hastebin.com/hayeziwera.java

It also happens when you close the player's inventory, and then open it again.

/version output: http://prntscr.com/iduq92

**Comment by zachbr** [comment]
We don't support 1.8.8 in any capacity.
I have been told this issue was fixed in vanilla 1.12. Do with that what you will.
