### ISSUE TITLE
Netty Errors

### ISSUE THREAD

**Issue by vocandew** [PaperMC/Paper#1010]
I start server on my VPS, no shit hosting(24GB ram, i7). My testers moving/building etc and i have in console: https://hastebin.com/ukozigunod.sql. Next error is:  https://hastebin.com/ibewirifat.md and 

Plugin list: ProtocolSupport

[00:25:20 INFO]: This server is running Paper version git-Paper-1327 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
First error is that something in the netty stack threw an exception, second is that the client disconnected improperly, more than likely related to the first. More than likely the cause of the issue here is ProtocolSupport.
