### ISSUE TITLE
Hopper make infinite items Build#1​32​7 

### ISSUE THREAD

**Issue by khlfkk** [PaperMC/Paper#1011]
in Build#1​32​7 , when spigot.yml set like below:

    ticks-per:
      hopper-transfer: 24
      hopper-check: 24
    hopper-amount: 3

then to setup like this image : <redacted>

you can bug a lot of same items.

my plugin list in test server:
Plugins (0):

Thanks for support and help @electronicboy

**Comment by khlfkk** [comment]
more test result , after build # 1325 all can use this to make infinite items .

**Comment by aikar** [comment]
very likely due to my hopper changes, until we can identify issue and resolve it, please set hopper-amount to 1

**Comment by khlfkk** [comment]
@aikar thanks for support

**Comment by aikar** [comment]
Please update to build https://ci.destroystokyo.com/job/Paper/1328/ to fix this issue.

**Comment by khlfkk** [comment]
@aikar Thank you so much.
