### ISSUE TITLE
Minecraft::Save Players high timings

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#1021]
I was wondering if anyone has any suggestions on how I could improve my "Save Players" timings as it seems to be pretty high.

**Timings:** https://timings.aikar.co/?id=0acaede46ba14000aa7cb5b808c1104f
**player-auto-save-rate:** 18000
**Paper Build:** #1337

**Comment by aikar** [comment]
I'm thinking it may be your garbage collection flags, in that garbage may be triggering full GC's and putting the blame incorrectly into player saving, as saving does generate a lot of garbage objects.

Please try using the recommended JVM flags: https://mcflags.emc.gs

also, please do not use /timings reset. The report is only for 3 minutes though you have a 3 hour uptime, would of helped to have some more data with more windows.


Note also your timings under "All" vs "Lag", your player saving is extremely low there. Meaning overall your doing good, but when you do lag, player saving is a huge part of it. 

I've added a max-player-auto-save-per-tick setting defaulted to 10 that will reduce the impact here for auto save.

But if you have any plugins calling .savePlayers() or using /save-all, that will still result in high player save spikes.

**Comment by SecretlyJealous** [comment]
I'll try out the recommended flags and latest build.
