### ISSUE TITLE
Chunk Error

### ISSUE THREAD

**Issue by StevenAVC** [PaperMC/Paper#1022]
Hi i have this error in my console, is the chunk error but i go to the coords and all it's normal.
Error: https://pastebin.com/WxUq4jUS
PD: I use paperspigot version 1.9 with viaversion

**Comment by mikroskeem** [comment]
Old versions are not supported

**Comment by StevenAVC** [comment]
Why do not support previous versions?, if paperspigot... Spigot supports versions of 1.7-1.12.x

**Comment by zachbr** [comment]
No they don’t. Spigot supports latest.

And even if they did, we don’t.
