### ISSUE TITLE
Snowmen trails

### ISSUE THREAD

**Issue by BBoyJD10** [PaperMC/Paper#1024]
Snowmen are not creating snow trails in any biome on spigot paper

**Comment by Black-Hole** [comment]
There is a gamerule "mobGriefing" controlling that.

**Comment by zachbr** [comment]
![snowman creating snow trails](https://i.imgur.com/o1C3ShE.png)

Please ensure your game rules are set as you want them and that you have no plugins interfering with this behavior.
