### ISSUE TITLE
Convert Paper to Gradle

### ISSUE THREAD

**Issue by aikar** [PaperMC/Paper#1026]
We are currently planning to move to Gradle as part of the MCP branch, but in effort to to bring the speed benefits of gradle without waiting for the MCP work to be finished, we can bring down the non MCP parts to master.

  - [ ] Port Paperclip to Gradle
  - [ ] Remove the Paper pom patches. Create sub gradle files in parent paper repo, so these files can be properly maintained
  - [ ] Create a script to identify what hash/source of the upstream poms the gradle files are in sync with, so any time upstream changes, we can be alerted for the need to update respectively (or, willingly choose to ignore the update)
  - [ ] Convert build scripts.

**Comment by DenWav** [comment]
I will do all but the update hash check scripts. Someone else can do that.

**Comment by JRoy** [comment]
bad bot

**Comment by MiniDigger** [comment]
we dont really need an issue for this tbh, almost all of this is done (minus the update detection for upstream pom changes, which ill create an issue on paperweight for)

**Comment by DenWav** [comment]
Closing as this is handled with paperweight, no reason to keep this around.
