### ISSUE TITLE
Unloading chunks.

### ISSUE THREAD

**Issue by Moenish** [PaperMC/Paper#103]
The chunks aren't being unloaded correctly. It only works with the /lagg unloadchunks command.
(Using it gives me this message: http://pastebin.com/wL8CeB0e)
Paper version: "This server is running Paper version git-Paper-521 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)"
This problem generates a big amount of lag on the server. We had 7 tps in the nether today :/
I can give a link to a timings test if necessary.

**Comment by martijnrondeel** [comment]
Might be duplicate of #53.
