### ISSUE TITLE
player.giveEXP with Mending is too strong

### ISSUE THREAD

**Issue by DrPanic** [PaperMC/Paper#1036]
I used `player.giveExp(1, true)` but the item with mending will loose the complete damage instead of 2 durability. Paper is Build 1342. See attached Screenshots.
![2018-03-08_18 31 14](https://user-images.githubusercontent.com/5235435/37166260-e3f94e1e-22fe-11e8-9b59-e5b93608231d.png)
![2018-03-08_18 31 20](https://user-images.githubusercontent.com/5235435/37166261-e41bbcec-22fe-11e8-990d-80c118291ea0.png)

**Comment by aikar** [comment]
Oops.... I don't know how I managed to do this, but def a bug:
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0257-Ability-to-apply-mending-to-XP-API.patch#L62

I'll fix tonight unless someone wants to beat me to it.
