### ISSUE TITLE
Secure Seed

### ISSUE THREAD

**Issue by xKumorio** [PaperMC/Paper#10386]
### Is your feature request related to a problem?

So that players don't abuse the use of seed

### Describe the solution you'd like.

You can slightly modify the generation so that you can't use the seed of the world
or this https://github.com/Earthcomputer/SecureSeed

### Describe alternatives you've considered.

idk

### Other

-

**Comment by electronicboy** [comment]
I believe that we generally decided against this because it's a fairly set of invasive changes to solve something which is relatively low priority vs all of other concerns for an issue we already have some level of mitigation for

**Comment by 456dev** [comment]
If changing the structure / generation seeds in the config files isn't enough, you can always use a datapack/plugin to change worldgen

**Comment by BangXi** [comment]
My server was set up before the map was generated.
<paper-world-defaults.yml>
feature-seeds:
generate-random-seeds-for-all: true

<spigot.yml>
seed-ancientcity: 200xxxxx
seed-buriedtreasure: 103xxxxx
seed-desert: 143xxxxx
seed-endcity: 103xxxxx
seed-fossil: 143xxxxx
seed-igloo: 143xxxxx
seed-jungle: 143xxxxx
seed-mansion: 103xxxxx
seed-mineshaft: 158xxxxx
seed-monument: 103xxxxx
seed-nether: 300xxxxx
seed-ocean: 143xxxxx
seed-outpost: 1657xxxxx
seed-portal: 342xxxxx
seed-shipwreck: 1657xxxxx
seed-slime: 9872xxxxx
seed-stronghold: 589xxxxx
seed-swamp: 143xxxxx
seed-trailruins: 834xxxxx
seed-village: 103xxxxx
(Fill in the numbers randomly)

I also use Anti-Xray: engine-mode: 1 + RayTraceAntiXray
Most of the cheaters chose to leave
In my opinion, it's already safe
