### ISSUE TITLE
Ping Issue

### ISSUE THREAD

**Issue by Feerko** [PaperMC/Paper#1039]
# Performance issue
Almot all of players have ping issue

###  Timings or Profile link:
There is no tps issues

### Description of issue:
Today it happened as describe here https://github.com/PaperMC/Paper/issues/895
I did not make any changes on the server.

I have over 1000 ping... All players have ping issues.
When i'm joining into server i get 'Loading terrain' for 5-30 seconds
There is still 20 tps, I have good dedicated server and a lot free ram, cpu and bandwidth...

### Plugin list:
This isn't plugin issue, i tried with deleting all of plugins.

### bukkit.yml, spigot.yml, paper.yml, server.properties
Same as above.

### Paper build number:
<img width="628" alt="zrzut ekranu 2018-03-09 o 22 08 53" src="https://user-images.githubusercontent.com/16988054/37230074-7b1c9480-23e6-11e8-8ad7-7e3b5b6ce570.png">

**Comment by electronicboy** [comment]
All players having issues would more than likely be an issue with your
setup or networking issues. Paper handles the latency calculations off the
main thread, so if you have 1000ms, either you've got something in the area
that players are spawning into, or you have a plugin/network issue.

**Comment by Feerko** [comment]
<img width="812" alt="zrzut ekranu 2018-03-09 o 22 15 32" src="https://user-images.githubusercontent.com/16988054/37230337-7b7fb636-23e7-11e8-9d9c-293f0e537ad2.png">

<img width="200" alt="zrzut ekranu 2018-03-09 o 22 16 04" src="https://user-images.githubusercontent.com/16988054/37230343-7e28d124-23e7-11e8-8b36-9f3596fff5f2.png">

it's caused not for all players. I have lag only when i'm join into server. It's not caused by plugins because i tried with deleting plugin by plugin.

**Comment by Feerko** [comment]
Here is my configs:

[bukkit.yml.txt](https://github.com/PaperMC/Paper/files/1798481/bukkit.yml.txt)
[paper.yml.txt](https://github.com/PaperMC/Paper/files/1798482/paper.yml.txt)
[server.properties.txt](https://github.com/PaperMC/Paper/files/1798483/server.properties.txt)
[spigot.yml.txt](https://github.com/PaperMC/Paper/files/1798484/spigot.yml.txt)

**Comment by electronicboy** [comment]
I would suggest taking an MTR and using standard network monitoring, this
seems like this isn't a paper issue, but something with your setup or your
network. Referring to the issue you originally commented on might give some
hints on how to reduce the strain during connection, I'm away from home so
can't look at timings/speak on IRC, but you'd be better off trying to get
support there.

**Comment by Feerko** [comment]
That's weird. I tried to connect direct to server without waterfall 'loading terrain' took ~1 second.

**Comment by sgdc3** [comment]
@electronicboy this is an issue that happens with bungeecord + spigot 1.12.2, it seems that mojang messed up with the keepalive packet logic.

**Comment by BBoyJD10** [comment]
sTILL GOt same issue

**Comment by sgdc3** [comment]
@electronicboy we should do something about that, you can't just ignore the problem

**Comment by BBoyJD10** [comment]
agreed 100%

**Comment by electronicboy** [comment]
You're implying that there is a problem here for us to fix, which so far there has been nothing shown to me which is a problem on our side.
The only thing that could be done here is to roughen up the averaging, which really isn't something I'd personally be happy to do, as it's not really fixing anything, and would only create complaints on the other side where the calculated average latency is easier to rocket due to a single spike...

**Comment by 0XE4** [comment]
I've been having this issue for months, combined with #895 which all started in 1.12.2. There are other services running on the box that the server runs on and they have not had any latency issues. The issue affects multiple servers not running bungeecord.

This definitely looks like an issue with Minecraft and most likely in Mojang's side and not Spigot/Paper. But very real and frustrating to get anyone to acknowledge this.

**Comment by 0-x-2-2** [comment]
I have been having this same issue since 1.12.2
