### ISSUE TITLE
Disconnects

### ISSUE THREAD

**Issue by BBoyJD10** [PaperMC/Paper#1044]
Random crashing from server with "Disconnected" or "Timed Out" only happens on the spigot server and to random players behind bungee.

**Comment by electronicboy** [comment]
Message with just "disconnected" or "timed out" would imply networking issues/improperly closed clients, either way; There is very little (Well, none, really) info here that indicates that the issue is on our end.
If you require general support, I'd suggest using the IRC/Discord.

**Comment by Tofuus** [comment]
We were randomly having these issues too. After much frustration we tracked it down to NCP cancelling keepalive packets. Check your NCP config for "keepalivefrequency" and either disabling it or changing the cancelling behaviour.
