### ISSUE TITLE
Javadocs not updating

### ISSUE THREAD

**Issue by ShaneBeee** [PaperMC/Paper#10446]
### Expected behavior

For the javadocs to be updated

### Observed/Actual behavior

I noticed the javadocs aren't up to date

### Steps/models to reproduce

The last update of paper includes new API for raids, including getID and getBossBar
but if you head to the docs, neither of those are there:
https://jd.papermc.io/paper/1.20/org/bukkit/Raid.html

### Plugin and Datapack List

N/A

### Paper version

N/A

**Comment by Nacioszeczek** [comment]
Stuff needs to build and caches need to expire.
In the meantime you can use the Javadoc in your IDE, e.g. in IDEA by pressing Ctrl+Q while your cursor is blinking on a class/method.

**Comment by ShaneBeee** [comment]
> Stuff needs to build and caches need to expire. In the meantime you can use the Javadoc in your IDE, e.g. in IDEA by pressing Ctrl+Q while your cursor is blinking on a class/method.

ok good to know thanks. Ive never had this happen before, just wasn't sure if it was an issue.
