### ISSUE TITLE
Cannot build with paper api 1.20.5 

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#10472]
### Expected behavior

Should build

### Observed/Actual behavior

net.kyori:adventure-bom:pom:4.17.0-SNAPSHOT was not found in https://papermc.io/repo/repository/maven-public/

### Steps/models to reproduce

I tried updating repo to https://repo.papermc.io/repository/maven-public/
tried updating lombok, tried switching to java 21, still unworking

### Plugin and Datapack List

N/A

### Paper version

N/A

**Comment by yannicklamprecht** [comment]
In a fork or paper itself?

You need to add

```
 maven("https://s01.oss.sonatype.org/content/repositories/snapshots/") // TODO - Adventure snapshot
 ```
 to subprojects.repositories in your root build.gradle.kts
 
 Can be removed when a stable adventure version for 1.20.5 is released.
