### ISSUE TITLE
PlayerPickupItemEvent console spam

### ISSUE THREAD

**Issue by ItsMennyo** [PaperMC/Paper#1048]
Hello. I'm creating a new server with PaperSpigot. This is not my first time that I work with Paper because I love it when I used it in the past. When I first worked with Paper I had no issues or errors with plugins. But now when I install a plugin it gives a lot of errors [examples here](https://hastebin.com/etikuradil.apache). Weird thing for me is I only have this issue with the latest few versions of Paper. When I used Paper for the first time I don't had this at all. I reported this to some of the devs of those plugins and most of them they says it doesn't affect the plugin or the performance (also some says that they cant fix this on there end) but it is still really annoying that I get spammed with all those errors. Is there not a way to fix this or even demp this?

**Comment by aikar** [comment]
This is not a bug nor something you should be concerned about.

This is also not specific to Paper. Upstream deprecated this event.
edit: hmm saw in logs you are on latest. I'm not sure why this event is triggering the spam

**Comment by aikar** [comment]
Going to reopen and change title about that log line.
It looks like we are intending to not print spam on this event (@Warning(false)), however it is still printing.

**Comment by aikar** [comment]
In your bukkit.yml, check that
settings.deprecated-verbose=on

does not exists

if it does, set it to =default

**Comment by ItsMennyo** [comment]
Oh boiii Setting deprecated-verbose to default works. Thank you 🥇
