### ISSUE TITLE
Async scheduler changes resulting in system resource problems

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1049]
Hi, this is just to shine the light on a potentially very bad issue. I updated from build #1349 to #1357 today and it broke so many things. For one, all of the servers on the dedi were affected and lagging horribly until they either crashed or were not joinable, I was getting errors like: java.lang.OutOfMemoryError: unable to create new native thread & my tmux instances dying to "bash fork retry: no child processes" where it was just being spammed and non responsive, the entire dedi was dying.

Anyways I googled some of those errors and have been lead to https://en.wikipedia.org/wiki/Fork_bomb by multiple articles. After trying a few other things and since I had not changed much more than the server jar in the last day, I decided to revert back to #1349 and to reboot the dedi because even with all the servers stopped & killed java could not create new native threads, they all started working just fine again.

Sorry if this is not following the format, I just wanted to point out my experience because I do believe it is from the recent update.

**Comment by aikar** [comment]
Can you paste the logs? There's nothing for us to go on here.

There has been nothing done to forking processes though. It sounds like your server crashed in some way and the auto restart script may of got stuck in some kind of loop?

**Comment by ghost** [comment]
Seems it was actually build #1353 and sure, full log: https://pastebin.com/Z45MwnAR Hope this helps, you can see multiple occurences of "java.lang.OutOfMemoryError: unable to create new native thread"

**Comment by aikar** [comment]
while it seems to relate to the async changes, i can't see how the async stuff would of caused anything different in behavior here.

Was this a single case and you downgraded after, or does it constantly reoccur?

IT looks like the server simply ran out of resources at the time, and triggered this.

can you retry the update in a test environment and try to reproduce? if you do reproduce, can you print the process list.

**Comment by ghost** [comment]
I ran it multiple times and it happened on other servers too. When it first happened I restarted the servers, it happened again so I then restarted the dedi entirely and when it happened after that I reverted and it stopped. And sure ill play around with latest on dev

**Comment by MatrixTunnel** [comment]
I've been having an issue very similar to this ever since the async changes. I'm not exactly sure what it is yet but I'll post something here if anything changes

**Comment by electronicboy** [comment]
Next time this occurs, try to get a report using jstack, You'll need to grab the process ID, and then pass it to the jstack command; 
e.g. jstack 520

That should give us a list of every thread and where it's at

**Comment by minoneer** [comment]
We are also experiencing issues that appear to be related to some sort of concurrency issues since updating from #1347 to #1350 last night. The server occasionally freezes for some time, with all players loosing connection due to timeout. Stacktrace for all threads from the Watchdog:
https://paste.devsylum.de/abuguduxuz.md
We were unable to reproduce in a test environment. Maybe it helps to shed some light.

**Comment by aikar** [comment]
ugh github I did not mean it is resolved yet. stop interpreting my message too deeply!

Try build 1358 and let me know how things go. I am still super perplexed how this issue could occur, so i took out my optimization (but it really makes no sense for this to help) to 0 delay no repeat tasks.

I also switched executors for the management thread to a more proper single threaded executor I intended to use.

**Comment by aikar** [comment]
I also can not recreate it in dev, even with spamming async tasks :/

**Comment by aikar** [comment]
@minoneer  @MatrixTunnel  @dandzn any status on latest builds?

**Comment by MatrixTunnel** [comment]
Looks like things are running fine now. I'm not sure if it was a one-time thing but it's better now then before

**Comment by aikar** [comment]
Closing. Open a new issue if problems still arise.
