### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by aurel85** [PaperMC/Paper#1053]
Hi,

Recently I have this message that sometimes appears in my console just before the connection of some players. Do I have to worry about it ? And is there a way to stop having it ?

https://pastebin.com/AAhxyZb8

It does not seem to change much in game even if recently (new machine) I have unexplained lags but it could come from something else.

I use PaperSpigot 1.12.2 version 1360.

Thank you in advance !

**Comment by aikar** [comment]
Yep there was a bug there. Please update to build 1361+ to resolve this.
