### ISSUE TITLE
re-enable vanilla command signs

### ISSUE THREAD

**Issue by Wqrld** [PaperMC/Paper#1054]
could you add a patch to re-enable vanilla command signs? I really want to play missile wars on my spigot server but its unplayable due tot most sign commands not working

**Comment by aikar** [comment]
Build 1362+ you may now set in commands.yml "unrestricted-signs: true"

Please note doing this is at your own risk and should never be done if players have creative mode.

I BELIEVE it is safe to do where untrusted players do not have creative, as sign updates still strip commands. But Paper is not responsible if players find a way to elevate their permissions with signs if you enable this.

**Comment by Wqrld** [comment]
awesome! thanks a lot

**Comment by Wqrld** [comment]
i dont see it show up in my fresh commands.yml, did you forget to auto-add it in the config?

edit: not going to reply for this, trying it now

**Comment by theminecoder** [comment]
It won’t show automatically, you will need to add it yourself
