### ISSUE TITLE
No more skin except mine (ig, tab and dynmap)

### ISSUE THREAD

**Issue by aurel85** [PaperMC/Paper#1055]
Hi,

Since #1053 and the version 1361 I see all the players of my server without skin (except mine) that it is in-game, in the tab or on the dynmap. With version 1365 (currently on my server) it's always the same.
For the dynmap I have the latest version that fixes the skin bug that happened 1 month ago.
There is nothing in the logs.

My plugin for Tab : https://www.spigotmc.org/resources/tab.1448/
A screen of the Tab : https://sandbox.fr/images/uploads/original/1521736708.png

Thank you in advance.

**Comment by aikar** [comment]
yep someone reported this earlier. I'm at work and unable to fix at this time, will fix this evening.

Please downgrade back last known good version and i'll update when issue is resolved tonight.

**Comment by aikar** [comment]
Fixed in https://github.com/PaperMC/Paper/commit/b8a672dd94395ee3d91c9301cf597fe47f4a29c3
build 1366+

**Comment by aurel85** [comment]
This bug is back with version 1370.
