### ISSUE TITLE
Random crash upon join?

### ISSUE THREAD

**Issue by RainOfPain125** [PaperMC/Paper#1056]
**The following are 'hard suggestions': if you have the information
available to you, you really should put it in the report. Choose one of
the following templates from below that best fits the issue you wish to
report.**

# Crash, Stacktrace

### Link/paste of stack trace
https://pastebin.com/dqKGqasS
    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Plugin list:
Plugins (64): ActionAnnouncer, AdvancedBan, ArrowTrails, Auctions, Chairs, ChatFeelings, ChatItem, ChestRestock, Citizens, ColoredAnvils, CombatLogX, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CrazyCrates, CrazyEnvoy, DeluxeJoin, DiscordSRV, dynmap, EpicRename, Essentials, EssentialsChat, eZProtector, FastAsyncWorldEdit, Gringotts, HolographicDisplays, InfoBook, InventoryFull, LuckPerms, MassiveBooks, MassiveCore, mcMMO, mcMMOAction, MessageAnnouncer, Multiverse-Core, NoCheatPlus, NoPlugins, OpenInv, Orebfuscator4, PerWorldInventory, Plan, PlayerMention, PluginLibrary, ProtocolLib, Questioner, ServerListPlus, ShulkerBlock, SilkSpawners, SimpleBackup, SuperTrails, SuperVanish, Tablist, TitleManager, Towny, TownyChat, TownyNameUpdater, Trading, UltraCosmetics, Vault, VPNGuard, Wild, WorldBorder, WorldEdit, WorldGuard
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
 git-Paper-1360

**Comment by electronicboy** [comment]
You have damaged regions, I'd suggest backing up your world and running Minecraft region fixer over it and seeing if it helps.

**Comment by RainOfPain125** [comment]
Used it

Unreadable player files:
No problems found.

Unreadable data files:
No problems found.

Chunk problems:
No problems found.


Region problems:
No problems found.

**Comment by electronicboy** [comment]
In that case, I'd suggest restoring a backup, There is much we can do about worlds which are damaged

**Comment by RainOfPain125** [comment]
We seemed to have fixed it. The thing that was causing the issue was player A was logged off in the normal minecraft world (not in our other Earth world) and when said player logged on the server would stop

Now that we deleted the normal mc world and the player has spawned in our earth world it no longer happens.

Thanks anyways :P
