### ISSUE TITLE
Use Minecraft logger (or another more specific logger) for messages to console command sender

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/Paper#1058]
Basically I would propose to change this:
https://github.com/PaperMC/Paper/blob/9daa9cec930f16d52330656f42ab992eb4612683/Spigot-Server-Patches/0208-Use-TerminalConsoleAppender-for-console-improvements.patch#L110
to use MinecraftServer.LOGGER or ideally a more specific logger so its easier to filter the messages.

**Comment by Proximyst** [comment]
This does not exist anymore.

**Comment by Proximyst** [comment]
Closing was a PEBKAC! This is still there :p
