### ISSUE TITLE
Problem with skin

### ISSUE THREAD

**Issue by aurel85** [PaperMC/Paper#1061]
Hi,

#1055 

This bug is back with version 1370 (except for the dynmap).
Finally now it concerns that those who are connected before me, when a new player connects there is no problem.

Thank you in advance.

**Comment by aikar** [comment]
I can not reproduce. I logged in and out multiple times.

You may of just gotten rate limited.

**Comment by aurel85** [comment]
In any case with the 1371 I do not have the problem !
