### ISSUE TITLE
Piston/Sand Query

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Paper#1066]
Hey,

This is more of a query than an issue, apologies if this isn't the place for queries. 

Does Paper have any features for the performance of pistons/falling blocks? People in creative servers can create these piston setups which generate a lot of falling block entities which kills TPS. Is there a way to limit piston/falling entities within spigot or paper?

Thanks.

**Comment by Brokkonaut** [comment]
I think that should be done by a plugin and not by the server itself, because there can be many different wanted cofigurations (limit per server, limit per world, limit per plot, limit per owner) and many different things that can create lag

**Comment by electronicboy** [comment]
Closing, I've been busy and so haven't really been doing much beyond picking off an issue or two while I can...

There is nothing really inside of Paper itself that I'm aware of that would optimize stuff like this directly, it's very hard to observe this behavior from the server and maintain such a safety net while considering all potential implications and wants from people.

It's much easier for a plugin sitting on the outside of the internals which can specifically aim to observe this behavior, especially when paper provides events which should capture all of what's going on and allow plugins in the safety net of an API to handle this kinda thing.
