### ISSUE TITLE
Error: Build 1373

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1067]
Hello,
I encounter several problems with the build 1373 of paperclip.
Indeed, the server does not launch with this version. Also, with a version higher than 1349, I no longer see the skins of the players in play.

Crash report: https://hastebin.com/giqafobuxa.sm
Log: https://hastebin.com/ayihemopoz.md

Thanks,

**Comment by aikar** [comment]
@Minecrell this looks related to your ping changes.

**Comment by aikar** [comment]
and @Heliosard skin issues are resolved in later builds. Try a few older builds.

**Comment by aikar** [comment]
hmm it looks like you have a negative value for settings.sample-count in spigot.yml @Heliosard 
Set that to 0 or a positive number to fix this.

But we should at least fix sample-count to ignore negatives and Math.max to 0
