### ISSUE TITLE
30.03 13:00:34 [Server] WARN Skipping Entity with id minecraft:rideablespider

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Paper#1069]
30.03 13:00:34 [Server] WARN Skipping Entity with id minecraft:rideablespider
30.03 13:00:34 [Server] WARN Warning, could not find EntityType for rideablespider - Please report this to Paper at https://github.com/PaperMC/Paper/issues
30.03 13:00:34 [Server] WARN Skipping Entity with id minecraft:rideablespider
30.03 13:00:34 [Server] WARN Warning, could not find EntityType for rideablespider - Please report this to Paper at https://github.com/PaperMC/Paper/issues
30.03 13:00:34 [Server] WARN Skipping Entity with id minecraft:rideablespider

getting spammed, 1.12.2 paper-1371, 3 versions behind. Also i doubt this is related but for some reason despite 0 changes besides updating paper /msg is an unregistered command. all plugins relating to it are loaded and working, but this is unlikely to do with paper unless you made some cmd changes or something.

just thought i'd report.

**Comment by aikar** [comment]
hmm the log spam looks like i missed removing one. you can ignore the error, its caused by you using a custom entity plugin, but theres nothing we can do about it.

as for command, nothings changed there lately.

**Comment by Cobwebster** [comment]
Kk thank you :)
