### ISSUE TITLE
PaperSpigot 1.9 Plugin Incompatibilities

### ISSUE THREAD

**Issue by Spireshield** [PaperMC/Paper#107]
Hello!
I just loaded PaperSpigot 1.9, and soon realized that many plugins are incompatible.
I've fixed many of them, and they now work, excluding ChestShop and LWC. I have downgraded, upgraded, unofficial builds and all, and both aren't working.
Thank You!

**Comment by Ichbinjoe** [comment]
We are not responsible for plugins not working on 1.9. Contact the plugin
developer for these plugins to be fixed.

**Comment by Spireshield** [comment]
Okay, thank you.
