### ISSUE TITLE
Error: Dragon UUID

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1072]
Hello,

Sometimes when you spawn a dragon and get his UUID, you can't find him afterwards with the same UUID.
This bug has been present for several versions. It's prevents us from getting the UUID of a dragon that appears for factional events.

Currently, I'm using the: Paper version git-Paper-1349

Thanks,

**Comment by aikar** [comment]
how are you "finding" him? Can you find a dragon who's UUID has changed?

**Comment by ghost** [comment]
When the spawn dragon, its UUID is sometimes "null" or different.

**Comment by Black-Hole** [comment]
Please provide some code to reproduce the issue. Also please try to reproduce without any other plugin beside your test plugin

**Comment by BillyGalbreath** [comment]
I wonder if this is a [Entity#getEntityId()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html#getEntityId--) and [Entity#getUniqueId](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html#getUniqueId--) mixup. The mention of it being sometimes null has me off, though..

**Comment by Proximyst** [comment]
Given we don't have any reports of this issue, I'll assume it has been fixed somewhere at some point, or this was a user error as Billy mentioned. Please open a new issue if this is still present.
