### ISSUE TITLE
latest paperclip weird console errors

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Paper#1073]
Not sure if this is paperclip related, but we're seeing this error randomly.

04.04 11:44:26 [Server] WARN java.io.NotSerializableException: org.bukkit.Color
04.04 11:44:26 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
04.04 11:44:26 [Server] WARN at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
04.04 11:44:26 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
04.04 11:44:26 [Server] WARN at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
04.04 11:44:26 [Server] WARN at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
04.04 11:44:26 [Server] WARN at 

I'm assuming its not paper related, just narrowing down my search since i cant think of any plugin thats writing colors to config. I guess just close this ticket if you know its not paper related.

**Comment by mikroskeem** [comment]
Whole server log?

**Comment by aikar** [comment]
You cut off the stack that would of shown what plugin caused it.

Though im not sure why color isnt made serializable though. seems an easy one to do... but ultimately, best done upstream

going to close as its not a paper issue, but if you need help identifying plugin please paste more of the stack trace
