### ISSUE TITLE
doVillages stuck in a loop, loading chunks with no players, even when server first boots. (not spawn chunks)

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#1074]
git-Paper-1358 (MC: 1.12.2)

RAM consumption issue. Areas with Villages loaded/not unloading. They load up when the server starts and do not unload.

https://timings.aikar.co/?id=ccc6079f415647b5b120b0da4cbd1030

doVillages seems stuck in a loop. Chunks load in when no one is around, even after server restart. Villages might just be getting created over and over.

**Comment by hurrgurl** [comment]
Why not update to latest and see if it helps?

**Comment by MiniDigger** [comment]
spigot ticks inactive villagers now. they recently added a config option for that since ppl complained: `entity-activation-range.tick-inactive-villagers: false`
try if that improves (after you updated paper)

**Comment by NullCase** [comment]
OK, that's completely removed the odd chunk loading loop.

I wonder if there's a way to tick inactive villagers without having them generate this loop where chunks are constantly loading with nobody around. I can definitely see some value in having the activation of villagers treated differently than say sheep or cows. Especially with automated crop farms. But not when it's behaving like a lag machine.

In a few weeks I'll try turning `entity-activation-range.tick-inactive-villagers: true` just to see if it's been fixed.

Something about the "recreateStructures" still using a lot more CPU than before. Anyway, your suggestion definitely helps.

https://timings.aikar.co/?id=fbec58b1cefd4f0f8dcbfe2919c16e3a

**Comment by electronicboy** [comment]
Chunk issues should be resolved in https://github.com/PaperMC/Paper/commit/280e8b14cafa83742a4736a5ca477706cedae2b5
I would imagine that this might also help with villagers in general
