### ISSUE TITLE
Why are the player profiles requested when it is "online-mode: false"

### ISSUE THREAD

**Issue by DardBrinza** [PaperMC/Paper#1076]
I use the last build of paper (1.12.2 #1383) and get lot of errors in the console:
https://pastebin.com/MWCYFqHj

(debug mode)
https://pastebin.com/57dEQAPM

It should not make inquiries, because I turned off the online mod, so why do I get out of the players because of the requests that are turned off?

**Comment by sgdc3** [comment]
Are you using any plugin that fetches player skins/skulls?

**Comment by aikar** [comment]
Hmm, forgot to check for online mode before looking up textures in the profile api stuff.

Will fix soon

**Comment by DardBrinza** [comment]
@sgdc3 Yep, skin restorer (bungee + paper)
