### ISSUE TITLE
Massive TPS-Drop after Upgrade from 1342 to 1384 

### ISSUE THREAD

**Issue by DrPanic** [PaperMC/Paper#1077]
# Performance issue

###  Timings or Profile link:
Build 1342: https://timings.aikar.co/?id=614954473e8244158b1a13743a43900f
Build 1384: https://timings.aikar.co/?id=53765f6b1324404cbdebfcb2c8b7f8fd

### Description of issue:
The new option `cooldown-when-full: true` reduced the server workload massively. After the update to build 1384 the tps loss increased up to 100% and the server had tps lower as 10. After an downgrade the tps-loss is gone.

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml: https://pastebin.com/UNCcQiDV
spigot.yml: https://pastebin.com/88v91Pj9
paper.yml: https://pastebin.com/mYUvQL2d
server.properties: https://pastebin.com/AqkTEKHb

### Paper build number:
1384

**Comment by Black-Hole** [comment]
It seems like a lot of villagers in minecarts. Have a look at #1074

**Comment by DrPanic** [comment]
Yeah. That also. But look at Minecraft::tickTileEntity - nms.TileEntityHopper eg. After the update it is up to 20% and before it was 6%. It seems that `cooldown-when-full` is not applied anymore, because its like the value the ticks were used before `cooldown-when-full` was possible.

I have a look at #1074 too.

**Comment by DrPanic** [comment]
No, unfortunately #1074 doesnt fix it:
https://timings.aikar.co/?id=cad40358bad7493fa1d407ed993baa1e

The Hoppers are still on high consumption.

**Comment by electronicboy** [comment]
You're ticking 16k hoppers in the latter tick compared to the former having only just under 5k, each hopper isn't taking much time, but in the sheer quantity that you have it's going to hurt. Disabling the hopper move events from being fired might help at the risk of breaking any plugin that relies on that event

The inflation in loaded chunks is probably to blame for that, can you provide timings on the latest build with that setting set as mentioned in #1074 ?

**Comment by electronicboy** [comment]
Nvm, didn't read the last message properly where you linked such timings...

**Comment by zachbr** [comment]
Please swap to build 1381, run it for a while, and let us know if you see similar results.

**Comment by 0XE4** [comment]
We've just come from 1380 to 1384 and are having the same kind of performance drop since the upgrade. Will try going to 1381.

**Comment by electronicboy** [comment]
Should be fixed in https://github.com/PaperMC/Paper/commit/280e8b14cafa83742a4736a5ca477706cedae2b5

**Comment by 0XE4** [comment]
1386 has great performance so far, thanks @electronicboy

**Comment by DrPanic** [comment]
Same here, thank you 👍
