### ISSUE TITLE
ServerInternalException: Attempted to place a tile entity 

### ISSUE THREAD

**Issue by RainOfPain125** [PaperMC/Paper#1078]
**The following are 'hard suggestions': if you have the information
available to you, you really should put it in the report. Choose one of
the following templates from below that best fits the issue you wish to
report.**

### Paper build number:git-Paper-1383 (MC: 1.12.2)
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

# Incompatibility (Bug)

### What behaviour is expected:
Not sure...
### What behaviour is observed:
https://pastebin.com/Bjq7b0Gk
### Steps/models to reproduce:
We don't know what happened... We just know it's associated with paper spigot.
### Plugin list:
___A list of your plugins___
Plugins (65): ActionAnnouncer, AdvancedBan, ArrowTrails, Auctions, BlowableObsidians, BountyHunters, CFD, Chairs, ChatFeelings, ChatItem, ChestRestock, Citizens, ColoredAnvils, CombatLogX, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CrazyCrates, CrazyEnvoy, DeluxeJoin, DiscordSRV, EpicRename, Essentials, EssentialsChat, eZProtector, FactionChat, Factions, FastAsyncWorldEdit, HeadDrop, HolographicDisplays, InfoBook, InventoryFull, LuckPerms, MassiveBooks, MassiveCore, mcMMO, mcMMOAction, MessageAnnouncer, Multiverse-Core, NoCheatPlus, NoPlugins, OCMFixer, OpenInv, Orebfuscator4, PerWorldInventory, Plan, PlayerMention, PluginLibrary, ProtocolLib, ServerListPlus, ShulkerBlock, SilkSpawners, SimpleBackup, SuperTrails, SuperVanish, Tablist, TitleManager, Trading, UltraCosmetics, Vault, VPNGuard, Wild, WorldBorder, WorldEdit, WorldGuard

**Comment by electronicboy** [comment]
This issue is generally always down to plugins which are modifying the state of the world in an unsafe manner, plugins like FAWE are known to cause this issue.

**Comment by RainOfPain125** [comment]
Oh, sorry for that.
