### ISSUE TITLE
Sprint aborting when in air

### ISSUE THREAD

**Issue by sjoerdtim** [PaperMC/Paper#1079]
# Incompatibility (Bug)

### What behaviour is expected:
Sprinting during PVP shouldn't get aborted.

### What behaviour is observed:
While you are fighting and sprinting, sprint sometimes gets aborted. As far as I've tested, this usually happens when you get hit in the middle of a crit. It's been very hard for me to reproduce, but after disabling all plugins, it came down to something being related to the version.
After sprint is aborted, you are unable to sprint until you stand still (by walking against a wall or releasing the forward key), pressing the sprint key again does not fix the issue.

### Steps/models to reproduce:
Simply fight someone while sprinting and jumping and this issue can occur.

### Plugin list:
None

### Paper build number:
I have tested it and it happens with versions 1330, 1370 and 1389
The bug doesn't happen with 1283 and 1300
This leads me to believe the issue is some change comitted between 1300-1330, hopefully this will make it easier for you to solve.

**Comment by Brokkonaut** [comment]
I can confirm this bug.

**Comment by electronicboy** [comment]
anybody able to pinpoint the version more accurately? makes it easier to solve the issue if we know where it is, but I can't see any changes between 1300 and 1330 which would cause it, only concern around those dates would have been a craftbukkit commit, but we didn't merge that one for a day or two from the looks of it

**Comment by Brokkonaut** [comment]
I had a look at the server sources and could not find anything related. i'm not sure what causes it, maybe its some vanilla (client side?) behavior.

**Comment by Brokkonaut** [comment]
https://github.com/PaperMC/Paper/pull/1085 might fix that problem. at least it fixed it on our server. its technically not a bug, but just a strange minecraft behaviour.

**Comment by aikar** [comment]
Was not a bug, as this was vanilla behavior. But this can now be configured as #1085 has been pulled.
