### ISSUE TITLE
Configs overwritten with "NULL"

### ISSUE THREAD

**Issue by RainOfPain125** [PaperMC/Paper#1082]
# Incompatibility (Bug)

### What behaviour is expected:
...
### What behaviour is observed:
Tons of configs turned into "NULL", including spigot.yml, paper.yml, and a few config yml's
### Steps/models to reproduce:
No idea...
### Plugin list:
___A list of your plugins___
Plugins (65): ActionAnnouncer, AdvancedBan, ArrowTrails, Auctions, BlowableObsidians, BountyHunters, CFD, Chairs, ChatFeelings, ChatItem, ChestRestock, Citizens, ColoredAnvils, CombatLogX, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CrazyCrates, CrazyEnvoy, DeluxeJoin, DiscordSRV, EpicRename, Essentials, EssentialsChat, eZProtector, FactionChat, Factions, FastAsyncWorldEdit, HeadDrop, HolographicDisplays, InfoBook, InventoryFull, LuckPerms, MassiveBooks, MassiveCore, mcMMO, mcMMOAction, MessageAnnouncer, Multiverse-Core, NoCheatPlus, NoPlugins, OCMFixer, OpenInv, Orebfuscator4, PerWorldInventory, Plan, PlayerMention, PluginLibrary, ProtocolLib, ServerListPlus, ShulkerBlock, SilkSpawners, SimpleBackup, SuperTrails, SuperVanish, Tablist, TitleManager, Trading, UltraCosmetics, Vault, VPNGuard, Wild, WorldBorder, WorldEdit, WorldGuard
### Paper build number: I'm not sure which build number this had happened on, however, I am using git-Paper-1390 right now

**Comment by mikroskeem** [comment]
Java version?

**Comment by electronicboy** [comment]
Based upon your thread on the spigot forums, your disk is corrupted. More than likely your system shutdown improperly and didn't update the contents of some files safely, this isn't a paper issue; Your course of action is to either attempt to recover the files by either praying that chkdsk works, or by restoring a backup of the files.

(I'd link for reference but I can't find it anymore)

**Comment by RainOfPain125** [comment]
Why would it 'update' the files, when it could have just kept what was already there in the configs?

Guessing thats how it all works...?

**Comment by electronicboy** [comment]
Because it needed to write back any potential updates to the file, might even just be pot luck that you killed the directory structure due to a single fine in there or somewhere
