### ISSUE TITLE
GameMode crashes

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Paper#1083]
Latest version and some are like 20ish versions behind but the error is the same on the ones which are the latest paper version.

we're getting a few of our gamemodes crashing with the same error,

https://hastebin.com/faxadiqiso.md

**Comment by electronicboy** [comment]
PEX is accessing methods which can cause network lookups on the main thread, there are known issues with PEX which allows people to take advantage of this to crash servers.

**Comment by Cobwebster** [comment]
Really appreciate that info, we're moving over to luckperms now. <3
