### ISSUE TITLE
Question (Sorry)

### ISSUE THREAD

**Issue by RainOfPain125** [PaperMC/Paper#1084]
I could not find any sort of forum for paper spigot, so I thought I could quickly ask here -

What is the difference between paper spigots built-in anti-xray versus a plugin like Orebfuscator? Is it more efficient, is it written better? Is it more updated? Should I get rid of Orebfusctor in return for papers built-in one with no downsides?

Also - Is there a forum for paper spigot? I'd love to favorite it and ask questions there instead of here. Or maybe a discord?

**Comment by electronicboy** [comment]
Papers build in obfuscator is simple, but tests showed that it was more performant; You'd have to look at the original PRs comments for more information, https://github.com/PaperMC/Paper/pull/858

Basically: if you're only needing the basic obfuscation and are willing to get rid of some of the more complex features that are provided in the plugin, I would recommend switching; If you need the more advanced features, you'll wanna look elsewhere.

Also, Paper has an IRC channel and a discord (https://discord.gg/jETyjUw)
