### ISSUE TITLE
using spigot essentials /sethome in the nether makes overworld bed become obstructed

### ISSUE THREAD

**Issue by BaltimoreCalling** [PaperMC/Paper#109]
Players have been losing their essentials /home bed after they use /sethome in the nether.

Running current versions of paper and spigot essentials,

**Comment by kashike** [comment]
Stop using Spigot Essentials, use EssentialsX.

**Comment by zachbr** [comment]
Duplicate of #85 which I still don't even think is a real bug w/ paper. But w/e

**Comment by BaltimoreCalling** [comment]
Same with EssentialsX

**Comment by BaltimoreCalling** [comment]
Please reopen

**Comment by Ichbinjoe** [comment]
This is solely a plugin issue. It will remain closed.

**Comment by zachbr** [comment]
This was closed for being a duplicate, not because we were dismissing the issue. Although I must say I have my doubts at its validity.
To comment on it, please go to #85 and discuss there. Thanks :)
