### ISSUE TITLE
PacketPlayInPositionLook - Lag

### ISSUE THREAD

**Issue by Baktus79** [PaperMC/Paper#1096]
Hey

I am not sure if this is related to the Paper application or not, but I will try to post this one here. Hopefully some of you have some answers on why this is happening and what I can do to fix the issue.

Lately I have been experience some heavy lag spikes. Normally my server is stable at about 19-20 TPS, but the past 2 weeks or so I am getting real bad spikes. It drops from 20 to 1 in just a second. The spike takes about 5-6 seconds before it goes back to 20. I use Aikar Timings to nail down the problem but it doesnt seem to be a plugin issue. 

The Aikar Timings report constantly shows me that Minecraft::Packet - PacketPlayInPositionLook is the reason for the lag spikes. Why is this happening?

Paper Version: git-Paper-1399
view-distance=8

![lag_spikes1](https://user-images.githubusercontent.com/19745447/39097925-6ee4ea1a-4663-11e8-9af7-3ccabf27f1b8.png)

**Comment by mikroskeem** [comment]
Plugins list?

**Comment by Baktus79** [comment]
![plugins](https://user-images.githubusercontent.com/19745447/39098430-364456a2-466b-11e8-8a8f-56c816fc5411.png)

**Comment by aikar** [comment]
appears that your CPU may just be struggling at times, as no plugin is showing as a cause. 

check with your host, as if your running under a VM, you may be having CPU Steal issues.

For any further questions, feel free to ask on IRC https://paperchat.emc.gs or Discord https://paperdiscord.emc.gs
