### ISSUE TITLE
Water and Lava

### ISSUE THREAD

**Issue by BoxmanCaleb** [PaperMC/Paper#11]
Here's my issue. I've tried removing all plugins, and then changed from PaperSpigot to Spigot. Not a plugin issue, but once I moved to Spigot alone, it worked like vanilla. (Second picture). Any idea what would cause this in PS? I'm thinking it's a configuration option, but I was testing with default settings, so no idea what option I could change to fix this.

http://m.imgur.com/a/S7fcz

**Comment by BoxmanCaleb** [comment]
Please, if any of you guys know whether it's a bug with PaperSpigot, or is it an option in the configuration?

**Comment by zachbr** [comment]
I'll be looking into this on Friday if no one beats me to it

**Comment by BoxmanCaleb** [comment]
Sounds good. :+1:

**Comment by zachbr** [comment]
Seems to work just fine over here. Can you paste the output of `/version` here, and perhaps a schematic of what you were using for testing? I think I reproduced it but I can't get the same results. I also tried a few other scenarios. Just not seeing any weird results.

**Comment by BoxmanCaleb** [comment]
https://gyazo.com/5b3709a5ffa8f93315ba7b43c9e06d1f

And here's the schematic. :)
http://www.mineslam.com/downloads/papertesting.schematic

**Comment by zachbr** [comment]
I'll continue looking at your issue, however something I noticed now is that you're quite out of date, the build you're running is from Fri Oct 16 22:23:05 2015 -0500. While I keep looking,. please update your server and re-test on your end.

**Comment by BoxmanCaleb** [comment]
Sure thing!

**Comment by zachbr** [comment]
May have confirmation on this, will work more towards reproducing and solving soon.

**Comment by SnakeDaoust1232** [comment]
<3

**Comment by zachbr** [comment]
This was reported to us again, with this linked as evidence:
Video: https://www.youtube.com/watch?v=VFExX4Oxg10&feature=youtu.be

But I still cannot reproduce this at all, nor can anyone I've talked to. Please paste your configs, all of them, minecraft, bukkit, spigot, paper, etc, somewhere and link them here

**Comment by SnakeDaoust1232** [comment]
Before i do this. This was used to be running on 1.7 paperspigot. I never did delete the configs or paper.yml or anything. i just threw the 1.8 jar on the server and booted it up. Should i give that a try first?

**Comment by SnakeDaoust1232** [comment]
"That a try" Meaning deleting the configs and regen-ing the files.

**Comment by BoxmanCaleb** [comment]
I've already tried that Snake. :/

**Comment by zachbr** [comment]
Please give this build a try, I have removed the water-specific changes so we'll be able to determine if any of them are the culprit. Please test for some time as this issue seems fairly random and we don't want to miss anything.

Paper jar for testing: https://drive.google.com/open?id=0B5xdwK8OIEwGTnp1eHVLRlVlaDg
Source diff: https://gist.github.com/Zbob750/fc87d9234b5e6da7c822

**Comment by BoxmanCaleb** [comment]
I'll check in the morning! :+1:

**Comment by BoxmanCaleb** [comment]
That fixed it for me! :)

**Comment by SnakeDaoust1232** [comment]
It didn't fix anything for me :(

I deleted my bukkit.yml, spigot.yml, and paper.yml and regenerated them also.

Here they are.

Bukkit.yml: http://pastebin.com/ybePB6Gx
Spigot.yml: http://pastebin.com/wZQa28mC
Paper.yml: http://pastebin.com/fHwpgaRB

**Comment by SnakeDaoust1232** [comment]
I just checked out another server I'm running PaperSpigot 1.8 on and there is no water issue.

Here is the verson: https://gyazo.com/505e6747f2a3bb2469f8a86856ea80e2

**Comment by SnakeDaoust1232** [comment]
I have found the issue. You can close the thread. <3

**Comment by zachbr** [comment]
Care to say what it was? You don't appear to be the only one having this issue.

**Comment by SnakeDaoust1232** [comment]
I have a "SpongeableLava" plugin that i had coded in 1.7. It needs to be updated to 1.8.

**Comment by zachbr** [comment]
I need to know who is still experiencing this bug and if I can get you some updated builds to test.

**Comment by BoxmanCaleb** [comment]
If you'd like I can test, but afaik what you sent before fixed it. :)

**Comment by zachbr** [comment]
What I sent before disabled all of the water changes we make, and is not in the master version. I'd like to find a single cause and then fix it for everyone, not just keep making one-off builds for a few people :)

I'll get you a few different builds to try soon.

**Comment by BoxmanCaleb** [comment]
Of course dude, I understand. :+1:

**Comment by zachbr** [comment]
@BoxmanCaleb and any others experiencing this issue. I have compiled several jars with each of the water and lava changes removed. Please try each of them for ... a relatively long period of time and let me know if you're able to reproduce any liquid issues.

Thanks
https://drive.google.com/folderview?id=0B5xdwK8OIEwGN2ZkVS1DSkdlRFk&usp=drive_web#list

**Comment by zachbr** [comment]
@BoxmanCaleb any status on this?

**Comment by BoxmanCaleb** [comment]
Sorry about the delay, I have state testing this week. I'll surely began testing this week, sorry for the delay.

**Comment by zachbr** [comment]
If this issue continues on 1.9 please let us know
