### ISSUE TITLE
going through end portal glitches out your game

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#110]
probably a spigot bug, but if you go into the end portal that spawns in the end, you just end up with the screen "downloading terrain" forever and you can no longer play until the portal is broken

**Comment by Techcable** [comment]
Might be the don't display end credits patch.

**Comment by PhanaticD** [comment]
i have tried with and without, doesnt matter

**Comment by hurrgurl** [comment]
I'm on 504 and everything is working quite well, try downgrading?

**Comment by zachbr** [comment]
I'm going through the end portal consistently without issues on latest

**Comment by PhanaticD** [comment]
the issue is pressing the escape button while the end credits display does not teleport you to spawn, but instead you are still standing at the end portal in the end, and since you are standing in a end portal in the end the credits start rolling again, and so it repeats forever until the portal block is broken or your playerdata login location is changed

**Comment by hurrgurl** [comment]
Try changing your /setworldspawn maybe?

**Comment by zachbr** [comment]
This was fixed w/ 0363644455691d01d1e2e7ce20f029faa1f6fe2f
Just confirmed.
