### ISSUE TITLE
Minecraft packet processing high timings

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#1100]
Recently I've been trying to optimise my server as best as possible but for some reason the timings are showing Packet processing related stuff as really high. For example the PacketPlayInChat, PacketPlayInPositionLook, and PacketPlayInPosition. Running Paper Build #1402

Here's a timings with roughly 200 players online: https://timings.aikar.co/?id=0c76faa4592444759499163a3b8405e2 I also get occasional lag spikes where player movement is frozen which I assume is related to the packet processing stuff.

Here's some profiler info since it is more in depth than timings: 
![systemutils](https://user-images.githubusercontent.com/10485646/39381652-bb624252-4a5a-11e8-8d23-8dae2bf8caba.png)
![networkmanager](https://user-images.githubusercontent.com/10485646/39381657-bf886802-4a5a-11e8-9357-590ae7ff9ca8.png)

I don't understand why network manager is so high either, what is going on with EntityHuman.B? I'm running a creative server.

**Comment by aikar** [comment]
It's all related to player movement.

This is generally summed up as "Your server can't support that many players"

I do not see any signs of an issue here.

About all you can do is either a faster CPU, or reduce your server cap.

**Comment by SecretlyJealous** [comment]
My server load is only at 20% though and I've got an Intel Xeon E5-1650v3 CPU which should be able to handle this, it just seems strange that player movement is the only thing that is acting up. Everything else besides from the packets I mentioned is running smoothly.

**Comment by Leymooo** [comment]
3.8ghz is low for survival server. 
For minigames this cpu is good, but for survival you need a 4.3+ghz. Like a 6700k or 7700k

**Comment by SecretlyJealous** [comment]
It's not a survival server, it's a creative server. The CPU usage never goes above 10%.

**Comment by electronicboy** [comment]
E5's are horrible for heavily populated, their single core performance is poor, which is shamefully where all of the business logic in MC sits, so unless you're running a few dozen instances and need the core count, I would consider jumping over to one of the newer i7's.

The Player position look packet is also concerned entirely around the process of checking that their move is valid and updating other clients; Maybe try reducing the player tracking range and making sure that players aren't moving around too fast for your server to handle, but at the end of the day, the workload is just getting too much to handle, my suggestions will potentially nudge off the inevitable, but you're looking to be at the limit of what that CPU is going to give you

**Comment by SecretlyJealous** [comment]
@electronicboy Thanks for pinpointing the issue to the CPU. I'm going to get an Intel Core i7-8700K @ 3.70GHz which I'm hoping should solve the issue.

**Comment by bloggy** [comment]
It will not solve your issue, trust me.
