### ISSUE TITLE
server crash - 3 versions behind

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Paper#1102]
3 versions behind on paper, not really sure what caused this.

[crash-2018-04-28_11.01.35-server.txt](https://github.com/PaperMC/Paper/files/1957843/crash-2018-04-28_11.01.35-server.txt)

Is there anything obvious? 

console log >
https://pastebin.com/9MTm3q7G

Thank you in advanced, i'm not sure if this is something we can resolve on our end. We recently enabled anti-xray although its unlikely related.

**Comment by electronicboy** [comment]
Something on the server is modifying player chunk maps async, this is pretty much guaranteed to be down to a plugin doing stuff it shouldn't

**Comment by Cobwebster** [comment]
Do any of these look like it could be the cause? 

https://gyazo.com/aa1c938763c12ce67353fe715886b338

I'm thinking maybe NoCheatPlus

**Comment by Cobwebster** [comment]
@electronicboy is there anyway to locate the plugin? it wasn't nocheatplus.

**Comment by Cobwebster** [comment]
I disabled anti-xray.

**Comment by Cobwebster** [comment]
located the issue, it was anti-xray related. paper.yml was missing the new option which was added so I guess it was looking to find it and found nothing and caused crashing.

**Comment by zachbr** [comment]
That's not how any of that works.

**Comment by Cobwebster** [comment]
The issue is for sure related to the anti-xray being enabled, the only thing I noticed was that it didn't have the new       update-radius: 2 in the file because we copied over the xray settings from our previous setup. If that doesn't matter then it could be a issue with the new anti-xray changes. not sure but our issue was resolved by disabling anti-xray via paper.

**Comment by zachbr** [comment]
As far as I can tell, you haven't actually sorted through your plugins, you just tinkered with the config and it hasn't happened in a while so the issue must be fixed.

That's not how we resolve issues so we will continue to ascribe this problem to a plugin for the time being.
Locking so we don't continue doing this "well it must be this" dance for the next six weeks.
