### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#1103]
git-Paper-1399

First crash in months, something to do with vanilla Minecraft?

https://pastebin.com/qxvAXDwm

**Comment by zachbr** [comment]
Please include your plugin list so we can cross-reference it with other reports.

Thanks.

**Comment by hurrgurl** [comment]
Had /timings running for about 6 hours before crash. 

Plugins are:
NCP, WG, ESS

I also make my own stuff. I went through crash logs before posting here. If I find something on my end I'll let you know right away.

Sorry but I don't have a whole lot to add to the crash report, at least not right now. :-(

**Comment by zachbr** [comment]
Configs?

**Comment by hurrgurl** [comment]
Configs are pretty much default gen spigot.

**Comment by zachbr** [comment]
@hurrgurl Im going to merge this ticket into GH-1104 as it seems to have had more discussion. They appear to share the same root issue.

Thanks for your report
