### ISSUE TITLE
Anti-Xray causing CME

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Paper#1104]
I created an issue yesterday explaining a crash issue, there was a lot of focus on random plugins but it seems it is the result of anti-xray being enabled via paper. (It got closed because it got assumed we randomly found a solution when we didn't. We just disabled anti-xray)

Same logs and errors as posted here https://github.com/PaperMC/Paper/issues/1102

We disabled anti-xray and we get no crash issues, we enable it with the new feature and it crashes within the hour. 

I'm just making this final report so you can see that I was able to confirm it directly ties with the anti-xray setup. Whether or not its a fault with a plugin not working with the anti-xray or the other way round is beyond me, We're using pretty standard plugins so if its a plugin you'll prob get this report a lot. We're just gonna leave it disabled for now, do what you want with this issue. I assume it might come up a lot. Hopefully the info provided will help in some way.

    anti-xray:
      enabled: false
      engine-mode: 2
      chunk-edge-mode: 3
      max-chunk-section-index: 3
      hidden-blocks:
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - redstone_ore
      - lit_redstone_ore
      - clay
      - emerald_ore
      - ender_chest
      replacement-blocks:
      - stone
      - planks
      update-radius: 2

**Comment by zachbr** [comment]
can you re-test with update-radius set to 1?

**Comment by Cobwebster** [comment]
Sure, we'll wait for our reboot and change it to that setting and see if it crashes again.

**Comment by stonar96** [comment]
I will also take a look at this later.

I don't think that it's related to the update radius. Can you please test with chunk-edge-mode 1?

**Comment by stonar96** [comment]
`PlayerChunkMap` line 123 to 130:

            Iterator iterator = this.f.iterator();

            while (iterator.hasNext()) {
                playerchunk = (PlayerChunk) iterator.next();
                playerchunk.d();
            }

            this.f.clear();

Maybe `playerchunk.d();` modifies the `Set<PlayerChunk> f` in some way, which would cause the CME. Indeed Anti-Xray might load chunks in chunk-edge-mode 3 inside this method. I am not sure at the moment if this can cause changes in the `Set<PlayerChunk> f`. I will check that out. In case of doubt we can also just remove the line which loads the chunks inside this method, because nearby chunks are probably loaded anyway in this case.

**Comment by Cobwebster** [comment]
Could be a little early to report this but these settings haven't made us crash yet,

    anti-xray:
      enabled: true
      engine-mode: 2
      chunk-edge-mode: 1
      max-chunk-section-index: 3
      hidden-blocks:
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - redstone_ore
      - lit_redstone_ore
      - clay
      - emerald_ore
      - ender_chest
      replacement-blocks:
      - stone
      - planks
      update-radius: 1

**Comment by stonar96** [comment]
@Cobwebster thanks for testing so far. As I have already mentioned in #1105 I think it's related to the chunk-edge-mode setting. update-radius: 2 (which is default) and chunk-edge-mode 1 should be safe to use at the moment. I will try to find out what exactly causes the issue.
