### ISSUE TITLE
Make the number of skeleton horses that spawn in storms configurable

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#111]
![2016-03-20_17 40 59](https://cloud.githubusercontent.com/assets/8324198/13905544/f6df4b86-eec2-11e5-855a-b011edf08807.png)

**Comment by zachbr** [comment]
Pretty sure this is plainly the result of vanilla. I remember talking about it right after Mojang released 1.9 vanilla.

**Comment by Puremin0rez** [comment]
Vanilla Issue. The chances that they spawn from lightning should probably be configurable though.

**Comment by andris155** [comment]
Thanks!

**Comment by SmallSansSerif** [comment]
So what's a good number here to try as it seems like these spawn a lot? What's the vanilla percentage? 

skeleton-horse-thunder-spawn-chance: -1.0

**Comment by zachbr** [comment]
There is no singular 'vanilla percentage' it's based on their difficulty scale that slowly increases as you spend more time in a world and varies based on the server's difficulty setting. Not sure _why_ they did that, but they did. Telling it -1.0 is just our thing for making the server use that vanilla value. I'd personally just start playing around until you find a sane value
