### ISSUE TITLE
Crash Server IndexOutOfBoundsException

### ISSUE THREAD

**Issue by fhebuterne** [PaperMC/Paper#1110]
Hello,

Today, my serveur was crash, i've see some error in logs, i've put all errors on a pastebin.
I have already had this error during a previous crash.

Could you fix this bug please ?

# Crash, Stacktrace

### Link/paste of stack trace

https://pastebin.com/raw/e6msuMKq

### Paper build number: 1402

Thank's

**Comment by electronicboy** [comment]
You have a bad chunk somewhere in the world which basically has too much information in there, shamefully there isn't much we can really do about this, you'll need to attempt to locate the chunk and clean it up in mcedit or something
