### ISSUE TITLE
Chat message validation failure when send message in 1.21

### ISSUE THREAD

**Issue by NoNameGMM** [PaperMC/Paper#11111]
### Expected behavior

be nomal(

### Observed/Actual behavior

[14:21:51 WARN]: Failed to validate message acknowledgements from XXX
[14:21:51 INFO]: XXX lost connection: Chat message validation failure
[14:21:51 INFO]: XXX left the game

### Steps/models to reproduce

When player press "T" to send something
he will be kicked because of Chat message validation failure

### Plugin and Datapack List

**Plugins**:  CoreProtect, GrimAC, GSit, ImageFrame, LuckPerms, MOTD, MultiLogin, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, nAntiBot, OpeNLogin, Orebfuscator, PlaceholderAPI, PlugManX, Points, ProtocolLib, SkinsRestorer, spark, *TPAPro, UltraSetHome, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, Vulcan

**Datapack**: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]

### Paper version

This server is running Paper version 1.21-93-master@d08e8d1 (2024-07-18T22:39:15Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-89-44c3dd0 (MC: 1.21)

**Comment by lynxplay** [comment]
Can you attempt to replicate this without plugins please?
Sending chat messages works fine for me on 1.21.

**Comment by NoNameGMM** [comment]
I tried to unload CoreProject then it don't have this bug now

thanks.
