### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Phyther** [PaperMC/Paper#1111]
# Crash, Stacktrace

### Link/paste of stack trace
https://pastebin.com/9vMEnigY

### Plugin list:
https://pastebin.com/sxU2prsi
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
1403

**Comment by electronicboy** [comment]
Watchdog reports are generally unreliable and could mean that something before that caused the server to not tick for too long, e.g. a plugin checking for updates improperly; Watchdog is pointing towards leaderheads as having been doing something when the server crashed, so might be worth looking there first.

**Comment by Phyther** [comment]
Thank you.
