### ISSUE TITLE
Stackable items

### ISSUE THREAD

**Issue by madtomic** [PaperMC/Paper#1114]
Any chance you guys would add stackable items for non stackable items such as potion or water bottle?

**Comment by 0-x-2-2** [comment]
you can do this with a plugin.

**Comment by zachbr** [comment]
see https://github.com/PaperMC/Paper/issues/221

This sort of thing introduces all sorts of behavioral issues and inconsistencies around the server that need to be carefully examined and resolved. I don't see this happening anytime soon.
