### ISSUE TITLE
gamerule maxEntityCramming doesnt work without a solid block

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#1118]
The gamerule maxEntityCramming doesnt work for mobs that are contained in a 1x1 space without a solid block underneath them. This enables huge mobfarms -> server lags. 
An example for this bug is a cave-spider-fam. The spiders are swept into a 1*1 cavity, scramble up and get stuck under an iron fence. The gamerule maxEntityCramming doenst detected the huge accumulation of those spiders.
Screenshot: https://imgur.com/a/PDLa1J2
video: https://www.youtube.com/watch?v=UulK0D6CCtQ
PaperSpigiot 1.12.2 - 1404

**Comment by RoboMWM** [comment]
And you've tested this in vanilla?

**Comment by TheoRetisch1** [comment]
I tested it right now and it seems like it doesn't work in vanilla either :(. Sad story.

**Comment by RoboMWM** [comment]
Should check for a ticket in vanilla's issue tracker and link it here then c:
