### ISSUE TITLE
Bug? Compiling issues

### ISSUE THREAD

**Issue by Shnatta** [PaperMC/Paper#1119]
### Compiling a jar
So, yesterday I tried to compile my own jar for my own personal needs but it simply doesn't produce the third jar (remapping jar)

To create an editable jar I do:
```
git clone https://github.com/PaperMC/Paper
cd ./Paper
git checkout ver/1.8.8
./build.sh --jar
```

Then I make my necessary changes in folder called '**Spigot-Server**'

Then I do
```
cd <path where I changed a .java class>
git add <.java class>
git commit -m "Message"
```

Then I head back to the root directory
```
cd /Desktop/Paper
mvn clean install
```

Everything seems to be installed but I cannot find the remmaped jar

```
[INFO] --- specialsource-maven-plugin:1.2.1:remap (default) @ paperspigot ---
[INFO] Replacing original artifact with remapped artifact.
[INFO] Replacing /Users/jonathand/Desktop/Paper/PaperSpigot-Server/target/paperspigot-1.8.8-R0.1-SNAPSHOT.jar with /Users/jonathand/Desktop/Paper/PaperSpigot-Server/target/paperspigot-1.8.8-R0.1-SNAPSHOT-remapped.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ paperspigot ---
[INFO] Installing /Users/jonathand/Desktop/Paper/PaperSpigot-Server/target/paperspigot-1.8.8-R0.1-SNAPSHOT.jar to /Users/jonathand/.m2/repository/org/github/paperspigot/paperspigot/1.8.8-R0.1-SNAPSHOT/paperspigot-1.8.8-R0.1-SNAPSHOT.jar
[INFO] Installing /Users/jonathand/Desktop/Paper/PaperSpigot-Server/dependency-reduced-pom.xml to /Users/jonathand/.m2/repository/org/github/paperspigot/paperspigot/1.8.8-R0.1-SNAPSHOT/paperspigot-1.8.8-R0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] PaperSpigot-Parent dev-SNAPSHOT .................... SUCCESS [  1.141 s]
[INFO] PaperSpigot-API 1.8.8-R0.1-SNAPSHOT ................ SUCCESS [ 18.425 s]
[INFO] PaperSpigot 1.8.8-R0.1-SNAPSHOT .................... SUCCESS [01:23 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:43 min
[INFO] Finished at: 2018-05-12T07:20:39+02:00
[INFO] ----------------------------------------------------------------------
```

If anyone could help me or have any suggestions on where it could be, please comment below!

**Comment by electronicboy** [comment]
`/Users/jonathand/Desktop/Paper/PaperSpigot-Server/target/paperspigot-1.8.8-R0.1-SNAPSHOT.jar`
if the jar isn't there, try running maven outside of the desktop.

**Comment by Shnatta** [comment]
Well, when I check the `/Users/jonathand/Desktop/Paper/PaperSpigot-Server/target/paperspigot-1.8.8-R0.1-SNAPSHOT.jar` in JD-GUI my changes don't seem to apply?

I edit one line in one the classes found in  Spigot-Server, then I save the document. Then I close the document and cd <document-locatoin> where I do cd git add <class>. Then I type git commit -m "I have changed blah blah blah" then I cd /Desktop/Paper and type mvn clean install. I do get 2 jars but none of them has the changes I made if I look it up with JD-GUI.

**Comment by electronicboy** [comment]
You don't edit spigot sources when trying to edit paper, Please read the documentation for the project, this issue tracker is also for issues with supported versions of the server software, not for compilation help.

**Comment by MiniDigger** [comment]
adding to what electronicboy said, for help with complication you may find more success in irc or discord (https://paperdiscord.emc.gs)

**Comment by Shnatta** [comment]
Thanks to both, I figured it out 👍
