### ISSUE TITLE
lost connection: Failed to verify username!

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [PaperMC/Paper#11193]
### Expected behavior

Successfully jumped to server 2.

### Observed/Actual behavior

![image](https://github.com/user-attachments/assets/758c97aa-d81b-4d2f-9335-8da34f30c6d3)
![image](https://github.com/user-attachments/assets/6d33bb26-bfe0-480b-a9d4-826554a8888c)

### Steps/models to reproduce

1. Use bungee to connect two servers, in which bungee has a geyser installed on it.

2. Players use the Bedrock client to enter the No.1 server under the name of [BE]TLKExcavator, which is very normal at this time! Right? !

3. I tried to enter the No.2 server, and an accident happened at this time-No.2 server wouldn't let me in! !

### Plugin and Datapack List

![image](https://github.com/user-attachments/assets/cfa2c93e-d501-4031-890b-75ebc1d050ce)

### Paper version

> version
[00:54:35 INFO]: Checking version, please wait...
[00:54:36 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-Purpur-2095 (MC: 1.20.2)

**Comment by powercasgamer** [comment]
1.20.2 is not supported.

**Comment by electronicboy** [comment]
We do not support 1.20.2 or protocol hacks, failed to verify username would suggest an issue with your means of supporting BE clients

**Comment by MinecraftEarthVillage** [comment]
> 我们不支持 1.20.2 或协议黑客攻击，无法验证用户名表明您支持 BE 客户端/代理的方式存在问题

So what if I switch to a JAVA client?

Still can't get in?

**Comment by electronicboy** [comment]
> Failed to verify username!

Implies that your server is not configured properly for proxies, but, this is not a support forum (nor are you using a supported version)

**Comment by MinecraftEarthVillage** [comment]
> > Failed to verify username!
> 
> Implies that your server is not configured properly for proxies, but, this is not a support forum (nor are you using a supported version)

The problem now is: as long as there are symbols in the name, you can't redirect the server. The compatibility of user names in your is so poor that even mohist can let Chinese names and even names with various strange symbols in, and there has never been a BUG.

**Comment by MinecraftEarthVillage** [comment]
If I remove [ and ], I can go in and out freely.

**Comment by electronicboy** [comment]
The only extra check we have vs vanilla can be disabled in the unsupported section of the global config

**Comment by MinecraftEarthVillage** [comment]
LOW
VERYLOW
![image](https://github.com/user-attachments/assets/3a0bddd7-ea73-491d-a41c-8d235156b00d)
