### ISSUE TITLE
Issue standards

### ISSUE THREAD

**Issue by Ichbinjoe** [PaperMC/Paper#112]
I feel we should document proper issue report styling to help cut down on bad issues (including plugin related issues, not submitting the timings link directly for server performance issues, etc)

This is purely an idea, and looking for input on the thought.

**Comment by zachbr** [comment]
Perhaps we could this in combination with the issue templates feature GitHub rolled out recently?
Might make it easier for newer users to provide useful information.

https://github.com/blog/2111-issue-and-pull-request-templates
