### ISSUE TITLE
Why can't you save player data?

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [PaperMC/Paper#11201]
### Expected behavior

These strange red words should not appear.

### Observed/Actual behavior

![image](https://github.com/user-attachments/assets/cb884412-d10e-43d0-97b4-c06457e5e07c)

### Steps/models to reproduce

I ~ don t~ know ~ ~ This is just an ordinary server.

### Plugin and Datapack List

 AnimatedScoreboard, AuthMe, ChestCommands, *ChineseNickName, Citizens, CMILib,
*CommandNPC, ConsoleSpamFix, CoreProtect, dynmap
[12:50:28 INFO]:  Essentials, HideAndSeek, HolographicDisplays, LaggRemover, LibsDisguises, *LiteCu
stomAnnouncer, LuckPerms, Multiverse-Core, NoSpawnChunks, PlaceholderAPI
[12:50:28 INFO]:  PlugManX, ProtocolLib, Residence, *Shift_Menu, SkinsRestorer, TabTPS, TrChat, Vau
lt, ViaBackwards, ViaRewind
[12:50:28 INFO]:  ViaVersion, WorldBorder, WorldEdit

### Paper version

[12:59:52 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-Purpur-2095 (MC: 1.20.2)

### Other

Don't tell me that "to update" 1.20.4 and 1.21, I don't watch the junk version whose compatibility has exploded so far.

**Comment by powercasgamer** [comment]
1.20.2 is not supported anymore. We also do not support offline mode.Also follow the issue template next time you’re on a supported version and provide the latest.log file.

**Comment by electronicboy** [comment]
Your OS blew up renaming a file, with an error which I cannot read. You would need to diagnose why your system blew up, we probably can't do much here.
