### ISSUE TITLE
(!) PaperSpigot Issues Velocity Log-Spam [PLEASE-READ]

### ISSUE THREAD

**Issue by FresterEx** [PaperMC/Paper#1127]
My server using Paperclip-1.10.2 when active Velocity of plugin like a LaundPads or MythicMobs having error! please fixed because is very important! 

Log: https://pastebin.com/k1WwZxb2 
Tags > @aikar

**Comment by electronicboy** [comment]
You're running an unsupported version of the server software which we have no intention to touch. You have a plugin that is setting an entity to a velocity which is above what we consider safe and potentially going to cause a crash.

**Comment by aikar** [comment]
Note that updating Paper does resolve your issue. It no longer logs in the latest version.

**Comment by FresterEx** [comment]
But i need at 1.10.2? pls fix them? whyyyyyyyyyyyyyyyyy

**Comment by aikar** [comment]
No you don't. 10 has nothing special over 12
