### ISSUE TITLE
CraftWitch being cast to Player

### ISSUE THREAD

**Issue by JamieSinn** [PaperMC/Paper#1129]
https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/775

git-Paper-1417 (MC: 1.12.2)

Timings of the event:
https://timings.aikar.co/?id=8cab5b2468744dd4b68a23ccce221153

**Comment by aikar** [comment]
doh sorry about that. I thought it was EntityHuman, so casted to player. Will try to fix tonight.
