### ISSUE TITLE
Newest Build Breaks Skript! --> java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData

### ISSUE THREAD

**Issue by artfcl-intlgnce** [PaperMC/Paper#1134]
### What behaviour is expected:
___What you expected to see___
Skript to load

### What behaviour is observed:
___What you actually saw___
Skript did not enable

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Run Latest Version of paperclip and use Skript
Restart Server

### Plugin list:
Don't judge :)
AttackSpeedRemover version 2.1.4
MinePacks version 1.17.8
Vehicles version 9.3.2
ColorConsole version 2.3.3
PlugMan version 2.1.4
TigerReports version 4.1.6
LuckPerms version 4.2.17
FirstJoinPlus version 2.4.1
Skript version 2.1.2
FastCraft version 2.0.3
SpyPlusPlus version 1.0
CommunityChest version 1.6
ProtocolLib version 4.3.0
Multiverse-Core version 2.5-b719
MVdWPlaceholderAPI version 2.5.1
FastAsyncWorldEdit version 18.05.25-4049014-1138-20.1.8
Vouchers version 1.6.5.3
Advanced_Drop_Party version 1.8.9
VoidGenerator version 1.2.0
mcMMO version 1.5.10-SNAPSHOT
ColoredSigns version 1.1.0
StaffMonitor version 1.4
PlaceholderAPI version 2.8.7
DeluxeCommands version 1.7.0
ForceField version 3.2
TitleAPI version 1.7.5
DailyLootbox version 1.7
LagMonitor version 1.17
ShutdownNotice version 3.1
CoreProtect version 2.14.2
LagAssist version 1.10.4
Wild version 3.14.1
VoteRoulette version 3.2.3
WorldEdit version 6.1.7;dd00bb1
BackupLikeMe version 0.1.1
CrackShot version 0.98.7
WorldBorder version 1.8.7
HeapDump version 1.4.0
Votifier version 2.3.7
BannerBoard version 1.9.9
LibsDisguises version 9.5.1
BlowableObsidians version 4.5
eZProtector version 4.2.4
CrackShotPlus version 1.7
ParticleProjectileApi version 0.1.2
Vault version 1.6.6-b${env.TRAVIS_BUILD_NUMBER}
DrugMeUp version 1.1.1
TitleAdvanced version 6.1.0
EpicRename version 3.3.1
CreativeParkour version 2.11.8
ParticleGrenades version 0.2.1
HolographicDisplays version 2.2.6
WiiPay version 1.5.2
ChatItem version 1.3.6.4
PlayerVaults version 4.0.5
MyCommand version 5.3.4
BountyHunters version 1.4.7
mcMMOAction version 2.3.2
Statscraft version 1.2.0
CrackShotAdditions version 1.0.9
Citizens version 2.0.22-SNAPSHOT (build 1536)
CrazyAuctions version 1.2.4
TrollCommandsPlusPlus version 6.28.53
ChatGames version 1.0
ParrotAnnouncer version 1.8
Trading version 3.2
WorldGuard version 6.2.1;84bc322
Brewery version 1.5
WanderingNPC version 1.7
EZPrestige version 1.2.2
CratesPlus version 4.4.5
AreaShop version 2.4.0
Essentials version 2.15.0.9
CrazyAuctionsAnnouncer version 1.1
McMMOExtras version 5.3.2
SuperVanish version 6.0.5
EnjinMinecraftPlugin version 3.4.3
AuthMe version 5.4.0-b1877
EnchantsPlus version 1.7.4a
EssentialsGeoIP version 2.15.0.9
CommandNPC version 1.9.1
Jobs version 4.5.3
dtlTraders version 4.0.5
Sentinel version 1.4.5 (build 165)
EssentialsChat version 2.15.0.9
WorldGuardExtraFlags version 3.0.4
SharpSK version 1.6.3
BeastCore version 1.0-SNAPSHOT
CMI version 7.7.10.1
EZRanksPro version 1.7.1
FactionsTop version 5.0.12
Factions version 1.6.9.5-U0.2.1-RC-1.4-BETA-2
BungeeTabListPlus version 2.8.4
VentureChat version 2.12.2
MobHunting version 5.6.3
FactionsTopv5Hologram version 1.0.4
FactionsTopv5ChangeAnouncer version 1.0.2
DiscordSRV version 1.16.3
XPboost version 1.95
AdvancedAchievements version 5.7.4
MentionMe version 0.4.2
LeaderHeads version 3.1.8.1
McDuels version 15.0.0
BossShopPro version 1.9.8
ItemShops version 1.0.8

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-1430 1.12.2

### Anything else:
___Anything else you think may help us resolve the problem___
```
java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B
	at ch.njol.skript.util.Color.<clinit>(Color.java:82) ~[?:?]
	at ch.njol.skript.SkriptCommand.<clinit>(SkriptCommand.java:60) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:254) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1430]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1430]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1430]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1430]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1430]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1430]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1430]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1430]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [patched_1.12.2.jar:git-Paper-1430]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1430]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]```

**Comment by zachbr** [comment]
Your version of Skript was released in 2014.
2014!

Update it! https://github.com/SkriptLang/Skript/releases

**Comment by artfcl-intlgnce** [comment]
Was just coming on to close the ticket with same conclusion - sorry for the trouble
They should prob update their Bukkit page to point to the new builds
https://dev.bukkit.org/projects/skript
`The latest version of Skript is 2.1.1 (11 March 2014)`

**Comment by zachbr** [comment]
no worries!
