### ISSUE TITLE
/locate command not working with OTG/Biome Bundle

### ISSUE THREAD

**Issue by CGDoctor8** [PaperMC/Paper#1135]
### What behaviour is expected:
/locate to find a mansion 

### What behaviour is observed:
Unable to locate any Mansion feature
(Dose not happen on spigot or bukkit )

### Steps/models to reproduce:
Install Paper Spigot
Install [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator)
Install [Biome bundle](https://minecraft.curseforge.com/projects/biome-bundle) do not forget to follow the directions under "Spigot Server" found [here](http://openterraingen.wikia.com/wiki/Installing_Worlds)
Try to use the /locate command

### Plugin list:
Open Terrain Generator

### Paper build number:
git-Paper-1431
latest 

### Anything else:
I don't think seed has anything to do with it but if so
-4661749536751046939
Mansion at | X: 1919 Z: -2427

**Comment by CGDoctor8** [comment]
This seems to also effect villager trading from the Cartographer he will never unlock either of the special maps

**Comment by mikroskeem** [comment]
Try reporting this issue to OTG issue tracker.

**Comment by CGDoctor8** [comment]
Well it works on Bukkit & Spigot wouldn't this classify as a paper issue?

**Comment by electronicboy** [comment]
This is a bit of a misnomer on our side from what I can see, appears that something is missing up how structure info is loaded/populated or something, needs looking into, but potentially worth asking if they've seen it before

**Comment by TheFinestSurgeon** [comment]
![about this well](https://user-images.githubusercontent.com/16968048/40884495-4fdd51d0-66c9-11e8-9fbc-e283e486ccc1.png)

**Comment by BillyGalbreath** [comment]
Can confirm feature works in Spigot but not Paper.

Paper http://i.imgur.com/J0jSQN2.png

Spigot http://i.imgur.com/RvRyqcX.png

**Comment by Proximyst** [comment]
The underlying issue here seems to either be fixed, or plugin-specific. Using Terra with its default settings, it can find strongholds and jungles, but not mansions (because I'm not near one? because the terrain generator doesn't generate them?). I also can't verify this on 1.16, as the plugin referenced is not updated to support it. I'd say this is safe to close; open a new issue if this is still an issue with an up-to-date world generator.
