### ISSUE TITLE
Minecraft 1.7.10 (tekkit and ftb)

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1136]
I Currently have a Tekkit legends server running with thermos (forge and spigot) but as Tekkit has so many things going on with the machinery Ive been trying to do everything I can do to make a less laggy experience for my server. Right now I'm running 100% on busy days on one of the cores and 20% on the other cores.

Is there any way i could compile Paper to work back with Minecraft 1.7.10 and maybe if possible use HOSE to enable Multi-core tic processing?

I might be willing to pay.

**Comment by electronicboy** [comment]
no.
