### ISSUE TITLE
Problem: Crash Server

### ISSUE THREAD

**Issue by KoTEHoChek** [PaperMC/Paper#1137]
i'm russian
https://hastebin.com/oqijutivim.md

**Comment by Leymooo** [comment]
Обнови  эссентиалс, про спавн тоже не забудь.

**Comment by Black-Hole** [comment]
Plugin issue with Essentials or EssentialsX. You should update to a recent version of EssentialsX.

**Comment by electronicboy** [comment]
Update EssentialX.
