### ISSUE TITLE
chunks not unloading

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#1138]
after this commit https://github.com/PaperMC/Paper/commit/e74e4584d6d1bd10a4d6929a0f1d90fb66fc0f69

chunks no longer unload, entities stay loaded and over time this can cause some bad performance for obvious reasons

**Comment by aikar** [comment]
Ah crap this is valid. The change used the wrong method for looking up chunks for Tile Entities and its tripping the active counter.

Fixing

**Comment by aikar** [comment]
actually, looks like its using a method that SHOULD be behaving correctly, but spigot changed the behavior of that method recently. fixing the method used instead.

**Comment by aikar** [comment]
Fixed in 1432+
