### ISSUE TITLE
I suddenly am removed from the server but still on

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#114]
This happens in my hub, I will be standing around minding my own business when all of a sudden everyone disappears and I cannot chat https://gyazo.com/7312788ef06487bbdbbb2b1dd54405d7 and i am not on tab list, however i still see the world. no errors in console, and relogging fixes it

**Comment by PhanaticD** [comment]
this has something to do with my player stacker plugin, which spawns a invisible slime, mounts it on your head then mounts a player on top of the slime. This issue does not happen with that plugin removed

**Comment by PhanaticD** [comment]
rider point of view: https://gyazo.com/c29dd2c7053a5f419630946e1d3f6057
vehicle point of view: https://gyazo.com/57f2b6e0750f83f3fbb1be5578756b5c
third party point of view: https://gyazo.com/326f605da8df8e7599027184694ac290

as you can see the vehicle point of view is screwed up, and the vehicle player is the one this ends up happening to (when the rider leaves the server)

**Comment by PhanaticD** [comment]
okay so the actual cause of all this is most likely an issue with new 1.9 passengers/riding, it was identified here https://www.spigotmc.org/threads/spigot-1-9-player-setpassenger-help.130324/

**Comment by PhanaticD** [comment]
okay so the actual cause of all this is most likely an issue with new 1.9 passengers/riding, it was identified here https://www.spigotmc.org/threads/spigot-1-9-player-setpassenger-help.130324/

**Comment by willies952002** [comment]
Could you please provide the name of/a copy of/a link to the stacker plugin you are using to produce this issue? This will help us find and fix the issue easier :smiley:

**Comment by PhanaticD** [comment]
its actually a commandhelper script http://forum.enginehub.org/threads/player-stacker-script-not-working-on-1-9.16621
