### ISSUE TITLE
paper building failed

### ISSUE THREAD

**Issue by Fchen48** [PaperMC/Paper#1142]
### What behaviour is expected:
___What you expected to see___
I expected a compiled jar file.

### What behaviour is observed:
___What you actually saw___
I doesn't saw a compiled jar file

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Entering ```./paper jar```

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
latest commit from master branch

### Anything else:
___Anything else you think may help us resolve the problem___
Jenkins check everyday if there is a new commit, if there is anything new jenkins will checkout and perform ```./paper jar``` but since 4 days I will receive this error:  

    Downloading unmapped vanilla jar...
    Applying class mappings...
    Applying member mappings...
    Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at net.md_5.ss.SpecialSource.map(SpecialSource.java:69)
        at net.md_5.ss.SpecialSource.main(SpecialSource.java:44)
    Failed to build Paper

System is up-to-date

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.4 LTS
    Release:        16.04
    Codename:       xenial

nothing changed with java and zip/unzip the last few days.

    $ java -version
    java version "1.8.0_171"
    Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
    Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by electronicboy** [comment]
Corrupted jar, apparently.

**Comment by Fchen48** [comment]
I tried to delete the whole workspace and re-issued a build.  
Which jar is corrupted? Still saying "corrupted jar" is in no way helpful, and why is it closed?

**Comment by electronicboy** [comment]
Because your issue is not a paper issue, This issue tracker is for actual issues with the software, not your build environment.

The jar that is going to be broken at that stage is likely the mapped jar inside of the work directory. If you want help with build issues, you're much better off attempting to get support on the IRC/Discord.

**Comment by electronicboy** [comment]
`version-cl` is likely to be the broken jar at that point, unless for some reason your system failed to open `version-m` for some reason
