### ISSUE TITLE
1.8.8 bug (invalidconfigurationexception)

### ISSUE THREAD

**Issue by grrocks** [PaperMC/Paper#115]
https://www.spigotmc.org/threads/invalidconfigurationexception-when-the-config-is-perfect.131534/

As you could see in that thread (look at the last comment by me also) there is a issue with loading Configs and it is just from the latest version of paperspigot I have tried 1.8.7 paperspigot and it works perfectly fine.

**Comment by zachbr** [comment]
All development focus is on 1.9
