### ISSUE TITLE
"Silently" catching entity tracking error

### ISSUE THREAD

**Issue by ytnoos** [PaperMC/Paper#1151]
### Link/paste of stack trace
https://pastebin.com/L9RB0M7W

### Plugin list:
Custom plugins + EffectLib, ProtocolLib, ProtocolSupport, ProtocolLegacySupport

### Actions to reproduce (if known):
I have 2 custom plugins, the first spawns some fallings cake with the method World#spawnFallingBlock(Location, MaterialData), the second spawns an invisible armorstand (hologram) with WorldServer#addEntity(net.minecraft.server.Entity, SpawnReason)

I think it isn't a problem of my plugin but some bug never fixed from spigot

### Paper build number:
Paper version git-Paper-ec071b6b (MC: 1.12.2) (Implementing API version 1.12.2-RO.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Either something is messing with entity IDs or you've got issues elsewhere, that jar isn't provided by us (Custom modifications?)

**Comment by ytnoos** [comment]
Well yes, we forked Paper and modified something but we didn't touch anything about entity IDs, world and chunks

**Comment by QuickGlare** [comment]
We've only disabled world saving and disabled redstone

**Comment by QuickGlare** [comment]
I've fixed updating at the latest commit

**Comment by electronicboy** [comment]
Entity ID is assigned when the entity is created:

```
public Entity(World world) {
        this.id = Entity.entityCount++;
```
The only way in which a duplicate ID would exist is that something has set the ID of the entity overriding what the server set, or something is spawning entities async and causing duplicate IDs

**Comment by aikar** [comment]
this error is never due to dupe entity ids, but caused when something causes 2 track commands to be sent.

ive seen it plenty of times in odd ball bug cases. theres no 1 deterministic way to discover whats wrong with this stack.

You neeed to restart your server with  -XX:-OmitStackTraceInFastThrow  so we can see the full stack trace.

**Comment by ytnoos** [comment]
I started with the parameter you said but the exception isn't full (new https://hastebin.com/ugosefucen.vbs)
Btw now i can make this bug happens, i have a zombie NPC (nms) with an armorstand on his head that spawns and despawn ever 2-3 seconds, when i spawn the falling cakes (BirthdayBombing) there's a probability (about 1/10 times) that the zombie disappears throwing this error.
