### ISSUE TITLE
Can you prevent ctrl+c from stopping the server instance.

### ISSUE THREAD

**Issue by andrewkm** [PaperMC/Paper#1152]
ctrl+c is the death of my soul.

Accidentally having my testing environment console selected and running ctrl+c (windows 10) basically runs the server stop command.

Doesn't happen in Bungee's java instance, so must be a thing controlled by Spigot/Paper's java instance.

Can you get us a config option to prevent ctrl+c going through?

**Comment by zachbr** [comment]
Maybe a system property like Dsuppress.sigint but I'd be hesitant to add a config option just because you can't not press CTRL+C in your terminal.

**Comment by electronicboy** [comment]
For me, it took me a while to learn, but I kinda just eventually picked up on not sending ctrl-c to my server process...

Seems like a trivial thing to do, just needs a consensus from the rest of the team, I also agree on the thought of it not being a config option, sigint is a pretty standard signal for a process to send to safely kill something (before being more forceful if the software doesn't respond to that in time), seems somewhat of a dangerous option

**Comment by BillyGalbreath** [comment]
I'm not sure removing an emergency brake from a car is the proper response to having a habit of randomly pulling that emergency brake..

**Comment by RoboMWM** [comment]
Can't exactly recall, but there's been times where the console input wouldn't be responsive yet a Ctrl-C does the trick to get it to shutdown safely.

**Comment by andrewkm** [comment]
@BillyGalbreath good analogy lol, just that the emergency break is only used for mainly one thing in the car, while ctrl+c is sometimes used dozens of times a day for required tasks. Nonetheless, I was just very salty about having it happen recently few times in a row. xD Closing issue.

**Comment by aikar** [comment]
I think a good potential improvement here is an option that requires you press it twice in succession. People trying to copy and paste generally wouldnt do that.
It's a concept used in some REPL's to "confirm" the action.

**Comment by DenWav** [comment]
I have this issue too, but the fix is very easy and shouldn't be server-level. Just set your start-up script like so:

```bash
trap '' INT
java <...> -jar paperclip.jar
trap - INT
```

This tells bash to ignore SIGINT, executes the Java command (the Paper server), then once that's completed, tells bash to stop ignoring SIGINT. It's shell-level, rather than in Java.

---

Re-reading the issue, it looks like you're in Windows. It looks like you can accomplish the same thing in a bit of a different way using batch scripts: https://stackoverflow.com/a/36953316/2353230

**Comment by megapro17** [comment]
https://stackoverflow.com/questions/59920097/ignore-ctrlc-in-delay-powershell

**Comment by GrenFlem** [comment]
> I'm not sure removing an emergency brake from a car is the proper response to having a habit of randomly pulling that emergency brake..

Uh.. it is when its ALSO the thing that copies selected text...

**Comment by GrenFlem** [comment]
having ctrl+c as a shutdown shortcut would be the same as having ctrl+v a computer restart shortcut when no textbox is selected.

its dumb and a would be, but in this case it IS a HUGE oversight.

**Comment by mbax** [comment]
A solution has already been provided for people unfamiliar with how this sort of stuff works, @GrenFlem : https://github.com/PaperMC/Paper/issues/1152#issuecomment-398623691

This was provided many, *many* years ago. Please be sure to read issues in full before responding - there is no rush! 😊
