### ISSUE TITLE
Configurable shield delay

### ISSUE THREAD

**Issue by AoElite** [PaperMC/Paper#1153]
There's a delay on shields before they actually block hits & projecticles. It's hard coded into the game and making it configurable would be a lovely addition to paper. The default delay value is 5 ticks (0.25s), which is located in the `EntityLiving.class` in the `isBlocking()` method.

```java
    public boolean isBlocking() {
        if (this.isHandRaised() && !this.activeItem.isEmpty()) {
            Item var1 = this.activeItem.getItem();
            if (var1.f(this.activeItem) != EnumAnimation.BLOCK) {
                return false;
            } else {
                return var1.e(this.activeItem) - this.bp >= 5;
            }
        } else {
            return false;
        }
    }
```

**Comment by BillyGalbreath** [comment]
Is this asking for an API addition or paper.yml addition?

**Comment by AoElite** [comment]
It could be either but having it configurable in paper.yml would be nice.

**Comment by hafarooki** [comment]
Oh so THAT'S where that delay comes from!
