### ISSUE TITLE
java.lang.AssertionError: TRAP

### ISSUE THREAD

**Issue by HYPExMon5ter** [PaperMC/Paper#1156]
### Stacktrace:
https://hastebin.com/oxugaqiwix.vbs

### Plugin list:
![image](https://user-images.githubusercontent.com/12315186/41503983-707b7246-71af-11e8-9404-bef972f496f1.png)

### Actions to reproduce (if known):
Not sure how to reproduce.

### Paper build number:
![image](https://user-images.githubusercontent.com/12315186/41503994-a4aa03d4-71af-11e8-9795-33d9e428222a.png)

**Comment by aikar** [comment]
This is 100% caused by a plugin manipulating the count when vanilla is also manipulating it.

Try removing plugins to see when the issue stops occurring.

Stack trace deals with using a fire charge
