### ISSUE TITLE
Kicked due to keepalive timeout

### ISSUE THREAD

**Issue by Gaurav99** [PaperMC/Paper#1157]
This issue is happening on all of our servers on our network -- not just on login or switching servers, but randomly while players are switching servers. We reduced our view-distance to 4, that didn't help. It happens to players regardless of client version, region, ping, or whether or not they're AFK.  Sometimes, players are disconnected from the (bungee) network entirely, but other times they're simply moved to the lobby.

We've also increased the incoming-packet-spam-threshold from 300 to 900, to no avail.  We even tried to add the -Dpaper.playerconnection.keepalive=60 startup flag as suggested as a last resort in another issue report, which didn't resolve the issue. 

Whenever someone is kicked, all the logs say is this:
_[Server thread/WARN]: PLAYER was kicked due to keepalive timeout!
[Server thread/INFO]: PLAYER lost connection: Timed out_
There's no error or anything, that ^ is all we get.

We've been dealing with this issue for weeks now, and we're not sure where else to go.

We do use ProtocolSupport, but like I said earlier, even if players are on the same version as the server (1.12.2), they still get this issue.

### Paper build number:
1428

**Comment by electronicboy** [comment]
See #895

**Comment by PatoConBotas** [comment]
> Este problema está ocurriendo en todos nuestros servidores en nuestra red, no solo al iniciar sesión o al cambiar de servidor, sino al azar mientras los jugadores cambian de servidor. Redujimos nuestra distancia de visualización a 4, eso no ayudó. Les sucede a los jugadores independientemente de la versión del cliente, la región, el ping o si están AFK o no. A veces, los jugadores se desconectan por completo de la red (bungee), pero otras veces simplemente se trasladan al lobby.
> 
> También hemos aumentado el umbral de spam de paquetes entrantes de 300 a 900, sin éxito. Incluso intentamos agregar el indicador de inicio -Dpaper.playerconnection.keepalive=60 como se sugirió como último recurso en otro informe de problemas, que no resolvió el problema.
> 
> Cada vez que alguien es expulsado, todos los registros dicen lo siguiente: _[Subproceso del servidor/ADVERTENCIA]: ¡EL JUGADOR fue expulsado debido a un tiempo de espera agotado! [Hilo del servidor/INFORMACIÓN]: El JUGADOR perdió la conexión: Se agotó_ el tiempo de espera . No hay ningún error ni nada, eso es todo lo que obtenemos.
> 
> Llevamos semanas lidiando con este problema y no sabemos adónde más ir.
> 
> Usamos ProtocolSupport, pero como dije antes, incluso si los jugadores están en la misma versión que el servidor (1.12.2), todavía tienen este problema.
> 
> ### Número de compilación en papel:
> 1428

Pudiste solucionarlo?
