### ISSUE TITLE
Automatically adjust parameters according to TPS

### ISSUE THREAD

**Issue by Cat7373** [PaperMC/Paper#1159]
**Is your feature request related to a problem? Please describe.**

Sometimes we may wish to lower some of the parameter limits at low TPS

For example world-settings.default.entity-activation-range

**Describe the solution you'd like**

This is my patch for Spigot
It still has some questions but it is enough for me

https://github.com/Cat7373/Spigot_Patchs/blob/master/Spigot/CraftBukkit-Patches/0156-Cat73-TpsConfigure.patch

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by electronicboy** [comment]
This really feels like something that would be much better for a plugin to deal with as opposed to us, I wouldn't mind exposing additional API if/where necessary, but I just can't see this inside of papers config

**Comment by Cat7373** [comment]
A closer look seems to be indeed, okay, thanks
