### ISSUE TITLE
Mobs are spawning in massively large numbers in small areas on occasion, was this due to the village loading chunks problem?

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#1165]
###  Timings or Profile link:

https://timings.aikar.co/?id=3f357b77b7b143faaf9bec198b12c490#timings

### Description of issue:
Mobs are spawning in rediculously large amounts in small areas and buildings on occasion a lot more than usual and is very noticable, was this due to the village loading chunks problem fixed recently? Also when players are attacking zombies sometimes the zombies take away their weapon and replaces it with an armour piece this was reported by several players.

### Plugin list:

Plugins (123): ActionHealth, AdvancedPortals, AgarthaLib, AlwaysOnline, AntiPortalTrapping, ArmedArmorStands, AsyncWorldEdit, AsyncWorldEditInjector, AutoUpdaterAPI, BetterDrops, Blacksmith, BlockStatus, BottleRecycling, Broadcaster, Builder, ChangeSkin, chatemotes, Citizens, CitizensCMD, CityWorld, ClickSort, ColorCodes, ColoredAnvils, CombatTagPlus, CommandPrompter, CraftBook, Craftconomy3, Crash, CS-CoreLib, CustomJoinItems, CustomSoundManagerAPI, DamageIndicator, DeluxeChat, DeluxeMenus, Denizen, DiscordSRV, DragonEggRespawn, DynamicSigns, EazyEmojis-Lite, EditableSign, Essentials, EssentialsChat, EssentialsGeoIP, eZProtector, FirstJoinPlus, FOLFriends, ForceResourcepacks, ForgeModBlocker, FurnitureLib, gravy, HolographicDisplays, icJukeBox, InfoBook, InventoryFullPlus, InventoryOverflow, InventoryTweaks, LastHolo, LibsDisguises, LightAPI, LuckPerms, MaintenanceSpigot, Mentions.gg, Missing_Recipes, MoneyDrop, MultiInv, Multiverse-Core, Multiverse-Portals, MVdWPlaceholderAPI, NoPos, numberKeyBind, OnlinePlayersMenu, OpenInv, PacketListenerApi, ParadiseLand, PlaceholderAPI, PluginManagerReloaded, ProtectionLib, Protectiontime, ProtocolLib, PulseHealth, Questioner, Realistic-Swimming, RealisticLiquid, RealisticMC, SavageDeathCompass, SecurityVillagers, SelectionVisualizer, Sentinel, ShulkerBoxPlus, SilkSpawners, SimpleSit, Skript, Slime_Chunk, StackableItems, StatusBlock, SuperTrails, SurvivalMechanics, SurvivalMechanicsFlagAddon, TabList, TintHealth, TitleManager, Towny, TownyChat, TownyGUI, TownyNameUpdater, TownyTitle, TradeMe, Trails, UltimateDrugs, UltimateTrash, UltimateTroll, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WGRegionEvents, WGTitles, Wild, WorldEdit, WorldGuard, WorldGuardExtraFlags

### bukkit.yml, spigot.yml, paper.yml, server.properties

bukkit: https://pastebin.com/RKKrj3k1
paper: https://pastebin.com/gRKwqbYR
spigot: https://pastebin.com/ytZTG5CE
server-properties: https://pastebin.com/VM7J1FYL

### Paper build number:

This server is running Paper version git-Paper-1466 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Other helpful links

This issue in the link is very similar to this one I'm having, maybe related?

https://bugs.mojang.com/browse/MCPE-25161

Screenshot of removing mobs 600+ when set spawn limit is 100 in bukkit and mobspawn range is 4 in spigot/yml

https://www.dropbox.com/s/8yr08n3axbagek6/2018-06-22_18.26.44.png?dl=0

https://www.dropbox.com/s/v26r2osf92xmsgd/2018-06-22_18.34.53.png?dl=0

https://www.dropbox.com/s/fercb7a1xpzoqu0/2018-06-22_18.36.05.png?dl=0

**Comment by electronicboy** [comment]
`Also when players are attacking zombies sometimes the zombies take away their weapon and replaces it with an armour piece this was reported by several players.`
Something like that is more than likely 100% going to be down to a plugin

as for mob spawns, spawn limit is basically handled as a per-player radius limit, when you have the limit set to 100 and as tight of a spawn radius as 4, it's very likely that mobs are going to spawn in large amounts close together, especially when you've got stuff like towny or are in areas where mobs can't naturally spawn, they'll bulk up where they can spawn in order to head towards the limit

**Comment by axemwa** [comment]
ok that makes a lot of sense thanks so much

**Comment by axemwa** [comment]
What would you recommend I set the range and monster spawns to then?

**Comment by axemwa** [comment]
ok that makes a lot of sense thanks so much
What would you recommend I set the range and monster spawns to then?
and isnt the radius of 4 the default anyway? and its in chunks isnt that quite a large amount?
Mob Spawn 70 and Radius 4 is the dault settings so how can mob spawn 100 affect it by that much?
EDIT - Increasing the radius definately made it worse must be a plugin then

**Comment by axemwa** [comment]
Increasing the radius definately made it worse must be a plugin then

**Comment by electronicboy** [comment]
Please don't flood the issue tracker with comments, it floods peoples emails.

The code which handles all of this is a massive jumble of hell, looks like it's not technically "per player" but the real limit does increase with the number of players online and the number of chunks loaded (The limit isn't so much of a limit as a "part of the equation, it has a massive impact on the limit, but doesn't work how you'd expect).

keep the radius the same, but decrease the mob limit;
limit is basically = mob limit * loaded eligible chunks (in the spawn range) / 289

**Comment by axemwa** [comment]
Ok thanx deleted old messages and put them as one not a problem, and ok I'll try 50 mobs with radius of 4 then. 

EDIT - Damn nah it's still doing it https://www.dropbox.com/s/kfv0gdnk8tah04h/2018-06-22_19.17.32.png?dl=0 has to be a plugin

Even the animals seem to be spawning a lot faster

**Comment by axemwa** [comment]
Seems to be a plugin i added in the last few days; craftbook, forgemodblocker, armed armor stands and ezprotector it must be one of them

EDIT - Damn tried removing them all still didn't work ugh
Did u check through all my links timings etc to see what might be causing it

**Comment by aikar** [comment]
try increasing your mob spawn radius to 8, which is the vanilla value...

Your view distance is 10, so 8 is fine. Spigot reduced it from its vanilla value expecting it to help people, but it condenses the same amount of mobs into a much tinier area...

So for density, adjust radius. for count, adjust limit.

**Comment by axemwa** [comment]
Tried but sadly this was the result

![image](https://user-images.githubusercontent.com/37608633/41778462-0085b2bc-766e-11e8-9024-8313fcd52ed8.png)
Luckilt I do have a working backup of the server

**Comment by axemwa** [comment]
It turned out to be a setting in the Citizens plugins config which causes issues. 

`
  player:
    remove-from-list: false`

https://github.com/CitizensDev/Citizens2/issues/1520#issuecomment-399505788
