### ISSUE TITLE
Player get kicked from whole network when tellraw with a scoreboard query is executed

### ISSUE THREAD

**Issue by Bloodrayne1995** [PaperMC/Paper#1168]
### What behaviour is expected:
_Player executes a commandblock, which executes a /tellraw command. This command shows a message with a scoreboard value to the player._ 

### What behaviour is observed:
___Player got kicked from whole bungeecord network___

### Steps/models to reproduce:

1.  Create an objective in the scoreboard (in our case: eotaler)
2.  Try to execute /tellraw @p ["",{"text":"You have got this amount of EoTaler: "},{"score":{"name":"@p","objective":"eotaler"}}]

### Plugin list:
We have got over 50 Plugins. We listed them here: [https://pastebin.com/XCXhdLu1](https://pastebin.com/XCXhdLu1)

### Paper build number:
Paper-1467. Version-Output:
[19:16:08 INFO]: This server is running Paper version git-Paper-1467 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[19:16:08 INFO]: Previous version: git-Paper-1404 (MC: 1.12.2)
[19:16:08 INFO]: You are running the latest version

#### What are we trying to do:
We have got a bonus system. Our Players get special items if they vote for us.
This item is magma cream with NBT-Tags.
On our Map we have got a place where the player can pay in these items which transfer this
items to the scoreboard objective "eotaler". 
Then they can buy special things like a name tag or bigger building plot for these "eotalers".
This bug happens, when the player wants to know how much "eotaler" in his scoreboard objective he has got.

#### Stacktrace:
[https://pastebin.com/ut0C0BFQ](https://pastebin.com/ut0C0BFQ)

#### What we have already done:

- Remove scoreboard.dat file and restart server (in case this file is malformed)
- Update Paper to Build 1467 from 1404
- Update Bungecoord to Build 1310 To 1321
- Try tellraw with minecraft standard scoreboard objective (same result)
- Tested same command in single player mode and on one another server with Build 1404 (works fine)

#### Thoughts from us:
- Stacktrace shows, that bungee processes this command (We don`t know why). How will be
  Bungee involved into it
- The commands work on our other servers (in same bungee network), so the influence of bungee is unknown

#### What we will do now:
- removes all /tellraw commands with a scoreboard-query
- write a plugin which tells the player his scoreboard value

#### If you need some information of us:
- We dont know which information you would need. Please contact us, what information you will need
- We are able to make a Teamviewer session, if you want to. But in advance we are not native english speaker

**Comment by BillyGalbreath** [comment]
Unable to reproduce.

https://youtu.be/DsxzX34qYWY

**Comment by Bloodrayne1995** [comment]
Interesting.

To be sure: Did you test it on a bungee network?

**Comment by BillyGalbreath** [comment]
No. If it only happens behind Bungee then it's a Bungee problem and not Paper.

**Comment by Bloodrayne1995** [comment]
Ok.

We got now a plugin, which let  us show messages like tellraw without this tellraw-Command.
We are trying to separate this server from bungee and try it again. This will take a little time, so we cannot provide the result today. 

Thank you for your fast response.

**Comment by electronicboy** [comment]
Try replicating without plugins such as `.tom.sparse.spigot.chat.protocol.ChatPacketInterceptor` messing around with the contents of what you're sending

**Comment by aikar** [comment]
I am behind Bungee:
![](https://i.imgur.com/GMEgm54.png)

Can't reproduce. As said above, Sparse Chat Packet Interceptor is a huge likely culprit.
