### ISSUE TITLE
Paper doesn't like exclamation marks.

### ISSUE THREAD

**Issue by andrewkm** [PaperMC/Paper#1171]
I was watching Sweden vs Germany, got happy cause they scored, and made Paper go boom with **say SWEDEN GOAL!!!!!!!!!!!!!!!!** :( 

Tested with zero plugins on:
Paper 1468 **broken**
Spigot 1641 **not broken**

-Launch paper
-Type in console **say TEST!!**
-Type in console **say TEST!!**
-Boom? https://pastebin.com/raw/8AE28MX3

or

-Launch paper
-Type in console **say TEST!**
-Type in console **say TEST!**
-Type in console **say TEST!**
-Type in console **say TEST!**
-Type in console **say TEST!!**
-Boom? https://pastebin.com/raw/HFbLQAgT

and

-Launch spigot
-Type in console **say TEST!!**
-Type in console **say TEST!!**
-Type in console **say TEST!!**
-Type in console **say TEST!!**
-Type in console **say TEST!!**
-Type in console **say TEST!!**
-Type in console **say TEST!!**
-Type in console **say TEST!!**
-Type in console **say TEST!!**
-Type in console **say TEST!!**
-Type in console **say TEST!!**
-No Boom? https://pastebin.com/raw/r7ad0mPK

Stop discriminating against soccer fans and let us celebrate by spamming console :( <3

PS: _The server continues to function after the boom, but console becomes unresponsive and doesn't accept commands. Have to restart from in-game to get console functional again._

**Comment by andrewkm** [comment]
More info:
This was broken as of **Build 1114** on **June 11th 2017**.
_Looks like there was quite a few console changes on that date, so that would likely be where to look._

https://github.com/PaperMC/Paper/commits/master?after=ff572760c46b5b5b0b7c553d84a64a4b6811ab4c+419

**Comment by BillyGalbreath** [comment]
You mean [build 1113](https://destroystokyo.com/ci/job/Paper/1113/)? I'm looking into this (with not much success) and this is where I keep ending up.

**Comment by andrewkm** [comment]
@Yive your build numbers are off =P
https://yivesmirror.com/grab/paperspigot/PaperSpigot-1.12-b1113.jar is not [1113](https://destroystokyo.com/ci/job/Paper/1113)

Anyways, yes @BillyGalbreath on your link, [1112](https://destroystokyo.com/ci/job/Paper/1112/) works while [1113](https://destroystokyo.com/ci/job/Paper/1113) doesn't.

**Comment by BillyGalbreath** [comment]
I'm at a loss here. From what I'm seeing this is a bug in jline, but I cant find any mention of it anywhere else, so i'm probably way off base. @Minecrell

**Comment by stephan-gh** [comment]
It seems like JLine implements Bash's Event Designators by default: http://www.gnu.org/software/bash/manual/html_node/Event-Designators.html

For example, if you use

```
> say hi
> say I just used !!
```

It would say `I just used say hi`. And something in the code that parses these things seems to be broken sometimes.

In any case, this isn't really useful in the Minecraft console, so we can just disable it to avoid this error. Will make a PR later.
