### ISSUE TITLE
Refresh player when setting it's game profile 

### ISSUE THREAD

**Issue by NickAcPT** [PaperMC/Paper#1179]
**Is your feature request related to a problem? Please describe.**
The game profile api has a big missing feature. That feature is the refreshing of the player's own game profile on the client side.

**Describe the solution you'd like**
I'd like to have a feature where Paper automatically refreshes the game profile to the player itself.

**Describe alternatives you've considered**
I've considered sending the packets myself, but that requires sending packets (which in turn requires NMS), which in turn causes us to make hard to maintain boilerplate code.

**Additional context**
None.

**Comment by aikar** [comment]
This was added
