### ISSUE TITLE
Error that is spamming my console. :D

### ISSUE THREAD

**Issue by TheIntelloBox** [PaperMC/Paper#1181]
Hello everyone ! :D 

My console is spammed by an error: 
[20:25:44] [Netty Epoll Server IO #3/WARN]: [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.nio.channels.ClosedChannelException: null

	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.12.2.jar:git-Paper-1468]

This is the full error ! : D
Thanks for fixing it or helping me to fix it ! :D 
Have a nice morning or a nice day or a nice evening or a nice night ! :D 
TheIntelloBox. :D

**Comment by mikroskeem** [comment]
You haven't provided any useful data.

Complete log?  
Plugins list?  

And please, use something like [GitHub Gist](gist.github.com) when you are going to send logs here.

**Comment by zachbr** [comment]
Please don’t use hastebin or pastebin. I hate coming back to tickets a few weeks/months later and having dead links.

Use gist or just putting it in the ticket is fine.

**Comment by TheIntelloBox** [comment]
Hey ! :D

Full log when the error appears: https://gist.github.com/TheIntelloBox/d34abfb66ccc8955f8f0081ff1e64533 ! :D 

And I have 209 plugins so the list would be very long... :D.

**Comment by electronicboy** [comment]
Something that's hooking into netty is throwing exceptions, this is pretty much *always* down to plugins that are using netty directly or using protocol lib throwing exceptions, either due to issues directly with the plugin or because they don't handle reloads properly

**Comment by TheIntelloBox** [comment]
Hi ! :D 

Do you know plugins that can cause these errors ? :D 

Thanks for your answer ! :D

**Comment by mikroskeem** [comment]
Not without plugins list

**Comment by TheIntelloBox** [comment]
To who can I sent my list of plugins ?

**Comment by JanTuck** [comment]
To us on this issue

**Comment by TheIntelloBox** [comment]
I don't want that everyone can see my plugin list...

**Comment by JanTuck** [comment]
I guess we wont be able to help you then.

**Comment by electronicboy** [comment]
Closing due to it not being a paper issue

if you require assistance, you're more than welcome to use the discord/IRC, however, even with a plugin list we're somewhat useless unless somebody is able to see a plugin that was causing this issue for them. There are tools which will record every exception thrown and might allow you to pick up on what is exploding, beyond that it's simply a case of pulling out plugs until the light goes out.
