### ISSUE TITLE
Obfuscated ores showing when an NPC builder excavates down to stone before building something

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#1183]
### What behaviour is expected:
The actual ores and stones etc that were on the ground

### What behaviour is observed:
Obfuscated ores(the ones that show when players attempt to use an xray mod when anti-xray is switched on in paper.yml) are showing when the builder digs down to a cetain level when attmepting to build something, it's nothing major but just something I thought I'd point out and to ask if there's a way around it without having to remove the anti-xray feature. Also the obfuscated ores do dissapear when a player attempts to mine or hit them. EDIT - The obfuscated ores also seem to be acting as a light source.

### Steps/models to reproduce:
Get a Citizens NPC with builder trait to build something where digging down is required

### Plugin list:
Plugins (125): ActionHealth, AdvancedPortals, AgarthaLib, AlwaysOnline, AntiPortalTrapping, AsyncWorldEdit, AsyncWorldEditInjector, AutoUpdaterAPI, BetterDrops, Blacksmith, BlockStatus, BottleRecycling, Broadcaster, Builder, ChangeSkin, chatemotes, Citizens, CitizensCMD, CityWorld, ClickSort, ColorCodes, ColoredAnvils, CombatTagPlus, CommandPrompter, Craftconomy3, Crash, CrispyAntiWDL, CS-CoreLib, CustomJoinItems, CustomSoundManagerAPI, DamageIndicator, DeluxeChat, DeluxeMenus, Denizen, DiceFurniture, DiscordSRV, DragonEggRespawn, DynamicSigns, EazyEmojis-Lite, EditableSign, Essentials, EssentialsChat, EssentialsGeoIP, eZProtector, FirstJoinPlus, FOLFriends, ForceResourcepacks, ForgeModBlocker, FurnitureLib, gravy, HolographicDisplays, icJukeBox, InfoBook, InventoryFullPlus, InventoryOverflow, InventoryTweaks, LastHolo, LibsDisguises, LuckPerms, MaintenanceSpigot, Mentions.gg, Missing_Recipes, MoneyDrop, MultiInv, Multiverse-Core, Multiverse-Portals, MVdWPlaceholderAPI, MVdWUpdater, NoPos, numberKeyBind, OnlinePlayersMenu, OpenInv, PacketListenerApi, ParadiseLand, PlaceholderAPI, PluginManagerReloaded, ProtectionLib, Protectiontime, ProtocolLib, PulseHealth, Questioner, Realistic-Swimming, RealisticLiquid, RealisticMC, SavageDeathCompass, SecurityVillagers, SelectionVisualizer, Sentinel, ShulkerBoxPlus, SilkSpawners, SimpleSit, Skript, Slime_Chunk, StackableItems, StatusBlock, SuperTrails, SurvivalMechanics, SurvivalMechanicsFlagAddon, SwordDefence, TabList, TintHealth, TitleManager, TokenEnchant, Towny, TownyChat, TownyGUI, TownyNameUpdater, TownyTitle, TradeMe, Trails, UltimateDrugs, UltimateTrash, UltimateTroll, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WGRegionEvents, WGTitles, Wild, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
This server is running Paper version git-Paper-1470 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Anything else:
Refer to this link please

https://github.com/mcmonkey4eva/Builder/issues/3#issuecomment-401529455

**Comment by Black-Hole** [comment]
I don't if this could be fixed. There is no event if a plugin modifies a block. So you'll see those ores while using WorldEdit, too.

**Comment by Shevchik** [comment]
In older antixray implementations block update packet triggered the update blocks in radius. I don't know how new implementation works tho.

**Comment by stonar96** [comment]
Thank you for the report. I will take a look at it later.

The system for block updates is pretty much the same as the system used in Spigot 1.8.

**Comment by axemwa** [comment]
@stonar96 No problem, thankyou.

**Comment by zachbr** [comment]
This is probably fixed as of 1.13. If you still see it in 1.13 builds please re-open this ticket.
