### ISSUE TITLE
Problem with setProtocolVersion 

### ISSUE THREAD

**Issue by Alex134831** [PaperMC/Paper#1184]
### What behaviour is expected:
1.11 as fake version of the server

### What behaviour is observed:
1.12.2

### Steps to reproduce / Description:
Use [PaperServerListPingEvent#setProtocolVersion](https://destroystokyo.com/javadocs/com/destroystokyo/paper/event/server/PaperServerListPingEvent.html#setProtocolVersion-int-) with 315

I did this but still it shows "Paper 1.12.2" when i ping the server using 1.8 client. I tried more protocol versions from http://wiki.vg/Protocol_version_numbers. But [getProtocolVersion](https://destroystokyo.com/javadocs/com/destroystokyo/paper/event/server/PaperServerListPingEvent.html#getProtocolVersion--) works fine.

Also, if i ping the server using 1.12.2 client, it still says "Paper 1.12.2" so it makes it look like wrong version.

### Plugin list:
My test plugin, no ViaVersion etc.

### Paper build number:
1468

**Comment by theminecoder** [comment]
You’ll want to use `setVersion` to set the text that is returned.

**Comment by Alex134831** [comment]
It won't show the version string if protocol version of the client matches with protocol version of the server, that is why i want to change it. It still makes it look like the client uses a wrong version and it shows the version string, but still that is not what the method should do if i used it correctly.

**Comment by Black-Hole** [comment]
You can set the protocol version, you can set the string deplayed for non matching protocol version and you can query the protocol version of the client. Where do you see an issue that should be fixed or added?

The client compares the protocol versions and if they match, no string will be displayed. If you want to change that you need to patch die client, not the server.

**Comment by Alex134831** [comment]
Hmm do you still don't understand? I set the protocol version to 315 (1.11) but still it says "Paper 1.12.2" instead of "Paper 1.11".

**Comment by electronicboy** [comment]
The protocol version has no effect whatsoever on what the version string in the handshake shows, if you wish to change what is displayed there, you'll need to handle that yourself, as was already stated.

**Comment by Alex134831** [comment]
@electronicboy What, then what it is supposed to do? It changes the protocol version, but no any visual effect? Hmm, i got it. :+1:

**Comment by electronicboy** [comment]
it sets the protocol version as sent in the handshake response, the protocol version and the server version are entirely detached from one another programmatically, if you want to modify the version string, you need to use the setVersion method on the ping event
