### ISSUE TITLE
Paper Repo 1.8.8

### ISSUE THREAD

**Issue by Im-Fran** [PaperMC/Paper#1186]
Can you upload a PaperSpigot-API repo for 1.8.8?

**Comment by electronicboy** [comment]
There is already a repo with API 1.8.8, I passed you the link to it on IRC, 
https://github.com/PaperMC/Paper/blob/ver/1.8.8/Spigot-API-Patches/0001-POM-changes.patch#L25

**Comment by Im-Fran** [comment]
ok

**Comment by Im-Fran** [comment]
but, how i can implement it on maven?

**Comment by Im-Fran** [comment]
can anyone helpme?

**Comment by electronicboy** [comment]
This issue tracker is for issues with (supported versions of) the server software itself, not for general assistance with how to use your build tools, please do not spam it for support.

https://paper.readthedocs.io/en/paper-1.11/developers/

You will need to adjust the information in there with the new repo URL: https://destroystokyo.com/repo/repository/maven-public/

and grab the information for the version from the patch I linked above.
