### ISSUE TITLE
Mouse warps to random corner of computer screen when closing/restarting console

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#1187]
It's as the title says have had this happening for quite a while now and was wondering if it was fixable as it can get quite annoying.

**Comment by zachbr** [comment]
I've never had this happen.
Please provide all of the information requested in the template you deleted so we can investigate.
It'd also help if we knew what platform (Windows/Linux/macOS) and version you're running on.

Edit: That would've been [this](https://raw.githubusercontent.com/PaperMC/Paper/master/.github/ISSUE_TEMPLATE/behavior-bug---plugin-incompatibility.md) template

**Comment by axemwa** [comment]
That's ok if it's not happening to you or anyone else than its not related to paper I guess, was just looking to see if anyone else has the issue but if its not happening to anyone else don't worry about it was just after a quick fix if it was a common thing which is why I didn't fill out the template thanks anyway :)
