### ISSUE TITLE
Max-Growth-Height not working

### ISSUE THREAD

**Issue by artfcl-intlgnce** [PaperMC/Paper#1189]
### What behaviour is expected:
___What you expected to see___
Max growth height of cactus growth to 4 according to config

### What behaviour is observed:
___What you actually saw___
Max growth of cactus not limited

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Set max-growth-height to 4, and build a cactus [on the nether roof]
I have not attempted in other worlds

### Plugin list:
___A list of your plugins___
AttackSpeedRemover version 2.1.4
MinePacks version 1.17.8
Vehicles version 9.3.2
ColorConsole version 2.3.3
PlugMan version 2.1.4
TigerReports version 4.1.7
LuckPerms version 4.2.17
FirstJoinPlus version 2.4.1
Skript version 2.2-dev35b
FastCraft version 2.0.3
SpyPlusPlus version 1.0
EasyBackup version 2.7.1
ProtocolLib version 4.3.0
Multiverse-Core version 2.5-b719
MVdWPlaceholderAPI version 2.5.1
FastAsyncWorldEdit version 18.05.25-4049014-1138-20.1.8
Vouchers version 1.7
Advanced_Drop_Party version 1.8.9
VoidGenerator version 1.2.0
skUtilities version 0.9.2
mcMMO version 1.5.10-SNAPSHOT
PluginConstructorAPI version 1.0.36
ColoredSigns version 1.1.0
StaffMonitor version 1.4
PlaceholderAPI version 2.8.7
ParrotAnnouncer version 1.12
DeluxeCommands version 1.7.0
ForceField version 1.0
WolvSK version 1.6.0
TitleAPI version 1.7.5
ShutdownNotice version 3.1
CoreProtect version 2.14.2
LagAssist version 1.10.11
dynmap version 2.5-Dev201706100405
Wild version 3.14.1
VoteRoulette version 3.2.3
WorldEdit version 6.1.7;dd00bb1
PacketListenerApi version 3.6.0-SNAPSHOT
HackedServer version 1.33.1
BackupLikeMe version 0.1.1
CrackShot version 0.98.7
AutoUpdaterAPI version 2.4.3
SkQuery version 3.6.0-Lime
WorldBorder version 1.8.7
HeapDump version 1.4.0
Votifier version 2.3.7
BannerBoard version 1.9.9
LibsDisguises version 9.5.1
BlowableObsidians version 4.5
eZProtector version 4.2.4
CrackShotPlus version 1.7
WildSkript version 1.8
ParticleProjectileApi version 0.1.2
Vault version 1.6.6-b${env.TRAVIS_BUILD_NUMBER}
DrugMeUp version 1.1.1
TitleAdvanced version 6.2.0
CreativeParkour version 2.11.8
ParticleGrenades version 0.2.1
HolographicDisplays version 2.2.6
WiiPay version 1.5.2
RouletteXL version 1.0.1
ChatItem version 1.3.6.4
PlayerVaults version 4.0.5
MyCommand version 5.3.4
Orebfuscator4 version 4.3.3
Up2Date version 1.4.4
BountyHunters version 1.4.7
mcMMOAction version 2.3.2
Statscraft version 1.2.0
SkStuff version 1.6.4.1
CrackShotAdditions version 1.0.9
Citizens version 2.0.22-SNAPSHOT (build 1505)
OnTime version 4.1.4
CrazyAuctions version 1.2.4
TrollCommandsPlusPlus version 6.28.53
ChatGames version 1.0
Trading version 3.2
WorldGuard version 6.2.1;84bc322
Brewery version 1.5
WanderingNPC version 1.7
EZPrestige version 1.2.2
XP-Deposit version 4.2.0
CratesPlus version 4.4.5
AreaShop version 2.4.0
Essentials version 2.15.0.9
CrazyAuctionsAnnouncer version 1.1
McMMOExtras version 5.3.2
Skellett version 1.9.6b
SuperVanish version 6.0.5
EssentialsExtras version 2.15.0.1
EnjinMinecraftPlugin version 3.4.3
EnchantsPlus version 1.7.4a
EssentialsGeoIP version 2.15.0.9
CommandNPC version 1.9.1
QualityArmory version 1.1.103
Jobs version 4.5.3
EssentialsChat version 2.15.0.9
ChestShop version 3.9.1 (build 72)
EssentialsSpawn version 2.15.0.9
WorldGuardExtraFlags version 3.0.4
AuthMe version 5.4.0-b1877
BeastCore version 1.0-SNAPSHOT
SharpSK version 1.6.3
CMI version 7.8.6.0
EZRanksPro version 1.7.1
CustomEnchants version 17.7
FactionsTop version 5.0.12
Factions version 1.6.9.5-U0.2.1-RC-1.4-BETA-2
BungeeTabListPlus version 2.8.4
VentureChat version 2.12.2
FactionsTopv5Hologram version 1.0.4
FactionsTopv5ChangeAnouncer version 1.0.2
Conquer version 1.3.1
DiscordSRV version 1.16.3
XPboost version 1.95
AdvancedAchievements version 5.7.4
MentionMe version 0.4.2
Sentinel version 1.4.5 (build 166)
LeaderHeads version 3.1.8.3
MobHunting version 5.6.6
McDuels version 15.0.0
BossShopPro version 1.9.8
ItemShops version 1.0.8

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
1430

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by electronicboy** [comment]
I can't see how this would be possible; Config file? Can you replicate this without 100 plugins?

**Comment by Trigary** [comment]
Unable to reproduce (didn't use the plugins), version: git-Paper-210 (MC: 1.13.1)

**Comment by BillyGalbreath** [comment]
Also unable to reproduce. Video demonstration of cactus growth modifier set to 10 (used randomTickSpeed of 3000 to speed things up):

[![Unable to Reproduce](http://img.youtube.com/vi/MVQVtw6jaq8/0.jpg)](http://www.youtube.com/watch?v=MVQVtw6jaq8)
