### ISSUE TITLE
shields not preventing damage

### ISSUE THREAD

**Issue by jd1378** [PaperMC/Paper#119]
shields do not prevent damage from mobs .
i've seen a similar here but its fixed on spigot now 
https://hub.spigotmc.org/jira/browse/SPIGOT-1981

**Comment by zachbr** [comment]
Double check your version, make sure you're up to date. Paste your version string here.
Pretty sure this is fixed.

**Comment by jd1378** [comment]
i found that it was Skript plugin's fault .
hope i helped .
