### ISSUE TITLE
Server Icon ByteBuffer not being released

### ISSUE THREAD

**Issue by Starmixcraft** [PaperMC/Paper#1191]
The memory of my server is at 20GB and i restrited it to 2 GB, i changed the Netty Leak detector to paranoid and got this:

`16:59:19] [Netty Epoll Server IO #1/ERROR]: [io.netty.util.ResourceLeakDetector] LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	io.netty.buffer.AdvancedLeakAwareByteBuf.toString(AdvancedLeakAwareByteBuf.java:742)
	net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:736)
	net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:622)
	java.lang.Thread.run(Thread.java:748)
#2:
	io.netty.buffer.AdvancedLeakAwareByteBuf.setInt(AdvancedLeakAwareByteBuf.java:304)
	io.netty.handler.codec.base64.Base64.encode3to4BigEndian(Base64.java:238)
	io.netty.handler.codec.base64.Base64.encode3to4(Base64.java:180)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:130)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:111)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:91)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:78)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:74)
	net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:734)
	net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:622)
	java.lang.Thread.run(Thread.java:748)
#3:
	io.netty.buffer.AdvancedLeakAwareByteBuf.setByte(AdvancedLeakAwareByteBuf.java:286)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:135)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:111)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:91)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:78)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:74)
	net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:734)
	net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:622)
	java.lang.Thread.run(Thread.java:748)
#4:
	io.netty.buffer.AdvancedLeakAwareByteBuf.order(AdvancedLeakAwareByteBuf.java:70)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:123)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:111)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:91)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:78)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:74)
	net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:734)
	net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:622)
	java.lang.Thread.run(Thread.java:748)
Created at:
	io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(UnpooledByteBufAllocator.java:96)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:113)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:123)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:111)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:91)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:78)
	io.netty.handler.codec.base64.Base64.encode(Base64.java:74)
	net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:734)
	net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:622)
	java.lang.Thread.run(Thread.java:748)
: 2504 leak records were discarded because they were duplicates
: 2504 leak records were discarded because the leak record count is targeted to 4. Use system property io.netty.leakDetection.targetRecords to increase the limit.`

as you can see there are more then 2500 bytebuffs not released, this is a big problem for every server!!!
I am usin the latest Paper build

Additions:
Plugins: only my plugin that only changes the leak detector
System: Java-8_171, linux Ubuntu 16.06
Server Prop: https://hastebin.com/uyupesenak.ini
Bukkit.yml: https://hastebin.com/yefipelope.coffeescript
Spigot.yml : https://hastebin.com/fucenazoti.swift
Paper.yml: https://hastebin.com/uxuzomezuq.coffeescript

After examening the error and decompiling the code(dont be mad, i just wantet to see if i can spot it and maybe help with fixing), i found the problem, in MinecraftServer.java at line 684 a bytebuff is created by Base64.encode(bytebuf); the new bytebuf called bytebuf1 is never relesed.
`
Unchanged code:

                BufferedImage bufferedimage = ImageIO.read(file);
                Validate.validState(bufferedimage.getWidth() == 64, "Must be 64 pixels wide", new Object[0]);
                Validate.validState(bufferedimage.getHeight() == 64, "Must be 64 pixels high", new Object[0]);
                ImageIO.write((RenderedImage)bufferedimage, "PNG", new ByteBufOutputStream(bytebuf));
                ByteBuf bytebuf1 = Base64.encode(bytebuf); //bytebuf bytebuf1 never released!
                serverping.setFavicon("data:image/png;base64," + bytebuf1.toString(StandardCharsets.UTF_8));`

`         
Fixed code:

                BufferedImage bufferedimage = ImageIO.read(file);
                Validate.validState(bufferedimage.getWidth() == 64, "Must be 64 pixels wide", new Object[0]);
                Validate.validState(bufferedimage.getHeight() == 64, "Must be 64 pixels high", new Object[0]);
                ImageIO.write((RenderedImage)bufferedimage, "PNG", new ByteBufOutputStream(bytebuf));
                ByteBuf bytebuf1 = Base64.encode(bytebuf);
                serverping.setFavicon("data:image/png;base64," + bytebuf1.toString(StandardCharsets.UTF_8));
		 bytebuf1.release(); //This line fixed the leak`

PS: Sorry for my bad english, im from germany

**Comment by electronicboy** [comment]
Feel free to use the issue template and provide some basic information about your setup.

**Comment by Starmixcraft** [comment]
Updated information

**Comment by AJMFactsheets** [comment]
Not to discount your issue, but I often run stock paper (no plugins) with only 1GB of heap memory with no issues, even for many days straight, but few players join, only 3 maximum. To my knowledge, Java will garbage collect unused objects even without a delete-type method being called, which could explain why I never had encountered a OutOfMemoryException. Still, certainly good practice to release the object once done, so still a good find.

Also, don't feel bad about decompiling as MCP, Bukkit, Spigot, Paper all allow you to view source code, I doubt you've done anything wrong. ;)

**Comment by Starmixcraft** [comment]
@AJMFactsheets this issue only applyes if you have a server icon set, because the bytebuf is used to send the icon. Yes you are right java will garbage collect unused objects but the netty bytebuf is different, because is uses a byte[] that is copyed from a socket, TCP is stream based so things that you dont read or release will just stack in the sockets (cash) untill you have all the date to process youre packet

(client) -> (packet1, packet2) -> (encoder/encryper) -> (stream) -> (socket reads the data and once [i think is is 250 bytes or the stream sends no data for 50ms] the read method is called in netty then the decoder reads the bytebuff and if he only reads the first 50 bytes because the next 200 are from the next packet the 200 will be stored in the sockets cash untill the next read method call) -> (decoder) -> (server)

**Comment by AJMFactsheets** [comment]
@Starmixcraft Oh I see, I only use a static server icon, so I would never encounter this particular issue. I'm curious, does the server icon set allow for animated icons or a random icon selected? I've never heard of it before.

**Comment by Starmixcraft** [comment]
@AJMFactsheets the support for animated icons has been removed in mc 1.8.3 and a random icon selection is not supported, but you can request a feature

**Comment by electronicboy** [comment]
Thanks for the report and the information, should be resolved now
(in other news, github randomly lost this issue and couldn't be accessed for a few hours this morning, woo!)
