### ISSUE TITLE
Furnance issue on newest update

### ISSUE THREAD

**Issue by arturek1666** [PaperMC/Paper#1192]
### What behaviour is expected:
When placing items to furnace they should stay there and cook instead of disappearing 

### What behaviour is observed:
When placing coal and iron ore into the furnace the items getting removed 

### Steps/models to reproduce:
Just place stuff into furnace and you will see 

### Plugin list:
This issue is happening on 2 different server of mine and they have different plugins so don't think it's plugin issue 

### Paper build number:
git-Paper-1482 (MC: 1.12.2)

### Anything else:
I am 100% sure it must be an paper spigot as it was fine before updating the paperspigot. However i think it's 2 version behind that it works as I updated 2 today and they have same issue

**Comment by aikar** [comment]
confirmed, will try to resolve ASAP. It is very likely due to https://github.com/PaperMC/Paper/commit/bbfb696f30385515c050f53964d441ceb24f1ab4

@bloodmc thoughts?

**Comment by aikar** [comment]
1481 is last build before this

**Comment by aikar** [comment]
confirmed it is that patch, working towards solution now.
