### ISSUE TITLE
Server crashes. 

### ISSUE THREAD

**Issue by Eternalrealms** [PaperMC/Paper#12]
Hello, my server crashes constantly with this error. I can not find any plugin that is involved are you able to assist me?

Crash report: http://hastebin.com/mimusaruvi.avrasm

**Comment by zachbr** [comment]
Update your server, you are more than a month out of date. If the issue continues, we need the updated crash report it spits out

**Comment by Eternalrealms** [comment]
Do you know what patch would solve or prevent this issue? Looking at the commits a lot of the updates were for documentation.

**Comment by zachbr** [comment]
I have a few ideas, but nothing is certain. Now, please update your server to the latest version. If it continues I need an updated crash report, if it doesn't that's good as it gives me somewhere to start looking.

**Comment by Hockeyfreak15** [comment]
Hi, I too am experiencing this issue, same error, using the latest 1.8.8 verison of PaperSpigot.

**Comment by Techcable** [comment]
@hockeyfreak15
Please post the error you get on hastebin.

**Comment by bcillie** [comment]
Here's my error log http://hastebin.com/oqinipi

**Comment by Ichbinjoe** [comment]
@Hockeyfreak15 what plugins do you have on your server?

**Comment by Hockeyfreak15** [comment]
@Ichbinjoe I prefer not to leak my list. However, I don't see a plugin in the error. Which is why I'm here.

**Comment by Ichbinjoe** [comment]
What we have determined is that the cause of the issue is probably a plugin setting a velocity which is super high, causing this to happen. If you look at the pull request above, it outlines this.

**Comment by zachbr** [comment]
Update to latest, continue to test. Report back with new logs. Thanks.

**Comment by zachbr** [comment]
The additional data provided to you in c04cff4 should be enough to assist you in tracking these down on your own, seeing as you have yet to respond.
