### ISSUE TITLE
getTo() wrong location [Spigot Bug]

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#120]
There is a annoying bug in Spigot since the release which is already reported for over a week. It doesn't seem like that there will be a fast fix by the Spigot developers so maybe you can take a look to fix the issue (I hope it's not a huge bug):

https://hub.spigotmc.org/jira/browse/SPIGOT-1903

**Comment by PhanaticD** [comment]
This guy seems to have investigated the issue a lot https://github.com/Brettflan/WorldBorder/pull/61

this is causing more problems than with just the worldborder plugin however, two other plugins of mine also mess up when teleporting players across worlds, this is a pretty big issue surprised it has not been take care of yet

**Comment by PhanaticD** [comment]
maybe what should be happening is all movement should just be cancelled until world change is successful, as the "moved wrongly!" appearing in console appears to be what is causing double teleports

**Comment by PhanaticD** [comment]
okay so apparently this bug only happens with pressure plates, unless you add in a scheduler to do the teleport then it does not happen

not sure about worldborder though

**Comment by aikar** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/254/overview

**Comment by WonderDave** [comment]
Can this bug be re-opened?  While the issue seems to have been fixed (in Paper) for Nether portals, the problem definitely still exists with End portals.  The bug happens for me nearly all the time, and I'm not using any pressure plates.

**Comment by aikar** [comment]
Can you provide more details? Because my fix was super global and would take care of it across the board. I just followed the change world code and it will run into my code.
Can you provide a video of the issue?

**Comment by WonderDave** [comment]
I've made a video and have just updated the bug report (#242) with more
information and a link to the video.  Thanks for your assistance.
