### ISSUE TITLE
Paper Crash.

### ISSUE THREAD

**Issue by itaquito** [PaperMC/Paper#1202]
Hey! My server crashed just when I was playing with command blocks, Is this an out of memory or something like that?
https://pastebin.com/GKC8QDci

**Comment by electronicboy** [comment]
That report is a "your server took too long to tick",  potentially some relation to #1176, but that should only really be a concern if you're logging data much faster than your console can support; I'd suggest keeping your eyes on timings

**Comment by itaquito** [comment]
OK. thanks!
