### ISSUE TITLE
Bugs with leaves.

### ISSUE THREAD

**Issue by TheIntelloBox** [PaperMC/Paper#1209]
### What behaviour is expected:
___When we place leaves in creative mode, they should stay.___

### What behaviour is observed:
___When we place leaves in creative mode, they disappears.___

### Steps/models to reproduce:
___/gamemode 1, then place leaves, they dispawn.___

### Paper build number:
___B1500.___

**Comment by mikroskeem** [comment]
Cannot reproduce. What plugins do you have installed?

**Comment by zachbr** [comment]
If you still see this, re-open with additional information.
