### ISSUE TITLE
TNTIngiteEvent

### ISSUE THREAD

**Issue by Starmixcraft** [PaperMC/Paper#1210]
The TNTIgniteEvent is to be fired if a tnt block transformes to a entity, there is currently no simpel way to get the entity wen a tnt is ignited(besides listening spawn packets and getting it with entity id).

Event parameters: The block that got triggered, The entity that will spawn if not canceled, the action that was the cause(Flint_And_Steal,RedStone,Explosion).

I would add it myself but I'm too stupid to build spigot workspace

**Comment by BillyGalbreath** [comment]
This should be closed. Guess the link from #1214 didnt work correctly
