### ISSUE TITLE
Too lazy to make a PR as I'd have to build 1.12, Free item optimization

### ISSUE THREAD

**Issue by CullanP** [PaperMC/Paper#1211]
You can reduce a lot of item lag by skipping merges if the stack size is above/equal to the max stack size

**Comment by aikar** [comment]
Already behaves this way (not sure why github added core team task when I clearly clicked invalid)

```java
} else if (itemstack1.getCount() < itemstack.getCount()) {
                        return entityitem.a(this);
                    } else if (itemstack1.getCount() + itemstack.getCount() > itemstack1.getMaxStackSize()) {
                        return false;
```

**Comment by CullanP** [comment]
Put it in the x() method to avoid looking for nearby entities, e.g 

> public void x() {
        ItemStack stack = getItemStack();
        if (stack.count >= stack.getMaxStackSize()) {
            return;
        }

**Comment by aikar** [comment]
Oh I see, thanks
