### ISSUE TITLE
Decompile script error

### ISSUE THREAD

**Issue by Starmixcraft** [PaperMC/Paper#1213]
I think that in the decompile.sh in line 16 there is a error the line contains: " jar xf "$decompiledir/$minecraftversion-mapped.jar" net/minecraft/server" but jar is not a command is the line not supose to say " tar xf "$decompiledir/$minecraftversion-mapped.jar" net/minecraft/server"?

**Comment by electronicboy** [comment]
Install the JDK into your path, jar is a valid command provided by the JDK
