### ISSUE TITLE
Player get kicked for invalid keepalive

### ISSUE THREAD

**Issue by Starmixcraft** [PaperMC/Paper#1215]
Players get kicked with the message "sent an invalid keepalive! pending keepalive: false got id: 0 expected id: 0" sadly i was not able to track down the issue so i have to report ab bug without a solution.

I am usin git-Paper-1492

**Comment by electronicboy** [comment]
Something is sending keepalives when we're not pending one, id 0 would imply that you're using a plugin such as ViaBackwards and allowing clients to join the server which don't have the 1.12.2 keepalive changes.
