### ISSUE TITLE
Creepers does not keep their "SSSSSSSS" loop (w/ WorldGuard)

### ISSUE THREAD

**Issue by TNTUP** [PaperMC/Paper#1216]
### What behaviour is expected:
Having WorldGuard, disabled creeper explosion/block damage in a certain world, igniting creepers would let them stuck into the SSSSSSS process in a loop, which I've found quite a funny bug. Updated to Paper #1500 this morning and I noticed they do not keep their SSSSSSS while ignited. I don't know since what commit causes this, ill try downgrading to the one who I expect it to work.

I've only enabled this config behaviour only in a Creative world.

### What behaviour is observed:
Ignited the creeper, it does SSSSSSSS but becomes normal after that.

### Steps/models to reproduce:
I haven't updated WorldGuard in a while so this can't be WG fault because this behaviour was still working before updating Paper.

Get WorldGuard and set this in your config (creeper related)

mobs:
    block-creeper-explosions: true
    block-creeper-block-damage: true

Then ignite the creeper, it should stuck at SSSSSSSS until you kill it. 
### Plugin list:
WorldGuard

### Paper build number:
18:16:33 CONSOLE: [INFO] This server is running Paper version git-Paper-1500 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
18:16:33 CONSOLE: [INFO] Previous version: git-Paper-1499 (MC: 1.12.2)
18:16:33 CONSOLE: [INFO] You are running the latest version

Before upgrading to Build 1500, I was on 1415 so something creeper related changed it. Reverting to this version and trying future ones until it breaks.

[00:14:47] [Server thread/INFO]: This server is running Paper version git-Paper-1415 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Anything else:
Since this is a funny bug, I don't think that will be resolved, but I'll downgrade until it works and locking myself to 1.12.2 (1.13-pre7 is out and lots of plugins are dead) so no 1.13 for me until forever.

**EDIT**Found the commit which removed the "ignited" flag. I'll stay on Build 1446 or else fork and remove that patch and rebuild patches then ill be fine, I guess?

**Comment by aikar** [comment]
That was a bug... and I do not believe it should be made configurable either. I suggest forking if you want abnormal gameplay behavior such as this or find another solution

**Comment by TNTUP** [comment]
Thats I was going to fork it^^ 

EDIT: Deleted the file and it works^^ I love that bug ill keep it haha! Love Paper <3
