### ISSUE TITLE
When console option to show(mark), the server go to freeze

### ISSUE THREAD

**Issue by DahunDev** [PaperMC/Paper#1218]
### Description of issue:
___If applicable___

In the console, right click and, edit -> show(mark),
then the server get freeze until the mark option left.
In the original Spigot, that freezing not occures.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

1500 , lastest

**Comment by stephan-gh** [comment]
What exactly is "Edit -> Show (Mark)" Can you make a screenshot of this option? Which platform/OS are you using?

**Comment by hugmanrique** [comment]
I believe he's talking about `cmd` on Windows. Right click on the top bar, hover over `Edit` and then click `Mark`:

![cmd screenshot](https://i.imgur.com/nElqaaL.png) (It's in Spanish)

**Comment by zachbr** [comment]
I'm not convinced this is a bug.
The mark function of cmd exists to make it easy to select and copy text out of the console. In other Windows command line apps, mark also pauses output.

So to me, this just makes sense.

**Comment by zachbr** [comment]
I misunderstood this as "the logger freezes" rather than "the server stops ticking"
See #1176, loggers will need to be made async to resolve this which goes back to that issue.
