### ISSUE TITLE
Chunk updating

### ISSUE THREAD

**Issue by ConradHD1** [PaperMC/Paper#1225]
When I activate an ability with mcmmo and it completes, after that event the chunk area freezes entities and shows this visual glitch.

https://gyazo.com/9f8264bab03c7e36ad0519739ac9ed61

This happens for everything (Obvious with item dropping, mob dying, firework rocket armor stands etc)
I'm pretty sure this isn't just McMMO (natural events maybe?)also.

**Comment by electronicboy** [comment]
This is a client desync issue, if you right click in the spot it's occuring, you'll see the block which is causing that visual issue

The problem with this is that mcmmo causes behavior which is a bit of an odd interaction between the client and the server

**Comment by ConradHD1** [comment]
The problem is that there is no block there and it still happens, it does the same with fireworks and every entity (even players).

It glitches the whole area (As in the whole chunk) and isn't resolved until you press f3 + a or relog.

**Comment by ConradHD1** [comment]
This was fixed by disabling "Refresh Chunks" in the mcmmo config.yml
