### ISSUE TITLE
Optimize World.isValidLocation

### ISSUE THREAD

**Issue by Cat7373** [PaperMC/Paper#123]
I know this is a very simple way, nothing complicated logic
But its high number of calls
Perhaps what can be optimized

![](http://ww4.sinaimg.cn/large/9103a520jw1f25rmy6su7j20s30b50xf.jpg)
![](http://ww2.sinaimg.cn/large/9103a520jw1f25rmxr72kj20sf05ajtk.jpg)

**Comment by Cat7373** [comment]
# current

```
private boolean isValidLocation(BlockPosition blockposition) {
    return blockposition.getX() >= -30000000 && blockposition.getZ() >= -30000000 && blockposition.getX() < 30000000 && blockposition.getZ() < 30000000 && blockposition.getY() >= 0 && blockposition.getY() < 256;
}
```

# new

```
private boolean isValidLocation(BlockPosition blockposition) {
    return blockposition.isValidLocation();
}

class BlockPosition {
    public boolean isValidLocation(BlockPosition blockposition) {
        return thix.y < 256 && this.y >= 0 && thix.x < 30000000 && this.z < 30000000 && this.x >= -30000000 && this.z >= -30000000;
    }
```

**Comment by Ichbinjoe** [comment]
I'm not sure you will see any realistic improvement. Instead, we could
probably enforce these bounds on creation and state changes. (Disclaimer,
not looking at code right now)

**Comment by Cat7373** [comment]
Can reduce several function calls - -

**Comment by Ichbinjoe** [comment]
If you think it will help run a before and after benchmark on it, and
report back.

**Comment by aikar** [comment]
I had something like this before, I'll do something about it tonight. I was waiting to see if it was still relevant with tech's inline change, but seems it might still be.

thinking the inlining may not be working as expected w/ his change.

By swapping out the code for this on my fork for 1.8.8, I did get it to disappear off hotspots. with it showing up, means it's not being inlined.

**Comment by Techcable** [comment]
Those calls already will be inlined with my patch, which @aikar didn't have on 1.8.8
Don't really see the point of this patch.

**Comment by aikar** [comment]
@Techcable the OP is on 1.9 and using Paper... has nothing to do with my own server.

Something about your patch must not be working (or at least in all cases) as inlined code will not show up on Hot Spots like this.
We at least know the method of my patch is common to assisting inlining.

**Comment by aikar** [comment]
Also your patch is targeting the getX/Y/Z calls, and this one targets the isValidLocation method.

My assumption is that the inlining for getX/Y/Z is not considered in the calculations for inlining isValidLocation. So we can simply just do both to be sure.
