### ISSUE TITLE
1.13: Readd Anti Xray

### ISSUE THREAD

**Issue by aikar** [PaperMC/Paper#1230]
Patch removed, needs to be re added. 
0235-Anti-Xray.patch

**Comment by stonar96** [comment]
I have looked at the source and checked the changes and it shouldn't be that hard to readd Anti-Xray from my point of view. There are infact minor changes for example in `DataPaletteBlock` but the functionality is all in all still the same such that it can be easy reimplemented by going through the old patch file with small adjustments.

I think it's easier (not just for me) if you (the Paper Core Team) readd it by yourself and if you have any questions or need my help at a specific point you can ask me here of course. Once it is readded I would of course check it.

Please give me a short answer if that's okay for you.

**Comment by NullCase** [comment]
You're probably going to think i'm just piling on work. It seems like you're really busy and I'm really impressed by how much work you've put in to Paper 1.13.

Still I wanted to tell you guys about this before someone else takes the opportunity. I am willing to give you my entire budget for ore block obfuscation to whoever produces a stable anti-xray update first.

I've spoken with the Orebfuscator devs. They are aware of this bounty, but I wanted you to know too so you don't lose the chance to make some money producing this update.

It's an important enough target for me that I want to put money on whomever gets a stable release out first.

**Comment by nahia95** [comment]
Any news on this?

**Comment by aikar** [comment]
Stonar gave us an update on IRC that there is some significant rework needed for 1.13. He is looking into it, no ETA.

**Comment by stonar96** [comment]
Looks good so far. I have a basic concept now and started implementing it yet. `DataPaletteBlock` needs a few changes. The reason is that in 1.13 `DataPaletteBlock` is directly loaded from NBT.

There is also the new `ProtoChunk` instead of `ChunkSnapshot` which also uses `DataPaletteBlock` now.

All this makes it harder for me to add the predefined block data to the `DataPalette`s which are used to obfuscate the chunk packets.

**Comment by NullCase** [comment]
It sounds like you may want testing & feedback at some stage. I am happy to also provide testing & feedback at that stage to advance the update towards a stable release.

**Comment by stonar96** [comment]
![2018-08-20_02 40 59](https://user-images.githubusercontent.com/18699205/44315364-c1617380-a423-11e8-8e85-c9b11b521de5.png)

Just in case someone is interested, this is a screenshot of testing the first build (with working obfuscation). There are still many things to implement at the moment, such as the block updates, but most of the work is done. https://github.com/stonar96/Paper/tree/feature/anti-xray/2.0/pre/1.13

**Comment by NullCase** [comment]
Someone is interested! How do I download the file?

**Comment by nahia95** [comment]
@NullCase you have to compile the fork stonar96 has made

**Comment by NullCase** [comment]
I have to compile it. Ok, it sounds like I ought to wait instead. Otherwise i'd learn from scratch. By that time this patch might already be added to paper :smile:

**Comment by bilemedimkq** [comment]
Hello,

when I compile the project I get such an error.
Could you help?

https://prnt.sc/klcvx3

or does one of you compile it into a jar and give it to me?

**Comment by zachbr** [comment]
Builds 170+

**Comment by NullCase** [comment]
@stonar96 got paid. great work.
