### ISSUE TITLE
java.nio.channels.ClosedChannelException 

### ISSUE THREAD

**Issue by TheIntelloBox** [PaperMC/Paper#1233]
### Link/paste of stack trace
I have put debug=true in my server.properties and I have these errors:
    https://hastebin.com/azopaluyet.cs

### Paper build number:
___B1500.___

**Comment by mikroskeem** [comment]
Dear fucking lord.

Start removing plugins (especially ones which deal with protocol hacks) one by one and then figure out which cause given issue.

edit: Gboard autocorrect is annoying.

**Comment by aikar** [comment]
I'm not sure why you removed the plugin list from your report.... 
Please don't try to "hide" information from us.

This is caused by a plugin.
