### ISSUE TITLE
Console Errors - Duplicate Mobs

### ISSUE THREAD

**Issue by 0XE4** [PaperMC/Paper#1234]
### What behaviour is expected:
No errors in the console regarding mobs.

### What behaviour is observed:
`[16:50:26 ERROR]: Deleting duplicate entity EntityZombie['Zombie'/1285092, uuid='REDACTED', l='world', x=36.81, y=59.00, z=536.50]`  
`[16:50:26 ERROR]: Keeping entity minecraft:zombie that already exists with UUID REDACTED - EntityZombie['Zombie'/1285068, uuid='REDACTED', l='world'
, x=32.55, y=59.00, z=525.79]`
`[16:50:26 ERROR]: Deleting duplicate entity EntityZombie['Zombie'/1285093, uuid='REDACTED', l='world', x=36.81, y=59.00, z=536.50]`
`[16:50:26 ERROR]: Keeping entity minecraft:zombie that already exists with UUID REDACTED - EntityZombie['Zombie'/1285068, uuid='REDACTED', l='world'
, x=32.55, y=59.00, z=525.79]`

This is for all mobs, Zombies, Rabbits etc.

### Steps/models to reproduce:
Start the server and view console output.

### Plugin list:
N/A

### Paper build number:
`Paper version git-Paper-1502 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

**Comment by aikar** [comment]
how often are you seeing it? Also there is no need to redact UUID's, they aren't secret :)

This does add more info to my #1223 issue. I believe the reason these messages are showing is the source of #1223, so please follow that issue.

Respond over on 1223 please
