### ISSUE TITLE
how fix this warn

### ISSUE THREAD

**Issue by cuervito** [PaperMC/Paper#1235]
### What behaviour is expected:
___What you expected to see___
hello I put the last paper 1.12 and it gives me a warn all the time

### What behaviour is observed:
___What you actually saw___
12:49:09] [Netty Epoll Server IO #1/WARN]: [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException: null
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___
Paper version git-Paper-1500 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by aikar** [comment]
Do you really have no plugins? Please list your plugins, as this is caused by plugins.

Or are you using ViaVersion on Bungee and 1.13 is trying to connect?

**Comment by cuervito** [comment]
yes i have plugins  .. AAC, AACAdditionPro, CancelSounds, ChatGuard, ChestCommands, CustomJoinItems, Essentials, EssentialsChat, FastAsyncWorldEdit, FastPot, GUIPlus, HolographicDisplays, LeaderHeads, NoRain, OldCombatMechanics, PermissionsEx, PlaceholderAPI, PressureCommand, ProtocolLib, ProtocolSupportPotions, SkyWars, SmoothKnockback, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, WorldEdit, WorldGuard..   i using viaversion   last

**Comment by aikar** [comment]
one of the Via plugins will be the source of this issue. Please report issue to them.
