### ISSUE TITLE
invincible player

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#124]
a player logged in while in the nether, did /home (essentials command) and is now invincible to all damage

**Comment by Ichbinjoe** [comment]
Sounds like something needed reported to essentials.....

**Comment by PhanaticD** [comment]
i think it may be a issue with cross world teleporting with the new invincible packet sending

**Comment by PhanaticD** [comment]
I was on build 539, just updated to 553 and had the player do the same steps that initially caused this to happen and it worked fine, so i am not sure if it only happens some of the time or was fixed between those

**Comment by Ichbinjoe** [comment]
Unless you can repeat this again, this issue should be closed.

**Comment by zachbr** [comment]
I have a PR for this to upstream CB [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/238/overview). So I'd like to be certain.

I will test this personally in several hours.
