### ISSUE TITLE
Add Mojang API

### ISSUE THREAD

**Issue by NickAcPT** [PaperMC/Paper#1242]
**Is your feature request related to a problem? Please describe.**
There's no unified way of requesting data from Mojang's endpoints.

**Describe the solution you'd like**
The idea is to build a unified API that any paper developer can use to request information from Mojang ([list of all endpoints](http://wiki.vg/Mojang_API))

**Describe alternatives you've considered**
I've considered using existing code from the web, but they end up not being the best (exception handling) and it makes it repetitive since there's no built-in way to do it in Paper.

**Additional context**
Nothing to add.

**Comment by aikar** [comment]
This is something best left to external libraries, and not a good fit for paper
