### ISSUE TITLE
Connection Handler - Causing lag or false positive?

### ISSUE THREAD

**Issue by SirKillian** [PaperMC/Paper#1251]
###  Timings or Profile link:
https://timings.aikar.co/?id=564fa06b3fac41cbb392a5d77a1cf4cd

### Description of issue:
Connection Handler causing lag?
Even when all plugins are disabled and only 1 player joining.

### Plugin list:
0 plugins loaded.

### bukkit.yml, spigot.yml, paper.yml, server.properties
Bukkit.yml : https://hastebin.com/ekosokusow.yml
paper.yml: https://hastebin.com/aqisedavum.yml
spigot.yml: https://hastebin.com/minovahopa.yml
server.properties: https://hastebin.com/uzawusigov.properties

### Other helpful links
/

### Paper build number:
We first discovered this on build 13XX. (can't remember the exact build)
We updated few days ago to build 1504 but is still happening.

**Comment by aikar** [comment]
There is no lag shown in this report...

There is a `single` tick out of 4800 that had a hiccup.

It's fine. It was likely just a garbage collection. Please do not use the existence of red as a sign of lag. Look at TPS, look at the graph, look for heavy amounts of high levels of orange.

No problems are showing here.
