### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by madtomic** [PaperMC/Paper#1252]
Extracting NMS classes...
./scripts/decompile.sh: line 16: jar: command not found
Failed to build Paper

I just got this trying to build paper.

**Comment by madtomic** [comment]
Seems like the Advancement.java is missing.

**Comment by zachbr** [comment]
You don’t have the JDK installed properly.

jar is a standard command bundled with the JDK. Not a paper issue.

**Comment by madtomic** [comment]
It is not JDK issue.

$ ./paper jar
Downloading unmapped vanilla jar...
Applying class mappings...
Applying member mappings...
Creating remapped jar...
Installing remapped jar...
Extracting NMS classes...
Decompiling classes...
Applying CraftBukkit patches to NMS...
Patching Advancement.java < nms-patches/Advancement.patch
sed: can't read /c/Users/madtomic/Desktop/PaperSpigot Source/Paper/work/Minecraft/1.12.2/net/minecraft/server/Advancement.java: No such file or directory
cp: cannot stat '/c/Users/madtomic/Desktop/PaperSpigot Source/Paper/work/Minecraft/1.12.2/net/minecraft/server/Advancement.java': No such file or directory
Failed to build Paper

**Comment by DenWav** [comment]
Run `./paper clean` then try `./paper jar` again.

**Comment by zachbr** [comment]
Can’t speak for the current one, but the first was absolutely an environment issue because you didn’t have the jar command

**Comment by madtomic** [comment]
I tried clean and jar again.

$ ./paper jar
Submodule path 'work/BuildData': checked out 'be360cc298a06b5355ecd057f5b1feb894a73f0f'
Submodule path 'work/Bukkit': checked out 'bdd0eda71f87cb8ca3b1842bd9bbd43bba5a08bd'
Submodule path 'work/CraftBukkit': checked out '57ab4cfc6f4ff526d44319d9b8c79f6848db2de7'
Submodule path 'work/Paperclip': checked out 'd0395f6304db49e4472dab9dbf247e994a1122b8'
Submodule path 'work/Spigot': checked out '642f6d2288b830f41347e8c0a162fbc0584e1579'
Downloading unmapped vanilla jar...
Applying class mappings...
Applying member mappings...
Creating remapped jar...
Installing remapped jar...
Extracting NMS classes...
./scripts/decompile.sh: line 16: jar: command not found
Failed to build Paper

now it said this again,

**Comment by aikar** [comment]
Try renaming "PaperSpigot Source" to "Paper"

You obviously have something weird going on, you need java in path.

**Comment by madtomic** [comment]
humm... it's environment variables. so it shouldn't matter where it is but I will try rename it to Paper

**Comment by madtomic** [comment]
Same issue, I never had this kind of issue before. I am building on the same system and I had build before. The only thing changed is I clone the latest version and try to build.

**Comment by DenWav** [comment]
Finding `jar` on the path is only the `PATH` variable. It's probably been changed somehow and that's causing your environment to be broken.

**Comment by 0-x-2-2** [comment]
I believe I had to manually add something to my environment variables

**Comment by madtomic** [comment]
Thanks everyone, I will look into this.
