### ISSUE TITLE
The server has stopped responding!

### ISSUE THREAD

**Issue by SomeBottle** [PaperMC/Paper#1255]
### Link/paste of stack trace

23.07 19:54:11 [Server] ERROR The server has stopped responding!
23.07 19:54:11 [Server] ERROR Please report this to https://github.com/PaperMC/Paper/issues
23.07 19:54:11 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports
23.07 19:54:11 [Server] ERROR Paper version: git-Paper-22 (MC: 1.13)
23.07 19:54:11 [Server] ERROR ------------------------------
23.07 19:54:11 [Server] ERROR During the run of the server, a plugin set an excessive velocity on an entity
23.07 19:54:11 [Server] ERROR This may be the cause of the issue, or it may be entirely unrelated
23.07 19:54:11 [Server] ERROR Excessive velocity set detected: tried to set velocity of entity 3fe3ce06-8f7d-42b8-9093-512a7958fa87 id #15658 to (2.623150244459688,-0.0784000015258789,-4.8987874750376195).
23.07 19:54:11 [Server] ERROR org.bukkit.craftbukkit.v1_13_R1.entity.CraftEntity.setVelocity(CraftEntity.java:268)
23.07 19:54:11 [Server] ERROR net.minecraft.server.v1_13_R1.PlayerList.repositionEntity(PlayerList.java:1017)
23.07 19:54:11 [Server] ERROR net.minecraft.server.v1_13_R1.Entity.teleportTo(Entity.java:2645)
23.07 19:54:11 [Server] ERROR net.minecraft.server.v1_13_R1.Entity.d(Entity.java:2588)
23.07 19:54:13 [Server] ERROR net.minecraft.server.v1_13_R1.Entity.postTick(Entity.java:380)
23.07 19:54:13 [Server] ERROR net.minecraft.server.v1_13_R1.World.entityJoinedWorld(World.java:1489)
23.07 19:54:13 [Server] ERROR net.minecraft.server.v1_13_R1.World.g(World.java:1455)
23.07 19:54:13 [Server] ERROR net.minecraft.server.v1_13_R1.World.tickEntities(World.java:1262)
23.07 19:54:13 [Server] ERROR net.minecraft.server.v1_13_R1.WorldServer.tickEntities(WorldServer.java:615)
23.07 19:54:13 [Server] ERROR net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:1060)
23.07 19:54:13 [Server] ERROR net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428)
23.07 19:54:13 [Server] ERROR net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914)
23.07 19:54:13 [Server] ERROR net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812)
23.07 19:54:13 [Server] ERROR java.lang.Thread.run(Thread.java:745)
23.07 19:54:13 [Server] ERROR ------------------------------
23.07 19:54:13 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
23.07 19:54:13 [Server] ERROR ------------------------------
23.07 19:54:13 [Server] ERROR Current Thread: Server thread
23.07 19:54:13 [Server] ERROR PID: 17 | Suspended: false | Native: false | State: RUNNABLE
23.07 19:54:13 [Server] ERROR Stack:
### Plugin list:
![tim 20180723200532](https://user-images.githubusercontent.com/12976469/43075540-ccc4abc8-8eb3-11e8-931e-b39ed4371968.png) 

### Actions to reproduce (if known):
Lots of Players moving fast, and all of them cannot eat anything (It never happened when I was using Paper1.12.2)

### Paper build number:
Paper version: git-Paper-22 (MC: 1.13)

**Comment by 0-x-2-2** [comment]
The cause is most likely outdated plugins

**Comment by aikar** [comment]
You cut off the stack trace at the important part, but this isn't a bug.

1.13 has extremely bad performance right now, and converting chunks is a very slow process.

Allowing players to move at fast speeds will encounter this as you're going to load a lot of chunks and cause the server to do too much.

Reduce your view distance, and reduce how fast players can travel is the only recommendations at this time.

**Comment by 0-x-2-2** [comment]
Possibly he could use the world optimizer don't know if its in the server tho but its a feature in the client. https://i.imgur.com/JvdXPq8.png

**Comment by aikar** [comment]
That doesn't help anything. All it does is force you to keep your server turned off for a long time vs letting people play.
