### ISSUE TITLE
1.13: Farmland doesn't get hydrated (seemingly randomly)

### ISSUE THREAD

**Issue by Nikokku** [PaperMC/Paper#1259]
### What behaviour is expected:
___Farmland within the vanilla reach of water to get hydrated.___

### What behaviour is observed:
___Farmland not getting hydrated in seemingly random patterns.___

### Steps/models to reproduce:
___Should be self-explanatory.___

### Plugin list:
___None, tested on a 'fresh' server.___

### Paper build number:
___Paper version git-Paper-"4608731d" (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)___

### Anything else:
___Like I said, this was tested a fresh server without any plugins. Testing in vanilla revealed that this is not a problem in singleplayer. The Paper version used was compiled with Java 10 and the server run with it aswell. I will include a screenshot of the test result.___

![2018-07-23_23 04 37](https://user-images.githubusercontent.com/5014822/43105847-b0aaddea-8ed6-11e8-9a7c-5842649de4e9.png)

**Comment by kangarko** [comment]
What is your /gamerule randomTickSpeed ? Try increasing it for debug purposes.

**Comment by Nikokku** [comment]
I set up another fresh Paper server and tried just making farmland like in vanilla to test again. Was still there. Then I put the latest WorldEdit dev build on to test on a larger scale. I made what is shown in the attached picture. What is weird is that testing revealed that no matter if the randomTickSpeed is 3 or 1000 it always ends up in exactly the same pattern.

![2018-07-24_17 06 53](https://user-images.githubusercontent.com/5014822/43147763-140774a6-8f64-11e8-936a-364221d3631f.png)

**Comment by Nikokku** [comment]
I tested it the exact same way again on a Spigot server and it works just fine on there, so yeah, definitely a Paper issue.

**Comment by aikar** [comment]
is this 1.13 only?

**Comment by Nikokku** [comment]
Considering I had a 1.12.2 Paper survival server where no such bug was reported I would say so, yes.

**Comment by aikar** [comment]
Ok just needed to confirm scope of if its a bad patch apply i.13, or longer term bug

**Comment by Nikokku** [comment]
Just to be save I tested the same way on the latest 1.12.2 build and yea, definitely 1.13

**Comment by viiivira** [comment]
I've been having the same problem and it seems like it is a regular pattern of a line of hydrated farmland 4 blocks to the south of water sources.

![image](https://user-images.githubusercontent.com/5164188/43162273-84254800-8f58-11e8-934b-0f34de9962fa.png)

**Comment by Nikokku** [comment]
Following up on Everett1999's answer I decided to test it like that on a larger scale, the result is in the screenshot. Again, redoing it always produces the same pattern.

![2018-07-24_22 13 10](https://user-images.githubusercontent.com/5014822/43163615-f4dc83fc-8f8e-11e8-8be1-9ff71b8e8460.png)

**Comment by Nikokku** [comment]
Okay so it seems like the only farmland getting watered is the south-most side of the water radius, no matter the position. I'm gonna play around with some settings to see if something has an effect on it.

![2018-07-24_22 20 18](https://user-images.githubusercontent.com/5014822/43163891-ebbca4ae-8f8f-11e8-9599-ce3d49256d05.png)
![2018-07-24_22 21 20](https://user-images.githubusercontent.com/5014822/43163895-ede3cb68-8f8f-11e8-95cd-107964aded1f.png)

**Comment by Nikokku** [comment]
Playing around with paper.yml didn't reveal anything, that's the end of my testing abilities.^^

**Comment by aikar** [comment]
Fixed in build 34
