### ISSUE TITLE
Titles kicking clients

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#126]
PhanaticD lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

paperspigot build 553

related to https://github.com/PaperMC/Paper/issues/94

**Comment by zachbr** [comment]
We've been checking APIs this whole time, not the NMS itself, which plotsquared, and many others, use.

**Comment by PhanaticD** [comment]
im pretty sure i linked to the plotsquared issue report in my initial bug report
