### ISSUE TITLE
1.13: Chat text is the same color as player name using vanilla name color

### ISSUE THREAD

**Issue by BaltimoreCalling** [PaperMC/Paper#1263]
### What behaviour is expected:
x color chat name: white text

### What behaviour is observed:
x color chat name: x color text

### Steps/models to reproduce:
null
### Plugin list:
Spigot Essentials. Worldguard. Bpermissions. VotingPlugin. WorldEdit.
### Paper build number:
Paper version git-Paper-28 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by aikar** [comment]
What is your world setting for: use-vanilla-world-scoreboard-name-coloring

**Comment by BaltimoreCalling** [comment]
It's set to true

**Comment by BaltimoreCalling** [comment]
I love that feature, and it's a big reason I use PaperSpigot. On 1.12.x it would display correctly.

**Comment by BaltimoreCalling** [comment]
Aikar, I'll copy my production server into a test environment without plugins and see how things differ. I'll report back.
