### ISSUE TITLE
Error: EntityHumanNPC

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1268]
Hello,

I have a bug with the latest version 1.12 of paperclip.

Error: https://hastebin.com/fexokibizo.cs
Build: git-Paper-1500 (MC: 1.12.2)
Citizens: Citizens v2.0.23-SNAPSHOT (build 1560)

Thank you for correcting that.

**Comment by zachbr** [comment]
```... Report this to https://github.com/PaperMC/Paper/issues/1223```

Report to GH-1223 as mentioned in the log.

**Comment by aikar** [comment]
Oddly, you told us the incorrect Paper version number, as that message was added in the most recent build which is not 1500.

It is not a bug, it is simply a debug information message. You can ignore it.
