### ISSUE TITLE
1.13: Depositing items in a furnace using a hopper. Items vanish from the hopper.

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#1270]
### What behaviour is expected:
Input a stack of items into a hopper which is pointed into a furnace. Expected a stack of items to go into the furnace.

### What behaviour is observed:
Items instantly vanish from the hopper. Sometimes 2 items per stack end up in the furnace.

### Steps/models to reproduce:
Have furnace, hopper, items. Place furnace. Place hopper into top of furnace. Deposit items into hopper. Check furnace.

### Plugin list:
vanilla MC server, but i have added Autorank and a chat bot.

### Paper build number:
git-paper-34 (MC:1.13)

### Anything else:
Permission to quickly list bugs for a few days would be nice. Forms... i don't like them.

**Comment by aikar** [comment]
Permission denied ;) Without everything asked, we wouldn't have the information needed to understand the report or judge context.

Looking for if anyone else can reproduce this.

I won't be able to work on anything tonight likely though, so looking for others.

**Comment by NullCase** [comment]
Thanks guys. You're pumping out updates like crazy. I'll keep downloading & testing on our public test server.

**Comment by aikar** [comment]
confirmed a bug in my hopper patch. im too tired to get it fixed tonight, will look tomorrow night unless someone can figure it out ahead of time.

**Comment by aikar** [comment]
I've removed the hopper patch for now until it can be fixed. Build 35.
