### ISSUE TITLE
/version throws an ssl error.

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#1271]
version (etc) information available here: https://github.com/PaperMC/Paper/issues/1270

when doing /version "Error obtaining version information" due to an ssl error.

24.07 22:12:24 [Server] INFO NullCase issued server command: /version
24.07 22:12:24 [Server] WARN javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
24.07 22:12:24 [Server] WARN at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
24.07 22:12:24 [Server] WARN at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
24.07 22:12:24 [Server] WARN at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
24.07 22:12:24 [Server] WARN at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
24.07 22:12:24 [Server] WARN at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
24.07 22:12:24 [Server] WARN at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
24.07 22:12:24 [Server] WARN at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
24.07 22:12:24 [Server] WARN at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
24.07 22:12:24 [Server] WARN at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
24.07 22:12:24 [Server] WARN at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
24.07 22:12:24 [Server] WARN at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
24.07 22:12:24 [Server] WARN at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
24.07 22:12:24 [Server] WARN at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
24.07 22:12:24 [Server] WARN at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
24.07 22:12:24 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
24.07 22:12:24 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
24.07 22:12:24 [Server] WARN at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
24.07 22:12:24 [Server] WARN at java.net.URL.openStream(URL.java:1038)
24.07 22:12:24 [Server] WARN at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
24.07 22:12:24 [Server] WARN at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
24.07 22:12:24 [Server] WARN at com.google.common.io.CharSource.openBufferedStream(CharSource.java:107)
24.07 22:12:24 [Server] WARN at org.bukkit.command.defaults.VersionCommand.getFromJenkins(VersionCommand.java:293)
24.07 22:12:24 [Server] WARN at org.bukkit.command.defaults.VersionCommand.getDistance(VersionCommand.java:266)
24.07 22:12:24 [Server] WARN at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:214)
24.07 22:12:24 [Server] WARN at org.bukkit.command.defaults.VersionCommand.access$000(VersionCommand.java:37)
24.07 22:12:24 [Server] WARN at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:199)
24.07 22:12:24 [Server] WARN at java.lang.Thread.run(Thread.java:745)
24.07 22:12:24 [Server] WARN Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by electronicboy** [comment]
If you're on ubuntu, do the following:
```
1. rm /etc/ssl/certs/java/cacerts file
2. run "update-ca-certificates -f"
```

This should cause your system to regenerate the needed certificate stores

**Comment by NullCase** [comment]
thanks @electronicboy 

It seems like I'll have to contact my host provider, but that's great advice.
