### ISSUE TITLE
1.13: Cave Spider Spawner not functional

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#1272]
### What behaviour is expected:
Spawner spawning mobs.

### What behaviour is observed:
Mobs don't spawn.

### Steps/models to reproduce:
Find mob spawner, observe whether mobs spawn.

### Plugin list:
Autorank, a chat bot.

### Paper build number:
git-Paper-37 (MC:1.13)

### Anything else:
I still don't like forms.

**Comment by NullCase** [comment]
OK, i've learned something new.

I'm on Paper 1.13 version 46 now (couple hours old)

In an unlit room the light levels remain high. The light prevents mobs from spawning.

https://i.imgur.com/LmpDZLZ.jpg

**Comment by electronicboy** [comment]
what is your random light tick setting set to in spigot.yml? also, have you tested this in spigot?

**Comment by NullCase** [comment]
random-light-updates: false

**Comment by electronicboy** [comment]
Try setting it to true, there are known issues around that setting on spigot

**Comment by NullCase** [comment]
OK, i set random-light-updates: true

at first the problem persisted: same bright areas.

I placed blocks in the brightest areas. once those blocks were updated the problem went away.
