### ISSUE TITLE
1.13: Getting kicked for Timed out when spectating

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#1274]
When spectating in the view of an entity I get kicked for "Timed out" after about 30 seconds. It does not happen when not in the view of an entity.

### What behaviour is expected:
No kick for Timeout

### What behaviour is observed:
Kick for timeout

### Steps/models to reproduce:
- /gamemode spectate
- Left-click an entity
- Wait 30 seconds

### Plugin list:
None

**Comment by 0-x-2-2** [comment]
this happens when a player stops sending serverbound movement packets.

**Comment by electronicboy** [comment]
got the full message from the server logs?

**Comment by Brokkonaut** [comment]
> [16:29:38 INFO]: [Brokkonaut: Set own game mode to Spectator Mode]
[16:30:10 INFO]: Brokkonaut lost connection: Timed out
[16:30:10 INFO]: Brokkonaut left the game

After setting the gamemode to spectator I left-clicked some random entity to switch to that entity's view
