### ISSUE TITLE
Cititzens plugin causing Entity loss with Paper

### ISSUE THREAD

**Issue by aikar** [PaperMC/Paper#1280]
After a bit of testing with @LogGits, we've discovered since build 1482 that Entities can be lost on chunk reloads.

Lots of initial suspicion was that it was due to the optimization work around current chunk lookups, but confusion since Sponge doesn't have any problems.

We then had lots of discussion at #1223 thinking it was dupe uuid related (which is a valid vanilla issue that issue is tracking), but it wasn't that either.

After review, it appears any Entity Type that you have an NPC of the same type loaded, is impacting the Entity Map and breaking saves.

Suspect is this change: https://github.com/PaperMC/Paper/commit/18c3716c49d53dbb02b1a9934ef6d2e017c51f70#diff-0e1eb6790ee1f97a3a4411d7fa7028d7R39

Because we precache the Entity ID, I'm thinking this lookup is failing somehow, causing it to get a null save ID.

@mcmonkeyforeva @fullwall do you have any suggestions on timing / best way to potentially fix this before we drop the precache optimization?

though I guess i could say if null, try looking up again.

**Comment by stevmei** [comment]
Moving to the matching issue...

Interesting. There are some people (me including) that have some teleport issues with Citizenz. A real player was teleported to an NPC which has the same name as the player. Maybe this could be related or is it just a coincidence?

Issue was CitizensDev/Citizens2/issues/910

**Comment by aikar** [comment]
@sigmaroot that should not relate to this issue.

**Comment by stevmei** [comment]
@aikar Okay thanks, so maybe it's still an issue with NCP as expected back then.

**Comment by aikar** [comment]
@logGits please try build 1515. Should be fixed now. I sadly can not recreate it in dev, but this is the most likely source.

**Comment by aikar** [comment]
apparently hes still having the issue

**Comment by aikar** [comment]
@LogGits has reported no more issues on latest builds.
