### ISSUE TITLE
PlayerPreTeleportEvent

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#1285]
If any plugin teleports a player using `Entity#teleport()`, and the player has at least one passenger, then in fact he will not be teleported, but the plugin will consider otherwise.

It is not possible to remove passengers from the player using `PlayerTeleportEvent`, as in this case it is not called. However, if it was called - it's still useless, because the player would not have been teleported.

So I suggest adding an `PlayerPreTeleportEvent` that will be called before the actual teleport, but immediately after `Entity#teleport()` is invoked, so that passengers can be removed using custom plugin and they do not interfere with the process of teleportation.

You can also solve this problem by removing passengers in the `Entity#teleport()` method itself.

**Comment by molor** [comment]
In mini-games, this can seriously interfere with the gameplay. For example, MobArena will assume that the player has been moved to the arena and already takes damage from mobs, but in fact he is on spawn and looks in the chat, what is now the wave number and what prizes he received.

**Comment by aikar** [comment]
I have changes in my fork that i've been meaning to bring to paper that allows entities to teleport with passengers, wouldn't that be better?

**Comment by BillyGalbreath** [comment]
@aikar I would love that teleport with passengers patch ^_^

**Comment by Proximyst** [comment]
Potential patches to pull for this issue:
- https://github.com/starlis/empirecraft/blob/efd7ea89f1dcff065072b474d04ca7a97612badc/patches/server/0060-Allow-Vehicle-Passenger-Teleporting-for-Bukkit-API.patch
- https://github.com/Minevictus/Papercut/blob/ffa263684dfc295eaadc106b668173582c395973/patches/api/0003-Add-EntityTeleportHinderedEvent.patch + https://github.com/Minevictus/Papercut/blob/ffa263684dfc295eaadc106b668173582c395973/patches/server/0004-Add-EntityTeleportHinderedEvent.patch

These are different solutions with different mindsets to the same problem, so we'll have to decide for one or the other. EmpireCraft's seems to be the one which would best fit in this case, given it fixes the contract in `Entity` which does *not* state vehicles cannot be teleported.

**Comment by Laarryy** [comment]
As far as I can read, this has been addressed at https://github.com/PaperMC/Paper/blob/master/patches/server/0920-More-Teleport-API.patch#L39-L63

If it hasn't or this code is faulty, please open a new issue for an amendment to the aforementioned patch. Thanks!
