### ISSUE TITLE
1.13: Nether Portal Behavior

### ISSUE THREAD

**Issue by hoorigan** [PaperMC/Paper#1286]
### What behaviour is expected:
Upon activating a nether portal, the player should be able to stand in the portal, and the player should be taken to the nether.

### What behaviour is observed:
Nether portals only seem to transport players to the nether intermittently.  When they do work, the portal spawned in the nether will have portal blocks missing and/or facing in the wrong direction.  Additionally, there are occasionally parts of additional portal frames sticking out of the spawned portal, as if the server had difficulty generating the portal frame.  Upon returning through the portal you just spawned, there is also a strong likelihood that you will pass through yet another portal spawned in the overworld, somewhere near your original portal.  The portal spawned in the overworld does not appear to have the same trouble as the portal spawned in the nether.

![2018-07-25_22 17 34](https://user-images.githubusercontent.com/14971345/43363960-a5cfded2-92de-11e8-93b1-102b443e4083.png)
![2018-07-28_22 59 33](https://user-images.githubusercontent.com/14971345/43363961-a92849f2-92de-11e8-9d02-d38fc7979749.png)

### Steps/models to reproduce:
1. Build a nether portal frame.
2. Activate the portal with flint and steel.
3. Walk into the portal blocks, see if you are transported.
4. If so, check the frame of the portal spawned in the nether.

### Plugin list:
None.

### Paper build number:
[03:23:59 INFO]: This server is running Paper version git-Paper-52 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[03:23:59 INFO]: Previous version: git-Paper-48 (MC: 1.13)
[03:23:59 INFO]: Checking version, please wait...
[03:24:00 INFO]: You are running the latest version

### Anything else:
I wish I had more useful information.  Nothing is logged, even with debug enabled.

**Comment by VADemon** [comment]
I can partially confirm this behaviour on 1.12.2

I went from Nether to Overworld and it obviously took the server 3 tries to finally generate a working portal on the other side. There were 3 vertically stacked portal frames, without portal blocks inside 2 of them. The teleport attempt obviously "timed out"  because I had been waiting for much longer than needed each time for the server to teleport me, and on 3rd try it succeded.

It was on a high Y-level in Nether (below roof) and above an Ocean.

**Comment by prplz** [comment]
I'm having similar behaviour on git-Paper-70, although I managed to travel to the nether successfully the first time, I couldn't get out after travelling some distance in the nether and constructing another portal to travel to the overworld. After a few server restarts I managed to get through and found all the portals it generated. The portal that actually "worked" only had one portal block inside it.
![image](https://user-images.githubusercontent.com/2089783/43457446-3ca6fe1c-950a-11e8-90a5-495dd965f9d0.png)

**Comment by hoorigan** [comment]
Because it came up in another issue I had, are either of you running a BungeeCord/Waterfall proxy?  Or are you both connecting directly to your servers?

**Comment by prplz** [comment]
No proxy

**Comment by electronicboy** [comment]
Has anybody tested/replicated this upstream?

**Comment by hoorigan** [comment]
This works fine on the following Spigot version, without a proxy:

This server is running CraftBukkit version git-Spigot-69774b3-549d9b0 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

**Comment by prplz** [comment]
My money is on https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0278-Call-PortalCreateEvent-for-exit-portals.patch right now

**Comment by qixils** [comment]
Some newly generated portal blocks still face the wrong direction as of paper 78

**Comment by zachbr** [comment]
Make that two reports.

```<prplz> not sure if it's linked to the bug i fixed, but portals still look weird in 1.13```

![portal](https://user-images.githubusercontent.com/1254957/43626820-20baa798-96b9-11e8-9755-b851e4fccb6d.png)

Re-opening this issue pending further testing and investigation.

**Comment by zachbr** [comment]
I believe I have fixed this issue. I am no longer able to reproduce this at all.
Builds 83+

Thanks for the reports. 👍
