### ISSUE TITLE
1.13: Optimize World.a(double d0, double d1, double d2, double d3, Predicate<Entity> predicate)

### ISSUE THREAD

**Issue by aikar** [PaperMC/Paper#1289]
This method iterates all players in a world and compares distance.

Optimize this to behave like getNearbyEntities (or use it) and only iterate potential chunks

**Comment by aikar** [comment]
Also cover the method directly below it: isPlayerNearby for same thing

**Comment by aikar** [comment]
And add    

`public EntityHuman a(double d0, double d1, double d2, double d3, double d4, @Nullable Function<EntityHuman, Double> function, @Nullable Predicate<EntityHuman> predicate) {`

Dang a lot of bad methods here...

**Comment by Proximyst** [comment]
This doesn't seem to be an issue anymore, from the looks of things without any actual information, at least. Reopen the issue if you disagree, and please add information as to why you do in that case.
