### ISSUE TITLE
Running version from the console throws stacktrace

### ISSUE THREAD

**Issue by stefvanschie** [PaperMC/Paper#1294]
When running `version` from the console, it throws the following stacktrace: https://hastebin.com/weniyuxori.md

Tested on git-Paper-1523 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT).

I didn't have any plugins running (I tested it twice both with and without plugins and both tests resulted in the same error) and there were no players online.

**Comment by electronicboy** [comment]
See #1271, your cert store is outdated/busted
