### ISSUE TITLE
[1.13] Going from a long portal to a shorter portal causes issues

### ISSUE THREAD

**Issue by qixils** [PaperMC/Paper#1295]
### What behaviour is expected:
Entering a long nether portal, say 4 block long portal for example, which leads to a shorter portal, say only 2 blocks long, should put you in the portal.

### What behaviour is observed:
Instead, you get placed on top of the portal, which in some cases can result in a player getting sucks on the nether roof.

### Steps/models to reproduce:
1. Create a 4x4 portal, or any portal which is longer than the usual 2 blocks.
2. Go into one of the edges of the portal.
3. You should be placed on top of your portal in the nether.

### Plugin list:
CoreProtect

### Paper build number:
git-Paper-73 (1.13)

### Anything else:
This may not occur when generating a new portal in the nether, however I haven't tested this. Going from a smaller to a larger portal, as well as one portal to a portal of the same size also works. Only going from a large portal to a smaller portal causes issues.

**Comment by zachbr** [comment]
Please update and re-test on the latest build.
Changes have been made in this area since your version.
Thanks

**Comment by qixils** [comment]
oh whoops, 60 was my previous version. i am on the current latest build of 73 
![image](https://user-images.githubusercontent.com/13265322/43479259-f5f0393e-94cd-11e8-84fd-700b9068d0a7.png)

**Comment by zachbr** [comment]
Should be fixed in builds 78+
Thanks for reporting.

**Comment by AJMFactsheets** [comment]
Any chance this patch can also be applied to the stable 1.12.2 branch? I've just had it happen in build #1547.
Thanks
