### ISSUE TITLE
New logger is broken on Windows

### ISSUE THREAD

**Issue by amadeusmz** [PaperMC/Paper#1297]
### What behaviour is observed:
https://i.imgur.com/MuObYap.png

### Steps/models to reproduce:
This happen after the server start for several hours, maybe this only happen on ConEmu, I use ConEmu so I can easily manipulate servers, haven't tried Windows default console yet.
This also happen on Waterfall

### Paper build number:
1518
I  can't identify which build this issue started.

### Anything else:
Revert to the old logger?

**Comment by aikar** [comment]
We will not be reverting as these logger changes are massively superior.

I'm not sure how feasible even providing a config option would even be.

When did the issue start? theres been multiple phases to logger updates.

But I believe there was another recent issue where a non standard windows terminal, possibly conemu, was reported to have an issue with the updated jline.

@Minecrell

**Comment by MiniDigger** [comment]
that is strange. I heard ppl having issues with ConEmu, but that was on waterfall. I personally run ConEmu with paper just fine.
could also be a weird interaction between jline, conemu and your ssh client? do you use wls to use ssh? 
it would help if you could share your whole setup so we could try to nail it down.

**Comment by electronicboy** [comment]
That looks like your window resized but the terminal wasn't properly notified of the change (it appears that there have been other issues with conemu and it's lack of proper support for a few things), try using a different console emulator?

You can disable the newer terminal using `-Dterminal.jline=false` and use the fallback

**Comment by amadeusmz** [comment]
This issue is caused by adding `chcp 65001` into the batch file, after removing it the issue seems to be gone now.

**Comment by amadeusmz** [comment]
Nope... the bug is still there

**Comment by Proximyst** [comment]
As this has almost lived on 2 years and there have been no reports of this in a while, I'll close this issue. If you happen to come over it again, please open a new issue (or comment here to have it reopened, I suppose).
