### ISSUE TITLE
Scoreboard teams color in chat

### ISSUE THREAD

**Issue by Artuto** [PaperMC/Paper#1299]
Hi, So basically when a team has a color it is not shown in the chat, instead only on the tab list. However this doesnt replicates Vanilla functionallity, since it should display the color in the chat.

I hope it can be fixed.

**Comment by electronicboy** [comment]
There is a configuration option in paper.yml for this `use-vanilla-world-scoreboard-name-coloring`, how well that works is however 100% dependant on your plugins

**Comment by Artuto** [comment]
This doesnt work, and I dont have any plugin modifing chat.

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/43574568-6e6acb44-963c-11e8-9950-047909b96e82.png)
Working fine here, worth noting that there are several ways to break this, mainly being plugins which modify player display names and chat formatting plugins

We need more information about your setup, etc, plugins, how are you modifying the scoreboard? (i.e. the general information which you should have filled in from the template)

**Comment by Artuto** [comment]
Oh, well the template didnt appeared so uh. But I think I got it fixed. Thx anyway
