### ISSUE TITLE
1:13 - Horse bug

### ISSUE THREAD

**Issue by DoreK333** [PaperMC/Paper#1303]
### What behaviour is expected:
It should be possible to enter the horses

### What behaviour is observed:
You can not get on a horse - when you move your head, the head of the horse also moves in the same direction, although I do not sit on a horse.
When I click Shift it's like I'm going off a horse (then the horse's head does not move)

### Steps/models to reproduce:
Video: https://youtu.be/FzDESiIY7rI
### Plugin list:
WorldEdit, WorldGuard, DynamicBungeeAuth

### Paper build number:
paper-89
### Anything else:
lack

**Comment by Black-Hole** [comment]
Please try to reproduce without WorldGuard and please use the forums for help configuring WorldGuard.

**Comment by aikar** [comment]
the behavior you see is expected anytime riding the horse is denied. vanilla handles it very funky.
as black hole suggested, it would likely be your worldguard plugin denying your ride.

**Comment by DoreK333** [comment]
After removing WorldGuard, the problem persists.

**Comment by aikar** [comment]
![](https://i.imgur.com/1irBtr9.png)

I'm able to get on horses just fine, only using Citizens, Essentials, Essentials Chat and Multiverse Core

Please ensure your bungee is up to date as well as paper and your not using any protocol hack plugins for either.

**Comment by DoreK333** [comment]
After the waterfall update, the problem was fixed. I apologize for my oversight.
