### ISSUE TITLE
setPlayerProfile API for org.bukkit.block.Skull

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#1307]
Currently the setPlayerProfile API is only available for SkullMeta (items) but not for org.bukkit.block.Skull (blocks).

Would be nice to have it there too.

This is the setPlayerProfile API for SkullMeta:
https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0082-Add-SkullMeta.setPlayerProfile-API.patch
https://github.com/PaperMC/Paper/blob/pre/1.13/Spigot-Server-Patches/0233-Add-SkullMeta.setPlayerProfile-API.patch

**Comment by aikar** [comment]
merged
