### ISSUE TITLE
NullPointerExeption on join [When using ProtocolSupport]

### ISSUE THREAD

**Issue by Tim-NL** [PaperMC/Paper#131]
In the latest version I'have got this; 

https://snapr.pw/i/590f3a178d.png

---

No errors in the console.
And I'm using ProtoclSupport so I'm not sure if thats an problem.

**Comment by zachbr** [comment]
There is zero usable information here. This may end up being closed unless there's something blatant being over looked :/

**Comment by Tim-NL** [comment]
I don't know what information I can give; 

Some info i can give;
#555 works fine. 

I'm using ProtocolSupport and I'm joining using 1.8.7 

#556 gives the error from the screenshot, the console gives;

23.03 21:14:47 [Server] [info] UUID of player Tim_kwakman is c0af31e4-f321-42c1-b98e-414dee6141f7
23.03 21:14:48 [Connect] User Tim_kwakman, IP -snip-
23.03 21:14:48 [Server] Tim_kwakman ran command Message of the Day
23.03 21:14:48 [Disconnect] User Tim_kwakman has disconnected, reason: Disconnected

So i can't give any more usefull information, because there isn't any. 

(Testen on 2 servers, behind an bungeecord, both have the same.)

**Comment by Tim-NL** [comment]
---

Just tested it and its only when ProtoclSupport is installed, but it seems to work 100% fine on build #555

**Comment by zachbr** [comment]
Test against latest Spigot so we can figure out where we need to look. All we did that looks like it could have caused that was merge with their changes

**Comment by Tim-NL** [comment]
Okay, sorry for the late response, but here it is;

Spigot 1.9 (latest build) works perfect. 

Latest Paper build gets this error on Minecraft 1.9; https://snapr.pw/i/fbd9faa6f9.png (1.8 gives the nullpointer)

**Comment by willies952002** [comment]
I can confirm that this is an issue. Here is my latest.log: https://hasteb.in/fifupepuvi.log
I have narrowed it down to an issue that is being caused by ProtocolSupport when it's installed as this same server build is working properly otherwise.

**Comment by zachbr** [comment]
@Tim-NL @willies952002 Thank you both for the information. I will try and look into this soon. Hopefully we can figure out where the issue is and get it resolved.

**Comment by zachbr** [comment]
I believe this was fixed on their end, I'm not aware of anything we've done that could have fixed this.
Regardless, this issue is no longer relevant. The latest development builds of ProtocolSupport work fine on the latest Paper builds.
