### ISSUE TITLE
Failed to resolve dependency while building:

### ISSUE THREAD

**Issue by DreadKyller** [PaperMC/Paper#1311]
Upon getting to the --jar part of the build script, running "mvn clean install" starts its work and after a moment I find myself with this error:

`[ERROR] Failed to execute goal on project paper-api: Could not resolve dependencies for project com.destroystokyo.paper:paper-api:jar:1.12.2-R0.1-SNAPSHOT: Failed to collect dependencies at com.mojang:authlib:jar:1.5.25: Failed to read artifact descriptor for com.mojang:authlib:jar:1.5.25: Could not transfer artifact com.mojang:authlib:pom:1.5.25 from/to aikar (https://repo.aikar.co/content/groups/aikar/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]`

**Comment by stephan-gh** [comment]
Probably related to https://github.com/PaperMC/Paper/issues/1271

**Comment by DreadKyller** [comment]
Potentially, although the two issues seem quite different from each other. I see the `PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` is shared between them. However I'm running on a windows machine using the bash client provided by git and mysys. So I don't have a /ect/ssl folder so that post doesn't help me.

**Comment by electronicboy** [comment]
Duplicate of #1271 
You need to fix your servers ca-certificate store, for ubuntu, see the issue linked
Your issue is your java client cannot verify the ssl certificates trust path to the root

**Comment by DreadKyller** [comment]
@electronicboy, please read what I said above to the previous person who also references that post. I am NOT on Ubuntu, that post does nothing for me, thanks for closing this issue and preventing me from ever getting a working answer. The commands provided there do not work for me because like I said I'm not on Ubuntu, I do not have an /etc/ssl directory, and "run" isn't a valid command. I'm building this on my local machine, not a server, and I'm on windows using the bash environment provided with git.

**Comment by electronicboy** [comment]
I've read what you said, the issue is closed as it's not something on our side

I can read the error message, and I've explained what it means, your java installation has a broken certificate store, depending on your OS depends on the route you need to go to fix that

**Comment by DreadKyller** [comment]
Well I did the alternative for Windows that I could find and it immediately broke again. And it's only that specific repository, no where else does maven have any issues. I just ended up manually going to the repo and downloading the required filed manually and adding them to my local .m2 repository, fortunately only two files were needed from that repo.

**Comment by aikar** [comment]
@DreadKyller this is usually caused by out of date Java.

Other repos work for you because those repos do not use LetsEncrypt. We do... so you must use a new enough java that supports LetsEncrypt.

**Comment by aikar** [comment]
Also the snarky response was not needed. We are perfectly capable of still holding a discussion here (but discord is better) for support issues with it being closed.

There is not an 'issue' in paper, so it did not need to be open.
