### ISSUE TITLE
Crash in chunk loading when player join!

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1317]
### Plugin list:

    Broadcaster*, ChatControl, ChatFormat*, Citizens, CoreProtect, DisableJoinMessage*, 
    DiscordSRV*, Essentials*, EssentialsAntiBuild*, EssentialsChat*, EssentialsSpawn*,
    FBasics*, GroupManager*, LagAssist*, LiteBans*, Lockette*, PlaceholderAPI*, 
    ProtocolLib*, Residence, TitleManager*, Vault*

### Actions to reproduce (if known):
    Chunk loaded..? i dont know

### Paper build number:
    Paper version git-Paper-112 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

### [https://pastebin.com/RK9yuEc3](https://pastebin.com/RK9yuEc3)

**Comment by prplz** [comment]
Does it happen without plugins?

**Comment by ghost** [comment]
Yes

**Comment by aikar** [comment]
You have a corrupted region file. Did you convert a 1.12 world?

Ultimately, this wasn't an issue with Paper, however I just pushed build 115 that will solve this issue for you by auto repairing the region file.
