### ISSUE TITLE
PlayerInterractEvent event call error

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1318]
Hello,

We found a bug using the "PlayerInterractEvent" event for a plugin to convert the experience into a bottle. We use this event, by clicking on the exp bottle, to give the player the amount of experience contained in the bottle.
Only, sometimes, the event is not called and the bottle is used as a simple bottle of experience. We figured out how to reproduce the problem, here is a video : https://www.youtube.com/watch?v=ztAZlYow32Y&feature=youtu.be

In fact, spawn an entity (here a pig) and quickly clicking aiming at the entity does not call the event at the first click.

Version: **git-Paper-1534 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**

Can you do what is necessary to correct the problem?

Thanks,

**Comment by Black-Hole** [comment]
You might want to provide the code used.

**Comment by ghost** [comment]
Code here: https://hastebin.com/apazidadiy.cs

**Comment by mikroskeem** [comment]
Repaste this to gist.github.com as pastes on hastebin expire and coming here weeks/months later leads to getting no useful information.

**Comment by ghost** [comment]
Here: https://gist.github.com/Heliosard/3a3e42144b053f1ac9d1aff8061b7453

**Comment by ghost** [comment]
I'm sorry to insist, but it's quite problematic on our server.

**Comment by aikar** [comment]
I think you also need to handle PlayerInteractEntityEvent is your issue.

**Comment by aikar** [comment]
Please open a new issue if you need further assistance
