### ISSUE TITLE
World#isChunkGenerated(x, y) / Chunk#isGenerated()

### ISSUE THREAD

**Issue by Blazzike** [PaperMC/Paper#1329]
**Is your feature request related to a problem? Please describe.**
This feature request is related to the lack of an API for checking if a chunk has been generated.

**Describe the solution you'd like**
Simply adding either or both methods: World#isChunkGenerated(x, y) and Chunk#isGenerated()

**Describe alternatives you've considered**
World#loadChunk(x, z, false) was suggesed as an alternative to checking if a chunk has been generated but will load the chunk while doing so.

**Comment by aikar** [comment]
I think you meant Location.isGenerated(), as you can't get a Chunk reference without it being generated :P

**Comment by Blazzike** [comment]
Oh, I assumed because Chunk#isLoaded was a method that you could. I was unsure. :P
