### ISSUE TITLE
Survival players are able to phase through blocks using mountable entities

### ISSUE THREAD

**Issue by GlowHack** [PaperMC/Paper#1332]
### What behaviour is expected:
Survival players should not have the abilities to phase through walls with mounted entities, or in general.

### What behaviour is observed:
If a mountable entity is inside of a block, it is able to phase through the world with the use of a simple hacked client.

### Steps/models to reproduce:
Simply get a ride-able entity, preferably a boat, put sand upon its head, then with the use of a hacked client, the entity is able to phase through all blocks. this can lead to many normally unassailable places to be accessible. 

### Plugin list:
None

### Paper build number:
git-paper-1536 Minecraft-1.12.2

### Anything else:
no.

**Comment by aikar** [comment]
anti cheat to this level is outside of the scope of the Paper projects level. This is best solved through plugins, as it's extremely complex.
