### ISSUE TITLE
Banner Related Crashes

### ISSUE THREAD

**Issue by electro2560** [PaperMC/Paper#1337]
### Link/paste of stack trace

    https://pastebin.com/wwDyEN7b

### Actions to reproduce (if known):
It seems the changes first introduced in build 135 cause crashes regarding banners. When having the server running with a player standing still, it seems to randomly crash without the player ever moving or doing anything.

### Paper build number:
136

Possibly related to issue #1336

**Comment by aikar** [comment]
duplicate of 1336, resolved in build 138

**Comment by hafarooki** [comment]
This issue brings shame to the name of 1337

**Comment by Miclebrick** [comment]
https://i.imgflip.com/nmr99.jpg
http://instagramnyc.com/images/1333-meme-rcm480x0.jpg

I restored honor to its name
