### ISSUE TITLE
1.12.2 issue

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Paper#1343]
17.08 07:50:59 [Server] WARN Duplicate UUID found used by EntityPig['Pig'/1409231, uuid='d308c3eb-fac5-43c9-9f39-3e9f667a5813', l='ASkyBlock', x=2060.59, y=8.00, z=5706.57, cx=128, cd=356, tl=5318276, v=true, d=false], regenerated UUID for EntityPig['Pig'/1410435, uuid='961a9b12-6e85-40b6-9826-93a968b54950', l='ASkyBlock', x=2060.59, y=8.00, z=5706.57, cx=128, cd=356, tl=5318276, v=false, d=false]. See https://github.com/PaperMC/Paper/issues/1223 for discussion on what this is about.
17.08 07:50:59 [Server] WARN Duplicate UUID found used by EntityMushroomCow['Mooshroom'/1409232, uuid='397b818d-2164-4d64-9d16-8d6da22d92ca', l='ASkyBlock', x=2054.61, y=171.00, z=5698.20, cx=128, cd=356, tl=42127413, v=true, d=false], regenerated UUID for EntityMushroomCow['Mooshroom'/1410436, uuid='1a568e05-8000-4f69-9ee4-ac15fda9563e', l='ASkyBlock', x=2054.61, y=171.00, z=5698.20, cx=128, cd=356, tl=42127413, v=false, d=false]. See https://github.com/PaperMC/Paper/issues/1223 for discussion on what this is about.
17.08 07:50:59 [Server] WARN Duplicate UUID found used by EntityCow['Cow'/1409233, uuid='2e94d7fb-e621-405b-a8ed-f78d8197831b', l='ASkyBlock', x=2063.49, y=174.00, z=5707.84, cx=128, cd=356, tl=41229154, v=true, d=false], regenerated UUID for EntityCow['Cow'/1410437, uuid='4a3f2ae9-f61f-46f3-8608-62bd49f9bbae', l='ASkyBlock', x=2063.49, y=174.00, z=5707.84, cx=128, cd=356, tl=41229154, v=false, d=false]. See https://github.com/PaperMC/Paper/issues/1223 for discussion on what this is about.
17.08 07:50:59 [Server] WARN Duplicate UUID found used by EntityVillagerNPC['Villager'/1409234, uuid='69a9a2d9-5634-4f44-8e2e-35d1db337e5e', l='ASkyBlock', x=2063.30, y=179.00, z=5703.30, cx=128, cd=356, tl=2815584, v=true, d=false], regenerated UUID for EntityVillagerNPC['Villager'/1410438, uuid='3d2d8c58-c2ca-4ad8-8474-55bb53b5350a', l='ASkyBlock', x=2063.30, y=179.00, z=5703.30, cx=128, cd=356, tl=2815584, v=false, d=false]. See https://github.com/PaperMC/Paper/issues/1223 for discussion on what this is about.
17.08 07:50:59 [Server] WARN Duplicate UUID found used by EntityVillagerNPC['Villager'/1409235, uuid='3e0f518b-9dbe-43ac-87cc-344bf5635240', l='ASkyBlock', x=2063.30, y=179.00, z=5704.99, cx=128, cd=356, tl=2812808, v=true, d=false], regenerated UUID for EntityVillagerNPC['Villager'/1410439, uuid='6b2aa005-e380-4bd3-b267-f616926b269c', l='ASkyBlock', x=2063.30, y=179.00, z=5704.99, cx=128, cd=356, tl=2812808, v=false, d=false]. See https://github.com/PaperMC/Paper/issues/1223 for discussion on what this is about.
17.08 07:50:59 [Server] WARN Duplicate UUID found used by EntityVillagerNPC['Villager'/1409236, uuid='fd8f89fa-4f0e-455f-8771-010c9800633b', l='ASkyBlock', x=2063.30, y=179.00, z=5706.99, cx=128, cd=356, tl=2792066, v=true, d=false], regenerated UUID for EntityVillagerNPC['Villager'/1410440, uuid='984fa10e-40f5-4329-9f5e-67ddbc9d48a5', l='ASkyBlock', x=2063.30, y=179.00, z=5706.99, cx=128, cd=356, tl=2792066, v=false, d=false]. See https://github.com/PaperMC/Paper/issues/1223 for discussion on what this is about.
17.08 07:50:59 [Server] WARN Duplicate UUID found used by EntityVillagerNPC['Villager'/1409237, uuid='679b732a-8ee9-440f-9209-0c802c29b07e', l='ASkyBlock', x=2063.50, y=179.00, z=5710.59, cx=128, cd=356, tl=99891, v=true, d=false], regenerated UUID for EntityVillagerNPC['Villager'/1410441, uuid='9608d8da-292e-49f7-a334-c962fe20c027', l='ASkyBlock', x=2063.50, y=179.00, z=5710.59, cx=128, cd=356, tl=99891, v=false, d=false]. See https://github.com/PaperMC/Paper/issues/1223 for discussion on what this is about.
17.08 07:51:07 [Server] INFO <~❤Nyan=＾● ⋏ ●＾=Nyan❤~❤~❤~Lazi> mhm

**Comment by VADemon** [comment]
Update to the latest Paper build.

UPD: And actually read #1223

**Comment by Cobwebster** [comment]
kk i updated, so i gotta do

Please go edit your configs and set:
duplicate-uuid-resolver: saferegen
in your default world config

?
