### ISSUE TITLE
setViewDistance() not working as expected

### ISSUE THREAD

**Issue by CGsama** [PaperMC/Paper#1349]
### What behaviour is expected:
setViewDistance() should set the view distance for a player

### What behaviour is observed:
view distance setting in spigot.yml will set the lower bound for the setting 

### Steps/models to reproduce:
in server.properties set the view distance to 2
in spigot.yml set the view distance to 2
the api can set view distance from 2

in spigot.yml set the view distance to 10
when player join, it can set to 2, soon then start load 10 chunk, after that the api cant set lower than 10

### Plugin list:
https://www.spigotmc.org/resources/set-my-view-distance.59822/

### Paper build number:
1104

### Anything else:
View distance setting in spigot.yml looks take control of mob render distance as well. 
So that whatever view distance i set using the api, the mob or player render distance will follow the setting in spigot.yml
i.e. even I can see the map for 64 chunk, but mobs i only can see 2 chunk, but i can hear the sound (so weird)
Seems like that will override the server view distance setting.

Expect the api can set spigot view distance as well, or create another lile setMobViewDistance()

**Comment by aikar** [comment]
it is a known bug that were looking for help fixing as noone has had time to look at it on our team.

as for entities range, that is configured on entity-tracking-ranges in spigot.yml and has never been bound to view-distance (not even in vanilla).

You would need an alternate tracking range API to support that.

**Comment by CGsama** [comment]
I have tried that in spigot.yml, i only change the view distance, it also affact the mob setting, one pic i set to 2, another set to 10.

![2018-08-19_04 44 38](https://user-images.githubusercontent.com/15722562/44307174-bea34780-a36b-11e8-964a-60deff05591f.png)
![2018-08-19_04 46 12](https://user-images.githubusercontent.com/15722562/44307176-c2cf6500-a36b-11e8-920b-c7c8428492f1.png)


As the picture shows, I can't see the villager. However, I can hear the sound of the villager.
So i guess it not affact the mob logic, but how the mob show to player.

If I set to 0(or 1 i cant remember), i cant see any mobs or player, but terrain display as i set

Thanks

**Comment by zachbr** [comment]
Also worth noting that there is (was?) a bug with the client not unloading chunks. Either use the client debug menu to force reload the chunks or leave the area and come back.

The chunks are unloading server side but the client isn’t updating to show that.

**Comment by aikar** [comment]
FYI View Distance is restricted to 3-32, so 2 and 64 are not valid values.

In order to avoid it from sending the full view distance, you MUST call it in PlayerJoinEvent.

**Comment by CGsama** [comment]
Sorry maybe I didnt explan clearly for the picture. Attachment is a short video to show that.
At 00:22 is the issue of mob render, and at 01:35 is the control sample.
After 02:45 shows the issue of the override.

https://github.com/CGsama/issue1349/blob/master/issue1.mp4

Thank you.

**Comment by aikar** [comment]
That sure is weird. I see what you mean in that even though you set reduced view distance, it still sent farther.

I spent some time looking at that code but it really didn't make sense, as the code looks fine...

As for the tracking ranges, I think to solve that we would need to retrack all entities on view distance change.
