### ISSUE TITLE
"Entities cannot die" problem occurs again

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#135]
With build 555 of Paper the bug which should got fixed in [this commit](https://github.com/PaperMC/Paper/commit/ba0da2d2ddadbaec4dbe69771838e7fe234fc9bd) occurs again.

This is the old issue report: https://github.com/PaperMC/Paper/issues/108

**Comment by zachbr** [comment]
Cannot reproduce in build 559. Please update and re-test. Upstream has been tinkering with the damage API implementation for some time now.

**Comment by ghost** [comment]
Forgot to add that the problem occurred and then disappeared again without even a restart. At the moment we can't reproduce it either but I will upgrade the version ASAP.

**Comment by aikar** [comment]
actually curious how it would of happened again considering I block the NaN values o.o

must be setting damage another way that doesnt go through the filter I added.

**Comment by ghost** [comment]
Problem also occurred with version 575. Sadly I don't know any way to reproduce the bug. The bug just appears after 16 hours uptime without any obvious reason and disappears after an hour...

**Comment by Brokkonaut** [comment]
We had the same bug on Spigot 1.9 (switched to Paper today) - Afaik in a whole chunk the entities do not tick anymore. When I move some entity to the same chunk where other frozen mobs are, it will also be frozen. When the chunk is reloaded (Every player moved away and back to the chunk some time later) the entities will move again.

I hope this can help finding the cause of the bug..

**Comment by ghost** [comment]
We really need a bugfix for this. Seems like minecarts are also impacted and don't drop as a item if they get destroyed.

**Comment by zachbr** [comment]
Can we have a status update? Please use the latest version and let us know how that's working. A lot has changed since this ticket was opened. Use build 689 or newer. Thanks :)

**Comment by ghost** [comment]
The issue isn't fixed with build 702.

If the bug appears also gravel and sand are affected. They just loose their gravity until the chunks works again.

**Comment by zachbr** [comment]
Has anyone come up with any way to consistently reproduce this behavior?
As it is, we're essentially waiting for someone to "happen upon it" and fix it then and there, and seeing as many of us cannot reproduce it, that really hurts the chances of getting this fixed.

**Comment by zachbr** [comment]
If someone is still seeing this on latest, leave a reply and  I'll re-open this ticket.
