### ISSUE TITLE
EntityNameable issue

### ISSUE THREAD

**Issue by NotMyFault** [PaperMC/Paper#1351]
### Link/paste of stack trace

   https://hasteb.in/eticeleb.yaml

___We need all of the stack trace! Do not cut off parts of it.___

### Plugin list:
![](https://i.imgur.com/dIOhPkQ.png)

### Actions to reproduce (if known):
N/A
The messages (`EntityNameable['Welcome To Tutorials'/35413...`) occurring in the stack trace are from this (https://www.spigotmc.org/resources/holograms.4924/) hologram plugin I'm using. It doesn't affect the holograms, it just spams my console. 
### Paper build number:
1548

**Comment by aikar** [comment]
Please add this information to https://github.com/PaperMC/Paper/issues/1302 as the log message states.

I'll have to see what that hologram plugin is doing.
