### ISSUE TITLE
Paper is stripping newline console messages from plugin start-up verbose.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#1353]
Paper dev 1547 (Spigot 1.12.2)

RE: https://github.com/garbagemule/MobArena/issues/488#issuecomment-414123953

Paper seems to be stripping newline character plugin messages from plugin start-up verbose. Downgrading to Spigot, the messages display fine.

Possible related patches.
* https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0210-Use-TerminalConsoleAppender-for-console-improvements.patch
* https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0236-Use-Log4j-IOStreams-to-redirect-System.out-err-to-lo.patch
* https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0239-Disable-logger-prefix-for-various-plugins-bypassing-.patch

**Comment by aikar** [comment]
cc @Minecrell

**Comment by stephan-gh** [comment]
Hmm, I cannot reproduce this:
https://gist.github.com/Minecrell/abbc5748763eeb0e5f29c1e290f58b12#file-gistfile1-txt-L109-L113

Have you tried it outside of Multicraft?

**Comment by mibby** [comment]
I have not tried this outside of Multicraft yet, but seeing as Spigot works perfectly fine with the same multicraft configuration from my testing in a second environment, I'm not sure that is a factor. Unless perhaps there is a plugin conflict with my production server?

I'll do some further testing in a little bit.

**Comment by stephan-gh** [comment]
One difference with the message compared to Spigot is that Paper logs errors in red color. Maybe this is confusing Multicraft's console parsing.

**Comment by mibby** [comment]
That could possibly be it. I have multicraft stripping all colors from console with I believe ```Djline.terminal=jline.UnsupportedTerminal``` in the java startup arguments. Mainly so the log file doesn't have unsupported / unknown character blocks in the log for messages that were colored. (Old issue, not sure if still existing.)

Full multicraft jar config.
https://paste.ubuntu.com/p/kvScFXbCWd/

**Comment by stephan-gh** [comment]
@mibby `-Djline.terminal=jline.UnsupportedTerminal` doesn't have any effect on Paper, a similar option is called `-Dterminal.jline=false` or alternatively just use the `--nojline` command line option (this should work on both Spigot and Paper).

Can you try adding one of these?

**Comment by mibby** [comment]
@minecrafter Sure. However replacing the jline argument did not seem to fix the problem.

Upon further deep testing, it seems to be a conflict with the plugin ConsoleSpamFix.

ConsoleSpamFix v1.6.0
Paper dev 1550 (Spigot 1.12.2)

CSF Config
https://paste.ubuntu.com/p/ZX2D5KNpnb/

I'm not sure why it is conflicting and stripping newlines, as my config isn't set to do so, but I'll forward this to the appropriate dev since I don't think it is an issue with Paper - unless Paper isn't happy with the plugin. @brunyman

**Comment by aikar** [comment]
CSF will need to add support for console lines containing colors. On that note going to close since nothing we can do to fix the plugin outside of turning off colors, which isn't an option.

**Comment by stephan-gh** [comment]
@mibby I'm not sure why it doesn't hide that message on Spigot (did you test with CSF installed?), but I'd say that everything works as expected here. You have instructed CSF to hide messages containing `Failed to parse`, which happens to be part of the error that isn't showing up in your console:

```
Failed to parse wave growth for wave normal1 of arena default: 2
```

**Comment by mibby** [comment]
Doh. Can't believe I didn't connect ```Failed to parse``` with MobArena's error message containing it too. But wouldn't the newline empty lines still show up?

**Comment by aikar** [comment]
No, its one log message

**Comment by aikar** [comment]
im sure theres prob a filter for completely empty lines.
