### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by randalz-z** [PaperMC/Paper#1354]
EntityPlayer['SheyderTeyl'/695, uuid='24d62611-d8dc-36ef-9008-722bc6d77772', l='world', x=151.76, y=68.00, z=-369.92, cx=9, cd=-24, tl=82954, v=false, d=true](SheyderTeyl at 151.7637030806323,68.0,-369.92332113994655) was removed from a entitySlice we did not expect. Report this to https://github.com/PaperMC/Paper/issues/1302
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: java.lang.Throwable
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: 	at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:758)
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: 	at net.minecraft.server.v1_12_R1.Chunk.b(Chunk.java:741)
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:723)
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: 	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1537)
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:683)
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921)
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: 	at java.lang.Thread.run(Thread.java:748)
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: EntityPlayer['SheyderTeyl'/695, uuid='24d62611-d8dc-36ef-9008-722bc6d77772', l='world', x=151.76, y=68.00, z=-369.92, cx=9, cd=-24, tl=82954, v=false, d=true](SheyderTeyl at 151.7637030806323,68.0,-369.92332113994655) was removed from a entitySlice we did not expect. Report this to https://github.com/PaperMC/Paper/issues/1302
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: java.lang.Throwable
20.08 17:29:49 [Server] INFO K[17:29:49 WARN]: 	at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:758)

**Comment by aikar** [comment]
Please report to the correct issue as the log line says.
