### ISSUE TITLE
debug netty (informations) paperclip 158 - netty

### ISSUE THREAD

**Issue by minecraft7net** [PaperMC/Paper#1358]
[09:22:23] [Server thread/INFO]: This server is running Paper version git-Paper-158 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

[09:22:23] [Server thread/DEBUG]: [io.netty.util.internal.NativeLibraryLoader] Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.

https://pastebin.com/FfPeWuGN

java: jdk1.8.0_162

start options: 
INVOCATION="/opt/java/jdk1.8.0_162/bin/java -Xmx4G -Xms2G -Dpaper.playerconnection.keepalive=60 -jar $SERVICE $OPTIONS"
SERVICE='paperclip-158.jar'
OPTIONS='nogui true'

**Comment by prplz** [comment]
Not an error

**Comment by minecraft7net** [comment]
yes its debug information but i'm interesting how and what can i configure based on those information to improve server performance and network server performance its some java options or some Linux based sysctl properties to set. or what is minimum and recommended java version for paperclip b158

**Comment by stephan-gh** [comment]
There is nothing you can optimize regarding these debug messages. As it says in the log, netty is just trying different options to load the native libraries; one of them worked in the end so all is good!

`[09:22:23] [Server thread/DEBUG]: [io.netty.util.internal.NativeLibraryLoader] Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.`
...
`[09:22:23] [Server thread/DEBUG]: [io.netty.util.internal.NativeLibraryLoader] netty_transport_native_epoll_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /tmp`
...
`[09:22:23] [Server thread/DEBUG]: [io.netty.util.internal.NativeLibraryLoader] Successfully loaded the library /tmp/libnetty_transport_native_epoll_x86_647937235755534997347.so`

**Comment by electronicboy** [comment]
There is nothing there to be improved, the loading mechanism looks for an already available version of the native netty library before attempting to just extract it itself and loading that version up. This issue tracker really doesn't serve for skeptical "what can I tweak on my system to improve performance", as all it does is lead to people passing around the jar of snake oil
