### ISSUE TITLE
1.13: softdepend is ignored

### ISSUE THREAD

**Issue by DrPanic** [PaperMC/Paper#1359]
### What behaviour is expected:
Softdepended Plugins will be loaded first

### What behaviour is observed:
Softdepend is ignored and will be loaded later. If i change `softdepend `to `depend `it loads correctly.

### Paper build number:
git-Paper-159

**Comment by aikar** [comment]
can you paste some plugin yml's and logs? this seems highly unlikely.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/plugin/SimplePluginManager.java hasnt changed nor do we have any changes to that code.

Can you please come ask for assistance on discord or irc instead and we can figure out what's wrong.

**Comment by DrPanic** [comment]
Seems like a strange problem with our plugin. Thanks for the help in the discord. Same with Spigot, so I'm closing here.
