### ISSUE TITLE
Compile Fail

### ISSUE THREAD

**Issue by bilemedimkq** [PaperMC/Paper#1365]
Hello,

when I compile the project I get such an error.
Could you help?

https://prnt.sc/klcvx3

**Comment by mikroskeem** [comment]
First of all... why are you building as a root?

Anyway this is quite odd error, please clone the repository again and then try running `./paper jar`

**Comment by aikar** [comment]
What OS/Shell? I fresh cloned the repo last night into a new folder and was able to apply successfully, so there is something unique to your environment.

**Comment by bilemedimkq** [comment]
OS: Centos 7 694 bit
Shell: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Comment by TNTUP** [comment]
Same issue here, recently switched machines, installed maven, git, openjdk 8 on Debian 9 Stretch. Building it as normal user minecraft

minecraft@xxxx:~/__Build/Paper$ ./paper jar
Downloading unmapped vanilla jar...
Applying class mappings...
Applying member mappings...
Creating remapped jar...
Installing remapped jar...
Extracting NMS classes...
Decompiling classes...
Pointing /home/xxxx/__Build/Paper/work/Minecraft/current to 1.12.2
Failed to build Paper

**Comment by zachbr** [comment]
Will take a look at this on a fresh VM(s?) later.

**Comment by zachbr** [comment]
Debian 9, fresh install.

Issues I ran into: Debian doesn't ship with curl, and I forgot to set my git config aliases. That's it.

Packages I installed: `maven openjdk-8-jdk git curl`

`git clone https://github.com/PaperMC/Paper`
`cd Paper`
`git config --global user.name "Paper Airplane"`
`git config --global user.email "paper@flies.so.high.in.the.sky"`
`./paper jar`

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:54 min
[INFO] Finished at: 2018-08-23T21:29:30-04:00
[INFO] Final Memory: 33M/423M
[INFO] ------------------------------------------------------------------------



Build success!
Copied final jar to /home/zach/Paper/paperclip.jar
```
Will look at CentOS next.

**Comment by aikar** [comment]
Can you try on latest master? I added some code to ensure the symlink process doesn't cause a fatal error, but not sure if that's the issue since an actual error message never printed.

**Comment by TNTUP** [comment]
Well I already have those packages installed and I'm on that java version (same as my previous server) "0            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      auto mode". But still fails. 

Though Spigot's buildtools works and I have built the 1.12.2 and 1.13 jars, but paper seems not to get well with me, as it does not say/output the error is.

But it still builds on my last machine (will be disabled soon as I have moved servers) works. But not on the current 

I will try this one now Aikar ^^ //edit: nope

**Comment by zachbr** [comment]
@TNTUP install `patch` from repos.

**Edit** I actually meant @bilemedimkq as I only saw this issue on CentOS, but feel free to try as well.

**Comment by TNTUP** [comment]
Yep, it works now! It would mean I didn't had patch installed, weird :/ Solved

```

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:20 min
[INFO] Finished at: 2018-08-23T22:31:42-04:00
[INFO] Final Memory: 43M/1488M
[INFO] ------------------------------------------------------------------------



Build success!
Copied final jar to /home/minecraft/__Build/Paper/paperclip.jar

```

**Comment by bilemedimkq** [comment]
I tried debian, it worked!
I think CentOS has a problem.

Thank you!
