### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by bilemedimkq** [PaperMC/Paper#1370]
Hi, I want to build 1.13. how can I do it ?

**Comment by aikar** [comment]
If you are simply looking to use Paper, and are a server owner, you can download ready to use jars at https://paper113.emc.gs

If you are a developer looking to help out with PR'ing to Paper:

1) `git clone git@github.com:PaperMC/Paper paper` 
2) `cd paper`
3) `git checkout pre/1.13` - ignore the pre, it is proper 1.13 release, and will be 1.13.1 soon as it's out from upstream
4) `./paper patch && mvn clean install`

see [CONTRIBUTING.md](https://github.com/PaperMC/Paper/blob/pre/1.13/CONTRIBUTING.md) for information on PR'ing.

**Comment by bilemedimkq** [comment]
thank you :)
