### ISSUE TITLE
World#isChunkTicked(x, y) / Chunk#isTicked()

### ISSUE THREAD

**Issue by sotr2333** [PaperMC/Paper#1377]
**Is your feature request related to a problem? Please describe.**
Currently, there is no a method to check whether a chunk is actually generated/ready (terrain generated, light inited, decorated)

**Describe the solution you'd like**
Simply adding either or both methods: `World#isChunkTicked(x, y)` / `Chunk#isTicked()`

**Describe alternatives you've considered**
Simply expose `ticked` boolean in `Chunk` to API, `Chunk#v` in 1.13 and `Chunk#r` in 1.12.x

**Additional context**
There is `isTerrainPopulated`(`done`) and `isLightPopulated`(`lit`) in 1.12.2 but seem gone in 1.13, it's nice if can add them as well.

**Comment by aikar** [comment]
How are you even getting a reference to a chunk before it's complete? That shouldn't happen on the api

**Comment by sotr2333** [comment]
@aikar I use `BlockPhysicsEvent` with new API `getSourceBlock`(`getBlock` will also have this issue) + `getChunk`, and I find some event is coming from terrain decorating. I'm working on a block logging plugin, so I want to ignore events from terrain generation (before the chunk has been ticked), but I cannot find a way (then I tried `isTicked()` in nms, it works - if I call `isGenerated` it will return true).

**Comment by sotr2333** [comment]
Tested again, this method can filter most events from terrain generation, but some events can still pass, I'm looking for a better way.

**Comment by sotr2333** [comment]
ok, it's clear now:
+ terrain decoration such as 'add water source into caves', 'randomly remove torch in mineshaft' or 'waterfall in caves' (not include tree gen) will happen after chunk generated (at this moment `isChunkGenerated` will return `true`), but before the chunk have been ticked.
+ natural water spread (which have a natural water source generated in caves or somewhere) will only trigger one `BlockPhysicsEvent` (if we place a water source manually, the spread will always call 6 events), those events will come a bit late after the chunk has been ticked. They are actually the typical water spread, but just a bit special in updating its neighbor blocks.

There is no more block placing related to terrain generation after this two points, so I think `isChunkTicked` is the best way to check whether a chunk is actually generated ~~and should be a good replacement of `isChunkGenerated`~~ (This will load the chunk, but very conventient to check a loaded chunk). @aikar

**Comment by aikar** [comment]
No, this isn't a thing. As soon as the Bukkit API can see a chunk, it's ready.

Chunk's do not exists in the chunk map while they are generating.
any physics event your seeing from a chunk is already generated. Water will be a forever source of events like this.

As it stands, there is no such thing as an unticked chunk outside of the VERY first addition of the chunk when generated.

There is a ChunkPopulateEvent for this to learn when a chunk has generated.

**Comment by sotr2333** [comment]
I tried to listen ChunkPopulateEvent and adding those chunks to a Set (newly generated world), and check whether there is a BlockPhysicsEvent from an unticked but populated chunk / ticked but unpopulated chunk and the result is odd, sometimes there is BPE from unticked but populated chunk while sometimes it's from ticked but unpopulated chunk (I teleported to the location to confirm what actually changed there, I saw mineshaft decorating, gravel dropping and water spread), none of them can indicate whether a chunk is finished its decoration.

**Comment by aikar** [comment]
everything about this is different in 1.13. We can't add something to 1.12 that is meaningless and would be immediately removed in 1.13, as 1.12 is on its last stretch of support right now.

your going to need to use reflection to do this.

**Comment by sotr2333** [comment]
ok, thank you, but I still cannot find a way to check a chunk is done.
