### ISSUE TITLE
1.13.1 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [PaperMC/Paper#1378]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-1-development-builds.336415/

**Comment by prplz** [comment]
Everyones asleep dude

**Comment by TheIntelloBox** [comment]
I live in Europe. x)

**Comment by prplz** [comment]
That's great and all but be patient

**Comment by TheIntelloBox** [comment]
Yeah. :)
