### ISSUE TITLE
Pause Watchdog during Reload

### ISSUE THREAD

**Issue by Blazzike** [PaperMC/Paper#1381]
This is to prevent server not responding message spam during reload. Thanks!

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-182

**Comment by sgdc3** [comment]
Reload should be removed xD **-jk**

**Comment by BillyGalbreath** [comment]
Solution: Don't use `/reload` ^_^
