### ISSUE TITLE
Tab-to-complete command not working

### ISSUE THREAD

**Issue by Darciah** [PaperMC/Paper#1382]
### What behaviour is expected:
Upon typing a command, you should be able to see a tree of possible <argument> or other variable and be able to use the new tab-to-complete/autofill.

### What behaviour is observed:
All commands are affected, for example typing in "/gamemode" no longer displays the list of possible outcomes. The same is observered of both standard and non-standard (plugin) commands. Since the 1.13.1 update of PaperMC, I have noticed this behavior.

### Steps/models to reproduce:
Press T to being up chat and begin typing any command. Try to use Tab to complete the first layer of the command and look for a popup table of possible command progression. Nothing further is displayed.

### Plugin list:
Plugins (8): CoreProtect, dynmap, LuckPerms, WorldEdit, Vault, GriefPrevention, Essentials, EssentialsChat (no datapacks present)

### Paper build number:
Paper version git-Paper-183 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

### Anything else:
Running CraftBukkit version git-Spigot-2440e18-4228a56 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT), this issue is not present and this feature, functions as expected.

Deleting and allowing a new paper.yml file to generate, did not fix this.

**Comment by Tomographix** [comment]
Have the same issue :)

**Comment by zachbr** [comment]
cd5da239f84aa2bb94640bc479b2fb6d8f7ed31d
028399fd33cd1e1ceffeb45449cbb7d5f032718a

Builds 188+

Thanks for letting us know.
