### ISSUE TITLE
Tab-to-complete on Bungeecord not working

### ISSUE THREAD

**Issue by bundabrg** [PaperMC/Paper#1383]
### What behaviour is expected:
Upon typing a command that is provided by the Bungeecord proxy, you should see the list of options.
Example:
  /send {should show list of players} {should show list of destinations}

Also /send should be in blue indicating it's a correct command.

### What behaviour is observed:
No bungeecord command is shown as available (text is red) nor does it show tab-completes for the command. However if I type the command anyway it will execute on the Bungeecord Proxy.

### Steps/models to reproduce:
1. Setup Bungeecord, without any plugins (apart from a permission one)
2. Setup PaperMC behind it, without any plugins
3. Connect to the PaperMC server
4. Type '/send '. It should show the completes and a list of suggestions

### Plugin list:
LuckPerms on Bungeecord
None on PaperMC

### Paper build number:
This server is running Paper version git-Paper-173 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

### Anything else:
I setup both a plain Spigot 1.12.2 server and a patched Vanilla 1.12.2 server (so it supports Bungeecord ip_forward) and connected to them. Both have working Bungeecord tab completes.

I should note that unlike #1382 all tab-completes for local plugins on the server work fine.

**Comment by 0-x-2-2** [comment]
This sounds like a issue with bungeecord

**Comment by bundabrg** [comment]
Whilst on the surface I would agree, I eliminated it from the equation pretty much by what I added in 'Anything else'.

That is, I setup both a plain Spigot and a (patched for ip_forward) Vanilla server behind the same bungeecord, same config, and can confirm that both work. Only PaperMC is not working.

Update: Both my tests were with 1.12.2 whereas Im using a 1.13 PaperMC so I'll just do a quick test with a 1.13 Spigot and report back.

**Comment by electronicboy** [comment]
This is a bungeecord issue, with 1.13's command framework, tab completion relies upon the server to define the command for the client, Bungeecord does not support the brigadier framework, as it doesn't send the command definition, the client doesn't know that it's a command, and can't provide any form of completion

**Comment by bundabrg** [comment]
Thanks. I can confirm Spigot 1.13 fails as well.
