### ISSUE TITLE
Fortress unrecognised as a fortress in 1.13.1

### ISSUE THREAD

**Issue by lukeeexd** [PaperMC/Paper#1384]
### What behaviour is expected:
Wither Skeletons, blazes, normal skeletons spawning in fortress

### What behaviour is observed:
No Wither Skeletons, blazes, normal skeletons spawning in fortress

### Steps/models to reproduce:
Had my server on Paper 1.12.2 then switched to 1.13.1 and someones wither skeleton farm stopped working. It worked in 1.12.2. I tried the server with bukkit 1.13 and it worked. I had someone join the server who had never joined and they didn't get the advancement for finding a fortress, they got the advancement at another one

### Plugin list:
None as I tested it without any

### Paper build number:
181

### Anything else:
Seems as if the fortress where his farm was stopped being recognised as a fortress. Might have something to do with fortresses already discovered not working once switching to 1.13.1

**Comment by NullCase** [comment]
Build 206. Newly generated world (~4 days old).

Nether Fortresses seem OK. I visited a couple and got the advancements & had mobs spawning.

**Comment by lukeeexd** [comment]
@NullCase Ya if you generate the world in 1.13.1 it will be fine

**Comment by NullCase** [comment]
I don't know, today I'm looking at Witch Huts that don't match their bounding boxes. So it seemed to me like checking up on this fortress issue was a good idea.

It sounds like you have a pretty good grasp of the problem you're facing though.

**Comment by GrumpyChunks** [comment]
I've seen a similar issue on my server. One particular fortress, which partialy goes outside the world border (via the world border plugin, not the vanilla world border feature), isn't recognised as a nether fortress. As well as the behviour detailed above, there are no blaze spawners in the structure where you would normally find one. Using Core Protect, I've verified that the spawner hasn't been removed by a player.

Posting here in case other server owners have a similar set up with this issue. Note that I've not indentified the cause of this as yet, so it might not have anything to do with paper. I'm afraid I can't confirm the version of paper that was in place when the world was pregenerated (using /wb fill from the world border plugin). For info, my Nether world border is set to circular with a radius of 625 blocks. Aproximately 75% of the fortress is within the border, including the places where I would expect to see a spawner. Achievements are obtained when the player visits other fortresses which do appear to have generated correctly.

Edit: Recreated the world with the same seed in a paper server with no plugins, teleported to the same coordinates, and the nether fortress is working fine, so it's not an issue with paper itself (at least no with build 448 of 1.13.2).

**Comment by LogicalGeekBoy** [comment]
I just thought I'd add that I've seen this in Vanilla and there is an open bug report that I've added my experience to. I hope this helps: https://bugs.mojang.com/browse/MC-133992

**Comment by Proximyst** [comment]
This has been fixed at some point, and the Mojira issue has been closed.
