### ISSUE TITLE
1.13 Vanilla bug adding golems to the world twice.

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#1385]
### What behaviour is expected:
Iron golems spawning properly without error do not want golems to the world twice

### What behaviour is observed:

![](https://user-images.githubusercontent.com/37608633/44671307-54259200-aa64-11e8-9782-82e8224d458c.png)

### Steps/models to reproduce:

use -Ddebug.entities=true to startup flags in start.bat

### Plugin list:
AdvancedPortals, AntiPortalTrapping*, AutoTorch, BetterDrops, BetterExplosions, BKCommonLib, BlockElytraArrowBoost*, BlockStatus*, BottleRecycling*, Broadcaster*, ChangeSkin*, ChatControl, Citizens, CitizensCMD, CityWorld*, ColorCodes*, ColoredAnvils*, CommandPrompter, ConsoleSpamFix, CorpseReborn*, Craftconomy3*, CS-CoreLib*, DeluxeMenus*, DiceFurniture, DoorCloser*, DynamicSigns*, EazyEmojis-Lite*, EditableSign*, Essentials*, EssentialsChat*, EssentialsGeoIP*, FastAsyncWorldEdit*, FirstJoinPlus*, ForceResourcepacks, FurnitureLib, GlowFeller, HeadDatabase*, HorseTpWithMe, InventoryFullPlus*, KeyCommandBind*, LibsDisguises, LightAPI*, LuckPerms*, MaintenanceSpigot*, Mentions.gg*, Missing_Recipes, MoneyDrop*, MultiInv*, Multiverse-Core*, MVdWPlaceholderAPI*, MythicMobs, NoPos*, OpenInv*, PacketListenerApi*, PacketWrapper*, PlaceholderAPI, PluginManagerReloaded*, ProtectionLib*, ProtocolLib*, PublicCrafters*, PulseHealth*, RealisticLiquid*, SavageDeathCompass*, SecurityVillagers, Sentinel, Shopkeepers, SilkSpawners, SimpleSit*, Skinner*, SmokingPipes, SmoothSleep, SpigotLib*, TabList*, TitleManager*, Towny*, TownyChat*, TownyGUI, TownyNameUpdater*, TownyTitle*, UltimateDrugs*, UltimateTrash*, UltimateTroll*, Vault*, VisualFixer, VoidGenerator, WDLCompanion*, WorldBorder*, WorldEdit, WorldGuard, WorldGuardExtraFlags*

### Paper build number:
Paper version git-Paper-184 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

### Anything else:
https://github.com/PaperMC/Paper/issues/1223#issuecomment-416707787
https://pastebin.com/FbDeJtJF
[Latest.log](https://github.com/PaperMC/Paper/files/2326297/latest.log)

**Comment by aikar** [comment]
Fixed in 199+
