### ISSUE TITLE
Kicked for Spam

### ISSUE THREAD

**Issue by Tomographix** [PaperMC/Paper#1388]
### What behaviour is expected:
User is typing a message and proof-reading it before sending.

### What behaviour is observed:
User typed message and was kicked for spam during editing it - before it was sent.
User is unable to join again until after server restart yet it is still possible to TP to their character ingame.

### Steps/models to reproduce:
https://www.youtube.com/watch?v=IMSouM8nuvs&feature=youtu.be

### Paper build number:
http://prntscr.com/ko4ida

### Anything else:
I thought it might be ChatControl so I disabled this. Didn't seem to make a difference.

**Comment by molor** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-4116?

**Comment by electronicboy** [comment]
This has been exposed in the configuration for a while, upstream spigot just decreased the increment variable from 2 > 1, I'll update the default, but anybody who is still having this issue should configure their limits properly
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0346-Break-up-and-make-tab-spam-limits-configurable.patch

**Comment by Tomographix** [comment]
Hi electronicboy, this is still an issue for me despite having dropped the value to 1 in the config.
  spam-limiter:
    tab-spam-increment: 1
    tab-spam-limit: 500

Thanks

**Comment by electronicboy** [comment]
The configuration is exposed for you to play with it, increment 1 is the lowest you can go, increasing the limit would be the next move; If tweaking that configuration doesn't help at all, you're more than likely getting kicked by a plugin

looking back at OP, `User is unable to join again until after server restart yet it is still possible to TP to their character ingame.` I can guarantee that that is going to be down to a plugin,
