### ISSUE TITLE
Creepers don't explode in creative mode with flint and steel

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#1389]
### What behaviour is expected:
Creepers don't explode when you ignite them in creative mode.

### What behaviour is observed:
They don't explode, just remains puffy.

### Steps/models to reproduce:
Change your gamemode to creative. Find or spawn a creeper. Right-click with flint and steel in hand. 

### Plugin list:
None, fresh install.

### Paper build number:
Paper version git-Paper-193 (MC: 1.13.1)

### Anything else:
Tried with latest spigot build and works fine.

**Comment by zachbr** [comment]
Thanks for letting us know.

This is fixed in builds 197+
