### ISSUE TITLE
1.13 BUG

### ISSUE THREAD

**Issue by zsn741656478** [PaperMC/Paper#1391]
### What behaviour is expected:
Create a world

### What behaviour is observed:
[https://i.loli.net/2018/08/30/5b87841333f3f.png](url)
[https://paste.ubuntu.com/p/MDNmHW4JkG/](url)

### Steps/models to reproduce:
Use Multiverse plugin to create a world

### Plugin list:
essential,luckperms,Multiverse,vault,plugman,worldedit,CoreProtect,ProtocolLib

### Paper build number:
paperclip-173

### Anything else:
none

**Comment by mikroskeem** [comment]
> --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---

Did you even read the error message?  
Was the world created fine?  
Not enough information.

**Comment by aikar** [comment]
I am not clicking that url... seriously why would you use such a domain for linking images.

But based on what mikro posted, this is not a bug, as it says.

Something caused your server to lag, and paper simply informed you so you can get an understanding on what did it.
