### ISSUE TITLE
Disable phantoms spawn above players in creative mode

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#1392]
**Is your feature request related to a problem? Please describe.**
This is a feature. It is always anoying to see phantoms flying above our heads when we are in creative mode for a long time... server admins will know what i'm talking about .

**Describe the solution you'd like**
Disable phantoms spawn near players who are in creative mode.

**Describe alternatives you've considered**
Make a boolean in the config for enable or disable this feature...

**Additional context**

**Comment by aikar** [comment]
This is better solved by a plugin. We recently added an event that can be used to accomplish this too.
@BillyGalbreath want a new plugin user? :P

**Comment by BillyGalbreath** [comment]
Made a lightweight plugin that does exactly what you want ;)

Source: https://github.com/BillyGalbreath/NoCreativePhantoms
Jar: https://www.dropbox.com/s/2ih9cfvajp7i0e0/NoCreativePhantoms.jar?dl=0

**Comment by lordrius** [comment]
Oh! many many thanks Billy, i will try it!
