### ISSUE TITLE
Expand 'non-player-arrow-despawn-rate'

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#1393]
**Is your feature request related to a problem? Please describe.**
No, just an small improvement that should be easy (maybe) to add.

**Describe the solution you'd like**
`non-player-arrow-despawn-rate` lets us clear skeleton arrows faster, but why not expand this to ALL ground arrows that cannot be picked up by a player? This includes arrows from an infinity bow and tipped(potion) arrows.

In fact, as it relates to performance, players spamming an infinity bow to death can be many more times the impact of the occasional skelly arrow.

I understand that this will not be a massive performance change, but just makes sense considering the non-player-arrow-despawn-rate is only there for this very reason (clearing cosmetic arrows).

**Comment by aikar** [comment]
@CeIebrimbor what are you asking that arrow-despawn-rate in spigot.yml doesn't cover?

do you want to set a different rate for creative arrows thats different from non creative arrows? that's only thing missing atm is creative arrow control.

**Comment by CeIebrimbor** [comment]
Spigot’s despawn just removes all arrows. Paper’s non-player-arrow-despawn goes a step further by allowing servers to remove skeleton arrows faster. The reason being that they cannot be picked up (cosmetic only), so why keep them around?

The recommendation is that Paper expands that to include all arrows that cannot be picked up. Including arrows fired from an Infinite Bow and Tipped Arrows.

As I said...not really a big request or something that “solves” performance issues. Just another step towards better performance.

Just setting Spigots option lower removes all arrows, including those that would be able to be picked up, thus impacting Survival.

**Comment by BillyGalbreath** [comment]
@CeIebrimbor I dont understand why you think the paper setting only works for arrows shot by skeletons? The code covers all arrows that a player cannot pickup:

https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0076-Configurable-Non-Player-Arrow-Despawn-Rate.patch#L35

**Comment by Trigary** [comment]
I was looking at the code and thinking the same, but testing revealed that it's not as simple as it looks: player arrows never get affected. Maybe it has something to do with the other if statement in that method.

**Comment by CeIebrimbor** [comment]
Did build 225 cover a different change to arrows?

**Comment by zachbr** [comment]
This was added, everyone thank billy for the PR :p
