### ISSUE TITLE
Setting block with applyPhysics=false to air drops attached blocks.

### ISSUE THREAD

**Issue by hafarooki** [PaperMC/Paper#1394]
### What behaviour is expected:
The block disappearing, but the blocks around it remaining.

### What behaviour is observed:
The block disappeared, but fragile attached blocks disappeared, too.

### Steps/models to reproduce:
1.  Place a block of cobblestone
2. Put redstone on top
3. Set cobblestone to air using a plugin which passes false for applyPhysics

### Plugin list:
ExplosionRegen

### Paper build number:
1.13 build 200 

### Anything else:
Additionally, setting redstone dust over air makes the redstone fall, same with signs iirc

**Comment by zachbr** [comment]
Cannot reproduce as of build 206

![](https://i.imgur.com/KrqfPzM.png)
(https://webmshare.com/6vvDn)

**Comment by hafarooki** [comment]
think I actually tested it wrong, I should have tested it the way I mentioned but I figured it'd have the same results, my bad. I think the actual problem is placing over air, not removing under the block. will test it soon
