### ISSUE TITLE
Console error placing structure block

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#1395]
### What behaviour is expected:
Don't see any error in console when placing structure block.

### What behaviour is observed:
Placing structure block triggers that error. With latest spigot version and also fresh installation don't occur.

https://pastebin.com/v7B7b5v8

### Steps/models to reproduce:
give yourself a structure block and place it.

### Plugin list:
None, fresh install and config files

### Paper build number:
Paper version git-Paper-200 (MC: 1.13.1)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by aikar** [comment]
Sigh, I guess passing world to snapshots isn't going to work.

Things break if you do, and break if you don't, woot!

**Comment by aikar** [comment]
fixed in 213+

**Comment by BillyGalbreath** [comment]
@aikar someone ran into this on build 315. https://hastebin.com/jiwisadebu.css

I am unable to reproduce. https://i.imgur.com/2rSmn6z.jpg

**Comment by aikar** [comment]
@BillyGalbreath that is unrelated to this
