### ISSUE TITLE
Lastest Builds

### ISSUE THREAD

**Issue by madtomic** [PaperMC/Paper#14]
Hi Zbob750,

Will we soon have a build-able jar for use or we are still under heavily catching up?

Edit: Sorry, I meant to post in PaperSpigot-1.7 I saw some commits on Jenkins and wondering about this. I'd be happy if we can get an updated 1.7 to use. :)

Thanks,
madtomic

**Comment by zachbr** [comment]
Nope. We do not support 1.7 in any fashion. We have kept it in its own separate repo with its own separate issue tracker so that those that want to play with the source code can, but our involvement with it is through
