### ISSUE TITLE
1.13.1 Player Crashes

### ISSUE THREAD

**Issue by miniharry** [PaperMC/Paper#1401]
### Link/paste of stack trace

https://hastebin.com/ekefuyeguc.pl

### Plugin list:

LuckPerms, GPWithdraw, Elevators, PlaceholderAPI, Boss, WorldBorder, BuycraftX, Votifier, Multiverse-Core, InnovativeMechanics, AdvancedPortals, MCRandomPort, FastAsyncWorldEdit, IPWhitelist, DeluxeMenus, Ridables, mcMMO, Vault, TokenManager, ShopGUIPlus, Essentials, HeadDatabase, Citizens, EssentialsChat, SuperbVote, PlayerVaults, EssentialsSpawn, TitleManager, CrateReloaded, WorldEdit, WorldGuard, GriefPrevention, MyPet, AreaShop, GPAccruals, QuickShop, HCPlaceholders

Removed ProtocolLib, Essentials, TitleManager, etc. in efforts to try and fix this problem.

### Actions to reproduce (if known):

Players are always kicked typing /r (we changed the chat plugin from DeluxeChat to Essentials and it still happened with this command) and at random.

We switched to Spigot and there have been no kicks so far.

### Paper build number:

paperclip-206 from 1 Sep

**Comment by electronicboy** [comment]
See the spam limit configuration in paper.yml, we recently reduced the increment value to 1 as the default following upstream, however, the config is there for you to tweak as you wish

**Comment by Castiella** [comment]
Hi, sorry to jump on this but i'm having the same issue, can you recommend what level to set the   incoming-packet-spam-threshold:  to please? I have it set to  300 and people are still being kicked for spam. :)

**Comment by electronicboy** [comment]
spam threshold is a different to this, I'd suggest setting the `tab-spam-increment` to 1, and raising the limit up too in sizable increments
