### ISSUE TITLE
The server has not responded for 10 seconds!

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#1402]
### Link/paste of stack trace
https://pastebin.com/KcBXP7aA
    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it.___

### Plugin list:
___A list of your plugins___
`Plugins (61): 2048*, AdditionsAPI, AdvancedAchievements, ArmorWeight*, Battleship*, BountyHunters, ChangeSkin, ChatControl, Citizens, CitizensCMD, ConditionalCommands*, CoreProtect, CorpseReborn*, DamageIndicator, EnderContainers, Essentials*, EssentialsChat*, EssentialsGeoIP*, EssentialsSpawn*, FastAsyncWorldEdit*, GameBox*, GemCrush*, Hardcore, HardcoreAdditions*, Heads, Kredites*, Lands, LibsDisguises, LogicPuzzles*, LuckPerms*, MineMarket-Universal*, MineMarketAPI*, Minesweeper*, MP-GameBundle*, Multiverse-Core*, MyCommand*, MythicMobs, NametagEdit*, NoCheatPlus*, OpenInv*, PlaceholderAPI, PlugMan*, PomaAdditions*, ProtocolLib*, Ridables, SafeTrade*, SignEdit*, StaffKezikonyv, Stats, Tagpluszkulcs, Thirst, TitleManager*, Vault*, Votifier*, VotingPlugin, WDLCompanion*, WhacAMole*, WorldEdit, WorldGuard, WorldGuardExtraFlags*, WorldGuardPomaFlags*`

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
I don't know.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
```
02.09 14:20:03 [Server] INFO This server is running Paper version git-Paper-206 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
02.09 14:20:03 [Server] INFO Previous version: git-Paper-173 (MC: 1.13)
02.09 14:20:03 [Server] INFO Checking version, please wait...
```

**Comment by aikar** [comment]
```
--- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
```
You just have chunk generations lagging server.
