### ISSUE TITLE
loadChunk(x, y, false) returns false if a 1.12.2 < chunk has not been converted to 1.13

### ISSUE THREAD

**Issue by Blazzike** [PaperMC/Paper#1403]
### What behaviour is expected:
true

### What behaviour is observed:
false

### Steps/models to reproduce:
Use loadChunk(x, y, false) on a chunk that has not been converted.

### Paper build number:
206 (1.13.1)

**Comment by aikar** [comment]
This will be fixed as part of the Async Chunk Loading work.

**Comment by aikar** [comment]
Actually this is better fixed separate, can someone PR loadChunk(int, int, boolean) to do:

```java
return world.getChunkProviderServer().getChunkAt(x, z, true, generate || isChunkGenerated(x, z)) != null; // Paper
```

**Comment by aikar** [comment]
Fixed in 208+
