### ISSUE TITLE
Double Doors breaking and duplicating. 

### ISSUE THREAD

**Issue by Castiella** [PaperMC/Paper#1404]
### What behaviour is expected:
When you open double doors, they should just open.

### What behaviour is observed:
One of the doors breaks off, then you get given 2 doors in your inventory.

### Steps/models to reproduce:
open double doors

### Paper build number:
Paper version git-Paper-206 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Any other information? I cannot reproduce this in build 206.

**Comment by Castiella** [comment]
Closing, it was a conflict with LWC.
