### ISSUE TITLE
Ability to block the server sending command list to client in 1.13+

### ISSUE THREAD

**Issue by danjono** [PaperMC/Paper#1406]
md_5 doesn't seem to like the idea of having this implemented into Spigot as referenced by this JIRA report from the Spigot bug tracker [here](https://hub.spigotmc.org/jira/browse/SPIGOT-4029?jql=text%20~%20tab%20ORDER%20BY%20created%20DESC)

The person who submitted the report does state that they would like to be able to modify the list of commands that get sent to the player via a DeclareCommandsEvent. I realise that only commands that the player has access to are being sent however there are a few commands that do not have a permission node attached to them on the default command (usually to show the version you are running) and will always show up, LuckPerms for example on my setup. 

This is my eyes is not a great solution with server security in mind as this can be just the same as a player doing /pl or /plugins and seeing what you run. There are also some other good points raised by the person who submitted the report about hiding deprecated aliases also which I do believe also can be beneficial.

While I understand modifying this data may be a challenge, can at least a config variable be added into paper.yml to be able to block the packet(s) from being sent to the player with all available commands in the first place.

**Comment by Spottedleaf** [comment]
I'm not sure why hiding plugins loaded in the server is considered in good security.

**Comment by electronicboy** [comment]
This could be very easily done using the event and a plugin by removing anything that isn't wanted from the list, there is much more control here using the event as opposed to a config option

**Comment by danjono** [comment]
How would you propose it could be done? 

The only event I can see where this could edit/block this is on PlayerCommandSendEvent however this seems to be read event after the data has been sent. I've tried to make a constructor with it but again I cannot see a way to update the data that has already been sent to the player?

**Comment by electronicboy** [comment]
The event is fired before it's sent to the client, any entry removed from
the list will be removed from the list of commands being sent to the client

**Comment by danjono** [comment]
I've done a bit more testing on my end since last night. I was having a problem with the event PlayerCommandSendEvent not firing also which also was a reason why I was suggesting having this feature. 

I've worked out that in the spigot.yml if commands.tab-complete is set to -1, the data is still sent to the client however the listener event is not fired (not sure if this is intended or if it might be a Spigot API bug) so I couldn't change the list that was sent. If the value is sent to 0, I can intercept the event and clear the commands so thankfully for me at least I've got a solution now.

While I agree this can be done with a plugin, I still think for others that also want to remove all the commands from being sent to the client in 1.13+ it would be handy to have a config variable to save on having to run a separate plugin just to do that.

**Comment by BillyGalbreath** [comment]
> While I agree this can be done with a plugin, I still think for others that also want to remove all the commands from being sent to the client in 1.13+ it would be handy to have a config variable to save on having to run a separate plugin just to do that.

I dont understand whats wrong with adding a plugin that does one thing only. You act like a simple plugin that listens to this one event is going to push your server over the limit and lag it to death (hint: it wont)

**Comment by zachbr** [comment]
> While I agree this can be done with a plugin, I still think for others that also want to remove all the commands from being sent to the client in 1.13+ it would be handy to have a config variable to save on having to run a separate plugin just to do that.

No thanks. We aren't in the business of exposing every API feature as paper.yml configurable value, even if we do break that rule occasionally (for various reasons). Use a plugin.
