### ISSUE TITLE
[1.13.1] Failure to save chunks in End containing Spawn Egg Phantoms

### ISSUE THREAD

**Issue by NFRCG** [PaperMC/Paper#1408]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it.___
Stacktrace: https://gist.github.com/NolanMC/205d78b9645019a4b6431225ea231b22 
Entire Log: https://gist.github.com/NolanMC/6ab739723dc4e9e7f743005e557f4e7c
(The error gets cut off in the full log and in stacktrace, this was not done by me). 
### Plugin list:
___A list of your plugins___
03.09 04:38:39 [Server] INFO Plugins (11): AdvancedAchievements, CrazyAuctions*, Essentials, EZBucket*, FastAsyncWorldEdit*, GroupManager*, Jobs, McWiki, PlaceholderAPI*, Vault*, WorldEdit
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
1. Go to the End
2. Use a Phantom Spawn Egg from Creative
3. Wait for game to save the chunk or use /save-all when Phantom is alive in the chunk. 

Killing the Phantom and attempting to save the chunk afterwards, works properly.
- Has been reproduced on Paper 209 and 184 (with/without plugins)
- Cannot be reproduced on the latest version of Spigot (without plugins, version below)
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
03.09 04:37:30 [Server] INFO This server is running Paper version git-Paper-209 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
03.09 04:37:30 [Server] INFO Previous version: git-Paper-184 (MC: 1.13.1)
03.09 04:37:30 [Server] INFO You are running the latest version

Spigot Version where it is not occuring: 
03.09 04:46:34 [Server] INFO This server is running CraftBukkit version git-Spigot-0ede7d0-ee5efeb (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
03.09 04:46:34 [Server] INFO Checking version, please wait...
03.09 04:46:34 [Server] INFO You are running the latest version

**Comment by aikar** [comment]
Fixed in 214+
