### ISSUE TITLE
1.13.1 When trying to connect to server, players get stuck on "Loading terrain..."

### ISSUE THREAD

**Issue by V-DeVito** [PaperMC/Paper#1414]
Multiple players have this error when trying to connect to the server. Here are the things that they have already done:
-Updating Java
-Uninstalling then re-downloading Minecraft launcher
-Server owner has deleted the scoreboard.dat file (This was suggested by other bug reporting communities)
-The server owner has also deleted all the player data for one person, and it still is an issue.

The error is off and on, where they can sometimes connect at one point, then 3 hours later they can't.

Here's a log from one of the players:
https://paste.ubuntu.com/p/t6gmzgJnjS/

**Comment by hugmanrique** [comment]
https://bugs.mojang.com/browse/MC-34947

**Comment by zachbr** [comment]
That log doesn't really tell us much unfortunately. I have heard this report before however, this issue seems to affect certain 1.13.1 servers more than others.

**Comment by V-DeVito** [comment]
What else should I post to help figure this out?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zachbr** [comment]
If you're still seeing this on recent builds of 1.13.2 please paste your server log here in a reply and we'll go from there. thanks.
