### ISSUE TITLE
Llama setCarryingChest() don't refresh to other players

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#1415]
### What behaviour is expected:
Hi! i'm writing a piece of code trying to make shift right-click llama with chest, drops the chest and inventory contents and works fine for me, no errors in console. But for other players close to me, they still see llama with chest texture and if they ride it, can see llama inventory slots, but if they reconnect to the server they see it without, it's like if needs some kind of refresh to other players, i don't know... this is my code:

https://pastebin.com/FYepcKvC

### What behaviour is observed:
If my code is correct, i think if it works fine for me then should work fine for anybody.

### Steps/models to reproduce:
Try this code, tame llama, put chest, Shift right-click with empty hand, the chest (and llama's inventory drops). Try it with another person around.

### Plugin list:
None.

### Paper build number:
Paperclip-221

### Anything else:
I also tried to cast Llama using ChestedHorse, but same issue. If my code is wrong, sorry for the inconvenience of this opened issue.

**Comment by hugmanrique** [comment]
Does this also happen upstream (Spigot/CB)?

**Comment by lordrius** [comment]
I just tried with latest Spigot version and yes, it happens.

**Comment by hugmanrique** [comment]
Mind creating a bug report on Spigot JIRA and link it here? 

~~Paper mantainers can close this as this is an upstream bug.~~

**Comment by aikar** [comment]
No, we still fix upstream bugs like this.

**Comment by lordrius** [comment]
I'm also trying another piece of code **pig.setSaddle(false)** and happens the same thing, for the player who execute the action works fine, but for closer players don't refresh pig saddle state...

**Comment by BillyGalbreath** [comment]
**Delay it by 1 tick.**

Video of it working: https://youtu.be/Se4qOCd1eUo

My test code (revised from yours to make more sense):

```
public class TestPlugin extends JavaPlugin {
    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(new Listener() {
            @EventHandler(priority = EventPriority.LOW, ignoreCancelled = true)
            public void removeLlamasChest(PlayerInteractEntityEvent event) {
                if (event.getHand() != EquipmentSlot.HAND) {
                    return; // only listen to one packet
                }

                Entity entity = event.getRightClicked();
                if (!(entity instanceof Llama)) {
                    return; // not a llama
                }

                Llama llama = (Llama) entity;
                if (!llama.isCarryingChest()) {
                    return; // not carrying a chest
                }

                Player player = event.getPlayer();
                if (!player.isSneaking()) {
                    return; // not shift clicking
                }

                if (player.getInventory().getItemInMainHand().getType() != Material.AIR) {
                    return; // holding an item
                }

                if (player.getInventory().getItemInOffHand().getType() != Material.AIR) {
                    return; // holding an item
                }

                LlamaInventory llamaInv = llama.getInventory();
                for (int i = 0; i < llamaInv.getSize(); i++) {
                    ItemStack item = llamaInv.getItem(i);
                    if (item != null && item.getType() != Material.AIR) {
                        player.getWorld().dropItem(llama.getLocation(), item);
                        llamaInv.setItem(i, null);
                    }
                }

                player.playSound(llama.getLocation(), Sound.ENTITY_LLAMA_CHEST, 1.0F, 1.0F);
                player.getWorld().dropItem(llama.getLocation(), new ItemStack(Material.CHEST));

                event.setCancelled(true);

                new BukkitRunnable(){
                    public void run() {
                        llama.setCarryingChest(false);
                    }
                }.runTaskLater(TestPlugin.this, 1);
            }
        }, this);
    }
}
```

**Comment by lordrius** [comment]
Many thanks Billy! the delay made the trick, excellent.
