### ISSUE TITLE
Particle.SPELL_MOB not showing properly on 1.13.1

### ISSUE THREAD

**Issue by thorlauridsen** [PaperMC/Paper#1418]
### What behaviour is expected:
Particle.SPELL_MOB is supposed to look like the swirl particle you also see when using splash potions.

### What behaviour is observed:
Particle.SPELL_MOB looks exactly like the redstone particle.

### Steps/models to reproduce:
On previous versions, such as 1.12.2. I could spawn a colored SPELL_MOB particle like this:
location.getWorld().spawnParticle(Particle.SPELL_MOB, location, 0, 1.0D, 0.0D, 0.0D);
That would in this example, spawn a completely red SPELL_MOB particle.

Using that code on Paper 1.13.1, gives me an error and says:
"Caused by: java.lang.IllegalArgumentException: Particle SPELL_MOB requires data, null provided"

So I read up on DustOptions and use that as the required data. 
This code works on Paper 1.13.1 with no errors:
DustOptions options = new DustOptions(Color.fromRGB((int) R, (int) G, (int) B), (float) size);
location.getWorld().spawnParticle(Particle.SPELL_MOB, location, amount, offX, offY, offZ, options);

But it shows the incorrect particle. It looks exactly like Particle.REDSTONE.

When using normal Spigot 1.13.1: (Build git-Spigot-0ede7d0-228a5cd)
I do not get an error when using this code:
location.getWorld().spawnParticle(Particle.SPELL_MOB, location, 0, 1.0D, 0.0D, 0.0D);

I am able to spawn the SPELL_MOB particle without an error that asks me to use DustOptions.

Notice that Particle.SPELL_MOB.getDataType() returns different values on Spigot and Paper

### Plugin list:
A single custom plugin to test this.

### Paper build number:
git-Paper-244

**Comment by chickeneer** [comment]
Yes. I confirm this issue. I have known about it being a paper issue since the 1.13 update. I will PR a fix this evening.

**Comment by zachbr** [comment]
This was fixed in builds 229+. Thanks for letting us know.
