### ISSUE TITLE
Whitelist always looks up online mode UUIDs, even in offline mode, is not fix

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#142]
#79 This bug is not fix in lastest Paper, I test it:
1. online-mode=false
2. /whitelist add Apple
3. Find the 3c7db14d-ac4b-4e35-b2c6-3b2237f382be in whitelist.yml (wrong!!!)
4. **5862580e-aa1b-3ba2-82db-40e501c08259 is true!!!**
5. Apple can not join server.
   always looks up the online UUID, and not case sensitive of player name.
   **I use lastest Paper, before I posted this.**

Others, 1.8 also has this problem.

**Comment by zachbr** [comment]
What is "latest version"

Also offline mode can never ever be case sensitive with usernames.

**Comment by ghost** [comment]
@Zbob750 The compiled version of the lastest Git code.
And the UUID is always looks up online.

**Comment by zachbr** [comment]
That is not a version string. If you cannot give us real version strings we will not accept issues from you.
