### ISSUE TITLE
Picking up a player thrown trident causes server crash

### ISSUE THREAD

**Issue by BillyGalbreath** [PaperMC/Paper#1420]
### What behaviour is expected:
Picking up a player thrown trident does **not** crash server.

### What behaviour is observed:
Picking up a player thrown tident **does** crash server.

### Steps/models to reproduce:
* Give yourself a trident with 1 use left `/give @p minecraft:trident{Damage:249} 1`
* Throw the trident in survival mode.
* Go pick up the trident.
* Witness server crash.

### Plugin list:
*none*

### Paper build number:
224 (but I think thei effects **all* 1.13.x builds)

### Anything else:
The root problem is caused by the CraftBukkit event `PlayerPickupArrowEvent` building a new `EntityItem` with an ItemStack of AIR. The ItemStack is AIR because the 0 durability trident ItemStack was converted to AIR when it was thrown.

The ItemStack in question is a field in the `EntityThrownTrident` class named `aw` (in 1_13_R2). This field holds the ItemStack that was used to throw the trident (to ensure it's durability is passed to the next ItemStack when it is picked up by a player).

Working on a fix now.

**Comment by Spottedleaf** [comment]
This affects every single 1.13.* build that exists.
