### ISSUE TITLE
Multicraft Conf Files

### ISSUE THREAD

**Issue by M-AlNoaimi** [PaperMC/Paper#1423]
**Is your feature request related to a problem? Please describe.**
Adding a new jar file to multicraft is reasonably straightforward, but when it's a different spigot type like Paper, it requires a little more effort as the conf file needs to work with this type of Spigot/Bukkit. 

**Describe the solution you'd like**
Whenever there is a new update of PaperSpigot, the conf file needs to which be written again as the conf file is different for each type of spigot build. The solution I was looking for is for the creators of Paper to also include one extra file which is a conf file that is meant for when host owners need to add it to Multicraft.  Here are the guides if anyone was looking for it: [Conf Guide Link](https://www.multicraft.org/site/docs/conf)

**Additional context**
Here's is a working example of the conf file for PaperSpigot-1.8.8: 

```
[config]
name = 1.8.8 (SNAPSHOT-0.1)
source = http://yivesmirror.com/grab/paperspigot/PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar
configSource = http://raw.githubusercontent.com/wert/MultiCraft-JAR-Conf/master/minecraft/paperspigot/paperspigot-1.8.8.jar.conf
category = 2. PaperSpigot

[encoding]
encode = utf-8
decode = utf-8
fileEncoding = utf-8

[start]
command = "{JAVA}" -server -Xmx{MAX_MEMORY}M -Xms{START_MEMORY}M -Djline.terminal=jline.UnsupportedTerminal -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -Xincgc -jar "{JAR}" nogui {PARAMS}

[force_config]
configFile = server.properties
newline = \n
search1 = server-ip
replace1 = server-ip={IP}
search2 = server-port
replace2 = server-port={PORT}
search3 = max-players
replace3 = max-players={MAX_PLAYERS}

[parse_log]
start=^(?P<time>(:?[-\d]+ )?\[?[:\d]+\]?)\s+\[?(?P<type>[^]<>]+)[\]>]\:?\s+(:?\[(:?Minecraft-)?(:?Server)\]\s+)?(?P<line>.*)$

[parse_startup]
start=^\s*Done
important=true

[parse_players]
listSplit=\s*,\s*
listLine=(?P<name>.*)
start=^(?:Connected\s*players|Online \([\d]+[^)]*\)):\s*(?P<v_listStr_append>.*)$
start1=^There are (?P<v_maxDataLines>\d+)/\d+ players
data=^(?P<v_listStr_append>.+)$
trigger=list
important=true
isList=true
maxLines=2
maxDataLines=0

[parse_chat]
start=^(?P<source>\[[^\]]+\])?\s*<(?P<sender>[^>]*)>\s*(?P<message>.*)$

[parse_command]
shortStart=(?:tried|issued server) command
start=^(?P<sender>.+)\s(?:tried|issued\sserver)\scommand:\s*(?P<command>.*)$
important=true

[parse_connect]
shortStart=logged in with entity id \d+ at
start=^(?P<name>.+?)\s*\[/(?P<ip>[^\]:]*)(:?(?P<port>[0-9]+)?)\]\s*logged in
start1=^(?P<name>.+)(?P<ip>\s+)logged in

[parse_disconnect]
shortStart=(lost connection|Kick(ing|ed))
start=^(?P<name>.+)\slost connection:\s*(?P<reason>.*)$
start1=^CONSOLE:\s*Kicking\s(?P<name>.+)$
start2=Kicked\s(?P<name>.+) from the game\s*$
```

Again if this were to happen, it would be highly appreciated.

**Comment by electronicboy** [comment]
if somebody wants to PR this to say something like a misc files folder, than maybe; But I can't see this being something that the core maintainers go out of their way to do, not sure if any of us have a running multicraft installation to test if this is working (also, really shouldn't be linking to yives site....)

Actually, thinking back, this might be better off in an entirely separate repo under the PaperMC org

**Comment by zachbr** [comment]
If we were to do this, we'd probably put these files in a separate repo.
We'd have to figure out some way to label certain files as unsupported as well (in the case of your above 1.8.8 example). And yes, you'd not be able to use yives.
