### ISSUE TITLE
onTabComplete not complete commands in 1.13.1

### ISSUE THREAD

**Issue by dudullle** [PaperMC/Paper#1424]
**Build used :** Paper version git-Paper-227 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
 
the **"onTableComplete"** is raised BUT the autocompletion doesnt appear to the client.

Also **not working with the latest version of WaterFall**.

**Note :** It works on Spigot and BungeeCord

**Comment by zachbr** [comment]
Cannot reproduce this. I've got my own plugins that rely on this and they're all working just fine.

If you didn't, test without waterfall and third party plugins or provide some form of additional information so that we can try and look into this further.

**Comment by electronicboy** [comment]
I'll look into this properly tomorrow, but there is definitely an issue with the patch here, the SuggestionBuilder is being created using the transaction ID as opposed to being passed an actual range

**Comment by zachbr** [comment]
Please re-test against builds 236+

**Comment by dudullle** [comment]
It works when i type my command in the console, but not in game.
Running build 238

**Comment by dordsor21** [comment]
Same issue for me, running paper 265.

No issues when using latest spigot for 1.13.1 or when executing commands via console.

**Comment by dudullle** [comment]
Still not working in build 299

**Comment by BillyGalbreath** [comment]
I can't reproduce this.. It's got to be a bug in the proxy you are using.

**Comment by dudullle** [comment]
Not working without proxy ... and sometimes, when i press tab, playernames are displayed like this :
"Dudullle/tpa Du"

**Comment by Foorcee** [comment]
set the tab spam limiter in waterfall.yml to 0 ?

**Comment by dudullle** [comment]
Working in build 335+
