### ISSUE TITLE
world and generation lag

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#1426]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___
https://timings.aikar.co/?id=37d08bc4eefb4786b249e53b768c7017

### Description of issue:
___If applicable___

### Plugin list:
___All plugins running on the server___
`09.09 14:42:11 [Server] INFO Plugins (89): 2048*, AdditionsAPI, AnvilRestrict, AreaShop*, Battleship*, ChangeSkin, ChatControl, ChestShop, Citizens, CitizensCMD, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CrazyAuctions, CreativeNbtControl, DeluxeHeads, Duels, EnderContainers, EntityDetection*, Essentials*, EssentialsChat*, EssentialsGeoIP*, EssentialsSpawn*, EventekGUI, FastAsyncVoxelSniper, FastAsyncWorldEdit*, GameBox*, GemCrush*, GriefPrevention, JukeBox, Kezdes, LockettePro, LogicPuzzles*, Lottery*, LuckPerms*, mcMMO, MineMarket-Universal*, Minesweeper*, MobArena, MobHeads, MobMerge*, MP-GameBundle*, Multiverse-Core*, Multiverse-NetherPortals*, MyCommand*, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv*, Paintball, PickupSpawners, PlayerWarp, PlotSquared*, PlugMan*, PomaAdditions, ProtocolLib*, RandomTeleport*, redclockdetector*, RedstoneClockDetector*, RestrictedCreative, Shopkeepers, SignEdit*, StaffKezikonyv, StaffTime, Stats, SuperLuckyBlock-Pro, Tagpluszkulcs, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChest, VanillaAdditions, Vault*, Vipkulcs*, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, WhacAMole*, WorldBorderPearlBlock*, WorldEdit, WorldGuard, WorldGuardExtraFlags*, WorldGuardPomaFlags, YouTubeBridge*`

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___
bukkit.yml: https://pastebin.com/fhAVUQFw
spigot.yml: https://pastebin.com/6drCy0Nb
paper.yml: https://pastebin.com/tAL9LvQN

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
```
09.09 14:48:51 [Server] INFO This server is running Paper version git-Paper-231 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
09.09 14:48:51 [Server] INFO Previous version: git-Paper-227 (MC: 1.13.1)
```

**Comment by aikar** [comment]
General Lag (spelled with 1 g, not 2) is not a bug.

As you are aware we are working on getting async world generation which will solve this.
