### ISSUE TITLE
Server crash related to lighting update

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#1431]
### Link/paste of stack trace
Going to include the thread dump information even though it says not to report it I think it will help diagnose the problem.

Thread dump: https://pastebin.com/m9EFj4hv
Crash: https://pastebin.com/JF4veUfU

I'm assuming this is related to lighting but I have no idea why its crashing the server. Enabling the lighting queue doesn't change anything, just results in this crash: https://pastebin.com/X9sxJDgS

### Plugin list:
FastAsyncWorldEdit, WorldEdit

### Paper build number:
Paper version: git-Paper-1558 (MC: 1.12.2)

**Comment by Orlaando-dev** [comment]
Update your paper version to the latest. Most issues like this are fixed on later versions of Paper.

**Comment by SecretlyJealous** [comment]
> Update your paper version to the latest. Most issues like this are fixed on later versions of Paper.

I'm only one build away from the latest one on the main repository and I see no commits in both Paper and Paper-1.13 which address anything related to lighting.

**Comment by electronicboy** [comment]
Could you please provide more history with the log file?

Loading chunks in lighting is bad, but that looks like a bit of a downfall in the lighting code and an optimization made in CB which means that lighting appears to be able to load chunks in cases where a block is on the edge of a chunk

The lighting code is limited to only running within the space of a normal tick, outside of your system clock being broken, I'm not too sure how this code would run for that long

**Comment by aikar** [comment]
@electronicboy I noticed there's a bug in the code that it only limits per chunk, a single chunks processing can still violate it
