### ISSUE TITLE
Nametagged mobs despawning

### ISSUE THREAD

**Issue by Castiella** [PaperMC/Paper#1434]
### What behaviour is expected:
when you nametag a mob it shouldnt despawn

### What behaviour is observed:
they are despawning 

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:

![image](https://user-images.githubusercontent.com/29293070/45439633-3d14b000-b6b2-11e8-9c69-198745d7a246.png)

### Paper build number:

![image](https://user-images.githubusercontent.com/29293070/45439674-5f0e3280-b6b2-11e8-8268-f5ac905b7b1b.png)

### Anything else:
really sorry if this has been patched already, looked for possible other reports but couldnt see. A

**Comment by LogGits** [comment]
Was having this issue a while back on a 1.12.2 build. Scary to see it resurface on 1.13.1. Last time it was an issue with paper + citizens2. You could try removing citizens and restarting to check if that is still the cause.

**Comment by aikar** [comment]
Try build 309 please and see if it continues, 1569 for 1.12.2

**Comment by zachbr** [comment]
Reply if you're still seeing this against recent builds and we'll go from there.
