### ISSUE TITLE
Citizens2 Latest

### ISSUE THREAD

**Issue by SlookHD** [PaperMC/Paper#1435]
here is Bug

https://pastebin.com/U38QWvLb

server version:   paperclip-245.jar
Pluign version:  citizens-2.0.24-SNAPSHOT.jar
--

Plugin List:
https://gyazo.com/84dbe3a4cff9f5872020f3fc0680fd84
--

**Comment by ghost** [comment]
Also have this issue. Haven't tested on regular Spigot, but OP says bug is only present on Paper so I figured I'd share my info too:

**full log with error:** https://gist.github.com/eightbitx/9e22d2de5fc027d045039fb0026070b7
**server version:** git-Paper-"fbed5674" (Aikar's Async Chunk Gen beta)
**plugin version:** v2.0.24-SNAPSHOT (build 1568)

**Comment by aikar** [comment]
I will fix it in a few hours. It is paper specific due to recent changes, and would also be present in the main builds too (it's not specific to Async Chunks)

**Comment by aikar** [comment]
248+

**Comment by DereC4** [comment]
pluign
