### ISSUE TITLE
Tab Complete bug

### ISSUE THREAD

**Issue by MatinHQ** [PaperMC/Paper#1441]
Hello, I recently update my paper spigot to latest 1.12.2 version
`[20:04:26 INFO]: This server is running Paper version git-Paper-1561 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[20:04:26 INFO]: Previous version: git-Paper-1559 (MC: 1.12.2)
[20:04:26 INFO]: Checking version, please wait...
[20:04:27 INFO]: You are running the latest version`

but the problem is when I want to do tab complete that was going to send an empty packet to the WaterFall and WaterFall is going to kick me: https://paste.ubuntu.com/p/5fQ7y69D9K/

I don't have this problem on previous build information :
`[20:07:28 INFO]: This server is running Paper version git-Paper-1547 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[20:07:28 INFO]: Previous version: git-Paper-1500 (MC: 1.12.2)
[20:07:28 INFO]: Checking version, please wait...
[20:07:28 INFO]: You are 14 version(s) behind`

**Comment by electronicboy** [comment]
Plugins, etc?
This is more than likely going to be an issue with a plugin messing with packets, the code isn't designed in a way that we could send an empty packet unintentionally

**Comment by MatinHQ** [comment]
is there any way to send you plugin list in private?

**Comment by electronicboy** [comment]
I'd prefer it on the issue tracker as then other people can look into it, given that this issue is more than likely guaranteed to be down to a plugin I'm feeling more inclined to close this issue, if anybody can provide any form of information which indicates that there is a potential for this to occur in our code, feel free to note it

**Comment by MatinDark** [comment]
Ok [here](http://s8.picofile.com/file/8337325850/2018_09_15_15_57_49.png) you are

**Comment by krusic22** [comment]
Can confirm this happening after build 1553: https://github.com/PaperMC/Paper/commit/cd5da239f84aa2bb94640bc479b2fb6d8f7ed31d

**Comment by egg82** [comment]
Can confirm as an issue, but we had it marked down as a plugin thing and I never got around to testing it. Likely candidates are PremiumVanish and ViaVersion.

Edit: Our issue also affected BungeeCord, not just Waterfall.

**Comment by electronicboy** [comment]
This appears to be confirmed as fixed, also going to look into dealing with waterfall

**Comment by electronicboy** [comment]
Wait, Wrong issue, but 100% guaranteed to be caused by a plugin and not us
