### ISSUE TITLE
Dynamic View Distance

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1447]
The player count of my server is very variable, and I always need to restart the server to buff the view distance if the server goes well, or nerf it if the server starts lagging.

It would be a good idea to put additionnal options for setting a dynamic view distance :
There could be a maximum, a minimum and a multiplicator (for example, the view distance is set to 10 chunks by default, loses 1 chunk every 10 players, and cannot go under 4 chunks).

It would be also possible (i think) of reducing the view distance automatically if the servers TPS starts dropping.

Thanks for reading my request !
(sorry if my english is not exact because i'm french baguette baguette)

**Comment by electronicboy** [comment]
Shamefully, this request falls over into the area in which a plugin would provide a  better solution, given that we couldn't address all needs/wants from such a system implemented in the server

Creating a plugin to do what you want would be a reasonable job for any plugin developer with the paper API as everything you'd need for it is already exposed in the API, just needs the logic strapping together
