### ISSUE TITLE
Server Crashing Randomly after 10-15 hours of running

### ISSUE THREAD

**Issue by LataRebo** [PaperMC/Paper#1448]
### Link/paste of stack trace
> [09:09:39 ERROR]: The server has stopped responding!
> [09:09:52 ERROR]: Please report this to PaperSpigot directly!
> [09:10:08 ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
> [09:10:08 ERROR]: PaperSpigot version: git-TacoSpigot-bf023c7 (MC: 1.8.8)
> [09:10:08 ERROR]: ------------------------------
> [09:10:08 ERROR]: Server thread dump (Look for plugins here before reporting to PaperSpigot!):
> [09:18:04 ERROR]: ------------------------------
> [09:18:05 ERROR]: Current Thread: Server thread
> [09:18:05 ERROR]: PID: 17 | Suspended: false | Native: false | State: RUNNABLE
> [09:18:05 ERROR]: Stack:
> [09:18:05 ERROR]: net.minecraft.server.v1_8_R3.ServerNBTManager.saveWorldData(SourceFile:43)
> [09:18:06 ERROR]: ------------------------------
> [09:18:06 ERROR]: Entire Thread Dump:
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Craft Scheduler Thread - 1953
> [09:25:01 ERROR]: PID: 3822 | Suspended: false | Native: false | State: TIMED_WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Craft Scheduler Thread - 1952
> [09:25:01 ERROR]: PID: 3821 | Suspended: false | Native: false | State: RUNNABLE
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: net.minecraft.server.v1_8_R3.NBTTagString.load(SourceFile:37)
> [09:25:01 ERROR]: net.minecraft.server.v1_8_R3.NBTTagCompound.a(SourceFile:406)
> [09:25:01 ERROR]: net.minecraft.server.v1_8_R3.NBTTagCompound.load(SourceFile:70)
> [09:25:01 ERROR]: net.minecraft.server.v1_8_R3.NBTTagCompound.a(SourceFile:406)
> [09:25:01 ERROR]: net.minecraft.server.v1_8_R3.NBTTagCompound.load(SourceFile:70)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: process reaper
> [09:25:01 ERROR]: PID: 3819 | Suspended: false | Native: false | State: TIMED_WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: pool-13-thread-1
> [09:25:01 ERROR]: PID: 349 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: CombatTagPlus ForceField Thread
> [09:25:01 ERROR]: PID: 321 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: AACTiming-Executor
> [09:25:01 ERROR]: PID: 319 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: pool-14-thread-1
> [09:25:01 ERROR]: PID: 317 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Chunk I/O Executor Thread-2
> [09:25:01 ERROR]: PID: 307 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Chunk I/O Executor Thread-1
> [09:25:01 ERROR]: PID: 306 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: pool-15-thread-1
> [09:25:01 ERROR]: PID: 305 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: pool-37-thread-1
> [09:25:01 ERROR]: PID: 304 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: ProtocolLib-StructureCompiler 0
> [09:25:01 ERROR]: PID: 303 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: File IO Thread
> [09:25:01 ERROR]: PID: 210 | Suspended: false | Native: false | State: RUNNABLE
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Timer-3
> [09:25:01 ERROR]: PID: 172 | Suspended: false | Native: false | State: TIMED_WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Query Listener #1
> [09:25:01 ERROR]: PID: 146 | Suspended: false | Native: false | State: RUNNABLE
> [09:25:01 ERROR]: Thread is waiting on monitor(s):
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: net.minecraft.server.v1_8_R3.RemoteStatusListener.run(SourceFile:261)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: factions-top-persistence-task
> [09:25:01 ERROR]: PID: 45 | Suspended: false | Native: false | State: TIMED_WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: factions-top-chunk-task
> [09:25:01 ERROR]: PID: 44 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: MVStore background writer nio:/home/container/plugins/FactionsTop/database.mv.db
> [09:25:01 ERROR]: PID: 142 | Suspended: false | Native: false | State: TIMED_WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: factions-top-sql-pool-0
> [09:25:01 ERROR]: PID: 139 | Suspended: false | Native: false | State: TIMED_WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-82
> [09:25:01 ERROR]: PID: 134 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-83
> [09:25:01 ERROR]: PID: 135 | Suspended: false | Native: true | State: RUNNABLE
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.nio.fs.LinuxWatchService.poll(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-80
> [09:25:01 ERROR]: PID: 132 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-81
> [09:25:01 ERROR]: PID: 133 | Suspended: false | Native: true | State: RUNNABLE
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.nio.fs.LinuxWatchService.poll(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-78
> [09:25:01 ERROR]: PID: 130 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-79
> [09:25:01 ERROR]: PID: 131 | Suspended: false | Native: true | State: RUNNABLE
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.nio.fs.LinuxWatchService.poll(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-76
> [09:25:01 ERROR]: PID: 128 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-77
> [09:25:01 ERROR]: PID: 129 | Suspended: false | Native: true | State: RUNNABLE
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.nio.fs.LinuxWatchService.poll(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-74
> [09:25:01 ERROR]: PID: 126 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-75
> [09:25:01 ERROR]: PID: 127 | Suspended: false | Native: true | State: RUNNABLE
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.nio.fs.LinuxWatchService.poll(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-72
> [09:25:01 ERROR]: PID: 124 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-73
> [09:25:01 ERROR]: PID: 125 | Suspended: false | Native: true | State: RUNNABLE
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.nio.fs.LinuxWatchService.poll(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Timer-2
> [09:25:01 ERROR]: PID: 119 | Suspended: false | Native: false | State: TIMED_WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Timer-1
> [09:25:01 ERROR]: PID: 117 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: AAC-DebugWriter
> [09:25:01 ERROR]: PID: 110 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: AAC-LogWriter
> [09:25:01 ERROR]: PID: 109 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-32
> [09:25:01 ERROR]: PID: 73 | Suspended: false | Native: true | State: RUNNABLE
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Okio Watchdog
> [09:25:01 ERROR]: PID: 71 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: HSQLDB Timer @688e562b
> [09:25:01 ERROR]: PID: 66 | Suspended: false | Native: false | State: TIMED_WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: org.hsqldb.lib.HsqlTimer$TaskQueue.park(Unknown Source)
> [09:25:01 ERROR]: org.hsqldb.lib.HsqlTimer.nextTask(Unknown Source)
> [09:25:01 ERROR]: org.hsqldb.lib.HsqlTimer$TaskRunner.run(Unknown Source)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: pool-12-thread-1
> [09:25:01 ERROR]: PID: 61 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: pool-11-thread-1
> [09:25:01 ERROR]: PID: 58 | Suspended: false | Native: false | State: TIMED_WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Netty Epoll Server IO #3
> [09:25:01 ERROR]: PID: 30 | Suspended: false | Native: false | State: RUNNABLE
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: io.netty.channel.epoll.Native.epollWait(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: MStore ModificationPollerRemote
> [09:25:01 ERROR]: PID: 57 | Suspended: false | Native: false | State: TIMED_WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: MStore ModificationPollerLocal
> [09:25:01 ERROR]: PID: 56 | Suspended: false | Native: false | State: TIMED_WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-23
> [09:25:01 ERROR]: PID: 54 | Suspended: false | Native: false | State: WAITING
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.misc.Unsafe.park(Native Method)
> [09:25:01 ERROR]: ------------------------------
> [09:25:01 ERROR]: Current Thread: Thread-24
> [09:25:01 ERROR]: PID: 55 | Suspended: false | Native: true | State: RUNNABLE
> [09:25:01 ERROR]: Stack:
> [09:25:01 ERROR]: sun.nio.fs.LinuxWatchService.poll(Native Method)
> [09:25:01 ERROR]: ------------------------------

### Plugin list:
(private) I think it has nothing to do with my plugins, let me know if yes
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
I use FactionSpigot, a custom TacoSpigot fork
This server is running CraftBukkit version git-TacoSpigot-bf023c7 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Comment by electronicboy** [comment]
1) You are not using our software
2) You are using a version of the server which has not been supported in several years

The crash also only really indicates that the server took too long to tick, that's really all we can see from that.
