### ISSUE TITLE
Can't add worlds during WorldLoadEvent

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#1453]
**Is your feature request related to a problem? Please describe.**
In one of my plugins, I adding a custom world immediately after the WorldLoadEvent (only if the overworld has been loaded). In this case, I get a ConcurrentModificationException when performing this operation. To avoid this, in plugin onEnable(), I replace worlds HashMap with ConcurrentHashMap, and everything starts working fine. However, you have recently made changes, and Paper now uses an improved version instead of the usual HashMap, i. e. PaperWorldMap. I don't want your work to be done in vain in my case and PaperWorldMap to be replaced by ConcurrentHashMap (because you do really good things).

**Describe the solution you'd like**
I would be grateful if PaperWorldMap extends ConcurrentHashMap - in that case, I would not perform a replacement, and my plugin would work even better.

**Additional context**
Answering the question why I adding custom world in WorldLoadEvent: because I need any plugin to have access to it at the time of its enable, as well as to the native worlds.

**Comment by aikar** [comment]
Can you instead just use the provided Bukkit API's instead of hacking into internals?

What is wrong with using the proper API's.

It sounds like you are adding this world async. That is not allowed. Simply move your world addition to be done on the main thread and you will not have concurrent modification issues.

**Comment by molor** [comment]
@aikar, I use Bukkit API methods everywhere in my plugin. The only exception is that I replace HashMap with ConcurrentHashMap using Reflection API at the moment of plugin enable.

And no, the world is not added asynchronously. Just look at how the WorldLoadEvent is called in the source, and why I get the exception.

**Comment by aikar** [comment]
@molor good to hear you are using the API's. I see why you are having the issue now.

Delay your world addition by 1 tick, and that will solve it.

**Comment by molor** [comment]
Maybe there is some other way to add world using Bukkit.createWorld() to have it added BEFORE all plugins are enabled, but I don't know about it and would also be grateful if you could tell me.

> Delay your world addition by 1 tick, and that will solve it.

No, scheduler starts after all plugins have been enabled. I need the opposite.

**Comment by aikar** [comment]
Why do you need it before all the plugins are enabled?

One thing I can see doing is moving WorldLoadEvent to fire after the iteration is finished. that will solve your como problem.

However note that making PaperWorldMap extend ConcurrentHashMap would not help, as we don't actually use the map.

So you should only 'patch' it if the type == IdentityHashMap for spigot, and I'll see about fixing the como issue this evening.

**Comment by molor** [comment]
> Why do you need it before all the plugins are enabled?

I need that any plugin to be able to access it at the time of its enable, as well as the native worlds. 

Otherwise, for example, if a plugin checks the Location in its configuration file in onEnable() and does not find the specified world on server, it will give an error. But specified world still exists, it just will be added after the error is received, when the plugin that adds it will be enabled.

**Comment by molor** [comment]
> However note that making PaperWorldMap extend ConcurrentHashMap would not help, as we don't actually use the map.

You are right, for some reason I did not immediately notice it.

**Comment by electronicboy** [comment]
So, you're trying to work around an issue in bukkits Location serialization?

**Comment by molor** [comment]
I gave the first example that came to mind of those that once faced.

That is, if config.yml contains something like:
```
location:
  world: myCustomWorld
  x: 0
  y: 63
  z: 0
```
then Bukkit.getWorld("myCustomWorld") will return null if myCustomWorld was not created at this point, but will be created later..

**Comment by aikar** [comment]
if you need this before onEnable finishes, then why don't you just create the world in your plugins onEnable instead of the event?

**Comment by molor** [comment]
@aikar, because there is no way to make sure that my plugin is always enabled first. Plugin can be enabled sixth, or can be enabled by the last. But another plugin that needs my custom world is enabled earlier, and at that moment my world does not exist.

**Comment by SpiderRobotMan** [comment]
In your plugin.yml you can tell it to load plugins before or after your own https://bukkit.gamepedia.com/Plugin_YAML

**Comment by molor** [comment]
@SpiderRobotMan, yes, I know. But putting names of all the plugins that exist in the universe there is not the best way to solve this problem. What if in my plugin another plugin are listed as depend (question is rhetorical)?
