### ISSUE TITLE
Server randomly crashing (Newest Paper --> 19-9-2018 (EU, 15:45 AMSTERDAM TIME)

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1456]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it.___

### Plugin list:
AdvancedBan, AntiCreeper, BlockLocker, DiscordSRV, PermissionsEx, EssentialsX, GuiPlus, WE and WG, PhantomSMP, RegionGUI

### Actions to reproduce (if known):

[wo, 19. sep 2018 09:03:42 CEST ERROR] The server has not responded for 10 seconds! Creating thread dump
[wo, 19. sep 2018 09:03:42 CEST ERROR] ------------------------------
[wo, 19. sep 2018 09:03:42 CEST ERROR] Server thread dump (Look for plugins here before reporting to Paper!):
[wo, 19. sep 2018 09:03:43 CEST ERROR] ------------------------------
[wo, 19. sep 2018 09:03:43 CEST ERROR] Current Thread: Server thread
[wo, 19. sep 2018 09:03:43 CEST ERROR]     PID: 18 | Suspended: false | Native: false | State: RUNNABLE
[wo, 19. sep 2018 09:03:43 CEST ERROR]     Stack:
[wo, 19. sep 2018 09:03:43 CEST ERROR]         java.util.zip.Inflater.inflateBytes(Native Method)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         java.util.zip.Inflater.inflate(Inflater.java:259)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         java.io.BufferedInputStream.read(BufferedInputStream.java:265)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         java.io.DataInputStream.readByte(DataInputStream.java:265)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:75)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:43)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.RegionFileCache.read(RegionFileCache.java:118)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:163)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:125)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:234)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:219)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:105)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.PlayerChunk.<init>(PlayerChunk.java:55)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.PlayerChunkMap.c(PlayerChunkMap.java:227)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.PlayerChunkMap.addPlayer(PlayerChunkMap.java:285)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:311)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:409)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:169)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13R2.LoginListener.Y(LoginListener.java:65)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:253)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:130)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1117)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:945)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:843)
[wo, 19. sep 2018 09:03:43 CEST ERROR]         java.lang.Thread.run(Thread.java:748)
[wo, 19. sep 2018 09:03:43 CEST ERROR] ------------------------------

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

**Comment by aikar** [comment]
This is not the newest paper. You are REALLY out of date.
You're just triggering lag warnings, this is not a crash.

The newest version of Paper as of a few weeks ago prints "This is not a crash. Do not report this to paper"
Ultimately, loading chunks is lagging you.

Best you can do is try the Async Chunks Beta which will solve this issue: https://achunks.emc.gs
