### ISSUE TITLE
[QUESTION] Boat moved wrongly!

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#146]
Is there anything I can do about the ''boat moved wrongly!'' flying machine console spam?
1. Build a simple flying machine
2. Launch it
3. Get in a boat
4. Watch your console get spammed

https://www.youtube.com/watch?v=uhbq1nMUutU

Tweaking moved wrongly values doesn't help. Can anyone point me in the right direction?

**Comment by Puremin0rez** [comment]
Spigot just made the values actually do something again.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/129f87a2c0ca73bea240b952d62e98ec59a1dc66

Give it a shot once Paper updates.

**Comment by zachbr** [comment]
Still relevant?

**Comment by hurrgurl** [comment]
Still relevant. Try it yourself, very easy to reproduce.

**Comment by zachbr** [comment]
Ultimately, "flying machines" are bugs in and of themselves, so it's not surprising the server does not handle them well.
