### ISSUE TITLE
High processor usage new Minecraft 1.13.1 Entities

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#1460]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___
https://timings.aikar.co/?id=f93b8b7891ec4867895ed3f4845f4374

### Description of issue:
___If applicable___
High processor usage new Minecraft 1.13.1 Entities

### Plugin list:
___All plugins running on the server___
`Plugins (91): 2048*, AdditionsAPI, AnvilRestrict, AreaShop*, Battleship*, ChangeSkin, ChatControl, ChestShop, Citizens, CitizensCMD, CombatLogX, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CrazyAuctions, CreativeNbtControl, DeluxeHeads, Duels, EnderContainers, EntityDetection*, Essentials*, EssentialsChat*, EssentialsGeoIP*, EssentialsSpawn*, EventekGUI, FastAsyncVoxelSniper, FastAsyncWorldEdit*, GameBox*, GemCrush*, GriefPrevention, JukeBox, Kezdes, LockettePro, LogicPuzzles*, Lottery*, LuckPerms*, mcMMO, MineMarket-Universal*, Minesweeper*, MobArena, MobHeads, MobMerge*, MP-GameBundle*, Multiverse-Core*, Multiverse-NetherPortals*, MyCommand*, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv*, Paintball, PickupSpawners, PlayerWarp, PlotSquared*, PlugMan*, PomaAdditions, ProtocolLib*, RandomTeleport*, redclockdetector*, RedstoneClockDetector*, RestrictedCreative, Shopkeepers, SignEdit*, StaffKezikonyv, StaffTime, Stats, SuperLuckyBlock-Pro, SurvivalGames*, Tagpluszkulcs, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChest, VanillaAdditions, Vault, Vipkulcs*, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, WhacAMole*, WorldBorderPearlBlock*, WorldEdit, WorldGuard, WorldGuardExtraFlags*, WorldGuardPomaFlags, YouTubeBridge`

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___
bukkit.yml: https://pastebin.com/zJVWDMq2
spigot.yml: https://pastebin.com/i3NkuP14
paper.yml: https://pastebin.com/wqp7JP3y
server.properties: https://pastebin.com/w2anHdNJ

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
```
20.09 19:30:23 [Server] INFO This server is running Paper version git-Paper-"a3677899" (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
20.09 19:30:23 [Server] INFO Previous version: git-Paper-"6e86b182" (MC: 1.13.1)
```

**Comment by aikar** [comment]
numerous fixes to water mobs have been placed, outside of that nothing else much to do. each mc update is heavier than the previous.
