### ISSUE TITLE
1.13.1 - Nerf the Fish Ai

### ISSUE THREAD

**Issue by tsiedsma** [PaperMC/Paper#1461]
It's no secret the cod ai is causing issues with 1.13.1, it would be nice to have an option in the config to disable fish ai altogether (drill down to types of fish if you want).  On an SMP with many many players and all the new water mechanics and features, the last thing we need is fish ai causing lag spikes and tps issues.

Not sure if this is something that can be handled with Paper or not but it would be an amazing feature.

**Comment by aikar** [comment]
if your going to nerf their AI, just stop them from spawning.

a fish sitting still isn't really accomplishing anything?

**Comment by tsiedsma** [comment]
Well, they would still spawn but just sit there any not try to path find.

**Comment by aikar** [comment]
Also, we have no evidence to show that their AI is directly responsible for the lag yet...

What we do know, is that them pathfinding has been a huge source of synchronous chunk loads. I've fixed quite a few of them, but I'm fairly sure I saw a remaining trigger that is unresolved.

Their pathfinding shouldn't be any worse than other mobs, we just have to stop the chunk loads.

**Comment by tsiedsma** [comment]
That's fair.  I haven't experienced it firsthand, and personally don't care about the fish spawning at all.  Was just looking to avoid issues in the future, but maybe 1.13.2 will resolve some of those issues and I won't have to worry about it.  Thanks for your feedback :)

**Comment by Brokkonaut** [comment]
Ihdev you can use a plugin that disables their AI.

**Comment by BillyGalbreath** [comment]
To be honest, I'm unable to reproduce all these claims of "fish cause lag"

I spawned a few hundred fish in a small pond and just sat there staring at them. The first 100 fish didnt cause much of a fuss, so more were spawned. At least 500 or so (I'm assuming, I lost count) with lots and lots of collisions going on still didnt produce anything out of the ordinary (just the typical raise in usage you would expect from such cramming).

https://timings.aikar.co/?id=5cd921cc185044ba9147baa403c2d6c9

![Fish!](https://i.imgur.com/fAkKd1L.jpg)

**Comment by tsiedsma** [comment]
I haven't seen it either, just thought it might be a nice option in the config to disable the AI instead of using a 3rd party plugin to disable fish.  I'm not messing with them on my server, we have not had an issue.  Just forward thinking I guess.

**Comment by aikar** [comment]
Fixed this a few days ago
