### ISSUE TITLE
Fish causing lag

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1462]
###  Timings or Profile link:
https://timings.aikar.co/?id=16112adaede841f1be19a413dbe37ae2#timings

### Description of issue:
Seems tropical fish causes lag
Funny thing is, I dont see any fish. Searched everywhere.
No random spawning fish, no dolphins.

### Paper build number:
Paper version git-Paper-274 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by x1p** [comment]
The problem with no fish in the sea is because of a know bug.
https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-4368?filter=allopenissues

Still, the turtles give a serious amount of lag.

**Comment by BillyGalbreath** [comment]
To be honest, I'm unable to reproduce all these claims of "fish cause lag"

I spawned a few hundred fish in a small pond and just sat there staring at them. The first 100 fish didnt cause much of a fuss, so more were spawned. At least 500 or so (I'm assuming, I lost count) with lots and lots of collisions going on still didnt produce anything out of the ordinary (just the typical raise in usage you would expect from such cramming).

https://timings.aikar.co/?id=5cd921cc185044ba9147baa403c2d6c9

![Fish!](https://i.imgur.com/fAkKd1L.jpg)

**Comment by x1p** [comment]
I strongly believe that the breeding and hatching of turtles are the main cause.

**Comment by x1p** [comment]
The turtle lag is much less now. I think this can be closed.

**Comment by aikar** [comment]
The issue was about fish, but I've now fixed water mob lag in general now in Paper 331+
