### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by vaniron** [PaperMC/Paper#1463]
Hi, i am noob in terms of java so just asking if it is ok/recommended to use asyncworld with world system plugin which basically generates worlds per player and if there are any other ways how to improve server performance in this case.. Not having any issues just wanting to improve for possible higher player count in the future.

**Comment by hafarooki** [comment]
https://paperdiscord.emc.gs is more suited for this

**Comment by vaniron** [comment]
Well async generating was merged into paper anyway and it looks working good for me so far. Thanks for discord link.
