### ISSUE TITLE
Players are bugging through blocks after teleport

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#147]
# Incompatibility (Bug)
### What behaviour is expected:

**_After a teleport players should stand on the surface.**_
### What behaviour is observed:

**_After a teleport players don't stand on the surface, they are bugging through blocks.**_
### Steps/models to reproduce:
1. Set a teleportation location with a plugin (e.g.: /home; /is;)
2. Make sure that the chunks where this location is are unloaded for you
3. Use the teleportation command
### Plugin list:

**_PermissionsEx, Modifyworld, Vault, ASkyblock**_
### Paper build number:

**_Paper-575**_

**Comment by Gabscap** [comment]
A plugin side workaround for this problem is to load the chunk before teleporting the player. I have created a PR which lets the server load the chunk.

**Comment by ghost** [comment]
Commit doesn't fix the bug. I don't think that this is the problem of the chunk loading because it's also happening with /tpa requests where one players already loaded all chunks (you only have to make sure that the second player - who teleports to the first one - didn't loaded the chunks where the first one is).

**Comment by ghost** [comment]
I tested it again with build 581: The problem does still exist.

**Comment by ghost** [comment]
Any news on this?

**Comment by Gabscap** [comment]
I have no idea what else can be done serverside to prevent this from happening. You can work around this issue by setting the teleport destination 0.5-1 blocks above the ground.

**Comment by ghost** [comment]
Well the bug appeared appeared with 575 (or a few versions before, but not more than 10-15).

Maybe the issue is caused by a commit like these two:
https://github.com/PaperMC/Paper/commit/8b76c66f4b9aa54effadef82a3fe18f8e4fef506
https://github.com/PaperMC/Paper/commit/5bd7a9ab6235de76d98f5e8ca07befa6cb4d8a5d

**Comment by LuminousLoreBloom** [comment]
Perhaps it can be solved by sending a PacketPlayOutMapChunk before teleport?

**Comment by Gabscap** [comment]
I'ts worth a try, but I dont know how the client handles this packet if the chunk is not in range. Maybe someone knows and wants to enlighten us?

**Comment by BlackBeltPanda** [comment]
I'm also having this problem. I added 0.5 to the player's y-dimension on teleport in my plugin but it only sometimes helps. It seems to occur with any plugin-induced teleportation.

**Comment by ghost** [comment]
Finally fixed if you use build 669 (I think already with 666, huge thanks to @aikar for https://github.com/PaperMC/Paper/commit/3f68b7f930dc4c3bf62dba67aa0d17d9bba938be)
