### ISSUE TITLE
Server Crash when generating chunks

### ISSUE THREAD

**Issue by TriaticMonkey** [PaperMC/Paper#1470]
### Stacktrace:
https://pastebin.com/fAbjNUUa

### Plugin list:
CoreProtect, GriefPrevention, Multiverse-Core, PermissionsEx, SuperbVote, Votifier, WorldEdit

### Actions to reproduce:
Use git-Paper-279, generate a new chunk

### Paper build number:
git-Paper-279

### Extra Info:
Downgraded back to Paper-274 and it doesn't crash
I think the Chunk reworks in Paper-277 cause this

**Comment by Brokkonaut** [comment]
can confirm that, it just crashed my server too

**Comment by tsiedsma** [comment]
Also seeing crashes related to chunk generation

Crash Report:
https://gist.github.com/lhdev/694a547bbf5aca7cb4bfabd996c6655d

**Comment by melinstagibson** [comment]
Same issue here
