### ISSUE TITLE
Crash when some player tried to place a shulker chest

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#1471]
Its a server converted from 1.12.2 to 1.13.1. When some player tried to place a shulker box it gave this error:

https://pastebin.com/raw/JhZRwmVf

And then thousands of more errors until the server died.

**Comment by TriaticMonkey** [comment]
Shulker boxes seem fine on my test server.

**Comment by Brokkonaut** [comment]
Most shulker boxes on my server are fine too, it looks like the names of some named boxes were not properly converted

**Comment by zachbr** [comment]
Thanks for letting us know, builds 283+
