### ISSUE TITLE
Server crashed, Minecraft 1.13.1, git-Paper-273

### ISSUE THREAD

**Issue by Rhaelyxs** [PaperMC/Paper#1472]
### Actions to reproduce (if known):
All I know is that I was getting beaten up by the Drowned

[crashpapermc.txt](https://github.com/PaperMC/Paper/files/2407968/crashpapermc.txt)

**Comment by mikroskeem** [comment]
Seems like server just lagged out. Has this happened more than once?

**Comment by Rhaelyxs** [comment]
That was the first time.

**Comment by zachbr** [comment]
Doesn't appear to be much here for us to work with. If someone can find some specific and reproducible case causing this or other performance issues they should let us know.
