### ISSUE TITLE
Reloading the servers list during the startup cause errors

### ISSUE THREAD

**Issue by iGabyTM** [PaperMC/Paper#1473]
### Link/paste of stack trace

https://paste.helpch.at/idafitomap.md

### Plugin list:
AgarthaLib, Carz, Citizens, CitizensCMD, DreamFish, Essentials, EssentialsSpawn, FastAsyncWorldEdit, HolographicDisplays, HolographicExtension, LuckPerms, NametagEdit, PlaceholderAPI, PlugMan, ProtocolLib, QuickBoard, TitleManager, Vault, ViaBackwards, ViaVersion, WG-GUI, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Actions to reproduce (if known):
Servers list refresh during the startup

### Paper build number:
1562

**Comment by BillyGalbreath** [comment]
@Minecrell I was told to ping you for this.

My diagnosis is a simple race condition. During startup there is a short period where the server is responding to pings (creating the server list ping event) before the player sample is actually populated, creating the NPE.

**Comment by zachbr** [comment]
Thanks for letting us know. 1.13.1 Builds 289+

**Comment by zachbr** [comment]
1.12.2 builds 1564+
