### ISSUE TITLE
Corrupted playerdata [Feature request]

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#1474]
Since I upgraded to 1.13 a few players can't connect and get an "Internal server error" would it be possible to add something where it just deletes there player data if the error orrcures? Maybe you could just attempt to fix the data automatically on join?

Here's the playerdata:
http://185.38.149.99/downloads/81f3b618-4d28-46a0-9c7c-bc011b4940e8.dat
Here's there error:
https://pastebin.com/raw/3DvqQUCc

**Comment by Brokkonaut** [comment]
Similar to this one: https://github.com/PaperMC/Paper/issues/1471 

Maybe ignoring bad json in ChatDeserializer would be an option? Like just return an empty textcomponent and printing an error to the console

**Comment by zachbr** [comment]
Thanks for letting us know, builds 283+
