### ISSUE TITLE
WildernessTP not working on Paper

### ISSUE THREAD

**Issue by briang112** [PaperMC/Paper#1475]
### What behaviour is expected:
For the player to be teleported to a random spot upon executing /wild

### What behaviour is observed:
Internet server error when attempted to execute /wild

### Steps/models to reproduce:
Simply attempt to excute the "/wild" command.

### Plugin list:
INFO Plugins (51): BuycraftX*, ChatFormat*, ChestCommands*, Citizens, CoinFlipper*, CommandDoesNotExist, CommandNPC*, ConditionalCommands*, CrateReloaded, CrazyAuctions*, DeathMessagesPrime*, DeluxeMenus*, Essentials*, EssentialsChat*, EssentialsSpawn*, FeatherBoard*, HolographicDisplays, Interactables*, Jobs, LagAssist, Lands, LiteBans*, LuckPerms*, mcMMO, Multiverse-Core*, Multiverse-NetherPortals*, MVdWPlaceholderAPI*, MyCommand*, NightVisionReloaded*, NoNetherRoof*, OreAnnouncer*, PlaceholderAPI, ProtocolLib*, PvPToggle*, Rankup, React*, ServerListPlus*, ShopGUIPlus, SilkSpawners, SuperbVote, SuperTrails*, SuperVanish*, TAB, TitleManager*, Vault*, Votifier, WG-GUI, Wild, WorldBorder*, WorldEdit, WorldGuard

### Paper build number:
23.09 00:50:44 [Server] INFO This server is running Paper version git-Paper-284 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

### Anything else:
Plugin Link: https://www.spigotmc.org/resources/wilderness-tp.18431/

**Comment by zachbr** [comment]
Did you report an error without actually linking the error?

**Comment by tsiedsma** [comment]
I'm using it on Paper 1.13.1 and it works fine

**Comment by tsiedsma** [comment]
Maybe report to the mod author?

**Comment by hafarooki** [comment]
`Internal Server Error` means that an error occurred in the code when trying to run your command. The full error is in your console, go get it.

**Comment by RoboMWM** [comment]
You're using the wrong wilderness-tp plugin. [This is the one you want.](https://www.spigotmc.org/resources/wilderness-tp-the-one-true-wild-tp.22853/)

**Comment by briang112** [comment]
Thanks Robo, that worked.

**Comment by zachbr** [comment]
Author changed plugins completely but we never got enough information to look at the issue. Guess this is closed then?
