### ISSUE TITLE
Lagspikes with 1.13.1

### ISSUE THREAD

**Issue by timr2000** [PaperMC/Paper#1476]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___

### Description of issue:
___https://timings.aikar.co/?id=2c70d75b4b75454aa5f141e4a355d563___

### Plugin list:
___http://prntscr.com/kxo7j2___

### bukkit.yml, spigot.yml, paper.yml, server.properties
___paper:https://pastebin.com/rJc8biL7 spigot:https://pastebin.com/E8MzDdha bukkit:https://pastebin.com/bnjDLBM8___

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
___http://prntscr.com/kxo7f8___

**Comment by HauserGrim** [comment]
Update paper and try again

**Comment by timr2000** [comment]
> 
> 
> Update paper and try again

Got the latest version.. 291

**Comment by HauserGrim** [comment]
> > Update paper and try again
> 
> Got the latest version.. 291

Sorry, I did not look carefully at the screenshot and saw the previous version

**Comment by aikar** [comment]
Use my recommended GC flags for one: https://mcflags.emc.gs
2nd) Lower your animals activation range in spigot.yml. I use around 12. You seem to have both issues with Cod and Chickens.
