### ISSUE TITLE
Server seemingly randomly crashes with message "Timed out". However server does not lag before hand

### ISSUE THREAD

**Issue by archiebakeru1660913** [PaperMC/Paper#1477]
### Link/paste of stack trace

https://pastebin.com/Z89wVRay
___We need all of the stack trace! Do not cut off parts of it.___

### Plugin list:
___A list of your plugins___
![image](https://user-images.githubusercontent.com/42930694/45930730-9bb41680-bf5b-11e8-8b15-b9671412784b.png)

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Unsure, seems to happen when players join (But again i'm unsure)

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

git-Paper-254 (1.13.1)

**Comment by electronicboy** [comment]
Slow disk?
Your logs are indicating that your major hold up is chunk loading, I'd also heavily suggest ensuring that you've updated.

closing due to outdated version/likely not our issue
