### ISSUE TITLE
Tab complete kicks users [Only after PaperSpigot build 1552] (so 1553 & up)

### ISSUE THREAD

**Issue by cloakfox** [PaperMC/Paper#1482]
First of this kick only happens when using Bungeecord or Waterfall (haven't tested lilypad)
But for some reason **after PaperSpigot build 1552** users get kicked to the hub when trying to tab complete commands or usernames. They instantly get kicked.

There are 0 errors in PaperSpigot console, after some extensive testing with different builds of paperspigot and waterfall managed to pick up an error in Waterfall that might be usefull.

https://hastebin.com/sofemuguhi.bash

Now the reason why I am reporting this here is because this started to happen after build 1552 for PaperSpigot, tried downgrading proxy versions but that didn't fix the issue.

PaperSpigot: 1562 (latest at the time of writing) (1.12.2)
Plugins: ViaVersion 1.5.2, viarewind-all-1.3.13, viabackwards-all-2.3.1.jar, ViaRewind Legacy Support-1.3.1.jar

Waterfall: #223

_I am currently running 1552 to prevent the tab completion kicks_

**Comment by electronicboy** [comment]
Pre 1553, Paper wasn't handling tab completion properly and wouldn't send a response back in many cases, could you please try to replicate this issue without plugins on the server
