### ISSUE TITLE
Many light bugs

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#1483]
Since some days we have huge problems with light bugs, light not updating or light updating too late, also clients have noticeable more lag (probably when the client tries to fix the light) since this change.

Current build is git-Paper-294, previously on that server (where those light bugs did not exist) was git-Paper-278

Example of the light bugs: https://cubeimage.de/images/2018/09/24/OBjx.png

**Comment by Brokkonaut** [comment]
I found this change to be the cause:
https://github.com/PaperMC/Paper/commit/e07e0cb3ca5626472d629051b6919d1f0671358b#diff-767d6043c8896301795fbbdde8add109R39
When I disable the light queue there are no problems. Is it possible to readd that config option? I don't think that its something that should be enforced for all users.

**Comment by aikar** [comment]
I'm going to work on improving the light queue instead. I was unaware the light queue caused a big difference until now heh.

Improvements that should have no difference in expectations do not need a config. If we are unable to fix the issue, then I will re-add the config back, but going to try fixing it first.

**Comment by Brokkonaut** [comment]
Ok, if this can be fixed it would be great :)

**Comment by Luysita** [comment]
Same is happening with my server's players:

![2018-10-03_11 07 52](https://user-images.githubusercontent.com/4097013/46402793-a9566280-c6f8-11e8-818d-e7c61834b248.png)
![2018-10-03_11 20 56](https://user-images.githubusercontent.com/4097013/46402802-ab202600-c6f8-11e8-88b5-8cb902bdb8f6.png)
![2018-10-03_11 32 05](https://user-images.githubusercontent.com/4097013/46402806-ad828000-c6f8-11e8-93c0-ad82ceb5737f.png)


Using build 327.

**Comment by aikar** [comment]
I think this relates to #1539  - the recheck gaps change was likely causing all these issues.

please reopen if still having issues.

1.13 in build 341+.
1.12 in build 1574.
