### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by crejk** [PaperMC/Paper#1485]
* What went wrong:
Could not resolve all files for configuration ':bukkit:compileClasspath'.
```
> Could not resolve net.md-5:bungeecord-chat:1.13-SNAPSHOT.
  Required by:
      project :bukkit > com.destroystokyo.paper:paper-api:1.13.1-R0.1-SNAPSHOT
   > Could not resolve net.md-5:bungeecord-chat:1.13-SNAPSHOT.
      > Could not parse POM https://papermc.io/repo/repository/maven-public/net/md-5/bungeecord-chat/1.13-SNAPSHOT/bungeecord-chat-1.13-20180902.212957-1.pom
         > Could not find net.md-5:bungeecord-parent:1.13-SNAPSHOT.
           Searched in the following locations:
               file:/home/travis/.m2/repository/net/md-5/bungeecord-parent/1.13-SNAPSHOT/maven-metadata.xml
               file:/home/travis/.m2/repository/net/md-5/bungeecord-parent/1.13-SNAPSHOT/bungeecord-parent-1.13-SNAPSHOT.pom
               file:/home/travis/.m2/repository/net/md-5/bungeecord-parent/1.13-SNAPSHOT/bungeecord-parent-1.13-SNAPSHOT.jar
               https://repo.maven.apache.org/maven2/net/md-5/bungeecord-parent/1.13-SNAPSHOT/maven-metadata.xml
               https://repo.maven.apache.org/maven2/net/md-5/bungeecord-parent/1.13-SNAPSHOT/bungeecord-parent-1.13-SNAPSHOT.pom
               https://repo.maven.apache.org/maven2/net/md-5/bungeecord-parent/1.13-SNAPSHOT/bungeecord-parent-1.13-SNAPSHOT.jar
               https://papermc.io/repo/repository/maven-public/net/md-5/bungeecord-parent/1.13-SNAPSHOT/maven-metadata.xml
               https://papermc.io/repo/repository/maven-public/net/md-5/bungeecord-parent/1.13-SNAPSHOT/bungeecord-parent-1.13-SNAPSHOT.pom
               https://papermc.io/repo/repository/maven-public/net/md-5/bungeecord-parent/1.13-SNAPSHOT/bungeecord-parent-1.13-SNAPSHOT.jar
```

**Comment by electronicboy** [comment]
I don't think that spigot publishes the bungeecord-parent to a maven repo, but that is what you're apparently missing, you might need to compile bungeecord locally and install it to your local maven repo

**Comment by electronicboy** [comment]
Actually, nvm, those files are deployed on the papermc repo, either you're having connection issues to the repo or you have something that is breaking the file download on your system

**Comment by crejk** [comment]
@electronicboy https://travis-ci.org/BestGuilds/BestGuilds/builds/432628900?utm_source=github_status&utm_medium=notification

**Comment by MiniDigger** [comment]
@electronicboy the bungee parent pom isn't deployed to the paper repo:
https://papermc.io/repo/#browse/browse:maven-public:net%2Fmd-5%2Fbungeecord-chat
it is however present in the sonatype repo:
https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bungeecord-parent/
I guess paper should mirror that repo

@crejk for now I would recommend adding the sonatype repo to your list of repos
https://oss.sonatype.org/content/repositories/snapshots/

**Comment by electronicboy** [comment]
Sorry, I was working on several things and got distracted (this issue is primarily closed because build issues with your plugin aren't an issue with this software), however; As @MiniDigger stated, some of bungee is deployed to central which is a repo that is always considered by all maven clients, try adding it to your repos, if that doesn't work, I'll explicitly add it to the maven pom (as the fact that it's not declared in there is kinda gross anyways)

**Comment by crejk** [comment]
@MiniDigger thanks

**Comment by MiniDigger** [comment]
the sonatype repo isn't automatically considered by maven clients, maven central is, the sonatype snapshot repo isn't iirc.
