### ISSUE TITLE
Sorry if this wrong place to go and I know it might not be paper, but I don't know where else to ask getting weird error I don't understand

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#1486]
Weird error I can't understand
https://hastebin.com/oyakozaved.cs

**Comment by electronicboy** [comment]
You have a plugin that is spewing out some information in some library it uses, you'll likely need to perform some work of elimination in order to work out what plugin it is

**Comment by axemwa** [comment]
thanx ill see if i can find out whats causing it, wierd though the error only comes up occasinally/rarely, I originally thought it was a connection dropout of some sort that was happening when a plugin was trying to access the internet to gather info for example skins, so you don't think it would be that?

EDIT - Also do you think headdatabase is causing it? - https://www.spigotmc.org/resources/head-database.14280/
