### ISSUE TITLE
Spam WARN in console

### ISSUE THREAD

**Issue by Sakanas** [PaperMC/Paper#1488]
**is there any way to remove this spam?**
began to appear in the latest version

`25.09 05:51:16 [Server] WARN Tried to add entity minecraft:blaze but it was marked as removed already
25.09 05:51:16 [Server] WARN Tried to add entity minecraft:skeleton but it was marked as removed already
25.09 05:51:16 [Server] WARN Tried to add entity minecraft:skeleton but it was marked as removed already
25.09 05:51:17 [Server] WARN Tried to add entity minecraft:blaze but it was marked as removed already
25.09 05:51:23 [Server] WARN Tried to add entity minecraft:cow but it was marked as removed already
25.09 05:52:28 [Server] WARN Tried to add entity minecraft:item but it was marked as removed already
25.09 05:52:28 [Server] WARN Tried to add entity minecraft:item but it was marked as removed already
25.09 05:52:28 [Server] WARN Tried to add entity minecraft:item but it was marked as removed already
25.09 05:52:28 [Server] WARN Tried to add entity minecraft:item but it was marked as removed already`

### Steps/models to reproduce:
I ran around the map and it appeared

### Plugin list:
Plugins (71): AAC, AntiBotDeluxe, Arconix, ASkyBlock, AuthMe, BannerMaker, BattleLevels, BetterSleep, BKCommonLib, BlockLocker, BottledExp, ChestShop, Citizens, CMI, CommandNPC, CoreProtect, CrazyCrates, CS-CoreLib, dtlTraders, EliteMobs, EpicSpawners, ExoticGarden, FastAsyncWorldEdit, HackedServer, Heads, JDALibLoaderBukkit, JH_Chain, JH_Shop, Jobs, LagAssist, LibsDisguises, LuckPerms, Marriage, mcMMO, mcMMOHorse, MinePacks, MobFarmManager, MobHunting, MultiWorldMoney, My_Worlds, MyCommand, MyPet, MythicMobs, PandaWire, PlaceholderAPI, PluginConstructorAPI, PlugMan, ProtocolLib, PvPManager, Reputation, Residence, Revenge, RPGFood, SavageDeathChest, Shopkeepers, SimpleClans, Slimefun, StackMob, TokenManager, TradeMe, TryMe, UltimateChat, UltimateTrash, Vault, VoidSpawn, Votifier, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, Zenchantments

### Paper build number:
25.09 05:55:01 [Server] INFO CMI plugin version: 8.0.11.0
25.09 05:55:01 [Server] INFO Server version: Paper(1567) 1.12.2-R0.1-SNAPSHOT
25.09 05:55:01 [Server] INFO Vault version: 1.6.11(+)

**Comment by aikar** [comment]
This is indicative of a plugin doing something undesirable.

You can add to your startup flags -Ddebug.entities=true to find out what one.

Please paste results on Discord and we can advise from there.
