### ISSUE TITLE
Server crash, 1.13.

### ISSUE THREAD

**Issue by Rhaelyxs** [PaperMC/Paper#1489]
### Actions to reproduce (if known):
I was walking near an end city.
[paper_crash.txt](https://github.com/PaperMC/Paper/files/2416276/paper_crash.txt)

**Comment by oxycclock** [comment]
Update your server to #300

**Comment by electronicboy** [comment]
I'd suggest checking your full log file, there should be more information as to what was holding up the server for so long that it took a full minute to tick
