### ISSUE TITLE
Portal chat freeze game-mechanics: flag request

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1492]
Normally with an unmodified client, while being inside a nether portal waiting to be teleported chat is disabled for whatever reason. I request it to be added to under game-mechanics: where it can be set to false to not disable chat.

**Comment by 0-x-2-2** [comment]
This is clientsided and could be done by a simple plugin using [protocol-lib](https://www.spigotmc.org/resources/protocollib.1997/) to destroy the portal blocks clientsided when a player clicks the blocks or similar.

**Comment by electronicboy** [comment]
as noted above, this isn't controlled by the server, but there are tricks that a plugin could take to work around this.
