### ISSUE TITLE
Villager disppear

### ISSUE THREAD

**Issue by Will33ELS** [PaperMC/Paper#1495]
### What behaviour is expected:
___Every time the server reboots, villagers disappear___

### What behaviour is observed:
___What you actually saw___

### Plugin list:
___Plugins (20): BuycraftX, ChestShop, Citizens, CommandNPC, Craftconomy3, CrateReloaded, ElenoxCore, ElenoxEventConfigurator, ElenoxHDV, ElenoxSkyblockV3, FastAsyncWorldEdit, HeadDatabase, HolographicDisplays, MobStacker, Multiverse-Core, PermissionsEx, Shopkeepers, Vault, ViaVersion, WorldEdit___

### Paper build number:
___Paper version git-Paper-1500 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)___

### Anything else:
___I tried to switch my server to Spigot and the problem is fixed. I handed PaperSpigot but I can not stay with this bug: /___

**Comment by electronicboy** [comment]
You are currently 68 builds outdated, there have been many fixes to the code which handles saving entities and stuff in the world since then.
