### ISSUE TITLE
invisible citizens npcs

### ISSUE THREAD

**Issue by BBoyJD10** [PaperMC/Paper#1496]
### What behaviour is expected:
___What you expected to see___
Citizens npcs sometimes turn invisible 

### What behaviour is observed:
___What you actually saw___
no citizens npcs sometimes

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
latest version with async

### Plugin list:
___A list of your plugins___
just citizens and spigot

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
build 304 

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by vaniron** [comment]
Can confirm this issue, also happening on my server - same version 304.

**Comment by sgdc3** [comment]
This is unrelated to async chunks, as i'm experiencing similar issues since 1.13.1/1.13, also i think npcs aren't spawned at all, not just invisible. @BBoyJD10 I think you should report this issue to Citizens first.

**Comment by BBoyJD10** [comment]
Definitely didnt have this before the merge @sgdc3

**Comment by aikar** [comment]
Try build 311+ please and see if it continues, 1569 for 1.12.2

**Comment by BBoyJD10** [comment]
Still occurring here on build 311

**Comment by BiGUNMAN** [comment]
Enable debug in the citizens config?

I'm having a similar issue, however some of my NPC's aren't being spawned:. Here's my citizens debug (I reported this issue to the devs there): https://pastebin.com/FVeNdHd9

As @sgdc3 said, these Citizens fail to be spawned, they aren't invisible. That's because if you select a citizen, and type /npc spawn, they will only spawn if despawned. If an NPC is invisible but spawned, you'll have to select it, despawn it, and spawn it again (this is if we have the same issue).

Citizens Dev responded and basically said they don't care about Paper users... https://github.com/CitizensDev/Citizens2/issues/1580

**Comment by sgdc3** [comment]
This needs to be fixed paper side then, if spigot is fine it's probably caused by some of the recent chunk loading/entity changes

**Comment by aikar** [comment]
Nothing we can do until more information on how to reproduce is given. I've loaded big's data files just fine.

Try removing plug-ins to find which one is causing it

**Comment by aikar** [comment]
Still unable to repro any issues, even using @BBoyJD10's plugin files...

Things of note, UltraComestics failed to load in my test server, and could relate to it if you can try removing that.

Do you use that @sgdc3 ?

**Comment by BiGUNMAN** [comment]
This is my plugin list, and I did not use UltraCosmetics: https://i.imgur.com/rAaDU4T.png
Note: I'm not launching anything with Plugman, use it only for testing purposes.

**Comment by vaniron** [comment]
I got invisible npcs on server restart, but those directly on spawn are visible. Maybe this info could help.

**Comment by sgdc3** [comment]
@aikar no, i don't use such plugin

**Comment by CeIebrimbor** [comment]
This is still a thing. Citizens2 NPCs will periodically not spawn when entering their area. Using /citizens2 reload usually ends up spawning them.

**Comment by aikar** [comment]
Looking at Citizens bug tracker, there are open bugs that sound like the source of this issue.

nobody has provided a way to reproduce the issue to me. Citizens load just fine for me.... Even using files provided by people with the said problem.

**Comment by aikar** [comment]
https://github.com/CitizensDev/Citizens2/issues/1332

**Comment by zachbr** [comment]
Closing as fixed with the above citizens ticket.
