### ISSUE TITLE
Light source appears around block broken under water

### ISSUE THREAD

**Issue by FixTheAdmin** [PaperMC/Paper#1499]
### What behaviour is expected:
No light source when block is broken.

### What behaviour is observed:
Breaking a block under water creates a light source around the block. Does not go away when block is replaced. This visual glitch is not resolved after reconnecting or restarting the server. This does not appear to happen in hand made pools of water.
https://i.imgur.com/AjdwCyt.jpg

### Steps/models to reproduce:
-forceupdate a custom map to 1.13 from 1.12. This specific map was made in worldpainter. Break a block under water. Light will appear. 

### Plugin list:
No plugins installed.

### Paper build number:
https://i.imgur.com/AjdwCyt.jpg

### Anything else:
Server is behind waterfall proxy.

**Comment by aikar** [comment]
do you have the light queue enabled? if so, try disabling it.

We've had one other person report this too. And this is truely with no plugins?

**Comment by FixTheAdmin** [comment]
queue-light-updates is set to false.
Disovered the bug when I already had plugins. Removed the plugins and bug still appears. https://i.imgur.com/k2EJapF.jpg

**Comment by aikar** [comment]
I don't expect it to auto repair itself. does NEW light emit without plugins?

**Comment by FixTheAdmin** [comment]
Indeed, new light emit without plugins. Sorry for being unclear.

**Comment by aikar** [comment]
https://minecraft.gamepedia.com/Water Apparently this is not a bug, and an intended change in 1.13.
The server is recalculating the light to the new 1.13 rules, so pre 1.13 chunks are darker than they should be.

Thanks @Brokkonaut for informing us of this.

**Comment by FixTheAdmin** [comment]
Thank you very much for providing an explanation and sorry for reporting it here. Would it be possible for -forceupdate to change water to the correct lightning? Have a nice day.

**Comment by KarlOfDuty** [comment]
Is this not a bug with converting from a 1.12.2 world to a 1.13 one? 

As you say it is getting the wrong light level so saying it is not a bug seems incorrect. It's just that the bug is the rest of the world instead of the area around the block.

**Comment by electronicboy** [comment]
If you had random lighting disabled (Which is set by default), you're likely dealing with the side effects of spigot having a patch to workaround the side effects of disabling random light updates

**Comment by aikar** [comment]
@KarlOfDuty mojang chose to not convert that...

It would also really slow down conversion if we triggered a light update on every water block in a chunk (just the act of DETERMINING water blocks would be heavy, we would have to scan the entire chunk)

It's just something youll have to live with.

**Comment by FixTheAdmin** [comment]
@electronicboy Would reconverting the world with random light enabled give me a better result?

**Comment by aikar** [comment]
@Bezod no.

**Comment by FixTheAdmin** [comment]
For anyone else having this issue, spoke with the developer creatorfromhell and he made a plugin that corrects lightning on chunk load. https://www.spigotmc.org/resources/1-13-lighting-fix.61185/
