### ISSUE TITLE
Exception Events

### ISSUE THREAD

**Issue by natemort** [PaperMC/Paper#15]
Hello, I'm currently looking into integrating my server with https://raygun.io/ (specifically the error reporting) but to do so there needs to be some way for plugins to generally handle or at least be notified of exceptions.  I'm perfectly willing to  write this feature myself and am planning on doing so for my own fork, however I figured I might as well see if: a) anyone else is interested in this feature; and b) if anyone else has input on the design of such a system.

  What I currently have in mind for API design is a base event which has a HandlerList, ExceptionEvent, which is fired whenever the server would print an exception to the log.  I believe the exception should be printed prior to the event being fired, as there should always be at least some degree of logging whenever things go bad.  Beyond ExceptionEvent there would be something along the lines of ListenerExceptionEvent, for when plugins throw an exception while listening to an event, CommandExceptionEvent, for when plugins throw an exception while executing a command, and an InternalExceptionEvent, for when something goes wrong within Minecraft's internals.  There'd probably be a few more specific events, as I haven't really looked too thoroughly over all the situations in which something can go wrong(PluginMessageExceptionEvent?).  No event would be fired for exceptions thrown by a handler of ExceptionEvent.

The purpose of the numerous sub-events is to provide as much contextual information as possible to the listener of the ExceptionEvent.  Please let me know what you think, if this is something you're interested I'll have a PR up for this by the weekend.

**Comment by kashike** [comment]
I'm interested in seeing this

**Comment by zachbr** [comment]
As am I :+1:

**Comment by Ichbinjoe** [comment]
I think an event would be very appropriate for this situation. I had a similar system awhile ago, and I think is absolutely a needed step in the right direction. :+1:

**Comment by zachbr** [comment]
Added in a7b53030d943c8205513e03c2bc888ba2568cf06
