### ISSUE TITLE
Too many mobspawning

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#150]
![12919331_573916662762365_1935692243_o](https://cloud.githubusercontent.com/assets/8324198/14061940/59603e94-f38e-11e5-94e5-4f79e41d640e.png)
Bukkit: http://pastebin.com/bJATVP17
Spigot: http://pastebin.com/Xy4wumJE
Paper: http://pastebin.com/gt6TLDe6
Timings: http://timings.aikar.co/v2/?id=0337f2b500694c64ad1e8baf5bd9278c
Plugins (49): MobEggSpawnerBlocker, PlugMan, NametagEdit, MineMarket-Universal, ChatColor, AsyncWorldEditInjector, CoreProtect, Deadbolt, SkinsModule, LimitCreative, CreativeNbtControl, ClearLag, ChatControl, Chairs, ProtocolLib, NoCheatPlus, LibsDisguises, AsyncWorldEdit, IPWhitelist, OldGoldSurvival, RedstoneClockDetector, PermissionsEx, Vault, FamoustLottery, FwdMsgChanger, MyCommand, PlayerHeads, WorldEdit, Essentials, PlotMe, Jobs, Auctions, Multiverse-Core, TreasureChest, EssentialsChat, MobArena, WorldGuard, EssentialsGeoIP, LimitedCreative, EssentialsSpawn, PvPManager, RedstoneClockPreventer, TitleManager, iZone, AreaShop, SurvivalGames, CraftBook, ChestShop, MyPet

**Comment by zachbr** [comment]
Using GH-138 as a master ticket for this issue. Please report any further details there.
