### ISSUE TITLE
Entity Turtle performence issue

### ISSUE THREAD

**Issue by Foorcee** [PaperMC/Paper#1501]
turtles are very laggy 

Timings:
https://timings.aikar.co/?id=b31b671d422244288f0fd864ed38ea5b

JProfiler Data:
http://screen.forceupdate1.de/17-43-48.png

World:
http://forceupdate1.de/paper/world.zip

**Comment by Foorcee** [comment]
@aikar

**Comment by BillyGalbreath** [comment]
~~Looks like the node processor is having trouble determining the PathType. Are these laggy turtles on land or in water?~~ Wasn't having difficulty, it was just doing it every single tick :S

**Comment by Foorcee** [comment]
in water
You can download the world
