### ISSUE TITLE
Server crash at unload world

### ISSUE THREAD

**Issue by Foorcee** [PaperMC/Paper#1505]
Stacktrace: https://paste.md-5.net/xaqenisuse.coffee

**Comment by aikar** [comment]
I noticed this shutting down my server once even. The File IO thread has a concurrency issues on whether or not any pending work remains.

**Comment by arturek1666** [comment]
I had same issue when ever a player go inside a chunk that is unloaded he can see blocks invincible and it crash the server :(. When using spigot no issue. 

This issue make me switch to spigot for some time ahh :(
