### ISSUE TITLE
Slimes spawned from spawner cannot jump

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1507]
### What behaviour is expected:
I want slimes spawned by a spawner to jump as natural as possible

### What behaviour is observed:
They do not despite the settings:
Paper: `spawner-nerfed-mobs-should-jump: true`
Spigot: `nerf-spawner-mobs: false`

### Paper build number:
Not very relevant, but it's paper 1.13.1 build 311

**Comment by zachbr** [comment]
If nerf-spawner-mobs is false, the jump setting shouldn’t have any effect

**Comment by x1p** [comment]
Ok. But, I tested both true and false on both settings and it doesn't seem to matter.
Slimes out of mob-spawners won't jump.

Does anyone know how to make them jump like normal slimes?

**Comment by zachbr** [comment]
The root issue is unrelated to nerf mobs entirely. There's a bug with our slime API that causes this when they're spawned via mobspawner.

**Comment by zachbr** [comment]
Thanks for reporting this. Fixed in builds 315+
