### ISSUE TITLE
World refuses to load when starting in graalvm

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/Paper#1511]
### What behaviour is expected:
world should load

### What behaviour is observed:
world doesn't load, timeout on
 net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.loadOrGenerateChunk(PaperAsyncChunkProvider.java:177)

### Steps/models to reproduce:
start paper in graal 

### Plugin list:
none

### Paper build number:
317

### Anything else:
works fine on spigot

paper log: https://hasteb.in/kuyicobo.java
spigot log: https://hasteb.in/oxapejes.java
os: Ubuntu 18.04 bionic [Ubuntu on Windows 10]
graal version:
```
gjava -version
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-20180625212755.graaluser.jdk8u-src-tar-g-b11)
GraalVM 1.0.0-rc6 (build 25.71-b01-internal-jvmci-0.48, mixed mode)
```

this seems to be related to async chunks, it loads fine using a random older paper build, 288

**Comment by aikar** [comment]
Graal must not support something correctly. I'm honestly not going to spend any time on this, so up to someone else to figure it out a workaround.

**Comment by MiniDigger** [comment]
as discussed in irc, I can no longer reproduce it. Ill close this and reopen with more details if it should happen again.
