### ISSUE TITLE
Running functions causes significant performance issues

### ISSUE THREAD

**Issue by GoldenDelicios** [PaperMC/Paper#1513]
###  Timings or Profile link:
https://timings.aikar.co/?id=c96962d5c4694d9fbf39aa3445a1940c

### Description of issue:
Running a datapack with functions tagged as `#minecraft:tick` (i.e. such functions run once every game tick) causes a lot of tick lag compared to vanilla. Linked is an example of a simple datapack intended to reduce lag caused by huge numbers of naturally-spawned fish, the function running is called `fishlag:loop`. It consists of only 6 commands yet takes 18 mspt to run. In vanilla the difference in performance is trivial.

### Plugin list:
No plugins

### bukkit.yml, spigot.yml, paper.yml, server.properties
All configs set to default

### Other helpful links
This is the datapack used, only 6 commands run per tick, yet it takes 18 ms/tick to run on average:
https://cdn.discordapp.com/attachments/294853547336531968/495679682138865664/fishlag.zip

### Paper build number:
git-Paper-315 (MC: 1.13.1)

**Comment by BillyGalbreath** [comment]
Unable to reproduce

![Screenshot](https://i.imgur.com/aAEWk30.png)

https://timings.aikar.co/?id=995fd92dead8435f8cb4fac8b084d915

**Comment by aikar** [comment]
Your timings report shows a 3ms average, not 18ms, thats only during a spike.

And I would blame your garbage collection flags as the source of that spike.

Please update your JVM flags to https://mcflags.emc.gs
