### ISSUE TITLE
Farmland's Light Level Does Not Update, and is Always 0.

### ISSUE THREAD

**Issue by NFRCG** [PaperMC/Paper#1516]
### What behavior is expected:
When exposed to sunlight or a block like Glowstone, Farmland's light level should update like other blocks in the game. 
### What behavior is observed:
The light level of tilled dirt (farmland) does not update when exposed to light, and stays at 0.
### Steps/models to reproduce:
GIF of Farmland lit by Glowstone: https://i.gyazo.com/f77c14b7f10725e689b49c7e61a07104.mp4
GIF of Farmland lit by Sun: https://i.gyazo.com/d8472a06bfea53361b467995751c19a8.mp4
### Plugin list:
Reproduced with no plugins on a test server.
### Paper build number:
Tested on a few different versions: 319, 317, 309, 280 and 279. I was able to reproduce the issue on all of them. 

### Anything else:
On my production server, this can cause farmland to not operate correctly (seeds not planting due to insufficient light level.). It also did not seem to matter if optimize-light-queue config option was toggled to false/true.

**Comment by aikar** [comment]
do you have the light queue option enabled in paper.yml? if so, turn it off and try.
does it happen on spigot/vanilla?

**Comment by electronicboy** [comment]
Would you try enabling spigots "random-light-updates", I seem to recall somebody having some issues with this down the line somewhere in 1.13 on spigot leading down to this setting

**Comment by NFRCG** [comment]
I was able to replicate the issue in Vanilla just now, I am not sure if this means it is intended behavior. 
I was able to replicate the issue with the latest version of Spigot with random-light-updates true and false. 
/version ouput for Spigot (Latest): This server is running CraftBukkit version git-Spigot-f6a273b-7a2f486 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT) 

I was able to reproduce with any combination of random-light-updates true/false, as well as optimize-light-queue true/false

**Comment by Black-Hole** [comment]
Farmland does not fill it's block. So if you're standing on top of it, you're actually inside the block. You should test the block above the farmland for it's light level.

**Comment by aikar** [comment]
Closing since this appears to be working as designed.
