### ISSUE TITLE
Weird "Chunk Ticks" lag

### ISSUE THREAD

**Issue by JaydenJinx** [PaperMC/Paper#1517]
https://timings.aikar.co/?id=705962eb59274e94b7021c426fbf4cf4

Server is being run from a powerful computer, stays at 20tps for a while, but eventually plummets due to "Chunk Ticks - Blocks" without any additional info as far as I can tell. I am unable to replicate this in game, it just happens.

EDIT: Apologies, forgot version info. **git-Paper-319 for 1.13.1**

**Comment by JaydenJinx** [comment]
UPDATE: I have found how to replicate it. When randomTickSpeed is set high, the server experiences extreme lag at times.

**Comment by sgdc3** [comment]
maybe because randomTickSpeed defines how often blocks are ticked? xD

**Comment by aikar** [comment]
yes, this is working as intended... 
The more you increase random tick speed, the more your server will lag.

Keep it at the default of 3 IIRC.

**Comment by JaydenJinx** [comment]
Default is 20. Will do. Just needed to grow a bunch of trees instantly while building.

**Comment by aikar** [comment]
No, the default is 3
https://minecraft.gamepedia.com/Commands/gamerule
