### ISSUE TITLE
intermittent crash

### ISSUE THREAD

**Issue by dfl2me** [PaperMC/Paper#1518]
Console	: [0 03:00:22 ERROR]: The server has stopped responding!
Console	: [0 03:00:22 ERROR]: Please report this to https://github.com/PaperMC/Paper/issues
Console	: [0 03:00:22 ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
Console	: [0 03:00:22 ERROR]: Paper version: git-Paper-292 (MC: 1.13.1)
Console	: [0 03:00:22 ERROR]: ------------------------------
Console	: [0 03:00:22 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
Console	: [0 03:00:22 ERROR]: ------------------------------
Console	: [0 03:00:22 ERROR]: Current Thread: Server thread
Console	: [0 03:00:22 ERROR]: 	PID: 18 | Suspended: false | Native: false | State: RUNNABLE
Console	: [0 03:00:22 ERROR]: 	Stack:
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.DataPaletteBlock.a(DataPaletteBlock.java:150)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.DataPaletteBlock.b(DataPaletteBlock.java:222)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:943)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveBody(ChunkRegionLoader.java:596)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.ChunkRegionLoader.access$000(ChunkRegionLoader.java:33)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.ChunkRegionLoader$1.get(ChunkRegionLoader.java:376)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.ChunkRegionLoader$1.get(ChunkRegionLoader.java:374)
Console	: [0 03:00:22 ERROR]: 		org.spigotmc.SupplierUtils.createUnivaluedSupplier(SupplierUtils.java:59)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:395)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.ChunkProviderServer.saveChunk(ChunkProviderServer.java:220)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.java:279)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.WorldServer.save(WorldServer.java:900)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.CommandSaveAll.a(SourceFile:58)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.CommandSaveAll.a(SourceFile:39)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.CommandSaveAll.b(SourceFile:22)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.CommandSaveAll$$Lambda$1266/363103401.run(Unknown Source)
Console	: [0 03:00:22 ERROR]: 		com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:132)
Console	: [0 03:00:22 ERROR]: 		com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:72)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.CommandDispatcher.a(CommandDispatcher.java:188)
Console	: [0 03:00:22 ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
Console	: [0 03:00:22 ERROR]: 		org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
Console	: [0 03:00:22 ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:726)
Console	: [0 03:00:22 ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:688)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:478)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:435)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:945)
Console	: [0 03:00:22 ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:843)
Console	: [0 03:00:22 ERROR]: 		java.lang.Thread.run(Thread.java:748)
Console	: [0 03:00:22 ERROR]: ------------------------------
Console	: [0 03:00:22 ERROR]: Entire Thread Dump:
Console	: [0 02:59:08 ERROR]: ------------------------------
Console	: [0 02:59:08 ERROR]: Current Thread: Netty Epoll Server IO #3
Console	: [0 02:59:08 ERROR]: 	PID: 34 | Suspended: false | Native: false | State: RUNNABLE
Console	: [0 02:59:08 ERROR]: 	Stack:
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.Native.epollWait0(Native Method)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.Native.epollWait(Native.java:114)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256)
Console	: [0 02:59:08 ERROR]: 		io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
Console	: [0 02:59:08 ERROR]: 		java.lang.Thread.run(Thread.java:748)
Console	: [0 02:59:08 ERROR]: ------------------------------
Console	: [0 02:59:08 ERROR]: Current Thread: Netty Epoll Server IO #2
Console	: [0 02:59:08 ERROR]: 	PID: 33 | Suspended: false | Native: false | State: RUNNABLE
Console	: [0 02:59:08 ERROR]: 	Stack:
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.Native.epollWait0(Native Method)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.Native.epollWait(Native.java:114)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256)
Console	: [0 02:59:08 ERROR]: 		io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
Console	: [0 02:59:08 ERROR]: 		java.lang.Thread.run(Thread.java:748)
Console	: [0 02:59:08 ERROR]: ------------------------------
Console	: [0 02:59:08 ERROR]: Current Thread: File IO Thread
Console	: [0 02:59:08 ERROR]: 	PID: 32 | Suspended: false | Native: false | State: RUNNABLE
Console	: [0 02:59:08 ERROR]: 	Thread is waiting on monitor(s):
Console	: [0 02:59:08 ERROR]: 		Locked on:net.minecraft.server.v1_13_R2.RegionFile.a(RegionFile.java:196)
Console	: [0 02:59:08 ERROR]: 	Stack:
Console	: [0 02:59:08 ERROR]: 		java.io.RandomAccessFile.seek0(Native Method)
Console	: [0 02:59:08 ERROR]: 		java.io.RandomAccessFile.seek(RandomAccessFile.java:557)
Console	: [0 02:59:08 ERROR]: 		net.minecraft.server.v1_13_R2.RegionFile.a(RegionFile.java:255)
Console	: [0 02:59:08 ERROR]: 		net.minecraft.server.v1_13_R2.RegionFile.a(RegionFile.java:196)
Console	: [0 02:59:08 ERROR]: 		net.minecraft.server.v1_13_R2.RegionFile$ChunkBuffer.close(RegionFile.java:303)
Console	: [0 02:59:08 ERROR]: 		java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:241)
Console	: [0 02:59:08 ERROR]: 		java.io.FilterOutputStream.close(FilterOutputStream.java:159)
Console	: [0 02:59:08 ERROR]: 		java.io.FilterOutputStream.close(FilterOutputStream.java:159)
Console	: [0 02:59:08 ERROR]: 		net.minecraft.server.v1_13_R2.RegionFileCache.write(RegionFileCache.java:128)
Console	: [0 02:59:08 ERROR]: 		net.minecraft.server.v1_13_R2.ChunkRegionLoader.processSaveQueueEntry(ChunkRegionLoader.java:441)
Console	: [0 02:59:08 ERROR]: 		net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:412)
Console	: [0 02:59:08 ERROR]: 		net.minecraft.server.v1_13_R2.FileIOThread.c(FileIOThread.java:39)
Console	: [0 02:59:08 ERROR]: 		net.minecraft.server.v1_13_R2.FileIOThread.run(FileIOThread.java:30)
Console	: [0 02:59:08 ERROR]: 		java.lang.Thread.run(Thread.java:748)
Console	: [0 02:59:08 ERROR]: ------------------------------
Console	: [0 02:59:08 ERROR]: Current Thread: Netty Epoll Server IO #1
Console	: [0 02:59:08 ERROR]: 	PID: 31 | Suspended: false | Native: false | State: RUNNABLE
Console	: [0 02:59:08 ERROR]: 	Stack:
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.Native.epollWait0(Native Method)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.Native.epollWait(Native.java:114)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256)
Console	: [0 02:59:08 ERROR]: 		io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
Console	: [0 02:59:08 ERROR]: 		java.lang.Thread.run(Thread.java:748)
Console	: [0 02:59:08 ERROR]: ------------------------------
Console	: [0 02:59:08 ERROR]: Current Thread: Craft Async Scheduler Management Thread
Console	: [0 02:59:08 ERROR]: 	PID: 30 | Suspended: false | Native: false | State: WAITING
Console	: [0 02:59:08 ERROR]: 	Stack:
Console	: [0 02:59:08 ERROR]: 		sun.misc.Unsafe.park(Native Method)
Console	: [0 02:59:08 ERROR]: 		java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
Console	: [0 02:59:08 ERROR]: 		java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
Console	: [0 02:59:08 ERROR]: 		java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
Console	: [0 02:59:08 ERROR]: 		java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
Console	: [0 02:59:08 ERROR]: 		java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
Console	: [0 02:59:08 ERROR]: 		java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Console	: [0 02:59:08 ERROR]: 		java.lang.Thread.run(Thread.java:748)
Console	: [0 02:59:08 ERROR]: ------------------------------
Console	: [0 02:59:08 ERROR]: Current Thread: Netty Epoll Server IO #0
Console	: [0 02:59:08 ERROR]: 	PID: 29 | Suspended: false | Native: false | State: RUNNABLE
Console	: [0 02:59:08 ERROR]: 	Stack:
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.Native.epollWait0(Native Method)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.Native.epollWait(Native.java:114)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239)
Console	: [0 02:59:08 ERROR]: 		io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256)
Console	: [0 02:59:08 ERROR]: 		io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
Console	: [0 02:59:08 ERROR]: 		java.lang.Thread.run(Thread.java:748)
Console	: [0 02:59:08 ERROR]: ------------------------------
Console	: [0 02:59:08 ERROR]: Current Thread: ObjectCleanerThread
Console	: [0 02:59:08 ERROR]: 	PID: 28 | Suspended: false | Native: false | State: TIMED_WAITING
Console	: [0 02:59:08 ERROR]: 	Stack:
Console	: [0 02:59:08 ERROR]: 		java.lang.Object.wait(Native Method)
Console	: [0 02:59:08 ERROR]: 		java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
Console	: [0 02:59:08 ERROR]: 		io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54)
Console	: [0 02:59:08 ERROR]: 		io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Console	: [0 02:59:08 ERROR]: 		java.lang.Thread.run(Thread.java:748)
Console	: [0 02:59:08 ERROR]: ------------------------------
Console	: [0 02:59:08 ERROR]: Current Thread: Timer-0
Console	: [0 02:59:08 ERROR]: 	PID: 27 | Suspended: false | Native: false | State: TIMED_WAITING
Console	: [0 02:59:08 ERROR]: 	Stack:
Console	: [0 02:59:08 ERROR]: 		java.lang.Object.wait(Native Method)
Console	: [0 02:59:08 ERROR]: 		java.util.TimerThread.mainLoop(Timer.java:552)
Console	: [0 02:59:08 ERROR]: 		java.util.TimerThread.run(Timer.java:505)
Console	: [0 02:59:08 ERROR]: ------------------------------
Console	: [0 02:59:08 ERROR]: Current Thread: Paper Watchdog Thread
Console	: [0 02:59:08 ERROR]: 	PID: 26 | Suspended: false | Native: false | State: RUNNABLE
Console	: [0 02:59:08 ERROR]: 	Stack:
Console	: [0 02:59:08 ERROR]: 		sun.management.ThreadImpl.dumpThreads0(Native Method)
Console	: [0 02:59:08 ERROR]: 		sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
Console	: [0 02:59:08 ERROR]: 		org.spigotmc.WatchdogThread.run(WatchdogThread.java:113)
Console	: [0 02:59:08 ERROR]: ------------------------------
Console	: [0 02:59:08 ERROR]: Current Thread: Server console handler
Console	: [0 02:59:08 ERROR]: 	PID: 21 | Suspended: false | Native: true | State: RUNNABLE
Console	: [0 02:59:08 ERROR]: 	Thread is waiting on monitor(s):
Console	: [0 02:59:08 ERROR]: 		Locked on:java.io.BufferedInputStream.read(BufferedInputStream.java:345)
Console	: [0 02:59:08 ERROR]: 		Locked on:sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
Console	: [0 02:59:08 ERROR]: 		Locked on:java.io.BufferedReader.readLine(BufferedReader.java:324)
Console	: [0 02:59:08 ERROR]: 	Stack:
Notice	: Minecraft server has stopped running.

**Comment by aikar** [comment]
Can you get all the logs that was above this ? the ones that was printing every 5s...

**Comment by aikar** [comment]
Oh I just noticed the save-all. Did you use /save-all true? if so, that will crash your server potentially. Don't use that command.

**Comment by dfl2me** [comment]
okay i will make that change

**Comment by dfl2me** [comment]
It's the Save The World State job in McMyAdmin. I've disabled that job.

**Comment by dfl2me** [comment]
Still getting the occasional error.
[error.log](https://github.com/PaperMC/Paper/files/2454629/error.log)

**Comment by aikar** [comment]
This was an old build that isn't supported and save-all will cause these issues.
