### ISSUE TITLE
Dynamic viewdistance per player based on their recent chunkload history

### ISSUE THREAD

**Issue by Decme** [PaperMC/Paper#1519]
Although I'm sure every server admin would like to run with 15 viewdistance, this is almost never practical on multiplayer due to severe TPS drops, particularly when players are exploring with elytra.

It would be good for players who remain mostly stationary to have higher viewdistances because they're generally causing less impact on server load, and dynamically drop viewdistance for a limited period of time for players who are excessively loading chunks (example flying over an unexplored ocean or in the end islands)

Should this be implemented, multiple configuration controls would be much appreciated, example: Maximum viewdistance, minimum viewdistance, rate at which the drop kicks in, amount of time to wait until slowly restoring viewdistance back to normal after a player stops moving, etc.

I've considered dropping the global viewdistance and just putting up with it, but this isn't a real solution as many players enjoy having high viewdistance.

Other considerations: if possible a feature control to detect when players are flying in a single direction for a long period of time, and focus more on chunkloading in front of them than say, 90 degrees to the sides.

**Comment by electronicboy** [comment]
Shamefully, this request falls over into the area in which a plugin would provide a better solution, given that we couldn't address all needs/wants from such a system implemented in the server

Creating a plugin to do what you want would be a reasonable job for any plugin developer with the paper API as everything you'd need for it is already exposed in the API, just needs the logic strapping together

(#1447)

**Comment by Decme** [comment]
Hey electronicboy, sorry I'm new to the Paper ecosystem, do you know the best place to request such a plugin?

**Comment by hafarooki** [comment]
I'd suggest the ~~awesome Paper Discourse forum that exists~~ friendly Paper [Discord server](https://paperdiscord.emc.gs) (BillyGalbreath likes to make plugins like that)

**Comment by Decme** [comment]
Just leaving this here in case someone lands on this page from a random Google search:
https://github.com/Lxct/BestViewDistance
