### ISSUE TITLE
Team deleted after restart

### ISSUE THREAD

**Issue by splintermik** [PaperMC/Paper#1524]
Hello I just found a bug, if I create a team ( /team add red ) at the server restart, the team has disappeared

paper : Paper version git-Paper-324 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

plugin : 0

thanks :)

**Comment by electronicboy** [comment]
paper.yml has a configuration option to allow saving empty teams which is disabled by default as there is generally no sane reason to do so, but is there if you need it
