### ISSUE TITLE
Build 324 breaks chestshop functionality

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1525]
### What behaviour is expected:
Players buy from a chestshop by clicking on the sign (with right arm) and are able to buy stuff in game.

### What behaviour is observed:
Build 324 (2-oct-2018 15:21:26) breaks this. When a player want to buy from a chestshop sign, it says: "player not found"

### Steps/models to reproduce:
Build 323 works normally, from build 324 and higher, buying from signs is not working anymore.

### Plugin list:
AreaShop*, ChestShop, CMI, CMIEInjector*, FeatherBoard*, Multiverse-Core*, MVdWPlaceholderAPI*, NoPlugins*, PermissionsEx*, PlugMan*, ProtocolLib*, TAB, Vault*, WorldEdit, WorldGuard

### Paper build number:
 git-Paper-324 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
And higher

### Anything else:
There is a similar issue here: https://github.com/ChestShop-authors/ChestShop-3/issues/150 but this is still unresolved.

**Comment by tsiedsma** [comment]
Also experiencing this issue.

**Comment by WindUnwaken** [comment]
This issue also happened on PetBlock and many plugins with gui, it breaks gui function.
I recommend use Build 323, everything is good.

**Comment by zachbr** [comment]
This should be fixed in builds 330+

**Comment by jakkuh** [comment]
This same issue exists in Papers latest build for 1.12.2, is it possible to back port the fix?

@zachbr

**Comment by zachbr** [comment]
The change that broke this was never added to 1.12.2. Your issue is unrelated to this ticket. Open a new one.
