### ISSUE TITLE
Item Thrower and Owner API.

### ISSUE THREAD

**Issue by Parozzz** [PaperMC/Paper#1526]
Something that would be useful, and never being implemented (Not sure why though), is an API for Item to getting/setting the Thrower and the Owner of an Item. 
When the Thrower is almost useless but good for completition, Owner is used by vanilla to avoid other players to pick up your item, and since it is already done I don't see why I should do it with events.

What I am asking here is a getter and a setter for both UUID (Owner and Thrower) saved inside the EntityItem class. I would do it by myself, but I haven't got much time, unfortunately.

**Comment by aikar** [comment]
I wasn't even aware that mojang stored this data, that's pretty cool.

**Comment by aikar** [comment]
Curious though, what even decides owner?
The only way I see that value differing is if the itemstack records the first player to pick an item up so if its rethrown, it stays owned by the same player.
but that would break stacking.

**Comment by Tofuus** [comment]
I'm fairly certain owner isn't ever set. It's just optional NBT data you can set that'll prevent anyone except the owner from picking it up. Probably added in for map makers?

**Comment by Parozzz** [comment]
In fact, Owner is a map makers tool that was added my Mojang but never used in-game. Even more, it does not seem to be used in the EntityItem merge method. Maybe adding an Owner check there should be good enough? (I do think thrower is used in some advancements, nothing more. But still, maybe something worth exposing?)
