### ISSUE TITLE
random console spam

### ISSUE THREAD

**Issue by vaniron** [PaperMC/Paper#1527]
###  Timings or Profile link:
https://timings.aikar.co/?id=d9b80d810b5b4a76becf39c648dc1460

### Description of issue:
Console spam which randomly starts and ends. No idea why.

### Plugin list:
ActionHealth*, AdvancedPortals, BuycraftX*, ChestCommands*, Citizens, CitizensCMD, Confiscate, CoreProtect, CrazyAuctions, EpicRename, Essentials*, EssentialsAntiBuild*, EssentialsChat*, EssentialsSpawn*, FastAsyncWorldEdit*, GuiCreationTool*, HolographicDisplays, LuckPerms*, LWC, MessageAnnouncer*, MobArena, MobFarmManager, MobHeads, Multiverse-Core*, NoSpawnerChange, Parties, PlayerPoints*, PluginHiderPlus*, ProtocolLib*, Quests*, ShopChest, SilkSpawners, SkinsRestorer, TAB, TimeIsMoney*, TradeSystem, Vault*, VoidGenerator, WorldBorder*, WorldEdit, WorldGuard, WorldSystem

### Other helpful links
Error log: https://pastebin.com/raw/Z6cn1sua

### Paper build number:
1.13.1 324

**Comment by aikar** [comment]
please update to 332 and paste the new error if it occurs again
there was a bug that the error printed was useless. I made it print the real error now.

**Comment by vaniron** [comment]
Got new error for you, resulting in TPS loss.
https://pastebin.com/raw/Mk9rvibj

**Comment by aikar** [comment]
You have permission errors on your region files. run the following command to fix it:

find your username if you don't know it: `whoami`

then run:
`sudo chmod -R yourusername .`

**Comment by aikar** [comment]
Feel free to join our Discord if you need more assistance.
