### ISSUE TITLE
Timings/Region reports abnormal amounts of chests

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1528]
###  Timings or Profile link:
https://timings.aikar.co/?id=8bf4627336a94a3dacf1a079ca41f4dd#regions

### Description of issue:
Timings report shows:
```
-7680,-3072 (Area Seen 3 times)
Totals: 57 Entities - 3001 — Tile Entities - Summary:
BEACON: 1
CREEPER: 1
BAT: 1
PHANTOM: 1
SKELETON: 2
ZOMBIE: 3
CHICKEN: 12
PIG: 16
SHEEP: 21
CHEST: 3000
```
In the region, there can't be found anything but wilderness. It's in the middle of an ocean. No players have build here.

### Plugin list:
AreaShop*, BottledExp, BuycraftX*, ChatControl, ChestShop, ClearLag*, CMI, CMIEInjector*, CustomTime*, dynmap*, EntityControl*, EpicHeads, FeatherBoard*, GriefPrevention, iDisguise, Images*, LogBlock, Multiverse-Core*, MVdWPlaceholderAPI*, NightVision*, NoPlugins*, OnlyProxyJoin*, PermissionsEx*, PlugMan*, ProtocolLib*, Spartan, SuperpickaxeReloaded, TAB, TimeIsMoney*, TradePlus, UnbreakingAnvils*, Vault*, Votifier, VotingPlugin, WorldBorder*, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
Bukkit.yml https://hastebin.com/iyitofugez.coffeescript
Spigot.yml https://hastebin.com/hezonebocu.coffeescript
Paper.yml https://hastebin.com/elinifakil.coffeescript

### Other helpful links
These high numbers exist for a while. It seems to me, they keep getting bigger. It's probably something in the world. But I can't find out what. Had a few crashed in the past. Wolrd is build 1.13 native.

### Paper build number:
Paper version git-Paper-323 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by aikar** [comment]
A region is a 512x512 area. You're going to need to look farther in every direction.

Also that does not mean 3000 chests, it's more so closer to 1000 chest, as the area was seen 3 times. find what player is online near that area and teleport to them.
If you need any further assistance, feel free to jump on discord or irc with us.
