### ISSUE TITLE
Server deadlocks when loading chunks in onDisable

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#1532]
### What behaviour is expected:
The server should not deadlock but load the chunk

### What behaviour is observed:
The server deadlocks

### Steps/models to reproduce:
Load a chunk in onDisable

### Paper build number:
This happens since the async chunk loading update, build 301 did not have this problem.

**Comment by electronicboy** [comment]
Could you please provide a jstack if possible?

**Comment by aikar** [comment]
I don't really need it. I was considering this might be a possibility.


It's because I stopped the executors. I just need to leave them running, but cancel all pending async tasks instead.

**Comment by Brokkonaut** [comment]
https://pastebin.com/raw/qpcLS83k
