### ISSUE TITLE
NameTags still visible when entity rides a player

### ISSUE THREAD

**Issue by Drc-DEV** [PaperMC/Paper#1536]
### What behaviour is expected:
When an entity rides a player the nametag should be no longer visible

### What behaviour is observed:
Using Build 1573 the nametag can be seen even with an entity mounted on the player

### Steps/models to reproduce:
Spawn a pig, make the pig mount the player, the nametag of the player is still there

### Plugin list:
This bug is related to Paper, as with Spigot I can't see the nametag

### Paper build number:
Build 1573, but I noticed the bug when I upgraded from 1567, which worked fine, I suspect the bug has been introduced with 1569 ("Fix issues with entity loss due to unloaded chunks")

### Anything else:
Please fix this, as all my minigames rely on this feature.

**Comment by aikar** [comment]
No recent changes would have related to that.

I'm not aware of any behavior that should make the name tag disappear in this scenario to begin with. I believe that something else may have changed in your environment

**Comment by Drc-DEV** [comment]
I'll try with no plugins at all and different builds and I will update this ticket.

**Comment by Drc-DEV** [comment]
The error was caused by some plugin using packets that went crazy, sorry.
