### ISSUE TITLE
Separate method for entity position broadcast in EntityTrackerEntry

### ISSUE THREAD

**Issue by Gerrygames** [PaperMC/Paper#1537]
I am overwriting the EntityTrackerEntry#broadcast method in order to catch the broadcasted packets and save them to a MCPR file. [This patch](https://github.com/PaperMC/Paper/blob/9fe29f979c40ecdce72d9fdb661d8e211a952600/Spigot-Server-Patches/0037-Send-absolute-position-the-first-time-an-entity-is-s.patch#L51-L63) unfortunately breaks the recording of relative entity move packets. This could be fixed by creating a separate method like [this](https://gist.github.com/Gerrygames/b6aa709abdcb37f597d1195bcbad0796).
I would create a PR, but for some reason I keep getting an error when trying to run ./paper patch.

**Comment by mikroskeem** [comment]
Speak about the `./paper patch` error.

**Comment by Gerrygames** [comment]
I did clone the repository and ran ./paper patch. I did not modify any files whatsoever.
https://gist.github.com/Gerrygames/88c616f2093f65b89a63699f28f8305e

**Comment by aikar** [comment]
I don't understand how this breaks anything, nor how your method is any different? how does using a method help?

**Comment by Gerrygames** [comment]
This is how my extended EntityTrackerEntry looks like:
https://gist.github.com/Gerrygames/0b3bf4dfb5f6535ddd392acf118a6901
This patch breaks my plugin, because the broadcast method is no longer called for relative entity move packets.

The behavior will be exactly the same. A separate method would just make it easier for me to overwrite the method.
