### ISSUE TITLE
Light/shadow issues

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#1539]
### What behaviour is expected:
When shadow is created, don't see black spots or areas.

### What behaviour is observed:
Using latest version of Paper, when for example player grows a big tree, it projects strange dark shadows. Using latest version of Spigot i can't reproduce the issue.

### Steps/models to reproduce:
Grow a big tree and see shadows on floor or tall grass.

### Plugin list:
None, fresh.

### Paper build number:
Peperclip-335.

### Anything else:
Video using Paper:
https://www.youtube.com/watch?v=dV120kXcmUs

Video using latest Spigot:
https://www.youtube.com/watch?v=Y_N0-UFkPfY

**Comment by zachbr** [comment]
Attach a timings URL or your configurations please.

**Comment by lordrius** [comment]
spigot.yml
https://pastebin.com/6deGhXzk
paper.yml
https://pastebin.com/hb0LSZRb

**Comment by aikar** [comment]
fixed in 341+.
I was able to reproduce the issue as shown at least in a few manners, and its fixed when I reverted the recheck gaps changes. back ported to 1.12 in build 1574.
