### ISSUE TITLE
ChunkLoad issues & Timings issues

### ISSUE THREAD

**Issue by TomLewis** [PaperMC/Paper#154]
### Version:

Even though I built this yesterday, its saying im 121 versions behind.
2016-03-27 11:27:38 | This server is running Paper version git-Paper-459 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
Checking version, please wait...  
You are 121 version(s) behind
### Description of issue:

ChunkLoad issues and Timings errors
http://pastebin.com/prsTt4nQ

**Comment by ghost** [comment]
Can't confirm your problem with the version number. Delete your cache folder and try it again with the newest build from here: https://ci.destroystokyo.com/job/PaperSpigot/

**Comment by TomLewis** [comment]
Any idea what is triggering it? So i can duplicate

**Comment by zachbr** [comment]
I don't know where you got that jar, but we made that version on Mar 7, 2016 2:21:55 AM. So it is certainly very out of date. Please re-test against the newest build (581 at the time of this reply) and let us know if it continues. If it does, please attach the new errors and logs. 
Thanks.

**Comment by aikar** [comment]
I am 100% confident this is a plugin due to a bug in BanManager.

It's using some permission registration to identify who to send a message to, and an unloaded block is registered, which then triggers a very dangerous async chunk load.

they need to fix that.

**Comment by TomLewis** [comment]
@Zbob750 I downloaded it from here [not-an-official-or-updated-website] where it says "PaperSpigot-latest.jar" via the mirror URL. The paperspigot team need to buy paperspigot.com and put everything in one place.

@aikar Thanks for the input, I will pass this message on.

**Comment by zachbr** [comment]
Official downloads haven't moved since they were offered. You chose to get it from a third-party who was not up-to-date. That's all there is to it.
