### ISSUE TITLE
Failed to check session lock

### ISSUE THREAD

**Issue by vaniron** [PaperMC/Paper#1540]
### What behaviour is expected:
Stopping the server without errors.

### What behaviour is observed:
Error "Failed to check session lock for world located at ./ID801-cd89bcc1-a7d9-3a1e-adf1-61953a76177f, aborting. Stop the server and delete the session.lock in this world to prevent further issues."

### Steps/models to reproduce:
/stop

### Plugin list:
ActionHealth*, AdvancedPortals, BuycraftX*, ChestCommands*, Citizens, CitizensCMD, Confiscate, CoreProtect, CrazyAuctions, EpicRename, Essentials*, EssentialsAntiBuild*, EssentialsChat*, EssentialsSpawn*, FastAsyncWorldEdit*, GuiCreationTool*, HolographicDisplays, LuckPerms*, LWC, MessageAnnouncer*, MobArena, MobFarmManager, MobHeads, Multiverse-Core*, NoSpawnerChange, Parties, PlayerPoints*, PluginHiderPlus*, ProtocolLib*, Quests*, ShopChest, SilkSpawners, SkinsRestorer, TAB, TimeIsMoney*, TradeSystem, Vault*, VoidGenerator, WorldBorder*, WorldEdit, WorldGuard, WorldSystem

### Paper build number:
341

### Anything else:
Got WorldSystem plugin generating worlds per player, this error appers on server stop sometimes, I am not sure if its plugin or server problem, just reporting to be sure.

**Comment by electronicboy** [comment]
Something is editing the files on the disk improperly on the loaded world, thus triggering the session check error
