### ISSUE TITLE
Light bug - random dark patches

### ISSUE THREAD

**Issue by Darunox** [PaperMC/Paper#1549]
### What behaviour is expected:
transfert map 1.12.2 to 1.13.1

Hello,
we found that the problem appears in a particular case.

1st image the quartz blocks are in this position in 1.12.2.
http://zupimages.net/viewer.php?id=18/41/m9gd.png

After the conversion in 1.13.1 of this chunk we move the blocks in column like this. No problem...
http://zupimages.net/viewer.php?id=18/41/bkea.png

After a disconnection and reconnection the beug appears.
http://zupimages.net/viewer.php?id=18/41/4yau.png

The problem is independent of optifine.

After creation of one cube with /fill wall by wall.
https://imgur.com/a/GVd9Zxf

Plugins :
CoreProtect, Essentials*, EssentialsChat*, EssentialsSpawn*, GriefPrevention, Multiverse-Core*, Multiverse-Portals*, PermissionsEx*, SysInfoPlugin*, Vault*, WorldEdit, WorldGuard, XRayHunter

Last update Paper build number: 349

In complement with this issue : https://github.com/PaperMC/Paper/issues/1542

Thank you in advance for your answer.

**Comment by aikar** [comment]
Can you please supply the region file in question that is exhibiting this

**Comment by aikar** [comment]
Actually why did you open a new issue on this, please use the original one you commented on.
