### ISSUE TITLE
crashes with build 350

### ISSUE THREAD

**Issue by dfl2me** [PaperMC/Paper#1550]
getting a issue in build 350
[new-error-build-350.log](https://github.com/PaperMC/Paper/files/2454645/new-error-build-350.log)

**Comment by electronicboy** [comment]
Could do with the full server log, that way we can see the full picture of what is blocking there

**Comment by dfl2me** [comment]
am attaching the server logs. if there's another location i should look, please let me know.
[2018-10-07-3.log](https://github.com/PaperMC/Paper/files/2454675/2018-10-07-3.log)
[2018-10-07-4.log](https://github.com/PaperMC/Paper/files/2454676/2018-10-07-4.log)

**Comment by dfl2me** [comment]
The server is running via McMyAdmin on a VMWare ESXi 6.0 Ubuntu Linux VM.
Additional Specs:
10GB RAM allocated to MC (12GB assigned to VM)
2 vCPU
128GB SSD

Using the following startup flags:

-Xms10G -Xmx10G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs

**Comment by aikar** [comment]
I can see room for improvement here. Will fix soon as I can

**Comment by aikar** [comment]
Build 351+ should solve this
