### ISSUE TITLE
Option to block moving into unloaded chunk

### ISSUE THREAD

**Issue by aikar** [PaperMC/Paper#1551]
As an way to ensure TPS is never hit by main blocking chunk loads, add an option to the Async Chunks feature that rejects movements if it would put them into an unloaded chunk.

By doing this, we can just make clients get the snapback appearance if they are moving faster than the server can load or generate chunks, which adding main blocking requests to the mix can just make the issue worse.

This would need to be default off, but can be a nice option who rather rubber band players than add more TPS loss.

**Comment by hurrgurl** [comment]
Where is the option in paper yml?

Can't find it. 

git-Paper-386

**Comment by ghost** [comment]
Would this be possible to backport to 1.12.2?

**Comment by MiniDigger** [comment]
@hurrgurl you should find a setting named prevent-moving-into-unloaded-chunks in the settings section of the paper.yml.

**Comment by hurrgurl** [comment]
Yeah that's what I've been looking for, it is non existent for me in paper yml

Using git-Paper-387

I tried regenerating paper yml, still no "prevent-moving-into-unloaded-chunks" in settings of paper.

**Comment by aikar** [comment]
I'll fix when I get home tonight, I see the problem.

**Comment by sgdc3** [comment]
uhm did i miss something?

**Comment by aikar** [comment]
@sgdc3 config methods have to be private, not public

**Comment by electronicboy** [comment]
should probably be per world too
