### ISSUE TITLE
MobSwpaning not balanced ?

### ISSUE THREAD

**Issue by Righx** [PaperMC/Paper#1553]
### What behaviour is observed:
___Mobspawning not balanced, we have make mobtower, when i'm alone on the server, no problem, spawning rate is perfetc (lot of mob). BUT, when we are more players on the server, nothing mob in the tower.
If all players are in the tower, no problem (lot of mobs ...___

### Plugin list:
___Dynmap - Luckperms - Mywarp___

### Paper build number:
___352, but we have this problem since several versions.___

### Anything else:
___Original mobcap is 70 (bukkit.yml), we have try with 120, same problem.___

**Comment by aikar** [comment]
This is a vanilla bug. We are aiming to fix it with https://github.com/PaperMC/Paper/pull/1334 though. Not sure when it will be pulled yet, but follow that PR.
