### ISSUE TITLE
Lose tps , Help me please [ It's important for me.]

### ISSUE THREAD

**Issue by nuangtr** [PaperMC/Paper#1554]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out https://timings.aikar.co/?id=9d7b54ad64024ef1a2e1bc84e590271f#timings

### Description of issue:
Help me please
I tried removing multiple plugins, but Lose tps 
player online 13-20 > Lose tps 
I lost the Tps for a while.

### Plugin list:
Plugins (49): AgarthaLib, BlockRegen, ChatControl, ChatItem, Citizens, ClearLag, CrackShot, CrackShotPlus, CrateReloaded, EasyHat, Essentials, EssentialsAntiBuild, EssentialsProtect, EssentialsSpawn, FarmLimiter, FarmProtect, FeatherBoard, FrameProtect, GangsPlus, GUIPlus, HeadDatabase, HolographicDisplays, KarenProtect, LibsDisguises, LockettePro, Marriage, MultiWorld, MVdWPlaceholderAPI, MyItems, MyPet, MythicMobs, NametagEdit, NoFlyZone, NoPlugins, PermissionsEx, PhatLoots, PlaceholderAPI, PlayerShopGUIPlus, PlayerSkillsReborn, ProtocolLib, ProtocolSupport, ResourcePackDownloader, SafeTrade, ServerSigns, ShopGUIPlus, Shopkeepers, Vault, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://gist.github.com/nuangtr/e5155b5c3fce24754a05647ea411c87d

### Paper build number:
git-paper-1562

**Comment by nuangtr** [comment]
system
memory 40 gb
cpu xeon (R) cpu e5-2660 0@ 2.20 Ghz x 12
Centos linux 7

**Comment by electronicboy** [comment]
`timingcost: 301`
that, along with everything else, really heavily suggests that your hardware is just not up to the job that you're wanting from it, configuring stuff like `max-player-auto-save-per-tick` might help you get more out of what you've got, view distance should also not be equal to mob spawn range, it needs to be higher to avoid chunk loading from entities, that will avoid the odd performance hit here and there due to mobs causing chunk loads

**Comment by nuangtr** [comment]
Thank you for help <3
--
Do you think I should upgrade my hardware?

**Comment by aikar** [comment]
Yes hardware upgrade looks to be your best bet. timings cost 301 shows the CPU is not fast, this should be in the 100's ideally (or lower)

Player Saving does File IO on main, so if you are not using SSD's, that also will hurt a lot, which your player saving is really high.

adjusting max player auto save per tick may help reduce the impact until you can upgrade hardware though.
