### ISSUE TITLE
issues w/ #352. not connecting. server eventually crashes. log attached.

### ISSUE THREAD

**Issue by dfl2me** [PaperMC/Paper#1555]
Paper build 352
Issue is players not able to connect.
Only one plugin enabled:
BukkitCompat R22A - PhonicUK
Description:
McMyAdmin Compatibility Plugin

Server eventually crashes.

Log is attached. If you need more info, I am happy to provide.
[latest.log](https://github.com/PaperMC/Paper/files/2456047/latest.log)

**Comment by aikar** [comment]
From what I can see, you simply had lots of chunks queued and it couldn't provide the chunk fast enough. not sure why that wouldn't of jumped into high priority mode though, or if it did, you must of had a ton of high priority tasks.

Only thing I can recommend is try again?

What is your view distance?
Can you provide a timings so we can see all of the config.

**Comment by dfl2me** [comment]
View distance is 10.
I tried the timings, but that's when the server crashed.

I will try again without plugins.

**Comment by electronicboy** [comment]
Run the timings command from the console, we only need the timings in order to get some important information about your server;

**Comment by dfl2me** [comment]
https://timings.aikar.co/?id=b29344186be24dd8bf16fd2190171bc4

**Comment by dfl2me** [comment]
i think i fixed it. i saw that in my the_end region, there were 20,000 entities loading. these were snow golems and snowballs. i logged into the server and killed those entities. my guess is someone put them there to fight endermen. not necessary. new timings report attached:

https://timings.aikar.co/?id=ea6333c7086540b9b37bfe7471178268
