### ISSUE TITLE
random disconnects with build #355

### ISSUE THREAD

**Issue by dfl2me** [PaperMC/Paper#1558]
version of paper:
git-Paper-355 (MC: 1.13.1)

plugins:
ClearLag 2.9.7 - bob7l
BukkitCompat R22A - PhonicUK

Experiencing random timeouts while exploring. Server eventually crashes. I tried getting a timings report after the crash, but it didn't show anything:

https://timings.aikar.co/?id=9ca8fe599cfc421aa071f57de7b2a1db

Running timings again and will update w/ any new information.

Server log attached.
[McMyAdmin-20181010-083909.log](https://github.com/PaperMC/Paper/files/2466206/McMyAdmin-20181010-083909.log)

**Comment by dfl2me** [comment]
https://timings.aikar.co/?id=8763b93f086049dfa3019c839247edc1

**Comment by aikar** [comment]
Please try latest. I made some improvements that might of related here, but not 100% sure.

**Comment by dfl2me** [comment]
i haven't seen any random disconnects in ~11 hours. additionally, i disabled the BukkitCompat plugin to see if that would make any difference. i will re-enable it again tomorrow and if i see issues, i'll conclude that the plugin is to blame at this point.

**Comment by dfl2me** [comment]
i forgot to mention in the above comment that i am using build #360 (latest)

**Comment by electronicboy** [comment]
Closing in part due to inactivity, but also due to #1627 being merged which should also help, if you have any further issues, feel free to bump this ticket/speak to us on IRC/Discord
