### ISSUE TITLE
Players are bugging through blocks after teleport

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#156]
### Issue Reference: https://github.com/PaperMC/Paper/issues/147

Problem still isn't fixed with the newst build 580. I added the following comment to the original issue:

Commit doesn't fix the bug. I don't think that this is the problem of the chunk loading because it's also happening with /tpa requests where one players already loaded all chunks (you only have to make sure that the second player - who teleports to the first one - doesn't have loaded the chunks where the first one is).

**Comment by kashike** [comment]
Retry with build 581, which is now the latest?

**Comment by ghost** [comment]
Doesn't work with build 581 either.

**Comment by kashike** [comment]
In that case, please comment on #147, I've reopened it.
