### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Nevercold** [PaperMC/Paper#1561]
### Link/paste of stack trace
Log: https://hastebin.com/ewibehunud.md
Error: https://hastebin.com/ebemedebof.pl
Crashreport: https://hastebin.com/dalufemewe.pl

### Plugin list:
none

### Actions to reproduce (if known):
I have uploaded a map (which works in the singelplayer and with the normal spigot too) And when I join Joine the error and the server crashes.

### Paper build number:
git-Paper-360 (MC: 1.13.1)

**Comment by MiniDigger** [comment]
Could you upload the map (or the spawn area) here so that the team can reproduce the issue?

**Comment by Nevercold** [comment]
Can I send this via private message? Does not want everyone has the map.

**Comment by aikar** [comment]
your links are dead

**Comment by Nevercold** [comment]
so, new:
Log: https://hasteb.in/ifegixoh.md
Crashreport: https://hasteb.in/kuturoni.rb
I send you the map just about Discord Private Message. My Discord name is Niekold#9410

**Comment by Nevercold** [comment]
new error: https://gist.github.com/Nevercold/211b09442ef47fd6921f69cc9d72f98c

**Comment by aikar** [comment]
try build 375+ I put in something that should prevent this from occurring and logs if something undesirable happens.
