### ISSUE TITLE
Monsters can't spawn :/

### ISSUE THREAD

**Issue by Aurelien30000** [PaperMC/Paper#1567]
Hello !
First of all I wish to apologize for my fragile English ^^. (If you need more details, don't hesitate)
### What behaviour is expected:
The monsters should spawn naturally on the map.

### What behaviour is observed:
Hostile mobs do not appear except if you force them to with /summon command and spawn eggs.

### Steps/models to reproduce:
Not to be in difficulty peaceful and be night or day in the caves

### Plugin list:
No plugin. vanilla (paper) server.

### Paper build number:
https://papermc.io/ci/job/Paper/lastSuccessfulBuild/artifact/paperclip-1580.jar (1.12.2 last build)

### Anything else:
Nothing

Thank you in advance

**Comment by aikar** [comment]
yep known issue, will be fixed sometime today

**Comment by aikar** [comment]
Fixed in 1581+
