### ISSUE TITLE
Update migration to 1.13.1 ?

### ISSUE THREAD

**Issue by mtoensing** [PaperMC/Paper#1570]
Hi, 

I am currently running my Paper Server with 1.12.2 on my Raspberry Pi with this script: https://github.com/mtoensing/RaspberryPiMinecraft

Every time I reboot this server I get the lastest version from destroystokyo.com:
wget -q https://ci.destroystokyo.com/job/PaperSpigot/lastSuccessfulBuild/artifact/paperclip.jar -O /home/pi/minecraft/paperclip.jar

The server is still on 1.12.2 so I assume this is the current stable release. Or isn't it? I see many issues with requests regarding problem with 1.13.1. It there a planned upgrade path? How do we securely update? Are you planning a migration?

**Comment by electronicboy** [comment]
1.13 builds are under their own project on the ci server, https://papermc.io/ci/job/Paper-1.13/ 1.13.1 builds are there, I believe that the intent is now that we'll be using a separate job on the Jenkins for every version, that way build numbers are more useful to us, and it makes dealing with changes in older versions during its small area of support after a new release easier
