### ISSUE TITLE
Signs created on MacOS in map from 1.12.2 show encoding problems in 1.13.1 like this: □□

### ISSUE THREAD

**Issue by mtoensing** [PaperMC/Paper#1571]
### What behaviour is expected:
No unrecognised characters or encoding fragments on signs from 1.12.2. maps in 1.13.1 

### What behaviour is observed:
New lines start with a □ character. 

### Steps/models to reproduce:
Use map from PaperMinecraft 1.12.2 in PaperMinecraft 1.13.1. 

### Plugin list:
No plugins installed.

### Paper build number:
This server is running Paper version git-Paper-366 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
[20:39:27 INFO]: Previous version: git-Paper-1581 (MC: 1.12.2)
[20:39:27 INFO]: Checking version, please wait...
[20:39:28 INFO]: You are running the latest version

### Anything else:
Signs where all written on a Mac if that helps but I don't think so 
<img width="966" alt="screen shot 2018-10-13 at 20 34 09" src="https://user-images.githubusercontent.com/136737/46908780-2dde8780-cf28-11e8-91de-526e44fee90f.png">
<img width="966" alt="screen shot 2018-10-13 at 20 41 41" src="https://user-images.githubusercontent.com/136737/46908789-69795180-cf28-11e8-91cc-52842fa1e05b.png">
<img width="966" alt="screen shot 2018-10-13 at 20 42 06" src="https://user-images.githubusercontent.com/136737/46908795-76964080-cf28-11e8-954d-7d525145a2bf.png">

**Comment by mtoensing** [comment]
I looked at many more signs on our map. It appears to me that the signs written on a windows pc don't show the squares while all signs written on users with a mac have this "square" problem. 

This sign was created on a windows pc and its perfectly normal.
<img width="1552" alt="screen shot 2018-10-13 at 20 46 18" src="https://user-images.githubusercontent.com/136737/46908861-66329580-cf29-11e8-9bbc-9337bc8323dc.png">

**Comment by BillyGalbreath** [comment]
Did those signs originally use color codes (non black) in them?

**Comment by mtoensing** [comment]
No. No color codes. How do I even do that?

**Comment by electronicboy** [comment]
I've not seen anything like that on my own maps, but that would kinda suggest some form of character being in there that shouldn't have been

**Comment by mtoensing** [comment]
After some more research we can verify that this only applies to signs created on a mac

**Comment by BillyGalbreath** [comment]
Looks like a vanilla bug. They dismissed it as not reproducible. Might want to jump in on that action with your information and reproduction steps.

https://bugs.mojang.com/browse/MC-135733

**Comment by mtoensing** [comment]
That one seems different. It has something to do with a special character (apple logo) and not a generell encoding problem caused by a mac.

**Comment by zachbr** [comment]
Could you send us a chunk or region prior to the conversion (from a 1.12 backup) so that we can try and see what character that is and reproduce it?

**Comment by mtoensing** [comment]
Tank you @zachbr 
Here is a backup of the map in 1.12.1 I made right before I started it the first time with 1.13.2 https://www.dropbox.com/sh/t9uylu7lqyfpjdp/AACiecO1XkVOeWcOZv_Rd1Wqa?dl=0

**Comment by zachbr** [comment]
@mtoensing sorry for the delay, can you send me in-game coordinates of where one of these signs might be? I've got a bunch of listeners on chunk loads looking for signs but even then there's a ton of regions here and I'm pretty much flying around blind trying to get one to trigger.

**Comment by zachbr** [comment]
Nevermind I stumbled across some.

The two characters I keep seeing pop up are \uF700 \uF701 both of which are in the private use area of the Unicode Block.

**Comment by zachbr** [comment]
This should be fixed in versions 389+
The offending data will be stripped from signs automatically as the chunks they are in are loaded.

**Comment by mtoensing** [comment]
Wow! Thank you!
