### ISSUE TITLE
Question about Tab complete bug "spigot.yml"

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1572]
### What behaviour is expected:
I would like to set spigot.yml something like:
```
commands:
  tab-complete: 3
  send-namespaced: false
```

### What behaviour is observed:
Tab complete works starting from the first character, no matter what value `tab-complete` has. Tried values between 0 and 5. This reveals plugin information to easy. This means I had to set it completely off (`-1`).
Questions arise to me: Is this a spigot issue or a paper? Can this be fixed? 

### Paper build number:
independent from any version

**Comment by electronicboy** [comment]
tab completion is now client sided, the server isn't really in control with this anymore, setting -1 will disable sending all commands to the client, breaking tab completion entirely
