### ISSUE TITLE
Advice request regarding armor stands performance

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#1574]
As armor stands have become a popular decorative object over the last years, they lead to self-inflicted TPS problems. If between 2000 and 5000 armor stands are processed per tick, they will have a considerable importance in the timings, no matter how good the CPU is. One can regulate the use to a certain extent, but because of the great possibilities one must come to terms with this sin. So how to improve the armor stands performance?

1)	What does “armor-stands-tick” do?
2)	Is “armor-stands-do-collision-entity-lookups” combined with this plugin (https://github.com/zachbr/BlockArmorStandMovement/releases/tag/v1.0) still a good tip?
3)	Any think else I can do but reducing the armorstands?
I am grateful for any advice 😊

**Comment by BillyGalbreath** [comment]
1) That setting, when set to false, will disable armorstands staying in sync with the poses datawatchers. This should be ok, as I cant think of anything the client does that would alter the poses (commands that could manipulate the poses are sent to the server to be processed on the server anyways).

2) No idea what that plugin actually does. Worth a shot, I guess.

3) Armorstands are entities. Entities naturally use a lot more cpu than blocks do. I understand you can use them for decorations, but you have to eventually come to terms with the fact that they were never designed for that. There comes a point where if you need that much decorations it is advised to move to modded server and clients. ;)

**Comment by TheoRetisch1** [comment]
Thank you for your reply Billy! I did some testing. The effect of "armor-stands-tick: false" is just amazing. It reduces the performance required for armor stands to a ridiculous level (https://imgur.com/a/4vcYOeq). Billy is right about the server processing nearly all manipulating poses. That means that plugins working with armor stands will work flawlessly in most cases. 
There is only one big issue. A player can’t see an armor stand spawned by a plugin, so one needs to relog to get the specific packets from the server. Which event would a plugin have to call to let players see the armor stand immediately? Is it even that simple? How hard is Paper trying to stop all events between player and armor stand and how can one stop this behavior for the armor stand spawning event in a plugin?

**Comment by TheoRetisch1** [comment]
Hej,

I am still very much interested in this topic. Of course, I don't expect a complete solution. But I'd be happy to get a hint on how and where to start to send a single armor stand visualization package to a player despite armor-stand-tick being disabled. It's one of two crucial points that keep me from getting absolutely breathtaking performance thanks to this option. I really appreciate any help :)

**Comment by BillyGalbreath** [comment]
Shortly after my last comment I learned that disabling the armorstand tick indeed messes with behavior in an undesired way. With the tick disabled clicking to add/remove armor is broken. You are able to put armor on, but the visual does not update. Clicking again to remove that invisible armor does not work. You have to break the armorstand for it to drop the armor.

For this reason, I would now advise not to disable the armorstand tick.

**Comment by astei** [comment]
Disabling armor stand ticking is appropriate only for very niche situations. It's not an option to be enabled for the sake of enabling it.

**Comment by TheoRetisch1** [comment]
Thanks for your input :). Disabling armor-stand-ticks is definitly not an option that would be only important for just very few niche servers. Armorstands are used more and more often and by more and more servers as decorative elements and for redstone circuits (https://imgur.com/a/bhtkXqi). Now one can of course argue that this procedure abuses the actual function of armor stands as entities and that these servers themselves are to blame. Removing all armor stands embedded in the corresponding concepts is the same as closing the server. Why not help those servers that have already encountered performance problems and at the same time free the armor stands from their entity role. Armor stands offer a lot of possibilities to make the unmodified Minecraft more detailed and varied. The technical possibility already exists with the armor-stand-tick option, it just must be extended. If you exclude armor stands with base plate from the option, as I suggested and explained in detail in #1654, you avoid the unwanted side effects. 
If in the second step a solution is found to force individual armor stands to update plugin-based, the problem is solved. The remaining process of editing armor stands is sent to the server to be processed on the server anyways.

I hope I pointed out that this is not a niche problem of a random guy who thinks that it can be achived in 5 minutes. I hope you can think about putting this problem on the to-do list next to the 1000 other ideas and problems that appear here and solve the worst still present performance problem.

**Comment by TheoRetisch1** [comment]
The bugs have been fixed in version 1.13.2 and enabling default armorstands can be easily accomplished using a plugin. As a result, the armor-stand-ticking function has become a powerful performance feature. Thanks to everyone who answered my questions a few months ago.

**Comment by flowl** [comment]
@TheoRetisch1 spamming armor stands in moving state, like into water, is still a very often encountered way to bring down a server within minutes.  Do you have any advice or plugin that removes armor stands when there are more than ~100 found in a chunk? I  am even thinking about disabling armor_stands completely and making them a special item obtainable as a reward.
I'm  trying `armor-stands-do-collision-entity-lookups` now but I think it still makes a server slow down quickly.

**Comment by TheoRetisch1** [comment]
Well I didn't open this ticket at the time to remove armor stands and have no interest in doing so. Just think what unpleasant side effects this could have.
But if you really want it, set `armor-stand-ticks` to false in paper.yml, that will stop armor stands from falling.
Alternatively, a pull request was merged two days ago, which could exactly meet your requirements? https://github.com/PaperMC/Paper/pull/4792

**Comment by flowl** [comment]
@TheoRetisch1 on fun servers with economy it's not too uncommon that the balance of how many items beeing available in the game is altered.
Making the armor stand a special item that is worth a dragon egg is a very appealing idea to me :-) Players have to earn them >:-D
Thanks for pointing me to the that PR, I think it's helpful!
I also found https://github.com/PaperMC/Paper/issues/1927 which addresses the same thing and just noticed you were involved too. I'm trying both setting no and watch the performance.
Thanks m8!
