### ISSUE TITLE
server crash on build #366

### ISSUE THREAD

**Issue by dfl2me** [PaperMC/Paper#1575]
server crashes when a player logs in.

Plugins: all disabled

Tried pulling timings reports to no avail, server crashed before i could retrieve.

Logs attached.
[McMyAdmin-20181013-073931.log](https://github.com/PaperMC/Paper/files/2475920/McMyAdmin-20181013-073931.log)
[2018-10-13-5.log](https://github.com/PaperMC/Paper/files/2475922/2018-10-13-5.log)

**Comment by dfl2me** [comment]
timings report:
https://timings.aikar.co/?id=77f7b18120b14fdcad3b34e18c4f78ea

**Comment by dfl2me** [comment]
corresponding log to that timings report attached
[McMyAdmin-20181013-175826.log](https://github.com/PaperMC/Paper/files/2475942/McMyAdmin-20181013-175826.log)

**Comment by electronicboy** [comment]
Should be fixed in build 406+
