### ISSUE TITLE
Add the ability to change renderType of scoreboard objective

### ISSUE THREAD

**Issue by CalebBassham** [PaperMC/Paper#1578]
Some scoreboard objectives can have renderType and it is currently not possible to change it in the api. For example, an objective with "health" criteria it can have a render type of "hearts" or "integer". The default is "integer" and I would like to be able to change it to hearts but currently the only way to do that is using the vanilla command.

**Comment by ghost** [comment]
Is this not possible with `getScoreboard().getObjective("").setRenderType(RenderType.HEARTS);`?

**Comment by CalebBassham** [comment]
Pretty sure that wasn't a thing when I made this issue but I just updated to the most recent version and it is so... closing now. Thanks!
