### ISSUE TITLE
Server Lag!

### ISSUE THREAD

**Issue by DragonSurvival** [PaperMC/Paper#1580]
###  Timings or Profile link: https://timings.aikar.co/?id=de825f95053f4cd6852bb4f3c44057ed
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___

### Description of issue:
___If applicable___

### Plugin list:
IN TIMINGS

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit: https://hastebin.com/ilogodonak.coffeescript
spigot: https://hastebin.com/efasaludat.bash
paper: https://hastebin.com/egejarigah.coffeescript

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
paperclip1.13.1 - 364

**Comment by aikar** [comment]
WorldGuard PlayerMoveEvent appears to be your biggest culprit. You'll need to ask them how to improve that.
