### ISSUE TITLE
"Offworld" regions are generated

### ISSUE THREAD

**Issue by shelterx** [PaperMC/Paper#1584]
When using the latest builds of Paper with my 1.12.x converted world, the server always creates these region files in all dimensions (overworld, the end and nether).
r.-26.37.mca, r.-26.38.mca, r.-27.37.mca and r.-27.38.mca.
They show up as a single chunk of region very far away from the actual player generated terrain.

If I stop the server and delete these region files they always come back when I start Paper again.

If I delete the regions and move back to Vanilla Minecraft 1.13.1 the regions DO NOT show up/gets created, so it is Paper that's doing something and generates these regions on start up.

No plugins, 
git-Paper-375 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)

Suggestions how to dig further into this is much appreciated.
![temp](https://user-images.githubusercontent.com/8688458/47149198-2413a600-d2d3-11e8-8d23-cf6a3f39f27a.PNG)

**Comment by BillyGalbreath** [comment]
Does this happen on Spigot or CraftBukkit as well?

**Comment by shelterx** [comment]
No, just tried with CraftBukkit version git-Spigot-f6a273b-cd6252a (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT), those regions are NOT created when running spigot.
So it's entirely Paper related. 
(I have seen these region files before i started using paper, then i just deleted them but I can't get them to generate in any other mc version right now.)

**Comment by aikar** [comment]
I can't see how paper could cause this. This just means a plugin accessed chunk out there. Did someone use /locate or treasure map maybe that didn't get used in the spigot test?

**Comment by shelterx** [comment]
Well, I don't think anyone know of the locate command, and there's no tresure map found yet.
There's an End City in the End  in that chunk. In overworld and nether it seems to be just empty land.
I think paper "polls" something that Spigot and Vanilla doesn't do. 
I just removed those region files and they came back upon startup again.
2018-10-18  16:48         1 060 864 r.-26.37.mca
2018-10-18  16:48         1 089 536 r.-26.38.mca
2018-10-18  16:48             8 192 r.-27.37.mca
2018-10-18  16:48             8 192 r.-27.38.mca

The plugin folder is empty.

**Comment by aikar** [comment]
You wouldn't happen to have your world spawn out there would you? try setting your world spawn using the vanilla command. 

the 8192 files is indicative that something is calling chunkExists()

can you get startup logs? 

Only thing I can think is to give you a debug build that prints when something creates a new region file.

**Comment by shelterx** [comment]
I have full access to the server so it's no problem.
I renamed my "player" .dat file and logged in, I spawned where I am supposed to, unless some other player has a weird spawn location? But are player spawn locations polled during start?
EDIT: I checked the  spawn and pos with nbtexplorer, all players seems to be within world borders.
EDIT2: Used /setworldspawn - no difference.

[latest.log](https://github.com/PaperMC/Paper/files/2492424/latest.log)

**Comment by shelterx** [comment]
@aikar What is actually going on now?
I moved worldspawn, now in overworld it generates a new region called r.-23.27.mca r.-23.28.mca r.-24.27.mca r.-24.28.mca instead (also "offworld"). But in nether and The end the old region files i first wrote about are still generated.
EDIT: Checked level.dat, didn't see anything weird in that file.

**Comment by shelterx** [comment]
Anyway, I double and triple checked, Spigot does not create these files, PaperMC do.

EDIT: Seems like it's level.dat related (worldspawn issue?), I moved the overworld .dat to nether and the end. Now Paper creates the r-r23.27 etc regions in those dimemsions aswell.

**Comment by shelterx** [comment]
@aikar I nailed it down to level.dat file being the problem so here it is.
Wild guess, maybe a combination of mapseed + worldspawn.
[level_dat.zip](https://github.com/PaperMC/Paper/files/2498282/level_dat.zip)

**Comment by mtoensing** [comment]
Same problem here. They are generated even if I delete them on restart or start. I noticed this because of my overviewer render with “no borders”. 

https://mc.marc.tv/iso/
Select No Border and look to the top left. 

How can I fix it?

<img width="1426" alt="screen shot 2018-12-04 at 21 19 18" src="https://user-images.githubusercontent.com/136737/49470414-52f5c500-f80a-11e8-95d4-18fe2ec05f97.png">

![image](https://user-images.githubusercontent.com/136737/49470487-85072700-f80a-11e8-8e09-21368e6a390e.png)

**Comment by shelterx** [comment]
The devs have to dig into it. They have all they need one post above yours.
As a "workaround" I currently use spigot instead, it does not generate these regions.
I prefer paper tho'.

**Comment by shelterx** [comment]
This bug seems to be gone now. I don't seem to get any "offworld" chunks anymore.
