### ISSUE TITLE
Mob spawners request.

### ISSUE THREAD

**Issue by Parozzz** [PaperMC/Paper#1590]
What I am asking here are two things:

1.  A few time ago, precisely on September 9, this was added in the pre-1.13 branch #1425 . Change the nbt filtering mob spawner has, through a Paper.yml option or having it directly bypassed as in the pull request above.

2.  Change the modifier to public for the "mobs" and the "spawnData" field inside the MobSpawnerAbstract. The first is a List of MobSpawnerData and manager multiple spawn type of the same spawner, the second one is just the actual MobSpawnerData of the mob is being spawned. I would like them changed so they could be reached without needed to use nms or having to use save/load through NBTTagCompounds every time. This is already been done for every other field except those two. (I know there is an API for setting the "spawnData" field, but every extra configuration that can be done to the spawning entity are impossible without hacky ways or through events, like setting a different loottable to the mob or having it spawn with low health) 
2,1. I'll list this as a sub suggestion, would be cool though to have an actual API for adding spawn type to this potential list.

Is this something that might be too difficult to maintain for future releases or is something manageable?.

**Comment by aikar** [comment]
what is your use case for 1?

2.0 is a no. that IS NMS so your using NMS to do that regardless. You can use reflection to set the value
2.1 sure, an api to set multiple mobs is fine since nms seems to support this idea.

PR's welcome for that

**Comment by Parozzz** [comment]
1: What I am doing, I am actually saving the NBTTagCompound saved from a destroyed Spawner and saving it inside the ItemStack created from it. I need to reapply this NBTTagCompound using the BlockBreakEvent back to the spawner when placed. This would help since is an already functioning vanilla mechanic.
But this might help also other people, who use commands to create spawners and they cannot anymore.

2: No problem for that.
2.1: Yeah, not long time ago Spigot actually added an API to change *most* of the values (After has been done here i think), still not adding support for the Spawn Potentials.
