### ISSUE TITLE
Server crash related to lighting updates

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#1592]
Build: git-Paper-1582 (MC: 1.12.2)
Log: https://pastebin.com/XYC3XjVx
Crash report: https://pastebin.com/7TeywMqR

Here's a crash I got later which did not generate a crash report, only a stacktrace: https://pastebin.com/cY5qXcBH

**Comment by electronicboy** [comment]
The line at which this crash was caused, shows that this is theoretically impossible outside of plugins messing around with stuff async

The latter log file looks like somebody is doing something to cause excessive light updates

**Comment by SecretlyJealous** [comment]
> The line at which this crash was caused, shows that this is theoretically impossible outside of plugins messing around with stuff async
> 
> The latter log file looks like somebody is doing something to cause excessive light updates

Got any recommendations on what I can do to fix this? The second crash I mentioned is the one I get often, the other one seems to have been a one off situation. [https://pastebin.com/peb1YCHU](https://pastebin.com/peb1YCHU) and without lighting queue: [https://pastebin.com/jLzGWx2m](https://pastebin.com/jLzGWx2m)

Timings with lighting queue enabled: https://timings.aikar.co/?id=15b03bd4787f4e4da643967bbc593774  https://timings.aikar.co/?id=a051b64e6e39448b9995eba03129b429 Light Chunks seems extremely high.

I'm in a weird situation where someone can basically just cause a bunch of light updates to trigger and it crashes the server sometimes but I can enable the lighting queue to stop the crashing in the short term from happening constantly however the issue with the lighting queue is that on weekends for example my server always crashes at around the evening during peak time (has done this for the past two weekends) but last weekend I disabled the lighting queue on purpose and the server did not crash. It leads me to think that the lighting queue is getting overwhelmed the longer its running for. But again, by having lighting queue disabled someone could just easily trigger a bunch of lighting updates to crash the server.

Is there anything that could be done to improve the behaviour of the lighting queue when it is basically overwhelmed due to being enabled on the server for too long?

**Comment by SecretlyJealous** [comment]
Had a plugin run this and it fixed the issue, the method no longer exists in 1.13 and I have not had it happen on 1.13 so I assume the issue is fixed. For whatever reason it seems like chunks can be set to lit false (maybe a spigot issue?)
>     @EventHandler
>     public void onChunkLoad(ChunkLoadEvent event) {
>         if(event.isNewChunk()) return;
>         CraftChunk craftChunk = (CraftChunk) event.getChunk();
>         Chunk handle = craftChunk.getHandle();
>         handle.e(true); // set lit to true
>     }
