### ISSUE TITLE
Equipping armor on Armor Stands makes armor invisible

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#1593]
git-Paper-375 (MC: 1.13.1)

When:

```
armor-stands-do-collision-entity-lookups: false
armor-stands-tick: false
```

Adding any kind of armor to armor stand makes that armor invisible, armor drops just fine if armor stand is destroyed. Armor will stop being invisible after client relogin. 

Is this intended behavior?

**Comment by BillyGalbreath** [comment]
Confirmed. It's the `armor-stands-tick` option that causes this. This setting, when false, bypasses the server<->client datawatcher sync.

**Comment by zachbr** [comment]
Should be fixed in builds 430+
Thanks
