### ISSUE TITLE
Player's remaining air does not refill when respawning

### ISSUE THREAD

**Issue by aeonlamb** [PaperMC/Paper#1597]
### What behaviour is expected:
When you die and respawn, the player's remaining air value should be full once again if it was previously a lower value.

### What behaviour is observed:
If you die from drowning, and respawn underwater once again, you will be drowning the instant you respawn. This differs from vanilla. 

### Steps/models to reproduce:
1. Place bed in a river, ocean, any body of water
2. /time set night, sleep in bed to set spawnpoint
3. drown
4. observe you are still drowning the instant you respawn

### Plugin list:
none

### Paper build number:
Paper-382 (latest 1.13.1)

### Anything else:
This is a really specific, not very important bug, but may as well report it, eh?

**Comment by zachbr** [comment]
This is just as a result of drowning while in a bed right?

**Comment by ghost** [comment]
The issue is that if you respawn underwater, your air level does not reset to full.
