### ISSUE TITLE
Drowned Pathfinding Slow

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#1599]
git-Paper-382

The drowner pathfinding and moving seems to take too much time, specifically when both the player target and the mob are both in water.

https://i.imgur.com/PK54EHK.png

**Comment by hurrgurl** [comment]
Remains an issue in paper 387

**Comment by Beaness** [comment]
I think this should be closed since its refered to a closed issue.

**Comment by hurrgurl** [comment]
This has been fixed, thank you.
