### ISSUE TITLE
PaperSpigot / ViaVersion (Protocol Hack) compatibility issue

### ISSUE THREAD

**Issue by alexmarkey** [PaperMC/Paper#160]
PaperSpigot Build - http://prntscr.com/akwsd2
ViaVersion Build - 0.6.7 and below (Temp fix in 0.7.0 that I got the dev to add)

Using ViaVersion (https://www.spigotmc.org/resources/viaversion.19254/) a protocol hack that allows 1.9 clients join a 1.8 server, whenever a player is using a 1.9 client, paperspigot lets them place blocks where they are standing.
Due to our server having a large skywars playerbase (4,000+ players), whenever players tower up they will place blocks inside themselves knocking them off of their tower.

I believe the reasoning for this to be related to the being able to place blocks inside invisible players.  Currently I have had the ViaVersion def implement a temp fix that checks if the player is placing a block in where they're standing and cancel if they are, however due to latench this is a pretty bad fix and players still glitch in blocks.

Not saying this is necessarily a PaperSpigot issue, however if some indicators could be given as to what is causing this issue so that we can fix it on the ViaVersion end of things, that would be much appreciated :)

if you want to reproduce this, feel free to go on my server mc-central.net hop on our Creative server, grab a plot, look at your feet then place a block.

**Comment by zachbr** [comment]
All development focus is on 1.9. We no longer formally support 1.8.8

**Comment by liach** [comment]
Go to https://github.com/MylesIsCool/ViaVersion/issues/new

**Comment by alexmarkey** [comment]
As stated I am willing to get this fixed myself if you can tell us what is going on.
