### ISSUE TITLE
data lost upon opening 1.12.2 Spigot world data with 1.13.1 paperclip

### ISSUE THREAD

**Issue by rkiddy** [PaperMC/Paper#1601]
I had a 1.13.1 world running with paperclip. I made a copy of it. I replaced its world data with the world data from a 1.12.2 server running Spigot. I expected that it might upgrade the world data.

What I saw is that I was unable to load the world. It timed out several times. Unbeknownst to me, it also deleted the data. I had a copy of my map data but I lost my person data.

I have a fairly large world. I can supply details or I can re-run the experiment, if it is desired.

**Comment by rkiddy** [comment]
[screenlog.1.txt](https://github.com/PaperMC/Paper/files/2498781/screenlog.1.txt)

This is the errors I saw when trying to enter the server.

**Comment by zachbr** [comment]
Try running an updated version, that log shows that you are nearly 60 versions behind.

**Comment by rkiddy** [comment]
You are right. My bad. The current version does not have the problem. Sorry for the noise.
