### ISSUE TITLE
Occasional lag, too many plugins?

### ISSUE THREAD

**Issue by Leomelonseeds** [PaperMC/Paper#1602]
I don't know if this is the right place to post this but might as well give it a shot. 

So I recently upgraded my server, yet players still complain about lag. I heard from @frash23 on spigot that "you can host 80 players with 2GB allocated RAM and 50 plugins without any real problem." How would I do this?

I am also considering removing some plugins, I do not know which ones though. To get an idea of my server follow this link (please don't take this as advertising, it's not): https://www.spigotmc.org/threads/ultima-kingdoms-1-8-tell-me-why-my-server-sucks.339952

**I use aikar's startup flags (6GB)**

###  Timings or Profile link:
https://timings.aikar.co/?id=dbb9033774194cd79a44812e8748e57f#timings

### Plugin list:
https://i.gyazo.com/18471b038d35414bc931e358710acb48.png

### bukkit.yml, spigot.yml, paper.yml, server.properties
Server.properties: https://hastebin.com/moyuhipebi.ini
bukkit.yml: https://hastebin.com/ojeroqocij.coffeescript
spigot.yml: https://hastebin.com/citotinola.bash
paper.yml: https://hastebin.com/zulopopoqi.cs
(wtf each of them saved in a different file format xDDD)

### Other helpful links
Setup:
https://i.gyazo.com/300bd889faf5e9aaf50415ca6545c4e1.png

### Paper build number:
1581 (1.12.2)

**Comment by Leomelonseeds** [comment]
Updated timings report with about 15 players on:
https://timings.aikar.co/?id=70b75254b0e74b388164f0a8737a7239#timings

**Comment by zachbr** [comment]
If you're still seeing this please reply here with an updated timings link, plugin list, and version number.
