### ISSUE TITLE
Could not pass event PlayerPickupArrowEvent

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1604]
### What behaviour is observed:
When a player picks up arrows shot by another player this error comes by
https://hastebin.com/iwafoxawij.cs

### Steps/models to reproduce:
Shoot arrows just beside a player

### Plugin list:
3 plugins gives errors with this behaviour:
- WorldGuard v7.0.0-SNAPSHOT;1750-7e0ff24
- Spartan vBuild 206
- GriefPrevention v16.11.4

See: https://hastebin.com/nojuzefete.cs
Reported this to WG and got the answer that this concerns bukkit.

### Paper build number:
git-Paper-381 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

### Anything else:
https://dev.enginehub.org/youtrack/issue/WORLDGUARD-3986

**Comment by Brokkonaut** [comment]
Full stack trace:
https://pastebin.com/raw/dxSHCNqN
