### ISSUE TITLE
Iron Phoenix paper 1.13

### ISSUE THREAD

**Issue by Dinip** [PaperMC/Paper#1607]
### What behaviour is expected:
A lot of iron golems (~2600 iron/h) and ~20k drops/h...

### What behaviour is observed:
Like 100 iron/h and 600 drops/h

### Steps/models to reproduce:
I've made an Iron Phoenix farm (https://www.youtube.com/watch?v=kxixJ5P_V7k), I've waited the 1h30 as he said in the video. I've already made this farm 1.13.1 pure vanilla and it worked perfectly.
Yesterday we've finished a mob farm (https://youtu.be/UN0sKkWhsfA), I've also have done it on vanilla one time and worked no problem. Here on this server running paper we are having problems with the spawn rates. I've left my user online all night in both farms with no users online and the drops were so low..

### Plugin list:
AutoSaveWorld
CoreProtect
DiscordSRV
SavageFactions
TPA
Security Villagers

### Paper build number:
![image](https://user-images.githubusercontent.com/8941012/47272839-0704fe80-d583-11e8-8ce5-e3030c44bca8.png)

### Anything else:
Nope! :)

**Comment by aikar** [comment]
check spigot.yml for "tick-inactive-villagers" set it to true, should fix it.

outside of that, can only suggest boosting "animals" activation range in same file.

if that doesn't work then im not sure.
