### ISSUE TITLE
How can I disable the entity collision feature? Like it was in 1.8.

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#161]

**Comment by MADS0LADEN** [comment]
Create a scoreboard team, and disable collision on that team and then add the players to that team.

**Comment by andris155** [comment]
"Set the command block to Repeat, Always Active and set the command to:
/scoreboard teams join all @a[team=]"
This is not TPS friendly.

**Comment by RoboMWM** [comment]
> This is not TPS friendly.

How do you know?

> command block

He never mentioned a command block...

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=DMlzrlY52OE
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/14109370/f38eb358-f5c1-11e5-8a54-c83c76f0e6b6.PNG)

**Comment by RoboMWM** [comment]
Again, my exact same comment applies.

How do you know this isn't "TPS friendly" and this isn't the only way to do it...

**Comment by aikar** [comment]
set paper.yml settings.enable-player-collisions: false
No performance impact.

**Comment by andris155** [comment]
Thanks!
