### ISSUE TITLE
Extrem TPS drops 1.13.2 - CPU overload of one core

### ISSUE THREAD

**Issue by Serial1990** [PaperMC/Paper#1613]
###  Timings or Profile link:
https://timings.aikar.co/?id=7e0e1ce551464754ae6ac1dac65d00d7
https://timings.aikar.co/?id=cf10ebb3860b4f7ea2f810393238c6e0

### Description of issue:
My CPU Workload reaches often 100% of one core and the TPS spikes alot...

### Plugin list:
https://timings.aikar.co/?id=7e0e1ce551464754ae6ac1dac65d00d7#plugins

### bukkit.yml, spigot.yml, paper.yml, server.properties
spigot.yml: https://pastebin.com/ncWBPCCX
bukkit.yml: https://pastebin.com/V0K57Pak
paper.yml: https://pastebin.com/FwwhqspZ
server.properties: https://pastebin.com/uNfGHVWC

### Other helpful links
Start Flag: java -Xms${MINRAM}G -Xmx${MAXRAM}G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=60 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs -jar /home/${USER}/minecraft/server.jar --noconsole

### Paper build number:
390

**Comment by electronicboy** [comment]
Looks like you have a redstone machine on the server somewhere triggering a lot of block updates

**Comment by Serial1990** [comment]
> Looks like you have a redstone machine on the server somewhere triggering a lot of block updates

I now use PandaWire. I let u now tomorrow.

**Comment by Serial1990** [comment]
Ok, looks like pandawire fix this problem. :)

https://timings.aikar.co/?id=e6cf9bc6aaad4710b28fcf1fff8a5383
