### ISSUE TITLE
Would Paper possibly disable Mob agro (AI)?

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#1614]
I may be off thinking Paper is the culprit, but I can't figure this out. Wondering if it's possible that Paper could make lazy, unresponsive mobs. Maybe to do with ticking mobs and chunk loading/unloading?

### What behaviour is expected:
Hostile Mobs to agro when players are near.

### What behaviour is observed:
Hostile mobs will not attack until attacked first. If you have a bow at a medium distance, you can just kill mobs all day. 

### Steps/models to reproduce:
I generated a world on 1.13.1 using EpicWorldGenerator (doubt it's relevant). Players say mobs won't attack. You can walk right up to a Creeper and push it around. If you don't hit it, it basically has the AI of a sheep. Occasionally moving, never attacking.

### Plugin list:
Arconix*, AutoAFK*, AutoPickup*, BannerMaker*, Citizens, CitizensCMD, CMI, CrazyCrates, CrazyEnchantments, CurrencyDrops*, DeluxeCommands, DeluxeJoin, EpicFarming, EpicSpawners, EpicWorldGenerator, eZProtector*, FarmLimiter*, GPAccruals*, GriefPrevention, GriefPreventionFlags, Heads*, mcMMO, mcMMOAction*, McMMOExtras*, PermissionsEx*, PlayerHeads*, PlayerShopGUIPlus, ProtocolLib*, PvPManager*, RepairPlus, ServerSigns*, ShopGUIPlus, Vault*, VeinMiner, Votifier, WorldBorder*, WorldEdit

### Paper build number:
git-Paper-386 (MC: 1.13.1)

Paper.yml: https://hastebin.com/niwigelezo.coffeescript
Spigot.yml: https://hastebin.com/leqogayuri.coffeescript
Bukkit.yml: https://hastebin.com/layowewara.coffeescript
server.properties: https://hastebin.com/vobovuzeho.ini

**Comment by CeIebrimbor** [comment]
Downgraded to Spigot and issue still happened.

**Comment by aikar** [comment]
Issue sounds like a plugin. I just found out activation-range does have an impact here too, but your range was set to 40 so that wasn't the source.

**Comment by CeIebrimbor** [comment]
Pretty sure it's plugin too. Going to do the trial and error with 60 plugins now...

**Comment by xXkguyXx** [comment]
Could maybe just print out what plugins have events registered with events regarding targeting
