### ISSUE TITLE
Build #396 server crash and lag

### ISSUE THREAD

**Issue by dfl2me** [PaperMC/Paper#1615]
It happens during world exploration. I can tell when it's about to occur when I am unable to shoot a bow and arrow. Timings show issues w/ tileEntityHopper at times.

**### Link/paste of stack trace**
Minecraft (MCMA) log: https://pastebin.com/0LCtjdTA

**### Plugin list:**
All plugins disabled for now.

**### Actions to reproduce (if known):**
Happens during world exploration.

**### Paper build number:**
396

**Timings Reports**
https://timings.aikar.co/?id=ea75e62e65614f58916344714a345c4b
https://timings.aikar.co/?id=aa8fa92f39724a17a6a681fed13eaf8e
https://timings.aikar.co/?id=6bfefab621a5444cabfed2cdf0c4dcb8
https://timings.aikar.co/?id=05a5b99652794df8a56b7642bb70a803
https://timings.aikar.co/?id=51f7f7298fb8482690a7b42a5d34898c
https://timings.aikar.co/?id=649b2642a3b744b48c58b7048327ac5c

**YML Files**
Spigot: https://pastebin.com/1F8KFBau
Paper: https://pastebin.com/9U33fcsg
Bukkit: https://pastebin.com/KceDHNat

**Server Config**
https://pastebin.com/8nP4nq9p

**Comment by aikar** [comment]
You are having insane memory problems. REALLY bad. 

You had 69 Old Generation GC's in 1 of those timings. You never want a single one.

I don't understand this though. Are you using /reload? Did you reset timings? If you did reset timings, please don't ever do that.
If you used /reload, also don't do that.

Something's happening with your servers JVM on a very weird level.

But I have no idea what it could be. Try ditching the -Xmx10240M at end of your JVM flags, as you already have -Xmx10G at the start, but that would be interesting if that blew up java's behavior.

**Comment by dfl2me** [comment]
I don't know what /reload is or does, unless F3+A triggers that.
I do notice that timings are reset when the server starts up, is that default? If so, cool. If not, I won't use that command.
I ditched the memory flags this time.

Here is a new timings report when I restarted the server:
https://timings.aikar.co/?id=d51fc3f382054a7ba4e024edc2d85f9a

Maybe my java installation is corrupt?

**Comment by dfl2me** [comment]
I modified startup flags and upgraded to newest build.

Log: https://pastebin.com/WSPzbQSD

Was unable to generate a timings report.

**Comment by zachbr** [comment]
Closing as fixed by the linked commit.
