### ISSUE TITLE
AxisAlignedBB minX and minY are swapped around

### ISSUE THREAD

**Issue by bergerkiller** [PaperMC/Paper#1617]
### What behaviour is expected:
After 1.13.2, the 6 fields declared in AxisAlignedBB are like this:
```
    public final double minX;
    public final double minY;
    public final double minZ;
    public final double maxX;
    public final double maxY;
    public final double maxZ;
```

### What behaviour is observed:
The fields are instead like this (note minX and minY swapped):
```
    public final double minY;
    public final double minX;
    public final double minZ;
    public final double maxX;
    public final double maxY;
    public final double maxZ;
```
This differs from vanilla Spigot and Craftbukkit. I assume this is something that resulted from a mistake (?). The order matters, because the field order is used to validate the correct field declaration when talking with the server. It's used to detect inconsistencies when (obfuscated) fields are changed between server versions or implementations.

### Steps/models to reproduce:
Run it with a dev build for 1.13.2 of BKCommonLib. Say, https://ci.mg-dev.eu/job/BKCommonLib/459/

### Plugin list:
BKCommonLib (impacted)

### Paper build number:
399

### Anything else:
This is since 1.13.2. On 1.13.1 and earlier, the fields were still obfuscated a-f names.
Causes the following (intended!) warning to appear in BKCommonLib:
```
A class member of net.minecraft.server.v1_13_R2.AxisAlignedBB was not found!
Failed to find field public final double minY; - Alternatives:
    - public final double minY;
    - public final double minX;
    - public final double minZ;
    - public final double maxY;
    - public final double maxX;
    - public final double maxZ;
Field 'minY' not found in template for net.minecraft.server.v1_13_R2.AxisAlignedBB
```

**Comment by electronicboy** [comment]
I'll fix it in a sec, an oops occured while updating, however it was never considered an urgent fix given that nothing past compilation (outside of people doing... well, that, apparently) cares about

**Comment by electronicboy** [comment]
Fixed in https://github.com/PaperMC/Paper/commit/0696c672be13a2ac4bc1262ba6adfd4d40b46675

**Comment by bergerkiller** [comment]
Thank you for the very rapid patch! :)

**Comment by axemwa** [comment]
Thanx that was quick! :D
