### ISSUE TITLE
Minecraft Functions dont work as supposed.

### ISSUE THREAD

**Issue by MisterCookie1234** [PaperMC/Paper#1626]
Hello!
I have looked if Paper works with functions and it seems like it don't.
My Worldsave (including datapack): https://www.dropbox.com/s/jp3wz8o66zypp13/Minecraft%20Trains%20from%20Gshn28%20-%20Map%20by%20MisterCookie1234.zip?dl=0
The Ressourcepack:  https://www.dropbox.com/s/0701iniyw5ai7jx/Minecraft_Trains_1.13_-_By_Gshn28_RESOURCE_PACK.zip?dl=0

Problems i saw:
Well... Everything? Trains wont Move, Trains wont Spawn like they should and more. So basically everything is broken, even though all of them use Vanilla Commands

I used the 1.13.1 Version of Paper.

**Comment by akoimeexx** [comment]
Suggest loading your datapack in a default world in multiplayer Paper and running the individual commands via /function to test if they're working.

**Comment by MisterCookie1234** [comment]
Aye!
I did check it and everything runs fine now.
But, whenever the train gets out of my Render distance, he breaks. Like completely. Turns wont work anymore etc. Any ideas why thats happening?

**Comment by zachbr** [comment]
Depending on how your mcfunctions are written, entities that travel away may be switched to an inactive tick depending on their type, regardless once they leave "render" distance (the server refers to this as view distance and it refers to the area of chunks loaded around players) they may be unloaded entirely.

If you're still seeing this please reply here and let us know if you have any additional information.
