### ISSUE TITLE
Bow + boat bug

### ISSUE THREAD

**Issue by ArtNRG** [PaperMC/Paper#1628]
### What behaviour is expected:
The bows are shooting where I'm aiming while I'm riding a boat.

### What behaviour is observed:
The bows shooting in the one point.

### Steps/models to reproduce:
https://youtu.be/cBIVHhfJyjY

### Plugin list:
0 plugins

### Paper build number:
git-Paper-405 (MC: 1.13.2)

### Anything else:
Tested in vanilla single-player mode too, there is no bug.

**Comment by electronicboy** [comment]
tested in CB? Spigot?

**Comment by ArtNRG** [comment]
Tested in paper and vanilla only.

**Comment by ArtNRG** [comment]
Tested in the latest Spigot - CraftBukkit version git-Spigot-e4d0c66-72c3617 (MC: 1.13.2), there is the bug.

**Comment by aikar** [comment]
this likely relates to my vehicle changes, we had a case on my server in 1.12 where throwing items out of minecart didnt go away from you but i couldnt reproduce on 1.13
