### ISSUE TITLE
Low TPS without reason

### ISSUE THREAD

**Issue by AzoteBottle** [PaperMC/Paper#1629]
###  Timings or Profile link:
https://timings.aikar.co/?id=2b1ba018fa404f4187dac2f41418d181

### Description of issue:
low TPS without reason

### Plugin list:
https://timings.aikar.co/?id=2b1ba018fa404f4187dac2f41418d181#plugins

### bukkit.yml, spigot.yml, paper.yml, server.properties
Spigot.yml : https://pastebin.com/Bh91rNie
Paper.yml : https://pastebin.com/PKyXU8Cp
Bukkit.yml : https://pastebin.com/5fG0vMFp
Server.properties : https://pastebin.com/LWr7KzTN

### Other helpful links
I've got dedicated server : 
Intel  i7-7700K
4c/8t - 4,2GHz /4,5GHz
64Go DDR4 2400 MHz
SoftRaid 2x450Go NVMe
250 Mbps 

### Paper build number:
Paper 1.13.2 build 403

Kind regards

**Comment by james090500** [comment]
First, update paper you're out of date.

Second try lower your entities/activation range

Also jesus, lower your RAM, 60GB is stupid. Only leaving 4GB to System and your Java GC will have a heart attack, set it to like 10GB Max

**Comment by electronicboy** [comment]
Overall, you just have too much going on, reduce entity count/activations, as already noted, try to cut down on plugins like your own blocking the main thread as much as they are in some points (e.g. what is your plugin doing in quit/join events that is taking over a tick, can that be optimized; teleportation can ideally be done with loading the chunk async, and then using the callback to actually teleport the player, saving you from blocking the main thread loading up the chunk, etc)
