### ISSUE TITLE
Player data is not saved

### ISSUE THREAD

**Issue by rxdn** [PaperMC/Paper#1630]
### What behaviour is expected:
Player data should be written to disk when a player logs out or the server is rebooted

### What behaviour is observed:
Player data is not written to disk, leading to any items in the player inventory or ender chest being lost when a player logs out

### Steps/models to reproduce:
1) Join the server
2) Add some items to your inventory or ender chest
3) Leave and rejoin the server

### Plugin list:
Issue occurs without any plugins installed

### Paper build number:
git-Paper-1584

### Anything else:
The issue does not occur when running the latest 1.12.2 Spigot build. The server has 74GB of space free (this is a dedicated server, so not an issue of a host over-allocating storage). Other data, such as world changes, or files written by plugins are written without issue.

**Comment by zachbr** [comment]
Can't reproduce this. Are you sure you have world saves enabled? Otherwise I'm not sure, double check file perms in stuff like the world player data folder and hopefully you see something.

**Comment by aikar** [comment]
You need to provide full logs

**Comment by rxdn** [comment]
I'll switch back to Paper tomorrow night when not as many players are on and grab logs then. I checked file permissions when the issue was happening and they seemed fine, same as all other files.

**Comment by hurrgurl** [comment]
I have a similar issue, never figured out the cause.

Goes something like this:

1) Get shulker box full of items
2) Put shulker box in ender chest
3) Now /stop the server

Allegedly shulker/items disappear sometimes.

Been unable to reproduce myself, players still complain about item loss on /stop while theyre using ender chests.

Never found anything suspicious looking in logs.

--

Dedicated server java10
Paper build 406
Default spigot/bukkit/paper.yml config
No noteworthy plugins

**Comment by ArtNRG** [comment]
I have the same issue as @hurrgurl and can't find the way to reproduce it too. My players were reported it last time after switching from 1.12.2 to 1.13.1.

**Comment by zachbr** [comment]
Anyone have any recent issues with this (as of 1.13.2 or 1.12.2)?

**Comment by mike855** [comment]
Same problem here in 1.14.4, we are connecting with empty inventory

**Comment by zachbr** [comment]
If this is occurring on 1.14.4 or 1.13.2, please open a new ticket with full logs and configs. Closing this one as outdated and no information.
