### ISSUE TITLE
Sand falling not naturally

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1633]
### What behaviour is expected:
I excepted a sand to fall naturally...

### What behaviour is observed:
The sand falling not naturally...

### Steps/models to reproduce:
Break a block under the sand
https://youtu.be/tSHhsonCpRI

### Plugin list:
Only PlugMan

### Paper build number:
git-Paper-1581 (MC 1.12.2)

### Anything else:
Sorry, my friend played with me on discord, and I'm forget disable him sounds.
Sorry for my bad English

**Comment by electronicboy** [comment]
Please don't submit issues where you've used a plugin such as PlugMan to disable other plugins, there is no promise whatsoever that a plugin has been properly cleaned up and still isn't affecting the server still;

I cannot replicate this, and from your video, it entirely looks like this is a clientside rendering issue, not a server issue, as the blocks appear to be falling on your video normally, just looks like they're kinda missing their blockface(s) during rendering

**Comment by 0-x-2-2** [comment]
Looks like its falling fine on the server its just a client rendering issue when you are far away from 0, 0.
