### ISSUE TITLE
No NBT tags given for an item with datapack tags

### ISSUE THREAD

**Issue by krazzbeluh** [PaperMC/Paper#1635]
When I give a pickaxe for a gamemode adventure player with NBT tag "canDestroy", he recieves his pickaxe but without any tag like this. It works perfectly with SpigotMC but not with PaperMC. 
My command is 

> /give @s minecraft:diamond_pickaxe{CanDestroy:["#rust_cost_island:block_home_detect_base"],HideFlags:63}

To understand the problem, I've tried to delete the part "HideFlags:63" and I saw no Tags on the Pickaxe. And it works with all blocks named one by one.
The server is running Paper version git-Paper-403 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Thank you :)

**Comment by Parozzz** [comment]
What is "rust_cost_island:block_home_detect_base"?
Shouldn't it be "minecraft:stone" or similar?

**Comment by ghost** [comment]
> What is "rust_cost_island:block_home_detect_base"?
> Shouldn't it be "minecraft:stone" or similar?

I'm guessing it is an nbt tag for either a plugin of a forge mod

@krazzbeluh, if you could give us some background on what this is used for, that would make it easier to better understand how to fix the issue.

**Comment by krazzbeluh** [comment]
> 
> 
> > What is "rust_cost_island:block_home_detect_base"?
> > Shouldn't it be "minecraft:stone" or similar?
> 
> I'm guessing it is an nbt tag for either a plugin of a forge mod

it's almost that but it's for minecraft datapacks, it's 100% vanilla and added in 1.13.

**Comment by ghost** [comment]
> it's almost that but it's for minecraft datapacks, it's 100% vanilla and added in 1.13.

I'll look into this more when I get home, I won't forget about you.

**Comment by krazzbeluh** [comment]
> 
> 
> > it's almost that but it's for minecraft datapacks, it's 100% vanilla and added in 1.13.
> > I'll look into this more when I get home, I won't forget about you.

Ok Thank you, if it can help you, I found that on the official minecraft wiki : [https://minecraft.gamepedia.com/Tag](https://minecraft.gamepedia.com/Tag)

**Comment by Parozzz** [comment]
Might be because of the added API for adventure tags (CanDestroy and CanPlaceOn). Maybe you should want to start from there @GreenMeanie?

**Comment by mikroskeem** [comment]
This is because I added API to Paper which supports setting canDestroy/canPlaceOn on ItemStacks, but as I didn't really bother looking into 1.13+ features then it does not support anything besides items from Material class.

**Comment by ghost** [comment]
@Parozzz, I will do that

**Comment by GamerGlitz** [comment]
It looks like there is an issue with tags on PaperMC. Try doing the following:

/give @p minecraft:diamond_pickaxe{CanDestroy:["#rust_cost_island:block_home_detect_base"]}

If that doesn't work, try the following. If the following doesn't work, Paper should update the build:

/give @p minecraft:diamond_pickaxe{CanDestroy:["minecraft:stone"]}

Once you do what's above ^, then try to destroy some stone. If that doesn't work, then I think Paper should try to release an update for 1.13.2.

**Comment by krazzbeluh** [comment]
Without surprise, the first command doesn't work. The second doesn't work alone. But with a little modification, it works. It seems that we must add an other tag on the pickaxe. For example :
`/give @p minecraft:diamond_pickaxe{CanDestroy:["minecraft:stone"],Test:1b}`
And this doesn't work for the datapacks tags.

**Comment by aikar** [comment]
We already know what the issue is. Just a matter of someone taking the time to fix it. The issue is related to tags in general

**Comment by zachbr** [comment]
Sorry for the long wait on this, 1.13.2 builds 457+
