### ISSUE TITLE
Optimize Small Entity Movement is affecting parrots and wolves.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#1637]
Paper dev 415

https://github.com/PaperMC/Paper/commit/47b9a5d178d3a067e6557c0c2d60356e845cd141 is breaking certain mob animations / functions. Parrots are unable to sit on the ground - they continuously flutter. Wolves are also having issues when toggling their sitting interaction with right click. Possibly other entities affected as well, just that is what I have been informed of by players and able to confirm in a test environment.

Downgrading to Paper dev 411, all is well.

**Comment by LemonJoey** [comment]
Same. Cats Parrots and Dogs following players as they cannot be sat, just keep jigging up and down, also temp went back to dev 411 and no issues.

**Comment by Lxct** [comment]
Same, cats, parrots and dogs tp to player and cannot be sat. Even if the player don't click on them, they keep twerking

**Comment by delet-this** [comment]
This affects chickens as well, they keep fluttering nonstop

**Comment by Parozzz** [comment]
Seems to affect rabbit either, when they try to jump, they fail and keep running. Seems like they are stucked in the block they are trying to jump. Also, always speaking of rabbit, while they run away from you, walking animation is not showed client side but they move (Not sure if it's a client bug or not).

EDIT: Seems every mob is affected by this, especially when they try to jump a block.
