### ISSUE TITLE
Server Hanging When Feeding Food to Animal

### ISSUE THREAD

**Issue by go626201** [PaperMC/Paper#1639]
###  Timings or Profile link:
https://timings.aikar.co/?id=938114871fda4792a313a1675020965b
https://timings.aikar.co/?id=25b9e6b2589e47b3a44f477698c909a6

### Description of issue:
Some performance issue about feeding food to animal,and the server will suddenly hanging for few second and may return to few second ago,and tps may drop to about 15.
Second timing tps drop also happens when i testing for feeding to animals only about 30 food,and tps drop to 14.x
This issue had been tested for 2days same result for same issue.

### Plugin list:
 Plugins (14): Announcements, AuthMe, BlockLocker, CoreProtect, dynmap, dynmap-mobs, LagMonitor, LuckPerms, MyPet, NoSpawnChunks, PlugMan, SkinsRestorer, TreeGravity, Vault

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://pastebin.com/kTTU7Cyb -bukkit.yml
https://pastebin.com/AJaQLCu0 -spigot.yml
https://pastebin.com/BsGmpLf8 -paper.yml
https://pastebin.com/wHvbEQuf -server.properties

### Other helpful links
I was having about 400++ animal at the same place,but the issue only happens when feeding.
The Server was host on a minecraft shared hosting,but quite low load.
![image](https://user-images.githubusercontent.com/9418861/47922237-87b3eb00-def1-11e8-80f8-96c7cb383c27.png)

### Paper build number:
Paper version git-Paper-413 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Lxct** [comment]
Please update to build 424 (to see if the problem persists)

**Comment by electronicboy** [comment]
`timingcost: 1235` that value should be within the 90-150 range, the value being that high is a sign that your CPU is heavily overloaded, and is likely to be the cause of the issue
Also, NoSpawnChunks could probably be replaced by disabling keeping spawn chunks loaded, that would probably save some time from that plugin

**Comment by go626201** [comment]
Is that possible cause by ram shortage? since i only having 512mb ram for the server,and so the server keep gc for release ram?
https://timings.aikar.co/?id=420a2be738d9432c917d1d0cbb75445c
Updated to version 425.

**Comment by astei** [comment]
I don't think the amount of memory you've allocated is playing a particularly large role here (although you need to be careful when running a server in 512MB). The problem, as @electronicboy has noted, is that whatever node your server is on is extremely overloaded.

Please find a different host.
