### ISSUE TITLE
Fast digging with eff4 was lagging and the blocks were rollbacking

### ISSUE THREAD

**Issue by LoToRTv** [PaperMC/Paper#1640]
###  Timings or Profile link:
Fast digging with eff4 was lagging and the blocks were rollbacking

### Plugin list:
0 plugin

### bukkit.yml, spigot.yml, paper.yml, server.properties
default

### Paper build number:
last

**Comment by aikar** [comment]
What paper version? last is not a version number.

**Comment by 0-x-2-2** [comment]
Timings are also probably needed because this is probably related to lag.

**Comment by Lxct** [comment]
> What paper version? last is not a version number.

417

**Comment by Lxct** [comment]
> Timings are also probably needed because this is probably related to lag.

I've got the same issue since paper 414. Only with haste or eff, no lags, 19.7 tps.

**Comment by LoToRTv** [comment]
tps ist ok... I used the version 407 and everything is cool

**Comment by electronicboy** [comment]
If it was broken in a recent build, we need to know what build broke it
exactly

**Comment by dexterlabs1** [comment]
Noticing block lag (breaking and placing) in 417. Eff IV shovels with dirt for example. Downgrading to 411 fixed the issue.

I didnt try going down one version at a time to see if the issue was fixed... Didnt appear to happen in 413, cant say for sure. Updates went like this 411 (No issues) -> 413 (unsure about the issue) -> 417 (Issue showed up FOR SURE) -> 411 (fixed)

**Comment by deadman96385** [comment]
413 didn't have the issue

**Comment by Lxct** [comment]
It's since 414

**Comment by electronicboy** [comment]
The changes in 414 have been reverted in 416, only changes since then have only been changes to entity movement
Do you have a timings report? If the server was held up, it would show up in there

**Comment by delet-this** [comment]
I also have this issue on the latest build, downgraded to 411 and it's fine again. The lag is most noticeable with like efficiency iv shovel. I noticed there is no lag in creative mode. I don't get any TPS loss when this happens

Edit:
Im pretty sure this is the commit that broke it:
https://github.com/PaperMC/Paper/commit/645cfad6658d383c621d83624fcea614222cb54a

**Comment by aikar** [comment]
@electronicboy 414 also contained the change that is clearly the culprit, as @delet-this mentioned.

**Comment by aikar** [comment]
Confirmed it was not that commit, was my entity movement one. Build 420+
