### ISSUE TITLE
Dogs, cats and parrots cannot be set down by right-click

### ISSUE THREAD

**Issue by WELTEINZ** [PaperMC/Paper#1641]
### What behaviour is expected:
Right-click on dogs, cats and parrots to make them sit down

### What behaviour is observed:
Dogs, cats and parrots cannot be set down, and following me

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
DiscordSRV-Build-1.16.4.jar
Dynmap-3.0-beta-2-spigot.jar
CoreProtect-2.15.1.jar

### Paper build number:
416

### Anything else:
411 solved the problem. Thanks to Z750!

**Comment by aikar** [comment]
417 fixed this issue earlier today...
