### ISSUE TITLE
Blocks don't spawn any drops when broken with nothing in your hand.

### ISSUE THREAD

**Issue by KarlOfDuty** [PaperMC/Paper#1642]
### What behaviour is expected:
Block breaks, player gets drops.

### What behaviour is observed:

< Check image below >

Block breaks but nothing is dropped. Error in picture appears in console.

### Steps/models to reproduce:
A player just goes up to a block, breaks it, and the error appears in the console with no drops. ~~It only affected a small amount of players and continued after relogging.~~ The issue is not present in build 418.

Happens only when not holding an item in your hand in survival mode while breaking the block.

### Plugin list:
AdvanceRespawn*, AltFinder*, ChatControl, CoreProtect, DiscordSRV, DropSpawner, DungeonsXL, dynmap*, Dynmap-Towny*, EMCRails, Essentials, EssentialsAntiBuild*, FastAsyncWorldEdit*, FirstJoinPlus*, HolographicDisplays, LightingFix, LiteBans, LuckPerms*, mcMMO, mcMMO-Towny*, mcMMOAction, MobFarmManager, OpenInv*, Orebfuscator4, Plan*, PlayTime*, ProtocolLib*, QuickShop, RFChairs, spark*, SpigotPing*, SuperbVote, TheNewEconomy, Towny*, TownyChat*, TownyNameUpdater*, TrailGUI*, Vault*, Votifier, WDLCompanion*, Wild, WorldBorder, ZombiePigmanDropRemover*

Update: Also with no plugins installed.

### Paper build number:
Paper version git-Paper-420 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by KarlOfDuty** [comment]
![image](https://user-images.githubusercontent.com/18099825/47949605-8234c000-df46-11e8-8f08-c11a7bd64343.png)

**Comment by KarlOfDuty** [comment]
I grabbed one of the players this happened to and took him over to another server also running 420 (both of us joining for the first time), it had the same effect when breaking sugar cane but after breaking dirt for a while it seems to have corrected itself.

He then relogged and had the same issue again upon joining.

I gave him a silk touch diamond pickaxe as the error above mentions enchantments and it seems like it fixes the issue instantly.

**Comment by KarlOfDuty** [comment]
I have now narrowed the issue down to breaking things without holding an item in your hand. It happens to everyone, it was just that a few of the testers had items when they tried before. It is present without any plugins too. (Editing the original post with this info)

**Comment by zachbr** [comment]
Should be fixed in builds 421+
Thanks

**Comment by KarlOfDuty** [comment]
Yup, I can confirm it's fixed.
