### ISSUE TITLE
Pigman aggro not working correctly

### ISSUE THREAD

**Issue by Decme** [PaperMC/Paper#1643]
Running the latest Paper jar #424, pigmen no longer behave normally. When you aggro a pigman, other nearby pigman ignore you, and the one you aggroed tends to forget that you hit him after a few moments.

Plugins (13): BestViewDistance, ChatEx*, CoreProtect, DiscordSRV, dynmap*, Dynmap-WorldGuard*, Essentials*, NameColors*, OnDeathCoord*, PermissionsEx*, Vault*, WorldEdit, WorldGuard

**Comment by Lxct** [comment]
Same on my server. Pigmens also follow you very, very slowly.
Build : paper 424

**Comment by aikar** [comment]
Likely was caused by the movement merge patch, which I have now removed from Paper.

I can not reproduce on Paper 425+. Please reopen with more reproduce steps (and without plugins) if it still occurs 425+

**Comment by Decme** [comment]
Can confirm the issue is now fixed.
