### ISSUE TITLE
[From Spigot 1.13 to Paper 1.12.2] getClientViewDistance() API

### ISSUE THREAD

**Issue by Lxct** [PaperMC/Paper#1644]
**Is your feature request related to a problem? Please describe.**
Spigot just added this feature yesterday to Spigot 1.13 : 
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#getClientViewDistance--
I was wondering if you can apply it to paper 1.12.2.

**Describe the solution you'd like**
=> player.getClientViewDistance() return an int with client setting view distance.

**Describe alternatives you've considered**
Using protocollib ?

**Additional context**
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#getClientViewDistance--
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/9d0221aa2959e79a315d7f87edd9d82e3ee7ce43

**Comment by BillyGalbreath** [comment]
If you look at the [CraftBukkit source](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/96c461b3a528611ab4d4e22d71c63e10f9a1d034#nms-patches/PacketPlayInSettings.patch) you will see all it's doing is getting the first int field from the settings packet. In 1.13 and 1.12 this is the `b` field. ProtocolLib can be used just fine to obtain this information (and might even have a wrapper for it already). ;)

**Comment by Lxct** [comment]
It would be nice not to depend on protocollib

**Comment by zachbr** [comment]
1.12.2 is feature frozen. So this won’t be happening.

**Comment by MiniDigger** [comment]
@Lxct  use the paper api
https://papermc.io/javadocs/org/bukkit/entity/Player.html#getViewDistance--
iirc that gets initialized with whatever the client has set and then you can override it via setViewDistance

**Comment by aikar** [comment]
@MiniDigger that API is not the same thing, and does not prepopulate from client settings.
Would be a nice option to provide "use client distance of lower than servers" if someone wants to PR to 1.13.2 :P
