### ISSUE TITLE
too fast block placing

### ISSUE THREAD

**Issue by vaniron** [PaperMC/Paper#1645]
### What behaviour is expected:
player places block that remains on his place

### What behaviour is observed:
player places block but it remains in players inventory but its also visible as placed, on click it immediately disappers from the world

### Steps/models to reproduce:
Just place few block very quickly, bug doesnt appear when placing blocks slowly.

### Plugin list:
irrelevant - same plugins for several weeks, problem will be in latest spigot/paper updates

### Paper build number:
426 1.13.2

**Comment by vaniron** [comment]
Update:
Problem was created by me editing paper.yml and setting incoming-packet-spam-threshold to 3000, setting it back to 300 resolves this issue.

**Comment by aikar** [comment]
Sounds like you found the problem
