### ISSUE TITLE
texture pack bypassing antixray

### ISSUE THREAD

**Issue by vaniron** [PaperMC/Paper#1646]
### What behaviour is expected:
no texture pack should be able to bypass antixray

### What behaviour is observed:
this one is able to bypass it

### Steps/models to reproduce:
download and activate this pack, you are ready to go

### Paper build number:
426

### Anything else:
This xray pack is able to bypass antixray protection even if it is set to mode 2. Other xray packs works only if antixray is disabled and are unable to bypass the protection.
https://www.dropbox.com/s/amyb53sgp6prckw/BeastX%20X-Ray%20v1.1.1%20%5BMinecraft%201.13%5D.zip?dl=1

**Comment by prplz** [comment]
Is it only exposed (eg in caves) ores that you can see?

**Comment by vaniron** [comment]
Nope, even those hidden behind stone.

Using this settings:
anti-xray:
      enabled: true
      engine-mode: 2
      chunk-edge-mode: 1
      max-chunk-section-index: 4
      update-radius: 3
      hidden-blocks:
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - redstone_ore
      - lit_redstone_ore
      - clay
      - emerald_ore
      - ender_chest
      replacement-blocks:
      - stone

**Comment by Royster-85** [comment]
Can you post some screenshots between the version you were using before updating to ver. 426? Only because I updated to ver. 426 from ver. 425, used the x-ray texture pack mentioned above and I cant see any ores hidden behind stone. Any that have one surface exposed to air I can still see, but I dont think its possible to hide those as they're already exposed

**Comment by GamerGlitz** [comment]
I tried generating a world without caves, and I dug straight down. Unfortunately I couldn't see any unexposed ores so it seems like this isn't a real XRay pack and so it isn't really detectable.

**Comment by stonar96** [comment]
I will try this later. You can try to use `chunk-edge-mode: 2` or `3`. You might see ores from chunk edges. Also note that `update-radius: 2` is the maximum but this won't change anything.

**Comment by zachbr** [comment]
Should be resolved in latest builds of 1.13.2

**Comment by bretwak6-maker** [comment]
hi
