### ISSUE TITLE
Tons of errors and the server stopped responding at the end

### ISSUE THREAD

**Issue by SincerelyFaust** [PaperMC/Paper#1647]
### Link/paste of stack trace

https://hastebin.com/uzususeziz.shell

### Plugin list:
https://imgur.com/XuH5OGj

### Actions to reproduce (if known):
No clue

### Paper build number:
425

**Comment by electronicboy** [comment]
Timings? Looks like you have plugins clogging up the scheduler

**Comment by SincerelyFaust** [comment]
https://timings.aikar.co/?id=0ec8fe5d6a144f9a959617379541d51b

EDIT: Got some more tasty errors
https://hastebin.com/odanojigij.shell

**Comment by zachbr** [comment]
Reply with additional information or come visit us in discord for a more immediate response https://discord.gg/papermc
