### ISSUE TITLE
1.13.2 Looking for Cause of TPS Loss

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#1649]
###  Timings or Profile link:
https://timings.aikar.co/?id=6de7165506bc466db8365ebc23528573

### Description of issue:
Server lag and TPS loss, vanishes suddenly. So far unexplained.

### Plugin list:
https://i.imgur.com/dT3xjoS.png

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://pastebin.com/spaJDheU

### Paper build number:
04.11 18:11:54 [Server] INFO This server is running Paper version git-Paper-407 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
04.11 18:11:54 [Server] INFO Previous version: git-Paper-392 (MC: 1.13.2)
04.11 18:11:54 [Server] INFO You are 19 version(s) behind

### Notes:
Behind a few versions. Updating tomorrow. (edit: updated at 6am UTC to build 426. waiting on a better sample of data).

Vehicles move slow almost all the time. Otherwise the lag is only noticeable when TPS loss >70%

**Comment by 0-x-2-2** [comment]
I believe it is related to mine-carts as there is 2000+ in one region but I not really sure.

**Comment by NullCase** [comment]
And 1000+ skeleton horses in another region....?

The number of entities is probably being multiplied by the # of times the region is loaded.

Region visited 13x. Look at how many entities are an exact multiple of 13.

**Comment by NullCase** [comment]
In region 0,0 all of the following entities exist as exact multiples of the # of times the region is visited..

edit: actually this is roughly stated on the page: 

> They are a representation of number of times seen within this selected history window.
They will be much higher than seen in game. It is intended to help you identify where the most TE/E's are.

BEACON:
BLACK_SHULKER_BOX:
BREWING_STAND:
DRAGON_WALL_HEAD:
JUKEBOX:
PINK_WALL_BANNER:
TRAPPED_CHEST:
YELLOW_SHULKER_BOX:
EXPERIENCE_ORB:
ZOMBIE_VILLAGER:
BLUE_SHULKER_BOX:
BROWN_BED:
ENCHANTING_TABLE:
GREEN_BED:
LIGHT_GRAY_BED:
LIME_BED:
YELLOW_BED:
RED_WALL_BANNER:
BLUE_BED:
RED_BED:
PARROT:
MINECART_HOPPER:
LLAMA:
SIGN:
DROPPER:
DISPENSER:
WHITE_BED:
WOLF:
OCELOT:
RABBIT:
COMPARATOR:
LIGHT_GRAY_SHULKER_BOX:
DAYLIGHT_DETECTOR:
ENDER_CHEST:
PIG:

**Comment by LogGits** [comment]
Try updating ur paperspigot buid to the latest.

**Comment by NullCase** [comment]
OK, generating new chunks (end city raiding) is a legitimate contender. From 8:30 - 8:40

https://timings.aikar.co/?id=5769501d4c5c4643b84927b50919556e

**Comment by NullCase** [comment]
Lag has improved after updating to build 441.

https://papermc.io/ci/job/Paper-1.13/441/
