### ISSUE TITLE
"Silently" catching entity tracking error.

### ISSUE THREAD

**Issue by SmallSansSerif** [PaperMC/Paper#165]
[18:01:08] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_9_R1.ReportedException: Adding entity to track

Error in console in Paper build 606. See the pastebin below:
http://pastebin.com/cvQFA1qP

Saw this was reported elsewhere 5 days ago too: https://github.com/PaperMC/Paper/issues/136

**Comment by zachbr** [comment]
Then please keep that issue going, avoid duplicates if possible. It makes it harder for us to track the status of issues if they're spread all around. Please just copy-pasta this over to #136 please, thanks :)
