### ISSUE TITLE
Random server crashes

### ISSUE THREAD

**Issue by tomasloksa** [PaperMC/Paper#1650]
### Link/paste of stack trace

https://pastebin.com/qD2dGHXq - first one today

https://pastebin.com/G5Lti5gV - second one

### Plugin list:

Plugins (38): AdvancedPortals, AreaShop, ASkyBlock, AuthMe, BedwarsRel, BuycraftX, ClearLag, CommandSigns, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, HolographicDisplays, Jobs, LibsDisguises, Multiverse-Core, MultiVIP, MySkin, NoCheatPlus, OpenInv, PermissionsEx, PerWorldInventory, PowerlessLamps, ProjectileDamage, ProtocolLib, pvparena, Residence, ShopChest, SurveyPlugin, SurvivalGames, TAB, UltraCosmetics, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard

### Actions to reproduce (if known):

Server crashes randomly (every few hours) without any prior errors or unusual events hapenning.

### Paper build number:

git-Paper-1574 (MC: 1.12.2)

**Comment by zachbr** [comment]
If this is something you're still seeing regularly with an updated build and plugins please reply here and we'll re-open this ticket.
