### ISSUE TITLE
Minecarts randomly disappearing

### ISSUE THREAD

**Issue by brickery** [PaperMC/Paper#1651]
My server admin recently posted on the Discord asking for help, we were told to submit this as a bug report:

### What behaviour is expected:
Using Paper as an SMP server, we want to mimic vanilla survival mechanics as closely as possible, however we have been receiving player reports that minecarts are disappearing at random.

### What behaviour is observed:
Minecarts (hopper, and regular; moving, and stationary; on rail, and off rail) disappear. It seems like they are turning into minecart items and despawning. 

### Steps/models to reproduce:
A test was done where stationary minecarts are placed above each other on separate blocks. Most of the time, only 1 or 2 disappear while the rest remain.

### Plugin list:
Plugins (29): Actionbar, BelovedBlocks, BungeeTabListPlus, ColoredAnvils, CoreProtect, DeathMessagesPrime, DiscordSRV, Essentials, EssentialsGeoIP, EssentialsSpawn, Holograms, HubKick, LagMonitor, LuckPerms, Multiverse-Core, MySkin, NotifyUser, PlaceholderAPI, ProtocolLib, PvPManager, SimpleBackup, TitleManager, Vault, VentureChat, ViaBackwards, ViaVersion, Whitelist, WorldEdit, WorldGuard
(No lag clearing plugins)

### Paper build number:
git-Paper-1584 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) (2 versions behind)

### Anything else:
We have ruled out chunk loading and unloading as when we do the test stated above, only 1 or 2 minecarts disappear while the others remain.

**Comment by WesleyVanNeck** [comment]
same on 1.13

latest

**Comment by MatrixTunnel** [comment]
I am also experiencing this and have observed boats doing the same thing (but more rarely)

**Plugin list:**
Plugins (3): ChopTree3, CoreProtect, GarbageCollector

**Paper build:**
git-Paper-1586 (MC: 1.12.2)

**Comment by APimpNamedShane** [comment]
I have experienced this quite a bit. Boats and minecrafs disappear for no reason. I run Paper 1.12.2 and the common plugin I'm seeing is coreprotect. Somehow my villagers have become invincible as well. Seems odd, and I was ready to blame my host until I found this post.

**Comment by zachbr** [comment]
I'm pretty sure we're still getting occasional reports of this, if someone could confirm in writing here that'd be appreciated.

**Comment by RedStoners85** [comment]
I experienced this on my paper server running Paper-142 Minecraft 1.15.2. I went through the console and no commands were run to kill the minecarts.

**Comment by alebcay** [comment]
I believe I'm seeing this too. No console logs/messages regarding the disappearances either. Technically on Tuinity, but I'm not aware of this issue happening there specifically, while it has been reported here.

```
Tuinity version git-Tuinity-"0729373" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

**Comment by Hlebuw3k** [comment]
On my server the minecarts just keep dissapearing for a LOT of players, we ruled out lighting because people have lighting rods away from the minecarts. Running Minecraft Paper 1.18.2 with CoreProtect as one of the plugins.

**Comment by sam51210** [comment]
Still having it.

**Comment by mbax** [comment]
@sam51210 this issue is 8 years old, from a *very* different version of the server. I imagine any issue from back then wouldn't be the same as you're experiencing. 
Additionally, the lack of any substantial reports in the mean time suggests to me that this may be a plugin issue. Visit #paper-help on the PaperMC discord server for advice narrowing it down.
