### ISSUE TITLE
Armor-stands-tick option: Differentiation between armor stands with and without base plate

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#1654]
Hej,

it would be wonderful if you could distinguish between armor stands with and without base plate in the armor-stands-tick option. If the armor-stands-tick option is set to false, only armor stands without base plates should be affected so that the default armor stands maintain their normal behaviour and still fall.

Why would this be a sensible option for the majority?
Well on most servers the majority of the armor stands and therefore also the part that affects the performance is generated by plugins or command blocks. Using armor stands as decoration is becoming more and more popular. For you to be able to imagine what I mean, I have arranged a few example pictures: https://imgur.com/a/bhtkXqi

In a subordinate role in terms of performance, invisible armor stands are also increasingly used in redstone circuits to be able to execute other commands on their position/on them. These facts make it more and more important to be able to set the armor-stands-tick to false to spare performance. The crucial point is that the relevant part of armor stands does not have a base plate. 

A single player, however, still likes to set up his one or two armor stands in his house, which are insignificant in terms of performance. He loves to move them for custom clothes racks with pistons and slime blocks and to be able to do all sorts of other weird stuff with them. It is certainly in the interest of many server administrators to be able to save an incredible "amount" of performance without harming the normal gaming experience. This goal could be achieved by using the armor-stand-tick only on armor stands without a base plate. 

I hope I have made it obvious that this is not just a super special solution for a random guy, but an improvement that would be welcomed by many paper users. I would be pleased if you could at least consider adding this point to your to-do list. Keep up your great work :)

Best regards

**Comment by kashike** [comment]
Use a plugin for this. We're not going to add a configuration option for every possible scenario.
