### ISSUE TITLE
This is outrageous, I need serious help (miles of errors)

### ISSUE THREAD

**Issue by SincerelyFaust** [PaperMC/Paper#1655]
### Link/paste of stack trace
https://hastebin.com/exagukowid.md

### Plugin list:
https://imgur.com/XuH5OGj

### Actions to reproduce (if known):
At a random time it just goes nuts and spits out all those errors

### Paper build number:
425

**Comment by aikar** [comment]
crazyauctions plugin is causing your issue.

**Comment by SincerelyFaust** [comment]
Thank you, master.
