### ISSUE TITLE
Villagers disappear by chance or lose their tradability at maximum trading level

### ISSUE THREAD

**Issue by WELTEINZ** [PaperMC/Paper#1658]
### What behaviour is expected:
No disappearance of Villagers, furthermore the possibility of trading at maximum trading level of Villager.

### What behaviour is observed:
After the **conversion** from Spigot 1.12.2 to Paper 1.13.2 dev 416 a Mending Villager disappeared and a handful of the Villagers (maximum trading level) with which you could trade before are no longer able to do so. The trading window opens and closes shortly afterwards.

### Plugin list:
Dynmap v3.0-beta-2
DiscordSRV 1.16.4

### Paper build number:
dev 417

**Comment by WELTEINZ** [comment]
Thanks, I'll test that tonight and give you a feedback. Btw you commented on the wrong issue.. >>> #1656

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
