### ISSUE TITLE
Multicraft ratelimit bug

### ISSUE THREAD

**Issue by FrankHeijden** [PaperMC/Paper#1659]
### What behaviour is expected:
Normal behaviour with multicraft, just like spigot

### What behaviour is observed:
Multicraft is skipping lines while its not exceeding its actual rate limit

### Steps/models to reproduce:
Multicraft + paper

### Paper build number:
git-Paper-432

### Anything else:
Spigot does not have this problem, switched to paper and had this issue immediately.

**Comment by aikar** [comment]
You will have to take this up with multi craft. We have no control over its logic and if it is due to our logging changes, it's still up to multicraft to fix it
