### ISSUE TITLE
Drowned behavior and pathfinding

### ISSUE THREAD

**Issue by Decme** [PaperMC/Paper#1662]
### What behavior is expected:
In vanilla:
Drowned will track/aggro on turtle eggs during the day.
Drowned will pathfind to water source blocks if they're out of water.

### What behavior is observed:
In Paper:
Drowned only track/aggro on eggs at night.
Drowned will wonder aimlessly if they're out of water.

### Steps/models to reproduce:
Spawn some eggs & Drowned in creative and /time set day

### Plugin list:
ChatEx*, CoreProtect, DiscordSRV, dynmap*, Dynmap-WorldGuard*, Essentials*, NameColors*, OnDeathCoord*, PermissionsEx*, Vault*, WorldEdit, WorldGuard

### Paper build number:
426

**Comment by zachbr** [comment]
Still occurring on recent builds?

**Comment by Chew** [comment]
Author hasn't responded for over a year, and no other reports have been filed about this, if you are still experiencing this issue on a supported version, feel free to open a new issue. Have a good day!
