### ISSUE TITLE
Sponges Causing Crashes

### ISSUE THREAD

**Issue by BiGUNMAN** [PaperMC/Paper#1663]
### Link/paste of stack trace
https://hastebin.com/kinihevuho.rb

### Plugin list:
https://i.imgur.com/at4R6qh.png

### Actions to reproduce (if known):
Not sure, a player was messing around with sponges and then instantly crashed the server. Now everytime they rejoin at the location where they were using sponges, the server instantly crashes. If I teleport to their location, I instantly crash the server as well.

@WindUnwaken had a very similar issue, and posted it here: https://github.com/PaperMC/Paper/issues/1660 (user is experiencing a separate issue here). Here's a diff-checker of the crash report Wind and I posted (probably don't need it but I already have it anyways): https://www.diffchecker.com/U4WYUkJG

> [crash.txt](https://github.com/PaperMC/Paper/files/2564834/crash.txt)
> Using sponge and tried to clear water causing this, turn back to version 427 fixed this.

**EDIT:** I can confirm that downgrading to version 427 fixes this.

### Paper build number:
428

**Comment by WindUnwaken** [comment]
Paper 428 change blockfixer, probably related to thread,

I run my server on vps which have 6vcpu and centos7, java8-191

**Comment by okx-code** [comment]
I'm still having this issue on Paper 437.
https://gist.github.com/okx-code/012b8993ab4de1970006a22fe612659f

**Comment by electronicboy** [comment]
Should be fixed in 438+
