### ISSUE TITLE
12 tps - 130 players

### ISSUE THREAD

**Issue by BiGUNMAN** [PaperMC/Paper#1664]
###  Timings or Profile link:
Timings (12 tps, 130 players): https://timings.aikar.co/?id=e0b01efc0453426886efcbc3ae908513

VisualVM Snapshot: https://drive.google.com/file/d/1Doqv_hXkCXfkLy7ypMlsHMH6pFClhvgg/view?usp=sharing 

### Description of issue:
Horrible lag that doesn't seem to be caused by a plugin at 70-80+ players.

### Plugin list:
https://i.imgur.com/z2M7IEs.png

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml: https://paste.ee/p/0lgJ1
spigot.yml: https://paste.ee/p/nDXlB
paper.yml: https://paste.ee/p/zf6ev
server.properties: https://paste.ee/p/45Vh7

### Other helpful links
Been piling info here: https://papermc.io/forums/t/lag-at-70-players-please-help-dad/215, I've put the newest info in this Github and the bottom of the forum post.

### Paper build number:
427

**Comment by zachbr** [comment]
Lots of performance changes and improvements have landed since this ticket was created.
Going to invite you to join the discord at https://discord.gg/papermc if you're still seeing this.
