### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1665]
### Link/paste of stack trace

https://pastebin.com/xQfCWeU9

### Plugin list:
EssentialsX-2.15.0.55
EssentialsXChat-2.15.0.55
EssentialsXSpawn-2.15.0.55
WildTP
worldedit-bukkit-7.0.0-beta-01
worldguard-legacy-7.0.0-beta-01

### Actions to reproduce (if known):
Unable to reproduce. This happened when I was not on the server. I'm not sure what caused it.

### Paper build number:
429

**Comment by electronicboy** [comment]
Please update and provide the full log file, you've also seemingly disabled the periodic warnings for the server not ticking in a period of time, this needs to be enabled for us to provide support with these types of issues

**Comment by electronicboy** [comment]
Should be fixed in the latest build
