### ISSUE TITLE
Add support for player joining server on outdated client or server.

### ISSUE THREAD

**Issue by EOT3000** [PaperMC/Paper#1666]
Sorry, I don't know how else to name it, but could you handle a 1.13 player, for example joining a 1.13 server differently. Instead of writing outdated client, make the player join the server because there is almost absolutely no difference between 1.11 and 1.13.1. But it still says outdated server, or outdated client.

**Comment by zachbr** [comment]
No

**Comment by EOT3000** [comment]
sorry, I made a mistake in description. I wrote 1.11 when I meant 1.13

**Comment by zachbr** [comment]
Answer is still no, use a plugin for this if you want it.

**Comment by EOT3000** [comment]
ok
