### ISSUE TITLE
LootableInventoryReplenishEvent call for first refill.

### ISSUE THREAD

**Issue by Parozzz** [PaperMC/Paper#1667]
I was working with Lootables inventories and seems like the LootableInventoryReplenishEvent is not called for the first refill. Is this something intentional?
https://gist.github.com/Parozzz/979e82822d758c2dca98c9178a054367

If this is something intentional, can another event be called for that specific moment? Otherwise i have no control over lootables inventory for the first refill.

Otherwise i would need to use nms, use the PlayerInteractEvent to check when a player interact with a Lootable container and check the PaperLootableInventoryData by myself, but the feature above would be nice.

**Comment by BillyGalbreath** [comment]
The event is cancellable, but the first fill is required to *always* fill. Plus, the first fill technically isn't a "replenish", as that implies it previously was filled.

**Comment by Parozzz** [comment]
Still, my question remain. Maybe add an event for the first fill?
