### ISSUE TITLE
Block#breakNaturally enhancement

### ISSUE THREAD

**Issue by crysis992** [PaperMC/Paper#1668]
The javadocs for [block#breakNaturally(ItemStack tool) ](https://papermc.io/javadocs/org/bukkit/block/Block.html#breakNaturally-org.bukkit.inventory.ItemStack-)does not respect enchantments that are on the given tool, nor does it reduce durability or drop experience for like coal/diamond ore.
And the javadocs are a bit misleading.

My suggestion is to add another method like Block#breakNaturally(ItemStack tool, boolean respectEnchantments) to correctly apply the enchantments on the tool, drop experience and reduce the durability of the ItemStack.

**Comment by electronicboy** [comment]
Would probably be better off on Player, given that you *need* to provide a Player to the code which does all of this, which then also increments statistics, etc... It's not really something that's built in a way that's ideal to expose in API

**Comment by hugmanrique** [comment]
Btw, they are adding a Vanilla command to do exactly this in 1.14, so I assume it will be relatively easy to expose the NMS method in the future.

**Comment by Machine-Maker** [comment]
Player has `breakBlock` which runs all the logic to simulate a player block break, the event, xp, drops, enchants, effects, etc. I think that should suffice for this?
