### ISSUE TITLE
Pathfinding is taking too long still

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#1669]
###  Timings or Profile link:
https://sparkprofiler.github.io/?hkiaD8VO5Z

### Description of issue:
Looks like pathfinding is taking too long

### Plugin list:
Custom, nothing notable. Mostly vanilla.

### bukkit.yml, spigot.yml, paper.yml, server.properties
Default

### Paper build number:
Paper 440

**Comment by MiniDigger** [comment]
mmmh, looks like the raytraycing of PathfinderGoalNearestAttackableTarget does a sync chunk load. not sure if thats avoidable.

**Comment by aikar** [comment]
I think it is, if you hit an unloaded chunk, it should cancel the ray trace as a fail in same way a limit was hit.

**Comment by hurrgurl** [comment]
Should be fixed now,

Thank you! ^_^
