### ISSUE TITLE
Expose different heightmaps in the api

### ISSUE THREAD

**Issue by Shevchik** [PaperMC/Paper#1672]
Starting from 1.13 minecraft server now stores different heightmaps, not just light blocking. It may be useful to expose them.
May be adding an overload of method getHigestBlockAt with type.

**Comment by aikar** [comment]
def a good idea, and i want to change the damn height map spigot used, as it isn't the correct one that the Bukkit API expects.... mojang uses a different map for the same type of check.

**Comment by Shevchik** [comment]
Changing the current getHighestBlockAt used map is bad idea IMO, because many people actually expect it to return the highest light blocking block.

P.S. Also might be worth actually using this map in the tileentitybeacon and erase useless beam color calculation.

**Comment by Spottedleaf** [comment]
It can't be used in the calculation as the beacon colour is determined by accumulating stained glass colours. It can only be used for checking whether the calculation is possible (highest block == stained glass)
