### ISSUE TITLE
Crash 14-11-2018

### ISSUE THREAD

**Issue by Roshanxy** [PaperMC/Paper#1673]
### Link/paste of stack trace
https://pastebin.com/K3WNArxL
### Plugin list:
Cartel
Citizens
CoreProtect
Fawe
Essentials
Factions
FastAsyncWorldEdit
GriefPrevention
HorseTPWithMe
Images 
MassiveCore
PermissionsEx
RealisticTime
ServerMinimap
SkinsRestorer
Vault
WildTP
### Actions to reproduce (if known):
I literally have no clue on why it happened, the server was quite calm when it happened. 
### Paper build number:
 This server is running Paper version git-Paper-442 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Black-Hole** [comment]
A player sent a move packet with a distant destination.
You could try to set "prevent-moving-into-unloaded-chunks" to "true" in the paper.yml file.

**Comment by Roshanxy** [comment]
> A player sent a move packet with a distant destination.
> You could try to set "prevent-moving-into-unloaded-chunks" to "true" in the paper.yml file.

Thank you for the reply. I shall edit this in the config.

**Comment by Black-Hole** [comment]
Just restart the server.
