### ISSUE TITLE
Lighting Issues (Specifically in Mob Farms)

### ISSUE THREAD

**Issue by jvanis** [PaperMC/Paper#1675]
### What behaviour is expected:
Mob farms are built with multiple diamond shaped platforms, a roof is created over them to ensure Light Level 0 during all times of the day.  Farm will run and spawn mobs.

### What behaviour is observed:
Farm will work for a period of time, unsure of when it stops working exactly, typically after leaving the chunk or logging out, it will then have random block lighting issues where spawn platforms receive Sky light and stop spawning mobs.  

### Steps/models to reproduce:
Using a standard diamond shaped platform with water dispenser in the middle, large slab (or block) roof over the top  

### Plugin list:
DiscordSVR, LuckPerms, LWC, CoreProtect

### Paper build number:
442(Was happening on 425 as well I know for certain)

### Anything else:
We were able to fix one by extending the roof to much larger than normally required, but it then came back as an issue the next day.

**Comment by zachbr** [comment]
Please either link timings or paste every single config, `server.properties`, `bukkit.yml`, `spigot.yml`, and `paper.yml`

**Comment by jvanis** [comment]
Timings https://timings.aikar.co/?id=b83e92477eb84e8db71e1aa17a082c71

**Comment by zachbr** [comment]
Lots of changes in lots of areas that could touch this. If this is something you're still seeing on **fresh** builds and block updates please reply here, I will re-open the ticket.

Note that lighting will randomly relight but the only way to guarantee an attempt to relight is to trigger updates on the affected blocks and in the area.
