### ISSUE TITLE
Server Crash : Should always be able to create a chunk

### ISSUE THREAD

**Issue by NipoCN** [PaperMC/Paper#1677]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/15/18 11:28 AM
Description: Ticking player

java.lang.IllegalStateException: Should always be able to create a chunk!
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:392)
	at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:385)
	at net.minecraft.server.v1_13_R2.World.b(World.java:826)
	at net.minecraft.server.v1_13_R2.Entity.a(Entity.java:1293)
	at net.minecraft.server.v1_13_R2.EntityHuman.dg(EntityHuman.java:214)
	at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:161)
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:403)
	at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:432)
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1440)
	at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:347)
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:154)
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1129)
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:392)
	at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:385)
	at net.minecraft.server.v1_13_R2.World.b(World.java:826)
	at net.minecraft.server.v1_13_R2.Entity.a(Entity.java:1293)
	at net.minecraft.server.v1_13_R2.EntityHuman.dg(EntityHuman.java:214)
	at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:161)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.v1_13_R2.EntityPlayer)
	Entity ID: 750704
	Entity Name: NJ_huaxin
	Entity's Exact location: -3051.44, 70.79, -12480.43
	Entity's Block location: World: (-3052,70,-12481), Chunk: (at 4,4,15 in -191,-781; contains blocks -3056,0,-12496 to -3041,255,-12481), Region: (-6,-25; contains chunks -192,-800 to -161,-769, blocks -3072,0,-12800 to -2561,255,-12289)
	Entity's Momentum: 0.00, -0.40, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:403)
	at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:432)
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1440)
	at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:347)
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:154)
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1129)
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Linux (amd64) version 3.10.0-862.9.1.el7.x86_64
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4976139040 bytes (4745 MB) / 7387742208 bytes (7045 MB) up to 7387742208 bytes (7045 MB)
	JVM Flags: 3 total; -Xms7168M -Xmx7168M -XX:+AggressiveOpts
	CraftBukkit Information: 
   Running: Paper version git-Paper-428 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) true
   Plugins: { CoreProtect v2.15.1 net.coreprotect.CoreProtect [Intelli], LevelHearts v1.4.8* com.zettelnet.levelhearts.LevelHeartsPlugin [Zettelkasten], Essentials vTeamCity* com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally], GroupManager v2.0.5* org.anjocaido.groupmanager.GroupManager [HappyAreaBean], EssentialsChat vTeamCity* com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], mcMMO v1.6.0-SNAPSHOT com.gmail.nossr50.mcMMO [nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking], WorldBorder v1.9.0 com.wimbli.WorldBorder.WorldBorder [Brettflan], HolographicDisplays v2.3.1 com.gmail.filoghost.holographicdisplays.HolographicDisplays [], Vault v1.7.1-b91* net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], EssentialsSpawn vTeamCity* com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], LaggRemover v2.0.4* drew6017.lr.main.LaggRemover [drew6017], Citizens v2.0.24-SNAPSHOT (build 1591) net.citizensnpcs.Citizens [aPunch, fullwall], ChestCommands v3.1.4* com.gmail.filoghost.chestcommands.ChestCommands [], Residence v4.8.3.1 com.bekvon.bukkit.residence.Residence [bekvon, nate302, t00thpick1], NPC_Destinations v2.3.1 net.livecar.nuttyworks.npc_destinations.DestinationsPlugin [Sir_Nutty@Spigot], PlotSquared v18.11.05-ae2869a-2051* com.plotsquared.bukkit.BukkitMain [Citymonstret, Empire92, MattBDev], Multiverse-Core v2.6.0-b738* com.onarandombox.MultiverseCore.MultiverseCore [Rigby, fernferret, lithium3141, main--, dumptruckman], EliteMobs v6.6.0* com.magmaguy.elitemobs.EliteMobs [MagmaGuy], MyPet v3.0 de.Keyle.MyPet.MyPetPlugin [Keyle], EliteMobsCitizen v1.0* au.com.grieve.elitemobscitizens.EliteMobsCitizens [Bundabrg],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Log4j2-TF-1-AsyncLogger[AsyncContext@33909752]-1: [java.lang.Object.clone(Native Method), java.lang.Throwable.getStackTrace(Throwable.java:816), org.apache.logging.log4j.core.impl.ThrowableProxy.getStackTrace(ThrowableProxy.java:466), org.apache.logging.log4j.core.impl.ThrowableProxy.formatThrowableProxy(ThrowableProxy.java:224), org.apache.logging.log4j.core.impl.ThrowableProxy.formatCause(ThrowableProxy.java:211), org.apache.logging.log4j.core.impl.ThrowableProxy.getExtendedStackTraceAsString(ThrowableProxy.java:444), org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:68), org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38), org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:455), org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:232), org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:217), org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57), org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177), org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170), org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161), org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:218), org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156), org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129), org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120), org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84), org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448), org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433), org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417), org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:79), org.apache.logging.log4j.core.async.AsyncLogger.actualAsyncLog(AsyncLogger.java:337), org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161), org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45), org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29), com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168), com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Thread-17: [java.lang.Thread.sleep(Native Method), net.coreprotect.consumer.Consumer.run(Consumer.java:105), java.lang.Thread.run(Thread.java:748)], WAITING PaperChunkLoader-6: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1731/1022041976.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], WAITING PaperChunkLoader-2: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1731/1022041976.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Timer-1: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1610), org.bukkit.craftbukkit.v1_13_R2.CraftCrashReport.call(CraftCrashReport.java:32), net.minecraft.server.v1_13_R2.CrashReportSystemDetails.a(SourceFile:79), net.minecraft.server.v1_13_R2.CrashReport.h(CrashReport.java:66), net.minecraft.server.v1_13_R2.CrashReport.<init>(CrashReport.java:34), net.minecraft.server.v1_13_R2.CrashReport.a(CrashReport.java:260), net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:480), net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:432), net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1440), net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:347), net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:154), net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1129), net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439), net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943), net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841), java.lang.Thread.run(Thread.java:748)], WAITING PaperChunkLoader-3: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1731/1022041976.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], WAITING Paper Async Task Handler Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Craft Scheduler Thread - 1747: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], RUNNABLE Craft Scheduler Thread - 531: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.socketRead(SocketInputStream.java:116), java.net.SocketInputStream.read(SocketInputStream.java:171), java.net.SocketInputStream.read(SocketInputStream.java:141), java.io.BufferedInputStream.fill(BufferedInputStream.java:246), java.io.BufferedInputStream.read1(BufferedInputStream.java:286), java.io.BufferedInputStream.read(BufferedInputStream.java:345), sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735), sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678), sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587), sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492), org.mcstats.MetricsLite.postPlugin(MetricsLite.java:368), org.mcstats.MetricsLite.access$3(MetricsLite.java:282), org.mcstats.MetricsLite$1.run(MetricsLite.java:177), org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63), org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52), com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING pool-10-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING PaperChunkLoader-4: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1731/1022041976.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], WAITING pool-9-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING ObjectCleanerThread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.lang.Thread.run(Thread.java:748)], WAITING PaperChunkGen-world_nether: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1731/1022041976.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], WAITING Craft Async Scheduler Management Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.util.TimerThread.mainLoop(Timer.java:526), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.lang.ref.Reference.tryHandlePending(Reference.java:191), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)], TIMED_WAITING Thread-16: [java.lang.Thread.sleep(Native Method), net.coreprotect.thread.CacheCleanUp.run(CacheCleanUp.java:15), java.lang.Thread.run(Thread.java:748)], RUNNABLE Netty Epoll Server IO #2: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], WAITING PaperChunkGen-Kanos: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1731/1022041976.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], RUNNABLE Netty Epoll Server IO #3: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], RUNNABLE Server console handler: [java.io.FileInputStream.read0(Native Method), java.io.FileInputStream.read(FileInputStream.java:207), org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:65), org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62), org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168), org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133), org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:786), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:558), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:404), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:157), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:140), net.minecraft.server.v1_13_R2.DedicatedServer$2.run(DedicatedServer.java:83)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_13_R2.DedicatedServer$1.run(DedicatedServer.java:66)], WAITING PaperChunkGen-EliteWorld: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1731/1022041976.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], RUNNABLE Signal Dispatcher: [], TIMED_WAITING Paper Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:137)], WAITING PaperChunkLoader-1: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1731/1022041976.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Craft Scheduler Thread - 2: [java.lang.Thread.sleep(Native Method), com.intellectualcrafters.plot.database.SQLManager$1.run(SQLManager.java:163), org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63), org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52), com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING PaperChunkLoader-5: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1731/1022041976.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_13_R2.FileIOThread.c(FileIOThread.java:57), net.minecraft.server.v1_13_R2.FileIOThread.run(FileIOThread.java:30), java.lang.Thread.run(Thread.java:748)], WAITING PaperChunkGen-world: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1731/1022041976.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], RUNNABLE DestroyJavaVM: [], RUNNABLE Netty Epoll Server IO #1: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], WAITING PaperChunkGen-world_the_end: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1731/1022041976.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING pool-12-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Abandoned connection cleanup thread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:64), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], RUNNABLE Craft Scheduler Thread - 364: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.socketRead(SocketInputStream.java:116), java.net.SocketInputStream.read(SocketInputStream.java:171), java.net.SocketInputStream.read(SocketInputStream.java:141), java.io.BufferedInputStream.fill(BufferedInputStream.java:246), java.io.BufferedInputStream.read1(BufferedInputStream.java:286), java.io.BufferedInputStream.read(BufferedInputStream.java:345), sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735), sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678), sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587), sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492), com.plotsquared.bukkit.util.Metrics.postPlugin(Metrics.java:259), com.plotsquared.bukkit.util.Metrics.access$000(Metrics.java:23), com.plotsquared.bukkit.util.Metrics$1.run(Metrics.java:174), org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63), org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52), com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)],}
   
	Profiler Position: N/A (disabled)
	Player Count: 2 / 100; [EntityPlayer['Svnnynight'/728187, uuid='5905fe91-6739-4f94-a043-a978c9001ada', l='world', x=1024.61, y=67.00, z=-1002.30, cx=64, cz=-63, tl=802117, v=true, d=false](Svnnynight at 1024.610685061216,67.0,-1002.3005731421872), EntityPlayer['NJ_huaxin'/750704, uuid='6a19cedd-b780-4ef1-ab2b-ff800e2d71f8', l='EliteWorld', x=-3051.44, y=70.79, z=-12480.43, cx=-191, cz=-780, tl=5875971, v=true, d=false](NJ_huaxin at -3051.4401476252838,70.79009373816204,-12480.433634274706)]
	Data Packs: vanilla, file/bukkit (incompatible)
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)

**Comment by aikar** [comment]
Please provide full logs, the real error was before this in the logs, this information does not help understand what happened.
