### ISSUE TITLE
Light bug - random dark patches

### ISSUE THREAD

**Issue by Darunox** [PaperMC/Paper#1681]
Back to a problem : 

On our server, while using the first version of Paper with chunks stable conversion from 1.12.2 to 1.13.1, we performed some vanilla commands (/ fill) through a commandblock to make a big cube. This caused a light beug on the floor!

Despite the various updates, we still have not managed to erase this concern.

Here is this concern in image :

https://imgur.com/a/GVd9Zxf

CleanroomGenerator*, CoreProtect, Essentials*, EssentialsChat*, EssentialsSpawn*, GriefPrevention, Multiverse-Core*, Multiverse-Portals*, PermissionsEx*, SysInfoPlugin*, Vault*, WorldEdit, WorldGuard, XRayHunter

**Comment by zachbr** [comment]
MInecraft in general does not handle large block updates well, there are vanilla tickets as well about large fills.

Please re-test and provide the exact fill command for testing so we have an idea of the size we're dealing with. This may not be something that gets a quick fix.

**Comment by Chew** [comment]
OP Hasn't responded in over a year, so this must be closed due to inactivity. Many lighting issues have been fixed, so if you do still happen to have this issue, don't hesitate to open a new issue, ensuring you follow the template. Have a good day!
