### ISSUE TITLE
Pickup bug

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#1687]
https://www.youtube.com/watch?v=HaqzllQ5pAA

### Plugin list:
___A list of your plugins___
Plugins (0): 

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
```
[10:30:14] [Server thread/INFO]: This server is running Paper version git-Paper-451 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[10:30:14] [Server thread/INFO]: Previous version: git-Paper-413 (MC: 1.13.2)
[10:30:14] [Server thread/INFO]: Checking version, please wait...
[10:30:14] [Thread-15/INFO]: You are running the latest version
```

### Anything else:
I tested singleplayer - works perfectly pickup

**Comment by Parozzz** [comment]
I've had a similar issue. This does happen if you set an empty nbt tag to an item and then drop it. The dropped items do stack correctly on the ground, but when picked up start flooding your inventory.
Not sure if also spigot has this in or is only a bug with paper, I've not tested it.

**Comment by electronicboy** [comment]
Can you drop a stack on the floor and pickup the item, is there any difference with the item? Can you upload a copy of the player data file?

Item pickup is basically the exact same on vanilla, both items must match exactly, including all NBT tags on the item, if the pickup is failing on vanilla, there is likely something that is messing with the contents of the tags

**Comment by zachbr** [comment]
Anyone experiencing this issue please respond to electronic's questions and let us know if this occurs on vanilla as well as CB/Spigot. Thanks.
