### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by Sitmobedaf** [PaperMC/Paper#1688]
Stupid timings that do not display anything useful. When problems occur, it does not display any useful information and has a more complex design. How to restore normal spigot timings?

http://img11.lostpic.net/2018/11/17/3f5efd8d7cbf15fd4a6898d3a74f467b.jpg

**Comment by electronicboy** [comment]
Timings v1 is heavily flawed and does not present reliable information
Timings v2 is working as intended there, you had shy of 8K falling entities being ticked, of which ticking all of them took ~891ms per tick to process

**Comment by aikar** [comment]
Timings v1 wouldn't of provided you anything better in this scenario, you likely would not of been able to figure out it was falling blocks on v1.

If you are unable to understand the system then watch the video linked in the top right corner or simply ask others for help. The screenshot provided was pretty clear information, as @electronicboy said.
