### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DoogiePC** [PaperMC/Paper#1689]
### Link/paste of stack trace

https://pastebin.com/HpSyHkx1

### Plugin list:
ChatControl-7.9.36.jar, DummyFawe.jar, FeatherBoard.jar, PlaceholderAPI.jar, Skellett.jar, AnimatedNames.jar, LuckPerms-Bukkit-4.2.58.jar, RedstoneClockDetector.jar, CheckNameHistory.jar, FurnitureLib1_13.jar, PlotSquared-Bukkit-18.11.05-ae2869a-2051.jar, ArmorStandTools.jar, EssentialsX-2.15.0.45.jar, Marriage.jar, SharpSK.jar, ChestCommands.jar, EssentialsXAntiBuild-2.15.0.45.jar, HeadDatabase.jar, PluginDebugger-1.0-SNAPSHOT-all.jar, Skript.jar, EssentialsXProtect-2.15.0.45.jar, MVdWPlaceholderAPI.jar, SimpleAPI.jar, SkUniversal.jar, BlocksHub-3.0.0.jar, EssentialsXSpawn-2.15.0.45.jar, ipwhitelist-1.7-3.jar, CoreProtect-2.15.1.jar, FastAsyncVoxelSniper-favs-18.11.14-ec22c4f-2071.jar, nuvotifier-universal-2.3.5.jar, PlugMan.jar, skUtilities.v0.9.0.jar, PAFSpigot.jar, BuycraftX.jar, FastAsyncWorldEdit-bukkit-18.11.14-ec22c4f-2071.jar, ProtocolLib.jar, SimpleVoteListener.jar, SuperTrails.jar, LiteBans.jar, ProtocolSupport.jar

### Actions to reproduce (if known):
Unknown

### Paper build number:
git-Paper-1587 (MC: 1.12.2)

**Comment by electronicboy** [comment]
Can you replicate this without ~40 plugins? (and fix the build number in your issue report...)
I believe that a similar issue was already an issue for this type of crash, it was either fixed or was under some form of "this can't really happen outside of plugins being bad"
