### ISSUE TITLE
Spawning non-friendly mobs in creative mode not working as expected

### ISSUE THREAD

**Issue by stevmei** [PaperMC/Paper#169]
Non-friendly mobs are despawned instantly if:
1. Spawning player gamemode != survival
2. No other player with gamemode = survival is near the spawning location
3. All players online have gamemode != survival

So, acutally, it's possible to spawn mobs in creative mode when I'm alone on my testserver, but if the first player joins (survival mode), the spawned mobs are despawned.

Is this an added feature of paper or is this unexpected?
If unexpected: please fix :-)
If feature: please add config entry to enable/disable mob despawning in creative mode

Steps to reproduce:
1. Go online as the only player on server
2. /gamemode 1
3. Spawn a zombie with a spawn egg
4. Another player with /gamemode 0 joins the server (far away from your location, at least 5 chunks away)
5. Spawned zombie is despawned
6. Try to spawn another one
7. Another zombie is despawned instantly

Plugin list:
Tested without any plugin loaded.
Also tested with regular spigot (version git-Spigot-2038f4a-44216f1) and it was not reproducable there

Running version:
git-Paper-610

Thanks! <3

**Comment by ghost** [comment]
I can confirm this issue with build 625.

**Comment by zachbr** [comment]
Please test against Build 629 or newer, not sure if the above fix is related but it couldn't hurt.

**Comment by ghost** [comment]
Not fixed with build 630.

**Comment by stevmei** [comment]
Also not fixed with 631

**Comment by zachbr** [comment]
Thanks, we'll continue looking into these issues and hopefully get back to you.

**Comment by zachbr** [comment]
Should be fixed, Use build 671 or newer.
