### ISSUE TITLE
Server crashed unsure of cause

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#1694]
### Link/paste of stack trace

https://pastebin.com/bNJMma1D

### Plugin list:

https://pastebin.com/1MmZ4nnG

### Actions to reproduce (if known):

Have server running for a while, have atleast 2 players on, happens randomly. Eventually crashes, may be due to too many plugins but most of them are small.

### Paper build number:

[23:22:11 INFO]: This server is running Paper version git-Paper-451 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
The error would indicate that something tried to modify a player open inventory async

**Comment by axemwa** [comment]
Ah ok that makes sense CorpseReborn acceses player inventory when a player dies so that it can send it to an npc (corpse/grave) in the players place and [CorpseReborn](https://www.spigotmc.org/resources/corpsereborn.29875/) apparently doesn't fully support paper spigot and that bugs may occur...

It's also possible that when Citizens npcs die and the server goes to re apply the npc inventory/armor/weapons there could be a bug there somewhere, I'll do a timings paste to see if that helps

**Comment by axemwa** [comment]
Here's the [timings report](https://timings.aikar.co/?id=c1e9686a4e8740f39f36c09b5573a00e) I did, I also removed corpsereborn to see if it helps with the crashes

**Comment by electronicboy** [comment]
Closing, there is very little we can do about plugins behaving badly

**Comment by axemwa** [comment]
thats ok, sorry I forgot to close

**Comment by axemwa** [comment]
plus the server seems to be running fine now since i removed corpse reborn plugin thanx for the help

**Comment by egold555** [comment]
Hi. I am the developer of CorpseReborn. I'll look into this.

**Comment by axemwa** [comment]
Actually the crash/error still occurs so it may not be your plugin in this case @egold555, it says it has something to do with NBT tags any idea on what that would be?

I made a world intended to be my new Hub with a fair few entities with NBT tags added would something in there have caused this any ideas or directions u can point me in? Maybe one of the Boss Mobs that have one of the nbt tags causing an error?

The error I got in console:
https://pastebin.com/ieiacy0U

The crash report:
https://pastebin.com/Cbwapnze

**Comment by electronicboy** [comment]
All items store their data using an NBT tag, this includes stuff like enchantments, etc;

You have a plugin that is modifying itemstacks in inventories async, this is not safe, as it causes the very exception you're seeing in the crash reports when the server comes to process the contents to ensure that the client is up to sync with it properly

**Comment by egold555** [comment]
Nothing that changes itemstacks should be running async, unless something has changed in 1.13 that I am not aware of?

I haven't updated CorpseReborn in a long time because school has taken over all the time I have. I wouldn't be surprised if some event now runs async or some change has been made that I was not aware of.

**Comment by axemwa** [comment]
Is there a way to pinpoint which plugin is causing the crash?

**Comment by axemwa** [comment]
It could be this plugin as some of the yml files mention player item stacks a lot?
https://www.spigotmc.org/resources/multiinv.56659/
This plugin allows to ability to have seperate inventories for seperate worlds

A paste of one of the players' UUID.yml files in the MultiInv plugin folder mentioning player itemstacks:
https://pastebin.com/fhxmYWUB

I will ask the author if it's possible if it's their plugin

**Comment by electronicboy** [comment]
The only real way that you can check is by looking at the code yourself, or playing the "pull a few plugins" game and hoping that you find the actual cause

**Comment by axemwa** [comment]
Is this the same error(affects player item stacks etc)? I came across this crash/error when flying over chunks at max speed without stopping, and it mentioned an issue with chunk loading
https://pastebin.com/cmtS5RvN
