### ISSUE TITLE
Re-add target selectors for plugin commands in command blocks.

### ISSUE THREAD

**Issue by Artuto** [PaperMC/Paper#1697]
**Is your feature request related to a problem? Please describe.**
Re-add target selectors for command blocks. (Seems to be have been removed by [upstream](https://www.spigotmc.org/threads/1-13-commandblock.330213/#post-3089153))

**Describe the solution you'd like**
Be able to use things like `@p`, `@a`, `@e`, `@r` and `@s` in Command Blocks.

**Describe alternatives you've considered**
A way for command blocks to run commands as players.

**Additional context**
Nothing.

**Comment by SteeltonMC** [comment]
In the meantime I suggest using a plugin called "CommandHook"

https://www.spigotmc.org/resources/commandhook.61415/

**Comment by Artuto** [comment]
@SteeltonMC Judging by the discussion page it seems like the plugin has a bug and has been abandoned.

**Comment by BluePlastics** [comment]
PsuedoCommands seems to work as well, you just have to pass commands through the plugins command. The dev is also active and has taken some of my qol requests and put them in (making feature parity with how minecraft commands are supposed to work now).

https://www.spigotmc.org/resources/psudocommands-add-the-function-to-plugin-commands.56738/

**Comment by wellnesscookie** [comment]
I would love to see this feature built-in paper itself. Would be so amazing!

**Comment by fr3fou** [comment]
uh any news regarding this? I had some custom maps fail on me and I had to debug why they weren't working, turns out is that paper doesn't support `@p`

**Comment by aikar** [comment]
Well unless someone PR's it in a clean way, I doubt it's going to happen. 
This is best left to plugins in general but if a good PR comes we can review it.

**Comment by fr3fou** [comment]
any plugin recommendations for this? @aikar

**Comment by lordrius** [comment]
Hi! These are good ones...

https://www.spigotmc.org/resources/commandhook.61415/
https://www.spigotmc.org/resources/psudocommands-add-the-target-selector-to-plugin-commands.56738/

**Comment by eerussianguy** [comment]
Neither of those work in 1.16 unfortunately

**Comment by eerussianguy** [comment]
bump
