### ISSUE TITLE
BuildTools is broken

### ISSUE THREAD

**Issue by Xayanix** [PaperMC/Paper#1698]
```
==================
 Applying Patches
==================
bash: applyPatches.sh: No such file or directory
Error applying spigot and paper spigot patches
```

Running on Windows.

**Comment by zachbr** [comment]
I don't know what version this is for because you basically provided us with zero useful information.

I can confidently say its not anything we support at this point. If you get any issues building ver/1.12.2 or master, let us know, and provide some useful info next time.

**Comment by Xayanix** [comment]
nvm
