### ISSUE TITLE
X-Ray Proximity Hider (update-radius) Annoyances

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#1699]
**Is your feature request related to a problem? Please describe.**
Kinda. The anti-xray's proximity hider hides ground (item) entities and item frames. Which is really rough on normal gameplay after those things do not appear until you are almost right on top of them. 

I have my update-radius at 5 to try and make it less of a "glitch-like" behavior, but even then it's pretty rough.

See Video: https://youtu.be/p-I51Qpk-xg

**Describe the solution you'd like**
Ignore those entities in config (or entirely).
or
Set entity render in a different config setting so you could set their distance to 16 (or whatever).

**Comment by prplz** [comment]
This is not part of the anti-xray. What you are seeing is the effects of `entity-tracking-range.misc` in spigot.yml being set too low.

**Comment by CeIebrimbor** [comment]
I'm dumb...
