### ISSUE TITLE
Ender Chest Sound error

### ISSUE THREAD

**Issue by Cat7373** [PaperMC/Paper#170]
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0022-Optimize-TileEntity-Ticking.patch

Open：https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0022-Optimize-TileEntity-Ticking.patch#L166
Close：https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0022-Optimize-TileEntity-Ticking.patch#L181

Open：aL -> aM
Close：aK -> aL

**Comment by zachbr** [comment]
Thanks, we nearly missed this :)
Will be in master shortly
