### ISSUE TITLE
Vanilla team bug (color black)

### ISSUE THREAD

**Issue by AgoniaMc** [PaperMC/Paper#1703]
Easy description:
My server is a Vanilla server which runs Paperspigot for better performence. We use the vanilla team aka scoreboard feature. The /team modify team color black does not work. It only gives a black name in tab and above the players name. The color in chat is white. All the other colors work.

### Paper build number:
git-Paper-435 (MC: 1.13.2) (Implementing API version 1.13.2.R0.1-SNAPSHOT

**Comment by zachbr** [comment]
Thanks for letting us know.
Builds 462+
