### ISSUE TITLE
Thread issue

### ISSUE THREAD

**Issue by SkymaxPlay** [PaperMC/Paper#1704]
https://pastebin.com/yrdjWUth

The server crashes both with plugins and without them. It's hard to test it, because crashes occur sometimes after 5 min and sometimes after 24 hours. Also, the noumber of players doesn't matter. Sometimes it crashes with 300 players and sometimes with 2.

### Plugin list:
 WorldEdit, WorldGuard, Fast Async WorldEdit, rest plugins written by me

### Paper build number:
git-Paper-1589 (MC: 1.12.2)

### Configs:
spigot.yml: https://pastebin.com/YXwe1Z8d
server.properties: https://pastebin.com/NjuiyiZD
bukkit.yml: https://pastebin.com/d9yWdabS
paper.yml: https://pastebin.com/LtudxDcR

**Comment by astei** [comment]
Your server has some sort of memory leak. My bet is that it's one of the hand-written plugins you have.

Use a tool like [VisualVM](https://visualvm.github.io/), [YourKit](https://www.yourkit.com/java/profiler/features/) or [Eclipse Memory Analyzer](https://www.eclipse.org/mat/) to analyze a heap dump of your server around the time of the crash. (It might help to add the Java flag `-XX:+HeapDumpOnOutOfMemoryError` to your startup script).

**Comment by SkymaxPlay** [comment]
Memory leak? I dont think so. When server crashing I opened visualVM and none of my plugins was on top of memory usage.
More data, VisualVM screen and timings. 4 servers on dedicated server and all freezing one by one.
https://imgur.com/a/vaPc7Ei
https://timings.aikar.co/?id=6f59044586cf4f3592ffb59f7a10d0ed
https://timings.aikar.co/?id=28799cf5e15a489bafd4a41b4b7940ad
Last one, Tell me how task which broadcast one message takes 88% of tick????
https://timings.aikar.co/?id=4dd3b473df6f49cba8a78db65a658168

**Comment by electronicboy** [comment]
Looks like an overloaded system, your timings cost on one report is 76, yet on the other has jumped to 426, which would heavily indicate that something is being overloaded

Do the spikes line up with the GC activity spikes? Your memory usage also looks steadily high which is generally a case of either memory is leaking, or GC just can't keep up, given your high uptime and the high memory allocation, I'd suggest looking at this: https://mcflags.emc.gs

**Comment by SkymaxPlay** [comment]
https://pastebin.com/tFYH0dbk console logs
https://pastebin.com/cZEsZv8X after killed process

**Comment by astei** [comment]
> When server crashing I opened visualVM and none of my plugins was on top of memory usage.

I still suspect that there is a memory leak. Your server is constantly GCing, and each time it GCs it is unable to keep up with the demand.

Try using https://mcflags.emc.gs/ and `-XX:+HeapDumpOnOutOfMemoryError`. If you get an `OutOfMemoryError`, put the heap dump into VisualVM.

**Comment by crobey98** [comment]
We are having this issue as well. With and without plugins. We have had our server host look into it and they're insisting it is not on their end so it has to be paper causing this issue for us.

**Comment by electronicboy** [comment]
We need information such as timings information, so far all we've seen is something which either looks like a memory leak or an overloaded server
