### ISSUE TITLE
Inactitive entities causing lag?

### ISSUE THREAD

**Issue by Bobr902011** [PaperMC/Paper#1706]
###  Timings or Profile link:
https://sparkprofiler.github.io/?0z41tW63VX

### Description of issue:
17% on inactive entities

Looks like inactive entities are slow and causing issues with lag, something about pathfinding?

Running the server for 24+ hrs makes the lag worse.

### Plugin list:
None

### bukkit.yml, spigot.yml, paper.yml, server.properties
Default

### Paper build number:
463

**Comment by aikar** [comment]
It's going to be situational. Mobs are looking into unloaded chunks, causing it to load chunks. cat did some work to limit damage here recently, but I will work on a fix tonight to stop it loading chunks all together.

**Comment by electronicboy** [comment]
That patch kinda got shoved off into a branch while I was working on other things, however, was committed today in build 464
