### ISSUE TITLE
EntityRemoval task makes server lag

### ISSUE THREAD

**Issue by dudullle** [PaperMC/Paper#1707]
**Timings :**
https://timings.aikar.co/?id=4b91f4bfeaf144068fa6b99ef0b4d72e
**Paper version**
Paper 448 - MC 1.13.2

My TPS was around 20 before some updates  with 10 players but now it is around 19.10, with 0 online players

**Comment by dudullle** [comment]
same issue with build 463

**Comment by zachbr** [comment]
If you're still seeing this please open a new ticket or bug us on discord https://discord.gg/papermc
