### ISSUE TITLE
Paperclip 1.9.2 missing Armor Bar

### ISSUE THREAD

**Issue by netherstar** [PaperMC/Paper#171]
as you can see here
http://i.imgur.com/QT7xueb.png

**Comment by willies952002** [comment]
Could you please provide the following information to help us try and reproduce/fix this issue:
1. Steps/models to reproduce

**Comment by netherstar** [comment]
as you can see in picture, fresh install of server, no plugins.

**Comment by zachbr** [comment]
![minecraft 1 9 2_004](https://cloud.githubusercontent.com/assets/1254957/14186732/56b2df34-f745-11e5-91d4-8f05f6ed4df7.png)

**Comment by willies952002** [comment]
@tuanjr I would say try disabling all resource packs, that's what might be causing it.

**Comment by netherstar** [comment]
Sorry, my fault! it's cause by Optifine.

**Comment by ThundeRabbit** [comment]
i have this problem too! How do i fix it??

**Comment by zachbr** [comment]
Update your resource pack or remove it.
Or any other client-side mods.
