### ISSUE TITLE
/version issue

### ISSUE THREAD

**Issue by NoopyyGaming** [PaperMC/Paper#1711]
### What behaviour is expected:
/version 

### What behaviour is observed:
Error obtaining version information

### Steps/models to reproduce:
N/A

### Plugin list:
No plugins atm

### Paper build number:
CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Anything else:
Fixing the version problem only, but i haven't other things to help you fix this

**Comment by 0-x-2-2** [comment]
1.8.8 is unsupported.

**Comment by NoopyyGaming** [comment]
Oh okey, and which one shoul i use instead then ?

**Comment by 0-x-2-2** [comment]
1.13.2 or 1.12.2 but 1.12.2 only has bug fixes.

**Comment by NoopyyGaming** [comment]
I don't like the pvp on 1.12.2 :/

**Comment by darbyjack** [comment]
Then just use 1.8.8 and stop worrying about the /version command.

**Comment by NoopyyGaming** [comment]
I'm only asking he, you don't need to be furious on me :P
