### ISSUE TITLE
Startup Console: Scoreboard Error

### ISSUE THREAD

**Issue by SteeltonMC** [PaperMC/Paper#1714]
### What behaviour is expected:

 I log of NBT errors are reported in console upon starting of a server using latest Paper.jar

___What you expected to see___

No NBT Data Errors

### What behaviour is observed:

Just upon startup

___What you actually saw___

Console Errors

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Latest Paperclip.Jar

### Plugin list:
___A list of your plugins___

Basic plugins. Essentials, WorldEdit, Etc.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

Version: 469

### Anything else:
___Anything else you think may help us resolve the problem___

I am simply here to report the bug. :)
![capture](https://user-images.githubusercontent.com/45464775/49238491-8382cc80-f3ce-11e8-9a34-a1a2038eaa6d.PNG)

**Comment by MiniDigger** [comment]
please don't send in screenshots.
please provide a copy of the relevant log lines from your latest.log file.
generally this looks like your scoreboard file got corrupted somehow, maybe by a plugin. can you provide that too?

**Comment by electronicboy** [comment]
If a file is corrupted, there is nothing we can do about that; delete the file or restore a backup of it if needed, file will be in <world-folder>/data

More than likely your server crashed while saving this file or failed to save to disk properly (common issues on shared hosts when the servers disk fills)
