### ISSUE TITLE
Book writing kicks for Book too large!

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1716]
### What behaviour is expected:
___What you expected to see___
I expected to be able to write book properly.

### What behaviour is observed:
___What you actually saw___
I got kicked with the message of "Book too large!"
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
just write a 3 page book.

### Plugin list:
___A list of your plugins___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
1592
### Anything else:
___Anything else you think may help us resolve the problem___
[10:05:03] [Server thread/WARN]: Govindas tried to send too large of a book. Book Size: 666 - Allowed:  514 - Pages: 3
[10:05:03] [Server thread/INFO]: Govindas lost connection: Book too large!
paper.yml:
  book-size:
    page-max: 1024
    total-multiplier: 0.9

**Comment by 0-x-2-2** [comment]
What where you writing in the book?

**Comment by Govindass** [comment]
> What where you writing in the book?

shouldn't be anything dangerous as I didn't use some special symbols, I cannot share what I was writing as it is very personal.

**Comment by 0-x-2-2** [comment]
Was it written in english?

**Comment by aikar** [comment]
it appears you downloaded the first paper build I added this, and have the old defaults.

I changed the defaults shortly after.

change page-max to 2560 and total multiplier to 0.98 and itll fix it (or just delete the book-size section and let it regenerate)

**Comment by mathiascode** [comment]
The new defaults were not backported to the 1.12.2 branch. 1.12.2 still uses the old 1024 and 0.9 values.
