### ISSUE TITLE
Sleeping at night takes only the first player's wait time

### ISSUE THREAD

**Issue by DutchFlander** [PaperMC/Paper#1719]
### What behaviour is expected:
In order to have morning on a multiplayer server everybody should be in the bed at the same time.
When more than one player is playing on a server, the last person who goes to sleep should also wait for the screen to fade for sleeping which is approximately 3 sec on vanilla server.

### What behaviour is observed:
Someone goes to sleep, his/her screen fades in a few seconds (~3 sec). When the next player goes to bed for sleeping, in his client the sleeping takes only a few milliseconds and immediately there is morning on the server. So the fading period is missing from the sleeping state when someone else is already sleeping in the bed.
In other words: only the first player going to bed has the fading effect, all the rest who are going to sleep after the first person's fading period will just have to wait the remaining time, which after the first playes's ~3 second is 0 second (immediate).

### Steps/models to reproduce:
1. Have at least 2 people playing on a server
2. Wait for the night
3. Make the first player go to sleep and wait for the fading effect to finish while in the bed
4. The second player can go to sleep
5. This second player will skip the fading effect/sleeping animation and there will be morning on the server immediately

### Plugin list:
none

### Paper build number:
[12:03:38 INFO]: This server is running Paper version git-Paper-473 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[12:03:38 INFO]: Previous version: git-Paper-472 (MC: 1.13.2)
[12:03:38 INFO]: Checking version, please wait...
[12:03:38 INFO]: You are running the latest version

I'm using paper since git-Paper-413 and the issue is still present.

### Anything else:
Couldn't find related bug report and not sure if this behavior is intentional or not, but in my opinion it is silly that the last player who goes to bed just have to hit it and there is immediate morning on the server skipping the actual lying in bed animation and screen fading.

**Comment by aph3rson** [comment]
Can confirm we've seen this too, also on build 473 with no mods.

**Comment by DutchFlander** [comment]
Current version is git-Paper-599 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) and the issue still present.
Can we expect a fix for it before 1.14?

**Comment by electronicboy** [comment]
I don't believe anybody has looked into this, is this issue report requesting a fix to bring paper back to vanilla behavior, or requesting a change of what is currently vanilla behavior?

**Comment by DutchFlander** [comment]
Since I couldn't find any document mentioning changes regarding the sleeping behavior in paper survival servers, I suspect this is a bug, not a feature, so it should be "a fix to bring paper back to vanilla behavior".

**Comment by Spottedleaf** [comment]
https://gist.github.com/Spottedleaf/0ab4721adddbe32e5d5a89f9d7f8b9bd

This is because CB modifies everyoneDeeplySleeping() to return true if at least one player is deeply sleeping
(note that faux sleeping is determined by plugins)

**Comment by ravkr** [comment]
Any updates?

**Comment by aikar** [comment]
leaf said this was resolved in 1.14. Please verify the issue still exists before bumping for updates.
