### ISSUE TITLE
Add config to disable frost walker ice

### ISSUE THREAD

**Issue by ZephireNZ** [PaperMC/Paper#172]
I suggest that Paper add a configuration option to disable the melting of `frosted_ice` blocks.

While the enchantment can be useful, it can also be a hog on tick time as I found out. Because each block is individually ticked every 1-2 seconds, it can cause issues when players create large underground pathways as I experienced. This all added up to a large chunk of my tick lag being solely frosted ice.

**Comment by kashike** [comment]
@ZephireNZ So what, you want frost walker ice to always stay?

**Comment by ZephireNZ** [comment]
Yes, basically when frost walker is used, a `frosted_ice` block is created, and a world tick is registered for 20-40 ticks in the future. The block is ticked, and then registers again until it reaches removal criteria. The problem is that it will never expire if the ice is in dark enough conditions, causing considerable lag in large quantities.

I suggest adding a toggle in the config, to prevent it from registering the world tick for itself, and hence preventing this kind of lag.
