### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by LogGits** [PaperMC/Paper#1722]
1) Is there a way to change trident despawn rate? (similar to `non-player-arrow-despawn-rate and creative-arrow-despawn-rate`) Im trying to change the default despawn rate, the non player despawn rate, and creative player despawn rate of tridents.

2) I had this conversation on the discord a while ago but i never found out the answer. Is there a difference between these two methods of doing a backup? If so, which one is preferred and why?
```
save-off, save-all, backup, save-on
save-all, save-off, backup, save-on
```
Thanks in advance~

**Comment by LogGits** [comment]
Is there any news on this?

**Comment by electronicboy** [comment]
1) currently, no
2) The difference is that save-off first means that you shouldn't end up with any changes from standard world saving after you've saved, but you probably wanna:
`save-off, save-all flush, backup, save-on`, passing flush to save-all ensures that the save-queue is written to disk

**Comment by zachbr** [comment]
This ticket came first but there is a more explicit feature request for separate trident despawn times at #1742. Closing in favor of that ticket.

**Comment by LogGits** [comment]
Can we reopen this. That issue was regarding range. This is regarding rate (e.g. how long it takes to despawn a trident after it has been thrown by a player). This is currently being taken from `non-player-arrow-despawn-rate` which i have set to 3s. This means skeleton arrows despawn after 3 seconds. The sideeffect is now player tridents are being affected. If a player throws a trident it despawns after 3 seconds.

**Comment by electronicboy** [comment]
~~Read the last comment.~~
different issue, pretty sure that there is already an issue open for that

Anyways, explict issues are preferred over a single issue tryna ask multiple things
