### ISSUE TITLE
Players get invisible when dying or connecting.

### ISSUE THREAD

**Issue by Haryol** [PaperMC/Paper#1725]
I have spotted a recurrent issue who made players get invisible when dying or connecting, sometimes just disconnect is enought to make players visible again but sometimes we need to use "/kill" or disconnect and launch Minecraft again.

here is the Plugin and the version use on the serveur:
https://timings.aikar.co/?id=797075e1bf964934ab33b65f26c75663

**Comment by electronicboy** [comment]
Can you replicate this without 40 plugins?
