### ISSUE TITLE
Teleport through wall after getting out of bed

### ISSUE THREAD

**Issue by Decme** [PaperMC/Paper#1726]
### What behavior is expected:
Not to be teleported through a wall when getting out of bed

### What behavior is observed:
This: https://drive.google.com/open?id=13jnkqnWAcG9uvh9liQycuBUv7Kdpb4yx

### Plugin list:
ChatEx*, CoreProtect, DiscordSRV, dynmap*, Dynmap-WorldGuard*, Essentials*, NameColors*, OnDeathCoord*, PermissionsEx*, Vault*, WorldEdit, WorldGuard

### Paper build number:
473

**Comment by Phoenix616** [comment]
Looks like it doesn't search two of the edges here:

https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0284-Configurable-Bed-Search-Radius.patch#L44-L81

This code
```java
int x = -r;
int z = r;

// Iterates the edge of half of the box; then negates for other half.
while (x <= r && z > -r) {
    [...]
    if (x < r) {
        x++;
    } else {
        z--;
    }
}
```
only iterates through positive x and z edges, not negative x or z. With radius 1 it ends up checking through x/z `-1/1`, `0/1`, `1/1`, `1/0` and stops at `1/-1`. (Because of the `while (x <= r && z > -r)`, `z == -1` is not greater than `-r` with `r == 1` it doesn't check `-1/-1`, `0/-1`, `-1/0` or `)

**Comment by MisterVector** [comment]
Taking the original code and isolating x and z, I made some changes which produce the following path (y is omitted):

With radius = 1:

```
x: -1 z: 1
x: 0 z: 1
x: 1 z: 1
x: -1 z: 0
x: 0 z: 0
x: 1 z: 0
x: -1 z: -1
x: 0 z: -1
x: 1 z: -1
```

Here is the diff of the changes I made: https://gist.github.com/MisterVector/71963bbf96b04e4337e1f22cd42e5282/revisions?diff=unified#diff-30932ceeb50a123853061f7fd69d7e95

However, running the Paper server with this updated code did not fix the issue.

Also, the for loop doesn't seem necessary. With a radius more than 1, the same path segments will be iterated over multiple times (I.E. 1, 1 will be traversed twice with a radius of 2, etc.).

**Comment by CeIebrimbor** [comment]
This is the same behavior for vehicles (like boats). If you dismount a boat towards a wall you are next to a wall, or under a platform (similar to the video above), you appear on the other side or above.

In fact, this behavior has been going on for some time. Not sure if the behavior is linked. Looks like it might be.

**Comment by Kruize1** [comment]
I would like to bump up the severity/priority of this bug.

Players can get stuck in an infinite death loop, if the blocks behind the wall are lava.

If you watch the video, the spot where the player ends up is usually filled with lava. If they die from the lava, they will spawn right back in that exact same spot.

If other players have knowledge of this bug, they can trap and kill other players. The victim who is stuck in the death loop is essentially "bed banned" unless they receive divine intervention from another player or OP.

**Comment by kickash32** [comment]
Been working on a fix for this, need suggestions in which order to select the same coloured blocks.
![image](https://user-images.githubusercontent.com/8919730/58773111-db6edb80-8589-11e9-87d7-a976769e3ec5.png)
Currently this is how I have it setup.

It prioritizes spawning on the same level (allows spawning 1 block lower or higher) and blocks that are closest to the adjacent blocks to the bed.

Another picture representation with range bed-spawn-range=2
![image](https://user-images.githubusercontent.com/8919730/58773354-bc247e00-858a-11e9-9adf-614c7659f214.png)


3D representation (block are places where players spawn)
<img width="966" alt="image" src="https://user-images.githubusercontent.com/8919730/58773301-8bdcdf80-858a-11e9-819e-ebb936dc12af.png">
