### ISSUE TITLE
Random Kicks and getting this report 1.12.2

### ISSUE THREAD

**Issue by PengBread** [PaperMC/Paper#1732]
### Link/paste of stack trace

07.12 01:48:39 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
07.12 01:48:39 [Server] ERROR The server has not responded for 55 seconds! Creating thread dump
07.12 01:48:39 [Server] ERROR ------------------------------
07.12 01:48:39 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
07.12 01:48:39 [Server] ERROR ------------------------------
07.12 01:48:39 [Server] ERROR Current Thread: Server thread
07.12 01:48:39 [Server] ERROR PID: 17 | Suspended: false | Native: false | State: RUNNABLE
07.12 01:48:39 [Server] ERROR Stack:
07.12 01:48:39 [Server] ERROR net.minecraft.server.v1_12_R1.WorldServer.j(WorldServer.java:561)
07.12 01:48:39 [Server] ERROR net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:328)
07.12 01:48:39 [Server] ERROR net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:905)
07.12 01:48:39 [Server] ERROR net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
07.12 01:48:39 [Server] ERROR net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
07.12 01:48:39 [Server] ERROR net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
07.12 01:48:39 [Server] ERROR java.lang.Thread.run(Thread.java:748)
07.12 01:48:39 [Server] ERROR ------------------------------
07.12 01:48:39 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---

It says do not report but the server kicked everyone out. I think its the best to report it.

### Plugin list:
___A list of your plugins___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
git-Paper-1593

**Comment by electronicboy** [comment]
We need the logs before that, something held your server up from ticking for a whole minute, which should be indicated from the previous logs

**Comment by PengBread** [comment]
Logs here
https://pastebin.com/UNNh7q9r

Apparently it looked like the votifier event from enjin plugin.
Is it Enjin Plugin Votifier event caused it? One of my tech says it is but not sure how to disable that thing.

**Comment by Black-Hole** [comment]
It seems the plugin is loading the player data of every player who ever visited your server. There are many other votifier plugins and you could ask the plugin author to look into it.
