### ISSUE TITLE
Latest Paper build not built against latest spigot? Found via citizens incompatibility if true curious is this update coming soon?

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#1736]
### What behaviour is expected:
Citizens compatibility (built against latest Spigot) in latest Paper build

### What behaviour is observed:
WARNS in console - https://pastebin.com/CFeGsZJE
& Latest Log - https://www.dropbox.com/s/chwy69umhu9rvk8/latest.log?dl=1
### Steps/models to reproduce:
Install latest Paper - https://papermc.io/ci/job/Paper-1.13/
Install latest citizens dev build - http://ci.citizensnpcs.co/job/Citizens2/

### Plugin list:

https://pastebin.com/uikqFBSV

### Paper build number:
This server is running Paper version git-Paper-474 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Anything else:
mcmonkey4eva mentions it's an error due to Paper not updating their included copy of spigot yet, if this is the case when will then update be coming out, just curious?
See here for reference - https://github.com/CitizensDev/Citizens2/issues/1628

**Comment by zachbr** [comment]
Nope, almost did it the other night but they weren’t in a good spot.

No ETA.

**Comment by axemwa** [comment]
[Paper 475](https://papermc.io/ci/job/Paper-1.13/475) fixed it, thanx :P
