### ISSUE TITLE
Timings problem

### ISSUE THREAD

**Issue by Sitmobedaf** [PaperMC/Paper#1737]
I think your timings are very incomprehensible and inconvenient. Is it possible to return standard spigot timings? Or should I contact you whenever I have problems with TPS?!

https://timings.aikar.co/?id=83bfc99b912045d7aa4f650c4b729d4e

Best regards!

**Comment by zachbr** [comment]
While we understand change can be difficult, we believe our version of timings, v2, is the best choice for Paper and its users. We will not be reverting back to the inferior system it replaces.

There are resources available to help you understand v2, such as [this video](https://www.youtube.com/watch?v=T4J0A9l7bfQ), and with time you may come to see its benefits.

This tracker is for source code level bugs not helping you diagnose performance issues with your server. If you need help, please see either the forums or Discord.
