### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by ecoterrorist** [PaperMC/Paper#1739]
As soon as I switch to Paper, I begin to see console spam like this. https://hastebin.com/icopilumep.css
Version: 
![screen shot 2018-12-09 at 8 29 53 am](https://user-images.githubusercontent.com/42695513/49698053-b24a3100-fb8c-11e8-83c9-1b410a29ef17.png)

**Comment by electronicboy** [comment]
What version of core protect are you using?

**Comment by Ayymoss** [comment]
@ecoterrorist Latest CoreProtect works with build 488 without issue.

**Comment by electronicboy** [comment]
Known issue with CoreProtect, they're working on a fix
