### ISSUE TITLE
Prevent tridents from despawning.

### ISSUE THREAD

**Issue by andrewkm** [PaperMC/Paper#1742]
if possible can you add an option for "tridents" to ignore:
`    despawn-ranges:
      soft: 28
      hard: 96`

tridents-ignore-despawn-ranges: true

Please <3 lol.

**Comment by kickash32** [comment]
Is this even an issue for trident and arrows? I tested despawn ranges on them, and they do not despawn based on distance from players. They only despawn after a certain amount of time in a block(configurable in paper.yml).

**Comment by kickash32** [comment]
Alternatively could add option `never-despawn-player-tridents: true`.
However this could easily be accomplished using a plugin.

**Comment by andrewkm** [comment]
Can be done via plugin.
