### ISSUE TITLE
tick entity problem for zombie pigman

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#1747]
Minecraft::tickEntity - nms.EntityPigZombiecount(68182)  total(70.30% 64.502s, 96.42% of tick)avg(0.95ms per - 48.21ms/50.96 per tick)
this data timings report and gold zombie pigman farm nether for player

**Comment by successed** [comment]
http://prntscr.com/lulvw1

**Comment by zachbr** [comment]
![why can't you just read](https://i.imgur.com/dOFRQ30.png)
