### ISSUE TITLE
Patch 0163-ShulkerBox-Dupe-Prevention interferes with Coreprotect's ability to roll back shulker boxes

### ISSUE THREAD

**Issue by carlpoole** [PaperMC/Paper#1748]
### What behaviour is expected:
When using CoreProtect (http://coreprotect.net/download/CoreProtect-2.15.2.jar) on latest Paper 480, MC 1.13.2, I expect to be able to roll back a stolen/destroyed shulker box and find the items inside from before.

### What behaviour is observed:
The shulker box rolls back but it is empty.

### Steps/models to reproduce:
Place a shulker box, place items inside. Wait for a minute or so. Destroy it with TNT or break it with pickaxe, etc. and then run`/co rb t: 30s`

### Plugin list:
Just CoreProtect version 2.15.2 (or 2.15.1)

### Paper build number:
Tested on 480 and 473

### Anything else:
This works as expected on Spigot, but not Paper. When I downloaded the source and removed the `Patch 0163-ShulkerBox-Dupe-Prevention` and re-built Paper, CoreProtect shulker rollbacks worked as expected.

**Comment by carlpoole** [comment]
Some chat from the discord about the issue that might be helpful for troubleshooting/fixing https://discordapp.com/channels/289587909051416579/289587909051416579/523052948566048777

**Comment by electronicboy** [comment]
Already discussed on the paper discord with Intelli, This needs to be fixed by CoreProtect (and ~~should~~ *hopefully should* be fixed in the next version of CP afaik)
