### ISSUE TITLE
player mount issue

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#1752]
### What behaviour is expected:
standard experience

### What behaviour is observed:
the player becomes invisible, is unable to see other players, and is able to bypass checks in plugins (a player used this to grief protected areas and walk outside of the world border), also is unable to chat 

### Steps/models to reproduce:
simply mount player2 on top of player1 (setPassenger is the method I believe), then have the player on top switch bungee servers or log off

### Plugin list:
___A list of your plugins___

### Paper build number:
git-Paper-1592 (MC: 1.12.2)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Librazy** [comment]
reproduced on 1592, only code relevant is setPassenger

**Comment by Black-Hole** [comment]
Your code just have to listen to PlayerQuitEvent and dismount if the "vehicle" is another player.

**Comment by PhanaticD** [comment]
its when the player on top leaves not bottom

**Comment by Librazy** [comment]
confirmd on git-Spigot-2cf50f0-2b93d83 so an upstream issue

**Comment by Librazy** [comment]
it seems that there is severe desync between server and 'vehicle' client, after passenger mounted then unmounted by logoff. Server runs fine with an WARN `Skipping Entity with id minecraft:`. Plugin logic/events are fine but maybe not sync with the vehicle client.

There is no warn about https://papermc.io/javadocs/org/bukkit/entity/Entity.html#addPassenger-org.bukkit.entity.Entity- requires a PlayerQuitEvent hook

Paper 1.13.2 seems affected, Spigot 1.13.2 untested.

**Comment by zachbr** [comment]
There's now a workaround for this in 1.12.2, if someone can reproduce the issue in 1.13.2 we will port it to that version as well.

**Comment by Librazy** [comment]
@zachbr I did a brief test before and this issue reproduces on 1.13.2

**Comment by zachbr** [comment]
Didn't see this, sorry.
Ported to 1.13.2 as of now. Thanks for letting me know.
