### ISSUE TITLE
Creature spawn event on chunk gen

### ISSUE THREAD

**Issue by Sitmobedaf** [PaperMC/Paper#1753]
How can I cancel spawn mobs, if the event is not triggered when generating chunks? Navreno should make an "AsyncChunkGenEvent" event and we could do something about it or any other right decision?!

`SpawnReason reason = e.getSpawnReason();
			if (reason == SpawnReason.CHUNK_GEN && !e.getEntity().getType().equals(EntityType.VILLAGER)) {
				e.setCancelled(true);
			}`

**Comment by Spottedleaf** [comment]
As far as I'm aware you can use ChunkLoadEvent.

**Comment by Librazy** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-4534 and fixed upstream

**Comment by Sitmobedaf** [comment]
I temporarily use an alternative - ChunkPopulateEvent

**Comment by electronicboy** [comment]
merged upstreams changes last night: 
https://github.com/PaperMC/Paper/commit/3496f2d7e494b44d152c02e1779881f4e55813c1
