### ISSUE TITLE
Paper Spigot 1.13.2 build 483 keeps disconnecting players and causing low TPS

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#1754]
After updating to latest paper spigot 483 after about 5-10 seconds after joining the server I get this message in console "[03:47:57 WARN]: handleDisconnection() called twice" and it disconnects the player, I also get TPS warnings reported by LagMonitor before it happens
I do not have this problem in build 481 so is this an issue with paper?

**Comment by electronicboy** [comment]
Timings?

**Comment by mergu** [comment]
This isn't a timings issue, it's an issue that has to do with spigot updating mappings here: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/c64fe5080c996e8ea29b3e113043dd0aa962aaee
This was recently pulled into Paper here: https://github.com/PaperMC/Paper/commit/3496f2d7e494b44d152c02e1779881f4e55813c1

Issue seems to be plugins using nms that need to update, specifically Denizen had this issue and it was resolved here: https://github.com/mcmonkey4eva/Denizen/commit/321d609f2412e626c1554bef24f395bfe9eaa98a

**Comment by axemwa** [comment]
Hmm build 481 seems to be doing it aswell after all

**Comment by axemwa** [comment]
hopefully it was just my internet connection playing up

**Comment by axemwa** [comment]
> 
> 
> This isn't a timings issue, it's an issue that has to do with spigot updating mappings here: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/c64fe5080c996e8ea29b3e113043dd0aa962aaee
> This was recently pulled into Paper here: [3496f2d](https://github.com/PaperMC/Paper/commit/3496f2d7e494b44d152c02e1779881f4e55813c1)
> 
> Issue seems to be plugins using nms that need to update, specifically Denizen had this issue and it was resolved here: [mcmonkey4eva/Denizen@321d609](https://github.com/mcmonkey4eva/Denizen/commit/321d609f2412e626c1554bef24f395bfe9eaa98a)

Thanx downgrading to denizen 489 fixed my issue

**Comment by axemwa** [comment]
> 
> 
> This isn't a timings issue, it's an issue that has to do with spigot updating mappings here: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/c64fe5080c996e8ea29b3e113043dd0aa962aaee
> This was recently pulled into Paper here: [3496f2d](https://github.com/PaperMC/Paper/commit/3496f2d7e494b44d152c02e1779881f4e55813c1)
> 
> Issue seems to be plugins using nms that need to update, specifically Denizen had this issue and it was resolved here: [mcmonkey4eva/Denizen@321d609](https://github.com/mcmonkey4eva/Denizen/commit/321d609f2412e626c1554bef24f395bfe9eaa98a)

Oh thankyou all I had to do was update to latest Denizens :) now everything works fine no more warns
