### ISSUE TITLE
Entity Phantom has been removed

### ISSUE THREAD

**Issue by nolife80** [PaperMC/Paper#1755]
[Mon, 17. Dec 2018 19:43:50 UTC WARN] EntityPhantom['Phantom'/1012086, uuid='eb68aac2-2b24-467d-b66d-9bbb0e61a4f9', l='world', x=39.50, y=116.05, z=-1.36, cx=2, cz=0, tl=568, v=false, d=false] was removed from a entitySlice we did not expect. Report this to https://github.com/PaperMC/Paper/issues/1302

**Comment by electronicboy** [comment]
> Report this to #1302
