### ISSUE TITLE
Question regarding the correct JAR file url

### ISSUE THREAD

**Issue by mtoensing** [PaperMC/Paper#1756]
Hi

I currently use this url and download the jar file every day: 

https://papermc.io/ci/job/Paper-1.13/lastSuccessfulBuild/artifact/paperclip.jar

Is this the same as 

https://papermc.io/ci/job/Paper-1.13/XXX/artifact/paperclip-XXX.jar

while XXX is the most recent build number?

**Comment by electronicboy** [comment]
most recent build that successfully compiled, yes; every build has a versioned and non-versioned artifact attached to it
