### ISSUE TITLE
entities not loading until your super close

### ISSUE THREAD

**Issue by BBoyJD10** [PaperMC/Paper#1759]
### What behaviour is expected:
Entities load_

### What behaviour is observed:
Only loading when really close to them

### Steps/models to reproduce:
update server

### Plugin list:
https://gyazo.com/d28521bbf96add90b878ab99b2c2db37

### Paper build number:
https://gyazo.com/6ce05dfcf320312c1d6af9c942579d51

### Anything else:
n/a

**Comment by electronicboy** [comment]
Entities load with the chunks, this is more than likely entity tracking related, but you've not included any information whatsoever that's useful to us, other than you have several plugins known to mess around with the server.

**Comment by MagmaGuy** [comment]
Had the same issue, looked around, turns out it was a ProtocolSupport bug

https://i.imgur.com/KSXCwxA.png
