### ISSUE TITLE
Long pause when entities try to move

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#1761]
Paper 480

It said don't report to paper, but it looks like i really should!!!

https://pastebin.com/fpaQ32ju

**Comment by Spottedleaf** [comment]
As far as the logs you have shown, it looks like your server is just overloaded. You should probably get more logs and confirming the pauses as bugs before opening an issue.

**Comment by electronicboy** [comment]
That's a player trying to move, more than likely at a high speed thus causing a lot of work for the server, especially if it has to start loading chunks; There is a configuration option in paper.yml to prevent players moving into such chunks

**Comment by hurrgurl** [comment]
Sorry forgot to mention that it's enabled.

**Comment by hurrgurl** [comment]
Gonna update to latest, there is a good chance that #485 & #486 solves this issue.
