### ISSUE TITLE
Problems with the generation of chunks

### ISSUE THREAD

**Issue by DarkFort** [PaperMC/Paper#1775]
###  Timings or Profile link:
https://timings.aikar.co/?id=7ae6f949245f49f08f9f081b6065c3bd                      

### Description of issue:
[Error](https://gist.github.com/DarkFort/16ffc1bd1c9fbf8b5bfd421c310e59ae)

### Plugin list:
Plugins: AdminChat*, AdvancedRandomTeleport, AntiRelog*, AuthMe, AutoPlayerCmd*, CCLogger*, ChestCommands, ClearLag*, CoreProtect, DeluxeJoin, Essentials*, EssentialsSpawn*, HackedServer*, InventoryRollback, LeaderHeads*, LiteBans, LuckPerms, MessageAnnouncer*, MyCommand*, NametagEdit*, PlaceholderAPI, Plan*, PlugMan*, ProtocolLib*, RFChairs, SkinsRestorer, TitleManager*, TradeMe, Vault*, WorldBorder, WorldEdit, WorldGuard         

### bukkit.yml, spigot.yml, paper.yml, server.properties
[bukkit.yml](https://pastebin.com/U32wqw4j)
[spigot.yml](https://pastebin.com/sf8tNqGf)
[paper.yml](https://pastebin.com/gKH2LVev)
[server.properties](https://pastebin.com/f44innKn)

### Paper build number:
[13:15:34 INFO]: This server is running Paper version git-Paper-488 (MC: 1.13.2)
 (Implementing API version 1.13.2-R0.1-SNAPSHOT)                                
[13:15:34 INFO]: Checking version, please wait...                               
[13:15:35 INFO]: You are running the latest version

**Comment by aikar** [comment]
Paper 520+ should fix this now
