### ISSUE TITLE
Torch bug

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#178]
**The following are 'hard suggestions': if you have the information
available to you, you really should put it in the report. Choose one of
the following templates from below that best fits the issue you wish to
report.**
# Incompatibility (Bug)

Bukkit: http://pastebin.com/bJATVP17
Spigot: http://pastebin.com/Xy4wumJE
Paper: http://pastebin.com/gt6TLDe6
### Steps/models to reproduce:

https://www.youtube.com/watch?v=_Gkndq0ah0E
### Plugin list:

Plugins (49): MobEggSpawnerBlocker, PlugMan, NametagEdit, MineMarket-Universal, ChatColor, AsyncWorldEditInjector, CoreProtect, Deadbolt, SkinsModule, LimitCreative, CreativeNbtControl, ClearLag, ChatControl, Chairs, ProtocolLib, NoCheatPlus, LibsDisguises, AsyncWorldEdit, IPWhitelist, OldGoldSurvival, RedstoneClockDetector, PermissionsEx, Vault, FamoustLottery, FwdMsgChanger, MyCommand, PlayerHeads, WorldEdit, Essentials, PlotMe, Jobs, Auctions, Multiverse-Core, TreasureChest, EssentialsChat, MobArena, WorldGuard, EssentialsGeoIP, LimitedCreative, EssentialsSpawn, PvPManager, RedstoneClockPreventer, TitleManager, iZone, AreaShop, SurvivalGames, CraftBook, ChestShop, MyPet
### Paper build number:

This server is running Paper version git-Paper-625 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Cannot reproduce on build 628.

**Comment by Puremin0rez** [comment]
Cannot reproduce either on build 628.

**Comment by aikar** [comment]
This really looks like a plugin cancelling a physics event.
