### ISSUE TITLE
Player not Found

### ISSUE THREAD

**Issue by MookBoy** [PaperMC/Paper#1780]
### What behaviour is expected:
I expected to be able to sell items with the sign correctly formatted and correctly placed on the chest.

### What behaviour is observed:
After placing the sign, I get a "chest shop has been created!", but when attempting to sell an item, a "Player is not found!"

### Steps/models to reproduce:
Not sure. 

### Plugin list:
CustomCommands_v3.0.1-BETA.jar
EssentialsX-2.16-pre2.3%20(1).jar
EssentialsXAntiBuild-2.16-pre2.3.jar
EssentialsXGeoIP-2.16-pre2.3.jar
EssentialsXProtect-2.16-pre2.3.jar
EssentialsXSpawn-2.16-pre2.3.jar
EssentialsXXMPP-2.16-pre2.3.jar
holograms-2.6.jar
Jobs4.9.5.jar
mcMMO%20(2).jar
nuvotifier-2.4.1.jar
PermissionsEx-1.23.4%20(1).jar
PluginLibrary-1.2.1.jar
PyrCore_v6.0.6-BETA.jar
Rankup-3.3.1.jar
SuperbVote-0.5.3.jar
Towny.jar
TownyChat.jar
TownyNameUpdater.jar
Vault%20(4).jar
worldedit-bukkit-7.0.0-beta-04.jar
worldguard-legacy-7.0.0-beta-02.jar

### Paper build number:
![image](https://user-images.githubusercontent.com/46274741/50555077-5b201380-0c95-11e9-897e-f4df06b68485.png)

### Anything else:
nope

**Comment by zachbr** [comment]
That isn't paper
