### ISSUE TITLE
Custom AuthLib Yggdrasil API

### ISSUE THREAD

**Issue by Ghost-chu** [PaperMC/Paper#1782]
**Is your feature request related to a problem? Please describe.**
I want use myself Yggdrasil API to replace Mojang cuz i can use that link with blog, wiki and forum and Disocrd.
But it usually need JavaAgent, my IDC disallow me to do that. So is possible support Custom AuthLib Yggdrasil API?
**Describe the solution you'd like**
Add a option in paper.yml

**Describe alternatives you've considered**
Hotload JavaAgent——But plugin will loaded after minecraft server booted...

**Additional context**
Nop

**Comment by Ghost-chu** [comment]
JavaAgent:https://github.com/yushijinhun/authlib-injector/wiki

**Comment by mikroskeem** [comment]
IDC = ? ("I Don't Care" doesn't quite fit in this context)

_Side note: you can load Java agent on runtime as well, see [this](https://github.com/mikroskeem/Shuriken/blob/master/instrumentation/src/main/java/eu/mikroskeem/shuriken/instrumentation/runtime/AgentFactory.java#L106), you could use a wrapper which loads server jar into classpath, loads agent and then calls server's `main(String[] args)`_

**Comment by Ghost-chu** [comment]
@mikroskeem IDC=Internet Data Center in there, and my idc disallow me to change server core or edit args

**Comment by DoNotSpamPls** [comment]
Unofficial opinion: I think this is way too niche to make an appearance as a config option. You could just edit the source code yourself to use your thing instead of the yggdrasil api

**Comment by electronicboy** [comment]
Bypassing mojangs authentication is not something we're inclined to support, nor are we going to write API which only a handful of people would use
