### ISSUE TITLE
TPS down on havesting

### ISSUE THREAD

**Issue by Zzheyd** [PaperMC/Paper#1787]
Hi,

I'm using the latest version of paper on my public server, on normal using the tps is around 18~20.

But, when player harvesting a lot of carrot for example, tps down to 5~6 !
(http://image.noelshack.com/fichiers/2019/01/4/1546536595-2019-01-03-18-29-30.png)

Paper.yml : https://hastebin.com/epodiweqej.coffeescript
Spigot yml : https://hastebin.com/nenihajudu.cpp
Bukkit.yml : https://hastebin.com/gabetemonu.coffeescript
Server.pro : https://hastebin.com/numuyiwari.bash

If you have any idea for healping my server :/

Thx you !

**Comment by electronicboy** [comment]
Please use the forums/IRC/Discord for support with timings (and provide timings), this issue tracker is designed for issues and bugs with the server software, support for stuff like timings on the tracker only leads to flooding peoples email inboxes needlessly
