### ISSUE TITLE
Server crashed unsure of cause using latest Paper 492 for Minecraft 1.13.2

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#1789]
Server crashed here's the report, what caused it? - https://pastebin.com/puqtxK0E
Here's the server log with the errors - https://pastebin.com/28jM7gg5

**Comment by axemwa** [comment]
If u need more details just ask, sorry I had to make this report quick, I'm going out for a while

**Comment by electronicboy** [comment]
The server was trying to clone an itemstack, yet threw an exception due to a concurrent modification (aka: something is modifying this item as we iterate it), given that the clone methods do not mutate the data structure, I believe it's pretty safe to state that you have a plugin that is likely messing with inventory contents async

```
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_192]
    at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_192]
    at net.minecraft.server.v1_13_R2.NBTTagCompound.clone(NBTTagCompound.java:374) ~[patched_1.13.2.jar:git-Paper-492]
```

**Comment by axemwa** [comment]
Oh it must be the same issue thats happening here https://github.com/PaperMC/Paper/issues/1694
that u helped me with last time but I couldn't end up finding out which plugin it was since it only seemed to occur at random but I have a good feeling its the multiinv plugin I mentioned in that other link that's doing it as its a world inventory manager which does seem to affect item stacks according to what it looks like in the player inv storage yml [here](https://pastebin.com/cW7hd1fW)

So I will start looking for another world inventory manager to see if that helps, I just put in a request to a fairly new world inventory manager's author to add a converter for me for my old world inventory manager plugin so that I don't have to manually transfer all the player inventories over

**Comment by axemwa** [comment]
I have 1 more question, not sure if it's an issue with paper so I'll ask first 
for some reason when I type restart in my server console sometimes this comes up it never used to happen
![image](https://user-images.githubusercontent.com/37608633/50686064-b3775c80-106b-11e9-8f90-cbb9813b49fc.png)

My restart script in spigot is 

./start.bat

My startup flags are 

@echo off
java -Xms4G -Xmx4G -jar D:\mcss\servers\CivcraftBETA\paperclip.jar
EXIT

The file is called 
start.bat

**Comment by electronicboy** [comment]
Try removing the ./

**Comment by axemwa** [comment]
thanks again just got this msg, something must have changed in recent updates, either that or regerating my server yml files did something cause i used to be able to use ./
