### ISSUE TITLE
Huge amount of passive mobs

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#179]
version git-Paper-628 (had similar issue on earlier versions)

Passive mobs spawn like crazy from time to time. My entity count is around 7000 with ~50 people online. Down to ~5500 after butchering all hostile entities. Warmroast shows all passive mobs taking up around 12% CPU. (Used to be around 3% in 1.8)

Passive mob spawn is at 10 & 300 spawn interval + 4 activation range.
Hostile mob spawn is at 50 & 4 spawn interval (no issues with hostile mobs)

Also, we are using some plugin code to remove some types of entities (those prone to being farmed like sheep and cow) in close proximities to players if their count is over a threshold. Could occasional mass use of Entity::remove mess with paper's removing of entities?

**Comment by zachbr** [comment]
Duplicate of GH-138. Please read through that and provide any additional information you feel is relevant.
