### ISSUE TITLE
Sand Behaving Incorrectly (Doesn't correctly abide by physics)

### ISSUE THREAD

**Issue by Ayymoss** [PaperMC/Paper#1790]
### What behaviour is expected:
Place sand, it falls. 

### What behaviour is observed:
Place sand, it hovers in the air, place sand next to it (It updates) and it disappears, relog and it appears, but where it was and not on the floor as you'd expect.
See a video: https://youtu.be/E3KpsogGnUM

### Steps/models to reproduce:
Place sand in the air. (Possibly gravel?) 

### Plugin list:
https://i.imgur.com/m1ChwXo.png

### Paper build number:
This server is running Paper version git-Paper-492 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Anything else:
Possible that this happens with any block that is affected by in-game physics, however, I only tested Sand.

It's also entirely possible it's one of my plugins, but I'm not sure which one it would be?

**Comment by electronicboy** [comment]
Cannot replicate, I'd suggest trying to remove plugins in batches and work out the cause

**Comment by Ayymoss** [comment]
I'm an idiot. It turns out it was a region I created, after going through all my plugins and finding out it was localised to WorldGuard/WorldEdit I started deleting configs slowly and found that it was the regions.yml in worlds folder. After that, it now works fine. 

This 'bug' was unrelated to Paper, Spigot or WorldGuard but my own fault. This has since been resolved. Thank you.
