### ISSUE TITLE
Chunk - Entity - Despawn Entity

### ISSUE THREAD

**Issue by FranFrau** [PaperMC/Paper#1792]
### What behaviour is expected:
https://pastebin.com/FJceriW7

### What behaviour is observed:
https://pastebin.com/FJceriW7

### Steps/models to reproduce:
error

### Plugin list:
Plugins (15): CS-CoreLib, ElectricSpawners, EmeraldEnchants, Essentials, EssentialsChat, EssentialsSpawn, ExoticGarden, ExtraGear, ExtraHeads, LuckPerms, PotionCreation, Slimefun, SlimefunOres, Vault, ViaVersion

### Paper build number:
This server is running Paper version git-Paper-1574 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT

**Comment by electronicboy** [comment]
Duplicate of #1302 as the error message stated...
