### ISSUE TITLE
Players Kicked when selecting player heads (1.13.2)

### ISSUE THREAD

**Issue by PossumLover** [PaperMC/Paper#1794]
### What behaviour is expected:
___Not to be kicked from server when selecting certain items in your inventory___

### What behaviour is observed:
___When players select a player head or a skulker box which contains a player head they are kicked from the server___

### Steps/models to reproduce:
___Left clicking on a player head or a skulker box containing one. Images https://imgur.com/a/bAh1wg5___

### Plugin list:
___Advanced Ban, BetterBanners, EasyBackup, Luckperms, Mobheads, Staff+, Vault, VaultChatFormatter, WorldEdit___

### Paper build number:
___git-Paper-493 (MC: 1.13.2)___

### Anything else:
___May not be helpful but when a player is kicked it does not create any errors in the console just says that the player left the game.___

**Comment by electronicboy** [comment]
Error suggests that the kick was observed by the client and not by the server itself, could you obtain client logs? Can you replicate this issue without plugins?

**Comment by PossumLover** [comment]
I found the source of the issue. It was an error relating to Velocity's compression of packets. Turning compression off fixed the issue.
