### ISSUE TITLE
Maps freeze once every few seconds

### ISSUE THREAD

**Issue by Joiubaxas** [PaperMC/Paper#1796]
### What behaviour is expected:
For maps to update smoothly without any freezing as they do on Spigot.

### What behaviour is observed:
On Paper maps freeze every few seconds.

### Steps/models to reproduce:
Send map packets.

### Plugin list:
Only my map plugin I am developing.

### Paper build number:
This server is running Paper version git-Paper-498 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Anything else:
Video of maps updating in
Paper (that's where the freezing happens) 
https://www.youtube.com/watch?v=bbo6lLCZANY

Spigot (regular expected behaviour)
https://www.youtube.com/watch?v=-pFELAXMGKk

**Comment by zachbr** [comment]
How are you sending map packets?
Some sample code would really help here. It doesn't need to be your plugin, but just some basic tester plugin we could run and reproduce with. The details of _how_ matter here.

**Comment by Joiubaxas** [comment]
There is quite a lot of code that goes into this so it would take time for me to rewrite it since there is a lot of stuff that doesn't have anything to do with sending packets in the code. This is my best explanation if this doesn't help I will try to recreate simplest code I can.

For every map I have a MapRenderer with contextual set to true. That means that every player gets it's own MapRenderer for every map. Since MapRenderer can only update every 10 ticks I have scheduled SyncRepeatingTask which runs every 4 ticks. The SyncRepeatingTask calls a method which sends a packet called PacketPlayOutMap. I'm not using reflection for NMS. I have an interface and classes for every NMS version.

Edit: SyncRepeatingTask is called every 2 ticks and Maps are updated every 5 ticks. I reserve one call of the SyncRepeatingTask for creating the image other one for updating the display. So the method generates image > updates display > generates image > updates display > image > updates display, but I don't think that's important for the issue.

**Comment by zachbr** [comment]
Most likely caused by https://github.com/PaperMC/Paper/blob/b68b28243987b3a009511570f1b59678ace06ea4/Spigot-Server-Patches/0110-Improve-Maps-in-item-frames-performance-and-bug-fixe.patch#L40-L41

**Comment by Joiubaxas** [comment]
Could you send me a build of paper which doesn't contain this patch so I can test with my plugin? I tried to build paper myself but I have some problems with Java path not working.

**Comment by electronicboy** [comment]
Two builds here:

ideally test this first, which just removes the change which Z highlighted: https://keybase.pub/electronicboy/builds/paper/paper-1.13.2-RedMapImprovements.jar
this one removes the full patch: https://keybase.pub/electronicboy/builds/paper/paper-1.13.2-NoMapImprovements.jar

This is pretty complex to diagnose without reproduction code, especially when it sounds like you're already fighting against the implementation, somewhat makes some of this patch seem highly irrelevant, but, we have no idea what your code is doing

**Comment by aikar** [comment]
we can likely drop that 1 line. that was optimizations I made years ago and that code is now different. but rest of the patch is still good.

ultimately, we are slowing down the map update rate. So maybe we can make it a config instead?

**Comment by asiekierka** [comment]
That wouldn't be a bad idea, IMO. I'm of the opinion that plugins should control update rates for custom maps themselves, if possible, because the map update rate slowdown is probably sensible for pure vanilla maps but less so for plugin-extended maps.

**Comment by aikar** [comment]
could also use fast rate for custom renders, delayed on vanilla

**Comment by asiekierka** [comment]
I'd say adding a way to control the rate in Paper API, if possible, would be an idea worth considering. But this could also work.

**Comment by Joiubaxas** [comment]
Tried the first build which had only one change. I observed that the freezing still happened, but the time maps were freezon was shorter. Tried the build which was without the whole map patch observed behaviour same as in Spigot 1.13.2.

**Comment by aikar** [comment]
Fixed in 595+
