### ISSUE TITLE
Strack trace cause by plugin but the trace itself has some formatting issues.

### ISSUE THREAD

**Issue by Narimm** [PaperMC/Paper#1797]
### Link/paste of stack trace

`13:29:16 [PLAYER_COMMAND] MayaArcana: /c
13:29:28 --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASHstr_repeat(" ", strlen(" "))- git-Paper-481 (MC: 1.13.2) ---
13:29:28 The server has not responded for 10 seconds! Creating thread dump
13:29:28 ------------------------------
13:29:28 Server thread dump (Look for plugins here before reporting to Paper!):
13:29:28 ------------------------------
13:29:28 Current Thread: Server thread
13:29:28         PID: 30 | Suspended: false | Native: false | State: RUNNABLE
13:29:28         Stack:
13:29:28 str_repeat(" ", strlen("                "))java.util.HashMap$TreeNode.find(HashMap.java:1864)
13:29:28 str_repeat(" ", strlen("                "))java.util.HashMap$TreeNode.find(HashMap.java:1874)
13:29:28 str_repeat(" ", strlen("                "))java.util.HashMap$TreeNode.find(HashMap.java:1874)
13:29:28 str_repeat(" ", strlen("                "))java.util.HashMap$TreeNode.find(HashMap.java:1874)
13:29:28 str_repeat(" ", strlen("                "))java.util.HashMap$TreeNode.getTreeNode(HashMap.java:1886)
13:29:28 str_repeat(" ", strlen("                "))java.util.HashMap.getNode(HashMap.java:576)
13:29:28 str_repeat(" ", strlen("                "))java.util.HashMap.get(HashMap.java:557)
13:29:28 str_repeat(" ", strlen("                "))org.bukkit.craftbukkit.v1_13_R2.util.CraftLegacy.toLegacy(CraftLegacy.java:151)
13:29:28 str_repeat(" ", strlen("                "))org.bukkit.craftbukkit.v1_13_R2.util.CraftLegacy.toLegacyData(CraftLegacy.java:140)
13:29:28 str_repeat(" ", strlen("                "))org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.toLegacyData(CraftMagicNumbers.java:119)
13:29:28 str_repeat(" ", strlen("                "))org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getData(CraftBlock.java:128)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.block.BlockCollection.add(BlockCollection.java:25)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.challenge.ChallengeLogic.islandContains(ChallengeLogic.java:236)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.challenge.ChallengeLogic.tryCompleteOnIsland(ChallengeLogic.java:252)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.challenge.ChallengeLogic.tryComplete(ChallengeLogic.java:210)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.challenge.ChallengeLogic.completeChallenge(ChallengeLogic.java:161)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.command.challenge.ChallengeCompleteCommand.execute(ChallengeCompleteCommand.java:37)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.utils.command.CompositeCommand.execute(CompositeCommand.java:129)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.utils.command.BaseCommandExecutor.onCommand(BaseCommandExecutor.java:42)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.command.ChallengeCommand.onCommand(ChallengeCommand.java:57)
13:29:28 str_repeat(" ", strlen("                "))org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
13:29:28 str_repeat(" ", strlen("                "))org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
13:29:28 str_repeat(" ", strlen("                "))org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732)
13:29:28 str_repeat(" ", strlen("                "))org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.performCommand(CraftPlayer.java:449)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.menu.SkyBlockMenu.onClickChallengeMenu(SkyBlockMenu.java:1055)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.menu.SkyBlockMenu.onClick(SkyBlockMenu.java:785)
13:29:28 str_repeat(" ", strlen("                "))us.talabrek.ultimateskyblock.event.MenuEvents.guiClick(MenuEvents.java:28)
13:29:28 str_repeat(" ", strlen("                "))com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor649.execute(Unknown Source)
13:29:28 str_repeat(" ", strlen("                "))org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
13:29:28 str_repeat(" ", strlen("                "))co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
13:29:28 str_repeat(" ", strlen("                "))org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
13:29:28 str_repeat(" ", strlen("                "))org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
13:29:28 str_repeat(" ", strlen("                "))net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2296)
13:29:28 str_repeat(" ", strlen("                "))net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
13:29:28 str_repeat(" ", strlen("                "))net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
13:29:28 str_repeat(" ", strlen("                "))net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
13:29:28 str_repeat(" ", strlen("                "))net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$3134/865637096.run(Unknown Source)
13:29:28 str_repeat(" ", strlen("                "))java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
13:29:28 str_repeat(" ", strlen("                "))java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:29:28 str_repeat(" ", strlen("                "))net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109)
13:29:28 str_repeat(" ", strlen("                "))net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)
13:29:28 str_repeat(" ", strlen("                "))net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
13:29:28 str_repeat(" ", strlen("                "))net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
13:29:28 str_repeat(" ", strlen("                "))net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
13:29:28 str_repeat(" ", strlen("                "))java.lang.Thread.run(Thread.java:748)
13:29:28 ------------------------------
13:29:28 --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
13:29:28 ------------------------------
13:29:30 The main thread failed to respond after 10 seconds
13:29:30 Possible cause: uSkyBlock
13:29:30 -------------------------------------
13:29:30 Name: Server thread | Id: 30 | Suspended: false | State: RUNNABLE | Owner: Minecraft
13:29:30 
13:29:30 Owned monitors:
13:29:30 - us.talabrek.ultimateskyblock.block.BlockCollection[Orange Alpha] at us.talabrek.ultimateskyblock.block.BlockCollection.add(BlockCollection.java:24)
13:29:30 Stack trace:
13:29:30 str_repeat(" ", strlen(" "))at java.util.HashMap$TreeNode.find(HashMap.java:1864)
13:29:30 str_repeat(" ", strlen(" "))at java.util.HashMap$TreeNode.find(HashMap.java:1874)
13:29:30 str_repeat(" ", strlen(" "))at java.util.HashMap$TreeNode.find(HashMap.java:1874)
13:29:30 str_repeat(" ", strlen(" "))at java.util.HashMap$TreeNode.getTreeNode(HashMap.java:1886)
13:29:30 str_repeat(" ", strlen(" "))at java.util.HashMap.getNode(HashMap.java:576)
13:29:30 str_repeat(" ", strlen(" "))at java.util.HashMap.get(HashMap.java:557)
13:29:30 str_repeat(" ", strlen(" "))at org.bukkit.craftbukkit.v1_13_R2.util.CraftLegacy.toLegacy(CraftLegacy.java:151)
13:29:30 str_repeat(" ", strlen(" "))at org.bukkit.craftbukkit.v1_13_R2.util.CraftLegacy.toLegacyData(CraftLegacy.java:140)
13:29:30 str_repeat(" ", strlen(" "))at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.toLegacyData(CraftMagicNumbers.java:119)
13:29:30 str_repeat(" ", strlen(" "))at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getData(CraftBlock.java:128)
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.block.BlockCollection.add(BlockCollection.java:24) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.islandContains(ChallengeLogic.java:236) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.tryCompleteOnIsland(ChallengeLogic.java:252) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.tryComplete(ChallengeLogic.java:210) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.completeChallenge(ChallengeLogic.java:161) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.command.challenge.ChallengeCompleteCommand.execute(ChallengeCompleteCommand.java:37) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.utils.command.CompositeCommand.execute(CompositeCommand.java:129) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.utils.command.BaseCommandExecutor.onCommand(BaseCommandExecutor.java:42) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.command.ChallengeCommand.onCommand(ChallengeCommand.java:57) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
13:29:30 str_repeat(" ", strlen(" "))at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
13:29:30 str_repeat(" ", strlen(" "))at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732)
13:29:30 str_repeat(" ", strlen(" "))at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.performCommand(CraftPlayer.java:449)
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.menu.SkyBlockMenu.onClickChallengeMenu(SkyBlockMenu.java:1055) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.menu.SkyBlockMenu.onClick(SkyBlockMenu.java:785) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at us.talabrek.ultimateskyblock.event.MenuEvents.guiClick(MenuEvents.java:28) [uSkyBlock]
13:29:30 str_repeat(" ", strlen(" "))at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor649.execute(Unknown Source)
13:29:30 str_repeat(" ", strlen(" "))at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
13:29:30 str_repeat(" ", strlen(" "))at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
13:29:30 str_repeat(" ", strlen(" "))at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
13:29:30 str_repeat(" ", strlen(" "))at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
13:29:30 str_repeat(" ", strlen(" "))at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2296)
13:29:30 str_repeat(" ", strlen(" "))at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
13:29:30 str_repeat(" ", strlen(" "))at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
13:29:30 str_repeat(" ", strlen(" "))at net.minecraft.server.v1_13_R2.Play...`
___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
Many  -  some of which are not working well together ....hence the stack.

### Actions to reproduce (if known):
Have a plugin cause a problem and we get the stack...but as you can see it has some issues.
We are aware of why we are getting the error...its the formatting that we are reporting here.

### Paper build number:
481

**Comment by mikroskeem** [comment]
wut in tarnation...

plugins list?

**Comment by BillyGalbreath** [comment]
** *Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.* **

`13:29:16 [PLAYER_COMMAND] MayaArcana: /c 13:29:28 --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH`

**Comment by electronicboy** [comment]
Those are PHP method calls, I'm going to guess that you're using a web panel of some sort? If so I'd take it to them
