### ISSUE TITLE
What is this ?

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#1799]
https://textsaver.flap.tv/lists/2e75

**Comment by zachbr** [comment]
Is your question about the server not responding? The vehicle entity being overwritten at player login? Or what.

**Comment by successed** [comment]
kicked all players. The server crashes.

**Comment by zachbr** [comment]
Server lagged out, watchdog killed it. The stacktraces provide some information as to what it was doing when that happened. If you can find some sort of way for us to reproduce this issue, ie its not just general server load issue, we'll be happy to look into it.

**Comment by successed** [comment]
i have logs..
[2019-01-12-3.log.gz](https://github.com/PaperMC/Paper/files/2752331/2019-01-12-3.log.gz)
[2019-01-12-5.log.gz](https://github.com/PaperMC/Paper/files/2752332/2019-01-12-5.log.gz)
[2019-01-12-4.log.gz](https://github.com/PaperMC/Paper/files/2752333/2019-01-12-4.log.gz)

**Comment by zachbr** [comment]
The fact that it's always the same person causing it suggests to me that their stored vehicle may be corrupt or intentionally broken (Creative mode perhaps?). I suggest you start by removing their player data.

In every single one of the logs you sent, it appears to be a result of the bounding box of the vehicle ridden at login by Leufzeryus

**Comment by successed** [comment]
yes, i removed to all of player Leufzeryus  data  and this fixed. Thanks.

**Comment by zachbr** [comment]
:+1:
