### ISSUE TITLE
Server crashes for no obvious reason

### ISSUE THREAD

**Issue by TitanicFreak** [PaperMC/Paper#18]
My server seems to crash for no obvious reason, and its not reproducable as its random whether it occurs or not. We can go days without crashing. Here's the error.

http://hastebin.com/dojonusezu.vbs

**Comment by Techcable** [comment]
You about a month out of date.
Please update before reporting issues.

**Comment by TitanicFreak** [comment]
Ugh, really hate the new paperclip system, updated anyway. Will report back if another crash occurs.

**Comment by zachbr** [comment]
This also isn't a crash in the traditional sense. This is the server freezing up and watchdog killing it. So the server is spending way too much time on getCubes/getEntities for w/e reason.

**Comment by Techcable** [comment]
@TitanicFreak 
Why do you hate the paperclip system?

**Comment by TitanicFreak** [comment]
I dislike paperclip as I could edit papertools to create custom jars relatively easy, w/ Paperclip I have absolutely no idea how to create custom jars. I mainly wanted v1 timings back instead of v2 timings.

**Comment by Techcable** [comment]
@TitanicFreak 
Use [my script](https://gist.github.com/Techcable/0b491b70347fd46a9e3f) to create custom paperclip jars. [Example for TacoSpigot](https://github.com/TacoSpigot/TacoSpigot/blob/master/package.sh)
Also, timings v2 is way, way, way better than timings v1 in every aspect except user interface.

**Comment by Zbob750** [comment]
You can still do that, just use the source code. All papertools did was make every single user download the entire repo and compile it like a developer, which is pointless. Developers can still do things like that by cloning the repo and making their own jars.

**Comment by aikar** [comment]
v1 timings is buggy and unreliable, you should not downgrade it.

Just ask for help reading the timings in the paper channel if you cant figure it out... but its pretty simple

open the tree on the lag tab and expand until you find where heavy stuff is.

**Comment by TitanicFreak** [comment]
After using v1 timings for literally years now, moving to v2 timings is harder then it looks.

**Comment by Techcable** [comment]
Yeah, itd be nice if @aikar wrote some docs. Even I dont understand it that well :/

**Comment by aikar** [comment]
i'll see about recording a video and adding link to video on the page.

**Comment by TitanicFreak** [comment]
Welp, my server just crashed again with the latest PaperSpigot. 

Log: http://hastebin.com/jabileyuka.vbs

Probably won't help, but hey, you never know.

**Comment by gsand** [comment]
@TitanicFreak Are there any plugins that you recognize in your stack traces?

**Comment by TitanicFreak** [comment]
Any updates of this? Still crashing.

**Comment by zachbr** [comment]
"This also isn't a crash in the traditional sense. This is the server freezing up and watchdog killing it. So the server is spending way too much time on getCubes/getEntities for w/e reason."

This is a known issue with vanilla/craftbukkit/spigot/paper. Typically its caused by an abusive plugin but not always. No, we have no updates at this time.

Also going to clean this issue thread up a bit.

**Comment by TitanicFreak** [comment]
Right, the latest paper with velocity warnings helped me figure out why my server was crashing.

Was apparently my cratekey plugin from picknchew, which causes this crash occasionally.

http://hastebin.com/ohetufukah.avrasm

I think I can handle myself now, thanks for the help!
