### ISSUE TITLE
WGExtender is broken

### ISSUE THREAD

**Issue by Leymooo** [PaperMC/Paper#180]
http://pastebin.com/A7yCY4zs

plugins 
![image](https://cloud.githubusercontent.com/assets/8667294/14228865/0272982c-f92c-11e5-875e-6e35de1aca10.png)
#144

**Comment by zachbr** [comment]
This is an issue with WGExtender registering its commands improperly using the command map directly. The author was made aware of the issue but apparently has no intent to resolve the issue. For more information, please see the original issue GH-17.
