### ISSUE TITLE
Auto-updater.

### ISSUE THREAD

**Issue by TheIntelloBox** [PaperMC/Paper#1801]
Hello ! :D 

Could you add an auto-updater ? I have a connexion and everytime that I download a paperclip, it takes 10 minutes. :D 

Sincerely ! :D
TheIntelloBox. :D

**Comment by MiniDigger** [comment]
How would an auto updater help anything with this? 
It will still take 10 minutes to download...

**Comment by ArtNRG** [comment]
Run this .sh script instead of FTP uploading, it's really fast:

#!/bin/bash
cd /patch/to/your/minecraft/server/
rm paperclip._jar
mv paperclip.jar paperclip._jar
wget https://papermc.io/ci/job/Paper-1.13/lastSuccessfulBuild/artifact/paperclip.jar

**Comment by TheIntelloBox** [comment]
Where should I put it ?

**Comment by ArtNRG** [comment]
> Where should I put it ?

Anywhere you want. I put it inside the server folder.

**Comment by TheIntelloBox** [comment]
I create a Autoupdater.sk file ?

**Comment by ArtNRG** [comment]
> I create a Autoupdater.sk file ?

Yes. It's manual updater actually, but it's fast. You can also run it automatically using cron jobs.

**Comment by mikroskeem** [comment]
>I create a Autoupdater.sk file ?

made my day

**Comment by DenWav** [comment]
We've discussed the idea of auto-updating in the past and are all in agreement, it's not happening.

**Comment by YaCodesDevelopment** [comment]
> wget https://papermc.io/ci/job/Paper-1.13/lastSuccessfulBuild/artifact/paperclip.jar

This doesn't seem to work any longer

**Comment by Proximyst** [comment]
For future note: the PaperMC CI is no longer public, and you should use the latest artifact API available; as of writing, this is v2 (and v1 is set to be removed in November 2021). Please see https://papermc.io/api/docs/ for the latest information on this, and feel free to ask in [our Discord server](https://discord.gg/papermc) anytime.
