### ISSUE TITLE
Error With Essentials And PremiumVanish

### ISSUE THREAD

**Issue by TheCalypso** [PaperMC/Paper#1803]
### What behaviour is observed:
___What you actually saw___
Hello, I just found a problem with Paper, when Essentials and PremiumVanish plugins are loaded at the same time the players wanting to put a command in the chat are automatically evicted with the following message in chat: "The server you've been previously gone, you've been connected to a fallback server." The concern is that there is no problem in the console. 
However there is no problem on Spigot, thank you. 

### Plugin list:
EssentialsX-2.16.0.31 / Protocollib (for PremiumVanish) / PremiumVanish 2.4.1

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
Version Of PaperSpigot: #500

Thank you for helping !

**Comment by zachbr** [comment]
Getting moved to a fallback server would only occur as a result of a communications issue between the proxy server and the backend.

Is the backend server crashing, is it sending some illegal packet combination, is there anything in logs of either the proxy or the backend?

Also, as was mentioned in Discord, PremiumVanish has caused protocol related issues in the past, please ensure your version is up to date.

**Comment by TheCalypso** [comment]
Hello,
I can assure you that the version of PremiumVanish is up to date. However I still think that the concern comes from Paper and then that with Spigot there is no problem

**Comment by zachbr** [comment]
Please provide the information I requested.

**Comment by TheCalypso** [comment]
Hello,
I just found that in the proxy logs, I think you can help me with that: p
https://pastebin.com/mybqtdke

Do not hesitate to tell me if you need something else :)

**Comment by zachbr** [comment]
Unfortunately, all that tells me is that its mangling the packet. It doesn't tell me why.
The author is at least vaguely aware of this issue as they are suggesting users disable the tab complete module in the config if they have this issue.

Given that this is a premium plugin, and one that operates on individual packets via ProtocolLib, there's not a ton of digging that can be done here. If someone who has bought the plugin would like to do some further digging, we will accept feedback and PRs, but it's not like we can just go download this thing and sift through its source code.

**Comment by Artuto** [comment]
I may add that I use Paper 498 and PV 2.4.1 (no essentials but I dont think it should be a problem), and i dont get this so maybe something is wrong in your setup

(not sure if Paper #500 broke smth)

**Comment by TheCalypso** [comment]
Hello, 
What am I supposed to do? If you want the plugin I can send it to you so that you can analyze it?
@Artuto 
If you had read what I put above it is only when it has Essentials and PV AT THE SAME TIME ON THE SERVER!

**Comment by TheCalypso** [comment]
@Artuto 
If you had read what I put above it is only when it has Essentials and PV AT THE SAME TIME ON THE SERVER!

**Comment by zachbr** [comment]
We aren't going to encourage you to distribute premium resources or cooperate should you choose to anyway.
We cannot provide an adequate level of support for premium resources. 

> The author is at least vaguely aware of this issue as they are suggesting users disable the tab complete module in the config if they have this issue.

I'd recommend you just do that and hope the author cares enough to get involved, short of that I wouldn't expect much to change.
