### ISSUE TITLE
Entities clipping into blocks, escaping pens on chunk boundaries

### ISSUE THREAD

**Issue by aeonlamb** [PaperMC/Paper#1806]
### What behaviour is expected:
Mobs should stay inside of their pens, and not mysteriously die to unknown causes.

### What behaviour is observed:
This is a very strange and oddly specific bug, and if I walked through how we discovered what causes it this bug report would be way too long.

Basically, there is a bug in the server that causes mobs to clip into nearby blocks if they attempt to pathfind to a place in another chunk at specific times, which can lead to them dying or escaping from a fenced-off pen. 

### Steps/models to reproduce:
I've attempted to reproduce this on a test server, both with and without plugins, and have had no luck so far. I've only been able to see this occur on our live server, and many of my players have reported similar issues.

There is only one specific area in which one of my fellow staff members was able to repeatedly reproduce this glitch, which helped us understand what causes it. Take a look at these sheep pens:

![2019-01-11_11 27 30](https://user-images.githubusercontent.com/20532513/51055172-ed78bf00-1593-11e9-809e-6570405ad81b.png)

The yellow lines indicate chunk boundaries. What's more, take a look at the other side of this wall (taken in spectator mode, inside of the log wall):

![2019-01-11_11 29 36](https://user-images.githubusercontent.com/20532513/51055247-329cf100-1594-11e9-8aab-a888011c8ed6.png)

Every so often, the sheep in these pens (only the ones on the chunk boundary) will mysteriously suffocate inside of the log wall and die. However, if another layer of grass is added to the other side of the log wall (i.e. two blocks up from where the sheep are), the sheep will no longer clip inside of the wall and die. This seems to suggest that the sheep see it as a valid location to pathfind to for some reason, and somehow end up inside of the wall and suffocate.

It's been reported to me that this happens more often when players are frequently traveling back and forth between one location and another, so chunk loading/unloading seems related to it.

The most important things you need to know are: 
- animal pen, on a chunk boundary (the wall needs to be in the first block of the next chunk over from the pen).
- there needs to be space on the opposite side of the wall that the animals can pathfind to as if the wall were not there
- using poison potions on the animals so they have 1/2 a heart helps test; as they will die the moment they take any damage from anything
- we used coreprotect to log animal deaths which helped us discover that the animals died inside of the wall due to suffocating

I can't guarantee this isn't caused by a plugin, but I don't know what would cause it if it really were a plugin issue.

### Plugin list:
![java_2019-01-16_14-34-18](https://user-images.githubusercontent.com/20532513/51283086-dc68ed00-199b-11e9-95d6-b9c8bb4232a4.png)

### Paper build number:
Paper-498 (1.13.2). This has happened on several previous 1.13 builds as well. 

### Anything else:
Apologies if this ends up being a plugin problem, but due to the random nature of this bug I have had a hard time reproducing it in an isolated environment. The mobs' pathfinding is totally random so you basically just have to get lucky (or unlucky?) to witness this happening. I can't think of any plugins that could affect this.

**Comment by aeonlamb** [comment]
Update on this. I've managed to reproduce this bug in an environment with no plugins. This is a bug in Paper (or perhaps upstream). It doesn't affect vanilla minecraft from my testing.

Another detail that's crucial to reproducing this: teleporting back and forth does not seem to cause this, only traveling into and out of the chunks naturally does. I.e. by walking or flying from one place to another. It seems as though the order in which the chunks load matters, but I can't be sure.

I created a testing environment specifically to test for this bug, since it's dependent on RNG it can be difficult to reproduce in a consistent manner unless you're testing hundreds of entities at once. The world file is attached here:

[paper-1806.zip](https://github.com/PaperMC/Paper/files/2787354/paper-1806.zip)

As far as I know, config settings don't matter at all, I used the defaults. Again, this was tested on Paper-498 (1.13.2), but is also known to have affected previous 1.13 builds. There are instructions on signs in the world, if my previous explanations of the bug did not suffice.

**Comment by carlpoole** [comment]
I think I noticed this happening with minecarts as well. I've had a couple of different rail setups where the last piece of powered rail sat pointing into a chunk border. Sometimes when I entered the chunks I noticed that the minecart had stopped making its way around because it had phased inside the block in the next chunk and was stuck. I'm not sure if its related but it sounds very similar

**Comment by electronicboy** [comment]
https://bugs.mojang.com/browse/MC-2025 potentially? We should have a patch to combat that one, however

**Comment by aeonlamb** [comment]
It does seem similar to mc-2025, however in the testing world I linked I tried it on a vanilla 1.13.2 server and couldn't reproduce the same results there. Although due to its randomness there's a chance I just got unlucky, I did test for like ~30 minutes or something on vanilla though

**Comment by aeonlamb** [comment]
Hello, it's been something like a month since I reported this, but I spent some more time doing tests recently. I have a few things to update with here:

- This still occurs in recent builds of Paper for 1.13.2 (tested in build 525)
- This does NOT occur on latest versions of craftbukkit or spigot, it is a problem ONLY on paper
- It has nothing to do with chunks loading/unloading, this can occur even when you are standing completely still

I actually made a video demonstrating this bug. [Watch it here](https://www.youtube.com/watch?v=MYYJD4ZHv74) if it'll help you understand better.

Basically, the nature of the bug is like this:

Player is in a chunk distant from animal pen on chunk boundary, let's say the player is south of this animal pen. The animal pen is situated on a chunk boundary, in this example the chunk boundary would have to be to the north. The wall forming the north-most part of the animal pen is in the south-most block of the chunk directly north of the animal pen. So, all the other fences or what have you and all of the animals in the pen are in one chunk, but the north wall is in another chunk. On the other side of that wall, there needs to be grass (or, potentially, any other solid block the animals can pathfind to) exactly one block above the floor of the animal pen itself, so that if the wall were removed animals would pathfind to it normally. The player has to be distant enough from the pen so that the chunk with the wall and raised grass platform in it is the chunk on the very edge of the currently loaded chunks.

Now, with this exact setup, if there are enough animals in the pen, and you wait long enough, you will begin to see animals dying. You don't even need to move. They just go inside of the wall and die. If my explanation was too confusing, just watch the video, hopefully it will help you understand better.

As I mentioned before, I tested this on spigot & craftbukkit as well as a vanilla 1.13.2 server. This did not occur on any of them, I can only reproduce it on Paper.

**Comment by aikar** [comment]
can you test vs 1.12? i wonder if mojang conflicted with our patch to solve collision issues in 1.13

**Comment by aeonlamb** [comment]
I don't think I can test against 1.12 at the moment, but I'm pretty sure it didn't happen on 1.12... it's kind of a niche bug but with enough players over time you'll hear word of it happening, and we never had those issues in 1.12 as far as I can remember

**Comment by aeonlamb** [comment]
I tested this on paper for 1.12, I can't seem to get the bug to occur there. Tested on build 1604.

It is a problem in paper 1.13

**Comment by aeonlamb** [comment]
I tried this out really quick after that recent patch and it seems that patch did not fix this bug. The sheep in my testing environment still die. :( (tried on paper build 566 w/ no plugins again, just to be clear)

**Comment by aeonlamb** [comment]
Hello, it's much later now, but I decided to look into this again to see if I could find out more about this bug.

I found out a few things which should help to fix this, I hope.

- Disabling async chunk loading / async chunk generation does not affect the bug, it still happens
- The bug still occurs on Paper 1.13.2 build 636 (latest for 1.13 at time of writing)
- I cannot initially reproduce the bug on 1.14.x, although chunk loading has changed which may be why

But, most importantly, I think I have found the precise build / commit which causes this bug. I tried many different builds of paper 1.13, until I could narrow it down to just one build on which this first started occurring. This bug exists on Paper 1.13 build 196 and after. Before build 196, I could not reproduce this issue. [Here is the commit that supposedly causes this issue](https://github.com/PaperMC/Paper/commit/aabff6632d8b6f27998c3c8c0eb680ec837cef5f).

I don't know what exactly about this commit is causing the issue, but it is clear it is something to do with chunk loading. Hopefully knowing when this first started occurring is helpful to fix it.

**Comment by aikar** [comment]
hmm....

That patch wasn't meant to change any behavior, but I see a very bad looking change:
https://github.com/PaperMC/Paper/commit/aabff6632d8b6f27998c3c8c0eb680ec837cef5f#diff-d99ed16b117f396cb2896e47f9209c41R21

That could explain quite a few issues.
Not loading correct neighbor coords

**Comment by aeonlamb** [comment]
It's so late here, but I noticed the latest patch and decided to test it out right away. I'm happy to say, I think that one line of code did it. This has been one of the worst bugs plaguing my server (and i'm sure, plenty of others on 1.13), and it looks like it's finally fixed. Thanks so much!
