### ISSUE TITLE
Cartographer generating "map" trade causes lag spike

### ISSUE THREAD

**Issue by Zenya4** [PaperMC/Paper#1810]
Timings or Profile link:
https://timings.aikar.co/?id=60d7c3df1b3346219833caf3793db555

Description of issue:
Only applicable for "Cartographer" type villagers. When a player trades with a cartographer, and unlocks the final trade (usually an exploration map), there is a lag spike for a few seconds before the trade is unlocked. During this period the server freezes and nothing can be done. Server recovers after a few seconds.

Cause: Server has to generate a valid exploration map for cartographer, for player to trade with. This is very resource intensive in general. On a PaperSpigot server with no plugins, this takes around 2-3 seconds and the server freeze generally only experienced by a few players (but it is recorded by the React lag monitoring plugin in /re monitor). With EpicWorldGenerator plugin, custom chunks are generated so the server has to work very hard to scan through all these chunks to find a valid structure. It will always never find it as all chunks are custom-generated by the plugin, with no structures, and the server will freeze for around 12 seconds before recovering.

Solution:
Generate the map async to server load over a longer period of time, rather than stressing out the server by forcing it to generate a map instantly. Alternatively, add an option in the config to disable or modify the final trade for the exploration map (pre-generate?) to make it less resource intensive.

Plugin list:
AAC, antiraildupe, BlocksHub, ClaimLevels, CMI, CMIEInjector, CombatLogX, ConditionalCommands, CoreProtect, CraftingStore, CrateReloaded, CrazyAuctions, CrazyEnchantments, DiscordSRV, EpicWorldGenerator, FastAsyncWorldEdit, GriefPrevention, HamSteakAddon, HeapDump, iDisguise, iDisguiseAdditions, LiteBans, LuckPerms, LWC, mcMMO, OnlyProxy, PandaWire, PlayerVaults, ProtocolLib, ProtocolSupport, React, ShopGUIPlus, SpigotLib, TokenManager, Vault, ViaVersion, Votifier, WorldEdit, WorldGuard

bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml: https://hastebin.com/ujatayamar.coffeescript
spigot.yml: https://hastebin.com/kidizuvimo.cpp
paper.yml: https://hastebin.com/oqaxiburig.coffeescript
server.properties: https://hastebin.com/cuzifapako.bash

Other helpful links:
EpicWorldGenerator: https://www.spigotmc.org/resources/epicworldgenerator-1-8-8-1-13-2-support-all-update-aquatic-features.8067/
React: https://www.spigotmc.org/resources/react-smart-server-performance.21057/

Paper build number:
Paper version git-Paper-455 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

How to reproduce:
1. Summon a Cartographer or find a village with a cartographer villager.
2. Turn timings on (/timings on)
3. Turn React's lag monitoring capabilities on (/re monitor)
4. TPS is the green number on the left of the display. When the server freezes it becomes an (!) with a number beside it to show the number of seconds the server is freezing for.
5. Start trading with the cartographer. Monitor the TPS closely with React
6. When the final trade is unlocked (exploration map trade), issue will occur

I sincerely hope this issue can be fixed, as it also occurs (but less severely) on a PaperSpigot server with no plugins. Thank you for your time.

**Comment by Zenya4** [comment]
Hello,

No rush, but I would like to know if the developers have any intention of fixing this issue anytime soon. It is really becoming an issue as more and more players know about this and are doing it on purpose during peak hours to lag the server. 

If the developers don't intend to fix this, I will make a plugin for my server specifically to block that final trade so that this issue can never occur. I do hope that this will be resolved, for the general community of PaperSpigot, though. 

Should any more information be required to reproduce this bug, feel free to let me know.

Regards,
Zenya

**Comment by zachbr** [comment]
Please confirm this issue is still occurring so we know how to proceed.

**Comment by Zenya4** [comment]
Yes, it is still an occurring issue. However, I have found an option in paper.yml to disable cartographer map trades so it’s a temporary fix for my server. Something should still be done about the main lag spike on map generation though.

**Comment by Zenya4** [comment]
Do you still need any additional info?

**Comment by hurrgurl** [comment]
> Yes, it is still an occurring issue. However, I have found an option in paper.yml to disable cartographer map trades so it’s a temporary fix for my server. Something should still be done about the main lag spike on map generation though.

Having similar issues in 1.15 paper

Did you ever find an alternative to disabling cartographer map trades?

**Comment by perseus5** [comment]
Probably #2781 #2312

**Comment by electronicboy** [comment]
Tracked more generically by #2312
