### ISSUE TITLE
Asynchronous Async command

### ISSUE THREAD

**Issue by jimmyr57000** [PaperMC/Paper#1811]
Hello, 

I have a problem with my main infrastructure plugin
I went to PaperSpigot simply because the spigot version 1.12 to ping player problem..

This is my error: https://hastebin.com/icihiqibat.md
The problem and present that when I use PaperSpigot
Thank you in advance to the person who will help me ..

### What behaviour is observed:
The mistake is not always present

### Steps/models to reproduce:
On execute command..

### Paper build number:
git-Paper-1526 (1.12.2 R0.1)

**Comment by kamcio96** [comment]
fix your plugin, don't use async thread for commands

**Comment by aikar** [comment]
well this is def an interesting stack. 

Ultimately yes your plugin needs to stop dispatching commands async. We normally protect against this and force them sync, but its actually not the command thats triggering it, its the broadcast.

what's in your broadcast message? Any command selectors like @e?

**Comment by jimmyr57000** [comment]
Hello,

Thanks you for your help.
My system command use a custom CommandManager
here is the line where of the command is executed

Code: https://hastebin.com/azobafoway.cs

I have remplaced: 

Old: execute.runTaskAsynchronously(FCGameServer.instance);
New: execute.runTask(FCGameServer.instance);

Working.. 

Thanks you !

**Comment by aikar** [comment]
Yes that is the correct solution.

In future, please don't use hastebin, I can't open those links! :( use https://gist.github.com
