### ISSUE TITLE
Server has stopped responding.

### ISSUE THREAD

**Issue by brandonlooksdumb** [PaperMC/Paper#1812]
Hi, my server crashes frequently and I don't know how to fix it. Hopefully someone will help, thank you.

### Link/paste of stack trace
https://pastebin.com/veEiKCXf

### Plugin list:
http://prntscr.com/ma6wxl

### Actions to reproduce (if known):
Often, my server crashes unexpectedly. For example everyone plays normal and then suddenly no one moves and after 5 seconds the server is spam by the errors of the pastebin and crash.

### Paper build number:
http://prntscr.com/ma6vp1

**Comment by electronicboy** [comment]
Because it's an easy to spot issue, I'll tell you, but in the future, if you desire support, you should use a supported version, as this issue has been fixed for a while on paper itself.

Eitherway, caused by skungee
