### ISSUE TITLE
#506 the new problem in chunk load maps

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#1813]
i use the xray mode because i have crack server and
screen shoots : 
enginemode:2 - https://prnt.sc/ma789b, https://prnt.sc/ma7aeo
engine mode :1 http://prntscr.com/ma7gsq - http://prntscr.com/ma7jn9
and my server version latest build #506

**Comment by successed** [comment]
@electronicboy check this new you updates..

**Comment by electronicboy** [comment]
Chunks not rendering is a client issue, the only change in the new build is that LOAD will now request the chunks to load, meaning that servers with async chunk loading will effectively act as a mixture between WAIT and LOAD
