### ISSUE TITLE
jump event not fire for plugins

### ISSUE THREAD

**Issue by Stivencannor** [PaperMC/Paper#1814]
### What behaviour is expected:
i think ,paper not fire jump event for other plugins. 

### What behaviour is observed:
for example jump not working for SimpleElevator. before update paper on my server, elevator was working! and there is no error on console. i have updated simpleElevator to newer version too!

### Plugin list:
SimpleElevator , Essentials and ...

### Paper build number:
 This server is running Paper version git-Paper-507 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
 Previous version: git-Paper-503 (MC: 1.13.2)
 Checking version, please wait...
 You are running the latest version

### Anything else:
pls write new plugin to test, and fix it.

**Comment by Stivencannor** [comment]
please check this:
[https://github.com/PaperMC/Paper/pull/1587](https://github.com/PaperMC/Paper/pull/1587)

**Comment by TheFlagCourier** [comment]
Looks like SimpleElevator is designed for 1.9 (_unless you have a newer source_). You'll want to contact it's developer to see about fixing it. Also, the PR you reference is not merged or closed yet, so plugins cannot implement it.

**Comment by electronicboy** [comment]
This plugin doesn't use the jump event, it uses the move event, I'm not aware of any changes around here that would break it
