### ISSUE TITLE
Falling sand not behaving like vanilla

### ISSUE THREAD

**Issue by Frogperson** [PaperMC/Paper#1818]
### What behavior is expected:
Falling sand should behave the same as vanilla and become a block when it lands.

### What behavior is observed:
Falling sand entity pops off into item form when it lands on a retracting piston.

### Steps/models to reproduce:
![image](https://user-images.githubusercontent.com/17440180/51584050-8adfc700-1ea1-11e9-8613-93df0e0855c3.png)

### Plugin list:
None

### Paper build number:
504

### Anything else:
It seems to happen when the falling block lands on the piston in the same tick that the piston starts to retract.

**Comment by Drc-DEV** [comment]
This heavily affects tnt sand cannons in factions servers. Can confirm this is a problem also in build 614 and in build 1612 of 1.12.2 paper

**Comment by kickash32** [comment]
Does not occur on build 65 of 1.14.2

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
