### ISSUE TITLE
Lightning only spawning fire on the block it hit

### ISSUE THREAD

**Issue by Frogperson** [PaperMC/Paper#1819]
### What behaviour is expected:
When lightning strikes in vanilla, it sets random blocks on fire in a 3x3 around it.

### What behaviour is observed:
Lightning is only lighting the center block of that 3x3 on fire.

### Steps/models to reproduce:
Stand in the center of a flat 3x3 section of blocks (netherrack is nice because the fire won't go out)
`/summon minecraft:lightning_bolt`

### Plugin list:
None

### Paper build number:
504

**Comment by BillyGalbreath** [comment]
Is your server in easy difficulty? Lightning will only do those random fires around the center in normal or hard difficulties.

**Comment by Frogperson** [comment]
I don't remember what my difficulty was, but I think it was just left at default for both Paper and Vanilla. I've never heard that about difficulty, but sure enough, that seems to be it! Thank you :)
