### ISSUE TITLE
PlayerTeleportEvent is not be firing.

### ISSUE THREAD

**Issue by andrew121410** [PaperMC/Paper#1820]
### What behaviour is expected:
That when using player.teleport() is should fire PlayerTeleportEvent if I’m not mistaking.

### What behaviour is observed:
That PlayerTeleportEvent did not run at all.

### Steps/models to reproduce:
   Download the latest Paper Spigot for 1.12.2

### Plugin list:
https://ibb.co/72Zj63n

### Paper build number:
[17:23:04 INFO]: This server is running Paper version git-Paper-1596 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[17:23:04 INFO]: Previous version: git-TacoSpigot-"f8ba67d6" (MC: 1.12.2)
[17:23:04 INFO]: Checking version, please wait...
[17:23:06 INFO]: You are running the latest version

### Anything else:
All I wanted too do is get the player location before the player teleports

**Comment by electronicboy** [comment]
The code for the CraftPlayer teleport method will fire the event unless the player is dead, is not connected fully, or is in a vehicle, https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java?at=refs%2Fheads%2Fversion%2F1.12.2#496   Either one of those conditions is being hit or you're potentially not actually teleporting a player

**Comment by andrew121410** [comment]
interesting

**Comment by andrew121410** [comment]
Soo is their a event that fires when player.teleport() is run?

**Comment by andrew121410** [comment]
I mean all I want is too make a /back command

**Comment by electronicboy** [comment]
I'd suggest asking for support in the [IRC](http://irc.spi.gt/iris/?channels=paper) or [Discord](https://discord.gg/jETyjUw), I believe this is more likely to be a code issue than an issue with the event not being fired
