### ISSUE TITLE
Recipe order not being preserved

### ISSUE THREAD

**Issue by Frogperson** [PaperMC/Paper#1821]
### What behaviour is expected:
When adding multiple recipes to the server, they should show up in the recipe book in the same order they were added.

### What behaviour is observed:
The recipes were all jumbled up with only small groups of 2-4 in the correct order.

### Steps/models to reproduce:
Add a bunch of recipies via `Bukkit.addRecipe()` , give yourself all the recipes with `/recipe give <username> *`, then check your recipe book.

### Plugin list:
None

### Paper build number:
504

### Anything else:
If the order added is unable to be preserved, then at least having them in alphabetical order would be nice

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
