### ISSUE TITLE
Reconnect while riding a horse glitch players

### ISSUE THREAD

**Issue by PWWP** [PaperMC/Paper#1823]
### What behaviour is expected:
When players return they should be able to normally interact world.

### What behaviour is observed:
Recently I have been having an issue with paper. The issue is when a user leaves the server whilst riding on a horse and they rejoin they are not able to build, break blocks or move on the server until they get back on a horse.

### Plugin list:
AuthMe, NoCheatPlus, PermissionsEx, PlugMan, ProtocolLib, ProtocolSupport, ProtocolSupportStuff, SkinsRestorer, Vault, WorldBorder, WorldEdit, WorldGuard

### Paper build number:
git-Paper-500 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Can you replicate this without plugins?

**Comment by PWWP** [comment]
> 
> 
> Can you replicate this without plugins?

Yes, I will try today.

**Comment by PWWP** [comment]
However, the problem doesn't occur without plugins. I will check which one create bug and thanks for help.
