### ISSUE TITLE
Add a LivingEntity#playPickupItemAnimation method

### ISSUE THREAD

**Issue by Parozzz** [PaperMC/Paper#1824]
Inside the nms class EntityLiving there is a method, EntityLiving#receive that accepts an entity and an integer. This method plays the pickup animation for that specific LivingEntity to any nearby player if the entity is a dropped item, an arrow or an experience orb. The integer is the amount of a dropped item(For the itemstack) or 1 in case of others. I am not sure what it does, maybe just have the animation show different model based on the quantity.

Would be cool if this method can be somehow exposed to allow that specific animation to be played.

**Comment by Chew** [comment]
Added in https://github.com/PaperMC/Paper/commit/4cc7de6c51ea8dede78ce1d16a4ef583b0a5a01a. Thanks for the request!
