### ISSUE TITLE
Async chunk provider makes server thread wait too long

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#1825]
Paper 509
No plugins

https://pastebin.com/VL7k6m0W

Notable paper config changes:
`prevent-moving-into-unloaded-chunks: true`
`delay-chunk-unloads-by: -1s`

Rest of the paper/spigot config is pretty much default.

**Comment by aikar** [comment]
not a 'bug' or problem. you have a piston pushing into an unloaded chunk and that causes a sync chunk load. 
if its causing constant spikes, youll need to find the redstone contraption causing it.

**Comment by hurrgurl** [comment]
Thanks!
