### ISSUE TITLE
PersistentVillage.getClosestVillage() takes too long

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#1826]
Paper 511
No plugins
Default config except for:
`      villages-load-chunks: false`
`      tick-inactive-villagers: false`
`      zombie-aggressive-towards-villager: false` (true made no difference)

Powerful hardware
Not a lot of zombies

https://i.imgur.com/pllJ6Qh.png 

https://sparkprofiler.github.io/?Ih3zgDiSOL

What's happening there? Can it be made faster?

**Comment by hurrgurl** [comment]
The cause seemed to be villages.dat

It was about 16 mb, deleting it solved this issue.

**Comment by 0-x-2-2** [comment]
not really a fix because you just deleted all of the villages lol
