### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#1827]
https://hastebin.com/mamogaqaza.md

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___http://prntscr.com/menqgd_

### Actions to reproduce (if known):
___https://hastebin.com/mamogaqaza.md___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we http://prntscr.com/menqu4

**Comment by electronicboy** [comment]
Please do not create issues for outdated versions of the server software, we no longer support them. Your watchdog report also points to a plugin making network requests on the main thread.

**Comment by successed** [comment]
> Please do not create issues for outdated versions of the server software, we no longer support them. Your watchdog report also points to a plugin making network requests on the main thread.

which one do you think?
