### ISSUE TITLE
BlockPistonRetractEvent not firing for sticky pistons with no block attached

### ISSUE THREAD

**Issue by stefvanschie** [PaperMC/Paper#1829]
### What behaviour is expected:
When having a plugin listening for a BlockPistonRetractEvent, I'd expect this event to fire for sticky pistons which are retracted without a block.

### What behaviour is observed:
I'm uncertain if the behaviour specified above is actually correct or not, however I thought I'd make an issue just in case.

When having a plugin listen for a BlockPistonRetractEvent, this event will not be fired when a sticky piston retracts with no block attached. As specified above, I'm uncertain if this is intended, however seeing how this event has methods for getting any possible blocks that moved during the retraction of the piston, I'd assume that this event should fire even if the sticky piston does not retract blocks. This would also streamline the event mechanism for all types of pistons; currently non-sticky pistons also trigger the BlockPistonRetractEvent when they retract, even though they also do not move blocks when retracting.

Currently the BlockPistonReatractEvent is fired three times for the retraction of a normal piston, fired once for a sticky piston which is retracting one or more blocks and zero times for a sticky piston that isn't retracting blocks.

### Steps/models to reproduce:
I've written the following plugin to test the behaviour described above:
```java
public class Main extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onBlockPistonRetract(BlockPistonRetractEvent event) {
        getLogger().info("BlockPistonRetractEvent fired.");
    }
}
```

### Plugin list:
The only plugin installed on the server is the plugin used for testing the behaviour specified.

### Paper build number:
This server is running Paper version git-Paper-512 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Anything else:
If the behaviour specified in the "Observed behaviour" section is as intended, feel free to ignore this issue.

**Comment by zachbr** [comment]
```java
// CraftBukkit start
if (!this.sticky) {
    org.bukkit.block.Block block = world.getWorld().getBlockAt(blockposition.getX(), blockposition.getY(), blockposition.getZ());
    BlockPistonRetractEvent event = new BlockPistonRetractEvent(block, ImmutableList.<org.bukkit.block.Block>of(), CraftBlock.notchToBlockFace(enumdirection));
    world.getServer().getPluginManager().callEvent(event);

    if (event.isCancelled()) {
        return;
    }
}
```

Although it is not documented within [BlockPistonRetractEvent](https://papermc.io/javadocs/org/bukkit/event/block/BlockPistonRetractEvent.html), this is clearly intended in the implementation.

For that reason, I would suggest you take this question up to Spigot and ask why this is the case.
Sorry for the bad news.

**Comment by zachbr** [comment]
~~That change dates back to a bugfix for normal pistons, and there are other callers, this may be less "intentional" and more "this used to work from another caller and the code changed in an update and broke it".~~

The history behind this change is just weird. See commit message.

Moving to bug.

**Comment by MiniDigger** [comment]
Maybe this should be noted in the javadocs a bit more clearly.
