### ISSUE TITLE
Placing chest with NBT data drops its contents on an WorldGuard region

### ISSUE THREAD

**Issue by joestr** [PaperMC/Paper#1831]
### What behaviour is expected:
The chest should not be placed and its contents should not be dropped.

### What behaviour is observed:
The chest indeed was not placed, but its contents were dropped.

### Steps/models to reproduce:
1.) Create an WorldGuard region.
2.) Place a chest, fill items in it.
3.) Grab the chest with NBT data (Ctrl-Key)
4.) Give the NBT-Chest a player who does not have any rights on this region from 1.).
5.) The player from 4.) places the chest.
6.) The chest was not placed, but its contents were dropped.
7.) The player can repeat step 5.) and 6.) as long as they want.

### Plugin list:
ArmorStandToold (3.2.0)
BannerBoard (1.9.10.4)
BKCommonLib (1.13.2-v2)
BungeeTabListPlus (2.8.9)
CommandWatcher (1.1)
CoreProtect (2.15.2)
DatabaseHandler (0.2.0)
dynmap (3.0-beta-3-160)
Dynmap-WorldGuard (1.1-alpha-2)
HolographicDisplays (2.3.2)
LuckPerms (4.3.6)
NametagEdit (4.4.0)
PlaceholderAPI (2.9.2)
Plan (4.6.1)
ProtocolLib (4.4.0)
QuickAndDirty (0.1.5)
React (6.581)
ReWorld (1.1.5)
Trade (0.1.1)
Train_Carts (1.13.2-v1)
WorldBorder (1.9.0)
WorldEdit (7.0.0-beta-04;17f52cb)
WorldGuard (7.0.0-beta01;01dfebe)
ZoneMenu (0.1.0-SNAPSHOT)

### Paper build number:
21ba01aa

### Anything else:
Relates to https://dev.enginehub.org/youtrack/issue/WORLDGUARD-3420

Steps to create:
![2019-02-02_23 58 30](https://user-images.githubusercontent.com/20691668/52170419-2c8cd100-274a-11e9-8637-1923232d292f.png)

![2019-02-03_00 01 02](https://user-images.githubusercontent.com/20691668/52170420-2d256780-274a-11e9-9bad-0c4036d16a6b.png)

A user uses this bug
https://www.youtube.com/watch?v=FXu4Br0HllI

**Comment by zachbr** [comment]
Still occurring with latest Paper and updated plugins?

**Comment by joestr** [comment]
Still occours on Paper 5c01331 with WorldEdit 4123-4de5487 and WorldGuard 1835-44c4e58

**Comment by joestr** [comment]
clicked the wrong button ...

**Comment by zachbr** [comment]
Thanks, I’ll  try and take a look at this.

**Comment by zachbr** [comment]
This is fixed in builds 608+
Thanks for the report.

**Comment by Kapitowa** [comment]
This bug occur on 1.17.1 build of paper.
