### ISSUE TITLE
tab-complete: -1 is not work.

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#1832]
server version : http://prntscr.com/mfwq9w
spigot.yml : http://prntscr.com/mfwqdn
tab complete is not a closed.
how to fix this problem ?

my plugin list : http://prntscr.com/mfwqk8

i use the bungeecord proxy.

tab-complete is work : http://prntscr.com/mfwrlr

how to close

**Comment by ShaneBeee** [comment]
I just tested this, and it seems to work fine. 
I changed it, reloaded my server (its a test server so I dont really worry about /reload)
Didn't change anything
Restarted my server, and now it works fine, blocks the tab complete


Try restarting your server.

**Comment by successed** [comment]
> I just tested this, and it seems to work fine.
> I changed it, reloaded my server (its a test server so I dont really worry about /reload)
> Didn't change anything
> Restarted my server, and now it works fine, blocks the tab complete
> 
> Try restarting your server.

come to server play.izmirmc.com 1.13.2

**Comment by electronicboy** [comment]
When the tab complete value is 0 or less, the server doesn't send any command definition packets; Given how this system works, I would hazard a guess that one of your servers in the setup doesn't have that disabled, and so the client is being sent them from there

**Comment by successed** [comment]
> When the tab complete value is 0 or less, the server doesn't send any command definition packets; Given how this system works, I would hazard a guess that one of your servers in the setup doesn't have that disabled, and so the client is being sent them from there

i have 3 server and all of spigot.yml in tab-complete: -1, do you want to see ?

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/52249572-be800f80-28eb-11e9-9ca0-880b442ca019.png)
Cannot reproduce

**Comment by successed** [comment]
> ![image](https://user-images.githubusercontent.com/1228900/52249572-be800f80-28eb-11e9-9ca0-880b442ca019.png)
> Cannot reproduce

Check my server : http://prntscr.com/mgq396  and plugin list : http://prntscr.com/mgq3nf and stop close the issue.. @electronicboy

**Comment by zachbr** [comment]
If we can't reproduce it, we can't reproduce it. We aren't going to come join your server, that doesn't help us.

In your case, it looks like all those commands are related to a world generator plugin, so it seems likely that there's a single plugin or two doing their own special snowflake thing that we can't control.

**Comment by successed** [comment]
> If we can't reproduce it, we can't reproduce it. We aren't going to come join your server, that doesn't help us.
> 
> In your case, it looks like all those commands are related to a world generator plugin, so it seems likely that there's a single plugin or two doing their own special snowflake thing that we can't control.

thank you, fixed.
