### ISSUE TITLE
Sort of crash on latest build of 1.12.2 -b 1596

### ISSUE THREAD

**Issue by dino147** [PaperMC/Paper#1840]
Server version: PaperSpigot 1.12.2 build 1596
Server type: creative server with plotsquared, essentials, worldedit, worldguard, AAC, etc...
All my servers are kicked/timed out. Error: https://pastebin.com/PRfW5366

I don't know what to do, sometimes server runs normaly but in other days I get a few crashes (as today...).
This doesn't seems to be a plugin issue as there are no specific errors about plugins (only one with [LiteBans] Unhandled exception occured in onPacketReceiving(PacketEvent) for LiteBans but it doesn't seem to be the cause of the server crash...)

Please help me, this is quite important... I've also checked the worlds for corupted chunks with minecraft region fixer but I didn't find any (there is also a chunk-related issue..)

**Comment by electronicboy** [comment]
Your server is having issues keeping up, I'd suggest joining IRC/Discord for support, the litebans error is also likely what actually caused the players to be kicked (outside of your other issues)
