### ISSUE TITLE
Moving Holograms Shaking

### ISSUE THREAD

**Issue by Segysmundo** [PaperMC/Paper#1841]
I have been using a plugin that adds holograms over player's heads to display achievement titles, on spigot there was no real problem but when i swapped to paper I started noticing these weird delays in movement causing the hologram to shake around.

 **Paper build number:** 1596 _(latest)_

For testing purposes, my server only has these plugins:
- [PvpTitles](https://www.spigotmc.org/resources/pvptitles.20927/) _(The title's over the heads)_
- [HolographicDisplays](https://dev.bukkit.org/projects/holographic-displays)
- [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/)

In the following gifs you can see on Spigot it's way smoother and I can't figure out why.

On Paper for 1.12.2
![ezgif com-crop](https://user-images.githubusercontent.com/19178945/52378804-f6f92800-2a68-11e9-8827-439463a8254f.gif)

On Spigot for 1.12.2
![ezgif com-crop 1](https://user-images.githubusercontent.com/19178945/52378846-155f2380-2a69-11e9-9d24-1396c168a122.gif)

### Edit: Just tested it out with [another similar plugin](https://www.spigotmc.org/resources/holomedals-donater-perk-reward-for-events-achievements-1-8-1-13-2.31223/) to check if it was PvpTitles causing it, but the problem is the same.

**Comment by aikar** [comment]
potentially related: https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0037-Send-absolute-position-the-first-time-an-entity-is-s.patch
