### ISSUE TITLE
Allow Block#setBlockData / Block#SetType to use World#n instead of setting to air when a tile entity is present. (Also add obf helper.)

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1842]
**Is your feature request related to a problem? Please describe.**
Hi, Paper boys! When I'm replacing a block that contains a tile entity, the previous tile entity is not properly getting discarded before the new one is placed and it causes:

`[01:27:23 ERROR]: Block at 2,560,110,1,536 is Block{minecraft:sign} but has net.minecraft.server.v1_13_R2.TileEntityFurnace@6a82f4ba. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.`

PLEASE DO NOT FEAR: I AM NOT USING THE BUKKIT API.

This feature request addresses this problem.

**Describe the solution you'd like**
I think changing the Block methods to use World#n would be better than setting the block to air first, but I need to be honest with you--I really just want an obfuscation helper for World#n. Like I really, really want World#n to not be called "n." Desperately. 

**Describe alternatives you've considered**
I've considered eating a raw red onion and screaming in agony while the onion juices burn my tongue and nasal passages.

**Additional context**
I love you guys (especially you, Shane!) and I can't wait to ask you a new set of 50 questions tomorrow. Thank you and I love you so, so much. Talk to you later, Shane.

**Comment by aikar** [comment]
What? "PLEASE DO NOT FEAR: I AM NOT USING THE BUKKIT API."
Use the Bukkit API.

Anything broken when using NMS is up to you to figure out.

Please provide reproduce code using Bukkit API

**Comment by Snow-Pyon** [comment]
> What? "PLEASE DO NOT FEAR: I AM NOT USING THE BUKKIT API."
Use the Bukkit API.
Anything broken when using NMS is up to you to figure out.
Please provide reproduce code using Bukkit API 

This is actually a suggestion to the API, setTypeAndData sets the block to air then to the actual block when it comes to tile entities, instead of calling World#n on the entity as you're *probably* supposed to.

**Comment by zachbr** [comment]
This change will affect a very core API method. Needs testing and verification. We may consider slipping in a runtime flag to allow for more testing before making this change, pending additional investigation.

**Comment by BillyGalbreath** [comment]
Doing this will break some vanilla logic. Example being setting a filled chest block to something else causes the chest to drop its contents. This change will prevent that from happening.

**Comment by aikar** [comment]
I dont think this should touch any existing api, and should be added as an optional new api.

But I question if this is even valid? I've never heard of the api causing that error. You said you were using nms, so it doesn't seem like we have anything to do anyways?

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
