### ISSUE TITLE
Weird error since todays update

### ISSUE THREAD

**Issue by KimoriWasTaken** [PaperMC/Paper#1843]
When starting the server on my raspberry through ./start.sh and opening up the screen -r minecraft it shows upt a bunch of spam error messages and those two:

2019-02-08 01:57:21,813 main ERROR Null object returned for RollingRandomAccessFile in Appenders.
2019-02-08 01:57:21,849 main ERROR Unable to locate appender "File" for logger config "root"

After that it launches and works but I'm worried about those messages and what effect they have on the server performance that is really low anyways.

It first happened today after it updated, so there should have been a recent commit or it was caused by installing postfix, which I don't think.

If nothing can be done I'll backup my world and whipe and clean reinstall everything on my sd card.

**Comment by electronicboy** [comment]
Do you by any chance have a log4j.xml file in your servers folder root? (or have some java flag specifying a custom log4j config?) looks like an invalid logger config

**Comment by KimoriWasTaken** [comment]
`find: ‘log4j.xml’: No such file or directory`

For some reason crontab can't start th server aswell with a command like

`0 6 * * * /home/pi/minecraft/restart.sh`

Even though the postfix mail shows it executed it

Subject: Cron <pi@raspberrypi> sleep 10;/home/pi/minecraft/start.sh
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/pi>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=pi>
Message-Id: <(removed cause idk if this should be shown)>
Date: Fri,  8 Feb 2019 03:10:31 +0100 (CET)

Updating to most recent paperclip version.
Starting Minecraft server.  To view window type screen -r minecraft.
To minimize the window and let the server run in the background, press Ctrl+A then Ctrl+D`

I might just clean reinstall everything, I really don't know what happened

**Comment by KimoriWasTaken** [comment]
Even after reinstalling everything and choosing the new options of "Do you want the server to automatically start on startup" it doesn't start the server by the way.

The only line that was added to crontab was the one where it schedules at restart at 4 am.

Is the reboot job supposed to be stored elsewhere?

Edit.: I can ONLY start it if I manually `cd minecraft` and then `./start.sh`
If I just type `home/pi/minecraft/start.sh` it give me the usual echo message and terminates the application short afterwards.

Edit 2: `home/pi/minecraft/start.sh` works on the 3rd try every reboot. I'll give up at this point and will try again tomorrow or so

**Comment by KimoriWasTaken** [comment]
auto start on reboot solved by removing the update and flush lines in start.sh
They are in reboot anyways, so why are they also there?

I'd really like to know where that auto reboot code is written though, the one I enabled when it asked me if I wanted that or not. It's not is user/crontab.
Is it in sudo crontab or etc/crontab? 

Thank you in advance!

**Comment by zachbr** [comment]
>I'd really like to know where that auto reboot code is written though, the one I enabled when it asked me if I wanted that or not. It's not is user/crontab.
Is it in sudo crontab or etc/crontab?

Paper does _not_ make system-level changes like this. This is out of scope for this tracker. If you're still seeing this you may be able to get someone to help in our discord https://discord.gg/papermc
