### ISSUE TITLE
Sheep causing lag

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1844]
###  Timings or Profile link:
https://timings.aikar.co/?id=3d9cae3018364f949a0f3d78b90ff290_

### Description of issue:
After a day, in the evening, only a few players are still online. Most of them afk or relaxing a bit. The TPS was fairly low for only 5 players. Around 19,6. Run the timings. Sheep seem to be the problem. Checked every player and the area around them. No sheep around or just a few. Obviously no high numbers of sheep within the activation range of 8 blocks.
```
    entity-activation-range:
      animals: 8
```
So that makes me wonder why sheep are such a problem. Do they remain active on the whole map or something?

### Plugin list:
BestViewDistance is causing some lag too, will try a day or so without. For furthe plugins: timing says it all I think.

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
Paper 1.13.2 build 519

**Comment by x1p** [comment]
I've checked more than once. There are not that many sheep in comparison to other animals. It seems to me that sheep make more lag than other animals.

**Comment by hurrgurl** [comment]
Can you make the video showcasing the issue with your sheep?

**Comment by x1p** [comment]
It looks like sheep are not deactivated over time. As if they remain active.
In the morning the same players are active on their land as in the evening. Yet, in the evening, the TPS is worse than during the day.
How do you suppose to make a video of sheep? They look normal, act normal.

**Comment by multicody10** [comment]
Yeah, same problem.
Short: https://timings.aikar.co/?id=aeeb0000cacf4eccbd2b7c8b2b54c72b
Long: https://timings.aikar.co/?id=ddbed0f7cad349e780bd11a95b9162b0

Going to every single player, none of them have any amount of mobs that should be causing THIS much degradation.

Seems like someone else noticed as well: https://github.com/PaperMC/Paper/issues/1791

**Comment by Brokkonaut** [comment]
580 sheep in your world... what do you expect?

**Comment by x1p** [comment]
It's a reasonable large world so they can't all be activated. Replace "sheep" with "cow", and this would not be a problem, at least not as big as sheep.
I can't expect players to limit their sheeps to only 1 per color per player.

**Comment by x1p** [comment]
I've killed large numbers of wild sheep. This improves the situation.

Ideally it would be very nice if the numbers of animal spawning can be adjusted per kind of animal. This would give server owners the ability to influence the game and would have multiple advantages.

**Comment by zachbr** [comment]
Spawn changes have gone in that may make this problem worse (or better). Please let us know if you're still seeing this and let us know what version you're on. Thanks.

**Comment by x1p** [comment]
Sheep lag has been reduced dramatically after butchering large uninhabited areas.

Still experiencing lag from time to time. Each time it's a different entity. Can't wait for 1.14 to hopefully solve this.
I think it can be closed for now.
