### ISSUE TITLE
Crash in the end

### ISSUE THREAD

**Issue by jpeaceau** [PaperMC/Paper#1850]
https://pastebin.com/8bbJAXsJ I was getting spammed with this when a player was building in the end. WorldEdit was also giving errors but not as much as PaperSpigot and it was only giving errors in the end. I'm using ProtocolSupport, the player was in 1.8.9. Also, we would get kicked whenever the enderdragon would respawn nearby. Using paper-521.

**Comment by electronicboy** [comment]
That just looks like somebody was running an excessive worldedit operation which took too long for the server to tick, unless there was some error from chunk loading previously to that
