### ISSUE TITLE
[Feature Request] Config setting for option to revert IronGolem spawning mechanics to pre-1.13

### ISSUE THREAD

**Issue by CherubHeart** [PaperMC/Paper#1851]
IronGolem farms made with spawner cages are no longer able to work because they relied on the IronGolems to spawn in the air. Now, with 1.13, IronGolems must spawn on a solid block. Once on the block, they do not drop and therefore the farms can not function. 

 I would love to see a configuration option to allow IronGolems to spawn mid-air again, as they did prior to 1.13.

 Thank you for considering my request. It would be especially helpful for younger players on public servers like we run who will struggle with finding a functioning work-around for this issue.

**Comment by bermudalocket** [comment]
@CherubHeart In the meantime, here's a design workaround: https://imgur.com/a/J0id0xJ

**Comment by kickash32** [comment]
Is this still relevant to the changes in 1.14.3?

**Comment by LogGits** [comment]
@kickash32 Yes
