### ISSUE TITLE
Patch

### ISSUE THREAD

**Issue by bilemedimkq** [PaperMC/Paper#1855]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/51c118b1d7f6ed9847fa853081e1eed67ddeb293

Can you add this in 1.13.2?

(https://github.com/ProtocolSupport/ProtocolSupport/issues/1022)

**Comment by BillyGalbreath** [comment]
Slow your roll. Paper pulls from upstream regularly. Give it some time.
