### ISSUE TITLE
Integration of skipping the night by sleeping like the plugin 'Better Beds'

### ISSUE THREAD

**Issue by WELTEINZ** [PaperMC/Paper#1857]
Hello,

currently i use the plugin '**Better Beds**' ([https://www.spigotmc.org/resources/better-beds.1824/](url))
to skip the night with a preconfigured number of players.
However, for my server this means an additional plugin for a simple feature.
Therefore I think it would be useful to integrate it into Paper.
According to the download rating and comments on Spigotmc.org,
I'm not the only one who wants an integration.
Also, the plugin is very minecraft-update proof since it last received an update in april 2015
and it works very well.

Cheers!

WELTEINZ

**Comment by BillyGalbreath** [comment]
`an additional plugin for a simple feature`

That's the entire point of the Bukkit project. Features should be provided by plugins. Bukkit simply gives the means to do so via an API.

**Comment by mikroskeem** [comment]
>Also, the plugin is very minecraft-update proof since it last received an update in april 2015
and it works very well.

So, what's the point of integrating it into server then? :p

**Comment by zachbr** [comment]
Our feelings mirror those of the comments here

**Comment by WELTEINZ** [comment]
Hi,

since the automatic execution of autosave (there are many plugins for this) is also part of papermc and I saved EssentialsX by PaperMC (automatic autosave is part of this plugin), I thought it would be nice to implement a better beds adaption since skipping the night on survival servers is a common problem when there are a lot of players on the server.
