### ISSUE TITLE
Cactus piston bugs.

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#1858]
version : http://prntscr.com/ml2lcu

Problem : https://youtu.be/UIAvdNfrMNg
Fps problem: http://prntscr.com/ml2o3z

**Comment by aikar** [comment]
can you please state what the problem is?

**Comment by successed** [comment]
> can you please state what the problem is?

Thanks to 1 cactus and the redstone circuit in the video, unlimited cactus can be obtained.

**Comment by BillyGalbreath** [comment]
This is actually a vanilla feature, and can be replicated without an over engineered piles of redstone.

[![Cactus Popping, Oh My!](https://img.youtube.com/vi/Op7iJXA0rv8/0.jpg)](https://www.youtube.com/watch?v=Op7iJXA0rv8)

**Comment by NachtRaben** [comment]
Blasphemy! Cactus isn't a renewable resource!

**Comment by successed** [comment]
The cactus in the video is being refreshed in 3 seconds, please watch the video before making these kind of silly comments and i have server growth rate settings in standard condition.

**Comment by aikar** [comment]
It is a bug, not a feature. I thought we had this patched.... But I think something with physics changed in 1.13 maybe source of the issue.

**Comment by successed** [comment]
Is this an uncorrectable problem?

**Comment by BillyGalbreath** [comment]
> The cactus in the video is being refreshed in 3 seconds ... i have server growth rate settings in standard condition.

This is why you should specify as much information as possible in your reports. You show a video and expect us to guess at whats going on.

**Comment by successed** [comment]
> > The cactus in the video is being refreshed in 3 seconds ... i have server growth rate settings in standard condition.
> 
> This is why you should specify as much information as possible in your reports. You show a video and expect us to guess at whats going on.

Did you read this? ? http://prntscr.com/ml7kqz

**Comment by BillyGalbreath** [comment]
> > > The cactus in the video is being refreshed in 3 seconds ... i have server growth rate settings in standard condition.
> > 
> > 
> > This is why you should specify as much information as possible in your reports. You show a video and expect us to guess at whats going on.
> 
> Did you read this? ? http://prntscr.com/ml7kqz

Yes. Yes, I did. And I was able to recreate that vague response in my video using vanilla features.

**Comment by aeonlamb** [comment]
This is vanilla behavior. When a cactus receives an update from a piston or other block being pushed by a piston's "0-tick" pulse, it will advance a growth stage automatically, regardless of the random tickspeed. In my opinion this should not be patched unless mojang has shown some indication that they consider it to be a bug and intend to patch it themselves.

**Comment by aikar** [comment]
While it does kind of seem undesirable to be done at the rapid pace pistons provide, the code clearly states this is desired behavior, so going to close.

please report to mojang if you want, but while i agree its not ideal, fixing it isnt possible without breaking other updates from triggering growth too.

**Comment by aikar** [comment]
note that this isnt the same thing I commented on above thinking we fixed it.

**Comment by successed** [comment]
> note that this isnt the same thing I commented on above thinking we fixed it.

I reported this to mojang. report link : https://bugs.mojang.com/browse/MC-144210

**Comment by successed** [comment]
well yeah,mojang says you should take care of this situation.
check this aut https://mail.google.com/mail/u/0/#inbox/FMfcgxwBVgqHjrDbbQdHLGWjBHzMZf

**Comment by BillyGalbreath** [comment]
> well yeah,mojang says you should take care of this situation.

You misread what they said. They simply want you to recreate the bug using vanilla software, not Paper.

**Comment by successed** [comment]
> > well yeah,mojang says you should take care of this situation.
> 
> You misread what they said. They simply want you to recreate the bug using vanilla software, not Paper.

I did not do it, my players have done, I don't know how to do ..
Can you help with this?

**Comment by NachtRaben** [comment]
You have a video, reverse engineer it.

**Comment by successed** [comment]
https://www.youtube.com/watch?v=NkV9iXii9_4

Can this video help me?

**Comment by aikar** [comment]
Please discuss how to recreate it on Vanilla on Discord or IRC.
