### ISSUE TITLE
Finding a location to place nether portal takes too long

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#1861]
Paper 524
No plugins
All configs are default

- - -

https://pastebin.com/k5ujKEDM

I think it mostly happens when the other side is full of water and the final portal destination becomes the least likely kind - hovering above water.

**Comment by zachbr** [comment]
Please confirm you're still seeing this issue for us, thanks.

**Comment by hurrgurl** [comment]
Haven't seen it in a while.

Also halved portal search radius. I'll bring it back up to paper default & see if any issues arise.

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
