### ISSUE TITLE
Crops retain the will to go on without water

### ISSUE THREAD

**Issue by Dalethium** [PaperMC/Paper#1869]
### What behaviour is expected:
Crops dying if there is no water near by

### What behaviour is observed:
Crops staying alive with no water near by under specific circumstances
### Steps/models to reproduce:
1. place a piece of dirt anywhere not near water
2. till the dirt
3. quickly place a crop and bonemeal it to full growth
4. watch as the crop remains alive.

### Plugin list:
``AutoAnnouncer*, Autorank, BetterBanner, CoreProtect, DiscordSRV, dynmap*, EnderSurfer*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FirstJoinPlus*, LuckPerms*, mcMMO, Minecart_speedplus*, Multiverse-Core, PerWorldInventory, PluginLibrary*, ProtocolLib*, spark*, Vault*, Votifier, VotingPlugin, Whitelist*, WorldEdit``

### Paper build number:
git-paper-525

**Comment by sotr2333** [comment]
I can reproduce this in Spigot, as long as there is a crop in the soil (no need to full growth), neither the crop and the soil will dying. Set `randomTickSpeed` to 200 or higher, and u will find that they are still growing.

**Comment by electronicboy** [comment]
https://minecraft.gamepedia.com/Tutorials/Crop_farming#Sowing  Sounds like vanilla behavior? The wiki might be wrong, but I don't recall there being any behavioral difference between vanilla and CB and co?

**Comment by Dalethium** [comment]
Oh, you're right! I'm sorry to have wasted your time!
