### ISSUE TITLE
Chest recipe creates button

### ISSUE THREAD

**Issue by Xenthyk** [PaperMC/Paper#1872]
### What behaviour is expected:
Just updated to version 542 and the recipe for a chest creates a button. 8 wood planks around the workbench creates a button instead of a chest

### What behaviour is observed:
explained above

### Steps/models to reproduce:
Explained in first step

### Plugin list:
Long list but reverting back to version 511 fixed the issue.

### Paper build number:
542

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by aikar** [comment]
can you try 543, I just reverted the patch that would of caused this, ill have to look more into it I guess.

**Comment by Xenthyk** [comment]
Chest recipe works in 543
