### ISSUE TITLE
[Suggestion] Tell block breaks after process event

### ISSUE THREAD

**Issue by sotr2333** [PaperMC/Paper#1873]
**Is your feature request related to a problem? Please describe.**
Spigot sends a break block packet before the BlockBreakEvent process, and if the event is cancelled, send a packet again to restore the block change: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/PlayerInteractManager.patch#141

Thus when cancelling the event, the block will be appearing as AIR for a moment /even in local server

**Describe the solution you'd like**
Move down the AIR packet send to after the event processing.

**Comment by BillyGalbreath** [comment]
This is a very old topic, and I remember seeing conversations about it before Spigot even existed. I don't remember specifics but the old Bukkit team pretty much was saying something to the effect of it is needed to prevent server->client desync issues.

**Comment by sotr2333** [comment]
I've applied this to my paper [fork](https://github.com/Akarin-project/Akarin/blob/6f25bb7ea4cc7b786a4348d2516de2a20a110e60/src/main/java/net/minecraft/server/PlayerInteractManager.java), no issue found so far
