### ISSUE TITLE
[Feature request] Makes get world more easier for Block/Entity events

### ISSUE THREAD

**Issue by sotr2333** [PaperMC/Paper#1874]
**Is your feature request related to a problem? Please describe.**
We have to do as `evt.getEntity().getWorld()` or `evt.getBlock().getWorld()` to get a world instance from Block, Entity, etc. events and it is inconvenitent.

**Describe the solution you'd like**
Add a helper method to the event, so we can directly get the world from the event.

**Comment by zachbr** [comment]
This sounds like a large diff for a relatively minor quality of life improvement.

**Comment by sotr2333** [comment]
@zachbr Why it's a large diff? This could be done in the father class simply: https://gist.github.com/cakoyo/6934779ac91ba960b9d3304ae1ab1963

**Comment by zachbr** [comment]
It's a large diff to do it properly in all events that could possibly expose it. It also then should be maintained as new events add and remove objects that include it.

That's ignoring the fact that this is all seems a bit silly anyway given how accessible they already are. We could just flatten down all available objects into each and every event, but that sort of defeats the entire purpose those objects exist.

**Comment by liach** [comment]
can we just get a target world event interface?
