### ISSUE TITLE
massive amount of signs with random data crash client

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1876]
### What behavior is expected:
client connects to server and starts rendering signsban¹ chunks without problems or disconnects

### What behavior is observed:
client after entering signsban¹ chunk gets disconnected and any attempts to reconnect immediately fail

### Steps/models to reproduce:
1. Build massive amount of signs
2. Fill them with random data *at this point chunk turns into signsban¹*
3. Try entering signsban¹ chunk and you will be disconnected
4. Any attempt to reconnect while being in signsban¹ chunk would fail

___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Anything else:
I expect this behavior was allowed by chunks size being not capped at 1MB and reverted after saving [ref commit 8448011](https://github.com/PaperMC/Paper/commit/84480114eb940560073d9bcfcbe8bd917705cb3b)

singsban¹ - chunk full of signs filled with random ASCII/Unicode data which can make client disconnect

*EDIT: cleanup and fix some sentences*

**Comment by aikar** [comment]
been on my to do list, i'll knock it out tonight.

**Comment by 0-x-2-2** [comment]
:^)

**Comment by aikar** [comment]
547 and 1601 has fixes now.

we trim any large payloads sent from the client, and for any existing sign in the world, large payloads are trimmed before sending to the client, so it covers existing ban chunks too.
