### ISSUE TITLE
Recent change breaks command signs

### ISSUE THREAD

**Issue by Combustible** [PaperMC/Paper#1878]
### What behaviour is expected:
All my command signs have had their commands removed from them. Still testing to figure out which specific change did this. 

Tested with F3+i and `/data get block` - command signs no longer have the onClick NBT JSON data. 

Broken in 40f5a94b, these signs were previously working in ddab622b

**Comment by zachbr** [comment]
There were several commits trying to limit the amount of content on signs between those two commits. That functionality is probably going to need additional tweaking or options in order to support signs with lots of command information on them.

**Comment by Combustible** [comment]
Most of these signs had relatively short commands - less than 30 characters. For example `/leaderboard @s race`. I suspect if it's length based it's so short as to be effectively useless.

**Comment by aikar** [comment]
im going to drop the patch and fix it a different way.
