### ISSUE TITLE
Carrot Farm does not work anymore since i updated

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1879]
### What behaviour is expected:
When the villager places a crop on the farmland on lightlevel 7, it SHOULD break automatically because of the observer clock against it.
### What behaviour is observed:
When the villager places a crop on the farmland on lightlevel 7, it does not break but will grow.
### Steps/models to reproduce:
https://www.youtube.com/watch?v=nKmQ93W8FN8&t=27s
### Plugin list:
BlockLocker, Bondage, DropSpawnerBR, Hydra, IPWhitelist, Lands, LuckPerms, Matrix, NotTooExpensive, PandaWire (Also tested without PandaWire), ProtocolLib, ServerRestart, Topographica (Private DynMap alternative), Vault

### Paper build number:
551

### Anything else:
When downgrading to papermc version 523 the farm just works fine. It also works fine on Vanilla 1.13.2

**Comment by richardthornton** [comment]
I can confirm this has happened for me too on an Ubuntu 18.04.2 LTS server. Downgrading to 523 restores the expected mechanic.

**Comment by electronicboy** [comment]
Are you able to tie it down to a more definitive breaking build? That's a fair amount of builds in the meantime...

**Comment by electronicboy** [comment]
Actually, looks like this was fixed in build 555?

**Comment by ghost** [comment]
Fixed in build 555. You can close this now @electronicboy
