### ISSUE TITLE
Display scoreboard team colours in chat messages, as per vanilla behaviour.

### ISSUE THREAD

**Issue by zedwick** [PaperMC/Paper#188]
I believe Paper should support as much of vanilla behaviour as possible, which should include chat behaviour. There are many vanilla adventure maps, minigames and other such command block creations which use scoreboard teams and would normally colour players chat messages to denote which team they are on in competitive play. The lack of team colours make navigating chat very difficult, and I know of no released plugin which can provide this vanilla functionality.

I think this should be a stock feature in Paper, though I would completely understand if it were a configurable option which is disabled by default to avoid conflict with plugins which expect and rely on completely unformatted chat. (This has been the default long before scoreboard teams were added to vanilla, after all)
# Incompatibility (Bug)
### What behaviour is expected:

Vanilla Minecraft behaviour is to show scoreboard team colours for player names in chat messages, join/leave messages and death messages.
### What behaviour is observed:

No colours are shown for player names in chat messages, but are shown for join/leave and death messages.
### Steps/models to reproduce:

/scoreboard teams add Team1
/scoreboard teams option Team1 colour green
/scoreboard teams join Team1
Type any message into chat
### Plugin list:

No plugins
### Paper build number:

This server is running Paper version git-Paper-640 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

**Comment by kashike** [comment]
This has been a bug with CraftBukkit for a **long** time.

https://bukkit.atlassian.net/browse/BUKKIT-4119
https://bukkit.atlassian.net/browse/BUKKIT-4973

**Comment by zachbr** [comment]
Never try and do labels from your phone. It doesn't work out so well

**Comment by zachbr** [comment]
This is disabled by default because although it is vanilla behavior, plugins _do not_ expect vanilla behavior in this case.

I have done preliminary testing to make sure it works as expected when disabled, and when enabled, but it is always possible I have missed a use case or overlooked something. Please test with build 647 or newer and let us know how it goes.
Thanks.

**Comment by zedwick** [comment]
This works perfectly for me with enabled, thank you for implementing it! I wasn't sure this would be taken up with how long plugins have relied on it as was, very happy ^_^

I made a mistake in saying the colour shows in Paper when the player logs in, as it does not. It does in vanilla, though. Could you add the colour to the player's name when they log in, too? It's not as big of a deal if it doesn't show there, but is vanilla behaviour.

**Comment by zachbr** [comment]
Bukkit's PlayerJoinEvent basically butchers any easy handling of it. I'm not sure we value the feature enough to go through and redo its handling.

**Comment by zedwick** [comment]
As I said, not a big deal; would have just been nice. Thanks for looking into it!

Could this be pushed into 1.8.8 also? I'd love to have the coloured chat available for some 1.8 maps

**Comment by zachbr** [comment]
Our final update for 1.8.8 was on Feb 28th. After that we dropped support for it. We did backport a security fix for it on March 29th but it only received that patch because of the severity of the issue.

We no longer provide formal support for 1.8.8. The code should be easy to backport for anyone else that is interested though.

**Comment by zedwick** [comment]
I understand. Thanks again.
