### ISSUE TITLE
[Bug] If enforce-whitelist is on the /deop command kicks everyone on the server when used.

### ISSUE THREAD

**Issue by KarlOfDuty** [PaperMC/Paper#1880]
I have tested this on two different systems with a completely fresh and plugin free server of version 551.

I created the server from scratch with the paper jar, changed the setting to true, joined the server with two accounts, opped them and then had one deop the other.  It also works by just deopping yourself I just realised as well.

**Comment by aikar** [comment]
This is working as intended, Vanilla behavior.

You must whitelist those players if enforce whitelist is on...
I assume op inherits a whitelist, so they rescan the online players to remove anyone not whitelisted who was getting it by deop previously.

you didn't mention also adding them to a whitelist?

**Comment by KarlOfDuty** [comment]
Wait it is intended behaviour that the entire server should get kicked whenever I /deop someone?

**Comment by KarlOfDuty** [comment]
To clarify, there is no whitelist active. And all 140 players got kicked by me deopping someone yesterday.

**Comment by aikar** [comment]
Are you saying that players explicitly on the whitelist are getting kicked? The code is checking if they are not whitelisted as reason for kicking.

the code also thats that enforce whitelist is on AND the server is whitelist enabled.

**Comment by aikar** [comment]
it sounds like something turned whitelist on then

**Comment by electronicboy** [comment]
Vanilla seemingly doesn't check if the whitelist is on when it checks from a quick test

**Comment by KarlOfDuty** [comment]
I can definitely confirm there is no whitelist on as no one would have been able to get on the server in that case.

**Comment by KarlOfDuty** [comment]
And on the test servers there was def no whitelist on as I joined the accounts and then opped them on a completely fresh server they had never joined before.

**Comment by aikar** [comment]
Ok confirming there is a bug, mojang has 2 booleans for if whitelist is enabled and is checking wrong one.

**Comment by KarlOfDuty** [comment]
What's the other one for? Well the one being used currently.
