### ISSUE TITLE
Catch Shift-clicking on CraftItemEvent

### ISSUE THREAD

**Issue by Thefirstalpha** [PaperMC/Paper#1883]
**Is your feature request related to a problem? Please describe.**
When you craft items by shift-clicking, it will only count the result of the recipe and not all items that you craft. Example, if you take a stack of coal, and a stack sticks to craft torches by shift-clicking, the amount return by the CraftItemEvent will be 4 torches, but you've craft 256 torches...

**Describe the solution you'd like**
Add a getCraftAmount() or getAmount() to the CraftItemEvent, that return the exact number of craft made by shift-clicking

**Describe alternatives you've considered**
The only alternative that I know is to make a schedule on every second that store the inventory of the player. Then when the player craft the items by Shift-clicking, make the difference between the 2 inventories to count the number of crafted items.

**Comment by Thefirstalpha** [comment]
Steel no update about that?
It's been a long time since this issue exist, I found it on some bukkit forums from 2012
https://bukkit.org/threads/cant-get-amount-of-shift-click-craft-item.79090/
https://www.spigotmc.org/threads/craftitemevent-shift-clicking.52463/

**Comment by electronicboy** [comment]
This is down to the implementation of the event, fixing that issue would involve moving a fair chunk of logic and potentially introduce many other complications around calculating the total amount
