### ISSUE TITLE
AFK thru-wall hack

### ISSUE THREAD

**Issue by Trip1234** [PaperMC/Paper#1886]
### What behaviour is expected:
bug testing

### What behaviour is observed:
when my player went afk while underwater I was pushing against him and he moved through walls

### Steps/models to reproduce:
1. set two walls with one block open between them, flill with water
2. have player use /afk
3. other player bumps into them causing them to push through a wall

### Plugin list:
essentials

### Paper build number:
git-paper-525 (1.13.2 build)
### Anything else:
it might be an essentials issue I just wanted to post here as well

**Comment by ShaneBeee** [comment]
I would assume this is totally an issue with Essentials, since there is no "AFK" in Minecraft/Spigot/Paper or any of that, thats strictly something Essentials has added.

**Comment by caojohnny** [comment]
Not able to reproduce, it might help to upload a video if possible.
