### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#1897]
My server has crashed daily for the past week now and I cant figure out what's causing it... 

My crash logs: https://pastebin.com/JTiWRQY6

Plugins: https://pastebin.com/wykkafyd

Verison: git-Paper-525 (mc 1.13.2)

**Comment by jordanwilliams1** [comment]
I'm thinking it might be orebfuscator-4.4.4.jar ?

I Run async chunks.

**Comment by 0-x-2-2** [comment]
Seems like something is modifying the world async so it probably is orebfuscator.

**Comment by zachbr** [comment]
Closing as an unknown plugin modifying `PlayerChunk#players` asynchronously. If additional information is provided or discovered to usurp that assumption we can go from there.
