### ISSUE TITLE
Server says it's extremely out of date but it isn't

### ISSUE THREAD

**Issue by Platinteufel** [PaperMC/Paper#19]
Hey, I've just installed PaperSpigot and now it tells me I'm about 3000 versions behind .. I'm a bit confused, am I running a current spigot-version with all spigot/craftbukkit-patches? 
http://fs5.directupload.net/images/160207/ds3zt3v4.png

**Comment by zachbr** [comment]
This is a known issue with the Paperclip builds. It will be fixed when we drop PaperTools and update to Minecraft 1.9. It does not affect anything, when you download the latest version you are running the latest version.

**Comment by zachbr** [comment]
Fixed it for Paperclip users broke it for PaperTools users.
Paperclip users will see the correct, expected output. PaperTools users will see "Error obtaining version output".

Consider it one more reason to ditch PaperTools early.
