### ISSUE TITLE
Tab Autofill doesn't work. Commands always in red.

### ISSUE THREAD

**Issue by gotsly** [PaperMC/Paper#1900]
### What behaviour is expected:
I expected Paper to work well with 1.13 auto completion with the tab button.

### What behaviour is observed:
Commands when being written are always in red. If you write the command alone (i.e. /gamemode) it says unknown command until you insert the actual game mode (i.e. /gamemode creative). This happens with all other commands regardless of what plugin they are from.
### Steps/models to reproduce:
Really don't know what to add here. Just find a way to fix the tab auto completion and get commands working like normally.

### Plugin list:
BannerMaker
BKCommonLib
BlocksHub
Citizens
ClearChat
CoreProtect
DiscordSRV
DummyFawe
EssentialsX
EssentialsXChat
EssentialsXProtect
EssentialsXSpawn
FastAsyncWorldEdit
LuckPerms
Multiverse-Core
PerWorldInventory
PlaceholderAPI
ProtocolLib
ServerlistMOTD
SimpleRename
Skript
TownyChat
Towny
TownyNameUpdater
Vault

### Paper build number:
Build #565 (the same has happened with previous builds)
### Anything else:
Maybe it's the compatibility with 1.13.2?

**Comment by aikar** [comment]
The described behavior of gamemode is vanilla behavior.

You would have to ask Mojang to create a handler for /gamemode by itself.

If any thing else is off with plugins showing red on /foo then it would be a bug in one of you plugins, as in a vanilla server without any plugins manipulating Brigadier packets, tab is working as intended.

**Comment by aikar** [comment]
Start removing plugins until the commands work again.
I would start with BKCommonLib and anything using ProtocolLib

Also make sure you didn't turn off tab complete in spigot.yml
there is a setting commands.tab-complete
