### ISSUE TITLE
Tab Completion suggests vanished players

### ISSUE THREAD

**Issue by Drc-DEV** [PaperMC/Paper#1901]
When this option is enabled

> suggest-player-names-when-null-tab-completions: true

the player gets the list of all players in the server, even the vanished ones. This would not be a problem if vanish plugins handled the Tab completion to remove vanished players, but for example plugins like premiumvanish make players crash when they handle tabulator packets.

My suggestion is to exclude players from the Tab Completion if player.canSee(Player player); is false when the above mentioned option is true.

**Comment by aikar** [comment]
```java

    private List<String> tabComplete0(CommandSender sender, String alias, String[] args, Location location) throws IllegalArgumentException {
        Validate.notNull(sender, "Sender cannot be null");
        Validate.notNull(args, "Arguments cannot be null");
        Validate.notNull(alias, "Alias cannot be null");

        if (args.length == 0) {
            return ImmutableList.of();
        }

        String lastWord = args[args.length - 1];

        Player senderPlayer = sender instanceof Player ? (Player) sender : null;

        ArrayList<String> matchedPlayers = new ArrayList<String>();
        for (Player player : sender.getServer().getOnlinePlayers()) {
            String name = player.getName();
            if ((senderPlayer == null || senderPlayer.canSee(player)) && StringUtil.startsWithIgnoreCase(name, lastWord)) {
                matchedPlayers.add(name);
            }
        }

        Collections.sort(matchedPlayers, String.CASE_INSENSITIVE_ORDER);
        return matchedPlayers;
    }
```
It already does this....

**Comment by aikar** [comment]
FYI this code is shared to CraftBukkit.

All that Paper setting does is allow you to turn off the CraftBukkit behavior if you don't want it to suggest player names.

You may have something else leaking it instead.

**Comment by Drc-DEV** [comment]
Thank you, it could be ProtocolSupport then.. Thanks anyways
