### ISSUE TITLE
Entity and team

### ISSUE THREAD

**Issue by Jerozgen** [PaperMC/Paper#1904]
#### First bug:
Summoned entity with `Team` NBT tag **is** added to specified team.
#### Second bug:
An entity **doesn't attack** me if we're from same team.

#### First bug:
Summoned entity with `Team` NBT tag **isn't** added to specified team.
#### Second bug:
An entity **attacks** me if we're from same team.

#### First bug:
1. `/team add test`
2. `/summon skeleton ~ ~ ~ {Team:"test"}`
3. `/team list test`
#### Second bug:
1. `/team add test`
2. `/summon skeleton`
3. `/team join test @e[type=skeleton]`
4. `/team join test`
5. `/gamemode adventure`

### Paper build number:
- git-Paper-566 (MC: 1.13.2)

**Comment by mikroskeem** [comment]
In paper.yml, check `allow-non-player-entities-on-scoreboards`

**Comment by Jerozgen** [comment]
Ok, thank you!
