### ISSUE TITLE
asyncworldedit physics freeze broken repeaters

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#191]
using build 647 currently, anything pasted with asyncworldedit causes repeaters in the area to not update, redstone torches as well, however if i travel to an area far away from the pasted item, redstone works

happens both with fire-physics-event-for-redstone true and false, and after a server restart

https://gyazo.com/22797aa6efb412bc811ff9ee8fd4e897

I am not sure if this is an issue with the new optimizations in paperspigot, or a bug with asyncworldedit

**Comment by aikar** [comment]
Do you have AWE fast mode on? That avoids physics calls on paste.

**Comment by PhanaticD** [comment]
yea but the weird thing is the whole area stays with no repeaters or torches even after server restart

**Comment by zachbr** [comment]
Closing for age/inactivity. If this continues on latest, open a new issue please.
