### ISSUE TITLE
Citizens last build (1626) and Paper

### ISSUE THREAD

**Issue by aurel85** [PaperMC/Paper#1910]
Hi,

With the last update of Citizens we can't longer make it work with PaperSpigot. Apparently you have to make an update on your side (with Spigot it's ok)
https://www.spigotmc.org/resources/citizens.13811/update?update=269226

Error : https://hastebin.com/azapoxoqad.cs
/version : 
![Capture](https://user-images.githubusercontent.com/24486147/54650131-51949380-4aad-11e9-9f10-132620c97df4.PNG)

Thank you in advance !

**Comment by zachbr** [comment]
There are never ETAs for upstream updates.
