### ISSUE TITLE
Players aren't picking up items correctly

### ISSUE THREAD

**Issue by carlpoole** [PaperMC/Paper#1911]
### What behaviour is expected:
When in creative mode and occasionally in survival, the player is not able to pickup some items floating on the floor. Item's are not anything in particular, no special/hacky item data.

### What behaviour is observed:
When in creative and sometimes in survival items don't get picked up.

### Steps/models to reproduce:
Go into creative mode, give yourself a looting sword like this: 

`/give @p minecraft:diamond_sword{Enchantments:[{id:"minecraft:looting",lvl:10000}]} 1`

And then summon and kill a mob like a chicken or a pig. Behavior is inconsistent with vanilla MC because all the items are supposed to get sucked up even if the inventory is full. It didnt seem to matter if the inventory was full or not, but at some point the items stop being picked up and you can run through them on the ground and nothing happens.

Tested in 1.13.2 vanilla and all the items get sucked up fine.

### Plugin list:
None

### Paper build number:
Tested 525, 565

### Anything else:
No further info at this time. 

Thank you!

**Comment by aikar** [comment]
> no special/hacky item data.
> {Enchantments:[{id:"minecraft:looting",lvl:10000}]}

That would be hacky item data.... 

>with vanilla MC because all the items are supposed to get sucked up even if the inventory is full.

Are you meaning when you have a stack at 50 for example and try to pick up 4, to let it merge into until it hits 64?

**Comment by carlpoole** [comment]
The hacky item data was in reference to the drops themselves (ie. they are just standard vanilla items like raw chicken or feathers etc. and not stacks of items with unusual nbt data)

Not exactly. When you are in creative in vanilla and you run through a pile of items, they all get picked up, whether you have the space or not. The excess are just "deleted". In paper it seems like I can fill my inventory and then it appears to stop. If I kill another mob while having a full inventory, some drops are able to be picked up, but then it stops again.

Note: I just re-tested and then restarted the server. Player was in creative with full inventory, was able to kill another mob with the looting 1000 sword and absorb all the items to fill my inventory but then on a second kill about half the items were picked up before it stopped.

**Comment by carlpoole** [comment]
Another bug that I think is related to this: If a player puts some items in their offhand that doesn't equal a full stack (eg. 32 leather) and runs into a pile of floating leather items, it isn't picking up 32 more leather to fill the stack as expected. In vanilla it works every time, and the offhand stack is filled to 64. In paper it works once or twice then stops. (if it works, drop out 32 items and try again, it stopped working after this for me) -- same testing environment as above.

What my inventory looks like: https://imgur.com/lhYFetw

Not picking up any extra leather as I should be (only 32 in off hand slot and no more will pick up):https://imgur.com/8M2FMHa

**Comment by aikar** [comment]
```java
                // Possibly < 0; fix here so we do not have to modify code below
                this.pickupDelay = 0;
            }
            // CraftBukkit end

            if (this.pickupDelay == 0 && (
```
I see the issue here. Bukkit only sets pickupDelay = 0 if you can hold it, allowing it to stay negative which breaks the vanilla logic.

Should be able to just make the if do <= 0 instead
