### ISSUE TITLE
SpawnChangeEvent seemingly not fired for commands

### ISSUE THREAD

**Issue by stefvanschie** [PaperMC/Paper#1913]
### What behaviour is expected:
When registering a SpawnChangeEvent in a plugin, it'd be expected that this event would be fired whenever the world's spawn changes. The reason I think this is its supposed behaviour, is because of the description seen on the JavaDocs which states: "An event that is called when a world's spawn changes." (https://papermc.io/javadocs/1.13/org/bukkit/event/world/SpawnChangeEvent.html).

### What behaviour is observed:
When a SpawnChangeEvent has been registered in a plugin, this event is seemingly never fired. I have tried using both the `/setworldspawn` and `/spawnpoint` commands from Vanilla Minecraft from both an operator on the server and the console, as well as by specifying various different parameters, such as the player and the location. However none of these attempts resulted in the event being fired.

### Steps/models to reproduce:
I first created a plugin with the following code: https://hatebin.com/rmrwsvgomw. I then compiled this plugin, put it in the plugins folder on my local testing server and started it by activating the paperclip.jar file from the command line. After that I executed both the `/setworldspawn` and `/spawnpoint` commands both without parameters and with parameters testing multiple different players and positions. I executed these commands from both the console and as a player (with the needed permission).

### Plugin list:
Only the plugin that I used for testing this bug, of which the code can be seen in the above section, was on the server when encountering the described behaviour.

### Paper build number:
"This server is running Paper version git-Paper-570 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)"

### Anything else:
Changing the world spawn by calling `World#setSpawnPoint` does, on the other hand, trigger the event.

**Comment by aikar** [comment]
I bet its due to this event being created before vanilla added a way to even set the spawn, so it previously was limited to API level changes only.

**Comment by BillyGalbreath** [comment]
PR was merged that fixed this

**Comment by Chew** [comment]
Someone forgot to link the issues :cry:
