### ISSUE TITLE
VoxelShape#a NMS method seems to be removed?

### ISSUE THREAD

**Issue by FozzieHi** [PaperMC/Paper#1914]
### Paper build number:
git-Paper-577

### Anything else:
As this is a developer enquiry, the template didn't seem appropriate here as this error is just spammed when the jar is loaded as I check this every time a packet is sent, I am wondering why Paper has renamed the VoxelShape#a method and what to? it doesn't seem to be present in the latest version of Paper and is really conflicting with my plugin.

The VoxelShape#a method is non-existent when I try to access it here - https://github.com/funkemunky/Atlas/blob/master/API/src/java/cc/funkemunky/api/utils/blockbox/boxes/BlockBox1_13_R2.java#L59

**Comment by aikar** [comment]
Spigot is changing mappings constantly now. you're "expected" to call CraftMagicNumbers.INSTANCE.getMappingsVersion() and load mappings based off that completely unfriendly value to know what mappings to load.

this is all on spigot.

**Comment by aikar** [comment]
recommended to only support the latest mapping - so just update the name and release a new jar. trying to support every mapping he has released will be a nightmare.
