### ISSUE TITLE
When player join, it shows an error!

### ISSUE THREAD

**Issue by foxi69** [PaperMC/Paper#192]
# Incompatibility (Bug)
### Steps/models to reproduce:

> null
# Crash, Stacktrace
### Link/paste of stack trace

http://pastebin.com/RY5sLV4j
### Plugin list:

Plugins (44): RedstoneClockPreventer, WorldEdit, SimpleTrading, TitleMotd, AnimatedNames, ChatControl, ActionHealth, ProtocolLib, SkinsRestorer, iDisguise, getID, PermissionsEx, TreeAssist, Tab, Lottery, CustomBot, FAQ, Vault, LightAPI, ShopGUIPlus, Essentials, ShareControl, PlaceholderAPI, SexyMotd, BattlePets, Jobs, PlotSquared, Multiverse-Core, Holograms, DeluxeChat, TreasureChest, HeavySpleef, AncientGates, CraftBook, ServerSigns, GriefPrevention, EssentialsSpawn, AntiXRay, AuthMe, Paintball, MobArena, ProtectionLib, FurnitureLib, DiceFurniture
### Paper build number:

git-Paper-643 also occurring on git-Paper-647

This server is running Paper version git-Paper-647 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT

**Comment by zachbr** [comment]
Please provide a list of your plugins, as we ask for in the issue template you appear to have ignored.

**Comment by foxi69** [comment]
Sorry :(

Plugins (44): RedstoneClockPreventer, WorldEdit, SimpleTrading, TitleMotd, AnimatedNames, ChatControl, ActionHealth, ProtocolLib, SkinsRestorer, iDisguise, getID, PermissionsEx, TreeAssist, Tab, Lottery, CustomBot, FAQ, Vault, LightAPI, ShopGUIPlus, Essentials, ShareControl, PlaceholderAPI, SexyMotd, BattlePets, Jobs, PlotSquared, Multiverse-Core, Holograms, DeluxeChat, TreasureChest, HeavySpleef, AncientGates, CraftBook, ServerSigns, GriefPrevention, EssentialsSpawn, AntiXRay, AuthMe, Paintball, MobArena, ProtectionLib, FurnitureLib, DiceFurniture

**Comment by RoboMWM** [comment]
You should test which plugin is causing this by loading half your plugins, seeing if it exists or not, and then half again, etc. Or load plugins in one-by-one, whichever is easier.

**Comment by foxi69** [comment]
Hmmm the problem is the SkinsRestorer, but the dev said is unfixable. mojang/minecraft/bukkit error

**Comment by foxi69** [comment]
so no way to fix it in paper?

**Comment by zachbr** [comment]
Not in this case, resolving the error would just make the players not get teleported when they joined. This isn't something we'll be fixing. It'll be up to the plugin author to find a fix or workaround for, or for you to use something that doesn't break this
