### ISSUE TITLE
Expose getValidBlockForPosition in the api

### ISSUE THREAD

**Issue by Frogperson** [PaperMC/Paper#1921]
**Is your feature request related to a problem? Please describe.**
Not really a "problem" per se, but it would be pretty handy to make sure the block we're placing is in a valid spot where the server would allow a player to place it as well.

**Describe the solution you'd like**
Title kind of says it all. Basically, expose the nms method `Block.getValidBlockForPosition` to the api so plugins can check if a location is "safe" before placing a block.

**Comment by Chew** [comment]
I've been told by @JRoy this is no longer in the Minecraft Server, and as such can't be implemented anymore. Thank you for your suggestion!
