### ISSUE TITLE
[Paper 597] Paper server not allowed to use empty enchantment tag

### ISSUE THREAD

**Issue by SteveKunG** [PaperMC/Paper#1923]
### What behaviour is expected:
When you using `/give @s diamond{Enchantments:[{}]}` command, you can create a fake glowing effect.

### What behaviour is observed:
A diamond that you given using command from above, it's looks like normal item.

### Steps/models to reproduce:
- Start your Paper server.
- Using `/give @s diamond{Enchantments:[{}]}` command

### Paper build number:
Paper 597

### Anything else:
So, this break all my datapacks that uses fake enchantment to make item glowed.
Maybe configuration for allowed to use empty enchantment tag?

![2019-03-29_23 37 39](https://user-images.githubusercontent.com/6128413/55248122-b608dd00-527b-11e9-93d9-efdc4c8d2923.png)
![2019-03-29_23 37 51](https://user-images.githubusercontent.com/6128413/55248123-b608dd00-527b-11e9-9d23-cf239df26781.png)

**Comment by Spottedleaf** [comment]
confirmed for cb causing the issue by stripping the tag, vanilla does not strip the tags

**Comment by kickash32** [comment]
Can you test again? It works for me on paper-284.

**Comment by SteveKunG** [comment]
Yeah, can confirm it fixed.
