### ISSUE TITLE
Option to auto-remove unknown attributes or remove ignoring message spam.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#1924]
Paper dev 597 (Paper 1.13.2)

My console seems to be spamming this warning repeatedly (50+ times/sec).

```
[15:53:39] [Server thread/WARN]: Ignoring unknown attribute 'generic.rideSpeed'
[15:53:39] [Server thread/WARN]: Ignoring unknown attribute 'generic.rideMaxY'
```

This attribute was added via the plugin Ridables by @BillyGalbreath.
https://github.com/BillyGalbreath/Ridables/blob/8ecb377fc74f454411610a004e6a335edbddcf3f/src/main/java/net/pl3x/bukkit/ridables/entity/RidableType.java#L148
https://www.spigotmc.org/resources/1-13-2-ridables-ride-and-control-any-mob-with-full-wasd-control.58985/

I removed the plugin for testing purposes due to it overriding some vanilla right click interactions.

Would it be possible to add an option to automatically strip (remove) unknown attributes instead of constantly complaining? Or alternatively, add an option to disable the check / warning? I have no way to bulk edit all player.dat files to remove this attribute, or even worse, on all living entities (mobs) that it's applied retrospectively on.

**Comment by BillyGalbreath** [comment]
Should probably close this since core team doesnt want to suppress the warnings (see comments in my closed PR linked above)

**Comment by Chew** [comment]
The quote in question:

> From the previous time this was raised, I was skeptical on the whole "providing means to disable legit warnings", there are cases where they can be annoying, but overall dropping of them is highly questionable to me

Closing as a result of this, consider a console spam suppressor plugin, apparently those exist.

**Comment by AngelOfCreation** [comment]
I don't even use paper, but this was a terrible decision.
