### ISSUE TITLE
/timings paste and /timings report returns a Upload Error: 200: OK 

### ISSUE THREAD

**Issue by kafuuchino-desu** [PaperMC/Paper#1925]
when i was doing a performance test on my server after moving from Windows to Centos, /timings report and /timings paste always return a Upload Error: 200: OK without further information in the log. Before i move the server to Centos, timings worked well on windows using the same version.
Is there a spicified port required for timings to work normally?

Plugin list:
coreprotect, vault, permissionsEx

Paper build number:
git-Paper-473

Anything else:
Firewalld on the server is running, players connect the server through Bungeecord.

**Comment by aikar** [comment]
Please update your paper for one, but be sure you have outbound 443 (Web/SSL) open and also ensure that your server is not ancient which CentOS is guilty of being usually.

Your server needs to support SNI for SSL and modern TLS versions.
