### ISSUE TITLE
Bound lead vanishing

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1926]
### What behaviour is expected:
Sheep bound to a fence pole by a lead. Lead is visible.

### What behaviour is observed:
Lead is visible as long as player stays within 48 blocks or joins the game near sheep. As soon as player flies off outside the range of 48 blocks, and returns to the animal, the lead is invisible. Only the knot remains.

### Steps/models to reproduce:
Paper 597, place fence pole, place sheep, bind it with a lead an fly off.

### Plugin list:
Pretty default: WE 7 beta 5, WG 7 beta 3, Plugman, Multiverse. Vault, nothing fancy.

### Paper build number:
Build 597

### Anything else:
The range of 48 suggests it has something to do with entity-tracking-range.
Tested with optifine 1.13.2 E7 and vanilla client

![2019-03-30_14 51 37](https://user-images.githubusercontent.com/28690790/55276986-64079c00-52fb-11e9-895c-0b8ad0db9bc4.png)

**Comment by HauserGrim** [comment]
+1
![image](https://user-images.githubusercontent.com/37507220/55282512-b83b6c00-534d-11e9-8052-1829dbdb625d.png)

**Comment by ShaneBeee** [comment]
This is a vanilla behaviour, that even happens in single player.
I could be wrong but I believe this is a visual glitch that is client side

**Comment by x1p** [comment]
Ah ok. I assume there is nothing that paper can do about that. I'll close this issue then. Thanks anyway.
