### ISSUE TITLE
Entities receive incorrect/odd SpawnReason

### ISSUE THREAD

**Issue by aeonlamb** [PaperMC/Paper#1933]
In the recent change to the mob cap mechanics in paper build 572, it was made so that the mob cap of a world is only calculated using mobs with a certain "spawn reason", specifically `NATURAL`. However, as I discussed in [this forum post](https://papermc.io/forums/t/changes-to-the-mob-cap-in-latest-paper-builds/672) I made the other day, there are a few cases where entities get incorrect or unusual spawn reasons.

Seeing as the spawn reason is determined by bukkit (I believe?), it's possible that I may be reporting this bug in the wrong place, or that these little quirks of this system are too insubstantial to even consider a bug, or something of that nature. If that's the case, feel free to close the ticket, but I figured I may as well send something in anyways.

In all the following cases, an entity that is spawned gets a spawn reason that is incorrect:

- Mobs spawned due to world generation get `DEFAULT` instead of `CHUNK_GEN` (tested using async chunk loading/generation, not sure if related)
- Items dropped by dying mobs / armor stands breaking get `CUSTOM` instead of `DEFAULT` (tested without any plugins)
- Mobs spawned from a dispenser using a spawn egg get `SPAWNER_EGG` instead of `DISPENSE_EGG`
- Mobs spawned from a mob spawner block get `DEFAULT` instead of `SPAWNER`

In the following cases, an entity gets a spawn reason that seems strange or unexpected:

- Fish spawned from a player using a fish in a bucket get `SPAWNER_EGG`. There's not another more fitting spawn reason for this currently, but having it lumped in with spawn eggs seems strange to me.

There may be other incorrect or strange spawn reasons, but I can only spend so much time testing various cases where entities get spawned in and how the server handles them. I determined the spawn reason simply by using `/data get entity` on the entity in question, its NBT data includes the spawn reason as saved by Paper.

### Plugin list:
None

### Paper build number:
1.13.2 build 597

### Anything else:
Not a bug, but I think worth mentioning: all entities that existed on the server prior to this update will receive the spawn reason `DEFAULT` as soon as you update, because the server cannot determine any other spawn reason for them. That makes them no longer count towards mob cap even if they ordinarily would. I believe this is intended, but I have to wonder if there's something that could be done to improve that behavior or not. If not, it's not really a huge deal.

**Comment by aikar** [comment]
see: https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0423-Entity-getEntitySpawnReason.patch#L59

Anything not persistent will actually default to NATURAL

Animals though are likely to be getting wrong type since bukkit screwed the pooch and made them all persistent, but don't know for sure. animal limits are so low anyways, I don't think it's caused much trouble.

but yes there's many places the spawn reason is wrong/could be more refined, so i'll consider this a valid report of that.

**Comment by aeonlamb** [comment]
Oh ok, didn't know that. I believe nearly all the pre-existing mobs I checked were indeed animals, they were all `DEFAULT`. I just assumed that everything pre-existing defaulted to default, because, well... it's called default. xD makes sense though.
