### ISSUE TITLE
ProtocolLib sending packet without executing filters fails when world xray is enabled

### ISSUE THREAD

**Issue by bergerkiller** [PaperMC/Paper#1934]
### What behaviour is expected:
When sending a packet using [Protocollib's sendServerPacket API](https://aadnk.github.io/ProtocolLib/Javadoc/com/comphenix/protocol/ProtocolManager.html#sendServerPacket(org.bukkit.entity.Player,%20com.comphenix.protocol.events.PacketContainer,%20boolean)), with filters set to false, no event is received by protocollib packet listeners listening on that packet. Monitors do receive the packet event.

### What behaviour is observed:
When in paper.yml the:
```
world-settings:
  default:
    anti-xray:
      enabled: true
```
Is set, this functionality breaks, and a registered packet listener on a packet is triggered despite filtered=false being set when sending the server packet. This is currently causing breakage where a plugin is cancelling a packet it should not be able to see at all.

### Steps/models to reproduce:
Blank new world, create a little wall with item frames, use /map to get a maplands map and put it in the item frames. Leave the server, rejoin. Now suddenly no map contents are displayed, because the map packet is cancelled (it assumes it is not coming from maplands), because the map packet is not filtered.

It is also very likely that this issue only occurs right after a player joins the server, since this is when this is observed. Further updates seem to work correctly.

### Plugin list:
ProtocolLib (#425), Maplands (v0.5), BKCommonLib (#528)

_can provide a small demo plugin to reproduce the issue if requested, since this problem runs quite deep_

### Paper build number:
This server is running Paper version git-Paper-584 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Anything else:
Most likely Paper is registering some sort of packet listener of its own to process the world map packets before they are sent to the clients, to obfuscate them. This is creating a strange incompatibility with protocollib where the aforementioned logic breaks. The packet that broke is the 'Map packet', which is what is sent to set the contents of a Minecraft Map item. (not a map chunk packet).

This might be a race condition when players join, because maplands can send map update packets at a later stage and then it does appear to actually work. (no listener is fired). Only right after a player joins does this logic break currently.

This was a very difficult issue to track down, and this issue might be in Protocollib itself. I don't know enough about the internals of either to make a good distinction.

**Comment by aikar** [comment]
you didnt provide a link to maplands, but the way you worded things, it sounds like working as intended?

According to the javadocs you linked, when filters=false, it should behave exactly as you described, where only MONITOR is fired.

If you want pre monitor, you need to set filters=true.

**Comment by bergerkiller** [comment]
The problem is that not only MONITOR is fired, but all lower levels as well, despite filters=false

There's a packet listener on level NORMAL which is receiving the event for the packet, and it should not be getting that when sending a server packet with filters=false being set. This listener is cancelling the packet I'm trying to send, resulting in a blank item frame in the client.

Stripping down the entire server, changing the x-ray enabled options back to false was the only thing that eventually fixed a bug someone was having. I could then easily reproduce it myself.

**Comment by bergerkiller** [comment]
If it helps:
- [Listener cancels the event here](https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/internal/network/ProtocolLibPacketHandler.java#L275)
- [Packet is sent here](https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/internal/network/ProtocolLibPacketHandler.java#L129)

I understand that, being so deep down the belly of another library isn't helping, so I'm willing to write a small plugin to reproduce the issue using solely ProtocolLib.

*edit*

I noticed the extra null (for NetworkMarker) when sending the packet. Using the method without NetworkMarker parameter did not fix it.

**Comment by bergerkiller** [comment]
I've written a 100% reproducible test case that only has ProtocolLib as dependency. The issue is a little more complex, and I guess it's pure chance I ran into it. To trigger this bug, the packet must be sent one tick delayed in onPlayerJoin. Any later, or directly, and it works fine.

'Working fine' means that the Packet Listener is NOT notified of the sending of the packet when filters=false.

Test plugin:
https://www.dropbox.com/s/ocskgqpod1b0dvd/ProtocolLibSendUnfilteredPacketTest-1.0.jar?dl=0

Usage & Test plan:
1. Install this plugin and ProtocolLib in a server
2. Make sure xray is enabled in paper.yml
3. Join the server
4. You will see two messages logged in the server log.

The first one is as expected, it's the join message:
`onPacketSending() fired: '{"extra":[{"color":"yellow","text":"bergerkiller"},{"color":"yellow","text":" joined the game"}],"text":""}'`

The second one though, should NOT have been logged, as we are sending a server packet where filters=false, so NORMAL priority listeners should not see it:
`onPacketSending() fired: '{"text":"Packet sent one tick delayed in onPlayerJoin (filters\u003dfalse)"}'`

You may have to rejoin the server a few times as the bug seems to not be 100% guaranteed to occur, but likely enough it can be reproduced.

5. Stop the server, disable xray again.
6. Join server again
7. Observe how now the 'Packet sent one tick delayed in onPlayerJoin' message never appears, which is how it is supposed to be.

I also added the command /testsendpacket and /testsendpacket filters which will send the packet (filters=false and filters=true). This always succeeds, and only when filters=true is the listener called.

This means this bug only occurs in a very short time frame, the tick after a player joins the server. When you send the packet inside onPlayerJoin it is ignored properly.

This bug also only, ever, occurs when you enable the xray in paper, but I'm starting to think this might be an issue ticket better suited for the ProtocolLib issue tracker.

Source:
```java
package com.bergerkiller.bukkit.psup;

import java.lang.reflect.InvocationTargetException;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.java.JavaPlugin;

import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.events.ListenerOptions;
import com.comphenix.protocol.events.ListenerPriority;
import com.comphenix.protocol.events.ListeningWhitelist;
import com.comphenix.protocol.events.PacketContainer;
import com.comphenix.protocol.events.PacketEvent;
import com.comphenix.protocol.injector.GamePhase;
import com.comphenix.protocol.wrappers.EnumWrappers.ChatType;
import com.comphenix.protocol.wrappers.WrappedChatComponent;

public class Main extends JavaPlugin implements org.bukkit.event.Listener {
    private MainPacketListener packetListener;

    public class MainPacketListener implements com.comphenix.protocol.events.PacketListener {

        @Override
        public ListeningWhitelist getSendingWhitelist() {
            return ListeningWhitelist.newBuilder()
                    .priority(ListenerPriority.LOWEST)
                    .types(PacketType.Play.Server.CHAT)
                    .gamePhase(GamePhase.PLAYING)
                    .options(new ListenerOptions[] { ListenerOptions.ASYNC } )
                    .build();
        }

        @Override
        public void onPacketSending(PacketEvent event) {
            PacketContainer packet = event.getPacket();
            String message = packet.getChatComponents().read(0).getJson();
            System.out.println("onPacketSending() fired: '" + message + "'");
        }

        @Override
        public Plugin getPlugin() {
            return Main.this;
        }

        @Override
        public ListeningWhitelist getReceivingWhitelist() {
            return ListeningWhitelist.EMPTY_WHITELIST;
        }

        @Override
        public void onPacketReceiving(PacketEvent event) {
        }
    }

    @Override
    public void onEnable() {
        this.packetListener = new MainPacketListener();
        ProtocolLibrary.getProtocolManager().addPacketListener(this.packetListener);
        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @Override
    public void onDisable() {
        ProtocolLibrary.getProtocolManager().removePacketListener(this.packetListener);
        this.packetListener = null;
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        boolean filters = (args.length > 0 && args[0].equals("filters"));
        sendChatPacket((Player) sender, "Packet sent by command", filters);
        return true;
    }

    @EventHandler
    public void onPlayerJoin(final PlayerJoinEvent event) {
        sendChatPacket(event.getPlayer(), "Packet sent in onPlayerJoin", false);
        Bukkit.getScheduler().scheduleSyncDelayedTask(this, new Runnable() {
            @Override
            public void run() {
                sendChatPacket(event.getPlayer(), "Packet sent one tick delayed in onPlayerJoin", false);
            }
        });
    }

    public static void sendChatPacket(Player player, String message, boolean filters) {
        PacketContainer packet = new PacketContainer(PacketType.Play.Server.CHAT);
        packet.getChatComponents().write(0, WrappedChatComponent.fromText(message + " (filters=" + filters + ")"));
        packet.getChatTypes().write(0, ChatType.CHAT);
        try {
            ProtocolLibrary.getProtocolManager().sendServerPacket(player, packet, filters);
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by bergerkiller** [comment]
This is an old issue now, but I'd like to revive it. I have found additional information about what causes it, and it has to do with your changes to the NetworkManager to handle map chunk packets.

https://github.com/dmulloy2/ProtocolLib/issues/763#issuecomment-581083651

**Comment by bergerkiller** [comment]
This issue can be closed, since a fix was introduced in ProtocolLib https://github.com/dmulloy2/ProtocolLib/pull/782
