### ISSUE TITLE
PaperChunkLoader - Unsupported key: minecraft:skull in TaggedChoiceType

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#1935]
Paper dev 597 (Spigot 1.13.2)
ProtocolSupport dev 372

RE: https://github.com/PaperMC/Paper/issues/1623

This issue seems to be back. Noticing the errors occurring in my console and logs. :(
```
[17:11:23] [PaperChunkLoader-3/WARN]: Unsupported key: minecraft:skull in TaggedChoiceType[id, MobSpawner -> MuType[V99_4], 
Chest -> ((Tag["Items", List[MuType[V99_3]]] | NilDrop), NilSave), 
Airportal -> NilSave, 
DLDetector -> NilSave, 
Banner -> NilSave, 
FlowerPot -> ((Tag["Item", (Int | NamedType["item_name", NamespacedString])] | NilDrop), NilSave), 
Trap -> ((Tag["Items", List[MuType[V99_3]]] | NilDrop), NilSave), 
EnchantTable -> NilSave, 
Furnace -> ((Tag["Items", List[MuType[V99_3]]] | NilDrop), NilSave), 
Dropper -> ((Tag["Items", List[MuType[V99_3]]] | NilDrop), NilSave), 
Comparator -> NilSave, 
Cauldron -> ((Tag["Items", List[MuType[V99_3]]] | NilDrop), NilSave), 
Control -> NilSave, 
EndGateway -> NilSave, 
Music -> NilSave, 
Piston -> NilSave, 
Beacon -> NilSave, 
Skull -> NilSave, 
Hopper -> ((Tag["Items", List[MuType[V99_3]]] | NilDrop), NilSave), 
Sign -> NilSave, 
Structure -> NilSave, 
EnderChest -> NilSave, 
RecordPlayer -> ((Tag["RecordItem", MuType[V99_3]] | NilDrop), NilSave)]
```

**Comment by aikar** [comment]
ultimately this is a sign that something is off in a chunk format that made it think it needs to be converted but didnt, or it did but the previous save state is unknown how to handle it.

I have pending changes to fix this in my own fork that I will be bringing over soon, by ripping out the entire 1.13 system for legacy conversions.
if that doesn't fix it then nothing will. mojang messed up with this new conversion system and there won't be much more we can do beyond what i have pending.

i'm going to go ahead and close this as i'm not going to remember to do it later - just keep eye on paper updates, and i'll prob make an announcement in discord when it lands.

ultimately this should be filed to mojang as this shouldn't of happened in chunk loading unless you have a plugin storing custom data in the chunk, and it's too systemic of a problem to do any more fixing than what i've done (and my 'fix' is pretty cut throat - i throw away mojangs system as much as i can)
