### ISSUE TITLE
Obtain ItemStack from Trident entity

### ISSUE THREAD

**Issue by Draycia** [PaperMC/Paper#1937]
**Is your feature request related to a problem? Please describe.**
I would like to make it so loyalty tridents return to the player when they fall in the void or are destroyed by other possible means. Currently, it's difficult to obtain the ItemStack of the Trident entity and seemingly impossible without using NMS. Reflection may also be required to gain visibility of required methods.

**Describe the solution you'd like**
Add a method `getItemStack()` to the Trident entity or an alternate method to obtain the thrown Trident's original ItemStack.

**Describe alternatives you've considered**
N/A

**Additional context**
Was told to file the request by @BillyGalbreath so he can implement it

**Comment by ravkr** [comment]
Any updates?

**Comment by aikar** [comment]
this was added in 1.15
