### ISSUE TITLE
Chunk exists method

### ISSUE THREAD

**Issue by martijnrondeel** [PaperMC/Paper#194]
It would be great if it was possible to check if a certain chunk is generated or not. Checking if `getChunkAt()` returns null doesn't work since it generates the chunk when it doesn't exist.

**Comment by Foorack** [comment]
I'm quite sure you can use loadChunk with generate set to false to check if it exists or not. I have not tested this personally though.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#loadChunk(int,%20int,%20boolean)

**Comment by zachbr** [comment]
Looks like it does. We could add a courtesy method to better describe this behavior, but I'm not sure it's necessary.
