### ISSUE TITLE
Stop and restart issues in builds 601-608 for 1.13.2. Suspect Build 601.

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#1941]
### Description of issue:
There was a change in a Paper 1.13.2 build between 598 and 608 when stopping or restarting the server for some reason the server either won't close/restart or there's a 15 second delay before the server actually exits/restarts it seems to be random. I noticed the difference because when I downgraded from the latest (608) to build 597 it would stop and restart like normal again.

![image](https://user-images.githubusercontent.com/37608633/55666963-94bc7800-589d-11e9-9bd3-cd137f1533ca.png)

### Plugin list:

![image](https://user-images.githubusercontent.com/37608633/55666969-a56cee00-589d-11e9-9bd4-613fd347eee1.png)

### Bukkit.yml, spigot.yml, paper.yml, server.properties
All default, this was tested on a fresh new server with a few plugins (for testing purposes) added 

### Paper build number:
608 (for 1.13.2)

**Comment by NullCase** [comment]
Yeah. same issue while testing 607, 602, 603 and 604.

I dont know how to code, but it seems like this is from 601: Make region files more reliable to write to (commit: c4ff33a) — aikar / githubweb

because 597 also works fine and it's just on shutdown while saving chunks with the 4 listed at the top.

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Paper/commit/c4ff33a9e577e1c9951409f6d640d149e23a19f8

has been confirmed as the cause (the calls to sync() specifically)

**Comment by axemwa** [comment]
Fixed or not an issue?

**Comment by axemwa** [comment]
Fixed in build 609
