### ISSUE TITLE
Chestshop / Admin shop, player not found

### ISSUE THREAD

**Issue by kellyhamlin** [PaperMC/Paper#1943]
https://github.com/PaperMC/Paper/issues/1525

I see this has happened before, not sure when it started exactly, on build 584 currently.

**Comment by Chew** [comment]
Because of the age of this issue, and lack of any reports about it, I will assume this is fixed. This was also 3 major versions ago, so I'd be surprised if they themselves haven't fixed. Thanks for the report!
