### ISSUE TITLE
Blocks showing wrong light level.

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#1945]
### What behaviour is expected:
Light levels display correctly.

### What behaviour is observed:
Total darkness, 0 light level on blocks next to light sources.

### Steps/models to reproduce:
Unknown.

### Plugin list:
Autorank, Bot*, CheaperPhysicsEvent, ChestShop, ChestShopNotifier*, ClaimslistClassifier, CoreProtect, dynmap*, Dynmap-GriefPrevention*, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsSpawn, GPAuctions, GPRealEstate*, GriefPrevention, GroupManager*, InGameMotd, PlaceholderAPI, PlayerVaults*, PluginLibrary*, ProtocolLib*, PVPToggle*, ReferralSystemCustom*, SuperTrails*, Vault, WorldBorder*, WorldEdit, WorldGuard

### Paper build number:
git-Paper-597

### Anything else:
Issue first reported by players on April 1st.

![](https://i.imgur.com/29iDxNo.png)

**Comment by NullCase** [comment]
![](https://i.imgur.com/26VisBP.png)

**Comment by aikar** [comment]
has this area been like this? do you have random light disabled? i did recently remove an optimization around light incase it was source of this, but light would need to be regenerated to fix any impacted areas.

**Comment by NullCase** [comment]
OK, it sounds like 610 or later has a change for me to test. and light levels will have to be updated in those few spots. 

Here's some light related settings

from spigot config:
```
world-settings:
  default:
    random-light-updates: true
```

from paper config
```
settings:
  queue-light-updates-max-loss: 10

world-settings:
  default:
    optimize-light: true

    queue-light-updates: true
````

I don't know but it seems like the dark patches can appear when the chunk is loaded. Because in the top image I had an opportunity to check and the dark patch is only inside one chunk. Also because the top image was fixed once by a player and it reappeared in the same way later.

![2019-04-05_21 34 22](https://user-images.githubusercontent.com/32785664/55707968-ca9f5080-59b2-11e9-89ad-4ee838fcdff3.png)

**Comment by Brokkonaut** [comment]
Its a minecraft bug that is fixed in 1.14: https://bugs.mojang.com/browse/MC-80966

**Comment by cblegare** [comment]
1.14 is out :D

**Comment by NullCase** [comment]
it's out! but... idk if Paper 1.14 is out :)

did you mean Paper 1.14?
