### ISSUE TITLE
"Stopped responding" after loading

### ISSUE THREAD

**Issue by kangarko** [PaperMC/Paper#1947]
When setting up a completely clean server using Paper build 610 it always prints this message after loading:

https://pastebin.com/WEpqbkUd

Also happens without plugins at all.

All files are generated by default. I tried to disable async chunks but without luck.

**Comment by kangarko** [comment]
[server files.zip](https://github.com/PaperMC/Paper/files/3051665/server.files.zip)
Attaching server files just to be sure. Always happens even when I remove all worlds completely.

**Comment by mikroskeem** [comment]
Too slow hardware? What are your server host's specs?

**Comment by kangarko** [comment]
Absolutely not. Never had this issue. Running on my local PC, i7 5820K @ 4.4Ghz, GTX 980 and 32GB DDR4 RAM.

**Comment by kangarko** [comment]
Alright, that was my mistake, I set timeout-time in spigot.yml to 0 and meant to disable it. It resulted in this fatal error.

I suggest paper adds a failsafe check for this as I may not be the only one accidentally setting this value to 0 in hope of getting rid of it. Thanks @aikar

**Comment by aikar** [comment]
there's quite a lot of configs that could cause bad things if set incorrectly. if it was one of our own id say sure, but rather not bother for a spigot config that isn't a common problem.
