### ISSUE TITLE
URLs / links / href typed in chat by clients fail to be clickable. 

### ISSUE THREAD

**Issue by godsyn** [PaperMC/Paper#195]
# Incompatibility (Bug)
### What behaviour is expected:

Typing a URL in chat should provide a clickable link to the minecraft client. 
### What behaviour is observed:

URLs typed by clients fail to provide a clickable link. They are just text. Note: if the server console typed a link, the URL works.
### Steps/models to reproduce:

Type a URL
### Plugin list:

Plugins (0):
### Paper build number:

```
[14:23:33 INFO]: This server is running Paper version git-Paper-650 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)
[14:23:33 INFO]: Checking version, please wait...
[14:23:33 INFO]: You are running the latest version
```

Note: this is specific to Paper, as Spigot does not have this behaviour.

**Comment by godsyn** [comment]
Update : seems to have broken around after build 646

> [15:05] Z750 | godsyn: please try 646. Have a sneaking suspicion if what the issue is
> [15:05] Z750 | https://ci.destroystokyo.com/job/PaperSpigot/646/
> [16:02] godsyn |  Z750: URLs do work on 646

**Comment by zachbr** [comment]
Caused by 6b75dac6f43dd55dc5ed4f850b696a3b88d37839
I'll be taking a look at this soon

**Comment by zachbr** [comment]
Should be fixed in builds 651 and newer. Thanks for reporting :)

**Comment by godsyn** [comment]
Confirmed working. Thank you.
