### ISSUE TITLE
restart on crash not killing previous server

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#1954]
my creative server crashed due to asyncworldedit plugin someone probably tried to do something way too large, and I have this restart on crash script:
screen -dmS creative java -Xms6G -Xmx8G -jar creative.jar

however I noticed a few hours later two instances running, the stuck one at 200% cpu. I did a jstack on it hope it helps: https://pastebin.com/raw/M28Cr3nw

git-Paper-612 (MC: 1.13.2)

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
