### ISSUE TITLE
Please help me analyze why my server crashed, thanks!

### ISSUE THREAD

**Issue by lintx** [PaperMC/Paper#1955]
The log said that this is not a bug, but I tried to find out why it did this but failed. The java process runs full of CPU, I have to kill java to use it normally. In the past month, it happened several times. Can help me find the reason?

### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here:https://pastebin.com/krd7wgPH

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
Plugins (23): AT, BossShopPro, BungeeTabListPlus*, Citizens, CMI, ConfigureCore*, CoreProtect, DeluxeJoin, DeluxeTags*, EpicFarming, ExpCake, FastAsyncVoxelSniper, FastAsyncWorldEdit*, LuckPerms*, Multiverse-Core*, PlaceholderAPI, PlayerShops, PlugMan*, QuestWorld, ShopGUIPlus, SkyBlock, Vault*, WorldEdit

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

[20:37:38 INFO]: This server is running Paper version git-Paper-557 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[20:37:38 INFO]: Previous version: git-Paper-551 (MC: 1.13.2)
[20:37:38 INFO]: Checking version, please wait...
[20:37:44 INFO]: You are 57 version(s) behind

**Comment by electronicboy** [comment]
Server logs indicate that somebody is likely spamming packets, I'd also suggest updating your server and keeping it maintained.

**Comment by aikar** [comment]
a lot of the lag was caused by FAWE. I informed FAWE dev of the problem and he has put in a fix for it. I don't know if FAWE builds for every commit or not though.
