### ISSUE TITLE
[RFC] Shade HikariCP into Paper

### ISSUE THREAD

**Issue by willies952002** [PaperMC/Paper#196]
Just felt like putting this on the table as a RFC (Request For Comment).

I think that it would be a good idea to include the [HikariCP](http://brettwooldridge.github.io/HikariCP/) library into Paper.
This would make it so developers don't have to worry about shading it into their plugins.

**Comment by kashike** [comment]
:-1: This is something that should be left to plugins to provide, to be honest. Plugins use different database managers, and for the majority of people this is just going to make the Paper jar larger with no gain.

**Comment by Black-Hole** [comment]
A library system would be much better. So the required libraries are downloaded by paper using maven. :)

**Comment by Ichbinjoe** [comment]
This causes a backwards compatibility issue by overwriting classes which
may be of lower version. Unless we share it to com.paper or whatever, I
would have to say no

**Comment by willies952002** [comment]
> Unless we share it to com.paper or whatever

What do you mean by this?

**Comment by kashike** [comment]
s/share/shade

> This causes a backwards compatibility issue by overwriting classes which
> may be of lower version. Unless we share it to com.paper or whatever, I
> would have to say no

and shading would cause "omg I can't find x.y package!" errors

**Comment by willies952002** [comment]
ah, okay

**Comment by willies952002** [comment]
[Black-Hole](https://github.com/Black-Hole) Said:

> A library system would be much better.

This actually gave me an idea. What if inside of the plugin jar, there was a libs.yml file, or maybe just an entry in plugin.yml, that described to the server that libs it needs, which the server then goes and loads at runtime.

However, this would probably require a major overhaul to the way the server loads.
The load order would have to be:
1. Read Plugins for Library Entries
2. Download Required Libraries
3. Start Server
4. Load libs via custom loader
5. Pre-World (Startup) Load Plugins
6. Load/Gen World
7. Post-World Load Plugins

Example Usage

> ```
> libs:
>   - com.zaxxer:HikariCP:2.4.5
>   - org.json:json:20160212
>   - ...
> ```

This is just a concept based on something that someone said \o/

Side Question: would libs passed in via classpath work close to the same way?

**Comment by DenWav** [comment]
That is just ridiculous.

**Comment by Ichbinjoe** [comment]
This is far outside of the role of the server.

**Comment by willies952002** [comment]
as I said, it's just a concept =P

**Comment by Techcable** [comment]
Why is managing plugin libs outside the role of the server?
