### ISSUE TITLE
[DungeonsXL] Chunk load bug with joining DXL world

### ISSUE THREAD

**Issue by HauserGrim** [PaperMC/Paper#1969]
What behaviour is expected:
The player should normally see chunks around.

What behaviour is observed:
When player joined to DXL map, several chunks near the spawn point are not displayed in client.

Steps/models to reproduce:
Create/edit/join to DLX map

Demonstation:
https://youtu.be/YqsYli0T_vU

Plugin list:
Only DungeonsXL

Paper build number:
Tested on 1.13.2, build 617 and 627
/ver:
"[21:33:09 INFO]: This server is running Paper version git-Paper-627 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[21:33:09 INFO]: Previous version: git-Paper-621 (MC: 1.13.2)
[21:33:09 INFO]: You are 2 version(s) behind"

Anything else:
On spigot 1.13.2  everything worked fine
No console errors
If the player moves away enough to unload the chunks and returns, they will load normally.

**Comment by zachbr** [comment]
No. Not all needed info. Fill out the template. https://github.com/PaperMC/Paper/blob/master/.github/ISSUE_TEMPLATE/behavior-bug---plugin-incompatibility.md

**Comment by HauserGrim** [comment]
Okay..., I edited issue

**Comment by HauserGrim** [comment]
UPdate

**Comment by HauserGrim** [comment]
In the new DXL snapshots, the author has changed something in loading chunks and there is no more problem on Paper.
But there was no problem on Spigot, but it was on Paper.
