### ISSUE TITLE
Items dropped from TEs are not be captured during block placement

### ISSUE THREAD

**Issue by kforbro** [PaperMC/Paper#1970]
https://youtu.be/CPyZkacmEX4

Can you fix this dupe, please? It is not worldguard bug. 
Paper 1.12.2. This dupe seems to be fixed on Paper 1.13

**Comment by electronicboy** [comment]
Should be fixed in 1613+, I've left this issue up given that it's a long-standing CB bug caused by a vanilla issue, however, in the future, please do not report duplication issues on issue tracker and contact us on IRC/Discord
