### ISSUE TITLE
Ability to disable the movement buffering whatever thingy that Paper has.

### ISSUE THREAD

**Issue by EnderSlime123** [PaperMC/Paper#1971]
**Is your feature request related to a problem? Please describe.**
Allow us to disable the "PLAYERNAME moved too quickly!" movement buffer or whatever it is.

I've removed the other parts of the format since I'm only reporting 1 thing. This has nothing to do with other plugins.

**Comment by electronicboy** [comment]
We don't allow server operators to disable warnings which aid us in debugging issues users are reporting, I did notice that spigot actually exposes the multiplier for that in spigot.yml

**Comment by EnderSlime123** [comment]
> We don't allow server operators to disable warnings which aid us in debugging issues users are reporting, I did notice that spigot actually exposes the multiplier for that in spigot.yml

Well, I'm constantly teleported back a few blocks every so often, which can be very annoying.

**Comment by electronicboy** [comment]
As already stated, you can configure the limit in spigot.yml, we're not interested in exposing options to disable warnings which mean something potentially funky is going on.

**Comment by EnderSlime123** [comment]
Alright then, sorry. Found the option.
