### ISSUE TITLE
hidePlayer not working after leaving spectator mode

### ISSUE THREAD

**Issue by crysis992** [PaperMC/Paper#1972]
### What behaviour is expected:
The player should stay hidden

### What behaviour is observed:
The player becomes visible to all other players.

### Steps/models to reproduce:
1. Hide yourself to all other online players via the hidePlayer method
2. Get into spectator gamemode
3. Spectate any entity then stop spectating the entity
4. Switch into any other gamemode
5. You're visible again

Hiding the player again on PlayerStopSpectatingEntityEvent or even ticks delayed does not work, only when switching gamemodes but that causes the player to appear for a very short timespan.

### Plugin list:
AvarionChat, Citizens, CT-Core, CTCconomy, HolographicDisplays, LuckPerms, MoonCore, PlaceholderAPI, ProtocolLib*, Vault*, WorldEdit, WorldGuard

### Paper build number:
This server is running Paper version git-Paper-620 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by BillyGalbreath** [comment]
Unable to reproduce.

Video: https://youtu.be/iOMu_KIkiRo

Test plugin:

```
public class TestPlugin extends JavaPlugin {
    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (label.equals("hideme")) {
            getServer().getOnlinePlayers().forEach(p -> p.hidePlayer(this, (Player) sender));
        }
        else if (label.equals("showme")) {
            getServer().getOnlinePlayers().forEach(p -> p.showPlayer(this, (Player) sender));
        }
        return true;
    }
}
```

**Comment by meyden92** [comment]
Not sure why, but after a clean setup/patching files again I can't reproduce it either.
I guess this issue can be closed.
