### ISSUE TITLE
Options to fine-tune recent changes to mob cap

### ISSUE THREAD

**Issue by Decme** [PaperMC/Paper#1976]
Referencing https://papermc.io/forums/t/changes-to-the-mob-cap-in-latest-paper-builds/672
Tested on build 610 and 621

My server has been running great for the most part ever since this change was implemented. I even installed Aikar's plugin 'fair natural spawns'. TPS has generally been consistent between 19 and 20, depending on number of players, maybe dropping to 18.5 on a busy day.

Recently, one of our players has built an enormous overworld gold farm with dozens of huge portals. I'm okay with this, my server allows for huge builds and players can get away with just about any build as long as it doesn't cause the server to lag.

Problem is this new farm does lag the server. A lot. Players reported TPS dropping as low as 9 when someone was afking at the farm. I think I know why. The article I linked above highlights the problem nicely.

Quote: "_NETHER_PORTAL is given to mobs spawned from nether portals. This is basically just zombie pigmen. It does not include other mobs that pass through portals; they retain their original spawn reason._"

Quote2: "_Also worth mentioning: gold farms based on zombie pigmen spawning from nether portals just became a whole lot more viable/useful after this update, because their spawn reason (NETHER_PORTAL) will never count towards the hostile mob cap. You could run a pigman farm of this design while running another natural-spawning based hostile mob farm, such as a guardian farm etc., and not impact the efficiency of either farm whatsoever. You could even combine it with a natural spawning based pigman farm to create a pigman farm that’s twice as fast and gets twice as much gold in the same amount of time… Honestly this one might be even more prone to being abused than the buff to slime farms._"

My request/suggestion: Allow players to set individual mob caps in Paper.yml on each of these spawn reasons:

DEFAULT
NATURAL
BREEDING
CHUNK_GEN
CUSTOM is the spawn
DISPENSE_EGG
SPAWNER_EGG
EGG
JOCKEY
LIGHTNING
NETHER_PORTAL
SHOULDER_ENTITY
SLIME_SPLIT
SPAWNER
FromMobSpawner
TRAP
BUILD_IRONGOLEM
BUILD_SNOWMAN
BUILD_WITHER
CURED
DROWNED
ENDER_PEARL
INFECTION
OCELOT_BABY
REINFORCEMENTS
SHEARED
SILVERFISH_BLOCK
VILLAGE_DEFENSE
VILLAGE_INVASION

To be clear, I don't want to nerf the gold farm into oblivion, I only want to adjust the rates sufficiently so that the server's performance doesn't take such a huge hit. I don't believe lowering the mob cap in Bukkit.yml would help if the gold farm ignores the mob cap.

**Comment by kickash32** [comment]
This seems overkill and hard to manage... I think a better solution would be to selectively include spawn reasons into their respective mob limits.

**Comment by Phoenix616** [comment]
Pretty sure individual mob caps would require manually keeping track of every mob type and require a decently large change in the internal mob spawning code as the Vanilla server only keeps track of the general spawn limit types that can be found in the bukkit.yml making it impossible to target individual mobs right now.

**Comment by electronicboy** [comment]
the mob spawning limits in the server ONLY apply to naturally generated mobs in the mob spawning logic, all other limits would have to be handled much further down the stream, what you're specifically asking for could easily be achieved with a plugin using the add entity events, however, this would also potentially cause issues with stuff like loading chunks going over the cap, etc

The implications and the options that would be required in such a solution would honestly be better dealt with as a plugin as opposed to being built in the server, would apply to much more versions and offer plugin devs to deal with the behavior/configuration level you're looking for
