### ISSUE TITLE
Setting a high delay in CreatureSpawner makes the number overflow

### ISSUE THREAD

**Issue by kangarko** [PaperMC/Paper#1977]
Setting a high number in CreatureSpawner#setDelay or min delay or max delay will break it and set it to a negative, firing the spawner rapidly. 

Code: https://i.imgur.com/MMuLwAv.png

Behavior:
![a](https://i.imgur.com/R8sht9j.gif)

Please note I am calling vanilla API, just using Boss for convenience testing.

### Plugin list:
Boss

### Paper build number:
621

**Comment by MiniDigger** [comment]
its a short, if you overflow a short it will be negative, minecrafts treats negative values as a reset to the delay.
nothing that paper can or should do here (other than maybe noting that in the docs)

**Comment by BillyGalbreath** [comment]
The spawn delay is stored in the code as an int (integer), but it is saved to NBT as a short. Your 50 minutes in the example given is 60,000 ticks which is way beyond the scope of a short.

**Comment by kangarko** [comment]
I see, is there anything that could be done? Many of my players desire to have this value higher than that range. Thanks.

**Comment by MiniDigger** [comment]
Do it yourself, set the highest value but store the actual value in nbt, then every x minutes, set the delay high again and decrease the amount in nbt until that value is lower than max short. then you can just remove the nbt field and let minecraft count it down.

**Comment by kangarko** [comment]
A big thanks for @BillyGalbreath for saving the day!
