### ISSUE TITLE
CraftItemStack equals doesn't recognize equality between "Damage: 0" and absent Damage nbt tag.

### ISSUE THREAD

**Issue by Archemedes** [PaperMC/Paper#1979]
### What behaviour is expected:
An undamaged item may or may not have an nbt tag Damage which is set to 0. Absence of this tag and the actual item durability/damage being 0 would be considered equal for gameplay purposes. In rare cases a damage of zero might have the tag omitted. This affects CraftItemStack specifically (not its ItemStack.class counterpart) due to the different way in which these two classes hold their state.

### What behaviour is observed:
CraftItemStack's equal does a "dumb" recursive equals check on the NBTCompound "tag" of its handle (the NMS itemstack). It doesn't recognize the context so it will not consider the items equal.

### Steps/models to reproduce:
Items might have Damage:0 after any setDurability((short) 0); call (they will be spawned, if undamaged, without such a tag). serializing and unserializing an item through YAML (using Bukkit's built-in serialization methods) is a reliable way to strip a "Damage: 0" tag from a CraftItemStack. Serializing a CraftItemStack that IS damaged will not have this issue as the nbt tag would be conserved between (de)serialization.

Be aware that items that otherwise have no meta may not reproduce this bug because hasItemMeta explicitly checks for getDamage in those cases.

### Plugin list:
irrelevant its vanilla.

### Paper build number:
Paper version git-Paper-588 

### Anything else:
pls

**Comment by hugmanrique** [comment]
Closely related: https://github.com/PaperMC/Paper/pull/1279

This behavior was mantained by Spigot and Paper in order to not break pre-1.13 plugins:

```
hasItemMeta() will return true if ItemStack.getDamage() != 0 or it has the Damage tag or any other tag is set.
```

Check the test cases on that PR.

**Comment by Archemedes** [comment]
Thanks but yours is a different issue.
Regardless of whether or not Damage is considered part of the ItemMeta's equals check and/or evaluated for purposes of ItemStack::hasItemMeta, two identical items should be equal regardless of whether or not one explicitly specifies that it has 0 damage and the other implies it through absense of the Damage nbt tag.

**Comment by Phoenix616** [comment]
Does Vanilla Minecraft stack them together? If so they should be equal imo, if not they shouldn't.

**Comment by Archemedes** [comment]
Let me find a damageable item in vanilla Minecraft that stacks...

**Comment by Archemedes** [comment]
Fix: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/c3749a2358d93d272702a20fa6d36b08722f9ea3
Am now closing
