### ISSUE TITLE
Vanilla/Spigot: squids are spawning in solid blocks

### ISSUE THREAD

**Issue by Platinteufel** [PaperMC/Paper#199]
I don't know if you're going to fix this, but maybe someone could take a look into it. 
Issue in spigots tracker (won't fix there): https://hub.spigotmc.org/jira/browse/SPIGOT-2165

Seems like this is a vanilla bug (tested in vanilla & sandbox spigot server), but squids from squid-spawners are spawning not only in water, but also in solid blocks and die instant. Is it possible to make sure that they can only spawn in water?
![bug](https://cloud.githubusercontent.com/assets/13700636/14409646/a0c2bd2a-ff19-11e5-9194-177d8142e05e.png)

**Comment by zachbr** [comment]
As far as I can tell, Mojang didn't do this check in 1.8.x either. So they just straight up ignore any "is this location in a block" checks, because then they'd have to sort out water. It also appears to affect all water mobs, not just squids.

**Comment by zachbr** [comment]
Available in build 678 or newer
