### ISSUE TITLE
Issue when setting blocks to air/deleting blocks using a populator

### ISSUE THREAD

**Issue by KarlOfDuty** [PaperMC/Paper#1990]
Hello, I keep getting this warning when chunks are loaded where I've deleted blocks:
```yaml
[18:30:14 WARN]: Tried to load a DUMMY block entity @ BlockPosition{x=264, y=18, z=-1905} but found not block entity block Block{minecraft:air} at location
[18:30:14 WARN]: Tried to load a block entity for block Block{minecraft:air} but failed at location BlockPosition{x=264, y=18, z=-1905}
```

I assume these are the remains of some tile entity that I deleted and that I am missing some step to remove that remaining part.

Here is my current test code that just deletes all blocks in a chunk:
```java
// Deletes all blocks from the chunk
for (int x = chunkCornerX; x < chunkCornerX + 16; x++)
{
   for (int y = 0; y < world.getMaxHeight(); y++)
   {
      for (int z = chunkCornerZ; z < chunkCornerZ + 16; z++)
      {
         world.getBlockAt(x, y, z).setType(Material.AIR, false);
      }
   }
}
```

**Comment by electronicboy** [comment]
We need some level of clarification on *when* you're actually doing that, e.g. what event? Sounds like you're hitting in somewhere between loading and TEs being added to the world

**Comment by KarlOfDuty** [comment]
It is in a block populator, so when chunks are generated.

**Comment by aikar** [comment]
Isn't that kind of the opposite of what populators are for....

You should be using the chunk data provider thing instead (sorry dont know the proper term, never done world gen stuff myself)

populators are designed to go ADD (populate) more things to a chunk after its generated, not go edit it.

you should be controlling the chunks to not even create in a filled state to begin with.

**Comment by KarlOfDuty** [comment]
Yes, I know. I'm using a block populator instead because I need the default minecraft generation to run within a designated area but with a chunk generator I have to define my own world generation while having no access to the vanilla chunk generator.

The above code is just my test code for the part of the map that should be removed.

**Comment by electronicboy** [comment]
populators run before the server has actually entities into chunks, if you want to fully control the process, you'd need to be handing the chain yourself instead of diving in after the fact

**Comment by KarlOfDuty** [comment]
Are you sure about that? Because I am able to delete normal entities like generated mobs and minecarts and such in the populator.

Anyway, as far as I can tell there is no way to use vanilla world generation with ChunkGenerators. What I want is to use vanilla world generation within specific areas and have empty space around them. I don't see a way of doing that if I replace the world generation with my plugin to begin with.

**Comment by aikar** [comment]
can't you delegate to the vanilla generator? ultimately, this isn't a bug in paper, so going to close.

I recommend joining discord and discuss how to work around it in #paper-dev

**Comment by electronicboy** [comment]
Sorry, I just noticed I misread the intent of that message, I'm going to guess that that actually comes from the setType method, I'm not well versed on the code here and not had the kickstart of caffeine yet, but looks this is really just a case of "vanilla doesn't like you doing that", If the chunk should already be loaded it will have entities/TEs in there, but you can't start removing blocks like TEs in populators without having some extra cleaning up duties

**Comment by KarlOfDuty** [comment]
Yes, that was what I wanted to know about, what kind of extra cleanup can I do exactly? I haven't been able to get any info on the topic.

**Comment by KarlOfDuty** [comment]
> can't you delegate to the vanilla generator? ultimately, this isn't a bug in paper, so going to close.
> 
> I recommend joining discord and discuss how to work around it in #paper-dev

Oh and I don't think it is possible to delegate it to the vanilla generator, that was my original plan but I couldn't find a way to do so.

**Comment by electronicboy** [comment]
You'd basically need to use the lovingly unsupported NMS to remove the TE itself from the world, mojang seems to leave dummy TEs in the world which are loaded up properly in a later stage, the code for placing blocks in the world doesn't expect that you're going to remove a queued TE from the world

**Comment by davidmeusel** [comment]
is it possible to save the blocks in a file and replace them later with air (after the world-gen process)

**Comment by 3ed5d9e9-b562-431d-acc9-a4f2e47d7735** [comment]
is it possible to save the blocks in a file and replace them later with air (after the world-gen process)
