### ISSUE TITLE
ItemStack Type of 1.13-items returns Material.AIR

### ISSUE THREAD

**Issue by aurorasmiles** [PaperMC/Paper#1998]
### What behaviour is expected:
I am using a onInvClose-Event for a Custom(Sign)Inventory, the Item put into that inventory gets saved to a database if it isnt Air or Amount isnt 0.
When trying I found out the the 1.13-Items return Material.AIR from a .getType(), instead of their actual material.

### What behaviour is observed:
I printed out the ItemStack, the ItemStack.getType() and the ItemStack.getAmount(), which returned the following:
ItemStack{TRIDENT x 1}
AIR
1

If needed I can provide a code sample, but seeing as the ItemStack is correct and just not the Type I suspect this is a Paper issue

### Paper build number:
Build 1.13.2#588

**Comment by Black-Hole** [comment]
You have to specify that your plugin is compatible to 1.13 by adding this line to your plugin.yml file:
api-version: 1.13

**Comment by aurorasmiles** [comment]
damn, forgot it :C 
thx
