### ISSUE TITLE
Server Crack 1.8.8

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#1999]
### Link/paste of stack trace
https://pastebin.com/vPiV4Nmy

### Plugin list:
AccountGuard, AdvancedBan, AntiBot-Ultra, AntiCommandTab, AuctionHouse, Authme-5.6.0, BanRecipe, boosCooldowns, CasualProtector, ChestCommands, ChunkSpawnerLimiter, ClearLag, cncp, ColoredTags, CoreProtect 2.12.0, CustomCrates, CustomPayloadFixer, DiscoArmor, dsPvptop, EssentialsX 2.16.0.31, EssentialsXProtect 2.0.1 and XSpawn, EzRanksPro, FactionsUUID, HeadHunder, HolographicDisplays, IllegalStack, ItemRenamer, Jobs 3.8.2, MaddyAdvert, MC-Cron, mcMMO, Reputation, MobManager 3.0.1, MV-Core, MyCMD, NoCheatPluus, PermissionsEx 1.23.4, PlaceholderAPI 2.9.2, PlayerVaults, PlayTime, PlotSquared-Bukkit, PlugMan, ProtocolLib, PvPManager, Redclock, RedstoneClockPreventer, Residence 4.5.13.2, ShopKeepers, SilkSpawners, SkinRestorer, TitleManager, Vault, ViaVersion-2.0.1, worldedit-bukkit 6.1, worldguard 6.1.

### Actions to reproduce (if known):
Not sure. Happened on its own.

### Paper build number:
git-PaperSpigot-"4c7641d" (MC: 1.8.8) (API version 1.8.8-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
1.8.8 is loooong past its support window
