### ISSUE TITLE
Command block causing weird console warn message

### ISSUE THREAD

**Issue by Zoruaz** [PaperMC/Paper#200]
# Incompatibility (Bug)
### What behaviour is expected:

The behaviour expected is a console without spam.
### What behaviour is observed:

When using command blocks with a certain line, it spams the console with: 
[Server] WARN Unable to create attribute: Modifier name cannot be empty

That's it, nothing else (aside from the regular messages)
### Steps/models to reproduce:

Create a (chain) command block (connected to a repeating command block) with the command:
/scoreboard players tag @a[tag=!Elytra_Tier5] add Elytra_Tier5 {Inventory:[{Slot:102b,id:"minecraft:elytra",tag:{ElytraTier:5b}}]}
### Plugin list:

CoreProtect, WorldEdit, VoxelSniper, PermissionsEx, HolographicDisplays, Vault, WorldGuard, Citizens, Essentials, EssentialsChat, EssentialsSpawn, EnjinMinecraftPlugin.
(Also a custom plugin, but that doesn't seem to be a problem)
### Paper build number:

git-Paper-660

**Comment by zachbr** [comment]
Is this still happening on the latest 1.9.4 build?
