### ISSUE TITLE
[1.14] Unsafe nether portals and no connection.

### ISSUE THREAD

**Issue by KingHorse2015** [PaperMC/Paper#2008]
### What behaviour is expected:
Travel safely to the nether and back. And portals are linking.

### What behaviour is observed:
When travelling to the nether I got stuck inside the portal. Or did fall straight to lava when not moving.
When travelling to the overworld I got spawned 10-15 blocks above the ground.
On both sides a new portal was spawned, everytime I got through.

### Steps/models to reproduce:
Build a nether portal. Travel through it multiple times.

### Plugin list:
None

### Paper build number:
This server is running Paper version git-Paper-"bc024aec" (MC:1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

### Anything else:
Sorry, I am not a developer so I dont have a idea to fix the issue.

**Comment by KingHorse2015** [comment]
![2019-05-07_08 18 35](https://user-images.githubusercontent.com/15171668/57276094-cc872d00-70a0-11e9-9e6c-3675b3a90043.png)
![2019-05-07_08 19 51](https://user-images.githubusercontent.com/15171668/57276118-e4f74780-70a0-11e9-8643-bd9809c959c7.png)

**Comment by BillyGalbreath** [comment]
You know paper hasn't even released 1.14 yet, right? That's why you had to compile it yourself instead of download it.

This should really be discussed in discord instead of making a bug ticket to software that doesn't exist yet...

**Comment by KingHorse2015** [comment]
Yes, I know. That is why I made the bug report, instead of saying every where that it is broken. Yes, I complied it myself, to take a look at it.

I didn't know that I would have to discuss it in de discord first, sorry for that.

Edit: I dont have problems with being on cutting edge software. So I put this in testing environment, next to my main spigot 1.14 survival server.

**Comment by electronicboy** [comment]
Bugs on the tracker should be fine so long as they're clearly noted that they're for 1.14, beyond that, this is still a WIP in progress, expect stuff to burn, PRs encouraged

**Comment by KingHorse2015** [comment]
Is the [1.14] in the title enough? I am playing on testing to night more things, so I might run into more bugs.

**Comment by Spottedleaf** [comment]
please build & test https://github.com/Spottedleaf/Concrete-PR/tree/ver/1.14 to see if the issue is resolved

**Comment by KingHorse2015** [comment]
Issue has been resolved. Quick and great work.
