### ISSUE TITLE
Mob spawning rate goes down to almost zero after startup

### ISSUE THREAD

**Issue by burdoto** [PaperMC/Paper#2012]
### What behaviour is expected:
Consistent mob spawn rates

### What behaviour is observed:
Mob spawning goes down extremely after a couple of days. Right after a server restart it seems to be fine, but then it goes down with time.

### Steps/models to reproduce:
❌

### Plugin list:
- Chairs
- CoreProtect
- dynmap
- Essentials
- EssentialsChat
- EssentialsSpawn
- LandClaiming
- Multiverse-Core
- Multiverse-Inventories
- Multiverse-Portals
- PermissionsEx
- PhantomSpawnControl
- PlotSquared
- PluginConstructorAPI
- Vivecraft-Spigot-Extensions
- WorldEdit
- WorldEditSelectionVisualizer
- WorldGuard

### Paper build number:
`git-Paper-616`

### Anything else:
- There are some animal farms around spawn
- There are at least three afk-mobfarms
- `keep-spawn-loaded-range` is set to `1`
- If requested, I can share configuration details

**Comment by kickash32** [comment]
Can confirm, seem to be noticing the same thing, my mob farm stops working after a few days until the server restarts.

**Comment by i0xHeX** [comment]
Can confirm that also noticed that issue in past. Seems was vanilla bug and fixed. For now I don't experience that issues at least since Paper b50, mobs spawning well. I thing ticked can be closed.

**Comment by Chew** [comment]
Superseding with #2168 as there's more discussion there. Thanks for the report!
