### ISSUE TITLE
Is there no PlayerToggleFlightEvent?

### ISSUE THREAD

**Issue by kimonneuhoff** [PaperMC/Paper#2013]
Hello,
i never got any Problems with the PlayerToggleFlightEvent and i did not know what I did wrong when it doesn't worked this time. I uploaded now a Plugin which logs every event that happened into the console (Plugin name: EventDebug) and there happens nothing when I try to double jump. My question is now: Is there really no PlayerToggleFlightEvent in PaperSpigot??

**Comment by mikroskeem** [comment]
What
