### ISSUE TITLE
[Feature/Improvement] "F3+C" Reveals Player Coordinates

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#2016]
Minecraft debug log can reveal coordinates of players who teleported recently.

This issue has been in Minecraft for quite some time:
https://www.spigotmc.org/threads/f3-c-bug-reveals-coordinates-any-fixes.94981/

How to reproduce:
1) Hold F3+C and wait for client to crash
2) Open crash report
3) Player coordinates are displayed under "Forced entities".

**Comment by kashike** [comment]
I'm sorry, but we won't be adding this functionality to Paper at this time. I suggest you look into implementing this functionality in a plugin instead.
