### ISSUE TITLE
Entity Loss/Duplicate UUID

### ISSUE THREAD

**Issue by fubieslc** [PaperMC/Paper#2017]
### What behaviour is expected:
For this not to happen I guess lol, is there a way I can disable this or something so entites stop despawning?

### What behaviour is observed:
I'm getting a bunch of duplicate id errors, I tried putting the uuid-resolver setting to saferegen but it didn't help much. Lots of entities are coming up missing lately too, animals, item frames, maps in item frames etc.

PASTEBIN OF LOGS:
https://pastebin.com/AeL9uJ6R

### Steps/models to reproduce:
Not sure, this came out of nowhere in my server when I swapped from spigot to paperspigot 1.14

### Plugin list:
Citizens
CoreProtect
Essentials
ezBroadcast
Groupmanager
Imagemaps
HolographicDisplays
LWC
RandomTeleport
SimpleSit
StaffChat
TreeGravity
Vault
VoxelSniper
WorldBorder
Worldedit
Worldguard

### Paper build number:
git-Paper-11 (MC: 1.14)

**Comment by VADemon** [comment]
`duplicate-uuid-resolver` set to "warn" or decrease `duplicate-uuid-saferegen-delete-range` (from [here](https://github.com/PaperMC/Paper/blob/fb25dc17c62acce335346d5e96899257ae7230c7/Spigot-Server-Patches/0293-Duplicate-UUID-Resolve-Option.patch) )

Saferegen is the default setting

See #1223 for info

**Comment by electronicboy** [comment]
That patch was dropped in 1.14, however needs to be restored;

This is still an issue in craftbukkit, just the warnings are actually disabled making it seem like this isn't actually occurring

**Comment by Black-Hole** [comment]
Should be fixed in 1.14.2: https://bugs.mojang.com/browse/MC-150170?focusedCommentId=547891&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-547891
