### ISSUE TITLE
[1.14]Chest close sound not playing

### ISSUE THREAD

**Issue by KingHorse2015** [PaperMC/Paper#2019]
### What behaviour is expected:
I expect to hear the chest close sound, on chest closing.
### What behaviour is observed:
Chests don't make sounds on closing.
Animation is played normally

### Steps/models to reproduce:
Place chest, open and close it.

### Plugin list:
DiscordSRV
Minecraft Hook 2.6
Verrified Commands (Plugin for Minecraft Hook)
Discord-Bot-api for Minecraft Hook
Coreprotect

### Paper build number:
 This server is running Paper version git-Paper-"e0d8e0dd" (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

### Anything else:
Send player chest close sound. 
In spigot it works fine. (Same world/plugins)

**Comment by Spottedleaf** [comment]
confirmed

**Comment by electronicboy** [comment]
Fixed in build 13+
