### ISSUE TITLE
Remove ITickAble from more tile entities.

### ISSUE THREAD

**Issue by Shevchik** [PaperMC/Paper#202]
# Suggestion

Both TileEntitySkull and TileEntityEnchantmentTable tick methods don't do anything useful on server side. This may be the same for other tileentities.

**Comment by aikar** [comment]
enchant table still does some stuff that rather not take risks on. too much random code to be confident on that affects animations, and they aren't spammed enough to be worth the effort.

**Comment by Shevchik** [comment]
Variables on tile entity skull are not used outside the tick method. The same if for enchantment table, protocolsupport overrides enchant table and has empty tick method, and i nevrr had a problem with.

**Comment by Shevchik** [comment]
Also maybe we should do something with beacon too. It has absolutely useless beacon color tracker that wirks only on client side. Also it loads chunks when checking structure which is bad too.
