### ISSUE TITLE
Mobs living 

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#2025]
**Is your feature request related to a problem? Please describe.**
Hey. I had a villager which was poisoined by zombie, I closed him into 1 of villagers room to let he don't poise them too. When I was doing potion to heal him, he just disappeared. The room had only 2 beds, 2 craftings and 1 torch. I locked him by place wood before the doors to let he don't leave and he just left me without info. When I walked into mine I heard voice of villager zombie so I started search him mining blocks but my pickaxe has ended and I needed to return home and take another one and again happened something like this...

**Describe the solution you'd like**
A option to let mobs stay a life when player leave a region or chunks. 

**Describe alternatives you've considered**
Option in paper.yml "keepmobsalife" or something like this. To let mobs don't disappear when player run somewhere.... If this is a cheat into survival then *I didn't wrote this thread*. 

**Additional context**

**Comment by electronicboy** [comment]
This is plugin territory
