### ISSUE TITLE
Add API method: setMaxPlayers()

### ISSUE THREAD

**Issue by TheLuca98** [PaperMC/Paper#2028]
**Is your feature request related to a problem? Please describe.**
There's currently no official API to dynamically change the player limit for the server (the actual limit, not just the number shown in the MOTD).

**Describe the solution you'd like**
Given the existence of `org.bukkit.Server#getMaxPlayers()`, I think the most obvious solution would simply be to add a setter in the same class, i.e. `org.bukkit.Server#setMaxPlayers(int)` with its own static alias in `org.bukkit.Bukkit`.

**Describe alternatives you've considered**
- Use reflection to modify a private NMS field
- Use the event system to change the MOTD and the login flow

Both solutions are what I would consider a hacky workaround.

**Additional context**
_Not applicable_

**Comment by MiniDigger** [comment]
Maybe a more general API to provide access to the server properties in a writable manner would be more appropriate?

**Comment by TheLuca98** [comment]
@MiniDigger Sure. It's also worth noting that there are not many properties that would need to be implemented, given that most of them are world-related and are thus are already handled by `World`.

**Comment by brayjamin** [comment]
@MiniDigger I've been looking for what you're saying forever..
 An API for the server properties would allow for essentially dynamically updating properties, without hacky workarounds.
 Going to suggest this when I get a chance! :P

**Comment by Michael-Ziluck** [comment]
Where would be the best place to put an API that handles the server properties?

I think the best way to handle it is the following:
1. Create a class called `ServerProperties` (open to name suggestions) in the same package as `Server`.
2. Create a final property within `Server` that is a reference to an instance of the `ServerProperties` class. In that class, there will essentially just be a bunch of getters and setters.
3. Switch all references to any server properties to the ones in the `ServerProperties` class.

There are three things I'd like input on:
1. How should updating `server.properties` on the file system work?
    - When an option is changed
    - When the server shuts down
2. Should servers have the ability to disable saving the `server.properties` file, and if so should it be opt-in or opt-out?
3. Would it actually be beneficial to go through with step 3 above, or would step 1 and 2 be sufficient?

**Comment by willies952002** [comment]
> 1. How should updating `server.properties` on the file system work?
>    * When an option is changed
>    * When the server shuts down

Personally, I would say on server shut down - this will reduce file i/o while the server is running, and also minimizing the possibility for an edge-case CME. However, I'm not sure if the file would be saved if a crash was to occur, so possibly having a method to manually save it to disk would be a good idea.
> 2. Should servers have the ability to disable saving the `server.properties` file, and if so should it be opt-in or opt-out?

I believe it should be opt-in, like most of the other Paper features.
> 3. Would it actually be beneficial to go through with step 3 above, or would step 1 and 2 be sufficient?

This would effectively be the implementation of the new API, making it a required step.

**Comment by Michael-Ziluck** [comment]
After looking into it more, I think it probably would be best not to have a `ServerProperties` class. All of the configuration options exist in the class `net.minecraft.server.DedicatedServerProperties`. In that class, all of the variables are public and final. Creating an entire API dedicated to editing those properties could have serious side effects. I'd still like to implement this feature request if it is accepted without the whole API.

Thoughts, @willies952002?

**Comment by Brokkonaut** [comment]
I don't see a reason for this. The second "workaround" (Use the event system to change the MOTD and the login flow) is widely used, allows to handle all of that and even more like having different limits for different players (for example extra team/vip slots). So why add another api that can only handle parts of an existing api?

**Comment by kashike** [comment]
#4178 added this.
