### ISSUE TITLE
NetworkManager: unneded packet queue.

### ISSUE THREAD

**Issue by Shevchik** [PaperMC/Paper#203]
# Suggestion

NetworkManager has 2 unneded fields: "i", "j".
They are used for packet queuing while channel is not open. They only case when is happens is after channel disconnect. So this queue is useless, and just slows down networkmanager tick and sendPacket. There is even an rwlock for that queue, which is totally not needed, because queue uses CLQ.

Those fields should be removed.

**Comment by AlfieC** [comment]
I tested this - server works fine without them (and faster!). Will PR the changes in the morning.

**Comment by zachbr** [comment]
:+1:

**Comment by AlfieC** [comment]
@Zbob750 any specific tests I should do? All I tested was logging in/out running around

**Comment by zachbr** [comment]
This shouldn't really have any side effects, I remember looking at these fields a while back. They just don't need to exist. I can't imagine there's anything non-NMS trying to hook into them either so... yeah should e fine.

**Comment by AlfieC** [comment]
One last question: How do you want to handle empty methods? There's `public void m()` but it has stuff that only processes the network queue stuff - should I remove it entirely or leave it in case it's referenced anywhere else?

**Comment by zachbr** [comment]
I'd say just leave them empty.
Edit: Or just comment the contents so they're not empty in source, but are still functionally empty.

**Comment by Shevchik** [comment]
Fixed by 324acd64b4788027e49d579a0b263500a20636c8
