### ISSUE TITLE
Paper 1.12.2 crash

### ISSUE THREAD

**Issue by Roshanxy** [PaperMC/Paper#2033]
https://pastebin.com/f9KY7Y0N

[22:36:59] [Server thread/INFO]: This server is running Paper version git-Paper-1613 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
--
[22:36:59] [Server thread/INFO]: You are running the latest version

What happen before this?
No clue, I was sitting in my house when I got a time out all of the sudden

If you want more info, hmu

**Comment by KisaragiEffective** [comment]
now 1.12.2 didn't supported :thinking:

**Comment by Roshanxy** [comment]
@Kisaragi what do you mean?

**Comment by zachbr** [comment]
Your server lagged out while ticking a Bat. The stacktrace from the initial check is different than the one from the final all-threads-dump, so it looks like your server is just running really behind.

There's no way for me to know if this was an isolated incident and we just happened to get caught on this one bat as it was going through the tick or if you have a lot of bats doing horrible things. Just keep an eye on it and see what happens.
