### ISSUE TITLE
Paper 1.14.1 Crash (Java 11)

### ISSUE THREAD

**Issue by AloneSpace** [PaperMC/Paper#2035]
### Link/paste of stack trace

https://pastebin.com/WPCiitWV

### Plugin list:
___A list of your plugins___

### Paper build number:
git-Paper-20 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Update your server, if this continues please paste the *full* log somewhere, there is additional context missing.
