### ISSUE TITLE
Possibility of backporting "prevent-moving-into-unloaded-chunks" to 1.12 paper?

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2036]
Would it be possible to add the 'prevent-moving-into-unloaded-chunks' to 1.12 paper?

**Comment by waifubeater360** [comment]
braaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaap

**Comment by zachbr** [comment]
1.12.2 is feature frozen, so no.
