### ISSUE TITLE
Suggestion - growth-speed-modifier for chorus plants

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#204]
# Suggestion

I would love to see an option to modify the growth-speed of the new chorus plants. I'm not sure if Spigot wants to implement it so I suggest it to the Paper project to allow us a more specific modification of the growth-speed.

**Comment by kickash32** [comment]
This is difficult to do as the Chorus Flower grows as soon as it is ticked. 
One option I was considering is that we could have a multiplier from which we can use in a RNG to determine if a ticked Chorus Flower should randomly ignore that tick (if the multiplier is lower than 1) and also if the newly grown Chorus Flower should get ticked again (if the multiplier is higher than 1).
