### ISSUE TITLE
Inventory#getName() is gone.

### ISSUE THREAD

**Issue by RaymondTracer** [PaperMC/Paper#2040]
I assume Bukkit, CB or Spigot might've removed it, can we get this method back?

**Comment by GMatrixGames** [comment]
Although it's not recommended by any means to use that method, I think for plugin compat. until devs update their plugins, it should be added back.

But it will send a quite annoying message to the console on plugin load.

**Comment by RaymondTracer** [comment]
>Although it's not recommended by any means to use that method

Please excuse my ignorance but what's the alternative?

**Comment by BillyGalbreath** [comment]
InventoryView#getTitle()

Remember, inventories don't have names. Never have.. it's the view that has the name.

![](https://proxy.spigotmc.org/e87c05568d3a7f304cb937571bed0c77513d23fa?url=https%3A%2F%2Fi.imgur.com%2FOlwMr55.png)

**Comment by RaymondTracer** [comment]
Thank you for the explanation, you learn something new every day.
