### ISSUE TITLE
[request] add CommandBlock#getMode, #isPowerRequired, #getVector

### ISSUE THREAD

**Issue by KisaragiEffective** [PaperMC/Paper#2041]
**Is your feature request related to a problem? Please describe.**
I feel api is too weak features to access command block... :(

**Describe the solution you'd like**
```java
public /* Some enum that commandblock's mode in IMPLUSE, CHAIN, REPEAT */ getMode() {
// stuff
}

public boolean isPowerRequired() {
// stuff
}

public BlockFace /* maybe not comfortable */ getVector {}
```

**Describe alternatives you've considered**
One of them is touch to nms (it has show mode and powerRequired), but they obsfucated method and changed method name per major release, its uneffective and can break compatibility easily. another is checking the byte of it (in 1.12.2), but the 1.13 and above has removed byte-mecanical, so i can't either. If this added, we can remove useless version checks.

**Additional context**
*None*

**Comment by Phoenix616** [comment]
The mode is accessible via the material enum ;) `COMMAND_BLOCK`, `CHAIN_COMMAND_BLOCK` and `REPEATING_COMMAND_BLOCK` , the direction via the [BlockData](https://papermc.io/javadocs/paper/1.13/org/bukkit/block/data/type/CommandBlock.html) (CommandBlock extends Directional) and it also has the `isConditional`/`setConditional` check

**Comment by KisaragiEffective** [comment]
I'm stacked at like 1.12
thx for tell me!
