### ISSUE TITLE
Chunk load lag

### ISSUE THREAD

**Issue by videosambo** [PaperMC/Paper#2042]
###  Timings or Profile link:
Before restart:
[https://timings.aikar.co/?id=a067a2363b404dc4a2d84188bc21dc15](https://timings.aikar.co/?id=a067a2363b404dc4a2d84188bc21dc15)
After restart:
[https://timings.aikar.co/?id=bf85b1fc22e348deaefc9071975f5b38](https://timings.aikar.co/?id=bf85b1fc22e348deaefc9071975f5b38)

### Description of issue:
So server starts lagging when you walk some time, I have dynmap but it has loaded whole map already and its pause none while server has players

### Plugin list:
coreprotect, dynmap, plugman

### bukkit.yml, spigot.yml, paper.yml, server.properties
spigot.yml: [https://pastebin.com/dCurCv9p](https://pastebin.com/dCurCv9p)
bukkit.yml: [https://pastebin.com/NJpTwBc8](https://pastebin.com/NJpTwBc8)
paper.yml: [https://pastebin.com/R51QkX3B](https://pastebin.com/R51QkX3B)

### Other helpful links
Server website: [http://simpelecraft.tk/](http://simpelecraft.tk/)
Dynmap: [http://simpelecraft.tk:8123/](http://simpelecraft.tk:8123/)

### Paper build number:
git-Paper-20 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

PS. I accidentally put this first without information

**Comment by electronicboy** [comment]
Update
