### ISSUE TITLE
Expose net.minecraft.server.Block#getStepSound

### ISSUE THREAD

**Issue by Parozzz** [PaperMC/Paper#2045]
As for now, there is no easy way to get block sounds. Since vanilla stores them internally inside SoundEffectType class, it would be useful to create an API for them.

**Comment by jacobsandersen** [comment]
#2097 should help with this. It adds a `BlockSoundGroup` type into Paper which is accessible on `org.bukkit.block.Block` via `getSoundGroup()`. The new type gives you the break, step. place, hit, and fall sounds for a block as registered in the NMS `SoundEffectType` class.

**Comment by Parozzz** [comment]
I am following the pr via email, thank you for implementing this and your time

**Comment by jacobsandersen** [comment]
@zachbr @kashike Closeable
