### ISSUE TITLE
Exception while updating neighbours server crash

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#2047]
### Link/paste of stack trace

https://pastebin.com/pb2a7K1R

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
Plugins (92): AdditionsAPI, AdminVedelem, antiRedstoneClock, AnvilRestrict, AreaShop, BuntetesLogolo, ChatControl, ChestCommands, ChestShop, ChestShopNotifier*, Citizens, CitizensCMD, CombatLogX, CommandHook, CommandSigns, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus*, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, EnderContainers, EntityDetection, EpicHeads, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, GriefPrevention, GriefPreventionFlags, HolographicDisplays, HonapStaffja, HungerGames, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, MobHeads, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoSpawnerChange, NoteBlockAPI, OpenInv*, Paintball, PickupSpawners, PlaceholderAPI*, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaAdditions, RedstoneClockDetector*, RestrictedCreative, Ridables, SignEdit*, StaffChat, StaffTime, Stats, SzulinapiTuzijatek, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, Votifier, VotingPlugin, VoxelSniper*, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
16.05 22:50:20 [Server] INFO This server is running Paper version git-Paper-23 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Something is modifying a list asynchronously. It could be yet another bug in 1.14 or it could be a plugin, there is no way for me to know.
Please re-test without 90 plugins.

**Comment by andris155** [comment]
Latest Paper version fixed this.
