### ISSUE TITLE
[Bug] No dragon appear at the end with disabled legacy dragon scan

### ISSUE THREAD

**Issue by i0xHeX** [PaperMC/Paper#2053]
Expected:
- Dragon appear at the end

Observed:
- No dragon appear at the end

Reproducing:
- Set `scan-for-legacy-ender-dragon: false`
- Remove existing end map if you visited it (world_the_end)
- Join the end (via portal for example)

Plugin list: [no plugins]

Paper build number: 26 (MC: 1.14.1)

With `scan-for-legacy-ender-dragon: true` dragon will appear.

**Comment by BillyGalbreath** [comment]
This is intentional by design. That scan is what determines if the battle manager should spawn a dragon or not. If you disable that check, it just doesn't even try.

See #941 for details on why I implemented this in #1167
