### ISSUE TITLE
Crash when entering a chunk

### ISSUE THREAD

**Issue by Taskeren** [PaperMC/Paper#2057]
### Link/paste of stack trace
https://paste.ubuntu.com/p/Whwf2hDQwN/

### Plugin list:
- DailyRewards
- EssentialsX
- EssentialsXChat
- EssentialsGeoIP
- EssentialsXGroupManager
- EssentialsXProtect
- EssentialsXSpawn
- GroupManager
- HolographicDisplays
- HolographicDisplaysExstension
- Multiverse-Core
- Parkour
- PlayerHeads
- ProtocolLib
- QuickShop-Reremake
- Residence
- Vault
- Whitelist+
- WorldEdit

### Actions to reproduce (if known):
It may be caused when I enter a chunk which is not constructed.

### Paper build number:
git-Paper-26

**Comment by Taskeren** [comment]
Same as #2052

**Comment by Blazzike** [comment]
Hastebin link expired @nitu2003's crash report: https://paste.ubuntu.com/p/Whwf2hDQwN/
