### ISSUE TITLE
Slow chunk loading

### ISSUE THREAD

**Issue by Cerexus** [PaperMC/Paper#2058]
###  Timings or Profile link:
https://timings.aikar.co/?id=63a88138a4a841e888f7f1ed778febb8

### Description of issue:
Extremly slow Chunkloading. 90% off the chunks need up to 20 Seconds to load sometimes.
(Multiworlds generated all in 1.14).

### Paper build number:
Paper 26

**Comment by reececal** [comment]
Are you using Multiverse?

**Comment by HyperlyBola** [comment]
> Are you using Multiverse?

I've had this same problem even without using multiverse, I believe it's paper itself, and just 1.14 being bad

**Comment by k9lego** [comment]
> 
> 
> > Are you using Multiverse?
> 
> I've had this same problem even without using multiverse, I believe it's paper itself, and just 1.14 being bad

1.14's chunk loading is awful. Yell at Mojang, not Paper ;)

**Comment by xacrimon** [comment]
Yup its just 1.14 doing it's thing. Seems to be fixed in 1.14.2 vanilla.

**Comment by Cerexus** [comment]
On normal Spigot i dont have any Chunk Issues ^^

Acrimon <notifications@github.com> schrieb am So., 19. Mai 2019, 10:18:

**Comment by electronicboy** [comment]
Comparable spigot timings? comparable spark profiling?
I very little interest in attempting to drill down on open-ended issues, especially given the state of 1.14 in general

**Comment by Cerexus** [comment]
The Timings are nearly similar..  The only thing is that it sometimes take up to minutes to load chunks (the chunks are already generated) after a teleport..  i dont use Multiverse i have my own Plugin that just loads a world and teleport me in, not more.

**Comment by minecraft7net** [comment]
i had similar experience yesterday with paper 1.14.1 build 33 - tested switch paper <-> spigot on spigot less problems but players still tell me that its not perfect. placing block and destroy blocks.
"..."
you have a problem with writing blocks
little blocks still appear and disappear less but still
I do not know what you have changed but digging is a murder you cover with the right one or you start to smoke while standing on cobble
"..."

**Comment by electronicboy** [comment]
33 has a known potential issue that was fixed in 34, this issue is likely covered by the latest build, I'd suggest updating

Closing this issue, if there are still concerns vs spigot (and not 1.14 in general), please provide profiler snapshots comparing the two, many of us don't have ways to replicate these environments and need people to produce useful reports.
