### ISSUE TITLE
chunk loading cause server stop

### ISSUE THREAD

**Issue by newbie029** [PaperMC/Paper#2059]
### Plugin list:
Plugins (24): AuthMe, BossShopPro, BungeeTabListPlus*, CoreProtect, CursedCore*, CursedVIP*, DeluxeChat, Essentials, EssentialsProtect, EssentialsSpawn, GriefPrevention, IllegalStack, LuckPerms, Multiverse-Core, MyCommand, OreReplacerPlugin, PlaceholderAPI*, ProtocolLib*, SkinsRestorer, TradePlus, UltimateTimber, Vault, WorldEdit, WorldGuard

### Paper build number:
git-Paper-20 (MC: 1.14.1)

### Anything else:
Heres the log https://pastebin.com/kWx4CqyS

**Comment by electronicboy** [comment]
Duplicate of #2052, also, you're running an outdated build
