### ISSUE TITLE
Suggestion - View distance

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#206]
Can you make a option in paper where the view distance is changed on playercount? This would be a amazing feature to have, For my survival server I refuse to turn it down from 8, But if there is 40 people on then I Wouldn't mind dropping it to 5 to help boost performance.

Add a option to paper.yml:

Live View Distance:
   player-limits: ['15:8', '20:7', '30:6', '40:5', '50:4']

**Comment by zachbr** [comment]
We provide an API for getting the TPS as well as setting per-player view distance.

All of the tools are there for you
