### ISSUE TITLE
Too many channels registered!

### ISSUE THREAD

**Issue by Zilacon** [PaperMC/Paper#2063]
So im aware this has been addressed here https://github.com/PaperMC/Paper/commit/d09826faf2ceb55f6e1aea491379f228102799bb

But it still seems to be a problem for me. Where do i define this "DISABLE_CHANNEL_LIMIT"?
This is one of the errors im getting.
![Screenshot_151](https://user-images.githubusercontent.com/3002248/58106992-dda26480-7b9d-11e9-91c3-ff19adf63c60.png)

**Comment by BillyGalbreath** [comment]
It's a system property. This mean it's added using Java flags in your start script.

Add this before -jar

`-Dpaper.disableChannelLimit=true`

**Comment by Zilacon** [comment]
Yeah but this is not possible when the server is on a mc server host. Atleast not mine.

**Comment by Zilacon** [comment]
Is there some way this could be set as a configuration option in paper.yml?

**Comment by BillyGalbreath** [comment]
Get a better host then. Startup flags are essential to running a Minecraft server.

**Comment by Zilacon** [comment]
Oof
