### ISSUE TITLE
Remove all misuses of the @NotNull annotation that cause Maven tests to fail

### ISSUE THREAD

**Issue by Michael-Ziluck** [PaperMC/Paper#2064]
Currently, Bukkit and Spigot seriously misuse the NotNull annotation. It would be nice if these could be removed at some point.

**Significant clarification in my [comment](https://github.com/PaperMC/Paper/issues/2064#issuecomment-494846445) below!**

**Comment by MiniDigger** [comment]
any examples of misuse? 
and how do those make your tests fail? do you violate the contracts that those methods define?

**Comment by aikar** [comment]
We already did a few months ago (well annoying uses of Nullable)... You're going to need to declare each you believe is wrong.

**Comment by Michael-Ziluck** [comment]
Oops, sorry, clarification: They cause Maven tests to fail when the project is compiled from within IDEs that add runtime assertions for NotNull annotated methods and parameters.

One example of tests failing when the project is compiled within an IDE is in `ValidatingPromptTest`. There is code that says the following:
```java
TestBooleanPrompt prompt = new TestBooleanPrompt();
assertTrue(prompt.isInputValid(null, "true"));
```
TestBooleanPrompt extends BooleanPrompt, and in BooleanPrompt there is the following code:
```java
@Override
protected boolean isInputValid(@NotNull ConversationContext context, @NotNull String input) {
    String[] accepted = {/* Apache values: */"true", "false", "on", "off", "yes", "no",/* Additional values: */ "y", "n", "1", "0", "right", "wrong", "correct", "incorrect", "valid", "invalid"};
    return ArrayUtils.contains(accepted, input.toLowerCase());
}
```
The test calls the method `isInputValid` which doesn't permit null values, causing the test to always fail when those annotations are converted to assertions.

Links to the code on Spigot:
- https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/conversations/BooleanPrompt.java
- https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/test/java/org/bukkit/conversations/ValidatingPromptTest.java

**Comment by aikar** [comment]
Then your report isn't about the use of the not null annotation, it's that there is a bad test that tests an illegal input.

**Comment by Michael-Ziluck** [comment]
That would be a better way to resolve the issue come to think of it, yes. A better test would be to test an empty string rather than null since command arguments and parsed strings will never be null, but they could be empty.

**Comment by aikar** [comment]
That null goes to the context, not the input.
