### ISSUE TITLE
Certain Commands not working in loaded chunks

### ISSUE THREAD

**Issue by ghall2499** [PaperMC/Paper#2068]
### What behaviour is expected:
___What you expected to see___
Trying to use /data merge entity in a chunk to rotate an armor stand.
### What behaviour is observed:
___What you actually saw___
Armor stand isnt turning until i leave the chunk and reload the chunk.
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
https://www.dropbox.com/s/65a2bj5vayfd3qh/2019-05-22_19-38-12.mp4?dl=0
### Plugin list:
___A list of your plugins___
EasyBackup
Essentials
EssentialsAntiBuild
EssentialsChat
EssentialsProtect
EssentialsSpawn
FastAsyncWorldEdit
LuckPerms
Multiverse-Core
Multiverse-Inventories
OpenAudioMc
Vault
WorldEdit
WorldGuard
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-39
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Chew** [comment]
Considering this is 1.14 and no other discussion or other reports have occurred, this has likely been fixed and might've been a cause of a plugin. If you are still experiencing this issue on a supported version, don't hesitate to open a new issue. Thanks for the report!
