### ISSUE TITLE
Server thread dump

### ISSUE THREAD

**Issue by CroatiaGM177** [PaperMC/Paper#2070]
I dont have any plugins.

[ERROR] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-37 (MC: 1.14.1) ---

[ERROR] The server has not responded for 10 seconds! Creating thread dump

[ERROR] ------------------------------

[ERROR] Server thread dump (Look for plugins here before reporting to Paper!):

[ERROR] ------------------------------

[ERROR] Current Thread: Server thread

[ERROR] PID: 32 | Suspended: false | Native: false | State: RUNNABLE

[ERROR] Stack:

[ERROR] net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:499)

[ERROR] net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115)

[ERROR] net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:96)

[ERROR] net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:306)

[ERROR] net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(IWorldReader.java:95)

[ERROR] net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:301)

[ERROR] net.minecraft.server.v1_14_R1.World.getType(World.java:658)

[ERROR] net.minecraft.server.v1_14_R1.PortalTravelAgent.a(PortalTravelAgent.java:80)

[ERROR] net.minecraft.server.v1_14_R1.Entity.teleportTo(Entity.java:2564)

[ERROR] net.minecraft.server.v1_14_R1.Entity.a(Entity.java:2511)

[ERROR] net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2162)

[ERROR] net.minecraft.server.v1_14_R1.Entity.postTick(Entity.java:372)

[ERROR] net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:580)

[ERROR] net.minecraft.server.v1_14_R1.WorldServer$$Lambda$2640.000000006C7A92A0.accept(Unknown Source)

[ERROR] net.minecraft.server.v1_14_R1.World.a(World.java:880)

[ERROR] net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)

[ERROR] net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1165)

[ERROR] net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)

[ERROR] net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1048)

[ERROR] net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:892)

[ERROR] java.lang.Thread.run(Thread.java:813)

[ERROR] ------------------------------

[ERROR] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---

[ERROR] ------------------------------

[ERROR] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-37 (MC: 1.14.1) ---

[ERROR] The server has not responded for 15 seconds! Creating thread dump

[ERROR] ------------------------------

[ERROR] Server thread dump (Look for plugins here before reporting to Paper!):

[ERROR] ------------------------------

[ERROR] Current Thread: Server thread

[ERROR] PID: 32 | Suspended: false | Native: true | State: RUNNABLE

[ERROR] Stack:

[ERROR] sun.misc.Unsafe.park(Native Method)

[ERROR] java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)

[ERROR] net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:116)

[ERROR] net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:96)

[ERROR] net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:306)

[ERROR] net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(IWorldReader.java:95)

[ERROR] net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:301)

[ERROR] net.minecraft.server.v1_14_R1.World.getType(World.java:658)

[ERROR] net.minecraft.server.v1_14_R1.PortalTravelAgent.a(PortalTravelAgent.java:80)

[ERROR] net.minecraft.server.v1_14_R1.Entity.teleportTo(Entity.java:2564)

[ERROR] net.minecraft.server.v1_14_R1.Entity.a(Entity.java:2511)

[ERROR] net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2162)

[ERROR] net.minecraft.server.v1_14_R1.Entity.postTick(Entity.java:372)

[ERROR] net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:580)

[ERROR] net.minecraft.server.v1_14_R1.WorldServer$$Lambda$2640.000000006C7A92A0.accept(Unknown Source)

[ERROR] net.minecraft.server.v1_14_R1.World.a(World.java:880)

[ERROR] net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)

[ERROR] net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1165)

[ERROR] net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)

[ERROR] net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1048)

[ERROR] net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:892)

[ERROR] java.lang.Thread.run(Thread.java:813)

[ERROR] ------------------------------

[ERROR] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---

[ERROR] ------------------------------

**Comment by astei** [comment]
`--- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-37 (MC: 1.14.1) ---`

It appears as if your server is running behind on chunk generation.

**Comment by CroatiaGM177** [comment]
What can i do it to fix that problem ?

**Comment by astei** [comment]
Get stronger hardware, and stop using bad hosting.

**Comment by CroatiaGM177** [comment]
Can you suggest a host? i am currently using server.pro 4gb?

**Comment by astei** [comment]
Practically any host is going to be better than Server.pro. I can't give any shared hosting recommendations because I use VPSes and dedicated servers.

**Comment by electronicboy** [comment]
I'd suggest taking discussions to IRC/discord, this system sends out emails on every reply to anybody sub'd to the project

As for the issue, 1.14.x chunk loading/generation performance is pretty harsh, we're working on things to help address it, but this is just one of the inherent issues you opted to deal with when you jumped to 1.14 given its current state
