### ISSUE TITLE
Huge error messages + server crashes

### ISSUE THREAD

**Issue by goldrat1** [PaperMC/Paper#2071]
### Link/paste of stack trace
https://pastebin.com/6KyRwuSi
**Server thread dump starts at Line 474**
    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
AntiCreeper, CoreProtect, CS-CoreLib, CustomCrafting, DiscordBotAPI, DiscordChatWM, DropEdit2, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, GroupManager, ImageMaps, KeepChunks, mcMMO, PlugMan, Slimefun, Vault, WolfyUtilities, WorldEdit

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Uhh, starting the server? I think it has something to do with portals/teleporting/changing worlds, but can't be sure.
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-39 (MC: 1.14.1) (Latest version)

Error emsag spikes every few minutes, eventually led to a 
Server's RAM usage is constantly going upwards, don't know if that's just the host or the amount of players, but it might have something to do with these error messages.
Can't seem to find any plugins in the crash log.

**Comment by Spottedleaf** [comment]
loading chunks after portaling brought your server down
