### ISSUE TITLE
friend join console spam

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#2076]
### What behaviour is expected:
When friend join I get spam in console.

### What behaviour is observed:
Spam in console 

### Steps/models to reproduce:
https://pastebin.com/yJ0Xhgf1

### Plugin list:
Plugins (29): AutoRespawnPlus, Citizens, ClearLag*, CommandSigns, Essentials, EssentialsChat, EssentialsGeoIP, HolographicDisplays, InvRestore2*, Multiverse-Core, Multiverse-Inventories*, Multiverse-NetherPortals, PermissionsEx*, PixelPrinter, PlaceholderAPI*, PluginConstructorAPI, PlugMan*, RFChairs, ServerRestorer, SkQuery*, Skript, skript-mirror*, TopLite*, TuSKe*, Vault, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
This server is running Paper version git-Paper-42 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
[14:55:37 INFO]: Previous version: git-Paper-41 (MC: 1.14.1)
[14:55:37 INFO]: Checking version, please wait...
[14:55:37 INFO]: You are running the latest version

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by zachbr** [comment]
General 1.14 chunk performance issue, closing.
