### ISSUE TITLE
PersistentDataContainer does not remember values on players

### ISSUE THREAD

**Issue by TauCu** [PaperMC/Paper#2078]
### What behaviour is expected:
Persistent metadata being persisted.

### What behaviour is observed:
The values being removed when the player leaves the server.

### Steps/models to reproduce:
https://pastebin.com/qeRvTHPf

### Plugin list:
TestPlugin

### Paper build number:
git-Paper-39

### Anything else:
Spigot fixed this issue on the 25th, However paper still has this issue, and it can be rather destructive for plugins that use this to store data for players.

However I'm not sure what patch actually fixed it.

**Comment by electronicboy** [comment]
I was mid upstream merge before, just not finish it yet, but it's worth noting that you're not on the latest build either
