### ISSUE TITLE
ChunkMapDistance CME

### ISSUE THREAD

**Issue by tomkimberlin** [PaperMC/Paper#2084]
### Link/paste of stack trace

https://pastebin.com/F4wmM4iJ

### Plugin list:

BettingGames, ChatControl, ChestProtect, CMI, Confiscate, CoreProtect, CraftingStore, CropChecker, DeathChestPro, DiscordSRV, GadgetsMenu, GCore, IllegalStack, Lands, LiteBansGUI*, mcMMO, ProtocolLib*, PvPToggle, RPGMoney, ServerRestart, SmoothSleep, Spartan, TradePlus, UltraPermissions, Vault*, Votifier, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, YourAuction

### Actions to reproduce (if known):

Randomly occurs. Typically near the time a player teleports (/spawn, /tpa, etc.).

### Paper build number:

Paper(43) 1.14.1-R0.1-SNAPSHOT

**Comment by electronicboy** [comment]
There should be an error in the logs before that

**Comment by tomkimberlin** [comment]
My bad I was copying from console and missed some of the trace.

https://pastebin.com/zEMdemdp

**Comment by tomkimberlin** [comment]
https://pastebin.com/BYKb38Hw

Here is another trace which just happened on latest Paper.

**Comment by tomkimberlin** [comment]
[log.txt](https://github.com/PaperMC/Paper/files/3225244/log.txt)

I'm not sure how helpful extra logs are but here is another with the 1.14.2 build of Paper.

**Comment by kaanakduman** [comment]
I just experienced the same issue with Paper 51
https://hasteb.in/ucujoziw.cs

**Comment by electronicboy** [comment]
as a note, timing stack corruption is generally caused by other things throwing exceptions, major one here happens to be `ChunkMapDistance`, I've collected some data and will try to look at it when get to it, appears to be down to vanillas chunk loading system

**Comment by tomkimberlin** [comment]
Gotcha. Thanks for looking into it.

**Comment by lukaskabc** [comment]
Simmilar problem here:
https://pastebin.com/sxagvsHP

and after any command i see in chat:
Cannot send chat message

(paper 1.14.2 #53)

**Comment by aikar** [comment]
The timings message is unimportant and not relevant. the real error here is the CME. disregard anything about the timings message.

**Comment by tomkimberlin** [comment]
Okay. I've attached another log from Paper-53. Seems to be happening much less often and when it does it won't spam it multiple times.
[log.txt](https://github.com/PaperMC/Paper/files/3229402/log.txt)

**Comment by creator3** [comment]
We've been having this issue as well, and we're not using Paper. It appears to be a Spigot issue. I was able to set everything up to detect the concurrent modification a little earlier and got a pretty useful stack trace. https://pastebin.com/LCSkzZNP

It seems to have something to do with loading chunks in the ChunkLoadEvent. Notice the ChunkMapDistance.a call on line 26 and the following call to Iterable.forEach() (this.k.forEach). At the top of the trace, ChunkMapDistance.a is called again, which finishes by calling this.k.clear()

**Comment by Spottedleaf** [comment]
We were aware that loading chunks in the event caused the issue

**Comment by lagnat** [comment]
I spent a bunch of time tracking down the root cause of the CME.  Note that I don't run a paper server but I came across this ticket during my research and I felt that it would be useful to report my findings here.

https://hub.spigotmc.org/jira/browse/SPIGOT-5116?focusedCommentId=34007&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-34007

**Comment by electronicboy** [comment]
This is actually already fixed here, I was just busy and forgot to go close the ticket properly, https://github.com/PaperMC/Paper/blob/ver/1.14/Spigot-Server-Patches/0395-ChunkMapDistance-CME.patch
