### ISSUE TITLE
async-chunks

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#2087]
1.14 is kinda impossible to play once you get above 30+ players without async-chunks, When will this be added back :(

**Comment by jordanwilliams1** [comment]
@electronicboy Why was it closed? Is it never being added back?

**Comment by electronicboy** [comment]
It was closed because the issue tracker is for issues/bugs with the software, not for questions concerning ETAs and other things we've already given an answer to. async chunks will come back when it's ready.

**Comment by IS4Code** [comment]
@electronicboy Where are the answers then? I have seen none.

**Comment by electronicboy** [comment]
The question has been discussed on discord every day almost, we don't need issues tracking stuff like this
