### ISSUE TITLE
Perched Dragon Breath Hitbox

### ISSUE THREAD

**Issue by multicody10** [PaperMC/Paper#2088]
### What behaviour is expected:
The area effect cloud the dragon spawns while it's perched can be collected with glass bottles. Each time you collect a bottle of it, it should decrease in size until the hitbox size reaches 0 and the breath despawns.
This also applies to the area effect clouds spawned by the fireballs the dragon shoots.

### What behaviour is observed:
When you collect a bottle of the breath, the hit box decreases like normal, but doesn't despawn at 0. Instead, the hitbox goes negative and begins expanding each time you collect a bottle of it.
The area effect clouds spawned by the fireballs the dragon shoots work like they should though.

### Steps/models to reproduce:
Destroy all the beacons in the ender dragon boss fight to make the dragon perch. Get nearby then wait for the dragon to spawn his breath where his head is. Use a glass bottle and spam right click while looking at decreasing the hitbox.

https://youtu.be/l_DRT7spMjY
Timestamps:
3:55 to 4:30
6:10 to 6:25

### Paper build number:
Paper version git-Paper-627 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Black-Hole** [comment]
What behaviour is observed in vanilla Minecraft versions 1.13.2 and 1.14.2?

**Comment by multicody10** [comment]
The same behavior is observed in a 1.12.2, 1.13.2, and 1.14.2 singleplayer vanilla world.

**Comment by multicody10** [comment]
Issue was fixed in paper 1.13 thanks to BillyGalbreath and zachbr
