### ISSUE TITLE
Players are experiening Error: null - when trying to /home with essentials. 

### ISSUE THREAD

**Issue by AstroDoughnaut** [PaperMC/Paper#2091]
### What behaviour is expected:
Successful teleport to a sethome using /home 

### What behaviour is observed:
Failure to teleport, instead receive "Error: null" when running /home

### Steps/models to reproduce:
Running /home with the latest EssentialsX build.

### Plugin list:
![image](https://user-images.githubusercontent.com/50031187/58443364-5164d580-80a6-11e9-970e-e33359e24e86.png)

### Paper build number:
![image](https://user-images.githubusercontent.com/50031187/58443372-5b86d400-80a6-11e9-82f5-d2fb019dc82a.png)

### Anything else:
`27.05 20:39:26 [Server] INFO INFO]: Hero_Pigg issued server command: /home bed
27.05 20:39:26 [Server] INFO ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:world - syncChunkLoad} did not stopTiming)
27.05 20:39:26 [Server] INFO java.lang.Throwable: null
27.05 20:39:26 [Server] INFO at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:96) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at co.aikar.timings.TimingHandler.close(TimingHandler.java:203) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1830) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1638) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:974) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.2.jar:git-Paper-51]
27.05 20:39:26 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

**Comment by kaanakduman** [comment]
I'm experiencing the same issue. I have noticed a few things:
- This bug only happens with some homes. Some homes will be fine while others will always say Error: null
- This bug also occurs with both homes and warps.
- This bug clears up after just waiting a few minutes.
- This bug occurs with both build 739 at https://ci.ender.zone/job/EssentialsX/ and build 98 at https://ci.ender.zone/job/EssentialsX-Experimental
- This bug did not seem to exist in build 50, but does in build 51.
- On Spigot 1.14.2, the bug appears to also exist but does not provide any error logs in the console.
- Removing PhantomSMP fixed the problem for me, but since Doughnaut does not have that plugin, I believe that it is a different plugin giving him that error. 

This is a console log for one example of the bug: https://hasteb.in/lagequvo.cs

**Comment by MiniDigger** [comment]
duplicate of #2084 ?

**Comment by electronicboy** [comment]
more than likely duplicate of #2084, Timing stack corruption is just a side-effect of the original issue
