### ISSUE TITLE
Server Crash Paper 1.14.2

### ISSUE THREAD

**Issue by Amonly25** [PaperMC/Paper#2092]
Crash Report: https://pastebin.com/KMd8Hjjr

Console Error: 
27.05 20:52:21 [Server] ERROR TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper 

https://pastebin.com/mg7iVi0D

**Comment by Prof-Bloodstone** [comment]
Looks like it duplicates #2084

**Comment by electronicboy** [comment]
Duplicate of #2084
