### ISSUE TITLE
"Frozen" Villagers causing immense server tps drops when there is more than 5 loaded in one area.

### ISSUE THREAD

**Issue by DXUltimate** [PaperMC/Paper#2093]
###  Timings or Profile link:
Timings keep returning a 400 Error so I cannot provide
[16:33:00 INFO]: Preparing Timings Report...
[16:33:01 INFO]: Error uploading timings, check your logs for more information
[16:33:01 WARN]: Invalid Format
java.io.IOException: Server returned HTTP response code: 400 for URL: http://timings.aikar.co/post
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_211]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_211]
        at co.aikar.timings.TimingsExport.getResponse(TimingsExport.java:335) ~[patched_1.14.2.jar:git-Paper-51]
        at co.aikar.timings.TimingsExport.run(TimingsExport.java:303) ~[patched_1.14.2.jar:git-Paper-51]
[16:33:01 INFO]: Upload Error: 400: Invalid Format
[16:33:01 INFO]: Check your logs for more information

### Description of issue:
Insane server TPS lag involving 10 or villagers in the same area. Villagers are permnanetly stuck in place since updating from 1.14.1 paper-42. Able to have 20 TPS until villagers are loaded, then server drops TPS drastically, villagers also do not move and are stuck in place permanently. This is not a mojang thing since they work fine in single player.

I can provide a live example of my server to show you if necessary.

### Plugin list:
Plugins (31): Announcer*, Boss, ChestSort, CMI, CrateReloaded, CrazyAuctions, EnjinMinecraftPlugin, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, GadgetsMenu, HeadDatabase*, Jobs, LockettePro, LuckPerms, MCPerks, Multiverse-Core, QuickShop, SimpleBackup*, StaffChat*, SuperbVote, TicketManager, Vault, VeinMiner, ViaVersion*, Votifier, VotingPlugin, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://pastebin.com/fuhe4Sv4 - bukkit
https://pastebin.com/7zYbCFMT - paper.yml
https://pastebin.com/3BYFcUPL - spigot
https://pastebin.com/C5118MW1 - server.properties

### Other helpful links
None, unfortunately.

### Paper build number:
https://puu.sh/DyjcG/28c43098fe.png - image of info it gave.

**Comment by finlaysawyer** [comment]
Whilst I'm not experiencing the TPS drops, I can reproduce that the villagers are permanently stuck in place since also updating from 1.14.1 paper-42.

**Comment by ChrisPatrol** [comment]
Can confirm also getting frozen villagers who do not walk around but stay in one place. You can however trade with them. Noticed NO tps drops.
Version paper 51, 1.14.2.

**Comment by finlaysawyer** [comment]
Just been fixed upstream - https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/ba575a5a41a12dbe0d0626f7ad7e25384d0d9885

**Comment by MiniDigger** [comment]
who doesn't like broken mappings :D https://hub.spigotmc.org/stash/projects/SPIGOT/repos/builddata/commits/633897ca59f5feb54c9f7f1a953f1989d9cb1b64
