### ISSUE TITLE
1.14.1: PreRuleMatchEvent cannot be triggered asynchronously from primary server thread

### ISSUE THREAD

**Issue by kangarko** [PaperMC/Paper#2099]
Using Paper 1.14 b52

How to solve this problem? I am using ProtocolLib so the listening naturally goes on a separate thread. I am kind of puzzled here. That's a new function that was not here in 1.13 and I'd like to keep my plugins up to date.

Here's a snippet of my code, the API fires somewhere there but you get the basics:
![a](https://i.imgur.com/ewOrfN0.png)

Thanks

**Comment by electronicboy** [comment]
Events need to be properly marked async if they're being fired off the main thread, in the past with CB they'd just silently block, potentially leading to a deadlock in the server should the right conditions arise, the Event class has a constructor which lets you set if the event is firing async or not

**Comment by kangarko** [comment]
How do I do this?

**Comment by kangarko** [comment]
Oh okay, thank you!

**Comment by kangarko** [comment]
@electronicboy Is it safe to mark the affected events async and then use them in both sync and async scenarios?

**Comment by electronicboy** [comment]
Nope, they should be marked according to if they're fired from the main thread, `super(!Bukkit.isPrimaryThread());` would do it

**Comment by kangarko** [comment]
Thanks!
