### ISSUE TITLE
/reload permissions removes plugin.yml-granted permissions from non-op players

### ISSUE THREAD

**Issue by RoboMWM** [PaperMC/Paper#210]
Not sure how this should be categorized, but the `/reload permissions` command causes default permissions as specified by a plugin's plugin.yml (for non ops) to not be given. I don't use any permissions plugin.

This behavior is similar to loading in a new plugin after server start (via a plugin manager like plugman).
### (One way) To reproduce:
1. Install GriefPrevention
2. Note how default players can use commands like /trust, /accesstrust, etc.
3. Do /reload permissions
4. Note how non-ops can no longer use commands like /trust, /accesstrust, etc.

**Comment by kashike** [comment]
This is currently intended - permissions are cleared when `/reload permissions` is ran.

**Comment by aikar** [comment]
probally need to run some other form of re-initialization to grant things granted by plugins.

@willies952002

**Comment by willies952002** [comment]
I'll look into this to see what can be done

**Comment by willies952002** [comment]
Update: I have a build out for testing, I'll report back as soon as I'm done.
