### ISSUE TITLE
People can't use /home

### ISSUE THREAD

**Issue by HyperlyBola** [PaperMC/Paper#2101]
### What behaviour is expected:
___What you expected to see___
People being able to use /home
### What behaviour is observed:
___What you actually saw___
Errors in console and them getting the message "NULL"
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
1. Type /home
2. See what happens
### Plugin list:
___A list of your plugins___
EssentialsX
WorldGuard
WorldEdit
AutoMessager
AVPORTALS
GriefPrevention
NuVotifier
SuperbVote
PEX
ImageOnMap
PetMaster
Timber
Vault
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
54
### Anything else:
___Anything else you think may help us resolve the problem___
https://pastebin.com/NfEvcxAs

**Comment by kaanakduman** [comment]
https://github.com/PaperMC/Paper/issues/2084

**Comment by kickash32** [comment]
Need proper logs and what plugin the /home command belongs to.

**Comment by HyperlyBola** [comment]
^ That's literally all I get from the logs when someone uses /home, as you saw a person type /home *homename* then it only gives that out, I don't believe this is entirely plugin related :)

**Comment by kickash32** [comment]
You say there are errors in the console, can you post all of them?

**Comment by HyperlyBola** [comment]
Oh by errors I just meant repeats of this https://pastebin.com/NfEvcxAs, and it only occurs when a user types /home, or tries to warp somewhere, anyways i recently found out this issue is a dupe of another one so ima close it.
