### ISSUE TITLE
1.14: Player/Armor stand rotation does not work

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#2102]
When a player sees another rotating player/an armor stand, the player/armor stand does not rotate. (for players only the head rotates)

In spigot/vanilla the whole player rotates.

the cause of this bug is here: https://github.com/PaperMC/Paper/blob/ver/1.14/Spigot-Server-Patches/0037-Send-absolute-position-the-first-time-an-entity-is-s.patch - When I undo the changes in lines 56-75 (always calling `this.f.accept(packet1);`) it works as expected.

**Comment by Puremin0rez** [comment]
I actually thought this was a vanilla issue, but sure enough you're right.

**Comment by BillyGalbreath** [comment]
Omg, I've actually seen this in game but didnt think anything of it.. One of my players turned to look at me as I was running around them, and only their head moved. I thought it was freaky, but then moved on with life and forgot about it. ^_^

Can confirm.

**Comment by electronicboy** [comment]
Fixed in the latest build (55+)
