### ISSUE TITLE
Toggle "mobs should only spawn in water"

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#211]
# Suggestion

**_This commit https://github.com/PaperMC/Paper/commit/8ccd31ed38792ba71a5e0587912eca0fc1d7b900 makes it impossible for players to build squid grinders with squid spawners, I would appreciate an option which allows us to toggle this new "feature"**_

**Comment by Puremin0rez** [comment]
I'm guessing you mean actual squid mob spawners? Well then, I guess it's true when they say everything breaks someones specific workflow haha.

**Comment by ghost** [comment]
Yes I mean actual squid spawners which worked fine until this change was pushed out.

**Comment by zachbr** [comment]
After testing it myself, the only grinders this commit breaks are ones that have no logical sense of working in the first place. It is more than possible to make a grinder just as it was before, the only thing this changes is bad vanilla logic that had no place ever existing.

Under the project's "aims to fix gameplay and mechanics inconsistencies." goal, I would argue this more than counts as a mechanics inconsistency to ever allow water mobs to spawn inside of any non-water block.

No thanks.

EDIT: Although I am questioning whether we should be checking the block under the mob or the block the mob spawns in itself, will probably fix that here in a second.
