### ISSUE TITLE
Duplication of items using unloaded chunks

### ISSUE THREAD

**Issue by hyperdefined** [PaperMC/Paper#2114]
A player on my server was able to duplicate items using a donkey in unloaded chunks.

### Steps/models to reproduce:
He was using a hacked client, but basically he teleported himself into a unloaded chunk and got back on a donkey, there for duplicating the donkey and any items in it's inventory.
There is a better way to show it here: https://www.youtube.com/watch?v=b4aVBUEwj3o
### Paper build number:
This server is running Paper version git-Paper-1613 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Black-Hole** [comment]
There is an option "prevent-moving-into-unloaded-chunks" in the paper.yml file.

**Comment by hyperdefined** [comment]
@Black-Hole I don't seem to have that in mine. Is it for 1.12.2?

**Comment by Black-Hole** [comment]
Some patches were backported, but not all it seems. :(
So maybe it's a good time to start migrating your server to 1.13.2?

**Comment by 0XE4** [comment]
This is still possible on git-Paper-1615 (MC: 1.12.2)

Edit: Down to 1614 and it is patched. Odd that it works again in 1615.
