### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#2115]
Been having a lot of crashes recently but have not made any changes to the server.

Crash 1: https://pastebin.com/xxuNUuSv
Crash 2: https://pastebin.com/wqntAuXP
Crash 3: https://pastebin.com/DN7rDGYz
Crash 4: https://pastebin.com/Zt5zn1Ax

Paper build: git-Paper-1613

**Comment by electronicboy** [comment]
Traced down to "nice players" on discord
