### ISSUE TITLE
Random block ticks are tied to mob-spawn-range in spigot.yml

### ISSUE THREAD

**Issue by coreyg142** [PaperMC/Paper#2120]
### What behaviour is expected:
Crops grow, trees decay, etc as normal

### What behaviour is observed:
Crops don't grow, leaves don't decay, grass doesn't spread when farther than mob-spawn-range

### Steps/models to reproduce:
Create a line of bamboo, fly out farther than mob-spawn-range value and no farther than the server view distance, observe that the bamboo fails to grow. Gradually move up a chunk every few minutes until growth starts. The chunk distance at that point should be the value for mob-spawn-range.

### Plugin list:
EssentialsX
Worldedit
Worldguard

### Paper build number:
This server is running Paper version git-Paper-59 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

### Anything else:
This issue was reported to Spigot six days ago: https://hub.spigotmc.org/jira/browse/SPIGOT-4988

And they seem to have implemented a fix four days ago: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/ffe694746d4d17124a1117057108a1212a9a9af8

However it doesn't seem like this fix has made it over to Paper.

**Comment by electronicboy** [comment]
This was fixed a good little while ago, forgot to close the ticket
