### ISSUE TITLE
Enormous mobSpawn and entityTick TPS lag 1.14.2 #58

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [PaperMC/Paper#2123]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___
https://timings.aikar.co/?id=d1ea65f14e114230a7b1d8a0727e6a00#timings
### Description of issue:
___If applicable___
Enormous mobSpawn and entityTick TPS lag issue with low amount of entities
### Plugin list:
___All plugins running on the server___
Timings included
### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___
Timings included
### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
1.14.2 #58

**Comment by Kryniowesegryderiusz** [comment]
@electronicboy could you please give me a id of issue this is duplicate of? i cant find it :/

**Comment by electronicboy** [comment]
There are several ticks relating to this issue, this is, in general, the current state of 1.14 due to changes all the way up in vanilla

**Comment by Kryniowesegryderiusz** [comment]
Thank you
