### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by foxi69** [PaperMC/Paper#213]
**The following are 'hard suggestions': if you have the information
available to you, you really should put it in the report. Choose one of
the following templates from below that best fits the issue you wish to
report.**
# Performance issue

**_This section should be used for any report regarding performance issues**_
### Timings or Profile link:

**_We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real
cause of the issue.**_

http://timings.aikar.co/v2/d=411c6e14b8324f238639a84504781ff6
### Description of issue:

**_If applicable**_
### Plugin list:

16.04 11:53:15 [Server] INFO Plugins (44): RedstoneClockPreventer, WorldEdit, SimpleTrading, TitleMotd, AnimatedNames, ChatControl, ActionHealth, ProtocolLib, NoCheatPlus, SkinsRestorer, iDisguise, getID, PermissionsEx, TreeAssist, Tab, Lottery, CustomBot, FAQ, Vault, LightAPI, ShopGUIPlus, Essentials, ShareControl, PlaceholderAPI, SexyMotd, BattlePets, Jobs, PlotSquared, Multiverse-Core, Holograms, DeluxeChat, TreasureChest, HeavySpleef, AncientGates, CraftBook, ServerSigns, EssentialsSpawn, GriefPrevention, AuthMe, Paintball, MobArena, ProtectionLib, FurnitureLib, DiceFurniture
### bukkit.yml, spigot.yml, paper.yml, server.properties

**_Gist/pastebin/hastebin links**_
### Other helpful links

**_The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.**_
### Paper build number:

**_This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.**_

git-Paper-681
# Incompatibility (Bug)
### What behaviour is expected:

**_What you expected to see**_

http://pastebin.com/YRhP1eAD
### What behaviour is observed:

**_What you actually saw**_
### Steps/models to reproduce:

**_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue**_
### Plugin list:

**_A list of your plugins**_
### Paper build number:

**_This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.**_
# Crash, Stacktrace
### Link/paste of stack trace

```
You can also simply just use code formatting in markdown!
```

**_We need all of the stack trace! Do not cut off parts of it.**_
### Plugin list:

**_A list of your plugins**_
### Actions to reproduce (if known):

**_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue**_
### Paper build number:

**_This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.**_
# Suggestion

**_We love suggestions! Suggestions are fairly unstructured, and will be treated as such**_

**Comment by zachbr** [comment]
Closing for age/inactivity. If this continues on latest, open a new issue please.
