### ISSUE TITLE
update error 

### ISSUE THREAD

**Issue by slvlr** [PaperMC/Paper#2130]
I am on paper version 59 everything works fine no errors, I updated to paper 65 and this is my log https://pastebin.com/tnk9LQhw  Error with Holograms, TownyChat, Citizens, ontime - and players couldn't speak in chat  -  I downgraded back to version 59 and it all fixed again

**Comment by electronicboy** [comment]
Spigot recently made some changes to some internal methods, plugins will need to be updated to fix this

**Comment by slvlr** [comment]
Could you confirm which plugins are breaking on this list please? Towny chat I think is the only one with a load error and the rest is shutdown crash errors?

**Comment by 0-x-2-2** [comment]
Enjin (maybe), Holograms, Citizens and TownyChat. There is some other plugins throwing exceptions when being disabled tho.
