### ISSUE TITLE
Server crash (1.12.2)

### ISSUE THREAD

**Issue by riku6460** [PaperMC/Paper#2132]
### Link/paste of stack trace
Log: https://pastebin.com/RJsh5MB0
Crash report: https://pastebin.com/kguciTgy

### Plugin list:
    Plugins (14): CheckPoint, EmbedScript, FastAsyncWorldEdit, GoNiAth, Hide, Kick5zig, LuckPerms, Multiverse-Core, NoCollision, ProtocolLib, ProtocolSupport, ProtocolSupportController, RandCmd, WorldEdit

### Paper build number:
    This server is running Paper version git-Paper-1615 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by kickash32** [comment]
What is the CheckPoint plugin? It seems to be causing the issue. Is this a unique occurrence? Please post more details.

**Comment by electronicboy** [comment]
Don't teleport players async, it doesn't end well
