### ISSUE TITLE
Command block Crash (resolved)

### ISSUE THREAD

**Issue by fbievan** [PaperMC/Paper#2135]
I will just upload the log for this part to pastebin and link it here:
https://pastebin.com/zvWBnw5h
### Plugin list:
None
### Actions to reproduce (if known):
Here is a youtube link to reproduce it: https://www.youtube.com/watch?v=278Lf9LOO4s&feature=youtu.be
and if you want to see what i'm running there is a strcture block command if you want to um contact me to get that file 
### Paper build number:
Paper version git-Paper-65 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SN

**Comment by kickash32** [comment]
If this is resolved, you should close the issue.
