### ISSUE TITLE
Eating movement speed is not slowed

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#2137]
### What behaviour is expected:
Slow when eating food.

### What behaviour is observed:
While using sprint and eat player does not slow

### Steps/models to reproduce:
Fix it and return to slow

### Plugin list:
Nah.. Plugins (32): AdvancedPortals, AutoRespawnPlus, Citizens, ClearLag*, EpicHeads, EpicMoonGenerator, Essentials, EssentialsChat, EssentialsGeoIP, HolographicDisplays, InvRestore2*, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, PermissionsEx*, PixelPrinter, PlaceholderAPI*, PluginConstructorAPI, PlugMan*, RFChairs, ServerRestorer, SkQuery*, Skript, SpigotLib, TopLite*, TuSKe*, Vault, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
[17:36:21 INFO]: Checking version, please wait...
[17:36:21 INFO]: Previous version: git-Paper-65 (MC: 1.14.2)
[17:36:21 INFO]: You are running the latest version

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Spottedleaf** [comment]
cannot produce

**Comment by 0-x-2-2** [comment]
this is client-sided. you are probably using some sort of mod that causes this.

**Comment by Misio12320** [comment]
Optifine? Then its Minecraft bug

**Comment by 0-x-2-2** [comment]
optifine for 1.14.2 is a beta and has a ton of bugs.
