### ISSUE TITLE
Vanished-players-don-t-have-rights patch incomplete

### ISSUE THREAD

**Issue by kennytv** [PaperMC/Paper#2138]
### Steps/models to reproduce:
(using 1.14 paper-66, not sure if that's a thing in 1.13)
Hide player A from player B -> player B can't place blocks in player A's position, even though A is invisible.

The patch `0264-Vanished-players-don-t-have-rights.patch` does add a `canSee` boolean to the methods below, but both
![29tcv](https://user-images.githubusercontent.com/28825609/58984851-59c1bc80-87da-11e9-8317-97fb3df8f427.png) in `IWorldReader` and

![5jjg4](https://user-images.githubusercontent.com/28825609/58984856-5b8b8000-87da-11e9-8c23-e5189300eb5a.png) in `IEntityAccess` don't actually make use of them (as seen by the wonderful gray, squiggly line 👀).

**Comment by Spottedleaf** [comment]
wow I butchered that patch
