### ISSUE TITLE
Error executing task java.util.concurrent.ExecutionException:

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#214]
error logs
http://hastebin.com/kovosihaxu.avrasm

java 8 77 x64
paperclip #684

plugins
http://hastebin.com/bufikevena.vbs

bukkit.yml
http://hastebin.com/axovinitor.sm

spigot.yml
http://hastebin.com/uvubagebon.sm

paper.yml
http://hastebin.com/ahojezokef.sm

server.properties
http://hastebin.com/kusinocago.hs

**Comment by zachbr** [comment]
Closing for age/inactivity.
If this continues on latest, open a new issue please.
