### ISSUE TITLE
paper #67 - TIMING_STACK_CORRUPTION

### ISSUE THREAD

**Issue by Kbryst** [PaperMC/Paper#2141]
https://pastebin.com/brfRVXth

I don't actually know what "stacktrace" is. I'm assuming this counts as one?

### Plugin list:
-World guard
-World edit
-EssentialsX
-CMI
-Towny

### Actions to reproduce (if known):
-Loading in a map from 1.13.2 to 1.14.2 (just flying around it). The map loads in fine, just one area does this. I'm looking for the minecraft skull that could be in this area, in hopes of clearing the error.

### Paper build number:
Paper build #67 - currently latest version

**Comment by Chew** [comment]
> This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

Unfortunately we are unable to do anything about this issue without any logs. We have plenty of TIMING_STACK_CORRUPTION issues to spare though, so maybe it was superseded by one of them...

Edit: Just realized this was 1.14, probably 1.14 issue. We don't talk about 1.14.
