### ISSUE TITLE
TIMING_STACK_CORRUPTION - Combination with CraftBook

### ISSUE THREAD

**Issue by knniDE** [PaperMC/Paper#2143]
Complete Error Log w/o INFO Messages

on my friends server:
http://wb.knni.de/logs/Error-TIMING_STACK_CORRUPTION.log

on github upload:
[Error-TIMING_STACK_CORRUPTION.log](https://github.com/PaperMC/Paper/files/3263414/Error-TIMING_STACK_CORRUPTION.log)

I have no idea why.
As soon as I remove CraftBook, however, this error no longer appears.

**Comment by Chew** [comment]
Hello! This does appear to be an issue with CraftBook, and I've been told that it's much better now, especially after a whole year of this being open. If you are still having issues with the plugin, I recommend reporting to them first, then to us if it's really our issue. Thank you for the report!
