### ISSUE TITLE
Server join chunks loaded and kick

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#2146]
###  Timings or Profile link:
https://timings.aikar.co/?id=36e0964ac9cc4afd9373990c91875737

### Description of issue:
When joining server chunks are empty for 3 seconds, first showing entities after 1 second generating chunks and kick. EDIT: Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host

### Plugin list:
Plugins (29): AdvancedPortals, AutoRespawnPlus, Citizens, ClearLag*, EpicHeads, Essentials, EssentialsChat, EssentialsGeoIP, InvRestore2*, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, PermissionsEx*, PixelPrinter, PlaceholderAPI*, PluginConstructorAPI, PlugMan*, RFChairs, ServerRestorer, SkQuery*, Skript, TopLite*, TuSKe*, Vault, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit: https://pastebin.com/cmB255Fh
2. https://pastebin.com/WbUpXpSF
server.properties: https://pastebin.com/1pC2bfMp
paper: https://pastebin.com/iazaTYKg

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
This server is running Paper version git-Paper-68 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

**Comment by Misio12320** [comment]
https://timings.aikar.co/?id=d1d82c240df3407bbaf75bef81835cee new one. https://pastebin.com/NdzjmPAe https://pastebin.com/F92ZLP9X I have 10 times join server to get lucky one and play.

**Comment by electronicboy** [comment]
You have plugins which are throwing exceptions because they've not been updated, other errors are just 1.14 being 1.14 (watchdog), keepalive timeout along with the error you're saying you're getting kicked with indicates that your potentially having network issues

**Comment by Misio12320** [comment]
Which also plugin breaking the server in performance? Suggestions?
