### ISSUE TITLE
1.14 server Crash

### ISSUE THREAD

**Issue by kennytv** [PaperMC/Paper#2147]
### Link/paste of stack trace
https://paste.mykns.net/mirubosusa.md

### Plugin list:
PEX, ProtocolLib, a custom one (that didn't really do that much tricky stuff at that point, also isn't included in the stacktrace)

### Actions to reproduce (if known (not really)):
Didn't really see a specific cause, https://youtu.be/SDSX2jffpCk around the 20 minute mark

### Paper build number:
1.14 paper-67

**Comment by KisaragiEffective** [comment]
does this happen on latest build?

**Comment by kennytv** [comment]
No idea, problem is that
a) I dont know how to reproduce it
and b) won't have the next round for that 1.14 project until next month or so

**Comment by kennytv** [comment]
Closing in favor of #2381
