### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#215]
git-Paper-684

Crash happened after about 10 hours of uptime with the 684 build.

http://pastebin.com/FdXZwj56

**Comment by hurrgurl** [comment]
Apparently I had more than a single crash (before 684).

Both come from git-Paper-647
http://pastebin.com/k5uKpXvf

**Comment by aikar** [comment]
these kind of errors happen when you have bad plugins doing things async.

the best we can do is to add code to help identify which bad plugin it is, but you can try removing them 1 by 1, it'll likely be one dealing with chunks.
