### ISSUE TITLE
Spawn Protection does not work with ItemFrames

### ISSUE THREAD

**Issue by marwuint** [PaperMC/Paper#2150]
What behaviour is expected:
If not OP you can't change or destroy anything in spawn

What behaviour is observed:
Itemframes and items in them can be destroyed/rotated even when not server operator.

Steps/models to reproduce:
Right click an item in itemframe....

Plugin list:
None.

Paper build number:
This server is running Paper version git-Paper-55 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
Anything else:

**Comment by Black-Hole** [comment]
Vanilla issue: https://bugs.mojang.com/browse/MC-862

**Comment by kickash32** [comment]
I have my doubts that Mojang will ever fix this. Personally I think if you really want to fine tune your spawn protection, you should use world guard and turn off entity damage inside spawn region.

**Comment by k9lego** [comment]
WorldGuard is the best option tbh

**Comment by Chew** [comment]
This appears to be fixed in 1.15.2 pre-release 1, implying it's fixed on 1.15.2, this needs to be tested to ensure it's fixed on latest supported versions (1.15.2 and 1.16.1)

**Comment by Chew** [comment]
Actually, just checked myself, definitely is fixed on 1.15.2 Paper so I assume 1.16.1 is fixed as well. Thank you for the report!
