### ISSUE TITLE
[1.14] Entity Villager performence issue

### ISSUE THREAD

**Issue by Foorcee** [PaperMC/Paper#2151]
Villager tick cause lags on the server.

JProfiler: https://i.imgur.com/6AIdmPS.png

Timings: https://timings.aikar.co/?id=457ad671bb074dc1ac7ae8d0911a6bec

Version 
Paper 1.14-68

**Comment by Foorcee** [comment]
JProfiler exclusively on main server thread: https://i.imgur.com/hkXbREn.png, https://i.imgur.com/PK4EO6Z.png

**Comment by successed** [comment]
yeah, i have problem. #80 1.14.2

im waiting 1.14.3

**Comment by Proximyst** [comment]
Outdated by now, and we've optimised villagers.
