### ISSUE TITLE
Saved toolbars events

### ISSUE THREAD

**Issue by eUipKh** [PaperMC/Paper#2152]
**Is your feature request related to a problem? Please describe.**
Is there any option that you guys could create events for the saved toolbar feature introduced in 1.12?

**Describe the solution you'd like**
Just add two or three simple events.
- SaveToolbarEvent.
- RestoreToolbarEvent.
- (Maybe?) ClearToolbarEvent.

**Describe alternatives you've considered**
...

**Additional context**
- https://imgur.com/ZwyBU2q

**Comment by electronicboy** [comment]
Toolbars themselves are handled by the client, all we get is a flood of slot packets
