### ISSUE TITLE
The server has stopped responding!

### ISSUE THREAD

**Issue by Denschen** [PaperMC/Paper#2154]
### Link/paste of stack trace
- Lobby Server: https://pastebin.com/ekc442Px [The (MySQL) Error with the Bansystem/Lobbystem does not have to be the reason for the crash]
- Practice Server: https://pastebin.com/vFY0zSns (No plugin included in the error)

### Plugin list:
- Lobby Server: http://prntscr.com/nzkwms
- Practice Server: https://prnt.sc/nzkg2j

### Actions to reproduce (if known):
- It's not known. Every single PaperSpigot Server crashed after several hours.

### Paper build number:
- This server is running Craftbukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Black-Hole** [comment]
1.8.8 isn't supported for more than four years now! So it's about time that you update to a supported version.

**Comment by Denschen** [comment]
I know that 1.8.8 isn't supported. But the most PvP server networks are still on 1.8.8. That's why you should publish a stable version

**Comment by BillyGalbreath** [comment]
I dont think you understand what not supported means.

**Comment by electronicboy** [comment]
This is free software, We already have enough with maintaining modern versions of the game, why would we add more work for ourselves?

As for your first crash, mysql on the main thread would be my best guess, the second is more elusive, system clock jump, maybe? Pretty hard to work out what really happened as you're missing the features which make debugging these issues easier.
