### ISSUE TITLE
Vouchers incompatibility

### ISSUE THREAD

**Issue by Crqnkk** [PaperMC/Paper#2158]
### What behaviour is expected:
___What you expected to see___
I expected the plugin to load all my items and the plugin it self.
### What behaviour is observed:
___What you actually saw___
it seemed fine but then while starting the server it just crashes.
09.06 17:00:36 [Server] INFO [Vouchers] Enabling Vouchers v1.7.5
09.06 17:00:36 [Server] INFO [Vouchers] Loading the Config.yml
09.06 17:00:36 [Server] INFO [Vouchers] Successfully loaded Config.yml
09.06 17:00:36 [Server] INFO [Vouchers] Loading the Data.yml
09.06 17:00:36 [Server] INFO [Vouchers] Successfully loaded Data.yml
09.06 17:00:36 [Server] INFO [Vouchers] Loading the Messages.yml
09.06 17:00:36 [Server] INFO [Vouchers] Successfully loaded Messages.yml
09.06 17:00:36 [Server] INFO [Vouchers] Loading the VoucherCodes.yml
09.06 17:00:36 [Server] INFO [Vouchers] Successfully loaded VoucherCodes.yml
09.06 17:00:36 [Server] ERROR Error occurred while enabling Vouchers v1.7.5 (Is it up to date?)
09.06 17:00:36 [Server] INFO java.lang.NullPointerException: null
09.06 17:00:36 [Server] INFO at me.badbones69.vouchers.api.Vouchers.load(Vouchers.java:24) ~[?:?]
09.06 17:00:36 [Server] INFO at me.badbones69.vouchers.Main.onEnable(Main.java:52) ~[?:?]
09.06 17:00:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
09.06 17:00:36 [Server] INFO [Vouchers] Disabling Vouchers v1.7.5
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
n/a idk
### Plugin list:
___A list of your plugins___
Auctionhouse
buycraftx
chatcolor2
clearlag
coinflip
combatlogx
coreprotect
cratesplus
cs-corelib
customcommands
easybackup
envoys
epicrename
essentials
essentialschat
essentialsspawn
factions
factionsfly
factionstop
gcore
hideacievements
holograms
hologramsplaceholders
litebans
lottery
luckperms
matrix
mcmmo
messageannouncer
mineablespawners
mobloot
moneynote
multiverse-core
obybreaker
placeholderapi
player heads
playervaults
pluginhiderplus
plugman
protocollib
quickboard
redeemmcmmo
tablist
ushop
vault
voteparty
votifier
votingplugin
vouchers
wild
worldborder
worldedit
worldguard
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-paper-70 mc 1.14.2
### Anything else:
___Anything else you think may help us resolve the problem___
idk

**Comment by electronicboy** [comment]
I'd suggest speaking to the plugin author, we can't do much about premium plugins as we don't have access to them, NPEs also mean that they're assuming that something isn't null when it is, generally a configuration error on your side or a bug with the plugin
