### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by noramibu** [PaperMC/Paper#2159]
### Link/paste of stack trace
Line 838
https://pastebin.com/raw/9TsEsjSR

### Plugin list:
___A list of your plugins___
AlphaChest
AuctionHouse
AuthMe
Citizens
EssentialsX
EssentialsXChat
EssentialsXGroupManager
Factions
Holograms
Multiverse Core
Mythic Mobs
OB-Boss
PlayMoreSounds
ProtocolLib
Quests
SkinsRestorer
SkQuery
SkRayFall
Skript
TuSke
UltimateCatcher
UltimateTimber
Vault
Vixio
WolvSk
worledit-bukkit-6.1.9
worldguard-6.2.1
### Actions to reproduce (if known):
Sorry sir, i dont know

### Paper build number:
log of version command
> version
[04:29:57 INFO]: This server is running Paper version git-Paper-1613 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[04:29:57 INFO]: You are 2 version(s) behind

**Comment by jacobsandersen** [comment]
Firstly, try updating your paper server. You're 2 versions behind. I don't see anything standing out; there is one blocked thread with regard to the console appender.

Secondly, at the very bottom, Skript (though, I don't think Skript is the cause) gives you some recommendations. Did you try those?

**Comment by electronicboy** [comment]
Your server took too long to tick, for additional support join discord and provide the *full* server logs (Also, re-enable the early watchdog warnings in paper.yml, your log file is basically useless without it)
