### ISSUE TITLE
[1.13.2] Performance issue with some entities

### ISSUE THREAD

**Issue by fhebuterne** [PaperMC/Paper#2160]
###  Timings or Profile link:

Timings 9 june : https://timings.aikar.co/?id=c5312616140340e9bb146f4a0f7c3531
Timings 10 june : https://timings.aikar.co/?id=dc0f55c6a44e4f58850f36b4f48a2d93

### Description of issue:

Hello,
Recently we are upgraded from paper 1.12.2 to paper 1.13.2 and we have some performance issue with entities, we have low TPS and entities are in red in all timings.

### Plugin list:

(See Plugins in Timings)

### bukkit.yml, spigot.yml, paper.yml, server.properties

bukkit.yml : https://pastebin.com/24mcGYSW
spigot.yml : https://pastebin.com/U3RCfZjr
paper.yml : https://pastebin.com/YvkZbgvL
server.properties : https://pastebin.com/6haJZz3f

**Comment by ds58** [comment]
Possibly related to #1791

**Comment by Proximyst** [comment]
Given the data is gone, and this is very outdated, I'll close this issue. If you need help with optimisation in the future, our Discord's a great place to ask.
