### ISSUE TITLE
1.14.2 b76 huge performance problem

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [PaperMC/Paper#2161]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___
https://timings.aikar.co/?id=2df0775b063a429e82f9b6cdbdcb51d6
### Description of issue:
___If applicable___
There is some strange issue with BentoBox, but they say its paper bug so idk what to do XD The fact is server in unplayable :/
### Plugin list:
___All plugins running on the server___

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
1.14.2 76

**Comment by electronicboy** [comment]
I overlooked something while rewriting a patch, working on a fix now
