### ISSUE TITLE
Allow custom "No permission" message

### ISSUE THREAD

**Issue by leifadev** [PaperMC/Paper#2165]
Could you make it possible to have the option in a yml file like the bukkit.yml to be able to change/customise the permission message that gets shown to player when they dont have permission to execute a command?
This would be very appreicated!

Example:
/server/bukkit.yml/
`permission-message: You do not have permission to use that command`

**Comment by electronicboy** [comment]
`messages.no-permission` (in paper.yml) - Plugins can and do override that, however, best option there is often to have another plugin come in and replace them if you really wanted that
