### ISSUE TITLE
İ Have performance problem #80

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#2167]
###  Timings or Profile link:
https://timings.aikar.co/?id=13df09a4f0b6426198b00a603bf13334
and
https://timings.aikar.co/?id=77fd7c8017674d0f9a826f1f14164cca

### Description of issue:
Low tps

### Plugin list:
http://prntscr.com/o0cz4s

### bukkit.yml, spigot.yml, paper.yml, server.properties

[bukkit,spigot,paper.yml.zip](https://github.com/PaperMC/Paper/files/3275767/bukkit.spigot.paper.yml.zip)

### Paper build number:
[12:47:05 INFO]: This server is running Paper version git-Paper-80 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
[12:47:05 INFO]: Checking version, please wait...
[12:47:05 INFO]: Previous version: git-Paper-77 (MC: 1.14.2)
[12:47:05 INFO]: You are running the latest version

**Comment by Prof-Bloodstone** [comment]
Your problem is using 1.14 - chunk handling is very slow unfortunately.

**Comment by successed** [comment]
> Your problem is using 1.14 - chunk handling is very slow unfortunately.

This a not chunk problem. This a villager problem. Check this timings..

**Comment by electronicboy** [comment]
Please use the search function in the future
