### ISSUE TITLE
Extremely Low Hostile Mob Spawning Rates 

### ISSUE THREAD

**Issue by Jesse-Goertzen** [PaperMC/Paper#2168]
### What behaviour is expected:
Standard hostile mob spawning rates.

### What behaviour is observed:
Extremely low mob spawns. A spawner that used to produce 20-30 hostile mobs per "flush" on vanilla is now producing 0-5. There are very few mobs on the surface at night, and using `/paper entity list` shows approximately 20 mobs of each hostile type, with a notable exception of 0-2 *Drowned*. 

### Steps/models to reproduce:

1. Start server/map on vanilla server 1.14.1
2. Upgrade to 1.14.2
3. Upgrade to Paper
4. Experience low mob spawning rates.

### Plugin list:

- BloodInMinecraft*
- ChestSort
- FastLeafDecay
- gravy
- ID-Library
- LuckPerms
- PlayerParticles
- ShulkerPacks

We have also tested spawning without any plugins installed and experienced the same rates.

### Paper build number:
`This server is running Paper version git-Paper-80 (MC: 1.14.2)`

`(Implementing API version 1.14.2-R0.1-SNAPSHOT)`

`Previous version: git-Paper-76 (MC: 1.14.2)`

### Anything else:
Our server is small, just 3 active players at any time. Often only 1 or 2.

[Here is a zip containing our configuration files.](https://github.com/PaperMC/Paper/files/3277722/paper_config.zip)

**Comment by wiauxb** [comment]
### Same problem on the Paper 1.14.4 Build 137

It seems to only happened into the Nether.
We played a long time before we realized the issue so it's hard to say how to reproduce it, but the server has been switched from Paper 1.14.4 to vanilla 1.14.4 and then back to Paper 1.14.4, it could be a part of the issue ...

- No plugins
- default configuration exept gamerule maxEntityCramming to 250

**Comment by Eldritch-Oliver** [comment]
This has also been a problem with upgrading from Paper 1.16.1 to Paper 1.16.2, the overworld was fine but the nether was having minimal spawns and those that were spawning were not aggressive.

---

Plugins:
 - EssentialsX 2.18.1.0
 - MoreMobHeads 1.14 - 1.0.15
 - PowerRanks
 - World Edit Bukkit 7.2.0 beta 02
 - World Guard Bukkit 7.0.4 beta 1

---

Configurations:
 - Only WorldEdit modified, rest are all default
 - No config changes between the upgrade version

---

Fix:
 - We found that resetting the nether fixed the issue. We are not sure specifically why but it made the mobs aggressive again and spawn in higher quantity.
