### ISSUE TITLE
EntityTag data being removed from item frames in the inventory

### ISSUE THREAD

**Issue by darkllama23** [PaperMC/Paper#2169]
### **Description of issue:**

Will spawn in an item frame with custom EntityTag data, after a couple seconds that custom data will disappear. We are using a custom datapack on the world too. The datapack works fine in vanilla.

### **Paper Build No:**

 73 (1.14.2)

### **Plugin List:**

Custom plugin that records chat and commands to a SQL database, and that's it

### Screenshots: 

When you first spawn in the item frame with custom entitytag data:
![2019-06-11_17 46 20](https://user-images.githubusercontent.com/6438066/59312543-8b73d100-8c7b-11e9-80e2-33069ad44812.png)

A couple seconds later:
![2019-06-11_17 47 05](https://user-images.githubusercontent.com/6438066/59312565-9fb7ce00-8c7b-11e9-8954-b49a960d0e9e.png)

**Comment by kickash32** [comment]
Is this issue occurring in vanilla as well?

**Comment by darkllama23** [comment]
> Is this issue occurring in vanilla as well?

Yes, and thank you for reminding me. I updated the original post.

**Comment by darkllama23** [comment]
I have more information to provide and I am not sure to update this issue or close it and create a new one, I am making a new comment for now. 

This issue still exists in the latest build of paper (Build 176; 1.14.4), and after some digging around, its really similar to [Issue No. 559](https://github.com/PaperMC/Paper/issues/559). 

Steps to reproduce:
- Change to creative
- Obtain an item frame with NBT data, either its by trading with a villager (datapack function), loot command or give command
- Open Inventory
- Type /data get entity %player Inventory[x].tag and you will see the 'EntityTag' NBT will be gone.
- Place item frame, and you will see it will no longer be the custom model.

[Screenshots Here](https://imgur.com/a/v0QP1AH)

The 'filter-nbt-data-from-spawn-eggs-and-related' option in the paper.yml is also set to false.

**Comment by MulverineX** [comment]
Any way I could help with this? I am running into the same issue. Did you come up with some solution/workaround @darkllama23 ?

**Comment by MulverineX** [comment]
This still isn't resolved. Also, it's not just 1.14, it persists in 1.15, and it probably wasn't fixed in 1.16

**Comment by MulverineX** [comment]
Ditto.

**Comment by ProblemsSender** [comment]
does this bug exist in 1.12.2 server? because it seems i have the same issue with the NBT tag with armor, the set of armor only counts as 1 piece to the overall attribute.

**Comment by lynxplay** [comment]
I am trying to replicate this on the the latest 1.17.1 version, however am unable to.
Here is my following setup to replicate it on 1.14.4, which produces the bug:

1. Move myself into creative mode.
2. Give myself the item frame through `/give @s item_frame{CustomModelData:99,EntityTag:{Item:{id:"minecraft:item_frame",Count:1b,tag:{CustomModelData:42}}}} 1`
3. Open my creative inventory.
4. Check the item frame item in my inventory through `/data get entity @s Inventory[0]`
5. Notice the data is gone

Replicating this on 1.15.2 also worked, however the item had to be moved in the creative inventory, opening was not enough.
I was not able to replicate this on 1.16.5's latest build, so I am a bit worried I could have missed something in my setup. 

@aurorasmiles do you still recall how you replicated this on 1.16 ? I know it has been a while :sweat_smile:

**Comment by lynxplay** [comment]
Just like with 1.17.1 I am unable to replicate this with the steps laid out in [my previous comment](https://github.com/PaperMC/Paper/issues/2169#issuecomment-980216095).

I will be closing this issue concerning how old it already is and due to the fact that I cannot replicate it anymore.

If anyone runs into this issue on the latest version, please open a new issue about it :+1:
