### ISSUE TITLE
The village in the server is full of fool villagers!?服务器的村庄里都是傻子村民！？

### ISSUE THREAD

**Issue by William-Scott** [PaperMC/Paper#2172]
### What behaviour is expected:
___What you expected to see___
some normal villagers
一些普通的村民
### What behaviour is observed:
___What you actually saw___
There are only a bunch of green idiot villagers in the three villages until now.
到现在为止三个村庄里只有一堆绿衣傻子村民
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
No
没有
### Plugin list:
___A list of your plugins___
No Plugin be used
没用任何插件
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
Previous version: git-Paper-67 (MC: 1.14.2)
### Anything else:
___Anything else you think may help us resolve the problem___
No
没了

**Comment by kickash32** [comment]
The first thing you should try when you have issues is to update your server if you are not running the latest build.
