### ISSUE TITLE
Timings Error 400 issue.

### ISSUE THREAD

**Issue by DXUltimate** [PaperMC/Paper#2173]
### What behaviour is expected:
The timings report uploaded and reported.

### What behaviour is observed:
https://puu.sh/DEZHd/238acb3cd8.png

Error 400, doesn't upload, nor give me the timings that I need.

### Steps/models to reproduce:
Not sure. 

### Plugin list:
https://puu.sh/DEZLa/0032dfc464.png
I don't think my plugins would have anything to do with the timings reporting process. I did try and set it up where there were no plugins on, and it still refused to provide a timings report, so.

### Paper build number:
Paper v80. This has happened as well since I started using paper in 1.14's paper 52

### Anything else:
If you need any of the current versions of the plugins I am using, I am more than happy to provide a download if necessary. I did do an update recently on essentialsX, CMI and QShop.

**Comment by ghost** [comment]
Well, I had the same Error. I fixxed this with changing the locales from the Server, where the MC-Server is running on to `C.UTF-8`.

https://lintut.com/how-to-set-up-system-locale-on-ubuntu-18-04/
