### ISSUE TITLE
Editing sign if opened by HumanEntity#openSign is not possible

### ISSUE THREAD

**Issue by pitcer** [PaperMC/Paper#2175]
### What behaviour is expected:
Ability to edit sign by the player if opened by `HumanEntity#openSign`.

### What behaviour is observed:
The sign cannot be edited and the following message is showed in the console:
![image](https://user-images.githubusercontent.com/10583479/59424109-a9544980-8dd3-11e9-8dda-4de45f724287.png)

### Steps/models to reproduce:
* Write plugin with listener of `PlayerInteractEvent`
* Add the following code:
```java
Block block = event.getClickedBlock();
BlockState state = block.getState();
Sign sign = (Sign) state;
Player player = event.getPlayer();
player.openSign(sign);
```
* Click on the sign, edit some lines and click `Done`

### Plugin list:
There is only my plugin, which adds the listener described above.

### Paper build number:
`git-Paper-81 (MC: 1.14.2)`

### Anything else:
Setting sign as editable (by `sign.setEditable(true)`) is not resolving the problem.

**Comment by Spottedleaf** [comment]
The issue is you're trying to edit a copy of the sign. Use the non-copy operation for getState.

**Comment by pitcer** [comment]
What do you mean by "non-copy operation for getState"? I tried getState(false), but it doesn't change anything.

**Comment by electronicboy** [comment]
Works as intended here
```kotlin
    fun openSign(sender: Player) {
        val sign = getSign(sender)

        if (sign == null) {
            MessageUtil.sendError(sender, "You must be facing a sign!")
            return
        }

        sender.openSign(sign)


    }

    private fun getSign(player: Player) : Sign? {
        val block = player.getTargetBlock(mutableSetOf(Material.AIR), 8)

        if (!MaterialTags.SIGNS.isTagged(block)) {
            return null
        }

        return block.state as Sign?
    }
```

You're not calling update() on the sign state somewhere are you?

**Comment by pitcer** [comment]
Ok, I used exact the same code as you, generated clear paper server and it works, so I did something wrong in my plugin. Thanks for help and sorry for writing redundant issue.
