### ISSUE TITLE
Compilation issue on branch ver/1.14

### ISSUE THREAD

**Issue by shit-ware** [PaperMC/Paper#2179]
Hi,

I am forgoing the the template (sorry) because this isn't a runtime issue but an issue with compiling.
When I run ./paper jar to build, maven failed with the following error:
![image](https://user-images.githubusercontent.com/10711154/59465536-bcc1dd80-8df0-11e9-9470-ac83766f4465.png)
Is this an environment issue or is there a code issue?

Thanks.

**Comment by kickash32** [comment]
What JDK are you using?

**Comment by shit-ware** [comment]
![image](https://user-images.githubusercontent.com/10711154/59465766-3c4fac80-8df1-11e9-88ea-5caa0c185c1a.png)

**Comment by kickash32** [comment]
First of all, use code blocks, not images.
JDK 12 has this issue, you can either downgrade to JDK 11 or just use `mvn` to compile directly.

**Comment by shit-ware** [comment]
Thought it would have been easier, sorry. Alright, thanks.

**Comment by MiniDigger** [comment]
noticed this one before, since jdk 13 has just been forked from mainline and is set to GA in 3 months I think its time to replace the java 6 submodule with 7 or just remove it. creating an issue in the paperclip repo
