### ISSUE TITLE
Plain Paper Crashing Build #85

### ISSUE THREAD

**Issue by Fordy436** [PaperMC/Paper#2185]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___
https://pastebin.com/pCfcNC8U

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
None
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
When 2 or more players join, wait a while...
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
Build 85, latest.

Very strange issue... appears to occur randomly and suddenly with no errors showing in the console.

**Comment by electronicboy** [comment]
The process was intentionally killed by something on the machine, I'd suggest speaking to your hosting provider or checking your system logs
