### ISSUE TITLE
[1.12.2] Block Inventory Overwritten by Block State update

### ISSUE THREAD

**Issue by DarkArc** [PaperMC/Paper#2189]
### What behavior is expected:
```
Chest chest = (Chest) getWorld().getBlockAt(x, y, z).getState();
Inventory chestInventory = chest.getBlockInventory();
chestInventory.clear();
chest.update(true);
```

This code used to work, however, after further investigation, it seems updating the block state now overwrites any chances made to the inventory even if that inventory is obtained as part of the block state.

This provides an opportunity for dupe glitches, and similar problems within legacy code.

### Paper build number:
1615

**Comment by electronicboy** [comment]
The block inventory is the inventory of the block in the world, if you wanna modify the inventory of the snapshot, you should modify the inventory of the snapshot

This is a change upstream which kinda improved the system as a whole, but broke many plugins which where using this incorrectly, there is no fix here without breaking something else

**Comment by DarkArc** [comment]
I suspect that previously this was required for updating the block inventory, but this code was written well over 5 years ago, so I can only speculate at this point. Thanks
