### ISSUE TITLE
Enderchest does not play closing sound

### ISSUE THREAD

**Issue by Yottazoid** [PaperMC/Paper#2190]
### What behaviour is expected:
Enderchest should play its closing sound when exiting the GUI

### What behaviour is observed:
Enderchest does not play closing sound

### Steps/models to reproduce:
- Place enderchest, open then exit GUI

### Plugin list:
None

### Paper build number:
git-Paper-87 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

### Anything else:
Possibly related to  #2019

**Comment by electronicboy** [comment]
Fixed in 88+
