### ISSUE TITLE
/locate Endcity crashes server

### ISSUE THREAD

**Issue by GlazedPineapple** [PaperMC/Paper#2191]
### What behaviour is expected:
___What you expected to see___
/locate EndCity should give you coords to a endcity
### What behaviour is observed:
___What you actually saw___
The server timed out and I have to restart it
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
1. go to the end
2. run /locate endcity
3. Server timeout
### Plugin list:
___A list of your plugins___
BetterSleep,Coreprotect,developerapi,essentiasl,essentialsAntiBuild,Essentialschat,EssentialsGeoIP,LagAssist,LuckPerms,NotchAppleCrafter
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-paper-87
### Anything else:
___Anything else you think may help us resolve the problem___
I have also not found any endcitys. I have flown around in /gmsp and still could not find any
Here is a link to the errors that I get: https://hastebin.com/edociwulag.makefile

**Comment by Brokkonaut** [comment]
I had a similar crash today, but it happened without anyone using the "/locate endcity" command. There were just some players moving around in the world.

Looks like some severe problem with chunk loading.

https://pastebin.com/raw/zE98ebtp

**Comment by shadowscott** [comment]
Something similar happened to me. /locate Buried_Treasure ends up crashing server. Not sure if this is because I don't have a treasure map, but thought it would still work.

https://pastebin.com/GTWDY5sS

**Comment by Phoenix616** [comment]
Caused by the issues described in #2312
