### ISSUE TITLE
Timings URL

### ISSUE THREAD

**Issue by JohnS19** [PaperMC/Paper#2193]
I'm not sure if it's only me but 

if I use /timings paste in the console, it gives me the incorrect link:
https://timings.aikar.co/d=

Meanwhile, in the actual game, the command gives me the correct link of:
https://timings.aikar.co/?id=

**Comment by MiniDigger** [comment]
whats your paper version?

**Comment by electronicboy** [comment]
This issue is caused by control panel software improperly handling the console output
