### ISSUE TITLE
Issue with water. Very weird, never seen it before.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [PaperMC/Paper#22]
I'm running the latest version of PaperSpigot 1.8 as of 2/10/16. Water is acting weird. View the video to see what I'm saying.

Video: https://www.youtube.com/watch?v=VFExX4Oxg10&feature=youtu.be

**Comment by zachbr** [comment]
This is almost certainly a duplicate of #11. Going to keep it open just in case it is its own separate issue.
Thanks for the report

**Comment by SnakeDaoust1232** [comment]
<3 Please fix.

**Comment by zachbr** [comment]
Closing as duplicate
