### ISSUE TITLE
SSL_ERROR_INTERNAL_ERROR_ALERT

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#220]
Getting error when accessing paper changelog web, is everything okay?

**Comment by zachbr** [comment]
We're aware of this situation and hope to have it resolved soon. For the moment, it is out of our hands.
Please be aware, there has not been any security breach, this is a configuration-based issue.

**Comment by zachbr** [comment]
We'll provide updates on Twitter as the situation evolves.
No need to keep this open. https://twitter.com/PaperPowered
