### ISSUE TITLE
Player#stopSound(Sound) not working if called directly in event

### ISSUE THREAD

**Issue by JustDylan23** [PaperMC/Paper#2201]
```java
@EventHandler
public void onPlace(BlockPlaceEvent event) {
    event.getPlayer().stopSound(event.getBlock().getSoundGroup().getPlaceSound();
}

@EventHandler
public void onPlace(BlockPlaceEvent event) {
    Bukkit.getScheduler().runTaskLater(Main.getPlugin(), () ->
            event.getPlayer().stopSound(event.getBlock().getSoundGroup().getPlaceSound()), 1);
}
```
### What behaviour is expected:
You shouldn't be able to hear sounds.

### What behaviour is observed:
You heard the sounds regardless.

### How to recreate the issue:
Both methods can be used to recreate the issue

### Plugin list:
Only the plugin I was working on.

### Paper build number:
Build 95 for 1.14.2

**Comment by jacobsandersen** [comment]
Please try to reproduce using an alt and verify that the alt also hears the sound even when the event is canceled. I believe the sound you're hearing is only playing for the local client who placed the block and this is not a paper issue.

**Comment by JustDylan23** [comment]
If someone can confirm that the stopSound method should not have the equivalent results as the stopsound command in minecraft's cli than this issue can be disregarded.

**Comment by JustDylan23** [comment]
I did some messing around with the ingame stop sound command and it appeared to stop the block placing sound

**Comment by loopyd** [comment]
After some thorough testing via this basic BlockEvent plugin (git-paper-95)

main.java

```
package com.lupinedream.soundtest;

import org.bukkit.event.EventHandler;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.PluginManager;
import org.bukkit.plugin.java.JavaPlugin;

public class main extends JavaPlugin {
    private static Plugin plugin;
    private static PluginManager pm;

    @Override
    public void onEnable() {
        plugin = this;
        pm = getServer().getPluginManager();
        pm.registerEvents(new BlockEventsListener(), plugin);
        getLogger().info("Plugin has been enabled!");
    }

    @Override
    public void onDisable() {
        getLogger().info("Plugin disabled!");
    }

    public static Plugin getPlugin() {
        return plugin;
    }

}
```

BlockEventListener.java
```
package com.lupinedream.soundtest;

import org.bukkit.Bukkit;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockPlaceEvent;
import static org.bukkit.Bukkit.getLogger;

public class BlockEventsListener implements Listener {

    @EventHandler
    public void onPlace(BlockPlaceEvent event) {
        getLogger().info("BlockPlaceEvent fired!");
        event.getPlayer().stopSound(event.getBlock().getSoundGroup().getPlaceSound());
    }

    /* @EventHandler
    public void onPlace(BlockPlaceEvent event) {
        getLogger().info("BlockPlaceEvent fired!");
        Bukkit.getScheduler().runTaskLater(main.getPlugin(), () ->
                event.getPlayer().stopSound(event.getBlock().getSoundGroup().getPlaceSound()), 1);
    } */
}
```

**Test 1**
__**git-paper-95 test**__
Control:  Method 1 from the simple plugin source code shared here, jar in plugins folder, using blocks:  dirt, wood, stone.
Result:  Block sound plays, message "BlockPlaceEvent fired!" displays in server log to confirm firing of the event.
Alt result:  Block sound does not play.

**Test 2**
__**git-paper-95 test**__
Control:  Method 2 from the simple plugin source code shared here, jar in plugins folder, using blocks:  dirt, wood, stone.
Result: Block sound plays, message "BlockPlaceEvent fired!" displays in server log to confirm firing of the event.
Alt result:  Block sound does not play.

**Test 3**
__**Vanilla jar test**__
Control:  No plugins loaded.  Ran commands:

`/stopsound @p block minecraft:block.wood.place` 
`/stopsound @p block minecraft:block.stone.place`
`/stopsound @p block minecraft:block.gravel.place`

Result: Block sound plays.
Alt result:  Block sound does not play.

**Test 4**
__**Vanilla jar test**__
Control:  Ran command:

`/stopsound @p `

Result:  Everything EXCEPT the block placing sound was muted.  Music and sound effects where all muted.

Make your inferences from these results.

**Comment by JustDylan23** [comment]
I put the `/stopsound @a` in a repeating command block in my server and it appeard to sometimes stop the block placing sound, since the sound gets fired client side as soon as the block is placed it isn't sync with the command since it is only being fired 20 times a second. I think that in this case there can't be much done because of the awkward timing between the sound and the stopsound.
