### ISSUE TITLE
Incorrect spawner generation eventually crashing server

### ISSUE THREAD

**Issue by Spottedleaf** [PaperMC/Paper#2202]
### Link/paste of stack trace
https://gist.github.com/Spottedleaf/2361557f58e1d0bc3248c522af061148
Warning in console on chunk generation:
`[23:50:03 ERROR]: Failed to fetch mob spawner entity at (2300, 11, 1694)`

### Plugin list:
None

### Actions to reproduce (if known):
> UltraWafflesToday at 11:43 PM
> its just that one
> for now
> apparently its seed base problem
> i made a single player world too see if the problem persist
> it has the same spawner
> seed: -3992479988386776686
> location: 2300 11 1694

Generate a world with seed -3992479988386776686 and teleport to (2300,11,1694) and run a timings report.

### Paper build number:
95

Thanks to UltraWafflesToday on discord for finding the issue was with world generation.

**Comment by dead-battery-games** [comment]
I believe I have a similar issue. Log is attached.

[Crash Report.txt](https://github.com/PaperMC/Paper/files/3639138/Crash.Report.txt)

Currently running Paper version 193.

**Comment by HexedHero** [comment]
Build 214 and I'm having the exact same issue, if for some reason you get a dungeon to spawn with a chest next to the spawner it will completely fuck up the spawners data and make it impossible to remove said spawner even with worldedit.

I have no plugins installed apart from WorldBorder and if I generate a 10k world I normally get at least one of these issues and it completely fucks up the world. Deleting the region file and letting it regen does nothing.

Any known fixes, even using something like MCEdit?

My stacktrace if anyone needs it
https://pastebin.com/raw/xzV7PyXz

**Comment by kickash32** [comment]
Have you tried using `/setblock` to clear it?

**Comment by HexedHero** [comment]
confirmed /setblock does fix the issue

**Comment by AJMFactsheets** [comment]
From my testing, this isn't exclusively a Paper problem. Varying error messages are displayed in chat in all upstream versions.

Vanilla:

> [Server-Worker-7/ERROR]: Failed to fetch mob spawner entity at (2300, 11, 1694)
> [Server thread/WARN]: Block entity invalid: minecraft:chest @ ew{x=2300, y=11, z=1694}

Spigot:

> [Server thread/WARN]: Block entity invalid: minecraft:chest @ BlockPosition{x=2300, y=11, z=1694}

Paper:

> Failed to fetch mob spawner entity at (2300, 11, 1694)



Calling `/data get block 2300 11 1694` on the "mob spawner" gives the following:

> 2300, 11, 1694 has the following block data: {LootTable: "minecraft:chests/simple_dungeon", x: 2300, y: 11, z: 1694, id: "minecraft:chest", LootTableSeed: 1413741608320992051L}

It is also obvious something is awry in-game, since the spawner is shown as the default pig spawner. Moveover, placing grass and torches around it does not cause pigs to actually spawn like it should. It seems that the game has given the mob spawner the tile entity data of a dungeon chest.

I couldn't find a vanilla bug report, but it seems vanilla is the source of this problem. Surely this is an unintended corruption, so a fix would probably be welcomed.

**Comment by HexedHero** [comment]
> From my testing, this isn't exclusively a Paper problem. Varying error messages are displayed in chat in all upstream versions.
> 
> Vanilla:
> 
> > [Server-Worker-7/ERROR]: Failed to fetch mob spawner entity at (2300, 11, 1694)
> > [Server thread/WARN]: Block entity invalid: minecraft:chest @ ew{x=2300, y=11, z=1694}
> 
> Spigot:
> 
> > [Server thread/WARN]: Block entity invalid: minecraft:chest @ BlockPosition{x=2300, y=11, z=1694}
> 
> Paper:
> 
> > Failed to fetch mob spawner entity at (2300, 11, 1694)
> 
> Calling `/data get block 2300 11 1694` on the "mob spawner" gives the following:
> 
> > 2300, 11, 1694 has the following block data: {LootTable: "minecraft:chests/simple_dungeon", x: 2300, y: 11, z: 1694, id: "minecraft:chest", LootTableSeed: 1413741608320992051L}
> 
> It is also obvious something is awry in-game, since the spawner is shown as the default pig spawner. Moveover, placing grass and torches around it does not cause pigs to actually spawn like it should. It seems that the game has given the mob spawner the tile entity data of a dungeon chest.
> 
> I couldn't find a vanilla bug report, but it seems vanilla is the source of this problem. Surely this is an unintended corruption, so a fix would probably be welcomed.

From my testing, in vanilla you at least remove the spawner etc

**Comment by HexedHero** [comment]
I made a vanilla bug report https://bugs.mojang.com/browse/MC-163945

**Comment by HexedHero** [comment]
Recent CraftBukkit update re-added the tile entity fixer so now we can remove the said spawner without any API issues etc but doesn't said the normal gen issue
