### ISSUE TITLE
EntityDismountEvent issue

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#2204]
Hi!

I used a piece of code that works fine in Paper 1.13.2, but now in Paper/Spigot 1.14.2 it does not work correctly. Basically the code what it allows is to avoid being dismounted under water. The issue is that the player get stuck and can't dismount while shifting...

https://pastebin.com/CSGVtT4V

Using paper-96 clean setup, no plugins.

There is something wrong with the code or just still Minecraft 1.14 is a mess? I remember that some time ago when Billy was developing his ridables plugin, something similar happened...

Many thanks and sorry for my english, i'm spanish...

**Comment by caojohnny** [comment]
You're adding the player as a passenger multiple times

**Comment by lordrius** [comment]
Oh my! I forgot to specify which hand in the PlayerInteractEntityEvent... Now is working fine, sorry and many thanks!
