### ISSUE TITLE
setCanPickupItems ignored for some mobs

### ISSUE THREAD

**Issue by kangarko** [PaperMC/Paper#2205]
Paper 1.14.2 build 96
More info here: https://github.com/kangarko/Boss/issues/312

Basically, the flag setCanPickupItems seems to be ignored for some mobs. Here is a description reported by one of my customers:

```
All of the illager bosses I have made are picking up my members items and upon death, they do not drop them. We tried to enable a gamerule so mob grief is permanently disabled, but it is only making it worse (they still pick up the weapons), not sure what's going on and I have had to give them back their items via spawning.

It happened again, but strangely enough, with a Spider and Stray Skeleton lol.
```

**Comment by caojohnny** [comment]
So far as I am able to tell, both `mobGriefing` and `LivingEntity#getCanPickupItems()` have to be true in order to be able to naturally pickup items in the first place, so the fact that setting the former to `false` making things worse doesn't really make any sense.

**Comment by kangarko** [comment]
I see, I added a listener for entity pickup along with debug messages to my plugin, we will see what the user will report. I am pretty sure he has mobGriefing enabled (?).

**Comment by zachbr** [comment]
We are aware of at least one case in which vanilla does not check it for raiders. Going to treat as a bug.

From one of the internal channels:


![72962FA5-3450-4A45-B5D9-3EED272B4016](https://user-images.githubusercontent.com/1254957/59936208-10e24880-9415-11e9-9ef9-2ec6a908a399.jpeg)

**Comment by kangarko** [comment]
Thanks for professional and responsive input!
