### ISSUE TITLE
Errors in console with new blocks 1.14.2

### ISSUE THREAD

**Issue by JavituRec** [PaperMC/Paper#2207]
I have errors in start server with blocks:

[Server thread/ERROR]: Error creating legacy block: acacia_button. Possibly a new block.
[Server thread/ERROR]: Error creating legacy block: acacia_pressure_plate. Possibly a new block.
[Server thread/ERROR]: Error creating legacy block: acacia_sign. Possibly a new block.

Full error: https://pastebin.com/QNtPVYt0

Version of paper: paper_87

All the best.

**Comment by electronicboy** [comment]
You missed the template, nor is that a message printed by the server itself
