### ISSUE TITLE
1.14: Readd Anti Xray

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#2209]
## Request
Anti-Xray patch was removed in 1.14, needs to be re-added 😃 
0235-Anti-Xray.patch

## GoFundMe Campaign
There is a monetary reward for the contributor that makes this request happen. See all details regarding the reward on the GoFundMe page.
https://www.gofundme.com/f/readd-paper-antixray

## GoFundMe Goal Completion:
**$100 of 100** contributed for the July 10th deadline.

**Comment by kashike** [comment]
@stonar96

**Comment by arturek1666** [comment]
yeah I agree as x-ray is simple to get for all mc version just by intalling texturepack xD. This should be added to 1.14.X as fast as posible xD

**Comment by Tim269** [comment]
I like the idea but no paypal as payment is horrible :(

**Comment by CeIebrimbor** [comment]
@schneidertm
You mean GoFundMe not allowing PayPal? Can’t do much about that.

**Comment by 0-x-2-2** [comment]
> yeah I agree as x-ray is simple to get for all mc version just by intalling texturepack xD. This should be added to 1.14.X as fast as posible xD

xray texture packs don't work very well because of cave culling that was added in 1.8

**Comment by Black-Hole** [comment]
> xray texture packs don't work very well because of cave culling that was added in 1.8

Optifine offers more than enough features for those resource packs.

**Comment by CeIebrimbor** [comment]
Build 127
