### ISSUE TITLE
Droped Items disappearing on death, but dropped Exp remains on the floor.

### ISSUE THREAD

**Issue by sixamscrew** [PaperMC/Paper#2214]
### What behaviour is expected:
___Players dying and then walking back to their death spot, and getting their items back.___

### What behaviour is observed:
___The items automatically disappeared, even with the /back command from EssentialsX plugin. However dropped Exp didn't disappear.___

### Steps/models to reproduce:
___Player dies,  goes back to deah spot to get items, items automatically disappear, but exp dropped remains___

### Plugin list:
___EssentialsX, GriefPrevention, McMMO, GroupManager, ClearLag, EscapeLag, ChestShop___

### Paper build number:
___97.___

### Anything else:
___Just started happening this yesterday, when I switched from spigot to paperspigot. Server version 1.14.2___

**Comment by Spottedleaf** [comment]
Can't produce locally.

**Comment by sixamscrew** [comment]
Sorry, I dindn't understand you.

**Comment by MiniDigger** [comment]
He said that the can't reproduce your issue. So most likely this is caused by your plugins. Try removing ClearLag and EscapeLag and see if it still occurs.

**Comment by sixamscrew** [comment]
Sorry, removed the plugins, same thing happening

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
