### ISSUE TITLE
Area effect clouds (lingering potion entities) despawn immediately with an undefined radius or a radius < 0.5

### ISSUE THREAD

**Issue by GoldenDelicios** [PaperMC/Paper#2221]
### What behaviour is expected:
Summoning an area_effect_cloud without defining the Radius (defaults to 0.0) or defining the Radius as < 0.5 should last as long as its Age < (Duration + WaitTime). This is vanilla behavior that is very useful for datapacks that need marker entities, and until recently worked on Paper.

### What behaviour is observed:
Summoning such a cloud will despawn almost immediately.

### Steps/models to reproduce:
* Run `/summon area_effect_cloud ~ ~ ~ {Duration:1200}`, and have F3+B to show entity bounding boxes. Observe that it despawns instantly on Paper, but lasts a minute in vanilla.
* Run `/summon area_effect_cloud ~ ~ ~ {Duration:1200, Radius:0.49}`. Observe the same results
* Run `/summon area_effect_cloud ~ ~ ~ {Duration:1200, Radius:0.5}`. Observe that it correctly lasts a minute on both Paper and vanilla.

### Plugin list:
No plugins

### Paper build number:
Paper 105, Minecraft 1.14.2. Also appeared in recent 1.13 builds.

### Anything else:
___Anything else you think may help us resolve the problem___
I believe this may be a result of fixing MC-114618 in recent 1.13 and 1.14 builds. In my view, the fix should remove clouds when they have a negative radius (less than 0.0) instead of when their radius is less than 0.5.

Edit: This seems to be the relevant Paper issue: https://github.com/PaperMC/Paper/issues/2088

**Comment by electronicboy** [comment]
Behavior of this is based around vanilla code: https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0441-MC-114618-Fix-EntityAreaEffectCloud-from-going-negat.patch#L32

**Comment by GoldenDelicios** [comment]
If I've understood the code correctly, the major difference is that in vanilla, the radius-based despawning only happens when radiusPerTick != 0.0 (i.e. the cloud is neither growing nor shrinking when an entity is standing in it). Taking the radius-based check outside of that conditional makes using small AreaEffectClouds as permanent entities (for custom maps or for datapacks) impossible for longer than a game tick, and in itself should be considered a bug as this is commonly used vanilla behavior.

**Comment by MiniDigger** [comment]
@GoldenDelicios did #2223 fix your issue? If so, this can be closed :)

**Comment by zachbr** [comment]
This is awaiting a backport to 1.13.2 as well. I’ll close it when that is done.

**Comment by GoldenDelicios** [comment]
@MiniDigger The issue has been fixed in the 1.14 builds, yes :)

**Comment by zachbr** [comment]
Backported to 1.13.2 as well.
