### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by DaniGTA** [PaperMC/Paper#2222]
### Link/paste of stack trace

Look at the files pls.

### Plugin list:
- Dynmap
- LuckPerm

### Actions to reproduce (if known):
Join in a Raid i think.

### Paper build number:
94
[crash-2019-06-23_00.46.27-server.txt](https://github.com/PaperMC/Paper/files/3317691/crash-2019-06-23_00.46.27-server.txt)
[2019-06-23-1.log](https://github.com/PaperMC/Paper/files/3317692/2019-06-23-1.log)

**Comment by electronicboy** [comment]
Vanilla issue fixed in 1.14.3 (They broke it in another way in .3, but we have that fixed too)
