### ISSUE TITLE
The server crashed, it seems, because of the timings.

### ISSUE THREAD

**Issue by BoomEaro** [PaperMC/Paper#2228]
### Link/paste of stack trace
https://pastebin.com/GBzyCPin

### Plugin list:
AdvancedAchievements, AdvBans, AgentPrefix, AutoSaveWorld, BigLogger, BlocksHub, Board, BungeeTabListPlus, CES, Chairs, ChatChecker, ChestCommands, Citizens, ClearLag, CommandBlockProtect, CoreProtect, CraftBook, CrazyAuctions, CrazyDebuger, DynPad, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, HideStream, HolographicDisplays, InterceptCommands, ItemFixer, Jail, Jobs, MenuMaker, MultiWorld, MyPet, NoCheatPlus, OpenInv, Orebfuscator4, PandaWire, PermissionsEx, PlaceholderAPI, PlayerUtils, PortalProtect, ProtocolLib, PvPAssistant, RegionTrade, Scavenger, SFE, SimpleClans, SimpleParkour3, SuperEffects, TrophyHeads, Vault, ViaVersion, WgAddon, WGExtender, WorldBorder, WorldEdit, WorldGuard

### Actions to reproduce (if known):
I turned on the timings, I decided to just fly around the world and the server closed.

### Paper build number:
This server is running Paper version git-Paper-1615 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by aikar** [comment]
nothing in that relates to timings. Mojang has concurrency bugs in that code in vanilla and that looks to be the source of the crash

**Comment by BoomEaro** [comment]
Maybe I was mistaken, saying that the matter is in timings. But I'm worried about this line:
at co.aikar.timings.TimedChunkGenerator.recreateStructures(TimedChunkGenerator.java:100) ~[patched_1.12.2.jar:git-Paper-1615]

(I have never used paper before, and have not seen a similar error on a regular spigot, therefore, I made such conclusions.)

**Comment by aikar** [comment]
that is just a middleware to be able to time mojangs code. it does not alter behavior.

**Comment by BoomEaro** [comment]
This error is peculiar only to 1.12.2 or is it on all versions of the game?
