### ISSUE TITLE
1.14.3 Maps seem to be broken

### ISSUE THREAD

**Issue by partydev** [PaperMC/Paper#2229]
### What behaviour is expected:
Maps working properly.

### What behaviour is observed:
Maps not saving any information, 'flickering'.
https://i.gyazo.com/b62b81dfd3e80bb1af96aaa1a77423aa.mp4

### Steps/models to reproduce:
Launch a 1.14.3 server, hold a map.

### Plugin list:
N/A

### Paper build number:
108

### Additional Information:
Not tested in Spigot

**Comment by flanigomik** [comment]
if you have advanced tool tips turned on, you can see map items rapidly swapping between map IDs.

**Comment by electronicboy** [comment]
Fixed in 110+ (I lied, not 109+)
