### ISSUE TITLE
EssentialsX plugin won't load anymore as of build 108

### ISSUE THREAD

**Issue by ShadowFlare** [PaperMC/Paper#2231]
### What behaviour is observed:
EssentialsX plugin would load on build 107 for MC 1.14.2 (though warns about incorrect server version) and functions for what I use it for, but it errors and doesn't load as of build 108 for MC 1.14.3.

### Plugin list:
Vault v1.7.2-b107
EssentialsX v2.16.1.0 (with matching EssentialsProtect plugin)
LuckPerms v4.4.26

### Paper build number:
Build 108 for Minecraft 1.14.3

**Comment by zachbr** [comment]
https://github.com/PaperMC/Paper/commit/56ee5647abdf74c4b85d0f555a43850d805f6753#commitcomment-34064309

Spigot changed the version string. EssentialsX cannot understand it and fails to load. AFAIK they have a PR to fix it and are generally aware of the issue.

**Comment by ShadowFlare** [comment]
Ah, I see.  Thanks for the prompt reply.  I reported it here because I thought maybe there was some problem with the merge of the Spigot changes.
