### ISSUE TITLE
Unable to tame horses and donkeys

### ISSUE THREAD

**Issue by Gijs-Hooghiemstra** [PaperMC/Paper#2234]
Just downloaded the build 110 and I was unable to tame horses and donkeys. I was able to do it in the latest version of spigot. I don't know what causes the problem :(

**Comment by mikroskeem** [comment]
Fill the form... it's not here for nothing ;)

**Comment by Arkerras** [comment]
I'm having the same issue.

### What behaviour is expected:

Horse to buck player off after mounting to tame

### What behaviour is observed:

No issues mounting the horse initially however the horse doesn't buck players off or move (it only rotates) and no taming animation occuring.  Repetitive attempts to mount or feed the horse don't seem to make a difference.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Find a horse, mount the horse, notice no movement or bucking. Repeat as many times as you like

### Plugin list:

McMMO latest
DynMap latest

### Paper build number:

 git-Paper-115 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by brr3** [comment]
Exact same thing as @Arkerras explained is happening for me. I am however using way more plugins.

**Plugin list:**
Announcer, AreaShop, BuycraftX, ChatColor2, ChestShop, ChestShopNotifier, ConsoleSpamFix, CoreProtect, Craftconomy3, DiscordSRV, dynmap, Essentials, EssentialsSpawn, GroupManager, Multiverse-Core, Multiverse-NetherPortals, MyHome, MyWarp, OnTime, OpenInv, PlaceholderAPI, PluginConstructorAPI, ProtocolLib, RewardSign, ServerRestorer, SignBoard, Statscraft, StreetlightsAdvanced, SuperLogger, TimeVote, VanishNoPacket, Vault, VentureChat, Votifier, VotingPlugin, WeatherVote, WorldEdit, WorldGuard

**Paper build number:**
114 (MC: 1.14.3)

Pretty sure this worked in the 1.14.2 builds as I did not get any complaints then from my players.

**Comment by zachbr** [comment]
Can this be re-tested now that the other issue with passives is fixed?

I’m fairly sure this is fixed but would like confirmation on latest. Thanks

**Comment by Spottedleaf** [comment]
resolved as of latet

**Comment by zachbr** [comment]
GH-2232

Closing as fixed
