### ISSUE TITLE
Wither Skeletons not scared of tamed wolf 1.14.3

### ISSUE THREAD

**Issue by EliasLahham** [PaperMC/Paper#2236]
### What behaviour is expected:
The wither skeleton is supposed to see the dog and run away from it.

### What behaviour is observed:
The wither skeleton has clear view of the dog but just stands there. Tested this in vanilla 1.14.3 and it works fine, but not in paper.

### Steps/models to reproduce:
My setup include a dog on a slab with trapdoors around it and one slab above it. I'm using this guide for my wither skeleton farm: https://www.youtube.com/watch?v=OxUIJcTcokw

### Plugin list:
 n/a

### Paper build number:
1.14.3

### Anything else:
Have not checked other mobs like creepers + cats, etc..

**Comment by CeIebrimbor** [comment]
Duplcate of #2232?

**Comment by electronicboy** [comment]
Duplicate of #2232

**Comment by Blazzike** [comment]
This has not been resolved. Seems to only apply to wither skeletons.
