### ISSUE TITLE
Citizens Error

### ISSUE THREAD

**Issue by alan67160** [PaperMC/Paper#2239]
### What behaviour is expected:
citizensn plugin work

### What behaviour is observed:
give error and not spawning npc

### Steps/models to reproduce:
25.06 23:59:38 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.06 23:59:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904)
25.06 23:59:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060)
25.06 23:59:38 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
25.06 23:59:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177)
25.06 23:59:38 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)
25.06 23:59:38 [Server] WARN at net.minecraft.server.v1_14_R1.World.a(World.java:895)
25.06 23:59:38 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579)
25.06 23:59:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
25.06 23:59:38 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:314)
25.06 23:59:38 [Server] WARN at net.citizensnpcs.util.NMS.trySwim(NMS.java:421)
25.06 23:59:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096)
25.06 23:59:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104)
25.06 23:59:38 [Server] WARN java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.ay()Z
25.06 23:59:38 [Server] WARN Entity threw exception at world:102.5,64.5,-400.5
25.06 23:59:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
25.06 23:59:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-58]
25.06 23:59:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-58]
25.06 23:59:36 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-58]
25.06 23:59:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-58]
25.06 23:59:36 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-58]
25.06 23:59:36 [Server] INFO at net.minecraft.server.v1_14_R1.World.a(World.java:907) ~[patched_1.14.2.jar:git-Paper-58]
25.06 23:59:36 [Server] INFO at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.2.jar:git-Paper-58]
25.06 23:59:36 [Server] INFO at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.2.jar:git-Paper-58]
25.06 23:59:36 [Server] INFO java.lang.Throwable: null
25.06 23:59:36 [Server] ERROR TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)

### Plugin list:
Plugins (29): ActionHealth*, AutoMessage*, betterSleeping*, Citizens, ClearLag, CMI, CoreProtect, DeluxeChat, DiscordSRV, HeadDatabase*, HolographicDisplays, LiteBans, LockettePro, LuckPerms, Multiverse-Core*, MyPet, OreBroadcast*, PlaceholderAPI*, ProtocolLib*, QuickShop, Residence, Shopkeepers, SuperVanish, TitleManager*, TreeGravity, Vault*, ViaVersion*, WorldEdit, WorldGuard

### Paper build number:
This server is running Paper version git-Paper-58 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-110 (MC: 1.14.3)
You are 49 version(s) behind

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by electronicboy** [comment]
Update citizens

**Comment by alan67160** [comment]
https://ci.citizensnpcs.co/job/Citizens2/
this is the last build of Citizens2

**Comment by alan67160** [comment]
Citizens-2.0.25-b1706.jar

**Comment by electronicboy** [comment]
Oh, I got the version mixed up, your version of citizens is too new for that version of the server

**Comment by alan67160** [comment]
What citizens version should I use?

**Comment by 0-x-2-2** [comment]
Update paper.
