### ISSUE TITLE
1.14.3 MOB Performance problem

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#2241]
i have paper 1.14.3 #114 version.

When the mobs erase tps rise, tps performance falls.

The video is here: https://youtu.be/sCoaAzBja7Q

Can you solve this problem?

**Comment by supertakeru** [comment]
Video doesn't work

**Comment by successed** [comment]
> Video doesn't work

Sorry, retry please.

**Comment by MiniDigger** [comment]
timings link? that video is useless

**Comment by successed** [comment]
> timings link? that video is useless

https://timings.aikar.co/?id=00bc55792cbc45a5a0c6422053717f69

**Comment by ghost** [comment]
I have exactly the same problem, it also ignores limits set in spawn-limits and thousands of mobs are revived.

**Comment by successed** [comment]
> I have exactly the same problem, it also ignores limits set in spawn-limits and thousands of mobs are revived.

Yeah, they are born excessively.

**Comment by ghost** [comment]
Will they fix it?
After checking thoroughly, I find that the server ignores this: ticks-per (monster-spawns) even if set to 2000, it is a REUNION of millions of mobs.

**Comment by successed** [comment]
> Will they fix it?
> After checking thoroughly, I find that the server ignores this: ticks-per (monster-spawns) even if set to 2000, it is a REUNION of millions of mobs.

they have not responded to any.

**Comment by ghost** [comment]
It's not bad just...

**Comment by successed** [comment]
> It's not bad just...

There is verry verry bad mean, we have chunk load problem..

**Comment by Primorior** [comment]
Having the same problem
