### ISSUE TITLE
Error message in console regarding Citizens plugin

### ISSUE THREAD

**Issue by Zoneman1972** [PaperMC/Paper#2246]
### Link/paste of stack trace

https://pastebin.com/EQhVPVGH

### Plugin list:
Citizens

### Actions to reproduce (if known):

Load the server with Paper version 114 and Citizens Version 2.0.25-b 1703

### Paper build number:
This server is running Paper version git-Paper-114 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-107 (MC: 1.14.2)
You are 1 version(s) behind

**Comment by Prof-Bloodstone** [comment]
`Citizens Version 2.0.25-b 1703` is for 1.14.2, from what I can see. You need to update Citizens.

**Comment by Zoneman1972** [comment]
I tried that and it’s still giving the error.
