### ISSUE TITLE
Citizens errors

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2248]
So the 1.14.3 pappermc builds doesnt work with citizens. currently got the latests citizens build which is for 1.14.3. I've reported this before but i've been told its a problem with citizens which I belive is not the issue. NPCs arent visble at all. 

### Steps/models to reproduce:
Start server

### Plugin list:
Citizens

### Paper build number:
27.06 19:09:49 [Server] INFO This server is running Paper version git-Paper-115 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

### Anything else:
27.06 19:13:38 [Server] INFO Smirren issued server command: /citizens reload
27.06 19:13:38 [Server] WARN Entity threw exception at world:-137.0012,68.0,265.4988
27.06 19:13:38 [Server] WARN java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.at()Z
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.util.NMS.trySwim(NMS.java:421)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:314)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.World.a(World.java:933)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
27.06 19:13:38 [Server] WARN at java.lang.Thread.run(Thread.java:748)
27.06 19:13:38 [Server] ERROR [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
27.06 19:13:38 [Server] INFO java.lang.Throwable: null
27.06 19:13:38 [Server] INFO at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.World.a(World.java:945) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
27.06 19:13:38 [Server] WARN Entity threw exception at world:-135.5081,68.0,263.9864
27.06 19:13:38 [Server] WARN java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.at()Z
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.util.NMS.trySwim(NMS.java:421)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:314)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.World.a(World.java:933)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
27.06 19:13:38 [Server] WARN at java.lang.Thread.run(Thread.java:748)
27.06 19:13:38 [Server] ERROR [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
27.06 19:13:38 [Server] INFO java.lang.Throwable: null
27.06 19:13:38 [Server] INFO at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.World.a(World.java:945) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
27.06 19:13:38 [Server] WARN Entity threw exception at world:-135.9958,68.0,277.9868
27.06 19:13:38 [Server] WARN java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.at()Z
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.util.NMS.trySwim(NMS.java:421)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:314)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.World.a(World.java:933)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
27.06 19:13:38 [Server] WARN at java.lang.Thread.run(Thread.java:748)
27.06 19:13:38 [Server] ERROR [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
27.06 19:13:38 [Server] INFO java.lang.Throwable: null
27.06 19:13:38 [Server] INFO at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.World.a(World.java:945) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
27.06 19:13:38 [Server] WARN Entity threw exception at world:-122.8691,68.0,278.0899
27.06 19:13:38 [Server] WARN java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.at()Z
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.util.NMS.trySwim(NMS.java:421)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:314)
27.06 19:13:38 [Server] WARN at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.World.a(World.java:933)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
27.06 19:13:38 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
27.06 19:13:38 [Server] WARN at java.lang.Thread.run(Thread.java:748)
27.06 19:13:38 [Server] ERROR [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
27.06 19:13:38 [Server] INFO java.lang.Throwable: null
27.06 19:13:38 [Server] INFO at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.World.a(World.java:945) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-115]
27.06 19:13:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by MiniDigger** [comment]
mappings update, citizens needs to update.

**Comment by ghost** [comment]
thats sucks. they are kinda slow at it..

**Comment by CeIebrimbor** [comment]
Latest from Spigot (1.14.2) or latest from https://ci.citizensnpcs.co/job/Citizens2/
