### ISSUE TITLE
Minecraft::world - syncChunkLoad lag

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#225]
# Performance issue
### Timings or Profile link:

http://timings.aikar.co/v2/?id=e25461448579422e96d6bbe621366363&start=1461170215&end=1461170619
### Plugin list:

http://timings.aikar.co/v2/?id=e25461448579422e96d6bbe621366363&start=1461170215&end=1461170619&section=plugins
### bukkit.yml, spigot.yml, paper.yml, server.properties

http://timings.aikar.co/v2/?id=e25461448579422e96d6bbe621366363&start=1461170215&end=1461170619&section=config
server.properties: http://pastebin.com/kXB3Ejdv
### Paper build number:

git-Paper-689 (MC: 1.9.2)

**Comment by aikar** [comment]
Updating should resolve issues as a catch-all bandaid was added to upstream

**Comment by zachbr** [comment]
Closing as resolved, comment if necessary
