### ISSUE TITLE
PlayerInteractEvent not firing correctly.

### ISSUE THREAD

**Issue by Ajaxan** [PaperMC/Paper#2250]
### What behaviour is expected:
The PlayerInteractEvent triggers when you left click a block or air (among other triggers). It only stops triggering if you hit an entity. If you are too far away from the entity to hit it, the event should fire because you are still hitting air.

### What behaviour is observed:
Under specific circumstances the last sentence in what is expected behavior doesn't occur. Here are the specific conditions:
- Be in survival mode
- Holding a weapon
- Left Clicking on an entity
- Entity outside survival range for left clicking
- Entity inside creative range for left clicking

It should be noted that this doesn't cover the full spectrum of the range different between survival and creative. It's only the inner part of the range difference. 

### Steps/models to reproduce:
- Creating a simple plugin with an event listener to monitor the PlayerInteractEvent
- Add some logging code to know when the event is triggered. (can also be useful to include the distance between you and the nearest entity for monitoring if you are on either side of the blind spot of the event.)
- Start far away from the entity, and slowly approach it left clicking ever tiny step forward while in survival. The event will stop responding when you get close to the entity but are not yet within striking range for survival. This only happens in survival.
- A distance of 3.5 - 3.6 blocks seems to be the sweet spot.

### Plugin list:
PIETest.jar (Ran a clean server with only this plugin to confirm)

### Paper build number:
version git-Paper-636 (MC: 1.13.2)

### Anything else:
I can send tiny test plugin I used for convenience if wanted. Just ping me in the Paper Discord (Ajaxan#5642) or let me know if you'd prefer a dropbox link or similar in the issue ticket here. This is the full code of the test jar: https://pastebin.com/HHi2TBw9

**Comment by Black-Hole** [comment]
If you don't get a PlayerInteractEvent, then the client didn't send a packet. You might want to report to the Mojang issue tracker that you want the client to always send the packet.

**Comment by Ajaxan** [comment]
This does not seem to be the case. I added a ProtocolLib Packet Listener and some adjustments to the test plugin code. I will always get the arm swing packet but inside the conditions I mentioned above the PIE will not fire.

I understand that this isn't a high priority bug, and as a result I can simply use the packet to catch the event and handle it that way if this isn't believed to be worth the effort to attempt to fix or is outside the scope of what the API should do.

**Comment by kickash32** [comment]
I believe this is outside the scope of the API, as the firing of an event signifies something has happend or will happen, but in this case nothing happens whether the event goes through cancelled or otherwise. Whether the client sends a packet for the invalid attack is an implementation detailed, best handled by a protocol lib.

**Comment by Ajaxan** [comment]
I'd disagree. Based on the that fact the PIE fires when you swing at AIR which itself inherently means nothing happens this is essentially the same thing. This is more of making that event more consistent by removing a dead zone that occurs when you click air in front of an entity.

**Comment by Brokkonaut** [comment]
imo its an api bug. a packet from the client is always sent, but unter certain conditions no event is fired (while it is normally fired when clicking air or clicking at entities/blocks in range)
