### ISSUE TITLE
timings talk about lag while saving players, even when there are 0 players on the server

### ISSUE THREAD

**Issue by DmitriyDy** [PaperMC/Paper#2252]
I get lag spike on Save players at "player-auto-save-rate: 1200" and "max-player-auto-save-per-tick: 1". For all time in timings this ~5% server tps. But every 1200 ticks this 99% server tps.
Last timings with 0 players on server. This is not an isolated case. So for several days. And my tps always 19.99 and less
https://timings.aikar.co/?id=0fa728740ae04385b6e86c058a5fdbef

UPD:
More timings. https://timings.aikar.co/?id=8d63a5131d124912ab38829c199d224c

**Comment by RikoDEV** [comment]
Same problem here, but with chunk unload. 0 players on the server and empty world generator. (Paper 1.14.3)

https://timings.aikar.co/?id=db8c189c5bb945b8b6f2bbb731dc6819
