### ISSUE TITLE
Unknown server crash

### ISSUE THREAD

**Issue by KarlPro123** [PaperMC/Paper#2254]
Hi!

So my server is having crash problems in the last weeks, and I can't read anything out from the crash reports. Could anyone help me?

https://pastebin.com/hazt6FA2

**Comment by BillyGalbreath** [comment]
![image](https://user-images.githubusercontent.com/332527/60336201-4e8b2800-9965-11e9-931b-0be190924835.png)
![image](https://user-images.githubusercontent.com/332527/60336246-78dce580-9965-11e9-960a-068bca3962fb.png)

**Comment by KarlPro123** [comment]
I tried disabling Jobs, lets see if it crashes

**Comment by electronicboy** [comment]
either an issue with jobs (or something else in the tick taking too long) or potential packet spam
