### ISSUE TITLE
Console spam minecraft:air

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#2259]
### What behaviour is expected:
we need fix the console spam

### What behaviour is observed:
console picture: http://prntscr.com/o8fcd7

### Plugin list:
this not a plugin message. i try default server this work on the console spam

### Paper build number:
#117 1.14.3

### Anything else:
Unable to resolve BlockEntity for ItemStack: minecraft:air

**Comment by KisaragiEffective** [comment]
NOTE: There's plugin for log filter, like [Console Spam Fix](https://www.spigotmc.org/resources/console-spam-fix.18410/)

**Comment by BillyGalbreath** [comment]
The message is displayed because you have a plugin or datapack that is using outdated nbt.

Using a plugin like "console spam fix" isn't a fix. It's just hiding a real problem by filtering out messages you should be seeing.

**Comment by mazunki** [comment]
I have the same problem/warning while forceUpgrading the chunks of my world. What causes this?

**Comment by ActuallyVieja** [comment]
Me too, While force-updating 1.16.1 Does it actually have any impact on gameplay / Corrupt chunks?

**Comment by Strahilchu** [comment]
Just got a bunch of these while generating world with Chunky on Paper 1.16.3 #195
I doubt its anything corrupt its just some bug idk, world is fine I can flyspeed 10 to the world border with zero tps drops or errors

**Comment by Chew** [comment]
"It is perfectly normal to see these and will have no impact on your game. Mojang uses a program called DataFixerUpper (DFU) which unfortunately isn't the greatest. Any time this shows up, it's likely an error on their end when handling upgrades."
