### ISSUE TITLE
Mobs disappearing through portals undrr specific circumstances.

### ISSUE THREAD

**Issue by Vonr** [PaperMC/Paper#2261]
### What behaviour is expected:
___What you expected to see___
Mobs going through a nether portal in the overworld to the nether while there is a player in the nether (but not loading the exit portal) do not disappear.
### What behaviour is observed:
___What you actually saw___
The mobs either disappeared in the nether or did not go into the nether at all and disappeared in the portal in the overworld.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
1. Build 2 portals, one in the overworld and one in the nether and link them (look at youtube)
2. Have a player in the nether but not load the chunks of the exit nether portal.
3. Push a mob through the portal, I used a blaze in my tests.
4. Go through the nether portal.
5. Notice that the mob is nowhere to be seen in the nether.
_EXTENDED:_
6. Move the player in the nether beside your exit nether portal
7. Push another mob through the portal in the overworld.
8. Notice that the mob is easily seen in the nether. This should be the case even without a player in the nether.

### Plugin list:
___A list of your plugins___
Nothing.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
Paper 1.14.3 build 118

### Anything else:
___Anything else you think may help us resolve the problem___
Unfortunately not.

**Comment by Vonr** [comment]
seems to be vanilla behaviour but I would still consider this a bug, please fix.

**Comment by aeonlamb** [comment]
This is not a bug. The mob despawns once it's on the other side of the portal because there are no players within 128 blocks, so it instantly despawns. If there is a player there then it won't despawn. Totally normal & expected behavior

**Comment by ArchmageInc** [comment]
That sort of puts a damper on the "Monsters Hunted" and "Uneasy Alliance" advancements.

**Comment by NBS-Paste** [comment]
> This is not a bug. The mob despawns once it's on the other side of the portal because there are no players within 128 blocks, so it instantly despawns. If there is a player there then it won't despawn. Totally normal & expected behavior

Would a chunk loader work as well or does it have to be a player?
Also is there a way I could not have a player so when no one else is on the farm still works?

**Comment by NBS-Paste** [comment]
> This is not a bug. The mob despawns once it's on the other side of the portal because there are no players within 128 blocks, so it instantly despawns. If there is a player there then it won't despawn. Totally normal & expected behavior

I just tries this and it wasn't working.

**Comment by NBS-Paste** [comment]
> This is not a bug. The mob despawns once it's on the other side of the portal because there are no players within 128 blocks, so it instantly despawns. If there is a player there then it won't despawn. Totally normal & expected behavior

Is there a way to stop this.

**Comment by Endernite** [comment]
I have the same problem how can you disable that?

**Comment by ArchmageInc** [comment]
> I have the same problem how can you disable that?

@Endernite The only way I've found is to use a name tag.

**Comment by NBS-Paste** [comment]
> > I have the same problem how can you disable that?
> 
> @Endernite The only way I've found is to use a name tag.

But we can’t name tag every mob that goes through a mob farm.
