### ISSUE TITLE
The map/chunks don't load properly

### ISSUE THREAD

**Issue by LucidAPs** [PaperMC/Paper#2265]
### What behaviour is expected:
I expected to see what i always see which is the map loading properly.

### What behaviour is observed:
I saw the map getting stuck and players unable to move through the unloaded chunks.

### Steps/models to reproduce:
Just walking around past the original spawn point, https://imgur.com/KARhXaV

### Plugin list:
ActionHealth3.3.1
AutomaticInventory
BetterChairs
JEssentials+V1.5.9
LuckPerms-Bukkit-4.4.1
MOTD
PlaceholderAPI-2.10.3
SecondNature_1.0.0.1
SinglePlayerSleep-2.13.21
TAB v2.4.10
Vault
worldedit-bukkit-7.0.0
worldguard-bukkit-7.0.1-beta-01

### Paper build number:
#119

**Comment by MiniDigger** [comment]
Can you attack a chunk debug log? I don't remember the command, it's under /paper

**Comment by RZzHh** [comment]
A similar problem has arisen since the #115 release. Remote transfer or TP, the unloaded block cannot be loaded automatically, the player is stuck in a blank area, and the socket has a similar problem. It is recommended to use #114 temporarily.

**Comment by Spottedleaf** [comment]
provide a debug log when this occurs from /paper debug chunks

**Comment by vincewip** [comment]
similar problems still happening on paper build #127
plugins in use: CoreProtect, PlaceholderAPI, TabList, WorldBorder
screenshot: https://i.imgur.com/dYBFKSj.png
debug log: [chunks-2019-07-11_00.36.33.txt](https://github.com/PaperMC/Paper/files/3380265/chunks-2019-07-11_00.36.33.txt)

hope this helps.

**Comment by Spottedleaf** [comment]
I don't see player tickets around the player in that log - which means something has gone terribly wrong. Any steps you noticed to produce this?

**Comment by vincewip** [comment]
nothing really, all i did was log in to my server and walk around for a while until i saw that chunks stopped loading. the server doesn't throw any error messages either. 

as suggested above by PFCraft-box downgrading to #114 seems to fix the issue...
