### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Zoneman1972** [PaperMC/Paper#2268]
### Link/paste of stack trace

http://prntscr.com/o8vkij

### Plugin list:
CMI 8.6.5.4
Holograms 2.8
Crazy Envoy 1.3.5

### Actions to reproduce (if known):

Let the Crazy Envoy start with no players in the area

The error starts spamming console when the Crazy Envoy starts up and there are no players in the Envoy Arena or the chunks of the Arena are unloaded.
(The chests utilise Holograms over them.)
 As soon as a player warps to the Envoy arena, the errors stop.

### Paper build number:
This server is running Paper version git-Paper-120 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-114 (MC: 1.14.3)
You are running the latest version

**Comment by electronicboy** [comment]
Issue with timings is more than likely just a side effect of an earlier
exception, we need more logs

**Comment by Zoneman1972** [comment]
Trust me, there is nothing in the log apart from the initial server start up and then when an Envoy event starts the error starts and repeats over and over until someone actually uses the warp command to enter the arena.

I have made 2 edited versions of the logs to show exactly what I mean.

[Holograms-paper error.txt](https://github.com/PaperMC/Paper/files/3348547/Holograms-paper.error.txt)
[Envoy attended so no error.txt](https://github.com/PaperMC/Paper/files/3348548/Envoy.attended.so.no.error.txt)

I have tried to paste the logs here, but they are too large. I tried to put them to pastebin, they are also too large for there.
So, believe me when I say that this error is coming from Holograms 2.8 activating in unloaded or inactive chunks and as the additional error states, report to paper.
