### ISSUE TITLE
Skeleton horse bug

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#227]
https://www.youtube.com/watch?v=maMjC1laeDc
### Plugin list:

http://timings.aikar.co/v2/?id=e25461448579422e96d6bbe621366363&start=1461170215&end=1461170619&section=plugins
### bukkit.yml, spigot.yml, paper.yml, server.properties

http://timings.aikar.co/v2/?id=e25461448579422e96d6bbe621366363&start=1461170215&end=1461170619&section=config
server.properties: http://pastebin.com/kXB3Ejdv
### Paper build number:

git-Paper-689 (MC: 1.9.2)

**Comment by hurrgurl** [comment]
What if you do it in survival as a normal player?

**Comment by zachbr** [comment]
Looks like an issue with your client not seeing them as mounted after you move outside of range.
I  assume you relog and they're back right where they're supposed to be, mounted on the horses?
I believe @aikar is working on a fix to this and similar vehicle desync issues.

**Comment by zachbr** [comment]
https://bugs.mojang.com/browse/MC-96954

**Comment by zachbr** [comment]
I believe this was fixed with 53abbfdc4c1832973ed17145060436ad1ab6f5fe
