### ISSUE TITLE
1.14.4 TODO

### ISSUE THREAD

**Issue by zachbr** [PaperMC/Paper#2271]
*Meta ticket for small changes slated to come with 1.14.4*

**Comment by zachbr** [comment]
- [x]  ~~Bump Paper-Server JNA to 5.3.1 (or w/e relevant release is)~~ Remove JNA dependency entirely

**Comment by Spottedleaf** [comment]
> and they changed the navigation classes
> it looks like they added a set of possible positions to path find to
> so imma drop 0077-EntityPathFindEvent until we can resolve the api for that
> unless I just use a for loop and call the event for each one :kappa:
> yeah I'll do that for now and let's re-visit that
