### ISSUE TITLE
Tab completion does not work when command is set to "/g"

### ISSUE THREAD

**Issue by Derkades** [PaperMC/Paper#2276]
### What behaviour is expected:
Tab completion works regardless of command name

### What behaviour is observed:
When my command is set to "/g", tab complete does not work. When I set the name to something else, like "/a" or "/m", tab complete works fine

### Steps/models to reproduce:
Description above should suffice. If not, there are step by step instructions in a comment below. If you prefer, video: https://www.youtube.com/watch?v=_3hS84dF7YU

### Plugin list:
Custom

### Paper build number:
1.14.3 build 122

### Anything else:
It works with spigot, not with paper. Using the latest available download for paper, and a freshly compiled spigot jar from BuildTools.

I don't think it's related to #1733 , my `/g` command does not override any commands. When I run `/help g` it lists help for the vanilla /gamerule, /gamemode and /give commands.

**Comment by electronicboy** [comment]
A list of concise instructions would be much more preferable to a youtube video, does it work when you rejoin the game? Looks like the client still recognizes /g, so something is probably not sending the command registration, is there anything in the logs?

**Comment by Derkades** [comment]
Nothing in the logs. The command still works as expected, just not tab completion.

This is what I do in the youtube video:
1. Set command in plugin.yml and in onEnable (where it is registered) to `/a`
2. Put plugin in plugins folder, reload server
3. Type `/a map ` - A tab completion thing appears
4. Set command in plugin.yml and in onEnable to `/g`
5. Put plugin in plugins folder, reload server
6. Type `/g map ` - A tab completion thing does not appear.
7. Set command in plugin.yml and in onEnable to `/m`
8. Put plugin in plugins folder, reload server
9. Type `/m map ` - A tab completion thing does appear.
10. Type `/help g` - Shows no `/g` command (as expected, because the command is set to /m)

In the video I reloaded the server, but this did not effect the results because
1. After restarting, tab completion still does not work for `/g`
2. Even after reloading (not restarting), tab completion works for `/a` and `/m`

There is no particular reason for me trying `/a` and `/m`, I just tried two arbitrary single character commands (similar to /g)

**Comment by Weber588** [comment]
For if it's of relevance: This occurs regardless of whether or not /g is an alias or a main command. 

- If /g is the main command, and there is another alias of the same command, the TabCompleter will work on all aliases except /g. 
- If /g is an alias, tabbing will work on the main command and other aliases, but not /g itself.

**Comment by ninja-** [comment]
Not sure if related, but I ran into a similar bug lately. I wanted to have an /on command, but turns out that you can't, because if you use

```
mycommand:
    aliases: [bla, blabla, on]
```

on will always be interpreted as "true" and so you get a /true command instead lol

**Comment by Derkades** [comment]
@ninja- Unrelated issue, and not a bug. The yaml parser interprets `on` as a boolean. Force it to interpret it as a string by adding quotes: `aliases: [bla, blabla, 'on']`

**Comment by Derkades** [comment]
Fixed in 1.17. Somehow.
