### ISSUE TITLE
Crash Question

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#2279]
Sorry if I'm in the wrong section.

Paper122 keeps on crashing for me. (https://pastebin.com/btZAG1BB)

Please correct me if I'm wrong. If the crash report says "Writing into PalettedContainer from multiple threads (other thread: name: Craft Scheduler Thread - 54)", does that mean the stack trace of "Craft Scheduler Thread - 54" is supposed to contain some mention of "DataPaletteBlock.setType", just like the Server thread? Thread 54 doesn't seem to mention anything change-inducing. Does that mean other threads could also be at fault, even though none of them mention any kind of "setType" operation that would sound dangerous?

For example, the thread "Netty Epoll Server IO #1" has a plugin that is calling World.getType (subsequently calling ChunkProviderServer.getChunkAt) in the instance of crash. Could that also cause a problem, even though it doesn't sound like it writes anything?

**Comment by MiniDigger** [comment]
some plugin is using bukkits scheduler to set blocks async. its impossible to say which plugin as the thread is already sleeping by the time vanilla detects the corruption. 
I don't think that the getType calls on the netty threads have anything to do with it, but its not that kind of a good idea too, as you can see all netty threads are currently waiting on the main thread, slowing down packet processing. so I would talk to the author of com.updogg.psessions about that.
