### ISSUE TITLE
New arrows stack bug

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#228]
https://www.youtube.com/watch?v=tVXEixTednY
### Plugin list:

http://timings.aikar.co/v2/?id=e25461448579422e96d6bbe621366363&start=1461170215&end=1461170619&section=plugins
### bukkit.yml, spigot.yml, paper.yml, server.properties

http://timings.aikar.co/v2/?id=e25461448579422e96d6bbe621366363&start=1461170215&end=1461170619&section=config
server.properties: http://pastebin.com/kXB3Ejdv
### Paper build number:

git-Paper-689 (MC: 1.9.2)

**Comment by zachbr** [comment]
Are those vanilla arrows? They look like they have custom NBT set on them. In which case we need a way to create them so we can test this properly.
Is there a plugin you're using to create them specifically?

**Comment by andris155** [comment]
Crafted arrows

**Comment by zachbr** [comment]
Thanks, will try and look into this soon

**Comment by zachbr** [comment]
Can't reproduce this behavior w/out any plugins.

**Comment by andris155** [comment]
Crafted new arrows, and works perfectly. :O
