### ISSUE TITLE
High local server ping in new build #123

### ISSUE THREAD

**Issue by JavituRec** [PaperMC/Paper#2281]
###  Timings or Profile link:
https://timings.aikar.co/?id=a27dd549546d495db19ea6ecfabc8181

### Description of issue:
High ping in local server:

![poingg](https://user-images.githubusercontent.com/10663192/60659240-37f93b00-9e55-11e9-806e-46db9f00ce8b.png)

### Paper build number:
![vers](https://user-images.githubusercontent.com/10663192/60659358-7c84d680-9e55-11e9-8b5b-840bb46aeba9.png)

**Comment by Ristovski** [comment]
Appears to have a significantly higher CPU usage as well

**Comment by OneCake** [comment]
I'm using build #120 and I am having the same issue, it uses increasing amounts of memory, even with no players on the server. However, I believe this is a general Minecraft issue ( https://bugs.mojang.com/browse/MC-149018 )
