### ISSUE TITLE
Better support for non-LivingEntity deaths

### ISSUE THREAD

**Issue by caojohnny** [PaperMC/Paper#2282]
There's currently no way to detect whether or not a non-LivingEntity (such as Item entities) has died to the void. No events are called, and the only workarounds are hacks such as using the scheduler to figure out where and when an entity simply disappears. I tried listening to `EntityDeathEvent`, `EntityDamageEvent`, `ItemDespawnEvent`, and on the recommendation of Z in Discord, `EntityRemoveFromWorldEvent` (which seems to be called by players being removed rather than any entity, but I digress).

Since Z might have missed my message, the output for the event is as follows:

```
[19:29:44 INFO]: <AgentTroll> dropping item at y=-61
[19:29:51 INFO]: <AgentTroll> now killing myself
[19:29:55 INFO]: AgentTroll fell out of the world
[19:29:57 INFO]: Removed: CraftPlayer{name=AgentTroll}
```

code:
``` java
@EventHandler
public void onRemove(EntityRemoveFromWorldEvent event) {
    Entity entity = event.getEntity();
    System.out.println("Removed: " + entity);
}
```

**Describe the solution you'd like**
The most preferable solution is to have full entity damage/death event support like normal LivingEntities. When they are taking void damage, `Entity#doVoidDamage()` is overridden to call `EntityLiving#damageEntity(...)`, however, `damageEntity(...)` is available to all `Entity` subclasses, so I fail to see why it shouldn't be called for all entities, e.g. Item entities. I haven't yet looked to see if `damageEntity(...)` leads to `EntityDeathEvent` being called, but adding support for that if not already present would be excellent as well.

The alternative solution is also to fix `EntityRemoveFromWorldEvent` to actually be called, this isn't preferable because I am losing a lot of context such as damage reason, but it is better than using a scheduler, and it sounds like it is broken anyways because it isn't being called even though it touts itself to be called whenever "an entity is being removed from a world for any reason."

**Describe alternatives you've considered**
Discussed in the first paragraph. There are hacks such as using the scheduler to figure out when the entity disappears, but there are no guarantees here. I think that adding support for this is relatively trivial compared to the potential benefit for server gamemodes such as skyblock or skywars, where players regularly lose items to the void by accident. The only problem now is the scope - where should `damageEntity(...)` be called for example.

**Additional context**
I'm willing to implement/maintain any agreed-upon solution.

In the case I've missed something, please let me know because I'm sure the absolute best solution would be one that requires no changes at all.

**Comment by zachbr** [comment]
Version?

**Comment by caojohnny** [comment]
Tested originally on 1.14.2 da401a6d, but retested just now on 1.14.3 build 123 with the exact same result

(edited original post, ecat didn't tell me anything :p)

**Comment by KSashaDF** [comment]
Tested and confirmed on 1.14.4, build 218.

The lack of a functional EntityRemoveFromWorldEvent breaks certain plugins, with no reliable alternative. This event worked for all entities on 1.13.2.
