### ISSUE TITLE
getNearbyEntities crashes server when run from ProtocolLib

### ISSUE THREAD

**Issue by kangarko** [PaperMC/Paper#2284]
Paper 1.14.3 build 124

I am transforming sounds for certain entities using packet interception in ProtocolLib. Problem is I need to find those entities and that seem to crash the server on 1.14 (not previously).

The method I am using:
![a](https://i.imgur.com/AarvpDK.png)

The code that is problematic:
![a](https://i.imgur.com/z0smXFh.png)

An example stack trace can be found here:
https://github.com/kangarko/Boss/issues/356

Thanks

**Comment by Spottedleaf** [comment]
This has occurred because you are making an async call when you should not be, you've deadlocked the server

**Comment by electronicboy** [comment]
Few things:

1) Accessing the world async is dangerous, requesting chunks to be loaded should be done by the server on the main thread, but this is your gotcha: You blocked the networking thread waiting for this chunk, which when the server went to send a packet, deadlocked the server, network manager will never be unlocked until main can process the chunk, and main is stuck there waiting on the lock on the network manager to give way

2) getNearbyEntities itself is also not safe to call async, the underlying data structures are basically dangerous when called off the main thread

Yes, in both of those instances you can get lucky and have no issues, but there are edge cases to everything, many of those are based solely upon what the server itself is doing at the point that you call it

**Comment by kangarko** [comment]
Thanks, did not realize this method could load up chunks.

Do you guys have any idea how can I remap those sounds? I know Citizens have done it using NMS but that's not doable within my plugin. I checked https://wiki.vg/Protocol but the named packet does not contain the entity so that's why I am tampering with the location.

Thanks so much.
