### ISSUE TITLE
Citizens cause server freeze

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#2285]
### What behaviour is expected:
___What you expected to see___
Citizens works perfectly with Paper.

### What behaviour is observed:
___What you actually saw___
Citizens cause server freeze
https://pastebin.com/xXpbZmUn

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Use Citizens

### Plugin list:
___A list of your plugins___
Plugins (94): AdditionsAPI, AdminVedelem, antiRedstoneClock, AnvilRestrict, AreaShop, AsyncWorldEdit, BuntetesLogolo, ChatControl, ChestCommands, ChestShop, Citizens, ChestShopNotifier*, ChestSort, CombatLogX, CommandHook, CommandSigns, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, EnderContainers, EntityDetection, EpicHeads, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, GriefPrevention, GriefPreventionFlags, HeapDump*, HolographicDisplays, HonapStaffja, HungerGames, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, NametagEdit*, NoSpawnerChange, NoteBlockAPI, OpenInv*, Paintball, PickupSpawners, PinataParty*, PlaceholderAPI*, PlayerHeads, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaAdditions, RestrictedCreative, Shopkeepers, SignEdit*, StaffChat, StaffTime, Stats, SuperLuckyBlock, SzulinapiTuzijatek, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, VillagerOptimiser, Votifier, VotingPlugin, VoxelSniper, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-122 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___
Citizens-2.0.25-b1717
I already reported to Citizens developer, but not fixed this.
https://github.com/CitizensDev/Citizens2/issues/1854

**Comment by KisaragiEffective** [comment]
>I already reported to Citizens developer, but not fixed this.
>CitizensDev/Citizens2#1854

then write fix and make pr
IN MY OPINION, their plugin compatibility is NOT paper's business.

**Comment by Spottedleaf** [comment]
It's unfortunate that the dev closed the issue. It is not safe to make chunk load calls in load events, and that's exactly what is occurring here. There's nothing we can do currently to resolve this issue as it is very deep in vanilla.

A rough fix that the developer could look into is delaying the task by a tick to get it out of the server chunk queue.

**Comment by CeIebrimbor** [comment]
![image](https://user-images.githubusercontent.com/14807889/60910114-c7776300-a234-11e9-8533-909e652471fd.png)
Time to close this after https://github.com/CitizensDev/Citizens2/commit/82e4f2dcea3477477d77cb15bc4df40a6521db71 ?

**Comment by Momonche** [comment]
@CeIebrimbor That build doesn't resolve the problem
https://pastebin.com/cBqjfGak

**Comment by zachbr** [comment]
That stacktrace isn't related to the issue that this ticket was created for.
