### ISSUE TITLE
PlayerLecternPutEvent

### ISSUE THREAD

**Issue by artur9010** [PaperMC/Paper#2286]
**Is your feature request related to a problem? Please describe.**
Event that will be fired when player put book on Lectern.

**Describe the solution you'd like**
Add event that will be fired when player puts book on lectern.

**Describe alternatives you've considered**
Canceling right click will also block option to read book by players.

**Comment by Black-Hole** [comment]
Just cancel the right click if the player has a book in the used hand and the lactern is empty.

**Comment by wizjany** [comment]
a block place is already thrown for the state change of no-book to book. don't even have to check yourself if the player has a book.

edit: to be clear, this is true of all item-block interactions, as craftbukkit just captures state changes when a player uses an item and sends those state changes as a place/multiplace event.
