### ISSUE TITLE
Anti XRay CFG missing on paper.yml

### ISSUE THREAD

**Issue by danielsartor** [PaperMC/Paper#2287]
I've just installed the Paper for MC version 1.14.3 (Build 124 according to download page)

Here is the CFG generated:
https://pastebin.com/cvKMqmby

**Comment by Spottedleaf** [comment]
Paper is currently missing anti-xray, had you taken a look through our issues you would have seen that.

We have a test build available from this PR here - https://github.com/PaperMC/Paper/pull/2240.
It is in testing so do expect something to go wrong. Report issues with it there

**Comment by danielsartor** [comment]
Sorry, my friend told me something that it was re-added, then I got the latest version but it wasn't there. Then I decided to report, but I was aware about it. (:
