### ISSUE TITLE
Option "treasure-maps-return-already-discovered" is actually inverted

### ISSUE THREAD

**Issue by f0x48** [PaperMC/Paper#2288]
### What behaviour is expected:
this option when setting to false should giving the undiscovered location.
when setting to true, it should give the closest structure

### What behaviour is observed:
when setting to false Server send closest structure regardless already discovered or not
but, when setting to true. it send the undiscovered structure 

### Steps/models to reproduce:
Trade with villagers

### Plugin list:

Plugins (17): AuthMe, BestViewDistance, Bonuschest, ChangeSkin, ChatCo, CustomHelp, EdwinLogin, NoCheatPlus, OldschoolKill, PermissionsBukkit, PingMOTD, ProtocolLib, RemoveJoinLeaveMessage, SimpleAutoBroadcast, Tablist, TornadoxxDonkey, ViaVersion

### Paper build number:
paper-1617 (1.12.2)

### Anything else:

**Comment by jeconneely** [comment]
I am running paper-124 (1.14.3) and I get the closest treasure regardless of the setting, which is frustrating because I want the undiscovered treasure.  If it makes a difference the treasure chest was collected rather than left in-place empty.

**Comment by electronicboy** [comment]
For 1.14.x, looks like that option was not actually implemented, for 1.12, I'll have to take a look

**Comment by electronicboy** [comment]
`pass false to return first structure, regardless of if its been discovered. true returns only undiscovered` - This is actually 100% intended, it's behavior however might not line up with what you're expecting, however? maybe we should consider renaming this config option?

**Comment by f0x48** [comment]
> `pass false to return first structure, regardless of if its been discovered. true returns only undiscovered` - This is actually 100% intended, it's behavior however might not line up with what you're expecting, however? maybe we should consider renaming this config option?

Maybe i miss understand the documentation? i read it from https://paper.readthedocs.io/en/stable/server/configuration.html#treasure-maps-return-already-discovered .

if you say `pass false to return first structure, regardless of if its been discovered` the default option should be true then.

**Comment by Machine-Maker** [comment]
Looking through the code, I think currently the [documentation](https://paper.readthedocs.io/en/latest/server/configuration.html#treasure-maps-return-already-discovered) is correct. The default value `false` leaves vanilla behaviour of finding the closest "unreferenced" or not discovered location. Changing it to true, will return the closest location even if it has been referenced/found before. 

So this can probably be closed.
