### ISSUE TITLE
Minecraft::Save Players long per tick?

### ISSUE THREAD

**Issue by jivvy** [PaperMC/Paper#2289]
###  Timings or Profile link:
https://timings.aikar.co/?id=e4f10a23af684753bc8a6227e99211e1

### Description of issue:
Recommended parameters are used in the start.bat, from: https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

There is a low player count, as is evident. The machine hosting it is a Ryzen 5, with 16gb total ram, located entirely on an SSD. Other servers I've hosted did not experience these occasional hiccups. They are not game-breaking, but they are a nuisance. I've looked through the timings, I think Minecraft::Save Players is unusual, but I've never read timings out from the viewer before like this, so I don't know what's normal, just what's in red and how ticks work.

I also have an HDD that spins down due to disuse. None of the server is located on it, except back-ups, but this problem was present before I moved the back-up location to the HDD, so I don't think it's relevant. I made a script that keeps it spinning, but don't expect any change.

Edit: Also, I've noticed while playing a game or even just doing some lighter work on this machine, I occasionally get a couple seconds of moderately intense stuttering -- audio, video, mouse, all of it. I thought maybe it was RAM (maybe set-up, timings or something, maybe slots even?) or HDD, which is pretty old. You could keep that in mind if it helps, but the stuttering and server hiccups don't seem to occur simultaneously, so not sure how far that goes for you.

### Plugin list:
Several tiny plugins:
[Chairs](https://dev.bukkit.org/projects/chairsreloaded) -- lets you sit on stairs
ProtocolLib
[ServerRestorer](https://dev.bukkit.org/projects/serverrestorer?gameCategorySlug=bukkit-plugins) -- back-ups
[WitherAC](https://www.spigotmc.org/resources/wither-anti-cheat-new-free-anti-cheating-solution-looking-for-testers.68657/) -- WIP anti-cheat. Already contacted them, they are sure they are not related.

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml ----- https://pastebin.com/8sGY8pwh
spigot.yml ----- https://pastebin.com/k066N9b6
paper.yml ----- https://pastebin.com/8zpGsyCf
server.properties -- https://pastebin.com/YFkGEF3c

### Paper build number:
This server is running Paper version git-Paper-123 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

**Comment by Chew** [comment]
Hello! I hope you and your server are doing well. Unfortunately this issue is over a year old and as such needs to be closed. Fortunately, that means a year of improvements has occurred! However, if you still happen to be experiencing issues do not hesitate to ask us on our [Discord server](https://discord.gg/papermc) in #paper-help, we'd love to help! Have a good day!
