### ISSUE TITLE
My server got auto shut down :(

### ISSUE THREAD

**Issue by CaoTrongThang** [PaperMC/Paper#2298]
I really don't know what is going on :(, i'll provide all info you guys need, please help me :( (im very stupid ad English)
https://pastebin.com/EiPScVmF

**Comment by Spottedleaf** [comment]
There should be more information right before that, please post that too

**Comment by CaoTrongThang** [comment]
What information you need? ~~", i don't how how to get information before that :(

**Comment by mikroskeem** [comment]
Simply post whole server log into gist.github.com
