### ISSUE TITLE
prevent-moving-into-unloaded-chunks not working in 1.14.x?

### ISSUE THREAD

**Issue by RealCorebb** [PaperMC/Paper#2301]
### What behaviour is expected:
Shout not generate new chunks

### What behaviour is observed:
Still generate new chunks

### Steps/models to reproduce:
set prevent-moving-into-unloaded-chunks:true
Generate a fresh new map.
In the world,just go around,and it still generate new chunks.

### Plugin list:
EssentialsX

### Paper build number:
paper-125

### Anything else:
I can go anywhere without knock back

**Comment by aeonlamb** [comment]
Sounds like what you want is a world border. That config option prevents players from moving into chunks that have not been loaded by the server yet. Loaded =/= generated. The server will still generate chunks regardless of this config setting.

You can set a world border with the vanilla /worldborder command. See here: https://minecraft.gamepedia.com/World_border

**Comment by RealCorebb** [comment]
> Sounds like what you want is a world border. That config option prevents players from moving into chunks that have not been loaded by the server yet. Loaded =/= generated. The server will still generate chunks regardless of this config setting.
> 
> You can set a world border with the vanilla /worldborder command. See here: https://minecraft.gamepedia.com/World_border

Thanks a lot.

**Comment by Spottedleaf** [comment]
I'm going to go ahead and confirm this, see https://github.com/PaperMC/Paper/pull/2297. The PR will not resolve the issue but shows why this is occurring and what fix is required.

(At a technical level you're not moving into unloaded chunks but rather the patch is loading chunks you are moving into, and it should not be doing that)

Please re-open.

**Comment by Spottedleaf** [comment]
I've updated the PR to resolve this case.

**Comment by Spottedleaf** [comment]
please re-try on latest to see if this is fixed

please note that also the client does not immediately render chunks sent from the server

**Comment by RealCorebb** [comment]
> please re-try on latest to see if this is fixed
> 
> please note that also the client does not immediately render chunks sent from the server

Yes,it works.I'll get knocked back immediately if i fly faster than the server loading chunks.
