### ISSUE TITLE
Server crash on player join 1.14.*

### ISSUE THREAD

**Issue by Serrrgio** [PaperMC/Paper#2304]
### Link/paste of stack trace

   https://pastebin.com/srW2wgbS

### Plugin list:
no plugins

### Actions to reproduce (if known):
Download user .dat file https://drive.google.com/open?id=1hefJUEBYqvEmuOiL0Ypb8FqHCtcdN_6H
put world/playerdata
rename to you UUID or join on the server with player name 123ha3ap321

After logging into the server, the server does not respond to commands and after a while it crashes
His happens when a player disconnects from the server while in the boat

![paper](https://user-images.githubusercontent.com/1352496/60955170-f8c16300-a308-11e9-8321-ae63a99e0e4f.png)

### Paper build number:
current, git-Paper-127 and all builds 1.14.3

**Comment by Proximyst** [comment]
We've fixed a lot of the issues relating to chunk loading since 1.14. Please reopen a new issue if this issue is still reproducible.
