### ISSUE TITLE
Server is crashing after a couple of hours

### ISSUE THREAD

**Issue by Skajdrowski** [PaperMC/Paper#2305]
Here's the logs
[2019-07-10-9.log](https://pastebin.com/raw/rWA0PQsE)

**Comment by Skajdrowski** [comment]
Another logs from last night [2019-07-11-1.log](https://pastebin.com/raw/VqbEqVFF)

**Comment by brightestpixel** [comment]
I'm having the same issue, memory usage appears to be fairly low and then server will just randomly stop responding. I was using paper-129 btw.

**Comment by Skajdrowski** [comment]
> 
> 
> I'm having the same issue, memory usage appears to be fairly low and then server will just randomly stop responding. I was using paper-129 btw.

I think it's gonna be fixed in 1.14.4 as of [MC-149018](https://bugs.mojang.com/browse/MC-149018) bug

**Comment by Chew** [comment]
1.14 was an absolutely buggy mess for servers. Fortunately, Mojang has learned their lesson (hopefully) and made servers much more stable on the versions we support (1.15.2 and above). So, if this error still occurs on any of those versions, feel free to open a new issue. Have a good day!
