### ISSUE TITLE
The map's region file is abnormally increased

### ISSUE THREAD

**Issue by cras4202tw** [PaperMC/Paper#2307]
### What behaviour is expected:
Region file normal increase

### What behaviour is observed:
My minecraft server, World_nether region file has increased abnormally, almost 3 files per second, even if World_neter does not have any players, more then 80GB size server tps is below 10

### Steps/models to reproduce:
Even if I delete World_nether,and restart server to create map, it will continue to increase abnormally, I don't have to do something special.

### Plugin list:
ClearLag, Essentials, EssentialsChat, PermissionsEx, RandomSpawn

### Paper build number:
 git-Paper-1617 (MC: 1.12.2)

**Comment by cras4202tw** [comment]
This is an old map over 80GB . The number of regions is very abnormal.
![old map over 80GB](https://i.imgur.com/eFFiRCj.png)

**Comment by MiniDigger** [comment]
try removing your randomspawn plugin and see if the world still grows

**Comment by cras4202tw** [comment]
I can understand that if you regenerate in a new location, a new region file will be generated, but World_nether is not a reborn world, and the state of the region file is increased, even if there is no player in World_nether.

**Comment by Chew** [comment]
This error occurs on 1.12.2 so must be closed for being outdated. As Mini suggested, you should try and reproduce this with no plugins on latest (preferably 1.16.2), and, if it still occurs, feel free to open up a new report. Have a good day!
