### ISSUE TITLE
EntityExplodeEvent

### ISSUE THREAD

**Issue by DispenserLP** [PaperMC/Paper#2315]
The event is not triggered, if you clean up the _blocklist_, all blocks are dropped anyway, the same thing happens when setting the yield. No function!

### Paper build number:
[14:32:40 INFO]: This server is running Paper version git-Paper-131 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
[14:32:40 INFO]: Previous version: git-Paper-126 (MC: 1.14.3)
[14:32:40 INFO]: You are running the latest version

**Comment by Proximyst** [comment]
Works fine on 1.16.2.

**Comment by jaylawl** [comment]
Experiencing this issue on:

```
This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads
```

This code does not fire upon a creeper exploding:
```


    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = false)
    public void onEntityExplode(@NotNull EntityExplodeEvent event) {

        System.out.println("onEntityExplode");
}
```

**Comment by lynxplay** [comment]
Can you please open a new issue including as much information as you can provide for this ? (E.g. replication steps, code, etc)
 Reopening this ancient issue with little to no information will not yield any benefit.

**Comment by jaylawl** [comment]
> Can you please open a new issue including as much information as you can provide for this ? (E.g. replication steps, code, etc) Reopening this ancient issue with little to no information will not yield any benefit.

I thought my issue would not really be relevant anyway due to me being on the final builds of 1.17 and thus i only meant to document the occassion, but i shall do as you ask

**Comment by lynxplay** [comment]
As of right now 1.17 is still supported ¯\_(ツ)_/¯. If you have easy replication steps for this it would still be considered a bug.

**Comment by jaylawl** [comment]
Thank you
