### ISSUE TITLE
Multiple ender dragons in the end when playing survival

### ISSUE THREAD

**Issue by nikhiljha** [PaperMC/Paper#2320]
### What behaviour is expected:
1 Ender Dragon

### What behaviour is observed:
4 Ender Dragons

### Steps/models to reproduce:
1. Open a new Paper 1.14.3 world.
2. Go to the end.

### Plugin list:
None

### Paper build number:
131

### Anything else:
This has also been reproduced by LoXR and barty on Discord.

![](https://media.discordapp.net/attachments/582344791065362481/600156268023382032/Screen_Shot_2019-07-14_at_7.41.35_PM.jpg?width=1840&height=1035)

**Comment by MassiveLag** [comment]
Same

**Comment by robertoccu** [comment]
Same in our server. Only one boss bar but multiple dragons. When killed, more appeared, but no one spawned the egg or open the portal.

We unload the world (Multiverse). Some hours later loaded it and only was one dragon. Killed it and it opened the portal, end gateway and spawned the egg.

Spawned one with Ender Crystals and killed it. All normal and other end gateway.

Some minutes later without doing anything, other Dragon spawned, without boss bar. When killed, no portal was opened.

Build 131

**Comment by Joo200** [comment]
I had this issue with 1.12.2. one problem could be that the enderdragon moves into an unloaded chunk. The vanilla part from the server detects the missing ender dragon (unloaded chunk -> enderdragon dead?) And causes the respawn of a new dragon.

**Comment by Aurelien30000** [comment]
I can confirm this issue in 1.12.2.

**Comment by clrxbl** [comment]
Can confirm this issue on Paper 1.14.2.

**Comment by robertoccu** [comment]
Today two more spawned. One at the morning and another some hours (and one server reset) after.

Later I check the logs. This appears, but I don't know if at the exact moment. I will check next time:
[Server thread/INFO]: Scanning for legacy world dragon fight...
[Server thread/INFO]: Found that the dragon has been killed in this world already.

Build 134

**Comment by BillyGalbreath** [comment]
I'd like some more details. Could you please attach a timings report so I can see all your server config settings? I have a feeling this is caused by view distance being too low, or keep spawn loaded is disabled, etc

**Comment by robertoccu** [comment]
Timings: https://timings.aikar.co/?id=2a1f0accca1a4a6a9ff138212122ac0c (yes, that timings are a mess. We think that is ChunkAsync using all of our CPU)
A difference compared to yesterday: I reduced view-distance from 8 to 6 and added ViaVersion.

Today no dragons spawned, but tps were higher than yesterday. Maybe is something related between end loading, dragon alive check and low tps.

**Comment by Spzatak** [comment]
confirming this issue on 1.14.4

**Comment by electronicboy** [comment]
Any idea if this is replicable in spigot/vanilla? You can also disable the legacy ender dragon check

**Comment by hanss314** [comment]
Can confirm on 1.14.4

**Comment by ghost** [comment]
Multiple appeared, I found the one attached to the health bar, saw it disappear while on the bedrock block, then slowly the others started to also disappear.

When there was only one left, although the health bar stayed the same while hitting it, I got the following:
![2019-08-15_10 49 28](https://user-images.githubusercontent.com/5023340/63081099-705b6100-bf4b-11e9-9852-83bae085bf80.png)

No egg, no portal, then the others reappeared.

1.14.4

**Comment by s1h4d0w** [comment]
1.14.4 here, same issue. New server running for about a week now.

PaperMC-176 on Ubuntu Server 18.04.3
Timings: https://timings.aikar.co/?id=bb2293d2b5a44f51b34d8d02c3bfdea1

Plugins: AntiCurse, ArmoredElytra*, AuthMe, AutoMessager, BetterRTP*, ChatReaction, ChopTree2, ClearLag, CoreProtect, CrazyEnchantments, DeathCoordinates, DynamicShop, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, GriefPrevention, HolographicDisplays, InfernalMobs, Item2Chat, Jobs, JoinMessagePlus*, JukeBox, LuckPerms, Matrix, MineableSpawners, Multiverse-Core, MyCommand, NoteBlockAPI, OnTime*, PhantomSMP, ProtocolLib, QuickShop, ServerListPlus*, SkinsRestorer, SuperbVote, UltraCosmetics, Vault, Votifier, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

I teleported to the end once as OPed player, then left immediately as I realized I was literally the first one to go there before normal players. Then eventually a player made it to the End and there were maybe 10-20 dragons flying around.

I don't have the exact console output but it said something like this:

```
[Server thread/INFO]: Scanning for legacy world dragon fight...
[Server thread/INFO]: Found that the dragon has not been killed in this world.
[Server thread/INFO]: Found that there's a dragon still alive (coordinates and stuff).
[Server thread/INFO]: But we didn't have a portal, let's remove it.
```

Then the player started messaging me in a panic saying there were dozens of dragons. I used killall to remove them, but the boss bar stayed up. I then just spawned a new dragon using spawnmob and that fixed the whole thing.

But reading these replies it seems like more can still spawn.

**Comment by PachiMc** [comment]
same to me

**Comment by Remski01** [comment]
https://github.com/PaperMC/Paper/issues/2320#issuecomment-516665981

**Comment by NullCase** [comment]
Confirmed in Paper-225 (MC: 1.14.4)
* I'd update to latest but for that recent issue about vanishing chunks. Just gonna wait on that one. Idk, paper devs are legit and maybe it's solved already.

**Comment by dmodoomsirius** [comment]
confirmed with paper-236.

Plugins: AdvancedWarn, ArmorStandEditor, Autorank, BannerMaker*, BetterRTP*, BlockLocker, BuyRegion, CoreProtect, CS-CoreLib, DeathMessagesPrime, dynmap*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EXPGRadioPlugin*, FastLeafDecay, InventoryRollback, MeltDown, MineableSpawners, MobCapture, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MysqlEconomyBank, PermissionsEx*, PlayerReport*, PlotSquared, PluginLibrary*, ProtocolLib*, Shop, SmoothSleep, StaffPlus, SuperVanish, Vault, WG-GUI, WorldEdit, WorldGuard

Config option in paper.yml scan-for-legacy-ender-dragon at the recommendation of electroniccat was set to false and still have the same issue with them spawning.

steps to reproduce
1. warp to the end
2. kill all the ender dragon's using the `killall hostile` command
3. warp out of the end. 
4. warp back in using essentials commands.
