### ISSUE TITLE
"treasure-maps-return-already-discovered" not implemented in 1.13.x/1.14.x

### ISSUE THREAD

**Issue by electronicboy** [PaperMC/Paper#2321]
I am running paper-124 (1.14.3) and I get the closest treasure regardless of the setting, which is frustrating because I want the undiscovered treasure.  If it makes a difference the treasure chest was collected rather than left in-place empty.

_Originally posted by @jeconneely in https://github.com/PaperMC/Paper/issues/2288#issuecomment-511253906_

**Comment by Puremin0rez** [comment]
Confirmed - this actually affects both 1.13 and 1.14.

1.13: https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0154-Configurable-Cartographer-Treasure-Maps.patch
1.14: https://github.com/PaperMC/Paper/blob/ver/1.14/Spigot-Server-Patches/0134-Configurable-Cartographer-Treasure-Maps.patch

The patch is only partially implemented.

**Comment by Panderine** [comment]
Is this implemented in 1.14.4 or not?

I'm getting the same **discovered** ocean monument with each new map I generate with each NEW cartographer.
