### ISSUE TITLE
Villagers trades become more expensive that the displayed price

### ISSUE THREAD

**Issue by feature** [PaperMC/Paper#2326]
### What behaviour is expected:
I expect the prices in the villager trading menu to reflect the actual price of the trades. In vanilla Minecraft trade prices seem to increase either when they're traded a lot, or when they're resupplied.

### What behaviour is observed:
After doing the same trade with the same villager a lot, the actual prices of the trades increases significantly, but the displayed price remains unchanged or often discounted.

### Steps/models to reproduce:
I've experienced this issue specifically with the iron trades for the toolsmith and armorer villagers. 

1. Get a toolsmith or armorer villager
2. Unlock the iron trade
3. Do the iron trade till it locks
4. Wait for the villager to resupply, and repeat 3 about 3-5 times
5. Check the actual price, as described below

You can verify the actual prices at any point by putting your emeralds into the trading slot, and then clicking the emerald stack to update it after you've done the trade, and the subtract the updated stack size with the initial stack size to calculate the actual price.

### Plugin list:
Plugins (11): AntiVPN, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, <redacted>*, TreeFeller*, Vault, WorldEdit, WorldGuard

### Paper build number:
This server is running Paper version git-Paper-127 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-122 (MC: 1.14.3)
You are 5 version(s) behind

### Anything else:
I've redacted the name of a server specific plugin, but I'm certain it has nothing to do with the issue. I'm aware the server is slightly outdated but I do not operate the server so I cannot update it, however I could not find any recent commits related to trading, so I do not believe it's fixed in the latest versions.

As I mentioned before, trade become more expensive if you do the same trade a lot, I believe this issue is because the price increase is not added to the displayed price.

**Comment by Tohya1** [comment]
See https://bugs.mojang.com/browse/MC-151282

**Comment by feature** [comment]
Thanks @Tohya1. That is odd, because I was not able to reproduce the issue on vanilla 1.14.3.

**Comment by 0-x-2-2** [comment]
Yeah this is a vanilla bug.

**Comment by feature** [comment]
I found a similar bug report [MC-148454](https://bugs.mojang.com/browse/MC-148454), where it is only bugged for other players and but not for the host. This is probably why I couldn't reproduce the issue in my vanilla single player world.

**Comment by zachbr** [comment]
Mojang has marked this as fixed for 1.14.4
