### ISSUE TITLE
Firework.getSpawningEntity() returns null for fireworks spawned by a crossbow

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#2327]
### What behaviour is expected:
Firework.getSpawningEntity() should return the shooters uuid

### What behaviour is observed:
Firework.getSpawningEntity() returns null

### Steps/models to reproduce:
Load a crossbow with fireworks and fire it at an entity

### Plugin list:
-

### Paper build number:
132

### Anything else:
-

**Comment by Spottedleaf** [comment]
try on spigot?

**Comment by Brokkonaut** [comment]
Its a paper api, spigot does not have that.

https://github.com/PaperMC/Paper/blob/ver/1.14/Spigot-API-Patches/0045-Fireworks-API-s.patch#L30

**Comment by Spottedleaf** [comment]
oh
