### ISSUE TITLE
EntityBreedEvent not triggered for foxes

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2330]
### What behaviour is expected:
Expected breeding foxes to trigger an EntityBreedEvent.

### What behaviour is observed:
The event wasn't triggered.

### Steps/models to reproduce:
With the following plugin,
```
import org.bukkit.entity.Fox;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.entity.EntityBreedEvent;
import org.bukkit.plugin.java.JavaPlugin;

import static org.bukkit.Bukkit.getPluginManager;

public class FoxMayhemPlugin extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onEntityBreed(EntityBreedEvent event) {
        if (event.getEntity() instanceof Fox) {
	    getLogger().info("Foxes bred"); // Never gets here
        }
    }
}
```
1. Load plugin
2. Breed foxes
3. Observe that the "Foxes bred" message is not logged

### Plugin list:
N/A

### Paper build number:
128

### Anything else:
N/A

**Comment by Black-Hole** [comment]
It seems foxes and turtles overwrite PathfinderGoalBreed.g(), so the event won't be called. Turtles breeding is very special, but foxes should call the event.

**Comment by MisterVector** [comment]
Looks like Spigot already took care of this.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/54f4e7f95884a9666b3eb5d5f5415cdd2eea89a8

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Paper/commit/cdd0bb43763323d96ce44394a94409929fa553b9 resolves this ^
