### ISSUE TITLE
Being kicked because of flying in rain with trident

### ISSUE THREAD

**Issue by Vernoxvernax** [PaperMC/Paper#2331]
### What behaviour is expected:
being kicked when using trident (enchanted with riptide) in the rain. (you can fly)

### What behaviour is observed:
--'--

### Steps/models to reproduce:
enchant your trident with riptide (I had riptide II)

### Plugin list:
WorlEdit, ClearLagg, AutoSaveWorld, Dynmap, PlugMan, TAB, TreeFeller, Chair

### Paper build number:
"This server is running Paper version git-Paper-131 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)" "(you are 3 versions behind)"

### Anything else:

**Comment by CeIebrimbor** [comment]
server.properties
allow-flight:true

This is not Paper. That setting is not stable on newer versions of MC.
