### ISSUE TITLE
Build is not located for 1.14.4

### ISSUE THREAD

**Issue by Cyber-MC** [PaperMC/Paper#2334]
Hi there,

My name is CyberPatriot and I have discovered that the latest version (Build #135/1.14.4) could not be located on the download page. 

Proof can be found here: https://imgur.com/2ypedNA

**Comment by astei** [comment]
It was just bumped up to 1.14.4: https://papermc.io/api/v1/paper/1.14.4/135

**Comment by ghost** [comment]
Use EDGE ir Firefox for the download

**Comment by Cyber-MC** [comment]
It wasn't when I did it a couple minutes ago. Now it is
