### ISSUE TITLE
invisible entities

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2335]
### What behaviour is expected:
All the entities are invisible. Even the new ones

### What behaviour is observed:
All the entities are invisble, even if you use spawn eggs

### Steps/models to reproduce:
Upgrade from paper #134 to #135

### Plugin list:
___A list of your plugins___
AConomy*, AdvancedBan*, AdvancedMobArena, ArmoredElytra*, AuctionHouse, ChatManager, CoreProtect, DynamicShop, EasyWhitelist*, ECore, FactionsBlue, FlightControl, GSit, HeadsPlus, Jobs, JupiterCore, LoginSecurity*, MineableSpawners, MySkin, NeoMoreTPPlus, OpenInv*, PlaceholderAPI*, ProtocolLib, sleep-most*, TAB, Take-Me-Back*, UberEnchant, UltraPermissions, Vault.

### Paper build number:
Paper version git-Paper-135 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[INFO] Previous version: git-Paper-134 (MC: 1.14.3)
[INFO] You are running the latest version 

### Anything else:
All plugins seems to work properly. 

> Maybe a Texture map/track issue?

**Comment by SteeltonMC** [comment]
I can confirm. Same results happening to me.

**Comment by breadbyte** [comment]
Caused by [TAB](https://www.spigotmc.org/threads/tab-1-8-x-1-14-3-reborn.324177/page-44#post-3480266).

**Comment by supertakeru** [comment]
close

**Comment by ghost** [comment]
Confirm TAB is the plugin that cause the issue
