### ISSUE TITLE
Server idle cpu usage is less stable than on default spigot 1.14.4

### ISSUE THREAD

**Issue by Wqrld** [PaperMC/Paper#2336]
Hi, we've been recommending paperspigot for minecraft 1.14.4 but with the recent performance boost in minecraft itself it looks like paper is even performing worse than normal spigot.

git-Paper-135 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT), All these benchmarks where done on a newly generated idle world after a restart

it's not by much although spigot 1.14.4 uses on average 11% cpu and paper is above that with average 15% with spikes to 40-90%.

(already way better than the constant 30% on 1.14.3)

I understand that 1.14.4 support is brand new but i feel like this should be looked into.

**Comment by MiniDigger** [comment]
Dude, it's been not even 24 hours...
You are lucky to even have a build at all

**Comment by NullCase** [comment]
@MiniDigger It seems like you guys are pretty busy rn. 

What kind of issues do you want posted first for the 1.14.4 releases?

**Comment by Saffanity** [comment]
@MiniDigger learn to respect users of your project. That goes to the other participants for this project. If you dont wanna help people remove the support, its that simple.

**Comment by electronicboy** [comment]
Performance in 1.14 is a complex matter, especially given spigots max-tick-time setting, it can make paper seem that it's performing worse when spigot is actually just opting to hide the issues by not ticking entities properly

I think somebody did say something about this on one of the internal channels, would be interesting to see profiler results between the two (Though, that in and of itself is fun...)

**Comment by zachbr** [comment]
Enough drama on this ticket. Continued attempts to introduce non-technical matters will result in your being blocked from accessing this tracker.

**Comment by Spottedleaf** [comment]
I don't see any changes of ours that can cause high idle usage, this appears to be a more vanilla related issue

**Comment by Wqrld** [comment]
While this is a vanilla issue it would still be good to try and fix it, maybe take a look if it is possible to revert to the old entity AI? I believe that was the main cause

**Comment by aikar** [comment]
No that is absolutely not possible. Everythings going to move to the new AI. We are optimizing as much as we can.

But the new AI system is not actually causing any problems. It's just villager specific code.

**Comment by Wqrld** [comment]
I don't see that back in my results. Even things like bats and zombies are using significant cpu time when no villagers are loaded. This is visible on 1.13-1.15 and absolutely reproducible across multiple machines and hosting companies.

**Comment by aikar** [comment]
They aren't using the new AI. Yes everything about mc is getting slower. We're doing what we can.

This is true for every mc update.

**Comment by Wqrld** [comment]
Then i probably misread the changelogs. I love the work that you are doing but the jump from 1.12 to 1.13+ in entity cpu was way too big to be neglected. I hope you guys find something to improve it.
