### ISSUE TITLE
ChunkPopulateEvent and BlockPopulator fires before neighbor chunks are generated (custom world gen)

### ISSUE THREAD

**Issue by paulevsGitch** [PaperMC/Paper#2337]
### What behaviour is expected:
ChunkPopulateEvent and BlockPopulator(populate) fired after chunk neighbors are generated (on positive side like vanilla or by chunk perimeter like old docs says).

### What behaviour is observed:
ChunkPopulateEvent and BlockPopulator(populate) executes after chunk was generated ignoring its neighbors. This ends up with cascading worldgen lag, as any block outside of a chunk will immediately fire its population, and this becomes a circle.

### Steps/models to reproduce:
- Create simple custom world generator (can be simple void chunks)
- Make ChunkPopulateEvent or BlockPopulator
- Place checking code like this inside:
`int x = event.getChunk().getX();`
`int z = event.getChunk().getZ();`
`System.out.println("Populate: " + x + " " + z);`
`for (int px = - 1; px < 2; px++)`
`  for (int pz = - 1; pz < 2; pz++)`
`    System.out.println(String.format("%d %d is %b", px, pz, event.getWorld().isChunkGenerated(x + px, z + pz)));`
`System.out.println("----------------");`
- Result for one of chunks can look like so:
`Populate: -1 -4`
`-1 -1 is false`
`-1 0 is false`
`-1 1 is false`
`0 -1 is false`
`0 0 is true` - chunk itself
`0 1 is false`
`1 -1 is false`
`1 0 is false`
`1 1 is false`
Which means all its neighbors is not generated.

### Plugin list:
Custom World Generator

### Paper build number:
git-Paper-135

### Anything else:
May be this is old problem, as I see many plugins with custom world generation use their own chunk providers, as they can't generate trees and structures via default methods. If I am wrong and this is not a bug so how to populate chunks correctly?

**Comment by Spottedleaf** [comment]
This could be related to https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/989f9b3daa6e44ee177a65cbb183a3345a72ae35
