### ISSUE TITLE
Invisible mobs???

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2338]
So we updated our server last night, (we were running viaversion so I WAS on the newest update already client side) upon starting up the server and logging on, ALL mobs are now invisible. They do not have any hitbox, and it is happening for all players on our server. The only sign that they exist is the sounds played when near them.

**Comment by clrxbl** [comment]
There's a template you use for issues for a reason.
Update https://www.spigotmc.org/resources/tab-1-8-x-1-14-4-reborn.57806/ if you use it.

**Comment by zachbr** [comment]
This is caused by a popular plugin. We can't tell you if you're using it or not because you ignored the issue template and just posted this blob of useless information.

**Comment by ghost** [comment]
If we could make it more obvious where the template is that would be great

**Comment by clrxbl** [comment]
The template is literally already pasted in when you start an issue.

**Comment by zachbr** [comment]
https://i.imgur.com/bef8VRG.mp4

**Comment by ghost** [comment]
Literally is not there for me, but I think I also started my issue from a oneoff spot while looking to see if other people had it, next time will look for it, ty for the help
