### ISSUE TITLE
Invisible Mobs

### ISSUE THREAD

**Issue by Saffanity** [PaperMC/Paper#2340]
### What behaviour is expected:
I expected to see mobs on my server because thats how minecraft works.

### What behaviour is observed:
The mobs on the server are not showing up, you can hear the sounds but you cannot see or interact with them.

### Steps/models to reproduce:
You can login to my server if thats not a an issue dont really know how to put it in a video.

### Plugin list:
Plugins (29): AsyncWorldEdit, ChatModifier*, ChatReaction, ClearLag, CoreProtect, DiscordSRV, EditableSign, EnjinMinecraftPlugin, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, LagMonitor*, LiteBans, LuckPerms, LWC, MyCommand, OpenInv*, PlaceholderAPI*, ProtocolLib, SuperbVote, SuperVanish, TAB, Vault, Votifier, WorldEdit, WorldGuard

### Paper build number:
Version 135

### Anything else:
It was working fine with 1.14.3.

**Comment by Spottedleaf** [comment]
update or remove TAB

**Comment by supertakeru** [comment]
close
