### ISSUE TITLE
[1.12.2]EntityTracker.updatePlayer cause huge lag

### ISSUE THREAD

**Issue by daboluo666** [PaperMC/Paper#2344]
###  Timings or Profile link:
![profile](https://i.loli.net/2019/07/21/5d3417774316d34985.png)

### Description of issue:
When there are more than 75 online players, EntityTracker.updatePlayer method can cause lag. Sometimes even more than 35%.

### Paper build number:
1.12.2 paper latest

**Comment by ninja-** [comment]
this looks pretty normal to me. not sure if your interpretation of profile is right. please check with /timings first

**Comment by electronicboy** [comment]
Ultimatly, the entity tracker is one of those things which does not scale well with MC, I've had ideas around it whenever I find the time for it, but 1.12.2 is too old for that (and is no longer supported)

**Comment by kamcio96** [comment]
@electronicboy pls link PR/issue with your future idea 😉

**Comment by daboluo666** [comment]
@electronicboy I tried 1.13.2 and 1.14.4 today, and this problem still here.

**Comment by electronicboy** [comment]
As with any piece of software, it can only take so much going on before it slows down, I don't keep generic "X part of the codebase is slow when I have a lot of players" open, information reported on the issue tracker very rarely provides the level of information required to start looking into these areas of the codebase which we know are kinda slow especially when you consider the burden of maintaining abi compat so plugins messing with the tracker don't break when we make any improvements, it's a lot of time and investment into running over large portions of the codebase, if somebody wants to spend the time to look into improvements/specific target areas of the entity tracker which can be improved, I welcome you to do so, but there is nothing on this issue which highlights much beyond a generic "the server doesn't scale well"
