### ISSUE TITLE
portal-search-radius misbehaving badly at low values.

### ISSUE THREAD

**Issue by Weasel-Beans** [PaperMC/Paper#2345]
### What behaviour is expected:
I used to have portal-search-radius set to 8(default 128), so players on my server wouldn't have their portals cross-linking with other players' base portals. This worked mostly fine on 1.13.2, but one of the recent updates, maybe 1.14 or 1.14.3 broke this.

### What behaviour is observed:
Existing linked portals sometimes work properly, but all new portals created while portal-search-radius is set to a low number generally lead to problems with the portal generation on the other side. People sometimes spawn up in the air, sometimes above lava in the nether, with no portal to catch them, or they spawn inside solid rock/netherrack. If a portal does spawn, it's usually in the wrong spot or intersecting with other portals. Usually there is a different result each time a player moves through the same portal. There are also some very bizarre things taking place in the nether with portal generation, both before this bug and now.(A lot worse now.) Take a look at this: https://i.imgur.com/bOPNkpp.jpg . . . I don't think those portals were made by a normal human being.

### Steps/models to reproduce:
Use a recent build of paper and change portal-search-radius in paper.yml to 8, or any low number, then try using nether portals on that server.

### Plugin list:
This issue isn't related to plugins, I've tested it on a local test server.

### Paper build number:
136, although it's probably been happening since 1.14.

### Anything else:
I heard that Mojang removed something important to nether portals/search radius. I suggest removing this option until they fix that, unless it has some function that I'm not aware of.

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
