### ISSUE TITLE
Add Config Feature to Remove Certain Block IDs from X-Ray Engine 2 Randomization

### ISSUE THREAD

**Issue by Rvby1** [PaperMC/Paper#2346]
**Is your feature request related to a problem? Please describe.**
When using Paper's anti-x-ray Engine 2 on Paper-135, there's a common issue where players will mine a block, see diamond or mossy created by the block ID randomization, only to have it vanish before their eyes. This usually occurs when TPS drops are causing block lag, but I've had reports of it happening even when block lag is not present.  This likely occurs because the server isn't able to or, in the case of block lag, simply doesn't know to switch block-id-data back fast enough. 

**Describe the solution you'd like**
There's not really any solution that I can think of that would fix the prpoblem of servers occasionally running behind. Instead, I think it would be helpful to have a config option where server ops could list a number of blocks/block IDs that they don't want the engine's randomizer to randomize to. 
For example, an op could list "diamond_ore" and "mossy_cobble" in the `block-id-randomizer-blacklist`. This would then prevent any block ids from being randomized to "diamond_ore" or "mossy_cobble." This would of course make diamond and mossy not appear anywhere—but I don't think that matters much. It would tip off cheaters that an anti-x-ray is being used, but I don't think it would affect legit players. 

**Additional context**
I'm honestly not sure how the block-id-randomization occurs on the backend, so I'm not really sure of the performance implications of having a blacklist. Engine 2 is already heavier than Engine 1, so adding more performance overhead would not be ideal. If performance implications are intense, perhaps define and Engine 3 with this feature?

**Comment by Black-Hole** [comment]
So why ain't you running with engine mode 1 then? There you can alter the list of replacement blocks.

**Comment by Rvby1** [comment]
I am running on engine 1. Engine 1 is just less effective, so I thought it'd be a nice feature to request for the engine 2 configuration so that I (and other ops) could run a more effective anti-x-ray engine without inconveniencing legit players.

**Comment by stonar96** [comment]
There has always been a list of blocks in paper.yml for this. I think this issue can be closed.

**Comment by Rvby1** [comment]
Could be wrong, but I'm fairly certain that there is no such config option in paper.yml to do this for **Engine 2**. There is one for Engine 1.

**Comment by stonar96** [comment]
`hidden-blocks` is what you are looking for. It does and always did what you want in `engine-mode: 2`. Just remove `diamond_ore` and `mossy_cobblestone` from this list.

**Comment by Rvby1** [comment]
Hah, I think you're right. Didn't recognize the relationship between `hidden-items` becoming the list of block-ids that would be used to replace the blocks with the block-ids listed in `replacement-blocks`. Thanks for pointing that out.

I was concerned for a moment that this would make it so x-rayers would know that `diamond_ore` and `mossy_cobblestone` were real since they wouldn't be randomized—but this could be addressed by adding `mossy_cobblestone` and `diamond_ore` to the list of `replacement-blocks` so that they would also be randomized.

 I believe this issue can in fact be closed.
