### ISSUE TITLE
'enable-treasure-maps: false' not working in 1.14.4

### ISSUE THREAD

**Issue by robertoccu** [PaperMC/Paper#2347]
### What behaviour is expected:
When 'enable-treasure-maps' is false, treasure maps not generate in shipwreck and underwater ruins.

### What behaviour is observed:
When 'enable-treasure-maps' is false, treasure maps generate anyway in shipwreck and underwater ruins.

### Steps/models to reproduce:
Put 'enable-treasure-maps' in paper.yml to false. Search some shipwrecks or underwater ruins and open the treasure chests.

### Plugin list:
None

### Paper build number:
git-Paper-136 (MC: 1.14.4) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

### Anything else:
No datapacks that modifies loot tables.

Maybe it doesn't help to fix this, but Treasure Map generation is very laggy (and can cause crash) on 1.14. Maybe due to poor performance in chunk loading: https://github.com/PaperMC/Paper/issues/2312

**Comment by Spottedleaf** [comment]
The configuration option is actually for whether cartographers can give out the maps.

**Comment by ghost** [comment]
^

**Comment by Chew** [comment]
As leaf said. See [the config docs](https://paper.readthedocs.io/en/latest/server/configuration.html#enable-treasure-maps). Bit weird naming scheme I agree, but that's just what it does I guess. Thanks for the report!
