### ISSUE TITLE
I getting error!

### ISSUE THREAD

**Issue by TheAberto** [PaperMC/Paper#2348]
Click to go to [Error logs](https://paste.ubuntu.com/p/cbgjm2vrBT/
)

**Comment by clrxbl** [comment]
The Paper github issue templates exist for a reason, use them.
You're also using a 5 year old Minecraft version which isn't supported by anyone.

**Comment by TheAberto** [comment]
the console should not write " Please report this to PaperSpigot directly!" in that case

**Comment by clrxbl** [comment]
You're using a 5 year old Minecraft version and you expect us to change that for software we haven't updated for 5 years.

**Comment by zachbr** [comment]
Use a modern version if you want assistance of any sort from this project.

**Comment by TheAberto** [comment]
no i do not expect. i said why the console tell me that?
