### ISSUE TITLE
[1.12.2] On player join instant kick after server load

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2349]
###  Timings or Profile link:

https://timings.aikar.co/?id=f8d8f5236663468d8a16ed089f869513

### Description of issue:
When a player joins, the server goes to max cpu and once the server is fully loads it kicks the player.

### Plugin list:
CleanroomGenerator, CratesPlus, CrazyAuctions, CrazyEnchantments, CreateYourOwnMenus (broken), FastAsyncWorldEdit, HolographicDisplays, LuckPerms, Multiverse-Core, Prison, Sk-Perm, SkQuery, skRayFall, Skript, Vault, ViaBackwards, ViaRewind, ViaVersion, Vixio, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml - https://pastebin.com/MjRSErZz
spigot.yml - https://pastebin.com/ir6A4Gng
paper.yml - https://pastebin.com/wkAQ9qrh
server.properties - https://pastebin.com/qKAwXB2B

### Other helpful links
The error itself - https://pastebin.com/XhvC9wHj

### Paper build number:
git-paper-1615

**Comment by ghost** [comment]
Changed provider to Spigot. Should work now.

**Comment by electronicboy** [comment]
The error indicates that your server took too long to tick processing the chunk loads, given the fact that you only have a single CPU core, your setup is probably too under-spec'd for async chunks to work properly, if you wish to use Paper, I'd suggest getting better hardware (I'd heavily suggest this anyways, mc should never be ran on a single core CPU) or disabling that feature
