### ISSUE TITLE
Chests placed on certain planes have no sound and backwards animation

### ISSUE THREAD

**Issue by Yottazoid** [PaperMC/Paper#2354]
### What behaviour is expected:
All chests, placed anywhere, have normal sounds/animations

### What behaviour is observed:
Chests are placed on certain planes every 100 blocks have no sounds and backwards animations.

### Steps/models to reproduce:
Video:
[2019-07-22 2012-52-19.mp4](https://www.dropbox.com/s/g6gmadii284cw7x/2019-07-22%2012-52-19.mp4)

World from video:
[chest world.zip](https://github.com/PaperMC/Paper/files/3415578/chest.world.zip)

- Place chest at `0,0,0`
- Open chest -> No sound, plays closing animation.
- Exit chest gui -> No sound, plays opening animation.
- Place another chest `+x,-z (1,0,-1)`, `-x,+z (-1,0,1)`, `-x,+y (-1,1,0)` and `+y,-z (0,1,-1)`
- Open/close chests -> No sound/backwards animation.

### Plugin list:
None

### Paper build number:
`git-Paper-137 (MC: 1.14.4)`

### Anything else:
Does not occur with Spigot

**Comment by Spottedleaf** [comment]
confirmed happening on paper
