### ISSUE TITLE
use-faster-eigencraft-redstone bug

### ISSUE THREAD

**Issue by seema84** [PaperMC/Paper#2356]
### What behaviour is expected:
I'm getting "one" redstone dust

### What behaviour is observed:
I'm getting "two" redstone dust (item duplication)

### Steps/models to reproduce:
1. set use-faster-eigencraft-redstone on true
2. build this on the pictures
https://i.imgur.com/4ZxPMOz.png
https://i.imgur.com/ft5yKnt.png
3. break the marked block (not the dust)

### Plugin list:
no plugins

### Paper build number:
 This server is running Paper version git-Paper-639 (MC: 1.13.2)
 (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Anything else:
"use-faster-eigencraft-redstone false" stop this bug

**Comment by clrxbl** [comment]
Can confirm on git-Paper-135 (MC: 1.14.4)

**Comment by clrxbl** [comment]
![image](https://user-images.githubusercontent.com/28601081/61633856-47b7b280-ac90-11e9-95e4-c871f9c891c3.png)

Only seems to happen when it's a powered redstone line of 2 wide, doesn't seem to occur when it's longer than 2 or when it's just 1 redstone dust. And it only seems to happen when you destroy the block on top of the power source.

**Comment by HexedHero** [comment]
Confirmed
Video:
https://cdn.hexedhero.com/u/gUrIZXN2eF.mp4

**Comment by GitGoppy** [comment]
Confirmed in Paper 1.14.4 194 still a problem

**Comment by ghost** [comment]
Confirmed on Paper 1.14.4 #223

**Comment by Trigary** [comment]
Still present in git-Paper-43 (1.15.1), but the redstone wire doesn't have to be exactly 2 long, it just needs to be at least 2 long and powered from the block below. Does not work with activator rails. Also works if you eg. use a piston to move the block

**Comment by Spottedleaf** [comment]
Confirmed to be an issue with eigencraft's logic
