### ISSUE TITLE
Random TPS drop, high RAM usage and then hard crash on Paper-137

### ISSUE THREAD

**Issue by iperrealistico** [PaperMC/Paper#2359]
### Link/paste of stack trace

Firstly i get some error dumps like this one:

https://pastebin.com/JGEMBBcV

Then server keeps running.

Then, after some time, the big crash comes.

https://pastebin.com/sQN0brnu

Here is another example

https://pastebin.com/Q7qSKF8J

When it happens, memory usage is almost at 7/7gb.

### Plugin list:
 Announcer*, AntiAFKPro*, ChatControl, ClearLag, CraftBook, EasyBackup*, EasyBackupCore*, EasyQueue*, Essentials, EssentialsProtect, EssentialsSpawn, FarmLimiter, Harbor, IllegalStack, LuckPerms, MOTD, OreReplacerPlugin, ProCosmetics, ProtectionStones, RandomTeleport, RegionUnstuck, Shopkeepers, SimplePortals, StableMaster, SuperbVote, TradeSystem, Votifier, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Looks like it is happening randomly. For a moment i tought that it was caused by craftbook, when two boats collided. But then i tried again and it was just a coincidence. I can't find a correlation with a plugin, so i think this is caused by paper itself.

### Paper build number:
This server is running Paper version git-Paper-137 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by HexedHero** [comment]
I think maybe your RAM is capping and its doing collection to the point where it just crashes.

I see a LOT of advancements which is used for PMs in ChatControl

**Comment by iperrealistico** [comment]
> I think maybe your RAM is capping and its doing collection to the point where it just crashes.
> 
> I see a LOT of advancements which is used for PMs in ChatControl

Hey, happy to see you also here :)

I will try to disable ChatControl on next boot. But at this point i don't even think its a plugin related issue. This issue is probably related to Paper itself, i think.

Edit: here are my timings https://timings.aikar.co/?id=180e710d26274b22b1799cf90ce3eda4

**Comment by Acrothetics** [comment]
I've had a similar occurrence since updating to Paper version git-Paper-136 (MC: 1.14.4). Yet to have it occur on 137 (updated 8 hours ago). At times of crashing, in my case, it appears to be due to Minecraft::World - doChunkUnload and the server hangs while it's taking too long, then crashes. I can post log/timings data later on today. My server host has recommended a reduction of render-view distance from 10 to no lower than 7. But the server had no issues until updating to Paper version git-Paper-136 (MC: 1.14.4) so unsure why it would suddenly now be a problem.

**Comment by iperrealistico** [comment]
> I've had a similar occurrence since updating to Paper version git-Paper-136 (MC: 1.14.4). Yet to have it occur on 137 (updated 8 hours ago). At times of crashing, in my case, it appears to be due to Minecraft::World - doChunkUnload and the server hangs while it's taking too long, then crashes. I can post log/timings data later on today. My server host has recommended a reduction of render-view distance from 10 to no lower than 7. But the server had no issues until updating to Paper version git-Paper-136 (MC: 1.14.4) so unsure why it would suddenly now be a problem.

My render distance is actually set to 4, I think that my server can't handle anything above it when players are above 20/25. 8 GB RAM Intel Core i3 Dual Core (Kimsufi KS7)

If you look at my timings the issue is related to chunk unload also for me. Especially when players join/logout

**Comment by iperrealistico** [comment]
> I think maybe your RAM is capping and its doing collection to the point where it just crashes.
> 
> I see a LOT of advancements which is used for PMs in ChatControl

During night it crashed many times also without chatcontrol..

**Comment by electronicboy** [comment]
Reduce `-XX:G1MaxNewSizePercent=80` to 70/60, for further support, I'd suggest asking on irc/discord, this doesn't really seem like a paper issue as much as something more relating to your setup, I'd also prefer not to flood people with emails given the steps needed to look further into such issues

High chunk related stuff would be the fact that you're running on an HDD, we heavily do not recommend HDDs for servers, especially as they tend to bottleneck the server fairly fast without async chunks (in the works), and still cause some level of performance concern with that feature

**Comment by iperrealistico** [comment]
> Reduce `-XX:G1MaxNewSizePercent=80` to 70/60, for further support, I'd suggest asking on irc/discord, this doesn't really seem like a paper issue as much as something more relating to your setup, I'd also prefer not to flood people with emails given the steps needed to look further into such issues
> 
> High chunk related stuff would be the fact that you're running on an HDD, we heavily do not recommend HDDs for servers, especially as they tend to bottleneck the server fairly fast without async chunks (in the works), and still cause some level of performance concern with that feature

Hey! Thanks for the info. However to me it does not look like a plugin issue, really. I cant really figure it out what is this caused from. Server always ran fine on HDD with G1MaxNewSizePercent=80. It started giving issues yesterday, after i expanded the map. The server could just not handle it, so i restored a backup from the day before. But server did not stop lagging. So i updated to 1.14.4, now the server runs smoothly, until it crashes.

**Comment by electronicboy** [comment]
I'm not saying that it's a plugin issue, My pointers from the information you've provided that this is more related to the hardware you're running or something with your setup, such issues require much more conversion than can realistically be supported on an issue tracker given that we tend to aim to avoid flooding peoples emails for debugging issues which seem more specific to the environment people are running in

> Server always ran fine on HDD
> after i expanded the map
HDDs are very "cool" in how they operate in that expanding the world can increase the amount of time a HDD has to spend processing everything in play, I'm not saying that this is directly the issue, but HDDs and MC are asking for bottlenecks, smaller severs are generally fine, but once you get past a handful of people, the performance from a spinning disk can begin to hurt harshly, given that 1.14 makes this much harsh given that all of the patches to move the work of loading chunks off the main thread have basically been killed

> G1MaxNewSizePercent=80
You're tripping old-gen, which means that there is something potentially funky with your memory setup, reducing that setting may help stabilize that, but when we see old-gen spiking, it's generally a case of invalidating your timing sample given the unpredictable nature and the fact that it will skew timings given the nature of GC

Pretty much all of your errors are pointing to areas where the server is going to be I/O bound to reading data from the disk, or an areas where memory allocation is going to be potentially sporadic
