### ISSUE TITLE
Lunar cycles not handled correctly when setting the time with World.setTime()

### ISSUE THREAD

**Issue by lbenedetto** [PaperMC/Paper#2363]
### What behaviour is expected:
World.setTime(114000) should set the time to midnight during a New Moon

### What behaviour is observed:
The time is set to midnight at whatever phase the moon is currently in (or would be in if it was night)

### Steps/models to reproduce:
This is the entirety of my plugins code necessary to reproduce the issue. Sorry its in Kotlin.
```Kotlin
server.worlds
    .filter { world -> world.environment == World.Environment.NORMAL }
    .onEach { world ->
        world.setGameRule(GameRule.DO_DAYLIGHT_CYCLE, false)
        world.time = 114000
    }
```

### Plugin list:
No plugins, other than the one I'm making (which so far sets that game rule, and then tries to set the time to midnight 

### Paper build number:
Also reproduced on Build 136
```
[20:42:34 INFO]: This server is running Paper version git-Paper-138 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[20:42:34 INFO]: Checking version, please wait...
[20:42:34 INFO]: Previous version: git-Paper-136 (MC: 1.14.4)
[20:42:34 INFO]: You are 1 version(s) behind
```

### Anything else:
`/set time 114000` does work.

It feels like someone clamped the day night cycle to fit in the range of 0-24000 (`input % 24000` perhaps?), and then tried to just keep track of the lunar cycles themselves.

**Comment by electronicboy** [comment]
Have you tried setFullTime? Sounds like you're looking at the wrong method

**Comment by lbenedetto** [comment]
It says it might break redstone clocks, so I'd rather avoid using it.
Is it not possible to set the time forwards without breaking redstone clocks? ie, from 0 to 114000?

**Comment by electronicboy** [comment]
```
    @Override
    public void setTime(long time) {
        long margin = (time - getFullTime()) % 24000;
        if (margin < 0) margin += 24000;
        setFullTime(getFullTime() + margin);
    }
```
Basically, it's only designed to set the time of the current day (or move forward if needed, as per the javadocs...), if you want full control over the time, you need to set it fully
