### ISSUE TITLE
1.14.4 Performance problem

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#2366]
###  Timings or Profile link:
https://timings.aikar.co/?id=f29e7fd91e194526aa589ee7f9040da4

### Description of issue:
İneed more performance.

### Plugin list:
in timings.

### bukkit.yml, spigot.yml, paper.yml, server.properties
[bukkit,paper,spigot.zip](https://github.com/PaperMC/Paper/files/3426687/bukkit.paper.spigot.zip)

### Other helpful links
none

### Paper build number:

Paper-146 (MC: 1.14.4)

**Comment by electronicboy** [comment]
Performance of 1.14, in general, is a known issue, there is no need to create tickets periodically over this. For support with timings, use the forums

**Comment by successed** [comment]
> Performance of 1.14, in general, is a known issue, there is no need to create tickets periodically over this. For support with timings, use the forums

**Why didn't you examine this problem?**

i remove citizens plugin it is fixed i have more performance and tps 20

**Comment by electronicboy** [comment]
The issue tracker is for reporting issues with the server software, not for seeking advice on timings: `For support with timings, use the forums`

**Comment by successed** [comment]
> The issue tracker is for reporting issues with the server software, not for seeking advice on timings: `For support with timings, use the forums`

Okay.
