### ISSUE TITLE
Crash with BettingGames plugin

### ISSUE THREAD

**Issue by DjeyMute** [PaperMC/Paper#2367]
![Capture d’écran (230)](https://user-images.githubusercontent.com/47302852/61805714-930bc580-ae36-11e9-8b5d-c5c764354e73.png)
![Capture d’écran (231)](https://user-images.githubusercontent.com/47302852/61805734-9e5ef100-ae36-11e9-9609-3826f580698a.png)
![Capture d’écran (232)](https://user-images.githubusercontent.com/47302852/61805736-9e5ef100-ae36-11e9-9b29-07c7aac93931.png)
![Capture d’écran (233)](https://user-images.githubusercontent.com/47302852/61805737-9e5ef100-ae36-11e9-8c0b-cfdb2db45ac9.png)

**Comment by electronicboy** [comment]
The plugin is working with skulls in a way which requires looking up their skull profiles, Paper has incremental warnings to tell you what is going on when the server isn't ticking and is highlighting the plugin that is doing these lookups
