### ISSUE TITLE
For the Plugin Safarinet

### ISSUE THREAD

**Issue by DjeyMute** [PaperMC/Paper#2368]
For version 1.14.4 in Safarinet plugin 
https://www.spigotmc.org/resources/safarinet-premium-mob-catcher-plugin-50-off.9732/

By the dev of plugin : 

MasterCake said :
In this case, you need to contact paper, saying that they should sort out their NMS class and package naming. They should equal to Spigot ones.

ERROR Could not pass event PlayerInteractEntityEvent to SafariNet v1.14.4-SNAPSHOT 
22.07 18:55:35 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.EntityTypes.e()Ljava/lang/String; 
22.07 18:55:35 [Server] INFO at de.Linus122.SafariNet.version.v1_14_R1.SafariNet.getEntityId(SafariNet.java:110) ~[?:?] 
22.07 18:55:35 [Server] INFO at de.Linus122.SafariNet.version.v1_14_R1.SafariNet.saveEntity(SafariNet.java:49) ~[?:?] 
22.07 18:55:35 [Server] INFO at de.Linus122.SafariNet.version.v1_14_R1.SafariNetFactoryWrapper.catchEntity(SafariNetFactoryWrapper.java:139) ~[?:?] 
22.07 18:55:35 [Server] INFO at de.Linus122.SafariNet.Listeners.CaptureListener.interact(CaptureListener.java:190) ~[?:?] 
22.07 18:55:35 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor487.execute(Unknown Source) ~[?:?] 
22.07 18:55:35 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137] 22.07 18:55:35 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137] 22.07 18:55:35 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137] 22.07 18:55:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1983) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-137] 
22.07 18:55:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by mikroskeem** [comment]
Tell plugin author to update the plugin.

**Comment by electronicboy** [comment]
The method it's complaining about was renamed in 1.14.4
