### ISSUE TITLE
Items are disappearing when dropped or broken

### ISSUE THREAD

**Issue by timothykra** [PaperMC/Paper#2369]
### What behaviour is expected:
___For the item to drop onto ground___

### What behaviour is observed:
___Item is dropped and vanishes into thin air___

### Steps/models to reproduce:
___Drop item, check___

### Plugin list:
___ArmorStandEditor.jar
Banknotes.jar
BuycraftX.jar
ChestShop.jar
Citizens.jar
CommandHook.jar
CoreProtect-2.16.3%20%283%29.jar
Duels-3.2.3.jar
EssentialsX-2.17.0.0.jar
EssentialsXSpawn-2.17.0.0.jar
FastAsyncWorldEdit-bukkit-1.13.106.jar
FileZilla_3.42.1_win64-setup.exe
GameModer.jar
GreatKits.jar
GriefPrevention.jar
HealthBar%20%281%29.jar
HolographicDisplays.jar
iDisguise.jar
Jobs4.13.0.jar
LootChest-1.9%20%281%29.jar
MarriageMaster%20%281%29.jar
Multiverse-Core-2.5.0.jar
Quests-3.7.2.jar
Staff%2B.jar
SuperVanish%20%281%29.jar
Towny.jar
TownyChat.jar
TownyNameUpdater.jar
tradeshop-2.0.2-2019-05-29T19.46.38.jar
Trading_v3.2.jar
UltraPermissions.jar
Vault.jar
VoxelSniper-5.171.0-SNAPSHOT.jar
worldedit-bukkit-6.1.9.jar
___

### Paper build number:
___1.13.2-R0.1-Snapshot___

### Anything else:
___This randomly happens when a new person joins the server, or just sometimes when a second person joins the server.___

**Comment by VADemon** [comment]
Remove the Filezilla plugin and try again.

Also `/version`

**Comment by timothykra** [comment]
didnt work 

and I did /version 1.13.2 came up

**Comment by zachbr** [comment]
Has this been tested without ~30 plugins? Or verified by anyone else?

**Comment by timothykra** [comment]
It has been verified by anyone that comes on the server and the server had no plugins and the glitch was still there

**Comment by gp-Airee** [comment]
can confirm

**Comment by zachbr** [comment]
Someone having this issue is going to need to dig into it themselves or provide some sort of consistent way to reproduce it. I can't.

**Comment by timothykra** [comment]
what do you mean by reproduce?

**Comment by Draycia** [comment]
Try to cause it to happen again and figure out the steps to cause it to happen

**Comment by timothykra** [comment]
Most of the time when i restart my server, it fixes and comes back when a new person to the server joins

**Comment by timothykra** [comment]
if you want like proof, i can try a video

**Comment by ghost** [comment]
We don't need proof, we need steps to reproduce on a clean server

**Comment by timothykra** [comment]
i dont know what caused it, or what is causing it. The only thing I know is that the glitch is there, sometimes i can restart the server, it will fix itself and then when a new player joins, it comes back.

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
