### ISSUE TITLE
Wither projectiles not properly hurting endermen

### ISSUE THREAD

**Issue by KrisEike** [PaperMC/Paper#2370]
With the "Optimize-explosions:" setting set to true, wither rose farms get significantly worse, and often the wither fails to hit the endermen, or the endermen doesnt die from being hit. 

Basically, this setting is making the wither projectiles blow up without enderman taking any damage most of the time. Just the explosion and that's it.

**Comment by zachbr** [comment]
The issue templates aren't there to be ignored. Fill one out please.
