### ISSUE TITLE
1.14 Hopptimization [funding available for optimizations]

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#2371]
###  Timings or Profile link:
https://timings.aikar.co/?id=09e8086195324acd8fa9edf06bb47b07

### Description of issue:
1.14 performance issues are well known. Do you guys think it's a lost cause until 1.15?

Idk what can be done to optimize, but in case there is something for hoppers. That's the #1 source of lag atm for LMC.

### Plugin list:
Bot*, CheaperPhysicsEvent, ChestShop, ChestShopNotifier*, ClaimslistClassifier, CoreProtect, dynmap*, Dynmap-GriefPrevention*, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsSpawn, GPAuctions, GPRealEstate*, GriefPrevention, GroupManager*, InGameMotd, PlaceholderAPI*, PlayerVaults*, PluginLibrary*, ProtocolLib, PVPToggle*, SuperTrailsPro*, Vault, WorldBorder*, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://pastebin.com/DvZFx4qQ

### Paper build number:
1.14.4 build 146

**Comment by BillyGalbreath** [comment]
The timings posted show zombie villagers being the laggiest thing (28.78%) and hoppers 2nd (13.96%). You full tick is only overloaded by 6.72% (106.72% total), so eliminating (or reducing) zombie villagers should alleviate your lag and give you some breathing room.

**Comment by NullCase** [comment]
eliminating them for breathing room.

It sounds like the solution is to play less minecraft, because we all know more minecraft is what happens when people play.

what you're saying makes sense, but do you think it's really a solution?

**Comment by BillyGalbreath** [comment]
It's a temp solution that needs constant monitoring. It will change over time, so you have to know what to look for.

/kill @e[type=zombie_pigman]

I do this on my server from time to time. It's mostly zombie villagers and iron golems for me, tho. Tps goes back to normal for a few hours until something else decides to run amuck.

**Comment by NullCase** [comment]
I don't know, because that Zombie Villager lag only appears during the first interval. And if you select everything else it's armor stands using 38%. Besides, there aren't 2700 zombie villagers going around.

Something else is going on here.

**Comment by CeIebrimbor** [comment]
Apply this guide, you are passing up a lot of optimization opportunity.
https://www.spigotmc.org/threads/guide-server-optimization.283181/

Close this issue. Performance support is more appropriate for the Paper Discord.
https://discord.gg/jETyjUw

**Comment by NullCase** [comment]
@c

**Comment by NullCase** [comment]
@CeIebrimbor Thanks for the guide. I'll test these out today. Do you have a donation option?

**Comment by CeIebrimbor** [comment]
I don’t take donations. Please donate to Paper, they make it all possible and put in 50x more time than me :smile:

**Comment by NullCase** [comment]
you bet.

**Comment by NullCase** [comment]
@CeIebrimbor here's the receipts. 
![Paper Donation in August](https://user-images.githubusercontent.com/32785664/62387166-e3b2ab00-b527-11e9-92b3-72dc3a3a7ad2.png)

**Comment by CeIebrimbor** [comment]
Did not need proof (I believed you). But good on you. Well deserved!
