### ISSUE TITLE
1.12.2: Anti-Xray issue with Datavalue's Block

### ISSUE THREAD

**Issue by Biorn1950** [PaperMC/Paper#2372]
PaperMC 1.12.2 (lastest)

I tried to add in the config file paper.yml hiddenBlocks Mossy Stone Brick Monster Egg.

block 97 (monster_egg) with DataValue 3 (Mossy Stone Brick Monster Egg) and that don't affect this block.

>    anti-xray:
      enabled: true
      engine-mode: 2
      chunk-edge-mode: 1
      max-chunk-section-index: 3
      update-radius: 2
      hidden-blocks:
      - 97:3 //DON'T WORK
      replacement-blocks:
      - stone
      - planks
>
How can I add this block ?

If somebody could help me with this issue, you're welcome. ;)

**Comment by BillyGalbreath** [comment]
https://minecraft.gamepedia.com/Infested_Block#Data_values

![image](https://user-images.githubusercontent.com/332527/61938389-939b7d80-af56-11e9-9c84-7dbd3419d845.png)

**Comment by Biorn1950** [comment]
Theses namespaced id are for 1.13 and above

**Comment by Biorn1950** [comment]
> ![image](https://raw.githubusercontent.com/Biorn1950/Divers/master/monster_egg.PNG)

Namespaced ID in 1.12

**Comment by BillyGalbreath** [comment]
Yeah, I forget we're still supporting 1.12 for some weird reason. IDK, man. I haven't touched or looked at 1.12 in over a year already. Someone else might see this and know, but 1.12 is too far legacy for myself to even be bothered :3

**Comment by NullCase** [comment]
@stonar96 is your guy to ask @BillyGalbreath.

**Comment by electronicboy** [comment]
The anti xray mechanism doesn't support numerical IDs or data values
