### ISSUE TITLE
i have adventure mode and i can destroy painting

### ISSUE THREAD

**Issue by LoToRTv** [PaperMC/Paper#2374]
i have adventure mode and i can destroy painting.

**Comment by electronicboy** [comment]
You forgot to fill in the template... Would also be nice to know if this issue is applicable to vanilla/craftbukkit/spigot

**Comment by LoToRTv** [comment]
vanilla is it basic minecraft settings for mc? or bug 1.14.4 ?

**Comment by LoToRTv** [comment]
I thought it was a spigot fault...
now i tried in on signl

**Comment by AzureAaron** [comment]
Confirmed on Vanilla 1.14.4, git-Spigot-1981d55-c88867e, git-Paper-147 and git-Bukkit-c8867e

**Comment by electronicboy** [comment]
https://bugs.mojang.com/browse/MC-579
Working as intended, apparently
