### ISSUE TITLE
velocity

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#238]
http://pastebin.com/vqq5Eezp

**Comment by FunnyCraft** [comment]
and http://pastebin.com/2nppy2BB

**Comment by kashike** [comment]
This is not a bug, it is a warning. See #217, #40

**Comment by FunnyCraft** [comment]
http://pastebin.com/2nppy2BB - This problem remained.

**Comment by kashike** [comment]
Again, that is not a bug/problem with Paper.
