### ISSUE TITLE
Rideable entities are able to desync

### ISSUE THREAD

**Issue by Paralusion** [PaperMC/Paper#2380]
### What behaviour is expected:
___What you expected to see___
As soon as you dismount the entity (client-sidely), you'd get kicked for inappropriate behaviour.
### What behaviour is observed:
___What you actually saw___
You can client-sidely dismount the entity and therefor desync it from the server, meaning you can do a lot of stuff with it, such as bypassing anti-cheats.
### Steps/models to reproduce:
Client-sidely dismount the entity
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
Does not matter
___A list of your plugins___

### Paper build number:
Does not matter
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by zachbr** [comment]
Try again, fill out the template completely. We decide what does and doesn't matter, not you.

**Comment by VADemon** [comment]
https://bugs.mojang.com/browse/MC-101247 ?

**Comment by Paralusion** [comment]
Plugin list: None
Paper build number: 1681

**Comment by zachbr** [comment]
That's just exceedingly unfortunate timing on your part. Support for MC 1.12.2 was dropped this morning.
