### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by kennytv** [PaperMC/Paper#2381]
### Link/paste of stack trace

https://paste.mykns.net/edizevezam.md

Not sure if this is just a duplicate of #2147, but since the stacktrace seems different, I'm just going to post it

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___ -> pretty sure this is a Vanilla/Spigot/Paper bug, since there is also no sign of another plugin interfering in the stacktrace

### Plugin list:
ProtocolLib, PeX, a custom one (that doesn't mess with entities/arrows)

### Actions to reproduce (if known):
*PROBABLY* someone shooting a firework with a crossbow, though I am not sure, since there were around 75 players doing all sorts of stuff ¯\_(ツ)_/¯

### Paper build number:
Paper 146 for 1.14.4

**Comment by electronicboy** [comment]
We need the full log

**Comment by kennytv** [comment]
@electronicboy https://paste.mykns.net/peyuriviro.md ... or like, "full" full? 👀

**Comment by electronicboy** [comment]
The lack of incremental warnings either indicates that you disabled them (In which case, we need a log with it enabled), or that you have deeper issues and your jvm/server was overloaded which is somewhat outside of what we can look into

**Comment by kennytv** [comment]
We set watchdog warnings higher, I'll try my luck reproducing the bug with it set to warn as usual

**Comment by noahchrde** [comment]
@electronicboy here we got the same crash in Minecraft-Suro again:
https://paste.mykns.net/emafezediw.md

https://youtu.be/gXVY-9LHiZ0?t=4952
https://www.twitch.tv/videos/460555395?t=01h13m01s

We hope you can fix this fast. Thank you!

**Comment by kennytv** [comment]
^ See the Twitch clip for the most probable cause, the dump now also contains the incremental watchdog warnings

**Comment by kennytv** [comment]
This crash does *only* occur with Paper (not reproducible with Spigot); Shoot with a piercing crossbow through a hidden player.

A video with repro proof and a more detailled description will be sent by Noah later, though that info should suffice to start digging I guess :*

**Comment by noahchrde** [comment]
Here you can see it in the video:
https://www.youtube.com/watch?v=alQ0zC8QHvg&feature=youtu.be

The left player is simply hidden with the follwing code:
`final Player target = Bukkit.getPlayer("Noaaah");
player.hidePlayer(this, target);`

The user on the right side has a crossbow with a piercing two enchantment.
