### ISSUE TITLE
Disable ticking for ItemFrames

### ISSUE THREAD

**Issue by LoneDev6** [PaperMC/Paper#2383]
**Is your feature request related to a problem? Please describe.**
It's related to TPS drops when too many itemframes are created in loaded chunks

**Describe the solution you'd like**
Add a simple patch similar to [0125-Allow-disabling-armour-stand-ticking.patch](https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0125-Allow-disabling-armour-stand-ticking.patch)

**Describe alternatives you've considered**
Nothing

**Additional context**
Nothing

**Comment by HexedHero** [comment]
Yes please !

**Comment by BillyGalbreath** [comment]
I was going to add something like this in the past, but spigot already has a limiter up in there.

From spigot.yml:
![image](https://user-images.githubusercontent.com/332527/62012978-60bdd900-b152-11e9-89e5-4d6f9da2cbbe.png)

By default, item frames already only tick once every 5 seconds.

**Comment by CeIebrimbor** [comment]
Semi-Related...
What functionality is lost (if any) from bumping the `hanging-tick-frequency` up? Would doubling it cause weird behavior?

**Comment by kickash32** [comment]
Not really, the only effect is delayed death (it getting popped off).

**Comment by electronicboy** [comment]
```java
if (this.e++ == this.world.spigotConfig.hangingTickFrequency && !this.world.isClientSide) { // Spigot
            this.e = 0;
```
is basically what determines if a hanging entity should tick, it would (probably) be better to use the entity ID to offset the current tick number instead of relying on that value, as it's not persistent, so you could easily end up with several dozen frames all ticking on the same tick

**Comment by CeIebrimbor** [comment]
Fair to say that Paper would never release an option to break item frames by not ticking them? The PR by kickash is the only reasonable way to help item frame ticking load. Maybe this gets closed?...

**Comment by kickash32** [comment]
You can already effectively disable item frame ticking by setting `hanging-tick-frequency` to a really high number like `2147483647` (highest possible integer in java). Note that `hanging-tick-frequency` actually sets the period of ticks to be skipped (should really be named `hanging-tick-period`)

**Comment by CeIebrimbor** [comment]
And break a bunch of vanilla stuff in the meantime... 😓 

But yeah, if the request is to kill vanilla behavior, it's already available.

**Comment by LoneDev6** [comment]
> 
> 
> And break a bunch of vanilla stuff in the meantime... 😓
> 
> But yeah, if the request is to kill vanilla behavior, it's already available.

Can you write a list of which behaviors would be broken?
Thanks

**Comment by wizjany** [comment]
Anything that passively breaks item frames, like water flowing over them, won't. Anything else that depends on item frames ticking also won't work.

I believe direct damage still will work tho.

**Comment by LoneDev6** [comment]
So I see no issue at all, if someone want to be able to disable itemframes ticking then this feature would be nice to be added.
If @CeIebrimbor doesn't want to disable itemframes ticking, then he could just leave the upcoming option to `true `;)

**Comment by electronicboy** [comment]
You wouldn't want not ticking them in general to be global behavior, there are some areas where ticking them is irrelvant, e.g. spawn areas, probably would be better as an event so that plugins could selectivly cancel anything

**Comment by LoneDev6** [comment]
> 
> 
> You wouldn't want not ticking them in general to be global behavior, there are some areas where ticking them is irrelvant, e.g. spawn areas, probably would be better as an event so that plugins could selectivly cancel anything

Nice idea! Would be great

**Comment by BillyGalbreath** [comment]
> So I see no issue at all, if someone want to be able to disable itemframes ticking then this feature would be nice to be added.

Not sure why the current `hanging-tick-frequency` option is unusable for you? As stated before, just set it to `2147483647` to effectively disable them from ticking (that's about 204 years between ticks, real time).

The first tick for item frames is very important one as its the one that sets to rotation, the bounding box (the thing that makes it so players can interact with it), etc. Without it all item frames will appear to be facing south regardless of attached position. This makes the current `hanging-tick-frequency` option already the best option.

**Comment by LoneDev6** [comment]
> 
> 
> > So I see no issue at all, if someone want to be able to disable itemframes ticking then this feature would be nice to be added.
> 
> Not sure why the current `hanging-tick-frequency` option is unusable for you? As stated before, just set it to `2147483647` to effectively disable them from ticking (that's about 204 years between ticks, real time).
> 
> The first tick for item frames is very important one as its the one that sets to rotation, the bounding box (the thing that makes it so players can interact with it), etc. Without it all item frames will appear to be facing south regardless of attached position. This makes the current `hanging-tick-frequency` option already the best option.

Good to know, thanks!

**Comment by CeIebrimbor** [comment]
_waits for issue to be closed by OP_
