### ISSUE TITLE
Add api/event allow plugin add / remove somethings in tick list.

### ISSUE THREAD

**Issue by Ghost-chu** [PaperMC/Paper#2384]
**Is your feature request related to a problem? Please describe.**
Add api/event allow plugin add / remove somethings in tick list.
So this allow plugin remove stuffs from ticking list.
It powerful for performance improvement plugin.

**Describe the solution you'd like**
A new api or event was added in Paper

**Describe alternatives you've considered**
Nope

**Additional context**
I already know paper can clear-tick-list, so modify it shouldn't very hard...

**Comment by Spottedleaf** [comment]
What type of tick list? There are many in this game.

**Comment by Ghost-chu** [comment]
I think entity and tile will very useful

**Comment by electronicboy** [comment]
No, because pretty much: https://aikar.co/2015/10/08/spigot-tick-limiter-dont-use-max-tick-time/
