### ISSUE TITLE
Riding a boat above a soul sand bubble column causes players to teleport up 2 blocks 

### ISSUE THREAD

**Issue by MarkElf** [PaperMC/Paper#2391]
### What behaviour is expected:
Not teleporting up two blocks would be ideal.

### What behaviour is observed:
Teleporting up two blocks.

### Steps/models to reproduce:
1. Find an ocean or large body of water source blocks.
2. Place at least a 3x3 patch of soul sand on the bottom of said ocean/water.
3. Ride a boat over the top of bubbles.
4. Teleport up two blocks

### Plugin list:
None. I guess protocollib which doesn't impact this in any way.

### Paper build number:
b152 - https://github.com/PaperMC/Paper/commit/93891ad57a8317678c41bad4f755627821db0eaa

### Anything else:
I guess here is an image showing someone else recreating it - https://cdn.discordapp.com/attachments/538695199744851989/605975366456311838/unknown.png. Seems to be a vanilla bug but I would hope it could be patched as I don't have much faith in Mojang pushing a 1.14.5 update to fix one thing. Would probably be a good idea to let Spigot staff know to fill them in too, I'm just not sure how to navigate there - I did send a support request for this issue.

**Comment by kickash32** [comment]
Boats in general are very buggy due to desync between client and server. They will likely require an overhaul which only Mojang is able to do.

**Comment by MarkElf** [comment]
This was an issue with minecraft itself.
