### ISSUE TITLE
[Suggestion] Add Trident to PlayerLaunchProjectileEvent

### ISSUE THREAD

**Issue by ShaneBeee** [PaperMC/Paper#2394]
**Is your feature request related to a problem? Please describe.**
Not really no. Kind of sort of. More of a personal problem, trying to get a way to catch when a player shoots a trident.

**Describe the solution you'd like**
I would like to see you guys please add Tridents to the PlayerLaunchProjectileEvent. When looking thru the patch for this event, it seems to catch eggs, snowballs, potions and enderpearls, but not tridents. 

**Describe alternatives you've considered**
I feel like Ive tried many things, and nothing I could do to find a way to catch when a player actually throws a trident. One thing I tested for started is the interact event, but the issue there is it is fired when the player first clicks to "pull back" the trident, but not when it actually launches. 

**Additional context**
You guys are awesome, I love you!!

**Comment by ghost** [comment]
Yes please!

**Comment by HexedHero** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-5207?jql=

**Comment by Proximyst** [comment]
```java
  @EventHandler
  public void onCreate(ProjectileLaunchEvent event) {
    Bukkit.broadcastMessage("Launched projectile: " + event.getEntityType() + " by " + ((Entity) event.getEntity().getShooter()).getName());
  }
```
![https://uwu.whats-th.is/7ajR8SS.png](https://uwu.whats-th.is/7ajR8SS.png)

Fixed at some point since issue creation.
