### ISSUE TITLE
Plugin incompatibility with Cosmetics Teasure

### ISSUE THREAD

**Issue by therealatsuga** [PaperMC/Paper#2395]
### What behaviour is expected:
A working plugin 

### What behaviour is observed:
Many error-messages and parts of plugin not working

### Steps/models to reproduce:
install the plugin on a paper-server

### Plugin list:
doesn't matter? 

### Paper build number:
git-Paper-148

### Anything else:
Maybe contact to the developer of cosmetics treasure (https://www.spigotmc.org/resources/cosmetics-treasure-1-10-1-14-1-14-support.33313/)
RDev_

**Comment by ghost** [comment]
Contact the developer of the plugin to fix it

**Comment by electronicboy** [comment]
"many error messages"
If you want assistance, you'll need to provide information, such as the errors, it's also not your call as to what information is relevant, and would be nice if you'd fill in the template properly.

**Comment by zachbr** [comment]
We do not provide support for premium plugins.
We cannot go around buying all of them or jumping through specific hoops in order to look into issues that may (or may not) be our problem.

If the author or some user wants to send us a stacktrace or a simplified test case with code showing us the issue that's fine, but we cannot buy random premium resources just to see what's wrong.

**Comment by therealatsuga** [comment]
Well, I'm very sorry I didn't fill out properly the form. I'm not a developer and my english is crappy because it's not my native language. I've already contactet the developer of the plugin. On the other side, Paper promises ALL spigot-plugins are also gonna work on paper, so I just tried to report my problem. I'm sorry I'm to stupid for github... I just don't know what a stacktrace or a simplified test case is.

The only thing I can provide is my log.

https://pastebin.com/Guuy3r8M

**Comment by zachbr** [comment]
The issue in your stacktrace would occur on Spigot as well. Ensure that your plugin is up to date, otherwise contact the developer. They are still treating Cats as a type of Ocelot which has not been the case for some time now in Minecraft.
```[15:44:24 ERROR]: Could not pass event InventoryClickEvent to CosmeticsTreasure v1.13
java.lang.UnsupportedOperationException: Cats are now a different entity!
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftOcelot.setCatType(CraftOcelot.java:25) ~[patched_1.14.4.jar:git-Paper-148]
at me.RDev.pets.AngryCat.playAngryCat(AngryCat.java:30) ~[?:?]
at me.RDev.GUIListener.InventoryPets(GUIListener.java:329) ~ ```
