### ISSUE TITLE
EntityMinecartChest High Tick Cpu Usage

### ISSUE THREAD

**Issue by malsem** [PaperMC/Paper#2397]
###  Timings or Profile link:
https://timings.aikar.co/?id=e9e417eee0d749d183a29b35de01586b#timings

### Description of issue:
EntityMinecartChest Is Consuming A Lot Of Cpu Usage

### Plugin list:
Plugins (46): AdvancedHelp, AntiCommandSuggestions, AsyncWorldEdit, AuthMe, Bank, betterSleeping*, BlockLocker, BlocksHub, ChatManager, ChopTree2, Citizens, CitizensCMD, Core, CoreProtect, DeathTax*, DiscordSRV, EnchantControl, EpicRename, Essentials, EssentialsGeoIP, EssentialsSpawn, ezBroadcast*, FarmLimiter*, GriefPrevention, HolographicDisplays, IllegalStack, LuckPerms, OreReplacerPlugin, PermissionGamemode*, PlaceholderAPI*, ProtocolLib, RandomTeleport, RFChairs, SAML, ShopChest, SilkTouchSpawners, SkinsRestorer, SuperVanish, TAB, Vault, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags, XRayDetector*

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://pastebin.com/28w3h7jm

### Paper build number:
This server is running Paper version git-Paper-"1832d799" (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by kickash32** [comment]
Doesn't really seem like a paper problem, you just seem to have a lot more chest mine carts compared to any other entity.
