### ISSUE TITLE
Holograms/Armor Stands

### ISSUE THREAD

**Issue by Mikgreg** [PaperMC/Paper#24]
Hi

In my creative mode server people are somehow able to place invisible armor stands which create holograms, I don't have any information right now on how they are made as I'm just finding them all over the map and removing them.

The stands can be placed on worldguard & plotsquared protected areas, as well as the normal vanilla spawn protection.

I'm running paperspigot version
http://i.imgur.com/7AhCfg8.png

**Comment by L4BORG** [comment]
Hacked clients? They're able to spawn items with any NBT data, http://minecraft.gamepedia.com/Chunk_format if player is in GM1, tho I'm not sure if that's the issue...

And you're using https://github.com/filoghost/HolographicDisplays/ or something like HD?

**Comment by zachbr** [comment]
If this continues on 1.9, please let us know
