### ISSUE TITLE
NPE in StructureGenerator

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#240]
http://pastebin.com/2jEpCnRd

**Comment by willies952002** [comment]
Please use the issue template, as without information regarding the issue, we cannot fully investigate this. I have provided the pertinent template for you to use with the information you have already provided filled in.

---

> # Crash, Stacktrace
> 
> ### Link/paste of stack trace:
> 
> http://pastebin.com/2jEpCnRd
> 
> ### Plugin list:
> 
> **_A list of your plugins**_
> 
> ### Actions to reproduce (if known):
> 
> **_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue**_
> 
> ### Paper build number:
> 
> git-Paper-702

**Comment by FunnyCraft** [comment]
http://SSMaker.ru/fadfeb66/

**Comment by FunnyCraft** [comment]
INFO Plugins (62): JoinCommands, FunnyCasino, ChatGame, EliteWeapons, CheatItemWatchDog, DynPad, FunnyCr, TickOptimizer, RandomPlacer, FunnyCase, NoteBlockAPI, PotionFix, RedstonePower, FunnyCraft, HideStream, UralChat, WorldEdit, HealthBar, SimpleElevator, Essentials, ClearLag, SwornGuns, AutoMessage, Chairs, WorldBorder, SunCraftHeads, Multiverse-Core, FunnyContracts, MRPvPMoney, PermissionsEx, SuperSpleef, Funnydone, MineResetLite, CustomJoinItems, TopStatistics, Vault, UralClans, ProtocolSupport, DrugMeUp, DrinksCMD, Scavenger, Marriage, WorldGuard, ChestCommands, McMusic, EssentialsSpawn, ChatManager, ShopGUIPlus, TitleManager, BowSpleef, mwParkour2, Jobs, LimitedWorldEdit, ProtocolLib, NoCheatPlus, PayDay, ColoredTags, WGLW, AuthMe, Passport, ScoreboardStats, ShoppingCartReloaded

**Comment by zachbr** [comment]
Please start following the issue templates when you create issues.

**Comment by zachbr** [comment]
Still an issue on latest?
