### ISSUE TITLE
Entity/Mob not shown (Dissappear)

### ISSUE THREAD

**Issue by kravinkebab** [PaperMC/Paper#2400]
### What behaviour is expected:
___What you expected to see___
Mobs/Entity shown
### What behaviour is observed:
___What you actually saw___
I don't see any mobs/entity
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
https://youtu.be/189X769z9gQ
### Plugin list:
___A list of your plugins___
Plugins (50): KeepItems, PlaceholderAPI, AntiSpam, SkinsRestorer, antiRedstoneClock, GSit, AntiCurse, CoreProtect, GroupManagerPex, Wild, WorldEdit, OreReplacerPlugin, FirstJoinPlus, XRayDetector, SAML, LoginSecurity, VeinMiner, ClearLag, AutoMessage, PlayerTime, AdvancedBan, Votifier, IPLimit, Multiverse-Core, VotingPlugin, FishinRoulette, PermissionsEx, LangUtils, StaffChatReloaded, Vault, Warnings, Rankup, LWC, WorldGuard, SimplePortals, MorphShops, Essentials, UltimateStacker, Jobs, RedProtect, CrateReloaded, TradeSystem, EssentialsChat, TAB, ChestShop, EssentialsProtect, EssentialsAntiBuild, EssentialsSpawn, TitleManager, DynamicShop
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
paper-154
### Anything else:
___Anything else you think may help us resolve the problem___
I don't know, but this is happen when i want to upgrade the version from 1.14.3 Spigot into 1.14.4 paper.
When i did, all entity are like invisible but if i downgrade it to 1.14.3 it's become normal

**Comment by electronicboy** [comment]
Update your plugins, specifically Tab
