### ISSUE TITLE
Server OOM

### ISSUE THREAD

**Issue by Bobcycle** [PaperMC/Paper#2403]
### Link/paste of stack trace
https://paste.md-5.net/tocijabiwi.rb

### Plugin list
___A list of your plugins___/pl
![image](https://user-images.githubusercontent.com/43217357/62415713-a7b63d80-b62e-11e9-8cb2-91830ff0bb38.png)

### Actions to reproduce (if known):
I have not been able to make the server run out of memory on command, what I do notice is that it only happens due to our server peak times. 

### Paper build number:
This server is running Paper version git-Paper-"1832d799"
 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Previous version: git-Paper-152 (MC: 1.14.4)

Heap dump: https://drive.google.com/file/d/1DQXD-1NuKm7lG2oxcFKFFJ_yVq9rFpZm/view?usp=sharing
Chunk debug report: [chunks-2019-08-03_17.19.00.txt](https://github.com/PaperMC/Paper/files/3464132/chunks-2019-08-03_17.19.00.txt)
![image](https://user-images.githubusercontent.com/43217357/62415113-ecd57200-b624-11e9-9ad5-804119505df9.png)

![image](https://user-images.githubusercontent.com/43217357/62415117-f6f77080-b624-11e9-8b29-879af5537834.png)
![image](https://user-images.githubusercontent.com/43217357/62415242-d03a3980-b626-11e9-9e28-fa518f65150e.png)

I am running out of memory on my 1.14.4 server, have undertaken a few steps to try and fix this.
1. Profiled over 20+ heap dumps which all say it's chunk related.
2. Switched to paper build "git-Paper-"1832d799" which is a test build.
3. Made an attempt at unloading chunks trough other plugins without success.
4. Allocated 15GB instead of the normal 10GB to see if the behavior will change.

Note that changing to a test build and allocating 15GB is out of the norm. I am aware of this, however, this is purely to try and solve the issue which I have been facing. This also happens under normal conditions, running the normal builds and with 10GB allocated.

This is my start script under here. I have a few heap dumps which I have profiled lined up, I don't know if sharing a 2GB file would go a long way, if screenshots would suffice, please tell me.

```
#!/bin/sh

while true;
do

  echo "Starting server: Survival 1.14.4 (10GB) (25564)"
  sleep 1 
  echo "Killing port 25564/tcp"
  fuser -k 25564/tcp 
  echo "Press CTRL + C to abort the startup"
  sleep 1

  java -Xms10G -Xmx10G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=70 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+HeapDumpOnOutOfMemoryError -Dusing.aikars.flags=mcflags.emc.gs -jar paperclip.jar

  echo "The server crashed, or stopped unexpectedly!"

done
```

**Comment by Bobcycle** [comment]
#2106 
> Please take this issue to its own issue or on discord, people get notified here.
> 
> Secondly, if you don't bother to take the dump when you've OOM'd or about to it's useless.

I don't know how to directly quote someone, but these heap dumps automatically get dumped once the server runs out of memory. This is also in my startup script: -XX:+HeapDumpOnOutOfMemoryError

If anyone would be able to tell me how to continue or how to supply more information regarding this issue, that'd be amazing since I feel like I have been able to supply anything which I can.

**Comment by Spottedleaf** [comment]
can you provide the crashlog associated with the heapdump

**Comment by Bobcycle** [comment]
Server (crash) log: https://paste.md-5.net/jujesutufu.md
Crash report: https://paste.md-5.net/tocijabiwi.rb

Edit: Cause seemed to be ProtocolSupport?
