### ISSUE TITLE
disable-chest-cat-detection not taking effect

### ISSUE THREAD

**Issue by OS-Void** [PaperMC/Paper#2406]
### What behaviour is expected:
If set to true, the cat shouldn't detect chests (save some server work) to go sit on them.

### What behaviour is observed:
The cat walks around a little, eventually it detects a chest and it'll walk to it and sit on it, and repeat.

### Steps/models to reproduce:
Tamed a wild cat (not to be confused with an ocelot), idle a little around a chest.
(Tried setting it both to true, and to false, and on both runs it still detected the chest, same behavior)

### Plugin list:
None.

### Paper build number:
git-Paper-152

**Comment by electronicboy** [comment]
https://paper.readthedocs.io/en/stable/server/configuration.html#game-mechanics

It prevents chests looking for cats, not the inverse
