### ISSUE TITLE
Feature Request to add Tab-complete for the op command in console if players are online, used to work in 1.12 but doesn't in 1.13 now

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#2407]
**Is your feature request related to a problem? Please describe.**
Tab-complete for op in console used to work in previous minecraft version (eg: 1.12.2) when players are online but no longer does, possible to re-add for server versions 1.13-1.14.4?

**Describe the solution you'd like**
To add tab-complete for the op command in console if players are online

**Describe alternatives you've considered**
Can still tab complete the op command as a player (with the permission) so doing that for now, just can't in console

**Comment by electronicboy** [comment]
This doesn't even seem to work in vanilla? *internally sighs*

**Comment by axemwa** [comment]
Oh so are u saying it's something that can't be done or that you're surprised that it's not in vanilla?

**Comment by BillyGalbreath** [comment]
This seems to be fixed already
