### ISSUE TITLE
TPS issue under 4 tps constantly

### ISSUE THREAD

**Issue by ColaIan** [PaperMC/Paper#2409]
###  Timings or Profile link: https://timings.aikar.co/?id=a03071c36aa94a0986e7d8846f25e8b1
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___

### Description of issue: Low tps
___If applicable___

### Plugin list: Plugins (91): AdvancedAchievements, AdvancedMonthlyCrates, AsyncWorldEdit, BungeeTabListPlus, ChestSort, Citizens, ClearLag, CloudNet-Bridge, CMI, CommandItems, Companions, CoreProtect, CrazyAuctions, CrazyEnchantments, CrazyEnvoy, DailyRewards, DeluxeMenus, DeluxeTags, DropEdit2, EasterEggs, Elevator, EliteLootbox, EpicCraftingsPlus, EpicFarming, EpicFurnaces, EpicHeads, EpicHoppers, EpicSpawners, FabledSkyBlock, FastAsyncWorldEdit, FeatherBoard, HolographicDisplays, ID-Library, InventoryRollback, ItemEdit, JukeBox, LiteBans, LobbyPresents, LuckPerms, LuckPerms-GUI, MineSync, Minions, Mixer, Multiverse-Core, MVdWPlaceholderAPI, MyCommand, NoteBlockAPI, OldCombatMechanics, OreCrops, PlaceholderAPI, PlayerVaults, PluginConstructorAPI, PlugMan, ProQuests, ProtocolLib, React, Recount, ReferralSystem, RestrictedCreative, ScratchCards, SCTFreeze, SCTMoneyPouch, SCTNick, SelectionVisualizer, ShopGUIPlus, Spartan, SpartanNotify, SuperVanish, TAB, TDG, TradeMe, TradeSystem, TrollBoss, UltimateAutoRestart, UltimateFishing, UltimateKits, UltimateRepairing, UltimateStacker, UltimateTimber, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidChest, VoidSpawn, Votifier, VotingPlugin, WolfyUtilities, WorldEdit, WorldGuard, YoutubeBridge
___All plugins running on the server___

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://pastebin.com/iaGpqvCP
https://pastebin.com/F7iFgge6
https://pastebin.com/m8ZFwm6q
https://pastebin.com/UeAJbTM5
___Gist/pastebin/hastebin links___

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number: Paper-152 (1.14.4)
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

**Comment by HexedHero** [comment]
Get a better CPU

**Comment by ColaIan** [comment]
that's two E5 2620 server cpus @HexedHero

**Comment by HexedHero** [comment]
> that's two E5 2620 server cpus @HexedHero

My point stands
Minecraft uses a single thread, doesn't matter if you have 100 CPUs, my old CPU is 2x better than ur two CPUs together for MC

**Comment by kickash32** [comment]
More CPU cores don't really help Minecraft, it needs fast single thread performance. Dual CPUs systems in particular are terrible at running Minecraft due to their nature.

**Comment by ColaIan** [comment]
no, seriously, the tps is constantly 20 when I'm using pure spigot instead of paper

**Comment by kickash32** [comment]
Then you should provide a spigot timings report for comparison.

**Comment by ColaIan** [comment]
okay one sec, I need to build from buildtools

**Comment by HexedHero** [comment]
https://serverjars.com/

**Comment by ColaIan** [comment]
it's against EULA and technically not legal

**Comment by HexedHero** [comment]
faster than building

Edit: Against EULA? Nothing to do with EULA but okay.

**Comment by ColaIan** [comment]
not minecraft's EULA, but read this https://www.spigotmc.org/wiki/unofficial-explanation-about-the-dmca/

**Comment by kickash32** [comment]
Can you please try these startup flags exactly as they are https://mcflags.emc.gs/ (you can change XMS XMX to 16G if you want)

**Comment by HexedHero** [comment]
More power to the guy that DMCA'd I guess *shrug*

**Comment by ColaIan** [comment]
those flags only messes up with garbage collectors to optimize memory usage, not related to performance

**Comment by Spottedleaf** [comment]
no that's not even close to what the flags are doing

your timings report shows that your GC is actually hitting you VERY hard

**Comment by kickash32** [comment]
This thread has gone on long enough, general lag issues should be discussed on the paper discord at https://discord.gg/papermc (use #paper-help).

**Comment by ColaIan** [comment]
it isn't general lag, let me get up with the pure spigot and paste the timings

**Comment by ColaIan** [comment]
https://timings.spigotmc.org/?url=ecavotenof there we go

**Comment by electronicboy** [comment]
the GC metrics of your server makes those timings highly suspicious, you are blowing a lot of CPU time away on handling garbage collection, the report also indicates that the CPU is not exactly a fast one, but outside of GC issues and trying to combat them, the only real next step is to grab a sampler and take a deeper dive into what the server is actually doing

Issue is delving into these issues often requires much more conversation can be done on github without flooding peoples inboxes needlessly, I would suggest joining the discord for support
