### ISSUE TITLE
Velocity [WARN]

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#241]
http://pastebin.com/sz9kYpjw - build 704, still in force error.

**Comment by Puremin0rez** [comment]
`23.04 17:20:28 [Server] WARN at no.HON95.DynPad.DPListener.onPlayerMove(DPListener.java:51)`

That plugin is your problem. It's setting a really high velocity on a player, which has been known to cause server deadlocks.

**Comment by FunnyCraft** [comment]
What can I do to remove the error?

**Comment by Puremin0rez** [comment]
Does the plugin allow you to configure the velocity that it applies to the player?

It is setting a velocity of 4.5, whereas the max allowed is 4.0 before a warn occurs.

**Comment by FunnyCraft** [comment]
Thank you, you helped me a lot.
