### ISSUE TITLE
Disable mob spawner nerf for naturally generated spawners

### ISSUE THREAD

**Issue by Xinayder** [PaperMC/Paper#2411]
The current Spigot setting `nerfSpawnerMobs` and the related Paper setting to make these mobs jump, so as to not break mob farms, work for any kind of spawner.

It would be nice if there was a third setting that could disable this nerfed behavior for naturally generated spawners, which wouldn't get rid of the danger aspect of dungeons and mineshafts.

**Comment by CeIebrimbor** [comment]
`nerf-spawner-mobs` is a Spigot setting :thinking:

**Comment by zachbr** [comment]
The server does not track which spawners are naturally generated vs placed by a plugin. This seems out of scope for the server-core.

**Comment by Machine-Maker** [comment]
I was thinking of adding new API to spawners for setting their nerf'd status. If that happens, this can be a thing.

**Comment by Igzak** [comment]
Any updates? Really good feature

**Comment by Owen1212055** [comment]
In general, there is no great way to distinguish blocks placed by plugins vs natural generation. It is very much possible to use the API to mark custom-placed spawners with a special tag that can be used in joint with https://github.com/PaperMC/Paper/pull/4863#issuecomment-1870658198
