### ISSUE TITLE
Little or no cooldown on ender pearl usage

### ISSUE THREAD

**Issue by GoldenDelicios** [PaperMC/Paper#2412]
### What behaviour is expected:
Ender pearls have a cooldown of 20 ticks after a player throws one.

### What behaviour is observed:
Ender pearls can be thrown very quickly. It does appear that there is some cooldown, but it is greatly diminished. The cooldown effect in the inventory still appears as normal client-side.

### Steps/models to reproduce:
Give yourself a stack of ender pearls and hold or spam right click while wielding them.

### Plugin list:
No plugins

### Paper build number:
Paper 152 and 156 (Minecraft 1.14.4)

### Anything else:
This issue does not seem to affect the cooldowns inflicted by eating chorus fruit or blocking an axe attack with a shield.

**Comment by Spottedleaf** [comment]
produced locally, confirmed
