### ISSUE TITLE
grass dont growth

### ISSUE THREAD

**Issue by seema84** [PaperMC/Paper#2414]
### What behaviour is expected:
grass should grow back

### What behaviour is observed:
grass dont growth in spawnarea after sheep eat it
after some time it looks like this ->

example
https://i.imgur.com/USRCm1u.png

### Steps/models to reproduce:
- create a server
- set a spawnpoint
- wait a while (without a player near this chunks)

### Plugin list:
no plugins

### Paper build number:
Paper #152 (1.14.4) also #641 (1.13.2) 

### Anything else:
-

**Comment by MiniDigger** [comment]
does it work for you outside of the spawn area?

**Comment by HexedHero** [comment]
If it works outside the spawn area then I think its just the spawn protection not allowing to change it.

**Comment by kickash32** [comment]
I don't think that's how spawn protection works, and if it is, its still a bug

**Comment by danny6167** [comment]
Is there perhaps a bug here where spawn protection is blocking more than it should? It also seems to block interact with essentials warp signs in the spawn protection are. So you cant use them to warp.

**Comment by seema84** [comment]
> 
> 
> does it work for you outside of the spawn area?

I've only seen it in the spawnarea.

**Comment by Spottedleaf** [comment]
1.14 wont tick areas that aren't near to players (~16k chunk radius distance required)

**Comment by kickash32** [comment]
That explanation only half makes sense, if its not ticking, then how is the grass being removed? (sheep can't eat if they don't get ticked right?)

**Comment by Spottedleaf** [comment]
uhh you sure they're eating while the players are away?

**Comment by seema84** [comment]
> uhh you sure they're eating while the players are away?

yes

**Comment by MrSpock78** [comment]
I have the same problem but since 1.13.2.
Somehow they are eating grass in loaded chunks but it does not grow like in 1.12.2
![2019-06-23_12 59 55](https://user-images.githubusercontent.com/28217121/63214519-553e4c00-c119-11e9-81c3-f50edd7d81ff.png)

**Comment by aeonlamb** [comment]
I believe the issue is that, while the server will keep the spawn chunks loaded, the spawn chunks are not affected by random ticks, unless there is a player within an 8-chunk radius (iirc). Grass growing is caused by random ticks, so if no random ticks can occur in the spawn chunks then grass won't regrow. However, the chunks are still loaded, and many of them are still "entity-processing", so the sheep can still eat grass. I believe this is the same behavior as in vanilla. You can probably use a plugin like worldguard to prevent this with some region flags, personally I just prevent all mob spawning in the spawn on my server.

**Comment by MrSpock78** [comment]
It feels like entity-activation-range is kinda broken since 1.13.x.
In my case it is not the spawn region. I am usually 8-10 chunks away from that shown region.
The pattern shows that the sheep was very active with an animal activation range of 20.

**Comment by MrSpock78** [comment]
Comparing an area 256x256 filled with 50%dirt 50%grass_blocks in 1.12.2 to 1.14.4
In one corner I filled the area with grass_blocks only and placed sheeps from the middle to the top and from the middle to the top right.
![2019-08-18_17 58 55](https://user-images.githubusercontent.com/28217121/63227045-833b9300-c1e2-11e9-989a-836a594e3ef3.png)
On the next picture you can see that they are eating grass in areas where it does not regenerate:
![2019-08-18_17 59 11](https://user-images.githubusercontent.com/28217121/63227061-aebe7d80-c1e2-11e9-988d-4d2fe676473a.png)
In 1.12.2 that did not happen:
![2019-08-18_18 06 04](https://user-images.githubusercontent.com/28217121/63227072-eb8a7480-c1e2-11e9-821c-22fbfe31ec84.png)

**Comment by MrSpock78** [comment]
3h later:
![2019-08-18_21 27 54](https://user-images.githubusercontent.com/28217121/63229287-39ad7100-c1ff-11e9-9f6d-cc4b10e06e58.png)

**Comment by kickash32** [comment]
@MrSpock78 I'm not sure but your issue seems separate from this? This is about grass turning to dirt at an unloaded spawn. Not sure if in your setup the chunks are loaded or not and if spawn point is near or not...

**Comment by MrSpock78** [comment]
I think it is the same issue. Somehow sheeps are eating grass where they didn´t do it before. The grass growing/ticking area did not change between 1.12-1.14. It is a round radius of ~128 blocks. But the sheeps seems still ticking and eating grass in all loaded chunks, so over time there you´ll get areas full of dirt on the outside of this ~128 block radius.
Edit:
view-distance: 10
entity-activation-range:
    animals: 20
Spawn is not near but I have a small sheep farm next to my spawn with same effect since 1.13.x

**Comment by Spottedleaf** [comment]
after further investigation, chunks do not tick if they're not loaded by players, even if they're at ticket level 31 or lower

**Comment by limwa** [comment]
Okay, maybe I am a little bit late to the party, but this is WAI, I think. The spawnchunks is a 19x19(I think) chunk grid of entity processing chunks. This means that, even if a player is outside the area, the entities inside will still be ticking. Random ticks, however, only occur in a certain radius around the player. So, while normal game ticks are responsible for making the sheep eat the grass, random ticks are responsible for making the grass grow back. Therefore, if there is no player around the spawnchunks, the grass will not grow.

**Comment by kickash32** [comment]
So this may be intended by Mojang and their amazing wisdom. If OP could submit a bug report on mojira and get a confirmation on the intentions of Mojang, we could move forward with this.

**Comment by MrSpock78** [comment]
Isn´t it vanilla that all entities are ticking in loaded chunks?
The entity-activation-range should slow down ticking entities if no player is near. But that must have been changed somehow with 1.13.x.

**Comment by seema84** [comment]
paper 1.15.1 is also affected

**Comment by seema84** [comment]
why was it closed? its fixed?

**Comment by kickash32** [comment]
Won't fix due to it being intentional.

**Comment by seema84** [comment]
https://bugs.mojang.com/browse/MC-169772

**Comment by seema84** [comment]
perhaps you can help with the explanation in this bug report

**Comment by limwa** [comment]
It's intentional because grass only grows if it's within 128 blocks (I think, not sure) of a player. Therefore, if no player is around, grass won't grow.

EDIT: See Block Tick in https://minecraft.gamepedia.com/Tick

**Comment by seema84** [comment]
> Won't fix due to it being intentional.

intentional from paper? this issue don't exist in vanilla
i can only reproduce it in spigot/paper

**Comment by seema84** [comment]
the problem still exists (build 393 - 1.16.4). in vanilla i can't reproduce it.
maybe you can reopen the issue or i need a new one?

**Comment by Chew** [comment]
Please make a new issue. Make sure you follow the template entirely and are on the LATEST version.

**Comment by Chew** [comment]
Actually, since it was closed for being intentional, no need to open a new one.

**Comment by electronicboy** [comment]
vanilla only ticks chunks when they're within a specific range of the player, mobs tick, if they're in chunks marked to tick, which means that you're gonna have mobs doing stuff like eating the grass in chunks which won't have grass growing as they're not ticking.
The only "fix" for this on our side would be to make chunks always tick, no matter how far they are from players, or, prevent entities from ticking at all when they're not in range of a player, both options which will only upset a huge chunk of people.

**Comment by seema84** [comment]
> 
> 
> vanilla only ticks chunks when they're within a specific range of the player, mobs tick, if they're in chunks marked to tick, which means that you're gonna have mobs doing stuff like eating the grass in chunks which won't have grass growing as they're not ticking.
> The only "fix" for this on our side would be to make chunks always tick, no matter how far they are from players, or, prevent entities from ticking at all when they're not in range of a player, both options which will only upset a huge chunk of people.

I can understand that very well. However, it is also very annoying when the whole world looks very disheveled in Survival. At each player regions arise where no more grass is. My bug report at Mojang was closed. Maybe you can achieve more there?

**Comment by electronicboy** [comment]
You need to create a bug report from vanilla, go spawn a few dozen sheep at spawn and leave them to do what they do, they should I'd imagine cause the exact same effect. Mojang doesn't care about bug reports from software that isn't there's unless you can demonstratively prove without a doubt that it's a vanilla issue, which, is best done with vanilla.

**Comment by seema84** [comment]
Maybe you can help to explain the issue a bit more in the bug report.

https://bugs.mojang.com/browse/MC-210802

**Comment by seema84** [comment]
I must say that it looks less bad in vanilla with 50 sheeps than in Paper with two.

**Comment by seema84** [comment]
![2021-01-05_23 43 47](https://user-images.githubusercontent.com/2832339/103925976-9a04c180-5118-11eb-82c9-dbf3c20c41ec.png)

thats in paper

**Comment by seema84** [comment]
![567](https://user-images.githubusercontent.com/2832339/103926676-8574f900-5119-11eb-84ca-a8cff534c234.png)

**Comment by limwa** [comment]
@seema84, this issue is closed due to it being intentional. Since you have already opened a bug report on the Minecraft JIRA, you should wait for their response.
