### ISSUE TITLE
World save,unload and drop problem, AntiXray

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#2419]
### What behaviour is expected:
fix

### What behaviour is observed:
world save same problem
https://timings.aikar.co/?id=7437b8de62584de998764f31cb9d5b96

### Steps/models to reproduce:
timings: https://timings.aikar.co/?id=7437b8de62584de998764f31cb9d5b96

### Plugin list:
in timings : https://timings.aikar.co/?id=7437b8de62584de998764f31cb9d5b96

### Paper build number:
#158 1.14.4

### Anything else:
we need world save fix and this a debug : http://prntscr.com/op0s06

Maybe AntiXray problem.

**Comment by CeIebrimbor** [comment]
World save is only taking 10% of your timings. This is not absurd considering its task. If you don't like red numbers, stop looking a Lag View.

Compare this to your mob stacker plugin taking more than 8% of your tick. Aren't those plugins supposed to reduce lag? 🤔

**Comment by Spottedleaf** [comment]
timings shows that the disk io is taking up 17ms per run so your disk is hitting you hard

meanwhile plugins are at the top of the timings list during the big spike at the end

**Comment by successed** [comment]
> timings shows that the disk io is taking up 17ms per run so your disk is hitting you hard
> 
> meanwhile plugins are at the top of the timings list during the big spike at the end

How can see this ? İ need see

**Comment by successed** [comment]
> timings shows that the disk io is taking up 17ms per run so your disk is hitting you hard
> 
> meanwhile plugins are at the top of the timings list during the big spike at the end

Check this out, İ have new server i9900k cpu Nwme disc ddr4 8gb ram 
Timings : https://timings.aikar.co/?id=ae482343c6ed4c12994192b3f51f8dcb
