### ISSUE TITLE
Teleport via End portal puts player in wrong location

### ISSUE THREAD

**Issue by WonderDave** [PaperMC/Paper#242]
This is the same issue as Paper Bug Report #120 .  The problem seems to have been fixed for Nether portals, but it definitely still exists for End portals, in both directions.  It causes players to be teleported to the new dimension, but at the coordinates from the originating dimension.  For me, this doesn't happen all the time, but it happens most of the time.

This affects all versions of Paper.  The bug also exists with Spigot (#1903) with both Nether and End portals.

**Comment by WonderDave** [comment]
Video of Problem:  [https://vimeo.com/164040040](https://vimeo.com/164040040)

I've made a video that illustrates the problem that I'm experiencing.  I removed most plugins.  The video shows the plugins in use and the Paper version.  The "Practice" plugin has a PlayerTeleportEvent method in which I display in the chat window the From/To world and X/Z coordinates every time the PTE fires.

In the video I first go from the Overworld through a Nether portal to the Nether, and then back through the portal.  You can see that the PTE fires only one time for each trip through the portal and takes me to the correct location.  Then I go from the Overworld through an End portal, and from the displayed coordinates you can see that the PTE fires twice, and I am ultimately teleported into The_End, but to the same coordinates where I was in the Overworld.  I fall out of the world, die, and respawn back in the Overworld.  Then I go through the End portal again, but this time the PTE fires just once and I am taken to the correct location in The_End.

I made this video several times because in the first few recordings it took about five or six attempts each time before the End portal took me to the correct location.  I finally got "lucky" with this recording and was able to make it shorter.

The same problem also occurs most of the time when I travel from The_End back to the Overworld, but I did not show that in this video.

If there's something that I'm overlooking, or if something that I'm doing or not doing is causing the problem, or if there is additional information that I can provide, please let me know.  Thanks.

**Comment by WonderDave** [comment]
I'm not sure if this is useful info or not, but the problem seems to occur only when the player is in Survival mode.  If a player is in Creative mode, the End teleports occur without any problems.

**Comment by aikar** [comment]
Just updating to say this isn't forgotten, just haven't had the time to debug this myself... Hopefully someone else may be interested in looking into it.

**Comment by zachbr** [comment]
Cannot reproduce this. I am teleported to the expected coordinates irrespective of my current gamemode.

**Comment by WonderDave** [comment]
I just did some more testing and, with only the Multiverse-Core and Multiverse-NetherPortals plugins installed, I am able to reproduce the problem (although, as before, it occurs only some of the time).  But without the Multiverse plugins installed I was unable to reproduce the problem and the teleports worked as expected.

I never experienced this issue with Multiverse when I was using 1.8.9, so something about the interaction between Multiverse and Paper/Spigot must be causing this (sometimes) problem.  Maybe Multiverse needs some minor updates to be fully compatible with 1.9.

**Comment by sgdc3** [comment]
I think that it's multiverse-netherportals fault. No issues without it.

**Comment by aikar** [comment]
i tried reproducing with the logic in multiverse portals and could not

but we are using multiverse core on the test server.

https://gist.github.com/aikar/bbe179403bd8a2c4120e7c2f3f6dd3f8
compare to
https://github.com/Multiverse/Multiverse-NetherPortals/blob/master/src/main/java/com/onarandombox/MultiverseNetherPortals/listeners/MVNPPlayerListener.java#L92

was fine each time

in video you are in worldanarchy, is this your main world and you just updated server.properties?

I am stuck

**Comment by WonderDave** [comment]
@aikar The "worldanarchy" in the video is not my main world.  Even with Multiverse-Core and Multiverse-NetherPortals enabled, if I teleport to/from the End of my main world, all is good.  But if I teleport to/from the End of worldanarchy, the issue occurs (sometimes).  If I enable my test plugin that displays the from/to worlds and coordinates in PlayerTeleportEvent, I can see that the times when the problem occurs are the times when PlayerTeleportEvent is being called twice.  For a split second I'm in the correct location, and then I'm teleported to the wrong location (to the correct world, but to the 'from' coordinates of my originating world).  What's also weird is that simply enabling the test plugin that displays the PTE coordinate info seems to make the problem occur less frequently.  I have no idea why.

I appreciate your efforts to reproduce this issue.  A while back you fixed the teleport issue for Nether portals, and that was the more significant problem that was experienced by many. So, since that's been taken care of, at this point, knowing that setting the gamemode to "creative" eliminates the problem that I'm experiencing with End portals, and since I seem to be the only one having this problem, I'm fine with having this issue closed.

**Comment by sgdc3** [comment]
@WonderDave Not the only one ;)

**Comment by sgdc3** [comment]
And i'm almost sure it's mv-netherportal's fault. Now i'm opening a new server in my network without it (using the vanilla behavior) let's see if it works ;)

**Comment by aikar** [comment]
Ok not your main world changes the scenario. 

when I created world2, world2_the_end, the end portal does not work.

I'm not sure what handles connecting non main worlds to each other, do you have another plugin handling that? I have multiverse on test and it did not handle linking the 2 (unless a reboot is required?)

I think that may be the source of the issue.

**Comment by WonderDave** [comment]
I use Multiverse-Core to handle access to all of my worlds, and Multiverse-NetherPortals to manage the portals between them.  With _only_ those two plugins enabled, the problem does occur (and the PTE is called twice and the coordinates get mixed up).

Since (for me) the problem occurs sometimes, but not always, could it be a timing issue?

**Comment by aikar** [comment]
I suspect the issue relies around Multiverse-Portals then.

NEtherPortals logic I cant see fault in.

**Comment by WonderDave** [comment]
Just to clarify, I use Multiverse-NetherPortals (build 704).  I've never used Multiverse-Portals.

**Comment by zachbr** [comment]
Closing, inactivity/third-party. If we can trace this back to Paper, fine sure let's keep talking, but as it is it appears to be an issue elsewhere.

**Comment by zachbr** [comment]
@WonderDave are you seeing this or anything like it on the latest 1.10 builds? Curious as we're starting to hear sporadic comments similar to this issue.

**Comment by WonderDave** [comment]
@Zbob750 I am no longer experiencing the problem with End portals sometimes teleporting players to wrong coordinates.  My "fix" has been to put each player in Creative mode at the start of a teleport, and then put the player back into Survival mode after the teleport.  I just tried removing that fix, and even without it I cannot get the problem to reoccur.  Every trip through an End portal gets me to the correct place, although I can't think of anything that I've done that might have resolved the issue.  I'm still using Multiverse-Core and Multiverse-NetherPortals.  Of course, I don't want the problem to come back, but I'll test some more and will leave another comment if I can get the problem (or anything similar) to reoccur.
