### ISSUE TITLE
Server Crash: Exception in server tick loop

### ISSUE THREAD

**Issue by DmitryRendov** [PaperMC/Paper#2422]
### Link/paste of stack trace
https://pastebin.com/EsS2k4kM

### Plugin list:
Plugins (41): AntiAFKPlus, AntiWorldDownloader, AutoMessage, BlockPluginz*, BungeeTabListPlus*, ChatGuard, ChestShop, ChunkSpawnerLimiter, ClearLag, DiscordSRV, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, FishinRoulette, GraviTree, GriefPrevention, GriefPreventionFlags, HolographicDisplays, IllegalStack, JDynmapGriefPrevention, Jobs, LagMonitor, LimitPillagers, LogBlock, LuckPerms, Multiverse-Core, Multiverse-Portals, NoSpawnerChange, PhantomAdmin, PlaceholderAPI*, PlayTime*, PlugMan, ProtocolLib, TitleManager*, TogglePvp, Vault, VillagerOptimiser, WorldBorder, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Randomly doesnt matter how long the server is up. Previosly I faced this issue being on spigot but with a bit different error trace - https://pastebin.com/S0p2JKDB It seems paper has nothing to do with this crash. Anyway, it'd be great if you have a look and return back to me with some advice or postmortem.

### Paper build number:
[07:26:13 INFO]: This server is running Paper version git-Paper-158 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[07:26:13 INFO]: Checking version, please wait...
[07:26:13 INFO]: You are 2 version(s) behind

**Comment by breadbyte** [comment]
Update. This has been fixed on build 159.
