### ISSUE TITLE
Enchants are being capped at Level 10!

### ISSUE THREAD

**Issue by BoyJamal** [PaperMC/Paper#2423]
### What behaviour is expected:
Enchants are being capped at level 10 even though I turned off unsafe enchants in Essentials. Should allow me to go to the max unsafe level.

### What behaviour is observed:
Cant enchant anything higher than level 10

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
https://ibb.co/59L9f1P

### Paper build number:
1.8.8 or Paper version 4c7641d

### Anything else:
Is there anyway I can check all plugin activity to see the reason why its happening?

**Comment by zachbr** [comment]
1.8.8 is not supported
