### ISSUE TITLE
§k color code strange glitch also on surrounding text

### ISSUE THREAD

**Issue by LoneDev6** [PaperMC/Paper#2424]
### What behaviour is expected:
Not glitched surrounding text

### What behaviour is observed:
It's really strange, if I set this nickname with plugin EssentialsX (I think it will work even with other plugins) and then I write on chat or I press tab, the surrounding text gets glitched in a strange way, which is a bit slower and different from the normal §k color code behaviour.
This glitch disappears after some time. I noticed this happens on server start and disappears after some minutes.

### Steps/models to reproduce:
- Enable these settings in EssentialsX (to be able to see nickname in tab list):
change-displayname, change-playerlist, 
- Use this EssentialsX command: /nick &0&k�&fLoneDev&0&k�&f
- Write on chat and see the previous text (prefix and "LoneDev") glitch in a strange way
- If you don't see any glitch restart the server and when you join you should see the glitched text.

### Plugin list:
EssentialsX

### Paper build number:
git-Paper-159 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Anything else:
![glitch](https://media.giphy.com/media/lOlL1fchuk5o8WxYh0/giphy.gif)
![glitch](https://media.giphy.com/media/Vi5SAs2vZAe8f8Dl2v/giphy.gif)

**Comment by mikroskeem** [comment]
Client side bug, nothing to do about it here.

Or rather a feature?

**Comment by LoneDev6** [comment]
It's strange this happens only when the server is fresh started, I'm curious if there's a way to trigger this, I like the effect

Edit: this seems to happen only when you restart your Minecraft client.. sad it's a clientside bug..
