### ISSUE TITLE
PlayTime statistics frozen

### ISSUE THREAD

**Issue by RussianHacker69** [PaperMC/Paper#2426]
### What behaviour is expected:
The playtime of a player should increase...

### What behaviour is observed:
The playtime is frozen 

### Steps/models to reproduce:
Using a plugin like SpigotBoard to display the time played in the scoreboard or using a plugin like PlayTime / OnTime, tried both and the playtime is really frozen

### Plugin list:
https://gyazo.com/c495c3d3fbd83d7a98607f7cea9156f0

### Paper build number:
git-Paper-162 (MC 1.14.4)

### Anything else:
Tried with a couple of plugins which displays the playtime but no response, the problem occurs when i updated the paper at the latest build. ( I was like 4-5 builds behind)

**Comment by ghost** [comment]
That is a lot of plugins... Your server may be processing too much

**Comment by RussianHacker69** [comment]
I saw servers with 100+ plugins, so that's not the point... if you're interested i can leave a timings report.
Edit: I saw that i have stats:   disable-saving: true in spigot.yml and that was the problem, i'll close this.

**Comment by ghost** [comment]
Oh ok
