### ISSUE TITLE
Something weird about entities is happening, timings v2 bug?

### ISSUE THREAD

**Issue by mareksipos93** [PaperMC/Paper#2427]
Hi!

My CPU usage is rising more than it should. When there are about 25+ players online, server starts losing TPS.

So I wanted to use timings v2 to find the issue. The problem is that the issue seems to be always different entity.

I guess that there is something going on there... something resource intensive and timings v2 cannot profile it and assigns used resources to random entity - so it's impossible to find real cause of performance problems.

Please see these timings and use time slider from left to right width the width of 2 time points. So for example from 0 to 2, then from 2 to 4, then from 4 to 6 etc...

https://timings.aikar.co/?id=e28caf203f864d2d8d349fab28573fa5

When you are viewing different parts of these timings, select LAG button and check the cause of main lags. It's always different entity.

Interval 0-2 its MinecartRideable, Interval 2-4 its EntitySkeleton, interval 4-6 its EntityPig, interval 6-8 - well okay this time its Disk IO but from 8-10 its EntityPlayer and from 10-12 its EntityGuardian. And if you select interval 0-12 its EntityItemFrame.

(I've selected timings with lower player count on purpose so it's more clear to see the behaviour I'm reporting - when there are more players, this happens more frequently and server starts to lose TPS without any reason - the cause seems to be **always different entity**).

Plugins (24): AuthMe, AutoMessager, BanManager*, BetterAlias*, ChestShop, CommandSigns, Essentials, EssentialsChat, EssentialsSpawn, FakaHedaMinequery*, GreenCore, GreenXGen, Holograms*, LimitPillagers, LuckPerms, PluginManager, ProtocolLib*, Residence, SkinsRestorer, Vault, VillagerOptimiser, Votifier, WorldEdit, WorldGuard

server.properties -> https://pastebin.com/dpTYiq2H
bukkit.yml -> https://pastebin.com/6dG4pCC4
spigot.yml -> https://pastebin.com/9pCyq63e
paper.yml -> https://pastebin.com/QMUnATEi

This server is running Paper version git-Paper-162 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
424/29654 ticks indicates that this isn't really a major issue and is more likely to be some form of an anomaly in general; To me, that looks to be GC:

```
{
ParNew: [
5577
73814
]
MarkSweepCompact: [
120
86235
]
}
```

**Comment by mareksipos93** [comment]
As I said, it becomes major issue when more players are online - but the main purpose of this is not performance itself - but rather the fact that it's impossible to find the cause as timings v2 assigns used computational time to random entity.

**Comment by electronicboy** [comment]
Shamefully, there really ain't much of a way around this, timings just times how long a handler takes to run, things such as GCs pausing the JVM or the server in general being overloaded somehow, aren't really all that detectable in a useful manner for timings; 

In this case, with the metrics from the system config > gc tab, I would probably start looking into how your memory is behaving, https://mcflags.emc.gs are a good set of flags, I'd also probably suggest seeking further assistance on Discord/IRC
