### ISSUE TITLE
Asynchronous Async Player Chunk Add errors

### ISSUE THREAD

**Issue by grzegorzekkk** [PaperMC/Paper#243]
### Description of issue:

I have my console spammed by errors like this:
http://pastebin.com/Ha4iwXmM
Dev referenced it to that issue: https://github.com/BanManagement/BanManager/issues/577
and send me here.
Anyway to fix that on side of paper or banmanager?
On pure spigot that error doesn't appear, but I wish to use paper.
### Paper build number: 693
# Crash, Stacktrace
### Link/paste of stack trace

http://pastebin.com/Ha4iwXmM

**Comment by Brokkonaut** [comment]
BanManager has to fix it. On Spigot it will not cause this exception but it can cause chunk corruption or server crashes beacuse of those async modifications. This is defnitely never safe.

Paper just catches those incorrect operations and shows the exception to protect the server stability..
