### ISSUE TITLE
Last tick on unload is not processed properly

### ISSUE THREAD

**Issue by L0laapk3** [PaperMC/Paper#2435]
It seems like the last tick does not properly process events anymore. I discovered this when using portal devices that disable the portal in the same gametick that the player is transported.

### What behaviour is expected:
After the player is transported, the portal is extinguised consistently. ( = vanilla behaviour)

### What behaviour is observed:
After the player is transported, the behaviour is wildly inconsistent: Sometimes the portal gets extinguished (updates happened in same tick), sometimes it will not get extinguished until the first tick after the player is transported back (updates didnt happen in same tick), sometimes, if the player is lucky, the player is even greeted with a nice lava/water shower when he returns. (updates partially happened in the same tick and were interrupted, causing weird stuff)

My theory is that the updates in that tick just stop immediatly instead of finishing the tick properly, causing all kinds of weird behaviour.

The `delay-chunk-unloads-by` option seems to not have any effect on this as the chunks get unloaded instantly.

### Steps/models to reproduce:
1. Download savefile & start paper server.
2. Observe inconsistent behaviour.

### Plugin list:
None

### Paper build number:
163

**Comment by L0laapk3** [comment]
I forgot to attach the savefile, here you go: https://transfer.sh/14npIi/test.rar
Test setup is at -444 165.

**Comment by Spottedleaf** [comment]
In general this comes down to 1.14's chunk system of aggressively unloading chunks and how they handle players

**Comment by L0laapk3** [comment]
Its really a dealbreaker for me that the behaviour differs from vanilla behaviour. :(

**Comment by BillyGalbreath** [comment]
I wonder if this is the same reason pets dont teleport with the owner unless a player is left behind to keep the chunk loaded...

**Comment by Spottedleaf** [comment]
After further investigation I do not see any difference from vanilla.

What's occurred here is that vanilla will add a post-teleport teleport ticket to the teleported area after using the portal, and this will last ~5 seconds. So if you rapidly port you will see that your portal will correctly be destroyed.
If you don't rapidly port you will see it not extinguish.

We follow the behavior, so this is not an issue.

**Comment by L0laapk3** [comment]
How so, "we follow the behavior"? The result in paper is completely different, at least with the default settings.

I have 2 questions:
1. How did you manage to replicate the vanilla behaviour in paper? I'd like our builds on the server to work again. (What settings did you use for this?)
2. It worries me that the current tick is literally interrupted in the middle of the tick upon unloading which results in wildly inconsistent behaviours instead of finishing to the end of the tick. I'm not sure if this is caused by paper or if this is actually the vanilla behaviour? I originally thought vanilla did finish the tick properly but I did not know about the post teleport keeping things loaded for a little while.

**Comment by Spottedleaf** [comment]
1. already told you
2. the only thing which can unload chunks mid tick is plugins

**Comment by Spottedleaf** [comment]
just for clarification a ticket is something which will keep chunks loaded

**Comment by L0laapk3** [comment]
Demonstration as requested per discord:

https://youtu.be/kEgQeGlwt4c (just watch in 2x speed)
Explenation: Of the 5 times I tried, the first and third time i ended up in the original portal that shouldve already been closed. on the other tries it closed in the same tick as I left like expected and ended up at the alternative portal.

In vanilla, the portal will close properly everytime and you always end up at the alternative portal.

On my server it only works ~5% of the time for one portal and another one ~30% of the time, it seems like it heavily depends of how much stuff is in the area, I guess thats just because when theres more stuff to do theres a smaller chance that the redstone gets to finish before the tick gets interrupted.

**Comment by Spottedleaf** [comment]
video unavailable

**Comment by L0laapk3** [comment]
Heres also a vanilla demonstration:

https://youtu.be/d4T7nXsMw90 
(I went trough in creative instantly the first time to prove that the nether portal still favors the redstone portal as long as its open).
As you can see, every single time it consistently shuts down the portal in the same tick as that you go trough it, its 100% consistent, Ive also tested this on a vanilla server a bunch of times and on an actual survival server where the time between usage is much longer and its always been 100% consistent.

**Comment by Spottedleaf** [comment]
Even in vanilla you see the behavior is inconsistent. In fact it's exactly what I said it would be - rapidly porting made the portal close with the first try NOT working. (Note: I was mistaken about the portal ticket time being 5s, it's actually 15s).

As for the comparison to Paper in your video, you will actually notice the only time in your portalling it failed to close was the first portal or the time you were in the overworld for about 15 seconds.
