### ISSUE TITLE
alt-item-despawn-rate Entities

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#2440]
**Is your feature request related to a problem? Please describe.**
Experience orbs are items that stay around pretty long by default and many players are too lazy to pick it up. If the chunk is unloaded, the orbs stay there very long causing unnecessary items on the ground which can cause lag.

**Describe the solution you'd like**
It would be nice if the paper setting `alt-item-despawn-rate` could make them disappear sooner

**Describe alternatives you've considered**
Putting  under the alt-item-despawn-rate setting is not accepted since it's not a material. A waring appears:
`Could not add item EXPERIENCE_ORB to altItemDespawnRateMap: No enum constant org.bukkit.Material.EXPERIENCE_ORB`
A workaround would be to set the main despawn rate lower, and make an exception for every other material I would like to despawn longer. This would be a rather extensive list and would certainly contain entities as well like hoppers

**Additional context**

**Comment by kickash32** [comment]
Experience orbs are not items that you can pickup and store in an inventory so they are not applicable for altItemDespawnRateMap. In terms of reducing lag from many experience orbs, you can already configure merge radius and related settings. If you still want to change the despawn rate of experience orbs, please change your feature request to reflect that.

**Comment by x1p** [comment]
I'm not sure how to refrase the request so orbs will despawn faster than the default despawn rate. But that is basically the question: how can I make despawn orbs that I are ignored before the player leaves the area? 
Perhaps we can agree that no one walks more than 1 chunk to pick up an experience orb unless it is a diamond pickaxe that is floating around on the ground.

Merging orbs is a half solution. Orbs will stick together but won't despawn until the default despawn rate has expired. Shortening the despawn rate is an option but requires to put many many blocks in the alt-item-despawn-rate to ensure valuable items to despawn close to the default.

**Comment by LoneDev6** [comment]
You can achieve this with a plugin that can clean up entities.
You can for example use this one https://github.com/NerdNu/MobLimiter and set this in config:
`  experience_orb:
    chunk_max: 1`


but to me this has no sense since experience orbs doesn't make the server lag.. there are other things that make server lag much
