### ISSUE TITLE
Server Chunk Saving Error

### ISSUE THREAD

**Issue by WhyDoWeWonder** [PaperMC/Paper#2443]
### Link/paste of stack trace
https://www.mediafire.com/file/rbx45x5bfalfg7m/2019-08-10-5.log/file
    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

### Actions to reproduce (if known):
I really don't know
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
paper-163
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

**Comment by Spottedleaf** [comment]
It looks like a plugin may be performing saves async - https://github.com/PaperMC/Paper/pull/2308 would resolve.

**Comment by Chew** [comment]
As Spottedleaf stated, #2308 should solve this issue, however if your issue is not solved, please open a new issue with a new log, preferably uploaded to a site like paste.gg. Have a good day!
