### ISSUE TITLE
Volatile TPS problem

### ISSUE THREAD

**Issue by blek-id** [PaperMC/Paper#2444]
###  Timings or Profile link:
https://timings.aikar.co/?id=350904763e9e4248a18c3cbfca008200

### Description of issue:
TPS is really volatile, I'm having a hard time maintaing a 18+ TPS on my server. I thought that it was AAC's move check that was causing it. I disabled move check and TPS went up, but really unstable. I notice that sometimes there's a high amount of % used by a certain entityTick, like nms.EntityParrot for example on the timings I've given above.

I am looking forward to upgrade my machine with OVH's https://www.ovh.com/world/dedicated-servers/game/1901mc01.xml but the machine isn't available yet on my region. So I'm currently on a waiting list for the machine.

### Plugin list:
Plugins (74): AAC, AACPlus, Admin360-Reloaded*, AntiAutoFishing, AntiBotDeluxe*, ArtMap, AuctionHouse, AuthMe, Bank, BlockParticles, BlockRegen, BossShopPro, ChatControl, ChestCleaner, Citizens, CitizensIntergration*, CMI, ConditionalCommands*, Core, CoreProtect, CrateReloaded, DeathMessagesPrime, Denizen, dilarangancurinblock, Duels, EggCatcher, Elevator, EntityDetection, ezAuctions, eZProtector, GCore, GlowAPI*, HeadDatabase*, HealthScale, IllegalStack, Jetpack, KeepChunks, LagAssist, LibsDisguises, LightAPI*, LuckPerms, LWC, MCCore*, MiniaturePets*, MMOItems, Multiverse-Core*, Multiverse-NetherPortals*, MythicMobs, PacketListenerApi*, Parties, PerWorldInventory, PinataParty*, PlaceholderAPI, ProtocolLib*, QuestCreator, Residence, SafeTrade, ShopChest, Shopkeepers, SkinsRestorer, StaffPlus, Stargate*, TransportPipes, Tridentrepair, UltimateDrugs, Vault*, ViaVersion*, VIPJoinSlots*, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml: https://pastebin.com/ctRVRqAN
spigot.yml: https://pastebin.com/ctR8fyDJ
paper.yml: https://pastebin.com/Bhvxfxft
server.properties: https://pastebin.com/C1LFcxGK

### Other helpful links
I've contacted the host for support and these are the transcript that I have between the support
https://pastebin.com/JfBHTXvj

### Paper build number:
641

**Comment by successed** [comment]
Do you need performance ? 

Set bukkit.yml

spawn-limits:
  monsters: 20
  animals: 5
  water-animals: 2
  ambient: 8

**Comment by blek-id** [comment]
I do, but I just find it weird that sometimes the TPS would just be fine for hours on end, but then suddenly it's back to <10 TPS

**Comment by blek-id** [comment]
https://timings.aikar.co/?id=8d5631ff586d4ee98b0b7d1411a17abb
Packet processing seemed to be so high

**Comment by successed** [comment]
> https://timings.aikar.co/?id=8d5631ff586d4ee98b0b7d1411a17abb
> Packet processing seemed to be so high

Because you have more entities, Set bukkit.yml and retry timings paste. 
Normal entites 1000-2500.

**Comment by blek-id** [comment]
I'll retry it right now

**Comment by blek-id** [comment]
https://timings.aikar.co/?id=3030aee5fa99478f8ab08366f5489ae6

Here it is right now

**Comment by blek-id** [comment]
https://timings.aikar.co/?id=7a29674ac9aa457cae6c25e314673704
and now there's a weird TPS spike

**Comment by successed** [comment]
> https://timings.aikar.co/?id=7a29674ac9aa457cae6c25e314673704
> and now there's a weird TPS spike

Normal entity is fixed and now you need use this plugin : https://www.spigotmc.org/resources/insights-limit-blocks-auto-scan-block-entity-counts-live-actionbar-scan-api-1-8-1-14-4.56489/
And set tile entity chunk limit, maybe 30- 50 (Painting - 5)

Next: 
EntityDetection plugin use and check tile entity list, remove more tile chunk limit.

Next: Fine.. İ need last timings paste.

You need last paper version.

**Comment by blek-id** [comment]
Insight is installed,
Paper latest version is installed,
Limited tile entity to 50 (painting 25, hopper 25)

I can't remove chunk that already has more tile entity :( the players just wouldn't be fine with that.
Will post timings soon

**Comment by blek-id** [comment]
I've updated my machine to a dedicated server, and this is how it is now
https://timings.aikar.co/?id=57ae4a2e9c154cbbb88c89d3072161c0
There's still some significant TPS loss, what do you think?

**Comment by Chew** [comment]
Hello! I hope you and your server are doing well. Unfortunately the links you mentioned have expired and as such this issue needs to be closed. Also, a year of improvements has occurred, but if you still happen to be experiencing issues do not hesitate to ask us on our [Discord server](https://discord.gg/papermc) in #paper-help, we'd love to help! Have a good day and thanks for the report.
