### ISSUE TITLE
Server crash while executing "old" command block

### ISSUE THREAD

**Issue by Androkai** [PaperMC/Paper#2446]
### Link/paste of stack trace
* information: https://gist.github.com/Androkai/babfff00363ed5600d2ce82e59360503/edit
* schematic file: [schematics.zip](https://github.com/PaperMC/Paper/files/3490037/schematics.zip)

### Plugin list:
AntiXRay (1.9.0)
AreaShop (2.6.0#292)
CoreProtect (2.17.5)
Craftconomy3 (3.5.1-SNAPSHOT)
DeathMessagesPrime (1.14.10)
Essentials (2.17.1.11)
EssentialsGeoIP (2.17.1.11)
EssentialsSpawn (2.17.1.11)
HolographicDisplays (2.3.3-SNAPSHOT)
Lift (60)
LightAPI (3.3.1)
LuckPerms (4.4.1)
Multiverse-Core (4.1.0-SNAPSHOT-b773)
Multiverse-NetherPortals (4.1.0-SNAPSHOT-b761)
NBTEditor (3.2-SNAPSHOT)
NoCheatPlus (1.3-beta.9-CustomFork)
OpenInv (4.0.6)
PlaceholderAPI (2.10.3)
PlugMan (2.1.6)
PremiumVanish (2.4.9)
ProtocolLib (4.5.0-SNAPSHOT)
ShinyItems (1.7.1)
TimeVote (1.42)
UndineMailer (1.9.2)
Vault (1.7.2-b107)
WeatherVote (1.42)
WorldBorder (1.9.10 (beta))
WorldEdit (7.0.1-SNAPSHOT;4610-17cfdee)
WorldGuard (7.0.1-SNAPSHOT;1968-e59d61e)

### Actions to reproduce (if known):
I switched from 1.12.2 to 1.14.4 and used WorldEdit to paste a schematic in a new world. The schematic contains a building which has some command blocks with teleportation commands to move the player with relative positions like `/minecraft:teleport @p ~+4 ~+18 ~-4`. Using one of these comand blocks crashed my server. Figuring out whats wrong I noticed that it doesn't matter which command (e.p. `/say Hello world!`) I use, it's always crashing. I also noticed that everything is working fine with new command blocks, placed with creative mode. I couldn't decide about if this is now a "bug" of WorldEdit to not convert the value from the old schematic file correctly or Paper/Spigot to not catch the error resulting from a command block I could generate and which is totally fine as long as you not execute it.

I added a schematic (had to zip it to be able to upload it here directly) with two command blocks: on the left side a new one without any problems and on the right side the "bad" one which kills everything. Because it's possible to reproduce it this way the difference between the two command blocks must be stored in the schematic file but I lack of a tool to "unpack" it to a format I can read and evaluate.

### Paper build number:
git-Paper-166 (MC: 1.14.4)

**Comment by electronicboy** [comment]
This is one of those cases of "We could maintain a patch for it, but it doesn't fix the fact that your block is broken", your command blocks need to be updated for 1.14

**Comment by Androkai** [comment]
> This is one of those cases of "We could maintain a patch for it, but it doesn't fix the fact that your block is broken", your command blocks need to be updated for 1.14

Alright. After figuring out what's wrong it's no longer a big problem for me. I will just update all my schematics and that's it.
