### ISSUE TITLE
Items/Entities are disappearing when dropped or broken

### ISSUE THREAD

**Issue by timothykra** [PaperMC/Paper#2449]
### What behaviour is expected:
For you to be able to see item on ground 

### What behaviour is observed:
 Item vanishes into thin air

### Steps/models to reproduce:
Drop an item on my server and the item disappears. https://youtu.be/psmA4H9se9w. If you slow it down to 0.25 speed, you can see that the item is dropped but does not end up on the floor.
 
### Plugin list:
ArmorStandEditor.jar
Banknotes.jar
BuycraftX.jar
ChestShop.jar
Citizens.jar
CommandHook.jar
CommandNPC-1.9.1.jar
CoreProtect-2.16.3%20%283%29.jar
Duels-3.2.3.jar
DummyFawe.jar
Dynmap-3.0-beta-3-spigot.jar
EssentialsX-2.17.0.0.jar
EssentialsXSpawn-2.17.0.0.jar
FarmProtect-v1.9.0.jar
FastAsyncWorldEdit-bukkit-1.13.106.jar
GreatKits.jar
GriefPrevention.jar
HealthBar%20%281%29.jar
HolographicDisplays.jar
iDisguise.jar
JEssentials%2BV1.4.0.jar
Jobs4.13.0.jar
LightSource.jar
LootChest-1.9%20%281%29.jar
MarriageMaster%20%281%29.jar
Matrix%20%281%29.jar
Multiverse-Core-2.5.0.jar
Quests-3.7.2.jar
SimpleSit.jar
Staff%2B.jar
SuperVanish%20%281%29.jar
Towny.jar
TownyChat.jar
TownyNameUpdater.jar
tradeshop-2.0.2-2019-05-29T19.46.38.jar
Trading_v3.2.jar
TrollBoss_v6.1.5.jar
UltraPermissions.jar
Vault.jar
VoxelSniper-5.171.0-SNAPSHOT.jar
WatchCat.jar
worldedit-bukkit-6.1.9.jar

### Paper build number:
git-Paper-524 (MC 1.13.2)

### Anything else:
We have had no plugins on the server and glitch was still there.

**Comment by electronicboy** [comment]
You're only 100+ builds out of date

**Comment by timothykra** [comment]
What does that mean? And how do I update it then?

**Comment by electronicboy** [comment]
You need to update the server software by downloading a new copy from here, 
https://papermc.io/downloads and replacing your existing server jar, if you're using a shared host you'll need to consult their FAQs if you're not sure

**Comment by timothykra** [comment]
I updated it to git-Paper-641 now and the glitch is still there.

**Comment by electronicboy** [comment]
Can you reproduce this on a fresh server?

**Comment by timothykra** [comment]
As in without plugins?

**Comment by timothykra** [comment]
Yes I have removed all plugins and the glitch was still there

**Comment by electronicboy** [comment]
as in, a brand new server, new world, etc; I'll try and spin up a server soon for this version

**Comment by timothykra** [comment]
no since I use a host and they don't want to try that. I offered to try and never got the chance. I only have 1 server

**Comment by Draycia** [comment]
Are you unable to start a server on your computer?

**Comment by timothykra** [comment]
I do not know how

**Comment by timothykra** [comment]
So?

**Comment by electronicboy** [comment]
Duplicate of #2369

**Comment by timothykra** [comment]
yeah cause no one was responding to my issue so i recreated it

**Comment by electronicboy** [comment]
recreating issues just wastes our time as we have to deal with duplicates, your issue is not one that appears to be easily reproduced

**Comment by ghost** [comment]
No one will respond if you don't provide any further information on how to reproduce the issue. It is marked as cannot reproduce for a reason, you have to figure out how to reproduce it. Making duplicate issues won't get it solved.

**Comment by timothykra** [comment]
what do you mean by reproducing?

**Comment by electronicboy** [comment]
Please use the original ticket
