### ISSUE TITLE
suggestion to add configurable minimum spawn range for mobs, and configurable global limit

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#245]
http://hydra-media.cursecdn.com/minecraft.gamepedia.com/thumb/4/4a/Mob_spawning_ranges.png/800px-Mob_spawning_ranges.png

as seen here and observable in-game mobs can only spawn outside 24 blocks from players. with a setting of mob spawning range of 3, that only leaves mobs possible to spawn in a small area. mobSpawn clearly goes up or down in usage when lowering or increasing mob spawning range without touching ticks per or mob limits. with a configurable minimum range, could potentially fix mob amount issues with current low settings needed on servers with high players. currently setting the range to 1 or 2, even with 1 tick per spawns, and very high limit on monsters, barely spawns anything at night, but mobSpawn still shows a lot of usage

another issue is the obvious global cap in play, where using for example worldedit to test with, a player can hoard all possible spawns to themselves while another play will get absolutely no monster spawns around them during night, and when removing all mobs with worldedit, mobs will spawn around both players again. suggestion is to add an option to enable a cap per player(s) in chunks, so 70 monsters in bukkit.yml would actually only spawn 70 monsters in those chunks around the player(s) and not more, and at the same time not refuse to spawn more monsters around others players that are located somewhere else entirely.

some wild suggestions but paper has so much configurable and helped me so much, so maybe this could be an option too

**Comment by josephworks** [comment]
that has been added in the latest builds.

**Comment by ghost** [comment]
now that the global cap issue is fixed in paper, could the configurable minimum spawn range part be added? letting mobs spawn as close as 12 - 16 blocks away from the player will fix mob issues even further.

**Comment by diegogarciarojo** [comment]
> that has been added in the latest builds.

where is the config?
