### ISSUE TITLE
Outdated paper

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#2451]
**Is your feature request related to a problem? Please describe.**
Yes, when using hosting server.pro and updating the Paper it still says outdated version. 

**Describe the solution you'd like**
Ignore the number of e.g paper-152.jar (latest on server.pro) and only search in files whats updated and do not send to console if is not updated. 

**Describe alternatives you've considered**
As said up. I updated my paper to the latest 167 and still get message outdated version because the jar its named paper-152.jar and cannot change to 167 because this feature is for premium users. 

**Additional context**

**Comment by CrystallDEV** [comment]
Paper doesn't consider the name of the paper jar. Which means that you are basically having an outdated jar and therefor its not an issue paper is able to resolve. You should contact the support of server.pro or buy a premium user

**Comment by Misio12320** [comment]
I have only outdated number, the version is up to date. I downloaded the 167 and renamed to 152 so.

**Comment by electronicboy** [comment]
If you're running build 167, /version will report as 167 as the info is stored *inside* the jar, if it's not reporting itself as 167, you're not running 167
