### ISSUE TITLE
Entity Duplication Bug causing excessive lag and server crashes

### ISSUE THREAD

**Issue by Stixil** [PaperMC/Paper#2452]
Hello, I am running a Paper server on MC 1.14.4 and am using a shop plugin called UltimateShops that uses entities to display shops. Unfortunately, a bug is causing the entities to duplicated over time causing excessive lag. No errors are logged until the server becomes overloaded and the standard overload message is given. 

[20:56:42] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5009ms or 100 ticks behind

It continues to get worse over time until the server either is restarted manually or crashes entirely. Disabling the entity display fixes this issue. There are no errors logged in the other plugin, and the developer has directed me here. At the time of posting, I am using the newest versions of Paper and UltimateShops Premium. 

https://www.spigotmc.org/resources/ultimateshops-player-admin-item-shops-1-8-1-14-premium.64925/

Thank you very much for the help, I can provide additional info as requested.![03|690x388]

### Steps/models to reproduce:
This happens automatically over time, I suspect is has to do with chunks being unloaded and reloaded, duplicated the entities, as the largest areas of issue are shops located in high-traffic areas.

### Plugin list:
Plugins (29): AntiVPN, BlockLocker, ChestShop, ClearLag, CommandHook, CoreProtect, DiscordSRV, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, Harbor, HungerGames, LaggRemover, Lift, LimitPillagers, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-SignPortals, NoMobGriefing*, PerWorldServer, UltimateAutoRestart*, UltimateShops, Vault, VillagerOptimiser, WorldEdit

### Paper build number:
This server is running Paper version git-Paper-166 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Anything else:

![2019-08-12_17 08 56_2](https://user-images.githubusercontent.com/53889383/62899278-71ab4480-bd25-11e9-97fd-0b8ede69a9bc.png)
![2019-08-12_17 06 08](https://user-images.githubusercontent.com/53889383/62899286-740d9e80-bd25-11e9-8a05-0d654aa381b6.png)

**Comment by electronicboy** [comment]
Are there any entity duplication warnings or? if there is not, there is very little we can do to diagnose issues around premium plugins

**Comment by electronicboy** [comment]
Without any entity duplication warnings, it would suggest that the issue is down to the plugin intentionally spawning them back in but not properly removing ones left in the world; There is very little we can do around premium plugins, we don't have access to them nor the source to begin digging into potential causes

**Comment by Stixil** [comment]
The plugin is available in a free version as well, all apologies for not mentioning that, and the issue is present in it as well. 
https://www.spigotmc.org/resources/ultimateshops-player-admin-item-shops-1-8-1-14-lite.61048/
I'm not sure if this changes anything, but I appreciate the time regardless.
