### ISSUE TITLE
RCON - online players

### ISSUE THREAD

**Issue by sustained** [PaperMC/Paper#2456]
I'm not sure if this should be here or if I should take up the issue with the Spigot devs (or even the vanilla server devs) but basically when communicating with a server via RCON it doesn't return a list of all online players.

A sample of online players is returned only which seems to be a maximum of 12 players (or perhaps it is some percentage of online players).

The sample is cool and fairly useful and allows us to do certain things but not having access to ALL online players makes some things impossible and for my use-case makes the protocol kind of useless.

If a large sample of players (each with a name and uuid) is returned then I see absolutely no reason why all online players can't be returned too.

Seems like a completely arbitrary limitation to me.

Thanks for reading!

----

If this issue should be taken up with the Spigot team or even with the Minecraft devs then just let me know.

**Comment by mikroskeem** [comment]
How to reproduce? Did you try with vanilla? Spigot?

**Comment by MiniDigger** [comment]
Minecraft and spigot will send all players. Paper will do the same, unless you modified the player list via the GS4QueryEvent, which is an event paper added to modify the query responce. 

code for reference: https://hasteb.in/iwaroref.java
see line 225 and 277

**Comment by sustained** [comment]
Thank you for the prompt responses!

@MiniDigger Interesting, a server I play on is running PaperMC 1.14.4 protocol version 498 and I'm pretty sure they aren't doing any of that. It's *mostly* a vanilla server. Any examples of what could be modifying this `GS4QueryEvent` and/or why so I can dig into it some more?

I'm using the **node-gamedig** library. Here's a minimal reproduction:

```bash
mkdir -p /tmp/gamedig-example && \
cd /tmp/gamedig-example && \
wget https://gist.githubusercontent.com/sustained/05943cd6a7751018c56a96ac7df33b67/raw/fc4a634b70e55370a53117890e8ada99506cd6ff/gamedig-example.js && \
npm init --yes && \
npm install gamedig --save && \
MC_SERVER="YOUR PAPERMC SERVER URL HERE" node gamedig-example.js
```

You'll need Node/NPM installed and to edit the environmental variable `MC_SERVER` in the shell code above.

[Link](https://gist.githubusercontent.com/sustained/05943cd6a7751018c56a96ac7df33b67/raw/fc4a634b70e55370a53117890e8ada99506cd6ff/gamedig-example.js) to the JS file that the above shell code downloads and runs.

--------

It could be that this is an issue with the library I'm using but the docs state -

![image](https://user-images.githubusercontent.com/5995080/62945849-716b8180-bdd7-11e9-8287-7072d8a3ca86.png)

And that's exactly what I get - an array of empty objects.

I'll try with some other libraries/languages to ensure that it's not an issue with node-gamedig.

**Comment by sustained** [comment]
Some more information - apparently Waterfall and Bungeecord have decided to implement the Bedrock edition (gamespy3) protocol which means that for this specific library I would need to pass in `minecraftpe` or `minecraftbe` as the game.

https://github.com/SpigotMC/BungeeCord/blob/0dd538f9ff77c20da72c4530b3d21633799bc3a5/query/src/main/java/net/md_5/bungee/query/QueryHandler.java#L103
https://github.com/PaperMC/Waterfall/blob/7dd259045b14e6506bf9f48e63c164334faac445/BungeeCord-Patches/0031-Proxy-query-event.patch#L142

So that got me wondering if perhaps PaperMC is doing the same - no luck there though, I couldn't get it to work.

Still attempting to find other libraries to test with.

**Comment by sustained** [comment]
I've determined that this issue is not at all your problem. Thanks for replying though!

If anyone happens to find this via Google and is curious to know more - you may [consult this issue](https://github.com/sonicsnes/node-gamedig/issues/136) which I opened with **node-gamedig**.

**Comment by sustained** [comment]
[Fixed here](https://github.com/sonicsnes/node-gamedig/issues/136#issuecomment-542515453), again, for anyone who finds this via Google.
