### ISSUE TITLE
Guardian farm rates plummeted.

### ISSUE THREAD

**Issue by willrun4fun** [PaperMC/Paper#2461]
### What behaviour is expected:
A productive XP farm.

### What behaviour is observed:
Since moving from vanilla to Paper recently our guardian farm is getting almost no spawns at all.  This is even with just one person signed on and at the farm.

### Plugin list:
commandsigns, coreprotect, dynmap, essentialsx, luckperms, openinv, serverrestorer, vault

### Paper build number:
163

**Comment by CeIebrimbor** [comment]
Switching to Spigot makes the rates return to vanilla(ish)? Please confirm.

**Comment by willrun4fun** [comment]
I've never ran regular Spigot.   Would you want me to run it as a test?
what is the easiest way to get a build without setting up all the environment to do it?

**Comment by CeIebrimbor** [comment]
We want to determine if it's Spigot before assuming it's Paper. Spigot is notorious for screwing with spawn mechanics.

**Comment by willrun4fun** [comment]
I just got the latest build of Spigot and ran the world with it on a backup.  Same results.

**Comment by CeIebrimbor** [comment]
So not a Paper bug 😃

**Comment by josephrooks** [comment]
That's odd, because I'm on the latest Paper release and just had to lower the mobcap because my server's guardian spawns were through the roof compared to what's expected. May be a broader spawning problem because this has happened with some other mobs in 1.14 for me as well.

**Comment by LoneDev6** [comment]
> 
> 
> That's odd, because I'm on the latest Paper release and just had to lower the mobcap because my server's guardian spawns were through the roof compared to what's expected. May be a broader spawning problem because this has happened with some other mobs in 1.14 for me as well.

yes exactly, same

**Comment by willrun4fun** [comment]
I ended up diagnosing it as they are now swimming up in lava on 1.14.4.  I redesigned the softener with just a drop only.
