### ISSUE TITLE
Bring option to enable protection stacking

### ISSUE THREAD

**Issue by samolego** [PaperMC/Paper#2462]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
It's the feature request from previous version of MC (1.14 - 1.14.2)

**Describe the solution you'd like**
A boolean in paper config to allow protection stacking, aka creating "god armor". For example, being able to put "fire protection" on chestplate already enchanted with "protection".

**Comment by aeonlamb** [comment]
I don't see the point to re-introducing an obvious bug. Also, seems like something a plugin could easily do.

**Comment by zachbr** [comment]
> Also, seems like something a plugin could easily do
