### ISSUE TITLE
No enderdragons paper 1.14.4

### ISSUE THREAD

**Issue by Dinoosawruss** [PaperMC/Paper#2465]
### What behaviour is expected:
Expected to go to the end and see an ender dragon

### What behaviour is observed:
No ender dragon was there, tried to create a new world and was still not there

### Steps/models to reproduce:
1) Create an end world
2) Go to end
3) No ender dragon

### Plugin list:
Plugins (61): ActionHealth*, AreaShop, ArtMap, AuctionHouse, BannerBoard*, BossShopPro, Citizens, ColoredAnvils*, CommandNPC*, CoreProtect, CraftingStore, CrazyCrates, CustomHeads*, DailyRewards*, DeluxeChat, DeluxeMenus, DeluxeTags*, DiscordSRV, EditableSign, EpicRename, Essentials, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, HolographicDisplays, Item2Chat, ItemShops*, Jobs, LibsDisguises, LimitPillagers, LiteBans, LuckPerms, MaxOnline, MineableSpawners, MOTD, Multiverse-Core*, NametagEdit*, Phantom-B-Gone*, PlaceholderAPI*, PlayerParticles, PlayerWarps*, Playtime*, PluginConstructorAPI, PlugMan, ProtocolLib, PyroFishingPro, PyroMining*, Quests, QuickShop, RandomTeleport, Shopkeepers, Skript, SuperbVote, TAB, Vault, VillagerOptimiser, Votifier, Voting*, WorldBorder*, WorldEdit, WorldGuard

### Paper build number:
[07:14:09 INFO]: This server is running Paper version git-Paper-172 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[07:14:09 INFO]: Previous version: git-Paper-166 (MC: 1.14.4)
[07:14:09 INFO]: You are running the latest version

### Anything else:
N/A

**Comment by MrIvanPlays** [comment]
Try reproducing without plugins and on a fresh end world

**Comment by Dinoosawruss** [comment]
Without plugins - Yes
Fresh world - No

**Comment by Dinoosawruss** [comment]
Fixed it by taking the end world from a different server with the same seed
