### ISSUE TITLE
Hopper single item transfer problem

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#2467]
Only 1 item is transferred through the hopper.

Check this video: https://youtu.be/A4i4UjkQcxk

Server version :  Paper-171 (MC: 1.14.4)

Timings and plugin list and all of .yml files : https://timings.aikar.co/?id=8ce18811f16e403b91534da346de48e2

What should be, is that all items come back after transfer.

**Comment by electronicboy** [comment]
spigot.yml `hopper-amount: 1`
beyond that, this is called tick behavior and is 100% down to the order of how the game ticks things in the world
