### ISSUE TITLE
Crafting Lapis/Redstone - Blocks causes Lagspike

### ISSUE THREAD

**Issue by DaLeberkasPepi** [PaperMC/Paper#2470]
###  Timings or Profile link:
https://timings.aikar.co/?id=ac78fd434a26486caff6cc003e8c1aca

### Description of issue:
if you craft one stack of Redstone/Lapis-blocks at once i get a lag spike warning from /spark tickmonitoring

### Plugin list:
see timings

### bukkit.yml, spigot.yml, paper.yml, server.properties
[config files.zip](https://github.com/PaperMC/Paper/files/3513355/config.files.zip)

### Paper build number:
1.14.4 b172

**Comment by Spottedleaf** [comment]
Can you show a spark sampling of this occurring?

**Comment by DaLeberkasPepi** [comment]
I can make one at friday when I get home

**Comment by DaLeberkasPepi** [comment]
thats a spark sample with only the ticks over 100ms (only the ticks where 64 redstone blocks are crafted at once) 
Running with spigot 1.14.4 b175
https://sparkprofiler.github.io/#lbkyTXqBnL

Running with spigot 1.14.4 b176 and with everything sampling
https://sparkprofiler.github.io/#LxaRsZfMAk
