### ISSUE TITLE
kurwy

### ISSUE THREAD

**Issue by h4p1x** [PaperMC/Paper#2471]
jak kurwy jebane zbuildowac 1.8.8 bo ten syf mi builduje gowniane 1.13 szmaty XD

**Comment by inzynierr** [comment]
XDDD

**Comment by h4p1x** [comment]
@PaperMC

**Comment by kickash32** [comment]
Please use the issue template and translate to English.

**Comment by h4p1x** [comment]
how to build 1.8.8????????????1111111oneoneone

**Comment by wajwuz** [comment]
XDDD

**Comment by h4p1x** [comment]
XD

**Comment by h4p1x** [comment]
> Please use the issue template and translate to English.

how to build 1.8.8??????????!!!!!!!!!!!!!!!!!!!oneoneone 1.13 is shit

**Comment by inzynierr** [comment]
please kurwa kys on the sciana

**Comment by HexedHero** [comment]
I've never seen a more cancer thread

**Comment by wajwuz** [comment]
> I've never seen a more cancer thread

so now you see :joy:

**Comment by CaptainAmpersand** [comment]
This seems to be a dumpster fire of an "Issue" thread.
The link you're looking for is https://papermc.io/ci/job/Paper/443/

**Comment by h4p1x** [comment]
@CaptainAmpersand kurwa autyzmie jebany nie chce jarki

**Comment by KennyTV** [comment]
can someone please just snap them out of existence 👀

**Comment by h4p1x** [comment]
@KennyTV Zamknij pizde jebana ksiezniczko z baltahimu pojebana dziewico pierdolona

**Comment by inzynierr** [comment]
next cancer on the github :rofl:
