### ISSUE TITLE
KURWO 

### ISSUE THREAD

**Issue by h4p1x** [PaperMC/Paper#2472]
SZMATO CO BLOKUJESZ MI DZIWKO KURWO MI ODPOWIEDZ SZMATO RUDA CI LEB ROZJEBIE O KRAWEZNIK JAK MI NIE ODPOWIESZ JAK ZBUILDOWAC 1.8.8 BO SIE BULDUJE TYM SYFEM 1.13 KURWO RUDA

**Comment by h4p1x** [comment]
@PapeMC @inzynierr

**Comment by h4p1x** [comment]
@PaperMC

**Comment by inzynierr** [comment]
:-1:

**Comment by electronicboy** [comment]
1) Please refrain from flooding our emails
2) This is an English community
3) We do not care about multi-year old versions of the game, the issue tracker is for reporting issues, not requesting development assistance.
