### ISSUE TITLE
Unicode characters removed from sign on chunk unload/reload

### ISSUE THREAD

**Issue by LoneDev6** [PaperMC/Paper#2474]
### What behaviour is expected:
Keep unicode characters on signs after server restart or chunk unload/load

### What behaviour is observed:
Unicode characters gets removed from signs.

### Steps/models to reproduce:
How to reproduce the issue:

    create a sign and write this text:

    

    restart the server/unload reload chunk
    you'll see characters got cleaned up..

### Plugin list:
none

### Paper build number:
This server is running Paper version git-Paper-173 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by LoneDev6** [comment]
I investigated more and the issue seems to be in chunk unload/load, not in world save or server restart

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/blob/ver/1.14/Spigot-Server-Patches/0330-Strip-private-area-unicode-characters-from-signs.patch
This is intentional behavior

**Comment by LoneDev6** [comment]
How can this be disabled?
Can this be added as a paper.yml setting?

**Comment by Spottedleaf** [comment]
`There is a flag -DPaper.keepInvalidUnicode=true that can be used if you
do not want us to strip these characters from your signs, though I can
think of no reason to use it.`

**Comment by LoneDev6** [comment]
Am I obliged to add this java flag? -DPaper.keepInvalidUnicode=true
My plugin uses these characters in signs and other places, I can't ask all my users to set this flag, would be better to have something configurabile in paper.yml

**Comment by LoneDev6** [comment]
I could add this nbtflag manually "Paper.RemovedPrivateUnicode" on sign creation to bypass check, this may work right?

**Comment by Spottedleaf** [comment]
It's a startup flag for the server itself.

**Comment by LoneDev6** [comment]
> 
> 
> I could add this nbtflag manually "Paper.RemovedPrivateUnicode" on sign creation to bypass check, this may work right?

I bypassed this feature adding this flag to TileEntity using my own plugin.
(Using a custom NBT api)
![immagine](https://user-images.githubusercontent.com/27242001/63267240-e1737f00-c291-11e9-969b-a8d347b25b4a.png)

**Comment by zachbr** [comment]
This is not a supported configuration and subject to change or break in the future. Just FYI.

**Comment by LoneDev6** [comment]
Don't worry I fixed as I've said
