### ISSUE TITLE
Segfault with new async api

### ISSUE THREAD

**Issue by niclimcy** [PaperMC/Paper#2479]
Related commit: https://github.com/PaperMC/Paper/commit/294e30462b65a5031bfb3b7225b66feac039511d

### Link/paste of stack trace
https://pastebin.com/9WtLxZg0

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
- LuckPerms
- World Edit
- World Guard
- Essentials
___A list of your plugins___

### Actions to reproduce (if known):
Happens on server start.
Running on a virtual machine in a docker instance.
SMT enabled VM with 6 cores using NUMA and no cpu time restrictions on docker.
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
Paper-174

**Comment by electronicboy** [comment]
seg fault thrown in native code, I have some level of doubts that async is relevant here outside of maybe pushing memory harder;
i would probably recommend updating your JVM, b212 is outdated, and maybe running a mem-test

**Comment by VADemon** [comment]
CPU and Memory configuration+speed, OS?
