### ISSUE TITLE
Timings not working

### ISSUE THREAD

**Issue by MrIvanPlays** [PaperMC/Paper#2480]
### What behaviour is expected:
Working timings link

### What behaviour is observed:
A timings link that doesn't work. 
The timings link it gave me: https://timings.aikar.co/d=e64cb0d061cd4c4989b79f4a040e99dd
Screenshot: 
![image](https://user-images.githubusercontent.com/37958105/63334048-358a6c00-c343-11e9-866b-9081c8e59dfd.png)

### Steps/models to reproduce:
/timings on ; wait some time ; /timings paste

### Plugin list:
Plugins (18): AntiAd, AuthMe, CraftingStore, LuckPerms, MaxBans*, MOTD, Multiverse-Core, OldCombatMechanics, Report, RetronixSentials, SkinsRestorer, StrikePractice*, SuperbVote, TitleWelcomeMessage, Vault, Votifier, WorldEdit, WorldGuard

### Paper build number:
20.08 12:09:03 [Server] INFO This server is running Paper version git-Paper-173 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
20.08 12:09:03 [Server] INFO Checking version, please wait...
20.08 12:09:03 [Server] INFO Previous version: git-Paper-172 (MC: 1.14.4)
20.08 12:09:03 [Server] INFO You are 1 version(s) behind

### Anything else:
I saw there was a issue created about this (#770) but it was closed because of outdated version

**Comment by electronicboy** [comment]
`?id=` You'll need to fix the URL manually, We can't do much about broken terminals

**Comment by MrIvanPlays** [comment]
Fixed and again, nothing
![image](https://user-images.githubusercontent.com/37958105/63334278-c2352a00-c343-11e9-969a-7efab7693f81.png)

**Comment by electronicboy** [comment]
You're missing the ?

**Comment by MrIvanPlays** [comment]
> You're missing the ?

Oh

**Comment by aikar** [comment]
To be clear, it's your environment breaking the output of the link. either the log reader, or terminal. Something is corrupting the url on your end. nothing to do  with my end.

**Comment by HexedHero** [comment]
Get the URL from your latest.log in your server or in-game, not from the console.
