### ISSUE TITLE
TPS Loss

### ISSUE THREAD

**Issue by MrIvanPlays** [PaperMC/Paper#2481]
Timings report: https://timings.aikar.co/?id=cc6886d32e934e52ad9000f9d8ecfc80

### What behaviour is expected:
No tps losses

### What behaviour is observed:
TPS drops to 15

### Steps/models to reproduce:
Turn on server, join and wait

### Plugin list:
Plugins (18): AntiAd, AuthMe, CraftingStore, LuckPerms, MaxBans*, MOTD, Multiverse-Core, OldCombatMechanics, Report, RetronixSentials, SkinsRestorer, StrikePractice*, SuperbVote, TitleWelcomeMessage, Vault, Votifier, WorldEdit, WorldGuard

### Paper build number:
20.08 13:57:03 [Server] INFO This server is running Paper version git-Paper-174 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
20.08 13:57:03 [Server] INFO Checking version, please wait...
20.08 13:57:04 [Server] INFO You are running the latest version

### Anything else:
RetronixSentials and Report are my own plugins.
From the timings report, i think the tps loss is due to chunk loading or thing like that

**Comment by LoneDev6** [comment]
please give a timings report
use command /timings paste
and send link here

**Comment by ShaneBeee** [comment]
I recommend running your timings for more than 3 minutes. 
The 3 minutes you have there doesn't look all that bad. Just kind of looks like general startup lag with world loading.

**Comment by MrIvanPlays** [comment]
> please give a timings report
> use command /timings paste
> and send link here

I have included one in the original post.

> I recommend running your timings for more than 3 minutes.
> The 3 minutes you have there doesn't look all that bad. Just kind of looks like general startup lag with world loading.

Sure

**Comment by MrIvanPlays** [comment]
Here's a timings link after waiting 15 or more minutes https://timings.aikar.co/?id=f5d6b2b435a4452d99154b42144cffb6
Also before I set in server.properties the view distance to 6, but I am still able to view 16 chunks.

**Comment by ShaneBeee** [comment]
Your timings look perfectly fine.

**Comment by MrIvanPlays** [comment]
Then why there are red things laying there ?

**Comment by HexedHero** [comment]
You're fine

**Comment by electronicboy** [comment]
First timings indicates that block ticking is apparently killing TPS
Second set indicates the same concern near the beginning but that dies off and runs fine; Only real advice here would be to check your random tick gamerule in the lobby world/try to find what is actually being ticked around spawn etc

as for the 2nd timings, 52 ticks out of 15.7k being over the 50ms threshold is not really a concern, TPS loss is pretty much expected to happen on all servers

**Comment by MrIvanPlays** [comment]
randomTickSpeed gamerule was 2000. Now i set it to 1000
https://gyazo.com/380f178c7e573e15f0e192da1a3c0a2c

**Comment by electronicboy** [comment]
vanilla is 3

**Comment by HexedHero** [comment]
WTF? the default is 3

**Comment by MrIvanPlays** [comment]
Wait wut then why it was 2000 ?

**Comment by HexedHero** [comment]
You were literally speeding up the game by 666.666x

**Comment by MrIvanPlays** [comment]
I didn't set that to 2000, I dont know why it was 2000. As you told me the default is 3, I set it to 3

**Comment by kickash32** [comment]
FYI you can always delete a config section or line and it will reset it to default.

**Comment by HexedHero** [comment]
Hes talking about /gamerule, it's embedded into the world
