### ISSUE TITLE
Enchantments in anvils are broken

### ISSUE THREAD

**Issue by pineapplebox** [PaperMC/Paper#2482]
Issue:
Unlike vanilla behaviors, when putting an item into an anvil with an enchanted book, it can obtain any enchantment.
EX: Putting a sword in an anvil with a protection IV book will result in a sword with protection IV. This is not possible in vanilla.

Plugins:
RandomSpawn, OldschoolKill, NoCheatPlus, MYSlots, ChatCo

**Comment by zachbr** [comment]
You did not provide all the information requested in the template

**Comment by Proximyst** [comment]
Cannot reproduce. Fill out a new issue with the template filled if this is still an issue.
