### ISSUE TITLE
Some /gamerule are not working

### ISSUE THREAD

**Issue by Slybianco** [PaperMC/Paper#2490]
### What behaviour is expected:
___Clear Log___

### What behaviour is observed:
___1. Tried on a fresh server, no plugins; Only "/gamerule logAdminCommands false" is still not working;___

___2. Tried on the server with plugins, both commands: "/gamerule logAdminCommands false" & "/gamerule commandBlockOutput false" are not working___

![Cattura2](https://user-images.githubusercontent.com/8469978/63519867-fa7b6a80-c4f3-11e9-9657-2b3b2797daa6.PNG)

![Cattura](https://user-images.githubusercontent.com/8469978/63518643-c69f4580-c4f1-11e9-94af-d889a57e1cf9.PNG)

### Steps/models to reproduce:
___just by using "/gamerule commandBlockOutput false" or "/gamerule logAdminCommands false"___

### Plugin list:
___ArmoredElytra, ArmorStandEditor, Clearlag, Dynmap-3.0-beta-5-spigot, EssentialsX-2.17.0.0, EssentialsXSpawn-2.17.0.0, hsrails, KeepDeathDrop, MineableSpawners, Multiverse-Core-4.0.0, Multiverse-Inventories-3.0.0, Multiverse-NetherPortals-4.0.0, Music, MySkin, PermissionsEx-1.23.4, PlayerParticles_v6.5, PluginConstructorAPI, Shopkeepers-2.7.1, Sickle, Stayput, UnlimitedElytra, VeinMiner-1.14.0, VillagerTradingPlus-1.1.0, worldedit-bukkit-7.0.1-rc1-dist, worldguard-bukkit-7.0.1-beta-01, XpBottles___

### Paper build number:
___paper-175.jar___

**Comment by Slybianco** [comment]
Even changing the silent option in spigot.yml doesn't fix the problem

**Comment by VergilPrime** [comment]
Any progress on this bug? :)

**Comment by mikroskeem** [comment]
Did you compare with vanilla?

**Comment by maicol07** [comment]
This is happening again with 1.16.1

**Comment by Stylite** [comment]
This is happening on 1.16.1.

**Comment by Machine-Maker** [comment]
I am unable to replicate the commandBlockOutput gamerule not working.

**Comment by Proximyst** [comment]
This is an Essentials command which always logs.

**Comment by maicol07** [comment]
This bug isn't solved. The commandBlockOutput rule isn't working

**Comment by electronicboy** [comment]
gamerules are per-world, beyond that, create a new issue
