### ISSUE TITLE
MC-156852 fix reintroduces MC-156013

### ISSUE THREAD

**Issue by animeavi** [PaperMC/Paper#2491]
The [fix](https://github.com/PaperMC/Paper/pull/2396) for [MC-156852](https://bugs.mojang.com/browse/MC-156852) in Paper re-introduces the bug fixed in [MC-156013](https://bugs.mojang.com/browse/MC-156013).

Tested making a dirt tower and breaking it with a diamond shovel with Efficiency IV in my server.

**Comment by kickash32** [comment]
This is a known trade off that was made...

**Comment by animeavi** [comment]
I did imagine it was that kind of situation, just wanted to make sure.
I guess this can be closed if there's no solution.

**Comment by zeanrivera** [comment]
https://github.com/PaperMC/Paper/pull/2544

**Comment by aikar** [comment]
This is resolved in 1.15 now (our patch is no longer there)
