### ISSUE TITLE
async chunk exception

### ISSUE THREAD

**Issue by Spottedleaf** [PaperMC/Paper#2499]
### What behaviour is expected:
no error

### What behaviour is observed:
https://cdn.discordapp.com/attachments/289587909051416579/614714638134673408/unknown.png

### Steps/models to reproduce:
worldborder fill

### Plugin list:
worldborder, ???

### Paper build number:
174

### Anything else:
opened on behalf of CYBER#0396

**Comment by HexedHero** [comment]
oh no. pls fix
