### ISSUE TITLE
Recipes added by plugins not visible to players until they relog

### ISSUE THREAD

**Issue by Frogperson** [PaperMC/Paper#2503]
### What behaviour is expected:
When I add a recipe via Bukkit.addRecipe(), the recipes should be immediately visible to players as they are with datapacks and the vanilla `/reload` command.

### What behaviour is observed:
New recipes aren't visible until the player relogs. By not visible I mean they won't show up in the recipe book, and they don't tab-complete in the `/recipe give` or `/recipe take` commands (however the commands do still work)

### Steps/models to reproduce:
Add a recipe with Bukkit.addRecipe(), give it to the player with either `/recipe give` or Player.discoverRecipe()

### Plugin list:
Just my custom recipe plugin.

### Paper build number:
175

**Comment by Spottedleaf** [comment]
does this occur on spigot/cb?

**Comment by Frogperson** [comment]
Yes, just tested on both CraftBukkit and Spigot

**Comment by BillyGalbreath** [comment]
Pretty sure calling `PlayerList#d(EntityPlayer)` would fix this, as that is what updates and sends all permissions for a client. Quick test of changing worlds would know for sure if that works or not (changing worlds calls this method).

**Comment by Frogperson** [comment]
If going to the nether counts as changing wolds, then that unfortunately didn't change anything. Recipes are still invisible until I relog

**Comment by electronicboy** [comment]
The issue is that bukkit doesn't send these newly defined recipes to the client automatically and pretty much expects that this all occurs at startup so that the information is there ready to be sent to the client

In order to combat this, the server needs to send the list of recipes to the client, given that this is not a pretty operation and that plugins very rarely/should define recipes at runtime, I'd say that the fact that CB doesn't go out of its way to resend the recipe list is something that should be blessed, however; might wanna be backed up with a method to manually resend that to the client

**Comment by Frogperson** [comment]
That makes sense. However, I don't think it's out of the question that some plugins may want to add recipes after the server has already started.  Like if they wanted to have an in-game command/gui to create new recipes, or even just editing config files and then a `/recipeplugin reload` command.

Maybe change this to a feature request for a manual way of resending that data rather than a bug report then? Or should I create a new issue?

**Comment by Machine-Maker** [comment]
Just to add to this, the issue does indeed still exist on 1.16.4 build 311. And calling PlayerList#d(EntityHuman) after adding the recipe did not update it for the player. Still needed to relog.

**Comment by Machine-Maker** [comment]
mmm hmm, yeah, just add the stale after I said it was still an issue.

**Comment by Chew** [comment]
Yes, you did say that... 2 months ago though, the point of Stale is to make sure bugs like this are still reproducible as of the comment.

**Comment by ZandercraftGames** [comment]
Can confirm still reproducible in 1.17.1.

**Comment by Machine-Maker** [comment]
So the linked PR should fix this issue. I also wanted to mention, that adding a recipe and then resending the recipe data to the client is not enough to have the recipe show up in the recipe book. And that is intended. The player must also "discover" the recipe. Methods for that already exist on the HumanEntity interface. Resending the data to the client, either through Bukkit#resendData or using the boolean parameter when adding a recipe in the first place, plus having each player "discover" the recipe will have the recipe show in their recipe book without a relog.
