### ISSUE TITLE
Custom loot tables not working

### ISSUE THREAD

**Issue by zhekalevin** [PaperMC/Paper#2506]
### What behaviour is expected:
Using `/loot spawn ~ ~ ~ loot custom:custom` should spawn a number of items from the custom datapack loot table.

### What behaviour is observed:
Using the command produces an error "An unexpected error occured trying to execute that command". 

### Steps/models to reproduce:
1) Create an empty datapack and add a custom loot table to it. For example, like this:
`{
	"pools": [{
		"rolls": {
			"min": 1,
			"max": 25
		},
		"entries": [{
			"type": "item",
			"name": "minecraft:stone",
			"weight": 1,
			"functions": [{
				"function": "set_count",
				"count": 0
			}]
		}]
	}]
}`

2) Then spawn loot from the loot table using `/loot spawn ~ ~ ~ loot custom:custom`. 
Using `/loot give` or `/loot insert` is going to drop 0 items every time despite `"rolls": {"min": 1,"max": 25}`.
3) Copy the datapack to a vanilla server to confirm that the behavior is a bug.

### Plugin list:
N/A

### Paper build number:
git-Paper-175 (MC: 1.14.4)

### Anything else:
N/A

**Comment by electronicboy** [comment]
Is there anything in the server logs? Have you tested on spigot/craftbukkit?

**Comment by zhekalevin** [comment]
No, nothing in the logs, just that I issued the `/loot spawn` command. Tested on spigot, same bug.

**Comment by metroite** [comment]
My datapacks work with custom loot tables and I have tested it with blocks and entities

**Comment by mikroskeem** [comment]
Can you provide the datapack for testing?

**Comment by S-RoadRunner-S** [comment]
I have this same issue.  Nothing in logs...just a "An unexpected error occurred trying to execute that command".
What's really strange is that it works in my Single User World but doesn't in my Hosted Multi-User World. I get the error in the Hosted Multi-User World.

Any insight is appreciated.

loot_table:
{"pools":[{"rolls":{"min":1,"max":100},"entries":[{"type":"item","name":"minecraft:stone","weight":1,"functions":[{"function":"set_count","count":0}]}]}]}

Command Block to store in scoreboard "rng" as player "number":
execute store result score number rng run loot spawn ~ ~ ~ loot arena:num

EDIT:  It seems to work as long as the "count" is anything but "0". When I set to "1" it works but then leaves a stack of stone. I don't want the stone.  :(
Setting to "0" works in single user...what's wrong with multi-user?

**Comment by Utlamo** [comment]
I have this same problem on spigot. I Using {"function":"set_count","count":0} in my loot table.

**Comment by aikar** [comment]
You need to stop using set_count 0, this is an illegal value that the game does not allow. 

The only flaw here is that single player isn't telling you that you did something wrong.

**Comment by Maddox-RVS** [comment]
So what do we use instead? Becuase I am having the same issue, If is set 'set_count" function to 1 it still doesnt work on the server running bukkit/spigot, and if I delete the functions option (basically deleing set_count func from the loot table) in my json for the custom loot table, it STILL not working on a bukkit/spigot server. This all works in single player however.

**Comment by MiniDigger** [comment]
please open a new issue with your loottable/datapack, server version, plugins, etc

**Comment by Utlamo** [comment]
How works as intended? You dont support datapack? set_count 0 is current value becouse remove item, also result from command is equal random roll. So all datapacks where is used this simple and easy way to get random number dont work. If you can't fix this now dont use works as intended, but its misleading for people who try find reson why downloaded from internet datapack dont work.

**Comment by MiniDigger** [comment]
please open a new issue with your loottable/datapack, server version, plugins, etc
