### ISSUE TITLE
mojang join game code crash

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2508]
Hello,
Since the installation of 1.14.4 on one of our hubs servers, after a few hours of launch, we encounter a thread dump.
Here is the error: https://gist.github.com/Heliosard/aaf07fa16be75471a65e8b7c2248d0db

> Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.

I took the liberty of doing so after contacting the ProtocolSupport developer on this subject.
Here is his answer:

> This method literally calls mojang join game code, so not a protocolsupport problem.

Thank you in advance for your help.

### Plugin list:
BuycraftX, Citizens, CitizensCMD, ConditionalCommands, FeatherBoard, HChat-Bukkit, HDLinkSpigot, HHelp, HLang, HLobbyInteracts, HolographicDisplays, HTitles, LuckPerms, MVdWPlaceholderAPI, NoCheatPlus, PlaceholderAPI, PlayerUUIDCache, ProtocolLib, spark, TAB, TitleAdvanced, Vault, ProtocolSupport, ProtocolSupportAddon, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Any

### Paper build number:
git-Paper-176 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
as the warnings state, speak to us on IRC/Discord for support, your server is taking too long to tick
