### ISSUE TITLE
Chunks aren't unloading

### ISSUE THREAD

**Issue by ducitymp** [PaperMC/Paper#2515]
###  Timings or Profile link:
https://timings.aikar.co/?id=4999545942e84070b38b747b3e6a0684

### Description of issue:
Chunks never unload. The total amount of loaded chunks keeps increasing. If I use the '/paper debug chunks' command it shows alot of chunks with '""queued-for-unload": true'.

### Plugin list:
http://prntscr.com/oyvnik

### bukkit.yml, spigot.yml, paper.yml, server.properties
Bukkit.yml: https://pastebin.com/Nny2fLVW
Spigot.yml: https://pastebin.com/gBBnr8BT
Paper.yml: https://pastebin.com/KgXGz7b3
Server.properties: https://pastebin.com/WuCPUHzq

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

No links but there is a chunk dump in the attachments.

[chunks-2019-08-29_00.35.07.txt](https://github.com/PaperMC/Paper/files/3553158/chunks-2019-08-29_00.35.07.txt)

### Paper build number:
Paper-176

**Comment by Spottedleaf** [comment]
the chunks are queued for unload since being at level 45

if you have saving disabled this will happen since unloads are not processed, check that

**Comment by ducitymp** [comment]
That worked! Thanks for the fast reply.
