### ISSUE TITLE
enable-player-collisions not working

### ISSUE THREAD

**Issue by sandor111** [PaperMC/Paper#2517]
So in my paper.yml I have this:
enable-player-collisions: false

But players can still push each other.

[18:36:56 INFO]: This server is running Paper version git-Paper-642 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[18:36:56 INFO]: Previous version: git-Paper-629 (MC: 1.13.2)

**Comment by BillyGalbreath** [comment]
Feature works fine. As noted in the documentation, you most likely have a plugin overiding scoreboards/teams, which causes this feature to not work as expected. Hard to tell, though, because you didn't fill out the issue template :/

**Comment by sandor111** [comment]
Yea it is probably

**Comment by CaptainAmpersand** [comment]
I'm not too sure about your personal plugins, but in my case the plugin "TAB" had overriden the collision. Hope this might be able to help you!

**Comment by electronicboy** [comment]
Conflict with plugins is outside of the realms of what we can properly handle given how plugins interact with scoreboards, it's pretty much 100% up to them to provide support for this (shamefully, Mojang decision to use scoreboards here was pretty bleh)

**Comment by sandor111** [comment]
Turned out to be caused by SkRayFall
