### ISSUE TITLE
Suggestion: Add Strict Minecraft Client Version Support

### ISSUE THREAD

**Issue by BaltimoreCalling** [PaperMC/Paper#252]
# Suggestion

Ok, so again...nooby mcnoob here. My terminology may be a bit...noobish.

The Mojang vanilla instances of the server jar are not backwards compatible with previous versions. Only 1.9.2 clients can connect to 1.9.2 servers, etc. This sounds like kind of a pain, but it does do one thing: it keeps hacked clients out until they update to the proper version of Minecraft (which they have been slow to do).

Currently, any version of 1.9 can connect to Spigot/Paper servers, meaning all of those people with hacked clients released for 1.9 can connect, and easily hack.

If it's possible, and perhaps make an option available, make paper only allow clients using the current Minecraft client version able to connect.

**Comment by Brokkonaut** [comment]
You can do it with a plugin with protocollib.

**Comment by aikar** [comment]
those hacked clients will then just spoof their version to say they are 1.9.2....

Sorry not something that provides benefit.
