### ISSUE TITLE
crash report paper build 175

### ISSUE THREAD

**Issue by leoncp9** [PaperMC/Paper#2520]
log
https://pastebin.com/EdpBCuhB
server version paper spigot 1.14.4 build 175

crash
https://drive.google.com/open?id=1pOJSMDjMgUsDIOz1fUUgiE4u22p1wNtD

**Comment by Black-Hole** [comment]
The world generator plugin you're using for the world "plotworld" (presumably PlotSquared) isn't compatible with 1.14.4, you should look for an update of that plugin.
