### ISSUE TITLE
ConnectionHandler affecting server performance

### ISSUE THREAD

**Issue by rickylegada** [PaperMC/Paper#2524]
###  Timings or Profile link:
https://timings.aikar.co/?id=09cd07482f2f49ef9834f7d6f471b3aa
https://sparkprofiler.github.io/#4cY5LPyZY8

### Description of issue:
I have consulted some developers regarding the ConnectionHandler problem lately and when we saw the spark profiler, we're not sure what's causing it and we concluded that it would be best for paper team to have it looked at.

### Plugin list:
![image](https://user-images.githubusercontent.com/40695735/64067829-86fafb00-cc61-11e9-94f6-f870cb2ecc5e.png)

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://pastebin.com/Pvun0d6b - bukkit.yml
https://pastebin.com/5Ka42ZPy - spigot.yml
https://pastebin.com/4pgBDMQ8 - paper.yml
https://pastebin.com/maNGrvKJ - server.properties

### Paper build number:
Paper("988887d2")

**Comment by electronicboy** [comment]
This issue tracker isn't really the best place for general performance support, timings is mostly just looking like it's just a general overload, e.g. reduce entities, view distance, etc; Spark is mostly pointing towards maps, but accuracy of a sampler can be somewhat questionable and we might be missing a lot more information there
