### ISSUE TITLE
Scoreboard objective doesn't increase: minecraft.used:minecraft.bone_meal

### ISSUE THREAD

**Issue by metroite** [PaperMC/Paper#2527]
### What behaviour is expected:
Increasing value for the player in the objective minecraft.used:minecraft.bone_meal when using bone_meal items on the ground

### What behaviour is observed:
The value is not increasing

### Steps/models to reproduce:
1. Create scoreboard:
/scoreboard objectives add bonemeal minecraft.used:minecraft.bone_meal
2. Setdisplay scoreboard:
/scoreboard objectives setdisplay sidebar bonemeal

### Plugin list:
none

### Paper build number:
177

**Comment by xt449** [comment]
Also does not count when used on wheat, pumpkin stem, melon stem, beetroots, potatoes, carrots, grass.
