### ISSUE TITLE
/data modify Item NBT modification in player inventory is not possible eventhough it is in vanilla

### ISSUE THREAD

**Issue by metroite** [PaperMC/Paper#2528]
### What behaviour is expected:
See the Item NBT change in the inventory of the target player

### What behaviour is observed:
It was uneffected and the NBT hasn't been changed

### Steps/models to reproduce:
1. Modify any item in a inventory of a player:
/data modify entity @s SelectedItem.tag.modify set value 1
2. Check if the value changed:
/data get entity @s SelectedItem.tag.modify
3. Find out that it hasn't and be sad.

### Plugin list:
none

### Paper build number:
177

### Anything else:
Minecraft states that player data is not modifyable as a chat feedback. In Vanilla it works nevertheless. I would like to see that being the case here too (hence being like in vanilla).

**Comment by xt449** [comment]
Minecraft bug, see https://bugs.mojang.com/browse/MC-145179
Marked as intended here: https://bugs.mojang.com/browse/MC-122102

**Comment by metroite** [comment]
> 
> 
> Minecraft bug, see https://bugs.mojang.com/browse/MC-145179

I know, but its not working like it is in vanilla and therefore it is breaking many of my datapacks which rely on this feature/bug, however you might call it.
Would be awesome though if Paper made this an intended feature! Or at least make it like it is in vanilla.
