### ISSUE TITLE
Exception ticking world - 1.14.4 - Build #182

### ISSUE THREAD

**Issue by RealGatt** [PaperMC/Paper#2529]
### Link/paste of stack trace

https://pastebin.com/nPsafV5r

### Plugin list:
CoreProtect v2.17.5 net.coreprotect.CoreProtect 
LuckPerms v4.4.1 me.lucko.luckperms.bukkit.LPBukkitBootstrap  
WorldEdit v7.0.1;61bc012 com.sk89q.worldedit.bukkit.WorldEditPlugin 
EntityTrackerFixer v1.0.3* net.minemora.entitytrackerfixer.EntityTrackerFixer
AsyncWorldEdit v3.6.4 org.primesoft.asyncworldedit.AsyncWorldEditBukkit
BlockLocker v1.6.1 nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl
ClearLag v3.0.6 me.minebuilders.clearlag.Clearlag
PlugMan v2.1.6 com.rylinaux.plugman.PlugMan
WorldBorder v1.9.10 (beta) com.wimbli.WorldBorder.WorldBorder
Vault v1.7.2-b107
ProtocolLib v4.5.0-SNAPSHOT com.comphenix.protocol.ProtocolLib 
WorldGuard v7.0.0;02b731f com.sk89q.worldguard.bukkit.WorldGuardPlugin 
SpudClub v1.0 space.gatt.mscraft.Main - Custom plugin by me, does small things.
AuctionHouse v1.8.2 com.spawnchunk.auctionhouse.AuctionHouse
Quests v3.7.8-b16 me.blackvein.quests.Quests  
CustomHeads v2.9.6* de.mrstein.customheads.CustomHeads
Essentials v2.17.1.12 com.earth2me.essentials.Essentials
EssentialsProtect v2.17.1.12 com.earth2me.essentials.protect.EssentialsProtect
EssentialsChat v2.17.1.12 com.earth2me.essentials.chat.EssentialsChat
TAB v2.5.1 me.neznamy.tab.bukkit.Main
EssentialsSpawn v2.17.1.12 com.earth2me.essentials.spawn.EssentialsSpawn

### Actions to reproduce (if known):
Happens randomly. Couldn't find anything to link the crashes. 

### Paper build number:
Paper-182 (of course as soon as I post this theres a 183)

**Comment by RealGatt** [comment]
Updated to build #183, and updated a few of the plugins - hasn't happened since. Will update if it does.

**Comment by Spottedleaf** [comment]
NPE in fastutil iteration is a sign of concurrent modification

**Comment by RealGatt** [comment]
👍 Haven't had the error since updating plugins. Gonna close for now.
