### ISSUE TITLE
High chunk tick

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#253]
Since 1.9 my chunk tick has been high and its really putting a strain on my server... Can you somehow optimize it please, When i was on 1.8 i could hold 60-70 players @ 20tps now i cant even hold 35-40 at a 20tps, 1.9 shouldn't have such a big drop like that. Please can do some serious optimizing? 

My timings: https://timings.aikar.co/v2/?id=4246e54760384ba8b7dfec963fb99754&section=all

**Comment by zachbr** [comment]
Duplicate of GH-201
