### ISSUE TITLE
Nighttime detector not working with eigencraft redstone

### ISSUE THREAD

**Issue by NathanCollaert** [PaperMC/Paper#2530]
### What behaviour is expected:
___What you expected to see___
A nighttime detector shouldn't emit a redstone signal when it is daytime.

### What behaviour is observed:
___What you actually saw___
A nighttime detector emits a redstone signal even if daytime.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
(1. Enable eigencraft redstone) <-- haven't tested without.
2. Place a daytime detector and change it to a nighttime detector.
3. Place something that can show you a redstone signal besides the detector.
4. Notice redstone pulse even when daytime.

### Plugin list:
___A list of your plugins___
None

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
Paper version git-Paper-176 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by BillyGalbreath** [comment]
Daytime sensors send out a single strength based on amount of light. Its not on or off, but a wide range.

https://youtu.be/Jdj3fAsv2LY

**Comment by Proximyst** [comment]
This is intentional behaviour, see Billy's video.
