### ISSUE TITLE
[BUG] Invisible armorstands can't be removed by players (no plugins installed)

### ISSUE THREAD

**Issue by LoneDev6** [PaperMC/Paper#2531]
### What behaviour is expected:
Armor stand removed when player hits it

### What behaviour is observed:
Armor stand can't be removed by player, it was possible back in Paper version 173

### Steps/models to reproduce:

spawn invisible armorstand
```
/summon minecraft:armor_stand ~ ~ ~ {Invisible:true}
```

### Plugin list:
nothing

### Paper build number:
This server is running Paper version git-Paper-183 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by BillyGalbreath** [comment]
Can confirm. Likely caused from [this](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/6ed8a189660db58e31d4768a1916a3e79a73d544) upstream commit.

Edit: Yup, the `bD` field is used for invisiblity, so invisible armorstands are not receiving damage.

**Comment by LoneDev6** [comment]
So it's a spigot bug? I have to report it to spigot jira?

**Comment by LoneDev6** [comment]
This surely would break a lot of plugins.. do you have any advice to fix my plugin since this seems to be a new introduced feature and not a bug? I need to detect players trying to break invisible armorstand

**Comment by BillyGalbreath** [comment]
It's not intended, it's a bug.

**Comment by LoneDev6** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/6ed8a189660db58e31d4768a1916a3e79a73d544
> SPIGOT-5290: Invulnerable and/or Marker armor stand triggers EntityDamageEvent

I think they added this as a feature

**Comment by BillyGalbreath** [comment]
Invisibility is not part of that feature

**Comment by LoneDev6** [comment]
Oh sorry I misread Invulnerable, so I have to report this to official Spigot jira?

**Comment by HexedHero** [comment]
Doesn't it make sense if something in invis you can't dmg it?

**Comment by BillyGalbreath** [comment]
> Doesn't it make sense if something in invis you can't dmg it?

No, because you can hit every other invisible entity in the game. Think about those invisible spiders that spawn in hard mode.. ;)

**Comment by BillyGalbreath** [comment]
I'm trying to fix this, if my local Paper clone will behave :S

**Comment by HexedHero** [comment]
> > Doesn't it make sense if something in invis you can't dmg it?
> 
> No, because you can hit every other invisible entity in the game. Think about those invisible spiders that spawn in hard mode.. ;)

You can still see them tho, they aren't fully invisible. Armour stands are completely not there at all, anything else that can go invis has particles/sounds/some part visible. I don't think it'll be changed in Spigot back to what it normally was.

**Comment by HauserGrim** [comment]
Are you sure this is a bug? Check in single player.

As far as I remember, invisible armor stand can only summoned with a command and deleted with the other command (/minecraft:kill @e and specify type and coords)

Sorry for bad english :D

**Comment by HexedHero** [comment]
> Are you sure this is a bug? Check in single player.
> 
> As far as I remember, invisible armor stand can only summoned with a command and deleted with the other command (/minecraft:kill @e and specify type and coords)
> 
> Sorry for bad english :D

Its never worked like that in vanilla/SP, Spigot just finally got around to fixing it seems and people complaining because they used a bug for their plugin.

**Comment by LoneDev6** [comment]
Ok so how can I detect players trying to remove an invisible armorstand? Without EntityDamageEvent I can't check if a user can destroy or not the furniture.

**Comment by LoneDev6** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-5309

**Comment by LoneDev6** [comment]
If anyone's interested I ended up using packets to detect this behaviour, but I still hope spigot will have a leftclick event implemented.

https://www.spigotmc.org/threads/check-if-armorstand-is-left-clicked-by-player.394264/#post-3542242

**Comment by andfont** [comment]
I have the same problem! my plugins with armor-stand have stopped working because events are not activated! EntityDamageEvent etc ... because they are invisible now the user cannot remove them! please why are you doing these things? Fixing this is not invulnerable if you are invisible or do not have to activate events please! fix this thanks!

**Comment by andfont** [comment]
It is terrible if the armor-stand is invisible does not trigger any events! it's terrible! It does not work: PlayerInteractEntityEvent, PlayerArmorStandManipulateEvent, EntityDamageEvent etc. none!! big mistake big bug !! please fix this !!

**Comment by HexedHero** [comment]
> It is terrible if the armor-stand is invisible does not trigger any events! it's terrible! It does not work: PlayerInteractEntityEvent, PlayerArmorStandManipulateEvent, EntityDamageEvent etc. none!! big mistake big bug !! please fix this !!

Dude, fucking chill.

This change was nothing to do with paper, go complain to Spigot.

**Comment by andfont** [comment]
I have already done it but I didn't know that paper was a slave, it would depend so much, it was almost a copy of spigot. I think I'll go to spigot again because from what I see you depend too much on spigot, I thought it was more independent and not an almost direct copy!

**Comment by HexedHero** [comment]
> I have already done it but I didn't know that paper was a slave, it would depend so much, it was almost a copy of spigot. I think I'll go to spigot again because from what I see you depend too much on spigot, I thought it was more independent and not an almost direct copy!

Then you clearly don't understand what Paper is then.

**Comment by ArctoranDev** [comment]
Given Spigot has resovled it can we confirm Paper has fixed it? https://hub.spigotmc.org/jira/browse/SPIGOT-5309

**Comment by electronicboy** [comment]
Fixed by upstream, event is now fired as cancelled for this
