### ISSUE TITLE
1.14.4 Build #186 World save performance

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#2533]
###  Timings or Profile link:
https://timings.aikar.co/?id=dc69ed75b58b489b95dcb22d8fa84804

### Description of issue:
World save and entity problem.

### Plugin list:
in timings

### bukkit.yml, spigot.yml, paper.yml, server.properties
in timings
### Other helpful links
İ have Nwme disc i9 cpu and i have 17 player world save tps drop.

### Paper build number:
build 186

**Comment by electronicboy** [comment]
The issue tracker is not the place for support with timings
