### ISSUE TITLE
1.14.4 Build #186 World save and entity problem

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#2534]
Timings or Profile link:
https://timings.aikar.co/?id=dc69ed75b58b489b95dcb22d8fa84804

Description of issue:
World save and entity problem.

Plugin list:
in timings

bukkit.yml, spigot.yml, paper.yml, server.properties
in timings

Other helpful links
İ have Nwme disc i9 cpu and i have 17 player world save and entity tps drop.

Paper build number:
build 186

**Comment by successed** [comment]
Why this closed ?

**Comment by electronicboy** [comment]
Because 1) This is not the place for support with timings 2) General performance issues are pretty well documented across the board for 1.14, we don't need another ticket for this

**Comment by successed** [comment]
1) Why did you close the previous one? This need timings link http://prntscr.com/p17wgc
2) When will you resolve performance issues?

**Comment by electronicboy** [comment]
We've had this discussion multiple times:
There is ongoing work on the server, however, the major performance fixes for 1.14 are going to have to come from mojang.

And, given that we've had this discussion multiple times: There is no need for yet another ticket about the performance of 1.14 being bad, we know, mojang knows. This is also not the place to request general support for your server given that it needlessly floods peoples emails.

**Comment by successed** [comment]
> We've had this discussion multiple times:
> There is ongoing work on the server, however, the major performance fixes for 1.14 are going to have to come from mojang.
> 
> And, given that we've had this discussion multiple times: There is no need for yet another ticket about the performance of 1.14 being bad, we know, mojang knows. This is also not the place to request general support for your server given that it needlessly floods peoples emails.

I was using 176 and I went to 186 and these problems arose. Do I have to use 176 again?
176 I do not encounter the error of saving the world. Why do I come across 186?

**Comment by successed** [comment]
and I'm currently having this problem despite using i9 cpu vs nvme disk ddr4 ram.
