### ISSUE TITLE
Significant TPS drop down with 1.14.4 from tickEntities

### ISSUE THREAD

**Issue by YellowZaki** [PaperMC/Paper#2535]
###  Timings or Profile link:

https://timings.aikar.co/?id=64e8fc3760644c16a8c0815b4d57beb4

### Description of issue:

Since I updated to 1.14.4, my TPS have dropped down significatly. I used to have 20tps with 50 players. Now I have 6-7tps.
I can't/I don't know how to identify the issue. In the timings I think the lag comes from Minecraft::tickEntity - nms.EntityEnderCrystal. But everytime I get a timing, the name of the entity  at the top changes. Sometimes it is Horse, ItemFrame... It is very strange.

### bukkit.yml, spigot.yml, paper.yml, server.properties
Paper: https://pastebin.com/jUfwTQAK
Spigot: https://pastebin.com/RcNa8Us4
Bukkit: https://pastebin.com/X8h11jFZ

### Paper build number:

183 (1.14.4)

**Comment by lorek123** [comment]
I've started with 1.14.4 but the tps are now significantly low: https://timings.aikar.co/?id=3653e7c1633c448d9f6663108893eee3#
I didn't had such big amount of Sheeps and Turtles on loaded chunks to have such issues.

**Comment by successed** [comment]
There is mojang problem.

**Comment by successed** [comment]
> ### Timings or Profile link:
> https://timings.aikar.co/?id=64e8fc3760644c16a8c0815b4d57beb4
> 
> ### Description of issue:
> Since I updated to 1.14.4, my TPS have dropped down significatly. I used to have 20tps with 50 players. Now I have 6-7tps.
> I can't/I don't know how to identify the issue. In the timings I think the lag comes from Minecraft::tickEntity - nms.EntityEnderCrystal. But everytime I get a timing, the name of the entity at the top changes. Sometimes it is Horse, ItemFrame... It is very strange.
> 
> ### bukkit.yml, spigot.yml, paper.yml, server.properties
> Paper: https://pastebin.com/jUfwTQAK
> Spigot: https://pastebin.com/RcNa8Us4
> Bukkit: https://pastebin.com/X8h11jFZ
> 
> ### Paper build number:
> 183 (1.14.4)

bukkit.yml - set this ;

spawn-limits:
  monsters: 10
  animals: 5
  water-animals: 2
  ambient: 8
ticks-per:
  animal-spawns: 5
  monster-spawns: 1
  autosave: 6000

**Comment by Kapono5000** [comment]
Have you been able to figure this out? I am experiencing the same problems.

**Comment by Zoiter7** [comment]
Hey! Try to use this plugin :p
https://www.spigotmc.org/resources/entitytrackerfixer-fix-1-14-4-entitytick-lag.70902/

Regards
