### ISSUE TITLE
Shulker projectiles explode immediatly

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#2536]
The projectiles of shulker explode immediately and no longer fly towards players. This issue does not occur using version 641 with the same setup.

Paper 1.13.2 643-645

**Comment by Spottedleaf** [comment]
video?

**Comment by TheoRetisch1** [comment]
So you can't reproduce the issue? o.O It looks like this if they open and start shooting at you: https://imgur.com/a/NjVQnly

**Comment by AJMFactsheets** [comment]
Can confirm this is an issue on a brand new server with no plugins running Paper 1.13.2 build 645.

**Comment by HexedHero** [comment]
Confirmed
https://cdn.hexedhero.com/u/r9GUYIneyP.mp4

**Comment by AJMFactsheets** [comment]
After further testing, this bug first shows up in Paper 1.13.2 build 642.

**Comment by zachbr** [comment]
Should be fixed in 647+
