### ISSUE TITLE
waiting on these chunks crash

### ISSUE THREAD

**Issue by Lusteroth** [PaperMC/Paper#2537]
### Link/paste of stack trace

https://pastebin.com/92AvZ1zY
https://pastebin.com/CHPmWgua
https://pastebin.com/xbjXcbK4

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

Server stops after the error

### Plugin list:
___A list of your plugins___

AsyncWorldEdit, BetterChairs*, BlockParticles, BlocksHub, ChestShop, ClearLag, Confiscate, EH-OnlyProxyJoin*, Essentials, EssentialsChat, EssentialsSpawn, GCore, HolographicDisplays, IllegalStack, Jobs, JumpPads*, LagMonitor, LuckPerms, Matrix, Multiverse-Core, PlaceholderAPI*, PlotSquared, ProtocolLib, QuickBoard*, SimpleAPI, SimplePets, SkinsRestorer, TAB, Vault, WorldBorder, WorldEdit, WorldGuard

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Server is crashing - I really do not know why

### Paper build number: 
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

Build 186 (1.14.4)

**Comment by electronicboy** [comment]
matrix is deadlocking the server by trying to load chunks off the main thread

**Comment by Lusteroth** [comment]
Is there a way to help the developer of matrix? Maybe tell him what he needs to change?

**Comment by electronicboy** [comment]
They need to read the API spec and stop accessing stuff async
