### ISSUE TITLE
Server keeps crashing without reason

### ISSUE THREAD

**Issue by eatalotyo** [PaperMC/Paper#2539]
### Link/paste of stack trace

[01:13:56] [Server thread/ERROR]: Encountered an unexpected exception
--
328 | net.minecraft.server.v1_14_R1.ReportedException: Exception ticking world
329 | at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1187) ~[minecraft_server.jar:git-Paper-17]
330 | at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[minecraft_server.jar:git-Paper-17]
331 | at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1057) ~[minecraft_server.jar:git-Paper-17]
332 | at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:902) ~[minecraft_server.jar:git-Paper-17]
333 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
334 | Caused by: java.util.ConcurrentModificationException
335 | at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_222]
336 | at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_222]
337 | at net.minecraft.server.v1_14_R1.TickListServer.a(TickListServer.java:81) ~[minecraft_server.jar:git-Paper-17]
338 | at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:276) ~[minecraft_server.jar:git-Paper-17]
339 | at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1174) ~[minecraft_server.jar:git-Paper-17]
340 | ... 4 more
341 | [01:13:56] [Server thread/ERROR]: 	Cause of unexpected exception was
342 | java.util.ConcurrentModificationException: null
343 | at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_222]
344 | at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_222]
345 | at net.minecraft.server.v1_14_R1.TickListServer.a(TickListServer.java:81) ~[minecraft_server.jar:git-Paper-17]
346 | at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:276) ~[minecraft_server.jar:git-Paper-17]
347 | at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1174) ~[minecraft_server.jar:git-Paper-17]
348 | at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[minecraft_server.jar:git-Paper-17]
349 | at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1057) ~[minecraft_server.jar:git-Paper-17]
350 | at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:902) ~[minecraft_server.jar:git-Paper-17]
351 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

### Plugin list:
ClearLag
Essentials
MFHoppers
StackMob
Vault
WorldBorder
WorldEdit
WorldGuard

### Actions to reproduce (if known):
I simply start up the server and this keeps happening, despite uninstalling and reinstalling the plugins.

### Paper build number:
Paper/Bukkit 1.14

**Comment by KisaragiEffective** [comment]
Build number required. Ensure you ran latest build.
