### ISSUE TITLE
tickEntity error

### ISSUE THREAD

**Issue by p82183645** [PaperMC/Paper#2547]
![image](https://user-images.githubusercontent.com/5382252/64543442-cf986f80-d357-11e9-91c7-c909e1f97bd4.png)

paper 1.14.4 latest

**Comment by zachbr** [comment]
This occurs when a plugin tries to make an entity attack that doesn't have the correct attack attributes, typically passive mobs.

Also, please correctly fill out the template next time you report an issue.
