### ISSUE TITLE
monsters frozen outside activation range go into super speed once activated

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#255]
it seems like monsters that are outside of activation range go into some sort of speeding up mode where they go super speed if outside activation range for a very long time once a players enters their activation range. just had a creeper, once i went near enough, sprint to me at an insane speed and instantly explode before i could even react, pretty bizarre and funny. have also had zombies and skellies be much faster than usual if de-activated for a while.

paper build 712

**Comment by zachbr** [comment]
Has anyone been able to reproduce this?
@bonces are you still seeing this issue?
