### ISSUE TITLE
Pig Zombie no angry on turtle egg

### ISSUE THREAD

**Issue by MrJorman** [PaperMC/Paper#2550]
Decided to make a gold farm, but Pig Zombie no angry on turtle eggs, please fix problem

**Comment by zachbr** [comment]
Fill out the issue template
https://github.com/PaperMC/Paper/issues/new/choose

**Comment by HexedHero** [comment]
I think he means that Pigmen zombies aren't stomping on turtle eggs to destroy them.

@MrJorman Please test this on Vanilla Spigot with no plugins and see if they do it if not its a Spigot MAYBE vanilla bug if they do test on Paper and report back if they do or not.

However it is working fine for me on Paper 187
http://cdn.hexedhero.com/u/CZBS2jXsV0.jpg

**Comment by BillyGalbreath** [comment]
@MrJorman please verify you have the mob griefing gamerule set to true, as this is a requirement for the Pathfinder to target the turtle eggs.

Unable to reproduce on my end.
