### ISSUE TITLE
Reimplement Chunk-Regeneration

### ISSUE THREAD

**Issue by Cytoox** [PaperMC/Paper#2551]
We are hosting a minecraft-network with 500-1000 concurrent players and we love to use paper especially because of the performance problems in the new versions (our servers are running on 1.14.4).

Now we have a problem: With version 1.14 it is no longer posible to regenerate chunks like before: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#regenerateChunk-int-int-

We need an implementation of that for the version 1.14.4 but our dev-team has not the time and the knowledge to do this. So we decided to give the person that can do this for us a donation of 150€. The condition is a working implementation for regenerating chunks that works like World#regenerateChunk in version 1.13.2 or better.

If you need any proof for this offer, add me on Discord: Cytoox#3169

Thanks for you time!

**Comment by HexedHero** [comment]
@Spottedleaf ez 150€

**Comment by LoneDev6** [comment]
@Cytoox you could use https://www.spigotmc.org/resources/coreprotect.8631/ and restore area to its original state. I know it's not the same thing but would help in the mean time.
(note that this will apply only from the moment you'll install CoreProtect as it logs block changes, it won't be able to know what changes were made before its installation).



Can I get my 150€? lol

**Comment by Cytoox** [comment]
Well thats not what we want 😅

**Comment by limwa** [comment]
From the JavaDocs
"Deprecated.
regenerating a single chunk is not likely to produce the same chunk as before as terrain decoration may be spread across chunks. Use of this method should be avoided as it is known to produce buggy results."

If you don't mind that, you can keep on using the regenerateChunk method.
If you do, you'd need to pretty much rewrite all world generation in order to support it. (Also, look below for another possible solution)

**Comment by LoneDev6** [comment]
@Cytoox 
Only way to restore the **exact** state of chunk is to save it with a logger plugin or a custom made one (pretty simple to do, you just have to save chunk data on chunk generation event).
If you don't care about getting the same exact chunk you can use regenerateChunk method as @PixelLima said

**Comment by kennytv** [comment]
... The point of this issue is that the method currently does not have any implementation at all.

**Comment by Gerrygames** [comment]
We don't need to restore the chunk 100% accurately. That's why we said "works like World#regenerateChunk in version 1.13.2 or better". It didn't work perfectly in 1.13.2 and doesn't need to be any better than that.
We can't use regenerateChunk, since it's functionality got completely removed. That's why we opened this issue in the first place.

**Comment by LoneDev6** [comment]
Only way to do that is to save chunk data on its first generation and restore it later.

**Comment by kennytv** [comment]
You are answering the wrong question - all they (and we) want is for that method to be reimplemented. Not to search for (hacky and/or memory intensive) alternatives 🤷‍♂️

**Comment by Gerrygames** [comment]
Well how did it work in 1.13.2 then? Again: We are not asking for chunks the be restored accurately. We only want an implementation in 1.14.4 like the one that exists in 1.13.2.

**Comment by limwa** [comment]
Let me see what I can do

**Comment by LoneDev6** [comment]
Maybe you can take a look at https://github.com/Jikoo/Regionerator code, it deletes chunk data directly from region files, so they can be regenerated automatically by server

**Comment by kickash32** [comment]
World Edit has a fix for this, you could try using the WE API.

**Comment by wizjany** [comment]
not so much a fix as a workaround. we just make a new world and copy blocks in from that.

**Comment by Foorcee** [comment]
Without restarting?

**Comment by LoneDev6** [comment]
> 
> 
> not so much a fix as a workaround. we just make a new world and copy blocks in from that.

Very smart, didn't think about this. Basically you have two copies of the world, one with no buildings and one where players can play?

**Comment by wizjany** [comment]
no, but you can do that with backups and the snapshot restore feature, which is completely separate but honestly much more useful if people have the foresight to make a backup.

edit: also for the record there's /delchunks, which does essentially the same thing as the regionerator that was linked earlier, though we only do it on a restart for safety reasons.

**Comment by Cytoox** [comment]
> World Edit has a fix for this, you could try using the WE API.

We are testing the workaround from worldedit on our live systems now. 
It seems to work well!

**Comment by Foorcee** [comment]
@wizjany Perhaps entities in the region should also be removed when regenerating

**Comment by wizjany** [comment]
This isn't the place to discuss worldedit features.

**Comment by dan-negura** [comment]
I’ll give it a go, I’ve been working with terrain generation for 8 months so I feel like I should try to solve this problem.

**Comment by dan-negura** [comment]
Alright so I thought regenerating was going to be easier to implement than how it is. So after many failed attempts I came up with a workaround that does it's job and replaces the chunks with original generation ones, but it requires first the creation of another world on the same server. Then the plugin allows for easy selection and import of chunks from the other world. The chunks are grabbed from the same place as the replaced ones, so there's no coordinate and schematic headaches.
Have a look for yourselves, I also published the source.
https://www.spigotmc.org/resources/chunktransfer-across-worlds-useful-for-chunk-regeneration.74219/

Edit: I know that this isn't a regen function, but honestly this is extremely close to that, and you don't need a backup, just instantiate a new world with the same seed and generator. Also this produces consistent results where the decoration is how it was originally (for obvious reasons).

**Comment by wizjany** [comment]
That's...pretty much exactly what worldedit does already?

**Comment by dan-negura** [comment]
> That's...pretty much exactly what worldedit does already?

What command would you use from WE to do that?
I'm not sure how easy it is to use WE's function, I wrote something that made sense to me in terms of simplicity and goal. Also my approach loads one chunk at a time, I tested it on a 600MB server with 40 x 40 chunks transferred, and it was fine.

**Comment by Foorcee** [comment]
I once created a suggestion for an implementation in Minecraft.

https://feedback.minecraft.net/hc/en-us/community/posts/360074834291--regenerate-command-for-tarrain-regeneration

**Comment by jumpsplat120** [comment]
What's the deal on this?

**Comment by lynxplay** [comment]
It has been labeled as accepted, concerning we are in the mids of updating to 1.18, this issue will most likely be looked at after the update is done :+1:

**Comment by Owen1212055** [comment]
There is currently an upstream PR that implements this feature.

**Comment by MiniDigger** [comment]
can you link it please for tracking purposes?

**Comment by Owen1212055** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/959/overview

**Comment by Fanisus** [comment]
Any Updates?

**Comment by electronicboy** [comment]
Please don't bump issues needlessly, you'll see that there is discussion upstream about this, we have little interest spending what time we have on this for upstream to just sweep it under our feets
