### ISSUE TITLE
Timing stack corruption CloneItemStack EntityFox

### ISSUE THREAD

**Issue by Technoguyfication** [PaperMC/Paper#2552]
### Link/paste of stack trace

    https://hastebin.com/uzebahoguf.md

### Plugin list:

12.09 01:00:39 [Server] INFO Plugins (13): dynmap*, Dynmap-Essentials*, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, LuckPerms, MessageAnnouncer, MineableSpawners, PlugMan, Vault, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Unknown, appeared in log

### Paper build number:
 158 mc 1.14.4

**Comment by HexedHero** [comment]
Update your paper version, this was fixed in a future version your not using!
Close this and update :D

**Comment by Technoguyfication** [comment]
Thanks! I should've looked more closely at the version number. My hosting _said_ I was on 187 but it appears that was wrong.
