### ISSUE TITLE
Pillagers using ridiculous amount of CPU time?

### ISSUE THREAD

**Issue by Technoguyfication** [PaperMC/Paper#2554]
###  Timings or Profile link:

https://timings.aikar.co/?id=d1590c2a5cf44567a9a5e8ae3aa9f5cd

### Description of issue:

My server TPS has been pretty low lately so I started investigating the cause of the issue. It looks like pillagers are using a significant amount of tick time (almost 40%). This seems like it has to be some sort of performance bug. In the timings report, I killed all the pillager entities loaded in the world (only 14 of them) right before the latest "notch" on the timeline and the pillager cpu time dropped down to nearly nothing. I don't think 14 mobs should be causing the TPS to drop to almost 15 TPS.

### Plugin list:

ClearLag, dynmap*, Dynmap-Essentials*, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, LimitPillagers, LuckPerms, MessageAnnouncer, MineableSpawners, PlugMan, Vault, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___

[spigot.yml](https://hastebin.com/igatuxuyic.cpp)
[paper.yml](https://hastebin.com/aqekufemus.coffeescript)
[bukkit.yml](https://hastebin.com/vejobijiza.coffeescript)

(sorry for the random languages in hastebin I'm trying to get this done before class lol)

### Other helpful links

None

### Paper build number:

187

**Comment by electronicboy** [comment]
Closing as a dupe, performance issues in 1.14 are well known, use discord/IRC for support
