### ISSUE TITLE
TIMING_STACK_CORRUPTION

### ISSUE THREAD

**Issue by poqdavid** [PaperMC/Paper#2555]
### What behaviour is expected:
Well normally shouldnt see the error

### What behaviour is observed:
https://hastebin.com/eqivowayaf.txt

### Steps/models to reproduce:
Not sure it just showed up on the console after I changed Minecraft version from 1.12.2 spigot to paper 1.13.2 it said to report it so i did

### Plugin list:
AdvancedPortals
AuthMe
FastAsyncVoxelSniper
FastAsyncWorldEdit
GadgetsMenu
LuckPerms
Plan
ViaBackwards*
ViaVersion*
Votifier
VotingPlugin
WorldEdit

### Paper build number:
 git-Paper-641 (MC: 1.13.2)

### Anything else:
Nope

**Comment by zachbr** [comment]
The small snippet of log you provided is not enough information to help you. Please provide significantly more.

**Comment by poqdavid** [comment]
Ok hastebin link is broken so https://paste.ee/p/wxYbX and its all that not even crash log
but also since the last reboot the server had it havent happened

**Comment by zachbr** [comment]
That new link isn't any better. Provide more logs if it happens again. That snippet is worthless

**Comment by poqdavid** [comment]
Well just found out this error happens when we run `//setbiome` and `/b biome` also we use
FastAsyncWorldEdit-bukkit-1.13.180.jar
FastAsyncVoxelSniper-favs-1.13.180.jar
Well thats like all

**Comment by Chew** [comment]
Both of the paste links are gone, and the issue sounds like it was caused by a plugin. Both Paper, and likely the provided plugins, have had numerous fixes and, as no one else has reporting having this issue, I will close it due to age and inactivity. If it does happen again, feel free to open a new issue.
