### ISSUE TITLE
WTF my TPS ???

### ISSUE THREAD

**Issue by MrJorman** [PaperMC/Paper#2557]
I when online to 40 online, TPS drops to 8-15 TPS. My timings: https://timings.aikar.co/?id=eb84437b6f05490ba7b4a9002ac334eb

Wtf man?? Fix please!

**Comment by MrJorman** [comment]
https://imgs.info/i/cLUFO

Map loading WorldBorder plugin a little, the TPS is small, even without plugins

**Comment by MrJorman** [comment]
New timings, 50 online: https://timings.aikar.co/?id=360c9798572e4acb9b87cd5d9d79569b

**Comment by MrJorman** [comment]
New timings, 60 online: https://timings.aikar.co/?id=2f1a0f2459b74cb7a94b74860fc5e454#timings

TPS 11.0-15.0

fix bro please. 

server: 2 x Core i7 8700K OC, 10Gb RAM, 80Gb NVME

**Comment by SlickJava** [comment]
https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/

make sure to get EntityTrackerFixer if the lag persists as well

**Comment by MrJorman** [comment]
UP!

**Comment by MiniDigger** [comment]
you have a dual socket i7 8700k? :doubt:

edit: oh, you use 2 cores of an i7 8700k, I see.
yeah, your server is just not powerful enough, maybe its even oversold by some crappy host. you don't even use the full 10gb ram your host seems to promise you 😂  
nothing paper can do.

**Comment by VADemon** [comment]
The host only gives your server a max of 8GB and artificially cripples CPU features (`UseSSE=3`)

Bad hoster.

**Comment by zachbr** [comment]
This issue tracker isn't for getting to the bottom of your server's performance issues.
