### ISSUE TITLE
zero tick farm

### ISSUE THREAD

**Issue by YBCM** [PaperMC/Paper#2558]
https://bugs.mojang.com/browse/MC-113809

Could Paper fix this?

**Comment by samolego** [comment]
I wouldn't agree with "fix", maybe making it optional. It's very useful in redstone contraptions.

**Comment by BillyGalbreath** [comment]
I wont fix MC-8328 but I can port the fix for MC-113809 to Paper.

**Comment by YBCM** [comment]
Oh I think I was a bit confused. I meant MC-113809

**Comment by Evident-Dev** [comment]
Is this something that we can re-enable? My server uses Zero tick farms a lot, feel like it should be optional.

**Comment by samolego** [comment]
Yeah, of course, my server uses them too. There's an ootion in paper config.
