### ISSUE TITLE
Items dropped in end portal vanish. Do not appear at Spawn.

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#2561]
### What behaviour is expected:
items that fall in end portal appear at spawn.

### What behaviour is observed:
 Items vanish. Do not appear at Spawn.

### Steps/models to reproduce:

- break bed to appear at spawn when you use end portal.
- go to end portal.
- throw items in end portal.
- enter portal.
- look for items. (no items)

### Plugin list:
no plugins.

### Paper build number:
git-Paper-187 (MC: 1.14.4)

**Comment by NullCase** [comment]
I don't know if it's possible, but in case the items are appearing somewhere... How could I find the location?

**Comment by fadillzzz** [comment]
I'm on the same version and everything works fine on my end.

**Comment by theocraat** [comment]
I found my items 25000 blocks in the air.
