### ISSUE TITLE
Too much pillagers causing server lag

### ISSUE THREAD

**Issue by Einsfier** [PaperMC/Paper#2565]
###  Timings or Profile link:
[Timing Report](https://timings.aikar.co/?id=e183b4fe15f54aef8192d382b0389b37)

### Description of issue:
Pillager outpost keeps spawning mobs until reachs the spawn-limits.
My setting for spawn-limits is
```spawn-limits:
  monsters: 50
  animals: 10
  water-animals: 10
  ambient: 3
```

**Be noted that** I have the setting `per-player-mob-spawns: true` which is introduced in recent commit.
I am not sure that Is this setting break the vanilla outpost behaviour or not.
Just for advise. :D

### Plugin list:
It's not necessary here. I didn't use any plugins which may break vanilla mob spawns.

### bukkit.yml, spigot.yml, paper.yml, server.properties
[server.properties](https://pastebin.com/vjncRThq)
[bukkit.yml](https://pastebin.com/nn5Dq2vw)
[spigot.yml](https://pastebin.com/Emy16BsH)
[paper.yml](https://pastebin.com/Nmwqyfdp)

### Other helpful links
I did a roughly count and confirmed that there are about 50 pillagers which correspond to the setting of spawn-limits.
I think there should be a special limit in settings for those pillagers spawn by outpost.
Any other ideas?

![image](https://user-images.githubusercontent.com/11040951/64950782-c99e1380-d8ae-11e9-98b8-931ec8e8abcb.png)

![image](https://user-images.githubusercontent.com/11040951/64950738-b12df900-d8ae-11e9-96a4-5e1f0d15db98.png)

### Paper build number:
git-Paper-186 (MC: 1.14.4)

**Comment by MrJorman** [comment]
yes yes, fix please, my timings is 12% pillager....

**Comment by MrJorman** [comment]
autosave: -1 go man, lagg save server... i'm russian, and i no know english so good

**Comment by kickash32** [comment]
Get the plugin known as LimitPillagers. Pillager spawning is unlimited, who knows what mojang was thinking.

**Comment by Einsfier** [comment]
> autosave: -1 go man, lagg save server... i'm russian, and i no know english so good

Thanks for advice.
But my MC server is running on dual-E5v4 with pure SSD storage.
Regular chunk saving barely affects the performance as paperMC has it optimized well.

**Comment by electronicboy** [comment]
Pillagers don't count towards the standard mob spawn limits and are entirely seperate, this is a pretty well known vanilla issue
https://bugs.mojang.com/browse/MC-156262

**Comment by Einsfier** [comment]
> Get the plugin known as LimitPillagers. Pillager spawning is unlimited, who knows what mojang was thinking.

Thanks. I'll try to fix this out later.
