### ISSUE TITLE
Multicraft player count is incorrect

### ISSUE THREAD

**Issue by StefanH-AT** [PaperMC/Paper#2567]
### What behaviour is expected:
___When a player disconnects, they should disappear from the "connected players" list and no longer count towards the online player display on multicraft___

### What behaviour is observed:
___Players that connect to the server get added to the online player count, but when they disconnect, they don't get removed. This leads to incorrect player statistics in multicraft___

### Steps/models to reproduce:
___Connect to the server. Disconnect.___

### Plugin list:
___ None ___

### Paper build number:
___git-Paper-186 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT___

**Comment by electronicboy** [comment]
This is down to how multicraft works, it would need to be configured correctly in order to match the logs; Not really a paper issue as much as multicraft needs configuring for the software running in there

**Comment by HexedHero** [comment]
multicraft sucks, move on.
