### ISSUE TITLE
Narrator: Narrates Chat - Doesn't work

### ISSUE THREAD

**Issue by metheos** [PaperMC/Paper#2568]
### What behaviour is expected:
Enabling the Narrator: Narrates Chat should read chat messages out loud for accessibility

### What behaviour is observed:
Enabling the Narrator: Narrates Chat has no apparent effect

### Steps/models to reproduce:
* Log into a PaperMC server on the latest build (192) or other recent builds (I started at 186)
* Enable Narrator: Narrates Chat in the client settings
* Observe chat messages that are not narrated

### Plugin list:
LuckPerms
Spark

### Paper build number:
This server is running Paper version git-Paper-192 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Anything else:
This works as expected in Vanilla
I found [this closed issue](https://hub.spigotmc.org/jira/browse/SPIGOT-3975) on spigot which may explain the technicalities. They marked it closed, but I guess it's a regression.

**Comment by electronicboy** [comment]
Shamefully, there is very little we can do about this, only way to fix this would involve removing the ability for plugins to format chat

**Comment by LightningXCE** [comment]
Is there any ability to disable the chat formatting? This is an important feature for a server that I run for accessibility.

**Comment by fchagas97** [comment]
I love this resolution lol
