### ISSUE TITLE
InventoryClickEvent occasionally not firing when moving items

### ISSUE THREAD

**Issue by Murreey** [PaperMC/Paper#2569]
### What behaviour is expected:
Creating a handler for an InventoryClickEvent should always run when items are moved around an inventory.

### What behaviour is observed:
Occasionally, when moving items in your inventory, the InventoryClickEvent doesn't run when placing the items down.

### Steps/models to reproduce:
I've been using a test event like this to reproduce the bug, with random colours so I can see if the chat moved/didn't move when expected to:

```java
@EventHandler(priority = EventPriority.LOWEST)
public void testClick(InventoryClickEvent event) {
    event.getWhoClicked().sendMessage(ChatColor.getByChar(Integer.toHexString(new Random().nextInt(16))) + "Inventory slot " + event.getSlot() + " clicked.");
}
```

Move an item around in a survival inventory. Every so often (say one in thirty moves?) the event won't fire when the item is placed back down. It won't send any message to chat, and the last slot number in your chat history will be different from where you placed the item (you can test this by picking it up again and you'll see the new, correct number).

It doesn't seem to happen in the creative inventory, but will in a normal survival inventory, or when you have a chest/plugin inventory opened (including in creative mode). Also doesn't seem to happen when just clicking around, or when picking items up. I've only seen it happen when placing the items back down.

I've also noticed that when it happens, the item in my hand (visible behind the inventory window) will move, and do the 'pop up' animation like when you move your selected slot to an item. Both hands will do it if I have the survival inventory open, but only the main hand when doing it through a chest.

### Plugin list:
Only a plugin I've made to test the issue, which only has the above event in it and nothing else.

### Paper build number:
git-Paper-192 (MC: 1.14.4)

### Anything else:
This has possibly been around since at least 1.12.2, as I've had players mention it before but I put it down to a random fluke/server lag/whatever.

**Comment by electronicboy** [comment]
You're probably missing handling events such as the inventory drag event,
I'm not aware of cases where this event doesn't fire outside of the client
blindly acting as if a drag was sent (even if for a single slot)

**Comment by Murreey** [comment]
Yeah looks like that's it - if your mouse moves even slightly between clicking the slot and releasing the click, it counts as a drag event and doesn't trigger an InventoryClick.

Seems like a trap a lot of people are going to fall in to, given how little you need to actually 'drag' for it to count. Surely if a drag event only has one 'dragged' slot, it's really just a click event?

Raises another issue as well - it _doesn't_ fire in the creative inventory. In fact it seems like drag events don't fire at all, and instead it fires a bunch of individual click events for every slot that was part of the drag.

**Comment by Shevchik** [comment]
Creative Inventory actually fires InventoryCreativeEvent, but handling anything in creative inventory is not really possible, since it's mostly client controlled.

**Comment by zeronerve** [comment]
So how do we execute code each time an item is moved to another slot, whether by a click or an accidental drag? I'm having trouble seeing which event fires after the last drag.

**Comment by electronicboy** [comment]
You need to handle all of the relevant inventory events, click, drag, etc; There is no way around it
