### ISSUE TITLE
Spawn too many monster

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#257]
![2016-04-26_17 00 14](https://cloud.githubusercontent.com/assets/16057404/14832014/65e9d9cc-0bf8-11e6-8b44-3b6749971af4.png)
![2016-04-26_17 08 21](https://cloud.githubusercontent.com/assets/16057404/14832013/65e94afc-0bf8-11e6-8967-6fa42264fd6c.png)
![2016-04-26_17 20 05](https://cloud.githubusercontent.com/assets/16057404/14832015/65ec87c6-0bf8-11e6-96cd-001af252ff07.png)
(used fullbright mod)

Bukkit.yml: http://pastebin.com/j0BAWr6J
Spigot.yml: http://pastebin.com/Zxh3Rabe
Paper.yml: http://pastebin.com/vnKuQm5j

Paper:
git-Paper-706 (MC: 1.9.2)

**Comment by ghost** [comment]
too many? that's my dream. i use pretty much same settings and get nowhere near that. how many players do you have when that happened? try changing ticks-per monster-spawns: 1 to 2 to 4 and mob-spawn-range: 4 to 3

**Comment by aikar** [comment]
This isn't a bug. We fixed bugs with mob spawning that has been in Spigot for years. 

You will need to tweak your bukkit.yml settings for mob limits and spigot.yml for mob spawn range to find your desired amount.

That picture does not look like its over 50.
