### ISSUE TITLE
I low TPS when 50 players online +

### ISSUE THREAD

**Issue by MrJorman** [PaperMC/Paper#2570]
Optimize your Paper or add please Multiprotocol because the server is at 40-50 online and above is already starting to lag and slow down, the TPS drops much.

Photo CPU, RAM, DISC: https://ibb.co/BPJyWm5

**Comment by Draycia** [comment]
Feel free to submit PRs to optimize aspects of the server.
Otherwise it's your job as the server owner to make changes as are necessary in order to sustain the server.

Considering your other two issues about your server's TPS were closed I'm not sure why you think this one is acceptable either.
