### ISSUE TITLE
paper 1.14.4 LEGACY_SIGN

### ISSUE THREAD

**Issue by leoncp9** [PaperMC/Paper#2574]
hello i get one problem with paperspigot 1.14.4
this is the problem
Hello, i get some error in paper 1.14.4, i can't finish game when i reach the limit of rounds
[Zombies] Plugin Zombies v1.3.7 generated an exception while executing task 44
https://pastebin.com/t66ELiSi

Could not pass event EntityDeathEvent to Zombies v1.3.7
https://pastebin.com/H7sg8u2c

Error occurred while disabling Zombies v1.3.7 (Is it up to date?)
https://pastebin.com/7KBaCDwE

developer write to me
Hey there again, so i tried to find and fix the issues now, there are good & bad news for you.

Good news: The first issue that you provided ( Stats Issues ) have been finally fixed ( update will be released in about 5 minutes )

Bad News: The 2 other issues can't be fixed, basically its an issue from "Paper Spigot" they are not really up to date like Spigot is. Basically i can't fix that, cause its an issue from their side, the only way would be to use the normal Spigot instead of the modified external Paper Spigot. You can also contact Paper Spigot with those issues, basically they haven't yet added multiple new block types like in this case "LEGACY_SIGN" if they get this fixed, then you can still use Paper Spigot, otherwise Spigot itself would be the only option. 

so can you fix this?

**Comment by Joo200** [comment]
LEGACY_SIGN is marked as Deprecated.
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#LEGACY_SIGN

The developer from Zombies uses deprecated stuff. Maybe he should update to non legacy materials?
The plugin is a premium plugin, there is no way to take a look at the source code from the plugin.

**Comment by electronicboy** [comment]
LEGACY_* materials are due to the plugin author not setting the api_version
of the plugin, this is not an issue on our side

**Comment by leoncp9** [comment]
ok thank
