### ISSUE TITLE
TIMINGS ON = 4-5 TPS why? TIMING OFF = 20 TPS 

### ISSUE THREAD

**Issue by FlashLight34** [PaperMC/Paper#2575]
###  Timings or Profile link:
i turned off timingsV2 forever now :|
but watch this https://timings.aikar.co/?id=006b0c29fda044eaad01809009a8a382

### Description of issue:
all in title :P 
i tryed to unload some map etc
and when i turned off timings i got back all my good TPS 5 -> 20 its magic its a new bug?

### Paper build number:
this server is running Paper version git-Paper-192 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by astei** [comment]
`timingcost: 9413`

You must be on an overloaded server or something, if this is higher than 300 or so you're in deep trouble. Find a different host.

Note that you also only have one CPU core available to the server, which also slows everything down.

**Comment by Spottedleaf** [comment]
If you want to record performance of timings you should use a sampler (i.e jvisualvm or spark).

I've found personally testing that sometimes timing overhead can cost me a couple TPS, but not something of this scale
And what astei said also applies

**Comment by zettlinger** [comment]
on a 2990WX timings also gives a severe hit and i only run it when i see tps dropping. Adding timings at that moment in time will drop it as low as 5 ! (17-20 when timings isnt on

**Comment by astei** [comment]
I'm taking back my words.

Today I decided to run a Paper 1.14.4 server on a VPS (Linode 4096) running FreeBSD 12.0-RELEASE. The server was constantly using 50+% CPU and was experiencing massive TPS drops (18 to 13 TPS). Even after applying optimizations, the server was still performing badly.

I upgraded to a Linode Dedicated 4GB plan and saw absolutely no difference in performance.

However, If I disable timings, then the server does in fact stay at 20TPS, and after warming up, is sitting at 6-7% when idle.

**Comment by astei** [comment]
Also, for reference, my `timingcost` has been consistently around the 15000-17165 range.

**Comment by zachbr** [comment]
So the real question is why is timings so expensive on these servers compared to everyone else.

**Comment by Hyronymos-Old** [comment]
Can confirm that I had the same Issue

I can reproduce it when ever you want on a 40-50 Users SkyBlock Server

**Comment by zachbr** [comment]
Confirmations without timings links arent going to help. We need all the info they provide.

**Comment by Hyronymos-Old** [comment]
Will send a timings report + a short video on YouTube tomorrow

**Comment by Spottedleaf** [comment]
it's preferable to also send in a sampling (i.e spark), so we can verify timings is an issue

**Comment by astei** [comment]
I posted these on Discord but I'm going to provide them here so it's in one place.

Here's some timings: https://sparkprofiler.github.io/#mI5y9csZH5

Here is a Spark profile without timings: https://sparkprofiler.github.io/#4fxC3TQ944
Here is a Spark profile with timings: https://sparkprofiler.github.io/#mI5y9csZH5

**Comment by Ghost-chu** [comment]
It works for me, after i disable the timings, tps from 11 back to 20!

**Comment by zettlinger** [comment]
I have timings disabled on default for a while , this timings report was with only 2 ppl on TPS was a solid 20 for hrs. Since only 2 ppl were on i decided to do a timings and it crashed tps from 20 to 10.8

(Making a new timings last was too short)
longer: https://timings.aikar.co/?id=2e69c2dd45ae474daaa65a96c2f5311d
even longer: https://timings.aikar.co/?id=9efb6a44b16a4920a4961ff4727bcec2
(now turned off since it halves tps)

ps. not sure how to do spark posts?
