### ISSUE TITLE
ItemStack has no enchantment

### ISSUE THREAD

**Issue by CodeDoctorDE** [PaperMC/Paper#2577]
### What behaviour is expected:
If I want to serialize an enchanted item, I want to have the enchantment after a deserialisation too.

### What behaviour is observed:
A no enchanted item.

### Steps/models to reproduce:
```java
public String serialize(){
        return gson.toJson(itemStack.serialize());
}
```
Value is the json string
```java
itemStack = ItemStack.deserialize(gson.fromJson(value, new TypeToken<Map<String, Object>>(){}.getType()));
```

### Plugin list:
Only my plugin.

### Paper build number:
 This server is running Paper version git-Paper-194 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)                

### Anything else:
The output json:
```json
{"mainhand":"{\"v\":1976,\"type\":\"STONE_SWORD\",\"meta\":{\"enchantments\":{\"Enchantment[minecraft:sharpness, DAMAGE_ALL]\":5},\"attributeModifiers\":{},\"repairCost\":0,\"hideFlag\":0,\"unbreakable\":false,\"damage\":0,\"placeableKeys\":[],\"destroyableKeys\":[],\"unhandledTags\":{},\"persistentDataContainer\":{\"customDataTags\":{},\"registry\":{\"CREATE_ADAPTER\":{},\"adapters\":{}},\"adapterContext\":{\"registry\":{\"CREATE_ADAPTER\":{},\"adapters\":{}}}},\"version\":1976}}"}
```

**Comment by electronicboy** [comment]
You need to deserialize the meta before the stack itself due to how bukkit works, using the JsonConfiguration library might be more ideal given that it should handle bukkit stuff properly
