### ISSUE TITLE
#194 invisible mobs

### ISSUE THREAD

**Issue by successed** [PaperMC/Paper#2578]
### What behaviour is expected:
I expected to see mobs on my server because thats how minecraft works.

### What behaviour is observed:
The mobs on the server are not showing up, you can hear the sounds but you cannot see or interact with them.

### Steps/models to reproduce:
You can login to my server if thats not a an issue dont really know how to put it in a video.

### Plugin list:
https://timings.aikar.co/?id=af215d8b8c8f41e3a080c2f0d8a51229

### Paper build number:
#194 

### Anything else:
It was working fine with #193

**Comment by HexedHero** [comment]
Just updated to test and doesn't happen with me, It seems to look like its one of your plugins not liking the new Spigot/Bukkit changes that were just pulled
https://cdn.hexedhero.com/u/ONf1JXawTM.jpg

**Comment by successed** [comment]
> Just updated to test and doesn't happen with me, It seems to look like its one of your plugins not liking the new Spigot/Bukkit changes that were just pulled
> https://cdn.hexedhero.com/u/ONf1JXawTM.jpg

Yeah, EntityTrackerFixer plugin is bad guy.
