### ISSUE TITLE
PlayerVelocityEvent not firing for fishing rod caused velocity

### ISSUE THREAD

**Issue by AoElite** [PaperMC/Paper#2579]
### What behaviour is expected:
PlayerVelocityEvent firing when a player is pulled by a fishing rod.

### What behaviour is observed:
Whenever a player is pulled by a fishing rod the PlayerVelocityEvent doesn't fire.

### Plugin list:
A single plugin to test this issue.

### Paper build number:
Tested on 2 builds: 1.14.4 Build 195 and 1.13.2 Build 647

**Comment by Spottedleaf** [comment]
It looks to me like this is implemented client-side given the absence of velocity setting in the hook handling (server only sets the velocity of the entity pulled)

**Comment by 0-x-2-2** [comment]
Correct this is implemented/calculated client-side

**Comment by zachbr** [comment]
Closing as can't fix.
