### ISSUE TITLE
End chests sending packets containing coords of other players

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#258]
It is possible for players to grab a packet by having their end inventory opened up, and waiting for other players to open up an end chest, this apparently sends packets to all players with end chest open containing co-ordinates of players that opened end chests

I don't have much more information than this, not really experienced enough to test it out myself and the people that discovered this aren't willing to share

paper build 712

**Comment by aikar** [comment]
I can't see any reason this could happen. It's possible those players were just trolling you?

On open it calls the sound effect with a radius, I can't see any other packets to be sent.

**Comment by Black-Hole** [comment]
There is a PacketPlayOutBlockAction send to players within 64 radius, too.

**Comment by aikar** [comment]
yeah but thats not entire world. theres nothing we can really do about that.

if someones using it to find exact coords of people within 64 blocks of them, then youll need to find them cheating through other means and ban them.

**Comment by ghost** [comment]
> if someones using it to find exact coords of people within 64 blocks of them

Chances are, if somebody is within 64 blocks of somebody else, they can trace on them anyways.
