### ISSUE TITLE
TIMING_STACK_CORRUPTION - Exception generating new chunk

### ISSUE THREAD

**Issue by sannielollie** [PaperMC/Paper#2583]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

https://pastebin.com/3aPFSEb7

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
Plugins (104): 3DManeuverGear, AAC, AdvancedBan, AnimatedNames, ArcadeBoard, AutoCrafters, AutoSapling, Banknotes, BannerBoard, BentoBox, BierfietsMuziekspeler, BKCommonLib, BossShopPro, BungeeTabListPlus, ChatControl, ChopTree3, Citizens, ClearLag, CommandHook, ConditionalCommands, ConsoleSpamFix, CoreProtect, CorpseReborn, CrateReloaded, CrazyAuctions, CustomCommands, CustomPolls, DeathMessagesPrime, DiceFurniture, EditableSign, Elevator, EnjinMinecraftPlugin, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, Factions, FishyDispensers, FurnitureLib, GadgetsMenu, GAListener, GCore, GriefPrevention, GroupManager, HeadDatabase, HeadsInventory, HeadsPlugin, HideAndCustomPlugins, Holograms, HorseTpWithMe, iControlU, ID-Library, IllegalStack, JoinCommands, JsonMessageMaker, LWC, MassiveCore, mcMMO, MCSSCommunicator, MineableSpawners, MiniaturePets, Multiverse-Core, Multiverse-Inventories, MVdWPlaceholderAPI, MySQLWhitelist, NightVision, NoteBlockAPI, PacketListenerApi, Parties, PlayerPoints, PlayTimeRewardsRecoded, PlotSquared, PluginLibrary, PlugMan, PremiumVanish, ProtectionLib, ProtocolLib, Quests, React, RecipeBookDupePatch, RedstoneCommand, SantaClaus, SimpleBossBar, SimpleSit, Sinterklaas, SkinsRestorer, Sudo, Superpickaxe, TCHangRail, Trading, Train_Carts, UltraBar, Vault, ViaVersion, VoidGenerator, VoidSpawn, Votifier, VotingPlugin, WorldBorderPearlBlock, WorldEdit, WorldGuard, XRayHunter, CustomEnchantments, ElytraPlus

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Teleport to a older (1.9 or 1.12) generated world, then use /spawn or /warp or /tpa (doesnt matter what teleport command) to teleport back to the 1.14 world
The server then instantly crashes.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
[18:04:56 INFO]: This server is running Paper version git-Paper-192 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[18:04:56 INFO]: Checking version, please wait...
[18:04:56 INFO]: Previous version: git-Paper-176 (MC: 1.14.4)
[18:04:56 INFO]: You are 3 version(s) behind

**Comment by electronicboy** [comment]
```
Caused by: java.lang.UnsupportedOperationException: Custom generator is missing required method generateChunkData
    at org.bukkit.generator.ChunkGenerator.generateChunkData(ChunkGenerator.java:87) ~[patched_1.14.4.jar:git-Paper-192]
```
Your chunk-gen plugin doesn't work for 1.13+

**Comment by sannielollie** [comment]
> ```
> Caused by: java.lang.UnsupportedOperationException: Custom generator is missing required method generateChunkData
>     at org.bukkit.generator.ChunkGenerator.generateChunkData(ChunkGenerator.java:87) ~[patched_1.14.4.jar:git-Paper-192]
> ```
> 
> Your chunk-gen plugin doesn't work for 1.13+

The thing is - i am not using any chunk-gen plugin (as far as i know) except for VoidGenerator - when i remove that plugin the issues still occours.
