### ISSUE TITLE
Timing stack corruption

### ISSUE THREAD

**Issue by Muspah** [PaperMC/Paper#2589]
### Link/paste of stack trace
Server logfile: https://paste.md-5.net/ibofugeked.md
Generated crash report: https://paste.md-5.net/ohiwogiqip.rb

### Plugin list: 
Plugins (19): AnimatedNames*, ChestShop, CustomOreGen, dynmap*, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, LuckPerms, Multiverse-Core, Multiverse-NetherPortals, MVdWPlaceholderAPI*, Tab*, uSkyBlock, Vault, WorldBorder, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Unknown, the issue occurred after a user executed the /is level command from uSkyBlock, which fires a task that grabs ChunkSnapshot's to calculate the Skyblock island level. Running the task again after the server rebooted didn't trigger this issue again.

### Paper build number:
[11:47:52 INFO]: This server is running Paper version git-Paper-196 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[11:47:52 INFO]: Checking version, please wait...
[11:47:53 INFO]: Previous version: git-Paper-195 (MC: 1.14.4)
[11:47:53 INFO]: You are running the latest version

**Comment by Spottedleaf** [comment]
please update, should be resolved

**Comment by Muspah** [comment]
Thanks very much! 👍
