### ISSUE TITLE
Leash bug

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#259]
https://www.youtube.com/watch?v=v5N1JrHeKpI
git-Paper-706 (MC: 1.9.2)
Bukkit.yml: http://pastebin.com/j0BAWr6J
Spigot.yml: http://pastebin.com/Zxh3Rabe
Paper.yml: http://pastebin.com/vnKuQm5j

**Comment by andris155** [comment]
![2016-05-01_22 39 59](https://cloud.githubusercontent.com/assets/8324198/14944276/6b028694-0fee-11e6-8687-397a9adb6a28.png)
infinity leash :O

**Comment by Cat7373** [comment]
This seems to be a client display Bug
