### ISSUE TITLE
Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by LucidAPs** [PaperMC/Paper#2590]
### What behaviour is expected:
Everything is working but i shouldn't get the error messages.

### What behaviour is observed:
The console is spammed with this error message.

[19:10:13 ERROR]: Could not pass event InventoryClickEvent to VotingPlugin v5.20.1
java.lang.NullPointerException: null

### Steps/models to reproduce:
Use the Votifier / Voting Spigot Plugin

### Plugin list:
Votifier
VotingPlugin

### Paper build number:
#196

**Comment by ghost** [comment]
This is a plugin related problem and should be reported to the plugin author instead.

**Comment by zachbr** [comment]
You have provided no useful logs. The tiny piece you have provided mentions a plugin by name.
Provide more logs that show this is our issue and we'll re-open this ticket.
