### ISSUE TITLE
1.14.4 Crashing

### ISSUE THREAD

**Issue by iLemon** [PaperMC/Paper#2591]
### Link/paste of stack trace
https://gist.github.com/iLemon/f03ef35e9c00b5f6cb07f28ca239d0e0
    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
Can pm this if required
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
195

**Comment by iLemon** [comment]
The above happens when 
```  
async-chunks:
    enable: false
```

If I change it back to enabled
```
  async-chunks:
    enable: true
```
then the server freezes and kicks everyone: https://pastebin.com/dmrG9hQ9

**Comment by BillyGalbreath** [comment]
So... You changed a pretty core config option then issued a /reload and the server choked..

**Comment by iLemon** [comment]
> So... You changed a pretty core config option then issued a /reload and the server choked..

Where does it say I reloaded?

**Comment by BillyGalbreath** [comment]
Where does it say you restarted? Your reproduction steps are vague, at best.

**Comment by Spottedleaf** [comment]
I have a fix pending PR for the first issue, as for the second issue you need to give more logs

note for the people responding about reloading: it will not cause deadlock like this (it also wont have any effect, still not recommended though)

**Comment by AlfieC** [comment]
> > So... You changed a pretty core config option then issued a /reload and the server choked..
> 
> Where does it say I reloaded?

how would you have players to kick if you restarted?

**Comment by Spottedleaf** [comment]
The current fix you can use while waiting for the pr to be merged is to set async-chunks:true
