### ISSUE TITLE
Performance problem with Chunk provider tick

### ISSUE THREAD

**Issue by PWWP** [PaperMC/Paper#2592]
###  Timings or Profile link:
https://timings.aikar.co/?id=a4b29291523643749570414773f46ebf

### Description of issue:
I have a problem with settings optimization. In my opinion the main problem is chunk provider tick and entity ticking but I probably can't do anything about it. 
The server is in freebuild mode - lots of animals on plots, additional functions, automatic farms, npc, mines, professions etc.
I hope that the optimization problem lies somewhere in the paper server configuration.  Up to version 1.9 the server was able to handle 150-180 people without lags and now it is about 80-100 👎 

Dedicated server parameters:
Procesor - Intel  i7-4790K (4c/8t) 4/4.4GHz
RAM -32GB DDR3 1333MHz
240GB  SSD

### Plugin list:
In timings. 

### bukkit.yml, spigot.yml, paper.yml, server.properties
paper.yml - https://pastebin.com/DyD2xwXX
spigot.yml - https://pastebin.com/79N16WFW
bukkit.yml - https://pastebin.com/uiNRngm5
server.properties - https://pastebin.com/Nv12aFYj

### Paper build number:
 Paper version git-Paper-186 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Thank you in advance for all the tips on how I can fix it 👍

**Comment by zachbr** [comment]
>  Up to version 1.9 the server was able to handle 150-180 people without lags and now it is about 80-100

Comparing 1.14.4 with 1.9 is not going to go well. Such a wide ranging and vague issue as "doesn't perform as well as a 3 year old version of the game" is not a good fit for this tracker.
For general tips on optimizing 1.14.4 as best as you can, join the discord or post on the forums.
