### ISSUE TITLE
Flat bedrock generation at y=5

### ISSUE THREAD

**Issue by dege16** [PaperMC/Paper#2596]
Issue confirmed with build 192 and 196. Launching a new blank server with only the custom configuration being the seed in server.properties. World generates with a flat layer of bedrock at y=5. Changing the generator setting of flat-bedrock to true (it's initially false) only moves the flat layer to y=1;

**Comment by Spottedleaf** [comment]
confirmed

**Comment by zachbr** [comment]
Thanks for the report. Fixed in 199+
