### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Daejangnamu** [PaperMC/Paper#2597]
paper 199
Multiverse-Core 4.1.0 (last version)

/mv create    error

https://hastebin.com/vaxecanupi.md
log check it please

**Comment by Spottedleaf** [comment]
It is normal for the watchdog to inform you your server has stopped ticking for 10 seconds during world creation (given it's lengthy)

**Comment by Daejangnamu** [comment]
> It is normal for the watchdog to inform you your server has stopped ticking for 10 seconds during world creation (given it's lengthy)

thank you
