### ISSUE TITLE
AutoSave every millisecond

### ISSUE THREAD

**Issue by vmozharov** [PaperMC/Paper#2599]
Activated Debug, and there is always AutoSave.
Paper latest version. Minecraft 1.14.4.
The server without plugins, in configs changed nothing.
Tried to put in configs more an interval on AutoSave. Tried to put on 0 and -1, but nothing changed.

Screen logs:
![image](https://user-images.githubusercontent.com/49596638/65822677-f52ae180-e250-11e9-8b15-827e4268fe27.png)

**Comment by BillyGalbreath** [comment]
This is intended design. It's part of the incremental saves Paper does, which is a good thing. It's not actually a full autosave, just a partial one. Basically, it takes your full autosave that happens every 5 minutes and devides the work up into super small parts and spread it across that entire 5 minutes. This prevents the hicccup/lag you get when autosave saves everything all at once every 5 minutes. ;)

**Comment by Spottedleaf** [comment]
The only thing not intentional however is the logging, which will be fixed

**Comment by vmozharov** [comment]
> This is intended design. It's part of the incremental saves Paper does, which is a good thing. It's not actually a full autosave, just a partial one. Basically, it takes your full autosave that happens every 5 minutes and devides the work up into super small parts and spread it across that entire 5 minutes. This prevents the hicccup/lag you get when autosave saves everything all at once every 5 minutes. ;)

> The only thing not intentional however is the logging, which will be fixed

Thanks for answer!
