### ISSUE TITLE
Configurable enchantment list on enchantment table.

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2602]
Allow you to change the enchantment list to a specific item on the enchantment table.
**paper.yml** example:

```
enchantment-list:
  IRON_AXE:
    - EFFICIENCY;
    - SHARPNESS;
```
This will allow enchanting the iron axe only for these 2 enchantments.

**Comment by HexedHero** [comment]
This is more of a plugin thing

**Comment by electronicboy** [comment]
While this would 100% be a plugin thing, the concern is really around the API available for this, I'm not sure that there is any

**Comment by ghost** [comment]
Can't the `PrepareItemEnchantEvent` be used and then the `getOffers` method?

**Comment by ghost** [comment]
I tried to implement this, but it is difficult. More precisely, I would like to receive curses on the table of enchantment.

**Comment by ghost** [comment]
I decided to test that with the following code:
```java
@EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
public void onPrepareItemEnchant(PrepareItemEnchantEvent event) {
    int bookshelves = event.getEnchantmentBonus();
    if (bookshelves != 16) {
        return;
    }
    double random = Math.random() * 100.0D;
    if (random <= 80.0D) {
        System.out.println(event.getOffers()[2].getEnchantment().getKey().getKey());
        event.getOffers()[2] = new EnchantmentOffer(Enchantment.VANISHING_CURSE, 1, 3);
        System.out.println(event.getOffers()[2].getEnchantment().getKey().getKey());
    }
}
```
it makes that if the enchanting table has 16 bookshelves around it (a "full" enchanting table) there's an 80% chance that the last offer would have the curse of vanishing enchant. While setting the enchant works, the server doesn't seem to care about it and still applies his own enchants at the end. My guess is that it's either not working properly, or the API is just misleading (I haven't checked server's code yet).

Besides that, API seems to be a bit old since in vanilla each offer can contain more than 1 enchant.

https://i.imgur.com/T8Zlvgv.png
https://i.imgur.com/VwkNZ34.png

I also tested that with normally offerable enchants (like sharpness) and the issue persists.

As a side note:
If you just want to have the curse of vanishing enchant to be applicable (and don't care if it's visible in the enchanting table), try adding the enchant in the `EnchantItemEvent`.

**Comment by ghost** [comment]
It really requires a more extensive API for plugins.

**Comment by Machine-Maker** [comment]
As far as I can tell, the server doesn't pick the additional enchants until its clicked. So the offer really only can support a single enchant.

EDIT: This also should be possible using both the prepare and EnchantItemEvent to set the resulting enchantments.
