### ISSUE TITLE
Server crashes when mining with OP Pickaxe

### ISSUE THREAD

**Issue by namePlayer** [PaperMC/Paper#2603]
###  Timings or Profile link:
https://timings.aikar.co/?id=ab73b085030d404e81d531092c5b46cf

### Description of issue:
I have a user on my Server, who everytime mines with efficiency 5 luck 3 and Mending, but when he is mining, the Server starts to lag extremly with 5 - 10 TPS

### Plugin list:
AdvancedAntiXray*, AntiVPN, ChatManager, ChestShop, ClearLag, CommandItems, CoreProtect, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, GoldenCrates, HolographicDisplays, Jobs, JupiterCore, LuckPerms, Multiverse-Core, Plan, PlotSquared, PlugMan, Rankup, RedstoneClockPreventer2*, Skript, SpigotBoard*, TAB, Trading*, Vault, Votifier, VotingPlugin, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
paper.yml: https://hastebin.com/jihiribovo.coffeescript
server.properties: https://hastebin.com/asoyihurab.bash
spigot.yml : https://hastebin.com/honixasecu.rb
bukkit.yml : https://hastebin.com/vobuturire.coffeescript

### Other helpful links
- / -

### Paper build number:
This server is running Paper version git-Paper-199 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Previous version: git-Paper-195 (MC: 1.14.4)
You are running the latest version

**Comment by t895** [comment]
Why are you using AdvancedAntiXray when Paper has one built in already? Also, other people have reported that AdvancedAntiXray causes crashes when mining new blocks too quickly.
![image](https://user-images.githubusercontent.com/14132249/65834891-ad867300-e2ad-11e9-8ecd-eb090b001c6e.png)

**Comment by mikroskeem** [comment]
>Timings or Profile link

... how can you fuck up even so badly. You'll get that link using `/timings paste` command.

> bukkit.yml, spigot.yml, paper.yml, server.properties

Please use something more persistent, such as gist.github.com. After few days those pastes are gone and nobody's gonna figure out what configuration you had.

**Comment by namePlayer** [comment]
Hey @t895,
I have now disabled AdvancedAntiXray and i will test the Performance now for 1 - 3 days. Tahnks for the hint, that i can Disable.

Cheers.
