### ISSUE TITLE
Timing Stack Corruption

### ISSUE THREAD

**Issue by CookieMellow** [PaperMC/Paper#2604]
### Link/paste of stack trace
30.09 00:10:37 [Server] ERROR TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:spawn - syncChunkLoad} did not stopTiming)
30.09 00:10:37 [Server] INFO java.lang.Throwable: null
30.09 00:10:37 [Server] INFO 	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:96) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at co.aikar.timings.TimingHandler.close(TimingHandler.java:203) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.Chunk.unloadCallback(Chunk.java:659) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$null$4(PlayerChunk.java:295) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$a$5(PlayerChunk.java:289) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_211]
30.09 00:10:37 [Server] INFO 	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669) ~[?:1.8.0_211]
30.09 00:10:37 [Server] INFO 	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1997) ~[?:1.8.0_211]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.PlayerChunk.a(PlayerChunk.java:288) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.ChunkMapDistance.lambda$a$1(ChunkMapDistance.java:126) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_211]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:124) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:289) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:361) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[custom.jar:git-Paper-107]
30.09 00:10:37 [Server] INFO 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
   
### Plugin list:
Advanced Portals
Buycraft X
Clearlag
Coreprotect
Cratesplus
EpicRename
EpicSkyblock
EssentialsX
EssentialsXChat
EssentialsXSpawn
GUIPlus
Holograms
Litebans
LuckPerms-Bukkit
MineableSpawners
Multiverse Core
PlayerParticles
Skyblock Randomizers V1
TAB
UberEnchant
Vault
VoidGenerator
VotingPlugin
nuvotified
Worldedit
worldguard

### Paper build number:
1.14.2-R0.1-SNAPSHOT

**Comment by HexedHero** [comment]
`1.14.2-R0.1-SNAPSHOT`
