### ISSUE TITLE
Can't take ANY damage and Hostile Mobs ignore me

### ISSUE THREAD

**Issue by NoFace851** [PaperMC/Paper#2605]
### What behaviour is expected:
___To take damage and have hostile mobs attack me___

### What behaviour is observed:
___i take no damage from nothing, fall damage, drowning, lava etc, I don't take any damage and hostile mobs don't attack me, they just ignore me, even if i attack them___

### Steps/models to reproduce:
___I have no idea of what's causing this, when i delete the playerdata the problem is solved, but i can't keep doing this everytime this happens, this happened in the past and is happening now, i don't know if it's paper's fault but i removed ALL of my plugins and the problem persists___

### Plugin list:
___Plugins used BEFORE i removed all of them (this issue persisted): Plugins (68): AdvancedBan*, AutoMessager, Autorank, ChatControl, ChestShop, ClaimFly, ClearLag, ColoredSigns*, CommandSigns, ConditionalCommands*, CubeShopPlugin*, DeathMessagesPrime, DragonSlayer, DragonTimer, EditableSign, EntityDetection, EpicFurnaces, Essentials, GetSpawners, GriefPrevention, Guilds, HackedCore*, HackedServer*, HolographicDisplays, HolographicDisplaysExtension, IllegalStack, IPWhitelist*, JukeBox, LimitPillagers, LuckPerms, mcMMO, Minepacks, MobHeads, Multiverse-Core, MVdWPlaceholderAPI*, NoteBlockAPI, OldCombatMechanics, OreAnnouncer, PegasusRaio*, PixelVip*, PlaceholderAPI, PlayerParticles, PlotSquared, PluginLibrary*, PlugMan, ProtocolLib, PunishmentGUI*, PvPToggle, Quests, SAML, SecurityVillagers, SetTheSpawn, SkinsRestorer, Spartan, Statz, TAB, UltimateChat, UltimateModeration, UltimateRepairing, UltimateStacker, Vault, VoidGenerator, WorldBorder, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardExtraFlags, XPBoost*___

### Paper build number:
___This server is running Paper version git-Paper-207 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
>.... [17:54:08 INFO]: Checking version, please wait...
>.... [17:54:08 INFO]: Previous version: git-Paper-201 (MC: 1.14.4)
>.... [17:54:08 INFO]: You are running the latest version.___

### Anything else:
___I don't know, maybe it's a plugin's fault but i removed all of them and this persisted, ONLY fixed when i delete the playerdata from the world :/ ___

**Comment by zachbr** [comment]
Yes, depending on what the plugins are doing their effects can persist even after removal. We’d need to see the affected player data to say.

**Comment by NoFace851** [comment]
here:

https://www.mediafire.com/file/6anri996krx4ue9/e5c14073-415e-30de-b56a-5b4cfc372047.dat/file

this player data

**Comment by electronicboy** [comment]
That player data file has the invulnerable flag set on it, you'll need to disable that (somehow), no specific recommendation there

**Comment by NoFace851** [comment]
what? How can i disable this, what plugin could be activating this flag? please help :/

i downloaded NBT editor and set Invunerable from 1 to 0. It fixed it, but how could a plugin be changing this automaticaly? If you know please tell me

**Comment by electronicboy** [comment]
Invulnerablity is something that plugins can set with the API for things like god mode, etc; I couldn't tell you what plugin is doing it, that's your job as a server owner is to know what your plugins are doing; As for fixing it, you'll need a plugin or something to mark the players as not being invulnerable;

**Comment by aaronorsette** [comment]
For anybody who had this issue like I did and OP did it is caused when you install LuckPerms without Essentials Protect (at least in my case) I fixed it by installing the "optional" Essentials Protect addition to EssenetialsX you can get that here as of time of comment:

in the EssentialsX config under there are settings for specifically Essentials Protect and the default should be good but you want them set to false like this:
`############################################################
# +------------------------------------------------------+ #
# |                 EssentialsX Protect                  | #
# +------------------------------------------------------+ #
############################################################

# You need to install EssentialsX Protect for this section to work.
# See https://essentialsx.net/wiki/Module-Breakdown.html for more information.

protect:

  # General physics/behavior modifications. Set these to true to disable behaviours.
  prevent:
    lava-flow: false
    water-flow: false
    water-bucket-flow: false
    fire-spread: true
    lava-fire-spread: true
    lava-itemdamage: false
    flint-fire: false
    lightning-fire-spread: true
    portal-creation: false
    tnt-explosion: false
    tnt-playerdamage: false
    tnt-itemdamage: false
    tnt-minecart-explosion: false
    tnt-minecart-playerdamage: false
    tnt-minecart-itemdamage: false
    fireball-explosion: false
    fireball-fire: false
    fireball-playerdamage: false
    fireball-itemdamage: false
    witherskull-explosion: false
    witherskull-playerdamage: false
    witherskull-itemdamage: false
    wither-spawnexplosion: false
    wither-blockreplace: false
    creeper-explosion: false
    creeper-playerdamage: false
    creeper-itemdamage: false
    creeper-blockdamage: false
    ender-crystal-explosion: false
    enderdragon-blockdamage: true
    enderman-pickup: false
    villager-death: false
    bed-explosion: false
    respawn-anchor-explosion: false
    # Monsters won't follow players.
    # permission essentials.protect.entitytarget.bypass disables this.
    entitytarget: false
    # Prevents zombies from breaking down doors
    zombie-door-break: false
    # Prevents Ravagers from stealing blocks
    ravager-thief: false
    # Prevents sheep from turning grass to dirt
    sheep-eat-grass: false
    # Prevent certain transformations.
    transformation:
      # Prevent creepers becoming charged when struck by lightning.
      charged-creeper: false
      # Prevent villagers becoming zombie villagers.
      zombie-villager: false
      # Prevent zombie villagers being cured.
      villager: false
      # Prevent villagers becoming witches when struck by lightning.
      witch: false
      # Prevent pigs becoming zombie pigmen when struck by lightning.
      zombie-pigman: false
      # Prevent zombies turning into drowneds, and husks turning into zombies.
      drowned: false
      # Prevent mooshrooms changing colour when struck by lightning.
      mooshroom: false
    # Prevent the spawning of creatures. If a creature is missing, you can add it following the format below.
    spawn:
      creeper: false
      skeleton: false
      spider: false
      giant: false
      zombie: false
      slime: false
      ghast: false
      pig_zombie: false
      enderman: false
      cave_spider: false
      silverfish: false
      blaze: false
      magma_cube: false
      ender_dragon: false
      pig: false
      sheep: false
      cow: false
      chicken: false
      squid: false
      wolf: false
      mushroom_cow: false
      snowman: false
      ocelot: false
      iron_golem: false
      villager: false
      wither: false
      bat: false
      witch: false
      horse: false
      phantom: false
`

**Comment by Olfi01** [comment]
> For anybody who had this issue like I did and OP did it is caused when you install LuckPerms without Essentials Protect (at least in my case) I fixed it by installing the "optional" Essentials Protect addition to EssenetialsX you can get that here as of time of comment: https://essentialsx.net/downloads.html
> 
> in the EssentialsX config under there are settings for specifically Essentials Protect and the default should be good but you want them set to false like this: https://imgur.com/a/cdyd3eL

But why the HELL does LuckPerms just make players randomly invulnerable?

**Comment by powercasgamer** [comment]
> But why the HELL does LuckPerms just make players randomly invulnerable?

It doesn't.

**Comment by Olfi01** [comment]
> > But why the HELL does LuckPerms just make players randomly invulnerable?
> 
> It doesn't.

Well, then how did the same thing just happen on my server? Me and a friend both suddenly stopped taking damage (or mob aggro, or anything) and lo and behold, we do indeed have invulnerable set to true all of a sudden. There also aren't that many plugins on our server, but LuckPerms is one of them.

**Comment by powercasgamer** [comment]
> > > But why the HELL does LuckPerms just make players randomly invulnerable?
> > 
> > 
> > It doesn't.
> 
> Well, then how did the same thing just happen on my server? Me and a friend both suddenly stopped taking damage (or mob aggro, or anything) and lo and behold, we do indeed have invulnerable set to true all of a sudden. There also aren't that many plugins on our server, but LuckPerms is one of them.

Instead of commenting on a year old closed issue. Join [our discord](https://discord.gg/papermc) and ask for support in the #paper-help channel. I can assure you it's not LuckPerms causing it.

**Comment by Olfi01** [comment]
You're right, sorry, I jumped to the conclusion. The problem was another plugin (AutoAFK). Thank you!
