### ISSUE TITLE
Pillager spawns limit.

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2606]
Make a pillager spawns limit like in bukkit.yml for performance.

**Comment by electronicboy** [comment]
Pillagers are not bound by the same system, there are plugins which deal with this issue without us breaking (albeit stupid) vanilla mechanics

**Comment by niqofdez** [comment]
https://www.spigotmc.org/resources/limitpillagers-fix-outpost-spawns-and-more.69733/

**Comment by ghost** [comment]
Maybe it’s worth adding a setting that disables constant spawn at Outposts or even at some specific structures?
