### ISSUE TITLE
0 tick farms

### ISSUE THREAD

**Issue by ardentcrest** [PaperMC/Paper#2610]
### What behaviour is expected:
Working 0 tick farms.

### What behaviour is observed:
None working 0 tick farms

### Steps/models to reproduce:
Using ilmangos bamboo 0 tick farm with iskill85's super smelter the bamboo is not growing at 0 tick speed  

### Paper build number:
This server is running Paper version git-Paper-207 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by Puremin0rez** [comment]
Change "fix-zero-tick-instant-grow-farms" in "paper.yml" to "false".
