### ISSUE TITLE
Async world generation bugs out for Plugins 

### ISSUE THREAD

**Issue by Articdive** [PaperMC/Paper#2611]
### Link/paste of stack trace
--- pastebin link deleted ---

### Plugin list:
WorldEdit
My own Custom Generator using 3 Populators for (dead trees, rocks and ore gen) and a custom noise library for the actual world gen,that I created.
Code for the populator after which the errors appeared: (ore generation)
Though I can't be sure that it is the main culprit for it, it is the firelighter
--- pastebin link deleted ---

### Actions to reproduce (if known):
Honestly starting the server causes a long stack-trace and something then blocks the thread, probably some async going haywire.

### Paper build number:
Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Told me to ping you if it's still consistent
@Spottedleaf

**Comment by electronicboy** [comment]
Your block populator is loading neighbouring chunks due to the propagated
block updates, you need to set blocks without updating physics/avoid
accessing unloaded chunks in general

**Comment by Articdive** [comment]
ah okay using setType(Material, false) seems to have fixed the problems thank you 
@electronicboy
