### ISSUE TITLE
Per EntityType entity-tracking-range

### ISSUE THREAD

**Issue by LoneDev6** [PaperMC/Paper#2616]
**Is your feature request related to a problem? Please describe.**
Ender Dragon invisible in the distance

**Describe the solution you'd like**
Would be cool to have an Ender Dragon specific setting in paper.yml to set entity-tracking-range of this entity

**Describe alternatives you've considered**
Would be nice to add this setting and allow users to chose which EntityType can have custom 
entity-tracking-range

**Comment by kickash32** [comment]
Having the dragon exempt from the tracking range seems like a simpler solution. How about that instead?

**Comment by LoneDev6** [comment]
Is there an option on paper config? Or needs to be implemented?

I would prefer a setting to be able to set different distances for each entity type.
Or maybe better an API to set that with plugins, so I can for example show some holograms (based on metadata or display name) only when you're near it and not in the distance.

**Comment by JLyne** [comment]
For the dragon issue specifically, you could perhaps increase the tracking range for just the end, by using per-world settings. Not a whole lot of entities in the end normally, so could work until something else is implemented.
