### ISSUE TITLE
Chickens don't suffocate

### ISSUE THREAD

**Issue by lukemagdalin** [PaperMC/Paper#2620]
### What behavior is expected:
I expect suffocating chickens when spawned in between slab and a block.

### What behavior is observed:
Chickens are immune to THE WALL

### Steps/models to reproduce:
Place a slab on the ground with a block on top (like stone, glass won't work) having a small space in between, and place a dispenser pointing into the death machine, then enclose the rest of the sides (preferably glass you can see) so it summons chickens in that slab space. put chicken spawn egg in the dispenser and power it. The chicken should be in the area and with a black texture but not actually suffocating.

### Plugin list:
DiscordSRV, HyperLinks*, skQuery, skript, WorldEdit, WorldGuard
### Paper build number:
Paper version git-Paper-3398704d (MC: 1.14.4) (Implementing API version 1.14.4-70.1-SNAPSHOT)

### Anything else:
WorldGuard and WorldEdit aren't affecting the area that I tested this in.
This setup works in a local world as I made sure this was a bug.

**Comment by kickash32** [comment]
So this does not occur in single player (vanilla)...?  What about spigot?

**Comment by ghost** [comment]
Just tested that on 1.14.4 and chickens:
- suffocated on Vanilla,
- suffocated on clean Spigot server,
- suffocated on clean Paper server.

All in all, I could not reproduce your issue.

**Comment by ghost** [comment]
Also, 

> The chicken should be in the area and with a black texture but not actually suffocating.

this entirely differs from what you wanted to achieve:

> I expect suffocating chickens when spawned in between slab and a block.

When I was testing this, chickens were being spawned on the slab, indeed were having a black texture, and were suffocating, but that is exactly what you wanted to achieve in the first place.

**Comment by lukemagdalin** [comment]
sorry I replied so late I have been busy,
but what I was trying to do was to kill chickens by suffocating them with just a slab space. When I did this I did get a black texture but the chicken didn't die. I did try this in a vinnilla server and the chicken did die. although now that I check my server version is behind now. I am gonna update it and see if the problem continues.

**Comment by lukemagdalin** [comment]
So as it turns out, I have been testing my setup with a new server. Chickens do suffocate with the latest server and plugins. I suspect its probably something went wrong when I updated the server, so I am just gonna backup the old world and regenerate the rest of the server. Anyways thanks for your help on my endless journey of errors.
