### ISSUE TITLE
very low tps with datapacks

### ISSUE THREAD

**Issue by DraTrav** [PaperMC/Paper#2622]
### What behaviour is expected:
datapacks to function without tps dropping

### What behaviour is observed:
the tps drops down to 3 and somtimes goes lower

### Steps/models to reproduce:
download a datapack some examples are
https://www.planetminecraft.com/mod/ben-10-reboot-data-pack/
https://www.curseforge.com/minecraft/customization/furniture-datapack

### Plugin list:
none

### Paper build number:
latest and pre versions too
paper 190 -209 have been tested
### Anything else:
this problems only occurs with paper spigot but when im on normal spigot the tps stays stable at 20

**Comment by HexedHero** [comment]
Just vanilla minecraft, not a paper issue. We might be able to improve it but its defo not on top prio

**Comment by CHATALOT1** [comment]
Would be good to see this one solved, present in my server too. (using [VanillaTweaks](vanillatweaks.net/) datapacks)

**Comment by MiniDigger** [comment]
timings? profiler report?

In generally, datapacks are bad for performance

**Comment by CHATALOT1** [comment]
> 
> 
> timings? profiler report?
> 
> In generally, datapacks are bad for performance

Honestly not sure what a profiler report is but i looked in the timings and it just refers to main:tick which doesn't really tell me much as the main namespace is used by virtually every datapack in VanillaTweaks. It doesn't seem to display any functions called by other functions. I don't know where you get the notion that "datapacks are bad for performance" as I've never heard that before nor seen any evidence of it (unless of course you are doing something like spawning loads of entities or what have you).

Nevertheless, here is my timings report: https://timings.aikar.co/?id=296e9614d36c470185c020e917643088

**Comment by MiniDigger** [comment]
"I don't know where you get the notion that "datapacks are bad for performance""
everything a datapack can do, a plugin can do with better performance, as it avoids the whole "lets execute countless commands" thing.

>  -Xmx28G -Xms25G

pls, for the love of god, never run a server with such obsecene amount of ram. especially not if you didnt tune the garbage collector. take a look at https://mcflags.emc.gs/

in generall, it looks like your specific case just suffers from too many entites, be sure to give this a read https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/

**Comment by CHATALOT1** [comment]
I've gotten support from the official paper discord server now, thanks for your effort nonetheless.

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/commit/e4602b6d4808090149c6d5d7567134c308f05e11
