### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by nestormaldonado** [PaperMC/Paper#2623]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
https://gyazo.com/7cd33f0d2203418ad38d903f3e56b4b8
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-1618

**Comment by electronicboy** [comment]
You're missing any form of information on the crash, 1.12.2 is also no longer supported
