### ISSUE TITLE
stopTiming called async for world - chunkLoad - TileEntities

### ISSUE THREAD

**Issue by NoDi522** [PaperMC/Paper#263]
This error is spamming my console and it causes lag

**Minecraft log error:** http://pastebin.com/d21LR6kL
**Plugin list:** http://prnt.sc/azb94a

**Version:** git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Black-Hole** [comment]
Blame ObsidianBreaker
