### ISSUE TITLE
[Vanilla bug] Pillagers spawning in trees. Can Paper patch this?

### ISSUE THREAD

**Issue by christofin** [PaperMC/Paper#2630]
### What behaviour is expected:
Pillagers should not be spawning on solid blocks when covered by leaves. 

### What behaviour is observed:
Just pillagers will ignore when a block is covered by a leaf block, and will effectively spawn in trees, as well as other blocks that are covered by leaves. 

### Steps/models to reproduce:
Play the game long enough and wait. Living in a jungle helps. 

### Plugin list:
Not relevant -- this is a vanilla bug. 

### Paper build number:
Paper-210

### Anything else:
This isn't a Paper issue, but as Paper has been known to patch some vanilla bugs before, I'm hoping this one might get looked at! Here's the vanilla bug report:

https://bugs.mojang.com/browse/MC-163308

This is a bug in vanilla; running a search on the Minecraft reddit for "pillager tree" shows that a lot of other people are having this issue. I was able to reproduce in single player, too.

https://www.reddit.com/r/Minecraft/search?q=pillager+tree&restrict_sr=on

**Comment by kickash32** [comment]
This is marked as fixed in 1.15

**Comment by Chew** [comment]
Thanks to slicedlime, this has been fixed upstream and as a result should be fixed on Paper. If for whatever reason this still occurs on the latest version, don't hesitate to open a new issue. Have a good day!
