### ISSUE TITLE
Make the fix for zero tick farms an optional thing please.

### ISSUE THREAD

**Issue by Evident-Dev** [PaperMC/Paper#2634]
**Is your feature request related to a problem? Please describe.**
In reference to the fix you made in https://github.com/PaperMC/Paper/issues/2558. I would kindly ask that you please make this a configurable fix for servers that want to use zero tick farms or those who don't. 

**Describe the solution you'd like**
My server has been using them for ages, and when we updated they are now broken. We are hoping you would be kind enough to add the fix you implemented as an option fix we can turn on and off in the paper configuration. 

**Describe alternatives you've considered**
Removing the fix all together is also an option since zero tick farms are actually quite lag friendly, and still exist in the vanilla game.

**Additional context**
Like I said, it just seems like something that should be optional, and we are hoping to continue to use paper as a Semi-Vanilla Minecraft server. Zero tick farms are a must as we pump out some crazy projects and it is a major set back for us now. Non Zero tick farms produce so much lag comparatively. And honestly once vanilla does fix it, if it's something you leave in the loader as an option it will possibly even draw servers to use paper that much more. Appreciate your consideration for this feature request.

**Comment by SlickJava** [comment]
It is an option, set `fix-zero-tick-instant-grow-farms: true` to `false` in paper.yml

**Comment by Evident-Dev** [comment]
Oh! I missed this completely! Thanks!
