### ISSUE TITLE
Asynchronous chunk loading causes server lag and chunks taking a long time to load

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2635]

**Comment by breadbyte** [comment]
Your timings cost is at ``1961``, indicating a really overloaded/slow server.
Common acceptable values for these should be at around the 100-200 range.
Considering you're also running on an ARM system, i theorize that your hardware is simply too slow to run minecraft.

Even if you disregard that information, if you look at your timings report, Essentials is taking up most of your time. 
Even an op/deop command is taking too much time to execute.
This happens alongside world saving using save-all in your timings report. I suggest removing whatever auto-save functionality you have implemented, in exchange for paper's incremental world saving.

SkinsRestorer is also taking a bit of time to run it's task.

These kinds of performance questions are best suited for discussion at the paper discord/irc channels.

**Comment by PhoenixDiscord** [comment]
@breadbyte I tried to get help on this on Discord but didn't got any response.

Tomorrow I will remove SkinsRestorer & Essentials and will see if anything improves.

**Comment by PhoenixDiscord** [comment]
Also, what is the incremental world saving?

**Comment by breadbyte** [comment]
Incremental world saving spreads saving over several ticks instead of saving the entire world all in one go.
Paper incrementally saves by default, you just need to turn off your own autosave system.

**Comment by PhoenixDiscord** [comment]
Okay, thanks. I'm actually moving to a dedicated desktop PC in a few months/weeks so I'll see if I have any problems once I do it.

Closing this for now.

**Comment by electronicboy** [comment]
Missed this one, async chunk loading is great, but it's only ever going to be as great as your hardware; Super low memory environments or environments where there is already a strain on CPU resources or communication between threads are generally going to struggle to keep up with the load much harsher, disabling async chunk loading in these environments is recommended given these constraints
