### ISSUE TITLE
Server crash on startup.

### ISSUE THREAD

**Issue by FrostDelta123** [PaperMC/Paper#2637]
https://gist.github.com/FrostDelta123/3dd8ee3da896546efc931af60376e910

In this crash-report we can saw this line

`at com.minelazz.epicworldgenerator.nativeAPI.implementations.v1_14_R1.generator.NativeEpicChunkProvider2.createStructures(lca:163)`

This is the signs of using EpicWorldGenerator, but it is NOT cause of this crash. I tried to remove it and paper still crashing and now AsyncWorldEdit cause... but if EWG or AWE will be without other plugins it works. IDK what should i do.

**Comment by ShayPunter** [comment]
Hello @FrostDelta123,

Have you reported this to the author of EWG? Also, ensure you are updated to the latest version of PaperSpigot & also try Spigot to see if the same error is happening there.

**Comment by Spottedleaf** [comment]
EWG did not enable properly from the looks of the log.

Should also provide the logs where AsyncWorldEdit crashes.

**Comment by FrostDelta123** [comment]
I tried delete EWG and AWE and still not working. After deleting i generate new world, but still not working, oh

**Comment by electronicboy** [comment]
We'd need the full log file to see what is going on

**Comment by Chew** [comment]
Issue Author hasn't responded in more than 3 months. If you are still experiencing this issue on the latest version, don't hesitate to make a new issue. Have a good day!
