### ISSUE TITLE
Water not behaving properly

### ISSUE THREAD

**Issue by NoFace851** [PaperMC/Paper#2638]
### What behaviour is expected:
___I expected the water to behave properly___

### What behaviour is observed:
___Water doesn't go to other blocks as seen here: https://imgur.com/a/14ZF8rl___

### Steps/models to reproduce:
___It happens randomly, this happened to a mobtrap that was working before, but suddenly this problem started___

### Plugin list:
___AdvancedBan*, AutoMessager, Autorank, BigornaNerf*, ChatControl, ChestShop, ClaimFly, ClearLag, ColoredSigns*, CommandSigns, ConditionalCommands*, CubeShopPlugin*, DeathMessagesPrime, DragonSlayer, DragonTimer, EditableSign, EnchantControl, EntityDetection, EntityTrackerFixer, Essentials, GetSpawners, GriefPrevention, Guilds, HackedCore*, HackedServer*, HolographicDisplays, HolographicDisplaysExtension, IllegalStack, IPWhitelist*, JukeBox, LimitPillagers, LuckPerms, mcMMO, Minepacks, MobHeads, Multiverse-Core, MVdWPlaceholderAPI*, NoteBlockAPI, OldCombatMechanics, OreAnnouncer, PegasusRaio*, PixelVip*, PlaceholderAPI, PlayerParticles, PlotSquared, PluginLibrary*, PlugMan, ProtocolLib, PunishmentGUI*, PvPToggle, Quests, SAML, SecurityVillagers, SetTheSpawn, SkinsRestorer, Spartan, Statz, TAB, UltimateChat, UltimateModeration, UltimateRepairing, UltimateStacker, Vault, VoidGenerator, WorldBorder, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardExtraFlags, XPBoost*___

### Paper build number:
__This server is running Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
>.... [16:12:14 INFO]: Previous version: git-Paper-207 (MC: 1.14.4)
>.... [16:12:14 INFO]: You are 5 version(s) behind.___

### Anything else:
___The first time this happened was in a border between chunks, but the second wasn't___

**Comment by BillyGalbreath** [comment]
Grief prevention doesn't let liquids flow passed a claim border. Check for any claims.

**Comment by HexedHero** [comment]
Yea, can confirm its GP. Had this issue a few times with players.

**Comment by NoFace851** [comment]
the problem is: It was working before and it's full claimed, not on any claim borders :/

**Comment by NoFace851** [comment]
any other ideas?

**Comment by Prof-Bloodstone** [comment]
Was having very similar issue the other day on our server and we don't have any sort of land claims or anything.

I've tried placing water manually. I've tried placing blocks nearby, hoping to send a block update. I've tried filling the whole area with commands and then removing the blocks - but it didn't fix anything. We tried restart. We tried rollback with CoreProtect. Nothing.

A solution was to pour water from up higher, where it's original source was. I have no idea why it worked or how it worked, but it did work.

Was sure it was a one-time issue with our server, but maybe it's something broken?

Before and after screenshots:
https://ibb.co/MRpK0GT
https://ibb.co/pZ4q4hL

EDIT: For reference some server info:
Plugins (15): BuycraftX*, CapAFK*, CoreProtect, DeathLog, DiscordSRV, dynmap*, FirstJoinMessage*, isSlimeChunk*, LuckPerms, OnePlayerSleep, player-dimension-lister*, ServerRestartWithCountdown*, Vault, VaultChatFormatter*, WorldBorder

[Tue, 15. Oct 2019 19:11:51 GMT INFO] This server is running Paper version git-Paper-213 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[Tue, 15. Oct 2019 19:11:51 GMT INFO] Previous version: git-Paper-210 (MC: 1.14.4)
[Tue, 15. Oct 2019 19:11:51 GMT INFO] You are 1 version(s) behind

**Comment by NoFace851** [comment]
sadly, the problem is in a mobtrap, there's no way of changing it so the water comes from above, gonna  wait and see if someone has a fix :/

**Comment by limwa** [comment]
Actually, there is. It all depends on how you design your mob trap. Anyhow, this issue should be further investigated by server owners, imo, as, right now, the developers of the papermc team have no way of reproducing this reliably...

**Comment by limwa** [comment]
And it seems that the only plugins that you too have in common are Vault and WorldBorder

Edit: can you please provide the coordinates of the spot where that thing happened and your world border size please?

**Comment by NoFace851** [comment]
the easiest fix is to move all you need with worldedit. I think the problems are with chunks, maybe worldborder bug? idk

**Comment by limwa** [comment]
Try setting your world border shape to square

**Comment by NoFace851** [comment]
It's already a square

**Comment by Prof-Bloodstone** [comment]
Actually we have worldborder disabled for now, because of a spigot bug that makes it unusable.

Afair Vault is just an API translation, so it shouldn't mess with anything.

I'll check if I still have a backup from when it happened - if a full stop/start cycle didn't fix it, there's a good chance there's some trace in the region files.
