### ISSUE TITLE
[Maven] Modules "Paper-Server" and "Paper-API" not found

### ISSUE THREAD

**Issue by QuaternionsRock** [PaperMC/Paper#2640]
### What behaviour is expected:
I simply tried cloning the repository and running `mvn clean install`, as one would do for Spigot.

### What behaviour is observed:
`[ERROR] Some problems were encountered while processing the POMs:
Child module C:\Users\quaternionsrock\IdeaProjects\Paper\Paper-Server of C:\Users\quaternionsrock\IdeaProjects\Paper\pom.xml does not exist @ 
Child module C:\Users\quaternionsrock\IdeaProjects\Paper\Paper-API of C:\Users\quaternionsrock\IdeaProjects\Paper\pom.xml does not exist @ `

**Comment by electronicboy** [comment]
Read the readme

**Comment by QuaternionsRock** [comment]
I did, although this warning seemed decidedly more important:

`<!-- Avoid making changes to this file, it has to be deployed manually -->`

I'm confused as to why this repo/artifact isn't in the POM file by default?

**Comment by electronicboy** [comment]
Because we can't ship mojang source files, the same as spigot, so the build process is needed to deal with pulling in the decompiled source from the vanilla server; -api is deployed in maven, -server contains mojang code so we cannot deploy it

**Comment by QuaternionsRock** [comment]
I am still unsure as to how exactly I can look through the (patched) source code like you can with MCP. Is there anyway to accomplish this?

**Comment by electronicboy** [comment]
Yes, `./paper patch` (or `./paper jar`), as per the readme

**Comment by QuaternionsRock** [comment]
Are you perhaps referring to a different readme than the README.md in this repo? `./paper patch` isn't mentioned anywhere (although `jar` is)

**Comment by mikroskeem** [comment]
CONTRIBUTING.md has more details about the build process
