### ISSUE TITLE
Skulls can make chunk packet too large too

### ISSUE THREAD

**Issue by Shevchik** [PaperMC/Paper#2642]
Skulls do contain profile property which can be large, placing too much skulls will result in chunk packet too large error.

Paper does have a patch to fix that with signs, probably same thing should be done with skulls.

**Comment by monoclex** [comment]
Bump - Recently just ran into a similar issue with this. Can this be fixed? In the meantime it'd be really nice to have MAX_PACKET_SIZE be configurable, as a temporary:tm: workaround.

**Comment by MrEDok** [comment]
i think the fix is this one https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0337-Handle-Oversized-Tile-Entities-in-chunks.patch

this one fix "patch" oversize chunk/chunk ban

**Comment by aikar** [comment]
we're missing some improvements by Leaf on that patch, just one of those 'keep forgetting' things to pull from him.
