### ISSUE TITLE
Repeater Doesn't Forward Signal To Next Repeater

### ISSUE THREAD

**Issue by zapdos26** [PaperMC/Paper#2643]
### What behaviour is expected:
The repeater should continue on and light up the next repeater, passing along the signal.

### What behaviour is observed:
The next repeater does not light up or pass along the signal.

### Steps/models to reproduce:
This appears to be random. Sometimes it fixes itself without issue. Here is a video in action of reproducing it, along with additional information: https://www.youtube.com/watch?v=Uea_WA9PNP8

### Plugin list:
ArmorStandEditor, ControlMobNoises, CoordinatesHud, CoreProtect, DropHeads, InventoryRollback, LimitPillagers, LOTM-ForceGameMode*, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, Multiverse-SignPortals, MyCommand, OpenInv*, PlugMan*, RaidBlocker, SafeSpectate*, SAML, Vault, VaultChatFormatter*, World_Time_Synchronizer, WorldBorder, WorldEdit

### Paper build number:
 This server is running Paper version git-Paper-207 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Anything else:
 use-faster-eigencraft-redstone: true
I know we are a few versions behind, but I did not see a change where redstone would be affected in this behavior.

**Comment by zapdos26** [comment]
We have updated to the latest version, and this is still an issue. Any help would be appreciated.

**Comment by RodneyMKay** [comment]
Have you tried disabling WorldBorder, WorldEdit, Multiverse-Portals and Multiverse-SignPortals for a short period of time to test if the issue persists?

**Comment by LogGits** [comment]
Can confirm this issue was not present on version 196, after updating to 225 i receive many reports of this occurring.

I wont be able to test as of right now but based on the information that you provided the issue could have been introduced from 197 to 207 (though i could be wrong entirely).

EDIT: I am also using `use-faster-eigencraft-redstone: true`
EDIT 2: player alerted me that it was happening while we were on 196 so my timeline is irrelevant.

**Comment by kickash32** [comment]
Does this still happen on the latest 1.15 builds? Does this get fixed if eigencraft-redstone is false?

**Comment by BillyGalbreath** [comment]
Unable to reproduce this on 1.16.2 (with and without Proxi's PR bringing back eigencraft redstone)

https://youtu.be/3pFt-LhQSz4

**Comment by broken1arrow** [comment]
> 
> 
> Unable to reproduce this on 1.16.2 (with and without Proxi's PR bringing back eigencraft redstone)
> 
> https://youtu.be/3pFt-LhQSz4

Have try load and reload the chunk (and dont do the test in spawn) :)

**Comment by BillyGalbreath** [comment]
> Have try load and reload the chunk (and dont do the test in spawn) :)

If loading and unloading chunks is a requirement to trigger this, then I believe you are witnessing this vanilla bug https://bugs.mojang.com/browse/MC-147818

**Comment by broken1arrow** [comment]
> 
> 
> > Have try load and reload the chunk (and dont do the test in spawn) :)
> 
> If loading and unloading chunks is a requirement to trigger this, then I believe you are witnessing this vanilla bug https://bugs.mojang.com/browse/MC-147818

I guess even TS some start this, is a vanilla issue he expiring.

But you get (at least before, in 1.15), more frequent get problems if you use eigencraft redstone (soo i Think this amplifier the problems). Specially if paper team say they cant fix eigencraft redstone´s bugs (even 1.15 changes behavior on redstone, so if it eigencraft has stay the same for years no wonder you at last get problems).
