### ISSUE TITLE
Reporting error while respawning the end dragon

### ISSUE THREAD

**Issue by eternitymoe** [PaperMC/Paper#2644]
Paper Version git-Paper-218 (MC: 1.14.4)

While players respawning the dragon, server will report error on console after i update to the Build 218.

<img width="993" alt="Screenshot 2019-10-19 at 15 31 01" src="https://user-images.githubusercontent.com/44344308/67140301-d76afe00-f28b-11e9-8c48-7bb42fa4c5b5.png">

**Comment by eternitymoe** [comment]
This ERROR will also shown on Paper-219
Tested with a NO PLUGIN server
<img width="983" alt="Screenshot 2019-10-19 at 23 24 56" src="https://user-images.githubusercontent.com/44344308/67147500-0bfcab00-f2c8-11e9-8e22-58a09aef058b.png">
<img width="725" alt="Screenshot 2019-10-19 at 23 28 23" src="https://user-images.githubusercontent.com/44344308/67147514-26368900-f2c8-11e9-8707-fc4ea78033b2.png">

**Comment by electronicboy** [comment]
https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-5367
