### ISSUE TITLE
Possible world corruption on public server?

### ISSUE THREAD

**Issue by Weasel-Beans** [PaperMC/Paper#2648]
While rendering Dynmap I'm seeing plenty of errors showing up every now and again like this:

>.... [06:19:09 ERROR]: Block at 1,292,178,2,063 is Block{minecraft:water} but has net.minecraft.server.v1_14_R1.TileEntitySkull@13241c99. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
>.... [06:19:09 ERROR]: Don't know how to fix for this type... Can't do anything! :(

>.... [06:19:10 ERROR]: Block at 1,293,177,2,062 is Block{minecraft:water} but has net.minecraft.server.v1_14_R1.TileEntitySkull@4de4d59a. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
>.... [06:19:10 ERROR]: Don't know how to fix for this type... Can't do anything! :(

Any ideas what this could be? It worries me that I could be dealing with corruption here. A few days ago I downloaded the world files from my server using FileZilla to my computer and reuploaded them to a different host node. FileZilla did not show any failed transfers or anything, I have no idea why that could cause this issue, but that's the only thing that's changed recently that comes to mind. So far I've seen TileEntitySkull and TileEntityChest popping up. This is on Paper 1.14.4 build 218. I've been using this world on a public server with countless players since March, so needless to say I don't want to just make a new one.

Should I head to each of these locations in-game and try to fix them individually?

**Comment by LoneDev6** [comment]
Seems related to this: https://github.com/PaperMC/Paper/issues/2644
It's a Spigot bug https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-5367


I don't think your world is corrupted btw
