### ISSUE TITLE
Entity Leave Vehicle is not Sending to the Player if That Player is the Vehicle

### ISSUE THREAD

**Issue by connection-lost** [PaperMC/Paper#265]
Here is something that you might just miss while fixing the riding problem:
### The issue:

If an entity is riding a player, and we eject the entity, everyone else but player will receive the entity leave vehicle packet.
### Steps/models to reproduce:

The test environment is: 
1. Having two (or more) players. 
2. Use the following code to let some entity to ride on one of the player:
`player.setPassenger(someentity)`
3. Use the following code to eject:
`player.eject()`
### What behaviour is expected:

The "someentity" will ride on the player, then getting ejected.
### What behaviour is observed:

The player who had someentity ride on him will see the entity rides on the player, but not ejected. The other player can see the expected player. In general, the player who has been ridden on does not receive the packet that the passenger has left.
### Plugin list:

No other plugin used.
### Paper build number:

git-Paper-712

**Comment by zachbr** [comment]
Confirmed, started playing with this tonight.
EDIT: this is likely going to be some nasty workaround, I haven't touched this since the other day, but it's a mess.
EDIT: and the fact that the 'vehicle' player doesn't render the 'passenger' player half the time makes this a pain as well.
