### ISSUE TITLE
ParticleBuilder

### ISSUE THREAD

**Issue by DispenserLP** [PaperMC/Paper#2650]
### What behaviour is expected:
When using Paper's own _ParticleBuilder_, there is a problem with color setting, where docs say you can apply the .color() method to the following particle types:

"Sets the particle color. Only valid for REDSTONE, SPELL_MOB and SPELL_MOB_AMBIENT."
If you now try to put the color on the Spell_MOB particle, there is an error in the console.

### What behaviour is observed:
Error in the console: "java.lang.IllegalStateException: Color may only be set on REDSTONE"

### Paper build number:
This server is running Paper version git-Paper-213 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Previous version: git-Paper-206 (MC: 1.14.4)

### Anything else:
I hope for an explanation, maybe even the doc entry is wrong, but I would be pleased to be able to use the function again in the future.

**Comment by chickeneer** [comment]
This documentation issue was resolved at some point between this ticket and now. It is true only REDSTONE is possible.
