### ISSUE TITLE
PlayerBucketEmptyEvent's setItemStack not working.

### ISSUE THREAD

**Issue by goosewoman** [PaperMC/Paper#2651]
### What behaviour is expected:
Changing the item stack in the event should change the itemstack in the inventory. (otherwise there's no point in a setitemstack function)

### What behaviour is observed:
The event updates the item stack on the API side, but it never changes the itemstack for the actual player.

### Steps/models to reproduce:
```java
    @EventHandler( priority = EventPriority.HIGHEST )
    public void onPlayerEmptyBucket( PlayerBucketEmptyEvent event )
    {
        System.out.println( "event triggered" );
        ItemStack clone = event.getItemStack().clone();
        clone.setType( event.getBucket() );
        event.setItemStack( clone );
        //or event.getItemStack().setType( event.getBucket() );
    }
````

you can change the itemstack to whatever you want and it won't change anything.

### Plugin list:
tested on a server with no plugins running except for the plugin with just the listener listed above.

### Paper build number:
 git-Paper-648 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Anything else:
Bug has been reported twice on spigot 3 years ago with no signs of anything being done to resolve the bug. Which is why I'm reporting here in the hopes of getting at least a response.

**Comment by limwa** [comment]
Maybe an updateInventory() will fix the problem for you until Bukkit, Spigot or Paper fix this issue

**Comment by goosewoman** [comment]
It doesn't. Because there's no item to update. It's never changed in the inventory on the server side.

I currently update it in a task, but it's hacky at best.

**Comment by kickash32** [comment]
How should this function interact with cancelling the event? Theres nothing in the documentation about this interaction.

**Comment by kickash32** [comment]
Actually upon further investigation I found the implementations of the PlayerBucketEvents to be extremely buggy. Changing the implementation would require too much effort and additionally changing the event to act according to the documentation would most likely break many plugins.

As a result I have taken the time to write a template for API users to use to instead
https://gist.github.com/kickash32/b7a794ac8056f1c3e52adda5e6e4545b
