### ISSUE TITLE
InventoryCloseEvent

### ISSUE THREAD

**Issue by DispenserLP** [PaperMC/Paper#2652]
### What behaviour is expected:
using _InventoryCloseEvent_

`if (e.getView().getTitle() != null && e.getView().getTitle().contains("Test")) {
// Do something
}`

### What behaviour is observed:
When using the above event, an error message is always output in the console. This issue only happened in 1.14.4 minecraft. Does this issue supposed to be related to mojang?

`java.lang.IllegalStateException: Title not set
at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
at net.minecraft.server.v1_14_R1.Container.getTitle(Container.java:48)
at org.bukkit.craftbukkit.v1_14_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69)`

### Paper build number:
This server is running Paper version git-Paper-220 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by limwa** [comment]
Does the inventory have a title?

**Comment by DispenserLP** [comment]
Yes, that inventory has a name, the error occurs only with the paperspigot, with the last spigot version it does not happen.

**Comment by NachtRaben** [comment]
PaperSpigot is an unsupported platform. We use Paper here. :^)

**Comment by DispenserLP** [comment]
Yeah, i mean it, i actual use Paper :) sorry, my mistake.

**Comment by electronicboy** [comment]
This is CB code, not something that we've touched, but I can say that the behavior here is kinda gross; getTitle will throw an exception if the title is not set, can't really see a non-exception inducing way to check that; If this is only occuring on Paper, which I doubt would be the case, we'd need a minimal replication plugin for this

**Comment by DispenserLP** [comment]
Ok, I've seen through other forums as well, the event was recently updated by md_5, maybe it has not been updated on paper yet? Funny is just, usually the error should not come because the inventory name is not net.

**Comment by limwa** [comment]
Does this error occur when you close your inventory or other inventory?

**Comment by DispenserLP** [comment]
The error occurs as soon as I close the inventory, which I query with .contains().

**Comment by limwa** [comment]
Yes, I know that. The thing is that the event gets triggered for every inventory you close. This means that if you close an inventory that does not have a title, the getTitle() method will throw an exception on the e.getView().getTitle() != null check, I believe. So if you really need this to work now, use a try-catch and just ignore the exception instead of checking if it is different than null.
I agree that this needs to be changed though. Making the method return null would be enough for this event...

**Comment by DispenserLP** [comment]
OK, I've already tried removing the null match, I also suspect that the exception will be triggered on my InventoryCloseEvent, but I do not know why it should fire, I'm not aware of inventory, which has no title. I hope the problem could be fixed in the future because I do not want to use a try-catch block just to stop receiving the error message.

**Comment by limwa** [comment]
And, by the way, why are you using getView() instead of getInventory()?

**Comment by DispenserLP** [comment]
Because you can not use it to determine a specific inventory, which bears the current name, for example "test".

**Comment by limwa** [comment]
Okay, I didn't know inventory.getTitle() was removed in 1.14
How are you opening your inventory to the player?

**Comment by DispenserLP** [comment]
I create a new inventory via the Bukkit API in for example the PlayerInteractEvent and set the player as InventoryHolder.

**Comment by limwa** [comment]
Don't set the player as the holder. Just do p.openInventory(Bukkit.createInventory(null, slots, "name"));
Then, on InventoryCloseEvent, just call e.getView().getTitle()

I have tested this method and it works

**Edit: completely forgot Bukkit.createInventory()**

**Comment by limwa** [comment]
If the issue has been solved, please close it

**Comment by limwa** [comment]
@DispenserLP
