### ISSUE TITLE
Nether portals can generate portals beyond the world border in the overworld

### ISSUE THREAD

**Issue by VeilStar** [PaperMC/Paper#2654]
### What behaviour is expected:
Nether portals do not generate beyond the world border, and instead are generated near the world border if a player went through a nether portal in the nether dimension at a location beyond the world border's location divided by 8.

### What behaviour is observed:
Nether portals are generated beyond the world border.

### Steps/models to reproduce:
Set the world border to 100000 (making the border appear at 50000).
Create a nether portal in the nether at -12000 90 -12000 and go through it.

### Plugin list:
Happens even without any plugins.

### Paper build number:
Paper version git-Paper-221 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Previous Version: git-Paper-210 (MC: 1.14.4)
You are running the latest version

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Black-Hole** [comment]
As a workaround you should set the world border of the nether world below 1/8 of the world border of the overworld.

Plugins could manipulate the exit location of a portal. So there might be plugins doing so already.

**Comment by electronicboy** [comment]
IMHO, the correct behavior here would likely be to just prevent the portal
being generated on the other end of this occurs, otherwise you just break
the portal in the other direction. It's pretty much essential that your
world border sizes don't conflict with how vanilla mechanics work

**Comment by VeilStar** [comment]
For context: We're running a semi-vanilla server that has been up and running for several years. The nether already has stuff built in it well past 6250 as this wasn't an issue before, running various spigot builds from 1.9 all the way to 1.13.2. We switched to paper for 1.14.4, coming from spigot 1.13.2. Before this switch portals would simply generate near the world border in the overworld if they were build far enough out in the nether. Setting custom world border sizes is not really a work around we can use.

Either way, not generating the portal is fine enough imo, but portals shouldn't be generated beyond the world border and shouldn't teleport the player beyond the world border.

**Comment by Proximyst** [comment]
This commit should have fixed it. https://github.com/PaperMC/Paper/commit/842e040c19567ea7682c288f2ed6a72ba52354a7

**Comment by zachbr** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/2040c4c476931e2b1582cd14e2e4d1e260eb5322

Upstream commit mentioned in 842e
