### ISSUE TITLE
Error when loading a chunk without a player

### ISSUE THREAD

**Issue by MrEAlderson** [PaperMC/Paper#2655]
### What behaviour is expected:
No error

### What behaviour is observed:
- An error: https://pastebin.com/74k60Uqs
- The chunk not getting loaded

### Steps/models to reproduce:
Call anything that'd load a chunk, such as Chunk#load, Block#setType.

### Paper build number:
git-Paper-207

**Comment by Spottedleaf** [comment]
I can't say what caused it - generally I would expect an unload call being called in a load event would do it.
We can add a warning for that type of call though. I've put it on my TODO

**Comment by HexedHero** [comment]
git-Paper-207?

**Comment by general2811** [comment]
paper-221
