### ISSUE TITLE
Less cheaters

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2657]
In the game, all player data is transferred to other players. Maybe you should transfer only the necessary information? because of this, there are mods thanks to which you can see the entire inventory of a player, his health, etc.

*I'm from another country, sorry for the terrible google translator. = /*

**Comment by mikroskeem** [comment]
There are plugins which can do that. See anticheat plugins and several public projects which obfuscate e.g player health info & armor data.

**Comment by Shevchik** [comment]
1. Inventory items: Only player equipment is transferred to other players. (And it is an essential information).
2. Health: Internal client logic depends on entity health in multiple places, so it is a necessary information to transfer.
3. Gamemode: some internal logic depends on player gamemode, so it is a necessary information to transfer.

**Comment by 0-x-2-2** [comment]
> In the game, all player data is transferred to other players. Maybe you should transfer only the necessary information? because of this, there are mods thanks to which you can see the entire inventory of a player, his health, etc.
> 
> _I'm from another country, sorry for the terrible google translator. = /_

Only the server only sends the necessary information already and it is not possible to view the entire inventory of other players.

**Comment by Cryptite** [comment]
> * Health: Internal client logic depends on entity health in multiple places, so it is a necessary information to transfer.

In reality the only important health updates are "Alive" or "Dead" (0 health). For the vast majority of cases, there's no need to receive accurate health about a player unless you're visibly wanting to show it with Scoreboard Teams, or other mods.

**Comment by Proximyst** [comment]
This is more of plugin territory (ProtocolLib is probably good help here).
