### ISSUE TITLE
Projectiles overloading chunks in the End

### ISSUE THREAD

**Issue by skerit** [PaperMC/Paper#2659]
###  Timings or Profile link:

Here are the timings, a while before it became a *huge* problem:
https://timings.aikar.co/?id=87e41bcdb8a042e29017ec7c0e2fd11c

### Description of issue:

Went to the End at 19:00 to kill the dragon with a group. Someone brought a bunch of snowmen to keep the Endermen busy.

A few hours later (maybe around midnight, when I took the timings report) a bit of server lag was poping up. I started getting the "**large chunk detected**" error. That's when I took the timing. I noticed something was happening in the End, but didn't have time to go check.

Another few hours later (at 02:00) I tried to go to actually go to the End, but that didn't work. My client froze & the server crashed.

I found a few `.mca` files that were 14MiB big. I deleted them, and that fixed it.
There were still some snowmen running around the other side of the End.

The next morning, it was broken again. Those other region files around spawn, where the snowmen still were, were also 14MiB big.

I eventually opened the file in `MCA Selector`. I selected a chunk with lots of snow, and it contained over 20.000 entities of snowballs.

![image](https://user-images.githubusercontent.com/755212/67639136-57c4db00-f8ec-11e9-920e-067e34cfd476.png)

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:

```
[19:03:11 INFO]: This server is running Paper version git-Paper-221 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[19:03:11 INFO]: Checking version, please wait...
[19:03:11 INFO]: Previous version: git-Paper-209 (MC: 1.14.4)
[19:03:11 INFO]: You are 2 version(s) behind
```

**Comment by skerit** [comment]
Here's the region file:

[r.0.0.zip](https://github.com/PaperMC/Paper/files/3776230/r.0.0.zip)

**Comment by electronicboy** [comment]
Technically #2496, but this is a really sticky topic, the longevity of entities is an issue, honestly not sure what the correct behavior here would be

**Comment by kickash32** [comment]
A possible fix for this could be to force chunks to tick for a minimum amount of time whenever an entity enters them. This way whenever a snowball enters the inactive chunk, the other snowballs inside it, can't accumulate.

**Comment by kickash32** [comment]
As there doesn't seem to be a "right" solution to this issue, I suggest you use this plugin to mitigate the problem.

https://github.com/NerdNu/MobLimiter

I would suggest a reasonable cull limit so that most snowballs are removed on chunk unload.

**Comment by electronicboy** [comment]
I've been thinking, it's only really a few entities which are at risk here, and in general, the main ones that people care about, e.g. tridents, enderpearls; do not really seem to be an issue; Given the vanilla issue, I think it's worth having some form of "lets not save them" (in general, or if their shooter was a non-player, maybe?), or maybe a cap to the # it will save in a chunk

**Comment by jackmulholland** [comment]
Does anyonenknow the fix for this? Or what config was added? I’ve tried using Moblimiter with a config entry for Snowballs and it still seems to happen

**Comment by Proximyst** [comment]
A potential(/ideal?) fix to this would be this: https://github.com/pl3xgaming/Purpur/blob/ver/1.16.2/patches/server/0080-Add-option-to-disable-saving-projectiles-to-disk.patch

**Comment by radiant-ai** [comment]
Today a group of players managed to crash my servers with a bunch of snowmen. Is it going to be patched soon?
For now I will just write a small plugin to remove projectiles in the end every X ticks.

Edit: I am not sure if a plugin can solve this issue, because the projectiles are usually in unloaded chunks...

**Comment by chrisliebaer** [comment]
Just to confirm the issue still persists on `Paper-274`. Had to clean an entire chunk full of lama spit (20k entities). The chunk itself got so big that it was move into it's own `.mcc` file.

That's 8 MB of uncompressed lama spit. The more you know.
