### ISSUE TITLE
Latest Build Download Link

### ISSUE THREAD

**Issue by CodeDoctorDE** [PaperMC/Paper#2661]
What is the link for the latest build jar?

**Comment by limwa** [comment]
https://papermc.io/downloads#Paper-1.14
Click on the top one

**Comment by CodeDoctorDE** [comment]
No, for my cloud i need a path to a jar on the server.

**Comment by CodeDoctorDE** [comment]
.jar on the end of the url

**Comment by electronicboy** [comment]
Right click the download link for the version you want, there is a post
pinned in the discord for the paperdocs with more info about the downloads
api

**Comment by CodeDoctorDE** [comment]
and for the always newest version?

**Comment by CodeDoctorDE** [comment]
I do not need to update anymore

**Comment by limwa** [comment]
https://papermc.io/ci/job/Paper-1.14/lastBuild/artifact/paperclip.jar

**Comment by CodeDoctorDE** [comment]
thanks ;)

**Comment by limwa** [comment]
Actually, as @electronicboy said, you should use this one https://papermc.io/api/v1/paper/1.14.4/latest/download

**Comment by CodeDoctorDE** [comment]
and for waterfall https://papermc.io/api/v1/waterfall/latest/download ?

**Comment by limwa** [comment]
https://papermc.io/api/v1/waterfall/1.14/latest/download
It's this one

**Comment by mikroskeem** [comment]
Please use Discord for such questions next time.

**Comment by CodeDoctorDE** [comment]
Okay
