### ISSUE TITLE
Hoppers don't respect MaxStackSize value of container

### ISSUE THREAD

**Issue by kripesh101** [PaperMC/Paper#2662]
### What behaviour is expected:
```java
// BlockDropper is instance of org.bukkit.block.Dropper
BlockDropper.getInventory().setMaxStackSize(1);
```
Items in dropper don't stack when being transferred from the hopper.

### What behaviour is observed:
Items stack up in the first slot of the dropper. However, manually placing the items works as intended.

### Steps/models to reproduce:
1. Create plugin that sets Dropper's MaxStackSize to 1
```java
// BlockDropper is instance of org.bukkit.block.Dropper
BlockDropper.getInventory().setMaxStackSize(1);
```
2. Set dropper's MaxStackSize to 1.
3. Place hopper above the dropper.
4. Put items into the hopper.
5. Check inventory of dropper.

### Plugin list:
- Self-made plugin to set Dropper's MaxStackSize.

### Paper build number:
git-Paper-221 (MC: 1.14.4)

### Anything else:
- The problem also occurs when transferring items using droppers into the container.
- I have set `disable-move-event` to true for hoppers.

**Comment by kickash32** [comment]
The docs do note that this API is unstable and the value set may overridden in many unexpected ways.

**Comment by Machine-Maker** [comment]
Replicated this bug on 1.16.4 build 311
