### ISSUE TITLE
Barriers don't show up while holding one

### ISSUE THREAD

**Issue by johncsuti** [PaperMC/Paper#2665]
### What behaviour is expected:
___Barrier blocks show up while holding a barrier___

### What behaviour is observed:
___Blank box no barrier just the outline___

### Steps/models to reproduce:
___Nothing happens on all my 1.14.4 servers___

### Plugin list:
___None___

### Paper build number:
___git-Paper-221 (MC: 1.14.4)___

### Anything else:
___Nothing really im op on my server so it cant be a permission issue___

**Comment by johncsuti** [comment]
![2019-10-30_22 27 25](https://user-images.githubusercontent.com/22971404/67914213-ceb8d880-fb65-11e9-99d4-ed4b0c472e2a.png)

**Comment by electronicboy** [comment]
This is client sided and has nothing to do with the server, double check
that you've not disabled particles or something like that

**Comment by johncsuti** [comment]
Nope turns out it was an issue with the server, i kinda really modified paper code files so it would force set somethings and it was settings particles to off instead of on. Yes that is against the eula but its on a private server too so yeah that was the issue. Also yes its modded for it to work.

**Comment by zachbr** [comment]
We don’t provide support for custom changes to our code here. Your failure to disclose them wasted all of our time. Please don’t use this tracker with your custom version in the future.
