### ISSUE TITLE
Chunk Ticks - Blocks TPS lag

### ISSUE THREAD

**Issue by AsVaidas** [PaperMC/Paper#2666]
Server has a problem with TPS lag

https://timings.aikar.co/?id=5701d11c31bc44c594314e2741282af8 (Paperspigot)
https://timings.spigotmc.org/?url=jiwuqudono (Spigot)

Tried changing host, tried a few anti-lag plugins, tried detecting Tile blocks (and there is just a few of them). 
Can't seem to find any reason why it should lag. 

root@hsiy:~# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel Xeon Processor (Skylake, IBRS)
Stepping:              4
CPU MHz:               2593.924
BogoMIPS:              5187.84
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-3

TOP:
`top - 15:23:21 up 10 days, 20:04,  1 user,  load average: 2.15, 1.94, 1.84
Tasks: 130 total,   1 running, 129 sleeping,   0 stopped,   0 zombie
%Cpu(s): 32.3 us,  1.9 sy,  0.0 ni, 65.3 id,  0.1 wa,  0.0 hi,  0.4 si,  0.0 st
KiB Mem : 16436780 total,   167196 free, 15142904 used,  1126680 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   818960 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2985 root      20   0 17.191g 0.014t  26520 S 136.3 90.7 114:44.08 java
`
16GB ram, 1TB bandwith

**Comment by electronicboy** [comment]
For support with timings, please use discord/irc/the forums; Overall, looks like 1.14 and a slow CPU (Running under a hypervisor also doesn't help get a full picture of what is going on either and creates its own set of overheads)

As a note, anti-lag plugins often try to tackle the issue improperly and trap the server in a TPS loss cycle, configuring your server to not need these plugins in the first place is a much better solution

**Comment by AsVaidas** [comment]
> For support with timings, please use discord/irc/the forums; Overall, looks like 1.14 and a slow CPU (Running under a hypervisor also doesn't help get a full picture of what is going on either and creates its own set of overheads)
> 
> As a note, anti-lag plugins often try to tackle the issue improperly and trap the server in a TPS loss cycle, configuring your server to not need these plugins in the first place is a much better solution

Yea, I don't use anti-lag plugins, they made more lag. 
It seemed like it's my own programming fault, but block ticks still high (other things got a lot lower). 
Thanks for the response!
