### ISSUE TITLE
Crash while waiting on chunk

### ISSUE THREAD

**Issue by VacantFiend** [PaperMC/Paper#2669]
### Link/paste of stack trace
https://pastebin.com/UYAawAV6

### Plugin list:
ChunkMaster, CoreProtect, DeathFeathers, Dynmap, JoinMessagePlus, LibsDisguises, LimitPillagers, LuckPerms, MobHeads, ProtocolLib, Seats, Sk-NBeeT, Skellett, SkQuery, Skript, SpigotPing, VillagerOptimiser.

### Actions to reproduce (if known):
Returned to problem chunk and nothing happened. First time it's ever happened in the past month and a half.

### Paper build number:
Updated from 196 to 221 on 10/25/2019.

**Comment by Spottedleaf** [comment]
It was stuck on generation - specifically the lighting phase (light status is after feature status). I think these deadlocks are relating to lighting. Wouldn't surprise me given we already know of poor threading occurring for lighting.
