### ISSUE TITLE
1.14.4 server uses a lot of memory

### ISSUE THREAD

**Issue by Xayanix** [PaperMC/Paper#2670]
![image](https://user-images.githubusercontent.com/12672902/68070622-26775f80-fd71-11e9-8e3b-4cb05db9b1ad.png)

70 players online, 3GB memory allocated.
Basic plugins like Essentialsx, Vault.
Build git-Paper-223 (MC: 1.14.4)

**Comment by Xayanix** [comment]
Probably caused by Loottables.

**Comment by aikar** [comment]
What's your evidence that its Loot Tables? Need more details from those result to show what's holding it.

**Comment by HexedHero** [comment]
How are you even holding 70 players with 3gb

**Comment by Xayanix** [comment]
> What's your evidence that its Loot Tables? Need more details from those result to show what's holding it.

https://hastebin.com/ekuwawiyok.bash
also: https://github.com/PaperMC/Paper/issues/2312



> How are you even holding 70 players with 3gb

It's pretty enough if you know how. We are holding 250+ players easily on servers with 3gb ram.
Fast CPU is more important than tons of memory.

**Comment by limwa** [comment]
> It's pretty enough if you know how. We are holding 250+ players easily on servers with 3gb ram.


~~Well, that doesn't seem to be true because your server is crashing due to the amount of players online.~~

**Comment by Xayanix** [comment]
> > It's pretty enough if you know how. We are holding 250+ players easily on servers with 3gb ram.
> 
> Well, that doesn't seem to be true because your server is crashing due to the amount of players online.

You have no idea what are you talking about. Already fixed it by removing lootables, but still is spigot issue which should be fixed.

**Comment by electronicboy** [comment]
What you've screenshotted really shows nothing, 1.14 in general uses more memory vs earlier versions; If there is an actual memory issue, you need to actually provide the relevant information, e.g. showing the actual issue much better than just showing what really looks like typical memory usage for 1.14; if this is also an issue specific to spigot as you're seemingly implying, you need to actually show this

**Comment by Xayanix** [comment]
Temporarily "fixed" it, by removing Lootable tile logic.
Here is download link for anyone who has same problem:

https://anonymousfiles.io/8IjBERtT/
