### ISSUE TITLE
I got an error in console for some reason

### ISSUE THREAD

**Issue by TheNicksinIsTaken** [PaperMC/Paper#2673]
https://pastebin.com/N58XdjvX
no gameplay was messed with it just gave me this error and told me to report so I think it will have affect in the future.

**Comment by Spottedleaf** [comment]
there should be an exception right before that, we need that too

**Comment by TheNicksinIsTaken** [comment]
https://pastebin.com/4pr4rvE7

**Comment by alaajel** [comment]
to fix this please prevent air from dropping ??
java.lang.IllegalArgumentException: Cannot drop air

**Comment by electronicboy** [comment]
The server already prevents air from being dropped, best guess would be that that is not an air stack, but a stack which is invalid in some other form of way, e.g. negative value? We could improve the check there, but this is ultimately not a paper issue
