### ISSUE TITLE
Server deadlock while waiting for end chunk

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2674]
### Link/paste of stack trace
https://pastebin.com/SML8h2t8
### Actions to reproduce (if known):
Loading end chunks - probably issue with lighting. See similar issue report #2669
### Plugins:
Not related to issue. 
### Paper build number:
paper 221

**Comment by electronicboy** [comment]
We'd need the full logs, or at least the full logs of the watchdog reports; However, this is chunk loading induced from a player flying into chunks which aren't fully loaded, more than likely the player was just flying too fast and caused excessive loads, no real indication of a deadlock here
