### ISSUE TITLE
Low TPS and crash issue

### ISSUE THREAD

**Issue by JHarris12345** [PaperMC/Paper#2677]
### Link/paste of stack trace

    https://pastebin.com/YmWmDkAy

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

I know it says do not rpeort to paper however the worldguard devs said due to the "The server has not responded for 0 seconds! Creating thread dump" should not have shown so it is paper

### Plugin list:
https://gyazo.com/b634bd2879e6d29ecef10c7abbada96a

### Actions to reproduce (if known):
N/A

### Paper build number:
223

**Comment by electronicboy** [comment]
"0 seconds" - timings report? (Mainly so we can see your config file)
Standard support for TPS related issues should be resolved on the discord, the issue tracker is for bugs, not general support

**Comment by JHarris12345** [comment]
I didnt manage to get a timings report whilst it was major lagging as it crashed. But here is before. TPS is high there but the issue of BlockPhysicsEvent was the cause of TPS loss https://timings.aikar.co/?id=3cac4349901a410f9b0eb70d75705acc

**Comment by electronicboy** [comment]
I see no issues in your configuration there; Only real guess from that would be that the server started the next tick while the watchdog thread was about to start dumping information, seems a bit odd given that the server appears to be near the end of a tick there, given that it's debug information, it's not really an issue outside of an annoyance

The low TPS in that timings report is primarily due to block ticking in the world; some redstone mech or other

**Comment by JHarris12345** [comment]
Anyway to fix it starting the tick when watchdog posts a dump thread? I have these crashes up to 10x a day. Also is there anyway to fix redstone lag (ive optimized it in paper) because it is literally only 1 contraption that isnt that big on a redstone clock. I dont want to ask people to remove their builds

**Comment by electronicboy** [comment]
Watchdog dumps are not crashes, they're warnings;
Only real fix for any potential race condition there would really just introduce additional unneeded complexity and introduce barriers where not needed

**Comment by electronicboy** [comment]
as a note, the size of a contraption isn't the issue, it's the size of work it's causing on the server; 28k physics updates in a singular tick is *not* normal and will create a lot of work not only for the server, but also plugins which needs to listen on those interactions

Only fix here is to reduce the work on the server, e.g. limiting players from building contraptions which induce thousands of block updates a tick

**Comment by JHarris12345** [comment]
Is this mainly redstone clocks? Its hard to stop an entire server building redstone contraptions whereas easier to stop clocks.
