### ISSUE TITLE
If `keep-spawn-loaded: false` Then items Vanish if dropped through End's exit portal.

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#2681]
### What behaviour is expected:
Items dropped through end portal arrive at spawn.

### What behaviour is observed:
When `keep-spawn-loaded: false` items vanish when dropped through end's exit portal.

### Steps/models to reproduce:
'keep-spawn-loaded: false'
go to End. drop items through.

### Plugin list:
Bot*, CheaperPhysicsEvent, ChestShop, ChestShopNotifier*, ClaimslistClassifier, CoreProtect, dynmap*, Dynmap-GriefPrevention*, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsSpawn, GPAuctions, GPRealEstate*, GriefPrevention, GroupManager*, InGameMotd, PlaceholderAPI, PlayerVaults*, PluginLibrary*, ProtocolLib, PVPToggle*, SuperTrailsPro*, Vault, WorldBorder*, WorldEdit, WorldGuard

### Paper build number:
Paper version git-Paper-225 (MC: 1.14.4)

### Anything else:
If another player keeps spawn loaded by standing at spawn, items dropped through the End's exit portal will appear at spawn, as normal.

**Comment by NullCase** [comment]
@zachbr It seems like payments are slower now, and LMC is just one server. 

Still, I will put money on this issue. Because you guys are working hard and time isn't free.

Happy to donate, as always.

Basically LMC is looking at this problem where items dropped in the the exit portal are vanishing. For context, it looks like spawn isn't caused to load when items are sent through the exit portal. In our case, items vanish.

I don't know, maybe it's a configuration problem. Do you think I've messed something up here?

**Comment by NullCase** [comment]
If this is a bug, then I'm still happy to donate in support of a patch for this. Again it's possible the problem is on my end.

**Comment by AJMFactsheets** [comment]
Very interesting issue that did not exist in 1.13! I have been trying to get around to fixing this for weeks now. So far, I have created a tentative fix for this issue. If you would like a precompiled binary I have released one on my fork of paper [here](https://github.com/AJMFactsheets/Paper/releases/download/Fix-2681/paperclip-fix-2681.jar)

**Comment by NullCase** [comment]
hi @AJMFactsheets It sounds like you've already built a solution!

I don't know how to code. Because its just not my speciality :)

How would it work to add this to Paper? What would it cost?

And once I've had an opportunity to test your solution, do you mind if I donate something because I'd like to support your hard work here.

**Comment by AJMFactsheets** [comment]
Thank you @NullCase I have done more testing and my solution seems relatively stable and lag-friendly. If you find any problems on any test/production servers I'd love screenshots or debug logs. So far, my solution seems much better than the current behavior of deleting all items sent through the exit end portal.

If the Paper admins approve of this solution, it will be added to Paper :)

If you feel the solution is valuable, donations are always appreciated!

**Comment by NullCase** [comment]
In advance of approval/testing, whats the best way to donate?

**Comment by NullCase** [comment]
@AJMFactsheets In advance of approval/testing, whats the best way to donate?

**Comment by AJMFactsheets** [comment]
I have figured out that the items do not vanish, but spawn at Y=0 due to the chunk not being loaded. Some items are able to bubble to the surface, but could burn in lava or get stuck in a cave.
I'm going to submit a pull request with a much better fix than before with precompiled jars for 1.15 and 1.14.4

@NullCase I would donate to the awesome people who run Paper and Spigot! Especially for such a speedy 1.15 release!

**Comment by NullCase** [comment]
Hi @AJMFactsheets It seems like with 1.15 this one is on the back burner, which makes sense. Just in case it gets merged, I'm checking regularly so I can test and get Paper's dev team some $.

I'll post the receipts here after that's all been done.

**Comment by NullCase** [comment]
Confirmed! Thanks guys.

@AJMFactsheets Here's the deets. thanks again for your hard work. (some details removed for privacy).
![Vanish item fix - Donation to Paper on behalf of AJMFactsheets](https://user-images.githubusercontent.com/32785664/73057256-041c4c00-3e5f-11ea-8a24-741d1b784aab.png)
