### ISSUE TITLE
Rasbian Paper 1.14.4 Latest Repetitive Crash while loading (new) chunks.

### ISSUE THREAD

**Issue by Teku16** [PaperMC/Paper#2682]
### Link/paste of stack trace
https://pastebin.com/p944YpQe

### Plugin list:
Essentials
World Border

### Actions to reproduce (if known):

The issue was occurring every time we moved outside of the spawn radius, it was fixed by doing a world border generation upfront with WB. From what I am reading and from prior experience, 2.7G of ram is plenty to generate chunks on the fly with one person logged in...

While we have circumvented the issue, for now, I would like to find a solution for the future. 

### Paper build number:

/version says: `git-Paper-225 (MC: 1.14.4) API 1.14.4-R0.1-SNAPSHOT`

Thanks!

**Comment by RodneyMKay** [comment]
From the stack trace: "There is insufficient memory for the Java Runtime Environment to continue."

**Comment by Teku16** [comment]
> From the stack trace: "There is insufficient memory for the Java Runtime Environment to continue."

Yes, I know. However, that is not the case. There is plenty of memory available when running the server... Is there some optimization I could be missing? I have mostly stock settings from paper/bukkit/spigot. I've run servers in the past with 1-2G just fine when loading. Unless 1.14 is that much more resource-intensive? Thanks for the reply, anyway.

**Comment by EbonJaeger** [comment]
1.14 is definitely more resource intensive, yes.

**Comment by electronicboy** [comment]
Not a paper issue, your OS refused to allocate memory to java, from the memfree info, looks like you actually had free ram, just your kernel refused the allocation for some reason; You'd need to potentially go down the avenue of a bad JVM install/bug, maybe try a different version of java

**Comment by Shevchik** [comment]
Most likely it refused to give up memory because the actual limit of how much memory 32bit OS can give to application is low (especially on raspberry, where a shitton of things are mapped on the upper memory addresses). And java needs memory for it's internal vm usage (classes, JIT codecache, some memory for ). Nettty needs memory for buffer pool, etc. So most likely you really run out of memory which rpi can allocate to a single process.
