### ISSUE TITLE
Trident setPierceLevel is not working

### ISSUE THREAD

**Issue by ArmyAgira** [PaperMC/Paper#2690]
this is my code
`	public void Trident(Player p) {
		org.bukkit.entity.Trident ar = p.launchProjectile(org.bukkit.entity.Trident.class);
		ar.setShooter(p);
		ar.setPierceLevel(10);
		ar.setPickupRule(PickupRule.DISALLOWED);`
and ar.setPierceLevel(10); is not working...
is that normal?

paper version : git-Paper-220 (1.14.4)
api version: 1.14.4-R0.1-SNAPSHOT

**Comment by zachbr** [comment]
See GH-2541.

**Comment by ArmyAgira** [comment]
> See [GH-2541](https://github.com/PaperMC/Paper/issues/2541).
hm....
i cant understand.

this trident can damage to entity
but its not pierce

**Comment by kickash32** [comment]
Although Tridents have these methods, they do not do anything. This is because who ever added the Tridents to the Bukkit API did not notice most of the projectile code is overriden. I believe this issue should be reopened after it has been reformatted into a formal feature request.

**Comment by zachbr** [comment]
The formal request is the other ticket. This is a duplicate.

**Comment by ArmyAgira** [comment]
so is that cant use?

**Comment by kickash32** [comment]
I see, thought the ticket was closed as the author's problem was solved.

> so is that cant use?

Yes unfortunately the API is broken for the time being (not really a simple fix as a moderate amount of code needs to be recreated)

**Comment by ArmyAgira** [comment]
> I see, thought the ticket was closed as the author's problem was solved.
> 
> > so is that cant use?
> 
> Yes unfortunately the API is broken for the time being (not really a simple fix as a moderate amount of code needs to be recreated)

i see...
i hope this work...
