### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Nedjii** [PaperMC/Paper#2691]
### Link/paste of stack trace

The link above includes the plugin list.

I don't know how to reproduce the issue, it used to happen every minute then it stopped and 10 days later it crashed again. It's about NBT in the crash report but the player had nothing else than flowers in his inventory so I didn't manage to figure what was causing the crash.

I'm running git-paper-"1253ca47" (MC: 1.13.2)

**Comment by electronicboy** [comment]
You have a plugin which is messing with inventories async

**Comment by Nedjii** [comment]
I don't have any inventory managing plugin, I already looked about that.

**Comment by Nedjii** [comment]
If it is a plugin causing this is there a way to figure out which ? I got 104 plugins and the crash is really random, it can happen one time a week so removing plugins one by one wouldn't make me know the one messing.

**Comment by electronicboy** [comment]
The only "easy" way that I know of debugging these types of issues basically boils down to tryna work out when these async accesses occur which often involves modifying the server to produce info when this occurs, which can be a bit of a struggle for areas like this as accessing inventories async is valid in some contexts but not others; the other alternative basically involves decompiling your plugins and inspecting them manually

**Comment by Nedjii** [comment]
I see, thanks for the help !
