### ISSUE TITLE
modify playerdata through /data

### ISSUE THREAD

**Issue by metroite** [PaperMC/Paper#2694]
**Is your feature request related to a problem? Please describe.**
Yes it is related to https://github.com/PaperMC/Paper/issues/2528

**Describe the solution you'd like**
Is it possible to completely allow access to playerdata with the vanilla commands /data and /execute? This would be absolutely amazing! Plugins are able to do that iirc.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
Minecraft has many commands like /clear or /effect, which modify the player data directly, but when it comes to /data or /execute it is not permitted (except for item tags in player inventories).

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
