### ISSUE TITLE
Wrong bit shift in Chunk#getChunkKey(Location)

### ISSUE THREAD

**Issue by Flo0** [PaperMC/Paper#2696]
The method Chunk#getChunkKey(Location) shifts the x and z component of
the location Object towards MSB instead of LSB.

This means they get basically multiplied by 16 and packet into a long.

I decompiled the latest Paper build (226)

The decompiled method:
Chunk.getChunkKey((int)((int)Math.floor((double)loc.getX()) << 4), (int)((int)Math.floor((double)loc.getZ()) << 4));

What i think it should look like:
Chunk.getChunkKey((int)((int)Math.floor((double)loc.getX()) >> 4), (int)((int)Math.floor((double)loc.getZ()) >> 4));

**Comment by electronicboy** [comment]
This is intentional, this is for API usage, not to replicate internal
vanilla behaviour

**Comment by Spottedleaf** [comment]
The shift is the wrong way, the function requires chunk coordinates.
