### ISSUE TITLE
Knowledge Book not filling items in the crafting grid properly

### ISSUE THREAD

**Issue by WiebeHero** [PaperMC/Paper#2698]
### What behaviour is expected:
1: A recipe containing a ItemStack as a ingridient should be put in the crafting grid when clicking the recipe (if available).
2: Crafting recipes turn white when a recipe with only ItemStacks are present in the crafters inventory.
3: Minecraft recipes (that you click in the book) that scan items based on materials.

### What behaviour is observed:
1: This is not present, it will just put a normal obtained item in the crafting grid instead of the actual ItemStack
2: The recipes in the book do NOT turn white when a ItemStack is given and required in the recipe.
3: Minecraft recipes do not scan for materials, but for ItemStacks.

### Steps/models to reproduce:
Video: https://www.youtube.com/watch?v=bOR0erlEutg

### Plugin list:
My own plugin
BlowableObsidian
Citizens
Essentials
item-nbt-api-plugin
LuckPerms
Multiverse-Core
PermisisonsEX
Protocollib
ProtocolSupport
ProtocolSupportStuff
WorldEdit
WorldGuard

### Paper build number:
git-Paper-575

### Anything else:
Nothing else.

**Comment by Zeruska** [comment]
I guess its a client side bug, not server side.
The client check only the Material, instead of ItemStacks, so cant make a difference between items.

**Comment by WiebeHero** [comment]
You might be right there, but it would still make no sense at all. Normal minecraft recipes should (I believe) only check for materials and not the actual ItemStack. Which you can clearly see displayed in the video. If this is a clientside bug il probably take it to the bug tracker of mojang.

**Comment by Machine-Maker** [comment]
@WiebeHero Normal minecraft recipes check the entire ItemStack, not just the material. You can have recipes that require specifically named items, etc. So it probably is indeed a client side thing
