### ISSUE TITLE
Chunk taking time to load until server stops. "Chunk Status - minecraft:heightmaps"

### ISSUE THREAD

**Issue by robertoccu** [PaperMC/Paper#2699]
### Link/paste of stack trace

Stacktrace when server stopped: https://pastebin.com/Ya5p2Liz
Before that, some informative message of a chunk not loading (up to 60 seconds): https://pastebin.com/yjTkMKjp

### Plugin list:
Plugins (47): ArenaCTF*, AutoMessage, BattleArena, BetterShulkerBoxes, BuycraftX, Citizens, CommandBlockHelper, CommandHelper, CommandHook, CoreProtect, CustomMessages*, DeathMessagesPrime, Denizen, dynmap*, EntityTrackerFixer, EpicHeads, Essentials, EssentialsAntiBuild, EssentialsProtect, EssentialsSpawn, FastLeafDecay, Herochat*, HorseStables*, Itemizer, LimitPillagers, LWC, McersUtils*, Multiverse-Core, Multiverse-NetherPortals, NBTEditor, OpenInv*, PermissionsEx*, PermissionsExTabColors*, PerWorldInventory, Plot2Dynmap*, PlotSquared, ServerBotForTelegram, Shopkeepers, Spleef*, TreasureChest, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Actions to reproduce (if known):
Caused by a player (probably flying) exploring an old world generated with Minecraft 1.0.0 (but played actively until Minecraft 1.7 and less frequently until Minecraft 1.13. This is the first time we opened this map with PaperMC installed. No problems before with Spigot.

Sorry but the map is private and I'm not able to share it.

### Paper build number:
This server is running Paper version git-Paper-225 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-221 (MC: 1.14.4)
You are 1 version(s) behind

---

Maybe related to #2674 

Note that "Chunk Status" is "Chunk Status - minecraft:heightmaps" and other stacktraces of chunk problems have "Chunk Status - minecraft:full".

Until a way to fix it is found, maybe disabling async chunk loading do the trick?

**Comment by electronicboy** [comment]
Unlikely to be related to async loading, just looks like a block update triggered a ton of block updates somewhere which induced a fair amount of chunk loading, I do wonder why world updates would be triggering physics updates; I guess it would be potentially needed for some aspects such as block connections, but o.O I would maybe suggest tryna pre-upgrade the world, no indications of a deadlock whatsoever, but you've not provided the full log so we can't really see the full picture

**Comment by robertoccu** [comment]
> Unlikely to be related to async loading, just looks like a block update triggered a ton of block updates somewhere which induced a fair amount of chunk loading, I do wonder why world updates would be triggering physics updates; I guess it would be potentially needed for some aspects such as block connections, but o.O I would maybe suggest tryna pre-upgrade the world, no indications of a deadlock whatsoever, but you've not provided the full log so we can't really see the full picture

Here is a full log that ends with the same chunk again causing server to stop. This time when the user that was exploring the map reconnect from the previous 'crash'.

It's too big for pastebin or hastebin so here is the file.

[2019-11-20-2.log](https://github.com/PaperMC/Paper/files/3871794/2019-11-20-2.log)

**Comment by electronicboy** [comment]
without a sane means of replication, this is a bit of an oddball one, real worry would be that it tried to load the chunk which it was converting or something like that and ended up deadlocking
