### ISSUE TITLE
Chunk Refuses to Unload if the Player's View Distance is Tampered

### ISSUE THREAD

**Issue by connection-lost** [PaperMC/Paper#270]
This is a critical issue related to paper's player view distance API. The issue will cause chunks unable to unload even chunk#unload() is used.
Whenever a player's view distance is being decreased by paper's player view API, there is a chance that the additinal chunks will not be unloaded properly. 
### Steps/models to reproduce:
1. Set server view distance to 8.
2. Let a player join the server.
3. player#setViewDistance(5); which 5 < 8
4. Let the player log out in order to unload every chunk that loads for him.
### What behaviour is expected:

Chunk unloaded properly.
### What behaviour is observed:

See the image below. White means loaded chunks and black means unloaded chunks. Each pixel = 1 chunk. Solid square means there is a player right there, non-solid squares means chunks that are not properly unloaded.
http://i.imgur.com/hcC9Iql.png
There are a lot of "squares" that are has a border of 3 pixels. I have a custom plugin that changes player's default view distance from 8 to 5. 8 - 5 = 3.
This is also tested on my local server with similar result. The border width of the squares is always the shrinked distance.
### Other
1. I think the moment when setting the view distance triggers the issue, but maybe it is triggered when player leaves the server. Still testing.
2. ~~I am not sure whether this bug will only work on non-pregenerated world or not. Because I am not able to reproduce this bug over and over on the exact same spot in the map.~~ This issue is confirmed on both pre-generated world and new worlds.
3. The bugged chunk is not unloadable using bukkit's chunk-gc, nor using chunk#unload()
4. This bug may also cause things similar to #207, but it needs to be confirmed. My server is still having #207, not sure why. I will disable my dynamic view distance feature, and will try to compare the results.
### Plugin list:

no additional plugins.
### Paper build number:

tested on paper-712 and paper-724

**Comment by aikar** [comment]
This patch is def a source of trouble. I fixed #207 after much debugging due to this patch.

Though I don't personally use this API (though considering it) so havent had time to look into it more.

@Byteflux fix it!

**Comment by aikar** [comment]
this should be resolved with the 1.9.4 update, I put the fix in while I was doing the update.

reopen if still an issue.
