### ISSUE TITLE
Slf4J NOP for Plugin dependency

### ISSUE THREAD

**Issue by codesalatdev** [PaperMC/Paper#2703]
I am currently working on a plugin that uses a third-party dependency for IRC connections. This dependency is **very** verbose and has no way to disable logging. Instead, the maintainer recommends adding slf4j-nop (no operation) to the jar. Spigot uses that by default, but Paper seems to have implemented a different approach for logging.

I am not very familiar with SLF4J, but If I understand this correctly, paper has a binding for logging in its classpath that the dependency uses. Because the messages from that dependency are spamming in the log (~20 lines of connection debugging + heartbeat information every 5 min), I would like a way to just discard all of these (it still throws exceptions that are handled properly by myself). As long as I am not missing anything obvious, the architecture does not allow to do that right now.

**Comment by mikroskeem** [comment]
You can tap into implementation details and configure log level in onEnable for specific logger package. Log4j-core should be enough for that.

**Comment by codesalatdev** [comment]
Solved like @mikroskeem suggested. Thank you very much! Closed.
