### ISSUE TITLE
Server crashes with input/output error

### ISSUE THREAD

**Issue by jintsuu** [PaperMC/Paper#2707]
### Link/paste of stack trace

    https://pastebin.com/Z1BDR9Kb

### Plugin list:
Dynmap
WorldBorder
PermissionsEx
EssentialsX
Massivecore
Factions
Vault
PlaceholderAPI
Protocollib

### Actions to reproduce (if known):
Unknown. Server seems to randomly shut down after being online for a while.

### Paper build number:
git-Paper-230

**Comment by electronicboy** [comment]
Your terminal caused an IO exceptions, invalid characters sent? bad terminal?

**Comment by jintsuu** [comment]
Sorry, what would qualify as an invalid character or bad terminal? I'm very much a noob when it comes to server hosting, my bad.

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
