### ISSUE TITLE
Block Metadata is completely broken.

### ISSUE THREAD

**Issue by TheRealGammer** [PaperMC/Paper#2708]
### What behaviour is expected:
___I expected it to work.___

### What behaviour is observed:
___Whenever I do Block#hasMetadata it always returns false, and when I do Block#getMetadata#size it's always zero.___

### Steps/models to reproduce:
___I wrote the following code:___
```java
public class eventHandler implements Listener
{
	@EventHandler
	public void onPlayerInteract(PlayerInteractEvent event)
	{
		Block block = event.getClickedBlock();
                System.out.println(block.hasMetadata("snowy")); //Tested on grass block
                //...........
		
	}
}
```

### Plugin list:
___Only mine.___

### Paper build number:
___git-Paper-192 (MC: 1.14.4)    :    1.14.4-R0.1-SNAPSHOT___

**Comment by Shevchik** [comment]
And where is the code that sets it?

**Comment by electronicboy** [comment]
Wrong API, you're looking for the BlockData API, specifically the Snowable interface https://papermc.io/javadocs/paper/1.14/index.html?org/bukkit/block/data/Snowable.html

Bukkits metadata API is for plugins to store data at runtime against block locations
