### ISSUE TITLE
Relocate fastutil to match spigot/craftbukkit package

### ISSUE THREAD

**Issue by crysis992** [PaperMC/Paper#2709]
### What behaviour is expected:
Being in the same package as in spigot/craftbukkit

### What behaviour is observed:
It's in a different package

### Steps/models to reproduce:
I'm using some classes of the fastutil library, but it's in a different package/path in paper than it is on spigot. It would make things a lot easier if it would be located on the same path as on spigot/craftbukkit to keep compatibility for plugins relying on it.

**paper**: it.unimi.dsi.fastutil
**spigot & craftbukkit:** org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil

### Paper build number:
This server is running Paper version git-Paper-230 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
FastUtil is provided as API, it's not viable for us to handle this without breaking plugins going in the other direction; To my understanding, you should just be able to use relocations in your own build in order to get a jar which will work as expected in non-paper environments

**Comment by zachbr** [comment]
We used to have a hook in spigots legacy remapping tool to take care of this at runtime. I’ll have to see why that’s not functioning anymore or if there’s an issue.

**Comment by electronicboy** [comment]
Different issue to my understanding

Compiling against paper will be fine for paper, however; due to the fact that we don't relocate, will break for Bukkit/Spigot
if the plugin was compiled for Bukkit/Spigot, it will work fine on all platforms

**Comment by zachbr** [comment]
Hmm I may have misread the issue then.

Not sure there’s a great solution to this issue then. Spigot placing it under the implementation libraries folder is their way of expressly keeping it out of API. We already don’t support people (ab)using Spigot’s older terminal libraries from that path. Not sure it makes a lot of sense to change our minds.
