### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#271]
logs
http://hastebin.com/tutahegejo.avrasm

build
paperclip-724

java 8_91 x64

plugins
CoreProtect, icJukeBox, WorldEdit, SimpleTrading, PluginManagerReloaded, AdvancedReport, FastCraftPlus, LuckyBlock, pParticles, Interactables, ActionHealth, CustomRecipes, LiquidControl, ProtocolLib, WorldGuard, LibsDisguises, Shopkeepers, WildSkript, EditableSign, PermissionsEx, HorseTpWithMe, PvPDiffTimer, CustomTime, QwickTree, DuelMe, Tablist, Vault, SimpleSit, SilkChests, Titlebar, Skript, PortalCommands, Essentials, SexyMotd, ChangeSkin, HolographicDisplays, PreciousStones, ColoredTags, ChestCommands, EssentialsChat, RandomTeleport, EssentialsSpawn, Smileychat, AuthMe

paper.yml
http://hastebin.com/gaziguduca.rb

spigot.yml
http://hastebin.com/kofunayogu.vala

bukkit.yml
http://hastebin.com/vahequtuva.vala

server.properties
http://hastebin.com/muturoyewu.hs

timings
https://timings.aikar.co/v2/?id=841595c485ec4ccd8b636d90be5ba719

**Comment by aikar** [comment]
We can confidently say this is caused by a bad plugin.

Try removing any that deal with entities 1 by 1 until issue stops occurring.
