### ISSUE TITLE
Chunks disappearing MC-150202

### ISSUE THREAD

**Issue by Gerrygames** [PaperMC/Paper#2714]
### What behaviour is observed:
Since we updated from Paper 1.14.4 195 to 229 users started complaining about chunks disappearing.
Here are some screenshots are users sent us:
https://imgur.com/ahfWIve
https://de.share-your-photo.com/067155650f

### Steps/models to reproduce:
Unfortunately we can't really say how to reproduce this or when exactly this occurs. This seems to be happening at random. There were only a handful complains.

### Plugin list:
If you really need a list of our plugins, I can provide it. However almost all our plugins are custom and private (except ViaVersion and ProtocolLib). And this issue appeared after updating Paper and we did not update any of our plugins since then or shortly before that.

### Paper build number:
Paper 229 / 23e53aab97466adb42c46d16ad3b5ff26254d1bd

### Anything else:
The only commit that has anything to do with chunk loading between 195 and 229 is this one:
https://github.com/PaperMC/Paper/commit/bfc807c27af524162a56c41bcceb62358f640a80
Maybe there is an issue if the world gets unloaded too quickly after being loaded?

Sorry for not being able to provide any real information on how to reproduce this issue. But maybe someone can have a look at the given commit and will see an obvious issue with it. Chunks disappearing is really a severe issue. 
We downgraded to Paper 205 and hope that the issue will no longer occur. Will report back if that's the case.

**Comment by Gerrygames** [comment]
This might be related to / be https://bugs.mojang.com/browse/MC-150202
We also had some player that ended up with chunks outside their islands world border.
I will create a git diff for 19w34a and see what changed. Maybe it is possible to backport the fix.

Edit: The diff between 1.14.4 and 19w36a is 14mb in size :thinking:

Edit:
Well they added a check/warning in the world upgrader:
```diff --git a/net/minecraft/util/worldupdate/WorldUpgrader.java b/net/minecraft/util/worldupdate/WorldUpgrader.java
-final CompoundTag id18 = byg15.read(bhd16);
-if (id18 != null) {
-    final int integer19 = ChunkStorage.getVersion(id18);
-    final CompoundTag id19 = byg15.upgradeChunkTag(byn7, () -> this.overworldDataStorage, id18);
+final CompoundTag jd18 = bzu15.read(bii16);
+if (jd18 != null) {
+    final int integer19 = ChunkStorage.getVersion(jd18);
+    final CompoundTag jd19 = bzu15.upgradeChunkTag(cad7, () -> this.overworldDataStorage, jd18);
+    final CompoundTag jd20 = jd19.getCompound("Level");
+    final ChunkPos bii17 = new ChunkPos(jd20.getInt("xPos"), jd20.getInt("zPos"));
+    if (!bii17.equals(bii16)) {
+        WorldUpgrader.LOGGER.warn("Chunk {} has invalid position {}", bii16, bii17);
+    }
```

**Comment by Gerrygames** [comment]
It's definitely not caused by the newer Paper version. The issue seems to be occurring increasingly often even with the older Paper version.
Pretty sure this is not a Paper issue then, but a vanilla one. If someone could look into the issue and maybe create a fix for it, that would still be awesome.

**Comment by Gerrygames** [comment]
I copied the RegionFile code from 1.15-pre4 to Paper 1.14.4 and it seems to be fixed. At least nobody reported further issues so far.

Edit: Nope it‘s not fixed. Since the RegionFile code is the only thing they changed the bug will most likely still exist in 1.15 vanilla.

**Comment by KenaiTheWolf** [comment]
You may have a corrupted world file, I recently experienced this and had to revert to an old copy of the world to fix it. The next sever reboot I did created a long repeating error message due to this.

**Comment by Foorcee** [comment]
The error still exists in the 1.15.1

https://bugs.mojang.com/browse/MC-161823

`[13:41:47] [Server thread/INFO]: Preparing start region for dimension '20f49fc3-c6e4-4722-8630-6c6fcc531418'/minecraft:overworld
[13:41:47] [Server thread/ERROR]: Chunk file at [-5, -2] is in the wrong location; relocating. (Expected [-5, -2], got [-5, -1])
[13:41:47] [Server thread/ERROR]: Chunk file at [-6, -3] is in the wrong location; relocating. (Expected [-6, -3], got [-6, -2])
[13:41:47] [Server thread/ERROR]: Chunk file at [-5, -3] is in the wrong location; relocating. (Expected [-5, -3], got [-4, -5])
[13:41:47] [Server thread/ERROR]: Chunk file at [-4, -3] is in the wrong location; relocating. (Expected [-4, -3], got [-4, -2])
[13:41:47] [Server thread/ERROR]: Chunk file at [-6, -2] is in the wrong location; relocating. (Expected [-6, -2], got [-3, -6])
[13:41:47] [Server thread/ERROR]: Chunk file at [-4, -2] is in the wrong location; relocating. (Expected [-4, -2], got [-3, -4])
[13:41:47] [Server thread/ERROR]: Chunk file at [-6, -1] is in the wrong location; relocating. (Expected [-6, -1], got [-1, -6])
[13:41:47] [Server thread/ERROR]: Chunk file at [-5, -1] is in the wrong location; relocating. (Expected [-5, -1], got [-2, -5])
[13:41:47] [Server thread/ERROR]: Chunk file at [-4, -1] is in the wrong location; relocating. (Expected [-4, -1], got [-1, -4])`

**Comment by Foorcee** [comment]
![00F44626-0EC2-40D7-8386-3439B83B4A40](https://user-images.githubusercontent.com/5587062/72799048-a2809580-3c44-11ea-9684-0d2bb17bf76a.jpeg)


Since we used the fix from @Spottedleaf , it seems to be better, but not fixed yet

**Comment by electronicboy** [comment]
> Start a second client, open the previous world

That's client specific, nothing to do with the server (and that one is somewhat obviously going to create issues if they're opening the same world in two seperate client instances...)

There has been additional stuff added to try to debug what is going on here in recent builds, we don't really have any form of way of replicating this yet, however

**Comment by e-im** [comment]
Closing as stale/no reproduction-- if anyone is still experiencing this on 1.17, leave a comment.
