### ISSUE TITLE
Server Crash (Exception generating new chunk)

### ISSUE THREAD

**Issue by Lusteroth** [PaperMC/Paper#2717]
### Link/paste of stack trace

   https://pastebin.com/9baGXxt2

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

https://pastebin.com/gziM85k7

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

None

### Actions to reproduce (if known): 
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

I don't know how to reproduce. If the player joins, the server crashes.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

Build 234 (1.14.4)

**Comment by Chew** [comment]
Expired paste and vague issue. Was likely fixed in newer versions. If you're still experiencing this on a supported version and can reliably reproduce it, please open a new issue. Thanks for the report!
