### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by foxi69** [PaperMC/Paper#272]
**The following are 'hard suggestions': if you have the information
available to you, you really should put it in the report. Choose one of
the following templates from below that best fits the issue you wish to
report.**
# Performance issue

**_This section should be used for any report regarding performance issues**_
### Timings or Profile link:

**_We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real
cause of the issue.**_

https://timings.aikar.co/v2/d=3d477da2db25456184861d88284be6b4
### Description of issue:

**_If applicable**_

http://pastebin.com/RMUJJ90P
### Plugin list:

08.05 15:23:44 [Server] INFO Plugins (45): RedstoneClockPreventer, WorldEdit, SimpleTrading, TitleMotd, PlaceholderAPI, AnimatedNames, ChatControl, ActionHealth, ProtocolLib, NoCheatPlus, SkinsRestorer, iDisguise, getID, PermissionsEx, TreeAssist, Tab, Lottery, CustomBot, FAQ, Vault, LightAPI, ShopGUIPlus, Orebfuscator4, Essentials, SexyMotd, BattlePets, Jobs, PlotSquared, Multiverse-Core, Holograms, DeluxeChat, TreasureChest, HeavySpleef, AncientGates, CraftBook, ServerSigns, EssentialsSpawn, GriefPrevention, AuthMe, Paintball, MobArena, ProtectionLib, Regenerator, FurnitureLib, DiceFurniture
### bukkit.yml, spigot.yml, paper.yml, server.properties

**_Gist/pastebin/hastebin links**_
### Other helpful links

**_The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.**_

> # This is the main configuration file for Paper.
> # As you can see, there's tons to configure. Some options may impact gameplay, so use
> # with caution, and make sure you know what each option does before configuring.
> # 
> # If you need help with the configuration or have any questions related to PaperSpigot,
> # join us at the IRC.
> # 
> # IRC: #paperspigot @ irc.spi.gt ( http://irc.spi.gt/iris/?channels=PaperSpigot )
> # Wiki: https://paper.readthedocs.org/
> # Paper Forums: https://aquifermc.org/

config-version: 9
settings:
  load-permissions-yml-before-plugins: false
  limit-player-interactions: true
  sleep-between-chunk-saves: false
  region-file-cache-size: 256
  enable-player-collisions: false
timings:
  enabled: true
  verbose: true
  server-name-privacy: true
  hidden-config-entries:
- database
- settings.bungeecord-addresses
  history-interval: 300
  history-length: 3600
  world-settings:
  default:
    verbose: true
    generator-settings:
      canyon: true
      caves: true
      dungeon: true
      fortress: true
      mineshaft: true
      monument: true
      stronghold: true
      temple: true
      village: true
      flat-bedrock: false
    allow-block-location-tab-completion: true
    use-vanilla-world-scoreboard-name-coloring: false
    spawner-nerfed-mobs-should-jump: false
    optimize-explosions: true
    mob-spawner-tick-rate: 60
    portal-search-radius: 128
    max-mob-spawn-attempts: 50
    squid-spawn-height:
      minimum: 45.0
      maximum: 63.0
    max-growth-height:
      cactus: 3
      reeds: 3
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 900
    despawn-ranges:
      soft: 32
      hard: 128
    falling-block-height-nerf: 0
    tnt-entity-height-nerf: 0
    water-over-lava-flow-speed: 5
    fast-drain:
      lava: false
      water: false
    lava-flow-speed:
      normal: 30
      nether: 10
    lootables:
      auto-replenish: false
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
    disable-teleportation-suffocation-check: false
    use-chunk-inhabited-timer: true
    keep-spawn-loaded-range: 8
    nether-ceiling-void-damage: true
    allow-non-player-entities-on-scoreboards: false
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
    grass-spread-tick-rate: 1
    fix-cannons: false
    game-mechanics:
      disable-chest-cat-detection: true
      disable-end-credits: true
    non-player-arrow-despawn-rate: 3000
    disable-explosion-knockback: false
    use-hopper-check: false
    baby-zombie-movement-speed: 0.5
    all-chunks-are-slime-chunks: false
    allow-leashing-undead-horse: false
    container-update-tick-rate: 1
    keep-spawn-loaded: true
    queue-light-updates: false
    disable-thunder: false
    skeleton-horse-thunder-spawn-chance: -1.0
    disable-ice-and-snow: false
    fire-physics-event-for-redstone: false

> # This is the main configuration file for Spigot.
> # As you can see, there's tons to configure. Some options may impact gameplay, so use
> # with caution, and make sure you know what each option does before configuring.
> # For a reference for any variable inside this file, check out the Spigot wiki at
> # http://www.spigotmc.org/wiki/spigot-configuration/
> # 
> # If you need help with the configuration or have any questions related to Spigot,
> # join us at the IRC or drop by our forums and leave a post.
> # 
> # IRC: #spigot @ irc.spi.gt ( http://www.spigotmc.org/pages/irc/ )
> # Forums: http://www.spigotmc.org/

config-version: 8
settings:
  player-shuffle: 0
  filter-creative-items: true
  user-cache-size: 1000
  int-cache-limit: 1024
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-multiplier: 10.0
  timeout-time: 60
  restart-on-crash: true
  restart-script: ./start.sh
  netty-threads: 4
  attribute:
    maxHealth:
      max: 2500.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
  bungeecord: false
  late-bind: false
  sample-count: 12
  save-user-cache-on-stop-only: false
  debug: false
  moved-too-quickly-threshold: 100.0
commands:
  spam-exclusions:
- /skill
  silent-commandblock-console: true
  replace-commands:
- setblock
- summon
- testforblock
- tellraw
  log: true
  tab-complete: 1
  messages:
  restart: Szerver újraindul, kérlek várj...
  whitelist: Nem vagy rajta a whitelisten.
  unknown-command: Ismeretlen parancs. Használd a "/help" paracsot, ha segítség kell.
  server-full: A szerver tele van!
  outdated-client: Régi verziójú kliensed frissítsd {0}-re/ra!
  outdated-server: A szerver sajnos még régebbi verzión fut! ( {0} )
  stats:
  disable-saving: false
  forced-stats: {}
  world-settings:
  default:
    verbose: true
    nerf-spawner-mobs: false
    growth:
      cactus-modifier: 800
      cane-modifier: 800
      melon-modifier: 800
      mushroom-modifier: 800
      pumpkin-modifier: 800
      sapling-modifier: 800
      wheat-modifier: 800
      netherwart-modifier: 800
    entity-activation-range:
      animals: 32
      monsters: 32
      misc: 16
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
    ticks-per:
      hopper-transfer: 8
      hopper-check: 8
    hopper-amount: 1
    save-structure-info: true
    max-entity-collisions: 8
    mob-spawn-range: 4
    dragon-death-sound-radius: 0
    seed-village: 10387312
    seed-feature: 14357617
    hunger:
      walk-exhaustion: 0.2
      sprint-exhaustion: 0.8
      combat-exhaustion: 0.3
      regen-exhaustion: 3.0
    max-tnt-per-tick: 100
    max-tick-time:
      tile: 1000
      entity: 1000
    item-despawn-rate: 3000
    merge-radius:
      item: 4
      exp: 6
    arrow-despawn-rate: 1200
    enable-zombie-pigmen-portal-spawns: true
    wither-spawn-sound-radius: 0
    view-distance: 8
    hanging-tick-frequency: 100
    zombie-aggressive-towards-villager: true
    random-light-updates: false

> # Minecraft server properties
> # Sun May 08 15:07:56 CEST 2016
> 
> spawn-protection=0
> server-name=OperationCraft
> generator-settings=
> force-gamemode=false
> allow-nether=false
> gamemode=0
> broadcast-console-to-ops=false
> enable-query=false
> player-idle-timeout=0
> difficulty=1
> spawn-monsters=true
> op-permission-level=4
> announce-player-achievements=false
> pvp=true
> snooper-enabled=false
> level-type=DEFAULT
> hardcore=false
> enable-command-block=true
> max-players=200
> network-compression-threshold=512
> resource-pack-sha1=
> max-world-size=29999984
> server-port=25566
> debug=false
> server-ip=79.172.205.214
> spawn-npcs=true
> allow-flight=false
> level-name=world
> view-distance=8
> resource-pack=
> spawn-animals=true
> white-list=false
> generate-structures=true
> online-mode=false
> max-build-height=256
> level-seed=
> use-native-transport=true
> enable-rcon=false
> motd=OperationCraft
### Paper build number:

**_This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.**_

724

**Comment by foxi69** [comment]
what I configured wrong?

**Comment by zachbr** [comment]
Your server stopped responding, and was killed, because of regex lookups by Regenerator.

**Comment by StargateMC** [comment]
Hi @Zbob750 - Regenerator doesn't perform any regex lookups at all. 

Regards
Bysokar

**Comment by Spottedleaf** [comment]
@Zbob750 
It is actually snakeyml, not the plugin directly.

@DraksterAU 
The issue will most likely remain closed. An external plugin caused this crash, because it was most likely **loading a large config** from **disk**.

Tell the author to not perform I/O on the main thread.

**Comment by StargateMC** [comment]
I am the author.
So to fix this (which only happens on slow servers), I should be loading config async, which I am....?

**Comment by NachtRaben** [comment]
Not necessarily Async, but using the runTaskAsynchronously in the scheduler would be more than adequate.

**Comment by StargateMC** [comment]
That's exactly what I'm doing.

**Comment by StargateMC** [comment]
@foxi69 please zip your regenerator directory up and send to me. I'll debug.

Thanks all.

**Comment by Spottedleaf** [comment]
@DraksterAU 

As shown by the stack trace, you are loading a config here:
com.draksterau.Regenerator.listeners.eventListener.onChunkUnload(eventListener.java:67)

This is not the place to discuss this. Take this report to a place where you can manage it.

**Comment by zachbr** [comment]
As far as PaperMC is concerned, this is an issue with Regenerator and should be moved to their preferred channel for discussion and resolution.

Thanks.
