### ISSUE TITLE
Expand i18N localization API

### ISSUE THREAD

**Issue by zachbr** [PaperMC/Paper#2720]
Right now the API is only exposed on [ItemStacks](https://papermc.io/javadocs/paper/1.14/org/bukkit/inventory/ItemStack.html#getI18NDisplayName--), not materials and other places it could be useful.
Furthermore, there is no way to use an alternative language other than the en_US localization file that ships as part of the vanilla jar. In an ideal world, it would be possible to use an external file for other languages or per-server changes.

There have also been requests to get the raw translation keys (ie `block.minecraft.melon`) for use and storage, rather than just immediately returning the translated string.

Additional research and time is needed to explore the possibilities here.

**Comment by mikroskeem** [comment]
Getting the raw translation key should be as trivial as adding one or more OBFHELPERs, I've done that before.

If 1.15 lands here, then I'll upstream my changes.

**Comment by ravkr** [comment]
Any updates @mikroskeem?

**Comment by mikroskeem** [comment]
Completely forgot about it

**Comment by yannicklamprecht** [comment]
Regarding missing language file on server side. We could automatically add these language files as resource bundles of by a system using yaml.
Here is a script to automatically download the latest language file from Mojang directly.
Tools used: cURL and jq
https://gist.github.com/yannicklamprecht/c764fa6ffddde69137fd846728676b47
This could be integrated into the Paper build process or ported to Java to download language file on the fly based on players playing on the server.

**Comment by yannicklamprecht** [comment]
Not stale and the adventure has begun.

**Comment by qixils** [comment]
It's now possible to get [raw translation keys](https://github.com/PaperMC/Paper/pull/4016) (with some [caveats](https://github.com/PaperMC/Paper/issues/4600)) but it remains impossible to get translated strings for languages other than English. While this may be seen as unnecessary with recent adoption of Adventure, I'd argue it could still be appreciated for debug logging, non-translatable text fields like player names on scoreboards, sending death messages to an external service (such as a discord channel), etc.

**Comment by Machine-Maker** [comment]
The server only comes with English translations. You’d have to provide your own set of Minecraft’s translation files if you want other languages. Idk the legality situation around that tho.

**Comment by qixils** [comment]
As mentioned earlier in the thread, it's easy to download language assets from Mojang's servers which I believe would not impose any license issues as long as it's performed at runtime.

It may not be ideal to download all files by default though. Perhaps a config option for whitelisted languages could be added, and/or an option to only download language files used by online players (assuming the server can access that information? Not sure off the top of my head)

**Comment by electronicboy** [comment]
The server is sent the locale of the client but so far into the login process that it's practically a joke of a feature, managing resources external to us gets a bit iffy as you need to have the capacity to track these files and know when they're updated, so it's not just as simple as downloading them

We are welcoming PRs for this as this is not a high priority for us, but, there are definitely still issues/concerns which need to be addressed, I think somebody was working on a script to pull them all into the build process but there was some concerns around that approach

**Comment by yannicklamprecht** [comment]
> The server is sent the locale of the client but so far into the login process that it's practically a joke of a feature, managing resources external to us gets a bit iffy as you need to have the capacity to track these files and know when they're updated, so it's not just as simple as downloading them
> 
> We are welcoming PRs for this as this is not a high priority for us, but, there are definitely still issues/concerns which need to be addressed, I think somebody was working on a script to pull them all into the build process but there was some concerns around that approach

Jep, I did but closed it because of two reasons:
- legality
- adventure has superseded my intent


The code could be extracted to a little lib that provides these files on request, falls back to English if file has to be downloaded first, after finishing replace the handle for that.

**Comment by Owen1212055** [comment]
This could be prolly closed in favor of https://github.com/PaperMC/Paper/issues/3257

Adventure has covered majority of this PR, and switching out the language instead of English is the main focus of the previously mentioned PR (which is also mentioned here a bit).

**Comment by Machine-Maker** [comment]
Closing for reasons Owen stated. The `Translatable` interface has been implemented in a bunch of places, with PRs to add it to more.
