### ISSUE TITLE
Server crash at spartan kick

### ISSUE THREAD

**Issue by jj136975** [PaperMC/Paper#2722]
https://pastebin.com/A8cbxsLM

**Comment by jj136975** [comment]
is it plugin issue or paper ?

**Comment by ninja-** [comment]
this looks like issue in procosmetics

**Comment by jj136975** [comment]
yup, I'm trying removing it, I'll tell you more info if it still crashing

**Comment by jj136975** [comment]
Still crashing https://pastebin.com/byfZhvVr

**Comment by HexedHero** [comment]
TacoSpigot 1.8.8, stop replying. We don't support 1.8.

**Comment by Draycia** [comment]
You should probably also ask TacoSpigot for support if you're using their fork.
Just like you don't go to Spigot for support with Paper.
