### ISSUE TITLE
Server crash suddenly

### ISSUE THREAD

**Issue by jj136975** [PaperMC/Paper#2723]
Here is the crash report https://pastebin.com/byfZhvVr

Thx for help if you find anything.

**Comment by Draycia** [comment]
We just told you 1.8.8 isn't supported and to ask TacoSpigot for support.

If you're using extremely outdated versions you're expected to provide your own support.

**Comment by MiniDigger** [comment]
its pretty trival to see which plugin is causing issues. if you are not able to do that, you shouldnt run ancient unsupported software.

**Comment by jj136975** [comment]
But I have exactely the same errors on Paper and on Spigot

**Comment by MiniDigger** [comment]
because this is neither a paper nor a spigot issue.

**Comment by jj136975** [comment]
So how can I fix it ?

**Comment by Draycia** [comment]
You're conveniently ignoring where I said 1.8.8 isn't supported.

**Comment by jj136975** [comment]
kk ...
