### ISSUE TITLE
Impossible to download the latest Paper versions (234 & 235)

### ISSUE THREAD

**Issue by aurel85** [PaperMC/Paper#2724]
Hi,

Since version 234 (with version 233 everything is ok) I can not download Paper, I have this error :

{"error":{"code":404,"message":"Could not locate build"}}

I download here : https://papermc.io/downloads

Am I the only one ?

Thank you in advance.

**Comment by electronicboy** [comment]
modify the url and use /latest in place of the build number

**Comment by aurel85** [comment]
It's ok, thank you !
