### ISSUE TITLE
Killing villagers yields kill message in console

### ISSUE THREAD

**Issue by StealWonders** [PaperMC/Paper#2734]
### What behaviour is expected:
No kill / death message in console like it was all versions below

### What behaviour is observed:
`[20:15:44 INFO]: Villager EntityVillager['Villager'/666, uuid='8885beb2-abb7-4f4f-a29b-aca4ce356ed8', l='world', x=367.50, y=70.00, z=88.38, cx=22, cz=5, tl=734, v=true, d=false] died, message: 'Villager was slain by StealWonders'`

### Steps/models to reproduce:
Kill a villager :-)

### Plugin list:
EssentialsX

### Paper build number:
git-Paper-1 (MC: 1.15)

### Anything else:
I like cats

**Comment by electronicboy** [comment]
Intentional https://bugs.mojang.com/browse/MC-165985

**Comment by StealWonders** [comment]
I guess for science we can keep it then :P 
Closing this

**Comment by Black-Hole** [comment]
Spigot added an option "settings.log-villager-deaths" for this. After next upstream merge it should work on Paper, too.

**Comment by electronicboy** [comment]
I was debating on adding a setting for this, but the fact that villagers going missing has been an odd complaint here and there, figured it would be best to leave it in... Whatever, I guess...
