### ISSUE TITLE
No ageables work (nothing grows)

### ISSUE THREAD

**Issue by hostadam** [PaperMC/Paper#2736]
# What behaviour is observed:
Cactus, sugarcane, kelps, cocoa beans do not grow, at all.

### Plugin list:

BuycraftX, CoreProtect, Crates, Dynmap, GeoBase, GeoEnchants, GeoFactions, IPWhitelist, Missions, Multiverse, PlugMan, Votifier, WorldBorder, WorldEdit

### Paper build number:
git-Paper-3 (MC: 1.15)

**Comment by kompetenzbolzen** [comment]
Same here with no plugins.

**Comment by Primorior** [comment]
lol can confirm

Edit: Seems to work on git-Paper-2 (1.15)
