### ISSUE TITLE
Anti Xray chunks disappear and reappear

### ISSUE THREAD

**Issue by LucidAPs** [PaperMC/Paper#2737]
### What behaviour is expected:
The anti xray works fine with the default settings

### What behaviour is observed:
When i stand still and i turn and move the camera chunks disappear and reappear is that normal?

No plugins , paper 1.15 build #4

https://i.imgur.com/uqdcw9m.mp4

**Comment by electronicboy** [comment]
Clientside rendering ha nothing to do with the server
