### ISSUE TITLE
Nether portals on top of the Nether roof don't work

### ISSUE THREAD

**Issue by SpeedCuberMK** [PaperMC/Paper#2739]
as of 1.15, nether portals on top of the nether should work just like every portal in the nether, but they are working the same as they did on 1.14.4 and previous versions, they can take you out of the nether, but they don't work on the way to the nether.

**Comment by MiniDigger** [comment]
Tested with spigot and vanilla?

**Comment by VacantFiend** [comment]
https://bugs.mojang.com/browse/MC-160677

Works in vanilla/spigot AND paper from my testing.
https://streamable.com/o2i22

**Comment by magicus** [comment]
I'm using paper 1.51.1 build 42, and this works fine for me. Either the issue has beeen resolved, or there is some additional problem with the OPs setup.

**Comment by Ronynkai** [comment]
I am having this issue sporadically as well. Running Paper 1.15.2 build 93 (I have it auto updating). One of my players' nether portal will not link to his portal going into the nether, it just drops him off without generating a portal. From the nether back, it's no problem.

**Comment by Proximyst** [comment]
Works fine in 1.16.2. Minecraft will _not_ generate portals above the nether, but will happily link to them.
