### ISSUE TITLE
1.15 join/leave messages

### ISSUE THREAD

**Issue by AsVaidas** [PaperMC/Paper#2741]
Paperspigot doesn't hide join/leave messages even if it was programmed

`
	@EventHandler
	public void onPlayerJoin(PlayerJoinEvent e) {
		e.setJoinMessage(null);`

**Comment by Aaron2550** [comment]
Why'd you close it?

**Comment by AsVaidas** [comment]
> Why'd you close it?

Opened a ticket without further testing. 
My plugin class that handles those messages didn't load because one plugin wasn't loading
So yea, it's not an issue, and I don't know how to remove a ticket completely
