### ISSUE TITLE
spectating an entity doesn't work and teleports you randomly

### ISSUE THREAD

**Issue by justEli** [PaperMC/Paper#2743]
### What behaviour is expected:
___What you expected to see___
When hitting an entity in spectator mode, it would share the screen of that entity.

### What behaviour is observed:
___What you actually saw___
When hitting an entity in spectator mode, your screen starts to shake, you see the sky only, and when you leave the entity, it randomly teleports you.
Console is being spammed with: (JustEli is spectating an entity)
![image](https://user-images.githubusercontent.com/8517465/70847831-5a15d100-1e69-11ea-9850-d73abb29e39d.png)

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
https://i.imgur.com/UFNruvH.mp4
In spectator, hitting this player, screen starts to shake (and low fps), doesn't share screen of entity, and then Shift to escape teleports me somewhere.

### Plugin list:
___A list of your plugins___
None that affect spectating entities.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
1.15 Paper-8

### Anything else:
___Anything else you think may help us resolve the problem___
Worked fine when I was using Spigot 1.15 yesterday.

**Comment by stefvanschie** [comment]
More info regarding this issue on git-Paper-14. The screen shaking doesn't always happen: sometimes the screen stays in place normally and follows the entity as should happen, sometimes I'm stuck in place and sometimes the world around me is invisible (excluding entities). Exiting the entity is troublesome, sometimes I'm stuck in one spot, unable to move (re-connecting fixes this); on other occasions I get teleported to a 'random' spot. From my testing this randomness seems to be rather specific however: the x coordinate will be 69, the y coordinate the same as the spectating entity and the z coordinate the same as the spectating entity as well. Note that these relative coordinates are copied correctly from the entity's current location, even if you as the spectator are stuck in one spot. I'm uncertain why these numbers (more specifically why this 69 on the x-axis).
I've encountered this behavior across a variety of entities: pigs, cats, cows, horses and chickens.

I'll try to do some more testing, also across Vanilla, CB and Spigot.

Edit: the console spamming also seems to not be consistent: sometimes it occurs, others it doesn't.

**Comment by stefvanschie** [comment]
This bug does not appear on Vanilla 1.15, CB 1.15, Spigot 1.15 or Paper 1.14.4 (236).

**Comment by stefvanschie** [comment]
I think patch 0316 is at error here. Not too familiar, but there's at least a call in there with the wrong coordinates (y, y, z instead of x, y, z; see line 56 of the patch). I doubt that causes all this behavior, though, but probably a good starting point.

**Comment by MiniDigger** [comment]
now that cat fixed my derp, can you retest please?

**Comment by JustEli** [comment]
Still seems to teleport the spectating player to a different player than the one they were spectating, when leaving(?)

**Comment by justEli** [comment]
I think it's all fixed, thanks!

**Comment by MiniDigger** [comment]
close this issue then please :)
