### ISSUE TITLE
Server crashing in 1.15

### ISSUE THREAD

**Issue by perseus5** [PaperMC/Paper#2746]
### Link/paste of stack trace
https://pastebin.com/DQimHZER

### Plugin list:
___A list of your plugins___
BuycraftX, Citizens, CoreProtect, Holograms*, LockettePro, mcMMO, MCore, mSurvival, spark, ViaVersion*, WorldEdit, WorldGuard
### Actions to reproduce (if known):
No idea.

### Paper build number:
14.12 17:16:37 [Server] INFO This server is running Paper version git-Paper-"0585f99b" (MC: 1.15) (Implementing API version 1.15-R0.1-SNAPSHOT)

**Comment by perseus5** [comment]
https://pastebin.com/sEuLnGd3 

I think its caused by flying into unloaded chunks?

**Comment by electronicboy** [comment]
Concurrency issue with the gen code, basically

**Comment by perseus5** [comment]
Anything I can do atm to alleviate it? Keeps crashing the serverrrr 😔
