### ISSUE TITLE
1.14.4 /give with custom NTB tags returns unknown item error

### ISSUE THREAD

**Issue by KenaiTheWolf** [PaperMC/Paper#2749]
### What behaviour is expected:
__When a /give command is run with /give username item{tags} the item should be spawned in the user’s inventory. __

### What behaviour is observed:
___The game returns “unknown item”.___

### Steps/models to reproduce:
___Run this command in a command block:  

/give @p diamond_sword{Enchantments:[{id:"bane_of_arthropods",lvl:10},{id:"fire_aspect",lvl:10},{id:knockback,lvl:10},{id:looting,lvl:10},{id:mending,lvl:1},{id:sharpness,lvl:10},{id:"silk_touch",lvl:1},{id:smite,lvl:10},{id:sweeping,lvl:10},{id:unbreaking,lvl:10}]} 1
__
### Plugin list:
___Occurs with nothing but EssentialsX installed. ___

### Paper build number:
___git-paper-236 MC: 1.14.4 implementing API 1.14.4-R0.1-SNAPSHOT.___

**Comment by electronicboy** [comment]
"occurs with nothing but a plugin which replaces the give command"

**Comment by KenaiTheWolf** [comment]
Using /minecraft:give also results in the same issue.

**Comment by MiniDigger** [comment]
to provide a more helpful response, use /minecraft:give or uninstall essentials if you want to use the vanilla give command.

**Comment by KenaiTheWolf** [comment]
I don’t have the issue with spigot even using EssentialsX. The initial response already left me with a negative experience. Seems like spigot got their stuff in order for 1.15.

**Comment by mikroskeem** [comment]
Huh? You installed a plugin which intentionally overrides /give command and you still expect command block to use the vanilla command instead of overridden one? Or did I understand wrong?

**Comment by KenaiTheWolf** [comment]
I’m aware of this but the issue only started happening when I transitioned from spigot. Worked fine before. The only thing I changed was switching to paper.

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/71136334-6baa0080-21fc-11ea-9de4-1d0ea4ddb817.png)
give is overriden by essentials, meaning that the vanilla command usage is not going to work, you can use command block overrides in commands.yml to redirect a command to the vanilla command. But, there is no difference here in how command blocks work when executing commands vs Spigot here

**Comment by KenaiTheWolf** [comment]
I understand that it overrides it. What I’m saying is I have ALWAYS since 1.7.10 been able to apply NBT tags while addressing the ***essentials command.*** Even up until 1.14, but then I switched APIs to paper and now it’s broken which makes it seem like there’s something on paper’s side going on.

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/71136725-9b0d3d00-21fd-11ea-9d63-375cd9c4dc27.png)

**Comment by mikroskeem** [comment]
Did Essentials even support said feature...?

**Comment by KenaiTheWolf** [comment]
It always has to my knowledge, the only thing it changes is it allows you to use numerical IDs or single word IDs for items.

**Comment by 0-x-2-2** [comment]
> It always has to my knowledge, the only thing it changes is it allows you to use numerical IDs or single word IDs for items.

No, it overwrites the entire command. Any vanilla features will no longer work unless they have been implemented.  You must have been using the vanilla command the entire time because essentials give command does not support NBT tags.

https://github.com/EssentialsX/Essentials/blob/a4182b5ff9c68a073ea993482d815e02eca895f0/Essentials/src/com/earth2me/essentials/commands/Commandgive.java#L28
