### ISSUE TITLE
Agressive Mobs don't spawn without player movement. Paper 1.14.4, no Plugins.

### ISSUE THREAD

**Issue by Onyxtite** [PaperMC/Paper#2750]
### What behaviour is expected:
Agressive mobs should spawn  ~arround the player when he is still during night time, and the spawn cap hasn't been met.

### What you expected to see:
Mobs gradually spawning arround the player during night, even if the player doesn't move.

### What behaviour is observed:
If the players on the server don't move during night time, no agressive mobs will spawn arround them. Nightmares are an exception, if enough nights without sleep have passed. You can actually wait the whole night without getting any spawns.

### Steps/models to reproduce:
-Download the last version of paper.
-Run in an empty folder & accept the eula.
-Connect to the server. 
-Run The commands /gamemode User Creative & /teleport 1000 100 1000 (note, this probably isn't required, but that way we are making sure we aren't being affected by proximity to the spawn point)
-Build a little dirt pillar ~8 blocks , just so you can see better (not necessairy).
-Check to see if there are no agressive mobs on sight, that's usually the case.
-Do /time set night and wait, no agressive creatures will spawn in the whole night
-If you move arround during the night, creatures will spawn.

### Plugin list:
None.

### Paper build number:
This was tested with Paper release 236 (/version output: This server is running Paper version git-Paper-236 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT) ) (this is the last release available at the time of opening this ticket)

### Anything else:
-F3 entity counts give numbers arround 3/30 (though it'd be important to count them via commands, since f3 counts seem to be regional).
-This was tested with java 8, it probably wouldn't make a difference, but just in case it helps.
-This issue occurs even with multiple players (as long as they both stay still), and it also occurs on paper 234.
-The issue remains even if per-player-mob-spawns: true
-The issue does not happen on a single player world.
-The issue remains if changing difficulty to hard via command
-Gamerule doMobSpawning is set to true (its the default value, but i double checked)
-While i haven't investigated them, i've gotten player reports from low mob quantity, specially ghasts in the nether, which if true, could mean that its not related to mobs with lowlightSpawnConditions.
-The issue seems to also be happening on spigot. I used the same procedure, and an old 1.14.4 spigot build (/version returned: This server is running CraftBukkit version git-Spigot-94af569-6ddeb98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT) .You are 38 version(s) behind )
-The same problem also happens with passive mobs, but i only checked that on spigot 1.14.4 (the build in the previous line).
-It'd probably be worth checking if the issue is also happening on craftbukkit, and on later spigot versions, however, I can't do it right now, so if someone would like to, it'd be really helpful.
-I've tried changing the following setting on bukkit.yml, and it seems to allow monsters to spawn on paper 1.14.4 build 236 (although in low quantity). I'll continue investigating with changing other settings.
  spawn-limits:
    monsters: 150
-Acording to this expanding the mob Spawn Range above 8 wouldn't change anything,  https://www.spigotmc.org/threads/what-exactly-does-mob-spawn-range-do.176889/ however, i've tried reducing it to 4 and the spawn rate seem to increase dramatically (while simultaniously using monsters: 150)
-This post was a bit helpful on my investigation: https://papermc.io/forums/t/mob-spawning-issues-1-14-4/2096

**Comment by Chew** [comment]
Hello! Been a while since this beautifully, well crafted report was filed. However, I was not able to reproduce this error on the latest 1.16.2 build. I ensured to follow all of your steps, though when you specify "moving" I'm not sure if you meant head moving or actually physical x,y,z location, so I was sure to do neither. I didn't see a lot of mobs spawning but I did hear a zombie from behind me. If you do somehow manage to have this issue on 1.16.2, feel free to open a brand new issue and we will be sure to look into it more. Thank you for the report and have a good day!

**Comment by Onyxtite** [comment]
For future reference, by moving, i meant xyz movement. Right now i'm really busy so i can't do extensive testing.
I'll do extensive testing when i have the chance, if I encounter the bug again,  but hopefully it's been resolved by some update. 
Thanks for getting back to me!

**Comment by electronicboy** [comment]
Player movement has 0 tie on mob spawning unless something with screwing with the server, only real "risk" there is that you hit the mob cap, but they're all underground hiding, etc

**Comment by Onyxtite** [comment]
@electronicboy It may not have direct ties, but when you move you load chunks and I believe that does cause mobs to spawn. However the problem reported here is that mobs didn't spawn if you just stood still the whole night, and if you did the same thing in vanilla, mobs would spawn. Still though, i'll retest on a later day.
