### ISSUE TITLE
prevent-moving-into-unloaded-chunks

### ISSUE THREAD

**Issue by MrEDok** [PaperMC/Paper#2752]
### What behaviour is expected:
prevent player from moveing into unloaded chunk

### What behaviour is observed:
flying really fast 200bps into unloaded chunk

### Plugin list:
ChatCo*, DeathMessagesPrime, DiscordSRV, FarmLimiter, PermissionsEx*, PlaceholderAPI, RandomSpawn*, ServerAge*, spark, Specterium, SpecteriumJD, TAB

### Paper build number:
 git-Paper-6 (MC: 1.15)

### Anything else:
https://streamable.com/1xpyx

**Comment by Spottedleaf** [comment]
requires https://github.com/PaperMC/Paper/blob/master/removed/1.15/0399-Use-getChunkIfLoadedImmediately-in-places.patch and https://github.com/PaperMC/Paper/blob/master/removed/1.15/0410-Reduce-sync-loads.patch to work

**Comment by kickash32** [comment]
These patches have been added into 1.15 now.
