### ISSUE TITLE
Zero Tick Farms Dissabled despite fix-zero-tick-instant-grow-farms value

### ISSUE THREAD

**Issue by DollarSignSubjectNameHere** [PaperMC/Paper#2754]
### What behavior is expected:
Zero tick farms to have vanilla functionality when `fix-zero-tick-instant-grow-farms:` is false

### What behavior is observed:
Zero tick farms are disabled regardless of setting

### Steps/models to reproduce:
[build guide](https://youtu.be/2wVzDC4bsZk?t=426)

### Plugin list:
Dynmap-3.0-beta-7-spigot
ImageMaps

### Paper build number:
`This server is running Paper version git-Paper-8 (MC: 1.15) (Implementing API version 1.15-R0.1-SNAPSHOT)`

**Comment by DollarSignSubjectNameHere** [comment]
[paper.yml](https://pastebin.com/vxfMCfKs)

**Comment by zachbr** [comment]
Vanilla made their own changes that likely broke many (but not all) designs. Double check that any cases actually work on a vanilla server.

**Comment by DollarSignSubjectNameHere** [comment]
the design works in vanilla single player

**Comment by VacantFiend** [comment]
https://streamable.com/7x96m

**Comment by DollarSignSubjectNameHere** [comment]
https://streamable.com/t9bc5

**Comment by VacantFiend** [comment]
Line 85 of your paper.yml if you didn't fix it already but that shouldn't make them pop off.
`fix-zero-tick-instant-grow-farms: true`

Try moving the pistons below instead of above. That can cause that issue. Looking at your pistons they seem to be firing slower than they should so i'm thinking that's what it is.

**Comment by DollarSignSubjectNameHere** [comment]
yep that was the issue @VacantFiend  sorry for this
