### ISSUE TITLE
Citizens error

### ISSUE THREAD

**Issue by Cerexus** [PaperMC/Paper#2756]
I changed the Server Software from spigot to paper and my log got spammed with Errors from citizens.

I cant use Citizens and Paper with my Setting. Spigot works fine with the same Settings.

### Steps/models to reproduce:

Just use my Citizens Folder and any of the 1.15 Alpha Releases.

### Paper build number:
http://prntscr.com/qb4u9q

Files to reproduce:

[citizens_error.zip](https://github.com/PaperMC/Paper/files/3965096/citizens_error.zip)

**Comment by electronicboy** [comment]
please provide log files...

**Comment by Cerexus** [comment]
[2019-12-15-5.log](https://github.com/PaperMC/Paper/files/3965100/2019-12-15-5.log)
ah sorry

**Comment by kickash32** [comment]
looks like a plugin issue, one of the NPC's on an attribute somehow and it keeps triggering a NPE. Contact the plugin author for a fix or try to track the NPC down and recreate it.

**Comment by electronicboy** [comment]
was https://github.com/CitizensDev/Citizens2/issues/1995
