### ISSUE TITLE
1.15 16GB not enough?

### ISSUE THREAD

**Issue by AsVaidas** [PaperMC/Paper#2759]
### Link/paste of stack trace
https://kaimux.lt/crash/

### Plugin list:
[19:39:43] [Server thread/INFO]: Plugins (36): AdminSystem, AdvancedBan*, AsVaidasAPI, AwesomeSnow*, ChestSort, CompatNoCheatPlus, ConditionalCommands, CrazyCrates, DiamondAnticheat, Factions, FactionWars, GroupManager, Idea, IllegalStack, mcMMO, MobOptimizer, MyCommand, NoCheatPlus, Packages, PlaceholderAPI, PlugMan*, ProtocolLib, RanksTime, SkinsRestorer, TAB, TPSmeter, TryMe, Updates, WorldEdit, WorldFiller, ZC-lock, ZCLogin, ZCMessages, ZCSurvivalCore, ZCTops, ZCTrade

### Actions to reproduce (if known):
50 players in the server and uptime for up to 1 hour

### Paper build number:
![image](https://user-images.githubusercontent.com/5215112/70866481-d1835780-1f72-11ea-9c5d-b9b00422c641.png)

15GB for the server, 16GB host, and it's crashing because of not enough ram. Does 1.15 use 2x ram than 1.14?

**Comment by electronicboy** [comment]
Your OS needs ram too, java also uses memory outside of Xmx.

**Comment by AsVaidas** [comment]
> Your OS needs ram too, java also uses memory outside of Xmx.

I know that, I changed to 15GB today, it was crashing with 12GB for server, 4GB left for host

**Comment by lukeeexd** [comment]
> > Your OS needs ram too, java also uses memory outside of Xmx.
> 
> I know that, I changed to 15GB today, it was crashing with 12GB for server, 4GB left for host

Use 10GB

**Comment by AsVaidas** [comment]
> > > Your OS needs ram too, java also uses memory outside of Xmx.
> > 
> > 
> > I know that, I changed to 15GB today, it was crashing with 12GB for server, 4GB left for host
> 
> Use 10GB

And then it won't crash? Because 1.14.4 didn't crash with 12GB

**Comment by lukeeexd** [comment]
> > > > Your OS needs ram too, java also uses memory outside of Xmx.
> > > 
> > > 
> > > I know that, I changed to 15GB today, it was crashing with 12GB for server, 4GB left for host
> > 
> > 
> > Use 10GB
> 
> And then it won't crash? Because 1.14.4 didn't crash with 12GB

https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

**Comment by electronicboy** [comment]
This issue tracker is not for support, nor are we going to run through your log files for you. If you want to ask questions, use the discord, but we can't debug memory issues for you.

**Comment by AsVaidas** [comment]
> This issue tracker is not for support, nor are we going to run through your log files for you. If you want to ask questions, use the discord, but we can't debug memory issues for you.

1.14.4 didn't have it, 1.15 crashes every day for 30 times. Is it really my problem and it doesn't have anything to do with 1.15 o spigot/paperspigot?



> > > > > Your OS needs ram too, java also uses memory outside of Xmx.
> > > > 
> > > > 
> > > > I know that, I changed to 15GB today, it was crashing with 12GB for server, 4GB left for host
> > > 
> > > 
> > > Use 10GB
> > 
> > 
> > And then it won't crash? Because 1.14.4 didn't crash with 12GB
> 
> https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

Tried, lagged my server to 13 tps avarage

**Comment by electronicboy** [comment]
You have yet to show a crash report which shows that this is not an issue with your configuration, i.e. not the OS running out of memory. We are not going to run through all the log files you've thrown into a folder.
