### ISSUE TITLE
Server chunk load deadlock (async loading)

### ISSUE THREAD

**Issue by weaondara** [PaperMC/Paper#2760]
### Link/paste of stack trace
https://waste.cutiepie.at/dcw8qw6oyae81woh

### Plugin list:
AsyncWorldEdit, BungeePerms*, Citizens, CleanroomGenerator*, Essentials, EssentialsSpawn, FarmweltResetter, LogBlock, Multiverse-Core, Multiverse-NetherPortals, PluginChannel*, PluginUtilitiesLib, ProtocolLib, Stargates, WorldEdit, WorldGuard
Citizens is on latest as of writing this (2.0.26-SNAPSHOT (build 1790))

### Actions to reproduce (if known):
place a citizen npc on a world
regenerate the map with multiverse
async load the chunk the npc is located
wait for crash report

### Further elaboration:
We have a farm world resetter plugin. The reset is done via Multiverse regenWorld. After that some chunks are loaded (generated) async (code below). This world also contains Citizens npc located in these chunks. When the chunk (containing the npc) is loaded Citizens tries to spawn that npc. In the spawn function (linked below) Citizens calls getChunk() of the Location of the npc and the server deadlocks everytime. The chunk in question is (30,-1). It is loaded before indicated by `[19:26:26] [Server thread/INFO]: [Farmweltresetter] =DEBUG= Loaded chunk x/z=(30,-1)`.
This chunk is then accessed by Citizens.
I did some code digging into citizens. The crash is initiated here: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/npc/CitizensNPC.java#L233

Code:
The Code is run by an async Thread.
```
List<Point2D> toload = new ArrayList();
for (int x = min.getBlockX() - 32; x <= max.getBlockX() + 32; x += 16)
    for (int z = min.getBlockZ() - 32; z <= max.getBlockZ() + 32; z += 16)
        toload.add(new Point2D(x >> 4, z >> 4));

//load chunks async and wait
Object lock = new Object();
Consumer<Chunk> consumer = new Consumer<Chunk>()
{
    int loaded = 0;

    @Override
    public void accept(Chunk t)
    {
        loaded++;
        t.addPluginChunkTicket(FarmweltResetter.getInstance());
        Logging.debug("Loaded chunk x/z=(" + t.getX() + "," + t.getZ() + ")");
        if (loaded == toload.size())
        {
            Logging.debug("Spawn chunks loaded");
            synchronized (lock)
            {
                lock.notify();
            }
        }
    }
};

//load chunks and wait till finished
if (!toload.isEmpty())
    synchronized (lock)
    {
        Logging.debug("Loading " + toload.size() + " spawnchunks ... ");
        //Util.sync(...) runs a task sync (in Server-Thread) and waits until complete
        Util.sync(() -> toload.forEach(p -> world.getChunkAtAsync(p.getX(), p.getZ(), consumer)));
        Logging.debug("Waiting for spawnchunks ... ");
        lock.wait();
        Logging.debug("All spawnchunks loaded!");
    }
```

### Paper build number:
git-Paper-236 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
latest as of writing this

**Comment by aikar** [comment]
Please reopen if still an issue on 1.15.2 latest
