### ISSUE TITLE
[1.15][paper-8+] Excessive chests with items in it causes extensive TPS loss when idling

### ISSUE THREAD

**Issue by DXUltimate** [PaperMC/Paper#2764]
Timings report: https://timings.aikar.co/?id=e28520e335ad4dd9a2a19281f05d27ab

This only happens when there are at least 6 people online, and I'm in this room.
https://puu.sh/EPVoP/f057a841ed.png

(also side note, thank you for fixing timings, as it didn't work for me a while ago =D)

**Comment by wizjany** [comment]
Your title would probably be better off written as "excessive hoppers" tbh. Chests don't really *do* anything.

**Comment by DXUltimate** [comment]
Interesting, those same hoppers never gave an issue at all prior to the
update to 1.15, hence this thread. If it did, I wouldn't have created this.
Thanks. =)
