### ISSUE TITLE
slower with more walk speed

### ISSUE THREAD

**Issue by TheMagBum** [PaperMC/Paper#2767]
https://github.com/EssentialsX/Essentials/blob/849efa9756495a34260d57ff1d81df1283e5f5e7/Essentials/src/com/earth2me/essentials/commands/Commandspeed.java#L124
I use this method but it doesn't work, so you become more slow and not faster

**Comment by Black-Hole** [comment]
To understand your issue, please provide the source code for a minimal plugin to reproduce your issue and the Paper version you're using (output of the /version command).

**Comment by TheMagBum** [comment]
https://hastebin.com/mixunazibu.java
Version: 
This server is running Paper version git-Paper-19 (MC: 1.15) (Implementing API version 1.15-R0.1-SNAPSHOT)
[Checking version, please wait...
Previous version: git-Paper-11 (MC: 1.15)
You are running the latest version

**Comment by andrepl** [comment]
just tested your code on paper-19.  `/speed 11` is fast, `/speed 0.1` is slow. seems correct to me

**Comment by TheMagBum** [comment]
Habe you test walk speed? By me 10 is slowly

**Comment by electronicboy** [comment]
have you tried removing your player data file/looking at the contents of it to check for other attribute modifiers?

**Comment by TheMagBum** [comment]
I deleted the data but it doesn't help
