### ISSUE TITLE
TPS always drops to 8-12 after an hour of uptime

### ISSUE THREAD

**Issue by justEli** [PaperMC/Paper#2769]
###  Timings or Profile link:
https://timings.aikar.co/?id=1825ce9a514644ea875193bc48ae4ca4

### Description of issue:
TPS has been dropping to very low rates eversince I started using Paper-19, mostly after an hour of uptime. The TPS still stays very low when there are 3 players online. The amount of entities seems to raise all the time..

### Plugin list:
https://timings.aikar.co/?id=1825ce9a514644ea875193bc48ae4ca4#plugins

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://timings.aikar.co/?id=1825ce9a514644ea875193bc48ae4ca4#config

### Other helpful links
¯\_(ツ)_/¯

### Paper build number:
1.15 Paper-19

**Comment by wizjany** [comment]
This is a bug tracker, not a place to get timings help.

**Comment by electronicboy** [comment]
Update.

**Comment by justEli** [comment]
Excuse me?

**Comment by MiniDigger** [comment]
You are running an outdated build, the new one most likely fixed your issue.

Update.
