### ISSUE TITLE
ticks-per.monster-spawns is ignored

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2771]
_On version git-Paper-21 (MC: 1.15)_

It seems to me that changing `ticks-per.monster-spawns` in bukkit.yml does not have any effect.
It is confirmed by the fact that `PlayerNaturallySpawnCreaturesEvent` keeps being fired continuously.

**Comment by electronicboy** [comment]
You erm... forgot the template...

**Comment by Menzani** [comment]
**What behaviour is expected:**
I'm expecting to see batches of `PlayerNaturallySpawnCreaturesEvent` being fired every 20 seconds.

**What behaviour is observed:**
I'm seeing batches of `PlayerNaturallySpawnCreaturesEvent` being fired continuously.

**Steps/models to reproduce:**
1. Listen to `PlayerNaturallySpawnCreaturesEvent`.
2. Set `ticks-per.monster-spawns` to `400` in bukkit.yml.
3. Join the server.

**Plugin list:**
none

**Comment by ghost** [comment]
Reproduced in Spigot. [An issue](https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-5484) has been opened there.
