### ISSUE TITLE
Paper.yml world-settings.default.hopper.disable-move-event option not working

### ISSUE THREAD

**Issue by rayanbzd** [PaperMC/Paper#2774]
### What behaviour is expected:
Hopper move event have to be disabled when world-settings.default.hopper.disable-move-event is set to true

### What behaviour is observed:
Hopper move event stay enabled when  world-settings.default.hopper.disable-move-event is set to true

### Steps/models to reproduce:
Create test plugin with InventoryMoveItemEvent for hoppers with a Sysout on console
Enable world-settings.default.hopper.disable-move-event in Paper.yml
Event is still enabled (see your sysout in console)

### Paper build number:
Paper-22 (MC: 1.15.1)

**Comment by electronicboy** [comment]
This patch has been removed in the meantime

**Comment by rayanbzd** [comment]
Does it mean that Paper will no longer be able to disable this event?

**Comment by electronicboy** [comment]
Until the patch is restored, no
https://github.com/PaperMC/Paper/pull/2765
