### ISSUE TITLE
Redstone T Flip flop broken on Paper 1.15.1 

### ISSUE THREAD

**Issue by cj3636** [PaperMC/Paper#2775]
Make a T-Flip flop gate with sticky pistons and toggling does not work.

**Comment by MiniDigger** [comment]
please follow the issue template and provide screenshots of your contraption and what we are meant to see. this report, as is, is useless.

**Comment by StealWonders** [comment]
@MiniDigger do you not know what a T-Flip flop is?

**Comment by zachbr** [comment]
Do you not know how to open a useful ticket?

**Comment by BillyGalbreath** [comment]
Unable to reproduce

https://youtu.be/bGGO04BTPw8
