### ISSUE TITLE
IndexOutOfBoundsException when trying to join

### ISSUE THREAD

**Issue by eirikh1996** [PaperMC/Paper#2780]
### What behaviour is expected:
___What you expected to see___
When joining the server, you are supposed to log into the world you quit in

### What behaviour is observed:
___What you actually saw___
Instead, this happens:
https://gyazo.com/7f0ad1cc3e205083edf2bb321fd449ff

### Steps/models to reproduce:

1. Run a 1.14.4 server
2. Join the server, and leave it
3. Shut down the server and upgrade to 1.15.1
4. Launch it again after upgrade
5. Try joining it and watch this problem occuring

### Plugin list:
[INFO] ....>.... Plugins (37): AntiVPN, AutoMessager, Autorank, BanManager*, Cannons, ChatControl, Citizens, ClearLag, CombatLogX, CoreProtect, CorpseReborn*, CrazyCrates, DiscordSRV, dtlTraders, Essentials, EssentialsChat, EssentialsSpawn, HolographicDisplays, JumpPads*, mcMMO, Movecraft, Multiverse-Core, MyCommand, NationCraft*, PermissionsEx*, PingTest*, PluginConstructorAPI, PluginLibrary*, ProtocolLib*, QualityArmory, Statz, StructureBoxes, Vault, ViaVersion*, vote_gui*, Votifier, WorldEdit

### Paper build number:
[INFO] ....>.... This server is running Paper version git-Paper-23 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

[INFO] .... Checking version, please wait...

[INFO] .... Previous version: git-Paper-237 (MC: 1.14.4)

[INFO] .... You are running the latest version

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by NachtRaben** [comment]
There is almost nothing useful here to diagnose your problem. You'll need to provide some server logs of wherever the player had connected before getting disconnected. Also you are using protocol hacks like ProtocolLib/ViaVersion. Please ensure these plugins are updated to their latest versions and see if you can reproduce it.

**Comment by MrEDok** [comment]
Update Protocollib ?

**Comment by eirikh1996** [comment]
> Update Protocollib ?

I do use version 4.4.0, which is the latest update of ProtocolLib

**Comment by eirikh1996** [comment]
Here is the entire server log on 1.15.1: https://hastebin.com/sexepuriwi.rb
Plus, I logged out in a MultiVerse world

**Comment by Draycia** [comment]
It's the latest release version*

As taken from its spigot page:

ProtocolLib
If you're running 1.14 or 1.15, use the latest dev build.
If you're running 1.8 through 1.13, use the latest release.

**Comment by MrEDok** [comment]
@eirikh1996 still update your protocollib you not using the version that is for 1.15
ProtocolLib

If you're running 1.14 or 1.15, use the latest dev build.
https://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

**Comment by eirikh1996** [comment]
> @eirikh1996 still update your protocollib you not using the version that is for 1.15
> ProtocolLib
> 
> If you're running 1.14 or 1.15, use the latest dev build.
> https://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

I updated PL to the version provided in the link and everything works fine now. Thanks alot for the help. I am therefore closing this issue now
