### ISSUE TITLE
Crash with PNJ paper 1.14.X and Paper 1.15.X

### ISSUE THREAD

**Issue by jere62smi** [PaperMC/Paper#2784]
The last exchange with a cartographer NPC crashes the server. I want to clarify that this problem is present since 1.14.X and is always present in 1.15.X

In addition I also have 2 other errors when interacting with a NPC it would appear in 1.14.4
http://bin.mc-imperia.fr/gJBtORkCp0
http://bin.mc-imperia.fr/UDjE3usb9z
http://bin.mc-imperia.fr/zcpGTFb6dP
http://bin.mc-imperia.fr/Oxh2hGm80M

**Comment by electronicboy** [comment]
PNJ? Can you replicate this without plugins?

**Comment by Momonche** [comment]
PNJ is a "Personnage Non Jouable" in french
So it's a NPC

Momonche
Official french traducer.

**Comment by zachbr** [comment]
If you're still seeing this we need updated logs on 1.15.2. Thanks.

**Comment by electronicboy** [comment]
This issue has actually been traced back to plugins messing with villager trades
