### ISSUE TITLE
Mismatch in destroy block

### ISSUE THREAD

**Issue by LoneDev6** [PaperMC/Paper#2785]
### What behaviour is expected:
No error

### What behaviour is observed:
Error message in console sometimes

### Steps/models to reproduce:
Unknown

### Paper build number:
This server is running Paper version git-Paper-25 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
Previous version: git-Paper-235 (MC: 1.14.4)
You are running the latest version

### Anything else:
Errors:
>.... [19:02:14 WARN]: Mismatch in destroy block pos: BlockPosition{x=-565, y=99, z=951} BlockPosition{x=-565, y=98, z=951}
>.... [19:02:14 WARN]: Mismatch in destroy block pos: BlockPosition{x=-565, y=97, z=951} BlockPosition{x=-565, y=98, z=951}

**Comment by electronicboy** [comment]
https://bugs.mojang.com/browse/MC-166432

**Comment by Puremin0rez** [comment]
Also seems to occur when block breaks are cancelled - such as breaking blocks in a protected claim.

**Comment by Puremin0rez** [comment]
Fixed upstream - message was downgraded to debug so you won't see it anymore.
