### ISSUE TITLE
1.14.4 too many mobs?

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#2789]
I Updated to 1.14.4 and I've noticed a large increase in mobs? I'd assume this is a bug with paper?

![image](https://user-images.githubusercontent.com/16514150/71319676-569dcd80-2499-11ea-90a4-cb5751f91037.png)

bukkit.yml: https://pastebin.com/raw/UwdrepLz
spigot.ym: https://pastebin.com/raw/GqrGFvHt
paper.yml: https://pastebin.com/raw/Sr5XXusS

/version
https://i.gyazo.com/317f5ba802b1cedc3fcefd9dcce51331.png

Is this a simulator issue to this:

https://github.com/PaperMC/Paper/issues/138

(Not as bad tho, Just normal mobs in the wild seem too high)

**Comment by Puremin0rez** [comment]
Your mob spawn range in spigot.yml is set to only 4 chunks, this means that per your bukkit.yml spawn settings, there's going to be 60~ hostile mobs spawned within 4 chunks of a player, which is quite condensed.

**Comment by jordanwilliams1** [comment]
@Puremin0rez The default is 4? that hasn't been touched.

**Comment by kickash32** [comment]
default is 8, spigot sets it to 4.

**Comment by jordanwilliams1** [comment]
@kickash32 What do i need to lower? I Didn't have this many mobs on 1.13. and i was running the same settings

**Comment by kickash32** [comment]
1.14 changed the mob spawning rules in regard to mobspawnrange. you either need to set mobspawnrange to 8 or divide each mob's spawn limits by 4.
