### ISSUE TITLE
Packetprocessing lag

### ISSUE THREAD

**Issue by Getblock** [PaperMC/Paper#2790]
###  Timings or Profile link:
https://timings.aikar.co/?id=cb47c5230da14095af06a68b77ce7915

### Description of issue:
I just updated the server to paperspigot 1.15.1 from 1.14.4 both at their latest version. Currently, the packetprocessing was never this bad or even close to it and now it's causing a massive tick loss 

### bukkit.yml, spigot.yml, paper.yml, server.properties
server properties:
https://pastebin.com/NRJdK8Wk

paper:
https://pastebin.com/DvrsbYqG

spigot:
https://pastebin.com/gRfhagPH

bukkit:
https://pastebin.com/iVJDjtjr

Server version: Paper(26) 1.15.1-R0.1-SNAPSHOT

**Comment by yurinogueira** [comment]
Me too :(
