### ISSUE TITLE
Server deadlock when loading chunks

### ISSUE THREAD

**Issue by justEli** [PaperMC/Paper#2792]
### Link/paste of stack trace
For Paper-25 and Paper-26, not as fatal, very great lag spikes.
https://pastebin.com/1gZCqeDV

But really since Paper-27, it got quite hot and several crashes already occured in a few hours, so I downgraded to Paper-25 and that seems to work fine again.
https://pastebin.com/gWftLvDz <- Most useful.
https://pastebin.com/1vTXeT5y <- Thought I'd post this one too.

### Plugin list:
Plugins (23): AuctionHouse, BeeHivesTrees, ChestShop, Coins*, CoreProtect, CreepersTrimGrass, Discord, dynmap*, GriefPrevention, GSit, LiteBans, Oak, PermissionsEx*, PlugMan, Portandum, SAML, SmoothSleep, SortedWarps, TradePlus, Vault, VillagerOptimiser, Votifier*, WorldEdit

### Paper build number:
1.15
Paper-27 has been pretty fatal for me
(Paper-25, 26 do have very great lag spikes as well)

**Comment by wizjany** [comment]
This isn't a deadlock, just villager trades taking too long to find treasures for maps.

**Comment by perseus5** [comment]
#2312

**Comment by justEli** [comment]
All I'm saying is that this really is an outstanding issue since Paper-27, and when using Paper-25, it seems to be all fine again.

**Comment by wizjany** [comment]
It's not an issue with any particular build. There's nothing in 27 that makes this worse. Welcome to Minecraft, this is how treasure maps work.

**Comment by Aaron2550** [comment]
@JustEli You can try and set `treasure-maps-return-already-discovered: false` to true in the paper.yml. this will, as the name suggests, sometimes (?) give out already discovered treasure-maps but may help with the lag spikes when villager trades look for maps.

EDIT: If its already implemented in 1.15.x

**Comment by justEli** [comment]
thanks! will do
