### ISSUE TITLE
Villager#setProfession won't work properly

### ISSUE THREAD

**Issue by luizsusin** [PaperMC/Paper#2794]
### What behaviour is expected:
When setting villager profession, view it on the Villager itself.

### What behaviour is observed:
Although debug info (from my Plugin) shows me that the entity has the specified type and profession, the Villager spawned is actually a Villager without any profession.

### Steps/models to reproduce:
A pseudo-code, very simillar to the one in my plugin. Assume that "old" is another Villager entity, spawned with /summon in the game, with a profession. Also, assume that there's verifications to ensure that the `clone` LivingEntity is a Villager _etc_. This is obviously a simplified version.

`LivingEntity clone = (LivingEntity) old.getWorld().spawnEntity(loc, old.getType());`
`((Villager) clone).setVillagerType(((Villager) old).getVillagerType()); // Works great`
`((Villager) clone).setProfession(((Villager) old).getProfession()); // Doesn't work`

### Plugin list:
LibsDisguises, ProtocolLib, PlaceholderAPI and my plugin itself.

### Paper build number:
`git-Paper-27 (MC: 1.15.1)`

### Anything else:
I'm sorry if there's something I'm missing or if it's not Paper's fault. I'm also not used to open issues on GitHub.

**Comment by kickash32** [comment]
Villagers can change professions randomly if they don't have any xp, try giving them 1 xp.

**Comment by luizsusin** [comment]
Perfect, that was exactly the problem. Thank you @kickash32.
