### ISSUE TITLE
TIMING_STACK_CORRUPTION Exception generating new chunk

### ISSUE THREAD

**Issue by daspositioned** [PaperMC/Paper#2798]
### Link/paste of stack trace

Stack trace: https://pastebin.com/HRcxpLXa
Crash report: https://pastebin.com/ZbQKc9LK

### Plugin list:

Plugins (19): ChatManager, CreativeItemControl, CreatureLimit, CSECount, Holograms*, JBann, JCommands, MoneyforJanus, Multiverse-Core, Multiverse-Inventories, MyPet, PermissionsEx*, PlotSquared, PluginConstructorAPI, PunishmentGUI*, TimeforJanus, Vault, WorldEdit, WorldGuard

### Actions to reproduce (if known):

Unknown

### Paper build number:

git-Paper-236 (MC: 1.14.4)

**Comment by electronicboy** [comment]
The timing stack corruption is basically irrelevant, the issue is that your chunk generator blew up, probably failed to load properly, check your logs
