### ISSUE TITLE
PlayerNaturallySpawnCreaturesEvent is ignored

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2799]
_On version git-Paper-29 (MC: 1.15.1)_

Cancelling `PlayerNaturallySpawnCreaturesEvent` does not work; monsters spawn nonetheless.

This could be related to the fact `ticks-per.monster-spawns` is ignored in bukkit.yml (see #2771).

**Comment by perseus5** [comment]
Having the same problem so I made one upstream: https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-5484

**Comment by Menzani** [comment]
Thank you.

**Comment by Menzani** [comment]
I must point out that `PlayerNaturallySpawnCreaturesEvent` is called too many times.
If that is intended and not a bug, then maybe an option should be implemented similar to `hopper.disable-move-event` that would reduce the amount of garbage allocated.

**Comment by Menzani** [comment]
I must point out that `PlayerNaturallySpawnCreaturesEvent` is called a lot of times.
If that is intended and not a bug, then maybe an option should be implemented similar to `hopper.disable-move-event` that would reduce the amount of garbage allocated.

**Comment by Menzani** [comment]
I must point out that `PlayerNaturallySpawnCreaturesEvent` is fired a lot of times per tick.
If that is intended and not a bug, then maybe an option should be implemented similar to `hopper.disable-move-event` that would reduce the amount of garbage allocated.

**Comment by ghost** [comment]
Thank you. Also, `PlayerNaturallySpawnCreaturesEvent` is fired a lot of times, which I do not think is intended.

**Comment by Spottedleaf** [comment]
all the issues you describe are due to a bad implementation of the event which I plan on rewriting

**Comment by kickash32** [comment]
`ticks-per.monster-spawns` being ignored is a separate issue, although the bad implementation does fire `PlayerNaturallySpawnCreaturesEvent` even if spawns are not being attempted. The implementation does not indicate in any way that the `PlayerNaturallySpawnCreaturesEvent` is useless (not cancelled by default or anything else).

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Paper/pull/2802 will resolve the spam nature of the event and also ~~fixes `ticks-per.monster-spawns`~~ - however it will still call the event every tick and the spawnRadius will still be the spawn range for all mob types

**Comment by Menzani** [comment]
Still no progress on the bug upstream...

**Comment by ghost** [comment]
The event is still fired like 4000 times per second. Also upstream has not yet fixed `ticks-per.monster-spawns` being ignored.

**Comment by Spottedleaf** [comment]
The fix I have is significantly delayed.

**Comment by electronicboy** [comment]
Looking back at this, there are two major issues
1) The boolean return is inverted (something something trusting spigot to name methods sanely something something...)
2) Given how spawning actually works now, this event is somewhat shortsighted, probs wanna at the very least look towards how to limit this more effectively, update mob counters?

**Comment by ghost** [comment]
Cancellation not working was fixed by 9976a76809fa55f97ac8056749ba810ca2dbc54d.
