### ISSUE TITLE
Paper Still Thinking it has a Session.lock

### ISSUE THREAD

**Issue by Clarkcj12** [PaperMC/Paper#280]
# Crash, Stacktrace
### Link/paste of stack trace

[Crash Log](https://gist.github.com/Clarkcj12/1eeaec969eb004e8b5d5cdb51a1750fe)
## Description of issuse:

For some reason I uploaded a new world from my old server. and it had a session.lock file that I forgot to remove. I started it up and alerted me about it then shutdown. I since removed the session.lock file from the world folder and it still says it has a session.lock file in the folder and it isn't even there its like a ghost. I looked to check to see if it is there via FileZilla, the method which I deleted the file, and SSH's ls function.
### Plugin list:

BKCommonLib, WorldEdit, BuyCraft, CoreProtect, Essentials2.x suite (GeoIP, Chat, Spawn, Protect), PermissionsEx, ProtocolLib, WorldGuard
### bukkit.yml, spigot.yml, paper.yml, server.properties

[Bukkit.yml](https://gist.github.com/Clarkcj12/f8d31ddadf57bd5e72f42423d06edfbc), [Spigot.yml](https://gist.github.com/Clarkcj12/aa16f1f13cd41b9bd4f7e689f5400061), [Paper.yml](https://gist.github.com/Clarkcj12/b48f6251fc7d102e6db2451bd4ed41e3), [server.properties](https://gist.github.com/Clarkcj12/76adc821cfeb6ab4c5109ca8a6454276)
### Actions to reproduce (if known):

Upload a new map that is from another server that has a session.lock file in it. Boot up server, and shut it down, and remove the session.lock file from the world folder, and boot server back up, server will crash saying there is a session.lock file in the ./world folder and asks you to remove it even though it doesn't exist anymore.
### Paper build number:

As far as I can tell it is the Paper build git-Paper727, I can't do a proper /version as such as my server keeps crashing.

**Comment by zachbr** [comment]
Your crash log link 404s. Bad link?

**Comment by Clarkcj12** [comment]
@Zbob750 Sorry, correction its this [link](https://gist.github.com/Clarkcj12/1eeaec969eb004e8b5d5cdb51a1750fe)

**Comment by zachbr** [comment]
The only way I am able to reproduce your issue is if I delete the session.lock file while the server is running and then force a save-all.

And it explicitly says to shut it down first.

**Comment by NachtRaben** [comment]
Sounds like a classic unix file permissions error, without the rest of the log though I can't tell.
Try running the following command if you can access root privileges on your host. 
sudo chown -R <user>:<Group/CommonlyTheUserr> /path/to/server/instance/without/trailing/slash
