### ISSUE TITLE
Unload unused chunks on explicit save regardless of autosave

### ISSUE THREAD

**Issue by Janmm14** [PaperMC/Paper#2801]

**Comment by electronicboy** [comment]
saving and unloading are detached from one another, the server doesn't unload chunks because they won't be saved, and you cannot garauntee any form of consistency in this state

**Comment by Janmm14** [comment]
they would get saved when save is called

**Comment by electronicboy** [comment]
You still have the time gap between the chunk being saved and the unload
logic being ran

**Comment by Janmm14** [comment]
Sure, but it would prevent servers running out of ram when they have autosave off and do some sort of manual saving - although that is not recommended

**Comment by electronicboy** [comment]
set the autosave value stupidly high, we're not going to risk people losing data in chunks to permit stupidity

**Comment by Janmm14** [comment]
i don't get how unloading after a save operation on a chunk if chunk does not need to be loaded anymore can lead to data loss, but apparantly thats possible

**Comment by electronicboy** [comment]
Because saving doesn't mean running chunk unload logic, there is potentially a full tick between a save-all and chunks unloading

**Comment by Spottedleaf** [comment]
it's very technically possible to allow this behavior but why would we go through the effort when the solution is to simply have saving enabled with incremental saving, if people don't want incremental then all they do is change the settings so autosave doesn't occur and they're just fine?

**Comment by Janmm14** [comment]
i see
