### ISSUE TITLE
Error executing task on Server java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Dymeth** [PaperMC/Paper#2803]
**Link/paste of stack trace:**
https://pastebin.com/raw/RfcACZRg

**Plugin list:**
AuthMe, Brewery, BroadCastMessage*, Chatty*, CoreProtect, FastAsyncWorldEdit, NametagEdit*, PermissionsEx*, PlaceholderAPI, PlugMan, ProtocolLib*, rHideTags*, SerialKey, SimpleJail*, SimpleSit*, SkinsRestorer, StopNetherTrap, TemporalWhitelist*, Vault, WorldEdit

**Actions to reproduce (if known):**
No ideas

**Paper build number:**
Paper version git-Paper-237 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by BijuuKrunos** [comment]
I think this is not completely fixed. I had this error with the newest paper:

`[18:31:15] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
        at net.minecraft.server.v1_15_R1.ChunkMapDistance.b(ChunkMapDistance.java:230) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1362) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:811) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1145) ~[?:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-126]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
`

**Comment by electronicboy** [comment]
> The player gets the message "Cannot send Chat Message" everytime he wants to write something or execute a command until rejoining. Everytime he is getting this error in chat i have the error from above in console.

unrelated, this issue is regarding teleportation of a dead player teleporting, your issue is desync between the client and the server, server thinks that player is dead; replicate without plugins.

**Comment by sannielollie** [comment]
Getting about the same issue, but cant find a solution. I have tried disabling all plugins that are on the server of the topic starters (also on other bug reports regarding this issue) to see if one of those plugins is causing the issue on my server. But well, all with the same result - the issue still occours. Mostly on a teleport, using EssentialsX. 

This is how to reproduce it:
-User teleports using a home, warp, tpa.
-User sees the world "dissapearing" and all entities, including theirselves start shaking.
  All user input in chat (text and commands) just give the feedback "cannot send chat message"

This is what i see in my console at that certain moment:
https://pastebin.com/raw/7zvgGbJv

I am really out of ideas, and my players find it really annoying.

**Comment by aikar** [comment]
Please update to 1.15.2. Numerous issues have been fixed, and haven't had any new reports of that one recently.

**Comment by sannielollie** [comment]
> Please update to 1.15.2. Numerous issues have been fixed, and haven't had any new reports of that one recently.

Thanks for your reply on this Aikar!
Yeah, i know i have to update my whole server. But yeah, running over 110+ plugins means a lot of work to update everything, im just on my own. I just hoped for a simple solution. Are you sure it is fixed in 1.15.2 and upcoming versions? So its not a (completely?) plugin related issue?

Is there any workaround? I dont care if its a really strange workaround, as long as it works (temp fix) i am happy. Usually i skip one minecraft version before i update my server completely xD

**Comment by aikar** [comment]
1.15 is considered an urgent update to 1.14, 1.15 is just "1.14 continued"

May want to consider culling really unnecessary plugins to reduce maint cost.

**Comment by sannielollie** [comment]
Yeah well, im already down from +/- 160 plugins to 110 - i'll just have to find a lot of spare time then. I dont know how much efford it will cost to update the server, i remember going from 1.12.2 to 1.14 was  a lot of work. Culling down the plugins any further is an option, i'll see wich plugins are not important :)
And yes, its running without any lag, thanks to paperspigot and your optimization guides :)

**Comment by kylematzen** [comment]
I understand this issue is cleared/closed, but I am just mentioning that in most cases this error pops up due to the fact of the player entity being removed from a world or the server. Or it's due to Chat not being declared as "Shown" in Chat Settings.

**Comment by aikar** [comment]
entity remove from world issues we are working on fixing in 1.15
the client chat shown issue would not cause this error.

**Comment by sannielollie** [comment]
> entity remove from world issues we are working on fixing in 1.15

Ah, so updating at this stage to 1.15 doesnt solve the issue yet?

**Comment by aikar** [comment]
We have removed a primary source of triggering it, but vanilla logic is still subject to it in extreme timing. 

But that source is not super common. we had just increased the likelyhood of it temporarily, but thats now back to reduced.

though this specific issue is actually fixed in 1.15 because of another change.

**Comment by i0xHeX** [comment]
Still in b183 (1.15.2)

```
16.04 16:20:20 [Server] FATAL Error executing task on Server
16.04 16:20:20 [Server] INFO java.lang.NullPointerException: null
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.ChunkMapDistance.b(ChunkMapDistance.java:230) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1479) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:844) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1145) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1052) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1022) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:945) ~[patched_1.15.2.jar:git-Paper-183]
16.04 16:20:20 [Server] INFO at java.lang.Thread.run(Thread.java:830) [?:?]
```

**Comment by aikar** [comment]
Fixed in 196.
