### ISSUE TITLE
Hoppers transport items in pairs

### ISSUE THREAD

**Issue by simonsmd** [PaperMC/Paper#2804]
### What behaviour is expected:
Hopper transports only one item at once.

### What behaviour is observed:
Hoppers facing downwards into other hoppers transport two items at once.

### Steps/models to reproduce:
The issue only appears if a hopper is facing downwards into another hopper.
If the hopper is facing into a chest or not downwards it works as expected.

### Plugin list:
none

### Paper build number:
 git-Paper-31 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

### Anything else:
The issue also appears in a normal Minecraft singleplayer world so I will also report this to Mojang but I also wanted to report it here so it may get fixed faster.

**Comment by Menzani** [comment]
Exactly what I reported some days ago. However, I don't know if this is intended behavior.

**Comment by Menzani** [comment]
This is intended behavior, see for example [here](https://www.reddit.com/r/Minecraft/comments/2j0o4g/til_vertical_hopper_chains_transport_items_a_lot/).

**Comment by Menzani** [comment]
This is intended behavior, see [here](https://www.reddit.com/r/Minecraft/comments/2j0o4g/til_vertical_hopper_chains_transport_items_a_lot/) for example.
