### ISSUE TITLE
TNT duplication

### ISSUE THREAD

**Issue by Shieldly** [PaperMC/Paper#2808]
### What behaviour is expected:
TNT not duplicating when a fire is burning above

### What behaviour is observed:
When fire burns on a TNT block it can cause it to duplicate

### Steps/models to reproduce:
_Example Video_: https://www.youtube.com/watch?v=G48xUlVnXbk

### Plugin list:
None at all 
![image](https://user-images.githubusercontent.com/40553947/71569517-47201500-2a95-11ea-9f9b-43fae69add82.png)

### Paper build number:
![image](https://user-images.githubusercontent.com/40553947/71569542-67e86a80-2a95-11ea-8354-c44124c2c2dc.png)

### Anything else:
Not at this moment

**Comment by mikroskeem** [comment]
Isn't this a vanilla bug? I recall it being present for few years now.

**Comment by Shieldly** [comment]
No I switched off of Paper to Spigot and the issue is fixed

**Comment by electronicboy** [comment]
Seems tied to the tnt prime event
