### ISSUE TITLE
Server crash，because paper server bug

### ISSUE THREAD

**Issue by Extreme-Icer** [PaperMC/Paper#2809]
version:MC1.14.4-git-paper-238
BUG phenomenon:There is a problem with paper's papi, and a serious sending and receiving error occurs in netty, causing the server to crash and the server to be disconnected.The problem lasted for 20 minutes. The problem was temporarily resolved after switching to the spigot server. This issue is serious, please troubleshoot.Since this problem cannot be checked through the log, it is inconvenient to upload the log.

**Comment by electronicboy** [comment]
If you can't provide logs or anything, I've literally got no idea what
you're expecting us to look at...

**Comment by electronicboy** [comment]
Fwiw, there are multiple options to convince the server to produce more info for exceptions, if you require further assistance, please ask on the discord/forums

**Comment by Extreme-Icer** [comment]
[2019-12-31-6.log](https://github.com/PaperMC/Paper/files/4012640/2019-12-31-6.log)

**Comment by Extreme-Icer** [comment]
please see this server log.

**Comment by electronicboy** [comment]
There is no crash in there? You have a lot of keepalive timeouts, but that's more likely to be a networking issue vs netty related, especially if that was pretty much everybody on the server

**Comment by Black-Hole** [comment]
The log shows that at [12:40:37] the unsupported /reload command was used.
