### ISSUE TITLE
Crash: Exception ticking world + Lightning

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#281]
# Crash, Stacktrace
### Link/paste of stack trace

Log: http://pastebin.com/Gquv8SJ2
Crash: http://pastebin.com/E4NFgub7
### Plugin list:

Not needed. It's a Minecraft/Paper bug.
### Actions to reproduce (if known):

**_Join at a specific place (the conditions are unknown) which crashs the server.**_
### Paper build number:

**_Version 730 - 1.9.4**_
### Work-Around

Set random-light-updates to "false". Then the server will only give out the log error but will not crash.

**Comment by ghost** [comment]
random-light-updates: false doesn't fix the problem completely.
This issue needs to be fixed asap.

**Comment by ghost** [comment]
### Version 731:

Log: http://pastebin.com/5bnbUnid
Crash: http://pastebin.com/zCg7btur

**Comment by hurrgurl** [comment]
Same issue

**Comment by zedwick** [comment]
I too am having an issue which seems similar, though my random-light-updates is already false but the server is still crashing. No issue in spigot.

https://pste.me/#/mdM8l

**Comment by ghost** [comment]
As written above the issue for me occurs also if random-light-updates is false. 

It's really annoying. We can just hope that it get fixed soon by the developers.

**Comment by ghost** [comment]
@zedwick look up if the Spigot Server and the Paper Server have ANY setting different

**Comment by mibby** [comment]
@aikar Can also confirm it happening on paper 730. 8 crashes in less than 12 hours.

```
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 16
    at net.minecraft.server.v1_9_R2.Chunk.getBrightness(Chunk.java:591)
    at net.minecraft.server.v1_9_R2.World.b(World.java:775)
    at net.minecraft.server.v1_9_R2.World.a(World.java:2393)
    at net.minecraft.server.v1_9_R2.World.c(World.java:2422)
    at net.minecraft.server.v1_9_R2.Chunk.a(Chunk.java:310)
    at net.minecraft.server.v1_9_R2.Chunk.b(Chunk.java:300)
    at net.minecraft.server.v1_9_R2.Chunk.recheckGaps(Chunk.java:274)
    at net.minecraft.server.v1_9_R2.Chunk.lambda$h$0(Chunk.java:248)
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:789)
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:627)
    at java.lang.Thread.run(Thread.java:745)
```

Could it have something to do with the queue-light-updates patch you wrote?
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0031-Lighting-Queue.patch#L52

**Comment by Plusgames** [comment]
> Can also confirm it happening on paper 730 < That is written at the first post

Paper build number:

Version 730 - 1.9.4

**Comment by mibby** [comment]
@Plusgames So, what are you getting at? Having another person confirm with the same or greater paper version isn't a hindrance to the report, but rather confirms the problem exists than being a user issue. 1.9.4 isn't necessary to report since builds 728+ are 1.9.4 only.

**Comment by zedwick** [comment]
@Plusgames I am just stopping the same server, swapping out the spigot jar for paper, starting the server and seeing it crash, swapping out paper for spigot and starting it to see it working fine.

No settings changed. If it helps, for anyone who may want to test it against the same map, I am running TerraSwoopForce map by Noxcrew, standing in the player spawn room.

**Comment by ghost** [comment]
OK thx @zedwick 
@mibby sorry i understood it differently i got it know 

I am gonna test this out tomorow and may correct it if not fixed until there
Good Day

**Comment by stevmei** [comment]
Confirmed, seems to crash sometimes due to light updates in loaded chunks.

**Comment by ghost** [comment]
Same here, getting the same error log. Build 731

**Comment by zachbr** [comment]
@mibby is testing whether build 732 fixes the issue.

**Comment by zedwick** [comment]
I can confirm build 732 seems to have fixed this issue for me, thanks @Black-Hole

**Comment by ghost** [comment]
Can confirm that the issue is fixed. Big thanks to @Black-Hole
