### ISSUE TITLE
Unable to get "Bad Omen" after upgrade

### ISSUE THREAD

**Issue by RaidersPlay** [PaperMC/Paper#2810]
### What behaviour is expected:
___What you expected to see___
When killing a pillager, the bad omen is supposed to appear on the screen and a raid triggered when going into a vilage
### What behaviour is observed:
___What you actually saw___
Killed 10 pillagers with banners and no bad omen. Verified that disableRaids is set to false. Even tried setting it to enable and back to false
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___
Removed all plugin to try and rule out plugins. No success, still not getting bad omen.

[14:16:16] [Server thread/INFO]: Plugins (8): AngelChest, BanGui, DiscordSRV, dynmap*, DynmapHider*, Harbor, LightPerms, MyDog

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
[14:17:04] [Server thread/INFO]: This server is running Paper version git-Paper-32 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[14:17:04] [Server thread/INFO]: Previous version: git-Paper-31 (MC: 1.15.1)
[14:17:04] [Server thread/INFO]: You are running the latest version

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by RaidersPlay** [comment]
I've spoken to the guys on my server.
No one can recall starting a raid since we updraded to 1.15.0 from 1.14, paper 230.
So, the last bad omen affect was when we where on 1.14, paper 230.
I can't seem to find any other setting that would block getting the bad omen affect.

I've removed all the datapacks and plugins on the server and still could not trigger the bad omen affect. These datapacks and plugins was used on 1.14 also.

**Comment by RaidersPlay** [comment]
Still not working.

New version information...
[Tue, 21. Jan 2020 07:51:04 CAT INFO] This server is running Paper version git-Paper-60 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[Tue, 21. Jan 2020 07:51:04 CAT INFO] Previous version: git-Paper-58 (MC: 1.15.1)
[Tue, 21. Jan 2020 07:51:04 CAT INFO] You are running the latest version

**Comment by nbastin** [comment]
This is happening for us as well - previously 1.15.1-33 and now on -62, same issue.

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/72839524-55bfad80-3c8a-11ea-9a64-d1d5795b8f84.png)
Was testing something else earlier, but, basically...

**Comment by electronicboy** [comment]
coming back and looking at this, basically "that's not how it works"
You only get the effect from killing illagers, not pillagers

**Comment by nbastin** [comment]
Erm, when did that change happen?  We certainly used to get Bad Omen from raiding parties in 1.14, and I'm fairly sure vanilla 1.15 as well (although I would need to test again to be sure I last did this in 1.15).

(Edit: Technically _patrol_ parties, from the patrol captain.  This definitely worked in 1.14).

**Comment by electronicboy** [comment]
patrol leaders are the only things which give the effect, which does work as I ended up stumbling across one while testing some other stuff earlier, which is how I had that effect

**Comment by RaidersPlay** [comment]
I have a stack of pillager banners, still not able to get the effect after upgrading from 1.14.1 to 1.15.0. 
I've checked the server setting disableRaids and it is set to false..
I searched for any other ways to fix this, and found no help, only thing mentioned was a glitch in previous minecraft versions that was fixed.
The only other thing I can think of, is that something went wrong when we upgraded. But if that is the case, how to fix...

**Comment by nbastin** [comment]
I was able to get Bad Omen from a pillager outpost, but not from a patrol in the world.  Rolling back to 1.14 doesn't have this problem.

**Comment by RaidersPlay** [comment]
I've checked. I have the exact same thing as @nbastin. Searched an outpost and went to the outpost. Then only do I get bad omen. When killing a patrol with a banner, no bad omen.

**Comment by bardicknowledge** [comment]
I'm not sure if this should have been closed.  I'm having the same issue.  Killing banner-wielding pillagers in vanilla Minecraft gives the player Bad Omen.  This doesn't matter if the banner pillager is a patrol leader or an outpost captain, as both can give the effect:
https://minecraft.gamepedia.com/Pillager#Bad_Omen

Killing the outpost captain does give the Bad Omen effect, but patrol leaders are supposed to do this as well.

**Comment by electronicboy** [comment]
EntityRaider.java
```java
if (this.isPatrolLeader() && raid == null && ((WorldServer) this.world).c_(new BlockPosition(this)) == null) {
                .......
                if (!itemstack.isEmpty() && ItemStack.matches(itemstack, Raid.s()) && entityhuman != null) {
                    MobEffect mobeffect = entityhuman.getEffect(MobEffects.BAD_OMEN);
                    byte b0 = 1;
                    int i;

                    if (mobeffect != null) {
                        i = b0 + mobeffect.getAmplifier();
                        entityhuman.c(MobEffects.BAD_OMEN);
                    } else {
                        i = b0 - 1;
                    }

                    i = MathHelper.clamp(i, 0, 5);
                    MobEffect mobeffect1 = new MobEffect(MobEffects.BAD_OMEN, 120000, i, false, false, true);

                    if (!this.world.getGameRules().getBoolean(GameRules.DISABLE_RAIDS)) {
                        entityhuman.addEffect(mobeffect1, org.bukkit.event.entity.EntityPotionEffectEvent.Cause.PATROL_CAPTAIN); // CraftBukkit
                    }
                }
            }
```

The code clearly checks that the killed entity is marked as a patrol leader before it will actually give the bad omen effect

if you can demonstrate where this is the case in vanilla code, i.e. not a community wiki, we can re-open the issue

**Comment by BillyGalbreath** [comment]
This whole ticket confuses me.

Firstly, a patrol leader (from a coding perspective) is both the patrol leader and an outpost captain. If they naturally spawned in with a banner on their head (not from a command, etc), they are a patrol leader.

This banner is given to them in the `EntityMonsterPatrolling#prepare` method if and only if their patrol leader flag is set to true.

Now that that's out of the way, I can report that I am unable to reproduce the bug being reported. Killing any patrol leader (includes the random spawn and outpost spawn) gives me and my players the bad omen, as expected.

**Comment by RaidersPlay** [comment]
My assumption can only be, there something went wrong during the upgrade from 1.14 to 1.15. Maybe a flag was not transferred correctly or something.
Although it does not seem to be a common issue, but reported by myself and someone else. It seems to be a glitch rather that a bug.
Unfortunately I'm no coder, and can't even find the EntityRaider.java code that was specified above..
We made the decision to just live with the problem and reset/recreate the whole server when 1.16 comes out due to the neither world update.

**Comment by nbastin** [comment]
This problem is trivially reproducible if you take a 1.14 world that has pillager spawns (which is pretty easy, since in 1.14 they didn't despawn), and then load it into 1.15.  On a vanilla server the existing pillagers work fine (they will trigger a Bad Omen effect when killed), but in Paper they do not.  Newly spawned patrols in Paper work as expected, so this is clearly some kind of data inconsistency from old worlds.
