### ISSUE TITLE
Tps lose with 10 players+

### ISSUE THREAD

**Issue by MrMIStakee** [PaperMC/Paper#2811]
https://timings.aikar.co/?id=379b556e050f46828e70de1e222af6ac#timings

Drops to 10 tps when the number of players reaches more than 10

I have been observing this problem for a very long time, from 1.14.x to 1.15.1

**Comment by electronicboy** [comment]
The issue tracker is not for support with timings

**Comment by MrMIStakee** [comment]
The core is the problem! It consumes tps

**Comment by electronicboy** [comment]
It has been well documented time and time again that the performance of 1.14 vanilla is harsh, running 1.14+ in an underpowered environment is asking for issues; Your server is basically overloaded, only having 2 cores is also basically far from ideal these days too
