### ISSUE TITLE
On server Init - dosnt work on 1.13

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2813]
**Is your feature request related to a problem? Please describe.**
When I create new world with `Bukkit.createWorld(new WorldCreator("%arg-1%")).environment(Environment.NORMAL))` and on server init event I set `setKeepSpawnInMemory(false)` on 1.12.2 my world gets loaded in 0.30sec, but on 1.13.2 takes 5-6sec

**Describe the solution you'd like**
Maybe look at way to fix if its a problem in 1.13.2

**Describe alternatives you've considered**
um my english is not that good to understand this question

**Additional context**
nah just improve it if possible

**Comment by HexedHero** [comment]
Wouldn't this be because Mojang re-made the generation engine stuff because it was "too hard" to add the new oceans into the old gen?

**Comment by kickash32** [comment]
Thats irrelevant, on discord he noted that it works in 1.12 and 1.15 but not 1.13 (not known 1.14). So this should be fixable.

**Comment by ghost** [comment]
Yes, I tested on 1.15 it works. Very weird, or I fcked up someting...

**Comment by electronicboy** [comment]
Is the server actually loading chunks on 1.13 or?

**Comment by ghost** [comment]
What do you mean? When I teleport to created worlds it loads chunks

**Comment by electronicboy** [comment]
What I'm tryna wonder is the relevance of `setKeepSpawnInMemory`, if this is literally a case of "1.13 inits worlds slower" and literally has nothing to do with that setting, I'm not entirely sure what's expected here; You could try grabbing a sample of the process and seeing if there is anything obvious that sticks out, but the performance here is heavily down to the work vanilla itself has to do

**Comment by AJMFactsheets** [comment]
Since keeping spawn loaded seems to affect the results, I believe the problem is that a patch added to 1.14 (and thus 1.15) was never backported to 1.13. Hopefully the PR can be merged quickly since support for Paper 1.13.2 is ending tomorrow!
