### ISSUE TITLE
FATAL Error executing task on Server

### ISSUE THREAD

**Issue by zydde** [PaperMC/Paper#2818]
Hello! A few days ago I've been getting spammed with errors that look something like this:

`02.01 09:52:47 [Server] FATAL Error executing task on Server
02.01 09:52:47 [Server] INFO java.lang.IllegalStateException: POI data mismatch: already registered at BlockPosition{x=-6234, y=81, z=-1997}
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.VillagePlaceSection.a(SourceFile:81) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.VillagePlaceSection.a(SourceFile:65) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.VillagePlace.a(VillagePlace.java:36) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.lambda$null$14(WorldServer.java:1838) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-233]
02.01 09:52:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

I have no idea what could be causing this.

Plugins **(21)**: BetterSleeping*, CoreProtect, DiscordSRV, dynmap*, Dynmap-Towny, Essentials, Gringotts, LoginSecurity*, LuckPerms, PlugMan, PowerRanks*, ProtocolSupport, ProtocolSupportStuff, SkinsRestorer, SkQuery, Skript, Towny, Vault, WorldBorder, WorldEdit, WorldGuard

Let me know if you need more info. Thanks!

**Comment by electronicboy** [comment]
Vanilla issue, shouldn't have any side effects and will stop after the inconsistency has been fixed on its own
