### ISSUE TITLE
Add Patches folder for custom user patches

### ISSUE THREAD

**Issue by danthedaniel** [PaperMC/Paper#282]
# Suggestion

It'd be awesome if patches made locally could be placed into an alternate patch folder (something that would be hidden from git with .gitignore). That way admins could make custom patches while also easily staying up to date with Paper through git pulls.

Also if possible, custom patches would ideally be tied to a specific server version, and automatically un-applied after a new MC release (or at least a warning message would be displayed).

**Comment by zachbr** [comment]
While I do not want to come off as harsh or in any way discourage people from modifying Paper to their own needs, adding a custom patches folder is outside the scope of Paper itself.

You are free to fork it and add any patches you want, or set up yourself as a downstream similar to what we have done with Spigot, or what others have done with us. Unfortunately, providing a patch folder for users to just throw patches in doesn't really benefit the project in any way, and I suspect will only increase support burdens.
