### ISSUE TITLE
New PlayerHotbarChangeEvent / PlayerOffhandChangeEvent

### ISSUE THREAD

**Issue by Whimsyturtle** [PaperMC/Paper#2821]
**Is your feature request related to a problem? Please describe.**
Currently, Paper has the ``PlayerArmorChangeEvent`` that allows devs to **quickly and easily** detect when players **change armor items** in their armor slots by just listening into that event, instead of having to listen to numerous events, including (but not limited to): 
- InventoryClickEvent
- InventoryDragEvent
- PlayerInteractEvent
- PlayerItemDamageEvent
- PlayerItemMendEvent
- PlayerDeathEvent
- BlockDispenseArmorEvent

When I tried to lookup to find a similar event for players **changing their mainhand/offhand** (note: not necessarily just item swapping between the mainhand and offhand, see below for more cases), I found that no such event existed in Spigot or Paper - meaning if I wanted to detect players changing their mainhand/offhand items accurately, I'd have to replicate it with my own listener.

**Describe the solution you'd like**
Paper should implement it's own event similar to the ``PlayerArmorChangeEvent``, but for players changing their mainhand/offhand items. Perhaps the ``PlayerHotbarChangeEvent`` and ``PlayerOffhandChangeEvent`` could be created? Or perhaps they could be merged into a single event? I'll leave it up to anyone who wishes to implement this.

Either way, the these event(s) would basically be called whenever a player's mainhand **or** offhand items change, either from **item damage, item loss, or item gain**. In essence, it should be the equivalent of listening to the following events (similar to how the current ``PlayerArmorChangeEvent`` operates):
- InventoryClickEvent (for movement of items to the hotbar or offhand slot)
- InventoryDragEvent (for dragging of items to the hotbar or offhand slot)
- PlayerSwapHandItemsEvent (for swapping mainhand and offhand items)
- EntityPickupItemEvent (for picking up items into the hotbar slot)
- PlayerDropItemEvent (for dropping items from the hotbar or offhand slot)
- PlayerDeathEvent (for dropping of items from the hotbar or offhand slot)
- PlayerItemDamageEvent (for losing durability on items in the hotbar or offhand slot)
- PlayerItemMendEvent (for gaining durability on items in the hotbar or offhand slot)

**Describe alternatives you've considered**
I have attempted to use the ``PlayerItemHeldEvent`` that Spigot currently has, as @BillyGalbreath suggested - but it **does not contain the same level of functionality** that I need that is currently provided by Paper's ``PlayerArmorChangeEvent`` (for example, although the ``PlayerItemHeldEvent`` fires when a player presses the num keys to switch their hotbar slots, it **does not get called** when the player **manually left clicks** another different item into their hotbar slot via the inventory menu).

In addition, I have also tried to implement my own "custom" PlayerHotbarChangeEvent/PlayerOffhandChangeEvent events using combinations of pre-existing Spigot/Paper events, but I find that my code faces some bugs/glitches. In all honesty, it would probably be easier (and more performant) if Paper were able to add these new events for devs to use.

**Additional context**
N/A

**Comment by JRoy** [comment]
A pull request to paper would likely be the most painless solution

**Comment by BillyGalbreath** [comment]
https://papermc.io/javadocs/paper/1.15/org/bukkit/event/player/PlayerSwapHandItemsEvent.html

**Comment by Whimsyturtle** [comment]
> https://papermc.io/javadocs/paper/1.15/org/bukkit/event/player/PlayerSwapHandItemsEvent.html

Doesn't that only work when a player press their hotbar switch key? My suggestion is to add separate event(s) that will be triggered when players change their mainhand **or** offhand items, not switch between them.

**Comment by BillyGalbreath** [comment]
https://papermc.io/javadocs/paper/1.15/org/bukkit/event/player/PlayerItemHeldEvent.html ???

Your question is very unclear. Even with the amount of words you've put, you've not told us specifically what events you want to listen to using a single event. You've listed the armor events quite nicely, but given us nothing about this "changing their mainhand/offhand items"

**Comment by Whimsyturtle** [comment]
> https://papermc.io/javadocs/paper/1.15/org/bukkit/event/player/PlayerItemHeldEvent.html ???
> 
> Your question is very unclear. Even with the amount of words you've put, you've not told us specifically what events you want to listen to using a single event. You've listed the armor events quite nicely, but given us nothing about this "changing their mainhand/offhand items"

I apologize if my wording isn't clear. Is there a version of the PlayerItemHeldEvent that you mentioned for offhand items? Or does it get called for both mainhand/offhand?

**Comment by Whimsyturtle** [comment]
I've edited my original post for further clarity / testing that I have done. Thanks!

**Comment by Machine-Maker** [comment]
Ok, so just to try and understand what you want @Wealthyturtle, You'd like an event, where when **IN** an open inventory, the player places a different item in the offhand/shield slot. Is that right?

**Comment by Whimsyturtle** [comment]
> Ok, so just to try and understand what you want @Wealthyturtle, You'd like an event, where when **IN** an open inventory, the player places a different item in the offhand/shield slot. Is that right?

No, what I am suggesting is an event that fires whenever the player’s offhand/mainhand changes, e.g. when a player picks up a new item with an empty mainhand, or a tool in their offhand/mainhand loses durability. This **shouldn’t be restricted** to the player having to have their inventory open, or the event only firing when they place a different item in the offhand slot.
