### ISSUE TITLE
it rains ignoring the blocks

### ISSUE THREAD

**Issue by ShaunaAyala** [PaperMC/Paper#2822]
What behaviour is expected:
no see the rain on roofs

What behaviour is observed:
the rain goes through blocks

Steps/models to reproduce:
![image](https://user-images.githubusercontent.com/45226984/71747618-e6a32600-2e4e-11ea-9982-873e992fe0b9.png)

Plugin list:
Fawe(world edit), EssentialsX, LiteBans, ProtocolLib, Vault, LuckPerms and world guard

Paper build number:
lasted paper 33 (1.15.1)

Anything else:
schematics, world edit or fawe

**Comment by Puremin0rez** [comment]
Are you using ProtocolSupport or ViaVersion? This is a common issue with client compatibility with different versions of the game.

When submitting issues, follow the template and provide actual information. This screenshot does not help.

**Comment by limwa** [comment]
Is this a server-side problem? I thought the server would only tell if it was raining at the client's position or not and the client would do the rest

**Comment by kennytv** [comment]
The client receives a heightmap for chunks which determines such cases of rain or beacon beams. So if that heightmap is messed up, this might happen... Tho obv there's a need for more info

**Comment by ShaunaAyala** [comment]
only paper spigot 1.15.1 lasted version without protocolsupport or viaversion all people see this

**Comment by electronicboy** [comment]
Please fill out the template.

**Comment by ShaunaAyala** [comment]
what template srry im new here :(

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/blob/master/.github/ISSUE_TEMPLATE/behavior-bug---plugin-incompatibility.md
GH shows you the template selection when you create an issue

**Comment by ShaunaAyala** [comment]
i can edit this or need create other post?

**Comment by Black-Hole** [comment]
That might be this vanilla issue: https://bugs.mojang.com/browse/MC-149791
