### ISSUE TITLE
Pathfinder.findPath() always give null

### ISSUE THREAD

**Issue by DesertFoxHU** [PaperMC/Paper#2823]
### What behaviour is expected:
Guardians coming to me

### What behaviour is observed:
Guardians are standing in one place

### Steps/models to reproduce:
1.15.1 #33 build
Try to use moveTo() or findPath(), moveTo always return false

### Paper build number:
git-Paper-33 (MC: 1.15.1) (API version 1.15.1-R0.1-SNAPSHOT)
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
Dont change anything if the target position is on ground
mob.getPathFinder() - The Pathfinder is not null, only the findPath() gives me null

**Comment by MarvinJWendt** [comment]
Hi @DesertFoxHU, could you please tell me how you fixed that?
I am stuck at the issue, that the PathFinder returns null, all the time.
Thank you :)

**Comment by DesertFoxHU** [comment]
You need to set the mob's path every second. So use a simple timer

**Comment by DesertFoxHU** [comment]
But I dont think guardians have normal pathfinder (some mobs are moving differently, for example the ender dragon).
But with Zombie it should be working

**Comment by MarvinJWendt** [comment]
I figured that out, I put the `moveTo` into a schedular. Is there no way to get the full path as a List of the blocks?
