### ISSUE TITLE
Fluids not working

### ISSUE THREAD

**Issue by GrifterMage** [PaperMC/Paper#2831]
### What behaviour is expected:
--Lava rendered as lava
--Water has its own visibility system
--Water affects player physics
--Survival players require air while underwater

### What behaviour is observed:
--Lava is rendered as water
![2020-01-08_14 22 51](https://user-images.githubusercontent.com/49353797/72022132-92b88880-3224-11ea-9649-8284008325cd.png)

--Water reduces visibility to the same degree as lava
--Water does not affect player physics (flowing water doesn't push them, players cannot swim, falling players drop right through water as though it weren't there, etc)
--Players don't drown underwater (air bubbles don't show up at all)

### Steps/models to reproduce:
Nothing required

### Plugin list:
None

### Paper build number:
git-paper-35

**Comment by BillyGalbreath** [comment]
You sir, have client issues :3

**Comment by PfluorescentZebra** [comment]
It was happening for multiple people, on a server where we were testing solely the latest spigot build.

**Comment by BillyGalbreath** [comment]
Test it again on a fresh server without any plugins

**Comment by HexedHero** [comment]
`lava pops`

A visual issue with clients maybe with resourcepack.

**Comment by GrifterMage** [comment]
A visual issue with a resource pack would not:
Stop players from drowning
Prevent players from swimming
Prevent players from being moved by flowing water
Prevent water from extinguishing players on fire
Prevent water from slowing falling players and eliminating fall damage
Prevent items from rising in water
Allow placing of water buckets in the nether

Also, no resource packs were being used by any player involved. So whatever it is, it's definitely not a resource pack issue.

The world in question was copied from a 1.14.4 server--initially there were plugins, but upon encountering this issue we disabled them to see if it was a plugin problem and restarted; that didn't fix things, and a new End dimension generated fresh showed the same problems.

We're currently deleting everything to try again with a fresh world file; will update when done with that.

**Comment by GrifterMage** [comment]
After a lot of testing, the problem seems to have been caused by a server data pack that contained some  outdated loot tables. No idea why or how a bunch of unused loot tables in a non-"minecraft" namespace being 1.14.4-formatted instead of 1.15.1-formatted could cause the server to forget that water doesn't act on entities the same way air does, but apparently they can.
