### ISSUE TITLE
1.15.1 server hangs for several minutes at a time, several times daily.  No plugins in stack traces.

### ISSUE THREAD

**Issue by BigScary** [PaperMC/Paper#2832]
To players this feels like a crash because they all lose connection and can't reconnect until the episode is over.  It usually lasts 3-5 minutes.  The below paste includes many stack traces spamming the logs.  None mention plugins as far as I can see, and likewise the timings report doesn't point to any plugins as major contributors (my interpretation anyway).

### Link/paste of stack trace

Here's a timings report capturing an incident:

https://timings.aikar.co/?id=51059200ab8e4931914275474284d98a

Here's a longer paste from logs, including many of these stack traces from a single incident:

https://pastebin.com/xrzvyykf

### Plugin list:

We have lots including some original works, but there are none mentioned in the stack traces.

### Actions to reproduce (if known):

Seems to happen when a player logs in, but not every time.  Wild guess, might be related to players' first time login after update, when the player had played on the server before the update...?  Maybe it's the first time many of the chunks surrounding that player's login location are being loaded in 1.15.1?

### Paper build number:

git-Paper-34 (MC: 1.15.1)

EDIT: Also reproduces in git-Paper-58

**Comment by electronicboy** [comment]
timings report? potentially packet spam

**Comment by Spottedleaf** [comment]
can you provide the full log please - every time the watchdog shows a stacktrace

**Comment by BigScary** [comment]
Here's a timings report capturing an incident:

https://timings.aikar.co/?id=210b85374c264eae9535eb99c5f444bb

Here's a longer paste from logs, including many of these stack traces from a single incident:

https://pastebin.com/Wt9cWgFr

Total hang time in this case was about 3 minutes (ouch!).

This APPEARS to coincide with player login events, for the first time after update to 1.15.1 from 1.14.4.  After it clears up, that player doesn't trigger the same issue again on future logins, but it can still happen for other players.

**Comment by Spottedleaf** [comment]
unfortunately that log isn't useful, although that's my fault
wait until https://github.com/PaperMC/Paper/pull/2868 is merged, update, and then provide another log - then it will give us the details we need

**Comment by electronicboy** [comment]
Are you sure that you're not generating chunks? You have a task running which blocks the main thread pretty harshly for loading/generation, which given how mojangs chunk system works in 1.14+, kinda makes me wonder if you're just blowing the server up flooding it with generation tasks

**Comment by BigScary** [comment]
> Are you sure that you're not generating chunks? You have a task running which blocks the main thread pretty harshly for loading/generation, which given how mojangs chunk system works in 1.14+, kinda makes me wonder if you're just blowing the server up flooding it with generation tasks

That's a great observation.  :)  I've been running the server this way for many months on 1.14.4 and I carefully throttled the process you noticed to keep TPS high (one chunk per 5 seconds).  I think you can see from the timings that the hang is happening related to a connection handler rather than the scheduler, though.  Also, this process continues only about 10 minutes after boot until we have enough chunks sampled.  Our hang problem continues throughout the day.

**Comment by BigScary** [comment]
Reproduced on paper-58.  New timings report:

https://timings.aikar.co/?id=51059200ab8e4931914275474284d98a

New logs:

https://pastebin.com/xrzvyykf

**Comment by electronicboy** [comment]
Looks like the chunk was stuck in the queue for generation/population

**Comment by Spottedleaf** [comment]
it looks like it's just really slow generation
can this be reproduced without plugins? we really can't tell if there are many chunks queued to be generated, which would cause something like this

**Comment by BigScary** [comment]
I've narrowed this (woohoo!).  It happens when the player who's joining logged out in a world that was deleted.  So I think this will work to reproduce:

1. Get a player into the nether.
2. Log the player out in the nether.
3. Stop the server.
4. Delete the nether world folder.
5. Restart the server.
6. Log the player in.

Expected:

Player joins in "world", at the world spawn.

Actual:

Minutes of server-wide hang, followed by the expected result.

Context:

The above process has been working very smoothly since 1.13 for me, without the hang.  The hanging started in 1.15.

We delete nether, end, and a secondary overworld (it's created by a plugin) daily during our reboot.  This gives our players an entirely new adventure every day, and we discourage building in those temporary worlds by disabling land claims there.

Theory:

My wild guess, knowing nothing about how things work, is that pre-1.15, the server wouldn't bother trying to load(generate) the chunks around the player, because the player would be moved to "world" spawn point anyway...  and post-1.15, those chunks are being generated unnecessarily.

**Comment by Spottedleaf** [comment]
does not occur locally

**Comment by BigScary** [comment]
Thanks for having another look.  I am able (with my plugins) to reproduce the issue in the nether only when I use large coordinates (logging out of the nether around -10k, 50, -10k).  I'll try to narrow this down more.  Are there any tools you can recommend?  Is there a command or API I can use to get a dump of all the chunks queued to generate along with a reason code/enum?  It would help to have a hint, otherwise I'll just be testing wild theories.  ChunkLoadEvent only fires AFTER a chunk is done, so I can't use it to track new entries in the queue, right?

EDIT: I noticed something that I'm pretty sure is new for 1.15.  Please correct me if I'm wrong.  When I log back in after the nether was deleted and having logged out in the nether around x:-10k, z:-10k, I log back in the default world **at the same coordinates**.  I'm pretty sure that previously, I woudl have found myself back at the default world's spawn point rather than at the coordinates corresponding to the nether coordinates where I logged out?

**Comment by BigScary** [comment]
So I think I've reduced this with a workaround.  When players log out, I teleport them to the spawn point in the main world which does not get deleted daily.  That way when they log back in, they're not at some far-flung coordinates where they'll trigger lots of chunk gens.

**Comment by BigScary** [comment]
So that didn't really work.  It might have reduced it, but hasn't eliminated it.  I have discovered that teleporting to one of the far-flung chunks mentioned in the logs (-17,000x, -15000z) hangs the server for several minutes, even though those chunks would have already been generated the last time a player joined that world in the same location (though there was a reboot between).  After the hang is done, I log back in at those coordinates which does NOT cause a hang, but I'm totally unable to move in any direction, despite being seemingly surrounded by nothing but air and in creative mode.  I can't even stop flying to have the server pull me down.

**Comment by BigScary** [comment]
I fixed this by optimizing a custom chunk generator in my default world.  I still don't understand exactly why it suddenly became an issue after the 1.15 update, as the inefficient custom chunk generator code hadn't changed in about 6 months.  I'm closing the bug report because I figure whatever the 1.15 change was, it isn't a bad thing **unless** coupled with an inefficient custom chunk generator.  :)  Thank you all for your patience in helping me explore this.
