### ISSUE TITLE
Sleeping player does not eject bed when teleported

### ISSUE THREAD

**Issue by JRoy** [PaperMC/Paper#2834]
### What behaviour is expected:
The player should be ejected from the bed before being teleported.

### What behaviour is observed:
The player is teleported without being ejected causing the player to lie on the ground.

### Steps/models to reproduce:
Here is the code used, you don't need to use this just teleport a player somewhere whenever they sleep.
```java
public class Main extends JavaPlugin implements Listener {

  @Override
  public void onEnable() {
    getServer().getPluginManager().registerEvents(this, this);
  }

  @EventHandler
  public void onChat(AsyncPlayerChatEvent event) {
    PaperLib.teleportAsync(event.getPlayer(), event.getPlayer().getWorld().getSpawnLocation()); //It's not a PaperLib/async teleportation issue, tested with Player#teleport as well
  }
}

```

1. Sleep in bed
2. Chat to cause the teleportation to the world's spawn point.
3. Profit

### Plugin list:
None

### Paper build number:
~~Latest~~ Paper-42

**Comment by BillyGalbreath** [comment]
You're teleporting (a non MT safe method) inside an async event. Try doing it in the `PlayerChatEvent`, or use a `BukkitRunnable` to schedule the teleport onto the main thread.

**Comment by JRoy** [comment]
@BillyGalbreath Issue still persists, I made sure to test it wasn't async weirdness beforehand :P

**Comment by BillyGalbreath** [comment]
Confirmed.

Does this happen in Spigot and CraftBukkit as well?

**Comment by JRoy** [comment]
@BillyGalbreath Problem persists in upstream as well, reported here: [SPIGOT-5509](https://hub.spigotmc.org/jira/browse/SPIGOT-5509).

Will leave this open in case md_5 decides this is intended behavior 🙃

**Comment by JRoy** [comment]
Fixed Upstream
