### ISSUE TITLE
Add composter class & methods

### ISSUE THREAD

**Issue by StealWonders** [PaperMC/Paper#2838]
**Is your feature request related to a problem? Please describe.**
I was trying to create a plugin to allow you to put more items (like bamboo) into composters as they
are very limited right now. I noticed that there is no class to cast the block to and therefore also no methods to change the fill state of one.

**Describe the solution you'd like**
I would love for someone to add the composter to the api.

**Comment by ShaneBeee** [comment]
Composter falls under [**Levelled**](https://papermc.io/javadocs/paper/1.15/org/bukkit/block/data/Levelled.html)
