### ISSUE TITLE
Dynamic view distance

### ISSUE THREAD

**Issue by thehollowedone** [PaperMC/Paper#2839]
**Is your feature request related to a problem? Please describe.**
I desire a high and dynamic view system for rendering chunks for players. This would be fantastic for my case as it is great for survival; having a view of the land really helps set your eyes on the prize of where'd you like to go next.

**Describe the solution you'd like**
A dynamic serverside view limit depending on the performance of the server.
This plugin dives into it deeper but I would assume if this feature was talked about it wouldn't implement any of the AFK detection features that help reduce performance impact of players who may have lots of chunks loaded in yet are afk.  https://www.spigotmc.org/resources/best-view-distance.61963/

**Describe alternatives you've considered**
Static per-world view limits.

**Additional context**
N/A

**Comment by electronicboy** [comment]
We expose the API (pending...) so plugins can determine when/how to do this, not really something we care to try to hassle with
