### ISSUE TITLE
Custom "Generic" Attributes

### ISSUE THREAD

**Issue by MeFisto94** [PaperMC/Paper#2840]
**Is your feature request related to a problem? Please describe.**
I wanted to implement Mana into my Plugin. Now there would obviously be armor plates which have more "mana" than others as well as  somes which have more "mana regeneration".

Apart from that I might want potions or enchantments with that attributes as well, but I guess they have different Attributes. I could still capture the events and set the attribute modifiers on the player or something.

I did *not* want to go over the hurdles of duplicating NMS's attribute accumulation code. Especially when thinking about plugin interaction, a specific attribute name `myplugin.mana.max` could be the attribute for the maximum amount of mana.

**Describe the solution you'd like**
Instead of Bukkit's Attributes being an enum, it could be a class with public static fields for the current attributes (GENERIC_MAX_HEALTH).
The problem for that is that Attributes need to be registered with the Entity in `initAttributes`.

It is **not** possible or desired, to no-op the filter mechanism in AttributeMapBase#a(MultiMap), as that will probably lead to unpredictable breakages further down the road, especially when there are things like IAttribute, which define min, max and default values (which we need).

**Describe alternatives you've considered**
I see two things as potential implementations and/or ideas, but I am open to your ideas, which is why I've opened this issue instead of a finished PR.
We have to consider two states, though you'll probably argue about the second one, which has no practical use, but is important for developing plugins:

1. The Server does a cold start. Here we just need to ensure that Plugins Register Custom Attributes early enough, say in a static list, so that every entity which is created, can register the whole list (or clones thereof).
2. The Server is reloaded. Here the Entities already exist and we need to register them later on. I don't know if this is easily possible and all that is needed is a "flush" to trigger recalculation of all active attributes. Alternatively re-equipping equipment etc.

I have thought about a way where LivingEntity would just expose something like registerAttribute, which would work with 2, but that is cumbersome for Plugins. Basically one would need to register the attribute in every line which tires to read or write attribute values, to ensure it's registered. This would still leave us with the need to flush recalculation though.

Maybe there is something I don't know, though, say we could re-create all entities during reload (however we'd be pretty much at a restart then, I suppose)

What are your ideas?

**Comment by Spottedleaf** [comment]
Is there any reason https://hub.spigotmc.org/javadocs/spigot/org/bukkit/persistence/PersistentDataHolder.html is not good enough?

**Comment by yannicklamprecht** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-5501

I gave the same answer. 😄

**Comment by electronicboy** [comment]
for just storing data, the data holder is fine; I believe that it's more the util that attributes offer, vs just being a chunk of data; Major limitation of custom attributes however is the bukkit API is designed in a way that is totally unfriendly to expansion here (yay bukkit)

**Comment by yannicklamprecht** [comment]
We could overload the API?!  All under the condition that Minecraft supports custome Attributes today. Much changed between 1.8.x and 1.15.x.

**Comment by BillyGalbreath** [comment]
The thing is, it doesn't matter where you store your data (attributes, persistent data containers, nbt, lore, a global static hashmap in your plugin). Your'e still going to have to write the logic that uses it. Minecraft won't do anything with it on its own. So I'm not sure why you can't use existing solutions.

**Comment by MeFisto94** [comment]
Yes, it's what @electronicboy described, 
> I did not want to go over the hurdles of duplicating NMS's attribute accumulation code. Especially when thinking about plugin interaction, a specific attribute name myplugin.mana.max could be the attribute for the maximum amount of mana.

So that's exactly what Minecraft _shall_ do with it, this and hopefully propagating it to the client, so that I can work together with a custom resource pack.

I mean troubles start with the ArmorChangedEvent, which is only available in Paper, I'd have to hook that, then all potion events, I'd need to hook them, etc. And then I still need to duplicate the whole structure, having additive and multiplicative Modifiers etc.

Sure, it would be faster to just code it that way, or even just shoveing all the code where it is executed every tick, but it's neither good nor beautiful.

Also a reason for proposing this is that I suspect quite a few would benefit from this, be it Mana or some kind of Sprint Energy or basically everyone wanting to go with custom/special Items. 
The set of built in Attributes is limited, what if you wanted. One could imagine better elytras with more flying speed or worse ones with a slower "deploy time", swords which have a 10% Chance of Poisoning the Enemy, whatever.

**Comment by Shevchik** [comment]
Except that client can't actually handle custom attributes well. The client actually throws an error on receive on custom attributes, just it gets ignored by the client because it generally tries to ignore all error happened in network.

**Comment by MeFisto94** [comment]
Has that changed since 1.8? On the other hand, just because it did work for that guy doesn't say the client was just silently ignoring errors.

Do you think we would have potential crashes in upcoming versions in case that behavior would change?

**Comment by electronicboy** [comment]
Basically, given the fact that the client clearly doesn't like it, while it might not crash atm, we cannot garauntee that such bad behavior will still be allowed in the future, nor can I really see a clean way to replicate this behavior using the API in a safe/clean way, I believe that this one is going to have to be a "no"; Alternatives have been given which will work just as well without upsetting the client

Would be pretty trivial to create a 3rd party API that wraps the existing mechanisms for storing data that MC provides and providing the features that the built-in attribute system exposes
