### ISSUE TITLE
Anti-xray does not work with chests or block entities

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2849]
_On version git-Paper-42 (MC: 1.15.1)_

In engine mode 1, chests that are a few blocks away and were placed by me are hidden, while chests that are part of dungeons are not.

In engine mode 2, blocks are not replaced with chests, or with any block entity. Only blocks that are not entities work in `hidden-blocks`.

**Comment by Menzani** [comment]
Did you manage to reproduce this? Making chests work in anti-xray would allow hiding them along with ores.

**Comment by BillyGalbreath** [comment]
This was never possible, and was never intended design. Orebfuscator, the plugin which this feature is based on, doesn't even do that. Instead, Orebfuscator has a proximity hider feature, which is not part of this.
