### ISSUE TITLE
Item frame duplication / popping off wall.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#285]
Paper dev 739.

@aikar @Zbob750 Item frames are popping off the wall and duplicating itself and the content it holds. Teleporting away and back, the same item frames re-duplicate and pop off the wall again. Can't replace item frames back on the wall since it already exists on the block, invisible.

Video of bug in action. 
-snip-

@nextgendan (Intelli) Also confirmed experiencing the problem on paper, with only dynmap installed.

Edit: I tested without dynmap installed, the issue still occurs. NextGenDan and I have no other plugins in common, so the problem has to be internally in Paper/Spigot/MC?

**Comment by Intelli** [comment]
Here's a snippet of a chat log from one of the players on my server, regarding the issue:

> Dupping with items in item frames happened for me again
> http://i.imgur.com/ArcAT3q.png
> Note that I was the only one online :P
> I tried to reproduce it, but It did not happen again
> Logged in now, They duped again.
> http://i.imgur.com/DouwX5S.png
> Let me relog and see to see if the item frames return.
> They duped again!
> http://i.imgur.com/07zRH1A.png
> Let me relog again.
> http://i.imgur.com/yZ2Cyr1.png
> They duped again ^
> Relogging
> http://i.imgur.com/5E4NOs3.png
> .... Let me see how many time I can do this. For science.
> http://i.imgur.com/wNUo2kS.png

Edit:

> [01:34:47] < Intelli > player first reported it to me on March 26 :D
> [01:47:47] < Intelli > >Paper version git-Paper-552 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Comment by connection-lost** [comment]
https://www.spigotmc.org/threads/chests-empty-and-item-frame-items-being-duped.147147/
Also are those item frames are at the edge of a chunk and attached to another chunk?

**Comment by mibby** [comment]
Zip of paper test environment.
https://www.dropbox.com/s/mycypnjv1l9g0c8/test-server.rar?dl=0

At coordinates -12215, 99, 6639.

**Comment by hurrgurl** [comment]
Can you still reproduce it with no plugins?
Also what makes your frames break in that video?

**Comment by mibby** [comment]
Way ahead of you hurrgurl. Already tested with Aikar using the paper test environment. So to answer your question, yes.

**Comment by zachbr** [comment]
Seeing this in CB as well with the affected regions.
EDIT: this is apparently happening in some of the very first 1.9 builds as well. Possible chunk corruption caused by third-party plugin?

**Comment by zachbr** [comment]
Looks like corruption caused by a third party.

**Comment by zachbr** [comment]
> [01:39:19] < mibby > Yeah, there it is. 5402 entities

Yep, duped entities are colliding with one another and the itemframes are removing eachother.

**Comment by BlackBeltPanda** [comment]
Was this fixed or a workaround found? I'm having the same issue.

**Comment by zachbr** [comment]
Was a corrupted chunk issue, afaik it can be resolved by removing all itemframes or all entities using an external program
