### ISSUE TITLE
Mined blocks/entities not despawning correctly

### ISSUE THREAD

**Issue by darkedlol** [PaperMC/Paper#2853]
### What behaviour is expected:
When a block is mined, it would lay dormant on the ground or group with other mined blocks that are of the same type around it. When a player walks over the blocks, it would expect to be picked up by the player and the floating block would expect to vanish

### What behaviour is observed:
Mined blocks/items are able to be picked up by the player and will appear in their inventory, however they will appear to remain on the ground and still appear floating as if they have not been picked up. 

If a player logs out and logs back in the floating blocks will have vanished and it will appear as normal.

If a secondary player is with the player that is mining the blocks, the same blocks will appear as unable to be picked up for both players. If that secondary player logs out and logs back in the floating blocks will have vanished, even if they are still appearing for the primary player

### Steps/models to reproduce:
The way to reproduce the issue is to mine blocks. There doesn't appear to be any very specific method to making it happen. Mining and having blocks drop onto the floor near other blocks is the main method in causing the issue to occur

Link to a video of the issue occurring

https://www.youtube.com/watch?v=sVEoUWu3rro

### Plugin list:
BlockLocker, CommandSigns, DiscordSRV, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, GroupManager, IridiumSkyblock, LogBlock, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, Multiverse-SignPortals, PlaceholderAPI, PlayerHeads, ProtocolLib, ProtocolVanish, Shopkeepers, Vault, WorldEdit, WorldGuard

### Paper build number:
Paper-31

### Anything else:
The issue appears to happen with any "floating" entity, such as Exp orbs will float around the player and not disappear, even though the player has "received" the Exp and it reflects in their Exp bar.
Happens with any kind of block, such as 
- Mining Diamond ore -> Diamond floats
- Mining Stone -> Cobblestone floats
- Shovelling Sand -> Sand Floats
I removed the following plugin and the issue did not resolve
- IridiumSkyblock
There are no Worldguard flags in the area that the blocks are mined

**Comment by Trigary** [comment]
Running git-Paper-43, unable to reproduce. Have you tried without plugins? One of them is surely the cause of this.

**Comment by darkedlol** [comment]
Just ran my server natively outside of plugins

Issue doesn't occur

Looks like I'm in for a long night of fun, thanks for the test :)
