### ISSUE TITLE
[Feature request] Add support for 1.9-1.9.2 clients. 

### ISSUE THREAD

**Issue by Leymooo** [PaperMC/Paper#286]
HI. How about add support for 1.9 - 1.9.2 clients?

**Comment by connection-lost** [comment]
Although I know it might hard for paper/spigot to let 1.9.4 to add 1.9.2 support, I was hoping paper may give us a surprise :)
Not pressing on you guys, but the awesomeness of paper already tastes like rainbow.

http://wiki.vg/Protocol_History#1.9.3-pre2

**Comment by ConnorLinfoot** [comment]
Just as a note either to help the paper devs or for other people you can use Protocol Support to add 1.9.2 (and lower) to 1.9.4 - https://github.com/ProtocolSupport/ProtocolSupport

**Comment by connection-lost** [comment]
@ConnorLinfoot wow, I thought protocol support was dead.

**Comment by zachbr** [comment]
We're not interested in getting into providing protocol support, even for minor versions.
Supposedly that ProtocolSupport plugin works pretty well too.
