### ISSUE TITLE
ItemFlags working unexpectedly on Tipped Arrows

### ISSUE THREAD

**Issue by soupluvr** [PaperMC/Paper#2862]
### What behaviour is expected:
Adding `ItemFlag.HIDE_ATTRIBUTES` or `ItemFlag.HIDE_POTION_EFFECTS`

### What behaviour is observed:
Arrows with either or both ItemFlags still show their potion effects. This is true whether the item has a potion or does not.

### Steps/models to reproduce:
Create an ItemStack with `Material.TIPPED_ARROW`, and set `ItemFlag.HIDE_ATTRIBUTES` or `ItemFlag.HIDE_POTION_EFFECTS`. 

### Plugin list:
MoreArrows, a custom plugin by me. Only functionality at this point is to give arrows.

### Paper build number:
git-Paper-50

Edit: Formatting

**Comment by electronicboy** [comment]
ItemFlags are handled by the client, not the server (All that information is still sent), have you tested this on vanilla by setting the flags manually or spigot/cb?

**Comment by soupluvr** [comment]
Wrote up a quick spigot plugin to give the player two tipped arrows on join. They both are just night vision arrows with a custom name and color, but one has `HIDE_ATTRIBUTES` and `HIDE_POTION_EFFECTS` and the other doesn't. The flagged arrow does not show the potion effect, and works normally. I haven't tested this in vanilla, but I'm assuming if it's not an issue in Spigot, it's not an issue doing it with Vanilla NBT.
