### ISSUE TITLE
Add a option for set the value of zombie villager transform chance

### ISSUE THREAD

**Issue by niqofdez** [PaperMC/Paper#2865]
**Is your feature request related to a problem? Please describe.**
This is 100% on difficulty hard in vanilla and allows players to infect/cure villagers over and over to cheapen their trades (all for 1 emerald). ¿What is the point of the hard difficulty then?

**Describe the solution you'd like**
Add a option for set the value of zombie villager transform chance in paper yml

**Describe alternatives you've considered**
Do nothing.

**Comment by nbastin** [comment]
Note that you would probably also need to have an option to set/eliminate the zombie villager natural spawn rate, if you are trying to have a complete solution to control availability.

**Comment by niqofdez** [comment]
Was added with #2501

**Comment by Kellero96** [comment]
Hi. Regarding this value:
zombie-villager-infection-chance: -1.0

We want to reduce the chance of getting a villager infected. Our server is setted to HARD, so with that value to -1.0, should mean "Vanilla", 100%.

Please just explain this. If i reduce that value to -0.4, the chance will be 40%?

I don't find any documentation

**Comment by nbastin** [comment]
Unfortunately, this feature is inconsistent with other percentage-based modifications (like `baby-zombie-movement-modifier`) and the value is an integer instead of a floating point value.  Also, -1.0 is just a sentinel default, not an indicator of what configured values should be.

So, if you want your chance to be 40%, you need to just set the value to 40:

`zombie-villager-infection-chance: 40`

**Comment by MaxLevs** [comment]
But what about weapons? In vanilla if a zombie has a sword in hands it just decrease villager's hp faster and after one's hp is about to 0 one can become zombie or not.. But here can it be different from vanilla? Can a sword in zombie's hand mean 100% villager's death? 
I have a server on papermc `1.17.1. zombie-villager-infection-chance` is set 50.0 and any villagers that has fight with  zombie are dead.

**Comment by Machine-Maker** [comment]
I'm confused what weapons have to do with infection chance. Don't villagers convert when they die? I don't think it matters how long it takes for the villager to die from the zombie.
