### ISSUE TITLE
Sand With paperspigot

### ISSUE THREAD

**Issue by BlueDemonic** [PaperMC/Paper#287]
how to fix it so doesnt break with explosion in paperspigot because cannons doesn't work due to this on my server please help

**Comment by zachbr** [comment]
Please follow the template.

**Comment by BlueDemonic** [comment]
wheres the template

**Comment by zachbr** [comment]
https://github.com/PaperMC/Paper/blob/master/.github/ISSUE_TEMPLATE.md

It was pre-filled into the issue as well.

**Comment by Zbob750** [comment]
Closing
