### ISSUE TITLE
Last firework rocket of a stack doesn't explode in dispenser 

### ISSUE THREAD

**Issue by FlorianANAYA** [PaperMC/Paper#2871]
Hello,

There is an issue with launching fireworks via a dispenser.

### Issue

When the firework is the last of its own item stack in the dispenser, firework effect don't trigger and no particles are displayed.
Having the exact same firework on an other stack of the dispenser does not change this behaviour.
The problem does not occur with vanilla Minecraft server or in single player.

### Steps to reproduce
Put two firework rockets (with any color/effect) in a dispenser.
Apply a redstone signal to the dispenser : a firework will launch and explode normally.
Apply a redstone signal again : the last firework will launch but not explode.

### Plugin list
This happens with no plugin. 

### Paper build number
Paper version 51 for Minecraft 1.15.1, tested on windows 8.1 64bits and Debian 9 64bits, both with java 8.

**Comment by Spottedleaf** [comment]
confirmed
