### ISSUE TITLE
portal-search-radius changes not respected in 1.15

### ISSUE THREAD

**Issue by dbkynd** [PaperMC/Paper#2874]
### What behavior is expected:
When the ``portal-search-radius`` is set to a value, this value should be used to limit the portal search radius when using Nether Portals.

### What behavior is observed:
In PaperMC for 1.15.1, regardless of the ``portal-search-radius`` setting in paper.yml, it seems to be using the Vanilla default of 128 radii. It works as expected with PaperMC for 1.14.4

### Steps/models to reproduce:
With the ``portal-search-radius`` set to 32 in ``paper.yml``
Create an Overworld portal at 0, 0
Step through the portal, generating a portal in the Nether at or near 0, 0
Go back to the overworld and create another portal at 800, 0
Step through this second overworld portal and you will be brought to the Nether portal near 0, 0

### Plugin list:
No plugins used. Freshly created Paper instance.

### Paper build number:
git-Paper-51 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

### Anything else:
With the 800, 0 overworld portal, the starting search coordinates in the nether for valid (lit) portals is 100, 0. And the portal it is finding near 0, 0 is is well outside the 32 radii.

I had read that portal searching was altered by Mojang in 1.15? Allowing portals to link above 127 (Nether Roof Portals). So perhaps a change there altered how this setting is being applied in PaperMC?

**Comment by zachbr** [comment]
Hi, there have been some changes in this area recently. Can you confirm this on the latest builds (51 at this time)?

Thanks

**Comment by dbkynd** [comment]
Confirmed am on PaperMC 51

**Comment by Spottedleaf** [comment]
see why it's not working will submit a pr
