### ISSUE TITLE
General problem with performance and with PaperAsyncTabCompleteHandler performance 

### ISSUE THREAD

**Issue by PWWP** [PaperMC/Paper#2878]
###  Timings or Profile link: 
https://timings.aikar.co/?id=8b99e0794ad24a08b70b4f9a33d00731
https://timings.aikar.co/?id=e5739def14264950b0b9859b1b5f6448

### Description of issue: 
ProtocolSupportStuff::Event: n.p.p.l.a.PaperAsyncTabCompleteHandler gives 20% of server usage. 
Minecraft::Server Oversleep always takes 40% server performance - what does it depend on and can it be reduced?
In addition, with 100 players on the server is 8 tps. Above 130 players on the server can no longer play :/. I can't see what causes this performance drop. 

I'm using Intel i7-4790K 4c / 8t 4GHz, 32Gb ram / SSD. 

### Plugin list:
WE, WG, ProtocolSupport, ProtocolSupportStuff, Essentials, WorldBorder, EntityTrackerFixer, IllegalStack, CasualProtector, VillagerOptimiser etc...

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://pastebin.com/drL9Ky62 - paper.yml
https://pastebin.com/qUDYDLXD - spigot.yml
https://pastebin.com/KEfjab6b - bukkit.yml

### Paper build number:
![obraz](https://user-images.githubusercontent.com/6884361/72668004-58b86500-3a22-11ea-81d5-c80d2555666a.png)

Essentials gc/lag command:
![obraz](https://user-images.githubusercontent.com/6884361/72668114-bac59a00-3a23-11ea-903a-aae225e046c5.png)

**Comment by electronicboy** [comment]
This issue tracker is not for seeking support with timings, issue with performance problems stemming from plugins should also be taken to the author
