### ISSUE TITLE
ChunkIO Crash

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#288]
# Crash, Stacktrace

http://pastebin.com/MyNgeBxG
### Plugin list:

Not needed.
### Actions to reproduce (if known):

Not known.
### Paper build number:

Paper 732

I'm not sure if this is already fixed in a new build. Just wanted to report in case it isn't fixed.

**Comment by aikar** [comment]
Very weird bug... The code does seem like it can be improved to avoid this case, as before 1.9.4 this wasnt possible.

But as to whats triggering it, its like its failing to generate/load a chunk.

**Comment by ghost** [comment]
The issue didn't occur again after upgrading to 736 (and higher).
I will report back if it happens with one of the newer builds again.

**Comment by ghost** [comment]
Problem does still occur with build 740:

http://pastebin.com/XHQ6N5Cm

**Comment by SecretlyJealous** [comment]
I had the same crash but I reported it to spigot a few days ago and apparently they fixed it. Guess paperspigot has not added the patch yet? 
![untitled](https://cloud.githubusercontent.com/assets/10485646/15434012/df2c325a-1eac-11e6-96ef-9bcd94df545d.png)
Here's the report: https://hub.spigotmc.org/jira/browse/SPIGOT-2282
Commit says: "Get loaded chunk"

**Comment by zachbr** [comment]
Merged with latest upstreams in build 749. Thanks for letting us know :+1:
