### ISSUE TITLE
[1.15.1 Build 58] Big Spruce tree not growing

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2880]
Hello, when I try to grow a big spruce tree, if there is a block next to the sappling and I put bone meal on the saplings next to the block, the tree does not grow.
It's annoying because you can't grow with a dispenser.
![2020-01-19_17 35 09](https://user-images.githubusercontent.com/46854473/72684582-15253000-3ae2-11ea-91f4-6bafa15f99d7.png)

**Comment by Trigary** [comment]
I don't exactly understand what is going on, but it's the same as in vanilla and is probably on purpose.

**Comment by Aurelien30000** [comment]
No, vanilla behaviour enables this configuration to work. It's a confirmed bug but you should try on Spigot first (it's perhaps a Spigot bug and not Paper) ^^

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/72685011-b78ee480-3add-11ea-835d-b69c5debdd4a.png)
Literally just dumped a full stack of bonemeal on that sapling...

**Comment by Trigary** [comment]
Apologies for the incorrect testing, but the issue seems to be deeper. Both on Paper and vanilla I seem to be able to bone meal the 2x2 tree as long as the block is only on the east/south side of the saplings. This seems to be a vanilla bug and not a feature as I have originally thought. Or at this point, I have no idea.

**Comment by Aurelien30000** [comment]
Seems to depend of the cardinal direction, works on the north for me but not with a south position :/
Indeed a vanilla bug, also apologies for the bad conclusion.

**Comment by electronicboy** [comment]
It's basically down to how the logic to look for other saplings works, it knows that it needs to look for other pairs, but likely starts searching in the wrong place, hits the block and fails the check

**Comment by ghost** [comment]
Thank you all !
