### ISSUE TITLE
Server is waiting a chunk for the thousands seconds

### ISSUE THREAD

**Issue by sandtechnology** [PaperMC/Paper#2885]
### What behaviour is expected:
Running Normally

### What behaviour is observed:
Server is waiting for a chunk(Look like is caused by a fox?) and stucking the server.
Server thread stacktrace: https://paste.ubuntu.com/p/HG7J9svXft/
Full stacktrace by jstack: https://paste.ubuntu.com/p/JmBPTwJ6rb/

### Steps/models to reproduce:
unknown

### Plugin list:
 Plugins (33): AlwaysKeepInventory*, AsyncWorldEdit, AutoMessage, ChunksExplorerLimiter*, ClearLag, ColorMOTD*, CoreProtect, dynmap*, Essentials, EssentialsSpawn, FastLeafDecay, IllegalStack, LangUtils, LimitPillagers, LuckPerms, LWC, Multiverse-Core, NyaaCore, OpenInv, PlaceholderAPI, ProtocolLib, QQBinder, QuickShop, Residence, SleepVote, TitleManager, TrChat, Vault, Wayback*, WorldBorder, WorldEdit, WorldeditFixer, yasui

### Paper build number:
52

### Anything else:
None

**Comment by electronicboy** [comment]
We need the full log, not an except of one singular trace, closing as this is likely an entity moving too fast, there are already other issues tracking this one, if you can create your own builds, there is also a patch on one of the branches which fixes this at the cost of breaking all entity movements into unloaded chunks
