### ISSUE TITLE
Owned wolves can be sitted/stand up by other players

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#2886]
### What behaviour is expected:
Players can not sit/stand up another player's dog.

### What behaviour is observed:
**Only when the dog owner is online**, other players can sit/stand up his dog.

### Steps/models to reproduce:
Right click on someone else's dog when its owner is online.

### Plugin list:
None.

### Paper build number:
git-Paper-60 (MC: 1.15.1)

### Anything else:
Also tested in vanilla 1.15.1 and 1.15.2 server. I think is a vanilla issue, but I hope you guys can fix it faster than Mojang (if you can confirm of course). Not sure if it has been reported in Jira.

Thanks!

**Comment by WI5E** [comment]
Was able to reproduce in vanilla 1.15, but not 1.15.1

**Comment by lordrius** [comment]
Hi! Looks like a reported vanilla bug [MC-167561](https://bugs.mojang.com/browse/MC-167561) Any chance to fix it? Or maybe wait for Mojang?

Many thanks!

**Comment by RiverThrough** [comment]
> 
> 
> Hi! Looks like a reported vanilla bug [MC-167561](https://bugs.mojang.com/browse/MC-167561) Any chance to fix it? Or maybe wait for Mojang?
> 
> Many thanks!

Was on my way here to say just that, also I want to confirm I personally was having the bug happening on 1.15.1 and also on 1.15.2 but as we now know it is not a paper bug
