### ISSUE TITLE
KeepAlive Timeout for slow internet

### ISSUE THREAD

**Issue by soshimee** [PaperMC/Paper#2888]
### What behaviour is expected:
___Just taking super slooooooooowwww to join the server, and be playable.___

### What behaviour is observed:
___Getting kicked for 95%___

### Steps/models to reproduce:
___Use super slow internet to join the server___

### Plugin list:
___
![pluglist](https://user-images.githubusercontent.com/45235204/72893256-f500a580-3d5b-11ea-803b-b350e4ae5f35.png)
___

### Paper build number:
___This server is running Paper version git-Paper-239 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)___

### Anything else:
___Allowing to change keepalive timeout___

**Comment by electronicboy** [comment]
Use the search feature in the future. #895

**Comment by soshimee** [comment]
that didn't help at all

**Comment by soshimee** [comment]
And I don't even have proxy, it's direct ip

**Comment by electronicboy** [comment]
Read the full topic, there is literally a method of increasing the timeout time there.

**Comment by soshimee** [comment]
It's hosting and I can not change arguments for it.

**Comment by BillyGalbreath** [comment]
> It's hosting and I can not change arguments for it.

Get a better host. Nothing we can do about limited hosts.

**Comment by drewburr** [comment]
@electronicboy this is the number one Google result. A link goes a long way.

https://github.com/PaperMC/Paper/issues/895#issuecomment-353794790

`java …. -Dpaper.playerconnection.keepalive=60 -jar …`
