### ISSUE TITLE
1.15.1 Shulker boxes disappearing into cyber space

### ISSUE THREAD

**Issue by Commander07** [PaperMC/Paper#2890]
### What behaviour is expected:
Shulker boxes should not disappear into cyber space
### What behaviour is observed:
Shulker boxes disappearing into cyber space

### Steps/models to reproduce:
idk it has only happend twice

### Plugin list:
Sleep, LuckPerms, PluginConstructorAPI, WorldEdit, TrollPRO, VeinMiner, CrispyDisguies, Vault, WorldGuard, EnchantmentSolution, Coins, Essentials, CommandPanels, QuickShop, GriefPrevention
### Paper build number:
https://i.imgur.com/F62mfBH.png

### Anything else:
I dont know if it is this but my tools are renamed to russian as a joke so i dont know if they disappear due to invalid characters or something

**Comment by VADemon** [comment]
Yes it has to do with your tool naming. They become "our tools". Thanks for the contribution to the International!

**Comment by zachbr** [comment]
You aren’t running Paper according to your version image. Seek support from Spigot.

![](https://i.imgur.com/F62mfBH.png)

**Comment by Commander07** [comment]
zachbr i though it was running paper it is my friend hosting the server using mc server soft and he selceted paper and they gave him the link and the .jar is named paper aswell

**Comment by zachbr** [comment]
The version command is the main source of truth. You (or the host) can name the jar whatever they want. That version command is what tells us what you’re really running.

In this case, it says you’re running an older version of Spigot 1.15.1

**Comment by Commander07** [comment]
i know

**Comment by HexedHero** [comment]
48 version behind and not even Paper, why are you here.

**Comment by zachbr** [comment]
Not super needed. The user made a mistake and that’s the end of it.

If you switch to the latest paper 1.15.2 build and still see this let us know. Otherwise, update and seek support from Spigot.
