### ISSUE TITLE
Unable to resolve Block Entity for ItemStack

### ISSUE THREAD

**Issue by Zzheyd** [PaperMC/Paper#2891]
Unable to resolve BlockEntity for ItemStack: minecraft:bee_nest
Unable to resolve BlockEntity for ItemStack: minecraft:beehive
Unable to resolve BlockEntity for ItemStack: minecraft:light_gray_banner

Have this with : Paper-1.15.2-b65.jar :s

**Comment by electronicboy** [comment]
You failed to use the template, but that's down to your world data being inconsistent during upgrades, no sane reason that that one could happen, generally attribute to bad plugins, etc

**Comment by endoped** [comment]
Hmm, I just started seeing this same issue on one of my servers after a paper update...no plugins changed. Might you have been a bit hasty in dismissing and closing this?

**Comment by limwa** [comment]
If you think that is the case, you need to provide enough information so that the Paper staff is able to pinpoint the issue. Try running a clean server, with no plugins and see if the issue still happens.

**Comment by endoped** [comment]
Good point, I'll see if I can track it down further when I have some time.
