### ISSUE TITLE
Hives generated by growing trees have no bees.

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#2893]
### What behaviour is expected:
0-3 bees spawned with the hive.

### What behaviour is observed:
No bees spawning. Sample size is ~10 hives (roughly 200 trees grown).

### Steps/models to reproduce:
Place flowers, grow trees, generate a bunch of hives, look for bees.

### Plugin list:
Bot*, CheaperPhysicsEvent, ChestShop, ChestShopNotifier*, ClaimslistClassifier, CoreProtect, dynmap*, Dynmap-GriefPrevention*, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsSpawn, GPAuctions, GPRealEstate*, GriefPrevention, GroupManager, InGameMotd, PlaceholderAPI, PlayerVaults*, ProtocolLib, PVPToggle*, SuperTrailsPro*, Vault, WorldBorder*, WorldEdit, WorldGuard

### Paper build number:
Paper version git-Paper-65 (MC: 1.15.2)

### Anything else:
Hoping for more feedback here because of the 5% generation rate and chance of 0 bees spawning. 

Anyone getting bees to spawn in hives generated by growing trees?

**Comment by BillyGalbreath** [comment]
This can be solved by forcing the beehive generation onto the main thread when generated from a sapling. I had this same problem in [Purpur](https://github.com/pl3xgaming/Purpur/blob/0c8fa3d50108c0b16fee47d1281d16786ac9443f/patches/server/0097-Allow-beehives-to-generate-with-saplings.patch#L49)

**Comment by rumickon** [comment]
Same issue.
Cannot find it on upstream bug tracker.

**Comment by rumickon** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-5537

**Comment by silentnoodlemaster** [comment]
and now it's patched upstream 
 https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/6515ea4957c5ebc8b88e3f7581a8a4dbb55fecb1

**Comment by MiniDigger** [comment]
oh wow https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/6515ea4957c5ebc8b88e3f7581a8a4dbb55fecb1#src/main/java/org/bukkit/craftbukkit/block/CapturedBlockState.java

**Comment by silentnoodlemaster** [comment]
wow indeed

**Comment by electronicboy** [comment]
Fixed in 83+
