### ISSUE TITLE
Adjust Minecart dismount to resolve Mojang issue MC-148869

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#2895]
**Is your feature request related to a problem? Please describe.**
Exiting a Minecart when the surrounding area is blocked places a player in the ground. 

To be clear, this has been identified as a Mojang issue. But it looks like they aren't going to solve it soon because 1.15.2 is probably the last release for 1.15.

https://bugs.mojang.com/browse/MC-148869

**Describe the solution you'd like**
Adjust the exit position so that players feet are on the tracks instead of in the ground. (If there's a block above this should at least put them into 'crawl'/swim mode. Or some better alternative.

**Describe alternatives you've considered**
We've tried adjusting builds in-game. I've also gone as far as working with GP devs on adding /trapped functionality for the Nether. That's a bit of a rabbit hole (more details in context).

**Additional context**
Our most commonly used rail system is in the Nether. Maybe not a surprise. Players are getting stuck all the time when exiting carts.

GriefPrevention doesn't offer /trapped functionality for the Nether. So I tried funding a solution there, but we hit a snag trying to find the best solution. 

GP's trapped works well in the overworld: moves players to outside a claim corner at Y ~63, usually in an area they can build. Un-trapping in the Nether isn't as straight forward because for starters there's uncertainty about the Y level. There's a roof, but putting players up there will not work for lots of servers.

I don't know if this is something Paper Devs are interested in, but Liberty Minecraft can donate some $ to support a solution here.

**Comment by BillyGalbreath** [comment]
This is a weird one to fix. I cant seem to find a happy place to spawn at. The player either falls through the floor, or takes suffocation damage from the ceiling

**Comment by NullCase** [comment]
A happy place :) yes, I too had problems with that in suggesting a new option for GP's /trapped.

How did Mojang do this prior to 1.14? Because most rails/farms were designed with those rules and worked as designed. It seems like just restoring that would solve my issue, but I don't know how to code so idk if its more complicated.
