### ISSUE TITLE
Specific 0-tick farm not working only on PaperMC (even after proper configuration)

### ISSUE THREAD

**Issue by TrendMend** [PaperMC/Paper#2898]
Hey,

there is [this ilmango farm](https://www.youtube.com/watch?v=hMtFHU6f9c0) that doesn't work in paper, it has been confirmed to work on spigot as well as vanilla server jars, but on paper it has not been working for anyone. I have configured the server properly (for 0 tick farms), and I can confirm this because I have another farm that uses an older, slower version that still works (including not working until config change). Any ideas?

**Comment by electronicboy** [comment]
paper.yml, ctrl-f "zero-tick"

edit: Okay, maybe not that; but you failed to provide any of the requested information, if you want us to look into this, provide a world file or something
