### ISSUE TITLE
Version #71 notable increases in entity lag / TPS loss.

### ISSUE THREAD

**Issue by NullCase** [PaperMC/Paper#2899]
###  Timings or Profile link:
git-Paper-71 (MC: 1.15.2) https://timings.aikar.co/?id=ca85a55686ce4e5398379a96a43cd9dd

### Description of issue:
TPS loss really picked up in this recent version. Last version it was a non-issue. We were on git-Paper-65 (MC: 1.15.2) before this. Timings looked more like this. https://timings.aikar.co/?id=b7150917269e464fa70228b0bec087c8

### Plugin list:
Bot*, CheaperPhysicsEvent, ChestShop, ChestShopNotifier*, ClaimslistClassifier, CoreProtect, dynmap*, Dynmap-GriefPrevention*, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsSpawn, GPAuctions, GPRealEstate*, GriefPrevention, GroupManager, InGameMotd, PlaceholderAPI, ProtocolLib, PVPToggle*, SuperTrailsPro*, Vault, WorldBorder*, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
unchanged before/after recent update.

### Paper build number:
git-Paper-71 (MC: 1.15.2)
Previous version: git-Paper-65 (MC: 1.15.2)

**Comment by electronicboy** [comment]
Reduce entities

**Comment by NullCase** [comment]
@electronicboy The recent performance update solved this problem. This was a legitimate issue demonstrating a change in performance.

It looks like this issue was interpreted as a request for 'technical support' (that's what Discord is for, as I know because it is expressly said many places.

How is it that a person I have blocked is even able to respond? I don't know. I blocked you for being rude and hastily misinterpreting a situation. Over a year later your first interaction has achieved the same result. Please respect my decision to block you.

https://timings.aikar.co/?id=accdf62bd509402ebf247386241f64ff

**Comment by BillyGalbreath** [comment]
You can't block a [core team member](https://github.com/orgs/PaperMC/people) from their own issues section..

**Comment by NullCase** [comment]
That makes sense, thanks.

**Comment by electronicboy** [comment]
> This was a legitimate issue demonstrating a change in performance.

Which is cool, but, you didn't exactly show that. We and the core team have literally 0 interest in trying to find specific builds which introduce performance regressions, we don't have the ability to jump through every single build in hopes of trying to find the troublesome build, even if we did have the time or means to do so, which, we don't. If you want us to treat this as a build induced performance regression, pinpoint specific builds for us, don't just slam timings from two arbitrary versions and expect us to magically find the build which introduced such regression.

There isn't a single build between 65 and 71 which would have likely introduced any form of performance regression, given that with the only difference I saw between your two timing reports, I severely doubt that the version change is as of much importance here, especially given that your 71 report has a lot of issues from entityTick spikes, which given the varying nature of entity AI introduces lots of variables into the mixture, heck, even your latest report shows that you're ticking less entities per tick, 1.2k/pct, vs 71 with 2.1k/pct, and 61 with 500/pct, given that the recent "performance update" was a trivial set of patches with very little in the way of actually boosting performance, heck, your server is still performing worse on 84 vs 65, I'd point to the fact that you've more than halved the number of ticking entities is much more of an improvement to your servers situation than the build numbers.

If you want to actually report build performance regressions, identify the build and provide info. Don't just effectively dump timings between two different versions and expect us to just take that as a build induced regression, especially as somebody who can read timings, I'm going to read them and spot things like the entity tick count being doubled between builds and tell you the standard advice that we tell everybody else having heavy TPS loss with heavy entity counts. I'm fairly convinced that anybody else looking at this report would have likely taken the exact same route of recommending you to reduce the entities, yes, my response was haste, I'm having health issues and so trying to deal with issues as and when I can, I see reports similar to your 71 builds 20 times a day on all versions (even the very latest builds!), hence, you got given the exact same advice given to everybody else where entityTick is eating away a majority of the tick time.

I hope my explanation shows you where I'm coming from and that your way of reporting this was pretty lackluster, but, going forward, if you don't want any interaction with me, quite simply, don't use our issue tracker. You don't get to pick and choose who deals with your issue reports nor do I really care to avoid dealing with issues from people who have elected to take an issue with me, I have better things to do than manage a list of people to avoid. You're also more than welcome to actually communicate with us if our initial assessment of issues is incorrect, we have a discord as well as the issue tracker here where you could have stated that, instead, you opted to partake in no discussion and even later came back to effectively stick a middle finger up.

**Comment by NullCase** [comment]
I'm not reading any of that. You work hard, I don't know why because clearly you do not respect or think the people you support are worth your effort. Do not contact me again.

**Comment by Draycia** [comment]
🍿 Trying your hardest to convince him to start keeping a list huh?

**Comment by mikroskeem** [comment]
>I'm not reading any of that.

Who needs help in the end, is it you or...? We don't really have to waste our time for such childish behavior. As mentioned before, don't use Paper's issue tracker then.

**Comment by zachbr** [comment]
> going forward, if you don't want any interaction with me, quite simply, don't use our issue tracker. You don't get to pick and choose who deals with your issue reports nor do I really care to avoid dealing with issues from people who have elected to take an issue with me, I have better things to do than manage a list of people to avoid. You're also more than welcome to actually communicate with us if our initial assessment of issues is incorrect, we have a discord as well as the issue tracker here where you could have stated that, instead, you opted to partake in no discussion and even later came back to effectively stick a middle finger up.
