### ISSUE TITLE
feature request: use GraalVM to AOT Paper and plugins if enabled

### ISSUE THREAD

**Issue by mio-19** [PaperMC/Paper#2900]
**Describe the solution you'd like**
use GraalVM to AOT compile Paper and plugins if enabled
It may greatly improve Paper performance and reduce startup time

**Describe alternatives you've considered**

**Additional context**

**Comment by electronicboy** [comment]
We have no interest in shipping native images

**Comment by MiniDigger** [comment]
why do you need anything from paper to do this? if you want native images, compile them yourself?

**Comment by mio-19** [comment]
@MiniDigger `Dynamic Class Loading` is not supported by Native Image

**Comment by yannicklamprecht** [comment]
> @MiniDigger `Dynamic Class Loading` is not supported by Native Image

How should Paper handle a problem that you can't handle yourself? Open source projects live from pr by example. Do you assume that Paper can magically compile everything into a big uber native image?!

**Comment by mikroskeem** [comment]
At best you can AOT vanilla server tbh
