### ISSUE TITLE
paper-74 breaks compatibility with Multicraft

### ISSUE THREAD

**Issue by zlainsama** [PaperMC/Paper#2902]
### What behaviour is expected:
Sending commands through web console working fine.

### What behaviour is observed:
Sending commands through web console doesn't work at all.

### Steps/models to reproduce:
Update to paper-74, send commands through web console in multicraft, and observe no response from web console and logs.

### Plugin list:
ViaVersion-3.0.0-SNAPSHOT
viabackwards-all-3.0.0-SNAPSHOT
HelperCheat-0.0.1-SNAPSHOT

### Paper build number:
It was 74 before reverting to 73.

25.01 04:58:39 [Server] INFO This server is running Paper version git-Paper-73 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
25.01 04:58:39 [Server] INFO Checking version, please wait...
25.01 04:58:41 [Server] INFO Previous version: git-Paper-74 (MC: 1.15.2)
25.01 04:58:41 [Server] INFO You are 1 version(s) behind

### Anything else:
I also tested without any plugins in a new world, and observed same result.
My server provider are using a very old version of multicraft, this might not happen with latest multicraft, but i'm stuck with the old version because of my server provider.
Please revert commit a0438faba9d98c6fb23c7f6876c21d110ba5783b.

**Comment by electronicboy** [comment]
MUUUULTTIIIICRAAAAFFFTTTT....
