### ISSUE TITLE
Player NPCs With Citizens2 Load Spawn Chunks and Cannot Be Unloaded

### ISSUE THREAD

**Issue by Kas-tle** [PaperMC/Paper#2905]
### What behaviour is expected:
When `keep-spawn-loaded: false` is set in paper.yml, spawn chunks should not be loaded.
When no player is within view distance of an player-NPC-containing chunk, that NPC and chunk should not be loaded.

### What behaviour is observed:
When a player NPC is present, keep-spawn-loaded is ignored and spawn chunks load. The amount of spawn chunks loaded depends on the view-distance in server.properties.
When no player is on the server or within view distance of the player-NPC-containing chunk, the chunk remains loaded.

### Steps/models to reproduce:
1. Create a clean server with the latest build of Paper 1.15.2 (67 at time of test)
2. Install EssentialsX for chunk counting (Paper alone may be used, but you must subtract "Inactive" chunks from "Total" chunks to get the loaded chunk value. If using this method, substitute `lag` for `paper chunkinfo` in later steps).
4. Start server and accept EULA to create configuration files.
5. Set `keep-spawn-loaded-range: 0` and `keep-spawn-loaded: false` in paper.yml.
6. Restart server, set `gamerule doMobSpawn false` in console, join, and `/tp 0 100 1000` to get far away from spawn chunks. If entities are present, remove with `/minecraft:kill @e[type=!player]`
7. Run `lag` in console and note the number of chunks loaded.
8. Run `/npc create notch` to spawn an NPC
9. Run `lag` in console again. The number of chunks loaded should have roughly doubled due to the loading of spawn chunks.
10. Leave the server.
11. Run `lag` from console and note the number of chunks loaded.
12. Run `npc delete notch` from console.
13. Run `lag` from console. There should now be 0 chunks loaded.

### Plugin list:
EssentialsX, Citizens2

### Paper build number:
git-Paper-67 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
With no players present, on `paper debug chunks`, checking for the chunk containing the NPC, there is a ticket present for said chunk, so this might have something to do with Spigot Server [Patch 0375](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0395-Asynchronous-chunk-IO-and-loading.patch).
```
    {
     "x": 0,
     "z": 62,
     "ticket-level": 33,
     "state": "BORDER",
     "queued-for-unload": false,
     "status": "minecraft:full",
     "tickets": [
      {
       "ticket-type": "unknown",
       "ticket-level": 33,
       "object-reason": "[0, 62]",
       "add-tick": 1810
      }
     ]
    },
```
This issue does not occur on Spigot or CraftBukkit.

**Comment by Spottedleaf** [comment]
Given citizens uses actual player objects in the world, they are treated as such and will load chunks.

**Comment by Kas-tle** [comment]
@Spottedleaf Fair enough, but what is causing the spawn chunks to be rendered only when a player NPC is present then, despite having the setting turned off? If I, myself log on, go far from the spawn chunks, and create an player NPC, the loaded chunks double. If I remove said NPC, the loaded chunk count goes back to normal. So it seems like player NPCs are somehow being treated differently than players. I suppose I should also mention that the default behavior of Citizens is to not load chunks for player NPCs, and it is successful in preventing this on Spigot.

**Comment by Spottedleaf** [comment]
I can't say unless you provide a chunk debug report (and it's very much not likely our end for this)

**Comment by Kas-tle** [comment]
NPC Only: [chunkdebug-npc_only.txt](https://github.com/PaperMC/Paper/files/4113311/chunkdebug-npc_only.txt)
Player + NPC: [chunkdebug-player_and_npc.txt](https://github.com/PaperMC/Paper/files/4113312/chunkdebug-player_and_npc.txt)
Player Only: [chunkdebug-player_only.txt](https://github.com/PaperMC/Paper/files/4113313/chunkdebug-player_only.txt)

**Comment by Spottedleaf** [comment]
All I see is player chunks, which lines up with what I said before - citizens. This is their issue given the misuse of the player object. I don't know how they handle it and I'm not interested in debugging their issues.

**Comment by Kas-tle** [comment]
Where the NPC is present in 0, 62, there are no nearby player chunks. All the player chunks are centralized around the spawnpoint. But, if you are not willing to look into it I understand. I will ask them if they are willing to pursue it further, as I came here at their advice since I could not replicate on Spigot. Sorry for any trouble.

**Comment by fullwall** [comment]
Just to chime in here because I don't have access to my full debugging environment right now - Citizens removes the player entities from the server player list and Spigot unloads the chunks correctly. This appears to be a Paper-only issue. Is there some API we should use to allow these chunks to unload?

**Comment by electronicboy** [comment]
keep spawn is irrelevant, but the fact that there is a player entity there is keeping tickets in place which will keep those chunks loaded due to the ticket system... Paper relies upon tracking entities in the world properly, so this is one of those "bleh" situations...

```
> paper entity list * world
[14:36:05 INFO]: Total: 39
[14:36:05 INFO]:   12: minecraft:cow
[14:36:05 INFO]:   11: minecraft:sheep
[14:36:05 INFO]:   8: minecraft:pig
[14:36:05 INFO]:   2: minecraft:item
[14:36:05 INFO]:   2: minecraft:rabbit
[14:36:05 INFO]:   2: minecraft:villager
[14:36:05 INFO]:   1: minecraft:falling_block
[14:36:05 INFO]:   1: minecraft:player
> list
[14:36:12 INFO]: CONSOLE issued server command: /list
[14:36:12 INFO]: There are 0 out of maximum 20 players online.
>
```

**Comment by UnknownSilicon** [comment]
I know this is a very old issue, but I am able to replicate this on the latest Paper + Citizens versions on 1.17.1

**Comment by Drift91** [comment]
> given the misuse of the player object.

Is there an alternative way to render a player entity without using a player object?

I'm also curious as to why this isn't an issue on Spigot but is on Paper; Is there some kind of difference in the API that Citizens2 needs to account for?

**Comment by mcmonkey4eva** [comment]
`I'm also curious as to why this isn't an issue on Spigot but is on Paper;`
It's literally related to a feature that *only exists* on Paper - a specific minor optimization in the `paper.yml` doesn't function when there's an NPC in the way. (On Spigot, spawn chunks are just loaded all the time regardless)
It doesn't affect much of anything beyond the one particular minor optimization not happening, which really just means there's a small bit of extra RAM use, so it's a fairly low priority issue.

**Comment by Drift91** [comment]
> On Spigot, spawn chunks are just loaded all the time regardless

Hmm, I thought I'd seen a couple of complaints elsewhere that plugins such as Multiverse were able to unload the chunks on Spigot but not on Paper when NPCs were present. I suppose that would be because Paper handles it natively and overrides Multiverse while Spigot has no such functionality?
