### ISSUE TITLE
Bees freeze and don't die below Y: 0 

### ISSUE THREAD

**Issue by SirvydasS** [PaperMC/Paper#2906]
### What behaviour is expected:
___I expect to see when a bee flies below Y: 0 she doesn't freeze and she will die.___

### What behaviour is observed:
___I saw in my skyblock map (where is everywhere void) about 10 bees is frozen (not moving and not dying) about Y: -7.___

### Steps/models to reproduce:
___Spawn bee near Y: 0 it need bee will fly below Y: 0 by oneself and when she flies below she freezes. If you spawn bee below Y: 0 she immediately falls down to void and dies.___
![2020-01-26_09 11 42](https://user-images.githubusercontent.com/8950371/73132425-a71dc300-4023-11ea-9ca5-826b37233f0e.png)

### Paper build number:
___This server is running Paper version git-Paper-71 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)___

**Comment by Trigary** [comment]
Vanilla bug. After some time they just stop flying around and hover in one place. And if you summon a bee below Y: 0 it just drops like a rock. At least those die.
PS: I just realized you also said that. I guess it's too early for me.

**Comment by BillyGalbreath** [comment]
Mojang doesn't care about this issue (marked as invalid) https://bugs.mojang.com/browse/MC-167279

I have a simple fix, which is to apply gravity to bees if they go below Y 0. This ensures they fall far enough to die and don't just get stuck in the void.

https://youtu.be/abvpAkGsz78
