### ISSUE TITLE
Blocks disappear and holograms

### ISSUE THREAD

**Issue by car1ot** [PaperMC/Paper#2907]
**TESTED VERSIONS: 1.12 and below**

### What behaviour is expected:
Normal

### What behaviour is observed:
Holograms disappear in client-side, and sometimes blocks when unloading chunks and loading again.

### Steps/models to reproduce:
Go out from chunk and go back. Also ask friend to build something out of your view distance and come back to friend's building. There gonna be "invisible" glitched blocks.

### Plugin list:
Protocol support, HolographicDisplays

### Paper build number:
[13:51:50 INFO]: This server is running Paper version git-Paper-77 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[13:51:50 INFO]: Previous version: git-Paper-33 (MC: 1.15.1)
[13:51:50 INFO]: You are running the latest version

### Anything else:
no

**Comment by Trigary** [comment]
> TESTED VERSIONS: 1.12 and below

> This server is running Paper version git-Paper-77 (MC: 1.15.2)

Which one is it then? Or is 1.12 the client version?

Also, is this a paper-specific issue? Is this something that's not present in Spigot? Is this not a bug in those plugins?

**Comment by car1ot** [comment]
> > TESTED VERSIONS: 1.12 and below
> 
> > This server is running Paper version git-Paper-77 (MC: 1.15.2)
> 
> Which one is it then? Or is 1.12 the client version?
> 
> Also, is this a paper-specific issue? Is this something that's not present in Spigot? Is this not a bug in those plugins?

_**The client version, where bug appears is 1.8.8. Also bug appears only on aminated holograms! When you teleport into unlodaded chunk, and it slowly loading, animated holograms disappear.**_

**Comment by electronicboy** [comment]
So, you're saying that you can't replicate this on a 1.15.2 client on a 1.15.2 server?

**Comment by yannicklamprecht** [comment]
When 1.15.2 clients have no issue.
It's clearly not a Paper bug, more of a protocol hack bug. Report it to protocol support.

When you can replicate it on 1.15.2 both client and Server without using a protocol hack we will listen again.
