### ISSUE TITLE
ScriptCraft - "No JavaScript Engine available."

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2908]
### What behaviour is expected:
ScriptCraft is a plugin that allows players to write custom scripts for the server.

### What behaviour is observed:
As of paper 1.15 build 63, the plugin fails to load and displays the following error:
```
[11:11:40] [Server thread/INFO]: [scriptcraft] Enabling scriptcraft v3.4.0-2019-01-20*
[11:11:40] [Server thread/ERROR]: [scriptcraft] No JavaScript Engine available. ScriptCraft will not work without Javascript.
```

### Steps/models to reproduce:
First, download paper build 63 here:
`https://papermc.io/ci/job/Paper-1.15/63/`
Next, download ScriptCraft 3.4.0
`https://github.com/walterhiggins/ScriptCraft/releases/tag/3.4.0`
Finally, run the server with ScriptCraft installed in the `./plugins` directory.

### Plugin list:
ScriptCraft

### Paper build number:
git-Paper-62

### Anything else:
I have been told to "use craftbukkit" and "install the JDK" however neither of these have solved the issue. Perhaps there is something there, but I doubt it.

**Comment by electronicboy** [comment]
Nothing to do with paper, your java environment is missing a javascript engine

**Comment by ghost** [comment]
@electronicboy I have tested the plugin on build 62 and previous, and it works fine. How can the same version of java both have and not have a JavaScript engine?

**Comment by electronicboy** [comment]
Paper doesn't and has never bundled its own javascript engine, no idea how upgrading the server would have any form of relevance here

**Comment by ghost** [comment]
@electronicboy Let me put it this way. In a controlled environment with the same version of Java, the same plugins, and the same files and configurations, the only thing changed is the server version, and that change causes it to break. Could this be a compatibility issue?

**Comment by electronicboy** [comment]
No idea what version of java you're using or anything, but this has literally nothing to do with paper, only concern would be in environments with other plugins is the fact that there is no garauntee to enabling order outside of dependencies, could be pure happenchance that some other plugin is bundling in a scripting engine and started up earlier in your other tests

The scripting engine is between the plugin and the JRE, no idea if the version you're using bundles nashhorn or not, or if it was relying on something else bundling it, no idea if newer JVM versions bundle nashhorn with them or not

**Comment by ghost** [comment]
@electronicboy Well, I ran 2 tests, a control and a live test. The control tested version 62 and 63 of paper with 1 plugin: ScriptCraft. The live test did the same, but included my standard plugin loadout on the main server. In both instances, the same result occured. This is looking more and more like a compatibility issue with 1.15.2, perhaps something mojang did or perhaps some unintended side effect of a change somewhere along the line. I will be focusing my debug efforts on the ScriptCraft plugin repo from now on. Thanks for the help.

**Comment by MiniDigger** [comment]
in this whole thread you havent once stated the java version and jvm distribution you use, which is the actual software which bundles the javascript engine.

**Comment by ghost** [comment]
@MiniDigger yep, that's my mistake. however this issue had nothing to do with paper, and in fact was a compat issue like i suspected. it's been fixed by the plugin developers and needs no further follow-up.

**Comment by kangarko** [comment]
@MiniDigger @electronicboy same for my products, oddly enough NOTHING has changed I literally run Minecraft 1.15 and 1.15.2 in my IDE using the same Java 8 JDK and the latter version could not find the engine.

Luckily I found solution here: https://github.com/walterhiggins/ScriptCraft/commit/5650c495177df174ecb81d43f02959bd70a698ba

What have you done to the way plugins are loaded in the server that's causing this?

**Comment by electronicboy** [comment]
We've literally changed nothing here, nor has upstream done anything that would affect this to my knowledge, given how scripting engines are accessed, this is more a JRE environment thing

**Comment by kangarko** [comment]
As we told you, nothing has changed on our computers, see https://www.spigotmc.org/threads/1-15-2-missing-nashorn-javascript-engine-scriptenginemanager.415648/#post-3682327

**Comment by kangarko** [comment]
Something has to have changed on the server since that is the only variable that was swapped during my testing.

**Comment by Trigary** [comment]
Upstream did add those "accessed plugin XY without declaring a depend/softdepend/loadbefore on it", could this somehow be connected to that? They had to mess with the classloader to some extent to detect these, hadn't they?

**Comment by wizjany** [comment]
Pretty sure plugin classloaders already worked that way - they just added messages to things.

**Comment by electronicboy** [comment]
probably: 

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/acc05b4092c6324cd471fada343553fe2df4d6b9

Basically, the fact that this worked in the first place was likely a bug

**Comment by jkenefick** [comment]
So whose responsibility is it to fix this?  As a scriptcraft consumer who is experiencing this issue, what do I do to fix this issue?

**Comment by BillyGalbreath** [comment]
> So whose responsibility is it to fix this? As a scriptcraft consumer who is experiencing this issue, what do I do to fix this issue?

Upgrade scriptcraft, it was fixed already as stated above

**Comment by Trigary** [comment]
I am a bit late, but whatever, I have already written most of what I wanted to say...

> So whose responsibility is it to fix this? As a scriptcraft consumer who is experiencing this issue, what do I do to fix this issue?

ScriptCraft has already fixed this issue, see [kangarko's link](https://github.com/walterhiggins/ScriptCraft/commit/5650c495177df174ecb81d43f02959bd70a698ba). The latest release on their GitHub does not contain this fix, however. So ask them to update their downloadable release or build it yourself.
