### ISSUE TITLE
BeastX Xray Texture pack bypasses paper anti-xray

### ISSUE THREAD

**Issue by Agaloth** [PaperMC/Paper#2909]
**Is your feature request related to a problem? Please describe.**

This xray Texture pack bypasses the current git-paper-239 (1.14.4) anti-xray : https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/2851461-1-8-1-15-beastx-collection-bigtreasure-norain

**Describe the solution you'd like**

I would like to get that texture pack non working with the current paper's anti-xray, I host a towny earth server and the ressources are limited.

**Comment by Black-Hole** [comment]
Not possible with how Minecraft handles chunks.
You might want to remove or cover all ores with adjacent air blocks.

**Comment by electronicboy** [comment]
only exposed blocks will be visible in these packs, outside of expensive computation, there is no way to prevent this
