### ISSUE TITLE
Add spawn-limits as per-world option

### ISSUE THREAD

**Issue by imDaniX** [PaperMC/Paper#2910]
**Is your feature request related to a problem? Please describe.**
I don't want to see so many mobs in nether or in the end, but I can't deal with it without some third-party plugins.

**Describe the solution you'd like**
spawn-limits section(like in bukkit.yml) in world-settings section(paper.yml).

**Describe alternatives you've considered**
Do nothing.

**Comment by imDaniX** [comment]
Was hopping for https://github.com/PaperMC/Paper/pull/2982, but it's just whoped out of the way.

**Comment by aikar** [comment]
I intend to pull that soon

**Comment by imDaniX** [comment]
\*patiently waiting*
