### ISSUE TITLE
EAR doesn't work as expected in 1.15.1 #59 and later

### ISSUE THREAD

**Issue by snurre0** [PaperMC/Paper#2911]
### What behaviour is expected:
Entities being ticked only every so often when outside the entity-activation-range set in spigot.yml.'
Video of expected behaviour: https://www.youtube.com/watch?v=uEqQ4JGQlm0
EAR is set to 2 for the demonstation.

### What behaviour is observed:
A lot of the entity types that only get ticked once in a while in spigot, is now getting ticked at normal rate in paper, even if outside the EAR.
Video of unexpected behaviour in paper-59 and later: https://www.youtube.com/watch?v=_ssdSEq-b0I
EAR is set to 2 for the demonstation.

### Steps/models to reproduce:
- Set EAR to 2 for all entities
- Spawn a cat and a creeper next to each other
- Fly away from the creeper, at least 2 blocks

### Plugin list:
Happens without plugins

### Paper build number:
[22:07:29 INFO]: This server is running Paper version git-Paper-59 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

### Anything else:
I have tested a lot of different mobs, this is what works and don't works, when it comes to EAR:
Works for: adult pig/sheep/cow, adult and baby villagers, 
Does not work for: baby pig/sheep/cow, cats, creeper/zombie/spider, fish, bats, adult and baby bees, adult and baby foxes.
I know that baby animals might be intended not to work.

Would also be nice to have this work for water mobs, doesnt seem to work in any version.

kickash32 mentioned at discord, that this bug might be a result of trying to improve stuff for the EAR in paper-59

**Comment by kickash32** [comment]
Please test build 78.

And yes, baby animals do intentionally immune from EAR.

**Comment by snurre0** [comment]
Seems to work much better now, thank you!
I guess it's intended that mobs with active tasks does not respect the ear while doing their tasks.
Other than that, most seems to be back to how it was. 

Thanks again!
