### ISSUE TITLE
applyMending throws nullpointerexception if the player doesn't have any eq with mending

### ISSUE THREAD

**Issue by Xeonmeister** [PaperMC/Paper#2916]
### What behaviour is expected:
applyMending(n) and giveExp(n, TRUE) should try to apply mending but if the player has no mending on any eq then he should just get the experience. (or maybe only get the exp with the giveExp and not with applyMending im not sure)

### What behaviour is observed:
Until the player has at least one eq with mending everything works fine. But if you have no eq with the mending enchant these 2 methods will start to throw nullpointerexceptions.

### Steps/models to reproduce:
call either applyMending(n) or giveExp(n, TRUE) on a player who wears no mending enchanted equipment.

### Paper build number:
1.15.2 b80

**Comment by electronicboy** [comment]
It's much faster for us and much more likely to see issues like this patched if you actually provide information such as the errors, otherwise, we have to run around and reproduce it ourselves which takes more than should be needed, and pushes even the smallest of issues down the todo list.

**Comment by Trigary** [comment]
This issue can be closed :)
