### ISSUE TITLE
World creation exception getChunkAT only on paper 

### ISSUE THREAD

**Issue by DevJoey** [PaperMC/Paper#2920]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

https://hasteb.in/yuwomosu.md

### Plugin list:
___A list of your plugins___
Multiverse
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Create a world with multiverse
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
 This server is running Paper version git-Paper-86 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[21:01:05 INFO]: You are running the latest version

**Comment by electronicboy** [comment]
Those warnings are just saying that your server is taking too long to tick, this is pretty much expected given the speed of world generation, you can disable spawn chunks in paper.yml if you wanna speed this up
