### ISSUE TITLE
Projectile CustomModelData

### ISSUE THREAD

**Issue by DesertFoxHU** [PaperMC/Paper#2921]
**Is your feature request related to a problem? Please describe.**
Items can have custom model data, but projectiles cant have

**Describe the solution you'd like**
Maybe projectile.setCustoModelData or projectile.setItemStack or an option to launch an item like projectiles (not throwning)

**Comment by electronicboy** [comment]
CustomModelData only works for itemstacks, you can't also just substitute one entity for another without side-effects; You could probably use protocollib and deal with the packet trickery for this yourself, no idea to what extent you can get away with that, however, to my understanding, you wouldn't be able to control the orientation of said item, etc

**Comment by Shevchik** [comment]
However since 1.15 projectiles has data watcher that holds full itemstack instance inside of it.
Tho i'm not sure if adding cusotmmodel data tag to that item will work, but that worth a try.
