### ISSUE TITLE
Cobblestone Generator

### ISSUE THREAD

**Issue by SmoTHyG** [PaperMC/Paper#2929]
Hi, I'm trying to make a cobblestone generator like in the image ( https://imgur.com/ggOZjdN ) without transforming lava into obsidian.
When I mine the ore the lava transforms into obsidian

I want to know how to make that, and I heard is a solution with paperspigot.

I'm waiting for suggestions.

**Comment by JRoy** [comment]
wtf

**Comment by limwa** [comment]
Just break the block below each water block and move the water sources away from the ores by one block. It should fix the bug.

**Comment by rvveber** [comment]
Well water flows quicker than lava, so it will flow into the lava and make it obsidian wont it?
Don't know why this is an actual issue that belongs here

**Comment by LuigiGamingLP** [comment]
Fluid source Blocks always check for air around them. If there is any, they will spread. Water spreads faster than lava. If it hits a block flowing down, it seeks the fastest path down. If water slightly touches flowing lava, the lava will turn into cobblestone. Thus: the first line should be water sources, some blocks to stop it flowing in the lava and the second line downwards just lava source blocks

That way you can expand the farm lateron.
