### ISSUE TITLE
Paperclip.jar is NOT unloading chunks and creating terrible TPS

### ISSUE THREAD

**Issue by TomLewis** [PaperMC/Paper#293]
Just built and run the latest version of Paperclip.jar to see if this 1.9.4 issue was resolved, but it still hasn't, somehow there is 19,000 chunks loaded. Its not unloading chunks.
/version shows.
git-paper-741

Im going to move back to Spigot to see if this is an issue or not.

**Comment by zachbr** [comment]
Duplicate of GH-284
