### ISSUE TITLE
spawn-animals=false | animals still spawning

### ISSUE THREAD

**Issue by BijuuKrunos** [PaperMC/Paper#2931]
### What behaviour is expected:
I don't want that animals spawn in the world

### What behaviour is observed:
Animals...

### Steps/models to reproduce:
create new world or generate new chunk with this:
in server.properties:
spawn-animals=false

### Plugin list:
No Plugins

### Paper build number:
This server is running Paper version git-Paper-90 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
even with /gamerule doMobSpawning false
animals still spawning.

Option is working for monsters and villagers.

**Comment by electronicboy** [comment]
tested on spigot? CB? vanilla?

**Comment by BijuuKrunos** [comment]
-.- menno
Vanilla: yes
Craftbukkit: no
spigot: no
paper: no

okey.. sry. i go to Craftbukkit/Spigot...
