### ISSUE TITLE
Font Formatting &m and &n not (always) working

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#2933]
### What behaviour is expected:
&m and &n working always

### What behaviour is observed:
Since 1.15, `&m` and `&n` are skipped in formatting in some certain places like the header of the player tab list, or the last line of the scoreboard.
When a bossbar is active, the formatting appears.
When the bossbar disappears, the formatting disappears.
The number of lines in the scoreboard is irrelevant, always the last line is affected.

### Steps/models to reproduce:
Download any scoreboard plugin, like e.g Featherboard.
Set it up and make the last line something with `&mStrikethrough` or `&nUnderline`
Check to see if formatting is applied.
Check what happens when a bossbar is active (mcMMO, vanish plugin, etc)

### Plugin list:
Any scoreboard plugin

### Paper build number:
git-Paper-90 (MC: 1.15.2)

**Comment by electronicboy** [comment]
> When a bossbar is active, the formatting appears.
When the bossbar disappears, the formatting disappears.

Both of these are aspects of the client, not the server, the server does not care if you have a bossbar or whatever displayed when formatting text
