### ISSUE TITLE
DisableJavaSafteyCheck startup argument

### ISSUE THREAD

**Issue by LogGits** [PaperMC/Paper#2935]
**Is your feature request related to a problem? Please describe.**
Running paper on newer java (e.g. 14 aka 58.0) versions causes:
`Unsupported Java detected (58.0). Only up to Java 13 is supported.`

**Describe the solution you'd like**
A jvm arg that allows for disabling that safety check. e.g. `-DisableJavaSafetyCheck`

**Comment by BillyGalbreath** [comment]
Not a paper issue

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/Main.java#153

`-Djava.class.version=58.0`

**Comment by MiniDigger** [comment]
I don't think overriding the class version like that should be the recommended way to disabled that check.

I personally just straight up removed that check because its stupid, but if core team would accept a PR to add such an option I would happily step up to do so.

**Comment by electronicboy** [comment]
I honestly detest the idea of having such trivial patches lying around, but
kinda support people's right to shoot themselves in the foot if they so
wish...

**Comment by zachbr** [comment]
So as annoying as it is, it does serve a purpose given the whole legacy plugin rewrite system they have in place.

I too support a bypass however. I’d still like it to print the warning to console for support reasons but there’s no reason it has to prevent the server from starting.

The real question is do we remove that return entirely or just offer another system property to bypass? I’m more on the side of a system property myself but open to thoughts. This is a small change so I’ll make it myself after feedback.

**Comment by Zrips** [comment]
@zachbr 
Some way to bypass this protection would be nice to have, but I'm not talking about config option, some allot more complicated to do, just to eliminate someone turning this protection off without knowing what it actually does. Like @LogGits said, it could be jvm argument like that same -DisableJavaSafetyCheck and then we could get some scary line at startup informing that Java version is not supported and all that jazz but it would still load. People might want to test new versions of Java without any need to recompile their own version without those 4 lines of code. 
Option - is always something nice to have.

**Comment by MiniDigger** [comment]
I would suggest
```diff
+ if (!Boolean.getBoolean("AllowUntestedJavaVersions")) return;
- return;
```

**Comment by BillyGalbreath** [comment]
```-DIReallyWantThisJavaVersionAndKnowWhatImDoingISwear```
