### ISSUE TITLE
Cactus not growing

### ISSUE THREAD

**Issue by Glenndiscord** [PaperMC/Paper#2939]
### What behaviour is expected:
I made a cactus 0 tick farm andi expected it to work, tried doing it north and south then east and west still didnt work. I tried growing cactus normally and even that doesnt grow so I dont know whats up but pretty sure its something to do with paper

**Comment by Trigary** [comment]
As far as I know, 0 ticks farm are disabled by default in paper.yml or somewhere similar. Have you enabled them?

**Comment by Glenndiscord** [comment]
No where do i do that? And secondly it doesnt even grow cactus normally

**Comment by Trigary** [comment]
Like, can you read? Have you checked paper.yml?

Regarding cactus not growing normally, please attempt to follow the issue template. It exists for a reason.

**Comment by Glenndiscord** [comment]
Why do you have to be rude about it?

**Comment by Trigary** [comment]
Because you seemingly put no effort at all into this: firstly, you ignored the issue templates and then secondly, you basically ignored what I said. I do not like it when people ignore what others have put time and effort into.

**Comment by electronicboy** [comment]
In the future, please use the search feature, and, more in general, fill out the template fully instead of cutting huge *important* segments out
paper.yml ctrl-f "zero-tick"
