### ISSUE TITLE
ServerConnection tick is blocking

### ISSUE THREAD

**Issue by Shevchik** [PaperMC/Paper#294]
Tick method of ServerConnection ticks all network managers. But it locks the network manager list, so netty io threads can't add new network manager to the list while server is processing them.

It wasn't a big problem before, but now it is. NetoworkManager ticks PlayerConnection, and player connection now handles player health, scoreboard update, etc... So under heavy load + bot attack netty io threads stop doing anything because they are locked on network manager list.

**Comment by aikar** [comment]
interesting catch, putting in a fix for this.
