### ISSUE TITLE
Team modify collisionRule not works

### ISSUE THREAD

**Issue by Dymeth** [PaperMC/Paper#2941]
### What behaviour is expected:
Expected the mobs on the team to not have collisions.

### What behaviour is observed:
Mobs have collisions regardless of the value of collisionRule.

### Steps/models to reproduce:
1) Launch the Paper server with default configs and without plugins
2) Spawn two pigs nearby and use the following commands:
/team add NoClip
/team modify NoClip collisionRule never
/team join NoClip @e[type=minecraft:pig]

### Plugin list:
No plugins

### Paper build number:
git-Paper-98 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
This problem is not observed on the recent Spigot build (2 behind): 
git-Spigot-c574e08-c985389 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
paper.yml has a configuration option to prevent non-player entities being teamed because plugins, `allow-non-player-entities-on-scoreboards`
