### ISSUE TITLE
Items being sucked into wrong entity client side

### ISSUE THREAD

**Issue by Fallenchamp** [PaperMC/Paper#2942]
**What behavior is expected:**
For the minecraft items to be drawn into the players inventory with the normal animation when you pick up items.

**What behaviour is observed:**
https://gyazo.com/e950c987de6deaceb6643dd5082dec64

https://gyazo.com/e5bccabb2e088f86cc26952a09f95ea6

We have been having issues on our server where players will randomly become frozen (screen shaking violently and cannot move until they are killed).  Today we noticed that for this persons client, items he was dropping was being sucked far away into a random entity.  It ended up, in this specific instance, being a hologram.  Even after the hologram was removed his client was sending his pickup animations into it until he was killed and everything returned to normal.

**Steps/models to reproduce:**
We have been testing this non stop for two weeks now, we are unable to properly replicate this issue in any specific manner however it randomly happens to players very often.

**Paper build number:**
Paper (86) 1.15.2-R0.1-SNAPSHOT

**Comment by electronicboy** [comment]
You need to fill in the issue template.

**Comment by Fallenchamp** [comment]
> You need to fill in the issue template.

Fixed that, totally my bad didn't look for any format before posting.
