### ISSUE TITLE
SignChangeEvent - Some Unicode symbols get lost

### ISSUE THREAD

**Issue by SoSeDiK** [PaperMC/Paper#2943]
### What behaviour is expected:
Sign's line to be set as provided in String.

### What behaviour is observed:
Some Unicode symbols get lost (used in the example: `\uE100` or ``).

### Steps/models to reproduce:
So I have this part of code:
```java
@EventHandler
public void onSignChange(SignChangeEvent e) {
	e.setLine(0, "a\uE100a");
}
```
It's being used in two scenarios:
1. The player placed a sign and finished editing it. Result: the client displays to the player `aa`, BUT the server will actually set the line to `aa`. The player won't see `` upon rejoin as well as `player.openSign(thatSign)` & `print(thatSign.getLine(0))` won't contain that symbol.
2. I opened an already placed sign for the player using `player.openSign(placedSign)`. He finished editing it, and the event is fired again. This time that symbol is set without problems.

### Plugin list:
Only my test plugin with the example above.

### Paper build number:
Paper version git-Paper-99 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
This one works fine too (*just in case*):

```
Sign sign = (Sign) block.getState();
sign.setLine(0, "a\uE100a");
sign.update();
```

**Comment by zachbr** [comment]
This was intentionally added to avoid the invalid Unicode character block from showing up on signs as part of world conversions. 

Any Unicode in the private use block (`U+E000` to `U+F8FF`) is currently stripped from signs.

It’s probably been long enough now that most people have converted their worlds and we can drop the change. Will look at shortly.

**Comment by LoneDev6** [comment]
Thanks!
Btw I used to fix this setting the Paper tag manually on each sign editing:
`setBoolean("Paper.RemovedPrivateUnicode", true);`
