### ISSUE TITLE
2 consoles

### ISSUE THREAD

**Issue by xJust1n** [PaperMC/Paper#2945]
Hey if i start my server plop 2 consoles on how can i disable one of them?

https://prnt.sc/r09sx4

**Comment by wizjany** [comment]
https://www.spigotmc.org/threads/spigot-bungeecord-1-15-2.414068/

![image](https://user-images.githubusercontent.com/568161/74165559-4c739200-4bf3-11ea-8e71-55bb6ce23d58.png)
