### ISSUE TITLE
Placing [] in an empty list for the list "items" under "alt-item-despawn-rate" causes Paper to say the entry is invalid

### ISSUE THREAD

**Issue by alfonsojon** [PaperMC/Paper#2946]
### What behaviour is expected:
___Paper should parse the entry `items: []` as an empty list___

### What behaviour is observed:
___Paper logs `alt-item-despawn-rate was malformatted` to the console___

### Steps/models to reproduce:
___Set `items:` in paper.yml as an empty list and put [] after the semicolon.___

### Paper build number:
___`This server is running Paper version git-Paper-99 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`.___

### Anything else:
___Not caused by plugins, though I am running BungeeCord.___

**Comment by electronicboy** [comment]
`[]` is for an array, `{}` is for an empty map

**Comment by alfonsojon** [comment]
Thank you! I didn't realize this section was a map.
