### ISSUE TITLE
Wolves & nametags

### ISSUE THREAD

**Issue by Jaimss** [PaperMC/Paper#2948]
### What behavior is expected:
A wolf gets a nametag applied to itself when you right-click with a nametag. 

### What behavior is observed:
A wolf receives no name, while the nametag is consumed. The wolf just sits/stands.

### Steps/models to reproduce:
1. Get a nametag and a wolf. 
2. Rename the nametag in an anvil.
3. Tame the wolf with bones. 
4. Try to rename the wolf. It will just sit/stand, while the nametag is consumed. 

### Plugin list:
Plugins (57): AdvancedHelp, AdvancedPortals, AuctionHouse, AutoLapiz*, Broadcaster*, BuycraftX, ClearLag, CMI, CoreProtect, CrateReloaded, DeathChestPro, DeluxeChat, DeluxeTags*, dynmap*, EntityTrackerFixer, EpicSpawners, FeatherBoard*, Filters*, GriefPrevention, GriefPreventionDynmap*, HelpGUI, HolographicDisplays, Jobs, LimitPillagers, LuckPerms, LWC, mcMMO, Multiverse-Core, Multiverse-NetherPortals, MVdWPlaceholderAPI*, NerfPhantoms, OldCombatMechanics, PlaceholderAPI, PlayerVaults*, PlayerWarps, PluginHiderPlus, PlugMan, PremiumVanish, ProtocolLib, ShopGUIPlus, SuperbVote, TAB, TradePlus, UltimateKits, UltimateStacker, Vault*, ViaBackwards, ViaRewind, ViaVersion, VillagerOptimiser, Votifier, Vouchers, VoxelSniper*, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
[22:21:35 INFO]: This server is running Paper version git-Paper-102 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[22:21:35 INFO]: Previous version: git-Paper-99 (MC: 1.15.2)
[22:21:35 INFO]: You are running the latest version

### Anything else:
N/a

**Comment by Trigary** [comment]
Unable to reproduce, the wolf does set/stand, but also receives the new name. You should reproduce without plugins.

**Comment by BillyGalbreath** [comment]
Does this still happen on build [114](https://papermc.io/ci/job/Paper-1.15/114/)?

**Comment by Jaimss** [comment]
Nope, this is resolved now.
