### ISSUE TITLE
PlayerArmorChangeEvent is fired by armor items taking durability

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2949]
### What behaviour is expected:
PlayerArmorChangeEvent only fired when a player takes off or puts on an armor piece

### What behaviour is observed:
the behavior above but an armor piece taking damage also fires this event.

**Comment by electronicboy** [comment]
This is basically a technical expansion of #2487 there is no way to limit the event like that now

**Comment by Aaron2550** [comment]
So there's no need to check for playerdamage to update a  durability variable?
