### ISSUE TITLE
Repairing items with colored names takes too much exp from players

### ISSUE THREAD

**Issue by BlackBeltPanda** [PaperMC/Paper#295]
### What behaviour is expected:

The amount of stated exp should be removed from the player.
### What behaviour is observed:

An extra level above the stated amount is removed from the player. If the player has exactly the amount required, the exp is removed but the item is not repaired.
### Steps/models to reproduce:

Apply a colored name to an item with damage and attempt to repair it in an anvil.
### Plugin list:

http://pastebin.com/raw/7XZ6fzqq
### Paper build number:

git-Paper-726
### Screenshots:

Before repair with more exp than stated requirement: https://cdn.discordapp.com/attachments/181710095338569728/181711769188696065/2016-05-16_02.48.59.png

After repair: https://cdn.discordapp.com/attachments/181710095338569728/181711848175960065/2016-05-16_02.49.22.png

Before repair with same amount of exp that's required: https://cdn.discordapp.com/attachments/181710095338569728/181712033807466497/2016-05-16_03.16.08.png

After repair: https://cdn.discordapp.com/attachments/181710095338569728/181712094813487106/2016-05-16_03.16.16.png

**Comment by aikar** [comment]
Have you tried on Spigot and Vanilla? Without plugins?

Paper hasn't modified that system...

**Comment by BlackBeltPanda** [comment]
Is the "Mojang_\<version\>.jar" file in the "cache" folder the vanilla .jar? If so, then yes, this also happens in vanilla with no plugins.

**Comment by aikar** [comment]
@BlackBeltPanda on 1.11.2? If so, should also file it on Mojang bug tracker.

There was an issue before where client did not receive the amount of exp the server is going to charge, which resulted in desyncs, but that was fixed recently.
