### ISSUE TITLE
Option to _just_ download & patch server

### ISSUE THREAD

**Issue by AstraLuma** [PaperMC/Paper#2951]
**Is your feature request related to a problem? Please describe.**
I'm working on a [server container system](https://github.com/minecraft-podman/container-server) and I would like to push as much prep as possible to the container build and minimize what's done on server launch.

The PaperMC server JAR at the moment downloads+patches the mojang server on first launch and caches the result.

**Describe the solution you'd like**
Some kind of CLI flag to do the download+patch (I don't think any other prep is expensive) and exit.

**Describe alternatives you've considered**
About all I can think of is a build process where:
1. Start the server
2. Wait for the server to cache the files
3. Stop the server
4. Copy the cached files to the final container.

**Additional context**
This is part of a larger project for defining a minecraft server with just a config file, and running that server (and associated extras) in containers.

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paperclip/pull/9/commits/a9522934295034e22df5376cd6b56485665e97d7

That's only supported so far back, but basically, you can also (ab)use --version I believe it was for earlier builds, or, just start it without the eula being accepted
