### ISSUE TITLE
Fishing rods sometimes cause error with /timings paste

### ISSUE THREAD

**Issue by fabianmakila** [PaperMC/Paper#2953]
### What behaviour is expected:
No errors when running /timings paste.

### What behaviour is observed:
We get this error:
`13.02 00:07:44 [Server] WARN Entity threw exception at world:1129.4407081224192,70.68775451239205,2438.620988139657
13.02 00:07:44 [Server] WARN java.lang.NullPointerException
13.02 00:07:44 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1248)
13.02 00:07:44 [Server] WARN at net.minecraft.server.v1_15_R1.EntityFishingHook.m(EntityFishingHook.java:229)
13.02 00:07:44 [Server] WARN at net.minecraft.server.v1_15_R1.EntityFishingHook.tick(EntityFishingHook.java:115)
13.02 00:07:44 [Server] WARN at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:759)
13.02 00:07:44 [Server] WARN at net.minecraft.server.v1_15_R1.World.a(World.java:856)
13.02 00:07:44 [Server] WARN at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497)
13.02 00:07:44 [Server] WARN at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245)
13.02 00:07:44 [Server] WARN at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
13.02 00:07:44 [Server] WARN at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
13.02 00:07:44 [Server] WARN at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
13.02 00:07:44 [Server] WARN at java.lang.Thread.run(Thread.java:748)
13.02 00:07:44 [Server] ERROR [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.minecraft.server.v1_15_R1.EntityFishingHook} did not stopTiming)
13.02 00:07:44 [Server] INFO java.lang.Throwable: null
13.02 00:07:44 [Server] INFO at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.15.2.jar:git-Paper-103]
13.02 00:07:44 [Server] INFO at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.15.2.jar:git-Paper-103]
13.02 00:07:44 [Server] INFO at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:511) ~[patched_1.15.2.jar:git-Paper-103]
13.02 00:07:44 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-103]
13.02 00:07:44 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-103]
13.02 00:07:44 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-103]
13.02 00:07:44 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-103]`

### Steps/models to reproduce:
Has something to do with fishing at the same time as getting timings.

### Plugin list:
AdvancedBan*, ChatSentinel*, CoreProtect, DiscordBridge, DNotify, EntityTrackerFixer, F3NPerm, GriefPrevention, GSit, KickFromClaim, LuckPerms, Playtimes*, RandomTeleport, RiptideTempFix, ServerListPlus*, SmoothSleep, SpeedLimiter, WAEssentials, WorldBorder, WorldEdit, WorldGuard

### Paper build number:
git-Paper-103

### Anything else:
-

**Comment by BillyGalbreath** [comment]
Looks like this can happen when the `ProjectilCollideEvent` is cancelled, which nulls the `movingobjectposition` which is then used for the `ProjectileHitEvent` and throws the NPE

![image](https://user-images.githubusercontent.com/332527/75085332-bc382580-54ed-11ea-9a00-b2682c651013.png)
