### ISSUE TITLE
New crash with block ticking optimization?

### ISSUE THREAD

**Issue by introvertism** [PaperMC/Paper#2956]
### Link/paste of stack trace

https://paste.ubuntu.com/p/WXFtJVCWpH/

### Plugin list:
Plugins (79): AsyncWorldEdit, AuctionHouse, BetterRTP*, BlockLocker, ChestShop, Chunkmaster, Citizens, CitizensCMD, CoinFlipper, ConditionalCommands*, CoreProtect, CraftingStore, DeluxeMenus, DeluxeTags*, DiscordSRV, DoKeepInventory*, DonatorJoinPlus, EntityTrackerFixer, Essentials, EssentialsSpawn, Harbor, HiveChecker, HolographicDisplays, IllegalStack, Item2Chat, Jobs, KixsChatAnnouncer, LibsDisguises, LimitPillagers, LiteBans, LuckPerms, Matrix, mcMMO, mcmmo-placeholders, MoneyNote*, NerfPhantoms, OreAnnouncer, PacketListenerApi*, PlaceholderAPI, PlayerVaults, PlayerWarps, PlayTime*, ProtocolLib, ProtocolSupport, SAML, ServerListPlus*, ShopGUIPlus, SimpleFreeze*, spark, SpawnRangeEditor, SpecializedCrates, SpigotPing*, SuperVanish, TAB, TempFly*, TheNewEconomy, TicketManager, TimeIsMoney*, TitleMotd*, Towny, TownyFlight, TownyLevels, TownyNameUpdater, UltimateAutoRestart, UltimateKits, UltimateTimber, Vault, VentureChat, VillagerOptimiser, Votifier, VotingPlugin, Vouchers, WildStacker, WildTools, WorldBorder, WorldEdit, WorldGuard, WorldGuard-Towny*, XPBoost

### Actions to reproduce (if known):
NA

### Paper build number:
This server is running Paper version git-Paper-102 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Nothing to do with the block ticking optimizations, either falls between some known bug (apparently not, but, am leaving that here for reference *sips tea*), or, a bad plugin

**Comment by Spottedleaf** [comment]
that can only occur due to a plugin modifying the visibleChunks field

**Comment by introvertism** [comment]
Is that something new? Server has been up for nearly 2 months and never had that crash before and then it finally happened around 24 hrs after switching to the new paper build. Not blaming you guys at all I'm just curious so I can stop this from happening again in the future. Appreciate all your guys hard work and tysm for the insanely fast response

**Comment by electronicboy** [comment]
plugin devs often do stupid things in their plugins, e.g. messing with internal collections, because they can get away with it 99.9999999% of the time, often times they can get away with it for months before somebody experiences a crash from their plugin

**Comment by introvertism** [comment]
Ah okay, thanks for the info. Hopefully I can figure out something soon to fix it :p doubt it though lmao
