### ISSUE TITLE
TnT fix suggestion

### ISSUE THREAD

**Issue by tehrenderr** [PaperMC/Paper#296]
Suggestion: Fix for east/west cannoning that has plagued faction servers forever. It doesn't seem to work when I set fix-cannons to true.

Here is the gist of the problem
http://www.minelink.net/threads/east-west-cannoning-patched.565/

**Comment by zachbr** [comment]
We're open to a PR for this, but no one on the team runs or maintains a cannon server actively on 1.9. Short of said PR, I doubt this will ever get looked at.
fix-cannons was also removed in 1.9.4 because it was hopelessly broken on all of 1.9.x

**Comment by tehrenderr** [comment]
I need this for a 1.8.8 server, sorry for not specifying.

**Comment by zachbr** [comment]
We do not support 1.8.8 in any capacity. It includes a version of fix-cannons but the behavior is not quite the same as 1.7.10.

But as I said, we don't support it any longer. No updates, no comments, no issue fixes, nothing.
What you see is what you get with 1.8.8
