### ISSUE TITLE
Connection to the server is lost

### ISSUE THREAD

**Issue by randalz-z** [PaperMC/Paper#2965]
(I am Russian, I use a translator)

Hello, sometimes there is a problem on my server, about this happens once every 1-2 weeks.

- Problem description:
The server is running, players are playing, nothing special, and suddenly the server kicks about 10% of all players from the server, and at the same time the connection to the server disappears.

- How do I usually solve it:
I turn off the server, and the "stop" command does not help, I just have to close the "Ctrl + C" screen and start a new one.
/asw manager reload Photoclub, that is, restarting the plugin via AutoSaveWorld, helps for exactly 3-4 minutes, then the connection is lost again.

- What's my question:
I use version Protocolib v4.5.0 server PaperSpigot 1.12.2 (version 1596). I found articles on the Internet, people said that you just need to update the kernel to a newer version, the question is, in version 1618, the case is not solved this problem?

P.S. Sorry in advance, if incorrectly designed the theme.

**Comment by electronicboy** [comment]
1.12.2 is no longer supported, the fact that reloading plugins pushes off the issue also screams that this is a plugin issue
