### ISSUE TITLE
Error executing task on Server

### ISSUE THREAD

**Issue by SrBedrock** [PaperMC/Paper#2966]
### Link/paste of stack trace

Full log: https://mclo.gs/9NqX6RE#L10712
Erros: https://hasteb.in/xovowujo.cs https://hasteb.in/runodiqa.cs https://hasteb.in/pehimuzu.cs
Timings: https://timings.aikar.co/?id=9c2a4d1527ee4b248c214fa91dbd6dd6#timings

### Plugin list:
> [15:31:55 INFO]: Plugins (46): AuthMe, BackToTheRoots, BuycraftX, ChatReaction, ChatReactionPlus, CheaperPhysicsEvent, ConsoleSpamFix, CoreProtect, CrazyCrates, DeluxeTags*, EasyChairs, EntityTrackerFixer, Essentials, EssentialsSpawn, EZColors, eZProtector, FarmLimiter, FastLogin, GriefPrevention, HolographicDisplays, KillerMoney*, Lottery, LuckPerms, mcMMO, ModReq*, PacketLimiter, PlaceholderAPI, PlayerHeads, PlayerShopGUIPlus, ProtocolLib, PsudoCommand, ShopGUIPlus, SkinsRestorer, SuperbVote, TAB, TrMenu, UltimateChat, Vault, VKAutoPickup, VoidGenerator, Votifier, Wild, WorldBorder, WorldEdit, WorldGuard, WorldLoader

### Actions to reproduce (if known):
I don't know how to reproduce the error.

### Paper build number:
>[15:33:00 INFO]: This server is running Paper version git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
>.... [15:33:00 INFO]: Checking version, please wait...
>.... [15:33:01 INFO]: Previous version: git-Paper-243 (MC: 1.14.4)

**Comment by electronicboy** [comment]
as per discord, I bet that you can't reproduce this without plugins; Something is potentially registering entities improperly
