### ISSUE TITLE
SSLException: Received fatal alert: internal_error

### ISSUE THREAD

**Issue by panda** [PaperMC/Paper#297]
Hey!

I've been dealing with this small issue for awhile now, and I was wondering if there is a quick fix for this issue:

Basically, my issue is that, when im trying to see if i'm running the latest version of Paper. it throws a "received fatal alert" error

https://gist.github.com/YoloxPanda/72d81e6ab5ff55aa75a3e99bbb5af763 
^ make sure you check that :)

**Comment by zachbr** [comment]
Everything looks fine on our end, internal error is typically associated with local JVM issues.

General advice would be to make sure you're using the latest version of JRE. Which as of now is 8u92 (8u91 is also likely fine as far as I know).
EDIT: and on *nix systems make sure you're not behind on any network security packages.

**Comment by panda** [comment]
Thanks, I was able to fix the issue :)

**Comment by WonderDave** [comment]
@YoloxPanda What did you do to fix this issue?  I just switched from McProHosting to a Linux machine running CentOS, and I'm now getting the same messages that you were getting when I issue the "version" command.
