### ISSUE TITLE
#112　bug  getDrops()

### ISSUE THREAD

**Issue by firefly0314** [PaperMC/Paper#2974]
I found it when using craftbook.

↓　A series of conversations　↓

 Pretty sure the drill IC requires a tool in the chest to break blocks
If the blocks you're trying to break require a tool, that'd be why
Do you keep Pickel on your chest?
Do you mean should you put a pickaxe in there? If so the answer is probably
(ﾟдﾟ)(｡｡)(ﾟдﾟ)(｡｡)
It only uses the first tool from memory
Put the pickaxe in the first spot
I tried but did not dig.
Maybe Spigot changed the way chests are ordered :upside_down:
I'll have to look into it when I get a chance
Dirt is coming out instead of stones ...?
As in it's giving the dirt item rather than giving stone, but breaking stone?
That sounds like a Spigot bug then - as we just call getDrops() on the block
Yes, breaking the stone will drop dirt
If you are free today, change the paper version and verify.:thumbsup:
I will not be free today
But that almost 100% sounds like a Spigot bug

**Comment by electronicboy** [comment]
getDrops uses the passed itemstack just fine, however, this is down to NMSes handling of block stuff, nothing we nor anybody can garauntee behavior of
