### ISSUE TITLE
log output on docker container show only as ">"

### ISSUE THREAD

**Issue by mtoensing** [PaperMC/Paper#2975]
### What behaviour is expected:
I would like to see the whole log message

### What behaviour is observed:
I only see ">" and when I hover over the message I see the whole message. 

### Steps/models to reproduce:
<img width="1272" alt="Screen Shot 2020-02-19 at 08 12 08" src="https://user-images.githubusercontent.com/136737/74810479-c096ef80-52ef-11ea-95f0-8443f8222d43.png">

### Plugin list:
No plugins

### Paper build number:
1.15.2#112

### Anything else:
This happened before and after this commit: https://github.com/PaperMC/Paper/commit/9f5fadcc7ce3e855bc95ea8937ca7c488e247127  I thought I bring this to your attention since somebody looked into this. PaperMC is the only application that show this behaviour. This is the dockerfile https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/blob/master/Dockerfile

**Comment by MiniDigger** [comment]
does it happen if you just look at the logs via docker commands (so without whatever stupid web panel you use?)

if it still persists and is not a bug in the panel, its most likely caused by jline. you can disable jline via --nojline

**Comment by mtoensing** [comment]
@MiniDigger 
Thank you. But where do I put the command so that it works? Like this?

`/usr/local/openjdk-11/bin/java -jar -Xms$MEMORYSIZE -Xmx$MEMORYSIZE -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs -Dcom.mojang.eula.agree=true /opt/minecraft/paperspigot.jar --nojline`

**Comment by MiniDigger** [comment]
yes

**Comment by mtoensing** [comment]
Thanks. Works like a charm!
