### ISSUE TITLE
The rain problem

### ISSUE THREAD

**Issue by Blueeyestar** [PaperMC/Paper#2976]
since the 1.15 version we have the problem on our server that it only rains ... rains .. rains ... It is quite annoying. Before 1.15 it was rather rare. Can you maybe add an option where you can enter the percentage, how likely is it to rain?

**Comment by MiniDigger** [comment]
you can do that via plugins

**Comment by DarkEyeDragon** [comment]
Have had this happen too recently. Every few (5-8) minutes it would start raining. Until i got annoyed enough at the static noise and just disabled rain completely.

**Comment by BillyGalbreath** [comment]
When you skip the rain it doesnt reset the rain timer. Let the rain finish playing out so it can reset the timer when its done, then you'll get normal rain again. This has been a thing in minecraft since forever.

**Comment by electronicboy** [comment]
https://minecraft.gamepedia.com/Weather#Behavior
Weather is not chance-based, it's randomized already by the server with a length between the two, anything here is basically 100% on plugins to deal with properly, if you want more control over this, use a plugin
