### ISSUE TITLE
Crash radomly

### ISSUE THREAD

**Issue by gabriel262m** [PaperMC/Paper#2977]
Hello! I am presenting the error that you will see in the log, I do not know what causes it but it is very annoying and I do not really understand the reason for this since it is very random and does not have a precise moment if it simply appears.

I am very new to this server and my reading of the errors is not good, so I decided to paste it here waiting for some help.

Thanks in advance
https://pastebin.com/9699NVtf

Version:
 git-Paper-243 (MC: 1.14.4)  
 1.14.4-R0.1-SNAPSHOT

Ram 12gb
Intel Xeon E5-1650v4 @ 4.00GHz CPU
NVMe SSDs in RAID 1
DDR4 ECC RAM

**Comment by BillyGalbreath** [comment]
It's not an error or a crash, its a thread dump. If the watchdog detects a good amount of lag it will dump the current stack it's lagging with to help you find out what's causing that lag.

**Comment by gabriel262m** [comment]
Is there any way to solve this? Sometimes it happens more than 5 times in a row until it is simply impossible to play and I have optimized everything as much as possible following an optimization guide for paper 1.14.4.

By the way I have about 58 plugins and a maximum amount of 5 players connected a day and still crash a lot.

I thought it was some kind of annoying plugin because I didn't have this problem before and now it's simply out of nowhere that it's impossible to keep the server in a normal way without at least 3 crashes a day.

I would appreciate any help or recommendation

**Comment by electronicboy** [comment]
Your server took too long to tick and is showing that the JVM, or the box as a whole, is overloaded
The issue tracker is for reporting issues, not seeking support, not that 1.14 is supported anymore either, 1.15 is basically 1.14 + bees + performance improvements
