### ISSUE TITLE
Packet-PacketPlayInAutoRecipe

### ISSUE THREAD

**Issue by Zhujingxi** [PaperMC/Paper#2978]
###  Timings or Profile link:
https://timings.aikar.co/?id=db67afb8649b40f0a142ab775bf54975&tdsourcetag=s_pctim_aiomsg
### Description of issue:
Packet-PacketPlayInAutoRecipe cost 46.87ms leg. The server is runing just like normal but the leg comming with no sign. We rebot the server but just solve the problem in a short time.

### Plugin list:
AuthMe-5.6.0-SNAPSHOT.jar
CoreProtect-2.18.1.jar
FastLogin.jar
GroupManager [v3.2].jar
MOTDColor.jar
protocolLob.jar
Vault.jar
### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
#112

**Comment by electronicboy** [comment]
your timings report doesn't point to any form of lag from packets

**Comment by Zhujingxi** [comment]
> your timings report doesn't point to any form of lag from packets

oh sorry, i give you the report after i rebot the server this is the report before:https://timings.aikar.co/?id=16b7cc54bb984f93b4757fc72ab05e27&tdsourcetag=s_pctim_aiomsg

**Comment by electronicboy** [comment]
The recipe stuff in general ain't pretty overall, but, that was 1 tick where it took 45ms and falls into "acceptable", that is not the cause of your issues
