### ISSUE TITLE
Enchanting table GUI not giving empty book the matching enchant.

### ISSUE THREAD

**Issue by Krater107a** [PaperMC/Paper#2979]
### What behaviour is expected:
When enchanting books using enchanting table, what enchant you choose in the GUI should match what enchant you got for your book.

### What behaviour is observed:
When enchanting books using enchanting table, what enchant you choose in the GUI does not always match what enchant the book is given. Example: Choose 'punch I' and you get 'bane of arthropods IV'.

### Plugin list:
Clearlag, IllegalStack, Matrix Anti-Cheat, ProtocolLib, SaveDeathDrops

### Paper build number:
git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:

**Comment by kickash32** [comment]
Test without plugins.

**Comment by BillyGalbreath** [comment]
Unable to reproduce.

https://youtu.be/qCeiZIFKFQA

Also, just by this `Choose 'punch I' and you get 'bane of arthropods IV'` tells me you have some plugin messing with things (most likely IllegalStack). Those two enchantments are not compatible. One goes on a bow only, the other will not apply to a bow at all.

**Comment by Krater107a** [comment]
Wow paper team is awesome, thanks for gettin' back with me on this issue and for the replies. I will continue to experiment with this issue on my paper server and will post results when I get some.

**Comment by Krater107a** [comment]
@BillyGalbreath You are correct. After doing some additional testing I can confirm that plugin 'illegal stack' is what is causing this issue. Maybe this thread can help other server owners with the same problem.
