### ISSUE TITLE
CME at 748

### ISSUE THREAD

**Issue by oloflarsson** [PaperMC/Paper#298]
Using: https://ci.destroystokyo.com/job/PaperSpigot/748/
https://gyazo.com/33f7163468a60993f0eb418a33d51a0e

Did not happen ~10 builds ago.

**Comment by oloflarsson** [comment]
Could this commit be the cause?
Just a wild guess on my end :smile_cat:.
https://github.com/PaperMC/Paper/commit/d22f9071ff1c2cd8f4c0513a0e3d9b3e8e119a0c

**Comment by aikar** [comment]
anything note worthy that happened ? plugin list?

I can't see how this could've happened with vanilla paper.

**Comment by Brokkonaut** [comment]
We have the same problem since updating to the latest paper yesterday. No other recent plugin updates and with latest paper our servers crash every some hours.

The version that did not crash was from may 14 (build #740), so the change must have been in one of the latest commits.

**Comment by Black-Hole** [comment]
Could you provide a complete plugin list?

**Comment by Brokkonaut** [comment]
Most of our plugins are private plugins, so the names would not help much (I wrote them myself, and I'm sure there are no async bukkit-api calls).
Public plugins are WorldEdit, WorldGuard, dynmap, bPermissions, ChestShop, OpenInv, LogBlock, EssentialsX, LWC, ProtocolSupport

The crash is was quite random with 5 to 60 players online and no special event before the crash in the logs.

Currently we downgraded our servers to #740 and its running without crashes for some hours now.

**Comment by Brokkonaut** [comment]
I think it was the Plugin ProtocolSupport in combination with the commit https://github.com/PaperMC/Paper/commit/d22f9071ff1c2cd8f4c0513a0e3d9b3e8e119a0c
They fixed it here https://github.com/ProtocolSupport/ProtocolSupport/commit/0d859636d39a9775f52586abf7e7facc693f4fc7

**Comment by oloflarsson** [comment]
@Brokkonaut - I am also a user of ProtocolSupport. I suppose we can assume that was the cause.
