### ISSUE TITLE
Player respawns at the location where they died when shot by arrow from player

### ISSUE THREAD

**Issue by Dimotai** [PaperMC/Paper#2980]
Basically, the title. If two players are in combat, the player who dies by an arrow shot by another player's bow will respawn at the same location where they died.

Scenario:

Player A has a bow and 16 arrows and shoots Player B four times and kills Players B. Player B then respawns exactly at the location where Player B died.

This issue does not seem to be present in other methods of killing (swords, fist, etc.)

This issue is not present in CraftBukkit's version git-Spigot-800b93f-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT.

This issue **IS PRESENT** in Paper's latest 1.15.2 release: git-Paper-118 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT with **NO PLUGIN** intervention.

Should be an easy fix.

Thanks!

**Comment by JRoy** [comment]
> with NO PLUGIN intervention.

Did you actually test without plugins, or are you guessing?

> Should be an easy fix.

Then fix it yourself

**Comment by Dimotai** [comment]
> > with NO PLUGIN intervention.
> 
> Did you actually test without plugins, or are you guessing?
> 
> > Should be an easy fix.
> 
> Then fix it yourself

Yes, I did test it without plugins. And no, I don't have the time on my hands

**Comment by mikroskeem** [comment]
>And no, I don't have the time on my hands

You had enough time to reply with this, you'll have enough time to fix it yourself if it's "easy". Furthermore, I couldn't reproduce the issue on Paper.
