### ISSUE TITLE
MobSpawning causes lag

### ISSUE THREAD

**Issue by Fejm** [PaperMC/Paper#2984]
###  Timings or Profile link:
https://timings.aikar.co/?id=6cf4cf9a832a4ee88af31baf222e8466

### Description of issue:
Well, server lags as hell when /gamerule doMobSpawning true is enabled. Turning it off brings TPS to 20. Players are complaing about lack of mobs becouse of this.

### Plugin list:
Custom coded, Account system + Cuboids system, pretty simple + LogBlock

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml
https://gist.github.com/Fejm/c8d5958bee4795c8edd5e4981756ad78 
paper.yml
https://gist.github.com/Fejm/323d004fb8da5f4c9ea5fa33309c48bf
spigot.yml
https://gist.github.com/Fejm/4d6f93cf6da427a7f0633a68a615f31c

### Paper build number:
Custom  - added some events and patches to 6ea3c2c, nothing related to the problem. 
It is also worth mentioning that I added a patch that reduces entity ticking by 2 if TPS is low.

**Comment by electronicboy** [comment]
https://www.spigotmc.org/threads/guide-server-optimization⚡.283181/page-20#post-3684550

**Comment by Fejm** [comment]
I know, followed everything. From java flags to configs. Did i miss something?
I feel that is performance problem with mobspawning itselfs - not with configuration.

**Comment by electronicboy** [comment]
`Vanilla is much more active towards ensuring that it reaches its spawn targets`

**Comment by electronicboy** [comment]
You're also heavily tripping old-gen, so, your timings are somewhat invalid too, there are some known caveats around mob spawning with paper too, we don't need another ticket for it, however.

**Comment by Fejm** [comment]
What you mean by old-gen? How to solve this issue? Also, if i set less RAM there is extreme GC/CPU usage.

**Comment by kickash32** [comment]
Come on over to the discord and we can discuss this further.
