### ISSUE TITLE
Lags on player join

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2986]
###  Timings or Profile link:
Spark : https://sparkprofiler.github.io/#Ig4OFg5GrP
Timings: https://timings.aikar.co/?id=2f2e437154f540dab5bf63cf81d30729

### Description of issue:
We have tested the latest version of paperclip (build 118) without any plugin except spark. As a result of these tests, we discovered that when a player joins, lags are observed. Thank you for your help.

### Plugin list:
Spark (only for the test)

### Paper build number:
Paper version git-Paper-118 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
the server is sending stuff to the client, not exactly super avoidable
