### ISSUE TITLE
Tamed wolves are able to be commanded to sit or stand up by NOT an owner and it occures only if the owner is online

### ISSUE THREAD

**Issue by Camillo82** [PaperMC/Paper#2987]
### What behaviour is expected:
Tamed wolves should be able to command only by the owner

### What behaviour is observed:
Tamed wolves are able to be commanded to sit or stand up by NOT an owner when the owner is on-line while it is not possible if the owner is offline

### Steps/models to reproduce:
Create a tamed wolf. Any other player on the server can make it sit or stand up unless the owner of the wolf is offline.

### Plugin list:
NO PLUGINS

### Paper build number:
Latest build #118

### Anything else:
Could be vanilla MC 1.15.2 bug?

**Comment by BillyGalbreath** [comment]
You sure? Build 114 was confirmed to have fixed that.

**Comment by electronicboy** [comment]
Just double checked as I totally tested it properly at the time, but, cannot reproduce

**Comment by Camillo82** [comment]
I've just updated to #118 build and it does happen but only if the dog's owner is online. If the owner is off-line everything is fine.
