### ISSUE TITLE
Tamed wolves are able to be commanded to sit or stand up by NOT an owner BUT ONLY when the owner is ONLINE - still not FULLY fixed in #118 build

### ISSUE THREAD

**Issue by Camillo82** [PaperMC/Paper#2988]
### What behaviour is expected:
Tamed wolves should be able to be commanded only by the owner

### What behaviour is observed:
Tamed wolves are able to be commanded to sit or stand up by NOT an owner BUT ONLY when the owner is on-line, while everything is fine if the owner of that wolf is offline

### Steps/models to reproduce:
Create pure paper server on #118 build. Create a tamed wolf and stay online. Login another player. Another player on the server can make the wolf sit or stand up UNLESS the owner of the wolf is offline.

### Plugin list:
NO PLUGINS - PURE PAPER BUILD

### Paper build number:
Latest build #118

### Anything else:
Has been said that it had been fixed in build #114 but it is not - still occuring if the owner of the wolf is ONLINE.

**Comment by electronicboy** [comment]
Do not close an issue just to reopen a new one.
We cannot reproduce this issue, if you can provide a video and the full output of /version instead of "latest build", because your commentary on the last ticket indicates that you're not even sure that you're on the latest.
