### ISSUE TITLE
NameTagEdit - Prefix get's removed

### ISSUE THREAD

**Issue by yannic-md** [PaperMC/Paper#2993]
### What behaviour is expected:
___Normal Prefixes with NameTagEdit___

### What behaviour is observed:
___White Nametag at all players___

### Steps/models to reproduce:
___1. Change the "enable-player-collisions:" in paper.yml to true.
2. Restart your server.
3. Join the server.___

### Plugin list:
over 50, but without this setting, all is working without problems.
But i need that feature, because i want to make events.

### Paper build number:
___git-Paper-118___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by electronicboy** [comment]
We have no intent to aim to work around issues with plugins and that option, especially when it seems that that plugin is not using the API (Which, is somewhat expected)
I'd suggest asking NTE to add support for that option
