### ISSUE TITLE
1.15.2: ExplosionPrimeEvent not fired for EnderCrystal

### ISSUE THREAD

**Issue by kangarko** [PaperMC/Paper#2995]
### What behaviour is expected:
To see ExplosionPrimeEvent fired for ender crystals

### What behaviour is observed:
When I create an explosion using the createExplosion API call next to a crystal, it disappears. On 1.8.8 I can prevent the crystal from disappearing by cancelling the explosion prime event. On 1.15.2 it does not work.

### Steps/models to reproduce:
Code: 
```java
@EventHandler(priority = EventPriority.MONITOR)
	public void onExplosionPrime(final ExplosionPrimeEvent event) {
		System.out.println("prime for " + event.getEntity());
	}
```

### Plugin list:
Arena

### Paper build number:
git-Paper-122 (MC: 1.15.2)

**Comment by Trigary** [comment]
Vanilla behaviour: the end crystal does not explode if it got damaged by an explosion. It just dies "silently" in that case.

**Comment by kangarko** [comment]
So there's no way for plugin developers to prevent the crystal disappearing on explosion without using NMS?

**Comment by MiniDigger** [comment]
checked if entitydeathevent is being fired?

**Comment by electronicboy** [comment]
as Trig said, the crystal doesn't explode if damaged by an explosion, use the entity damage events
