### ISSUE TITLE
BlockPlaceEvent::getHand() is always HAND for blocks like beds & doors etc.

### ISSUE THREAD

**Issue by SoSeDiK** [PaperMC/Paper#2997]
### What behaviour is expected:
Placing blocks like beds & doors & flowers from the second hand during BlockPlaceEvent gives `event.getHand() == EquipmentSlot.OFF_HAND`.

### What behaviour is observed:
`event.getHand()` is always `EquipmentSlot.HAND` for them.

### Steps/models to reproduce:
Place one of those blocks from the off-hand and print the hand during BlockPlaceEvent. It'll be HAND.

### Plugin list:
Only one which does `Bukkit.broadcastMessage("Hand: " + e.getHand().toString());` on BlockPlaceEvent.

### Paper build number:
git-Paper-122 (MC: 1.15.2)

**Comment by Trigary** [comment]
It would seem that this never got updated since off hands were introduced, I will PR a fix.
