### ISSUE TITLE
[Idea] Performance boost of PrepareItemCraftEvent event

### ISSUE THREAD

**Issue by LoneDev6** [PaperMC/Paper#2999]
### Description of issue:
I noticed that PrepareItemCraftEvent is called one time for each item * its amount.
For example this would call the event 28 times.
![image](https://user-images.githubusercontent.com/27242001/75722981-a8ee3c80-5cdb-11ea-8f48-01ce782d4a90.png)

Is this really needed?
Why can't it be called one time? I think that would be great to make performance better.

### Plugin list:
None

### bukkit.yml, spigot.yml, paper.yml, server.properties
Default ones

### Paper build number:
This server is running Paper version git-Paper-75 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Brokkonaut** [comment]
I don't think it will improve performance much. Afaik crafting is no performance bottleneck (at least i never saw it in a relevant position in timings)

**Comment by PhanaticD** [comment]
I have noticed plugins can suffer from this

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/75962667-18228700-5ebc-11ea-9c34-8e8c006fbc95.png)
Unless you're actually clicking the item in there 28 times, I have no idea how you're even seeing that, the 2 second look at the logic does not show such behavior, nor does a listener on the event?

(You're also running a stupendously old version of the server software...)

**Comment by electronicboy** [comment]
Oh, the actual /crafting/ does that, not the placement; misread
But, the event call itself is a non-issue, this is more down to how this logic is implemented by vanilla, reducing the calls to the event would imply breaking the behavior here vs bukkit

**Comment by LoneDev6** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/1228900/75962667-18228700-5ebc-11ea-9c34-8e8c006fbc95.png)
> Unless you're actually clicking the item in there 28 times, I have no idea how you're even seeing that, the 2 second look at the logic does not show such behavior, nor does a listener on the event?
> 
> (You're also running a stupendously old version of the server software...)

You can trigger this way:
- get a lot of diamonds
- click the recipe book to craft diamond blocks
- see the event called one time for each item in single slot * its amount.

**Comment by LoneDev6** [comment]
@electronicboy I don't want to bother, but maybe this could be a good source of performance improvements as would reduce checks done by plugins that listen on PrepareItemCraftEvent :D

**Comment by electronicboy** [comment]
I don't believe that there is much interest in rewriting vanillas crafting
mechanic
