### ISSUE TITLE
tcpr.ca

### ISSUE THREAD

**Issue by NotJustPizza** [PaperMC/Paper#300]
Is it official download site https://tcpr.ca/downloads/paperspigot or fake?

**Comment by MrPowerGamerBR** [comment]
@SlimaKCoder Why do you need to download Paper from a external source? Just download paperclip.jar from http://aquifermc.org and be happy...

Also, since when Yive's Mirror is the "official Paper download website"?

**Comment by zachbr** [comment]
Not official, not recommended.
Supported downloads are provided, by us, here: https://ci.destroystokyo.com/job/PaperSpigot/

**Comment by NotJustPizza** [comment]
I'm only asking. This site has better ranking in Google, but probably is malicious ;/

**Comment by MrPowerGamerBR** [comment]
@SlimaKCoder it isn't "malicious" (I sometimes use it to download older Spigot/CraftBukkit builds that aren't avaliable anymore), but it is better download from the source (that is updated and official) than using something unofficial.

**Comment by Ichbinjoe** [comment]
From talking with Yive, I really don't think his aim is to infect hundreds of servers. However, since paperspigot gives you a download link, there is no reason not to use it :P

**Comment by sgdc3** [comment]
tcpr.ca is a very useful and reliable service, if you want you can use checksums to check if the jar is genuine.

**Comment by zachbr** [comment]
Starting to go a bit off topic, we provide a download and that is the one we recommend. The aforementioned site had had previous issues with serving very outdated versions of our software, so we don't recommend it, or any other third party site. Use whatever though, it's just all on you.
