### ISSUE TITLE
Polar bears have forgotten how to climb

### ISSUE THREAD

**Issue by BlueScreenBuddy** [PaperMC/Paper#3004]
### What behaviour is expected: When you polars chase you they should be able to climb up one block.
___What you expected to see___

### What behaviour is observed: If you climb up one level after attacking a polar bear, they stay there and will not climb.
___What you actually saw___

### Steps/models to reproduce: Attack a polar bear the move up one block. Link: https://i.imgur.com/5CuXZZQ.mp4
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___ 

### Plugin list: BackpacksRemastered, CricTreeCapitator, mcMMO, MythicDrops, DynMap
___A list of your plugins___

### Paper build number: git-paper-126 (1.15.2)
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by kickash32** [comment]
Confirmed bug with snow tiles.

**Comment by chickeneer** [comment]
I have just tested this in vanilla. Confirmed the issue in 1.15.2 and then it doesn't reproduce for 1.16.2. So I believe this issue to be solved for 1.16.
