### ISSUE TITLE
Zero-tick farm not working in server, whilst working in single player.

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3005]
### What behaviour is expected:
To see the sugercane grow at zero-tick speed.

### What behaviour is observed:
The sugarcane growing at normal speed.

### Steps/models to reproduce:
https://www.youtube.com/watch?v=qadaI38zRZc

### Plugin list:
CustomJoinMessages, PlaceholderAPI, ServerRestart

### Paper build number:
122

**Comment by Draycia** [comment]
Change the setting relating to zero tick in the paper.yml 

Should contain "zero-tick" in the key name.

**Comment by BillyGalbreath** [comment]
Zero tick farms are a bug that Mojang is actively trying to fix. Paper has fixed them completely. If you want to re-break your server we have included the option to do so in your Paper settings.

**Comment by ghost** [comment]
> Zero tick farms are a bug that Mojang is actively trying to fix. Paper has fixed them completely. If you want to re-break your server we have included the option to do so in your Paper settings.

Does this option need to be disabled?:
fix-zero-tick-instant-grow-farms: true

**Comment by Draycia** [comment]
Yes
