### ISSUE TITLE
Rail dupe glitch

### ISSUE THREAD

**Issue by OwerPlay** [PaperMC/Paper#3006]
### What behaviour is expected:
___What you expected to see___
Either Rail break or drop
### What behaviour is observed:
___What you actually saw___
Rail breaked and dropped
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
https://prnt.sc/rc95hf
Warning: Observers that rails are on have to face up
### Plugin list:
___A list of your plugins___
https://prnt.sc/rc95oo
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
https://prnt.sc/rc95v4
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by electronicboy** [comment]
loooooong standing vanilla issue, has been fixed and busted multiple times

**Comment by OwerPlay** [comment]
It couldnt be looooooooooong vanilla issue, because it uses observers which are not in a game for a long time

**Comment by electronicboy** [comment]
the observer is just a means of inducing the bug rather than using a clock. exact same bug, different vector.

**Comment by OwerPlay** [comment]
It has to be on a looking up observer otherwise it does not duplicate

**Comment by Black-Hole** [comment]
If you could reproduce this bug without using pistons, this would be a new bug. ;)
A piston just reacts to a redstone signal and duplicates with the right timing.

**Comment by BillyGalbreath** [comment]
The bug is actually in the slime block. Remove the slime block, remove the bug ;)
