### ISSUE TITLE
Enable hoppers configurations for minecraft with hopper

### ISSUE THREAD

**Issue by eUipKh** [PaperMC/Paper#3008]
**Is your feature request related to a problem? Please describe.**
So we have a pretty hardcore item transfer speed /amount in our server (8 items every 64 ticks) to reduce some hopper lag because we have a lot of them but I just realize that we still have some lag coming from InventoryMoveItemEvent called by minecarts with hoppers.

Video: https://youtu.be/LuR87BoKQmI

In the video it took 2 minutes to call InventoryMoveItemEvent 40 times with hoppers and just 3 seconds to do the same with minecart with hoppers.

**Describe the solution you'd like**
It would be really nice to have a config option to enable hoppers settings for minecarts with hopper, this will reduce some lag coming from plugins that listen to InventoryMoveItemEvent.

**Describe alternatives you've considered**
None.

**Additional context**
Tested on paper 1.15.2 build 126.

**Comment by HexedHero** [comment]
+1 Hopper Minecarts are death when it comes to lag

**Comment by QalleVcs** [comment]
+1 like and comment if you agree

**Comment by BillyGalbreath** [comment]
Uh.. For minecart hoppers to work they quite literally _needs_ to tick/scan every tick. This is because they are almost always in motion.

Imagine a 10 length track with a minecart hoppers going back and forth. There is a chest directly above the very center. How often do you think time, the stars, and the planets will align if that hopper only scanned once a second? (Hint: almost never)

**Comment by HexedHero** [comment]
> Uh.. For minecart hoppers to work they quite literally _needs_ to tick/scan every tick. This is because they are almost always in motion.
> 
> Imagine a 10 length track with a minecart hoppers going back and forth. There is a chest directly above the very center. How often do you think time, the stars, and the planets will align if that hopper only scanned once a second? (Hint: almost never)

Over the years of seeing players make farms with Minecart hoppers they always have a track always under other hoppers/chests and/or sitting still pulling drops from a magma floor for example. Regardless having a setting for this would only improve servers with players/farms like this and not affect servers with a setup like you mentioned.

**Comment by electronicboy** [comment]
It would affect servers setup like that, you'd still end up with items being transferred in an unreliable manner, thus leading to more bug reports; This would 100% be unattachable to the existing settings for this very reason

**Comment by HexedHero** [comment]
> It would affect servers setup like that, you'd still end up with items being transferred in an unreliable manner, thus leading to more bug reports; This would 100% be unattachable to the existing settings for this very reason

Put it in the unsupported settings? I'm confused, the people that would enable this should and would know how this is going to affect the hopper carts and want it to be like that when enabling it.

**Comment by aikar** [comment]
This feels best left to a plugin. This is trivial for a plugin to delete minecarts with hoppers and prevent creating or placing new ones.

You either accept the lag they cause with how players use them, or you don't allow players to use them.

There is no in between here.
