### ISSUE TITLE
Villagers get out of bed at the wrong location

### ISSUE THREAD

**Issue by adepierre** [PaperMC/Paper#3009]
### What behaviour is expected:
The villager should get out of his bed on the one block we want when he is in a cell

### What behaviour is observed:
The villager escapes to blocks he doesn't in vanilla

### Steps/models to reproduce:
I found this testing the simple model of iron farm presented by Gnembon in [this video](https://www.youtube.com/watch?v=vMSiholH_lc). [World download](https://www.dropbox.com/s/gf9u43m3s8yckb1/1.14.4%20iron%20farms%20(both%20worlds).zip?dl=0)

- load the world with paper
- go to the farm with rails
- /time set night to force the villagers to go to bed
- /time set day to let them get out of it

Some of them should be out of their cell

### Plugin list:
None

### Paper build number:
Paper-126

### Anything else:
Here is an image of the cell they escape from. One villager has decided to leave its bed on the glass block two layers under the bed. The same behaviour doesn't happen on a vanilla server where all the villagers get out on the one block in the middle.

![image](https://user-images.githubusercontent.com/24371370/76111687-0090ee80-5fe1-11ea-848c-2a17dd3311c6.png)

**Comment by Awakened-Redstone** [comment]
I'm have the same issue with the same farm...

**Comment by adepierre** [comment]
@Awakened-Redstone there is a simple fix for the farm: just fill the space under the two beds with glass and add 3 more on the next block.

You should end up with something like that (V = villagers, B= bed and G = glass):

```
V   B    B   G
    G    G   G
    G    G   G
```

This doesn't fix the paper bug but it fixes the farm in paper :)

**Comment by Awakened-Redstone** [comment]
Tanks, was searching for a temporary fix

**Comment by electronicboy** [comment]
Odd, it's like they /try/ to wake up where they're supposed to, and just derp somewhere in the process, had one that just floated around randomly when tryna sleep in general before popping underneath the beds...

**Comment by Noah0505** [comment]
I have the sam issue to with same farm. 
have a video with some bad english and a world download. 
https://youtu.be/D-IJM0JW8bY
https://drive.google.com/drive/folders/1VQ_7x6hg9E449HhlidPkpwh9GJaHYVtO?usp=sharing

**Comment by Articdive** [comment]
If it helps, replacing the inner side of the glass box with slabs solves the problem (if you really need your iron farm to work)!
like this:
https://i.imgur.com/hGxu5vz.png

**Comment by luke790** [comment]
> I have the sam issue to with same farm.
> have a video with some bad english and a world download.
> https://youtu.be/D-IJM0JW8bY
> https://drive.google.com/drive/folders/1VQ_7x6hg9E449HhlidPkpwh9GJaHYVtO?usp=sharing

Hey, I downloaded your world but I cant find where the iron farm actually is. Do you have coordinates?

**Comment by Noah0505** [comment]
> > I have the sam issue to with same farm.
> > have a video with some bad english and a world download.
> > https://youtu.be/D-IJM0JW8bY
> > https://drive.google.com/drive/folders/1VQ_7x6hg9E449HhlidPkpwh9GJaHYVtO?usp=sharing
> 
> Hey, I downloaded your world but I cant find where the iron farm actually is. Do you have coordinates?

The coordinates is -1085 78 2262

**Comment by ghost** [comment]
Had this issue as well, ended up replacing some of the glass with slabs. It appears to have been caused by patch 0242 that allows a configurable bed search radius.

**Comment by bregger** [comment]
It looks like patch 0242 replaces vanilla bed search with a configurable bed search algorithm, and defaults the bed search radius to vanilla settings.

There's a few ways to fix it and it should be a pretty simple PR either way. Not sure what the more paper-mc community way to fix it would be though. Of these alternatives what would be the better options

1. Use vanilla code for both players and villagers when bed search radius is set to 1
2. Always use vanilla code for villagers, since it seems unlikely that the intent was for this patch to impact villagers.
3. Both (I'd lean towards doing both personally)

From the comments it doesn't seem like it is intended to be a performance optimization. Seems like when we're adding configuration to change vanilla behavior it would be wise to always use the vanilla code when that config can be toggled "off" or set to a vanilla-like default. That way it's an opt-in for differences in quirks between the two.

**Comment by aikar** [comment]
the point of those changes was to help players, so less needed really for villagers. was simply a side effect of mojang reusing that code for villagers.
 id be ok with them going to vanilla logic.

**Comment by aikar** [comment]
kickash has made some changes that should resolve this, please let us know if still an issue in latest build

**Comment by ghost** [comment]
Appears to still be an issue in the latest build. My villagers just keep escaping...

**Comment by kickash32** [comment]
I have tested the farm configuration many times and it never happened after the fix, can you reupload your world download. The current link doesn't work.
