### ISSUE TITLE
Issues with server startup

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#301]
With paper 748 particularly this commit https://github.com/PaperMC/Paper/commit/d22f9071ff1c2cd8f4c0513a0e3d9b3e8e119a0c

the server takes a few minutes longer to startup, mainly after "loading libraries..." during which time cpu usage is at 100% and I have even got "unable to create new native thread" errors despite having plenty of memory

when doing a jstack it at first didnt even respond at all, then got this message and similar spammed a couple hundred times: http://pastebin.com/1nxAeGWQ

with build 747 this issue does not happen at all

**Comment by Techcable** [comment]
Its deadlock because Aikar tried to make the UserCache thread safe for my UUID API.
My rewrite of minecraft's UUID caching system fixes it (bur Aikar wants it seperate from the UUID API).

**Comment by zachbr** [comment]
Closing for age, inactivity, I don't believe this issue is still as prevalent.
