### ISSUE TITLE
Chunk error on loading/unloading

### ISSUE THREAD

**Issue by Corenb** [PaperMC/Paper#3010]
### What behaviour is expected:
Chunk error on loading/unloading

### Plugin list:
![plugins](https://user-images.githubusercontent.com/1338450/76150196-0271b500-60a8-11ea-801c-402c1e9ba305.PNG)

### Paper build number:
git-paper-129

### Anything else:
https://pastebin.com/VTcV3swm

**Comment by wizjany** [comment]
your reported build number and jar name disagree 🤔

**Comment by Corenb** [comment]
> 
> 
> your reported build number and jar name disagree 🤔

Oups sorry :x I read the previous version...
