### ISSUE TITLE
Appears every day scary stacktraces

### ISSUE THREAD

**Issue by XXY233** [PaperMC/Paper#3014]
### Link/paste of stack trace
https://pastebin.com/S6t2462d

### Plugin list:
AAC, Brewery, ChestSort, ChestTerminal, CMI, Companions, CoreProtect, CrazyCrates, CS-CoreLib, DeluxeJoin, DeluxeMenus, DiceFurniture, DyedBackpacks, DynamicBungeeAuth*, ExoticGarden, FurnitureLib, HolographicDisplays, HotbarPets, Images, InventoryRollback, JukeBox, LockettePro, LuckPerms, Magic, Marriage*, MineChess, MobFarmManager, NoteBlockAPI, PlaceholderAPI, PlotSquared, PocketMobs, ProtectionLib*, ProtocolLib, QualityArmoryVehicles, Residence, SAML, ShopChest, Slimefun, TitleManager, UltimateFireworks, Vault, VolleyBall, WorldEdit, WorldGuard

### Actions to reproduce (if known):
This has been on my server for a week,The server always stops responding. I don't know when and how it happened, but it appears several times a day, and I don't find any plugins from it. Each time it happens (the location of the block) is different, but the stacktrace of the trace is the same.

### Paper build number:
This server is running Paper version git-Paper-129 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-128 (MC: 1.15.2)

**Comment by MiniDigger** [comment]
Your server cant keep up processing entity collission. This is not a paper bug (as the logs say...)
Do you have a timings link?

**Comment by XXY233** [comment]
> Your server cant keep up processing entity collission. This is not a paper bug (as the logs say...)
> Do you have a timings link?

Yes I had one during that time: https://timings.aikar.co/?id=0835a6645c3b42d48b1a949dfe50ddf1

**Comment by electronicboy** [comment]
not a paper issue, your server is taking too long to tick; processing collisions from player movement; in the future, for support with timings and "taking too long to tick", please use the discord/irc/forums
