### ISSUE TITLE
Villages cats control

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#3016]
**Is your feature request related to a problem? Please describe.**
Today, cats naturally generated by villages (villagers and beds) are a plague. I'm worried about their pathfinding (if is the case) because they walk far away from the villages... Also you can find them lost in the forests or floating in the water.

**Describe the solution you'd like**
Some method to control cat spawning from villages or an option to disable this mechanic.

**Comment by Misio12320** [comment]
What's the status? This is a problem on my server.. @Chew

**Comment by Chew** [comment]
How in the world am I supposed to know, I assigned the label 3 months ago and I don't even do any developing...
