### ISSUE TITLE
Skeleton horses plague

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#3017]
**Is your feature request related to a problem? Please describe.**
You can find them everywhere ...

**Describe the solution you'd like**
If a skeleton horse trap despawns over time if not triggered, force some kind of despawn over time of the skeleton horses spawned when the trap is triggered. I think they are the ones remains wandering the world.

**Comment by kickash32** [comment]
Skeleton horse trap already despawns if not triggered in 15 minutes. Would you like a similar configurable timer for Skeleton horses after the trap is triggered and the skeletons are defeated?

**Comment by lordrius** [comment]
Yes, I had thought about applying them **setRemoveWhenFarAway()** or something when they spawn because of Triggered Trap, but this would prevent players from getting and keeping them... So it's not a good option.

They are so many wandering everywhere...

Thanks for your time!

**Comment by kickash32** [comment]
They could be configured to be removed when they are far away if the skeleton rider has been killed. Essentially after the trap has been dealt with, the skeleton horses act like passive monsters (they won't attack like daytime spiders) and despawn if players are far away.

**Comment by Proximyst** [comment]
I think that this is more of plugin territory; use [`#setRemoveWhenFarAway`](https://papermc.io/javadocs/paper/1.16/org/bukkit/entity/LivingEntity.html#setRemoveWhenFarAway-boolean-) and [`EntityMountEvent`](https://papermc.io/javadocs/paper/1.16/org/spigotmc/event/entity/EntityMountEvent.html) together to let players keep them.
