### ISSUE TITLE
fix-cannons no effect

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#302]
Paper build 747

fix-cannons: true

has no effect

**Comment by zachbr** [comment]
Duplicate of GH-296.
tl;dr the majority of features it provided were hopelessly broken as of 1.9. So it was completely removed as of 1.9.4. We're open to PRs and help, but we're not cannoners, nor do we have any interest in becoming them, we aren't capable of properly testing this ourselves. Help wanted.

**Comment by PaulGaming** [comment]
@Zbob750  I know the main aspects of cannoning and how they work; I could help you guys in understanding the basics and how they work.

**Comment by zachbr** [comment]
@PaulGaming thanks for your offer :) I will try and get that patch updated again soon and we can start playing with it.

**Comment by PhanaticD** [comment]
I can host test server if needed

**Comment by Techcable** [comment]
SportBukkit seems to have it for 1.9.4: https://github.com/OvercastNetwork/SportBukkit/blob/master/CraftBukkit/0073-Fix-TNT-physics.patch

**Comment by zachbr** [comment]
They have their own subset of changes, not all of them. They're not really a cannon server though either. Have to look more into what they're doing.

**Comment by Techcable** [comment]
It could help 🍊

**Comment by zachbr** [comment]
We have it already :p save for the explosion changes

**Comment by PaulGaming** [comment]
So you found a fix already?

**Comment by zachbr** [comment]
I have no idea if it's "fixed", as I said we aren't cannon people. Check commits, TNT behavior changes are in with a different config value

**Comment by PhanaticD** [comment]
i put the latest version on our cannon server, we will test it

**Comment by PaulGaming** [comment]
It seems to work a bit.. theres a couple issues with entity movements that's a pain.
