### ISSUE TITLE
Vanilla in Paper's config.

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#3020]
**Is your feature request related to a problem? Please describe.**
I think the Paper is bugging the Vanilla Minecraft. So I want to suggest a thing.

**Describe the solution you'd like**
Add a config to make vanilla 100% in Paper e.g Paper remove entities to get better perfomance, and Minecraft does not. So I suggest to make 100% Vanilla with little performence upgrade to Vanilla.

**Describe alternatives you've considered**
Should be better because I want to use Minecraft Vanilla with plugins without Paper's removing entity or some examples...

**Additional context**
None.

**Comment by electronicboy** [comment]
> e.g Paper remove entities to get better perfomance
No it doesn't?

Papers config aims to be vanilla by default where we're tweaking stuff, there is also no viable way for there to be a single config flip to tweak a lot of settings, that would break a lot of the configuration aspect

**Comment by Gaming32** [comment]
If you would like to do this, I would recommend using Spigot instead, as it does much less tweaking by default. The performance isn't as good though (from what I've heard). Or you could do something else entirely, such as Sponge (has an entirely different plugin API than Spigot and Paper, which are based on Bukkit).

**Comment by emielderckx** [comment]
> If you would like to do this, I would recommend using Spigot instead, as it does much less tweaking by default. The performance isn't as good though (from what I've heard). Or you could do something else entirely, such as Sponge (has an entirely different plugin API than Spigot and Paper, which are based on Bukkit). 

That is not how it works, paper is closer to vanilla then spigot/bukkit.

If you want vanilla use fabric, the vanilla jar or play around with paper's config
