### ISSUE TITLE
no memory leak, this post is invalid

### ISSUE THREAD

**Issue by PonyPC** [PaperMC/Paper#3024]
###  Timings or Profile link:
[https://timings.aikar.co/?id=e678c915bd724fec923df39ffa11986e](https://timings.aikar.co/?id=e678c915bd724fec923df39ffa11986e)

### Description of issue:
I have tested 5G and 10G heap size of jvm. Since Old Gen is full after about 100 player playing around 1 hour, the Eden Gen will trigger a full gc while it's full too. BUT the significant thing is Survivor Gen never be used after Eden/Old Gen full. And the Full GC Time spends around 5-10s depending on heap size. That will cause TPS drop down and use up all of my 8 core CPU to gc.
This is jstat info:
```
S0C      S1C       S0U    S1U   EC       EU       OC         OU         MC       MU       CCSC    CCSU      YGC    YGCT    FGC  FGCT     GCT
227840.0 150528.0  0.0    0.0   714752.0 714752.0 6329600.0  6329202.5  112384.0 101281.2 15872.0 13478.0   2802   63.118  601  6472.430 6535.547
```
According to jvm docs, if garbage size is bigger than Survivor Gen, it would be send to Old Gen after minor GC. And the Old Gen is full cause Full GC finally.
I have searched on StackOverFlow, and find this post said it mostly has memory leak cause a huge memory area can't put in to Survivor Gen. From: [https://stackoverflow.com/questions/54512129/jvm-survivor-spaces-are-not-used](https://stackoverflow.com/questions/54512129/jvm-survivor-spaces-are-not-used)
I also tested with Spigot same version and same plugins. The Survivor Gen is always used and TPS is stable. So I think the issue may be in Paper. 😥 But I can't find the issue source. I have dumped the jvm heap, only shows a large mount of bytes in top of memory class list. I wish Paper can fix it and port back to 1.12.2. Thanks.

### Plugin list:
Essentials, LWC, WorldGuard, ClearLag, ProtocolLib, AngelChest, CoreProtect, BungeeTabListPlus, GroupManager, WorldEdit, antiRedstoneClock, OpenInv, EssentialsProtect, DisableJoinMessage, BetterChairs, PvPToggle, MysqlInventoryBridge

### bukkit.yml, spigot.yml, paper.yml, server.properties
[bukkit.yml](https://paste.ubuntu.com/p/wNJMPWWnzk/)
[spigot.yml](https://paste.ubuntu.com/p/fp8Nzpn95z/)
[paper.yml](https://paste.ubuntu.com/p/9hy7tFtt5y/)
[server.properties](https://paste.ubuntu.com/p/qYCMc7QBds/)

### Other helpful links
Heap size is toooo big to upload, but the top of use is Bytes[] around several gigabytes.

### Paper build number:
This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
This server is running Paper version git-Paper-132 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by PonyPC** [comment]
I don't know why you give me a 👎. @Spottedleaf

**Comment by electronicboy** [comment]
1.12.2 is unsupported, we also cannot debug this type of stuff without a dump

**Comment by PonyPC** [comment]
1.15.2 also has this issue, wait for me about hours to upload 1.15.2 heap. @electronicboy

**Comment by PonyPC** [comment]
I have uploaded [heap](http://www.ipeggyhsu.com/xxx.7z)
Please reopen this issue, thanks. @electronicboy

**Comment by electronicboy** [comment]
replicate without plugins

**Comment by PonyPC** [comment]
Okay, many thanks. I'll upload after finish. @electronicboy

**Comment by PonyPC** [comment]
I'm sorry, I confirmed that paper has no memory leak. Sorry for disturbing. @electronicboy @Spottedleaf

**Comment by aikar** [comment]
You are using some really weird Java flags overall.

You also do not seem to have an understanding on how java gc works.
yes paper uses more memory to improve performance, but it is not a leak.

If java GC is not tuned correctly to its usage with the standard old GC engine, yes performance can suffer.

But with G1GC, GC is easier to tune for most scenarios.

Please see https://mcflags.emc.gs for how to configure garbage collection.
