### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xGabrielUC** [PaperMC/Paper#3028]
### Link/paste of stack trace
    ERROR: https://hastebin.com/fopokezeyo.cs
    LOGS: https://www.mediafire.com/file/qubllf3f1zxa3ba/2020-03-14-1.log.gz/file

### Plugin list:
https://imgur.com/a/QaWVyBL

### Actions to reproduce (if known):
----

### Paper build number:
This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Trigary** [comment]
- That's an issue in the beloved SpigotCourse's / MineAcademy's / whatever's codebase
 - 1.12.2 is unsupported, it's 2 and a half years old

**Comment by electronicboy** [comment]
1.12.2 is no longer supported, nor does that error have anything to do with paper
