### ISSUE TITLE
Problems removing unloaded entities

### ISSUE THREAD

**Issue by XxMoonlightBringerxX** [PaperMC/Paper#3030]
### What behaviour is expected:
 In Spigot, the code I use removes the entities on unloaded chunks when the server stops.

### What behaviour is observed:
In Paper, it doesn't, the entities get dup on start.

### Steps/models to reproduce:
1.- I claimed a horse to register it in the plugin.
2.- I restarted the server on two different versions, Spigot and Paper.
3.- On Spigot the entity gets removed and on Paper not.

### Plugin list:
- MMO Equestrians

### Paper build number:
Last build offered on Yive's Mirror.

### Anything else:
What I use to remove the entities on stop is the next code:

Main
```java
public void onDisable() {
	hm.unload();
	MySQL.close();
}
```

Manager:
```java
public void unload() {
	if (horses != null) {
		YamlConfiguration yml = FileManager.getYml(FileManager.LINKS_FILE);
		for (HorseInterface hi:new ArrayList<>(horses)) {
			if (!hi.getHorse().isValid()) HorseManager.findHorse(hi);
			if (hi.isLinked()) yml.set(String.valueOf(hi.getId()), VUtils.locParse(hi.getHorse().getLocation()));
			else yml.set(String.valueOf(hi.getId()), null);
		HorseManager.unloadHorse(hi, true);
		}
		FileManager.saveYml(yml, FileManager.LINKS_FILE);
	}
}
```

findHorse method:
```java
public static void findHorse(HorseInterface hi) {
	hi.getHorse().getWorld().loadChunk(hi.getHorse().getLocation().getChunk());
	for (Entity ent:hi.getHorse().getLocation().getChunk().getEntities()) if (ent.getUniqueId().compareTo(hi.getHorse().getUniqueId()) == 0) hi.setHorse((Horse) ent);
}
```

I would appreciate another way more correct to find the unloaded entities, but I would like to know which differences between Spigot and Paper are making them dup. I don't know if it's about the isValid() checking or other fields of the entities.

**Comment by aikar** [comment]
your horse instance should contain a weakref to the entity its bound to.
on unload, then just do

forEachHorse:
Entity entity = horse.getEntity();
if (entity != null) entity.remove();


Anytime an entity is associated to a Horse, do horses.put(entity.getUniqueId(), horse);


And in ChunkUnloadEvent, iterate all entities, if entity is tied to a horse remove it

Horse horse = horses.remove(entity.getUniqueId());
if (horse != null) entity.remove();


For further help, please use #paper-dev on discord.
