### ISSUE TITLE
When you exit an hopper or brewing stand all the items go to your inventory

### ISSUE THREAD

**Issue by sian2005** [PaperMC/Paper#3032]
### What behaviour is expected:
When you exit an hopper or an brewing stand, the items stay in there.

### What behaviour is observed:
All the items go straight to your inventory when you exit an hopper or brewing stand, there is no way around this.

### Steps/models to reproduce:
![Paper Hopper Bug](https://user-images.githubusercontent.com/62208362/76702715-5e51c480-66cc-11ea-9b82-9c91ff98c4a3.gif)

### Plugin list:
ItemJoin.jar was the issue

### Paper build number:
git-paper-112 (MC 1.15.2)

**Comment by MrEDok** [comment]
Update paper and replicate without plugin.
Tested on latest paper and doesnt have this problem. So mostlikely a bad plugin doing that

**Comment by sian2005** [comment]
Found it :)
It was ItemJoin

**Comment by MiniDigger** [comment]
pls close this issue then :)
