### ISSUE TITLE
zero tic bamboo farm dont work.

### ISSUE THREAD

**Issue by Noah0505** [PaperMC/Paper#3033]
### What behaviour is expected:
___What you expected to see___ bamboo grow ca every tick

### What behaviour is observed:
___What you actually saw___ bamboo not growning at all

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___ zero tick bamboo farm

### Plugin list:
___A list of your plugins___ nothing that efects zero tick

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___ 135

### Anything else:
___Anything else you think may help us resolve the problem___ zugarcane farm zero tick works

**Comment by Trigary** [comment]
You pretty much failed to follow the issue template... Anyway, did you disable the patching of zero tick farms in paper.yml? Did you try looking for a solution? Both Googling this and searching on GitHub gave me the fix.
