### ISSUE TITLE
Players going through end portal not teleported to the correct coordinates

### ISSUE THREAD

**Issue by ARman444** [PaperMC/Paper#3035]
### What behaviour is expected:
The player is teleported to the correct coodinates (100, 49, 0)

### What behaviour is observed:
Player keeps their overworld coordinates when teleporting.

### Steps/models to reproduce:
Video of it happening: https://www.youtube.com/watch?v=KIjNbBmuFbo
This is a very inconsistent bug, so this is all I have to offer, unfortunately.

### Plugin list:
CustomCrafting, DangerousCaves, DeathChestPro, DeathMessagesPrime, EssentialsX, FirstJoinPlus, GSit, ImageMaps, Matrix Anticheat, OpenInventory, PermissionsEx, PlayerHeads, ProtocolLib, SilkSpawners, SlimeFinder, SpigotPing, TabList, WildTP, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
paper-133 1.15.2

### Anything else:
This is a very inconsistent issue. Most of the time, this issue doesn't occur. I'm pretty sure this used to be a vanilla server bug that was patched a while ago.

**Comment by ARman444** [comment]
Update: Did some testing with the person in the video. It appears that it's mostly an issue with high ping, as he was able to recreate it multiple times (albeit very inconsistently). Server TPS stayed at a consistent 20.

Unfortunately, I was unable to recreate the issue myself, which makes me think it could be an issue with his client. Could that be the issue?

**Comment by heathfx** [comment]
We are experiencing this as well with high-ping players. has happened at least 5 times.

**Comment by ARman444** [comment]
I love paper, but this issue is keeping me from using it. Would really appreciate it if this was fixed soon!
