### ISSUE TITLE
Trader llama performance issues or unusual timings report

### ISSUE THREAD

**Issue by pengooin** [PaperMC/Paper#3037]
###  Timings or Profile link:
Original timings report, please notice how 62% of the time spent on ticks is only on LlamaTraders, despite only an average of 10.95 llama traders ticked per second, or 32.72ms in total. I manually counted and used the paper entities list command to determine there were 14 trader llamas in total for the world. All of these llamas came from wandering traders that had spawned in the world.
https://timings.aikar.co/?id=6d4c6b5d67c549dfa80997d2b9feb470

In an attempt to see if trader llamas were the problem, I summoned in 20 trader llamas and re-ran the timings. Despite doubling the average llama traders per tick (now 22.69), 57.15% of the time spent on ticks was solely for llama traders, or 30.71ms in total.
https://timings.aikar.co/?id=0bfd223d42ae45bb9c6d8eee110d2c05

I was highly confused how the total time to process all of the trader llamas was approximately the same, so I removed the 20 extra trader llamas I spawned, returning to the original number of 14 trader llamas. The timings report indicates again that trader llamas took 62.34% of the time spent processing a tick, with an average number of 10.62 llamas ticked per tick, overall taking 32.58ms to process all llama traders.
https://timings.aikar.co/?id=03b3479e0c0145729295b9d82fe85a01

### Description of issue:
Timings is reporting that trader llamas are taking up more than half of the time to process a tick, despite there only being 14 trader llamas in the world (I manually counted and used the paper entities list command). To test if llamas were the problem, I summoned in 20 more trader llamas. The performance had virtually no change. Confused, I removed the 20 spawned in trader llamas, and performance was again unaltered. 

One thing to note is that the original 14 trader llamas were all obtained from naturally spawned wandering traders. It is possible that those 14 are causing all of the lag, and the 20 trader llamas I spawned in were in some way different from those that came from a wandering trader, for the summoned in trader llamas did not noticeably impact performance when added or removed. It is also possible that this problem is completely irrelevant to trader llamas, and is instead a problem with the timings report.

Additionally, please be aware that trader llamas and llamas are not the same entity, and performance of llamas appears to be acceptable.
### Plugin list:
None

### bukkit.yml, spigot.yml, paper.yml, server.properties
Spigot.yml - https://pastebin.com/Wyfx4P7M
Paper.yml - https://pastebin.com/SV39wyDJ
Bukkit.yml - https://pastebin.com/rz4NRqGY
Server.properties - https://pastebin.com/QbF72Pmx

### Other helpful links
N/A

### Paper build number:
This server is running Paper version git-Paper-135 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by pengooin** [comment]
It appears the problem is timings, I removed the 14 offending trader llamas, and instead of trader llamas taking up a significant portion of each tick, sheep, salmon, skeleton horses, and zombies all went up in time per tick.

A timings report with the 14 trader llamas removed about midway:
https://timings.aikar.co/?id=c9cb379e6fc54f328b85e8a02dfa8415

A timings report where during the entire timing, there were no trader llamas in the world.
https://timings.aikar.co/?id=90ef1671946f43b4a274ee5f33f2abd8

**Comment by AJMFactsheets** [comment]
This issue duplicates Issue #2489 
The way I currently get around this bug is to set the timing start and end point to the same time, then results seem accurate.

**Comment by pengooin** [comment]
Sorry if I do not interpret this correctly, but it seems these are different issues. In #2498 the number of entities per tick is highly inflated (666 cats instead of 79), in my case the number of entities per tick appears to be correct (There were 14 llamas in the world, and an average of 10 llamas per tick), but the time per entity is inflated. 

Either way I will try your suggestion with timings, thank you.

**Comment by pengooin** [comment]
It appears update 143 for paper 1.15.2 has resolved this issue. My timings reports make much more sense now, thank you!
