### ISSUE TITLE
Lack of Hostile mobs spawning

### ISSUE THREAD

**Issue by Cyber-MC** [PaperMC/Paper#3042]
###  Timings or Profile link:
https://timings.aikar.co/?id=b858059e2315473093f81e5fefa52e32

### Description of issue:
Since yesterday afternoon, I have been attempting to figure out why there is a lack of hostile mobs on the server I co-own, named WonderCraft. On our 1.15.2 port "Buzzy," the gamemode is considered to be Slimefun Survival, but the difficulty is set to Hard. After tinkering around with the bukkit.yml a couple days ago, I decided to increase the mob limit per chunk and that was the end of that. Fast forward a day later or so and they're pretty much gone, except for some peaceful mobs and phantoms.

### Plugin list:
___All plugins running on the server___
![image](https://user-images.githubusercontent.com/31489616/76966793-802d9000-68f4-11ea-8558-661ace2093bb.png)

### bukkit.yml, spigot.yml, paper.yml, server.properties
Bukkit.yml: https://hastebin.com/fuwiyuqepu.coffeescript
Spigot.yml: https://hastebin.com/enofozayoc.cpp
Server.properties: https://hastebin.com/xikuyeloci.bash
### Other helpful links
Slimefun-4: https://github.com/TheBusyBiscuit/Slimefun4 (Unsure if this could be the issue)

### Paper build number:
Paper Build: git-Paper-140 (Latest)

![image](https://user-images.githubusercontent.com/31489616/76967071-e1556380-68f4-11ea-9fd3-0f47d120397b.png)

**Comment by Cyber-MC** [comment]
Note: This issue still occurred on Paper 137

**Comment by electronicboy** [comment]
only recent change was some changes to the counters from upstream which should have no real-world impact on counts, etc;
we've had several reports of this, but cannot reproduce ourselves, best advice is replicate without plugins, etc

**Comment by Cyber-MC** [comment]
> only recent change was some changes to the counters from upstream which should have no real-world impact on counts, etc;
> we've had several reports of this, but cannot reproduce ourselves, best advice is replicate without plugins, etc

I'll see what I can do locally

**Comment by Cyber-MC** [comment]
Locally seemed to work just fine, so I am unable to reproduce the issue as well. I'm going to see if resetting the bukkit.yml will work.

**Comment by Cyber-MC** [comment]
Yeah that worked, jesus christ so many mobs
