### ISSUE TITLE
Player Yaw displays incorrectly

### ISSUE THREAD

**Issue by Klyser8** [PaperMC/Paper#3045]
### What behaviour is expected:
As a player turns their head, the yaw should change between 0 and 360

### What behaviour is observed:
If a player keeps spinning the same direction, the Yaw keeps going up to the thousands.

### Steps/models to reproduce:
1. System.out.println(playerMoveEvent.getFrom().getYaw()) in any plugin
2. In game, keep turning your head clockwise/counter clockwise without changing direction.
3. The Yaw can be observed to be going up to the thousands in the console

### Plugin list:
Only a custom plugin to test this.

### Paper build number:
git-Paper-143 (MC:1.15.2)

**Comment by kickash32** [comment]
fixing this may break plugins which expect this behaviour

**Comment by Klyser8** [comment]
> fixing this may break plugins which expect this behaviour

But the behavior does not make much sense in terms of how it is supposed to work.

If this wants to be kept, I think that a description on how the Yaw actually works in the docs would be great, so that there isn't as much confusion surrounding it.

**Comment by Black-Hole** [comment]
You should report that to the Spigot issue tracker. Currently there are no patches in Paper that just changes JavaDoc.

**Comment by Beaness** [comment]
This is i think a minecraft bug. When i was debugging packets i saw that the same thing happens. When the player keeps turning their head it keeps increasing the yaw. The yaw in look packets is over 360 when this happens.

**Comment by electronicboy** [comment]
a mixture of "that's how the API's always worked" (to my knowledge, somebody did test 1.8) and that's how vanilla does it, otherwise, you can't track player movement properly
