### ISSUE TITLE
One-hit killing a zombie pigman angers nearby pigmen

### ISSUE THREAD

**Issue by Southpaw1496** [PaperMC/Paper#3046]
**It is now fixed in Build 245 (maybe before that but the point is it's fixed)**
### What behaviour is expected:
___When you one-hit kill a zombie pigman, other pigmen do not get angry___

### What behaviour is observed:
___The pigmen do, in fact, get angry___

### Steps/models to reproduce:
___

1. Obtain a diamond axe with Smite 5
2. Spawn some pigmen (not required if pigmen are already there)
3. Switch your gamemode to survival
4. Hit one
[Video](https://youtu.be/r7j0RGYbMRU) 

___

### Plugin list:
___None___

### Paper build number:
___git-Paper-143___

### Anything else:
___Nothing___

**Comment by Trigary** [comment]
Is the expected behaviour you described the one currently in vanilla Minecraft?

**Comment by wizjany** [comment]
iirc in discord it was mentioned that this is not vanilla, but is upstream (bukkit or spigot, unsure what was tested)?

**Comment by Southpaw1496** [comment]
It's not vanilla behaviour and I did test and it's not on Spigot (which I assume means it's not on CraftBukkit)

**Comment by aikar** [comment]
working fine on latest paper
