### ISSUE TITLE
Restart script terminated early

### ISSUE THREAD

**Issue by thislooksfun** [PaperMC/Paper#3047]
### What behaviour is expected:
On crash or using the `restart` command the restart script should be started and kept alive.

### What behaviour is observed:
The restart script is started, but the is killed when Java exits.

### Steps/models to reproduce:
1. Create a `start.sh` script
2. Set it as the restart script
3. Start the server
4. Issue the `restart` command
5. The server won't be restarted

### Plugin list:
This is not a plugin issue

### Paper build number:
`Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

### Anything else:
This is happening on Ubuntu 18.04.3 LTS, using Openjdk version "1.8.0_242", and I am starting the server initially using `screen -dmS minecraft <start script>`

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/issues/2402#issuecomment-518004013
