### ISSUE TITLE
Hostile mobs sometimes appear invisible, require leaving and re-joining the server to become visible again

### ISSUE THREAD

**Issue by iCeParadox64** [PaperMC/Paper#3048]
### What behaviour is expected:
I expect all mobs on the server to be visible, obviously.

### What behaviour is observed:
Sometimes, hostile mobs will appear invisible. They cannot be seen, they cannot be attacked, but they can still attack players. This has happened with zombies, zombie pigmen, and pillagers, and probably others that slip my mind. It happens to all players on my server, and requires the affected player(s) to leave the server and re-join for the mobs to become visible again.

### Steps/models to reproduce:
Seemingly happens completely at random. At first I thought it might only be happening in our main town since there's a lot going on there, but it recently happened to me while I was thousands of blocks away, and I was the only one on the server.

### Plugin list:
ChestSort, FastLeafDecay, Graves, Lasso, LuckPerms, PhantomSpawnControl, Sickle

### Paper build number:
**git-Paper-143** (1.15.2)  
This also happened on the previous version, **git-Paper-112** (1.15.2)

**Comment by kickash32** [comment]
Make sure all your plugins are updated and test again

**Comment by iCeParadox64** [comment]
All plugins are up-to-date. Still happening.

**Comment by Proximyst** [comment]
What's the status of this? ~~We've gotten EAR 2 now, which might have fixed this as a "side-effect";~~ (EDIT: strikethru, see kickash' comment) is it still replicable?

**Comment by kickash32** [comment]
EAR has nothing to do with tracking entities.

**Comment by aikar** [comment]
Going to go ahead and close as there's been no other reports of this, but we've also since rewrote entity tracking, so please file new issue with relevant information if it still exists on latest.
