### ISSUE TITLE
Server crashes when certain players join.

### ISSUE THREAD

**Issue by Mobbybobby** [PaperMC/Paper#3049]
Hi my skyblock server(1.15.2 newest paper release no Plugins) crashes when certain players join. Paper starts saying the server is not responding until it finally shutsdown after lika minute. The players that are affected broke a composter and replaced it. The Composter was a POI of an Villager. I removed the Composters in console to fix it but i didn't fix it. I tried deleting the poi data and the playerdata, but nothing helped. I also tried mc region fixer and it didn't find any problems. Everyone else can play on the server. only when one of the 2 players join the server immediately stops responding. I don't know if this is the right place to poast this but maybe someone can help.

https://pastebin.com/gzLaywZy

thx

Mobby

**Comment by electronicboy** [comment]
the server is timing out due to chunk loading induced from teleporting players from some datapack
