### ISSUE TITLE
TPS problems, unknown source

### ISSUE THREAD

**Issue by martijnpu** [PaperMC/Paper#3056]
###  Timings or Profile link:
https://timings.aikar.co/?id=917bd9453fc641f9870e356444873ebd

### Description of issue:
The TPS on our server drops sometimes and we as staff can't find the source of it. Looks like minecraft::entityTick (SELF), but no idea what that is.

### Plugin list:
Plugins (54): AdvancedPortals, AnimatedNames*, AsyncWorldEdit, BKCommonLib, BungeeTabListPlus, BuycraftX, ChatControl, ClearLag, ColoredSigns*, CombatLogX, CoreProtect, CrateReloaded, CustomDeathHolograms*, DeluxeMenus, Essentials, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, HolographicDisplays, HolographicExtension*, IngotsBlocks*, LightCleaner, LiteBans, LuckPerms, MiSwitch*, MVdWPlaceholderAPI*, MyHome*, MyWarp, NerfPhantoms, PlaceholderAPI, PlayerVaults, PrefiX, ProtocolLib, ProtocolSupport, RestartCountdown, RFChairs, Shop, Spartan, SuperbVote, SuperTrailsPro*, Tab*, TokenEnchant, TradeMe, UltimateTimber, UnbreakingAnvils*, Vault, ViaVersion*, VoteParty, Votifier, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://pastebin.com/Gw4WLycz

### Other helpful links
xxx

### Paper build number:
This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-118 (MC: 1.15.2)
You are running the latest version

**Comment by benwoo1110** [comment]
From the timings you have linked, it seems that ChatControl is the cause. Specifically reply and tell command. Can you give me more info on the plugin, like what is the use and function?

**Comment by martijnpu** [comment]
Thanks for looking!

ChatControl is a premium plugin, and highly maintained, for everything around the chat bungeewide. I'm passing this timings on to them to figure out what'w wrong, and hopefully they give me a specific answer or the change some code.
