### ISSUE TITLE
Exploding Pistons

### ISSUE THREAD

**Issue by nbclover** [PaperMC/Paper#3058]
### What behaviour is expected:
 Pistons retract normally

### What behaviour is observed:
Pistons explode when they are supposed to retract.

### Steps/models to reproduce:
The bug has occurred in a 0-tick farm, a tree farm, and an Etho hopper clock.

### Paper build number:
git-paper-135

### Anything else:
I think that the bug may be occurring because of pistons retracting and other pistons opposite of them extending at similar times, but I have to evidence to support this.

**Comment by Draycia** [comment]
plugin list

**Comment by Proximyst** [comment]
This issue should be closed for not being caused by paper in any sense.

Don't use explody pistony plugins. It's truly that simple. And remember to report the actual plugins list next time you open an issue which has a >99% chance of being caused by a plugin.
