### ISSUE TITLE
Server Crash - 1.14.4

### ISSUE THREAD

**Issue by rudipratm** [PaperMC/Paper#3059]
### Link/paste of stack trace
Crash Log's Link: [**Pastebin**](https://pastebin.com/KHNJAtz2)

_PS: I only showing the Beginning of ERROR SECTION till the End of it, to keep my users personal information._

### Plugin list:
AdvancedClans*, ChestCommands, ChestShop, ClearLag, Essentials, EssentialsChat, EssentialsSpawn, GUIShop, HealthBar*, HolographicDisplays, LoginSecurity*, mcMMO, Minepacks, MyCommand, PermissionsEx*, PlaceholderAPI, PluginHiderPlus, PlugMan, ProtocolLib*, ProtocolSupport, RedProtect, TAB, Vault, ViaBackwards*, ViaRewind*, ViaVersion*, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Nothing, just automatic restart the server after it crash.

### Paper build number:
This server is running Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT).

**Comment by JRoy** [comment]
Paper 1.14.4 is not supported, update to 1.15

Additionally, this problem was probably one of your plugins (Minepacks)

**Comment by rudipratm** [comment]
So that's why Minepacks appear at the first line?

Thanks for your information.

**Comment by electronicboy** [comment]
apparently severe server overload, nothing to do with minepacks either, that's just the hikari threadpool noting the fact that the time appeared to jump

**Comment by rudipratm** [comment]
So that is a memory overload. I've upgrade the memory to 6 GB and working fine. Thanks for your response :)
