### ISSUE TITLE
Packet Processing consume high cpu tick

### ISSUE THREAD

**Issue by malsem** [PaperMC/Paper#3060]
###  Timings or Profile link:
https://timings.aikar.co/?id=c10e19e826244f699ddedd6abd7f3497

### Description of issue:
The server is lagging really hard after upgrade to 1.15.2 from 1.14.4. All I can see from the timings is the packet processing is taking A REAL HIGH cpu usage. Is there any possible fix for the packet processing. Im using shared hosting with intel core i7-7700k(what the hoster said). The tps drop below 10 when player reached 30 and above. 

### Plugin list:
Plugins (50): AdvancedAnnouncement*, AdvancedHelp, AdvancedRegionMarket, AntiCommandSuggestions, AuthMe, BlockLocker, ChatManager, ChunkSpawnerLimit, Citizens, CitizensCMD, ClearLag, CMI, CMIEInjector*, Core, CoreProtect, CrazyCrates, DeathTax*, DiscordSRV, EnchantControl, EntityTrackerFixer, EpicRename, FarmLimiter, GriefPrevention, GriefPreventionFlags, IllegalStack, IPWhitelist*, LibsDisguises, LimitPillagers, LuckPerms, Multiverse-Core, NotTooExpensive*, PacketLimiter, PlaceholderAPI, ProtocolLib, RandomTeleport, RestrictedCreative, SAML, ShopChest, SilkTouchSpawners, SkinsRestorer, TAB, TimeVote, Vault, VillagerOptimiser, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags, XRayShield

### Other helpful links:
No

### Paper build number:
[Mon, 23. Mar 2020 13:58:22 SGT INFO] This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[Mon, 23. Mar 2020 13:58:22 SGT INFO] Checking version, please wait...
[Mon, 23. Mar 2020 13:58:25 SGT INFO] Previous version: git-Paper-129 (MC: 1.15.2)

**Comment by maityyy** [comment]
My friends have the same problem.
https://timings.aikar.co/?id=06ae168f892d450795fcb34137d4274b#timings

**Comment by PonyPC** [comment]
Have same problem

**Comment by yurinogueira** [comment]
Have same problem

**Comment by KarlPro123** [comment]
Confirming, we also have major Packet Processing lag, specially PlayInPositionLook. Here's our timings https://timings.aikar.co/?id=0000442f31274e78863b48597eedf6ed#timings

We aren't sure if this is a paper side issue, however this is a new one, 1-2 weeks ago this wasn't an issue.

**Comment by maityyy** [comment]
Here are a few more reports from my friends.
https://timings.aikar.co/?id=535c73065371484e9e830d0f7b230784
https://timings.aikar.co/?id=b7c4a2f77dcf4c4b96b48b67a0b93395

**Comment by electronicboy** [comment]
well known issue, there is a PR in the queue to address some of this
#2970

**Comment by LabodiDavid** [comment]
For everyone experiencing this in the future there is a temporary solution: 
Using [Aikar's flags (Described here)](https://aikar.co/mcflags.html) for starting up the server jar.
`-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true`
I experienced this while developing a plugin on 1.18.2 with java 17 and currently this seems like solved the problem for me.
