### ISSUE TITLE
Garbled characters when using non-ASCII characters in the MOTD

### ISSUE THREAD

**Issue by luuk00000000000000000000000000000000000** [PaperMC/Paper#3064]
### What behaviour is expected:
To see non-ASCII characters show up in the MOTD

### What behaviour is observed:
A bunch of garbled characters in the MOTD
![Naamloos](https://user-images.githubusercontent.com/34450360/77417367-2974fa00-6dbd-11ea-8b82-7dd87cc2a88c.png)

### Steps/models to reproduce:
1. Enter any non-ASCII character in the `motd` config line in `server.properties`
2. Start server
3. Go to server list in the client

### Plugin list:
I have two plugins installed:
 - [Chairs](https://dev.bukkit.org/projects/chairsreloaded)
 - [SinglePlayerSleep](https://www.spigotmc.org/resources/single-player-sleep.68139)

### Paper build number:
```
[11:53:30 INFO]: This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[11:53:30 INFO]: Checking version, please wait...
[11:53:30 INFO]: Previous version: git-Paper-136 (MC: 1.15.2)
[11:53:30 INFO]: You are running the latest version
```

### Anything else:
I found [this](https://bugs.mojang.com/browse/MC-2215) Mojang bug report, but it seems that Mojang still didn't do anything with it, so I am turning to you guys.

**Comment by luuk00000000000000000000000000000000000** [comment]
It seems to work fine when you encode your text to unicode escapes and enter those in your motd string, so I'm guessing that the server doesn't convert them correctly

**Comment by HauserGrim** [comment]
Convert: http://www.itpro.cz/juniconv/

**Comment by electronicboy** [comment]
this is a java limitation, newer versions of java support unicode in property files
