### ISSUE TITLE
Memory leak? Ticklist? I do not really understand this.

### ISSUE THREAD

**Issue by HauserGrim** [PaperMC/Paper#3065]
###  Timings or Profile link:
I lost the link to the timings when filling the memory, but it’s clear that the server just started to lag when memory was full.

### Description of issue:
After several hours of playing with 5-8 players, the 2 GB rams fill up almost completely. Even if all players exit, then the used memory is several times larger than after restart.
Below is a link to heap dump.

### Plugin list:
Plugins (54): AnBot*, ASTime, AuthMe, AutoMessage*, AutoSaveWorld*, Chairs, ChatGuard*, Chunkmaster, Citizens, DeluxeMenus, DeluxeTags, DisableWindowItems, dtlTraders, DungeonsXL, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, ExtendViewDistance, FastHarvest, FishFix, Guilds, HolographicDisplays, IllegalStack, LibsDisguises, LuckPerms, Matrix, MobSpawnLimit, MythicMobs, NametagEdit*, NicksFilter*, NoCollisionSpawner, NoCreativePhantoms, PandaWire, PlaceholderAPI, ProtocolLib, RecipeManager, SaveTheCoral, ServerListPlus*, SkinsRestorer*, Soulbound*, StackMob, StackMobBridge, TitleManager, TradePlus, UltimateTimber, Vault, VillagerOptimiser, WGExtender, WGFixer*, WorldEdit, WorldGuard, WorldGuardExtraFlags, XuanCatAPI
Some of them are forks, updated for the new version.

### bukkit.yml, spigot.yml, paper.yml, server.properties
paper.yml: https://pastebin.com/c6sZt4kH
spigot.yml: https://pastebin.com/gztTRs1H
bukkit.yml: https://pastebin.com/7Smnw2Qy
server.properties: https://pastebin.com/0Exq7x7i

### Other helpful links
Heap dump: https://drive.google.com/open?id=1EkSUs_9XWLTZtRf17zA6YZFmJ6__eBz3

### Paper build number:
This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-137 (MC: 1.15.2)

**Comment by HauserGrim** [comment]
A couple of screenshots, I don’t know if they will be useful.
![Снимок экрана (156)](https://user-images.githubusercontent.com/37507220/77433440-0d3a8280-6de8-11ea-9e03-26920c8fcaea.png)
![Снимок экрана (154)](https://user-images.githubusercontent.com/37507220/77433449-0f044600-6de8-11ea-9c04-a1117503fc7f.png)

**Comment by DmitryRendov** [comment]
143 is a bit laggy for me as well. downgraded to 137.

**Comment by Spottedleaf** [comment]
The ticklists are retaining a lot of data in long scheduled - because their target tick time is far greater than the current tick. They existed in a chunk at one point but were removed - the remove logic however does not remove from long scheduled.
Current tick is 643291743, first entry in long scheduled is at tick 643319334, last entry in long scheduled is at tick 2147399438... 

So there's two problems: not removing from long scheduled, and the excessive delay for those tick entries.

**Comment by HauserGrim** [comment]
> 143 is a bit laggy for me as well. downgraded to 137.

I'll try, thanks for the advice.


> The ticklists are retaining a lot of data in long scheduled - because their target tick time is far greater than the current tick. They existed in a chunk at one point but were removed - the remove logic however does not remove from long scheduled.
> Current tick is 643291743, first entry in long scheduled is at tick 643319334, last entry in long scheduled is at tick 2147399438...
> 
> So there's two problems: not removing from long scheduled, and the excessive delay for those tick entries.

I understood almost nothing :D

**Comment by jere62smi** [comment]
I have exactly the same problem with more than 100 players, I have reached a critical stage, it becomes urgent that paper corrects RAM problem! We urgently need an update!

**Comment by perseus5** [comment]
I'm also having memory issues after updating

**Comment by SrBedrock** [comment]
I believe there is a memory leak but I can't analyze the dumb heap due to its size

![image](https://user-images.githubusercontent.com/51332006/77567242-9fed2700-6ea5-11ea-876a-d568e02fe26e.png)

Usually with the same amount of players the heap never exceeds 3GB

**Comment by HexedHero** [comment]
Weirdly enough, I'm not having these issues and my heaps are normal just as before the update

**Comment by MiniDigger** [comment]
#3068

**Comment by HauserGrim** [comment]
Check out the new build tomorrow. If there are no problems, I will close issue.

**Comment by jere62smi** [comment]
For me the problem is still present, the ram seems to go up less quickly but that does not correct the problem. Why does the RAM fail to go down even when there is no one left on the server?

**Comment by HauserGrim** [comment]
> For me the problem is still present, the ram seems to go up less quickly but that does not correct the problem. Why does the RAM fail to go down even when there is no one left on the server?

Try create "/paper dump" when nobody will be on the server and tell me its file size.

**Comment by HauserGrim** [comment]
There is no longer a leak with the ticklist, but I noticed that there is another leak, which I can’t determine due to the small online on my server.
I hope someone with a large number of players creates issue.

**Comment by MagmaSlime123** [comment]
@HauserGrim 

I'd recommend using Tuinity, a fork of Paper optimized for large player counts.
