### ISSUE TITLE
Add features to alert commands

### ISSUE THREAD

**Issue by leoncp9** [PaperMC/Paper#3066]
Hi can you add the options for remove the prefix in the /alert command by waterfall proxy?
\u00a7h
In game i can use &h before all text for remove the prefix, but in the messages.properties file of Waterfall.jar i can't set the code \u00a7h
so is possible set the code &h for remove the prefix in /alert ?
Thank

**Comment by MiniDigger** [comment]
please file this issue on the waterfall repo.
this is the paper repo.

**Comment by leoncp9** [comment]
ok thank
