### ISSUE TITLE
Mobs in teams attack the wrong person

### ISSUE THREAD

**Issue by RGFTheCoder** [PaperMC/Paper#3067]
### What behavior is expected:
When you create a team and add yourself and mobs to it, the mobs won't attack you.

### What behaviour is observed:
Even when being in the same team, all mobs attack you.

### Steps/models to reproduce:
`/team add red`
`/team join red @s`
spawn a zombie.
`/team join red @e[type=minecraft:zombie]`
switch to survival mode.
The zombie still attacks you.

### Plugin list:
CleanroomGenerator
dynmap
EssentialsX (only core jar)
ItemEditor
LuckPerms
Multiverse-Core
VeinMiner
worldedit

### Paper build number:
This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
I already tried removing essentials as it feels to be the only plugin that would mess this up.

**Comment by wizjany** [comment]
https://paper.readthedocs.io/en/latest/server/configuration.html#allow-non-player-entities-on-scoreboards

**Comment by RGFTheCoder** [comment]
Thank you. :)
