### ISSUE TITLE
Snow random tick has incorrect behavior

### ISSUE THREAD

**Issue by KernelFreeze** [PaperMC/Paper#3069]
### What behavior is expected:
Vanilla behavior:
![vanilla](https://i.imgur.com/fkm8GIg.png)

### What behavior is observed:
Paper (Notice the snow under blocks)
![paper](https://i.imgur.com/xKkFkqV.png)

### Steps/models to reproduce:
Put a layer of blocks in a snow biome, start a storm and wait

### Plugin list:
FastChunkPregenerator

### Paper build number:
Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
I think this is related with #2914

**Comment by AJMFactsheets** [comment]
Could not reproduce with build 143. Are you able to reproduce with no plugins?

**Comment by KernelFreeze** [comment]
Now I can't reproduce with the same conditions in the same server, it's very weird, like it's quantum or something
