### ISSUE TITLE
Possible to configure chat / command & tab-complete disconnect.spam throttle?

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#307]
Is it possible to be able to configure the disconnect.spam built-in protection for chat / command & tab-complete packets? So it can be reduced to be less restrictive or disabled entirely? 

In my case, I've had a few complaints from staff being kicked for disconnect.spam when looking up a bunch of logs quickly.

**Comment by Black-Hole** [comment]
You could use "spam-exclusions" in spigot.yml for your log commands.

**Comment by mibby** [comment]
Isn't that case sensitive though? As in if I added `/lb`, it wouldn't for example cover all cases of `/lb page #`?

**Comment by zachbr** [comment]
I believe that is covered, as it's just checking if the string (command) starts with your exclusion. So long as they're using `/lb`, `/lb blahblah` and `/lb BLAHblah` should be covered.
