### ISSUE TITLE
PlayerInteractEntityEvent causes server exception when canceled for EnderDragon/EnderDragonPart

### ISSUE THREAD

**Issue by drunderscore** [PaperMC/Paper#3070]
### Link/paste of stack trace
https://pastebin.com/ZgunHXmz

### Plugin list:
SpigotInteractBug, sourcecode can be found [here](https://gist.github.com/drunderscore/6d7f9042533af2327115708a346a55a0), or a direct download [here](https://github.com/PaperMC/Paper/files/4384648/SpigotInteractBug-1.0-container.zip)

### Actions to reproduce (if known):
Simply interact with the ender dragon, in any dimension (ex, by right clicking), and the above exception will be thrown. Most likely caused by some obscure bug when handling complex entities/complex entity parts, of which the ender dragon is the only one of it's kind. Additionally, `Entity#getType` on `PlayerInteractEntityEvent#getRightClicked` will return `UNKNOWN`, which isn't correct (however, this also occurs on Spigot, whereas the above exception does not). Even more additionally, the event is called twice (for the same entity), whereas the exception occurs once.

### Paper build number:
Paper-144
`git-Paper-144 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**Comment by Trigary** [comment]
The exception appears twice for me (the interact event also gets fired twice). So can confirm that this issue exists, I am on git-Paper-162. Issue is not present on latest Spigot (git-Spigot-a03b1fd-5838285). Present in git-Paper-63 as well, the first 1.15.2 Paper release.

**Comment by Trigary** [comment]
Is this issue present on latest? (221 and above)

**Comment by drunderscore** [comment]
Still present in 221

`git-Paper-221 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

https://pastebin.com/Ac603Mn3 (shows both the broadcast message and the exception twice)

**Comment by aikar** [comment]
build 223
