### ISSUE TITLE
Server Keeps laging & crash's on /nuke command never happened before

### ISSUE THREAD

**Issue by Veltabex** [PaperMC/Paper#3073]
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:581)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:484)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:613)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1387)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:860)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:887)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:773)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:612)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1028)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1366)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1703)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
27.03 22:49:50 [Server] INFO [22:49:50 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849)
27.03 22:49:52 [FMCS] Skipped 4 lines due to rate limit (30/s)
27.03 22:49:52 [Server] INFO [22:49:52 INFO]: Opped xx_veltabex_xx
27.03 22:50:06 [Server] INFO [22:50:06 INFO]: [Xx_Veltabex_xX: Opped babeblu]
27.03 22:50:11 [Server] INFO [22:50:11 WARN]: [AntiBotUltra] Task #372 for AntiBotUltra v7.1 generated an exception
27.03 22:50:11 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
27.03 22:50:11 [Server] INFO at ittrio.antibotultra.light.source.AutoWhite$1.run(AutoWhite.java:32) ~[?:?]
27.03 22:50:11 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[paper-1.12.2.jar:git-Paper-1490]
27.03 22:50:11 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [paper-1.12.2.jar:git-Paper-1490]
27.03 22:50:11 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839) [paper-1.12.2.jar:git-Paper-1490]
27.03 22:50:11 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [paper-1.12.2.jar:git-Paper-1490]
27.03 22:50:11 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [paper-1.12.2.jar:git-Paper-1490]
27.03 22:50:11 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paper-1.12.2.jar:git-Paper-1490]
27.03 22:50:11 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
27.03 22:50:14 [Server] INFO [22:50:14 INFO]: (0) [Warrior] babeblu > the fuck
27.03 22:50:18 [Server] INFO [22:50:18 INFO]: [BuycraftX] Fetching all due players...
27.03 22:50:18 [Server] INFO [22:50:18 INFO]: [BuycraftX] Fetched due players (0 found).
27.03 22:50:18 [Server] INFO [22:50:18 INFO]: **Nigger(0) [Warrior] Xx_Veltabex_xX > t
27.03 22:50:27 [Server] INFO [22:50:27 INFO]: There are 2 out of maximum 49 players online.
27.03 22:50:27 [Server] INFO [22:50:27 WARN]: [Essentials] Permissions lag notice with (ModernVaultHandler). Response took 119,675925ms. Summary: Getting prefix for babeblu
27.03 22:50:27 [Server] INFO [22:50:27 INFO]: default: [Warrior]babeblu, [Warrior]Xx_Veltabex_xX
27.03 22:50:31 [Server] INFO [22:50:31 INFO]: [LP] LOG > (babeblu) [U] (babeblu)
27.03 22:50:31 [Server] INFO [22:50:31 INFO]: [LP] LOG > parent add co-owner
27.03 22:50:33 [Server] INFO [22:50:33 INFO]: (0) [Co-owner] babeblu > hellok
27.03 22:50:46 [Server] INFO [22:50:46 INFO]: [LP] LOG > (babeblu) [U] (xx_veltabex_xx)
27.03 22:50:46 [Server] INFO [22:50:46 INFO]: [LP] LOG > parent add owner
27.03 22:50:49 [Server] INFO [22:50:49 WARN]: [Essentials] Permissions lag notice with (ModernVaultHandler). Response took 64,340118ms. Summary: Getting suffix for Xx_Veltabex_xX
27.03 22:50:49 [Server] INFO [22:50:49 INFO]: **Nigger(0) [ Owner ] Xx_Veltabex_xX > t
27.03 22:50:50 [Server] INFO [22:50:50 INFO]: (0) [Co-owner] babeblu > type something
27.03 22:51:25 [Server] INFO [22:51:25 INFO]: (0) [Co-owner] babeblu > asd
27.03 22:51:26 [Server] INFO [22:51:26 INFO]: **Nigger(0) [ Owner ] Xx_Veltabex_xX > t
27.03 22:51:29 [Server] INFO [22:51:29 INFO]: (0) [Co-owner] babeblu > asd
27.03 22:51:32 [Server] INFO [22:51:32 INFO]: **Nigger(0) [ Owner ] Xx_Veltabex_xX > tt
27.03 22:51:40 [Server] INFO [22:51:40 INFO]: (0) [Co-owner] babeblu > asd
27.03 22:51:40 [Server] INFO [22:51:40 INFO]: (0) [Co-owner] babeblu > asd
27.03 22:51:41 [Server] INFO [22:51:41 INFO]: (0) [Co-owner] babeblu > asd
27.03 22:51:42 [Server] INFO [22:51:42 INFO]: (0) [Co-owner] babeblu > asd
27.03 22:51:56 [Server] INFO [22:51:56 INFO]: **Nigger(0) [ Owner ] Xx_Veltabex_xX > t
27.03 22:52:01 [Server] INFO [22:52:01 INFO]: (0) [Co-owner] babeblu > type something in the chat
27.03 22:52:09 [Server] INFO [22:52:09 INFO]: (0) [Co-owner] babeblu > alex is a stupid nigger
27.03 22:52:10 [Server] INFO [22:52:10 INFO]: **Nigger(0) [ Owner ] Xx_Veltabex_xX > y
27.03 22:52:13 [FMCS] Loading server properties
27.03 22:52:18 [Server] INFO [22:52:18 INFO]: (0) [Co-owner] babeblu > asd
27.03 22:52:18 [Server] INFO [22:52:18 INFO]: **Nigger(0) [ Owner ] Xx_Veltabex_xX > t
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: The server has stopped responding!
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: Please report this to https://github.com/PaperMC/Paper/issues
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: Paper version: git-Paper-1490 (MC: 1.12.2)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: ------------------------------
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: ------------------------------
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: Current Thread: Server thread
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 	PID: 17 | Suspended: false | Native: false | State: RUNNABLE
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 	Stack:
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		net.minecraft.server.v1_12_R1.StructureGenerator.populateStructure(StructureGenerator.java:226)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		net.minecraft.server.v1_12_R1.StructureGenerator.populateStructure(StructureGenerator.java:217)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		net.minecraft.server.v1_12_R1.StructureGenerator.a(StructureGenerator.java:34)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		net.minecraft.server.v1_12_R1.WorldGenBase.a(SourceFile:34)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		net.minecraft.server.v1_12_R1.ChunkProviderGenerate.getOrCreateChunk(ChunkProviderGenerate.java:173)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		org.bukkit.craftbukkit.v1_12_R1.generator.NormalChunkGenerator.getOrCreateChunk(NormalChunkGenerator.java:36)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		co.aikar.timings.TimedChunkGenerator.getOrCreateChunk(TimedChunkGenerator.java:93)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:194)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:174)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:181)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:118)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:618)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		org.bukkit.Location.getBlock(Location.java:100)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		net.hydrotekz.BlowableObsidians.listeners.Listener.onBoom(Listener.java:67)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		net.hydrotekz.BlowableObsidians.listeners.Listener.onBlockExplode(Listener.java:39)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor236.execute(Unknown Source)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
27.03 22:52:20 [Server] INFO [22:52:20 ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
27.03 22:52:22 [FMCS] Auto-saving world...
27.03 22:52:25 [FMCS] Skipped 932 lines due to rate limit (30/s)
27.03 22:52:25 [Server] INFO [22:52:25 INFO]: (0) [Co-owner] babeblu > asd
27.03 22:52:30 [Server] INFO [22:52:30 INFO]: (0) [Co-owner] babeblu > asd
27.03 22:52:42 [Server] INFO [22:52:42 INFO]: (0) [Co-owner] babeblu > asd
27.03 22:52:42 [Server] INFO [22:52:42 INFO]: Stopping server
27.03 22:54:41 [Server] INFO [22:54:41 INFO]: Negative index in crash report handler (32/49)
27.03 22:54:57 [FMCS] Loading server properties
27.03 22:55:52 [Server] INFO [22:55:52 INFO]: Negative index in crash report handler (32/49)
27.03 22:55:52 [Server] INFO [22:55:52 INFO]: [TAB] Disabled in 2ms
27.03 22:58:03 [FMCS] Loading server properties
27.03 22:59:04 [Server] INFO [22:59:03 INFO]: Negative index in crash report handler (0/49)
27.03 22:59:04 [Server] INFO [22:59:04 INFO]: [MobHunting] Closing database connection.
27.03 22:59:04 [Server] INFO [22:59:04 INFO]: [MobHunting] MobHunting disabled.
27.03 23:00:05 [FMCS] Received stop command
27.03 23:00:05 [FMCS] Stopping server!
27.03 23:00:37 [FMCS] Terminating server via signal
27.03 23:00:38 [FMCS] Forcefully killing server
27.03 23:00:39 [FMCS] Failed to kill server! (PID: 26262) Please try to end it manually.
27.03 23:00:40 [FMCS] Server stopped
27.03 23:00:40 [Disconnect] User [22:45:27 INFO]: babeblu has disconnected, reason: Server shutting down
27.03 23:00:40 [Disconnect] User [22:45:26 INFO]: babeblu lost connection: You has disconnected, reason: Server shutting down
27.03 23:00:40 [Disconnect] User [22:45:26 INFO]: babeblu has disconnected, reason: Server shutting down
27.03 23:00:40 [Disconnect] User [22:47:25 INFO]: babeblu has disconnected, reason: Server shutting down
27.03 23:01:09 [FMCS] Loading server properties

**Comment by electronicboy** [comment]
1.12.2 is no longer supported
