### ISSUE TITLE
Method Chunk#getEntities() returns entities that are not appearing in the world

### ISSUE THREAD

**Issue by i0xHeX** [PaperMC/Paper#3075]
I have custom own plugin to balance mob cap, and the main thing it do is listen to `CreatureSpawnEvent` and cancels them, when monsters near the player (or other type) are reached limit. It basically checks entities of each chunk around the player and sum them. 

Issues detected on enderman farm (common design). 

### What behaviour is expected:
Every time any player joins the farm endermans should spawn (and be visible) up to limit, which plugin controls, based on right `Chunk#getEntities()` result.

### What behaviour is observed:
In some case when you join farm - no endermans exists (as seen from client side) and no more spawning. Plugin debug shows, that there are already 70 monsters around, but actually there is only one endermite, from client side and from `/paper entity list` command. Plugin debug uses method below:
https://pastebin.com/B221pwkX

This is plugin debug:
https://i.imgur.com/NQhYs2M.png

This is paper result:
https://i.imgur.com/oCGU6LP.png

### Steps/models to reproduce:

- Player A joins the farm
- Player A leaves the game (+ Wait 15s for chunk unload)
- Player A joins the game (endermans still near)
- Player A leaves the game (+ Wait 15s for chunk unload)
- Player B joins the farm (and no endermans near, no more spawning)

### Plugin list:
Auth, CoreProtect, EasyBackup, HideLog, LuckPerms, MicroTools, MobCapBalancer*, Plan, PlugMan, ProtocolLib, RFChairs, ServerRestart, SkinsRestorer, spark, Spartan, WhitelistPlayers*

### Paper build number:
git-Paper-145 (MC: 1.15.2)

### Anything else:
I suspect something going wrong with carrying entities inside chunk slices that leads to wrong `Chunk#getEntities()` result. There are no plugins which change entity mechanics. MobCapBalancer only monitors entity count and cancels spawn event.

**Comment by aurorasmiles** [comment]
We have a similar problem
https://waste.cutiepie.at/vfmbkikqa9l179ld
And, it's not only chunk#getEntities but also world#getEntities for us. Only the WorldEdit API returns a correct number

**Comment by aikar** [comment]
This is fixed in latest builds, please let us know if you still see issues and provide new reproduce examples.
