### ISSUE TITLE
Minecraft::world - syncChunkLoad lag

### ISSUE THREAD

**Issue by colo13verdadeo** [PaperMC/Paper#3078]
Timings:
https://timings.spigotmc.org/?url=muraqiduro
&
https://timings.spigotmc.org/?url=qokiliviyi
### Plugin list:
https://imgur.com/a/8EtzLXD

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___

Is server SPIGOT

### spigot
This is a final build for 1.12.2. Please see(...)

**Comment by Redned235** [comment]
> Timings:
> https://timings.spigotmc.org/?url=muraqiduro
> &
> https://timings.spigotmc.org/?url=qokiliviyi
> 
> ### Plugin list:
> https://imgur.com/a/8EtzLXD
> 
> ### bukkit.yml, spigot.yml, paper.yml, server.properties
> _**Gist/pastebin/hastebin links**_
> 
> Is server SPIGOT
> 
> ### spigot
> This is a final build for 1.12.2. Please see(...)

This is the Paper issue tracker, not Spigot.
