### ISSUE TITLE
Unsupported Java detected (59.0). Only up to Java 14 is supported.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#3079]
Can Java 15 be added preliminarily to the supported list so it can be started up for testing? :) 

```
Unsupported Java detected (59.0). Only up to Java 14 is supported.
```

**Comment by zachbr** [comment]
We added an override flag to avoid having to constantly bump this.
`-DPaper.IgnoreJavaVersion=true`

**Comment by mibby** [comment]
Ah, nice. Thanks. :)
