### ISSUE TITLE
Corrupt chunks

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#308]
# Incompatibility (Bug)
### What behaviour is expected:

**_Chunks should work like in vanilla minecraft.**_
### What behaviour is observed:

Players reported that they have to fight with issues in some chunks:
- Freezing Mobs
- No item drop after breaking blocks
- Fishing Rod doesn't work 

Screenshot: http://i.imgur.com/f6tkaw3.png

Players said that it looks like that "the chunks are getting unloaded". Maybe this issue gets caused by one of the last commits for the chunk saving? 
### Steps/models to reproduce:

**_Not known.**_
### Plugin list:

**_Not needed.**_
### Paper build number:

**_745**_

**Comment by zachbr** [comment]
You need to attach the affected regions to this ticket so that we can start investigating.

**Comment by sgdc3** [comment]
Having the same issue on latest 1.8 build. I made a little plugin that reloads the chunks in a specified radius, but a definitive fix would be amazing.

**Comment by sgdc3** [comment]
If you teleport outside of that chunk you can see the blocks but everything is freezed, but if you teleport inside of the glitched chunk the client gets stuck falling on the void like in an unloaded chunk.

**Comment by sgdc3** [comment]
Idk of this is the same issue but the effects are the same.

**Comment by ghost** [comment]
@Zbob750 You want the region files of the world? Then I will try to get some with corrupted chunks.

**Comment by Platinteufel** [comment]
So this is a 1.9.4 issue? I don't have any problems (1.9.2), paper 724

**Comment by zachbr** [comment]
As far as we know, this remains isolated to a few users. The information we've received has not been detailed enough to reproduce or test properly on our end (not that things are always easy anyway, especially if this is random).

**Comment by Platinteufel** [comment]
But it seems like there are a few chunk issues in 1.9.4 like #284 or #303. I'm not sure if I should update to 1.9.4 yet. :/

**Comment by zachbr** [comment]
Make a backup and test it. Not everyone will see every issue. It's one of the things that makes it difficult for us. If you run into an issue, let us know, maybe your information will be able to help.

**Comment by ghost** [comment]
We now have multiple chunk errors... (build 761)
- Lightning errors
- Unloaded chunks
- Deleted chunks

Used https://dinnerbone.com/minecraft/tools/coordinates/ to find the chunk files, I hope it worked.

Deleted chunks: 
http://i.imgur.com/5039xh9.jpg
http://download.sparty.io/chunks/r.22.6.mca

Lightning errors (if you place light sources, it fixed the problem until you walk out of the rage, then these chunks reset them self to the dark lightning)
http://i.imgur.com/vzTn12b.png
http://download.sparty.io/chunks/r.-1.-1.mca

Unloaded chunks:
Will be added later.

**Comment by ghost** [comment]
Still have to fight chunks which get deleted...

Any news for this issue?

**Comment by ghost** [comment]
More and more chunks are disappearing from my maps. Nothing we can do about it?

**Comment by zachbr** [comment]
We need your plugin list. There are multiple plugins that can cause this. As of now I remain unconvinced this is an issue inherent in Paper.

**Comment by Black-Hole** [comment]
Timings might also show which plugin is unloading chunks forcefully.

**Comment by ghost** [comment]
Plugins which handle chunks:
- AutoSaveWorld
- ChunkSpawnerLimiter
- ASkyblock
- Dynmap

All other plugins never touch chunk loading/saving.

**Comment by Black-Hole** [comment]
ASkyblock is calling Chunk.unload(), you could try a fork where you remove those calls:
https://github.com/tastybento/askyblock/search?utf8=%E2%9C%93&q=unload

**Comment by Platinteufel** [comment]
Maybe interesting too:
https://hub.spigotmc.org/jira/browse/SPIGOT-2385

**Comment by zachbr** [comment]
Closing as duplicate, of the now resolved, [SPIGOT-2322](https://hub.spigotmc.org/jira/browse/SPIGOT-2322)
