### ISSUE TITLE
GetBlockAgainst inconsistency

### ISSUE THREAD

**Issue by LogGits** [PaperMC/Paper#3080]
### What behaviour is expected:
Consistently returning correct `BlockPlaceEvent.getBlockAgainst()`.

### What behaviour is observed:
When a player has high latency or is using Timer hack(I was able to reproduce using 6.67 client timer speed), the server occasionally thinks that the player is placing against the wrong block. In the code below, it blocks placing hoppers against chests. However, when a player has a high timer speed or ping, it occasionally thinks they are placing the hopper against a hopper and places the hopper against the chest regardless. A similar thing happens if I use PlayerInteractEvent with `.getClickedBlock()`.

### Steps/models to reproduce:
1) I used some sort of client timer hack set to `6.67`.
2) I used this code:
```java
@EventHandler (priority = EventPriority.LOWEST)
public void onPlace (BlockPlaceEvent event) {
    Material placed = event.getBlockPlaced().getType();
    Material against = event.getBlockAgainst().getType();
    if (placed == Material.HOPPER) {
        if (against == Material.CHEST) {
            event.setCancelled(true);
        }
    }
    Bukkit.broadcastMessage(event.getBlock().getType().name() + " block, " + placed.name() + " placed against " + against.name() + " cancelled: " + event.isCancelled());
}
```
### Plugin list:
N/A

### Paper build number:
git-Paper-126 (MC: 1.15.2)

**Comment by electronicboy** [comment]
The information used in the event is received directly from the client, there is very little we could do to deal with any oddball state desync issues induced from this, this is something you'd need to take up with mojang

**Comment by LogGits** [comment]
Ok thx @electronicboy
