### ISSUE TITLE
Idea: An option to disable the annoying lagback

### ISSUE THREAD

**Issue by itsTyrion** [PaperMC/Paper#3082]
**Is your feature request related to a problem? Please describe.**
It annoys mo to the death that I keep getting teleported around because I don't have a beefy VPS atm. 
The feature correcting movement when there's too many packets (Probably to patch Timer speed above 1.0f) is a medium annoyance when there's a lag spike and a severe annoyance when there's slight but constant lag to the point where walking becomes almost impossible.

**Describe the solution you'd like**
I'd love to see a config option to raise the packet cap or disable the feature completely. Sure, no one wants cheaters speeding around, but I don't need that for a small survival server with > 5 well known mates. 

**Describe alternatives you've considered**
Downgrading .___.

**Additional context**
example: https://streamable.com/i351a

**Comment by aikar** [comment]
This is already configurable:
spigot.yml
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-threshold: 100.0


make these higher.

**Comment by itsTyrion** [comment]
> This is already configurable:
> spigot.yml
> moved-wrongly-threshold: 0.0625
> moved-too-quickly-threshold: 100.0
> 
> make these higher.

yes and no.. AFAIK that would print "moved wrongly/too quickly" to the console. There's not a single message of this type. And we're not talking massive lag or so, we're talking max. 6 ms tick time and nothing below 19.5 tps. 
Sometimes the setbacks (incl. a (from what I can tell, at least sometimes) random yaw) are triggered by a > 1 block movement (and I already doubled the wrongly-threshold)
