### ISSUE TITLE
Connection timings time out.

### ISSUE THREAD

**Issue by colo13verdadeo** [PaperMC/Paper#3086]
02.04 04:53:31 [Server] ERROR Could not paste timings
02.04 04:53:31 [Server] INFO java.net.ConnectException: Connection timed out: connect
02.04 04:53:31 [Server] INFO at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[?:1.8.0_212-1-ojdkbuild]
02.04 04:53:31 [Server] INFO at co.aikar.timings.TimingsExport.run(TimingsExport.java:293) ~[patched_1.12.2.jar:git-Paper-1618]

IP Blocked?
I remember that only once did he let me use /timings paste

**Comment by aikar** [comment]
Ok, I've fully removed the massive ban I had on virtua.br. hopefully the issues I had with bots won't come back.

**Comment by colo13verdadeo** [comment]
Again blocked :C

You can add bypass my ip?
177.54.148.217

**Comment by colo13verdadeo** [comment]
@aikar

**Comment by aikar** [comment]
That IP is not being blocked on my side.

**Comment by colo13verdadeo** [comment]
So... Why time out :c? @aikar

**Comment by clrxbl** [comment]
Perhaps your host is blocking it

**Comment by colo13verdadeo** [comment]
:c 
Is an dedicado.

**Comment by colo13verdadeo** [comment]
What port use?

**Comment by clrxbl** [comment]
Port doesn't matter, see if you can traceroute the timings server.

**Comment by colo13verdadeo** [comment]
I cant use Timings on server, when use paste or report show error.
