### ISSUE TITLE
Items randomly stopping in waterstreams

### ISSUE THREAD

**Issue by motz0815** [PaperMC/Paper#3087]
### What behaviour is expected:
Items normally running through water/ice lines for transport in redstone systems.

### What behaviour is observed:
Items stopping on the space between two waterstreams.

### Steps/models to reproduce:
With paper version 156, you just need to make a waterstream like to transport with hoppers, but actually water, not hoppers. duh. so, if there are many items in the waterstream, some get caught on the ice blocks with signs or whatever.
![2020-04-02_10 31 46](https://user-images.githubusercontent.com/49114741/78227226-3d131580-74cd-11ea-8f8a-c2046b425864.png)

### Plugin list:
no plugins at the time of the bug.

### Paper build number:
This server is running Paper version git-Paper-156 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
in the paper build 155 the items flow through the waterstreams as normal as ever, the issue came up with build 156.

**Comment by Aurelien30000** [comment]
Update to build 158, seems fixed :)

**Comment by motz0815** [comment]
Okay, when did this build come out? xD Like 5 minutes ago :D but it's good to see it fixed.
