### ISSUE TITLE
Frost walker boots on armor stand don’t freeze water

### ISSUE THREAD

**Issue by lewisflude** [PaperMC/Paper#3088]
### What behaviour is expected:
When an armour stand with frost walker enchanted boots is on water and is pushed with a piston/slime block, the water should freeze.
### What behaviour is observed:
Nothing happens. Additionally, when a mob (zombie etc.) is wearing frost walker boots, the frost walker effect is not applied.
### Steps/models to reproduce:
Place an armor stand above water, and place leather boots with the frost walker enchantment onto it.

### Plugin list:

AdvancedPortals, AreaShop, AutoBroadcast*, Chunkmaster, Coins, CoreProtect, CraftingStore, DiscordSRV, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, Harbor, HolographicDisplays, HolographicPlaceholders, LimitPillagers, LuckPerms, LWC, OpenInv, PlaceholderAPI, PluginConstructorAPI, ProtocolLib, QuickShop, ServerRestorer, Vault, VillagerOptimiser, WDLCompanion*, WorldEdit, WorldGuard

### Paper build number:

git-Paper-149 (MC: 1.15.2)

**Comment by lewisflude** [comment]
Additionally it does not move as expected when pushed with a piston/slime block. Any pointers would be really appreciated! Happy to provide more information if needed.

**Comment by electronicboy** [comment]
paper.yml, `armor-stands-tick` ?
Also, update

**Comment by lewisflude** [comment]
> paper.yml, `armor-stands-tick` ?
> 
> Also, update

Oh yes, I’ll update in a second. I’ve tried armor-stands-tick both true and false, and both give the same result.

**Comment by lewisflude** [comment]
Updating fixed the issue! Thanks for the speedy response. :)

**Comment by Trigary** [comment]
Since the problem luckily got fixed, could you please close this issue? Thanks :)
