### ISSUE TITLE
Server log not showing color codes

### ISSUE THREAD

**Issue by InsaneJ** [PaperMC/Paper#3090]
Using PaperMC 161 I'm not seeing color codes from various plugins and chat in latest.log. I'm not using any kind of custom log4j configuration to alter server logs. The server is started with the -Dfile.encoding=UTF-8 flag set.

Other Minecraft servers work as expected. See screenshot below for a comparison between a KCauldron (1.7.10) and PaperMC 161 with cross server chat enabled.

My server is running Ubuntu 18.04. Output of "uname -a"
Linux athrun 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

![papermc_not_showing_colors_in_log](https://user-images.githubusercontent.com/1933471/78408074-7d29e380-7606-11ea-838a-21bdea1c9b7c.png)

**Comment by electronicboy** [comment]
this is intentional behavior, text files are text files, there is very little sane reason to throw ansi escape characters into them
You might be able to use a custom log4j config to restore this behavior by removing the strip, but, untested, etc


------
![image](https://user-images.githubusercontent.com/1228900/78409038-a0519480-7600-11ea-80f0-8ed6074386e0.png)
because I have no idea why I opted to test this,

```xml
        <RollingRandomAccessFile name="File" fileName="logs/latest.log" filePattern="logs/%d{yyyy-MM-dd}-%i.log.gz">
            <PatternLayout>
                <LoggerNamePatternSelector defaultPattern="%highlightError{[%d{HH:mm:ss}] [%t/%level]: [%logger] %minecraftFormatting{%msg}%n}">
                    <!-- Log root, Minecraft, Mojang and Bukkit loggers without prefix -->
                    <!-- Disable prefix for various plugins that bypass the plugin logger -->
                    <PatternMatch key=",net.minecraft.,Minecraft,com.mojang.,com.sk89q.,ru.tehkode.,Minecraft.AWE"
                                  pattern="%highlightError{[%d{HH:mm:ss}] [%t/%level]: %minecraftFormatting{%msg}%n}" />
                </LoggerNamePatternSelector>
            </PatternLayout>
            <Policies>
                <TimeBasedTriggeringPolicy />
                <OnStartupTriggeringPolicy />
            </Policies>
            <DefaultRolloverStrategy max="1000"/>
        </RollingRandomAccessFile>
```

**Comment by InsaneJ** [comment]
We have been using this feature for many years to facilitate cross-server chat between many different Minecraft versions. The problem there is that there aren't any plugins that support all Minecraft versions. Old ones are no longer supported, new ones pop up, etc. So we made some bash scripts that could tail the server logs and post global chat messages between them.

Thank you for posting the log4j configuration. Though would it be possible to make this color-striped log a toggle-able feature? Default on, and with an option to bring the colors back?

**Comment by wizjany** [comment]
toggleable by adding `-Dlog4j.configurationFile=path/to/custom/log4j.xml` to your startup flags already :^)

**Comment by InsaneJ** [comment]
That's not really the same though. It depends on the custom config staying relevant and the log system not being altered any further.

@electronicboy said there's very little sane reason to throw ansi escape codes into the log files. Well turns out that there's a very good reason. Our cross server chat supports everything from Beta Minecraft on Bukkit, through MCPC+, Sponge, Spigot, KCauldron and Vanilla Minecraft. But with Paper it breaks down. We could work around it if we really wanted to by comparing the un-colored output with permission files and figure out what colors to add to certain things. But it would make more sense for us to just go back to Spigot at that point, which would be a shame.
