### ISSUE TITLE
Server crash possibly caused by an entity

### ISSUE THREAD

**Issue by JTHicks26** [PaperMC/Paper#3091]
### Plugin list:
BetterChairs
CraftPlus
EssentialsX + EssentialsXChat
Harbor
ImageOnMap
InventoryRollback
LibsDisguises
LuckPerms
ProtocolLib
Sudo
TreeAssist
Vault
WorldEdit

### Actions to reproduce (if known):
Unable to reproduce. Crash happens approximately once daily.

### Paper build number:
This server is running Paper version git-Paper-156 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-155 (MC: 1.15.2)

**Comment by electronicboy** [comment]
entity moving too fast; Update, this is already fixed
