### ISSUE TITLE
Server start stop responding after update to 161

### ISSUE THREAD

**Issue by sandtechnology** [PaperMC/Paper#3096]
### Link/paste of stack trace
https://paste.ubuntu.com/p/BrJcC3CBD2/

### Plugin list:
AlwaysKeepInventory*, AsyncWorldEdit, BungeeConsoleChat*, BungeeTabListPlus, ChunksExplorerLimiter,LWC, LWCTrust, Matrix, MobSpawnLimit, NyaaCore, Oh_the_dungeons_youll_go, PlaceholderAPI, PlayerListGUI, PlayerSQL, PlayReward,TimeIsMoney*, TitleManager, TrMenu, Universes, Vault, VillagerOptimiser, WoodCutter, WorldBorder, WorldEdit, WorldEditSUI, yasui
### Paper build number: 161

Downgrade to 158 seems fix this problem, but I don't know what caused it

**Comment by Spottedleaf** [comment]
As suggested on discord: move the die() call to .dead = true
This should be the proper code fix
