### ISSUE TITLE
Server Crash | 1.15.2

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3097]
### Link/paste of stack trace

Log: https://pastebin.com/VtYtq7Mh

### Plugin list:
AdvancedBan*, AntiAFKPro*, AutoBroadcast, BuycraftX, CoreProtect, DiscordSRV, dynmap*, Dynmap-Towny, GlobeMC-Environment, GMC-Custom, GMC-Essentials, Hue, LuckPerms, mcMMO, Orebfuscator4, PiggyBank, PlaceholderAPI, PlayerRanks*, PluginHiderPlus*, PlugMan, ProtocolLib, SimpleCombatTag*, Spartan, StaffPlus, SuperbVote, Towny, TownyChat, TownyNameUpdater, Vault, Votifier, WorldBorder

### Actions to reproduce (if known):
I am unsure. I believe it is from a player loading a certain chunk?

### Paper build number:
This server is running Paper version git-Paper-161 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by ninja-** [comment]
this is caused by Orebfuscator

**Comment by ghost** [comment]
This was not the solution. I removed Orebfuscator and after an hour, this happened again.

https://pastebin.com/WLNW2em2

**Comment by Black-Hole** [comment]
Plugin issue. Caused by whatever plugin is using the class  com.thedaviski.join.listeners.PlayerListener
