### ISSUE TITLE
Enhance default value handling in ConfigurationSection

### ISSUE THREAD

**Issue by schmerm** [PaperMC/Paper#3098]
The get* family of methods (like getInt(key, def) in ConfigurationSection currently:
1) Return the value for 'key' if 'key' is defined
2) Return the default value 'def' if 'key' is not defined

However, I do not think that they modify the underlying ConfigurationSection.
It would be nice if there was a capability to ALSO, in addition to 1) and 2), do:
3) If 'key' was not defined in the ConfigurationSection, define it and set it as the default value.

This would be very similar to a Python dict's 'setdefault', except I think that name is already taken/ambiguous within ConfigurationSections.

There are of course ways to do all this functionality with multiple calls to different methods, but they all require the magic string for 'key' to be consistent, which usually leads to it being made a final static String constant somewhere. Having a one-stop-shop method to do it all would allow 'key' to only have to ever be specified once.

**Comment by aikar** [comment]
This is already possible. config.setDefaults(otherConfig)

Please see Bukkit API examples for more information on this, and I believe bukkit even automatically does it on your primary config where it does something like .copyDefaults() and then ->save()

Will need to google for examples, but this behavior def exists.
