### ISSUE TITLE
UserCache crash and server thread gets blocked

### ISSUE THREAD

**Issue by ShirasawaSama** [PaperMC/Paper#3099]
### Link of stack trace

https://paste.ubuntu.com/p/JzmsMG3wmS/

### Plugin list:

- CoreProtect
- dynmap*
- EntityDetection
- Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn
- LuckPerms
- OpenInv
- PlugMan
- WorldEdit

### Actions to reproduce (if known):

Unpredictability, occurs when a player joins the server. Then, the **SERVER THREAD** gets **BLOCKED**.

It looks like a deadlock caused by a `Map`.

### Paper build number:

`git-Paper-158 (MC: 1.15.2)`

**Comment by electronicboy** [comment]
Blocked by mcpanelbackend
