### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by goldenkuky209** [PaperMC/Paper#3107]
Server keeps crashing.

06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.StreamAccumulator$1.tryAdvance(SourceFile:31)
06.04 17:56:05 [Server] ERROR java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.VoxelShapes.a(VoxelShapes.java:178)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.Entity.a(Entity.java:851)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.Entity.a(Entity.java:839)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.Entity.e(Entity.java:808)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.Entity.move(Entity.java:560)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.EntityLiving.e(EntityLiving.java:2209)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2560)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:504)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:28)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.EntityChicken.movementTick(EntityChicken.java:51)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2322)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:702)
06.04 17:56:05 [Server] ERROR net.minecraft.server.v1_14_R1.WorldServer$$Lambda$4014/1521161844.accept(Unknown Source)
06.04 17:56:06 [Multicraft] Skipped 10 lines due to rate limit (30/s)
06.04 17:56:06 [Server] ERROR ------------------------------
06.04 17:56:06 [Server] ERROR The server has stopped responding! This is (probably) not a Paper bug.
06.04 17:56:06 [Server] ERROR If you see a plugin in the Server thread dump below, then please report it to that author
06.04 17:56:06 [Server] ERROR *Especially* if it looks like HTTP or MySQL operations are occurring
06.04 17:56:06 [Server] ERROR If you see a world save or edit, then it means you did far more than your server can handle at once
06.04 17:56:06 [Server] ERROR If this is the case, consider increasing timeout-time in spigot.yml but note that this will replace the crash with LARGE lag spikes
06.04 17:56:06 [Server] ERROR If you are unsure or still think this is a Paper bug, please report this to https://github.com/PaperMC/Paper/issues
06.04 17:56:06 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports
06.04 17:56:06 [Server] ERROR Paper version: git-Paper-239 (MC: 1.14.4)
06.04 17:56:06 [Server] ERROR ------------------------------
06.04 17:56:06 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
06.04 17:56:06 [Server] ERROR The server is waiting on these chunks: []
06.04 17:56:06 [Server] ERROR ------------------------------
06.04 17:56:06 [Server] ERROR Current Thread: Server thread
06.04 17:56:06 [Server] ERROR PID: 32 | Suspended: false | Native: false | State: RUNNABLE
06.04 17:56:06 [Server] ERROR Stack:
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:298)
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:373)
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.IWorldReader$1.tryAdvance(IWorldReader.java:158)
06.04 17:56:06 [Server] ERROR java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.StreamAccumulator$1.tryAdvance(SourceFile:31)
06.04 17:56:06 [Server] ERROR java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.VoxelShapes.a(VoxelShapes.java:178)
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.Entity.a(Entity.java:851)
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.Entity.a(Entity.java:839)
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.Entity.e(Entity.java:808)
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.Entity.move(Entity.java:560)
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.EntityLiving.e(EntityLiving.java:2209)
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2560)
06.04 17:56:06 [Server] ERROR net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:504)
06.04 17:56:09 [Multicraft] Skipped 818 lines due to rate limit (30/s)
06.04 17:56:09 [Server] INFO UUID of player noHacksJustYeet is 018ac154-10c4-406c-839a-ec4a5419f2cd
06.04 17:56:17 [Server] INFO Stopping server
06.04 17:56:18 [Server] INFO 2020-04-06 17:56:18,600 Thread-2 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
06.04 17:56:18 [Server] INFO 2020-04-06 17:56:18,699 Thread-2 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
06.04 17:56:27 [Multicraft] Server shut down (running)
06.04 17:56:27 [Multicraft] Restarting crashed server in 1200 seconds
06.04 17:56:27 [Multicraft] Server stopped

**Comment by aikar** [comment]
Please update to 1.15 to receive support.
