### ISSUE TITLE
ItemMeta#getLore() removing purple colour codes.

### ISSUE THREAD

**Issue by Xemorr** [PaperMC/Paper#3108]
### What behaviour is expected:
___What you expected to see___
The purple colour code in the lore.

### What behaviour is observed:
___What you actually saw___
The purple colour code was removed.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
`ItemMeta itemMeta = Bukkit.getItemFactory().getItemMeta(Material.DIAMOND_SWORD);
        List<String> lore = new ArrayList<>();
        lore.add(ChatColor.translateAlternateColorCodes('&', "fasfdsfsa"));
        lore.add(ChatColor.translateAlternateColorCodes('&', "fasdfsa"));
        lore.add(ChatColor.translateAlternateColorCodes('&', "gfgagsgsg"));
        lore.add(ChatColor.translateAlternateColorCodes('&', "&5&lEnder I"));
        itemMeta.setLore(lore);
        new BukkitRunnable() {
            @Override
            public void run() {
                for (Player player : Bukkit.getOnlinePlayers()) {
                    for (String string : itemMeta.getLore()) {
                        player.sendMessage(string);
                    }
                }
            }
        }.runTaskTimer(this, 50L, 50L);`
^in your on enable.

### Plugin list:
___A list of your plugins___
`Citizens, CrateReloaded, ESBosses, ESChallenges, ESCombat2, ESDimensions, Essentials, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit, Phytomining, ShopGUIPlus, SkyblockNPCs, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard`

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-162 (MC: 1.15.2)

### Anything else:
___Anything else you think may help us resolve the problem___
Look at how getLore() is implemented?

**Comment by suneettipirneni** [comment]
The reason that it's happening is because you're calling `translateAlternateColorCodes()` on the string being passed into the lore, if you want colored text just leave as: "&5&lEnder I".

Eg.

```java
lore.add("&5&lEnder I");
```

**Comment by aikar** [comment]
Seems this is due to how Spigot implemented setLore, but we may be able to fix it.

Disregard the previous comment, it was not correct.

**Comment by Phoenix616** [comment]
Afaik. this is necessary in order to not return a purple string when you add a string without color codes to the lores due how translating to chat components work currently. Changing this without keeping the non-colored strings non-colored on return would break backwards compatibility with plugins that might rely on the exact string getting returned that they added to the lore.

**Comment by Xemorr** [comment]
Firstly, it used to work on 1.13.2 (I just updated from that version) so it must be a relatively new bug, and secondly by default they have &5&o on the items lore, so just remove the &5&o rather than the &5 &o individually? Although to be fair, I haven't seen the implementation, so I might be misunderstanding it.
