### ISSUE TITLE
[ERROR] Illegal PlayerChunkMap::addEntity

### ISSUE THREAD

**Issue by DaveTheCamper** [PaperMC/Paper#3111]
I was using version 147, after update to 162 this issue is spamming my console.

> >.... [23:15:39 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [23:15:39 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world: EntityVindicator['Vindicator'/527667, uuid='d58d41c0-bacb-478c-b960-d81ef5bba69f', l='world', x=1722.50, y=65.00, z=-1424.50, cx=107, cz=-90, tl=0, v=false, d=true]
>.... [23:15:39 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1490)
>.... [23:15:39 WARN]: at sun.reflect.GeneratedMethodAccessor461.invoke(Unknown Source)
>.... [23:15:39 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [23:15:39 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [23:15:39 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
>.... [23:15:39 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
>.... [23:15:39 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
>.... [23:15:39 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [23:15:39 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [23:15:39 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
>.... [23:15:39 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
>.... [23:15:39 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
>.... [23:15:39 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
>.... [23:15:39 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by electronicboy** [comment]
this is an issue with EntityTrackerFixer

**Comment by rayanbzd** [comment]
Fixed here: https://github.com/Esmorall/EntityTrackerFixer/pull/11
