### ISSUE TITLE
A potential problem with entities?

### ISSUE THREAD

**Issue by TheJaake** [PaperMC/Paper#3112]
In the past few days I've been running into quite a few problems with my server freezing up and eventually crashing. These problems started the show up when the userbase created an enderman farm. I'm not too avid in understanding java errors but I can't seem to find any plugin associated with the crash. 

Here is the pastebin:
https://pastebin.com/CDnb7ZrF

Thanks

**Comment by wizjany** [comment]
`DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH`
Your server is severely overloaded.

**Comment by TheJaake** [comment]
But by what? I have used paper for years to run this Minecraft server and have never had a problem similar to this.

**Comment by aikar** [comment]
Based on that pastebin, it's not an issue with entities. your cpu appears to be running extremely slow, and a single tick is taking an enormous amount of time.

Each of those thread dumps are at different locations of the tick process. nothings stuck, just moving really slow.

Consult with your server hosting provider, or if it's your own machine, check on system health.

CPU is likely tanked (overloaded)
