### ISSUE TITLE
[Vanilla bug] Nether portal is not redefined within world border if coordinates are negative.

### ISSUE THREAD

**Issue by HauserGrim** [PaperMC/Paper#3113]
In vanilla, if the portal is generated outside the border, it will be redefined inside the border. Or so it should be.

But if you place the portal on negative coordinates and the generated portal is outside the border, it will not be redefined.

How to reproduce:
Set world border to 10000
Go to nether
Place the portal on ... let's say -2000 90 1500
Go to the portal
The portal in the world will appear on ~ -16000 90 4999. As you can see, the negative coordinate is still outside the border, but the positive has changed to be within the border.

Coordinates of world and nether have a ratio 1:8.

Why fix it? Players teleport far beyond world border they die.

MC ver: 1.15.2

https://bugs.mojang.com/browse/MC-157373

**Comment by HauserGrim** [comment]
https://bugs.mojang.com/browse/MC-157373

**Comment by HauserGrim** [comment]
![image](https://user-images.githubusercontent.com/37507220/80352840-27e79780-887d-11ea-933b-f9d2982cecc8.png)

**Comment by aikar** [comment]
for clarity anyone reading this closed, we just pulled upstream so this is now fixed in latest.
