### ISSUE TITLE
Growth modifier in spigot.yml doesn't work

### ISSUE THREAD

**Issue by didkoti** [PaperMC/Paper#3117]
I tried to change the growth modifiers in spigot.yml but they doesn't seem to work. Nothing changes.

### What behaviour is expected:
Super fast growth

### What behaviour is observed:
Normal growth

### Steps/models to reproduce:
Change the modifiers under growth in spigot.yml. In my case I tried with 500 to check if it would work at all.

### Paper build number:
git-Paper-165 (MC:1.15.2)

**Comment by didkoti** [comment]
I'll quote a person's problem from 6 years ago. It's the same and idk if the problem has been ever fixed.
> I'm using Spigot and trying out a new idea that I've had. I've set the crop growth modifier in my spigot.yml to several different options (1000,10000, and even 100000) and am not getting the results I want. I'd like a situation where wheat will grow in 20 seconds or so.
> 
> The issue I'm having is that, up to around 1000, I can notice faster growth speed, but it is not fast enough for what I would like. Once I go higher than 1000, it seems to revert back to vanilla behavior. Using "/tps" shows that the server is running at 20.

**Comment by Darwin1546** [comment]
I just ran into the same problem

**Comment by chickeneer** [comment]
`if(random.nextInt((int) ((100.0F / modifier) * (25.0F / f)) + 1) == 0)`
That is the formula for the growth modifier's, noting that 100 is default and `(25.0F / f)) + 1` is the vanilla formula.

Helping people read this code statement. The `random.nextInt` returns a random integer from zero to whatever parameter is passed. If that integer is zero. Then the block will grow.

**Comment by chickeneer** [comment]
Accidentally clicked the wrong button. Sorry about that.

I am looking in the code, and the formula modifications appear to look right. What plants did you try this on? Do note. This does not change any of the requirements for a block to grow, just changes the formula which happens when ticked.

I am skeptical whether we would want to change spigot's formula, as some may rely on the exact way it works currently.

**Comment by didkoti** [comment]
Oh, I kinda forgot about that issue.
I think the problem was that it needed really big values to actually feel some change.
You can close it.

**Comment by Darwin1546** [comment]
And what about 0?
You can set `sapling-modifier: 0` and trees will still growth.

**Comment by chickeneer** [comment]
> And what about 0?
> You can set `sapling-modifier: 0` and trees will still growth.

That sounds like something you just need to use a plugin for... Listen to the StructureGrowEvent.
Ultimately, this is a Spigot config. We will fix bugs in upstream; but for compatibility shouldn't be changing how those configs work...

Zero does nothing, check your server logs. Should get an error. (The internal formula divides by zero, so cannot allow that config value).
