### ISSUE TITLE
Problem with TPS and tracker stage? What does it means

### ISSUE THREAD

**Issue by KiroxTV** [PaperMC/Paper#3123]
As you can see, my problem is with TPS and some kinds of things that i don't understand, why?
Please, if someone kind can look into my configs and other staffs, what should I do to improve TPS laggs on my server? Either if it's there about 30+ people the server is lagging.. Just simple - What should I do, what plugin I should install, what option i can reduce - To reduce the TPS laggs on my server.
https://timings.aikar.co/?id=14f680717d564d7cb0fca4cdd7df37fd

**Comment by electronicboy** [comment]
The issue tracker is not for support with timings
