### ISSUE TITLE
Error with Citizens

### ISSUE THREAD

**Issue by Gorderok** [PaperMC/Paper#3128]
Hello, I have this error on build 168. I didn't have a problem on build> 165

https://pastebin.com/wveh7XDt
https://pastebin.com/af7XrGAr

Edit: this error this error with mythicmobs
https://pastebin.com/8JG0kmvu

**Comment by aikar** [comment]
this is 'mostly' mitigated in recent builds of what was causing an increased occurrence of this issue.

There is still a flaw in mojangs code, but that isn't new, and well handle that eventually.

But update and for most part this will be gone.
