### ISSUE TITLE
Wrong serialization - deserialization of written books

### ISSUE THREAD

**Issue by BlackBes** [PaperMC/Paper#3133]
### What behaviour is observed:
When de-serialising a serialised written (signed) book meta it will result in a different meta than it originally was. When applied to an item stack it will create two different items. (E.g. when saving into and getting from a config)

The difference between the two items will be in the pages section of the NBT data. The item that went through the serialisation process will have the book text in an extra tag and not in the text tag like the Vanilla one. (See NBTExplorer screenshot)

This does not happen with unsigned books.

I included a plugin with which one can test this, just get and sign a book with text and run the command /metatest while holding the book.

### Steps/models to reproduce:
Here is the code I use in the plugin for completion sake, it has to use a CraftClass as ConfigurationSerializable does not define a deserialize method in Bukkit:

`Map<String, Object> serialized = item.getItemMeta().serialize();
try {
    ItemMeta deserialised = CraftMetaBook.SerializableMeta.deserialize(serialized);
    ItemStack clone = new ItemStack(item);
    clone.setItemMeta(deserialised);
    if (item.isSimilar(clone)) {
        sender.sendMessage("Item is the same after serialisation and deserialisation!");
    } else {
        sender.sendMessage("Item is NOT the same after serialisation and deserialisation! Giving you the item...");
        ((Player) sender).getInventory().addItem(clone);
    }
} catch (Throwable throwable) {
    sender.sendMessage("Error while deserialising: " + throwable.getMessage());
    throwable.printStackTrace();
}`

### Plugin list:
Shopkeepers
[https://hub.spigotmc.org/jira/secure/attachment/12790/MetaTest.jar](url)
[https://hub.spigotmc.org/jira/secure/attachment/12791/NBTExplorer_2017-04-27_17-07-17.png](url)

### Paper build number:
176

### Anything else:
Wouldn't it be possible to save the pages in their stringified chat component format ("{text: "..", color: "..", ..}") and parse them from that, which should ideally be lossless? The deserialization would also need to be able to parse from the legacy format (for example by using the item's serialized data version to determine whether its using the old or new format).

**Comment by djytw** [comment]
May related to SPIGOT-3206

**Comment by BlackBes** [comment]
> 
> 
> May related to SPIGOT-3206

Yes, that`s it.

**Comment by aikar** [comment]
This is now resolved. I even PR'd it to Spigot.
