### ISSUE TITLE
max-entity-collisions still loads in new Spigot.yml when it's moved into Paper.

### ISSUE THREAD

**Issue by JMCY26** [PaperMC/Paper#3140]
Fresh install of paper, 

Both spigot.yml and paper.yml have: max-entity-collisions in the config when it doesn't do anything over the Paper one.

**Comment by electronicboy** [comment]
this is a side-effect of paper migrating old configuration over, it's considered a non-issue

**Comment by JMCY26** [comment]
It's not old configuration though, its new generated yml.

**Comment by electronicboy** [comment]
I know, what I'm saying is that the code which attempts to migrate that info over will add it to spigot.yml if it's not already set, this is basically considered a non-issue

**Comment by JMCY26** [comment]
gotcha, thanks!
