### ISSUE TITLE
Add Player#useItem(int slot) method

### ISSUE THREAD

**Issue by consllogluke** [PaperMC/Paper#3141]
**Is your feature request related to a problem? Please describe.**
Currently, forcing a player to use an item isn't too straightforward, and the only methods to do it are using NMS, or by manually checking to see what the item is and having a condition for each type of item to manually replicate the effects of using the item. Adding a nice method to the API would make this much easier to deal with.

**Describe the solution you'd like**
A `Player#useItem(int slot)` method that takes the slot in the player's inventory that you want to use would be the best solution. If there's no item in the specified slot, throw an exception. This will make plugin developers have to check to see if there's an item there prior to calling this method.

**Describe alternatives you've considered**
I've considered using NMS, which would break with almost every game update and is not very straightforward to newer plugin developers. I find NMS to be tedious and having to update with each game update is not something I really want to do. Another alternative is to manually replicate the effects of the item, but that would require many conditions and still wouldn't be perfect. Building this method directly into the API would make things a lot easier, as these alternate solutions are far from perfect.

**Comment by kickash32** [comment]
By using an item, do you mean consumables?

**Comment by Laarryy** [comment]
I'm going to mark this as stale; we don't know what the issue opener wanted to do specifically, and we don't have anyone else that seems to want this feature. 

If you or someone you love has been diagnosed with mesotheli-... would like to see this added, please open a new issue and describe what exactly you mean. For example, if you'd like to be able to trigger someone eating, you might request a `consumeItem` method for Players, especially if you don't mean something like throwing a potion, 'using' a bow that's not in-hand, etc. As it stands, depending on what the current feature requester wants (which we have not been told) we could end up overstepping what is necessary.
