### ISSUE TITLE
Adding PotionEffect ignores icon boolean

### ISSUE THREAD

**Issue by SoSeDiK** [PaperMC/Paper#3142]
### What behaviour is observed:
`CraftLivingEntity#addPotionEffect` ignores predefined `effect.hasIcon()` value resulting icon being controlled by `effect.hasParticles()`.

### Paper build number:
Build 183.

### Anything else:
I guess that should be fixed in the upstream, but I don't know where and how to report that :P

**Comment by Trigary** [comment]
That method tells you whether there's a texture for that specific potion type, not whether the texture will get displayed.

**Comment by SoSeDiK** [comment]
Why are you able to set that value then?
It's about whether you should see the icon on the top right of the screen or not.

**Comment by Black-Hole** [comment]
In the protocol there is indeed a flag to control the display of the icon in the client:
https://wiki.vg/Protocol#Entity_Effect

**Comment by zachbr** [comment]
This is just using the wrong constructor internally and not passing the flag along like it should be. Should be easy to fix.

**Comment by Trigary** [comment]
Apparently I'm stupid, sorry.
