### ISSUE TITLE
Only one entity/player can enter boat

### ISSUE THREAD

**Issue by Toffikk** [PaperMC/Paper#3147]
**What behaviour is expected:**

One or two entities/players can enter the boat

**What behaviour is observed:**

Only one entity/player can enter the boat.

**Steps/models to reproduce:**

You will have to try to enter the boat with another entity/player

**Plugin list:**
0 

**Paper build number:**
git-Paper-184 (MC: 1.15.2)

**Comment by chickeneer** [comment]
I was not able to replicate this with that build without plugins. Are you sure you do not have any plugins?

If so, maybe clarify the reproduction steps.
Here were mine.
Player A placed a Boat. And entered it.
Player B right-clicked and got in the boat as the passenger.
