### ISSUE TITLE
XP Orb merging(?) breaking XP farms (pigman farm)

### ISSUE THREAD

**Issue by silkera** [PaperMC/Paper#3148]
### What behaviour is expected:
XP flowing like in vanilla, as seen in this video https://www.youtube.com/watch?v=l9oteFEj770&t=50s

### What behaviour is observed:
No XP actually flowing to the player or occasionally a massive node of XP makes its way to the player

### Steps/models to reproduce:
build/ world download in the video link i posted, this happens in spigot as well.

### Plugin list:
- Armored Elytra
- AutoWorldBackup
- ChestSort
- DeathMessagePrime
- Denizen
- DeveloperAPI
- DynMap
- EssentialsX
- EssentialsXSpawn
- GroupManager
- ProtocolLib
- Vault

### Paper build number:
143

### Anything else:
I wouldn't've a slightest clue..

**Comment by BillyGalbreath** [comment]
Works as intended.

Disable xp merging in spigot.yml if you don't want it.

**Comment by silkera** [comment]
Setting the merging to -1 instead of 0 fixed the issue, thanks for reminding me to take a look at it again :)
