### ISSUE TITLE
Brigadier sorting performance

### ISSUE THREAD

**Issue by virustotalop** [PaperMC/Paper#3154]
###  Timings or Profile link:
https://spark.lucko.me/?CgSlYGCVq7

### Description of issue:
Brigadier is sorting nodes every time a child is added as seen [here.](https://github.com/Mojang/brigadier/blob/master/src/main/java/com/mojang/brigadier/tree/CommandNode.java#L92) This was tested on 1.13.2 but this likely is still an issue in the newest version. I believe that this issue is somewhat resolved due to #3116 but it could still be useful. This issue seems to be resolved by deleting the sorting line and [making the children map a TreeMap.](https://github.com/Mojang/brigadier/blob/master/src/main/java/com/mojang/brigadier/tree/CommandNode.java#L28) The issue occurs on login or world switch and may be related to previous issues discussed. This fix has been on a production server for a month with no noticeable issues. Not sure how reproducible this will be on the latest builds due to #3116 but let me know if I should try to reproduce this on a newer version.

### Plugin list:
Plugins (11): CountryFlags*, DynamicScoreboard*, Essentials*, EssentialsChat*, EssentialsSpawn*, LuckPerms*, ObbyLang*, PandaWire, PlaceholderAPI, RedstonePatch, spark*

### bukkit.yml, spigot.yml, paper.yml, server.properties
Default

### Other helpful links
Spark after the patch is applied: https://spark.lucko.me/?I7HW1n2Xll

### Paper build number: 
655 (MC: 1.13.2)

**Comment by Spottedleaf** [comment]
1.13 unsupported

**Comment by virustotalop** [comment]
I understand 1.13 is not supported and I'm not asking for an update to 1.13. I've already patched this in a maintained 1.13 build and I wanted to contribute the fix back to paper for supported builds.

**Comment by kickash32** [comment]
Please verify this issue exists in 1.15 builds first.

**Comment by virustotalop** [comment]
It seems that the main issue is fixed, where the server lags out but that doesn't occur anymore due to being called async. I wasn't able to produce any data with timings or spark but I decided to do some micro-profiling by checking the start and stop execution times. I did this by setting the start time at the beginning of the sendAsync method and then stopping and getting the time for completion before the runSync call. 

Time in millis
Before brigadier patch
```
[04:12:45 INFO]: Debug time: 7217
[04:12:46 INFO]: Debug time: 7706
[04:12:46 INFO]: Debug time: 8402
[04:12:47 INFO]: Debug time: 7830
[04:12:47 INFO]: Debug time: 7607
[04:12:50 INFO]: Debug time: 8152
[04:12:50 INFO]: Debug time: 8182
[04:12:53 INFO]: Debug time: 7038
[04:12:53 INFO]: Debug time: 8091
[04:12:54 INFO]: Debug time: 6749
[04:12:54 INFO]: Debug time: 7434
```
After brigadier patch
```
[04:14:48 INFO]: Debug time: 65
[04:14:48 INFO]: Debug time: 51
[04:14:49 INFO]: Debug time: 48
[04:14:49 INFO]: Debug time: 48
[04:14:50 INFO]: Debug time: 50
[04:14:50 INFO]: Debug time: 47
[04:14:50 INFO]: Debug time: 40
[04:14:51 INFO]: Debug time: 33
[04:14:51 INFO]: Debug time: 105
[04:14:52 INFO]: Debug time: 43
[04:14:52 INFO]: Debug time: 37
[04:14:52 INFO]: Debug time: 123
[04:14:53 INFO]: Debug time: 33
[04:14:53 INFO]: Debug time: 26
[04:14:54 INFO]: Debug time: 22
[04:14:54 INFO]: Debug time: 21
```

**Comment by aikar** [comment]
Good information overall, but may be worth posting this to Brigadier itself for mojang to improve.

**Comment by virustotalop** [comment]
I was thinking about submitting a pull request to Brigadier but it doesn't look like the repo is particularly active. I'm not sure how you guys want to include it, if you do. Would you prefer I try to push it to Brigadier itself? Just looking at the open pull requests did dissuade me from submitting a pull request to begin with.

**Comment by aikar** [comment]
Your welcome to open a PR here too. the file is already included in the project so makes it easy to edit.

That should be straight forward to pull, even with it being async no harm in getting the data computed faster and less CPU used.

But id still raise an issue on Brig repo, then hope someone sees it.

**Comment by Spottedleaf** [comment]
You can't make the children map a treemap. It's sorted by value, not key.

**Comment by virustotalop** [comment]
It looks like by looking at the code again the implementation creates the same result.  When adding a child the code calls [node.getName()](https://github.com/Mojang/brigadier/blob/8e9859e4712f06ad287f8c0a18725309151778ec/src/main/java/com/mojang/brigadier/tree/CommandNode.java#L86) which returns the name in `LiteralCommandNode`. The [compareTo()](https://github.com/Mojang/brigadier/blob/8e9859e4712f06ad287f8c0a18725309151778ec/src/main/java/com/mojang/brigadier/tree/CommandNode.java#L177-L184) method called gets the [getSortedKey()](https://github.com/Mojang/brigadier/blob/8e9859e4712f06ad287f8c0a18725309151778ec/src/main/java/com/mojang/brigadier/tree/LiteralCommandNode.java#L117) method which also returns the name. By looking at the code and looking at the output in-game everything seems correct. Do you see any issues, I could be looking at it wrong still.
@Spottedleaf

**Comment by Spottedleaf** [comment]
How interesting, good catch. However the values are also compared by the type of the CommandNode. Specifically, LiteralCommandNode will be sorted after ArgumentCommandNode.

**Comment by virustotalop** [comment]
That is true I did [miss this.](https://github.com/Mojang/brigadier/blob/8e9859e4712f06ad287f8c0a18725309151778ec/src/main/java/com/mojang/brigadier/tree/CommandNode.java#L181) The implementation looks fine when I check on the client but I don't have a great environment to test on. Alternatively a TreeSet could be used and then a HashMap for [getting a child by name.](https://github.com/Mojang/brigadier/blob/8e9859e4712f06ad287f8c0a18725309151778ec/src/main/java/com/mojang/brigadier/tree/CommandNode.java#L55) I don't think this is an ideal solution but I'm not aware of any Map implementations that you can sort by key. Any suggestions on how to implement it?

Edit: I went ahead and tested it with the new solution I came up with and everything seems fine. Let me know if you can think of anything wrong conceptually with the solution or an alternative.

**Comment by aikar** [comment]
It looks like current implementation childrens key is always the same thing as the values sortedKey except for RootCommandNode which is always empty, implying dont sort root

children.put(node.getName(), node);

however there is no harm in sorting based on command name either....

So currently a tree map exactly as initially proposed should be perfectly fine.

**Comment by aikar** [comment]
This is merged now
