### ISSUE TITLE
Named Mobs Despawning

### ISSUE THREAD

**Issue by Tomographix** [PaperMC/Paper#3157]
### What behaviour is expected:
Named mobs such as fish, dolphins, cows etc, including villagers do not despawn.

### What behaviour is observed:
Named mobs such as fish, dolphins, villagers etc despawn randomly.

### Steps/models to reproduce:
I have re-produced this issue with naturally spawned animals and ones spawned in via spawn eggs.
The mob is then named, then you wait. It can take several hours for the mobs to disappear.
For example, if you have 3 fish, 2 dolphins, one other mob and 2 villagers, they will steadily despawn over a time period of 15 minutes to days. The despawn is random but still happens reliably.

### Plugin list:
None. I wanted to make sure there were not any potential plugins causing the issue.

### Paper build number:
Paper version git-Paper-184 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
This is a relatively recent issue with PaperClip. The mobs were fine several weeks ago.
I do not have a build number sorry for that.

**Comment by nbastin** [comment]
Just as a data point, we're using Paper-185 with hundreds of villagers and at least dozens of named animals and I have personally not experienced this problem and no one else on the server has reported anything like it either.

Is there a simple test case that is reproducible in a fresh world with certain config?

**Comment by Tomographix** [comment]
> Just as a data point, we're using Paper-185 with hundreds of villagers and at least dozens of named animals and I have personally not experienced this problem and no one else on the server has reported anything like it either.
> 
> Is there a simple test case that is reproducible in a fresh world with certain config?

I'll test with clean spigot, bukkit, paperclip configs and let you know :)

**Comment by totemo** [comment]
I can't speak with surety to the villager issue (although... zombies?), but for fish and dolphins, they are prone to dying of suffocation. Ensure you include some kind of death logging in your test setup.

**Comment by Tomographix** [comment]
> Just as a data point, we're using Paper-185 with hundreds of villagers and at least dozens of named animals and I have personally not experienced this problem and no one else on the server has reported anything like it either.
> 
> Is there a simple test case that is reproducible in a fresh world with certain config?

Can confirm with a completely clean setup, that mobs are still disappearing.

> I can't speak with surety to the villager issue (although... zombies?), but for fish and dolphins, they are prone to dying of suffocation. Ensure you include some kind of death logging in your test setup.

I agree with the fish and dolphins, but they are just kept in a large open area. If other mobs weren't disappearing i'd put it down to that yes but it doesn't seem restricted to any specific mob type with others like parrots and villagers also going.

**Comment by Tomographix** [comment]
I'm not sure if it is related, but both of these commits were made to paperclip around the time of the issues starting:
https://github.com/PaperMC/Paper/commit/832687de704f645ddfd5e9cbc7a667c878ef8f14
https://github.com/PaperMC/Paper/commit/748e6447e3c9c8fff6ed56b35eadf4d09b0e1e76

**Comment by zachthedev** [comment]
I just got word from one of my players that they experienced the same issue today. A named zombie from the iron farm and the named pigmen from the pigmen farm despawned. Not sure how long it took to happen but it was noticed until today. They remember seeing the mobs yesterday night though.
I haven't been able to reproduce it yet.
Running version: git-Paper-217
Plugins: ChatItem, LuckPerms, OpenInv, ProtocolLib, ServerListPlus*, SpectatorMode, SuperVanish, TabList, WorldEdit

**Comment by nbastin** [comment]
Are these mobs protected from lightning?  Almost all of the "mysterious" named mob disappearances on our server can be explained by lightning, and protecting the areas has always solved the problem.

Also, again, if someone can describe a repeatable setup where this occurs, it would be easier to verify and isolate the conditions required for it to occur.

**Comment by Tomographix** [comment]
> Are these mobs protected from lightning? Almost all of the "mysterious" named mob disappearances on our server can be explained by lightning, and protecting the areas has always solved the problem.
> 
> Also, again, if someone can describe a repeatable setup where this occurs, it would be easier to verify and isolate the conditions required for it to occur.

I don't have weather enabled on my server.

**Comment by PierreBouchet** [comment]
I have the same issue with animals and villagers despawning randomly, even named ones. 
Specially animals spawned with eggs (reproduced chickens do not despawn but chickens spawned using eggs do) 
Just have to go to an other world, coming back and  they have despawned.

**Comment by benkocik** [comment]
I am having the same issue in git-Paper-261.  I have observed this with named villagers and named endermite.  For villagers, "tick-inactive-villagers" is set to true in spigot.yml.  For endermite, these mobs are located in The End.  After some further research I have found [this](https://bugs.mojang.com/browse/MC-27535) on Mojang's bug tracker for Minecraft Java, could this be a Minecraft issue and not Paper?  I plan to check if this issue is still happening in newer versions of Paper.

Edit: Should have added that this is a 1.15.2 survival server

**Comment by Tomographix** [comment]
> I am having the same issue in git-Paper-261. I have observed this with named villagers and named endermite. For villagers, "tick-inactive-villagers" is set to true in spigot.yml. For endermite, these mobs are located in The End. After some further research I have found [this](https://bugs.mojang.com/browse/MC-27535) on Mojang's bug tracker for Minecraft Java, could this be a Minecraft issue and not Paper? I plan to check if this issue is still happening in newer versions of Paper.
> 
> Edit: Should have added that this is a 1.15.2 survival server

I agree the villagers could be a Mojang issue. In saying that, I had no issues with them disappearing in 1.15.2 until several days before I created this post. Not a single one had despawned before that.

**Comment by Gazla** [comment]
Have seen similar issues recently since moving to Paper-240 it's been more common. Villagers and fish specifically have been reported as disappearing. 

Also haven't quite worked it out yet but Pillagers that spawn around a Pillager outpost seem to be being treated differently to Pillagers spawned by raids where plugins (like towny) are concerned.

**Comment by clrxbl** [comment]
Can also confirm that this issue is happening, for us it has been an issue for atleast months now.

**Comment by johnfriedrich** [comment]
Can confirm on Paper 282 for dolphins and squids

**Comment by WillFP** [comment]
Can confirm on paper-158

**Comment by clrxbl** [comment]
Paper 158 is super outdated, you should definitely upgrade @Auxilor

**Comment by electronicboy** [comment]
There is a mojang issue tracking this, we do have some improvements, but, apparently not 100%, one thing of a technical note, this probably doesn't impact people, but, the requirement is that they're marked as persistent, the name itself is actually irrelevant, saying that, I doubt that people are actually using plugins to name mobs in these cases
https://bugs.mojang.com/browse/MC-27535

**Comment by Tomographix** [comment]
> There is a mojang issue tracking this, we do have some improvements, but, apparently not 100%, one thing of a technical note, this probably doesn't impact people, but, the requirement is that they're marked as persistent, the name itself is actually irrelevant, saying that, I doubt that people are actually using plugins to name mobs in these cases
> https://bugs.mojang.com/browse/MC-27535

I agree part of this is a Mojang issue but mobs did not at all despawn before these two updates were added: https://github.com/PaperMC/Paper/commit/832687de704f645ddfd5e9cbc7a667c878ef8f14
https://github.com/PaperMC/Paper/commit/748e6447e3c9c8fff6ed56b35eadf4d09b0e1e76
There was no issues for quite a while on 1.15.2. The issue also isn't as prevalent on Tuinity either.

**Comment by jontyms** [comment]
> There is a mojang issue tracking this, we do have some improvements, but, apparently not 100%, one thing of a technical note, this probably doesn't impact people, but, the requirement is that they're marked as persistent, the name itself is actually irrelevant, saying that, I doubt that people are actually using plugins to name mobs in these cases
> https://bugs.mojang.com/browse/MC-27535

This bug is marked as fixed on snapshots

**Comment by sohcah** [comment]
Experiencing this with endermites on my PaperMC 1.16 server (paper-74)

**Comment by Til-Weimann** [comment]
confirming for 1.16, paper-89.jar

**Comment by Til-Weimann** [comment]
**For those of you with only Villagers despawning,** updating paper might be a solution.
There has been a bug in paper that deleted villagers with a reputation of <1 when sharing a gossip.
This bug should no longer occur with versions paper-98 and following.
See here: https://github.com/PaperMC/Paper/pull/3857

**Comment by aikar** [comment]
Not really, that bug only impacted Proxi using a Paper only API and had a bug in the code to create 0. 

That scenario never would happen without plugin code that im aware of.

**Comment by Til-Weimann** [comment]
True, but thats something I personally had. Just wanted to mention it if some of you used something similar.

**Comment by ConnorTron110** [comment]
Reproduced on paper-131 1.16.1

Im running a vanilla server using paper since Vanilla is super sluggish, he named some endermite and they de-spawned, hes super annoyed about this :/

**Comment by Proximyst** [comment]
Often endermites are quite simply killed. Can you ensure it vanished instead of died normally using something like CoreProtect?

**Comment by ConnorTron110** [comment]
Apparently there was no way it could die, I cant check that for sure but apparently there was no chance it could die.

**Comment by ghost** [comment]
Does your friend have thorns or anyone else because endermites attack players within 16 blocks and if a mob attacks an endermite, any endermites in the area become hostile toward that mob, and could've died that way.

**Comment by ConnorTron110** [comment]
No he took his armour off

**Comment by aeonlamb** [comment]
> Reproduced on paper-131 1.16.1
> 
> Im running a vanilla server using paper since Vanilla is super sluggish, he named some endermite and they de-spawned, hes super annoyed about this :/

If your server is using mcMMO, if you activate any combat abilities that do AoE damage (i.e. Serrated Strikes), it will inflict damage on any mobs within a certain radius- with a lot of common endermite lure enderman farms, this will end up killing the endermite because it's always close enough to be affected by this.

Not sure of your server setup, but you should consider plugin causes as well.

**Comment by ConnorTron110** [comment]
nah its pure vanilla, There was no way it would die

**Comment by whyonly8** [comment]
I too am having this problem. Any named Zombies disappear of disconnecting and reconnecting. I am on paper-136. I have a bunch of plugins but only Mythic Mobs effects the Mobs in any way. I could set all Zombies to never despawn, but this would cause huge problems. I updated to the most recent paper in an attempt to fix this, but it didn't help.

**Comment by mpriem** [comment]
Hi! I'm on Paper build #240 (1.16) and my kids are complaining that villagers are despawning randomly. Is this something that others are facing as well?

**Comment by Prof-Bloodstone** [comment]
@mpriem I know this is something that can happen, as will you if you'll read the messages above, but on my server each time someone reported it, it always turned out that a rogue zombie spawned and killed them.

Having a logging plugin like Prism, Logblock or Coreprotect helps to find out the cause, but by default you should receive information in logs about Villager deaths - try grepping through you log files to see if your missing villager is listed there.

If you will have trouble doing so for any reason and need help, join us on Discord.

**Comment by mpriem** [comment]
@Prof-Bloodstone thanks for your help. I went up and down the logs and couldn't find anything that would explain it. They are keeping their villagers boxed in in houses and giving them jobs. Some just randomly disappear. I have a few plugins but was wondering if this might not be just a Mojang bug. We see other strange things with villagers as well such as glitching and moving while on their back.

**Comment by VincyZed** [comment]
Can confirm. On my side named dolphins despawn as soon as everyone leaves the server for some time.

**Comment by Qwerty-Space** [comment]
Not sure if it's a related issue, but when a player is in the overworld somewhere, and you send a mob through a nether portal to somewhere else, the mobs will despawn.  However they don't despawn if there's no one in the overworld.

**Comment by Nemesees** [comment]
I'm currently having this issue in my server. I had a lake with a bunch of named pufferfish(around 16) and after a few weeks, only 2 remain. Fortunately it seems that other mobs I have named like the zombie for my iron farm, piglins for my piglin bartering system and villagers(not named).

**Comment by Machine-Maker** [comment]
actually, @Cybuuur if you are still having this issue, open a new one with your information. Thanks

**Comment by iSeitan** [comment]
still happening with purpur 1.17.1 build 1423

**Comment by Machine-Maker** [comment]
@iSeitan open a new issue with your information, reproduction steps, plugin, etc. the whole template. (and if you can reproduce it on **Paper** not **Purpur**. they have their own bug tracker

**Comment by Chew** [comment]
Purpur? 🤨

**Comment by iSeitan** [comment]
> Purpur? 🤨

It’s a fork of paper

**Comment by aurorasmiles** [comment]
Yes, report it to Purpur then or reproduce it on Paper and open a new issue.

**Comment by Machine-Maker** [comment]
If you can reproduce the issue on **Paper**, then you can report it here. but if not, then report it to them
