### ISSUE TITLE
java.io.WinNTFileSystem.rename0(Native Method)

### ISSUE THREAD

**Issue by BrockCruess** [PaperMC/Paper#3161]
git-Paper-243 1.14.4 crashes on regular world/playerdata saves but permissions are all in order on the server's files. Server is a z800 with 80gb of ram dedicated to the minecraft server, twin x5680 processors, Windows 10 pro.

Server thread dump (Look for plugins here before reporting to Paper!):
The server is waiting on these chunks: []
------------------------------
Current Thread: Server thread
PID: 31 | Suspended: false | Native: true | State: RUNNABLE
Stack:
java.io.WinNTFileSystem.rename0(Native Method)
java.io.WinNTFileSystem.rename(Unknown Source)
java.io.File.renameTo(Unknown Source)
net.minecraft.server.v1_14_R1.WorldNBTStorage.saveWorldData(WorldNBTStorage.java:117)
net.minecraft.server.v1_14_R1.WorldServer.saveIncrementally(WorldServer.java:905)
net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1124)
net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
java.lang.Thread.run(Unknown Source)
------------------------------
--- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
------------------------------
--- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-243 (MC: 1.14.4) ---
The server has not responded for 15 seconds! Creating thread dump
------------------------------
Server thread dump (Look for plugins here before reporting to Paper!):
The server is waiting on these chunks: []
------------------------------
Current Thread: Server thread
PID: 31 | Suspended: false | Native: true | State: RUNNABLE
Stack:
java.io.FileOutputStream.open0(Native Method)
java.io.FileOutputStream.open(Unknown Source)
java.io.FileOutputStream.<init>(Unknown Source)
java.io.FileOutputStream.<init>(Unknown Source)
net.minecraft.server.v1_14_R1.PersistentBase.a(SourceFile:51)
net.minecraft.server.v1_14_R1.WorldPersistentData.a(WorldPersistentData.java:171)
net.minecraft.server.v1_14_R1.WorldServer.k_(WorldServer.java:947)
net.minecraft.server.v1_14_R1.WorldServer.saveIncrementally(WorldServer.java:889)
net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1124)
net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
java.lang.Thread.run(Unknown Source)

**Comment by wizjany** [comment]
1.14 is no longer supported.

**Comment by BrockCruess** [comment]
So if 1.15.2 isn't stable and is being updated daily what are we supposed to use to run a stable server?? What stable versions do you support?

**Comment by zachbr** [comment]
All releases of Paper, including 1.14.4 got updates very frequently. It is not a sign of instability.
We only support 1.15.2 now.

**Comment by BrockCruess** [comment]
Can you confirm this issue has been addressed before I move my server to 1.15.2 then?

**Comment by zachbr** [comment]
Nope. You should move your server to 1.15.2 to get support in general.
This is a general poor performance issue in 1.14.4. It has generally gotten better in 1.15.2 but there is no way for me to guarantee either way about this specific issue.
