### ISSUE TITLE
Plugin load issue

### ISSUE THREAD

**Issue by Decme** [PaperMC/Paper#3162]
The ExtendViewDistance plugin and its dependency (XuanCatAPI) have stopped working since Paper 1.15.2 build 177

Build 177:
>.... [16:23:54 INFO]: [XuanCatAPI] Enabling XuanCatAPI v1.0.51
>.... [16:23:54 INFO]: [XuanCatAPI] NBT測試通過!
>.... [16:23:54 INFO]: [ExtendViewDistance] Enabling ExtendViewDistance v8.1.8
>.... [16:23:54 INFO]: [ExtendViewDistance] Plugin loading completed!

Build 178 to 185:
>.... [16:26:52 INFO]: [XuanCatAPI] Enabling XuanCatAPI v1.0.51
>.... [16:26:52 INFO]: {C:{S:1,K:[I;3,4,5,6]},A:[[[1,2,3,4]],[[1,2,3,4]]]}
>.... [16:26:52 INFO]: {A:[[[1,2,3,4]],[[1,2,3,4]]],C:{S:1,K:[I;3,4,5,6]}}
>.... [16:26:52 WARN]: [XuanCatAPI] NBT測試不通過...
>.... [16:26:52 INFO]: [XuanCatAPI] Disabling XuanCatAPI v1.0.51
>.... [16:26:52 INFO]: [ExtendViewDistance] Enabling ExtendViewDistance v8.1.8
>.... [16:26:53 ERROR]: [ExtendViewDistance] Plugin ExtendViewDistance v8.1.8 has failed to register events for class xuan.cat.ExtendViewDistance.Event because xuan/cat/XuanCatAPI/api/event/packet/ServerLightUpdatePacketEvent does not exist.

List of plugins:
Plugins (9): ExtendViewDistance, IllegalStack, NoSpectTab, PacketLimiter, PhantomSMP, PluginHiderPlus, ProtocolLib, spark, XuanCatAPI

**Comment by aikar** [comment]
Erm im iffy on this. 177 is what would've actually broke it... 
ARe you sure you have tried on latest? We fixed the issue uncovered in 177. But that build also shouldn't of impacted startup, only when a player first joins the world.

can you paste logs WITH the thread names?

**Comment by BillyGalbreath** [comment]
```
.... [16:26:52 INFO]: {C:{S:1,K:[I;3,4,5,6]},A:[[[1,2,3,4]],[[1,2,3,4]]]}
.... [16:26:52 INFO]: {A:[[[1,2,3,4]],[[1,2,3,4]]],C:{S:1,K:[I;3,4,5,6]}}
.... [16:26:52 WARN]: [XuanCatAPI] NBT測試不通過...
```
`NBT測試不通過` translates to `NBT test failed`, and looking at the verbose but cryptic output above it it looks like expected vs actual values do not match.

**Comment by aikar** [comment]
ah so its likely blowing up on the NBT Tag Compound change
Ask author to please add support for Paper for it.

It's likely trying to touch the internal map used in some way.

We didn't change the field type... so it must be trying to touch jvm hashmap internals.

**Comment by HauserGrim** [comment]
Author already updated plugin. :fp:
![image](https://user-images.githubusercontent.com/37507220/79499451-a3eb0f80-8033-11ea-8c2c-5329c451407c.png)

**Comment by Spottedleaf** [comment]
It broke because it relied upon iteration order.

**Comment by Decme** [comment]
Apologies, the plugin author had written several weeks ago that he was discontinuing development of the plugin, so I didn't think to check. He has updated & I checked it's now working with Paper 1.15.2 build 185
