### ISSUE TITLE
Inventory Interfaces Broken

### ISSUE THREAD

**Issue by ryanhaticus** [PaperMC/Paper#3163]
### What behaviour is expected:
An inventory to open.

### What behaviour is observed:
An inventory didn't open.

### Steps/models to reproduce:
Run `player.openInventory()` with any inventory.

### Plugin list:
Not relevant.

### Paper build number:
#1851 

### Anything else:
Works on Spigot. Paper is chugging.

**Comment by aikar** [comment]
Is the player sleeping or dead?

**Comment by ryanhaticus** [comment]
No, it's fired when the player joins. Works fine on Spigot, issues in Paper.

**Comment by electronicboy** [comment]
Don't open inventories on player join, there are potentially some oddball quirks with opening inventories there specifically on paper vs upstream, e.g. chunks are still potentially being sent to the client at that phase which with some other logic is kinda iffy; In general, even on spigot opening inventories in the join event is shaky at best, heavily recommended that you just don't do that
