### ISSUE TITLE
Paper 1.15.2 crash

### ISSUE THREAD

**Issue by averwhy** [PaperMC/Paper#3171]
### Link/paste of stack trace

    https://pastebin.com/p0JLS0Gg

### Plugin list:
CoreProtect, DiscordSRV, WorldGuard, WorldEdit, Holographic displays, Essentials, Multiverse core, multiverse inventories, multiverse nether portals, powerranks*

### Actions to reproduce (if known):
one person was in the nether, exploring, i was mining obsidian

### Paper build number:
version git-paper-167
_oops im 19 versions behind how do i update_

**Comment by aikar** [comment]
https://papermc.io/downloads - the same way you hopefully downloaded it in the first place.

this is fixed already
