### ISSUE TITLE
Attempting to sleep in a bed while in the air results in being kicked

### ISSUE THREAD

**Issue by greenywd** [PaperMC/Paper#3176]
### What behaviour is expected:
Beds should work as expected when attempting to sleep in them.

### What behaviour is observed:
Players get kicked for "Flying is not enabled on this server" when attempting to sleep in a bed while in the air.

### Steps/models to reproduce:
Jump, interact with a bed while still in the air, you enter the bed and appear to start sleeping however get kicked before waking up.

### Plugin list:
None

### Paper build number:
193

**Comment by greenywd** [comment]
After doing a bit of research I found that the bug occurs on vanilla servers too (https://bugs.mojang.com/browse/MC-114544). In that thread another bug is mentioned which might contribute to the issue as it relates to how the game misplaces you when waking you up from sleeping (https://bugs.mojang.com/browse/MC-148370).

**Comment by mcavoyk** [comment]
Not sure if this is the same issue, but villagers are not properly placed when exiting beds on Paper server. 

Trying to use Gnembon's iron farm from [here](https://youtu.be/vMSiholH_lc?t=1154), and on a vanilla server it works, but on Paper build 196, the villagers seem to drop out of their beds into the air about half the time.

**Comment by zachbr** [comment]
Not related to this issue, that's being tracked at GH-3009

**Comment by mcavoyk** [comment]
> Not related to this issue, that's being tracked at [GH-3009](https://github.com/PaperMC/Paper/issues/3009)

Thanks
