### ISSUE TITLE
Enderdragon battle in the overworld

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3177]
**Is your feature request related to a problem? Please describe.**
There is no way to create a DragonBattle and spawn an enderdragon with that dragonbattle controlling it. 

**Additional context**
I am trying to create an enderdragon fight event in the overworld and in my spawn area, if I try to set an enderdragon which I have spawned's phase to something such as circling it flies to 0,0 outside of spawn and then circles, perhaps because its dragonbattle is null and this is the default location. If one could change the location of the portal this ender dragon is trying to circle, perhaps by creating a DragonBattle and setting the portal location to the portal in spawn and then setting the dragon's dragonbattle to it.

**Describe the solution you'd like**
A method to instantiate a DragonBattle (maybe Bukkit/World.createDragonBattle?) and a method in EnderDragon such as dragon.setDragonBattle(DragonBattle dragonbattle) 
**Describe alternatives you've considered**
Using the dragons pathfinder to get it to move (Does not move)

**Comment by HexedHero** [comment]
I might be wrong but isn't the Ender Dragon's AI hardcoded into the game? Such as the move to 0, 0?

**Comment by ghost** [comment]
My assumption would've been it moves to its DragonBattle's getEndPortalLocation()?

**Comment by ghost** [comment]
If something like this isnt possible the second best thing would simply be a way to get an enderdragon to move.
