### ISSUE TITLE
TNT with high diagonal velocity crashes/laggs server

### ISSUE THREAD

**Issue by andrewgazelka** [PaperMC/Paper#318]
# Incompatibility (Bug)

High amounts of TNT with high diagonal velocity crashes/lags server. This behavior is strange compared to the normal amount of lag given.
### How to reproduce:

Just fire a lot of TNT that is moving diagonally quickly.
### Plugin list:

This still crashes servers with no plugins enabled.
### Paper build number:

This server is running CraftBukkit version git-PaperSpigot-60136e7-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

This bug has also been seen on multiple big 1.8 PaperSpigot servers. This has not been confirmed as a 1.9 PaperSpigot bug yet.

**Comment by PaulGaming** [comment]
Tnt doesn't travel diagnal.  It travels in a triangular pattern.

**Comment by andrewgazelka** [comment]
Yeah, I figured that out. I fixed it but unfortunately Paper doesn't accept 1.8.8 patches anymore.

**Comment by andrewgazelka** [comment]
The big issue was just chunks being loaded inside the triangle and not on the borders.

**Comment by sgdc3** [comment]
@UltraX3 They accept critical patches.

**Comment by andrewgazelka** [comment]
I'm pretty sure the only way to fix this is first load all the chunks in the X direction as see if TNT collides and then load all chunks in the Z direction.

**Comment by zachbr** [comment]
We do accept critical patches, this isn't one of them.

There are options built into paper 1.8.8 to kill TNT when it hits an unloaded chunk.

Ultimately, this is TNT flying around and loading chunks, as intended. If your server can't handle that option, don't use it.
