### ISSUE TITLE
Paper-198 - Failed to synchronously serialize unloading chunk data

### ISSUE THREAD

**Issue by ArtNRG** [PaperMC/Paper#3185]
### Link/paste of stack trace
https://paste.gg/p/anonymous/f2f3bac238034b6080bc640b1c64dbbb

### Paper build number:
The issue appears after upgrading from Paper-195 to Paper-198 with no plugin changes.

**Comment by Trigary** [comment]
Use 199

**Comment by aikar** [comment]
This is semi normal and happens occasionally on unloads.

Leaf could tell you why but long as a 2nd error doesn't show up following it, it is fine

**Comment by Spottedleaf** [comment]
It looks like it's possible to screw over class order initialisation thanks to the async save.
