### ISSUE TITLE
Citizens Plugin doesn't work with Paper-199

### ISSUE THREAD

**Issue by NicoNekoDev** [PaperMC/Paper#3186]
### What behaviour is expected:
Player NPCs from Citizens to exist

### What behaviour is observed:
Player NPCs don't spawn/load/exist as entities

### Steps/models to reproduce:
Just create an NPC with player entity type.
1) Install Citizens.
2) type /npc create bob [optional type /npc create bob --type player]
3) the entity doesn't spawn

### Plugin list:
Just Citizens (tested with version 2.0.26-b1881 and 2.0.26-b1857).

### Paper build number:
git-Paper-199 (I had git-Paper-196 and didn't have any issue)

### Anything else:
~~I'm gonna test it with version between 196 and 199.~~
Only on version 199.

**Comment by Spottedleaf** [comment]
This is due to https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0486-Fix-Longstanding-Broken-behavior-of-PlayerJoinEvent.patch#L38

**Comment by Blueeyestar** [comment]
We also have the problem

**Comment by engineer1109** [comment]
we cannot see the npc...  But the npc actually exists. They can speak, But are invisible in client.

**Comment by Blueeyestar** [comment]
It's because it's Npc with user skins. Because Npc with a mob look are all visible. So it must have something to do with it, the Citizens tries to retrieve the skin data but the new paper version blocks this

**Comment by Spottedleaf** [comment]
> 
> 
> It's because it's Npc with user skins. Because Npc with a mob look are all visible. So it must have something to do with it, the Citizens tries to retrieve the skin data but the new paper version blocks this

not even remotely correct

**Comment by Blueeyestar** [comment]
> 
> 
> > It's because it's Npc with user skins. Because Npc with a mob look are all visible. So it must have something to do with it, the Citizens tries to retrieve the skin data but the new paper version blocks this
> 
> not even remotely correct

then why is it ?? you can see all Citizens mobs like creeper skeletons and all other people just not citizens with playerskin. so why is that?

**Comment by HexedHero** [comment]
> > > It's because it's Npc with user skins. Because Npc with a mob look are all visible. So it must have something to do with it, the Citizens tries to retrieve the skin data but the new paper version blocks this
> > 
> > 
> > not even remotely correct
> 
> then why is it ?? you can see all Citizens mobs like creeper skeletons and all other people just not citizens with playerskin. so why is that?

Because they changed the player join code and the NPC is a fake player but looks real to the server. They didn't change monsters.

**Comment by aikar** [comment]
Ugh always problems with citizens. I think I know how to fix it

**Comment by Ma8ician** [comment]
same problem

**Comment by chickeneer** [comment]
Ma8ician. Did you upgrade to a newer Paper release? That is why this issue was closed. Is that Aikar pushed a new build which should have fixed it.

**Comment by aikar** [comment]
Build 200+ has the fix. I personally verified it.

**Comment by HexedHero** [comment]
Can confirm fixed in 200+ paper

**Comment by Ma8ician** [comment]
Thank you guys worked a treat!

**Comment by Ithirul** [comment]
200 Seems to work, but 201 makes them all invisible again :( could be just me tho since I have a lot of plugins, but this never happened before. Still, thanks a lot for your hard work! 200 works great.

**Comment by AlfieC** [comment]
> This is due to https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0486-Fix-Longstanding-Broken-behavior-of-PlayerJoinEvent.patch#L38

can we start linking patches properly so the links don't break on rebase

**Comment by aikar** [comment]
Too much effort. There's a browser extension that fixes the link for you.
https://github.com/PaperMC/Paper/blob/HEAD@%7B2020-04-19T12:05:23Z%7D/Spigot-Server-Patches/0486-Fix-Longstanding-Broken-behavior-of-PlayerJoinEvent.patch#L38

https://github.com/sindresorhus/refined-github
