### ISSUE TITLE
Cant connect to server

### ISSUE THREAD

**Issue by pederov** [PaperMC/Paper#3190]
So, i have a paper server, but when it has loaded and i go to the server list in minecraft it says: Cant connect to server. I dont understand because i dont get any errors in command prompt. I run these plugins: Worldedit bukkit
LuckPerms
MuliVerse core
Worldguard
Vault

And it says its overloaded sometimes, but idk how to fix it! So, if you could be so kind and help me it would be very much appreciated!

**Comment by electronicboy** [comment]
use the discord/IRC/forums for general support

**Comment by pederov** [comment]
What discord

**Comment by electronicboy** [comment]
Read the readme; https://github.com/PaperMC/Paper#paper-
