### ISSUE TITLE
Enchanting books does not preserve order of enchantment.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#3194]
When you go into an anvil, you can't rearrange the order of the enchantments on the books, while in a singleplayer vanilla world, you can. A player of mine is doing a special enchant where order on the books matters greatly (apparently).

### What behaviour is expected:
Enchantment order being preserved.

### What behaviour is observed:
Enchantment order is alphabetized?

### Steps/models to reproduce:

MULTIPLAYER

![link1](https://cdn.discordapp.com/attachments/700362485173190826/700362777470173224/2020-04-16_10.08.52.png)
![link2](https://cdn.discordapp.com/attachments/700362485173190826/700362788870160404/2020-04-16_10.08.54.png)
![link3](https://cdn.discordapp.com/attachments/700362485173190826/700362790254411867/2020-04-16_10.08.55.png)

---

SINGLEPLAYER

![link4](https://cdn.discordapp.com/attachments/700362485173190826/700487553924595732/2020-04-16_10.09.26.png)
![link5](https://cdn.discordapp.com/attachments/700362485173190826/700487555023634544/2020-04-16_10.09.27.png)
![link6](https://cdn.discordapp.com/attachments/700362485173190826/700487557913378896/2020-04-16_10.09.28.png)

### Paper build number:
Paper version git-Paper-184 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by wizjany** [comment]
https://github.com/PaperMC/Paper/issues/3110

**Comment by aikar** [comment]
This is purely display only as discussed on that linked issue.
This is how older versions of MC did it, and not going to break things just for a cosmetic difference.

**Comment by mibby** [comment]
Ah, I see. Thanks for the info!
