### ISSUE TITLE
[Feature] non-ticking-view-distance

### ISSUE THREAD

**Issue by partydev** [PaperMC/Paper#3196]
**Overall Bounty**
- $90

**Is your feature request related to a problem? Please describe.**
Do you really need to tick every chunk in your view distance? My players at least don't give a shit and only care about the first 3 chunks ticking in their view distance. This means that if there were a non-ticking-view-distance option, you wouldn't have to worry about the performance cost of increasing your view distance past 3! Imagine the adventures we could have if 1.15.2 servers could finally have a normal view distance just like all of the old versions! Anyway, in 1.15.2 chunks suck. Ticking them is super expensive and unnecessary in many cases. I suggest, no I beg, that the non-ticking-view-distance patch be ported to Paper.

**Describe the solution you'd like**
Implement a non-ticking-view-distance patch where if the non-ticking-view-distance is set higher than the normal view-distance, the chunks will not be ticked, only loaded in.

**Describe alternatives you've considered**
This is the only way.

**Additional context**
This is the only way. Also I am putting a $35 bounty on this one if anyone wants to contribute.

**Here is the bounty source link. Please contribute to this if you are able.**
https://www.bountysource.com/issues/91196936-feature-non-ticking-view-distance-35-bounty

**Bounty Contribution List**
- BartyRealms - $35
- ClassicSurvival - $20
- Anonymous - $20
- Draycia - $10
- JuanDelPueblo - $5

**Comment by maityyy** [comment]
https://www.spigotmc.org/resources/viewdistancetweaks-1-14-1-15.75164/
https://www.mc-market.org/resources/13692/

**Comment by partydev** [comment]
> 
> 
> https://www.spigotmc.org/resources/viewdistancetweaks-1-14-1-15.75164/
> https://www.mc-market.org/resources/13692/

First plugin you linked is outside of the scope of this issue, Second plugin does not work very well, is poorly documented (Chinese), and written using a closed source API. I prefer it being done at the server level as it has been proven to be more efficient.

**Comment by maityyy** [comment]
> > https://www.spigotmc.org/resources/viewdistancetweaks-1-14-1-15.75164/
> > https://www.mc-market.org/resources/13692/
> 
> First plugin you linked is outside of the scope of this issue, Second plugin does not work very well, is poorly documented (Chinese), and written using a closed source API. I prefer it being done at the server level as it has been proven to be more efficient.

The second plugin is open source. Also https://github.com/Kugge/BestViewDistance

**Comment by clrxbl** [comment]
> > > https://www.spigotmc.org/resources/viewdistancetweaks-1-14-1-15.75164/
> > > https://www.mc-market.org/resources/13692/
> > 
> > 
> > First plugin you linked is outside of the scope of this issue, Second plugin does not work very well, is poorly documented (Chinese), and written using a closed source API. I prefer it being done at the server level as it has been proven to be more efficient.
> 
> The second plugin is open source. Also https://github.com/Kugge/BestViewDistance


That doesn't matter, both of those plugins are irrelevant to the requested feature.

**Comment by partydev** [comment]
> 
> 
> > > https://www.spigotmc.org/resources/viewdistancetweaks-1-14-1-15.75164/
> > > https://www.mc-market.org/resources/13692/
> > 
> > 
> > First plugin you linked is outside of the scope of this issue, Second plugin does not work very well, is poorly documented (Chinese), and written using a closed source API. I prefer it being done at the server level as it has been proven to be more efficient.
> 
> The second plugin is open source. Also https://github.com/Kugge/BestViewDistance

The second plugin relies on a closed source API. Anyway, the first plugin relies on NMS which is not ideal, and the new plugin you suggested relies on methods that no longer work on Paper due to the patch being taken out. They are completely outside of the scope of the requested feature, as @clrxbl mentioned.

**Comment by Frogperson** [comment]
I would really love to see this added too. I suggested it about a year and a half ago https://github.com/PaperMC/Paper/issues/1531 but unfortunately, nobody seemed interested in implementing it stating that it wouldn't have many performance gains.

**Comment by electronicboy** [comment]
That was before mojang rewrote the whole chunk system so a lot of chunks are already loaded outside of the view distance, as well as having a super cool system for it

**Comment by Ghost-chu** [comment]
I have enjoy this on Tuinity, It should can merge in Paper from Tuinity.
*maybe*

**Comment by yashendra2797** [comment]
I get really excited every time a Paper dev talks about view distance implementations. I wish I knew of a way to help out with this issue.

**Comment by partydev** [comment]
Looks like leaf is rewriting it in Tuinity, might make the port over someday!

**Comment by rayanbzd** [comment]
spottedleaf have just finish to rewrite it, and il work really good. i'm using it with 120 online players and 0 problems. Juste perfect and an amazing work

**Comment by xuancat0208** [comment]
hmmmm.... It seems that this day will come soon
