### ISSUE TITLE
Help?!?!?! Server crashed?!?! I only spawned cat?

### ISSUE THREAD

**Issue by Muvvitt** [PaperMC/Paper#3197]
[latest.log](https://github.com/PaperMC/Paper/files/4506233/latest.log)

**Comment by electronicboy** [comment]
You missed the entire template, so no idea why I actually looked, but this is not a paper issue, spawning a metric ton of entities is going to overload the server's resources.

**Comment by juliavdkris** [comment]
but he only spawned cat

**Comment by darbyjack** [comment]
Buttttttttt theeeeeeee cat came back, the very next day, oh the cat came back, he thought he was a goner but the cat came back, he just couldn't stay awayyyyy

**Comment by Redned235** [comment]
> Buttttttttt theeeeeeee cat came back, the very next day, oh the cat came back, he thought he was a goner but the cat came back, he just couldn't stay awayyyyy

but he only spawned cat???
