### ISSUE TITLE
Remove prev. issue

### ISSUE THREAD

**Issue by dementisimus** [PaperMC/Paper#3198]
Hi!

Could you please delete my issue (https://github.com/PaperMC/Paper/issues/2848)? 
And after you did that, could you delete this one too?

Thank you so much! :D

**Comment by BillyGalbreath** [comment]
Issues aren't deleted. They are closed. The issue you linked was closed the same day you made it...

**Comment by VADemon** [comment]
I don't understand why you are so concerned about a random issue here Stefan. You can remove the text yourself.
