### ISSUE TITLE
 Suggestion to reduce server lags when a player connects.

### ISSUE THREAD

**Issue by TheCalypso** [PaperMC/Paper#3199]
**Is your feature request related to a problem? Please describe.**

Hello, like many Mini game servers we use PaperMC. However we are not supposed to know that when a player logs in there is a CPU unnick. For example we have a machine at OVH with the following characteristics: 4c / 8t 5GHz, 64Gram, 1To Nvme, 4Tode SSD. We run at an average of 30 players with 20% CPU usage. When a player connects the processor goes up to 60-70% then goes down to 20%. 

**Describe the solution you'd like**

In order to avoid this worry of prosseur pick. I could meet, someone who had developed "his paper". Its solution is simple, when the server starts, the map or maps are loaded in the Ram, when the player connects, the server does not recalculate the chuncks around the player but just sends the packets stored in the ram to the player. With this solution the picks disappear. I think this is an option that could be added in spigot with the choice of activation or not. This is of course not a solution for surviving servers but for all servers developing game modes with map statics (which does not change during the game) that would be really good! This solution also allows us to avoid micro lags when the CPU is saturated.
I remain at your disposal for any questions.

**Describe alternatives you've considered**

An alternative solution would be possible. Would it be possible to add an option with x1, z1, x2, z2. This would load the chuncks beyond the selected area.
We can apply this to the previous idea. Put a coordinate system to load the map in ram only the chunck in the selection.

I am aware that this is a time-consuming job.

I wanted to congratulate you on the work you do every day to optimize Paper, which is what drives me to give you ideas like this one! Continue like that !

**Comment by TheCalypso** [comment]
Hello, I post this message following the previous car I did not get a response from the party of the person I wanted to know if you read my message or just forgot to answer it x)

I understand that the idea I am putting forward is very complicated to implement unfortunately I am really sorry that I cannot give you a code? I don't have it in my possession.

Thank you for your efforts!

**Comment by aikar** [comment]
This is already possible. You may use forceload chunks on your entire map, or set a really large spawn radius.

Nothing crazy going to be done beyond that. 

There is one PR that will reduce login CPU usage, but need to verify it doesn't break anything though
I will go review that tonight.

**Comment by TheCalypso** [comment]
Thank you for your reply ! I tried the option "keep-spawn-loaded-range: 8
    keep-spawn-loaded: true ". But I don't see any difference in processor usage, always a spike when connecting the player. Do you have any other parameters to advise me?

**Comment by aikar** [comment]
Update, new version reduced cpu use on login

**Comment by TheCalypso** [comment]
No worries I will test with the next update (Paper-265) to see if I have any changes.
(I just tested quickly with the 264 and I didn't see anything, always going from 2% to 40%)

Thank you very much for your time and your answers! I am trying to help you as best I can.
