### ISSUE TITLE
Items won't move downward in hoppers

### ISSUE THREAD

**Issue by dwilley83** [PaperMC/Paper#320]
### Description of issue:

When items are traveling through a hopper chain and there is a hopper below one of them that is not locked, the items will keep going through the chain instead of traveling downward. Also noticed they will travel through a locked hopper. This affects the use of item sorters and the ability to lock hoppers. The Items will, however travel downward into hoppers if the hopper chain is broken and the item has no other choice but to go down. Could be a speed issue? Also have observed that hoppers will not transfer items when used in a hopper clock. Items have to be removed and placed back into the hopper.
### Plugin list:

AdminChatChannel, Announcer, CoreProtect, DeluxeChat, Dynmap, Essentials, FindMyEntities, ModifyWorld, PermissionsEx, Skript, Slack, SuperVanish, VillageInfo, WorldBorder, WorldEdit, and WorldGuard.
### bukkit.yml, spigot.yml, paper.yml, server.properties

bukkit.yml = http://pastebin.com/3N84Li50
spigot.yml = http://pastebin.com/Ta8LKrnS
paper.yml = http://pastebin.com/dnMUCS1B
server.properties = http://pastebin.com/VffSvatE
### Paper build number:

This server is running Paper version git-Paper-764 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
### What behavior is expected:

When a hopper is placed below another hopper (aimed in any direction) items should travel downward providing that the hopper is not locked/disabled. This is widely used in item sorters. 
Hoppers should also send items out of them if they are disabled. They will send items out but not take items in if they are locked. This is vanilla behavior.
### What behavior is observed:

Items will not transfer downward in unlocked/enabled hoppers if there is hoppers running in a chain with a hopper placed below the chain. Also have observed that hoppers will not send items out if they are locked/disabled. They should send remaining items out if they are locked but not receive them.
### Steps/models to reproduce:

Redstone item sorters with multiple channels and hopper chains with an unlocked hopper below one of the hoppers in the chain.

**Comment by zachbr** [comment]
Set `use-hopper-check` in paper.yml to false and let us know if the behavior continues.

**Comment by dwilley83** [comment]
After setting use-hopper-check to false, the hoppers work worse than they did before. When using them as an item sorter, sometimes the hopper will transfer items faster than normal or will completely ignore the item type it's supposed to be sorting.

**Comment by zachbr** [comment]
And are you on current latest or the same build you originally reported this to us with?

**Comment by dwilley83** [comment]
I think i had last noticed it on #784. I updated to #790 last night but had issues with baby zombie speed so I had to go back to #786 which didn't have any issues on my test server.

**Comment by dwilley83** [comment]
I noticed #791 is out right now and I will test that later tonight.

**Comment by zachbr** [comment]
Alright, just trying to make sure we can reproduce on latest.
Feel free to elaborate on the baby zombie speed issues here as well.

**Comment by dwilley83** [comment]
I'm not sure what happened with the baby zombie speed but I updated the paperclip jar file to Paper #790 last night, hadn't touched anything in the paper.yml file and I was running around at night and a baby zombie ran up and was running around so fast I couldn't kill it and i ended up dying. As far as I can tell, baby zombie speed is set to 5 in the paper.yml which I assume is the default. Before that we were on Paper #784 and didn't have that issue.

**Comment by dwilley83** [comment]
I just had the paperclip jar create a fresh paper.yml file and it looks like there's added and removed settings. It may be worth it to have the server create a fresh paper.yml file and make sure everything is set right.

**Comment by zachbr** [comment]
Should be 0.5. Not 5. 5 would be insane. Baby zombie movement speed, that is.

**Comment by zachbr** [comment]
Closing for age, if you can reproduce this on latest please open a new ticket.

**Comment by navyjosh** [comment]
I am experiencing the same issue.

edit] was this ever resolved?

**Comment by MiniDigger** [comment]
@navyjosh see Zs latest comment:
> if you can reproduce this on latest please open a new ticket.
