### ISSUE TITLE
[17:32:46 WARN]: was kicked due to keepalive timeout!

### ISSUE THREAD

**Issue by EgZiG** [PaperMC/Paper#3200]
### What behaviour is expected:
Not to kick players

### What behaviour is observed:
Kicking players

### Steps/models to reproduce:
Just be on server for a while and it will kick tou
### Plugin list:
https://prnt.sc/s3f0ak

### Paper build number:
git-Paper-245 (MC: 1.14.4)
### Anything else:
idk but i have over 1500 ping on server

**Comment by wizjany** [comment]
https://github.com/PaperMC/Paper/issues/895#issuecomment-372175216

**Comment by EgZiG** [comment]
i saw it, but it dosent solve the problem

**Comment by electronicboy** [comment]
1.14.4 is no longer supported, #895 basically covers this as much as possible
