### ISSUE TITLE
Chunks not loading in not default worlds

### ISSUE THREAD

**Issue by DaveTheCamper** [PaperMC/Paper#3201]
### What behaviour is expected:
Chunks loading correctly

### What behaviour is observed:
Some times it doesn't happen, when player goes to other world, chunks wont load, he must go back to default world and try again. (I already tried with only me online and same thing happened) This is not exclusivity of this world, all world that are not default worlds (world, nether and end) the same thing happen 

### Steps/models to reproduce:
First try: 
![2020-04-21_16 20 46](https://user-images.githubusercontent.com/44680026/79905923-5a147780-83ed-11ea-987f-e768c3c3fe1b.png)

Came back to default world and tried again: 
![2020-04-21_16 20 57](https://user-images.githubusercontent.com/44680026/79905954-68629380-83ed-11ea-87f5-348d4a9627c4.png)

Solo try: 
![2020-04-20_19 13 37](https://user-images.githubusercontent.com/44680026/79905982-72849200-83ed-11ea-842f-01cdf0ce9736.png)

Lets try again: 
![2020-04-20_19 13 47](https://user-images.githubusercontent.com/44680026/79905997-76b0af80-83ed-11ea-866f-54ae4806af54.png)

### Plugin list:
AdminFun*, AdvancedAchievements, AdvancedEnchantments*, AntiAFKPlus*, AntiWorldFly, ArmorStandTools, BlockLocker, Bloodmoon, boosCooldowns*, BossShop*, Cash, ChatControl, ChatPlugin, ChatReaction, ChestMaster*, ChestShop, Citizens, ClearAll*, ClearLag, ComandosMysql*, CombatLogX, CrazyAuctions, CS-CoreLib, CubeShopPlugin*, CustomHeads*, CustomMessages*, CustomPayloadFixer*, CustomPolls*, DeathMessagesPrime, DeluxeTags*, EconomyControl, Elevator, EntityTrackerFixer, Essentials, EssentialsSpawn, Eventos, ExperienceBottle*, FastLogin, FirstJoinPlus*, Gladiador, GriefPrevention, GroupManager, Images, ItemFilter, Jobs, Keys, LagAssist, Leilao, LuckCommands, Marriage*, MC-Cron*, mcMMO, Multiverse-Core, MyCommand, MyPet, NoSpawnChunks*, OldCombatMechanics*, OreAnnouncer, PacketListenerApi*, PerWorldPlugins*, PlaceholderAPI*, ProtocolLib, Pshops, QuestsReloaded, ResetChest, RPGItensRevolutions, SafeTrade, ServerTutorialPlus*, Shopkeepers, SignEdit*, SimpleClans*, Skilltree, Slimefun, Spawners, StackItens, StackMobs, TAB, Ticket, TitleManager*, TopLite*, Torneio, TreysCommandBlocker*, Tutorial, UberEnchant*, Upgrade, Vault, Vender, ViaVersion*, VipZero*, Votifier*, VotingPlugin, VoxelSniper*, WorldEdit, WorldGuard, X1

### Paper build number:
This server is running Paper version git-Paper-201 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
This starts after 170 build

**Comment by aikar** [comment]
Can you try without this plugin "NoSpawnChunks"? sounds very suspect...

Haven't had anyone else report something like this. I also use non default worlds myself too without issue.

**Comment by DaveTheCamper** [comment]
Already tried without NoSpawnChunks and doesn't work, but i removed to test again and have the same result. Something that can help and i forgot to say is, if for one player the chunk is loaded, it can still stay unloaded for someone else even if they are already normalized for some player.

**Comment by DaveTheCamper** [comment]
This is a Citizens issue
