### ISSUE TITLE
Player was kicked due to KeepAlive Timeout

### ISSUE THREAD

**Issue by soshimee** [PaperMC/Paper#3204]
### What behaviour is expected:
___Players NOT being disconnected with slow internet.___

### What behaviour is observed:
___Players with slow internet being disconnected from the server. (KeppAlive Timeout)___

### Steps/models to reproduce:
___Have super slow internet and join any server.___

### Plugin list:
___Happens without any plugins___

### Paper build number:
___Happens in all versions___

### Anything else:
___Adding a config to configure KeepAlive Timeout___
___I have no proxy___

**Comment by electronicboy** [comment]
#895
