### ISSUE TITLE
Hardcrash when closing GUI monitor on startup

### ISSUE THREAD

**Issue by Joren2087** [PaperMC/Paper#3212]
### Link/paste of stack trace

Although the stacktrace reports "do not report this to paper", I successfully reproduced this bug without any plugins. My world also isn't corrupted. If I leave the GUI open the server successfully starts.

https://paste.md-5.net/ewaserujew.md
https://paste.md-5.net/ogerobudal.md

### Plugin list:
I was able to reproduce this bug without any plugins

### Actions to reproduce (if known):
Start the server in command prompt with the following bash command:
`java -Xmx4096M -jar Paper-latest.jar`
On startup, the new GUI window will apear. Close the window while the server is still starting up. This causes some recursion loop (or whatever) and the watchdog will kill the server thread.
No crash folder has been made after this crash.

### Paper build number:
```
[18:03:48 INFO]: This server is running Paper version git-Paper-209 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[18:03:48 INFO]: Checking version, please wait...
[18:03:48 INFO]: Previous version: git-Paper-199 (MC: 1.15.2)
[18:03:48 INFO]: You are 2 version(s) behind
```

Thank you in advance.

**Comment by electronicboy** [comment]
Probably the recent toyings with watchdog, but, you can't close the GUI when the server is running, it will stop the server, with with --nogui if you want no gui

**Comment by Joren2087** [comment]
Do you mean it shouldn't be possible to close the GUI window or just that I may not close the window?However, it would be better if this is fixed. A hardcrash cannot be healthy for my server data.

**Comment by electronicboy** [comment]
you cannot close the window without stopping the server, the only concern here is that watchdog tried to do stuff, the issue with watchdog is actually already fixed
