### ISSUE TITLE
Server stuck after he tries to update himself

### ISSUE THREAD

**Issue by kamziksvk** [PaperMC/Paper#3218]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

Hello I am little bit desperate. My paper lobby / authme server was working fine for a few months withouth serious problem. Tonight the problem wit lag stacktrace started and it seems like the server wants to upgrade himself. I looked into the plugins and other stuff too, but it seems to me it is a problem of Paper Spigot update. Can you please take a look at it? Thank you in advance!

Including the server log: https://pastebin.com/2nja25s4

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list: AnimationLib, AuthMe, AWD, BotBank, BungeeNPC, BuycraftX, Citizens, CommandNPC, ConsoleSpamFix, CountryOnJoin, CraftBook, CustomServerMessages, DiscordLink, Essentials, EssentialsChat, EssentialsGeoIP, FastAsyncWorldEdit, FastLogin, FunGun, HackedCore, HackedServer, HolographicDisplays, Images, midas_monitoring, MidasVIP, MidasVote, MultiWorld, MyCommand, NoDrop, NoRain, PermissionsEx, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, ServerSelectorX, SkinsRestorer, SkQuery, Skript, SpawnTP, SuperbVote, TimeLock, TitleManager, UltimateBossBar, UltraCosmetics, VoidGenerator, VoidTP, Votifier, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

___A list of your plugins___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

I dont know how to reproduce this error.

### Paper build number: 
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-1618

[17:43:27 INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[17:43:27 INFO]: Previous version: git-Paper-"5d8b3d49" (MC: 1.12.2)
[17:43:27 INFO]: Checking version, please wait...
[17:43:27 INFO]: You are running the latest version

**Comment by electronicboy** [comment]
1.12.2 is no longer supported, you also have some plugin using a update library which is trying to connect somewhere and killing the server as it's timing out

**Comment by kamziksvk** [comment]
> 1.12.2 is no longer supported, you also have some plugin using a update library which is trying to connect somewhere and killing the server as it's timing out

And do you have idea which plugin could it be? I checked the log, but didn't find anything
