### ISSUE TITLE
[feature] add 'getRestocks()' and 'setRestocks()'

### ISSUE THREAD

**Issue by Thibaut040** [PaperMC/Paper#3219]
**Is your feature request related to a problem? Please describe.**
I try to change the amount of stocks a villager can do a day.

**Describe the solution you'd like**
add method `getRestocksToday()` or/and `setRestocksToday()`
You can find it with /data command.

**Describe alternatives you've considered**
Something complicated with saving times of clickevents in variables, matching with recipes, but it didn't work :(

**Additional context**
If you have another solution to my problem, feel free to leave a comment. :)

**Comment by yashendra2797** [comment]
Is this fixed now with https://github.com/PaperMC/Paper/commit/c03260a280347e73ed9c7018646492ffc936ea81? Can the issue be closed?
