### ISSUE TITLE
All chests after updating to 770 from 768 erased

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#322]
Just updated to 770 from 768 and all chests are empty

**Comment by kashike** [comment]
Please use the issue template

**Comment by ghost** [comment]
No plugin or config changes. Plugins are nocheatplus and some chat only plugins that don't touch any inventory functions at all.

Stopped the server on 768, updated to 770. After starting, players that opened their chests found them completely empty. I quickly stopped and went back to 768 and items are no longer disappearing from chests

**Comment by aikar** [comment]
about to push fix. just found this myself with my change tonight.

**Comment by aikar** [comment]
This is fixed in Build 772
Sorry about this. I too got hit by it myself and had to restore backups.
