### ISSUE TITLE
Chunks not loading or loading very slow in 1.15.2

### ISSUE THREAD

**Issue by bloggy** [PaperMC/Paper#3220]
### Paper build number:
This server is running Paper version git-Paper-214 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Performance Issue:

I just updated my 1.13.2 server to 1.14.4 and then to 1.15.2 using the spigot's --forceupdate startup parameter. But chunk loading seems to be very slow in 1.15.2 compared to 1.13.2. Especially when TPS drops below 20, you will sometimes notice chunks not loading or loading only in a view-distance of 1 from the player's location.

Is there anything to chance in the paper's config to prevent chunks from loading so slowly? I have not touched paper config at all, because in 1.13.2 chunk loading is so smooth and the view distance keeps the same (we set it to 4) even on low tps. 

What is causing this and how can we optimize this to get better performance when it comes to chunk loading?

**Comment by Thibaut040** [comment]
How much memory (RAM) do you have?

**Comment by aikar** [comment]
The entire chunk system just got extremely more complex in 1.14 and 1.15. 

We've got some optimizations to speed up loading more than vanilla does at least.


if servers overloaded, processing those chunk tasks will be delayed some to avoid decreasing TPS EVEN MORE... This is actually vanilla logic.

I did jump on a server that was running 6 TPS and flew around, and yes it wasn't blazing fast, but didn't seem as bad as you reported.

I'm pushing an improvement to our patch to make it push loads even harder, so this should be greatly improved.

And you have a lot of players and you want to improve GENERATION speed, at the cost of more TPS loss, then you can increase this new config:

settings.chunk-tasks-per-tick
defaults to 1000

Note, that this 1000 does NOT apply to simple loads.

**Comment by aikar** [comment]
Will be build 218+

**Comment by bloggy** [comment]
Thank you aikar for your reply. I will check out that build once available. Chunk generation is nothing that I really need as we have a fully rendered 1.13.2 map which was updated to 1.14.4 and then to 1.15.2. All chunks are already generated there.

The only thing we really are looking for is an improvement for chunk loading, especially when TPS are between 11 and 20 TPS. We run a busy server with many plugins and up to 100 player per server.

But as I mentioned: we don't have any issues with chunk loading on the same machine, same settings but on 1.13.2. 

UPDATE: Oh the build is already there :-D So I report back once we tested it.

**Comment by bloggy** [comment]
Hello aikar,
we have tested it now (the latest version of paper from today) but the chunk loading is not much better or better at all than it was before. I can not see any difference :-/ Especially when traveling fast with boats on ice ground, you often get stuck in unloaded chunks even though we have:
prevent-moving-into-unloaded-chunks set to true

Do you think there is anything else you can improve? Why do chunks not load asynchronous? wouldn't that help?

**Comment by kickash32** [comment]
Chunk loading is async, however the whole chunk system is just slower due to multitude of reasons. If you want to feel the improves paper has made, try running 1.15.2 spigot. 1.15.2 is just slower than 1.13.2 and you will just have to accept that.

**Comment by aikar** [comment]
@bloggy can you provide a timings report? How many CPU cores do you have? memory?

Please join discord and discuss there and we can provide tips to improve.

As said, chunks do load asynchronously. Your system appears to just not be able to keep up.

My servers are running on a pretty old CPU and even at 6 TPS it was fine.

**Comment by bloggy** [comment]
I can provide spark profiler link: https://spark.lucko.me/#fBbJehQrDp
At this time we had about 30 - 40 players on the server (we run a dedicated machine with I7 and 32 GB RAM). We have no issues with chunk loading on 1.13.2 as mentioned above.
