### ISSUE TITLE
Kicking Player while commandspamming -> ConcurrentModificationExeption

### ISSUE THREAD

**Issue by Nononitas** [PaperMC/Paper#3223]
I programmend a plugin which edits players PacketPlayOutTabComplete with ProtocolLib. On spigot.jar its working fine and won't kick me. If I use paper instead it will kick me

### What behaviour is expected:
Edits players Tabcomplete.

### What behaviour is observed:
If you spam a command in example "/gd claim extend" it will kick you with the following exception:
https://pastebin.com/Mzi9abav

### Steps/models to reproduce:
Spam "/gd claim extend" you need the permission griefdefender.*

### Plugin list:
ProtocolLib 4-5.1-SNAPSHOT-b447, PL-Hide-Pro (please write a pm because its a premium plugin), griefdefender-1.2.5c, Luckperms

### Paper build number:
git-Paper-217 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

If you need more information please ask. Thanks in advance

**Comment by electronicboy** [comment]
We'd need replication code, but based upon the nature of the servers code, this is unlikely to be related to paper itself; I'd suggest joining discord
