### ISSUE TITLE
Lead disappears after forcing leashed mob go through nether portal

### ISSUE THREAD

**Issue by i0xHeX** [PaperMC/Paper#3226]
### What behaviour is expected:
Lead will drop on the other world near mob teleported (as it works on pure vanilla)

### What behaviour is observed:
Lead disappears

### Steps/models to reproduce:

1. Leash a mob
2. Force him to go through nether portal
3. Teleport to another world via that portal

### Plugin list:
Auth, CoreProtect, EasyBackup, Harbor, HideLog, LuckPerms, MadhouseMusic, PlugMan, ProtocolLib, RFChairs, SafeLag, ServerRestart, SkinsRestorer, spark, WhitelistPlayers*

### Paper build number:
git-Paper-220 (MC: 1.15.2)

**Comment by aikar** [comment]
I'm guessing Spigot bandaided this here and now that the root issue is fixed, this isn't needed anymore:

if (this instanceof EntityInsentient) {
                    ((EntityInsentient)this).unleash(true, false); // Unleash to prevent duping of leads.
                }

Will see if removing that fixes it.
