### ISSUE TITLE
Pregenerating while using RealisticWorldGenerator v4.9.5 leads to server crash

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3230]
When using plugin: chunkmaster v0.15b to pregenerate the world
and
When using plugin: realisticworldgenerator v4.9.5 for world-gen

We get the following errors which lead to server crashing:

Current Thread: Server thread
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: PID: 23 | Suspended: false | Native: false | State: TIMED_WAITING
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: Stack:
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: sun.misc.Unsafe.park(Native Method)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.bl(IAsyncTaskHandler.java:131)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:486)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:325)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:270)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.World.getType(World.java:649)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:194)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setBlockData(CraftBlock.java:177)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: com.syntaxphoenix.realistic.antileak.Mihoko.Takayama(SourceFile:54)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: com.syntaxphoenix.realistic.antileak.Isa.Takayama(SourceFile:154)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: com.syntaxphoenix.realistic.antileak.Isa$$Lambda$4040/2088021679.run(Unknown Source)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: com.syntaxphoenix.realistic.antileak.Manabu.Hikozaemon(SourceFile:46)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: com.syntaxphoenix.realistic.antileak.Manabu$$Lambda$4041/1501059172.run(Unknown Source)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: java.lang.Thread.run(Thread.java:748)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: ------------------------------
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: Current Thread: Server Infinisleeper
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: PID: 25 | Suspended: false | Native: false | State: TIMED_WAITING
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: Stack:
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: java.lang.Thread.sleep(Native Method)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: net.minecraft.server.v1_15_R1.DedicatedServer$1.run(DedicatedServer.java:72)
26.04 23:36:09 [Server] Startup [03:36:09 ERROR]: ------------------------------

Server Specs Are As Follows:
Paper v220
Intel  Xeon E5-1630v3 @ 3.7Ghz
DDR4 ECC Memory
16GB RAM
250Mbps Uplink

Love PaperMC btw so keep up the good work :)

Thanks,
            Blake

**Comment by aikar** [comment]
need full logs. you cut off any potential useful info to help you figure it out.
