### ISSUE TITLE
Entity Pathfinder NullPointerException after upgrading to paper. (nearly crash)

### ISSUE THREAD

**Issue by jokbon** [PaperMC/Paper#3232]
**Entity Pathfinder NullPointerException**

Paper: 209 (fix version)->220 (isusue version)->216 (fix version)

Sad story:
Closed paper 209 by /stop
Placed paper 220
Started server.
Joined server noticed warnings in console.
Entities started to weirdly disapear.
After some time commands stopped to work.
Closed server.
Deleted version cache.
Placed paper 216
Started server.
Same warns. 
/killall fox > 0 cleared
/killall all > multiple cleared
Still warns.
Restarted server
No warnings

[New Text Document (5).txt](https://github.com/PaperMC/Paper/files/4538158/New.Text.Document.5.txt)

**Comment by aikar** [comment]
timings report? plugins?

haven't seen this before, and the only thing that could even make this NPE is if the getControllerLook() was returning null which would be really odd...

I suspect plugin.

**Comment by jokbon** [comment]
Plugins:
AutoPickup, BetterSleeping*, BungeeGuard, Essentials, EssentialsChat, EssentialsSpawn, InfiniteScoreboard, JumpPads, LuckPerms, PlaceholderAPI, SkinsRestorer, UltimateChat, UltimateModeration, VoidTP, WorldEdit, WorldGuard

**Comment by kashike** [comment]
This issue has become stale - if this is still an issue on the latest version of Minecraft we support, please open a new issue.
