### ISSUE TITLE
Server Error Upon Load

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3235]
### What behaviour is expected:
No Errors

### What behaviour is observed:
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: Current Thread: Server thread
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: PID: 24 | Suspended: false | Native: false | State: RUNNABLE
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: Stack:
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.lang.Throwable.fillInStackTrace(Native Method)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.lang.Throwable.fillInStackTrace(Unknown Source)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.lang.Throwable.<init>(Unknown Source)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.lang.Exception.<init>(Unknown Source)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.lang.ReflectiveOperationException.<init>(Unknown Source)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.lang.ClassNotFoundException.<init>(Unknown Source)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.net.URLClassLoader.findClass(Unknown Source)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: app//org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: app//org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:215)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: app//org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: app//org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.lang.ClassLoader.loadClass(Unknown Source)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.lang.ClassLoader.loadClass(Unknown Source)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: com.comphenix.protocol.concurrency.ConcurrentPlayerMap.entrySet(ConcurrentPlayerMap.java:268)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.util.AbstractMap$2$1.<init>(Unknown Source)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.util.AbstractMap$2.iterator(Unknown Source)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: com.comphenix.protocol.async.PlayerSendingHandler.trySendServerPackets(PlayerSendingHandler.java:205)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: com.comphenix.protocol.async.AsyncFilterManager.sendProcessedPackets(AsyncFilterManager.java:480)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: com.comphenix.protocol.ProtocolLib$3.run(ProtocolLib.java:558)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: app//org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: app//org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: app//net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: app//net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: app//net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: app//net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
27.04 10:22:08 [Server] Startup [14:22:08 ERROR]: java.base@11.0.6/java.lang.Thread.run(Unknown Source)

### Plugin list:
Full server log here: https://mcpaste.io/d0f0e2363b809957

### Paper build number:
v220

**Comment by aikar** [comment]
```
[Server] Startup [14:22:08 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-226 (MC: 1.15.2) ---
[Server] Startup [14:22:08 ERROR]: The server has not responded for 10 seconds! Creating thread dump
```
Your plugins are choosing to create this scenario, notably skript and protocollib. by delaying tasks until after the server started instead of blocking until fully initialized like they should be.

Not an issue, just its telling you plugins did something iffy.
