### ISSUE TITLE
Server Crash When Pregenerating Chunks

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3236]
### What behaviour is expected:
No Crashing

### What behaviour is observed:
Server Crash due to Paper Watchdog Thread

### Plugin list:
Plugins believed to be causing the issue: 
1. chunkmaster v0.15b
https://www.spigotmc.org/resources/chunkmaster.71351/
2. realistic world generator v4.9.6 https://www.spigotmc.org/resources/realisticworldgenerator.15905/

Full Server Log Here: https://mcpaste.io/1008fb6bbdd09975

### Paper build number:
Paper v226 (newest at time of issue)

**Comment by aikar** [comment]
Not a bug. your generating too many chunks at one time.

consult with those 2 plugins to find the best configurations to avoid this.
