### ISSUE TITLE
Worldguard Hook Error

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3238]
### What behaviour is expected:
Error when trying to hook into worlguard

### What behaviour is observed:
27.04 10:57:40 [Server] Startup [14:57:40 INFO]: [Wind] Could not hook into WorldGuard, WorldGuard Platform or instance is null!
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: java.lang.NullPointerException
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:100)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at b.c.b(Unknown Source)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at a.j.c(Unknown Source)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at me.creeper.wind.Wind.a(Unknown Source)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at me.creeper.wind.Wind.onEnable(Unknown Source)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895)
27.04 10:57:40 [Server] Startup [14:57:40 WARN]: at java.base/java.lang.Thread.run(Unknown Source)

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
Full Log: https://mcpaste.io/1fc6087c933caea9

### Paper build number:
Paper v226 (newest at time of issue)

**Comment by wizjany** [comment]
that's an issue with whatever plugin `me.creeper.wind.Wind` is, nothing to do with paper
also the link is anything but a "full log"
