### ISSUE TITLE
Chunk

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#324]
So it should be? build 772
![image](https://cloud.githubusercontent.com/assets/14358233/15877203/282fef56-2d1b-11e6-97f4-cca782aa7907.png)

**Comment by aikar** [comment]
try the F3+H I think it is to refresh chunks (look it up)

the client is a bit buggy still with problems like this.

**Comment by connection-lost** [comment]
@aikar *F3+A

**Comment by FunnyCraft** [comment]
and it would give me?
For example, I run around the world and all that I saw chunks remain in the client.

**Comment by FunnyCraft** [comment]
You can check it out for yourself.

**Comment by connection-lost** [comment]
I think this happens to me before I install optifine too. It should be a client issue.

**Comment by FunnyCraft** [comment]
This will somehow be corrected?

**Comment by sgdc3** [comment]
@FunnyCraft It's a client issue, i don't think that there is a way to fix this server-side.
