### ISSUE TITLE
Villagers walk even if they farther then activation-distance

### ISSUE THREAD

**Issue by StKillReal** [PaperMC/Paper#3241]
**What behaviour is expected:**
Villagers doesn't move if they are farther then activation-distance 

**What behaviour is observed:**
Villagers move so far like they want and it doesn't metter which activation-distance I use

**Steps/models to reproduce:**
Set activation-range for villagers to 10 and go farther than 10 and they still will move, search beds, do everything they need and cause lag

**Plugin list:**
There are no plugins which change villagers behaviour in my plugin list

**Paper build number:**
Build 226 (it started from 221)

**Anything else:**
Even if I set this values, villagers still walk around
wake-up-inactive:
        villagers-max-per-tick: 1
        villagers-every: 6000
        villagers-for: 1

**Comment by wizjany** [comment]
tick-inactive-villagers?

**Comment by electronicboy** [comment]
this is probably part of EAR 2, where there is an intent to actually keep entities in a manner where they can do stuff properly, induces much less breakage to farms, etc

**Comment by StKillReal** [comment]
> tick-inactive-villagers?

false

**Comment by aikar** [comment]
If you wish to truely make them not move again when nothing to do, edit spigot.yml 

wakeup-inactive section

set villagers-max-per-tick to 0

please jump on discord if you need any more assistance in configuration

Though, villagers will still get immunity when they have tasks to do.

**Comment by aikar** [comment]
i guess if you want truely "dumb" villagers, would need to add some dumb mode config for them heh.

But ear has always been the intent to try to keep vanilla mechanics alive still, just keep them low cost during inactivtiy.

**Comment by StKillReal** [comment]
> i guess if you want truely "dumb" villagers, would need to add some dumb mode config for them heh.

Yes, I think "dumb villagers" is really important setting if we're talking about 1.14+, cause villagers just kill tps. Players make farms with villagers to trade with them and their activities like searching beds, going to the job etc are not important, because they just sit in the small buildings 3x3 blocks and only one things they should do is trading. I really hope u will add some option like this
