### ISSUE TITLE
Live Adjustments To Server View-Distance

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3242]
**Is your feature request related to a problem? Please describe.**
Would improve server performance.

**Describe the solution you'd like**
A setting to allow the server to auto-update the servers view-distance based on server tps.
Decreasing it when server TPS dips below a predefined threshold.
Increasing it when server TPS is above predefined threshold.

**Comment by electronicboy** [comment]
This API is currently missing from the server, but should hopefully be back in the future
