### ISSUE TITLE
Lagging EntityTick

### ISSUE THREAD

**Issue by TheKlimoT** [PaperMC/Paper#3245]
EntityTick 35%. 
Check timings: https://timings.aikar.co/?id=6b1bef3e04c64e0e8af98cbe6558bc4b

Pls optimize mobs. Mobs are a very heavy load on the server, and the server drops to 10 TPS.

PaperSpigot: 226 version

**Comment by clrxbl** [comment]
Zombies are taking 20% ticks on that timings report, see if you have a farm somewhere. Limit farms with FarmLimiter.

**Comment by TheKlimoT** [comment]
> 
> 
> Zombies are taking 20% ticks on that timings report, see if you have a farm somewhere. Limit farms with FarmLimiter.

Everything is already limited, I have done less spawnrate everywhere, lags do not go away, FarmLimiter is worth it.

**Comment by TheKlimoT** [comment]
`# Plugin created by filoghost. All rights reserved.
# Redistribution of this product is forbidden.

# How often to check mob farms in seconds.
check-interval: 300

broadcast:
  enable: true
  message: '&8[&6SKOLOT.FUN&8]&b Убито &e{amount} &bлишних животных.'
  # How many entities should be removed at minimum to broadcast the message.
  minimum: 1

rules:
# A global rule active on all the worlds, for groups of 50+ entities.
- entities: all
  exclude: villager
  worlds: all
  distance: 3
  max-amount: 10
# A rule to avoid friendly mob farms, limit the mobs amount to 25.
- entities: pig, cow, sheep, chicken
  worlds: all
  distance: 5
  max-amount: 10
# A rule for spawner grinders, max of 10 mobs of the same type in the same block.
- entities: zombie, skeleton, spider, cave spider
  worlds: all
  distance: 1
  max-amount: 10

extra:
  # The rate of mobs that will successfully spawn from a nether portal.
  # Setting to 0% disables mobs spawning from portals.
  portal-spawn-rate: '100%'
  # Whether to exclude tamed entities or not
  exclude-tamed: true
  # Whether to exclude entities with a name tag or not
  exclude-nametagged: false`

**Comment by TheKlimoT** [comment]
> # Plugin created by filoghost. All rights reserved.
# Redistribution of this product is forbidden.

# How often to check mob farms in seconds.
check-interval: 300

broadcast:
  enable: true
  message: '&8[&6SKOLOT.FUN&8]&b Убито &e{amount} &bлишних животных.'
  # How many entities should be removed at minimum to broadcast the message.
  minimum: 1

rules:
# A global rule active on all the worlds, for groups of 50+ entities.
- entities: all
  exclude: villager
  worlds: all
  distance: 3
  max-amount: 10
# A rule to avoid friendly mob farms, limit the mobs amount to 25.
- entities: pig, cow, sheep, chicken
  worlds: all
  distance: 5
  max-amount: 10
# A rule for spawner grinders, max of 10 mobs of the same type in the same block.
- entities: zombie, skeleton, spider, cave spider
  worlds: all
  distance: 1
  max-amount: 10

extra:
  # The rate of mobs that will successfully spawn from a nether portal.
  # Setting to 0% disables mobs spawning from portals.
  portal-spawn-rate: '100%'
  # Whether to exclude tamed entities or not
  exclude-tamed: true
  # Whether to exclude entities with a name tag or not
  exclude-nametagged: false

**Comment by TheKlimoT** [comment]
Plugin created by filoghost. All rights reserved.
Redistribution of this product is forbidden.

How often to check mob farms in seconds.
check-interval: 300

broadcast:
  enable: true
  message: '&8[&6SKOLOT.FUN&8]&b Убито &e{amount} &bлишних животных.'
  # How many entities should be removed at minimum to broadcast the message.
  minimum: 1

rules:
A global rule active on all the worlds, for groups of 50+ entities.
- entities: all
  exclude: villager
  worlds: all
  distance: 3
  max-amount: 10
A rule to avoid friendly mob farms, limit the mobs amount to 25.
- entities: pig, cow, sheep, chicken
  worlds: all
  distance: 5
  max-amount: 10
A rule for spawner grinders, max of 10 mobs of the same type in the same block.
- entities: zombie, skeleton, spider, cave spider
  worlds: all
  distance: 1
  max-amount: 10

extra:
  The rate of mobs that will successfully spawn from a nether portal.
  Setting to 0% disables mobs spawning from portals.
  portal-spawn-rate: '100%'
  Whether to exclude tamed entities or not
  exclude-tamed: true
  Whether to exclude entities with a name tag or not
  exclude-nametagged: false

**Comment by Proximyst** [comment]
We optimise mobs anywhere we can. The only real solution to not lagging by sheer amount of mobs is to reduce it. Closing as this is not specific enough to be an actual issue; we'll optimise anything we come over when we do.
