### ISSUE TITLE
Named mob despawning

### ISSUE THREAD

**Issue by jontyms** [PaperMC/Paper#3246]
### What behaviour is expected:
___What you expected to see___
Named zombie does not despawn
### What behaviour is observed:
___What you actually saw___
Consistently a named zombie will despawn after reloading chunks and/or restating the server
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
1.name zombie
2.unload chunk

### Plugin list:
___A list of your plugins___
Plugins (15): AdvancedBan*, ChatControl, CoreProtect, DiscordSRV, dynmap*, Harbor, LuckPerms, Matrix, PlaceholderAPI, ProtocolLib, StaffPlus, TAB, Vault, ViaBackwards, ViaVersion
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___266

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Trigary** [comment]
I remember seeing a similar issue. Can you reproduce this without plugins?

**Comment by zachthedev** [comment]
I just got word from one of my players that they experienced the same issue today. I haven't been able to reproduce it yet.
Running version: git-Paper-217
Plugins:  ChatItem, LuckPerms, OpenInv, ProtocolLib, ServerListPlus*, SpectatorMode, SuperVanish, TabList, WorldEdit

**Comment by jontyms** [comment]
A zombie with boots did not despawn

**Comment by lordgecko27** [comment]
Having the same issue here. Various players report that they have experienced this, also with other mobs.
Running version: git-Paper-282 (MC: 1.15.2)

**Comment by electronicboy** [comment]
Duplicate of #3157
