### ISSUE TITLE
Clone command blocks are not triggered correctly

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#3247]
How to reproduce:
- Create a chain of two Command blocks:
1st command in the first cmb C1 (normal, needs redstone, unconditional): clone for an area of about 1000 blocks
2nd command in the second CMB C2 (chain, always active, unconditional): Does not matter, e.g. setblock
- The command block C1 is powered by a redstone block via a third CMB (/setblock) or by setting a redstone block by hand

Result:
The redstoneblock triggered cmb's (both C1 and C2) are not reliably executed.
An additional observer at the place where the redstoneblock is placed shows that there is always a mechanical block update => the observer is always triggered and turns on a lamp.
Evidently the impulse for CMBs to execute at constant environmental conditions is sometimes missing.

Other conditions:
- Paper 1.15.2 - 226 
- the error also occurs if `use-faster-owncraft-redstone` and `use-optimized-ticklist` are set to` false`
- the error occurs independently of worlds
- the error also occurs when the TPS variations are as good as 0 and only one test person is online
- the error does not occur in the singleplayer
- the problem also occurs when all plugins except Worldguard (7.0.3-SNAPSHOT;2033-5e7829c), Worldedit (4990) and Multiverse (4.1.0-b775) are disabled
- the bug only affects version 1.15.2, in older versions (1.13.2) it does not occur

Note:
The bug is quite annoying, as many useful small command block based features rely on a simple clone command in a chain. I am grateful for any hint that could help to solve the problem!

**Comment by aikar** [comment]
This is same issue as https://github.com/PaperMC/Paper/issues/3145
Please follow that issue

**Comment by TheoRetisch1** [comment]
Thanks for the quick investigation!

**Comment by TheoRetisch1** [comment]
A concretization: It only happens when the command blocks are in a chain.

**Comment by TheoRetisch1** [comment]
Could we please reopen this ticket, I still have this specific bug, even with the fixed FAWE version 195 or using "default" Worldedit :/

**Comment by aikar** [comment]
We still have another open ticket in this area: https://github.com/PaperMC/Paper/issues/3251

Follow that now for any updates.

**Comment by TheoRetisch1** [comment]
Uhm the bug is no longer of interest, it was due to FAWE. As soon as the FAWE tick-limiter is deactivated it works. But why did I claim stiffly and firmly that it also occurs without plugins and with normal Worldedit? Well you had to update the redstone manually in many places ... well, I'm sorry for the inconvenience xD.

**Comment by aikar** [comment]
Wtf FAWE added a tick limiter? FFS.... STOP IT
