### ISSUE TITLE
Restart script not running on watchdog stop

### ISSUE THREAD

**Issue by mathiascode** [PaperMC/Paper#3248]
### What behaviour is expected:
The server should run the restart script when the watchdog attempts to stop the server.

### What behaviour is observed:
The script doesn't seem to run. Instead, the server skips directly to the shutdown phase.

### Steps/models to reproduce:
1. Download FastAsyncWorldEdit (https://github.com/IntellectualSites/FastAsyncWorldEdit)
2. Run the following command: //sphere oak_sign 75
3. The server will lag. When the watchdog eventually tries to stop the server, the restart script isn't executed. The server hangs indefinitely (although this is a different issue).

### Plugin list:
FastAsyncWorldEdit

### Paper build number:
226

### Anything else:
Downgrading to a build that doesn't include https://github.com/PaperMC/Paper/blob/842e040c19567ea7682c288f2ed6a72ba52354a7/Spigot-Server-Patches/0468-Forced-Watchdog-Crash-support-and-Improve-Async-Shut.patch brings back restart script functionality.

**Comment by aikar** [comment]
You need to provide logs, but if its stuck in shutdown, then yes it makes sense restart isn't running.

also need what is your start method, spigot.yml config?

Using /bin/sh?

Finally, we also really do not recommend using the restart script. It's not the best solution for it. A bash start script with a while loop is more reliable.

**Comment by mathiascode** [comment]
Log from latest build: https://pastebin.com/R7bVC6Kz
Log from older build: https://pastebin.com/MPKUZicV

spigot.yml:
```
# This is the main configuration file for Spigot.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# For a reference for any variable inside this file, check out the Spigot wiki at
# http://www.spigotmc.org/wiki/spigot-configuration/
# 
# If you need help with the configuration or have any questions related to Spigot,
# join us at the IRC or drop by our forums and leave a post.
# 
# IRC: #spigot @ irc.spi.gt ( http://www.spigotmc.org/pages/irc/ )
# Forums: http://www.spigotmc.org/

config-version: 12
settings:
  log-villager-deaths: true
  debug: false
  save-user-cache-on-stop-only: false
  sample-count: 12
  bungeecord: false
  player-shuffle: 0
  user-cache-size: 1000
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-multiplier: 10.0
  timeout-time: 60
  restart-on-crash: true
  restart-script: ./stop.sh
  netty-threads: 4
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
messages:
  whitelist: You are not whitelisted on this server!
  unknown-command: Unknown command. Type "/help" for help.
  server-full: The server is full!
  outdated-client: Outdated client! Please use {0}
  outdated-server: Outdated server! I'm still on {0}
  restart: Server is restarting
commands:
  spam-exclusions:
  - /skill
  silent-commandblock-console: false
  replace-commands:
  - setblock
  - summon
  - testforblock
  - tellraw
  log: true
  tab-complete: 0
  send-namespaced: true
advancements:
  disable-saving: false
  disabled:
  - minecraft:story/disabled
stats:
  disable-saving: false
  forced-stats: {}
world-settings:
  default:
    seed-endcity: 10387313
    trident-despawn-rate: 1200
    verbose: true
    mob-spawn-range: 8
    hopper-amount: 1
    dragon-death-sound-radius: 0
    seed-village: 10387312
    seed-desert: 14357617
    seed-igloo: 14357618
    seed-jungle: 14357619
    seed-swamp: 14357620
    seed-monument: 10387313
    seed-shipwreck: 165745295
    seed-ocean: 14357621
    seed-outpost: 165745296
    seed-slime: 987234911
    max-tnt-per-tick: 100
    view-distance: default
    enable-zombie-pigmen-portal-spawns: true
    item-despawn-rate: 6000
    arrow-despawn-rate: 1200
    wither-spawn-sound-radius: 0
    hanging-tick-frequency: 100
    zombie-aggressive-towards-villager: true
    nerf-spawner-mobs: false
    max-entity-collisions: 8
    merge-radius:
      exp: 3.0
      item: 2.5
    growth:
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      beetroot-modifier: 100
      carrot-modifier: 100
      potato-modifier: 100
      wheat-modifier: 100
      netherwart-modifier: 100
      vine-modifier: 100
      cocoa-modifier: 100
      bamboo-modifier: 100
      sweetberry-modifier: 100
      kelp-modifier: 100
    entity-activation-range:
      water: 16
      villagers: 32
      flying-monsters: 32
      animals: 32
      monsters: 32
      raiders: 48
      misc: 16
      tick-inactive-villagers: true
      wake-up-inactive:
        animals-max-per-tick: 4
        animals-every: 1200
        animals-for: 100
        monsters-max-per-tick: 8
        monsters-every: 400
        monsters-for: 100
        villagers-max-per-tick: 4
        villagers-every: 300
        villagers-for: 100
        flying-monsters-max-per-tick: 8
        flying-monsters-every: 200
        flying-monsters-for: 100
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
    ticks-per:
      hopper-transfer: 8
      hopper-check: 1
    hunger:
      jump-walk-exhaustion: 0.05
      jump-sprint-exhaustion: 0.2
      combat-exhaustion: 0.1
      regen-exhaustion: 6.0
      swim-multiplier: 0.01
      sprint-multiplier: 0.1
      other-multiplier: 0.0
    max-tick-time:
      tile: 50
      entity: 50
    squid-spawn-range:
      min: 45.0
  worldeditregentempworld:
    verbose: false
```

stop.sh:
```
#/bin/sh
pkill -9 java
```

I'm already running the server in a while loop, but the restart script is a failsafe for shutting down the server in case it hangs (yes, dirty hack, but it has worked good enough).

**Comment by aikar** [comment]
that was a misuse of the restart script....

Ultimately you were relying on the fact it was entirely broken before, and now its fixed.

This patch fixed the intended behavior of restart script, but we still don't recommend using it.

what I would suggest for doing what you are trying to do here is to use a plugin that uses the paper API Bukkit.isStopping() during Plugin onDisable(), and starts a thread with a timeout that does System.exit(1) after the timeout.

Your old log shows that it was killing your process at VERY dangerous times during the saving process, which was very likely to corrupt your data.

If your ok with that risk, then you're going to need to handle this with a plugin instead. We're not going to be able to break restart script to support a misuse of it sorry.

**Comment by mathiascode** [comment]
Thank you for clarifying. I'll look into alternative methods.
