### ISSUE TITLE
Hoppers not working?

### ISSUE THREAD

**Issue by disgusdad** [PaperMC/Paper#3249]
Hoppers not feeding into object [composter, brewery, etc...]
Existing world 1.15.2

Plugins:
EssentialsX
LuckPerms
Vault

Version:
226 but noticed the issue a few releases ago.

**Comment by darbyjack** [comment]
Try to replicate without plugins.

**Comment by disgusdad** [comment]
Appears not related to paper. reinstall of minecraft fixed issue.
