### ISSUE TITLE
(1.8.8) Startup error, no color in console

### ISSUE THREAD

**Issue by amadeusmz** [PaperMC/Paper#325]
**The following are 'hard suggestions': if you have the information
available to you, you really should put it in the report. Choose one of
the following templates from below that best fits the issue you wish to
report.**
# Incompatibility (Bug)
### Description of issue:

I get this error everytime I starts the server
http://pastebin.com/W9fBPx1M
And the console don't have color when the server running, and it's difficult to type commands in the console.
I've tried everything, like installing Visual C++ 2008 (x86) or 2010 (x64)
This issue doesn't happen in other spigot or paperspigot builds.
I'm sorry if 1.8.8 is no longer supported, but I need this to get fixed as I can't update to 1.9 for some reasons.
### Plugin list:

No plugins
### bukkit.yml, spigot.yml, paper.yml, server.properties

All are default
### Paper build number:

Build 443 (1.8.8 final)
CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8R0.1-SNAPSHOT)

Windows Server 2008 64 bits and Windows 7 64 bits, With Java 8.

**Comment by zachbr** [comment]
We do not accept issues for 1.8.8 anymore.

**Comment by amadeusmz** [comment]
Please help, just tell me which commit was this issue fixed so I can decompile the original class and solve it myself.

**Comment by zachbr** [comment]
I have no idea. I wasn't even aware it had issues in 1.8.8 until late last night.

But with it being both unsupported and Windows only, we really aren't interested in messing with it. Try bugging TacoSpigot and seeing what they know. I think they still support 1.8.8.
