### ISSUE TITLE
Add support for createVanillaChunkData

### ISSUE THREAD

**Issue by Pangamma** [PaperMC/Paper#3250]
Related to: https://github.com/PaperMC/Paper/pull/1846/files
Specifically, 
`
` public ChunkData createVanillaChunkData(World world, int x, int z) {
`
`        return Bukkit.getServer().createVanillaChunkData(world, x, z);
` }
`

**Describe the solution you'd like**
I would like to be able to use this function call to create a chunk using the default vanilla chunk generator before processing it using a custom chunk generator that wraps it. 

**Describe alternatives you've considered**
I've tried to replicate the vanilla chunk generation but it was tightly tangled with like 24 files... I've tried chunk populators, but trees and structures on the edges of chunks cause issues. I've tried looking into NMS code to instantiate a default chunk generator. Again- everything is super tightly coupled.

@MiniDigger

**Comment by Chew** [comment]
This was implemented in #3252 but didn't actually close, enjoy!
