### ISSUE TITLE
Implement triggered skeleton horse trap sound radius

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#3254]
**Is your feature request related to a problem? Please describe.**
When playes triggers a Skeleton Horse trap, thunder sound is played for all online players...

**Describe the solution you'd like**
Implement an option like wither spawn sound radius and dragon death sound radius to configure the radius in blocks.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by aeonlamb** [comment]
This is already configurable, in paper.yml. Check the "lightning-strike-distance-limit" settings. Keep in mind this controls how far away you need to be to hear any and all thunder, not just the lightning strike from a skeleton horse trap, but that's hardly an issue if you ask me.
