### ISSUE TITLE
Mob dropping Problem

### ISSUE THREAD

**Issue by coco0325** [PaperMC/Paper#3255]
Plugin code:
public void onDamage(EntityDeathEvent e) {
     if(e.getEntity() instanceof IronGolem){
          e.getDrops().add(ITEM);
     }
}
### What behaviour is expected:
ITEM dropped every time the iron golem die.

### What behaviour is observed:
ITEM only drop at first death.

### Anything else:
Paper#227,220 have this problem, but Paper#211 doesn't.

**Comment by aikar** [comment]
yeah I know what the issue is here. You can mitigate this for now by doing item.clone() (which is a safer thing to do anyways)
