### ISSUE TITLE
Pillager increasing server load

### ISSUE THREAD

**Issue by Sylensky** [PaperMC/Paper#3259]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___
https://timings.aikar.co/?id=1e7804f2e64d4c12819a1f08d1c862a2

### Description of issue:
___If applicable___
I recently noticed that everytime a player find a fortress from the pillagers that the cpu usage drives up and slows down the server overall.
### Plugin list:
___All plugins running on the server___
a screenshot is more applicable on this part since its a lot to write down, sorry about this.
![image](https://user-images.githubusercontent.com/57076968/80643822-02b77c80-8a69-11ea-88fa-5c6b1e32ba4c.png)

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___

[settings.zip](https://github.com/PaperMC/Paper/files/4554464/settings.zip)

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___
I dont know what else i should attach sorry for the inconvenience.
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-62 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Update, entity performance is far from amazing, but running months old software hardly helps anything
