### ISSUE TITLE
insane server load on account switch

### ISSUE THREAD

**Issue by Sylensky** [PaperMC/Paper#3260]
### What behaviour is expected:
___What you expected to see___
My server is running in offline mode which means cracked players can also join the server. Therefor if a player buys minecraft he obviously wants to use the same account he already had on the server. The point now is when he tries to connect with almost the same username something is getting messed up and he can't write anything in the chat. All that i can notice is that the cpu usage is going up to almost 100% on all cores. 
Maybe i should state that i got a bungeecord network. The behaviour occurs on one server of the network once he logged in and tries to chat. If i kill that server and let it start again, the cpu usage seems to stay fine. 
### What behaviour is observed:
___What you actually saw___
So in detail this happened:
Player aka "test" is a cracked user that plays on my network.
Now he decides to buy minecraft and thought of the idea to name him "TesT" as an example.
Then he tries to get into the network again and firstly all seems fine until he tries to send a message into the chat. 
Only way to resolve that issue was to complete remove both users from the database and registering only one them again. 

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Using a cracked account that sound very similiar like a premium minecraft account. 
The cracked account should have played some time on the server to gain data about him. 
Cracked user logs out and premium user logs in. Observe the incoming cpu load.

### Plugin list:
___A list of your plugins___
![image](https://user-images.githubusercontent.com/57076968/80645417-5fb43200-8a6b-11ea-9afd-21600eaa6628.png)

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-62 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___
I dont have much to attach because i couldn't get online in time to capture timings as it happened. Best i can give is this timings where it was like an hour into it.
https://timings.aikar.co/?id=5fc919a331d74d4fbcdceb91b4e73294

**Comment by electronicboy** [comment]
Issues due to running in a cracked server are 100% on you, nor are you even running a supported version
