### ISSUE TITLE
Commodore trying to convert any commands prevents use of newer java feature

### ISSUE THREAD

**Issue by DRSchlaubi** [PaperMC/Paper#3262]
### What behaviour is expected:
The plugin loads normally

### What behaviour is observed:
When spigot tries to load classes that use newer java (records in my case) features it throws an exception 

### Steps/models to reproduce:
Try to use any java 9+ feature in a plugin (I tried records)

### Plugin list:
Only my test plugin is on the server

### Paper build number:
```
[12:03:07 INFO]: This server is running Paper version git-Paper-227 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[12:03:08 INFO]: Previous version: git-Paper-243 (MC: 1.14.4)
[12:03:08 INFO]: You are running the latest version
```

### Anything else:
Stacktrace: https://hasteb.in/quculope.rb

**Comment by MiniDigger** [comment]
Basically, bukkits stupid material combat rewriting is always needed, even on modern plugins, since it also rewrites material values and stuff to not return legacy materials.

That rewriting happens with asm and Lang level set to 7. I'll try to bump that and see how that goes after work.

(This is still the case on 1.15, op is using 1.14)

**Comment by MiniDigger** [comment]
this is some fine bullshit
using ASM7 -> "This feature requires ASM8_EXPERIMENTAL" on my plugin
using ASM8_EXPERIMENTAL -> "ASM8_EXPERIMENTAL can only be used by classes compiled with --enable-preview" on other plugins

**Comment by DRSchlaubi** [comment]
Update asm from 7.3.1 (or whathever currently is used) to ask 8.0.1 then you can use Opcodes.ASM8

**Comment by MiniDigger** [comment]
yeah, really, its not that easy. check #paper-dev, am not repeating my rant here

**Comment by zachbr** [comment]
Thanks for the PR mini. I’ll get that merged when I get home if no one beats me to it.

I would generally caution you against using preview features (records are still a preview feature even in Java 14) while this stupid legacy system exists. While it was easy to fix this time, there is no guarantee that it will be in the future. We will make a best-effort attempt to support what we can but it’s never guaranteed depending on the specific preview feature.

Now maybe once the legacy system goes away it’ll be a different story. Personally I look forward to that day.

Edit: Actually, I’m trying to figure out how your use of records triggered this but some of mine in some test plugins didn’t. 🤔 Well, happy to bump ASM regardless. It needs done.

**Comment by Paul1365972** [comment]
Is there a reason why we only bump ASM in Server and not API? I am asking, because it just caused a version conflict in project

**Comment by electronicboy** [comment]
That's just where it was needed to work, but yea, API needs doing too

**Comment by Paul1365972** [comment]
Should i open a separate issue and/or pull rq for this?
