### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3267]
### What behaviour is observed:
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: Current Thread: Server thread
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: PID: 23 | Suspended: false | Native: false | State: RUNNABLE
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: Stack:
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: net.minecraft.server.v1_15_R1.MCUtil.getCoordinateKey(MCUtil.java:71)
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: com.destroystokyo.paper.server.ticklist.PaperTickList.addToNotTickingReady(PaperTickList.java:118)
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: com.destroystokyo.paper.server.ticklist.PaperTickList.queueEntryForTick(PaperTickList.java:112)
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: com.destroystokyo.paper.server.ticklist.PaperTickList.prepare(PaperTickList.java:259)
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:277)
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: net.minecraft.server.v1_15_R1.TickListServer.b(TickListServer.java:46)
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:441)
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1303)
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157)
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
30.04 12:13:22 [Server] Startup [16:13:22 ERROR]: java.lang.Thread.run(Thread.java:748)

### Paper build number:
v227

**Comment by electronicboy** [comment]
We need the *full* log, not a snippet

**Comment by aikar** [comment]
You conveniently cut off the part that says "DO NOT REPORT THIS TO PAPER" too....

Your server is running slow. this is just telling you that.
