### ISSUE TITLE
Iron farm won't work because of spawning

### ISSUE THREAD

**Issue by CakeKD1** [PaperMC/Paper#3268]
### What behaviour is expected:
___Zombie comes around and stress the villagers into spawning an iron golem___

### What behaviour is observed:
___Zombie comes around and stress the villagers, but iron golem doesn't spawn___

### Steps/models to reproduce:
___https://streamable.com/0b4yut___

### Plugin list:
___Chunkmaster, DynMap, OpenInv, ProtocolLib, SuperVanish, WorldBorder, WorldEdit___

### Paper build number:
___git-paper-"5ab48ad9"___

### Anything else:
___The farm was made by Gnembon: https://www.youtube.com/watch?v=vMSiholH_lc___

**Comment by BillyGalbreath** [comment]
> git-paper-"5ab48ad9

Try downloading an official build

**Comment by kekePower** [comment]
I'm the server admin and have been compiling Paper from git for a while.

Official build has been installed now and I'm now waiting for feedback from @CakeKD1

**Comment by Marcelo-Petrucelli** [comment]
Would this be related to #2959 ?

**Comment by aikar** [comment]
Please keep discussion on a single issue, such as the one linked #2959 
But I made more improvements today, so latest paper should hopefully help.
