### ISSUE TITLE
0465-Remove-streams-from-Mob-AI-System.patch causes plugin incompatibility for many pets plugins, AI

### ISSUE THREAD

**Issue by NickkTMD** [PaperMC/Paper#3269]
### What behaviour is expected:
Plugins like [Ultra Cosmetics](https://www.spigotmc.org/resources/1-8-to-1-15-ultra-cosmetics-opensource-free.10905/) and likely other plugins that modify mob path finding to work like they do on normal spigot.

### What behaviour is observed:
The plugin throws Field not found exceptions when trying to access field f in PathfinderGoalSelector class. This is due to 0465-Remove-streams-from-Mob-AI-System.patch renaming the EnumSet variable from 'f' to 'goalTypes'.

### Steps/models to reproduce:
Install and run any plugin that accesses the PathFinderGoalSelector EnumSet 'f' via Reflection.

### Paper build number:
 Paper version git-Paper-229 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
I believe this issue could be fixed by just changing the variable name back from 'goalTypes' to the original 'f'.

**Comment by Phoenix616** [comment]
They are using internals and not API so that stuff breaks is kinda expected. There is [an event](https://papermc.io/javadocs/paper/1.15/com/destroystokyo/paper/event/entity/EntityPathfindEvent.html) which handles Mobs trying to pathfind somewhere which can be used to cancel that attempt.

**Comment by NickkTMD** [comment]
Aren't all plugins written for Spigot supposed to work with Paper? I don't see any reason not to just change the variable back to f. it seems easier than expecting plugins to detect if they are running on a Paper or Spigot server and to use an event or NMS accordingly.

**Comment by yannicklamprecht** [comment]
No. Only plugins written against the Spigot-API are running on Paper out of the box. Th plugin you've problems with is written against implementation.

**Comment by electronicboy** [comment]
This is something I'll look into, tid more involved than just switching the field name back
Saying that, the only real guarantees are on API, we aim to ensure reasonable compatibility with NMS, however, there is no guarantees here, nor do we really have the ability to know what things plugins are messing with, especially when in a lot of cases field access is often pointless vs the methods already in these classes
