### ISSUE TITLE
/reload commands tab complete not work

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#3270]
### What behaviour is expected:
___What you expected to see___
/reload commands tab complete work

### What behaviour is observed:
___What you actually saw___
/reload commands tab complete not work
<img width="187" alt="Capture" src="https://user-images.githubusercontent.com/8324198/80771409-aa10de00-8b53-11ea-9d06-d3c1868a5ff7.PNG">

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Write /reload com and press tab.

### Plugin list:
___A list of your plugins___
None

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-224 (MC: 1.15.2)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by aikar** [comment]
Fixed in latest build
