### ISSUE TITLE
100% CPU usage on start up - powerful cpu

### ISSUE THREAD

**Issue by danielboos1** [PaperMC/Paper#3272]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___

### Description of issue:
___If applicable___
When starting the server my CPU usage usually goes to 100% considering that I have a 8 thread 4 cores CPU running at 3.9ghz is insane to be honest. Also it takes a while to start up for me
### Plugin list:
___All plugins running on the server___
Metrix anti cheat
Geysermc
Protocollib
### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
226

**Comment by paul0665** [comment]
I think this is normal, server need time to start up.

All of my server will do that too.

**Comment by pop4959** [comment]
Do you have any comparison to make with older versions of Paper? I don't see any regressions.

paper-143: `[01:28:23 INFO]: Done (8.722s)! For help, type "help"`

paper-229: `[01:29:35 INFO]: Done (1.588s)! For help, type "help"`

![image](https://user-images.githubusercontent.com/17698576/80793187-4c789380-8b4b-11ea-9c23-65409e828184.png)

**Comment by aikar** [comment]
Working as intended. Mojang has to build data fixers at startup which is extremely resource intensive and uses all threads.
then loading spawn chunks again uses a nice burst.

Nothing can be done about this

**Comment by danielboos1** [comment]
cant you build data fixers once then cache them?  this was a nice example showing that even on one of the most powerful CPUs it hits 100%
> ![image](https://user-images.githubusercontent.com/17698576/80793187-4c789380-8b4b-11ea-9c23-65409e828184.png)

**Comment by paul0665** [comment]
The high usage for short time shouldn't effect anything. If you still want it, you can try docker.

**Comment by aikar** [comment]
It is not possible to cache them no.
If you want to analyze the code and make some suggestions to mojang, the code is here: https://github.com/Mojang/DataFixerUpper
