### ISSUE TITLE
[MC 1.15.2] Player#setWalkSpeed() with negative value doesn't work

### ISSUE THREAD

**Issue by Roggnar** [PaperMC/Paper#3273]
### What behaviour is expected:
Negative value should reverse directions

### What behaviour is observed:
This has the same effect as setting the walk speed to 0

### Steps/models to reproduce:
Just use the method Player#setWalkSpeed(float args) with values between - 1 and 0

### Paper build number:
Version: git-Paper-228

### Anything else:
When using setFlySpeed with negative value, the directions are reversed

**Comment by Roggnar** [comment]
Also when chosing a value between 0 and 1, the walk speed is correctly adjusted

**Comment by mikroskeem** [comment]
Does negative walk speed even work with vanilla? If it doesn't then nothing for Paper to do here.

**Comment by aikar** [comment]
It's likely the fly speed behavior is a bug / quirk of impl, and not intended design. 

Not sure this should be supported.

**Comment by Roggnar** [comment]
Ah ok, it's too bad. Thanks for the reply
