### ISSUE TITLE
Factions UUID incompatibility?

### ISSUE THREAD

**Issue by reverendjesus** [PaperMC/Paper#3275]
### What behaviour is expected:
A faction being created.

### What behaviour is observed:
[this error](https://pastebin.com/NuLJx9bC)

### Steps/models to reproduce:
issue the command /f create

### Plugin list:
___A list of your plugins___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Proximyst** [comment]
https://github.com/drtshock/Factions/issues report here...

**Comment by aikar** [comment]
Please report to the appropriate place.
