### ISSUE TITLE
Middle click in survival = kicked

### ISSUE THREAD

**Issue by PapiCapi** [PaperMC/Paper#3277]
### What behaviour is expected:
___What you expected to see___
Giving to the player in main hand the item middle clicked 

### What behaviour is observed:
___What you actually saw___
It is kicking the player when he is in survival mode and middle clicking at a block he has in his inventory.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Set yourself in survival
Middle click a block you have in your inventory

### Plugin list:
___A list of your plugins___
 AdvancedAchievements, AntiAFK*, AntiDecoCombat*, AreaShop, ASReplace*, AsyncWorldEdit, Bank, BlockLocker, ChatItem, ChestCommands, ChestShop, ChestShop-LegacyIds, Core, CoreProtect, CrazyCrates, DabCore*, DeACoudre*, dynmap*, Dynmap-Essentials*, Dynmap-WorldGuard*, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, ExtendViewDistance, FarmLimiter, Fe*, Grades, HolographicDisplays, IllegalStack, Insights, Jobs, KeepItems*, Lift, LuckPerms, MinewebBridge*, ModReq*, MoncubeCore, Multiverse-Core, MyPet, OnTime*, OpenInv, PlayerHeads, PlugMan, ProtocolLib, ProtocolSupport, Realistic_World, Shopkeepers, SkQuery, Skript, TAB, TokenManager, Vault, VillesSemi*, VoidGenerator, VoteMoncube, VoxelSniper*, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, XrayInformer*, XuanCatAPI

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-234 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

This is what appends when trying to get an item with the above method 👍 
[11:59:54 WARN]: Ogust1 tried to set an invalid carried item
[11:59:54 INFO]: Ogust1 lost connection: Invalid hotbar selection (Hacking?)
[11:59:54 INFO]: [Bank] Saving Bank for d6692bb7-c977-4ed7-b4c4-bd6fb38c2089 with SQLLiteLoader
[11:59:55 INFO]: [-] Ogust1
[11:59:55 WARN]: handleDisconnection() called twice

**Comment by plebexer** [comment]
Same happens to me

**Comment by danny6167** [comment]
I reproduced this on a fresh, no-plugin, default config paper server running 234.
Doesn't kick if the item is in one of your other hotbar slots, only if it has to pull from inventory.

**Comment by danny6167** [comment]
Use build 232 until they fix the patch that caused this.
Seems this patch assumed that items can only come from the hot bar when checking for valid item slot position - https://github.com/PaperMC/Paper/commit/85fb00152a83107d3635b30a6aa0ef7eb22f9931

**Comment by 20BBrown14** [comment]
Same is  happening on my server with version 1.15.2-R0.1-SNAPSHOT

**Comment by NotGeri** [comment]
Same deal happening on b234 1.15.2

**Comment by paul-maxime** [comment]
Confirmed fixed in build 235.
