### ISSUE TITLE
paper 233 and up kicks player when using pick block

### ISSUE THREAD

**Issue by diablo050189** [PaperMC/Paper#3278]
### What behaviour is expected:
When using pick block, highlighted hotbar slot should fill with item looking at from inventory.

### What behaviour is observed:
When using pick block, game kicks user for "Invalid Hotbar Selection(Hacking?)" 

### Steps/models to reproduce:
Launch server with build 233 or later and try to use pick block.

### Plugin list:
NoMobGriefing
SimpleSpawn
SinglePlayerSleep
Worldedit
Luckperms

### Paper build number:
This server is running Paper version git-Paper-234 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
I used a backup that was on 232 and pick block works just fine but 233 and up pick block just kicks the user. Her is what log says when a user is kicked:
[09:04:01 WARN]: [player] tried to set an invalid carried item
[09:04:01 INFO]: [player] lost connection: Invalid hotbar selection (Hacking?)
[09:04:01 INFO]: §e[player] left the game
[09:04:01 WARN]: handleDisconnection() called twice

**Comment by wizjany** [comment]
#3277
