### ISSUE TITLE
Lag spikes when entering specific chunks

### ISSUE THREAD

**Issue by aerteis** [PaperMC/Paper#3279]
###  Timings or Profile link:

https://timings.aikar.co/?id=5b833970533244488b89afcb22080c18

### Description of issue:
I'm facing such a weird problem since yesterday: I have lag spikes (micro freezes) when I enter some chunks and it does the same for a friend (but for the same chunks even after reboot)

I have a constant 20 TPS with the Aikar flags on Java 11 with the 1.15.2 version of paper (build 192, I also tried with the last one) and 6GB of ram allocated

Here is the server configuration (old gaming PC): 8 GB, i5-4570 @ 3.20 Ghz with a SSD

The problem seems to come from the map that I'm importing (https://www.minecraft-france.fr/map-downstream-survival-games-1-7-5/) since when I let the server generate one, I have no lag spikes even when generating many new chunks...

I tried to import part of the map into a new world with mcedit, but same problem.

### Plugin list:

No plugin (I tested by deactivating them, which explains why you can see them in the timings)

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml : https://pastebin.com/CFaPnqLj
spigot.yml : https://pastebin.com/1z8ihzNF
paper.yml : https://pastebin.com/Y0cadeSh
server.properties : https://pastebin.com/PQ9rW3b6

### Other helpful links
Here's a screen where you can see the micro freeze when I get into a chunk : https://imgur.com/a/DIFhHwY

**Comment by electronicboy** [comment]
Well known vanilla issue at this point, nor is it anything to do with the server
