### ISSUE TITLE
ChunkIOExecutor::syncChunkLoad MCUtil.ensureMain?

### ISSUE THREAD

**Issue by Qveshn** [PaperMC/Paper#3284]
Hi
I have a problem with Paper while loading chunks in another thread.
Currently I have tested it only on 1.12.2 (paperclip-1618.jar). But I think this occurs in other versions.

The problem:

I use World::getChunkAt.
My plugin works perfectly with CraftBukkit and Spigot servers, but not with Paper.
    
Paper prints stack trace like:

    [04:51:04 WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
    [04:51:04 WARN]:        at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:54)
    [04:51:04 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
    [04:51:04 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:170)
    [04:51:04 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:153)
    [04:51:04 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
    [04:51:04 WARN]:        at net.minecraft.server.v1_12_R1.World.getChunkAt(World.java:357)

Paper uses MCUtil.ensureMain to warn and execute instance.getSkipQueue in main thread queue.

    package org.bukkit.craftbukkit.v1_12_R1.chunkio;
    ...
    public class ChunkIOExecutor {
    ...
        private static final AsynchronousExecutor<QueuedChunk, Chunk, Runnable, RuntimeException> instance;
    ...    
        public static Chunk syncChunkLoad(World world, ChunkRegionLoader loader, ChunkProviderServer provider, int x, int z) {
            return (Chunk)MCUtil.ensureMain("Async Chunk Load", () -> {
                return (Chunk)instance.getSkipQueue(new QueuedChunk(x, z, loader, world, provider));
            });
        }
I wonder why Paper does it.
Method instance.getSkipQueue uses mechanics to allow loading chuncks from another thread.
So, it should work perfectly without any MCUtil.ensureMain.

Is it possible to remove async check there?

**Comment by aikar** [comment]
Because you're doing something extremely horrible and bad and need to fix it. Paper is protecting server owners from your mistake.

Do not use getChunkAt off of main thread. 
That's beyond the fact 1.12 is also not supported, but the issue here is not relevant to your version, you need to fix your code, and ensure you only access chunks from main thread.

**Comment by aikar** [comment]
Also, the impl has thread safety to ensure that its own management of state is safe.

However, the action of loading a chunk off main is still in itself not safe. There is so much other state manipulation and post load callbacks that occur that are not safe to be ran asynchronously. 

This change ensures that all of the state manipulation occurs on main, and then plugins doing this still get their chunk to act on in unsafe ways, but we try our best to protect the worlds understanding of chunks at least. 

The hope is you are just reading the chunk and not manipulating which will avoid corruption at least.

If you are also manipulating then bad things will happen.

**Comment by Qveshn** [comment]
At first I want to thank you for reply.

I do not modify chunk data. I need chunk only to send packet to client.
All modifications I do in main thread.
My main goal is to change light in chunk. I do it in main thread. But player do not see it until I send him the packet  to update chunk.
To avoid lags I send packets in separate thread with fixed delay.

In 1.12 I do it as
```java
Chunk chunk = ((CraftWorld) world).getHandle().getChunkAt(chunkX, chunkZ);
PacketPlayOutMapChunk packet = new PacketPlayOutMapChunk(
	chunk, sectionsMaskSky | sectionsMaskBlock);
((CraftPlayer) player).getHandle().playerConnection.sendPacket(packet);
```
In 1.15 I do it as
```java
Chunk chunk = ((CraftWorld) world).getHandle().getChunkAt(chunkX, chunkZ);
PacketPlayOutLightUpdate packet = new PacketPlayOutLightUpdate(
	chunk.getPos(), chunk.e(), sectionsMaskSky, sectionsMaskBlock);
((CraftPlayer) player).getHandle().playerConnection.sendPacket(packet);
```
1.15 has another mechanics to load chunks. It uses CompletableFuture to load chunk from other thread. Therefore it works fine both in bukkit and paper.
But 1.12 uses syncChunkLoad and paper warns on other thread.

May be I need to collect chunks and keep them in main thread and then to use them while sending packets in other thread

Any way thanks for reply
😃

**Comment by x4e** [comment]
It doesnt matter whether you are not modifying the chunk, the simple act of loading a chunk causes a lot of stuff to trigger elsewhere, such that its not safe to do it asyncronously. You need to do this on the main thread.
