### ISSUE TITLE
Hopper states not changing with "use-faster-eigencraft-redstone" enabled

### ISSUE THREAD

**Issue by benkocik** [PaperMC/Paper#3285]
### What behaviour is expected:
Applying redstone signal to hopper changes hopper block state from "enabled: true" to "enabled: false"

### What behaviour is observed:
Applying redstone signal to hopper does not affect state.  Hopper state is always "enabled: true"

### Steps/models to reproduce:
1. In paper.yml set "use-faster-eigencraft-redstone" to "true"
`use-faster-eigencraft-redstone: true`
2. In game, apply redstone signal to hopper.
3. In game, using debug screen (F3) aim cross hair at hopper and observe "Target Block" info.

### Plugin list:
- BetterSleeping-2.6.2
- EssentialsX-2.17.2.0
- EssentialsXChat-2.17.2.0
- EssentialsXSpawn-2.17.2.0
- Timber+1.0.7
- VillagerOptimiser-1.1.2

### Paper build number:
git-Paper-240 (MC: 1.15.2)

### Anything else:
Setting "use-faster-eigencraft-redstone" to "false" fixes the problem.  
`use-faster-eigencraft-redstone: false`
From my understanding setting this true should not have any effect on vanilla redstone devices.

### Update:
After a few server restarts and updates it is found that this issue still occurs (with use-faster-eigencraft-redstone: false) so this might not entirely be related to the following setting.  Seems that this is a sporadic issue...
Update 2: More investigation showed to be a client issue, closed issue...

**Comment by nbastin** [comment]
I've seen this and I believe it's only a cosmetic issue - if the hopper state _needs_ to be updated (because it would otherwise act) it will change and act as expected.

Do you have an example of an instance where the hopper is actually behaving incorrectly, or are you also seeing this as only a cosmetic issue?
