### ISSUE TITLE
Twilight Forest dimension not created at first load on MC 1.12.2 with latest TF version

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [PaperMC/Paper#3287]
### What behaviour is expected:
Upon first starting the server with The Twilight Forest mod installed, its dimension should be created.

### What behaviour is observed:
A Twilight Forest dimension is not created, breaking the mod.

### Steps/models to reproduce:
1. Download a paperclip.jar compatible with MC 1.12.2
2. Download the latest version of The Twilight Forest
3. Start the server, then stop it
4. Delete the world folders
5. Copy the TF .jar to the mods folder
6. Start the server again
7. Start Minecraft and connect to 127.0.0.1

### Plugin list:
McMMO 1.5.08

### Paper build number:
git-paper-1618 (MC 1.12.2)

### Anything else:
N/A

**Comment by zachbr** [comment]
We do not provide support for 1.12.2 any longer.

**Comment by aikar** [comment]
nor do we support mods on any version. it sounds like a bug in that mod, consult with them.
Note that Paper is not Forge. We can not load mods.
