### ISSUE TITLE
dropping items fires interact event

### ISSUE THREAD

**Issue by MrBretze** [PaperMC/Paper#3289]
So we found an issue in another plugin, and after further testing realized this was a Spigot/CB issue.

The player interact event is fired when you drop an item, whilst not looking at a block (ie: looking up at the sky)
If you are focused on a block (where you can see the block's hitbox) the interact event will not fire.

(https://hub.spigotmc.org/jira/browse/PLUG-370 spigot issue)

@EventHandler
private void onClick(PlayerInteractEvent event) {
    Bukkit.broadcastMessage("Player interacted");
}

@EventHandler
private void onDrop(PlayerDropItemEvent event) {
    Bukkit.broadcastMessage("Player dropped");
}

Paper build 177 and 245

**Comment by zachbr** [comment]
Interact event is fired pretty much whenever the client sends the interact packet.
As mentioned in the Spigot ticket, the client now sends that packet when dropping an item.

We will not deviate from upstream to hack up a fix this.

**Comment by MrBretze** [comment]
Oh okay, sorry

**Comment by zachbr** [comment]
No need to apologize, it is a little weird, but it is what it is. :)
