### ISSUE TITLE
Teleport on carpet = death

### ISSUE THREAD

**Issue by TerranTitan01** [PaperMC/Paper#3290]
### What behaviour is expected: Teleport to the other person
___What you expected to see___

### What behaviour is observed: When a player requests to telport to another player while standing on carpet when the teleport is accepted and the player it teleported to the other player they fall out of the world and die.
___What you actually saw___

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list: AntiCreeper*, Autorank, CMI, CMIPaperLib, CoreProtect, DiscordSRV, DiscordSRV-Staff-Chat*, PlacerholderAPI, PluginLibrary, SimpleVoteListener, SpecializedCrates, Statz, Vault, NuVotifier, WorldEdit
___A list of your plugins___

### Paper build number: 244
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by bigfoot547** [comment]
It sounds like the Y coordinate is truncated, causing the player to be teleported INSIDE of the carpet instead of on top of it. I don't believe this is a problem with paper, and I remember essentials being notorious for truncating coordinates.

**Comment by TerranTitan01** [comment]
Ok so like how would i fix this?Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Bigfoot <notifications@github.com> Date: 5/8/20  12:54 AM  (GMT-06:00) To: PaperMC/Paper <Paper@noreply.github.com> Cc: TerranTitan01 <Tyler.walker2031@gmail.com>, Author <author@noreply.github.com> Subject: Re: [PaperMC/Paper] Teleport on carpet = death (#3290) 
It sounds like the Y coordinate is truncated, causing the player to be teleported INSIDE of the carpet. I don't believe this is a problem with paper.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PaperMC/Paper/issues/3290#issuecomment-625645009",
"url": "https://github.com/PaperMC/Paper/issues/3290#issuecomment-625645009",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Proximyst** [comment]
This is not a Paper bug. Go nag the author of the TPA plugin.

**Comment by ice-fly** [comment]
Not experiencing issues using latest paper-274 @TerranTitan01 can you confirm your issue is with /minecraft:tp ?
