### ISSUE TITLE
getAttackCooldown() creates an exception

### ISSUE THREAD

**Issue by WillFP** [PaperMC/Paper#3291]
Using getAttackCooldown on the latest version of paper 1.15.2 leads to this exception:
`java.lang.NoSuchMethodError: org.bukkit.entity.Player.getAttackCooldown()F`

**Comment by aikar** [comment]
Please post logs proving you are on the latest paper.

I see the method just fine there.

./src/main/java/org/bukkit/craftbukkit/entity/CraftHumanEntity.java:499:    public float getAttackCooldown() {
./src/main/java/org/bukkit/entity/HumanEntity.java:364:    public float getAttackCooldown();

**Comment by WillFP** [comment]
My mistake, it wasn't the latest - updated, all sorted
