### ISSUE TITLE
Nether Generation Stalls

### ISSUE THREAD

**Issue by ataranlen** [PaperMC/Paper#3292]
### What behaviour is expected:
The nether world generation should run all the way to the world border

### What behaviour is observed:
After a certain distance (uknown) the nether stops generating chunks, well within the world border.
https://cdn.discordapp.com/attachments/101461617497096192/707253590481305719/2020-05-05_09.28.23.png

### Steps/models to reproduce:

> "It's just that I traveled quite a long distance"
> I was using Aristois entity speed and Look Lock. I was going backwards on my horse because the Look Lock would only let me face the opposite way of where I wanted to go. I left myself moving for a little while. When I checked back in on the game, I was still in the sitting animation, but my horse was behind me. I logged off then logged back in. When I got back in, I was falling off the edge of the nether roof. Now I can't break anything or use a nether portal

> i can place blocks, interact with shulkers
> But not braeak

### Plugin list:
ASP*
boosCooldowns*
BungeeTabListPlus*
BuycraftX*
Captchas
ColoredAnvils*
ColorfulCommands*
Decapitation*
EntityTrackerFixer
FastAsyncWorldEdit
Greentext*
Herochat*
IgnoreDeath*
IllegalStack
LagMonitor
LimitPillagers
NBTAPI*
NoCheatPlus*
NoDroppingOffline*
PermissionsEx*
PlaceholderAPI
Plan
PlugMan
Praise*
ProtocolLib
ProtocolSupport (limited to 1.12.2 and 1.15.2)
ProtocolSupportStuff
RusherTroll*
SimplySpawn*
SSX-Connector*
SuffixCommands*
UltraCosmetics
Vault
VillagerOptimiser
WorldEdit (FastAsyncWorldEdit)
WorldGuard

### Paper build number:
This server is running Paper version git-Paper-245 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
paper.yml and spigot.yml world settings
https://paste.gg/p/ataranlen/2430c007b18b4c23b626c09c685be1d2

**Comment by ataranlen** [comment]
An additional symptom of this issue is the server can sometimes crash and not stop, leaving the server stuck at "Saving Players"

https://paste.gg/p/ataranlen/09a3f093edb049b8a7d1a759f459ecc0

**Comment by aikar** [comment]
@ataranlen if that's the source of the delay, then that seems completely unrelated to async teleport, and question is why is your rehash taking so long

what is your region file cache size set to ? thats either paper.yml or spigot.yml

**Comment by ataranlen** [comment]
Paper.yml:
`region-file-cache-size: 256`

I'm not sure where async teleport comes in.
