### ISSUE TITLE
Errors/Crashes on Startup with Many Skripts

### ISSUE THREAD

**Issue by BetaBurnt** [PaperMC/Paper#3294]
### What behaviour is expected:
Log from running the same setup on PaperSpigot #209 - https://pastebin.com/wX5rCZXw
That would be the expected behaviour.

### What behaviour is observed:
From Paper 1.15.2 build #211 and up there are a lot of errors given when my scripts start loading in, they take a lot longer to load, overload the server and often cause crashes due to the extent of the overloading

If I backdate to PaperSpigot #209 everything loads as normal, same scripts same Skript version, all other plugins the same (Skript 2.5alpha3 - was 2.4.1 but updated to test and they both do the same thing).
Any PaperSpigot build from 211 to the latest (#245 at this time) have this issue.

Switching to the latest Spigot 1.15.2 build instead of PaperSpigot at this time also stops this happening so the issue is present only on the newer Paper builds specifically which suggests an issue specific to PaperSpigot (however, I have also reported this to the Skript devs).

Logs from the exact same setup as the above startup logs on PaperSpigot #211 are in the file linked here as it was too big to pastebin: https://www.dropbox.com/s/owvep8fc50sa6hl/paper211.log?dl=0

### Steps/models to reproduce:
Install the latest Skript alpha, using the latest PaperSpigot and start adding in a lot of scripts until this triggers.

To confirm - I did test with no scripts, everything is then fine, but I cannot find a specific script or scripts that trigger this. I've tried adding them back in one at a time till it started but then if I remove them all again and start with the script that triggered it the first time... it's all fine and I can keep adding them back in and then at some random point this starts again.

### Plugin list:
Big list - https://pastebin.com/kt6jQbE2

To confirm if I disable everything except for Skript and the Skript addons and plugins that the scripts depend on to lighten the overall server load (which is a large decrease in the plugins on the server) this still happens, and the list of plugins is then - https://pastebin.com/tsxbFLgK

### Paper build number:
As stated above.

**Comment by Proximyst** [comment]
Not only does it say `DO NOT REPORT THIS TO PAPER` almost 100 separate times, but this is a plugin problem. Nothing for Paper to handle; just don't do that and it'll be fine :)

**Comment by aikar** [comment]
This is ultimately a fault of skript delaying its startup tasks by 0 ticks instead of doing it in the proper place.
while this technically should be closed because it's not an issue, i'm going to put in a bandaid to stop these bad plugins and force it back into the startup process.

You need to report the issue with skript ultimately that they should be doing loading in onenable and not a delayed task where init stuff is supposed to be done.

They also really should look at paralleling the parse step too....

**Comment by Matocolotoe** [comment]
> You need to report the issue with skript ultimately that they should be doing loading in onenable and not a delayed task where init stuff is supposed to be done.
> 
> They also really should look at paralleling the parse step too....

According to the project structure, not sure they will ever take a look at it xD
