### ISSUE TITLE
Experience clustered affects repairing of Items with mending

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [PaperMC/Paper#3295]
### What behaviour is expected:
By default: "If multiple items have the enchantment, one is chosen at random for each XP orb collected". This is thinking about many experience orbs happening when a mob is killed.

### What behaviour is observed:
Since Paper seems to cluster those orbs to avoid lag and save processing, we get a wacky behaviour when wearing a full set of armor with mending, or having 2 items in both hands. Killing A LOT of mobs may result in taking forever to repair anything, doesn't matter how many enemies you kill. This happens because all is clustered in one orb and, therefore, by getting it, the chance of that going to an specific item is minimal. Usually it depends from mob to mob, but can be around 10x lower per piece of equipment with Mending.

### Steps/models to reproduce:
Spawn 60 Enderman with 1 points of life in a 3x2. Take a full durability armor with mending and 2 damaged swords with mending. Apply a killing blow on all 60 of them.
One tool may get repaired, but both won't. On Vanilla behaviour many orbs will be absorbed (much lag will happen too xD), but the chances of you repairing anything, although is not the same amount, is much higher, to the point that a killing blow like that would possibly repair both tools in your hand.

### Plugin list:
None

### Paper build number:
Paper version git-Paper-237 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
Let me be clear about 2 things here:

1 - This may not be a bug, only a change in a normal behaviour with clearly good intentions, but that may lead to a bad experience when playing.
2 - I may have a suggestion (although I've never programmed any mods/plugins in my life). It may sound simpler than it is, and may require more than this, but I'll take a shot suggesting it.
Wouldn't be possible to save the number of clustered orbs in that final single orb entity (an int of some sort) and then apply distributively that exp to various items when it's consumed by the player? If so, no changes on items or in the Mending enchanting would be required.

Thanks for the AWESOME job with Paper! Its astonishingly amazing.

**Comment by kickash32** [comment]
Just take off whatever is fully repaired. Or you could set a max exp merge value in the config.

**Comment by VADemon** [comment]
I agree with OP, this behaviour needs to be fixed. And apparently all unused exp from a single fat orb will go to waste (if it's more than enough to fully repair an item that was rolled), wasting way more exp than Vanilla normally would.

**Comment by BillyGalbreath** [comment]
https://github.com/PaperMC/Paper/commit/072d6ec8cbd6bf49cf2d109bcca584fc129ab66c

This is the entire reason I made that PR. I personally have mine set to 100, so a single orb will never merge into more than 100, resulting in less wasted exp ;)

**Comment by Marcelo-Petrucelli** [comment]
Yeah, I was thinking about keeping the orb merger, but that would have to be handled. In any case, making it configurable is good, but may also lead to people saying that it lags anyway. I really dunno what's best.

Thanks for the PR.
