### ISSUE TITLE
End gateways do not impose vehicle checks but break because of them

### ISSUE THREAD

**Issue by Proximyst** [PaperMC/Paper#3297]
### What behaviour is expected:
The same vehicle checks Nether and End portals use to take effect and hinder teleportation with an entity on top of your head.

### What behaviour is observed:
The checks are not performed and you teleport like "usual". The passengers you have become invisible to you, and you cannot teleport anywhere due to this as all other teleports impose checks.

### Steps/models to reproduce:
- Place an entity on your head.
- Enter an end gateway using trapdoors.
- Try a command like `/home` from EssentialsX and watch it fail.

### Plugin list:
Inapplicable, I found this quirk in the code while adding stuff to a fork.

### Paper build number:
This was in the code and build as of 10 days ago. Don't really know which build this would be.

**Comment by aikar** [comment]
I would investigate the fork, because the check is clearly there:

BlockEnderPortal

    public void a(IBlockData iblockdata, World world, BlockPosition blockposition, Entity entity) {
        if (!world.isClientSide && !entity.isPassenger() && !entity.isVehicle() && entity.canPortal() && VoxelShapes.c(VoxelShapes.a(entity.getBoundingBox().d((double) (-blockposition.getX()), (double) (-blockposition.getY()), (double) (-blockposition.getZ()))), iblockdata.getShape(world, blockposition), OperatorBoolean.AND)) {


The only thing that we've changed around this is to BLOCK using portals more based on entity state, 

public boolean canPortal() {
        return isAlive() && valid; // Paper
}

**Comment by Proximyst** [comment]
That's an end _portal_, I was referring to an end _gateway_. Check `TileEndGateway` or something along those lines.

**Comment by aikar** [comment]
Oh, I always forget they are different.

We haven't touched that file recently. I questioned adding some checks to it for the dupe fixes, but since it was same-world teleporting I ended up not bothering. 

But this is vanilla behavior, see TileEntityEndGateway line 67

There's no checks for passenger state, nor any commits removing them either. 

![image](https://user-images.githubusercontent.com/58008/81151619-2ab64c80-8f4f-11ea-8c5c-c98dc6138e92.png)

**Comment by aikar** [comment]
I agree thouugh that it does make sense FOR it to do this, so PR's welcome if you want to change 67 to iterate entities and skip ones that can't portal (copy the logic pasted above)

**Comment by Proximyst** [comment]
If anyone can be bothered to PR a fix for this, I've already got the "gist" of it as to how it works (same logic as in `BlockEnderPortal`) here:
https://github.com/Minevictus/Papercut/blob/9028dc05e363b4383bfbca197fdb8a555b1b844e/patches/server/0003-Add-EntityTeleportHinderedEvent.patch#L109-L128

All you have to do is remove the `EntityTeleportHinderedEvent` calls, then it's done. :)

**Comment by kickash32** [comment]
I got a patch done, just need to PR it shortly.
