### ISSUE TITLE
MAX_HEALT dont work on enderdragon (always 200.0D)

### ISSUE THREAD

**Issue by Euphillya** [PaperMC/Paper#3298]
**Is your feature request related to a problem? Please describe.**
Hello why dont modify generic.MAX_HEALTH to Enderdragon ? Actualy  just possible modify damage but modify hp directly is better for all plugins because we no longer need to call an event to reduce the damage 

**Describe the solution you'd like**
Just modify normaly 
Files : EntityEnderDragon.java
code : this.getAttributeInstance(GenericAttributes.MAX_HEALTH).setValue(200.0D);

PS : sorry my english is not good ^^"

**Comment by Machine-Maker** [comment]
On Paper 1.16.4 build 310 I was able to set the health of the ender dragon using the attributes. I set the max health attribute to 300 and then set the health to 300. When I ran `/data get entity @e[type=minecraft:ender_dragon,limit=1]` after summoning in a dragon with no ai, it showed its max health attribute to be 300 and its health to be 300 as expected. 

![image](https://user-images.githubusercontent.com/15055071/100975153-679cee80-34f2-11eb-8692-e2700aeef324.png)
