### ISSUE TITLE
Entity tracker issues

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3300]
### What behaviour is expected:
Players/mobs behaving normally 

### What behaviour is observed:
Certain players/mobs become frozen on other player's screens but in reality they are moving and can still dig/attack the player, if the player attempts to attack the frozen mob/player no attack sound plays

### Steps/models to reproduce:
No tick view distance may be the cause, the settings i am using are 3 view distance and 7 no tick

### Plugin list:
None of my plugins interact with the entity tracker thus this isnt very relevant

### Paper build number:
git-paper-251

**Comment by P-paj** [comment]
Can confirm am experiencing this in Paper 247

 Players when teleported to an area will sometimes not be shown to others - letting them interact as an unseen entity.

Also sometimes players will see another freeze in place - the frozen player still able to do things.

**Comment by P-paj** [comment]
When these players are experiencing this issue - fighting invis players, or other players seeing them as frozen/ invis - things like holograms (which we are using for damage hitmarkers) stay loaded client side - causing increasing fps lag until relog. 

The armorstaands for these holograms dont exist server side.

**Comment by ghost** [comment]
My settings, viewdis: notick 7 normal 3      
entity-tracking-range:
      players: 64
      animals: 32
      monsters: 32
      misc: 32
      other: 64

**Comment by Spottedleaf** [comment]
Please update to latest, we might have fixed it

**Comment by P-paj** [comment]
Tried latest, seemed to happen less often at first. But now happening constantly again.

**Comment by opacityz** [comment]
Also experiencing this issue on version 251.

> When these players are experiencing this issue - fighting invis players, or other players seeing them as frozen/ invis - things like holograms (which we are using for damage hitmarkers) stay loaded client side - causing increasing fps lag until relog.

**Comment by Spottedleaf** [comment]
update again, we've tried another fix

**Comment by opacityz** [comment]
fixed on version 254
