### ISSUE TITLE
Extreme server crash since the update

### ISSUE THREAD

**Issue by Blueeyestar** [PaperMC/Paper#3305]
Paper version git-Paper-254 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Hello, since I made the 8 updates today, my server has been greasing again and again. Is it paper? I had never had before. who can help me?

https://pastebin.com/p6Pz28AU

>.... [22:56:47 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-254 (MC: 1.15.2) ---
>.... [22:56:47 ERROR]: The server has not responded for 10 seconds! Creating thread dump
>.... [22:56:47 ERROR]: ------------------------------
>.... [22:56:47 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
>.... [22:56:47 ERROR]: ------------------------------
>.... [22:56:47 ERROR]: Current Thread: Server thread
>.... [22:56:47 ERROR]: PID: 19 | Suspended: false | Native: false | State: RUNNABLE
>.... [22:56:47 ERROR]: Stack:
>.... [22:56:47 ERROR]: com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor352.execute(Unknown Source)
>.... [22:56:47 ERROR]: org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [22:56:47 ERROR]: org.bukkit.plugin.EventExecutor$$Lambda$2867/778509500.execute(Unknown Source)
>.... [22:56:47 ERROR]: co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [22:56:47 ERROR]: org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [22:56:47 ERROR]: org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [22:56:47 ERROR]: org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471)
>.... [22:56:47 ERROR]: org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:438)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:137)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1353)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$4414/1250737581.run(Unknown Source)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1208)
>.... [22:56:47 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
>.... [22:56:47 ERROR]: java.lang.Thread.run(Thread.java:748)
>.... [22:56:47 ERROR]: ------------------------------
>.... [22:56:47 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
>.... [22:56:47 ERROR]: ------------------------------

**Comment by aikar** [comment]
Not really sure what greasing is, but as it says "DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH", discord is better for asking for help here.

Based on logs, your operating system was having serious issues potentially at kernel level. Your system health looks like it was really impacted.

Consult with your host if you are not the administrator of the server.
