### ISSUE TITLE
Paper saves item nametag data in a different order from vanilla

### ISSUE THREAD

**Issue by Robit** [PaperMC/Paper#3306]
This bug was discovered while helping a customer (I work for a host) debug why commands they were running on a server were not returning the same results as they were on a vanilla world. I haven't done extensive testing on this, so I haven't been able to narrow down exactly what's going on, but there seems to be some inconsistency in how paper saves NBT data compared to vanilla. 

### What behaviour is expected:
When you /give yourself an item with a {Name:'{...}'} set of tags should give you an item with the contents of the Name tag in order. 

### What behaviour is observed:
The tags are out of order (see below). 

### Steps/models to reproduce:
1. Run `/give @p minecraft:elytra{Name:'{"italic":false,"color":"red","text":"Phoenix"}}',Lore:['{"text":"Set the ashen skies alight","color":"red","italic":false}']},Enchantments:[{id:"minecraft:protection",lvl:4s},{id:"minecraft:unbreaking",lvl:5s},{id:"minecraft:mending",lvl:2s}],AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:.2,Operation:1,UUIDLeast:393781,UUIDMost:517799,Slot:"chest"},{AttributeName:"generic.armor",Name:"generic.armor",Amount:8,Operation:0,UUIDLeast:365684,UUIDMost:752309,Slot:"chest"}]} 1`
2. Place the elytra you were given in your chestplate slot.
3. Run `/execute if entity @a[nbt={Inventory:[{Slot:102b,id:"minecraft:elytra",Count:1b,tag:{display:{Name:'{"text":"Phoenix","color":"red","italic":false}'}}}]}]` **This test will fail on a PaperMC server despite succeeding in vanilla**
3. Run `/execute if entity @a[nbt={Inventory:[{Slot:102b,id:"minecraft:elytra",Count:1b,tag:{display:{Name:'{"italic":false,"color":"red","text":"Phoenix"}'}}}]}]` **These tags are out of order from what you expect the item to have, yet the test succeeds on a Paper server despite failing in vanilla.**

### Plugin list:
I tested this in vanilla paper, with no plugins. I only later added a simple nbt inspector plugin which adds a command (/nbti) to check the nbt of the item and verify the tags were indeed out of order in the way specified above.

### Paper build number:
This server is running Paper version git-Paper-254 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by aikar** [comment]
Did you get your example mixed up? Because it sounds like Paper is correct and Vanilla is wrong based on what you supplied....

**Comment by aikar** [comment]
Ultimately closing as {Won't Fix} regardless. HashMap ordering is not guaranteed. 

This isn't the only area we deviate from vanilla, and we aren't fixing these kind of issues, because preserving order based on non deterministic contract is not feasible, and not worth sacrificing performance optimizations for.

Just edit your commands so they work with whatever paper generates, not vanilla.

but in your example, it sounds like Vanilla is wrong and paper is better, in that Paper preserved your ORIGINAL input, and vanilla did not.
If you want order to not matter, put in a ticket to Mojang.

**Comment by Robit** [comment]
Makes sense have a nice day
