### ISSUE TITLE
Skript Issues with Paper

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3308]
### What behaviour is expected:
Server Error
Note: error doesn't occur when using Paper v209

### What behaviour is observed:
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: java.base@11.0.6/java.util.regex.Pattern.atom(Unknown Source)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: java.base@11.0.6/java.util.regex.Pattern.sequence(Unknown Source)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: java.base@11.0.6/java.util.regex.Pattern.expr(Unknown Source)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: java.base@11.0.6/java.util.regex.Pattern.compile(Unknown Source)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: java.base@11.0.6/java.util.regex.Pattern.<init>(Unknown Source)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: java.base@11.0.6/java.util.regex.Pattern.compile(Unknown Source)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: ch.njol.util.StringUtils.replaceAll(StringUtils.java:70)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: ch.njol.skript.ScriptLoader.replaceOptions(ScriptLoader.java:1008)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1038)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:694)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:410)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: ch.njol.skript.ScriptLoader$$Lambda$3650/0x000000080123f440.run(Unknown Source)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:429)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:348)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: ch.njol.skript.ScriptLoader$$Lambda$3649/0x000000080123f040.run(Unknown Source)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:381)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: ch.njol.skript.Skript$2.run(Skript.java:592)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: app//org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: app//org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: app//net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: app//net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: app//net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: app//net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
06.05 20:45:40 [Server] Startup [00:45:40 ERROR]: java.base@11.0.6/java.lang.Thread.run(Unknown Source)

### Steps/models to reproduce:
Run Paper v256 with Skript v2.5-alpha3

### Plugin list:
Skript v2.5-alpha3

### Paper build number:
Paper v256

**Comment by aikar** [comment]
can you give more of the log, it seems cut off, and i cant reproduce this

**Comment by ghost** [comment]
https://mcpaste.io/e5c194071616e49d

**Comment by aikar** [comment]
You are on build 255, not 256.... which 256 was exactly to fix this.
