### ISSUE TITLE
Bugged Lighting

### ISSUE THREAD

**Issue by NikoEatsPancakes** [PaperMC/Paper#3309]
### What behaviour is expected:
Proper lighting

### What behaviour is observed:
Odd lighting bugs where certain areas are completely blacked out

### Steps/models to reproduce:
Unsure; updated to 258 from a really old Tuinity build and the issue started occurring, and persisted on 259 as well as 257 when I tried to revert in an attempt to fix the issue

### Plugin list:
Plugins (66): AdvancedPortals, afkTerminator*, AntiVPN, Autorank, Chisel*, CommandBlockTools*, CourierNew, DiscordSRV, dynmap*, EnderCore, EnjinMinecraftPlugin, EntityDetection, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, FamoustLottery, FoundDiamonds*, HideAndSeek, HolographicDisplays, IllegalStack, LibsDisguises, LimitPillagers, LiteBans, LogBlock, LuckPerms, LWC, MarriageMaster, MobFarmManager, Multiverse-Core, MyWarp, NewbieChat*, NoSpawnerChange, NoteBlockAPI, OnTime*, OpenInv, PacketLimiter, ParrotGlue, PerWorldInventory, PhantomSpawnControl, PluginLibrary, PowerlessLamps*, ProtocolLib, QCGames, QCPlayers*, QuickShop, RandomTeleport, RedstoneClockDetector*, SAML, SignEdit*, SimpleSit*, spark, SpeedBuilders, StaffChat*, Taxes, UltimateTimber, VanishNoPacket*, Vault, VillagerOptimiser, VolleyBall, Votifier, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

### Paper build number:
258, 259, 257

### Anything else:
Screenshots of the issue: https://imgur.com/a/HkGQda3

**Comment by jpenilla** [comment]
I had the same issue after upgrading from 256 to 258, updated to 259 and it persisted

**Comment by aikar** [comment]
reverted the patch in 260

**Comment by AerWyn81** [comment]
Updated to 261 issue still persist. Command /paper fixlight work but there are so many chunks in dark. Downgrade to a previous version (245) fixed this issue.

**Comment by aikar** [comment]
No it did not. Downgrading paper does absolutely nothing to solve impacted chunks. The only way to fix them is either using a --forceUpgrade --eraseCache to fix entire world, or use /paper fixlight on a per area basis.

**Comment by AerWyn81** [comment]
Ok sorry, Everything's back to normal. Thanks.
