### ISSUE TITLE
Build 213 break Fastlogin plugin AuthMe auto login feature when using on the Waterfall proxy

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#3312]
### What behaviour is expected:
___What you expected to see___
Build 213 break Fastlogin plugin AuthMe auto login feature when using on the Waterfall proxy.
This feature works perfectly with build 212 and before.

### What behaviour is observed:
___What you actually saw___
Fastlogin AuthMe auto login feature works perfectly when using on the Waterfall proxy

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Install Fastlogin plugin to proxy and Minecraft server.
Install AuthMe plugin to Minecraft server.
Setup Fastlogin system and turn on premium login.
If join the AuthMe auto login not work.

### Plugin list:
___A list of your plugins___
Plugins (3): AuthMe, FastLogin, ProtocolLib

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-245

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Prof-Bloodstone** [comment]
Update. This issue was fixed some time ago: https://github.com/PaperMC/Paper/commit/3e9fc24b66d5f602e7d8510f160ff988c412a8d2

**Comment by andris155** [comment]
This update don't fixed this bug.

**Comment by andris155** [comment]
This fix maybe fix Fastlogin if use on the Paper server, but if use the Fastlogin plugin on the proxy server not work auto login with AuthMe.

**Comment by andris155** [comment]
Fastlogin plugin author fixed this.
https://github.com/games647/FastLogin/issues/331
