### ISSUE TITLE
Chunk Load And Async World Save Crash

### ISSUE THREAD

**Issue by DevYorma** [PaperMC/Paper#3313]
### Link/paste of stack trace

https://hastebin.com/dulutoqoxo.sql

### Plugin list:
Plugins (75): AcoWorth, AdvancedDungeons, AdvancedRegionMarket, ArmorStandTools, ArmShopBridge, AsyncWorldEdit, AuctionHouse, ChestProtect, Citizens, Clans-Spigot-Part*, CoreProtect, DecoHeads*, DiscordSRV, dynmap*, EliteLootbox, EpicWorldGenerator, FriendsAPIForPartyAndFriends*, GHolo, IALibs, IllegalStack, ImageOnMap, ItemsAdder, ItemsAdder-WorldEdit, Jobs, Kosmos, Lands, LandsDiscordBot, LangUtils, LightAPI*, LimitPillagers, LuckPerms, Matrix, Minepacks, Misk, MrCore_BukkitImpl, Multiverse-Core, NoteBlockAPI, Oh_the_dungeons_youll_go, PacketListenerApi*, PlaceholderAPI, PlayerRadios, PlotSquared, PlugMan, PremiumVanish, ProtocolLib, ProtocolSupport, QuickShop, Reqn*, SaneEconomy*, SK-NBeeT, Skellett, Skore*, SkQuery, Skript, skript-db*, skript-mirror*, Skungee*, skUtilities*, SQLibrary*, TAB, Tablisknu, TitleManager*, TuSKe*, UltimateTimber, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaRewindPotions*, ViaVersion, VillagerOptimiser, Votifier, WorldBorder, WorldEdit, WorldGuard

### Actions to reproduce (if known):
-

### Paper build number:
git-Paper-260 (MC: 1.15.2)

**Comment by aikar** [comment]
Your link is invalid

**Comment by DevYorma** [comment]
Ok... that's funny because I am able to access it.
Here a diffrent link: https://pastebin.com/uFaZU1iW

**Comment by electronicboy** [comment]
```
Caused by: java.lang.IllegalStateException: Asynchronous world save!
    at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.15.2.jar:git-Paper-260]
    at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.save(CraftWorld.java:1397) ~[patched_1.15.2.jar:git-Paper-260]
    at minelazz.tob.<init>(dea:62) ~[?:?]
    at com.minelazz.epicworldgenerator.nativeAPI.implementations.v1_15_R1.generator.NativeEpicChunkProvider2.addDecorations(cca:371) ~[?:?]
```

**Comment by aikar** [comment]
EpicWorldGenerator is doing a save in world gen, report to them to remove that line of code.

**Comment by DevYorma** [comment]
Ok thanks for your help.
