### ISSUE TITLE
Server won't start because of watchdog (1.15.2, works in 1.13.2)

### ISSUE THREAD

**Issue by bloggy** [PaperMC/Paper#3314]
### What behaviour is expected:
Load the server and all plugins without problems and not spam console with watchdog-messages.

### What behaviour is observed:
Watchdog causes the server to not start (because some plugins are taking long time to load)

### Steps/models to reproduce:
Install skript (plugin) and add dozens of scripts to make the server start take long (1 - 3 minutes) and see watchdog spamming console.

Paper: Tuinity version git-Tuinity-"e00a4e3" (which basically is paper, you can also test with latest paper build)

This is only 1 of many console errors I get when I start server:
https://pastebin.com/TgbUVY0L

**Comment by zachbr** [comment]
No it isn't the latest paper build. It's at least two upstream updates behind Paper.
We do not accept issues from unofficial builds for this and many other reasons. Reproduce on latest paper or seek support from your fork.

**Comment by aikar** [comment]
And the issue is fixed in latest, tuinity is behind.
