### ISSUE TITLE
Breaking waterlogged tile entities causes odd error

### ISSUE THREAD

**Issue by bigfoot547** [PaperMC/Paper#3318]
### Link/paste of stack trace

`Block at -215, 63, 138 is Block{minecraft:water} but has net.minecraft.server.v1_15_R1.TileEntityChest@1363f049. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.`

### Plugin list:
No plugins installed.

### Actions to reproduce (if known):
Place a (trapped) chest inside of a water source block, or otherwise create a waterlogged (trapped) chest, then break the chest. My assumption is that this will occur with *any* waterlogged tile entity, but I cannot recall any other than chests and trapped chests off of the top of my head.

### Paper build number:
`git-Paper-260 (MC: 1.15.2)`

**Comment by aikar** [comment]
Well that's an interesting one. did confirm this scenario. 

validation of the TE state change seems to maybe be getting it post removal triggering false message because before 1.13 this concept of a TE being inside water didnt exist.

probably just need to add and != water to the validator.

**Comment by danny6167** [comment]
For reference, this appears to be the upstream bug.
https://hub.spigotmc.org/jira/browse/SPIGOT-5560

**Comment by vitalyraif** [comment]
This bug still present in Paper build 174.
`[14:31:05 ERROR]: Block at -157, 62, -15 is Block{minecraft:water} but has net.minecraft.server.v1_16_R2.TileEntityChest@424a7b11. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.`
