### ISSUE TITLE
Wolves included in despawn-ranges

### ISSUE THREAD

**Issue by Champverse** [PaperMC/Paper#332]
This is more of a quick feature request - although I'm unsure if this was originally intended.

Wolves currently are included in the despawn range around players, and given that the majority spawn on world generation, it makes them increasingly rare.

Is it possible to have Wolves removed from the despawn range?

Appreciate all the ongoing support for Paper!

**Comment by Puremin0rez** [comment]
Well then.... that'd be why I've never seen a wolf in the past few years of playing.

**Comment by Champverse** [comment]
This is resolved in 1.10 Paper - thanks for the help!
