### ISSUE TITLE
[SPIGOT-5705] HoverEvent Constructors for ItemStack, Entity, Achievement

### ISSUE THREAD

**Issue by MeFisto94** [PaperMC/Paper#3320]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to use `HoverEvent.Action.SHOW_ITEM` and related.
I have to dive into NMS, where I am at the point of rendering this enum useless.

**Describe the solution you'd like**
This is how I "solved" it for me:
```java
public static HoverEvent hoverItem(ItemStack stack) {
    net.minecraft.server.v1_15_R1.ItemStack is = ((CraftItemStack)stack).getHandle();
    NBTTagCompound nbt = is.save(new NBTTagCompound());
    return new HoverEvent(HoverEvent.Action.SHOW_ITEM, new BaseComponent[]{new TextComponent(nbt.toString())});
  }
```
This should be implemented as Constructor directly on HoverEvent and potentially also supporting the other Actions.

**Describe alternatives you've considered**
Living without this and being frustrated all the time :P

**Additional context**
I was about to open an issue at spigot, but there already is the tracking issue https://hub.spigotmc.org/jira/browse/SPIGOT-5705
It's been only 1.5 weeks since that report, but I was told that creating an issue here as well might be desireable.

**Comment by Proximyst** [comment]
There is already an open PR for the items.
https://github.com/PaperMC/Paper/pull/3266
