### ISSUE TITLE
Random Server Crashes

### ISSUE THREAD

**Issue by dionmeader97** [PaperMC/Paper#3327]
Hi All,

We released our Minecraft server last night but on our survival server, we kept experiencing random crashes. Most of the time it wouldn't provide a crash-report but I did, however, manage to get one in the end.

Any help/ideas would be greatly appreciated.

Below is the crash report.

[crash-2020-05-09_00.11.32-server.txt](https://github.com/PaperMC/Paper/files/4603395/crash-2020-05-09_00.11.32-server.txt)

**Comment by aikar** [comment]
this was fixed in a later version already.
