### ISSUE TITLE
Console Error - InventoryClickEvent

### ISSUE THREAD

**Issue by LucidAPs** [PaperMC/Paper#3328]
I have four different plugins giving me the same exact error, i have no means to reproduce the errors and it doesn't seem to break their behaviors in any way.

> Could not pass event InventoryClickEvent to "plugin name"
> java.lang.IllegalStateException: Title not set

This is one full log example: https://pastebin.com/raw/Fj5rLGgp

This server is running Paper version git-Paper-264 (MC: 1.15.2)
Java 8

**Comment by LucidAPs** [comment]
More examples all the same day and almost the same time
SpleefX: https://pastebin.com/raw/QZinEm5Y
CrazyCrates: https://pastebin.com/raw/PR43H08K
HackedServer: https://pastebin.com/raw/RkyAgjL3

**Comment by electronicboy** [comment]
Something opened an inventory without a title and the implementation in craftbukkit means that it will shout if something tries to get the title

**Comment by LucidAPs** [comment]
So what needs to be done for these errors to stop? Are the authors plugins responsible for preventing or fixing this? It just seems a bit strange for it to be happening for all these plugins, i also showed my configurations to the authors and didn't find anything wrong with them. Furthermore if the errors happen when a menu opens without a proper title then why i can't reproduce the error when i open all menus and try all the options?

**Comment by aikar** [comment]
all it takes is for 1 plugin to create the inventory without a title.

But considering opening an inventory without a title is a supported thing... this is a valid bug in upstream

just need to ditch that IllegalStateException

**Comment by aikar** [comment]
Oh wait, apparently it's suppose to default the title if not. hmm.

**Comment by CDFN** [comment]
I can't tell what's causing it. Creating inventory with null title isn't possible due to check in MinecraftInventory contructor. When we're not passing `title` parameter to constructor, default `Chest` is used. I think it's caused by weird code in plugins and not by upstream.
