### ISSUE TITLE
Loyalty trident loyal problem using no-tick view distance

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#3329]
If you enchant a trident with loyalty and throw it into a loaded but not ticked chunk, the trident will not return. Once the chunk is ticked again, the trident will return to its owner. For players the difference between loaded and ticked chunks is invisible, they just see that it doesn't work. So could you prevent tridents from flying into non-ticked chunks? Or is this a side effect you have to live with if you activate the feature?

view-distance: 3
no-tick-view-distance: 8
Paper 1.15.2 - 264

**Comment by ghost** [comment]
this is just a result of a chunk not ticking

**Comment by TheoRetisch1** [comment]
Still a very unpleasant experience. That's why I suggested to prevent a trident from flying into unticketed chunks.

**Comment by VADemon** [comment]
View-dist of 3 is an unpleasant experience. 48b is not enough to get the 50 blocks sniper achievement (if you are standing on the edge of a chunk you're in)

The trident is an entity and if it's not ticking - it's not ticking. The same problem would appear in Vanilla if the trident happened to land in an unloaded chunk somehow. So I think you would need to put it up with Mojang and Spigot first.

**Comment by electronicboy** [comment]
really, anything lower than 4/5 VD is going to cause issues with projectiles, etc; There is no real "fix" for this without taking an all too opinionated approach, you quite simply have the option of holding it in the air doing nothing, which is already what happens, or, to remove them, which would upset players about losing their items

**Comment by TheoRetisch1** [comment]
You're right: My settings do not reflect a balance between performance and gameplay. I set the view-distance to 5 and it runs very well. Thanks for the help :)
