### ISSUE TITLE
Pistons & Gravel

### ISSUE THREAD

**Issue by Champverse** [PaperMC/Paper#333]
When attempting to drop a block of gravel by removing the block from below it, the block of gravel simply breaks.

This can be replicated by placing a block of gravel on top of a powered piston, then unpowering the piston.

Tested in single player and hence deduced it's not a feature of the game. This bug does not occur in single player.

**Comment by WonderDave** [comment]
This was also true of sand, but the glitch seems to have been fixed beginning with the last few versions of 1.9.4.  I've used PaperSpigot builds #773, 776, and 780, and the problem no longer occurs for me.

**Comment by zachbr** [comment]
You have left out some pretty important information. I suggest you take a look at the issue template and try again.
