### ISSUE TITLE
Allow leashing undead horse doesn't work

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#3333]
### What behaviour is expected:
With paper option **allow-leashing-undead-horse: true**, players are able to leash zombi and skeleton horses.

### What behaviour is observed:
Using latest paper version Paper-273 and with **allow-leashing-undead-horse: true** if you right-click on a skeleton or zombie horse, the lead just drops on the ground.

### Steps/models to reproduce:
Activate **allow-leashing-undead-horse**, start a server and try to leash a skeleton or zombi horse.

### Plugin list:
None, fresh environment.

### Paper build number:
Paper-273

### Anything else:
Nothing.

**Comment by nbastin** [comment]
I can't reproduce this on either Paper-260 or Paper-280.  Are your horses tamed?

**Comment by lordrius** [comment]
Oh my bad, I was trying with summoned and egg-spawned skeleton and zombi horses that spawn untamed... Those who spawn by lightning are tamed, closing...
