### ISSUE TITLE
Bukkit.getPlayer(UUID) not taking pendingPlayers into account

### ISSUE THREAD

**Issue by cijaaimee** [PaperMC/Paper#3334]
### What behaviour is expected:
When calling Bukkit.getPlayer(UUID) didn't use to return null when the player was still logging in, but since the  `a(NetworkManager networkmanager, EntityPlayer entityplayer)` method was broken down into pieces for async chunk loading on player joins, it will return null if called before the chunk has been loaded.

### What behaviour is observed:
It returns null.

### Steps/models to reproduce:
There's not much to reproduce here. The method simply doesn't take into account pending players that have technically already logged in, but are waiting for the chunks to load.

### Plugin list:
Not necessary.

### Paper build number:
It's a fork, but that's completely unrelated.

### Anything else:
CraftServer.getPlayer(UUID) just calls this method in PlayerList:

```java
    @Nullable
    public EntityPlayer a(UUID uuid) {
        return  (EntityPlayer) this.j.get(uuid);
    }
```

In order to fix the issue, I've done this:
```java
    @Nullable
    public EntityPlayer a(UUID uuid) {
        EntityPlayer player = (EntityPlayer) this.j.get(uuid);

        if (player == null) {
            return pendingPlayers.get(uuid);
        }

        return player;
    }
```

I'd post a PR myself but I don't want to go through the cloning process (I'm lazy).

**Comment by aikar** [comment]
Working as intended. These players are supposed to be invisible to the api until they join
