### ISSUE TITLE
Zero tick farms are broken in build 265 and later

### ISSUE THREAD

**Issue by greenywd** [PaperMC/Paper#3341]
### What behaviour is expected:
Zero tick farms working with `fix-zero-tick-instant-grow-farms` set to false.

### What behaviour is observed:
Instead of (in my case) sugar cane growing, it instead breaks.

### Steps/models to reproduce:
The zero tick farm I was able to reproduce this with is [this one](https://www.youtube.com/watch?v=2wVzDC4bsZk&t=413s), but other people on the server using other designs also see the same issue.

### Plugin list:
None

### Paper build number:
265 and later

### Anything else:
https://papermc.io/ci/job/Paper-1.15/265/changes -

**Comment by greenywd** [comment]
Forgot to mention, this is on 1.15.2.

**Comment by aikar** [comment]
Erm, this design seems to work for me on latest still... but i suspect it might be dependent on position in world.

I'll revert the change overall though.

**Comment by aikar** [comment]
This is also the dumbest mechanic I've seen. This trick is some how relying on specific values for the hash code.... relying on some low level jvm implementation detail.

sadly not first time i've heard of "technical minecraft" relying on JVM internals though.
