### ISSUE TITLE
First time Player Spawn being overwritten by Paper.

### ISSUE THREAD

**Issue by ablac** [PaperMC/Paper#3342]
### What behavior is expected:
When a player spawns I want them to spawn at the set spawn by MaSuite.

### What behavior is observed:
Player spawns instead at default map spawn instead of the designated MaSuite Spawn

### Steps/models to reproduce:
Not entirely sure, but I've tested this with and without plugins, and with EssentialsXSpawn, MaSuiteSpawn, and a few other plugins to make sure it wasn't an issue

### Plugin list:
BungeeTabListPlus, BuyCreatF, Essentials, EssentialsAntiBuild, EssentialsProtect, LuckPerms, MaSuiteChat, MaSuiteCord, MaSuiteHomes, MaSuitePortals, MaSuiteTeleports, MaSuiteWarps, Spartan, Vault, Worldedit

### Paper build number:
git-Paper-280 (mc 1.15.2)

### Anything else:
I have tested this issue with and without plugins, and with only required plugins to make/spawn work, yet they always get override by something on the server-side.

**Comment by Proximyst** [comment]
Although not a fix, you can work around this by setting the world spawn (`/setworldspawnpoint` or something along those lines).

**Comment by kickash32** [comment]
Is this a paper specific issue? If it's not then the plugin must not be using the API correctly and you should contact the author.

**Comment by ablac** [comment]
So after hours of google searching, I actually solved the problem! Built into Vanilla Minecraft and there seem to be no physical settings for it, is /gamerule spawnRadius (value)

by default this is set to like 16 I believe, so it spawns the person within 16 blocks of where /setworldspawn is.

**Comment by ablac** [comment]
Its something paper can fix, as the Vanilla GameRules are overriding the plugins, and paper could add a config that makes it default to 0

**Comment by Proximyst** [comment]
Plugins can themselves set the game rules, and game rules are per-world, meaning they'd have to handle it for the spawn world.

**Comment by aikar** [comment]
Well that's weird, because the code that does that runs before all of the initial event fires....
Line 117:         if (nbttagcompound == null) entityplayer.moveToSpawn(worldserver); // Paper - only move to spawn on first login, otherwise, stay where you are....

128:
```java
        // Spigot start - spawn location event
        Player bukkitPlayer = entityplayer.getBukkitEntity();
        PlayerSpawnLocationEvent ev = new com.destroystokyo.paper.event.player.PlayerInitialSpawnEvent(bukkitPlayer, bukkitPlayer.getLocation()); // Paper use our duplicate event
        Bukkit.getPluginManager().callEvent(ev);

        Location loc = ev.getSpawnLocation();
        worldserver = ((CraftWorld) loc.getWorld()).getHandle();

        entityplayer.spawnIn(worldserver);
        entityplayer.setPositionRaw(loc.getX(), loc.getY(), loc.getZ()); // Paper - set raw so we aren't fully joined to the world (not added to chunk or world)
        entityplayer.setYawPitch(loc.getYaw(), loc.getPitch());
        // Spigot end

```

So plugins should be able to listen PlayerSpawnLocationEvent (Spigot event) to set that initial location

But even then setting it in PlayerJoinEvent should work too.
the move to spawn thing is only called once.

**Comment by ablac** [comment]
Ya its weird I tested with Essentials, MaSuiteSpawn and A few other spawn plugins, and none of them worked till use the /gamerules
