### ISSUE TITLE
Hopper minecart moving above hopper didnt distribute item equally

### ISSUE THREAD

**Issue by sket0714** [PaperMC/Paper#3343]
### What behaviour is expected:
In vanilla, hopper minecart having multi items type, each type is the same amount of items with the hoppers array, moving above the hoppers array, each type of items will be distributed equally to each hopper.

### What behaviour is observed:
If hoppers are pointed to solid block or air, the result is as expected, but if hoppers are pointed to brewing stand, except the first type of item, others type of item won't be distributed equally.

### Steps/models to reproduce:
video:
https://youtu.be/uplQTsAtPlE

### Plugin list:
SkinsRestorer, version: 13.7.9

### Paper build number:
Paper version git-Paper-280 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

ps: all config in paper.yml is default

### Anything else:
I've tested in vanilla server, and this problem only occurs in paper server.

**Comment by aikar** [comment]
Does this happen on build 278?

**Comment by sket0714** [comment]
Yes this does happen on build 278

**Comment by aikar** [comment]
Was the brewing stands full? If so, you need to disable hopper.cooldown-when-full in paper.yml world config.

**Comment by sket0714** [comment]
Yes, disable hopper.cooldown fixed the issue, but when enabled it even though the brewing stands weren't filled the problem still occurs.
