### ISSUE TITLE
Strange pathfinding behavior on Paper-280

### ISSUE THREAD

**Issue by sandtechnology** [PaperMC/Paper#3346]
### What behaviour is expected:
Zombie pigman walk to turtle egg and try to destroy it

### What behaviour is observed:
Zombie pigman is walking like a circle:
![2020-05-11_22 40 29](https://user-images.githubusercontent.com/20417547/81575654-d9d4a700-93d9-11ea-9177-072efab05ead.png)

### Steps/models to reproduce:
1.Build a structure like this:
![2020-05-11_23 01 12](https://user-images.githubusercontent.com/20417547/81577173-b6aaf700-93db-11ea-98b6-8596bcf7e45c.png)
![2020-05-11_23 01 20](https://user-images.githubusercontent.com/20417547/81577187-b9a5e780-93db-11ea-8983-2db5ec215b8c.png)
![2020-05-11_23 01 23](https://user-images.githubusercontent.com/20417547/81577221-c32f4f80-93db-11ea-8e39-204d3cce071e.png)

2.Summon enough zombie pigman on the stone platform
3.Saw the strange behavior 

### Plugin list:
Plugins (17): AutoCraft, BungeeTabListPlus, CMI, CMIPaperLib, CoreProtect, LuckPerms, LWC, LWCTrust, PlaceholderAPI, PlayerSQL, PlotSquared, PlotTweaker, PlugMan, ProtocolLib, SimpleORM*, TitleManager, WorldEdit

### Paper build number:
280

### Anything else:
This issue ONLY appear on 280, downgrade to 279 seems fix this issue.

**Comment by aikar** [comment]
weird. i swear I didn't change any of the logic myself, unless IDEA got the conversion of the code wrong...
I'll look into it this evening.

**Comment by aikar** [comment]
I see issue:
https://github.com/PaperMC/Paper/commit/7a7c429260dac18f0cc00f079a19105b2f12f130#diff-3732465173598774f2a6e7892ec65356R156

Missed a detail here. Will fix this evening.
