### ISSUE TITLE
Question on Hopper Optimization

### ISSUE THREAD

**Issue by isaaclepes** [PaperMC/Paper#3347]
QQ:  Will this optimization make obsolete the performance benefit of adding containers over hopper lines?  (I.E. composters/furnaces over hoppers to stop them checking for items on the ground to increase their tps performance as seen here: https://www.youtube.com/watch?v=yINcXy-ajiU)

**Comment by aikar** [comment]
"obsolete" no, but it does allow you to use ANY solid block, not just containers.
It basically expanded that improvement.

Solid blocks might be slightly better too.

**Comment by J0schlZ** [comment]
Are blocks like glass or sea lanterns also traited as solid block in this case?
