### ISSUE TITLE
Error on /version

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#335]
I'm not sure why but whenever I do /version I get this error in console: http://hastebin.com/atijixaxuc.avrasm
In game it says "Error obtaining version information"

Here's my java version if it helps:

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by zachbr** [comment]
Duplicate of GH-222
