### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 65

### ISSUE THREAD

**Issue by viveleroi** [PaperMC/Paper#3353]
### Link/paste of stack trace

https://hasteb.in/yiweyuhu.yaml

### Plugin list:
https://hasteb.in/ritovura.css

### Actions to reproduce (if known):
Unknown

### Paper build number:
273

**Comment by viveleroi** [comment]
Happened again on paper 282: https://hasteb.in/vanocovi.pl

**Comment by electronicboy** [comment]
Please use gist or something sane in the future, closing due to the fact that the pastes are dead
