### ISSUE TITLE
rain issue??

### ISSUE THREAD

**Issue by MrIvanPlays** [PaperMC/Paper#3354]
### What behaviour is expected:
Everywhere to rain

### What behaviour is observed:
Rain only where ground is water
[this](https://drive.google.com/open?id=1cODYf379KoW55uvBOazZfhru1eYufWoM) video shows the problem

### Steps/models to reproduce:
not sure

### Plugin list:
Plugins (3): LuckPerms, Skins, ToggleInventory-Revamped

### Paper build number:
This server is running Paper version git-Paper-282 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
not sure if thats actually an issue or is just a normal behaviour, but I remember back in the old days it used to rain everywhere

**Comment by Redned235** [comment]
> ### What behaviour is expected:
> Everywhere to rain
> 
> ### What behaviour is observed:
> Rain only where ground is water
> [this](https://drive.google.com/open?id=1cODYf379KoW55uvBOazZfhru1eYufWoM) video shows the problem
> 
> ### Steps/models to reproduce:
> not sure
> 
> ### Plugin list:
> Plugins (3): LuckPerms, Skins, ToggleInventory-Revamped
> 
> ### Paper build number:
> This server is running Paper version git-Paper-282 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
> 
> ### Anything else:
> not sure if thats actually an issue or is just a normal behaviour, but I remember back in the old days it used to rain everywhere

This is expected behavior. What is actually happening is you’re flying back and forth from the savannah biome to the river biome. In savannahs it won’t rain, but in the river biome it will.

**Comment by MrIvanPlays** [comment]
> > ### What behaviour is expected:
> > Everywhere to rain
> > ### What behaviour is observed:
> > Rain only where ground is water
> > [this](https://drive.google.com/open?id=1cODYf379KoW55uvBOazZfhru1eYufWoM) video shows the problem
> > ### Steps/models to reproduce:
> > not sure
> > ### Plugin list:
> > Plugins (3): LuckPerms, Skins, ToggleInventory-Revamped
> > ### Paper build number:
> > This server is running Paper version git-Paper-282 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
> > ### Anything else:
> > not sure if thats actually an issue or is just a normal behaviour, but I remember back in the old days it used to rain everywhere
> 
> This is expected behavior. What is actually happening is you’re flying back and forth from the savannah biome to the river biome. In savannahs it won’t rain, but in the river biome it will.

oof closing then
