### ISSUE TITLE
offlineplayer.hasPlayedBefore() returns if a player is online and not if he played before

### ISSUE THREAD

**Issue by Hugo5000** [PaperMC/Paper#3356]
### What behaviour is expected:
offlineplayer.hasPlayedBefore() to return true after the player left for the first time.

### What behaviour is observed:
offlineplayer.hasPlayedBefore() returns if the player is currently online

### Steps/models to reproduce:
use offlineplayer.hasPlayedBefore() in a plugin command

### Plugin list:
- Chairs
- CoreProtect
- Essentials
- EssentialsAntiBuild
- EssentialsChat
- EssentialsProtect
- EssentialsSpawn
- LuckPerms
- Multiverse-Core
- PhantomEconomy
- PlotSquared
- AdvancedTowny
- Vault
- WorldBorder
- WorldEdit
- WorldGuard

### Paper build number:
git-Paper-282

![image](https://user-images.githubusercontent.com/50522012/81699852-2ebefe80-9468-11ea-8256-ca505ee12923.png)
![image](https://user-images.githubusercontent.com/50522012/81699857-31b9ef00-9468-11ea-98ba-2988ea806033.png)

**Comment by MeFisto94** [comment]
According to the code, this should read a `.dat` file from your overworld's playerdata folder, can you confirm that this file is delete when the player leaves etc?

Paper did modify that code a bit by lazy loading the WorldNBTStorage, but it doesn't look like this should cause your issue.

Try to check the file and maybe also without plugins (I'll try to reproduce it here as well)

**Comment by Proximyst** [comment]
![https://owo.whats-th.is/2eq7D1A.png](https://owo.whats-th.is/2eq7D1A.png)

```kotlin
@CommandAlias("hasplayedbefore|hpb|hasplayed")
object HasPlayedBeforeCommand : BaseCommand() {
    @Default
    @CommandCompletion("@players")
    fun root(sender: CommandSender, @Single player: String) {
        @Suppress("DEPRECATION") val target = Bukkit.getOfflinePlayer(player)
        sender.sendMessage("${target.name} has${if (target.hasPlayedBefore()) "" else " not"} played before")
    }
}
```

It works as intended with this test plugin as the only plugin.

**Comment by Hugo5000** [comment]
I have found how to recreate it, I should have mentioned that earlier but I am using a bungeecord to connect to the server. And having a bungeecord in online mode, and the server in offline mode, like it should be, has the server create the playerfile with the online uuid but checks for the offline uuid in the world folder.

**Comment by Proximyst** [comment]
![https://uwu.whats-th.is/76Jj5RB.png](https://uwu.whats-th.is/76Jj5RB.png)

This is through Waterfall.

**Spigot**
`server.properties` - `online-mode=false`
`spigot.yml` - `settings.bungeecord: true`
`paper.yml` - `settings.bungee-online-mode: true`

**Waterfall**
`config.yml` -
```yaml
online_mode: true
ip_forward: true
listeners:
- ping_passthrough: false
```

**Comment by Hugo5000** [comment]
oh I didnt see that `settings.bungee-online-mode: true`, sorry I only recently switched to paper
