### ISSUE TITLE
Light not getting calculated for a bukkit world generator

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/Paper#3357]
### What behaviour is expected:
Let there be light!
![https://i.imgur.com/CcCTIcr.jpg](https://i.imgur.com/CcCTIcr.jpg)

### What behaviour is observed:
No light ;(
![https://i.imgur.com/3xZ100P.png](https://i.imgur.com/3xZ100P.png)

### Steps/models to reproduce:
https://github.com/MiniDigger/worldgentest/blob/master/src/main/java/me/minidigger/worldgentest/LightTestGenerator.kt
`/mvc lighttest normal -g worldgentest:light`
`/mvtp lighttest`

Running `/paper fixlight` fixes it

### Plugin list:
Multiverse and Worldgentest

### Paper build number:
280

### Anything else:
Am scared in the dark ;(

**Comment by kashike** [comment]
> Am scared in the dark ;(

https://www.youtube.com/watch?v=kOL7aeIDruA
