### ISSUE TITLE
Command Block string length issue

### ISSUE THREAD

**Issue by AutismFather** [PaperMC/Paper#3358]
### Entering a command line into a command block that is greater than 256 characters:
sudo PlayerName ct command add /summon minecraft:dolphin ~ ~2 ~ {Moistness:2147483647, Passengers: [{"id": "drowned", Count:1, HandItems:[{},{id: trident, Count: 1, tag:{Enchantments:[{id: impaling, lvl:1}, {id: channeling, lvl: 1}]}}], HandDropChances:[0.0f,0.1f]}]}

### Errors at maximum string length and disconnects me from server:
io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (272 > 256)

### Steps/models to reproduce:
Simply type in more than 256 characters into a command block command line

### Plugin list:
N/A

### Paper build number:
281

**Comment by MrIvanPlays** [comment]
Not an issue, but rather limit set by mojang.

**Comment by Brokkonaut** [comment]
No. Mojangs command block command limit is 32500.

**Comment by Black-Hole** [comment]
That's a plugin issue. The plugin that is providing the command "sudo" is somehow executing that command as a chat message from the player.
The vanilla "execute" command don't have that limitation.

**Comment by aikar** [comment]
this is fixed in latest
