### ISSUE TITLE
Falling Blocks glitch/display issues

### ISSUE THREAD

**Issue by crysis992** [PaperMC/Paper#336]
This bug is about Falling Blocks, this bug exsist since build #767 - "Fix fallingblocks getting stuck on fences"

I'm using the plugin CubeRunner, which spawns alot of falling blocks in a repeating task via NMS/Reflection. This is the method it uses to spawn falling blocks:
(Tested on latest build - 782)

`try {
                        final Object craftWorld = Class.forName("org.bukkit.craftbukkit." + CubeRunner.NMS_VERSION + ".CraftWorld").cast(player.getWorld());
                        final Object world = craftWorld.getClass().getMethod("getHandle", (Class<?>[])new Class[0]).invoke(craftWorld, new Object[0]);
                        final Object entityBlock = Utils.getNMSClass("Block").getMethod("getById", Integer.TYPE).invoke(null, itemStack.getMaterial().getId());
                        final Object iBlockData = entityBlock.getClass().getMethod("fromLegacyData", Integer.TYPE).invoke(entityBlock, itemStack.getDurability());
                        final Object entityFallingBlock = Utils.getNMSClass("EntityFallingBlock").getConstructor(Utils.getNMSClass("World"), Double.TYPE, Double.TYPE, Double.TYPE, Utils.getNMSClass("IBlockData")).newInstance(world, l.getX(), l.getY(), l.getZ(), iBlockData);
                        entityFallingBlock.getClass().getField("ticksLived").set(entityFallingBlock, 1);
                        entityFallingBlock.getClass().getSuperclass().getMethod("setCustomName", String.class).invoke(entityFallingBlock, user.getUUID().toString());
                        entityFallingBlock.getClass().getSuperclass().getMethod("setCustomNameVisible", Boolean.TYPE).invoke(entityFallingBlock, false);
                        entityFallingBlock.getClass().getMethod("a", Boolean.TYPE).invoke(entityFallingBlock, true);
                        entityFallingBlock.getClass().getField("dropItem").set(entityFallingBlock, false);
                        world.getClass().getMethod("addEntity", Utils.getNMSClass("Entity"), CreatureSpawnEvent.SpawnReason.class).invoke(world, entityFallingBlock, CreatureSpawnEvent.SpawnReason.CUSTOM);
                        if (number % 2L != 0L) {
                            continue;
                        }
                        entityFallingBlock.getClass().getSuperclass().getField("motX").set(entityFallingBlock, (1.0 - Math.random() * 2.0) / 10.0);
                        entityFallingBlock.getClass().getSuperclass().getField("motY").set(entityFallingBlock, 0);
                        entityFallingBlock.getClass().getSuperclass().getField("motZ").set(entityFallingBlock, (1.0 - Math.random() * 2.0) / 10.0);
                        entityFallingBlock.getClass().getSuperclass().getField("velocityChanged").set(entityFallingBlock, true);
                    }`

It causes to spawn some glitching falling blocks, which cannot be removed until the server restarts. 
Anyways, it was working fine till the build 767. So i assume its a PaperSpigot related bug, not a plugin error.

Video about the issue:
https://youtu.be/DooDR3R0B-o

Edit: This does NOT affect the spigot jar / upstream

**Comment by zachbr** [comment]
Likely a result of https://github.com/PaperMC/Paper/commit/96a263cddf43ea443f01164b37bea5113a5c8a40

Needs testing/investigation.

**Comment by Postremus** [comment]
Will look into this.

**Comment by Postremus** [comment]
It is another case of https://bugs.mojang.com/browse/MC-90523.
World to test this against (contains a few of these glitched blocks at x850 y8 z1573): https://dl.dropboxusercontent.com/u/46071056/Minecraft/paper-%23336.zip
Spigot removes these glitched blocks, paper and vanilla just leave them be currently.

**Comment by ChagnonSebastien** [comment]
Hi, I am the developer of the CubeRunner plugin mentioned by crysis992.
Today a third server informed me about the glitching blocks.
I would like to know if anything will be done in the near future to solve this issue because it really breaks the gameplay of my minigame.
Thanks a lot.

**Comment by TNTUP** [comment]
@crysis992 Same here on my French Québec server, I'm on Paper 1.9.4 and it occurs. Hope a fix will be released (I guess it will be for 1.10.2 not in 1.9.4)

**Comment by meyden92** [comment]
It is now over 1 month since the report, are there any news? Since this prevents me from using paperspigot on my server :/

**Comment by TNTUP** [comment]
Didn't they fixed in 1.10.2? I've havent tried it so can't say it sorry

**Comment by Postremus** [comment]
No, not fixed in vanilla 1.10.2

2016-07-20 3:47 GMT+02:00 Yann notifications@github.com:

**Comment by mibby** [comment]
I am also affected by this on Paper 820.  Looking forward to a fix or workaround to this problem. :)

**Comment by zachbr** [comment]
Made configurable and disabled by default.
This is the best workaround that I'm aware of as of now.

EDIT: builds 823+
