### ISSUE TITLE
Server crash many times on Paper282 (not on Paper280)

### ISSUE THREAD

**Issue by radekklima21** [PaperMC/Paper#3363]
This is the part of server.log:
https://pastebin.com/n6Wgb8fU

And this is the part of GC log:
https://pastebin.com/48w90F5A

The problem never happened before

I dont know is problem happened by a lot of Old GC's (Pause Full) or the Pauses Full are happened by a server issue? Today is the first day I am using new Aikar flags. (And I updated to Paper282 from 280)

**Comment by Symphonic3** [comment]
Try without Aikars flags

**Comment by FabioZumbi12** [comment]
I got the same issue... changed to aikar's flags but the problems stills!!

Initially i suspected be my hd issue, but its not. The lag increases and then crash. I using a too old build and now i am testing if will crash.

**Comment by hurrgurl** [comment]
Been getting those for months, player moving too fast?

**Comment by Symphonic3** [comment]
This is still happening in the latest paper build (#354)
