### ISSUE TITLE
Add an @Async Annotation to Bukkit APIs

### ISSUE THREAD

**Issue by MeFisto94** [PaperMC/Paper#3369]
**Is your feature request related to a problem? Please describe.**
It's always a problem to be certain about what parts of the Bukkit API are safe to call async and which are not (without looking at the sourcecode). It's even worse that you can always call the API async and get away with it until one day, you don't.
Also it can't be the goal to have "async coding" consist of only chaining main thread enqueues.
That's why I'd propose two things as an ongoing process

**Describe the solution you'd like**
Annotate thread safe APIs with an `@Async` Annotation, so I can see this information with one click.
Maybe we would like to expand to `@Async(safe=false)` as well, so we can explicitly mark methods as NOT safe (because we won't get around to slam the Annotation on every method, that'd be a work in progress).

Additionally, we should try to look at most common methods and improve their safety.
For instance, let's take Player#sendMessage. Is it Async? One guy on Discord told me it's `practically safe` and we've been looking into the source code. It's safe as long as the `playerConnection` field isn't freed. An AtomicReference and a lock might help there or just not nulling the playerConnection but replacing it with a dummy connection until the `Player` is garbage collected (which probably is never, for flakey plugins, lol)

**Describe alternatives you've considered**
We need some form of declaration, even if it was a wiki, a txt file or whatever, however imo an Annotation is the only thing that is tied directly to the code and thus doesn't get out of sync as easy.

**Additional context**
The sendMessage example is intentional, because 99% of the commands consist of just sending messages and maybe a short hashmap lookup

**Comment by mikroskeem** [comment]
Should ask about this in upstream I think

**Comment by aikar** [comment]
This would be a rather small add.... almost nothing is.
but yes send message will be safe. itll be a huge break for that to ever not be true.

not going to do this.

**Comment by Toffikk** [comment]
Maybe ... , You should do it Yourself and then PR later.
