### ISSUE TITLE
Server crashes when trying to get a block of unloaded world

### ISSUE THREAD

**Issue by AsVaidas** [PaperMC/Paper#3370]
### Link/paste of stack trace
https://paste.gg/p/anonymous/3a99f129a167406bb52421838f64a223

### Plugin list:
Plugins (30): AdminSystem*, AsVaidasAPI*, AutoRestart*, BuildersWand, BungeeGuard, ChestSort, Events*, FactionWars*, GroupManager, GSit, Idea*, IllegalStack, MyCommand, Packages*, PlaceholderAPI, PlugMan, RanksTime*, TAB, TPSmeter*, Updates*, ZCAutoBots*, ZCBans*, ZCCrates*, ZCDeop*, ZCMainCore*, ZCMessages*, ZCPlayerLimit*, ZCTops*, ZCTrade*, ZCYouTube*
* - Programmed by me

### Actions to reproduce (if known):
IlleagalStack plugin tries to get a block type with getType() after the world was unloaded.
It should return a stack trace and don't allow that, but paper instead crashes the server

### Paper build number:
[06:02:19] [Server thread/INFO]: This server is running Paper version git-Paper-282 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by ghost** [comment]
stop illegalstack from performing such operations?

**Comment by HexedHero** [comment]
Version of IS?

**Comment by AsVaidas** [comment]
> stop illegalstack from performing such operations?

Paper should throw null pointer exception, not crash the server

**Comment by HexedHero** [comment]
Update ur IllegalStack, there was a recent fix for the fTimer

**Comment by AsVaidas** [comment]
> Update ur IllegalStack, there was a recent fix for the fTimer

Still testing that new version. I try to keep my plugins always up to date.
