### ISSUE TITLE
Add IsNullOrAir to ItemStack

### ISSUE THREAD

**Issue by Onidotmoe** [PaperMC/Paper#3371]
Similar to IsNullOrEmpty() in C#, this would be a nice quality of life improvement for Itemstacks and would reduce boilerplate code.

Basically it would turn this :

`((Carpet != null) && !Carpet.getType().isAir())`

into this :
`(!Carpet.IsNullOrAir()) `

Which is way cleaner

**Comment by stonar96** [comment]
If `ItemStack carpet` is `null` and there exists a method called `boolean isNullOrAir()` in `ItemStack`, then `carpet.isNullOrAir()` will throw a NPE. One possible solution is to create a `static` function in `ItemStack` that does this. `static boolean isNullOrAir(ItemStack itemStack)`

**Comment by Onidotmoe** [comment]
oh sorry, the method in C# goes like this `String.IsNullOrEmpty("String that could be null or empty")`
so the Paper method should look the same `ItemStack.IsNullOrAir(Carpet)`

**Comment by Proximyst** [comment]
There is already `Material#isAir`, so do your own null checks before checking an item's air-ness.

I personally do not see the need for a static utility method for this, as nullability is something each plugin should handle themselves (hey, Kotlin makes it really easy too! An item is air if `itemStackHere?.type?.isAir != false` returns `true`).

**Comment by A248** [comment]
In my opinion this is unnecessary. It's not hard to do a null check. From what I know, Paper is not a typical codebase – changes and diff should be minimized to reduce conflicts when pulling from upstream. This seems like an unnecessary addition.
