### ISSUE TITLE
Session.lock breaks daily

### ISSUE THREAD

**Issue by feroxmc** [PaperMC/Paper#3380]
### Link/paste of stack trace
The log is 177,000 lines in total so i'd been forced to cut it down because its just so big if you'd like the full file i will try and attach it to this.
https://gist.github.com/FeroxDrood/ca743d71fa1263d29dde14a74ccc0670

Also the end of the log is herehttps://gist.github.com/FeroxDrood/a7bfe5108e509dee1468d51f3812820b
Just a heads up that the crash report folder is generated but it is empty.

### Plugin list:
Plugins (79): AdvancedEnchantments, AdvancedPortals, AdvancedRegionMarket, AEEssentialsKitsAddon*, AEFixItemRepairing*, AntiCooldown, ArtMap, AsyncWorldEdit, AuctionHouse, BannerBoard*, BetterRTP, boosCooldowns*, Boss, BuycraftX, ChatColor2*, ChatFeelings, ChatManager, ChatReaction, ChestShop, Citizens, ClaimFly, ClueScrolls, CommandNPC*, CommandTimer*, CoreProtect, CrateReloaded, CustomGUI, DeluxeChat, DeluxeTags*, DragonDropElytra, EntityDetection, EpicHoppers, EpicRename, Essentials, EssentialsChat, EssentialsSpawn, ExtraContexts*, FarmLimiter, GriefPrevention, GSit, HeadDatabase*, HolographicDisplays, IllegalStack, IPWhitelist*, Jobs, LeaderHeadsRevamped, LibsDisguises, LimitPillagers, LuckPerms, Marriage*, mcMMO, MoreFish, MorphRedeem, Multiverse-Core, NoSpawnerChange, PhantomSpawnControl, PlaceholderAPI, PlayerVaults, PlayerWarps, PowerlessLamps*, ProtocolLib, PvPManager, QuickBoard*, Rankup, RawMsg, ResourceWorld, ShopGUIPlus, ShowItem, SuperbVote, SuperTrails*, SuperVanish, TAB, TitleManager, TradeMe, Vault, Votifier, WildStacker, WorldEdit, WorldGuard

### Actions to reproduce (if known):
N/A

### Paper build number:
Paper 1.15.2 Build 284

**Comment by feroxmc** [comment]
Full Log
[2020-05-16-1.log](https://github.com/PaperMC/Paper/files/4638107/2020-05-16-1.log)

**Comment by kickash32** [comment]
The server is failing to write files due to being unable to acquire a write lock on the files. This could be due to there being another server running in the same directory or the server does not have write permissions.

**Comment by feroxmc** [comment]
> The server is failing to write files due to being unable to acquire a write lock on the files. This could be due to there being another server running in the same directory or the server does not have write permissions.

I'm running Chown multiple times a day, also how would I close off the server running in the same directory? 

'chown mc10:mc10 -R /home/minecraft/servers/server10'

**Comment by aikar** [comment]
That isn't the issue here.

You have some plugin going insane and opening TONS of files. Potentially a plugin using Bukkit.getOfflinePlayers()

This is exceeding the servers open file handle limit, causing all of this.

The main plugin seen in the stack traces is superbvote

Try removing it and see if it continues.

But this isnt' a paper issue, so please use discord for assistance.

**Comment by aikar** [comment]
running chown could also be the source if its processing a lot of the files leaving handles open.
You should not be running that outside of one off scenarios.

**Comment by astei** [comment]
I don't think SuperbVote was the cause, only a victim caught in the crossfire.
