### ISSUE TITLE
Removing entity while ticking ?

### ISSUE THREAD

**Issue by Momonche** [PaperMC/Paper#3384]
### Link/paste of stack trace

https://pastebin.com/sHQM8eHh

### Plugin list:
Plugins (80): ActionBarAPI, AreaShop, ArmorEquipEvent*, AsyncWorldEdit, AvancedItemEffets*, Bank, BetonQuest, BlyatRPG, boosCooldowns*, Broadcaster, BungeeTabListPlus, ChestCommands, Citizens, ClearLag, CombatIndicator*, CommandHook, Core, CoreProtect, CrazyCrates, EnchLimiter, EpicSpawners, Essentials, EssentialsAntiBuild, EssentialsMysqlStorage, EssentialsSpawn, Factions, FBasics*, GemsEconomy*, HealthBar*, HelpopEra, HolographicDisplays, HolographicScoreboard*, Hub, IllegalStack, InfiniteAnvil*, InfiniteDispenserX*, Jobs, JSONAPI, LiteBans, Lores*, LuckPerms, Magic, MassiveCore, MineProtectEra, MobArena, MoneyPrinters, MovingDevApi, Multiverse-Core, Multiverse-Portals, MysqlPlayerDataBridge, NoCheatPlus, NoElytra*, OldCombatMechanics, OpenInv, PearlFix, PlaceholderAPI, PlayerHeads, PlugMan, ProtocolLib, ProtocolSupport, RewardPRO, RPGChest, RPGMenu, RubisEra, ScoreboardStats*, Sentinel, ServerSigns, ShopGUIPlus, SignEdit, SkinsRestorer, spark, TPBukkit, Vault, VentureChat, VoteBox, WarnBan, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Actions to reproduce (if known):
I'm not sure, but when a player is fighting  against Sentinel/Citizens NPC, sometime the server crash with the pastebin error

### Paper build number:
git-Paper-282 (MC: 1.15.2)
I'm going to update to 284 soon for more tests

**Comment by electronicboy** [comment]
`Removing entity while ticking!` is a side-effect of the watchdog, needs fixing, but, that is not your underlying issue here, your server took too long to tick; use discord for support, will keep this open given the underlying bug exposed here

**Comment by Momonche** [comment]
Little update of this, I think my issue is related to Citizens, I just find this error when my server crash
https://pastebin.com/n20qH5Jg
Maybe I have to create an issue on Citizens

**Comment by aikar** [comment]
No, it's a vanilla bug. It's just a bad race condition that we haven't gotten to fixing since it's low occurrence.

**Comment by electronicboy** [comment]
I fixed this fairly recently
