### ISSUE TITLE
Card is flooded with black spots-Paper Update Problem with Dynmap

### ISSUE THREAD

**Issue by Blueeyestar** [PaperMC/Paper#3386]
Paper version git-Paper-298 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Dynmap-Version: Dynmap-3.0-beta-10-spigot.jar

Since the update to Paper Version 298 this morning, black spots have appeared on all loaded zones. If you try to render it again it will get worse instead of going away.
Is there a paper update? before that everything was fine

I'll take the paper version again before the update Paper version git-Paper-284 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

the condition normalizes again and you can remove the black spots again with a radius render.

Therefore the problem must be in an update between the Paper version 284 -298.

I hope the problem can be found.

![dynmap](https://user-images.githubusercontent.com/35557302/82148182-1168a680-9853-11ea-9382-152bda4eecaf.png)

**Comment by sandtechnology** [comment]
Same issue there, and it will appear on all dynmap version, you can download the latest dev version there:https://dynmap.us/builds/dynmap/Dynmap-HEAD-spigot.jar
To Reproduce this is very easy, just install the latest paper and this plugin then do the full render via /dynmap fullrender world, you would see the black block on the web map:
![TIM截图20200518124332](https://user-images.githubusercontent.com/20417547/82175034-33bafc80-9905-11ea-8a23-67f803888a59.jpg)

Downgrade to Paper-284 fix this issue.

**Comment by aikar** [comment]
I know what issue is, but please do not call us "Paper-Spigot", that is not our name. It's just "Paper".

**Comment by Blueeyestar** [comment]
> 
> 
> I know what issue is, but please do not call us "Paper-Spigot", that is not our name. It's just "Paper".

Do you already know which update produces this error? I just want to know up to which version I can install the updates.

Thanks for the effort you make. You do a great job

**Comment by Blueeyestar** [comment]
Is the problem under treatment? there are already 17 new versions. I would like to be up to date: /

**Comment by aikar** [comment]
It is my priority for tonight. I was busy working on other feature for past 2 days that prevented me from being able to work on this, so now that's done I can knock this out.

**Comment by Blueeyestar** [comment]
great that's great. that will definitely please the others. You are doing a very important great job. You give joy to many users .. thank you for that

**Comment by deiphiz** [comment]
I was actually able to fix this on my server by updating to the latest release candidate of Dynmap: https://dynmap.us/builds/dynmap/ "Dynmap-3.0-RC2-spigot.jar"
Hope this helps anyone :)

**Comment by Blueeyestar** [comment]
I have just fully tested this and can confirm this. The new RC2 fixed the problem.

**Comment by Blueeyestar** [comment]
Great work. Thank you very much and stay healthy :)
