### ISSUE TITLE
Compass acts weird

### ISSUE THREAD

**Issue by nopjar** [PaperMC/Paper#3387]
### What behaviour is expected:
___What you expected to see___
That the compass of the player points to the right direction
### What behaviour is observed:
___What you actually saw___
When more then one player uses the compass (the compass-target is different for every player) all the other compasses are pointing to the wrong direction
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Set the compass-target for the players to different locations
### Plugin list:
___A list of your plugins___
Just a plugin, that only sets the new compass-target, nothing else
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-298 (MC: 1.15.2)
### Anything else:
___Anything else you think may help us resolve the problem___
Thats the code of the plugin and its a test plugin so I didnt spend time to check for every possible nullpointer..
```
package io.github.minecaftdev.testplugin;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.java.JavaPlugin;

public class TestPlugin extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        Bukkit.getServer().getPluginManager().registerEvents(this, this);

        getLogger().info("Plugin erfolgreich geladen!");
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {

        if (sender instanceof Player) {
            Player bukkitPlayer = (Player) sender;
            if (args.length == 0) {
                Location location = bukkitPlayer.getTargetBlockExact(20).getLocation();
                bukkitPlayer.setCompassTarget(location);
                bukkitPlayer.sendMessage("Location gesetzt zu: " + location.toString());
            }
        }

        return true;
    }

    @EventHandler
    public void onJoin(PlayerJoinEvent event) {
        ItemStack compass = new ItemStack(Material.COMPASS);
        ItemMeta compassMeta = compass.getItemMeta();
        compassMeta.setDisplayName(ChatColor.LIGHT_PURPLE + "Thats funny");
        compass.setItemMeta(compassMeta);
        event.getPlayer().getInventory().addItem(compass);
    }
}


```

**Comment by JRoy** [comment]
Not only are you 44 builds out of date but you are asking to fix a plugin that you haven't shared any code from. For plugin development support, go to the discord at https://discord.gg/papermc

**Comment by nopjar** [comment]
thanks, updated the information. I accidentally put in the wrong version.

**Comment by lols11** [comment]
I have this same issue on build 333. It looks like that after approaching a distance of about 50 blocks to the location indicated by the compass, the compass goes crazy

**Comment by electronicboy** [comment]
compass behavior is 100% controlled by the client, 
```
    public void setCompassTarget(Location loc) {
        if (getHandle().playerConnection == null) return;

        // Do not directly assign here, from the packethandler we'll assign it.
        getHandle().playerConnection.sendPacket(new PacketPlayOutSpawnPosition(new BlockPosition(loc.getBlockX(), loc.getBlockY(), loc.getBlockZ())));
    }
```

if that's incorrect, then either something else on the server is updating the position on the client, or, "that's just how the client works"
