### ISSUE TITLE
Random server crash

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#3389]
### Link/paste of stack trace

https://pastebin.com/raw/5V77F4sN

### Plugin list:
Plugins (46): AddEveryoneToScoreboardTeam, ArmorStandTools, BlockSpectatorWorldChanges, bPermissions, BrokkoCommandLogger, BrokkoSecurity, BungeeNCPNotify, CommandSigns, CreativeEntities, CreativeItemControl, CubeQuest, CubesideEventplan, CubesideSettings, CubesideStatistics, CubesideVoteManager, Essentials, FakePlotMe, GamesInWorlds, GlobalAutoMessage, GlobalChat, GlobalClient, GlobalPort, Head-Cases, InteractiveBookAPI, JnRmirrors, Multiverse-Core, MyHelpPages, NoCheatPlus, PlayerStatistics, PlayerUUIDCache, ProtocolLib, ProtocolSupport, ProtocolSupportAddons, ProtocolSupportVersions, RedstoneMechanics, ResourcePackUtils, SchereSteinPapier, SecurityTool, TeamspeakBridge*, VanishNoPacket, Vault, WESV, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Actions to reproduce (if known):
No idea. I had some crashes like this on the current build. Did never happen before on the older build.

### Paper build number:
This server is running Paper version git-Paper-bb4002d82 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-a6a197b11 (MC: 1.15.2)

**Comment by Aaron2550** [comment]
It literally says "do not report to paper", well anyway the logs r talking about protocol support so maybe thats where your issue lies... Have you checked their bugtracker if this is known?

**Comment by Brokkonaut** [comment]
> If you are unsure or still think this is a Paper bug, please report this to https://github.com/PaperMC/Paper/issues

I think its a paper bug. That version of ProtocolSupport did not cause any problems and there is nothing in their bug tracker. I just updated paper, nothing else.

**Comment by aikar** [comment]
reopening this ticket since there seems to be some issues still on sync loads.
latest helps a ton with some things, but still a bit more to go.

**Comment by aikar** [comment]
this was resolved around 308~ but obviously use latest
