### ISSUE TITLE
Modified Biome Names

### ISSUE THREAD

**Issue by WonderDave** [PaperMC/Paper#339]
Let me first say that this is an extremely minor issue (really more of a question/request).  It actually started with 1.9, and I submitted an issue report with Spigot back in March, but I never understood the explanation that was given, and my report was marked as "Invalid".  So, I figured I'd try here with Paper, hoping that I can at least get a response that makes sense to me.

A number of biome names now begin with "Mutated", instead of their specific variations.  For example, if I'm in a "Flower Forest" and press F3 on my Mojang client, it shows "Flower Forest".  But if I use "player.getLocation().getBlock().getBiome()" to display the biome name, it shows "MUTATED_FOREST".  The same is true for "Sunflower Plains", which Spigot/Paper shows as "MUTATED_PLAINS".  There are others.

There are also other differences in biome names.  For instance, "Savanna Plateau" is now called "SAVANNA_ROCK", while "Savanna Plateau M" is called "MUTATED_SAVANNA_ROCK" (Spigot used to call it "SAVANNA_PLATEAU_MOUNTAINS").  And the "Beach" biome is now called "BEACHES".  None of this was the case with Spigot 1.8.8, which had the biome names matching what the client displayed.

If I compare this [1.7/1.8 list](https://jd.bukkit.org/org/bukkit/block/Biome.html) with this [1.9/1.10 list](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html), I can see what appears to be the name changes.  Does anyone know why the biome names displayed by Spigot/Paper are different from what's shown by the client, and is it possible to have them changed so that they match what the client displays?

For what it's worth:  This server is running Paper version git-Paper-784 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)

**Comment by Black-Hole** [comment]
There was no need to change the names in 1.9. But now they are changed and will stay this way to not break plugins again.
You could write your own mapping function that maps each biome to a fancy name or old names to the new ones.

**Comment by MrPowerGamerBR** [comment]
Now I'm curious... Why did they change the biomes enums?

Also, why did they add "MUTATED_" to almost every biome ID?

**Comment by zachbr** [comment]
Looks like they updated the API's biome enum to reflect the NMS biome naming as described in `net.minecraft.server.BiomeBase`. I've listed out these same definitions below:

`"ocean", "plains", "desert","extreme_hills", "forest", "taiga", "swampland", "river", "hell", "sky", "frozen_ocean", "frozen_river", "ice_flats", "ice_mountains", "mushroom_island", "mushroom_island_shore", "beaches", "desert_hills", "forest_hills", "taiga_hills", new BiomeTaiga(Biome
 "smaller_extreme_hills", "jungle", "jungle_hills", "jungle_edge", "deep_ocean", "stone_beach", "cold_beach", "birch_forest", "birch_forest_hills", "roofed_forest", "taiga_cold", "taiga_cold_hills", "redwood_taiga", "redwood_taiga_hills", "extreme_hills_with_trees", "savanna", "savanna_rock", "mesa", "mesa_rock", "mesa_clear_rock", "void", "mutated_plains", "mutated_desert", "mutated_extreme_hills", "mutated_forest", "mutated_taiga", "mutated_swampland", "mutated_ice_flats", "mutated_jungle", "mutated_jungle_edge", "mutated_birch_forest", "mutated_birch_forest_hills", "mutated_roofed_forest", "mutated_taiga_cold", "mutated_redwood_taiga", "mutated_redwood_taiga_hills", "mutated_extreme_hills_with_trees", "mutated_savanna", "mutated_savanna_rock", "mutated_mesa", "mutated_mesa_rock", "mutated_mesa_clear_rock"`

As @Black-Hole said, re-changing them now that they've been changed once already is only going to make compatibility a mess. If they choose to change them each and every release we can perhaps look into a Paper-API biome enum, but for now I don't see any need.

**Comment by Black-Hole** [comment]
Looking at the code it seems a bit easier to just use the internal Minecraft names for biomes:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/block/CraftBlock.java#327

There are only a few mutated biomes with a special name in the client: Sunflower Plains, Flower Forest, Ice Plains Spikes and Mesa (Bryce).

And there is an error in the wiki, there is no biome with ID 128 in the code:
http://minecraft.gamepedia.com/Data_values#Biome_IDs
