### ISSUE TITLE
Server startup error - Server-Worker-4 died

### ISSUE THREAD

**Issue by Nezz202** [PaperMC/Paper#3392]
### Link/paste of stack trace

https://pastebin.com/jHb9VDmH
https://pastebin.com/VCZXdfmt

### Plugin list:
```
 Plugins (70): BannerBoard*, BlockParticles, BossShopPro, BuycraftX, ChatControl, ChatReaction, Citizens, CitizensCMD, ClearLag, ClueScrolls, CommandSigns, Core, CrateReloaded, CustomEnderChest, DiceFurniture, EditableSign, Essentials, EssentialsChat, EssentialsSpawn, FeatherBoard*, FurnitureLib, GPAccruals*, GriefPrevention, Harbor, HeadDatabase*, HolographicDisplays, HolographicExtension*, ImageOnMap, LimitPillagers, LiteBans, LuckPerms, mcMMO, MineableSpawners, Multiverse-Core, MVdWPlaceholderAPI*, OpenInv, ParagonAdvent, ParagonAntiBoatFly, ParagonChatBattle, ParagonChestShops, ParagonCoreSpigot, ParagonEvents, ParagonGPAlias*, ParagonMarriage, ParagonMathBattle, ParagonParkour, ParagonPerms, ParagonPlayTimePAPI*, ParagonRestarts, ParagonTags, ParagonUpdater, ParagonWild, PartyAndFriendsGUI, PlaceholderAPI, PlayerParticles, PlugMan, ProtectionLib*, ProtocolLib, SimplePets, Spartan, TAB, TitleManager*, TradePlus, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags
```

### Actions to reproduce (if known):
Our server restarts every 6 hours. Upon the server going through its standard startup, it gets to a point and just hangs until this error appears. I have to Ctrl+C the server, and restart it maunally (in which case it still sometimes fails to start. It's not everytime the server restarts, which is making me worried as to actually whats causing this. Other than the paper version, and the updated jvm arguments from a couple of weeks ago, nothing else to me knowledge has been changed on the server itself.

I've had a google, and I can't seem to find any similar issues around. So if anyone has suggestions or need more info from me, let me know and I'll get this.

### Paper build number:
First noticed on Build Paper-1.15.2#282, but also present on latest at time of writing:

```
[11:37:19 INFO]: This server is running Paper version git-Paper-299 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[11:37:19 INFO]: Checking version, please wait...
[11:37:20 INFO]: Previous version: git-Paper-282 (MC: 1.15.2)
[11:37:20 INFO]: You are running the latest version
```

**Comment by MaxWarsNicht** [comment]
I got the same thing.

> Plugins (23): AsyncWorldEdit, BlockUpdateCommand, BungeeTabListPlus, Citizens, CoreProtect, CustomHeads*, dynmap*, Elevator, LagMonitor*, LuckPerms, Multiverse-Core, OldCombatMechanics, PlaceholderAPI, PlugMan, ProtocolLib, SimpleUtilities, Vault, Vehicles, VoxelSniper*, WorldBorder, WorldEdit, WorldEditSUI, WorldGuard

**Comment by aikar** [comment]
this is fixed in 325
