### ISSUE TITLE
Asynchronous entity ticking

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [PaperMC/Paper#3393]
**Is your feature request related to a problem? Please describe.**
mobs are infernally lagging at 1.15 and create a huge load on the server even in small quantities

**Describe the solution you'd like**
Add Asynchronous entity ticking

**Describe alternatives you've considered**
I can only say that it is possible and it really works, but I can't help you with the implementation

**Additional context**
Video https://vk.com/ks?z=video59649933_456239586%2Fvideos59649933%2Fpl_59649933_-2

**Comment by Envel-Nikita-Gutsenkov** [comment]
Look at tickEntities() and distribute them to different threads, simultaneously correcting the concurrent modification exception that appears

**Comment by Cryptite** [comment]
https://github.com/PaperMC/Paper/projects/3

**Comment by Envel-Nikita-Gutsenkov** [comment]
> 
> 
> https://github.com/PaperMC/Paper/projects/3

slightly different things

**Comment by zachbr** [comment]
Parallel processing in the linked project is the only implementation we will stomach and it is covered with enough potential problems to be a 'nice to have' for later. Doing things _safely_ and interacting with plugins _safely_ significantly complicates things, as every random summer fork that adds this already runs into.
