### ISSUE TITLE
Add `Cause` to `WeatherChangeEvent` and `ThunderChangeEvent`

### ISSUE THREAD

**Issue by userMacieG** [PaperMC/Paper#3397]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Create something similar to [LightningStrikeEvent.Cause](https://papermc.io/javadocs/paper/1.15/org/bukkit/event/weather/LightningStrikeEvent.Cause.html) for [WeatherChangeEvent](https://papermc.io/javadocs/paper/1.15/org/bukkit/event/weather/WeatherChangeEvent.html) and [ThunderChangeEvent](https://papermc.io/javadocs/paper/1.15/org/bukkit/event/weather/ThunderChangeEvent.html)

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by Machine-Maker** [comment]
I don't think there are enough causes for each of those right?

**Comment by Chew** [comment]
What would be the causes of the Weather/Thunder? Thunder's cause is always lighting (I believe) and Weather is just natural.

**Comment by Proximyst** [comment]
Plugins and commands can also change weather. One might want a plugin to disable natural weather changes, while allow forced (plugin/command) ones.

**Comment by Chew** [comment]
Ah, alright, makes sense

**Comment by Machine-Maker** [comment]
*not stale anymore*
