### ISSUE TITLE
`PortalCreateEvent` doesn't work

### ISSUE THREAD

**Issue by userMacieG** [PaperMC/Paper#3398]
### What behaviour is expected:
Call event when portal is created.

### What behaviour is observed:
Event is not called when portal is created.
Tested on nether portal and end portal.

### Steps/models to reproduce:
Create listener with event `PortalCreateEvent` and make simple debug.
Example: 
![image](https://user-images.githubusercontent.com/24211405/82259158-6abbfd00-995b-11ea-8262-5a6a6a1491da.png)

### Plugin list:
Only custom plugin containing this event.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Aaron2550** [comment]
Well, what was the problem?
