### ISSUE TITLE
Restart not working

### ISSUE THREAD

**Issue by NiveryIGN** [PaperMC/Paper#3399]
### What behaviour is expected:
___Server restart___

### What behaviour is observed:
___Server stopped without starting back up___

### Steps/models to reproduce:
___I read that I could use a script but I have no idea how to do it___

### Plugin list:
___ABlockLimit, ASkyBlock, AutoMessage, Banknotes, BattleLevels, BuycraftX, ChestShop, ClearLag, CombatLog, CustomHelp, EasySetSpawn, EnhancedBalTop, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FeatherBoard, HeadDrops, Holograms, LiteBans, LockettePro, LootProtect, Multiverse-Core, MVdWPlaceholderAPI, NoFlyZone, PermissionsEx, PingPlayer, PlayerVaults, PotionStacker, SellWands, ShopGUIPlus, ShopGUIPlusSilkSpawnersBridge, SilkSpawners, StaffChat, TAB, Timber, Vault, ViaBackwards, ViaVersion, VoidSpawn, WorldEdit, WorldGuard___

### Paper build number:
___Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)___

### Anything else:
___I have no clue but I could restart when I had craftbukkit 1.12.2 then I switched to PaperMC for plugin issues and it's no longer working___

**Comment by utkudotdev** [comment]
So you have a restart script, right? Like a .bat or .sh file?

**Comment by electronicboy** [comment]
1.12.2 is no longer supported, nor do we recommend the use of spigots built-in restart feature, it's flawed in that it will try to start the new server before the current has fully closed, which can break the new starting process in varying manners
