### ISSUE TITLE
Error obtaining version information

### ISSUE THREAD

**Issue by L4BORG** [PaperMC/Paper#34]
```
>ver
[02:38:26 INFO]: This server is running CraftBukkit version git-PaperSpigot-"ee63dbe" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[02:38:26 INFO]: Checking version, please wait...
[02:38:27 INFO]: Error obtaining version information
```

looks like tacos got misplaced...

**Comment by zachbr** [comment]
You built that jar with PaperTools right?

**Comment by zachbr** [comment]
[20:59:40] Z750 | UUID00: your issue, you built that jar with PaperTools right?
[20:59:57] UUID00 | hm, yeah

This was intentionally done when we switched to the Paperclip system, PaperTools is on life support until 1.9, at which point it's dead.

**Comment by Tiippex** [comment]
Sorry, I still have an issue with that. Im using the Paper1305 and downloaded the paperclip (https://ci.destroystokyo.com/job/Paper/1305/)
![Error](http://tiippex.de/pics/i/4llbj.png)

**Comment by electronicboy** [comment]
working fine here, looks like somebody either had a network issue when you tried it, or the issue is on your end

**Comment by Tiippex** [comment]
I already have this problem for a long time, but I never had time to report it.

When I use spigot it works without problems :o
What could be a possible problem on my side? Is it maybe that my server does not accept the SSL certificat?

@zachbr do you have any idea?

**Comment by NoopyyGaming** [comment]
I got this too but only : Error obtaining version information
