### ISSUE TITLE
NBT tag order changes when dropping item. (Specifically inside item name and lore)

### ISSUE THREAD

**Issue by iJordi** [PaperMC/Paper#3400]
### What behaviour is expected:
In vanilla singleplayer, the order from the tags for items obtained using /give stays the same after dropping the item and picking it back up. 

### What behaviour is observed:
Dropping the item changes the order of its tags. See screenshot below
I specifically experienced this with the text and the text formatting parts
Normally should not be an issue, but this messes up custom trades for villagers

### Steps/models to reproduce:
-  give yourself an item and check its nbt data. (Command I was using for screenshot)
` give @p minecraft:gold_nugget{display:{Name:'{"text":"Gold Coin","color":"gold","bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false}'},CustomModelData:123456} 64
`
- take the item out of your inventory (drop it or put it in a chest) and get it back
_Middle clicking in creative mode also changes the nbt of the copy_
- check the nbt data again.

### Plugin list:
Worldedit

### Paper build number:
282 

### Anything else:
Discovered while trying to set up custom villager trades. Villagers accept the items when received through /give, but don't want to trade it anymore if the item has been thrown on the ground anymore. After testing and having the issue multiple times, checked the dat files and compared them with vanilla singleplayer behaviour. (top says spigot, I mean Papermc)
![papermc tags](https://user-images.githubusercontent.com/17070428/82312150-f159f400-99c6-11ea-883f-cc27fae3d2a1.png)

_Note for anyone having problems with this too, it can be easily be worked around by changing the order in the /give command; putting formatting first, then text_

**Comment by Prof-Bloodstone** [comment]
Related:
https://github.com/PaperMC/Paper/issues/3110
https://github.com/PaperMC/Paper/issues/3306

As mentioned in the second ticket:
> HashMap ordering is not guaranteed.

**Comment by aikar** [comment]
https://github.com/PaperMC/Paper/issues/3306#issuecomment-625433320

Won't be fixed. Though it is odd /give isn't auto fixed.
