### ISSUE TITLE
Clarify which armorstand changes were implemented in Paper build 274

### ISSUE THREAD

**Issue by Shynixn** [PaperMC/Paper#3401]
### What behaviour is expected:
Armorstands tick and work in the same way as in Paper build 273

### What behaviour is observed:
The custom armorstand entity using heavy NMS code in my plugin [BlockBall](https://github.com/Shynixn/BlockBall) started to fall through the map and is no longer able to move. I have debugged my plugin but I did not discover any obvious changes.

### Steps/models to reproduce:
~

### Plugin list:
BlockBall.jar

### Paper build number:
git-Paper-274 (MC: 1.15.2) 

### Anything else:
Hello!

Can you please clarify or show me the changesets of Paper build 274? I have received multiple reports that my plugin no longer works and I would like to continue to support Paper. 

My plugin also requires the following setting in the paper.yml to work. 
``armor-stands-tick: true``

**Comment by Prof-Bloodstone** [comment]
According to: https://papermc.io/ci/job/Paper-1.15/274/
Patches added in that version:
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0515-Ensure-Entity-AABB-s-are-never-invalid.patch
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0517-Wait-for-Async-Tasks-during-shutdown.patch
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0518-Optimize-WorldBorder-collision-checks-and-air.patch

I believe you are only interested in the first one.

**Comment by Shynixn** [comment]
Thank you! I'll check it...

**Comment by Shynixn** [comment]
I have found the compatibility issue in my plugin and I fixed it.
The problem is that PaperSpigot changes the NMS method called ``setPositionRaw(double d0, double d1, double d2)`` that it does no longer just "set the raw position" but instead executes additional code which clashes when overwriting the NMS method called ``recalcPosition`` which I use to modify the bounding box of the soccer ball. 

In order to fix this, I have replaced the call of setPositionRaw with field calls. 

Again, thank you for your help, this issue can be closed.

**Comment by aikar** [comment]
I would recommend instead setting the entities width and height correctly instead, and then the AABB would of been calculated correctly.

That was the point of the change, to ensure you always have a valid AABB anytime position is update so that recalcPosition does compute the same coords as your setPositionRaw

**Comment by Shynixn** [comment]
I'll take a look into this.
