### ISSUE TITLE
Make event `PlayerEggThrowEvent` cancellable

### ISSUE THREAD

**Issue by userMacieG** [PaperMC/Paper#3404]
**Is your feature request related to a problem? Please describe.**
No ability to block egg throwing.

**Describe the solution you'd like**
Give ability to cancel event by `event.setCancelled()`

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by electronicboy** [comment]
`PlayerEggThrowEvent#set/isHatching` already exists for this

**Comment by userMacieG** [comment]
> `PlayerEggThrowEvent#set/isHatching` already exists for this

How `isHatching` give ability to block egg throwing?

**Comment by harrisonglp** [comment]
Use ProjectileLaunchEvent to cancel egg throwing.

**Comment by electronicboy** [comment]
Oh, the actual throwing of the egg, no; That event is far too late for that, the thrown projectile is already in the world, ^
