### ISSUE TITLE
EntityPickupItemEvent not firing when player picks up item

### ISSUE THREAD

**Issue by TheBenHC** [PaperMC/Paper#3408]
### What behaviour is expected:
When a player picks up an item, the EntityPickupItemEvent should fire, because a player is an entity.

### What behaviour is observed:
The event does not fire. It is still possible to listen for the PlayerPickupItemEvent (which does fire), but this class is deprecated and so too are all of its methods.

### Steps/models to reproduce:
On a fresh 1.15.2 Paper Server, add a plugin with the two listeners below. Only the one containing the PlayerPickupItemEvent will fire - the other will not.

### Plugin list:
The only plugin I have installed is one I used to test this bug. It contains two event handlers:

    @EventHandler
    public void onEntityItemPickup(EntityPickupItemEvent event) {
    	this.getLogger().log(Level.INFO, "[ENTITY] Picked up " + event.getItem().getName());
    }
    
    @EventHandler
    public void onPlayerItemPickup(PlayerPickupItemEvent event) {
    	this.getLogger().log(Level.INFO, "[PLAYER] Picked up " + event.getItem().getName());
    }

### Paper build number
Paper 1.15.2, Build #301

**Comment by faustinozanetto** [comment]
Im having the same issue
