### ISSUE TITLE
Fire ticking causing lag in nether if too many chunks are loaded? (keep-spawn-loaded)

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#341]
I'm not sure about this, but it seems the more I increase the radius of spawn chunks to keep loaded, the more lag there is in nether from Fire ticks in block schedule

At 128 chunk radius it goes to 5 tps with no players even on

This is with 80 radius
https://timings.aikar.co/v2/?id=a0aed12bfbd442a8b8aabfc91104ccab

Build 785

**Comment by aikar** [comment]
You are loading 64k chunks is why. That value is in chunks, not blocks. Please update your config to 8
