### ISSUE TITLE
Paper Build 282 - 301 Hoppers not transferring Block broke by a Block Breaker plugin. 

### ISSUE THREAD

**Issue by PhantumOne** [PaperMC/Paper#3412]
### What behaviour is expected:

When a block is broken above a Hopper using any block breaker plugins (I have tested with BlockBreaker, Craftbook and EpicHoppers) it should be transferred to the chest below it.
 
### What behaviour is observed:

When the block breaker breaks a block, you see the Hopper take it, but the chest and hopper are empty.

### Steps/models to reproduce:

Install any Paperclip after build 281 (282 to 301) and install the plugins I listed below 

### Plugin list:

EssentialsX-2.17.2.0 (Includes AntiBuild, Chat, Protect and Spawn)
FabledSkyblock 2.2.11
Vault 1.7.2-b107
worldedit-bukkit-7.1.0
worldguard-bukkit-7.0.2

### Paper build number:

Build 282 thru 301)

### Anything else:

I have attached links to to videos. 

This is FabledSkyblock showing the Hopper working correctly on build 281 and not working on build 282 and 301.

[Link to video](https://screenrec.com/share/nGtXyb2Hg8) 

This video show it not working in build 301 in the Overworld (I just did not want to load 281 and 282 to show it working in 281 and not 282 - redundant).

[Link to video](https://screenrec.com/share/mjA4VIpkPy)

**Comment by Tina-King** [comment]
Im also having this same issue, seems to be fixed on latest spigot so hopefully next time paper updates to latest spigot this may fix.

**Comment by Euphillya** [comment]
Always not working....
