### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MithrandirCraft** [PaperMC/Paper#3416]
### Link/paste of stack trace

https://gist.github.com/MithrandirCraft/d0747afab24054c9a184ad76c1a243ee

### Plugin list:
40ServidoresMC, AdvancedPortals, AntiXrayHeuristics, AuthMe, AutoMessage*, BungeeTabListPlus, Chairs, ChatControl, ClearLag*, CoreProtect, CrazyCrates, ElytraBalance, EnjinMinecraftPlugin, Essentials, EssentialsSpawn, FastLogin, GriefPrevention, GriefPreventionFlags, HideJoinLeaveMessages*, HolographicDisplays, HolographicScoreboard*, KickFromClaim, LibsDisguises, LuckPerms, MarriageMaster, Matrix, MiniaturePets*, MythicMobs, PlaceholderAPI, PlayerHeads, PremiumVanish, ProtocolLib, RandomTeleport, Shopkeepers, SkinsRestorer, Spawner, SSX-Connector*, StatsPvP*, TouchscreenHolograms, Vault, Votifier, VotingPlugin, WorldEdit

### Actions to reproduce (if known):
Possibly teleporting using essentials's /tpa, since there was a teleportation occuring right before the error, but I presume any sort of large movement would cause this, since I've been having all sorts of loading trouble with chunks, (suposadly derived from player movement as you guys stated).

### Paper build number:
git-Paper-304 (MC: 1.15.2)

**Comment by Athemis** [comment]
I encountered a similar crash but without any usage of teleport commands prior to the crash. Logfile and crash report: 

https://gist.github.com/Athemis/02457b182d23b9981f8fceda5c10b351

### Plugin list:
EssentialsX, EssentialsXChat, Chunkmaster, LuckPerms, Vault

### Paper build number:
git-Paper-304 (MC: 1.15.2)

**Comment by aikar** [comment]
Please try build 305, which contains a huge amount of improvements. Please open a NEW issue if a new issue is found.
