### ISSUE TITLE
Chunk Generation w/ WorldBorder Severely Slowed

### ISSUE THREAD

**Issue by partydev** [PaperMC/Paper#3417]
Paper has recently put forth some changes in the more recent versions that severely slow down chunk generation with worldborder. I also saw a huge slowdown in chunkmaster. In my testing I compared Paper-304 with Paper-283. 

In this gist you can clearly see that world generation speed has slowed by 3-4x, compared to previous builds. I think this should be addressed or looked into.

Both tests were run with 5GB of memory allocated to the server. Both using a normal world.

https://gist.github.com/bartyrealms/529321077029ff2c9bdb0e9a005a50cd

As of right now our world generating server is permanently stuck on Paper-283.

**Comment by Proximyst** [comment]
Is it possible for you to try doing a binary search (divide in 2, try both halves, repeat) to find out which patch(es) did the regression(s)?

**Comment by fredagsguf** [comment]
Can confirm this is happening aswell on my server, many players experience chunks right beside them not being loaded.

**Comment by Proximyst** [comment]
This is the "faulty" commit, by the way: https://github.com/PaperMC/Paper/commit/84673141a03c946c3e95444abcb3c7fd513f8c79

From the looks of how slow it is to pregen on new builds, try pregenning on b284 (or earlier), then play on b304+. According to Aikar, b304 should have good performance boosts to the player's eye (but NOT to WorldBorder's fill), but I haven't tested that myself so I'm trusting his word there.

**Comment by radiant-ai** [comment]
Hello, I have same problem. Any player can cause LARGE lag spikes and thread deadlocks flying elytras (according to logs). There is no such problem with Spigot builds or older Paper builds, this might be a bug in new Paper builds.

**Comment by aikar** [comment]
Please try build 305, which contains a huge amount of improvements. Please open a NEW issue if a new issue is found.

I was able to generate with world border even on my old cpu much faster now.
