### ISSUE TITLE
kicked due to keepalive timeout!

### ISSUE THREAD

**Issue by jontyms** [PaperMC/Paper#3420]
### What behaviour is expected:
___What you expected to see___
Not getting repeatedly kicked or random teleport to  same location 
### What behaviour is observed:
___What you actually saw___
getting repeatedly kicked and random teleport to  same location 
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
join server 
### Plugin list:
___A list of your plugins___
none 
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-304 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___
server console https://pastebin.com/Er7rDcwd

**Comment by jontyms** [comment]
Can't interact with any containers

**Comment by jontyms** [comment]
tested in paper 205 same issue

**Comment by Proximyst** [comment]
You just have a horrible connection to the host or your packets are otherwise being lost or delayed a lot.

See: https://github.com/PaperMC/Paper/issues/895#issuecomment-372175216

**Comment by aikar** [comment]
as proxi mentioned, see linked issue
