### ISSUE TITLE
Picking up shot arrows doesn't fire EntityPickupItemEvent

### ISSUE THREAD

**Issue by TheBenHC** [PaperMC/Paper#3421]
### What behaviour is expected:
When a player picks up an arrow which has been shot, an EntityPickupItemEvent should fire, because a player is an entity and an arrow is an item.

### What behaviour is observed:
Both the PlayerPickupItemEvent and PlayerPickupArrowEvent are fired. However, the PlayerPickupItemEvent class has been deprecated, and since the PlayerPickupArrowEvent is just a subclass of that, its methods are deprecated as well.

### Steps/models to reproduce:
On a fresh 1.15.2 Paper server, run a plugin with the following three event handlers:

    @EventHandler
    public void onEntityItemPickup(EntityPickupItemEvent event) {
    	this.getLogger().log(Level.INFO, "[ENTITY ITEM PICKUP] Picked up " + event.getItem().getName());
    }
    
    @EventHandler
    public void onPlayerItemPickup(PlayerPickupItemEvent event) {
    	this.getLogger().log(Level.INFO, "[PLAYER ITEM PICKUP] Picked up " + event.getItem().getName());
    }
    
    @EventHandler
    public void onPlayerArrowPickup(PlayerPickupArrowEvent event) {
    	this.getLogger().log(Level.INFO, "[PLAYER ARROW PICKUP] Picked up " + event.getItem().getName());
    }

Then, shoot an arrow and allow it to land on the ground. When you go to pick it up, the EntityPickupItemEvent will not fire, but the other two will. Example of what you would see:

[20:53:45 INFO]: [TestPlugin] [PLAYER ITEM PICKUP] Picked up Arrow
[20:53:45 INFO]: [TestPlugin] [PLAYER ARROW PICKUP] Picked up Arrow

### Plugin list:
Only the plugin described above.

### Paper build number:
Paper version git-Paper-301 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Machine-Maker** [comment]
PlayerPickupArrowEvent isn't deprecated. And neither are its methods.

**Comment by TheBenHC** [comment]
@Machine-Maker As I mentioned above, PlayerPickupArrowEvent extends PlayerPickupItemEvent, which is a deprecated class.

Therefore, doing something like the following would result in warnings:
```
    @EventHandler
    public void onPlayerArrowPickup(PlayerPickupArrowEvent event) {
    	event.setCancelled(true); // Would generate a warning, since setCancelled(...) is deprecated in the PlayerPickupItemEvent class
    }
```

**Comment by Machine-Maker** [comment]
@TheBenHC I don't see deprecation warnings when I paste exactly what you put above. 
![image](https://user-images.githubusercontent.com/15055071/100958155-a8840b80-34d0-11eb-943e-c424ef9a6645.png)


Also, correct me if I'm wrong, but I only see logic for player's picking up arrow entities, so should EntityPickupItemEvent be fired when picking up an arrow entity?
