### ISSUE TITLE
Issue with Item Name in new Serialization API to byte[]

### ISSUE THREAD

**Issue by minoneer** [PaperMC/Paper#3424]
Thanks for the new ItemStack serialization API introduced in build 298 - it should solve many issues I currently have with the Bukkit ItemStack serialization. I just played around with it considering to migrate my plugin and discovered that there is an Issue serializing/deserializig custom ItemStack names. Would be great to get it fixed!

### What behaviour is expected:
Serializing and then deserializing a named item should result in an identical ItemStack

### What behaviour is observed:
When serializing and then deserializing a named item, the name contains the entire JSON object instead of just the text.

### Steps/models to reproduce:
Take an ItemStack with a custom name (either by Plugin or a native one like an ominous banner). Then serialize it via `ItemStack#serializeAsBytes()` followed by `ItemStack.deserializeBytes(...)`.

### Paper build number:
Paper version git-Paper-304 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
Examples after deserialization:

![2020-05-21_14 37 42](https://user-images.githubusercontent.com/6442649/82559897-af6cb180-9b70-11ea-8e42-4e30dccf7631.png)
![2020-05-21_14 37 46](https://user-images.githubusercontent.com/6442649/82559902-b0054800-9b70-11ea-8476-a30164c84661.png)

**Comment by minoneer** [comment]
The same issue occurs with the content of a Book and Quill. In contrast, already signed books are identical to the original stack as expected.

![2020-05-21_14 45 39](https://user-images.githubusercontent.com/6442649/82560478-d37cc280-9b71-11ea-9d33-5a7f295a7774.png)

**Comment by Proximyst** [comment]
I believe this is due to https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0463-Add-Raw-Byte-ItemStack-Serialization.patch#L93 which was done by aikar right before the merge.

**Comment by aikar** [comment]
Dangit forgot to pass that dataVersion variable in place of that -1.

**Comment by minoneer** [comment]
Thanks for the quick fix!
