### ISSUE TITLE
 Illegal Entity bounding box attempt on 

### ISSUE THREAD

**Issue by Blueeyestar** [PaperMC/Paper#3427]
I installed paper version 305 today.
When I started the server, the server no longer started. instead I got a permanent error message in the console:

https://pastebin.com/dNmaF9aj

I had to kill the server otherwise the loop would not stop. Only when I imported the Paper Version 304 back on the server did everything go back to normal.

I assume it has something to do with the update [281181c] Use saner Entity bounding box limits.

**Comment by aikar** [comment]
I just pushed fix for this in 306.

**Comment by Blueeyestar** [comment]
Thank you and a pleasant weekend :)
