### ISSUE TITLE
dynmap issue on paper-307.jar

### ISSUE THREAD

**Issue by IIIVVIII** [PaperMC/Paper#3431]
dynmap issue on 
paper-307.jar

![image](https://user-images.githubusercontent.com/34328781/82682585-ed4d0100-9c68-11ea-8766-e96de88a8cd3.png)

**Comment by 20BBrown14** [comment]
Also having this issue but I'm on Paper-304

**Comment by IIIVVIII** [comment]
Dynmap-3.0-RC2-spigot.jar  solve this problem
