### ISSUE TITLE
Very high PlayerChunkMap tick times

### ISSUE THREAD

**Issue by HexedHero** [PaperMC/Paper#3438]
###  Timings or Profile link:
https://spark.lucko.me/#5kGlwjLkzm
https://spark.lucko.me/#0twrmT1JO8

### Description of issue:
Since updating to the recent paper builds I've been getting a lot of high tick times and above is spark reports with tracking only ticks over 100ms. If I downgrade to paper 247 this issue completely goes away.

I had a week of being sick and wasn't home, when I got back I updated from 245 to I think 283 at the time and saw a few issues of high tick times, so I kept updating hoping there were just some issues needed to be ironed out but here we are at 309 (now 311) and I'm still having issues so I downgraded to 283 and checked for any possible plugin that might be doing anything but no luck so I downgraded to 247 and to my surprise the high tick times completely went away so I've been tracking the issues for the last few days on the latest paper at the time and found that over the uptime of the server it gets worse and worse starting at 120ms+ than after a good 8+ hours uptime, it'll start doing almost 300ms tick times, all spark reports show it being the PlayerChunkMap/Broadcast.

### Paper build number:
Version 309

Thank you for everything, I am really frustrated and completely stuck on what to do. I will continue to update and check for more high tick times.

**Comment by aikar** [comment]
as discussed on discord, caused by plugins.
