### ISSUE TITLE
Flying machines break on chunk borders

### ISSUE THREAD

**Issue by Gerrygames** [PaperMC/Paper#3439]
### What behaviour is observed:
Flying machines / redstone contraptions with slime/honey blocks at chunk borders break when chunks are loaded/unloaded.

### Steps/models to reproduce:
https://youtu.be/K7sLV5B_qWU

### Paper build number:
Paper 1.15.2 build 309

### Anything else:
This doesn't seem to be a vanilla issue. I could not find any bug report regarding this on bugs.mojang.com nor could I reproduce this on a vanilla server.

**Comment by Drianikaben** [comment]
Redstone can't travel outside of loaded chunks.  So when even 1 of the pistons goes outside of the loaded chunk, flying machines stop.  This is normal behavior.

**Comment by aikar** [comment]
that was my thought to. 
Tile Entities are not supposed to tick in non ticking chunks. A border chunk is a non ticking chunk.

Nothing about these SHOULD be loading chunks. You're supposed to be on the machine to cause the chunks to load.

I just had Dinnerbone tell me to file bugs if we find cases where vanilla is loading chunks that shouldn't be, so you can consider this a bug in vanilla if you can't reproduce this in Vanilla.

This is working as intended.

**Comment by Gerrygames** [comment]
This is not about whether flying machines should load chunks or not. They shouldn't. This is the case in vanilla and Paper. But they should not break when being on the edge of ticking / non-ticking chunks. The flying machine gets into a completely broken state and has to be manually started again. This does not happen in vanilla. They stop when outside the view distance and start when within the view distance again.
