### ISSUE TITLE
ItemMeta serializing to YAML not saving black colour code.

### ISSUE THREAD

**Issue by bloggy** [PaperMC/Paper#3440]
I hope for a quick fix of this issue because we as a RPG server are really dependent on working lores. I just post a link to the issue with all information contained there:

https://hub.spigotmc.org/jira/browse/SPIGOT-5749?filter=-4&jql=text%20~%20lore%20ORDER%20BY%20created%20DESC

Let me know if you need further information.

**Comment by harrisonglp** [comment]
This is due to the deserialization of ItemMeta lore using CraftChatMessage.fromComponent() where the default ChatFormat is Black, therefore it removes black color codes when it shouldn't. This should be an easy fix.
