### ISSUE TITLE
world Sync Chunk Load (SELF) huge lag tps drop ;sudden 20-> 10tps w/ no response 

### ISSUE THREAD

**Issue by hkkongou** [PaperMC/Paper#3444]
###  Timings or Profile link:
https://timings.aikar.co/?id=8eaba69db6894ad8a890c3330867b92f

### Description of issue:
It occurs in at any time , no warning, server lag, tps drop 10, kick all players .

### Plugin list:
included in timings report

### bukkit.yml, spigot.yml, paper.yml, server.properties
https://pastebin.com/wfAEHFGD
https://pastebin.com/9XHLq3qZ
https://pastebin.com/evUHNJQm
https://pastebin.com/Zn6zeELJ

### Paper build number:
Paper 1.15.2  313

**Comment by ghost** [comment]
There was a change to packets in build 310, looking at your timings report its causing a lot. Try build 309 and see if this issue still persists.

**Comment by electronicboy** [comment]
The ~~packet~~ network stack changes are 100% irrelevant here
For support with timings, please use the discord

**Comment by aikar** [comment]
> There was a change to packets in build 310, looking at your timings report its causing a lot. Try build 309 and see if this issue still persists.

What? Do you know something we don't? that's not relevant at all..
