### ISSUE TITLE
Control the natural spawn rate of individual mobs

### ISSUE THREAD

**Issue by MCHalfAssed** [PaperMC/Paper#3445]
**Is your feature request related to a problem? Please describe.**
Not related to a bug/issue, more so just a way to further improve lag/TPS in servers. 

**Describe the solution you'd like**
Right now the Bukkit config only allows us to lower the natural spawn rate for groups of mobs, like here;

```
spawn-limits:
  monsters: 100
  animals: 8
  water-animals: 3
  ambient: 0
```
For monsters, I believe it would be beneficial for players to adjust the spawn rates of individual monsters since this is a rather large category. Whatever is not specified will fall into the default category spawn limits.

One example how this would benefit servers - Guardians spawn in the 500s (even in daylight), which is much higher than any other mob in the overworld. So essentially, I would want to add;

```
individual-spawn-limits: true
    guardian: 20
    zombie_pigmen: 25
    enderman: 25
    pig: 15
    cow: 15
```

**Describe alternatives you've considered**
I tried adjusting my bukkit config to lower mob counts, however for survival servers this may not be the possible since the server depends on monsters. Also there are some plugins that completely disable mobs, but don't allow to adjust spawn rates. 

**Additional context**
If you have any other questions please don't hesitate to reach out to me :)

**Comment by MCHalfAssed** [comment]
Do feature requests normally take two+ weeks to get to? Not trying to rush anyone, just want to make sure I submitted everything correctly.

**Comment by electronicboy** [comment]
The vanilla spawning logic really doesn't provide a clean way to accommodate this
