### ISSUE TITLE
[50% TPS loss] Paper

### ISSUE THREAD

**Issue by Bricec6** [PaperMC/Paper#3446]
###  Timings or Profile link:
https://timings.aikar.co/?id=31a23dc4bf3d4951bc1ddd46754bb768#timings

### Description of issue:
Chunk bug
Big chunk of chunk since the paper updates that produce a lot of TPS losses, there were no such losses before.
The server has just been turned on, even testing when it's been open for a long time.

### Plugin list:
![image](https://user-images.githubusercontent.com/51750055/82821576-a8ada980-9ea4-11ea-8318-c87e99f536d3.png)

### bukkit.yml, spigot.yml, paper.yml, server.properties
spigot yml: https://pastebin.com/AKDxCkr6
bukkit.yml: https://pastebin.com/KPdDY86X
paper.yml: https://pastebin.com/VRBAHedg

### Paper build number:
git-Paper-300 (MC: 1.15.2)

**Comment by electronicboy** [comment]
For support with timings, please use the discord
