### ISSUE TITLE
Entity invisible after teleport with player

### ISSUE THREAD

**Issue by MasKAT-PL** [PaperMC/Paper#3447]
### What behaviour is expected:
The player after teleportation will see entity in which the sitting. (when far teleport)

### What behaviour is observed:
The player can not see the entity in which the sitting.

https://www.youtube.com/watch?v=kRBCHjrfzjc&feature=youtu.be

### Steps/models to reproduce:
@EventHandler
public void onSpawn (PlayerSpawnLocationEvent event) {
  event.setSpawnLocation(WorldSpawn);
}
@EventHandler
public void onJoin (PlayerJoinEvent event) {
  if(event.getPlayer().isInsideVehicle()) {
    entity = event.getPlayer().getVehicle();
    lastLocation = entity.getLocation();
    event.getPlayer().leaveVehicle();
    entity.teleport(WorldSpawn);
  } else {
    lastLocation = event.getPlayer().getLocation();
  }
}

... after logging in:
Location newlocation = lastLocation;
player.teleport(newlocation);
if(the player was previously in the vehicle) {
  entity.teleport(newlocation);
  entity.addPassenger(player);
}

### Plugin list:
Vault.jar
EXPConomy_Release.jar
LuckPerms-Bukkit-5.1.15.jar

### Paper build number:
git-Paper-313 (MC: 1.15.2)

### Anything else:
To solve this problem, I think you can refresh the visibility of the entity after the teleportation, because this facility is physically there (it is visible to other players who are there, but invisible to the player who teleports at the same time as the entity)

**Comment by Fejm** [comment]
Doing these stuff onJoin may cause issues. Try to teleport 1 tick after join by using scheduler.
https://bukkit.gamepedia.com/Scheduler_Programming

**Comment by MasKAT-PL** [comment]
Thank you for your answer.

Teleport onJoin is not a problem. I teleport vehicle and player to spawn - it's ok. The problem is when the player enter command /login. Then I try to teleports the player and the vehicle to previous location in the same time - after teleports the vehicle is not visible for the player, but is visible to all other players.
When I use scheduler and I will teleport vehicle delayed by 5 tick - it seems to be working

**Comment by Fejm** [comment]
> delayed by 5 tick

1 tick is enough.

**Comment by MasKAT-PL** [comment]
1 tick not is enough for this :(

**Comment by Fejm** [comment]
Ogólnie myślałem że rozchodzi się o ten stary błąd z wykonywaniem czynności podczas logowania (onJoin). To już siedzi w MC od 1.7 chyba. Tak ma ta gra i nic z tym nie zrobisz. Natomiast widzę że masz problem już z graczem w pełni dodanym do serwera. Teraz jeszcze w roli pewności, czy teleportujesz gracza i pojazd do tego samego świata czy do innego? Taka informacja może pomóc nam znaleźć Twój błąd. Wiesz jak to jest, my tu wszyscy jesteśmy lekko leniwi i wolimy żebyś podał nam konkretny błąd na tacy.
__
Short english version: 
I was wrong, assuming it was an old bug with doing things when adding player to world. But it's not. I asked for more info - is this teleport to the same world or different.

**Comment by aikar** [comment]
please use discord for further questions on it. yes teleporting on vehicles is funky, and even more so during join.
