### ISSUE TITLE
New server started but spams console with errors regarding chunk loading

### ISSUE THREAD

**Issue by compieter-gh** [PaperMC/Paper#3448]
### Link/paste of stack trace

[latest.log](https://github.com/PaperMC/Paper/files/4678217/latest.log)

### Plugin list:
NONE

### Actions to reproduce (if known):
Am kinda unsure it's a completely new server on windows 10 1909 and with java 1.8.0_251 JRE

### Paper build number:
315

**Comment by HexedHero** [comment]
Already fixed on 316

**Comment by compieter-gh** [comment]
okay thanks
