### ISSUE TITLE
Bees do not apply the poisoning effect

### ISSUE THREAD

**Issue by JavituRec** [PaperMC/Paper#3449]
### What behaviour is expected:
When the bee attacks, it must poison the player

### What behaviour is observed:
When the bee attacks, it does not poison the player

### Steps/models to reproduce:
Spawn a bee and attack she. The bee attack to you but you not received a posion effect.

### Plugin list:
Nothing

### Paper build number:
318

**Comment by jaylawl** [comment]
Bees do not poison you if the difficulty is set to easy.

Is your difficulty set to easy?

**Comment by JavituRec** [comment]
Yes, I have changed difficulty to normal and fix.

Thanks.
