### ISSUE TITLE
Crashing / Time outs.

### ISSUE THREAD

**Issue by Kainzo** [PaperMC/Paper#345]
1.9.4 [16:47:40 INFO]: This server is running Paper version git-Paper-773 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
http://paste2.org/PjMYpn6b

What seemed to fix this issue was temp removed CraftBook's IC mechanics in config.yml
Just stating this was really odd and I'd like to see a fix if possible.

**Comment by kamcio96** [comment]
It's ChestShop bug

**Comment by Kainzo** [comment]
That is highly unlikely, I removed Craftbook IC's and the issue stopped.

**Comment by Kainzo** [comment]
Some ramblings.

the problem is chestshop is creating a block break event from within a block break event, thus creating an infinite loop
4:36 PM thats why your stacktrace is soo long

4:37 PM <kamcio96> 
https://github.com/Acrobot/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Listeners/Block/Break/SignBreak.java#L121

4:37 PM <Billy> realname 
it gets stuck in this loop and doesnt allow the server to tick. eventually it crashes out due to tick timeout

4:38 PM <kamcio96> 
that line is cause
4:39 PM ⇐ Spottedleaf quit (~Spottedleaf@SpigotMC-l6ct2d.bchsia.telus.net) Ping timeout: 121 seconds

4:41 PM <Billy> realname 
oh! i see whats happeneing
4:41 PM its not a block break event. its a physics event
4:42 PM chestshop is updating its sign/shop because craftbook is updating physics. the two keep triggering each other to update
4:43 PM might not even be craftbook. could possibly recreate using vanilla redstone
4:43 PM ↔ f0rk popped in  

4:43 PM @kashike 
Kainzo: if you could replace "latest" in your issue with the actual version, that'd be nice :)

4:46 PM <Kainzo> John Romano 
ahhhhhhhhhhh
4:46 PM i thought it listed it in the log
4:46 PM sec
4:47 PM [16:47:40 INFO]: This server is running Paper version git-Paper-773 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
4:47 PM Ill go add that

4:49 PM @Aikar 
https://github.com/Acrobot/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Listeners/Block/Break/SignBreak.java#L121
4:49 PM is the problem
4:49 PM its chestshop
4:50 PM they should not be calling .update on signs
