### ISSUE TITLE
Inconsistent Nullability in PlayerInventory

### ISSUE THREAD

**Issue by KSashaDF** [PaperMC/Paper#3450]
The PlayerInventory interface is unusual. Other inventories will return null if the item is an air item, but the PlayerInventory interface has methods which are marked as `@NotNull`. I was going to report that there are methods in the PlayerInventory interface that are incorrectly marked as `@NotNull` (such as `getItemInMainHand()`), but then after some testing I found this annotation is correct (except for the below mistake). This seems like a recent fix, as the slightly outdated decompiled code I have indicates it should return null, but I could be wrong. However, although most of the `@NotNull` annotations in PlayerInventory do accurately represent behavior, it is also inconsistent with other inventory methods.

Regardless of the above issue, the `PlayerInventory#getItem(EquipmentSlot)` method is marked as `@NotNull`, but can return null. Note that the other methods for getting equipment items are marked as `@Nullable`.

I am on the latest version of Paper (318).

**Comment by electronicboy** [comment]
the nullability of stuff is heavily inconsistent for history reasons and upstream intent to maintain support for older versions to an asine level, we can't really do much about that without breaking behavior, that's something that upstream needs to fix

The annotations being completely out in some areas is a well known issue, but really a low priority to run over everything, ideally, report upstream or shove in a PR

**Comment by aikar** [comment]
best to bring up with Spigot
