### ISSUE TITLE
mob-spawner-tick-rate setting not applying/working

### ISSUE THREAD

**Issue by Gumpah** [PaperMC/Paper#3455]
### What behaviour is expected:
In my `paper.yml` file, I've first set the `mob-spawner-tick-rate` to **2** (instead of **1**), and then **40**, and I expected the spawners to spawn much slower.

### What behaviour is observed:
I've seen absolutely no difference. So, I decided to see if it wasn't enough or wasn't working. I set it to **40**, and still no difference with the time to spawn entities.

### Steps/models to reproduce:
I think that the problem is only appearing on my server so I don't think you could be able to reproduce it. If it was possible, you'd just have to observe a spawner and it time to make spawn mobs, then you would put a high value on the `mob-spawner-tick-rate` setting (ex: **30**), and observe the same spawner. If you would see no changes, then you'd have the same issue I'm experiencing 

### Plugin list:
ArmorStandEditor, ChestShop, CoreProtect, CraftBook, DeathMessagesPrime, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, InventoryRollback, Jobs, KeepChunks, LibsDisguises, LimitPillagers, LuckPerms, MarriageMaster, Multiverse-Core, PerWorldInventory, PlotSquared, ProtocolLib, RandomBox, Residence, Skript, TAB, Vault, WorldEdit, WorldGuard

### Paper build number:
This server is running Paper version git-Paper-284 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
Thank you for the time you'll spend on my problem, I hope it can be fixed.

_Just to be sure, I just tested out with **1** and **60** values, I was waiting for the spawn time, and calculating, I did it 5 times with **1** and 5 with **60**, and I got the same results with both._

**Comment by Phoenix616** [comment]
Default dungeon Vanilla Mob Spawners try to spawn once between 200 and 799 ticks, you'll going to have to set ticks higher than that to notice any change in spawning behaviour for default spawners or test this with a Mob Spawner with way lower `MinSpawnDelay` and `MaxSpawnDelay` set.

**Comment by Gumpah** [comment]
Hi! Thank you for your answer. Well I kept seeing optimization tutorials saying to increase the value to 2-3, and that it should not affect the vanilla behavior that much, so I figured that it had an effect at a much higher value (x30).
Do I need a plugin to modify those values or is it possible with Paper's tools?

**Comment by Phoenix616** [comment]
I'm unsure what your goal is, `mob-spawner-tick-rate` is literally the config value that you want to modify if you want to reduce the speed at which spawners tick (= check if they should and can spawn entities). And if you want spawners to be slower than in vanilla just decrease the tick rate beyond the vanilla spawn delays I guess.

**Comment by Gumpah** [comment]
Yes, that's what I want to do. I'll try this. Do you know if it will still be in a range or always trying to spawn at the tick I put in the setting? If you don't I'll just test it out.

**Comment by Phoenix616** [comment]
It will use any of the normal check behavior, it just wont try to check as often.

**Comment by Gumpah** [comment]
Thank you so much, it's working perfectly, I really appreciate, have a nice day!

**Comment by MadDog443** [comment]
So could anyone actually explain the behavior of this config setting, while it states what it is in the docs it does not state the measurement, is this a multiplier, a ticks per check, or a checks per tick?

**Comment by electronicboy** [comment]
It's a ticks per check option, to delay how often a spawner tries to run
it's logic

**Comment by MadDog443** [comment]
So, in a blank config it is default at 1, and in optimization guides they always say to set it to 2, kinda like its a delay multiplier. In the case of doubling the time it takes for mobs to spawn from specifically spawners I'd have to enter between 400 and 1600 or the average of the two? Idk I just don't understand why it would default to 1 in this case.

**Comment by electronicboy** [comment]
It's how often the check is run, spawners have a counter on them before
they can spawn again, if the value is set to 2, then it runs every 2 ticks
instead of every tick, and decrements the counter by 2, thus making there
be little difference in the time between spawns; if you want to actually
modify how long spawns take in general, you'd need a plugin to change how
long the counter runs for, as it's defined from the mob spawners data

**Comment by MadDog443** [comment]
Thanks for the info.
