### ISSUE TITLE
Server Crash due to Rapid Chunk Loading

### ISSUE THREAD

**Issue by Cassy343** [PaperMC/Paper#3457]
[Stack trace (including full thread dump)](https://pastebin.com/p9AYCahJ)
At the bottom it said to report this to paper hence I am here.

### Plugin list:
- BuycraftX
- CoreProtect
- FarLands (custom plugin I wrote for the server)
- HeadDatabase
- OpenInv
- ProtocolLib
- RegionProtection (rewrite of grief prevention and world guard I mashed into one plugin)
- Shop
- Votifier
- VoxelSniper
- WorldEdit

### Actions to reproduce:
The player Losum who joined at the beginning of the log explains a little bit what is going on. He used a hacked client (I am not sure which one) to accelerate himself to load chunks extremely quickly presumably causing the crash.

### Paper build number:
```
This server is running Paper version git-Paper-295 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-257 (MC: 1.15.2)
You are 26 version(s) behind
```

**Comment by electronicboy** [comment]
update, and check the option for moving into unloaded chunks in paper.yml
