### ISSUE TITLE
Teleporting to exact coordinates without decimals sometimes causes the entity to fall through the ground

### ISSUE THREAD

**Issue by ingfors** [PaperMC/Paper#3458]
### What behaviour is expected:
Running the following code I expect the player to be teleported on top of the highest available block at the specified location.

`int x, y, z;    
double angle = Math.random() * 360;
double radius = Math.random() * 1000;
World world = Bukkit.getWorld("world");
Player player = Bukkit.getPlayer("username");

x = (int)(Math.sin(angle) * radius);
z = (int)(Math.cos(angle) * radius);
y = world.getHighestBlockYAt(x, z);

player.teleport(new Location(world, x, y+1, z));`

### What behaviour is observed:
Player is teleported to the specified location but sometimes while in survival mode keeps falling though the world a couple of blocks down. Resulting in death by suffocation. I would estimate this happens 1/10 times but it might depend on what hardware you are using.

I have also tried the following with the same result.
`player.teleportAsync(new Location(world, x, y+1, z));`

The problems seems to be that I specify cordinates without any decimal values. Running the exact same code as before but instead replacing the teleport command with the following fixes the issue.

`player.teleport(new Location(world, x+0.5, y+1, z+0.5));`

### Plugin list:
I run a empty server with just PlugMan v2.1.7 and a simple custom plugin using the code above.

### Paper build number:
Build: 321
Version: 1.15.2

**Comment by DarkEyeDragon** [comment]
This is caused by teleporting to the edge of the blocks and being partially in other (higher) blocks causing the suffocation. Offset by 0.5 so you're in the center of the block.

**Comment by ingfors** [comment]
> This is caused by teleporting to the edge of the blocks and being partially in other (higher) blocks causing the suffocation. Offset by 0.5 so you're in the center of the block.

I understand that might sometimes be the case. But if I look at the y coordinates my character keeps falling through the ground for around 4-5 blocks even if below me is dirt and stone. This happens while the chunk is loading. When I teleport to the middle of a block and look at y coordinates the server automatically make an effort to keep my at my top location while the chunk is loading. By constantly changing my y value. This does however sometimes not happen when teleporting to the coorner of a block.

**Comment by aikar** [comment]
Sadly there is also the issue here that the .getHighestBlockYAt is not always safe for teleporting.

You may want to try using a different HeightMap such as OCEAN_FLOOR_WG, see HeightMap class.

But most people end up just checking blocks themselves based on the base result.
