### ISSUE TITLE
ChunkMaster fails if you wait for a few minutes after server startup

### ISSUE THREAD

**Issue by konsolas** [PaperMC/Paper#3459]
### What behaviour is expected:
ChunkMaster would generate chunks without any issues.

### What behaviour is observed:
ChunkMaster spams the console with messages about chunks failing to load.

### Steps/models to reproduce:

1. Create a paper server with ChunkMaster 0.15-beta as the only plugin.
2. Start the server.
3. Wait at least three minutes.
4. Execute the command `chm generate world 200 blockradius`
5. Wait a few more seconds for the generation task to start

### Plugin list:
ChunkMaster 0.15-beta

### Paper build number:
```
[23:21:18 INFO]: This server is running Paper version git-Paper-321 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[23:21:18 INFO]: Checking version, please wait...
[23:21:18 INFO]: Previous version: git-Paper-314 (MC: 1.15.2)
[23:21:18 INFO]: You are running the latest version
```

### Anything else:
Here is the log file from when I reproduced this issue: https://gist.github.com/konsolas/9357f671e6ddaff87442fc9172864985

In Paper 314, there was no need to wait after startup - this would start happening immediately.

Paper 313 completes the task with no issues, regardless of whether or not you wait for 3 minutes.

**Comment by Lusteroth** [comment]
Looks like issue #3451

**Comment by konsolas** [comment]
I just tried the same procedure (including the 3 minute wait) on Paper 313 - it completed without issues. 

It seems that there is currently no reliable way to pregenerate a world on Paper >= 314. 

A temporary workaround might be pregenerating on 313 before upgrading back to latest (though I guess you'd have to downgrade again to pregenerate anything else)
