### ISSUE TITLE
World's day does not update correctly

### ISSUE THREAD

**Issue by BillyGalbreath** [PaperMC/Paper#346]
/time set 192000

Expected:
makes the world's day 8 _EDIT:_ client-side

Actually Happens:
the world's day reset to 0 _EDIT:_ client-side

This is a huge problem for my Pl3xTime plugin since it gives admins the ability to set the world's day counter.

The ticks stored in the WorldData are correct. I can pull world.getFullTime() and %24000 to get the correct days (8). But F3 still shows days as 0. http://prntscr.com/bivw24

This is not a problem on vanilla, CraftBukkit, or Spigot. Only happens on Paper.

**Comment by BillyGalbreath** [comment]
This functionality not only breaks the vanilla /time command, but for plugins trying to set the world's day counter like my Pl3xTime plugin:

https://bitbucket.org/BillyGalbreath/pl3xtime/src/0b74217c4333349e609dce85332dca47c231fe37/src/main/java/net/pl3x/bukkit/time/command/CmdTime.java?at=master&fileviewer=file-view-default#CmdTime.java-215

**Comment by zachbr** [comment]
F3 client-debug will not be accurate in order to workaround a client side issue with banners.
API and commands will continue to function as normal, (updating everything server-side as always), the only thing that  won't work properly is the local time in client, which isn't used for anything anyway.

If you are trying to use it for something... why?

**Comment by zachbr** [comment]
Patch in question, for reference. https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0095-Waving-banner-workaround.patch

As you can see, it only modifies the values sent to clients.

**Comment by zachbr** [comment]
Seems we've reached a fundamental disagreement [over this in IRC.](https://korobi.io/network/spigot/channel/Paper/logs/2016/06/20/#L1420)
Where we value banners waving more than F3 debug's time slot (and that is all that this patch alters) being correct.
