### ISSUE TITLE
Build 321 - Villagers do not claim a workstation

### ISSUE THREAD

**Issue by NathanCollaert** [PaperMC/Paper#3462]
### What behaviour is expected:
Villagers are linked to a workstation.

### What behaviour is observed:
Villagers don't have a workstation linked to them and won't ever link to any workstation.

### Steps/models to reproduce:
Get a villager, place a workstation, observe.

### Plugin list:
None, tested on fresh server.

### Paper build number:
321

**Comment by calumari** [comment]
Unable to reproduce in 321.

Are you sure it's day and the villager has line of sight to the workstation?

**Comment by NathanCollaert** [comment]
All villagers had a workstation linked in my world, after update they all lost it and didn't want to link to one.
New villagers without a profession were unable to link to one either.
Yes it was day and yes they were right in front of their workstation without being in a minecart.

**Comment by NathanCollaert** [comment]
Reverting back to 320 fixed it all.

**Comment by NathanCollaert** [comment]
Now that I think of it. I didn't try without an iron trapdoor above the workstation, maybe that has something to do with it.

**Comment by NathanCollaert** [comment]
> Now that I think of it. I didn't try without an iron trapdoor above the workstation, maybe that has something to do with it.

IF this is the case, then it would also be a bug and the expected behavior of the above issue still applies.

**Comment by jariha** [comment]
My farmer villagers stopped resetting their trades after this version. I can later try previous version if it fixes the issue.

I tried to place the composter to different locations but no success.

**Comment by ToniVC** [comment]
Same problem here. I updated my server to 321 version and users have started to complain about villagers not working.

**Comment by johnfriedrich** [comment]
Villagers are broken on 321+. Many users reporting one of the following issues:
- stop sleeping if there is abed near to the wall
- dont find the bed anymore in general
- disconnecting from workstations

**Comment by DaveBC** [comment]
EDIT: Appears fixed with 324. Thank you.

Experiencing the same problem as @NathanCollaert. 
Here is my setup to reproduce the bug. There are also carpets underneath each workstation.

![Villager Setup](https://i.imgur.com/cG8Bsxc.png)

In 321 no villagers are able to restock (since they can't locate a workstation). Reverting to 320 allows only the one village with a workstation in front to restock.

**Comment by aikar** [comment]
Please try 324. I did not have any of the reported issues even before pushing that optimization, but made some improvements that might help.

But also beds code was not even touched yet so not sure how that would be an issue....

**Comment by jariha** [comment]
324 seems to fix the issue with villagers not resetting their trades.
Thank you!

**Comment by ToniVC** [comment]
After updating to 324 my users report villagers are back to normal behaviour. Thank you!
