### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by Toufailleur** [PaperMC/Paper#3463]
### What behaviour is expected: 
Make trains, create stations, etc... All things related to TrainCarts.

### What behaviour is observed:
Nothing happened, except error : [17:52:16] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Train_Carts v1.15.2-v1 (log attached)

### Steps/models to reproduce:
- Install build 322
- Installl plugins
- Launch Server
- Place a minecart on a rail, place another right behind, normally they must link together.

### Plugin list:
- BKCommonLib-1.15.2-v3
- SignLink-1.14.4-v1
- TrainCarts-1.15.2-v1

### Paper build number:
322

### Anything else:
It still works properly on Spigot, and it was still available in Paper Build 304. First error appeared in build 313. Didn't test builds in between.
[latest.log](https://github.com/PaperMC/Paper/files/4696860/latest.log)

**Comment by wizjany** [comment]
The plugin is trying to handle its own exceptions but there's an error in its exception handler. We can't see the actual cause of the issue...

**Comment by Toufailleur** [comment]
Indeed. Well I was able to narrow the first build where this bug appeared : in 305. It started with BKCommonLib. If it can help...
[305.log](https://github.com/PaperMC/Paper/files/4697429/305.log)

**Comment by electronicboy** [comment]
This is an issue with BKCommonLib, which they've seemingly already patched
