### ISSUE TITLE
Server Crashes Randomly with the error "Writing into PalettedContainer from multiple threads"

### ISSUE THREAD

**Issue by Riknesh** [PaperMC/Paper#3464]
My server keeps crashing after I receive an "Writing into PalettedContainer from multiple threads" error. Here is the stack trace from the crash report.
https://pastebin.com/nrUzxXKW

### Plugin list:
Plugins Installed (77): Admin-GUI, antiRedstoneClock, AntiVPN, AuctionHouse, AuthMe, AutoMessager, Autorank, BuycraftX, CactusLimiter*, ChatInjector*, ChestSort, Citizens, CoreProtect, eBackup, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, Factions, FactionsTop, FactionsTopv5Hologram, FactionsTopv5NPCs, FastCraft, FractalForest, GSit, HeadDatabase*, HelpPagePlus, HolographicDisplays, HolographicExtension, Images, InfiniteScoreboard, InteractiveChat, LibsDisguises, LimitPillagers, LiteBans, LuckPerms, LWC, LWCTrust, MarriageMaster, Matrix, MiniaturePets*, MotionCapture*, Multiverse-Core, MythicMobs, MythicSkriptAddon*, OpenInv, PerWorldInventory, PetMaster, PL-Hide, PlaceholderAPI, PlayerParticles, PluginLibrary, PluginManager*, ProtocolLib, PvPManager, SAML, ServerListPlus*, ShopGUIPlus, SkBee, Skent*, SkinsRestorer, SkQuery, Skript, skript-mirror*, SmoothSleep, spark, Statz, SuperVanish, TAB, TreeGravity, Vault, VillagerOptimiser, Vixio*, Votifier, VotingPlugin, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Occurs randomly.

### Paper build number:
Paper version git-Paper-321 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
> Description: Writing into PalettedContainer from multiple threads (other thread: name: Craft Scheduler Thread - 6025, class: class java.lang.Thread)

Replicate without plugins

**Comment by Riknesh** [comment]
How do I replicate it? It occurs randomly

**Comment by electronicboy** [comment]
Your issue is caused by plugins modifying the world in from another thread, you'll need to work out what's going on
