### ISSUE TITLE
Attributes are reset to the default ones

### ISSUE THREAD

**Issue by DeelTer** [PaperMC/Paper#3467]
### What behaviour is expected:
When I add unique attributes to a wolf, they stay with it forever

### What behaviour is observed:
I added attributes to the wolf, but after it became angry - all attributes were reset to the default ones (**also works with taming**)

### Steps/models to reproduce:
[VIDEO](https://youtu.be/PM-yqEHv1K8) pay attention to the chat-debug
I just set the entity attributes.

### Plugin list:
_only my_

### Paper build number:
git-Paper-322 (MC: 1.15.2)

### Anything else:
For some reason, this **works with a cat**, but it **doesn't work with a wolf**

**Comment by electronicboy** [comment]
This is standard vanilla behavior, you'd need to reset your attributes if you want them to persist
