### ISSUE TITLE
Entering certain chunks causes freeze/drops

### ISSUE THREAD

**Issue by LordManzana** [PaperMC/Paper#3468]
What behaviour is expected:
Just normal chunk load

What behaviour is observed:
Freeze/drop FPS when chunks loaded

Steps/models to reproduce:
https://youtu.be/SJvpZcHRF7I

Tested on my map (with 32 chunks load, also with 2 chunks load):
jonatan.co/docs/world.zip - sorry for the size :(
Go to -1764, 66, 2441
Facing east, move from current chunk to next one
Game freeze a lot.

Go to -1766 85 2793
Facing east, move from current chunk to next one
Game drop fps/freeze just a sec.

Plugin list:
Tested in a world with and without any plugins.

Paper build number:
Was using round #290, recently moved to #322.

**Comment by wizjany** [comment]
https://bugs.mojang.com/browse/MC-162253 ?

edit: in theory, fixed here https://github.com/PaperMC/Paper/commit/72f89a076aa56a6f60cdda354e7ac5eb324daed7

**Comment by LordManzana** [comment]
> https://bugs.mojang.com/browse/MC-162253 ?


Yeah, also reach it and:

Placed at 255 barriers, still freeze, don't know if it's the same behaviour since in the issue it's just freezing a sec, in my case it's like 20 seconds

**Comment by hurrgurl** [comment]
> > https://bugs.mojang.com/browse/MC-162253 ?
> 
> Yeah, also reach it and:
> 
> Placed at 255 barriers, still freeze, don't know if it's the same behaviour since in the issue it's just freezing a sec, in my case it's like 20 seconds

Hope Mojang makes an actual fix with 1.16

/fingerscrossed
