### ISSUE TITLE
DIsappearing shulker boxes

### ISSUE THREAD

**Issue by mbravorus** [PaperMC/Paper#3470]
### What behaviour is expected:
Shulker boxes reliably stay where they are and drop when pickaxe-d and get picked up to inventory.

### What behaviour is observed:
Multiple players have reported multiple occasions of shulker boxes disappearing. I understand this is very hard to reproduce, so I will attempt to provide as much details as I can.

### Steps/models to reproduce:
All but one reports had shulkers disappearing after being placed, usually opened, and usually attempted to pick up.

The only time I have experienced it myself, I have placed a shulker box from my inventory on the ground, opened it, accessed some items, closed it, used pickaxe on it, saw the particle animations and then it wasn't there. I relogged and found it floating as an entity a couple blocks away.

Other players state they have tried relogging as well and it didn't help, but as I wasn't there and can't control the timeline, I can't verify what was actually happening.

At no time were there any error messages on the server console. There is also no observable correlation between player ping times and the disappearances (meaning, ping for everyone involved is usually 50-80ms). Server is also not plagued by lag and is usually flat at 20 tps. There is rarely more than 3-4 players on at the same time, I think absolute maximum was 8 once. Server is running Aikar's optimized flags and has -Xmx 4Gb

This is not a frequent occurrence, about maybe once every 5-6 days (not correlated to any server restarts as far as I can see), but highly unpleasant.

### Plugin list:
Plugins (6): Chairs, CoreProtect, DiscordSRV, dynmap*, LuckPerms, PrometheusExporter*

Note: disappearances have been occurring before installation of Chairs and CoreProtect as well

### Paper build number:
This server is running Paper version git-Paper-309 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Note: I upgrade every now and then and the issue has been occurring infrequently for the last 50ish builds or so

### Anything else:
Naturally, I am willing to implement any needed debug actions as long as it doesn't cripple the server

**Comment by hurrgurl** [comment]
Heard many similar reports about it for years now. Nobody has been able to reproduce this reliably.

My guess is that shulker item entities get stuck in-between blocks after they're broken, until they disappear eventually.

**Comment by mbravorus** [comment]
Surely there must be a way to make a debug build so that eventually all the potentially suspect paths are logged and we can whittle the problem down to the root cause?

**Comment by hurrgurl** [comment]
If you must, maybe try tracking all shulker item entities and see if they actually disappear into nothingness after breaking.

**Comment by mbravorus** [comment]
happy to do some RTFM if you could point me to something (that is, how do I do such tracking)

**Comment by johnneijzen** [comment]
i had this happen to me yesterday and i did taught maybe i lagged then i try to check all my chest. in the end i just run old playerdata instead and on my server we also using coreprotect

**Comment by Legit4K** [comment]
This issue happened to one of my players today, 4 out of 5 of the shulker boxes were gone

**Comment by DXUltimate** [comment]
This has happened as well several times, to one individual, except he's using a hopper auto-sorting system as well. For whatever reason, in our case, this is only happening with unnamed shulkers and never with named ones (hard to tell if that has anything to do with it, but it is worth mentioning). The version of paper we use is paper 161 for mc 1.16.2.

**Comment by Keeeelme** [comment]
still happens at 1.18.1. lost 4 shulker boxes

**Comment by GreenJon902** [comment]
From what I can see, the issue is caused by a block being placed but not saved as placed or something like that. My CoreProtect logs tell me that I edited the contents of the shulker but didnt actually place or break the shulker!
![2022-05-14_19 34 32](https://user-images.githubusercontent.com/37347905/168444253-d44da318-d055-4223-9d3b-a9b6895e4493.png)

**Comment by WaffleBits** [comment]
still exists

**Comment by darylsonnier** [comment]
Had 2 shulker boxes and an ender chest disappear when getting into the end.  Disappeared right by two other players who were already in the end.

**Comment by rrvk** [comment]
Where the shulkerboxes and enderchest on the obsidian platform? Because every on there will be regenerated / deleted

**Comment by darylsonnier** [comment]
Yes, the obsidian platform at the edge of the end island where you first spawn into the end.

**Comment by rrvk** [comment]
That is normal that that happens then 

the platform is restored and any overlaying blocks on or within 3 blocks above the obsidian are removed when the player enters the End.


https://minecraft.fandom.com/wiki/Obsidian_platform

**Comment by TravisGM92** [comment]
Just had it happen to me. I placed a shulker down right as a chicken was passing and it briefly showed on the screen then disappeared. It isn't anywhere in the area, nor in my inventory.

**Comment by Celophy** [comment]
In my server, this bug persist, player loose their shulkers often

**Comment by PaintsplattersMC** [comment]
i am also expierencing this issue on paper 1.19.2

**Comment by nhanledev** [comment]
This issue still happens a lot. I have to track the shulker by CoreProtect and rollback the player break action to recover player's shulker box.

**Comment by HorusApl** [comment]
Can confirm still having this 1.19.3. It seems to be directly correlated to redstone activity as I can reproduce it within about 5 minutes of breaking/picking up a shulker if I am near a redstone contraption (item sorter, uses minecarts) but I cannot reproduce it ever if I am not near any redstone.

**Comment by Leonardo-Fiori** [comment]
Happens frequently on my server too, coreprotect sees a placed shulker, player logs off, logs back in, the shulker is gone, he tries placing dirt to see if it was a visual bug, but it wasn't
<img width="422" alt="image" src="https://github.com/PaperMC/Paper/assets/25549272/301b2547-474c-4044-ac1b-0515ea29b9bb">

**Comment by pjindras** [comment]
Yes, the problem still presists and noone made solution / way how to prevent this shulker behaviour. Many servers have the same issue with shulkers.

It is hard to reproduce, but it happens. 

Do I have an actual info, or has anything further been resolved on this matter?

I think this is just more of a challenge for a professional, I haven't done anything with it myself, I've tried a number of things.

**Comment by UPSOKen** [comment]
Still experiencing this on `1.21.4`.

**Comment by mbax** [comment]
@UPSOKen [commented](https://github.com/PaperMC/Paper/issues/3470#issuecomment-3062618662):
> Still experiencing this on `1.21.4`.

Can you reproduce it on 1.21.7 without plugins? If so, please describe your method.

**Comment by UPSOKen** [comment]
> [@UPSOKen](https://github.com/UPSOKen) [commented](https://github.com/PaperMC/Paper/issues/3470#issuecomment-3062618662):
> 
> > Still experiencing this on `1.21.4`.
> 
> Can you reproduce it on 1.21.7 without plugins? If so, please describe your method.

Unfortunately, no - it seems entirely random.

If I am ever able to reproduce what causes it, I will report back.
