### ISSUE TITLE
Compass lost its pointing location

### ISSUE THREAD

**Issue by jokbon** [PaperMC/Paper#3471]
Compass lost its pointing location...
When doing /spawn i go to world spawn. But compas points to other location.
![UntitAGSEGgled](https://user-images.githubusercontent.com/29400409/83298810-c4df7c80-a1fd-11ea-872f-4267603bad88.png)

**Comment by jokbon** [comment]
When i set spawn point it got updated and it points to right thing now.

**Comment by electronicboy** [comment]
In the future, fill in the template
as for your issue, replicate without plugins, also, make sure that that is the actual vanilla world spawn and not one set by essentialsspawn, for example
