### ISSUE TITLE
Server in online mode has considerably higher latency than offline mode

### ISSUE THREAD

**Issue by hieu-van** [PaperMC/Paper#3474]
###  Timings or Profile link:
_deleted_

### Description of issue:
After switching to online mode, the server is considerably more laggy, especially when joining or travelling between worlds. Even in LAN, the network strength indicator is not always full, occasionally drops to 2 or 3 bars. The situation gets worse when there are multiple players.

### Plugin list:
No plugins installed.

### bukkit.yml, spigot.yml, paper.yml, server.properties
_deleted_

### Other helpful links/notes
* I tried to run the server both with aikar's flags and without, but there wasn't any difference.
* Increasing RAM limits doesn't help.

### Paper build number:
321

**Comment by electronicboy** [comment]
Only difference between online and offline mode is really the encryption layer, looking at that, your CPU is underspec'd, as well as having memory issues, you really *need* at least 4 cores if you wanna use a modern build of MC
