### ISSUE TITLE
New option in paper.yml, for carto. villager

### ISSUE THREAD

**Issue by DiegoDaniel** [PaperMC/Paper#3476]
**Is your feature request related to a problem? Please describe.**
This would help with the problem with cartograph leveling up to lv 2. The servers freezes because of the map that he will sells on lv2.

**Describe the solution you'd like**
I would like an option like "preventCartoLevel2Map: true" to change that item on trades from villager with any other thing like paper or w/e.

**Describe alternatives you've considered**
I think that there is no other alternative, i have banned the Cartography Table from my server due to this problem, when a villager reachs lv2, the whole server freezes because of the map searching for monuments. I have a world generated with "Epic World Generator". 

Ty so much! Hope my request helps people... Sorry for bad english (?

**Comment by aikar** [comment]
There is a config already for this:
enable-treasure-maps: false
