### ISSUE TITLE
Interactions to the world breaks future interactions

### ISSUE THREAD

**Issue by forkiesassds** [PaperMC/Paper#3477]
### What behaviour is expected:
If I interact with the world I should be able to interact after interacting a few times

### What behaviour is observed:
If I interact with the world I can't interact after interacting a few times

### Steps/models to reproduce:
1. Do something such as open doors, chests, sleep or even eat.
2. Try to interact, doors appear to open but they are still closed, placed blocks are not actually there, chests do nothing.
3. If you still can interact try doing it a few times until you can't interact.

### Plugin list:
DiscordSRV, Geyser-Bukkit, ProtocolLib, ServerlistMOTD*, SkinsRestorer, Sw1ftIcons*, ViaBackwards, ViaRewind, ViaVersion

### Paper build number:
This server is running Paper version git-Paper-330 (MC: 1.15.2) (Implementing API version 1.15.2 R0.1-SNAPSHOT) Previous version: git-Paper-329 (MC: 1.15.2)

### Anything else:
Not sure if it is due to the world, clearing out all of the plugins did not fix the problem, does not happen on Vanilla or Spigot. And no it's not spawn protection. It is NOT a Geyser bug. Not using any proxy server to connect to the server.

**Comment by aikar** [comment]
Based on the gif you sent on Discord, I'm going to assume you spammed it so fast you desynced the client from the server and the client simply doesn't realize an inventory is open.

Please provide reproduce steps / video that don't involve spamming interactions that fast.

**Comment by forkiesassds** [comment]
Ok, heres a gif that does not involve spamming interactions, all I did was just eat. https://imgur.com/K9NYUbG. I know that even spamming a door does this.
