### ISSUE TITLE
Custom entity AABB doesn't "stick" anymore

### ISSUE THREAD

**Issue by jaylawl** [PaperMC/Paper#3479]
### What behaviour is expected:
I am giving an entity a customized AABB for minigame purposes.
The AABB isn't supposed to change, it has been working like that in my code for almost a year without any issues - unless the entity is being teleported in which case i had to re-apply the custom AABB.

This used to work until very recently.

### What behaviour is observed:
As soon as the entity is being moved by applying velocity to it, the AABB reverts to it's vanilla values.

### Steps/models to reproduce:
1. Spawn an armor stand (i use .setSmall(true))
2. Run this code on it:
```
    public static void setAABB(Entity entity) {
        double cubicSize = .25;
        double inputHalf = .125;
        Location l = entity.getLocation();
        double x1 = l.getX() - inputHalf;
        double y1 = l.getY();
        double z1 = l.getZ() - inputHalf;
        double x2 = l.getX() + inputHalf;
        double y2 = l.getY() + cubicSize;
        double z2 = l.getZ() + inputHalf;
        ((CraftArmorStand) entity).getHandle().a(new AxisAlignedBB(x1, y1, z1, x2, y2, z2));
    }
```

3. Do this to move the entity:
```
entity.setVelocity(vector)
```
In my code, the velocity is updated every tick; it's a custom physics engine so to speak. But it doesn't move the entity in another way than using .setVelocity()

### Plugin list:
Just my custom plugin for this, removed any other plugins to investigate this issue.

### Paper build number:
1.15.2
Currently used version producing the bug: `git-Paper-322`
Last known version where it was *working as intended*: `git-Paper-260`

### Anything else:
May your coffee be strong.

I noticed there have been some AABB changes in the latest paper version but those are yet beyond my understanding. From what i could read i don't think they should've affected the functionaly of my code here though. As i said, this was unchanged for about a year and has been working exactly the same on both 1.13 and 1.14.

**Comment by jaylawl** [comment]
#3401 likely related

**Comment by jaylawl** [comment]
https://gyazo.com/3be9489f4d29bf933163bb9ef99fdca1

Monitoring the AABB on every tick here.
EntityBB (1) before the execution of my physics code
EntityBB (2) is after the physics code is done

The next cycle would be on the next game tick, after the entity has been moving for that tick (due to it's velocity being set a vector calculated by said code).

The 0.25³ sized AABB is my custom one, but the height reverting to the 0.9875 is the vanilla AABB.

**Comment by jaylawl** [comment]
I have temporarily "fixed" this by applying my custom AABB on every tick while the entity is moving - at least that's working my purposes.

Some clarification on what happened to AABB's would be dope tho. Thanks!

**Comment by aikar** [comment]
We updated setPositionRaw to always update the AABB instead of setPosition.

I'm assuming your calling that after the AABB is being set.
If you call Entity.a(AABB); after position, that would be the most accurate way to ensure its set.

But.... You shouldn't be doing it this way anyways!
The real issue is that you are setting custom sizes through AABB hackery instead of just adjusting the entities width and height values instead which is what the AABB logic uses to calculate the AABB.

You can do this:
entity.size = EntitySize.b(width, height);

And it would actually set the entities expected width/height and then it'll handle AABB's for you.

**Comment by jaylawl** [comment]
> 
> 
> We updated setPositionRaw to always update the AABB instead of setPosition.
> 
> I'm assuming your calling that after the AABB is being set.
> If you call Entity.a(AABB); after position, that would be the most accurate way to ensure its set.
> 
> But.... You shouldn't be doing it this way anyways!
> The real issue is that you are setting custom sizes through AABB hackery instead of just adjusting the entities width and height values instead which is what the AABB logic uses to calculate the AABB.
> 
> You can do this:
> entity.size = EntitySize.b(width, height);
> 
> And it would actually set the entities expected width/height and then it'll handle AABB's for you.

That's useful info, thanks for that!

However, just to be clear, i was never using setPositionRaw nor setPosition methods, at least not to a degree that i would've been aware of. I strictly move the entity by using entity.setVelocity.

That piece about size is some holy information to me, and if it works out, that would save me a bunch of headaches about my AABB hackery.

I just investigated entity.size within the NMS Entity.class, but it appears that it's a private field and i couldn't find any methods within the class that would allow modification of that field.

Am i looking in the wrong spot; e.g. did you mean something other than NMS entity?

**Comment by aikar** [comment]
You're using NMS, surely reflection is something you're use to :P

**Comment by jaylawl** [comment]
This AABB stuff is the only NMS stuff i'm touching, and that's purposely so because i've heard "dont use NMS" a million times x)

i think you're overestimating my skills a little bit - appreciated, but i have many things to learn!

so you're saying that there is a way to edit that private size attribute? if so, that's all i need to know, i'll find it. trying to not tax your time

//edit:

turns out i didnt know what reflection was :D i thought it meant using NMS
thanks a ton!

**Comment by Chew** [comment]
Gonna assume by the "thanks" that this was resolved, if not, ensure this is reproducible on a supported version and we can re-open if needed.
