### ISSUE TITLE
Chunk Loading Issues

### ISSUE THREAD

**Issue by Elric02** [PaperMC/Paper#3481]
### Link/paste of stack trace

First, the server stopped responding and I got this message : https://pastebin.com/vMsr9g9v
Than, I got this message : https://pastebin.com/ejA6M8Ni

### Plugin list:
Chunkmaster, Citizens,CoreProtect, CrateReloaded, DiscordSRV, EntityDetection, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, Holograms, Jobs, LibsDisguises, LimitPillagers, LuckPerms, Multiverse-Core, MythicMobs, PlaceholderAPI, Plan, PluginManager, ProtocolLib, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Actions to reproduce (if known):
No idea :/ I've had this issue a few times a day since I upgraded to Paper build ~305 (Can't remember exactly at which build it started)

### Paper build number:
This server is running Paper version git-Paper-327 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Legit4K** [comment]
Experiencing the same thing here (build #332)

**Comment by electronicboy** [comment]
need the full log, that really doesn't tell us much

**Comment by Elric02** [comment]
@electronicboy here's all I have, hope it helps : https://pastebin.com/cDmP04eG

**Comment by Elric02** [comment]
Reverted to Paper build 300 for now, I don't have any issue with this build (except maybe little lags lol)

**Comment by aikar** [comment]
It appears you are on a single core CPU.... This is kinda expected to be able to crash if too much is loaded at once on a single core CPU :/

**Comment by Elric02** [comment]
You're right, we've got a problem somewhere. We'll be investigating this. 
But I think this issue in particular isn't bound to our single core CPU, as we didn't have any problem on build 300

**Comment by aikar** [comment]
Well, one change was that I made single core CPU's not use threads at all because its slightly more efficient to NOT use threads there...

You REALLLY need a multi core CPU, but I will adjust some things to give single core CPU a single thread.

**Comment by Elric02** [comment]
All right, thanks !
