### ISSUE TITLE
Portal scanning crash

### ISSUE THREAD

**Issue by salatmaster** [PaperMC/Paper#3482]
### Link/paste of stack trace

https://paste.gg/p/anonymous/58f2ed15847a4817805bb64ad5434034

### Plugin list:
Plugins (44): AbstractApi*, AbstractCooldown*, AbstractMenus, AdminChat*, AdvancedRandomTeleport, AntiRelog*, AutoPlayerCmd*, BenioApi, CoreProtect, DiamondConverter*, Essentials, EssentialsSpawn, HolographicDisplays, LiteBans, LuckPerms, Matrix, ModernChat*, MyCommand, NametagEdit*, PlaceholderAPI, PlayerLogger, PlugMan, ProtocolLib, RemoveAliases, samopis, SkinsRestorer, spark, SpawnerCart, TitleManager, TradeMe, VanillaEconomyBalancer, VanillaLagFixer, VanillaRegionCleaner, Vault, VC_Clans, VCBack, VCFly, VCMarket, VillagerOptimiser, WorldBorder, WorldEdit, WorldGuard, ZerxArena

### Paper build number:
 This server is running Paper version git-Paper-331 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by jaylawl** [comment]
First line of your posted report:
```

  | [18:45:36] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-331 (MC: 1.15.2) ---
-- | --


```

**Comment by electronicboy** [comment]
We told the author to create the issue, but, did say to test if it was "fine" on an earlier version first, no idea if that was done 🤷

**Comment by electronicboy** [comment]
#3489
