### ISSUE TITLE
paper version 333 does not work

### ISSUE THREAD

**Issue by Blueeyestar** [PaperMC/Paper#3483]
Unfortunately the latest paper version 333 does not work. Problems occur when starting.

Patching vanilla jar...
Failed to read vanilla jar and patch file
java.util.zip.ZipException: invalid stored block lengths
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
at java.io.FilterInputStream.read(FilterInputStream.java:133)
at io.papermc.paperclip.Paperclip.readFully(Paperclip.java:243)
at io.papermc.paperclip.Paperclip.checkPaperJar(Paperclip.java:129)
at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:91)
at io.papermc.paperclip.Paperclip.main(Paperclip.java:45)
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 1
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Aborting automatic reboot due to crash within the last 60 seconds.
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 30455M / 81920M
[Pterodactyl Daemon] Ensuring correct ownership of files.

**Comment by electronicboy** [comment]
your jar is corrupted, redownload/retransfer, if using ftp, make sure that the transfer mode is not in ascii, etc

**Comment by Blueeyestar** [comment]
I had never had the problem. when I had put the 332 back on it went as usual !!

**Comment by aikar** [comment]
yes because your 332 jar was not corrupt.... Redownload 333

**Comment by aikar** [comment]
Though this looks like it failed to download vanilla, so maybe your 332 jar is fine, and you need to delete your cached folder.
