### ISSUE TITLE
A lot of lag spikes | not cause plugins

### ISSUE THREAD

**Issue by JavituRec** [PaperMC/Paper#3485]
###  Timings or Profile link:
1 https://timings.aikar.co/?id=8487c69ab68c458ea6dfb22fd88b216f
2 https://timings.aikar.co/?id=9c149c61e51748fb9566f7de711a76e8

### Description of issue:
I've been noticing that the server has started to have a permanent TPS drop. When I reboot I still have large spikes in TPS downloads that will return to permanent shortly.

I have examined it and it seems to be something of entities along with the chunk load but I can't see any more beech. Attached is the report from the timings.

### Plugin list:
![hki](https://user-images.githubusercontent.com/10663192/83452601-4d0d8e00-a459-11ea-95db-5a1928dfe98d.PNG)
![HKee](https://user-images.githubusercontent.com/10663192/83452603-4da62480-a459-11ea-8c15-00153b12d263.PNG)

### bukkit.yml, spigot.yml, paper.yml, server.properties
Bukkit: https://pastebin.com/hFDpz0xH
Spigot: https://pastebin.com/8vgKAHrd
Paper: https://pastebin.com/dJenaVAY

### Paper build number:
Paper 333

**Comment by radekklima21** [comment]
You have 3GB RAM and 2 threads CPU.. Beautiful... 

(And the number of plugins is insane.. I have several 70 players servers and I have less number of plugins than you)

**Comment by aikar** [comment]
In the sustained lag it was purely from a zombie farm. nothing systemic shows here as a paper issue.

You need to control your entities and/or players activity to prevent this. 
For further assistance in controlling things like this please use Discord.
