### ISSUE TITLE
Server freezes

### ISSUE THREAD

**Issue by crazykidney** [PaperMC/Paper#3490]
### Description of issue:
Server freezes for a few seconds

### Plugin list:
None

### Other helpful links
https://pastebin.com/WVqNSN5b

### Paper build number:
333

**Comment by electronicboy** [comment]
A player has a map which is rendering and loading chunks, that's all we can really see/say, but, there are wider issues tracking this

**Comment by crazykidney** [comment]
Could it be related to many map arts existing?
