### ISSUE TITLE
All Server Chunks are "frozen" after one Day of playing.

### ISSUE THREAD

**Issue by Aragur** [PaperMC/Paper#3491]
###  Timings or Profile link:
https://timings.aikar.co/?id=f4c2f5fa2b7545789156d2ccc7e7423b

### Description of issue:
After one day of playing every chunk is in a frozen state.  
So you can't interact with mobs.  
Can't pickup blocks.  
You can eat.  
You can break blocks.  
Other Players don't see the blocks broken but get kicked for flying if they step on them.  
This issue didn't happen on older Versions of Paper. But I don't know which Versions they were maybe 299-320

### Plugin list:
Own coded Plugin only for Chat modification. (Same Problem happens with no plugin active)

### bukkit.yml, spigot.yml, paper.yml, server.properties
Using default with the exception of anti-xray enabled

### Other helpful links
A Video https://streamable.com/zalk33

### Paper build number:
Latest (333)

**Comment by aikar** [comment]
Assuming latest has helped here? I did identify some cases where the ticket throttle could let the player move into chunks that were not added as a player ticket yet, and I'm thinking they then immediately unloaded next tick.

However, I think this is now resolved as I force add the ticket if its missing in the priority method, though I'm not sure that covers every potential :/

Going to tweak it for guarantee, but I think this is mostly fixed now.

**Comment by Aragur** [comment]
@aikar it looks like that my Plugin caused the issue.  
It has done Webrequests in the Main Thread.  
But why I couldn't find this in the TPS record?  Or why does this freeze Chunks and not the Server completely (TPS freeze or sth like this)

**Comment by electronicboy** [comment]
TPS is a bad metric, you'd need timings/incremental watchdog for stuff like that (and, even timings will only tell you so much)

**Comment by Aragur** [comment]
Okay and how can look at them?  
Timings report also hasn't showed anything special.  
But my real question is why some chunks where frozen, and some worked perfectly fine?
