### ISSUE TITLE
Problem with building in 1.8.8 source

### ISSUE THREAD

**Issue by Vladimir-Urik** [PaperMC/Paper#3492]
It would not be bad if you use source code instead of patch files in version 1.8.8, because many people, including me, have problems with building from patches.
If someone has already built me ​​the source code please send it

**Comment by electronicboy** [comment]
1.8.8 is not supported, if you have everything installed as per the readme, it will build just fine too

sharing sources is also not permitted, which is why this repo does also not provide the actual source tree
