### ISSUE TITLE
Multiple chunk saving fail (Failed to save NBT)

### ISSUE THREAD

**Issue by luizsusin** [PaperMC/Paper#3495]
### Link/paste of stack trace
https://www.heypasteit.com/clip/0IUR6X

### Plugin list:
Quite a few, but as far as I know, CrafTITStackMob (which is mine) is the only one who stores an NBT data on entity. However, I do not use the class VillagerTrades. I truly don't think this is related to a plugin.
Plugins (59): AdvancedPortals, AdvancedRegionMarket, AsyncWorldEdit, AuthMe, AutoMessage, BeastWithdraw, BlockVersion*, ChestSort, ColoredAnvils, CommandHook, ConsoleSpamFix, CrafTITClans, CrafTITCrates, CrafTITEconomy, CrafTITEssentials, CrafTITPositions, CrafTITRegions, CrafTITShop, CrafTITSpawners, CrafTITStackMob, CrafTITWebhook, EntityDetection, EpicHeads, FogusCore, GoldenCrates, HolographicDisplays, ImageOnMap, IronElevators*, LuckPerms, MaxBans*, mcMMO, Minepacks, Multiverse-Core, MyPet, PlaceholderAPI, PlugMan, ProCosmetics, ProtocolLib, ProtocolSupport, PvPManager, RedProtect, SamAliases, ServerListPlus*, SimpleJail*, SkinsRestorer, spark, SunLight, SuperVanish, SusinCore, SusinEvents*, TAB, Vault, Vote*, Votifier, Wild, WorldBorder, WorldEdit, WorldGuard, Zenchantments

### Actions to reproduce (if known):
Not sure, it randomly starts happening from the server startup. Every single error happens for the same reason: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.server.v1_15_R1.VillagerTrades. For some reason, It randomly happens only sometimes after the server startup. Sometimes it simply doesn't. Truly unpredictable.

### Paper build number:
Paper version git-Paper-332 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by aikar** [comment]
This would imply your jar is being replaced while the server is running.

It seems like you might have something trying to auto update paper? If so, you need to turn that off, as that is the source.

Please join discord if you need further help from the community on this.

**Comment by aikar** [comment]
Actually leaf pointed out this was a load order issue. will fix in next build by preloading the class.

**Comment by luizsusin** [comment]
Perfect! Thank you!
