### ISSUE TITLE
Broken PlayerList Packet

### ISSUE THREAD

**Issue by Vladimir-Urik** [PaperMC/Paper#3496]
In version 1.8.8, an error disappears when I create a tab using packets:
`[13:04:45 INFO]: GGGEDR lost connection: Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine`

**Comment by Proximyst** [comment]
Well that sucks. Now fix it yourself; versions older than 1.15.2 are unsupported by Paper.

**Comment by yannicklamprecht** [comment]
1.8.8 is not supported use 1.15.2

**Comment by Vladimir-Urik** [comment]
You don't know how to fix all my plugins I have programmed for version 1.8.8 it would mean a lot of work :/
???

**Comment by Proximyst** [comment]
Your bad decisions when it comes to support is not our problem; it's made clear both on the Discord and on papermc.io that older versions are 100% unsupported.

**Comment by Vladimir-Urik** [comment]
I know they are not supported but I need to fix it: / I mainly use it because I do a pvp server

**Comment by Proximyst** [comment]
This is astonishing and you won't believe it: You can PvP on 1.15.2 too. The version is unsupported. Figure it out yourself, you're on your own.

**Comment by aikar** [comment]
Note the error message states it's not even a code problem.
It sounds like a firewall is closing the connections.

**Comment by Vladimir-Urik** [comment]
> he error message states it's not even a code problem.
> It sounds like a firewall is closing the connections.

I have the firewall turned off
