### ISSUE TITLE
Experience hide in Join

### ISSUE THREAD

**Issue by Danifoxe** [PaperMC/Paper#3497]
### What behaviour is expected:
Experience bar with my current experience when i login.

### What behaviour is observed:
Experience bar empty when i login.

### Steps/models to reproduce:
When i logout and rejoin to my server, the bar is empty. It continues until i get more exp, and it shows my current experience. (other players report the same)

![2020-06-03_10 00 19](https://user-images.githubusercontent.com/59784220/83654021-25feab80-a582-11ea-915b-6c0e35f2ad92.png)
![2020-06-03_10 01 56](https://user-images.githubusercontent.com/59784220/83654027-28f99c00-a582-11ea-8e50-dc12140ba6b7.png)

### Plugin list:
AuthMe, CoreProtect, CourierNew, DiscordSRV, dynmap*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, FastLogin, GriefPrevention, GSit, LuckPerms, ProtocolLib, Quests, QuickShop, SkinsRestorer, TimeVote, Vault, Votifier, VotingPlugin, WorldEdit

### Paper build number:
Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
I dont know if it is a Paper, plugin or MC bug.

Thanks.

**Comment by electronicboy** [comment]
The server can take a moment to send that, but, it 100% works fine, replicate without plugins, especially as you're running plugins at high risk for stupidity...
