### ISSUE TITLE
Paper Timings Exception

### ISSUE THREAD

**Issue by Rhbarber** [PaperMC/Paper#3499]
### What behaviour is expected:
Ussual Joining and no Timings Error

### What behaviour is observed:
Timings Exception when Player Joining

### Steps/models to reproduce:
Player Joining

### Plugin list:
Plugins (38): AuthMe, BetterEnd, BetterSleeping3, BloodMoon, Chunkmaster, CombatLogX, CommandSigns, CoreProtect, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, HolographicDisplays, HomeGUI, HubBasics, HungerGames, KitPvP, LiteJoin*, LuckPerms, MaintenanceSpigot, MCInteractive, MineChess, Multiverse-Core, Multiverse-Inventories, OldCombatMechanics, PlaceholderAPI, PluginConstructorAPI, ProtocolLib, SimplePortals, SkinsRestorer, TAB, UltimateKits, Vault, VoidGenerator, WorldBorder, WorldEdit, WorldGuard

### Paper build number:
Paper 334

[Paper 334 1.15.2 Timings Issue.txt](https://github.com/PaperMC/Paper/files/4726122/Paper.334.1.15.2.Timings.Issue.txt)

**Comment by aikar** [comment]
This is fixed but FYI you are using the wrong version of Essentials, please update to the updated and proper version: https://www.spigotmc.org/resources/essentialsx.9089/
