### ISSUE TITLE
Separate level seed for nether and end.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#350]
Is it possible to have a separate level seed for nether and end respectively, detached from the main server.properties level seed? That way you could change the seed to regenerate an entirely new nether/end world when resetting them, but keep the same seed for the primary overworld for worldedit //regen support.

Being able to define each world's seed separately would help tremendously in avoiding players setting homes to all the end cities and boats.

**Comment by josephworks** [comment]
@Zbob750 this is smart idea

**Comment by mikroskeem** [comment]
@josephworks Do not bump issue tickets with comments which do not add anything useful to conversation.

**Comment by aikar** [comment]
old ticket finally closed @mibby, Build 270+
```
seed-overrides:
  world_name: string or integer seed
```
Uses same strategy MC does (hash code of the string)

This will not default be in your  paper.yml since we would never default a seed override. You will need to add entir esection
