### ISSUE TITLE
java.lang.VerifyError with plugin using Jackson (JDA dependency)

### ISSUE THREAD

**Issue by Andre601** [PaperMC/Paper#3502]
### What behaviour is expected:
The plugin should work fine without any issues.

### What behaviour is observed:
A plugin will throw the `java.lang.VerifyError` when using either the Jackson library directly, or a dependency, which has it as its own dependency set, without shading the library.

Relocating the Jackson library in the plugin fixes the issue, however.

### Steps/models to reproduce:

1. Make a plugin that either uses JDA or Jackson
2. Run a PaperMC server with the newest build (334)
3. Start the server with the plugin and non-relocated dependencies.

### Plugin list:
AdvancedTabOverlay*, Animatronics*, ArmorStandTools, BKCommonLib, CinematicUI, Citizens, DeluxeChat, DeluxePlugins*, DiscordSRV, Essentials, EssentialsSpawn, HeadDatabase*, HelpPagePlus, HolographicDisplays, InfoHeads, InteractiveBoard*, LeaderBalloons, LeadWires, LightAPI*, LuckPerms, MailMe, Maplands, MessageAnnouncer, Multiverse-Core, OpenAudioMc, PlaceholderAPI, **PowerPlugins**, ProtocolLib, QuickShop, ServerListPlus, StatusNPC, SurveyPlus*, Vault, VoidGenerator, WarpSystem, WorldEdit, WorldGuard

(The plugin name in **bold** is the one with the issue)

### Paper build number:
PaperMC 334 (MC 1.15.2)

### Anything else:
This was tested using PaperMC 334 and 284 (Latest one I used before updating) and while the error appeared on 334 does it not on 284, meaning that at some point between those updates, either PaperMC, Spigot or Minecraft (Depending from where PaperMC pulls its source to patch) have received an update that affected the Jackson library used (either added it, or changed version)

Looking at the dependencies of PaperMC does it look like that it doesn't add Jackson, so it must be on either Spigot's or Minecraft's end.
Knowing both sides and how likely it is that they will fix this, is it better to report this here to get patched/fixed.

**Comment by zachbr** [comment]
Please include the stacktrace for the VerifyError in your ticket.

**Comment by Andre601** [comment]
https://hatebin.com/arcbwdsdjg

**Comment by Proximyst** [comment]
```
  Reason:
    Type 'com/fasterxml/jackson/core/JsonParseException' (current frame, stack[0]) is not assignable to 'com/fasterxml/jackson/core/exc/StreamReadException' (stack map, stack[0])
```

I have a feeling the plugin is loading one of these classes from another plugin. Mind sharing full logs?

**Comment by Andre601** [comment]
This is the full log from start up until I executed the stop command
https://paste.helpch.at/dalaniqige.md

**Comment by A248** [comment]
If you open up the Paper-334's patched jar, you'll notice that there is no com.fasterxml.jackson package. So, Jackson is not in Paper after all (unless it has been relocated to some CB-internal package besides org.bukkit.craftbukkit.libs that I'm unaware of).

Your problem is here:
```
[PowerPlugins] Loaded class com.fasterxml.jackson.core.Versioned from QuickShop v4.0.2.12 which is not a depend, softdepend or loadbefore of this plugin.
```
QuickShop must have a different version of Jackson. It's almost always a good idea to relocate dependencies. Either try without QuickShop, or, as you suggested, relocate.

**Comment by Andre601** [comment]
I'll move it to QuickShop then.

And I already investigated this and interestingly enough do they have jackson as dependency, but it is commented out, which is weird.
So perhaps this has been fixed already but a new version wasn't pushed yet.

**Comment by Andre601** [comment]
But it is kind of interesting, that this error never appeared when using an older version of Paper (284), but does appear on newer ones (334).
Any particular reason why that is? The plugin QuickShop didn't change version between the server updates, so I can only think of JDA updating Jackson, [but this isn't the case either...](https://github.com/DV8FromTheWorld/JDA/commit/4bf1d48f0c52eeb39a493f6d454a62dd5fc2a424#diff-392475fdf2bc320d17762ed97109a121) (Was updated in december)

**Comment by aikar** [comment]
Yes, we improved the class loader to favor your own class loader over others.

However, that is then having its own set of quirks for plugins that are not configured correctly.

So it helps duplicate dependencies in some ways and hurts mixed/missing deps in others :/ 

the end goal was that if 2 plugins shade same lib theyd each pull their own, but it appears that isn't always the case.
