### ISSUE TITLE
Paper 334 hard crash?

### ISSUE THREAD

**Issue by crazykidney** [PaperMC/Paper#3503]
### Link/paste of stack trace
https://pastebin.com/uPc8VTWY

### Plugin list:
none

### Actions to reproduce (if known):
Not sure, player moving too fast?

I was told in discord to enable **prevent-moving-into-unloaded-chunks** so I did, the crash still occurs and paper wont shutdown peacefully, have to kill it.

Could be related to https://github.com/PaperMC/Paper/issues/3395

### Paper build number:
334

**Comment by electronicboy** [comment]
not enough info, pretty sure.I also said to not report this given the current known issues tracking stuff related to unloaded chunk movement...
