### ISSUE TITLE
Paper 334 crash on entering the End

### ISSUE THREAD

**Issue by Mineinjava** [PaperMC/Paper#3504]
### Link/paste of stack trace

Server logs:
https://pastebin.com/Wd8Z9bCS

Also, my server is stuck on `Saving chunks for level 'world_the_end'/minecraft:the_end`

Plugin list:
Vault
FogusCore
Saberfactions
GoldenCrates
EssentialsX
EssentialsX Chat
worldedit

### Actions to reproduce (if known):
2 players enter end portal

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
334

**Comment by Mineinjava** [comment]
also, the end never loaded a single chunk. I dont know why it takes so long to save.

**Comment by aikar** [comment]
In this specific case, your end world has not been converted to the newest version of Minecraft and it was busy doing the world conversion, which sadly is very slow. 

Once you get it to get past this initial conversion, it would be ok. I suggest raising watchdog timeout temporarily to like 2 minutes if crashes before it ever gets a shot to finish it, or at worst case, use --forceUpgrade to do it offline.

Join us on discord if you need any further tips for this.
