### ISSUE TITLE
First PlayerInteractEvent not called after living entity spawn

### ISSUE THREAD

**Issue by Gleyder42** [PaperMC/Paper#3508]
### What behaviour is expected:
If you click a living entity, PlayerInteractEvent and PlayerInteractEntityEvent should be called.

### What behaviour is observed:
PlayerInteractEvent and PlayerInteractEntityEvent are called both, except if I spawned the entity.
If I spawend the entity, the first click only calls PlayerInteractEntityEvent, the following clicks are calling both events again.

### Steps/models to reproduce:
Make a listener and print the events to the command line. Make sure it's only the main hand.
Spawn any living entity with a spawn egg (I used a pig).  This should print PlayerInteractEvent. Then right click the entity. This should print PlayerInteractEntityEvent. Click the same entity again. This should print PlayerInteractEntityEvent and PlayerInteractEvent. Your log shoud look like this.

PlayerInteractEvent
PlayerInteractEntityEvent
PlayerInteractEntityEvent
PlayerInteractEvent

```
public class ClickListener implements Listener {

  @EventHandler
  public void onInteract(PlayerInteractEvent event) {
    if (event.getHand() != EquipmentSlot.HAND) {
      return;
    }

    System.out.println("PlayerInteractEvent");
  }

  @EventHandler
  public void onInteract(PlayerInteractEntityEvent event) {
    if (event.getHand() != EquipmentSlot.HAND) {
      return;
    }

    System.out.println("PlayerInteractEntityEvent");
  }

}
```

### Plugin list:
Only mine to reproduce the bug.

### Paper build number:
git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by MrIvanPlays** [comment]
What about PlayerInteractAtEntityEvent?

**Comment by blablubbabc** [comment]
Maybe related / caused by the same underlying issue: https://hub.spigotmc.org/jira/browse/SPIGOT-5610
PlayerInteractManager caches certain interaction event results and then reuses that result inside PlayerConnection for the next handled interaction.

**Comment by Machine-Maker** [comment]
I believe this issue was fixed at some point. Following the replication steps, I got PlayerInteractEvent when I used the spawn egg, but all subsequent right clicks spit out PlayerInteractEntityEvent.
