### ISSUE TITLE
Server shutdown while workbench crafting results in loss of items.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#351]
If you are in a workbench crafting and the server shuts down / restarts, you lose the items that were in the workbench. Is there any way to prevent this?

**Comment by zachbr** [comment]
I could never reproduce this, if it did exist it should now be fixed as of the latest merge.

**Comment by mibby** [comment]
Hm, alright. Hopefully it is resolved upstream. :) I'll let you know if I hear back from anyone that it is still occurring, as I believe intended behavior is to drop the items on the ground on restart.
