### ISSUE TITLE
Villagers are able to obtain professions from workstations they can't access

### ISSUE THREAD

**Issue by greenywd** [PaperMC/Paper#3510]
### What behaviour is expected:
Villagers can only obtain a profession from an accessible workstation.

### What behaviour is observed:
Villagers are able to obtain professions from workstations that they can't access.

### Steps/models to reproduce:
I think this bug relies on the Villager being able to see the workstation (in certain scenarios), but not being able to get to it. Regardless, all you have to do is trap a villager in a room with a workstation with the entrance/exit being a 2x1 gap with a trapdoor on the floor (stops the villagers from being able to leave, but players can still run through). Place a workstation outside of the room and break the one inside. 

### Plugin list:
None, was able to reproduce on a fresh Paper Server. 

### Paper build number:
334

### Anything else:
Video of bug: https://www.youtube.com/watch?v=yCIvaScDjW4

Additionally, Villagers don't get a job from a workstation placed like [this](https://i.imgur.com/y6x21Hr.png), so I suspect it's got something to do with the height of the trapdoors messing up their pathfinding.

**Comment by aikar** [comment]
This is expected vanilla behavior. It's due to the fact that Pathfinding does not count a trap door as a collision. 

Definitely not fixing this and angering everyone else.

**Comment by greenywd** [comment]
Ah, fair enough. Definitely seemed a bit weird to me but can't complain if it's vanilla!
