### ISSUE TITLE
Help fix TPS

### ISSUE THREAD

**Issue by bloheey** [PaperMC/Paper#3512]
###  Timings or Profile link:
https://timings.aikar.co/?id=df7fdca1b5484c85a298a1ea27c310be

### Description of issue:
How to configure configs or add a plugin so that the TPS is 20, at least with 100 players?
The main idea of the server is vanilla.

### Plugin list:

![image](https://user-images.githubusercontent.com/49293340/83947690-439d7080-a821-11ea-963e-7f6a2df7036e.png)

### bukkit.yml, spigot.yml, paper.yml, server.properties
paper - https://pastebin.com/VQ4Ubd70
bukkit - https://pastebin.com/tfHTRX3N
spigot - https://pastebin.com/w4SKRQ3i
server.properties - https://pastebin.com/JpzLFdbe

### Paper build number:
![image](https://user-images.githubusercontent.com/49293340/83948124-de974a00-a823-11ea-9a71-8eac5051385f.png)

**Comment by electronicboy** [comment]
The issue tracker is not for support with timings, please use the discord/irc/forums
