### ISSUE TITLE
Build #803 is Breaking Pistons & Making Blocks Disappear

### ISSUE THREAD

**Issue by WonderDave** [PaperMC/Paper#352]
Everything was good with build #802, but with build #803 every piston is breaking apart when redstone is applied.  The broken piston is dropped on the ground and can be picked up, although the client shows a weird half-piston until I log out and back in.  Interestingly, the block (or blocks) that are being pushed by the piston are completely gone after logging out and back in.

To reproduce, just put down a piston (of any type) and place a redstone torch behind it.  The piston will extend and then break up.  No errors are produced in the console.

I'm using a bunch of plugins, but everything seems to work fine with build #802, so I'm pretty sure the problem lies with whatever changes were made in #803.  If I go back to using #802, the problem goes away and all is good (although the broken pistons are still broken and need to be replaced, and the vanishing blocks are still gone).

The problematic Paper version is:  This server is running Paper version git-Paper-803 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Think we've got this figured out now.
Builds 804 and newer should be fixed. Thanks for reporting.
