### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by coco0325** [PaperMC/Paper#3521]
### Link/paste of stack trace
https://hastebin.com/esosiyolec.php

### Plugin list:
AdvancedAchievements, AntiAFK, Barrels, BetterRTP*, BungeeTabListPlus, ChatControl, Clans, Clans-Spigot-Part, ClearLag, CMI, CMIPaperLib, CoreProtect, CS-CoreLib, DeluxeMenus, DisableJoinMessage*, DiscordSRV, DyedBackpacks, ExoticGarden, ExtraHeads, FriendsAPIForPartyAndFriends, GemsEconomy*, GriefPrevention, GriefPreventionFlags, HeadDatabase*, IllegalStack, LangUtils, LessPillagers, LuckPerms, MarketPlace, MaSuiteCore, MaSuiteHomes, MaSuiteTeleports, MaSuiteWarps, Matrix, Multiverse-Core, MySQL, MysqlPlayerDataBridge, NametagEdit*, PartyAndFriendsGUI, PlaceholderAPI, PlayerWarps, PlayerWarpsBungee*, PluginConstructorAPI, PlugMan, ProCosmetics, ProtocolLib, PvPInvite, SAML, ShowItem, Slimefun, SlimeLabTweak, TradeMe, Vault, VaultChatFormatter*, VillagerOptimiser, VoidGenerator, WorldBorder, WorldEdit, WorldGuard

### Paper build number:
1.15.2 #341

**Comment by Toffikk** [comment]
This crash is probably caused by LuckPerms , and / or by coreprotect 
Try updating these to the latest version , 

https://luckperms.net/download

https://www.spigotmc.org/resources/coreprotect.8631/

**Comment by electronicboy** [comment]
Nothing to do with LP, the server took too long to tick and was killed by watchdog, check the full logs
