### ISSUE TITLE
Sea mobs spawn with over 1000 entities around 1 player.

### ISSUE THREAD

**Issue by DoubleGe** [PaperMC/Paper#3523]
Normally sea mobs don't spawn that much as now. ATM with Build #342 (don't know if it happened earlier) (loading dimensions it will also happen)

**Picture**
![2020-06-08_22 28 32](https://user-images.githubusercontent.com/29043515/84078675-9588f680-a9d9-11ea-9707-4f16a6c000a9.png)
![2020-06-08_22 28 52](https://user-images.githubusercontent.com/29043515/84078678-96ba2380-a9d9-11ea-9c5f-da755f18d7c8.png)

Plugin list:
CoreProtect
MaintenanceSpigot

Paper build number:
git-Paper-342 (previous version: git.Paper-299)

Timings (From build 348)
[https://timings.aikar.co/?id=e579a8f0eebc41d98a176bdfb4ce0c33](url)

**Comment by WonderDave** [comment]
It looks like we're experiencing the same situation on my server.  I'm also not sure exactly when it started, but I'm pretty sure everything was okay with build 284.  I then upgraded directly to build 334, at which point we began seeing the above water mob issue.

**Comment by kickash32** [comment]
If someone could narrow down the range of builds where this issue was introduced, it would really help find the cause.

**Comment by OrangeCatUnderscore** [comment]
I think this started sometime after build 321, but no later than build 324... It's been causing some crashes that seemed to start after updating from 321 to 324.

**Comment by OrangeCatUnderscore** [comment]
I've done a bit more testing, this seems to start with build 323.

**Comment by Jakesta13** [comment]
> I've done a bit more testing, this seems to start with build 323.

Here's a example with what we got on the server this build was tested on, see screenshot.
![12009342-856E-46B5-BF26-94A94492F7FC](https://user-images.githubusercontent.com/10874330/84316239-cb90bc80-ab38-11ea-8c55-4cef447c39d6.png)

**Comment by DoubleGe** [comment]
prob Same issue on hostile mobs spawn with lots and lots of mobs 

![2020-06-11_15 32 54](https://user-images.githubusercontent.com/29043515/84391204-f0e4ff80-abf8-11ea-86a9-87955d9108c3.png)
![2020-06-11_15 33 07](https://user-images.githubusercontent.com/29043515/84391211-f2aec300-abf8-11ea-9dff-ae109e9f6766.png)

**Comment by kickash32** [comment]
Can you try with `per-player-mob-spawns: true` and see if it fixes this issue?

**Comment by Jakesta13** [comment]
> Can you try with `per-player-mob-spawns: true` and see if it fixes this issue?

For my server this is the current setting, I'm not sure if this would be the issue?

I feel like perhaps it's not 'listening' to the mob cap limit and just spawning mobs because it thinks no mobs are spawned so it just keeps spawning more over x ticks until it crashes..

**Comment by kickash32** [comment]
Can you also try `count-all-mobs-for-spawning: true`?

**Comment by Jakesta13** [comment]
> Can you also try `count-all-mobs-for-spawning: true`?

Good idea, I was considering this but never got round to it.
I'll update to the latest build and enable this and see what goes on and update here

**Comment by Jakesta13** [comment]
> Can you also try `count-all-mobs-for-spawning: true`?

Ok getting responses from players and it looks like it stopped mob spawning from going out of control ... I have also noticed it hasn't crashed as often (for some reason it crashes after restarts but I don't know what is causing it, crash reports state chunk loading, cant enable full papermc dumps since I'm using multicraft panel).

Edit: it appears to still spawn fish like mad

**Comment by kickash32** [comment]
A world/chunk download may help in the investigation (please note relevant location(s))

**Comment by Jakesta13** [comment]
> A world/chunk download may help in the investigation (please note relevant location(s))

Thanks, I've asked players to let me know where they see the mass amount of fish... I'll download regions where it's happening.. I haven't seen it personally but the server still crashes occasionally

**Comment by DoubleGe** [comment]
> A world/chunk download may help in the investigation (please note relevant location(s))

Last time I checked it only happened after restart (prob something with loading the world that's hanging on the spawning mobs)

**Comment by Jakesta13** [comment]
> > A world/chunk download may help in the investigation (please note relevant location(s))
> 
> 
> 
> Last time I checked it only happened after restart (prob something with loading the world that's hanging on the spawning mobs)

Dude! I never thought of mentioning it mostly happens right after restarts... it crashes about 4 or more times after a restart.. about a minute or two apart...

**Comment by DoubleGe** [comment]
> > > A world/chunk download may help in the investigation (please note relevant location(s))
> > 
> > 
> > Last time I checked it only happened after restart (prob something with loading the world that's hanging on the spawning mobs)
> 
> Dude! I never thought of mentioning it mostly happens right after restarts... it crashes about 4 or more times after a restart.. about a minute or two apart...

Before Build 342 it was also on login for me. With build 348 it was only after restart

**Comment by Jakesta13** [comment]
> > > > A world/chunk download may help in the investigation (please note relevant location(s))
> 
> > > 
> 
> > > 
> 
> > > Last time I checked it only happened after restart (prob something with loading the world that's hanging on the spawning mobs)
> 
> > 
> 
> > Dude! I never thought of mentioning it mostly happens right after restarts... it crashes about 4 or more times after a restart.. about a minute or two apart...
> 
> 
> 
> Before Build 342 it was also on login for me. With build 348 it was only after restart

Weird... 323 it has been awful since that build and 450 is where it calmed down.. it used to crash non-stop most of the time before... I also decreased water mobs since and still crashes

**Comment by kickash32** [comment]
Could you post those crash reports?

**Comment by Jakesta13** [comment]
> Could you post those crash reports?

I was having a hard time understanding what to look for in the files but I have attached most of them (my other archives include non-paper crashes, and finding the ones related will be a lot of combing, these ones here should be exact to this issue) in the case that there's something important in them that I missed, the dates are of the zip archive date and include a range of crash dates inside.
I'm using Multicraft Panel, and I can't seem to enable the function to allow full dumps unfortunately

Also in-case it adds interest, some of the crashes happened right after a player exclaimed about the amount of fish.

EDIT: I scrubbed the Crash reports and have posted them below, World seed and player coordinates have been retracted.
[Crash-reports_June17-2020-Scrubbed.zip](https://github.com/PaperMC/Paper/files/4794448/Crash-reports_June17-2020-Scrubbed.zip)
[hs_err_June-17-2020.zip](https://github.com/PaperMC/Paper/files/4794449/hs_err_June-17-2020.zip)

**Comment by aikar** [comment]
I had a hunch and talking with kickash, there is an issue with mob spawning since 1.14 that is a Vanilla bug, unless there's some deep magic in vanilla's system that I'm not seeing.

The issue is that previously mob spawning factored in actual loaded chunk count to calculate mob goals, so that your mob limits scaled while the chunks loading around you were still loading.

But now, while chunks are loading, the full mob limit is being desired, and its spawning new mobs before the server gets a chance to finish loading the mobs to even see that more mobs are not needed.

We need to revert mojangs change here and ensure that mob limits still scale based on loaded vs target goals.

**Comment by SupppRabit** [comment]
> I had a hunch and talking with kickash, there is an issue with mob spawning since 1.14 that is a Vanilla bug, unless there's some deep magic in vanilla's system that I'm not seeing.
> 
> The issue is that previously mob spawning factored in actual loaded chunk count to calculate mob goals, so that your mob limits scaled while the chunks loading around you were still loading.
> 
> But now, while chunks are loading, the full mob limit is being desired, and its spawning new mobs before the server gets a chance to finish loading the mobs to even see that more mobs are not needed.
> 
> We need to revert mojangs change here and ensure that mob limits still scale based on loaded vs target goals.

Is there any progress now? How to minimize the  effect as far?

**Comment by aeonlamb** [comment]
If this bug is the result of some code in 1.14, I will say, I never experienced this in my several months of running a 1.14.4 server. I just updated to 1.15.2 earlier this month (I took a break from mc for a while), and noticed this happening with a test server of mine. Haven't seen it happen on my prod server just yet, but I imagine it can still happen depending on where you login after a restart, since it has the same settings as that test server.

Also, my server has the config setting `count-all-mobs-for-spawning: true`, and this occurs with fish, squids, dolphins, and bats- all other mob spawning seems normal. I had this setting enabled in 1.14.4 as well and it did not cause any issues for me then.

**Comment by Jakesta13** [comment]
> If this bug is the result of some code in 1.14, I will say, I never experienced this in my several months of running a 1.14.4 server. I just updated to 1.15.2 earlier this month (I took a break from mc for a while), and noticed this happening with a test server of mine. Haven't seen it happen on my prod server just yet, but I imagine it can still happen depending on where you login after a restart, since it has the same settings as that test server.
> 
> 
> 
> Also, my server has the config setting `count-all-mobs-for-spawning: true`, and this occurs with fish, squids, dolphins, and bats- all other mob spawning seems normal. I had this setting enabled in 1.14.4 as well and it did not cause any issues for me then.

They recently changed how chunks are loaded either in the noted builds above (on mobile) or just before them.
The way the chunks load now probably amplifies the problem brought in 1.14, but the chunk loading method is much better except this problem... they'll need to sort the mob spawning rather than chunk loading now.

**Comment by iCaitlyn** [comment]
Just recently noticed this as well on a test server of MC version 1.15.2, build 385. Had not noticed this on our live 1.15.2 server of the exact same build, but this was immediately very apparent when the test server was booted up with an exact copy of the world used on the live server.

**Comment by Folas1337** [comment]
I can very much confirm that, I've reported that on https://github.com/PaperMC/Paper/issues/4338 and it's definitely happening with water mobs the most for some reason.

I've had a player in an ocean monument and they had 145 guardians around them (counted by using "/minecraft:execute" command). Really a big deal and it seems fine on spigot for me which definitely means it's related to paper.

**Comment by kickash32** [comment]
> I had a hunch and talking with kickash, there is an issue with mob spawning since 1.14 that is a Vanilla bug, unless there's some deep magic in vanilla's system that I'm not seeing.
> 
> The issue is that previously mob spawning factored in actual loaded chunk count to calculate mob goals, so that your mob limits scaled while the chunks loading around you were still loading.
> 
> But now, while chunks are loading, the full mob limit is being desired, and its spawning new mobs before the server gets a chance to finish loading the mobs to even see that more mobs are not needed.
> 
> We need to revert mojangs change here and ensure that mob limits still scale based on loaded vs target goals.

This needs to be reevaluated again. I looked over the code in 1.16.5 and it seems mob limits are indeed based on chunks loaded (again).

**Comment by Owen1212055** [comment]
As stated above it seems the logic has changed, and generally, no issues like this have been reported for a while.
If however you still are able to reproduce this, please comment on this issue/open a new one and this will be able to be reopened.
