### ISSUE TITLE
Bad Timings

### ISSUE THREAD

**Issue by mrunningmasterc** [PaperMC/Paper#3525]
###  Timings or Profile link:
https://timings.aikar.co/?id=5237c78f0c934c73aaaa1ad04c1ca388

### Description of issue:
Lots of bad timings and chunk timings

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit: https://pastebin.com/cC0xHxJd
Spigot: https://pastebin.com/Mydd37jP
Paper: https://pastebin.com/eEYw0N5Y

### Other helpful links
I've used this link to help optimize my server: https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/

### Paper build number:
This server is running Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by aikar** [comment]
Please use discord for assistance and Discussion with timings
