### ISSUE TITLE
tps becomes 0.0 and the server crashes

### ISSUE THREAD

**Issue by ttt0** [PaperMC/Paper#3529]
i have a survival server
average of 30 to 50 players playing
i don't use leak plugin
I bought

Tps goes down to around 0.0 and the server gets locked server doesn't turn off friends or doesn't give an error
Sometimes nothing happens for 2 days, sometimes 2 times in 1 hour
My server version:1.15.2 #335
gives such an error from the panel.

link: https://hastebin.com/taroqeligu.md

Logs:
https://cdn.discordapp.com/attachments/689480201306112167/719929425789190194/message.txt
Paper build number:
https://prnt.sc/swmzuk

**Comment by electronicboy** [comment]
update

**Comment by ttt0** [comment]
what?

**Comment by electronicboy** [comment]
Update your server, the main cause of your issues has been fixed
If you need support with timings, please use the discord/IRC/forums

**Comment by ttt0** [comment]
I will try.

**Comment by ttt0** [comment]
@electronicboy https://hastebin.com/pazeguseka.md

I upgraded version, separate problem continues

**Comment by electronicboy** [comment]
```
[04:31:08] [Paper Watchdog Thread/ERROR]: 		cloutteam.samjakob.gui.types.PaginatedGUI.getInventory(PaginatedGUI.java:333)
[04:31:08] [Paper Watchdog Thread/ERROR]: 		dev.aglerr.krakenlevels.commands.LevelsCMD.onCommand(LevelsCMD.java:577)
```
That plugin is causing network requests to be performed on the main thread

**Comment by ttt0** [comment]
@electronicboy https://throwbin.io/RWHNyTg I get such an error then my server crashes I use 1.15.2 #348
