### ISSUE TITLE
.cmd errors!

### ISSUE THREAD

**Issue by ovidiubachmatchi** [PaperMC/Paper#353]
Hello,
i have default settings, i don't have any plugin and the version of paperspigot is 443

Look at **http://hastebin.com/egidatudew.sm** ; look at all please!

**Comment by ovidiubachmatchi** [comment]
I have update the paperspigot but the only change is 
This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by sgdc3** [comment]
Very outdated version, do you really need to use version 1.8.8?

**Comment by ovidiubachmatchi** [comment]
Yes, because the 1.8.8 is most played

**Comment by sgdc3** [comment]
@SomkidApple add --nojline at the end of your starting parameters ("java -jar paperspigot.jar --nojline")
