### ISSUE TITLE
Slow chunk loading since #344+

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#3530]
### What behaviour is expected:
Normal chunk loading, slow but constant.

### What behaviour is observed:
Since version 344 chunk loading seems heavy and takes too long to load.

### Steps/models to reproduce:
Just load chunks, fly and explore world.

### Plugin list:
None.

### Paper build number:
git-Paper-344 & git-Paper-345.

### Anything else:
For comparison, I have recorded two videos:

git-Paper-341: https://youtu.be/hdaJaic3EbU
git-Paper 344 & 345: https://youtu.be/wmc57TwQQg0

**Comment by aikar** [comment]
can you provide a timings report. part if it is intentional, but i question view distances to fully understand expectations.

moving faster should make them load faster when you get near them, does it not?

part of the changes was to intentionally add some delay to chunks as they spiral out so that moving players dont end up loading all the chunks to then discard.

**Comment by lordrius** [comment]
Sure,
https://timings.aikar.co/?id=caf3897d63444cc78037510773cf0245

Moving faster seems that they load a bit faster but not too much. Server's view distance is set to 8 and I'm not using no-tick-view-distance. Small survival server, few players.

Thanks!

**Comment by compieter-gh** [comment]
Can confirm.
Have the same issue since that release.
if i need too supply my configs say so

**Comment by Neo-TA** [comment]
can confirm this is in 346 also https://imgur.com/a/R7Nhe7c and https://imgur.com/a/ifqiJhg

**Comment by clrxbl** [comment]
https://streamable.com/afzkj0 Probably related too, slow chunk loading.

**Comment by Momonche** [comment]
Can confirm too, I'm on build 343 and it's ok but if I update to 346, can't have more that 4 TPS (Tested on a RPG server with 2520 Citizens NPC)

**Comment by HexedHero** [comment]
Same issue as clrxbl, sometimes gets stuck on the end of regions.

**Comment by HexedHero** [comment]
Video of my issues:
https://i.imgur.com/FU0xvCN.mp4
