### ISSUE TITLE
Cartograpers

### ISSUE THREAD

**Issue by EOT3000** [PaperMC/Paper#3531]
https://pastebin.com/0v9F1LFJ

Server lags and has a chance of crashing when cartographers created

My server has disabled structures generating, so I think, what's going on is it's looking for woodland mansions (for explorer maps), but since structures are disabled, it crashes (same thing that happened when I did /locate)

Build #345

**Comment by aikar** [comment]
Check your paper.yml, you didn't disable seed based did you?

seed-based-feature-search: true

**Comment by electronicboy** [comment]
Vanilla issue, disabling structures does not stop the server looking for them when generating maps, etc; We spoke to them recently about this one iirc

**Comment by aikar** [comment]
I just wouldnt expect it to be a big hit if seed based is filtering which chunks are accessed and then we're only loading the chunk to structure start level.

unless its just finding lots of failures.

**Comment by electronicboy** [comment]
> unless its just finding lots of failures.

Is what I'm thinking is going on here, it's finding a chunk which could have one, failing, and going for the next... I guess we could maybe provide an optimization for seed based, if the chunk isn't generated, don't try to hit it if the chunk isn't generated, people not using seed based are probably just gonna have to be SOL here

**Comment by aikar** [comment]
well for some maps thats ok, but stuff like finding nearest mansion map intentionally looks for ungenerated (unless configs set) so they can find an unlooted mansion. but accessing Structure starts really shouldn't be that bad though.

@EOT3000 can you provide a timings report so we can just see all configs.

**Comment by Phoenix616** [comment]
> Vanilla issue, disabling structures does not stop the server looking for them when generating maps, etc; We spoke to them recently about this one iirc

Do you mean [MC-151364](https://bugs.mojang.com/browse/MC-151364)? Because apparently that was fixed in a 1.16 snapshot. Might not be worth backporting the fix for that seeing as 1.16 is about to release though.

**Comment by EOT3000** [comment]
https://timings.aikar.co/?id=e76ee94401f44214b688cd5f6dfdf905

**Comment by Proximyst** [comment]
Duplicate of #3536. 

I'm closing this as the other issue has a linked PR.
