### ISSUE TITLE
Some chunks are not loaded

### ISSUE THREAD

**Issue by Ling556** [PaperMC/Paper#3537]
### What behaviour is expected:
Block should return to normal when I break block.

### What behaviour is observed:
Since version 345,Block not return to normal when I break block.

### Steps/models to reproduce:

![2020-06-11_19 59 39](https://user-images.githubusercontent.com/59788198/84383340-af674b00-ac1e-11ea-9e0d-25286ffda32a.png)
![2020-06-11_19 59 42](https://user-images.githubusercontent.com/59788198/84383347-b2fad200-ac1e-11ea-9e65-7ac158ff10dd.png)

### Paper build number:
git-Paper-348 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by stonar96** [comment]
Cannot reproduce.
What is your `update-radius` setting? Can you please post the complete `anti-xray` config section from paper.yml or a timings link?
Did you have a high ping or low TPS while observing this issue?

**Comment by Ling556** [comment]
sorry,it is not anti-xray issues.
Some chunks are not loaded.
This problem occurred in the last few updates
https://timings.aikar.co/?id=e21a20c81c2f4b5585da742d7708a264
![2020-06-12_22 47 53](https://user-images.githubusercontent.com/59788198/84515686-5fac8080-acff-11ea-8639-40d126a70eee.png)
![2020-06-12_22 47 23](https://user-images.githubusercontent.com/59788198/84515702-64713480-acff-11ea-9784-19d3032c3134.png)

**Comment by Ling556** [comment]
Here is the video
[3.zip](https://github.com/PaperMC/Paper/files/4773931/3.zip)

**Comment by Laukage** [comment]
Happening to me aswell.

**Comment by FixTheAdmin** [comment]
Also getting this. TPS is at 20 but chunks stop loading after a while.

**Comment by fredagsguf** [comment]
This is also happening without anti-xray turned on..

**Comment by aikar** [comment]
And your sure your on latest? changes were made in some of the most recent builds that should have solved this.

**Comment by fredagsguf** [comment]
I'm on latest (well 365) and the issue seems to persist.

**Comment by aikar** [comment]
Anything your doing to trigger it? Plugins?

I can't reproduce this....

**Comment by fredagsguf** [comment]
When 1-3 players fly in a direction.
the player which aren't flying then won't get any chunks when they teleport and such.

i have however found a somewhat solution to it, i changed max-auto-save-chunks-per-tick: from 24 to 12, which seemed to help a bit.

![image](https://user-images.githubusercontent.com/46964809/85296972-72167f00-b4a2-11ea-84c4-c4cd95d995b1.png)

**Comment by stonar96** [comment]
All [plugins](https://hasteb.in/ajupuyes.lua) that both, @w1O42O86726 and @Laukage, have installed: HolographicDisplays, LiteBans, LuckPerms, mcMMO, ProtocolLib, spark, Vault, WorldEdit, WorldGuard
