### ISSUE TITLE
Server using every single MB of allocated memory on reloading resource manager

### ISSUE THREAD

**Issue by Crack3dC0d3** [PaperMC/Paper#3538]
### What behaviour is expected:
Well it shouldnt use 3gb to reload the resource manager right?

### What behaviour is observed:
It s using the 3GB allocated to 

### Steps/models to reproduce:
Download a fresh jar, Start a server on 3GB, The server should start without any issues. 
Now restart it and it gets killed when reloading resource manager because it ran out of ram.
(note im using the ptero panel with oomkiller enabled) 

### Plugin list:
None, I disabled them all to see if it would work and it doesnt.

### Paper build number:
348

### Anything else:
Well, this issue started occuring when i started using aikars GC flags.

**Comment by electronicboy** [comment]
Please actually read the page in its entirety
