### ISSUE TITLE
Slime block retraction bug

### ISSUE THREAD

**Issue by ondrejvajdak** [PaperMC/Paper#3539]
### What behaviour is expected:
Expected behaviour is the slime block should move, when the sticky piston retracts.

### What behaviour is observed:
The slime block was not moved.

### Steps/models to reproduce:
https://puu.sh/FVcFR/a312033aeb.mp4

### Plugin list:
Occurs on servers with/without plugins.

### Paper build number:
[22:22:21 INFO]: This server is running Paper version git-Paper-348 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
I think the problem is the piston under the slime block. This bug is in Spigot (built with BuildTools) too. The bug is not in the vanilla (tried in singleplayer).

**Comment by aikar** [comment]
Your only shot of this getting fixed (if this even is really a bug) is for someone to tell us why it's broken, what specific change caused it.

So much of piston weirdness like this depends on JVM internal quirks and simply changing the smallest piece of code can break weird stuff like this.

It could literally be anything. It could be that this doesn't work in vanilla consistently either and you're simply hitting JVM hashcode sorting where certain positions in the world work and others don't.

so to be straight, this isn't something I'm going to spend any of my time looking at.

**Comment by DoubleGe** [comment]
I tried this in singleplayer it seems to be a facing problem
![2020-06-12_10 48 06](https://user-images.githubusercontent.com/29043515/84483865-39082e80-ac9a-11ea-915f-06a9bd2f1331.png)
The left one is the broken one and the right one behaves as it should be 
(works only when facing North or South)

**Comment by ondrejvajdak** [comment]
@DoubleGe Oh, interesting. So it could be a problem in vanilla? Tried it in 1.14.4 (singleplayer) and the bug is still there (does not work in every direction). Should I report it to Mojang?

**Comment by DoubleGe** [comment]
You can report it but it's probably already reported I can check for you if you want

**Comment by DoubleGe** [comment]
You can post it if you want, I can't find the issue on Mojang bug tracker

**Comment by ondrejvajdak** [comment]
![b2797fe5c2](https://user-images.githubusercontent.com/29640516/84541244-4dc6df80-acf7-11ea-984e-b5376b28ad06.png)

🙂

**Comment by DoubleGe** [comment]
So Mojang won't fix it and you just to change your design

**Comment by aikar** [comment]
You can't fix it, it relies on JVM internals. 
And trying to make it consistent will break everything.
Going to close this since its expected behavior.
