### ISSUE TITLE
Mobs + Water issue. TPS LOSS when mobs are dragged by water.

### ISSUE THREAD

**Issue by DiegoDaniel** [PaperMC/Paper#3545]
###  Timings or Profile link:
This report is the one from the video i've uploaded (see below).
https://timings.aikar.co/?id=2fac16db573b45c4801ea4902e196eb8#timings

The next one (↓) is before a server restart without "Spartan" because i thought that Spartan was the problem. But the problem persist.
https://timings.aikar.co/?id=e8a0c63bf52e45f0a9f9fd8b2be3325f#timings

### Description of issue:
I'm testing some Mobs Farms from the people on my server, and this farm was working 10/10 before updating paper.
The thing is, when the water is released, and it drags mobs, the tps loss begins.
I'm 100% sure that this didn't happened before with others paper versions.
The last i remember working fine was paper 340. 

### Plugin list:
I will attach 3 ss.
![plugins1](https://user-images.githubusercontent.com/14002872/84466331-8b702d80-ac4f-11ea-8dda-481b7f853151.png)
![plugins2](https://user-images.githubusercontent.com/14002872/84466333-8c08c400-ac4f-11ea-979c-37d857624beb.png)
![plugins3](https://user-images.githubusercontent.com/14002872/84466335-8c08c400-ac4f-11ea-9af9-d3b90dc20c72.png)

### bukkit.yml, spigot.yml, paper.yml, server.properties
paper.yml : https://pastebin.com/whRnR29M
spigot.yml: https://pastebin.com/Ei6GpU82
bukkit.yml: https://pastebin.com/snqZtskE
server.prop: https://pastebin.com/hUniYzAN

### Other helpful links
I've made a video and uploaded to YT. Hope it helps.
It shows the farm a little and the tps loss.

CONSIDER: There are some mythic mobs, i have tested this issue without them, and still happends, so i couldn't say "the problem is MM".

Video: https://www.youtube.com/watch?v=zsZAeXMoUSw

### Paper build number:
#349, also with #348 and #347. Prolly others versions but i couldn't test them yet.

**Comment by aikar** [comment]
Not a bug. Mob farms cause lag. Mobs in water cause more lag than mobs not in water because it disables Entity Activation Range.

Water flowing is also a lot of processing (see Fluid Ticks)

It is what it is.
Limit scope of farms to reduce impact of a single farm on server.

**Comment by aikar** [comment]
and yes those plugins are adding up cost. GSit is adding a lot to fluid ticks
