### ISSUE TITLE
Still have performance issue with recent builds

### ISSUE THREAD

**Issue by Momonche** [PaperMC/Paper#3546]
###  Timings or Profile link:
I can't generate timings because the server crash after few minutes

### Description of issue:
With build after 343, my TPS can't be more than 5, but with 343 I have 20
Maybe related to this https://github.com/PaperMC/Paper/issues/3530 but not sure

### Plugin list:
Plugins (86): ActionBarAPI, AnimatedScoreboard, AreaShop, ArmorEquipEvent*, AsyncWorldEdit, AsyncWorldEditBossBar, AvancedItemEffets*, Bank, BetonQuest, BlyatRPG, boosCooldowns*, Broadcaster, BungeeTabListPlus, ChestCommands, Citizens, ClearLag, ColoredBooked, CommandHook, Core, CoreProtect, CrazyCrates, DeathMessagesPrime, DMPCitizens, EnchLimiter, EpicSpawners, Essentials, EssentialsAntiBuild, EssentialsMysqlStorage, EssentialsSpawn, Factions, FBasics*, GemsEconomy*, HealthBar*, HelpopEra, HolographicDisplays, HolographicScoreboard*, Hub, IllegalStack, InfiniteAnvil*, InfiniteDispenserX, Jobs, JSONAPI, LiteBans, Lores*, LuckPerms, Magic, MassiveCore, MessageAnnouncer, MineProtectEra, MobArena, MoneyPrinters, MovingDevApi, Multiverse-Core, Multiverse-Portals, MysqlPlayerDataBridge, NoCheatPlus, NoElytra*, OldCombatMechanics, OpenInv, PearlFix, PlaceholderAPI, PlayerHeads, PlugMan, ProtocolLib, ProtocolSupport, RewardPRO, RPGChest, RPGMenu, RubisEra, Sentinel, ServerSigns, ShopGUIPlus, SignEdit, SkinsRestorer, spark, Statz, TPBukkit, Vault, VentureChat, VoteBox, VoxelSniper, WarnBan, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Other helpful links
There is no server-crash logs but errors in console:
https://pastebin.com/7pBy09f9
https://pastebin.com/tKEYHYRT

### Paper build number:
Try with build 346 and 350 (MC: 1.15.2)

**Comment by electronicboy** [comment]
watchdog reports are not wanted on the issue tracker unless you can prove that something is basically blocking the main thread, without more info (timings, or at least the full log...), this issue is useless, please seek support on the discord/irc/forums
