### ISSUE TITLE
Individual Mob Spawn Limits

### ISSUE THREAD

**Issue by partydev** [PaperMC/Paper#3549]
**Is your feature request related to a problem? Please describe.**
Currently you can only limit mob spawns to animals, water-animals, ambient, and monsters. Some mobs lie outside of this range, some people want to modify individual monsters, etc. 

**Describe the solution you'd like**
An individual spawn limit for every single mob in Minecraft. Gives further control to server owners for how many monsters of each type the server will attempt to spawn, allows server owners to completely disable certain mobs in a less expensive way.

**Describe alternatives you've considered**
There are none!

**Comment by electronicboy** [comment]
per-type limits are defo not a viable option if you're tryna go on the "save performance" aspect...

**Comment by partydev** [comment]
> 
> 
> per-type limits are defo not a viable option if you're tryna go on the "save performance" aspect...

Could you go into a little more depth as to why doing something like splitting the monster group into skeleton/spider/creeper etc. would be more expensive? I guess it's more information to constantly consider. If setting individual mob limits is not a viable option, then perhaps being able to fully disable spawns of certain mobs would be. At least for mobs especially that are outside of those groups.

**Comment by Chasewhip8** [comment]
Wouldnt hurt performance that much for an extra map lookup but then again this is something that should go into a fork, paper isn't really the place for this IMO.

**Comment by electronicboy** [comment]
The server doesn't split mob spawning into entity types, it splits them into creature types; Having limits for each entity type would go against the current logic and shove us back into the *very* reason why we err against using mob limiting plugins, etc; 

There is no real way to say "only have X number of Y", without going essentially after the fact, which is what plugins can already do as efficiently with the prespawn events, you end up in a state which is literally no better than what we urge people to avoid
