### ISSUE TITLE
Buycraft can't execute skript-made commands.

### ISSUE THREAD

**Issue by xGioChR** [PaperMC/Paper#355]
# Incompatibility (Bug)
### What behaviour is expected:

With classic Spigot, I can make BuycraftX execute Skript-made commands.
### What behaviour is observed:

BuycraftX does not manage to execute the command with PaperSpigot.
### Steps/models to reproduce:
1. Run a server with PaperSpigot, Skript and BuycraftX;
2. write a simple command with skript ( I did it for you http://pastebin.com/NcwmMwvv ) ;
3. Create a free (it happens even with paid packages) content on the buycraft store;
4. link your store with your server;
5. claim the package on the webstore;
6. check the console.
### Plugin list:

BuycraftX and Skript.
### Paper build number:

I'm using the final 1.8.8 build, the "fix" one.
# Crash, Stacktrace

Here it is the crash -> http://pastebin.com/AdJBwRsZ
# Suggestions

I think this could happen even with other plugins.
I would suggest to change the way PaperSpigot handles commands.

**Comment by MrPowerGamerBR** [comment]
> I would suggest to change the way PaperSpigot handles commands.

I would suggest to change the way Skript handles commands.

IIRC the issue happens because Skript registers commands in the wrong way, it isn't PaperSpigot's (also, PaperSpigot 1.8.8 isn't supported anymore) fault that a plugin doesn't register his commands the normal and non-buggy way.

**Comment by zachbr** [comment]
This was already fixed. Or should I say worked around, since it is Skript's fault anyway.

Your outdated version is unsupported and doesn't contain the fix. Not much for us to do.
