### ISSUE TITLE
some random exception caught warning

### ISSUE THREAD

**Issue by MithrandirCraft** [PaperMC/Paper#3551]
### Link/paste of stack trace
https://gist.github.com/MithrandirCraft/c2b2faa5a3d10a07bc017067fc1639bb

### Plugin list:
 Plugins (45): 40ServidoresMC, AdvancedPortals, AntiXrayHeuristics, AuthMe, AutoMessage*, BungeeTabListPlus, ChatControl, ClearLag*, CoreProtect, CrazyCrates, DiscordSRV, ElytraBalance, EnjinMinecraftPlugin, Essentials, EssentialsSpawn, FastAsyncWorldEdit, FastLogin, GriefPrevention, GriefPreventionFlags, HolographicDisplays, HolographicScoreboard*, LibsDisguises, LuckPerms, MarriageMaster, MiniaturePets*, MythicMobs, NerfVillages, PlaceholderAPI, PlayerHeads, PremiumVanish, ProtocolLib, Shopkeepers, SkinsRestorer, spark, Spartan, Spawner, SSX-Connector*, StatsPvP*, Trade, Vault, Votifier, VotingPlugin, Wild, WorldEdit, XpBottles

### Actions to reproduce (if known):
idk

### Paper build number:
350

**Comment by jaylawl** [comment]
Propably caused by MythicMobs' spawners

**Comment by electronicboy** [comment]
Generally caused by plugins mangling in the networking code causing issues.

**Comment by aikar** [comment]
this should now be improved on latest.
