### ISSUE TITLE
Silent Commands

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3557]
I would like an option to prevent OP's from seeing other player's command feedback, similar to the gamerule
`sendCommandFeedback`, but only for other players.

This could be added as an option (`silent-commands` or `hide-command-feedback-for-other-players`) in paper.yml and would allow OPs to use commands silently but still be able to see their own command feedback. Basically vanish but for commands.

**Comment by MiniDigger** [comment]
How would other players see your command feedback? This sounds like something a plugin is doing weirdly

**Comment by ghost** [comment]
Like when a player uses a command like "/setblock" all other OPs see
_[Luracasmus: Changed the block at -1393, 65, 757986]_.

I want this to only be visible in the console / logs.

(This is for a server with many OPs where admins want to be able to use commands without everyone seeing it.)

**Comment by aeonlamb** [comment]
I think you would know when you just used a command yourself... there's a message in chat showing the results of the command you just entered. How is this any different from just disabling command feedback entirely?

**Comment by ghost** [comment]
Many players like to be able to see their own command feedback (help commands and clickable chat messages).
