### ISSUE TITLE
Swords bugged on latest versions

### ISSUE THREAD

**Issue by Elric02** [PaperMC/Paper#3563]
### What behaviour is expected:
Swords should make sweep attacks when attacking, and deal damage based on base damage, enchants and custom enchants (plugin)

### What behaviour is observed:
Swords seem to act as if they weren't swords anymore, no sweep attacks, custom enchants and vanilla enchants not increasing damage. Base damage still works fine though.

### Steps/models to reproduce:
Install Paper latest version and go fight some mobs. Hopefully (or not) you'll have the same issue

### Plugin list:
AdvancedAchievements, Chunkmaster, Citizens,CoreProtect, CrazyEnchantments, EntityDetection, EntityTrackerFixer, Essentials,FastAsyncWorldEdit, Jobs, LibsDisguises, LimitPillagers, LuckPerms, Multiverse-Core, MythicMobs, NBTAPI, PlaceholderAPI, ProtocolLib, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Paper build number:
350

### Anything else:
Not definitely sure that Paper is the cause, but restarting the server didn't fix the issue, and downgrading from Paper 350 to Paper 342 did. (I chose 342 because that's the version I had before upgrading to 350)

**Comment by aikar** [comment]
This is absolutely a plugin problem or some misunderstanding...

For one, we've never touched that area, and especially in any recent version.

**Comment by HexedHero** [comment]
EntityDetection?

**Comment by Elric02** [comment]
I'll try to re-upgrade to build 350 after having removed some plugins, which one would be causing this ? EntityDetection ? 
(I'll delete EntityTrackerFixer anyway, I've been told it's useless)

**Comment by HexedHero** [comment]
Didn't know the EntityDetection was the one by Phoenix, should be fine. but its defo one of the others.

**Comment by xDeeKay** [comment]
Having the same problem as of updating to build #350. Plugins we have in common: Essentials, LibsDisguises, Multiverse-Core, PlaceholderAPI, ProtocolLib, Vault, WorldEdit, WorldGuard

**Comment by xDeeKay** [comment]
An out of date LibsDisguises premium build is the culprit. Updating to 10.0.12-Premium returned the functionality of sweeping edge.

**Comment by Elric02** [comment]
No issue on latest Paper version anymore (371), closing the issue
