### ISSUE TITLE
Disable ticking for empty hoppers

### ISSUE THREAD

**Issue by Findus642** [PaperMC/Paper#3564]
**Is your feature request related to a problem? Please describe.**
Yes / No. Whilst hoppers are greatly optimised in PaperSpigot compared to other server softwares people still experience issues with them, mainly causing a TPS drop due to amount ticked.

**Describe the solution you'd like**
Having the option within the paper.yml to disable ticking for empty hoppers (If possible). This feature could be a per-world thing or enabled globally, similar to the Anti-XRay.

**Describe alternatives you've considered**
There is many other solutions such as reducing how often hoppers are ticked, only allow certain people to place hoppers, etc..

**Additional context**
None.

**Comment by aikar** [comment]
and how do you expect it to know if it's empty or not... ? It does so by ticking lol.

The process just then checks for if it has any item to move, or any item to "suck in", either item above it or item from a connected inventory.

There isn't really this concept of what your asking for, outside of maybe a "cooldown-on-empty" but even that might break hopper contraptions.
