### ISSUE TITLE
Inventory Bug (Duplication)

### ISSUE THREAD

**Issue by CroaBeast** [PaperMC/Paper#3566]
### What behaviour is expected:
Not duplicated items or even bugs with the inventory

### What behaviour is observed:
Items Duplicated and Full Lost of the inventory

### Steps/models to reproduce:
Idk how to reproduce that. Some players told that their armor was duplicated or even all their inventory was erased when they reconnected.
### Plugin list:
___A list of your plugins___
ChatSentinel, Citizens, CitizensCMD, ConsoleSpamFix, CoreProtect, DiscordSRV, Essentials, EssentialsSpawn, gProtector, HamsterAPI*, HolographicDisplays, InfiniteScoreboard, LevelPoints, LiteBans, LockLogin*, LuckPerms, LuckPermsChat, MessageAnnouncer, MobFarmManager, Multiverse-Core, MyCommand, PacketListenerApi*, PlaceholderAPI, PluginHider*, ProtectionStones, ProtocolLib, SkinsRestorer, StaffPlus, TAB, Vault, ViaVersion*, VoteDay, Wild, WorldBorder*, WorldEdit, WorldGuard
### Paper build number:
Paper-345

### Anything else:
Sorry, I try a lot to fix this, Idk what to do now

**Comment by chickeneer** [comment]
Fair warning. This issue will be closed for the reason you acknowledged in the Steps to reproduce.

If you can't reproduce it, we won't be able to reproduce it either. If there is an issue, it is more than likely going to be a problem with one of your plugins. Without more information, we have no way to know which or give any specific guidance beyond... Remove plugins till the issue stops happening. Then get support from that plugin's author.

**Comment by CroaBeast** [comment]
Well, I try to ask some players to tell me exactly how the items are duplicated.

1. Put the item you want in your offhand.
2. Use /spawn.
3. Exit Survival/Vanilla using the command "/server lobby".
4. With the NPC of the lobby, go back to Survival/Vanilla.
5. Use /back and the items are duplicated.

The armor duplication is a bit odd.
1. Die or disconnect closing Minecraft.
2. Reconnect the fast you can.
3. The duplicated armor will be appear in you inventory.

For Inventory Completely Deleted, is the same for Armor Duplication, I think
1. Die or disconnect closing Minecraft.
2. Reconnect the fast you can.
3. You have no items in your inventory.

Is this good enough? I have problems to elaborate more my words.

**Comment by partydev** [comment]
Have you reproduced this without any plugins? Additionally, this may be due to your server being a cracked server, which is unsupported. Very likely an issue with your setup rather than Paper causing this.

**Comment by FranKusmiruk** [comment]
> Have you reproduced this without any plugins? Additionally, this may be due to your server being a cracked server, which is unsupported. Very likely an issue with your setup rather than Paper causing this.

The only thing an online and offline mode server has to be considered different is the way players are authenticated, it can't produce bugs like this so that shouldn't matter. I do agree it isn't supported though.

**Comment by Draycia** [comment]
> > Have you reproduced this without any plugins? Additionally, this may be due to your server being a cracked server, which is unsupported. Very likely an issue with your setup rather than Paper causing this.
> 
> The only thing an online and offline mode server has to be considered different is the way players are authenticated, it can't produce bugs like this so that shouldn't matter. I do agree it isn't supported though.

Except the fact that the plugins typically used with offline mode servers can very easily cause issues, and other plugins may behave erratically with offline mode servers as well, even if the mode itself isn't the direct cause for issue.

**Comment by CroaBeast** [comment]
Oh, so If my server is in offline mode, is the issue itself I guess. Well, thanks for the anwser.

**Comment by Draycia** [comment]
That's not what we're saying. We're saying your plugins may be an issue.

**Comment by CroaBeast** [comment]
So, do anyone has an idea what plugin is causing that conflict/bug?

**Comment by MissPotato** [comment]
You're going to want to figure out a way to reliably reproduce this and then remove plugins until the issue goes away.

**Comment by CroaBeast** [comment]
Yeah, so thanks for the answer again.

**Comment by Proximyst** [comment]
As this issue hasn't been bumped in quite a while, I'll assume you found which plugin caused it. Contact us on Discord if you can reproduce a dupe without plugins.
