### ISSUE TITLE
Move TNT duplication option to dedicated config file (along with other unsupported options)

### ISSUE THREAD

**Issue by Techcable** [PaperMC/Paper#3567]
I understand the desire to make this configurable, but I think we should consider moving config options like this to a separate file like 'danger.yml'

It indicates to users it's a bad idea and Paper developers frown on the option. I'm aware this change caused quite an uproar. Experienced users who **really** want this feature can enable it. The file name (along with a large disclaimer in the header) should deter everyone else.

I think we should consider placing a warning in the log for each enabled option - further discouraging usage.

There seemed to be a strong concensus on Discord tonight in favor of moving this option to a separate file. I know I personally want to discourage it's use!

We may need to update timings reports to handle the new config (or maybe not if it's part of logs)

**Comment by jacobsandersen** [comment]
I think this is a great idea and would help to discourage users from enabling them while still allowing them to be present. I'm aware there is a section, 'unsupported-settings', but I fear that some users simply won't read into what section they are actually editing. They will simply edit.

Moreover, I think if this is implemented (and I sure hope it is), a PR should be made to timings to show a warning if any of the options are not at their defaults (akin to the GC warning.)

**Comment by MiniDigger** [comment]
could also highlight the fact that unsupported options are used in timings reports

**Comment by aikar** [comment]
nah this is a step too much for it. typically people aren't going to blindly set "enable dupes" configs. 

Plus, we will still give them support stuff completely unrelated to the change. just won't support anything caused by enabling the config.
