### ISSUE TITLE
BlockState#update(boolean, boolean) does not change state of redstone components

### ISSUE THREAD

**Issue by RealityTest** [PaperMC/Paper#3569]
### What behaviour is expected:
When changing a redstone component and triggering a update for that block it should update its powered state accordingly. 

### What behaviour is observed:
For example: I create a plugin that changes the rotation of "Directional" blocks like a powered repeater and use BlockState#update(true, true) on it. Even if the repeater now doesn't have a something to power it, it keeps the powered state (See attached images for a better understanding). The same thing happens for other redstone components like pistons. It does update the blocks next to it but only updates itself when manually triggering an update (for example placing or breaking a block next to it). The same problem exists in vanilla Minecraft when you use a debug stick to change the rotation of a redstone component.

### Steps/models to reproduce:
This is the code snippet I used to test it:
```
@EventHandler
public void onClick(PlayerInteractEvent e){
  Block block = e.getClickedBlock();
  BlockState state = block.getState();
  BlockData blockData = block.getBlockData();
  Directional directional = (Directional) blockData;
  directional.setFacing(BlockFace.NORTH);
  state.setBlockData(directional);
  e.setCancelled(true);
  state.update(true, true);
}
```

### Plugin list:
No plugins except for the provided example above

### Paper build number:
git-Paper-349

### Additional Information:
![state1](https://user-images.githubusercontent.com/20795287/84783094-228b0b80-afe9-11ea-8203-a685538719c8.png)
![state2](https://user-images.githubusercontent.com/20795287/84783096-23bc3880-afe9-11ea-991d-700587b66dd9.png)

**Comment by electronicboy** [comment]
This is an implementation detail of how redstone/blocks in general work, the block would need to be unpowered by a wire/source update

**Comment by aikar** [comment]
note that redstone power level is one of the properties in that block state update call, since you obtained clone of current and simply changed one property, it set the power level back to the value. 

You can set it to 0.

The apply physics flag here tells NEIGHBORS of the repeater that it updated, and the repeater would only receive a recursive update if the wire itself changed state as a reaction and triggered its own physics updates.

**Comment by RealityTest** [comment]
Thanks for the helpful information. I was hoping that there's a way to trigger a update for the repeater programmatically the same way breaking or placing a block next to it does (Which does update the powered state). 
Setting the power state to 0 is unfortunately not a solution since of course the problem would also occur the other way around (when rotating a unpowered repeater to a powered wire) so I guess I'll look for a workaround.

**Comment by aikar** [comment]
add a world.setType(air) before your last. update(true, true); line I think will do it.
