### ISSUE TITLE
StackOverflowError when shift clicking in custom inventories

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#357]
logs
http://pastebin.com/siU7nkGU

timings
https://timings.aikar.co/v2/?id=884e8c45642b4121b5ef21d5d31d470a

config
[s1.zip](https://github.com/PaperMC/Paper/files/343875/s1.zip)

other info
my server is crashed : O

**Comment by Black-Hole** [comment]
Seems like this bug:
https://hub.spigotmc.org/jira/browse/SPIGOT-1107

**Comment by ghost** [comment]
latest crash logs
http://pastebin.com/sXtb5e8z

**Comment by josephworks** [comment]
this is a spigot error. why don't you try and make a patch for it

**Comment by zachbr** [comment]
Fixed upstream
