### ISSUE TITLE
Show server.properties viewdistance in timings

### ISSUE THREAD

**Issue by Decme** [PaperMC/Paper#3570]
When offering help in debugging others' server lag, knowing what they've set the viewdistance to in server.properties would be very handy.

Other useful server.properties entries might include:
difficulty
spawn-monsters
max-players
spawn-npcs
spawn-animals

**Comment by aikar** [comment]
Already done, I just have to add front end display of it. I'll get to it soon as I can.

**Comment by aikar** [comment]
You can add &raw=1 to end of a timings URL to see it currently.
