### ISSUE TITLE
Teleporting to extreme Y values crashes server and client

### ISSUE THREAD

**Issue by T-x-T** [PaperMC/Paper#3575]
### What behaviour is expected:
The TP command not allowing teleporting to invalid coordinates

### What behaviour is observed:
The TP command allows you to teleport to an unsafe height, this can result in getting kicked or the entire server + client crashing

### Steps/models to reproduce:
teleport to anything close to or over 2147483647 and the client and server crash
teleport to anything over 30mio and you get kicked with the message `Invalid move player packet received `

Teleporting to high negative Y coordinates doesn't reset your position so you get caught in a loop of getting kicked / crashing the server

It seems like this only effects the Y coordinate, X and Z just say you got teleported to the high coordinate, but you dont actually get teleported

### Plugin list:
none

### Paper build number:
git-Paper-353 (MC: 1.15.2)

### Anything else:
I would assume that this isn't an issue that isolated to paper, but it would still be nice if the tp command had some validation

**Comment by zachbr** [comment]
The reason the X and Z don't work is we already do that validation. Will look at adding some for Y as well.

**Comment by T-x-T** [comment]
Is it possible to maybe also communicate back that the coordinates are out of bounds, IIRC vanilla does that

**Comment by zachbr** [comment]
Right now it just logs a warning to server console. Due to how the vanilla command code is written it's just a larger diff to communicate it back to players. The only people who should be trying this are those who want to crash your server anyway, so I'm not too upset they don't get a pretty message.

Maybe if someone is ever bored in the future.
