### ISSUE TITLE
Server Crash.

### ISSUE THREAD

**Issue by suoyukii** [PaperMC/Paper#3579]
### Log：
[2020-06-19-1.log](https://github.com/PaperMC/Paper/files/4807450/2020-06-19-1.log)

### Paper build number:
354

**Comment by iamceph** [comment]
You need to provide full log.

**Comment by aikar** [comment]
What is this supposed to be?

**Comment by suoyukii** [comment]
The log has been uploaded.
@iamceph @aikar

**Comment by aikar** [comment]
your server ran out of memory. Try increasing memory or checking if any plugins are having memory leaks.

Please join discord for assistance on that kind of debugging.

**Comment by suoyukii** [comment]
Maybe it has something to do with Geyser-Bukkit.
I'll ask over there.
