### ISSUE TITLE
Server timed out and wont stop without force

### ISSUE THREAD

**Issue by crazykidney** [PaperMC/Paper#3581]
### Link/paste of stack trace
https://pastebin.com/QsvvWD1x

### Plugin list:
None

### Paper build number:
354

**Comment by vladdoser** [comment]
Same, help... https://pastebin.com/T2QZU8j4

**Comment by Proximyst** [comment]
@crazykidney 1.12 is unsupported.
@myself-vladdos For help with that, join the [Discord](https://discord.gg/papermc).

EDIT: I mixed you up, sorry. Kidney, you can join the Discord for help, Vladdos is sadly out of luck.

**Comment by binary-dragon** [comment]
https://pastebin.com/Dy1x0ezN

Having the same issue. Tried updating paper to latest build (1.15.2 #366) and still got the same issue.

**Comment by electronicboy** [comment]
if it's freezing on shutdown, need a jstack, https://docs.oracle.com/javase/7/docs/technotes/tools/share/jstack.html

**Comment by binary-dragon** [comment]
> if it's freezing on shutdown, need a jstack, https://docs.oracle.com/javase/7/docs/technotes/tools/share/jstack.html

it's not happening for me during a shutdown. just during normal gameplay.

**Comment by electronicboy** [comment]
Then that is unrelated to this ticket, this issue is specifically about deadlocking when watchdog kills the server
