### ISSUE TITLE
per-world portal-search-radius not respected 

### ISSUE THREAD

**Issue by phemmer** [PaperMC/Paper#3583]
### What behaviour is expected:
When using a nether portal, the server should search for a portal within the world's configured `portal-search-radius` distance, creating a new one if not found.

### What behaviour is observed:
It appears that the overworld's `portal-search-radius` is used for both overworld & nether, as taking a portal to the nether will use the overworld's `portal-search-radius` when searching for a corresponding nether portal, even if the nether has a different configured value.

### Steps/models to reproduce:
Have config:
```
world-settings:
  default:
    portal-search-radius: 128
    portal-create-radius: 16
  world_nether:
    portal-search-radius: 16
```
* Create an overworld portal at 0,0. Travel through.
* Move nether world portal to 0,0, just to be safe.
* Go back to overworld and create a portal at 0,160, and travel through.  
This should create a portal in the nether within 16 blocks of 0,20. It does not, it instead uses the portal at 0,0.

### Plugin list:
None

### Paper build number:
354

### Anything else:
Changing `world-settings.default.portal-search-radius` appears to affect both traveling from overworld to nether, and nether to overworld, regardless of any world-specific setting.

Having the value the same traveling in both directions creates annoying situations.  
For example, lets say you set `portal-search-radius: 16`. You create a portal in the overworld at 0,160 (corresponds to nether coordinates 0,20). You travel through it and a corresponding nether portal is created at 0,30 (which is properly within 16 blocks of the translated coordinates, 0,20). When traveling the other way, the nether coordinates 0,30 correspond to overworld 0,240, which is outside `portal-search-radius: 16` of the original portal at 0,160, so it creates a new portal.  
So even though you originally created a brand new portal in the overworld, it creates a new overworld portal when leaving the nether.

**Comment by phemmer** [comment]
Was trying to see if I could come up with a plugin to work around the issue, and found that it does seem to acknowledge the existence of the per-world setting, but just doesn't use it.

Created a simple plugin to log the events:
```
    @EventHandler
    public void onPlayerPortalEvent(PlayerPortalEvent event) {
        Location from = event.getFrom();
        Location to = event.getTo();

        getLogger().info(String.format("Portal from=%s@%d,%d,%d to=%s@%d,%d,%d searchRadius=%d",
            from.getWorld().getName(), from.getBlockX(), from.getBlockY(), from.getBlockZ(),
            to.getWorld().getName(), to.getBlockX(), to.getBlockY(), to.getBlockZ(),
            event.getSearchRadius()));
    }

    @EventHandler
    public void onTeleportEvent(PlayerTeleportEvent event) {
        Location from = event.getFrom();
        Location to = event.getTo();

        getLogger().info(String.format("Teleport from=%s@%d,%d,%d to=%s@%d,%d,%d",
            from.getWorld().getName(), from.getBlockX(), from.getBlockY(), from.getBlockZ(),
            to.getWorld().getName(), to.getBlockX(), to.getBlockY(), to.getBlockZ()));
    }
```

Which produces the following as an example:
```
[13:47:55 INFO]: [PortalScale] Portal from=world@0,64,321 to=world_nether@0,64,40 searchRadius=16
[13:47:55 INFO]: [PortalScale] Teleport from=world@0,64,321 to=world_nether@1,101,20
```
So we can see that our nether target was z=40 with searchRadius=16, but it teleported to z=20.

**Comment by darcyamurphy** [comment]
We are also seeing this issue in a server running on version 40 for 1.16.1
