### ISSUE TITLE
spawner-nerfed-mobs-should-jump not working

### ISSUE THREAD

**Issue by eLeCTr1CiPlay** [PaperMC/Paper#3584]
### What behaviour is expected:
When spawner-nerfed-mobs-should-jump is set to true in paper.yml, spawner nerfed mobs should jump/float in water.

### What behaviour is observed:
Mobs are without AI and dont float/jump in water instead they remain submerged underwater.

### Steps/models to reproduce:
spawner-nerfed-mobs-should-jump: true in paper.yml
nerf-spawner-mobs: true in spigot.yml
Add water and wait for monsters to spawn from the spawner.

### Plugin list:
Bug persists on a test server with no plugins.

### Paper build number:
git-Paper-354 (MC: 1.15.2)

### Anything else:
n/a

**Comment by Machine-Maker** [comment]
Reproduced on build 371 with zombies

**Comment by Machine-Maker** [comment]
What mob type did you try this with?

Just tried on build 371 with creepers the settings work as intended; the creepers float up with no ai. I originally thought I was reproducing it until I remembered that zombies do not float anymore. The only entities that will float when spawned by a spawner with those config settings set are
- Bee
- Cat
- Chicken
- Cow
- Creeper
- Enderman
- Horses
- Illusioner
- Llama
- Ocelot
- Panda
- Parrot
- Pig
- Pillager
- Rabbit
- Ravager
- Sheep
- Silverfish
- Spider
- Vex
- VillagerTrader
- Vindicator
- Witch
- Wolf
