### ISSUE TITLE
paperclip is not effective

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [PaperMC/Paper#3585]
paperclip is so big that I doubt if it is a patch

**Comment by aikar** [comment]
is this like a java your momma joke

**Comment by pczmr8v5n454iycf** [comment]
No, seriously

**Comment by MiniDigger** [comment]
if you want to be take seriously, make a serious issue with a serious description

**Comment by pczmr8v5n454iycf** [comment]
https://github.com/PaperMC/Paper/issues/3586
