### ISSUE TITLE
Reduce the size of paperclip

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [PaperMC/Paper#3588]
**Is your feature request related to a problem? Please describe.**
paperclip is so big that I doubt if it is a patch instead of complete class files which break the GPL's linking clause.

**Describe the solution you'd like**
Reduce the size of paperclip

I think repackaging the jar as a tar can do the work

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by clrxbl** [comment]
can you fuck off already
