### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by osum54** [PaperMC/Paper#3590]
### What behaviour is expected:
When using a older version of paper this issue wouldn't happen
I tested exact plugins on paper 318 and it worked and then changed the jar to recent paper and it gave error below.

### What behaviour is observed:
https://pastebin.com/yYHnUTpY

### Steps/models to reproduce:
add advancedchests to plugins folder and try placing one of the modified chests.

### Plugin list:
in the pastebin link.

### Paper build number:
355
works on: 318 didn't try past this though

### Anything else:
The plugin that is giving a error is advanced chest and it didn't error on previous versions when i tested it back to back with the new version.

**Comment by osum54** [comment]
I checked, it works on 354

**Comment by MrEAlderson** [comment]
Can confirm. It's breaking many plugins and should be fixed asap.
I think it happens when calling ItemMeta#setOwner(String) but the player isn't online.
