### ISSUE TITLE
Multiple Ghost Blocks

### ISSUE THREAD

**Issue by osum54** [PaperMC/Paper#3593]
### What behaviour is expected:
No ghost blocks
Here's a gif i made of the machine actually moving correctly: https://i.imgur.com/NMZc07G.mp4

### What behaviour is observed:
https://imgur.com/a/SKOT5O2
Here's a gif of the ghost blocks being made: https://i.imgur.com/TFNkWOK.mp4

### Steps/models to reproduce:
Have a slime block redstone piston moving machine and back away a few chunks while it is going and then come back.
example: https://www.youtube.com/watch?v=rHN-zDvKNbU

### Plugin list:
https://pastebin.com/YTSZ78hz

### Paper build number:
362

### Anything else:
wasn't happening before build 354

**Comment by aikar** [comment]
I don't understand what this picture is supposed to represent

**Comment by Techcable** [comment]
What is a "slime block redstone piston moving machine"? Could you maybe figure out a simpler way to trigger the bug?

I'm not exactly sure what a "ghost block" is. Can you please explain it to us?

**Comment by osum54** [comment]
> I don't understand what this picture is supposed to represent

https://i.imgur.com/C2s5Z4F.png this is what it's suppose to look like
the piston flying machine is moving side to side breaking the sugarcane,


> What is a "slime block redstone piston moving machine"? Could you maybe figure out a simpler way to trigger the bug?
> 
> I'm not exactly sure what a "ghost block" is. Can you please explain it to us?

A redstone flying machine with pistons and redstone something like this: https://www.youtube.com/watch?v=rHN-zDvKNbU

A ghost block is a block that looks like it's there but once you break it, it turns to thin air because it was never actually there.

**Comment by osum54** [comment]
it happens when i go out of range of the chunk it's happening in.

**Comment by osum54** [comment]
Here's a gif i made of the machine actually moving correctly: https://i.imgur.com/NMZc07G.mp4

Here's a gif of the ghost blocks being made: https://i.imgur.com/TFNkWOK.mp4

**Comment by aikar** [comment]
Does enabling piston duplication in paper config resolve it?and you said ghost blocks so they aren't there if you relog right?

**Comment by aeonlamb** [comment]
This was a vanilla issue which I believe was fixed at a certain point. I remember it happening quite frequently in 1.12. It's mostly only noticeable with flying machines, but can happen anywhere pistons push slime blocks, like in the screenshot.

**Comment by osum54** [comment]
> Does enabling piston duplication in paper config resolve it?and you said ghost blocks so they aren't there if you relog right?

correct they aren't really there.

**Comment by osum54** [comment]
> This was a vanilla issue which I believe was fixed at a certain point. I remember it happening quite frequently in 1.12. It's mostly only noticeable with flying machines, but can happen anywhere pistons push slime blocks, like in the screenshot.

this hasn't been happening until updating my paper today.

**Comment by osum54** [comment]
> Does enabling piston duplication in paper config resolve it?and you said ghost blocks so they aren't there if you relog right?

turning piston duplication on does stop this.

**Comment by WonderDave** [comment]
@aikar  I'm also seeing this since upgrading today.  I have a witch farm, and the slime blocks are getting ghosted.  If allow-piston-duplication is set to 'true', then there is no ghosting.  But if I have it set to 'false' (which is what I want), then there is ghosting.

If I log off and log back on, the ghost blocks are gone.

**Comment by Proximyst** [comment]
The ghost blocks were caused by this commit: https://github.com/PaperMC/Paper/commit/96feb68ad9a79292a1bb2f23312b7bd3b2717bc9
