### ISSUE TITLE
Head drops on offline mode appear as Steve/Alex

### ISSUE THREAD

**Issue by Proximyst** [PaperMC/Paper#3594]
### What behaviour is expected:
The head to drop as its proper owner and be that in my inventory.

### What behaviour is observed:
The head appeared to be Steve/Alex, but placing it returned it to its proper owner.

### Steps/models to reproduce:
CraftBook with Head Drops on 1.0 drop chance. This should be replicable with any plugin using `SkullMeta#setOwner`, as that is what CraftBook is doing: https://github.com/EngineHub/CraftBook/blob/master/src/main/java/com/sk89q/craftbook/mechanics/headdrops/HeadDrops.java#L133

### Plugin list:
CraftBook, LuckPerms, Essentials

### Paper build number:
The regression came as of build 355 with this commit: https://github.com/PaperMC/Paper/commit/a70618cd5cb493fe9fe2a2a7375a7b1949d427d7
Build 354 works as expected.

### Anything else:
This is nothing but a hunch, but it might be that it's due to trying to use offline mode UUIDs when the head is not yet a block. I assume this because it works as expected on online mode.

This issue was reported by `pitilon#6950` on the PaperMC Discord.

**Comment by crazykidney** [comment]
Paper 365 - skulls don't get meta data from yml

https://pastebin.com/T7QsFV7N

Might be related

354 works fine

**Comment by Proximyst** [comment]
Not related, but that is indeed an issue. For that one, it appears Aikar missed the minimum 2 cases where a `null` profile is guaranteed to be passed.

**Comment by PatoTheBest** [comment]
I believe #3598 fixes this too

**Comment by 100petr** [comment]
Heads are already drop normally, thank you.

>

**Comment by 100petr** [comment]
Now some heads look normal, others don't.

**Comment by aikar** [comment]
Do you not have bungee online mode = true in paper.yml? That is the setting its checking for online vs offline.

**Comment by 100petr** [comment]
bungee-online-mode: false and I don't have bungee.

**Comment by Proximyst** [comment]
With the following options, the issue is still persistent on build 366:

`bungeecord: false` - `spigot.yml`
`online-mode=false` - `server.properties`
`bungee-online-mode: false` - `paper.yml` (also persistent with this as `true` as I tested originally.)

Note that this _only_ applies to dropped heads. Placed heads work as expected.

**Comment by 100petr** [comment]
![2020-06-24_09 28 48](https://user-images.githubusercontent.com/29830635/85515191-23c9c300-b5fd-11ea-82e1-7378991da45e.png)
The heads still show up as steve / alex

**Comment by 100petr** [comment]
This is only the case with some mobs. For example, zombies and skeleton heads look normal, but spider, cow, enderman, sheep, etc not

**Comment by HexedHero** [comment]
How is your plugin for the head drops handling the drops?

**Comment by 100petr** [comment]
I use a craftbook

**Comment by elmital** [comment]
Hi,
I got similar issue with a custom plugin wich from a `/head playername` command get the playername and give in the inventory of the sender a head with the skin of the playername using `SkullMeta#setOwner` like CraftBook. 
The error :
https://pastebin.com/0V41WRcY
The methods used :
https://pastebin.com/9QU1tZtP

But I observe something interesting using another custom command(`/seen playername`) solve the problem, the command is a command to see the last connection of a player using `OfflinePlayer#getLastLogin()`
code snippet:
https://pastebin.com/SkmVJwds

Just after using this command the `/head playername` command give the player head with the correct skin without problem even after a server reboot.
I tried with the [MHF_heads](https://minecraft.gamepedia.com/Head#Mojang_skins) and other random player name, I note that if a player account doesn't exist it give a Steeve head and doesn't fire the error.

[GIF using the commands](https://puu.sh/FZYhy/1e1db97952.gif)


I'm on paper-370, not using bungee and with `online-mode=true` in my `server.properties`. Sorry for my english, I hope this may help you.

**Comment by elmital** [comment]
Tested in paper-372, the fix solve my issue.
