### ISSUE TITLE
Lighting update issues

### ISSUE THREAD

**Issue by GitGoppy** [PaperMC/Paper#3595]
### What behaviour is expected:
Proper light updating in cave environment
### What behaviour is observed:
Lighting level for blocks is wrong half of the time, requires manual re-updating of the block's lightning.

### Steps/models to reproduce:
Get a clean paper server, a diamond pickaxe and a stack of torches.
Mine in the cave and place torches behind yourself, you will notice torches occasionally not updating blocks around them and when breaking ores you will notice that the air block is in the darkest light level even though there are either torches or natural light sources nearby. To update the lightning just break and place the block again to fix lighting.

### Plugin list:
No plugins

### Paper build number:
365 1.15.2 b6a25a5
### Anything else:
Issue occured after updating from 350 to 365. No plugin interference confirmed on blank 365 paper server. Probably occured in build 355 when new light engine changes were introduced.

**Comment by aikar** [comment]
i can not reproduce at all on latest. placed a lot of torches and all were fine.

I spent days reviewing every single change on this light patch, and it should line up with vanilla 100% (minus potential for queue order differences but in the scenario you are describing, that will not be at play)

are you at really far coordinates maybe?
is it reproducable in a certain area/seed?

**Comment by GitGoppy** [comment]
On second inspection it seems the culprit was a graphical issue with my minecraft client, I used a blank server but never restarted my client. Now that I tried to test it again today there are no light issues I found. Hence I can securely close this issue.
