### ISSUE TITLE
Add Entity activation range option just for hopper and chest minecarts

### ISSUE THREAD

**Issue by EvelineFlowercrown** [PaperMC/Paper#3596]
I encountered a problem with the entity activation range for misc entities, as it is set to 16 by default and includes minecarts, thereby fucking up big supersmelters and other big contraptions that include hopper minecarts. 

Adding another category for just hopper and chest minecarts (ideally with a higher default setting) would allow players to use those big mashines without also ticking item frames and all the other stuff in the misc section.

Another idea would be to activate them regardless of their distance to the player, as soon as there are changes being made to their inventories. That way you wouldnt have to tick them all the time, but have them working fullspeed when needed.

**Comment by Techcable** [comment]
Why not just expand your activation range for these entities?

**Comment by EvelineFlowercrown** [comment]
I did. And 128 activation range is a good solution for the time being, but I'd rather have only the needed entities ticked and not cause unnecessary lag by ticking item frames and other stuff under the misc section.

**Comment by LaurenceBarnes** [comment]
It would still be a nice thing to have honestly perhaps for Minecarts overall then
