### ISSUE TITLE
Paper Not Starting

### ISSUE THREAD

**Issue by ryans1230** [PaperMC/Paper#360]
### Description of issue:

We are trying to convert from Spigot to Paper, however one of our core plugins is not loading with Paper. See the link below. The latest version of Spigot does work with this plugin, however we'd love to pump that extra performance out of Paper
### bukkit.yml, spigot.yml, paper.yml, server.properties

All of these are stock as we are just trying to get a test server up and running at this point. 
### Paper build number:

810
### What behaviour is expected:

All plugins enabled
### What behaviour is observed:

http://pastebin.com/KGgw6G9m

**Comment by Black-Hole** [comment]
Please read the installation instructions for the "reactivemongo" plugin. Neither Spigot nor Paper bundle Log4J.

**Comment by ryans1230** [comment]
But would that affect Spigot being able to run properly (and load the plugin), and Paper not?

@Black-Hole ETA: We are supplying the required jars when we patch against our library folder: reactivemongo_2.11-0.10.5.0.akka23, reactivemongo-bson_2.11-0.10.5.0.akka23

**Comment by zachbr** [comment]
Your plugin is failing silently on Spigot. Paper does not allow that and disables it when it detects an error in onEnable. Fix your plugin, regardless of whether you end up using Paper.

Edit: for any additional help with this plugin specifically, we'd need to see its source code.

**Comment by ryans1230** [comment]
How does a plugin fail silently yet still load and have function in Spigot?

`[INFO] [ScalaTest] Loading ScalaTest v1`
`[INFO] [ScalaTest] Ensuring index 'Lowercase Username'...`
`[INFO] [ScalaTest] Index already existed`
`[INFO] [ScalaTest] Enabling ScalaTest v1`
`[INFO] [ScalaTest] Connected to WorldEdit`
`[INFO] Done (10.170s)! For help, type "help" or "?"`

**Comment by zachbr** [comment]
Source?
