### ISSUE TITLE
Worldedit //, /sp

### ISSUE THREAD

**Issue by Twister1one** [PaperMC/Paper#3602]
### What behaviour is expected:
At /sp area, recur, single with worldedit
I wish all the loot blocks. (the drop-block and many-block-drop option is true in the config)

### What behaviour is observed:
Currently with superpickaxe certain blocks do not drop

### Steps/models to reproduce:
Download worldedit #5066 and paper #365
/sp area or /sp recur or // in games
destroy a block of diorite, cobble, terracota (not drop)
destroy a block of plank, sand, wool (drop)

### Plugin list:
Worldedit

### Paper build number:
it-Paper-365 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
I already opened a problem on the worldedit github, he told me it's spigot

**Comment by aikar** [comment]
We just need to update upstream. Will aim to do that tonight.
