### ISSUE TITLE
TNT Dupe

### ISSUE THREAD

**Issue by Korinocho** [PaperMC/Paper#3604]
Well there is a TNT dupe involving dead coral. Its pretty easy to reproduce.
There is a video: https://www.youtube.com/watch?v=r-lI0i_XXj4
At 1:40 you can see how it works.
Look like it try to move the tnt but it activate it at the same time.

Its a Vanilla present bug, not a plugin one.

git-Paper-366 (MC:1.15.2)

**Comment by aikar** [comment]
Um. Are you sure you tested this on latest paper? Because we literally just fixed that....

Did you turn the dupe back on in config?

**Comment by Korinocho** [comment]
Let me delete paper.yml and try again. Maybe the config wasnt created (i cant find this config in the file) or something like that.

**Comment by HexedHero** [comment]
Just tested and doesn't work by default and only works with allow-piston-duplication true

**Comment by Korinocho** [comment]
Well i renamed the YML file (so a new one was created) and "allow-piston-duplication" appeared but its under "unsupported-settings" it is right?
Edit: well the fix is working good. Thanks!
