### ISSUE TITLE
Slow chunk loading

### ISSUE THREAD

**Issue by radiant-ai** [PaperMC/Paper#3605]
### What behaviour is expected:
Chunks are loading fast enough

### What behaviour is observed:
Chunks are loading slowly

### Steps/models to reproduce:
Update from __paper-350__ to __paper-365__, players (50+) start to observe very slow chunk loading.

### Plugin list:
![image](https://user-images.githubusercontent.com/43506080/85333594-75f4d200-b49f-11ea-9987-40c67bcaa481.png)

### Paper build number:
__Paper-365__

### Anything else:
I did not change anything except for updating to the newest Paper build. I just want to make sure if this could be caused by the most recent fixes and tweaks in chunk loading algorithms. Thanks.

**Comment by aikar** [comment]
which chunks? the ones in the distance? If so, that's by design. if it's the chunks surrounding the players immediate vicinity, then yes that's a concern.

**Comment by radiant-ai** [comment]
In build 350 when I had 50+ players I could fly with 3x fly speed and chunks were loading fast enough, but now I cannot do it even with default fly speed. Also a lot of players complain about chunk loading after the teleports.
