### ISSUE TITLE
Mobcap depending on player count

### ISSUE THREAD

**Issue by Kasper0911** [PaperMC/Paper#3606]
I was just wondering, if its possible to raise/lower the mobcap depending on the online players on the server. In the morning, not a lot of players are on the server, so the mobcap could be raised up to allow all the spawners to work at full speed. However in the afternoon, there's around 20 players online and the mobcap has to be lowered for the server not to crash.

**Comment by HexedHero** [comment]
https://paper.readthedocs.io/en/latest/server/configuration.html#per-player-mob-spawns

**Comment by Kasper0911** [comment]
> 
> 
> https://paper.readthedocs.io/en/latest/server/configuration.html#per-player-mob-spawns

I know how to change mob cap per player manually. Is there a way so that the mob cap will change based on tps or players online?

**Comment by HexedHero** [comment]
Did you even read what the config setting does. That is exactly what it does. It changes the limits inside bukkit.yml to be per player not global.

**Comment by Kasper0911** [comment]
I did read what it does. But still the mobcap needs to be changed manually. It doesnt make it automatic. Let's say there are 5 player online, I want the mobcap to be set to 25 as for hostile mobs. When there are let's say 20 people online however, I want the mobcap to be set to 15. By changing per-player-mob-spawn to true, it just changes the mobcap to be set to per player not per world.

**Comment by Brokkonaut** [comment]
Yes, plugins can do that. See here: https://papermc.io/javadocs/paper/1.15/org/bukkit/World.html#setMonsterSpawnLimit-int-

**Comment by kickash32** [comment]
mob cap already linearly scales with players, additionally it does not affect mob spawners.

**Comment by electronicboy** [comment]
as already noted, you'd need a plugin; Stuff like this is a rabbit hole of feature/behavioral requests which don't fit into our goals here.

**Comment by kalleswe** [comment]
That's kinda noob answer though. Just fix it would have been better.

**Comment by NBS-Paste** [comment]
> Yes, plugins can do that. See here: https://papermc.io/javadocs/paper/1.15/org/bukkit/World.html#setMonsterSpawnLimit-int-

How do I download this plugin?
Or how do I apply this to my bukkit.yml 
https://paper.readthedocs.io/en/latest/server/configuration.html#per-player-mob-spawns
