### ISSUE TITLE
massive lag spikes

### ISSUE THREAD

**Issue by mythiccal** [PaperMC/Paper#3614]
### Link/paste of stack trace
https://pastebin.com/aSTbhRGp
    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
https://prnt.sc/t5wxjz
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
https://prnt.sc/t5wxnu  - I was trading with these villagers, once I trade with them and exit the trade menu it causes a massive lag spike
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
https://prnt.sc/t5wxx6  - we are using build 231 because it has the vanilla villager behaviour (searching for workstations and beds) which fixed our previous villager issues.

**Comment by mythiccal** [comment]
didn't notice that top bit...

**Comment by electronicboy** [comment]
#2312
