### ISSUE TITLE
when a dead player joins death message is broadcasted

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3617]
### What behaviour is expected:
___What you expected to see___
No death message in chat

### What behaviour is observed:
___What you actually saw___
Death message printed in chat before join message (https://imgur.com/a/1xuuOF9)

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Die, log out while still dead, log in

**Comment by BomBardyGamer** [comment]
Unable to reproduce on the latest Paper 1.16.1 build, could you please give us more detail about what build version you're using?
The build version can be identified by typing /version, which should look something like git-Paper-"build version".

Also, let us know if this is still an ongoing issue or if it has been patched in the latest build.

**Comment by Chew** [comment]
User deleted account and never responded, sadly. No other reports of this occurred, template was never filled out so we don't know if this is a plugin issue, etc. If you do experience this on a supported version (any on https://papermc.io/downloads), feel free to open a new issue, _completely_ filling out the template. Thank you (whoever you were) for the report!
