### ISSUE TITLE
Q: How long will the cartographer bug last?

### ISSUE THREAD

**Issue by karlovm** [PaperMC/Paper#3619]
I know the problem of the unresponsive server is already known, but it has been going on since November 2019. My server is running on version Paper 1.15.2 and without plug-ins and a standard map, the server stops responding. This is very sad and I would like to know how soon this problem will be solved, because as I understand it pursues by all servers versions 1.14 and 1.15.

I apologize that the question may be off topic. Sorry for my english/

**Comment by aikar** [comment]
Can you describe what the actual issue is? I don't know what a map editor bug is.

**Comment by karlovm** [comment]
sorry i mean cartographer

**Comment by chickeneer** [comment]
@karlovm Please include any server errors from your logs file, so we can help understand the issue. Thank you.

**Comment by jere62smi** [comment]
I have exactly the same problem but unfortunately I was told that it came from me when not ...
To summarize the problem, when a player trades with a villager, when loading new trade, it crashes the server.

**Comment by chickeneer** [comment]
Is this the same issue as https://github.com/PaperMC/Paper/issues/3531
If so, leave extra information on that ticket. Although it appears the cause is well established what the cause is.

**Comment by karlovm** [comment]
It isn't a problem report. You already have many issues of this bug. I ask for fix and try to know any information about progress because it is very bad bug.

**Comment by kickash32** [comment]
might be fixed in 1.16, try testing in vanilla or spigot

**Comment by chickeneer** [comment]
> It isn't a problem report. You already have many issues of this bug. I ask for fix and try to know any information about progress because it is very bad bug.

This isn't really a Q&A section (notice the section is called issues). This seems like a good question to inquire on the original issue. Or inquire on Discord.

**Comment by karlovm** [comment]
It is vannila and spigot bug too

**Comment by karlovm** [comment]
Or only spigot i didnt tested vanilla

**Comment by electronicboy** [comment]
duplicate of #2312 
General gist of, outside of some revolutionary take on it, we've done all we can; Mojang is just doing stupidly large lookups, and our only "further" step would be to reduce that, which creates its own set of hell, and doesn't really fix the underlying issue.

**Comment by Toffikk** [comment]
They have fixed this in 20w17a snapshot - this is what they said :)

**Comment by electronicboy** [comment]
"fixed" is subjective, they improved it, they didn't solve the underlying issue
