### ISSUE TITLE
Cannot open custom merchant inventory without a villager.

### ISSUE THREAD

**Issue by Favorlock** [PaperMC/Paper#362]
# Suggestion

I was looking over the craftbukkit code and noticed that openInventory in CraftHumanEntity does not account for a custom merchant inventory. Would really love to see this added in.

**Comment by Favorlock** [comment]
I would also like to note that anvils created via Bukkit.createInventory do not appear to work. The result slot isn't working properly from what I can tell.

**Comment by josephworks** [comment]
this is fixed in citizens2

**Comment by aikar** [comment]
see for more discussion on this nature of adding support for more inventory types: https://github.com/PaperMC/Paper/issues/951

This is best left for upstream to resolve, but unlikely to do so. All of this code binds to world state.
