### ISSUE TITLE
Components for ItemMeta 

### ISSUE THREAD

**Issue by JRoy** [PaperMC/Paper#3621]
component methods for legacy text in ItemMeta for *RGB* possibly use allow for legacy § hack ill do this

**Comment by JRoy** [comment]
am stupid, mini did it.

**Comment by Momonche** [comment]
You're not stupid, love <3

**Comment by mdcfe** [comment]
Yes he is

**Comment by kennytv** [comment]
Yes he is

**Comment by MiniDigger** [comment]
I mean, whats the chance of me actually finishing that? 🤔 😂 

(https://github.com/PaperMC/Paper/pull/3513)
