### ISSUE TITLE
Unknown Server Crashes

### ISSUE THREAD

**Issue by Tobvl** [PaperMC/Paper#3623]
### Link/paste of stack trace

https://pastebin.com/fkfrTJpz

### Plugin list:
LuckPerms, FastAsyncWorldEdit, VoidGenerator, PlaceholderAPI, CustomJoinMessages, ViaVersion, CraftingStore, CustomJoinItems, JPremium, Vault, Multiverse-Core, ProtocolLib, DeluxeChat, WorldEdit, Images, ChestCommands, QuickBoard, HolographicDisplays, CMI, WorldGuard, BungeePortals, BungeeTabListPlus, CMIPaperLib

### Actions to reproduce (if known):
This started to happen some days ago, while for a long time i had never had this errors...
I've never experienced this PaperSpigot Watchdog Thread Error in my life, it's new for me.
Just start the server and when passed some time (not more than 5 minutes) it shows this error and in all my servers too...
Thanks for your help, my network is in your hands!

### Paper build number:
This server is running CraftBukkit version git-TacoSpigot-"95870a93" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Comment by untuned** [comment]
this isn't tacospigot, we can't support you

**Comment by aikar** [comment]
we do not support taco or 1.8.8. nor does the author. update to modern mc for support or you will need to find a different fork who does support the project.
