### ISSUE TITLE
Piglins are extremely laggy (ver/1.16 branch)

### ISSUE THREAD

**Issue by ishland** [PaperMC/Paper#3629]
###  Timings or Profile link:
https://timings.aikar.co/?id=f0a0858ce2434dc1ad4e8f07cce459bc

### Description of issue:
Piglins are extremely laggy

### Plugin list:
Plugins (13): JukeBox, Multiverse-Core, NoteBlockAPI, PlaceholderAPI, PluginManager*, ProtocolLib, QQMinecraft*, ServerMSPT, TitleManager*, UltimateTNT, Vault, ViaBackwards, ViaVersion

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml: https://pastebin.com/Ta08RLDk
spigot.yml: https://pastebin.com/5bt3Pfes
paper.yml: https://pastebin.com/m1fjUrK9
server.properties: https://pastebin.com/LudF0msU

### Other helpful links
Nope

### Paper build number:
```
This server is running Paper version git-Paper-"c3640b1d" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
```

**Comment by zachbr** [comment]
Nope

**Comment by Protonull** [comment]
Don't worry it about, stuff like this is to be expected, and people are working hard to get Paper 1.16 stable.
