### ISSUE TITLE
Players cant pick up items from ground

### ISSUE THREAD

**Issue by HyplexMC** [PaperMC/Paper#3631]
### What behaviour is expected: 
Players should be able to pick up items on ground

### What behaviour is observed:
Players cant pick up items when on ground

### Steps/models to reproduce:
Cant reproduce 

### Plugin list:
Plugins (32): AntiCreeper*, AntiXrayHeuristics, Clans, ClansChatAddon, ClansChestAddon, ClansKillAddon, ClansRenameAddon, ClansShowAddon, CMI, CMIPaperLib, CoreProtect, DeluxeMenus, DiscordSRV, DiscordSRV-Staff-Chat*, GriefPrevention, Holograms, LuckPerms, Multiverse-Core, PlaceholderAPI, PlayerReport, PluginLibrary, ProtocolLib, Quests, Rankup, ServerListPlus*, SimpleVoteListener*, SpecializedCrates, Statz, Vault, Votifier, WorldEdit, WorldGuard

### Paper build number:
233

### Anything else:
Hi multiple of my players have been reporting to me that occasionally they cant pick up items from the ground almost as if there was lag but we dont have lag on our server, sometimes it last for a while and sometimes it just fixes it self but it seems that when i restart the server it fixes it but it keeps happening again. I haven't done any changes to the server that could possibly trigger this, no adding plugins or updating them or changing the files. The fact that when i restart the server tells me that it cant be a issue with a plugin causing any issues and its definitely not lag cause it has happened with only 1 person online before. I cant re-create this issue. i asked the player(s) if they got any errors in chat when trying to pick the items up and they said there where none and i also got none in the console. I dont know what to do about this but its a big issue cause i am not always available to restart the server when this happens. I've done some research online but all the same issue(s) are form years back. I dont know what to do so if anyone has any idea of why this is happening that would be great.

**Comment by HyplexMC** [comment]
I am also having another issue when players try to pick block they are kicked from the server and its telling them they are being kicked for hacking. Should i make a new issue for this?

**Comment by zachbr** [comment]
You should start by updating, you're nearly 140 builds out of date.
Also, if there's no easy reproduction steps than this may take a while, assuming it's not a plugin anyway.

**Comment by HyplexMC** [comment]
OK sorry i didnt relize my host usually updates it for me sorry one sec

**Comment by HyplexMC** [comment]
> You should start by updating, you're nearly 140 builds out of date.
> Also, if there's no easy reproduction steps than this may take a while, assuming it's not a plugin anyway.

Ok sorry it seems one of my developers changed one of the settings in the console and removed the setting off of default so it didnt auto update the paper file and dropped us down loads of builds
