### ISSUE TITLE
Players Randomly Unable to Pickup Items

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3632]
### What behaviour is expected:
Players can pick up items

### What behaviour is observed:
Players randomly are unable to pickup any tile entities

### Steps/models to reproduce:
There are almost no ways to reproduce, this issue occurs randomly.

### Plugin list:
AdvancedPortals, AntiXrayHeuristics, BanManager, BlockParticles, BottledExp, BungeeGuard, ChestShop, Citizens, ClaimSender, CMI, CMIEInjector, CMIPaperLib, CoreProtect, CustomCrafting, DeadChest, Denizen, Dependizen, dtlTraders, Duels, EnjinMinecraftPlugin, FogusCore, GoldenEnchants, HeadDatabase, HolographicDisplays, ImageOnMap, ItemTrackers, Jobs, LibsDisguises, LuckPerms, LWC, LWCTrust, mcMMO, MiniaturePets, Multiverse-Core, MythicMobs, NewGods, OreRegenerator, PlaceholderAPI, PlayerParticles, PlayerWarps, Portabeacon, ProtocolLib, Rankup, TAB, Towny, TownyFlight, TownyNameUpdater, UltraCustomizer, UltraCustomizerPlus, Vault, VentureChat, Votifier, VotingPlugin, VoxelSniper, WitherAC, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
Build #372

### Anything else:
The temporary fixes I have found are either switching the players gamemode or teleporting them somewhere. I also went back to 368 before a couple upstream updates and no one is having the issue anymore. The people who I have talked to who have also had this issue are in a discord for CMI making me think that that is involved but according to them other random people are complaining about this issue in spigot discord and such.

**Comment by Firjens** [comment]
Have you tried it without running any plugins? Can it be reproduced without them?

**Comment by austin4195** [comment]
Can confirm players have been reporting this issue, have not tested it without plugins however nothing is showing as an error and incident is random.

**Comment by BiGUNMAN** [comment]
We've had this issue as well.

**Comment by johnsoncui02** [comment]
I have the same issue as well. on 1.15.2 build 372

**Comment by ghost** [comment]
I have not tried without plugins,  but many other people I have talked to who have had the issue also have had way different setups for plugins than I have, and I also haven't had the issue since I went back a couple versions on paper so I think it is a paper issue.

**Comment by Fabrimat** [comment]
Same here, I have CMI too

EDIT: In CMI 8.0.7.1 there is this message
![immagine](https://user-images.githubusercontent.com/13642582/85943846-fb123800-b932-11ea-8739-65ff5cca43d5.png)
Maybe it has been fixed, gonna test

**Comment by Baterka** [comment]
I had same problem in newest Paper build.
It seems fine in #372 so I am not updating for now.

**Comment by Fabrimat** [comment]
After updading CMI the problem seems to be fixed.
