### ISSUE TITLE
TPS DROP WITH 1.15

### ISSUE THREAD

**Issue by JavyMC123** [PaperMC/Paper#3633]
Timings:
https://timings.aikar.co/?id=024f9ce7117146d0968b91f76136ff4d
https://timings.aikar.co/?id=40d1c50f02944ee393caec630176f52f

Issue:
The TPS drop to 5, 4TPS with 60 players.

Plugin list:
https://gyazo.com/3ff0797db1615785ed479e2a976699ac

BUKKIT: https://pastebin.com/5ycLWs2V
SPIGOT: https://pastebin.com/36MeynnZ
PAPER: https://pastebin.com/y1ktawpY

 Paper build number:
Paper version git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Malfrador** [comment]
Tbh 60 players with less than 6 GB of RAM is pretty impressive. Im surprised it works at all.
This is not really the place for lag help tho, it probably is not a bug with that many players. Thats just the capacity of your server.
I recommend asking in the Paper discord or somewhere else for help with your timings. It also might be useful to take longer timings than just a few minutes - longer timings are more accurate and helpful. 

One thing I notice tho: Plugins like UltimateStacker do more harm then good. The stacking task is very intensive (18%+ of your tick), which probably is more than just letting the mobs be.

**Comment by electronicboy** [comment]
for support with timings, please use the discord/irc/forums
