### ISSUE TITLE
Offline player's skull causes lag

### ISSUE THREAD

**Issue by Kismalax** [PaperMC/Paper#3637]
### What behaviour is expected:
Don't have performance issue when moving skulls in the inventory.

### What behaviour is observed:
Got "The server has not responded for xx seconds!" message when moving non-existent (=player name is not a valid mojang profile name) player's skull in the inventory.

This is the server log I got, while recorded the video: [https://hastebin.com/siwahivohu.md](https://hastebin.com/siwahivohu.md)

### Steps/models to reproduce:
Video: [https://www.youtube.com/watch?v=UHPy3t7xeXc](https://www.youtube.com/watch?v=UHPy3t7xeXc)
The skull name "8sdhfsb63" is not a valid mojang profile name. When I do this with a real profile's skull, it's don't causing any problem.

I run the server in offline mode, so there are many random skull on the server, causing lag many times.

### Plugin list:
Plugins (1): Essentials

### Paper build number:
git-Paper-372 (MC: 1.15.2)

### Anything else:
I used the Paper-350 before 372, don't experienced any issue with.

**Comment by Blamo27** [comment]
Same thing here with Citizens : https://pastebin.com/gStE2smK

Timings on Paper-372 : https://timings.aikar.co/?id=d3fa632163e74895ad9f476037f0850a
Timings on Paper-343 : https://timings.aikar.co/?id=f8f840bc18874de98426cdaa063403ec

It was working fine on Paper-343

**Comment by Momonche** [comment]
Can you put this commit on 1.15.2 please ?

**Comment by electronicboy** [comment]
That was commited on 1.15.2

**Comment by Momonche** [comment]
Ow, I'm blind so, thanks
