### ISSUE TITLE
Mobs using too much ticks for AI outside of activation range?

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#364]
It seems like even with activation range set to 1, having just a few too many zombies and skeletons use way too much ticks in timings even if they're all standing completely still and not moving at all

The only mob altering plugin I had was one that limited total mobs inside a chunk to 8, and activation range was set to 2. With 150 players that's a possible max of 1200 activated mobs, but most likely not. Even with 1200 activated mobs it shouldn't lag, so there is something weird going on here or am I missing something?

Could be optimized somehow?

Build 813

![mobs](https://cloud.githubusercontent.com/assets/18597710/16715155/d3f5bcc2-46d8-11e6-9ec8-13aa032b2aa5.png)

**Comment by MrCaedes** [comment]
Also having this issue - We only have 35 players online, yet mobs are taking up an inordinate amount of the tick. Our timings, on our server, reflect those given here - With Zombies, Creepers and Iron Golems taking up around 20% of the tick each. 

We only started to experience this when we updated on the 7th July to the latest version of PaperSpigot available.

**Comment by aikar** [comment]
Ultimately there's nothing to "change" here. They are as optimized as it can get.

You should expand the timings on the entities to see if its a plugin thats causing them to cost more (please include links to timings instead of pictures)
