### ISSUE TITLE
Inventory Click event has different behaviour than previous versions

### ISSUE THREAD

**Issue by MrIvanPlays** [PaperMC/Paper#3643]
Last info available on my other post

**Comment by aikar** [comment]
I am so confused on what you are trying to report. Your GIF does not show you even trying to get an item out?

I just see you search for e and close it.

Can't reproduce any issue with it.

**Comment by MrIvanPlays** [comment]
> I am so confused on what you are trying to report. Your GIF does not show you even trying to get an item out?
> 
> I just see you search for e and close it.
> 
> Can't reproduce any issue with it.

I'm clicking. Idk if its something with my minecraft installation or its just windows/java being stupid. Ima give you another gif in just a sec.

**Comment by aikar** [comment]
Ultimately, Creative is 100% controlled by the client. Server has no control over this. If you're having an issue, you got to report it to Mojang.

**Comment by MrIvanPlays** [comment]
I switched to video in order for you to see that I'm actually clicking https://streamable.com/su7ns0


> Ultimately, Creative is 100% controlled by the client. Server has no control over this. If you're having an issue, you got to report it to Mojang.

Um it also didn't work for my skin menu. Source for the skin menu is available [here](https://github.com/MrIvanPlays/PagedInventoryAPI) if you think it's something wrong with my skin menu code.

**Comment by electronicboy** [comment]
Your client is literally showing it being picked up, can you replicate it without that plugin?

**Comment by MrIvanPlays** [comment]
> Your client is literally showing it being picked up, can you replicate it without that plugin?

ehmmm am I blind or sth? it is showing it but it doesn't stay on my cursor. 
sure ill remove the plugins

**Comment by MrIvanPlays** [comment]
https://streamable.com/hx2q2w

**Comment by jcoppock** [comment]
As @aikar mentioned, clicking within the Creative menu, and not within the player's inventory or hotbar, does not even fire an event on the server.

**Comment by MrIvanPlays** [comment]
Fine creative problem will be reported to mojang, but I did some research about my skin menu and fsr the behaviour of InventoryClickEvent has changed for 1.16

```java
  @EventHandler
  public void onJoin(PlayerJoinEvent event) {
    Player player = event.getPlayer();
    Inventory inventory = Bukkit.createInventory(null, InventoryType.CHEST, "I was testing");
    ItemStack item = new ItemStack(Material.PISTON);
    ItemMeta meta = item.getItemMeta();
    meta.setDisplayName("Mama's squeeze");
    item.setItemMeta(meta);
    inventory.addItem(item);
    player.openInventory(inventory);
  }

  @EventHandler
  public void onClick(InventoryClickEvent event) {
    Player player = (Player) event.getWhoClicked();
    if (event.getClickedInventory() == null) {
      return;
    }
    if (player.getOpenInventory().getTitle().equalsIgnoreCase("I was testing")) {
      event.setCancelled(true);
      if (event.getCurrentItem().getItemMeta().getDisplayName().equalsIgnoreCase("Mama's squeeze")) {
        player.sendMessage("I will hug you.");
      }
    }
  }
```
I didn't get a message when clicking the item (believe me, I AM clicking)
![image](https://img.mrivanplays.com/a6xqgOO2ub.gif)

however, dragging the item instead of clicking it then starts working: 
![other image](https://img.mrivanplays.com/ICc9iD06Yq.gif) 
and with dragging I get a NPE prob cuz im moving the item on an empty slot.

**Comment by MrIvanPlays** [comment]
Apparently after some googling this is just touchscreen mode and fsr I had that enabled.
