### ISSUE TITLE
Server Crash when Horse/lambda are leashed

### ISSUE THREAD

**Issue by C0an** [PaperMC/Paper#3644]
### Link/paste of stack trace
https://transfer.sh/RJny6/crash.txt

### Plugin list:
WorldEdit, FamilyGuyFunnyMoments

### Actions to reproduce (if known):
When using a leash on a Horse/lambda the server will instantly crash.

### Paper build number:
git-Paper-387571da (MC: 1.16.1)

**Comment by electronicboy** [comment]
Update, that's not even a release build...

**Comment by aikar** [comment]
Fixed in latest build (forgot github won't close since not master :( )
