### ISSUE TITLE
whitelist broken

### ISSUE THREAD

**Issue by palyons** [PaperMC/Paper#3645]
### What behaviour is expected:
Whitelist working

### What behaviour is observed:
Whitelist not functioning

### Steps/models to reproduce:
Deleted whitelist.json
/whitelist off
/whitelist on
Able to login, despite not being in the whitelist.json file
/whitelist reload
You are not whitelisted on this server!
Resumes normal broken functionality of being able to login again.

### Plugin list:
None

### Paper build number:
git-Paper-"d82de981" (MC: 1.16.1)

**Comment by electronicboy** [comment]
are you opped?

**Comment by palyons** [comment]
No I am not.

**Comment by jcoppock** [comment]
Removing operator status while in-game without being in the whitelist kicks the player, and then the player can just join back again.  '/whitelist reload' kicks all non-whitelisted players, and then they can join back, whether they have operator status or not.

**Comment by palyons** [comment]
> Removing operator status while in-game without being in the whitelist kicks the player, and then the player can just join back again. '/whitelist reload' kicks all non-whitelisted players, and then they can join back, whether they have operator status or not.

I was never opped...

**Comment by electronicboy** [comment]
I see the issue

**Comment by palyons** [comment]
> I see the issue

is it doing it for you too?

**Comment by jcoppock** [comment]
> > Removing operator status while in-game without being in the whitelist kicks the player, and then the player can just join back again. '/whitelist reload' kicks all non-whitelisted players, and then they can join back, whether they have operator status or not.
> 
> I was never opped...

I didn't say you were. I was just clarifying that operator status has no effect, it seems.

**Comment by MrIvanPlays** [comment]
Can reproduce

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/commit/bf4b541513c41f48d7eb54ec939c8c4d812155f6

**Comment by Silent-Hunter** [comment]
I am having this exact issue with the latest Paper 296. Regression, possibly?

**Comment by Machine-Maker** [comment]
I'm guessing to test it, you turned on the whitelist with no one on it, and tried to log in, and you were able to get it despite not being on the list.

If that is the case, try it again and make sure your character isn't opped. Operators bypass the whitelist.

**Comment by Silent-Hunter** [comment]
Okay yes, sorry. I tried that on 288 and it still let me on but it looks like I forgot to try that in 296.
