### ISSUE TITLE
Whitelist Not Enforced

### ISSUE THREAD

**Issue by TheRealVincentVanGogh** [PaperMC/Paper#3646]
### What behaviour is expected:
___Only whitelisted players may join the server___

### What behaviour is observed:
___Any player may join the server___

### Steps/models to reproduce:

1. Setup Server + Whitelist
2. Ensure server.properties whitelist settings and enforcement are all true.
3. Connect to the server using any account not allowed through the whitelist.
4. The connection succeeds.

### Plugin list:
N/A (NONE)

### Paper build number:
Paper-4 1.16.1

**Comment by jcoppock** [comment]
#3645

**Comment by Chew** [comment]
Update your Paper
