### ISSUE TITLE
Server never stops when eula=false

### ISSUE THREAD

**Issue by clrxbl** [PaperMC/Paper#3647]
### What behaviour is expected:
Server should stop

### What behaviour is observed:
![image](https://user-images.githubusercontent.com/28601081/85944352-63164d80-b936-11ea-97e3-53186c0eee08.png)
It never stops after the last log message unlike in previous versions e.g. 1.15.2

### Steps/models to reproduce:
Start a server with eula=false in eula.txt

### Plugin list:
Irrelevant

### Paper build number:
1.16.1 #8

### Anything else:
Has been there since the first usable ver/1.16 commit, reported a few times on Discord but still seems to be an issue.

**Comment by 0-x-2-2** [comment]
Running `jstack [pid]` will probably show the cause (probably non-daemon thread running)

**Comment by danny6167** [comment]
Means nothing to me, but see attached.
[jstack.txt](https://github.com/PaperMC/Paper/files/4842310/jstack.txt)

Note, it's also *not* reproducible in vanilla or git-Spigot-ad703da-d77f4d9

**Comment by electronicboy** [comment]
known issue, it's due to one of our threading changes

**Comment by mtoensing** [comment]
> known issue, it's due to one of our threading changes

So this is expected behaviour or will this be addressed in a future release?

**Comment by A248** [comment]
Will be addressed, known issues are not expected behaviour:
> known issue

**Comment by mtoensing** [comment]
This problem should be fixed in 1.16.1#30 https://github.com/PaperMC/Paper/commit/4fd0d54ee78f49a79263c9a0c5154aa4ec4fd6b6 but still occurs in my automatic testing. Not fixed. =/

**Comment by mtoensing** [comment]
Sorry but: This problem should be fixed in 1.16.1#30 4fd0d54 but still occurs in my automatic testing. **Not fixed. =/** @electronicboy

**Comment by electronicboy** [comment]
Fixed in the latest build
