### ISSUE TITLE
Building 1.12.2 version

### ISSUE THREAD

**Issue by grasscrash4384** [PaperMC/Paper#3648]
Hello
I have an issue here, I downloaded the /ver/1.12.2 branch on my computer and tried to compile it, but instead of compiling 1.12.2 version it downloaded 1.15.2 and compiled 1.15.2
How can I change it to make it compile 1.12.2 version?

**Comment by electronicboy** [comment]
1.12.2 is not supported...
Checkout the correct branch and then run the scripts
