### ISSUE TITLE
Console spam - ERROR

### ISSUE THREAD

**Issue by Meattekn** [PaperMC/Paper#3649]
Paper-6 1.16.1
Crash in spamming CONSOLE.

`com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[patched_1.16.1.jar:git-Paper-6]`

What the happen? I am installed plugin ANTI-SPAM CONSOLE.

**Comment by electronicboy** [comment]
You missed the entire template... and the full exception...

**Comment by Meattekn** [comment]
> You missed the entire template... and the full exception...

[latest.log](https://github.com/PaperMC/Paper/files/4842078/latest.log)
![image](https://user-images.githubusercontent.com/67541601/85945036-a925de00-b943-11ea-8b7c-94201127c8d6.png)

**Comment by electronicboy** [comment]
`[12:50:57] [Server thread/ERROR]: Could not pass event PlayerBedEnterEvent to CMI v8.7.0.0`
You'd need to speak to CMI
Also, the stack trace is cut off, there is a JVM flag to tell it to dump more lines from what I recall
