### ISSUE TITLE
Entities getting glitched up or removed when too many of them

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#365]
There is a weird bug that occurs when a player breaks for example a doublechest full of items, they seem to become glitched up as if removed from the game, and some items might be removed too that were in the chest. This also affects items in item frames, some items disappear at random inside frames once there are too many entities nearby

When players break a double chest full of items they can't use chat anymore, and chunks don't load and they get disconnected if they move away from the area
http://i.imgur.com/YXrarAT.png

Build 813

No plugins that limit or touch entities in any way

**Comment by zachbr** [comment]
Cannot reproduce, please provide the entirety of your plugin list, regardless of whether they appear to have any effect.
