### ISSUE TITLE
No exit code when server is run for the first time on 1.16.1

### ISSUE THREAD

**Issue by nicobonik** [PaperMC/Paper#3652]
I am trying to create a Docker container for PaperMC 1.16.1, but I'm facing one problem -- 

when I run the jar for the first time and get the `You need to agree to the EULA in order to run the server. Go to eula.txt for more info.` line, instead of the process exiting, it hangs indefinitely with no exit. Is this intended or is there a missing `System.exit()` call somewhere?

**Comment by electronicboy** [comment]
Duplicate of #3647
