### ISSUE TITLE
Weather commands being ignored

### ISSUE THREAD

**Issue by drazisil** [PaperMC/Paper#3653]
### What behaviour is expected:
Ability to clear the weather

### What behaviour is observed:
It's raining and won't stop

### Steps/models to reproduce:
Using build 8 of 1.16 paper 

### Plugin list:
[Sun, 28. Jun 2020 13:49:17 CEST INFO] Plugins (46): AdvancedTeleport, ArmorStandEditor, AsyncWorldEdit, AsyncWorldEditBossBar, AutoRestart, BanManager, BlocksHub, BuycraftX, ChestCleaner, CommandHook, Destinations, DiscordSRV, Elevators, Flight, Graves, Harbor, HeadDatabase*, HeadsPlus, LogBlock, LuckPerms, LWC, MailIt, MessageAnnouncer, ModReq*, MultitoolPlus, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, Nicky*, PerWorldInventory, PlaceholderAPI, PlayerControlPlus, Portalcontrol, ProtocolLib, Sickle, StaffFacilities*, Superbook, TAB, Vault, VentureChat, Villagerevolution, VoxelSniper, WG-GUI, WorldBorder, WorldEdit, WorldGuard

### Paper build number:
This server is running Paper version git-Paper-8 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
I have tried disabling weather cycle game rule. I have tried setting the __global__region weather lock to clear. Nothing stops the rain.

**Comment by electronicboy** [comment]
replicate without plugins, this works perfectly fine here

**Comment by ida2007** [comment]
Same problem - using build 3.
Plugins list: 
 AntiWither, AuctionHouse, Blacksmith, BuycraftX, ChatColor2, Citizens, CitizensCMD, ColoredAnvils, ColoredSigns, DWG_OasisDesert, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, FogusCore, GoldenEnchants, LuckPerms, Multiverse-Core, MysqlEcoBridge*, NoPlugins, PlaceholderAPI, PlotSquared, RHSignieren, ServerRestorer, ShopChest, SimplePortals, StackMob, StaticsServerEnhancment, TAB, TradeSystem, Vault, Votifier, VotingPlugin, WitherAC, WorldEdit, WorldGuard
