### ISSUE TITLE
1.16 Server keeps running if the eula is not accepted 

### ISSUE THREAD

**Issue by mtoensing** [PaperMC/Paper#3656]
### What behaviour is expected:
 I obtain the patched jar when I start the server without accepting the eula once. That worked in 1.15.x because after the message "You need to agree to the EULA in order to run the server. Go to eula.txt for more info." the server stopped. 

### What behaviour is observed:
Now it keeps running. Is there a parameter to start paper so that the jar is patched it just stops after that? 

### Steps/models to reproduce:
Just run Paper without the eula flag: 
/usr/local/openjdk-11/bin/java -jar /opt/minecraft/paperclip.jar; exit 0

### Plugin list:
none.

### Paper build number:
1.16.1#10

### Anything else:
You a great! =)

**Comment by wizjany** [comment]
#3647 pls use search
