### ISSUE TITLE
Unable to build PaperMC (Compile jar from source) on Centos 8

### ISSUE THREAD

**Issue by tackleza** [PaperMC/Paper#3657]
### What behaviour is expected:
Able to build PaperMC on Centos 8

### What behaviour is observed:
It's failed for no reason. It's just said "Failed to build Paper"
Other Linux is able to build PaperMC (Tested on Centos 7, Linux Mint 19)
But Centos 8 is unable to build even fresh install Centos 8

### Steps/models to reproduce:
Same step as readme said on (https://github.com/PaperMC/Paper/tree/ver/1.16#how-to-compiling-jar-from-source)
I clone this repo then run "./paper jar"
and failed after step "Pointing to [PATH]/work/Minecraft/current to [VERSION]"

### Paper branch:
master, ver/1.16 branch

### Anything else:
I love open source. And I want to learn something news and testing Development Build and my Jenkins server which is installed on Centos 8. And I think build script is not compatible to Centos 8 in someway
Forums thread here: https://papermc.io/forums/t/jenkins-unable-to-compiling-paper-jar-from-source/3895
Build full log here (Jenkins): https://pastebin.com/daX3MZ6Y
JDK Version: openjdk version "1.8.0_252"

**Comment by wizjany** [comment]
you were literally just told not to report this. it's not a paper issue, you're just missing some utils on your system (cat said probably patch).

**Comment by electronicboy** [comment]
This is not the place for support with build issues

**Comment by tackleza** [comment]
Confirmed. Centos 8 is missing `patch` command. It's didn't pre-install on Centos 8 (Unlikely Centos 7)
Now I'm able to build PaperMC.

It's should said `patch: command not found...` or something like that in the console. But it didn't

### Solution
This only a problem on Centos 8, just install `patch` by `yum install patch`

**Thank you**
_And sorry I didn't see you guys reply me on Discord :(_

**You can closed this issues...**
