### ISSUE TITLE
GenerateMap Error

### ISSUE THREAD

**Issue by Saharo4eks** [PaperMC/Paper#3658]
Information:
System: Windows 10
Processor: Ryzen5 1400
RAM: 8GB

Paper#10 1.16.1

I started generate map (plugin ChunkMaster) and recieve this error: https://pastebin.com/piNNvgvM
I contacted the developer ChunkMaster, he sent me here.

**Comment by HexedHero** [comment]
Try WorldBorder instead.

**Comment by electronicboy** [comment]
Nothing to do with the plugin, generation is firing events, which is off the main thread

**Comment by Saharo4eks** [comment]
> Try WorldBorder instead.
No, thanks. I don't have a month to generate the map.

**Comment by Trivernis** [comment]
@Saharo4eks Are you able to change the issue title? If so I'd suggest changing it to something like "[Crash] Async Chunks error: Server fails to schedule load callback" to be more descriptive.

**Comment by aikar** [comment]
this one is resolved already.
