### ISSUE TITLE
Ore obfuscation for 1.16 nether

### ISSUE THREAD

**Issue by radiant-ai** [PaperMC/Paper#3659]
**Is your feature request related to a problem? Please describe.**
I like the obfuscation of ores in Paper in upper world, however 1.16 is out and there is a need to implement ore obfuscation in the nether.

**Describe the solution you'd like**
Add ore obfuscation in nether chunks. Replace all hidden netherrack **from levels 8 to 22** with quartz, ancient debris and lava (must be ok?) blocks and send that to client.

**Describe alternatives you've considered**
No real alternatives except for asking plugin developers (which should not be discussed here)

**Comment by wizjany** [comment]
it works fine, just set up the antixray settings for your nether world.

**Comment by radiant-ai** [comment]
> it works fine, just set up the antixray settings for your nether world.

There is no separate config section for the nether world, I wish I could set different _max-chunk-section-index_ which should be 2 for the ancient debris. And the replacement options work globally, while I want nether-specific replacements.

**Comment by electronicboy** [comment]
It's a per-world config, just define those options for the nether world

**Comment by stonar96** [comment]
https://www.spigotmc.org/attachments/per-world-guide-pdf.444348/
