### ISSUE TITLE
EffectLib + BetonQuest generate error on Paper upon reload

### ISSUE THREAD

**Issue by PsychoLynx** [PaperMC/Paper#366]
### What behaviour is expected:

BetonQuest reloads normally with EffectLib installed (as it does in the latest Spigot with the same configurations, I have tested)
### What behaviour is observed:

Error is printed in the console, BetonQuest config is not reloaded.
### Plugin list:

BetonQuest-dev build 185
EffectLib-5.0
citizens-2.0.19-SNAPSHOT build 1379
### Steps/models to reproduce:

Use /q reload ingame or in the console
### Paper build number:

git-Paper-815 (MC: 1.10.2) 
# Crash, Stacktrace

http://pastebin.com/1cebykSx

**Comment by zachbr** [comment]
Cannot reproduce on latest versions of Spigot or Paper.

**Comment by PsychoLynx** [comment]
Can confirm, not primarily caused by Paper after all, but a malformation in my BetonQuest's config.yml which somehow interacts with Paper in a way it does not with regular Spigot. 

I am so terribly sorry for not testing more thoroughly. Thank you for your amazing work on Paper.
