### ISSUE TITLE
Player#setPlayerWeather(WeatherType#CLEAR) causes rain to start pouring down

### ISSUE THREAD

**Issue by Blazzike** [PaperMC/Paper#3661]
### What behaviour is expected:
Player#setPlayerWeather(WeatherType#CLEAR) to display clear weather on the client.

### What behaviour is observed:
Rain is displayed on the client.

### Steps/models to reproduce:
Call Player#setPlayerWeather(WeatherType#CLEAR) on a player instance.

### Plugin list:
N/A

### Paper build number:
git-Paper-10 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by wizjany** [comment]
upstream issue, fix already PRd. will be pulled once md5 gets to it and then paper pulls upstream.

**Comment by electronicboy** [comment]
Fixed in build 21 I think it was
