### ISSUE TITLE
Spectator Mode Entity Collision

### ISSUE THREAD

**Issue by palyons** [PaperMC/Paper#3669]
### What behaviour is expected:
Entity to phase through my game avatar.

### What behaviour is observed:
When in Spectator Mode observing a farm in my home, a minecart (hopper cart) collided with me, when it should have kept moving on the rails.

### Steps/models to reproduce:
Go Into Spectator Mode, place minecart, hopper cart, etc on powered rails, the cart will stop moving.

### Plugin list:
None

**Comment by aeonlamb** [comment]
This is a vanilla bug: https://bugs.mojang.com/browse/MC-153230

**Comment by Proximyst** [comment]
Fixed in vanilla in 1.16.2.
