### ISSUE TITLE
Skulls turning into steve heads after some time post placement.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#367]
Paper dev 815

Newly placed custom (skinned) heads are turning into steve skin after some time and relogging with custom skulls in your inventory turn into steve head. Did Spigot's upstream skull validation changes break something?

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/ca1bb1c44509603ef94285c7c4729b79026ae4cb

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/301db84d3d85f5218f3ec590224071c04140bbe2

For custom skull placement, I have been using this plugin. Worked fine before the validation changes.
https://www.spigotmc.org/resources/head-database-1600-heads-20-off.14280/

**Comment by mibby** [comment]
Another person reported a similar issue with heads losing their custom skin in containers / inventories here.
https://aquifermc.org/threads/custom-texture-head.225/

**Comment by zachbr** [comment]
Hopefully fixed in Builds 818+

**Comment by mibby** [comment]
Thanks. :D I'll let you know otherwise if it is still broken.
