### ISSUE TITLE
Error Generate Map

### ISSUE THREAD

**Issue by Saharo4eks** [PaperMC/Paper#3675]
Hi, a generate my map and recieve this error: https://pastebin.com/7arSgN5M

PaperSpigot#10 1.16.1
Windows 10
Ryzen5 1400, 8GB RAM

**Comment by Chew** [comment]
1) This isn't an error, it's just letting you know.
2) Please fill out template entirely.
3) We're called Paper now.

**Comment by pop4959** [comment]
This was addressed already in #3933. Also, you're using an extremely old version of Paper that isn't supported anymore, so you should update. 😄
