### ISSUE TITLE
Vanilla teams not working 100% correct

### ISSUE THREAD

**Issue by agoniaprivat** [PaperMC/Paper#3676]
### What behaviour is expected:
___What you expected to see___
The Vanilla team colors working on the 1.16.1 build

### What behaviour is observed:
___What you actually saw___
![image](https://user-images.githubusercontent.com/50961682/85959065-50356480-b99a-11ea-9a52-5337121645f6.png)
Green is correct, red is incorrect.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___
![image](https://user-images.githubusercontent.com/50961682/85959680-0cdcf500-b99e-11ea-8a0b-c005f3f960b6.png)

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
Paper-13 1.16.1
### Anything else:
___Anything else you think may help us resolve the problem___
No

**Comment by rm20killer** [comment]
what plugins are you running as if your running as it could be a plugin issue as some plugins override minecraft team system for chat messaging.

**Comment by agoniaprivat** [comment]
> what plugins are you running as if your running as it could be a plugin issue as some plugins override minecraft team system for chat messaging.

Edited the post with the plugins list. No error messages are displayed and I have vanilla teams enabled in config.
Does it work for you?

**Comment by MrIvanPlays** [comment]
> Also, please unban me on papers discord.
> Halvnaken#5585 I was banned for pinging a staff of yours.

Nice try, didn't think of that myself

**Comment by agoniaprivat** [comment]
Tested on latest version. Still not working.

**Comment by agoniaprivat** [comment]
Update:
Somehow on a test server teams are working properly. Just made a new world, with all the same plugins, but a new generated paper config :hmm:

Update 2:
Nevermind. Only the team I was in from spigot would stay the same in chat.

**Comment by TheAshenWolf** [comment]
![image](https://user-images.githubusercontent.com/36227512/86454456-89b1fb00-bd1f-11ea-8418-84a80c31441e.png)
![image](https://user-images.githubusercontent.com/36227512/86454608-c4b42e80-bd1f-11ea-97dd-64c57995eb65.png)
Issue still persists on Paper 44.

The red arrow shows a message sent using /say [msg]
The green one shows just the basic message.

As you can see, plugins are not to blame here, as I am only using the dynmap.

**Comment by MAXOUXAX** [comment]
Any updates guys ?

**Comment by Rtompkins1997** [comment]
Just waiting for this to upgrade

**Comment by EliasRipley** [comment]
Also experiencing this issue. Lots of players asking about this as we are a team based server.

**Comment by kennytv** [comment]
very likely just boils down to CB's handling of chat messages

**Comment by connormcdermid** [comment]
+1, the only thing keeping me from upgrading my server to paper at present

**Comment by kennytv** [comment]
@BillyGalbreath had a fix for that I think, maybe he can yeet that over to Paper

**Comment by BillyGalbreath** [comment]
Fixed in build 130 https://github.com/PaperMC/Paper/commit/58a745eba0beeec4f080256330261c505b8e1a66

**Comment by jackson-57** [comment]
I just updated to the fixed version of Paper, but the colors in chat still aren't working

**Comment by BillyGalbreath** [comment]
Be sure you aren't using a plugin that listens to the sync chat event. All it takes is 1 plugin like that to split the handling logic where these colors are applied

**Comment by jackson-57** [comment]
Possibly DiscordSRV.
