### ISSUE TITLE
Updating The New Economy causes crashes not related to The New Economy but user cache.

### ISSUE THREAD

**Issue by Agaloth** [PaperMC/Paper#3678]
### Link/paste of stack trace

    https://paste.ubuntu.com/p/YtPpNZsJMr/

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here. ___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:

Plugins (122): AdvancedEnchantments, AdvancedHelp, AdvancedMention*, Aliases*, ArmorStandTools, BannerBoard*, Barrels, BetterBowTrails*, BetterEnd, BlockLocker, BottledExp, Brewery, BuycraftX, ChatBrawl, ChatColorGUI*, ChatControl, ChestShop, ChestShop-towny*, ChestTerminal, Citizens, CitizensCMD, ClearLag, CoinFlipper*, ColoredAnvils*, CombatLogX, CommandCooldown*, CoreProtect, CS-CoreLib, CustomCrafting, DeathMessagesPrime, DeluxeChat, DeluxeCommands, DeluxeJoin, DeluxeMenus, DeluxeTags*, DiceFurniture, DiscordSRV, dynmap*, Dynmap-Towny, Elevator, EntityTrackerFixer, Essentials, EssentialsSpawn, ExoticGarden, FastAsyncWorldEdit, FeatherBoard*, FogusCore, FurnitureLib, FurnitureMaker, GameAPI, GodsEye, GoldenCrates, Graves, HeadDatabase*, HolographicDisplays, IALibs, InventoryRollback, ItemsAdder, Jobs, LightAPI*, LimitPillagers, LiteBans*, LitePlaytimeRewards, LiteXpansion, LuckPerms, MarriageMaster, MBanProxyVPN*, mcMMO, MessageAnnouncer, MineableSpawners, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MVdWPlaceholderAPI*, OldCombatMechanics, OpenInv, PacketListenerApi*, PhantomX, PlaceholderAPI, Plan, PlayerVaults, PluginManager, ProtectionLib*, ProtocolLib, Quests, RealisticTreeStay, Referral, RFChairs, ServerListPlus*, ShopGUIPlus, ShopGUIPlusMineableSpawnersBridge, SimplePets, Slimefun, StaffChat*, SuperTrailsPro*, SuperVanish, TAB, TheNewEconomy, TokenManager, TokenShopEditor, Towny, TownyChat, TownyFlight, TownyNameUpdater, UltimateTimber, Vault, Vehicles, ViaBackwards, ViaVersion, VillagerOptimiser, VoteParty, Votifier, Voting*, VotingPlugin, Wild, WildStacker, WolfyUtilities, WorldBorder*, WorldEdit, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV2*

### Actions to reproduce (if known):
___Install the newest version of The New Economy with all these plugins and run the server (it will crash when players are joining for a user cache error)___

### Paper build number:
___Paper 370.___

**Comment by ghost** [comment]
122 plugins

**Comment by Chew** [comment]
As the stack trace suggests, this appears to be a problem caused by one of your plugins. Likely the one you linked, so be sure to report the issue to them first. If it does happen to be our issue, feel free to come back to us with a more descriptive error. Unfortunately this has to be closed, have a good day!
