### ISSUE TITLE
Day cycle doesn't work, it stucks on first week

### ISSUE THREAD

**Issue by Cadiducho** [PaperMC/Paper#368]
# Incompatibility (Bug)
### What behaviour is expected:

A survival map where day count progress. When I write /time set 17000000 it should set the World Day into, more or less, Day 550.
### What behaviour is observed:

It stucks on 'Day 7', and then restart again into Day 1. This happend naturally, when the day progress by server ticks, or forced, when I write /time set and still go back to Day 1, 2, 3, 4, 5, 6 or 7, but never more of 7.
This broke our survival experience, because if Day doesn't progress, world difficult neither. Mobs doesn't spawn, Nether is almost empty of pigmans etc. It's like a 'easy difficult' loop.
### Steps/models to reproduce:

Go to latest Paper server and write /time set (a big number, such 17 millon) or /time set add. Anyway, you add or set to a big ticks number, it will not pass of Day 7. 
I recorded a video:
https://youtu.be/VcGpR3lW3uo
(On craftbukkit, spigot, paper etc. is the same world. I spawn on differents location due to online and offline mode, that gives differents UUIDs)
### Plugin list:

Anyone, like you could see on video, the server was without any plugin
### Paper build number:

Paper version git-Paper-816 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by MrPowerGamerBR** [comment]
This happens due to a workaround to fix the banner waving, this doesn't
affect the days server-side, only client-side.
Em 17 de jul de 2016 09:40, "Cadi" notifications@github.com escreveu:

**Comment by Gabscap** [comment]
[Link to Patch](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0092-Waving-banner-workaround.patch)
Related issues: #346 #266 
As @MrPowerGamerBR mentioned, this is only client side. The server itself saves the _real_ time and works with it. So there shouldn't be a problem with world difficulty, mob spawning, etc.

**Comment by Cadiducho** [comment]
So can be this disabled by config? I see on the patch I cant, but maybe that is a nice feature since our players prefer press F3 to see the real day :S

**Comment by Gabscap** [comment]
Good news: there is no need for a config option. #369

**Comment by zachbr** [comment]
Should be fixed in Builds 817+ thanks to @Gabscap's PR.
