### ISSUE TITLE
1.16.1 Custom ItemMeta resetting upon any action.

### ISSUE THREAD

**Issue by itsconnorgillespie** [PaperMC/Paper#3680]
### What behaviour is expected:
___What you expected to see___

I used the plugin ItemEdit (supported by 1.16) to add a custom name to an item and the item should display "Bloodstone" on the material RED_DYE with alternating bolded colors. 

### What behaviour is observed:
___What you actually saw___

When I rename the item to "&c&lB&4&ll&c&lo&4&lo&c&ld&4&ls&c&lt&4&lo&c&ln&4&le" or something with a lot of alternating colors, the item looses its NBT tags when dropped, moved in an inventory, cloned in creative, used in a chest or any inventory block, and the list goes on. If you simply rename the item "&c&lB&4&ll&c&lo&4&lo&c&ld&4&ls&c&lt&4&lo&c&ln" (Bloodstone without the e at the end and the &4&l) the item works perfectly fine.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Here is a video demonstrating the bug. (https://youtu.be/CFJHd315vm8)

### Plugin list:
___A list of your plugins___

All of the plugins are supported by 1.16 and no errors are returned in the config.

Vault
Unplaceable (Custom Plugin)
ProtocolLib
PlaceholderAPI
PermissionsEx
MythicMobs
ItemEdit
EssentialsX
DeluxeChat

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

get-Paper-14 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

I received an error this morning stating that an NBT tag was too big and it refused to let me connect. I restored my world to a previous backup and it worked as intended. To ensure this was not related to the issue, I went onto my survival world and tried to rename an item and had no success.

**Comment by aikar** [comment]
Fixed in build 19

**Comment by itsconnorgillespie** [comment]
Thank you!
