### ISSUE TITLE
1.16.1 spawnRadius always 0

### ISSUE THREAD

**Issue by minedhype** [PaperMC/Paper#3681]
### What behaviour is expected:
___What you expected to see___
Players will respawn in spawn radius

### What behaviour is observed:
___What you actually saw___
Players will only respawn at set spawn point block

### Steps/models to reproduce:
/setworldspawn, /gamerule spawnRadius 100, /kill youraccount

### Plugin list:
___A list of your plugins___
No plugins

### Paper build number:
This server is running Paper version git-Paper-18 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by hyperdefined** [comment]
I am having the same problem on my server. Tested without plugins and the spawnRadius is not being applied.

**Comment by Chew** [comment]
Latest Spigot matches Vanilla behavior. Paper does not.

**Comment by hyperdefined** [comment]
This bug seems fixed on the latest version (Paper-27). Not sure what changed, but spawnRadius is working again.

**Comment by aikar** [comment]
Well the irony is, it was a spigot bug, spigt fixed it:

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/fb4e54ad7b92603023494a276ad02ea935827109
