### ISSUE TITLE
1.16.1 Player head issue 

### ISSUE THREAD

**Issue by detoxv** [PaperMC/Paper#3682]
On latest build 19 player heads initially appear fine but in the creative or survival menu if clicked around the inventory a lot or clicked on several times they lose all NBT tags/data from "3 " tags in my case to 1 and revert to a steve head in the inventory.

**Comment by aikar** [comment]
I can't reproduce. Are you using any client mods (just have to ask, i know very little mods updated)

**Comment by detoxv** [comment]
Absolutely 0 client mods on complete vanilla minecraft latest version. It appears its when i left click to pick up the heads and use right click to move singles it turns into a steve head. Server side I use custom loot tables and the heads as a currency on my server and i used a command block to generate a dungeon chest that contains this custom currency. Upon shift clicking it out into the menu and clicking on it to pick up the stack it often changes to a steve head. This also happened with a custom rank essentials command to spawn them in via essentials (very latest version) I also use this item based currency on the shopkeepers plugin. Overall heads just seem buggy this update but at least they are actually working now as of the latest paper update. I'll definitely need to wait longer to update my live server just to be very sure heads have no issues as, economy is the core of the server. Just unsure whether i need to convert and change to a stock item currency and move away from textured playerheads yet or not

**Comment by LoneDev6** [comment]
Maybe this is related: https://hub.spigotmc.org/jira/browse/SPIGOT-5892
