### ISSUE TITLE
1.16.1 Italicized ChatColor Bug

### ISSUE THREAD

**Issue by itsconnorgillespie** [PaperMC/Paper#3683]
### What behaviour is expected:
___What you expected to see___

I used the plugin ItemEdit (supported by 1.16) to add a custom name to an item and the item should display "Bloodstone" on the material RED_DYE with alternating bolded colors.

### What behaviour is observed:
___What you actually saw___

When I rename the item to "&c&lB&4&ll&c&lo&4&lo&c&ld&4&ls&c&lt&4&lo&c&ln&4&le" or something with more than one color, the characters after the first defined color are italicized. This occurs within the lore of an item and the item's displayname. 

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Here is a video demonstrating the bug. (https://youtu.be/SQNgqoIK0_w) 
Take notice of the italicized lore "LEGENDARY".

### Plugin list:
___A list of your plugins___

All of the plugins are supported by 1.16 and no errors are returned in the config.

Vault
Unplaceable (Custom Plugin)
CustomRecipes (Custom Plugin)
ProtocolLib
PlaceholderAPI
PermissionsEx
MythicMobs
ItemEdit
EssentialsX
DeluxeChat

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

git-Paper-19 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

I am pretty sure this is a very easy fix and thanks for helping all of our servers run stupid fast!

**Comment by ghost** [comment]
update paper

**Comment by itsconnorgillespie** [comment]
@YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE I am on the latest paper version. I am on version 19 and I will edit my typo.

**Comment by aikar** [comment]
working on it.

**Comment by itsconnorgillespie** [comment]
@aikar Thank you so much! Have a nice night (or day)!

**Comment by itsconnorgillespie** [comment]
Just thought I would update you (if you were unaware), that the bug still exists as of paper 26.

**Comment by Sikatsu** [comment]
Could it be, that this also breaks certain placeholders due to it becoming italic?

1.16: ![image](https://user-images.githubusercontent.com/5664135/86397419-0f906080-bca4-11ea-8f6d-b44f8745dfa5.png)

1.15: ![image](https://user-images.githubusercontent.com/5664135/86397452-1d45e600-bca4-11ea-9d89-97ee8a45f6ba.png)

**Comment by itsconnorgillespie** [comment]
@Sikatsu yes. It happens with placeholders and anything with more than one color in the name. It’s due to &r the not resetting (what I found on a spigot jira report). I have no clue how long this is going to take to fix and it seems like it’s something paper doesn’t have control over.

**Comment by Sikatsu** [comment]
@aikar mentioned on discord this is a paper specific issue, so I think it is something paper has control over. Hopefully it won't take too long for a fix, it looks terrible in some situations haha! But I noticed that my placeholders don't function either, but when I parse them without the color code it seems to work fine.

**Comment by itsconnorgillespie** [comment]
I was unaware that spigot fixed it. Hopefully it can get fixed soon!

**Comment by detoxv** [comment]
Having this issue too, hopefully it does get fixed soon

**Comment by itsconnorgillespie** [comment]
@aikar I applaud you! Not sure which build fixed it, but the most recent version (paper-71) fixed this issue. Thank you and have a great rest of your day/night!
