### ISSUE TITLE
PiglinBarterEvent / API in Piglin Entity to modify trade tables.

### ISSUE THREAD

**Issue by jpenilla** [PaperMC/Paper#3684]
**Is your feature request related to a problem? Please describe.**
My feature request is not directly related to a problem but I believe it would be a useful addition to the API. There is no current API in 1.16 Paper or Spigot to listen for an Event when Piglins are bartered with, and there is also no API in the Piglin Entity to set their recipes.

**Describe the solution you'd like**
 - A solution would be a PiglinBarterEvent that would fire after the Piglin picked up the payment item, and before he drops the reward. The Event would expose an ItemStack payment and an ItemStack result, and result could be replaced with a setResult method in the Event.
 - Another useful solution would be a method in the Piglin Entity to set his recipes, similar to[ the implementation for Merchant Entities
](https://papermc.io/javadocs/paper/1.16/org/bukkit/inventory/Merchant.html#setRecipes-java.util.List-)

**Describe alternatives you've considered**
 - Listening to ItemSpawnEvent and figuring when a Piglin is dropping items to then spawn a different Item and cancel the event

**Additional context**
 - Piglin Bartering  is one of the biggest new features of 1.16, and allowing plugin developers to modify it would be immensely useful for balance changes as well as customization.

**Comment by jpenilla** [comment]
Once #3766 is merged the only missing API would be one to set other items to be picked up as barter payment.
Hopefully this could be done with an addition to the Piglin Interface

**Comment by Machine-Maker** [comment]
Yeah, I'm not sure what the best way to go about this would be. If we wanted it to be per-piglin, then it would have to be something that was stored in nbt with the rest of the entity. 

Could be a global thing too, not sure.

**Comment by jpenilla** [comment]
Storing a list of ItemStacks or Materials in the NBT is probably the way it would need to be done. If it was global I can imagine lots more issues when multiple plugins make changes. We would probably want getters and setters for the list as well as maybe add and remove methods. A way to get the default list of payment items would also be useful

**Comment by jpenilla** [comment]
Implemented upstream
