### ISSUE TITLE
Lighting glitch occurring in new chunk sections above ground that have no data and also affecting neighboring chunk sections

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#3685]
### Paper build number:
Paper version git-Paper-373 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### What behaviour is expected:
Lighting glitches should not occur in brand new chunk sections at high y levels of the world.

### What behaviour is observed:
When using nms to set the blocks for tall builds some of the chunk sections in between the selection will have very strange behavior in regards to lighting (the 3rd chunk section from ground level and above from my testing for some reason), you won't be able to see the glitch at first but relogging after the operation will make the glitch visible and multiple relogs may show the glitch looking different each time. If you don't want to relog you can also move away from the chunk to make it unload and load it again to make the glitch visible. In this state you cannot use /paper fixlight to fix the glitch or any other plugin that fixes lighting bugs such as CleanLight - it's as if something is stuck (Light engine?). The only way to fix this is to restart the server and then run /paper fixlight.

![2020-06-28_17 44 29](https://user-images.githubusercontent.com/10485646/85971925-61946600-b9c6-11ea-9637-e37b0c9ebea9.png)

This isn't a normal lighting glitch though, it's very specific and shouldn't be happening in the first place since setting the blocks with nms does not touch lighting at all, this is not an issue in 1.13.2 but occurs in 1.14.4 and 1.15.2 (must be related to the light engine?). This only affects certain chunk sections in between the region selection and neighboring chunk sections for some reason. I believe it has something to do with the **chunk sections in between the region selection having no data**, only the bottom and the top chunk section used for the region selection positions had data associated to them because a block had been placed in them so that I could select the region. I confirmed this because I was unable to reproduce this glitch when **every chunk section in the region selection had a block placed in it**. 

What's also strange is that **neighboring chunk sections** that were **not part of the region selection at all** were also affected by this glitch, it's as if the server is actively creating this glitch for some reason. I put together code that would set the skylight to 15 for every chunk section when blocks are set but even that doesn't solve the problem, it still has this weird lighting glitch problem for anything that is above the 2nd chunk section from ground level that I can't seem to avoid regardless of whether I don't touch the light or try to force the light level to be at a particular number.

This chunk section has not been touched by the plugin but the lighting is glitched:
![2020-06-28_17 45 03](https://user-images.githubusercontent.com/10485646/85972338-a076eb80-b9c7-11ea-9643-0bba9748959c.png)

### Steps/models to reproduce:
This is a small scale way of reproducing the issue, you will need FastAsyncWorldEdit.

Using a **new world** place a block in the corner of a chunk section:
![1](https://user-images.githubusercontent.com/10485646/85970946-d4501200-b9c3-11ea-855e-68e2f625941f.png)

On the opposite corner build a pillar outside of the chunk section until you have filled in the 5th chunk section. This pillar needs to be built for the test so that you can place the second region position inside the same chunk as the first block you placed. The region you will be setting needs to have empty chunk sections in between the top and bottom for the glitch to happen:
![2](https://user-images.githubusercontent.com/10485646/85971033-0792a100-b9c4-11ea-8fb5-814015934d60.png)

Now use the pillar to place the block inside the chunk section you will be using for the set operation.
![3](https://user-images.githubusercontent.com/10485646/85971083-242ed900-b9c4-11ea-8dde-071711db3a97.png)

Select the first block you placed on the corner of the chunk section:
![4](https://user-images.githubusercontent.com/10485646/85971138-3f014d80-b9c4-11ea-889a-aea163b47653.png)

Now select the second block you placed on the opposite corner of the chunk
![5](https://user-images.githubusercontent.com/10485646/85971203-69530b00-b9c4-11ea-8c4f-69c33b116e03.png)

Everything looks fine visually at first:
![6](https://user-images.githubusercontent.com/10485646/85971217-77a12700-b9c4-11ea-911a-9821d55ca752.png)

Rejoining or causing the chunk to unload and be loaded again will show that the 3rd chunk section has a lighting glitch on at least one side:
![7](https://user-images.githubusercontent.com/10485646/85971239-8ee01480-b9c4-11ea-9a62-5dea6f436c48.png)

Rejoining again will also show how something is going on behind the scenes to cause the glitch to look different:
![8](https://user-images.githubusercontent.com/10485646/85971273-a3241180-b9c4-11ea-8b6a-a4217d21df32.png)

It's also strange because it causes surrounding chunk sections that were not part of the region selection to also have a lighting glitch:
![9](https://user-images.githubusercontent.com/10485646/85971305-bc2cc280-b9c4-11ea-9abf-9c59c5225ff6.png)

![10](https://user-images.githubusercontent.com/10485646/85971372-ccdd3880-b9c4-11ea-9a32-247a1601db11.png)

You can attempt to use /paper fixlight but sometimes it will not do anything at all, when testing with much larger builds I could not get /paper fixlight to fix the issue at all - the only way to fix it was to restart the server and then run /paper fixlight.

In conclusion, I think the issue is related to the lighting engine actively creating these glitches if the region has empty chunk sections above ground level (the glitch happens from the 3rd chunk section and everything above that is also affected) and chunk sections outside of the operation are being affected by this for some reason even though they are not being touched by the plugin at all. You probably have a better idea of what is going on here and if this is a bug with the light engine I was hoping you would be able to apply some type of fix for it. Setting blocks via nms at high y levels are basically forced to have this lighting glitch on them regardless of whether they manually set the skylight or don't do lighting updates at all. I think this issue is probably the root cause of: https://github.com/PaperMC/Paper/issues/3542 but I'm not entirely sure.

### Plugin list:
FastAsyncWorldEdit, WorldEdit, Luckperms

**Comment by aikar** [comment]
Thanks for the info. Been hardcore trying to figure this out but still so lost, so will see if this adds anything.

The irony is, it's not even caused by our Light Engine changes. It's purely caused by (or at least exposed) by the priority system improving chunk load order.

Seems to relate to order chunks load w/ their neighbors.
