### ISSUE TITLE
When i load my world with armour statues datapack i get a NPE on startup (the server still runs)

### ISSUE THREAD

**Issue by rrvk** [PaperMC/Paper#3689]
### Link/paste of stack trace
https://pastebin.com/UzaWgNR0

### Plugin list/ Datapack:
* armour statues v2.7.1.zip From (https://vanillatweaks.net/picker/datapacks/)

### Actions to reproduce (if known):
* Greate a world
* When the world folder is generated stop the server
* Add the datapack
* Restart the server

### Paper build number:
`This server is running Paper version git-Paper-19 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`

**Comment by Prof-Bloodstone** [comment]
> [08:48:58 ERROR]: Couldn't load function tag minecraft:tick as it is missing following references: main:tick (from armour statues v2.7.1.zip)

Looks like the datapack is broken. Unfortunately quite often Vanilla Tweaks datapacks are invalid (had issues with head datapack which was broken silently).
Do yourself a favor and use a plugin - datapacks should not be used for things like this since they cause more performance loss than plugins.

**Comment by rrvk** [comment]
When i run it on the most recent version of 1.15.2 it will run, so it looks like 1.16.1 breaks it
`This server is running Paper version git-Paper-374 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**Comment by rrvk** [comment]
White the latest version of paper 1.16.1 it is fixed!
