### ISSUE TITLE
bukkit.yml ignored?

### ISSUE THREAD

**Issue by motoionic** [PaperMC/Paper#3690]
Upgraded from paper 1.15.2 to 1.16.1 this morning.

I have a bukkit.yml within a line saying: world-container: worlds

This means I can put my world files together in a folder away from the server configs.

However starting the latest dev build of paper 21 its generated new world files in the server root folder.

**Comment by electronicboy** [comment]
Spigot removed this due to some issues around load order, you now need to specify it at startup
```
-W, --universe, --world-container, --   World container (default: .)
  world-dir <File: Directory
  containing worlds>
```
