### ISSUE TITLE
Placing player heads with a custom name will change to steve heads after a while and when you break them

### ISSUE THREAD

**Issue by NathanCollaert** [PaperMC/Paper#3692]
### What behaviour is expected:
Placing a player head with a custom name and texture and breaking it again will give the player head with the correct texture and custom name.

### What behaviour is observed:
Placing a player head with a custom name and a custom texture will turn into a default steve head after a while, on top of that it will also change back to a default steve player head upon breaking it.

### Steps/models to reproduce:
* Download the wandering trader datapack from Hermitcraft.
* Trade with a wandering trader for one of the mini blocks (player head).
* Place the mini block and break it. OR Place the mini block and leave it there for a couple of minutes (might be caused by chunk unloading/loggin out and back in).

### Plugin list:
None

### Paper build number:
Paper version git-Paper-21 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by LoneDev6** [comment]
Maybe this is related: https://hub.spigotmc.org/jira/browse/SPIGOT-5892

**Comment by NathanCollaert** [comment]
Might be nice to mention that this doesn't occur with player heads that were already in the game since 1.15.

**Comment by SharkROAR** [comment]
This also happens when you middle click a custom head to copy it. 
Most of the time, although not always - which is super weird - it will lose its custom texture and possibly other NBT tags, except for the custom item name.

**Comment by aikar** [comment]
fixed in 30+
