### ISSUE TITLE
Config option "use-vanilla-world-scoreboard-name-coloring" doens't work correctly

### ISSUE THREAD

**Issue by MAXOUXAX** [PaperMC/Paper#3695]
Hey guys!
I've been using Paper on 1.15.2 and used this config option to display teams in the chat.
I tried to do the same on 1.16.1, and it doesn't work.
Prefixes are displayed correctly, but the color is always white.

### What behaviour is expected:
Config option displaying prefixes and colors correctly

### What behaviour is observed:
Config option correctly displays prefixes but the color is always set as white.

### Steps/models to reproduce:
- Edit `paper.yml` and set to true the `use-vanilla-world-scoreboard-name-coloring` option
- Start your server
- Create a team with a prefix and a color
- Talk in chat

### Plugin list:
None

### Paper build number:
Paper-10

**Comment by JieSheng03** [comment]
Similarly, for me, I used vanilla Minecraft server 1.15.2, updated it to vanilla Minecraft server 1.16.1, the team colour still shows up correctly in chat. However, after trying Paper-8 updating to Paper-24, team colour is still not showing up correctly in the chat after changing the same line in paper.yml. Team colour works in the scoreboard, player list, @a or /say but just not when they are typing normally.

**Comment by agoniaprivat** [comment]
Already reported:
https://github.com/PaperMC/Paper/issues/3676

**Comment by dvitski** [comment]
+1, this is currently the only thing preventing me from using Paper in 1.16

**Comment by aikar** [comment]
closing as this is a duplicate of the issue mentioned above
