### ISSUE TITLE
1.16.1 | Paper21 - Time out, then crash?

### ISSUE THREAD

**Issue by crazykidney** [PaperMC/Paper#3696]
### Link/paste of stack trace
https://pastebin.com/c2Nw3V11

### Plugin list:
Buycraft

### Paper build number:
21

###
What exactly happened there?

**Comment by willies952002** [comment]
Please provide a corrected list of plugins, the log has a tell-tale sign that there is at least BuycraftX installed.

**Comment by crazykidney** [comment]
Plugins are custom and don't do much, I believe they were all disabled when the issue happened.

I never disable Buycraft as it doesn't really break anything to my knowledge.

Still don't see how it's relevant to server trying to generate a chunk or something.

**Comment by willies952002** [comment]
Your issue report initially stated that you didn't have any plugins installed, which means *every* plugin, not just off-the-shelf ones.

**Comment by Proximyst** [comment]
Fixed in https://github.com/PaperMC/Paper/commit/0cf106087d4f210751df09e8d31a666444c02878.

> Current Thread: spark-cpu-monitor

> Plugin list: Buycraft

Please don't try to lie or the likes on issue reports...
