### ISSUE TITLE
1.16.1 Crash server : player have attribut modifications

### ISSUE THREAD

**Issue by Florianpal1** [PaperMC/Paper#3698]
### Link/paste of stack trace

https://hastepaste.com/view/cPzhwYwK

### Plugin list:

![image](https://user-images.githubusercontent.com/36370356/86040469-61d34680-ba44-11ea-86da-4dcdbe66b4e5.png)

### Actions to reproduce (if known):
i don't known

### Paper build number:
paper-24 and waterfall-358

**Comment by Proximyst** [comment]
Fixed with https://github.com/PaperMC/Paper/blob/8a609953b43b65f85869b0b1c90d79587abdc91f/Spigot-Server-Patches/0522-Convert-legacy-attributes-in-Item-Meta.patch.
