### ISSUE TITLE
1.10.2 cannon sand,tnt and tnt water damage problem

### ISSUE THREAD

**Issue by djyee** [PaperMC/Paper#370]
hello i am using 1.10.2 i am try to stack sand to wall but sand hit the wall and going up same thing hapening to tnt if tnt hit the wall its going up.  if i use toomany tnt in water its blowing up can you fix this problems if this is not problem can you add settings ?  sorry for my bad english here is the video: 
http://www.youtube.com/watch?v=O1UE8yFiFZU

**Comment by zachbr** [comment]
Should fix the issue with it exploding and causing surrounding damage in water.
As far as I can tell the 'issue' you're seeing in which it rises when hitting a wall, water or no, has always been a vanilla feature. The water slows it, it doesn't stop it. Yours is the first report I've gotten that that is in any way weird.

**Comment by djyee** [comment]
i am throwing 60-40 sand to wall its not stacking to wall i have no idea why -.-
 its working on 1.8 paper.

**Comment by zachbr** [comment]
Probably a duplicate of GH-329. That is no longer vanilla behavior. PRs welcome.
