### ISSUE TITLE
1.16.1: loottables.auto-replenish not working as expected

### ISSUE THREAD

**Issue by konsolas** [PaperMC/Paper#3701]
### What behaviour is expected:
Paper preserves the loot tables of dungeons chests.

### What behaviour is observed:
Chests lose their loot tables after they are opened

### Steps/models to reproduce:

- Get Paper #24
- Install https://github.com/nossr50/Invincible-World-Chests which cancels block breaks if the chest has a loot table
- Run the command `/give @p minecraft:chest{BlockEntityTag:{LootTable:"minecraft:chests/simple_dungeon"}}`
- Place the chest
- Try to break it (you won't be able to)
- Open the chest
- Try to break it (you will be able to)

Expected behaviour is that you aren't able to break it the second time

### Plugin list:
Invincible-World-Chests

### Paper build number:
```
This server is running Paper version git-Paper-24 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
```

### Anything else:
This was working on 1.15

**Comment by apppppppple** [comment]
This is happening to me as well.

**Comment by Puremin0rez** [comment]
Yup, I can confirm this issue.

Anything that has a loot table will lose its loot table upon viewing it. Chests, Chested Minecarts, etc.

**Comment by RWoof** [comment]
I also have the same issue, hopefully the fix is committed soon!

This is a big deal because it'll take forever to find and regenerate loot tables for chests in the game one by one, I bet a lot of servers haven't noticed this bug yet as it's subtle.

**Comment by elwakka** [comment]
Really need this fixed!   Please <3
