### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by B1gLev** [PaperMC/Paper#3703]
### Paper build number:
Version | git-Paper-374 (MC: 1.15.2)

**Comment by MissPotato** [comment]
Did you really take a picture of the crash instead of just uploading it to pastebin?

**Comment by B1gLev** [comment]
> Did you really take a picture of the crash instead of just uploading it to pastebin?
Sorry but I didn't think of this option

**Comment by MissPotato** [comment]
This looks like a server freeze than a crash, is there more in the log? Might, need to upload the full log.

**Comment by B1gLev** [comment]
This is the full log https://pastebin.com/1jSQupLm

**Comment by willies952002** [comment]
After checking the log, I'm not seeing anything that suggests that the server crashed. What line is the crash on?

**Comment by B1gLev** [comment]
What do you mean?

**Comment by c0d3rb0y** [comment]
Basically where in the log shows it crashed is what they mean.

**Comment by c0d3rb0y** [comment]
I checked your log, no sign of crash.

**Comment by B1gLev** [comment]
One of the plugins caused this error. Ever since I exchanged everything is perfect :smile:
