### ISSUE TITLE
Server Crash minecraft:generic

### ISSUE THREAD

**Issue by Cerexus** [PaperMC/Paper#3705]
https://pastebin.com/avkyKp52

### Actions to reproduce (if known):
There was that one player that crashed the server multiple times after he joined. I switched back to Paper 10 and it showed only  "Unable to create attribute" but was no longer crashing.

### Paper build number:
Paper 24

**Comment by Florianpal1** [comment]
I have the same problem. This problem appears in the build paper-20. You can use paper-19 if you want a more recent build.

**Comment by Cerexus** [comment]
@aikar What would you say?

**Comment by HexedHero** [comment]
Pastebin is removed

**Comment by Cerexus** [comment]
@HexedHero Oh, yes... Here again without expiration ^^ https://pastebin.com/iMPEEFP0

**Comment by HexedHero** [comment]
Hmm
`Caused by: net.minecraft.server.v1_16_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:generic.armorToughness`

seems to be because they changed it to "generic.armor_toughness" in 1.16 maybe.

**Comment by chickeneer** [comment]
Specifically the colon Since it is not one of these: `letter`, `number`, `/` ,`.`, `_`, `-`

**Comment by Cerexus** [comment]
The crash has something to do with the changes in paper 20. I switched to 19 and i have no crashes only that message "unable to..". With paper 20 the server crashes if certain players join

**Comment by RobertLynn76** [comment]
The game gets closed upon launching which is very frustrating and it needs to get fixed quickly but i came across some steps to <a href="https://technographx.com/minecraft-keeps-crashing/"> fix the issue of crashing </a> :
Fix 1: Restart Your Computer
Fix 2: Update the Game Patches
Fix 3: Update the Graphics Card Driver
Fix 4: Stop Overclocking Your CPU
Fix 5: Configure the Correct Settings
If you would follow every solution properly your issue would get fixed easily.
