### ISSUE TITLE
Unable to place water against double slabs.

### ISSUE THREAD

**Issue by rafe2486** [PaperMC/Paper#3706]
### To replicate:

1. Take a bucket of water, and try to pour it out against a double slab (any type).
2. The water appears for a split second, then disappears.
3. The water bucket appears empty, but when trying to place it a second time it pours out (unless you try using the double slab again).
4. If you try to pour out the bucket against a double slab more than once you lose the water.

### Plugins in use:
PlayerHeads
EntityTrackerFixer
Vault
DeadChest
SilkSpawners
![2020-06-29_17 26 52](https://user-images.githubusercontent.com/67610532/86060738-604d5280-ba33-11ea-84a2-2785d045de8e.png)
![2020-06-29_17 27 05](https://user-images.githubusercontent.com/67610532/86060741-60e5e900-ba33-11ea-8383-3a385c2ec57a.png)
![2020-06-29_17 27 15](https://user-images.githubusercontent.com/67610532/86060742-60e5e900-ba33-11ea-9d72-342fac56a2d0.png)
![2020-06-29_17 27 44](https://user-images.githubusercontent.com/67610532/86060744-617e7f80-ba33-11ea-8cc4-d851475a7cf7.png)

**Comment by wizjany** [comment]
what paper version? pretty sure this was fixed in upstream pull.
https://github.com/PaperMC/Paper/commit/78c855237936c084ba783d4926d18b6340b4d0ef

**Comment by rafe2486** [comment]
@wizjany 

![2020-06-29_18 20 14](https://user-images.githubusercontent.com/67610532/86061685-372dc180-ba35-11ea-9939-781d420d5233.png)

**Comment by Proximyst** [comment]
As the message states, you are 24 versions behind. This was already patched.

**Comment by aikar** [comment]
you need to be checking for updates and updating every 3-6 hours any time a new release is out.

Though most of our updates will come around this time til the next 8 hours~
