### ISSUE TITLE
1.15.2 build 374 make a crash with Citizens

### ISSUE THREAD

**Issue by Momonche** [PaperMC/Paper#3707]
### Link/paste of stack trace
https://pastebin.com/vn27kDrG
https://timings.aikar.co/?id=3d1e09f58bc04bbf8ae55507c16810a1#timings

### Plugin list:
ActionBarAPI, AnimatedScoreboard, AreaShop, ArmorEquipEvent*, AsyncWorldEdit, AsyncWorldEditBossBar, AvancedItemEffets*, Bank, BetonQuest, BlyatRPG, boosCooldowns*, Broadcaster, BungeeTabListPlus, ChestCommands, Citizens, ClearLag, ColoredBooked, CommandHook, Core, CoreProtect, CrazyCrates, DeathMessagesPrime, DMPCitizens, EntityTrackerFixer, EpicSpawners, Essentials, EssentialsAntiBuild, EssentialsMysqlStorage, EssentialsSpawn, F3NPerm, Factions, FBasics*, GemsEconomy*, HealthBar*, HelpopEra, HolographicDisplays, HolographicScoreboard*, Hub, IllegalStack, InfiniteAnvil*, InfiniteDispenserX, Jobs, JSONAPI-RELOADED, KnockbackMaster*, LiteBans, Lores*, LuckPerms, Magic, MassiveCore, MessageAnnouncer, MineProtectEra, MobArena, MoneyPrinters, Multiverse-Core, Multiverse-Portals, MysqlPlayerDataBridge, NametagEdit*, NoCheatPlus, OldCombatMechanics, OpenInv, PearlFix, PlaceholderAPI, PlayerHeads, PlugMan, ProtocolLib, ProtocolSupport, RPGChest, RPGMenu, RubisEra, Sentinel, ServerSigns, ShopGUIPlus, SignEdit, SkinsRestorer, spark, Statz, TPBukkit, Vault, VentureChat, ViaVersion, VoteBox, VoxelSniper, WarnBan, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Actions to reproduce (if known):
Launch git-Paper-374 with some Citizens's NPC

### Paper build number:
git-Paper-374 

Latest builds (since build 344) doesn't work with Citizens, when the server start, TPS can't be more than 5 and decrease to make the server crash

**Comment by Proximyst** [comment]
Can you reproduce this with *only* Citizens and give us the traces it spits out?

**Comment by Momonche** [comment]
More tests on my production server (with all plugins):

git-Paper-345
https://timings.aikar.co/?id=1580acecc79348debbc8c0e4b9b1d7b4
Works fine (and seems better than 343)

git-Paper-346
https://timings.aikar.co/?id=22d9b4ed2d564944a6161c9f14e77438
The issue appear on this build, nerver more than 5 TPS

git-Paper-374
https://pastebin.com/ZtnipyQV
Can't generate Timings cause of the hard lag and hard crash before I can do /timings paste

More test on a local server just with Citizens soon

**Comment by Momonche** [comment]
Local server, just with Citizens and Sentinel

git-Paper-345
https://timings.aikar.co/?id=d361e465987744f29e9fe205e2c9fdfc#timings
Works fine, 20 TPS

git-Paper-346
https://timings.aikar.co/?id=35759c7e99cf4439805507cd0940ff65
TPS drop to less than 5, like production server

git-Paper-374
https://timings.aikar.co/?id=a55db262146c44e4984dad46692220dc#timings
No crash, but TPS drop to less than 4

**Comment by Momonche** [comment]
In some builds this issue was affecting Paper
https://github.com/PaperMC/Paper/issues/3573
But somes fix be done by Aikar

After that, this issue appear 
https://github.com/PaperMC/Paper/issues/3637
But seems to be fix with Paper 373, but I can't find the commit on 1.15.2 (No changes ?)
That fix was push on 1.16.1 build 14 in the same time

**Comment by Momonche** [comment]
I just test with git-Paper-68 (MC: 1.16.1)
And that issue still here
https://timings.aikar.co/?id=24d3d63d23524fe79265985a5f62c499

**Comment by Momonche** [comment]
Latest buils of Citizens fix this issue
