### ISSUE TITLE
Item names inconsistant after 1.15.2 -> 1.16.1 update

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3709]
### What behaviour is expected:
for custom items to be named §dCustom item

### What behaviour is observed:
custom items named this monstrosity:
{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"light_purple","text":"Custom item"}],"text":""}

###Additional information
This has made various items on my physical economy server not stack or able to be traded with villagers

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
paper 1.16.1 build 24

**Comment by Proximyst** [comment]
This is a consequence of attempting to move to Mojang's components as they're used all over the game now. Time to update your items perhaps?

**Comment by ghost** [comment]
How can i do this via plugin

**Comment by ghost** [comment]
also {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"light_purple","text":"Custom item"}],"text":""} is absurdly wasteful

**Comment by Brokkonaut** [comment]
I think its an error when they got converted to 1.16. What you see there is the internal format that should not be visible.

**Comment by chickeneer** [comment]
I have marked this issue as incomplete. As mentioned, this is a consequence of everything being moved to components. As such, the section symbol § is not going to work the same as it has for previous Minecraft versions.
We would need to know more about how you are creating these custom items. To find out why they are not stacking or trading.
I hope to hear from you, you can also visit us on Discord.
