### ISSUE TITLE
player.getfirstplayed corrupted

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3712]
### What behaviour is expected:
___What you expected to see___
player that started playing 2 years ago, firstplayed should be that date

### What behaviour is observed:
___What you actually saw___
firstplayed being reset to a few hours ago

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
24
### Anything else:
___Anything else you think may help us resolve the problem___
who touched this

**Comment by Chew** [comment]
There is not enough information here to reliably figure out the underlying issue. And as the account no longer exists, it is impossible to receive more information, so this must be closed. If you have this issue on a supported version, please open a new issue, fill out the entire template, and we'll be happy to help.
