### ISSUE TITLE
[1.16] NBT lost on inventory click and other situations

### ISSUE THREAD

**Issue by jpenilla** [PaperMC/Paper#3714]
### What behaviour is expected:
An Item Frame gotten from this command ```/minecraft:give @s item_frame{EntityTag:{Invisible:1}}``` Should not stack with a normal Item Frame.

### What behaviour is observed:
After spam clicking the Item Frame with NBT on top of the one without inside my Inventory (Survival or Creative mode) the NBT tag eventually disappears and the two items that were different now stack. Also when getting an ItemStack from InventoryClickEvent.getCursor() it seems to lose this NBT.
Edit: NBT also gone when getting an ItemStack like this ```ItemStack hand = p.getInventory().getItemInMainHand();```

### Steps/models to reproduce:
1. ```/minecraft:give @s item_frame{EntityTag:{Invisible:1}}```
2. Spam click the Item Frame from the command on top of a normal Item Frame inside your inventory
3. Watch the NBT disappear

### Plugin list:
Essentials, EssentialsChat, LibsDisguises, LuckPerms, McRPG, PlaceholderAPI, ProtocolLib, Vault, WanderingTrades, WorldEdit, WorldGuard

### Paper build number:
1.16.1 Paper-27

**Comment by jpenilla** [comment]
May be related to #3692 and #3682

**Comment by jpenilla** [comment]
Confirmed to also exist on Spigot https://hub.spigotmc.org/jira/browse/SPIGOT-5907

**Comment by detoxv** [comment]
This is also happening with me with player heads NBT data getting lost on inventory clicks.

**Comment by jpenilla** [comment]
Fixed in Paper-29
