### ISSUE TITLE
Custom Player Heads revert to original player

### ISSUE THREAD

**Issue by Frilioth** [PaperMC/Paper#3716]
We are using the decapitation datapack that drops players heads. Prior to 1.16 this has allowed us to "Sell" all kinds of great designed heads. However, since 1.16 all player heads when placed on a block are given the same texture. Sometimes this is the original player head and sometimes it's a custom head but all the heads are the same. When in your inventory or on an armour stand they appear as they should as you can see on my hot bar, it's only when they are placed on a block. 

<img width="1931" alt="Screenshot 2020-06-30 09 29 13" src="https://user-images.githubusercontent.com/46084236/86103101-3e47e480-bab4-11ea-8041-7c1372d80be0.png">

### Plugin list:
armorstandeditor-1.14-23.jar
MotdManager-Reloaded.jar
Shopkeepers-2.10.0.jar
Vault.jar

### Paper build number:
paper-27

### Anything else:
I posted this issue on #3672 but aikar asked me  to start a new thread so here it is. He also said that

"basically your triggering the client bug that the patch that caused this issues original issue caused.

what your seeing is vanilla minecraft behavior. Paper has a patch to fix that, but it appears not every skull had the UUID updated correctly and some are still in the string format which can be iffy."

He asked me to show the data dump of 2 heads that are different. I dont know how to do this as text so Ive had to take screenshots.

<img width="1931" alt="Screenshot 2020-06-30 09 46 11" src="https://user-images.githubusercontent.com/46084236/86105148-e2cb2600-bab6-11ea-8e25-de71bb5e4cd3.png">

<img width="1931" alt="Screenshot 2020-06-30 09 46 16" src="https://user-images.githubusercontent.com/46084236/86105169-ea8aca80-bab6-11ea-8c3e-7bc91cb3575c.png">

<img width="1931" alt="Screenshot 2020-06-30 09 46 21" src="https://user-images.githubusercontent.com/46084236/86105183-ef4f7e80-bab6-11ea-910c-b3f9bc5f585d.png">

As you can see the signatures: are different but the value: is the same

**Comment by detoxv** [comment]
I have issues with player heads too with a similar decapitation system. Player heads revert to default heads when moving them in the inventory to different slots. Does this happen to you? If i move them around the inventory or press Q to drop them it sometimes reverts and they lose all NBT data down from 3 tags to 1 tag keeping the rename but losing all other data.

**Comment by SharkROAR** [comment]
This is still happening as of Paper-30, it appears that it is now even more broken: Custom heads are spawned in with only 2 instead of the usual 3 nbt tags on my server.

**Comment by aikar** [comment]
please provide copy of said heads nbt data.

Essentials phead and head gui plugins are working for me.

**Comment by aikar** [comment]
2 is the expected value count for 100% valid data. 3 was the old format that had Damage: 3

Client will show +1 than what the server has due to our fix for the client bug.

I have a player head that simply has 1 NBT Tag, SkullOwner
On client, this shows as 2
```
[05:33:00 INFO]: -5505, 72, -13186 has the following block data: {
  z: -13186, 
  id: "minecraft:skull", 
  y: 72, 
  x: -5505, 
  SkullOwner: {
  Name: "Aikar", 
  Properties: {
    textures: [{Signature: "MRBE....GexDiI=", Value: "ewogI...Qp9"}]
  },
  Id: [I; 599832366, 1782530960, -1988124989, 686750066]}}
```

Many plugins are still creating heads with Damage:3 which is pre 1.13 behavior.

This damage is getting stripped off because it wasn't supposed to be there.

**Comment by aikar** [comment]
Oh, pre 1.16 heads would of also had 3 because UUID used to be stored in 2 values.

This is now changed in 1.16, and heads are instead saved as 1 field for UUID

This change is whats been the source of the issues due to plugins and datapacks still using the old format.

Our fix makes it read the old format if its set that way still. but it will ultimately end up correct if set.

**Comment by SharkROAR** [comment]
Sorry, I'm not that familiar with the whole UUID-thing, but what I'm trying to do is this:

`/minecraft:give SharkROAR minecraft:player_head{display:{Name:"{\"text\":\"VoteToken\"}"},SkullOwner:{Id:"17c5685a-e32d-4797-8629-cfd61c433565",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmE2MGFjNmI0MmFjN2E0MzM2Yzg1MTY4NTE0ZTcxZjllZTM3OGNkYzE1MjMzNTI3ZTI1NGU5ZDhmNGM4ZWQifX19"}]}}} 1`

It's a Token used to turn into other things on our server.

Expected result:
![image](https://user-images.githubusercontent.com/1337229/86232907-f1880a80-bb94-11ea-87fe-bff91fc6e85d.png)

What I'm getting is a blank player head, the texture value gets removed:
![image](https://user-images.githubusercontent.com/1337229/86232564-6a3a9700-bb94-11ea-8a60-ebe263c28bfc.png)

**Comment by aikar** [comment]
Your input is not valid for 1.16
see the I with 4 numbers in expected, you must supply UUID in that format

**Comment by SharkROAR** [comment]
> Your input is not valid for 1.16
> see the I with 4 numbers in expected, you must supply UUID in that format

I see.  My bad! 
Thanks a lot! It's working now.

**Comment by Frilioth** [comment]
Morning guys. Just updated to paper-44 and tried 2 heads mods and 1 heads datapack and I still have the same problem as described above. What might I be doing wrong?

**Comment by Diamondback88** [comment]
This is still an issue as of the latest Paper build. Are all pre-1.16 heads placed in the world permanently damaged?

**Comment by aikar** [comment]
Your going to have to produce something that's supposively still wrong as everything should be working now

Mojang should of converted in world heads.

Most issues today will be out of date plugins and data packs

**Comment by aikar** [comment]
Also going to be worth seeing how 1.16.2 goes as mojang fixed it but I ultimately need test data

**Comment by Chew** [comment]
This might've been fixed in #206, "Fix pre-1.16 serialized SkullMeta being broken on 1.16+, losing textures", if this is still an issue please let us know

**Comment by aikar** [comment]
We've had that fix Spigot put in for months.

**Comment by Chew** [comment]
So this is unrelated or this was fixed?
