### ISSUE TITLE
BUG: chunk ban due NBT

### ISSUE THREAD

**Issue by gabboman** [PaperMC/Paper#3718]
Some player maliciously crafted something that causes this chunk ban when getting near this chunk

![imagen](https://user-images.githubusercontent.com/3456181/86120048-e7ea9e00-bad3-11ea-982d-50cae1e96ada.png)

what can be done and how can it be fixed?

My server, being anarchy.... deleting the chunk will mean that will happend again in a few days

**Comment by electronicboy** [comment]
You missed the entire template... Worth noting that there was an issue around skulls in 1.16, but, existing skulls will still be busted, pending a patch to fix them...

**Comment by Prof-Bloodstone** [comment]
Fill in the template, please.
We don't even know what version you are running.
There was a bug in 1.16 - it's been fixed since for new items, but old ones can still cause it.
Logs, version, plugins - template is there for a reason.
