### ISSUE TITLE
[BUG] chunk ban problem

### ISSUE THREAD

**Issue by gabboman** [PaperMC/Paper#3719]
### What behaviour is expected:
not getting chunkbanned

### What behaviour is observed:

![imagen](https://user-images.githubusercontent.com/3456181/86121689-b9ba8d80-bad6-11ea-9a3e-1366bdfb3ad9.png)

console output:

[11:40:23 INFO]: gabboman joined the game
[11:40:23 INFO]: gabboman[/REDACTED] logged in with entity id 3399 at ([world]REDACTED) 
[11:40:24 INFO]: gabboman lost connection: Disconnected
[11:40:24 INFO]: gabboman left the game

### Steps/models to reproduce:
shulker with a lot of items with lore and 32k superweapons

### Plugin list:
CoreProtect, Essentials, IllegalStack, LuckPerms, Matrix, MineAnarquiaAntiIlegales, Phantom-B-Gone*, ProtocolLib

MineAnarquiaAntiIlegales is a homemade plugin to avoid certain blocks and destroy end portals that are obviously not pre generated by the user. feel free to shreck the code of it in my github

### Paper build number:
git-Paper-27 (MC: 1.16.1)

### Anything else:

anarchy server. illegalstacks is suposed to destroy those weapons once someone equips them....
but also anarchy, so someone could do something again with books or who knows

**Comment by c0d3rb0y** [comment]
Too much NBT data, meaning that the server tried to handle too many NBT tags at once. Lots of enchants, and also lots of Lore? Bound to get some sort of ban. I don't think it's chunkban, unless you placed the shulker and it happened. Gonna need WAY more info.

**Comment by gabboman** [comment]
the only thing i got was a kick from client side, i pasted the only relevant log @c0d3rb0y 

no errors no nothing before the thing happend.

I think  that i got to fix it with illegalstacks, but its slightly... problematic the thing yet. im not sure that that thing was what fixed it

**Comment by aikar** [comment]
fixed in 30+

**Comment by GunacP40** [comment]
How can this be fixed? I have this issue on paper 1.16.5

**Comment by electronicboy** [comment]
Please don't bump random issues, this ticket is likely irrelevant to your actual issue, nor is 1.16.5 supported
