### ISSUE TITLE
[1.16] Pre-1.16 Shulker Boxes Crash Players

### ISSUE THREAD

**Issue by SequaciousGAMES** [PaperMC/Paper#3721]
### What behaviour is expected:
Players to be able to use Shulker Boxes from 1.15.2.

### What behaviour is observed:
 If a player had a Shulker box with NBT data in an inventory [either theirs or in a chest] from 1.15.2, as soon as that inventory is loaded after the 1.16 upgrade the player will crash.
No errors in console other than the player disconnecting.

### Steps/models to reproduce:
- Load up a 1.15.2 Paper server
- Get a Shulker Box that has some form of NBT data [some of these are empty so even placing and breaking one should do]
- Place that shuker box in a chest/hopper/your inventory
- Upgrade the server to a Paper 1.16 build
-- If the Shulker Box is in a container, when you open it you will crash out of the server
-- If the Shulker Box is in your inventory, you will be unable to join the server as you will instantly crash out of it
GIF of this happening: [Example](https://cdn.discordapp.com/attachments/289587909051416579/727309339584626718/hVPwJMDKJB.gif)

### Plugin list:
AdvancedPortals v0.5.5
AnimatedNames v7.3.2
Autorank v4.3.3
BungeeTabListPlus v3.3.0
BuycraftX v12.0.6
ccUnknownCommand v1.16.1-v0.6
ChestShop v3.11 (build 213)
Citizens v2.0.27-SNAPSHOT (build 2019)
CitizensCMD v2.4
CitizensText v1.17.2
CMI v8.7.0.3
CMIPaperLib v1.0.0
CommandCompletionFilter v1.0-SNAPSHOT (build 3)
CommandNPC v1.9.1
CommandSigns v2.2.0
CommandTimer v4.3.1
ConsoleSpamFix v1.8.2
CoreProtect v19.0
CrateReloaded v2.0.28
CustomGUI v2.5.0
DeluxeTags v1.8.1
DisplayShops v1.5.2 (Build 4)
EliteMobs v7.1.25
ExecuteEverywhere v1.2.4-SNAPSHOT
GameruleSync v1.0
HolographicDisplays v2.4.3
Juzdatip v2.0
LibsDisguises v10.0.13-SNAPSHOT
LuckPerms v5.1.29
LWC v2.2.6-2d10269
MaSuiteCore v2.0.1-SNAPSHOT
MaSuiteTeleports v2.0.0
mcMMO v2.1.130
MiniaturePets v2.4.3
MobHeads v3.9
MovingDevApi v1.1.9
Multiverse-Core v4.1.0-b775
Multiverse-NetherPortals v4.1.0-b763
Multiverse-Portals v4.1.0-b805
MVdWPlaceholderAPI v3.0.1
MySQLNicks v1.0.4
NoNetherRoof v1.0.5
NoSpawnerChange v2.1
PacketListenerApi v3.7.6-SNAPSHOT
PerWorldInventory v2.3.1
PlaceholderAPI v2.10.6
PluginLibrary v1.2.4
PlugMan v2.1.7
PremiumVanish v2.5.11
ProCosmetics v10.9.2
ProtocolLib v4.6.0-SNAPSHOT-b464
QuickClose v1.4.9
RegionGUI v4.2.9
SilkSpawners v6.3.1
SimplePets v4.3 (build 13)
TitleManager v2.2.7
Vault v1.7.3
VentureChat v2.19.0
ViaBackwards v3.0.2-SNAPSHOT
ViaCheckConnection v1.2.18
ViaRewind v1.5.1-SNAPSHOT
ViaVersion v3.0.2-SNAPSHOT
VoidGenerator v1.6.0
VotingPlugin v5.22
WorldBorder v1.9.10 (beta)
WorldEdit v7.2.0-beta-01+0eb9ac7
WorldEditGlobalizerBukkit v2.0.2
WorldGuard v7.0.3-SNAPSHOT;2038-9905d22
WorldGuardExtraFlags v4.1.4

### Paper build number:
Paper 1.16.1 Build 27

### Anything else:
I believe a similar issue arose with heads and was fixed in Build 20, I think the same thing may be happening here.

**Comment by ItaySharon** [comment]
+1, Adding to that: It seems as if these shulker box contain an corrupted `Items` nbt tag

Their Items tag is set to the following: `Items:[L;]`

Interestingly enough, only this specific value in the array breaks it

Tried the following (all of them didn't cause this bug):
* `Items:[0L]`
* `Items:[L]`
* `Items:["L"]`
* `Items:["L;"]`
* `Items:[B;]`
* `Items:[]`
* `Items:[0L;]` (Parser marks it as invalid NBT)

EDIT: It seems like player_heads have a similar issue with the Id tag containing `Id:[I; <other data here>]` (See [this](http://prntscr.com/t9c6zh) screenshot)

**Comment by SequaciousGAMES** [comment]
Going to just add to this comment when trying a new build rather than making more;
Edit: [04/07/2020] Can confirm this still happens as of Build 47

**Comment by aikar** [comment]
You're going to have to provide the chunk file because cannot reproduce this, and no one else is seeing this either.

**Comment by SequaciousGAMES** [comment]
> You're going to have to provide the chunk file because cannot reproduce this, and no one else is seeing this either.

Link to Chunk: [Dropbox](https://www.dropbox.com/s/ccedysfk4rb0lcx/r.6.9.mca?dl=0)
Opening any of the hoppers marked with 1.15.2 Shulker seen [here](https://i.imgur.com/W47yQzq.png) crash me out.

As Itay stated above, any with the Items tag set to "Items:[L;]" act corrupted.
They haven't been manually changed, this literally occurred from upgrading from 1.15 to 1.16

**Comment by ghost** [comment]
We got this problem too on 2 of our servers in big survival worlds.
seems to be not chunk depending for me because enderchests containing shulkers causing this issue too.
This is really a big issue for us.. because everyone loves shulker boxes :D

**Comment by ghost** [comment]
@InfinityAspire does this happen to you without a proxy like Bungeecord or Waterfall?

**Comment by SequaciousGAMES** [comment]
> @InfinityAspire does this happen to you without a proxy like Bungeecord or Waterfall?

I'm unable to test that currently but I would assume so. If I manage to test I'll let you know

**Comment by ninetown** [comment]
can confirm, have it with latest 86 paper.

tested without bungee - same

**Comment by ghost** [comment]
After many many hours of testing i found out, that the Proxy (Waterfall) was causing this issue for me..
I was using https://github.com/Exceptionflug/protocolize/releases/tag/v1.6.0 which is causing problem.

**Comment by SequaciousGAMES** [comment]
> After many many hours of testing i found out, that the Proxy (Waterfall) was causing this issue for me..
> I was using https://github.com/Exceptionflug/protocolize/releases/tag/v1.6.0 which is causing problem.

Can confirm this was the issue.
Never would've guessed it. Latest Dev build of Protocolize fixed it.
Closing the ticket.
