### ISSUE TITLE
Disabling Advancements Completely.

### ISSUE THREAD

**Issue by tkn0** [PaperMC/Paper#3723]
**Is your feature request related to a problem? Please describe.**
Yes, as of 1.16 the spigot advancement disabling doesn't seem to disable them completely, only the saving of them when a player leaves.
**Describe the solution you'd like**
I would like a config option to turn off all advancements from firing.
**Describe alternatives you've considered**
I was using spigot.yml to do this but as of 1.16 the feature seems to be broken
**Additional context**
None

**Comment by wizjany** [comment]
Does this work on spigot? If not this sounds more like a bug report for spigot than a feature request for paper. If it works on spigot but not paper, then this is a bug report for paper, not a feature request.

**Comment by tkn0** [comment]
I think it is an issue with spigot that was reported to MD_5 and was marked as resolve but it doesn't seem to be fixed.

**Comment by tkn0** [comment]
Yup, this is a spigot bug :)

**Comment by Puremin0rez** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-5885

The relevant issue is here, but it seems as if it's working as intended. Make sure your spigot.yml is configured properly. You have to configure more than just "disable-saving", you must also disable all the advancements with "*".
```
advancements:
 disable-saving: true
 disabled:
 - '*'
```

Regardless, this isn't a Paper issue

**Comment by tkn0** [comment]
I have that inside of my spigot.yml on a server with only spigot that I just made to test and it still doesn't work

**Comment by electronicboy** [comment]
just tested, it's busted

**Comment by Puremin0rez** [comment]
Confirmed, new issue here: https://hub.spigotmc.org/jira/browse/SPIGOT-5909

**Comment by tkn0** [comment]
Thats ME :)

**Comment by tkn0** [comment]
If you guys could vote for the issue that would be great, my server has memory issues with advancements.
