### ISSUE TITLE
Item names italic in 1.16

### ISSUE THREAD

**Issue by Joiubaxas** [PaperMC/Paper#3725]
### What behaviour is expected:
Item name not being italic

### What behaviour is observed:
Item name is italic for no reason

### Steps/models to reproduce:
Giving a player an item with a custom colored name. When using paper for some reason the name is italic, spigot 1.16.1 works as usual.

### Paper build number:
Paper-27

**Comment by EazyFTW** [comment]
#3683

**Comment by aikar** [comment]
see linked ticket, this is duplicate
