### ISSUE TITLE
Wrong slabs determine

### ISSUE THREAD

**Issue by MintyRoma** [PaperMC/Paper#3726]
### What behaviour is expected:
When use getType() on any new slabs it should return Material.STEP.

### What behaviour is observed:
When use getType() on any new slabs it returns Material.AIR.

### Steps/models to reproduce:
1. Place in world any new slabs as example stone slab or crimson slab.
2. In plugin try to get block located in place of slab.
3. Try to get type of block by getType(). You will get Material.AIR

### Plugin list:
Custom self-writed plugins

### Paper build number:
Paper #27 1.16.1

**Comment by electronicboy** [comment]
You need to set the api-version in your plugin.yml
