### ISSUE TITLE
Inconsistancy with itemstack naming

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3727]
### What behavior is expected:
An item from 1.15.2 named "§aSword of Destiny" to be named "§aSword of Destiny" after updating to 1.16.1

### What behavior is observed:
It seems half of the item's names have remained the same using chat colors as expected and the other half have been turned into very long text components which when viewed in an NBT viewer show as  `{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Sword of Destiny"}],"text":""}"` This has resulted in players of my server being unable to stack these two types of items or trade them with merchants.

### Steps/models to reproduce:
Retrieving an itemstack from YAML on 1.16.1 always results in them having a buggy text component name, putting an itemstack with chatcolor name into a chest on 1.15, upgrading to 1.16 then opening it will result in the item remaining the same.

### Paper build number:
paper 1.16.1 ver 27, ver 34

**Comment by aikar** [comment]
the new format is expected. where were the items that DIDNT change to that stored?

Is it ones that were in player inventory, and only ones that you touched some plugin level state that got changed?

**Comment by ghost** [comment]
The items that were in echests/player inventories were not converted to the long chatcodes, i think you should either datafix all these long components back to chatcodes or all the chatcodes into components

**Comment by aikar** [comment]
They are all components. There are no chat codes stored. The issue is mojang changed rendering, and Spigot has to add instructions to change the clients rendering.

not really an easy fix here. cant add dfu's once youve already converted your world.

**Comment by BillyGalbreath** [comment]
> not really an easy fix here. cant add dfu's once youve already converted your world.

I've tried showing you my [fix for this](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0095-Convert-legacy-item-text.patch) a couple times now. Was hoping to get some feedback to make it better before PR'ing it here, but it works as-is.

**Comment by ghost** [comment]
Yup, just tested it. If you are a 1.15.2 player and login to 1.16.1 your items in enderchest and inventory are still chatcolor while the items deserialized from yaml are componented

**Comment by aikar** [comment]
@BillyGalbreath the patch looks like an ok change for even older data, however it doesn't solve this specific users issue.

Your patch will convert legacy color codes in components, but that's not what this ticket is about (and im not sure what scenario should still exists for that case either)

This ticket is about taking components and adding italic: false and other modifiers to the component at the first color code/reset.

**Comment by BillyGalbreath** [comment]
> This ticket is about taking components and adding italic: false and other modifiers to the component at the first color code/reset.

Ok, made a new issue #3740 and pr #3741 for what I was talking about. I thought this ticket was the same thing.
