### ISSUE TITLE
Book enchantments

### ISSUE THREAD

**Issue by LeCraft2Ouf** [PaperMC/Paper#3728]
Good evening,

Please excuse me for this English made with the help of a translator.

I noticed that when I put an enchanting book in my hotbar the book remains shiny but has no more enchantments. This is a big problem since we can no longer use it in an anvil.

I also noticed, that its doing the same with the potions, they lose their effects.

I noticed that it only occurs in creative gamemode

Would you be so kind as to help me? I sincerely thank you for your work.

cordially

**Comment by LeCraft2Ouf** [comment]
Fix

**Comment by Machine-Maker** [comment]
Unable to reproduce on build 43 (1.16.1). I basically opened creative inventory, grabbed an enchanted book, moved over to the inventory view, and moved it between my inventory and hotbar. Still had the enchantments.

**Comment by LeCraft2Ouf** [comment]
Yes sorry the problem came from a plugin. I marked resolved

**Comment by Machine-Maker** [comment]
Oh, hit the "Close issue" button at the bottom of the page to change it from open to closed.

**Comment by LeCraft2Ouf** [comment]
Ah damn, thank you I think we could not manually ^^
