### ISSUE TITLE
Item duplication on dimension change with hoppers and chest minecarts

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#373]
Hopper push option allows duplicating of items with chest minecart into nether with hopper outside exit

Only works with
hopper:
      push-based: true

Create nether portal
Create rail track that leads into portal
Put minecart with a chest in it, insert non-stackable item
Inside the nether, put a hopper outside the exit where minecart will land
Go back out, push minecart with the chest in it and item through the portal
Go back into nether, hopper will now contain two of the item instead of one

Setting to false fixes it

Literally no plugins, tested on empty local server
Build 819

**Comment by zachbr** [comment]
Should be fixed in Builds 820+

**Comment by ghost** [comment]
Build 820

Still works, but now with stackable items, only difference is another player has to be inside the nether to keep it loaded (which I'm assuming is what makes this work)

demonstration video, skip to 5:08
https://www.youtube.com/watch?v=wLWgCtBRZoI

**Comment by zachbr** [comment]
@Techcable open to your thoughts on this,  bug me in IRC later when you have some free time

**Comment by zachbr** [comment]
Need third-party verification that this only occurs with hopper-push set to true, and that it won't work with the feature disabled.

Thinking this may be related to their inactiveTick with the feature enabled, but that's preliminary at this point.

**Comment by jordanwilliams1** [comment]
Just caught a player doing this, Sadly I've had to disable hopper-push (this stops the glitch).

Video on how to do the glitch: (Upload by me)
https://www.youtube.com/watch?v=4pfBi69z42A&feature=youtu.be&ab_channel=JordanWilliams
![15fa650f0caaa42e9483ac78ff31e3c0](https://cloud.githubusercontent.com/assets/16514150/17199955/1c0b9164-5479-11e6-893b-69a080ac4a71.png)

**Comment by WonderDave** [comment]
For what it's worth, I just tried this with Paper 821.  It only worked when the "hopper.push-based" setting was 'true'.  When I set it to 'false', this glitch did not work for me and nothing was duplicated.

I set this up without having a second player in the nether.  I just told Multiverse to keep the spawn area of the nether always loaded.  Also, I don't know how the glitch works for others, but for me, it would make only one extra copy of an item, and only of the item that I had in the top-left-most chest slot.  I didn't try filling more than the two top-left slots, so maybe someone else would be able to get more than one duplicate item with each pass through the portal.  The two items I used for testing were a beacon and a command block.

**Comment by Techcable** [comment]
This bug seems very odd, since the hopper should remove the item immediately after it sucks it in.
Maybe there's a bug in our `EntityMinecartContainer.acceptItem(TileEntityHopper)` logic?

Could this also have something to do with the fact that minecraft creates a different entity object when the hopper changes worlds?

**Comment by ghost** [comment]
any updates about this? would like to use the option again, awful lag from hoppers with it off :(

**Comment by jordanwilliams1** [comment]
> any updates about this? would like to use the option again, awful lag from hoppers with it off :(

**Comment by zachbr** [comment]
In builds 864+, Minecarts cannot travel through portals once this setting is enabled.
This mitigates the issue, and being that most of you likely don't care about Minecarts going through portals anyway, it's a good workaround for the time being.
