### ISSUE TITLE
[1.16] Not obvious documentation for PreCreatureSpawnEvent behaviour

### ISSUE THREAD

**Issue by imDaniX** [PaperMC/Paper#3730]
This is repost of an issue from my plugin - https://github.com/imDaniX/Dangerous-Caves-2/issues/23

### What behaviour is expected:
Event working _almost_ like a CreatueSpawnEvent, but with better performance and a bit less accurate.

### What behaviour is observed:
Event is fired randomly in walls and on the surface on day time(with checking EntityType for zombies, skeletons etc.)
[Video](https://www.youtube.com/watch?v=plteCs5CUto).

### Steps/models to reproduce:
Just try to listen for PreCreatueSpawnEvent and do something on its spawning location.

### Plugin list:
DamageIndicator, Essentials(Spawn,Chat), DangerousCaves

### Paper build number:
git-Paper-24

### Anything else:
This doesn't occur with CreatureSpawnEvent. Was working just fine on 1.15.2

**Comment by chickeneer** [comment]
If you are wanting to do something "on its spawning location". You need to use the CreatureSpawnEvent.
Keeping this issue open, as the documentation api needs updated.
This event fires even for a spawn that is going to fail later. If I recall correctly, it was added as a way to tell the server earlier in the spawning cycle to stop a mob spawn before more expensive logic is checked for that location, such as whether it 'fits' in a space (hence the walls/daytime)

**Comment by imDaniX** [comment]
@chickeneer, thank you for informing. Didn't expect this change on the first place.
