### ISSUE TITLE
It is not immediately clear that the "worldborder set" command only affects one dimension

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3731]
### What behaviour is expected:
The world border size set by the vanilla command `worldborder` is matched in all dimensions (Overworld, Nether, and End) ~~OR if Paper is supposed to allow the size to be different in each dimension, have an option in the `worldborder` command to specify a world (example new syntax: `worldborder set [diameter] [time] [world]`)~~ **This can already be done with `execute in minecraft:the_end` or `execute in minecraft:the_nether`**

### What behaviour is observed:
Running the `worldborder set [number]` command from console changes the world border size in the Overworld. However, the size is not changed in the Nether nor the End; ~~there is no apparent way to set the world border size in these dimensions without logging into the server and teleporting to these dimensions yourself.~~ There is also no indication when setting the world border size from the console that it is only doing so in the Overworld.

### Steps/models to reproduce:
1. Download the paper jar and start up a fresh server (no prior world required)
2. In the console, type `worldborder set 50`
3. In game, login to the server.
4. Observe the world border with a diameter of 50 blocks in the Overworld. You can also see this size with the `/worldborder get` command (if necessary, OP yourself using the console).
5. In game, teleport to the Nether (e.g. op yourself using the console then type `/setblock ~ ~ ~ minecraft:nether_portal` in game to quickly make a portal). You can also go to the End if you'd like (`/setblock ~ ~ ~ minecraft:end_portal`).
6. Observe that the world border with a diameter of 50 blocks in the Nether or End is missing. The `/worldborder get` command in-game at this point will show that the world border is of the default size (60,000,000 blocks)

### Plugin list:
None

### Paper build number:
```
This server is running Paper version git-Paper-27 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
```

### Anything else:
The behavior in vanilla singleplayer (as tested by running `/worldborder set 50` in a singleplayer world in the Overworld then going to the Nether and observing the worldborder) is to match the world border size across all dimensions.

**Comment by Prof-Bloodstone** [comment]
What about `execute in world_the_end run worldborder set 50` - I think I used that for my server, but can't confirm it now.
I believe on wiki it says that it's per world command.

**Comment by ghost** [comment]
> What about `execute in world_the_end run worldborder set 50` - I think I used that for my server, but can't confirm it now.

Ah, it does work (with `in minecraft:the_end` instead though), my apologies. 

> I believe on wiki it says that it's per world command.

I couldn't find that by searching for "world border" in the docs (https://paper.readthedocs.io/en/latest/search.html?q=world+border&check_keywords=yes&area=default#). There's a section that says "World settings are configured on a per-world basis" but that seems to be referring to the world settings in `paper.yml`, not things like the world border. I think that at the very least, something could be added to the documentation to prevent confusion about the per-world border.

I'll edit the original issue and the title to reflect this.

**Comment by aikar** [comment]
These are vanilla commands. Please give suggestions for vanilla commands to Mojang.

**Comment by ghost** [comment]
> These are vanilla commands. Please give suggestions for vanilla commands to Mojang.

I believe that the issue here is that the behavior of the vanilla command differs in Paper (in vanilla, it changes the border for all dimensions. In Paper, it changes the border only in the dimension you are in or the Overworld by default). Is this intentional and/or documented (I couldn't find a relevant wiki page)?

**Comment by aikar** [comment]
Oh, I guess that is true, but no there is no where to document that. its a long time behavior of having the ability to support more than the default worlds. 

the general goal is that all world based commands only operate on a single world.
