### ISSUE TITLE
[1.16] Server crash: Waiting for a chunk that never loads

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#3736]
### What behaviour is expected:
It should load the chunk when setting blocks via the api

### What behaviour is observed:
Sometimes chunks do never load and the server crashes

### Steps/models to reproduce:
The plugin is editing some blocks in a world and loading some chunks to do that.

### Plugin list:
-

### Paper build number:
This server is running Paper version git-Paper-29 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
Crash/Stacktrace: https://pastebin.com/raw/PmDnyjBd

**Comment by Chew** [comment]
Please provide a plugin list :heart:

**Comment by Brokkonaut** [comment]
The plugin list is not really relevant because the only plugins here are custom ones. But you can see from the stack trace that the plugin is trying to set a block in a sync BukkitRunnable, this triggers the internal physics and tries to load a chunk - but that one never loads.

One thing that might be relevant in this case is that the world where where plugin changes blocks is just loaded by that plugin a few ticks earlier and has setKeepSpawnInMemory(false) . There are no exceptions in the server log before the crash.

**Comment by panpawn** [comment]
Getting the same kind of crash: https://pastebin.com/raw/cDf0FHCE
