### ISSUE TITLE
End Gateway will not be created upon Dragon Death

### ISSUE THREAD

**Issue by nebula-a** [PaperMC/Paper#3737]
### What behaviour is expected:
That a new gateway would be created each time the dragon dies - there are currently 4 in my world so there's plenty of room.

### What behaviour is observed:
No new gateway appeared when the dragon was defeated.

### Steps/models to reproduce:
• Defeat the dragon once
• Defeat it at most 3 more times after re-spawning it.
• Observe the number of end gateways each time.

### Plugin list:
Plugins (13): CoreProtect, DiscordSRV, EntityChecker, EzFilter*, LuckPerms, LuckPermsChat, NoCreeperGrief, OpenInv, PlugMan, spark, StaffChat, SuperbVote, Votifier
Note: StaffChat is developed by me for my server and is chat-related only.

### Paper build number:
24

### Anything else:
Not that I can think of - possibly how the dragon fight is coded but that's all I can say as you develop this.

**Comment by nebula-a** [comment]
Note: The plugin EntityChecker is also coded by me and only adds a small entity-counting command. NoCreeper grief is too and empties the block list of an explosion.

**Comment by kickash32** [comment]
Did you upgrade this world from 1.15.2 or older?

**Comment by nebula-a** [comment]
> Did you upgrade this world from 1.15.2 or older?

yes, but all the chunks are upgraded

**Comment by DerekWearmouth** [comment]
Also having this issue with my 1.15.2 migrated world.

**Comment by nebula-a** [comment]
Any solutions if this isn't a bug..?

**Comment by DerekWearmouth** [comment]
> Any solutions if this isn't a bug..?

We ended up fully resetting the end file to fix this issue..

**Comment by ghost** [comment]
I have a similar issue, but the ender dragon is not spawned, and the perch for the dragon which has a portal is also not spawned. It's basically an empty end... I tried many recent builds, none of which helped with this.

**Comment by legacy2355** [comment]
I am also having this issue. 1.15.2 migrated to 1.16.1. The level.dat changed, is it somehow due to this?
