### ISSUE TITLE
1.16.1: Zombified Piglins not dropping Gold ingots

### ISSUE THREAD

**Issue by ChrisElfvius** [PaperMC/Paper#3738]
### What behaviour is expected:
Gold ingots dropping from Zombified Piglins when dying in an afk farm(does work on regular minecraft 1.16.1)

### What behaviour is observed:
Zombified piglins do not drop gold ingots

### Steps/models to reproduce:
Made a gold farm platform above bedrock in the nether. 

### Plugin list:
LuckPerms, CustomEnderChest, Sickle, TreeFeller, Vault, ChestSort, Essentials, EssentialsGeoIP, EssentialsChat, EssentialsAntiBuild, EssentialsSpawn, Harbor, EssentialsXMPP, EssentialsProtect (I've tried without any plugins installed as well)

### Paper build number:
git-Paper-32 (MC: 1.16.1)
(Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
No clue tbh :(

**Comment by alexmartz710** [comment]
Having this bug as well, also replicated it with no plugins on git-Paper-32 and it still doesn't drop any gold ingots when afk farming them.

**Comment by Ubergoobernator** [comment]
This is a problem of the base Spigot code...as it is plaguing Spigot servers right now.

**Comment by ChrisElfvius** [comment]
I helped getting it fixed on the spigot forums, but still doesnt work with paper
Will swap to spigot for now.

**Comment by Machine-Maker** [comment]
If its fixed on spigot, when upstream is updated, itll get fixed here.

**Comment by Ubergoobernator** [comment]
Chris, Paper is a fork of Spigot much like Spigot is a Fork of Bukkit.  It all flows down.

**Comment by aikar** [comment]
fixed in latest

irony is, this is reintroducing a bug mojang wants to fix :(
Wanting to verify if mojangs actually the one that fixed it.
