### ISSUE TITLE
ConcurrentModificationException / Light Engine Error

### ISSUE THREAD

**Issue by mk3ext** [PaperMC/Paper#3739]
Was told by kickash32 to create an issue

### Link/paste of stack trace

[https://hastebin.com/yecisetawu.md](https://hastebin.com/yecisetawu.md)

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
     EpicWorldGenerator
     WorldBorder
     CMI
     ChunkMaster
     WorldEdit
     WorldGuard

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
Paper-372 (MC: 1.15.2)

**Comment by Proximyst** [comment]
Given we're now quite a few light changes later, please reproduce this and report it again if it still happens.
Thank you for the issue nonetheless!
