### ISSUE TITLE
Elytra goes invisible when equipped with enchanted armor.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#374]
Paper 819

If you have an elytra equipped and equip an enchanted piece of armor, the elytra goes invisible. And then if you toggled to any item in your hotbar, it reappears. Cool effect, but probably not intended. Makes elytra look like transparent butterfly wings and shimmers if enchanted with durability. :P

**Comment by WonderDave** [comment]
This is a vanilla bug:  [https://bugs.mojang.com/browse/MC-99353](https://bugs.mojang.com/browse/MC-99353)

**Comment by zachbr** [comment]
Pretty sure this is an issue with the client.

**Comment by mibby** [comment]
Hrm, alright. I'll close the ticket. Quite an odd client bug. :P

**Comment by zachbr** [comment]
Pretty cool effect though, but likely a side-effect of how enchantments get rendered in-game conflicting with how elytra are rendered.
