### ISSUE TITLE
Legacy ItemStack names and lore do not update to match 1.16 standards

### ISSUE THREAD

**Issue by BillyGalbreath** [PaperMC/Paper#3740]
### What behaviour is expected:
Old items from 1.15.2 to have their names and lore updated when loaded in 1.16

### What behaviour is observed:
Old items from 1.15.2 keep their legacy names and lore when loaded in 1.16

### Steps/models to reproduce:
1) Run the attached plugin on a 1.15.2 server.
2) You will receive a cookie with a colored name on join.
3) Upgrade that server to 1.16 and run again.
4) You will receive another cookie with a colored name on join.
5) These cookies will not stack, and if you examine the items in the player.dat file you will see exactly why.

### Plugin list:
Only this test plugin.

### Paper build number:
Any 1.16 build

### Anything else:
Not only does this make these itemstacks not stack, but it messes up any plugin that relies on unique itemstack names and/or lore (like a crate key plugin).

Here's the test plugin:

[TestPlugin.jar.zip](https://github.com/PaperMC/Paper/files/4859198/TestPlugin.jar.zip)

```java
public class TestPlugin extends JavaPlugin {
    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(new Listener() {
            @EventHandler
            public void onJoin(PlayerJoinEvent event) {
                getServer().getScheduler().runTaskLater(TestPlugin.this, () -> {
                    ItemStack item = new ItemStack(Material.COOKIE);
                    ItemMeta meta = item.getItemMeta();
                    meta.setDisplayName(ChatColor.RED + "Nom Nom Nom");
                    item.setItemMeta(meta);
                    event.getPlayer().getInventory().addItem(item);
                }, 20);
            }
        }, this);
    }
}
```

Here's a screenshot of the items in player.dat using NBTExplorer:

![image](https://user-images.githubusercontent.com/332527/86269822-e9799c00-bb8f-11ea-9e11-3cc7b1022c55.png)

First item is 1.16 generated. Second item is 1.15.2 generated. They are out of order because I tried to stack them and that's just the order they ended up after clicking a bunch.

**Comment by UltraFaceguy** [comment]
Support for fixing this - all of my code that relies on ItemStack#isSimilar is now busted
