### ISSUE TITLE
 Ender Dragon getting stuck in unloaded chunks (papermc 1.16.1 build 23, 4 people in the end, survival, hard)

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3744]
### What behaviour is expected:
___What you expected to see___
Ender dragon supposed to be moving and flying
### What behaviour is observed:
___What you actually saw___
Enderdragon getting stuck in unloaded chunks not being able to get itself out (we werent able to do damage to it when it was stuck as well)
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___
worldedit, multiverse nether portal, multiverse, multiverse core, multiverse, slime fun, laggremover, limit pillagers, neterualnetworkAPI, multiverse sign, 
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
papermc build 23
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by NerdyKyogre** [comment]
Can confirm, also with Multiverse, build 34. Also occurs if dragon goes above build height: I had one stuck at y260. What happens when you hit it? For me I took crazy knock back but was able to damage the dragon.

**Comment by ghost** [comment]
We were on the ground and shot it with bows, the shots were hitting it but no damage was being done, eventually I had to fly up and load chunks the dragon was stuck in but then the dragon would fly into another unloaded chunk and get stuck,

**Comment by kickash32** [comment]
What is your view distance in the end?

**Comment by ghost** [comment]
the server had been set to a view distance of 16

**Comment by ghost** [comment]
I had found that a Datapack called Nolag was causing the unloaed chunks to appear, when I deleted it, this fixed the dragon but I havent tested it for other mobs
