### ISSUE TITLE
Repeated Curing of Villagers does not reflect Vanilla Behavior

### ISSUE THREAD

**Issue by Arkdirfe** [PaperMC/Paper#3745]
### What behaviour is expected:
If a villager is zombified and cured multiple times in a row it results in incrementally increasing discounts.

### What behaviour is observed:
Zombifying and curing a villager multiple times acts as if the villager was zombified and cured once with no further reductions possible.

### Steps/models to reproduce:
Spawn a villager and a zombie, wait for the zombie to kill the villager, then cure it. Repeat. The prices will not change after the first time.

### Plugin list:
AdvancedAchievements, ArmorStandEditor, AsyncWorldEdit, AsyncWorldEditBossBar, AuctionHouse, BetterFarming, ChatReaction, ChestSort, Citizens, CitizensCMD, CMI, CMIPaperLib, CoreProtect, CraftingStore, CrateReloaded, DeluxeChat, DeluxeMenus, DungeonsXL, dynmap*, EliteEnchantments*, EnchantmentBook, EntityTrackerFixer, EpicHoppers, EZPrestige*, EZRanksPro, FeatherBoard*, GemsEconomy*, GlowAPI*, GriefPrevention, HeadDatabase*, HolographicDisplays, ItemFilter, LibsDisguises, LimitPillagers, LiteBans, LuckPerms, mcMMO, MineCrates, Minepacks, MobFarmManager, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, MythicMobs, MythicMobsExtension, NBTAPI, PacketListenerApi*, PinataParty, PlaceholderAPI, Plan, PlayerWarps, PlugMan, ProtocolLib, SafariNet, ShopChest, ShopGUIPlus, spark, SpigotGuard, StaffFacilities*, TAB, TokenEnchant, TradeSystem, Vault, VillagerOptimiser, VoidGenerator, Votifier, VotingPlugin, Wild, WildStacker, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
git-Paper-30 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by BillyGalbreath** [comment]
Sounds like an unintentional bug fix. I like it ^_^

**Comment by Proximyst** [comment]
> VillagerOptimiser

Reproduce without plugins, especially without plugins that touch villagers.

**Comment by Arkdirfe** [comment]
Well, it seems like it does work without plugins. Sorry for the inconveninece, the bug just started appearing around the time we updated. Binary search time.

**Comment by VincentAdvocaat** [comment]
@Arkdirfe did you ever figure out which plugin caused this?

**Comment by Arkdirfe** [comment]
@VincentAdvocaat Yes, it was SafariNet, and admittedly due to a weird usage by me. What I did for testing was zombify the villages, then use the net to move them, then cure them (which was the exact "survival" use case we had on the server). It turns out that the net didn't properly save the villager's cure-related data, thus causing it to never go above one cure.
