### ISSUE TITLE
An optimization suggestion.

### ISSUE THREAD

**Issue by suoyukii** [PaperMC/Paper#3749]
**Describe the solution you'd like**

- Stop mob generation when the server's CPU usage or memory usage reaches below a value.
- Turn on mob generation when the server's CPU usage or memory usage reaches below a value.

Just add two setting options to the configuration of Paper.
This feature can effectively prevent server latency caused by high CPU usage or high memory usage.

**Comment by HexedHero** [comment]
CreatureSpawnEvent

if (Bukkit.getTPS[0] <= 19.99)
{

event.setCancelled(true);

}

**Comment by suoyukii** [comment]
It is recommended to set a global variable, and then use timer timing to determine whether to turn on mob generation. When the system wants to generate mob, it only needs to judge this global variable.

**Comment by kickash32** [comment]
A Plugin can easily achieve this by setting mob limits to 0 for however many ticks it wants based on the tps. However mob spawn lag usually only happens due to a bad config.

**Comment by Proximyst** [comment]
This is plugin territory. (Ab)use https://papermc.io/javadocs/paper/1.16/org/bukkit/World.html#setAnimalSpawnLimit-int-
