### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#375]
### Timings or Profile link:

https://timings.aikar.co/v2/?id=ff6838074b7b4af998ed0b24410b2a9d
### Crash, Stacktrace

http://pastebin.com/f4PKXBB8
and
http://pastebin.com/2S16xZ5M

**Comment by zachbr** [comment]
Still seeing this as of latest?

**Comment by zachbr** [comment]
Mm this is actually a duplicate of GH-313. Going to update that issue and close this one.
