### ISSUE TITLE
EntityTargetLivingEntityEvent does not fire for new mob types.

### ISSUE THREAD

**Issue by BigScary** [PaperMC/Paper#3752]
### What behaviour is expected:
Cancellable EntityTargetLivingEntityEvent fires when all entities target a living entity (like a player).  This has been and still is true for older mob types like creepers.

### What behaviour is observed:
This event is not firing for hoglins, zoglins, piglins, or zombified piglins.  Maybe others but not that I have noticed so far.

### Steps/models to reproduce:
Subscribe to this event and console output event.getentitytype().name().  Then spawn that creature type near a survival mode player.  You will see the targetting and attack, but nothing will output to console.  Contrast this with spawning a creeper, and you will see the output.

### Paper build number:
This server is running Paper version git-Paper-29 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by Machine-Maker** [comment]
Yeah, confirmed on build 41. 

It seems these new mobs aren't using the target pathfinding goal, but are using something else, so theres nothing firing the event for target changes.
