### ISSUE TITLE
Legacy lore is improperly converted

### ISSUE THREAD

**Issue by SoSeDiK** [PaperMC/Paper#3757]
### What behaviour is expected:
Properly converted lore.

### What behaviour is observed:
`§eTest§bLore!` displays as `§eTest§b§oLore!`:
https://imgur.com/wtxQaWq

### Steps/models to reproduce:
Create an item:
```
ItemStack item = new ItemStack(Material.COOKIE);
ItemMeta meta = item.getItemMeta();
meta.setLore(Collections.singletonList(ChatColor.YELLOW + "Test" + ChatColor.AQUA + "Lore!"));
item.setItemMeta(meta);
```
Check NBT:
`{display:{Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Test"},{"color":"aqua","text":"Lore!"}],"text":""}']}}`
The first part is fine while the other components won't be.

### Plugin list:
Only a test plugin that creates an item.

### Paper build number:
Paper build 41, 1.16.1.

**Comment by Machine-Maker** [comment]
Yeah, I reproduced this. I'm pretty sure it was caused by fb772923d5bbc6c53d18370f5bcd4083567f6035. Basically that changed the formatting system so it doesn't reset if its parent was already false, issue is. Lore defaults to italics.

**Comment by Machine-Maker** [comment]
Yeah, I reproduced this. It was caused by fb772923d5bbc6c53d18370f5bcd4083567f6035. I think Aikar tried to reduce the size of serialized metas by not including the full reset of text. But since the default for lore is italics, it broke it.

**Comment by aikar** [comment]
this was a duplicate ticket but this is mitigated now
