### ISSUE TITLE
add aincent_debris to the default hidden-blocks in the anti-xray engine

### ISSUE THREAD

**Issue by machineonamission** [PaperMC/Paper#3758]
**Is your feature request related to a problem? Please describe.**
My friend recently xrayed for aincent debris and i didn't think he would because i enabled paper's anti-xray plugin

**Describe the solution you'd like**
add aincent_debris to the default hidden-blocks list in config within anti-xray

**Describe alternatives you've considered**
I can manually add it to the list

**Comment by wizjany** [comment]
#3665 please use search

**Comment by machineonamission** [comment]
i may be stupid
