### ISSUE TITLE
Expose nms entity's isInWater() & aG() ["is in lava"]

### ISSUE THREAD

**Issue by jaylawl** [PaperMC/Paper#3761]
**Is your feature request related to a problem? Please describe.**
The boolean methods `isInWater()` and `aG()` (is in lava) already exist in nms' Entity.class

**Describe the solution you'd like**
Please expose these methods as API to prevent having to cast to NMS entity for this

**Comment by Machine-Maker** [comment]
#3762

**Comment by jaylawl** [comment]
Closing because it was successfully added (thanks again!)
