### ISSUE TITLE
Where could I find hashes of release .jars?

### ISSUE THREAD

**Issue by boner-cmd** [PaperMC/Paper#3767]
I use the Paper release .jar in a Minecraft server that I run in a Docker container. As a sanity check, I verify the hashes or signatures of all the files I download when building the container. Is there somewhere I can download the hashes of the release files on [the download page](https://papermc.io/downloads)? I see that releases are tied to commits, but I'm not sure where to look.

I posted as a feature request because I don't think it exists, but I'm not sure I didn't just overlook a similarly verifiable piece of information.

**Comment by VADemon** [comment]
https://papermc.io/ci/job/Paper-1.16/43/artifact/paperclip-43.jar/*fingerprint*/

Or use Jenkins API (only for the brave)

**Comment by danny6167** [comment]
Jenkins is planned to go away at some point. Perhaps the MD5/SHA could be added to the download page and the download API ?

**Comment by MiniDigger** [comment]
https://papermc.io/api/v1/paper/1.16.1/latest would be the proper way (https://papermc.io/api/v1/paper/1.16.1/latest/download for the file), but it doesnt include signatures right now.
I suggest to open an issue here https://github.com/PaperMC/Parchment

**Comment by boner-cmd** [comment]
Okay, I'll use Jenkins for now and [open an issue](https://github.com/PaperMC/Parchment/issues/5) on Parchment! Thanks!
