### ISSUE TITLE
END Portal not teleport to end world

### ISSUE THREAD

**Issue by myavuzokumus** [PaperMC/Paper#3769]
### What behaviour is expected:
When using normal spigot, there is no problem, but when I use the paper version, I cannot go to the end world from the end portal.

### Paper build number:
![image](https://user-images.githubusercontent.com/47111280/86439357-1bfed280-bd11-11ea-9d00-baadc6c00639.png)

**Comment by Machine-Maker** [comment]
Unable to reproduce. I created a new world, located the nearest stronghold, finished the portal, went through, and I was in the end.

**Comment by myavuzokumus** [comment]
![image](https://user-images.githubusercontent.com/47111280/86446120-2a062080-bd1c-11ea-8dc1-3bfd92f158d6.png)

**Comment by myavuzokumus** [comment]
Ok maybe this problem with nether world. I don't know absolutely. But in 1.15.2 version, not have this problem.

**Comment by MrEDok** [comment]
Do you have end disable in your config? Any plugin that block portal teleport?

**Comment by myavuzokumus** [comment]
Level-world: world, end world its disable. This another world and have end world.
Other question, no.

**Comment by myavuzokumus** [comment]
Ok, i think thats problem not cause by paper. I closing issue now.

**Comment by myavuzokumus** [comment]
OK I found the problem. The problem is caused by the "allow-end" setting in bukkit.yml. But when you turn this off, you are blocked from entering the end world, which is managed by another plugin. More precisely, when it closes this, it closes the work of the end portal. I request that this setting be turned off only for "level-world".

**Comment by Machine-Maker** [comment]
I think the allow-end setting should probably stay as it is. To me, it makes sense, that if allow end was turned off, end portals wouldn’t work.

**Comment by myavuzokumus** [comment]
Yeah, already. But in 1.15 version not have this issue.

**Comment by myavuzokumus** [comment]
Problem fixed by spigot build.
