### ISSUE TITLE
Chunks not unloading (inactive & border state)

### ISSUE THREAD

**Issue by Rincewind34** [PaperMC/Paper#3771]
###  Timings or Profile link:
https://timings.aikar.co/?id=c7eb2deef2ec406381f53ba7916bf3f9

### Description of issue:
After 30 Minutes with no player on the server, there are still some chunks in the state "inactive" and "border". Is there anything I can do to unload them? I tried to find out, what "inactive" and "border" exactly mean to fix it my self, but wasn't able to find an explanation.

> paper chunkinfo
[12:20:44 INFO]: Chunks in altewelt:
[12:20:44 INFO]: Total: 934 Inactive: 309 Border: 625 Ticking: 0 Entity: 0
[12:20:44 INFO]: Chunks in utilityTag:
[12:20:44 INFO]: Total: 0 Inactive: 0 Border: 0 Ticking: 0 Entity: 0
[12:20:44 INFO]: Chunks in utilityNacht:
[12:20:44 INFO]: Total: 0 Inactive: 0 Border: 0 Ticking: 0 Entity: 0
[12:20:44 INFO]: Chunks in dungeonTag:
[12:20:44 INFO]: Total: 0 Inactive: 0 Border: 0 Ticking: 0 Entity: 0
[12:20:44 INFO]: Chunks in dungeonNacht:
[12:20:44 INFO]: Total: 0 Inactive: 0 Border: 0 Ticking: 0 Entity: 0
[12:20:44 INFO]: Chunks in flatmap:
[12:20:44 INFO]: Total: 1011 Inactive: 386 Border: 625 Ticking: 0 Entity: 0
[12:20:44 INFO]: Chunks in treePack:
[12:20:44 INFO]: Total: 0 Inactive: 0 Border: 0 Ticking: 0 Entity: 0

### How I got there
- Server started (at this point there where no chunks loaded)
- Joined the server into the world "flatmap"
- Used the tp command to teleport a few thousand blocks away from my current location
- Switched the world to "altewelt"
- Disconnected

### Plugin list:
AerionArenaFight, AerionBowTraining, AerionBrewing, AerionClassSystem, AerionCollections, AerionDiscoverySystem, AerionDungeonSystem, AerionEconomicSystem, AerionFeedbackSystem, AerionFishing, AerionGroup, AerionMinigames, AerionNPCManager, AerionObelisk, AerionPathFinder, AerionQuestSystem, AerionQuestUtilities, AerionServerAPI, AerionShipControl, AerionShopSystem, AerionTradingSystem, AerionUInterface, AerionUtilities, AerionWarp, AsyncWorldEdit, BetterCommands, Citizens, FastAsyncWorldEdit, FlySpeed*, HeadDatabase*, Holograms, InterfaceAPI, LibsDisguises, LuckPerms, MythicMobs, NoteBlockAPI*, ProtocolLib, SpiderMySQL*, VoxelSniper*, WanderingNPC*, WorldEdit, WorldEditSUI, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
Properties: https://pastebin.com/d8xT8RY4
Bukkit: https://pastebin.com/tf8vJAdq
Spigot: https://pastebin.com/sj7hsPCS
Paper: https://pastebin.com/4NRzaANz

### Other helpful links
Sync Chunk Info: https://pastebin.com/1TArBEz1
Chunk debug: https://pastebin.com/Wp9Ypswj (was a bit too long, so only the first 10.000 lines)
How many chunks are queued to be unloaded: 0 (cat ./debug/chunks-2020-07-03_12.26.20.txt | grep "\"queued-for-unload\": true" | wc -l)

### Paper build number:
> version
This server is running Paper version git-Paper-39 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-655 (MC: 1.13.2)
You are 5 version(s) behind

**Comment by BeastPsycho** [comment]
Chunks loading server crash for spigot too, papers seems not fix it
I can see extreme tps drop due for Entity handling, and chunk loading

**Comment by aikar** [comment]
border is simply a non ticking chunk, inactive is sometimes normal, inactive is in memory but not loaded.

was this command ran immediately after logout? it does take some time to 'flush' the chunks, but they usually do unload when all are done.

spawn chunks will keep chunks loaded too.

however there are some known quirks that the chunks can get desynced and not unloaded correctly, so im gonna leave this open as id love to be able to fix it but no clue how yet.

**Comment by Rincewind34** [comment]
> border is simply a non ticking chunk, inactive is sometimes normal, inactive is in memory but not loaded.
> 
> was this command ran immediately after logout? it does take some time to 'flush' the chunks, but they usually do unload when all are done.
> 
> spawn chunks will keep chunks loaded too.
> 
> however there are some known quirks that the chunks can get desynced and not unloaded correctly, so im gonna leave this open as id love to be able to fix it but no clue how yet.

I've checked in 30 minutes after disconnect, and it didn't change the loaded chunks. The spawn chunks are disabled and there are no chunks loaded on server start. So the spawn chunk settings seem to work.
Is there a way through the api, to mark a chunk to be unloaded or queue them?

**Comment by josephrooks** [comment]
They're not being loaded by /forceload or some other chunk loading method are they? Do you know what specific chunks are staying loaded?

**Comment by Rincewind34** [comment]
> They're not being loaded by /forceload or some other chunk loading method are they? Do you know what specific chunks are staying loaded?

Forceload is not an option as a wrote before. The specific chunks are already uploaded in my original post.

**Comment by SoSeDiK** [comment]
Is there any news on this?

**Comment by Rincewind34** [comment]
I just tested it again, without plugins, there seems to be no problems. But that does not explain, what exactly happens
