### ISSUE TITLE
[scripts] improve idiot checks in paper scripts

### ISSUE THREAD

**Issue by electronicboy** [PaperMC/Paper#3773]
Creating an issue for tracking/am taking time off and will forget, 

The scripts are missing a few "nice to have" idiot checks,

primarily, missing commands are often treated in different manners
some missing commands will just provide an "ambiguous" command not found to users, as well as some "standard" tools such as patch will silently

Secondarily, the way rb works for mid-merge is flawed in that it just takes the current patch #, and tries to delete that many patches prior to rebuilding, this allows dropping patches mid-rebase which is an essential feature, however, because of this dependency on the patch # of the current mailbox being applied, running rebuild after already running one will delete further patches, it is *essential* that you rebuild and then immediately run patch again, however, there are no warnings/checks to ensure that this hasn't occurred

First issue is essentially a "free for all", prs welcome for that; PRs for the latter should be discussed on discord, otherwise is considered "team only"

**Comment by Proximyst** [comment]
> primarily, missing commands are often treated in different manners
some missing commands will just provide an "ambiguous" command not found to users, as well as some "standard" tools such as patch will silently

Fixed with #4172.

**Comment by Proximyst** [comment]
Stale who? Stale you! Zim-zalabim, unstale! ✨✨
