### ISSUE TITLE
[1.16] Players Spawning With Wrong World

### ISSUE THREAD

**Issue by DarkArc** [PaperMC/Paper#3778]
This is a developing issue, but I'm currently working with: a12a67785. 

Prior to the update my player was located at `World B, x, y, z` after the update my player appears in `World A, x, y, z` (the main/default world not created by MultiVerse/through multiworld support). 

The NBTTagCompound is correctly read in with `World B, x, y, z` on line 122 of `PlayerList.java`. Then `entityplayer.spawnIn(worldserver1)` causes the world to change to `World A`, though `x, y, z` are maintained.

The issue seems to be the resource key is not right. If the player goes to `World B`, and then reconnects, `worldserver1` will be correctly set to `World B`, instead of `World A`.

**Comment by DarkArc** [comment]
This appears to be caused by the NBT in 1.15 storing `"Dimension": 0` for all overworlds, which results in overworld/world 0. In the newer NBT the world name appears to be stored as a string (e.g. `"minecraft:astaria"`).

This behavior should (probably?) just be patched out? The NBTTagCompound load is giving the correct result, and in the case of a new player, the player seems to be populated targeting overworld/world 0 already.

**Comment by Machine-Maker** [comment]
This can be closed, was implemented in 4fd17445297b41e7121303bf886b32192346e715
