### ISSUE TITLE
Passengers are invisible

### ISSUE THREAD

**Issue by BillyGalbreath** [PaperMC/Paper#378]
### Description of issue:

Setting an entity as a passenger of anything makes the passenger invisible.

Works fine on CraftBukkit and Spigot.
### Plugin list:

None. Can reproduce with only a test plugin (code provided below).
### Paper build number:

Builds 718 and beyond.
### Code used to test:

```
public class MyPlugin extends JavaPlugin {
    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (!(sender instanceof Player)) {
            sender.sendMessage("Player only command.");
            return true;
        }

        Player player = (Player) sender;

        Entity pig = player.getWorld().spawnEntity(player.getLocation(), EntityType.PIG);
        Entity cow = player.getWorld().spawnEntity(player.getLocation(), EntityType.COW);

        pig.setPassenger(cow);
        player.setPassenger(pig);

        // cb/spigot player passenger workaround
        EntityPlayer playerHandle = ((CraftPlayer) player).getHandle();
        playerHandle.playerConnection.sendPacket(new PacketPlayOutMount(playerHandle));

        sender.sendMessage("Done.");
        return true;
    }
}
```
### Expected result of test code:

When running a command registered in plugin.yml a cow should be riding a pig and the pig riding the player that entered the command.
### What actually happens:

On Paper: The pig and cow entities are invisible. No errors.
On CraftBukkit or Spigot: Expected result happens.

**Comment by kamcio96** [comment]
Why are you sending that packet?

**Comment by BillyGalbreath** [comment]
Because MD_5 doesn't want to fix his broken API. When a player gets a passenger set to it all players on the server receive that packet so they can see the action and perform the mount on the client. Except the player getting mounted doesn't get the packet. MD_5 says it's a Mojang bug and won't fix, but it's clearly a CB bug because vanilla mounting works fine (getting on a horse or minecart, etc).

Anyways, Paper also uses this packet as a fix in server patch 0122. But it's not a problem of double sending the packet. I tested that by sending the packet twice on Spigot and CB and they both worked fine, and I even tested not sending the packet on Paper but the entities are still invisible.

**Comment by connection-lost** [comment]
The passenger & vehicle issue occurred since 1.9, there are too many troubles while setting passengers.
Something like this bugged me for a long time and I had to remove the feature from my server:
https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-2219
Currently I experience visual bug that player getting off another player packet is not sent to the player being ride on, and maybe more issues that I haven't discovered yet. The passenger & vehicle system is quite messy and may require a lot of time to fix the entire issue.

**Comment by BillyGalbreath** [comment]
New information.

Tested build 717 and it works as expected.

Build 718 introduced patch 0144 (entity tracking improvements) and thats the first build that started the invisible behavior.

All builds since then are effected.
