### ISSUE TITLE
Server crash waiting for nether chunk

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3783]
### Link/paste of stack trace
https://pastebin.com/qgCYzcnW

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
irrelevant

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
paper 43

**Comment by ghost** [comment]
same thing as #3780 i believe

**Comment by Looskie** [comment]
> same thing as #3780 i believe

:)

**Comment by looskie** [comment]
@dudeman123 Does your server also stay on and time people out upon reconnect?

**Comment by electronicboy** [comment]
Duplicate of #3780
