### ISSUE TITLE
KeepInventory don't work in nether

### ISSUE THREAD

**Issue by ImHoppy** [PaperMC/Paper#3784]
### What behaviour is expected:
Keep your inventory during a death in the nether

### What behaviour is observed:
Loss of stuff upon death

### Steps/models to reproduce:
 Activate the keepinventory gamerule and die in nether.

### Plugin list:
None

### Paper build number:
This server is running Paper version git-Paper-44 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by Machine-Maker** [comment]
did you activate the keepinventory gamerule in the nether or just the overworld?

**Comment by ImHoppy** [comment]
> did you activate the keepinventory gamerule in the nether or just the overworld?

Oh, I didn't know it was only for the world, thank you.
