### ISSUE TITLE
Command /gamerule doesn't update game rules

### ISSUE THREAD

**Issue by darcyamurphy** [PaperMC/Paper#3785]
### What behaviour is expected:
When using /gamerule <rule> true, the gamerule will be applied.

### What behaviour is observed:
When using /gamerule <rule> true, the gamerule is not changed. For example, the command /gamerule mobGriefing false did not disable mobGriefing, and the command /gamerule keepInventory true did not result in players keeping their inventories on death.

### Steps/models to reproduce:
Set a gamerule that is not currently true to true using the /gamerule command in game.

### Plugin list:
worldedit-bukkit-7.2.0-beta-01
worldguard-bukkit-7.0.4-beta1
Dynmap-3.1-beta-1-spigot
OpenAudioMc-6.3
BetterSleeping-3.0.1
DiscordSRV-Build-1.19.0

### Paper build number:
40

### Anything else:
When changing game rules with the /gamerule command, they seem to be changed only in the level.dat file in the world folder, and not the level.dat files in world_nether and world_the_end. I am able to manually change a game rule by editing the level.dat files in world_nether and world_the_end. It seems like once all three level.dat files have the same value for the game rule I want to change, the behaviour is then as expected.

The server has been updated from 1.15.2 running paper 272. This behaviour wasn't seen before the update. As part of the update I deleted all the nether data so we'd get the new biomes, I haven't tested whether this behaviour is seen on a fresh server.

**Comment by Prof-Bloodstone** [comment]
This is a known behavior. Game rules are per world.
You can either teleport to every world and run the command in there, or use the `execute in` command to change them in other worlds.

**Comment by Pavle012** [comment]
After i restart my server, the gamerules are reset. Is there a way to make them persistent?

**Comment by lynxplay** [comment]
They generally are as described in aboves issue and response.
If you believe there is an issue, open a new one please.
