### ISSUE TITLE
Last Successful Artifacts are mismatching

### ISSUE THREAD

**Issue by DutchFlander** [PaperMC/Paper#3786]
### What behaviour is expected:
Do not have version mismatch between Last Successful Artifacts

### What behaviour is observed:
Last Successful Artifacts are not the same

### Steps/models to reproduce:
Download e.g.:
<paper download page>/Paper-1.16/lastSuccessfulBuild/artifact/paperclip-47.jar
and
<paper download page>/Paper-1.16/lastSuccessfulBuild/artifact/paperclip.jar
Compare:
md5sum paperclip-47.jar paperclip.jar 
c55add44bbe8e5208aafdeb2ead95f8b  paperclip-47.jar
f3ce43dba112512e2b75d2812df619a7  paperclip.jar

### Plugin list:
N/A

### Paper build number:
1.16 - 47

### Anything else:
Since I always upgrade my server daily using the <paper download page>/Paper-1.16/lastSuccessfulBuild/artifact/paperclip.jar link, I noticed this behavior since release 37.

**Comment by clrxbl** [comment]
Use the API, do not use Jenkins CI links

**Comment by Prof-Bloodstone** [comment]
There's so many people using jenkins, that it has a cache slapped in front of it.
So you're actually downloading old version from the cache.
Jenkins will be blocked in the not so distant future, so you should use API instead.

**Comment by MiniDigger** [comment]
https://paper.readthedocs.io/en/latest/site/api.html

**Comment by DutchFlander** [comment]
Thanks, the API type of download is perfect!
:)

**Comment by DutchFlander** [comment]
Hi,

Just want to highlight that the API link is not updated since a couple of days:
https://papermc.io/api/v1/paper/1.16.4/latest/download downloads paper-1.16.4-294.jar instead of the (currently) latest paper-1.16.4-298.jar.

I think the link update is not working (?).

Kind regards,
DF
