### ISSUE TITLE
Tab complete -1 not working

### ISSUE THREAD

**Issue by MastoryMd5** [PaperMC/Paper#3788]
### What behaviour is expected:
Tab complete -1 does not work

### What behaviour is observed:
tab works with /

### Steps/models to reproduce:
In spigot.yml set tab_complete: -1
### Plugin list:
none

### Paper build number:
paper 1.16.1 build 44

**Comment by Machine-Maker** [comment]
Unable to reproduce on build 47.

**Comment by stonegray** [comment]
Able to reproduce on build 79

Able to reproduce on build 91

Possibly related to #3560

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/87490786-6a2fa200-c63e-11ea-98d7-ec929e87e22e.png)
Solely because it was the first plugin that popped up, cannot reproduce
Worth noting, that this solely controls if the server sends the command def or not, things like bungee networks, etc, will have issues where the client will still retain an older servers commands if it was sent

**Comment by aikar** [comment]
You really should not be using this setting anyway. -1 is a HORRIBLE setting and is really cruel to your players. I'm sure there are players this setting will make them leave the server.

Don't be mean to your players.

**Comment by MastoryMd5** [comment]
In Italy the community is really splitted, you can find the toxic player or young people that don't know anything about the tab complete, plugins or even what is papermc.
The toxic players try to do "bad reviews" about the server if it shows it's plugins or commands, i really don't mind give to others the list of the plugins that i use or tab complete but mostly i hate when people say "that server is crap because you can see the plugins"

To my players i give a small guide on commands and a GUI where they can do a lot of thing without commands, this is useful mostly for the younger audience that has problems typing commands.

**Comment by aikar** [comment]
convenience and user experience does not have a country bias. everyone benefits.
