### ISSUE TITLE
Thousands of Fake-Parrots 

### ISSUE THREAD

**Issue by RoliRavioli** [PaperMC/Paper#3789]
Hello. I want to report an Issue on Minecraft, so I dont knwo the rules here.

So, i play on a little Minecraft server, and now my Parrot got "copied" a thousand times and i dont know why. Only the Original Parrot can be moved, hitted or get on the Shoulder. The copied ones doesnt move, and they dont fall if the block underneath them gets break down.
There are so many of them that my ingame fps goes down.

### Plugin list:
![2020-07-04_19 55 00](https://user-images.githubusercontent.com/67838331/86518254-878b9180-be30-11ea-8d36-dd0112af2748.png)

### Other helpful links
Here is a Picture of the fake Parrots. On the right is the original one that I moved out of the Copys.
![2020-07-04_19 37 41](https://user-images.githubusercontent.com/67838331/86518282-c9b4d300-be30-11ea-9276-5606e9c200a0.png)

**Comment by aikar** [comment]
please reproduce without plugins, as this is so fringe it has to be plugin oriented.

**Comment by aikar** [comment]
also please include the report template information, you did not provide us any other context.

**Comment by HexedHero** [comment]
Holy shit fix ur red plugins

**Comment by calumari** [comment]
Strangely enough, I noticed this today as well on 1.15.2 build 372.
I re-logged and the duplicated parrots (there was a chicken too) disappeared.

OP and I share: LuckPerms, PAPI, FarmLimiter, WorldGuard and WorldEdit.

Happened shortly after teleporting with the vanilla /tp command.

**Comment by calumari** [comment]
Just a thought, could it be client-side? I installed OptiFine 1.16 pre2 today and I assumed it was an issue with that.

**Comment by RoliRavioli** [comment]
> Just a thought, could it be client-side? I installed OptiFine 1.16 pre2 today and I assumed it was an issue with that.

I just installed Optifine for 1.16.1 today too

**Comment by RoliRavioli** [comment]
> also please include the report template information, you did not provide us any other context.

Sorry,  i dont know the Site here an im not info programming. The admin of the Server Gold me to submit this issue here.

**Comment by RoliRavioli** [comment]
> Holy shit fix ur red plugins



> > also please include the report template information, you did not provide us any other context.
> 
> Sorry, i dont know the Site here an im not info programming. The admin of the Server told me to submit this issue here.

**Comment by calumari** [comment]
Don't worry! Next time you have an issue, stick to the template provided to make it easier for people to resolve your issue. Regarding the parrots, you may want to try with [OptiFine](https://github.com/sp614x/optifine).

**Comment by Proximyst** [comment]
This was an issue with the Optifine mod earlier on in 1.16; I assume this has since been fixed, as the reports of them disappeared on another server without a plugin or server update.
