### ISSUE TITLE
Summoned Phantoms do not target players

### ISSUE THREAD

**Issue by Eilux** [PaperMC/Paper#3791]
### What behaviour is expected:
Summoned phantoms should behave normally and attack players.

### What behaviour is observed:
Summoned phantoms circle normally but do not detect the player and attack them

### Steps/models to reproduce:
run the command: "/summon minecraft:phantom ~ ~10 ~"

### Plugin list:
none

### Paper build number:
git-Paper-47 (MC: 1.16.1) (Implementing API version: 1.16.1-R0.1-SNAPSHOT

### Anything else:
This problem also exists in older paper releases.

**Comment by Prof-Bloodstone** [comment]
Do you have `phantoms-only-attack-insomniacs: true` set in paper.yml

**Comment by Eilux** [comment]
Ah that was it.

**Comment by aikar** [comment]
Well, you should question do you really want to change that? Why would you want phantoms to attack people who ARE following the phantom rules.
