### ISSUE TITLE
I can't break anything with gamemode creative. Although I am an OP.

### ISSUE THREAD

**Issue by fakhrads** [PaperMC/Paper#3793]
Sorry before, I accidentally clicked send before I finished writing the problem I was experiencing

When I change my game mode to creative, I can't break anything. No notification appear. But, when I change it back to survival, I can break again.

Plugin list:
![image](https://user-images.githubusercontent.com/24514627/86522637-39f04280-be8b-11ea-8532-ef909660e867.png)

Paper build number:
![image](https://user-images.githubusercontent.com/24514627/86522641-512f3000-be8b-11ea-92a2-d1a5af590f63.png)

**Comment by Machine-Maker** [comment]
I feel like you are missing some information. Try and follow the template.

**Comment by BillyGalbreath** [comment]
Try without plugins

**Comment by armagidon-exception** [comment]
Try to decrease spawn-protection if you have it.

**Comment by fakhrads** [comment]
> Try without plugins

thanks for the reply sir. I found the problem is because vault plugin.

**Comment by aikar** [comment]
Can you try without CMI?

**Comment by aikar** [comment]
Vault would not cause this

**Comment by fakhrads** [comment]
> Can you try without CMI?

I have tried it. And, it still can't break anything with gamemode creative

**Comment by fakhrads** [comment]
> > Can you try without CMI?
> 
> I have tried it. And, it still can't break anything with gamemode creative

or, it's caused by other plugins that hook vault ?

**Comment by Chew** [comment]
> or, it's caused by other plugins that hook vault ?

This is it, this confirms that a plugin that depends on Vault is causing this issue.

**Comment by JanTuck** [comment]
Most likely some plugin incorrectly hooking into a vault or some other plugin incorrectly telling vault information about your permissions.

I see you have luckperms have you tried running the verbose mode and see if that gives any information?

**Comment by Chew** [comment]
Regardless, this isn't an issue with Paper and this should be closed.

As JanTuck mentioned, try `/lp verbose on [your name]` and breaking to see what perms are being checked.
