### ISSUE TITLE
[1.16.2] Portal Search Radius for the Nether does not mimic Vanilla

### ISSUE THREAD

**Issue by DarkArc** [PaperMC/Paper#3795]
###  Timings or Profile link:
https://spark.lucko.me/#zFtpx0I7vq

### Description of issue:
~~Entering a nether portal results in a serious performance hit as the server searches for an acceptable pairing.~~
Portal search radius was reduced to 16 in 1.16.2 for the nether (from the 128 for both directions before), but Paper still searches 128 (the config value) both directions)

### Paper build number:
Equivalent to: https://github.com/PaperMC/Paper/commit/4fd17445297b41e7121303bf886b32192346e715

----

~~Probably needs to be refactored to load the chunks in a non-blocking fashion... Or perhaps the vanilla default portal search radius of 128 should be reduced?~~

**Comment by JRoy** [comment]
The fact that you said "equivalent to" in your build makes me believe you have custom patches on top of paper which could affect performance.

For support with performance, go on the discord at https://discord.gg/papermc

**Comment by DarkArc** [comment]
I submitted the original https://github.com/PaperMC/Paper/commit/4fd17445297b41e7121303bf886b32192346e715, it's truly equivalent to, and that bit of login code I can promise has nothing to do with this. :)

----

You can see in the sample, there is a tremendous amount of time spent waiting on chunks to load in a blocking fashion.

**Comment by Cloud-Galaxyman** [comment]
I'm also having major problems with this. My portals are well over 300 blocks away from each other and they're still getting mixed up with each other. 
I know mojang changed portal behavior on the nether roof. Is that affecting anything? Does paper change portal behaviors from vanilla?

**Comment by ghost** [comment]
Since 1.16.2 portal search radius in vanilla in the nether is 16, in paper it is always 128 in all dimensions so you get portals mixing even when they are up to 2000 blocks from each other

**Comment by electronicboy** [comment]
You can configure the search radius in paper.yml, we should maybe reflect this default change, but, part of the issue is that toying with these values on an existing server would potentially break existing portals

**Comment by electronicboy** [comment]
```
    public Optional<BlockUtil.Rectangle> findPortal(BlockPosition blockposition, boolean flag) {
        // CraftBukkit start
        return findPortal(blockposition, flag ? 16 : 128); // Search Radius
    }
```
or, actually, CB still has the 128 in there

**Comment by electronicboy** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/PortalTravelAgent.patch#7
and so does vanillas code

**Comment by aikar** [comment]
Well I trackedit, it does look like vanilla changed it, that boolean is no longer search vs create, but now controlled by target == nether.

But I question if this is a bug in vanilla because this breaks existing portals as mentioned. going to ask mojang.

we can scale the search radius config / 8 which i initially was going to do on this update, but i ended up just leaving as is as I wasn't sure if i was misreading something.

But I am confident now vanilla search radius to the nether is in fact 16, but that is a pretty icky change on mojangs fault. as you would have multiple overland portals that use to go to the same place that now wont.

**Comment by BillyGalbreath** [comment]
> we can scale the search radius config / 8

I strongly suggest not hardcoding 8 in there seeing as datapacks can change that value (I use 1 on my server, for example)

**Comment by aikar** [comment]
can do portal-search-radius-nether-scaling: 8 then or so, idea is we want a default config to still be able to apply by dimension type, so then you can override that config in your individual nether worlds.

Though this scale is kind of different. Right now mojang is hard coded to 8 in vanilla regardless of your personal scale, it's still 128/16 - you can't change that in vanilla, so hard coding 8 there is still actually correct to keep it consistent with vanilla, but I'm not opposed to it being configurable.

**Comment by aikar** [comment]
and I swear we've had this convo before.

**Comment by aikar** [comment]
Relabeled ticket because performance is no different in logic for every update before this update, and yes it sucks, but same radius occurs on going to overworld too.

**Comment by DarkArc** [comment]
This seems like two distinct issues:
1. Blocking loading of chunks to search for a matching portal
2. The search radius being too large

Maybe only 2 needs fixed, but 1 doesn't seem like it should be ingnored either, as ultimately that was what was bringing the server to a crawl in my original report.

**Comment by aikar** [comment]
Well if you want to rewrite the entire portal system to be asynchronous (to be clear, that doesn't mean multi threaded), PR's welcome!

While it would be lovely to use asynchronous chunks for it, it's an extremly difficult problem because portal teleportation is a synchronous operation.

This is only realistic to get mojang to do it.

**Comment by nicegamer7** [comment]
Sorry, I hadn't realized you guys were discussing whether this should be configurable. I actually did read this a while ago, it slipped my mind though.

**Comment by zachbr** [comment]
GH-4781 should have resolved this in master.
