### ISSUE TITLE
Chunk problem while switching camera view

### ISSUE THREAD

**Issue by armagidon-exception** [PaperMC/Paper#3797]
### What behaviour is expected:
When you switch camera view you should not see through caves 

### What behaviour is observed:
When i switch camera view i see through caves for a split second

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
https://youtu.be/rMUczjXqIfU

### Plugin list:
___A list of your plugins___
![image](https://user-images.githubusercontent.com/42355119/86523681-00cbc880-beb3-11ea-8904-0479cc7e49f1.png)

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
![image](https://user-images.githubusercontent.com/42355119/86523690-0de8b780-beb3-11ea-8a7f-f07c91310d13.png)
it's fork of paper

### Anything else:
___Anything else you think may help us resolve the problem___
vanilla also has the same issue

**Comment by aikar** [comment]
we can not fix client issues.
