### ISSUE TITLE
[Paper Async Chunk Urgent Task Thread/WARN]

### ISSUE THREAD

**Issue by WieszczY85** [PaperMC/Paper#3799]
### What behaviour is expected:
The world generated in 1.15.2

### What behaviour is observed:
Warning loop in the console

### Steps/models to reproduce:
-

### Plugin list:
-

### Paper build number:
git-Paper-60 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by WieszczY85** [comment]
[Paper Async Chunk Urgent Task Thread WARN.txt](https://github.com/PaperMC/Paper/files/4874384/Paper.Async.Chunk.Urgent.Task.Thread.WARN.txt)

**Comment by Machine-Maker** [comment]
NOTE: Vanilla has a lot of console spam around `No key position_predicate in MapLike` for any chunk conversion:
https://bugs.mojang.com/browse/MC-191388
Any comments around "MapLike" are vanilla conversion issues.
-- direct from Paper discord

**Comment by WieszczY85** [comment]
"Resolution:Unresolved"
can this spam be turned off somehow?

**Comment by Machine-Maker** [comment]
Can probably create a filter somewhere to hide it. But this isn't a paper issue, and hence, this isn't the place.

**Comment by aikar** [comment]
No, If mojang doesn't fix it by 1.16.2, we will fix it then, but ultimately, we're not hiding an actual problem.

Your world IS having errors on converting.
