### ISSUE TITLE
[1.16] Anvil don't work

### ISSUE THREAD

**Issue by Homosanians** [PaperMC/Paper#3802]
### What behaviour is expected:
___What you expected to see___

### What behaviour is observed:
___What you actually saw___
after that steps enchanted item disappears, experience is consumed and never returned, book and item returns back

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
use anvil
1. put book and item into anvil
2. take enchanted item

### Plugin list:
___A list of your plugins___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
64

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Machine-Maker** [comment]
Yeah, this is reproducible.
