### ISSUE TITLE
Command.yml tab completer fix

### ISSUE THREAD

**Issue by armagidon-exception** [PaperMC/Paper#3803]
**Is your feature request related to a problem? Please describe.**
I may be lazy sometimes and use commands.yml to make command or just rebind command to another plugin, but it always has its terrible tab completer which shows you nicknames of all online players

**Describe the solution you'd like**
I want to have opportunity choose when i want to tab completion

**Describe alternatives you've considered**
Or a very least delete this stupid tab completer forever.

**Additional context**

**Comment by aikar** [comment]
settings.suggest-player-names-when-null-tab-completions set to false in paper.yml
