### ISSUE TITLE
cant repair items

### ISSUE THREAD

**Issue by moenius5** [PaperMC/Paper#3804]
So I just changed my server from vanilla to Paper 1.16.1

after changing repairing tools or armor in any way possible doesnt work anymore.

it takes the exp, but not the material and doesnt repair the item.

if i change back to vanilla the items get repaired as usual again.

Plugins none.

**Comment by Machine-Maker** [comment]
duplicate (probably) of #3802 

Also fixed in latest build (build 65)

**Comment by aikar** [comment]
As said, fixed in latest build
