### ISSUE TITLE
Ver/1.16 - respawn anchor in world and world_the_end

### ISSUE THREAD

**Issue by danechek** [PaperMC/Paper#3806]
This block is explodes when used in worlds other than nezer. Is it possible to add a function to allow its use for the other two worlds?

**Comment by Machine-Maker** [comment]
I don't think this is in the scope of paper. Sounds too much like a mod

**Comment by kickash32** [comment]
I feel like if someone wants to do this, it should be possible using a plugin using a few events. If its not currently possible the API needs to be expanded.
