### ISSUE TITLE
More lootables>auto-replinish options

### ISSUE THREAD

**Issue by TheFireOcean** [PaperMC/Paper#3808]
This isn't a problem. I just think it would be useful to keep things balanced.

I'd like to see options under auto-replenish where you could choose what was replenished like end city, dungeon, stronghold, shipwreck, (etc.) and also how often for the end city option

**Comment by Machine-Maker** [comment]
All of this is already possible with a plugin.

**Comment by aikar** [comment]
yeah i don't want to complicate the core feature. we expose an event for this to give you more fine tuned control, and recommend using that.
