### ISSUE TITLE
View Distance API Still Visually Broken

### ISSUE THREAD

**Issue by connection-lost** [PaperMC/Paper#381]
# Incompatibility (Bug)

The use of player#setViewDistance(radius) is still visually broken:
1. The chunks within the radius sent to player is correct.
2. Upon using player#setViewDistance(), the player however will experience a client screen freeze or flashes for a brief moment, depending on the performance of the computer. The freeze or flash seems to be a chunk load and visually equivalent to a F3+A. This is not happening to the view distance API prior to MC 1.8.x.
3. Upon using player#setViewDistance(), some entities might be visually disappear. The entities could be other mobs, other player or even the player itself. Attached screenshot is an example of the player itself has disappeared. Relog will fix the problem.
Screenshot: I am in third person mode but I cannot see myself! http://imgur.com/a/GJgad
### Steps/models to reproduce:

Reproducing is easy, just use player#setViewDistance(). It won't cause issue every time, but will more likely to cause the issue the longer the player has been on the server.
### Plugin list:

Nothing except that testing plugin of player#setViewDistance()
### Paper build number:

Paper 820 & 828

**Comment by zachbr** [comment]
Thanks for your detailed reproduction instructions. I was able to reproduce a minimal amount of flashing, and my player entity becoming invisible for a brief amount of time.

But I was testing locally, on a performant machine, so I don't doubt your claims.
We'll try to dig through this soon.

**Comment by zachbr** [comment]
Please re-test on builds 835+

**Comment by zachbr** [comment]
@connection-lost Working as intended once more? Would like you to verify. It all looks good here though.

**Comment by connection-lost** [comment]
It is working without problems now :)
