### ISSUE TITLE
PlayerDeathEvent triggered by EntityDeathEvent

### ISSUE THREAD

**Issue by BarcodeGIT** [PaperMC/Paper#3821]
### What behaviour is expected:
PlayerDeathEvent called one time when killed

### What behaviour is observed:
PlayerDeathEvent fired twice when entity killed 

### Steps/models to reproduce:
Put the .class object of the "PlayerDeathEvent" into a list and listen to the EntityDeathEvent, check if the list contains EntityDeathEvent and it will say it does and call the event

### Plugin list:
MyCustomGamemodePlugin

### Paper build number:
Paper 72 (1.16)

### Anything else:
Heres the code of the two events being called:

![5100db8b49d5a25037d62023cb8acee1](https://user-images.githubusercontent.com/55606335/86557167-3b148480-bf0a-11ea-85d4-8610db3186c3.png)

Heres the event being called when I /kill myself

![8146c7507c86e380229964eacafaa67b](https://user-images.githubusercontent.com/55606335/86556970-a742b880-bf09-11ea-951b-b9aae341bdcc.png)

(The null pointers are just caused by the entityDeathEvent calling the PlayerDeathEvent)
Maybe theres some basic java fact that im missing here since PlayerDeathEvent is an extension of EntityDeathEvent so when I check the list if it contains, since its a parent it says yes but I dont understand why it would call it and actually work even when I check if the event is an instance of PlayerDeathEvent in the "doEventModifier" Method

also heres the list its checking:
![0f4eb252d626e2a771a06cb632960319](https://user-images.githubusercontent.com/55606335/86557331-b0805500-bf0a-11ea-9ac1-bb1424130d24.png)

**Comment by electronicboy** [comment]
This is how event hierarchy works in bukkit (It's down to where the handler lists are, run up and you'll see entity death has the handler list), the same event is calling both handlers, not that two separate events are being fired

**Comment by BarcodeGIT** [comment]
> This is how event hierarchy works in bukkit (It's down to where the handler lists are, run up and you'll see entity death has the handler list), the same event is calling both handlers, not that two separate events are being fired

I see, so as long as I use this method of listening to events, this will happen regardless?

**Comment by electronicboy** [comment]
yes, PDE will call entity death handlers, just one of those things to factor into your design
