### ISSUE TITLE
villagers are not zombified

### ISSUE THREAD

**Issue by AlfreDGR** [PaperMC/Paper#3823]
### What behaviour is expected:
___What you expected to see___

### What behaviour is observed:
___What you actually saw___

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
#74

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by BillyGalbreath** [comment]
I don't think that's how the templates are supposed to be used

**Comment by AlfreDGR** [comment]
I cant write so much i am spanish

**Comment by amnotbananaama** [comment]
what is `difficulty=` set to in your `server.properties` file? By default (**even on a Vanilla server**), this is set to `easy`. See https://bugs.mojang.com/browse/MC-136161. You need to change the difficulty to either `normal` (50% chance of zombification) or `hard` (100% chance of zomibifcation). Note that these are vanilla mechanics, and not the fault of Paper.

**Comment by nahia95** [comment]
I'm using paper version 100 and I have difficulty set to hard on server.properties and I'm also experimenting this issue. I've tried editing the "zombie-villager-infection-chance" parameter in paper.yml with no success

**Comment by Proximyst** [comment]
Fill the template if you wish for anything to happen.

Setting the server to `hard` difficulty or `zombie-villager-infection-chance` to `100.0`, you'll get the desired outcome.
