### ISSUE TITLE
enable-player-collisions: false not work

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#383]
02.08 23:19:59 [Server] INFO This server is running Paper version git-Paper-828 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by Phreag** [comment]
Tested it and can confirm the bug.
Paper.yml is set to enable-player-collisions: false
But players can still push each other away.

Using BungeeCord and latest Paper build
[12:49:46 INFO]: This server is running Paper version git-Paper-832 (MC: 1.10.2) (Implementing API v
ersion 1.10.2-R0.1-SNAPSHOT)

**Comment by sgdc3** [comment]
Same issue

**Comment by zachbr** [comment]
Also needs testing without bungee.
Thanks for the input so far everyone

**Comment by Phreag** [comment]
Tested it without bungeecord, same effect there, 
enable-player-collisions: false and Players can be pushed.

**Comment by Phreag** [comment]
Also now tested it with a fresh server wothout any plugins, issue still exists.
So its defitetively not working as intended

**Comment by Phreag** [comment]
push...
