### ISSUE TITLE
[1.16] Entities causing lag?

### ISSUE THREAD

**Issue by MrIvanPlays** [PaperMC/Paper#3830]
https://timings.aikar.co/?id=a320cb5c493a411da529a701da003f02

### What behaviour is expected:
no entity lag

### What behaviour is observed:
entity lag causing tps to drop

### Steps/models to reproduce:
Only thing known is that it happens at more than 50 players online.

### Plugin list:
Listed in timings

### Paper build number:
Seen in timings

### Anything else:
I see it saying being a GC issue, however host claims that it is using aikar's flags, and they even sent me a pic:
![image](https://cdn.discordapp.com/attachments/620294227233865738/729754330361626725/unknown.png)
idk what should I do honestly, so I decided to open this issue.

**Comment by electronicboy** [comment]
1) Fill in the template
2) Clearly not aikars flags
3) Github is not the place for support with timings

**Comment by MrIvanPlays** [comment]
> 1. Fill in the template
> 2. Clearly not aikars flags
> 3. Github is not the place for support with timings

Where should I ask when you have me banned everywhere -_-
If github had ways to ban ppl from contributing to project, I'd be also banned from here.

**Comment by Proximyst** [comment]
GitHub has that. Don't make sure it happens here too :p
