### ISSUE TITLE
Server crash locks files and leaves the GUI on the screen.

### ISSUE THREAD

**Issue by spsquared** [PaperMC/Paper#3832]
Normally I stop the server and the GUI closes, however, this time it stays on, frozen. This also caused the program to not close, and killing the program would not close it. Now upon starting the server it aborts.

I don't know how I did it, I just closed the server to tweak a file.

Build #68 was used

Screenshot of broken GUI:
![Screenshot from 2020-07-06 14-21-51](https://user-images.githubusercontent.com/67865358/86626057-24b30b00-bf94-11ea-9c1d-385e495bc92b.png)
recent log:
[latest.log](https://github.com/PaperMC/Paper/files/4880611/latest.log)
crash reports, if it's helpful:
[crash-2020-07-06_14.03.47-server.txt](https://github.com/PaperMC/Paper/files/4880613/crash-2020-07-06_14.03.47-server.txt)
[crash-2020-07-06_14.04.27-server.txt](https://github.com/PaperMC/Paper/files/4880614/crash-2020-07-06_14.04.27-server.txt)
[crash-2020-07-06_14.07.34-server.txt](https://github.com/PaperMC/Paper/files/4880615/crash-2020-07-06_14.07.34-server.txt)

**Comment by JanTuck** [comment]
Just run the server with nogui, the gui was added in recently again after not actually having been there for ages. There is no use for it since you can see all the output in your terminal

**Comment by aikar** [comment]
This simply means you did not shut down the other instance properly and it is still open

youll need to kill that process more effectively. please use discord for further help on this specific issue.
