### ISSUE TITLE
 Failed to load player data for

### ISSUE THREAD

**Issue by B1gLev** [PaperMC/Paper#3833]
### What behaviour is observed:
So the console keeps spamming this "[19:24:37 WARN]: Failed to load player data for 096ce0c8-442d-3248-b424-7535428cd515" I don’t know why, and I don’t know how this should be solved

### Paper build number:
This server is running Paper version git-Paper-376 (MC: 1.15.2)

**Comment by electronicboy** [comment]
check your *full* logs, the jvm has a habit of stripping stack traces after an exception has been thrown once (There is also a JVM flag to disable this behavior)
Also, in the future, fill in the template

**Comment by B1gLev** [comment]
The error was resolved. Thanks for the quick response
