### ISSUE TITLE
Add Method to Check if Zombies Can Bang on Doors

### ISSUE THREAD

**Issue by WonderDave** [PaperMC/Paper#3837]
**Is your feature request related to a problem? Please describe.**
In my custom plugin, I'd like some sort of access to the Zombie "CanBreakDoors" property in "EntitySpawnEvent".  Specifically, my goal is to prevent the spawning of Zombies who are able to bang on doors (by cancelling the event for those who have that ability).    I can see methods like "isBaby" and "isConverting" and "isArmsRaised", but nothing related to being able to bang on doors.

**Describe the solution you'd like**
A method that exposes the "CanBreakDoors" field for Zombies so that I can cancel the spawning of Zombies who have the ability to bang on doors.

**Describe alternatives you've considered**
I am already able to prevent doors from breaking, but I'd like to prevent Zombies from even being able to bang on doors, whether or not the doors break.

**Additional context**
Thank you for considering this request.  If there is already a way to do this, I would love to know about it.

**Comment by Phoenix616** [comment]
You might be able to already work around this by removing the [`VanillaGoal#BREAK_DOOR`](https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/entity/ai/VanillaGoal.html#BREAK_DOOR) from the Mob.

**Comment by WonderDave** [comment]
I don't know how to do that.  I'm hoping that the two methods for this in #3838 that @Machine-Maker created will be merged.

**Comment by MiniDigger** [comment]
You can use the mob goal api: https://papermc.io/javadocs/paper/1.15/com/destroystokyo/paper/entity/ai/MobGoals.html#removeGoal-T-com.destroystokyo.paper.entity.ai.GoalKey-

Something like `Bukkit.getMobGoals().removeGoal(zombie, VanillaGoal.BREAK_DOOR)`

**Comment by WonderDave** [comment]
Thanks, @Phoenix616  and @MiniDigger .  That was helpful.  I've added the following to a method using the CreatureSpawnEvent:

   Entity entity = event.getEntity();
   if (entity instanceof Zombie)
      Bukkit.getMobGoals().removeGoal((Zombie)entity, VanillaGoal.BREAK_DOOR);

This definitely works when each Zombie is spawned, although it doesn't appear to be persistent.  For instance, if I spawn a ton of Zombies, none of them will bang on doors.  However, if I shutdown and restart my server, then those same Zombies (some of them) will start banging on doors.

**Comment by MiniDigger** [comment]
yeah, the list of goals sadly isnt persisted, you will need to reapply on chunk load :/
