### ISSUE TITLE
PlayerInteractEvent has left click when opening doors

### ISSUE THREAD

**Issue by Anrza** [PaperMC/Paper#3839]
Reproduce:
Listen for PlayerInteractEvent. Print .getAction() and .getBlock()
Open a door (right click it). Make sure the targeted block after the door is opened is air.
The listener will print LEFT_CLICK_AIR and null.
Trap doors also have this issue.

Version: git-paper-75 (MC 1.16.1)

**Comment by electronicboy** [comment]
this is just how vanilla/craftbukkit works, you need to verify the hand/action

**Comment by Anrza** [comment]
> 
> 
> this is just how vanilla/craftbukkit works, you need to verify the hand/action

@electronicboy What do you mean by "verify the hand/action"?

**Comment by electronicboy** [comment]
You need to check the hand/action in the event to check that they match, otherwise the event will fire for both hands in some cases

**Comment by Anrza** [comment]
@electronicboy I don't see how you would do that. The hand is information about which hand was used and the action is information about which clicked was used. Am I missing something?

**Comment by Anrza** [comment]
So I've tested a little and it seems like the problem isn't that the event is wrong, it's that it calls two events, one of which is right and then another which says left click.

**Comment by ItsAZZA** [comment]
@Anrza I believe you can check if the `event.getAction()` is `Action.RIGHT_CLICK_BLOCK`

**Comment by Machine-Maker** [comment]
> So I've tested a little and it seems like the problem isn't that the event is wrong, it's that it calls two events, one of which is right and then another which says left click.

Yes, that is how the event works. And you can filter based on what hand was used.

**Comment by Anrza** [comment]
@ItsAZZA Yea, I can. My issue is that an event with Action.LEFT_CLICK_AIR is fired, even though the player doesn't left click at all.

@Machine-Maker Yea, I know. I don't see how your input is helpful. Edit: No offense meant, but people keep saying things like that and I can't figure out how I am to solve my problem with it.

**Comment by electronicboy** [comment]
This has been the case for years, it's just one of those horrors which you need to work around, this is basically intentional due to the client sending two packets for these interactions

**Comment by Anrza** [comment]
@electronicboy Thanks for responding again. I see that current functionality is probably the best available. I've found an acceptable workaround.
