### ISSUE TITLE
Scoreboard not work

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#384]
02.08 23:19:59 [Server] INFO This server is running Paper version git-Paper-828 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Bukkit scoreboards? Vanilla scoreboards? How are they broken? Plugins?

**Comment by andris155** [comment]
Jobs reborn plugin
/jobs top command scoreboard
Paper 811 - works perfectly
Paper 828 - not showing scoreboard

**Comment by zachbr** [comment]
![1](https://i.imgur.com/cX12eGm.png)

Unless I'm missing something here, it seems to work just fine.
Actually everything looks to be working fine

![2](https://i.imgur.com/4xImpMy.png)

**Comment by sgdc3** [comment]
@Zbob750 Have you tried with enable-player-collisions: false?

**Comment by zachbr** [comment]
Pretty sure it was set to false, will double check again later tonight.

**Comment by zachbr** [comment]
@sgdc3 looks like it was enabled, good catch.
@andris155 in the future please follow the issue templates. Little details matter.

Fixed in builds 830+
