### ISSUE TITLE
Why was Jan-Lucas Ott (wizjany) demoted?

### ISSUE THREAD

**Issue by Karl-Heinz-Ott** [PaperMC/Paper#3840]
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
Why was Jan-Lucas Ott demoted?
@wizjany

**Comment by Machine-Maker** [comment]
Probably not the place...
