### ISSUE TITLE
Item names are italic

### ISSUE THREAD

**Issue by Swedz** [PaperMC/Paper#3842]
### What behaviour is expected:
Item names that are not italic.

### What behaviour is observed:
All item names that are set using `ItemMeta#setDisplayNameComponent(BaseComponent[])` are always italic.

### Steps/models to reproduce:
Use this code:
```
meta.setDisplayNameComponent(new ComponentBuilder(player.getName())
		.color(ChatColor.of("#4C4CB3"))
		.create());
```
The item with ItemMeta `meta` will have an italic name.

### Plugin list:
My plugins are custom, but here is the list, all work with 1.16:

- MCCubed
- ProtocolLib
- spark
- Tesseract

### Paper build number:
This server is running Paper version git-Paper-79 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Other information:
This [was an issue before](https://github.com/PaperMC/Paper/issues/3683), and was supposedly solved, but is happening to me on the latest build as of right now.

**Comment by KarlPro123** [comment]
Confirming

**Comment by Machine-Maker** [comment]
When you set lore using ItemMeta#setLore, unless you have a color/style code, it comes out as italic/purple. Why should not including a style code alter the vanilla behavior of item renaming. Items are italicized when renamed in an anvil.

**Comment by MrIvanPlays** [comment]
Solution: explicitly set it to not be italic

**Comment by aikar** [comment]
this is a new change by mojang, you are required to explicitly define you don't want italics now.
