### ISSUE TITLE
Server crashed twice when a player loads a crimson forest

### ISSUE THREAD

**Issue by alexmartz710** [PaperMC/Paper#3845]
### Link/paste of stack trace

https://paste.gg/p/anonymous/653307930bfa40658d76d32f78ca9d4d
https://paste.gg/p/anonymous/d637b6921aba45e4aa748e5dccdd3397

### Plugin list:
List is inside the links above.

### Actions to reproduce (if known):
I've only had this happened twice when two different players loaded a new crimson forest in the server.

### Paper build number:
First crash on July 4, 2020 Paper version git-Paper-47 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Second crash on July 7, 2020 Paper version git-Paper-74 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Update
