### ISSUE TITLE
[1.16.1] Villagers won't breed and will just look at each other

### ISSUE THREAD

**Issue by ungeskriptet** [PaperMC/Paper#3846]
### What behaviour is expected:
Villagers should do the shmexy and make a baby.

### What behaviour is observed:
Villager are just looking at each other and won't breed.

### Steps/models to reproduce:
Get latest PaperMC version (#79) place 4 beds and give them ~24 carrots.

### Plugin list:
None/Pure vanilla with few datapacks from [https://vanillatweaks.net/picker/datapacks/](https://vanillatweaks.net)

### Paper build number:
> [18:26:02 INFO]: This server is running Paper version git-Paper-79 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
> [18:26:06 INFO]: Previous version: git-Paper-70 (MC: 1.16.1)

### Anything else:
I downgraded to version #70 to fix it temporary

**Comment by rrvk** [comment]
I have the same issue, the villagers also dont farm anymore

**Comment by lordrius** [comment]
Can confirm. In build 79, they just throw food over and over. Switched to build 70 and hearts + baby villagear appears...

**Comment by crizyx** [comment]
Same Issue with the 1.16.1 build 79

**Comment by IonicEcko** [comment]
Same issue. Windows Server 2019, Java 14, Paper b79 (also broken on 77 I believe), tested without addons and datapacks. Fixes on revert to vanilla jar.

**Comment by Proximyst** [comment]
This issue was caused by https://github.com/PaperMC/Paper/commit/e588fd94a83d85d0aed09b8f71b4a9c5ec488425.

**Comment by FYWindis** [comment]
same issue confirmed in build 79

**Comment by Lost-Feight** [comment]
same in 78... whole server can't breed villagers

**Comment by ShashankVenkatramani** [comment]
also had this issue in build 79

**Comment by Machine-Maker** [comment]
This issue was fixed in build 80

**Comment by josesei** [comment]
Could replicate in build #90

**Comment by RedZephon** [comment]
Can confirm villager breeding is still broken in build #90

**Comment by Proximyst** [comment]
It was confirmed fixed as of b80.

Reproduce and create a new detailed issue with the build *after b80* where the mechanic broke.
