### ISSUE TITLE
[10:19:26 ERROR]: The server has not responded for 20 seconds! Creating thread dump

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3851]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

**Comment by ghost** [comment]
noob

**Comment by skedgywasedgy** [comment]
Doesn't it literally say not to report it as a bug in that very same message? That may be me remembering wrong but I've seen that message a couple of times.
