### ISSUE TITLE
Player getTargetEntity is undefined

### ISSUE THREAD

**Issue by darksoldier1404** [PaperMC/Paper#3856]
### What behaviour is expected:
___What you expected to see___

The method getTargetEntity(int) is undefined for the type Player

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
paper-api-1.16.1-R0.1-SNAPSHOT

i use maven project
and just undefined Player getTargetEntity
like this : https://imgur.com/3TAn5QV

**Comment by Proximyst** [comment]
The method is there. If you'd like help with this issue, please join our Discord and ask in #paper-dev, or ask in #paper-dev on `irc.spi.gt`.

**Comment by darksoldier1404** [comment]
> The method is there. If you'd like help with this issue, please join our Discord and ask in #paper-dev, or ask in #paper-dev on `irc.spi.gt`.

i know it is in there
but its not show up
and.. i already in server haha

**Comment by darksoldier1404** [comment]
i was dumb
i depend paper and spigot lol..
