### ISSUE TITLE
Add support for hex codes in messages like shutdown, restart, whitelist etc

### ISSUE THREAD

**Issue by jlachniet** [PaperMC/Paper#3858]
**Is your feature request related to a problem? Please describe.**
Messages from bukkit.yml, paper.yml, and spigot.yml do not fully support custom hex codes. For example, it is not possible to add hex codes to the custom shutdown message from bukkit.yml

**Describe the solution you'd like**
Adding custom support in the same way as supported in the MOTD

**Describe alternatives you've considered**
Might be possible with a plugin, but seems unnecessary for such a simple feature.

**Additional context**
N/A

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/86952237-99c84100-c14a-11ea-8f89-ed4cd642ae41.png)
Works fine here, uses the standard &x... format

**Comment by jlachniet** [comment]
Are you sure that the hex code you used didn't end with D? That looks like the same color as &d.

**Comment by electronicboy** [comment]
God damn...

**Comment by electronicboy** [comment]
Ideally, for spigot/CB stuff, that should be submitted upstream, but, looks like the bukkit stuff doesn't support color code parsing, wasn't sure if that was bungeechat only

**Comment by JRoy** [comment]
Cannot reproduce on latest, when using `§x§6§3§4§3§2§0Server is restarting` as a test value

**Comment by Chew** [comment]
![image from jroy](https://i.imgur.com/iSqyrWv.png)
