### ISSUE TITLE
Empty Text Is Stripped From Itemstacks Even When Colored

### ISSUE THREAD

**Issue by UltraFaceguy** [PaperMC/Paper#3861]
### What behaviour is expected:
"text":"" to not be stripped when it is a colored component

### What behaviour is observed:
"text":"" is stripped from itemstacks

### Steps/models to reproduce:
Obtain any itemstack with "text":"" in its data, drop it, pick it up again

### Plugin list:
N/A

### Paper build number:
gity-Paper-79

### Anything else:
While empty text should probably be stripped in some cases, when colored, it shouldn't be. This breaks compatibility with any legacy plugins that stored data on an item via a series of color codes (for invisible data storage) pr in my personal case, include a visual bar with progress tracking on an item. ( &9[|||||||&0||&9] displaying as a partially empty bar, &9[||||||||&0&9] being a full bar, right now the &0 is stripped from this bar, breaking the tracking of progress )

**Comment by Proximyst** [comment]
Can you reproduce this upstream?

**Comment by Hexicube** [comment]
@Proximyst Yes, see: #3869 as I missed this issue. The issue has been nailed to a specific commit.

**Comment by aikar** [comment]
per linked issue this is now resolved
