### ISSUE TITLE
TreeType enum for New Nether Trees

### ISSUE THREAD

**Issue by BarcodeGIT** [PaperMC/Paper#3862]
**Is your feature request related to a problem? Please describe.**
In the spigot javadocs it says they are there, but in the libraries for both spigot 1.16 and Paper-api 1.16 they arent there

**Additional context**
Here is a screenshot from the Paper-api 1.16 TreeType enum class
![15e38c9e413ac2b533e844f82983156a](https://user-images.githubusercontent.com/55606335/86974042-78eff380-c12a-11ea-9d97-e0c26082d3e3.png)

**Comment by aikar** [comment]
something is wrong with your build and it's not actually pulling 1.16, see: https://papermc.io/javadocs/paper/1.16/org/bukkit/TreeType.html#CRIMSON_FUNGUS

Please use discord #paper-dev for further assistance.

**Comment by BarcodeGIT** [comment]
> something is wrong with your build and it's not actually pulling 1.16, see: https://papermc.io/javadocs/paper/1.16/org/bukkit/TreeType.html#CRIMSON_FUNGUS
> 
> Please use discord #paper-dev for further assistance.

weird ok will do
