### ISSUE TITLE
[1.16] Passive Mobs not moving

### ISSUE THREAD

**Issue by C-o-l-l-i-n** [PaperMC/Paper#3863]
### What behavior is expected:
Passive mobs are supposed to naturally walk around.

### What behaviour is observed:
Pigs and cows and other passive mobs stand still. Hostile mobs do not stand still, and mobs spawned by hand do not stand still either.

### Steps/models to reproduce:
Unknown. Naturally occurring?

### Plugin list:
Aqua, CoreProtect, dynmap*, InfiniteScoreboard, LockettePro, LuckPerms, PlaceholderAPI, SilkSpawners, TAB, TradeSystem, Vault, XPConomy*

### Paper build number:
git-Paper-82 (MC: 1.16.1)

Thanks in advance.

**Comment by Machine-Maker** [comment]
Did you previously have installed EntityTrackerFix or another ai changing plugin?

**Comment by C-o-l-l-i-n** [comment]
> Did you previously have installed EntityTrackerFix or another ai changing plugin?

I have. I recently uninstalled EntityTrackerFix. Should I reinstall or something?

**Comment by Machine-Maker** [comment]
I believe EntityTrackerFix permanently messes up already spawned mobs. So you might have to just kill all the ones that aren't moving and find some new ones.

**Comment by C-o-l-l-i-n** [comment]
> I believe EntityTrackerFix permanently messes up already spawned mobs. So you might have to just kill all the ones that aren't moving and find some new ones.

Used essentials to kill all animals. What a shame. They should probably mention that on the spigot page :)
