### ISSUE TITLE
Main world overrides any structure-gen settings for other worlds.

### ISSUE THREAD

**Issue by NobleStrike** [PaperMC/Paper#3864]
As of 1.16 if the server.properties is set to a main world with structures disabled it overrides all worlds (nether, end and other added worlds), regardless of their individual world settings in their nbt files. It does place the cords for the structures however, you can see them with /locate but they just aren't generated. The issue can be worked around by using a main world with structures enabled, however many of us use flat worlds with it disabled as our spawns/hubs and have other multiple survival worlds. And changing the structure setting isnt easy at all it seems its all rooted deep into the nbt beyond my understanding.

I hope to just see each world act individually to its own settings, this issue could include more settings than structures, but that is untested. For basic vanilla servers i can see why the main world controls all other worlds structure settings for simplicity, but that creates issues for many of us, especially some of us with existing survival worlds that didn't fully generate before 1.16 or some of us trying to release new 1.16 nether worlds for our users just to find the servers spawn/hub world is breaking generation settings for all worlds suddenly.

Im on build #79 of version 1.16.1
This issue can happen with and without a multi world management plugin.
This bug may be under Spigot or Mojang, but who knows how long it would take for a patch to come through them, especially if this is a behavior change that causes a feature issue rather than a miss-code/change-of-code related error. That is unknown to me. 

This issue was also brought to the attention of the plugin dev of multiverse core, but if the issue is out of his reach then I figured posting it here was a good second step, as honestly many of us aren't sure what level this issue falls under.

Thank you, if this is also out of your hands i would really appreciate being pointed in the correct direction.

**Comment by BillyGalbreath** [comment]
You just found the missing piece to the puzzle \o/

Related ticket #3720

**Comment by NobleStrike** [comment]
This issue has been brought to the attention of spigot and multiverse as well. Spigot already tried to fix it before and failed.
