### ISSUE TITLE
Aquatic Mob rapid spawn/despawn

### ISSUE THREAD

**Issue by DeltaKilo97** [PaperMC/Paper#3865]
When building a taller structure over water, I noticed a bug where the aquatic mobs would rapidly spawn, be out of the radius, and despawn. I searched for a duplicate issue but could not find it. 

running latest PaperMC build on 1.16.1

**Comment by HexedHero** [comment]
https://github.com/PaperMC/Paper/issues/3523

**Comment by DoubleGe** [comment]
Issue is duplicated of ^

**Comment by Chew** [comment]
Duplicate of #3523

This appears to be a duplicate of #3523 , so this will be closed in favor of that issue instead. Thank you for contributing to Paper!
