### ISSUE TITLE
Command blocks with long command kick the client

### ISSUE THREAD

**Issue by Doctacosa** [PaperMC/Paper#3866]
### What behaviour is expected:
Right-clicking a command block with a long command already inserted in 1.15 would display that command, as it did before. Alternatively, pasting a long command in a command block would allow the paste operation to complete, allowing the player to save the command.

### What behaviour is observed:
The client gets automatically disconnected. Server-side, a message like this one appears:
[22:34:13 INFO]: Doctacosa lost connection: Internal Exception: io.netty.handler.codec.DecoderException: The received encoded string buffer length is longer than maximum allowed (12844 > 8192)

### Steps/models to reproduce:
1- Create a command block and try to paste this command, or any that is sufficiently long: https://pastebin.com/BBxeWm56
2- The client gets kicked.

### Plugin list:
Reproducible with NO plugins.

### Paper build number:
This server is running Paper version git-Paper-82 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
Does NOT happen on the vanilla server.
Does NOT happen on a Spigot server.
This seems specific to Paper.
I can provide more examples if needed.

**Comment by Machine-Maker** [comment]
Not reproducible for me. I tried on latest paper (82) with the command you had in the pastebin. I was able to paste the command in, and run the command.

**Comment by Doctacosa** [comment]
I did a whole lot of narrowing it down, and it's linked to a command alias we have defined in commands.yml. We have `/summon` defined as `minecraft:summon $$1 $2-` to ensure that players need to enter at least two parameters, I think that's a holdover from when we had a different `/summon` command before Minecraft introduced its own.

If I remove that alias, using command blocks with long commands works just fine.

Here's the file with all unrelated content removed.
[commands.yml.txt](https://github.com/PaperMC/Paper/files/4897202/commands.yml.txt)

**Comment by Chew** [comment]
So is this still a valid issue? Otherwise it should be closed.

**Comment by Doctacosa** [comment]
Yes, it's still a valid issue as per my follow-up.

I personally worked around it, so it's not a blocker for me anymore, but this is a strange protocol situation that I believe could be hiding deeper issues or be troublesome for others.

**Comment by aikar** [comment]
no its not hiding deeper issues, this was an intentional change to limit people from sending too large of commands.

thought i responded to this already, but best I can see is trying to make it so ops can override limit.

**Comment by Laarryy** [comment]
This issue is invalid as the 'issue' works as intended. If anyone is actually facing this problem, where as an op they cannot paste a long enough command, please open a new feature request issue. Otherwise, there's no point to addressing something that's not a bug and nobody wants!
