### ISSUE TITLE
The Paper 1.16.1 TNT replicator out of commission

### ISSUE THREAD

**Issue by Espboxx** [PaperMC/Paper#3868]
### What behaviour is expected:
___What you expected to see___
TNT replicator It replicates normally
### What behaviour is observed:
___What you actually saw___
TNT replicator Don't work
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
The automatic stone brush is done but THE TNT does not replicate
### Plugin list:
___A list of your plugins___
null
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
1.16.1 All
### Anything else:
___Anything else you think may help us resolve the problem___
The official server client 1.16.1 Can be used normally

**Comment by aikar** [comment]
Please look at the top of the page... There is a pinned issue
