### ISSUE TITLE
Extreme tps problems

### ISSUE THREAD

**Issue by Blueeyestar** [PaperMC/Paper#3870]
Paper version git-Paper-82 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

We have had extreme TPS problems on the server for a few days now. Nothing has changed in plugins.
Why are there these extreme TPS rashes. It didn't exist before.

I hope someone can say where the problem is and how we can solve it. We are at a loss

https://timings.aikar.co/?id=b895dc30d0c84179977b14ceba25fe3a

**Comment by clrxbl** [comment]
Your GC flags & Citizens are the issue.
GitHub issues shouldn't be used for issues like this, Discord is for that & you didn't use the template.

**Comment by BeastPsycho** [comment]
I NOTICE 1.16.1 has Bad world saves.
Tps drop to 12-10 until crash in my timings
I got a 3000% world saving from a 24h timing, but paper/spigot 1.15 i have same config an plugins, only in 1.16 and i had to move a dedicated to solve it... 80% lag reduced, not 100%

**Comment by electronicboy** [comment]
Please use IRC/Discord/forums for support with timings
