### ISSUE TITLE
Potion of Harming Dupe

### ISSUE THREAD

**Issue by skedgywasedgy** [PaperMC/Paper#3871]
### What behaviour is expected:
Upon drinking a potion of harming that would cause lethal damage, the player drops an empty bottle.
(In regular Minecraft this is glitched as well, but differently. The bottle stays in the inventory on death and disappears completely on respawn. This isn't much better but at least it doesn't create a dupe.)

### What behaviour is observed:
If the players dies from drinking a potion of harming, they drop a duped potion of harming and keep the empty bottle in their inventory on death. When they respawn, they still have the bottle in their inventory.

### Steps/models to reproduce:
Bring your health down low enough and drink a potion of harming that would cause lethal damage.

### Plugin list:
EssentialsX
Multiverse/Multiverse-Inventories
Towny
Vault
WorldEdit
WorldGuard

### Paper build number:
git-Paper-79 (MC: 1.16.1) (API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
No additional information.

**Comment by HexedHero** [comment]
`Multiverse/Multiverse-Inventories`

**Comment by skedgywasedgy** [comment]
No, it isn't. It occurs with MVInv disabled and I'm not teleporting between worlds when I respawn, which is the only time MVInv takes effect.

**Comment by Proximyst** [comment]
Reproduce on latest without plugins.

**Comment by skedgywasedgy** [comment]
Still occurs.

**Comment by clrxbl** [comment]
Cannot reproduce on Paper-79

**Comment by skedgywasedgy** [comment]
What did you do? 'Cause I've been able to consistently reproduce this glitch accross multiple versions.

**Comment by clrxbl** [comment]
Low health & drinking a Potion of Harming.

**Comment by skedgywasedgy** [comment]
Did drinking the potion of harming kill you?

**Comment by clrxbl** [comment]
Yes

**Comment by PepperCode1** [comment]
I was able to reproduce on latest. I found the problem in the code and will make a pull request later.

**Comment by Spottedleaf** [comment]
produced locally

**Comment by PepperCode1** [comment]
Newer and better pull request has been made.

**Comment by PepperCode1** [comment]
I'm leaving a comment to un-stale this issue as it still occurs, and the pull request that solves it has been marked at "ready for core".
