### ISSUE TITLE
[1.16.1 Paper #86] Packet Processing Error Upon Entering End Portal

### ISSUE THREAD

**Issue by theravensrequiem** [PaperMC/Paper#3876]
### What behaviour is expected:
To either return to last known respawn location or see end credits when you jump into the end portal.

### What behaviour is observed:
Player gets kicked with "Connection Lost - Packet processing error" when jumping into the end portal:
![image](https://user-images.githubusercontent.com/6815994/87188599-1e3ad100-c2bd-11ea-8d79-706dab6b8bbd.png)

### Steps/models to reproduce:
Jump into the end portal after killing the dragon.

### Plugin list:
CoreProtect-19.0.jar
DiscordSRV-Build-1.19.0.jar
EssentialsX-2.18.0.0.jar
EssentialsXChat-2.18.0.0.jar
GtzDoors-1.1.3.jar
HeadDatabase.jar
HorseTpWithMe-7.2.0.0.jar
PlaceholderAPI-2.10.6.jar
ProtocolLib.jar
SpigotLib.jar
UltraPermissions.jar
Vault.jar
WorldGuardExtraFlags.jar
worldedit-bukkit-7.2.0-beta-02.jar
worldguard-bukkit-7.0.4-beta1.jar

### Paper build number:
Paper version git-Paper-86

### Anything else:
When I was running Multiverse, jumping into the portal would crash the server. Now with just these plugins and the three main world folders, it simply kicks the player with the packet error.

![image](https://user-images.githubusercontent.com/6815994/87190703-f3eb1280-c2c0-11ea-9ae0-b45f3095912a.png)

**Comment by BillyGalbreath** [comment]
Do you have `disable-end-credits` enabled in paper.yml?

**Comment by theravensrequiem** [comment]
```disable-end-credits: false```
