### ISSUE TITLE
Clarify why I cannot swap NMS pathfinders when using Paper compared to Spigot where it is possible

### ISSUE THREAD

**Issue by Shynixn** [PaperMC/Paper#3877]
### What behaviour is expected:
Clearing and adding pathfinders to custom entities should work in the same way as in Spigot.

### What behaviour is observed:
When clearing the pathfinders of a custom entity and adding them again the entity does no longer
execute them. Basically, it stands still. 

### Steps/models to reproduce:

- Create custom entity (NMS, reflection etc.)
- Clear the default ai goals (Reflection PathfinderGoalSelector on field 'd' and clear goalSelector, targetSelector)
- Add your custom ai goals (this.goalSelector.a(1, SomeCustomPathfinderInstance))
- Observe that the entity works correctly (follows owner)
- Clear the default ai goals in the same way as before 
- Add your custom ai goals in the same way as before
- Observe that the entity does no longer work (does not follow owner)

### Plugin list:
PetBlocks

### Paper build number:
Paper-86 but I observed it in earlier versions too

### Anything else:
Hello!

I am using custom entities (heavy NMS) in my pet plugin PetBlocks and the pet entities have got problems when Paper is being used compared to Spigot. In Spigot I can swap pathfinders as I like and I do not have to respawn the entity. In Paper the pathfinders seem to break if I swap them.

Can you please point me to the related Paper patches to this problem (and maybe explain them to me) that I can add a workaround for it? 

My plugin also requires the following setting in the paper.yml to work. 
``armor-stands-tick: true``

**Comment by BillyGalbreath** [comment]
Instead of hacking and slashing your way to the `d` field, why not use the add/remove methods?

Example:
```
new HashSet<>(this.goalSelector.getTasks()).forEach(goal -> goalSelector.removeGoal(goal.getGoal()));
```

This is how Mojang designed it, and how they use it. If you examine the `eM()` method in `EntitySkeletonAbstract` class you will see that is indeed how they are swapping out goals.

**Comment by Shynixn** [comment]
Thank you for the reply. I'll try that.

**Comment by BillyGalbreath** [comment]
You could also use Paper's API to more easily handle Mob AI.

Example on how to clear all goals:
```
Bukkit.getMobGoals().removeAllGoals(mob);
```

You can even create and add your own using this API

https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/entity/ai/MobGoals.html

**Comment by aikar** [comment]
please use discord for further assistance

**Comment by Shynixn** [comment]
This 

> Instead of hacking and slashing your way to the `d` field, why not use the add/remove methods?
> 
> Example:
> 
> ```
> new HashSet<>(this.goalSelector.getTasks()).forEach(goal -> goalSelector.removeGoal(goal.getGoal()));
> ```
> 
> This is how Mojang designed it, and how they use it. If you examine the `eM()` method in `EntitySkeletonAbstract` class you will see that is indeed how they are swapping out goals.

Thank you. It resolved the issue for me.
