### ISSUE TITLE
Unsolvable memory leak

### ISSUE THREAD

**Issue by matiasilva** [PaperMC/Paper#3882]
### Timings

https://timings.aikar.co/?id=446947d3ffc34464a5400c6ac56b2a3d

### Description of issue:
After a few hours of running the server, even with noone online, the server reports that it can't keep up and proceeds to crash a few hours later. Restarting the server only solves the issue temporarily, see CPU usage below:

![image](https://user-images.githubusercontent.com/23108156/87224379-d67b7e80-c37c-11ea-8868-143fb2e4bfbe.png)

The Java garbage collector seems to running like crazy which leads me to believe it is a memory leak, potentially with plugins.

### Plugin list:

[13:47:20 INFO]: Plugins (18): Broadcaster, CoreProtect, Essentials, EssentialsChat, GriefPrevention, HolographicDisplays, LuckPerms, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, PerWorldInventory, PocketKnife, ServerRestorer, SpawnMultiverse, Vault, VoidGenerator, WorldEdit, WorldGuard

SpawnMultiverse is a custom plugin, it just aliases the /spawn command to a multiverse call.

### bukkit.yml, spigot.yml, paper.yml, server.properties

bukkit.yml: https://pastebin.com/y0ZTgmfa

spigot.yml: https://pastebin.com/0qfShLaM

paper.yml: https://pastebin.com/Y7pZ9JQv

I don't remember making major changes to these files.

### Other helpful links

Started on 1.15.2, upgraded to 1.16.1 a few days ago. Deleted the nether folder to regen the nether.

### Paper build number:

git-Paper-84 (MC: 1.16.1)

Though this issue existed once updating to 1.16.1

**Comment by HexedHero** [comment]
/paper heap
open it with eclipse memory analyzer

**Comment by matiasilva** [comment]
Will do, also just posted timings

**Comment by matiasilva** [comment]
The heap dump is too large for my laptop to process, it seems :/

**Comment by aikar** [comment]
high allocation rate is not the same thing as a memory leak
But i believe you pasted a CPU graph and not memory graph

what was the memory usage like? what conditions trigger this behavior?

**Comment by aikar** [comment]
if you can upload it and privately email it to me i can analyze it, but please make sure it was something actually full on memory usage.

**Comment by matiasilva** [comment]
Yes, it is a CPU graph however I looked at the garbage collector and at one point it was doing 200k context switches a second. This is what leads me to believe it has something to do with memory, but perhaps I'm wrong. The memory usage was didn't vary too much after those restarts: 
![image](https://user-images.githubusercontent.com/23108156/87402624-c1d4fb80-c5b3-11ea-9665-3902e17ac647.png). 
![image](https://user-images.githubusercontent.com/23108156/87402812-fd6fc580-c5b3-11ea-96fd-e5e9ea05e1dc.png)


From a look at the timings, it seems to be an issue in the "ninja_land" world? It also seems like WorldGuard is taking a long time each tick.

**Comment by electronicboy** [comment]
Looking at the OSes memory usage is basically pointless, java will use the memory in the heap consistently which will always show as "used" in process management/monitoring tools, outside of the various other bits of memory that java needs, as well as itself; You'd need to hook up something to watch the memory and GC usage, visualvm being a primary example which is bundled with the JDK, for example

**Comment by MrIvanPlays** [comment]
Can reproduce, I also believe that this is a memory leak. The server I maintain gets to 80 players every night, after that when they leave memory consumption stays at 100% and then starts running with ticks behind that eventually lead the server to crash. Restarting it after everyone has quit for the night even after no players had joined the server memory consumption rises again which is very very VERY weird.

**Comment by aikar** [comment]
ivan you have added 0 data to this with that comment.

there needs to be a heap dump or reproduction steps provided to prove a leak.

@matiasliva context switches are normal for 1.14+. The server no longer really sleeps and just spams switches now.

a leak would be represented that if looking at memory graphs, after a collection results in barely any memory released on an idle application

![image](https://user-images.githubusercontent.com/58008/87799177-ed0d5400-c81a-11ea-858c-a82ff7b64a5c.png)

in a leak, the orange will stay peaked to the top.

**Comment by ghost** [comment]
I can confirm having this issue too. I do not have any plugins (except for bStats that Paper automatically installs for you). Though disabling advancements as suggested in #3050 did reduce the leak, it did not completely stop it.

**Comment by MrIvanPlays** [comment]
> did reduce the leak, it did not completely stop it.

Indeed, there's AdvancementPlayerData leak. More advancements you have = more maps created = more memory consumed.

**Comment by matiasilva** [comment]
Thanks for the useful advice everyone, I haven't been able to figure it out and I've moved on to a Waterfall set-up rather than a complex multiverse set-up. I'll let everyone know if I manage to figure something out otherwise I'm afraid I have nothing else to say. I might've mistakenly assumed it was a memory leak. It seemed to be this way as there was some build-up involved and the problem would slowly get worse as time went by until the server crashed as seen in the CPU graph.

**Comment by ghost** [comment]
@matiasilva, #3050 got fixed (f503db3). Try updating to the latest Paper version and see if the issue still occurs. I am not at home so I cannot personally test it out my self.

**Comment by aikar** [comment]
This issue never confirmed it was actually a memory leak or due to advancements. 
Still need more information on what the state of the server is to know what's going on here.

**Comment by ghost** [comment]
True, but there is still a possibility...

**Comment by aikar** [comment]
As much possibility as it is due to pigs flying at speed 10 loading chunks and plotting world domination.

(hint: we have no evidence for either ;P)

**Comment by matiasilva** [comment]
Haha, thanks everyone for the advice. I can't do more testing because I have since dismantled the server ;(
