### ISSUE TITLE
No Nether structures

### ISSUE THREAD

**Issue by Hyronymos-Old** [PaperMC/Paper#3884]
Im running a Plotworld with PlotSquared, we have a nether world that doesnt generate structures like bastion_remnant, all worlds take on the main world's structure settings, thats causing that structures on my nether world doesnt generate + I cant find them with /locate, after editing level.dat, i could find them with /locate, but sadly they wasnt any structures 

### Steps/models to reproduce:
just create a nether world using multiverse or server.properties allow-nether: true

### Plugin list:
plotsquared, worldedit, worldguard, essentials, multiverse

### Paper build number:
Paper version git-Paper-86 and before

**Comment by BillyGalbreath** [comment]
Duplicates #3864 and #3720

**Comment by Hyronymos-Old** [comment]
note: this bugg exist in all paper build on 1.14 and 1.15 too

**Comment by Chew** [comment]
As Billy stated, this is a duplicate of #3864, which is currently open. Please track the progress there instead, have a good day!
