### ISSUE TITLE
After upgrading to paper spigot, chunks appearing partally loaded is super common when flying with elytra.

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3887]
After a server I play on upgraded to paper 1.16.1, many of the players noticed that chunks will partially load or take a long time to load when using elytra. Surrounding chunks will load fine sometimes leaving holes. Its very random. At first we thought this was an issue with minecraft 1.16.1 itself. But this all started happening after the server upgraded. This never happens on single player. I decided to join another popular server that uses vanilla 1.16.1 and this issue did not arise. We never encountered this when we used regular spigot.

I don't have much information on the server as I am not the owner. We are likely using the latest version of paper spigot. If anyone else has this issue please comment the specs of your server.

![2020-07-11_17 57 58](https://user-images.githubusercontent.com/59069249/87234567-47805d80-c3a0-11ea-9710-6053855ff50f.png)

![2020-07-11_17 57 52](https://user-images.githubusercontent.com/59069249/87234561-36375100-c3a0-11ea-9967-c6a3e06c878c.png)

![2020-07-11_17 57 04](https://user-images.githubusercontent.com/59069249/87234563-3d5e5f00-c3a0-11ea-85c8-47ec9beb0c93.png)

What I mean by partially loaded, sometimes you can see grass in a chunk but the rest is empty. Super weird.

**Comment by ghost** [comment]
If anyone else has this issue in your server please reply with what you are using.

**Comment by MiniDigger** [comment]
> We are likely using the latest version of paper

yeah, thats not helpful in any way. please post the output of /version

**Comment by chickeneer** [comment]
The abstract issue of chunks not loading properly is not a new one. The lack of overall details in this issue leads me to close it at this time. In favor of another ticket which will involve a reporter able to work with the Paper team on troubleshooting the whole scope of a server.
Paper's Discord may be a good place to seek support as well!
