### ISSUE TITLE
Anti-XRay not working when loading a world

### ISSUE THREAD

**Issue by AoElite** [PaperMC/Paper#3888]
### What behaviour is expected:
Anti-XRay should work for worlds that are generated/loaded after the server starts up.

### What behaviour is observed:
Anti-XRay  doesn't work for worlds that are generated/loaded after the server starts up.

### Steps/models to reproduce:
Set anti-xray to false & set the per world config for the world you want to true. Load the world after the server starts.

Example:
`World world = new WorldCreator("uhcworld100").createWorld();`
Config: https://pastebin.com/gRFv5KjY

### Plugin list:
ProtocolLib, ViaVersion, Luckperms, and just my own custom plugins

### Paper build number:
1.15.2 Paper build 378

**Comment by stonar96** [comment]
Cannot reproduce. I have tested this on git-Paper-378 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT). I made this plugin:
```java
    @Override
    public void onEnable() {
        new BukkitRunnable() {
            @Override
            public void run() {
                Bukkit.createWorld(new WorldCreator("anti_xray_test_world"));
                // Also tested new WorldCreator("anti_xray_test_world").createWorld();
            }
        }.runTaskLater(this, 200);
    }
```
I have used [this](https://paste.gg/p/anonymous/c31f1683573347b48b25e56c7867def9) config. Works as intended.

- Make sure your paper.yml is parsed without errors. (See console.)
- Don't use `/reload` after editing the config. Restart your server.
- Ores which are exposed to air cannot be hidden (especially in `engine-mode: 1`). Check if the ores which you are seeing aren't those ores.
- Check if the ores which you are seeing aren't above your `max-chunk-section-index` setting. Read the [docs](https://paper.readthedocs.io/en/latest/server/configuration.html#anti-xray) for an explanation.
