### ISSUE TITLE
PacketPlayInVehicleMove - Boat Player Crash

### ISSUE THREAD

**Issue by CyberSecGuy** [PaperMC/Paper#3889]
### What behaviour is expected:
Normal boat mechanics

### What behaviour is observed:
[23:46:57 INFO]: Redacted lost connection: Internal Exception: java.lang.NoClassDefFoundError: net/minecraft/server/v1_15_R1/PacketPlayInVehicleMove

### Steps/models to reproduce:
Hop in a boat!

### Plugin list:
Citizens, Essentials, EssentialsChat*, EssentialsSpawn, FindLag*, LuckPerms, Multiverse-Core*, PlugMan, SpigotGuard, Vault, ViaRewind, ViaVersion, Votifier, WorldBorder, WorldEdit, WorldGuard

### Paper build number:
This server is running Paper version git-Paper-86 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
Fix: Time the connect/disconnect and run a /kill on the victim before they get DC'ed again.

**Comment by electronicboy** [comment]
~~Once again,~~ (maybe different person, nvm) enable debug mode in server.properties, see what plugin is causing it

**Comment by aikar** [comment]
It was SpigotGuard in the last report, that plugin does not support 1.16 at least the version you have.
