### ISSUE TITLE
Advanced redstone algorithm

### ISSUE THREAD

**Issue by Graymanflo** [PaperMC/Paper#389]
Hey everyone.

PandaWire plugin (https://www.spigotmc.org/resources/pandawire.26418/) written by md_5 is a advanced redstone algorithm to minimalize redstone lag, I would love to see this algorithm introduced into Paperspigot if possible :).

**Comment by zachbr** [comment]
For the time being we recommend you continue to use the plugin md_5 wrote to port [Panda4994's redstone changes](https://gist.github.com/Panda4994/70ed6d39c89396570e062e4404a8d518).

There are quite a lot of compatibility questions to be answered before we can just throw this at 7000 servers. I don't want to explicitly cross anything off right now but it doesn't seem likely given the extent of the changes. You can't cough near the redstone code without breaking some glitchy machine from 3 years ago.

**Comment by ghost** [comment]
could it break things permanently or corrupt them? or is this plugin safe enough to use and simply remove if something doesn't work?

**Comment by sgdc3** [comment]
it should be safe

**Comment by zachbr** [comment]
This was posted a few days ago in a similar thread on Aquifer.
It shows a behavior change and a potential hurdle.

![Image](https://aquifermc.org/proxy.php?image=http%3A%2F%2Fi.imgur.com%2FVag81gE.jpg&hash=f3789eaf149f9d3f74845e9551252e3d)

**Comment by BiGUNMAN** [comment]
I've been using the plugin around the time its been released, and I haven't received any red stone complaints at all from my players (was done on active server with active redstone users). I have not tested it though so their certainly can be problems as the one mentioned above, but from the point of view of my users, it's been good.

**Comment by sgdc3** [comment]
> This was posted a few days ago in a similar thread on Aquifer.
> It shows a behavior change and a potential hurdle.

I personally like the "new" behaviour, it makes more sense xD

**Comment by Phoenix616** [comment]
I can not reproduce the behaviour displayed on your image @Zbob750. (Using paper 842 and PandaWire 1.0.1)

**Comment by zachbr** [comment]
Not my image, I pulled it from aquifer. If that issue doesn't exist then that's great 👍 
EDIT: relevant aquifer thread: https://aquifermc.org/threads/new-redstone-algorithm.223

**Comment by CeIebrimbor** [comment]
Is this idea stalled? Near future plans? Looks like PandaWire is solid enough with 400 users and zero reports of issues.

**Comment by zachbr** [comment]
Unfortunately there are still major differences between the vanilla redstone mechanics and Panda's changes. I can't see us maintaining another separate version when the plugin exists and does the job fine.

Panda himself expresses some of his reservations with the system here: 
https://www.youtube.com/watch?v=NnkSSs-I8XM
