### ISSUE TITLE
crash again please help

### ISSUE THREAD

**Issue by Sqalhag** [PaperMC/Paper#3898]

**Comment by astei** [comment]
Didn't paste the full crash report, didn't bother using the template, why?

You're out of memory, or a plugin has gone haywire and tried to create a crapton of async tasks.

**Comment by Proximyst** [comment]
The 5th line says exactly what the error is: Out of memory.

Please join the Discord instead of spamming us with trivial issues…

**Comment by aikar** [comment]
as the error says, you ran out of memory. TRy reducing Xmx, please use discord for assistance here.

**Comment by aikar** [comment]
You might also have a bad plugin creating tons of async tasks.
