### ISSUE TITLE
Build 90 (1.16.1) stops Plugin ChatControl AdminChat feature from working (/chc adminchat)

### ISSUE THREAD

**Issue by CapraGenus** [PaperMC/Paper#3899]
### What behaviour is expected:
When using the command /chc adminchat TEST you can send a message to users with admin group.

### What behaviour is observed:
It causes an error and states to check logs

### Steps/models to reproduce:
Install build 90 (1.16.1) and ChatControl 9.0.4
Use command /chc adminchat TEST

### Plugin list:
Plugins (37): AdvancedWarn, BlockParticles, Brewery, ChatControl, Citizens, CitizensCMD, ClearLag, CoreProtect, CraftBook, Denizen, Depenizen, DiscordSRV, dynmap*, Essentials, EssentialsChat, HolographicDisplays, Lands, LibsDisguises, LuckPerms, Multiverse-Core, MythicMobs, OpenInv, PlaceholderAPI, ProtocolLib, Quests, SaneEconomy*, Sentinel, SerialKey, ShopChest, spark, SuperbVote, Vault, Votifier*, WitherAC, WorldBorder, WorldEdit, WorldGuard

### Paper build number:
This server is running Paper version git-Paper-90 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
If you revert to build 87 then the issue is not present and the /chc adminchat command works as expected

**Comment by aikar** [comment]
You forgot to give link to the logs on pastebin

**Comment by Puremin0rez** [comment]
This is probably caused by the new version of bungeecord chat that was made upstream. Your plugin author will have to account for the changes.

That said, it's all guessing games unless you provide real information :P

**Comment by CapraGenus** [comment]
Just checked, yes it looks like it was the upstream update that caused this, will contact plugin dev.
