### ISSUE TITLE
timings memory and print on crash

### ISSUE THREAD

**Issue by EOT3000** [PaperMC/Paper#3902]
**Is your feature request related to a problem? Please describe.**
When I see my server crash when I'm gone, I want to see the timings, as well as memory usage

**Describe the solution you'd like**
When the server crashes, or starts lagging hard enough for watchdog to notice, it should send a link to a timings report. I also want to see server and pc memory usage added to what timings shows to see if that is the reason for the crash/lag

**Describe alternatives you've considered**
Telling everyone to run .timings report when the server is lagging. No memory alternative

**Additional context**
![CaptureRam](https://user-images.githubusercontent.com/43685885/87384865-c75a2380-c56a-11ea-8330-aacf6260aea4.PNG)

**Comment by electronicboy** [comment]
memory information is heavily useless with java, especially when you're using collectors like G1, ontop of how timings records information for those charts, you'd literally end up with nothing actually useful and a lot of people misreading info

automated timing reports is not something I at least would personally feel comfortable deploying, it would be pretty easy to make a plugin which would dump out a timings report when the server starts stalling, however; we do ask that you have some form of limits to avoid flooding the timings server
