### ISSUE TITLE
block pic button do not work if you bind it to different button

### ISSUE THREAD

**Issue by broken1arrow** [PaperMC/Paper#3903]
### What behaviour is expected:
If i use block pic button (my own key binning).
I shall do a command/button push in gui for some plugins.

### What behaviour is observed:
It do nothing if you don't use scroll wheel.
Vanilla minecraft stuff, like pic a stack in creative work.
But in plugins it not work (the event they use, do not work with the better keybindings)

### Steps/models to reproduce:
Change  pic button to one of side buttons on you mouse and it not work.

### Paper build number:
paper 90

**Comment by Proximyst** [comment]
Client issue or user error; nothing we can do.

**Comment by broken1arrow** [comment]
> 
> 
> Client issue or user error; nothing we can do.

NO, it work perfect. But you have to change keybindings to allow more buttons (minecraft self can do it).

**Comment by broken1arrow** [comment]
Also event you use for "block pick" is wrong used.

**Comment by Proximyst** [comment]
The client must send [the Pick Item packet](https://wiki.vg/Protocol#Pick_Item) to use the functionality. The server doesn't know what key is used. If it doesn't work, it's not fixable by Paper.

**Comment by broken1arrow** [comment]
> 
> 
> The client must send [the Pick Item packet](https://wiki.vg/Protocol#Pick_Item) to use the functionality. The server doesn't know what key is used. If it doesn't work, it's not fixable by Paper.

You have to change method to receive Pick_Item (Minecraft handle it not same way as paper and spigot do) , so is not Client issue or user error (you have no problem in vanilla). It is paper/spigot/bukkit error.

And  middleclick has not exist for years (it replace of a scroll wheel whit a button ability not made for use in games).

**Comment by electronicboy** [comment]
I'm not really sure what you're trying to say;

The server can only react on information that is sent to it by the client, e.g. the pick item packet, events are thrown into the handling of this logic;

If you have an actual test case which can prove their is a bug or know the issue, provide a minimal replication case, or submit a PR
