### ISSUE TITLE
Crash (Chunk has both internal and external streams) 1.16.1

### ISSUE THREAD

**Issue by Diederick-DW** [PaperMC/Paper#3905]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___
![image](https://user-images.githubusercontent.com/68290172/87444630-5280fb00-c5f7-11ea-939c-d753d8926daa.png)
![image](https://user-images.githubusercontent.com/68290172/87444681-6167ad80-c5f7-11ea-9f08-894077ae12e3.png)
___

### Plugin list:
___no plugins___

### Actions to reproduce (if known):
___when im standing still nothing goes wrong and if I fly around but when I go in a specific chunk it crashes___

### Paper build number:
___version is 1.16.1.___

**Comment by imDaniX** [comment]
`OutOfMemory`. How much RAM do you allocate for the server in your start script?

**Comment by Diederick-DW** [comment]
It should be enough we have 4GB of ram allocated to the server

**Comment by electronicboy** [comment]
not even paper...
