### ISSUE TITLE
Tripwire hook behavior inconsistent with vanilla when activated by a player riding on horse

### ISSUE THREAD

**Issue by maxzhu273** [PaperMC/Paper#3908]
### What behaviour is expected:
Tripwire hooks produce a continuous redstone pulse when activated.

### What behaviour is observed:
Tripwire hooks "pulse" if activated by the head of a player riding a horse.

### Steps/models to reproduce:
Video and server files used to reproduce:
https://www.dropbox.com/sh/tgu5wli35u2yqpf/AABuVy0O5Kn2Su1NQPV_Kgm2a?dl=0

Video shows behavior on vanilla server jar downloaded from https://www.minecraft.net/en-us/download/server/ then behavior on PaperMC 91

### Plugin list:
None

### Paper build number:
[17:13:02 INFO]: This server is running Paper version git-Paper-91 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
¯\\\_(ツ)\_/¯

**Comment by Proximyst** [comment]
Cannot reproduce on 1.16.2.

**Comment by maxzhu273** [comment]
Can reproduce on 1.16.1 PaperMC-137. Is there a 1.16.2 build I can test on?

**Comment by Chew** [comment]
Yes, check it out here: https://cdn.discordapp.com/attachments/742779128868241550/746543486081171537/1.16.2-r6.jar

**Comment by maxzhu273** [comment]
Can reproduce on 1.16.2-r6
Server files and video: https://www.dropbox.com/sh/96r0r0znr76q6e2/AABBINnyhjsGtSjFIt_P8_Roa?dl=0

**Comment by Chew** [comment]
What is the vanilla behavior?

**Comment by Chew** [comment]
Oh I see, it's in the original video. I'll play around with it too, but this looks pretty confirmed to me.

**Comment by maxzhu273** [comment]
The piston shouldn't be "pulsing". One other thing I should clarify is that the tripwire needs to be at head height of the player -- the tripwire works as intended if placed lower
I made another test setup in 1.16.2 with the vanilla jar and a more concise video https://www.dropbox.com/sh/02eeijkigaijlhg/AACl7qgRCLc9T2-w27XLZpFma?dl=0
