### ISSUE TITLE
fix seedcracking via usage of dungeons

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3909]
**Is your feature request related to a problem? Please describe.**
Players using https://github.com/KaptainWutax/SeedCracker can get the seed of any world with a few or even a single dungeon (the details of this are described in this video: https://www.youtube.com/watch?v=8CKh4x4iK38)

**Describe the solution you'd like**
A custom seed that one can apply, basically like the structure seeds in spigot.yml but for populators such as dungeons

**Describe alternatives you've considered**
Removing dungeons? Not really any valid alternatives

**Comment by hube12** [comment]
Ahah, you can try, that will not fix the issue, salts are really easy to crack ...

Anyway if that post really get traction i can submit a patch that will indeed make all of our effort in seed cracking pointless without disturbing minecraft world gen.

Cheers, 
Neil

**Comment by Brokkonaut** [comment]
Maybe adding an option to use a cryptographic secure prng would help?

**Comment by Puremin0rez** [comment]
@BillyGalbreath ended up "fixing" this by allowing users to specify a seed for dungeons and end pillars (another very quick way to crack world seed). 

Of course this will only fix the issue for new chunks, and it's not really a fix but more of a workaround in the same vein as all the other configurable seeds in spigot.yml

https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0110-Configurable-end-spike-seed.patch
https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0111-Configurable-dungeon-seed.patch

**Comment by KaptainWutax** [comment]
This has horrible side effects-- dungeons are always placed in the same position. On top of that, it's not much of a fix since the floor is still seed dependant.

**Comment by BillyGalbreath** [comment]
> This has horrible side effects

What side effects?

> dungeons are always placed in the same position

Same as villages and monuments and fortresses and so on and so forth.. Putting them on an alternate seed protects the seed. Anyone that cracks the seed using dungeons will have only cracked the dungeon seed, not the others.

> On top of that, it's not much of a fix since the floor is still seed dependant.

Not sure what you mean here..

**Comment by KaptainWutax** [comment]
Just find a dungeon in a chunk, dig in a straight line and all the other dungeons will be there. On top of that, you've only patched the decorator(the thing that picks the start positions) and left out the feature which actually takes care of placing it.

**Comment by BillyGalbreath** [comment]
> Just find a dungeon in a chunk, dig in a straight line and all the other dungeons will be there. On top of that, you've only patched the decorator(the thing that picks the start positions) and left out the feature which actually takes care of placing it.

I'll look into your claims, but I've already has numerous people tell me it works as expected and breaks seed crackers. Seeing as you're a seed cracker creator and aren't being very specific or forthcoming with a proposed solution, please excuse me for being a bit reluctant on jumping to believe you ;)

**Comment by KaptainWutax** [comment]
Oh I put out the tools to get it fixed, I have no intentions of keeping that secret. It will indeed stop my mod from working since it does some assumptions about the position, but in the long run, anyone dedicated enough can still use dungeons to find the world seed. The decorator code does nextInt(16), nextInt(16), nextInt(256) to determine the x, z and y position within a chunk. If you set the seed to be the same, you'll just get the same positions to spit out over and over again for every chunk.

**Comment by KaptainWutax** [comment]
And I am forthcoming when it comes down to it, it's just that this problem is HARD. To completely secure a world seed, the best I can think of involves crypto seeding... and then there's the challenge of having that not deteriorate performance.
