### ISSUE TITLE
Upstream merge Bukkit/Spigot changes.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#391]
Notification to pull upstream Bukkit/Spigot commits. :) Are git tickets fine to notify / remind or would it be better to just ping you on IRC?

**Comment by phase** [comment]
Paper only pulls from Spigot, fyi.

**Comment by zachbr** [comment]
**B**ukkit/**C**raft**B**ukkit/**S**pigot respectively.
And IRC is generally preferable whenever possible. Will be merged here shortly :)

**Comment by mibby** [comment]
Right. I'll ping you on IRC whenever possible then. :) Thanks.
