### ISSUE TITLE
Action Bar don't support new Hex ChatColor

### ISSUE THREAD

**Issue by tarkodev** [PaperMC/Paper#3915]
### What behaviour is expected:
I want to make Hex Color in Action Bar using Paper API

### What behaviour is observed:
The Action Bar don't support custom ChatColor (from bungee) with hex color and make the color black :/

### Steps/models to reproduce:
![image](https://user-images.githubusercontent.com/39101744/87604281-9dcf0280-c6f8-11ea-8af2-dce8e998a593.png)
![image](https://user-images.githubusercontent.com/39101744/87604413-a9bac480-c6f8-11ea-9e56-c1e2edc7ceb9.png)

### Plugin list:
![image](https://user-images.githubusercontent.com/39101744/87602604-922f0c00-c6f7-11ea-9b6d-c9590739595f.png)

### Paper build number:
In 1.16.1 the paper-90

**Comment by tarkodev** [comment]
Up ?

**Comment by HexedHero** [comment]
Have you tried with actual hex not color.red, does it work in Spigot?

**Comment by BillyGalbreath** [comment]
Use components instead of legacy strings. Spigot intentionally make bukkit/spigot API ignorant of hex colors, but coded in a safety for them. Your red shows as black because &x&F&F&0&0&0&0 parsed to just &0 (the last color overrides all previous ones).

**Comment by electronicboy** [comment]
afaik, this is purely a limitation of action bars as a whole, the current way of sending action bars just blows up

**Comment by aikar** [comment]
I believe this was fixed with https://github.com/PaperMC/Paper/pull/3959

If that didn't resolve it, then properly moving to components is going to be your only option anyways.

However you are on an old version, you need to update paper.
