### ISSUE TITLE
Major TPS loss with capable hardware + memory leak?

### ISSUE THREAD

**Issue by neiiljojo** [PaperMC/Paper#3916]
###  Timings or Profile link:
https://timings.aikar.co/?id=0333e77cbd5b4733ba2e42808b121cac
https://timings.aikar.co/?id=87e44f76ed6247208ac82f23ac5e6086s
https://spark.lucko.me/#g3aHtQvKw7
### Description of issue:
       Hello, I have been having some issues with TPS and memory on my 1.15.2 Minecraft server. I have tried optimizing chunk loading (as by timings this is shown as a major cause of TPS loss.). But I am still having tps dip as low as 15 with only around 12 players online. The server is running on three dedicated threads and 10 gb's of ram. I really could use some fresh eyes to take a look at this. 
       Additionally, I have also been having issues with a supposed memory leak, my ram usage will just continue to climb until the server crashes, I have disabled saving advancements, and I am now using the aikar flags which were recommended to me. But I am still not seeing ram return to an idle level even when there is no one on the server.

### Plugin list:
AAC, ActionHealth*, AdvancedBan*, ajStartCommands*, AntiAFK*, AuctionHouse, BetterRTP, BlockParticles, BookNews*, Bot-Sentry-Spigot, BuycraftX, ChatColor2*, ChatManager, ClearLag, CombatLogX, ConsoleSpamFix, CrazyCrates, CubCustomDrops, CustomItems*, DeluxeCommands, DeluxeMenus, DeluxeTags*, DevineDrop*, dynmap*, effectLib*, EmeraldBank, EnchantmentLock, EntityTrackerFixer, Essentials, EssentialsSpawn, FastAsyncWorldEdit, HolographicDisplays, IllegalStack, InfiniteScoreboard, InfoHeads, Item2Chat, ItemManager, JetsMinions*, LaggRemoverPlus*, Lands, LibsDisguises, LightAPI*, LuckPerms, mcMMO, Minepacks, Multiverse-Core, NametagEdit*, ore-control, OreAnnouncer, PetBlocks, PictureLogin, PL-Hide, PlaceholderAPI, PlayerlistPlus*, PlayerWarps, Playtime*, ProtocolLib, PunishmentGUI*, Quests, ServerListPlus*, SilkSpawners, SimpleRename, SmoothSleep, spark, SuperTrails*, SuperVanish, TokenManager, Trade, UltimateStacker, Vault, ViaVersion, VillagerOptimiser, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags. 

### bukkit.yml, spigot.yml, paper.yml, server.properties

Bukkit: https://pastebin.com/cfSYZuQj
Spigot: https://pastebin.com/gdjJhe0F
Paper: https://pastebin.com/b0N8HdBf
Server.properties: https://pastebin.com/mnWmtiQS

### Other helpful links
Here is the most recent timings report (as of 22:13 the 15th of July) 
https://timings.aikar.co/?id=9dbda1f9463d47da86dcc2c38dd71840
To me this shows that it is chunk loading, but if I have the world pre-loaded, should it still be effecting tps this much?

Additionally, I am running a 1:1000 scale map of the earth on my server, which I have pre-loaded for dynmap. It is a massive 40k long world.

### Paper build number:
git-Paper-378 (API version 1.15.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
The issue tracker is not the place for seeking support with timings, please use discord/irc/the forums
