### ISSUE TITLE
Anvil cannot be used

### ISSUE THREAD

**Issue by Ing-Ji** [PaperMC/Paper#3923]
### What behaviour is expected:
I should be able to put items in the anvil and rename or enchant or repair the item.

### What behaviour is observed:
After renaming the item the item will not be named and experience will be taken but if the user logs off and logs back on their experience will come back. Also not being able to repair or enchant their item.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
CoreProtect

### Paper build number:
1.16.1

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by rrvk** [comment]
Run `/version` to get the paper build version ;) 
1.16.1 is not the paper build number

**Comment by Ing-Ji** [comment]
> Run `/version` to get the paper build version ;)
> 1.16.1 is not the paper build number

I'm am extremely sorry. The version is this 
git-paper-92 (MC: 1.16.1)

It seems that I am three versions behind
You are 3 version(s) behind

How can I update the versions?

**Comment by tackleza** [comment]
You can update by re-download from
https://papermc.io/downloads

**Comment by Proximyst** [comment]
Cannot reproduce on 1.16.2.
