### ISSUE TITLE
New Tree Types spawning into blocks above

### ISSUE THREAD

**Issue by 12xx12** [PaperMC/Paper#3924]
I speek about a indoor tree placement while using bonemeal to grow it

### What behaviour is expected:
Trees not generating or generating in smaller size if there is no space above it.

### What behaviour is observed:
If there are blocks above the tree sometimes trees are generated higher then the first block above it. The tree doesn't replace any blocks above it.

### Steps/models to reproduce:
I used a room seven block high and planted both funguses and used bonemal on them. They grow, but sometimes the behaviour described above happens

### Plugin list:
ClearLagg, CommandHock, Essentials, EssentialsChat, ImprovedTimber (my own mod) LuckPerms, Vault, WorldEdit, Worldguard.

### Paper build number:
Paper#91

### Anything else:
![2020-07-16_19 52 03](https://user-images.githubusercontent.com/44411062/87705241-e68cc700-c79d-11ea-9390-514d62d2f824.png)

I removed some "leaves" to make the stem more visible
Edit: The trees spawned like that except for some "leaves" on the left tree

**Comment by MrIvanPlays** [comment]
Paper doesn't modify the generator's behaviour, perhaps this is a vanilla issue? Can you reproduce using the vanilla minecraft server?

**Comment by 12xx12** [comment]
Working as inteded... RTFM
