### ISSUE TITLE
some chunks not being lit properly in generation

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3927]
### What behaviour is expected:
Chunk generating with normal light

### What behaviour is observed:
some chunks have large dark spots as can be seen here. https://imgur.com/a/jh5IAmQ

### Steps/models to reproduce:
generate chunks on a paper server

### Paper build number:
paper 93

### Anything else:
Through my testing these patches perhaps seem more common on slower IO?

**Comment by dkfdevil** [comment]
I have this too on my map

But if you type 
/paper fixlight
It fixes the dark spots

**Comment by aikar** [comment]
this was the issue mentioned on discord, duplicate of #3685
