### ISSUE TITLE
Zombie villagers do not drop picked up items when cured

### ISSUE THREAD

**Issue by MagmaChicken999** [PaperMC/Paper#3928]
What behaviour is expected:
According to the Minecraft wiki, zombie villagers should drop items that they have picked up (but not items that they spawn with) when they are cured.

What behaviour is observed:
When they are cured, they don't drop the things they had picked up and instead everything disappears.

Steps/models to reproduce:
Summon zombie villagers in a world, allowing them to pick up armor/tools from the ground. Once one of the zombie villagers is able to pick up the items, cure it using a splash weakness potion and golden apple. Once it is cured, it will not drop the items.

Plugin list:
Just PaperSpigot.

Paper build number:
CraftBukkit version git-Spigot-c3a49df-2f18108 (MC: 1.16.1) (Implementing API version 1.16.1-R01-SNAPSHOT)

**Comment by Proximyst** [comment]
>git-Spigot

You're not even running our software.
