### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#393]
Crash log is too large for a single pastebin, had to make 2 parts.

Part 1 - http://pastebin.com/vBcqR6XY

Part 2 - http://pastebin.com/We6G0v4L

Something about infinitely recursive block flow?

**Comment by zachbr** [comment]
How often are you seeing this?

**Comment by hurrgurl** [comment]
Happened once, in like forever.

**Comment by RoboMWM** [comment]
I'm going to guess this is due to chunkgen + ~~very low RAM (1GB or less)~~ using the `-Xss` flag. I also had similar issues during chunkgen, with recursive flowing water. https://www.spigotmc.org/threads/possible-chunk-generation-error.97403/

**Comment by hurrgurl** [comment]
I don't use `-Xss` flag tho, only `-Xms10G -Xmx10G -XX:+UseG1GC`.

Crashed once in a span of 6 months or so.

**Comment by RoboMWM** [comment]
Now, in some worlds I do use a custom generator, but I also got a similar crash. (Note, this is _not_ my near-vanilla server so I don't care all that much, but still may be helpful.)

https://gist.github.com/RoboMWM/cbca5fc8c329404304ec7a6148ce9ee0
