### ISSUE TITLE
TileEntitySkull from invalid player causing low TPS

### ISSUE THREAD

**Issue by blek-id** [PaperMC/Paper#3935]
### What behaviour is expected:
Plugin that shows offline-mode player skull **SHOULDN'T** causes freeze and sudden TPS drop

### What behaviour is observed:
Plugin that shows offline-mode player skull causes freeze and sudden TPS drop

### Steps/models to reproduce:
1. /give @p minecraft:player_head{SkullOwner:ajdwoiajwdoiajw}
2. place them into a playervault, or an auction, or any plugin that will load the player head in a GUI (in my case, I'm using PlayerVaultsX
3. it lags and freezes the server and causes low TPS when the GUI is opened

### Plugin list:
___A list of your plugins___
spark 1.4.1, PlayerVaultsX 4.1.11

### Paper build number:
Paper 1.15.2, build 379

Some other version I tried:
build 372

### Anything else:
Spark sampler showing where the spike occurs:
https://spark.lucko.me/#oUdD4BbsqL //with playervaultsX

**Comment by blek-id** [comment]
Issue seems to be similar with #3637, but it's still happening even when using latest build

**Comment by blek-id** [comment]
Issue seem to only happen on build 355 onward, it works fine on 354

**Comment by MrIvanPlays** [comment]
Seems like this is the culprit commit? https://github.com/PaperMC/Paper/commit/a70618cd5cb493fe9fe2a2a7375a7b1949d427d7

**Comment by blek-id** [comment]
I believe so, as stated on https://papermc.io/ci/job/Paper-1.15/355/

> Make Skull Texture Lookup use the User Cache (commit: a70618c) (details / githubweb)
