### ISSUE TITLE
Create inventories with name using Text Components  

### ISSUE THREAD

**Issue by CadyKing** [PaperMC/Paper#3943]
**Is your feature request related to a problem? Please describe.**
No easy to create an inventory using Text Components

**Describe the solution you'd like**
Methods added to Bukkit class that would take BaseCompant[] instead of String to create an inventory name

**Describe alternatives you've considered**
Could use BaseCompant.toLeagcyText() but not everything supports it all the way

**Comment by CDFN** [comment]
Why would it take BaseComponent array? As I can see in protocol, using BaseComponent would be possible since [Open Window](https://wiki.vg/Protocol#Open_Window) takes `Chat` data type as title.

**Comment by Proximyst** [comment]
Because `BaseComponent[]` is the way to represent more than 1 `Chat` in this API.

**Comment by kashike** [comment]
We are handling this another way - tracking in #4830.
