### ISSUE TITLE
Strange "World.isOutsideWorld" Error on World Teleport Command

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#3947]
Using paper version 97 this error occurs, and it does not occur on version 93.

Using Multiverse to teleport to another world using /mvtp world_the_end creates this error on screen:
https://cldup.com/ObJNZrQnHF.jpg

And this error in console:
https://hastebin.com/koyuwocaso.md

When teleporting using PopulationDensity, I receive this error in console (none in game):
https://hastebin.com/gunuyajise.bash

**Comment by Proximyst** [comment]
Duplicate #3934, fixed by #3942

**Comment by ghost** [comment]
This also occurs on paper version 100.

**Comment by Proximyst** [comment]
Fixed by #3934. It's not merged yet.

**Comment by SpacePuppeh** [comment]
This also occurs on paper version #100.
