### ISSUE TITLE
Incorrect spawn reason for monsters (again) 1.15.2 v379

### ISSUE THREAD

**Issue by pluttotv** [PaperMC/Paper#3949]
### What behaviour is expected:
custom or plugin summoned mobs to have spawn reason of CUSTOM or PLUGIN
same for spawners -> bobs spawned from a spawner should have the spawn reason SPAWNER

### What behaviour is observed:
both summoned by plugin or spawner gave me DEFULT result spawn.

### Steps/models to reproduce:
on entity death:
if (e.getEntity().getEntitySpawnReason() == org.bukkit.event.entity.CreatureSpawnEvent.SpawnReason.SPAWNER
                || e.getEntity().getEntitySpawnReason() == org.bukkit.event.entity.CreatureSpawnEvent.SpawnReason.SPAWNER_EGG
                || e.getEntity().getEntitySpawnReason() == org.bukkit.event.entity.CreatureSpawnEvent.SpawnReason.CUSTOM) {

            System.out.println("SPAWNED BY SPAWNER ,egg or CUSTOM");
}

Edit:
using summon of essential gives DEFAULT, yet summoning with my plugin gives CUSTOM
checking it all on entityDeathEvent

### Plugin list:
only my own developed plugin and essential

### Paper build number:
v379 on 1.15.2

### Anything else:
i saw there was a fix to 1.16
on a topic 2 weeks old
https://github.com/PaperMC/Paper/issues/3708

so i dont know... to be honest around 333 build it worked perfect as im using this code for a while
and now i checked stuff related to it and found out it got broke -> like i can check spawn reasons for mobs.

**Comment by pluttotv** [comment]
System.out.println("CALL CHECK RESOPAWN: " + e.getEntity().getEntitySpawnReason());
gives default :(

**Comment by pluttotv** [comment]
also in EntitySpawnEvent spawned mobs from spawner says its default, as no reason was set.

**Comment by ploppyperson** [comment]
Still an issue

**Comment by Chew** [comment]
No need to pointlessly bump issues, especially if they're still issues. Please refrain from replying unless you have more details to add or it's been fixed.

**Comment by MiniDigger** [comment]
fixed by #4843
