### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by omarrazgui11** [PaperMC/Paper#3952]
Hello I have this crash report :(
[crash.log](https://github.com/PaperMC/Paper/files/4943732/crash.log)
version : 1.2
if ill give you a muffin if you help me

**Comment by omarrazgui11** [comment]
I didnt understand what you mean

**Comment by ghost** [comment]
You're running a version that is not supported. You'll have to update your server to a more modern version to get support.
> [00:43:46] [PaperSpigot Watchdog Thread/ERROR]: PaperSpigot version: git-TacoSpigot-bf023c7d (MC: 1.8.8)

**Comment by electronicboy** [comment]
> outdated

it means that your server version is outdated. You didn't even bother to spend the time to fill in the template, nor did you even provide accurate info in the info you did provide. if you want support, use supported software, and fill in the template...

**Comment by omarrazgui11** [comment]
everyone actually use paper 1.8.8 its factions I cant go on 1.16

**Comment by drunderscore** [comment]
Correct.

But 1.8 isn't supported; you won't get any help here. It's not even called PaperSpigot anymore.
