### ISSUE TITLE
Teleporting doesn't load target chunk, but only chunks around it

### ISSUE THREAD

**Issue by Nowaha** [PaperMC/Paper#3953]
### What behaviour is expected:
When teleporting to a far-away, unloaded location, I expect it to properly load all of the chunks, and especially the one you are standing in.

### What behaviour is observed:
It fully loads all the chunks ___except___ the one you are directly teleported into.
![image](https://user-images.githubusercontent.com/5718297/87875525-04db0880-c9d2-11ea-8fb0-5cc529f5a99b.png)

### Steps/models to reproduce:
Teleport to a unloaded location, i.e. using a plugin like Essentials to go to a /home from spawn just after a server restart. It doesn't ALWAYS happen, sometimes it does sometimes it does not.

### Plugin list:
![image](https://user-images.githubusercontent.com/5718297/87875475-b6c60500-c9d1-11ea-882e-7b9ed99f2b12.png)

### Paper build number:
git-Paper-101
![image](https://user-images.githubusercontent.com/5718297/87875486-c7767b00-c9d1-11ea-9175-a045a152ce83.png)

### Anything else:
There is 0 output in the client logs, and there is 0 output in the server logs.

**Comment by HorusApl** [comment]
Also having this issue.
