### ISSUE TITLE
BSkyblock not loading properly

### ISSUE THREAD

**Issue by PapiCapi** [PaperMC/Paper#3954]
### What behaviour is expected:
___What you expected to see___
The plugin is supposed to load in the next 1/2 minutes

### What behaviour is observed:
___What you actually saw___
The plugin is taking literally hours to load

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Add BentoBox to plugins with the BSkyblock addon

### Plugin list:
___A list of your plugins___
AntiAFK, AntiDecoCombat, AsyncWorldEdit, Bank, BentoBox, BlockLocker, ChatItem, ChestCommands, ChestShop, Core, CoreProtect, DeACourdre, EntityTrackerFixer, EssentialsX, FarmLimiter, Fe, HolographicDisplays, IllegalStack, LuckPerms, ModReq, MultiverseCore, Ontime, OpenInv, Plugman, ProtocolLib, ProtocolSupport, Pvp-Control, RifleChairs, Shopkeepers, Skript, Tab, TokenManager, UltimateeStacker, Vault, VillagerOptimiser, VoidGenerator, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
Paper 101 ( 1.16.1 )

### Anything else:
___Anything else you think may help us resolve the problem___
The BBox developper told me that it should be a Paper issue because it's plugin was just "loading the world" so the problem should come from the loading of the world

**Comment by electronicboy** [comment]
Without logs, etc; We can't see how long it's taking for you...

**Comment by Proximyst** [comment]
World loading works fine on Paper. You or the developer need to provide information as to *what* is happening (from a programmatical perspective).

**Comment by Poslovitch** [comment]
I'm one of the dev.

I'm not sure what's happening here. OP sent me these [startup logs](https://pastebin.com/6B3Ks37g). Everything is seemingly working fine from BentoBox's standpoint: addons are loaded (in the case of BSkyBlock, which is a gamemode, we [create the worlds at that time](https://github.com/BentoBoxWorld/BSkyBlock/blob/97c29e31e6b78cf29b6d2a61e3c76ba6cd213fb4/src/main/java/world/bentobox/bskyblock/BSkyBlock.java#L94)), then enabled.

However, starting at line 1192, this happens:
```
[06:59:47] [Paper Async Chunk Task Thread #0/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:beehive
[06:59:55] [Paper Async Chunk Task Thread #2/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:spawner
[07:00:57] [Paper Async Chunk Urgent Task Thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:air
[07:00:57] [Paper Async Chunk Urgent Task Thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:air
[07:00:57] [Paper Async Chunk Urgent Task Thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:air
[07:00:57] [Paper Async Chunk Urgent Task Thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:air
[07:00:57] [Paper Async Chunk Urgent Task Thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:air
[07:00:57] [Paper Async Chunk Urgent Task Thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:air
[07:03:29] [Paper Async Chunk Urgent Task Thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:light_gray_banner
[07:03:36] [Paper Async Chunk Task Thread #0/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:light_gray_banner
[07:11:26] [Paper Async Chunk Task Thread #1/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:beehive
[07:13:57] [Paper Async Chunk Urgent Task Thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:bee_nest
[07:13:57] [Paper Async Chunk Urgent Task Thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:bee_nest
[07:15:07] [Paper Async Chunk Urgent Task Thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:spawner
[07:16:28] [Paper Async Chunk Task Thread #4/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:spawner
```

I did ask OP to temporarily disable BentoBox. It seemingly made everything work properly again - but this does not provide an explanation as to why it happens. As far as I know, disabling BentoBox makes Bukkit ignore our worlds, thus carrying on with the proper loading of the server.

I could not, however, through my assumptions based on the answers OP provided me, clearly define whether the issue is caused by a world who went nuts, or by BentoBox itself.

EDIT: I have also asked OP to run --forceUpgrade. This had seemingly no effects.

**Comment by PapiCapi** [comment]
Here is an example of the logs ( i killed the process at the end ) : https://pastebin.com/6B3Ks37g

**Comment by electronicboy** [comment]
Nothing useful in there, those warnings are vanilla upgrade logic issues, seeing stuff like
`[09:38:43] [LoginProcessingThread/INFO]: UUID of player LukiGameur8 is 28696b91-905e-4da1-9477-63957f48926a` is hardly reassuring as to what you've got installed on there, especially when it double logs... reproduce without PS, I guess

**Comment by Poslovitch** [comment]
> reproduce without PS, I guess

I don't understand what you mean there.

**Comment by electronicboy** [comment]
ProtocolSupport

**Comment by PapiCapi** [comment]
Actually, my issue is from the time the plugin is taking to enable ( i allocated 16Go to the server with a decent CPU ).
Those warnings are gone after the --forceUpgrade.

I tried disabling ProtocolSupport but nothing changed with the time passed to enable the plugin ( now 2/3 minutes passed ) and it seems to take as long as the others times

**Comment by electronicboy** [comment]
oh, I misread the issue, we'd need sampling information in that case, what's loading chunks? timings report? (without the plugin if needed, just for info)

**Comment by PapiCapi** [comment]
Here is the timings report without the plugin : https://timings.aikar.co/?id=d83f22ae015340488caf8a7ab8b84f40
From what's loading chunks i don't really know, maybe @Poslovitch will be more useful than me

**Comment by PapiCapi** [comment]
I just tried to launch the plugin with the latest build from Spigot and it worked perfectly so for me, the problem is coming from Paper

**Comment by Proximyst** [comment]
Can you try on b93?

**Comment by PapiCapi** [comment]
With paper-93 it's working too.

To explain what i did :
- this morning i updated from paper 90 to paper 100
- found the "bug"
- forceUpgraded this server
- the bug was still appearing with paper 90
- now i tried, with a copy of the server which wasn't forceUpgraded 
- the server copy running paper 93 is working

Really don't know if this is clear and useful but i want to tell you all the informations i have

**Comment by Proximyst** [comment]
Most likely caused by https://github.com/PaperMC/Paper/commit/7db30ebd5768fa12251a017711d41ebfdc96c658 then, as many other issues are…

**Comment by PapiCapi** [comment]
Fixed since the build 122.
Thanks for your help !

**Comment by Chew** [comment]
Issue appears to be resolved! If you are still experiencing this issue on the latest version, don't hesitate to open a new issue. Have a good day!
