### ISSUE TITLE
Server crash - A chunk does never load in PaperLib.getBedSpawnLocationAsync

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#3957]
I just had this crash on my server: https://pastebin.com/raw/cXMLCKNV As you can see there is a chunk not loading and this deadlocked the server.

Because there is only paper and paperlib in the stacktrace, I think its the best to report it here.

The call from essentials is here: https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L411

Paper build: 101

**Comment by A248** [comment]
Based on the source you linked, it may be because Essentials is potentially calling a Bukkit API method async:

```java
            PaperLib.getBedSpawnLocationAsync(user.getBase(), false).thenAccept(location -> {
                if (location != null) {
                    user.getBase().setCompassTarget(location);
                }
            });
```

CompletableFuture#thenAccept's callback can run anywhere, either in the thread completing the future, or the caller thread.

**Comment by Brokkonaut** [comment]
Yes that might be an issue in essentials, but the crash happened before that - during getting the bed location, not during using it.

**Comment by RWoof** [comment]
I had a very similar crash with griefPrevention after updating from 88 to 98, I've also seen a few others post similar issues in the discord: https://github.com/TechFortress/GriefPrevention/issues/889

**Comment by imperium13** [comment]
Just got the same crash on Paper-123
