### ISSUE TITLE
PaperSpigot 1.8.8

### ISSUE THREAD

**Issue by ItsArdo** [PaperMC/Paper#396]
Hello, It been 2 days now and I've haven't found a way to disable passive natural mob spawning, the reason i'm saying passive it because that the only mobs that are currently naturally spawning in my world.

I've tired everything:
- Installed multiverse, to disable spawning - Didn't work.
- Ordered 2 Dev's to make a custom plugin to disable natural mob spawning - Didn't Work
- Went on bukkit.yml, Changed all limits to 0 - Didn't work.

---

I've tried everything, even removing plugins that may conflict that also didn't work. I need support ASAP, i'm using PapersPIGOT 1.8.8, and don't blame paperspigot because i even tried changing my server jar file it still didnt work!

I've also tried Spigot 1.8.8 and other versions of normal spigot, it still didn't work.

I've already tried /gamerule, multiverse etc.. nothing seems to be working. I've even made a totally new world and set the bukkit.yml limits to 0, still no luck.

Please fix this bug as I can't release my server if it not fixed.

My bukkit.yml:

http://pastebin.com/7buNxLND

**Comment by sgdc3** [comment]
Spigot 1.8.8 is no longer supported by the paper devs. :(
