### ISSUE TITLE
EntityTargetLivingEntityEvent not working

### ISSUE THREAD

**Issue by davidmayr** [PaperMC/Paper#3960]
### What behavior is expected:
The EntityTargetLivingEntityEvent doesn't get called when a bee is aggressive without a target. It worked in 1.15
### What behavior is observed:
nothing. It doesn't look like the event is getting called

### Steps/models to reproduce:
make a plugin with the EntityTargetLivingEntityEvent and look for bees.
Please spawn the bees without a target and a high anger level

### Plugin list:
CloudNet-Bridge, CloudNet-Signs, own Plugins.

### Paper build number:
git-Paper-101(MC 1.16.1)

### Anything else:
I don't really think I can do anything for you. It worked in 1.15 and now it doesn't.
I used it to spawn angry bees that should look for a player with specific requirements. And now it is broke.

**Comment by Proximyst** [comment]
Does this also not fire when the bee forgets its target (i.e. it has targetted someone, but then they lose interest)? Them not selecting a target upon being spawned is not what I would call a bug, at least.

**Comment by davidmayr** [comment]
but when i set them an anger level they should search for a target right?
