### ISSUE TITLE
Debug stick updates surrounding blocks

### ISSUE THREAD

**Issue by Phoenix616** [PaperMC/Paper#3962]
### What behaviour is expected:
When changing a block with the debug stuck surrounding blocks keep their values. (E.g. after being changed with a debug stick)

### What behaviour is observed:
The surrounding blocks reset to the "expected" value.

### Steps/models to reproduce:
1. Place two walls next to each other (they should automatically connect)
2. Get debug stick (e.g. with `/give @s debug_stick`)
3. Try to use the stick to remove the connection
4. The other wall always tries to restore the connection when the other one is modified, in Vanilla (and Spigot) it will disconnect

Paper behaviour: [Video](https://i.phoenix616.dev/fUEq87ln.mp4)
Vanilla/Spigot behaviour: [Video](https://i.phoenix616.dev/fPfOhJlj.mp4)

### Plugin list:
None

### Paper build number:
b101 (MC: 1.16.1)

### Anything else:
Works like expected in git-Spigot-0509002-6b95d59.

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0063-Debug-stick-should-not-update-neighbors.patch

**Comment by kickash32** [comment]
duplicate of https://github.com/PaperMC/Paper/issues/2134

**Comment by Phoenix616** [comment]
Nice one github search -.-
