### ISSUE TITLE
per-player-mob-spawns ignored for animal-mobs

### ISSUE THREAD

**Issue by imperium13** [PaperMC/Paper#3963]
### What behaviour is expected:
Mobs spawn around each player using the per player mobcap

### What behaviour is observed:
animal-mobs (cows, sheep, chickens) will not spawn around each player. every other mob will

### Steps/models to reproduce:
Ensure per-player-mob-spawns is set to true.
Run a superflat world (for easier viewing).  /summon a bunch of cows around a player. if a second player comes online or travels away, no animals will spawn.

### Plugin list:
none. just paper

### Paper build number:
This server is running Paper version git-Paper-101 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
This only seems to affect animal mobs.  Everything else (bats, hostiles, aquatic, etc) all seem to be fine.  This was first noticed because mooshrooms stopped spawning on a mushroom island after updating to 1.16.1  (but this was all tested on a fresh paper server, not on the main server).

**Comment by imperium13** [comment]
Loaded in a bunch of mooshrooms with a second player. No animal-mobs spawn around me no matter how long i wait.  (sped up mob-tick for animalmobs to 1 so they should spawn nearly instantly)
![](https://cdn.discordapp.com/attachments/289587909051416579/735004174718074910/unknown.png)


After killing the mooshrooms loaded by the second player, animal-mobs instantly spawn in around me.
![](https://cdn.discordapp.com/attachments/289587909051416579/735004186630160464/unknown.png)

**Comment by imperium13** [comment]
Just tried made a fresh paperclip-1 server and did the tests again.  The problem persists.  animal mobs seem to be using a global mobcap instead of the per-player one that is enabled

**Comment by electronicboy** [comment]
global mob cap is still in play, per-player apply an extra set of limits over the top of the global cap to actually enforce spreading; To me, what you're showing there looks normal, bulk of the animal spawns are from world-gen

**Comment by imperium13** [comment]
when I test it with the hostile mobcap, hostile mobs are spawning per-player as expected.  I upped the speed of mob-tick animal spawns for testing to be the same as hostile mobs so they should be spawning at the same rate.  Not sure why the animals would be treated differently?  

Back on 1.15.2 I believe the per-player mobcap was working for animals as well as hostiles. I can test in the older server as well to be sure and report back.

**Comment by imperium13** [comment]
Ran the test again but using 1.15.2 and paper-348.  The issue is not there.  animal spawns are being treated as per-player as expected.  Something changed thats messing up the per-player mobcap in 1.16.1
![image](https://user-images.githubusercontent.com/11136697/88080686-feb96900-cb44-11ea-94cc-7fcb2e29d291.png)
