### ISSUE TITLE
2 Errors 

### ISSUE THREAD

**Issue by AlfreDGR** [PaperMC/Paper#3966]
### Link/paste of stack trace
https://paste.gg/p/anonymous/cc555e918f18473180b89b930d51f808
https://paste.gg/p/anonymous/e962756321a049988dda7c1dfd214ec1
    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

**Comment by Prof-Bloodstone** [comment]
You didn't fill in the template at all.
The first error is vanilla - note from Aikar:
NOTE: Vanilla has a lot of console spam around No key position_predicate in MapLike for any chunk conversion:
https://bugs.mojang.com/browse/MC-191388
Any comments around "MapLike" are vanilla conversion issues.

Please use discord for assistance with such issues.

**Comment by Prof-Bloodstone** [comment]
The second error is a bug in `My pet` plugin. More detailed info is on PaperMC discord : https://discord.com/channels/289587909051416579/289587909051416579/734439045144510507

Again, please use Discord for assistance with logs and use the search feature.
