### ISSUE TITLE
[1.16.1] Dispenser behavior 

### ISSUE THREAD

**Issue by ArcticRaven** [PaperMC/Paper#3967]
### What behaviour is expected:
___What you expected to see___
Dispensers fire all events properly when using Paper. (Already tested on Spigoop)

### What behaviour is observed:
___What you actually saw___
Levers and Redstone pulses do not fire the same events. 

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
*note that this was done using craftbook
[not working with redstone pulse] https://drive.google.com/file/d/1O8eaL6jaxB4xt--RlBU5Dt4_fgKeXtyQ/view
[Working with lever]https://drive.google.com/file/d/1Ja3XtcJAGKZMvu9r5LqCGvSvlYal8NHy/view?usp=sharing

### Plugin list:
___A list of your plugins___
![image](https://user-images.githubusercontent.com/43667891/88045977-5f34b000-cb1d-11ea-92d9-855d9cd84a0b.png)
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
Paper-92

### Anything else:
___Anything else you think may help us resolve the problem___
Originally located on Paper 90. Tested on Paper-92 and Checked on Spigoot 1.16.1.

This was also semi-tested by Me4502(worldedit/craftbook dev) on Paper-101 but did not check for redstone-pulse activation. 

Discussion with other plugin users noted that the behavior is similar to other redstone related bugs that they are having - but redstone changes are not implemented with and plugins in this instance.

**Comment by Proximyst** [comment]
Cannot reproduce on b111 and CraftBook with:

- Lever directly on the dispenser;
- Button directly on the dispenser;
- Button on target block next to the dispenser;
- Redstone clock with a repeater pointing into the dispenser;
- Redstone clock with a piece of redstone dust pointing into the dispenser.

The fan mechanic always works as expected.

**Comment by Proximyst** [comment]
As this cannot be reproduced and the issue is inactive, I'll close it.
