### ISSUE TITLE
Dragging Items in Inventories 

### ISSUE THREAD

**Issue by NotGeri** [PaperMC/Paper#3969]
Hey.
Recently, we had a strange issue where items started acting weird in players' inventories. It appears to be just a visual glitch and nothing game-breaking but it's rather annoying. 
I'm using **git-Paper-88 (MC: 1.16.1)** with no plugins. Also using a completely vanilla instance of the game. It happens to most players so it's definitely server-side. 
Video of me showcasing this problem: https://geri.lol/c95a7

**Comment by Proximyst** [comment]
Can you reproduce on latest?

**Comment by NotGeri** [comment]
Same issue on 101. https://geri.lol/95d76

**Comment by NotGeri** [comment]
I'm not sure what could be causing this. I started a completely fresh instance of the latest paper and it's not happening there. I removed all the plugins and tested it that way and still happened. I reset my paper, bukkit and spigot configs and still happening.

**Comment by Proximyst** [comment]
Data packs?

**Comment by NotGeri** [comment]
It was a good idea, sadly disabling them doesn't seem to do anything. https://prnt.sc/tlwuud

**Comment by MrIvanPlays** [comment]
Are you sure that's not a client issue? Can you reproduce on vanilla or other upstream projects?

**Comment by NotGeri** [comment]
> Are you sure that's not a client issue? Can you reproduce on vanilla or other upstream projects?

I am almost certain. Doesn't happen anywhere else, no.

**Comment by MrIvanPlays** [comment]
well then that's weird. this looks like a rendering issue however i'm not rly sure how can paper cause this

**Comment by NotGeri** [comment]
It was an issue with some stupid command blocks. They were constantly deleting items with a specific tag. Apparently the game doesn't like that 👀
https://streamable.com/0mgif2
