### ISSUE TITLE
Client crash when entering an island

### ISSUE THREAD

**Issue by PapiCapi** [PaperMC/Paper#3975]
### What behaviour is expected:
___What you expected to see___
Not to crash

### What behaviour is observed:
___What you actually saw___
Client crashes with this message in console: 
"PapiCapi lost connection: Internal Exception: io.netty.handler.codec.DecoderException: VarInt too big"

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Paste this schematic in a world and it will make you crash. If you disconnect you won't be able to reconnect
[IleCrashSky.zip](https://github.com/PaperMC/Paper/files/4959867/IleCrashSky.zip)

### Plugin list:
___A list of your plugins___
AsyncWorldEdit, BedWars, ChatLink, CoreProtect, CrazyCrates, EffectLib*, Essentials, EssentialsChat, EssentialsSpawn, Fe*, HolographicDisplays, KillEffects, KitPvP, LuckPerms, ModReq*, Multiverse-Core, OnTime*, PlugMan, ProtocolLib, ProtocolSupport, Shopkeepers, SkQuery, Skript, TAB, TokenManager, TradePlus, Vault, VoidGenerator, VoxelSniper*, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-100 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Proximyst** [comment]
Reproduce without ProtocolSupport.

**Comment by PapiCapi** [comment]
Okay, seems to be a PS issue. Sorry for the bad report.
In the future i'll always try to disable PS before making an issue. 

Thanks anyway for the help
