### ISSUE TITLE
Closing Minecraft resolves to Black screen

### ISSUE THREAD

**Issue by Diederick-DW** [PaperMC/Paper#3977]
when I click on ''Quit Game'' My screen will go black and then I can't see anything anymore. I can still do everything but the screen stays black. 
anyone who knows what the problem is?

**Comment by electronicboy** [comment]
Nothing to do with paper...

**Comment by Diederick-DW** [comment]
paper?

**Comment by electronicboy** [comment]
This is the issue tracker for the paper server software, this issue has nothing to do with the server software
