### ISSUE TITLE
Foxes not dropping items held in their mouths

### ISSUE THREAD

**Issue by AllenZou123** [PaperMC/Paper#3984]
### What behaviour is expected:
Foxes have a 100% to drop items held in their mouths, so I expected to see something drop upon death, whether it's player based or a natural death.

### What behaviour is observed:
Foxes don't drop items for any type of death. I also tested this on a Paper server with no plugins and foxes still don't drop their items.

### Steps/models to reproduce:
This can be replicated by killing the fox in any way.

### Plugin list:
LuckPerms, ProtocolLib, WorldEdit, and WorldGuard

### Paper build number:
Paper version git-Paper-108 (MC: 1.16.1)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Proximyst** [comment]
Cannot reproduce on b111.

This might have to do with your gamerules and/or server configurations.

**Comment by AllenZou123** [comment]
https://gfycat.com/agreeableimaginativeapatosaur

I downloaded the Paper build that you are using and ran the jar in an empty directory. The video above shows me replicating the bug (the fox had a feather in its mouth).

**Comment by Chew** [comment]
Really made me kill a fox for this 😢. Anyway, using the following steps, I could not reproduce:
1) Booted brand new 1.16.2 server (build 141)
2) Spawned a fox via Spawn egg
3) Gave it a feather
4) I'm sorry, I killed it 😢. It dropped a feather and my heart 😔.

If my reproduction steps don't match yours, let me know. One of the patches from the giant 1.16.2 update may have fixed this.
