### ISSUE TITLE
Paper crashes server on sync chunk load, possibly related to light generation fix in 97?

### ISSUE THREAD

**Issue by RWoof** [PaperMC/Paper#3986]
### Link/paste of stack trace

https://pastebin.com/gaJd7LVw

Another older one will all my plugins:
https://pastebin.com/v2j0F61v

### Plugin list:

I cut back on my plugins to test this out and see if it could be reproduced:
Plugins (16): Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, GriefPreventionFlags, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, ProtocolLib, Vault, ViaBackwards, ViaVersion

### Actions to reproduce (if known):
I've tried to reproduce the crash in a few different ways, I have a feeling it might be related to the version of Java loading Minecraft. 

If I run the same server either Windows 10 Pro with Aikar's Java flags in Java 8 (Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.261-b12) Host: Windows 10 10.0 (amd64)) or Lubuntu 20.04 with the same flags and the default Java version installed on the system (openjdk-14-jre-headless/focal-updates,now 14.0.1+7-1ubuntu1 amd64), it seems stable, running fine for hours.
*Update 7/23/20* After further testing, server still dies with Java 14 in Lubuntu 20.04, ran fine in Windows though.

If I run it on either of my Lubuntu servers running 16.04 or 20.04 using the same flags and Java 8 (openjdk-8-jre-headless/focal,now 8u252-b09-1ubuntu1 amd64) it typically crashes after about 20 minutes to a couple of hours whenever GriefPrevention tries to run it's entity cleanup task in my creative world. The crash occurs even if the server is empty and not running any demanding tasks. I've seen TPS reports of 20.0 within 40 seconds of the server crashing and dying.

### Paper build number:
This server is running Paper version git-Paper-108 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

I have also seen the crash using Paper 98. Paper 88 runs fine and was the last version I used before upgrading and it is still running very stable on my Lubuntu 16.04 server in Java 8.

I can provide a zipped copy of my test server if needed.

**Comment by andris155** [comment]
Same problem

**Comment by Brokkonaut** [comment]
I have similar crashes nearly every day, a lot of different plugins that try to load a chunk and never get it loaded...

**Comment by TNTUP** [comment]
Might confirm but since I don't have Griefprevention installed on the 2nd survival server. 

This might help: https://pastebin.com/5aVa5aYS

**Comment by RWoof** [comment]
I have a zip of my Linux test server, seems to crash every time in both Lubuntu 16.04 and 20.04. Aikar if you're interested I can provide it to you, just let me know how to get it to you. I've mainly tested using Java 8 but it seems to crash with 14 as well. It hasn't made it past 2 hours in my experience so far, sometimes it crashes in as little as a few minutes. File is just under 3gb zipped.

**Comment by mben42** [comment]
Same problem here after upgrading from Paper 86 to 110.

**Comment by RWoof** [comment]
Still happening in 114: https://pastebin.com/tXFzEGa7

I also tried 93 and it seemed fine.

**Comment by RWoof** [comment]
Version 118 ran overnight for me with no crash. Thanks for fixing it!
