### ISSUE TITLE
hasDiscoveredRecipe function?

### ISSUE THREAD

**Issue by gustaavik** [PaperMC/Paper#3987]
**Is your feature request related to a problem? Please describe.**
I want an easy way of checking if the player have discovered a recipe, I noticed that spigot have implemented: [https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/HumanEntity.html#hasDiscoveredRecipe(org.bukkit.NamespacedKey)](url)

**Describe the solution you'd like**
explained above, I want to have a method to check if player has discovered a recipe.

**Describe alternatives you've considered**
Currently you can do HumanEntity.discoverRecipe, and returns true if player can discover it, meaning it havent already been discovered, but this also discovers it, which I dont want it too.

**Comment by Proximyst** [comment]
`Player` extends `HumanEntity` and as such has `hasDiscoveredRecipe`. Just use the method which already exists...

**Comment by Prof-Bloodstone** [comment]
If Spigot has something, so does Paper, since it's based on Spigot.
https://papermc.io/javadocs/paper/1.16/org/bukkit/entity/HumanEntity.html#hasDiscoveredRecipe-org.bukkit.NamespacedKey-

**Comment by gustaavik** [comment]
it doesnt show?

**Comment by gustaavik** [comment]
![image](https://user-images.githubusercontent.com/41763143/88318367-e8fd9c80-cd1a-11ea-871b-86b3e7c27f42.png)

**Comment by Proximyst** [comment]
Use the Paper API. Join our Discord if you wish further assistance.

**Comment by electronicboy** [comment]
This was a recent addition, if you're using maven/gradle, try running a build to get it to pull the updated the dependencies; if you're doing it manually, e.g. adding the jar to your classpath, update the jar
