### ISSUE TITLE
[1.16.1] Server crash, freeze and inaccessible (Watchdog error)

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#3992]
### What behaviour is expected:
No crash.

### What behaviour is observed:
The server has been working perfectly for a month until yesterday it started to Watchdog crash, freeze and become inaccesible.

Crash 1 (23/07/20) https://pastebin.com/z5EGFU2B
Crash 2 (24/07/20) https://pastebin.com/FyLp1kaK

I suspect it may be ServerRestorer because it matches the timing but I'm not sure, the plugin has been working without any problems the entire month...

### Steps/models to reproduce:
I don't know...

### Plugin list:
· ChatMessenger-1.2.4
· CoreProtect-19.1
· LuckPerms-Bukkit-5.1.26
· LWCTrust-1.0.3
· LWCX-2.2.6
· ServerRestorer-1.0.37
· SuggestionManipulator-1.0
· Vault-1.7.3
· VaultChatFormatter-1.0

### Paper build number:
Crash 1: paper-91
Crash 2: paper-110

**Comment by pianwan** [comment]
I don't think it's paper's problem.
Try removing ServerRestorer.
It also seems there is a problem with LWC.

**Comment by Proximyst** [comment]
I/O issues, not related to Paper. Try another way of backups.
