### ISSUE TITLE
Server stopped after trade with villager(Mapmaker, stained glass pane -> emerald)

### ISSUE THREAD

**Issue by seohae7785** [PaperMC/Paper#3993]
### Link/paste of stack trace
https://www.dropbox.com/s/v8pra57ab81bfu4/latest.log?dl=0

### Plugin list:
coreprotect griefprevention gpflag multiverse core skript TAB skript addons(Skbee Skellett skQuery skrayfall skutilities)

### Actions to reproduce (if known):
Server stopped after trade with villager(Mapmaker, stained glass pane -> emerald)
It happen with new villager(my map force-updated from 1.15.2, the past villager doesn't have any problem)

### Paper build number:
git-Paper-93, git-Paper-101 both have same problem

**Comment by Phoenix616** [comment]
Duplicate of #2312
