### ISSUE TITLE
Random crash 1.15.2

### ISSUE THREAD

**Issue by DennyResx** [PaperMC/Paper#3995]
The server has worked perfectly for months. Then, at some point, I updated Paper (from 347 to 380) and after a restart:
#1 https://pastebin.com/3jWkvkM0
#2 https://pastebin.com/D8RUSZcb
#3 https://pastebin.com/qQz0sA17
#4 https://pastebin.com/SWqMj7Lg
 
Then I disabled the async chunk load in paper.yml and the server held up for half an hour.
Afterwards, it lagged (as before) and a few seconds later it crashed:
#5 https://pastebin.com/ntGCytGH
 
I restarted it and after a few seconds:
#6 https://pastebin.com/kfaBVdas
#7 https://pastebin.com/EXWXsFFm
 
I tried to use Paper #379 and Paper #349 with a previous backup but nothing. I use Aikar's flags with 6GB of RAM. I tried with 4.5GB of RAM, too. My KVM specs: https://pastebin.com/FrWhmC5A (4 cores)

### Plugin list:
Plugins (55): AntiAFKPlus*, AnvilRestrict, BattlePass, BeastWithdraw, ChatGames*, ChestShop, Citizens, ClearLag, CombatLogX, CommandCooldown*, CoreProtect, CraftingStore, CrazyCrates, DeluxeMentions, DonatorJoinPlus, EpicFarming, EpicFurnaces, Essentials, EssentialsChat, EssentialsSpawn, ezAuctions, FabledSkyBlock, GUIPlus, HolographicDisplays, HolographicExtension, ItemRenamerReloaded, LuckPerms, Matrix, MidniteCore, Multiverse-Core, Multiverse-Inventories, MyCommand, OpenInv, PlaceholderAPI, PluginHiderPlus*, ProtocolLib, PublicCrafters, Rankup, ServerRestorer, ShopGUIPlus, SpigotPing, SuperTrailsPro*, TAB, TelegramBotsAPIPlugin*, TelegramReporter*, UltimateRepairing, UltimateStacker, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGenerator, VoidSpawn, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Start the server and wait for it to crash.

### Paper build number:
#349, #379, #380

**Comment by IamBartjuuh** [comment]
I am having the same issue on paper build #370

Plugins (49): AdvancedChatTorch*, AdvancedHelp, BeastWithdraw, ChatSentinel, ChestShop, CoinFlipper*, CommandPanels, CoreProtect, CraftingStore, CrazyAuctions, CrazyCrates, DeluxeJoin, EffectLib*, EpicHoppers, EpicSpawners, Essentials, EssentialsChat, EssentialsSpawn, FabledSkyBlock, HolographicDisplays, HolographicPlaceholders, ItemInChatFree, Lottery, LuckPerms, MovingDevApi, Multiverse-Core, MysteryBoxes, NerfPhantoms, PlaceholderAPI, PlayerParticles, PluginHiderPlus*, PlugMan, ProtocolLib, Reports, RewardPRO, ServerlistMOTD*, ShopGUIPlus, Trade, UltimateKits, UltimateModeration, UltimateRepairing, UltimateStacker, Vault, ViaVersion, Votifier*, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags

Still searching for the problem will let you know when I find something.

**Comment by IamBartjuuh** [comment]
The issue is that when both FabledSkyblock and UltimateStacker are used in the same server on the latest version the server give crash report when a player joins. Reported this [https://support.songoda.com/plugins/servlet/desk/portal/3/SD-6590](url) For now use this version. This one is the latest which worked. [https://songoda.com/product/ultimatestacker-the-simple-to-use-stacker/download/1.11.17](url)

**Comment by IamBartjuuh** [comment]
> 
> 
> The server has worked perfectly for months. Then, at some point, I updated Paper (from 347 to 380) and after a restart:
> #1 https://pastebin.com/3jWkvkM0
> #2 https://pastebin.com/D8RUSZcb
> #3 https://pastebin.com/qQz0sA17
> #4 https://pastebin.com/SWqMj7Lg
> 
> Then I disabled the async chunk load in paper.yml and the server held up for half an hour.
> Afterwards, it lagged (as before) and a few seconds later it crashed:
> #5 https://pastebin.com/ntGCytGH
> 
> I restarted it and after a few seconds:
> #6 https://pastebin.com/kfaBVdas
> #7 https://pastebin.com/EXWXsFFm
> 
> I tried to use Paper #379 and Paper #349 with a previous backup but nothing. I use Aikar's flags with 6GB of RAM. I tried with 4.5GB of RAM, too. My KVM specs: https://pastebin.com/FrWhmC5A (4 cores)
> ### Plugin list:
> 
> Plugins (55): AntiAFKPlus*, AnvilRestrict, BattlePass, BeastWithdraw, ChatGames*, ChestShop, Citizens, ClearLag, CombatLogX, CommandCooldown*, CoreProtect, CraftingStore, CrazyCrates, DeluxeMentions, DonatorJoinPlus, EpicFarming, EpicFurnaces, Essentials, EssentialsChat, EssentialsSpawn, ezAuctions, FabledSkyBlock, GUIPlus, HolographicDisplays, HolographicExtension, ItemRenamerReloaded, LuckPerms, Matrix, MidniteCore, Multiverse-Core, Multiverse-Inventories, MyCommand, OpenInv, PlaceholderAPI, PluginHiderPlus*, ProtocolLib, PublicCrafters, Rankup, ServerRestorer, ShopGUIPlus, SpigotPing, SuperTrailsPro*, TAB, TelegramBotsAPIPlugin*, TelegramReporter*, UltimateRepairing, UltimateStacker, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGenerator, VoidSpawn, WorldEdit, WorldGuard
> ### Actions to reproduce (if known):
> 
> Start the server and wait for it to crash.
> ### Paper build number:
> 
> #349, #379, #380


The issue is that when both FabledSkyblock and UltimateStacker are used in the same server on the latest version the server give crash report when a player joins. Reported this [https://support.songoda.com/plugins/servlet/desk/portal/3/SD-6590](https://support.songoda.com/plugins/servlet/desk/portal/3/SD-6590) For now use this version. This one is the latest which worked. [https://songoda.com/product/ultimatestacker-the-simple-to-use-stacker/download/1.11.17](https://songoda.com/product/ultimatestacker-the-simple-to-use-stacker/download/1.11.17)

**Comment by astei** [comment]
Or, even better, don’t use broken, shitty Songoda plugins!

**Comment by DennyResx** [comment]
Thank you IamBartjuuh. Does it also work with version 2.3.5 of FabledSkyblock? I had tried using 2.2.12

**Comment by IamBartjuuh** [comment]
They have update both ultimatestacker and fabledskyblock it should work on latest versions.

**Comment by DennyResx** [comment]
Ok, thanks
