### ISSUE TITLE
Changing complexity in server.propirties doesn't work

### ISSUE THREAD

**Issue by Saharo4eks** [PaperMC/Paper#3999]
Hello, I'm trying to change the complexity in the server.propirties file, but it doesn't change on the server.

Now my line looks like this: difficulty=hard
But on the server, I still get a light (standard) complexity

Paper#115 [1.16.1]

**Comment by MissPotato** [comment]
Have you restarted the server after making this change?

**Comment by aikar** [comment]
As part of making difficulty properly do it 'per world', it broke being able to change it by the file, as the file is now only used for initial world creation.

You may change difficulty in game using the /difficulty command to set it to desired difficulty.

**Comment by Machine-Maker** [comment]
Is this a bug still? Aikar said that changing difficulty in `server.properties` is only used for initial world creation.

**Comment by Proximyst** [comment]
Difficulty works in the same way as gamerules do: it's a per-world thing. Due to this, I'd argue we shouldn't change it as this is expected behaviour with Bukkit. There's no need to create inconsistency after all.
