### ISSUE TITLE
[1.16.1] #116 Server crash

### ISSUE THREAD

**Issue by ASlepushko** [PaperMC/Paper#4001]
### Link/paste of stack trace

   [Link to paste.gg/p/anonymous/541785462d5e468bae8c59eff0283d08]( https://paste.gg/p/anonymous/541785462d5e468bae8c59eff0283d08)

### Plugin list:
AdvancedBan
AdvancedTeleport
AmkMcAuth
AntiAura (Premium)
Chatty
DonateLink
GSit
LuckPerms
ProtocolLib
TAB
TradeSystem
Vault
worldedit-bukkit
WorldEditSUI
worldguard-bukkit
worldguardextender

### Actions to reproduce (if known):
don't know but it continuously. Probably when teleport from worlds. IDK.

### Paper build number:
116

**Comment by MrIvanPlays** [comment]
#3986

**Comment by Proximyst** [comment]
@MrIvanPlays Please read the crashlog before linking to other issues. These aren't related at all.

**Comment by MrIvanPlays** [comment]
> @MrIvanPlays Please read the crashlog before linking to other issues. These aren't related at all.

idk but it seems to me the origins come from the same problem.

**Comment by Proximyst** [comment]
@MrIvanPlays One is sync chunk loads and lighting fighting, the other is entity tracking not being thread-safe. They are not related at all.

**Comment by yannic-md** [comment]
same problem here. In normal spigot is it working.

**Comment by yannic-md** [comment]
Still hoping for a fix..

**Comment by aikar** [comment]
No information has been provided to even suggest this is a Paper issue.


This looks like its caused by a plugin.

**Comment by MrIvanPlays** [comment]
Try reproducing on latest build (to the creator of the issue)

**Comment by yannic-md** [comment]
@Alword

**Comment by R4zzerYT** [comment]
I think its fixed at me since the newest update @aikar :)

**Comment by ASlepushko** [comment]
@aikar Yes, it does caused by a plugin. With new AntiAura it works well.
