### ISSUE TITLE
[1.16.1] Watchdog termination causes an indefinite hang instead of stopping

### ISSUE THREAD

**Issue by SRLcore** [PaperMC/Paper#4008]
### What behaviour is expected:
When the Watchdog forces a server crash, I expect to see the server actually crash and stop.

### What behaviour is observed:
When the Watchdog forces a server crash, the server does not stop and hangs indefinitely.

This is caused by the server encountering a deadlock, which hangs the server indefinitely during shutdown. The deadlock occurs in `MinecraftServer::stop` locking on `stopLock`. 

When the `WatchdogThread` triggers a crash and is unable to shutdown safely, it calls `server.close()`, which subsequently calls `MinecraftServer::stop` from its own thread, which initially acquires the `stopLock` lock. Inside of this `synchronized(stopLock)` section, there is an infinite loop that waits for the main server thread to die. 

Unfortunately, this is where the trouble happens. Inside of the main server thread's `MinecraftServer::v`, there is a `finally` block that the JVM requires execute prior to allowing that section to finish (and thus allowing the main server thread to terminate). Inside of this `finally` block, the main thread calls `this.stop()`, which immediately goes on to try to acquire the same `stopLock` that the `WatchdogThread` is already holding. 

Because of the infinite loop awaiting termination inside of the `MinecraftServer::stop` method, and because it occurs inside of a critical section guarded by `stopLock`, and because `stop` is called from 2 separate threads, the server hangs indefinitely until it is killed externally.

### Steps/models to reproduce:
Find a way to trigger the `WatchdogThread` to stop the server using the `server.close()` method.

### Plugin list:
(not relevant, but providing for completeness)
- CoreProtect 19.1
- DiscordSRV Build-1.19.2-SNAPSHOT-821a160
- Dynmap 3.1-beta-1-spigot-367
- EssentialsX 2.18.0.7
- EssentialsXChat 2.18.0.7
- EssentialsXSpawn 2.18.0.7
- Harbor 1.6.2-SNAPSHOT-9fe4e38
- IllegalStack 2.1.7c
- LuckPerms Bukkit-5.1.81
- OreAnnouncer 2.6.2-fork
- ProtocolLib 1.6.1-893
- ServerListPlus 3.4.8-Universal
- Vault 1.7.3
- WitherAC 0.21.2
- WorldBorder 2.0.9
- worldedit bukkit-7.2.0-SNAPSHOT-5187
- worldguard bukkit-7.0.4-SNAPSHOT-2059

### Paper build number:
`git-Paper-116 (MC: 1.16.1)`

### Anything else:
- Server log of the (legitimate) watchdog crash (doesn't show anything other than the server continue to run after it should be stopped): https://pastebin.com/GY9ThDHG
- jstack thread dump taken several _hours_ later, showing the deadlock: https://pastebin.com/tdbgq5hd

In the latter thread dump, you can find the deadlock by searching for `BLOCKED`, which will show the relevant deadlocked sections (`0x000000060a85d4a8` is the `stopLock`). Reproducing relevant threads below:
```
"Server thread" #31 prio=7 os_prio=0 cpu=12189415.29ms elapsed=78765.55s tid=0x000055fa2c8f6000 nid=0x5c waiting for monitor entry  [0x00007f27a9de4000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:754)
	- waiting to lock <0x000000060a85d4a8> (a java.lang.Object)
	at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:699)
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1047)
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
	at net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$3036/0x00000008008f8840.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.7/Unknown Source)
```
```
"Paper Watchdog Thread" #48 prio=7 os_prio=0 cpu=669179.74ms elapsed=78764.83s tid=0x000055fa2d311800 nid=0x6a sleeping [0x00007f27b0910000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(java.base@11.0.7/Native Method)
	at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:763)
	- locked <0x000000060a85d4a8> (a java.lang.Object)
	at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:699)
	at net.minecraft.server.v1_16_R1.MinecraftServer.close(MinecraftServer.java:737)
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:157)
```

**Comment by Brokkonaut** [comment]
I can confirm this issue

**Comment by radiant-ai** [comment]
I do confirm this as well, when server crashes because of some bad plugins the only way to stop it is to kill -SIGKILL it and start it up manually

**Comment by PhanaticD** [comment]
happens on 1.15.2 as well
