### ISSUE TITLE
1.16 Gamemode Selector Permissions

### ISSUE THREAD

**Issue by Laarryy** [PaperMC/Paper#4012]
**Is your feature request related to a problem? Please describe.**
1.16 gamemode selector shortcut (f3+n, etc) doesn't have a permission, so OP is required to use it.

**Describe the solution you'd like**
Add a permission to paper that is assigned to that action, possibly even for each potential outcome (per-gamemode), though that wouldn't really fit with the previous f3+n permission which was just the same as the one to switch gamemode iirc(as survival wasn't part of that toggle).

**Describe alternatives you've considered**
Add it to bukkit? Seems a stretch though, so thought I'd ask here to get some more information and request it.

**Comment by MiniDigger** [comment]
duplicate of #4986
