### ISSUE TITLE
[1.16.1] InventoryOpenEvent when cancelled still plays the chest opening sound.

### ISSUE THREAD

**Issue by JamesPeters98** [PaperMC/Paper#4017]
### What behaviour is expected:
Chests should make no sound when the InventoryOpenEvent is cancelled.

### What behaviour is observed:
Chest plays the Open sound and then immediately after plays the Close sound.

### Steps/models to reproduce:

```
@EventHandler
public void onInventoryOpen(InventoryOpenEvent event){
    event.setCancelled(true)
}
```
Then try and open a chest.

### Plugin list:
None

### Paper build number:
This server is running Paper version git-Paper-117 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by ignissak** [comment]
I'd say you should use PlayerInteractEvent instead of InventoryOpenEvent.

**Comment by Proximyst** [comment]
```java
            Container container = itileinventory.createMenu(this.containerCounter, this.inventory, this); // This sends the open effect

            // CraftBukkit start - Inventory open hook
            if (container != null) {
                container.setTitle(itileinventory.getScoreboardDisplayName());

                boolean cancelled = false;
                container = CraftEventFactory.callInventoryOpenEvent(this, container, cancelled); // This calls the open event
```

The event is called *after* the effect. You can use `PlayerInteractEvent` if you want to cancel it before the open effect.

**Comment by Chew** [comment]
Closed as it appears to be intentional. See above comments.
