### ISSUE TITLE
[1.16.1] Villager trade crash

### ISSUE THREAD

**Issue by JKerboeuf** [PaperMC/Paper#4019]
Trading with some Villagers crashes the server, also watchdog can't stop the server, but this has already been reported in #4008 
**update: it seems like it is when trading glass panes with cartographers**

https://pastebin.com/D6u22hmP

plugin list :
- BetonQuest 1.12.0-DEV-90
- Brewery 2.1.1
- BungeeTabListPlus_BukkitBridge-3.3.3.jar
- BuycraftX.jar
- Citizens 2.0.27-b2069
- CMI 8.7.3.4
- CMIEInjector 1.0.2.3
- CommandNPC 1.9.1
- CrazyAuctions 1.2.15
- CrazyCrates 1.10.1-SNAPSHOT
- DynamicShop 2.11.7
- EntityDetection 1.1.3 build 21
- EntityWatch 2.7
- griefdefender 1.4.7
- Guilds 3.5.5.3
- HeadDatabase 4.12.4
- item-nbt-api 2.4.1
- LimitPillagers 2.13.0
- LogBlock 1.16.1.1
- LuckPerms 5.1.73
- MaSuiteCore
- MaSuiteHomes
- MaSuiteTeleport
- MMOItems 5.5.3-SNAPSHOT
- MMOLib 1.2.4
- Multiverse-Core 4.0.0
- MysqlPlayerDataBridge 3.34.0
- NoCheatPlus 3.16.0-RC-sMD5NET-b1134
- orereplacer 1.0.1.13.16a
- PlaceholderAPI 2.10.7
- ProtocolLib 4.5.1-SNAPSHOT-b445
- QuickShop 4.0.3.3
- RedstoneClockDetector 1.2.1
- SAML 2.0.0
- SimpleEntityTracker 1.0
- Smeltery 1.0-SNAPSHOT
- spark 1.4.2
- StackMob 5.2.3
- TAB 2.8.1
- Vault 1.7.3
- VillagerOptimiser 1.1.3
- worldedit 7.2.0-beta-02
- worldguard 7.0.4-beta1

**Comment by radiant-ai** [comment]
I had the same issue and thus decided to test. When I trade the glass panes server freezes but does not crash, if I trade even more it gives the same watchdog errors with a very hard freeze for 10-20 seconds.

**Comment by JKerboeuf** [comment]
It probably depends on the load on the server, on a server with no plugins, it just freezes for some time, but we have 50+ plugins, and a lot loaded so the server doesn't survive the freeze

**Comment by MrIvanPlays** [comment]
Can reproduce

**Comment by electronicboy** [comment]
Duplicate of #2312
