### ISSUE TITLE
[1.16.1] AABB / VoxelShape Related Crash

### ISSUE THREAD

**Issue by remdui** [PaperMC/Paper#4021]
### Link/paste of stack trace

https://pastebin.com/5pHQKB9x

I know it says DO NOT REPORT TO..., but we have been trying to deal with this for 2-3 weeks now. Tried a backup image of the server even before the crashes, can't seem a way to get rid of the crashes.

### Actions to reproduce (if known):

1) Start the server
2) Let players play the survival gamemode
3) After a random amount of time, sometimes 1 hour, sometimes 12 hours, the server will become unresponsive for the players (async chat still functions)
4) The latest commands that are performed before the crash are almost always teleportation commands (/warp, /rtp, /tp, /home). These are from different plugins, no relation between them except for teleporting the player and loading new chunks.
5) The stack trace pasted above is found in the console, always identical. 

### Paper build number:
Tested all version between paper-83 (the version we had before the crashes started occurring) and paper-121

**Comment by remdui** [comment]
Okay we found the bug!

When flying with an elytra with a certain minimum velocity and then performing a teleport command, the server will stop responding.

This happens due to the setting  

prevent-moving-into-unloaded-chunks = true

in paper.yml 

When disabling the setting the crash will not occur.

**Comment by remdui** [comment]
Okay not fixed with prevent-moving-into-unloaded-chunks set to false.

But it won't crash. Only a severe lag spike is noticed, with the same stack trace as in the first post.

**Comment by remdui** [comment]
Sorry for the long solo posting...

Manually fixed this within some plugins by inserting

 p.setVelocity(new Vector().zero());

 before doing the actual teleportation. But this seems more like a hack to me. It should probably be fixed within Spigot/Paper.

**Comment by electronicboy** [comment]
This is one of those long standing issues, manually resetting the velocity works in some cases but not all, this defo needs a better fix; There are also some improvements to that option to help which are apparently in the pipeline somewhere

**Comment by hurrgurl** [comment]
Had this issue for months, I'll try your solution. Great find!

**Comment by crazykidney** [comment]
Also had this problem for quite some time, resetting velocity for teleports feels weird.
