### ISSUE TITLE
[1.16.1] Server Crash

### ISSUE THREAD

**Issue by yurinogueira** [PaperMC/Paper#4022]
In the Paper 93 version the crash does not happen.

### Link/paste of stack trace
[Link](https://paste.gg/p/anonymous/c38d9d836d6a43039c7dba7b8056cdce)

### Plugin list:
AsyncWorldEdit, AuthMe, ChestShop, ChestTerminal, Citizens, CS-CoreLib, DiscordSRV, dtlTraders, EterniaLib, EterniaServer, ExoticGarden, FogusCore, GoldenCrates, GoldenEnchants, GriefPrevention, GriefPreventionFlags, HackedCore, HackedServer, HolographicDisplays, LiteXpansion, LuckPerms, mcMMO, MobFarmManager, Multiverse-Core, Multiverse-Inventories, MyPet, PlaceholderAPI, ProtocolLib, SimpleClans, SkinsRestorer, Slimefun, TAB, Vault, VillagerOptimiser, Votifier, VotingPlugin, WorldBorder, WorldEdit.

### Actions to reproduce (if known):
I don't know

### Paper build number:
Paper 123.

**Comment by FrankHeijden** [comment]
I have noticed this in one of my plugins as well, that requesting chunks through World#getChunkAt could sometimes freeze the server out of nowhere. I will try to debug this more tomorrow / see what I can come up with.
