### ISSUE TITLE
Server crashes on /stop

### ISSUE THREAD

**Issue by hotspuraz** [PaperMC/Paper#4023]
It's very long so I went with Pastebin.
https://pastebin.com/WuAPmKPW

### Plugin list:
Plugins (48): AdvancedRegionMarket, BuycraftX, ChestShop, ClearLag, CMI, CMIEInjector*, CMIPaperLib, CoreProtect, EasyBackup, EnchantGui, FogusCore, GoldenCrates, GriefPrevention, Harbor, HeadDatabase*, HolographicDisplays, HolographicExtension, Images, Insights, LastLoginAPI, LeaderHeadsRevamped, LiteBans, LuckPerms, MarriageMaster, MineableSpawners, MobFarmManager, Parties, PL-Hide, PlaceholderAPI, PlayerParticles, PluginConstructorAPI, PremiumVanish, ProtocolLib, Rankup, ShopGUIPlus, SuperLog, SuperTrailsPro*, TAB, UltimateAutoRestart, UltimateTimber, Vault, Votifier, VotingPlugin, Welcome*, Wild, WorldBorder, WorldEdit, WorldGuard

### Actions to reproduce (if known):
In this instance, the server crashed after saving the world and closing the server with /stop. The server stayed online and I had to manually stop the process via the console.

However, the server has crashed due to a similar reason while online with 60+ players. Again, it won't properly close and just shows players trying to join. Commands via the console are also unresponsive. 

### Paper build number:
Server: Paper(88) 1.16.1-R0.1-SNAPSHOT
I have tried multiple versions, another ticket suggested that a recent change to paper was the issue so I downgraded. It did crash on Paper-123 earlier though with similar errors.

**Comment by realDragonium** [comment]
Could you try to reproduce it without any plugins? The problem may lie with Votifier or VotingPlugin since both of those names are in the crash report. But just in case try it also without any plugin.

**Comment by hotspuraz** [comment]
Well the issue is that it only crashes with 50+ players online so I can't reproduce it on my test server and removing every plugin would result in.. many bad things

**Comment by CDFN** [comment]
>[23:06:12] [Paper Watchdog Thread/ERROR]: If you see a plugin in the Server thread dump below, then please report it to that author
>[23:06:12] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):

I'm pretty sure this isn't paper related problem

**Comment by electronicboy** [comment]
Need the full logs from the latest build, that doesn't even show any signs that you attempted to /stop, (I mean, it's also a fair chunk before it even checks if the server should still be running, seems entirely unrelated to it)

**Comment by hotspuraz** [comment]
Well I use a plugin to stop the server, which does 'save-all' then 'stop'

**Comment by electronicboy** [comment]
save-all is slow and can often routinely take stupidly long to actually complete (I've seen a dozen timing reports from spigot where they took 10+ seconds on small servers), there is also 0 reason to do so, the server already saves chunks on shutdown...

**Comment by hotspuraz** [comment]
It looks to be fixed since https://github.com/PaperMC/Paper/commit/76728529f9de02506a5c73aa4c5fc8c12d5fe13c
But thanks for just closing the tread without any real consideration.

**Comment by electronicboy** [comment]
We can only go off the info you provide, if you provide virtually none, we're just going to run towards "the most likely issue"; In the future, provide the *full* logs, from at least the time you run the command to it blowing up
