### ISSUE TITLE
Since 1.16.1 126 patch, my server dont´t load some worlds

### ISSUE THREAD

**Issue by TheMagBum** [PaperMC/Paper#4025]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!
https://paste.timo.cloud/vapisawuwo.md

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
I have updated the version, since then the server is running out of memory and can't finish loading. My server currently has 2.5 GB which should be enough, but since the new update it seems to draw much more. 

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
126

**Comment by Proximyst** [comment]
Since you've neglected to actually fill the template and give sufficient information, all we can say is that you've just ran out of memory.

**Comment by TheMagBum** [comment]
> Since you've neglected to actually fill the template and give sufficient information, all we can say is that you've just ran out of memory.

How i add my plugins? I cannot run /plugins because the server don´t load, and the plugins work befor this version fine. It´s not a plugin error

**Comment by Proximyst** [comment]
May I suggest reading the contents of the plugins directory? You can even just `grep` it for the files you want.

```console
$ ls plugins | grep '\.jar'
back-spigot-0.1.0.jar
EssentialsX-2.17.2.68.jar
homes-0.3.1.jar
InfiniteDispenserX.jar
inventory-sync-0.3.2.jar
LuckPerms-Bukkit-5.1.30.jar
mv-qol-0.1.2.jar
mv-util-spigot-6.1.3.jar
PlaceholderAPI-2.10.6.jar
redis-channels-spigot-0.3.3.jar
teleports-spigot-0.2.0.jar
Vault.jar
```

It working before you updated does not directly mean this isn't a plugin issue, but try to narrow down the version where this happened. What version were you on before? Try [binary searching](https://simple.wikipedia.org/wiki/Binary_search) for the build which starts the issue.

**Comment by TheMagBum** [comment]
The error was starting with 126, the 125 work all fine
Plugins:
ArmorStandTools.jar
BackUpSystem-Piraty-1.0.jar
Bank-System-1.0-SNAPSHOT.jar
BannerMaker.jar
BuildSystem-1.0-SNAPSHOT.jar
Citizens-2.0.27-b2073.jar
CustomHeads (1).jar
Doerfer-1.0-SNAPSHOT.jar.dis
DummyFawe.jar
Economy-1.0.jar
FastAsyncVoxelSniper-flattened-1.0.3-backward.jar
FastAsyncWorldEdit-1.16-306.jar
FurnitureLib.jar
goBrush 1.14+.jar
LuckPerms-Bukkit-5.1.84.jar
Marketplace.jar
Matrix.jar
Piraty-JobSystem-1.0-SNAPSHOT.jar
Piraty_ReportSystem-1.0-SNAPSHOT.jar
PiratySystem-Core.jar
PlotSquared-Bukkit-5.13.0.jar
PlugMan.jar
PremiumVanish-2.5.15.jar
ProtocolLib.jar
spark.jar
Time-Manager-1.0-SNAPSHOT.jar.dis
TimoCloud.jar
ViaVersion-3.0.1.jar

**Comment by Proximyst** [comment]
Can you attempt to load the world without plugins? If that works, try a [binary search](https://simple.wikipedia.org/wiki/Binary_search) to find the culprit.

**Comment by TheMagBum** [comment]
yes, i have try it without any plugins. It dosn´t work. Since the update thee wold load duration has a insante increases

**Comment by hurrgurl** [comment]
Does your system have enough memory?

Last time I had out of memory error, getting more memory solved the issue.

Try installing htop and see what's happening to your memory.

**Comment by TheMagBum** [comment]
In the 125 build, all work with only 1.25 gb memory, now i have 2.5 Gb and it not work.

**Comment by aikar** [comment]
cant reproduce any memory issues. your gonna have to provide more information

I find it extremely hard to believe that a simple world file without any plugins cant load.
You will need to zip up your spawn region files and configs.

For one, just provide us the config files too.

**Comment by TheMagBum** [comment]
If I take all plugins out, my worlds won't load anymore, so I took all plugins out and put only the world load plugin in.  That's where I use MV-Core.  But I only have 12 worlds or so.  Anyway, one world now pulls a lot more ram than it did before.

**Comment by Proximyst** [comment]
You didn't even list Multiverse. Please give a *complete* list of plugins...

**Comment by TheMagBum** [comment]
Mutlievers is in BuildSystem-Piraty.jar, this plugin use the same methode then MV
I have also exchanged the plugin with mv once, but the same error occurred

**Comment by aikar** [comment]
please provide configs and JVM start options.

**Comment by TheMagBum** [comment]
https://paste.timo.cloud/vozewiguse.coffeescript

**Comment by tofikarz** [comment]
Why are You using spigot.jar?

**Comment by meerpaluten** [comment]
because that must be the name of the jar from the cloud system

**Comment by yannic-md** [comment]
same
