### ISSUE TITLE
Mobs are not triggering pressureplates

### ISSUE THREAD

**Issue by MarkElf** [PaperMC/Paper#4026]
### What behaviour is expected:
___What you expected to see___
Summoning or a walking mob over a pressure plate should activate the pressure plate.
### What behaviour is observed:
___What you actually saw___
The pressure plate doesn't go down. I tested summoning a zombie 1 block above a [pressure plate and walking on to an oak and stone pressure plate. For the sake of testing another mobs, she's show the same behavior - not triggering a wood pressure plate. This does occur in single player.
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
http://prntscr.com/tqnwjy
### Plugin list:
___A list of your plugins___
http://prntscr.com/tqnwwr
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
b127, /version above.
### Anything else:
___Anything else you think may help us resolve the problem___
Occurs when both enabled and disabled 'use-faster-eigencraft-redstone' from paper.yml.

**Comment by Proximyst** [comment]
Works fine without plugins on b127. This is a plugin issue.

Side note, Eigencraft redstone is not in 1.16.1 (yet? We'll see) at all.

![https://uwu.whats-th.is/95eePbN.png](https://uwu.whats-th.is/95eePbN.png)

**Comment by MarkElf** [comment]
You are absolutely right, it was a worldguard issue. I probably should have tried it in other parts of the world first.

I updated the server from 1.15.2 to 1.16.1 and that section has been there, I should regenerate the paper.yml.
