### ISSUE TITLE
[1.16.1] KeepInventory Does not work in the End when you be killed or fall in the Void

### ISSUE THREAD

**Issue by 8ar10der** [PaperMC/Paper#4029]
### What behaviour is expected:
KeepInventory should be work

### What behaviour is observed:
Everything lost after reborn in the overworld.

### Steps/models to reproduce:
Die in the End when KeepInventory be set to true.

### Plugin list:
* mcMMO
* dynmap
* Chestsort

### Paper build number:
git-paper -123

### Anything else:
I try to die in a local game not my server. The KeepInventory is work. My local MC version is 1.16.1.

**Comment by electronicboy** [comment]
gamerules are per-world in craftbukkit, you need to change it in all worlds
