### ISSUE TITLE
Light Bug on Last Paper Version

### ISSUE THREAD

**Issue by TheCalypso** [PaperMC/Paper#4030]
### What behaviour is expected:
___What you expected to see___

Hello, I just updated to the latest version of paper. I used to run under the Paper-93 version and had no such problem, currently I have just updated the Paper-128 version.

Moreover, I would point out to you that with this new version of paper, my server crashes when it is launched, here is the error that I get : https://pastebin.com/x0F3PYJ7

### What behaviour is observed:
___What you actually saw___

When I go to my map, the light calculations are no longer done at all.
Before: 
![2020-06-21_16 20 57](https://user-images.githubusercontent.com/33781244/88921154-530fc780-d26e-11ea-9419-b43180e38201.png)

After:
![image](https://user-images.githubusercontent.com/33781244/88921015-180d9400-d26e-11ea-8548-10a59d90d006.png)

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___
Protocolibs, Custom Plugin, Head DataBase, PlaceolderAPI, HolographicDisplay, WorldBoarder. 

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
[14:06:54 INFO]: This server is running Paper version git-Paper-128 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[14:06:54 INFO]: Checking version, please wait...
[14:06:54 INFO]: Previous version: git-Paper-93 (MC: 1.16.1)
[14:06:54 INFO]: You are running the latest version

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by ghost** [comment]
On my server, it seems to affect only the first person to join after the server starts up. Players who join after the first person don't experience any lighting issues.  Rejoining fixes the issue. Running build 128.

**Comment by velnias75** [comment]
> On my server, it seems to affect only the first person to join after the server starts up. Players who join after the first person don't experience any lighting issues. Rejoining seems to fix the issue. Running build 128.

Can confirm this bug. I've tried to do `--forceUpgrade --eraseCacahe` as well as `/paper fixlight` plus `/save-all` before.
After a rejoin the dark places seem to be lit again.

**Comment by velnias75** [comment]
Sorry to destroy your hope :-( No change on my server :-(

![2020-07-31_06 59 50](https://user-images.githubusercontent.com/4481414/89001963-1ee2e800-d2fc-11ea-9b6e-c7b6a608c4a8.png)
![2020-07-31_07 00 10](https://user-images.githubusercontent.com/4481414/89001983-328e4e80-d2fc-11ea-9876-f9863a2bdf81.png)

2nd Screenshot is after `/paper fixlight` at the same position like the first picture.

**Comment by Lud00** [comment]
> Sorry to destroy your hope :-( No change on my server :-(
> 
> ![2020-07-31_06 59 50](https://user-images.githubusercontent.com/4481414/89001963-1ee2e800-d2fc-11ea-9b6e-c7b6a608c4a8.png)
> ![2020-07-31_07 00 10](https://user-images.githubusercontent.com/4481414/89001983-328e4e80-d2fc-11ea-9876-f9863a2bdf81.png)
> 
> 2nd Screenshot is after `/paper fixlight` at the same position like the first picture.

Try this: https://www.spigotmc.org/resources/light-cleaner.42469/
Worked for me

**Comment by velnias75** [comment]
> Try this: https://www.spigotmc.org/resources/light-cleaner.42469/
> Worked for me

Just at the moment I had the same idea :smile_cat: 

(But this plugin _overlights_ a bit. At least better than to loose all villagers to zombies)

**Comment by Lud00** [comment]
> > Try this: https://www.spigotmc.org/resources/light-cleaner.42469/
> > Worked for me
> 
> Just at the moment I had the same idea 😸
> 
> (But this plugin _overlights_ a bit. At least better than to loose all villagers to zombies)

My house is in the spawn area. It was a mayhem when I logged in. All villagers turned into Zombies. Creeper all over the place.
For some reason the **bug** only impacted the **Spawn area**.

**Comment by electronicboy** [comment]
Have you tried to fixlight since the update? Just noting that it won't automagically fix already affected areas

**Comment by velnias75** [comment]
> My house is in the spawn area. It was a mayhem when I logged in. All villagers turned into Zombies. Creeper all over the place.
> For some reason the **bug** only impacted the **Spawn area**.

I have spawn protection disabled, but some forced loaded chunks. Under my automatic wheat farm is a hall, which turned into an more than effective mob farm. 
But there are some more unlit places scatteed around. At least they are always at the same spots.

As workaround I tried to switch to version '#125' (ignore link), but it seems to be the same bug in that version or the bug found its way into the worlds save files.

**_EDIT_** Seems really to affect mainly the spawn area and forced loaded chunks. Travelled around 4000 blocks away and there the light seemed to be okay.

**Comment by velnias75** [comment]
> Have you tried to fixlight since the update? Just noting that it won't automagically fix already affected areas

I've tried `fixlight`and now testing with `cleanlight` from @Lud00 plugin proposal.
