### ISSUE TITLE
PlayerKickEvent leaveMessage is ignored

### ISSUE THREAD

**Issue by MeFisto94** [PaperMC/Paper#4031]
### What behaviour is expected:
When kicking a player, the set leaveMessage is used

### What behaviour is observed:
The default leave message is sent.

### Steps/models to reproduce:
`PlayerConnection#disconnect` throws a `PlayerKickEvent` which has a `leaveMessage` field.
`disconnect` then calls into `a(IChatBaseComponent)`, where the component is the quit reason written into the log files and displayed to the player
The actual quit message is defined by a call to `this.minecraftServer.getPlayerList().disconnect(this.player);`, because the `leaveMessage` is never passed into `a`.
 The Quit Message is then defined by the PlayerQuitEvent which is called by `PlayerList#disconnect`

### Plugin list:
none, observed by digging through the code

### Paper build number:
" 0b33230f2db4013d929b4b2e93b74ea57592a6d6 "

### Anything else:
Theoretically this bug should be resolved upstream, but I have low hopes that anyone in the chain is caring about this minor discrepancy. Some parties might even claim that everyone is relying on the current behavior.
The fix would be just to pass the leaveMessage to `a` for kicks and null for other disconnects.
I guess this issue is mostly there for people noticing this bug to confirm it's not an issue in their code.

**Comment by Machine-Maker** [comment]
If I pr'd a fix for this here, would it get merged? or should this really be pr'd to spigot's repo?

**Comment by Proximyst** [comment]
Feel free to PR a fix to us. It's quite understandable if you don't want to be fussed with PRing upstream lol
