### ISSUE TITLE
Serious glitch thats affected random players.

### ISSUE THREAD

**Issue by HyenaGodKing** [PaperMC/Paper#4032]
### What behavior is expected:
Player is able to interact and play functionally without glitches.
### What behavior is observed:
Two players on my server have already came across this glitch. It happens only specifically in my server and rebooting minecraft doesn't fix it. The player isn't able to interact with anything, can be immune to all damage, sometimes reports falling off the world, commands don't work for that player so when I did /tphere (playername) they never got teleported, even after I removed all my plugins and data packs the glitch was still occurring meaning it wasn't a plugin causing it. 

### Steps/models to reproduce:
That is an absolute mystery, one player said they were mining and then randomly started suffocating and from there it started. 

### Plugin list:
I removed every single plugin. 

### Paper build number:
paper-375.jar

**Comment by HexedHero** [comment]
Just sounds like a bad network

**Comment by HyenaGodKing** [comment]
It wasn't bad network. It happened two two people and they tried everything even days after nothing changed. Also they got a message saying "  "Don't disembark here! "

**Comment by electronicboy** [comment]
That doesn't even sound like a vanilla message? and doesn't appear in source... could a command block do that? 🤷

**Comment by HyenaGodKing** [comment]
They have been playing on my server forever and never have this issue before. I thought it was just network until another player got the issue. Whenever a player has this issue they will continue having this issue forever no matter how many days, times they restart their pc, restart their router, etc.

**Comment by aikar** [comment]
This behavior is representative of a player who's removed from the world. 

Can be caused by a plugin that called .remove() on a player, or by an error with the player leaving them  un registered to the world.

**Comment by HyenaGodKing** [comment]
Just an update on this situation all the players who were affected by this glitch were riding either a horse or donkey inside a protection worldguard region before this happened. When I removed all the plugins the issue continued to happen. Do you know more specifically what can be done to prevent this from continuing because this is making my server unplayable.

**Comment by Batur123** [comment]
> Just an update on this situation all the players who were affected by this glitch were riding either a horse or donkey inside a protection worldguard region before this happened. When I removed all the plugins the issue continued to happen. Do you know more specifically what can be done to prevent this from continuing because this is making my server unplayable.

Did you restart server when you remove all the plugins or people were still playing on the server?

**Comment by Brokkonaut** [comment]
I can confirm this issue, I had that issue for a few players some months ago in 1.15.2 and the only way to fix it was to delete their player data file (world/playerdata/theplayeruuid.dat). Somehow those player files got corrupted for players riding an entity.

**Comment by aikar** [comment]
Without logs showing an exception causing them to failed to be added to world, nothing can be done for this.

**Comment by josephrooks** [comment]
Went through something similar to what @Brokkonaut is describing a few weeks ago. In our case, the player was a server op having trouble logging in. They would be unable to do anything for a minute, and then get kicked, even though the world was loading around them. Removing their player file seemed to fix the issue. I don't remember when it was exactly or I'd try to dig up logs from that day - but it sounds very familiar.

**Comment by noahbclarkson** [comment]
"Don't disembark here!" is a world guard message in relation to disallowing the ride-flag (Whether vehicles (including animals) can be mounted) in region, its not a paper issue. You clearly have a region with the ride-flag disabled, use /rg list  to find your defined regions and use rg flag ride allow to enable riding, this flag often messes with other plugins such as a pet plugin?
