### ISSUE TITLE
Incorrect behavior with armor stands and frost walker on chunk-load

### ISSUE THREAD

**Issue by brennanmcmicking** [PaperMC/Paper#4036]
### What behaviour is expected:
When a chunk is loaded (either by logging into the server, coming within a close enough proximity to the chunk to load it, or teleporting into it), any armor stands with Frost Walker boots should cause the surrounding water to turn to ice. This is useful for detecting chunk loading.

### What behaviour is observed:
On Paper#129, when a player enters the chunk with the Frost Walker armor stand, nothing happens. No ice is created.

### Steps/models to reproduce:
Create a 1.16.1 Paper#129 or lower Minecraft server. Find a body of water with a block on the same level. Place an armor stand next to the water (as if it were a sugar cane), then place Frost Walker II boots on the armor stand. Then either leave the server and re-join, re-load the chunk by walking away and walking back, or re-load the chunk by teleporting away and teleporting back. Observe that there is no ice around the armor stand. You can replicate this process on a non-paper Minecraft 1.16.1 server and observe that ice will be created around the armor stand.
[Please observe this video replicating the bug](https://youtu.be/JEwTCc43RKM)

### Plugin list:
None. I did not show it in the video, but the server that was running Paper#129 did not have any plugins on it. It is a freshly created server with not modifications.

### Paper build number:
The Paper version used is Paper#129, the ___newest version as of 9:08pm PST, July 30th, 2020___.

### Anything else:
It is important to note that this [issue also occurred in the 1.15.2 build of Paper](https://github.com/PaperMC/Paper/issues/3088)  but it was fixed after March 30th 2020 but before or on April 3rd 2020 for MC1.15.2.

I understand that this may be considered "intended mechanics" because I don't see why loading a chunk would cause armor stands to produce ice, but this is how vanilla Minecraft servers function and I believe that PaperMC should follow vanilla Minecraft server mechanics as much as possible.

**Comment by e-im** [comment]
Thank you for the report and video, and sorry it has taken almost a year to get a response! Unfortunately, I was not able to reproduce this issue on paper 1.16.5 build 756. I have a feeling the issue you are encountering here is due to paper delaying chunk unloads by default; hence the chunk was never actually unloaded in your testing. This is controlled by `delay-chunk-unloads-by` in paper.yml. If you can still reproduce, let me know if waiting a bit longer to ensure the chunk has unloaded resolves the issue.

**Comment by e-im** [comment]
I'm going to close this, but do leave a comment if you are still experiencing this issue.

**Comment by brennanmcmicking** [comment]
Oh yeah, sorry. Forgot to reply to your previous comment. I tested it on paper 760 and now on initial login the ice appears, but any subsequent attempts to load the chunks will not produce ice no matter how long I stay away whether it be by logging out of the server for over 30 minutes and then rejoining, or by staying on the server but going 4000 blocks away.

**Comment by e-im** [comment]
I haven't seen this behaviour. Have I done anything different than you here? [https://youtu.be/NxpxEjiUFMI](https://youtu.be/NxpxEjiUFMI)

**Comment by brennanmcmicking** [comment]
The only difference I can see is that you are using /execute and I am using /tp. What is your reasoning for using /execute? Also, recorded another video on the latest version of paper (769) but forgot to type /paper version: https://www.youtube.com/watch?v=b7ArShckqdo

I think that it is important for me to mention, I originally opened this issue because I wanted to use this system as a chunk loading detector in a wither rose farm, but I have since found a different design that does not need it. I am totally willing to continue to help pinpoint the issue, but if you want to leave it for now and work on other things that's fine. I have not seen anyone else reference this issue or open something similar in almost a year, so it's probably not too big of a deal.

**Comment by e-im** [comment]
I've taken another look at this and haven't been able to find anything not working as intended.  `/execute` and `/tp` aren't any different there, `/execute` just runs `/tp` in a specific world. The exclusive rational for that is that f3+c allows you to copy your current location to the clipboard in that format.

Even though you waited a while in the video, my only real suspected cause is that the chunks still aren't actually unloading for some reason. Are you able to try actually stopping the server? Beyond that, you can use `/paper debug chunks` or `/paper chunkinfo` to ensure the chunks have actually been unloaded, or write a simple plugin to log chunk loads/unloads. It's possible there's another bug there that is causing the chunks to not unload, but I somewhat doubt it.

Noted I have re-looked at this this on 1.17, I didn't look at 1.16 further. It is possible something has changed between then and now in regard to this.
