### ISSUE TITLE
Villager not pathfinding correctly

### ISSUE THREAD

**Issue by StarryWorm** [PaperMC/Paper#4037]
When building a compact villager trading hall with npc aligned on the x axis (negative x coordinates), villagers believe their workstation to be one block further in the negative x-direction than it really is which causes them to be unable to restock their trades.  However, in singleplayer (non-paper) the villagers find the workstations properly.

Behavior expected:
Villager has "minecraft:job_site": {value: {pos: [I; x, y, z]}} when working at workstation at position (x, y, z) when using 
     /data get entity @e[type=minecraft:villager, limit=1, sort=nearest] Brain

Behavior noted:
Villager has "minecraft:job_site": {value: {pos: [I; x-1, y, z]}} when working at workstation at position (x, y, z) when using 
     /data get entity @e[type=minecraft:villager, limit=1, sort=nearest] Brain

Steps to reproduce:
https://www.youtube.com/watch?v=aK2d5-X898o

**Comment by aikar** [comment]
what did you do to discover a -1?

I'm a bit confused on how it could be broken since both our optimization to pathfinding and villager pathfinding are currently not in 1.16

but if theres some bit unpacking issue resulting in the wrong X Value that could be related.

**Comment by StarryWorm** [comment]
I did the exact same thing at the exact same coordinates in my singleplayer world and in the multiplayer server run on paper (b111)  and when I used said command, in the singleplayer (where the villager restocks) the coordinates where those of the actual block whereas they were said x-1, y, z in the multiplayer (vilager does not restock)

**Comment by StarryWorm** [comment]
Interesingly enough the two villagers in the outside (out of 5 villagers) work and restock their trades but not the three in the middle.
It also seems that by spacing them out they can all work, making this a mc issue most likely, however the saved coordinates are still wrong only in paper

**Comment by aikar** [comment]
mojang has fixed some issue in 1.16.2, which is likely this.

I've tried for past few hours looking for any chance of a bug on our end and im out of things to look at, so this must be the bug they just fixed.

as I'm def seeing villagers claim POI's according to expected villager behavior.

**Comment by aikar** [comment]
seeing as this will be fixed shortly with 1.16.2 update, im going to go ahead and close this unless someone can tell us exactly what the fix is to apply it faster than 1.16.2.

if so, please open a new issue w/ the fix.
