### ISSUE TITLE
Server thread dump/hang

### ISSUE THREAD

**Issue by KeplerDota** [PaperMC/Paper#4038]
### What behaviour is expected:
The server is expected to run smoothly

### What behaviour is observed:
These hangs are occurring that sometimes last 30+ seconds. Console output of what it says when it happens: https://pastebin.com/v6bF1557
Note that our server is using a world generated in 1.15 singleplayer that was moved onto the server.

### Steps/models to reproduce:
This isn't exactly something easy to reproduce, I'm moreso asking "anyone know what these error messages mean?"

### Plugin list:
BKCommonLib, ConsoleSpamFix, CoreProtect, DiscordSRV, dynmap*, InventoryRollback, LightCleaner, LuckPerms, OpenInv, PhantomSpawnControl, Vault, WorldEdit

### Paper build number:
130

### Anything else:
Really just hoping that someone's able to identify what these lines of console mean.
From what I've found it may be similar to [this issue on the Tuinity github](https://github.com/Spottedleaf/Tuinity/issues/143)
but I had this issue both on Tuinity and on Paper. With Async loading enabled.

**Comment by electronicboy** [comment]
#2312
