### ISSUE TITLE
Random Paper 130 crash

### ISSUE THREAD

**Issue by NatasFX** [PaperMC/Paper#4040]
### Link/paste of stack trace

https://pastebin.com/j4w9FdMK

### Plugin list:
EssentialsX-2.8.0.0.jar
SkinRestorer.jar

### Actions to reproduce (if known):
The crashes happens in a random way, i really dont know what is causing it.

### Paper build number:
Paper 130.

**Comment by electronicboy** [comment]
> [11:18:46] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 250624ms or 5012 ticks behind
Server is blatantly overloaded
