### ISSUE TITLE
PlayerMoveEvent doesn't get called when the player is a passenger on an armorstand and moves it's head.

### ISSUE THREAD

**Issue by SmushyTaco** [PaperMC/Paper#4041]
### What behaviour is expected:
PlayerMoveEvent getting called.
### What behaviour is observed:
PlayerMoveEvent not getting called.
### Steps/models to reproduce:
```kotlin
fun playerSitOnFloor(player: Player) {
    val armorStand = player.world.spawnEntity(player.location.add(0.0, -0.9, 0.0), EntityType.ARMOR_STAND) as ArmorStand
    armorStand.isVisible = false
    armorStand.isInvulnerable = true
    armorStand.isSmall = true
    armorStand.setCanMove(false)
    armorStand.setGravity(false)
    armorStand.isCollidable = false
    armorStand.isCustomNameVisible = false
    armorStand.addPassenger(player)
}
```
Use this to become a passenger of an armor stand and move your head and you'll see PlayerMoveEvent won't get called but if you move your head and you're not the passenger of an armor stand PlayerMoveEvent will be called as expected.
### Plugin list:
Just a plugin I was using for testing this.
### Paper build number:
Paper version git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
### Anything else:
Nope.

**Comment by chickeneer** [comment]
This behavior is consistent with players riding entities - in general. Such as intentional vehicles.
I don't mean to imply that it is a good state to be in, but is not unique to Armorstands.

Perhaps this should be a request for a PlayerMoveInVehicleEvent? I don't love it, but is all I could come up with.

**Comment by SmushyTaco** [comment]
> This behavior is consistent with players riding entities - in general. Such as intentional vehicles.
> 
> I don't mean to imply that it is a good state to be in, but is not unique to Armorstands.
> 
> 
> 
> Perhaps this should be a request for a PlayerMoveInVehicleEvent? I don't love it, but is all I could come up with.

Yeah an event for such a thing would be pretty helpful but wouldn't something like PassengerMovementEvent (and maybe a VehicleMovementEvent to match it) make more sense so it's not specific to players so it has more use cases?

**Comment by SmushyTaco** [comment]
How would I go about getting this to be a priority for Paper to implement?

**Comment by MiniDigger** [comment]
bumping the issue to remove the stale tag is a good first step :)

other than that, paper is a community project. we are all volunteers. we also heavily rely on contributions. so the best way to get this fixed fast, is to do it yourself, or find somebody who can do it.

**Comment by SmushyTaco** [comment]
Alright thanks
