### ISSUE TITLE
zoglin attack/targeting behavior abnormal

### ISSUE THREAD

**Issue by mbravorus** [PaperMC/Paper#4042]
### What behaviour is expected:
The setting is an enclosed with farm with 3 layers of packed ice built in place of a witch hut; based on Rays Works video linked below

There are two zoglins on each layer (I have also tried with one, doesn't matter). Zoglins are nametagged.

The expectation is that zoglins attack everything they can pathfind to, namely, in this case, witches spawning on their 7x9 platform. Attacked mobs (witches) then fall down and die by entity cramming in the stacked minecarts.

### What behaviour is observed:
A *fresh batch* of zoglins does indeed attack the witches as they spawn in; however, after an initial spawn of witches dies, zoglins get stuck and never attack anything again, just stand there (when there are two zoglins per level, they appear to stand butting heads with each other, not doing any damage though)

I have verified that witches do indeed die in the minecarts stack and not just e.g. sit in there. I have also verified that stuck zoglins do not attack even when there's only one witch and on their platform, none on the other two.

### Steps/models to reproduce:
 https://www.youtube.com/watch?v=wj9NG1UZ7ew is the build video

please note that there are people with similar problems described in the comments, with author recommending plain vanilla

(if a schematic would help, I can produce one)

### Plugin list:
Plugins (4): CoreProtect, DiscordSRV, dynmap*, LuckPerms

### Paper build number:
This server is running Paper version git-Paper-130 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
This may or may not be related to #3752 (purely contextual guesswork here)

**Comment by LukeAppGuy** [comment]
I am also experiencing this issue on my server with the exact same configuration!

**Comment by Ididthisforfun** [comment]
We are experiencing the same issue on our server with this same farm design as well!

**Comment by TheEpicProgrammer** [comment]
I also have this issue and why is it closed?

**Comment by james-d-elliott** [comment]
Should be fixed in 1.16.1 132+ (135 is latest).
