### ISSUE TITLE
1.16 - Server crash (out of nowhere)

### ISSUE THREAD

**Issue by yannic-md** [PaperMC/Paper#4043]
### Link/paste of stack trace

    Crash-Log: https://pastebin.com/4bb7EdG6
    Console-Log (before crash): https://pastebin.com/g0g5FBAg

### Plugin list:
___A list of your plugins___
AdvancedAchievements
AntiAura
AsyncWorldEdit
ChatControl
Citizens
CitizensCMD
ClearLag,
EntityTrackerFixer
EpicWorldGenerator
Essentials
HackedCore*, HackedServer*
HolographicDisplays
iConomy
IllegalStack
InteractiveBoard
JetsAntiAFKPro*
Jobs
KillRewards*
LagAssist
Lands
LightAPI
LoneLibs
LuckPerms
MaSuiteCore, MaSuiteTeleports
Multiverse-Core
NametagEdit*
PlaceholderAPI
PlayerShopGUIPlus
PlayerWarps
ProtocolLib
SimplePortalsSpawn
sleep-most*
SpigotLib
TabList
TimeIsMoney*
TrHologram, TrMenu
Vault, WorldEdit, WorldGuard

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
idk, the crash comes complete random

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-130 (MC: 1.16.1)

**Comment by Brokkonaut** [comment]
Similar to #4001.

**Comment by yannic-md** [comment]
Maybe important: https://pastebin.com/vEBChPrz
sometimes i get this error (dont crash the server)

**Comment by JanTuck** [comment]
That is not a paper issue, report to plugin author.

**Comment by electronicboy** [comment]
That doesn't even look possible to occur in vanilla, something like a plugin is mangling with stuff it shouldn't be
The fact that you have a plugin literally screaming about trying to add invalid entities to the world...

**Comment by yannic-md** [comment]
Thanks for letting me know! I contacted the Plugin dev. I think this thread can be closed now. 
https://github.com/PaperMC/Paper/issues/4001 has the same error like me, i think he has a world generator too. You should maybe ask him.
