### ISSUE TITLE
World Memory Leak

### ISSUE THREAD

**Issue by Foorcee** [PaperMC/Paper#4045]
Apparently related to the light changes.

![SQ7dTtX](https://user-images.githubusercontent.com/5587062/89131899-912c1600-d510-11ea-9d2b-3b2536e5147c.png)

So we had over 50 WorldServer instances

### Paper build number:
Build 129

**Comment by aikar** [comment]
ugh, forgot about world unload to stop the world threads. 
yeah ill need to fix that
