### ISSUE TITLE
Datapacks not active on server startup no errors logged

### ISSUE THREAD

**Issue by brothanb** [PaperMC/Paper#4046]
### What behaviour is expected:
Datapacks should be working upon server startup.

### What behaviour is observed:
Datapacks appear to be loaded but are not always active 

### Steps/models to reproduce:
install one or more datapacks.   (I was testing with double shulker shells.)
start server.
Login and test the datapack for the action.
If it fails, run minecraft:reload and retest.
Shutdown the server.
Start the server again and restest the datapack.

### Plugin list:
CoreProtect v19.1
Opening v4.1.2
WorldEdit sion 7.2.0-beta-02

### Paper build number:
Paper version git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
This appears to be like issue #3722 (https://github.com/PaperMC/Paper/issues/3722), and I even updated from paper-80.   However, no errors were logged at server startup as shown in the previous issue.
The datapack list command shows the datapacks as enabled, but they are not working.
Running the minecraft:reload command always corrects the issue for the running instance.
After a shutdown/restart, the problem occasionally reappears.

Our server is running on Linux, I was using MacOS 10.14.6 (Mohave) to reproduce the problem.

**Comment by Chew** [comment]
Does this still happen on the latest 1.16.4 build (b261)?

**Comment by brothanb** [comment]
We haven't noticed it reoccur since updating to 1.16.3 and now 1.16.4.

**Comment by Chew** [comment]
Great to hear. Because of how vague this is and the situation is now resolved, I'll be closing this issue. If anyone else has this issue on a supported version don't hesitate to make a new issue. Thanks for the report!
