### ISSUE TITLE
1.16.1 Server crash

### ISSUE THREAD

**Issue by ricardormmx** [PaperMC/Paper#4047]
### Link/paste of stack trace
https://pastebin.com/E3qfsnKh
Minecraft crash report: 
https://pastebin.com/CjzPW4dU

### Actions to reproduce (if known):
The error occurs while loading new areas of the world.

### Paper build number:
Paper 131, we also tried 115 and 130.

**Comment by MrIvanPlays** [comment]
Can reproduce.
