### ISSUE TITLE
Error since updating to 845 from 842

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#405]
29.08 19:39:29 [Server] ERROR This crash report has been saved to: /./crash-reports/crash-2016-08-29_19.39.28-server.txt
29.08 19:39:28 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:843) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:258) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:724) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.util.HashTreeSet.first(HashTreeSet.java:114) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at java.util.TreeSet.first(Unknown Source) ~[?:1.8.0_73]
29.08 19:39:28 [Server] INFO at java.util.TreeMap.firstKey(Unknown Source) ~[?:1.8.0_73]
29.08 19:39:28 [Server] INFO at java.util.TreeMap.key(Unknown Source) ~[?:1.8.0_73]
29.08 19:39:28 [Server] INFO java.util.NoSuchElementException
29.08 19:39:28 [Server] ERROR Cause of unexpected exception was
29.08 19:39:28 [Server] INFO ... 4 more
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:843) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:258) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:724) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.util.HashTreeSet.first(HashTreeSet.java:114) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at java.util.TreeSet.first(Unknown Source) ~[?:1.8.0_73]
29.08 19:39:28 [Server] INFO at java.util.TreeMap.firstKey(Unknown Source) ~[?:1.8.0_73]
29.08 19:39:28 [Server] INFO at java.util.TreeMap.key(Unknown Source) ~[?:1.8.0_73]
29.08 19:39:28 [Server] INFO Caused by: java.util.NoSuchElementException
29.08 19:39:28 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:854) ~[patched_1.10.2.jar:git-Paper-845]
29.08 19:39:28 [Server] INFO net.minecraft.server.v1_10_R1.ReportedException: Exception ticking world
29.08 19:39:28 [Server] ERROR Encountered an unexpected exception

**Comment by AlfieC** [comment]
A plugin of yours appears to be doing something async it shouldn't be. List your plugins.
