### ISSUE TITLE
Raytrace going past maxDistance.

### ISSUE THREAD

**Issue by SmushyTaco** [PaperMC/Paper#4051]
### What behaviour is expected:
Raytrace to stop at maxDistance
### What behaviour is observed:
Raytrace going past maxDistance.
### Steps/models to reproduce:
```kotlin
object RideCommand : TabExecutor {
    const val COMMAND = "ride"
    override fun onCommand(sender: CommandSender, command: Command, label: String, args: Array<out String>): Boolean {
        if (sender !is Player) {
            sender.sendMessage(COMMAND.onlyPlayersCanUseCommand())
            return true
        }
        val location = sender.eyeLocation.add(sender.eyeLocation.direction.multiply(1.25))
        val distance = sender.world.rayTraceBlocks(location, sender.eyeLocation.direction, 10.0)?.hitBlock?.location?.distance(location) ?: 10.0
        sender.sendMessage(distance.toString())
        val mob = sender.world.rayTraceEntities(location, sender.eyeLocation.direction, distance)?.hitEntity
        if (mob == null || mob == sender) {
            sender.sendMessage("${ChatColor.DARK_RED}You aren't looking at anything.")
            return true
        }
        sender.sendMessage(mob.location.distance(location).toString())
        mob.addPassenger(sender)
        return true
    }
    override fun onTabComplete(sender: CommandSender, command: Command, alias: String, args: Array<out String>): MutableList<String> {
        return Collections.emptyList()
    }
}
```
Run the /ride command while looking at a mob with a one block wall between you and the mob 
and look at the values in the chat and you'll see that the maxDistance for the rayTraceEntities line of code is exceeded (See picture below for reference).
![unknown](https://user-images.githubusercontent.com/41648290/89167623-7c5f7a80-d530-11ea-89b7-66bd84383c0d.png)
### Plugin list:
Just the plugin I used to test this.
### Paper build number:
git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
### Anything else:
Nope.

**Comment by BillyGalbreath** [comment]
Works as intended.

Your first number is the distance to the point of collision the raytrace has with the entity (from the angle of your screenshot, that would be the pig's top/back side).

Your second number is the distance to the entity's location (which is it's feet, which is about half a block's distance from it's top/back).

;)
