### ISSUE TITLE
PaperMC 1.16.1 #117 crash

### ISSUE THREAD

**Issue by ExplodingLemur** [PaperMC/Paper#4053]
### Link/paste of stack trace
https://pastebin.com/43XTdUVf

### Plugin list:
None

### Actions to reproduce (if known):
Unknown.

### Paper build number:
1.16.1 build 117

**Comment by aikar** [comment]
It appears you may of ran out of memory or something else brought processing speed to its knees in performance.

Running out of memory (from such as having a lot of work queued up holding up processing) where the server process is spamming the garbage collector is a common source of this.

You are behind on Paper updates on super critical performance fixes for chunk loading, so this could relate, so please update.
