### ISSUE TITLE
Twisting Vines + Bonemeal Glitches When Grown

### ISSUE THREAD

**Issue by Noodle4lyfe** [PaperMC/Paper#4054]
### What behaviour is expected:
Bonemeal the placed twisting vine and then keep right clicking. It should grow very high the more you rightclick the bottom twisting vine.

### What behaviour is observed:
It grew a tiny bit, but the vines near the top act like the bottom vine and you have to reach real high to even bonemeal again, normally you just have to bonemeal the bottom for it to grow high.

### Steps/models to reproduce:
Place down a twisting vine, bonemeal it, keep trying too so it will go high (it works like how placing a ton of scaffolding does), and observe the glitch.

### Plugin list:
Worldedit

### Paper build number:
git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
Nothing else. PaperMC is the best! 👍

**Comment by noahbclarkson** [comment]
Can confirm this happens to me as well with the only paper-131 installed. 
Edit: After checking on just plain old spigot the glitch still occurs which means paper can wait for an upstream patch or issue a patch themselves.

**Comment by Proximyst** [comment]
Fixed in CraftBukkit 3c7143e7b41.
