### ISSUE TITLE
1.16.1 crash 

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4055]
### Link/paste of stack trace

The actual crash: https://pastebin.com/gffAxc7p
Other information that may be useful: https://pastebin.com/0EYgrBp4

### Plugin list:
AntiAura, BKCommonLib, ChatManager, Citizens, Elevator, Essentials, EssentialsProtect, EssentialsSpawn, LightAPI, LiteBans, LocketteX, LuckPerms, mcMMO, PlaceholderAPI, PluginConstructorAPI, PocketGames, ProtocolLib, QualityArmory, React, Sentinel, TAB, Train_Carts, Vault, WorldEdit, WorldGuard

### Actions to reproduce (if known):
I really don't know. I asked around in another location and someone suggested I report this, as it looks non-plugin related.

### Paper build number:
Paper version git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

On another note, if this turns out to be a valid issue, you should probably rename the title to be more specific.

**Comment by ghost** [comment]
I have same problem but server ram and cpu goes to 100% for some reason but until this hapens its 80% or lower 
+-40 plugins, 12 players on and 6GB of ram

**Comment by dodofan** [comment]
Any update on this from a collaborator, or no?

**Comment by ghost** [comment]
It was good until yesterday when server crashed agarin

**Comment by Fox2Code** [comment]
It seems one of the plugins is spawning too many arrows making the server crash.  
Arrows are often used for chairs or entity related mechanics.  
The plugins I suspect crashing the server are `Sentinel`, `mcMMO`, `PocketGames`, and `Citizens` (But I might be wrong)
I don't know the plugin `PocketGames` but I hardly see how the other plugins in your list that I didn't put in my list can spawn so many arrows.  
Note: Commands block can also spawn arrows you should also check that.

For me, this crash is not Paper related.

**Comment by ghost** [comment]
Do you know what counts as "too many arrows?" 

Is it too many arrows firing at the same time, or too many arrow entities being left behind and not despawning? What do you mean exactly?

**Comment by Fox2Code** [comment]
`net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld()` and `net.minecraft.server.v1_16_R1.IBlockAccess.rayTrace()` in the stack trace made me think it's too many arrow is shooted.  
And just checked, the method `rayTrace` is not called when the arrow is on the ground.

**Comment by dodofan** [comment]
I've only got six sentinels that shoot arrows... not sure why this is happening :(

**Comment by Proximyst** [comment]
You've quite simply got an absolute truck load of arrows in the air. Kill them with `/kill @e[type=arrow]` and make sure your plugin doesn't do it again.
