### ISSUE TITLE
Ender dragon is full health after server restart

### ISSUE THREAD

**Issue by ArkadSt** [PaperMC/Paper#4058]
### What behaviour is expected:
___I expected ender dragon's health state to be the same as before the server restart as all the crystals were destroyed___

### What behaviour is observed:
___Ender dragon's health was reset when I restarted the server___

### Steps/models to reproduce:
___Go to ender, destroy all crystals, hit the dragon several times and restart the server___

### Plugin list:
___SkinsRestorer___

### Paper build number:
___131___

**Comment by JanTuck** [comment]
Able to reproduce on spigot & vanilla?

**Comment by ArkadSt** [comment]
Haven't tried yet, but I will.

**Comment by Proximyst** [comment]
Thanks Github, that's not the same repository.

**Comment by Chew** [comment]
The joys of GitHub, you can close issues cross repos! I can't though, guess it's write+ only
