### ISSUE TITLE
/give command not accepting verified correct inputs that contain spaces (from generators, other people testing them, etc)

### ISSUE THREAD

**Issue by AWebb3701** [PaperMC/Paper#4061]
Paper v131

Example Command:
`/give @p turtle_helmet{display:{Name:'[{"text":"Name with a space","italic":false}]'}} 1`

Error Received:
`Error: Unknown item name: turtle_helmet{display:{name:'[{"text":"name.`

Taking the spaces out of the name causes it to instead fail at the first space found in a lore entry.
`/give @p turtle_helmet{display:{Name:'[{"text":"Namewithoutspaces","italic":false}]',Lore:['[{"text":"Lore with Spaces","italic":false}]']}} 1`

returns:
`Error: Unknown item name: turtle_helmet{display:{name:'[{"text":"namewithoutspaces","italic":false}]',lore:['[{"text":"lore.
`

Extra information:
Using the command on Spigot works.

**Comment by electronicboy** [comment]
Use minecraft:give, this is because you have a plugin replacing the give command

**Comment by AWebb3701** [comment]
Worked, thanks!

**Comment by AWebb3701** [comment]
Addendum: minecraft:give still doesn't actually generate the item with lore. It DOES give the item with the enchantments and name that I request though.

**Comment by Proximyst** [comment]
Then your NBT is incorrect. We don't touch it.
