### ISSUE TITLE
Custom recipes using Recipe.ExactChoice(ItemStack) [stack size & recipe book bug]

### ISSUE THREAD

**Issue by gustaavik** [PaperMC/Paper#4063]
### What behaviour is expected:
The stack size of the itemstack is required for an ingredient while crafting custom recipes
![image](https://user-images.githubusercontent.com/41763143/89457001-009a4380-d765-11ea-950e-6cfcabd3a120.png)

### What behaviour is observed:
Right now it doesnt consider the stack size
![image](https://user-images.githubusercontent.com/41763143/89457046-13ad1380-d765-11ea-8188-15d71233422d.png)

### Anything else:
As seen on the picture below I clearly have the required amount of blaze rods, as shown in the crafting grid, but it is marked in red like it doesnt register that I have the items
![image](https://user-images.githubusercontent.com/41763143/89457372-9209b580-d765-11ea-8841-27b7943a2074.png)

**Comment by JanTuck** [comment]
IIRC, this is a spigot "draft" api, would be happy to see a paper equivalent that isn't a "draft" api.

**Comment by gustaavik** [comment]
Not sure what that means

**Comment by CDFN** [comment]
It's suggestion to someone to create working API.

**Comment by aikar** [comment]
This is working as intended, as the crafting system does not expect the idea of stack sizes as a requirement. A Shaped recipe sees this as prepping to rapidly create 12 of them.

While yes it's probably possible to do this code wise, its not safe to make such a deviation from vanilla concepts as mojang might do something that prevents us from maintaining this idea.

Also doing it prob complicates impl even more.

So unless you can investigate the system and study it in detail and propose an implementation that should be guaranteed maintainable, this is working as intended.

**Comment by aikar** [comment]
and IIRC recipe book was built with materials in mind and just doesnt work right with itemstack based.

**Comment by gustaavik** [comment]
What is IIRC recipe boo

**Comment by gustaavik** [comment]
I feel like IIRC is being mentioned everywhere

**Comment by gustaavik** [comment]
oh nvm

**Comment by gustaavik** [comment]
Should I post this to spigot instead?

**Comment by JanTuck** [comment]
IIRC = If I Recall Correctly.

And posting it to spigot will probably get you the same response, along with the lines of "draft api"

**Comment by CDFN** [comment]
No, its literally impossible with current api, as Aikar said.

**Comment by gustaavik** [comment]
frocck

**Comment by gustaavik** [comment]
frick*
