### ISSUE TITLE
1.16.1 Paper-131 crash

### ISSUE THREAD

**Issue by ExplodingLemur** [PaperMC/Paper#4069]
### Link/paste of stack trace

https://pastebin.com/2P55S53H

### Plugin list:
None

### Actions to reproduce (if known):
Unknown, but happens every couple days.

### Paper build number:
This server is running Paper version git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
your server is struggling to keep up, apparently some sheep movement is seemingly holding you up; Best advice is to use timings, try to work out where the entities are, etc

**Comment by ExplodingLemur** [comment]
> 
> 
> Best advice is to use timings, try to work out where the entities are, etc

Can you direct me to any documentation regarding use of timings?

**Comment by electronicboy** [comment]
`/timings report`, there is a video in the top corner of the page that goes over how to read it, etc
