### ISSUE TITLE
The console has no color.

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#407]
Sorry for my poor English.
bulid 443
![image](https://cloud.githubusercontent.com/assets/15712089/18109251/d2bd3370-6f42-11e6-8ac8-06b32ed20370.png)

The old version of the console has a color, but the bulid 443 is not.

![image](https://cloud.githubusercontent.com/assets/15712089/18109308/1629f242-6f43-11e6-8834-71dd18fd6edc.png)

build 443 error.
![image](https://cloud.githubusercontent.com/assets/15712089/18109179/6c051058-6f42-11e6-8fb6-40ae5340b48a.png)

**Comment by zachbr** [comment]
We do not support 1.8
