### ISSUE TITLE
Getting a skull of an offline player causes lag

### ISSUE THREAD

**Issue by ChrisTaylor201** [PaperMC/Paper#4075]
### What behaviour is expected:
Getting a skull of an offline player shouldn't cause lag.

### What behaviour is observed:
Getting a skull of an offline player causes lag, see the [Timings report](https://timings.aikar.co/?id=80de7fb028444b32ac41d4743e515021).

### Steps/models to reproduce:
1. Install [EssentialsX](https://www.spigotmc.org/resources/9089/).
2. Start Timings.
3. Get a skull of an offline player using `/skull` command.
4. Check the Timings report.

### Plugin list:
```
Plugins (1): Essentials
```

### Paper build number:
384 (1.15.2)

### Anything else:
I've noticed a similar issue with other plugins on our production server, namely:

* [BossShopPro](https://www.spigotmc.org/resources/222/) – when there's a skull of an offline player in a GUI,
* [LeaderHeads](https://www.spigotmc.org/resources/2079/) – when there's a skull of an offline player on an armor stand ([thread dump](https://gist.github.com/christaylor201/250279490900a14e9a2f3ceb07206b6a)),
* [VotingPlugin](https://www.spigotmc.org/resources/15358/) – same as with BossShopPro.

After consulting this issue with the plugin developers we've concluded it's most likely caused by [this patch](https://github.com/PaperMC/Paper/commit/a70618cd5cb493fe9fe2a2a7375a7b1949d427d7).

I wanted to reproduce this issue on a local server with nothing but EssentialsX installed to be sure it's not caused by other plugins.

**Comment by ishland** [comment]
duplicates #4004

**Comment by aikar** [comment]
Not a bug. Yes making network requests is slow.

You can ask Essentials to create the item async instead to avoid this.

**Comment by ChrisTaylor201** [comment]
Okay, thank you very much, I'll ask them to do it asynchronously. I also apologize for creating an unnecessary issue.
