### ISSUE TITLE
players in ops.txt and whitelist.txt not loaded

### ISSUE THREAD

**Issue by Erik1000** [PaperMC/Paper#4081]
### What behaviour is expected:
Player names should be read from txt file, written to json file and loaded into the server.

### What behaviour is observed:
The server renames the file from e.g. ops.txt to ops.txt.converted (this is expected) but won't actually add players in these files to the operators. On shutdown however the server will save these players to the json file. After restart the server will load the players from the json files and everything is fine.

### Steps/models to reproduce:

- Get the latest paper jar file
- accept the eula so the server will start (e.g. ``echo 'eula=true' > eula.txt``)
- write your player name in the ops.txt or whitelist.txt file (e.g ``echo 'Erik1000' > ops.txt``)
- start the server (``java -jar paper.jar``)
- either try to join the server to see if the actually on the whitelist or try some administrative command like ``/gamemode creative``  --> this won't work
- check if your name is either in the ops.json or whitelist.json file (spoiler: it isn't)
- stop the server and look again (now your name is in the file)
- start the server again (now your either on the whitelist or an operator)

In commands:

- ``echo 'eula=true' > eula.txt``
- ``echo 'YourName` > ops.txt``
- ``java -jar paper.jar``
- ``cat ops.json``
- ``stop`` (in the console)
- ``cat ops.json``
- ``java -jar paper.jar``

### Paper build number:
Paper version git-Paper-133 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT) --> latest

### Anything else:
This bug occurs on the bukkit and normal spigot version too (and many clones like magma or tuinity), but not then using the vanilla server.

**Comment by imDaniX** [comment]
So basically this is upstream problem. I think somebody should report it to [spigot's issues tracker](https://hub.spigotmc.org/jira/).

**Comment by Machine-Maker** [comment]
I just tested this, following the exact command steps laid out, and my player does appear on `ops.json` after starting the server. So I don't think this is still an issue.

**Comment by electronicboy** [comment]
The fact that they're in the file is not the issue, that behavior is explicitly stated here as working

This is a spigot bug, the init of the player list is done earlier in spigot before the actual conversion code is called, 
See DedicatedServer#158 and DedicatedServer#224

**Comment by Machine-Maker** [comment]
Yeah, I just found that out, didnt actually check if I had op, just that I was in the file

**Comment by Machine-Maker** [comment]
Why was 
```java
this.a((PlayerList) (new DedicatedPlayerList(this, this.customRegistry, this.worldNBTStorage))); // CraftBukkit - moved up
```
done? Either moving that back down, or moving the old file conversion up above it would fix the issue.

**Comment by Machine-Maker** [comment]
NO
