### ISSUE TITLE
crash pls help me

### ISSUE THREAD

**Issue by kevinwang-0916** [PaperMC/Paper#4082]
Link/paste of stack trace
https://pastebin.com/WuxBFzDW

Plugin list:
Plugins (38): AAC.AntiAFKPlus.AuctionGUIPlus.AutoAnnouncer.AutoRestart.BungeeGuard.ChestCommands.ChestSort.Citizens.CoreProtect.CustomJoinItems.Essentials.FogusCore.GroupManager.HolographicDisplays.LockettePro.Lottery.MobFarmManager.MoneyHunters.MOTD.Multiverse-Core.OpenInv.Orebfuscator.PlaceholderAPI.ProtocolLibQuickShop.Residence.SAML.Shopkeepers.TAB.TempFly.TradeUI.Vault.VillagerOptimiser.WorldEdit.WorldGuard.zAuctionHouseV2

Actions to reproduce (if known):
Server freezes on save (every 6000 ticks), not sure about the trigger

Paper build number:
1.16.1 version 133

**Comment by Proximyst** [comment]
![https://owo.whats-th.is/3g8AKrW.png](https://owo.whats-th.is/3g8AKrW.png)

Join our Discord if you'd like help with the issue.

**Comment by electronicboy** [comment]
Player moving too fast
