### ISSUE TITLE
ActivationRange crashes server

### ISSUE THREAD

**Issue by thedutchruben** [PaperMC/Paper#4084]
### Link/paste of stack trace
https://pastebin.com/QWRARhrw

https://pastebin.com/VyNGdFby

### Plugin list:
BannerBoard, BlocksHub, Blueprints, CommandLib, CoreProtect, CustomCrafting, DDG-Vehicles, DDGCoins, DDGCommandSync, DDGEntityManager, Dungeons, dynmap, FarmLimiter, FastAsyncWorldEdit, GlowAPI, GuiLib, InventoryVault, ItemEdit, LiteBans, LootEventSlave, LuckPerms, MineSecure, PacketListenerApi, PlanetCraft, PlanetCraftGame-Loot, ProtocolLib, Receive, RedSync, SmartCore, translator, VanishNoPacket, ViaVersion, WolfyUtilities, WorldBorder, WorldEdit, WorldGuard, WorldGuardEvents

### Actions to reproduce (if known):
1. we got 10-20 players
2. we created armorstands you can ride on.
3. people ride the armorstand around each other

### Paper build number:
git-Paper-b91-d964b1

**Comment by thedutchruben** [comment]
I got this issue from 1.13.2 - 1.16.1

**Comment by electronicboy** [comment]
You have a chunk with null entities, I don't really see how this could happen in paper, and cases like this have generally been attributed to plugins messing with internals improperly
