### ISSUE TITLE
Entity#teleportAsync occasionally sends players to spawn

### ISSUE THREAD

**Issue by bermudalocket** [PaperMC/Paper#4085]
Relevant code:
```java
// var player, world, x, y, z, yaw, pitch
Bukkit.getScheduler().runTask(this, () -> {
    var chunkLoadStart = System.currentTimeMillis();
    player.sendMessage(ChatColor.GRAY + "Requested chunks from server. Waiting...");
    player.teleportAsync(new Location(Bukkit.getWorld(world), x, y, z, yaw, pitch), PlayerTeleportEvent.TeleportCause.PLUGIN)
        .thenRunAsync(() -> {
            var chunkLoadTime = System.currentTimeMillis() - chunkLoadStart;
            var msg = String.format("%sSuccessfully loaded chunks in %d ms (%.2f ticks).", ChatColor.GRAY, chunkLoadTime, (double) chunkLoadTime / 50);
            player.sendMessage(msg);
        });
});
```

### What behaviour is expected:
The chunks to be loaded asynchronously, followed by the player being teleported to `(x, y, z)`.

### What behaviour is observed:
The player is occasionally teleported to spawn for a brief moment (< 1 second) before being teleported to `(x, y, z)`. When the player appears at spawn, they are visible to other players and can be interacted with (e.g. punched).

### Steps/models to reproduce:
I'm having a hell of a time reproducing this reliably. My best guess right now is that there's some interference from lag. If you create a command, e.g. `/testtp x y z` that runs `Entity#teleportAsync` and try to run that (teleporting into unloaded chunks, of course), _eventually_ the issue with occur.

### Plugin list:
I have reproduced this with a minimal setup, meaning Paper and a small plugin supplying the command described above.

### Paper build number:
```This server is running Paper version git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)```

### Anything else:
We are using Java 14.0.2 with Shenandoah GC on Ubuntu 18.04.3 LTS. The server is allotted 4 GB of memory.

**Comment by JRoy** [comment]
Multiple things here:

1) What is a "minimal plugin setup"? You need to reproduce this by having the code listed the only code running on a server.
2) You really shouldn't be using that GC, please read https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft

**Comment by bermudalocket** [comment]
A "minimal setup" means just Paper and a small plugin supplying the command I described.

I am more than familiar with that article by Aikar.
