### ISSUE TITLE
Moving outside a moving worldborder prevents you from reentering it

### ISSUE THREAD

**Issue by AoElite** [PaperMC/Paper#4089]
### What behaviour is expected:
What's expected is once you are outside a moving world border you should be able to move back into it.

### What behaviour is observed:
Attempting to move back into a world border while it's moving teleports you back outside of it

### Steps/models to reproduce:
Have a world border that constantly moves inwards, attempt go inside of it from the outside.

### Plugin list:
None

### Paper build number:
1.15.2 Build #385

**Comment by AoElite** [comment]
Accidently closed it oops

**Comment by Proximyst** [comment]
Cannot reproduce on 1.16.2. Is this still reproducible to you?

**Comment by Chew** [comment]
Author never responded. We're on the edge of not supporting 1.15.2 anymore, and doesn't appear to be reproducible on 1.16.2. If this is happening on latest 1.16.4 build, feel free to open a new issue. Otherwise, thanks for the report!

**Comment by Octol1ttle** [comment]
I'm sorry for commenting on this, but I had the same issue on 1.15.2 and I can confirm it's not present on 1.16.4
