### ISSUE TITLE
Mob generation from mob spawners

### ISSUE THREAD

**Issue by ohAleee** [PaperMC/Paper#4091]
### What behaviour is expected:
Mobs spawned by mob spawners attack players

### What behaviour is observed:
Mobs spawned by mob spawners do not attack.

[https://imgur.com/MlQuLS5](url)

### Steps/models to reproduce:
find a mobspawner or place one and wait for the mob to spawn. The player who is in Survival Mode will not be attacked

### Plugin list:
nobody.

### Paper build number:
This server is running Paper version git-Paper-134 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
A possible error in setting the entity's target?

**Comment by rrvk** [comment]
What is your `world-settings.default.nerf-spawner-mobs`  in `spigot.yml`
Because if that is on true the mobs from spawners dont have ai so dont attack players

**Comment by ohAleee** [comment]
oh damn, sorry my mistake.

**Comment by rrvk** [comment]
If that fix your issue then you can close it ;)
