### ISSUE TITLE
MutableBlockPosition.o IllegalAccessError

### ISSUE THREAD

**Issue by Jishuna** [PaperMC/Paper#4094]
### Link/paste of stack trace
[https://hastebin.com/yozuborubo.sql](https://hastebin.com/yozuborubo.sql)
### Plugin list:
Plugins (32): Citizens, dtlTraders, Essentials, FogusCore, GoldenCrates, JCommands, JCore, JDifficulty, JEnchants, JEvents, JFishing, JFoods, JInfo, JItems, JLuckyBlocks, JMagic, JMisc, JRanks, JScoreboard, JShop, JSkills, JSpawners, JWorldgen, LuckPerms, QuickShop, Towny, TownyChat, Vault, VotingPlugin, WorldEdit, WorldEditSUI, WorldGuard

### Actions to reproduce (if known):
Code pointed to by the stacktrace:
```java	
MutableBlockPosition blockPos = new MutableBlockPosition(pos.getX(), 0, pos.getZ());

for (int x = 0; x < 16; x++) {
    for (int z = 0; z < 16; z++) {
	int xPos = (pos.getX() + x);
	int zPos = (pos.getZ() + z);
	blockPos.o(xPos); <- CaveDecoratorFeature.java:49
	blockPos.q(zPos);
```
### Paper build number:
This server is running Paper version git-Paper-134 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
**(Issue observed as of build 131, does not occur on build 130)**

**Comment by electronicboy** [comment]
An NMS change was made to clean up some crud, the plugin needs to be rebuilt to account for the changes

**Comment by Jishuna** [comment]
It works properly on the latest build of spigot, does this mean it needs to be specifically edited to run on paper?

**Comment by electronicboy** [comment]
Nvm, I missed a change in aikars patch which would cause this
