### ISSUE TITLE
Error with packet 

### ISSUE THREAD

**Issue by Bossbirdyman51** [PaperMC/Paper#4095]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

https://pastebin.com/gvxA01cH

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
Paper 133

I have this error when a player place a bamboo in biome bungle or if he break or use bone meal

**Comment by JanTuck** [comment]
And, does it persist if you remove ALL plugins?

**Comment by Bossbirdyman51** [comment]
I don't know I test it later and I review ^^
