### ISSUE TITLE
createVanillaChunkData in generateChunkData causes nested call stack/crash

### ISSUE THREAD

**Issue by qixils** [PaperMC/Paper#4097]
### What behaviour is expected:
When developing a plugin for custom terrain generation, using `createVanillaChunkData` inside of the custom `generateChunkData` function of a `ChunkGenerator` class can create normal vanilla terrain to build off of

### What behaviour is observed:
Calling `createVanillaChunkData` from `generateChunkData` causes a function loop and quick server crash  
Logging the chunk coordinates ([`System.out.println(chunkX + " " + chunkZ);`](https://cdn.discordapp.com/attachments/555462289851940864/742273368103059536/unknown.png)) show it's not related to neighboring chunks, it's just one chunk infinitely getting called and causing the crash  
Using `createChunkData` does not cause such a crash

### Steps/models to reproduce:
Using my [test plugin](https://github.com/lexikiq/VanillaChunkTest), compiled [here](https://github.com/lexikiq/VanillaChunkTest/suites/1029295452/artifacts/13602532), and the relevant code snippet [here](https://github.com/lexikiq/VanillaChunkTest/blob/master/src/main/java/io/github/lexikiq/vanillachunktest/VanillaGenerator.java#L12) 
Remember to set a world to use the plugin's generation in bukkit.yml (see test plugin readme)

### Plugin list:
VanillaChunkTest

### Paper build number:
git-Paper-134 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
[crash logs](https://pastebin.com/raw/tYzNcVEY)

**Comment by thisisfel1x** [comment]
any progress on this issue?

**Comment by Pangamma** [comment]
I am also noticing this as well. Using version: git-Paper-277 (MC 1.16.4)

**Comment by Pangamma** [comment]
Super excited for whenever this gets fixed

**Comment by MiniDigger** [comment]
I am very sorry for taking so long to finally take a look. This was broken in 1.16.1, the fix is already cooking
