### ISSUE TITLE
Item loss/deletion

### ISSUE THREAD

**Issue by ZephaniahNoah** [PaperMC/Paper#4098]
Someone on my server died. I picked up their items in creative mode and gave them back to the player by pressing CTRL+Q on all the items. When the player picked them up some of them were gone. I tested this multiple times by giving myself about 20 stacks of an item in creative mode and passing them to a player with CTRL+Q. Some of the items get deleted.
Minecraft 1.16.1
Paper git-Paper-128

**Comment by Proximyst** [comment]
Creative mode has differences from survival mode. This is vanilla behaviour, and has been for years.

**Comment by ZephaniahNoah** [comment]
Ouch. Alright. I would report this to Mojang but there are some bugs on their site that haven't been patched for years. This really sucks. Thanks anyways.

**Comment by Proximyst** [comment]
This has been reported and closed on Mojira before. It's not a bug.

**Comment by ZephaniahNoah** [comment]
That makes no sense but okay.
