### ISSUE TITLE
Long commands result in kick for string buffer length

### ISSUE THREAD

**Issue by CampbellSoup077** [PaperMC/Paper#4099]
### What behaviour is expected:
To be able to use command blocks to the full 32,500 character limit

### What behaviour is observed:
When I pasted in a long command into a command block, it kicked me and spat out this error: 
[Mon, 10. Aug 2020 03:24:02 EDT INFO] Kamatayan lost connection: Internal Exception: io.netty.handler.codec.DecoderException: The received encoded string buffer length is longer than maximum allowed (8668 > 8192)

### Steps/models to reproduce:
Just try pasting any command into a command block that is larger than 8668 characters.

### Plugin list:
Plugins (19): AdvancedPortals, BungeeTabListPlus, CoreProtect, DiscordSRV, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, ExtraContexts*, Harbor, HeadDatabase*, InactivityChecker*, LuckPerms, Minepacks, OpenInv, PetBlocks*, Plan, Vault, WorldEdit

### Paper build number:
[Mon, 10. Aug 2020 03:33:45 EDT INFO] This server is running Paper version git-Paper-134 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[Mon, 10. Aug 2020 03:33:45 EDT INFO] Previous version: git-Paper-131 (MC: 1.16.1)
[Mon, 10. Aug 2020 03:33:45 EDT INFO] You are running the latest version

### Anything else:
Just earlier ran into this issue and waterfall was what was stopping the command from being pasted. Electronicboy very quickly updated and released a new build for waterfall. I updated that on our network and then ran into this issue. Thanks in advance for any help

**Comment by donvdp** [comment]
same here

**Comment by aikar** [comment]
Not going to change this. Mojang doesn't always make the best limits.
