### ISSUE TITLE
WorldEdit breaking from plugin with dependency (only on paper 1.16.1 - works fine in spigot)

### ISSUE THREAD

**Issue by MarinDEV** [PaperMC/Paper#4100]
### What behaviour is expected:
WorldEdit commands to work properly

### What behaviour is observed:
One plugin which has worldedit as a dependency causes worldedit to break (this works fine in spigot but it breaks worldedit in paper)

### Steps/models to reproduce:
Run /outset command in worldedit.

### Plugin list:
- WorldEdit, WorldGuard, Custom Plugin with 2 classes (https://pastebin.com/Tpd3afvd, https://pastebin.com/XaCBjRAB)

### Paper build number:
- git-Paper-131

### Anything else:
This is the error: https://pastebin.com/F8XNBneT
It could also help to know that this issue has only happened with the new version of paper. The last tested version was 1.14.2 and it worked fine then. This error doesn't exist in spigot.

**Comment by electronicboy** [comment]
```
java.lang.NoSuchMethodError: com.sk89q.worldedit.world.World.getMinY()I
    at com.sk89q.worldedit.regions.AbstractRegion.getWorldMinY(AbstractRegion.java:210) ~[?:?]
```
WE can't find a method from WE... Best guess is that you have some plugin shading in a different version of WE or something, differences in load order can cause oddball issues here, not a paper issue
