### ISSUE TITLE
Generate .java files

### ISSUE THREAD

**Issue by gutyerrez** [PaperMC/Paper#4102]
How i do to generate .java files? Only java .patch files in all folders

**Comment by CDFN** [comment]
Run ./paper patch

**Comment by Proximyst** [comment]
Welcome to Paper, we're happy you're taking interest in the project! For information on how to patch, compile, rebuild, and eventually contribute, please read our [contributing document](https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md).

**Comment by aikar** [comment]
Fixed CDFN's comment, the correct command is /paper patch to generate the source.

Jar is only needed for distribution of a final jar on the internet.

If you want to patch and compile a dev build, you can either run patch and then mvn clean install in the correct modules, or do ./paper build
