### ISSUE TITLE
Using the recipe book to craft items one at a time crashes a server easily

### ISSUE THREAD

**Issue by mattirizarry** [PaperMC/Paper#4104]
### What behaviour is expected:
I expect to see performance not drop if a player decided to make 64 iron blocks at 66 CPS using the recipe book in the default GUI.

### What behaviour is observed:
Whenever someone individually crafts multiple items in a recipe book instead of shift clicking, it will cause the server to lag.

### Steps/models to reproduce:

The video pretty much shows the error

### Plugin list:

```
ActionHealth*, AdvancedNMotd*, AntiWorldFly, AuctionHouse, AutoMessager, 
BlueShop, boosCooldowns, BuycraftX, ChestShop, ChestSort, Chunky, 
CommandSigns, ConditionalCommands, CoreProtect, CropClick*, 
DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, FogusCore, 
GoldenCrates, GriefPrevention, GriefPreventionFlags, HolographicDisplays, 
Jobs, LibsDisguises, LuckPerms, Multiverse-Core, NoCheatPlus, NoteBlockAPI, 
OldCombatMechanics, PlayerVaults, PlayerWarps, ProCosmetics, ProtocolLib, 
RandomTeleport, ShowItem, SilkSpawners, TAB, TreeFeller, Vault, ViaBackwards, 
ViaRewind, ViaVersion, Votifier, VotingPlugin, VoxelSniper, WorldEdit, WorldGuard
```

### Paper build number:

git-Paper-134

### Anything else:
https://timings.aikar.co/?id=bcc807378bb04fe68f060c54d8447eaf

Examine Aug 11, 2020 12:24 AM - Aug 11, 2020 12:37 AM for the spikes in TPS loss. 

`Minecraft::Packet - nms.PacketPlayInAutoRecipe` seems to be the culprit.

https://timings.aikar.co/?id=79d82451fbb04d1284934a6b2e4661c9 - This is the timings report from the time during the video

Examine Aug 11, 2020 12:50 AM - Aug 11, 2020 1:00 AM for the spikes in TPS loss.

[latest (2).log](https://github.com/PaperMC/Paper/files/5055090/latest.2.log)

**Comment by Chew** [comment]
Does this still happen on the latest build (b261)?

**Comment by mattirizarry** [comment]
Yes
