### ISSUE TITLE
Add turtle helmet in PlayerArmorChangeEvent's SlotType class

### ISSUE THREAD

**Issue by armagidon-exception** [PaperMC/Paper#4106]
**Is your feature request related to a problem? Please describe.**
I'm just making plugin and i noticed that PlayerArmorChangeEvent in SlotType in HEAD constant Material[] array doesn't have turtle helmet. And if it doesn't handle turtle helmet it will break some of my plugin logic.

**Describe the solution you'd like**
Add turtle helmet there, just add Material.TURTLE_HELMET in the array.

**Describe alternatives you've considered**

**Additional context**

**Comment by Rincewind34** [comment]
I think the HEAD Slot is missing quite a few to list every material the player can equip (e.g. the mob heads). Moreover, the "Jack o' Lantern" is as far as I know not equipable via vanilla mechanics.
On 1.16 there are the new netherite pieces missing.
