### ISSUE TITLE
Redundant Option in Paper Config to disable Patrol Spawning

### ISSUE THREAD

**Issue by TheShermanTanker** [PaperMC/Paper#4107]
**Is your feature request related to a problem? Please describe.**
In the Paper Config, there is an Option under game-mechanics called disable-pillager-patrols, which is redundant with the advent of the gamerule doPatrolSpawning

**Describe the solution you'd like**
The redundant Option should be removed

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Proximyst** [comment]
I personally don't see the need to remove it; if people are updating to the newer versions with older configs, they should be able to expect their configs to work as expected. If they feel the need of controlling it via gamerule instead, they can do so by just deleting the option.
