### ISSUE TITLE
Cancelling VehicleEnterEvent teleports player weirdly

### ISSUE THREAD

**Issue by FarisR99** [PaperMC/Paper#411]
I've already made a report on the Spigot JIRA but found out that it was only a bug on PaperSpigot.
https://hub.spigotmc.org/jira/browse/SPIGOT-2660

**Comment by zachbr** [comment]
I'm seeing this same behavior across the board, all the way up to CraftBukkit.

**Comment by FarisR99** [comment]
Weird, it works perfectly fine for me on Spigot. Even then, it's still an 'issue' I guess...

**Comment by AlfieC** [comment]
In my fork, I "fixed" this issue by simply teleporting the player to the entity they dismounted from. It's not exactly vanilla behavior but I found that this was better than them being teleported under blocks.

**EDIT:** I misread this issue - ignore me.

**Comment by zachbr** [comment]
This will be closed if you cannot demonstrate how it is different than CraftBukkit's. I cannot reproduce any oddities.

**Comment by FarisR99** [comment]
@Zbob750 Go ahead and close it, I've moved back to Spigot so I cannot show you a video anyway.
