### ISSUE TITLE
Small time out, dolphins loading stuff?

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#4110]
What happened there?

### Link/paste of stack trace
https://pastebin.com/raw/B7Lg1sg5

### Plugin list:
custom

### Actions to reproduce (if known):
Heard about dolphins doing heavy stuff awhile ago, is this it?

### Paper build number:
133

**Comment by MiniDigger** [comment]
this is the normal structure search lag, so this is a duplicate of #2312

**Comment by Chew** [comment]
See Mini's message ^
