### ISSUE TITLE
Server continue to crash due to world saving in paper 135

### ISSUE THREAD

**Issue by Redstone-ray** [PaperMC/Paper#4111]
### Link/paste of stack trace

https://pastebin.com/PzpkRMkQ -- Server crashes without crash log

https://pastebin.com/FHdXwzNc -- Server freezes/crashes without crash log

https://pastebin.com/V1uNCVwy -- Server did not crash, but freezes

 More details in #4070

O̶n̶e̶ ̶t̶h̶i̶n̶g̶ ̶t̶o̶ ̶m̶e̶n̶t̶i̶o̶n̶,̶ ̶a̶l̶l̶ ̶m̶y̶ ̶s̶u̶b̶s̶e̶r̶v̶e̶r̶s̶ ̶i̶s̶ ̶h̶a̶v̶i̶n̶g̶ ̶t̶h̶i̶s̶ ̶s̶a̶m̶e̶ ̶i̶s̶s̶u̶e̶ ̶n̶o̶w̶ ̶a̶f̶t̶e̶r̶ ̶I̶ ̶r̶e̶s̶t̶a̶r̶t̶e̶d̶ ̶t̶h̶e̶m̶,̶ ̶n̶o̶ ̶p̶r̶o̶b̶l̶e̶m̶ ̶b̶e̶f̶o̶r̶e̶ ̶r̶e̶s̶t̶a̶r̶t̶,̶ ̶d̶e̶s̶p̶i̶t̶e̶ ̶s̶o̶m̶e̶ ̶s̶e̶r̶v̶e̶r̶s̶ ̶a̶r̶e̶ ̶s̶t̶i̶l̶l̶ ̶o̶n̶ ̶1̶.̶1̶4̶ ̶a̶n̶d̶ ̶I̶ ̶h̶a̶v̶e̶n̶'̶t̶ ̶u̶p̶d̶a̶t̶e̶ ̶t̶h̶e̶m̶ ̶f̶o̶r̶ ̶m̶o̶n̶t̶h̶s̶,̶ ̶i̶t̶ ̶m̶i̶g̶h̶t̶ ̶b̶e̶ ̶a̶n̶ ̶i̶s̶s̶u̶e̶ ̶o̶n̶ ̶m̶y̶ ̶s̶i̶d̶e̶.̶

And I'm running OpenJ9-JDK11

**Comment by electronicboy** [comment]
There is nothing here that indicates that this could be a server issue, that block of code is doing a few file IO operations to shuffle the temp X.dat file onto the disk, the stall is happening in OS code
