### ISSUE TITLE
difficulty option in server.properties does not update existing worlds/dimensions

### ISSUE THREAD

**Issue by KurtThiemann** [PaperMC/Paper#4115]
### What behaviour is expected:
Changing the 'difficulty' options in the server.properties file should update the difficulty in all dimensions (overworld, nether, end) at the next server start (as it does in both Vanilla and Spigot)

### What behaviour is observed:
Only newly created dimensions are affected by the new difficulty

### Steps/models to reproduce:
- Create a new server with a newly generated world
- Change the difficulty option in the server.properties from its default value (easy) to a different value (e.g. hard)
- Restart the server
- Check the difficulty with /difficulty

### Paper build number:
git-Paper-135 (MC: 1.16.1)

**Comment by electronicboy** [comment]
This is only used on world creation due to CBs per-world difficulty support
