### ISSUE TITLE
TPS drops sharply on <20 players online

### ISSUE THREAD

**Issue by gabenitez0** [PaperMC/Paper#4119]
###  Timings or Profile link:
12/08: https://timings.aikar.co/?id=10ebfccb9f24430baa382757134a0e0b
12/08: https://timings.aikar.co/?id=a8a5be138261480b85ed85e8bd6443a8
Update:
14/08: https://timings.aikar.co/?id=8e3b5b7f355c4c71889b3fb5c25ddf9c
14/08: https://timings.aikar.co/?id=542dc2cc4e954783be69e1af7e0b42a8

### Description of issue:
When my server reaches approximately 20 players, the TPS starts to drop sharply.

### Plugin list:
AdvancedAFKPlugin*, antiRedstoneClock, AuctionHouse, AuthMe, BuycraftX, Citizens, DiscordSRV, EntityTrackerFixer, Essentials, EssentialsMysqlStorage, EssentialsSpawn, HolographicDisplays, LeaderHeadsRevamped, LimitPillagers, LitePlaytimeRewards, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, PlaceholderAPI, ProtocolLib, PvPManager, RandomTeleport, React*, ReferralSystem, SkinsRestorer, SpecializedCrates, StackMob, SuperCredits, SuperLobby, TAB, TheNewEconomy, Towny, TownyChat, TownyFlight, TownyNameUpdater, Vault, VillagerOptimiser, WitherAC, WorldBorder, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml: https://pastebin.com/CLGxTmqZ
spigot.yml: https://pastebin.com/3748SV8W
paper.yml: https://pastebin.com/sNxCsL1w
server.properties: https://pastebin.com/f4bY0r9U

### Paper build number:
This server is running Paper version git-Paper-133 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Previous version: git-Paper-127 (MC: 1.16.1)

### Hosting / VPS
![image](https://user-images.githubusercontent.com/21694696/90067234-2e333f80-dcc5-11ea-9dad-650aebeb1f5d.png)
https://contabo.com/?show=vps | VPS L SSD

**Comment by electronicboy** [comment]
for support with timings, please use discord/irc; In general, looks like your hardware is just slow

**Comment by gabenitez0** [comment]
> for support with timings, please use discord/irc; In general, looks like your hardware is just slow
i attached hardware data

**Comment by gabenitez0** [comment]
> for support with timings, please use discord/irc; In general, looks like your hardware is just slow

i attached hardware data

**Comment by NikoEatsPancakes** [comment]
> i attached hardware data

your hardware sucks

**Comment by gabenitez0** [comment]
> > i attached hardware data
> 
> your hardware sucks

what do you recommend? I don't know what is the criteria to choose
