### ISSUE TITLE
Paper won't build

### ISSUE THREAD

**Issue by c0d3rb0y** [PaperMC/Paper#4121]
used Git for Windows Bash, and did ./paper jar, did not build
here's the output

edit: made the windows thing clear

> Downloading unmapped vanilla jar...
Applying class mappings...
Applying member mappings...
Creating remapped jar...
Installing remapped jar...
Downloading 1.16.1 JSON Data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39583  100 39583    0     0   299k      0 --:--:-- --:--:-- --:--:--  301k
/c/Users/epicd/OneDrive/Documents/GitHub/Paper/work/Minecraft/1.16.1/1.16.1.json - https://launchermeta.mojang.com/v1/packages/41a855ae58cb7d5f401c5b23307f7f621682ca49/1.16.1.json
Downloading com.mojang:datafixerupper:3.0.25 Sources
Extracting com.mojang:datafixerupper Sources
./scripts/decompile.sh: line 59: jar: command not found
Failed to build Paper

**Comment by Proximyst** [comment]
Install the required applications as noted in CONTRIBUTING.

**Comment by electronicboy** [comment]
> ./scripts/decompile.sh: line 59: jar: command not found

You're missing the JDK
