### ISSUE TITLE
Inventory Click Event Bug

### ISSUE THREAD

**Issue by Ergenta** [PaperMC/Paper#4122]
there's a problem with inventory click event
When taking an item out of someone else's inventory and placing it into yours, the item auto moves to another location

I place item from other person into my inventory here as shown in this

<img width="179" alt="Annotation 2020-08-12 014238" src="https://user-images.githubusercontent.com/25316276/89983705-af46f400-dc3d-11ea-8a1f-0ab52bcbd657.png">

and moves here instantly when placed
<img width="167" alt="Annotation 2020-08-12 014256" src="https://user-images.githubusercontent.com/25316276/89983728-bc63e300-dc3d-11ea-8218-d104b99315ba.png">

Doesn't happen every time but happens about half the time

using paper 1.16.1 b134 with ess v2.18.0 and v2.18.21
Only essentials was installed when testing this

<img width="453" alt="Annotation 2020-08-12 033440" src="https://user-images.githubusercontent.com/25316276/89993771-d1943e00-dc4c-11ea-91fa-bf6bd2c4ad41.png">

Also does it with these 
<img width="331" alt="Annotation 2020-08-12 040810" src="https://user-images.githubusercontent.com/25316276/89997219-7b75c980-dc51-11ea-914c-33a32c244341.png">
with both with Optifine 1.16.1 and default vanilla client
There's no error and using default configs

Essentials said it's a spigot bug https://github.com/EssentialsX/Essentials/issues/3588

**Comment by Chew** [comment]
And we aren't Spigot, this is an upstream bug.
