### ISSUE TITLE
Server Crash when I walks into nether portal

### ISSUE THREAD

**Issue by wybran** [PaperMC/Paper#4126]
### Link/paste of stack trace
https://pastebin.com/agWGbgji

### Plugin list:
Plugins (33): AntiCheatReloaded, AutoMessage*, BeautyQuests, BungeeTabListPlus, ChatEmojis, Citizens, CoreProtect, DeathMessagesPrime, DeluxeMenus, Essentials, EssentialsChat, EssentialsSpawn, FMCore, HeadDatabase*, HolographicDisplays, LuckPerms, Maintenance, MobFarmManager, PlaceholderAPI, ProtectionStones, ProtocolLib, RandomTeleport, Shopkeepers, SignEdit, SimpleRename, SkinsRestorer, SuperVanish, TAB, Vault, VipSlot*, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Actions to reproduce (if known):
Server Crash when I walks into nether portal

### Paper build number:
This server is running Paper version git-Paper-"1ba2f2145" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by Proximyst** [comment]
Issues for 1.16.2 are to be reported on https://github.com/PaperMC/Paper/pull/4123.

**Comment by wybran** [comment]
server crash caused Citizens plugin
