### ISSUE TITLE
Client Crash/kick on open horse/donkey inventory

### ISSUE THREAD

**Issue by RgtArRr** [PaperMC/Paper#4127]
There is no error/stacktrace on console. The world was made on 1.16.1, and client kick with natural/egg horses with or without saddle

### Plugin list:
SAML,DiscordBotAPI,  ProtocolLib, PluginHider, ImageOnMap, and a custom made for chat/discord integration/joinMessage

### Actions to reproduce (if known):
Just press E for open horse inventory, also works with Shift + right click on horse
[video.zip](https://github.com/PaperMC/Paper/files/5072412/video.zip)

### Paper build number:
git-Paper-"1ba2f2145" (MC: 1.16.2)

I know there is not too much info for this, but I can grab more info if needed, just tell me how

**Comment by aikar** [comment]
try without SAML and ProtocolLib. And you'll have to upload video to youtube if you want it seen, as sorry not downloading videos....

**Comment by RgtArRr** [comment]
Now I try it without those plugins, and its the same. About the video you don't miss too much (when press e for horse inventory, insta client crash)

![image](https://user-images.githubusercontent.com/5290134/90308292-03531200-dea4-11ea-9ee4-589065e5e9a9.png)

**Comment by Proximyst** [comment]
Cannot reproduce on 1.16.2. Are you still able to do it?

![https://uwu.whats-th.is/2cTJ8uD.png](https://uwu.whats-th.is/2cTJ8uD.png)

**Comment by RgtArRr** [comment]
Right now I'm using paper 1.16.2 rc4
When I press E on a horse, it crash immediately

https://www.youtube.com/watch?v=Wd0bcYhydF4

there is no output on console 
[01:08:38 INFO]: RgtArRr issued server command: /version
[01:08:38 INFO]: /version
[01:08:58 INFO]: RgtArRr lost connection: Disconnected

as aikar says, I delete some plugins but it still happens

**Comment by electronicboy** [comment]
Check the proxy and server logs, that was a disconnect between the proxy and the server, not the client

**Comment by RgtArRr** [comment]
I forgot the proxy, sorry 
[01:08:58 WARN]: [/190.233.26.116:49010|RgtArRr] <-> DownstreamBridge <-> [survival] - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.GameState 30 Protocol GAME Direction TO_CLIENT
[01:08:58 INFO]: [RgtArRr] disconnected with: The server you were previously on went down, you have been connected to a fallback server

**Comment by electronicboy** [comment]
best guess is outdated proxy or something somewhere mangled a packet

**Comment by RgtArRr** [comment]
Omg, I was using waterfall #368, I update to #370 and it works like a charm.
