### ISSUE TITLE
1.16.2 Custom Worlds Incompatibility

### ISSUE THREAD

**Issue by agent320** [PaperMC/Paper#4128]
### What behaviour is expected:
To see the custom dimensions added by my datapack to be present in the game.

### What behaviour is observed:
The dimensions are inaccessible both via admin commands and the intended ways to access them

### Steps/models to reproduce:
attempt to use any custom dimension datapack in 1.16.2 on a paper 1.16.2 build.

### Plugin list:
None, no plugins were present

### Paper build number:
git-Paper-"1ba2f2145" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

### Anything else:
Please excuse me if this is already on your radar but hasnt been implemented into paper yet.

**Comment by Proximyst** [comment]
Reproduce on 1.16.1 or report on the 1.16.2 PR: https://github.com/PaperMC/Paper/pull/4123

**Comment by rrvk** [comment]
https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-6073?filter=allopenissues

**Comment by bop34** [comment]
This HAS to be done! I think everyone would be so happy about it. I think it might be a technical linitation with paper though

**Comment by JRoy** [comment]
Should(?) be fixed as of a08be1ec7cfe9a7aa134a073382407c53264fcba (Build 594)

**Comment by Prof-Bloodstone** [comment]
Can confirm this works with datapack addded here: https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-6073

Both custom biomes (as seen in the screenshot) as well a custom dimension was added. I'm not sure why upstream issue is still open with recent activity, but I think it's safe to close.

![2021-04-23_22 16 05](https://user-images.githubusercontent.com/46570876/115925595-b20f0f80-a481-11eb-9f88-5c0e2a8fdd5b.png)
