### ISSUE TITLE
stickey piston doesnt work

### ISSUE THREAD

**Issue by JulianBorghuis** [PaperMC/Paper#4130]
### What behaviour is expected:
___What you expected to see___
Normally i see the block move by an sticky piston
### What behaviour is observed:
___What you actually saw___
No blocks where moved

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
https://gyazo.com/a71e91676c99e2bf765018b22311c889
### Plugin list:
___A list of your plugins___
Essentials, worldedit, worldguard
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
Paper 1ba2f2145 1.16.2
### Anything else:
___Anything else you think may help us resolve the problem___
no

**Comment by amnotbananaama** [comment]
This is almost certainly not a Paper issue. Check [this](https://worldguard.enginehub.org/en/latest/regions/common-scenarios/#why-don-t-pistons-work) link for information specific to the WorldGuard plugin.

**Comment by Proximyst** [comment]
It works fine on 1.16.2. This is a plugin issue; please join our Discord if you need further help.
