### ISSUE TITLE
Server stop reponding after ~an hour

### ISSUE THREAD

**Issue by Momonche** [PaperMC/Paper#4134]
###  Timings or Profile link:
https://pastebin.com/RVFL32Ak

### Description of issue:
My lobby server start to crash after ~an hour
It's not really a crash but the server start to print errors and TPS drop, and more errors, and stop responding

### Plugin list:
Plugins (8): AuthMe, CoreProtect, LuckPerms, PlaceholderAPI, ProtocolSupport, SkinsRestorer, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml https://pastebin.com/iXvw7r34
spigot.yml https://pastebin.com/4C8uJqp1
paper.yml https://pastebin.com/EjRYiEGu
server.properties https://pastebin.com/ShDUB09r

### Paper build number:
git-paper-133 (MC 1.16.1)

**Comment by Brokkonaut** [comment]
The server just looks overloaded. Please create a timings report (/timings paste) while it is lagging.

**Comment by Momonche** [comment]
https://timings.aikar.co/?id=1ab38f7bf15f4853af6d791681c68c6b#timings

**Comment by electronicboy** [comment]
Server is overloaded, low memory situations are also far from ideal with modern MC.
