### ISSUE TITLE
BookMeta unexpected return for getGeneration

### ISSUE THREAD

**Issue by RgtArRr** [PaperMC/Paper#4138]
### What behaviour is expected:
b.getGeneration() for a Original Book, return Generation.ORIGINAL

### What behaviour is observed:
b.getGeneration() for a Original Book, returns Null

### Steps/models to reproduce:
I was using a hopper event
    @EventHandler
    public void hoper(InventoryPickupItemEvent e) {
        if (e.getItem().getItemStack().getType().equals(Material.WRITTEN_BOOK)) {
            BookMeta b = (BookMeta) e.getItem().getItemStack().getItemMeta();
            System.out.println(b.getGeneration());
        }
    }

output console
[03:14:31 INFO]: null
[03:14:57 INFO]: COPY_OF_ORIGINAL
[03:15:26 INFO]: COPY_OF_COPY

### Paper build number:
paper1.16.2.r3

### Anything else:
If a book is Copy or CopyofCopy, return is fine Generation.COPY_OF_ORIGINAL & Generation.COPY_OF_COPY

**Comment by Proximyst** [comment]
This is expected behaviour it seems. Check [`#hasGeneration`](https://papermc.io/javadocs/paper/1.16/org/bukkit/inventory/meta/BookMeta.html#hasGeneration--) and assume `ORIGINAL` if it's `false`. [`#getGeneration`](https://papermc.io/javadocs/paper/1.16/org/bukkit/inventory/meta/BookMeta.html#getGeneration--) is nullable.

**Comment by Rincewind34** [comment]
When this is the expected behaviour, how could #getGeneration return Generation.ORIGINAL?

**Comment by Proximyst** [comment]
When the NBT is set to be ORIGINAL (i.e. generation 0).

**Comment by RgtArRr** [comment]
My best to handle this was `(b.getGeneration() == null || b.getGeneration().equals(BookMeta.Generation.ORIGINAL)`

**Comment by kennytv** [comment]
It's just another case of Bukkit having bad API design. It not being present should always mean it's the original
