### ISSUE TITLE
New Collision Team Error/Crashing

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#414]
Error, followed by crash when the newest implementation of player collision (with collision team) is called during server shutdown. 

Event: Scoreboard.removePlayerFromTeam

**Paper Settings:**
enable-player-collisions: false
save-empty-scoreboard-teams: true (tried both true and false, same issue)

**Crash and Error:**
http://hastebin.com/hukefuwazi.vbs

**Actions to reproduce:**
Stop/Restart server with players online. Everything functions fine (from what I saw) if no players are online at shutdown.

**Paper build number:**
853

**Comment by CeIebrimbor** [comment]
(edit) Confirmed that 0 players online will not cause this. That's probably obvious based on the error, but wanted to be as informative as possible.

**Comment by zachbr** [comment]
Very probable it's some glaring mistake I made, will investigate soon

**Comment by CeIebrimbor** [comment]
Thanks!

Also, thank you for adding this. It's a load off doing it manually :+1:

**Comment by CeIebrimbor** [comment]
Related question, does "collideRule_9576" have team option "FriendlyFire", default nametag colors, "NameTagVisibility" and "DeathMessageVisibility" all set to vanilla expectations? Basically making sure the new team won't inadvertently disable pvp and show nametags and hide death messages, etc.

**Comment by zachbr** [comment]
Yes, all of the rest of the settings are their vanilla defaults. Feel free to check the patch file to confirm :)

**Comment by CeIebrimbor** [comment]
Thank you!

**Comment by zachbr** [comment]
Please test against builds 854+
This should be fixed.
