### ISSUE TITLE
Allow sending bossbar update asynchronously

### ISSUE THREAD

**Issue by marcbal** [PaperMC/Paper#4140]
**Is your feature request related to a problem? Please describe.**
I notices since my recent update of paper 1.15.2 that my custom bossbar are not updated anymore while my server is lagging (for instance, a worldedit command or whatever blocking the main thread). My custom bossbar are used to display the TPS of the server and the memory usage in realtime. The thing is that they are now freezing when the main thread is blocked, making us unable to monitor the lag.

**Describe the solution you'd like**
I found the [commit responsible for this](https://github.com/PaperMC/Paper/commit/f37381ea8aa3ad48c9d0540286347d8603f08359). While I understand the new addition making most of the packet sent using the main thread, I would suggest to add at least the bossbar packet to the list found in `NMS.NetworkManager.InnerUtil.canSendImmediate(...)` method.

**Describe alternatives you've considered**
An alternative solution I considered in 1.15.2, that I was doing temporarily, is to change the value of `NMS.NetworkManager.queueImmunity` just before sending the packet and restore is to the previous value just after. But this value is not there anymore in Paper 1.16...

**Additional context**
(for those who are curious, here are my boss bars)
![image](https://user-images.githubusercontent.com/6602556/90340508-014e9780-dff9-11ea-8fc6-f3ba62943453.png)

**Comment by marcbal** [comment]
I updated my feature request to match the fact we are in 1.16 now.
Is it possible to add the label "version: 1.16" and possibly "type: feature" too? Thanks

**Comment by Chew** [comment]
Not sure why it had a version label to begin with
