### ISSUE TITLE
Vanilla teams Colors Don't display in chat. 1.16.2

### ISSUE THREAD

**Issue by swampyhobgoblin** [PaperMC/Paper#4142]
team colors don't display in chat again. 

was an issue in 1.16.1 until build 130 came out.

https://github.com/PaperMC/Paper/issues/3676

**Comment by BillyGalbreath** [comment]
Unable to reproduce.

Paper 1.16.2 RC3

```
/team add a
/team join a
/team modify a color dark_green
/team modify a prefix ["",{"text":"as","color":"red"}]
```

![image](https://user-images.githubusercontent.com/332527/90342697-e61b6200-dfcf-11ea-98b2-4c1b042cd979.png)

**Comment by BillyGalbreath** [comment]
Be sure you set vanilla scoreboard name colors in `paper.yml`

```
use-vanilla-world-scoreboard-name-coloring: true
```

And be sure you dont have any plugin listening to the sync PlayerChatEvent. Any plugin that listens to that event will cause the server to ignore the above mentioned setting for all use-cases.

**Comment by swampyhobgoblin** [comment]
Not sure, the only new plugin i added while switching to 1.16.2 was coreprotect. Not sure if that would be causing the issue ill try removing it later to see if it is but it acts the same as it did before the fix in 1.16.1.  You can see the color in a whisper but not in chat.  I have use vanilla name coloring set to true in the yml 

![2020-08-16_16 33 57](https://user-images.githubusercontent.com/69768483/90343467-94c69f00-dfde-11ea-8d49-1d903d79b555.png)

**Comment by Rincewind34** [comment]
Try reproduce the bug on your server without the plugins anyway. This way we can figure out, if the "bug" is caused by your configuration.

**Comment by MiniDigger** [comment]
my bets are on discordsrv causing this

**Comment by swampyhobgoblin** [comment]
i removed both discordsrv and coreprotect and ended up with the same results. You can see the team color in a whisper but not in normal chat. I've had discordsrv installed for a while and never had any issues with it effecting team colors.

**Comment by BillyGalbreath** [comment]
> i removed both discordsrv and coreprotect and ended up with the same results. You can see the team color in a whisper but not in normal chat. I've had discordsrv installed for a while and never had any issues with it effecting team colors.

Replicate without plugins

**Comment by swampyhobgoblin** [comment]
so i set up a whole new server and it does seem to be the discordsrv plugin that's causing the issues.. =/  The colors still display in a whisper though, just not in chat. Is there a way around this?

**Comment by swampyhobgoblin** [comment]
It was the discordsrv plugin, When i updated to paper 1.16.2 I also updated the discordsrv plugin, seems something in the new version of that is whats causing the issue with the chat.  Downgraded back to the previous version and everything works as it should.  Looked exactly like the issue in paper 1.16.1 though.  you could see the colors in tab and a whisper but not in chat xD... 

Problem solved.

**Comment by MiniDigger** [comment]
yey I won

**Comment by BillyGalbreath** [comment]
> It was the discordsrv plugin, When i updated to paper 1.16.2 I also updated the discordsrv plugin, seems something in the new version of that is whats causing the issue with the chat. Downgraded back to the previous version and everything works as it should. Looked exactly like the issue in paper 1.16.1 though. you could see the colors in tab and a whisper but not in chat xD...
> 
> Problem solved.

I just learned the DiscordSRV has an alert system that attaches itself to every single event handler.

~~Do you have anything in your alerts yml file in DiscordSRV's plugin directory? If yes, can you try clearing it out [back to default](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/alerts/en.yml) and testing this issue again?~~

~~Scratch that. Tested it myself and it indeed still registers a listener to every single handler with an empty alerts yml.~~

~~You'll have to downgrade DiscordSRV to 1.19.0 before the alert system was implemented.~~

~~This advice goes to anyone that sees this. It doesnt just effect the color issue mentioned in this ticket, but it puts your entire server's chat in [sync mode](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/PlayerConnection.patch#959-997)~~

This was fixed in DiscordSRV. See my next comment

**Comment by BillyGalbreath** [comment]
DiscordSRV has [fixed the issue](https://github.com/DiscordSRV/DiscordSRV/commit/f6b95a3859ed2604b455516ee588434041a6e53f) in their latest [dev builds](https://snapshot.discordsrv.com/).
