### ISSUE TITLE
PlayerAttemptPickupItemEvent setFlyAtPlayer will not be set to false when cancelling the event

### ISSUE THREAD

**Issue by fayeinmay** [PaperMC/Paper#4144]
### What behavior is expected:
As described on: https://papermc.io/javadocs/paper/1.16/org/bukkit/event/player/PlayerAttemptPickupItemEvent.html#setFlyAtPlayer-boolean-

the setFlyAtPlayer value should be set to false when cancelling the event.

### What behavior is observed:
The value setFlyAtPlayer will not be set to false when cancelling the event, so the player will not be able to pick up the item server-side, but on the client-side, it gets sucked towards the player and the item disappears from the ground from that very player, but will not land into their inventory.

### Steps/models to reproduce:
Cancel the PlayerAttemptPickupItemEvent, but not set setFlyAtPlayer to false.
Try to pick up an item.

### Plugin list:
No plugins except this plugin with that event to test it.

### Paper build number:
git-Paper-134

### Anything else:
Nope

**Comment by BillyGalbreath** [comment]
@zachbr This was introduced during your manual merge

I PR'd it with the setting of cancel <https://github.com/PaperMC/Paper/pull/823/files#diff-0fd0b894190c81da206be3db5e564a08R90>

Manual merge didn't have it <https://github.com/PaperMC/Paper/commit/d7039347b06ecc8c65e3dbe0ca532d83960c75ef#diff-0fd0b894190c81da206be3db5e564a08R81>

**Comment by zachbr** [comment]
Must've missed it. Easy PR for someone bored.
