### ISSUE TITLE
Failed to build Paper

### ISSUE THREAD

**Issue by Sneakometer** [PaperMC/Paper#4148]
I tried building latest paper but couldn't get it to work.
`./paper jar`
![Screenshot_1](https://user-images.githubusercontent.com/50603525/90440820-28c86180-e0d8-11ea-9a19-8b51e8e732d9.png)

`java -version`
![Screenshot_2](https://user-images.githubusercontent.com/50603525/90440936-59a89680-e0d8-11ea-9230-3fd1418407b3.png)

On debian 9 (stretch)

**Comment by electronicboy** [comment]
One of the processes was killed by something out of our control, make sure that your machine has plenty of ram, etc; check dmesg

**Comment by Sneakometer** [comment]
Tried it on 3 other machines, same result. How much ram do you need to build this?

**Comment by aikar** [comment]
please jump on discord to paper-dev for help for this.
