### ISSUE TITLE
Water not behaving properly.

### ISSUE THREAD

**Issue by skyrawr** [PaperMC/Paper#4152]
### What behaviour is expected:
___What you expected to see___
non-source blocks dissapearing when source block is removed

### What behaviour is observed:
___What you actually saw___
non-source blocks got stuck and not dissapeared correctly, leaving some water blocks behind

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Create large lava cast mountain
Place water at top
Wait about 5 seconds
Remove water

### Plugin list:
___A list of your plugins___
AdvancedBan*, CoreProtect, DiscordSRV, EnderBank, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, LastLoginAPI, LibsDisguises, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, PlayerWarps, ProtocolLib, QuickShop, Skellett, skGlide*, skRayFall, Skript, SuperVanish, TAB, TnTRegen, Vault, VoidGenerator, WorldEdit, WorldGuard

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
git-Paper-130 (MC: 1.16.1)

### Anything else:
___Anything else you think may help us resolve the problem___
![image](https://user-images.githubusercontent.com/54551194/90614952-0b001700-e214-11ea-8b1d-de3f652004e7.png)
![image](https://user-images.githubusercontent.com/54551194/90614970-13f0e880-e214-11ea-917f-e8e0c5a21ad6.png)
![image](https://user-images.githubusercontent.com/54551194/90614984-1a7f6000-e214-11ea-94cf-bdcd7c238481.png)
![image](https://user-images.githubusercontent.com/54551194/90615000-21a66e00-e214-11ea-83d9-fe7e83a7b027.png)
![image](https://user-images.githubusercontent.com/54551194/90615011-25d28b80-e214-11ea-88e9-733cde657dc0.png)
![image](https://user-images.githubusercontent.com/54551194/90615021-29661280-e214-11ea-82de-038616fdf844.png)

**Comment by Proximyst** [comment]
Reproduce without plugins.

**Comment by Proximyst** [comment]
As this is getting stale, and I'd imagine you want immediate assistance in fixing such a vital issue, I'll assume you've figured it out and can close the issue.
