### ISSUE TITLE
Certain non-naturally generated monsters will not be counted in the monster generation limit

### ISSUE THREAD

**Issue by Redlnn** [PaperMC/Paper#4156]
### What behaviour is expected:
Villagers who become zombie villagers due to being killed by zombies, and villagers who become witches struck by lightning will be counted towards the monster spawn limit. This can inhibit monster spawning in some cases.

### What behaviour is observed:
- Villagers who are killed by zombies and become zombie villagers have the NBT tag `Paper.SpawnReason: "INFECTION"`. 
- Villagers struck by lightning and turned into witches do not have the `Paper.SpawnReason` tag. 
- Monster (such as zombie) generated by spawn egg and command have NBT tags of `Paper.SpawnReason: "SPAWNER_EGG"` and `Paper.SpawnReason: "DEFAULT"`.
- Only monsters with `Paper.SpawnReason: "NATURAL"` tag will be counted towards the monster spawn limit

### Plugin list:
No plugins used

### Paper build number:
Paper version git-Paper-"2b4ce0b" (MC: 1.16.1)   &   Paper version git-Paper-"47740f6" (MC: 1.16.2)

### Anything else:
The following options have been set in the configuration file of paper.yml
- `count-all-mobs-for-spawning: false`
- `per-player-mob-spawns: false`

**Comment by Prof-Bloodstone** [comment]
I believe `count-all-mobs-for-spawning` is just for handling this. If it's set to true, it counts all mobs towards spawning mob cap, setting it to false means that non-natural mobs (i.e. from spawners) are not counted towards the limit (so that a single person can't AFK at a spawner and nuke spawns for everyone). If you want all mobs to be counted towards spawn limit, then you need to set it to `true`. 
See: https://paper.readthedocs.io/en/latest/server/configuration.html#count-all-mobs-for-spawning

**Comment by Redlnn** [comment]
> I believe `count-all-mobs-for-spawning` is just for handling this. If it's set to true, it counts all mobs towards spawning mob cap, setting it to false means that non-natural mobs (i.e. from spawners) are not counted towards the limit (so that a single person can't AFK at a spawner and nuke spawns for everyone). If you want all mobs to be counted towards spawn limit, then you need to set it to `true`.
> See: https://paper.readthedocs.io/en/latest/server/configuration.html#count-all-mobs-for-spawning

If I set `count-all-mobs-for-spawning` to `true`, the monsters spawned by the spawner will also be counted into the monster spawning limit, which is different from vanilla’s behavior.

**Comment by Prof-Bloodstone** [comment]
> If I set `count-all-mobs-for-spawning` to true , the monsters spawned by the spawner will also be counted into the monster spawning limit, which is different from vanilla’s behavior.

I'm pretty sure that vanilla counts spawner mobs towards mob cap - there are spawner based "peaceful mob switches" in vanilla.
Example video that talks about it: https://youtube.com/watch?v=GeXjk04neqw&t=160
