### ISSUE TITLE
Enderman run into the water

### ISSUE THREAD

**Issue by Disguys** [PaperMC/Paper#4165]
### What behaviour is expected:
not run into the water

### What behaviour is observed:
run into the water

### Steps/models to reproduce:
video about the bug - https://youtu.be/BKf2vQFamkI

### Plugin list:
https://imgur.com/a/7XQXNL6

### Paper build number:
fork paper 1.16.2, maybe pathfinder optimization.

**Comment by aurorasmiles** [comment]
Could you reproduce this using Paper, and not Yatopia?

**Comment by Chew** [comment]
Hello, as aurora said we do not support Paper forks. If this issue still occurs on Paper, feel free to open another issue. Thanks!
