### ISSUE TITLE
PlayerInteractEntityEvent bugged out with mounts

### ISSUE THREAD

**Issue by ASlastic** [PaperMC/Paper#4190]
### What behaviour is expected:
PlayerInteractEntityEvent - I expected to mount on the Ender Dragon

### What behaviour is observed:
Server thinking I'm mounted but am not, causing it to treat me as if I'm mounted on it.

So... I re-logged and...
Was mounted on the EnderDragon, with it creating another one out of nowhere???

### Steps/models to reproduce:

@EventHandler
public void onInteract(PlayerInteractEntityEvent e) {
	Player p = e.getPlayer();
	if(e.getRightClicked() instanceof CraftEnderDragonPart) {
		if(e.getHand() == EquipmentSlot.OFF_HAND) return;
		e.getRightClicked().addPassenger(p);
	}
}

### Plugin list:
DarkFools, WorldEdit

### Paper build number:
This server is running Paper version git-Paper-138 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
YouTube video link showing behaviour:

https://www.youtube.com/watch?v=qss0wggXPGI

**Comment by BillyGalbreath** [comment]
Dont add yourself as a passenger to the complex part. Use the parent of the complex part (the dragon itself).

https://papermc.io/javadocs/paper/1.16/org/bukkit/entity/ComplexEntityPart.html#getParent--

```java
    @EventHandler
    public void onInteract(PlayerInteractEntityEvent event) {
        if (event.getHand() != EquipmentSlot.HAND) return;
        Entity entity = event.getRightClicked();
        if (entity instanceof ComplexEntityPart) {
            ComplexLivingEntity dragon = ((ComplexEntityPart) entity).getParent();
            dragon.addPassenger(event.getPlayer());
        }
    }
```

**Comment by ASlastic** [comment]
Thank you I didn't know much about ComplexEntityParts
