### ISSUE TITLE
Cancelling PlayerInteractEvent does not prevent armor equipping

### ISSUE THREAD

**Issue by CrystallDEV** [PaperMC/Paper#4194]
### What behaviour is expected:
Cancelling the PlayerInteractEvent prevents players from equipping armor from their hand

### What behaviour is observed:
Equipping an item with rightclick while having the item in hand still equips the item. This was not the case in <1.16 versions

### Steps/models to reproduce:
- Listen for a PlayerInteractEvent with rightclicks and cancel it
- Take armor in hand and press rightclick to equip it
- Item gets still equipped even tho the event got cancelled

### Plugin list:
- WorldEdit, Spark

### Paper build number:
This server is running Paper version git-Paper-135 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Previous version: git-Paper-108 (MC: 1.16.1)
You are 3 version(s) behind

--> New Versions don't affect the problem

**Comment by Prof-Bloodstone** [comment]
Unable to reproduce on `git-Paper-138 (MC: 1.16.1)`, with following code:
```kotlin
companion object {
    private val hands = listOf(EquipmentSlot.OFF_HAND, EquipmentSlot.HAND)
}
/**
 * Cancel right click interaction events - see if player will equip the armor
 * Bug: https://github.com/PaperMC/Paper/issues/4194
 */
@EventHandler
public fun onPlayerInteraction(event: PlayerInteractEvent) {
    if (event.hand in hands) {
        event.player.sendMessage("You are not allowed to use your hands")
        event.isCancelled = true
    }
}
```

My armor (chestplate) stays in my hand after right-clicking air, blocks or entities - regardless if it's in main of offhand.

**Comment by CrystallDEV** [comment]
I just checked this with a clean installation and can confirm, that the bug is not anymore present. I also updated paper, but this should not have impacted the result.
