### ISSUE TITLE
Exception while ticking — Fire in The End

### ISSUE THREAD

**Issue by Prixi** [PaperMC/Paper#4195]
### Link/paste of stack trace

https://pastebin.com/SYBhJweK

### Plugin list:
AdvancedBan
AutoMessager
CoreProtect
DiscordSRV
DiscordSRV-Staff-Chat
Essentials
EssentialsGeoIP
EssentialsSpawn
GroupManager
HolographicDisplays
Landlord
MyCommand
OreAnnouncer
ProtocolLib
SimplePrefix
SkipNight
SuperbVote
Votifier
WorldEdit
WorldGuard

### Actions to reproduce (if known):
Light a fire in The End.

### Paper build number:
https://i.imgur.com/XFTUNFq.png

**Comment by Prixi** [comment]
I created a new world and tested it again. It didn't occur in a new world.

**Comment by Rincewind34** [comment]
Don't use hastebin, it will get deleted at some time

**Comment by Prixi** [comment]
> 
> 
> Don't use hastebin, it will get deleted at some time

Edited into a Pastebin instead.

**Comment by electronicboy** [comment]
This has already been fixed, update
