### ISSUE TITLE
1.16.2 Build 142 through 148 - Unable to join, always times out

### ISSUE THREAD

**Issue by isaaclepes** [PaperMC/Paper#4200]
###  Timings or Profile link:
Unable to log in to pull report on 142

### Description of issue:
When using builds 142-148, I cannot join due to time out.  On client screen, it says 'Encrypting' until timeout.  Reverting to build 141 resolved the issue for us.

### Plugin list:
WorldEdit
Dynmap
Async World Edit

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___

### Other helpful links
https://pastebin.com/cYtN92vN

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

[05:51:31] [Server thread/INFO]: This server is running Paper version git-Paper-142 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by isaaclepes** [comment]
Tried the 148 build on my server, no players can join.  Removed plugins, same issue.  Is there something I did incorrectly here, just noticing the issue was closed very fast last time.

Tried using official 1.16.2 client and Optifine 1.16.2 pre-release client

Error stated is timeout.  From client side, the login stops on "Encrypting" before timing out.

Reverted back to 141 until next build comes out.

**Comment by Prof-Bloodstone** [comment]
142 had known issue, it was closed quickly, because it was quickly fixed. 144 should work. If you are still experiencing this, it would probably be best to create new issue on Github.

**Comment by isaaclepes** [comment]
> 142 had known issue, it was closed quickly, because it was quickly fixed. 144 should work. If you are still experiencing this, it would probably be best to create new issue on Github.

I am still having issues and will open a new issue report after play for a bit on 141 :).. Thank you!

**Comment by andreasbleck** [comment]
I've had the same issue happen on my server on build 148, but only for some players, they consistently couldn't join while other players where playing normally. Reverting to build 141 fixed the issue for those players that where affected.

**Comment by isaaclepes** [comment]
I was going to test today and open a new issue report, but the latest build is no longer having the issue for us.

**Comment by Chew** [comment]
Glad to hear it's all good now!
