### ISSUE TITLE
User kicked of with "Invalid custom payload"

### ISSUE THREAD

**Issue by dsluijk** [PaperMC/Paper#4201]
### What behaviour is expected:
The user should be able to join.

### What behaviour is observed:
The user is able to load the map for a brief second, before getting kicked off with the message "invalid custom payload"

### Steps/models to reproduce:
Attempt to join the server.

### Plugin list:
```
Plugins (18): ChestShop, Citizens, Denizen, DiscordSRV, DiscordSRV-Staff-Chat*, dynmap*, Dynmap-Towny, Essentials, Hyperverse, LuckPerms, PlotSquared, TheNewEconomy, TimeIsMoney*, Towny, TownyChat, Vault, WorldEdit, WorldGuard
```

### Paper version:
```
[Tue, 25. Aug 2020 13:45:24 GMT INFO] This server is running Paper version git-Paper-144 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[Tue, 25. Aug 2020 13:45:24 GMT INFO] Checking version, please wait...
[Tue, 25. Aug 2020 13:45:24 GMT INFO] Previous version: git-Paper-"dccaf59a0" (MC: 1.16.2)
[Tue, 25. Aug 2020 13:45:24 GMT INFO] You are running the latest version
```

### Anything else:
Full logs: https://pastebin.com/zYnnqTPQ
1.16.2 RC6 works fine.
Using the official Minecraft Launcher, with no customization. Happens to all users attempting to join. There is no proxy being used, the server is directly exposed to the internet.

**Comment by Kikisito** [comment]
I also got this problem when I updated to Paper build 138. Paper 137 works fine
Using Waterfall build 370. Affecting to all players with any client, including 100% vanilla.

**Comment by pietru2004** [comment]
same error https://paste.gg/p/anonymous/92b79aefccc540dfbff9bc5e697327e2

also ocurs at 1.16.1

**Comment by Phoenix616** [comment]
I assume this is caused by the brand [getting read with a fixed length](https://github.com/PaperMC/Paper/commit/627f4b8561115d40d6a39587d1ad94b0104f7e14#diff-b4287d0f0e533ab1e8babe81257e5da0R44) while the string is [actually send](https://wiki.vg/Plugin_channels#minecraft:brand) with a variable length.

**Comment by electronicboy** [comment]
readUTF8 takes the max length, not the total length, that looks fine?

**Comment by Phoenix616** [comment]
Hm, I see. Should only be able to happen if the sent length is above the actual string length.

Would be interesting if there is a proxy in front or any mods in use.

**Comment by thboehi** [comment]
Same issue on 1.16.1

**Comment by Proximyst** [comment]
We get that there is an issue (and we won't fix it on 1.16.1), but new "same here" posts won't help much. Please provide information about your setup such as:

- Paper version (MC version + build)
- Proxy? If so, version and which? (BungeeCord, Waterfall, Travertine, Velocity, Lilypad, etc. etc.)
- Is this an issue that affects *everyone* or just a subset (part of the larger amount) of your players?
- Plugins list
- Client information (100% vanilla? Fabric? Forge? Cheat/otherwise modified clients?)

Thank you for any information you can provide.

**Comment by VergilPrime** [comment]
Paper Version: git-Paper-144 (MC: 1.16.2)
Proxy: Bungeecord Build #1532
Effects: unknown, server in test mode.
Plugins: https://paste.thezomg.com/75560/92748159/
Client: Minecraft 1.16.2 with Optifine HD U G3 Pre-release 4

**Comment by Phoenix616** [comment]
@VergilPrime do you have any plugins on Bungee? And if so does it happen without them too? Also does it happen without Optifine and a plain Vanilla jar?

**Comment by VergilPrime** [comment]
I had old copies of PureCore and Vivecraft on BungeeCord but removed those. I tried with the unmodified 1.16.2 client as well, same result. Do you want me to try connecting to a vanilla server?

Edit: Direct connect to vanilla server = no problem.
Edit: Direct connect to Spigot server = same issue

**Comment by Chew** [comment]
Any problem on Waterfall?

**Comment by aikar** [comment]
1.16.1 users can simply use build 137 if you cant update to 1.16.2 yet.
what client mods are in use? this doesnt occur with vanilla client

**Comment by Phoenix616** [comment]
@VergilPrime can you post the stacktrace using Spigot too (and the exact version if it doesn't include that)

**Comment by PapiCapi** [comment]
Using : 

Paper 141 ( 1.16.2 )
Bungeecord build 1532
Vanilla client

I don't have any issue

**Comment by VergilPrime** [comment]
This seems to be happening again...
https://hastebin.com/fecibigivi.makefile
paper version 184, only Optifine installed.

**Comment by electronicboy** [comment]
can you replicate this without plugins? if yes, can you replicate without optifine (Doubt they're the issue, but 🤷 )

**Comment by VergilPrime** [comment]
Nevermind, this time it was Denizen.
