### ISSUE TITLE
XP error after falling into deactivated end portal

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#4205]
An error occurs when XP falls into a disabled end portal and the XP disappears. There are no problems with players or other items, if they enter the end portal they just stay there as desired.

error: https://pastebin.com/UdjXJ7uh
bukkit.yml: `allow-end: false`
Paper 1.16.1 - 135

**Comment by Prof-Bloodstone** [comment]
The logs kinda make sense for what you are saying - but I was unable to reproduce it on 1.16.2.
Maybe it got fixed in the meantime? Could you check? If it still occurs, do you have any plugins?

**Comment by TheoRetisch1** [comment]
The bug also occurs in 1.16.2 and it's due to CMI, thanks for the help!
