### ISSUE TITLE
Crash at random interval (something entity-related?)

### ISSUE THREAD

**Issue by Sabinno** [PaperMC/Paper#4208]
### **What behavior is expected:**
Not... this.

### **What behavior is observed:**
Crash at random interval. No apparent trigger. Appears to only occur when 1 or more players are online; that said, this could be the result of the bias of only paying attention to this issue when players reported a crash, then investigating subsequently.

### **Steps/models to reproduce:**
Frankly, I'm not sure. This is not manually reproducible.

### **Plugin list:** (at time of crash)
AAC, AltDetector, BanItem, CombatLogX, CooldownsX, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, LogBlock, LuckPerms, NameHide, ProtocolLib, RandomSpawnPlus, Reinforcement, StopShulkers, SuperTracerBlocker, WorldEdit

### **Paper version:**
Paper-131 (1.16.1) -- again, this happened some time ago.

### **Other information:**
It has not occurred in some time (possibly in part due to severely reduced player count), but I was asked to post about this issue here. There are no indicators of other plugins in this crash report, as far as I can tell, narrowing it down to either a PaperMC issue or a Minecraft Server issue. I'd like to at least rule out one of those.
Crash log (fairly ancient, was running b131, but can't find any more recent logs):
https://mcpaste.io/1bb06fb725d0d7da
Recent timings report (cannot find any from around time of crash, but hardly anything has changed since then)
https://timings.aikar.co/?id=5e9b48dbe86949949e3f190359843afe

**Comment by aikar** [comment]
This a common issue for ages now, just no super concrete source and no way to reproduce.

However someone did recently suggest something that seems valid to improve, so im about to push that up to solve it, though note it's only going to be on 1.16.2 as 1.16.1 is now unsupported.

**Comment by aikar** [comment]
and this is absolutely a duplicate but have no idea what the original(s) are because been so long/many.

**Comment by Sabinno** [comment]
Here's another crash log from last night. Actually affected players this time. I know there's an AAC message at the top, but this was happening long before we implemented AAC; I doubt it is related.

https://mcpaste.io/926770f1cd5bcd30
