### ISSUE TITLE
Soul sand underwater wrong

### ISSUE THREAD

**Issue by myk3sr** [PaperMC/Paper#4211]
### What behaviour is expected:

Soul sand uunderwater should push up air and make player float to the top,  It's very strange because it does push npc squids up even out of the water which is correct, but players get sucked down. 

### What behaviour is observed:

it pulls u down the opposite, which is what magma block should do. Boats sink also.

### Steps/models to reproduce:
Place soul sand underwater, preferably a stripe. Swim over it. Might have to reset server, seems a bit buggy

### Plugin list:
___A list of your plugins___

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Chew** [comment]
Please fill out template, notably:
* Plugins
* /version output

**Comment by Proximyst** [comment]
Most likely plugin issue.
