### ISSUE TITLE
Spawnpoint angle not working in 1.16.2

### ISSUE THREAD

**Issue by TechTitanX** [PaperMC/Paper#4212]
### What behaviour is expected:
___What you expected to see___

I expected the spawnpoint angle to spawn me facing the specified angle when spawnpoint was set.

### What behaviour is observed:
___What you actually saw___

I set the spawnpoint including the angle and it said the correct angle in chat. When I killed myself to test the spawnpoint it always faces me south ignoring the specified angle.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Load up any paper 145 1.16.2 server and run command "/minecraft:spawnpoint ~ ~ ~ 180" then do "/kill" then open f3 screen and look at the angle next to facing direction to see that it always spawns you facing south regardless of spawnpoint angle.

### Plugin list:
___A list of your plugins___

Armor stand editor
Image on Map
ImgMap
LagMeter
TangledMaze
Worldedit

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

git-Paper-145 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

I tested it on a brand new paper 145 server and the problem still persisted. Then I created a new vanilla 1.16.2 server and spawnpoint worked as expected. Below is an image of me on a paper 145 server setting spawnpoint with angle and killing myself and facing south instead of specified angle.
![image](https://user-images.githubusercontent.com/70251037/91254246-b62e3600-e716-11ea-9a57-d18a2e27bea3.png)

**Comment by MrIvanPlays** [comment]
upstream had released a fix. you may close this issue now

**Comment by Chew** [comment]
Dang you right, thanks @Machine-Maker for doin the heavy work

Closed in #4779
