### ISSUE TITLE
Error when ticking players

### ISSUE THREAD

**Issue by ClayCoffee** [PaperMC/Paper#4214]
### Link/paste of stack trace
    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___
https://paste.ubuntu.com/p/dBtT4g2CC7/
https://paste.ubuntu.com/p/BRs5hTxwYP/

### Plugin list:
___A list of your plugins___
Plugins (67): AAC, AsteroidBelt, BBSToper*, BetterTellraw*, BottledExp, ChestCommands, ClayAdvancedTowny, ClayAPI, ClayPlayerPoints, ClaySign, ClayTech, ClayTest, ClayTownyFlight, ClayTownyWar, CMI, CMIEInjector*, CMIPaperLib, ColoredBooks*, CoreProtect, CS-CoreLib, DisableAI*, dynmap*, Dynmap-Towny*, EcoPower, EntityTrackerFixer, EternalBroadcast*, HolographicDisplays, InfoBook, JukeBox, LaggRemover, LiteBans, LocationMarker, LoneLibs, LuckPerms, mcMMO, Mczf*, MczfGui, Multiverse-Core, MyPet, NoteBlockAPI, OPLimiter, PlaceholderAPI, PluginConstructorAPI, PlugMan, ProtocolLib, ProtocolSupport, ProtocolSupportStuff, QualityArmoryVehicles, QuickShop, ServerBooster, Shopkeepers, Slimefun, SlimefunImprover, StackMob, TitleManager, Towny, TownyChat, TownyGUI, TownyNameUpdater, TownyTitle*, Vault, ViaVersion, VillagerOptimiser, VipSystem*, WorldBorder, WorldEdit, WorldGuard

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Let some players join the server

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-145 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by ClayCoffee** [comment]
Error logs and more information here:
https://paste.ubuntu.com/p/dBtT4g2CC7/
https://paste.ubuntu.com/p/BRs5hTxwYP/

**Comment by Octol1ttle** [comment]
Replicate without plugins

**Comment by MrIvanPlays** [comment]
Duplicate of #4199
