### ISSUE TITLE
Zombie infection not working with infection chance settings for 100% conversion

### ISSUE THREAD

**Issue by vitalyraif** [PaperMC/Paper#4215]
### What behaviour is expected:
100% zombie villager conversion

### What behaviour is observed:
not 100% zombie villager conversion
### Steps/models to reproduce:
Set the difficulty to normal and in paper.yml set the option zombie-villager-infection-chance: to 1.0

### Plugin list:
GriefPrevention

### Paper version:
[18:48:13 INFO]: This server is running Paper version git-Paper-147 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[18:48:13 INFO]: Checking version, please wait...
[18:48:14 INFO]: Previous version: git-Paper-144 (MC: 1.16.2)
[18:48:14 INFO]: You are running the latest version

### Anything else:
Tried per world
  world:
    zombie-villager-infection-chance: 1.0
no difference

**Comment by amnotbananaama** [comment]
The range of values is not 0 to 1.0, but rather 0 to 100. So you currently have it set to a 1% chance of conversion. Set it to 100 for a 100% chance.

**Comment by vitalyraif** [comment]
Where I can read about it?
The documentation says:
zombie-villager-infection-chance
default: -1.0

description: Sets the change for villager conversion to zombie villager Set to -1.0 for default behavior based on game difficulty Set to 0.0 to always have villagers die when killed by zombies Set to 1.0 to always convert villagers to zombie villagers.

It's from [here](https://paper.readthedocs.io/en/latest/server/configuration.html)

**Comment by amnotbananaama** [comment]
> Where I can read about it?
> The documentation says:

That documentation is incorrect. I checked [the patch’s code](https://github.com/PaperMC/Paper/blob/4cc7de6c51ea8dede78ce1d16a4ef583b0a5a01a/Spigot-Server-Patches/0421-Configurable-chance-of-villager-zombie-infection.patch#L39) and it’s configurable from 0 to 100. Either the documentation needs to be changed, or the patch needs to be changed to be brought in line with the documentation.

**Comment by vitalyraif** [comment]
Thank you. I"d like to close this issue, but the documentation is still wrong or the patch. So I leave the issue open.

**Comment by Chew** [comment]
Updated docs, see above commit. In the future, if there is an issue with the docs, report it on the docs repo @ https://github.com/PaperMC/PaperDocs.
