### ISSUE TITLE
Pillager AI issues 1.16.2

### ISSUE THREAD

**Issue by Inimbi** [PaperMC/Paper#4223]
![0CCF2E65-75CE-4252-BD38-65A033F9CB17](https://user-images.githubusercontent.com/61849880/91431041-b3872a00-e857-11ea-84cb-07170e3e7aa6.jpeg)

### What behaviour is expected:
___Expected normal pillager pathfinding.___

### What behaviour is observed:
___Pillager pathfinding to villagers not working ___

### Steps/models to reproduce:
___Start a raid or raid farm and notice how the pillagers do not move towards the main villager correctly. ___

### Plugin list:
___Core protect, anti X-ray, Vanilla tweaks (no pillager related tweaks except mob head drops)___

### Paper version:
___git-Paper-144___

![9C9AC7F8-D3E5-46B2-AA9C-1B9281B1CE56](https://user-images.githubusercontent.com/61849880/91433181-c64f2e00-e85a-11ea-855b-e57522210983.png)

### Anything else:
___This is a very recent update and although we are behind, we cannot see any fixes for this issue in any of the recent releases.___

**Comment by Chew** [comment]
While you may be right, you are still outdated. Please confirm on latest (149) as we updated upstream 3 times.

**Comment by Proximyst** [comment]
Pillager AI works just as expected. Please make an issue with more specific reproduction steps, as the ones provided make them work fine.

**Comment by Gaukh** [comment]
So, I am with Inimbi and we've tried it out on the current build 149
https://puu.sh/Gml7Y/138c9528d9.mp4

This is what it looks like

**Comment by Inimbi** [comment]
Please see video shared above showing the issue more clearly. This was taken after updating to the latest build.
