### ISSUE TITLE
Items despawn in unloaded chunks after 5 mins.

### ISSUE THREAD

**Issue by johncsuti** [PaperMC/Paper#4226]
### What behaviour is expected:
Items to remain on the ground after 5 min. if the chunk is unloaded.

### What behaviour is observed:
Items despawn after 5 mins. in the nether without any player inside the nether.

### Steps/models to reproduce:
Drop an item in the nether and tp very far away wait 5 min. tp back and your items are gone.

### Plugin list:
CraftBook, dynmap*, Essentials, EssentialsChat, Harbor, LuckPerms, LWC, PL-Hide, PluginApi, PreventPortBypass*, ProtocolLib, Vault, WorldEdit, WorldGuard

### Paper version:
[Server] INFO This server is running Paper version git-Paper-138 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[Server] INFO Previous version: git-Paper-110 (MC: 1.16.1)

### Anything else:
N/A

**Comment by Chew** [comment]
Are the items in a spawn chunk? Those are always loaded unless you turn it off.

**Comment by johncsuti** [comment]
Nope sorry for the late reply

**Comment by RgtArRr** [comment]
check 
spigot.yml
item-despawn-rate: 6000

paper.yml
alt-item-despawn-rate:

test without plugins

I tested with no plugins on build 138 and cannot b able to reproduce. even waiting too long

**Comment by Chew** [comment]
Also, you're 14 builds behind, can you please upgrade and reproduce?

**Comment by johncsuti** [comment]
@chew No im on the latest for 1.16.1
@RgtArRr i have checked but will check again

**Comment by me4502** [comment]
1.16.1 is no longer supported, are you able to please test whether this can be reproduced on 1.16.2?

**Comment by johncsuti** [comment]
i will have to test on .2
