### ISSUE TITLE
[1.16.2] items are disappearing when picked up

### ISSUE THREAD

**Issue by rrvk** [PaperMC/Paper#4227]
### What behaviour is expected:
To pick up 1 item of a stack of what is on the ground

### What behaviour is observed:
I pick up a whole stack but only 1 is added into my inventory because there is no more space and the other 63 are gone

### Steps/models to reproduce:
* fill your inventory with something, so all the spaces are filled (for example coal)
* then drop a couple of stacks of an other item on the ground (for example coal ore)
* make 1 space in your inventory (hotbar) so you can pick up items, you will pick up 1 whole stack
* then drop/place 1 item of the stack
* you will pick up a whole stack but only 1 item get added to your invetory because there is no more space then that and the other 63 items are lost

### Plugin list:
None

### Paper version:
This server is running Paper version git-Paper-149 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

### Anything else:
I have recreated this on a clean paper instal with no property changes

**Comment by calumari** [comment]
Confirmed in 150.

Iirc, this is the intended behaviour when picking up items in creative. However, it also happens in survival, which it shouldn't.

Video: https://streamable.com/r4rxce

Edit: It also happens upstream (git-Spigot-b5a13e6-bf45161) but not in vanilla.
Edit 2: Reported [upstream](https://hub.spigotmc.org/jira/browse/SPIGOT-6115).

**Comment by rrvk** [comment]
This now has been fixed upstream thanks for the report upstream @calumari 
and upstream with this fix has been merge into paper https://github.com/PaperMC/Paper/commit/757948dca3823a3a6f9fad0049459675b7cc073f 

I have tested this issue again on paper 152 and the issue is no longer there thanks!
