### ISSUE TITLE
Permission for bypassing Anti-Xray (Can be given to staff on the server) Feature Request

### ISSUE THREAD

**Issue by AZFire1** [PaperMC/Paper#4233]
**Is your feature request related to a problem? Please describe.**
With Paper's anti-xray it's kinda frustrating that when you (op) go into gmsp and try looking at players to make sure they aren't xraying/hacking it kinda get's in the way and if you are looking for a xrayer then you can't really tell either as for you it looks the same as the xrayer does instead of you being able to see the ores.

**Describe the solution you'd like**
It would be cool if ops bypassed it, or there could be a perm added which you could give staff so you could bypass the anti-xray.

**Describe alternatives you've considered**
To ignore it and live with it.

**Additional context**
None

**Comment by Proximyst** [comment]
This is being implemented by #4074. :)
