### ISSUE TITLE
Paper Inconsistent with Vanilla Spectator

### ISSUE THREAD

**Issue by LogGits** [PaperMC/Paper#4234]
### What behaviour is expected:
Hostile entities (that aren't named or passengers) should despawn when the player enters spectator unless a nonspectator player is nearby.

### What behaviour is observed:
Hostile entities (that aren't named or passengers) don't despawn when the player enters spectator mode even if all nearby players are spectator aswell.

### Steps/models to reproduce:
1, Only player on server (can test with multiple and still reproduce if all go into spectator)
2, Found a natural zombie spawner (works with skeletons aswell) or wait for night time
3, Wait for a few mobs to spawn
4, Go into spectator
5, Notice the entities are still there.

### Plugin list:
N/A

### Paper version:
1.16.2 build 148 (which was downloaded from build 152's download link on the CI)

### Additional Information:
I was outside spawn protection & spawn chunks (roughly 1000 blocks out from spawn) when testing.

**Comment by LogGits** [comment]
Update: appears to also happen on build 174. Here is a gif:
https://gyazo.com/86bffb665d841482d16967c8f3b50686
EDIT:
I was able to reproduce with:
- no plugins
- new paper 174 jar
- new world, world_nether, world_the_end
- new paper.yml, spigot.yml, bukkit.yml, server.properties
- new entirely new folder and generated files via paper 174 jar file.

Not too sure what could be causing it.

**Comment by uncovery** [comment]
can confirm, same here. "Mint" server setup. While mobs do not spawn when you are in spectator mode, they do not despawn when you enter spectator mode.

**Comment by LogGits** [comment]
In addition to this; crops still grow, withers still shoot. It's almost like the server **somewhat** thinks the client is and survival.

**Comment by LogGits** [comment]
Bumping because still occurs

**Comment by LogGits** [comment]
Still occuring just bumping to prevent closure.

**Comment by e-im** [comment]
Tested in 1.17.1 build 333, Paper behaviour matches vanilla's which is different from 1.16, with neither despawning in the way described. Feel free to leave a comment if you still see any differences regarding this.
