### ISSUE TITLE
add new startup parameters

### ISSUE THREAD

**Issue by TOWUK** [PaperMC/Paper#4237]
hi, I was able to put a custom directory for these files, is it possible to do this function for standard files?
![image](https://user-images.githubusercontent.com/28830162/91582333-5626d200-e958-11ea-83d1-b03c3d9215a6.png)
(**java -Xms6G -Xmx6G -jar paper.jar -org.spigotmc.netty.disabled=true -C SERVER/commands.yml -P PLUGINS -S SERVER/spigot.yml -W WORLDS -b SERVER/bukkit.yml -c SERVER.cfg --paper SERVER/paper.yml nogui**)

**Comment by Proximyst** [comment]
`java -jar paper.jar -h`

Perhaps. It'll say. Take this on Discord next time.

**Comment by TOWUK** [comment]
ok
