### ISSUE TITLE
Looks like my server's scoreboard is dead

### ISSUE THREAD

**Issue by LunaXena** [PaperMC/Paper#4239]
### What behaviour is expected:
___What you expected to see___
use command /scoreboard objectives setdisplays (list or sidebar) etc
then shows score like this
![Scoreboard](https://user-images.githubusercontent.com/70392673/91591366-cc96f480-e997-11ea-8373-7be68477db36.png)

### What behaviour is observed:
___What you actually saw___
It was ok in first day with 1.16.2 butkkit
But after a day. It's gone. 
When I used command it works perfectly but now is nothing

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___
afk, armored elytra, block locker, chat2go, chestsort, kakc, lasso, noteblock, openinv, saml, shopkeeper, skellet, skquery,
skript, ultimate timber, world edit, world guard
### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
I used #148 but after this bug I updated to 1.16.2 #152 but no help
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Chew** [comment]
So what's actually happening is there's no scoreboard?

**Comment by LunaXena** [comment]
yeah.. there's no scoreboard

**Comment by Chew** [comment]
Is this still happening on latest build? (b261)


v clicked wrong button, ignore please

**Comment by LunaXena** [comment]
No now my paper work perfectly
Thx alot!!!!

2020년 11월 5일 (목) 오전 2:44, Olivia <notifications@github.com>님이 작성:
