### ISSUE TITLE
1.16 Hex Colours not working in TextComponent

### ISSUE THREAD

**Issue by james-samios** [PaperMC/Paper#4240]
### What behaviour is expected:
When creating a TextComponent with 1.16 hex colours, it defaults to normal colours.

### What behaviour is observed:
bungee API chatcolour used, but when creating a textcomponent for a chat message, it defaults to nearest MC colour.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
AAC, AACPlus, ProtocolLib, TAB by Neznamy, custom core

### Paper version:
git-Paper-158

**Comment by JRoy** [comment]
You didn't provide any code that you've used, how do you expect anyone to help you?

**Comment by james-samios** [comment]
Here:

         TextComponent tc = new TextComponent(C.yellow + "⦿ ");
                        TextComponent rankNameHover = new TextComponent(Main.onlinePlayers.get(p).getPrefix(true) + displayName + C.white + ": ");
                        rankNameHover.setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder(C.white + "Title: " + ChatColor.translateAlternateColorCodes('&', db.getStaffPreferenceString(p.getUniqueId(), "title")) + C.white + "\nDepartment: " + ChatColor.translateAlternateColorCodes('&', db.getStaffPreferenceString(p.getUniqueId(), "department"))).create()));
                        tc.addExtra(rankNameHover);
                        tc.addExtra(ChatColor.valueOf(db.getPreferenceString(p.getUniqueId(), "chatColour").toUpperCase()) + finalFormat + e.getMessage());

**Comment by james-samios** [comment]
Seems to work with hex colours if broadcasting it or sending it through e.setFormat, so I think it's an issue with the TextComponent class itself.

**Comment by JRoy** [comment]
Pretty sure the `§x§r§r§g§g§b§b` format only works in legacy strings. When using Components you must use the actual color builder.

**Comment by james-samios** [comment]
Ok, that seems to be the issue. Thanks.
