### ISSUE TITLE
Pistons explode rather than extend against warped fungus?

### ISSUE THREAD

**Issue by surfrock66** [PaperMC/Paper#4253]
### What behaviour is expected:
A piston, against a warped fungus, should extend and pop the fungus off.

### What behaviour is observed:
A piston, against a warped fungus, explodes rather than extends.  

### Steps/models to reproduce:
Three videos to demonstrate; 
The bug: https://gfycat.com/sizzlingsimilarcowbird
In our "Creative" zone, isolated, the bug doesn't happen: https://gfycat.com/densecalculatinggalapagosmockingbird
In single player, the bug does not happen, but when signing into our PaperMC server it does: https://gfycat.com/saneskeletalbeardeddragon
This is a build based on this video: https://www.youtube.com/watch?v=YiM7NOkJUwA&list=WL&index=2

### Plugin list:
EssentialsX (Base, AntiBuild, Chat, GeoIP, Protect, Spawn) Dynmap, GriefPrevention, JDynmapGriefPrevention, LuckPerms, Multiverse-Core, Multiverse-SignPortals, Vault

### Paper version:
Paper version git-Paper-168 (MC: 1.16.2) Implementing API version 1.16.2-R0.1-SNAPSHOT

### Anything else:
I'll continue testing to find the exact situation this happens in, I'm not sure what about the arrangement of the farm makes this happen.

**Comment by Proximyst** [comment]
Reproduce without plugins.

**Comment by Chew** [comment]
99% likely a bug with GreifPrevention

**Comment by surfrock66** [comment]
Further testing, Only happens when piston is facing South.  Disabling GriefPrevention fixes it.  I'll submit a bug there, thanks!
