### ISSUE TITLE
Server Crashing Unexpectedly

### ISSUE THREAD

**Issue by dotxzxc** [PaperMC/Paper#4254]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

**Comment by Prof-Bloodstone** [comment]
You provided literally 0 information...
Please provide information from the template.

**Comment by Saraistupid** [comment]
ah yes, issue
