### ISSUE TITLE
Server Crashing Unexpectedly

### ISSUE THREAD

**Issue by dotxzxc** [PaperMC/Paper#4256]
**Description of issue:**
Hello. So my server is crashing and I can't figure out why. I'll go to sleep at night and in the morning get on the network and the server is down. Thoughts?

bukkit.yml, spigot.yml, paper.yml, server.properties
Bukkit - https://pastebin.com/ZLidBjii
Spigot - https://pastebin.com/Pafgkwai
Paper - https://pastebin.com/b7s3hKZF
Server - https://pastebin.com/eN5REg18

**Crash, Stacktrace**
https://pastebin.com/DYe5traM

Plugin list:
https://pastebin.com/raw/vuqee5N3

**Paper build number:**
This server is running Paper version git-Paper-169 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Your server took too long to tick, for support, please use the discord
