### ISSUE TITLE
API method for determining whether an entity is ticking

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4257]
**Is your feature request related to a problem? Please describe.**
I would like to be able to see which entities are ticking and which are not. I am aware that paper entity list does this but I would like this to be achievable via the API

**Describe the solution you'd like**
An entity.isActivated()/entity.isTicking() flag or a chunk.isTicking() flag.

**Describe alternatives you've considered**
Using NMS for it

**Comment by RgtArRr** [comment]
I guess EntityLiving.hasAI() can be an option?
If you do .setAI(false); the entity wont do anything, even gravity do not apply
