### ISSUE TITLE
ERROR Spigot error when saving item meta

### ISSUE THREAD

**Issue by Klawdek** [PaperMC/Paper#4261]
### What behaviour is expected:
___What you expected to see___

### What behaviour is observed:
___What you actually saw___

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
The following error occurs in the console.  No players on server nothing is done to trigger it.  It just happens spontaneously. 
https://pastebin.pl/view/8bdbfb2c
I have also reported this to the spigot site.

### Plugin list:
___A list of your plugins___
Plugins (49): AreaShop, ArmorStandTools, BottledExp, ChestShop, Citizens, CitizensCMD, CraftBook, CrateReloaded, CrazyAuctions, CrazyEnchantments, DeluxeMenus, Denizen, Depenizen, DiscordSRV, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsSpawn, EZRanksPro, HolographicDisplays, Jobs, LibsDisguises, LWC, mcMMO, MineableSpawners, Minepacks, MobArena, Multiverse-Core, Multiverse-Portals, Multiverse-SignPortals, MythicMobs, ParticleHats, PhatLoots, PlaceholderAPI, PlayerParticles, ProtocolLib, Quests, RandomTeleport, Shop, Towny, TownyGUI, TownyNameUpdater, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, zPermissions
### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
git-Paper-387 (MC: 1.15.2)
I had originally put wrong version as I copied the previous version text sorry.
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Chew** [comment]
Can you link the Spigot issue so we can track this?

**Comment by Klawdek** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-6119?jql=
they seem to feel it is a paper problem.

**Comment by Draycia** [comment]
They never said that. They said they don't support forks. 

It's not a matter of whose fault it is, it's a matter of principle. Issues when using paper get reported to paper.

If you can reproduce on spigot 1.16.2, it would then be valid to report to spigot.
