### ISSUE TITLE
Paper-159 Light java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by radiant-ai** [PaperMC/Paper#4262]
### Link/paste of stack trace
https://pastebin.com/zXtASuJ8

### Plugin list:
AntiAFKPlus, AuthMe, BetterRTP, ChatControl, CMI, CMIEInjector*, CMIPaperLib, CoreProtect, CrazyAuctions, EzClans, FarmLimiter, HackedCore*, HackedServer*, HeadDatabase*, IronFarmLimiter, LagAssist, LimitPillagers, LuckPerms, Marriage, PlaceholderAPI, ProtocolLib, PvPManager, SAML, SkinsRestorer, Spartan, TAB, TimeIsMoney*, Vault, VillagerOptimiser, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, XProtect*

### Actions to reproduce (if known):
Happened only once overnight. I tried to reproduce using the region file and getting into the referring chunk, but nothing happened.

### Paper version:
git-Paper-159 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by radiant-ai** [comment]
Did not occur again for 3 weeks

**Comment by aikar** [comment]
Was actually fixed today proper
