### ISSUE TITLE
Nether portal not working at it shoud be in vanila

### ISSUE THREAD

**Issue by DarrenOfficial** [PaperMC/Paper#4266]
Paper 170 - 1.16.2

### What behaviour is expected:
When i enter nether portal, and when i go back it shoud go to the same portalthat i enter in

### What behaviour is observed:
when i enter nether portal it work, but when i go back it randomly created a portal far from the original portal

### Steps/models to reproduce:
Blank Server, running paper 170 make a nether portal

### Plugin list:
Skinrestorer

### Paper version:

01.09 06:56:08 [Server] INFO This server is running Paper version git-Paper-170 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
01.09 06:56:08 [Server] INFO Checking version, please wait...
01.09 06:56:09 [Server] INFO Previous version: git-Paper-160 (MC: 1.16.2)
01.09 06:56:09 [Server] INFO You are 4 version(s) behind

### Anything else:
I dont know

**Comment by rrvk** [comment]
What are the cords of the portal in the overworld and in the nether. 
Because what you expecting is not always true

**Comment by MrIvanPlays** [comment]
vanilla issue

**Comment by Chew** [comment]
Got a Mojira link @MrIvanPlays ?

**Comment by MrIvanPlays** [comment]
forgot it but a quick google search should pop it right away. basically they were describing the same behavior: create a portal, get inside, then return and a new portal was created.

**Comment by Chew** [comment]
To test this reliably, it would have to start on vanilla, then Paper. There's too many variables to pinpoint on Paper being the issue unless the variables are the exact same.

**Comment by MrIvanPlays** [comment]
yeah paper adds configurable portal search & create ranges, which by default are vanilla ones. so if darren had changed those values, it may occur too, but i remember this being a vanilla issue.

**Comment by chickeneer** [comment]
[MC-149705](https://bugs.mojang.com/browse/MC-149705) is one example of the Minecraft issue.
Definitely is a vanilla issue that has essentially always existed.

**Comment by malonnnn** [comment]
Related? https://hub.spigotmc.org/jira/browse/SPIGOT-6099

**Comment by Chew** [comment]
Build 170 would've had this change.
