### ISSUE TITLE
1.16.2 paper crash what happened in my server

### ISSUE THREAD

**Issue by kevinwang-0916** [PaperMC/Paper#4267]
Link/paste of stack trace
The actual crash:https://paste.gg/p/anonymous/1c1795d7d3af46ca89523b99513df3d2

Plugin list:
AAC, AntiAFKPlus, AuctionGUIPlus, AutoAnnouncer*, AutoRestart*, BungeeGuard, ChestCommands, ChestSort, Citizens, CoreProtect, CubCustomDrops, CustomJoinItems*, DiscordSRV, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, GroupManager, HolographicDisplays, KillerMoney*, LockettePro, Lottery, MobFarmManager, MOTD, Multiverse-Core, NoPlugins, OpenInv, PlaceholderAPI, ProtocolLib, QuickShop, Residence, SAML, Shopkeepers, TAB, TempFly, TradeUI, Vault, VillagerOptimiser, WorldEdit, WorldGuard, zAuctionHouseV2 (42)

Actions to reproduce (if known):
I really don't know.

Paper build number:
Paper-174（MC：1.16.2）

**Comment by Proximyst** [comment]
20 results for "DO NOT REPORT THIS TO PAPER".

You've got a player zooming about; take a stop by our Discord server's `#paper-help` for help with your issue.

**Comment by aikar** [comment]
Please try https://github.com/PaperMC/Paper/pull/4210 and report findings on #paper-test-builds on discord.

This test build is aimed to solve this issue.
