### ISSUE TITLE
Zombie#setShouldBurnInDay does not work

### ISSUE THREAD

**Issue by scrayos** [PaperMC/Paper#4268]
### What behaviour is expected:
I expect the zombie, that was flagged with Zombie#setShouldBurnInDay(false) to not burn in daylight.

### What behaviour is observed:
The zombie burns nevertheless.

### Steps/models to reproduce:
* Spawn a zombie with something like this: `Zombie en = world.spawn(location, Zombie.class);`
* Set "shouldBurnInDay" to false like this: ` en.setShouldBurnInDay(false);`
* Still see it burning

### Plugin list:
Only the test plugin, containing only this functionality

### Paper version:
This server is running Paper version git-Paper-174 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

### Anything else:
I already looked into the code and saw the obvious reason for the behaviour observed in the EntityZombie.class:
```java
    public boolean shouldBurnInDay() {
        return this.T_();
    }

    protected boolean T_() {
        return true;
    }

    public void setShouldBurnInDay(boolean shouldBurnInDay) {
        this.shouldBurnInDay = shouldBurnInDay;
    }
```

I also checked if this was somehow noted in the JavaDoc through for example deprecating the method, but this is not the case: https://papermc.io/javadocs/paper/1.16/org/bukkit/entity/Zombie.html#setShouldBurnInDay-boolean-

Thanks for looking into this!

**Comment by MrIvanPlays** [comment]
this is an easy fix, just open a pr and aikar will prob merge it right away

**Comment by scrayos** [comment]
I was thinking about it, you've convinced me. Will do.
