### ISSUE TITLE
Vanilla WorldGen Lakes Deadlock

### ISSUE THREAD

**Issue by aikar** [PaperMC/Paper#4272]
Vanilla appears to have a Deadlock risk here.

Lakes are looking for a structure, but structure escapes out of the RegionLimited world wrapper
This then hit some chunk that is still pending, but since main is blocked, itll never be not pending.

Full log from Zeffy here: https://paste.gg/p/anonymous/77db790e273446b3bedb58123725b337
```

[02:43:57] [Paper Watchdog Thread/ERROR]: ------------------------------
--
  | [02:43:57] [Paper Watchdog Thread/ERROR]: Current Thread: Server-Worker-2
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 	PID: 17 \| Suspended: false \| Native: false \| State: WAITING
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 	Stack:
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:476)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.World.getChunkAt(World.java:356)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.IWorldReader.getChunkAt(IWorldReader.java:100)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.StructureManager.a(StructureManager.java:27)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:2184)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.RegionLimitedWorldAccess.a(RegionLimitedWorldAccess.java:382)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldGenLakes.a(SourceFile:36)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldGenLakes.generate(SourceFile:18)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldGenFeatureConfigured.a(SourceFile:55)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldGenFeatureComposite.a(SourceFile:23)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldGenFeatureComposite$$Lambda$5582/1099215437.accept(Unknown Source)
  | [02:43:57] [Paper Watchdog Thread/ERROR]: 		java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)


```

**Comment by Zefferis** [comment]
I'd like to honor and credit our lovely server player **_Rachel_** for being the poor unfortunate soul that discovered this and promptly got kicked.

**Comment by aikar** [comment]
RegionLimitedWorldAccess is at fault here:
    public Stream<? extends StructureStart<?>> a(SectionPosition sectionposition, StructureGenerator<?> structuregenerator) {
        return this.f.a(sectionposition, structuregenerator);


Needs to be 

this.f.getStructureManager().a(this).a(sectionposition, structuregenerator);

That .a(this) converts the StructureManager to use a RLWA object instead.

**Comment by MrIvanPlays** [comment]
how about we nuke that stream entirely?

**Comment by aikar** [comment]
no

**Comment by MrIvanPlays** [comment]
bruh then we start recommending graalvm cuz they took a shit on them and made them F A S T

**Comment by Proximyst** [comment]
No. GraalVM isn't a topic anyone in Paper is very experienced with, and is as such not recommended. The same applies to ZGC, Shenandoah, OpenJ9 and so forth.

You're free to PR a stream removal after the bug is fixed if it really makes any difference whatsoever in what is already a slow process.

**Comment by aikar** [comment]
just going to note we will not accept a PR to remove streams here. Not rewriting WorldGen code, specially when its not even a main thread bottleneck.

Streams are ok in some cases, it depends how they are used. If it's not hot code, then the logical capabilities it has can end up being a performance increase. It's all very situational.

Let's end stream discussion here.

**Comment by MiniDigger** [comment]
vanilla ticket: https://bugs.mojang.com/browse/MC-199487
