### ISSUE TITLE
Ban lists expire checks waste resources on banned player join attempt

### ISSUE THREAD

**Issue by Shevchik** [PaperMC/Paper#4274]
Currently BanList does a full list iteration in order to remove expired ban entries on BanList#get. Currently login listener checks BanList#isBanned first, which doesn't trigger that check, so non banned players don't trigger this, so if you don't use vanilla ban system, you won't notice this, but if you do, constant banned players join attempt can make server waste resources on this.

The proposed change is to move banlist entries expire task to server stop/start instead. I will attempt to provide a PR later if i have the time.

**Comment by Proximyst** [comment]
An alternative could be something as easy as a lock, or just run it as you said, plus check for expiry on a banned player's login.

**Comment by Shevchik** [comment]
Expire date is already checked on player login, done just after getting the entry.

**Comment by Machine-Maker** [comment]
correct me if I'm wrong, but doesn't 6ef9abeec2fc9be9d2467c1950cfe9d5bf4260e7 fix this?
