### ISSUE TITLE
Custom payload error 1.16.2 paper-179

### ISSUE THREAD

**Issue by CypherPhyre** [PaperMC/Paper#4280]
### What behaviour is expected:
___What you expected to see___
Able to join server
### What behaviour is observed:
___What you actually saw___
Get kicked on join with error: Couldn't dispatch custom payload
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Attempt to join server
### Plugin list:
___A list of your plugins___
https://pastebin.com/PpC0xvBq
### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
[05:20:35] [Server thread/INFO]: CMI: 8.7.6.11 MySQL
[05:20:35] [Server thread/INFO]: Server: Paper(179) 1.16.2-R0.1-SNAPSHOT
[05:20:35] [Server thread/INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True 
[05:20:35] [Server thread/INFO]: Modules -> 52 enabled 0 disabled: 
### Anything else:
___Anything else you think may help us resolve the problem___
https://pastebin.com/Hws4mvdn

**Comment by CypherPhyre** [comment]
Reverted server back to paper-174. Players are able to join without errors.

**Comment by Chew** [comment]
Are they joining with a custom client (e.g. forge or fabric)

**Comment by CypherPhyre** [comment]
I tested this on a vanilla client and it still happens. I am unsure what other players try to join on.

**Comment by electronicboy** [comment]
Can you replicate this without plugins?
I fail to understand why so many servers are having issues parsing a well defined message from the client, especially as it works for 99.999% of everybody else...

**Comment by CypherPhyre** [comment]
The issue remains with paper-182. Without any plugins I can join without any error.

**Comment by yannicklamprecht** [comment]
Then search for the plugin that is causing the issue.
