### ISSUE TITLE
Add a way to disable thread dumps when the server isnt responding

### ISSUE THREAD

**Issue by cyberpwnn** [PaperMC/Paper#4282]
I kind of expected this to be in the config somewhere. Am I missing it? I'm running experiments which use a lot of memory, threads, and I'm relying on the console for diagnostics. I'm very aware that the server is not ticking nor has it ticked for X amount of seconds or minutes. That doesnt mean I need to see a dump of chunk tickets & the serve rthread every 5 seconds. 

Is there any way I can disable this so my console buffer is useful again?

**Comment by Proximyst** [comment]
Pass `-Ddisable.watchdog=true`.

**Comment by aikar** [comment]
You're looking for the 
  watchdog:
    early-warning-every: 5000
    early-warning-delay: 1000


in paper.yml, set these to higher values or 0 should disable.
Id recommend maybe just bumping it to delay: 15000 instead and every: 10000 to make it take longer before it engages and spams less, but note this offers us less context on WHY it's hung and can impact your support for issues.
