### ISSUE TITLE
Players being kicked using shulkers filled with books

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4283]
### What behaviour is expected:
A player not being kicked when they click on a book shulker.

### What behaviour is observed:
Player kicked with message: `Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/1 (PacketPlayInTileNBTQuery) was larger than I expected, found 128343 bytes extra whilst reading packet 1` or `Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 66`

### Steps/models to reproduce:
The Shulker in YAML form: https://pastebin.com/8mSeETGa video of the bug: https://youtu.be/h64XeCfbko8

### Paper version:
git-Paper-182 (MC: 1.16.2)

**Comment by MrIvanPlays** [comment]
book banning has been known for ages now. it is a vanilla issue

**Comment by broken1arrow** [comment]
> 
> 
> book banning has been known for ages now. it is a vanilla issue

But paper has counter ageist this, you can see in the paper.yml. You can limit pages and i think even size.

And even chunk saving is much better an vanilla (you cant overload a chunk soo easy). But i guess in this chase is player inventory bug?

**Comment by MrIvanPlays** [comment]
limiting the pages cant rly stop it entirely.
its not an inventory bug. 
 
the chunk dupe which worked with overloading the chunk has been first fixed by paper in 1.12 and mojang followed and fixed it in 1.15

**Comment by broken1arrow** [comment]
> 
> 
> limiting the pages cant rly stop it entirely.
> its not an inventory bug.
> 
> the chunk dupe which worked with overloading the chunk has been first fixed by paper in 1.12 and mojang followed and fixed it in 1.15

I understand that. but player can login again? if it only because he open the skulker box? or get the chunk impossible too load?

I think if one box of book cause it you can limit this effects in the settings (harder if players fill hole chunk of skulker boxes or chest).

**Comment by MrIvanPlays** [comment]
no thats not chunk banning. 
see https://youtu.be/_7f6DojmoWE

**Comment by broken1arrow** [comment]
> 
> 
> no thats not chunk banning.
> see https://youtu.be/_7f6DojmoWE

I have see this before :) That you show has the player 3 skulkers of books inventory already. Soo when you update  inventory you get kick out (so not depending what you open). 

So you get the inventory locked and only he some access to serverfiles can fix it.

I don know how to solve it properly, i think two ways either limit amount of symbols (can bee done in several ways, like limit how many each page or hole book) or increasing how much data every chunk saving.

**Comment by electronicboy** [comment]
> Packet 0/1 (PacketPlayInTileNBTQuery) was larger than I expected, found 128343 bytes extra whilst reading packet

Not a book ban, something mangled a packet; Replicate without plugins
