### ISSUE TITLE
Tps low help (In 1.16.2)

### ISSUE THREAD

**Issue by FranckJohann** [PaperMC/Paper#4286]
My tps was between 15/18 with 50 players, now with 1.16.2 it is between 5/10 with 30 players. can you help me? Below are some links with information.

Spigot.yml: https://pastebin.com/BvSrvdBr
Bukkit.yml: https://pastebin.com/Kw8vCAHc
Paper.yml: https://pastebin.com/2Ukbfm6s
Timings: https://timings.aikar.co/?id=52ae9084709c438d83c7472cec90b1c9
Timings: https://timings.aikar.co/?id=2f1864cbf7c444e5b8e87dc6ddeecae0

Paper: Paper-1.16.2-b179.jar
Plugins (71): AdvancedBan*, AngelChest, AntiAFKPlus, AntiWorldFly, ArtMap, BlockLocker, BloodManager, BottledExp, BungeeGuard, ChatControl, ChestShop, Citizens, CitizensCMD, CitizensServerSelector, ClearLag, CmdWhiteList*, ColorMOTD*, CombatLogX, CommandPrompter, CoreProtect, CS-CoreLib, CubCustomDrops, DeathCoordinates, DeluxeMenus, DinoVoteRewards*, EditableSign, Elevator, EntityTrackerFixer, EpicRename, Essentials, EssentialsSpawn, ezAuctions, FogusCore, GoldenCrates, GreatKits*, GroupManager, HeadDatabase*, HealthBar*, HideAchievements*, HomeGUI, IllegalStack, JoinText*, Marriage, MermaidPlus, MultiWorld*, MyCommand, NoRainReloaded*, OpenInv, PacketLimiter, PlaceholderAPI, PlayerHeads, PlayerParticles, PluginConstructorAPI, PosePlugin, ProtocolLib, SilkSpawners, SkinsRestorer, TAB, Towny, TownyChat, TownyFix*, TownyTitle*, UberEnchant, Vault, VipSystem, Votifier, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, Zenchantments

**Comment by electronicboy** [comment]
Please use discord for support with timings
