### ISSUE TITLE
BiomeGrid#setBiome() does not affect Vanilla decoration population. (SPIGOT-5880)

### ISSUE THREAD

**Issue by dfsek** [PaperMC/Paper#4287]
Note that this is on the fine line between a bug and a feature request. Due to the undefined nature of the behavior, I am submitting it as a bug.

### What behaviour is expected:
When BiomeGrid#setBiome is used during generation with Decorations/Structures enabled in the generator, the decorations corresponding to the _new_ biome should be generated.

### What behaviour is observed:
When BiomeGrid#setBiome is used during generation with Decorations/Structures enabled in the generator, the decorations corresponding to the _original_ biome are generated.

### Steps/models to reproduce:
1. Make a world generator that sets biome during the generation phase
2. Load the world generator
3. Observe structures and decorations generating where they are not supposed to.

### Plugin list:
[TestGenerator](https://github.com/PolyhedralDev/test-generator-1) - Quick and simple generator I made to demonstrate the issue. Use it in an End world. It gets the original biome, and if the biome is `small_end_islands` it sets Y=0 to stone. Then, it changes the biome everywhere to `end_highlands`. In theory, this means that the small end islands would never generate, since they only generate in `small_end_islands` biomes, yet they continue to generate in the areas that *used* to be `small_end_islands`.

### Paper version:
git-Paper-184 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

### Anything else:
This issue does not seem to be present in Paper 1.15, but is present in Spigot 1.15. Due to the undefined behaviour, I believe that it would be classified as a bug.
[SPIGOT-5880](https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-5880)

**Comment by Chew** [comment]
Are you saying the bug is in the current PAPER 1.16.2 version you are using? I can't understand what you mean by the bit at the end

**Comment by dfsek** [comment]
Issue is present in both Paper and Spigot 1.16.1/2. 

Issue is **not** present in Paper 1.15.2, but **is** present in Spigot 1.15.2

**Comment by Chew** [comment]
Ah, good to know
