### ISSUE TITLE
server crashed due to somebody exchange glass_pane with villager

### ISSUE THREAD

**Issue by mrjesen** [PaperMC/Paper#4289]
### Link/paste of stack trace
https://paste.gg/p/anonymous/c2f53fa61fcc4d9fabf97a0d1eaa2023

### Actions to reproduce (if known):
somebody exchange glass_pane with villager

### Paper version:
This server is running Paper version git-Paper-184 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by Proximyst** [comment]
Duplicate of #2312.
