### ISSUE TITLE
The server has not responded for 160 seconds! Creating thread dump

### ISSUE THREAD

**Issue by DahunDev** [PaperMC/Paper#4290]
### Description of issue:
Server Stopped

https://pastebin.com/7WXxwc6b

### Paper version:

This server is running Paper version git-Paper-1618 (MC: 1.12.2)

**Comment by Octol1ttle** [comment]
This is a Watchdog message
For help, go on IRC or Discord
Also 1.12.2 is unsupported

**Comment by Proximyst** [comment]
Unsupported version. Two *hundred* and seventy four results of "DO NOT REPORT THIS TO PAPER".

If you want help, reproduce on 1.16.2 or 1.15.2 and ask in `#paper-help`.
