### ISSUE TITLE
Problem with Motion

### ISSUE THREAD

**Issue by Militalex** [PaperMC/Paper#4292]
### What behaviour is expected:
![paper-183](https://user-images.githubusercontent.com/69317314/92309190-abd82b80-efa3-11ea-9636-08759b2374d5.png)
paper-183

### What behaviour is observed:
![paper-184](https://user-images.githubusercontent.com/69317314/92309193-ae3a8580-efa3-11ea-9c21-a196f29cfbfc.png)
paper-184

Since Paper 184 it is not possible to spawn Entities with Motion.

### Steps/models to reproduce:
/summon falling_block ~ ~ ~ {BlockState:{Name:"minecraft:lapis_block"},Time:1,DropItem:0b,HurtEntities:0b,Motion:[-0.4,1.0,-0.4]}

### Plugin list:
LuckPerms-Bukkit-5.1.93.jar
PlugMan.jar

### Paper version:
This server is running Paper version git-Paper-184 (MC:1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT) Checking version, please wait...
Previous version: git-Paper-152 (MC: 1.16.2) You are running the latest version

**Comment by chickeneer** [comment]
Related to #4210.

**Comment by ghost** [comment]
Got this problem too since build #184 (1.16.2)
Actually on: build #191 (1.16.3)

**Comment by ikuria** [comment]
pls fix that issue - we need motion!

**Comment by aikar** [comment]
1.16.2 is now end of life, so if you for some reason can't update to 1.16.3 you will have to go back to 183 instead.

Def would be caused by that change, so will look at getting it fixed.

**Comment by ghost** [comment]
We are on build #191 (1.16.3) as i said.
The issue is still present in this build.

**Comment by aikar** [comment]
yes we have not fixed it yet hence this being open still. I was just commenting that 1.16.2 will not receive the fix, so you have to update to 1.16.3 to get it fixed once the fix lands.

**Comment by ikuria** [comment]
update is running on 1.16.3, i'm just waiting for the fix - we have motion in one game we want to open in 2 hours,... not a good timing, so sad we have to close this game for maintenence

**Comment by electronicboy** [comment]
We really don't need the pointless bumps on this ticket, it's a known issue and will be fixed when somebody can get to it, your timeframes are 100% irrelevant to us; You're more than welcome to revert the offending commit yourself
