### ISSUE TITLE
server keep crash and sometime windows 10 downed

### ISSUE THREAD

**Issue by darksoldier1404** [PaperMC/Paper#4293]
### Link/paste of stack trace
https://pastebin.pl/view/5d1057f6
    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
server crash before load plugin
i think...
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

1.16.2 paper-184

**Comment by electronicboy** [comment]
> and sometime windows 10 downed

This, combined with the random characters here from your dump:

> Time: Sun Sep 06 03:49:37 2020 ´eCN¹I±¹ C￥AØ½A elapsed time: 17 seconds (0d 0h 0m 17s)

Suggests that either your system is busted, software or hardware level 🤷 

The actual crash is caused by a memory access violation, which is generally JVM level, not caused by the software running in it

**Comment by darksoldier1404** [comment]
i see
thank you!
