### ISSUE TITLE
Torch lighting glitch: Suddenly some light sources only illuminate 1x1 block

### ISSUE THREAD

**Issue by mtoensing** [PaperMC/Paper#4294]
### What behaviour is expected:
![image](https://user-images.githubusercontent.com/136737/92313352-0638b280-efcb-11ea-947e-bf17f340a663.png)

### What behaviour is observed:
![image](https://user-images.githubusercontent.com/136737/92313353-0a64d000-efcb-11ea-857d-35da705cacdc.png)

### Steps/models to reproduce:
Suddenly wide areas on my map appear to be broken or glitched. Some light sources only illuminate 1x1 block. I can fix this if I place a new light source and the lighting seems to reset itself. This even appears on my overviewer render:

![image](https://user-images.githubusercontent.com/136737/92313372-629bd200-efcb-11ea-844c-1434bd7a4b86.png)
Source: https://mc.marc.tv/iso

### Plugin list:
none.

### Paper version:
I am on 1.16.2 Paper-184

### Anything else:
I found this only in 1.14: This seems to be related: #1542 and this sound similar: https://www.reddit.com/r/Minecraft/comments/biveqo/114_lighting_glitch/ 

I attached a region file with this problem: 
[r.-1.-2.mca.zip](https://github.com/PaperMC/Paper/files/5178665/r.-1.-2.mca.zip)

My paper.yml 
[paper.yml.zip](https://github.com/PaperMC/Paper/files/5178676/paper.yml.zip)

I updated from 1.16.1 to 1.16.2 after the official version. I never used unstable paper releases on my map.

**Comment by MrIvanPlays** [comment]
until a proper fix is rolled out, /paper fixlight so you dont go everywhere and replace stuff

**Comment by HauserGrim** [comment]
+1
Lighting breaks in some chunks.
I haven't tried to reproduce the issue, but it looks like the screenshot.

**Comment by mtoensing** [comment]
Any news if this is a Paper bug or not?

**Comment by Chew** [comment]
Needs to be reproduced upstream to deduce that

**Comment by e-im** [comment]
This should be fixed as of merging with tuinity. If you are still experiencing this on 1.17.1, leave a comment. Additionally, if you do experience this, you can use the  `/paper fixlight` which is also now improved.
