### ISSUE TITLE
No tick view distance

### ISSUE THREAD

**Issue by BlazeX9** [PaperMC/Paper#4297]
When i am setting no tick view distance from -1 to 10, memory is acting weirdly it keep getting filled faster and after 3-4 hrs its crashing due to lack of memory! also i am having tps drops can you suggest how can i improve have attached timings reports - https://timings.aikar.co/?id=95486b4993024076b5f8ae4410d7086b#timings

**Comment by Proximyst** [comment]
You're told to fix major memory issues with the "FIX THIS" link.

For actual help with this, join our Discord's `#paper-help` channel.
