### ISSUE TITLE
World gen'd brown & red mushrooms do not drop when broken

### ISSUE THREAD

**Issue by drewhannay** [PaperMC/Paper#4298]
### What behaviour is expected:
Brown & red mushrooms broken by a player drop themselves as an item.

### What behaviour is observed:
Nothing is dropped.

### Steps/models to reproduce:
Find a naturally spawned red or brown mushroom in the overworld and break it with a fist or any item in hand. Mushrooms DO seem to drop properly in the nether, it's only in the overworld that I observed this issue.

### Plugin list:
None

### Paper version:
This server is running Paper version git-Paper-185 (MC: 1.16.2) (Implementing API version 1.16.2-R0-1.SNAPSHOT)

### Anything else:
Mushrooms placed by the player DO drop themselves, it's only naturally spawned mushrooms that do not drop

**Comment by Chew** [comment]
Can't reproduce on brand new Paper 1.16.3, did you upgrade your world? I got really unlucky and it took me many blocks until I finally got one, but I still did.

**Comment by drewhannay** [comment]
I was using a brand new world, no upgrade.

I just tried again with Paper-195 on 1.16.3 and I can still repro the issue. I maybe have some more info though. I think the issue only happens when a world gen mushroom has spawned in a location where the light level is too high for a mushroom to exist.

My test world is seed `-8522085790011288553`, using all default options (just started the paper jar directly).
You can find some brown mushrooms at `-1546, 64, -1113`.  The mushroom at `-1549,-1112` has a light level of 12 and the mushroom is dropped as an item when broken. The mushroom at  `-1546, -1111` has a light level of 14 and does NOT drop when broken.

**Comment by Chew** [comment]
Ohh I see how you mean, I thought you meant the roofed forest giant mushrooms. I reproduced the wrong thing then

**Comment by Proximyst** [comment]
Reproducible on Paper 1.16.3 b206. This is not an issue in vanilla; I've not checked on Spigot/CB.

**Comment by szikra** [comment]
I did some testing and I think they are "ghost mushrooms" that don't exist.
When you walk into an swamp area the first time you can see a lot of mushrooms, if you try to pick them they drop nothing.
And also if you disconnect instead (without picking them) and reconnect then they are no longer there.
You don't even need to disconnect you can just tp away and tp back (so the server unloads and reloads the chunks) and the mushrooms disappear. (not all of them, but most of them)

I deleted and recreated the server with the same seed many times to test this.
I also loaded my server world into single player and I created a new world with the same seed and there I can collect all the mushrooms I see fine but a lot of the mushroom shown by the server at first are not there at all.

There might be a problem with mushroom generation, or to be more precise a problem with filtering them in the wrong order (sending them to the client first, then filtering out the non viable ones which would lead to them not being saved and shown on the reload... but this is just a guess)
