### ISSUE TITLE
TNT Not Dropping Items

### ISSUE THREAD

**Issue by RocketManKian** [PaperMC/Paper#4302]
### What behaviour is expected:
I expect blocks to drop whenever I blow things up using TNT.

### What behaviour is observed:
When blowing up blocks with TNT nothing dropped, and I only used one TNT. So it's impossible for another piece of TNT to destroy the dropped items.

### Steps/models to reproduce:
[video.zip](https://github.com/PaperMC/Paper/files/5183578/video.zip)

### Plugin list:
ChatControl
CmdSigns
ColouredSigns
CommandSigns
DiscordSRV
Essentials
FastAsyncWorldEdit
GriefPrevention
Harbor
InteractiveChat
JoinMessagePlus
LitePlaytimeRewards
LuckPerms
PlaceholderAPI
ProtocolLib
SecuredNetwork
TAB
TradeShop
Vault
WorldGuard

### Paper version:
">> = [14:45:16 INFO]: This server is running Paper version git-Paper-185 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[14:45:16 INFO]: Checking version, please wait...
[14:45:17 INFO]: Previous version: git-Paper-163 (MC: 1.16.2)
[14:45:17 INFO]: You are running the latest version"

### Anything else:
N/A

**Comment by Octol1ttle** [comment]
Try without any plugins

**Comment by RocketManKian** [comment]
I have tried without no plugins and it just seems like with plugins, or without, there is just a chance whether the TNT will drop blocks or not. It's like a percentage chance it seems, sometimes it works, sometimes it doesn't. Very strange.

**Comment by Chew** [comment]
Can't seem to reproduce this on a brand new Paper 1.16.2 b186 server. I blew up sand several times and got all my items.
