### ISSUE TITLE
Colored Rendering of Players is only white

### ISSUE THREAD

**Issue by CloudeLecaw** [PaperMC/Paper#4303]
Plugins like CMI have a command to Render players in a colored shap around them.

![image](https://user-images.githubusercontent.com/12080017/92401018-27191900-f12d-11ea-84b6-74704c478b8a.png)

![image](https://user-images.githubusercontent.com/12080017/92400914-f507b700-f12c-11ea-9553-7d370c88c64f.png)

If you try the same with PaperMC the result is that the glow shap apears. but there is no way to color it. it just stays white no matter what color you choose

![image](https://user-images.githubusercontent.com/12080017/92401018-27191900-f12d-11ea-84b6-74704c478b8a.png)

**Comment by Octol1ttle** [comment]
You didn't show that with Paper the glow is white, on both screenshots the glow is dark purple
It also might be an issue with CMI

**Comment by CloudeLecaw** [comment]
hm i tested this with the last version of Paper and now it seems to work.. well at home i will do a bit deeper test to see what is blocking the coloring there. (may its also fixed there with the 185...) i will reply later and reopen ticket if i have any news

**Comment by JRoy** [comment]
Cannot reproduce on latest Paper with following code:
```java
        Scoreboard scoreboard = this.getServer().getScoreboardManager().getMainScoreboard();
        scoreboard.registerNewTeam("redteam");
        scoreboard.getTeam("redteam").addPlayer(event.getPlayer());
        event.getPlayer().setGlowing(true);
```

This is likely a problem with CMI
