### ISSUE TITLE
Nether portal crash

### ISSUE THREAD

**Issue by ArnoPompio** [PaperMC/Paper#4304]
Going in the nether portal near a worldborder makes the server crashes

Crash logs :

http://pastebin.fr/64697

### Plugin list:
Plugins: { PhantomSpawnControl v2.1.1 phantomspawncontrol.main.PhantomSpawnControl [alexqp], AntiCooldown v3.4 de.tubeof.ac.main.Main [], PlaceholderAPI v2.10.9 me.clip.placeholderapi.PlaceholderAPIPlugin [HelpChat], UltimateAutoRestart vBuild 40a dev.norska.uar.UltimateAutoRestart [Norska], OtherAnimalTeleport v2.0-b26 com.coollord22.otheranimalteleport.OtherAnimalTeleport [CoolLord22], PlugMan v2.1.7 com.rylinaux.plugman.PlugMan [rylinaux], FarmLimiter v1.4.0 me.filoghost.farmlimiter.FarmLimiter [filoghost], CommandTimer v4.3.1* me.playbosswar.com.Main [PlayBossWar], EntityDetection v1.1.3 (build #21) de.themoep.entitydetection.EntityDetection [Phoenix616], RawMsg v1.8.1 me.funnycube.rawmsg.Main [funnycube], ChatReaction v1.8.0 me.clip.chatreaction.ChatReaction [extended_clip], DeluxeTags v1.8.1* me.clip.deluxetags.DeluxeTags [extended_clip], BetterConcrete v1.5.0 com.github.alexqp.betterconcrete.main.BetterConcrete [alexqp], GSit v[2.16.0.0] me.gsit.Main.GSitMain [Gecolay], Voteparty v1.0* me.trollc.voteparty.Main [Troll_C], LuckPerms v5.1.93 me.lucko.luckperms.bukkit.LPBukkitBootstrap [Luck], QuickBoard v4.4.1* me.tade.quickboard.QuickBoard [Tejdik], DragonDropElytra v1.13_1.0.3 com.github.joelgodofwar.dde.DragonDropElytra [JoelGodOfWar/JoelYahwehOfWar], NoSpawnerChange v2.1 kangarko.nospawnerchange.NoSpawnerChange [kangarko], IllegalStack v2.1.6 me.dniym.IllegalStack [dNiym], BuycraftX v12.0.6 net.buycraft.plugin.bukkit.BuycraftPlugin [Buycraft], Votifier v2.7.1 com.vexsoftware.votifier.NuVotifierBukkit [Ichbinjoe, blakeman8192, Kramer, tuxed], Multiverse-Core v4.1.0-b775 com.onarandombox.MultiverseCore.MultiverseCore [Rigby, fernferret, lithium3141, main--, dumptruckman], ProtocolLib v4.6.0-SNAPSHOT-b478 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], LibsDisguises v10.0.14 me.libraryaddict.disguise.LibsDisguises [libraryaddict, Byteflux, Navid K.], FlyStorage v1.0 fr.andross.flystorage.FlyStorage [Andross], AdvancedPortals v0.5.8 com.sekwah.advancedportals.bukkit.AdvancedPortalsPlugin [sekwah41], ImageMaps v1.0.2 net.craftcitizen.imagemaps.ImageMaps [SydMontague], MovingDevApi v1.1.10 com.movingdev.minecraft.api.mainclasses.MovingDevApi [MovingDev], IPWhitelist v1.7* net.craftminecraft.bukkit.ipwhitelist.IPWhitelist [roblabla], LimitPillagers v2.14.0 me.hexedhero.lp.LimitPillagers [HexedHero], NerfPhantoms v1.2.0 com.tallcraft.nerfphantoms.NerfPhantoms [Tallcraft], Vault v1.7.3-b131 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], ChatColor2 v1.9.4* com.sulphate.chatcolor2.main.ChatColor [Sulphate], ResourceWorld v1.7.11 me.nik.resourceworld.ResourceWorld [Nik], EpicRename v3.8 com.gmail.justbru00.epic.rename.main.v3.Main [Justin Brubaker, JustBru00, jayoevans], MobArena v0.104.2 com.garbagemule.MobArena.MobArena [garbagemule], HolographicDisplays v2.4.4 com.gmail.filoghost.holographicdisplays.HolographicDisplays [filoghost], Marriage v2.0.20 com.lenis0012.bukkit.marriage2.internal.MarriagePlugin [lenis0012], PlayerVaults v4.1.11 com.drtshock.playervaults.PlayerVaults [drtshock, kashike, CmdrKittens], boosCooldowns v3.16.1* cz.boosik.boosCooldown.BoosCoolDown [LordBoos (boosik)], WorldEdit v7.2.0-beta-04+98f71a3 com.sk89q.worldedit.bukkit.WorldEditPlugin [], BlockQuest v2.2.2 me.robifoxx.blockquest.BlockQuest [], MineableSpawners v3.0.8 com.dnyferguson.mineablespawners.MineableSpawners [fergydanny], HeadDatabase v4.12.5* me.arcaniax.hdb.Main [Arcaniax], PowerlessLamps v2.5* net.nulll.uso.PowerlessLamps.PowerlessLamps [iPyronic], Citizens v2.0.27-SNAPSHOT (build 2100) net.citizensnpcs.Citizens [fullwall], AsyncWorldEdit v3.7.6 org.primesoft.asyncworldedit.AsyncWorldEditBukkit [SBPrime], CustomGUI v2.5.0 me.jacobculley.customgui.CustomGUI [], Vivecraft-Spigot-Extensions v1.16.2-r2 org.vivecraft.VSE [jrbudda, jaron780], EpicBosses v1.2.12 com.songoda.epicbosses.EpicBosses [Songoda], SuperbVote v0.5.4 io.minimum.minecraft.superbvote.SuperbVote [tuxed], LeaderHeadsRevamped v4.0.6 tech.panoply.leaderheads.LeaderHeads [Panoply Tech], WorldGuard v7.0.4-beta1;bc551da com.sk89q.worldguard.bukkit.WorldGuardPlugin [], AuctionHouse v2.1-rc8 com.spawnchunk.auctionhouse.AuctionHouse [klugemonkey], CommandNPC v1.9.1* me.messageofdeath.commandnpc.CommandNPC [messageofdeath], CoreProtect v19.1 net.coreprotect.CoreProtect [Intelli], ShopGUIPlus v1.38.0 net.brcdev.shopgui.ShopGuiPlugin [brc], PyroFishingPro v4.0.2 me.arsmagica.PyroFishingPro [], ExtraContexts v2.0-SNAPSHOT* me.lucko.extracontexts.ExtraContextsPlugin [Luck], mcMMO v2.1.133 com.gmail.nossr50.mcMMO [nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking, electronicboy, kashike], GriefPrevention v16.14.0 me.ryanhamshire.GriefPrevention.GriefPrevention [], ArtMap v3.6.3 me.Fupery.ArtMap.ArtMap [[Wispoffates, (Original) Fupery]], ChestShop v3.11 (build 213) com.Acrobot.ChestShop.ChestShop [Acrobot, https://github.com/ChestShop-authors/ChestShop-3/contributors], AdvancedRegionMarket v3.2 net.alex9849.arm.AdvancedRegionMarket [alex9849], Rankup v3.6.1 sh.okx.rankup.Rankup [Okx], EpicHoppers v4.6.11 com.songoda.epichoppers.EpicHoppers [Songoda], ShopGUIPlusMineableSpawnersBridge v1..0.0 net.brcdev.shopgui.bridge.mineablespawners.ShopGuiBridgeMineableSpawnersPlugin [brc], GriefPreventionFlags v5.9.2 me.ryanhamshire.GPFlags.GPFlags [Big_Scary, ShaneBee, DmitryRendov], Wild v2.22-e6c1382 net.poweredbyhate.wildtp.WildTP [LaxWasHere, RoboMWM], AdvancedEnchantments v8.0.0-Pre1.2 n3kas.ae.Core [GC], PlayerWarps v6.2.1 xyz.olzie.playerwarps.PlayerWarps [Olzie], MorphRedeem v1.2.1 net.naturva.morphie.mr.MorphRedeem [Morphie], AEFixItemRepairing v1.2.0* n3kas.fixae.repairing.Core [GC], Essentials v2.18.1.0 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, md678685], Jobs v4.16.1 com.gamingmesh.jobs.Jobs [phrstbrn, Zrips, montlikadani], CrateReloaded v2.0.23 com.hazebyte.crate.cratereloaded.CorePlugin [dinosaur], DeluxeChat v1.16.1 me.clip.deluxechat.DeluxeChat [extended_clip], TradeMe v6.0.4.1 me.Zrips.TradeMe.TradeMe [Zrips], EssentialsChat v2.18.1.0 com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], TAB v2.8.4 me.neznamy.tab.platforms.bukkit.Main [NEZNAMY], AEEssentialsKitsAddon v1.0.0* gc.aeaddon.esskits.Core [GC], SuperVanish v6.1.8 de.myzelyam.supervanish.SuperVanish [MyzelYam], ClaimFly v1.2.6 com.trophonix.claimfly.ClaimFlyImpl [Trophonix], ClueScrolls v4.0.4 com.electro2560.dev.cluescrolls.ClueScrolls [electro2560], ChatFeelings v4.6.8 com.zach_attack.chatfeelings.Main [zach_attack], PvPManager v3.12.3 me.NoChance.PvPManager.PvPManager [NoChanceSD], ChatManager v3.6.7 me.h1dd3nxn1nja.chatmanager.Main [H1DD3NxN1NJA], EssentialsSpawn v2.18.1.0 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], TitleManager v2.3.1 io.puharesource.mc.titlemanager.TitleManagerPlugin [Puharesource],}

### Actions to reproduce (if known):
Going in a nether portal

### Paper version:
Paer-185 1.16.2

**Comment by imDaniX** [comment]
Duplication of #4199

**Comment by Chew** [comment]
Indeed
