### ISSUE TITLE
BlockDropItemEvent#getItems() returns empty list with Beehive that contains Bee

### ISSUE THREAD

**Issue by bertek41** [PaperMC/Paper#4307]
### What behaviour is expected:
Expected to event.getItems() returns item not empty list.

### What behaviour is observed:
Event returns empty list althought there is item.

### Steps/models to reproduce:
Place beehive and spawn bee. When bee enter beehive break beehive. Beehive item will drop but event prints "BEEHIVE:0".

https://youtu.be/_-C2mWqraUs (1.16.3 build 191)

### Plugin list:
Just test plugin with this event:
```
@EventHandler
public void onBeeHiveBreak(BlockDropItemEvent event) {
	BlockState blockState = event.getBlockState();
	Material blockType = blockState.getType();
	Bukkit.broadcastMessage(blockType.name()+":"+event.getItems().size());
}
```

### Paper version:
git-Paper-186 (MC: 1.16.2)

### Anything else:
In survival mode event works as expected but in creative mode event returns empty list even there is item.

**Comment by HexedHero** [comment]
Thats not the way you get bees inside hives. Make sure its a beehive/nest and cast to Beehive then getEntityCount

`beehive hive = (Beehive) block.getState();`
`int amountOfBees = hive.getEntityCount();`

**Comment by bertek41** [comment]
Sorry I guess I explained it wrong. I am not getting entities. I am getting beehive item that dropped.

**Comment by bertek41** [comment]
Added video to issue.
