### ISSUE TITLE
Getting errors on startup join and using certain plugins

### ISSUE THREAD

**Issue by titustitus98** [PaperMC/Paper#4310]
### Link/paste of stack trace 
https://pastebin.com/bfWrKrcm
    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list: plotsquared, holoplots, papi, fawe, worldguard, luckperms, protocol lib holographic displays
___A list of your plugins___
 
### Actions to reproduce (if known): not known
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper version: 1.16.2
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

**Comment by electronicboy** [comment]
Somebody loaded a world with a command, loading a world is slow; you can disable keeping spawn loaded in paper.yml to help with that stuff

**Comment by titustitus98** [comment]
I disabled spawn being kept loaded and installed multiverse but it hasn't helped one bit, in fact it might have even made it worse as the server was lagging more than before, the server has about 3gb of ram just so you know.
