### ISSUE TITLE
Villager trade menu is not closed when unable to trade

### ISSUE THREAD

**Issue by FakEEE14** [PaperMC/Paper#4313]
### What behaviour is expected:
when there is a natural villager and you give them a workstation they will trade you the items

### What behaviour is observed:
when villager have his work if 2 to 3 pepole open the trade gui and third party come destroy the workstation and and put a bed next to villager villager leave the job and goto sleep and villager trade bar is still open and if you find a good deal with him you can trade infinitely as the third party can drop you emerald for trade and villager don't stop trading till gui closed

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
essentialsx,fawe,worldguard,griefpreventaion,vault on 1.16.3

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Chew** [comment]
Not sure how this could be considered a "dupe" as the name implies. This seems like a vanilla bug, if not, intended behavior.

**Comment by FakEEE14** [comment]
sometimes there is a discount and there is a xp bar that don't let you trade infinitely but this make it infinite xp farming good trading

**Comment by aikar** [comment]
yeah sounds like something we can patch. once villager sleeps and/or loses job, it should close open trade windows.

i guess this can be behind a game-mechanics config if anyone wants to PR it.

**Comment by MrIvanPlays** [comment]
[here's](https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.3/patches/server/0050-Fix-villager-dupe.patch) my attempt at patching this.

**Comment by FakEEE14** [comment]
work perfect thanks <3

**Comment by jacobsandersen** [comment]
I can't fully repro this. First of all, I can't open a trade with a villager for more than one player at a time. How are you opening it for 2-3 people at a time? Secondly, when I destroy the villager's workbench (composter/fletching table/etc) then the active trade does close.

I did experience the villager leaving for a bed, but not every time and I can't figure out what a reliable trigger for that is. However, in my PR there is code for when the villager sleeps it will close its inventory and cancel any trades. Seems like more of a band-aid than anything though.

My repro steps were:
- Find village
- Find villager
- Place down a job site block (fletching table)
- Villager takes job
- Open trade screen on Player 1
- Player 2 destroys job site block
- Player 1 has trade cancelled

When the villager slept while Player 1 had a trade open, the trade was cancelled with #4353.

Am I missing repro steps to get that 2-3 people scenario?

Here's a video showing trade screen being closed when job site is destroyed.
https://i.imgur.com/u6eEJ1z.gifv

**Comment by jacobsandersen** [comment]
@FakEEE14 Will need confirmation that this still occurs on the latest paper please; also, please include more context on how multiple players opened the trade window in the first place. I can only get this to happen for one player at a time. Please include repro steps as well, if mine are not correct.

**Comment by FakEEE14** [comment]
i try it at the latest version of 1.16.3 and it's patched, when the job station destroyed gui get closed

**Comment by jacobsandersen** [comment]
@FakEEE14 How about the sleep issue?

**Comment by FakEEE14** [comment]
it was related to the sleep when job station destroyed and villager goes to sleep but now when the gui closed, so villager can sleep in peace

**Comment by Chew** [comment]
So this is no longer an issue?

**Comment by jacobsandersen** [comment]
@Chew that's my take away. I think this and the attached pr can be closed.

**Comment by FakEEE14** [comment]
yeah it's fixed thanks to you awsome guys <3

**Comment by andrewkm** [comment]
Not fixed.
1.16.5 - B786
https://vimeo.com/592899890
