### ISSUE TITLE
Better compatibility with datapack?

### ISSUE THREAD

**Issue by oOBoomberOo** [PaperMC/Paper#4314]
**Is your feature request related to a problem? Please describe.**

As a data packer, We've always been on the bad term with Paper due to how incompatible our data pack is when using on the Paper server.
I've always received a bug report about my datapack not working on the paper servers due to some differences between the vanilla and paper version, which I believe shouldn't be the case since data pack is a vanilla feature that should be supported and work anywhere.
An example of this is my [Armor Stand Editor](https://www.planetminecraft.com/data-pack/armor-stand-editor/) datapack which frequently receive a report about getting pushed back by the invisible villager's collision (that I explicitly disable the collision), of course, this is due to how Paper handles entity's collision and team scoreboard. From what I've gathered, by default, a non-player entity cannot join a team, which prevents my method of disabling entity collision from working entirely and it's also completely different from vanilla's behavior.

**Describe the solution you'd like**
I believe that Paper should try to be more consistent with the vanilla behavior, and provide a way for the user to config their server explicitly.  
But if the solution above isn't possible then I would like Paper to at least document about the difference between Vanilla and Paper so that we, data packers, can know how to work around this problem easily.

I made this issue from the perspective of data packer but this isn't really limited to just that. Inconsistency between Vanilla and Paper can affect anyone that might be interested in using Paper.

**Comment by eatYourHashs** [comment]
Would like to second this. I am also a datapack creator. Datapacks aren't just limited to what's achievable with plugins, such as armor stand editing (as Boomber mentioned above); they can even go as far as to add entirely new content in the game, like mods. Supporting this extensive method of customizing and enhancing one's game really should be a given when making server software.

Edit: Another comment on the matter: By not supporting what is potentially the fastest growing modding method, and also one that's being not only actively supported but expanded upon by the devs, this software could become backed into the corner of relying on plugins, even when there are things datapacks can do far better than plugins (for example, adding entirely new content to the game; I can only name one sizable content plugin off the top of my head).

**Comment by RavioliFormuoli** [comment]
Also seconding as a datapack creator. It would be wonderful to run my private server on an optimized server software without worrying about compatibility issues. Although I'm aware a request such as this would likely take a lot of development time, I believe it would at least be worth investing into fixing some of the primary reasons why datapacks break on Paper.

**Comment by Machine-Maker** [comment]
> they can even go as far as to add entirely new content in the game, like mods.

How can datapacks add new content like mods? Pretty sure paper discourages all use of datapacks, more specifically, ones that make use of the tick function that runs a command every tick. This is __extremely__ inefficient.

**Comment by electronicboy** [comment]
Documentation has been suggested but we need people to work with us, we're a handful of people at most working on a project in our free time/what we have of it, we don't have the will to drive through and note down every single discrepancy between us, spigot, CB and vanilla, we've asked people to step up before to do it, but, nobody ever does

> From what I've gathered, by default, a non-player entity cannot join a team

This can be configured in paper.yml, `allow-non-player-entities-on-scoreboards`


Datapacks are a long overdue afterthought from mojang, and honestly, outside of their ability to add stuff to the game, which is still heavily limited, their overall far from the best solution for servers; Maybe a small server with a handful of friends, but, I dread to imagine the day when you have even remotely the number of players on a server we can generally support with them, plugins just do all of this much better as they're not wasting time blowing commands around and going 10 yards to do basic calculations.

if somebody wants to create documentation on the differences, there are likely ways to counteract each one that we can suggest or add it to the "list of stuff we should look into", but honestly, I can't see anybody willing to step forward to document the differences, we honestly don't have time to do it, we can throw it on our todo lists, but, being realistic, that'll be gotten to 10 years from now? We're going to have to have the community contribute here.
