### ISSUE TITLE
PlayerChunkMap memory leak? (not critical)

### ISSUE THREAD

**Issue by HauserGrim** [PaperMC/Paper#4315]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___
Timings
https://timings.aikar.co/?id=a0291b02e27d45fd8c07ab45939f1047#timings

### Description of issue:
I decided to check if there are any memory leaks. I made 2 dumps, one after the restart, the second after a certain time of the game and compared them.
Screenshot: https://user-images.githubusercontent.com/37507220/92999830-c888dc00-f52c-11ea-9900-25b3b5aee232.png
It's ok?

### Plugin list:
AnBot*, ASBorder, ASFrames, ASTime, AuthMe, AutoMessage*, AutoSaveWorld*, Chairs, ChatGuard*, Chunky, Citizens, DeluxeMenus, DeluxeTags, DisableWindowItems, dtlTraders, DungeonsXL, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, FastHarvest, FishFix, Guilds, HolographicDisplays, IllegalStack, LibsDisguises, LuckPerms, Matrix, MobSpawnLimit, NametagEdit*, NicksFilter*, NoCollisionSpawner, PlaceholderAPI, ProtocolLib, SaveTheCoral, ServerListPlus*, SkinsRestorer, Soulbound*, StackMob, TitleManager, TradePlus, UltimateTimber, Vault, VillagerOptimiser, VoxelSniper, WGExtender, WGFixer*, WorldEdit, WorldGuard

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___
bukkit.yml
https://pastebin.com/Y3Xpjy4u
spigot.yml
https://pastebin.com/3TFKgTn5
paper.yml
https://pastebin.com/HBUp3BEC

### Other helpful links
Heap dump after restart
https://drive.google.com/file/d/1JpEWgU2DP_XHLTZIQc2KWr1QnZfgQo9Y/view?usp=sharing
Heap dump after ~ 5 hours of playing with 2-4 players. After players leave.
https://drive.google.com/file/d/1qm-FLTFLu7V5Hg81DnLuPPsIOmOyDFbM/view?usp=sharing

### Paper version:
[18:29:00 INFO]: This server is running Paper version git-Paper-186 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[18:29:00 INFO]: Checking version, please wait...
[18:29:01 INFO]: Previous version: git-Paper-176 (MC: 1.16.2)
[18:29:01 INFO]: You are 3 version(s) behind

**Comment by aikar** [comment]
I'm not seeing anything here? what do you think is an issue?

**Comment by HauserGrim** [comment]
> I'm not seeing anything here? what do you think is an issue?

The second dump shows that it uses 2 times more memory, half of which is used by one class (which is not in the first)
If all is well, then you can close the issue. I'm not good at this.

**Comment by aikar** [comment]
the game does cache a lot of chunks in memory, and is iffy about unloading some of em. there is some known leaks but nothing were able to fully track down to fix ourselves without rewriting internals.

but nothing major is going on here so just going to close it as this doesnt show any concern
