### ISSUE TITLE
[Discussion] New Plugin Life-cycle API

### ISSUE THREAD

**Issue by JRoy** [PaperMC/Paper#4317]
Bukkit has long had its problems with plugin life-cycles. Plugins have had no explicit control over whether they are safe to be reloaded or not, if they're shutting down or reloading during `JavaPlugin#onDisable` (up until #3129), and how many plugin cycles a plugin has gone through. Combine those core problems with upstream's desire to not expose plugin life-cycles through API (~~because think about all those non-ticking, Bukkit-implementing server softwares that never shutdown!~!!1!11!~~) and no wonder reloading plugins is such a nightmare.

This is where this issue comes into play. I will be writing and PRing a new plugin life-cycle API to Paper within in the next couple of days/weeks (depends on how busy I am with work). Below are my current plans for the new API which should help solve some of the problems listed below.

The reason I am opening this as an issue for discussion is so that project members, contributors, or plugin developers can give their two-cents on the current API plans and/or suggest even more plugin life-cycle API that would help them write their plugins to respect (or avoid) plugin life-cycles better.

--- 

### New `reload` Property in `plugin.yml`
This property would have 3 different configuration options: `always` meaning the plugin is safe to be reloaded and properly handles its own life-cycle; `never` meaning the plugin in not safe to reload and that the reload command should skip over this plugin; `same-hash` (please suggest a better name) meaning that the plugin is safe to be reloaded as long as the plugin's hash (probably md5 hash due to its speed and since this isn't a security feature) hasn't been changed since the server start. 

Something I'd like input on here is the default value for this property. I'm leaning towards `same-hash` to ensure existing compatibility while adding some safety but it could also be set to false or true idk.

### New API `getPluginReloadCount()I` & `getGlobalReloadCount()I`
The motivation behind this API is to get the number of times the plugin/server has been run through a life-cycle (reloaded). The number of plugin cycles would be incremented each time a plugin is reloaded (forcibly or not). The number of global cycles would be incremented each time the `/reload` command is used.

The destination of these methods are TBD as I'm writing this before looking too deeply into implementation.

### New API `Bukkit#isStarting` & `Server#isStarting`
This API would allow for plugins to understand what part of the plugin life-cycle they are in during `JavaPlugin#onEnable`

### New behavior of `/reload`
The `/reload` command will have a new argument added to it, `force`, which will forcibly reload plugins and ignore their `reload` property. (Personally, I'm on the side of not documenting this in the confirmation message as I think that would train users to always use it.) Also, the `/reload` command will now display what plugins are reloaded and what plugins aren't.

### New behavior in `/version`
The `/version` command will now display the number of global cycles or will display the number of plugin cycles if a plugin is specified.

---

So those are my changes that I plan on making! I'd love feedback from project members, contributors, or plugin developers on improvements or additions I could make!

---

**Comment by Proximyst** [comment]
I'm fully in support of the new APIs, behaviour, and *especially* the property in `plugin.yml`.

Could we also have some API to know when the server is starting and/or the plugin is loaded for the first time (e.g. in the case of PlugMan where a plugin may be loaded well into the server lifetime)?

One thing I am somewhat scared of however is when `#getPluginCycles` would be incremented. Would plugins like PlugMan automatically respect this (disclaimer: I do not entirely know how PlugMan works)? If so, is it only on reload, or also on unload & load?

**Comment by JRoy** [comment]
> Could we also have some API to know when the server is starting and/or the plugin is loaded for the first time (e.g. in the case of PlugMan where a plugin may be loaded well into the server lifetime)?

Yeah sure, I could add `Bukkit#isStarting` to compliment that `Bukkit#isStopping` I added in #3129

> One thing I am somewhat scared of however is when #getPluginCycles would be incremented. Would plugins like PlugMan automatically respect this (disclaimer: I do not entirely know how PlugMan works)? If so, is it only on reload, or also on unload & load?

I can try my best to force plugins like PlugMan to respect the changes in this document, the cycle count shouldn't be a problem to enforce but the question is if I should break PlugMan until it specifically accounts for these new changes from Paper.

**Comment by Proximyst** [comment]
> but the question is if I should break PlugMan until it specifically accounts for these new changes from Paper.

Noo, never, do not break shit; if a plugin makes others misbehave, we don't really have reason to give a shit. PlugMan should add support once the API lands, and its users should update the plugin that already causes many, many headaches.

**Comment by aikar** [comment]
cycles feels like a weird word to use instead of just getReloadCount lol. 

and commands dont use - syntax so it should be /reload force
and prob would need like /reload safe to exhibit NEW behavior

ultimately the issue with reloading partial boils down to dependency order. loadafter is fine, but if a reloadable plugin has a loadbefore and that loadbefore plugin is not reloadable, then you have order issues.

But i think the idea is valid just going to be iffy to achieve strong enforcement of behavior.

ideally would need to bring this up w/ spigot to try to get more adoption.

**Comment by JRoy** [comment]
Fuck you stale bot

**Comment by OpticFusion1** [comment]
> 
> 
> cycles feels like a weird word to use instead of just getReloadCount lol.
> 
> and commands dont use - syntax so it should be /reload force
> and prob would need like /reload safe to exhibit NEW behavior
> 
> ultimately the issue with reloading partial boils down to dependency order. loadafter is fine, but if a reloadable plugin has a loadbefore and that loadbefore plugin is not reloadable, then you have order issues.
> 
> But i think the idea is valid just going to be iffy to achieve strong enforcement of behavior.
> 
> ideally would need to bring this up w/ spigot to try to get more adoption.

In the plugin.yml add a "reloadable" config option which defaults to false, if true reload it when reloading plugins otherwise skip it.
You could probably copy some of the behavior that loading plugins has as well

**Comment by Proximyst** [comment]
As @Draycia pointed out on Discord, Sponge offers an event for the reload instead of any forcing and whatnot. Could it be a thought to have an option for selecting whether your plugin will accept an event or no reload at all? 🤔

**Comment by Rincewind34** [comment]
I thought about this for quite some time now and I think adding an event for reloading would be the perfect design choice for a behaviour thats not really in target here.
As far as I understand, the goal is to get back to the old reload command from the Bukkit days (including possible hot swapping the actual classes). Thats not really practical with an event method.

As for the hot swapping technology: I think there are many plugins that would actually benefit from this kind of feature. When you are only doing some plain event and command stuff without any IO, thats the perfect plugin to be reloaded. But as I already mentioned: when IO comes in its getting tricky. onDisable makes some guarantees while the server is shutting down, that are not met in the reloading process: e.g. being on the main thread and being allowed to do blocking operations to save all the dirty progress caches for example. Same goes for onEnable. It would be great if those more complex plugins would also get a shot at being able to reload, but that would require more major api changes and some rethinking how plugins are dealing with startup and shutdown. A related topic (in my opinion) is kicking the players before actually shutting down the server. I know I read an issue recently about it and most plugins handle their stuff in onDisable and onQuit, but if this could be addressed by the same possibly new design philosophies, that would be great!

A few last words about the event: I think this is still a great idea. Having one command built into paper (or spigot) to trigger a plugin to reload its configuration would streamline the whole experience a little bit at least for me. That could also be independed of the dependency issues Aikar mentioned earlier.

**Comment by lokka30** [comment]
Thought of something - posting it here in hopes that it contributes to this thread. I'd love for something to be done with `/reload`.

Plugins can override a new method, `Plugin#onReload` (which can return a TriState of `SUCCESSFUL`, `NOT_IMPLEMENTED`, or `FAILURE`). In this method, plugins can safely assume the server is already running and just reload configs or other tasks which shouldn't require a restart.

Removing `/reload` entirely is also another option - any thoughts on this?

**Comment by CyberDie22** [comment]
> Removing `/reload` entirely is also another option - any thoughts on this?

I find `/reload` very useful while developing plugins because I don't have to restart the server every time I make a change to my plugin.

**Comment by electronicboy** [comment]
reload is not ultra tenable long term, it's already fraught with issues, and the fact that we're further having to hook into the Minecraft bootstrap process to do some things likely makes this a no go in the long run

**Comment by lokka30** [comment]
> > Removing `/reload` entirely is also another option - any thoughts on this?
> 
> I find `/reload` very useful while developing plugins because I don't have to restart the server every time I make a change to my plugin.

It may be convenient, but it's definitely not ideal. Leaving it in for this reason also exposes the reload functionality to "normal" server owners (who don't develop plugins) where it can be unknowingly abused, even if you yell at them in red text and ask them to confirm their action.

IIRC there is 'hot loading' available where you can make changes to your software and it will automatically take effect without any restarts/reloads.

**Comment by lynxplay** [comment]
Given that paper plugins landed, which are currently already introducing new lifecylces (see boostrap etc) and most of the feedback around this lives in the discord forum post, I'll close this as new lifecycle API for bukkit plugins seems unlikely once we fully migrate all functionality over to paper plugins.
