### ISSUE TITLE
Item stacking spigot problem

### ISSUE THREAD

**Issue by SaltyPotata** [PaperMC/Paper#4324]
### What behaviour is expected:
Items are not stacking after restart (see picture)

### What behaviour is observed:
Can't stack items

### Steps/models to reproduce:
https://hub.spigotmc.org/jira/browse/SPIGOT-5063

### Plugin list:
-

### Paper version:
![image](https://user-images.githubusercontent.com/62210667/93106873-26463100-f6b1-11ea-99ae-a663e0fe6778.png)

### Anything else:
https://hub.spigotmc.org/jira/browse/SPIGOT-5063

I have the same problem like that this is also a problem on paperspigot servers

**Comment by l1ttleO** [comment]
Outdated.

**Comment by Octol1ttle** [comment]
oh its actually outdated
1.16.2 is no longer supported

**Comment by SaltyPotata** [comment]
> oh its actually outdated
> 1.16.2 is no longer supported

I am pretty sure it happens on newer versions also

**Comment by JRoy** [comment]
This seems to directly be a copy of https://hub.spigotmc.org/jira/browse/SPIGOT-5063 and has nothing to do with Paper

**Comment by SaltyPotata** [comment]
> This seems to directly be a copy of https://hub.spigotmc.org/jira/browse/SPIGOT-5063 and has nothing to do with Paper

Yea but it occurs on paperspigot servers too I just sent that so that I can show my problem easier. Same problem happening

**Comment by wallxq** [comment]
Yee! I have the same problem.. #4305

**Comment by Chew** [comment]
Indeed, it appears to be a duplicate, and an upstream issue. Closing in favor #4305
