### ISSUE TITLE
Spectator Noclip Does Not Work

### ISSUE THREAD

**Issue by Mobmaker55** [PaperMC/Paper#4325]
### What behaviour is expected:
I ran `/gamemode spectator` and expected to be able to noclip through blocks.

### What behaviour is observed:
It was like I was in creative mode, except I was invisible. I could not go through blocks, just simply fly around.

### Steps/models to reproduce:
Run `/gamemode spectator`

### Plugin list:
BasicEcon 1.1 - custom, has 0 effect on movement
BasicImprovements 1.1 - custom, has 0 effect on movement
ChatEx
ChestShop
Dynmap 3.1 beta 3a
Harbor
LuckPerms 5.1.93
OpenInv
PlaceholderAPI 2.10.9
PlugMan
ProtocolLib
SilkSpawners
TabList 5.4.6
UberEnchant
Vault
Vivecraft Spigot Extensions
WitherAC_0.21.2
WorldEdit 7.2.0 beta 4
WorldGuard 7.0.4 beta 1

### Paper version:
This server is running Paper version git-Paper-186 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

### Anything else:
I know that my two plugins do not affect this, it might be Vivecraft, but I am not sure.

**Comment by Octol1ttle** [comment]
1.16.2 is no longer supported.
Please update

**Comment by Chew** [comment]
Reproduce without plugins

**Comment by Mobmaker55** [comment]
No plugins, it works normally. I will go troubleshoot on my own, thanks!

**Comment by Chew** [comment]
Good to hear, best of luck!

**Comment by dominicfeliton** [comment]
Tablist v5.4.6 is the issue.

Updating to 5.4.7 (latest available on spigot) will solve your problem 🙂
