### ISSUE TITLE
1.16.2 World tick crash with existing world from 1.16.1

### ISSUE THREAD

**Issue by tacogerbil** [PaperMC/Paper#4326]
I just recently changed over to 1.16.2.  I've also now force upgraded the world in the hopes it would fix the issue.
I let it run for quite a while without logging in (_the log it finished loading at 0852, I logged in at 1046_).  It seems the moment someone logs into the server the clock starts to tick as to the server crashing with an "Exception ticking world" crash.  Simply logging in and standing idle and under 10 minutes it will crash.
I've tried it with a new world and it stays up.  I log in a just let it run (stand idle).  No crash.
I'm running it on my Synology DS1618+ with 16GB RAM.
https://pastebin.com/JaDN5xdb

**_Plugins List:_**
**Plugins (53):** AcuteLoot, AngelChest, AsyncWorldEdit, BetterSleeping3, Cartographer2, ChestSort, ColorCodes, ColoredSigns, CoreProtect, DiscordSRV, Elevators, Essentials, EssentialsSpawn, ExtraContexts, FastCraft, floodgate-bukkit, ForceResourcepacks, Geyser-Spigot, GraveEntitySpawn, GSigns, IllegalStack, InteractionVisualizer, JetpackBasics, Jobs, LightAPI, LuckPerms, LumberJack, LWC, mcMMO, MMOItems, MMOLib, MobHunting, MyPet, NaughtyMode, NetherView, Oh_the_dungeons_youll_go, PlaceholderAPI, PlugMan, PortalFix, ProtocolLib, Residence, ServerListPlus, Shop, SimpleRename, SimpleSignEditor, Vault, VentureChat, ViaVersion, VillagerMarket, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

**_Actions to reproduce (if known):_**
Simply log in and sit idle.

Minecraft Version:
Previous version: git-Paper-186 (MC: 1.16.2) (have also tried various others with same result, only now decided to try again after I read that people have had good results turning off a-sync chunks, which I have now tried and after 15 minutes still no crash.)

**Comment by electronicboy** [comment]
1.16.2 is no longer supported, also, replicate without plugins, only cases we've seen of this specific one has been down to plugins messing around with internals

**Comment by aikar** [comment]
it is likely some plugin trying to mess with spawning asynchronously based on the logs too.
