### ISSUE TITLE
moved-wrongly-threshold does nothing

### ISSUE THREAD

**Issue by soshimee** [PaperMC/Paper#4327]
### What behaviour is expected:
___What you expected to see___
moved-wrongly-threshold should affect how "wrong" the player movements can be.

### What behaviour is observed:
___What you actually saw___
That affects nothing, and there are no logs when the players get snap back to their original position.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Use glitches, modified packets, or mods to clip through a block, but the option does not affect how deep the player can clip.

### Plugin list:
___A list of your plugins___
Reproducable without plugins, as it happened at all times with all servers I had opened.

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-191 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___
Adding an option to completely disable the movement check.

**Comment by electronicboy** [comment]
moved-wrongly-threashold is just for velocity related stuff, collision checks are entirely different; We have 0 interest in messing around with this code for your requirements, given the whole "if you can clip through walls, you'll also be able to clip (and fall) through the ground"

**Comment by soshimee** [comment]
"if you can clip through walls, you'll also be able to clip (and fall) through the ground" This is the exact thing how Bedrock handles it, if a player digs but the block was protected, the player just falls through the ground. Also, this is very problematic because it causes some players to get stuck in certain places and collisions are already being handled on the client side as well.
