### ISSUE TITLE
Strange crash, every second repets the same

### ISSUE THREAD

**Issue by flamingomg** [PaperMC/Paper#4328]
### Link/paste of stack trace
Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:     PID: 16 | Suspended: false | Native: false | State: TIMED_WAITING
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]     PID: 16 | Suspended: false | Native: false | State: TIMED_WAITING
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:     Stack:
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]     Stack:
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         sun.misc.Unsafe.park(Native Method)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         sun.misc.Unsafe.park(Native Method)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.IAsyncTaskHandler.bk(IAsyncTaskHandler.java:131)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.IAsyncTaskHandler.bk(IAsyncTaskHandler.java:131)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:511)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:511)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.World.getChunkAt(World.java:391)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.World.getChunkAt(World.java:391)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.IWorldReader.getChunkAt(IWorldReader.java:100)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.IWorldReader.getChunkAt(IWorldReader.java:100)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.World.getChunkAt(World.java:332)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.World.getChunkAt(World.java:332)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.World.getType(World.java:718)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.World.getType(World.java:718)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.ShapeDetectorBlock.a(SourceFile:27)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.ShapeDetectorBlock.a(SourceFile:27)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.ArgumentBlockPredicate$a.test(SourceFile:98)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.ArgumentBlockPredicate$a.test(SourceFile:98)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.ArgumentBlockPredicate$a.test(SourceFile:84)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.ArgumentBlockPredicate$a.test(SourceFile:84)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.CommandFill.a(SourceFile:94)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.CommandFill.a(SourceFile:94)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.CommandFill.e(SourceFile:58)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.CommandFill.e(SourceFile:58)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.CommandFill$$Lambda$2405/1923425009.run(Unknown Source)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.CommandFill$$Lambda$2405/1923425009.run(Unknown Source)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.CustomFunction$b.a(CustomFunction.java:152)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.CustomFunction$b.a(CustomFunction.java:152)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.CustomFunctionData$a.a(CustomFunctionData.java:163)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.CustomFunctionData$a.a(CustomFunctionData.java:163)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.CustomFunctionData.a(CustomFunctionData.java:91)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.CustomFunctionData.a(CustomFunctionData.java:91)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.CustomFunctionData.a(CustomFunctionData.java:54)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.CustomFunctionData.a(CustomFunctionData.java:54)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.CustomFunctionData.tick(CustomFunctionData.java:37)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.CustomFunctionData.tick(CustomFunctionData.java:37)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1296)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1296)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2974/283224765.run(Unknown Source)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2974/283224765.run(Unknown Source)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send:         java.lang.Thread.run(Thread.java:748)
[Mon, 14. Sep 2020 21:54:59 EDT ERROR]         java.lang.Thread.run(Thread.java:748)
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send: ------------------------------
[Mon, 14. Sep 2020 21:54:59 EDT ERROR] ------------------------------
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[Mon, 14. Sep 2020 21:54:59 EDT ERROR] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[Mon, 14. Sep 2020 21:54:59 EDT INFO] Send: ------------------------------
[Mon, 14. Sep 2020 21:54:59 EDT ERROR] ------------------------------

### Paper version: 1.16.1

**Comment by electronicboy** [comment]
1) Fill in the template
2) 1.16.1 is no longer supported
3) 
> DO NOT REPORT THIS TO PAPER

Your server took too long to tick, some datapack used a fill command which stalled the server

**Comment by flamingomg** [comment]
> 1. Fill in the template
> 2. 1.16.1 is no longer supported
> 
> > DO NOT REPORT THIS TO PAPER
> 
> Your server took too long to tick, some datapack used a fill command which stalled the server

How do I know which datapack used a fill command¿

**Comment by drunderscore** [comment]
Trial and error. Or, look at the functions and find a fill command.
