### ISSUE TITLE
Issues with upgrading worlds 1.12.2 > 1.16.3

### ISSUE THREAD

**Issue by YouHaveTrouble** [PaperMC/Paper#4334]
### What behaviour is expected:
___What you expected to see___

Basically seemless world upgrade from 1.12.2 to 1.16.3 or 1.15.2

### What behaviour is observed:
___What you actually saw___

This error in console for every chunk loaded
https://hastebin.com/meradujumu.sql

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

https://www.youtube.com/watch?v=p5BDuKXoDzs

1. put a 1.12 world into server directory
2. run it

note: the errors appear each time server is turned on and sometimes when new chunks are loaded.

### Plugin list:
___A list of your plugins___

Produced with no plugins at all

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

This server is running Paper version git-Paper-196 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by MrIvanPlays** [comment]
you may want to do 1.12 -> 1.13, then 1.13 -> 1.14, then 1.14 -> 1.15 and then 1.15 ->1.16
there were a lot of changes in 1.13, 1.14, 1.15 and 1.16 for chunk generation stuff so its the safest way to go

**Comment by electronicboy** [comment]
> so its the safest way to go

No, literally not in any form or capacity

**Comment by MrIvanPlays** [comment]
> > so its the safest way to go
> 
> No, literally not in any form or capacity

how come

**Comment by electronicboy** [comment]
remember that one version where mojang broke every double chest in the world and fixed it in a newer versions... That ain't the first world upgrade issue, nor is it the last, using the latest build means you have the latest fixes, it literally all ends up being transformed the same, 1.13 > .14 > 1.15, would literally result in the same data transformations as 1.13>1.15, just, less bugs.

**Comment by aikar** [comment]
Every MC version contains all the fixers from previous versions. 
it runs through them in order.

What cat was meaning is that say mojang identifies a bug in the 1.12 to 1.13 converter. They arent going to release a new 1.13 build, but they can put the fix in the latest 1.16 build.

If you do as Ivan suggested, youll be hit by the bug. But if you run 1.12 to 1.16, the bug could be fixed.

now, sadly this isnt something that mojang strongly does, but theres only potential benfits, not cons.

**Comment by YouHaveTrouble** [comment]
Okay, I'd lie if I said I'm following. The hell do I need to do to update then?

**Comment by Chew** [comment]
Don't do what Ivan said, the error is with 1.12 world upgrading to 1.16.3 directly right? Nothing inbetween? That's the way you're supposed to do it.

**Comment by electronicboy** [comment]
You don't need to update anything, we need to look into reproducing this, basically

**Comment by YouHaveTrouble** [comment]
I'd provide the world, but it's nearly 10gigs :/

**Comment by Prof-Bloodstone** [comment]
> I'd provide the world, but it's nearly 10gigs :/

See if you can trim it down. For example, see if you can leave just a few region files, and still able to reproduce it consistently. And most probably the nether/end worlds are not needed, so you might be able to cut it down to just tens or small hundreds of MB.

**Comment by YouHaveTrouble** [comment]
update: I managed to update the world after about ~15 tries, it no longer gives an error.
I did use exact same copy of the world as before, it just worked. I sure hope it's gonna work when I'll be updating the actual map, since longer it takes, longer players have to wait.
