### ISSUE TITLE
raids dont fully trigger

### ISSUE THREAD

**Issue by JoeFoxe** [PaperMC/Paper#4336]
### What behaviour is expected:
Raid bar fully to appear and spawn raid mobs

### What behaviour is observed:
Raid bar vanishing very quickly with no mobs or horn

### Steps/models to reproduce:
https://www.youtube.com/watch?v=UJ5aTSB_Nk4

### Plugin list:
PaperMC - thats it im told

### Paper version:
This server is running Paper version git-Paper-189 (MC: 1.16.2) (Implementing API 1.16.2-R0.1-SNAPSHOT) You are running the latest version
### Anything else:
I tweaked under EAR -> WUI -> villagers-every: 200 and it started working on my private server  but on the live server it wasnt working still, not sure if some other settings are changed but what would make it not work?

**Comment by Chew** [comment]
We don't support 1.16.2, does this happen on 1.16.3 (latest build)?

**Comment by JoeFoxe** [comment]
we just updated our server to 1.16.3 paper and it still is not working

**Comment by JoeFoxe** [comment]
Still  not working and ive tried everything. Please, someone help

**Comment by Phoenix616** [comment]
Please provide your full config files (or simply your timings as it contains that information)

**Comment by JoeFoxe** [comment]
this is the config i got from my admin of the server and i coped and used that for my testing, 
config-version: 12
settings:
  debug: false
  bungeecord: false
  sample-count: 12
  player-shuffle: 0
  user-cache-size: 1000
  save-user-cache-on-stop-only: false
  moved-wrongly-threshold: 0.0825
  moved-too-quickly-multiplier: 10.0
  log-villager-deaths: true
  timeout-time: 60
  restart-on-crash: true
  restart-script: ./start.sh
  netty-threads: 4
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
messages:
  whitelist: You are not whitelisted on this server!
  unknown-command: Unknown command. Type "/help" for help.
  server-full: The server is full!
  outdated-client: Outdated client! Please use {0}
  outdated-server: Outdated server! I'm still on {0}
  restart: Server is restarting
advancements:
  disable-saving: false
  disabled:
  - minecraft:story/disabled
commands:
  log: true
  tab-complete: 0
  send-namespaced: true
  spam-exclusions:
  - /skill
  silent-commandblock-console: false
  replace-commands:
  - setblock
  - summon
  - testforblock
  - tellraw
stats:
  disable-saving: false
  forced-stats: {}
world-settings:
  default:
    verbose: true
    hopper-amount: 1
    dragon-death-sound-radius: 0
    seed-village: 10387312
    seed-desert: 14357617
    seed-igloo: 14357618
    seed-jungle: 14357619
    seed-swamp: 14357620
    seed-monument: 10387313
    seed-shipwreck: 165745295
    seed-ocean: 14357621
    seed-outpost: 165745296
    seed-endcity: 10387313
    seed-slime: 987234911
    seed-bastion: 30084232
    seed-fortress: 30084232
    seed-mansion: 10387319
    seed-fossil: 14357921
    seed-portal: 34222645
    max-tnt-per-tick: 100
    enable-zombie-pigmen-portal-spawns: true
    item-despawn-rate: 6000
    view-distance: default
    wither-spawn-sound-radius: 0
    arrow-despawn-rate: 1200
    trident-despawn-rate: 1200
    hanging-tick-frequency: 100
    zombie-aggressive-towards-villager: true
    nerf-spawner-mobs: false
    end-portal-sound-radius: 0
    mob-spawn-range: 6
    max-entity-collisions: 8
    merge-radius:
      exp: 4.0
      item: 1.0
    growth:
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      beetroot-modifier: 100
      carrot-modifier: 100
      potato-modifier: 100
      wheat-modifier: 100
      netherwart-modifier: 100
      vine-modifier: 100
      cocoa-modifier: 100
      bamboo-modifier: 100
      sweetberry-modifier: 100
      kelp-modifier: 100
    entity-activation-range:
      animals: 24
      monsters: 24
      raiders: 48
      misc: 16
      water: 16
      villagers: 32
      flying-monsters: 32
      villagers-work-immunity-after: 100
      villagers-work-immunity-for: 20
      villagers-active-for-panic: true
      tick-inactive-villagers: true
      wake-up-inactive:
        animals-max-per-tick: 4
        animals-every: 1200
        animals-for: 100
        monsters-max-per-tick: 8
        monsters-every: 400
        monsters-for: 100
        villagers-max-per-tick: 4
        villagers-every: 200
        villagers-for: 100
        flying-monsters-max-per-tick: 8
        flying-monsters-every: 400
        flying-monsters-for: 100
    ticks-per:
      hopper-transfer: 8
      hopper-check: 1
    hunger:
      jump-walk-exhaustion: 0.05
      jump-sprint-exhaustion: 0.2
      combat-exhaustion: 0.1
      regen-exhaustion: 6.0
      swim-multiplier: 0.01
      sprint-multiplier: 0.1
      other-multiplier: 0.0
    max-tick-time:
      tile: 1000
      entity: 1000
    squid-spawn-range:
      min: 45.0
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64

**Comment by HexedHero** [comment]
Thats not how to send configs.
https://paste.gg/

Also just tested and works fine for me.

**Comment by JoeFoxe** [comment]
https://paste.gg/p/anonymous/083ab85fa77a4c1287023b584511fcda

here is the exact same thing

**Comment by Phoenix616** [comment]
Additionally to using a paste site (ideally [gist.github.com](https://gist.github.com)) please provide __all__ config files, not just one of them.

**Comment by JoeFoxe** [comment]
I havent made any changes to the other configs at all, so do with that as you wish

**Comment by JoeFoxe** [comment]
everything is just base paper, im asking, what do i need to change to get it to work, like vanilla
i just want it to act as vanilla as possible
