### ISSUE TITLE
Mobspawning count incorrect / limit ignored

### ISSUE THREAD

**Issue by Foorcee** [PaperMC/Paper#4338]
I had taken a closer look at mob spawning and found a mistake.

For each chunk, the number of spawned mobs in the class SpawnerCreature.d are updated. On closer inspection I found out that this does not work, because the value is overwritten. I think that the method mergeInt was not applied correctly. 

For the first chunk, the number is correct, then for all other chunks that are ticked, the amount of mobs is 0-3. So the limit of the mobs is ignored, because the count does not match.

From the docs: (Map.merge)
The first argument in the remapping function is the old value and the second value is the passed value.

https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#merge-K-V-java.util.function.BiFunction-

```java
 V oldValue = map.get(key);
 V newValue = (oldValue == null) ? value :
              remappingFunction.apply(oldValue, value);
 if (newValue == null)
     map.remove(key);
 else
     map.put(key, newValue);
```

I made a short test too, where you can see, that it does not work correctly.

```java
   Object2IntMap<EnumCreatureType> map = new Object2IntOpenHashMap<>();
    @Test
    public void mapTest(){
        updateSpawns(EnumCreatureType.MONSTER, 3);
        int spawns = map.getInt(EnumCreatureType.MONSTER);
        assertEquals(3, spawns);

        updateSpawns(EnumCreatureType.MONSTER, 0);
        spawns = map.getInt(EnumCreatureType.MONSTER);
        assertEquals(3, spawns); //AssertionFailedError: Expected :3, Actual :0
    }

//SpanwerCreature.java L160
    private void updateSpawns(EnumCreatureType creatureType, int spawns){
        map.mergeInt(creatureType, spawns, (keyInMap, valueInMap) -> {
            System.out.println(spawns + " " + valueInMap + " " + keyInMap);
            return Integer.valueOf(spawns + valueInMap.intValue());
        });
    }
```

**Comment by Foorcee** [comment]
Also, the amount of spawned mobs is theoretically incorrect when a skeleton rider is spawned (mob + passenger), they are counted as 1 spawn (entity)

**Comment by Proximyst** [comment]
Thanks Github, that's not the same repository.

**Comment by Folas1337** [comment]
Also not only does the counting seem to be off, it also seems that the limit itself is somehow not working.

I've set all "spawn-limit" to 0 in bukkit.yml then joined the server and killed everything by using "/minecraft:kill @e[type=!minecraft:player]" followed by a "/minecraft:kill @e[type=minecraft:item]".

That resulted in "/minecraft:execute if entity @e" giving me a count of "1" which is only my player.
After being on the server for another minute it starts going up again including mobs like pigs, chicken and cows in some random places. If I teleport to them via "/minecraft:execute at @e[type=minecraft:chicken,limit=1] run tp @s ~ ~ ~" it puts me to coordinates which aren't even close to the spawn (it was at -323 63 -392 while the spawn is at 181 63 -202).

Something similar seems to be happening if I turn up the "spawn-limit". With spigot the entities cap out at the default 130 which bukkit.yml is set to but when running paper it goes up to 450 at times which I don't understand at all.

Server version: This server is running Paper version git-Paper-294 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Plugins (0):

I'd love to see this issue resolved 😄
