### ISSUE TITLE
Dropping items using shift key and drop key results in deleted items upon drop

### ISSUE THREAD

**Issue by ChiboYen** [PaperMC/Paper#4343]
### What behaviour is expected:
___What you expected to see___
When I drop a row of stacks of blocks or various items, I expect the same amount to be on the ground to be picked up

### What behaviour is observed:
___What you actually saw___
Items when dropped quickly, get deleted.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
https://youtu.be/w-afe3PBqHI

Steps:
Have a bunch of items in inventory. Press 'E' to go into inventory. Hold whatever key is bound to shift and drop (so quick dropping is enabled), and glide over items in inventory. Repeat until reproduced, doesn't happen every time.

### Plugin list:
___A list of your plugins___
None. Latest paper version at the time (201)

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
![image](https://user-images.githubusercontent.com/69435677/93694714-f9848600-fac3-11ea-93f8-49c22d287422.png)

### Anything else:
___Anything else you think may help us resolve the problem___
None that I can think of currently

**Comment by HexedHero** [comment]
Can confirm, had 9 stacks of grass blocks and dropped them all a few times until I only picked 6 back up. Very easy to repeat.

**Comment by Shadowhackercz** [comment]
This behavior happens only in creative though. It's deleted maybe because of some mechanics in creative for deleting items?

**Comment by Proximyst** [comment]
This is intended behaviour.
