### ISSUE TITLE
Items take a few minutes to stack properly when moved

### ISSUE THREAD

**Issue by thenameisKO** [PaperMC/Paper#4344]
### What behaviour is expected:
Attempting to stack items should immediately allow clients to see items stacked based on vanilla Minecraft behavior. e.g.: stacks of 1, 16, or 64 depending on the type of item

### What behaviour is observed:
Players and staff have experienced issues with items of like-type not stacking properly when shift-clicked into an inventory or chest; the items either do not move at all from the source inventory/container, or the items move to the destination inventory/container as a separate stack instead of automatically stacking with existing items of the same type in the destination inventory/container.  After a few moments, the items then stack properly as if they were queued up for stacking.

### Steps/models to reproduce:
1. Open a container with items of like-type in both the container and the user's inventory (e.g.: dirt blocks in both inventories)
2. Attempt to place items in the source inventory/container in a stack with items of like-type in the destination inventory/container
3. If the bug occurs, the items from the source inventory will not stack with the items in the destination container (or vice versa) and may be placed into their own, separate stack if the items were shift-clicked.
4. After a few moments, the items may then stack properly as if the actions were an action queued up asynchronously.

### Plugin list:
AddLight*, AntiXRay*, ArmorStandEditor, AsyncWorldEdit, BeastWithdraw, BlockLocker, BountyHunters, BukkitCompat*, BuycraftX, ChatControl, ChestShop, ChestSort, Citizens, CMI, CMIEInjector*, CMIPaperLib, ConsoleSpamFix, CoreProtect, CrateReloaded, DiceFurniture, DiscordSRV, EpicRename, FurnitureLib, Gatekeeper*, GriefPrevention, HeadDatabase*, IllegalStack, Jobs, LibsDisguises, LimitPillagers, LiteBans, MobArena, Multiverse-Core, MyCommand, MythicDrops, PacketListenerApi*, PermissionsEx*, PhantomX, PhatLoots, PinataParty, PlaceholderAPI, PlaceItemsOnGroundRebuilt, PlayerHeads, PlotSquared, PluginLibrary*, ProCosmetics, ProtocolLib, PvPManager, React*, SelectionVisualizer, ServerListPlus*, Shopkeepers, TitleManager, TrollCommandsPlusPlus, UltimateFishing, Vault, VeinMiner, Vivecraft-Spigot-Extensions, Votifier, VotingPlugin, VoxelSniper, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, xInventories*, xRay

### Paper version:
This server is running Paper version git-Paper-202 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Tuinity-"598986c" (MC: 1.16.1)
You are running the latest version

### Anything else:
As there are also issues with teleporting to unloaded chunks, this MIGHT be an issue with how Paper is handling asynchronous tasks.  A separate ticket has been made for the teleporting issue.  We were unable to replicate these problems on Spigot-1.16.3 using their latest build.

**Comment by Chew** [comment]
Duplicate of #4305 ? Reproduce without plugins.

**Comment by thenameisKO** [comment]
Attempting to reproduce without plugins, not sure what relation it has to #4305 since my report is focused on any item type, not items with NBT data

**Comment by Octol1ttle** [comment]
Successfully replicated on Vanilla (Singleplayer 1.16.3, only OptiFine installed)

**Comment by Chew** [comment]
mojang what is going on with your code, anyone else wanna confirm in vanilla? Are there any open issues on Mojira about this?

**Comment by Octol1ttle** [comment]
Couldn't find any issues on Mojira about this

**Comment by thenameisKO** [comment]
Unable to replicate the issue at this time without plugins between myself and one of my staff members (though this may also be affected by the number of players online/TPS variations).  Also was unable to replicate it in single player on my own.  I'll leave this ticket open for a bit in case someone else can provide their own anecdote to prove if this is a Mojang issue or a Paper issue, unless it is the repo moderators' policy to close it instead.

**Comment by thenameisKO** [comment]
Update- also have seen this error thrown in console when players report that this issue is occurring despite the source/destination inventories having space available:
[Server thread/ERROR]: Can't find any space for item in the inventory

**Comment by electronicboy** [comment]
> [Server thread/ERROR]: Can't find any space for item in the inventory

That's purely the recipe book

I'm half dead right now, so, can't say I've read/fully understand the issue all too well, but, the only thing which screams here is a plugin messing with items in the inventory and maybe somehow eventually getting their data to line up, there is nothing in the server that would ever magically resort these items once they match, to debug something like this, you'd need to compare the items which are refusing to stack together

Issues like #4305 do come into mind due to the general issues between data upgrades with MC ad CB compat, it's possible that the item was just eventually used in a way that it forced some form of data conversion, e.g. CB > nms inventory transfer

**Comment by thenameisKO** [comment]
Really just trying to come up with some sort of source to look at as I haven't seen any errors in console otherwise (debug mode has been on) and my players and I have been able to replicate this issue with various materials from blackstone, to glass, to sand, to food, etc.  The issue seems to affect all items, and all of these items were created on a 1.16+ map as we did not carry over map data from 1.15.  It is incredibly difficult to narrow it down given that one of my staff and I could not replicate this issue on our development server.  It only became a problem after we updated to 1.16.3 on production since we didn't find breaking bugs in testing.

**Comment by thenameisKO** [comment]
Update since I finally had time to sit down and test this bug under various scenarios:

This issue occurs more often when there are 5+ players on, and still occurs on the latest version of Paper.  We were not able to replicate the issue on a Vanilla server or a Spigot server, but we were able to replicate it on Paper without any plugins included.  The issue did not occur before the 1.16.3 update.

**Comment by Phoenix616** [comment]
I cannot reproduce the issue and I'm pretty sure the code that is actually setting those items into these slots doesn't first move the items into a different slot and then combine it, it directly searches for a slot with a matching item and adds to that item stack.
