### ISSUE TITLE
Villager don't support legacy colored items after server restart

### ISSUE THREAD

**Issue by ffjdksl** [PaperMC/Paper#4347]
### What behaviour is expected:
Villagers that require items with especific meta (like custom colored name, lore, etc) save the info correctly

### What behaviour is observed:
After the server is restarted, villagers convert any color codes items had in their trades to the new RGB system, which makes trading impossible when carrying items with legacy-colored names.

legacy-colored: items that had colored names or lores before the 1.16 update or items given using PLUGINS after the update.

### Steps/models to reproduce:
1- Spawn in a custom villager that requires 1 emerald named "&aSomething" or any other legacy-colored name. The result of the trade doesn't matter.
2- Give yourself 1 emerald with the same name so you can complete the trade with the villager, just to check that everything is working fine for now
3- Restart the server
4- Try to trade with the villager, you shouldn't be able to because the required item for the trade inside the villager changed.

### Plugin list:
EssentialsX (To give yourself items with legacy-colored names) (/i emerald 1 name:&aSomething)
Shopkeepers (To edit villagers easily with shift + right click. WARNING: This plugin has some config options that mess item meta, make sure to have "convert-player-items" and "convert-all-player-items" at plugins/Shopkeepers/config.yml set to false before the test, otherwise weird stuff might happen.)

### Paper version:
git-Paper-196 (1.16.3-R0.1-SNAPSHOT)

**Comment by MrIvanPlays** [comment]
the strange thing here is that when the player data is loaded items are not converted
🤔

**Comment by ffjdksl** [comment]
True. I don't really know how conversion works, but I wonder how expensive it would be in term of resources if an attemp to update items in a player's inventory was done everytime they joined the server and everytime they pick up an item...
