### ISSUE TITLE
Paper #202 In 1.16.3 Spectators in Unloaded Chunks, cannot chat or teleport to other users

### ISSUE THREAD

**Issue by Kruize1** [PaperMC/Paper#4348]
### What behaviour is expected:
___What you expected to see___
In unloaded chunks, as a spectator, I should be able to send chat messages, type commands, and teleport to other users

### What behaviour is observed:
___What you actually saw___
I cannot send any messages "Cannot send chat messages" is what is returned. If i use numpad keys to teleport to users, nothing happens. Even if a player re-enters the chunk, I have to quit and go back to the server select screen, and re-enter the server. Then chat and teleport work.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
1. Enter server
2. Have other player enter server
3. Enter spectator mode
4. Spectate player
5. Have other player log off
6. Attempt to type messages
7. Instruct other user to log in
8. Attempt to type or use numpad (1 and 1) to teleport to user
9. Observe and note what happens

### Plugin list:
___A list of your plugins___
MythicMobs (v4.10.0-BETA-3433)
PerWorldInventory (v2.3.2)
ProtocolLib (v4.6.0-SNAPSHOT-b478)
CrazyCrates (v1.10.1-SNAPSHOT-Build#89)
GriefPrevention (v16.14.0)
TimedRewards (v1.1.9)
Multiverse-Core (v4.1.1-SNAPSHOT-b777)
WorldGuard (v7.0.4-beta1;bc551da)
TAB (v2.8.4)
SAML (v2.0.0)
LuckPerms (v5.1.26)
WorldEdit (v7.2.0-beta-05+e575ffe)
DeathCoordinates (v1.7.2)
BCommons (v0.2.10)
VillagerOptimiser (v1.1.4)
CommandWhitelist (v1.3.0)
WorldGuardExtraFlags (v4.1.4)

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-202 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

https://clips.twitch.tv/PoliteCrazyBaboonUncleNox

![image](https://user-images.githubusercontent.com/21042824/93727094-65232d80-fb6e-11ea-9d7b-8957f8f39d8c.png)

**Comment by Proximyst** [comment]
Regression reverted with https://github.com/PaperMC/Paper/commit/079a793b518b447e574bf6e4a54c2b4be4979a15.

**Comment by JRoy** [comment]
Likely no longer an issue, please reply if you are still having problems with this.

**Comment by lynxplay** [comment]
Should also generally be a non-issue due to #6657
