### ISSUE TITLE
Server Crash 1.16.3 build 202 shipwreck chest

### ISSUE THREAD

**Issue by iLiDanMoon** [PaperMC/Paper#4349]
I open the chest in the ship, and the server starts to crash!
Version 1.16.3 Paper -202 build
Multiworld Plugin
The map was created using the EpicWorldGenerator plugin
[crash-mw-world-Perfect-EpicWorldGenerator.log](https://github.com/PaperMC/Paper/files/5254943/crash-mw-world-Perfect-EpicWorldGenerator.log)

**Comment by iLiDanMoon** [comment]
Crash#1
https://imgur.com/a/JGvY995
Crash#2
https://imgur.com/a/6qcqj5w
Crash#3
https://imgur.com/a/JkaaQ94

**Comment by iLiDanMoon** [comment]
The world was created on 1.16.2 Version , and is used on 1.16.3 version of paper build-202

**Comment by Proximyst** [comment]
Reproduce without EWG.

**Comment by iLiDanMoon** [comment]
I fixed the crash by removing the ship from the map
I downloaded FAWE and made a set of earth then air
Used the paper loaded-chunks-r2 (1.16.3)kernel
I will close the topic, because the bug will be fixed in 1.17 (Possibly)

**Comment by electronicboy** [comment]
Duplicate of #2312
