### ISSUE TITLE
"Process auto save every tick" feature eating half of each tick

### ISSUE THREAD

**Issue by RoboMWM** [PaperMC/Paper#435]
# Performance issue
### Timings or Profile link:

https://korobi.io/network/spigot/channel/paper/logs/2016/09/25/#L625

Includes timings of build 878, and then of build 868
### Description of issue:

The new "process auto save every tick" is eating about half of a tick on my machine, even while nobody's on/no chunks loaded. I use an HDD, so not sure if that's related or not.
### bukkit.yml, spigot.yml, paper.yml, server.properties

Will give if needed (not sure if the timings link shows it or not properly). But relevant settings are ticks-per.autosave = 12000 in bukkit.yml, paper.yml autosave is set to -1 (default), I played with setting maxTicksPerAutosaveInterval to 0 and -1 with no change.
### Suggestions

Option to disable the new "process auto save every tick."
### Additional info

Timings of build 868 https://timings.aikar.co/v2/?id=8484b09697b94520bbc674002d874cfd&section=lag (auto-save hardly doing much, and even when it does it's no more than the "lag ticks" for autosave in build 878, so I don't think I'm benefitting much from auto-save-every-tick. Coincidentially the doVillages method also seems to hardly causing issues, where as build 878 was struggling with that too, primarily with diskIO/chunkIO.) Link to doVillages in 868: https://timings.aikar.co/v2/?id=3763ae77d54d4a308a257f08721ec56e&section=lag&start=1474829669&end=1474830999#60_113

Update: Seems related to the doVillages ChunkIO/DiskIO @marat569 was having issues with, as well as whoever this guy is in #paper https://korobi.io/network/spigot/channel/paper/logs/2016/09/25/#L1136

**Comment by RoboMWM** [comment]
Also @Bronzeteufel https://timings.aikar.co/v2/?id=c7464b295952441e902def5cc1353a73&section=all (autosave seems to be taking 1/5 of the tick on average since he probably has better hardware than I (but still significant IMO), but same doVillages chunk/disk IO spikes)

```
[22:45:14] Aikar: well this is interesting
[22:45:17] Aikar: vanilla has a chunk GC
[22:45:21] Aikar: runs on auto save
[22:45:32] Aikar: .... so guess whats runnign every tick now due to my change lol
```

**Comment by aikar** [comment]
should be fixed with a57cf22 please confirm

**Comment by RoboMWM** [comment]
Still awaiting testing with load (i.e. players), but so far preliminary results show drastic improvements https://timings.aikar.co/v2/?id=218d231473f14834a8b70d5a51a1c389&start=1474870216&end=1474870690&section=all

**Comment by RoboMWM** [comment]
Seems okay. Not sure for anyone else but TPS is back to a solid 20 again for me and no lag spikes as mentioned previously :D
