### ISSUE TITLE
Paper-202 performace degradation: chunks do not unload

### ISSUE THREAD

**Issue by radiant-ai** [PaperMC/Paper#4352]
###  Timings or Profile link:
Paper-202 26 hours uptime (Server had ~30,000 chunks loaded and was almost out of memory, CHUNK (SELF) 20%):
https://timings.aikar.co/?id=9782f5e61f854177907a3eee09bb3589
Paper-202 12 hours uptime (Server had ~22,000 chunks loaded with only 7 players, CHUNK (SELF) 17%):
https://timings.aikar.co/?id=efcede041ddc4a4cb0e8b341c81680a2
Paper-198 (Expected performace, much LESS chunks loaded):
https://timings.aikar.co/?id=fc58ea0cbe4a4238a12049d4b3b94e6b
Paper-185 (Expected performace):
https://timings.aikar.co/?id=315acb3ecfc244698c8ea4056b87f6b6

All timings are from the same server with same setup. Notice the number of chunks shown in the timings. There is huge amount of them loaded after a long uptime in paper-202 with only a couple of players online.
### Description of issue:
After updating to Paper-202 a lot of chunks stopped to unload from memory. This causes a massive performance degradation after 8 hours of uptime. All the plugins detect chunks as loaded and count the contained entities.

### Plugin list:
AntiAFKPlus, AsyncWorldEdit, AuthMe, BetterRTP, ChatControl, CMI, CMIEInjector*, CMIPaperLib, CoreProtect, CrazyAuctions, EzClans, FarmLimiter, HackedCore*, HeadDatabase*, IronFarmLimiter, LagAssist, LimitPillagers, LuckPerms, Marriage, PlaceholderAPI, ProtocolLib, PvPManager, SAML, SkinsRestorer, Spartan, TAB, TimeIsMoney*, Vault, VillagerOptimiser, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, XProtect*

### Paper version:
This server is running Paper version git-Paper-202 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Previous version: git-Paper-198 (MC: 1.16.3)

**Comment by Chew** [comment]
In the future, please provide the ENTIRE /version output string (as requested)

**Comment by aikar** [comment]
Patch has been reverted now so this is fixed in master, but ima leave this open as it does need to be resolved in the patch to bring it back.

**Comment by Stixil** [comment]
HI, I am having this issue as well on Paper-232, here is my /version output:

[04:07:12 INFO]: This server is running Paper version git-Paper-232 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[04:07:12 INFO]: Checking version, please wait...
[04:07:13 INFO]: Previous version: git-Paper-231 (MC: 1.16.3)
[04:07:13 INFO]: You are running the latest version

Plugin List:
[04:07:46 INFO]: Plugins (1): WarpSystem

Chunks seem to not unload from memory and server performance issues and crashes happen after the server reaches the max allocated memory.

**Comment by Chew** [comment]
> but ima leave this open as it does need to be resolved in the patch to bring it back.

**Comment by e-im** [comment]
No longer relevant.
