### ISSUE TITLE
Server crashes on Startup: "Exception in server tick loop".

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4354]
### Link/paste of stack trace

https://pastebin.com/4afsYtBB

### Plugin list:

- EasyPrefix.
- SkinRestorer.

### Actions to reproduce (if known):
It crashes right after startup.

### Paper version:
Build #204

Hosted on theminecrafthosting.com (Multicraft)

**Comment by electronicboy** [comment]
invalid banned players json file

**Comment by ghost** [comment]
It worked, thanks!
