### ISSUE TITLE
Built-in Silk Spawners Option in Config

### ISSUE THREAD

**Issue by Strahilchu** [PaperMC/Paper#4358]
Requesting the option to be able to break and pick-up spawners with a Silk touch item without needing a plugin.

Seems like a simple addon that could be a config option.

That is all, thank you

**Comment by Proximyst** [comment]
This is not within scope of Paper. If you'd like the server to handle it, there's [Purpur](https://github.com/pl3xgaming/Purpur) by our dear [BillyGalbreath](https://github.com/BillyGalbreath).
