### ISSUE TITLE
Stop Nether Portal Trapping

### ISSUE THREAD

**Issue by Strahilchu** [PaperMC/Paper#4359]
Requesting the option to move players out of a Nether portal if they are stuck in it.
Currently, if you end up in someone else's portal and they have blocked it up with Obsidian, or it's in a protected region... You'd be stuck in it until an Admin removes you. Can't open chatbox in portal.

**Comment by Proximyst** [comment]
This would not only not be possible from the server to change, but is also plugin territory if you just want them teleported out. Not within Paper's scope.
