### ISSUE TITLE
dispatchCommand involves system call

### ISSUE THREAD

**Issue by AlfieC** [PaperMC/Paper#436]
Hey,

I think enough time has passed where plugin authors have learned enough as to ensure commands are not executed async anymore. We can remove the `Bukkit.isPrimaryThread()` call (which, as it uses `Thread.currentThread()` is pretty disruptive) and make command sending a little bit faster.

**Comment by Techcable** [comment]
`Thread.currentThread` is an intrinsic, which compiles into just a couple assembly instructions. As I understand it, a _native_ thread local variable is very cheep, as the address of the thread is stored in a register. You may be confusing this with the high conversion overhead of a JNI (non intrinsic) call, or the high overhead of a ['context switch'](https://en.m.wikipedia.org/wiki/Context_switch), when the operating system is called.
Bukkit.isPrimaryThread is a _very_ fast method, and I beleive it should be used often, whenever there's a chance of concurrency issues.

**Comment by AlfieC** [comment]
http://www.jutils.com/checks/performance.html

**Comment by Spottedleaf** [comment]
Can you give performance metrics to prove that this is a performance issue (in an actual running server)?

**Comment by MiniDigger** [comment]
the copyright notice on that page is from 2007, so the page (and the info on it) is at least that old. are you sure that this is still a issue in the latest java versions?

**Comment by aikar** [comment]
its not worth removing. Timings calls this 15000x more times than a single command execution.

**Comment by Techcable** [comment]
@AlfieC Here's the header file where the [JVM intrinsics are defined](http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/58d961f47dd4/src/share/vm/classfile/vmSymbols.hpp#l636).
`Thread.currentThread()` is [marked as an intrinsic on line 736](http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/58d961f47dd4/src/share/vm/classfile/vmSymbols.hpp#l736).
When the c2 compiler is handling intrinsics, it handles Thread.currentThread() by delegating to the `generate_current_thread method`, which outputs three IR instructions.
First, it outputs the special `ThreadLocalNode` instruction, which is a special-case in the IR to access a thread local variable, and compiles down to simply accessing the base-address of the stack.
Then it adds it to the constant offset of the `JavaThread::threadObj_offset`.
Finally, it loads the object at the address from memory, creating the java-level thread object.
This should compile down to just a couple assembly instructions, making it _slightly_ more expensive than an array bounds-check, and not a performance bottleneck in either commands _or_ timings.
