### ISSUE TITLE
InventoryClickEvent#getCursor() return air if the inventory has been change

### ISSUE THREAD

**Issue by Anarchick** [PaperMC/Paper#4360]
### What behaviour is observed:
InventoryClickEvent#getCursor() return air even if an item is set as cursor BUT this bug appear only if you click outside of the inventory (slot -999)

### Steps/models to reproduce:
- Open a chest inventory and take an item as cursor
- Click outside of the inventoryview (slot -999) and it work as espected
- Write some code to switch to another inventory without manually closing your current chest inventory
- Click outside of the inventoryview (slot -999) and #getCursor() return air

This bug does not appear if you click on a real slot

### Paper version:
```
[16:23:33 INFO]: This server is running Paper version git-Paper-204 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[16:23:33 INFO]: Checking version, please wait...
[16:23:34 INFO]: Previous version: git-Paper-197 (MC: 1.16.3)
[16:23:34 INFO]: You are running the latest version```

**Comment by Shevchik** [comment]
Attach the code used for reproducing this. That's important because InventoryClickEvent API has a note about this: 
```
 The following should never be invoked by an EventHandler for InventoryClickEvent using the HumanEntity or InventoryView associated with this event:

    HumanEntity.closeInventory()
    HumanEntity.openInventory(Inventory)
    HumanEntity.openWorkbench(Location, boolean)
    HumanEntity.openEnchanting(Location, boolean)
    InventoryView.close() 
```

**Comment by aikar** [comment]
@Shevchik thats a pretty dumb java doc that you can consider invalid.
Literally like the primary usage of click event for GUI's is to do those things. 

So yes, it is supported to do those operations, ignore the javadoc.

If something is broken in those operations, then it needs to be fixed.

edit: nvm my hypothesis, i saw you say it is valid if you click in the new window so i assume cursor is still there.

Is cursor valid in inventory open event too?

**Comment by Anarchick** [comment]
> Is cursor valid in inventory open event too?

sorry don't understand what you want to check.

If it can help : I found this bug with my inventory navigator. When I left or right click in slot -999, it change the inventory to a near block inventory. Someone tell me that he can't drop items from inside of an inventory so had try to fix that by checking if the cursor is not air and this bug appear. I had patch this by waiting 1 tick before opening the new inventory but I assume that it's a bug. Something like: The getCursor() is clear before inventory closing and then recreated. It's maybe a simple order of operation that cause this.

**Comment by Shevchik** [comment]
@aikar It does make sense tho. What is the supposed result of uncancelled click happening in already closed inventory?
