### ISSUE TITLE
Wrong EntitySpawnReasons when Bees come out of a beehive

### ISSUE THREAD

**Issue by aurorasmiles** [PaperMC/Paper#4361]
### What behaviour is expected:
When a bee comes out of a beehive / nest, the EntitySpawnReason should be BEEHIVE
### What behaviour is observed:
The spawn reason is SPAWNER_EGG
### Steps/models to reproduce:

1. Make a plugin that prints out the EntitySpawnReason for bees (https://waste.cutiepie.at/lluwenvjm414ejhe)
2. Set up a few beehives with bees and wait till they come out
### Plugin list:
only the test plugin
### Paper version:
1.16.3 204

**Comment by aurorasmiles** [comment]
It seems like the bee keeps the spawn reason they originally spawned with. When I spawn the Bee mit a spawn egg, the EntitySpawnReason is Spawner_egg when they come out of the nest.
When I spawned them via breeding, the EntitySpawnReason also is breeding when it comes out of the nest

**Comment by Machine-Maker** [comment]
I feel like this is intended behavior? The spawn reason is supposed to be the same through out the entities "life". Technically, it is the same entity that comes out of the beehive after you spawned in that bee with a spawn egg. 

I could be getting it backwards tho. And it's supposed to be updated every time the entity appears in the world. If thats the case, then any entity that goes through a portal should have portal be its spawn reason.

**Comment by aurorasmiles** [comment]
I'm not sure. In that case, there should maybe be a seperate "BeeExitHive" event or something like that :D

**Comment by Machine-Maker** [comment]
But that isn't the reason they exist. You spawned them in with an egg. That's their spawn reason. Just cause they happen to go into a box doesn't change that reason.

**Comment by Proximyst** [comment]
I'd like input from @PaperMC/core-team on what the intended spawn reason here, as both reasons can be argued for.

**Comment by HexedHero** [comment]
I feel like this is intended and normal behaviour like Machine since its not the reason why they were spawned into the world, just exited a block but I 100% agree we need an EntityLeaveBlockEvent of some sort, you could prob add metadata to the bee on the EntityEnterBlockEvent and check for it on Spawn event and remove it.

**Comment by Chew** [comment]
I guess we're going philosophical here, what is considered "spawning"? Entity isn't loaded/rendered in the bee nest/beehive, it's stored, but it's not an actual, living entity. Does it "spawn" out of the bee hive/nest? If not, what would you call this?

**Comment by HexedHero** [comment]
Spawning = Added into the game for the first time.
Respawning/Added to world = Being added back into the world from storage. Firing such events like EntityAddToWorldEvent in Paper.

**Comment by electronicboy** [comment]
spawning is when the entity and it's data is created, we don't change the spawn reason when you reload entities in a chunk, it's basically the exact same concept

for a bee, you basically know that it came from either a nest during gen or from a player, those causes should remain, the entity doesn't "respawn" when it leaves a nest
