### ISSUE TITLE
Collisions option not working?

### ISSUE THREAD

**Issue by FlippantCactus** [PaperMC/Paper#439]
In paper.yml, I've set the setting for enable-player-collisions to false.
I'm using built #867 and haven't updated since it's not in the changes but am willing to do so.

**Comment by zachbr** [comment]
Working fine here.

**Comment by CeIebrimbor** [comment]
It works fine for me. You must have something manipulating scoreboard teams or forcing players on another team.

/scoreboard teams list

To see if the collision rule team exists on your server.

**Comment by AlfieC** [comment]
You also have to make sure the teams that your scoreboard plugin creates disables collisions.

**Comment by CeIebrimbor** [comment]
That is automagical if the option in paper is selected. If the team is created, its rule is to disable collisions is automatically set.

**Comment by FlippantCactus** [comment]
Ofc, fml. Redundant issue. Thanks anyways
