### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Carbonax** [PaperMC/Paper#44]
Hi, I followed the guide of running "PaperClip.jar" directly on my server, I did that but it resulted in this crash:

03.03 12:28:46 [Server] INFO at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
03.03 12:28:46 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
03.03 12:28:46 [Server] INFO at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
03.03 12:28:46 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
03.03 12:28:46 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source)
03.03 12:28:46 [Server] INFO at java.security.AccessController.doPrivileged(Native Method)
03.03 12:28:46 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source)
03.03 12:28:46 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source)
03.03 12:28:46 [Server] INFO at java.net.URLClassLoader.access$100(Unknown Source)
03.03 12:28:46 [Server] INFO at java.net.URLClassLoader.defineClass(Unknown Source)
03.03 12:28:46 [Server] INFO at java.security.SecureClassLoader.defineClass(Unknown Source)
03.03 12:28:46 [Server] INFO at java.lang.ClassLoader.defineClass(Unknown Source)
03.03 12:28:46 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method)
03.03 12:28:46 [Server] INFO Exception in thread "main" java.lang.UnsupportedClassVersionError: com/destroystokyo/paperclip/Paperclip : Unsupported major.minor version 52.0

According to my host my server was upgraded to Java 8, so what's gone wrong?

**Comment by Carbonax** [comment]
Issue with host, invalid issue. Sorry! :D

**Comment by zachbr** [comment]
no worries :)
