### ISSUE TITLE
FATAL EROR!

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#441]
http://pastebin.com/K9j1TUY7

**Comment by kashike** [comment]
Please fill out the issue template, and provide all requested details.

**Comment by FunnyCraft** [comment]
http://pastebin.com/cXU99KN6

**Comment by CeIebrimbor** [comment]
**[GadgetsMenu]** Task #17325187 for **GadgetsMenu v3.5.11** generated an exception

**Comment by FunnyCraft** [comment]
what about PwnFilter?

**Comment by CeIebrimbor** [comment]
Get with both those plugin devs to find the root.

And update to latest PaperSpigot (B#883)

**Comment by FunnyCraft** [comment]
The error is to blame GadgetsMenu?

**Comment by RoboMWM** [comment]
@FunnyCraft either fill out the template or close this issue. All you've done is paste the errors of two different issues, which is not sufficient for us to help you. If you are not sure if this is a paper or plugin issue, post in the [aquifer forums](http://aquifermc.org) instead.

**Comment by kashike** [comment]
If you fill this out we'll re-open it. Until then...
