### ISSUE TITLE
Timings disabling automatically

### ISSUE THREAD

**Issue by BlackBeltPanda** [PaperMC/Paper#444]
Build #885

After enabling timings with "/timings on" and waiting 30-60 minutes, typing "/timings paste" yields, "Please enable timings by typing /timings on". This happens every time unless I only wait about 5-10 minutes.

**Comment by aikar** [comment]
I think you have a plugin turning it off, or a staff member did, as I can not reproduce:

I started server with timings disabled:

```
[19:30:33 INFO]: Done (7.064s)! For help, type "help" or "?"
[19:30:33 INFO]: Timings Reset
>timings paste
[19:30:38 INFO]: Please enable timings by typing /timings on
>timings on
[19:30:42 INFO]: Enabled Timings & Reset
[19:30:42 INFO]: Timings Reset
>timings paste
[19:30:43 INFO]: Please wait at least 3 minutes before generating a Timings report. Unlike Timings v1, v2 benefits from longer timings and is not as useful with short timings. (178 seconds)
>timings paste
[19:34:29 INFO]: Preparing Timings Report...
[19:34:29 INFO]: View Timings Report: https://timings.aikar.co/v2/?id=df858b0228494989a7106dcab9130370
[19:34:29 INFO]: Timing Response: Compressed Size: 7468
Uncompressed Size: 23197
Raw Upload: https://timings.aikar.co/v2/?id=df858b0228494989a7106dcab9130370&raw=1
>timings paste
[19:45:26 INFO]: Preparing Timings Report...
[19:45:26 INFO]: View Timings Report: https://timings.aikar.co/v2/?id=37dd48cbd43c4d1ca0ad8e8619d64b70
[19:45:26 INFO]: Timing Response: Compressed Size: 12463
Uncompressed Size: 42315
Raw Upload: https://timings.aikar.co/v2/?id=37dd48cbd43c4d1ca0ad8e8619d64b70&raw=1
```

**Comment by zachbr** [comment]
Can't reproduce it here either.  I've had it running for ninety minutes now, it pastes the report just fine.

**Comment by BlackBeltPanda** [comment]
I'm guessing it must have been a plugin since I'm the only person on the server with access to the timings commands.
It seems to be working fine now, though.

**Comment by BlackBeltPanda** [comment]
Just had it happen again.
Here's an excerpt from the log showing that I kept having to turn the timings back on before getting them to successfully paste: http://pastebin.com/raw/SFZBySmn

**Comment by Black-Hole** [comment]
So please provide a full plugin list.

**Comment by BlackBeltPanda** [comment]
> AntiWorldFly, AutomaticInventory, BlockStore, BossBarAPI, BuycraftX, CaseOpening, ChatControl, ChestShop, Citizens, ClaimLevels, CleanroomGenerator, ConditionalCommands, CoreProtect, CraftBook, CS-CoreLib, CustomEnderChest, DeluxeTags, DiceFurniture, EffectLib, Essentials, EssentialsKitChest, EssentialsSpawn, FastAsyncWorldEdit, FastCraftPlus, FeatherBoard, FurnitureLib, FurnitureMaker, HolographicDisplays, iN_Blocks, LeaderHeads, LibsDisguises, LightAPI, LiveTweak, LockettePro, MarriageMaster, mcMMO, mcMMO_Party_Admin, MobArena, Multiverse-Core, Multiverse-NetherPortals, NametagEdit, Nicky, NoteBlockAPI, ObsidianAuctions, OpenInv, PandaEssentials, PandaSkyblock, PandaWire, PermissionsEx, PlaceholderAPI, PlugMan, PowerNBT, ProjectileTrajectory, ProtectionLib, ProtocolLib, PvPManager, Shop, SketchMap, SkQuery, skRayFall, Skript, Slimefun, SortingHopper, SpigotBridge, SQLibrary, SuperVanish, TerrainControl, TitleManager, TouchscreenHolograms, UltraCosmetics, uSkyBlock, Vault, VoidSpawn, VoteRoulette, Votifier, WorldBorder, WorldEdit, WorldGuard

**Comment by SecretlyJealous** [comment]
I have the exact same issue and it wasn't an issue before until I started using the newer builds. Most of my plugins are custom though so I knew it wasn't an issue with plugins. I copied over my plugins and their configs from my live server including the paper.yml to my test server and on my test server the timings command works but on my live server it doesn't. I restarted my live server to see if maybe player count or uptime is the reason for the command not working and I was able to get the command to work when the server had been up for around 8 minutes with 30 players on but after a couple of minutes I had around 100+ players on the server and when attempting to use /timings paste I'm prompted to enable timings so I use /timings on and then /timings paste but it tells me that I need to enable the timings again for the second time so I do that and then try pasting which gives me the message in red saying it has not been 3 minutes and that is normal but after 5 seconds doing /timings paste just tells me to enable the timings.

Using build #897

**Comment by aikar** [comment]
Something in your environment must be turning it off. It's impossible for the system to auto turn itself off. There's no code in our code base that can disable timings on any conditional element.

It's only by command or API.

Best we could do is add an exception when timings is turned off if a command line flag is passed, to debug whats turning it off

**Comment by SecretlyJealous** [comment]
Yeah something to debug what's causing this would be extremely help. Just find it odd that it is an issue on my live server and not my test server.

**Comment by aikar** [comment]
@SecretlyJealous do you use some server management system in prod that you dont use in dev? Maybe its sending timings commands.

**Comment by zachbr** [comment]
On builds 899+, run paper as `java -Dtimings.throwOnChange=true -jar paperclip.jar` to have the server print debug information about what is causing this.

If you cannot make sense of it, paste it here.

**Comment by BlackBeltPanda** [comment]
Looks like something to do with a plugin trying to save with auto-save enabled?
http://pastebin.com/raw/eP98uaXY

Edit: Nvm, timings still worked after that. I see no stack traces printed in my logs at all showing timings were disabled, but they were still disabled after a few hours.
Relevant log entries: http://pastebin.com/raw/BgvLzGZQ

Edit 2: Happened again, no errors or stack traces at all.

**Comment by BlackBeltPanda** [comment]
Still happening and still no stack trace in the logs indicated that it was turned off. There's only two stack traces at startup indicating they were enabled.

**Comment by SecretlyJealous** [comment]
Same issue here, temporarily using Spigot for 1.11 and the timings v1 works fine: https://timings.spigotmc.org/?url=xitajunada

**Comment by aikar** [comment]
We have discovered this is an issue with FastAsyncWorldEdit doing bad things.

You must set parallel-threads=1 in FAWE config (at least according to their codes comment)

Otherwise, FAWE will disable critical safety checks in the server and forcefully disable timings.
The safety checks that FAWE turns off can result in world corruption.

AsyncWorldEdit plugin does not have these restrictions.

**Comment by BlackBeltPanda** [comment]
Ah, thanks for finding that out! =D
I set parallel-threads to 1 and will wait and make sure it works. I much prefer FAWE over AWE Premium after using both. Hopefully the setting hasn't caused any issues other than timings, so far.
