### ISSUE TITLE
Hiba

### ISSUE THREAD

**Issue by trefamester** [PaperMC/Paper#447]
Nem működik a szikrából pattant 1 varázslat a gyémánt kardomon.

**Comment by zachbr** [comment]
You have not provided the requested information, nor are any of the translations I'm seeing for this making a ton of sense.

Please provide more information, and redescribe your issue in English.

**Comment by AlfieC** [comment]
I believe he's talking about the glint from swords not being shown on clients - I can't reproduce but that's the only translation I can come up with.

**Comment by andris155** [comment]
This is a SamshHit plugin bug. Not Paper.
