### ISSUE TITLE
Walking footstep sound plays repeatedly while inside someone with collision disabled.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#450]
Paper dev 889

With collision disabled;

```
  enable-player-collisions: false
```

When you are inside someone, the walking footstep sound plays repeatedly. Even while standing still.

**Comment by zachbr** [comment]
I've only ever managed to get this to happen one time. Thinking it might be a vanilla issue but I can't get it to happen enough on paper or vanilla to be sure.

**Comment by mibby** [comment]
Hm. I'm able to reproduce it nearly 100% of the time when I tested. Though maybe I was on a slab block floor. I can double check later tonight on ground level.

**Comment by MatrixTunnel** [comment]
I pretty sure it's a vanilla issue. It usually happens with 3+ people but I don't know what causes it. Now that I think about it, If I remember correctly, I was doing stuff with command blocks one time and I was using a scoreboard for "stat.walkOneCm" that counted up when this was occurring. This could have changed as that was a few versions ago (I was using 1.8 snapshots at the time)

**Comment by CeIebrimbor** [comment]
Super random shot in the dark @mibby 

Do you have AAC or another anti-cheat that spawns entities?

**Comment by zachbr** [comment]
This appears to be handled on the client. Not much we can do about it.
