### ISSUE TITLE
Minecart issue with hoppers

### ISSUE THREAD

**Issue by Luysita** [PaperMC/Paper#451]
### Description of issue:

Hoppers won't drop items to minecarts.
Minecarts with hoppers drop 2-3 items in chests/hoppers instead of 1.
### Plugin list:

AntiWDL, CoreProtect, DeluxeChat, dynmap, WorldEdit, OpenInv; NeosNoExplosion, AWD, PermissionsEx, BukkitCompat, WorldBorder, NoPl, Votifier
### bukkit.yml, spigot.yml, paper.yml, server.properties

http://pastebin.com/wFmYVmQG
### Paper build number:

This server is running Paper version git-Paper-819 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

NOTE: The issues are fixed with CraftBukkit version git-Spigot-047f737-744e1a1 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Disable push based hoppers as a workaround.

Closing as duplicate of GH-354

**Comment by Luysita** [comment]
"Disable push based hoppers as a workaround."
Sorry I don't understand this.

**Comment by MiniDigger** [comment]
There is a config option to disable the feature that causes this issue. It is called `hoppers: push-based:`, set it to false and restart the server.
