### ISSUE TITLE
Paper breaks cobblestone generators

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#452]
Incompatibility (Bug):

What behaviour is expected:
Creating a cobblestone generator in the fashion attached will allow the player to mine cobble infinitely and will not break. https://www.youtube.com/watch?v=veEoiCxTjDM

What behaviour is observed:
As soon as one of the cobblestone blocks in the line to be mined is broken, the machine attempts to generate more cobblestone, however cobble generates in the wrong place (where the lava should be flowing) and breaks the machine.

This means paper is causing lava to flow too slow, or water to flow too fast.

Steps/models to reproduce:
Run paper with default settings, make this generator. I've tried tweaking the settings I could think of, including lava-flow-speed, and nothing fixed it.

Plugin list:
N/A

Paper build number:
888

**Comment by zachbr** [comment]
Should be fixed in builds 895+

**Comment by arockstar28** [comment]
This is an issue again in 1.15

**Comment by MiniDigger** [comment]
@arockstar28  please open a new issue with new details and reproduction steps and stuff.
