### ISSUE TITLE
Flying is not enabled bug

### ISSUE THREAD

**Issue by Luysita** [PaperMC/Paper#454]
### Description of issue:

I updated paper today and I'm getting kicked for flying even though I'm not. I'm just happily building a massive building at the moment.
I'm also an operator so this shouldn't be happening to me.
I don't want to enable flight on the server.properties, that's risky.
### Plugin list:

AntiWDL, CoreProtect, DeluxeChat, dynmap, WorldEdit, OpenInv; NeosNoExplosion, AWD, PermissionsEx, BukkitCompat, WorldBorder, NoPl, Votifier
### Paper build number:

This server is running Paper version git-Paper-897 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Error on console:
[12:37:44 WARN]: Player was kicked for floating too long!
[12:37:44 INFO]: Player lost connection: user was kicked.
[12:37:44 INFO]: Player lost connection: Flying is not enabled on this server
[12:37:44 INFO]: Player left the game
[12:37:44 WARN]: handleDisconnection() called twice

Thank you.

**Comment by zachbr** [comment]
Fall back to build 896 for the time being.

**Comment by Luysita** [comment]
Thank you, fixed. I guess I'll update after a while.

**Comment by zachbr** [comment]
Having trouble reproducing this. Will continue to investigate.

**Comment by CeIebrimbor** [comment]
This always has the tendency to happen at random. Usually for laggy players or players stuck in a glitchy block. I'm not sure if it's recent builds that cause it, but rather a long-existing flaw that has been an issue for a while and in random cases.

If I'm not mistaken, the server.properties fly option just checks for players that have been off the ground for way too long. Way too long to be normal.

**Comment by Luysita** [comment]
@CeIebrimbor fixed it with build 896 though.

**Comment by CeIebrimbor** [comment]
Ok
