### ISSUE TITLE
Lootables - Replace Chest

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#456]
Can you please add an option under "Lootables" to have the server replace the chest if the chest was broken? Currently if a player breaks a chest in a village Paper will not attempt to replace the chest when refilling the loot.

To prevent issues with players trying to build there, perhaps it could be set to only replace the chest if the chest's location is currently AIR.

**Comment by zachbr** [comment]
Sounds like an easy fix for a plugin. Not sure this really fits the goal in mind with our config options, the data exposed by the API should be plenty to handle it.

**Comment by aikar** [comment]
not really something doable on core level anyways. The Lootable data is stored on the TE itself. Chest breaks... there is no more data. no reference that location even ever had a lootable object.

Nor does paper have any system to store said data without making custom meta on the chunk which is really out of scope.

I strongly recommend blocking breaks on chests you allow to regenerate.

**Comment by zachbr** [comment]
Just tested, you can block chests and other blocks with associated tables from being destroyed via the API, which is what I'd recommend you do here.
