### ISSUE TITLE
Maven Imports

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#457]
Hey, I know you know no longer support 1.7 however, I came across this [https://aquifermc.org/threads/paperspigot-1-7-10-maven-repo.178/](post). I imported it as it says in the post however when I go to compile the code, Maven gives me this [error](errhttps://gist.github.com/AlfieWest/05bd7e5170d2ebbdc600e0e69aa3e39d). 

Here is my full [pom.xml](https://gist.github.com/anonymous/0969374fcea8a6e775ecb693b82f7b28)

**Comment by Black-Hole** [comment]
Change the URL of destroystokyo-repo from https://repo.destroystokyo.com/content/repositories/snapshots/ to https://repo.destroystokyo.com/repository/maven-snapshots/

**Comment by zachbr** [comment]
Looks like we forgot to update that (old) post when the repo URL changed.
Updated that post.
