### ISSUE TITLE
Portal search radius ignores dimension scaling

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4573]
### What behaviour is expected:
When portal search radius in overworld is 128, it should be 16 in the nether, this is vanilla behaviour since 1.16.2

### What behaviour is observed:
Portal search radius is the same in the nether and in overworld

### Steps/models to reproduce:
1.Place a portal at 0 0 in overworld
2.Place a portal at 32 0 in the nether
3.Enter the portal in overworld, you will be teleported to the portal you built in the nether

### Plugin list:
None

### Paper version:
204

**Comment by e-im** [comment]
This is now configurable via `portal-search-vanilla-dimension-scaling`.
