### ISSUE TITLE
Some mobs spawning and instantly despawning when lowering hard despawn range

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4575]
**Is your feature request related to a problem? Please describe.**
When lowering despawn-ranges.hard, mob spawn range stays the same(128 blocks) and mobs that spawn outside hard despawn range instantly despawn. This creates unnecessary entities that only exist for 1 tick. Also since 1.16 this can drasticly lower mob spawn rates with certain configs. For example, if you have hostile mob limit of 2 and despawn range of 64, only 2 mobs can spawn each tick, and there is a quite big chance that they will spawn outside despawn range and instantly despawn, resulting in no mobs spawning most of the time.

**Describe the solution you'd like**
If you lower despawn-ranges.hard, spawn range also changes to that number(not mob-spawn-range from spigot.yml, but the number the game uses when spawning a mob and checking the distance to the closest player).

**Describe alternatives you've considered**
Adding a config for mob spawn range that is -1 by default, meaning that mob spawn range is the same as hard despawn range

**Additional context**

**Comment by electronicboy** [comment]
the mob spawn range *is* the option in spigot.yml, if that's not working as intended, create a new issue, but, that is the configuration option to control this, there is no need to throw another config ontop of an existing config

**Comment by ghost** [comment]
It is working as intended. I am talking about other spawn range. The option in spigot.yml controls the radius in chunks that mobs can spawn in around the player. But when the mob is spawned the game also checks the distance to the closest player in blocks, and if it is bigger than 128, the mob does not spawn. These are two different ranges that control different things.

**Comment by electronicboy** [comment]
128 is configurable, if your mob spawn range is lower than your despawn ranges, they won't despawn; I'm not really sure what the issue is here?

**Comment by ghost** [comment]
What is the config option name then? I can not find it anywhere. I can only find mob-spawn-range in spigot.yml, but that is a different range. I am talking about configurable spawn range in blocks, not chunks. Also the issue happens when despawn range is smaller than spawn range, not when it is bigger.

**Comment by electronicboy** [comment]
as I said, there is no interest to add a config option ontop of a config option; there is no config option for a block range, nor is there much interest in messing with the existing horror spawn logic to add one
