### ISSUE TITLE
org.bukkit.event.block.BlockBreakEvent#getBlock() sometimes returns air block.

### ISSUE THREAD

**Issue by metabrixkt** [PaperMC/Paper#4576]
### What behaviour is expected:
org.bukkit.event.block.BlockBreakEvent#getBlock() returns the broken block.

### What behaviour is observed:
org.bukkit.event.block.BlockBreakEvent#getBlock() returns the air block, which is appeared after breaking block.

### Steps/models to reproduce:
1. Create new java project and import paper api.
2. Create main plugin class, plugin.yml, etc. (basic plugin structure)
3. Create new class implementing Listener, create method onBlockBreak (name doesn't matter) with arg type of BlockBreakEvent.
4. Try **System.out.print**ing e.getBlock().getType(). Sometimes you'll see AIR in the console.

### Plugin list:
1 plugin: made in **Steps to reproduce**

### Paper version:
git-Paper-204, 1.16.3

**Comment by metabrixkt** [comment]
**Additional info:** I don't know if the number of players affects the frequency of the bug, but I have it with 10 players

**Comment by Brokkonaut** [comment]
This might happen when a player tries to break a block that is already broken on the server side. Did you test that?

**Comment by Proximyst** [comment]
If you use something like `Player#sendBlockChange`, this exact behaviour is very useful to know if the player has broken a block you want some special behaviour for breaking. "Fixing" this could potentially break a lot of plugins; closing as intended feature.

**Comment by metabrixkt** [comment]
@Proximyst I don't use sendBlockChange, it's grief alerts system, but how can I get the real broken block?

**Comment by Proximyst** [comment]
Check if it's air..?

```java
if (event.getBlock().getType().isAir()) return;
```

**Comment by epserv** [comment]
@Proximyst How grief alerts look:
Player **username** broke **username**'s **e.getBlock().getType()** (**number of alert**) in **world**.
If I use /gcheck **number of alert**, it teleports me to e.getBlock().getLocation(). I can see there was a block.
