### ISSUE TITLE
Timings dont work on brazilian servers

### ISSUE THREAD

**Issue by RAFAELESPADA** [PaperMC/Paper#4581]
### What behaviour is expected:
___What you expected to see___
Timings works fine
### What behaviour is observed:
___What you actually saw___
https://prnt.sc/uovjcb
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
I use /timings on and later /timings paste and it give me this error https://prnt.sc/uovjcb the host says it is because you blocked brazilian ips from using timings
### Plugin list:
___A list of your plugins___

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
https://prnt.sc/uovu1b
### Anything else:
___Anything else you think may help us resolve the problem___
Timings doenst work. I need it because my server is laggy. It gives me that error https://prnt.sc/uovjcb . The host say it because my server is brazilian and you have blocked brazlian ips from working. Please help me and make timings working again

**Comment by Proximyst** [comment]
The host's `/etc/hosts` file or your distribution of Paper points to/uses another domain than the official API. This is not an issue on our side: change host and remember to download your Paper from https://papermc.io/downloads
