### ISSUE TITLE
server crashing

### ISSUE THREAD

**Issue by ThePro1604** [PaperMC/Paper#4585]
lately i been experiencing some random timeouts for my server this is my crash log with the watchdog
https://pastebin.com/EavnbEYp
im using git-Paper-189 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by HexedHero** [comment]
Unsupported version. Update to 1.16.3.

**Comment by Chew** [comment]
"DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH" your server is lagging
If you want help, ask for it in [#paper-help on our discord server](https://discord.gg/papermc)
