### ISSUE TITLE
Chunks remain loaded, dramatically builds up memory usage

### ISSUE THREAD

**Issue by moerkoetsmeuk** [PaperMC/Paper#4586]
### What behaviour is expected:
For the server not to exceed the allocated memory and in turn eating up all of the server's available memory and CPU.

### What behaviour is observed:
When I leave the server running for a couple of hours, the memory usage is already much greater than allocated (6GB instead of 3GB for example), and when I leave it running for a full day, it's using up the total of 8GB and all 4 CPU cores are also at a steady 100%.
At the same time the server log is spamming that the server is overloaded.

### Steps/models to reproduce:
Simply running the Paper jar and leaving it on for a couple of hours to a day.

### Plugin list:
No plugins used during this test.

### Paper version:
git-Paper-387 (MC: 1.15.2)
git-Paper-204 (MC: 1.16.3)

### Anything else:
Hey, so I tested this problem in both 1.15.2 and 1.16.3 as you can see above, and it's the same on each version.
It seems that the entity tick is using up a looot of memory, the villagers in particular. The strange this is that this also happens when nobody is online. It seems like the chunk stays active and gets overloaded somehow.
I've also discussed this on the Spigot forums, and that's all the info we got out of it.

Here are the Timings reports:

For 1.15.2:
[https://timings.aikar.co/?id=4837dfa2d74a47d582346ad0b5ddf8ce](https://timings.aikar.co/?id=4837dfa2d74a47d582346ad0b5ddf8ce)

For 1.16.3:
[https://timings.aikar.co/?id=5044efd1b6f64f2a995e5c9e5fbd6089](https://timings.aikar.co/?id=5044efd1b6f64f2a995e5c9e5fbd6089)

Processors/RAM after a few hours:
[https://i.imgur.com/irOAbZI.png](https://i.imgur.com/irOAbZI.png)

Server overloaded:
[https://i.imgur.com/rOpGuud.png](https://i.imgur.com/rOpGuud.png)

**Comment by Strahilchu** [comment]
I don't believe this is a Paper.jar issue. I am unable to reproduce this on two different systems, having exactly what you have.
- edit: removed bad advice -

**Comment by aikar** [comment]
Please do not suggest bad advice such as removing flags, it has nothing to do with it.

Yes the server uses more memory than Xmx. We have no clue why. It's something about the way native memory is used.

We've tried to fix it on theories before but no impact. 

This is ultimately unfixable unless someone fixes it in the JVM or Netty, as mojangs limited use of native memory is correct and not bugged.

**Comment by aikar** [comment]
Also chunks did not remain loaded, your timings look fine.

Please pay attention to differences of Lag tab vs All tab. you had very little lag results.
