### ISSUE TITLE
StructureGenerator

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#459]
http://pastebin.com/Hw4UQWjJ

**Comment by kashike** [comment]
Please use the issue template.

**Comment by aikar** [comment]
While its incomplete, I did do some digging.
the line in question is:

if (world.spigotConfig.saveStructureInfo && !this.a().equals( "Mineshaft" )) {

Some how the world got passed as null.

I'm assuming this was some weird race condition with like the world unloading, so its not worth a diff for unless it happens often.

If it continues to happen, please reopen.
