### ISSUE TITLE
Add an EntityLeaveBlock Event (or similar)

### ISSUE THREAD

**Issue by aurorasmiles** [PaperMC/Paper#4594]
**Is your feature request related to a problem? Please describe.**
Related to #4361 
Afaik there's currently no reliable way to tell when an entity leaves a block, like bees do with their nests. I don't think there are any other mobs with a similar mechanic, but this might change in the future
**Describe the solution you'd like**
An event when an entity "leaves" a block (see bees).

**Describe alternatives you've considered**
The entity spawn event was the first event that came to mind, but since the entity isn't spawned that event is not usable here
**Additional context**
See #4361

**Comment by electronicboy** [comment]
CreatureSpawnEvent already covers this specific usecase, not really sure of where else an event would be suitable, given that there are already varying events thrown around the whole concept of an entity being added to the world

Leaving a vehicle would also not be leaving a block, (the beehive is technically not a block, even if it's entity is bound to one)

**Comment by aurorasmiles** [comment]
The vehicle was a typo :D 
That event has the same issue as in #4361 tho, hasn't it?

**Comment by electronicboy** [comment]
No, you get the spawn reason from the event, not the entity

**Comment by aurorasmiles** [comment]
Ah okay.
That is really confusing, since both events are called "SpawnEvents" but both kinda define "spawn" differently.

**Comment by electronicboy** [comment]
EntitySpawnEvent is the dumb catch-all fallback, more specific events are pretty much always fired
