### ISSUE TITLE
Anti-xray obfuscates blocks behind Slime blocks

### ISSUE THREAD

**Issue by metzg** [PaperMC/Paper#4597]
### What behaviour is expected:
Slime blocks are translucid. The block behind a Slime block shouldn't be obfuscated.

### What behaviour is observed:
Blocks behind Slime blocks are obfuscated

### Steps/models to reproduce:
Place slime blocks next to e.g. cave walls

![image](https://user-images.githubusercontent.com/12766310/94854304-fe82f700-042c-11eb-94c6-68770ba837bf.png)

### Plugin list:
n/a

### Paper version:
```
This server is running Paper version git-Paper-204 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
```
### Anything else:
no

**Comment by stonar96** [comment]
Can confirm. Thanks for reporting this. I'd like to fix this, however, it will conflict with #3311, so I'll wait for a decision on that first.
