### ISSUE TITLE
'Don't sleep between chunk saves' patch degrades chunk generation speed. 

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#46]
https://github.com/PaperSpigot/Paper/blob/master/Spigot-Server-Patches/0054-Don-t-sleep-between-chunk-saves.patch

The 'don't sleep between chunk saves' patch degrades chunk generation speed. Using WorldBorder with Spigot, generating 200 chunks at a time with the command `/wb world fill 200` generates up to 1,000+ chunks each process. With Paper, it is around 200 and degrades over time. After a few minutes, I've had the generation slow down to 20-50 chunks a process. Might be why md_5 ultimately removed it in Spigot.

Puremin0rez compiled and tested Paper without the patch to confirm that is the cause of the slow generation within Paper.

However, that patch is important to have because otherwise, it flushes to disk extremely slow. Due to waiting 10ms for each individual chunk to write to disk. This time adds up with big map generations. I have to periodically restart my server since generating 200 chunks at a time (1,000 each process) eats up 12GB of ram like nothing in only a couple of minutes. But it takes ~10 minutes just to shutdown with Spigot due to the slow writing to disk.

```
[14:17] <Puremin0rez> i guess it's a matter of, does the time you waste waiting for it to shutdown make up for the slower chunk generation?
[14:17] <mibby> No, because it degrades in generation speed with Paper.
[14:17] <mibby> After a few minutes, it goes down to 20-50 chunks / process.
```

Pinging relevant parties.
@aikar @Zbob750 @Puremin0rez

**Comment by Techcable** [comment]
Why is the patch causing the generation to slow down?
We can't just remove the patch, as OOME is unacceptable.

**Comment by mibby** [comment]
That's a question you'll have to ask Aikar or someone else who can look into it. But it is confirmed that is the patch that affects the generation speed within Paper.

**Comment by Puremin0rez** [comment]
Here's the data on the patch for those curious when using it in conjunction with WorldBorder (plugin)
http://pastebin.com/raw/pLaCiAkb

I vote we make this patch a configuration option so people can turn it off when pregenerating maps, then turn it back on when they're done.

This patch is too useful to fully remove and can easily be made configurable.

**Comment by zachbr** [comment]
`>> Paper with "Don't sleep" patch (& with aikars updated patch)`
Can we get this updated patch of his linked here please?

**Comment by Puremin0rez** [comment]
https://gist.github.com/aikar/0d77f19f5d1d4b8933a2

**Comment by TitanicFreak** [comment]
I personally don't see why it's an issue if your map takes awhile to generate, most people should already generate their maps several days or weeks ahead of the launch day.

If it's really an issue, I think making it configurable is a good compromise.

**Comment by martijnrondeel** [comment]
@TitanicFreak It would be an issue if the map has no worldborder and multiple players are exploring. Not all servers use worldborders/pregenerate their maps. Then again, running out of memory is not great either..

**Comment by mibby** [comment]
For what it's worth, this patch also seems to slow down loading already pre-generated chunks when flying in-game. Just flying through the world at fast speeds, chunk loading is extremely slow and TPS drops drastically.

That or chunk loading in 1.9 is absolutely terrible. :( Normal spigot doesn't seem too bad.

Edit: Posted a new ticket, as it seems to be an entirely different issue regarding chunk loading, both Paper and Spigot affected by it.

Regarding Aikar's fixed patch, generation performance is still the same slow speed and still degrades over time. In addition, I have noticed save-all tasks to take much longer than with the not-updated version of the patch. Noticeable by a few seconds compared to instantaneous before.

**Comment by zachbr** [comment]
This patch is no longer present in any form w/in Paper. We need to figure out the other causes behind these chunk issues and then we will return to this patch and its usefulness.
