### ISSUE TITLE
Getting a Materials' Translation Key is sometimes invalid

### ISSUE THREAD

**Issue by MeFisto94** [PaperMC/Paper#4600]
So, I'm the one who implemented https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0571-Add-a-way-to-get-translation-keys-for-blocks-entitie.patch, but apparently it does not work under all cases, specifically barriers and crimson_planks are not correctly translated on the client, I guess for every NMS `ItemBlock`.

The correct key can be obtained by calling `Item#getName` versus `Item#getOrCreateDescriptionId`, because the latter is not overriden in `ItemBlock`, 

`getName = block.minecraft.crimson_planks`
`getOrCreateDescriptionId = item.minecraft.crimson_planks`

@Shevchik has outlined on [Discord](https://discordapp.com/channels/289587909051416579/555462289851940864/761754453082374144), that there also is a difference between the keys of an ItemStack and an Item

### What behaviour is expected:
Keys that work for the client

### What behaviour is observed:
Keys that are broken for at least ItemBlocks

### Steps/models to reproduce:
```
String a = CraftItemStack.asNMSCopy(stack).getItem().getName();
String b = stack.getType().getTranslationKey();
String c = CraftMagicNumbers.getItem(stack.getType()).getName();
```
a is a working solution using the ItemStack, b is the current broken state, c is at least an immediate solution, it is the nms implementation of b, but using getName over getOrCreateDescriptionId, but that currently ignores Shevs' comment on ItemStacks.

### Plugin list:
not applicable

### Paper version:
8a046c95a4babfdd3fec3c0f4fa198f1437819b5, but it is caused by my patch, 0571 on master.

**Comment by Black-Hole** [comment]
A better solution could be to add Material.getItemTranslationKey() and Material.getBlockTranslationKey(), because some materials only have a item or block form or the translation could differ for block and item form.
Some item stacks have special names (like a compass with special tags could be "Lodestone compass").
