### ISSUE TITLE
Crash related to usercache.json ?

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#461]
Crash report: http://hastebin.com/eqewisiter.md
Build 900

**Comment by Black-Hole** [comment]
It seems tab completing in PermissionsEx is enumerating all offline players resulting in one query to the Mojang server for every player ever visited your server.

The best solution would be to limit the PermissionEx command to administrators who know how to use it.

**Comment by zachbr** [comment]
Thanks @Black-Hole
