### ISSUE TITLE
CreatureSpawnEvent - Server crash

### ISSUE THREAD

**Issue by fof1092** [PaperMC/Paper#4616]
Using "addPassenger()" within the CreatureSpawnEvent leads to a server crash.
With the latest Spigot version (git-Spigot-988b411-aa8206a (MC: 1.16.3)) I could not reproduce the error.

### Link/paste of stack trace
[latest.log](https://github.com/PaperMC/Paper/files/5323032/latest.log)
[crash-2020-10-04_12.38.30-server.txt](https://github.com/PaperMC/Paper/files/5323031/crash-2020-10-04_12.38.30-server.txt)

### Plugin list:
Only my own plugin with which I noticed the bug.

### Actions to reproduce (if known):
    @EventHandler
    public void onCreatureSpawnEvent(CreatureSpawnEvent e) {
        if (e.getEntity() instanceof Spider) {
            Entity creeper = e.getEntity().getWorld().spawnEntity(e.getEntity().getLocation(), EntityType.CREEPER);
            e.getEntity().addPassenger(creeper);
        }
    }

### Paper version:
This server is running Paper version git-Paper-214 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by mrfloris** [comment]
Thank you @Proximyst
