### ISSUE TITLE
Placing blocks in off-hand is unreliable when holding a tool/food in main-hand

### ISSUE THREAD

**Issue by zedwick** [PaperMC/Paper#462]
# Incompatibility (Bug)

### What behaviour is expected:
Blocks should be placed as intended, and not disappear nor have the items returned to inventory.
### What behaviour is observed:
blocks placed from off-hand will unreliably place when placed in quick succession whilst holding a tool in main hand.
### Steps/models to reproduce:
Hold sword in main hand
hold dirt in off hand
run backwards placing blocks (holding right-click)

### Plugin list:
No plugins

### Paper build number:
This seems to affect version 863+, not present in 862
This server is running Paper version git-Paper-863 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
This server is running Paper version git-Paper-908 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Also testing using latest version of Spigot, which does not have this issue:
This server is running CraftBukkit version git-Spigot-72c2605-33071ec (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by WonderDave** [comment]
Confirmed, although I'd never noticed this before.  You can see this happen even without moving by standing in the middle of a block on level ground, aiming at the ground at least two blocks in front of you, and then holding down the right mouse button just long enough to place two dirt blocks (or any type of block).  The first block will place, then the second block will place, but then that second block will instantly disappear.  It happens for me every single time as long as I am holding something (anything) in the main hand.

**Comment by zachbr** [comment]
Should be resolved in builds 909+
Please confirm.

**Comment by RoboMWM** [comment]
Confirmed

**Comment by zedwick** [comment]
Confirmed fixed, thanks!
