### ISSUE TITLE
Random Dark Spots on New Chunks and Existing Chunks

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4623]
### What behaviour is expected:
___Normal Terrain Lighting on the Surface___

### What behaviour is observed:
___Dark Spots scattered across the Land___

### Steps/models to reproduce:
___Create A world
Fly around___

### Plugin list:
___EssentialsX (core, chat, spawn, geoip)
LaggRemover
AdvancedNMotd
LuckPerms
Vault___

### Paper version:
___This server is running Paper version git-Paper-216 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)___

### Anything else:

- The startup parameters "--forceUpgrade --eraseCache" has been tested and has no effect on Paper, it just makes more dark spots while removing the old ones. However, testing with vanilla fixed all of the dark spots.
- Has been tested without any plugins and problem still persists.
- World was corrupted in the past but was recovered. All world tools show no issues prior and after being ran on Paper. 
- This looks like as if there's a platform above that area, when there's not.

___Screenshots___
https://imgur.com/a/njZjR0A

**Comment by ghost** [comment]
Curious on what this a duplicate of. Couldn't find anything related. I've seen other people's lighting bugs but they aren't exactly the same.

**Comment by electronicboy** [comment]
This is already a known issue and has been posted in the announcements channel on discord a while back, as well as I'm pretty sure there is another potentially few tickets around this general issue of the lighting system kicking itself

**Comment by ghost** [comment]
Ah alright. Thanks for the reply. Was worried about this as I had world corruption not so far back.
