### ISSUE TITLE
Reimplement the Player Collision option 

### ISSUE THREAD

**Issue by TheShermanTanker** [PaperMC/Paper#4627]
Currently the option `enable-player-collisions` which causes entity/player collisions to revert to how they used to work before 1.9, is implemented by actually creating a new scoreboard team on the scoreboard, and adding Players to the team to disable the collisions. This can cause issues when Players attempt to use scoreboard team commands with that option enabled, and I instead suggest for it to be implemented directly inside the method responsible for collision logic, rather than through a scoreboard.
At net.minecraft.server.MinecraftServer, line 454
```

// Paper start - Handle collideRule team for player collision toggle
        final Scoreboard scoreboard = this.getScoreboard();
        final java.util.Collection<String> toRemove = scoreboard.getTeams().stream().filter(team -> team.getName().startsWith("collideRule_")).map(ScoreboardTeam::getName).collect(java.util.stream.Collectors.toList());
        for (String teamName : toRemove) {
            scoreboard.removeTeam(scoreboard.getTeam(teamName)); // Clean up after ourselves
        }

        if (!com.destroystokyo.paper.PaperConfig.enablePlayerCollisions) {
            this.getPlayerList().collideRuleTeamName = org.apache.commons.lang3.StringUtils.left("collideRule_" + java.util.concurrent.ThreadLocalRandom.current().nextInt(), 16);
            ScoreboardTeam collideTeam = scoreboard.createTeam(this.getPlayerList().collideRuleTeamName);
            collideTeam.setCanSeeFriendlyInvisibles(false); // Because we want to mimic them not being on a team at all
        }
        // Paper end
```

<img width="960" alt="2020-10-08 (1)" src="https://user-images.githubusercontent.com/32636402/95458832-55487d80-09a5-11eb-9ccd-c8261f3b39cc.png">

**Comment by electronicboy** [comment]
Player collisions happen on the client, not the server; Making changes to the servers collision code will have 0 impact here
