### ISSUE TITLE
Crash caused by scoreboard modification

### ISSUE THREAD

**Issue by Faxed** [PaperMC/Paper#463]
**Issue:**
Every day now, since updating PaperSpigot, the server crashes - It's the same issue each time, in that it complains that a team already exists (of which leads to a crash). 

Whilst I initially believed it to be a plugin, I went through and checked everything that was updated that day - Two plugins and PaperSpigot (with the two plugins not even touching the scoreboard). 

**Crash Report:** http://pastebin.com/AuLhP54S

**Versions Tried:**
So far as we can see, the issue isn't present on build 842 - Of which we were using for a number of weeks (having no issues with versions before that either). However, upon updating to build 902 we've found that every day (like clockwork) the server crashes - Creating a crash report identical to the one linked above. 

We've tried various versions between 842 and after 902, but the issue still persists - It's generally a long thing to test for, given that it usually takes around a day to appear (maybe less).

**Comment by zachbr** [comment]
Hmm looks like a team wasn't removed at shutdown at some point. This can be caused by an unsafe shutdown of the server.

I'll check into a solution like removing any old ones at startup.

**Comment by Faxed** [comment]
It's really a self-perpetuating cycle in a way - Our first port of call was clearing the scoreboard data completely when we shutdown the server, we started the server again and things seemed fine; but a crash eventually happened on the same day, I do believe. 

Just as an addendum, so to speak.

**Comment by AlfieC** [comment]
Could band-aid it by just using `getOrCreate`

**Comment by zachbr** [comment]
@AlfieC only issue with that is it could still result in lots of random crap teams filling up the scoreboard :(

**Comment by zachbr** [comment]
Builds 910+ should prevent this from happening.
They will also cleanup any and all of the teams that may have gotten left behind in the past.
