### ISSUE TITLE
Paper Anti X-Ray 1.16 Blocks Visual Glitch

### ISSUE THREAD

**Issue by D3adhkwen** [PaperMC/Paper#4630]
### What behaviour is expected:
There shouldn't be any visual glitch just like non-1.16 blocks
![image](https://user-images.githubusercontent.com/38313757/95544716-8ae57900-0a2e-11eb-9dc5-bcb7dd06059c.png)

### What behaviour is observed:
![image](https://user-images.githubusercontent.com/38313757/95544591-29bda580-0a2e-11eb-872f-0483a6c6f11e.png)
![image](https://user-images.githubusercontent.com/38313757/95544774-b0728280-0a2e-11eb-90d4-2ddf1a825b9c.png)
![image](https://user-images.githubusercontent.com/38313757/95544695-7903d600-0a2e-11eb-8ff7-25d6d599c4c2.png)

### Steps/models to reproduce:
1. Put a bed on any blocks
2. The blocks u wake up to must be any 1.16 blocks
3. Sleep on the bed and leave bed
![image](https://user-images.githubusercontent.com/38313757/95544829-da2ba980-0a2e-11eb-9cd7-79789a9d3971.png)

### Plugin list:
![image](https://user-images.githubusercontent.com/38313757/95544363-7a80ce80-0a2d-11eb-845f-644e8a549e7b.png)

### Paper version:
![image](https://user-images.githubusercontent.com/38313757/95544860-e6b00200-0a2e-11eb-8a15-20ec9bc0946b.png)

### Anything else:
It sometimes happen without sleeping too (could be lag)
![image](https://user-images.githubusercontent.com/38313757/95544899-0515fd80-0a2f-11eb-91aa-67d282be09e2.png)

Settings of Anti X-Ray:
![image](https://user-images.githubusercontent.com/38313757/95545056-6d64df00-0a2f-11eb-84bd-7c3aef22cd9a.png)
![image](https://user-images.githubusercontent.com/38313757/95545080-781f7400-0a2f-11eb-91f9-06aefd8d71f8.png)

**Comment by Proximyst** [comment]
Reproduce without plugins, ESPECIALLY plugins like ViaVersion.

**Comment by D3adhkwen** [comment]
Thanks, found the problem to be with Spartan anti-cheat. Sorry for the inconvenience.
