### ISSUE TITLE
PlayerPortalEvent isn't Triggered

### ISSUE THREAD

**Issue by coco0325** [PaperMC/Paper#4632]
# What behaviour is expected:
PlayerPortalEvent being triggered.

### What behaviour is observed:
PlayerPortalEvent not being triggered after upgrade to 1.16.3 (It working in 1.15.2).
p.s. There's no nether world in the server.

### Steps/models to reproduce:
Build a nether portal and use plugin to listen the event.

### Paper version:
Paper 1.16.3 216

**Comment by ykgamma** [comment]
Also seeing this issue with paper version 1.16.4 324.
Nether is disabled.

**Comment by DarkArc** [comment]
So I looked into this and it's going to be awkward to fix. The new logic requires a destination world, and requires it to be a nether world for proper control flow.

I suspect people are trying to use this override the default nether portal functionality (please say something if that's not the case). Assuming that's true, it might be a better fix (granted not backwards compatible) to have a cancellable `NetherPortalReadyEvent` with a nullable destination world.

Then you could just have your plugin code be something like:

```
@EventHandler(ignoreCancelled = true)
public void onNetherPortalReady(NetherPortalReadyEvent event) {
  if (/*this is not a custom portal*/) {
    return;
  }
  
  // Block the portal teleport
  event.setCancelled(true);
  
  // Send entity on its way
  Location dest = // figure out where we want to go
  event.getEntity().teleport(dest, PlayerTeleportEvent.TeleportCause.NETHER_PORTAL);
}
```

Edit: Or just `PortalReadyEvent` so it can also accommodate end portals?

**Comment by eUipKh** [comment]
Any updates on this?
