### ISSUE TITLE
Hopper mine carts are not picking up items consistently through a solid block.

### ISSUE THREAD

**Issue by surfrock66** [PaperMC/Paper#4633]
### What behavior is expected:
Hopper Minecarts should pick up items through a magma block when over regular or powered rails

### What behavior is observed:
Hopper minecarts do NOT pick up items through magma block and occasionally other blocks.  We have experienced this on dirt (on one layer of a 3-layer melon/pumpkin farm) as well, though the dirt issue was fixed by replacing the minecart.  We consistently see this issue through magma in our slime farm.

Other farms are working fine, the issue is completely inconsistent and we cannot pinpoint a consistent cause.  The slime farm with items being pulled through magma at Y=6 is the most consistent example of this behavior. 

### Steps/models to reproduce:
Build a slime farm with the magma layer happening at Y=6, then a hopper-minecart rail collection happening under it at Y=5.  Items will consistently rest on top of the block layer.  The minecart hopper has been confirmed to be empty.

### Plugin list:
All plugins disabled for testing.  We normally use EssentialsX, GriefPrevention, Multiverse Core, Vault, Dynmap, BBOutlineReloaded and LuckPerms

### Paper version:
This issue has persisted for some time, since 1.16.1, however this is the version we are on today
[13:22:31 INFO]: This server is running Paper version git-Paper-209 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[13:22:31 INFO]: Previous version: git-Paper-168 (MC: 1.16.2)
[13:22:31 INFO]: You are 11 version(s) behind

### Anything else:

[spigot.yml.txt](https://github.com/PaperMC/Paper/files/5357357/spigot.yml.txt)
[paper.yml.txt](https://github.com/PaperMC/Paper/files/5357358/paper.yml.txt)
[bukkit.yml.txt](https://github.com/PaperMC/Paper/files/5357359/bukkit.yml.txt)

![2020-10-09_13 16 24](https://user-images.githubusercontent.com/1345467/95628295-976bd080-0a32-11eb-88bd-a2ed0576135c.png)
![2020-10-09_12 43 04](https://user-images.githubusercontent.com/1345467/95628311-9d61b180-0a32-11eb-8e41-33460785fdac.png)

**Comment by chlorophant** [comment]
Has this been fixed? I'm still experiencing it
