### ISSUE TITLE
Off-hand Items disappearing

### ISSUE THREAD

**Issue by Luysita** [PaperMC/Paper#464]
### Description of issue:
Hello, two of my players reported that when they die, the items that were in the shield slot just disappeared.
I don't usually use that slot, or I don't think most of the players do, so the bug wasn't reported until now.
Same happened with the build #899.
Thank you.

### Plugin list:
[INFO] Plugins (11): AntiWDL, CoreProtect, PermissionsEx, DeluxeChat, dynmap, WorldEdit, WorldBorder, NoPl, OpenInv, NeosNoExplosion, AWD

### Paper build number:
[INFO] This server is running Paper version git-Paper-909 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by mikroskeem** [comment]
> when they die, the items that were in the shield slot just disappeared.

`/gamerule keepInventory true`?

Does this problem still exist?

**Comment by zachbr** [comment]
Closing due to how old this bug is, if it still exists on latest please re-report.
