### ISSUE TITLE
Invalid discord invite in paper.yml

### ISSUE THREAD

**Issue by NotMyFault** [PaperMC/Paper#4643]
### What behaviour is expected:
Better use https://discord.gg/papermc over https://paperdiscord.emc.gs

### What behaviour is observed:
https://paperdiscord.emc.gs seems to be dead for some while

### Steps/models to reproduce:
Start a server to generate the paper.yml

### Plugin list:
/

### Paper version:
This server is running Paper version git-Paper-228 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

### Anything else:
/

**Comment by aikar** [comment]
I have fixed the link so itll at least work, and well update the readme soon.
Please no one PR this as we are not taking PR's like this during October.

One of us will get it later.

**Comment by NotMyFault** [comment]
> Please no one PR this as we are not taking PR's like this during October.

Thanks & hence I didn't come up with a pr for this one.
