### ISSUE TITLE
server crashes when going to a certain area in the map

### ISSUE THREAD

**Issue by ThePro1604** [PaperMC/Paper#4644]
let me start of by saying that I know it says this is not paper related but I'm lost for advice I tried posting on a few other forum for help and no one was able to figure out the problem pls help with this.
when ever someone is walking near the pigmen farm in the nether the server experience huge lag spike that most of the time crashes the server while the lag happening the chat stays active but the rest of the game mechanism are frozen.

This server is running Paper version git-Paper-206 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

the plugin we have on are:

CoreProtect

ClearLag

DeepVanish

HebrewFix

all the plugins are on the latest version

this is the crash log when the server crashes

https://pastiebin.com/5f846d476eee7

**Comment by Proximyst** [comment]
Barry brought his family over. 🐝

Quite simply put, you've got too many bees. Please join our Discord or `#paper-help` on `irc.spi.gt` for any further crashes, as it does say not to report it to Paper.
