### ISSUE TITLE
Item data changing when stored and saved

### ISSUE THREAD

**Issue by reimannsum** [PaperMC/Paper#4647]
[10:53:41 INFO]: This server is running Paper version git-Paper-138 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[10:53:41 INFO]: Checking version, please wait...
[10:53:41 INFO]: Previous version: git-Paper-136 (MC: 1.16.1)
[10:53:41 INFO]: You are running the latest version

### What behaviour is expected:
Redstone wrench to work after being stored (carrot on a stick item with special tags)

### What behaviour is observed:
I was using the redstone wrench datapack from vanilla tweaks. the wrench works but after being put in I believe any chest, could just be shulker boxes and ender chests. The wrench no longer works.

chests/shulkers do not do this while I am around/they are loaded. so ender chests I thought fixed this for a while but that was because I hadn't logged off. I think

### Steps/models to reproduce:
- make a wrench (G= gold ingot, I iron ingot)
. G .
. G G
I . . 
- put in chest/shulker/ender chest/shulker in ender chest
-save server
-restart server
-check that each one still rotates redstone items, shift + right clicking things that can normally be right clicked.

### Plugin list:
None

### Paper version:
10:53:41 INFO]: This server is running Paper version git-Paper-138 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[10:53:41 INFO]: Checking version, please wait...
[10:53:41 INFO]: Previous version: git-Paper-136 (MC: 1.16.1)
[10:53:41 INFO]: You are running the latest version

### Anything else:
Here is a test world for this issue exactly with wrenches that have stopped working when this has happened. so there should be a difference in data between the wrenches already spawned there and the data of a newly made wrench
[world.zip](https://github.com/PaperMC/Paper/files/5372518/world.zip)

**Comment by Proximyst** [comment]
Reproduce on 1.16.3.

**Comment by HexedHero** [comment]
1.16.1 KEKW

**Comment by aurorasmiles** [comment]
> 1.16.1 KEKW

Please refrain from comments like that, they contribute nothing and are just annoying. We can meme on discord

**Comment by reimannsum** [comment]
[12:55:59 INFO]: This server is running Paper version git-Paper-229 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[world(1).zip](https://github.com/PaperMC/Paper/files/5372934/world.1.zip)

Tested again 

upon first restart:
- wrenches in invintory and in blue shulker still worked. 
- wrenches in grey shulker (in ender chest) and one in ender chest did not work
- wrenches in yellow shulker box (in chest) and one in chest did not work

second restart was to test if wrenches on ground during restart would still work

- wrenches on ground, picked up after restart did not work
- wrench in blue shulker no longer worked

**Comment by reimannsum** [comment]
@Proximyst  tested on 1.16.3

**Comment by BillyGalbreath** [comment]
Works As Intended.

Paper reorders tags (like enchantments and stuff) alphabetically. This reordering breaks a few vanilla mechanics like item stacking due to the itemstack comparison check failing.

It's been brought up a few times and the resolution has always been Works As Intended.

(Edit) To clarify: Paper's stance is for plugins and datapacks to properly order their tags alphabetically. (See the fiasco with the chinese per player view distance plugin)

**Comment by electronicboy** [comment]
If it is tag reordering, this is working as intended, the issue is the nature of "fix one thing, break 20 others", we should consider looking into if this can be done more "enthusiastically", but would need to be weary about performance here

**Comment by HexedHero** [comment]
Another reason to use NBT

**Comment by BillyGalbreath** [comment]
> Another reason to use NBT

Shhh! You cant say that around the devs! NBT is implementation detail! We cant have regular users seeing or using NBT! /s
