### ISSUE TITLE
Instant mining does not function as intended

### ISSUE THREAD

**Issue by HypixionGaming** [PaperMC/Paper#4651]
### What behaviour is expected:
normal instant mining

### What behaviour is observed:
stone reappearing

### Steps/models to reproduce:
https://www.youtube.com/watch?v=aFozd_QdxeA

### Plugin list:
Harbor, IllegalStack, LiteBans, LuckPerms, ProtocolLib, Shrug*

### Paper version:
git-Paper-223 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

### Anything else:
Nope, just that forgive me if i did something wrong this is my first report! & this is only happens with stone blocks

**Comment by aikar** [comment]
Not seeing what is supposed to be the issue in the video? looks normal to me.

**Comment by Proximyst** [comment]
This is a side-effect of anti-xray. Nothing new, but I've no real idea about what may help with it. Perhaps @stonar96 might be of help here?

**Comment by chrisstar321** [comment]
The diorite just mines like normal, but the stone blocks disappear, reappear and disappear again

**Comment by HypixionGaming** [comment]
> 
> 
> The diorite just mines like normal, but the stone blocks disappear, reappear and disappear again

exactly what this gentleman said

**Comment by stonar96** [comment]
> Perhaps @stonar96 might be of help here?

I think I can't be helpful here aside from obvious solutions:

- Disable Anti-Xray.
- Use `engine-mode: 1` instead of `engine-mode: 2`.
- Use `update-radius: 1` instead of `update-radius: 2`.

Of course, all of these solutions have drawbacks.

**Comment by Proximyst** [comment]
Did stonar's suggestions have any effect?
