### ISSUE TITLE
Load new data pack from file (directory or zip)

### ISSUE THREAD

**Issue by orblazer** [PaperMC/Paper#4654]
**Is your feature request related to a problem? Please describe.**
This feature is great for custom loot table and provide it by plugin and not by default world.

**Describe the solution you'd like**
An method like `Bukkit.loadDataPack(NamespacedKey, File)` (first is key of data pack and second if file or data pack).

**Describe alternatives you've considered**
I have try to solve the loot table solution via NMS but this is really hard to make it.
Also i think just an method like `Bukkit.loadLootTable(NamespacedKey, File)` (with file is the json of loot table), could be great.

**Comment by webcrawls** [comment]
Would love this as well, but AFAIK it would be a lot of work to properly add datapack support to Bukkit

**Comment by orblazer** [comment]
@bluelyDev hum i have look inside minecraft code and for me this is not too much work for add an new directory for load data pack and for dynamic load this need re instantiate the resource manager in MinecraftServer or just "reflection" for push the pack in the map (i have try this and this could be work but in reflection its a pain for add it and reload)

**Comment by Nolij** [comment]
I would love a feature like this as it would allow for much easier creation of advancements and loot tables.
