### ISSUE TITLE
Entity Collisions are Broken

### ISSUE THREAD

**Issue by RedZephon** [PaperMC/Paper#4655]
### What behaviour is expected:
- Players should be able to interact/"nudge" entities.
- Entity collision should be enabled and working

### What behaviour is observed:
- Entity Collision is disabled
- Players pass through entities as if they are invisible

### Steps/models to reproduce:
- Load a Paper Server
- Attempt to push an entity
- Realize entities think you are invisible and that you can't push/move them
- Become sad that you are truly alone in Minecraft

### Plugin list:
These are the plugins from my Prod server, however in my testing I booted up a local dev server with no plugins, just paper, and I still had the issue.

  | Advanced-Portals-0.5.8-snapshot.jar | 107.41kB | 10/02/20 19:37:53 |  
  | AntiAFKPlus-3.02.jar | 443.9kB | 08/07/20 04:32:12 |  
  | Autorank-4.4.jar | 759.77kB | 08/11/20 00:07:40 |  
  | BetterSleeping.jar | 136.77kB | 09/01/20 16:36:13 |  
  | BigDoors (1).jar | 570.08kB | 08/07/20 04:32:12 |  
  | BottledExp2.2.8.1.jar | 316.16kB | 10/02/20 19:44:33 |  
  | BuycraftX.jar | 1.11MB | 08/07/20 04:32:13 |  
  | ChestSort.jar | 118.99kB | 10/02/20 19:37:53 |  
  | Citizens-2.0.27-b2120.jar | 3.99MB | 09/23/20 03:47:30 |  
  | ClueScrolls-4.0.8.jar | 1.12MB | 10/04/20 23:53:44 |  
  | CoreProtect-19.2.jar | 466.78kB | 10/02/20 19:38:36 |  
  | CustomSkinsManager-3.4.1-min.jar | 2.92MB | 10/09/20 18:40:03 |  
  | DeluxeCommands-1.11.1.jar | 42.21kB | 10/04/20 23:58:16 |  
  | DeluxeMenus-1.13.3-Release.jar | 142.46kB | 10/04/20 23:59:19 |  
  | DiscordSRV-Build-1.20.1-SNAPSHOT-1601870253.jar | 8MB | 10/04/20 23:58:18 |  
  | Dynmap-3.1-beta4-spigot.jar | 6.85MB | 10/02/20 19:37:54 |  
  | Dynmap-Essentials-0.91.jar | 22.84kB | 08/07/20 04:32:13 |  
  | Dynmap-GriefPrevention-0.80.jar | 20.64kB | 08/07/20 04:32:13 |  
  | Dynmap-WorldGuard-1.2.jar | 21.54kB | 08/07/20 04:32:13 |  
  | EcoEnchants v5.0.0-beta25.jar | 579.02kB | 10/11/20 20:57:00 |  
  | EpicWorldGenerator-8.1.34.jar | 3.17MB | 10/07/20 03:20:42 |  
  | EssentialsX-2.18.1.24.jar | 1.6MB | 10/13/20 22:19:52 |  
  | EssentialsXGeoIP-2.18.1.24.jar | 1.66MB | 10/13/20 22:19:49 |  
  | EssentialsXSpawn-2.18.1.24.jar | 16.89kB | 10/13/20 22:19:49 |  
  | Expansion-Parkour.jar.disabled | 4.97kB | 08/07/20 04:32:14 |  
  | floodgate-bukkit-2.jar | 8.13MB | 08/07/20 04:46:31 |  
  | FloodgatePlaceholders-1.1.jar | 1.99MB | 08/19/20 00:34:37 |  
  | Geyser-Spigot-7.jar | 16.48MB | 10/13/20 22:20:28 |  
  | Graves.jar | 63.77kB | 08/07/20 04:32:13 |  
  | GriefPreventionFlags-5.9.1.jar | 201.61kB | 08/07/20 04:32:14 |  
  | GriefPrevention.jar | 296.45kB | 10/02/20 19:37:52 |  
  | HolographicDisplays.jar | 522.14kB | 10/02/20 19:37:52 |  
  | HolographicPlaceholders-2.1.0 Stable.jar | 235.01kB | 10/04/20 23:53:37 |  
  | images-2.1.4.jar | 183.15kB | 08/25/20 18:28:23 |  
  | ItemsAdder (3).jar | 1.03MB | 10/11/20 20:57:00 |  
  | LeaderBalloons.jar | 0.92MB | 10/09/20 18:40:07 |  
  | LeakParkour.jar | 659.87kB | 10/09/20 18:40:04 |  
  | LightAPI-fork-3.4.5.jar | 123.21kB | 09/23/20 03:36:36 |  
  | LitePlaytimeRewards-2.4.2.jar | 115.69kB | 08/23/20 16:56:38 |  
  | LoneLibs.jar | 4.49MB | 09/23/20 03:36:35 |  
  | LuckPerms-Bukkit-5.1.93.jar | 1.34MB | 10/02/20 19:37:51 |  
  | MCBouncer.jar.disabled | 3.25MB | 10/11/20 19:41:29 |  
  | mcMMO-2.jar.disabled | 1.44MB | 08/07/20 04:39:28 |  
  | MineableSpawners-3.0.8.jar | 386.34kB | 10/02/20 19:37:51 |  
  | Multiverse-Core-4.1.1-SNAPSHOT.jar | 466.23kB | 08/07/20 04:57:35 |  
  | nuvotifier-2.7.1.jar | 2.72MB | 08/07/20 04:32:17 |  
  | Parkour.jar.disabled | 295.59kB | 08/07/20 04:32:14 |  
  | PlaceholderAPI-2.10.9.jar | 395.55kB | 08/07/20 04:57:38 |  
  | Plan-5.1-build-657.jar | 16.51MB | 08/25/20 18:28:24 |  
  | PlayerReport.jar | 35.59kB | 08/07/20 04:32:15 |  
  | PluginManager.jar | 28.43kB | 08/10/20 03:02:06 |  
  | ProtocolLib (5).jar | 1.29MB | 10/11/20 20:57:02 |  
  | Referral_1.10.jar | 60.77kB | 10/02/20 19:37:51 |  
  | serverlist-plugin.jar | 17.02kB | 08/07/20 04:32:16 |  
  | Shopkeepers-2.11.0.jar | 0.96MB | 08/25/20 18:28:24 |  
  | Statz-1.6.jar | 864.76kB | 08/23/20 18:22:07 |  
  | TAB v2.8.4.jar | 523.18kB | 08/25/20 18:28:25 |  
  | TradeSystem_v1.2.1.jar | 732.46kB | 10/09/20 18:40:04 |  
  | UltimateVotes.jar | 184.93kB | 10/02/20 19:37:50 |  
  | Vault (1).jar | 265.88kB | 09/23/20 03:36:35 |  
  | VentureChat (1).jar | 384.02kB | 08/25/20 18:39:39 |  
  | ViaBackwards-3.1.1.jar | 768.59kB | 09/10/20 15:32:20 |  
  | ViaVersion-3.1.1.jar | 4.13MB | 09/10/20 15:32:22 |  
  | VoxelSniper-6.1.2.jar | 2.3MB | 08/07/20 04:32:16 |  
  | WorldBorder.jar | 146.12kB | 10/15/20 15:30:19 |  
  | WorldGuardExtraFlags.jar | 144.33kB | 10/03/20 00:57:30 |  
  | worldedit-bukkit-7.2.0-SNAPSHOT-dist (2).jar | 4.09MB | 10/03/20 01:01:03 |  
  | worldguard-bukkit-7.0.5-SNAPSHOT-dist.jar

### Paper version:
>....=>.... [05:19:35 INFO]: This server is running Paper version git-Paper-231 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
>.... [05:19:35 INFO]: Checking version, please wait...
>.... [05:19:36 INFO]: You are running the latest version

### Anything else:

So when my players started complaining about this issue, I had just updated Paper and a couple plugins. I started disabling plugins 1 by 1 to find the issue (assuming it was a plugin). Then I disabled all plugins, collisions turned back on. So I started going 1 by 1, enabling plugins. Collisions got disabled when I turned on Custom Skins Manager. So I disabled that plugin, rebooted, thinking I solved the problem.

After a reboot, collisions are still disabled...so I kept checking plugins and couldn't get them to turn back on.

Then I copied over all my plugins, but not the configs, to a dev server. Booted it up, collisions disabled. Removed all plugins and rebooted with just PaperMC, no collisions. Then I removed all files, downloaded a fresh copy of paper, booted up, no collisions. So I have no idea what's going on but latest version has broken collisions for me. I've checked paper.yml to make sure collisions are enabled, and they are.

**Comment by HexedHero** [comment]
Works fine for me.

**Comment by RedZephon** [comment]
That’s cool, but I’m telling you it doesn’t.

**Comment by HexedHero** [comment]
And I'm telling you that it's a you problem. No need to be an arse.

**Comment by RedZephon** [comment]
I’m not being an arse. I started a brand new unaltered paper server and got these errors. I asked for support in discord and they advised me paper is probably broken and to make a post here. They also said you would say I’m wrong and that it actually isn’t broken. So please advise me why it’s not broken before saying it is because I’ve troubleshooted with your support team in discord and I’ve tested with a brand new unaltered paper server.

**Comment by HexedHero** [comment]
https://i.imgur.com/7MxOvU5.mp4

Normally if it works for someone else and not you, you should double-check your setup like paper.yml etc and plugins instead of doing nothing.

**Comment by RedZephon** [comment]
You clearly didn’t read my post. I have troubleshooted extensively on 2 servers. 

First I went through 1by1 on all my plugins disabling and enabling them to try and see if it was an issue with plugins. Then i disabled all plugins. 

Then I created a brand new 2nd server with a fresh copy of paper and a brand new paper.yml (with no plugins installed!!) and it still didn’t work. 

I checked the settings in paper.yml to ensure that entity collision is turned on and it is. 

I have spent days troubleshooting and getting support in the discord and they agreed that it is a paper issue. So instead of telling me why I’m wrong, ask more questions that lead to a resolution.

**Comment by Proximyst** [comment]
Let's keep civil.

Did you clear your player data when you "deleted all files"?
Did you clear your world data?
Did you try this without any plugins whatsoever and binary search when adding back?

**Comment by aikar** [comment]
You narrowed it to initially being plugin oriented.

It sounds like that plugin has modified your world state in some way that it is persisting even when the plugin is removed.

There isn't much we can do there without knowing what the plugin did....

**Comment by RedZephon** [comment]
I erased all files, worlds, plugin data, etc, and installed paper from scratch on a test server, booted up and didn't get collisions. The only thing that would make any kind of sense would be the server hardware/host preventing it somehow as that's the only thing that's consistent at this point.

**Comment by webcrawls** [comment]
If you can reproduce this on a **fresh** install of Paper (not your current installation with a wiped world, but a completely new one), and provide reproduction steps, then we'll be able to help you

**Comment by BillyGalbreath** [comment]
Zip up your entire server directory you're testing this on and post it here so we can experience this, too. Cause right now none of us are able to recreate this following the exact steps you've given.

**Comment by BillyGalbreath** [comment]
Guess you found the issue and fixed it? ;)

**Comment by webcrawls** [comment]
I (along with another guy) helped him out with it in the SpigotMC Discord. Turns out it was LeakParkour creating a scoreboard team to remove collisions.

**Comment by HexedHero** [comment]
So much for a fresh server test
