### ISSUE TITLE
Paper server: "Failed to read chunk data"

### ISSUE THREAD

**Issue by realS1NgL3** [PaperMC/Paper#4660]
### Link/paste of stack trace Failed to read chunk data for task: Task for world: 'Main World' at -54,14 poi: false, hash: 1506773362
net.minecraft.server.v1_16_R2.ReportedException: Loading NBT data
at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:475) ~[minecraft_server.jar:git-Paper-238]
at net.minecraft.server.v1_16_R2.NBTTagCompound.access$200(NBTTagCompound.java:27) ~[minecraft_server.jar:git-Paper-238]

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list: Skin restorer
___A list of your plugins___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper version: newest
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

**Comment by Proximyst** [comment]
Fill out the template.

If this is on b234, update and restore from a backup. If you have no backup, you're shit outta luck.

**Comment by realS1NgL3** [comment]
Any solution?

**Comment by realS1NgL3** [comment]
Failed to read chunk data for task: Task for world: 'Main World' at -54,14 poi: false, hash: 1506773362
net.minecraft.server.v1_16_R2.ReportedException: Loading NBT data
at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:475) ~[minecraft_server.jar:git-Paper-238]
at net.minecraft.server.v1_16_R2.NBTTagCompound.access$200(NBTTagCompound.java:27) ~[minecraft_server.jar:git-Paper-238]

**Comment by Proximyst** [comment]
If this is on b234, update and restore from a backup. If you have no backup, you're shit outta luck.

**Comment by realS1NgL3** [comment]
I have the backup, but it keeps happening again.

**Comment by realS1NgL3** [comment]
I hope half of my new house will not dissapear
:/
