### ISSUE TITLE
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server

### ISSUE THREAD

**Issue by NESTOWL** [PaperMC/Paper#4666]
### Link/paste of stack trace
https://pastebin.com/7FDZwXMT
### Plugin list:
![cmd_bajdq5anrh](https://user-images.githubusercontent.com/45520187/96367274-853a1280-1155-11eb-9556-f33001081492.png)
### Actions to reproduce (if known):
when connected to server
### Paper version:
240

**is it worth worrying about?**

**Comment by Proximyst** [comment]
Auth servers are down.
