### ISSUE TITLE
Chunk Glitch

### ISSUE THREAD

**Issue by Vulnerab1lity** [PaperMC/Paper#4667]
### What behaviour is expected:
There should be grass but instead there are weird blocks

### What behaviour is observed:
Weird chunk glitch

### Steps/models to reproduce:
I don't know how to reproduce that, it just appeared

### Plugin list:
![wadw](https://user-images.githubusercontent.com/42952817/96369217-f7f8bd00-1158-11eb-9087-53bfebe3fcb1.png)

### Paper version:
Client version: 1.16.3 vanilla
Server version: Paper-232 1.16.3

### Anything else:
I restarted the server and it was gone.
If i interact with these glitched blocks, they turn normal again.
It's client sided
![2020-10-18_15 21 02](https://user-images.githubusercontent.com/42952817/96369223-ff1fcb00-1158-11eb-9861-57a7ef327069.png)

**Comment by Proximyst** [comment]
I'm sorry, you point out this is client sided yet report it? Am I missing something?

Can you reproduce this without plugins (specifically those which interact with networking)?

**Comment by Vulnerab1lity** [comment]
It happend on someone else's device too it's the server

**Comment by Vulnerab1lity** [comment]
It's gone and I don't know how to reproduce it after I restarted the server

**Comment by Proximyst** [comment]
In that case, I'll close the issue. It's most likely just a plugin messing up (in which case, update them all).
