### ISSUE TITLE
CustomColors for Console

### ISSUE THREAD

**Issue by TheMagBum** [PaperMC/Paper#4668]
**Is your feature request related to a problem? Please describe.**
if you customize the chat with customColors it will not look so nice in the console, maybe you could also customize the console for costom colors

**Describe the solution you'd like**
That the Console also supports the new CustomColors

**Describe alternatives you've considered**
Keep it that way?

**Additional context**
![image](https://user-images.githubusercontent.com/45709417/96369771-12806580-115c-11eb-8124-3b8679d2612f.png)

**Comment by Prof-Bloodstone** [comment]
There is a PR for adding that, just there is still discussion on how to handle it best.

See: https://github.com/PaperMC/Paper/pull/4221
There is also a linked issue opened on the TCA repo which is what Paper uses for console.

Also pretty sure there was an issue created for that, but can't find it on my phone :/

**Comment by Chew** [comment]
https://github.com/Minecrell/TerminalConsoleAppender/pull/17

**Comment by BillyGalbreath** [comment]
I've been using #4221 for awhile now and it works great if you don't mess with the ansi/jline arguments ;)
