### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Xayanix** [PaperMC/Paper#4671]
https://pastebin.com/raw/SuVJTsG3

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
PlotSquared

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

paper-211 1.16.3

**Comment by HexedHero** [comment]
Not 100% sure so I apologise but I think you have a player(s) flying fast and loading a lot of chunks.

**Comment by Xayanix** [comment]
I limited player's max speed already

**Comment by electronicboy** [comment]
Need the full set of logs, at least to before a minute or so before the warnings started spewing, that report is basically 100% useless as-is

**Comment by Xayanix** [comment]
https://pastebin.com/raw/vQYcNBtD

**Comment by electronicboy** [comment]
chunk load stall due to lighting system stall, well-known issue at this point

**Comment by electronicboy** [comment]
and on that note, update, there have been further improvements to this over the past week or two so I recall.

**Comment by Xayanix** [comment]
Still happens on Paper-240
