### ISSUE TITLE
NMS causes the server to crash and will not restart

### ISSUE THREAD

**Issue by botany111** [PaperMC/Paper#4675]
https://pastebin.com/AtLKVehW

Plugins (66): AAC, AlwaysBed*, antiRedstoneClock, BBeeChecker, BlockLocker, BungeeGuard, Chair, Chunkmaster, ChunkSpawnerLimit, ClaimFly, CommandPanels, ConsoleSpamFix, CoreProtect, CrystalDisabler*, DiscordSRV, Elevator, EntityDetection, Essentials, EssentialsSpawn, FastLeavesDecay, GPTeleport, GriefPrevention, GriefPreventionFlags, Guilds, HeadDatabase*, HolographicDisplays, IllegalStack, KillerMoney*, LimitPillagers, LocaleLib, LuckPerms, MaSuiteCore, MaSuiteTeleports, MMT, MobFarmManager, MobSpawnLimit, Multiverse-Core, MysqlPlayerDataBridge, NoSpawnerChange, OreReplacerNether, OreReplacerPlugin, PL-Hide, PlaceholderAPI, Plan, PlayerHeads, PlayerWarps, PlugMan*, ProtocolLib, PvPManager, QuickShop, RandomTeleport, React*, Redeemable, SAML, SayFormat, SurvivalInvisiframes, TAB, TAB-BukkitBridge, TokenManager, Vault, VentureChat, VillagerLobotomizatorNator, VillagerOptimiser, WorldBorder, WorldEdit, ZavAutoMessager*

paper-232 1.16.3

**Comment by electronicboy** [comment]
> [23:39:15] [Guilds SQLite Connection Pool housekeeper/WARN]: [me.glaremasters.guilds.libs.hikari.pool.HikariPool] Guilds SQLite Connection Pool - Thread starvation or clock leap detected (housekeeper delta=1m5s884ms559µs929ns).

Your server stalled out or something screwed with the JVM clock source, not an NMS issue
