### ISSUE TITLE
Server randomly freezing and 100% cpu with no players online

### ISSUE THREAD

**Issue by Sneakometer** [PaperMC/Paper#4676]
I'm running a private survival server for 2-3 players using paper. I am experiencing seemingly random freezes when the server was running for 1-2 days. I was running latest paper when starting the server and experienced it on many previous builds too. I've now updated again but i'm about 100% sure it will happen again, as there where no related changes in recent commits. I'll let you know.

The console is spamming these stacktraces:
https://pastebin.com/n3UsBHT2
Plugins:  CoreProtect 19.2, ViaVersion and ViewDistanceTweaks.
Running on openjdk version "11.0.8" / debian 10 with 4GB ram (3GB allocated for Minecraft).

**Comment by HauserGrim** [comment]
Timings, paper version

**Comment by electronicboy** [comment]
Your servers taking too long to tick, as well as stuff like redstone in the world loading chunks. Please use discord for support, but, your server stalling for that long and in that manner suggests that your issue is a wider one than just paper itself, the full JVM is freezing

**Comment by Sneakometer** [comment]
Well, it does not happen using spigot.
Also there is little to no redstone on the server. As i said it's a very small private survival server with only a few buildings.
