### ISSUE TITLE
ICrossbow interface is missing on Piglin and Pillager

### ISSUE THREAD

**Issue by orblazer** [PaperMC/Paper#4678]
**Is your feature request related to a problem? Please describe.**
When i want make an custom entity behavior i need always use NMS (or re invent the wheel) for `shoot` with crossbow.

**Describe the solution you'd like**
Like `Skeleton` the Piglin and Pillager need have an interface for that.
The interface need like :
```java
public interface CrossbowUserEntity extends RangedEntity {
    void shoot(float speed);

    void shoot(@NotNull LivingEntity target, @NotNull ItemStack crossbow, @NotNull Projectile projectile, float multishotSpray);

    void shoot(@NotNull LivingEntity target, @NotNull Projectile projectile, float multishotSpray,  float speed);
}
```

**Describe alternatives you've considered**
Nothing.

**Comment by orblazer** [comment]
Thanks for rapidity @electronicboy but the method `shoot` still missing, that is why i have share the `CrossbowUserEntity` interface.

**Comment by electronicboy** [comment]
That's what the rangedAttack method should cover? it doesn't expose the shoot method itself but the logic which calls through to that

**Comment by orblazer** [comment]
Hum basicly `rangedAttack` call `shoot(float)` (that use cross bow in hand), but if we want shot when the mob not have crossbow we need call `shoot(LivingEntity, Projectile, float,  float)`
