### ISSUE TITLE
PlayerItemConsumeEvent is fired when it shouldn't be

### ISSUE THREAD

**Issue by partydev** [PaperMC/Paper#4682]
### What behaviour is expected:
Setting the food level of a player to 20 will not fire the PlayerItemConsumeEvent.

### What behaviour is observed:
Setting the food level of a player to 20 fires the PlayerItemConsumeEvent.

### Steps/models to reproduce:
```
    @EventHandler
    fun PlayerItemConsumeEvent.onConsume() {
        isCancelled = true
        player.setFoodLevel(20)
    }
```
Will continue firing the event. If you make a food item and cancel the consume event and then set the player food level to 20, it will keep firing the event in an infinite loop until they switch items.
### Plugin list:
N/A

### Paper version:
[16:04:34 INFO]: This server is running Purpur version git-Purpur-"54fdd69" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[16:04:34 INFO]: Previous version: git-Purpur-786 (MC: 1.16.3)
[16:04:34 INFO]: Unknown version
(a fork of purpur that only modified being able to toggle lag compensating eating for testing)

### Anything else:
N/A

**Comment by webcrawls** [comment]
Reproduce this on Paper

**Comment by aikar** [comment]
Works as intended. This event isnt even just limited to food at an abstract level.
This represents when the client is requesting to consume the active slot. it doesn't know if the action of the consumption is going to fail or not.

You likely want a PostConsumeEvent or something.

**Comment by YouHaveTrouble** [comment]
Excuse me, but WHAT. How is an API firing an event working as intended?

**Comment by chickeneer** [comment]
> Excuse me, but WHAT. How is an API firing an event working as intended?

The original issue was not reported correctly. There is an issue - but the API is not firing the event as suggested here.

The actual bug here. Is that both cancelling the event and setting the player's food level is failing to unset the "raised hand" status and active item for that player. Which causes the server tick to repeatedly attempt to consume the item despite it being cancelled.
Adding some debug to the steps to reproduce will show that each event call is occurring during different ticks for the before mentioned reason.

A solution to work with the current broken mechanics - is to simply schedule the setFoodLevel AFTER the event is done. Best done by scheduling the action to run on the next server tick. I have confirmed that this solution does indeed prevent the event from repeatedly firing.

**Comment by chickeneer** [comment]
I suspect the solution is to add `this.clearActiveItem();` to isCancelled part of the the event call for PlayerItemConsumeEvent in EntityLiving (but have not tested this solution)

**Comment by aikar** [comment]
doh, I misunderstood what the report was. I interpreted it as "The events firing even though my food was 20". Sorry about that.

**Comment by aikar** [comment]
chickens theory on clearing does sound valid.

**Comment by partydev** [comment]
I apologize for not explaining the issue more clearly or missing what exactly went wrong, and not being able to test on Paper. I am still new and learning.

**Comment by aikar** [comment]
was really my fault, I didn't read it thoroughly and just misinterpreted the issue

I just thought you didn't expect the event to re-fire if the food was already maxed and the user sent another attempt to consume.

**Comment by chickeneer** [comment]
To confirm that my idea does solve the issue at hand. Which was adding `                this.clearActiveItem(); // Paper` to after `event.isCancelled()`. I will PR the fix this evening when I have time.

Again, as mentioned, delaying the setFoodLevel is going to work as well without the fix (Spigot compatibility)

**Comment by partydev** [comment]
> 
> 
> To confirm that my idea does solve the issue at hand. Which was adding ` this.clearActiveItem(); // Paper` to after `event.isCancelled()`. I will PR the fix this evening when I have time.
> 
> Again, as mentioned, delaying the setFoodLevel is going to work as well without the fix (Spigot compatibility)

I tested delaying setFoodLevel by short delay and unfortunately the issue is still present if you continue to hold down the consume button. If you do not hold down the consume button, it is fine. For now, I am going to just use the FoodLevelChangeEvent instead of the PlayerItemConsumeEvent and see if it works more the way I want.

https://streamable.com/fs7nlb

**Comment by partydev** [comment]
please don't close this, bot

**Comment by OoLunar** [comment]
Has this issue been fixed yet? I'm still managing to get this through a Skript event handler. Works fine on Spigot, but not on Paper.

**Comment by MiniDigger** [comment]
theres a fix for this in the pipeline
