### ISSUE TITLE
Certain objects fails to load after last update.

### ISSUE THREAD

**Issue by AlexanderCurl** [PaperMC/Paper#4683]
### What behaviour is expected:
Objects loads correctly.

### What behaviour is observed:
My entire house disapperead, however my stuff in my inventory is present.

### Steps/models to reproduce:
Updated from paper-239 to paper-246

### Plugin list:
Vault, LuksPerms, EssentialsX

### Paper version:
paper-git-246

### Anything else:

After the update, downgrade doesn't work either. Tried serveral version.

[latest.log](https://github.com/PaperMC/Paper/files/5432941/latest.log)

**Comment by Proximyst** [comment]
You've got a corrupted world, most likely due to b234 or unsafe saving of the world. Nothing we can do about it. Restore from a backup.
If you manage to corrupt the world on whatever the latest build is at the time of your attempt, please comment again and this will be reopened.
