### ISSUE TITLE
Server-side ghost blocks on paper 1.16.3 (235-246)

### ISSUE THREAD

**Issue by BenjaminRodriguesMiranda** [PaperMC/Paper#4684]
### What behaviour is expected:
Expected behavior: I place 100 blocks, server registers 100 block placements.

### What behaviour is observed:
Observed behaviour: Server places a small percentage of those 100 blocks (skipping many)
### Steps/models to reproduce:
https://imgur.com/a/wLhFwcv
1. Run a paper server using version 235 or 246 (1.16.3)
2. Place many blocks
3. Relog, many blocks will disappear (or use a mod to reveal ghost blocks)

### Plugin list:
Redprotect, latest version
Worldedit, latest version
Also tested without plugins, same issues

### Paper version:
This server is running Paper version git-Paper-246 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

### Anything else:
tested on spigot 1.16.3, no issues.
Tested on paper 1.16.3 versions 235 and 246, without plugins, issues appear

EDIT: This is not a networking issue, other players living elsewhere have the same issues. TPS: 20, ping: 20ms
EDIT 2: Spigot now also shows this behavior, I will report it to them.

**Comment by electronicboy** [comment]
Test against vanilla and check your client logs, ghost blocks are hardly a new issue

**Comment by BenjaminRodriguesMiranda** [comment]
> Test against vanilla and check your client logs, ghost blocks are hardly a new issue

Checked in vanilla, no ghost blocks. Also: this is different, because instead of the client having less blocks then the server (bumping into air whilst insta-mining), this is the server not registering blocks

**Comment by electronicboy** [comment]
One thing to check would be, https://paper.readthedocs.io/en/latest/server/configuration.html#incoming-packet-spam-threshold lower value = less limiting iirc

**Comment by BenjaminRodriguesMiranda** [comment]
> One thing to check would be, https://paper.readthedocs.io/en/latest/server/configuration.html#incoming-packet-spam-threshold lower value = less limiting iirc

Its value was 10.000, I do not know how that happened. Thank you for the help!
