### ISSUE TITLE
Item entity X has no item?!

### ISSUE THREAD

**Issue by BillyGalbreath** [PaperMC/Paper#469]
There seems to be a common issue with Item entities that do not have an ItemStack attached to them (as seen by searching Google). It doesnt seem to be caused by any one thing in particular, but most issues point to Spigot's radius item stacking when large numbers of Items spawn at the same time (either naturally or by a plugin).

The suggestion is rather simple one. If the Item entity doesnt have an ItemStack, why not simply remove the Item from the world? OR at least add a paper.yml config option to turn this on. I dont think things will become a problem because Items that get picked up dont add ItemStacks to the inventory anyways as it is. So, removing the Item should fix the console spam and free up some server resources in the process which should reduce or remove the lag associated with this console spam cause.

http://image.prntscr.com/image/0f66e8e70def412487e07384b7e5f149.png

**Comment by aikar** [comment]
No longer valid for 1.11. Mojang removed the debug text.
