### ISSUE TITLE
Limit outgoing packets?..

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#4690]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. If one player let's explore an underwater fortress, other players (in other places of the world) will feel huge lags during the game. Why all this? And that is why:

![2020-10-25_21 21 16](https://user-images.githubusercontent.com/19989717/97115551-4fbe9780-1708-11eb-9264-e9a973edb93d.png)
![2020-10-25_21 21 16](https://user-images.githubusercontent.com/19989717/97115680-fe62d800-1708-11eb-90b0-1658a68f2565.png)

7 tx, **7k+** rx packets. Minecraft, are you seriously? How to prevent this?!

**Describe the solution you'd like**
A setting in paper.yml like "max-packets-per-second" or something other, to limit packets per player.

**Additional context**
I receive constant complaints from my players about this issue and will be very happy if you can help me fix it as soon as possible..

**Comment by Brokkonaut** [comment]
Many packets are very small and are sent very frequently (entity spawn/updates). So the amount does not tell much about the number of bytes sent. I do not think limiting those packets would be a good idea, because they would stack up for that client if they are queued or the client would desync (if they are discarded).

**Comment by molor** [comment]
As alternative way to solve this problem: reduce frequency of sending data packets for guardians

**Comment by electronicboy** [comment]
Easier said than done, we don't control the data that vanilla expects to be sent either way, and while you can maybe reduce some of them, you introduce the issues of state desync's, which cause a whole miriad of issues. if you can identify data which is sent too often that it's an issue, we can maybe look into it, but there is no easy or trivial way to blanket reduce the number of packets sent by something without having to investigate the side-effects

**Comment by Strahilchu** [comment]
Change network-compression-threshold in server.properties to 512 ? If its sending too many packets at least it shouldn't use lot of CPU compressing them. I'm not entirely sure, can even try setting it to 64. Worth a shot

**Comment by Proximyst** [comment]
Is this also even an issue on Paper at all? "Sadness" isn't Paper.

**Comment by molor** [comment]
> "Sadness" isn't Paper

Yea, it's Paper. I'm just changed "minecraft:brand" channel via plugin..
```
[23:37:16] This server is running Paper version git-Paper-"8e6d90c2" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
```

**Comment by molor** [comment]
Does anyone know, increasing `settings.netty-threads` in `spigot.yml` could help with this?

**Comment by HexedHero** [comment]
> Does anyone know, increasing `settings.netty-threads` in `spigot.yml` could help with this?

No

**Comment by Chew** [comment]
Alternatively, try it and see

**Comment by Chew** [comment]
This discussion has run its course.
