### ISSUE TITLE
Server hang/deadlock if chunk load occurs in onEnable

### ISSUE THREAD

**Issue by RoboMWM** [PaperMC/Paper#4693]
### What behavior is expected:
no deadlock/eternal hang on server startup

### What behavior is observed:
server startup hangs on either multiverse-core if keepspawninmemory is set to true, or if creativeparkour loads up (creativeparkour apparently checks/sets blocks in its world in onEnable).

### Steps/models to reproduce:
- Have plugin load chunks/place blocks or something in a world that causes chunks to be loaded during onEnable
- That chunk must throw an exception when being loaded (i.e. chunk corruption, e.g. build 236, NBT issue)

### Plugin list:
Let me know if you want my 100+ plugin list c:

### Paper version:
[Server thread/INFO]: Starting minecraft server version 1.16.3
[Server thread/INFO]: Loading properties
[Server thread/INFO]: This server is running Paper version git-Paper-247 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

### Anything else:
N​NY​aK​Np​Gm​s0​eU​Vp​iS​dH​z sees a hang on the chunk loading thread to print an error/crash report? - which it needs to get the plugin list - but this is locked by the server thread since it's still enabling plugins.

https://korobi.vq.lc/network/spigot/channel/paper-help/logs/2020/10/26/#L3187

jstack of the relevant threads:

CreativeParkour: https://gist.github.com/RoboMWM/beef47af98a91cba37685c0ba1d8f340
Multiverse: https://gist.github.com/RoboMWM/7c3f90181e11691129b721acef4e0187
RotatoR: https://gist.github.com/RoboMWM/edd98642e0886efa66f6f65e9421fa64

**Comment by aikar** [comment]
Yeah it sucks but this will never be fixed unless someone wants to come up with some extreme hack that doesn't suck.

**Comment by RoboMWM** [comment]
I'm not even sure what NBT issue I'd even have with these worlds, haven't had this issue until a week or so ago when I noticed this server wasn't starting - and is happening to any world.

**Comment by RoboMWM** [comment]
Removed/disabled all functions that cause chunk loads (setting keepSpawnInMemory in another plugin, etc.) and the server has started with no NBT issues or other crashes that I can see in the log. Unless I'm not looking for NBT issues properly, my guess is any plugin that loads chunks in onEnable is toast?

Edit: Mk I see the NBT issues now when joining the server and visiting the worlds. ~~Not sure how this happened to every single chunk that's normally loaded on start~~ was due to the build 236 issue.

**Comment by aikar** [comment]
No, only for a bad chunk. the server was trying to generate a crash report, and that's what lead to the deadlock.

main thread holds lock, chunk threads detect a fatal crash and tries to gen a crash report. crash report then wants to include the plugins in said report.

Only option here would be if crash reports checked that the server had finished starting already and DIDN'T include plugins, OR the plugins is cached in a way it no longer needs that same lock.

**Comment by OpticFusion1** [comment]
> 
> 
> No, only for a bad chunk. the server was trying to generate a crash report, and that's what lead to the deadlock.
> 
> main thread holds lock, chunk threads detect a fatal crash and tries to gen a crash report. crash report then wants to include the plugins in said report.
> 
> Only option here would be if crash reports checked that the server had finished starting already and DIDN'T include plugins, OR the plugins is cached in a way it no longer needs that same lock.

Probably best to have a Server#isFinishedLoading method, and if false don't include plugins in the crash report.
This would also allow plugins to check if the server is finished loading in a clean way if one does not exist currenttly, if needed for whatever reason

**Comment by RoboMWM** [comment]
> This would also allow plugins to check if the server is finished loading

there is ServerLoadEvent, and then the ol' trick of scheduling a task to run on first tick.

(Re the idea, Idk how feasible it is.)

**Comment by OpticFusion1** [comment]
> 
> 
> > This would also allow plugins to check if the server is finished loading
> 
> there is ServerLoadEvent, and then the ol' trick of scheduling a task to run on first tick.
> 
> (Re the idea, Idk how feasible it is.)

I was thinking something set literally right after the server's finished loading (i.e. right after or before the "done" message), unless ServerLoadEvent does that already

Edit: Could be a completely new event ServerFinishLoadEvent or something, that way nothing hacky has to happen

**Comment by Warriorrrr** [comment]
It seems like thanks to the changes that have been made to the chunk system, this issue is no longer present. I can confirm that the 3 methods shown in the jstacks (Block#setType, World#setKeepSpawnInMemory & Block#getState) all work fine now when ran from inside onEnable.

**Comment by RoboMWM** [comment]
> It seems like thanks to the changes that have been made to the chunk system, this issue is no longer present. I can confirm that the 3 methods shown in the jstacks (Block#setType, World#setKeepSpawnInMemory & Block#getState) all work fine now when ran from inside onEnable.

I don't remember too much of the details about this issue, but from what I put, it looks like one of the prerequisites is that the chunks involved have to be corrupted in such a way that a stacktrace is triggered to be printed - which would then cause the deadlock.
