### ISSUE TITLE
Server lag while 1 player flies on Elytra

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#470]
This is the first time this has occurred and this activity is very common, so it would have been an issue long ago if it had nothing to do with a tweak for recent builds.

**View end of report**
Build 902 Report:
https://timings.aikar.co/v2/?id=d95dada630cd458387da6acfbe203f9f&section=lag

After Update to 910:
https://timings.aikar.co/v2/?id=41aba73958f6463782f62976814152a5&section=lag

**Description**
Player simply flying quickly on Elytra

**Buikkit/Spigot/Paper ymls**
http://hastebin.com/gowijinasu.coffeescript

**Paper Build**
902 (updated to 910 w/ same TPS drop)

Not that it makes much difference...
Dual Xeon CPUs, DDR3 ECC RAM, SSD and 7GB RAM

**Comment by CeIebrimbor** [comment]
Same issue on 910:
https://timings.aikar.co/v2/?id=41aba73958f6463782f62976814152a5&section=lag

**Comment by Black-Hole** [comment]
It seems the player is exploring new chunks that need to be created first. That is an expansive process especially since flying an elytra is really fast.

You could prevent this by using a world border.

**Comment by CeIebrimbor** [comment]
World border set and preloaded the entire explorable map with WorldBorder's /fill (spent about 12 hours filling map, so yes it happened)

If you see WB missing from plugins, it is because I used it to fill and then removed and am using vanilla worldborder.

**Comment by CeIebrimbor** [comment]
This seems to be the culprit:
[+]Minecraft::world - Light Chunk

This fix (spigot.yml)?
random-light-updates: false
