### ISSUE TITLE
ItemStack#getItemMeta() is pretty heavy, could it be further optimized?

### ISSUE THREAD

**Issue by NCBPFluffyBear** [PaperMC/Paper#4705]
*This is a little bit on the side of a feature request, but it is because of a performance issue. I also want to get a second opinion.

###  Timings or Profile link:
https://spark.lucko.me/#k2Pl2r2LPh
https://timings.aikar.co/?id=665063dd8b2d400e83786cce39abc54e#timings

Here's what I'm looking at: 
![image](https://user-images.githubusercontent.com/31554056/97746576-8efa3900-1ab8-11eb-8a36-bb965f3cb1b7.png)

### Description of issue:
The cargo system in [Slimefun ](https://github.com/Slimefun/Slimefun4) is an item transport system that allows 9 items to be whitelisted/blacklisted. To compare these items, the plugin uses getItemMeta(). As seen in the spark profile, this method seems to be the stem of the issue. I'd like to know if any performance improvements could be made to this.

### Plugin list:
https://timings.aikar.co/?id=665063dd8b2d400e83786cce39abc54e#plugins

### bukkit.yml, spigot.yml, paper.yml, server.properties
[bukkit.yml](https://hastebin.com/ujewoxoqes.yaml)
[spigot.yml](https://hastebin.com/ufetimuyob.yaml)
[paper.yml](https://hastebin.com/epahoworox.yaml)
[server.properties](https://hastebin.com/zimazobiya.ini)

### Other helpful links
Slimefun 4 is open source: https://github.com/Slimefun/Slimefun4
This is the line from CargoUtils: [link](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java#L279)
And this is isItemSimilar(): [link](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java#L262)

### Paper version:
`[14:23:44 INFO]: This server is running Paper version git-Paper-251 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[14:23:44 INFO]: Previous version: git-Paper-206 (MC: 1.16.3)
[14:23:44 INFO]: You are running the latest version`

**Comment by aikar** [comment]
Not without breaking the api and requiring plugins to be rewritten. Just a downside of the clone nature of this API.

would be up to slimefun to do better here.

**Comment by NCBPFluffyBear** [comment]
Correct me if I am wrong, but couldn't you invent your own way of getting ItemMeta and add it as a new method to your API? That way plugins would need to specify that they want to use Paper's way of getting ItemMeta, so they won't lose compatability.

**Comment by electronicboy** [comment]
#4708
