### ISSUE TITLE
PacketPlayInTeleportAccept (IOException) - 1.16.3

### ISSUE THREAD

**Issue by ItWasEnder** [PaperMC/Paper#4706]
### What behaviour is expected:
Player joins server.

### What behaviour is observed:
Player is kicked while connecting to server.

### Steps/models to reproduce:
Not entirely sure, I am running a bungeecord network that connects to server running 1.16.3 paper.

### Plugin list:
AAC, AACPlus, AdvancedEnchantments, AdvancedHelp, AirBar*, AnimatedScoreboard, Bank, BeastWithdraw, BetterRTP, BKCommonLib, BungeeTabListPlus, ChatControl, Citizens, CitizensCMD, CMI, CMIPaperLib, ConditionalCommands*, Core, CrazyAuctions, DragonEggDrop, DynamicMarketplace, EasyPrefix, FancyBags, (WorldEdit)FastAsyncWorldEdit, Gateways*, GriefPrevention, GuiRedeemMCMMO*, Harbor, HeadDatabase*, InteractionVisualizer, InteractiveChat, KixsAutoAnnouncerPremium, LightAPI, LightCleaner, LiteBans, LuckPerms, mcMMO, Multiverse-Core, MVdWPlaceholderAPI*, NametagEdit*, NPC_Destinations, NPCDestinations_Animator, PL-Hide, PlaceholderAPI, Plan, PlayerWarps, PremiumVanish, Prism, ProtocolLib, PvPManager, Quests, QuickShop, Realistic_World, SolarisAdditions*, SpawnerWrench, SpecializedCrates, TotemSpawners, Towny, TownyFlight, TownyGUI, TownyNameUpdater, TrMenu, Vault, VoidGenerator, VoteParty, Votifier, Vouchers, VoxelSniper, WildStacker, WorldGuard, WorldGuardExtraFlags.

### Paper version:
Paper-1.16.3-b251

### Anything else:
https://pastebin.com/m48UwJNk

**Comment by electronicboy** [comment]
You have a plugin installed which is messing with the servers packet registry or (or doing horrific things in the networking code)

**Comment by ItWasEnder** [comment]
how should I go about debugging this to find the cause

**Comment by electronicboy** [comment]
Start pulling plugins, from what I recall, try pulling CMI, but, basically, start pulling plugins out in batches until you find the batch which causes it, and add them back one by one

**Comment by ItWasEnder** [comment]
Alright, thanks

**Comment by ItWasEnder** [comment]
I don't get this error all the time only sometimes after re-logging and the issue is solved when the server is restarted.
