### ISSUE TITLE
TPS drop | Akira's Timing Viewer | Where's the problem?

### ISSUE THREAD

**Issue by NessunoMC** [PaperMC/Paper#4707]
### All infos on the Timings Report.

https://timings.aikar.co/?id=e67bd233e25148d78ddb3143f0b0f3b4#timings

### Paper version:
git-PaperSpigot-"4c7641d" (MC: 1.8.8)

**Comment by electronicboy** [comment]
This is not the place for support with timings, nor has 1.8.8 been supported in years.
