### ISSUE TITLE
JsonList (banlists) always iterates over all elements when getting one from it

### ISSUE THREAD

**Issue by Shevchik** [PaperMC/Paper#471]
net.minecraft.server.{pkg}.JsonList get method iterates over all the list and removes stale entries (And even the way it does it is really inefficient).
It is always done on login when checking banned player, which means the longer the ban list the more lags it causes. I suggest to adding feature that only cleans it up upon load.

Also it always saves on adding/removing elements from it, that should be done on stop only, or there should be async task that does that.

Also ipbanlist doesn't support ipv6 due to it's socketaddress to string converter being stupid.

**Comment by AlfieC** [comment]
This has been the case since 1.7 I believe. Could be avoided by simply computing the next ban to expire, storing the timestamp of that expiry and then checking if the current time is past that expiry on get operations. However, this adds slight overhead on adding and removing from the list - but these are used much less.

I believe the reason the banlist is saved all the time is that if the server crashes, the banlist would remain correct. However, I'm not aware of many servers which use the default ban system. Most use LiteBans or a similar product - or just simply Bukkit's inbuilt ban system (I don't recall if this uses the JsonList).

**Comment by AlfieC** [comment]
I will add that the way it checks could also do with improvements. Currently, it works like so:

```
        ArrayList arraylist = Lists.newArrayList();
        Iterator iterator = this.d.values().iterator();
        while (iterator.hasNext()) {
            JsonListEntry jsonlistentry = (JsonListEntry) iterator.next();

            if (jsonlistentry.hasExpired()) {
                arraylist.add(jsonlistentry.getKey());
            }
        }

        iterator = arraylist.iterator();

        while (iterator.hasNext()) {
            this.d.remove(iterator.next());
        }
```

Simply changing that behavior to:

```
        Iterator iterator = this.d.values().iterator();
        while (iterator.hasNext()) {
            JsonListEntry jsonlistentry = (JsonListEntry) iterator.next();

            if (jsonlistentry.hasExpired()) {
                iterator.remove();
            }
        }
```

Is much faster and more efficient.

**EDIT:** This could be slightly improved further by just using `if (iterator.next().hasExpired() iterator.remove();`. This would reduce the amount of temporary objects created.

**Comment by Shevchik** [comment]
Bukkit built-in system uses JsonList. Many ban plugins still additionally ban players using built-in system, such as essentials.

**Comment by aikar** [comment]
This only triggers if a banned person logs in, but yeah it could be improved. PR's welcome.

**Comment by Spottedleaf** [comment]
How about adding a separate list (to JsonList) that is sorted for each ban entry by its expiration date? This way we don't have to iterate over all of them, ONLY the ones that are expired plus one.

If so, tag me and I'll make a PR.

**Comment by egg82** [comment]
Disregard last commit- it's the same code. Just trying to clean up my PR fork which caused things like that to happen. Need to use branches for PRs in the future
