### ISSUE TITLE
Remove @Deprecated to PrepareGrindstoneEvent

### ISSUE THREAD

**Issue by Doc94** [PaperMC/Paper#4713]
**Is your feature request related to a problem? Please describe.**
Only a warning for use of deprecated event.

**Describe the solution you'd like**
In teory the event works fine i dont know why keep the annotation.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Proximyst** [comment]
It's superseded by [`PrepareResultEvent`](https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/event/inventory/PrepareResultEvent.html).

**Comment by Doc94** [comment]
Im confuse, then why only PrepareGrindstoneEvent are the deprecated? or maybe can suggest add in docs more details?

**Comment by Proximyst** [comment]
It says in the docs that you should use the other event. Only that event is deprecated because only it was superseded.
