### ISSUE TITLE
Set BossBar title using BaseComponent

### ISSUE THREAD

**Issue by marcbal** [PaperMC/Paper#4716]
**Is your feature request related to a problem? Please describe.**
I can’t set the bossbar title using `BaseComponent`, despite the fact that boss bar titles are using `IChatBaseComponent` internally. I’m now using only components in my plugin for text messages (to get rid of legacy format), but it is kind of useless to convert my component to legacy text, if the bossbar convert it back to component.

**Describe the solution you'd like**
Add `setTitle(BaseComponent...)`, `setTitle(BaseComponent)` and `getTitleComponent()` to the boss bar API.

**Describe alternatives you've considered**
As I described in my problem description, We could just convert the component to legacyText, set the title using `setTitle(String)`, and let the bossbar convert it back to component.

**Additional context**
(none)

**Comment by Proximyst** [comment]
I'm unsure if this will be done with Bungee components; @kashike might have something to add there.

**Comment by SHsuperCM** [comment]
Any update on this?
Why would it not be possible to use components?
Vanilla already allows components in the title using /bossbar

**Comment by astei** [comment]
The community is starting to standardize on [Adventure](https://github.com/KyoriPowered/adventure) which is a much richer API than what the BungeeCord chat API provides. Of course the BungeeCord chat API will continue to be supported but new extensions using it are unlikely to be added.

**Comment by SHsuperCM** [comment]
Is it going to be included with paper? because until then, I dont think I'll add another dependency to what I'm working on.
Honestly I have never heard of it but it looks promising..

**Comment by Proximyst** [comment]
It will, yes. I'm not sure as to the progress of it, nor do I really know if we at all accept new APIs with the "legacy" BungeeCord components, so I'd say Adventure is your best bet.

**Comment by kashike** [comment]
We are handling this another way - tracking in #4830.
