### ISSUE TITLE
Saving player data is done on main thread.

### ISSUE THREAD

**Issue by Shevchik** [PaperMC/Paper#472]
Saving player data is always done on main thread when player disconnects. Loading is done the same way too. Maybe a thing similar to chunk io executor should be created.

**Comment by aikar** [comment]
Without implementing a lot of the hacky logic Chunk Saving does, it's not that clean.

Basically, you got to keep the data in a map until it finishes saving, so on login, if the data is in the map, use it.

As you got to avoid accidently loading player data from disk that is stale from the pending save.

**Comment by aikar** [comment]
I don't see the Paper team ever working on this. If anyone wants to go ham and try to accomplish this, feel free to PR. But please be sure to cover the same logic chunks do and keep a map of pending saves to look up if a player logs in during async pending save.
