### ISSUE TITLE
Worldborder events

### ISSUE THREAD

**Issue by DarkEyeDragon** [PaperMC/Paper#4720]
**Is your feature request related to a problem? Please describe.**
For my RTP plugin I pre-generate locations (based on the size of the worldborder). If the worldborder changes, there's no way to know about it. So when its changed there is a possibility you will be teleported outside the world border. Rechecking if the location is safe somewhat defeats the purpose of a pre generated location.

**Describe the solution you'd like**
Have 2 events related to the worldborder `WorldBorderChangeEvent` and `WorldBorderChangedEvent` (different names welcome). First one would trigger when the wb is changing and the second when its done changing since it can change over time.
**Describe alternatives you've considered**
Listening to the worldborder commands. Thats very hacky and prone to errors.
Validating the locations when consumed is a doable alternative. However having wb events wouldn't be a bad thing imo.

**Comment by Machine-Maker** [comment]
@DarkEyeDragon in your issue on your RandomTeleport you said someone else was making a pr. That still happening or... what?
