### ISSUE TITLE
Lighting Issue

### ISSUE THREAD

**Issue by AgentLoneStar007** [PaperMC/Paper#4721]
Hi. So I first noticed this bug in Paper build #246, and it's been present in every build since. The lighting is always at 15 on the client side, yet mobs can still spawn. Even in caves, or nighttime, the light is always at max level(15). I'm kind of wondering if this is an issue with Minecraft itself at the moment. If you wish, wait till the release of MC 1.16.4 before looking into this bug. Right now it's just a minor inconvenience, and not a server-crashing bug. I would be like, "Hey, just use this code to fix the bug," but I haven't learned Java yet. I'm hoping to, soon.

**Comment by Proximyst** [comment]
Fill the template with proper information. This could be reduced to "Light is bugged. I'd fix, but no idea how. Fix it whenever".

**Comment by AgentLoneStar007** [comment]
Alright, I see you've already marked it as invalid, which is true. I just fixed it. Just turn your brightness down to moody, then back up to whatever your desired setting is, and it fixes itself.
