### ISSUE TITLE
Double carpet pathfinding 

### ISSUE THREAD

**Issue by tlenevoli** [PaperMC/Paper#4724]
### What behaviour is expected:villagers having problems with pathfinding on a double layered carpet
___What you expected to see___ same, villagers and other mobs unable to pathfind on a double layered carpet.

### What behaviour is observed: the villagers are walking normally on a double layered carpet. 
___What you actually saw___ same.

### Steps/models to reproduce: in vanilla mobs cant pathfind on carpet. It is really useful for making farms, trading halls, or just making sure that mobs cant get in your house, without making an ugly wall.
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___ nothinh

### Paper version: git-paper 244 (mc1.16.3) (implementing api version 1.16.3 r0.1 snapshot)
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by MiniDigger** [comment]
I can't repro, as in, the behavior is the same on paper and vanilla: they walk on double carpet just fine
![https://i.imgur.com/ALZ00yD.png](https://i.imgur.com/ALZ00yD.png)

did I misunderstood what double layered carpet means?

**Comment by tlenevoli** [comment]
Yes. Mobs cant path find on or over double carpet. Is vanilla at least.

**Comment by MiniDigger** [comment]
That screenshot was taken on vanilla single player and the villager clearly pathfinded on double carpet?

**Comment by OpticFusion1** [comment]
Looked into it, they do sometimes get stuck in a spinning motion on double carpet, before eventually moving to a different block.
Perhaps that's what they were talking about?

Edit: This happens on vanilla single player

Edit: It's a general path finding issue. Any mob might end up stuck spinning on double carpet for a while before pathfinding correctly
