### ISSUE TITLE
Piglins Don't Pickup Gold Ingots

### ISSUE THREAD

**Issue by Cytosta** [PaperMC/Paper#4725]
### What behaviour is expected:
___What you expected to see___
Singleplayer 1.16.3 - https://imgur.com/u8MLZaQ

### What behaviour is observed:
___What you actually saw___
1.16.3 Paper server with 44 plugins: https://i.imgur.com/yfZrQl3.png
1.16.3 Paper server with 0 plugins: https://i.imgur.com/oIxqiCb.png

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
GIF recreating setup that works in singleplayer: https://i.imgur.com/I8yuxBB.gif

### Plugin list:
___A list of your plugins___
Shown up above that it's not working on a Paper server that has no plugins. But the list of plugins on the server I also tested is: https://i.imgur.com/gIb4AJf.png Before trying it in singleplayer & on another Paper server with no plugins, I removed IllegalStack to test if that was the issue (it wasn't).

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
Tested on build numbers: 232, 251, and 253. None work. Didn't try and previous versions. https://i.imgur.com/VREu6F1.png

### Anything else:
___Anything else you think may help us resolve the problem___
User on my server reported that this setup/farm is not working: https://www.youtube.com/watch?v=jVPM8dNsBgg&feature=youtu.be Can confirm, it is not working.

**Comment by WhatsTheBadNews** [comment]
Did you spawn in new Piglins to test with after removing IllegalStack?

NOTE: IllegalStack was doing this on my server until I disabled the feature. However, with the feature disabled, it persisted with Piglins that had spawned/been loaded while the feature was enabled. Newly spawned Piglins worked after it was disabled though.

**Comment by Cytosta** [comment]
> Did you spawn in new Piglins to test with after removing IllegalStack?
> 
> NOTE: IllegalStack was doing this on my server until I disabled the feature. However, with the feature disabled, it persisted with Piglins that had spawned/been loaded while the feature was enabled. Newly spawned Piglins worked after it was disabled though.

I did. Fresh Piglins each time. I also tried it on a freshly created 1.16.3 server (newly created world) with no plugins ever installed, same issues. Able to recreate the issue consistently.

**Comment by FluxCapacitor2** [comment]
Check your gamerules, is `mobGriefing` turned off?

**Comment by Chew** [comment]
That wouldn't line up with the "brand new server" as he stated though. I can mess around with this later and see and I'll keep that in mind (unless someone else wants to test)
