### ISSUE TITLE
Pets are not teleported with owner from unloaded chunks

### ISSUE THREAD

**Issue by DarkEyeDragon** [PaperMC/Paper#4731]
### What behaviour is expected:
Players teleporting should have their (non sitting) dogs/pets teleported with them

### What behaviour is observed:
When the chunks the player is teleporting from are unloading (due to no other player being nearby) entities stop ticking and thus don't teleport (at least to my understanding)

### Steps/models to reproduce:
Tame a few dogs, teleport anywhere, they wont teleport towards you like they used to in old versions (before the chunk system rewrite).

### Plugin list:
Not really relevant but:
`ACFExample*, Essentials, GriefPrevention, LuckPerms, Multiverse-Core, PlaceholderAPI, ProtocolLib, RandomTeleport, RedProtect, Test, Towny, Vault`
### Paper version:
This server is running Paper version git-Paper-231 (MC: 1.16.3)

### Anything else:
I doubt this is within the scope of paper to fix since this is a vanilla "issue". Just wanted to point it out in case there's something that can be done.

**Comment by Chew** [comment]
Is there an issue open on Mojira for this if it's a vanilla issue?

**Comment by ghost** [comment]
delay chunk unloads by a time.

**Comment by HexedHero** [comment]
Players teleport with their wolves just fine for me, I have 8 seconds on the Chunk unload delay setting.

**Comment by kickash32** [comment]
Delaying chunk unloads will not do anything if they are far enough away that they are not ticked... Perhaps the server needs to have another ticking phase, where it ticks pet entities regardless of their location as long as they are loaded? Could also have this behind a config toggle.

**Comment by Owen1212055** [comment]
This is just how entity ticking works, any entity that is unloaded will no longer be ticked... therefore the pet in the unloaded chunk will not teleport to the player.

I don't really see any really feasible way of "fixing" this without making any significant changes. 
Closing this, feel free to comment however if you feel that this should still be looked into.

**Comment by kickash32** [comment]
Alternative solution could be a special phase on unload which triggers logic to check if the mob is a pet, and causes it to teleport to the owner if it is able to (ie not sitting)?

**Comment by Owen1212055** [comment]
I mean, at that point you might as well make your own plugin that does something like this.

**Comment by kickash32** [comment]
Good point, and good enough.
