### ISSUE TITLE
Add air filled rooms to anti xray

### ISSUE THREAD

**Issue by TypicalHog** [PaperMC/Paper#4732]
Anti xray/orebfuscator is really good for hiding ores but bad for hiding bases (can be done by adding air as one of the replacement blocks). I think this very negatively affects the client-side performance. A very good compromise would be if there were base-sized pockets of air inserted randomly into the underground.

**Comment by MiniDigger** [comment]
@stonar96 do you think this would be feasible to implement

I think the "hard" part would be "base sized", it needs to look realistic?

**Comment by stonar96** [comment]
It is certainly possible but tbh I have too less of an idea about algorithms to generate such air pockets efficiently. It's not too hard to come up with something like that, but there are certainly people who can do this better than me and I'm not very interested in implementing this efficiently tbh.

I have hacked something together using `org.bukkit.util.noise.SimplexOctaveGenerator`, which you can find here: https://github.com/stonar96/Paper/blob/feature/anti-xray-generate-air-pockets/Spigot-Server-Patches/0685-Generate-air-pockets.patch

I'm generating 3D noise and create air pockets for all blocks that Anti-Xray considers as hidden and `generator.noise(...) < 0.`.

Here is a screenshot, showing me standing in an air pocket next to a real cave:
![grafik](https://user-images.githubusercontent.com/18699205/110016003-d32a6e00-7d24-11eb-977d-934db7e42411.png)

However, this is probably very inefficient and I won't PR these changes but for anyone interested working on it: Feel free to use this code to come up with something more efficient.
