### ISSUE TITLE
Feature Request: Disabling world compression

### ISSUE THREAD

**Issue by Titaniumtown** [PaperMC/Paper#4735]
There should be an option that lets you disable compression on the world. This would be useful in scenarios where ZFS (or similar) compression is used on the filesystem the world/server is stored on. Both the world and filesystem being compressed is redundant and unnecessary in those scenarios, and I would imagine would cause the machine to attempt to compress the already compressed world files, using more cpu without any benefits.

**Describe the solution you'd like**
A config option in paper.yml to disable world compression. This could possibly tie into #4715 where the config option that would specify compression type in that PR could be set to either `off`, `disabled`, or `none`.

**Comment by Proximyst** [comment]
The semi-official plan is just to merge #4715 for this functionality.

**Comment by Titaniumtown** [comment]
Oh, I didn't see that PR had that functionality, my mistake. I'll close this issue when that PR is merged!

**Comment by lynxplay** [comment]
Should hopefully be resolved https://github.com/PaperMC/Paper/pull/8505 :+1:
