### ISSUE TITLE
Server thread dump

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4736]
Ok so my server gives me tons of thread dumps right after the server finishes starting up. I'm using paper-253 jar, MC version 1.16.3; my plugins are CoreProtect & Shulker Respawner; my datapacks are anti-endermen grief, cauldron concrete, double shulker shells, larger phantoms, more mob heads, multiplayer sleep, & player head drops all from vanillatweaks.com. 
Here is the pastebin to the errors right after startup it lasts a while until it eventually crashes completely and shuts down, the first half of the errors are pretty similar but near the end theirs a bunch of different errors.
[](https://pastebin.com/bBcZncS2)

**Comment by electronicboy** [comment]
1) 1.16.3 is no longer supported
2) I've already told you the general issue on the discord, timings will tell you what datapack is causing issues, we cannot help you otherwise here.

**Comment by ghost** [comment]
Ok thank you I thought you were saying that to the Lord person.
