### ISSUE TITLE
Random Unidentifiable Crash

### ISSUE THREAD

**Issue by 27chandler** [PaperMC/Paper#4737]
### Link/paste of stack trace

https://pastebin.com/s44YWn8R

### Plugin list:
BackLobby
BungeeGuard
BungeeTabListPlus_BukkitBridge
Buycraft
ChatControl
Citizens
CMI
CombatLogX
FastAsyncWorldEdit
IllegalStack
KnockbackMaster
LogBlock
Luckperms-Bukkit
multichat
nuvotifier
OldCombatMechanics
PlaceholderAPI
Plan
ProtocolLib
ShopGUIPlus
Spartan
Spigot-CommandSigns
Vault
ViaBackwards
ViaRewind Legacy Support
ViaRewind
ViaVersion
VotingPlugin
Worldguard
WorldguardExtraFlags

### Actions to reproduce (if known):
Unknown, we most commonly get it when we have around 40-50 players online

### Paper version:
[00:32:12 INFO]: This server is running Paper version git-Paper-261 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[00:32:12 INFO]: Checking version, please wait...
[00:32:12 INFO]: Previous version: git-Paper-253 (MC: 1.16.3)
[00:32:12 INFO]: You are running the latest version

**Comment by 27chandler** [comment]
To add some extra information, we found out the cause was due to something in the end. One of our players had just entered the end portal, and when they arrived on the platform their client crashed, along with the server. I tested and there might be some corrupt entity on the platform somehow.

**Comment by Chew** [comment]
Just wanted to check in on this, does it still crash with no plugins? Is it still crashing?

**Comment by 27chandler** [comment]
I tested by loading the map with the corrupted entity into a server with no  plugins, it was still crashing even without any plugins loaded. (We resolved it in the running server by deleting the region file the entity was located in)

**Comment by Chew** [comment]
Ah okay, I'll leave this open, but it's likely some plugin caused it.

**Comment by electronicboy** [comment]
Server took too long to tick, hard to say due to the lack of the full set of dumps, but, likely the issue where mobs create a ton of entities
