### ISSUE TITLE
a Normal StackTrace

### ISSUE THREAD

**Issue by feja111** [PaperMC/Paper#4739]
### Link/paste of stack trace
https://hastebin.com/ucojesawin.yaml

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
Deluxe hub
inWartung
LPC-3.1.1.jar
LuckPerms-Bukkit-5.2.2.jar
PlaceholderAPI-2.10.9.jar
UltraCosmetics-2.5.9.jar
Vault.jar
ViaVersion-3.1.1.jar
worldedit-bukkit-6.1.jar
XConomy-2.8.9.jar

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-"5d8b3d49" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by HexedHero** [comment]
1.12.2 is unsupported.
