### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#474]
http://pastebin.com/LDfkUJ2E
Paper dev 910

**Comment by ghost** [comment]
remove this plugin PwnFilter

> [06:29:19] [Async Chat Thread - #96/ERROR]: Could not pass event AsyncPlayerChatEvent to PwnFilter v3.9.1

**Comment by zachbr** [comment]
PwnFilter having issues is not necessarily related, but it could be depending on how it is written. Watchdog looks at the main thread specifically. That being said, there isn't much to go off of here.
