### ISSUE TITLE
When braking armor stand it will drop items at wrong height

### ISSUE THREAD

**Issue by FajnB** [PaperMC/Paper#4743]
### What behaviour is expected:
Armor stand drops equipped items when it is broken. These equipped items (armor) must spawn 0.5 block above the head of the armor stand.

### What behaviour is observed:
If equipped armor stand is broken, armor on the stand is spawned at feet instead of 0.5 block above head.

### Steps/models to reproduce:
Place an armor stand and equip it with any peace of armor. Shoot it with arrow or just destroy it.
(recommend to shoot an arrow from dispenser for clearer view.)

### Plugin list:
Dynmap-3.1-beta4-spigot.jar
PlaceholderAPI-2.10.9.jar
TabList-v5.4.8.jar
WorldBorder.jar

### Paper version:
~~[22:09:53 INFO]: This server is running Paper version git-Paper-240 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)~~

~~(I know I am behind but due to some critical incompatibilities of some mods for 1.16.4 I have to stay on this version unil new version of mod is released)~~

- **Viz. Update**

### Anything else:
VIDEO of the bug.
Video [here](https://www.youtube.com/watch?v=H49Ne7ySKZ0&feature=youtu.be).

### _UPDATE_
Just tried it on a latest version and the bug persists.

Version:
[22:25:50 INFO]: This server is running Paper version git-Paper-262 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by FajnB** [comment]
Is there any progress or not?

**Comment by Machine-Maker** [comment]
I tested this out, and yes, it does seem that armor stands to drop their items on the ground on paper vs in the air on vanilla. (1.16.4). I couldn't 100% confirm that this is the case for other entities on vanilla. Glancing through the code for armor stands, I couldn't see anything that changed this drop height tho.

**Comment by FajnB** [comment]
I do not know if it is intentional or not. If you think that this is a bug and is unintentional it would be at least good to make a setting to make it drop higher when armorstand broken, so you can decide to have it like in vanilla. For me this is pretty much the same deal as 0 tick farms were. They existed in vanilla, but it was unintentional so the setting was added to allow it or disable it.
The now observed behavior on paper brakes armor item sorters.

**Comment by FajnB** [comment]
Will there be anything done to this issue?
I know that there are more important issues, but I want to at least know if there is any interest in this bug or if it is just dead as it is non essential gameplay feature.

**Comment by FajnB** [comment]
This bug is marked as bug and still is more than three months without any response what so ever is it will ever get repaired.

**Comment by electronicboy** [comment]
this is not really a critical bug and the current fix is caveated, with my health, this is low priority;
You are more than welcome to test the PR yourself or open a PR with a better solution
