### ISSUE TITLE
Add playsound event

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#4746]
**Is your feature request related to a problem? Please describe.**
No, its not.

**Describe the solution you'd like**
Add a event "on playsound" to check when Minecraft wants to play a sound.

**Describe alternatives you've considered**
I want to stop Minecraft playing sound without turning off the Music volume.
I got a idea to playsound when something happen, not when Minecraft want randomly

**Additional context**
I think none. Its good.

**Comment by Proximyst** [comment]
Music is done clientside.

**Comment by BillyGalbreath** [comment]
More specifically, ambient music (which seems to be the focus of your request?) is strictly client side.

Other sounds (jukebox, etc) are server side, and others (entity noises, etc) are client side.

Not really possible to make an event for this because it wouldn't cover all the sounds and would be confusing for devs

**Comment by Chew** [comment]
The only acceptable use for this would be cancelling the `/playsound` event, but why would you want that?

**Comment by Misio12320** [comment]
> The only acceptable use for this would be cancelling the `/playsound` event, but why would you want that?

I want to create a mini game without mute the "Music" option in settings. Or just add support to loop stopsound without breaking performance

**Comment by electronicboy** [comment]
> Or just add support to loop stopsound without breaking performance

"without breaking performance", it's a singular packet to send stopsound? Not really sure why there would be any performance issues...
