### ISSUE TITLE
Banner-waving patch no longer needed for 1.16?

### ISSUE THREAD

**Issue by weikengchen** [PaperMC/Paper#4747]
### Summary

This is related to Spigot server patch "0068-Waving-banner-workaround.patch" (note: the number may change in the future), which is a historical workaround for the bug [MC-63720](https://bugs.mojang.com/browse/MC-63720) to make the banner waves: 

https://github.com/PaperMC/Paper/blob/e38eceb42a106568e4db5830b936e550dbe509f5/Spigot-Server-Patches/0068-Waving-banner-workaround.patch

- This patch is likely **unnecessary** for 1.16 since MC-63720's page said it has been fixed in 1.15-pre3.
- This patch has a **side effect** that the client no longer receives the correct world age. The world age, however, is useful for a hacky player to construct a non-stop iron golem farm in a server with several worlds.

This patch has been discussed previously (https://github.com/PaperMC/Paper/issues/346, https://github.com/PaperMC/Paper/pull/369, https://github.com/PaperMC/Paper/issues/266) and is considered "won't fix" since banner-waving is more important. However, as this bug is fixed, probably this patch is not necessary.

### What behavior is expected:
The client expects the world age to be the correct age of the world, rather than the value % 192000.

### What behavior is observed:
The client receives the world age % 192000.

### Steps to reproduce:
This is a direct result of the patch. To observe it, with a Fabric client, one can use a client mod to invoke `getTime` of `ClientWorld` to read this value.

### Paper version:
Paper 1.16.4 263

------------------------

cc'ed the patch contributor for opinions. @Gabscap

**Comment by Gabscap** [comment]
You are right, this patch is not necessary anymore. I submitted a PR to remove it.
