### ISSUE TITLE
Hopper optimization

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#475]
Running latest paper build and I was wondering if there will be any more Hopper optimization coming? I Have 3 players on my server and we already have 20% load going to just hoppers. I'm going to start banning people from building stuff like this. But 20% load is still high just for this.

Picture of there hopper machine thingy: https://i.gyazo.com/13ca6654268f5cdcd0d8fd5d1825710c.jpg
Active hoppers at current time of timings: https://i.gyazo.com/3645ba58e53b666209a7e451e586c32d.png
Timings: https://timings.aikar.co/v2/?id=51d736c3cbef48ad8cb307560c9d996b&section=all

**Comment by jordanwilliams1** [comment]
I've got 

```
hopper:
  push-based: true
use-hopper-check: true
```

But Couldn't really find anymore optimization

**Comment by CeIebrimbor** [comment]
You can manipulate the ticking of hoppers in the spigot.yml. By setting "use-hopper-check" to true in paper, it will allow the use of the custom hopper mechanics set in spigot. By changing them, just know you are changing vanilla behavior and all Redstone contraptions that function on a sensitive tick requirement (based on vanilla) will most certainly break.

**Comment by CeIebrimbor** [comment]
More about possible future hopper improvements in #392

**Comment by AlfieC** [comment]
My work on hopper optimization is currently on hold - hoppers are not an issue on my server at the moment. However, I did make dramatic gains when it comes to this performance and as such will PR these at the appropriate times. 

The only thing stopping me from PRing these right now is that my main optimizations are on either 1.7 or 1.8 versions. I will start work on porting these to the latest versions, but this is not a priority for me right now. It's my understanding that @aikar runs on 1.9, and as such the same limitations may apply to him too.

**Comment by jordanwilliams1** [comment]
@AlfieC Thanks for the update.

**Comment by jordanwilliams1** [comment]
@CeIebrimbor Yes I Know. I Did the spigot for hoppers. Still use 20%+
