### ISSUE TITLE
Nerf trapped villagers?

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4752]
### Description of issue:
Trapped villagers are extremely common, extremely laggy, and found in trading halls. They attempt to path and calculate the mass of the sun or whatever shit they do that kills TPS. There should be some sorta optimization that reduces brain activity when trapped in a hole.

**Comment by ghost** [comment]
nerf-trapped-villagers: true
trapped-villagers-check-interval: 300
Under entity-activation-range in spigot.yml ^

**Comment by Chew** [comment]
This would be in paper.yml if implemented, we don't modify spigot.yml
