### ISSUE TITLE
PlayerInteractEntityEvent at Shopkeeper since latest build

### ISSUE THREAD

**Issue by AerWyn81** [PaperMC/Paper#4753]
## What behaviour is expected:
Open a shopkeeper interface when interact.

## What behaviour is observed:
Exception in console : https://pastebin.com/YgMmSXjr

## Steps/models to reproduce:
Start a server with the latest build of paper (271) and the latest version of Shopkeeper (2.12.0).

## Plugin list:
Paper / Shopkeeper

## Paper version:
Paper version git-Paper-271 (MC: 1.16.4)

## Anything else:
It seems to appear when a shopkeeper's inventory is filled, not when empty.

Shopkeeper developper figured out : 

> The issue is that the constructor of CraftMerchantRecipe creates a new nms.MerchantRecipe and assigns it to CraftMerchantRecipe.handle. However, the constructor of nms.MerchantRecipe in turn calls a newly added method (shouldIgnoreDiscounts, from commit https://github.com/PaperMC/Paper/commit/becb478cd5e25048e3fe8aa9dab5534ccb60e107) in the calling CraftMerchantRecipe. This method then attempts to access this nms.MerchantRecipe at CraftMerchantRecipe.handle, but which has not yet been initialized/assigned yet at the point (because this call originated from within the nms.MerchantRecipe constructor).

**Comment by Machine-Maker** [comment]
A possible solution is to add another argument to the nms.MerchantRecipe constructor that's used in the CraftMerchantRecipe constructor to pass the ignoreDiscounts boolean. That way it doesnt have to call the shouldIgnoreDiscounts method.

**Comment by Machine-Maker** [comment]
I believe #4755 from jmp just fixed this.

**Comment by Kooramah** [comment]
I can confirm that #4755 | paper-274 fixes this issue for Shopkeepers
