### ISSUE TITLE
Region file invalid sector warning when start server

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#4758]
### What behaviour is expected:

The server no writes region file invalid sector warning.

### What behaviour is observed:

The server writes region file invalid sector warning.
```
Region file ./world/region/r.-1.0.mca has an invalid sector at index: 428; size has to be > 0
Region file ./world/region/r.-1.0.mca has an invalid sector at index: 428; size has to be > 0
Region file ./world/region/r.-1.0.mca has an invalid sector at index: 428; size has to be > 0
Region file ./world/region/r.0.0.mca has an invalid sector at index: 0; size has to be > 0
Region file ./world/region/r.0.0.mca has an invalid sector at index: 0; size has to be > 0
```

### Steps/models to reproduce:

Start the server.

### Plugin list:
___A list of your plugins___
Plugins (19): AdvancedPortals, BetterGUI, ChatControl, ConditionalCommands, CoreProtect, EasySetSpawn*, ItemJoin, LPC, LuckPerms, NoCheatPlus, PlaceholderAPI, PlugMan, ProtocolLib, SkinsRestorer, SuperTrailsPro*, TAB, Vault, WDLCompanion*, WorldBorder

### Paper version:

This server is running Paper version git-Paper-275 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by Proximyst** [comment]
@MiniDigger Related to zero-padding?

**Comment by ghost** [comment]
Same issue here

`[13:45:36] [Paper RegionFile IO Thread/WARN]: Region file .\world\region\r.-1.-1.mca has an invalid sector at index: 823; size has to be > 0`

This issue only occurs with `paper-275` and above

**Comment by andris155** [comment]
![2020-11-13_15 46 48](https://user-images.githubusercontent.com/8324198/99084619-7b29f900-25c7-11eb-8773-2f6cc2afce25.png)
I confirm linked issue. Paper build 275 corrupt my server worlds...

**Comment by schoentoon** [comment]
I didn't run into any issues while testing this patch. Nor did @MiniDigger as I understood on Discord. Could a regionfile from before corruption perhaps be shared so it can hopefully be easier to reproduce and figure out the root cause of this?

**Comment by andris155** [comment]
[r.22.60.zip](https://github.com/PaperMC/Paper/files/5537830/r.22.60.zip)
This the good region file from my backup. 
This region file corrupted on the Paper build 275.
```
[06:43:21] [Paper RegionFile IO Thread/ERROR]: External chunk path ./spawn2/region/c.730.1942.mcc is not file
[15:23:53] [Paper RegionFile IO Thread/ERROR]: Chunk [730, 1942] header is truncated: expected 0 but read 0
```

**Comment by andris155** [comment]
[r.0.0.zip](https://github.com/PaperMC/Paper/files/5538017/r.0.0.zip)
This the good region file from my backup.
This region file corrupted on the Paper build 275.

`[15:45:04] [Paper RegionFile IO Thread/ERROR]: Declared size -871107081 of chunk [6, 12] is negative`

**Comment by schoentoon** [comment]
I can only reproduce the warning using the r.0.0 region file. However, this warning will also display on build 276 (so with the patch reverted)

**Comment by andris155** [comment]
I restored this file, and not loaded on build 275 and it works. Maybe the build 275 modify this file. I don't know.

**Comment by andris155** [comment]
I use build 274 and this version works perfectly.

**Comment by Chew** [comment]
Use build 276, should fix this.

**Comment by andris155** [comment]
[r.-1.0.zip](https://github.com/PaperMC/Paper/files/5538245/r.-1.0.zip)
This the good region file.
This region file cause warn message on the Paper build 275.

`[15:40:17] [Paper RegionFile IO Thread/WARN]: Region file ./world/region/r.-1.0.mca has an invalid sector at index: 362; size has to be > 0`

**Comment by Title666645** [comment]
![2021-03-18_16 59 13](https://user-images.githubusercontent.com/67227071/111657450-bb1a1a80-880b-11eb-9b45-f5e622f36d14.png)
![2021-03-18_16 59 24](https://user-images.githubusercontent.com/67227071/111657455-bce3de00-880b-11eb-9342-74288fc00c19.png)
![2021-03-18_16 59 30](https://user-images.githubusercontent.com/67227071/111657462-bf463800-880b-11eb-8dc0-0261ccb3ae3d.png)
![2021-03-18_16 59 40](https://user-images.githubusercontent.com/67227071/111657465-c0776500-880b-11eb-9711-605cefd475cf.png)
![2021-03-18_17 00 05](https://user-images.githubusercontent.com/67227071/111657471-c2412880-880b-11eb-8ab3-161c03beeb52.png)
![2021-03-18_17 00 15](https://user-images.githubusercontent.com/67227071/111657481-c4a38280-880b-11eb-991a-7e4198351a07.png)
![2021-03-18_17 00 23](https://user-images.githubusercontent.com/67227071/111657492-c66d4600-880b-11eb-9091-3ca216c611fa.png)
![2021-03-18_17 00 33](https://user-images.githubusercontent.com/67227071/111657499-c8cfa000-880b-11eb-805f-bf3e78b05e99.png)
![2021-03-18_17 00 36](https://user-images.githubusercontent.com/67227071/111657510-cbca9080-880b-11eb-84d9-63a497071d11.png)
![2021-03-18_17 00 39](https://user-images.githubusercontent.com/67227071/111657522-cec58100-880b-11eb-9287-8dfdf5b1f717.png)
![2021-03-18_17 00 42](https://user-images.githubusercontent.com/67227071/111657535-d08f4480-880b-11eb-991f-93b8b9aa392e.png)
![2021-03-18_17 00 50](https://user-images.githubusercontent.com/67227071/111657547-d4bb6200-880b-11eb-9667-2d2b56d441d0.png)
![2021-03-18_17 00 57](https://user-images.githubusercontent.com/67227071/111657560-d71dbc00-880b-11eb-881e-8cf64e6dfa0f.png)
![2021-03-18_17 01 08](https://user-images.githubusercontent.com/67227071/111657584-dd139d00-880b-11eb-80ec-b567890e81cf.png)
![2021-03-18_17 01 15](https://user-images.githubusercontent.com/67227071/111657592-dedd6080-880b-11eb-86ba-f49dbdab989d.png)

**Comment by electronicboy** [comment]
Please don't hijack outdated issues, create a new one, providing the FULL information, and ideally replication steps. Stuff like this is generally caused by closing the server improperly.
