### ISSUE TITLE
Creepers not spawning under trapdoors

### ISSUE THREAD

**Issue by meanjeans99** [PaperMC/Paper#4759]
I am running PaperMC 1.16.3 and I have a farm that will not spawn any creepers under ceiling mounted trapdoors.  When I remove the trapdoors, the farm will immediately spawn creepers, skeletons and zombies.

**Comment by electronicboy** [comment]
1.16.3 is no longer supported, if you can reproduce this on the latest version (please test this against vanilla, etc), maybe provide a better visual for what you're tryna replicate too, please create a new issue and fill in the template.
