### ISSUE TITLE
I can't start my PaperSpigot server (Crash)

### ISSUE THREAD

**Issue by bryanowen7** [PaperMC/Paper#476]
# Crash / Stacktrace

Hi!, I have many servers running on PaperSpigot, but this is the only one that is crashing every time I try to start it, I did some research and I checked the stacktrace but I can't recognize the error, I tried reinstalling my server with a recent backup (when it was running correctly), deleting the cache folder and and downloading PaperSpigot again, more information of version and plugins below. 

### Link/paste of stack trace:
http://pastebin.com/70sU15JU (The IP address of the server is replaced with XXX.XXX.XX.XX due to privacy)

### Plugin list: 
ASkyblock, AuctionHouse 3.2.1, ChatEx, CrateReloaded 1.3.67, CustomOreGen, EssentialsX 2.0.1, EssentialsXSpawn 2.0.1, FeatherBoard, HolographicDisplays, PermissionsEx 1.23.4, ShopGUIPlus, SilkSpawners, Skript, Superbvote, Vault, ViaVersion 0.9.8, Votifier 1.9, WorldEdit 6.1.3, WorldGuard

### Actions to reproduce (if known): 
Not known. The first time, it kicked with this message: "Timed out" and then the server closed, now I can't start it.

### Paper build number: 
Build #443

**Comment by kashike** [comment]
We don't support 1.8.8.
