### ISSUE TITLE
Add Bukkit recipe into BlockCookEvent/FurnaceSmeltEvent

### ISSUE THREAD

**Issue by ExcessiveAmountsOfZombies** [PaperMC/Paper#4761]
**Is your feature request related to a problem? Please describe.**
Currently if you want to get the recipe for one of the cooking events you'll just have to use the recipe iterator and then match the type to your current recipe (i.e iron ingots would return a smelting recipe and a blast furnace recipe and then you decide based on the block which recipe to use)

**Describe the solution you'd like**
Add a constructor with that accepts a Recipe so you can get it directly rather than using the iterator. 

**Describe alternatives you've considered**
just using the recipe iterator and then filtering the couple of results it gives back works as well.

EDIT: I did make the changes if this does get accepted, no idea if the PR format is properly done but it's there
https://github.com/ExcessiveAmountsOfZombies/Paper/commit/15a3e09cd37b71b86cf7f783643d6614bc080da6

**Comment by Machine-Maker** [comment]
@ExcessiveAmountsOfZombies you can def make the pr, its not formatted correctly, but if you want, you can take a look at CONTRIBUTING.md for the format guidelines.

**Comment by MiniDigger** [comment]
@ExcessiveAmountsOfZombies we will gladly help you make that commit into a proper PR, its mostly just missing // Paper comments.
But if you don't want to, thats fine to, but please say so, then somebody can pick up your patch and contribute it (with keeping you as the author of course)
