### ISSUE TITLE
/teammsg (or /tm) cannot be executed without OP

### ISSUE THREAD

**Issue by EssieFir** [PaperMC/Paper#4774]
### What behaviour is expected:
___What you expected to see___
A message to the team

### What behaviour is observed:
___What you actually saw___
"I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
While in a team, execute the command /tm or /teammsg 

### Plugin list:
___A list of your plugins___
None

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
git-Paper-279 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Machine-Maker** [comment]
Is this maybe a permissions plugin issue? Wiki says no op is required for that command.

**Comment by EssieFir** [comment]
My plugins folder has nothing in it.
(except for bstats, but that appears to be auto-generated)

**Comment by Chew** [comment]
Confirmed. `minecraft.command.teammsg` is undefined for non-ops according to LP verbose. Oping/deoping didn't change this though.
Vanilla behavior, btw, works fine. Not sure what messes with this.

**Comment by electronicboy** [comment]
`org.bukkit.craftbukkit.util.permissions.CommandPermissions` defines default perms for vanilla commands, etc, looks like it's not been updated in a little while

**Comment by Chew** [comment]
Should this be fixed here or brought upstream?

**Comment by MiniDigger** [comment]
its fine to be fixed here, if somebody wants to upstream this its obviously better
