### ISSUE TITLE
Invalid chest type returned 

### ISSUE THREAD

**Issue by jvdoorn** [PaperMC/Paper#4775]
### What behaviour is expected:
You can check a chests type (`LEFT`, `RIGHT`or `SINGLE`) by using the following code:

```java
// other imports
import org.bukkit.block.data.type.Chest;

// within some method or listener
Chest chest = (Chest) block.getState().getBlockData();
System.out.println(chest.getType());
```

If we look at the description of the `Type`s we expect a single chest to return `SINGLE`, the left chest to return `LEFT` and the right chest to return `RIGHT`. 

```java
/**
 * Type of this chest block.
 * <br>
 * NB: Left and right are relative to the chest itself, i.e opposite to what
 * a player placing the appropriate block would see.
 */
public enum Type {
    /**
     * The chest is not linked to any others and contains only one 27 slot
     * inventory.
     */
    SINGLE,
    /**
     * The chest is the left hand side of a double chest and shares a 54
     * block inventory with the chest to its right.
     */
    LEFT,
    /**
     * The chest is the right hand side of a double chest and shares a 54
     * block inventory with the chest to its left.
     */
    RIGHT;
 }
```
(Above code is taken from the `bukkit` source.)

### What behaviour is observed:
When clicking a single chest the type is `SINGLE`, this is expected. However when clicking the right chest the type is `LEFT` and when clicking the left chest the type is `RIGHT`. These are inverted!

### Steps/models to reproduce:
Place a single and a double chest, use a simple listener to log the type:

```java
@EventHandler
private void testChestType(PlayerInteractEvent e) {
    Block block = e.getClickedBlock();
    if (block.getType() == Material.CHEST || block.getType() == Material.TRAPPED_CHEST) {
        Chest chest = (Chest) block.getState().getBlockData();
        System.out.println(chest.getType());
    }
}
```

### Plugin list:
Luckperms, Essentials and Vault. 

### Paper version:
`This server is running Paper version git-Paper-390 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`.

### Anything else:
If this is not the right repository to report this to please point me in the right direction.

**Comment by Proximyst** [comment]
This might have to do with a mismatch in ordinals between some NMS enum and the Bukkit one.

**Comment by Machine-Maker** [comment]
This seems to also affect 1.16. Just tested it. Left shows right, and right shows left on build 282 (1.16)

EDIT: After looking at the F3 screen, that *also* shows left for right and right for left. That would suggest its a mojang bug?

![image](https://user-images.githubusercontent.com/15055071/99310341-bd457b80-280f-11eb-98fd-a70eccfa158d.png)
![image](https://user-images.githubusercontent.com/15055071/99310349-c20a2f80-280f-11eb-9563-9770e16ff7d8.png)

**Comment by MiniDigger** [comment]
what does a vanilla single player world do?

**Comment by Machine-Maker** [comment]
Just booted up a new vanilla 1.16.4 world (singleplayer) and they are still reversed. So def a mojang issue. Should this be fixed here or be made an issue on the jira?

**Comment by jvdoorn** [comment]
I have created an issue on the [Jira](https://bugs.mojang.com/browse/MC-206093). I'll leave it to you guys how you want to handle it here.

**Comment by Brokkonaut** [comment]
I would not call it a bug. It just depends on viewing direction what is left and what is right. If you look away from the chest through the front (that is what mojang is using for other blockstate properties like "facing" too) it is the correct description. For blocks it might not be so intuitive but for example for living entities it is intuitive to see the directions through their eyes. And it is useful to have it consistent for everything in minecraft.

**Comment by Machine-Maker** [comment]
I mean, either this is, or isn’t an issue depending on what perspective you are looking from for chest sides. Should be easy to say, yes it’s a bug, or no it’s not.
