### ISSUE TITLE
Dog attacks skeleton when sat

### ISSUE THREAD

**Issue by Ellipogus** [PaperMC/Paper#4776]
### What behaviour is expected:
___The dog stayed sat and does not do anything___

### What behaviour is observed:
___the dog was in a sitting state but moved towards the skeleton and attacked it___

### Steps/models to reproduce:
___Get a skeleton to attack a tamed dog when it is sat___

### Plugin list:
___none___

### Paper version:
___Paper 282 Mc: 1.16.4___

### Anything else:
___This doesn't happen in vanilla single player___

**Comment by Chew** [comment]
Unfortunately, I cannot reproduce, this would be hilarious if it worked though.

My steps to reproduce (that failed)
1) Spawn and tame dog
2) Spawn skeleton
3) Attack/get attacked by said skeleton
4) Dog growls, but does not move.

My guess is your client desynced from the server.
