### ISSUE TITLE
Allow Canceling the EntityUnleashEvent

### ISSUE THREAD

**Issue by Owen1212055** [PaperMC/Paper#4780]
**Is your feature request related to a problem? Please describe.**
Currently, I am trying to cancel leashes being broken when the leash holder gets too far away from the entity. However, currently, it seems that the event I want is not cancellable. This is not part of any issue, more like missing functionality.

**Describe the solution you'd like**
I would like to be able to cancel this event, and if it is canceled the leash will not break and no leash item will be dropped. 

In fact, being able to get the item entity that was spawned would allow us to kill/change it as well. Although I think it being cancellable would be optimal. 
**Describe alternatives you've considered**
So I've tried to just teleport the mob closer, kill the item that it spawned and releash the entity but it still doesn't allow the leash to go past its maximum length without breaking. 

**Additional context**
N/A

**Comment by Machine-Maker** [comment]
@Owen1212055 is your goal to extend the reach of the lead? You would need to cancel the event every tick essentially for as long as you wanted the lead to not break. Would a world configuration option like #4992 work better?

**Comment by Owen1212055** [comment]
> @Owen1212055 is your goal to extend the reach of the lead? You would need to cancel the event every tick essentially for as long as you wanted the lead to not break. Would a world configuration option like #4992 work better?

Having it as an event would allow me to customize which entities should be able to be unleashed and ones that shouldn't be able to. A configuration option limits this.

After all, unleashing summons an item entity and breaks the lead making it quite a pain to deal with. So cancelling it would allow for that item not to be spawned (maybe we could even set the item via the event) and so the entity wouldn't be unleashed.

**Comment by Machine-Maker** [comment]
Yeah, I went ahead and pr'd both. #4993

**Comment by Owen1212055** [comment]
Awesome, thank you so much!
