### ISSUE TITLE
ItemFrameMeta to SPAWN invisible item frames

### ISSUE THREAD

**Issue by Rincewind34** [PaperMC/Paper#4787]
**Is your feature request related to a problem? Please describe.**
I would like to create the ITEM, that can "spawn" an invisible item frame introduced in 1.16.

**Describe the solution you'd like**
A new subclass of ItemMeta with a new method

**Describe alternatives you've considered**
Current work around: meta.getPersistentDataContainer().set(new NamespacedKey(plugin, "invisible"), PersistentDataType.BYTE, (byte) 1);

**Comment by kennytv** [comment]
https://papermc.io/javadocs/paper/1.16/org/bukkit/entity/ItemFrame.html#setVisible-boolean-

**Comment by kennytv** [comment]
Whoops sorry, misread it. 🤔

**Comment by Rincewind34** [comment]
The title was a little bit misleading. I changed it ;)

**Comment by lynxplay** [comment]
Closing this as it will be implemented via properly API lands. Exposing meta API for this seems like more trouble than what this feature is worth to maintain.

I hope you can understand, we are going to work hard on the property API so this should be possible sooner than later :)

**Comment by codeHusky** [comment]
This didn't end up getting implemented in the DataComponent PR, is there still a current plan to implement this or was the ability to affect ItemFrame visibility / fixed state on an ItemMeta level (as well as the other CraftMetaEntityTag items)? @Owen1212055

**Comment by electronicboy** [comment]
The issue is that there is no current means of representing an entity tag in the API, and the desire to deal with this while mojang is heavily churning how they represent data in the server is ultra low

**Comment by codeHusky** [comment]
Gotcha, makes sense, glad it's on the radar at least. Will work around the API gap in the meantime
