### ISSUE TITLE
TNT Cannon Bug

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#479]
# Incompatibility (Bug)

### What behaviour is expected:
When using a TNT sand stacker cannon several sand should stack per shot, and sand should not be destroyed

### What behaviour is observed:
Even though TNT Cannon mechanics fixes are all enabled, sand stacking does not work, it fires the sand and the sand hits the wall but when falling down to the bottom it will only stack 1 and destroy the others.

### Steps/models to reproduce:
https://www.youtube.com/watch?v=tm4gb4HvqNA&t=3s if you build this cannon and try using it it wont stack more then 1 sand

### Plugin list:
https://gyazo.com/c28826320367cdc380e416ae06b3535e

### Paper build number:
git-Paper-809 (MC:1.10.2)

**Comment by zachbr** [comment]
Merged into our existing ticket for tracking these. GH-329
