### ISSUE TITLE
Request for async APIs for overriding the built-in chunk/world data I/O

### ISSUE THREAD

**Issue by DWVoid** [PaperMC/Paper#4791]
**Is your feature request related to a problem? Please describe.**
The vanilla and Bukkit chunk-storage modal is not very convenient for servers managing the session-based world maps, or at least non-trivial to use.

**Describe the solution you'd like**
Would like a set of APIs which allows plugins to hook custom implementations of persistent world data sources. Also, I would prefer these APIs to be async to avoid stalling main thread while doing I/O and to offload serialization tasks to worker threads.

**Describe alternatives you've considered**
There has been no alternative so far as I observed.

**Comment by Malfrador** [comment]
Regarding alternatives: There is the SlimeWorldManager plugin which does exactly this, custom world storage for session based worlds. 

However, this needs a lot of modifications to the server code to work (including a classmodifier you need to use), so I can see the use of such APIs to make that easier.

**Comment by electronicboy** [comment]
We've had this suggestion before and dicussed it before, the maintainability of such an API and the fact that a fair chunk of the I/O section would need to be re-written to accommodate this properly, throws a huge STOP sign in the name of sanity and maintainability.
