### ISSUE TITLE
Visual glitch with custom hearts container

### ISSUE THREAD

**Issue by Doc94** [PaperMC/Paper#4793]
### What behaviour is expected:
If you have custom heart containers (example 40 not the default 20) when you join you can see all containers filled.

### What behaviour is observed:
When join (you have full life) the client only show 20 hearts filled and the another 20 not filled, if you take damaage then the client reload the rest of containers full.

### Steps/models to reproduce:
1. Join to the server
2. Run this command `/attribute @s minecraft:generic.max_health base set 40`
3. Get all the containers filled
4. Disconnect from server
5. Reconnect to Server
6. Take damage

### Plugin list:
AsyncWorldEdit, ConterCraft, CoreProtect, LibsDisguises, LuckPerms, PlugMan, ProtocolLib, WorldEdit

### Paper version:
git-Paper-288 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Anything else:
Gif of issue: https://imgur.com/rp8sWqA

**Comment by Doc94** [comment]
Its a Spigot bug but they cant find the cause of issue: https://hub.spigotmc.org/jira/browse/SPIGOT-6250

**Comment by HexedHero** [comment]
Thought I'd mention that I've been using a workaround fix in my plugin for a while now, simply just doing
`Common.sendPacketToPlayer(event.getPlayer(), new PacketPlayOutUpdateAttributes(((CraftPlayer) event.getPlayer()).getHandle().getId(), ((CraftPlayer) event.getPlayer()).getHandle().getAttributeMap().b()));`
on PlayerJoinEvent

**Comment by Owen1212055** [comment]
Can reproduce as of 1.19.1, looking into this myself.

**Comment by Owen1212055** [comment]
Is this able to be reproduced as of 1.19.2 using the chunk system recode? 

Some testing was done and it seems that it resolves this issue, but my PR might serve a purpose as there is no reason to be resending the player tracker data like that anyways.

**Comment by Doc94** [comment]
Finally this issue looks fixed then i prefer close because the main issue is handled 🍡
