### ISSUE TITLE
Curse of Binding Items Disappear on Death

### ISSUE THREAD

**Issue by Stixil** [PaperMC/Paper#4799]
### What behaviour is expected:
Item should drop on the ground like in vanilla Minecraft.

### What behaviour is observed:
Item vanishes completely on death, like the Curse of Vanishing would.

### Steps/models to reproduce:
Obtain curse of binding armor. Die. It disappears whether worn or in the player inventory.

### Plugin list:
[16:50:47 INFO]: Plugins (0): 

### Paper version:
[16:50:54 INFO]: This server is running Paper version git-Paper-288 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[16:50:54 INFO]: Checking version, please wait...
[16:50:55 INFO]: Previous version: git-Paper-245 (MC: 1.16.3)
[16:50:55 INFO]: You are running the latest version

### Anything else:
Looks like curse of vanishing attributes are being applied to binding. I can supply video if it can't be reproduced, though it should reproduce every time.

**Comment by Proximyst** [comment]
Does it work upstream (i.e. Spigot)?

**Comment by kristibektashi** [comment]
Cooperate needs you to find the differences between curse of binding and curse of vanishing
Paper: They are the same picture

**Comment by Stixil** [comment]
Yes, it does drop correctly under Spigot 1.16.4, just not on PaperMC.

I uploaded a short video to demonstrate this: https://www.youtube.com/watch?v=IHHhFsRB4X8

**Comment by Toshimichi0915** [comment]
I cannot reproduce the issue.
I both tried your version(288) and latest paper version(344).
Did you change anything in the config?

**Comment by Proximyst** [comment]
Cannot reproduce on `git-Paper-579`.
