### ISSUE TITLE
Paper 1.11 Release?

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#480]
I Was wondering if the paper team were working on 1.11? If you are, do you have a rough estimation? Feel free to close this / yell at me. I Was going to post this on (aquifermc.org) but its been down for around a day now :(

**Comment by kashike** [comment]
![x](http://previews.123rf.com/images/808isgreat/808isgreat1206/808isgreat120600013/14152844-Man-yelling-with-hands-in-air-on-a-white-background-Stock-Photo.jpg)

It'll be out when it is out.
