### ISSUE TITLE
Feature: BlockPistonCheckEvent

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4802]
**Is your feature request related to a problem? Please describe.**
3 Words: Movable Tile Entities.

**Describe the solution you'd like**
I want to achieve it by 1) detecting when block is checked for immovability during an attempted piston push or pull (with the BlockPistonCheckEvent),  2) store the NBT of the block somewhere and set the block to a movable block, like cobblestone 3) override the default behavior of the event with a method, perhaps `setCanMove(boolean)` 4) wait for the blocks to be pushed and 5) use another method, like `getPushDirection()` to calculate the new block position and place the tile entity back into the world from memory.

**Describe alternatives you've considered**
Honestly, there's not many other ways to do this. Checking every redstone signal in-world is inconsistent and complicated, and may not even be directly next to the piston being powered. There's also the idea of a "BlockPoweredEvent" but that could get laggy.

**Comment by jpenilla** [comment]
Something like movable Tile Entities needs to be implemented in the server, not with a plugin (at least for a halfway decent implementation). Tuinity used to include a patch for movable TEs but it was dropped after some data loss issues were discovered. Some changes to how TEs are stored in 1.17 could make a patch like this more practical, but again this is a server level thing, not a plugin thing.

**Comment by lynxplay** [comment]
Given how little interest this issue has received and generally how messed up the logic for moving tile entities would be anyway, I feel like this is not something we are interested in at this point in time.

I'll be closing this issue, if large interest in this feature returns, please comment here and I'll gladly reopen this!
