### ISSUE TITLE
Spectators generating chunks with spectatorsGenerateChunks false

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4805]
###  Timings or Profile link:
https://imgur.com/a/jw88aPY

### Description of issue:
**EntityHuman.eu()** is called for spectators, this method that seems to be for updating the player's pose calls **this.world.getCubes(this, this.d(entitypose).shrink(1.0E-7D))** which causes a chunk load, even when the spectator is in an unloaded chunk with game-rule spectatorsGenerateChunks set to false. Fixing this bug will also be important for the implementation of https://github.com/PaperMC/Paper/pull/4804

### Paper version:
git-paper-288 (1.16.4, latest paper build at time of posting)

**Comment by ChimneySwift** [comment]
It appears this error occurs upstream in both [Spigot](https://i.imgur.com/iFeZT1a.png) and also in [vanilla](https://i.imgur.com/2H8l9CR.png).

Both were tested in spectator mode using gamerule spectatorsGenerateChunks set to false.

**Comment by Chew** [comment]
Is there any issue open on Mojira so we can track this?

**Comment by HexedHero** [comment]
> Is there any issue open on Mojira so we can track this?

It seems to work fine in vanilla idk how Swift tested it, the gamerule stops Spectator players from genning chunks but still allows them to load pre-rendered ones
https://i.imgur.com/d0UVkXa.mp4

**Comment by ChimneySwift** [comment]
> It seems to work fine in vanilla idk how Swift tested it, the gamerule stops Spectator players from genning chunks but still allows them to load pre-rendered ones
> https://i.imgur.com/d0UVkXa.mp4

Look at your map using MCEdit or MCA Selector, or something which directly reads the chunks from the disk. You can clearly see from my original screenshots that chunks are in fact generated in vanilla.

PlayerChunkMap is actually working correctly and not creating any chunk load tickets for those chunks (thus why they are never actually sent to the client). This is also supported by the fact that chunks aren't generated for the full client view distance, only the chunks the client is directly in. 

Based on my testing so far and along the lines of the original issue, it appears as though there are various checks in place (Such as the fall damage check) which get the chunk a player is in using getChunk or similar methods, which results in that chunk being loaded/generated if it isn't already. Obviously many of these checks shouldn't need to be run at all if they player is a spectator or above the chunks, so resolving this issue could potentially be a performance saving measure also.

**Comment by ChimneySwift** [comment]
> Is there any issue open on Mojira so we can track this?

I can't find any open Mojira issues for this

**Comment by ChimneySwift** [comment]
Looks like I was indeed correct on my initial assumption. Used stacktrace to determine all the methods which call getChunk and spent the last several hours modifying various methods to ensure they don't cause chunks to load/generate where it wouldn't make sense and now the bug appears to be fixed.

Changes are still a bit messy so I'll have to give them a tidy up before publishing what I have.

I'm assuming I should probably open a Mojira issue for this in addition?
