### ISSUE TITLE
Command Not Working

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4810]
**Is your feature request related to a problem? Please describe.**
/execute as @e[type=minecraft:ender_pearl] run data modify entity @s Owner set from @e[tag=a1] UUID command wasn't working in paper bukkit.

**Describe the solution you'd like**
Please Make Owner Tag.

**Information**
PaperMC 1.16.4 288 Build
Ubuntu 20.04 LTS
Version : Minecraft 1.16.4
No Console Stacktree
I will made new issues.

**Comment by Machine-Maker** [comment]
> Wasn't working

This isn't a great description about the problem. Did you get a big red message saying something went wrong, or a giant stacktrace in the console, or the command didn't do what it was supposed to do. 

The syntax of the command *looks* correct.

**Comment by Chew** [comment]
You are missing critical portions of the template.
Please list your plugins and Paper `/version` output. Additionally, if you are using plugins, please reproduce without them.

Optionally, reproduce on a fresh instance of Spigot and CraftBukkit as well to confirm this isn't an upstream issue.

**Comment by ghost** [comment]
@Machine-Maker @Chew

**Comment by Machine-Maker** [comment]
You didn't mention any plugins you might have? Also I still don't know what "wasn't working" means. Is it not setting the Owner tag on ender_pearls? I don't know what the outcome is supposed to be. You are still missing key parts of the template, or rather you used the feature request template for *NOT* a feature request. Take a look [here](https://github.com/PaperMC/Paper/blob/master/.github/ISSUE_TEMPLATE/behavior-bug---plugin-incompatibility.md), and fill in some more of those headers in your original post.

**Comment by Titaniumtown** [comment]
> @Machine-Maker @Chew

you just pinged them randomly lol.

**Comment by Chew** [comment]
And so did you...

**Comment by ghost** [comment]
I will make new issues.

**Comment by Titaniumtown** [comment]
Why?

**Comment by Chew** [comment]
They never provided the information we needed. Can't do much with such vague information. They haven't opened a new issue yet either it looks like.
