### ISSUE TITLE
[Request] Zombie break door in lower difficulty than hard

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#4811]
**Is your feature request related to a problem? Please describe.**
I would like to request make zombies break wooden doors in normal difficulty or easy.

**Describe the solution you'd like**
I don't like play hard mode because its to hard. And I want this request feature from hard mode to normal mode.

**Describe alternatives you've considered**
Add into config of Paper a feature "zombie-break-door-all-difficulty" or something like this thing.

**Additional context**
None.

**Comment by aikar** [comment]
I've had this myself for years heh, just need to port it to paper

**Comment by DarkEyeDragon** [comment]
Seems like something a plugin should do in my opinion. These are core mechanics.

**Comment by Machine-Maker** [comment]
Paper already has a config for zombie infection chance, that is a mechanic equally as "core" as this. A config for this seems perfectly in line with other configs paper already has.
