### ISSUE TITLE
Lead Duplication with End Portal

### ISSUE THREAD

**Issue by brothanb** [PaperMC/Paper#4814]
### What behaviour is expected:
Lead should not drop as item when animal goes through end portal

### What behaviour is observed:
The lead drops as an item when the animal goes through the end portal.  When you follow, the animal is attached to a new lead in the player's hand.

### Steps/models to reproduce:
Create an end portal.
Spawn an animal.  (I used a mooshroom.)
Attach animal to lead.
Lead the animal over the end portal.   The lead will drop.
Enter the end portal.   The animal will be attached to your lead and the dropped lead either be on the ground or in your inventory.

### Plugin list:
None.   This was reproduced without any plugins loaded.

### Paper version:
[13:26:53 INFO]: This server is running Paper version git-Paper-296 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Anything else:
This does not occur with Vanilla or Spigot.

**Comment by brothanb** [comment]
It still happens build 345.   It appears that the lead breaks/drops when the mooshroom enters the portal.  (https://youtu.be/_0VUymAkNoQ)

**Comment by Proximyst** [comment]
The video shows it being fixed.

Forgot closing this when merging. /closed

**Comment by brothanb** [comment]
The video starts with one lead and ends with two.

**Comment by Proximyst** [comment]
Because you're in creative mode, so you don't consume the one you give to the mob, and the mob then drops it when it goes through the portal.

**Comment by brothanb** [comment]
OK..  What was throwing me off is that even in Creative on Vanilla, the lead doesn't drop but stays attached.  (https://youtu.be/rT0q1eYRU4A).    I agree it's not an issue for creative mode and doesn't duplicate the lead in survival.
