### ISSUE TITLE
[Bug] Undeads are unable to pick up items

### ISSUE THREAD

**Issue by Zorock666** [PaperMC/Paper#4818]
### What behaviour is expected:
Zombies, Skeletons, Wither Skeletons, and Zombie Piglins should all be able to pick up items / weapons / armor, on occasion, as long as Difficult =/= easy, and gamerule mobGriefing is True.

### What behaviour is observed:
Despite the difficulty being Hard, and mobGriefing being True, mobs are unable to pick up any items at all.

### Steps/models to reproduce:
1. Make completely new Paper-296 server. Run it. Ensure gamerule and difficulty are set correctly.
2. Throw stuff on randomly spawned Zombies, Skeletons, Wither Skeletons, and Zombie Piglins, and see that they do not pick up items at all.
or
3. Make a long tube with items along the bottom, and spawn thousands of mobs inside, and see that they do not pick up items at all.

Using the command /paper version it mentions that I'm on the latest paper version and API version.

### Plugin list:
None at all

### Paper version:
"This server is running Paper version git-Paper-296 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)"

### Anything else:
Check your code I suppose?  I used to work fine. I can't be sure exactly which version it worked fine in though, as it's one of those things you don't really keep an eye on.

**Comment by Zorock666** [comment]
Oh, forgot to mention that Piglins can still pick up gold just fine, and Endermen can pick up blocks fine too.
And I've tested that in Vanilla MC, 1.16.4, the Zombies can pick up items fine as well.

**Comment by Machine-Maker** [comment]
Ok, just did some more testing, and zombies will only have a chance of having CanPickUpLoot being true if the difficulty is hard. So the gamemode can't be easy OR hard. Once I put the world into hard, mobs could pick up stuff again.

**Comment by Machine-Maker** [comment]
Looking further into the code, the amount of time that has passed on the server also play's a factor. My guess is, as more time passes, the chance the mobs will pick up stuff will increase and start to work on lower difficulties.

**Comment by Zorock666** [comment]
> Looking further into the code, the amount of time that has passed on the server also play's a factor. My guess is, as more time passes, the chance the mobs will pick up stuff will increase and start to work on lower difficulties.

Yea, in vanilla the pick-up rate is dependent on Difficulty and the chance of picking up items increases with Local Difficulty. On Easy they never pick up items. On Normal difficulty, it starts at 0%, but they start to pick up items after 3 ingame days. On Hard it starts around 6-7% I believe. So when you spawn a couple thousand zombies, odds are one of them should pick up something. On my actual server (not the clean one mentioned in the Issue post), we're on day 36264, and the issue is still there.

It really is an issue with papermc.

https://minecraft.gamepedia.com/Difficulty

**Comment by Machine-Maker** [comment]
I just set my day to 36264 (Normal difficulty) and spawned in a zombie. First one, picked up my dirt block.

**Comment by Chew** [comment]
Does this have to do with local difficulty?

**Comment by Zorock666** [comment]
So, I redid my own steps, and now, for some reason they decided that picking up items is a good idea. Just hard-mode and mobgriefing = true. All that's different is the seed (random on first startup).
So no idea what's wrong... Guess I do have a plugin somewhere that messes with things.. You can close this I suppose. Or continue to investigate if there's some super-specific case in which mobs don't pick up items, despite all variables suggesting they should. But I don't blame you if you don't.

**Comment by Machine-Maker** [comment]
I couldn't find anything broken with it once I understood that on normal mode, it takes a few in game days for mobs to even have a tiny chance to pick something up.

**Comment by Machine-Maker** [comment]
> Does this have to do with local difficulty?

Yes, I believe it does. Takes into account some number based on the chunk, and the world age, and the world difficulty and comes up with a multiplier it applies to the 55% chance for a mob to be able to pick up items.

**Comment by Zorock666** [comment]
> > Does this have to do with local difficulty?
> 
> Yes, I believe it does. Takes into account some number based on the chunk, and the world age, and the world difficulty and comes up with a multiplier it applies to the 55% chance for a mob to be able to pick up items.

It only matters on Normal difficulty, not on Hard. On Hard they can pick up items from the very beginning. Which is what I tested the first time, which for some unknown reason didn't work, but the 2nd time it did work. (I deleted all folders and files except the .jar and .bat for starting a new server).
So unless there's an inconsistency somewhere that only applies sometimes, which I kinda doubt myself, it's okay to mark this as solved/unnecessary bug report.

**Comment by Machine-Maker** [comment]
The local difficulty matters on both normal and hard. It affects the chance of the mob being able to pick up items.

**Comment by Zorock666** [comment]
> The local difficulty matters on both normal and hard. It affects the chance of the mob being able to pick up items.

Yes, but on Hard it doesn't affect whether they *can*. Just the chance (Which I think starts around 6-7%). On Normal they literally can't for a few in-game days.

**Comment by Machine-Maker** [comment]
There is no difference, there isn't something hard coded so it's not possible right away on Normal, that's just how the math works out. The chance is the same thing as "whether they can".
