### ISSUE TITLE
Exception when mounting Entities

### ISSUE THREAD

**Issue by minoneer** [PaperMC/Paper#482]
When mounting an entity (tested with horse and pig), paper throws NPEs and the mounted entity disappears.

Stacktrace:
http://hastebin.com/iqaqexawer.md

Paper version git-Paper-917 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Yep, should be fixed shortly.

**Comment by zachbr** [comment]
Should be fixed in builds **918+**

Edit: err 918

**Comment by minoneer** [comment]
Great, works again as expected. Thanks!
