### ISSUE TITLE
[Crash] AxisAlignedBB.c

### ISSUE THREAD

**Issue by MedicOP** [PaperMC/Paper#4822]
### Link/paste of stack trace

https://pastebin.com/raw/9XPqi0dh

### Plugin list:
AAC-4.4.2, AACPlus, AdvancedLottery, AuctionGUIPlus, BannerMaker, BuycraftX, ChatManager, Citizens, CleanroomGenerator-1.1.0, CollectorsX, CombatLogX, CommandNPC, CompassNavigation, ConditionalCommands, CrateReloaded, DeluxeCoinflip-1.8.6, EssentialsX-2.18.1.12, EssentialsXSpawn-2.18.1.12, ExecuteEverywhere, FarmLimiter, HeadDatabase, HolographicDisplays, InfiniteVoucher-2.0.7, Janus, LibsDisguises, MCAuthenticator, MiniaturePets, MobArena, Multiverse-Core-4.1.0, NightV2.0, NoSpawnerChange, OpenInv, PermissionsEx, PlaceholderAPI, PlayerParticles_v7.15, PlayerShopGUIPlus, PlayerVaultsX, PlugMan, ProtocolLib, RedstoneClockDetector, Shop, ShopGUIPlus, SimpleLay, SimplePets, SuperiorSkyblock, TradePlus-3.79.2, UltimateCatcher, Vault, ViaBackwards, ViaRewind-Legacy-Support, ViaRewind, ViaVersion, WildStacker, WildTools, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Don't know, it just happens out of the blue multiple times already

### Paper version:
This server is running Paper version git-Paper-83c89d7af (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Your server took too long to tick, without the full trace, we can't really say, but, that method call is so simple that it cannot be the cause of a hang, chances are there are just a lot of calls through there, too many items in the world, etc.

We'd need the full set of logs, but, this is not really suitable for an bug report, please use discord for support
