### ISSUE TITLE
Weird entity spawning behavior

### ISSUE THREAD

**Issue by evhan751** [PaperMC/Paper#4823]
### **What behaviour is expected:**
High number of mob spawns in farms, 

### **What behaviour is observed:**
Very low number of entities, around 4-5 constantly.

### **Steps/models to reproduce:**
Every mob farm i've made has this problem, but it almosts completly breaks guardian and slmie farms, because of the rates produces.

If you want to test it, you can use this world download which I used as a reference. 
https://www.youtube.com/watch?v=VA4R14oL_dg

### **Plugin list:**
None

### **Paper version:**
I've had this issue for about this for the last year, maybe last 2 years. I am not aware of the version.

### **Anything else:**
I tested the difference with the slime farm. With Paper, there are only 4-5 entities shown in the f3 menu, whereas I would get 25-30 with Vanilla.

**Comment by Machine-Maker** [comment]
I mean, a lot of this depends on your configured mob caps, in the various .yml files.

**Comment by electronicboy** [comment]
Current version?
timings report?

**Comment by evhan751** [comment]
I haven't touched any of the .yml files. Mobs seem to spawn fine usually, but not in these cases.

Current version : 1.16.4, I've also observed this with other versions of 1.16, 1.15 and 1.14.
How do I get the timing reports ?

**Comment by electronicboy** [comment]
`./timings report`

**Comment by evhan751** [comment]
https://timings.aikar.co/?id=ed10f6f8916844b4aa38e083903aa89e

**Comment by e-im** [comment]
Since the creation of this issue many issues regarding this have been resolved, and additionally the `/paper mobcaps` and `/paper playermobcaps` commands have been added in an attempt to make debugging issues like this easier. If you are still experiencing this issue in the same way on 1.17.1, leave a comment.
