### ISSUE TITLE
Piglin chest open check

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#4828]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
Add support for Piglins; I mean when player open chest and near is Piglin then the there should be an event added.

**Describe alternatives you've considered**
Add also into config to check this think and cancel when is set to true
player-near-piglin-chest-open-attack

**Additional context**
Everything said above.

**Comment by electronicboy** [comment]
What effect do piglins have on players opening chests?

**Comment by aurorasmiles** [comment]
They become aggressive towards that player, even when they are wearing gold armor (this also happens when a player breaks a chest)

**Comment by Misio12320** [comment]
> They become aggressive towards that player, even when they are wearing gold armor (this also happens when a player breaks a chest)
Yep, this I mean. Good job.

**Comment by Machine-Maker** [comment]
Exstaleliarmus!
