### ISSUE TITLE
Component support

### ISSUE THREAD

**Issue by kashike** [PaperMC/Paper#4830]
- [x] `Player#displayName`
  - Not used for chat yet
- [x] `Player#kick`
- [x] `ItemMeta#displayName`
- [x] `ItemMeta#lore`
- [x] `Nameable#customName`
  - [x] `Entity#customName`
  - [x] `Beacon#customName`
  - [x] `Container#customName`
  - [x] `EnchantingTable#customName`
- [x] `Server#motd` (#4852)
- [x] `BookMeta#pages` (#4852)
- [x] `Server#createInventory`
  - [x] `Bukkit#createInventory`
- [x] `Enchantment#displayName(int level)` (translatable component)

**Comment by Proximyst** [comment]
Signs ~~, chat, boss bar, action bar~~

**Comment by yannicklamprecht** [comment]
- [x] Team, 
- [x] Scoreboard where applicable.

**Comment by Machine-Maker** [comment]
Enchantment#displayName was already added. 

Unless there is something else that wasn't mentioned here, I believe everything listed here is in.
