### ISSUE TITLE
Server does not restart on crashes, process hanging

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#4831]
When I updated to 1.16 my server stopped restarting on crashes, my log mentions "hard crash" which may have something to do with it. 

Log: https://mcpaste.io/0b33791ae5df6570

I believe the issue has something to do with watchdog not shutting down correctly due to it deadlocking somewhere?
I created an issue on the pterodactyl github here: https://github.com/pterodactyl/panel/issues/2668 where the developer commented "We don't detect process hanging which is what is happening there. It says stopping but never stops, so to Wings the server container is still running. Crash detection only triggers if the container itself stops."

This is a really annoying issue because any time the server crashes I need to manually kill the server instance and then start it again.

### Paper version:
git-Paper-"1916ab2b" (MC: 1.16.3)

**Comment by HexedHero** [comment]
Non supported version.

**Comment by kashike** [comment]
Please update to 1.16.4 and re-test. If this is still an issue, let us know.
