### ISSUE TITLE
Server lagging and crashing

### ISSUE THREAD

**Issue by 2builders2tools** [PaperMC/Paper#4839]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___ 
![image](https://user-images.githubusercontent.com/73716286/101044198-13732800-354d-11eb-8034-fe3cb398173b.png)

### Description of issue:
Server lagging and Queue Crashing. I run the server connect.2b2t.org.

### Plugin list:
CurtisBungeeQueue

### bukkit.yml, spigot.yml, paper.yml, server.properties
Yes
### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
1.12.2

**Comment by Proximyst** [comment]
Outdated. Read the legacy page.

**Comment by 2builders2tools** [comment]
Hello. We are not updating as its unstable.

**Comment by 2builders2tools** [comment]
You banned us from our Discord for "trolling" even though we weren't this is a server issue not the server software

**Comment by Proximyst** [comment]
Hello. Figure it out yourself, then. Unsupported means no support.

**Comment by electronicboy** [comment]
1.12.2 is no longer supported in any capacity, nor have you provided any information if we did want to help
