### ISSUE TITLE
Lost packets issue

### ISSUE THREAD

**Issue by AlfieC** [PaperMC/Paper#484]
Hey,

This has likely been fixed (but reporting anyway in case it hasn't). On 1.7, the maxPacketsPerPlayer implementation is broken. Currently it does this:
`for (int i = org.github.paperspigot.PaperSpigotConfig.maxPacketsPerPlayer; (packet = (Packet) this.k.poll()) != null && i >= 0; --i) {`.

The `i >= 0` AFTER the `poll()` means that if the packet per player limit has been reached, these packets are ignored. 
Simple fix for this issue is to simply move the `i >= 0` to before the poll. However, this means that a player COULD cause the queue to build infinitely by just spamming packets, wasting memory. A better approach might be to ratelimit these on receiving the packet - meaning memory usage would be lower & the packet would be retained for a much shorter time.

**Comment by zachbr** [comment]
This entire thing was changed in later versions. This issue does not pertain to modern versions of Paper.
