### ISSUE TITLE
Support 1.12.2

### ISSUE THREAD

**Issue by 2builders2tools** [PaperMC/Paper#4840]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I get no support for 1.12.2 our server has over 1000 players and it is constantly lagging and we switched back to PaperSpigot as our fork was not working. We need support as 1.12.2 and up is not stable. Please help us out and we will be nice to you.

**Describe the solution you'd like**
Please add support for 1.12.2 for big servers our server is currently struggling to run even with the best hardware.

**Describe alternatives you've considered**
We have tried updating our hardware and we still have issues. We need help. I run the server 2b2t a survival server with no rules and 9TB Map that has been running for 9 years and almost 10 years this month.

**Comment by Proximyst** [comment]
No.
