### ISSUE TITLE
PrepareResultEvent called multiple times

### ISSUE THREAD

**Issue by Grabsky** [PaperMC/Paper#4844]
While playing with PrepareSmithingEvent, I noticed that it's called six times instead of one when I put item into Smithing Table GUI (and even more when I remove it). I couldn't really achieve anything with the event either (i.e. replacing result with PrepareSmithingEvent#setResult(ItemStack item)) which could be potentially caused by the event being broken at some point. As the issue could be on Spigot side, I tested Paper's PrepareResultEvent using same steps and it looks like the issue is the same.

### What behaviour is expected:
If I'm not missing the idea of PrepareResultEvent event, it should be called once each time GUI is modified.

### What behaviour is observed:
It's being called n times.

### Steps/models to reproduce:
1. Use this code to get console message every time the event is called:
```java
@EventHandler
    public void onPrepare(PrepareResultEvent event) {
        this.getLogger().info("Event called...");
    }
```
(You can also use attached file [SmithingTableTest.zip](https://github.com/PaperMC/Paper/files/5638544/SmithingTableTest.zip))
2. Put an item into Smithing Table.
3. Check console and see how many times "Event called..." message was printed.

### Plugin list:
[20:41:52 INFO]: Plugins (1): SmithingTableTest

### Paper version:
```
[20:28:59 INFO]: This server is running Paper version git-Paper-312 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[20:28:59 INFO]: Checking version, please wait...
[20:29:00 INFO]: You are running the latest version
```

**Comment by Grabsky** [comment]
Just noticed that putting items into Grindstone also calls the event more than it should. (called once only when trying to put incorrect item)

**Comment by BillyGalbreath** [comment]
This is expected behavior. The way mojang made these containers _really does_ update the inventory that many times. We can't change that behavior without breaking compatibility with what the client expects.

**Comment by Grabsky** [comment]
Thanks for clarifying @BillyGalbreath.

I'm playing with Prepare events for a couple of days already and they're not really co-operating with things such as eg. setting the result. I have to do it 1 tick after the event is run. I'm also wondering why PrepareAnvilEvent gets called when I change text cursor position (in rename field). Does it really change anything server-side?

Is it possible/worth effort to create patch adding 'PrePrepare' events which actually can be cancelled? Would make much more sense when modifying result items/repair costs (for anvil) etc. I've already put some time into exploring parts of code responsible  for Anvil behaviour, but I don't really understand how all of that works.

**Comment by Grabsky** [comment]
Discussed on Paper's discord yesterday. Looks like it's a known issue not only for Smithing Table but some others. I can confirm it's happening with Grindstone and Anvil as well. I didn't bring topic of 'PrePrepare' events, however I feel like modifying results before event is actually ran could be cause of client desynchronization. From my experience it appears that client is always trying to prepare results and put them in GUI on their own. I didn't find solution for that yet.

Back to the original issue - there apparently is a way to fix this, but this would probably require rewrite of containers behaviour.

**Comment by AyhamAl-Ali** [comment]
I still have this issue on paper 1.18.1 and 1.16.5 (even on spigot 1.16.5)
![image](https://user-images.githubusercontent.com/20037329/154990549-be74744c-e8eb-46d9-a59e-e128d31b9b5a.png)

Calls 4 times when i hold an item in cursor slot and place it in the anvil slot
But when i click with an empty cursor slot on any anvil slot it gets called 1 time only

**Comment by electronicboy** [comment]
As has already been stated, this is expected behavior; Outside of rewriting the entirety of how anvils work this is basically unavoidable
