### ISSUE TITLE
prevent-moving-into-unloaded-chunks not working

### ISSUE THREAD

**Issue by Cyberyisus2g** [PaperMC/Paper#4847]
Players have been crashing my server by using elytras and flying non stop into the horizon, i tested this error in a test server with no plugins and still happens

### What behaviour is expected:
___teleport players to loaded chunks when they move into a unloaded chunk___

### What behaviour is observed:
___players are not teleported after moving into a unloaded chunks___

### Steps/models to reproduce:
___Run a test server, download any fly hack and fly fast until you move into a unloaded chunk___

### Plugin list:
___none___

### Paper version:
___Paper version git-Paper-312 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT) but tried more___

**Comment by e-im** [comment]
Cannot reproduce / no longer relevant. If you are still able to reproduce this on 1.18.2, please leave a comment.
