### ISSUE TITLE
Some mobs with no goals still do things.

### ISSUE THREAD

**Issue by mikuhl-dev** [PaperMC/Paper#4848]
### What behaviour is expected:
Mobs with no goals do nothing.

### What behaviour is observed:
Some mobs with no goals still do things. Zoglin attacks mobs, Piglin walks around and transforms.

### Steps/models to reproduce:
Make a Zoglin or Piglin (maybe others?) and remove their mob goals.

### Plugin list:
None, other than the plugin to spawn to test.

### Paper version:
This server is running Paper version git-Paper-312 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by Machine-Maker** [comment]
Yeah, this is because the newer mobs do not use the goal system. They are using a new "Brain" system.

**Comment by MiniDigger** [comment]
and some mobs that don't have a brain still do stuff without goals too, in the tick method itself.
sadly there is nothing we can do about this.

hopefully somebody will have time to come up with a nice api for the new brain stuff in vanilla eventually.
