### ISSUE TITLE
broken end chunk generation

### ISSUE THREAD

**Issue by seema84** [PaperMC/Paper#4849]
### What behaviour is expected:
That the end is created without errors.

### What behaviour is observed:
Incorrect chunk generation.

### Steps/models to reproduce:
Create a  new end with multiverse.

### Paper version:
This server is running Paper version git-Paper-300 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Anything else:
example pictures:
https://i.imgur.com/SgiT6bv.png
https://i.imgur.com/GGv9mCL.png

**Comment by HexedHero** [comment]
Oh no.

Seed and cords to the broken part?

**Comment by Puremin0rez** [comment]
Please provide answers for the following to help with investigating this:
* How many end worlds do you have?
* What is the seed of the end world(s)?
* What are the coordinates of the incorrect generation?
* Is this world freshly made or an existing one?
* Is this occurring globally or just this one specific area?
* Are you able to get this to consistently occur as per your reproduction steps?

I'm unable to reproduce with the steps you have given.

Providing a list of plugins may help too. (e.g. custom world generators, etc)

**Comment by seema84** [comment]
I can't reproduce it myself right now. I think what I saw was still from the Version 1.16.3. Was there this problem? I think the issue can be closed for now.  Sorry for the trouble.

**Comment by Proximyst** [comment]
You can press the close issue button yourself, for future reference :)

**Comment by seema84** [comment]
i was not sure if you wanted to pursue this problem any further :)
