### ISSUE TITLE
1.11 performance question.

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#485]
Does 1.11 have any performance issues? I'm thinking of updating my server soon but I don't want it to be a nightmare when 1.9 first came out. Has there been any performance differences with 1.11?

**Comment by zachbr** [comment]
It's a relatively small update on top of 1.10. If you got 1.10.2 to a place where you like it, you should be okay. If you didn't, there's not a ton that's going to be better at this point.

Make a backup, test it locally, setup a cloned test server away from your main that people can play on, and just find out.
