### ISSUE TITLE
Server fails to add proper delay when scheduling a function in the Nether or End, running it immediately instead

### ISSUE THREAD

**Issue by GoldenDelicios** [PaperMC/Paper#4851]
### What behaviour is expected:
`/schedule` should always postpone execution of a datapack function by the number of ticks provided to the command.

### What behaviour is observed:
In the Nether and the End, scheduling a function will run immediately instead of scheduling it for a future tick. If a function re-schedules itself (commonly used to create periodic checks every nth tick), this can cause the server to get stuck in an infinite loop until watchdog kills it or it runs out of memory.

### Steps/models to reproduce:
1. Create or download a datapack with at least one function. One will be provided for testing.
2. Run `/schedule function <function> 100` in the Nether or End, or run `/execute in minecraft:the_end run schedule function <function> 100`.
3. If successfully reproduced, the function will run immediately instead of after 100 ticks. If the function also schedules itself in the Nether/End, the server will freeze and eventually crash.

However, I am only able to reliably reproduce this issue on our survival wold and our test world. I am not able to reproduce the issue on a brand new world. I have not been able to narrow down why that is so, so I'll include some extra information about these worlds.

- The test world was created during some 1.14 snapshot or pre-release, and has switched between running on Paper and vanilla snapshots/pre-releases.
- The survival world was created in Minecraft 1.14.3. This world has always run on Paper.
- My localhost world was created during 1.15.2, and has always run on Paper. I was unable to reproduce the issue on this world.
- I created a new world on the test world server. I was also unable to reproduce the issue in this world.

### Plugin list:
**Test server:** None
**Survival server:** Plugins (29): AFKSleep, Camera, CollarCheck, CoreProtect, DiscordSRV, dynmap*, EntityDetection, EntityGlo, F3Name, Fireworks, InventoryRollback, LightningFire*, LuckPerms, OpenInv, PetOwner*, PlaceholderAPI, Plan, PremiumVanish, ProtocolLib, RawStats, ShulkerSaver, spark, TAB-BukkitBridge, Vault, VentureChat, WorldBorder, WorldborderGateKeeper, WorldEdit, XGlow
**Localhost:** None

### Paper version:
**Test server:** This server is running Paper version git-Paper-312 (MC: 1.16.4)
**Survival server:** This server is running Paper version git-Paper-194 (MC: 1.16.3)
**Localhost:** This server is running Paper version git-Paper-220 (MC: 1.16.3)

### Anything else:
Attached you will find a test datapack to reproduce this issue; this is stripped down from the more complex datapack where I discovered this issue.
- Running `/function tunnel:stage1/buttonladder` will re-schedule itself every 10 ticks while a player is online. (It also writes "start buttonladder" to chat on each iteration.) If the issue is present, running this will get the server stuck in an infinite loop and crash.
- Running `/function tunnel:stage1/ladder` will schedule 17 functions, spaced 10 ticks apart, to create an animation of a ladder being built. The ladder will be built around 2857 42 2778 in the End. If the issue is present, the ladder will be built instantly.

[tunnel_light.zip](https://github.com/PaperMC/Paper/files/5646408/tunnel_light.zip)

**Comment by Machine-Maker** [comment]
Yeah, I confirmed this bug. Basically, you have to make sure you generate the end at a different time from the overworld. So I spun up a new server, loaded into the overworld, loaded up a test datapack, then stopped the server, deleted `world_the_end`, started server again, let it generate a new end, scheduled a function for 3s in the end, and it ran instantly. Working on a fix now, should really only be a one liner.

**Comment by GrifterMage** [comment]
I found this happening the other way around on the server I admin, which uses Multiverse. Functions scheduled while in a dimension that was significantly older than the main world would not run, because the server determined the tick to schedule them for on based on the age of the world the schedule command was run in, and that time was a long way off yet as far as the main world was concerned.

I assume the fix would cover that case, too, but don't know the code at all and figured I'd chime in just in case.

**Comment by Machine-Maker** [comment]
Yes, the fix changes the schedule command to use the scheduler of the world the command is run in, rather than the global one (which only looks at the "main" world age).

**Comment by nijamaDev** [comment]
I'm Having this bug on the latest version of paper _git-Paper-538_
