### ISSUE TITLE
GS4QueryEvent doesn't get called

### ISSUE THREAD

**Issue by hazae41** [PaperMC/Paper#4864]
Hello, it seems the GS4QueryEvent doesn't get called

### Steps/models to reproduce:
```kotlin
override fun onEnable() {
  super.onEnable()

  server.pluginManager.registerEvents(this, this)
}

@EventHandler
fun onquery(e: GS4QueryEvent) {
  println("queried")
}
```

    $ pip install mcstatus
    $ mcstatus localhost query

### What behaviour is expected:
See a debug message

### What behaviour is observed:
Nothing

### Plugin list:
Only my test plugin

### Paper version:
latest (1.16.4 b318)

**Comment by hazae41** [comment]
It seems the firing part has been removed (why?) https://github.com/PaperMC/Paper/commit/03a53a63b68a0d3f11f39ba58a1c0496a50a4940
https://github.com/PaperMC/Paper/blob/master/removed/1.16/0356-Fire-event-on-GS4-query.patch

The event is still there https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0172-Add-GS4-Query-event.patch

**Comment by electronicboy** [comment]
failed to merge, we must not have spotted it in the removed list with everything else going on

**Comment by hazae41** [comment]
Thanks!
