### ISSUE TITLE
Swapping Items to your off-hand and inventories

### ISSUE THREAD

**Issue by PancakeCatsss** [PaperMC/Paper#4869]
When creating a GUI menu in a plugin and canceling all the necessary events required to prevent a player from taking items from the menu I would have expected that to also block players being able to press F on an item within the menu and getting that item (a copy of that item) placed in their off-hand.

You can press F to put the current item over your cursor in your off-hand regardless of the events being canceled, In Survival mode, this item is a "ghost" item and will vanish once the players inventory updates, however, in Creative mode this item is real and can be used. 

How to reproduce: Install or make a plugin that has an inventory menu, open the menu and press F while your cursor is over one of the items within the menu. 

Plugin List:
- InventoryTestMenu (made to test this)

[17:15:37] [Server thread/INFO]: This server is running Paper version git-Paper-319 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[17:15:37] [Server thread/INFO]: Previous version: git-Paper-220 (MC: 1.16.3)
[17:15:37] [Server thread/INFO]: You are running the latest version

**Comment by Machine-Maker** [comment]
The whole creative mode thing... That sounds along the lines of the usual issues with creative mode issues. In creative mode, the client doesn't rely on validation with the server for items (hence the ghost item in survival but not in creative). So it's probably not fixable in creative mode
