### ISSUE TITLE
Duplication Glitch (Disconnecting + Throwing items)

### ISSUE THREAD

**Issue by abanator** [PaperMC/Paper#487]
I'm not sure if you guys already tried to patch this, but it's still working. Disconnecting and throwing items to the ground duplicates them. I already tried with Spigot and PaperSpigot and both of them doesn't seem to fix the glitch. I'm using the latest version.

**Comment by RoyCurtis** [comment]
Could not reproduce this on our beta with `git-Paper-924 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)` (latest build as of now).

What is your method for testing? [I tried keeping an item under my cursor](http://i.imgur.com/3ydkiER.png) and then kicking myself off the server via console.

Are you sure you are on the latest? (what does `/version` say?) [This CraftBukkit commit appears to resolve the issue](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/95436219a588cec7497112c879487ce5d5cec73a) (which [PaperSpigot 924 contains](https://ci.destroystokyo.com/job/PaperSpigot/924/))

**Comment by hurrgurl** [comment]
This dupe https://youtu.be/cviD9SXJPm0?t=3m31s

**Comment by ghost** [comment]
Duplicate of GH-481

**Comment by abanator** [comment]
Yes, I'm 100% sure that I'm on the latest version and it's still working. The link that hurrgurl posted shows the method for the glitch.

**Comment by zachbr** [comment]
The video shown is executing the older, now patched method. The method @abanator refers to involves a race condition with player saving in the vanilla server.

Unless anything has changed, Spigot denied his requests to look into it because he couldn't provide consistent reproduction instructions and was unable to consistently reproduce the issue.

**Comment by abanator** [comment]
https://www.youtube.com/watch?v=15CInNKrMgo&feature=youtu.be

This server is running Paper for example.

**Comment by zachbr** [comment]
Still can't reproduce that.

**Comment by zachbr** [comment]
Should be fixed in the latest build
