### ISSUE TITLE
Dupebug

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#4870]
### What behaviour is expected:
No errors, no dupe bugs

### What behaviour is observed:
Player can disconnect themselves whenever, without saving their data.

### Steps/models to reproduce:
Send some weird packets.

### Plugin list:
ProtocolLib, custom

### Paper version:
204

### Anything else:
https://pastebin.com/raw/8G1Vzy28

**Comment by JRoy** [comment]
> Send some weird packets.
heh

**Comment by electronicboy** [comment]
Please don't report duplication issues on a public tracker, use the discord
