### ISSUE TITLE
Mobs (Zombies etc.) Ignore Teams 

### ISSUE THREAD

**Issue by Colink02** [PaperMC/Paper#4875]
### What behaviour is expected:
___What you expected to see___
Setting a Zombie (or other mob) as the same team as the player should not attack that player. It should also not attack the player when friendlyFire is set to off in the team options

### What behaviour is observed:
___What you actually saw___
When summoning a zombie and adding it to a team the zombie would attack a player in the same team despite friendlyFire being off.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Tested versions: 319, 320
1. create a Team (ie. `/team add Runner`)
2. modify team to turn off friendlyFire (ie. `/team modify Runner friendlyFire false`)
3. summon zombie or other hostile mob (ie. `/summon zombie ~ ~ ~ {Invulnerable:1b,CustomNameVisible:1b,IsBaby:1b,Tags:["iceZombie"],CustomName:'{"text":"Ice Spirit"}'}`)
4. Add zombie or other hostile mob to the previously created team (ie. `/team join Runner @e[tag=iceZombie]`)
5. Go into survival mode and you'll be attacked by the hostile mobs even though your on the same team with friendly fire off

### Plugin list:
___A list of your plugins___
None
### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
![image](https://user-images.githubusercontent.com/11688661/101604166-2f038600-39c6-11eb-8fd3-d4e157852ba4.png)

### Anything else:
___Anything else you think may help us resolve the problem___
I check with the latest version of spigot (`CraftBukkit version git-Spigot-a19903d-5b74714 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)`) and it does not have this issue so it must be something to do with something inside paper itself

**Comment by aikar** [comment]
You will need to enable `allow-non-player-entities-on-scoreboards` in paper.yml, but note this comes at a performance cost.
