### ISSUE TITLE
MapView.getCenter is not retained when the server restarts

### ISSUE THREAD

**Issue by TauCu** [PaperMC/Paper#4876]
### What behaviour is expected:
MapView#getCenterX() to be the maps last center point.
MapView#getCenterZ() to be the maps last center point.

### What behaviour is observed:
MapView#getCenterX() was 0
MapView#getCenterZ() was 0

### Steps/models to reproduce:
1. Create a map with a custom renderer
2. Set the maps X and or Z to a number that isn't 0
3. Restart the server
4. Listen on MapInitializeEvent, get the map and check the X and Z

### Plugin list:
just my tpsgraph plugin (what I'm using maps for)

### Paper version:
[19:59:51 INFO]: Checking version, please wait...
[19:59:51 INFO]: Previous version: git-Paper-294 (MC: 1.16.4)
[19:59:51 INFO]: You are 1 version(s) behind

### Anything else:
This is a suggestion: It'd make it much easier if you could access the item that caused the MapInitializeEvent so that i wouldn't need to pack my own ID and data in the X and Z of the map ... or a PersistantDataContainer for Maps.

**Comment by Owen1212055** [comment]
Can't reproduce as of 1.19.1
