### ISSUE TITLE
Floating Armor Stand

### ISSUE THREAD

**Issue by NetStalker67** [PaperMC/Paper#4877]
### What behaviour is expected:
When using slime blocks and sticky piston to raise an armor stand into a pufferfishes range of detection, the armor stand should fall back to the piston when it retracts if it is not in viewable render range for entities. 

### What behaviour is observed:
When using slime blocks and sticky piston to raise an armor stand into a pufferfishes range of detection, the armor stand will float and not fall back to the piston when it retracts if it is not in viewable render range for entities. 

### Steps/models to reproduce:
set up sticky piston with armor stand on top, set redstone line to outside of render distance of armor stand, (when it no longer shows) trigger piston and walk back to within render range, piston is retracted and armor stand will show suspended and fall back to piston. 

This system is used in a recreation of Tango's decked out to reset the puffer fish which will stay "puffed" after nightly server reset. (this may also be a bug, not sure yet as its random as to which puffers stay puffed after reset)

### Plugin list:
CoreProtiect, HeadDatabase*, LuckPerms, RandomTp, Redye, SpawnTeleport, WoldEdit, WorldGuard

### Paper version:
git-Paper-298 (MC: 1.16.4) Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Anything else:
this behaviour has been observed in 1.16.2, 1.16.3, and 1.16.4 Unknown if it was in earlier versions. 

Replaced the armor stands with Cows in minecarts to solve the gravity problem.  during nightly reset. They react normally outside of entity render range

**Comment by aurorasmiles** [comment]
Did you perhaps disable `armor-stands-do-collision-entity-lookups` or `armor-stands-tick`?

**Comment by aurorasmiles** [comment]
I was not able to reproduce this issue with the setup you described

**Comment by jackmulholland** [comment]
@aurorasmiles I'm having similar issues, trying to remove a block under an armor stand so it falls down onto a slime block launcher piston but stepping back like 10 or 20 blocks freezes the armor stands and they don't fall down into the slime blocks when the block beneath them retracts.

Also a slime block CAN launch an armor stand upwards even when you're far away, but after, if the armor stand is standing on a slime block that retracts downward it does not fall back down to the slimeblock. Getting closer will then see the armor stand fall back down.

**Comment by jackmulholland** [comment]
@aurorasmiles I've opened an issue that I believe explains this further with more clear documentation: https://github.com/PaperMC/Paper/issues/4963

**Comment by e-im** [comment]
Thank you for opening a more detailed issue report, the behaviour you see here also falls in line with entity-activation-range. For armour stands further away than the default 16 blocks to work as expected, you will need to raise `entity-activation-range.misc` in spigot.yml
