### ISSUE TITLE
Random crash "Not supported"

### ISSUE THREAD

**Issue by bnt4** [PaperMC/Paper#4878]
### Link/paste of stack trace

`---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 09.12.20, 20:42
Description: Exception in server tick loop

java.lang.UnsupportedOperationException: Not supported.
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.MinecraftInternalPlugin.getServer(MinecraftInternalPlugin.java:85)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294)
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
	at java.base/java.lang.Thread.run(Thread.java:834)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 4.19.0-11-amd64
	Java Version: 11.0.9.1, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Debian
	Memory: 697148632 bytes (664 MB) / 2210398208 bytes (2108 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 5
	JVM Flags: 6 total; -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:MaxPermSize=256M -XX:-UseAdaptiveSizePolicy -XX:CompileThreshold=100 -Xmx8192M
	CraftBukkit Information: 
   Running: Paper version git-Paper-318 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT) false
   Plugins: { CFAPI-5 v5.0.0 de.craftfull.api.v5.spigot.SpigotCore [TaskID], FastAsyncWorldEdit v1.16-449;cc5b3ec com.sk89q.worldedit.bukkit.WorldEditPlugin [Empire92, MattBDev, IronApollo, dordsor21, NotMyFault], CF-ClanSystem v1.0.0 de.craftfull.clansystem.ClanSystem [TaskID], CloudNetAPI v2.1* de.dytanic.cloudnet.bridge.BukkitBootstrap [Dytanic], PlotSquared v4.4.495 com.github.intellectualsites.plotsquared.bukkit.BukkitMain [Citymonstret, Empire92, MattBDev, dordsor21, NotMyFault], CF-CoinSystem v1.0.0 de.craftfull.coins.CoinSystem [TaskID], CF-ChatSystem v1.0.0 de.craftfull.chat.ChatSystem [TaskID], Multiverse-Core v4.2.2-b812 com.onarandombox.MultiverseCore.MultiverseCore [dumptruckman, Rigby, fernferret, lithium3141, main--], CF-CityBuild v1.0.0 de.craftfull.citybuild.CityBuild [TaskID],}
   Warnings: DEFAULT
   Reload Count: 1
   Threads: { WAITING ForkJoinPool.commonPool-worker-7: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628), java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)], WAITING farmworld-01 - Light: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], TIMED_WAITING Timer-1: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:553), java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)], WAITING Paper Async Chunk Task Thread #0: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Paper Async Chunk Task Thread #3: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@11.0.9.1/java.lang.Thread.sleep(Native Method), com.github.intellectualsites.plotsquared.plot.database.SQLManager.lambda$new$0(SQLManager.java:180), com.github.intellectualsites.plotsquared.plot.database.SQLManager$$Lambda$5933/0x00000008413a0440.run(Unknown Source), app//org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99), app//org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54), app//com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], RUNNABLE Netty Epoll Server IO #2: [app//io.netty.channel.epoll.Native.epollWait0(Native Method), app//io.netty.channel.epoll.Native.epollWait(Native.java:114), app//io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], TIMED_WAITING Timer-0: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:553), java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)], TIMED_WAITING TaskScheduler-Group-4739233884467465500#194: [java.base@11.0.9.1/java.lang.Thread.sleep(Native Method), de.dytanic.cloudnet.lib.scheduler.TaskScheduler$Worker.sleepUninterruptedly(TaskScheduler.java:540), de.dytanic.cloudnet.lib.scheduler.TaskScheduler$Worker.run(TaskScheduler.java:491)], TIMED_WAITING Cleaner-0: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@11.0.9.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834), java.base@11.0.9.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)], RUNNABLE Signal Dispatcher: [], WAITING Craft Async Scheduler Management Thread: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], TIMED_WAITING WorldEdit Session Manager: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:553), java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)], WAITING Snooper Timer: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.lang.Object.wait(Object.java:328), java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:527), java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)], WAITING Paper Async Chunk Urgent Task Thread: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING mysql-cj-abandoned-connection-cleanup: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), app//com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:80), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], TIMED_WAITING Timer hack thread: [java.base@11.0.9.1/java.lang.Thread.sleep(Native Method), app//net.minecraft.server.v1_16_R3.SystemUtils$5.run(SystemUtils.java:465)], WAITING Paper RegionFile IO Thread: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], RUNNABLE Netty Epoll Server IO #3: [app//io.netty.channel.epoll.Native.epollWait0(Native Method), app//io.netty.channel.epoll.Native.epollWait(Native.java:114), app//io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING Finalizer: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@11.0.9.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)], TIMED_WAITING Common-Cleaner: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@11.0.9.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834), java.base@11.0.9.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)], RUNNABLE DestroyJavaVM: [], WAITING Paper Async Chunk Task Thread #1: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING Craft Scheduler Thread - 97: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234), java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462), java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361), java.base@11.0.9.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING world - Light: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING Paper Async Chunk Task Thread #2: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING TaskScheduler-Group-4739233884467465500#193: [java.base@11.0.9.1/java.lang.Thread.sleep(Native Method), de.dytanic.cloudnet.lib.scheduler.TaskScheduler$Worker.sleepUninterruptedly(TaskScheduler.java:540), de.dytanic.cloudnet.lib.scheduler.TaskScheduler$Worker.run(TaskScheduler.java:491)], WAITING Worker-Main-2: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], TIMED_WAITING ObjectCleanerThread: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), app//io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54), app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING Worker-Main-3: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING Paper Object Cleaner: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], TIMED_WAITING TaskScheduler-Group-4739233884467465500#197: [java.base@11.0.9.1/java.lang.Thread.sleep(Native Method), de.dytanic.cloudnet.lib.scheduler.TaskScheduler$Worker.sleepUninterruptedly(TaskScheduler.java:540), de.dytanic.cloudnet.lib.scheduler.TaskScheduler$Worker.run(TaskScheduler.java:491)], TIMED_WAITING Paper Watchdog Thread: [java.base@11.0.9.1/java.lang.Thread.sleep(Native Method), app//org.spigotmc.WatchdogThread.run(WatchdogThread.java:166)], RUNNABLE Reference Handler: [java.base@11.0.9.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@11.0.9.1/java.lang.ref.Reference.processPendingReferences(Reference.java:241), java.base@11.0.9.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)], RUNNABLE Server console handler: [java.base@11.0.9.1/java.io.FileInputStream.readBytes(Native Method), java.base@11.0.9.1/java.io.FileInputStream.read(FileInputStream.java:279), java.base@11.0.9.1/java.io.BufferedInputStream.read1(BufferedInputStream.java:290), java.base@11.0.9.1/java.io.BufferedInputStream.read(BufferedInputStream.java:351), java.base@11.0.9.1/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284), java.base@11.0.9.1/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326), java.base@11.0.9.1/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178), java.base@11.0.9.1/java.io.InputStreamReader.read(InputStreamReader.java:185), java.base@11.0.9.1/java.io.BufferedReader.fill(BufferedReader.java:161), java.base@11.0.9.1/java.io.BufferedReader.readLine(BufferedReader.java:326), java.base@11.0.9.1/java.io.BufferedReader.readLine(BufferedReader.java:392), app//net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:180), app//net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143), app//net.minecraft.server.v1_16_R3.DedicatedServer$1.run(DedicatedServer.java:67)], TIMED_WAITING Log4j2-TF-1-AsyncLogger[AsyncContext@55054057]-1: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123), app//com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:38), app//com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56), app//com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:159), app//com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING plotworld - Light: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING nether-01 - Light: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], RUNNABLE Netty Epoll Server IO #0: [app//io.netty.channel.epoll.Native.epollWait0(Native Method), app//io.netty.channel.epoll.Native.epollWait(Native.java:114), app//io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], TIMED_WAITING Craft Scheduler Thread - 98: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234), java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462), java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361), java.base@11.0.9.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], RUNNABLE Netty Epoll Server IO #1: [app//io.netty.channel.epoll.Native.epollWait0(Native Method), app//io.netty.channel.epoll.Native.epollWait(Native.java:114), app//io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], RUNNABLE epollEventLoopGroup-3-1: [app//io.netty.channel.epoll.Native.epollWait0(Native Method), app//io.netty.channel.epoll.Native.epollWait(Native.java:114), app//io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], WAITING Worker-Main-1: [java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], RUNNABLE Server thread: [java.base@11.0.9.1/java.lang.Thread.dumpThreads(Native Method), java.base@11.0.9.1/java.lang.Thread.getAllStackTraces(Thread.java:1658), app//org.bukkit.craftbukkit.v1_16_R3.CraftCrashReport.call(CraftCrashReport.java:33), app//net.minecraft.server.v1_16_R3.CrashReportSystemDetails.a(SourceFile:79), app//net.minecraft.server.v1_16_R3.CrashReport.i(CrashReport.java:71), app//net.minecraft.server.v1_16_R3.CrashReport.<init>(CrashReport.java:35), app//net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1029), app//net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178), app//net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3129/0x0000000840844c40.run(Unknown Source), java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)], TIMED_WAITING TaskScheduler-Group-4739233884467465500#198: [java.base@11.0.9.1/java.lang.Thread.sleep(Native Method), de.dytanic.cloudnet.lib.scheduler.TaskScheduler$Worker.sleepUninterruptedly(TaskScheduler.java:540), de.dytanic.cloudnet.lib.scheduler.TaskScheduler$Worker.run(TaskScheduler.java:491)], TIMED_WAITING Timer-2: [java.base@11.0.9.1/java.lang.Object.wait(Native Method), java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:553), java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)], TIMED_WAITING TaskScheduler-Group-4739233884467465500#196: [java.base@11.0.9.1/java.lang.Thread.sleep(Native Method), de.dytanic.cloudnet.lib.scheduler.TaskScheduler$Worker.sleepUninterruptedly(TaskScheduler.java:540), de.dytanic.cloudnet.lib.scheduler.TaskScheduler$Worker.run(TaskScheduler.java:491)],}
   
   Force Loaded Chunks: { world: {}, plotworld: {}, nether-01: {}, farmworld-01: {},}
	Player Count: 2 / 100; [EntityPlayer['tiroltvplay'/53, uuid='036e2058-5c38-4641-a45d-0b191c1b3b03', l='ServerLevel[plotworld]', x=3.85, y=64.50, z=28.72, cx=0, cz=1, tl=446141, v=true, d=false](tiroltvplay at 3.8523598985387357,64.5,28.718812558254477), EntityPlayer['TaskID'/54, uuid='f6876dc7-bbdc-4725-8b1d-0c1ab1b0cbde', l='ServerLevel[plotworld]', x=420.41, y=63.36, z=-39.39, cx=26, cz=-3, tl=3780795, v=true, d=false](TaskID at 420.40677786801325,63.356248110660964,-39.39326362445039)]
	Data Packs: vanilla, file/bukkit
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)`

### Plugin list:
CF-ChatSystem, CF-CityBuild, CF-ClanSystem, CF-CoinSystem, CFAPI-5, CloudNetAPI, FastAsyncWorldEdit, Multiverse, PlotSquared

(everything starting with CF- & the CFAPI-5 is self-made, the server crashed without these plugins too.

### Actions to reproduce (if known):
Nothing, idk why this issue is happening

### Paper version:
This server is running Paper version git-Paper-318 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by MiniDigger** [comment]
unrelated to the crash, you still have an issue with smth, try updating p2 or smth
