### ISSUE TITLE
ProjectileHitEvent for Fireball is called twice

### ISSUE THREAD

**Issue by jcoppock** [PaperMC/Paper#4880]
### What behaviour is expected:
When launching a Fireball using Player#launchProjectile(Fireball.class) and listening for hit events using ProjectileHitEvent, I expected to see the event fire only once for the one fireball.

### What behaviour is observed:
The ProjectileHitEvent is fired twice for a single Fireball hitting the ground.

### Steps/models to reproduce:
Launch a Fireball using Player#launchProjectile(Fireball.class) and listen for the event.

### Plugin list:
(my plugin, of course), Citizens, DiscordBotAPI, Essentials, EssentialsChat, LuckPerms, TAB, Vault, WorldEdit, WorldGuard

### Paper version:
git-Paper-322 (MC: 1.16.4) Implementing API version 1.16.4-R0.1-SNAPSHOT

### Anything else:
"SPAWNED FIREBALL" - printed when calling launchProjectile()
"projectile hit" - printed at the top of ProjectileHitEvent
"FIREBALL HIT" - printed when checking projectile instanceof Fireball and some other simple checks about the Fireball
"Fireball" - printing a list of nearby entities when the Fireball hits

I launched the Fireball using Fireball.class, not LargeFireball.class, so I do not understand why EntityLargeFireball shows up in this Stacktrace at all... Could this be the issue?

![image](https://user-images.githubusercontent.com/12204614/101696480-c8b94a80-3a3b-11eb-8350-b98ca44e4360.png)

**Comment by Owen1212055** [comment]
Can confirm this on Paper-346 (MC: 1.16.4).

**Comment by HexedHero** [comment]
I think reporting this to upstream would be the best bet of getting this fixed. Unless it's a paper only issue.

**Comment by electronicboy** [comment]
this is a CB one, not sure if there is a PR, been kinda ill-er, but, this is a CB issue last I recall, the call site for this event is in multiple locations

**Comment by aikar** [comment]
I put a comment on that recently, was considering removing it but wasnt sure if there was some special behavior I was not aware of, but I really can't see any reason for it to be there.

I believe this is just an artifact of code being there before projectile collision was abstractified, then the event was added to the abstract location, then this one didnt get removed.

https://github.com/PaperMC/Paper/commit/f6d3c6811e3a282685b54190d39d8e257624a215#diff-ac85ef067ff73ee95e83756ab3507490d2a370770d37db60e1881a2efcdb2018R17

**Comment by Owen1212055** [comment]
This was fixed in: https://github.com/PaperMC/Paper/commit/d3c9a195cb5778e99ea120ed4fea12fbf57abb97
