### ISSUE TITLE
Server does not restart on crashes, process hanging

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#4881]
When I updated to 1.16.4 my server stopped restarting on crashes, my log mentions "hard crash" which may have something to do with it. 

Log: https://mcpaste.io/e2e8109f0a425cf1

I believe the issue has something to do with watchdog not shutting down correctly due to it deadlocking somewhere?
I created an issue on the pterodactyl github here: https://github.com/pterodactyl/panel/issues/2668 where the developer commented "We don't detect process hanging which is what is happening there. It says stopping but never stops, so to Wings the server container is still running. Crash detection only triggers if the container itself stops."

This is a really annoying issue because any time the server crashes I need to manually kill the server instance and then start it again.

### Paper version:
git-Paper-322 (MC: 1.16.4)

**Comment by electronicboy** [comment]
We need a jstack report

**Comment by Strahilchu** [comment]
I hope this is fixed because I had the same issue

**Comment by electronicboy** [comment]
Without a jstack report, we cannot debug this issue

**Comment by Chillchillnetwork** [comment]
https://mcpaste.io/afeba2e6f172fac9 I have same problem

**Comment by SecretlyJealous** [comment]
I believe these commits may fix the issue: https://github.com/Spottedleaf/Tuinity/commit/8c5d945e45a68951e0cc10833d1d8abd4b39ac09 and https://github.com/Spottedleaf/Tuinity/commit/0ae7e671fea9a985c79dd736df6e10e8938a03ea but it's not added in paper yet.

Edit: those commits do not fix the issue :(

**Comment by electronicboy** [comment]
Closing issue due to lack of information requested
