### ISSUE TITLE
1.16.4 Nether mobs not spawning

### ISSUE THREAD

**Issue by TheDollinger** [PaperMC/Paper#4883]
I have recently shifted to Paper for the per person mob spawning which is supposedly going to change the bukkit global mob cap to a per person mob cap. The problem is once more than 1 player enters the nether, not a single mob spawns. I turned per-person-mob-spawning: true as well as count-all-mobs-for-spawning: true. The server view distance is 11 and mob-spawn-range: 9

These are the spawn-limits:

water-ambient: 20

monsters: 30

animals: 10

water-animals: 10

ambient: 5

Plugins:
Skins restorer

The current Paper version running is the latest 1.16.4 version

**Comment by e-im** [comment]
Note that `per-player-mob-spawns` does not change the total number of mobs in the world (that is, in the way you describe), but instead ensures equal sharing of mobs between players. The number of mobs total are already (and per-player does not change this) calculated based on the number of loaded chunks in the world.

However, I haven't been able to reproduce this issue on 1.17.1 build 353. Additionally, the commands `/paper mobcap` and `/paper playermobcap` have been added that may assist you in debugging issues like this. Should this persist for you on 1.17.1, leave a comment.
