### ISSUE TITLE
Dark oak tree no longer grows after updating from 261 to 323 (MC 1.16.4)

### ISSUE THREAD

**Issue by Cretezy** [PaperMC/Paper#4884]
I have build a tree farm using a tutorial (see reproduction steps below, with screenshot). Yesterday, we were on Paper-261, and the sapling was about to grow (the farm was working). Today, we have updated to Paper-323 and the dark oak saplings no longer grow. This is the only change done between the 2.

### What behaviour is expected:
The dark oak tree can grow.

### What behaviour is observed:
The dark oak tree doesn't grow.

### Steps/models to reproduce:
Farm build using tutorial: https://www.youtube.com/watch?v=B8V3spqd1HE

![image](https://user-images.githubusercontent.com/2672503/101946352-dcd88580-3bbc-11eb-98d4-02df9977fc58.png)

### Plugin list:
`Plugins (13): ChanceTransformZombieVillager*, ChestSort, CoreProtect, DiscordSRV, dynmap*, Graves, GSit, LuckPerms, ProtocolLib, SlimeChunk*, SuperVanish, WitherAC, WorldBorder`

### Paper version:

This server is running Paper version git-Paper-323 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

Previous version: git-Paper-261 (MC: 1.16.4)

**Comment by HexedHero** [comment]
Go down paper versions until it works again and tell us what version breaks it. We can't look at the code for 50+ versions and guess

**Comment by Cretezy** [comment]
Okay do I reverted to 261 and it was still happening. Turns out, somehow there were some ghost blocks presents. I couldn't place blocks where the thunks "should" go, so I `/fill`ed them in, removed the filled blocks, and it grew.

I've never seen something like this, and it's not version-specific. Unfortunately I can't reproduce this so I can't file a bug.
