### ISSUE TITLE
Item drop Mythicmobs Mobs not combined item paper

### ISSUE THREAD

**Issue by Chillchillnetwork** [PaperMC/Paper#4886]
### What behaviour is observed:
Item drop Mythicmobs Mobs not combined item paper
Item drop Mythicmobs not combined item paper By the way, making it combined is restart server , Enter the server again , load chunk but the name of the item is the same.

Example Mythicmobs NBT items not combined item paper https://www.youtube.com/watch?v=OMhOFHD6wyw

### Paper version:
Paper 1.16.3

**Comment by Chew** [comment]
Please confirm this happens on latest 1.16.4 build, and provide a plugin list.

**Comment by ghost** [comment]
It is fixed on 1.16.4

**Comment by aurorasmiles** [comment]
I wasn't able to reproduce this with Paper 1.16.4 323 and MythicMobs 4.10.1
