### ISSUE TITLE
Shulker Box Console Warning:  "Unable to resolve BlockEntity for ItemInstance"

### ISSUE THREAD

**Issue by WonderDave** [PaperMC/Paper#489]
Version and plugin info:
  [11:03:46] [Server thread/INFO]: This server is running Paper version git-Paper-924 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
  [11:03:46] [Server thread/INFO]: You are running the latest version
  [11:03:49] [Server thread/INFO]: Plugins (0):

Here's what I did:
  1) Created a brand new server/world and logged in
  2) Gave myself OP rights via the console
  3) Changed to gamemode 1
  4) From the creative inventory, added a shulker box (any color) to my hotbar
  5) Placed the shulker box
  6) Broke and picked up the shulker box
  7) Moved the *picked-up* shulker box from one slot in my hotbar to any other slot

Once doing the above, every time I moved the picked-up shulker box from one slot to another, the warning was generated in the console.

These warnings have shown up in my console numerous other times over the past two days, but doing the above seems to be the quickest way to get them to appear.  Gameplay does not seem to be affected in any way.

I was unable to get these warnings to appear in Spigot.

Thanks.

**Comment by Black-Hole** [comment]
You missed to include the actual warning. 😕

**Comment by WonderDave** [comment]
Most of the warning was in the title, but here's one of them.  The specific shulker box listed at the end can be any of the colors:

[11:57:21] [Server thread/WARN]: Unable to resolve BlockEntity for ItemInstance: minecraft:magenta_shulker_box

**Comment by zachbr** [comment]
This is caused by [0167-Process-NMS-Data-Conversion-post-ItemMeta-on-Copy.patch](https://github.com/PaperMC/Paper/blob/eb877d8cdb90657ee7514750f547ee1cbfbc5d3e/Spigot-Server-Patches/0167-Process-NMS-Data-Conversion-post-ItemMeta-on-Copy.patch).
It looks like this area has changed a bit in 1.11. I will let @aikar take a look and see if there's a better resolution available or how much work it'll be to resolve it.

**Comment by SecretlyJealous** [comment]
I'm getting this error (not sure if this is related to the issue but I'll post it anyway)
Error: http://hastebin.com/eduvoyejic.vbs

**Comment by TNTUP** [comment]
Confirming this in Paper 937. Thought it was a plugin issue! Glad I've searched it before making an issue xD

**Comment by aikar** [comment]
I'l try to dig more into this tonight

**Comment by aikar** [comment]
This was a 100% harmless debug message. I removed it in the latest paper so it wont clutter up logs.
