### ISSUE TITLE
Remove outdated/invalid config options

### ISSUE THREAD

**Issue by DontNeedAName** [PaperMC/Paper#4894]
**Is your feature request related to a problem? Please describe.**
Whenever a config option gets removed, it remains in the paper.yml file after updating and if you don't notice its removal, you might try to change it in the future and wonder why the change has no effect. Looking at the docs also won't help much, because they are rarely updated and might still contain that option, which causes even more confusion.

**Describe the solution you'd like**
Invalid config options should be removed when the config is read.

**Describe alternatives you've considered**
Maybe add an option for that as well. (Something like removed-invalid-config-entries)

**Additional context**
Idk if you can also apply this to bukkit.yml and spigot.yml. (I'm not sure if this even affects those)

**Comment by electronicboy** [comment]
The amount of effort and testing for such a feature would far exceed its worth, not to mention, ideally settings that are removed will be added back if they're still relevant, so it doesn't generally make sense

All of the platforms generally recommend redoing your config files on updates, as that's generally the only time options are removed (often tempariliy as we try to re-merge some less critical patches down the line)
