### ISSUE TITLE
entity-tracking-range not working correctly

### ISSUE THREAD

**Issue by JaHollTV** [PaperMC/Paper#4895]
Using latest Version of Paper and some before i have the following bug with the entity-tracking-range.

I set the values to:
  entity-tracking-range:
     players: 110
      animals: 110
      monsters: 110
      misc: 110
      other: 110

### What behavior is expected:
Expected was, that i can see for example Players 160 Block wide.

### What behavior is observed:
I can see Players 40 Blocks wide.

### Steps/models to reproduce:
Sadly it works on my lobby server perfect but not on my main game Server...

### Plugin list:
Tried also without Plugins and Problem still exist

### Paper version:
This server is running Paper version git-Paper-323 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Anything else:
On my Lobby Server the options work an i can see Players 160 Blocks wide. So i don't know where the Problem come from.
I also regenerated today bukkit.yml, spigot.yml and paper.yml

**Comment by HexedHero** [comment]
Not sure if this would change anything but you using no tick view distance?

**Comment by JaHollTV** [comment]
No, its set to -1.

**Comment by Malfrador** [comment]
I happen to have the tracking range for players on 100 for PvP reasons and its working perfectly fine for me.
Do you, by any chance, changed the client setting for "Entity Render Distance" to like 50%? Its quite a new setting, so maybe you overlooked it. I don't know if it even affects players tbh.

**Comment by JaHollTV** [comment]
Problem Solved:
Server.properties: entity-broadcast-range-percentage was set to 25

Next time i should rebuild also the Serverproperties....
