### ISSUE TITLE
Exception ticking world 

### ISSUE THREAD

**Issue by resi23** [PaperMC/Paper#4899]
### Link/paste of stack trace

latest.log: https://pastebin.com/Dwzs1YWT
Crash-Log: https://pastebin.com/LV2jfEeA

### Plugin list:
AdvancedRegionMarket, AltDetector, antiRedstoneClock, BetterShulkerBoxes*, Bomberman, BungeeTabListPlus, BuycraftX, ChestShop, ChestShopNotifier*, ChestSort, Chunkmaster, ColoredAnvils*, CraftDisplay, CrateReloaded, eGlow, Essentials, EssentialsSpawn, FriendsRELOADED, FurnitureLib, HackedCore*, HackedServer*, HeadDatabase*, HolographicDisplays, Images, Jobs, LagAssist, LibsDisguises, LuckPerms, MarriageMaster, MaSuiteCore, MaSuiteTeleports, MCPerks, Multiverse-Core, PinataParty, PlaceholderAPI, PlotSquared, ProtocolLib, RFChairs, SCAdmin, SCAFK, SCAnimalChat, SCAntiBed, SCAntiClone, SCArmorStandCrashFix, SCCustomPlotsquaredFlags, SCCustomRecipes, SCEvent, SCHelper, SCLib, SCMain, SCPlotsquared, SCSchach, SCSpawner, SCUnloadInv, SCWebserver, Seedcraft, SeedCraftBooks, SeedcraftEssentials, SlotMachine, Spartan, SuperTrailsPro*, TAB, TreasureChest, Vault, VierGewinnt, Votifier, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

### Actions to reproduce (if known):
I dont know
### Paper version:
This server is running Paper version git-Paper-325 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Previous version: git-Paper-298 (MC: 1.16.4)
You are 6 version(s) behind

**Comment by MiniDigger** [comment]
thats uuh, interesting

I don't see a way that that code could ever run into that error
![https://i.imgur.com/CPMs6KV.png](https://i.imgur.com/CPMs6KV.png)

**Comment by PaulBGD** [comment]
Looks like it could happen if a plugin calls anything async that ends up calling ChunkProviderServer#flagDirty, since it could modify the set.

**Comment by resi23** [comment]
I now have a guess. I have a plugin in it with which you can fill your XP into bottles via the brewing stand. When I was about to do that, the server crashed with the same error message

**Comment by electronicboy** [comment]
Replicate without plugins, something is messing with internal data collections improperly causing state corruption
