### ISSUE TITLE
 WARN]: at io.netty.channel.AbstractChannel$AbstractUnsafe.close(...)(Unknown Source) spamming => crash

### ISSUE THREAD

**Issue by lightgreenwings** [PaperMC/Paper#4900]
### What happens:
[11:46:37 WARN]: at io.netty.channel.AbstractChannel$AbstractUnsafe.close(...)(Unknown Source) spamming the console and the server crashes

### Steps/models to reproduce:
no scheme can be recognized

### Plugin list:

AsyncWorldEdit-3.8.0.jar 
  | CoreProtect-19.3.jar
  | craftbook-3.10.2-SNAPSHOT-dist.jar
  | CrazyEnchantments.jar
  | EssentialsX-2.18.2.0.jar 
  | EssentialsXChat-2.18.2.0.jar
  | EssentialsXProtect-2.18.2.0.jar
  | EssentialsXSpawn-2.18.2.0.jar
  | ezBroadcast_1.3.1.jar
  | HarbourSleeping.jar
  | HeadDatabase.jar
  | Jobs4.16.3.jar
  | LockettePro-2.10.8.jar 
  | MOTD.jar 
  | PlaceholderAPI-2.10.9.jar
  | PowerRanks.jar 
  | QuickShop-4.0.4.8.jar 
  | TAB v2.8.9.jar | 588.29kB 
  | UltimateAutoRestart Build 40c.jar
  | Vault.jar | 265.88kB 
  | worldedit-bukkit-7.2.0-dist.jar 
  | worldguard-bukkit-7.0.4.jar

all plugins are compatible with 1.16.4

### Paper version:
latest

**Comment by aurorasmiles** [comment]
Latest is not a version and please include server and crash logs.

**Comment by lightgreenwings** [comment]
I'm sorry, had a closer look now. version: build 328
Here is a latest.log: https://pastebin.com/F1PCMBKR
Seems that the server has not crashed

**Comment by electronicboy** [comment]
Something that's hooked into the network stack is mishandling exceptions causing the connection to dangle in a bad manner, which is why it's consistently spamming the console as it's not allowing the connection to close properly, replicate without plugins™
