### ISSUE TITLE
The entity gets off the boat and goes through the floor

### ISSUE THREAD

**Issue by GuNanOvO** [PaperMC/Paper#4906]
### What behaviour is expected:
The entity will not cross the floor after disembarking.

### What behaviour is observed:
After getting off the ship, the entity will pass through the floor.I tested the original version for a long time and did not find this problem, but it does exist on the paper, although the probability is not high.

### Steps/models to reproduce:
1. Build a platform; 
2. Place a ship and let the entity ride on it; 
3. Destroy the ship and let the entity disembark; 
4. There is a certain chance that the entity will sink into the ground, if the ground is thin, it will pass through.
![2020-12-18_16 34 15](https://user-images.githubusercontent.com/63027311/102595383-791d0200-4152-11eb-806d-c66ce22b95e9.png)
![2020-12-18_16 35 33](https://user-images.githubusercontent.com/63027311/102595442-8cc86880-4152-11eb-92d0-1964ba2e64a0.png)
![2020-12-18_16 37 27](https://user-images.githubusercontent.com/63027311/102595474-9782fd80-4152-11eb-8ace-dbb854055e9b.png)
![2020-12-18_16 37 29](https://user-images.githubusercontent.com/63027311/102595480-99e55780-4152-11eb-94c0-47fee3b2fcb8.png)
![2020-12-18_16 38 11](https://user-images.githubusercontent.com/63027311/102595517-a5388300-4152-11eb-9f66-54c36f252502.png)
![2020-12-18_16 38 13](https://user-images.githubusercontent.com/63027311/102595521-a8337380-4152-11eb-852a-8f65ac294378.png)

### Plugin list:
NO

### Paper version:
[16:51:28 INFO]: This server is running Paper version git-Paper-332 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[16:51:28 INFO]: You are running the latest version
![20201218164032](https://user-images.githubusercontent.com/63027311/102595319-5d196080-4152-11eb-96a0-bd53093408f0.png)

### Anything else:
NO

**Comment by Chew** [comment]
By "no" in plugin list I assume you mean you don't have any plugins?"

**Comment by GuNanOvO** [comment]
> 通过插件列表中的“否”，我假设您是说您没有任何插件？”
Yes

**Comment by schnism** [comment]
Good news: In 1.17 as of commit https://github.com/PaperMC/Paper/commit/05623c47ec541cdc17bd9ba390608a1c9ea07bea the issue is not occuring. 

So either it was fixed, or it is in one of the few patches not yet applied.

**Comment by kickash32** [comment]
Most likely fixed in vanilla 1.17

**Comment by qixils** [comment]
Lots of boat bugs were fixed in 1.17, this is most likely related to [200195](https://bugs.mojang.com/browse/MC-200195) or [212331](https://bugs.mojang.com/browse/MC-212331).

> or it is in one of the few patches not yet applied.

Issue still does not occur on the latest Paper builds, which have most patches reapplied. Safe to consider this fixed imo
