### ISSUE TITLE
PaperServerListPingEvent#setPlayerSample(List<PlayerProfile>)

### ISSUE THREAD

**Issue by katekerllenevich** [PaperMC/Paper#4909]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set the Player Sample in PaperServerListPingEvent.

**Describe the solution you'd like**
I propose a `PaperServerListPingEvent#setPlayerSample(List<PlayerProfile>)` method to set the list of players when hovering over the player count.

**Describe alternatives you've considered**
The only other thing I could think of would be some hacky nms method that will have to be maintained and updated.

**Additional context**
N/A

**Comment by JRoy** [comment]
PaperServerListPingEvent#getPlayerSample exposes a mutable array which does this exact thing :/

**Comment by katekerllenevich** [comment]
ohhh... im stupid lol
