### ISSUE TITLE
InventoryCloseEvent Reason not OPEN_NEW when expected

### ISSUE THREAD

**Issue by stijnb1234** [PaperMC/Paper#4912]
### What behaviour is expected:
The InventoryCloseEvent.getReason() will be OPEN_NEW when opening a new inventory with openInventory() while closing the old one

### What behaviour is observed:
InventoryCloseEvent.getReason() is always PLAYER

### Steps/models to reproduce:
1. Open an inventory with p.openInventory()
2. Open another inventory with p.openInventory(), this closes the old one
3. InventoryCloseEvent.getReason() is PLAYER

### Plugin list:
ArmorStandTools, BlockLocker, Citizens, Essentials, EssentialsSpawn, FastAsyncWorldEdit, FrogRacing (my custom plugin), LuckPerms, Multiverse-Core, PlaceholderAPI, PlugMan, ProtocolLib, SuperVanish, WorldBorder, WorldEdit, WorldGuard

### Paper version:
git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) - You are running the latest version.

### Anything else:
-

**Comment by limbo-app** [comment]
Hey @stijnb1234! You seem to be running an unsupported version (1.12) of Paper.

If you can reproduce this issue with the latest supported version, please [open a new issue](https://github.com/PaperMC/Paper/issues/new) with updated information.

**Comment by stijnb1234** [comment]
Yes, I know this version is unsupported, but I think I'm just doing something wrong. Will ask this on the Discord then...

**Comment by Chew** [comment]
Unsupported means unsupported. We won't help you if you're not on 1.16.
