### ISSUE TITLE
Allow disabling vanilla movement checks

### ISSUE THREAD

**Issue by gerome1812** [PaperMC/Paper#4917]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated with the vanilla movement checks. They are inconsistant, especially for players with higher latency or when using boats on ice/piston bolts. It is constantly spamming my console with `x moved too quickly`. Whitelisted server so client modification is no issue.

**Describe the solution you'd like**
I would like to be able to disable the vanilla movement checks

**Describe alternatives you've considered**
I have concidered writing a plugin to do this, although have never used nms so at this time is a bit out of my reach at this time. I have also found [trusted-server](https://github.com/gnembon/trusted-server), a mod for fabric that accomplishes this same thing. I however do not use fabric, I use paper.

**Additional context**
N/A

**Comment by electronicboy** [comment]
no, people disable these warnings, kill their servers, and then cry for support which takes 10 years because they disabled the warning we're explicitly looking for and tells them exactly what happened. Increase the movement threshold in what I think was spigot.yml

**Comment by BillyGalbreath** [comment]
Why dont you just set them to absurdly high numbers to effectively disable them? The modifiers are available in spigot.yml

**Comment by gerome1812** [comment]
That's understandable. Thanks for the quick response and maintaining such an awesome piece of software!

I have already set it very high but it is still happening.

I'll file an issue with purpur and see if they will add this, or just break down and figure out how to use nms.

**Comment by aidanhasaknife** [comment]
Apologies for commenting on such an old issue, but I don't see why this functionality couldn't be implemented as a system property, just like disabling timeout watchdog ([Spigot-Server-Patches/0098-System-property-for-disabling-watchdoge.patch](url)). Any thoughts?
