### ISSUE TITLE
Option to disable chat globally on a server without the need of a plugin. 

### ISSUE THREAD

**Issue by itaquito** [PaperMC/Paper#4918]
**Is your feature request related to a problem? Please describe.**
Some servers are not meant to have players interacting with each other, for example, an auth, queue or even a lobby server. Also, this can be helpful for server owners that don't have (or don't want) to have a staff team to moderate chat. Even, this can help servers focused on under-age audience.

**Describe the solution you'd like**
An easy to configure parameter on paper.yml
`disable-chat: true/false`

**Describe alternatives you've considered**
You can disable the chat using a plugin, however, currently, there isn't an up to date plugin that just does this. It is not the best option to use a plugin with other several features to just disable the chat.

**Additional context**
I think this is a little change that can help a lot of server owners. Thanks.

**Comment by zachbr** [comment]
It is not Paper's goal to be able to accomplish everything without a plugin.

What gets implemented via plugins in API (such as this) vs what we do directly in the server boils down to what is available in the API (can it be done), the maintenance costs, and many more factors.

In this case, this is well within the reach of a simple plugin. That plugin should work fine across many versions and certainly take less time than us messing with it in the server core. You may find a charitable developer willing to do it for free given how little effort it would take.

**Comment by MiniDigger** [comment]
and if you can't write plugins and can't think somebody, this is where stuff like Skript or Grakkit shine. Canceling the chat even is super simple using those, and the overhead they add for complex staff is not relevant for such small things.
