### ISSUE TITLE
Player wont't stand up after swim pose being in fake team created by packet with collision rule set to NEVER or PUSH_OWN_TEAM

### ISSUE THREAD

**Issue by armagidon-exception** [PaperMC/Paper#4919]
### What behavior is expected:
Player should stand up

### What behaviour is observed:
Player doesn't stand up, he remains swimming.

https://user-images.githubusercontent.com/42355119/102717001-95ef3c00-42f0-11eb-87db-2b54c05215fd.mp4

### Steps/models to reproduce:
1. Build a capsule
2. Set a block above yourself to swim.
3. Run a command with code using code i attached below.

Here's snippets of code i used:
[scoreboard.zip](https://github.com/PaperMC/Paper/files/5721069/scoreboard.zip)
Create instance of NameTagHider and use method hideTag.

4. Break block above yourself, you should remain swimming, but cannot go under blocks

### Plugin list:
PosePlugin, PosePluginAPI, PosePluginAPITest

### Paper version:
git-Paper-366 (MC: 1.16.4)

### Anything else:
As i noticed the problem looks the same as you would spam EntityMetadataPackets with SWIMMING pose. I think it's because client for some reason thinks that pose is swimming, but server is not, so player can swim, but can't go under blocks.

**Comment by imDaniX** [comment]
I mean, should it really be fixed on Paper's side?

**Comment by MiniDigger** [comment]
@imDaniX what do you mean by this? Is this a vanilla issue?

**Comment by imDaniX** [comment]
> @imDaniX what do you mean by this? Is this a vanilla issue?

First things first - currently sending custom packets is not a thing that's covered with Spigot or Paper APIs, isn't it? There's actually some, like sending blocks data, but this is kinda just a tip of an iceberg.
Secondly, this one is quite deep into nms and reflections. I really think that something is missing here, so it differs from the vanilla team-player behavior.

Or I'm just stupid and this is actually something that Paper should fix, I dunno.

**Comment by MiniDigger** [comment]
can't repro with 
```
[16:07:51 INFO]: MiniDigger issued server command: /team add Test
[16:07:51 INFO]: [MiniDigger: Created team [Test]]
[16:07:55 INFO]: MiniDigger issued server command: /team join Test
[16:07:55 INFO]: [MiniDigger: Added MiniDigger to team [Test]]
[16:08:02 INFO]: MiniDigger issued server command: /team modify Test collisionRule never
[16:08:02 INFO]: [MiniDigger: Collision rule for team [Test] is now "Never"]
```
on both paper nor vanilla. so idk what you send (am not looking at that mess reflection code), but its something stupid thats messing with the client.
