### ISSUE TITLE
Paper-335: Librarian Villager Disappears when placeing lectern

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4923]
Hello, i got this error when some of my players was making a Villager Hall, i just had a upgrade to this version when this started.
What to do?

Kind regards
Ronnie0982 

Preview of the console with error
>.... [18:04:57 WARN]: Entity threw exception at world:-288.30000001192093,68.9375,1123.5093185724731
>.... [18:04:57 WARN]: java.lang.IllegalStateException: No offered ingredients
>.... [18:04:57 WARN]: at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
>.... [18:04:57 WARN]: at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMerchantRecipe.toMinecraft(CraftMerchantRecipe.java:104)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityVillagerAbstract.a(EntityVillagerAbstract.java:248)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityVillager.eW(EntityVillager.java:829)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityVillagerAbstract.getOffers(EntityVillagerAbstract.java:99)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.BehaviorTradePlayer.b(SourceFile:121)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.BehaviorTradePlayer.a(SourceFile:108)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.BehaviorTradePlayer.d(SourceFile:78)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.BehaviorTradePlayer.d(SourceFile:20)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.Behavior.f(SourceFile:63)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.BehaviorController.e(SourceFile:521)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.BehaviorController.a(SourceFile:466)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityVillager.mobTick(EntityVillager.java:169)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityVillager.mobTick(EntityVillager.java:166)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityInsentient.doTick(EntityInsentient.java:765)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityLiving.movementTick(EntityLiving.java:2752)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityInsentient.movementTick(EntityInsentient.java:545)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityAgeable.movementTick(EntityAgeable.java:143)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2477)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:308)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.EntityVillager.tick(EntityVillager.java:211)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.World.a(World.java:884)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1356)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
>.... [18:04:57 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
>.... [18:04:57 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by Chew** [comment]
You are missing critical parts of the template. Have you forgotten them?

We need:
Plugins list
The FULL output of `/version`

**Comment by ghost** [comment]
Well just found out that is was a plugin was a part of the issue, sorry for the report.
