### ISSUE TITLE
Velocity connections are being refused

### ISSUE THREAD

**Issue by Ampflower** [PaperMC/Paper#4925]
### What behaviour is expected:
Velocity to be able to proxy and connect to Paper.

### What behaviour is observed:
Paper kicks Velocity, and by extension, the end player trying to connect to the server.
This is the only message logged from the connection attempt despite verbose being set to true.
```
[19:52:46 INFO]: com.mojang.authlib.GameProfile@643dfcdb[id=<null>,name=_KJP12,properties={},legacy=false] (/127.0.0.1:49386) lost connection: Disconnected
```

### Steps/models to reproduce:
Within Velocity's config, set forwarding to `modern`, and the IP and port the server is hosted on.
Set Paper to run on the given IP and port.

Note, both Paper and Velocity are running within the same VPS when I ran into this issue, it is possible that it maybe localhost specific. Paper was running on `127.254.254.254:1337` with Velocity running on `0.0.0.0:25565`.
```properties
# From server.properties
query.port=1337
server-ip=127.254.254.254
server-port=1337
```
```yaml
# From paper.yml
settings:
  verbose: true
  velocity-support:
    enabled: true
    online-mode: true
    secret: "STRIPPED"
```

### Paper Plugin list:
None, this was an extremely fresh install of Paper (and Tuinity, which also suffered from the same issue).

### Paper version:
This server is running Paper version git-Paper-339 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Velocity Plugin List:
Geyser & Floodgate

### Velocity version:
Velocity 1.1.2

### Anything else:
There is none that I can think of at this time. The proxy is known to work with being set to modern as Fabric servers with FabricProxy and crossstitch have no issues with Velocity connecting to it and proxying JE and Bedrock clients.

**Comment by Ampflower** [comment]
Actually, this maybe invalid, I noticed something in Velocity's log.
```
Dec 21 19:52:46 vmMinecraft01 Minecraft[30455]: [19:52:46 INFO]: [server connection] _KJP12 -> lobby has disconnected
Dec 21 19:52:46 vmMinecraft01 Minecraft[30455]: [19:52:46 ERROR]: [connected player] _KJP12 (/my-ip:56338): unable to connect to server lobby
Dec 21 19:52:46 vmMinecraft01 Minecraft[30455]: java.lang.IllegalStateException: Backend server is online-mode!
```

**Comment by Ampflower** [comment]
It appears that in order for Velocity to connect to the server, `online-mode` in server.properties must be false. Is this intended?

**Comment by clrxbl** [comment]
Yes, read Velocity documentation

**Comment by Ampflower** [comment]
I see [here](https://velocitypowered.com/wiki/users/getting-started/#gatsby-focus-wrapper:~:text=Go%20ahead%20and%20put%20your%20servers,should%20now%20be%20ready%20for%20use.) that it is required. Interesting that FabricProxy allows Velocity to connect regardless of if the server is in online mode.

Considering this is invalid, I'll go ahead and close this then.
