### ISSUE TITLE
Crash Server When Teleport

### ISSUE THREAD

**Issue by makingsoda** [PaperMC/Paper#4926]
### Link/paste of stack trace

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

https://pastebin.com/BzZWc0m8?fbclid=IwAR3i4MaIpuixKuHKlrJOq7NRnFa6u2hVFXinZsP7xcIgz-5OUFt8f7msMIc

### Plugin list:
___A list of your plugins___

{ skript-npc v0.1.2* io.github.nanodankster.skriptnpc.SkriptNPC [NanoDankster], PluginConstructorAPI v1.0.52 me.zombie_striker.pluginconstructor.PluginConstructorAPI [Zombie_Striker], PlaceholderAPI v2.10.9 me.clip.placeholderapi.PlaceholderAPIPlugin [HelpChat], NametagEdit v4.4.10* com.nametagedit.plugin.NametagEdit [sgtcaze, Cory], ConsoleSpamFix v1.8.3 net.craftersland.consolefix.CSF [CraftersLand], CPCameraStudioReborn v1.4.2* eu.crushedpixel.camerastudio.CameraStudio [CrushredPixel, chrismin13], SkinsRestorer v13.8.6 skinsrestorer.bukkit.SkinsRestorer [Th3Tr0LLeR, McLive, DoNotSpamPls, knat], NoRainReloaded v1.3.1* me.xtomyserrax.NoRainReloaded.Main [xtomyserrax], Crawling v3.0 Arthed.Crawling.Main [], SnowballsPlus v1.0 me.scill.snowballsplus.SnowballsPlus [Scill], WorldEdit v7.1.0;8e55131 com.sk89q.worldedit.bukkit.WorldEditPlugin [], LoginSecurity v3.0.2* com.lenis0012.bukkit.loginsecurity.LoginSecurity [lenis0012], CrackShot v0.98.9 com.shampaggon.crackshot.CSDirector [Shampaggon], PlaceholderSign v1.1.5 com.sagaciousdevelopment.PlaceholderSign.Core [Sagacious_], TotemEffect v1.3* me.trungbmt.plugin.main [], ProtocolLib v4.5.1 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], LibsDisguises v10.0.20 me.libraryaddict.disguise.LibsDisguises [libraryaddict, Byteflux, Navid K.], AutoPluginLoader v1.2.2 me.PCPSells.APLMain [[PCPSells]], DivineDrop v2.6* com.demkom58.divinedrop.DivineDrop [demkom58, demkom, GdemkomG], PermissionsEx v1.23.5* ru.tehkode.permissions.bukkit.PermissionsEx [[t3hk0d3, zml]], Vault v1.7.3-b131 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], MassiveCore v3.3.0 com.massivecraft.massivecore.MassiveCore [Madus, Cayorion, Ulumulu1510], GPS v2.19.4 com.live.bemmamin.gps.Main [Benz56], Scoreboard-revision vR3 1.4.2 RELEASE* rien.bijl.Scoreboard.r.Main [HelloitsRien], StackableItems v1.0.11 haveric.stackableItems.StackableItems [haveric], HolographicDisplays v2.4.5 com.gmail.filoghost.holographicdisplays.HolographicDisplays [filoghost], WorldGuard v7.0.3;5407315 com.sk89q.worldguard.bukkit.WorldGuardPlugin [], TabuuCore v2020.8.0 nl.tabuu.tabuucore.TabuuCore [Tabuu, Tabuu, CryptoMorin], PexTabCompleter v1.2.6 com.benzoft.pextabcompleter.PexTabCompleter [Benz56], MyCommand v5.6.7 it.emmerrei.mycommand.Main [emmerrei (ivanfromitaly)], Skript v2.5 ch.njol.skript.Skript [Njol, Mirreski, bensku, TheBentoBox, FranKusmiruk, ShaneBeee, Blueyescat, JRoy, Nicofisi, APickledWalrus, xXAndrew28Xx, Syst3ms, TheLimeGlass, Pikachu920, Sashie, Wealthyturtle, OfficialDonut, eyesniper2], CustomEnderChest v1.13.1 net.craftersland.customenderchest.EnderChest [CraftersLand], AnnouncerPlus v1.2.2 xyz.jpenilla.announcerplus.AnnouncerPlus [jmp], skDragon v0.16 ud.skript.sashie.skDragonCore [Sashie], SkQuery v4.1.3 com.w00tmast3r.skquery.SkQuery [LimeGlass, w00tmast3r], HeadDatabase v4.12.6* me.arcaniax.hdb.Main [Arcaniax], ItemEdit v2.2.1 emanondev.itemedit.ItemEdit [emanon], Multiverse-Core v4.2.2-b812 com.onarandombox.MultiverseCore.MultiverseCore [dumptruckman, Rigby, fernferret, lithium3141, main--], Citizens v2.0.27-SNAPSHOT (build 2117) net.citizensnpcs.Citizens [fullwall], Sentinel v2.2.0-SNAPSHOT (build 373) org.mcmonkey.sentinel.SentinelPlugin [mcmonkey], skript-placeholders v1.5* io.github.apickledwalrus.skriptplaceholders.SkriptPlaceholders [APickledWalrus, Pikachu920], skUtilities v0.9.2* uk.tim740.skUtilities.skUtilities [tim740], NPC_Destinations v2.3.64 net.livecar.nuttyworks.npc_destinations.DestinationsPlugin [Sir_Nutty@Spigot], HolographicExtension v1.10.9 net.kitesoftware.holograms.HolographicExtension [Niall7459], WolvSK v1.7.2 fr.nashoba24.wolvsk.WolvSK [Nashoba24], skRayFall v1.9.21 net.rayfall.eyesniper2.skrayfall.Core [eyesniper2], Images v2.1.7 com.andavin.images.Images [Andavin], SkBee v1.6.0 tk.shanebee.bee.SkBee [ShaneBee], PhatLoots v5.4.2 com.codisimus.plugins.phatloots.PhatLoots [Codisimus, Redned], Denizen v1.1.4-SNAPSHOT (build 1712-REL) com.denizenscript.denizen.Denizen [The DenizenScript Team], Skellett v1.9.8 com.gmail.thelimeglass.Skellett [LimeGlass], MythicMobs v4.10.1-3456 io.lumine.xikage.mythicmobs.MythicMobs [Ashijin], NexEngine v2.0.2 su.nexmedia.engine.NexEngine [NEX-Media], WorldGuardExtraFlags v4.1.4 net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin [isokissa3], BeautyQuests v0.18_PRE2 fr.skytasul.quests.BeautyQuests [SkytAsul], WolfyUtilities v1.6.1.2 me.wolfyscript.utilities.main.Main [WolfyScript], GoldenCrates v3.9.9.2 su.nightexpress.goldencrates.GoldenCrates [NightExpress], CustomCrafting v1.6.3.0 me.wolfyscript.customcrafting.CustomCrafting [],}

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

When teleport to new chunk

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

 Paper version git-Paper-391 (MC: 1.15.2)

**Comment by JRoy** [comment]
1.15.2 is no longer supported
