### ISSUE TITLE
Removing entity while ticking! (Exception ticking world)

### ISSUE THREAD

**Issue by resi23** [PaperMC/Paper#4927]
### Link/paste of stack trace

   lastet.log https://pastebin.com/VNgaY0ki
   crash.log https://pastebin.com/cckj5fL3

### Plugin list:
AdvancedRegionMarket, AltDetector, antiRedstoneClock, BetterShulkerBoxes*, Bomberman, BungeeTabListPlus, BuycraftX, ChestShop, ChestShopNotifier*, ChestSort, Chunkmaster, ColoredAnvils*, CraftDisplay, CrateReloaded, eGlow, Essentials, EssentialsSpawn, FriendsRELOADED, FurnitureLib, HackedCore*, HackedServer*, HeadDatabase*, HolographicDisplays, Images, Jobs, LagAssist, LibsDisguises, LuckPerms, MarriageMaster, MaSuiteCore, MaSuiteTeleports, MCPerks, Multiverse-Core, PinataParty, PlaceholderAPI, PlotSquared, ProtocolLib, RFChairs, SCAdmin, SCAFK, SCAnimalChat, SCAntiBed, SCAntiClone, SCArmorStandCrashFix, SCCustomPlotsquaredFlags, SCCustomRecipes, SCEvent, SCHelper, SCLib, SCMain, SCPlotsquared, SCSchach, SCSpawner, SCUnloadInv, SCWebserver, Seedcraft, SeedCraftBooks, SeedcraftEssentials, SlotMachine, Spartan, SuperTrailsPro*, TAB, TreasureChest, Vault, VierGewinnt, Votifier, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

### Actions to reproduce (if known):
I can not say it exactly. But with us the mobs speak (texts on Armorstands with HolographigDisplay API) and I think that this is the problem but I can't adjust it whenever I try, nothing happens no matter how often or for long

### Paper version:
This server is running Paper version git-Paper-335 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Previous version: git-Paper-331 (MC: 1.16.4)

**Comment by Annabxlla** [comment]
Could this be a duplicate from you? ID: [4899](https://github.com/PaperMC/Paper/issues/4899)
**Exception ticking world**

**Comment by electronicboy** [comment]
Replicate without plugins, something is messing with internal data collections improperly causing state corruption

**Comment by HexedHero** [comment]
I've gotten this before but only when I spawned like 10-20k entities in the same chunk lmfao
