### ISSUE TITLE
Paper Instantly Stops

### ISSUE THREAD

**Issue by mmilunicmobile** [PaperMC/Paper#4930]
### What behaviour is expected:
I expected for my server to start up properly.

### What behaviour is observed:
My server starts and then instantly stops.

<img width="1222" alt="Screen Shot 2020-12-22 at 8 11 20 PM" src="https://user-images.githubusercontent.com/62996888/102947679-e05bee80-4491-11eb-8f73-65f00053954d.png">

### Steps/models to reproduce:
I am not sure exactly how to reproduce, as this just started happening. It is not really a crash so it doesn't produce an error message.

### Plugin list:
I have no plugins.

### Paper version:
It is Minecraft Version 1.16.4 paper build 342. I cannot run the version command as it stops instantly.

### Anything else:
It appears to be quickly running the stop command. I am also on a Mac running MacOS Big Sur.

**Comment by electronicboy** [comment]
1) You're missing the full exception
2) `Server attempted to load chunk saved with newer version of minecraft`

There is a JVM flag to bypass this somewhere, but, it's unsupported

**Comment by mmilunicmobile** [comment]
How can I access that flag?

**Comment by electronicboy** [comment]
```
Can I downgrade my server to 1.16.3?
"no". World downgrades are not supported by vanilla in any capacity and are not supported. Due to the crashes/corruption that world downgrading can cause, after repeated incidents of people downgrading their world and complaining at it inducing data loss, we opted to add a check to prevent this occuring.
you can disable this check by adding the JVM arg -DPaper.ignoreWorldDataVersion=true to your startup script, however, 1.16.3 is no longer supported, and the general stance of not supporting world downgrades will not change, however, 1.16.3 > 1.16.4 was a trivial upgrade which does not seem to have caused any changes which might cause this, we cannot however guarantee that you will not have issues.

We go back to our repeated reminders to backup and test before upgrading your servers, and hope that if you end up in this stance, you learn why we remind people of this consistently.
```

**Comment by mmilunicmobile** [comment]
I accidentally ran the wrong jar in the folder and upgraded it to the 1.17 snapshots. Luckily, it crashed almost immediately, so the only thing it did was replace all the grass_paths with dirt_paths, so now all our paths in our village are gone, but thank you so much for your help.
