### ISSUE TITLE
Book and Quill dupe issue

### ISSUE THREAD

**Issue by TheForgottenKing** [PaperMC/Paper#4933]
### What behaviour is expected:
Book and Quills don't cause player data save issues

### What behaviour is observed:
https://www.youtube.com/watch?v=M_Y-IyG5rk4

Console gets filled with:

`[02:52:51] [Server thread/ERROR]: Failed to save player data for username`
`java.io.UTFDataFormatException: encoded string ({"text":...??????"}) too long: 65546 bytes`

### Steps/models to reproduce:
https://www.youtube.com/watch?v=M_Y-IyG5rk4

### Plugin list:
[20:06:20 INFO]: Plugins (13): BanItem, ChatCo*, Essentials, (WorldEdit)FastAsyncWorldEdit, IllegalStack, Multiverse-Core, NoCheatPlus, ProtocolLib, RandomSpawn*, TCPShield*, ViaBackwards, ViaVersion, void-generator

### Paper version:
1d4c8fc - Might still exist on the newest one, but I can't easily test this.

### Anything else:
Seems possibly similar to the chunk save state dupe

**Comment by electronicboy** [comment]
1) Don't post dupe issues on a public issue tracker
2) Update, this has already been fixed.
