### ISSUE TITLE
Bring back vanilla features e.g. sand duping, other forms of duping that have been in minecraft

### ISSUE THREAD

**Issue by JustJP2K** [PaperMC/Paper#4934]
I absolutely love paper, performance wise very nice. I also do like that paper removes game breaking dupes like the donkey dupe. 

However i would like to see a config option to enable vanilla minecraft duping mechanics and other removed vanilla mechanics. im running a vanilla server but went with paper since performance was worse on spigot. However i got players complaining that it is not vanilla since most duping mechanics dont work anymore as well as other vanilla mechanics.

So i had to switch back to spigot

I did enable all the duping and glitching mechanics in the config that were already available but there are still things that you cant modify that paper removed, which is in the vanilla version of minecraft, for example sand duping or tnt duping, which has been in the game for a long time and its a dupe that almost all the playerbase uses. Would be nice to have that be a config option to bring back the vanilla feel, since i really want to use paper but its just doesnt have the default minecraft mechanics anymore.

**Comment by electronicboy** [comment]
No, as per the other dozen issue reports like this, we have 0 interest in maintaining bugs

**Comment by Proximyst** [comment]
Side-note: Read the pinned issue(s) on the issue tracker.
