### ISSUE TITLE
Redstone Contraption Breaking in Paper but not in Vanilla

### ISSUE THREAD

**Issue by Runningkls** [PaperMC/Paper#4941]
**Behavior Expected:**
Tree farm designed by illmango should work perfectly when run on paper with no piston glitches or redstone timing errors.  This farm runs without issue on pure vanilla.

**Behavior Observed:**
The tree farm breaks immediately once a tree is planted in it.  Multiple pistons fire at incorrect times causing blocks to be misplaced within the farm.  This seems to be caused by the server skipping redstone ticks or something similar.  This issue has been noted with multiple other farm designs of similar complexity and seems to be connected with designs containing pistons.  While the tree farm in questions is fairly complex, it by no means should cause enough lag to be considered dangerous to server tps and therefore paper shouldn't be breaking it intentionally in order to save server performance.  Therefore it should be considered a bug and not an intended feature of paper.

**Steps to Reproduce:**
1. Download tree farm world provided in video description 
2. Run farm on paperspigot as described in begining of video (only need to place a few sapplings for farm to break)
3. Observe pistons that have misfired in random places throughout the build

**Tree Farm Design:**
https://youtube.com/watch?v=Kw3kgq19nrU

**Plugin List:**  
AntiCreeper, CoreProtect, DiscordSRV, DiscordWhitelister*, dynmap*, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, GroupManager, HolographicDisplays, ImageOnMap, InventoryRollback, LimitPillagers, Multiverse-Core, OpenInv, SignShop, SpecializedCrates, Vault, VillagerOptimiser, VoxelSniper, WorldEdit

**/version Output:**
This server is running Paper version git-Paper-344 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
26.12 12:57:23 [Server] INFO Checking version, please wait...
26.12 12:57:24 [Server] INFO Previous version: git-Paper-284 (MC: 1.16.4)
26.12 12:57:24 [Server] INFO You are 1 version(s) behind

**Comment by Chew** [comment]
> Any contraption that is large enough to cause any server lag, breaks

This is... the point of Paper. Prevent lag while being as least obtrusive on normal gameplay as possible. This is one of those cases where there's really no point for it to allow it to cause lag. I'll let a core answer this but this really isn't a bug. Besides, you failed to fill out the template so there isn't much we can do with this anyway.

**Comment by MiniDigger** [comment]
generally, to be able to repro issues like this, we really need a simple build where we can see what exactly is breaking. A giant contraption like this isnt helpful. 
paper isnt skipping redstone ticks anyways.
have you enabled the alternative redstone algo in your paper config? that I can see breaking farms like this, because it intentionally changes the block update order to be more deterministic and greatly reduce the amount of updates. this is optional, because while most ppl dont notice it, we know that it can break stuff.

**Comment by Runningkls** [comment]
Assuming you're referencing the eigencraft redstone option I have that disabled.
Unfortunately I don't believe a farm much smaller than this will reproduce the same problems as I've only encountered these issues with relatively large machines.  I'm not sure how else to characterize the issue other than skipping ticks (maybe there is a more technical term that would more accurately describe it).

**Comment by n-aspen** [comment]
> Assuming you're referencing the eigencraft redstone option I have that disabled.
> Unfortunately I don't believe a farm much smaller than this will reproduce the same problems as I've only encountered these issues with relatively large machines. I'm not sure how else to characterize the issue other than skipping ticks (maybe there is a more technical term that would more accurately describe it).

Your best bet for reproduction would be to watch exactly where it fails, build that mechanism as a standalone device, then place the server under load by other lag causers like colliding entities or by limiting available resources on a test server. In general, it's also best to test on a blank server with only the plugins you need to either recreate or measure the issue.

I have to agree w/. MiniDigger here, I've built mechanisms like this on paper and didn't have any issues once I disabled eigencraft. Even if Paper is causing the issue, these mechanisms are divisible into many smaller parts that rely on numerous different mechanics to function, so it's important to know which one is breaking and under what circumstances. Is it heavy load, is it locational, chunk boundaries?? Things don't just "break" with traditional computing.

**Comment by jackmulholland** [comment]
I have the ultimate tree farm by ilmango completely working in my paper server. But it does require some tweaking to the configs. But it is not incompatible.

**Comment by Runningkls** [comment]
what config changes did you make?

**Comment by jackmulholland** [comment]
@Runningkls https://pastebin.com/fkCfZ0Mt

**Comment by Titaniumtown** [comment]
@jackmulholland could you please pastebin that instead of just pasting the whole thing in. It's easier to read that way :)
Edit: Thanks!

**Comment by Runningkls** [comment]
@jackmulholland thanks for the pastebin.  I do have one question.  Have you ever run the farm while your server is experiencing lag at all?  If so, did the farm still work flawlessly?

**Comment by e-im** [comment]
I haven't been able to reproduce this issue on 1.17.1 build 388 while I am still able to on 1.16.5 build 780 and spigot 1.17.1. While it's unfortunate that I can't point to a commit that fixed this, I am closing it as fixed. Leave a comment if you are still experiencing this issue on 1.17.1
