### ISSUE TITLE
Cats getting teleported to owner after restart

### ISSUE THREAD

**Issue by FrostII0** [PaperMC/Paper#4944]
In my survival server in paper version 1.16.4 v343 cats, upon restart get teleported to their owner if they were tied to a fence using a lead. Not all the cats are teleported but only some. I play with other people so it might be because they are only mine which is doing the problem.

### What behaviour is expected:
___What you expected to see___
The cats to stay in the pen after a restart.
### What behaviour is observed:
___What you actually saw___
Cats being tped to the owner on restart.
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Tame multiple cats and tie them to the fence then go back to spawn. Restart the server and rejoin.
### Plugin list:
___A list of your plugins___
bStats - Didn't remove it.
### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-343 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Previous version: git-Paper-288 (MC: 1.16.4)
You are 2 version(s) behind
### Anything else:
___Anything else you think may help us resolve the problem___
The latest version from now paper #345 says it fixed Fix lead duplication but I don't think it's what's making the problem since I'm not on that version and it doesn't fix leads being broken.

**Comment by HexedHero** [comment]
Does it ONLY do it to cats tied to a fence?

**Comment by electronicboy** [comment]
This is likely tied to the old age bug of leashes just disappearing in some cases, biggest issue appears to be stuff like crossing chunk boundaries, etc

**Comment by FrostII0** [comment]
I'm not exactly sure how its happening I just know that it happens this way.

**Comment by Owen1212055** [comment]
I'm unable to reproduce this, and it doesn't look like it is possible to happen unless as mentioned above the lead is somehow removed.

If you still can reproduce this issue without plugins, feel free to comment on this / open another issue with reproduction steps.

**Comment by morfeyc** [comment]
I think cats still teleport when you re-enter
https://youtu.be/05Jpf0ckwPk
