### ISSUE TITLE
Elder guardian beam particle refuses to spawn

### ISSUE THREAD

**Issue by illumeleet** [PaperMC/Paper#4948]
### What behaviour is expected:
I expect to see guardian beam properly spawned
![image](https://user-images.githubusercontent.com/51333325/103178815-68c5ff00-4897-11eb-99b1-79a16b3ad2ff.png)

### What behaviour is observed:
Guardian doesn't spawn beam particle, only bubble particles
![image](https://user-images.githubusercontent.com/51333325/103178826-8b581800-4897-11eb-9dca-dce466c9e455.png)

### Steps/models to reproduce:
Spawn guardian\elder guardian

### Plugin list:
none

### Paper version:
1.16.4-346

### Anything else:
I also tested this on 1.16.4-256, everything was working as intended. So it probably broke somwhere recently

**Comment by HexedHero** [comment]
Can confirm this issue, tested on 346 in and outside of water.

**Comment by BillyGalbreath** [comment]
https://bugs.mojang.com/browse/MC-165595

**Comment by illumeleet** [comment]
> https://bugs.mojang.com/browse/MC-165595

so why did it work with older paper 1.16.4 builds then? in the same world

**Comment by electronicboy** [comment]
There was an old patch we had which would mangle the time for fixing some stuff, no idea when that was removed; When you jump ~100 builds, it makes our ability to debug this stuff on our own too time-consuming to run though all the changes, if this is a known vanilla issue, I'd probably ask that you check your level.dat's time to see if it's affected by that issue or not

**Comment by illumeleet** [comment]
> There was an old patch we had which would mangle the time for fixing some stuff, no idea when that was removed; When you jump ~100 builds, it makes our ability to debug this stuff on our own too time-consuming to run though all the changes, if this is a known vanilla issue, I'd probably ask that you check your level.dat's time to see if it's affected by that issue or not

Ok, if i'll generate new world and test that.

**Comment by illumeleet** [comment]
I can confirm that this issue only affects old worlds. But is there any easy way to fix it without re-generating world?

**Comment by BillyGalbreath** [comment]
> I can confirm that this issue only affects old worlds. But is there any easy way to fix it without re-generating world?

I link these issues so you can see details like this...

```
When I tried to use NBTExplorer to modify the "Time" metadata in 'level.dat',
I found out that when this value reaches ~2800000 or above , this issue occurs.
Pasting this value or anything higher on a brand new world will have an 100% chance to cause this issue.
```

https://bugs.mojang.com/browse/MC-165595?focusedCommentId=822239&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-822239

**Comment by illumeleet** [comment]
Thanks for help, closing issue. Mojang probably has to fix this stuff themselves.

**Comment by Machine-Maker** [comment]
did HexedHero's patch not fix this?

**Comment by HexedHero** [comment]
Can we close this? I tested again and it is fixed.
