### ISSUE TITLE
No damage on Trident with Riptide in /pweather

### ISSUE THREAD

**Issue by ArnoPompio** [PaperMC/Paper#4949]
When a player is using Riptide* on a Trident in /pweather storm, he gets infinite fly because the trident does not break.

*Tridents enchanted with Riptide can be thrown only when a player stands in water, during snowy weather in certain biomes, or during rainy weather

### What behaviour is expected:
The Trident must take damages from each use under /pweather storm.

### What behaviour is observed:
The Trident does not take damages from each use under /pweather storm

### Steps/models to reproduce:
Using a Trident with Riptide in /pweather storm

### Plugin list:
EssentialsX version: 2.18.2.0
PlaceholderAPI version: 2.10.9
LuckPerms version: 5.2.54
Vault version: 1.7.3-b131
Citizens version: 2.0.27-SNAPSHOT (build 2197)
ChestShop version: 3.11 (build 213)
EssentialsXChat version: 2.18.2.0
EssentialsXSpawn version: 2.18.2.0

### Paper version:
Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-345 (MC: 1.16.4)

### Anything else:
EssentialsX told me to put the issue here. You can read what they said about it here : https://github.com/EssentialsX/Essentials/issues/3876

**Comment by HexedHero** [comment]
It's client-side. Prob nothing can be changed.

**Comment by electronicboy** [comment]
last I knew, this is basically a no-go, it's handled on the client and last I knew getting the client out of that state was shaky at best

**Comment by Rincewind34** [comment]
In this case the method Player#setPlazerWeather should be removed. Or at least prevent the trident to be used at all and note that in the Java Docs.

**Comment by HexedHero** [comment]
> In this case the method Player#setPlazerWeather should be removed. Or at least prevent the trident to be used at all and note that in the Java Docs.

No, it shouldn't be removed, maybe noted but not removed...

**Comment by Chew** [comment]
I see no reason to remove a perfectly useable method and cause an unnecessary breaking change. Also, I don't see the point of a note, as it's implied the weather only applies to one person.
As stated, this isn't a matter of won't fix, but can't fix. Essentially, what you'd have to do is set the server weather to storm and everyone else's player weather to sun...
