### ISSUE TITLE
Server kept on crashing

### ISSUE THREAD

**Issue by SejDevStuff** [PaperMC/Paper#4951]
### Link/paste of stack trace
___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___
link: https://pastebin.com/5Fu57hPF

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

  AsyncWorldEdit-3.8.0.jar 
  |   | AutoMessager.jar 
  |   | Citizens.jar
  |   | Clearlag.jar 
  |   | EssentialsX-2.19.0-dev+15-2342d53.jar 
  |   | EssentialsXChat-2.19.0-dev+15-2342d53.jar 
  |   | Geyser-Spigot.jar 
  |   | HolographicDisplays.jar 
  |   | LuckPerms-Bukkit-5.2.49.jar  
  |   | NoSpawn-1.9.6.jar 
  |   | OreRegen1.5.jar 
  |   | PlaceholderAPI-2.10.9.jar 
  |   | ProtocolLib.jar 
  |   | Scoreboard-revision.jar
  |   | SuperVanish.jar 
  |   | Vault.jar 
  |   | WGCustomFlags.jar 
  |   | floodgate-bukkit.jar 
  |   | multiworld.jar 
  |   | worldedit-bukkit-7.2.0-dist.jar 
  |   | worldguard-bukkit-7.0.4.jar

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Nothing happened to cause this crash, it just occurred suddenly
### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
I cannot do /version since server doesn't start properly to do any commands

**Comment by JRoy** [comment]
> --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-350 (MC: 1.16.4) ---

you have a bunch of errors with plugins on startup, this isn't a paper issue.

**Comment by SejDevStuff** [comment]
> > --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-350 (MC: 1.16.4) ---
> 
> you have a bunch of errors with plugins on startup, this isn't a paper issue.

OK, thanks for letting me know
