### ISSUE TITLE
Cancelling PlayerEditBookEvent does not prevent changes to BookMeta

### ISSUE THREAD

**Issue by aurorasmiles** [PaperMC/Paper#4952]
### What behaviour is expected:
Cancelling the PlayerEditBook event prevents any changes to the BookMeta, as described in the Javadocs

> Called when a player edits or signs a book and quill item. If the event is cancelled, no changes are made to the BookMeta

### What behaviour is observed:
Only signing the book is cancelled, you can still press "Done" and your changes to the BookMeta gets saved

### Steps/models to reproduce:
Cancel PlayerEditBookEvent and Edit a book

### Plugin list:
n/a
### Paper version:
1.16.4 #323

### Anything else:
I noticed other weird things in that event as well. Setting a new BookMeta to the Book didn't work reliably as well

**Comment by Machine-Maker** [comment]
duplicate of #2329 

Apparently this has been around for a while now.

**Comment by aurorasmiles** [comment]
Duplicate of #2329
