### ISSUE TITLE
Armor stands duplicating 

### ISSUE THREAD

**Issue by J3fftw1** [PaperMC/Paper#4955]
### What behaviour is expected:
Armor stands not to duplicate

### What behaviour is observed:
We got multiple reports of people having their armor stands duplicated. We have tracked it down to this commit or arround there of paper. 
https://github.com/PaperMC/Paper/commit/0bdfb0158975de82c1089a744fe26e11c9b9bd52
In slimefun there weren't any updates recently that changed this behavior. 

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
It's hard to reproduce it since it randomly happens.

### Plugin list:
___A list of your plugins___
https://i.imgur.com/G8xnBjO.png

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
https://i.imgur.com/xDEFsiR.png

### Anything else:
___Anything else you think may help us resolve the problem___
Feel free to message me for more info but im not sure what more i can give
https://cdn.discordapp.com/attachments/565569196218384385/792103967173115924/unknown.pnghttps://cdn.discordapp.com/attachments/793462088508768296/793462728853159986/2020-12-29_20.57.08.png

The screenshots listed above are from 2 separate servers 1 uses yatopia other uses paper .
The server that uses paper has build 344 this is the exact build it started happening it we told him to downgrade to 343 and it stopped appearing.

If there is anything we do wrong on our end feel free to point it out.

We do make the hologram/armorstand here
This is the line which relates to armor stands and entities this could be the issue not sure
https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/utils/holograms/SimpleHologram.java#L47
if there is anything changed to it please point out and we will change it. 
Thanks in advanced

**Comment by MiniDigger** [comment]
can you try on 343, the build before that commit? (https://papermc.io/api/v2/projects/paper/versions/1.16.4/builds/343/downloads/paper-1.16.4-343.jar)

your version screenshot showed that you updated 90 builds, its hard to track that down with so big ranges.
that commit in particular touched block entities, so I dont see why that should have something to do with armorstands.

**Comment by J3fftw1** [comment]
We have told server owners to do this already. We're awaiting feedback on if it doesn't happen anymore.

**Comment by J3fftw1** [comment]
I got a message back from 1 of the owners that runs a network. on 1 of his servers it happens that is on the latest version and 1 is on 343 and it doesn't happen.

**Comment by MrIvanPlays** [comment]
that's very weird. how could an api addition cause a dupe?
