### ISSUE TITLE
The server stops working at a random moment

### ISSUE THREAD

**Issue by kacpiklPL** [PaperMC/Paper#4957]
Server crash at a random moment. Players are allowed to enter. Works onJoin, loads the player, and nothing else.

My crash code:
https://hastebin.com/nofonodoba.sql

**Comment by JRoy** [comment]
> DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH 

> net.minecraft.server.v1_12_R1

**Comment by electronicboy** [comment]
Outdated server, also, likely excessive velocity
