### ISSUE TITLE
Armor stands are not affected by gravity when a block beneath them is retracted at certain distances from the player.

### ISSUE THREAD

**Issue by jackmulholland** [PaperMC/Paper#4963]
### What behaviour is expected:
When using sticky pistons to drop an armor stand down a hole, the armor stand should fall down when the block beneath it retracts even when players are 18+ blocks away or while it is not in viewable render range for entities.

### What behaviour is observed:
When within ~18 or so blocks, the behavior is as expected and the armor stand falls into a newly opened hole and has gravity and collision and reacts to being bounced on slimeblocks. But when the player is further away, the armor stand will not be affected by gravity and will not fall down the hole.

### Steps/models to reproduce:
Place a sticky piston sticky side up with a block on top. place an armor stand on top of the top block. Attach a redstone line out at least 20 or so blocks and connect a lever. Powering the lever will see the armor stand move upward. But after the armor stand comes to a rest, turning the lever off will see the armor stand unaffected by gravity and not fall down to the lower block.

### Plugin list:
BKCommonLib, BukkitCompat*, Lightcleaner, MobLimiter* (but I've also tried without MobLimiter)

### Paper version:
Paper version git-Paper-352 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Anything else:
It seems like armor stands are affected by blocks being pushed INTO them which activates their physics and gravity and further collisions but not the removal of a block beneath them when players are a certain distance away. This present problems for a lot of redstone logic. and crowds of fake npcs that move around and things players like to build.

`armor-stands-do-collision-entity-lookups`  and  `armor-stands-tick` are both enabled, and `viewdistances` is set at -1

I've attached a quick video showing the inconsistencies. Sometimes the armor stand on the right falls, and other times it doesn't. Skip to the end to see it not fall. Depends on distance.

https://user-images.githubusercontent.com/14883963/103384727-4e18a380-4aac-11eb-80b3-01624e86e396.mp4

**Comment by HexedHero** [comment]
This is intended.

**Comment by jackmulholland** [comment]
@HexedHero It’s intended even at such short distances? We’re talking under 20 blocks away. This essentially means players can’t do anything with moving armor stands even if they’re in the same room. 

Players on my server spent hours making a crowd of armor stands that would drop onto a slimeblock and bounce up and do the wave. for an audience for a minigame, and we were pulling our hair out about why it was so inconsistent with where we activated the mechanism. There was nowhere you could stand and have them all move.

And there is no config to adjust the distance at which this happens.

And if you note in #4877 this also breaks redstone logic in some circumstances

**Comment by e-im** [comment]
This would be `entity-activation-range` in spigot.yml at work. You can read more about that and what it does [here, on spigot's wiki](https://www.spigotmc.org/wiki/spigot-configuration/). Raising the value for `misc` will tick armour stands further away (in blocks) from you.
