### ISSUE TITLE
Ticking player filled map crash

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#497]
Paper build 924
Log: http://hastebin.com/pemecokodo.md
Crash report: http://hastebin.com/linimuvije.rb
User dat file: [click here to download](https://www.dropbox.com/s/p9ofhsmpploo24o/9489eca2-2cbe-4f41-878e-49404fc35ea8.dat?dl=1)

**Comment by aikar** [comment]
Ultimately this is due to a player creating a bad map in creative to crash you... will put in a protection though.
