### ISSUE TITLE
Server crash:  Exception while ticking java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by samfces** [PaperMC/Paper#4974]
### Link/paste of stack trace

```
Stack trace -> https://paste.minebox.es/honejoqora.yaml
Crash report ->https://paste.minebox.es/yatizequbu.lua
```

### Plugin list:
`antiRedstoneClock, BentoBox, BsbMongo*, BungeeTabListPlus, BuycraftX, ChestShop, ClearLag, CombatTagPlus, ConditionalCommands*, CrazyAuctions, CrazyCrates, Essentials, FastAsyncWorldEdit (WorldEdit), FastCraft, GSit, HeadDatabase, HolographicDisplays, IllegalStack, JetsAntiAFKPro, JetsMinions, Jobs, LockettePro, LuckPerms, MyPet, OldCombatMechanics, PlaceholderAPI, PlugMan, ProtocolLib, ShopGUIPlus, SilkSpawners, SkinsRestorer, spark, TitleManager*, TradeMe, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, WorldGuard`

### Actions to reproduce (if known):
`No actions known to reproduce.`

### Paper version:
```
[11:01:32 INFO]: This server is running Paper version git-Paper-351 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[11:01:32 INFO]: Previous version: git-Tuinity-"d1db107" (MC: 1.16.4)
[11:01:32 INFO]: You are 5 version(s) behind
```

**Comment by Proximyst** [comment]
Likely caused by an insanely high velocity or teleport during flight.

**Comment by samfces** [comment]
I blocked high flight speed and teleport while flying and still occurring. Same crash

**Comment by electronicboy** [comment]
There are known issues between the varying levels of the software which can cause oddball movements to crash the server, looks like you somehow tripped one of those conditions

as for the array index out of bounds, that's likely 100% unrelated to this, assuming it wasn't a side-effect of the watchdog somehow, but, we're missing a useful stack trace there, best guess would be to replicate without plugins
