### ISSUE TITLE
The plugin "QuickShop" not working, and the devs told me to report it here

### ISSUE THREAD

**Issue by wattywatty14** [PaperMC/Paper#4975]
### What behaviour is expected:
Players being able to use the QuickShops plugin.

### What behaviour is observed:
An error, the devs told me to get in contact with you.

### Steps/models to reproduce:
https://github.com/Ghost-chu/QuickShop-Reremake/issues/777

### Plugin list:
https://prnt.sc/we3a0w

### Paper version:
Paper version git-Paper-356 (MC: 1.16.4) 

### Anything else:
Nope.

**Comment by blablubbabc** [comment]
Issue is probably lines 141 and 146 of patch https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0178-API-to-get-a-BlockState-without-a-snapshot.patch
WIth the recent CraftBukkit changes, CraftSign uses the lines variable to determine whether or not it should lazily initialize it and the originalLines field (which currently remains null).

**Comment by EkonC** [comment]
I can confirm this issue

**Comment by EkonC** [comment]
This issue still persists on paper 366

**Comment by MiniDigger** [comment]
can you try 357? https://papermc.io/api/v2/projects/paper/versions/1.16.4/builds/357/downloads/paper-1.16.4-357.jar

**Comment by EkonC** [comment]
It doesn't still work

**Comment by Proximyst** [comment]
@EkonC We need a new stacktrace in that case. Open a new issue with all the relevant info, or post the trace here so we can reopen.
