### ISSUE TITLE
Auto Redact Velocity Secret in Paper.YML on Timings Report

### ISSUE THREAD

**Issue by MandMDub** [PaperMC/Paper#4979]
**Is your feature request related to a problem? Please describe.**
The current timings report when being pushed will also push the velocity "secret" config setting. This setting should be redacted similar to the way query-plugins shows as "**redacted**".

**Describe the solution you'd like**
When a timings report is created and uploaded the Velocity Secret setting in paper.yml should read **redacted** rather than showing the full velocity secret that is currently configured.

**Describe alternatives you've considered**
Another option would be to either show a partial of the secret (not sure why this would need to be viewed in a papers timing report" or would be to not include the velocity settings at all (this would be a little much IMO).

**Comment by astei** [comment]
This is not a feature request. It is a bug.

**Comment by jpenilla** [comment]
It should be hidden by default, however it seems like old configs are not getting properly auto-updated with the new default values.
