### ISSUE TITLE
getMaxDurability on Material.TRIDENT returns 0

### ISSUE THREAD

**Issue by spthiel** [PaperMC/Paper#4982]
### What behaviour is expected:
Expected getMaxDurability to return 250

### What behaviour is observed:
getMaxDurability returns 0

### Steps/models to reproduce:
Have a trident ItemStack and call getType().getMaxDurability() on it

### Plugin list:
None

### Paper version:
git-Paper-366 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by Proximyst** [comment]
This feels like an upstream issue. Is this the same on CB/Spigot?

**Comment by spthiel** [comment]
Testing this on spigot I realized the issue was that I had not included api-version in the plugin.yml (where TRIDENT doesn't exist) and it does persist up to newest version of spigot.

So this issue was entirely on my side for not using modern api-version. Please excuse this.
