### ISSUE TITLE
Tools mining speed

### ISSUE THREAD

**Issue by Ielelele29** [PaperMC/Paper#4983]
**Is your feature request related to a problem? Please describe.**
I would like to create a pickaxe (and other tools too) that could break blocks at a different speed than normal, obtaining an effect like that of efficiency but different.

**Describe the solution you'd like**
I thought you could create an attribute for the tools, which is mining speed. This attribute allows you to change the basic speed at which a tool breaks blocks.

**Comment by MiniDigger** [comment]
lucky you! this already exist :D

you can change such attributes on the itemmeta of a itemstack.

**Comment by MiniDigger** [comment]
turns out, vanilla doesnt have an attribute for dig speed or smth, mmmh

I guess thats something we could add.

**Comment by imDaniX** [comment]
> I guess thats something we could add.

Is it? I'm pretty sure that mining speed almost purely client-side based on current tool material, its enchantment(efficiency) and player's potion effects(haste or fatigue)
