### ISSUE TITLE
Custom particle creation

### ISSUE THREAD

**Issue by Ielelele29** [PaperMC/Paper#4984]
**Is your feature request related to a problem? Please describe.**
I wanted to create a REDSTONE colorable particle that would move in a direction, but it's not possible.

**Describe the solution you'd like**
I had thought that if possible, methods could be created to make particles with custom textures, which could be made able to move, **and** be colored like some of the current particles.

**Describe alternatives you've considered**
If this is not possible I would like you to at least create one or more colorable particles that can move. I imagine a particle similar to that of REDSTONE that can be colored and moved.

**Comment by electronicboy** [comment]
We cannot create custom particles from the server, the client needs to be capable of knowing what they are and such, particles are not ticked or managed by the server
