### ISSUE TITLE
TNT Duping flag not working

### ISSUE THREAD

**Issue by LewisII** [PaperMC/Paper#4985]
### What behaviour is expected:
Expected when TNT duping flag is set to true that TNT duping machines work as in vanilla. 

### What behaviour is observed:
redstone does not ignite/light up. TNT does not fire 

### Steps/models to reproduce:
Duping machine https://youtu.be/nlfAwEV-cCk?t=1283
Tried to fire with levers and restone blocks does not engage.
Tried in single player world and no problems

### Plugin list:
Dynmap-3.1-beta5-spigot.jar
DeadChest-4.2.0.jar
MultiplayerSleep.jar

### Paper version:
[19:23:22 INFO]: This server is running Paper version git-Paper-376 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[19:23:22 INFO]: Previous version: git-Paper-355 (MC: 1.16.4)
[19:23:22 INFO]: You are 7 version(s) behind
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Proximyst** [comment]
Unsupported option means no support. This will not be looked into nor fixed.

**Comment by LewisII** [comment]
> Unsupported option means no support. This will not be looked into nor fixed.

https://github.com/PaperMC/Paper/issues/3854#issue-652999033

If you are not going to support it you need to change this post to remove the working as intended as your flag is not working as intended

**Comment by Proximyst** [comment]
"TNT Duping or Bedrock Breaking issues?" - "Do you have issues with TNT duping?"
Solution: It not working is intended!

The label is still correct. If the option doesn't work anymore, that's not really our concern, nor is it the _point_ of that issue.
