### ISSUE TITLE
Permission for F3 + N and F3 + F4 Debug Gamemode Change Shortcuts

### ISSUE THREAD

**Issue by Stixil** [PaperMC/Paper#4986]
**Is your feature request related to a problem? Please describe.**
Currently there is no vanilla permission for this and is locked to op only. This can be an issue on servers where permission management is more complex.

**Describe the solution you'd like**
An introduction of permission nodes for use of these debug shortcuts.

**Describe alternatives you've considered**
I am not sure of other alternatives than this. There are external plugins that add the nodes such as https://www.spigotmc.org/resources/f3nperm.46461/ however having it native to Paper would be excellent.

**Additional context**
N/A

**Comment by Proximyst** [comment]
This is not controlled by the server. [Trick the player into thinking it is operator](https://github.com/PaperMC/Paper/pull/4956) if you wish to do this -- this is however out of scope for the server software.
