### ISSUE TITLE
NPE while using ItemMeta.getDisplayNameComponent

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5002]
### Link/paste of stack trace

```
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(StringReader.java:50) ~[?:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[patched_1.16.4.jar:git-Paper-389]
	at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:48) ~[patched_1.16.4.jar:git-Paper-389]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.getDisplayNameComponent(CraftMetaItem.java:867) ~[patched_1.16.4.jar:git-Paper-389]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaCompass.getDisplayNameComponent(CraftMetaCompass.java:22) ~[patched_1.16.4.jar:git-Paper-389]
```

### Plugin list:
My custom private plugins

### Actions to reproduce (if known):
```java
new ItemStack(Material.COMPASS).getItemMeta().getDisplayNameComponent();
```

### Paper version:
git-Paper-389 (MC: 1.16.4)

**Comment by Machine-Maker** [comment]
Does the compass have a null displayName?

I'm guessing it does since that would perfectly match the stack trace you are getting.

**Comment by ghost** [comment]
> Does the compass have a null displayname?

yep, but on `git-Paper-335 (MC: 1.16.4)` NPE not occurs

**Comment by Machine-Maker** [comment]
Yes, upstream made some changes that messed a bit with how ItemMetas store the display name. I think your best course of action is to either report it to spigot, or check if it has a displayname first. There is a nice handy hasDisplayName method just for that.

**Comment by MiniDigger** [comment]
well, this is still a bug in paper. needs a null check here https://github.com/PaperMC/Paper/blob/9f61759d9048f4322d98c524ebaeda00444c648f/Spigot-Server-Patches/0519-Support-components-in-ItemMeta.patch#L30

**Comment by Machine-Maker** [comment]
@XjCyan1de what did the method return before? A 0-length BaseComponent array?

**Comment by ghost** [comment]
> @XjCyan1de what did the method return before? A 0-length BaseComponent array?

null array, this method also annotated as `@Nullable`

**Comment by Machine-Maker** [comment]
Its annotated as `NotNull`? or was that changed as well.
![image](https://user-images.githubusercontent.com/15055071/103685184-a1be3d80-4f41-11eb-990f-2209173c4689.png)

**Comment by ghost** [comment]
> Its annotated as `NotNull`? or was that changed as well.
> ![image](https://user-images.githubusercontent.com/15055071/103685184-a1be3d80-4f41-11eb-990f-2209173c4689.png)

Oh, I was wrong, before there really was 0 length array
