### ISSUE TITLE
PlayerInteractEvent is called twice with "LEFT_CLICK_AIR" when actually right clicking a block in adventure mode

### ISSUE THREAD

**Issue by MinecraftiUndCo** [PaperMC/Paper#5015]
### What behaviour is expected:
PlayerInteractEvent calling only twice with "RIGHT_CLICK_BLOCK" for main- and off-hand

### What behaviour is observed:
After the normal two events, the events is fired again twice but now with "LEFT_CLICK_AIR" when the player is in adventure mode

### Steps/models to reproduce:
Listen on PlayerInteractEvent while player is in adventure mode and right-clicking a block. Important: The event has to be setCancelled(true) in a plugin to have the two faulty events getting fired.

### Paper version:
git-Paper-386 (MC: 1.16.4)

### Anything else:
Problem was already discussed with @MiniDigger in Discord and he stated that the commit 5650a41f5e448c1d7706aa5c0af817006001d283 with paper version #369 broked it.

![grafik](https://user-images.githubusercontent.com/5124180/103814359-ce697680-5061-11eb-871b-3bd9c3e72058.png)

**Comment by MinecraftiUndCo** [comment]
Edit: It is necessary to cancel the event to have the other two with "LEFT_CLICK_AIR".

**Comment by Machine-Maker** [comment]
Ok, so I've narrowed the issue down a bit more. When you cancel the PlayerInteractEvent the client then sends an arm animation packet with calls the extra interact event in adventure, but the client only sends that packet if you cancel the first ones.
