### ISSUE TITLE
NetworkManager Portalling VillagePlace AsyncTask Lag

### ISSUE THREAD

**Issue by LucidAPs** [PaperMC/Paper#5035]
Run three samplers, two tracking ticks above 200 and the other 400. All seem to point on the same culprit.
https://spark.lucko.me/#b42FdRqmuN
https://spark.lucko.me/#nNqo2f5bRy
https://spark.lucko.me/#02LtR5Rg24

Plugins
https://hastebin.com/dehosasovu.md

Build 391

**Comment by electronicboy** [comment]
This is a well known and understood issue and is down to portals looking for where to place the portal, you can decrease the search radius to reduce the hit, but, there is no real managical fix here which doesn't involve mojang rewriting their logic/behavior around how portals are handled and allowing these searches to be done off the main thread
