### ISSUE TITLE
Cancelling PlayerDropItemEvent deletes items on logout/kick etc.

### ISSUE THREAD

**Issue by HexedHero** [PaperMC/Paper#5036]
### What behaviour is expected:
The item to go back into the player's inventory

### What behaviour is observed:
Item is completely deleted

### Steps/models to reproduce:
Cancel **PlayerDropItemEvent** then hold an item in your cursor then close MC or get kicked in anyway.
Normally the item in your cursor will get thrown on the floor when you leave the server but if you cancel the drop item it'll get deleted completely instead of being added back into the player's inventory like how the event handles it every other time.

### Plugin list:
Plugins (1): DevTest
A test plugin that just cancels the PlayerDropItemEvent 
    @EventHandler
    public void drop(PlayerDropItemEvent event) {
        event.setCancelled(true);
    }

### Paper version:
[22:48:31 INFO]: This server is running Paper version git-Paper-399 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[22:48:31 INFO]: Checking version, please wait...
[22:48:31 INFO]: You are running the latest version

**Comment by electronicboy** [comment]
afaik, the item isn't in an inventory so the server just drops the item and the client naturally picks it up in those cases or something, would need to look deeper

**Comment by HexedHero** [comment]
I found a workaround for it,
Check if the player in question isValid, seems the drop event fires after they leave so you can just ignore it and they makes it drop like normal.

**Comment by electronicboy** [comment]
I looked at the logic, vanilla just explicitly throws the item into the world if you close an inventory with an item on the cursor

**Comment by HexedHero** [comment]
How do you think the drop event should act in this case if cancelled? We shouldn't ignore the event being cancelled nor should we just delete items IMO we should put the item back into the player's inventory but I'm unsure if that's possible due to no knowing the player doesn't exist when this event fires.

**Comment by Machine-Maker** [comment]
Why can't we know if the player doesn't exist? Is the PlayerDropItemEvent called before the player disconnects?

**Comment by Strahilchu** [comment]
I noticed this! Some of my players items randomly disappear like this
