### ISSUE TITLE
Out of random lag spike error

### ISSUE THREAD

**Issue by jakkeren** [PaperMC/Paper#5037]
Out of random our server receives this error from paper. Doesn't seem like any plugins fault, after reading the dump:

`10.01 02:30:00 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-399 (MC: 1.16.4) ---
10.01 02:30:00 [Server] ERROR The server has not responded for 10 seconds! Creating thread dump
10.01 02:30:00 [Server] ERROR ------------------------------
10.01 02:30:00 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
10.01 02:30:00 [Server] ERROR ------------------------------
10.01 02:30:00 [Server] ERROR Current Thread: Server thread
10.01 02:30:00 [Server] ERROR PID: 32 | Suspended: false | Native: true | State: RUNNABLE
10.01 02:30:00 [Server] ERROR Stack:
10.01 02:30:00 [Server] ERROR java.net.SocketInputStream.socketRead0(Native Method)
10.01 02:30:00 [Server] ERROR java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
10.01 02:30:00 [Server] ERROR java.net.SocketInputStream.read(SocketInputStream.java:171)
10.01 02:30:00 [Server] ERROR java.net.SocketInputStream.read(SocketInputStream.java:141)
10.01 02:30:00 [Server] ERROR sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:457)
10.01 02:30:00 [Server] ERROR sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
10.01 02:30:00 [Server] ERROR sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1095)
10.01 02:30:00 [Server] ERROR sun.security.ssl.SSLSocketImpl.access$200(SSLSocketImpl.java:72)
10.01 02:30:00 [Server] ERROR sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:815)
10.01 02:30:00 [Server] ERROR java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
10.01 02:30:00 [Server] ERROR java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
10.01 02:30:00 [Server] ERROR java.io.BufferedInputStream.read(BufferedInputStream.java:345)
10.01 02:30:00 [Server] ERROR sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
10.01 02:30:00 [Server] ERROR sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
10.01 02:30:00 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
10.01 02:30:00 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
10.01 02:30:00 [Server] ERROR sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
10.01 02:30:00 [Server] ERROR com.mojang.authlib.HttpAuthenticationService.performPostRequest(HttpAuthenticationService.java:88)
10.01 02:30:00 [Server] ERROR com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:104)
10.01 02:30:00 [Server] ERROR com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:99)
10.01 02:30:00 [Server] ERROR com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:56)
10.01 02:30:00 [Server] ERROR com.destroystokyo.paper.profile.PaperGameProfileRepository.findProfilesByNames(PaperGameProfileRepository.java:44)
10.01 02:30:00 [Server] ERROR net.minecraft.server.v1_16_R3.TileEntitySkull$1.load(TileEntitySkull.java:65)
10.01 02:30:00 [Server] ERROR net.minecraft.server.v1_16_R3.TileEntitySkull$1.load(TileEntitySkull.java:47)
10.01 02:30:00 [Server] ERROR com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
10.01 02:30:00 [Server] ERROR com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
10.01 02:30:00 [Server] ERROR com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
10.01 02:30:00 [Server] ERROR com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
10.01 02:30:00 [Server] ERROR com.google.common.cache.LocalCache.get(LocalCache.java:4154)
10.01 02:30:00 [Server] ERROR com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
10.01 02:30:00 [Server] ERROR com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
10.01 02:30:00 [Server] ERROR com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
 `

**Comment by electronicboy** [comment]
You missed the template, and the full trace... You have skulls somewhere in the world which is causing lookups to mojangs textures server
