### ISSUE TITLE
Debug Stick Changing The Block State Of Multiple Stair Blocks At Once

### ISSUE THREAD

**Issue by AbstractYoshi** [PaperMC/Paper#5038]
### What behaviour is expected:
Changed Block State Of Stairs

### What behaviour is observed:
Both Stair Blocks Having Their States Changed At Once

### Plugin list:
Don't Have Any

### Paper version:
git-Paper-399 (MC: 1.16.4)

**Comment by MiniDigger** [comment]
well, you gotta provide more info than that, a picture or a video maybe? (you can just drag and drop them into the comment box to upload them)

**Comment by AbstractYoshi** [comment]
![2021-01-11_07 07 44](https://user-images.githubusercontent.com/77218976/104180841-cbf97a80-53db-11eb-8d76-c6b61321b372.png)
![2021-01-11_07 07 49](https://user-images.githubusercontent.com/77218976/104180846-cd2aa780-53db-11eb-92d6-9c4ea02cbce4.png)

**Comment by e-im** [comment]
I can provide a bit more of a clear outline on this- was with him in #paper-help a couple of days ago.
This is just the debug stick updating neighboring blocks as reported in #2134, although the fix never worked. I went over it with him on discord [here](https://discord.com/channels/289587909051416579/289587909051416579/797664654830731284), and reproduced on both versions 341 (when the fix was applied) and 399 without any plugins.

**Comment by e-im** [comment]
This is still not completely fixed. To test this I put four blocks down next to eachother. From left to right: Redstone lamp, piston, and two purpur stairs. I right clicked on them each once with the debug stick, again from left to right.
Here are the results from a vanilla server:
![vanilla server](https://sulu.me/3ef133.png)
And here is the same thing performed on the latest paper build (404)
![paper build 404](https://sulu.me/95fc3d.png)

What is expected is for the redstone lamp to turn on, the piston to lose it's head, and for both stairs to turn.
What actually happens is the lamp lights, but by extending the piston head the lamp updates and gets unlit. By rotating the stair the piston then retracts, and the piston retracting then brings the first stair back to it's original position. The second stair rotates normally as there is nothing to update it.
