### ISSUE TITLE
Paper v400 error on startup

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5039]
When starting the server this appears every time;

10.01 01:29:26 [Server] Startup [06:29:26 ERROR]: Failed to load function dsplayer:heart
10.01 01:29:26 [Server] INFO java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Invalid integer '1.4' at position 32: ...ds-health=<--[HERE]
10.01 01:29:26 [Server] INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
10.01 01:29:26 [Server] INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
10.01 01:29:26 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[?:?]
10.01 01:29:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
10.01 01:29:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
10.01 01:29:26 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
10.01 01:29:26 [Server] INFO Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Invalid integer '1.4' at position 32: ...ds-health=<--[HERE]
10.01 01:29:26 [Server] INFO at net.minecraft.server.v1_16_R3.CustomFunction.a(CustomFunction.java:69) ~[patched_1.16.4.jar:git-Paper-400]
10.01 01:29:26 [Server] INFO at net.minecraft.server.v1_16_R3.CustomFunctionManager.a(SourceFile:86) ~[patched_1.16.4.jar:git-Paper-400]
10.01 01:29:26 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
10.01 01:29:26 [Server] INFO ... 3 more

The server works just fine and iv'e tried resolving it on my end aswell as removing certain things i thought it may be but by reading it i think perhaps its on your end so figured id let you guys know.

Full Server Log: https://mcpaste.io/fa81e6bc19060d30

**Comment by zml2008** [comment]
`10.01 01:29:26 [Server] Startup [06:29:26 ERROR]: Failed to load function dsplayer:heart` 

You have an error in a datapack function.
