### ISSUE TITLE
Creating invisible entities

### ISSUE THREAD

**Issue by CDFN** [PaperMC/Paper#5040]
Hey, recently I wanted to create invisible arrow, however there's no setInvisible method available on Arrow interface (Arrow doesn't implement LivingEntity).
Current workaround for this is sending PacketPlayOutEntityDestroy to specific player which completly removes entity for client.  I'd like to hear what do you think about adding some interface which would add method hiding entity for one or more players using PacketPlayOutEntityDestroy. I'm not very familiar with existing codebase, hence not sure if it may cause any side-effects for clients. Every opinion is appreciated.

**Comment by MiniDigger** [comment]
mmmh, iirc, invisibility is handled for entities, not just living entities, on a metadata level, is this differently in code or why did bukkit model it like this?

**Comment by yannicklamprecht** [comment]
> mmmh, iirc, invisibility is handled for entities, not just living entities, on a metadata level, is this differently in code or why did bukkit model it like this?

https://github.com/PaperMC/Paper/pull/4722

Can be done by canceling this event, when merged.
This was initially created to hide projectiles but allow spawning particles at the entities location, for custom projectile trails.

**Comment by Owen1212055** [comment]
![image](https://user-images.githubusercontent.com/23108066/147400084-c68f7ce1-b1f4-4b1c-bc00-76d60e080419.png)

There is an upstream API that allows you to achieve this (it is currently experimental).
You can't mark arrows as invisible because certain entities just totally ignore their invisibility value. 

This can probably be closed.

**Comment by Chew** [comment]
Indeed, https://papermc.io/javadocs/paper/1.18/org/bukkit/entity/Player.html#hideEntity(org.bukkit.plugin.Plugin,org.bukkit.entity.Entity)

This ultimately solves the initial issue, make the player unable to see the arrow. If it's not entirely what you're wanting, let us know.
