### ISSUE TITLE
Issue Villager trade discount

### ISSUE THREAD

**Issue by Amazingleo29** [PaperMC/Paper#5041]
### What behaviour is expected:
___Villager have same discount for all player, after being cured___

### What behaviour is observed:
___Only one player can get discount on a villager trade___

### Paper version:
___This server is running Paper version git-Paper-393 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)___

**Comment by electronicboy** [comment]
Vanilla bug fix, see https://github.com/PaperMC/Paper/pull/4871
