### ISSUE TITLE
API for remove anvil italic

### ISSUE THREAD

**Issue by Ielelele29** [PaperMC/Paper#5042]
**Is your feature request related to a problem? Please describe.**
I tried all the functions I came up with to remove italics from renamed objects in the anvil, but i believe this formatting is added after the AnvilPrepareEvent

**Describe the solution you'd like**
A function that allows me to disable this formatting.

**Describe alternatives you've considered**
The formatting of the anvil is applied before the AnvilPrepareEvent, so that with the getResult() you get the ItemStack with the name already modified and editable.

**Comment by lukalt** [comment]
I actually think the formatting is added by the client before the new name is sent to the server.  What's your code to extract the new name of the item?

**Comment by Ielelele29** [comment]
```
@EventHandler
public static void onPutItemInAnvilEvent(PrepareAnvilEvent e)
{
	if (e.getInventory() != null)
	{
		AnvilInventory ai = e.getInventory();
		if (ai.getResult() != null)
		{
			ItemStack is = ai.getResult();
			ItemMeta im = is.getItemMeta();
			if (im.getDisplayName() != "" && im.getDisplayName() != null)
			{
				if (is.getEnchantments().isEmpty())
				{
					im.setDisplayName("§f" + im.getDisplayName());
				}
				else
				{
					im.setDisplayName("§b" + im.getDisplayName());
				}
			}
			is.setItemMeta(im);
			e.setResult(is);
		}
	}
}
```

This should add light blue if the object is enchanted, otherwise white; some times it worked fine, but most of it didn't. I tried with a replace to remove the italic but it had not yet been applied. The only way I have found is to change it with a tick of delay, but it is quite inconvenient.

**Comment by MrIvanPlays** [comment]
did u try the color "reset" or §r ?

**Comment by Ielelele29** [comment]
Yes, but it doesn't work.
