### ISSUE TITLE
[Request] Init command to prepare jar and dir structure

### ISSUE THREAD

**Issue by MichaIng** [PaperMC/Paper#5046]
**Is your feature request related to a problem? Please describe.**
Currently, if one wants to setup a fresh instance of PaperMC, the server needs to be started and it needs to be waited until the directory structure and configuration files are created. Then the server needs to be stopped to allow configuring it (using the default configs as starting point), installing plugins etc. Especially scripting an install and setup based on default configs is therefore a bid complicated.

**Describe the solution you'd like**
It would be great to have sort of an init command, which makes the server stop after the initial file structure, default config files (if missing) and, if possible even plugins (to have their config files as well), created, but before binding to a port, starting the world and spawn areas, e.g. between those two startup steps:
```
Jan 06 18:02:17 VM-Buster papermc[5382]: [18:02:17 INFO]: Generating keypair
Jan 06 18:02:18 VM-Buster papermc[5382]: [18:02:18 INFO]: Starting Minecraft server on *:25565
```

**Describe alternatives you've considered**
Instead of patching such a feature into the main server, a plugin could do the job that stops the server when being enabled.

**Additional context**
Initial request at Paperclip repo where it does not fit well but with short discussion already: https://github.com/PaperMC/Paperclip/issues/32
The exact implementation depends on the aim/use case, e.g. plugins are enabled, creating their config files, after the server has bound to an interface already and the world + spawn areas got created. So it makes sense to get some more opinions and use cases for this feature, and someone who can evaluate the effort, before deciding when and how the server should stop most reasonable.

**Comment by Machine-Maker** [comment]
Well, like electronicboy mentioned in the other issue, if you want to wait until all plugins are enabled, then you have to load the worlds. Some plugins rely on being enabled **after** world loading.

**Comment by Chew** [comment]
This is true. At most, it would generate all the necessary files without world or plugin loading, but that's half the issue as well.

**Comment by MichaIng** [comment]
I have no idea how much work it would be, and if there are any others which would find this useful, so I have zero expectations, but to cover all more use cases making both ideas available as individual option would be awesome:
- Exiting after base server init, to have base directory structure and `server.properties` generated, before loading the world.
- Exiting after all plugins have been enabled, after the load has been loaded, to have all plugin configs available as well.

Our install script indeed could make use of both options since we have choice included to install Geyser and Floodgate plugins, which are then pre-configured as well. Currently we start the service and run a file detection loop, but it's a bit unclean and difficult to then still show the servers output, so that users on slower hardware can see the PaperMC start procedure.
