### ISSUE TITLE
Auto update flag?

### ISSUE THREAD

**Issue by BaxAndrei** [PaperMC/Paper#5050]
I have a lot of servers to manage and its hard for me to check always witch one is outdated and my panel dont have yet Something to update every server automatically.

Something like `-auto-update` flag that will automatically check for latest version for curent version before starting server.

Edit: sorry. I accidentally checked wrong type. I meant to add a suggestion.

**Comment by Machine-Maker** [comment]
auto updating is a bad idea. You should always know what changes are being made before you update. And its really simple to add a version check to the startup script since papermc offers a [version API](https://papermc.io/api/docs/swagger-ui/index.html?configUrl=/api/openapi/swagger-config).

**Comment by Proximyst** [comment]
Never. We have the aforementioned API.
