### ISSUE TITLE
Bukkit.createVanillaChunkData causing freeze

### ISSUE THREAD

**Issue by alfiejfs** [PaperMC/Paper#5051]
### What behaviour is expected:
The server to not freeze and generate the vanilla chunk data for a given chunk

### What behaviour is observed:
A server freeze: 
![image](https://user-images.githubusercontent.com/42497992/104258663-f00a9980-5477-11eb-9d71-af08d9f88b76.png)

### Steps/models to reproduce:
Use a ChunkGenerator such as the following:
```
  @Override
  public ChunkData generateChunkData(World world, Random random, int chunkX, int chunkZ, BiomeGrid biome) {
    return Bukkit.createVanillaChunkData(world, chunkX/2, chunkZ/2);
  }    
```

on any new server (with no world generated). Untested if a world is already generated and trying to load new chunks.

### Plugin list:
![image](https://user-images.githubusercontent.com/42497992/104258491-90ac8980-5477-11eb-9958-52f6981ca763.png)

### Paper version:
![image](https://user-images.githubusercontent.com/42497992/104258479-8d190280-5477-11eb-99fd-f452fcdc5cc6.png)

### Anything else:
The call to `Bukkit.createVanillaChunkData(World, int, int)` is causing the freeze. It does not freeze up if you use the chunkX and chunkZ passed into the `generateChunkData` method, but if you modify those values in any way (or at least, divide them by 2 - I haven't tried with other modifications but assume the same applies), the server freezes.

If this is intended behaviour I apologise, but I am not sure it is.

**Comment by MiniDigger** [comment]
Why would you want to modify the coordinates? 
I would guess attempting to create chunk data for other chunks, while one chunk is being generated, ends in a deadlock, but would need a jstack to confirm that.
If that's the case, we should add a note to the javadocs, but i am not sure more than that could be done.

**Comment by alfiejfs** [comment]
> Why would you want to modify the coordinates?

I was trying to do something like scaling the world, so each block takes up a 2x2 space, which obviously requires loading the chunks of the effectiveX and effectiveZ. I can achieve this just by generating two worlds, but wasn't sure why it didn't work in the generator.

**Comment by JRoy** [comment]
Likely no longer an issue, please reply if you are still having problems with this.
