### ISSUE TITLE
General question about the paper API

### ISSUE THREAD

**Issue by Sukram28** [PaperMC/Paper#5057]
General question about the paper API

I don't know where best to ask this question. That's why I ended up here.
I feel really bad for asking this, but I planned to write a plugin for paper. Normally I used to use paperAPI.jar and integrated it as a Java Build Path. In the meantime, this jar no longer seems to exist. Since I've never really worked with Maven or Gradle, I don't really know what to do to integrate the API into Eclipse. (The How to right here doesn't help me a lot :/ https://github.com/PaperMC/Paper/)

**Comment by Machine-Maker** [comment]
Well I would start working with maven or gradle. It makes dealing with dependencies way easier. If you do really just want to add the JAR to the build path, then clone this repo, and run `./paper jar` and add that jar, but DON'T DO THAT. There are a zillion tutorials for using maven or gradle for mc plugins.

Also, this question is better asked [on discord](https://discord.gg/papermc).

**Comment by MiniDigger** [comment]
in the future, please ask questions on [discord](https://discord.gg/papermc) or on the [forums](https://papermc.io/forums/)
