### ISSUE TITLE
Server Throws Error for waterlogged chest

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5059]
I noticed when running a 1.16.4 version of Paper, an error is put in the console stating
`Block at2,068, 60 -74 is Block{minecraft:water} but has net.minecraft.server.v1_16_R3.TileEntityChest@6346fd32. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.`
Upon teleporting to the coordinates in the error, it appears to be a waterlogged chest from random world generation. And this error is thrown when placing any chest in water.

**Comment by Machine-Maker** [comment]
Duplicate of #3318 **and** #4729 (with a fix in #4784)

**Comment by Chew** [comment]
See above, plus please fill out the template next time, not much we can do without it.
