### ISSUE TITLE
[Request] Add categories to entity-per-chunk-save-limit

### ISSUE THREAD

**Issue by YouHaveTrouble** [PaperMC/Paper#5061]
It would be extremely useful to have some categories/keywords for entity-per-chunk-save-limit option, like for example:

    entity-per-chunk-save-limit:
      projectiles: 8
      hostile: 16
      animals: 24
      all: 8

The reason for this is it's extremely easy to miss entity types while listing them one by one like currently.

**Comment by jpenilla** [comment]
This seems to be non-trivial to do, as there isn't really a way to get the Entity class from the EntityTypes, which means we can't easily check inheritance from IProjectile for example.

**Comment by MiniDigger** [comment]
hardcoding it is, lol
