### ISSUE TITLE
Server warnings when op joins

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5064]
When an op player joins I get these warnings:

>.... [20:22:35 ERROR]: java.lang.NullPointerException
>.... [20:22:35 WARN]: java.lang.NullPointerException
>.... [20:22:35 WARN]: at net.minecraft.server.v1_16_R3.PacketDataSerializer.a(PacketDataSerializer.java:203)
>.... [20:22:35 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayOutChat.b(PacketPlayOutChat.java:45)
>.... [20:22:35 WARN]: at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:42)
>.... [20:22:35 WARN]: at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:12)
>.... [20:22:35 WARN]: at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
>.... [20:22:35 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [20:22:35 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [20:22:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
>.... [20:22:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
>.... [20:22:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
>.... [20:22:35 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
>.... [20:22:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
>.... [20:22:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
>.... [20:22:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
>.... [20:22:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
>.... [20:22:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
>.... [20:22:35 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
>.... [20:22:35 WARN]: at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$1.write(BukkitPipelineInjector.java:53)
>.... [20:22:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
>.... [20:22:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
>.... [20:22:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
>.... [20:22:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
>.... [20:22:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
>.... [20:22:35 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
>.... [20:22:35 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
>.... [20:22:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
>.... [20:22:35 WARN]: at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:305)
>.... [20:22:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
>.... [20:22:35 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
>.... [20:22:35 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
>.... [20:22:35 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
>.... [20:22:35 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
>.... [20:22:35 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by electronicboy** [comment]
you have a plugin sending bad chat packets

**Comment by aurorasmiles** [comment]
Next time, please provide more information, like a plugin list, complete logs, etc. There are templates for that when creating an issue here, please don't ignore them.
