### ISSUE TITLE
An expected class  io.netty.channel.AbstractChannelHandlerContext$13 was not found

### ISSUE THREAD

**Issue by andrewkm** [PaperMC/Paper#5066]
Updated paper to 418 from 412
Getting on every start:
`[01:25:57] [main/WARN]: An expected class  io.netty.channel.AbstractChannelHandlerContext$13 was not found for preloading: io.netty.channel.AbstractChannelHandlerContext$13`

**Comment by JRoy** [comment]
you're going to need to share the entire startup log

**Comment by electronicboy** [comment]
It's the class preloading, 13 no longer exists, no idea if that's changed number or gone, not sure how aikar was creating this list and I really no go go juice for that right now

**Comment by aikar** [comment]
Did netty version change?
