### ISSUE TITLE
Specify a configs directory in the command line args

### ISSUE THREAD

**Issue by timschwab** [PaperMC/Paper#5068]
**Is your feature request related to a problem? Please describe.**
I am attempting to Dockerize my MC server and it is mostly going well, but the config files (server.properties, paper.yml, etc) are proving frustrating to manage. I would like the config files to be in their own volume, but this has proved frustrating because they are hardcoded to be at the root.

**Describe alternatives you've considered**
I am putting this section in front of the solution section, if that is okay. I have considered just copying in the files from my host, but sometimes I want the MC instance to edit the files (such as in the case of ops.json). I have considered trying to have the MC root be a volume, but I don't want paper.jar to be included in the volume. Finally, I could try running paper.jar with the -Duser.dir flag, but I want the world data in a separate volume as the config data. So none of these solutions function as I would like.

There are currently two options that function as I would like. First, have every config file be a single-file volume. This works, but is not nice because I have to list every single config file as a volume in my docker-compose.yml file. Secondly, I can create symlinks from a config volume into the root. This is currently what I am doing, and it was inspired by [this repo](https://github.com/FelixKlauke/paperspigot-docker). However, this has the same unfortunate requirement to specify every config file I am doing this for.

**Describe the solution you'd like**
What I would like is something similar to the bukkit.yml > settings > world-container option, but for config files. The question immediately becomes, where would this be listed? There are two options: either a root-level config file, or the command line. Since having one root-level config file kind of defeats the purpose of the option (which is to move all configuration files into a separate directory), I think the best choice would be a command line option. Something like `--config-dir configs`. I asked in the Discord if this was done already and get a response of no.

The second question becomes, which files would this include? This is probably more debatable, but this would be my preference:

- server.properties
- ops.json
- whitelist.json
- banned-players.json
- banned-ips.json
- permissions.yml
- bukkit.yml
- spigot.yml
- paper.yml

It may even make sense to split it into two separate directories, one with the json files and permissions.yml, the other with everything else.

Thank you for your time, and I would love to hear feedback on this.

**Comment by MiniDigger** [comment]
there a options for a ton of files already:

```
 martin@PC-MARTIN  /mnt/d/IntellijProjects/Paper116  ➦ 169d8b49e ✚  java -jar Paper-Server/target/paper-1.16.5.jar --help
Option                                  Description
------                                  -----------
-?, --help                              Show the help
-C, --commands-settings <File: Yml      File for command settings (default:
  file>                                   commands.yml)
-P, --plugins <File: Plugin directory>  Plugin directory to use (default:
                                          plugins)
-S, --spigot-settings <File: Yml file>  File for spigot settings (default:
                                          spigot.yml)
-W, --universe, --world-container, --   World container (default: .)
  world-dir <File: Directory
  containing worlds>
-b, --bukkit-settings <File: Yml file>  File for bukkit settings (default:
                                          bukkit.yml)
-c, --config <File: Properties file>    Properties file to use (default:
                                          server.properties)
-d, --date-format <SimpleDateFormat:    Format of the date to display in the
  Log date format>                        console (for log entries)
--demo                                  Demo mode
--eraseCache                            Whether to force cache erase during
                                          world upgrade
--forceUpgrade                          Whether to force a world upgrade
-h, --host, --server-ip <String:        Host to listen on
  Hostname or IP>
--log-append <Boolean: Log append>      Whether to append to the log file
                                          (default: true)
--log-count <Integer: Log count>        Specified how many log files to cycle
                                          through (default: 1)
--log-limit <Integer: Max log size>     Limits the maximum size of the log
                                          file (0 = unlimited) (default: 0)
--log-pattern <String: Log filename>    Specfies the log filename pattern
                                          (default: server.log)
--log-strip-color                       Strips color codes from log file
--noconsole                             Disables the console
--nogui                                 Disables the graphical console
--nojline                               Disables jline and emulates the
                                          vanilla console
-o, --online-mode <Boolean:             Whether to use online authentication
  Authentication>
-p, --port, --server-port <Integer:     Port to listen on
  Port>
--paper, --paper-settings <File: Yml    File for paper settings (default:
  file>                                   paper.yml)
-s, --max-players, --size <Integer:     Maximum amount of players
  Server size>
--server-name <String: Name>            Name of the server (default: Unknown
                                          Server)
-v, --version                           Show the CraftBukkit Version
-w, --level-name, --world <String:      World name
  World name>

```

so only really missing are the json files. those arent configs, but data files, but I can understand the need for a mount here, which would be easier in a folder.

**Comment by timschwab** [comment]
Oh wow, okay I did not realize that. That is quite helpful, thanks. But yeah, it still would be nice to have options for the json files. Plus, it could be nice to have one directory option for all the config files, though that is nitpicky, and I could just specify each config file on the command line.
