### ISSUE TITLE
Plugins get disabled if they throw a error at startup.

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#507]
I've noticed for a while that some plugins will load on spigot and some won't load on paper because of a error thrown at the beginning of startup by the plugin.  Could you maybe add an option to allow plugins to still get enabled if they throw a error on startup? For example, LWC works on spigot. But if you try to load it on paper it won't load because of a error at startup.

Maybe add an option in paper.yml to allow plugins to try and start if they throw a error?

**Comment by kashike** [comment]
I assume this isn't an issue?

**Comment by jordanwilliams1** [comment]
@kashike I'm not sure anymore.. Here's my problem https://github.com/PaperMC/Paper/issues/510

**Comment by aikar** [comment]
I'm not a fan of allowing people to accept a completely bad setup.

You should get the author to fix the problem rather than ignoring it.

**Comment by jordanwilliams1** [comment]
@aikar Understandable, But sometimes it takes a few days for it to be updated. Maybe you could add an option in paper.yml to allow plugins to start?

**Comment by aikar** [comment]
No, the plug-ins are in a critical unknown state. They are not safe until the author gracefully handles missing a major dependency it expected
