### ISSUE TITLE
ItemStack#setType is heavy when the itemstack got a bunch of display name and lore

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/Paper#5071]
plugin in question here calls ItemStack#setType to DIAMOND_PICKAXE, to call getDrops using the tool and getting the right drops. replacing that with new ItemStack(DIAMOND_PICKAXE) avoided this issue

https://spark.lucko.me/#YnTs0gpbw1
![https://i.imgur.com/NnRvM3o.png](https://i.imgur.com/NnRvM3o.png)

we should be able to avoid the reparsing here, doesnt seem necessary

**Comment by ghost** [comment]
Thats itemmeta for you, terrible and slow system. There needs to be a better system in place for reading lore/enchants

**Comment by Chew** [comment]
Please avoid off-topic discussions on issues.

**Comment by MiniDigger** [comment]
He's right tho, looking at CraftMetaItem gives me cancer, I would very much prefer a mutable system in general.

but point of this issue is that the plugin in question was touching setType, not even the meta. so the nbt is already there and in theory should be able to be just copied over or smth.
I didn't look deeper yet tho.

**Comment by MrIvanPlays** [comment]
looking into this looks like bukkit gets completely new objects and doesn't modify at all the old ones.
there are also at least 2 calls to CraftMagicNumbers#getItem in CraftItemStack#setType which can be expensive in some cases.

**Comment by kashike** [comment]
`ItemStack#setType` is being deprecated (https://github.com/PaperMC/Paper/pull/10290).
