### ISSUE TITLE
mob spawn cancellation back-off

### ISSUE THREAD

**Issue by electronicboy** [PaperMC/Paper#5076]
[Not feeling well, but, wanted to make this issue while I remembered, please bear with me]

A common issue with mob spawning in modern versions of the server is how expensive and heavy-handed it is, plugins that clear mobs in the world often induce these types of spikes

In vanilla, the seeming reliance on mob spawning is that when you log in, you'll quickly (within a hanful of ticks to my recollection of the logic/experience) hit the spawn limit, it seems that the intent is that you'll stick to the mob limits pretty closely and deal with mobs slowly spawning back in due to the nature of things like the hard/soft despawn ranges removing mobs slow enough for the server to spawn the back in a small number each tick as they die off, this is fine;

However, there comes an issue due to this with when mobs spawns are canceled, e.g. such as with worldguard, in that the server will consistently try to meet the spawn targets, this is especially an issue with aspects like per player mob spawning, in which it's pretty easy for a plugin preventing spawns in a region for a handful of players to spend a good few ms trying to spawn mobs (I've personally seen this off the top of my head peek to 7-10ms with just bats prevented on some servers)

While, solving this on a global level is generally unviable, imho, there is no sane way to guarantee mob spawns without some form of granularity to ensure that spawning stays sane (the way the vanilla logic works has me worried that a global/chunk based attempt would introduce more caveats than worth investigating), it would potentially be ideal for per-player mob spawning to have a per-player back-off, easiest way I can see to do this is to artificially increase the number of mobs it sees for a player, if the server has had 3 mobs spawns, act as if we have 3 extra mobs in the chunk when checking the limits to allow us to back off here, and slowly bleed those off

This is just a theory as to what can be done to improve the performance of servers using things like protection plugins, there may be other solutions or the idea here may be so nuanced to implement, this does not solve a few vanilla issues with how spawning e.g. cases where there are few viable places for mobs to spawn can also induce similar performance penalties

**Comment by BillyGalbreath** [comment]
To combat this on my own server I just increased the `ticks-per` in `bukkit.yml` so that _nothing_ is vigorously spamming spawns per tick. By default monsters, water, water-ambient, and ambient all default spawns at a 1 tick interval. I've personally set monsters to 20, water to 100, water-ambient to 100, and ambient to 400. This allows my server to not get overwhelmed when players are inside spawn protected claims (some of which can extend far beyond the spawn ranges).

**Comment by kickash32** [comment]
So how would the backoff map work exactly? Is there going to be a limit to the back off map? I'm not certain how exactly mob spawning works but it can fail multiple times for each mob spawn so it would be very easy for the back off values to be many multiples of the mob spawn limits. We could add a limit to the back off values do not go above the mob spawn limit. Another thing to consider is how we are bleeding off the values, is it linear or exponential (or other)? Also is it going to be configurable through paper.yml?
