### ISSUE TITLE
Chickens from chicken jockeys despawn, even when named

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5077]
### What behaviour is expected:
___What you expected to see___
Named chickens to not despawn when ridden by a named baby zombie.
### What behaviour is observed:
___What you actually saw___
The named chicken despawns if the chunk is unloaded and reloaded.
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Spawn a chicken jockey and name both of them. Unload the chunk, by tping out or relogging. Chicken will disappear.
(Probably problem with implementation of chicken jockey chickens despawning)
### Plugin list:
___A list of your plugins___
n/a
### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Chew** [comment]
Missing Paper /version. Please confirm this happens on latest

**Comment by ghost** [comment]
> Missing Paper /version. Please confirm this happens on latest

I reported this on 1.16.4, but it still happens in the latest 1.16.5 release.

**Comment by Machine-Maker** [comment]
Cannot replicate this on 1.18.2. (made sure to set `keep-spawn-loaded`). A new issue can be opened if someone can still replicate this.
