### ISSUE TITLE
Problem with minecraft server startup.

### ISSUE THREAD

**Issue by EnderEclipz** [PaperMC/Paper#5079]
Ive been getting this for the past hour and the shockbyte support are currently offline lol. Sorry for the massive line of code...

https://paste.shockbyte.com/ufatedubecosukajurux  -  So this is what happened. I have no idea what happened except for the fact that I think something isn't loading properly.

This is the biggest error that comes up.

`18.01 02:42:13 [Server] WARN java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2586 > 2584
18.01 02:42:13 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:67)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:114)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38)
18.01 02:42:13 [Server] WARN java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2586 > 2584
18.01 02:42:13 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:67)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:114)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38)
18.01 02:42:13 [Server] WARN java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2586 > 2584
18.01 02:42:13 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:67)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:114)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38)
18.01 02:42:13 [Server] WARN java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2586 > 2584
18.01 02:42:13 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:67)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:114)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38)
18.01 02:42:13 [Server] WARN java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2586 > 2584
18.01 02:42:13 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:67)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:114)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38)
18.01 02:42:13 [Server] WARN java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2586 > 2584
18.01 02:42:13 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:67)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:114)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38)
18.01 02:42:13 [Server] WARN java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2586 > 2584
18.01 02:42:13 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:67)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:114)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38)
18.01 02:42:13 [Server] WARN java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2586 > 2584
18.01 02:42:13 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:67)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:114)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105)
18.01 02:42:13 [Server] WARN at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38)`

Just before the log ends it says this:
`18.01 02:42:14 [Server] ERROR Main thread terminated by WatchDog due to hard crash`

### Plugin list:
[Quite a few but here they are]
ChatItemDisplay
ArmorStand-Limiter
BetterRTP | Random Wild Teleport
Trash Gui
AdvancedRegionMarket
⚡️ SuperiorSkyblock2 ⚡️ The best core on market! ⚡️ 1.16 Support!
HelpOP
Jobs Reborn
CombatLogX
CoreProtect
VotingPlugin
ᵀᴼᴾ「GoldenCrates」▸ Advanced custom crates! [1.14 - 1.16]
AuctionMaster [1.8.8 - 1.16.4]
[PWarp] PlayerWarps! |GUI|EASY SET-UP|Player Warps|
Chat Manager [1.7 ~ 1.16] - With 30+ Features and 40+ Commands!
ᴳᴼᴼᴰ「SunLight」▸ Server Management Plugin / Essentials [1.14 - 1.16]
LockettePro - For 1.14/1.15/1.16
AuctionHouse
WorldBorder 1.15+
Simple Rename
Vault
FunQuiz
SpaceSellWands | Essentials worth | ShopGuiPlus Support | Multipliers | Uses per wand
NuVotifier
DiscordSRV
PlaceholderAPI
McMMO
CMI
Lands
AlonsoTags Pro
NBT API
DeluxeChat
InvHistory

### Actions to reproduce (if known):
Unknown

### Paper version:
I know it says not to have "Latest" but I cannot get onto the server as it won't start.
The only thing I can think of that would relate to this would be:
PaperMC 1.16.4 Latest (Build #416)

**Comment by katekerllenevich** [comment]
You can't downgrade from 1.16.5 to 1.16.4.

**Comment by electronicboy** [comment]
`Server attempted to load chunk saved with newer version of minecraft! 2586 > 2584`
