### ISSUE TITLE
Server doesnt responding and crashes

### ISSUE THREAD

**Issue by CubergDev** [PaperMC/Paper#5084]
### Link/paste of stack trace

    https://pastebin.com/Hs77tKiE
### Plugin list:
Advanced Teleport
AuthMe
Chunky
Clans
Clearlag
Coreprotect
DiscordSRV
EssentialsX
Holographic Displays
LuckPerms
Negativity
PowerRanks
Protocollib
SAML
SkQuery
Skript
SuperVanish
Vault
ViaBackwards
ViaVersion
VillagerOptimiser
WarpGui
WorldEdit
WorldGuard
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper version:
This server is running Paper version git-Paper-434 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 [09:05:38 INFO]: Previous version: git-Paper-416 (MC: 1.16.4)

**Comment by Chew** [comment]
> --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-434 (MC: 1.16.5) ---

You're just receiving a lot of lag. Hop on [Discord](https://discord.gg/papermc) if you want to help diagnosing it, but we need timings.
