### ISSUE TITLE
Broken YourKit Links

### ISSUE THREAD

**Issue by TheKodeToad** [PaperMC/Paper#5091]
YourKit Java and .NET profiler links are broken in README.md.
They should be replaced like so:
https://www.yourkit.com/java/profiler/index.jsp -> https://www.yourkit.com/java/profiler
https://www.yourkit.com/.net/profiler/index.jsp -> https://www.yourkit.com/.net/profiler
I didn't use a template because none of them were suitable for this issue.

**Comment by MiniDigger** [comment]
good find, thanks
