### ISSUE TITLE
Plugin (NMS) compilation issue: bad RuntimeInvisibleParameterAnnotations attribute: PlayerInfoData

### ISSUE THREAD

**Issue by Trigary** [PaperMC/Paper#5096]
### What behaviour is expected:
My compilation to succeed.

### What behaviour is observed:
My compilations (`mvn clean package`, `gradle clean fatJar`, etc) fail with the following error message:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project paper-plugin: Compilation failure
[ERROR] /mnt/c/Users/sarko/Desktop/Programming/PaperPlugin/src/main/java/hu/trigary/paperplugin/PaperPlugin.java:[16,40] cannot access net.minecraft.server.v1_16_R3.PacketPlayOutPlayerInfo.PlayerInfoData
[ERROR]   bad class file: /home/user/.m2/repository/com/destroystokyo/paper/paper/1.16.5-R0.1-SNAPSHOT/paper-1.16.5-R0.1-SNAPSHOT.jar(/net/minecraft/server/v1_16_R3/PacketPlayOutPlayerInfo$PlayerInfoData.class)
[ERROR]     bad RuntimeInvisibleParameterAnnotations attribute: PlayerInfoData(com.mojang.authlib.GameProfile,int,net.minecraft.server.v1_16_R3.EnumGamemode,net.minecraft.server.v1_16_R3.IChatBaseComponent)
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```
2 different people reproduced this on 3 different machines using 3 different JDK versions and 2 different build systems.

<details><summary>Full build log</summary>

```
user@TRIG-LT:~/Programming/PaperPlugin$ mvn clean package
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< hu.trigary:paper-plugin >-----------------------
[INFO] Building paper-plugin 1.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from spigotmc-public: https://hub.spigotmc.org/nexus/content/groups/public/com/destroystokyo/paper/paper-parent/dev-SNAPSHOT/maven-metadata.xml
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ paper-plugin ---
[INFO] Deleting /mnt/c/Users/sarko/Desktop/Programming/PaperPlugin/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ paper-plugin ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ paper-plugin ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /mnt/c/Users/sarko/Desktop/Programming/PaperPlugin/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /mnt/c/Users/sarko/Desktop/Programming/PaperPlugin/src/main/java/hu/trigary/paperplugin/PaperPlugin.java:[8,40] cannot access net.minecraft.server.v1_16_R3.PacketPlayOutPlayerInfo.PlayerInfoData
  bad class file: /home/user/.m2/repository/com/destroystokyo/paper/paper/1.16.5-R0.1-SNAPSHOT/paper-1.16.5-R0.1-SNAPSHOT.jar(/net/minecraft/server/v1_16_R3/PacketPlayOutPlayerInfo$PlayerInfoData.class)
    bad RuntimeInvisibleParameterAnnotations attribute: PlayerInfoData(com.mojang.authlib.GameProfile,int,net.minecraft.server.v1_16_R3.EnumGamemode,net.minecraft.server.v1_16_R3.IChatBaseComponent)
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.846 s
[INFO] Finished at: 2021-01-22T00:14:50+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project paper-plugin: Compilation failure
[ERROR] /mnt/c/Users/sarko/Desktop/Programming/PaperPlugin/src/main/java/hu/trigary/paperplugin/PaperPlugin.java:[8,40] cannot access net.minecraft.server.v1_16_R3.PacketPlayOutPlayerInfo.PlayerInfoData
[ERROR]   bad class file: /home/user/.m2/repository/com/destroystokyo/paper/paper/1.16.5-R0.1-SNAPSHOT/paper-1.16.5-R0.1-SNAPSHOT.jar(/net/minecraft/server/v1_16_R3/PacketPlayOutPlayerInfo$PlayerInfoData.class)
[ERROR]     bad RuntimeInvisibleParameterAnnotations attribute: PlayerInfoData(com.mojang.authlib.GameProfile,int,net.minecraft.server.v1_16_R3.EnumGamemode,net.minecraft.server.v1_16_R3.IChatBaseComponent)
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

</details>

### Steps/models to reproduce:
<details><summary>pom.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<groupId>hu.trigary</groupId>
	<artifactId>paper-plugin</artifactId>
	<version>1.0</version>
	
	<properties>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
	</properties>
	
	<dependencies>
		<dependency>
			<groupId>com.destroystokyo.paper</groupId>
			<artifactId>paper</artifactId>
			<version>1.16.5-R0.1-SNAPSHOT</version>
		</dependency>
	</dependencies>
</project>
```

</details>
<details><summary>PaperPlugin.java</summary>

```java
package hu.trigary.paperplugin;
 
import net.minecraft.server.v1_16_R3.PacketPlayOutPlayerInfo;
import org.bukkit.plugin.java.JavaPlugin;
 
public class PaperPlugin extends JavaPlugin {
	private void test(PacketPlayOutPlayerInfo packet) {
		PacketPlayOutPlayerInfo.PlayerInfoData data = null;
	}
}
```

</details>

### Plugin list:
Not applicable / just my own.

### Paper version:
```
version
[23:00:57 INFO]: This server is running Paper version git-Paper-438 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[23:00:57 INFO]: Checking version, please wait...
[23:00:58 INFO]: Previous version: git-Paper-428 (MC: 1.16.5)
[23:00:58 INFO]: You are running the latest version
```
That's the paperclip jar I got the error from. I also compiled paper from sources on a different machine, got the same results. I have tried it with Paper 1.16.4 somewhere around #~270 as well, the same error occurred, so this error is not new, it has been around for a while.

### Anything else:
The Minecraft community has come across this error a few times already:
https://github.com/SpongePowered/SpongeVanilla/issues/272
https://github.com/MinecraftForge/ForgeGradle/issues/472

[Notable exempt from the 2nd link: (LexManos)](https://github.com/MinecraftForge/ForgeGradle/issues/472#issuecomment-364800112)
> We have identified the issue. ProGuard, the Obfuscator that Mojang uses is breaking the annotation attribute for some reason we can't seem to find the justification for.

**Comment by electronicboy** [comment]
There is very little we can do about this at our level, the issue is that these class files are just blatently wrong, our only real way to resolve these issues without having to mess with the entire build chain (which is somewhat not viable and worth it given current plans) would be to forcefully decompile these classes in paper, the only real fix here is to run a pass with some tool capable of repairing these discrepenencies, which risks causing issues with the decompile/patch process

best you can do in the meantime is to use reflection to call the class vs having to compile against it

**Comment by yannicklamprecht** [comment]
Had a similar issue with reflection some months ago. Making the inner class static solved the issue. This is probably just removing the symptoms, but the real cause doesn't fix it.

**Comment by Trigary** [comment]
While all information is welcome, modifying source code is not an option in this scenario, or I'm not following you.

This issue can be fixed by decompiling the `PacketPlayOutPlayerInfo` class via the decompile tool (since then it will be recompiled as part of Paper-Server). I have tested that change, it didn't break anything. But PaperMC, unfortunately, doesn't wish to increase their maintenance burden just to support some random NMS class that is rarely used (which makes sense to me). But this is still an option for forks of Paper.

**Comment by yannicklamprecht** [comment]
> While all information is welcome, modifying source code is not an option in this scenario, or I'm not following you.
> 
> This issue can be fixed by decompiling the `PacketPlayOutPlayerInfo` class via the decompile tool (since then it will be recompiled as part of Paper-Server). I have tested that change, it didn't break anything. But PaperMC, unfortunately, doesn't wish to increase their maintenance burden just to support some random NMS class that is rarely used (which makes sense to me). But this is still an option for forks of Paper.

Yes, I didn't read the answers in Discord so half of the context was missing.

Yes I did that in my fork and added support for some often used packets as an API. That is not accepted by Paper because of "Stuff with packets are not viable for an API". It's just a couple of patches extending API no experimental performance optimization.

**Comment by MiniDigger** [comment]
>  But this is still an option for forks of Paper.
yes, but actually, this is something the tooling of spigot should fix. they make us use their (shitty) tooling (for now, anyways), and thats the location where it should be fixed.

**Comment by yannicklamprecht** [comment]
> >  But this is still an option for forks of Paper.
> yes, but actually, this is something the tooling of spigot should fix. they make us use their (shitty) tooling (for now, anyways), and thats the location where it should be fixed.

The other solution is the hardbreak, right?

**Comment by MiniDigger** [comment]
kinda, yes. we are stuck with their tooling, as long as we need to actually build upstream patches and stuff. this is offtopic tho
