### ISSUE TITLE
Bandwith usage request for analisis 

### ISSUE THREAD

**Issue by ricsal1** [PaperMC/Paper#5099]
###  Timings or Profile link:
![Capturar1](https://user-images.githubusercontent.com/25226624/105505450-ddd2fb80-5cc0-11eb-804b-cd29c6384a4f.PNG)

### Description of issue:
Hello,
Have been hosting a server and noticing around 1Mb/s for each player connected.
Since I have set the network-compression-threshold set to 256 , I was getting most of this data would be compressed if the packsize is bigger then 256.

From the fast analysis I made, with wireshark, the data is sent in tiny packets, so I rarely see a packet bigger then 36 bytes (attention there are no requests from client in the middle).

Don't know how the data is sent, if the flow is controlled by paper of from the original binary from minecraft, but looks to me there is margin for optimization if instead of all this packets, we manage to send 512 or even 256 (for lower latency) bytes packets and with compression.

I can help testing this with you.

### Plugin list:
DeadChest-4.3.0, DragonDropElytra-1.13_1.0.3, OpenInv, PlayerHeads, UnlimitedAnvil-1.0.6-R

### bukkit.yml, spigot.yml, paper.yml, server.properties
network-compression-threshold=256

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper version:
paper-1.16.5-439.jar

**Comment by aikar** [comment]
this is vanilla minecraft and is ultimately not viable, and would only make latency worse. You're ultimately asking to batch packets together, which that 'batching window' will then end up adding a constant time delay to latency for packets.

But any optimization here has to be suggested to mojang, to batch small updates together as a bulk packet for entity tracker for example. Nothing paper can do.

**Comment by ricsal1** [comment]
Thanks for your feedback
