### ISSUE TITLE
So confused... Plugin issues with paper?

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#510]
I Must of been playing around with my plugins for about 4 hours straight now... I Can't for the LIFE of my figure out what's going on.. All of my plugins work on spigot. As soon as i try it on paper they just don't work. 

Here's my plugin pack:
http://www.mediafire.com/file/t6gcfy156spd4f1/plugins.zip

If you remove lwc a lot of them start working.. But why do they even break.. they all work fine on spigot.. I'm so confused and dont understand why they work on spigot and not paper. I'm going to bed. I Really don't know what to do from this point. There must be some sort of bug with paper? 

Plugins loaded on PaperSpigot (latest)
![c2184db0328aff92fa755c2c99e6a81d](https://cloud.githubusercontent.com/assets/16514150/20612073/bb7d98fe-b2ad-11e6-98f5-7eb050900af7.png)
Plugins loadded on Spigot (latest, tried a few they all worked.)
![a6ecfebba2df77861405bb4b816a1c02](https://cloud.githubusercontent.com/assets/16514150/20612089/ebad3b6a-b2ad-11e6-87c0-6324859c3de6.png)

Startup log spigot: 
http://pastebin.com/zmmLQwNS
Startup log Paper:
http://pastebin.com/exNDJG6C

**Comment by zachbr** [comment]
Pretty sure this is directly related to your previous issue of us not allowing plugins to continue loading if they throw an exception in onEnable. I don't see much reason to revisit that decision at this time.

The majority of these plugins should have updates available to fix these issues. As far as I can see, there really isn't anything here paper specific about them, it's just we aren't allowing them to continue loading after failing once already.

If an update isn't available to resolve one of these issues, it should be reported to the author/s of the plugins, or someone capable of resolving them appropriately.

**Comment by aikar** [comment]
As spigot stated, they updated the SQLite Driver.

The new location is:

>>> unzip -l spigot-1.11.jar | grep NativeDB
     6213  2016-11-24 22:36   org/sqlite/core/NativeDB.class

There is nothing paper can do to fix that issue. The plugin devs HAVE to update to the new version.

**Comment by jordanwilliams1** [comment]
@aikar But If I remove the LWC plugin alot of them starting working again.. Coreprotect has been updated to 1.11 and doesn't look like there going to update it again cause it works 100% fine on spigot... but doesn't work on paper with my plugin setup?
