### ISSUE TITLE
Chunks dont load if player is constantly teleported

### ISSUE THREAD

**Issue by Ultrajungleboy** [PaperMC/Paper#5102]
### What behaviour is expected:
Obviously chunks SHOULD load

### What behaviour is observed:

no chunks loading when the player is teleported once every tick

### Steps/models to reproduce:
you can use the cpcamerastudio plugin to reproduce this, it uses some deprecated methods that ive since updated but they didnt change whether or not chunks would load
heres a video of it occuring when a normal player with latency goes through it:
https://streamable.com/sme34o
heres a video of it occuring when i use localhost:
https://streamable.com/x6hceo

Also the best way to test this would be to initially teleport yourself to an area that your client doesnt have loaded yet and then keep trying to teleport yourself

### Plugin list:
I've tested this exact same issue on a fresh server with no plugins

### Paper version:
git-Paper-438 MC 1.16.5 Implementing API version 1.16.5-R0.1-SNAPSHOT

### Anything else:
--when i don't teleport them for 1-2 ticks sometimes the client can recognize that they are no longer being teleported and will load some chunks

--TeleportAsync and teleport both produce the same results

--ive force loaded and loaded chunks where the player is every tick and it still produces the same result

--ive created a debug to see if the server recognizes that the chunks are loading and it returns true

--I've never personally worked with packets but I'm assuming this is a packet issue most likely?

--This is a VERY specific problem and there are some ways to get around this however I thought I'd share it :)

--I've had my friends bug test this as well and this is how i originally found out about the problem since ive just been using localhost

**Comment by radiant-ai** [comment]
Well, I can confirm this, I have a similar plugin that teleports players every tick and chunks indeed do not load. But I thought that it is quite an expected behaviour.

**Comment by Ultrajungleboy** [comment]
> Well, I can confirm this, I have a similar plugin that teleports players every tick and chunks indeed do not load. But I thought that it is quite an expected behaviour.

How do you get around it with your plugin?

And why would that be an expected behavior? I mean yes it's a very specific issue that won't bother a lot of players but I mean is there a reason that the chunks shouldn't load, because the server is loading them it's just the client can't see them/ isn't receiving them or whatever.

**Comment by Ultrajungleboy** [comment]
This issue was just fixed on the fork tuinity in the dev branch https://github.com/Spottedleaf/Tuinity/tree/dev/playerchunkloading

**Comment by e-im** [comment]
No longer reproducible on 1.17.1 post tuinity merge.
