### ISSUE TITLE
There is no setting to let Wither and Zombie_village count in total mobs limit.

### ISSUE THREAD

**Issue by sayl6** [PaperMC/Paper#5105]
### What behaviour is expected:
Wither and Zombie_village should count in total mobs limit

Original features
### What behaviour is observed:
___What you actually saw___

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Chew** [comment]
Missing critical template sections: Plugin list and /version output. Please confirm this happens on the latest build with no plugins.

**Comment by Chew** [comment]
Nevermind, this is a feature request. Wrong template I guess?

**Comment by sayl6** [comment]
I think my description is not clear enough.
Minecraft mob spawn limit is 70/player,“https://minecraft.gamepedia.com/Spawn#Monsters”
Wither and Zombie_villager  in vanilla is calculated into this limit.But paper not.
![QQ图片20210205111335](https://user-images.githubusercontent.com/52915510/106984805-361afa80-67a3-11eb-9409-4bcb48bc1582.png)

**Comment by electronicboy** [comment]
paper only counts naturally spawned mobs by default, this looks like it can be reverted to the vanilla behavior by setting the option in paper.yml to count all mobs?

**Comment by sayl6** [comment]
Oh.Thank you!!
