### ISSUE TITLE
When you bone meal bamboo the people near you gets kicked (including you)_

### ISSUE THREAD

**Issue by Win-ss** [PaperMC/Paper#5106]
### What behaviour is expected: the bamboo to grow
___What you expected to see___

### What behaviour is observed:
___What you actually saw___
i get the kick

### Steps/models to reproduce:
get bamboo thats not grown like 10 x10? thats what i did i was building a bamboo farm  when you are on top of the bamboo then bone meal it boom everyone in a small radius of you gets kicked by "Packets error"

### Plugin list:
antibotdeluxe clearlag cmdspy consolespamfix coreprotect discordsrv essentialsX holograms launchpad litebans loginsecurity luckperms multiverse portals and core  plot squared plugman and protocol support skin restorer staffchat supervote super vanish TAB vault and world gaurd.

### Paper version:
latest.
### Anything else: nothing

**Comment by electronicboy** [comment]
"latest" is ***NOT*** a version, please provide the full output of the /version command
Also, replicate without plugins, failing that, open a new issue providing the full info, and a copy of the full packet error.
