### ISSUE TITLE
Server Lags after version Upgrade to 1.16.5

### ISSUE THREAD

**Issue by derech1e** [PaperMC/Paper#5107]
###  Timings or Profile link:
https://timings.aikar.co/?id=f39ef6cfd6114590a3c3cd3dfa0d9356

### Description of issue:
After I upgraded the Paperspigot version to 1.16.5, the performance got worse. I had no issues on 1.16.4. I loaded the same world with the newer version and after that, it lagged unnormal.

### Plugin list:
GSit, Worldedit

### bukkit.yml, spigot.yml, paper.yml, server.properties
paper.yml: https://pastebin.com/rqSWQrGC
server.properties: https://pastebin.com/mFqY3nXG
spigot.yml: https://pastebin.com/aHmWmFwg
bukkit.yml: https://pastebin.com/rrCp8rnw

### Paper version:
git-Paper-443 (MC:1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Proximyst** [comment]
Not PaperSpigot, and not due to 1.16.5. Come to `#paper-help` on our Discord or on EsperNet IRC to receive help.
