### ISSUE TITLE
Programmable dragon egg block spawning

### ISSUE THREAD

**Issue by Trigary** [PaperMC/Paper#5110]
**Is your feature request related to a problem? Please describe.**
There is little control plugins (and server owners) have over whether the dragon egg should or shouldn't appear when the ender dragon is defeated.

**Describe the solution you'd like**
Addition of a `DragonEggAppearEvent`. (Better name ideas are welcome.) Whether that event is canceled or not determines whether the egg should appear or not. The event should have access to the `DragonBattle` instance, or, if that's not possible for whatever reason, at least the `previouslyKilled` flag.

**Describe alternatives you've considered**
 - Plugins might be able to listen to dragon's death using already existing events, somehow get the trophy position (it's not currently exposed in the API, but getting it is probably possible nevertheless), and set the block at that position manually. But this process is sub ideal at best.
 - Percentage based control through configuration files: the dragon egg should have a configurable chance to appear. (This is the original request of `@maverick#4689`)

If feedback is positive, I plan on making and PRing the necessary changes.

**Comment by aurorasmiles** [comment]
Yes please! We currently scan for the portal, and start a repeating task once the dragon is killed to remove the egg, which is really annoying. I'd love that feature
