### ISSUE TITLE
Inventory Interface Bug

### ISSUE THREAD

**Issue by SirPenguini** [PaperMC/Paper#5111]
### What behaviour is expected:
___What you expected to see___

I have a plugin called UpgradeableHoppers, however the hoppers do not work (act as normal hoppers).

### What behaviour is observed:
___What you actually saw___

Normal hopper behaviour (and console errors).

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Simply use a hopper from the plugin.

### Plugin list:
___A list of your plugins___

Upgardeable Hoppers.

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

Paper version git-Paper-370 (MC 1.15.2)

### Anything else:
___Anything else you think may help us resolve the problem___

https://pastebin.com/Z8KmijC6

![image](https://user-images.githubusercontent.com/77974523/105714452-4534b980-5f14-11eb-8780-c64bb6311a3e.png)

**Comment by electronicboy** [comment]
1) 1.15.2 is no longer supported
2) That method was added only a few months ago, so that's not gonna be in 1.15.2
