### ISSUE TITLE
Droped Items disappearing on death

### ISSUE THREAD

**Issue by BoomEaro** [PaperMC/Paper#5114]
### What behaviour is expected:
Remove items after 5 minutes (or as configured in spigot.yml)

### What behaviour is observed:
Items are removed instantly, only experience remains.

### Steps/models to reproduce:
Floating bug, I could not repeat it at the right time, but players sometimes contact me with information that after their death only experience remains.

### Plugin list:
CrazyDebuger, ChestCommands, Essentials, EssentialsChat, EssentialsSpawn, HolographicDisplays, LuckPerms, OpenInv, ProtocolLib, Vault, WorldEdit
(It doesn't seem like any of the plugins can affect the item drop.)

### Paper version:
[01:43:43 INFO]: This server is running Paper version git-Paper-439 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[01:43:43 INFO]: Previous version: git-Paper-389 (MC: 1.16.4)

### Anything else:
It looks like the issue is related to https://bugs.mojang.com/browse/MC-117783

I have a plugin that keeps a log of the deaths of players and their items that should have dropped to the ground. When teleporting to the location of the problem player's death, I expect to see the player's items, but I only see the experience.

**Comment by Proximyst** [comment]
Sounds more like unloaded experience orbs do not despawn after 5 minutes, whereas unloaded items do.

**Comment by e-im** [comment]
Unloaded items will not despawn. A lot of things can cause this, with a few common causes being the items going into the floor/hiding behind neighbouring blocks. There isn't all that much to be done here -- this issue has been reported essentially since the beginning of Minecraft and isn't something that can be reproduced reliably at all.
