### ISSUE TITLE
Create MaterialSetTags without legacy materials

### ISSUE THREAD

**Issue by kezz** [PaperMC/Paper#5118]
**Is your feature request related to a problem? Please describe.**
Creating a `MaterialSetTag` with the predicate constructor also includes legacy materials even when they aren't needed. This is odd because initialising using a list of materials by default removes legacy materials from the predicate.

**Describe the solution you'd like**
An additional constructor with a boolean to determine if legacy materials should be included. Also, this might be a breaking change but it might be worth making the non-boolean constructors default to ignoring legacy materials.

**Describe alternatives you've considered**
You cannot create a `MaterialSetTag` with a predicate if you don't want legacy materials in the tag. The only alternative is to construct a list of items and use the other constructor.

EDIT: Happy to do the code for this myself, would just like to know if such a feature would be acceptable or if there's some other option.

**Comment by yannicklamprecht** [comment]
I'm against this. Just use your List. Adding new legacy api features is not what I want for that project. Instead getting rid of all legacy shit.

**Comment by kezz** [comment]
> I'm against this. Just use your List. Adding new legacy api features is not what I want for that project. Instead getting rid of all legacy shit.

I totally get this, however, if we want tags to *not* use legacy api features, wouldn't it be better to remove them by default? I can't use a list in this use case as I'm not actually making a simple list of items - I would have to essentially mimic the code inside the class but with legacy materials removed in order to emulate the functionality I can get when I use the list constructor.

**Comment by yannicklamprecht** [comment]
> > I'm against this. Just use your List. Adding new legacy api features is not what I want for that project. Instead getting rid of all legacy shit.
> 
> I totally get this, however, if we want tags to _not_ use legacy api features, wouldn't it be better to remove them by default? I can't use a list in this use case as I'm not actually making a simple list of items - I would have to essentially mimic the code inside the class but with legacy materials removed in order to emulate the functionality I can get when I use the list constructor.

If I get that right you want create a list without legacy materials using the predicate constructor?

`new MaterialSetTag(NamespacedKey.minecraft("your_list"), Predicate.not(Material::isLegacy).and(Predicate.not(Material::isAir)));`
You can concat predicates so I don't see the need here for an additional constructor.

Please show your special use case where it doesn't work out for you.

**Comment by kezz** [comment]
I guess the root problem I have is the API isn't consistent. If we want to exclude legacy materials from `MaterialSetTag` then why don't we do that for all of the constructors? Could we not apply the same logic as this:

> `new MaterialSetTag(NamespacedKey.minecraft("your_list"), Predicate.not(Material::isLegacy).and(Predicate.not(Material::isAir)));`
> You can concat predicates so I don't see the need here for an additional constructor.

but with `MaterialSetTag`s where legacy materials *do* want to be included?

Regardless, all of this functionality should be included in Javadocs - I can make a PR for this at some point if needs be.

**Comment by Machine-Maker** [comment]
Yeah, I agree with @kezz. It should've been at least documented that the MaterialSetTag(NamespacedKey, Predicate<Material>) constructor also filter's out materials in addition to the ones provided in the filter. Probably worth doing that pr kezz.
