### ISSUE TITLE
FallDamange

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5120]
Hi, I found a bug. Method setNoDamageTicks(); not work to fall damage. Please fix this bug. A version of a paper is 1.16.5 #443.
This plugin coded in Spigot API

Thanks

**Comment by electronicboy** [comment]
1.16.4 is no longer supported, if there is a bug in .5, it would be fixed
there

**Comment by ghost** [comment]
Pardon, 1.16.5 #Edited

**Comment by Chew** [comment]
Missing template. Try again. Be sure to fill it out or we can't help

**Comment by Proximyst** [comment]
Confirmed with:

```kotlin
class NoDamageTicksCommand : BaseCommand() {
    override fun register(manager: PaperCommandManager<CommandSender>) {
        manager.command(manager.commandBuilder("nodmgticks")
            .argument(IntegerArgument.of("ticks"))
            .sender<Player>()
            .handler {
                val ticks: Int = it["ticks"]
                it.sender.maximumNoDamageTicks = ticks
                it.sender.noDamageTicks = ticks
            })
    }
}
```

**Comment by Trigary** [comment]
Everything is working fine as far as I can tell. What exactly is the bug that you two observed? What are the exact reproduction steps?

What I have tried:
 - Set max no damage ticks and no damage ticks and jump from a high place: no damage taken
 - Set max no damage ticks and no damage ticks, wait for them to run out and jump from a high place: damage taken
 - Set max no damage ticks and no damage ticks, wait for them to run out, jump from a high place (take damage) and then jump again before the no damage ticks run out: no damage taken

Is this not how it should work?

**Comment by Proximyst** [comment]
The first step there is what reproduced it for me. Are you sure you fell far enough?

**Comment by Trigary** [comment]
Yes
![image](https://user-images.githubusercontent.com/16213127/106391596-82a2b680-63ee-11eb-9f7e-06273bb206f4.png)

**Comment by Proximyst** [comment]
This should not take damage:

https://owo.whats-th.is/4yCg6MM.mp4

**Comment by Trigary** [comment]
I think that's how it's supposed to work and I don't think this is fall damage specific.

No damage ticks are no longer strictly "take no damage during this period", it's more like "ignore smaller damages; for higher damages apply the difference". See: https://minecraft.gamepedia.com/Damage#Immunity

We are missing vanilla reproduction steps, compared to which we could prove that the effects observed on Paper are incorrect.

**Comment by Proximyst** [comment]
I see, thank you! In that case I'll close the issue with cannot reproduce.
