### ISSUE TITLE
Force op hack possible to gain /op access somehow

### ISSUE THREAD

**Issue by BurkenDev** [PaperMC/Paper#5122]
### What behaviour is expected:
Authlib rejecting private IP range on an non private IP server.

### What behaviour is observed:
Authlib gets spoofed 192.168 ip when a hacker using some new kind of forceop mod thus allowing the client to gain access to accounts used for OP on the server without accually having to use those accounts to login.
Note: Server is in online mode and the server does not have or route 192.168 ip ranges. Nor does it have any ports open other than its bungeecord proxy on localhost. The modded client can execute any command.
This is similar to the old forceop hack a year ago but not quite the same. (that one required open ports). This one is fooling the auth lib that the user comes from 192.168. ip when in reality it's another ip (displayed by the proxy). Paper only reports 192.168 ip.

### Steps/models to reproduce:
Cannot reproduce since have no access to the client force op mod.

### Plugin list:
N/A

### Paper version:
445

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Proximyst** [comment]
Not a Paper problem. Set up your proxy correctly (`bungeecord: true` in `spigot.yml` and enable `ip_forwarding` in BungeeCord's `config.yml`) and come to our Discord if the issue persists. A local IP doesn't let you magically gain operator status nonetheless.

**Comment by electronicboy** [comment]
ip forwarding does not protect from spoofing, either configure firewall or use a plugin like bungeeguard
