### ISSUE TITLE
EntityPlayer Sound/Particles Cancellable Events

### ISSUE THREAD

**Issue by Splitrox** [PaperMC/Paper#5125]
Hi, I'm going to ask you something that I think is positive for a lot of people.
Today I bring one of the things that is very annoying to be creating a fork just for something like that.
I intend to change the entityhuman code so that in my plugin I can know if the player spawned a particle (Ex: SWEEP_ATTACK) or sounds (Ex:
ENTITY_PLAYER_ATTACK_STRONG, ENTITY_PLAYER_ATTACK_NODAMAGE, ENTITY_PLAYER_ATTACK_WEAK)
Unfortunately I can't do it any other way because the sounds and particles don't keep the owner's information, which in some cases is natural but doesn't allow me to reach my goal.
I was going to ask you to consider adding some form that could override the methods of the EntityHuman or EntityPlayer classes.
Another way I was thinking about choosing if I had to fork was to add new bukkits events where they exist where the sounds / particles of the players were called, in this case if I wanted from the event I could cancel the particle (My final goal is not only to be able to cancel the particle but to not show it to all players)

**Comment by Proximyst** [comment]
I am 100% unable to figure out what you want here. Do you want us to make NMS API (in which case, no)? Do you want us to add more API for attacks, particles, players, humans, or sounds? Have you already done so? Is this an excerpt from your diary? What's going on?

**Comment by OpticFusion1** [comment]
Going off what's said
1) I guess SoundPlayEvent & ParticleSpawnEvent events with both being cancel-able
SoundPlayEvent would allow you to get/set the sound that's playing, as well as what caused the sound, and set what players hear it
ParticleSpawnEvent would allow you to get/set the particle that's spawned, as well as what caused it to spawn, and set what players see it

2) Same as 1 except you get/set this information from the Sound/Particle its self, i think...

**Comment by Splitrox** [comment]
Sorry if I was not clear enough but the idea that OpticFusion1 passed is practically that, in this case there is no way to be able to filter the particles / sounds that the player makes without being from a fork and I think you could allow that. An example I gave was from events, in this case when the player makes a sound this sound could be canceled from a bukkit event as the same thing for the particles, it would help me a lot (avoided creating a fork) as I believe it allowed content creators to change the sound / cancel the sound, etc ... 
The problem here is that there is no way for me to know that the sound was made by a player (because that way I would do some way to change / remove it when sending the package to the customer)

**Comment by electronicboy** [comment]
We're not creating stupidly tight API for one users specific use-case, such intents is highly flawed and not gonna happen.
If you can propose/design an API which covers more aspects, this could be considered, but, providing hooks for a singular persons use-case is not something we generally consider, a much wider API would be needed here for this to actually be suitable API
