### ISSUE TITLE
/mspt timings always show high values after server startup

### ISSUE THREAD

**Issue by jaylawl** [PaperMC/Paper#5126]
**Is your feature request related to a problem? Please describe.**
Whenever you restart a server, the /mspt command shows high results at the very least in the 1m time frame. Of course this is due to the server just booting up.

**Describe the solution you'd like**
Automatically reset the MSPT timings (as is done with TPS) after the server startup phase is completed.

**Comment by electronicboy** [comment]
This is heavily due to JIT warmup which is not something we can even begin to measure to determine once that phase has really past

**Comment by jaylawl** [comment]
> 
> 
> This is heavily due to JIT warmup which is not something we can even begin to measure to determine once that phase has really past

I'm not sure i understand. TPS are also reset - that already exists, why can't the MSPT be reset too on the same event? It's just a collection of primitives after all.

**Comment by electronicboy** [comment]
TPS is never reset, it just only starts being touched once the server starts ticking, same for the mspt, it's only measured when the server is actually ticking; These times are expected to be higher than normal on startup as the JVM is still warming up, methods called often in the tick loop are still being compiled by the JVM into optimized code

**Comment by jaylawl** [comment]
In that case i misunderstood how TPS work, but i understand now. Appreciated!
