### ISSUE TITLE
Can't unban old players

### ISSUE THREAD

**Issue by akdukaan** [PaperMC/Paper#5129]
### What behaviour is expected:
`/minecraft:pardon x` should unban them and tell me `x was unbanned`.

### What behaviour is observed:
I am told `That player does not exist`. The player also continues to remain banned. 

### Steps/models to reproduce:
1. Stop the server.
2. Add some real player other than yourself to the banned-players.json.
3. Remove the player from the usercache.json if they exist in there.
4. Start the server back up.
5. Use the command `/minecraft:pardon x` to try to unban them.

### Plugin list:
Luckperms, Vault

### Paper version:
Paper version git-Paper-449 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Anything else:
Im not entirely sure how the minecraft:pardon command works but if it works the way I think it does, a potential solution could be to make the unban command check if the player exists in banned-players.json after seeing that the player doesnt exist in usercache.json.

**Comment by MrIvanPlays** [comment]
looking at the code and it looks like ArgumentProfile checks the user cache and if it's not present it blocks the command execution no matter what. 
a workaround is to use a string argument and manually match the players without checking the user cache and only checking the ban list.
another workaround is to rewrite the command to use bukkit's command system which is not the preferable option here.

**Comment by NoahvdAa** [comment]
I can no longer reproduce this. I emptied usercache.json and even changed the username in banned-players.json, but it would still unban the player. Am I doing something wrong here or has this been fixed?

**Comment by akdukaan** [comment]
I too am unable to reproduce it. I think it's been resolved.

**Comment by lynxplay** [comment]
Yea seems like the profile cache now correctly performs a lookup when a user is requested that does not exist in it yet.
