### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by aril3721** [PaperMC/Paper#5134]
###  Timings or Profile link:
https://timings.aikar.co/?id=c9ec319de3f04510808f32237f4bbc0c

### Description of issue:
pls help me. i dont know why on every 30s - 1m its soo lagging and make my server tps down on 7 - 8 tps i dont know how to fix it 

Sorry If my english soo bad

### Plugin list:
![image](https://user-images.githubusercontent.com/67541360/106351494-32a0f280-630f-11eb-874f-d771f21e25a2.png)

### bukkit.yml, spigot.yml, paper.yml, server.properties
Bukkit: https://pastebin.com/v9kztuUZ
spigot: https://pastebin.com/gNxXhpg9
Paper: https://pastebin.com/d24E2uMQ
Propertise: https://pastebin.com/8js4UMSn

### Paper version:
![image](https://user-images.githubusercontent.com/67541360/106351840-4ea59380-6311-11eb-9c1f-38127bbeff03.png)

**Comment by MiniDigger** [comment]
for performance help, please use the discord or the forums. this is most likely caused by a bad host (are you running on aws?!) and misconfiguration (can start by properly setting up your startup flags, as timings tells you)
