### ISSUE TITLE
Attempted to place a tile entity

### ISSUE THREAD

**Issue by Shinidk** [PaperMC/Paper#5138]
Hey! I was working on my server and decided to take a look at console to fix any error before I release the server. Once I opened the console I noticed a lot of warnings (never crashed the server but I thought it was weird to have all these warnings) so i decided to open a ticket and see if this is something that can be fixed or what type of issue this is (if there is a way to fix this pls let me know) 

30.01 10:50:15 [Server] WARN com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_16_R3.TileEntitySign@24d43134) at -3725,43,275 (Block{minecraft:sand}) where there was no entity tile!
30.01 10:50:15 [Server] WARN Chunk coordinates: -3728,272
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.Chunk.setTileEntity(Chunk.java:731)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.Chunk.a(Chunk.java:703)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:678)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkRegionLoader.lambda$createLoadEntitiesConsumer$8(ChunkRegionLoader.java:315)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.Chunk.addEntities(Chunk.java:786)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$null$46(PlayerChunkMap.java:1295)
30.01 10:50:15 [Server] WARN at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
30.01 10:50:15 [Server] WARN at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
30.01 10:50:15 [Server] WARN at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$c$47(PlayerChunkMap.java:1278)
30.01 10:50:15 [Server] WARN at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
30.01 10:50:15 [Server] WARN at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
30.01 10:50:15 [Server] WARN at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkTaskQueueSorter.b(SourceFile:58)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:994)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1041)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkProviderServer.runTasks(ChunkProviderServer.java:627)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1141)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000)
30.01 10:50:15 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
30.01 10:50:15 [Server] WARN at java.lang.Thread.run(Thread.java:748)
30.01 10:50:15 [Server] INFO Removing corrupt tile entity

In the paper.yml I do have "remove-corrupt-tile-entities" set to true. This issue so far didn't cause anything to happen to my server but I am afraid it will cause world corruption? If this could be clarified to me I would appreciate it a lot!

**Comment by katekerllenevich** [comment]
What version of paper are you running?

**Comment by Shinidk** [comment]
paper-1.16.5

**Comment by katekerllenevich** [comment]
That's not a version. Send the output of /version

**Comment by Shinidk** [comment]
https://imgur.com/a/wZ7wlh7

Here is the output

**Comment by Chew** [comment]
That build is a week out of date. Where did you even get it? Download a new jar from https://papermc.io/downloads 

We also need a plugin list.

**Comment by Shinidk** [comment]
That build was provided directly from the multicraft in pebblehost, like the automatic setup

**Comment by Shinidk** [comment]
here is the plugin list: https://imgur.com/a/a6vuhKU
Sorry for all the trouble

**Comment by Proximyst** [comment]
The block was corrupted; known bug with CraftBukkit, and not generally something we can really do anything about (or we would have -- many years ago).

**Comment by Machine-Maker** [comment]
Closing as this is old. If this happens on newer versions, a new ticket should be opened.
