### ISSUE TITLE
Spawneggs id not working on 1.11

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#514]
Paper Build 933:

Problem: Spawn egg Ids no longer work and they did on 1.10 when i use the ids for spawneggs you can't spawn anything?

**Comment by Black-Hole** [comment]
All entity ids changed with 1.11, please look up the right strings.

**Comment by Fonzee9** [comment]
I can't find the ids for 1.11 for spawneggs can you help me?

**Comment by Black-Hole** [comment]
http://minecraft.gamepedia.com/1.11#General_2

**Comment by Fonzee9** [comment]
I'm sorry but i can't find the spawneggs id in that page.. for 1.11

**Comment by zachbr** [comment]
This isn't a paper issue
