### ISSUE TITLE
Keep Items Stacked in Shulker Boxes

### ISSUE THREAD

**Issue by Henry055** [PaperMC/Paper#5140]
**Is your feature request related to a problem? Please describe.**
Yes, when breaking a shulker box with force stacked items (e.g. stacked pickaxes from using `/stack`) in them they unstack when they are broken. This causes items to be lost. Here's an image to help describe the issue:

Before:
![unknown](https://user-images.githubusercontent.com/73945068/106364701-ee225080-6328-11eb-88ba-99b778de1060.png)

After:
![2021-01-30_18 19 27](https://user-images.githubusercontent.com/73945068/106364704-f24e6e00-6328-11eb-8d2f-7b12cc524233.png)

**Describe the solution you'd like**
We would like it so that there was a way to keep items stacked when shulker boxes are broken.

**Describe alternatives you've considered**
We've tried to see if it's a plugin issue with the plugin that allows us to do `/stack` (WorldGuard) however we found out that it isn't related to that at all as it also happens in vanilla.

**Comment by Proximyst** [comment]
Confirmed locally. The shulker _must_ be destroyed in survival mode.

**Comment by MrIvanPlays** [comment]
it is _technically_ not a bug since you've stacked items that are unstackable in pure vanilla

**Comment by JRoy** [comment]
> it is _technically_ not a bug since you've stacked items that are unstackable in pure vanilla

It is, vanilla shouldn't be validating itemstacks on break/place.

**Comment by Proximyst** [comment]
Escalating to high priority due to #4748. Help is appreciated.
