### ISSUE TITLE
@ commands not working

### ISSUE THREAD

**Issue by kotykd** [PaperMC/Paper#5145]
### What behaviour is expected:
___I expect to be able to do a command with another plugin (I don't really care about minecraft official commands) for example: /givemoney @ s 100 (without the space between @ and s)___

### What behaviour is observed:
___^^^ instead of what is above it just says player not found.___

### Steps/models to reproduce:
___With an economy plugin, type /givemoney @ p or @ s or something similar and then you will see what i am talking about.___

### Plugin list:
 - Carz
 -  Citizens 2
 - CoreProtect
 - EssentialsX (with only that and EssentialsX chat)
 - FastAsyncWorldEdit
 - FloodGate
 - Geysermc
 - JobsReborn
 - Luckperms
 - MyCommand
 - OpenInv
 - PlaceholderAPI
 - ProtocolLib
 - SuperVanish
 - UltimateEconomy
 - Vault
 - ViaVersion

### Paper version:
___[01.02 17:34:33] [Server] [INFO] This server is running Paper version git-Paper-189 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[01.02 17:34:33] [Server] [INFO] You are running the latest version___

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by JRoy** [comment]
Not a Paper issue, needs to be supported on a per plugin basis

**Comment by electronicboy** [comment]
It's 100% on plugins to implement selectors, paper cannot do that for plugins.
There are plugins that can substitute those things by just running the command for every player, etc
