### ISSUE TITLE
shadow bug

### ISSUE THREAD

**Issue by seema84** [PaperMC/Paper#5147]
### What behaviour is expected:
No shadow errors are to be expected

### What behaviour is observed:
Shadow error

### Steps/models to reproduce:
explore new chunks (but they also come on already existing chunks from time to time, sometimes also in the same places if I have fixed them beforehand)

### Plugin list:
dynmap*, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, Vault, WorldEdit, WorldGuard

### Paper version:
git-Paper-439 (MC: 1.16.5)

![2021-01-30_22 08 39](https://user-images.githubusercontent.com/2832339/106536887-8f600100-64f9-11eb-8eac-6418effa34ed.png)
![2021-01-30_22 11 34](https://user-images.githubusercontent.com/2832339/106536931-a3a3fe00-64f9-11eb-8ecd-459cbaf0c3ab.png)
![2021-02-02_01 43 23](https://user-images.githubusercontent.com/2832339/106536968-b3bbdd80-64f9-11eb-8220-cb129bf08bc0.png)
![2021-01-15_00 52 53](https://user-images.githubusercontent.com/2832339/106537120-faa9d300-64f9-11eb-8a31-ae48c7717e99.png)
![2020-12-18_03 08 52](https://user-images.githubusercontent.com/2832339/106537263-478da980-64fa-11eb-8ce1-6b5e2574f78e.png)

**Comment by e-im** [comment]
The majority of lighting issues, including this have been fixed on 1.17.1 builds 232+. If you are still experiencing this, leave a comment.
