### ISSUE TITLE
/data command does not work properly

### ISSUE THREAD

**Issue by KleinDevDE** [PaperMC/Paper#5154]
### What behaviour is expected:
![image](https://user-images.githubusercontent.com/13904220/106658355-76109080-659d-11eb-97cd-8bb076031c95.png)

### What behaviour is observed:
No output

### Steps/models to reproduce:
I really don't know how...

### Plugin list:
This plugins has no effect to this behauvior cause I removed all plugins (also the datafolder from every plugin) and this problem does not got resolved..

### Paper version:
the server which runs the command perfectly:
![image](https://user-images.githubusercontent.com/13904220/106658476-a1937b00-659d-11eb-97cf-672e7d89fff4.png)
The server which has the problem:
![image](https://user-images.githubusercontent.com/13904220/106658605-ca1b7500-659d-11eb-83da-ebc2adb11851.png)

### Anything else:
Both servers are connected through the same waterfall proxy server.
I tested it with following scenarios:
- Without any plugin enabled
- Without any datapack enabled
- Copied all plugins plus data from the working server
- Without waterfall proxy server

No one of the scenarios works :/

**Comment by electronicboy** [comment]
1.16.4 is no longer supported and last I toyed with this it was working fine, if you can reproduce this in 1.16.5, please create a new issue
