### ISSUE TITLE
Endermen lose retaliation AI when attacked with specific gamerules set

### ISSUE THREAD

**Issue by partydev** [PaperMC/Paper#5155]
### What behaviour is expected:
Enderman retaliates when being attacked with specific gamerules set.

### What behaviour is observed:
Endermen does not retaliate when being attacked with specific gamerules set.

### Steps/models to reproduce:
Set `forgiveDeadPlayers` to false, set `universalAnger` to true, punch enderman in the legs.

### Plugin list:
none

### Paper version:
This server is running Paper version git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Anything else:
This was reported by a user in Discord that refused to make a ticket here, I tested it and it appears to cause this issue. It seems to work differently in Vanilla (endermen retaliates there).

**Comment by Prof-Bloodstone** [comment]
Can confirm this is a bukkit issue. Reported upstream: https://hub.spigotmc.org/jira/browse/SPIGOT-6337

**Comment by Trigary** [comment]
This is a vanilla issue. The `forgiveDeadPlayers` gamerule has nothing to do with it: it's just `universalAnger`.

Also worth noting, as also noted in Discord, that looking at the enderman's face results in attacks. So the enderman must be hit in the legs.

**Comment by Prof-Bloodstone** [comment]
I think neither of us tested if just setting one of those game rules is enough. But I did try it on vanilla and it worked fine, so seems to be bukkit issue.

**Comment by Trigary** [comment]
I tested it with just one gamerule.

I did try this on vanilla and it did not work; the same issue was present. This issue is also reported on the MC bug tracker: https://bugs.mojang.com/browse/MC-195278

**Comment by Prof-Bloodstone** [comment]
Tested again and the issue is indeed present in vanilla. I have no idea how I tested it yesterday, must have missed something.

**Comment by yannicklamprecht** [comment]
The bug is likely present in the check method of the reset anger goal of the enderman.

**Comment by Trigary** [comment]
The reset anger goal is used by multiple entities, yet they seem to work fine.

**Comment by Machine-Maker** [comment]
This issue appears to have been fixed by vanilla. There is a separate issue about spiders, but I will open another issue for that.
