### ISSUE TITLE
Anti-xray ghost blocks appear when using WorldEdit

### ISSUE THREAD

**Issue by AnttiMK** [PaperMC/Paper#5157]
### What behaviour is expected:
When using any WorldEdit command that deals with changing blocks to air `//set, //paste etc.`, no anti-xray ghost blocks should appear.

### What behaviour is observed:
WorldEdit leaves behind ghost blocks created by Paper's anti-xray (See this Gist for screenshots & config options: https://gist.github.com/Kopo942/8928b8377ed9aaad824e508ef0398a27). 
According to a WE developer, 
> Worldedit calls all the normal stuff for block placements, so likely Paper’s anti xray is checking at a more player specific spot for block changes. It’s likely something they’d need to fix.

### Steps/models to reproduce:
1. Apply anti-xray settings & restart the server
2. Join server, go below y48 in the Overworld, select a region and do `//set air`
3. Go anywhere in the Nether, select a region and do `//set air`

### Plugin list:
`AreaShop, BetterRTP, BuycraftX, ChestShop, ChestShopNotifier*, Citizens, ClaimBlockFixer, CoreProtect, Denizen, DiscordSRV, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, FeatherBoard*, GriefPrevention, HolographicDisplays, LiteBans, LuckPerms, LWC, Multiverse-Core, Multiverse-Portals, MVdWPlaceholderAPI*, PlaceholderAPI, Plan, PlugMan, PremiumVanish, ProtocolLib, RequiredPlugins, SuperbVote, TAB, TimeVote, Vault, Votifier, VoxelSniper, WorldBorder, WorldEdit, WorldGuard`

### Paper version:
```
This server is running Paper version git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version
```

### Anything else:
WorldEdit version at the time of reporting: `7.2.2+fc3c499` (release 7.2.2 on dev.bukkit.org)

**Comment by MM25564** [comment]
bump

**Comment by electronicboy** [comment]
This is basically down to how WE works, and I'm not really sure that there is much we can do here bar moving the call site for updating anti-xray, and impacting the performance of WE; I think ideally WE would potentially add support for this or something, but, feels somewhat out of place, for large modifications the number of updates would be immense, not really sure if this is an issue we'd wanna solve or if they'd wanna solve
