### ISSUE TITLE
CraftAsyncDebugger - memory leak

### ISSUE THREAD

**Issue by kamcio96** [PaperMC/Paper#516]
Paper build: 916

I did heap dump and I found 1.8 milion CraftAsyncDebugger instances ( 4.1% memory). The server was running for 5 hours. It could be upstream issue.

My suggestion: LinkList to next CraftAsynDebugger and remove unnecessary instance :wink:

_Also I found lot of BlockPosition but it could be plugin issue_

**Comment by Gabscap** [comment]
[This change](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/27d58a299c38613b9aeed403c35166c31f2d6025) creates a CraftAsyncDebugger instance for every executed task. In the event of a crash, the last X tasks will appear in the crash report.

**Comment by AlfieC** [comment]
kamcio96: This means that your console is likely being spammed with exceptions - fix those and they'll go away :)

The BlockPositions are short lived objects - I believe they're somewhat improved by the pooled blockposition system recently implemented.

**Comment by kamcio96** [comment]
@AlfieC CraftAsyncDebugger is creating in normal execute, there isn't `try catch`

**Comment by AlfieC** [comment]
Those CraftAsyncDebuggers are simply waiting to be cleaned up by GC most likely - not sure why they haven't. But, the implementation of CraftScheduler means that there should never be more than a couple retained - not 1.8million.

**Comment by kamcio96** [comment]
https://scr.hu/Mnljjd
https://scr.hu/lRAMMP
2659th CraftAsyncDebugger has reference to first 😕

**Comment by AlfieC** [comment]
to first? thats a lil strange
at worst i'd predict the nth debugger having a reference to the n - 1th

**Comment by aikar** [comment]
I think you misread your screenshot. That's the scheduler, not a debugger.

As said before, your issue was that it was generating thousands of exceptions. 
I reviewed the code for it and could not find an issue.

Reopen if you can get another heap dump showing consistent issues that demonstrates linking to an old object
