### ISSUE TITLE
Creeper damage from netherite is too strong

### ISSUE THREAD

**Issue by lostINParadies** [PaperMC/Paper#5160]
I have been able to determine the following problem: When a creeper explodes next to me although I have netherite with enchantment, I die directly. In Vanilla I get 2-3 hearts deducted for this. I have the problem with plugins and also without plugins. Therefore I think that it can not be due to a plugin. I use version paper git-345. 1.16.4

**Comment by Xarius86** [comment]
You are well over 100 builds out-of-date if you are using Paper 345.

**Comment by kashike** [comment]
We no longer support 1.16.4. Please update to 1.16.5.
