### ISSUE TITLE
Anti-Xray / Doesn't alter Ancient Debris

### ISSUE THREAD

**Issue by Prixi** [PaperMC/Paper#5161]
### What behaviour is expected:
Ancient Debris should be changed to a random block, as per anti-xray engine 3.

### What behaviour is observed:
They didn't change whatsoever. It's also been reported to me that this has happened on other servers.

### Steps/models to reproduce:
Enable Xray resource pack and locate Ancient Debris.

### Plugin list:
N/A

### Paper version:
```
[Server] INFO This server is running Paper version git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

[Server] INFO Previous version: git-Paper-444 (MC: 1.16.5)

[Server] INFO You are running the latest version
```

### Anything else:
Nada.

**Comment by Proximyst** [comment]
Works as expected. Ensure you're configuring it correctly; there is no engine mode 3, for starters. Come by #paper-help for live help!
