### ISSUE TITLE
0-tick piston block movers broken, works in certain X, Y, Z coords and directions

### ISSUE THREAD

**Issue by Apprisco** [PaperMC/Paper#5162]
### What behaviour is expected:
___What you expected to see___

![image](https://user-images.githubusercontent.com/34324909/106894606-317c1680-66bd-11eb-90d6-da547d707085.png)
tested on vanilla, all zero tick block movers work perfectly.

### What behaviour is observed:
___What you actually saw___

The instability based on coordinates and reboots is unreal.. Just by moving a few blocks.. it would break.
Just by changing directions.. it would break. All "fixes" in configs were disabled: 
![image](https://user-images.githubusercontent.com/34324909/106894739-5b353d80-66bd-11eb-9953-011ef97ead49.png)

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
![image](https://user-images.githubusercontent.com/34324909/106894768-638d7880-66bd-11eb-9776-e9a58783fb7e.png)

### Plugin list:
___A list of your plugins___
N/A
### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

git-Paper-391 on original testing, git-paper-455 also doesn't work.

### Anything else:
___Anything else you think may help us resolve the problem___

This seems to, almost, be a fundamental issue with paper.

**Comment by aikar** [comment]
It's a fundamental problem with your expectations actually.

The issue is a lot of these bugs that people are trying to depend on depend on java internals, where the X/Y/Z coordinates impact the hashcode of the data, which impacts iteration order.

We've not touched those internals since then, and ultimately if something we've changed is the cause of this, it's pretty much a won't fix.

Ultimately, need to change your build to be more deterministic.

**Comment by Apprisco** [comment]
How is forcefully updating a piston depending on a bug? I have considered switching to 4 gametick solutions... but the current behavior itself should be considered a bug. If this should be patched, patch it out completely instead of making it work in certain coordinates, while not in others.

**Comment by Apprisco** [comment]
Would making a fork removing every single redstone patch be viable? Or would Spigot itself break this? The latest 1.16.5 spigot was crashing so I haven't bothered testing this yet.
