### ISSUE TITLE
I get this error when new chunks load in the minigame I have setup. Its with paper tho. Happens on multiple of my servers.

### ISSUE THREAD

**Issue by MyPreciousGollum** [PaperMC/Paper#5170]
I am on the latest version of paper 1.16.5.

###  Timings or Profile link:
https://timings.aikar.co/?id=e2f46d278a104fe6b408e1a27da421d5

### Description of issue:
My annihilation plugin teleports people to a new world and it lags so bad that the tps cuts in half and sometimes kicks people off.

ISSUE: https://pastebin.com/rxQEUffq

### Plugin list:
Annihilation.jar DeluxeChat-8.9.7.jar DeluxeCombat v.1.19.5.jar LiteBans.jar PL-Hide-1.5.16.1.jar Skript.jar Vault.jar worldguard-bukkit-7.0.4.jar worldedit-bukkit-7.2.0-dist.jar AntiAC-2.7.jar    DeluxeChat-1.16.2.jar  eZProtector-Paper.jar      PlaceholderAPI-2.10.9.jar  ServerSelectorX-Connector-2.1.3-beta.jar  SQLPerms.jar XConomy-2.8.11.jar

### bukkit.yml, spigot.yml, paper.yml, server.properties
Bukkit - https://pastebin.com/7wp18AXQ

Spigot - https://pastebin.com/FD8EwDUY

Paper - https://pastebin.com/yHixzQZG

Properties - https://pastebin.com/4snEUYGc

### Paper version:
git-Paper-463

**Comment by Proximyst** [comment]
It has to update chunks, which is slow. There is only 1 core so it has to do this on the main thread. Upgrade your spec.

**Comment by MyPreciousGollum** [comment]
My server has 16 cores. What do you mean only 1?

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/107125501-554c8180-68a2-11eb-8562-3e1610cec235.png)
Java says you have 1 CPU thread

**Comment by MyPreciousGollum** [comment]
umm weird.

**Comment by MyPreciousGollum** [comment]
How do I run multithreading with java 8 and paper?

**Comment by katekerllenevich** [comment]
by default java uses all available threads, something might be blocking java from using them (pterodactyl for example). also when 1.17 comes out the minimum java version will be java 11. you should update now.

**Comment by MyPreciousGollum** [comment]
Okay so on my other minecraft server on one of my servers that I know is fast I tested timings and got 16 cores on that page.

**Comment by MyPreciousGollum** [comment]
I moved the server to another one because I have a 200 player event tonight and I can't do it on that server till I fix it zzz
