### ISSUE TITLE
Shulker Boxes disappearing randomly!

### ISSUE THREAD

**Issue by the-najjar** [PaperMC/Paper#5172]
### What behaviour is observed:
Shulker boxes randomly disappearing happened to 2 players. I have CoreProtect, 2 players lost 3 shulkers boxes and one player lost about 50 placed shulker boxes.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Uknown

### Plugin list:
___A list of your plugins___
Plugins (81): AdvancedAchievements, AdvancedRegionMarket, AdvancedTabOverlay, ArmorStandEditor, Autorank, BetterBees, BetterShulkerBoxes*, BlockParticles, BookShelf, BuycraftX, ChatManager, Citizens, CoreProtect, CraftEnhance, CrazyCrates, DiscordSRV, dynmap*, EpicWorldGenerator, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, floodgate-bukkit, Floodgate-Skript, Geyser-Spigot, GriefPrevention, GriefPreventionDynmapLite*, HolographicDisplays, HomeGUI, HubParkour, IllegalStack, InteractiveChat, InteractiveChatDiscordSRVAddon, InventoryRollback, InvisibleItemFrame, ItemEdit, LibsDisguises, LuckPerms, MarriageMaster, mcMMO, MobFarmManager, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyPet, MyPetGUI*, NBTAPI, OpenInv, PlaceholderAPI, PlayerWarps, PlotSquared, PluginConstructorAPI, PosePlugin, PosePluginAPI, ProtocolLib, PvPManager, QuickFarm, SAML, Shop, SignEdit, SimpleStack, SkBee, Skellett, skRayFall, Skript, Spartan, SQLibrary*, TuSKe*, UltimateTimber, uShop, Vault, ViaBackwards, ViaVersion, VoidGenerator, VoidSpawn, Votifier, VotingPlugin, Wild, WorldBorder, WorldEdit, WorldGuard

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
Paper version git-Paper-457 (MC: 1.16.5)

### Anything else:
___Anything else you think may help us resolve the problem___
It has been reported before in #3470

**Comment by JRoy** [comment]
Can you reproduce this without 81 plugins. Tile entities just *disappearing* doesn't seem likely as Paper bug. Both this issue and the issue you referenced have `CoreProtect` also.

**Comment by the-najjar** [comment]
> Can you reproduce this without 81 plugins. Tile entities just _disappearing_ doesn't seem likely as Paper bug. Both this issue and the issue you referenced have `CoreProtect` also.

The issue is, I got over 40 active players, and it only happened twice, not sure if making a server with paper and CO will produce it, if so it will take a loooot of time and good luck to reproduce it.
I got these errors between the time confirmed the items were there and between when it was reported.
https://haste.olziedev.com/nuriwomedi.properties
https://haste.olziedev.com/pesezayiro.properties
https://haste.olziedev.com/guwawamiyi.properties
https://haste.olziedev.com/tigezihipa.apache

**Comment by electronicboy** [comment]
Shulkers disappearing is one of those fun issues in vanilla which some people get, some people don't, I've managed to reproduce it once in my recollection and never again, appeared to be tied in some odd way to the chunk itself, defo needs somebody to see if they can reproduce this in a clean environment, but, I think I was actually just killing the server improperly in haste

On that note, your exceptions are all varying degrees of stuff messing with data, you have empty itemstacks in the world, which would suggest that something is modifying your world improperly or causing it to be saved improperly

Diagnosing these types of issues when you have 80 plugins and can't remove them to even begin to test is basically a non-starter, one of your exceptions is caused literally by a bug in a plugin

**Comment by Xarius86** [comment]
You have a problem with Shulker boxes -- while using a plugin, using an outdated API, that has a history of not working well with other plugins (while using 80 others) and causing duplication bugs that specifically messes with shulker boxes. I'd start there.

**Comment by brothanb** [comment]
By chance, do you have scheduled server restarts?   We've seen our hosting provider's server restart process cause some chunks to appear to be rolled back.

**Comment by the-najjar** [comment]
nah only auto world saves, also it happened during no restart or lag for the server.
