### ISSUE TITLE
Team will missing and have some error.

### ISSUE THREAD

**Issue by DoubleBobCat** [PaperMC/Paper#5176]
Server: Bungeecord Server + Paper-1.16.4-latest(I download it a few days ago.)
(*Using` paper only, this bug will not disappear.*)
1. I only moved the paper server to vanilla, and run it. But I found that all team was disappeared.
2. And after I add the team, if I add a monster(like a skeleton) to my team. They also will heart me.
(/team join player @e[type=minecraft:skeleton])
But they will not heart me in vanilla server.
3. I can`t use /tm although /teammsg is working.
4. My English is bad, hope you can understand it QwQ.

**Comment by aurorasmiles** [comment]
Please don't delete the issue template.
What version are you exactly using? 1.16.4 is no longer supported, consider using 1.16.5.
I don't think /tm and /teammsg are vanilla commands.

**Comment by Proximyst** [comment]
`/teammsg` (alias `/tm`) is vanilla.

Enable the option to allow non-players in teams in your `paper.yml` file.
