### ISSUE TITLE
Dragon Egg Probability

### ISSUE THREAD

**Issue by botany111** [PaperMC/Paper#5177]
ender-dragons-death-always-places-dragon-egg: true

It can increase the probability. I hope my players get dragon eggs again
But don’t want players to have a lot

Sorry, my English is not very good :(

**Comment by HexedHero** [comment]
Are you asking if we can make it a chance?

**Comment by Trigary** [comment]
Plugins have full control over whether or not an egg should appear via `DragonEggFormEvent`. Chance-based or other rarity settings related to dragon egg spawning are unlikely to get added to the Paper server configuration. I suggest you to try to get a plugin that does what you want, it is very easy to make one.

**Comment by Proximyst** [comment]
As Trigary said, this is for plugins to do.

**Comment by Trigary** [comment]
Here's a plugin for you @botany111 : https://github.com/Trigary/DragonHatchery
