### ISSUE TITLE
The server stop responding...

### ISSUE THREAD

**Issue by XBlowmPow3r** [PaperMC/Paper#5179]
the server stops responding every few hours, kicking everyone in the lobby, then resumes without crashing, can you tell me the cause of this? I would be grateful

https://pastebin.com/1JjHE8nn

### Plugin list:
https://i.imgur.com/YCKAfU2.png

### Actions to reproduce (if known):
it seems to happen without an action ...

### Paper version: 
- git-Paper-466 (MC: 1.16.5) ---

**Comment by aurorasmiles** [comment]
Just looking at the first line I'd guess "GoldenCrates" is the issue

**Comment by yannicklamprecht** [comment]
Or leaderheads adding head and letting the skins complete on main thread. tech.panoply.leaderheads

**Comment by Chew** [comment]
As stated above, likely a plugin issue. Either way, "DO NOT REPORT THIS TO PAPER". We'd need timings but that's better suited for [#paper-help on Discord](https://discord.gg/papermc). Thank you for the report!
