### ISSUE TITLE
create PID file

### ISSUE THREAD

**Issue by electronicboy** [PaperMC/Paper#5184]
**Is your feature request related to a problem? Please describe.**
Permit saner handling of start scripts, e.g. while true, goto loops;

**Describe the solution you'd like**
create a "run file",
on server startup, create a file in the servers directory, NORMALLY, this would be a pid file in which the pid of the java process would be written to in order to permit scripts to see if the process is still running, however, last I looked this seemed a bit sketchy for cross platform support and maybe not officially supported by java? but, more fundamentally, this would allow a script to check if this file still exists and would allow the scriot to determine if it should restart or not based on the existence of that file

some people take to workarounds for this, such as plugins or abusing restart.sh executing the script before the server has actually exited to try to accomplish this, however does induce some race conditions and potential for missed cases, e.g. native crashes 

**Additional context**
on start:
  - create PID file
on stop:
  - for /stop, ensure that we delete the file
  - Bukkit.shutdown(), this behavior would need to be determined, ideally we just force this to act the same as stop, however, would require plugins people are already using to cause servers to restart automatically
on restart:
  - though API or /restart, leave the file in place

**Comment by JRoy** [comment]
*cries in paperd*

**Comment by amaranth** [comment]
A modern init system doesn't need a pid file to determine if a service is running so this isn't all that useful anymore. Aside from that you'd want to remove it on any code path that results in the JVM shutting down, including `/restart`. Just having the pid file exist wouldn't be enough to know if the server is running, you'd also need to read the number from it, see if a process with that number is running, and hope the kernel hasn't reused your stale pid yet. If you just want a file to determine if the server is running I believe it already makes a lock file to prevent running two copies at the same time.

**Comment by electronicboy** [comment]
modern init systems don't really give you a means to access the console, idea was more just for a flag file so that something managing the server, e.g. a script, can determine if the server should still be running or not

a lock file defo sounds like an interesting alternative as then other stuff can see if the lock is still in place as practically any modern day OS will deal with that sanely, only real thing to be potentially weary about with that is /restart starting the new server before the old one closes properly, we'd need to make sure that the lock is released before that hook fires

**Comment by Owen1212055** [comment]
Assuming that this is solved in 1.19.4, which adds a new PID file launch option.
