### ISSUE TITLE
API for vanilla enchant mimic

### ISSUE THREAD

**Issue by alfiejfs** [PaperMC/Paper#5186]
**Is your feature request related to a problem? Please describe.**
A few times I have wanted to mimic a level X enchant on an item as if it were put in an enchantment table and enchanted at that level. As far as I am aware there is no API for this, and I had to use NMS to get the effect

**Describe the solution you'd like**
Some API that takes an `ItemStack, int` and enchants that ItemStack as if it were enchanted at the level of the passed integer

**Describe alternatives you've considered**
NMS, hardcoding the enchants

**Additional context**
Been a while since I've attempted this, but I thought I'd open the issue. Can't remember where I have a sample of achieving this effect, but a quick scan of source tells me `ContainerEnchantTable`, referencing `EnchantmentManager` has the majority of the methods that could be abstracted to an API

**Comment by BillyGalbreath** [comment]
Already exists. you can't add a normal enchantment, as levels that high dont exist. You have to add an _unsafe_ enchantment, which removes level and compatibility checks.

https://papermc.io/javadocs/paper/1.13/org/bukkit/inventory/ItemStack.html#addUnsafeEnchantment-org.bukkit.enchantments.Enchantment-int-

**Comment by Machine-Maker** [comment]
I think OP wants to include the randomness of extra enchants that the table gives? Instead of specifying an enchantment.

**Comment by alfiejfs** [comment]
> I think OP wants to include the randomness of extra enchants that the table gives? Instead of specifying an enchantment.

Yep, this is what I was getting at. Sorry if I poorly explained that @BillyGalbreath

**Comment by BillyGalbreath** [comment]
That's going to be rather difficult, as the randomness depends on a seed from the enchanting table properties

**Comment by alfiejfs** [comment]
Could a random seed not just be used each time? I don't see why that is an issue

**Comment by electronicboy** [comment]
It's more the whole notation of expecting to get vanilla behavior in a believable/consistent manner vs just having something which pretends to work, there's also varying other aspects such as the level of the table, etc; The concept that you're asking for it to be an enchant of a specific level from an anvil also seems misguided and would likely be on a plugin to deal with, best paper could offer is a bunch of enchants that the table might produce, etc

**Comment by alfiejfs** [comment]
I think that is what I'm asking? Something to mimic an item being enchanted an enchant table for a given enchant table level (ie 30 levels, 10 levels or whatever). As far as I am aware, the ContainerEnchantTable contains everything that is actually needed to do this, unless I am missing something

As for it being believable, I'm not sure what you mean by that. All calls to what I am proposing would be independent and not rely on any enchant table seeding or whatever actually goes on behind the scenes - just an independent call as if an item were being enchanted in a fresh enchant table.

**Comment by Proximyst** [comment]
I think this would be fine to implement with a random/specified seed with notes in the API. I think Cat's onto something with returning enchantment(s) the API could produce, so the caller can decide how to use them -- I'm fairly sure (though I haven't checked) that there's a method to apply multiple enchants on an item anyways.

**Comment by Machine-Maker** [comment]
Added here btw https://github.com/PaperMC/Paper/commit/8897cea0b05d9b5f110ed5f153a00daee32875c4

**Comment by alfiejfs** [comment]
Oh love it, amazing, tyvm @Machine-Maker and @jpenilla!
