### ISSUE TITLE
Performance regression of ItemStack#getEnchantmentLevel

### ISSUE THREAD

**Issue by konsolas** [PaperMC/Paper#5188]
**Is your feature request related to a problem? Please describe.**
Patch 0063 changes the implementation of ItemStack#getEnchantmentLevel and ItemStack#containsEnchantment. Instead of directly accessing the item's enchantment data, they now perform an expensive getItemMeta call:
 - https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0063-Handle-Item-Meta-Inconsistencies.patch#L129-L134
 - https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0063-Handle-Item-Meta-Inconsistencies.patch#L123-L124

Previously, ItemStack#getEnchantmentLevel was a fast alternative to getItemMeta, but this change makes them just as slow as each other.

**Describe the solution you'd like**
Revert the implementation of getEnchantmentLevel and containsEnchantment to upstream.

**Describe alternatives you've considered**
Call `EnchantmentManager.getEnchantmentLevel(CraftEnchantment.getRaw(ench), handle)` directly through reflection/nms.

**Additional context**
The patch resolves item meta inconsistencies, but getEnchantmentLevel and containsEnchantment can't introduce any inconsistencies given that they don't write any enchantments. It should be safe to continue using the faster upstream implementations.

**Comment by MM25564** [comment]
bump

**Comment by Proximyst** [comment]
@MM25564 If you continue to spam issues, you will be blocked from the organisation.

**Comment by MM25564** [comment]
sry :( im new

**Comment by Malfrador** [comment]
This is still an issue, don't stale.

**Comment by qixils** [comment]
could we get a `status: accepted` to please the holy stale bot? :>

btw, here's an updated permalink to the relevant patch: https://github.com/PaperMC/Paper/blob/47139376c468fad9261343a3806e241c23a9d4c3/patches/server/0062-Handle-Item-Meta-Inconsistencies.patch#L129-L143
