### ISSUE TITLE
Block.getTemperature() reporting incorrect temperatures in Swamp

### ISSUE THREAD

**Issue by Frogperson** [PaperMC/Paper#5190]
### What behaviour is expected:
According to the [Minecraft wiki](https://minecraft.gamepedia.com/Tint#Swamp_color):
> Swamp temperature, which starts at 0.8, is not affected by altitude. Rather, a Perlin noise function is used to gradually vary the temperature of the swamp. When this temperature goes below −0.1, a lush green color is used (
 #4C763C); otherwise it is set to a sickly brown (
 #6A7039).
 
Block.getTemperature() should correctly show these varying temperatures

### What behaviour is observed:
Block.getTemperature() is always returning the default 0.8 temp below sea level, and goes down when you go up in altitude.

### Steps/models to reproduce:
Just call Block.getTemperature() at various locations in a swamp and view the output

### Plugin list:
None (other than a plugin outputting temperatures when I place a block)

### Paper version:
466

### Anything else:
I didn't dig into the getTemperature code, but my guess is it's just grabbing the default temp for swamps (0.8) and calculating changes as though it were a normal biome. Swamps calculate temperatures differently than other biomes, though, so doing it the same way results in incorrect temperatures being returned.

**Comment by DLaMott** [comment]
Hello, I am looking into working on this. This will be my first contribution.

**Comment by Owen1212055** [comment]
This doesn't look like an issue. Minecraft seems to have internally deprecated this temperature behavior, and instead uses separate methods for stuff like how foliage color is handled.
![image](https://user-images.githubusercontent.com/23108066/176020960-1d86a9eb-7d92-456f-bce2-1894660a8a9d.png)

Swamps do not use the temperature for determining the grass color, and now instead use a SWAMP GrassColorModifier (and the base temperature, but this doesn't change).

So this is just the result of the temperature logic changing.

**Comment by Owen1212055** [comment]
Because the underlying Minecraft implementation has changed, this behavior is not considered correct anymore. 
A more in-depth explanation is provided above. Feel free to comment on this issue if you feel that the explanation is incorrect, and this can be reopened and re-evaluated.  

Thanks for the issue. 😄
