### ISSUE TITLE
Stack entities config

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#5193]
**Is your feature request related to a problem? Please describe.**
Add a feature to stack mobs which is spawned from breeding.

**Describe the solution you'd like**
This feature would be cool because plugin StackMob have some useless commands.

**Describe alternatives you've considered**
Also add a support for color name of stacked entities and unstack them while rightclick and breed them.

**Additional context**
None

**Comment by Proximyst** [comment]
Not gonna happen. Stacking mobs has detrimental effects on the server; limit them instead.
