### ISSUE TITLE
commandBlockOutput gamerule not working

### ISSUE THREAD

**Issue by maicol07** [PaperMC/Paper#5194]
### What behaviour is expected:
Command block output stops

### What behaviour is observed:
Command block output continues

### Steps/models to reproduce:
Try the gamerule

### Plugin list:
None

### Paper version:
Build `#468`

### Anything else:
With the Vanilla server this works.
Related to #2490

**Comment by electronicboy** [comment]
command used? screenshot? something outside of "doesn't work"

**Comment by maicol07** [comment]
I can send you my world.

Also tried on Spigot, same bug

**Comment by maicol07** [comment]
Here it is: [easyupload.io/9asbgr](https://easyupload.io/9asbgr) or [gofile.io/d/4Jn0my](https://gofile.io/d/4Jn0my)

**Comment by maicol07** [comment]
Here it is: [easyupload.io/9asbgr](https://easyupload.io/9asbgr) or [gofile.io/d/4Jn0my](https://gofile.io/d/4Jn0my)

**Comment by Titaniumtown** [comment]
You didn't have to say that twice *bu dum tsss*

**Comment by Proximyst** [comment]
Works fine.
![https://uwu.whats-th.is/6YeMdbd.png](https://uwu.whats-th.is/6YeMdbd.png)
