### ISSUE TITLE
Grindstone doesn't perform max stack size check

### ISSUE THREAD

**Issue by msmanui** [PaperMC/Paper#5196]
Hello, i found a new dupe that is working in paper 1.16.5 ofc

[https://www.youtube.com/watch?v=JugvvkVr2iA](url)

**Comment by Chew** [comment]
Thank you for the clickbait, this doesn't appear to be a dupe according to people on Discord. Is a bug though.

Edit: Imagine my shock! ![image](https://user-images.githubusercontent.com/8278263/108147030-d91d1f80-7093-11eb-86d7-a695db4aa895.png)

**Comment by JRoy** [comment]
Better title: `Grindstone doesn't perform max stack size check on result itemstack`

**Comment by msmanui** [comment]
> Thank you for the clickbait, this doesn't appear to be a dupe according to people on Discord. Is a bug though.
> 
> Edit: Imagine my shock! ![image](https://user-images.githubusercontent.com/8278263/108147030-d91d1f80-7093-11eb-86d7-a695db4aa895.png)

It does work on survival.

**Comment by Black-Hole** [comment]
Items with durability won't stack anyway. The remaining items that you can enchant with curses in survival mode are stackable already (compass, carved pumpkin, heads).
