### ISSUE TITLE
Items group through wall

### ISSUE THREAD

**Issue by F1nnM** [PaperMC/Paper#5204]
### What behaviour is expected:
When a item is droped to the left of a wall of blocks and one to the right off the wall, both items should remain there.

### What behaviour is observed:
The items group together and both items end up on one side of the wall.

### Steps/models to reproduce:
Build a 1 wide wall of any block, drop an item on the left side of the wall, drop one on the right side.

### Plugin list:
Chunkmaster, SAML, VillagerOptimizer

### Paper version:
This server is running Paper version git-Paper-"088fa6f28" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
(I cloned the repo and built it from source)

**Comment by PaulBGD** [comment]
It's fairly easy to add, but I think this would have to be behind a configuration option. Doing even a single block lookup will hit performance when merging items.

A more ideal fix would be to lower the radius of merging to less than a block, although at that point item merging becomes much less helpful.
