### ISSUE TITLE
Paper not supporting a specific map giving function errors

### ISSUE THREAD

**Issue by ricsal1** [PaperMC/Paper#5208]
### Link/paste of stack trace

https://paste.gg/p/PasteBot/d62f0d2c283a4a30abbcb596adca51b6

### Plugin list:
No plugins loaded

### Actions to reproduce (if known):
Just running a blanc server with version paper-1.16.5-471
Load the map from https://phoenixsc.me/download-links/among-us-1-16-3/  version 2 or 3 (log is from 3).

This map runs perfectly on Vanilla 1.16.5.

### Paper version:

paper-1.16.5-471

**Comment by Malfrador** [comment]
This can be fixed by setting `function-permission-level=` (server.properties) to 2 or higher. 2 is default, and I doubt many people change it. 

Apparently checking for permissions for functions isn't implemented in CraftBukkit, creating this misleading error message if the required permission(-level) isn't granted. 

Doing that I was able to play the map just fine. Its pretty well-made and fun actually, however I lost - against myself.

**Comment by ricsal1** [comment]
Hi,

Thanks for the tip.

Did you got this issue after?

[10:56:54 INFO]: Running delayed init tasks
[10:56:54 INFO]: Done (1.505s)! For help, type "help"
[10:56:54 INFO]: Timings Reset
[10:56:55 ERROR]: Block at -281, 77, -256 is Block{minecraft:barrier} but
has net.minecraft.server.v1_16_R3.TileEntityBrewingStand@7021590c. Bukkit
will attempt to fix this, but there may be additional damage that we cannot
recover.
[10:56:55 ERROR]: Block at -281, 77, -256 is Block{minecraft:barrier} but
has net.minecraft.server.v1_16_R3.TileEntityBrewingStand@9a56e53. Bukkit
will attempt to fix this, but there may be additional damage that we cannot
recover.
[10:56:55 ERROR]: Block at -281, 77, -256 is Block{minecraft:barrier} but
has net.minecraft.server.v1_16_R3.TileEntityBrewingStand@29da9e20. Bukkit
will attempt to fix this, but there may be additional damage that we cannot
recover.
[10:56:55 ERROR]: Block at -281, 77, -256 is Block{minecraft:barrier} but
has net.minecraft.server.v1_16_R3.TileEntityBrewingStand@4d8a085. Bukkit
will attempt to fix this, but there may be additional damage that we cannot
recover.
[10:56:55 ERROR]: Block at -281, 77, -256 is Block{minecraft:barrier} but
has net.minecraft.server.v1_16_R3.TileEntityBrewingStand@4afcdef2. Bukkit
will attempt to fix this, but there may be additional damage that we cannot
recover.

Regards

**Comment by Malfrador** [comment]
Yes, this seems to be "normal". While it's annoying, it shouldn't break the map. Michael also said on discord yesterday that the map was working, but spamming errors.

**Comment by ricsal1** [comment]
Hello,
Thanks, I confirm it works.
Anyway it spends a bit of cpu, do you think this can be optimized.
Thanks

A domingo, 21 de fev de 2021, 15:36, Malfrador <notifications@github.com>
escreveu:

**Comment by Malfrador** [comment]
Datapacks are not performant at all and inefficient. I don't think its possible to significantly optimize the map (or any Datapack).
The only thing you can do is using/making a plugin instead.

Btw, if you think this is solved, you can close the issue. Should be the button next to "Comment" and helps to keep the issue tracker clean ;)
