### ISSUE TITLE
Beacon Range is not applied

### ISSUE THREAD

**Issue by nfsprodriver** [PaperMC/Paper#5209]
I'm using build 471 (1.16.5).
I created a plugin in kotlin to set the range of beacons using the recently added beacon range functions. It's done by the chunk loader events:

```kotlin
package events

import BeaconRange
import org.bukkit.Chunk
import org.bukkit.World
import org.bukkit.block.Beacon
import org.bukkit.block.BlockState
import org.bukkit.event.EventHandler
import org.bukkit.event.Listener
import org.bukkit.event.world.ChunkLoadEvent
import java.util.logging.Logger

class ChunkLoad(private val range: Double, private val logger: Logger) : Listener {

    @EventHandler
    fun onChunkLoad(event: ChunkLoadEvent) {
        var chunk: Chunk = event.chunk
        var chunkBlocks: Array<out BlockState> = chunk.tileEntities
        chunkBlocks.forEach { block ->
            if (block is Beacon) {
                block.setEffectRange(range)
                logger.info("${block.effectRange}")
                block.update(true)
            }
        }
    }

    @EventHandler
    fun onWorldLoad(event: ChunkLoadEvent) {
        var world: World = event.world
        var loadedChunks: Array<out Chunk> = world.loadedChunks
        loadedChunks.forEach { chunk ->
            var chunkBlocks: Array<out BlockState> = chunk.tileEntities
            chunkBlocks.forEach { block ->
                if (block is Beacon) {
                    block.setEffectRange(range)
                    logger.info("${block.effectRange}")
                    block.update(true)
                }
            }
        }
    }
}
```

### What behaviour is expected:
I expect the range is extended to 500.0, my sample value here.

### What behaviour is observed:
The beacon (single one, level on (3x3)) keeps unchanged.

### Plugin list:
My plugin is the only one installed, logging works as expected.

Does anyone have an existing example to make this work?

**Comment by Malfrador** [comment]
I can't tell you why its not getting changed, but the effect will only work for currently loaded chunks, so a range like 500 blocks will only work if your view-distance is 32 chunks or the chunk with the block is somehow loaded all the time. Even then, im not sure if it will work - its not really intended for big ranges like that.

**Comment by nfsprodriver** [comment]
Thanks for your answer! Somehow I got it working, so might be a mistake from my side. This is my first plugin project. I'll check it out and come back to this...

**Comment by Proximyst** [comment]
Cannot reproduce. Works fine.
```kotlin
    @EventHandler
    fun event(event: PlayerInteractEvent) {
        val block = event.clickedBlock ?: return
        val state = block.state as? Beacon ?: return
        state.effectRange = 3.0
        state.update()
    }
```
