### ISSUE TITLE
The server file don't execute with Java OpenJDK 11 installed 

### ISSUE THREAD

**Issue by tiagopestanak** [PaperMC/Paper#5210]
Hi! I am having an issue when running the paper server. I have Java installed but it does not open any window when clicking on the file. I have Java OpenJDK 11 installed at the moment but it still doesn't work, since I downloaded the java indicated in [this post](https://papermc.io/forums/t/java-11-mc-1-17-and-paper/5615/2). Can you help me with this? I have the most recent server file in the moment. I tested it with Java JRE 8 and ran the file.
![Installed Java](https://user-images.githubusercontent.com/75392077/108623610-c01bc200-7437-11eb-85bd-44ec9078d9d4.png)

**Comment by electronicboy** [comment]
Please use the Discord/Forum/IRC for support
