### ISSUE TITLE
Join and Quit messages no longer accept null values

### ISSUE THREAD

**Issue by JasonHorkles** [PaperMC/Paper#5212]
### What behaviour is expected:
No blank line, restart message should show all new lines when `\n` is used
### What behaviour is observed:
Blank line is sent in console when a player joins or leaves, and the restart message doesn't show new lines with `\n` anymore
### Steps/models to reproduce:
Join and leave to see blank line
Set a restart message with multiple lines and restart the server while on the server to only get the top line
### Plugin list:
None
### Paper version:
git-Paper-475 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
### Anything else:
Started happening at build 473 (#4842)

**Comment by aurorasmiles** [comment]
bad title aside, I have a similar issue

**Comment by JasonHorkles** [comment]
> bad title aside, I have a similar issue

Feel free to change it or suggest a new one
