### ISSUE TITLE
Ilegal acesss editing request

### ISSUE THREAD

**Issue by CadmielMatioli** [PaperMC/Paper#5219]
###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.___

### Description of issue:
On minecraft servers as a whole it is possible to circumvent requests without encryption, for example, when you throw an item for example 1 diamond block on the floor you pause the request and edit for whatever you want, then when you let it sequence it just happens what you edited in, this can be done on absolutely any current miencraft server and does not apply to servers because I found out that it is a treatment between the minecraft itself and the server and not the hosting.
Apparently it was done by a direct connection on linux to catch the "conversation" between client and server and retrieve this information and edicts, so I managed to find until now, the information that passes between client and server is not encrypted

### Plugin list:
there were still no plug-ins when the server ran it

### bukkit.yml, spigot.yml, paper.yml, server.properties
pattern

### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Steps to Reproduce:
I can't reproduce because the users who managed to accomplish the feat unfortunately refuse to teach how it was done, I was only able to extract this information
pause and edit request between data that is passed from the minecraft client to the server

### Paper version:
1.16.2 and 1.15.1

**Comment by kashike** [comment]
We do not support 1.16.2 or 1.15.1.
