### ISSUE TITLE
disable-chest-cat-detection not working as intended

### ISSUE THREAD

**Issue by BillyGalbreath** [PaperMC/Paper#522]
Setting disable-chest-cat-detection to true in paper is not working as intended.

### What behaviour is expected:
Cats do not go sit on chests.

### What behaviour is observed:
Cats will go still sit on chests.

I'm not too familiar with the vanilla cat mechanics, but cats will not interact with player anymore (right click to sit/stand, eating raw fish) once a cat sits on a chest. Even if you push the cat off the chest by walking into it the cat is unresponsive. The cat will only become responsive again if you punch the cat (cause it damage).

### Steps/models to reproduce:
1) set disable-chest-cat-detection to true
2) start server normally
3) spawn in a cat and tame it
4) go stand near a chest

### Plugin list:
Tested with no plugins.

### Paper build number:
Paper build 945 (effects all 1.11 builds so far that I've tried)

**Comment by AlfieC** [comment]
That isn't what the option entails. Usually, you would not be able to open that chest if a cat was sitting on it. This was a performance waste for some servers. Enabling that options removes that check. 
Nothing to do with where a cat can go and sit.
