### ISSUE TITLE
No Patrol or Wandering Trader Spawning

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5223]
### What behaviour is expected:
Patrol and Trader Spawning following the vanilla spawning rules

### What behaviour is observed:
No Pilliger Patrol spawns or Wandering Trader Spawns

### Steps/models to reproduce:
Load a Server and wait (gamerule doPatrolSpawning and doTraderSpawn are true)

### Plugin list:
none

### Paper version:
This server is running Paper version git-Paper-480 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by e-im** [comment]
I haven't been able to reproduce this and see spawns of both frequently. Do you happen to use the `/time` command or have a plugin that sets the time such as a percentage sleep plugin? If this is done incorrectly, you will reset the day to 0 and these will never spawn. As you said you have no plugins, if you use the `/time` command ensure not to use `/time set` and only `/time add`. Or when using `/time set` include the number of days, else you will always reset it to 0.

**Comment by MiniDigger** [comment]
(please don't hurt me limbo)

**Comment by limbo-app** [comment]
> (please don't hurt me limbo)

:bone: :hammer: :ambulance:
