### ISSUE TITLE
Crash Report (Console asked me to)

### ISSUE THREAD

**Issue by Dangleben1** [PaperMC/Paper#5225]
[2021-02-22-1.log.gz](https://github.com/PaperMC/Paper/files/6024007/2021-02-22-1.log.gz)
[latest.log](https://github.com/PaperMC/Paper/files/6024008/latest.log) Here ya got the logs

### What behaviour is expected:
___Server to start up___

### What behaviour is observed:
___Took 2minutes and it shutted down i think___

### Steps/models to reproduce:
___No,___

### Plugin list:
___None___

### Paper version:
___paper-1.16.5-483___

### Anything else:
___Taskmanager --> HDD constantly 100%___

**Comment by electronicboy** [comment]
`[18:36:16] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 7691ms or 153 ticks behind`
Your server dumped that saying it was overloaded, and then came out a few minutes later and fully timed out; Either you disabled the incremental watchdog warnings, or, your system is so overloaded that it crapped out in a drastic fashion
