### ISSUE TITLE
XP orbs not merging after falling down

### ISSUE THREAD

**Issue by masterX244** [PaperMC/Paper#5226]
### What behaviour is expected:
XP orbs merging after they fall down

### What behaviour is observed:
XP orbs distanced closer than mergeradius.

### Steps/models to reproduce:
Throw a bottle of enchant onto the 7th row of that device and wait until orb reached floor. Then repeat

https://cdn.discordapp.com/attachments/710178160263692338/813489271662968832/unknown.png

### Plugin list:
None, tested on a plain Paper

### Paper version:
This server is running Paper version git-Paper-484 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by BillyGalbreath** [comment]
Works As Intended.

Merging _only_ happens at the time the entity is spawned into the world. To "fix" this we would have to continuously scan the world for nearby orb entities throughout the life of each orb entity and would cause much lag.

**Comment by masterX244** [comment]
Items still merge though after falling down

**Comment by electronicboy** [comment]
orbs aren't items, and orbs generally pool up much more the items easily outside of people messing around with stuff, this would essentially be a feature request but not too sure if there is much interest in this given the nature of xp orbs and how they pool up, especially with other features like the max merge stuff

**Comment by aurorasmiles** [comment]
As explained by @BillyGalbreath and @electronicboy this works as intended
