### ISSUE TITLE
Include BukkitAudiences

### ISSUE THREAD

**Issue by keyute** [PaperMC/Paper#5229]
**Is your feature request related to a problem? Please describe.**
As Paper has decided to support Adventure, Paper should shade either BukkitAudience or a form of audience as it does not really make sense to add an additional dependency into projects that decide to support Adventure.
**Describe the solution you'd like**
Include a form of BukkitAudiences
**Describe alternatives you've considered**

**Additional context**

**Comment by electronicboy** [comment]
if you're using adventure standalone, you really should be relocating your dependencies anyways, I don't think that this actually solves any form of issue

**Comment by keyute** [comment]
It certainly is not an issue to shade the platform dependency into my project, just thought that it would make more sense if Paper implemented Adventure Platform natively since most "legacy strings" methods are deprecated.

**Comment by Proximyst** [comment]
Adventure is implemented natively: you can call methods such as `CommandSender#sendMessage(Component)`.

**Comment by electronicboy** [comment]
Yea, No need to implement the platform as it's built-in, just like in other native impls of it, no need for a pretty wrapper for stuff to be in place; if you're actually trying to use adventure cross platform, you'd wanna stick to the standalone plugin bundle vs relying on the native stuff, as that won't be available, as well as typical "good practices" when using shared libs
