### ISSUE TITLE
Console command sender does not show colors/formatting when sending Adventure Components

### ISSUE THREAD

**Issue by emilyy-dev** [PaperMC/Paper#5232]
### What behaviour is expected:
I'd expect colors to show ngl

### What behaviour is observed:
No color and/or formatting is displayed

### Steps/models to reproduce:
```java
Bukkit.getConsoleSender().sendMessage(Component.text("anything tbh", NamedTextColor.RED));
```

### Plugin list:
* LuckPerms
* test
* ProtocolLib
* spark
* Vault
* WorldEdit

### Paper version:
`This server is running Paper version git-Paper-486 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

### Anything else:
![image](https://user-images.githubusercontent.com/35617540/108806641-07619a00-7581-11eb-844e-d1fb5a66cb28.png)

The component sent in the image above is (equivalent to):
```json
{
  "text": "",
  "extra": [
    {
      "text": "",
      "color": "gray",
      "extra": [
        {
          "text": "["
        },
        {
          "text": "PT",
          "color": "aqua",
          "bold": true
        },
        {
          "text": "]"
        }
      ]
    },
    {
      "text": " "
    },
    {
      "text": "You are not allowed to run this command",
      "color": "red"
    }
  ]
}
```

Additionally, sending components with Adventure shaded in the plugin (relocated of course) with `adventure-platform-bukkit` shows them colors just fine; for example:
![image](https://user-images.githubusercontent.com/35617540/108807228-96bb7d00-7582-11eb-9450-443bba123a86.png)

**Comment by jpenilla** [comment]
will be fixed when #5230 is merged
