### ISSUE TITLE
ItemStack serialized and deserialized not the same

### ISSUE THREAD

**Issue by PapiCapi** [PaperMC/Paper#5234]
### What behaviour is expected:
Same item serialized and deserialized.

### What behaviour is observed:
So actually i created a plugin which is storing items held in hand by a player, shows them in a GUI ( by deserializing them ) when doing a command and if the player wants to get back his item, he has to click on the item in the GUI. Actually, the items in the GUI and in the config are not the same so i can't compare anything.
Here is an output of a debug where itemSerialized is the item clicked and serialized :

itemSerialized: {v=2586, type=PRISMARINE_CRYSTALS, amount=64, meta=UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"text":"\u00A76\u00A7oMonnaie d'échange unique"}, lore=[{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"Cette monnaie vous permettra"}],"text":""}, {"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"de vous procurer auprès"}],"text":""}, {"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"des commerçants de nombreux"}],"text":""}, {"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":"objets ancestraux."}],"text":""}], enchants={PROTECTION_ENVIRONMENTAL=1}, ItemFlags=[HIDE_ENCHANTS]}}
 
itemInConfig: {v=2586, type=PRISMARINE_CRYSTALS, amount=64, meta=UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"text":"\u00A76\u00A7oMonnaie d'échange unique"}, lore=[{"text":"\u00A72\u00A7oCette monnaie vous permettra"}, {"text":"\u00A72\u00A7ode vous procurer auprès"}, {"text":"\u00A72\u00A7odes commerçants de nombreux"}, {"text":"\u00A72\u00A7oobjets ancestraux."}], enchants={PROTECTION_ENVIRONMENTAL=1}, ItemFlags=[HIDE_ENCHANTS]}}

 

### Steps/models to reproduce:
- Give yourself an item with a modified name and lore, for example :
minecraft:give @p minecraft:prismarine_crystals{display:{Name:'{"text":"\\u00A76\\u00A7oMonnaie d\'échange unique"}',Lore:['{"text":"\\u00A72\\u00A7oCette monnaie vous permettra"}','{"text":"\\u00A72\\u00A7ode vous procurer auprès"}','{"text":"\\u00A72\\u00A7odes commerçants de nombreux"}','{"text":"\\u00A72\\u00A7oobjets ancestraux."}']},HideFlags:1,Enchantments:[{id:"minecraft:protection",lvl:1s}]} 1

- Serialize the item into a config

- Unserialize the item

- Try to compare them using equals

### Plugin list:
![image](https://user-images.githubusercontent.com/49530141/108831393-597add80-75ca-11eb-8df2-7bd2b1418f39.png)

### Paper version:
[11:29:25 INFO]: This server is running Paper version git-Paper-487 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[11:29:25 INFO]: Checking version, please wait...
[11:29:25 INFO]: Previous version: git-Paper-444 (MC: 1.16.5)
[11:29:25 INFO]: You are running the latest version

### Anything else:
I think the issue is coming from the recent changes where "extra" was added juste before the lore and the item name.

**Comment by Proximyst** [comment]
Item serialisation has and always will be janky & unreliable. Use the byte-based serialisation methods instead.

**Comment by aikar** [comment]
even with byte though, you're not going to get that format back. your old format is old and illegal, and paper is fixing it for you.
