### ISSUE TITLE
Iron Golems Spawning inside of blocks

### ISSUE THREAD

**Issue by MM25564** [PaperMC/Paper#5236]
### What behaviour is expected:
___What you expected to see___
Iron Golems to spawn in air and not clipping any blocks.

### What behaviour is observed:
___What you actually saw___
Many iron golems spawning inside of fences, walls and clipping / suffocating in the edge of solid block walls.
![image](https://user-images.githubusercontent.com/79518386/108844154-9eefd880-75d3-11eb-9a85-7bfd6b26778b.png)
![image](https://user-images.githubusercontent.com/79518386/108845453-5b966980-75d5-11eb-83b5-89af83f9b78e.png)
https://user-images.githubusercontent.com/79518386/108882747-a5df1100-75fc-11eb-8cbe-db4c26d54178.mp4

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Build https://www.youtube.com/watch?v=0L_optIDx2U and watch them spawn.
Or use: https://mega.nz/file/pmoyBBBb#W3MNRzuaQi6MLseSYZYSTFXKvfTo_hYJnVKNaSw1aaU schematic and add the villagers and zombie. To make it happen more frequently, replace all of the area where water is (except for the zombie water) with glass.

### Plugin list:
___A list of your plugins___
![image](https://user-images.githubusercontent.com/79518386/108843140-33f1d200-75d2-11eb-9147-366da68549cc.png)

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
![image](https://user-images.githubusercontent.com/79518386/108843201-4835cf00-75d2-11eb-9b2b-0404283d5fdf.png)
This server is running Paper version git-Paper-487 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___
This issue disappeared when I set iron-golems-can-spawn-in-air to false in paper.yml
This issue is not present in singleplayer as it was fixed: https://bugs.mojang.com/browse/MC-148955
This issue was present before Adventure was implemented.
This issue is present on a completely fresh paper server.

**Comment by MM25564** [comment]
bump

**Comment by GamerWho52** [comment]
this is happening for me, its annoying as setting iron-golems-can-spawn-in-air to false stops many iron farms

**Comment by MM25564** [comment]
UPDATE: Issue still present on version 584

**Comment by ErnGr** [comment]
They also spawn inside of slabs

**Comment by Hiukuss** [comment]
Still present on Paper version git-Paper-276 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 1707c10)
Changing iron-golems-can-spawn-in-air to false in paper.yml did help but unsure if it affected overall farm rates.

![2021-09-23_16 51 01](https://user-images.githubusercontent.com/1525743/134584477-4527b4db-6ea7-4302-b93b-015b7a770d60.png)
![2021-09-23_16 57 11](https://user-images.githubusercontent.com/1525743/134584480-aa8d533d-792f-454e-83bb-76681b3cd8d4.png)
![2021-09-23_16 58 20](https://user-images.githubusercontent.com/1525743/134584484-46fa8afe-c9dc-493f-b2b5-3db3bc6264e1.png)

**Comment by Machine-Maker** [comment]
@MM25564 can you replicate this without plugins?
@Hiukuss can you replicate this without plugins?

I've been sitting here for a few minutes, with your pasted schematic, replaced the water with glass, and not a golem has spawned. There have been plenty of attempts (I'm debugging the code so I can see exactly when it tries to spawn a golem) but nothing is spawning.

As soon as I opened up a gap letting one spawn, one did right where it could. I'm going to mark this as cannot reproduce until given reason otherwise.

**Comment by MM25564** [comment]
Hm, this was a while ago when I tried it. It was happening for me with a fresh server before as I mentioned in my original post. Then again it was on 1.16.5.

**Comment by Hiukuss** [comment]
@Machine-Maker 
Removed all plugins and reverted back to `iron-golems-can-spawn-in-air = true` to test. 
Tested again with `iron-golems-can-spawn-in-air = false`.
Golems spawned as intended -- none in walls or transparent blocks for both settings.

OP and I share only Essentials, Essentials Chat, Essentials Spawn, Vault, and WorldEdit for plugins. **Removed EssentialsXSpawn and golem behavior was fixed.** 

Reported bug to the Essentials team. Should've done all this first, sorry! Not Paper's fault :)

![image](https://user-images.githubusercontent.com/1525743/134763883-93554895-bfa2-4590-bb1e-2988564c475e.png)

**Comment by Machine-Maker** [comment]
Awesome, glad to know the cause was found!
