### ISSUE TITLE
Iron Golem Farm Bug

### ISSUE THREAD

**Issue by CocoaTune** [PaperMC/Paper#5245]
Iron farms are only working sometimes and will suddenly stop working after a few minutes - sometimes when they sleep again it starts up but not all the time.

Version: 1.16.5

Plugins: BanItem, LaggRemover

(It didn't have a template when I made this comment)

**Comment by aurorasmiles** [comment]
Please don't delete the template. 
- What version are you using
- What plugins do you have installed
- Describe "bug out"
