### ISSUE TITLE
No multiple different block-damage to a player possible

### ISSUE THREAD

**Issue by TheFruxz** [PaperMC/Paper#5246]
### What behaviour is expected:
Multiple blocks having break-texture/design/overlay

### What behaviour is observed:
only one block a time has the break-texture/design/overlay

### Steps/models to reproduce:
Creating multiple different timed (async) BukkitRunnable's sendBlockDamage different Blocks (at different times) to the same player

### Plugin list:
Our Framework, our Plugin, LuckPerms, Multiverse-Core, ProtocolSupport, WorldEdit

### Paper version:
git-Paper-496 1.16.5-R0.1

### Anything else:
```kotlin
it.sendBlockDamage(block.location, (attempt.toDouble() / (remainingSeconds*timeMultiplikator)).toFloat())
```

The BlockDamage of an another block is dissappearing when an other block is receiving an block-damage

**Comment by MiniDigger** [comment]
are you sure this isn't a client limitation? I don't imagine this something the server would particularly caire about, especially since iirc that method you used just sends a packet.

**Comment by Shevchik** [comment]
WAI.
A single breaker id can only display breaking a single block. To display multiple block breaks, you will have to use different breaker ids. Since this method is bound to player, it always uses a player breaker id, so you are limited to one break at a time.

**Comment by BNTFryingPan** [comment]
it shouldnt be too hard to make the method support this. the packet that gets sent to the player uses an entity id, but that id doesn't actually have to match an existing entity for the client to display it, so you could use the block location (compressed into a single integer obviously) as the entity id. although it might be better to have that id passed as a parameter, depends on how it gets implemented

**Comment by Shevchik** [comment]
Entity id being used as a key on a client is an implementation detail. Mojang can start using source entity by id any time, so directly passing id shouldn't be a part of API.

**Comment by TheFruxz** [comment]
> it shouldnt be too hard to make the method support this. the packet that gets sent to the player uses an entity id, but that id doesn't actually have to match an existing entity for the client to display it, so you could use the block location (compressed into a single integer obviously) as the entity id. although it might be better to have that id passed as a parameter, depends on how it gets implemented

Yes, as an optional parameter it would be optimal, then you can actually use the block-damage api for something properly ^^

**Comment by TheFruxz** [comment]
UPDATE: Changes of #5840 pending
