### ISSUE TITLE
console hex support giving me weird behavior

### ISSUE THREAD

**Issue by mrfloris** [PaperMC/Paper#5248]
```
Bukkit.getConsoleSender().sendMessage("§x§a§a§a§a§0§0Test"); # Works
Bukkit.getConsoleSender().sendMessage("§x§a§a§a§a§0§0§eTest"); # Breaks apart because of extra §e color code
```
<img width="365" alt="Screenshot 2021-02-25 at 15 04 14" src="https://user-images.githubusercontent.com/28841349/109164460-c208bc80-777a-11eb-9416-f91dcda65e23.png">

### What behaviour is expected:
<img width="943" alt="Screenshot 2021-02-25 at 14 55 29" src="https://user-images.githubusercontent.com/28841349/109163373-90dbbc80-7779-11eb-9d21-3b8f98700633.png">
<img width="324" alt="Screenshot 2021-02-25 at 14 56 20" src="https://user-images.githubusercontent.com/28841349/109163461-a81aaa00-7779-11eb-81f4-4e8415b93b2b.png">
<img width="483" alt="Screenshot 2021-02-25 at 14 56 26" src="https://user-images.githubusercontent.com/28841349/109163463-a8b34080-7779-11eb-87d7-aea964bf3335.png">

### What behaviour is observed:
<img width="1192" alt="Screenshot 2021-02-25 at 14 56 59" src="https://user-images.githubusercontent.com/28841349/109163613-cc768680-7779-11eb-89ca-e62958a9ce03.png">
<img width="414" alt="Screenshot 2021-02-25 at 14 57 07" src="https://user-images.githubusercontent.com/28841349/109163617-ce404a00-7779-11eb-8ef4-8b4f545c0a14.png">
<img width="958" alt="Screenshot 2021-02-25 at 14 57 18" src="https://user-images.githubusercontent.com/28841349/109163619-ced8e080-7779-11eb-8724-1787f75d76e9.png">
<img width="961" alt="Screenshot 2021-02-25 at 14 57 21" src="https://user-images.githubusercontent.com/28841349/109163624-cf717700-7779-11eb-9494-38a55dc62688.png">

### Steps/models to reproduce:
For example, in CMI using CMI as chat manager, I can enable custom join/leave msgs, and use hex colors. Mine for example look like these:
```
  FirstJoin: '{#Cerulean>} 1MB Server »{#Lochmara<}{#Feijoa} Welcome new player &6[playerDisplayName]{#Feijoa}
    to 1MoreBlock.com!'
  LogoutCustom: '{#Cerulean} - {#Feijoa}Player &l[playerDisplayName]&r {#Feijoa}left.'
  LoginCustom: '{#Cerulean>} 1MB Server »{#Lochmara<}{#Feijoa} Welcome back &6[playerDisplayName]
    {#Feijoa}❤'
  deathlocation: '{#Cerulean>} 1MB Server »{#Lochmara<}{#Feijoa} You died at x:&6[x]{#Feijoa},
    y:&6[y]{#Feijoa}, z:&6[z]{#Feijoa} in &6[world]'
```
Note: the > < within the hex color codes make it a gradient as seen in the first screenshot.

### Plugin list:
CMI

### Paper version:
```
> version
[14:59:24 INFO]: --------------------------------------------------
[14:59:24 INFO]: CMI plugin version: 8.8.1.5 SqLite
[14:59:24 INFO]: CMILib: 1.0.0.2
[14:59:24 INFO]: Server: Paper(497) 1.16.5-R0.1-SNAPSHOT
[14:59:24 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True
[14:59:24 INFO]: Modules -> 53 enabled 1 disabled: flightCharge
[14:59:24 INFO]: --------------------------------------------------
> ver
[14:59:26 INFO]: This server is running Paper version git-Paper-497 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[14:59:26 INFO]: Checking version, please wait...
[14:59:27 INFO]: Previous version: git-Paper-496 (MC: 1.16.5)
[14:59:27 INFO]: You are running the latest version
>
```

### Anything else:
Martin mentioned on Discord they wanted a bug report, because it shouldn't be the plugin's that need to get fixed, and it's likely a bug in paper's log event pattern converter. I hope this information for this one particular plugin helps. It's the easiest one for me reproduce at the moment.

**Comment by JRoy** [comment]
working on this

**Comment by mrfloris** [comment]
<img width="282" alt="Screenshot 2021-02-25 at 19 46 05" src="https://user-images.githubusercontent.com/28841349/109201497-32770400-77a2-11eb-949f-346761193869.png">
<img width="325" alt="Screenshot 2021-02-25 at 19 46 00" src="https://user-images.githubusercontent.com/28841349/109201498-330f9a80-77a2-11eb-8b0b-737678795dda.png">

This seems to be a good step forward, easier to read.

Not sure where the underlines come from ~ why it's a bit bold in the beginning and stops halfway through, but .. this is already a lot easier to work with at least.

Thank you.

**Comment by Proximyst** [comment]
@JRoy Willing to handle this too?

**Comment by JRoy** [comment]
I'm going to need the raw legacy text which inflicted that result

**Comment by mrfloris** [comment]
> I'm going to need the raw legacy text which inflicted that result

I do not know what that means, besides the stuff I've shared in the first post.

**Comment by JRoy** [comment]
I need to the pre-formatted string that looks like this: ![image](https://user-images.githubusercontent.com/10731363/109202781-5ec65c80-7771-11eb-966a-0b0515f6ed87.png)

**Comment by mrfloris** [comment]
> I need to the pre-formatted string that looks like this: ![image](https://user-images.githubusercontent.com/10731363/109202781-5ec65c80-7771-11eb-966a-0b0515f6ed87.png)

Okay, I will poke @zrips who can perhaps provide that.

Also, I noticed background highlighting happening for a /msg to player, when i use the hex `{#orange}`
<img width="1416" alt="Screenshot 2021-02-25 at 19 59 12" src="https://user-images.githubusercontent.com/28841349/109203162-1d02d980-77a4-11eb-84ca-bda09abd8b61.png">
<img width="1062" alt="Screenshot 2021-02-25 at 19 58 58" src="https://user-images.githubusercontent.com/28841349/109203174-1ffdca00-77a4-11eb-8772-0c14b9f932fd.png">

customalias.yml for /celebration command using hex colors
```
  celebration:
    Cmds:
    - asPlayer! warp celebration
    - asConsole! cmi msg [playerName] !{#Cerulean} •&l&m                                                &r{#Cerulean}•
    - asConsole! cmi msg [playerName] !{#magenta} The {#yellow}1MoreBlock.com Community{#magenta}
      is now TEN years old! We are celebrating our anniversary throughout the year.
      Check the {#orange}/forums{#magenta} for detailed information.
    - asConsole! cmi msg [playerName] !{#yellow} https://omgboards.com/threads/263614/
    - asConsole! cmi msg [playerName] !{#Cerulean} •&l&m                                                &r{#Cerulean}•
    - 'asConsole! cmi msg [playerName] !{#orange} Available commands:'
    - asConsole! cmi msg [playerName] !{#green} - /celebration
    - asConsole! cmi msg [playerName] !{#green} - /celebration lootbox
    - asConsole! cmi msg [playerName] !{#green} - /celebration mikey
    - asConsole! cmi msg [playerName] !{#green} - /celebration stick
    - asConsole! cmi msg [playerName] !{#green} - /celebration giveaway
    - asConsole! cmi msg [playerName] !{#green} - /celebration soulbind
    - asConsole! cmi msg [playerName] !{#green} - /celebration dropparty
    - asConsole! cmi msg [playerName] !{#green} - /celebration bedrocker
    - asConsole! cmi msg [playerName] !{#Cerulean} •&l&m                                                &r{#Cerulean}•
```

**Comment by JRoy** [comment]
In the meantime, what console are you using?

**Comment by mrfloris** [comment]
> In the meantime, what console are you using?

I honestly can't find evidence that it matters, it's the same on ubuntu, freebsd, macos. 
The info provided in this ticket looks the same for Terminal.app and iTerm.app with xterm-256colors on macOS Catalina for both local server on same machine and remote servers.

**Comment by JRoy** [comment]
@Proximyst and I have tested against again a bunch of color codes and tried to mimic the color codes you used with the config from CMI you provided and still cannot reproduce this bug. This is most definitely a terminal issue or CMI doing some crazy dumb shit with color codes which wouldn't shock me.

**Comment by Proximyst** [comment]
Issue is caused by GNU/screen. Broken with `screen` & `screen -U`; works fine with `tmux` & no terminal multiplexer with [alacritty terminal emulator](https://github.com/alacritty/alacritty) and `alacritty` terminfo (`gzip -9cf | base64`):

```
H4sIAAAAAAACA61Xa2xcRxU+szNOcJUopbSlcEVJgBtK1NR379yZu5vb5mE7wXb92NohmGyN7NpO
1smuY683iVM/kh+QovAqqJVoVUSrVrwFRVCBIKg8ChWPIqEi8RASIEElXkJFBX4UMOfMmd004IIQ
XGe+78w5M9/Mzsyde/JKsR22wxb4oNiyYaI6MVmfaTTOLLesrY3pem1mdqK6dbp2sjrROFEHEO4f
iBbQ45ytGogSvASug7V1HhBrZwEUbMAWr4DrcfQdcBO2LEIf9EMJ3oz2W+AI4jGYhUVYhnNon4cL
8F64B60PwyfgUeTH4IvwODwBT8H34UdY/w38Af4Ez6O1WaytbRE82jbk0NuvR75RNOcRiUTsErtF
pzgg+sWwGBVvFVOigvEalnlxSiyJs+I82u8W7xP3ibV1n4fEx13ks+Ki+Ib4nvih+Ln4tfijeF6o
HLfYnHtp7tpckOvIFZynLzeQG82Vc2O58dyX0fOV3Ndyl/SebNnfQQskWUpeIdcf/Up59YtE/t1z
nevz6lbP7XKnTFwtQ+z0/t4XKJfkIXm7nJTH5LxclOfkO+Td8gPyQflR+aj8gnxcflM+JX8gfyp/
KX8nn5N/lUptUlerQL1GvUFFqqD2qh5VUqNqXFXUnDqtVtXb1bvUPeoB9Yj6pPqcuqieUN9VT6uf
qF+o/+63PKOeVX9W7W2b265te1Ubef6Of5c/S23/2u9c29r//Jz3GhfavvV/UPvPT/uGTRuC8mHY
CJshKIcz4Vw+nMrCuTicqqNDH0XoCcpxH/KtWPoutXrjP3fogSuoNZY9saniq4hGPq66agUrXVj2
sTNjTwnLAARjcbYRghsirJkaQr7mWkVJsYJDx1mURQ30xOROqF+BrLQFCYGbyCjKdFIJyi0NnECs
mxpJlYRcr9h122Mqr7s5H0Udu8mu4kIE5W1zaOssqVL7YDd6+uEsrcYqBEMoP0TzjvNUuw3LMJYR
mrZZJUwdFhwWCeOIWtK6xGR0o2HJT82HaFHyWdzJhMszxEvE4+7JV4Jb+IdoN3VnVJo/t9Q0BppG
Z9PY2zRGmkZ/0+huGl1N42DToLFnaJkIzAyQc5JicbiUXwl3hlN3QDAZjOG6rrtQhUtnYgqClA7E
AIR7wrli2MANDqdxa8IsKEfks2Ejy4cZmQbNmM0YzYTNfDinw2Wsp1xP0DRspmgWwgx3sAfa3QnC
ldsP4+MTE0eOHD06M3Ps2PHj1WqtNjt74sTc3Px8vb6w0GicPHnq1OnTi4tnztx559LS8vLKyirt
xGFa2bTiEFd56AAWWlKdxau8MQeY3Ca2nG4nuWZaTlrUWLt9T7yrxHQb0zATnxjfLfVc8FxkjiPP
ec9+QnHSHM6wtmFtw9rGa/vz6LnguciM2sZrG69tvDa3yyxrW9a2rG29tvXa1mtbr229tvXa1mtb
r83tMs3amrU1a2uvrb229traa2uvrb229tp+tX27LGHthLUTp30rH0y8qaaobmdpr8NyFuVjnRib
Fopjk+iiootZUsSD5Q/5WJLxHVc/escu9yLExqyEO/CFiKJoJewI45vi0Q46qi8WSdaPBLfTaO4q
cuheYnfslwor4c1hQ7uBw2nnylvnKzbjOymicVN5eu5duLx7sk73fHRZ/+Ty/nj2awA5TLZuwRxJ
SUq+NsLLMOvaARFksB+zqRE4DBNQgRNwClbgbfBOeD/cBw/CR+BT8BhchK/Dt1329DN4Bn4Pz2H2
lBPt4krxcnG9CMWNQmOGtE/0iCFxSIxhdnRc1MUZcU7cJd4j7hUPiIcx+/mM+DyOLDGfa4dNmEle
BddAgHnda+EG2AkxpDiXvTibPhiCgzifccztqlDHzG4VZ3QB7oZ74X74EDwCH4NP46y+BF+FJzGr
exp+jPP6FfwWnoW/wN9A4sy2iGtEILbh3HaIDszfipi/dQnc/XxMu4/fKlqfBbruNH79xox3uG+e
c0db5+nK3OXWsfUpck5/NvGKZDJMlildfeHlr5kSJsNkmVLfhK+hhMkwWaaUSfdwEybDZJlSvr74
deEpxf6l9+9nc0q6m1WYDJNlSvnacyqWVSyrWFaxrOLfY8NN/G3kLw7TGoi/fwmTYbJMaVfro0gt
mRImw2SZUqKYXtoywr5RGD0IXXXoWoD9GgYWYGQaRvD/GoswsgDHu7s0QUJgCCxBijBIhYKDFByk
4CAFBzG4f7BbO0wcGofWIUZ7hga0w8ShcWgdYrSXRuylEXtpxF4asZdG7D9wUDtMHBqH1iFGB0cp
ipg4NA6tQ4yWhg9ph4lD49A6xOhwL/VFTBwah9YhRt9UoqIJEgJDYAlSqNcWF2GB4B/KX9f1yA0A
AA==
```

**Comment by mrfloris** [comment]
Thank you all for looking into it. I am already glad the §x stuff is all gone and I can read the console again.
That the underline or random bold stuff is left due to screen, so be it. At least we narrowed that down.
