### ISSUE TITLE
Issue with ChatControl-Red since Adventure update

### ISSUE THREAD

**Issue by ElBananaa** [PaperMC/Paper#5249]
Hey! I recently updated to the latest version of paper, and since, I noticed a few compatibility issues with ChatControl-Red. I tried to downgrade to the first version including adventure, and the issue is still there. Using the latest version of paper without adventure fixes the issues. I asked Kangarko (ChatControl author), and he asked me to open an issue here, so here I am.

### What behaviour is expected:
The plugin has a feature that allows us to remove player messages one by one by clicking on a "button" in the chat which worked perfectly before. Same thing with the purge command that allows us to remove messages sent by a specific player.

### What behaviour is observed:
None of these features work anymore. For the remove button, nothing happens when you click on the it in the chat to remove a message. (Clickable messages still work perfectly tho, so I guess this is unrelated.) Same thing with the purge command: When you use the command, nothing happens.

### Steps/models to reproduce:
Simply install ChatControl-Red, ProtocolLib and Vault on a server, enable the channel feature in the plugin's configs, and try to remove a message.

### Plugin list:
[ChatControl-Red 10.2.7](https://github.com/kangarko/ChatControl-Red), Vault 1.7.3, ProtocolLib 4.6.0 and LuckPerms 5.2.118 (I have the permissions to use both features)

### Paper version:
```
This server is running Paper version git-Paper-497 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```

### Anything else:
I also tried on 3 different servers: My prod server, my test server and a local test server, and this issue happens on all of them when using paper with adventure. The prod and the test servers are under java 11, and the solo test server is under java 8.
The 3 servers are all up-to-date.

Thanks! :)

**Comment by Proximyst** [comment]
Premium plugin; unable to attempt reproduction. Author will have to report the issue with actual code or details.

**Comment by kangarko** [comment]
@Proximyst source of ChatControl is here: https://bitbucket.org/kangarko/chatcontrol-red/src/master/

I uploaded the jar for you here: https://bitbucket.org/kangarko/chatcontrol-red/downloads/ChatControl-Red-10.2.7.jar

The default config has the [X] feature out of the box if you have operator status.

We do all the remove magic in the model package in Packets class by evaluating if the JSON component contains our hidden uuid.

Thanks!

**Comment by MiniDigger** [comment]
"by evaluating if the JSON component contains our hidden uuid."

I expect that to be broken by the conversion internally to adventure

**Comment by kashike** [comment]
There's your issue: https://bitbucket.org/kangarko/chatcontrol-red/src/5fd47c1862a3acdf913a2b7538600affd48eb0fe/src/main/java/org/mineacademy/chatcontrol/model/Packets.java#lines-197:272

**Comment by kangarko** [comment]
I have no idea how to fix that if you are removing component parts

**Comment by kashike** [comment]
Removing your repository from public view is a great way to not get help fixing this.
