### ISSUE TITLE
Line-edit feature ^U does not work on Paper console in screen

### ISSUE THREAD

**Issue by SlimeDog** [PaperMC/Paper#5250]
### What behaviour is expected:
Line-edit feature ^U should work on the Paper console.

### What behaviour is observed:
Line-edit feature ^U does not work on the Paper console when run under Lunix `screen`. It works as expected on the Spigot console. Other control sequences -- ^W for example -- work as expected. No changes to the system, other that switching between Paper and Spigot.

### Steps/models to reproduce:
- Start Paper server in `screen`. Type a line, then try to erase it with ^U. The control-character is echo'd, but does not edit the line.

### Plugin list:
Large -- this is a plugin test server -- but irrelevant.

### Paper version:
```
> version
[08:33:37 INFO]: This server is running Paper version git-Paper-497 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[08:33:37 INFO]: You are running the latest version
```

**NOTE**: The above was updated to remove incorrect references to ^W and to better describe the situation.

**Comment by electronicboy** [comment]
os? running in screen, etc?

paper uses jline, which is what would need to implement these features afaik to work, make sure that the terminal features have hooked properly (you don't see a warning to the contrary), etc
if jline doesn't support this or your terminal doesn't work properly with jline, there is very little we can do

**Comment by electronicboy** [comment]
just tested, works fine here, sounds like a platform/terminal issue

**Comment by SlimeDog** [comment]
Server: CentOS (Linux)
Server shell: /bin/bash shell running in **screen**
Client terminal: Mac Terminal

Are you suggesting that Spigot does not use **jline** or uses it in a different way?

**Comment by electronicboy** [comment]
craftbukkit uses a 5 year old version of jline which is dumber but more forceful about supporting things, whereas the newer version seems to be a bit more capable of "failing gracefully" at the caveat that it seems to just kick itself whenever it runs in specific environments more easily vs the older mechanism

**Comment by SlimeDog** [comment]
"Failing gracefully" is different from "ignore line-edit sequences". Is there any configuration I can use to correct this? It's rather annoying, plus there is the **Wuff --- Wuff!** thing.

**Comment by electronicboy** [comment]
Not too sure, you didn't answer my question about if it said the features have been disabled or not, are you using any flags? etc

would potentially need to try and speak to the jline people unless paper is disabling it earlier for some reason

**Comment by SlimeDog** [comment]
Using flags for which application, please? No errors or warnings related to jline in the console/log. No indication that features are disabled in the console/log.

**Comment by SlimeDog** [comment]
screen -dmS sp-server java -Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dfile-encoding=UTF-8 -jar paper-1.16.5-497.jar nogui

Then, I am running the screen: `screen -D -r sp-server`

**Comment by electronicboy** [comment]
if you're able to build custom jars, probably worth trying to bump jline manually, looks like they've been busy and were a 'little' outdated

**Comment by SlimeDog** [comment]
I'll wait for paper builds to catch up. Thanks.

**Comment by SlimeDog** [comment]
Thanks. I'll have to wait for paper builds to catch up. May I suggest that would be a good thing (tm)?

**Comment by zachbr** [comment]
Alright so on a fresh copy of CentOS 7, both ^W and ^U work fine outside of screen.
Within screen, ^W seems to still work but ^U does not. With ^U it just echos.
In Tmux, both ^W and ^U seem to work.

So I'm not sure exactly what screen does, or what differences there are, that cause this. I can kick the tires on bumping jline but I don't know that it'll fix anything.

Edit for myself: check if this continues on the most recent release of screen, CentOS is very out of date with the current screen release. `Screen version 4.01.00devel (GNU) 2-May-06`

**Comment by SlimeDog** [comment]
Agreed. I was mistaken: ^W works, ^U does not, inside screen with Paper. Both work with Spigot.

CentOS Linux release 7.9.2009 (Core) server:
screen 4.1.0 0.26.20120314git3c2946.el7

MacOS BigSur client 11.2.1:
Terminal version 2.11

**Comment by SlimeDog** [comment]
In the interim, I can change my behavior to use (multiple) ^W instead of my habitual ^U. Alternatively, I can try to make fewer typing mistakes, but that's less likely.

**Comment by zachbr** [comment]
10 days later and I can't reproduce this any longer. Not entirely sure why.
^U works fine, clears the input as I'd expect it to.

I haven't updated screen, transaction history is empty except for the initial install. Old paper I tested against doesn't give me any problems. New paper jar doesn't give me any problems.
Tested in conhost and windows terminal in 20H2 and the macOS Terminal on Big Sur 11.3 (20E5196f)

I don't really have an answer but I can't reproduce. Pulling myself off of this one.

**Comment by electronicboy** [comment]
tested on a few setups and it worked fine, these control functions seem to be handled further down than paper by the terminal itself, even just raw stdin hijacking works with these control characters as it just basically sits in the buffer until you send it

**Comment by SlimeDog** [comment]
What more information can I provide? ^U continues to fail in my environment with Paper. It works fine in exactly the same environment with Spigot (I can switch between the two easily). And it works fine in the Linux shell and elsewhere. Everything related to this stack is up-to-date (so Spigot and Paper have been updated since the initial report, everything else the same).
```
$ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
```
```
$ java -version
java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode
```
```
> version
[16:52:31 INFO]: This server is running Paper version git-Paper-529 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[16:52:31 INFO]: You are running the latest version
```
```
>version
[16:52:46] [Server thread/INFO]: This server is running CraftBukkit version 3018-Spigot-db99f82-a021e33 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[16:52:46] [Server thread/INFO]: You are running the latest version
```

**Comment by Proximyst** [comment]
I think this is more of an issue with `screen` in general, really. See also #5253.

Not so sure this is something for us to look into beyond attempting to update JLine, really...

**Comment by SlimeDog** [comment]
> I think this is more of an issue with `screen` in general, really. See also #5253.
> 
> Not so sure this is something for us to look into beyond attempting to update JLine, really...

Agreed. Paper in `screen` is the only place in my environment where `^U` fails to represent correctly. I have offered to test anything that will contribute to isolating and resolving the issue.

**Comment by electronicboy** [comment]
input handling is weird, because I mean, who knows how the entire process works...

The thing is that aspects like ctrl-u are handled before paper even gets it, which screams that this is basically caused by something being slammed into the wrong mode somewhere or is being processed improperly elsewhere, investigating issues related due to specific shell environments, especially deeper ones, are pretty bleh, especially when they're not easily reproducable; upgrading jline may help, but, I have some doubts there...

**Comment by SlimeDog** [comment]
This issue is easily reproducible. It occurs always. Are there negative impacts anticipated by updating JLine? Is there something I can test?

**Comment by electronicboy** [comment]
Well, somebody would need to actually perform the update, it's just not as trivial as bumping the version

**Comment by electronicboy** [comment]
1.17.1 - 351
Screen version 4.08.00 (GNU) 05-Feb-20

Cannot reproduce

**Comment by electronicboy** [comment]
See #6829 for updated jline

**Comment by SlimeDog** [comment]
Unfortunately, `screen version 4.01.00devel (GNU) 2-May-06` is the "up-to-date" on CentOS, and I do not have a build environment there. :(
I hope the `jline` update will resolve the issue. In the interim, I'll create a Linux dev environment, and build and test a Linux `screen 4.08.00`. It is a certainty that CentOS is not going to update it.

**Comment by SlimeDog** [comment]
OK, I built a Linux version of `screen 4.08.00`. I confirm that the error does not exist with that executable. Nevertheless, it would be a kindness to update `jline`, since CentOS is not going to change the "up-to-date" of `screen` anytime soon. Anyone who relies on their provider for Linux executables is not going to be able to duplicate my effort.

**Comment by electronicboy** [comment]
have you tried the test build on the PR I said to see?

**Comment by SlimeDog** [comment]
> have you tried the test build on the PR I said to see?

The Paper PR above does not resolve the problem. Reverted to `screen 4.01.00devel`.

**Comment by e-im** [comment]
This isn't an issue paper will (or really has any sane means to) solve; just use tmux or a more up-to-date version of screen, as you mentioned.  This is a screen bug.
