### ISSUE TITLE
screen misparses our hex colour output

### ISSUE THREAD

**Issue by Proximyst** [PaperMC/Paper#5253]
### What behaviour is expected:

The `screen` output to be correct, as in equal to that of running the server without any terminal multiplexer, as well as with tmux:

`tmux`
![tmux demonstration](https://uwu.whats-th.is/6XZbMEy.png)

Purely `alacritty` with `alacritty` in `$TERM`
![alacritty demonstration](https://girlsare.life/3qG28qG.png)

### What behaviour is observed:

`screen` misinterprets the output somehow and breaks the output. This applies to both UTF-8 mode (`-U` option), as well as non-UTF mode (no `-U`).

![screen demonstration](https://uwu.whats-th.is/2eeK533.png)

### Steps/models to reproduce:

Send a message with RGB colours to the console. The colours in the examples are `#a2aeab` and `#ff681f`. I used EssentialsX nicknames & chatted to get the colours into console.

### Plugin list:

None are necessary, however for the sake of setting a good example:

```
Plugins (16): BlockLocker, ChatItemDisplay, Essentials, EssentialsSpawn, Gaea, grakkit*, LuckPerms, PlaceholderAPI, ProtocolLib, ProxiDebugPlugin, ServerUtils, spark, Stress, Terra, Vault, WorldEdit
```

### Paper version:

```
[20:40:27 INFO]: This server is running Paper version git-Paper-498 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[20:40:27 INFO]: Checking version, please wait...
[20:40:28 INFO]: Previous version: git-Paper-484 (MC: 1.16.5)
[20:40:28 INFO]: You are running the latest version
```

### Anything else:

```console
$ screen -v
Screen version 4.08.00 (GNU) 05-Feb-20
$ tmux -V
tmux 3.1c
$ alacritty -V
alacritty 0.7.1
$ zsh --version
zsh 5.8 (x86_64-unknown-linux-gnu)
$ java -version # Installed with SDKMAN!
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
$ uname -r
5.10.13_1
```

This only applies to the console; the log file and ingame chat are both correct.

---

This issue is rejected by the Paper team and is only present to let others know of the issue, such that someone else potentially PRs a workaround that must not affect the other correct cases.

**Comment by Owen1212055** [comment]
Can someone please see if this is still an issue with adventure's new hex color console logic?

**Comment by pop4959** [comment]
I can confirm that this is fixed now with the new Kyori ANSI text serializer.
