### ISSUE TITLE
Anti-Xray doesn't work properly

### ISSUE THREAD

**Issue by krolik-exe** [PaperMC/Paper#5254]
### What behaviour is expected:
Xray not working

### What behaviour is observed:
Xray working

### Steps/models to reproduce:
Set engine-mode to 1 in paper.yml
Install a plugin named AdvancedXray (forge), https://github.com/MichaelHillcox/XRay-Mod/ , and get an ore in your hand that is hidden in anti-xray config , activate xray{need to check your bindings , because on every computer it's different) , open it's menu on 
> g

and select 

> Add block in hand 

and set the distance to 64
Then you should see the ore that you choosed, being highlighted

### Plugin list:
No need to put them here , because it happens without them too

### Paper version:
Git-Paper-498
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by electronicboy** [comment]
anti xray only hides blocks which aren't exposed to air, use mode 2 to basically obfuscate the world so that it can create more noise, but, generally, there's very little you can do about x-ray completely without modifying how the client/server works pretty much

**Comment by stonar96** [comment]
Furthermore Anti-Xray only hides blocks up to a certain height that can be configured with the `max-chunk-section-index` setting (see docs).
