### ISSUE TITLE
Per player mob spawns stops all hostile mobs spawning in the nether.

### ISSUE THREAD

**Issue by NachoToast** [PaperMC/Paper#5255]
Spawns, spawn eggs, /summon, any hostile mob in the nether is instantly removed upon manifestation. Paper version 498, Minecraft 1.16.5, API Version R0.1-Snapshot.

**Comment by electronicboy** [comment]
you failed to fill in the template
per-player mob spawning also does not touch spawn eggs or /summon in any capacity, that would suggest a plugin or something is removing them

**Comment by apieceofbaggage** [comment]
@NachoToast 
I had the same issue as you, when I enabled per-player-mobs my Nether, and End for that matter, each began acting as peaceful dimensions. I was able to fix it by just doing "/difficulty hard" in each dimension.

**Comment by NachoToast** [comment]
@apieceofbaggage Thanks for the help, I'll try that out. :)
