### ISSUE TITLE
Many items make many problems

### ISSUE THREAD

**Issue by TheFruxz** [PaperMC/Paper#5256]
### What behaviour is expected:
A running server

### What behaviour is observed:
An crashing / lagging server

### Steps/models to reproduce:
do multiple times: /give PLAYER minecraft:snowball 20000000

### Plugin list:
no plugins

### Paper version:
1.15.5-R0.1-SNAPSHOT git-Paper-354

### Anything else:
Giving players to many items (in to quick time) make server lagging, up to crashing (maybe item inventory store problem)
Plugins via API can also crash server by giving player too many items in to short time (like auto-clicker at not good (or dev-version) shop system)

**Comment by Proximyst** [comment]
Don:t do that then

**Comment by TheFruxz** [comment]
TV commercial: 'You don't want viruses on your Windows computer? ... Then don't download viruses!'

**Comment by JRoy** [comment]
TV commercial [https://www.youtube.com/watch?v=FqWgTM4di4s](https://www.youtube.com/watch?v=FqWgTM4di4s)

**Comment by TheFruxz** [comment]
In Germany we have 'Nicer Dicer' for that: https://www.youtube.com/watch?v=lmTF5_KJw9A

**Comment by TheFruxz** [comment]
And that of course: https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by electronicboy** [comment]
Ticking a metric fuckton of entities takes a metric fuckton of time, not
really sure what you expect us to do or say about that many entities. Maybe
wait until we have quantum computers on every desk.
