### ISSUE TITLE
Crash with console spam (luckperms ?)

### ISSUE THREAD

**Issue by darkenimaX5** [PaperMC/Paper#5262]
Hello, sorry for my bad English I am French.

I have a problem, my server crashes several times a day for no obvious reason (too many monsters, ect)
and I still have the same log spam pattern before the crash. So I publish it here, thank you in advance for your help.

[2021-02-26-4.log](https://github.com/PaperMC/Paper/files/6051636/2021-02-26-4.log)

**Comment by electronicboy** [comment]
missing templates, unsupported version
