### ISSUE TITLE
PlayerTradeEvent cannot be cancelled.

### ISSUE THREAD

**Issue by ArnaudLier** [PaperMC/Paper#5263]
### What behaviour is expected:
___PlayerTradeEvent can be cancelled properly.___

### What behaviour is observed:
___PlayerTradeEvent cancellation has no effect.___

### Steps/models to reproduce:
- Use this EventHandler: ![image](https://user-images.githubusercontent.com/32982428/109343209-43d91280-786d-11eb-8254-55691defe0fd.png)
- Trade with a villager
- See that you can still trade no matter you cancel PlayerTradeEvent or not.

### Plugin list:
___ViaVersion, ViaBackwards and my plugin.___

### Paper version:
___This server is running Paper version git-Paper-499 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) You are running the latest version.___

**Comment by ArnaudLier** [comment]
It seems that the cancellation is only half done: I don't receive the XP and the uses are not updated but I can still exchange the item.

**Comment by 3meraldK** [comment]
fix that pls, confirming

**Comment by electronicboy** [comment]
Please don't bump PRs unless you have something useful to add, PRs welcome.

**Comment by Machine-Maker** [comment]
Nope, this is def still an issue. (with a fix waiting in the wings)
