### ISSUE TITLE
API to make ItemStacks glowing (without adding real enchants)

### ISSUE THREAD

**Issue by Trigary** [PaperMC/Paper#5274]
**Is your feature request related to a problem? Please describe.**
I want to make items (`ItemStack` / `ItemMeta`) glowing without changing anything else.

**Describe the solution you'd like**
Addition of two methods: `ItemMeta#setShiny(boolean)` and `ItemMeta#isShiny()`.
The setter shouldn't apply any real enchantments and definitely shouldn't add `ItemFlag.HIDE_ENCHANTS`: the item might already have enchantments (or if not, it might have enchantments in the future), so adding that flag would be bad. Adding a real enchantment is also bad since I don't want enchantments to show up under `#getEnchantments()` just because I called `.setShiny(true)`.
The return value of `isShiny()` should stay the same prior to and after serialization/deserialization, whatever that value might be. So in other words, this feature should support serialization.

**Describe alternatives you've considered**
Solutions that rely on `ItemFlag#HIDE_ENCHANTS` are possible but are complicated if we want to do it right: we have to keep in mind that items can get enchanted via commands, via enchanting tables, by other plugins. So we have to remove the `ItemFlag` when necessary, etc.
@HexedHero claims to achieve this by registering a custom `Enchantment`, but that's not supported by the Bukkit API, therefore is a non-solution.

**Additional context**
kashike believes implementing this is possible.

**Comment by ghost** [comment]
.addenchant lure 1
.addflag hideenchants

**Comment by Machine-Maker** [comment]
This looks like it *used* to be possible by setting the `Enchantments` key on an items tag to an empty NBTTagList, but it doesn't look like that is the case anymore. 

I don't know exactly what the client uses to determine if it should display it as glowing.

**Comment by Draycia** [comment]
Looks like the effect is possible via setting an invalid enchantment.
`/give @s minecraft:diamond_sword{Enchantments:[{id:"",lvl:0}]} 1`
The lore is rendered exactly the same as a vanilla sword, but with the glowing effect and name change.

Something thing to note though is that setting Enchantments to an empty list or with an invalid enchantment causes the item to be unenchantable via enchanting tables. Anvils however work perfectly fine and as expected from my minimal testing. Though this behaviour has remained consistent with the old method prior to 1.16

**Comment by Machine-Maker** [comment]
I wonder if the “unenchantable-ness” can be fixed on the server side or not? 

A potential problem with using an invalid enchant, might be that plugins can add their own enchantments which might use the same ID. Not super familiar with the enchantment system, this is just my initial reaction.

**Comment by Draycia** [comment]
The ID used can be blank, I don't suspect plugins will be adding ID-less enchants to items. Any use case for that I can think of would be possible through other already supported means, PDC etc.

Edit, as for the inability to be used in enchanting tables, that's likely to do with the server thinking the item's already enchanted (albeit an invalid enchant), sounds plausible that making it ignore blank ID'd invalid enchants would resolve that part.

**Comment by Machine-Maker** [comment]
Oh yeah, I agree. I would hope plugins aren't adding ID-less enchants, but some plugins do stupid things.

**Comment by kashike** [comment]
This will be fixed with the `minecraft:enchantment_glint_override` component being introduced in Minecraft 1.20.5.

**Comment by lynxplay** [comment]
Closing this, 1.20.5 is out in expeimental phase and ItemMeta#setEnchantmentGlintOverride
