### ISSUE TITLE
why i need this useless check???

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5275]
i wonder why you implement this garbage check for java version?
![Screenshot_1](https://user-images.githubusercontent.com/66251951/109399541-1d3dd900-794c-11eb-97cf-a5259d462f58.png)

on the vanilla, bukkit and spigot the console looks very clean on paper it's full of useless garbage

**Comment by Proximyst** [comment]
That's for helping us in `#paper-help` when people ask for help regarding anything from plugins to performance issues. It's helpful.
