### ISSUE TITLE
Allow player packets from non ticking chunks

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5277]
**Is your feature request related to a problem? Please describe.**
My server has many players, so to keep the tps at 20 I need to have ticking view distance at 3 and notick view distance at 7, when I set the player view distance in spigot.yml to above 48 it is capped to 48 by the view distance, I would like for players to be able to see eachother from further away than 48 blocks without having to increase tick view distance (which would increase lag)

**Describe the solution you'd like**
Track player entities outside of ticking chunk range

**Describe alternatives you've considered**
Increasing tick view distance, but it would cause my server to lag

**Additional context**

**Comment by MiniDigger** [comment]
I don't think thats possible.
to be able to see players, they need to be ticked/tracked.

**Comment by ghost** [comment]
> I don't think thats possible.
> to be able to see players, they need to be ticked/tracked.

https://github.com/PaperMC/Paper/pull/5308

**Comment by Owen1212055** [comment]
Can be closed, see: https://github.com/PaperMC/Paper/pull/5308#issuecomment-1048420715
