### ISSUE TITLE
Links are unclickable in Paper 1.16.5

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5279]
### What behaviour is expected:
___What you expected to see___
"Are you sure you want to open the following website?" dialogue appear

### What behaviour is observed:
___What you actually saw___
No "Are you sure you want to open the following website?" dialogue.

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
1. Enter a valid URI into chat, e.g "https://www.google.com" and post it
2. Attempt to click on the message and unlike in previous versions it will not give you the "Are you sure you want to open the following website?" dialogue, which is usually expected.

### Plugin list:
___A list of your plugins___
None

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
[15:09:44 INFO]: This server is running Paper version git-Paper-503 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[15:09:44 INFO]: You are running the latest version

### Anything else:
___Anything else you think may help us resolve the problem___
Running /say in Console with the URI and trying to click on it in the client works as expected, but not when posted as a message in chat.
I used a Paper 1.15.2 instance to test if this unexpected behaviour occurred in previous versions of Minecraft (as someone had said it seemed like a recent issue) and it DID give me the "Are you sure you want to open the following website?" dialogue when I clicked on the message.

**Comment by HexedHero** [comment]
Can confirm

**Comment by kezz** [comment]
Can confirm this works fine pre-Adventure (418)

**Comment by Titaniumtown** [comment]
I can reproduce.
