### ISSUE TITLE
Fox "Sleeping" NBT data reverts when NoAI is 1

### ISSUE THREAD

**Issue by Sukasa** [PaperMC/Paper#5283]
### What behaviour is expected:
Fox with NoAI and Sleeping data set to 1 stays sleeping at all times

### What behaviour is observed:
After update from older version (1.16.4 b276) to Paper 503, fox with NoAI tag set to 1 and Sleeping tag set to 1 immediately reverts sleeping tag after a couple seconds .

### Steps/models to reproduce:
Coax fox onto bed or use /tp to move fox.  Set NoAI = 1 and Sleeping = 1 via /data

### Plugin list:
FastLeafDecay

### Paper version:
503

**Comment by aurorasmiles** [comment]
We experienced a similar issue recently after updating, I'm not sure anymore which version it was exactly

**Comment by Machine-Maker** [comment]
~~I'm unable to reproduce this (unless I'm doing something wrong).~~
I placed a bed, ran `/summon minecraft:fox ~ ~ ~ {NoAI:1b,Sleeping:1b}` and the fox stayed sleeping w/no ai.

Oh ok. I tried it w/a fox from a spawn egg, and got it to happen. So yeah, confirmed this.

**Comment by NoahvdAa** [comment]
Can't reproduce on 1.19. Tried /summon, /data merge and spawn eggs with pre-filled NBT and the fox always stayed asleep.
<img width="848" alt="image" src="https://user-images.githubusercontent.com/44026893/183269592-024036e0-4d1c-4fae-b680-4c376ceb1574.png">

If this issue still occurs for you on a supported version (currently 1.19), please comment on this issue or create a new one.
