### ISSUE TITLE
Can't change difficult in world_the_end

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5286]
### What behaviour is expected:
I execute command /difficult hard in end, and the difficulty of end is supposed to switch to HARD.

### What behaviour is observed:
then i execute command /difficult, it says the difficulty now is EASY.

### Steps/models to reproduce:
1. enter world_the_end
2. execute /difficulty  `output: easy`
3. execute /difficulty hard  `output: swithced to hard`
4. execute /difficulty  `output: easy`

### Plugin list:
no plugin.

### Paper version:
git-paper-469(MC:1.16.5)

### Anything else:
it is updated from 1.16.4 to 1.16.5

**Comment by Ghost007CZ** [comment]
Can confirm on the latest build.

**Comment by embeddedt** [comment]
This is an upstream bug AFAIK: https://hub.spigotmc.org/jira/browse/SPIGOT-6330

I would agree that it's quite confusing - hopefully it gets fixed soon.
