### ISSUE TITLE
ProjectileLaunchEvent captures player state after launch, not before and cancelling does not revert Inventory

### ISSUE THREAD

**Issue by Cryptite** [PaperMC/Paper#529]
### Description of issue:
With 1 ender pearl in hand, throw it and note that inspecting Player.getInventory().getItemInMainHand(); returns AIR, not a pearl.

It should be extended to note that cancelling this event does _not_ cancel the item in the inventory being lost. It cancels the projectile firing, but not the loss of the item in the inventory.

### Paper build number:
953

**Comment by aikar** [comment]
How did it behave in 1.10? If this is a behavior change, ensure you file it on Spigot too.

**Comment by Cryptite** [comment]
In 1.10, the state of the Player's inventory was prior-to the launch, however, cancelling the event has _never_ reverted the inventory.

**Comment by Cryptite** [comment]
Added to Spigot Issues: https://hub.spigotmc.org/jira/browse/SPIGOT-2879

**Comment by zachbr** [comment]
Spigot took care of this by the looks, which is perfect as it eliminates any ambiguity between our implementation and theirs.

Update Paper for its inclusion.
