### ISSUE TITLE
Lava blockdata shows an incorrect block state

### ISSUE THREAD

**Issue by Owen1212055** [PaperMC/Paper#5291]
Lava with level of 6 incorrectly displays as 6 when using BlockData#getAsString.
![image](https://user-images.githubusercontent.com/23108066/109566203-8b4fe080-7ab1-11eb-8d5a-973b7e66068a.png)

![image](https://user-images.githubusercontent.com/23108066/109566961-9a835e00-7ab2-11eb-98e6-a7fdfbdf90ad.png)

### What behaviour is expected:
It should show as 6.

### What behaviour is observed:
It is shown as 2.

### Steps/models to reproduce:
Place down lava, find a lava block with level of 6.
```java 
System.out.println(block.getBlockData().getAsString());
```

### Plugin list:
Personal Plugin

### Paper version:
```
[17:38:45 INFO]: Checking version, please wait...
[17:38:45 INFO]: Previous version: git-Paper-457 (MC: 1.16.5)
[17:38:45 INFO]: You are running the latest version
```

### Anything else:

If it helps, I can confirm that this was an issue on June 10th, 2020 so this is not due to any recent changes.

**Comment by Chew** [comment]
> "latest is not a valid version"

I assume this was tested on build 506?

**Comment by Owen1212055** [comment]
> > "latest is not a valid version"
> 
> 
> 
> I assume this was tested on build 506?

My bad, yes. This was on build 506.

**Comment by Black-Hole** [comment]
You're mixing fluid data with block data. For lava fluid the "level" is what you're expecting. For the lava block the "level" is the distance to a source block. See also: https://minecraft.gamepedia.com/Lava#Fluid_states and https://minecraft.gamepedia.com/Lava#Block_states

Spigot doesn't offer an API for fluids yet.

**Comment by HexedHero** [comment]
> You're mixing fluid data with block data. For lava fluid the "level" is what you're expecting. For the lava block the "level" is the distance to a source block. See also: https://minecraft.gamepedia.com/Lava#Fluid_states and https://minecraft.gamepedia.com/Lava#Block_states
> 
> Spigot doesn't offer an API for fluids yet.

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/data/Levelled.html

**Comment by electronicboy** [comment]
which exposes the block level, not the "fluid" level, as blackhole said

**Comment by Owen1212055** [comment]
I see, I didn't know there was fluid data. Thank you for the brilliant explanation. I would also mark this as "not an issue" and close it.
