### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by Sckaletz** [PaperMC/Paper#5292]
### What behaviour is expected:
Single messages

### What behaviour is observed:
Double messages
![unknown](https://user-images.githubusercontent.com/6684408/109656940-3cfc1980-7b65-11eb-9f44-328d2124669d.png)
![unknown2](https://user-images.githubusercontent.com/6684408/109656943-3ec5dd00-7b65-11eb-860d-17aff58f01f3.png)

### Plugin list:
DeluxeChat v1.16.2
MarriageMaster v2.2.11

### Paper version:
git-Paper-507 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by ghost** [comment]
The chat system changed in the last update, go back to a build or wait for the plugin creator to update.

**Comment by JRoy** [comment]
> The chat system changed in the last update, go back to a build or wait for the plugin creator to update.

No, this is a Paper bug and will be fixed by Paper. Please reopen the issue.
