### ISSUE TITLE
Sign::line(int) returns nested TextComponent

### ISSUE THREAD

**Issue by ken-kentan** [PaperMC/Paper#5296]
### What behaviour is expected:
Should return none nested TextComponent.

### What behaviour is observed:

![2021-03-03_17 32 46](https://user-images.githubusercontent.com/10807357/109777817-773de780-7c47-11eb-9244-b14106c2f435.png)

**Sign::line(0)**

```
TextComponentImpl{content="", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[TextComponentImpl{content="[有料リージョン]", style=StyleImpl{color=NamedTextColor{value="#ffaa00"}, obfuscated=false, bold=false, strikethrough=false, underlined=false, italic=false, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}]}
```

### Steps/models to reproduce:

1. Create sign in old build(before paper-1.16.5-474)
2. Update paper to latest.
3. it will happen.

### Paper version:

`This server is running Paper version git-Paper-509 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

**Comment by Proximyst** [comment]
Works as intended.
