### ISSUE TITLE
Chunk unloading seems broken

### ISSUE THREAD

**Issue by martijnrondeel** [PaperMC/Paper#53]
This morning I started my server and after about 10 minutes with 20 players online, according to Essentials' `/lag` command, around 3k chunks were loaded. I've got the render distance set to 6, which would mean 12*12 chunks are loaded for every player which comes close to the 3k Essentials reports.

I just checked on my server again after a lot of lag reports and Essentials reported 9k chunks being loaded, with only 24 players. I had this same issue yesterday too (except the player count was 29 and the chunks loaded was 15k) but thought updating Paper to the latest version (#450) would maybe solve it, sadly it didn't :(

So it seems the number of chunks loaded slowly increases which causes massive lag eventually because of all the entities that remain active and need to be ticked.

**Comment by zachbr** [comment]
Is this issue still relevant? Getting better, getting worse? Please test on latest and let us know.

**Comment by martijnrondeel** [comment]
~~Using latest and it seems to be fixed now, will report if it 'comes back' again.~~

Still relevant in build 523.
Seems fixed in build 531, see below.

**Comment by martijnrondeel** [comment]
EssentialsX is still reporting a very large amount of chunks is loaded (15k), with 35 players online (render distance = 6, should be ~6k chunks total), however @aikar's [timings](http://timings.aikar.co/v2/?id=bc2d415d9b2d4064aa2d64546e7b6aab) says only around 6k chunks are loaded.

Might be something faulty is going on with EssentialsX' chunk counting?

As you can see in the timings my server is doing an absolute crap job too (8tps in the end) with ~30 players. I gave it a restart though, around 30 players came right back, and the TPS is at a stable 20 again, however this gets worse and worse within an hour and a restart is needed again :(

**Comment by aikar** [comment]
Be sure you're on a minimum of build 521, or you will have unload issues.

**Comment by martijnrondeel** [comment]
I used build 523 for the timings report.

**Comment by aikar** [comment]
be sure you're not using dynmap,
https://github.com/webbukkit/dynmap/issues/1916

dynmap is causing extreme issues atm and is the suspected cause.

**Comment by martijnrondeel** [comment]
Nope, not using dynmap, will add list of my plugins in a moment if that helps.

**Comment by martijnrondeel** [comment]
I'm using build 531 and it seems to be better now. Running the server for 3 hours now, I've got 29 players online and EssentialsX reports ~5k chunks loaded total, which seems right (no horrible TPS either!). Then I kicked all players and the chunk count went down to ~1k (presumably active spawn chunks?), so it properly unloaded them.

**Comment by cybertiger** [comment]
Might be relevant, I have seen fire spread in the nether cause issues with unloading nether chunks (I was using worldborder to pregenerate the nether, and was stuck with around 90,000 chunks loaded after a few minutes generating.).

**Comment by zachbr** [comment]
While we are still tracking down the many new causes of random chunk loading, the overall general issue of them not unloading ever should be resolved.
