### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#530]
do you think you can add this: https://github.com/TacoSpigot/TacoSpigot/blob/master/Paper-Server-Patches/0007-Optimize-armor-stands.patch

just for me :]

**Comment by PhanaticD** [comment]
no input wanted I have the final say

**Comment by RhvsW** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by AlfieC** [comment]
yes

**Comment by MrPowerGamerBR** [comment]
I wonder why this wasn't added yet, come on, it is a feature request by @PhanaticD!!11!

**Comment by aikar** [comment]
Not really a fan of something so specific that almost no one would want.

An API to control AS movement, and let a plugin control if that specific AS should skip movement? sure

**Comment by aikar** [comment]
In my view, we shouldn't litter up peoples config files with extreme options that will confuse them.

**Comment by PhanaticD** [comment]
Its not like they will be scarred for life if they look in their config and see one more value.. and it would be hugely beneficial to me as well as anyone else who has a server where armor stands are able to be used in mass.

**Comment by aikar** [comment]
I'm saying it should be an API, not a config option. Then write a plugin to turn it off.

**Comment by PhanaticD** [comment]
Oh okay well I have no idea how to write spigot API, I was hoping this would be accepted since it was already done and there would be no effort really needed to add it besides probably moving things around

**Comment by PhanaticD** [comment]
soooo I guess this API isnt going to happen any time this year

**Comment by zachbr** [comment]
Probably not, we're pretty busy. To be frank, this is just not a priority compared to the other issues currently open.

You know exactly how it could be implemented immediately, and that isn't by complaining.

**Comment by PhanaticD** [comment]
how?

**Comment by zachbr** [comment]
Set `armor-stands-do-collision-entity-lookups` to false in paper.yml and [use this plugin to block their movement](https://github.com/Zbob750/BlockArmorStandMovement/releases/tag/v1.0).

As of builds 985+ anyway.

**Comment by PhanaticD** [comment]
ily
