### ISSUE TITLE
getTrackedEntities(Class<T> entityClass)

### ISSUE THREAD

**Issue by MrPotatoPotatoPotato** [PaperMC/Paper#5300]
**Describe the solution you'd like**
In the player class of the latest release the getTrackedPlayers was added. Anyhow, 
I could also really use a getTrackedEntities method.
Also; the requested 'getTrackedEntities(Class<T> entityClass) would also work for getting the tracked players, by just using Player.class as the argument.

**Describe alternatives you've considered**
getTrackedEntities() should also do the job for me, but wont be as fancy in my opinion.

I hope this will be considered :) 
~MrPotatoPotatoPotato

**Comment by superkooks** [comment]
Hi! New contributor here. Would this be implemented in CraftLivingEntity or CraftEntity?

**Comment by Proximyst** [comment]
> Hi! New contributor here. Would this be implemented in CraftLivingEntity or CraftEntity?

Hey, welcome! This seems best to be implemented in `Player` (definition) and `CraftPlayer` (implementation) with a special case for `Player.class` to be calling the existing method as players are tracked in a special way.

**Comment by superkooks** [comment]
I know I probably look stupid, but I haven't done much generics. Does this make sense as a function signature?
`<T extends org.bukkit.entity.Entity> Set<T> getTrackedEntities(Class<T> entityClass);`

**Comment by Machine-Maker** [comment]
> I know I probably look stupid, but I haven't done much generics. Does this make sense as a function signature?
> `<T extends org.bukkit.entity.Entity> Set<T> getTrackedEntities(Class<T> entityClass);`

Yeah, looks good.

**Comment by Spottedleaf** [comment]
What goal is achieved by adding this function?

**Comment by Owen1212055** [comment]
Yea I don’t understand this, I moved getTrackedPlayers down to entity. But only other players can technically “track” entities.

**Comment by Owen1212055** [comment]
Closing as the exact use case of a method like this isn't really made clear.
Feel free to comment however and it can be reopened.
Thanks!
