### ISSUE TITLE
Statistics section of the GUI does not work on builds 518+ running macos

### ISSUE THREAD

**Issue by e-im** [PaperMC/Paper#5301]
### What behaviour is expected:
___What you expected to see___

The stats section of the GUI to display, adding tps on mac.

### What behaviour is observed:
___What you actually saw___

The log/players section of the gui works fine, however the statistics section does not load. This includes the graph as well as the new additions. This is logged: [https://paste.gg/p/anonymous/5606a2b323c046a1a37c37af130d85e7](https://paste.gg/p/anonymous/5606a2b323c046a1a37c37af130d85e7)

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

1. environment: macOS 11.2 20D5042d with adoptopenjdk 11/15 or corretto 11/15
2. run the server with `java -jar 518.jar` without `nogui`
3. See that the statistics section is non-functional and this is logged: [https://paste.gg/p/anonymous/5606a2b323c046a1a37c37af130d85e7](https://paste.gg/p/anonymous/5606a2b323c046a1a37c37af130d85e7)

### Plugin list:
___A list of your plugins___
none required

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___

tested on 1.16.5 518/519. Issue not present on <517

### Anything else:
___Anything else you think may help us resolve the problem___

I have tested this with the same setup on debian/windows. Works as expected in both cases.

**Comment by MiniDigger** [comment]
how did this work for me? lol
