### ISSUE TITLE
Adventure team colour methods don't accept decoration

### ISSUE THREAD

**Issue by kezz** [PaperMC/Paper#5302]
**Is your feature request related to a problem? Please describe.**
The "colour" attribute of teams in Minecraft can accept decoration (bold, italic, etc) in addition to colours. The new adventure `colour` methods should accept these formats. If you use `color()` on a team that has one of these formats set (for example, using `setColor(ChatColor.BOLD)`, it will throw an `IllegalStateException` despite the fact the team is in a perfectly valid state.

**Describe the solution you'd like**
Sadly, `TextColor` isn't a good fit here due to the fact that teams can also have formatting codes. If we're trying to remove `ChatColor` perhaps a new enum like `TeamFormat` should be created that contains the colours and decorations, with methods to retrieve the Adventure/Bukkit colours from this. [Here](https://github.com/Minestom/Minestom/pull/157/files#diff-e5b656575a6d5deec344729551a1856515a8eebdff86d5abc0e1695a9144162f) is an example I'm using on another project.

**Describe alternatives you've considered**
Other possible alternatives are as follows:
- Just keep using `ChatColor` and remove/deprecate the adventure methods.
- Have multiple methods such as `color()`, `decoration()` and methods to check if this is using a colour or decoration (this isn't ideal as reset isn't a colour or a decoration.

**Comment by kashike** [comment]
Vanilla itself does not support anything other than colours (hence this being called `color`...)- the vanilla command only accepting colours, and not decorations, is a good example of this.

**Comment by kezz** [comment]
Vanilla supports colours *and* the text decorations such as bold, italic, etc.

**Comment by kashike** [comment]
No, it does not:
```java
    @Override
    public ChatFormatting parse(final StringReader reader) throws CommandSyntaxException {
        final String string = reader.readUnquotedString();
        final ChatFormatting formatting = ChatFormatting.getByName(string);
        if (formatting != null && !formatting.isFormat()) {
            return formatting;
        }
        throw ERROR_INVALID_VALUE.create(string);
    }
```
`!formatting.isFormat()` prevents decorations from being used in the command. The limitation is in place for a reason.

**Comment by kezz** [comment]
Huh interesting! Thanks for pointing it out.

**Comment by Black-Hole** [comment]
The protocol allows those formatting codes: https://wiki.vg/Protocol#Teams
The client seems to renders those formatting for team members.

**Comment by kezz** [comment]
The point of the team colours was to match what the client actually supports in terms of the `/team` command, not what the client *can* support with protocol stuff.
