### ISSUE TITLE
Adventure fails to convert old sign text properly 

### ISSUE THREAD

**Issue by JRoy** [PaperMC/Paper#5304]
### Issue Summary
A sign created with text `§1[Buy]` on Paper build 472 (build right before adventure) produces the following NBT for `Text1`:
```json
{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_blue","text":"[Buy]"}],"text":""}
```

A sign created with text `§1[Buy]` on latest Paper build produces the following NBT for `Text1`:
```json
{"color":"dark_blue","text":"[Buy]"}', Text2: '{"text":"1"}
```

When using `Sign#getLine(int)` (converts to legacy string), Paper 472 will convert the both of the above components to `§1[Buy]` which is the "correct" legacy string representation.

However, using `Sign#getLine(int)` with the first component on the latest Paper, it will produce `§1[Buy]§r`. This may be the correct way to convert the component but we shouldn't being doing this in order to maintain compatibility with (the broken I guess) upstream component conversion.

**Comment by kashike** [comment]
This should be fixed as of https://github.com/PaperMC/Paper/commit/27a8d99ec4f11d1facccb6d68b120b67b74b16a2 and https://github.com/PaperMC/Paper/commit/7f72c4675bf18f1dc1fd1fea2737590fa41dc7a7.
