### ISSUE TITLE
Server Thread Dump

### ISSUE THREAD

**Issue by nikitushu2** [PaperMC/Paper#5305]
### Link/paste of stack trace
04.03 15:32:43 [Server] ERROR ------------------------------
04.03 15:32:43 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
04.03 15:32:43 [Server] ERROR ------------------------------
04.03 15:32:43 [Server] ERROR Current Thread: Server thread
04.03 15:32:43 [Server] ERROR PID: 27 | Suspended: false | Native: false | State: RUNNABLE
04.03 15:32:43 [Server] ERROR Stack:
04.03 15:32:43 [Server] ERROR com.google.common.collect.SingletonImmutableBiMap.get(SingletonImmutableBiMap.java:55)
04.03 15:32:43 [Server] ERROR com.google.common.collect.DenseImmutableTable.get(DenseImmutableTable.java:241)
04.03 15:32:43 [Server] ERROR net.minecraft.server.v1_12_R1.BlockStateList$BlockData.set(SourceFile:182)
04.03 15:32:43 [Server] ERROR net.minecraft.server.v1_12_R1.BlockStone.fromLegacyData(SourceFile:61)
04.03 15:32:43 [Server] ERROR com.pg85.otg.bukkit.BukkitMaterialData.internalBlock(BukkitMaterialData.java:219)
04.03 15:32:43 [Server] ERROR com.pg85.otg.bukkit.BukkitWorld.setBlock(BukkitWorld.java:526)
04.03 15:32:43 [Server] ERROR com.pg85.otg.generator.resource.OreGen.spawn(OreGen.java:128)
04.03 15:32:43 [Server] ERROR com.pg85.otg.generator.resource.Resource.spawnInChunk(Resource.java:195)
04.03 15:32:43 [Server] ERROR com.pg85.otg.generator.resource.Resource.process(Resource.java:152)
04.03 15:32:43 [Server] ERROR com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:259)
04.03 15:32:43 [Server] ERROR com.pg85.otg.bukkit.generator.OTGBlockPopulator.populate(OTGBlockPopulator.java:30)
04.03 15:32:43 [Server] ERROR net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:1173)
04.03 15:32:43 [Server] ERROR net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:1137)
04.03 15:32:43 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:59)
04.03 15:32:43 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
04.03 15:32:43 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
04.03 15:32:43 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
04.03 15:32:43 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.lambda$syncChunkLoad$0(ChunkIOExecutor.java:18)
04.03 15:32:43 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor$$Lambda$904/1878432897.get(Unknown Source)
04.03 15:32:43 [Server] ERROR net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:69)
04.03 15:32:43 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
04.03 15:32:43 [Server] ERROR net.minecraft.server.v1_12_R1.ChunkProviderServer.getOrLoadChunkAt(ChunkProviderServer.java:118)

### Plugin list:
ccInstantRespawn
FAWE
LuckPerms
OpenTerrainGenerator
Viabackwards
Viarewind
Viaversion
Worldborder
Worldedit

### Actions to reproduce (if known):
My world is generated via OpenTerrainGenerator. If you do not connect to the world for several days and then you join it, then the error arises, and the server crashes and self-restarts.

### Paper version:
git-Paper-1618 (MC: 1.12.2)

**Comment by e-im** [comment]
You both cut out the "DO NOT REPORT THIS TO PAPER" line as well as are using an unsupported version. Nice.

**Comment by JRoy** [comment]
and to add, this isn't even a Paper bug.

**Comment by Chew** [comment]
Strike 3, we don't support 1.12.2. You somehow managed to check every box for "close immediately." Thank you for your contribution and for filling out the template regardless.
