### ISSUE TITLE
/Team name color not showing up in chat

### ISSUE THREAD

**Issue by MikaGreen1604** [PaperMC/Paper#5307]
### What behaviour is expected:
___What you expected to see___
/team name color in chat
### What behaviour is observed:
___What you actually saw___
No /team name color in chat
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Have the 4 plugins active without them it does work, but in an earlier version of paper: 506(This server is running Paper version git-Paper-506 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
) it did work with the 4 plugins active
### Plugin list:
___A list of your plugins___
Essentials
Harbor
Luck Perms
Core Protect
### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-525 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by histefanhere** [comment]
Second this bug, it started happening on our Paper server 2 days ago when we updated to the most recent version (only plugin we have is core protect)

**Comment by Evilwuflers** [comment]
Third'ed', this hasn't been an issue until a couple of days ago even after a full server reset. Would love for this to be back without having to use the nickname plugin! Any other additions to the name including prefixes dont work either, but you can see them in the scoreboard and when people join the server.

**Comment by Linc-Sylvester** [comment]
Fourthed, the same problem happened around august last year.

**Comment by Proximyst** [comment]
Please just react with thumbs up if you can reproduce the issue...

**Comment by Linc-Sylvester** [comment]
> Please just react with thumbs up if you can reproduce the issue...

ty, will do ...

**Comment by BillyGalbreath** [comment]
> Please just react with thumbs up if you can reproduce the issue...

that doesnt keep the dreaded stalebot away, though :P

**Comment by PureVanillaFrance** [comment]
Hi ! 
I am still facing this issue.
It works fine when I don't have DiscordSRV. As soon as I put it it doesn't work anymore.
DiscordSRv says it's your issue. Any idea ?

**Comment by electronicboy** [comment]
Please actually read the issue before posting, you'll see that there is a linked pull request.

**Comment by ryantheleach** [comment]
If anyone encounters this issue, make sure that you check your configuration before reporting another bug.

The configuration option can be found in `config\paper-world-defaults.yml` under `scoreboards.use-vanilla-world-scoreboard-name-coloring: true`
