### ISSUE TITLE
Game breaking bug with zombified piglins

### ISSUE THREAD

**Issue by Phantix** [PaperMC/Paper#5310]
### What behaviour is expected:
the zombified piglin agro like normal and don't lose focus

### What behaviour is observed:
the piglins lose agro after the first few ones

### Steps/models to reproduce:
the problem completely breaks gold farms like this one https://www.youtube.com/watch?v=lCs3StdbuqU

### Plugin list:
none only paper

### Paper version:
526

**Comment by JRoy** [comment]
Does this work on spigot? on vanila?

**Comment by Phantix** [comment]
this farm works on vanilla spigot idk

**Comment by JRoy** [comment]
> this farm works on vanilla spigot idk
> 

Please try on spigot

**Comment by e-im** [comment]
I haven't been able to reproduce this behaviour on 1.17.1 build 351. If you are still experiencing this on 1.17.1 and have more information, feel free to leave a comment.
