### ISSUE TITLE
API to get armor value of item

### ISSUE THREAD

**Issue by aecsocket** [PaperMC/Paper#5311]
**Is your feature request related to a problem? Please describe.**
There should be an API to get the armor value of an item, as this is quite a common function and I feel like it is an oversight that this is not implemented. This may be due to difficulties such as having to compute the armor value using the attribute modifiers and whatnot, in which case provide API to calculate this armor value.

**Describe the solution you'd like**
Some sort of API on `ItemMeta` which allows calculating the armor value of the item, including attribute modifiers.

**Describe alternatives you've considered**
Manually getting the armor value of the `Material` using a hardcoded `Map<Material, Double>` or manually applying all of the attribute modifiers.

**Additional context**
In general, it may be useful to provide API to compute the final result of a `Collection<AttributeInstance>` such as those found on `ItemMeta#getAttributeModifier(...)`. In a similar vein, API to calculate:
* weapon damage
* damage reduction from armor

would be useful.

**Comment by Machine-Maker** [comment]
I'm pretty sure you can get the armor defense, toughness, and knockback resistance from the attributes.

**Comment by Xemorr** [comment]
> I'm pretty sure you can get the armor defense, toughness, and knockback resistance from the attributes.

Last time I used the attribute API it didn't have the defaults.

**Comment by reflqct** [comment]
Does this issue still need resolution?

**Comment by Chew** [comment]
I think the base of it was made in #5593, feel free to hop into [#paper-dev on our Discord server](https://discord.gg/papermc) if you need further information!

**Comment by Leisterbecker** [comment]
Can I work on that issue?

**Comment by Doc94** [comment]
In teory this issue can be close since https://github.com/PaperMC/Paper/commit/2d34898b55c97fcb97fd47275545641c54057172 not?

**Comment by hendoulmou9** [comment]
Can I work on this issue?
