### ISSUE TITLE
AnvilDamagedEvent should get the location of the anvil

### ISSUE THREAD

**Issue by DaniFoldi** [PaperMC/Paper#5312]
**Is your feature request related to a problem? Please describe.**
I'm trying to work with the AnvilDamagedEvent, but I would like to avoid putting players and blocks they are looking at into a  Map on InventoryClickEvent.

**Describe the solution you'd like**
The AnvilDamagedEvent could have a #getLocation() method that returns the Location of the anvil

**Describe alternatives you've considered**
The above mentioned HashMap storing players and the inventory they opened, and BlockBreakEvent which checks for anvils broken in the same tick - both are inefficient.

**Additional context**
A link to the Javadocs? https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/event/block/AnvilDamagedEvent.html

**Comment by Trigary** [comment]
You can get the `AnvilInventory` from the event, which exposes an `InventoryHolder`. Is that holder an instance of `BlockInventoryHolder` if you open an anvil that exists as a block in the game world? If yes, you can get the anvil location via `BlockInventoryHolder#getBlock()`.

**Comment by Machine-Maker** [comment]
I mean... `AnvilInventory` implements `Inventory` which has a getLocation method on it. It's nullable, but that's appropriate because there doesn't have to be an actual anvil. I'd just use that.

**Comment by DaniFoldi** [comment]
Thanks for the heads up, that does in fact solve the issue.
