### ISSUE TITLE
TOTEM-REVIEVE effect

### ISSUE THREAD

**Issue by TheFruxz** [PaperMC/Paper#5316]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Personally, I would find a way very nice to give a player the totem of undying effect via #playEffect( ... ). So e.g. #playEffect(..., Effect.TOTEM_OF_UNDYING, ...)

**Describe alternatives you've considered**
no

**Additional context**
Currently it is only accessible through Packets, but since Paper relies heavily on direct API (at least last time) I believe this is a very useful and beneficial feature for API users. Personally, at least, I would be pretty strong about making it convenient like other things yes!

**Comment by HexedHero** [comment]
player.playEffect(EntityEffect.TOTEM_RESURRECT);
works just fine.

**Comment by MiniDigger** [comment]
^
