### ISSUE TITLE
Unexpected blaze flying behaviour

### ISSUE THREAD

**Issue by emilcarr** [PaperMC/Paper#5318]
### What behaviour is expected:
Vanilla blaze behaviour is for blazes to fly when targeting a player and fall down otherwise. Player is within activation range of blazes.

### What behaviour is observed:
Blazes fly intermittently even when not targeting any player.

### Steps/models to reproduce:
Build ([sponge schem](https://emilcarr.scot/wp-content/uploads/2021/03/07/blaze.schem)) a 9x9x5 box with a blaze spawner in the middle and a lava funnel below. Allow blazes to spawn and observe behaviour.

### Plugin list:
Dynmap v3.1

### Paper version:
```
04:36:28.547
[CHAT] This server is running Paper version git-Paper-497 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
04:36:28.547
[CHAT] Previous version: git-Paper-468 (MC: 1.16.5)
04:36:28.548
[CHAT] You are 29 version(s) behind
```

### Anything else:

I compared the PaperSpigot sources to vanilla Minecraft decompiled with yarn mappings, and the behaviour in tick() and tickMovement() BlazeEntity/EntityBlaze have no discrepancies I can see that would result in this behaviour.

**Comment by Proximyst** [comment]
Works as intended. Blazes do not instantly fall down, it will take them a few seconds.

```
> ver
[12:06:26 INFO]: This server is running Paper version git-Paper-"69b1a5b07" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[12:06:26 INFO]: Checking version, please wait...
[12:06:26 INFO]: Previous version: git-Paper-527 (MC: 1.16.5)
[12:06:26 INFO]: Unknown version
> pl
[12:06:28 INFO]: ------------=[ ServerUtils Plugins ]=-------------
[12:06:28 INFO]:  Plugins (14): Essentials, EssentialsChat, EssentialsSpawn, Gaea, LuckPerms, PlaceholderAPI, ProtocolLib, ProxiDebugPlugin, ServerUtils, Terra, Vault, WorldEdit, grakkit and spark
[12:06:28 INFO]: -------------------------------------------------
> # version is based on 527
```

**Comment by emilcarr** [comment]
Apologies Proxymist, but that's not the behaviour I observed. The blazes flew 'intermittently', as in falling down then flying back up when I wouldn't expect.

**Comment by emilcarr** [comment]
I will try on a newer version of the server.

**Comment by Proximyst** [comment]
Will attempt to reproduce later today.

**Comment by emilcarr** [comment]
I'm now struggling to recreate this on a clean server setup - bear with me

**Comment by emilcarr** [comment]
Couldn't recreate the issue on a separate server. Server owned has updated server version. Issue is fixed. My apologies.
