### ISSUE TITLE
Port 1.15.2 villager optimisations

### ISSUE THREAD

**Issue by Proximyst** [PaperMC/Paper#5322]
We dropped some of the villager optimisations in the 1.16(.1) update; because of this, we need them ported back.

Patch file: https://github.com/PaperMC/Paper/blob/54ec85949d21a55a79889c46640c61bee4e6fe2d/removed/1.16/0530-Optimize-Villagers.patch

The current PR for this, #4101, is closed due to its author being blocked from the organisation.

**Comment by Pantera07** [comment]
This may have been forgotten.
I hope someone can solve this.

**Comment by Owen1212055** [comment]
Generally the whole POI searching logic has been optimized by Leaf, therefore this patch may not be needed anymore.
However if someone still sees that there is a possibility for improvement in this area do comment and this can be reopened.
