### ISSUE TITLE
Blank space when joining silently

### ISSUE THREAD

**Issue by Kristoffeh** [PaperMC/Paper#5324]
### What behaviour is expected:
When a normal user joins the server its supposed to show the default join message. BUT if the user joining is admin, admins will join silently and should not show any join or leave message.

### What behaviour is observed:
When a normal user joins the server, a blank space in the chat is shown (no message).

### Steps/models to reproduce:
I can make a video if this text is not enough. I have 2 plugins, EssentialsX and LuckPerms (permission plugin). In the EssentialsX plugin, there is an option in config.yml to enable silent joining and leaving. That option must be set to true.
In LuckPerms, the following permission nodes must be set to true for admins only:
- essentials.silentjoin
- essentials.silentquit
Performing these steps would allow you to recreate the bug.

### Plugin list:
- EssentialsX
- LuckPerms (permission plugin)

### Paper version:
07.03 15:26:04 [Server] INFO You are running an unsupported server version!
07.03 15:26:04 [Server] INFO Vault is not installed. Chat and permissions may not work.
07.03 15:26:04 [Server] INFO LuckPerms version: 5.3.0
07.03 15:26:04 [Server] INFO EssentialsX version: 2.18.2.0
07.03 15:26:04 [Server] INFO Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-529 (MC: 1.16.5)
07.03 15:26:04 [Server] INFO CONSOLE issued server command: /ess version

### Anything else:
The copy+paste above was done before the server upgrade my host took care of, but i can assure you that i am on version 529.

**Comment by Proximyst** [comment]
The Paper bug here is that it sends a message when it is set to `null`.

As for the bug on Essentials' side: They disable the join message no matter the permission.

```yml
# Should players with permissions be able to join and part silently?
# You can control this with essentials.silentjoin and essentials.silentquit permissions if it is enabled.
# In addition, people with essentials.silentjoin.vanish will be vanished on join.
allow-silent-join-quit: true
```
https://github.com/EssentialsX/Essentials/blob/eca6a9f247193202ccd773fc51952e579e14329b/Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java#L267

**Comment by JRoy** [comment]
Not an EssX bug, we postpone permission checks until we've loaded user data. If the user indicates that they want EssX overriding something to do with join messages, we set it to null and handle it ourselves. This is purely a Paper bug as you're preserving a null message as an empty translatable component.

**Comment by Trigary** [comment]
I have tried to reproduce this with my own plugin but failed. I did not try to use the listed plugin(s).

Both `event.joinMessage(null)` and `event.joinMessage(null)` produce no messages, not even empty ones, between the "Before" and "After" messages my plugin sends.
```
@EventHandler(ignoreCancelled = true)
private void on(PlayerJoinEvent event) {
	event.getPlayer().sendMessage("Before");
	event.joinMessage(null); //same as event.setJoinMessage(null);
	Bukkit.getScheduler().runTask(this, () -> event.getPlayer().sendMessage("After"));
}
```

**Comment by Proximyst** [comment]
This is an adventure bug @kashike fixed at some point over the past months.
