### ISSUE TITLE
Deprecating Spigot's PlayerJoinEvent message and PlayerQuitEvent message causes incompatibility

### ISSUE THREAD

**Issue by StarsDown64** [PaperMC/Paper#5326]
### What behaviour is expected:
A string containing the join/quit message to be returned by PlayerJoinEvent#getJoinMessage and PlayerQuitEvent#getQuitMessage

### What behaviour is observed:
An empty string is returned

### Steps/models to reproduce:
Use the method

### Plugin list:
Minecord v1.4.1-alpha1 (Testing plugin)
SuperVanish v6.2.0

### Paper version:
Paper 1.16.5 v530

### Anything else:
The fact that an empty string gets pushed to these methods means any spigot plugin trying to use the methods will not be fully compatible with Paper. For example my plugin (a spigot plugin) links in game chat and Discord chat; people joining/leaving no longer get sent to Discord on paper servers because of this issue. Not sure if this is intended/a bug/maybe you guys don't care cause it's spigot. Thanks for listening.

**Comment by kashike** [comment]
This should be fixed as of https://github.com/PaperMC/Paper/commit/27a8d99ec4f11d1facccb6d68b120b67b74b16a2 and https://github.com/PaperMC/Paper/commit/7f72c4675bf18f1dc1fd1fea2737590fa41dc7a7.
