### ISSUE TITLE
Hoglin & Piglin Brutes not aggressive toward players on survival server on hard mode.

### ISSUE THREAD

**Issue by ScreaminMonk** [PaperMC/Paper#5330]
### What behaviour is expected:
Hoglins and Piglin Brutes are to be hostile towards players in normal survival mode.

### What behaviour is observed:
Hoglins and Piglin Brutes, naturally spawned in or spawned by egg are both passive towards the player when in survival mode. Piglins in the same area become aggressive upon removing a gold armor item but the above mentioned stay the same. 

### Steps/models to reproduce:
[https://youtu.be/o1fc7LvvtHI](Hoglin & Piglin Brute Video ) Video showing steps taken to show non aggressive behavior. 

### Plugin list:
No plugins used. [https://timings.aikar.co/?id=ae45fe81976c4769b1cdafcc5f458c7f](Timings Report from same server)

### Paper version:
[09-Mar-2021 14:25:32] This server is running Paper version git-Paper-537 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[09-Mar-2021 14:25:32] Previous version: git-Paper-526 (MC: 1.16.5)

### Anything else:
This was discovered on a multiplayer server as early as the 4th of March when first seen by a player moving hoglins for a farm. Today I discovered the Piglin Brutes acting the same. Other hostiles in the nether act accordingly and try to attack the player.

**Comment by ScreaminMonk** [comment]
After testing several versions of Paper I have concluded that this situation breaks after version #510 and the lack of agro Hoglins and Piglin Brutes appears in version #511 
![Version #510-Agro](https://user-images.githubusercontent.com/53252959/110608191-9e1d8180-8151-11eb-9c1f-8fe0a3b06870.png)
![Version #511-NonAgro](https://user-images.githubusercontent.com/53252959/110608219-a5dd2600-8151-11eb-9722-29da63e3d3d3.png)

**Comment by Trigary** [comment]
Thank you for locating the exact build, that helps a lot :)

The issues in the patch that got introduced in that build is highlighted in the following image:
(expression is negated but shouldn't be; variable that should be used isn't used)
![image](https://user-images.githubusercontent.com/16213127/110611330-6af9e300-818f-11eb-8551-c6784ce154b3.png)
I plan on fixing it later today.

**Comment by ScreaminMonk** [comment]
Fantastic news and the speedy reply is greatly appreciated! Thanks much.
