### ISSUE TITLE
Plugins error on build 540

### ISSUE THREAD

**Issue by slvlr** [PaperMC/Paper#5331]
### What behaviour is expected:
No plugins to break and paper work work.

### What behaviour is observed:
At least 4 plugins broke.
![image](https://user-images.githubusercontent.com/8680731/110537032-11a39c80-811a-11eb-9b45-e4ed168ff3af.png)

### Steps/models to reproduce:
Updated from build 529 to 540.

### Plugin list:
___A list of your plugins___
![image](https://user-images.githubusercontent.com/8680731/110536976-fc2e7280-8119-11eb-8c87-8c207a06b6fa.png)

### Paper version:
Was build 540 with the issues. Previous build 529.

### Anything else:
I backdated to build 529, and the plugins loaded successfully. 
Logs: https://pastebin.com/e5SqiQY4

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/commit/e4d8a6279cbcbd748a769a104e592e7189477944
Invalid world names...

**Comment by slvlr** [comment]
> [e4d8a62](https://github.com/PaperMC/Paper/commit/e4d8a6279cbcbd748a769a104e592e7189477944)
> Invalid world names...

I'm sorry what?
Is this an issue I have done, and if so how do I fix this please?

**Comment by Chew** [comment]
Means update, you're behind (by 1 build).

**Comment by MiniDigger** [comment]
meh I should have considered that. thanks cat for the quick fix.
