### ISSUE TITLE
Death message Adventure issue

### ISSUE THREAD

**Issue by slvlr** [PaperMC/Paper#5332]
### What behaviour is expected:
Death message should be in color - this includes players usernames/ranks + the weapon name.
You should also be able to hover over the weapon to see it's info, enchantments etc. 

### What behaviour is observed:
![image](https://user-images.githubusercontent.com/8680731/110558798-04e37080-813b-11eb-80cd-e82d9abb0662.png)

### Steps/models to reproduce:
Kill someone, while holding something.

### Plugin list:
___A list of your plugins___
![image](https://user-images.githubusercontent.com/8680731/110558811-0b71e800-813b-11eb-9f1e-f7236db43952.png)

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
![image](https://user-images.githubusercontent.com/8680731/110558826-14fb5000-813b-11eb-8bea-d22ce4da8600.png)

### Anything else:
This happened since the adventure update.

**Comment by kashike** [comment]
We are not going to sift through 88 plugins to figure out if one is breaking death messages - comment if you can reproduce this without any plugins.

**Comment by Proximyst** [comment]
Closing as this is not a Paper issue.
