### ISSUE TITLE
Disable console coloration/highlight 

### ISSUE THREAD

**Issue by SlimeDog** [PaperMC/Paper#5335]
**Is your feature request related to a problem? Please describe.**
As one example, console/log output from `version` is now rendered with special characters.
![Screen Shot 2021-03-09 at 10 23 40 PM](https://user-images.githubusercontent.com/17748923/110585863-2423d300-8126-11eb-9347-6460aed9b22e.png)

**Describe the solution you'd like**
Please consider option to render console/log output in plaintext.

**Comment by jpenilla** [comment]
`-Dterminal.ansi=false`

**Comment by jpenilla** [comment]
also, the highlighting issue here is caused by #5253 if you are using screen (edit: it seems like certain terminals like to highlight italics, and that is more likely the case in this situation)

**Comment by Proximyst** [comment]
Not a Paper problem, take it up with your terminal emulator developers.

**Comment by SlimeDog** [comment]
> -Dterminal.ansi=false

I want to control what is colored/highlighted and what is not. I wish software developers did not feel the need to decide for me. The `version` output is not so important that it needs to be highlighted.

**Comment by Proximyst** [comment]
https://github.com/electronicboy/byof / https://github.com/Proximyst/paperfork/ then.

**Comment by SlimeDog** [comment]
> https://github.com/electronicboy/byof / https://github.com/Proximyst/paperfork/ then.

Well, yeah. That's really up-to-date. :(

**Comment by Proximyst** [comment]
They're templates on how to fork the server; you can update it pretty easily yourself. paperfork even lets you have 0 patches, so you can just update the submodule and delete the existing patches :)

**Comment by SlimeDog** [comment]
Thanks.
