### ISSUE TITLE
Vanilla Chat scoreboard bug 542

### ISSUE THREAD

**Issue by PureVanillaFrance** [PaperMC/Paper#5336]
### What behaviour is expected:
< PLAYER > text with PLAYER in color only
 
### What behaviour is observed:
< PLAYER > text with all white. No scoreboard colors with vanilla to true

### Steps/models to reproduce:
build 542 with discordSRV

### Plugin list:
DISCORDSRV

### Paper version:
542

**Comment by MiniDigger** [comment]
could you please attach screenshots from when it worked and when it didnt work, its rather confusing as is

**Comment by PureVanillaFrance** [comment]
![image](https://user-images.githubusercontent.com/76930233/110636274-6132a880-81ac-11eb-8781-974f8374d46c.png)

It should be like this.

But now everything is white (the player name is white eventhought he is in vanilla scoreboard team).

![image](https://user-images.githubusercontent.com/76930233/110671503-dc0cbb00-81ce-11eb-9e4b-5aa347f2522e.png)

I already put to true vanilla scoreboard in paper.yml.
It worked before :)

Thanks for your help !

**Comment by kashike** [comment]
Cannot confirm:
![meow](https://i.imgur.com/ahRRXyR.png)

I'm going to say that your plugin is causing this.

**Comment by PureVanillaFrance** [comment]
Thanks for your reply !
It comes when you have Discord SRV on as stated above.

Discord SRV says it comes from paper wioth legacy

**Comment by PureVanillaFrance** [comment]
![image](https://user-images.githubusercontent.com/76930233/110679350-ad471280-81d7-11eb-8596-466e1e96ac1b.png)

**Comment by Vankka** [comment]
Sooo how exactly is it that DiscordSRV is causing this even though it does**n't** alter chat through any way, like I would understand this if we were using `setMessage` or `setFormat` but we aren't.

For reference the AsyncPlayerChatEvent listener: https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/listeners/PlayerChatListener.java

**Comment by PureVanillaFrance** [comment]
I checked on my side to make sure I did everything right
![image](https://user-images.githubusercontent.com/76930233/110680183-90f7a580-81d8-11eb-8577-ef7ff08c8fc0.png)

**Comment by electronicboy** [comment]
We can only go off the info we've been given ontop of that option being somewhat of an as-is hack, can anybody else reproduce this? I'd be interested to see a full server log for science, beyond that, god knows™

**Comment by PureVanillaFrance** [comment]
![image](https://user-images.githubusercontent.com/76930233/110680828-6528ef80-81d9-11eb-9cf5-e29baec5b1f8.png)
 
reproduced on a local server of paper

**Comment by kashike** [comment]
Should be fixed with the next build.

**Comment by PureVanillaFrance** [comment]
Thank you very much :)
I'll test as soon as it is out and come back to you

**Comment by PureVanillaFrance** [comment]
![image](https://user-images.githubusercontent.com/76930233/110706114-a29c7580-81f7-11eb-89f2-1e1e5364178b.png)

Works like a charm ! thanks :p
