### ISSUE TITLE
Paper Auto disabling timings after 100 seconds

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#534]
Paper Build: 959

**Comment by MiniDigger** [comment]
related to #444 
take a look at aikars comment at the bottom.

**Comment by Fonzee9** [comment]
But it worked yesterday and i didn't switch plugins?

**Comment by MiniDigger** [comment]
try to set the system flag mentioned in the thread

**Comment by Fonzee9** [comment]
Okay thanks lol solved i am using FAWE that was the problem
