### ISSUE TITLE
Single Configuration File

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5341]
Just a simple request. Please just keep a single configuration file for the server. (Ex. Instead of bukkit.yml, spigot.yml and paper.yml, please keep **all** the settings in paper.yml.)

**Comment by jacobsandersen** [comment]
As paper is currently a fork of spigot, we can't do that. Technically, we could, but it'd be a bad choice and it would be hell to maintain.

After hard fork, perhaps? But even then, might be kind of hell to maintain. I'm not for or against it.

**Comment by Chew** [comment]
Pretty much the above. Helps differentiate what config came from where, and we don't particularly like touching other configs if not needed. I agree it would be useful, but way out of the scope of this project. Additionally, putting all values into the paper.yml is a bad idea in case you ever want to (for whatever reason) downgrade to Spigot, you'd lose all your config.

Alas, no template = no issue, so our adventure ends here. Thank you for your contribution nonetheless.
