### ISSUE TITLE
Optimization Villagers

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5342]
AIn fork paper "Tuinty" there is such optimization of mobs, villagers. Because when I was using the paper a while ago, my TPS was dropping to 10, and now when I have Tuinty, there are mobs, especially villagers are optimized. And with tuinty I have 20TPS, so as a proposal, adding optimized villagers, we could use tuinty as an example, because it has optimized mobs, villagers.  

I hope you will accept my request to optimize villagers, I would like to get back to using paper as soon as possible

**Comment by TheDGOfficial** [comment]
It is job of the maintainer/owner of fork or the code/patch owner (in this
case, Spottedleaf) to open PRs to implement them in upstream.

That being said, maintainer/owner of fork may think they are too
experimental and/or would not fit in Paper.

Also - I don’t think 10 to 20 TPS you’ve said would be real. If it is then
you have to provide details (i.e. Spark report, Timings, Server logs,
Plugins)

**Comment by Proximyst** [comment]
This is about as helpful as "paper slow, pls fix"; we know that other forks have patches that are interesting and exciting, and we're keeping an eye on them as they develop, however it is not possible for us to just drag in any ol' patch that we'd like. We'll include the patches we're able to when we're able to.
