### ISSUE TITLE
Behavior Bug Pre-Fill Template Assistant

### ISSUE THREAD

**Issue by darbyjack** [PaperMC/Paper#5347]
With PaperMC getting access to the new GitHub templates that are slowly rolling out, it would be cool to consider some kind of command to help pre-fill information for reporting bug 

As seen here (https://github.com/PaperMC/Paper/blob/0d92e6b53f1889fadc6a6c6aaf72b7e83a37aa31/.github/ISSUE_TEMPLATE/behavior-bug-or-plugin-incompatibility.yml) PaperMC is already in the works on the new template style that allows you to have required fields along with the ability to pre-fill information by using a specific URL.

An example could be something like `/paper bugreport` or `/paper report` and that would generate a link to help them get started filling out a Behavior Bug report here on GitHub. The command would generate a URL to pre-fill out the version information along with the plugins on the server.

**Comment by e-im** [comment]
Due to increased possible spam associated with this and length restrictions, this won't be added. Rather, a `/paper dump` command to upload diagnostic server information to a web-based viewer will be discussed. I'll open an issue with more details shortly.
