### ISSUE TITLE
MiniaturePets not working right with Paper

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#535]
The author said MPets uses nms and that
PaperSpigot removed the nms they are using 

This is a Paper issue since it broke a plugin based on a nms change anyway it can be fixed?

**Comment by zachbr** [comment]
Invalid?

**Comment by Fonzee9** [comment]
Well it's just i didn't know if you wanted to look into it.

This is the error it gives: http://hastebin.com/ogokelijij.md

**Comment by zachbr** [comment]
So I went to the discussion page to try and get more information on this issue...
> +the only way to "fix" it is remove MYSQL. Which will "let down" 5 times the buyers.

What the fuck is this guy doing using an NMS network manager field to do MySQL... It sounds like he's either doing horrible things or he has no idea what he's talking about.

**Comment by zachbr** [comment]
Someone sane replied later down, perhaps the person who actually does stuff
> That is because in 1.3 we started using packets allot once I finish adding support vi protocol lib both protocol lib and paper spigot would work

If they can say specifically which field it is we're removing that they need, we can look at perhaps keeping it around, but its more probable that they're just using the wrong field and we can point out the proper one to be using across ALL platforms.

**Comment by NacOJerk** [comment]
Hey Zbob750 I'm the main dev of mini pet (I have no idea what the other dev meant with the MySQL bullshit)
Any way I never truly dogged into paper spigot code but basicly I'm using the field in spigot named networkManager inside of playerConnection (I think it's in there)
To create a packet listener
Now seems like in paper spigot this field name is different I think the easiet fix for me like I told that user is for me to add a protocol lib feature for people with such indepndecies

**Comment by zachbr** [comment]
I believe that field is still there in Paper. Are you sure that's the one being referenced above?
Anyway, I'll dig more into this in the next few weeks hopefully, things are pretty busy for now.

**Comment by NacOJerk** [comment]
Here we go this is the packet listener injecting code
https://0bin.net/paste/r5sp+guLq-m6TnYk#OIopZgMAYRCSMdR2CWwuBhxXnyM7Y-k60zheZfSVIs1

**Comment by aikar** [comment]
This is a problem with their plugin. Nothing we can do to fix it.

**Comment by Fonzee9** [comment]
What your doing is wrong ZBob is helping him fix the issue and so what you do is close it?

**Comment by zachbr** [comment]
@Fonzee9 do you still see this if you run the jar located in serverdir/cache/patched_1.11.jar rather than serverdir/paperclip.jar ?

**Comment by Fonzee9** [comment]
I don't know if i've never run anything other then Paperclip

**Comment by zachbr** [comment]
Well try it and let us know.

**Comment by Fonzee9** [comment]
Okay i will but whats the difference between patched and Paperclip?

**Comment by zachbr** [comment]
They're the exact same, paperclip is a distribution and deployment tool for the patched jar.

**Comment by Fonzee9** [comment]
:O It worked no errors thank you so much @Zbob750

**Comment by Fonzee9** [comment]
By the way @Zbob750 Why does it have issues with the Paperclip version of Paper but not the Patched one?

**Comment by zachbr** [comment]
Because https://github.com/PaperMC/Paperclip/issues/4

In the future, just always run that jar. 
You will have to run paperclip to update the cached jar, so on each build you update to run paperclip, but after you can just run the cached jar.

**Comment by aikar** [comment]
@NacOJerk what is MP doing with reflection that's different than every other plugin?

If you can modify the reflection utility methods to work like everyone else does, then it should fix it.
