### ISSUE TITLE
Get rarity and proper name from ItemStack and Material

### ISSUE THREAD

**Issue by justEli** [PaperMC/Paper#5351]
**Is your feature request related to a problem? Please describe.**
It is currently impossible to get the rarity (enum) and rarity color of an ItemStack, other than using NMS reflection. It is also complicated to get the proper name (i.e. "Block of Iron" for `Material.IRON_BLOCK`) for ItemStack or enum Material.

**Describe the solution you'd like**
I would love to see two new functions, for `ItemStack` and `Material`:
- `ItemStack#getRarity`: returns an `enum ItemRarity` (new enum that has to be created, example below)
- `Material#getProperName` (or for `ItemStack`): returns a `String` with the name that is displayed in inventories

The `ItemRarity` would be a new enum, something like this:
```java
public enum ItemRarity
{
    EPIC (ChatColor.LIGHT_PURPLE),
    RARE (ChatColor.AQUA),
    UNCOMMON (ChatColor.YELLOW),
    COMMON (ChatColor.WHITE);

    private final ChatColor chatColor;

    ItemRarity (ChatColor chatColor)
    {
        this.chatColor = chatColor;
    }

    public ChatColor getChatColor ()
    {
        return chatColor;
    }
}
```
Note how the item rarity also already can provide the color that's bound to that rarity.

An example of how I'd like to result to be like:
```java
ItemStack item = new ItemStack(Material.IRON_BLOCK);

String name = item.getType().getProperName(); // "Block of Iron"
// or really can also be `item.getProperName()` if preferred
ItemRarity rarity = item.getRarity(); // ItemRarity.COMMON

System.out.printf("%s, %s, %s", name, rarity.name(), rarity.getChatColor().name());
```
Output: `Block of Iron, COMMON, WHITE`

**Describe alternatives you've considered**
Well, it may or may not be possible to implement it on the `Material` enum instead of the `ItemStack` class, if you can get that done. Not sure. But it would mean it's easier to access, as `Material` is more present (think of `block.getType()`), but idm if it's on `ItemStack`. Though, `Material#getProperName` would be possible, most likely, see examples below.

**Additional context**
Get NMS ItemStack and CraftItemStack for further reference in 1.16.5:
```java
org.bukkit.inventory.ItemStack itemStack = new ItemStack(Material.IRON_BLOCK);
net.minecraft.server.v1_16_R3.Item nmsItem = org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.getItem(itemStack.getType());
net.minecraft.server.v1_16_R3.ItemStack craftItemStack = org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.asNMSCopy(itemStack);
```
How rarity of an `ItemStack` is obtained using NMS, in 1.16.5:
```java
net.minecraft.server.v1_16_R3.EnumItemRarity itemRarity = nmsItem.i(craftItemStack);
```
How the "proper" name of a `Material` is obtained:
```java
String properName = net.md_5.bungee.chat.TranslationRegistry.INSTANCE.translate(nmsItem.getName());
```

**Comment by Machine-Maker** [comment]
The “Proper Name” you are referring to is just the English translation of the item/block. I think there is already support for getting the translation key and if you want to put it into any messages, adventure supports translatable components which should handle this.

**Comment by justEli** [comment]
Yes, as mentioned, it's a hassle, "complicated", to get that with adventure or any other API or even NMS. Would be very neat if it's just implemented in either `Material` or `ItemStack`.

**Comment by Machine-Maker** [comment]
Is it really a hassle? `Component.translatable(Material.DIRT.getTranslationKey)`?

**Comment by RezzedUp** [comment]
The point is to get the "proper" name server-side, not in a client-side translation.

**Comment by justEli** [comment]
`Material#getTranslationKey` (or anything similar) doesn't even exist?

**Comment by Machine-Maker** [comment]
> `Material#getTranslationKey` (or anything similar) doesn't even exist?

https://papermc.io/javadocs/paper/1.16/org/bukkit/Material.html#getTranslationKey--
wut?

**Comment by Machine-Maker** [comment]
> The point is to get the "proper" name server-side, not in a client-side translation.

The whole point of having the translation key, is that you never *need* the name server-side. You can just have the translate component and fit that in somewhere in whatever string somewhere.

**Comment by justEli** [comment]
> Is it really a hassle? `Component.translatable(Material.DIRT.getTranslationKey)`?

You're still not quite there yet with that tho. I'm proposing a `String` of a more proper name for items, instead of it being bound to (outdated) Material names.

**Comment by Machine-Maker** [comment]
If this string you want is getting sent to the client at any point, it's not good practice to use anything other than a Translatable component.

**Comment by RezzedUp** [comment]
While it is certainly preferable that client-facing messages utilize translatable components, there are circumstances where the client way of naming things is desired on the server itself. This data exists in the server as-is, so why not expose it for those who need it? The *strong* preference for translatable components could also be noted in the javadocs for the proposed convenience method.

**Comment by Machine-Maker** [comment]
What are such circumstances? I can't really think of any off the top of my head.

**Comment by kashike** [comment]
We are not going to be offering a way to retrieve the translated name of blocks/items/etc. You're free to open a new issue regarding the rarity, though!

**Comment by justEli** [comment]
Logging; storing; displaying materials on a website; item names on signs/console; or just when you want it to be a fancier name than (outdated) Material names... oh ok

**Comment by kashike** [comment]
For what it's worth, if you are wanting something for logging purposes, you should use something like `Material.STONE.getKey().asString()` - this will return a string like `minecraft:stone`. This is good for one reason mainly: there are times when the translated name of blocks has changed, but the registry key remains the same.

**Comment by Malfrador** [comment]
> What are such circumstances? I can't really think of any off the top of my head.

Using the name with other plugins, mainly. For example, displaying the name in a hologram or on a scoreboard or in a Placeholder.
If the API of all those plugins would support adventure, that might be possible with translatable components, but we are very very far from that. 

And for holograms, the client might not even display translatable components for displaynames (at least they are not used that way in vanilla, I haven't tried it). Using Components for Placeholders also seems somewhat awkward.

Also, the server already has that information. Adding API for it wouldn't be much effort and also has no maintenance work associated with it.
