### ISSUE TITLE
Add Contracts for ConfigurationSection

### ISSUE THREAD

**Issue by imDaniX** [PaperMC/Paper#5354]
**Is your feature request related to a problem? Please describe.**
Sometimes it's just annoying when you get warnings in IDE because of `@Nullable` in `ConfigurationSection#get(String, Object)` and `ConfigurationSection#getString(String, String)`.

**Describe the solution you'd like**
Add `@Contract("_, !null -> !null")` to it.

**Comment by MiniDigger** [comment]
good idea, do you wanna PR that?

**Comment by imDaniX** [comment]
@MiniDigger Never tried making patches before, but I guess I will try to, why not.

**Comment by imDaniX** [comment]
Closed due to https://github.com/PaperMC/Paper/commit/fdf2a59d59ef66764ceb5bfc1b09846dda0b726e
