### ISSUE TITLE
Client-side ejecting off boat while entering

### ISSUE THREAD

**Issue by AlexanderMandera** [PaperMC/Paper#5355]
### What behaviour is expected:
If you are placing a boat and try to enter it with high CPS, you should stay in the boat every time.

### What behaviour is observed:
If you are placing a boat and try to enter it with high CPS (>=10-15 clicks per seconds),
sometimes the player is ejected off the boat client-side, but is sitting in the boat server-side.
Other players can see the player inside the boat and interact with him (damaging)
and the bugging player swims away and cannot do anything.

The player is back at the position of the boat, when the boat is breaking or the player is pressing Shift.

Additionally, the console outputs "moved wrongly" messages:
```
[13:22:40 WARN]: Boat (vehicle of xxx) moved wrongly! 1.0034088392705627
[13:22:44 WARN]: Boat (vehicle of xxx) moved wrongly! 0.2675403361151041
[13:22:44 WARN]: Boat (vehicle of xxx) moved wrongly! 0.3670504549881741
[13:22:44 WARN]: Boat (vehicle of xxx) moved wrongly! 1.375
[13:22:44 WARN]: Boat (vehicle of xxx) moved wrongly! 1.1769468044596465
[13:22:44 WARN]: Boat (vehicle of xxx) moved wrongly! 1.375
[13:22:44 WARN]: Boat (vehicle of xxx) moved wrongly! 1.1967521287356533
[13:22:46 WARN]: Boat (vehicle of xxx) moved wrongly! 1.1539893569874096
[13:22:46 WARN]: Boat (vehicle of xxx) moved wrongly! 1.0597690340390784
```

We don't know if it the cause are the high CPS, but we could only reproduce it with that condition.
Six different players were able to reproduce the bug with it.

### Steps/models to reproduce:

1. Place boat
2. Entering boat usually with high clicks per second (>= 10-15, you can also use auto-clicker)
3. Try until you are ejected without pressing Shift
4. Use another player to look if you staying in the boat while swimming

Reproducing video (with the bug happening on second 4 to 5):
[![Reproducing Video](https://puu.sh/HoNxv/9f239fe014.png)](https://youtu.be/28nyHSKTLnk?t=2 "Reproducing Video")

My view after second 13:
![Minecraft Screenshot](https://user-images.githubusercontent.com/3356015/111036377-3a2fdd00-841f-11eb-9970-b61eb0baa99f.png)

I could not reproduce it by myself, but 4-5 other players on servers did and showed it to me.
It happened with custom clients like "Lunar Client" or "Badlion Client"
as well as on the default Vanilla client (where we could reproduce it once in the first 5 tries).

### Plugin list:
I have tested on a server with no plugins and on another with multiple plugins as well.
So no plugin could cause the bug.

### Paper version:
`This server is running Paper version git-Paper-547 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

### Anything else:
I will look into the server code too to find that issue, but I have not done any changes recently.
If I find something new, I will let you know. 😄 

If you have any questions about the bug, don't hesitate to ask me.
I hope the bug will be found soon 👍

**Comment by embeddedt** [comment]
I can confirm similar types of desync behavior on my 1.16 server when rapidly entering/exiting a boat. Vanilla 1.16 has some bugs with boat desyncs that are still not corrected in 1.16.5 to the best of my knowledge, however, there are fixes in the 1.17 snapshots. 

I'm not sure if this is something Paper can fix as the client might also be part of the problem.

**Comment by Gnomey123** [comment]
I still find this issue with boats all the time.
I personally think the entire boat collision manager needs to be rewritten (or heavily looked at, whichever is easier to do).

Things from standing on boats, pushing them, entering and exiting, and movement give all sorts of confusion on the server's end, with the only thing being in common is the same error message sent 20x times:

[xx:xx:xx WARN]: Boat (vehicle of xxx) moved wrongly! 0.2675403361151041

It should also be noted that I don't have any lag, anti-cheat, or any heavy plugins. I also run PaperMC on a nearby server provider with 6GB of ram.

**Comment by electronicboy** [comment]
Pretty sure that this is a client bug of which we have 0 means to resolve

**Comment by electronicboy** [comment]
> [xx:xx:xx WARN]: Boat (vehicle of xxx) moved wrongly! 0.2675403361151041

that confirms it, this is a desync between the server and the client, likely: https://bugs.mojang.com/browse/MC-202202
