### ISSUE TITLE
Modification of `commands` from PlayerCommandSendEvent not working properly!

### ISSUE THREAD

**Issue by TheFruxz** [PaperMC/Paper#5361]
### What behaviour is expected:
custom command-list output

### What behaviour is observed:
no commands output!

### Steps/models to reproduce:
```
    @EventHandler
    fun onCommandPreview(event: PlayerCommandSendEvent) {

        event.commands.clear()
        event.commands.add("test")

    }
```

### Plugin list:
LuckPerms, Multiverse-Core, ProtocolSupport

### Paper version:
git-Paper-529 (MC: 1.16.5)

### Anything else:
Used mutable commands list

**Comment by electronicboy** [comment]
You cannot add commands to this list manually due to how the entire system works, it would need to create a dummy command structure to add to the thing, might be easier to just actually register the commands properly

**Comment by TheComputerGeek2** [comment]
This looks like it is behaving as expected as per documentation (it explicitly says that adding elements is not supported and is undefined behavior. only supported operations are removal)
