### ISSUE TITLE
Player List Health Always Displays as Integer when set in Bukkit's API

### ISSUE THREAD

**Issue by Wyatt-James** [PaperMC/Paper#5362]
### What behaviour is expected:
Player health shown as hearts when using RenderType.HEARTS.

### What behaviour is observed:
Player health is shown as an Integer.

### Steps/models to reproduce:
In a Bukkit plugin, execute this code:

```java
Scoreboard mainScoreboard = Bukkit.getScoreboardManager().getMainScoreboard();
Objective healthDisplay = mainScoreboard.registerNewObjective("health", "health", "Health", RenderType.HEARTS);
healthDisplay.setDisplaySlot(DisplaySlot.PLAYER_LIST);
```

### Plugin list:
Just a testing Plugin as described above.

### Paper version:
git-Paper-547 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Anything else:
Works as expected with scoreboard command.

Started happening in Paper-473.
Works correctly in Spigot.

**Comment by montlikadani** [comment]
Third parameter of `Scoreboard#registerNewObjective` method requires `Component` as display name. So just deserialize the `Health` name using
```java
PlainComponentSerializer.plain().deserialize("Health")
```
for temporary solution. Obviously if you have Paper dependency.

**Comment by kashike** [comment]
> ```java
> PlainComponentSerializer.plain().deserialize("Health")
> ```

or `Component.text("Health")` :wink:

**Comment by Wyatt-James** [comment]
> for temporary solution. Obviously if you have Paper dependency.

Or alternately just run as a command with the console command sender.

**Comment by Wyatt-James** [comment]
Thanks 👍
