### ISSUE TITLE
Creating a sign with LockettePro broke after Adventure update

### ISSUE THREAD

**Issue by perseus5** [PaperMC/Paper#5363]
### What behaviour is expected:
https://cdn.discordapp.com/attachments/474446899336708097/820774780625616896/unknown.png
### What behaviour is observed:
https://cdn.discordapp.com/attachments/699736158892195851/820775920461807696/Screen_Shot_2021-03-14_at_4.45.30_PM.png
### Steps/models to reproduce: 
Creating a LockettePro sign 
### Plugin list:
___A list of your plugins___
LockettePro
### Paper version:
https://github.com/PaperMC/Paper/tree/808bd9198664938af58e98e622c41902343587e0

**Comment by kashike** [comment]
Please provide the full, unmodified, output of the `/version` command.

**Comment by perseus5** [comment]
I just made a blank test server with latest paper to replicate.

```
[22:15:47 INFO]: Checking version, please wait...
[22:15:48 INFO]: This server is running Paper version git-Paper-549 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-545 (MC: 1.16.5)
```

Also should've added this as well, I apologize:
- Download ProtocolLib
- `enable-uuid-support: true` in /plugins/LockettePro/config.yml

**Comment by JRoy** [comment]
Looks like this works as intended, UUID support on that plugin literally writes the uuid to the sign.

**Comment by perseus5** [comment]
Just reverted to before the adventure update, works fine
https://cdn.discordapp.com/attachments/505599000833949700/820784783642460170/Screen_Shot_2021-03-14_at_5.25.23_PM.png

**Comment by kashike** [comment]
https://github.com/brunyman/LockettePro/blob/master/LockettePro/src/me/crafter/mc/lockettepro/Utils.java#L167-L196

**Comment by perseus5** [comment]
I see that yes, but it worked before the adventure update? is their "hack" or whatever they did to make the uuid invisible now handled correctly with the latest paper? If so, completely understand and will go pound sand elsewhere trying to come up with a solution.

**Comment by kashike** [comment]
What version of ProtocolLib are you using?

**Comment by perseus5** [comment]
4.6.0 https://www.spigotmc.org/resources/protocollib.1997/

**Comment by kashike** [comment]
You need to use the latest snapshot version of ProtocolLib.

**Comment by perseus5** [comment]
oh wow, that was it! sorry for the troubles... thank you!

**Comment by perseus5** [comment]
I just realized I was still on the pre adventure paper after putting on the updated protocol lib, which is why it worked. I updated  back to latest paper and it's still happening. I feel like I can just rewrite Lockette so it uses persistent data container or something since what's happening now seems to be the correct behavior here... thoughts?

**Comment by JRoy** [comment]
At this point you've lied about your plugins, Paper version, and probably about even being on Paper in the first place. Please stop trying to hide whatever you're trying to hide and fill out the entire issue template again like you would, and provide detailed reproduction steps on **the latest Paper version**.

**Comment by kashike** [comment]
Cannot reproduce.
![2021-03-14_19 17 12](https://user-images.githubusercontent.com/5474071/111095175-25744780-84fa-11eb-9978-cf488d0b57b5.png)

**Comment by perseus5** [comment]
on the same setup as you, is `enable-uuid-support: true` in /plugins/LockettePro/config.yml enabled?

**Comment by kashike** [comment]
This is a plugin issue - LockettePro is doing stupid things:
https://github.com/brunyman/LockettePro/blob/master/LockettePro/src/me/crafter/mc/lockettepro/DependencyProtocolLib.java#L64-L82
https://github.com/brunyman/LockettePro/blob/master/LockettePro/src/me/crafter/mc/lockettepro/Utils.java#L322-L335

**Comment by perseus5** [comment]
bummer, will have to find a different plugin or rewrite it I guess. thanks anyways kashike : )
