### ISSUE TITLE
Repeated error, disconnects users

### ISSUE THREAD

**Issue by sudoShiba** [PaperMC/Paper#5365]
### Link/paste of stack trace

https://pastebin.com/wa0xJxhZ

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___
This is the glitch, it continuesly prints that and disconnects me

### Plugin list:
___A list of your plugins___
- BottledExp 2.2.8.2
- Dynmap 3.1-beta7-spigot.jar
- Dynmap-WorldGuard-1.2
- EssentialsX 2.18.2.0
- EssentialsXChat  2.18.2.0
- LuckPerms-Bukkit 5.3.0
- NametagEdit
- worldedit-bukkit 7.2.3
- worldguard-bukkit 7.0.4
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Join

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
550 (MC: 1.16.5)

**Comment by Proximyst** [comment]
Your server is just extremely overloaded.

**Comment by sudoShiba** [comment]
> Your server is just extremely overloaded.

I gave it 6G of ram, is that not enough. Should I remove some plugins. It did run on normal spigot

**Comment by aurorasmiles** [comment]
We don't know. You provided nearly no information at all, so we can't really help  you with that. I'd suggest joining our discord for more support

**Comment by sudoShiba** [comment]
> We don't know. You provided nearly no information at all, so we can't really help you with that. I'd suggest joining our discord for more support

I went to the discord and even when romoving all my plugins and datapacks, performance still sucked. I found that when i made a new server while adding plugins one by one, I found that using vault caused the issue and when I removed it it didn't work.

Maybe I should make a new issue idk

**Comment by aurorasmiles** [comment]
Vault just provides an interface for other plugins to use, it's likely not the issue. Your approach is right, but next time start adding Vault and other libraries first before adding other plugins to find the actual culprit

**Comment by sudoShiba** [comment]
> Vault just provides an interface for other plugins to use, it's likely not the issue. Your approach is right, but next time start adding Vault and other libraries first before adding other plugins to find the actual culprit

it doesnt really matter I cant use my world in a server
