### ISSUE TITLE
Improvements to PotionType + PotionData

### ISSUE THREAD

**Issue by Owen1212055** [PaperMC/Paper#5366]
Currently retrieving potion effects is quite limiting and a hassle to deal with. It seems like what is currently in place does not support the modern-day potions that we have. For example, there are potion types that now can contain multiple effects. (See, turtle master potion)

It is also not very easy to get the duration/amplifier of potions without dealing with "extended" and "upgraded".
![image](https://user-images.githubusercontent.com/23108066/111205060-2e6a2500-859d-11eb-985e-fb9f7e51c537.png)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

- An easy way to get List\<PotionEffect\> from PotionData. This would take into account extended + upgraded and give the corresponding effects. So potions like turtle master would return two effects.
- Adding support for multiple potion effect types from PotionType. Currently certain potions can have multiple effects on them by default, for example the turtle master potion. The system currently in place does not support this, as it only displays the slowness effect instead.
![image](https://user-images.githubusercontent.com/23108066/111206186-70e03180-859e-11eb-8c1a-dfb20c507a54.png)

**Describe alternatives you've considered**
There really aren't any very easy alternatives that work nicely. You would need to store all of this yourself, so instead, I just use NMS to deal with this. However, it would be great if this could be officially supported because I feel that others may benefit from this as well.

**Additional context**
N/A

**Comment by Owen1212055** [comment]
I cast you away, silly stale bot.

**Comment by electronicboy** [comment]
https://www.youtube.com/watch?v=ib084tzN8H0

**Comment by electronicboy** [comment]
This API has pretty much always been cludgy to work with and could probs just do with a replacement drafting for the API here as a whole rather than trying to expand it, maybe
