### ISSUE TITLE
add seed for dungeons in config

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5369]
**Is your feature request related to a problem? Please describe.**
Players are reversing seed with dungeons

**Describe the solution you'd like**
Paper should have a dungeon seed salt configuration option

**Describe alternatives you've considered**
Running a roblox server instead

**Additional context**
Patches have already been made for this, eg: https://github.com/pl3xgaming/Purpur/blob/ver/1.16.5/patches/server/0089-Configurable-dungeon-seed.patch

**Comment by e-im** [comment]
duplicate of #3909.
