### ISSUE TITLE
Health objective in a non-default scoreboard isn't updated

### ISSUE THREAD

**Issue by TheKinrar** [PaperMC/Paper#5370]
Here's some code for context.
```java
@EventHandler
public void onJoin(PlayerJoinEvent e) {
    e.getPlayer().setScoreboard(Bukkit.getScoreboardManager().getNewScoreboard());
    Objective healthObjective = e.getPlayer().getScoreboard().getObjective(DisplaySlot.BELOW_NAME);
    if (healthObjective == null) {
        healthObjective = e.getPlayer().getScoreboard().registerNewObjective("health", "health", Component.text("HP"));
        healthObjective.setDisplaySlot(DisplaySlot.BELOW_NAME);
    }
}
```
When a player joins, it creates a new scoreboard and applies it to them.
Then, it creates a new objective that should show players' health below their name.

### What behaviour is expected:
Players' health should show below their name and update when damage is taken or health is regenerated.

### What behaviour is observed:
It shows 0 health on login and never updates.

### Steps/models to reproduce:
Just create a plugin with that snippet and add it to your Paper installation.

### Plugin list:
Only my test plugin.

### Paper version:
`This server is running Paper version git-Paper-551 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

### Anything else:
This bug only happens since Paper went on an Adventure in 4e958e229f9f448a10dbc610bab460dbf222902e.
I tested with builds 472, 473 (Adventure) and 551.
It works fine in 472, but the issue is present in both 473 and 551 (latest at the time of writing).

Using a custom scoreboard created with getNewScoreboard() is important. It works fine using the default scoreboard.

In the above code I set a display name for the objective using Adventure's Component but this doesn't matter. Using Component.text, Component.empty, null or using deprecated String names do not affect the outcome.

**Comment by Machine-Maker** [comment]
This also affects the `food` criteria, and I'm guessing *all* of the built in ones.

EDIT: I think I found the issue. While rebasing after updating CraftScoreboard to adventure, one patch added some functionality that was commented out with no conflicts so it went totally unnoticed as missing in the new registerNewObjective method.
