### ISSUE TITLE
Being able to prevent Skull profile loading

### ISSUE THREAD

**Issue by Owen1212055** [PaperMC/Paper#5374]
Currently, if you would like to set the player of a player head for SkullMeta it causes it to load the player profile from Mojang when it is applied to items. This causes the server to load the head synchronously which can take a LONG time or even crash the server at times.

Unless there is some sort of plan for async player profile loading, I think that there should be a way to apply profiles to heads without requiring them to be loaded synchronously on the server. This does however cause some lag client-side but I feel this is much better than stalling the entire server.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like a way to apply a PlayerProfile to a skull but add an option to prevent the profile from being loaded.
For example, it would appear like this and the client would load it accordingly instead of the server.
``{id:"minecraft:player_head",tag:{SkullOwner:"Owen1212055"},Count:1b}``

Currently, if you have an item like that and it is refreshed it looks something like:
``{id:"minecraft:player_head",tag:{SkullOwner:{Name:"Owen1212055",Properties:{textures:[{Value:"ewogICJ0aW1lc3RhbXAiIDogMTYxNTkyMjQ5ODc1MCwKICAicHJvZmlsZUlkIiA6ICIzZjdlZGYyNGFmNzk0MTk3YWY1OGZjMzFlNGQ5NmU0MSIsCiAgInByb2ZpbGVOYW1lIiA6ICJPd2VuMTIxMjA1NSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OWY2OTc5NmU3N2U2ZmM0YWM0MWU0YTEyZmE1Mjc1YjcyNzlkMzZlM2I5NDI1NWVlYmI0NzgzNGZhNjJjYTZlIgogICAgfSwKICAgICJDQVBFIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lN2RmZWExNmRjODNjOTdkZjAxYTEyZmFiYmQxMjE2MzU5YzBjZDBlYTQyZjk5OTliNmU5N2M1ODQ5NjNlOTgwIgogICAgfQogIH0KfQ==",Signature:"WVF8AmzxQyCmFM6EpUDErRGX/L6MW3ur4/8BBbw+6LaADRgn3zJvX1PsJVRGWZzY6H/KuIieXIAwvkGl+/7zbMwKSKcCGQpI/QyiCypBqWGpTg1tPam3eCJM1WBZ8BjsswuSWijmDGgFKvaSMyCXe0fwOhPvHL2o+bGsqC0z8Uro4ppTViu5g3x53SXpiCyWq7N+tflTMpxnfgW+2j6ZOS0/tgkXEvajFosBnV/zE1d6BZTzq7umGoEMUIiwc9DAb51YoraHMXiVxjGnfT/EeiypyRq0XVOUC93aCrk7NsGk9QnczGbEq/n5AjiVnVtElcjyucY6noGRueIPP/jXNxEpqBEBMBK9cEru10VBAAHC6fVxweCenCSP/9UP1A02Zp4nf0SVn5a77QRA0/cMDnYHHnkaLXAJ3/gF0QIex8+qbaEiOgNr4mMTk1XewO3AcPuh19b6VnFIOcZk260aen7ktQfyCDuD29gh9A4axP3iy5ch8awilnBSryinGKQkU5/M8AxrtCsbm68ejo67YxcznZ7HtdcId2ReqbWiV1hiwSypIoW90nMkDjCFldfq4Ct1JAeH++zO2IuvNTblSADKqpvjMST6aDieqdtWlTv4nHNcQCCFpmApUotnKSvJl1zeXh4wGhDD5i9EtSZpUwluuKIbrPvLI4aIzCKzqRM="}]},Id:[I;1065279268,-1351007849,-1353122767,-455512511]}},Count:1b}``

**Describe alternatives you've considered**
Unfortunately, it is very difficult to work around this. Trying to edit the nbt directly causes it to be edited shortly after. (All skulls without a texture value appear to be manually loaded when the item is updated)

**Additional context**
N/A

**Comment by JRoy** [comment]
`SkullMeta#setOwner` can be called async so long as you do `ItemStack#setItemMeta` on the main thread when it completes.

**Comment by electronicboy** [comment]
This cannot be fixed without losing track of item updates, the logic to resolve this specific trait of the API is far from viable to do safely and consistently, this is something you'll need to work into your control flow.

**Comment by Owen1212055** [comment]
> `SkullMeta#setOwner` can be called async so long as you do `ItemStack#setItemMeta` on the main thread when it completes.

I can't do that, the loading is done when it is applied to the item sadly.
![image](https://user-images.githubusercontent.com/23108066/111377621-3f876480-8677-11eb-8f69-1a6df88d6f12.png)

So the only thing I can think of here is to manually call this getUnchecked method to have it so the profile is cached.

**Comment by electronicboy** [comment]
PlayerProfile#complete, then set

**Comment by Owen1212055** [comment]
> PlayerProfile#complete, then set

Ah okay, thank you!
