### ISSUE TITLE
Automatic Translation of Item Displayname Translatable Components

### ISSUE THREAD

**Issue by mcmdev** [PaperMC/Paper#5377]
**Is your feature request related to a problem? Please describe.**
I've been very happy to see the Translation capabilities of Adventure already being built into paper, but sadly, for item names the GlobalTranslator#render Method has to be used manually to get a translation.

**Describe the solution you'd like**
Although getting the player who receives an item might be a little harder to do then just sending a text message, I'd love to see Items get translated automatically the way Messages or Inventory Titles get translated, as it would reduce a few lines and would keep in line with other places where Components are now used.

**Describe alternatives you've considered**
The solution with calling the GlobalTranslator#render Method is working, but it requires a Locale and a few lines of extra code It's more of a request to have union with the other component features.

**Comment by Proximyst** [comment]
You're gonna have to show what you're doing, as that worked fine when we merged the PR.

**Comment by mcmdev** [comment]
Sure!
My server is running git-Paper-553 (MC: 1.16.5)

**Code:**
```java
    @Override
    public void onEnable() {
        GlobalTranslator globalTranslator = GlobalTranslator.get();

        TranslationRegistry translationRegistry = TranslationRegistry.create(Key.key("translationtest", "main"));

        translationRegistry.register("abc.myKey", Locale.US, new MessageFormat("This is a test."));
        translationRegistry.register("abc.myKey", Locale.GERMAN, new MessageFormat("Dies ist ein Test."));

        globalTranslator.addSource(translationRegistry);

        TranslatableComponent translatable = Component.translatable("abc.myKey");

        getCommand("ttest").setExecutor((sender, command, label, args) -> {
            sender.sendMessage(translatable);

            Player player = (Player) sender;

            ItemStack itemStack = new ItemStack(Material.STONE);
            ItemMeta itemMeta = itemStack.getItemMeta();
            itemMeta.displayName(translatable);
            itemStack.setItemMeta(itemMeta);
            player.getInventory().addItem(itemStack);
            return true;
        });
    }
```

**Result:**
The message in chat gets translated, the Item does not.
![example](https://user-images.githubusercontent.com/30979070/111505707-32d34100-8749-11eb-8356-2d481fac4b91.PNG)

**Comment by zml2008** [comment]
This isn't really possible without intercepting item NBT on send -- the translated data can't be stored since items can be transferred from player to player.

If you really need translation for items, your best bet is to use a resource pack -- since you'll probably already have one once you're getting into custom items.

If that's not possible I suppose you could track your custom items manually and update their names when transferred from player to player and when players change their language as well.

Either way, I doubt this is something Paper could effectively handle without it being a maintenance nightmare.
