### ISSUE TITLE
Problem with right to left languages

### ISSUE THREAD

**Issue by Elioz** [PaperMC/Paper#5378]
### What behaviour is expected:
This issue is related to right to left languages only (Hebrew, Arabic),
And this is really strange thing, when using the command /r to reply to private message,
this is the output and the server is not recgonized it as command, here is the example from my console
Knoobler issued server command: /rשלום

### What behaviour is observed:
So in the previous example, when writing /r with hebrew word right after, it not accepting the space right after the /r and execute it as one word, BUT, pay attention to this,
Knoobler issued server command: /a שלום
When executing it with other letter, it recognize the space, this issue is happing only with /r and any other letter will work.

### Paper version:
git-Paper-553 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by e-im** [comment]
`/r` isn't a paper command, but is often provided by plugins such as essentials. Are you able to reproduce this with default commands?

**Comment by e-im** [comment]
Closing as cannot reproduce, if you are still experiencing this issue with any paper-provided command on 1.17.1, leave a comment.
