### ISSUE TITLE
Old villagers

### ISSUE THREAD

**Issue by Ielelele29** [PaperMC/Paper#5385]
I would like to be able to reimplement the mechanics of the villagers of the old versions, disabling the changes made to their functioning in the 1.14 update, and thus reactivating the mechanics of the previous versions. I think a config is suitable for this update.

**Comment by MiniDigger** [comment]
you gonna need to to provide more info.
do you want to change the village mechanics to be more like vanilla? then you would need to specify what we "broke".
do you want to change the village mechanics back to some old version? thats most likely out of scope of paper and better suited for a plugin.
