### ISSUE TITLE
cancelling EntityChangeBlockEvent creates ghost blocks

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5386]
### What behaviour is expected:
When cancelled, the gravel block doesn't fall.

### What behaviour is observed:
When cancelled, the gravel block doesn't fall but the client thinks it is air when serverside its still gravel, creating a ghost block

### Steps/models to reproduce:
@EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onBlockFall(EntityChangeBlockEvent e) {
        if (e.getTo() == Material.AIR && e.getEntityType() == EntityType.FALLING_BLOCK) {
                e.setCancelled(true);
        }
    }

### Paper version:
558 1.16.5

**Comment by Trigary** [comment]
A "plugin-side" solution is to call `event.getBlock().getState().update(false, false);` when cancelling the event.
