### ISSUE TITLE
The server crashed for no reason

### ISSUE THREAD

**Issue by DorrD** [PaperMC/Paper#5388]
Hi there. A few weeks ago I experience a very annoying and unplayable problem, since every little time the server is open, it closes automatically. The most recent log and where it happened: https://pastebin.com/fdAZy9uZ

**Plugin list:**
![image](https://user-images.githubusercontent.com/42490993/111832798-854f6180-88f1-11eb-860c-85a2131d78c1.png)

**Paper Version:**
![image](https://user-images.githubusercontent.com/42490993/111832875-9ef0a900-88f1-11eb-8783-159cee8683cc.png)

What I think the cause is the following that I located: (debug allow)
![image](https://user-images.githubusercontent.com/42490993/111833041-dcedcd00-88f1-11eb-9b26-20443725160f.png)

**Comment by NotMyFault** [comment]
> [19:15:22] [Server thread/INFO]: [ShopGUIPlus] Enabling ShopGUIPlus v1.49.2
[19:15:22] [Server thread/INFO]: [ShopGUIPlus] Downloaded from https://directleaks.net

👀

**Comment by DorrD** [comment]
@NotMyFault The problem was when I added the new plugins, and I put these in and it started to give problems from then on. And I already tried to remove the plugins one by one, to locate it, but continue. These were the plugins I added and they started: 
![image](https://user-images.githubusercontent.com/42490993/111833840-04916500-88f3-11eb-830c-3e13d72c16be.png)

**Comment by Proximyst** [comment]
Not a Paper problem, and completely uninterested in helping someone who gets their plugins through piracy.
