### ISSUE TITLE
ChatFormat (for AsyncChatEvent) should include Player instead of displayName

### ISSUE THREAD

**Issue by hawkfalcon** [PaperMC/Paper#5395]
**Is your feature request related to a problem? Please describe.**
I'm finding the new ChatFormatter a little hard to use. All it provides (in chat()) is displayName and message, not player or even a player name. So looking up information, I have to use displayName, which could theoretically be the same for multiple players. It's also hard to look up player information or even just get a Vault prefix.

**Describe the solution you'd like**
I would like the chat() in ChatFormatter to take a Player instead of a displayName

**Describe alternatives you've considered**
Pass a player name or UUID. I have a workaround, which is to set the output to JUST the message and do everything in the message.

**Additional context**

**Comment by Machine-Maker** [comment]
You have access to the player object in AsyncChatEvent do you not?
```java
public void onChat(AsyncChatEvent event) {
    Player player = event.getPlayer();
    event.formatter((displayName, message) -> ofChildren(displayName, text(MoreObjects.firstNonNull(player.getClientBrandName(), "<none>")), message));
}
```

**Comment by hawkfalcon** [comment]
You do, and something like that *works*, but it doesn't let you do it elsewhere, e.g. if you make class implementing ChatFormatter. It feels like a workaround.
