### ISSUE TITLE
Italic Text on ItemStacks

### ISSUE THREAD

**Issue by janLindner** [PaperMC/Paper#5399]
### What behaviour is expected:
When defining the display name and lore of an `ItemStack` the text should not always be italic. 

### What behaviour is observed:
When using the new Components and the legacy serializer to create components the display name and lore of a created item is always italic. This does not happen when using the deprecated methods with just `String`.

Using Components: 
![image](https://user-images.githubusercontent.com/18546571/111920027-00994a80-8a8d-11eb-8566-a71f78d2d641.png)

Using legacy converter:
![image](https://user-images.githubusercontent.com/18546571/111920047-1e66af80-8a8d-11eb-8a68-5f05ddc8aef1.png)

### Steps/models to reproduce:
```java
final Component displayName = Component.translatable(
  material.getTranslationKey(),
  NamedTextColor.GRAY,
  TextDecoration.BOLD
);
anyMeta.displayName(displayName);

final Component lore = List.of(...components...)
anyMeta.lore(lore)
```

### Plugin list:
ProtocolLib

### Paper version:
This server is running Paper version git-Paper-562 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by kezz** [comment]
Components inherit styling from the parent condition which, in the case of item stacks, is italics. You can set a style of italic to false to prevent this. It's not a bug.

**Comment by zml2008** [comment]
Components need to explicitly be set to have their decorations non-italics. See https://jd.adventure.kyori.net/api/4.7.0/net/kyori/adventure/text/Component.html#decoration(net.kyori.adventure.text.format.TextDecoration,net.kyori.adventure.text.format.TextDecoration.State)
