### ISSUE TITLE
Whitelist 'player does not exist' Server

### ISSUE THREAD

**Issue by PureVanillaFrance** [PaperMC/Paper#5402]
### What behaviour is expected:
whitelist add player -> player is whitelisted

### What behaviour is observed:
whitelist add player -> player does not exist

### Steps/models to reproduce:
go inside console and whitelist add player -> does not work
I have to do it manually with uidd in the .yml and /whitelist reload -> works and player is whitelisted

### Plugin list:
CoreProtect, DiscordSRV, EntityDetection, PL-Hide, VillagerLobotomizatorNator, VillagerOptimiser, Votifier, VotingPlugin

### Paper version:
paper 562

### Anything else:
![image](https://user-images.githubusercontent.com/76930233/111974306-91a90980-8aff-11eb-99ed-a020149ef5df.png)
![image](https://user-images.githubusercontent.com/76930233/111974318-940b6380-8aff-11eb-8fde-9e0116ef7699.png)
![image](https://user-images.githubusercontent.com/76930233/111974325-95d52700-8aff-11eb-91b8-c7fd307756ef.png)

--------------------

![image](https://user-images.githubusercontent.com/76930233/111974341-9a014480-8aff-11eb-81f6-497840bad698.png)
![image](https://user-images.githubusercontent.com/76930233/111974346-9bcb0800-8aff-11eb-87f6-31dbc127afb3.png)

_

**Comment by Proximyst** [comment]
![https://uwu.whats-th.is/4UuiRAs.png](https://uwu.whats-th.is/4UuiRAs.png)

Cannot reproduce. Are you running online mode?

**Comment by PureVanillaFrance** [comment]
Online mode is on for sure.

**Comment by PureVanillaFrance** [comment]
Did you try to reproduce with all plugins ?
My hosts says it can't comme from them

**Comment by TheKinrar** [comment]
I've just tried adding a player to whitelist while preventing Paper from connecting to Mojang's servers, and it failed with that same `That player does not exist` message, so this might be some network issue on your side?

**Comment by TheKinrar** [comment]
Are you able to add a player who has already joined before?

**Comment by PureVanillaFrance** [comment]
Player who is already on works.
It works manually for new players (add in .yml)but not with console

**Comment by Proximyst** [comment]
Can you reproduce without plugins? If you still can't whitelist, this is an issue with your host.

**Comment by PureVanillaFrance** [comment]
Same issue with no plugins 
![image](https://user-images.githubusercontent.com/76930233/111977665-498be600-8b03-11eb-801c-637890baae24.png)

**Comment by PureVanillaFrance** [comment]
I will try updating paper to 564

**Comment by Proximyst** [comment]
Then this is an issue with your host. Nothing we can do.

**Comment by PureVanillaFrance** [comment]
Ok so we tried with the host.
We changed machines, removed all plugins and even try to go on spigot.

The issue is the same and does not come from the version of java or minecraft or the machine from host.
What could it be then ?

**Comment by Proximyst** [comment]
I'd suggest you join our [Discord](https://discord.gg/papermc) or IRC on EsperNet to the `#paper-help` channel. Ready yourself with all server configuration files and your startup script in a https://paste.gg/ so we can help you accordingly.

**Comment by JXSnack** [comment]
Any update on how it got fixed? I am having the same issue too right now and I really need help

**Comment by MiniDigger** [comment]
see proxis comment, please join our discord if you need help instead of bumping a 3 year old closed issue
