### ISSUE TITLE
Moving invulnerable end crystals through end exit portal permanently breaks spawn chunks where it appears

### ISSUE THREAD

**Issue by LysergikProductions** [PaperMC/Paper#5404]
### What behaviour is expected:
The invulnerable end crystal appears at spawn, and remains moveable with flying machines. Surrounding area does not break.

### What behaviour is observed:
After the invulnerable crystal is teleported to spawn where a build-height obsidian platform is found, it appears at build height within the spawn chunks. The surrounding area relative to the crystal position (not limited by chunk borders) becomes completely broken. Users cannot break or place any blocks in the affected area. The behaviour continues even if the crystal is removed.

### Steps/models to reproduce:
0) Set world spawn to a known location, and build an obsidian platform at that location at build height
1) Defeat the ender dragon for the first time
2) Build a flying machine just outside the range of the end spike reset radius that will align such that when moving can push the newly spawned end spike crystal toward the end's exit portal
3) Start the ender dragon summon sequence normally, and after the targeted end spike resets, start the flying machine
4) Stop the flying machine so it will be positioned above the exit portal
5) Using another flying machine or manual piston pushing, push the invulnerable end crystal through the end exit portal
6) Once through, follow the end crystal through the portal
7) Observe issue

### Plugin list:
https://github.com/dmulloy2/ProtocolLib
https://github.com/gcurtiss/protocol3/tree/main/protocol3
https://github.com/Arnuh/ArmorEquipEvent

### Paper version:
git-Paper-446 (MC:1.16.5) (Implementing API Version 1.16.5-R0.1-SNAPSHOT)

### Anything else:
![2021-03-21_07 12 22](https://user-images.githubusercontent.com/61183022/111999928-d75fd500-8af3-11eb-9ebd-e1960420c338.png)

The affected area is not bound by chunks but is a radius area from the center of the crystal
I have not tested this in a way that the crystal would spawn below build height. Build height may be the issue here.
This ability to move the invulnerable crystal does not break vanilla Minecraft as seen here:
https://www.youtube.com/watch?v=h4xR_X4PrUw&ab_channel=RaysWorks

**Comment by e-im** [comment]
No longer relevant as of a04ad7b, if you are still experiencing this on 1.17.1 without having changed that config, leave a comment.
