### ISSUE TITLE
Server chunk crash

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#541]
Crash report: http://pastebin.com/BPG3dLdp
Paper build: 961

**Comment by zachbr** [comment]
Your server couldn't keep up, if I remember correctly that specific stack usually corresponds to someone moving around very quickly.

**Comment by SecretlyJealous** [comment]
Is this crash similar too? https://hastebin.com/hejamularu.md

**Comment by Black-Hole** [comment]
No, that's a new one, have a look at https://hub.spigotmc.org/jira/browse/SPIGOT-2944
