### ISSUE TITLE
1.16 chunks on 1.12 server

### ISSUE THREAD

**Issue by codergautam** [PaperMC/Paper#5411]
### Expected behavior

world loads
--
ok so me and my friends are making a minecraft server but we messed up. when we started we used 1.16 and used protocolsupport to allow 1.8 clients. but then as our server grew larger and we added more stuff we started to see lots of lag and stuff. and i found out that 1.12 is better for performance. so when we tried to switch the jar the chunks wouldnt load. I know that there is a lot of difference between 1.12 and 1.16 chunk loading, but we really dont want to remake our server. is there any way or a plugin that converts the 1.16 chunks into 1.12?

### Observed/Actual behavior

a bunch of errors and server crash

### Steps/models to reproduce

open a 1.16 server
change the 1.16 jar to 1.12
see bunch of errors and server crash

### Plugin list

none

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Chew** [comment]
You cannot downgrade your world to a prior version. This is going to lead to corruption. You'll need to stick to 1.16 or reset the world. Not much we can do. 1.12 is also not supported anymore.
