### ISSUE TITLE
SelectorComponents do not get resolved

### ISSUE THREAD

**Issue by Exlll** [PaperMC/Paper#5413]
### Expected behavior

Get a message that contains the full list of entities

### Observed/Actual behavior

Get message `@e`

### Steps/models to reproduce
```java
@Override
public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
    Component component = Component.selector("@e");
    sender.sendMessage(component);
}
```
### Plugin list

None, except the one I used to verify this behavior.

### Paper version

> version
[00:16:21 INFO]: Checking version, please wait...
[00:16:21 INFO]: This server is running Paper version git-Paper-567 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

Creating and sending `SelectorComponent`s does currently not work properly as the selector does not get resolved. I haven't tested it but same problem might apply to all component types listed [here](https://minecraft.fandom.com/wiki/Raw_JSON_text_format#Component_resolution) (i.e. `score`, `selector`, and `nbt`)

**Comment by zml2008** [comment]
This needs to have `ComponentUtils.updateForEntity(CommandSourceStack, Component, Entity, int depth)` exposed in-api somehow.

I did something quickly for this in SpongeAPI ([API](https://github.com/SpongePowered/SpongeAPI/blob/bcc994fd84049ff7630d9f241bedefa2d7ba815e/src/main/java/org/spongepowered/api/adventure/SpongeComponents.java#L84), [implementation](https://github.com/SpongePowered/Sponge/blob/98eac411982fbeaac1d5019c3151f502053dfcf1/src/main/java/org/spongepowered/common/adventure/SpongeAdventure.java#L758), [`ResolveOperation` implementations](https://github.com/SpongePowered/Sponge/blob/2d955d1ff741356b48917b458736448e7f833c6f/src/main/java/org/spongepowered/common/adventure/SpongeResolveOperation.java#L59)) a while ago -- feel free to grab whatever's useful from that.
