### ISSUE TITLE
Seemingly random paper crash

### ISSUE THREAD

**Issue by Ryan12439** [PaperMC/Paper#5420]
### Stack trace

https://paste.gg/p/anonymous/9b65055d567042889aa2b89a253d14a1

### Plugin list

BungeeBridge, Citizens, DisableJoinMessage, Luckperms, MongoSK, SimplePortals, Skellett, SkQuery, skRayFall, Skript, Skript-Yaml, skScraft, skUtilities, TAB, TuSKe (PikachuPatch), Vault, Vault Chat Formatter, Vixio, Worldedit.

### Actions to reproduce (if known)

Unknown

### Paper version

This server is running Paper version git-Paper-556 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 14 version(s) behind
Previous version: git-Paper-469 (MC: 1.16.5) 

### Agreements

- [ ] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
Outdated, also, https://paste.gg/p/anonymous/9b65055d567042889aa2b89a253d14a1#pastefile1-l615
