### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Specthra** [PaperMC/Paper#5424]
### Stack trace

https://paste.gg/p/anonymous/58f4c7a0ad054092968f51bee89c9eb2

### Plugin list

 Plugins: { ColoredSigns v4.2.0* com.github.sirblobman.colored.signs.ColoredSigns [SirBlobman], Chunky v1.2.29 org.popcraft.chunky.ChunkyBukkit [pop4959], BlockLocker v1.9.2 nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl [Rutger Kok], PlaceholderAPI v2.10.9 me.clip.placeholderapi.PlaceholderAPIPlugin [HelpChat], Iris v1.3.2 com.volmit.iris.Iris [cyberpwn, NextdoorPsycho], AdvancedHelp v1.12.7 me.codedred.advancedhelp.Main [Cmaaxx, CodedRed], PlayerReport v3.3.6 me.PCPSells.PRMain [PCPSells], TabCompleteFilter v1.0.8 lee.code.tcf.TabCompleteFilter [Lee], ViaVersion v3.2.1 us.myles.ViaVersion.ViaVersionPlugin [_MylesC, creeper123123321, Gerrygames, KennyTV, Matsv], ViaBackwards v3.2.0 nl.matsv.viabackwards.BukkitPlugin [Matsv, KennyTV, Gerrygames, creeper123123321, ForceUpdate1], LuckPerms v5.3.0 me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin [Luck], ItemEditor v0.1.5 at.freakey.itemeditor.Core [Freakey], AnimatedScoreboard v0.2.3 me.jasperjh.animatedscoreboard.AnimatedScoreboard [JasperJH], spark v1.5.0 me.lucko.spark.bukkit.BukkitSparkPlugin [Luck, sk89q], ChunkyBorder v1.0.25 org.popcraft.chunkyborder.ChunkyBorder [pop4959], BuycraftX v12.0.6 net.buycraft.plugin.bukkit.BuycraftPlugin [Buycraft], MessageAnnouncer v1.12.2 me.clip.messageannouncer.MessageAnnouncer [extended_clip], Votifier v2.7.2 com.vexsoftware.votifier.NuVotifierBukkit [Ichbinjoe, blakeman8192, Kramer, tuxed], ProtocolLib v4.6.0 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], HamsterAPI v0.1.6* dev._2lstudios.hamsterapi.HamsterAPI [Sammwy, LinsaFTW], LibsDisguises v10.0.24 me.libraryaddict.disguise.LibsDisguises [libraryaddict, Byteflux, Navid K.], AAC5 v5.0.13 me.konsolas.aac.AAC [konsolas], ChatSentry v4.3.0 com.kixmc.ChatSentry.Main.Main [kixmc], ServerRestorer v1.0.39 me.zombie_striker.sr.Main [Zombie_Striker], Vault v1.7.3-b131 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], GMusic v[2.5.4.1] me.gmusic.main.GMusicMain [Gecolay], HolographicDisplays v2.4.6 com.gmail.filoghost.holographicdisplays.HolographicDisplays [filoghost], SkinsRestorer v14.0.2 net.skinsrestorer.bukkit.SkinsRestorer [Th3Tr0LLeR, McLive, DoNotSpamPls, knat], AdvancedNMotd v9.1.1 ru.namerpro.Bukkit.Base.Main [NamerPRO], RandomTeleport v7.9.2 com.vk2gpz.randomteleport.RandomTeleport [vk2gpz], LPC v3.2.0 me.oncode9.lpc.LPCPlugin [OnCode9], WorldEdit v7.3.0-SNAPSHOT+5647-476342a com.sk89q.worldedit.bukkit.WorldEditPlugin [], PlayerKits v2.13.1 pk.ajneb97.PlayerKits [Ajneb97], Essentials v2.18.2.0 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, md678685], Multiverse-Core v4.2.2-b812 com.onarandombox.MultiverseCore.MultiverseCore [dumptruckman, Rigby, fernferret, lithium3141, main--], DiscordSRV v1.21.3 github.scarsz.discordsrv.DiscordSRV [Scarsz, Androkai, Vankka], AdvancedTeleport v5.4-SNAPSHOT-2 io.github.niestrat99.advancedteleport.CoreClass [Niestrat99, Thatsmusic99], EssentialsChat v2.18.2.0 com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], SuperbVote v0.5.5 io.minimum.minecraft.superbvote.SuperbVote [tuxed], TAB v2.8.10 me.neznamy.tab.platforms.bukkit.Main [NEZNAMY], WorldGuard v7.0.5-SNAPSHOT+2105-f1f8b62 com.sk89q.worldguard.bukkit.WorldGuardPlugin [], AuctionHouse v2.1.12 com.spawnchunk.auctionhouse.AuctionHouse [klugemonkey], MythicMobs v4.11.0-2fb2bf23 io.lumine.xikage.mythicmobs.MythicMobs [Ashijin], EssentialsProtect v2.18.2.0 com.earth2me.essentials.protect.EssentialsProtect [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], EssentialsAntiBuild v2.18.2.0 com.earth2me.essentials.antibuild.EssentialsAntiBuild [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, Iaccidentally], NexEngine v2.0.6 su.nexmedia.engine.NexEngine [NEX-Media], EssentialsSpawn v2.18.2.0 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], SimplePortals v1.6.4 xzot1k.plugins.sp.SimplePortals [XZot1K], CoreProtect v19.5 net.coreprotect.CoreProtect [Intelli], MythicMobsExtension v1.738c-SNAPSHOT com.gmail.berndivader.mythicmobsext.Main [], Jobs v4.17.0 com.gamingmesh.jobs.Jobs [phrstbrn, Zrips, montlikadani], Citizens v2.0.27-SNAPSHOT (build 2270) net.citizensnpcs.Citizens [fullwall], AngelChest v3.3.0 de.jeff_media.AngelChest.Main [mfnalex, JEFF Media GbR], VoidTeleportPlus v3.1.2 it.endlessgames.voidteleport.VoidTeleport [EndlessGames], AuthMe v5.6.0-SNAPSHOT-b2440 fr.xephi.authme.AuthMe [Xephi, sgdc3, DNx5, timvisee, games647, ljacqu, Gnat008], SignShop v3.5.0 org.wargamer2010.signshop.SignShop [Wargamer2010, Devinish, Weaves], BetonQuest v1.12.2 pl.betoncraft.betonquest.BetonQuest [BetonQuest Organisation, Wolf2323, SaltyAimbOtter, seyfahni, joblo2213, bundabrg, Co0sh], GoldenCrates v3.11.0 su.nightexpress.goldencrates.GoldenCrates [NightExpress], CombatLogX v10.3.8.1 com.SirBlobman.combatlogx.CombatLogX [SirBlobman], FastLogin v1.11-SNAPSHOT-9ff404a com.github.games647.fastlogin.bukkit.FastLoginBukkit [games647, https://github.com/games647/FastLogin/graphs/contributors], eco v4.2.6 com.willfp.eco.spigot.EcoPlugin [Auxilor], EcoEnchants v6.10.12 com.willfp.ecoenchants.EcoEnchantsPlugin [Auxilor], ForceResourcepacks v1.10.11 (build #478) de.themoep.resourcepacksplugin.bukkit.ForceResourcepacks [Phoenix616], UClans v2.1.8 me.ulrich.clans.Clans [UlrichBR], UGladiator v1.0* me.ulrich.gladiator.Glad [UlrichBR], UChestClan v1.1* me.ulrich.chestclan.ChestClan [UlrichBR], ULands v2.8.7 me.ulrich.lands.Lands [UlrichBR],}

### Actions to reproduce (if known)

Idk

### Paper version

Running: Paper version git-Paper-570 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) false

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

[crash-2021-03-27_17.57.04-server.txt](https://github.com/PaperMC/Paper/files/6216574/crash-2021-03-27_17.57.04-server.txt)

**Comment by Specthra** [comment]
I need help please, my server is shutting down every 5 minutes
I beg your help

**Comment by Owen1212055** [comment]
This issue is the same as the one here:
https://github.com/PaperMC/Paper/issues/2718

**Comment by Specthra** [comment]
What I can do? how can I solve that? I need help

**Comment by electronicboy** [comment]
you have a plugin on your server modifying items in a way that the server doesn't expect

**Comment by Specthra** [comment]
I have a question, do I have to pay for you to help me?

**Comment by aurorasmiles** [comment]
Please join our Discord or IRC for support, GitHub issues is not the place for that. Generally what you want to do now is figure out which plugin causes that,you can do that by removing half of them and see if the problem still occurs, and then so on.
