### ISSUE TITLE
Add a batch packet sending method to PlayerConnection

### ISSUE THREAD

**Issue by bergerkiller** [PaperMC/Paper#5427]
### Is your feature request related to a problem?

When sending a lot of packets (>500 / tick) timings show a lot of time lost in sendPacket().

### Describe the solution you'd like.

Simple method: sendPackets(Iterable<Packet<?>> packets)

### Describe alternatives you've considered.

I've tried to write my own version of a batch packet send method, but quickly found that the implementation in PaperMC is too volatile to safely implement it. The problem is that there are a lot of rules, like main thread or not, and the queue. Considering PaperMC changes often, it's not something I can maintain on my own.

With some simple tests of scheduling many packets at once on the netty event loop I found a 600% performance improvement. A lot of time is lost in the schedule() function.

Another alternative is to improve how the packet queue works. When packets are sent from other threads, they are queued up and flushed later on. When flushing, it calls schedule() for every individual packet. This could be improved too.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by electronicboy** [comment]
I think a lot of this really needs re-implementing, for one I really wanna get rid of the current oversized packet handling logic as the way it works in general seems flawed for what it's really tryna solve,

the entire layout ain't really designed too well, and sending large numbers of packets really kicks itself, and due to issues like plugin compat, etc, which really shakes off large edits to that class

Not a netty pro, but, I have a tad bit of experience here with it and so, that class not only concerns me but worries me

**Comment by bergerkiller** [comment]
I spent a week messing around with it, but got stuck because a plugin someone was using (Lilypad Connect) was incompatible and players got disconnected due to packet corruptions. So you're right, plugin compatibility is a pain. And I know too little about the 'right' way to use netty to submit a PR. Too risky :)

That was for 1.12.2, when I saw the massive changes done in 1.16.5 I kind of gave up on the idea...

**Comment by astei** [comment]
The other major plugin that will cause issues with this is ProtocolLib. The way ProtocolLib hooks into the server to intercept packets being sent is not only intrusive but also precludes entire classes of Netty optimizations.

Ultimately, the only path forward is to have Paper provide "native" packet interception APIs and then teach ProtocolLib to use them instead.
