### ISSUE TITLE
tnt not affecting projectiles

### ISSUE THREAD

**Issue by blobcode** [PaperMC/Paper#5429]
### Expected behavior

I expected tnt to launch projectiles.

### Observed/Actual behavior

tnt did not launch projectiles, either in or out of water.

### Steps/models to reproduce

place tnt, spawn arrows / any projectile, light tnt

### Plugin list

None

### Paper version

This server is running Paper version git-Paper-571 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by TwoLeggedCat** [comment]
In my testing, the expected behavior is not the case in Spigot or even vanilla. Could you try it in vanilla and see if they are launched there?

**Comment by blobcode** [comment]
Yes, running a vanilla 1.16.5 server projectiles are launched by tnt. See attached video
[video](https://streamable.com/vlvpge)

**Comment by blobcode** [comment]
This is not shown on a paper 1.16.5 server, [video](https://streamable.com/jmizvf)

**Comment by TwoLeggedCat** [comment]
My apologies, must have been a mistake in my testing, I can reproduce now, and it appears to be an upstream issue. They are launched in vanilla but neither Spigot nor Paper.

**Comment by lynxplay** [comment]
The issue is most likely caused by the following:

```java
// see: net.minecraft.server.Explosion.java(224-228)[paper]

boolean wasDamaged = entity.damageEntity(this.b(), (float) ((int) ((d13 * d13 + d13) / 2.0D * 7.0D * (double) f2 + 1.0D)));
CraftEventFactory.entityDamage = null;
if (!wasDamaged && !(entity instanceof EntityTNTPrimed || entity instanceof EntityFallingBlock) && !entity.forceExplosionKnockback) {
    continue;
}
```

As the IProjectile does not overwrite `Entity#damageEntity` it always returns false and hence `wasDamaged = false`.
The code currently provides exceptions for `EntityTNTPrimed` and `EntityFallingBlock` so *one possible solution* would be the addition of an `instanceof IProjectile` check in the very same line.

//EDIT.1: 
Vanilla does no such checks to ensure that the entity was actually damanged (which explains why this works in vanilla).

**Comment by Zxchk** [comment]
So how do i fix this

**Comment by lynxplay** [comment]
> So how do i fix this

By opening a pull request that fixes the underlying issue, tho there are already a few attempts at this.

The sad truth is that the way spigot implements damage events makes it rather difficult to apply knockback from explosions correctly (the linked PRs in this issue go deeper as to why).

For now this will remain a limitation and will first be fixed when the paper core/development team pulls one of the attempts to fix this rather complex issue.
