### ISSUE TITLE
Error when start server

### ISSUE THREAD

**Issue by Rodrigolmti** [PaperMC/Paper#543]
Hello, i'm having one error when i try to start my server. I running on 1.8 version. The link above have one image with that error.

[Link](http://imgur.com/a/O41zI)

**Comment by sgdc3** [comment]
1.8 is no longer supported, just ignore that error, it happens when you run the server using the windows command prompt.

**Comment by Rodrigolmti** [comment]
There are another ways to run a server?

**Comment by sgdc3** [comment]
That error can be ignored ;)
