### ISSUE TITLE
Entity HitBox API

### ISSUE THREAD

**Issue by TheFruxz** [PaperMC/Paper#5434]
### Is your feature request related to a problem?

NO, no problem relatet

### Describe the solution you'd like.

A way to get a HitBox of an entity e.g. ArmorStand, Zombie, Player, Slime, etc. as a BoundingBox (e.g. by slime.get*Current*HitBox).

### Describe alternatives you've considered.

/

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Owen1212055** [comment]
Is this what you are looking for?

https://papermc.io/javadocs/paper/1.16/org/bukkit/entity/Entity.html#getBoundingBox--
