### ISSUE TITLE
Time elapsed shows invalid time in console

### ISSUE THREAD

**Issue by DarkEyeDragon** [PaperMC/Paper#5438]
### Expected behavior

[14:22:52 INFO]: Time elapsed: 30 ms
[14:22:52 INFO]: Time elapsed: 32 ms
[14:22:52 INFO]: Time elapsed: 34 ms
or any reasonable number

### Observed/Actual behavior

[14:22:52 INFO]: Time elapsed: 42177403 ms
[14:22:52 INFO]: Time elapsed: 42177405 ms
[14:22:52 INFO]: Time elapsed: 42177407 ms

Which corresponds to 11.71 hours

### Steps/models to reproduce

Start up the server. Check the startup log and look at the bottom section (without plugins)

### Plugin list

Non, fresh server

### Paper version

[14:28:14 INFO]: Checking version, please wait...
[14:28:15 INFO]: This server is running Paper version git-Paper-575 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-563 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
That's nanoseconds it seems. Thanks for the report!

**Comment by electronicboy** [comment]
Do you have keep spawn loaded disabled?

**Comment by DarkEyeDragon** [comment]
> Do you have keep spawn loaded disabled?

 `keep-spawn-loaded: false`
Yeah it's disabled

**Comment by electronicboy** [comment]
`WorldLoadListenerLogger` has two methods of note, one of them starts the timer, the other ends it and prints the message, looks like when that option is disabled, the first method won't be called, but the latter will
