### ISSUE TITLE
PlayerInteractEntityEvent called twice on empty ItemFrame

### ISSUE THREAD

**Issue by eereeska** [PaperMC/Paper#5442]
### Expected behavior

Single call of PlayerInteractEntityEvent

### Observed/Actual behavior

PlayerInteractEntityEvent has triggered twice

### Steps/models to reproduce

1. Place an a empty ItemFrame
2. Click on it with an empty hand

### Plugin list

None

### Paper version

This server is running Paper version git-Paper-575 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

Sorry for my eng :(

**Comment by Proximyst** [comment]
Can you check which hands interact with it? If it's one of the main hand, one of the off-hand, this would be intentional behaviour.

**Comment by eereeska** [comment]
Both:
[22:30:17 INFO]: HAND
[22:30:17 INFO]: OFF_HAND

Result of e.getHand()

PlayerInteractEntityEvent has called twice with different hands

**Comment by Proximyst** [comment]
Then that's intentional behaviour. Ignore the hand you don't care about.
