### ISSUE TITLE
villager conversion

### ISSUE THREAD

**Issue by seema84** [PaperMC/Paper#5446]
### Expected behavior

I expect the old villagers to be properly updated (level,maxuses etc).

### Observed/Actual behavior

All old villagers (before 1.14) have completely wild values. It looks like the levels were randomly assigned. Some have a "level" of over 100. Others have found a "maxuseses" value of 309. 

### Steps/models to reproduce

Since I only noticed it now (with version 1.16.5), I can't say exactly how to reproduce it.

### Plugin list

-

### Paper version

This server is running Paper version git-Paper-574 (MC: 1.16.5) 

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

![2021-04-02_20 33 52](https://user-images.githubusercontent.com/2832339/113445125-8f935480-93f5-11eb-8ac7-c11c046bbdb9.png)
![2021-04-02_20 34 12](https://user-images.githubusercontent.com/2832339/113445134-9326db80-93f5-11eb-9c30-803651600d57.png)
![2021-04-02_20 55 22](https://user-images.githubusercontent.com/2832339/113445322-f57fdc00-93f5-11eb-9e94-eb9f47ddb2e5.png)

**Comment by e-im** [comment]
I haven't been able to reproduce this, additionally, the system responsible for this has been reworked in 1.17.1. If you or anyone else is still experiencing this on 1.17.1, leave a comment or open a new issue.
