### ISSUE TITLE
Optional Kotlin-Support

### ISSUE THREAD

**Issue by TheFruxz** [PaperMC/Paper#5447]
### Is your feature request related to a problem?

Because Kotlin plugins would run better "natively" and especially directly this way

### Describe the solution you'd like.

You should be able to enable Kotlin support in the server settings, so that the Kotlin libraries needed for running Minecraft Paper Kotlin plugins are included in the server archives during e.g. patching.

### Describe alternatives you've considered.

/

### Agreements

I have searched for and ensured there isn't already an open issue regarding this.
I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Proximyst** [comment]
We aren't gonna do this. Package it yourself, and remember to relocate it.
