### ISSUE TITLE
Add Component-Methods to FileConfigurations

### ISSUE THREAD

**Issue by motz0815** [PaperMC/Paper#5449]
### Is your feature request related to a problem?

The problem is that with the new Component-System, Adventure, that has been put into the Paper-API, everything's pretty much fine, but FileConfigurations, like the default config you can add to your plugin, does currently not have any methods related to Components.

### Describe the solution you'd like.

It would be great to have methods for FileConfigurations regarding Components.
Such as:
getComponent(String path), which returns a Component,
getComponentList(String path) , which returns a List consisting of Components,
and maybe also getText and get TextList, for TextComponents, but that one is just QoL.

Because getString and getStringList both exist, it would be great to have the same methods for Components, without having to convert to one from a string or List<String>.

### Describe alternatives you've considered.

It is possible to get a plain String out of the config and then convert that one to a Component or TextComponent, 
and it is also possible, easiest with an ArrayStream, to convert a List<String> to a List<Component>, but if Adventure is now the only way to go, and all the methods containing Strings are deprecated now, it would be great to have simple methods for the new Types.

### Agreements

I have searched for and ensured there isn't already an open issue regarding this.
I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by yannicklamprecht** [comment]
Would personally wait for Mini-Message to be added to paper.

**Comment by kashike** [comment]
`getRichMessage` as a name for the method, based on internal discussions and the existence of the `sendRichMessage` method.
