### ISSUE TITLE
Ghasts spawning issue since 1.9/1.10/1.11

### ISSUE THREAD

**Issue by TNTUP** [PaperMC/Paper#545]
# Suggestion

___We love suggestions! Suggestions are fairly unstructured, and will be treated as such___

I don't know if its a suggestion haha XD I'm having issues with Ghast spawning in the nether, since I've moved to paper in 1.9.4, getting lots of reports from my players telling me its hard as f* to find ghasts, in Spigot/Vanilla its okay, but in Paper it does happen. I've even setup a survival server in 1.11 for my friends and I got told it was hard to get a ghast in the nether, had to downgrade to Spigot 1.11 for the time being.

It occurs since 1.9.4, in 1.10.2 and 1.11. Idk if others is fine, or a setting I need to change to let ghast spawn as normal in the nether? I don't know how to provide evidence how to reproduce, try playing in survival and hunt for some Ghasts, you'll notice it'll be hard to find. Try in Vanilla and get me 10 ghast tear in both versions (Vanilla/Spigot/Paper) in less than 30 minutes (Should be fine with a maxed bow in 30 minutes) then give me the results if possible? 

And, have a nice day and merry christmas :D

**Comment by Shivelight** [comment]
I can confirm, running paper 1.11 with minimal plugin (NCP, TeaLimit).

**Comment by galacticwarrior9** [comment]
Can confirm - also occurs with wither skeletons.

**Comment by TNTUP** [comment]
Closing this as its no longer an issue on 1.15.1/1.15.2. Been noticing normal ghast spawn behiavour as normal
