### ISSUE TITLE
Narrator not work start from build 473

### ISSUE THREAD

**Issue by AchiraE** [PaperMC/Paper#5450]
### Expected behavior

When enables "Narrator: Narrates Chat" in Chat Settings, chat should be narrated

### Observed/Actual behavior

Chat not narrated without change the option to "Narrator: Narrates All"

### Steps/models to reproduce

1. enables narrator from  Chat Settings->Narrator: Narrates Chat
2. chat

### Plugin list

None

### Paper version

Test on 472, works
Also test on 473 and 575, not work.
> version
[12:42:33 INFO]: This server is running Paper version git-Paper-473 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[12:42:33 INFO]: Checking version, please wait...
[12:42:34 INFO]: You are 106 version(s) behind

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by Prof-Bloodstone** [comment]
I can confirm that it indeed doesn't narrate chat unless you switch narration to `all`. It works in vanilla SP.
I was unable to confirm it working properly in 472 - I've also selectively tried a few versions going back to 1.16.4 build 370, but the issues also exists there.
~~I haven't checked upstream yet.~~

@AchiraE  Could you double check that using `Narrator: Narrates Chat` settings works for you in 472? Maybe you had it set to `Narrates all`? Or it also requires some other change to trigger?

EDIT: I've just checked freshly compiled Spigot and it doesn't work for me either.
```
This server is running CraftBukkit version 3032-Spigot-1ad8354-b530534 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```
Same happens on plain CB:
```
This server is running CraftBukkit version 3032-Bukkit-b530534 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```
Would love if someone could confirm before I go ahead and make an issue upstream.

**Comment by katekerllenevich** [comment]
I wonder if it works on a Vanilla server

**Comment by AchiraE** [comment]
My fault, I'm using a plugin that listens to the `AsyncPlayerChatEvent`, which is deprecated in 473. It works before 472.

I will test the new `AsyncChatEvent`

**Comment by Prof-Bloodstone** [comment]
I'm not using any plugins at all and it doesn't work for me. It doesn't even work in CB, but does in Vanilla SP and server.

**Comment by Prof-Bloodstone** [comment]
> My fault, I'm using a plugin that listens to the `AsyncPlayerChatEvent`, which is deprecated in 473. It works before 472.

@AchiraE Perhaps it works in the earlier version BECAUSE of your plugin, and Adventure introduced a regression in this regards? Is the chat plugin open source / available somewhere?

**Comment by AchiraE** [comment]
> > My fault, I'm using a plugin that listens to the `AsyncPlayerChatEvent`, which is deprecated in 473. It works before 472.
> 
> @AchiraE Perhaps it works in the earlier version BECAUSE of your plugin, and Adventure introduced a regression in this regards? Is the chat plugin open source / available somewhere?

You can try EssentialsX Chat. It works in 472.

**Comment by Prof-Bloodstone** [comment]
I can confirm this is caused by plugin interaction after Adventure update.

The chat narration doesn't work in Spigot/CB at all in any tested version - created upstream issue: https://hub.spigotmc.org/jira/browse/SPIGOT-6408

When using EssentialsX Chat 2.18.2.0 with default config, the narration works just fine in build 472, but breaks with later versions. The addition of new chat event which re-processes the output of the legacy one might be related to this.

**Comment by Proximyst** [comment]
a111b13
