### ISSUE TITLE
Item removal error when cancelling events

### ISSUE THREAD

**Issue by Owen1212055** [PaperMC/Paper#5451]
### Expected behavior

1. Place a block
2. The item is overridden with the newly set item.

### Observed/Actual behavior

1. Place block
2. Block is set to air

### Steps/models to reproduce

On the PlayerInteractEvent run the following code:

```java
 event.setUseInteractedBlock(Result.ALLOW);
 event.setUseItemInHand(Result.DEFAULT);
 player.getInventory().setItem(EquipmentSlot.HAND, new ItemStack(Material.OAK_PLANKS));
```

On the BlockPlaceEvent run the following code:
```java
event.setCancelled(true);
```

When you place down a block in survival mode the block you are holding will be removed instead of replaced with the newly set Oak Planks.

### Plugin list

Test Plugin

### Paper version

I can confirm that has been an issue since  05/10/2019

This server is running Paper version git-Paper-c310f0a61 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 29 version(s) behind

Testing with the latest update does not change anything.

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
So looking into this a little further, PlayerInteractEvent happens first, and the item is in fact set to an oak plank at this stage (used a debugger and breakpoints), but once the BlockPlaceEvent happens, the item disappears. Specifically when the Player#updateInventory is called in ItemStack#placeItem.

Can't the same thing be accomplished by denying using the item in hand in PlayerInteractEvent?

**Comment by Owen1212055** [comment]
Generally there are a lot of quirks that are just a result of how these events work. I find it not really beneficial to fix such an edge case.
