### ISSUE TITLE
Scaffold/speed hack + worldguard region + refreshPlayer = item dupe

### ISSUE THREAD

**Issue by s1h4d0w** [PaperMC/Paper#5452]
### Expected behavior

Items not to duplicate

### Observed/Actual behavior

A player enables scaffold and player hacks on our anarchy server, they sprint, jump and scaffold in a protected worldguard region and then trigger a refreshPlayer by changing their skin using SkinsRestorer

Suddenly the block they used to scaffold is now a full stack in their inventory, even if they previously only had a few blocks of that item.

### Steps/models to reproduce

* Enable scaffold + speed hacks
* Sprint, jump and scaffold in a worldguard region where they can't place blocks
* Trigger a refreshPlayer by for example doing `/skin <name>` with SkinsRestorer

### Plugin list

AuthMe, AutoMessager, AutoRestart, BetterRTP, BotSentry, ChatReaction, ClearLag, ConsoleSpamFix, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, HolographicDisplays, IllegalStack, Item2Chat, JoinMessagePlus, KeepDeathDrop, LocalThunder, LuckPerms, MobStacker, MyCommand, NoPortalDestroy, OnTime, ProtocolLib, ServerListPlus, SkinsRestorer, SuperbVote, Vault, Votifier, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

### Paper version

Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by limbo-app** [comment]
Hey @s1h4d0w! You seem to be running an unsupported version (1.12) of Paper.

If you can reproduce this issue with the latest supported version, please [open a new issue](https://github.com/PaperMC/Paper/issues/new) with updated information.
