### ISSUE TITLE
[Request] Init command to prepare jar and dir structure

### ISSUE THREAD

**Issue by nathanfranke** [PaperMC/Paper#5459]
### Is your feature request related to a problem?

Currently, if one wants to setup a fresh instance of PaperMC, the server needs to be started and it needs to be waited until the directory structure and configuration files are created. Then the server needs to be stopped to allow configuring it (using the default configs as starting point), installing plugins etc. Especially scripting an install and setup based on default configs is therefore a bid complicated.

### Describe the solution you'd like.

It would be great to have sort of an init command, which makes the server stop after the initial file structure, default config files (if missing) and, if possible even plugins (to have their config files as well), created, but before binding to a port, starting the world and spawn areas, e.g. between those two startup steps:

```
Jan 06 18:02:17 VM-Buster papermc[5382]: [18:02:17 INFO]: Generating keypair
Jan 06 18:02:18 VM-Buster papermc[5382]: [18:02:18 INFO]: Starting Minecraft server on *:25565
```

### Describe alternatives you've considered.

Instead of patching such a feature into the main server, a plugin could do the job that stops the server when being enabled.

### Agreements

I have searched for and ensured there isn't already an open issue regarding this.
I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

Initial request at Paperclip repo where it does not fit well but with short discussion already: PaperMC/Paperclip#32
The exact implementation depends on the aim/use case, e.g. plugins are enabled, creating their config files, after the server has bound to an interface already and the world + spawn areas got created. So it makes sense to get some more opinions and use cases for this feature, and someone who can evaluate the effort, before deciding when and how the server should stop most reasonable.

---

See https://github.com/PaperMC/Paper/issues/5046

**Comment by nathanfranke** [comment]
For initializing everything, including plugins, pipe the stop command into the jar process.

```sh
echo stop | java -jar paper.jar nogui
```

**Comment by e-im** [comment]
For myself I use an extremely simple patch like this: [https://paste.gg/p/Pencil/eb8aaa7a4b2e4532a6aa2b372adf026a](https://paste.gg/p/Pencil/eb8aaa7a4b2e4532a6aa2b372adf026a)

It's very simple and does the job for my needs, but would not belong in paper. This will also not generate configs from plugins as I don't see a way to do that effectively while still providing what plugins expect from the server.

**Comment by Proximyst** [comment]
Not really fit for Paper; let a plugin or better yet, shell piping do it.
