### ISSUE TITLE
Breaking a chest completely full evaporates all items.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#546]
Paper dev 963

If you break a chest in survival that is entirely full of items (i.e. 64 dirt in every slot), all items evaporate when the chest breaks. You see the items pop out for a second but they immediately disappear.

**Comment by zachbr** [comment]
Probably a plugin?

**Comment by mibby** [comment]
My apologies, it does seem to be a plugin issue. Caused by FastAsyncWorldEdit's tick limiter.
