### ISSUE TITLE
WSL 2 Ubuntu issue

### ISSUE THREAD

**Issue by TheFruxz** [PaperMC/Paper#5464]
### Expected behavior

Start of the patch

### Observed/Actual behavior

Instead of the patch starting, an error is thrown immediately:
./paper: line 2: $'\r': command not found
./paper: line 4: syntax error near unexpected token `$'in\r''
'/paper: line 4: `case "$(echo "$SHELL" | sed -E 's|/usr(/local)?||g')" in

### Steps/models to reproduce

1. run ./paper patch in WSL2 (newest official Microsoft-Store Release)

### Plugin list

/

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by lynxplay** [comment]
DId you checkout the project on windows ?
`\r` is part of the windows line-ending.
