### ISSUE TITLE
Cancelling PlayerInteractEvent with Sunflower in hand on grass places the upper part anyway

### ISSUE THREAD

**Issue by dawon** [PaperMC/Paper#5466]
### Expected behavior

When cancelling PlayerInteractEvent with Sunflower in hand, nothing should change.

### Observed/Actual behavior

The upper part of the sunflower is placed regardless of cancelling the event. (The bottom part is not placed though)

### Steps/models to reproduce

1) Create a plugin that cancels PlayerInteractEvent.
2) Right-click on the grass with sunflower in hand

### Plugin list

only the testing plugin

### Paper version

This server is running Paper version git-Paper-582 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-570 (MC: 1.16.5)

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by HexedHero** [comment]
Just curious, is it a "real" block or is it fake/goes away on relog?

**Comment by dawon** [comment]
> Just curious, is it a "real" block or is it fake/goes away on relog?

Oh, good point, didn't think of reconnecting.. It seems to be fake, aka no longer there after relog... But still, it shouldn't be there in the first place...

**Comment by Prof-Bloodstone** [comment]
This is upstream issue, reported: https://hub.spigotmc.org/jira/browse/SPIGOT-6435

**Comment by Prof-Bloodstone** [comment]
Fixed with latest upstream update: https://github.com/PaperMC/Paper/pull/5549
