### ISSUE TITLE
Entities are being ticked when chunk is inactive

### ISSUE THREAD

**Issue by HyplexMC** [PaperMC/Paper#5468]
### Expected behavior

Entities are not loaded in unloaded chunks

### Observed/Actual behavior

Entities (mainly sheep are the problem) are getting tick updates when the chunks are not being updated. The sheep eat the grass and since the chunks are not getting ticks the grass has no chance to spread to the dirt causing patches of dirt all around the world.

### Steps/models to reproduce

stand still and let time run its course.

### Plugin list

This is not a plugin issue

### Paper version

#583

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

This is a open unassigned ticket on Mojang's issue tracker and its been a (claimed) issue since 1.13.2.
https://bugs.mojang.com/browse/MC-210802?filter=-5&jql=resolution%20%3D%20Unresolved%20AND%20text%20~%20%22inactive%20sheeps%20eat%20grass%22%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC

This has become a massive issue on my survival world and Mojang is gonna take ages to fix it let alone look at the issue so I though the only thing I can do to help my server is to upvote that current open issue and to create a issue here to see if this is something you guys could fix.

![2021-04-07_08 48 48](https://user-images.githubusercontent.com/66493095/113823639-bc1bd900-9733-11eb-8547-714d9d18ca23.png)
In this photo the player is currently building a dragon and he re-opened a closed ticket on my discord after I thought I fixed the issue but actually didn't. He spends a lot of time in that one area building so the sheep have lots of time to roam and destroy the land, so when he leaves that area this is what he is greeted with. Its ugly and it needs fixing.

**Comment by electronicboy** [comment]
This is up to mojang to deal with if they wanna incur potential behavioral breakages from it, as much as it leads to stuff not being pretty, it is vanilla behavior
