### ISSUE TITLE
"The super spider, which can cross barriers."

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#547]
![2016-12-16_16 31 21](https://cloud.githubusercontent.com/assets/9270074/21274027/60650dce-c3ad-11e6-9391-d12136723cf5.png)
![2016-12-16_16 31 26](https://cloud.githubusercontent.com/assets/9270074/21274026/6064a564-c3ad-11e6-8b50-5c480e8b1d23.png)
![2016-12-16_16 32 12](https://cloud.githubusercontent.com/assets/9270074/21274028/6065e0f0-c3ad-11e6-813e-873ddd95901d.png)
![2016-12-16_16 32 22](https://cloud.githubusercontent.com/assets/9270074/21274029/60dff494-c3ad-11e6-9aa6-611e859a53fa.png)

[16:32:45 INFO]: This server is running Paper version git-Paper-963 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
[16:32:45 INFO]: Checking version, please wait...
[16:32:46 INFO]: You are running the latest version

Without any plugins.

**Comment by zachbr** [comment]
Going to assume this is in vanilla too?
I assume Mojang just never took barriers into account with Spider's ability to climb walls.

**Comment by ghost** [comment]
OK.

**Comment by zachbr** [comment]
Just because Mojang didn't think of it doesn't mean this isn't a bug.

**Comment by aikar** [comment]
FYI https://github.com/PaperMC/Paper/commit/4ac2cac9f90b9244aea3691ed9862181dfb23e74 nor the upstream copy of that, DID NOT fix this. That bug only affected spawning itself. not AI behavior.

**Comment by aikar** [comment]
I decided to go ahead and (hopefully) fix this. I cancelled pathfinding actions if the target is outside of the world border. I wasn't able to test if it fixes this exact demonstrated case, so please let us know if it still happens.

But fairly confident, as I hooked into same place we fire EntityPathfindEvent, which has been reliable for aborting pathfinds.

**Comment by aikar** [comment]
and to be clear, didn't change spiders from actually climbing the wall, that would be difficult. but stopped them from trying to go across the wall which results in climbing the wall.

**Comment by ghost** [comment]
@aikar @Zbob750 Well, this "fix" didn't work correctly.

![2017-01-10_11 45 53](https://cloud.githubusercontent.com/assets/9270074/21808470/9f01028c-d72a-11e6-8ca0-acca3f2be3a1.png)
![2017-01-10_11 47 15](https://cloud.githubusercontent.com/assets/9270074/21808469/9f00350a-d72a-11e6-8ac6-dabaab327bfe.png)
