### ISSUE TITLE
vulnerabilities in mysql-connector-java:5.1.49

### ISSUE THREAD

**Issue by Titaniumtown** [PaperMC/Paper#5473]
### Expected behavior

I expected the version of `mysql-connector-java` that paper uses (`5.1.49`) to not have known and major security vulnerabilities.

### Observed/Actual behavior

I was referred to this page: https://snyk.io/vuln/maven:mysql:mysql-connector-java by the `Dependency Analytics` plugin in code-oss (my main IDE). And I found: 
![image](https://user-images.githubusercontent.com/11786225/114197788-af100d00-9920-11eb-8cbb-49c8a227f2cc.png) Showing 1 high and 1 medium level vulnerabilities. Those vulnerabilities being Access Control Bypass and Privilege Escalation, respectively.

### Steps/models to reproduce

Go to https://snyk.io/vuln/maven:mysql:mysql-connector-java and observe 1 high level and 1 medium level vulnerabilities reported for the version of `mysql-connector-java` that Paper currently uses (`5.1.49`).

### Plugin list

N/A

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
@MiniDigger Do you know if bumping this 3 whole major versions would cause any noticeable issues with plugins and whatnot? Does the connector even provide an API beyond a driver that nobody should interact with directly?

**Comment by MiniDigger** [comment]
seems like it was not 3 major updates, just one from 5.1.x to 8.0.x
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-api-changes.html

there are breaking api changes, but nobody really should need to use that?
they mostly renamed and changed some exceptions and some config properties, I doubt this would make a difference to 99% of plugins that use that connector.
