### ISSUE TITLE
Chunk Ban with Player heads and Campfires

### ISSUE THREAD

**Issue by wecome42** [PaperMC/Paper#5475]
### Expected behavior

There would be heads and Campfires

### Observed/Actual behavior

It kicked me from the Server with the Message "**Internal Exception io.netty.handler.codec.Decoder.Exception: Badly compressed packet - size of 2372714 is larger than protocol maximum of 2097152**"

### Steps/models to reproduce

Download this region file and add it to a Paper Server world, Teleport to "**/tp 610 91 67**"

https://drive.google.com/file/d/1vBHlNMnmj3cK7n6Vk0jGKXzYHdMdQbdL/view?usp=sharing

### Plugin list

**Plugins (52):** ajParkour, AuctionHouse, AuthMe, BanWords*, BetterRTP, BetterSleeping3, BuycraftX, ChatReaction, ChristmasCalendar*, ClearLag, CommandPanels, CrateReloaded, DiscordSRV, EasterEggs*, EpicGuard*, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), FriendsSpigot, GriefPrevention, GroupManager*, HolographicDisplays, InfiniteAnnouncements, InfoBoardReborn*, InteractiveChat, KitPvP, Minetrends*, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, NoCheatPlus, PlaceholderAPI, PlayerParticles, PlayerReport*, PlotSquared, PluginConstructorAPI, ProtocolLib, ServerReviews*, SilkSpawners, SkinsRestorer, StaffChat*, TAB, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, WorldBorder, WorldGuard, WorldGuardExtraFlags

### Paper version

1.16.5-445

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
What version are you reproducing this on?

**Comment by wecome42** [comment]
1.16.5
