### ISSUE TITLE
PID 18

### ISSUE THREAD

**Issue by masterhacka** [PaperMC/Paper#5480]
### Stack trace

```
[https://paste.gg/p/anonymous/1009e482f3334d07844221e135dec70d](https://paste.gg/p/anonymous/1009e482f3334d07844221e135dec70d)
```

### Plugin list

[https://i.imgur.com/VtMwSaq.png](https://i.imgur.com/VtMwSaq.png)

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
Overloaded server. Ask for help on Discord. Fill the template next time.
