### ISSUE TITLE
PlayerItemHeldEvent fires twice

### ISSUE THREAD

**Issue by Owen1212055** [PaperMC/Paper#5482]
### Expected behavior

When the event is canceled it is not executed again.

### Observed/Actual behavior

The event is executed again after canceling a PlayerItemHeldEvent.

### Steps/models to reproduce

1. Cancel the ``PlayerItemHeldEvent`` when it is executed and print a test message to the console.
2. Observe

### Plugin list

None, edited the server directly.

### Paper version

This server is running Paper version git-Paper-54555252a (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information
Previous version: git-Paper-c310f0a61 (MC: 1.16.5)

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
this event is fired from the packet handler, unless the client is sending it twice, which I doubt, am not really sure what could be done here

**Comment by chickeneer** [comment]
I have investigated the issue. The issue is that when cancelling that event, the server sends the client a packet to set back to the previous slot. So the second event call actually has the same previous and next slot values.

Evidence. This plugin code...
```
    @EventHandler
    public static void onPlayerItemHeldEvent(PlayerItemHeldEvent event) {
        event.setCancelled(true);
        System.out.println("new slot: " + event.getNewSlot() + " - prev: " + event.getPreviousSlot());
    }
```

Yields this.
```
new slot: 4 - prev: 5
new slot: 5 - prev: 5
```

I think there is an open question whether this should be patched out by Paper. I don't see a valid reason for it to stay as is, but seems like something ideally to be patched upstream... Probably go ahead an patch it so it isn't forgotten about...

**Comment by chickeneer** [comment]
I meant to add on the fix patch if someone gets a chance
```
Index: src/main/java/net/minecraft/server/network/PlayerConnection.java
         PlayerConnectionUtils.ensureMainThread(packetplayinhelditemslot, this, this.player.getWorldServer());
         if (this.player.isFrozen()) return; // CraftBukkit
         if (packetplayinhelditemslot.b() >= 0 && packetplayinhelditemslot.b() < PlayerInventory.getHotbarSize()) {
+            if (packetplayinhelditemslot.b() == this.player.inventory.itemInHandIndex) return; // Paper - do not call event when previous and next slots are the same.
             PlayerItemHeldEvent event = new PlayerItemHeldEvent(this.getPlayer(), this.player.inventory.itemInHandIndex, packetplayinhelditemslot.b());
             this.server.getPluginManager().callEvent(event);
             if (event.isCancelled()) {
```
