### ISSUE TITLE
Error in building script on Windows

### ISSUE THREAD

**Issue by mcmdev** [PaperMC/Paper#5483]
### Expected behavior

A built paper and the project files.

### Observed/Actual behavior

`Downloading unmapped vanilla jar...
Applying class mappings...
Applying member mappings...
Creating remapped jar...
Installing remapped jar...
Extracting NMS classes...
Applying CraftBukkit patches to NMS...
./scripts/init.sh: line 77: /dev/fd/62: No such file or directory
On branch patched
nothing to commit, working tree clean
Failed to build Paper
`

### Steps/models to reproduce

Built against commit: d560151ecdad2eabccda797883c9e699b0985104
Date: 11.04.2021
Using: Git-Bash for Windows

### Plugin list

None, not a server issue.

### Paper version

None, not a server issue.

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
Looks like git borked itself or something, not much we can do with this kinda stuff
