### ISSUE TITLE
Entities glitch through floor when destroying boat

### ISSUE THREAD

**Issue by schnism** [PaperMC/Paper#5487]
### Expected behavior

When I destroy a boat with an entity (Villager, Zombie, Creeper, ...) in it, I expect the entity to stand on the floor afterwards.

### Observed/Actual behavior

If the floor is only 1 block high and has air below, the entity glitches into the floor, getting a suffocation damage and then falls through the floor and is below the platform.

### Steps/models to reproduce

Create a platform 10x10, 1 Block high, place a boat, place a villager, push villager into boat, destroy boat

### Plugin list

None

### Paper version

Paper version git-Paper-591 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by schnism** [comment]
![2021-04-12_23 06 50](https://user-images.githubusercontent.com/3404777/114463872-4e652680-9be5-11eb-8a19-cd4c37404ccd.png)
![2021-04-12_23 06 50_2](https://user-images.githubusercontent.com/3404777/114463868-4dcc9000-9be5-11eb-9745-56d7d93d18e3.png)
![2021-04-12_23 06 51](https://user-images.githubusercontent.com/3404777/114463866-4d33f980-9be5-11eb-98cb-0b3fa1edc454.png)
![2021-04-12_23 07 55](https://user-images.githubusercontent.com/3404777/114463864-4c02cc80-9be5-11eb-9c07-7139dac18296.png)

**Comment by TwoLeggedCat** [comment]
#4906?

**Comment by e-im** [comment]
Duplicate of #4906

**Comment by schnism** [comment]
> #4906?

Wow, yes, sorry. Searched for a similar issue upfront but oversaw this one. It is really the same problem.
