### ISSUE TITLE
1.16.5 Potential Server Crash

### ISSUE THREAD

**Issue by Ste3et** [PaperMC/Paper#5490]
### Stack trace

Here you can find the full Stacktrace about an Player who click outside the Pssible range of slots in the Inventory 
https://pastebin.com/hSvWZAJ1

### Plugin list

AuctionHouse v2.1.12
BungeeTabListPlus v3.4.3
ChangeSlots v2.3.0
Citizens v2.0.27-SNAPSHOT (build 2184)
CityWorld v4.1
CMI v8.8.3.2
CMIEInjector v1.0.2.3
CMILib v1.0.0.2
CoreProtect v19.4
DiceAnnauncer v1.0
DiceAntiAFK v1.0
DiceAntiRedstone v1.4.0
DiceBanManager v0.1
DiceBlockBreak v1.0
DiceChestShopAddon v1.0
DiceChunk v1.4
DiceChunkHologram v1.3
DiceChunkVisulizer v1.0
DiceChunkVote v1.0
DiceChunkWarpAddon v1.0
DicecraftServerRules v1.0
DiceCrate v1.0
DiceCreative v1.0
DiceFurniture v3.4.6
DiceInvites v1.0
DiceItemMarkt v1.0
DiceJob v1.0
DiceMiniEvent v1.0
DiceParticle v0.2a
DicePayday v1.0
DicePlaceHolders v1.0
DicePlayer v1.0
DiceRegenWorld v1.0
DiceRessourcePackPlugin v1.0
DiceSammelRework v1.3
DiceServerAPI v0.1
DiceSpawnEffect v1.1
DiceTabComplete v0.1
DiceTeam v0.1
DiceTokensAPI v0.1
DiceTokenShop v1.0
DiceTrollPlugin v1.0
DiceWBBBridge v1.0
dynmap v3.1-beta5-431
F3Name v3.3.0
FurnitureLib v2.3.9
HeadDatabase v4.13.2
ImageMaps v1.0.1
Jobs v4.17.2
LeaderHeadsRevamped v4.0.6
LuckPerms v5.3.21
MobFarmManager v1.5.9.1
Multiverse-Core v4.2.2-b812
NoteBlockAPI v1.6.1-SNAPSHOT
PlaceholderAPI v2.10.9
Plan v5.2 build 1174
PlugMan v2.1.6
ProtocolLib v4.6.1-SNAPSHOT-b498
RandomNether v1.0
Shop v1.8.2.4
Shopkeepers v2.12.0
Spartan vBuild 402
UltimateTimber v2.2.3
Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
ViaBackwards v3.2.0
ViaVersion v3.2.1
Votifier v2.7.1
VotingPlugin v6.1.4
WorldEdit v7.2.4+5723-e3bfc64
WorldEditGlobalizerBukkit v2.0.2
WorldGuard v7.0.5-SNAPSHOT+2099-129d273

### Paper version

Paper(591)

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by oRIOnTx** [comment]
I think problem with other plugins, because you have over 70)

**Comment by Chew** [comment]
Definitely an issue with your HeadDatabase plugin. It's failing to handle the event. Definitely not a crash, though. Just some spam.

**Comment by Esophose** [comment]
> Definitely an issue with your HeadDatabase plugin. It's failing to handle the event. Definitely not a crash, though. Just some spam.

That doesn't sound related considering there are like 10 plugins giving that same error in that server log. This looks the most suspicious and leads me to believe somebody named mori0 is just sending invalid window click packets.

> [20:49:37] [Server thread/ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R3.PacketPlayInWindowClick@48a60c5e for mori0[/2.244.110.106:41428]
net.minecraft.server.v1_16_R3.ReportedException: Container click
	at net.minecraft.server.v1_16_R3.Container.a(Container.java:220) ~[patched_1.16.5.jar:git-Paper-591]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2695) ~[patched_1.16.5.jar:git-Paper-591]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-591]

**Comment by electronicboy** [comment]
Somebody sent a bad packet, the logic for validating that the slots are actually valid is further down in vanilla code and plugins are basically blindly trusting the client here... Not a crash, just, spammy

**Comment by Ste3et** [comment]
Yeah i write my own little Spam mod and can confirm that the nearly same stacktrace appears.

https://pastebin.com/t3aUZjjL

That is my sourcecode of the mod
https://pastebin.com/4YZcpZ2K

A normal Spigot server did kick the Player and my own server make the same thing idk what was the problem yesterday.

**Comment by florianreuth** [comment]
Nice Log with my Username on top xd

**Comment by mori0** [comment]
og
