### ISSUE TITLE
1.16.5 Server crash

### ISSUE THREAD

**Issue by Guillaume-Lebegue** [PaperMC/Paper#5491]
### Stack trace

```
https://pastebin.com/zs6fZG3P
```

### Plugin list

EssentialsX-2.18.2.0.jar
Multiverse-Core-4.2.2.jar
Multiverse-Portals-4.2.1.jar
LuckPerms-Bukkit-5.3.3.jar
worldedit-bukkit-7.2.4.jar
Builders-Utilities-2.0.0-45.jar

### Paper version

This server is running Paper version git-Paper-592 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)              
You are running the latest version
Previous version: git-Paper-591 (MC: 1.16.5)

I think when it happened it was the previous version as I'm using a docker image and this image pull on each startup

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by Guillaume-Lebegue** [comment]
I'm using docker to run my server and I used this image: https://github.com/itzg/docker-minecraft-server
I have given 5G of RAM

I have 2 world which are still very little.
No one was online when it happened.

**Comment by aurorasmiles** [comment]
Looks like your server is just overloaded. I'd suggest joining our Discord for help and preparing a timings report for us to investigate

**Comment by electronicboy** [comment]
as above, your server is overloaded, please use discord or the forums for support

**Comment by Guillaume-Lebegue** [comment]
Thank for the help, but I'm just stupid.

I recently updated Builders-Utilities and forgot to set an option in the docker to delete old plugins.
So I had two versions of Builders-Utilities.
Since I deleted the old one, I didn't have any problems
