### ISSUE TITLE
Flying is not Enabled kick

### ISSUE THREAD

**Issue by Snowiiii** [PaperMC/Paper#5497]
### Expected behavior

If you are on several boots, the built-in spigot anti-cheat should not kick you because of fly, but recognize it

### Observed/Actual behavior

When I tried that, I was kicked

Here is a video that explains my problem well: https://youtu.be/lnqALy2WUNY

### Steps/models to reproduce

https://user-images.githubusercontent.com/71594357/115004724-64a20980-9ea7-11eb-8945-534ebc829113.mp4

### Plugin list

---

### Paper version

You are running the latest version
Previous version: git-Paper-593 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
Honestly, I believe this is a won't fix, disable the check in server.properties
the build in anti fly stuff relies on the client to provide info on if they're flying, the only real fix here would be to replace the thing which something more computationally expensive and practically just as ineffective

**Comment by Snowiiii** [comment]
Couldn't you just see if a boat below is a player?

**Comment by electronicboy** [comment]
For this specific case, yea, sure, now, what about horses? vehicles in general? the various other areas where this logic falters. It's much easier to just disable the flawed logic and use an anti cheat plugin, otherwise, replicate in vanilla and report to mojang and see if they'll fix this flawed system
