### ISSUE TITLE
Nether Protal bug

### ISSUE THREAD

**Issue by Snowiiii** [PaperMC/Paper#5498]
### Expected behavior

Hello this bug is about the fact that you can simply duplicate a Nether Portal, It is a bit difficult to explain, So if you build a Nether Prootal frame you put it on a block in the frame and set it up and you have to wait exactly until it does FAST explodes when the time comes you ignite the protal and the tnt should explode in the nether, then you can go into the nether and see a nether portal frame next to your own portal in the nether

### Observed/Actual behavior

No second portal should appear in the Nether

### Steps/models to reproduce

1. Place a Nether Portal Frame Important: Do not light the portal yet
2. Place a TNT on a lower block in the portal frame
3. Turn on the TNT and wait exactly until the TNT FAST ignites
4. Tongue out the portal if it worked, the TNT should be teleported into the Nether, if not then you will hear the TNT explode
5. Now enter the nether Important: before you enter the nether you should wait a bit to make sure that the tnt has already exploded in the nether
6. Now when you are in the Nether you should see a Second Nether Prootal frame next to a portal

### Plugin list

---

### Paper version

You are running the latest version
Previous version: git-Paper-593 (MC: 1.16.5)

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
and vs vanilla?
This just sounds like typical Minecraft behavior, if not, test against spigot/craftbukkit

**Comment by Snowiiii** [comment]
What do you mean found this bug on paper?

**Comment by electronicboy** [comment]
I'm not sure this is a bug as much as you disagreeing with how vanilla works, if vanilla doesn't work like this, I'd want to know who introduced this behavioral change; If this IS how vanilla works, you can change that behavior with a plugin quite trivially

**Comment by Snowiiii** [comment]
If you can fix it then please do so if not then not
