### ISSUE TITLE
Async Lighting causing chunk loads

### ISSUE THREAD

**Issue by Puremin0rez** [PaperMC/Paper#55]
This has started occurring in recent builds of Paper. My best guess as to why it has started occurring is because of the chunk lag fix that was added into Spigot and then merged from upstream into Paper. I did not have this problem prior to that upstream merge.

http://pastebin.com/raw/Mkyx5m1j

The aforementioned pastebin was from a 100% fresh server instance with async lighting enabled and the spam occurred on world generation. It might be async lighting related (since that thread is mentioned), but I do not have time to test that right now. (yes, i don't have time to flip a toggle in a config file, sue me)

@mibby has also had these issues earlier today and can help assist with anything else needed.

**Comment by mibby** [comment]
:)

**Comment by zachbr** [comment]
What version/s was this occurring on? I cannot reproduce this now, but there have been several changes since you opened this issue.

**Comment by Puremin0rez** [comment]
This issue occurred on "git-Paper-453"

I am now on "git-Paper-455" and can no longer cause this error to occur.

I'll leave this open so other parties can confirm.

**Comment by Puremin0rez** [comment]
Update: I lied.

I am still getting the problem, but not very often. I seem to be getting it most in the nether, but I've seen it trigger a few times for the main world.

I'm like 99% sure it started with this commit
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/60f01ef304badd4812cf17b3b39a3a53e4ee85d5

**Comment by zachbr** [comment]
We've forcibly disabled async light updates for the time being. It's clear that 1.9 has changed something underlying and we'll need to go back through this before it is considered safe for use in production. I believe Byteflux has volunteered to do so, and being that he wrote the current implementation, he is more than qualified.

**Comment by zachbr** [comment]
Async lighting has been removed entirely from the codebase.
