### ISSUE TITLE
Support for resetting user invalid statistics?

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#550]
PaperSpigot dev 978 (MC 1.11.1)

Minecraft seems to like to break stat tracking a lot. Is there any way to read all user stat files and purge the invalid statistics to prevent it from trying to load every time?

```
Invalid statistic in ./world/stats/5bc08448-d499-4ed6-8612-fdaa4ee7778b.json: Don't know what stat.drop.minecraft.totem is
```

**Comment by zachbr** [comment]
In builds 986+ set `remove-invalid-statistics` to `true` in paper.yml. It defaults to false.
