### ISSUE TITLE
ResultSet.TYPE_FORWARD_ONLY

### ISSUE THREAD

**Issue by YukanoXX** [PaperMC/Paper#5501]
### Expected behavior

i have that problem with every version of paper higher than #587

https://pastebin.com/LuAhhUd7

bevor no problems, no error posts

best regards
yukano

### Observed/Actual behavior

error logs on player join

### Steps/models to reproduce

by using paper version below 588 , all runs fine again

### Plugin list

mmocore, mmoitems , mythicLib, mythicmobs 

### Paper version

1.16.5 587+ until latest

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
Speak to the plugin author, they're using jdbc in a not so great way that breaks with the modern driver, we're not downgrading it as it was updated for security reasons.
