### ISSUE TITLE
Sign official PaperMC builds of Paper

### ISSUE THREAD

**Issue by Janmm14** [PaperMC/Paper#5502]
### Is your feature request related to a problem?

Recent threat of sophicisticated backdoor malware plugins over on spigotmc. I am concerned about malware spreading into other accessible jars on the system. I have seen one malware last year spreading into all plugin jars (not into the server jar yet though)

### Describe the solution you'd like.

Usage of some sort of certificate to sign official PaperMC builds of Paper. Could also be self-signed for 999 years or so. This allows for better checking of jar file modifications and some jar file modifications might even be stopped from running.

See also https://github.com/PaperMC/Waterfall/issues/629

### Describe alternatives you've considered.

none

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by electronicboy** [comment]
paperclip already performs basic validations, I don't really see what this solves which couldn't be trivially bypassed if they can work around paperclip

**Comment by MiniDigger** [comment]
Preeeeetttty sure the download APIs provides signatures you can verify if you are concerned about that kinda stuff and paperclip catches the most obvious things.

But like generally, just don't install sketchy plugins. A malicious plugin could disable the jar signing too if they want, this solves nothing against somebody who has full file access.

If you are concerned about security, you don't give the user running the server write perm to anything but config files and world files and run in docker, but even then, a malcious plugin is basically a RAT, so anything goes.

**Comment by Janmm14** [comment]
Ah yeah I forgot paperclip. This was meant as obstacle for malicious plugins, not as a way to completely block them.

**Comment by HexedHero** [comment]
This may give users a false sense of security, thinking as long as the validation passes they are not infected.

**Comment by MiniDigger** [comment]
Oh, another thing. Since SpigotMC pty ltd is the company providing a platform for such malicious activity, you should try to solve this problem at the root and bring it put to them.
Automatically flagging malicious code for staff review isn't all that hard, in fact, there are already open source solutions, directly tailored to minecraft. 
Relying on the community to do that for you is what we call a shitty move over here.

**Comment by aurorasmiles** [comment]
Most of the things we could do here could be easily mitigated by malicious software anyway. Use the hash to check the integrity of the file, and other than that, don't download software that you don't trust / don't know what it does, and don't download stuff from sketchy pages (or sites that for _some reason_ don't automatically check the code of plugins uploaded there)
