### ISSUE TITLE
Warn on the restart

### ISSUE THREAD

**Issue by nikitushu2** [PaperMC/Paper#5506]
### Expected behavior

No warn

### Observed/Actual behavior

17.04 19:31:57 [Server] INFO Flushing Chunk IO
17.04 19:31:57 [Server] INFO Closing Thread Pool
17.04 19:31:57 [Server] INFO Closing Server
17.04 19:31:57 [Server] WARN java.lang.Throwable: Server stopped
17.04 19:31:57 [Server] WARN at io.papermc.paper.util.TraceUtil.dumpTraceForThread(TraceUtil.java:16)
17.04 19:31:57 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.safeShutdown(MinecraftServer.java:992)
17.04 19:31:57 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.util.ServerShutdownThread.run(ServerShutdownThread.java:16)
17.04 19:31:59 [Multicraft] Server shut down (stopping)
17.04 19:31:59 [Multicraft] Server stopped

### Steps/models to reproduce

Install the latest Paper version for 1.16.5. Restart the server

### Plugin list

Warn appears even without any plugins installed

### Paper version

This server is running Paper version git-Paper-597 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-581 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
You have debug enabled in server.properties.

**Comment by nikitushu2** [comment]
Thanks
