### ISSUE TITLE
Breaking a shulker box in creative drops the shulker box item on the ground.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#551]
PaperSpigot dev 989

Assuming it may be a bug in minecraft. Shouldn't it not drop a shulker box when destroyed in creative, similar to how normal chests are destroyed when hit in creative?

**Comment by Black-Hole** [comment]
It's intended:
https://bugs.mojang.com/browse/MC-107380

**Comment by sudofox** [comment]
Have the shulker boxes you're placing been renamed, recolored, or had anything put inside of them before you broke them? @mibby 

I remember testing singleplayer, where empty shulker boxes didn't drop, but ones with stuff in it would.

**Comment by mibby** [comment]
That's a silly upstream bug if intended. =/ Everything else instantly destroys when hit in creative.

**Comment by supBross** [comment]
My shulker box will not drop even with item in it. Ive tried to use a piston does not drop

**Comment by mikroskeem** [comment]
@supBross Please open a new issue for that with detailed information.
