### ISSUE TITLE
TabCompletion not resetting on server switch with waterfall if disabled.

### ISSUE THREAD

**Issue by compieter-gh** [PaperMC/Paper#5511]
### Expected behavior

Tabcomplete should if disabled in spigot send a reset instead of doing nothing causing it to be overriden if a server has tabcomplete enabled in waterfall I issued this in waterfall itself but i think this is indeed more a paper/spigot issue than waterfall

### Observed/Actual behavior

If server 1 has tab complete enabled and server 2 disabled it gets all the suggestions from server 1 if send to that server.

### Steps/models to reproduce

First setup a bungee/waterfall environment then add at least 2 servers and disable tab complete on the second server then switch from server 1 too server 2 with tab complete disabled and you have your result it shows the suggestions of server 1 you can see this with adding a plugin too server 1 also.

### Plugin list

None or only worldedit.

### Paper version

This server is running Tuinity version git-Tuinity-"7d36676" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by MiniDigger** [comment]
please either repro on paper or report to tuinity

**Comment by compieter-gh** [comment]
![image](https://user-images.githubusercontent.com/34034571/115424346-ecb54580-a1fe-11eb-9237-44a02e670cd0.png)
Reproduced it on paper and provided a screenshot.
@MiniDigger
