### ISSUE TITLE
[1.12.2PaperSpigot]crash report help

### ISSUE THREAD

**Issue by qaz13570111** [PaperMC/Paper#5518]
### Stack trace

my log

### Plugin list

plugin list

### Paper version

Paper version: git-Paper-1618 (MC: 1.12.2)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
> My version of Minecraft is supported by Paper

nope
