### ISSUE TITLE
WorldGuard second boot: SIGBUS when trying to initialize SQLite profile cashe

### ISSUE THREAD

**Issue by dettner** [PaperMC/Paper#5520]
### Stack trace

https://paste.gg/p/anonymous/4378a51cfde7460786840066fecac9cd

### Plugin list

FastAsyncWorldEdit-Bukkit-1.16-657
worldguard-bukkit-7.0.4

### Actions to reproduce (if known)

1. Install WorldGuard
2. Start papermc
3. Everything works: WorldGuard works in-game. Directory plugins/WorldGuard/ is created
4. Stop papermc
5. Start papermc
6. ---> server crashes upon boot when initializing WorldGuard, according to dump in above pastebin.gg
7. Remove worldguard.jar, start papermc: The server boots without fail, but WorldGuard is not recognized
8. Add worldguard.jar, but remove directory plugins/WorldGuard works, like step 1+ above

### Paper version

 This server is running Paper version git-Paper-603 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
Not a paper issue, OSes don't like it when you modify files underneath them, if anything it's a JVM issue, but, not something anybody cares about

**Comment by dettner** [comment]
Thank you for your quick response! 

I have no clue as to who modified any file (or even what file). 

I guess somebody cares about this (me). But ok, thank you anyway!

**Comment by electronicboy** [comment]
Oh, actually, sigbus there miiight imply that some plugin is shading sqlite in and caused a conflict, sigbus means that something tried to access bad memory, e.g. incorrectly accessing some location in a file
