### ISSUE TITLE
1.11 forge client getting out of date message from 1.11.2 server

### ISSUE THREAD

**Issue by VerserVarlin** [PaperMC/Paper#553]
forge-13.19.1.2197 clients are not connecting to 1.11.2 version of papermc. getting out of date message. i am not the server owner so i cant give you the build number he is using but he updated within the last 12 hrs and before the update i was able to connect. forge runs 1.11. i think this might just be a protocol issue as in previous versions of mc i.e 1.10.2 you could connect so servers that where on the latest version of the server with a earlier version of 1.10. i hope this is resolved as i really like having my basic quality of life mods when i play on the server.

**Comment by liach** [comment]
1.11 is not compatible with 1.11.2.
