### ISSUE TITLE
Item NBTag changes on player rejoin

### ISSUE THREAD

**Issue by giuseppetrematerra** [PaperMC/Paper#5531]
### Expected behavior

.

### Observed/Actual behavior

I renamed an item through Paper-API into a colored text and its NBTag is just:
![image](https://user-images.githubusercontent.com/29181155/115786961-ca1f5a00-a3c1-11eb-81a5-e3d144975086.png)
but when I logoff and rejoin, it becomes:
![image](https://user-images.githubusercontent.com/29181155/115787005-d9060c80-a3c1-11eb-8cab-1db9733407f1.png)
making it completely unstackable and different from the previous one.
Now, i know theres a Component API to make that kind of stuff and indeed i have used it to make a TextComponent as follow:
`itemMeta.displayName(Component.text(ChatUtils.colorMessage(name)));`

### Steps/models to reproduce

Just rename an item, logoff and check its NBTag.

### Plugin list

Custom

### Paper version

Paper version git-Paper-597 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
There is 0 promises that internal data will remain consistent, especially as this data is loaded into it's proper representation as an object and then reserialised on leave, there is literally nothing we can do about this and you should avoid your reliance on broken components

**Comment by electronicboy** [comment]
(instead of tryna stuff legacy chat formatting into a component, use the legacy serialiser to create a real component structure)

**Comment by giuseppetrematerra** [comment]
Is there any API for legacy string conversion to the proper representation?

**Comment by electronicboy** [comment]
Yes, use the legacy serialiser

**Comment by giuseppetrematerra** [comment]
> Yes, use the legacy serialiser

Could you please link me the Documentation for this serialiser?

**Comment by lynxplay** [comment]
Use [this](https://papermc.io/javadocs/paper/1.16/io/papermc/paper/text/PaperComponents.html#legacySectionSerializer--) to get yourself a serializer and then you may use [deserialize](https://jd.adventure.kyori.net/text-serializer-legacy/4.7.0/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer.html?is-external=true#deserialize(java.lang.String)) or [serialize](https://jd.adventure.kyori.net/text-serializer-legacy/4.7.0/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer.html?is-external=true#serialize(net.kyori.adventure.text.Component)).

**Comment by giuseppetrematerra** [comment]
Ok thank you so much. I achieved my goal doing this if someone was interested:
```java var serializer = LegacyComponentSerializer.legacyAmpersand();
        var component = serializer.deserialize("&7[&f&lBlock &c&lWand&7]");
        component = component.decoration(TextDecoration.ITALIC, false);
        return component;
