### ISSUE TITLE
Click anvil or smithing table, InventoryOpenEvent always return CRAFTING.

### ISSUE THREAD

**Issue by MiunaPA** [PaperMC/Paper#5537]
### Expected behavior

When player click anvil or smithing table, InventoryOpenEvent should be returned is ANVIL or SMITHING.

### Observed/Actual behavior

Click anvil or smithing table, InventoryOpenEvent always return CRAFTING.

### Steps/models to reproduce

This is my testing code

```java
@EventHandler
public void onInventoryOpenEvent(InventoryOpenEvent event) {
   Player player = (Player) event.getPlayer();
   player.sendMessage(event.getInventory().getType().getDefaultTitle());
}
```

Click anvil return display Anvil , but it is return crafting
Click smithing table also return crafting.
[Testing Code GIF](https://imgur.com/04CJnOZ)

### Plugin list

[00:41:46 INFO]: Plugins (38): AdvancedPortals, BKCommonLib, BossShopPro, Brewery, BungeeTabListPlus, ChatControl, Citizens, ClearLag, CoreProtect, DiscordSRV, FastLeafDecay, GSit, HolographicDisplays, IllegalStack, ImageOnMap, Lasso, LightCleaner, LockettePro, LuckPerms, MysqlPlayerDataBridge, OpenInv, PA_Item, PA_Mailbox, PA_Money, PA_ServerFeature, PA_Teleport, PlaceholderAPI, PlayerHeads, PlayerParticles, PlugMan, ProtocolLib, Residence, Shopkeepers, ShulkerPacks, Vault, ViaVersion, VillagerOptimiser, WorldEdit

### Paper version

[00:41:30 INFO]: This server is running Paper version git-Paper-621 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-601 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Prof-Bloodstone** [comment]
CraftBukkit issue, reported upstream: https://hub.spigotmc.org/jira/browse/SPIGOT-6434

**Comment by Prof-Bloodstone** [comment]
Upstream thinks it works as intended. Unfortunately currently we are not able to do breaking changes like this, but hopefully there will be a mechanism in the future which will let us fix it.

The issue is that both blocks have `InventoryType.CRAFTING`, instead of having separate ones.

In the case of this event, if you want to get the real title, retrieve it from InventoryView: `event.getView().title()`

**Comment by Machine-Maker** [comment]
Ugh. How would it be considered a breaking change to fix a bug? Like I feel like it’s bugged behavior, and if someone is relying on that, that’s their problem. The xkcd about breaking workflows comes to mind.

**Comment by HexedHero** [comment]
In the same boat as Machine, don't see how this is intended at all. You're listening for the inventory open event and when a player opens the anvil inventory it doesn't tell you the correct inventory that was opened, seems like a bug.

Edit: After some research from `Nicole#0001`, it seems to be a Bukkit introduced bug.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/world/inventory/ContainerAnvilAbstract.patch#7,23

**Comment by Prof-Bloodstone** [comment]
We've re-considered this. I'll be raising your finding and my patch with MD_5 to hopefully have it fixed upstream, but we might end up having to fix it in Paper.

**Comment by Prof-Bloodstone** [comment]
Fixed upstream: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/a8d7c94a5b698732029f2f153904cbe943e70e71
Should be pulled to Paper shortly.
