### ISSUE TITLE
Stacktrace spamming

### ISSUE THREAD

**Issue by NicoNekoDev** [PaperMC/Paper#554]
StackTrace: http://pastebin.com/vSvEWySh

Btw, 'Elementals' is my plugin, but i don't see where exactly is this error.

Plugin list: CoreProtect, Itemizer, WorldEdit, SimpleTrading, GroupManager, ClearLag, XrayInformer, PlugMan, FastCraftPlus, PandaWire, Votifier, ProtocolLib, LibsDisguises, SkinsRestorer, ChopTree3, TagRegisterLib, EchoPet, SQLibrary, FeatherBoard, mcMMO, ActionAnnouncer, Tim, Tablist, Vault, MCMMOXPBar, ChestShop, Essentials, AnimatedNames, Citizens, ChestCommands, EssentialsChat, CraftBay, EssentialsSpawn, Denizen, MobCommands, CompatNoCheatPlus, AuthMe, NoCheatPlus, Sentinel, Builder, HolographicDisplays, Shopkeepers, LeaderHeads, CombatIndicator, TouchscreenHolograms, Elementals
Paper build number: 991 (MC: 1.11.2)

**Comment by Black-Hole** [comment]
Please post the complete stacktrace and please copy it from the log file so that the lines are in order.

**Comment by aikar** [comment]
@nicuch you cut off the most important part of the stack trace.

We need more information.

**Comment by NicoNekoDev** [comment]
ye, i'm sorry, i found it, aparently in multicraft is not showing up full error log. sorry for wasting time.
