### ISSUE TITLE
Persistent "Hostile" Mobs Despawn when out of Range

### ISSUE THREAD

**Issue by Fredthedoggy** [PaperMC/Paper#5545]
### Expected behavior

When Going out of range of a (Specifically NoAI, Persistent, Invulnerable) Hostile mob, the mob should stay spawned even though the Hostile Mobs normally despawn when out of range.

### Observed/Actual behavior

When Going out of range of a (Specifically NoAI, Persistent, Invulnerable) mob, it seems to despawn, even though it is persistent.

### Steps/models to reproduce

running the code:
```java
entity.setPersistent(true);
entity.setAI(false);
entity.setInvulnerable(true);
entity.teleport(new Location(entity.getWorld(), entity.getWorld().getSpawnLocation().getX(), 200.0, entity.getWorld().getSpawnLocation().getZ()));
```
with a Hostile mob, when you are nearby spawn, but low down.

### Plugin list

```
Plugins (1): TakeoverMobs
```
(My Test Plugin)

### Paper version

```
git-Paper-628
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by imDaniX** [comment]
[`LivingEntity#setRemoveWhenFarAway(false)`](https://papermc.io/javadocs/paper/1.16/org/bukkit/entity/LivingEntity.html#setRemoveWhenFarAway-boolean-)

**Comment by electronicboy** [comment]
that just sets the persistence flag

**Comment by Machine-Maker** [comment]
As imDaniX and electronicboy said, Entity#setPersistent has nothing to do with despawning, but rather if the entity will be saved on the next unload. setRemoveWhenFarAway is what you are looking for.
