### ISSUE TITLE
SetDifficulty method not changing Moster Spawn flag

### ISSUE THREAD

**Issue by AyhamAl-Ali** [PaperMC/Paper#5546]
### Expected behavior

When using `World#setDifficulty` from `PEACEFUL` to any other difficulty it should set `Monster Spawn` flag of that world to true by itself.

Currently in plugins, to make that we have to use and extra method which is `World#setSpawnFlag` otherwise the difficulty will change but monsters won't spawn.

### Observed/Actual behavior

Difficulty of world changes but Monsters don't spawn if difficulty is not `PEACEFUL`

### Steps/models to reproduce

```java
world.setDifficulty(Difficulty.PEACEFUL); // Monsters will despawn
world.setDifficulty(Difficulty.HARD); // Monsters won't spawn again unless we use World#setSpawnFlag

```

### Plugin list

None.

### Paper version

```java
> version
[12:21:34 INFO]: Checking version, please wait...
[12:21:35 INFO]: This server is running Paper version git-Paper-629 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
Must be fixed upstream; introducing side-effects to relatively unrelated methods is... undesirable.

**Comment by Prof-Bloodstone** [comment]
I see the issue, though it's worth nothing it's not reproducible with your steps. Setting difficulty through API to peaceful doesn't set those flags, and thus after setting difficulty to HARD, monsters will still spawn:
```
/js server.getWorld("world").setDifficulty(org.bukkit.Difficulty.PEACEFUL) # Monsters despawn
/js server.getWorld("world").getAllowMonsters() # -> true
/js server.getWorld("world").setDifficulty(org.bukkit.Difficulty.HARD) # Monsters start spawning again
```
The issue is that it creates a difference between what vanilla `/difficulty` command does and what `World#setDifficulty()` does.

I'd argue that this `gotcha` should be mentioned in JDs and left as is, since it's valid to change difficulty to HARD without setting those flags, as difficulty controls a lot more behaviors in the world.
If you want this behavior to change, you'd need to report it to Spigot at https://hub.spigotmc.org/jira.

**Comment by AyhamAl-Ali** [comment]
I am indeed comparing this with `/difficulty` command because when we use it it will spawn/despawn monsters and toggle their spawn as I have noticed in-game.

When I tried to make the same result of the command using my code, it didn't work with the steps I provided above.

I have already reported that to Spigot as well, haven't got a respond yet.

> Setting difficulty through API to peaceful doesn't set those flags, and thus after setting difficulty to HARD, monsters will still spawn:

I don't know the actual code behind changing Difficulty but once it is changed to `PEACEFUL` monsters stop spawning and when I set it back to `HARD` it changes successfully but monsters don't spawn again until server is restarted.

EDIT:
Here is [Spigot's issue link](https://hub.spigotmc.org/jira/browse/SPIGOT-6437)

**Comment by Proximyst** [comment]
> I am indeed comparing this with `/difficulty` command because when we use it it will spawn/despawn monsters and toggle their spawn as I have noticed in-game.

The difficulty command calls `MinecraftServer#a(WorldServer, EnumDifficulty, boolean)`, which also sets the flags. `World#setDifficulty(Difficulty)` of Bukkit's API only calls `WorldDataServer#setDifficulty(EnumDifficulty)` directly, which does not set the flag. This is a behavioural difference in Bukkit's implementation to the command, and not one we're willing to break.

> 
> When I tried to make the same result of the command using my code, it didn't work with the steps I provided above.
> 
> I have already reported that to Spigot as well, haven't got a respond yet.
> 
> > Setting difficulty through API to peaceful doesn't set those flags, and thus after setting difficulty to HARD, monsters will still spawn:
> 
> I don't know the actual code behind changing Difficulty but once it is changed to `PEACEFUL` monsters stop spawning and when I set it back to `HARD` it changes successfully but monsters don't spawn again until server is restarted.

I cannot reproduce this.

```kotlin
class BDifficultyCommand : BaseCommand() {
    override fun register(manager: PaperCommandManager<CommandSender>) {
        val difficulty = EnumArgument.of<CommandSender, Difficulty>(Difficulty::class.java, "difficulty")
        val world = WorldArgument.of<CommandSender>("world")

        val base = manager.commandBuilder("bdifficulty")
            .argument(difficulty)
        manager.command(base
            .argument(world)
            .handler {
                it[world].difficulty = it[difficulty]
            })
        manager.command(base
            .sender<Player>()
            .handler {
                it.sender.world.difficulty = it[difficulty as EnumArgument<Player, Difficulty>]
            })
    }
}
```

Hostile mobs despawn the second I do `/bdifficulty peaceful`, then spawn again once I do `/bdifficulty hard`. The code on the server as far as I could find and documented above also supports this behaviour.

> 
> EDIT:
> Here is [Spigot's issue link](https://hub.spigotmc.org/jira/browse/BUILDTOOLS-582?filter=-4)

**Comment by AyhamAl-Ali** [comment]
> The difficulty command calls MinecraftServer#a(WorldServer, EnumDifficulty, boolean), which also sets the flags. World#setDifficulty(Difficulty) of Bukkit's API only calls WorldDataServer#setDifficulty(EnumDifficulty) directly, which does not set the flag. This is a behavioural difference in Bukkit's implementation to the command, and not one we're willing to break.

I understand. That's correct I saw `/difficulty` command code and saw that it uses `MinecraftServer#a(WorldServer, EnumDifficulty, boolean)` that's how I got the idea of `setSpawnFlag`.

Since this is intended I think we reached the point of understanding.
