### ISSUE TITLE
World#refreshChunk​(int x, int z) is broken since 1.16

### ISSUE THREAD

**Issue by stonar96** [PaperMC/Paper#5551]
### Expected behavior

[World#refreshChunk​(int x, int z)](https://papermc.io/javadocs/paper/1.16/org/bukkit/World.html#refreshChunk-int-int-) should resend the entire chunk to nearby players. For example if Anti-Xray is enabled and a player gets the permission to bypass Anti-Xray, [World#refreshChunk​(int x, int z)](https://papermc.io/javadocs/paper/1.16/org/bukkit/World.html#refreshChunk-int-int-) should remove the Anti-Xray fake blocks from that chunk.

### Observed/Actual behavior

Since 1.16 this isn't the case anymore. The source code of [World#refreshChunk​(int x, int z)](https://papermc.io/javadocs/paper/1.16/org/bukkit/World.html#refreshChunk-int-int-) contains the following comments:
```java
// If there are more than 64 updates to a chunk at once, it will update all 'touched' sections within the chunk
// And will include biome data if all sections have been 'touched'
// This flags 65 blocks distributed across all the sections of the chunk, so that everything is sent, including biomes
```
However, this assumption isn't true anymore in 1.16. Only `PacketPlayOutMultiBlockChange` are used for those updates.

### Steps/models to reproduce

- Enable Anti-Xray in `engine-mode: 2` with `use-permission: true` and add `- air` to `hidden-blocks` in paper.yml.
- Join the server as spectator and non op (no permissions). (You should see the fake ores in the underground.)
- Op yourself.
- Invoke [World#refreshChunk​(int x, int z)](https://papermc.io/javadocs/paper/1.16/org/bukkit/World.html#refreshChunk-int-int-) for a visible chunk.

### Plugin list

A plugin to invoke [World#refreshChunk​(int x, int z)](https://papermc.io/javadocs/paper/1.16/org/bukkit/World.html#refreshChunk-int-int-).

### Paper version

> version
[01:33:01 INFO]: Checking version, please wait...
[01:33:01 INFO]: This server is running Paper version git-Paper-629 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Owen1212055** [comment]
Functionality was brought back in: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/c86a3f7a5877acb5406147923ac48d91c2f6e7d4

However, the new implementation uses x-ray, https://github.com/PaperMC/Paper/pull/7214 will revert this. So this is half fixed.
