### ISSUE TITLE
PlayerTradeEvent

### ISSUE THREAD

**Issue by Will33ELS** [PaperMC/Paper#5552]
### Is your feature request related to a problem?

Call the PlayerTradeEvent when trading on a CraftMerchantCustom. This will allow me to increment the usage value and check if the maximum number of trades has not been reached.

### Describe the solution you'd like.

Call the PlayerTradeEvent or create another one with a null abstractvillager

### Describe alternatives you've considered.

Allow a merchant to open his trading interface to multiple players and if the maximum usage value has been reached cancel the trading event and close the interface.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Machine-Maker** [comment]
I'd say this is a bug, because it should've been called here from the beginning. 

I'm not sure how to fix this exactly... It would be an API break to let the villager be null in PlayerTradeEvent. It probably has to be a whole separate event.

**Comment by Machine-Maker** [comment]
Was fixed/implemented in afe0785bfe28edf438cba6548a6fface3a72dfaa

#5263 needs to be fixed for both custom and regular merchants however.

**Comment by Will33ELS** [comment]
Thank you ;)
