### ISSUE TITLE
/version error

### ISSUE THREAD

**Issue by kanetjuh** [PaperMC/Paper#5556]
### Expected behavior

It should log the normal version without sending an error message and an error in the console

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/50002439/116607032-c9427700-a931-11eb-9d3a-873630a0164a.png)
With the message in minecraft: **"Error obtaining version information"**

### Steps/models to reproduce

![image](https://user-images.githubusercontent.com/50002439/116607109-e70fdc00-a931-11eb-8187-f226862e5beb.png)

### Plugin list

None

### Paper version

1.12.2

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
> My version of Minecraft is supported by Paper

false
outdated version uses an endpoint no longer public
