### ISSUE TITLE
Hostname validation fail

### ISSUE THREAD

**Issue by Florianpal1** [PaperMC/Paper#5559]
### Expected behavior

All players should be able to switch servers.

### Observed/Actual behavior

On the server, we have two types of players simultaneously, crack and premium. The premiums can change server. But the cracks when they try to change server. And we use the pterodactyl system to run our servers, only the proxy has access to the public ip of the proxy.

For the git-600 version: we have an error message :
Server thread/INFO]: /172.18.0.1:40786 lost connection: Invalid hostname. The strange thing is that it uses an internal ip of the machine and not its own ip. 

For the git-634 version we have an error message: 
[Server thread/INFO]: /172.18.0.1:52394 lost connection: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!

The ip_forward parameter is enabled on our proxy. Only cracked players have this problem.

### Steps/models to reproduce

To reproduce the problem, you need a system that handles cracks and premiums at the same time on a proxy. And you try to switch servers with a cracked player.

### Plugin list

![image](https://user-images.githubusercontent.com/36370356/116731582-28fc5900-a9ea-11eb-96e4-cd7b4e11d3ef.png)

### Paper version

git-Paper-600 (MC : 1.16.5) and tested git-Paper-637 (MC : 1.16.5) and i am the same result but a different error message.
![image](https://user-images.githubusercontent.com/36370356/116733669-aaed8180-a9ec-11eb-826e-0aa7e3ddda30.png)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
Pass `-DPaper.bypassHostCheck=true`.
