### ISSUE TITLE
Coping chests with worldedit crashes paper

### ISSUE THREAD

**Issue by Sandukhan** [PaperMC/Paper#5564]
### Stack trace

https://pastebin.com/b0qcyVs2

### Plugin list

- Worldguard-7.0.4
- Worldeidt-7.2.5
- rest see above

### Actions to reproduce (if known)

- Select a chest with worldedit by using the we-tool
- copy the chest with //copy

### Paper version

[15:25:55 INFO]: This server is running Paper version git-Paper-640 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by aurorasmiles** [comment]
Please properly fill out the issue template, and include a **full** error log.
