### ISSUE TITLE
Shift clicking over 1 ingot of any type into a beacon makes the beacon not activate.

### ISSUE THREAD

**Issue by iT3g4n** [PaperMC/Paper#5570]
### Expected behavior

If I shift click iron, netherite, diamond, etc. ingots, it should put 1 into the beacon, and it should activate when I click on the check mark.

### Observed/Actual behavior

It remove the ingots from my inventory until re-logging.

### Steps/models to reproduce

a normal beacon, maxed out with iron blocks (is where the issue happened for me) and 16 iron ingots in inventory, shift clicking them while in the beacon menu.

### Plugin list

MCServer/plugins/ActionHealth.jar
MCServer/plugins/AFKPlus.jar
MCServer/plugins/AutoRestart-v4.jar
MCServer/plugins/ClearChat.jar
MCServer/plugins/ColoredSigns-4.2.0.jar
MCServer/plugins/ConsoleScheduler.jar
MCServer/plugins/DoubleShulkerShells.jar
MCServer/plugins/Dynmap-3.1-spigot.jar
MCServer/plugins/DynmapStructures-2.3.1.jar
MCServer/plugins/Economobs-1.2.1.jar
MCServer/plugins/JoinMessagePlus-v3.3.jar
MCServer/plugins/LuckPerms-Bukkit-5.3.16.jar
MCServer/plugins/nLogin.jar
MCServer/plugins/NoChunkLag.jar
MCServer/plugins/ProtocolLib.jar
MCServer/plugins/ServerRestorer.jar
MCServer/plugins/SignShop-3.5.0.jar
MCServer/plugins/SkinsRestorer.jar
MCServer/plugins/tabtps-spigot-1.3.4.jar
MCServer/plugins/TNE.jar (the new economey)
MCServer/plugins/Vault.jar
MCServer/plugins/VeinMiner-Bukkit-1.17.6.jar
MCServer/plugins/WebConsole-2.1.jar
MCServer/plugins/worldedit-bukkit-7.2.4.jar

### Paper version

> version
[21:24:40 INFO]: Checking version, please wait...
[21:24:41 INFO]: This server is running Paper version git-Paper-642 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-641 (MC: 1.16.5)

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
"untl relogging" implies that something cancelled the movement improperly, can you replicate without plugins? can you replicate on spigot/craftbukkit/vanilla?

**Comment by iT3g4n** [comment]
This is the /plugins command output

Plugins (24): ActionHealth*, AFKPlus, AutoRestart*, ClearChat*, ColoredSigns*, ConsoleScheduler*, DoubleShulkerShells, dynmap*, dynmap-structures, Economobs, JoinMessagePlus, LuckPerms, nLogin, NoChunkLag, ProtocolLib, ServerRestorer, SignShop, SkinsRestorer, TabTPS, TheNewEconomy, Vault, VeinMiner, WebConsole, WorldEdit

**Comment by iT3g4n** [comment]
> "untl relogging" implies that something cancelled the movement improperly, can you replicate without plugins? can you replicate on spigot/craftbukkit/vanilla?

sorry I meant disconnecting and reconnecting to the server.

**Comment by e-im** [comment]
> shift-clicking them while in the beacon menu

Without plugins or client mods, you are also unable to shift-click items into a beacon. Going to close this as the issue comes from a plugin or client mod. However, if you can reproduce without plugins on the server (providing a list is not sufficient) and a vanilla client, do leave a comment.
