### ISSUE TITLE
RespawnFlags PR breaks NMS method signature

### ISSUE THREAD

**Issue by mcmonkey4eva** [PaperMC/Paper#5575]
I received user reports of: `java.lang.NoSuchMethodError: 'net.minecraft.server.v1_16_R3.EntityPlayer net.minecraft.server.v1_16_R3.DedicatedPlayerList.moveToWorld(net.minecraft.server.v1_16_R3.EntityPlayer, net.minecraft.server.v1_16_R3.WorldServer, boolean, org.bukkit.Location, boolean)'` 

I have verified the error myself on latest build (642) and presume it to apply all the way back to 633. Verified not present on 632 as well.

This patch: <https://github.com/PaperMC/Paper/blob/976c6d425b03dbdf3b695bd10b2f871fcc72edac/Spigot-Server-Patches/0717-add-RespawnFlags-to-PlayerRespawnEvent.patch> from this PR: <https://github.com/PaperMC/Paper/pull/5533>
is breaking as Denizen relies on that method

If an alternate signature is useful internally for that commit, the original signature should be kept as simply an autoredirect call to the new signature with whatever applicable default for the new parameter.

However I note in this case, as far as internal usage goes, the new parameter is always the same constant `RespawnFlag.END_PORTAL`, so it might be better to just switch the signature back to how it was and transfer the constant to just be specified on line 38 there

cc @Machine-Maker and @kashike (relevant to the PR)

**Comment by Trigary** [comment]
https://github.com/PaperMC/Paper/pull/5573
