### ISSUE TITLE
Whitelist command seems to be broken?

### ISSUE THREAD

**Issue by slaapkopamy** [PaperMC/Paper#5576]
### Expected behavior

/whitelist add name > name gets added to the json file
/whitelist remove name > name gets removed from the json file

### Observed/Actual behavior

/whitelist add name > no response
/whitelist remove name > no response
/whitelist reload > response with successfully reloaded

### Steps/models to reproduce

Step 1. Add people to your server whitelist.
Step 2. Repeat until it breaks... (like less then 40 names...)
Step 3. Now you have a json file where no users can't be added until they been in the server..

### Plugin list

![0t3HwiogG4ikKYzmQCwt](https://user-images.githubusercontent.com/32595704/117066256-cfb56200-ad28-11eb-9c03-270568cbcde7.png)
datapacks: oneplayersleeping + creepers dont do block damage.

### Paper version

git-paper-643 (mc: 1.16.5) api version: 1.16.5-R0.1-SNAPSHOT)
previous version git-paper-640 (mc: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
I looked into this and looks like mojangs servers are having some issues

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/117071057-7c421480-ad26-11eb-9811-431b911e0bf4.png)

**Comment by electronicboy** [comment]
https://bugs.mojang.com/projects/WEB/issues/WEB-4457
