### ISSUE TITLE
Keep console commands history after restart

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#5578]
### Is your feature request related to a problem?

I have a txt for for some useful commands, but every time after I restart server, I'm need to open this file and search for required command again, then copy+paste into console. 

### Describe the solution you'd like.

Save last N commands (it would be nice if the amount can be configured) to `console_history.json` (for example) or use (currently useless) `.console_history` file, and load it into console after server is started.

### Describe alternatives you've considered.

Currently I don't know.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Proximyst** [comment]
This is default behaviour in 1.16.5.

**Comment by molor** [comment]
@Proximyst, omg. I used 1.16.5 on public server, but the test server (that mentioned in this issue) runs on 1.16.3 and this is my fault. I'm sorry, thanks!
