### ISSUE TITLE
CME when removing mob goals when EntityTargetEvent is called

### ISSUE THREAD

**Issue by froobynooby** [PaperMC/Paper#5581]
### Expected behavior

You should be able to remove mob goals when EntityTargetEvent is called

### Observed/Actual behavior

It throws a CME and the entity is removed from the world: https://paste.gg/p/anonymous/73775931bea04bf4844b66a92abb7c66

### Steps/models to reproduce

1. Download and install TestPlugin (it is in the zip archive).
2. Start up the server and spawn a sheep.
3. Tempt the sheep with some wheat and the error should appear

### Plugin list

[TestPlugin](https://github.com/PaperMC/Paper/files/6433000/testplugin.zip):
```java
public class TestPlugin extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onEntityTarget(EntityTargetEvent event) {
        if (event.getEntity() instanceof Creature) {
            Creature entity = (Creature) event.getEntity();
            if (Bukkit.getMobGoals().hasGoal(entity, VanillaGoal.RANDOM_STROLL_LAND)) {
                Bukkit.getMobGoals().removeGoal(entity, VanillaGoal.RANDOM_STROLL_LAND);
            }
        }
    }
}
```

### Paper version

This server is running Paper version git-Paper-645 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
This would require us to copy all mob goals for every single mob ticked. You can start a new task for next tick to work around this.

**Comment by electronicboy** [comment]
Not really a bug, you're trying to modify the mobs goal list while the goals are running, best we could maybe do is just guard against this by throwing an exception if you try to modify it during iteration, beyond that, many of the solutions for this which allow you to mess around with a collection being iterated require changing things, like cloning the collection each tick, or looking at different collections which may allow this, praying that they retain the same order of insertion, etc, as the current impl used...

**Comment by froobynooby** [comment]
I still feel this should be addressed in some way or another. It's not documented and it's inconsistent - for example: modifying goals on EntityTameEvent will cause a CME for horses but not for wolves or ocelots; and modifying goals on EntityInteractEvent will cause CME for zombies breaking turtle eggs but not for them walking over a tripwire.

It also causes the entity to be removed from the world - noting the exception does not occur when adding/removing the goals, but in the entity's tick loop when it tries to move onto the next goal. It would surely be better to do as cat suggested and have addGoal/removeGoal throw an exception if the goal selector is in the middle of ticking. Ideally the API should always stop you from putting an entity into an illegal state
