### ISSUE TITLE
Returned team color is invalid

### ISSUE THREAD

**Issue by janLindner** [PaperMC/Paper#5585]
### Expected behavior

Using `Team#color()` should return a valid color implemetation when previously was set with `Team#setColor(NamedTextColor.RED)`.

### Observed/Actual behavior

An exception is thrown when calling `Team#color()`: `IllegalStateException: Team colors must have hex values`

### Steps/models to reproduce

Set color of a team with `Team#color(...)` then access the color with `Team#color()`.

### Plugin list

ProtocolLib

### Paper version

This server is running Paper version git-Paper-645 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

It would also be helpful if the color returned by Team would be `NamedTextColor` and not just `TextColor` as Teams can only use `NamedTextColors`. 

It probably has something todo with the internal color handling: 
![image](https://user-images.githubusercontent.com/18546571/117315315-df978800-ae87-11eb-95de-56852363e222.png)

**Comment by electronicboy** [comment]
That's checking the nms color, not the adventure color, you'll note that it does the Color > TextColor after that one and returns a NamedTextColor, can you see what the current value is?

**Comment by kezz** [comment]
What probably happened here is you set the colour of the team to a format (bold/strikethrough/etc) and then are trying to retrieve the colour as a `TextColor`, hence this exception will be thrown. Basically, teams are handled in NMS with the legacy chat format enum (which includes the formatting codes) but the Adventure methods here don't accept or return these colours. I raised this issue in the past and you can see the discussion [here](https://github.com/PaperMC/Paper/issues/5302). Essentially, the resolution was that it works as intended in line with the Vanilla teams command.

**Comment by janLindner** [comment]
Thanks for your responses. 

I investigated a bit further on my side, and it is acutally not connected with setting the team color with `Team#color(...)`. But instead with creating a new Team without any manuall color formatting, then the color is internally set to §r -> RESET. 

I would expect the default value for the team color to be WHITE and not RESET.

**Comment by janLindner** [comment]
But the described behavior is therefore obviously working as intended.
