### ISSUE TITLE
ItemMeta doesn't include vanilla attributes added in nms overrides

### ISSUE THREAD

**Issue by caucow** [PaperMC/Paper#5587]
### Expected behavior

Calling ItemMeta.getAttributeModifiers() or any of its overloads returns all AttributeModifiers on an item.

### Observed/Actual behavior

If a vanilla item adds AttributeModifiers by overriding vanilla's getAttributeModifiers method (`Item.a(EnumItemSlot)`), they are not properly wrapped and returned by ItemMeta, as ItemMeta is only checking the item's NBT for AttributeModifiers.

### Steps/models to reproduce

Call `ItemStack.getItemMeta().getAttributeModifiers()` or any of its overloads on an item that, in vanilla, has AttributeModifiers built into the item (ex. tools, armor, swords, trident).

Using the test plugin, log into the server and hold a (tools, armor, swords, trident) and run the `/test` command. `null` will be printed in the console, despite the player being able to mouse over the item and see the tooltip from attackdamage/attackspeed/armor AttributeModifiers.

### Plugin list

[TestPlugin.zip](https://github.com/PaperMC/Paper/files/6438204/TestPlugin.zip)
```
public class TestPlugin extends JavaPlugin implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender cs, Command cmnd, String string, String[] args) {
        Player p = (Player) cs;
        ItemStack heldItem = p.getInventory().getItemInMainHand();
        ItemMeta meta = heldItem.getItemMeta();
        if (meta != null) {
            System.out.println(meta.getAttributeModifiers());
        }
        return true;
    }   
}
```

### Paper version

> version
[19:55:16 INFO]: Checking version, please wait...
[19:55:17 INFO]: This server is running Paper version git-Paper-647 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 1 version(s) behind
Previous version: git-Paper-631 (MC: 1.16.5)

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

/version reports I'm 1 version behind, latest available on papermc.io is what I'm running.

Referencing #5311 here, I'm trying to make a plugin that makes use of vanilla damage attributes on an item (ie I need to know how much base damage it will do when hitting an entity). There is not currently any API method for calculating an Attribute's final value, so I am forced to check the mc wiki and do the calculation myself. However, since the API currently does not list AttributeModifiers added via nms method override, I am forced to use nms/reflection to get that information.

**Comment by Machine-Maker** [comment]
So this isn't super simple. Right now, the item meta doesn't know anything about the Material its the meta of. Since those attributes are the same for each Item/Material, I think it would be better to add methods to get attributes to the Material enum (where Material#isItem is true).

**Comment by Machine-Maker** [comment]
(just gonna expand on the reason why this shouldn't be a thing)

ItemMeta is the API representation of an itemstacks NBT, and since those vanilla (or default) attributes aren't present in the itemstack NBT, they don't belong in the ItemMeta either
