### ISSUE TITLE
Issue about detecting distance between player and target

### ISSUE THREAD

**Issue by Hivane060** [PaperMC/Paper#5589]
### Expected behavior

The distance between player and target should be detected when the player is aiming to the target (Without any solid blocks to obstruct the view)

### Observed/Actual behavior

When I am into the range where I can break the block I'm aiming while also aiming the target, the distance won't be detected anymore. 

More specifically, I won't get the distance value from org.bukkit.location.distance()

Here is an example:
![2021-05-07_19 03 19](https://user-images.githubusercontent.com/83833914/117484102-eb0db080-af66-11eb-9137-490ea39251e7.png)
If I aim that wither skeleton, but also my crosshair is aiming that obsidian block, the distance won't be detected.

This issue occurs only survival and creative mode (While in adventure mode it works well)

### Steps/models to reproduce

Install the plugins: skript and skript-reflect; and make a skript with this code:

on left click:
	set {_target} to player's targeted entity
	if {_target} is set:
		set {_d} to player's location.distance({_target}'s location)
		send "%{_d}%" to the player

Then summon a mob (with NoAI so that it doesn't move) and put blocks behind it.
If you aim the mob while you are far away from it (And mainly from those blocks) and you left click on it, a message in chat will appear saying the value of the distance between you and the mob;
When you approach just enough to get into the reach of breaking those blocks, aim the mob and one of the blocks behind it. You will notice that the messages with the distance value won't appear anymore.

### Plugin list

CustomCrafting, LibsDisguises, MythicMobs, ProtocolLib, SkBee, skDragon, Skellett SkQuery, skRayFall, SkUniversal, TuSke, WolfyUtilities,
Skript, skript-reflect

### Paper version

Paper 1.16.5 ; Build: #649

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Here is the class, related to the distance, which I'm having issues with:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Location.html#distance(org.bukkit.Location)

So overall: It's like if the reach necessary to break block is not letting to the org.bukkit.Location's class to detect the distance between me and the target I'm aiming to.

**Comment by electronicboy** [comment]
> You will notice that the messages with the distance value won't appear anymore

Location#distance returns the distance between two locations, nothing more, nothing less, the message not showing would have nothing to do with that method, that screams as if your code just isn't running, which is likely due to how interaction events work, I'd suggest speaking to the skript people as they may be able to help you find a better alternative or tell you what else you might need to listen to, etc
