### ISSUE TITLE
Scoreboard/Featherboard

### ISSUE THREAD

**Issue by johnsoncui02** [PaperMC/Paper#560]
how do we disable scoreboard and broadcasting achievements? It doesn't seem like i can find that in the config to disable this feature.

**Comment by zachbr** [comment]
Disabling the broadcasting of achievements is done via the ```announce-player-achievements=true``` key in ```server.properties```.

As for the scoreboard, that is only used if you have explicitly set it up, or you are using plugins that set it up for you. As such, that is up to you. There is no master toggle in any server to completely block all scoreboard access, nor will there be.

**Comment by johnsoncui02** [comment]
i mean can't you just add an option in the config to scoreboard: disabled

**Comment by zachbr** [comment]
No.

Either remove the plugins that are using it or contact their authors about adding an option not to use it.
Having paper globally block all access to the server scoreboard is not going to happen.

**Comment by johnsoncui02** [comment]
excuse me, i don't think im in the right area. i'm coming from a plugin
called CubeRunner, is this the right section? That's where they directed me
to..

**Comment by zachbr** [comment]
You're either in the wrong place, or you are misinformed about the issue.
Either way, there is nothing here we can help you with.

**Comment by johnsoncui02** [comment]
appreciate it Zach, so sorry for your time wasted.
