### ISSUE TITLE
DENY Interact at block produces left-click

### ISSUE THREAD

**Issue by TheFruxz** [PaperMC/Paper#5603]
### Expected behavior

After `event.setUseInteractedBlock(DENY)` the denied the interaction, it should just deny it!

### Observed/Actual behavior

After I `event.setUseInteractedBlock(DENY)` the `PlayerInteractEvent` an other PlayerInteract got fired, that said, the player left-clicked. The client also thinked, that he left-clicked and the hand had 'shaken'.

The fired Left-Click event can be caught using an `EventHandler`

### Steps/models to reproduce

> Written in Kotlin

1 ->
```kotlin
@EventHandler
	fun onInteract(event: PlayerInteractEvent) {
		val player = event.player

		if (!player.isBuildMode) {
			event.setUseInteractedBlock(DENY)
		}
	}
```

2 ->
```kotlin
@EventHandler
	fun onInteract(event: PlayerInteractEvent) {
		val player = event.player

		if (action == LEFT_CLICK_BLOCK) {
			println("Left-Click detected!")
		}
	}
```

3 -> Right click at an block!

### Plugin list

/

### Paper version

This server is running Paper version git-Paper-652 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-634 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

An RIGHT-click on an block causes this issue!

**Comment by TheFruxz** [comment]
The form is a little bit buggy with code-uses, but everything important can be read :(

> fixed

**Comment by electronicboy** [comment]
unless the deny is explictly sending a packet to the client which causes it to do that, there is generally very little that we can do about this stuff, the client sends multiple packets which are used for the interaction events which causes these events to be fired multiple times in general

**Comment by Owen1212055** [comment]
Cannot reproduce as of 1.19.1, if you happen to be able to reproduce this please leave a comment and this can be reopened.
