### ISSUE TITLE
Block#breakNaturally doesn't use the ItemStacks Silk Touch with certain blocks

### ISSUE THREAD

**Issue by HexedHero** [PaperMC/Paper#5604]
### Expected behavior

To get the block as Silk Touch does normally when used.

### Observed/Actual behavior

Block#breakNaturally doesn't use the ItemStacks Silk Touch with certain blocks such as Snow Layer Blocks.

If you have a shovel with Silk Touch and use it on the Snow Layer, you get the Snow Layer as normal but if you use the said same tool in the Block#breakNaturally API it will not drop the Snow Layer Block as using the tool normally would.

Video: https://i.imgur.com/VZmlMUY.mp4

### Steps/models to reproduce

```JAVA
    // Right click blocks to use the silk shovel
    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void a(PlayerInteractEvent event) {
        if (event.getPlayer().isSneaking() /* Allow block placements */ || event.getAction() == null || event.getAction() != Action.RIGHT_CLICK_BLOCK) { return; };
        final ItemStack shovel = new ItemStack(Material.DIAMOND_SHOVEL);
        final ItemMeta meta = shovel.getItemMeta();
        meta.addEnchant(Enchantment.SILK_TOUCH, 1, true);
        shovel.setItemMeta(meta);
        event.getClickedBlock().breakNaturally(shovel);
    }

    // Type "GIVE" to get the same tool
    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void b(PlayerChatEvent event) {
        if (event.getMessage().equalsIgnoreCase("GIVE")) {
            final ItemStack shovel = new ItemStack(Material.DIAMOND_SHOVEL);
            final ItemMeta meta = shovel.getItemMeta();
            meta.addEnchant(Enchantment.SILK_TOUCH, 1, true);
            shovel.setItemMeta(meta);
            event.getPlayer().getInventory().addItem(shovel);
        }
    }
```

### Plugin list

[02:44:44 INFO]: Plugins (1): DevTest

### Paper version

> version
[02:37:50 INFO]: Checking version, please wait...
[02:37:50 INFO]: This server is running Paper version git-Paper-655 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-642 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
i'd imagine that it's not calling into the loottables logic properly, which I'm not exactly sure is viable without passing in a player for "exact" behavior that many would expect

**Comment by electronicboy** [comment]
Then again, it calls the exact same logic, so, it should? Unless the lack of a player context is breaking this, somewhat hard to say given how joyous this loot system is to debug

**Comment by tahmid-23** [comment]
the fact that there is no player (or rather no entity, could just be entity) means that snow and chorus fruit won't drop when breakNaturally is called as they both check for the existence of an entity breaking them
so I don't know to what extent this is "intended"

**Comment by Machine-Maker** [comment]
A LootContext API would be pretty nice in a bunch of situations, this one included. Where you could construct exactly what was used by the server for getting drops.

**Comment by electronicboy** [comment]
We've already got one, just needs expanding

**Comment by Machine-Maker** [comment]
Looking at the loot table for snow layers (`data/minecraft/loot_tables/blocks/snow.json`), it looks like it requires an entity to drop anything. So this issue is probably `works-as-intended`. If new API needs to be added for something like this, open a new issue.
