### ISSUE TITLE
Zombified piglins keeps anger on player after death or relog of said player.

### ISSUE THREAD

**Issue by TraceLTRC** [PaperMC/Paper#5613]
### Expected behavior

After death, relog, or moving away from the zombified piglin by as much as 100 blocks, anger for the zombified piglin should reset (if forgiveDeadPlayers is enabled).

### Observed/Actual behavior

Zombified piglins continue to be aggressive towards the player, even after relogging, dying, or moving away.

### Steps/models to reproduce

1. Create a platform for zombified piglins to spawn with the size of 72x72, and a place for a player to stand on in the center of the platform without being damaged by the zombified piglin. (for convenience sake, you can use this [worldedit schematic](https://gofile.io/d/M4otsu)).
2. Create multiple 1x1 floating blocks on the outer edge of the platform and spawn a named zombified piglin in said floating blocks.
3. On the center of the platform where the player can stand, place a respawn anchor.
4. Use the respawn anchor and hit any of the naturally spawned zombified piglin.
5. Relog, die, or TP away.

### Plugin list

EssentialsX, WorldEdit, Vault.

### Paper version

This server is running Paper version git-Paper-662 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-629 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Paper.

### Other

When getting killed, minecraft server vanilla also has this issue, however the anger would slowly decay and return to passive after a couple of minutes.

**Comment by Machine-Maker** [comment]
Zombified piglins only forgive anger to dead players if the `forgiveDeadPlayers` gamerule is true. Is that the case here?

Also their forgiveness timer only ticks down if they are in loaded chunks, so just tp'ing far away and coming back wont work, neither will relogging afaik.

**Comment by TraceLTRC** [comment]
> Zombified piglins only forgive anger to dead players if the `forgiveDeadPlayers` gamerule is true. Is that the case here?
> 
> Also their forgiveness timer only ticks down if they are in loaded chunks, so just tp'ing far away and coming back wont work, neither will relogging afaik.

Yes. I have not touched gamerules at all and forgiveDeadPlayers was set to true. Everything is in default config setup. 

Unloaded chunks are also not the cause as having a second player stand on the platform would result in the same thing.

Seems like this happens because of the nametagged zombified piglins. They keep their anger no matter what.

**Comment by Machine-Maker** [comment]
I just tested this and couldn't replicate it,
* gamerule `forgiveDeadPlayers` set to true
* summoned zombified piglin (with and without nametag in different tests)
* attacked them
* let them kill me
* respawned nearby
* not angry anymore.

**Comment by e-im** [comment]
Thanks a lot for the schematic, made replicating your procedure much easier. However unfortunately while the behaviour as a whole seems weird, I was also unable to replicate a difference from vanilla as to when the piglins anger went away. The timer for the named piglins seems to act the same as the unnamed ones as well. I have a feeling that Machine-Maker was on the right track with his initial guess in that the piglins were out of range, which will cause this behaviour.
