### ISSUE TITLE
sugesstion: add an option in paper.yml to turn of the excessive velocity check

### ISSUE THREAD

**Issue by DominicDV** [PaperMC/Paper#562]
as with the latest paperclip version, I get stacktrackes of too high velocity in my console because of a 
"hub" plugin which catapults players in the direction they are looking at.
https://www.spigotmc.org/resources/launch-pads.328/
This error occurs somewhere above speed 6. 

more detail:
https://hub.spigotmc.org/jira/browse/SPIGOT-2383

**Comment by zachbr** [comment]
Probably not going to happen.

For more information about why it exists, and a conversation about raising the threshold at which we fire a warning, see GH-536.

We may raise the warning threshold at some point, it is unlikely it will ever be exposed as a toggle.
