### ISSUE TITLE
Adventure BossBar does not update for player when changing flags

### ISSUE THREAD

**Issue by aecsocket** [PaperMC/Paper#5623]
### Expected behavior

When changing a `BossBar`'s flags using `.addFlag` and `.removeFlag`, the viewing player(s) should see the update. This seems to work if e.g. changing the title, but for flags it does not seem to work (have not tested with other things like progress).

### Observed/Actual behavior

The boss bar does not update for the viewing player(s).

### Steps/models to reproduce

In the video, the action bar shows if there should be fog, and if the boss bar has the `CREATE_WORLD_FOG` flag. This code runs every tick:
```java
// BossBar bar = the bar that is shown to the player
                player.sendActionBar(Component.text("Should have fog: " + weather.fog() + " / Boss bar has fog flag: " + bar.hasFlag(BossBar.Flag.CREATE_WORLD_FOG)));
                if (weather.fog() && !bar.hasFlag(BossBar.Flag.CREATE_WORLD_FOG)) {
                    bar.addFlag(BossBar.Flag.CREATE_WORLD_FOG);
                    //player.hideBossBar(bar);
                    //player.showBossBar(bar);
                } else if (!weather.fog() && bar.hasFlag(BossBar.Flag.CREATE_WORLD_FOG)) {
                    bar.removeFlag(BossBar.Flag.CREATE_WORLD_FOG);
                    //player.hideBossBar(bar);
                    //player.showBossBar(bar);
                }
```

The status of these changes when I run a command, however the actual fog does not appear (hence boss bar is not updated). If the commented lines are uncommented, this works fine. You can also see in the video that the title of the boss bar updates fine, just the flags.

https://user-images.githubusercontent.com/43144841/118032691-dd3d9e00-b35f-11eb-8f65-032dd891aafc.mp4

### Plugin list

LuckPerms, MiniMOTD, Natura (my above plugin that is controlling the boss bar), ProtocolLib, spark

### Paper version

[21:17:22 INFO]: This server is running Paper version git-Paper-669 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-638 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Paper.

**Comment by kashike** [comment]
#6076
