### ISSUE TITLE
Include Recommended-Version in the jar manifest

### ISSUE THREAD

**Issue by TrixterTheTux** [PaperMC/Paper#5630]
### Is your feature request related to a problem?

With the newest minecraft versions moving towards more newer java versions, and the migration being encouraged through large console warnings, it is rather hard to allow users to switch between multiple different jars without impacting user experience due to possibly running the wrong java version. For example, the 1.16.5 builds recommend running Java 16, but are built with Java 8. This issue aims to solve this problem (in the future releases) by allowing indicating the recommended version for automated tools (e.g. game panels automatically choosing the wanted version).

### Describe the solution you'd like.

The downloaded jar's manifest file (meta-inf/manifest.mf) could include the field `Recommended-Version`, or alternatively the patcher jar's patch file (patch.properties) could include the field `recommended-jvm-version` (or similar) if former isn't possible, which would contain the major version number of the recommended java version for the jar. This allows any automated tool to check if it's present and automatically choose the recommended java version over having to rely on either the user choosing the correct version or using the minimum required version included in the java classes bytecode (leading to possible warning messages in console).

### Describe alternatives you've considered.

You can parse the target java version from the java classes bytecode (https://en.wikipedia.org/wiki/Java_class_file#General_layout), but this only provides the minimum required version. Alternatively, you could either parse the patch file (which gets complicated) to detect what the recommended version is, or manually maintaining a list of which minecraft versions should use which java version.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by e-im** [comment]
Now included as part of the `version.json` file, along with other information. Matches the behaviour of the vanilla server.
