### ISSUE TITLE
IPv6 working on Linux but not on FreeBSD

### ISSUE THREAD

**Issue by imp1sh** [PaperMC/Paper#5637]
### Expected behavior

I expect the same behaviour on FreeBSD as on Linux.

### Observed/Actual behavior

I set the server property like this:
`server-ip=`

On Linux I get this:
```
mcrx1:~/mc$ ss -ltpn|grep 25565
LISTEN 0      4096               *:25565            *:*    users:(("java",pid=14206,fd=24))
```

On FreeBSD I get this:
```
[jochen@mcofden1 ~/mc]$ sockstat -l|grep 25565
jochen   java       166   23 tcp4   *:25565               *:*
```

As you can see on FreeBSD it will only listen on IPv4 only.  I tried also the following value but then paper won't start at all

`server-ip=[::]
`

### Steps/models to reproduce

- Install Paper without any modifictaions to the server.properties in FreeBSD 12.2
- Start Server
- See that it will only listen on IPv4

As IPv6 is mandatory I consider this a bug, not a feature request.
https://datatracker.ietf.org/doc/html/rfc6540

### Plugin list

none

### Paper version

1.16.5

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
Assigning this to resident BSDer @zachbr.
This is rather low priority.

**Comment by MiniDigger** [comment]
does this work in vanilla? if not, that should be prolly be reported to mojang too
I know that mojang forced ipv4 for quite some time (thankfully there is no law that ipv6 is mandatory :P), but iirc that decision was reversed years ago
quick search on mojira doesn't list current issues with ipv6 and freebsd, so please try using a vanilla server and report to mojang if needed, so that they are aware of this issue too.

**Comment by imp1sh** [comment]
It also fails to work in vanilla so I will reach out to mojang, thank you.
This RFC of course is no law, but when it comes to IT, RFCs are very close to what laws represent.
Edit:
just created the mojang ticket: https://bugs.mojang.com/browse/MC-225661

**Comment by e-im** [comment]
Reproducible on 1.17, however, closing as wontfix as this is an underlying issue and not something paper can really fix itself, as well as a general lack of interest due to this only impacting a very very very small minority of users.
