### ISSUE TITLE
Same team monster attack the player.

### ISSUE THREAD

**Issue by sheng-ri** [PaperMC/Paper#5639]
### Expected behavior

The monster didn't attack the player WHEN player and monster in a team.

### Observed/Actual behavior

The monster attack the player.

### Steps/models to reproduce

1. Type /summon minecraft:skeleton ~ ~ ~ {Tags:["1"]}.  (Make sure skeleton around you)
2. Type /team add normal
3. Type /team join normal {Your Name}
4. Type /team join normal @e[tag=1]
5. Attack the skeleton or gamemode survival.

### Plugin list

None

### Paper version

> ver
[01:43:35 INFO]: Checking version, please wait...
[01:43:36 INFO]: This server is running Paper version git-Paper-675 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-629 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
Please share your `paper.yml` file as well.

**Comment by sheng-ri** [comment]
https://paste.ubuntu.com/p/Vytf2FkRjw/

**Comment by electronicboy** [comment]
`allow-non-player-entities-on-scoreboards` set that to true
