### ISSUE TITLE
BeaconActivatedEvent not firing in some cases

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [PaperMC/Paper#5644]
### Expected behavior

I expect to see BeaconActivatedEvent firing on every beacon activation circumstandes

### Observed/Actual behavior

BeaconActivatedEvent is not firing if ex. 50 blocks above beacon there is ex. slab that lets beacon through.

### Steps/models to reproduce

1. Place beacon pyramide.
2. Place slab ex. 100 above beacon
3. Palce beacon under 100 blocks under slab
4. BeaconActivatedEvent is not firing

### Plugin list

Only mine looking for BeaconActivatedEvent

### Paper version

16.05 01:57:56 [Server] INFO Checking version, please wait...
16.05 01:57:57 [Server] INFO This server is running Paper version git-Paper-677 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
16.05 01:57:57 [Server] INFO You are 4 version(s) behind
16.05 01:57:57 [Server] INFO Previous version: git-Paper-650 (MC: 1.16.5)

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
Yeah, you are absolutely correct. The activate event seems to not be called if there is a slab ~80 blocks above the beacon, but will be called with a slab just a few blocks above the beacon.

**Comment by Drc-DEV** [comment]
The whole implementation is rushed and breaks fawe when pasting schematics which contain beacons async. This should have been made an optional feature, or not implemented at all.

**Comment by kennytv** [comment]
That has nothing to do with a "rushed implementation", that's on fawe being fawe or the way you use it.
