### ISSUE TITLE
Riding a horse up atleast 5 stairs glitches the horse

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#565]
I was riding my horse up 6 staircases than suddenly it kept glitching

Build:1019

**Comment by zachbr** [comment]
Seems like the server can think the vehicle is moving wrongly when quickly moving upwards. Increase spigot's ```moved-wrongly-threshold``` in ```spigot.yml```. It's hard to recommend exactly how high, the highest I saw locally was ```0.1025``` but depending on server TPS lag and network latency, that value could need to be ```0.1525``` or even higher. You'll have to experiment.

If we get more reports of this issue we can look into raising that value by default or re-examining how the server detects these issues.
