### ISSUE TITLE
Custom "spawn-limits" for specified worlds if "per-player-mob-spawns": true

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#5656]
### Is your feature request related to a problem?

My current settings is:

bukkit.yml
```
spawn-limits:
  water-ambient: 10
  monsters: 50
  animals: 20
  water-animals: 15
  ambient: 10
```
paper.yml
```
world-settings:
  default:
    per-player-mob-spawns: true
```

In overworld everything with mob count is fine, but in The End there are too few mobs (~ 60, for 3-5 players in one place it's REALLY not enough to be killed by mob). Before, when `per-player-mob-spawns`  was = `false`, there are at least one mob in almost every chunk and that's exactly what I needed. But now I can't achieve this.

### Describe the solution you'd like.

Add another `spawn-limits` section to `paper.yml`, name it like `spawn-limits-per-player` and use values from it in worlds with `per-player-mob-spawns`: `true`; otherwise use `spawn-limits` from `bukkit.yml`

### Describe alternatives you've considered.

I don't know. Currently my The End world is too easy and I don't know what I can do to change this except reverting `world-settings.default.spawn-limits-per-player` to `false`.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by e-im** [comment]
I don't see why this would need to be tied to per player mob spawns or how linking the two would really add anything, would likely be better to just have per world spawn-limits.

**Comment by molor** [comment]
> just have per world spawn-limits

If I revert `world-settings.default.spawn-limits-per-player` to `false` and put back old `spawn-limits`, when one player plays in overworld, there are too much mobs. BUT if I use lower limits, >5 online players won't see >1-3 mobs at all... :c

**Comment by Machine-Maker** [comment]
#4837 adds per-world spawn limits (if this is just a feature request for per-world spawn limits, its a duplicate of #2910)

**Comment by e-im** [comment]
Duplicate of #2910 - thanks for pointing that out.

And yes, this would be. Molor, you can achieve the same outcome whether it is tied to per-player-mob-spawns or not, as both of these are configured per world.
