### ISSUE TITLE
Server crashed with the latest buildse - craftbook and others

### ISSUE THREAD

**Issue by CloudeLecaw** [PaperMC/Paper#5659]
### Stack trace

https://paste.gg/p/anonymous/9dafdf82438344a7a44aee2247421c97

### Plugin list

Plugins (80): AcceptTheRules-Beta (5.3), AdvancedAchievements (7.0.6), AdvancedModreq (6.1.3), ajParkour (2.12.0), ArmorStandEditor (1.16-25), BlockParticles (1.11.1-RELEASE), BlueMap (1.4.2), BuyRentRegion (7.7.3), ccRides (1.6.4), Celeste (1.51), ChestRestock (2.5.0), Citizens (2.0.27-SNAPSHOT (build 2314)), CMI (8.8.4.2), CMIEInjector (1.0.2.3), CMILib (1.0.0.2), CompassNavigator (1.6.0), ControllerBlockReloaded (2.1.0), CraftBook (3.10.4-SNAPSHOT;4700-609e3e4), DangerousCaves (2.2.14-SNAPSHOT;24), DeluxeMenus (1.13.3-Release), DiscordSRV (1.23.0-SNAPSHOT), DropEdit2 (1.1.37-SNAPSHOT), dynmap (3.2-SNAPSHOT-458), EasyBackup (3.3.5), EasyCarts (2.1), EntityTrackerFixer (1.3.3), EpicBackpacks (1.3.2), EvenMoreFish (1.2.0.2), FastLeafDecay (1.0), FishinRoulette (1.9.1), GadgetsMenu (4.6.9), GameBox (3.3.1), GCoreLegacy (7.16.3), GoldRush (1.7.0), GSlotMachine (2.4.1), HeadDatabase (4.13.6), HopperFilter (1.0.5), Hunger-Management (1.0.1), Images (2.1.7), Jobs (4.17.2), Lift (71), LogBlock (1.16.5.2-SNAPSHOT (build #130)), LoneLibs (1.0.9), Lottery (1.4.3), MobFarmManager (1.5.9.1), MobTransporter (2.4), MoneyPouch (3.5), Multiverse-Core (4.2.3-SNAPSHOT-b842), NoteBlockAPI (1.6.2-SNAPSHOT), OneTimeItem (6.9.1), OpenAudioMc (6.5.2), PacketLimiter (1.0.0), PermissionsEx (1.23.5), PermissionTimer (6.7.1), PerWorldInventory (2.3.2), PetDragon (1.4.2), PexTabCompleter (1.3.0), PlaceholderAPI (2.10.10-DEV-123), PlayerBTH (2.2.4), PlugMan (2.2.2), ProtocolLib (4.6.1-SNAPSHOT-b499), RainbowsPro (1.1.4), RedProtect (7.7.3), RedstoneProximitySensor (2.5.2), RHSignItem (1.15.2-1.16_R21), RPGBank (1.0.12), ServerMinimap (0.7.23), ServerTutorialPlus (1.21.5), Shopkeepers (2.12.0), Thirst (2.13.1), TranslationAPI (1.2), UltimateFireworks (3.2.4), Vault (1.7.3-b131), Vehicles (11.7), Vivecraft-Spigot-Extensions (1.16.5-r1), Votifier (3.0.0-SNAPSHOT), WorldBorder (2.1.2), WorldEdit (7.3.0-SNAPSHOT+5775-ec2fb07), Wraith (2.0.34), XWeather (1.2.3)

### Actions to reproduce (if known)

start the server in newver paperMC builds.

### Paper version

Well all after 68x?
We settet back to PaperMC 667 now - with this the server runs fine.

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

We settet back to PaperMC 667 now - with this the server runs fine.

**Comment by Machine-Maker** [comment]
If you are talking about the “ net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour.”

It’s not a crash, it’s a warning message that should be reported to the plugin author.

**Comment by Proximyst** [comment]
There's no crash here.

**Comment by CloudeLecaw** [comment]
the measses generated 2mb logs and is the reason on our server while it crashes. so we have to inform the plugins developer about this?

**Comment by electronicboy** [comment]
You have signs in the world which have invalid components, you'll wanna work out what caused that and report it to the plugin author as those signs are malformed

**Comment by CloudeLecaw** [comment]
This is what the citizenz def sais:
https://github.com/CitizensDev/Citizens2/issues/2552#event-4752353243

`This is purely and exclusively a Paper issue. Nothing can be done in Citizens to change that. Paper has to fix it.`

same to craftbook

https://github.com/EngineHub/CraftBook/issues/1267

```This does not look like an issue with CraftBook. It's just reading the sign from the world as-is using the string compatibility layer, not specifically doing anything with it. It's likely either something else has created invalid signs, or it's a bug in Paper.```

**Comment by CloudeLecaw** [comment]
> The main issue here is that the signs are being validated when they are read by plugins. So, therefore, this creates error spam that blames whatever plugin is the first to load the broken sign even if that plugin did not create the broken sign. 
> 
> There's nothing plugin developers can do about this. IMO the ideal solution would be for this warning to only be produced when a sign is set with invalid data, not read. As plugins can't tell if a sign would cause an error until after reading it, only Paper can do anything about this.

_Originally posted by @me4502 in https://github.com/EngineHub/CraftBook/issues/1267#issuecomment-842037643_

**Comment by electronicboy** [comment]
warnings already disabled, but, that issue is what I already highlighted above

**Comment by CloudeLecaw** [comment]
We notices that this affcts all our sign on our server and we have 100's of signs.
It cant ansolution to have to place all signs on the server aggain, it was working normal before.
Iven if we would replace all of the signs this is no garantee that this issue does Not Happen aggain..
It cant be that all signs broke and produce this massive spam now.
The reason why the sever might crash is because nof this massive spam because every sign is markd in Log with this error trace. And it affects all signs if it uses placeholders or not. So this must be a paper reason.
With paper 670 all is fine.  We cant tell you what update until 686 might broke it.

**Comment by electronicboy** [comment]
the update never changed anything bar adding a message to alert for such broken data

**Comment by CloudeLecaw** [comment]
But there never was anything broken...
or saying that all signs have broken data now?
may of them just contain words or a just ICs connected to commands of other plugins.

there is no broken thing
so this massive spam is wrong

**Comment by electronicboy** [comment]
just because it appears to be working right now does not mean that you're not using mangled data, once again, the update was just there to inform you that you had such mangled data so that you could aim to migrate away from that before it actually caused issues, you have been warned that you have something creating bad data, and now you need to look at getting it resolved before it creates further issues.

Once again, THIS UPDATE DID NOT CHANGE ANYTHING, it warned you about data that is considered invalid and WILL break in the future.
