### ISSUE TITLE
Server geting lag dnt knw what is reason please help

### ISSUE THREAD

**Issue by MoGGaming** [PaperMC/Paper#5660]
### Stack trace

```
https://paste.shockbyte.com/oqivosehujatulafavey
```

### Plugin list

Companions
Discordsrv
EconomyshopGUI
EssentialsX
essentialsxChat
FastAsyncWorldEdit
Floodgate
Geyser
griefPrvention
luckperms
Openlogin
TAB
Vault

### Actions to reproduce (if known)

Server Getting lag, 5TPS, Players Getting High MS

### Paper version

This server is running Paper version git-Paper-686 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-684 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
Well, the lots of warnings you are getting look to be from geyser somehow putting legacy color codes inside an adventure component. (If that’s what your issue is)

**Comment by electronicboy** [comment]
geyser is reading packets, in part looks like the adventure check is acting excessive, only checks for a section symbol vs actual legacy colors

**Comment by Proximyst** [comment]
Report issue to EconomyShopGUI. They are using legacy colour codes in components (e.g. `Component.text("§cCool")` instead of `Component.text().content("Cool").color(NamedTextColor.RED)`).

**Comment by electronicboy** [comment]
They're calling the legacy inventory methods

**Comment by Proximyst** [comment]
Didn't catch that, sorry. Assigning to kashike & Adventure project.

**Comment by MoGGaming** [comment]
> Report issue to EconomyShopGUI. They are using legacy colour codes in components (e.g. `Component.text("§cCool")` instead of `Component.text().content("Cool").color(NamedTextColor.RED)`).

Removed EcoshopGUI plugin but still having spam in consol

**Comment by electronicboy** [comment]
warning has been disabled but this is basically a sign that you have data on your server which is going to break in the future

**Comment by MoGGaming** [comment]
> warning has been disabled but this is basically a sign that you have data on your server which is going to break in the future

how to disable data on ?

**Comment by electronicboy** [comment]
one issue was a bug, and shouldn't have triggered, some others where due to other things creating bad data which you'll have to figure out through deductive reasoning, e.g. the one from geyser for reading the title will be whatever you have sending title messages is creating improper data
