### ISSUE TITLE
Suggestion to enhance the message for missing plugin dependencies

### ISSUE THREAD

**Issue by josephjthomas** [PaperMC/Paper#5666]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like.

If you have a plugin with more than 1 dependency and none of the required dependencies are installed on the server, Paper (Bukkit like behavior) throws a message saying that you should "download and install xy dependency to run this plugin".
This message only takes one plugin into consideration, descending from the first to last. So if your plugin depends on pluginA and pluginB, the message notifies you to install pluginA but completely ignores pluginB until you reboot the server and trigger the event again.
I would like to see an enhancement where the message notifies you of all hard dependencies and not one only, this can be very tedious if a plugin has several dependencies or you are not sure which dependencies are needed.
PluginDescriptionFile#getDepend() does return a full list of all dependencies, I am not too sure why this wasn't considered when adding to spigot.

### Describe alternatives you've considered.

None

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Machine-Maker** [comment]
I think the workaround most people use nowadays, is to just not add hard dependencies, make them only soft ones and do the checking yourself in onEnable or smth, but that doesnt take away from this feature request, is just a comment on a solution.

**Comment by josephjthomas** [comment]
So it seems. I kinda tried to avoid that because that's what the depend scope is for, I thought.

**Comment by josephjthomas** [comment]
Tested on Paper 710, this does not work. It lists the first dependency only, still.

**Comment by electronicboy** [comment]
logs? info?

**Comment by jpenilla** [comment]
can confirm 
```
org.bukkit.plugin.UnknownDependencyException: Unknown dependency Dep1. Please download and install Dep1 to run this plugin.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:284) ~[patched_1.16.5.jar:git-Paper-710]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-710]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-710]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1068) ~[patched_1.16.5.jar:git-Paper-710]
```

**Comment by josephjthomas** [comment]
Logs: https://paste.gg/p/anonymous/56cd292a77764590b2c746d8bc349857
plugin.yml:
```yml
name: DependTest
version: 1.0.0
main: com.jthomas.dependtest.DependTest
depend: ["pluginA", "pluginB"]
```
Edit: Someone was faster than me

**Comment by MiniDigger** [comment]
@Machine-Maker could you take another look at this?

**Comment by kennytv** [comment]
The same treatment has to be given to the SimplePluginLoader (or whatever it was called)

**Comment by Machine-Maker** [comment]
Oh, apparently that check is in more than one place. Looks like jmp got it.
