### ISSUE TITLE
Invisible blocks

### ISSUE THREAD

**Issue by Nottoknow2** [PaperMC/Paper#5667]
### Expected behavior

To see the block when its broken

### Observed/Actual behavior

Sometimes when i break a block its invisible

### Steps/models to reproduce

Mine a couple of blocks then one is invisible

### Plugin list

Essentials and essentials chat (failed to start)

### Paper version

[git.txt](https://github.com/PaperMC/Paper/files/6497327/git.txt)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

[video.zip](https://github.com/PaperMC/Paper/files/6497332/video.zip)
video

**Comment by e-im** [comment]
What client are you using, and would you be able to try on the vanilla client?

**Comment by Nottoknow2** [comment]
The normal Minecraft launcher and fabric

**Comment by e-im** [comment]
Would you be able to try on the vanilla client without any mods?

**Comment by Nottoknow2** [comment]
Ok I will today

**Comment by Nottoknow2** [comment]
Ok I forgot about this but it's was windows 10 on my end because my server network was cutting out but is has been fixed since moving to Linux
