### ISSUE TITLE
WorldEdit gets 0 entities from unloaded chunks

### ISSUE THREAD

**Issue by ArtNRG** [PaperMC/Paper#5669]
### Expected behavior

Copy a selected area and get affected entities from there (20 entities affected)

### Observed/Actual behavior

0 entities affected

### Steps/models to reproduce

1. Place some entities in a world, remember its coordinates
2. Leave the server or teleport to other world, the chunks with the entities must be unloaded
3. Type the commands in the server console:
/world world_name_with_entities
/pos1 7743,1,-9891 (change coordinates to fit your area)
/pos2 7768,255,-9878 (change coordinates to fit your area)
/copy -e

### Plugin list

ChatControlRed, CMI, CMILib, GriefPrevention, GriefPreventionUtilities, LuckPerms, Multiverse-Core, NoPhysics, PlaceholderAPI, ProtocolLib, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard

### Paper version

Paper-694 (MC: 1.16.5)
also tried Paper-348 (MC: 1.15.2)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I talked with WorldEdit dev's
> octylFractal
> wonder if there's some sort of paper optimization there
> wizjany
> i mean we definitely load the chunks to copy the blocks...
> if somehow the entities aren't there without a player nearby that's a server issue :P
> octylFractal
> yea, but maybe paper delays loading the entities somehow until a player is close
> you would have to ask paper about it
> wizjany
> we use bukkit api for entity gets too so it's not even like we're accessing the wrong thing in nms or something

**Comment by SirYwell** [comment]
I experienced that before but hadn't the time to look into it. But from what I've seen, running the copy command multiple times will get you more entities. As I was only using it via API, I just added a line:
`region.getChunks().forEach(chunk -> extent.getBlock(BlockVector3.at(chunk.getX() << 4, 0, chunk.getZ() << 4)));` (WorldEdit `Region` and `Extent`). That worked well in my case so I didn't bother with it anymore.

**Comment by kristibektashi** [comment]
If this is a WorldEdit bug shouldn't you report it to WorldEdit?

**Comment by Owen1212055** [comment]
There was a change that made entities independently from chunks, and I'm guessing that this is worldedit not properly accounting for that at the time, and judging that there has not been any more updates on this issue I am guessing that worldedit has since fixed this as well.

However, if that is not the case and they are using the event and still are unable to retrieve entities like this please feel free to comment and this can be reopened.
