### ISSUE TITLE
Error with adventure IChatBaseComponent's being null

### ISSUE THREAD

**Issue by WillFP** [PaperMC/Paper#5670]
### Expected behavior

https://github.com/Auxilor/eco/blob/a5b5bc6b46915786ca9db8425444587509a6d2f1/eco-core/core-nms/v1_16_R3/src/main/java/com/willfp/eco/proxy/v1_16_R3/ChatComponent.java

This code iterates over an IChatBaseComponent. In vanilla spigot (or forks of paper that haven't yet updated to adventure, such as purpur), no errors are produced. 

### Observed/Actual behavior

However, with adventure, either some iterated components are null, or the siblings of those components are also null.

This produces this stacktrace: https://pastebin.com/rFMBMHPZ

### Steps/models to reproduce

According to the user that reported the bug: 'it happens almost every time a message/thing in chat is sent'

### Plugin list

eco / ecoenchants are the only plugins that would be modifying IChatBaseComponents
Source code for those are available on my github.

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Phoenix616** [comment]
As far as I can tell this is due to AdventureComponent#getSiblings not checking if deepConverted returns null which can be the case if it's a null component. In this case that null component is provided by the fail-to-enter-bed message from the PlayerBedFailEnterEvent which is nullable.
