### ISSUE TITLE
Provide full release dependencies or at least retain snapshot artifacts for longer periods of time

### ISSUE THREAD

**Issue by A248** [PaperMC/Paper#5676]
### Is your feature request related to a problem?

Paper only publishes SNAPSHOT versions of the API. Depending on SNAPSHOTs works fine in most cases, but sometimes one may want to improve the stability of a build by reducing dependence on the instability of SNAPSHOTs.

Using a SNAPSHOT dependency is potentially unstable, and can lead to a build succeeding one day and failing the next. Many people are not troubled by this and use SNAPSHOTs just fine. For others build stability is somewhat more important. It's mostly a matter of preference.

Full release dependencies, unlike SNAPSHOTs, do not change, and thus imply a much greater level of stability.

In the absence of a full release, timestamped snapshots are an infrequently used feature of Maven. Developers can already use timestamped snapshots with Paper, by changing `1.16.5-R0.1-SNAPSHOT` to something like `1.16.5-R0.1-20210518.163810-280`. However, there is a problem with timestamped snapshots, described further below.

### Describe the solution you'd like.

Two solutions exist. The first is preferable:
1. Publish stable release versions of the API, i.e. without the -SNAPSHOT
2. Retain older SNAPSHOT versions in the nexus repository for a much longer period of time (possibly indefinitely)

### Describe alternatives you've considered.

Using timestamped snapshots in their current state works to an extent. However, the deletion of old SNAPSHOT versions from the nexus repository makes this solution unusable.

Old SNAPSHOTs are periodically deleted from the repository. For example, `1.16.5-R0.1-20210506.234042-225`, from May 6 - only 12 days ago - was recently deleted. This makes timestamped snapshots arguably less stable than simple SNAPSHOTs.

At the time of writing this, 226 is the build number of the oldest snapshot and 280 is the build number of the latest snapshot.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

If release dependencies are published, that would be another reason to help convince developers to depend on the paper-api instead of the spigot-api.

**Comment by electronicboy** [comment]
Paper, Spigot, Bukkit, and the ecosystem as a whole has no release cycle, so release builds is practically a non-starter outside of flip a coin "do we pin it and force everybody to update their poms"

**Comment by A248** [comment]
Release versions don't necessarily have to replace snapshots. They're mutually compatible.

> the ecosystem as a whole has no release cycle

I respectfully disagree. There's a release cycle for Paper; it just takes the form of snapshots and quick development. Release versions can provide a measure of stability for API consumers.

Moreover, Velocity, Adventure, and even Bungee provide full releases. The latter two even publish to Maven Central.
I understand Paper may not have done this before, but I don't see any downsides besides the additional work required to deploy full releases.

@mbax Would you like to voice any disagreements you have with this suggestion? I honestly don't see any problems with it.

**Comment by electronicboy** [comment]
publishing releases means getting into a version cycle which is hard to do when there is no release cycle
"we just push builds when we can" is not a release cycle, there is no promises as to when features, API additions, etc, will arrive in there, and so it's pretty hard to push releases when practically every release is gonna be outdated for those who want newer APIs

It's much easier to publish releases when you're in full control of the versioning cycle, but, we're not, and pushing arbitrary R bumps onto people which represent very little as for "we decided to draw a line in the sand here" feels very eer

Only velocity and adventure actually have some form of sane release system in which they use semver (iirc), bungees is basically just "flip a coin", hence why we don't really follow them there as they're not doing anything of note in regards to this

**Comment by Prof-Bloodstone** [comment]
We have discussed it internally and it's not feasible for use to do it. Accidental API breaks are fixed often within minutes, sometimes within hours of reporting. Unless there's some other, specific situation you had in mind? I'd argue that temporarily switching it to older specific snapshot version will require less work from you than switching snapshot version every so often, even if we were to extend the time they are stored for.
If you are really concerned about it, you can create own maven repo proxy, which will also protect against downtime of Paper maven repo.

**Comment by DenWav** [comment]
Sorry, little bit of miscommunication here.

We don't really want to do build-numbered releases or anything like that - not yet anyways. We might come back and look into something like that again some day, just not right now.

We can disable the cleaning of snapshot artifacts for now. We may end up with a retention period of 3 years or something like that, depending on growth. Hopefully that will be good enough for your use case?

**Comment by A248** [comment]
Okay, that's understandable. I quite appreciate the discussion and consideration, so thanks.

Retaining snapshots for 3 years is plenty of time. Maybe too much, even. Something like 1-2 years would do fine too. I don't expect to be depending on a 1-year-old API artifact anytime soon. I wouldn't imagine others would need to either.

**Comment by A248** [comment]
Sorry to bump an old thread, but it seems that the settings on the Nexus repository haven't changed. Snapshots are still deleted rather quickly.

As of writing this, the oldest 1.16.5 artifact is build 352, from June 8: https://papermc.io/repo/#browse/browse:maven-public

Some background / motivation: I wanted to test against a version of 1.16.5 which doesn't yet have the LibraryLoader "feature." The implementation of such feature is quite awkward with lots of code in constructors – at best, it adds log spam to my tests, and at worst, breaks them. However, I need an artifact with adventure API integration, so that rules out 1.16.4.

**Comment by electronicboy** [comment]
I've bumped up the timer to 3 years, I thought somebody had already tweaked the settings but nexus makes stuff fun so maybe they missed it or something
