### ISSUE TITLE
Boats can be placed through any entity.

### ISSUE THREAD

**Issue by PABLORAGNIzc** [PaperMC/Paper#5677]
### Expected behavior

You should not be able to place boats through entities, otherwise you could place them in protected areas. For example, in worldguard regions. I think it is a bug because in previous versions of paper it did not happen.

### Observed/Actual behavior

Boats can be placed through entities.

You can put boats through entities, sometimes you can also place boats in areas where you should not, without the need for entities to be involved.

### Steps/models to reproduce

https://www.youtube.com/watch?v=KjXyOVqkZa8

### Plugin list

![image](https://user-images.githubusercontent.com/84411800/118716890-bcf85e00-b7fb-11eb-9e7a-b019127216c6.png)

### Paper version

 This server is running Paper version git-Paper-703 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-700 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This bug does not happen with old paper 670 (We have only tried it higher than paper 700). Nor does it happen with spigot.

**Comment by Owen1212055** [comment]
Probably caused by my patch here, https://github.com/PaperMC/Paper/commit/2c5f8085ea8d3edfecc53f63b9fa504fe61422be 

That is very interesting, so that is why that interaction event was there then. Perhaps this could be extended on, but it seems to break when interacting on entities as clicking on entities usually doesn't trigger an interaction event.

**Comment by Owen1212055** [comment]
![image](https://user-images.githubusercontent.com/23108066/118717906-a4d11080-b7f4-11eb-8adf-1e47fd1f4e9d.png)
Checking again however, this should only occur when looking at a block?

**Comment by DarkEyeDragon** [comment]
Can confirm this.
![image](https://user-images.githubusercontent.com/6131099/118812632-99422000-b8ae-11eb-968b-e57e6ae5532c.png)
This server is running Paper version git-Paper-704 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-575 (MC: 1.16.5)

Seems like the easiest way is to look through the entity at a block within reach, that completely bypasses the protection.

**Comment by PABLORAGNIzc** [comment]
Good Morning. I just tried to do it with the new 704 paper and the bug is still happening. I am using paper 675 to avoid this bug, since in that version it does not happen.
________________________________
De: Joshua ***@***.***>
Enviado: miércoles, 19 de mayo de 2021 09:31
Para: PaperMC/Paper ***@***.***>
Cc: Pablo ***@***.***>; Author ***@***.***>
Asunto: Re: [PaperMC/Paper] Boats can be placed through any entity. (#5677)


Can confirm this.
[image]<https://user-images.githubusercontent.com/6131099/118812632-99422000-b8ae-11eb-968b-e57e6ae5532c.png>
This server is running Paper version git-Paper-704 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-575 (MC: 1.16.5)

Seems like the easiest way is to look look through the entity at a block within reach, that completely bypasses the protection.

**Comment by kennytv** [comment]
That's not the "new" build; you have to wait for this to be published.

**Comment by PABLORAGNIzc** [comment]
I understand. Sorry for the inconvenience, I'm a little new to this yet. Thanks for your kind attention.
________________________________
De: Nassim ***@***.***>
Enviado: miércoles, 19 de mayo de 2021 09:47
Para: PaperMC/Paper ***@***.***>
Cc: Pablo ***@***.***>; Author ***@***.***>
Asunto: Re: [PaperMC/Paper] Boats can be placed through any entity. (#5677)


That's not the "new" build; you have to wait for this to be published.
