### ISSUE TITLE
Build #1019 : Main class doesn't extends JavaPlugin

### ISSUE THREAD

**Issue by GuillaumeVDN** [PaperMC/Paper#568]
### The problem

Someone reported me PaperSpigot can't load my plugins, which is sad :(
I don't use directly JavaPlugin for my plugins, I use an abstract class (AbstractPlugin) which extends JavaPlugin, and PaperSpigot doesn't seems to detect that.

### Stack trace

Stack trace : http://pastebin.com/sEa0Tm0Z

You can find the main class here (which extends the abstract class) :
https://github.com/PYRRH4/PyrCore/blob/master/src/be/pyrrh4/core/Core.java
And here is the abstract class (wich extends JavaPlugin) :
https://github.com/PYRRH4/PyrCore/blob/master/src/be/pyrrh4/core/AbstractPlugin.java

### Paper build

Tested on : git-Paper-1019 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
But I think the bug appears on the previous versions too.

#### Thanks for the help !

**Comment by AlfieC** [comment]
....why?

**Comment by GuillaumeVDN** [comment]
@AlfieC why "why" ?

**Comment by mikroskeem** [comment]
> Someone reported me PaperSpigot can't load my plugins, which is sad :(

Have you tested that on your own too? Or is stack trace/version information from that "someone"?

**Comment by mikroskeem** [comment]
Works with no problems on `git-Paper-"9b9a43e4" (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)` and latest version of your plugin (currently `2.0.6` from SpigotMC page)

Invalid?

**Comment by Spottedleaf** [comment]
PluginClassLoader has not been modified by Paper, and thus it will perform the same checks as Spigot.

The Javadocs for Class#asSubclass disallow the behaviour you have described.

**Comment by GuillaumeVDN** [comment]
You're right, I retested and it seems to work. It's strange, two people using the same version (PaperSpigot #1019 and PyrCore 2.0.6) have this bug. What could be the problem then ? :/

**Comment by mfnalex** [comment]
Why don't you just use JavaPlugin, if I may ask?

**Comment by GuillaumeVDN** [comment]
Many things, you can look here if you want :
https://github.com/PYRRH4/PyrCore/blob/master/src/be/pyrrh4/core/AbstractPlugin.java

**Comment by zachbr** [comment]
You can't reproduce this and you wrote the software yourself.
I think it's safe to close this. Thank you for keeping us in the loop throughout :+1:
