### ISSUE TITLE
Scoreboard Component Support

### ISSUE THREAD

**Issue by richardwhateverr** [PaperMC/Paper#5685]
### Is your feature request related to a problem?

I want Hex Colors in Scoreboards.

### Describe the solution you'd like.

Objective#getScore(Component) Support

### Describe alternatives you've considered.

Tried to use the LegacyComponentSerializer.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by kashike** [comment]
Minecraft does not support this, and so we cannot either.

**Comment by richardwhateverr** [comment]
Really Sad.

**Comment by Machine-Maker** [comment]
You can use team prefixes to achieve a similar thing to this iirc.

**Comment by richardwhateverr** [comment]
In Sidebar Scoreboards? In Tablists you can use them. How do I use a prefix in SideBar Scoreboards.

**Comment by kennytv** [comment]
https://papermc.io/javadocs/paper/1.16/org/bukkit/scoreboard/Team.html#prefix-net.kyori.adventure.text.Component- is probably what you are looking for.

**Comment by Machine-Maker** [comment]
specifically this
```java
Team moneyCounter = board.registerNewTeam("moneyCounter");
moneyCounter.addEntry(ChatColor.RED + "" + ChatColor.WHITE);
moneyCounter.setPrefix(ChatColor.GREEN + "$" + economy.getBalance(player));
obj.getScore(ChatColor.RED + "" + ChatColor.WHITE).setScore(12);
```

**Comment by richardwhateverr** [comment]
Im looking for using Hex Colors for Text in Scoreboard. Idk what Teams should help?

**Comment by Machine-Maker** [comment]
That what this is, just substitute the `setPrefix(String)` with `prefix(Component)`.

For more help, join https://discord.gg/papermc, that's a much better place to get help like this.

**Comment by richardwhateverr** [comment]
![image](https://user-images.githubusercontent.com/82941418/118853054-a45b7700-b8d3-11eb-80fd-b0a9d2eda1d9.jpeg)

I want this in the Sideboard.

**Comment by Machine-Maker** [comment]
Man, I'm not gonna spoonfeed you the exact code, look at the snippet I posted above, use the component prefix method on Team, and you can do exactly that. Create a team, add an entry that's "invisible" (by just appending two ChatColor's together or smth), set a prefix on the team with a Component, then set the score of that "invisible" entry on the objective.

**Comment by richardwhateverr** [comment]
I dont need spoonfeed. But there are not enough colors. I just only need a way how to use HexColors und Scores.

**Comment by aurorasmiles** [comment]
https://jd.adventure.kyori.net/api/4.7.0/net/kyori/adventure/text/format/TextColor.html

**Comment by ikfir** [comment]
> Minecraft does not support this, and so we cannot either.

Minecraft does support it 
![image](https://github.com/user-attachments/assets/bfb76449-b49a-4bbe-ab96-90acc4992791)

If you look at the Protocol of [Update score](https://wiki.vg/Protocol#Update_Score)
![image](https://github.com/user-attachments/assets/941eb7a2-cae1-4573-a18e-920b1f4fbd24)

You can send text component
