### ISSUE TITLE
grass not growing

### ISSUE THREAD

**Issue by PureVanillaFrance** [PaperMC/Paper#5686]
### Expected behavior

grass block with spread on dirt

### Observed/Actual behavior

grass block doesn't spread on dirt

### Steps/models to reproduce

tick rate is at 1 in paper. Put grass block next to dirt

### Plugin list

None

### Paper version

705

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by LaurenceBarnes** [comment]
do /gamerule randomTickSpeed, what does it say?

**Comment by PureVanillaFrance** [comment]
3

**Comment by PureVanillaFrance** [comment]
![image](https://user-images.githubusercontent.com/76930233/118883531-a3d3d800-b8f5-11eb-834c-cfc09482044c.png)

**Comment by e-im** [comment]
I can not reproduce this. Ensure all [conditions for spread are met](https://minecraft.fandom.com/wiki/Grass_Block#Spread) and keep in mind that it is a random process and may take time/feel like it is not happening.

**Comment by LaurenceBarnes** [comment]
For testing, you can temporarily ramp up the randomTickSpeed.

**Comment by Chew** [comment]
This has been reported many times with varying causes and results. Could be your world messed up, could be [intentional behavior](https://bugs.mojang.com/browse/MC-169772). If you can get some reliable steps we can look into it further but as it stands the issue is too vague and not well tested.

**Comment by PureVanillaFrance** [comment]
Thanks for your reply. 
I did not modify the files. It seems to happen since I switch to java 16. 
Regards

**Comment by electronicboy** [comment]
java version would have basically 0 impact on this unless they changed the behavior of the random class which I doubt, RNG is a cold, heartless... You've provided practically 0 info on what your setup is, i.e. where you're seeing the issue, your layout, etc

We're not going to waste time tryna dig into what is most likely a nature of misunderstanding how spreading works or other factors like RNG when you provide limited info
