### ISSUE TITLE
UUID when whitelisting is wrong

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5688]
### Expected behavior

when whitelisting player, it just works, correct uuid

### Observed/Actual behavior

when i do /whitelist add player, the uuid it comes up with is wrong
The uuid displayed when player tries to join is correct
Was able to take the uuid and paste it into whitelist.json manually and player was able to join
I asked for help is discord, if you want to see that conversation my username is RichardTheTurd

### Steps/models to reproduce

whitelist a player while using bungee server (it may not be because of the bungee server but I could be wrong)

### Plugin list

Plugins (11): CoreProtect, DiscordSRV, FastChunkPregenerator, GSit, Harbor, LuckPerms, OpenInv, ProtocolLib, SetHome*, SpigotPing*, SuperVanish

### Paper version

This server is running Paper version git-Paper-705 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 1 version(s) behind
Previous version: git-Paper-576 (MC: 1.16.5)****

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
Closed based on [further discussion on discord](https://canary.discord.com/channels/289587909051416579/289587909051416579/844740033629126686).
