### ISSUE TITLE
Incorrect Locale sent in PlayerJoinEvent

### ISSUE THREAD

**Issue by Wyatt-James** [PaperMC/Paper#5689]
### Expected behavior

When a Player joins, listening to PlayerJoinEvent and calling event.getPlayer().getLocale() should return their client's Locale String.

### Observed/Actual behavior

en_us is always returned until the PlayerChangeLocaleEvent is called, which comes after the PlayerJoinEvent.

In Paper, the delay is less than 1 tick but still incorrect during the PlayerJoinEvent.
In Spigot, the delay is 20 ticks.

### Steps/models to reproduce

Create a Plugin listening for a PlayerJoinEvent and check the Player's Locale String on join. It will always be en_us.

### Plugin list

Just the aforementioned testing Plugin.

### Paper version

This server is running Paper version git-Paper-706 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Using Pakkit shows that the correct Locale is indeed sent to the server on join.

**Comment by Machine-Maker** [comment]
IIRC, the locale is sent much later and so is never available in player join event, this might not be fixable. This depends on when the client sends the first settings packet, and it's just too late to be included in PlayerJoinEvent

**Comment by electronicboy** [comment]
What machine said
