### ISSUE TITLE
"System Info" not logged to latest.log

### ISSUE THREAD

**Issue by josephjthomas** [PaperMC/Paper#5692]
### Expected behavior

When starting your Paper server, the system info found here
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0018-Show-Paper-in-client-crashes-server-lists-and-Mojang.patch#L69 
should be logged to console like any other entry you observe when booting up the server.

### Observed/Actual behavior

When starting up the server, the lines are missing from the latest.log file.

### Steps/models to reproduce

Grab the latest Paper build.
Start the Server
Compare the console output with the latest.log file

### Plugin list

None

### Paper version

ver
[15:32:46 INFO]: Checking version, please wait...
[15:32:46 INFO]: This server is running Paper version git-Paper-706 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-705 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
Problem is this is done long before logging is set up. Not sure if we're interested in fixing...

**Comment by electronicboy** [comment]
Not really a bug, and pros and cons of having it dump that info when it does vs later
