### ISSUE TITLE
Zombie's eaten up my tickrates. (default spawn settings)

### ISSUE THREAD

**Issue by DaniGTA** [PaperMC/Paper#5694]
### Expected behavior

Same tickrate as any other mob

### Observed/Actual behavior

High Zombie tickrate.

### Steps/models to reproduce

Run Paper.

### Plugin list

dynmap
bluemap
fastlogin
essentials
plan
viaVersion
CoreProtect

### Paper version

git-paper-704 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

My TPS drops for no real reason. i looked at the timings and i see that the zombies are the reason here. But i dont know why. 

https://timings.aikar.co/?id=84c59a6dfbd44035b4f14e24acb1a6d6

**Comment by e-im** [comment]
The issue tracker isn't the place for this, please come by [discord.gg/papermc](https://discord.gg/papermc) for support.
