### ISSUE TITLE
lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by YoMama30** [PaperMC/Paper#5704]
### Expected behavior

There arent any problems with the first player joining but right as the second one joins, both of them get kicked out and cant join back in, or only the second one gets kicked out and cant join back in

### Observed/Actual behavior

[15:02:52 INFO]: TimoVanTimo lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

### Steps/models to reproduce

Idk how to reproduce this but it just happens in my server: play.cringynetwork.tk:25741

### Plugin list

AureliumSkills
BetterEnd
BlepFishing
BlueMap
Bookshelf
BreakingSlab
Brewery
ChairsPlus
ChestShop
ChestTerminal (SlimeFun4 Addon)
CmdSigns
CombatIndicator
CoreProtect
CraftableNetheriteEquipment
CraftableSpawners
CrazyAuctions
CrazyEnchantments
CrispyBoard
Dimensions
DyedBackpacks (SlimeFun4 Addon)
EcoPower (SlimeFun4 Addon)
ElectricSpawners (SlimeFun4 Addon)
EssentialsX
EssentialsXChat
EssentialsXSpawn
ExoticGarden (SlimeFun4 Addon)
ExtraGear (SlimeFun4 Addon)
ExtraHeads (SlimeFun4 Addon)
ExtraTools (SlimeFun4 Addon)
FastChunkPregenerator
FishingBonus
FluffyMachines (SlimeFun4 Addon)
Gaea
GgeneticChickengineering
GoldenCrates
GoldenEnchants
HealthBar
HiveChecker
Holograms
HolographicDisplays
HotbarPets (SlimeFun4 Addon)
InfinityExpansion (SlimeFun4 Addon)
Jobs Reborn
LibsDisguises
Liquid (SlimeFun4 Addon)
LiteXpansion (SlimeFun4 Addon)
LPC
Luckperms
LWCX
MinecordBot
MobCapturer (SlimeFun4 Addon)
Monstrorvm
morecompost
MoreOres
Multiverse Core
MyPet
mythicdrops
MythicMobs
NexEngine
NoChunkLag
nuvotifier
Oh the Dungeons youll go
OnePlayerSleeping
PersonalWarps
PlaceholderAPI
PrivateStorage (SlimeFun4 Addon)
ProtocolLib
SFCalc (SlimeFun4 Addon)
SignURLs
SimpleUtils (SlimeFun4 Addon)
Skript
SlimeFUn4
SlimefunOreChunks (SlimeFun4 Addon)
SlimefunWarfare (SlimeFun4 Addon)
SlimyRepair (SlimeFun4 Addon)
SlimyTreeTaps (SlimeFun4 Addon)
SMG (SlimeFun4 Addon)
SoulJars (SlimeFun4 Addon)
SoundMuffler (SlimeFun4 Addon)
SpawnerMeta
SuperbVote
TerraformGenerator
TranscEndence (SlimeFun4 Addon)
TwerkingCrops
Vault
VehicleDesyncFix
VeryDangerousNether
VillagerSaver
WorldEdit
WorldGuard
WorldSpawn
ZEnchantments
ZNPCS

### Paper version

This server is running Paper version git-Paper-714 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-675 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
This would be up to one of your many plugins. Without more details, there is little that can be done to determine which. However, the issue tracker would not be the correct place for this as it is likely not an issue with Paper. Please attempt replication without plugins, and if you need further help come by [discord.gg/papermc](https://discord.gg/papermc),
