### ISSUE TITLE
unpatch dupe

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#571]
**please unpatch the disconnect dupe**

# Performance issue
it is lagging the server called 2b2t by constantly checking others inventory

###  Timings or Profile link:
lag

### Description of issue:
lag

### Plugin list:
idfk

### bukkit.yml, spigot.yml, paper.yml, server.properties
no
### Other helpful links
no

### Paper build number:
idk

# Incompatibility (Bug)
lag
### What behaviour is expected:
no lag
### What behaviour is observed:
lag
### Steps/models to reproduce:
install paper spigot and run server

### Plugin list:
idfk

### Paper build number:
idfk

# Crash, Stacktrace
idfk

### Link/paste of stack trace

    You can also simply just use code formatting in markdown!
idfk
### Plugin list:
idfk
### Actions to reproduce (if known):
idfk

### Paper build number:
idfk

# Suggestion

remove the anti dupe patches

**Comment by KurtisAD** [comment]
I'm assuming you mean one of these two pulls

https://github.com/PaperMC/Paper/pull/557

https://github.com/PaperMC/Paper/pull/564

Neither of them do inventory checks, and neither of them have any performance impact.

**Comment by sudofox** [comment]
I say this is **invalid**.
Please stop spamming the Paper bug tracker trying to get the dupe back on 2b2t, just wait until another dupe is found or get off your rear end and find a race condition yourself. 
The lag on 2b2t.org is primarily from player-made lag machines.
For that matter, @bonces appears to be the guy running 2b2t, none of the rest of you are.

recent examples of things he's been posting about:

https://github.com/PaperMC/Paper/issues/481
https://github.com/PaperMC/Paper/issues/399

**Comment by KurtisAD** [comment]
@sudofox That is incorrect, @bonces has relinquished ownership of 2b2t, the current owner is unknown
