### ISSUE TITLE
Enderdragon Respawning Glitching

### ISSUE THREAD

**Issue by deciduous-buffalo** [PaperMC/Paper#5712]
### Expected behavior

The ender dragon respawns and heals from the end crystals, then this phase ends and you can fight the dragon while blowing up all the end crystals as well.

### Observed/Actual behavior

When you use pistons to move the endcrystals that are healing the dragon as it is respawning, the ender dragon respawn phase glitches and is forever in the healing animation and stays like this. Additionally, the healing end crystals are invincible and players are using pistons to move them to the overworld where they cannot be destroyed by a player in survival mode.

### Steps/models to reproduce

Respawn the ender dragon by hand placing the necessary crystals and then while it is in the healing animation use pistons to move an end crystal with beam.

### Plugin list

ProtocolLib, ViaVersion, ViaBackwards

### Paper version

This server is running Paper version git-Paper-655 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

https://bugs.mojang.com/browse/MC-108513

This appears to be a bug that was supposedly patched in 1.13 but people are reporting it is happening again in 1.16.x and the 1.17 snapshots

![image](https://user-images.githubusercontent.com/84668536/119261098-a307a400-bb8a-11eb-88ae-0ba106a89545.png)

**Comment by Machine-Maker** [comment]
I might be misunderstanding, but the dragon fight progressed fine after I moved one crystal during the respawn phase. The dragon spawned correctly, and I was able to kill the dragon.

Note, this isnt' addressing the moving the crystals to the overworld part of the problem.

**Comment by deciduous-buffalo** [comment]
Yea I described it incorrectly, the dragon fight was able to finish, but the indestructible crystals is still an issue like you said
