### ISSUE TITLE
[Suggestion] "PAPER ONLY" comment on methods

### ISSUE THREAD

**Issue by LoneDev6** [PaperMC/Paper#5719]
### Is your feature request related to a problem?

Sometimes I find slow to check if a method is added by the Paper API and not available on Spigot while coding using Paper as dependency, for example the [isSolid](https://github.com/PaperMC/Paper/blob/7259c32bacbad6e200eeb573e39c9d0b329f59c3/Spigot-API-Patches/0247-Additional-Block-Material-API-s.patch#L52) method

### Describe the solution you'd like.

I think an handy solution would be to introduce a text on the top of each Paper method comments.
This allows to hover the method name and check if it's Paper only or not.

For example:

```java
+    /**
+     * PAPER ONLY!
+     * <p>
+     * Check if this block is solid
+     * <p>
+     * Determined by Minecraft, typically a block a player can stand on and can't be passed through.
+     *
+     * This API is faster than accessing Material#isSolid as it avoids a material lookup and switch statement.
+     * @return true if block is solid
+     */
+    boolean isSolid();
```

### Describe alternatives you've considered.

Ignore my suggestion

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by HexedHero** [comment]
You can just check if the method you're using is inside a // Paper comment, this is what I do.

```
    // Paper start - Add more WanderingTrader API
    /**
     * Set if the Wandering Trader can and will drink an invisibility potion.
     * @param bool whether the mob will drink
     */
    public void setCanDrinkPotion(boolean bool);
```

**Comment by Prof-Bloodstone** [comment]
You can also use Mini's api diff viewer and see if the method is there: https://minidigger.github.io/paper-api-diff/changes.html

**Comment by Proximyst** [comment]
Definitely not at the top. Ideally, we would have a `@since` with MC version; that could also have Paper-only in it.

**Comment by kashike** [comment]
I don't see a need for this. There's plenty ways to find out if a method is available in Paper (or forks of) only.

**Comment by MiniDigger** [comment]
if you are one of the sad souls that still has to support spigot, just use that as a dep. if you use paper as your dep, that means you expect to use the paper api

**Comment by LoneDev6** [comment]
I will stick with the current workflow: CTRL+Click on the method and check for //Paper start comment.
Thanks for taking the time to read my suggestion
