### ISSUE TITLE
EntityTrackerEntry crash

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#572]
Paper build: 1021
Log: https://hastebin.com/qanejeyeto.md
Crash: https://hastebin.com/xuvezofuva.sm

I'm assuming the player "QueenSabine" caused the crash with /hat so I checked their .dat file and didn't find anything suspicious, all they had was a banner on their head: http://i.imgur.com/qcKgcSM.png

**Comment by zachbr** [comment]
You should not see this happen again on builds 1027+.
You may see a warning about a plugin doing something it shouldn't however.

Please let us know if you continue to see this SOE behavior with these newer builds.

**Comment by zachbr** [comment]
Closing as resolved.

**Comment by SecretlyJealous** [comment]
Just got this crash again.
Crash report: https://hastebin.com/ixireboxox.sm
Log: https://hastebin.com/munivugebe.md

**Comment by zachbr** [comment]
If you still see this in 1.12.2 please re-attach updated logs using github gists or any service that doesn't expire pastes.
