### ISSUE TITLE
Armorestand ticks

### ISSUE THREAD

**Issue by rikdijkslag** [PaperMC/Paper#5722]
### Is your feature request related to a problem?

i have a problem with an car plugin i am using. The plugin uses armor stands for the cars. The armorestands are very laggy on paper, but on spigot everything works fine. I think paper limits the armorestand ticks. 

### Describe the solution you'd like.

Can there be a option to remove the limit for armorestand ticks.

### Describe alternatives you've considered.

I have tried to set _armor-stands-tick_ to false but then the armor stands stopped moving at all

I discovered that the cars worked on build # 467 (1.16.5) After that build the cars are laggy

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Proximyst** [comment]
Do you have any logs?

**Comment by rikdijkslag** [comment]
https://pastebin.com/pFHKE20G here i hava the logs

**Comment by electronicboy** [comment]
plugin is doing stuff off the main thread which can cause state corruption, paper prevents such stuff as it can cause damage to the server and the world itself

**Comment by rikdijkslag** [comment]
so it cant be fixed

**Comment by Machine-Maker** [comment]
Well, not by paper. Contact the developers of that vehicle plugin it looks like.
