### ISSUE TITLE
Enchantment glint removed at update for item without enchantments

### ISSUE THREAD

**Issue by DavidTs93** [PaperMC/Paper#5723]
### Expected behavior

"Fake" glint on an item persists.

### Observed/Actual behavior

When updating an item that has a "fake" enchantment glint the visual glint is removed.

### Steps/models to reproduce

Run the command: `/give @p baked_potato{Enchantments:[{}]}` (or with any other Material).
Go into Creative mode.
Pick up said item and place it anywhere within your inventory.
The visual glint is removed (but the NBT tag stays the same though)

Another way to reproduce this is to make a plugin that upon opening an inventory it changes the items (like changing/adding lore) and replacing them in the inventory - the glint will be removed as well.

My conclusion: any update to an item with a "fake" enchantment glint will have its visual glint removed upon update.

### Plugin list

This problem was tested on a COMPLETELY fresh run of PaperMC - not even the config files were changed.

### Paper version

This server is running Paper version git-Paper-730 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Tried reproducing the same problem with a fresh run of Spigot but there it won't even show the initial glint... Weird.
On the other hand, when running a fresh run of Vanilla MC the problem DIDN'T occur.

Also, for all those that say: "Why are you doing this?! Just apply some random enchantment and add a HIDE_ENCHANTS flag!", I say: I have MANY reasons why I do it this way (cuz of plugins - there, I said it) so please don't suggest that as a "fix".

**Comment by imDaniX** [comment]
> Tried reproducing the same problem with a fresh run of Spigot but there it won't even show the initial glint... Weird.

So, upstream bug? Should probably be reported to [Spigot's JIRA](https://hub.spigotmc.org/jira/)  too.

**Comment by DavidTs93** [comment]
> > Tried reproducing the same problem with a fresh run of Spigot but there it won't even show the initial glint... Weird.
> 
> So, upstream bug? Should probably be reported to [Spigot's JIRA](https://hub.spigotmc.org/jira/) too.

I'll report it there as well, but it seems that Paper _kinda_ fixed it but not entirely, hence this report.

**Comment by Machine-Maker** [comment]
> The visual glint is removed (but the NBT tag stays the same though)
Are you sure this is true? Using `/paper dumpitem` shows that the Enchantments nbt tag list was removed.
The glint is controlled entirely by the client based on the existence of that NBT tag so it doesn't make sense that it wouldn't be reset. 

I can however, reproduce the main issue that the Enchantment NBT tag is "validated" in the sense that it removes invalid entries into it when you move it in your inventory.

**Comment by Machine-Maker** [comment]
I'd also like to know, did this start happening at some point? or has this always happened?

**Comment by DavidTs93** [comment]
> > The visual glint is removed (but the NBT tag stays the same though)
> > Are you sure this is true? Using `/paper dumpitem` shows that the Enchantments nbt tag list was removed.
> > The glint is controlled entirely by the client based on the existence of that NBT tag so it doesn't make sense that it wouldn't be reset.
> 
> I can however, reproduce the main issue that the Enchantment NBT tag is "validated" in the sense that it removes invalid entries into it when you move it in your inventory.

First, this only happens after the item is changed (for some reason it happens whenever you click in your inventory while in Creative?)
Second, I checked again and the tag DOES seem to disappear... (I was mistaken before - the tag stayed only when I checked it on Spigot)
Is there an option to disable removing the "fake" enchantment glint during "validation"? It's really annoying...

> I'd also like to know, did this start happening at some point? or has this always happened?

I tried it for the first time yesterday, so no idea.
I can check on older versions, but I don't know how much it'll help...

**Comment by Machine-Maker** [comment]
> Is there an option to disable removing the "fake" enchantment glint during "validation"? It's really annoying...

no, not really. Basically, it parses the nbt into a map of enchantments, and if it finds `{}` in the list of enchantments (or really anything invalid) it just skips over it, so when that map is applied back to the item's nbt, it no longer has the `{}`. There is an issue open to create some API for this (#5274) so I'd pay attention to that. Otherwise, this isn't really something that's broken.

**Comment by DavidTs93** [comment]
> > Is there an option to disable removing the "fake" enchantment glint during "validation"? It's really annoying...
> 
> no, not really. Basically, it parses the nbt into a map of enchantments, and if it finds `{}` in the list of enchantments (or really anything invalid) it just skips over it, so when that map is applied back to the item's nbt, it no longer has the `{}`. There is an issue open to create some API for this (#5274) so I'd pay attention to that. Otherwise, this isn't really something that's broken.

Yes, I saw it before and I do hope it'll be added soon...
Thanks for the info! I guess it isn't a bug after all... Oh well 😄 
At least I gave SpigotMC a heads up.

This can be closed now.
