### ISSUE TITLE
Placing water on a campfire and then breaking the campfire causes tile entity corruption error

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#5724]
### Expected behavior

No errors in console

### Observed/Actual behavior

Console prints this error:
[18:09:17 ERROR]: Block at -319, 65, -912 is Block{minecraft:water} but has net.minecraft.server.v1_16_R3.TileEntityCampfire@630fa39b. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.

### Steps/models to reproduce

Place a campfire:
![2021-05-25_18 08 51](https://user-images.githubusercontent.com/10485646/119539728-74edb400-bd84-11eb-865a-c12024ef4c77.png)

Place water on the campfire:
![2021-05-25_18 08 56](https://user-images.githubusercontent.com/10485646/119539749-7d45ef00-bd84-11eb-91db-e3f958deb3b1.png)

Break the campfire and it will produce an error in console:
![2021-05-25_18 09 24](https://user-images.githubusercontent.com/10485646/119539858-9d75ae00-bd84-11eb-9e1e-2c373338a2c4.png)

### Plugin list

BungeeGuard, LuckPerms, PlugMan, spark

### Paper version

This server is running Paper version git-Paper-731 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by nullfact0r** [comment]
I know this isn't exactly relevant to the bug but could you tell me which resource and shader pack you are using?

**Comment by SecretlyJealous** [comment]
> I know this isn't exactly relevant to the bug but could you tell me which resource and shader pack you are using?

**Resource pack:** SapixCraft - https://sapixcraft.com/downloads/java/ (I'm using the 256x version)
**Shaders:** Sildur's Vibrant shaders v1.29 Extreme - https://sildurs-shaders.github.io/downloads/

**Comment by Machine-Maker** [comment]
This doesn't happen in 1.17 anymore, it even looks like the fix that already existed for 1.17 can be dropped.
