### ISSUE TITLE
SIGSEGV (0xb) at pc=0x00007fe4a4ae8b23, pid=13317, tid=13331

### ISSUE THREAD

**Issue by alsoGAMER** [PaperMC/Paper#5748]
### Stack trace

https://paste.gg/p/anonymous/727e8d3fe0eb44a3bf269f7e973ec490

### Plugin list

`[20:19:31 INFO]: Plugins (23): BetterEnd, BlepFishing, BlowableObsidians, ChatColor2, Chunky, CustomJoinMessages*, EntityTrackerFixer, FastAsyncWorldEdit (WorldEdit), Gaea, IdleBot, Images, LuckPerms, MapManager, Md5Lukas-Commons, PacketListenerApi*, ProtocolLib, Quests, ServerListPlus*, Terra, TreeboTrunks, TreeFeller, Waypoints, WorldGuard`

### Paper version

```
[20:16:51 INFO]: Checking version, please wait...
[20:16:51 INFO]: This server is running Paper version git-Paper-744 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 1 version(s) behind
Previous version: git-Paper-742 (MC: 1.16.5)
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

It appears to be a JVM crash, so I already reported this same issue to oracle.
I'm opening a ticket also here to notify you of this problem, so you can verify if it's 100% only a bug in the JVM or it's caused by some other Paper components

**Comment by electronicboy** [comment]
segmentation fault in JVM code, either JVM bug or bad memory
