### ISSUE TITLE
Return value of "org.bukkit.entity.Entity.getCustomName()" is null

### ISSUE THREAD

**Issue by TheWolf95** [PaperMC/Paper#5758]
### Expected behavior

The entity damaging the player on EntityDamageByEntityEvent has a custom name set by the plugin. 
The method should correctly return the value.
I tested on a purpur server and there it works with no errors, performing events based on the name of the damager.
NOTE: the plugin is written on paper library, not purpur one

### Observed/Actual behavior

The method returns a null value, despite it has for sure a notnull value.
General java.lang.NullPointerException errors output in console and events based on it don't fire (since the string has to be equal to the name I set)

### Steps/models to reproduce

Create a firework entity:
`Firework fw = (Firework) location.getWorld().spawnEntity(location, EntityType.FIREWORK);`

give it a meta:
`FireworkMeta fwm = fw.getFireworkMeta();`

`fwm.setPower(power);`
`fwm.addEffect(FireworkEffect.builder().withColor(color).flicker(true).build());`

`fw.setFireworkMeta(fwm);`

set a custom name and detonate:
`fw.setCustomName("lvlupFirework");
fw.detonate();`

### Plugin list

My personal one, which contains the upper code and Luckperms

### Paper version

> version
[16:43:37 INFO]: Checking version, please wait...
[16:43:37 INFO]: This server is running Paper version git-Paper-753 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-711 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

As said before: no issues are encountered on Purpur, which afaik is a Paper fork, it should so be not much different

**Comment by TheWolf95** [comment]
Update to this:
Apparently purpur has the same issue, but the events (damage cancelling) do fire. In fact I don't get damage by fireworks, but I don't know why. I checked I was able to get damage by flying into floor with elytra

**Comment by TheWolf95** [comment]
> Update to this:
> Apparently purpur has the same issue, but the events (damage cancelling) do fire. In fact I don't get damage by fireworks, but I don't know why. I checked I was able to get damage by flying into floor with elytra

Update number 2:
Cannot replicate error anymore on Purpur with last update

**Comment by lynxplay** [comment]
As far as I know, the ItemMeta is cloned/read internally when using Firework#setFireworkMeta. Modifications to the same firework instance after setting it will not modify the entity/itemstack the meta was applied on prior.

**Comment by electronicboy** [comment]
custom name is stored on the entity itself not the stack, we'd need more info of how/where you're reading this back in order to actually reproduce it

**Comment by lynxplay** [comment]
Well, I tested this with the following code:

[Listener to create the firework](https://pastebin.com/QvhEAn61)
[Damage listener](https://pastebin.com/Rs43Frgr)

and cannot reproduce this issue. Am I missing something from my setup ? 
Produces:
![image](https://user-images.githubusercontent.com/32834385/120241432-049ed100-c263-11eb-9c23-b3ee2a385652.png)

EDIT_1: Run on `git-Paper-407ad043c (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)` which is latest at this point in time.

**Comment by TheWolf95** [comment]
> Well, I tested this with the following code:
> 
> [Listener to create the firework](https://pastebin.com/QvhEAn61)
> [Damage listener](https://pastebin.com/Rs43Frgr)
> 
> and cannot reproduce this issue. Am I missing something from my setup ?
> Produces:
> ![image](https://user-images.githubusercontent.com/32834385/120241432-049ed100-c263-11eb-9c23-b3ee2a385652.png)
> 
> EDIT_1: Run on `git-Paper-407ad043c (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)` which is latest at this point in time.

To get the error I did not put the null check, spawning exactly a "lvlUpfw" and listening to damage using an instanceof Firework condition

**Comment by lynxplay** [comment]
Please just provide the listener code of the example plugin. The null check should have absolutely no effect on this as it is not triggered.

**Comment by TheWolf95** [comment]
> Please just provide the listener code of the example plugin. The null check should have absolutely no effect on this as it is not triggered.

the null check prevents the error from showing up. In any case this is the listener code:
```
@EventHandler
public void entityDamage(EntityDamageByEntityEvent e) {

	Entity damager = e.getDamager();
	if(damager instanceof Firework && damager.getCustomName().equalsIgnoreCase("lvlupFirework")) e.setCancelled(true);

}

**Comment by lynxplay** [comment]
For your convenience I recreated your exact setup [here](https://pastebin.com/wd1PRsgC) which still worked great.
If I'd had to guess, this is not a paper related issue but rather an issue on your end regarding the spawning of the firework.
I would probably suggest the discord for more intense and real-time help with your issue.

**Comment by TheWolf95** [comment]
It appears that the Event and setup were correct, but I was spawning more Fireworks with no custom name. If you use a method like this:
```
public static void spawnFireworks(Location location, Color color, int power){

        Firework firework = (Firework) location.getWorld().spawnEntity(location, EntityType.FIREWORK);
        FireworkMeta firework_meta = fw.getFireworkMeta();
       
        firework_meta.setPower(power);
        firework_meta.addEffect(FireworkEffect.builder().withColor(color).flicker(true).build());
       
        firework.setFireworkMeta(firework_meta );
        firework.setCustomName("fireworkName");
        firework.detonate();
        
    }
```
for each firework, there should be no errors!
Thanks to some talk with @lynxplay we figured out and solved it. Thanks to everyone!
