### ISSUE TITLE
Add "disable-all-bugfixes" option to config

### ISSUE THREAD

**Issue by spidunno** [PaperMC/Paper#5764]
### Is your feature request related to a problem?

If you need to run a server for testing completely vanilla thing (breaking bedrock, TNT duping, etc.) but still need plugins, currently you would have to change hidden config lines (and a lot of them, might I add).

### Describe the solution you'd like.

As a solution, you could add a `disable-all-bugfixes` option to the config (false by default). It could possibly be at the bottom of the config.

### Describe alternatives you've considered.

I honestly cant think of another solution as I feel this would be best.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by aurorasmiles** [comment]
If you want to disable our patches, use Spigot. 
https://github.com/PaperMC/Paper/issues/3724#issuecomment-654030198

**Comment by Chew** [comment]
Or build your own fork with patches you don't like removed.
