### ISSUE TITLE
Villagers dropping infinite food

### ISSUE THREAD

**Issue by 4L0N50asd** [PaperMC/Paper#5765]
### Expected behavior

Expected a normal trade between farmer villagers when breeding, with normal drops of food. This is an automatic system to get more villagers, I used the one from the image in **_Steps/models to reproduce_**

### Observed/Actual behavior

Villagers duplicating the food they were trading themselves, getting infinite stacks of food.

### Steps/models to reproduce

Just a simple farm like this, with the objective to get more villagers
![image](https://user-images.githubusercontent.com/67982577/120406055-4f474880-c34a-11eb-8ff7-1a70b3790eee.png)

So you give them food (i didn't give them more than 1 stack of carrots) and they start breeding.

This is what happened

https://www.youtube.com/watch?v=TlHv0ISh2a0

### Plugin list

Plugins (79): AdvancedBan, AnimatedFrames*, AuthMe, AutoMessage, AWD*, BlazeFly*, BottledExp, BungeeTabListPlus, BuycraftX, Citizens, ClearLag, ClientDetector*, CommandHook, CompatNoCheatPlus*, CoreProtect, CrateReloaded, CreativeGates, DeathMessages, DiscordPAPIStats, DiscordSRV, dynmap*, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, ExtraContexts, HolographicDisplays, InventoryRollback, Jobs, LibsDisguises, Lift, LimitPillagers, LuckPerms, LWC, MapManager, MassiveCore, mcMMO, MineableSpawners, minecrafterhuf, MorkazSk, MultiChat*, Multiverse-Core, Multiverse-NetherPortals, NametagEdit*, OpenInv, PacketListenerApi*, PerWorldInventory, PetBlocks*, PlaceholderAPI, PlayerStatueBuilderX, PlotSquared, ProtocolLib, pvparena, Quests, QuickShop, Residence, Shopkeepers, SkBee, Skellett, SkinsRestorer, SkQuery, Skript, skript-reflect, StackMob, TARDIS, TARDISChunkGenerator, Towny, UltimateAutoRestart, UltimateTimber, Vault, Votifier, VotingPlugin, WDLCompanion*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper version

This server is running Paper version git-Paper-756 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-592 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

So i just installed an older version:

This server is running Paper version git-Paper-738 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 18 version(s) behind
Previous version: git-Paper-756 (MC: 1.16.5)

And this bug is not happening right now.

**Comment by BillyGalbreath** [comment]
```
This server is running Paper version git-Paper-738 (MC: 1.16.5)
You are 18 version(s) behind
```

This was specifically fixed in [build 742](https://github.com/PaperMC/Paper/commit/501cc944887347caf3ad35623ad0aecf144508b5) before Spigot finally [fixed it](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/c51c0f7fbb1157aa47c1b32a756ca568b581816f) upstream and their fix replaced mine in [build 756](https://github.com/PaperMC/Paper/commit/b94a99b0337823efb2863243deeb8701c3ff781e) of Paper.

Can you jump around these versions to see where the problem started exactly for you?

**Comment by 4L0N50asd** [comment]
It seems like this issue started in build 756 of Paper, i just tested these versions and I am not getting this bug:

Paper 738
Paper 743
Paper 750
Paper 753
Paper 755

Tested again with Paper 756 and i'm getting the same issue
