### ISSUE TITLE
Invisible items in inventory if beeing in a creative category

### ISSUE THREAD

**Issue by crafter23456** [PaperMC/Paper#5768]
### Expected behavior

That the items get shown even if I am not in the inventory.

### Observed/Actual behavior

If I collect items from e.g. a waterstream or collect it and I'm in a collection tab of the gamemode creative inventory the items are invisible until I open a new gui.

### Steps/models to reproduce

Video: https://imgur.com/a/3XOpjSF
1. Open a block collection or like that in the creative inventory
2. Collect items while beeing in the inventory like e.g. from a waterstream
3. Open the player inventory and see, the items in the slots higher than 9 are invisible until I open a new gui like a chest

### Plugin list

No plugins

### Paper version

This server is running Paper version git-Paper-759 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-615 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I encountered the bug month ago but yet I had time to analyse it better :D

**Comment by Chew** [comment]
This feels entirely clientside, though I don't know enough about what we do to the inventory that could cause this. Does this same behavior happen in vanilla as well?

**Comment by e-im** [comment]
Vanilla issue, resolved in 1.17. [MC-87019](https://bugs.mojang.com/browse/MC-87019)
