### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5769]
### Is your feature request related to a problem?

Many people (me included) would like to stay on the LTS releases of Java. The latest LTS release is java 11.

### Describe the solution you'd like.

After the transition to Java 16, still retain support for Java 11

### Describe alternatives you've considered.

alternatively, as part of the automatic builds, we can have it build for Java 11 and Java 16 separately

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by yannicklamprecht** [comment]
Not a possibility. Minecraft 1.17 updates to Java 16. If you want to stay on Java 11 stay on Minecraft 1.16.5 until September.

**Comment by e-im** [comment]
Reference yannicklamprecht's comment, as well as [the 21w19a snapshot release](https://www.minecraft.net/en-us/article/minecraft-snapshot-21w19a) where Mojang announced their decision to go with java 16.

**Comment by MiniDigger** [comment]
And even if we could, there is virtually no reason to get stuck on LTS versions. Java versions are stable and designed to be ran in production.
