### ISSUE TITLE
Add option to disable entity collisions completely 

### ISSUE THREAD

**Issue by jd1378** [PaperMC/Paper#577]
i want to disable collisions so players and mobs can walk through each other easily and no one get pushed.
i will be glad if you add this option .

**Comment by aikar** [comment]
I think you can achieve this by setting max collisions per tick to 0 in spigot.yml?

**Comment by prplz** [comment]
@aikar it seems that option is long gone

**Comment by jd1378** [comment]
@aikar  i can't find the option 
edit: also its good to have the option to turn off collisions per mob

**Comment by aikar** [comment]
I re-added that setting under paper.yml, set max-entity-collisions=0

**Comment by malonnnn** [comment]
@aikar 

I notice that when riding in a minecart, the minecart will still come to a stop when hitting mobs. Is this intended?

**Comment by manvankaliber** [comment]
@aikar I set this setting to 0 and mobs still collide with each other. Walking in to them also causes them to be pushed away.

**Comment by MiniDigger** [comment]
please dont bump 3 year old issues, rather create a new one and link this, if you think this is related

**Comment by manvankaliber** [comment]
Why would I create a new issue when this exact issue isn't fixed yet? Github added a 're-open issue' button for a reason...

**Comment by Spottedleaf** [comment]
set cramming to zero and the max collisions per entity to 0 and they will be disabled
