### ISSUE TITLE
Display name bleeds into chat message if AsyncPlayerChatEvent is registered

### ISSUE THREAD

**Issue by Bentley1201** [PaperMC/Paper#5771]
### Expected behavior

Display name color not bleeding into the message - 
https://cdn.discordapp.com/attachments/505599000833949700/849748451834068992/Screen_Shot_2021-06-02_at_3.36.15_PM.png

### Observed/Actual behavior

Display name color bleeding into the message - https://cdn.discordapp.com/attachments/420342659115122688/849505901105774612/Screen_Shot_2021-06-01_at_11.29.13_PM.png

### Steps/models to reproduce

Using the code outlined here - https://pastebin.com/raw/APBA6hj7 the aqua color will bleed into the message, commenting out AsyncPlayerChatEvent fixes and resets the color before the >, as expected. 

### Plugin list

AdventureTest (the test plugin I made to duplicate) 

### Paper version

[20:40:36 INFO]: This server is running Paper version git-Paper-759 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-758 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
I believe this is how it behaved before Adventure, but assigning to kashike nonetheless as I've no idea...

**Comment by e-im** [comment]
This is expected behaviour.
