### ISSUE TITLE
Chunkbans

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5774]
### Expected behavior

Not be chunkbanned

### Observed/Actual behavior

Got chunkbanned

### Steps/models to reproduce

Download WurstClient for 1.16.5 (latest version)
Join Paper server with Creative
run CrashChest
Put a ton of them in a shulker
Break the shulker

### Plugin list

Citizens, CitizensCMD, LuckPerms, Multiverse-Core, NoCheatPlus*, WorldEdit, WorldGuard

### Paper version

This server is running Paper version git-Paper-762 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Accrilix lost connection: Internal Exception: net.minecraft.server.v1_16_R3.PacketEncoder$PacketTooLargeException: PacketTooLarge - PacketPlayOutEntityEquipment is 5403155. Max is 2097152

Was testing WurstClient crashchest because I had heard Paper patches that, spoiler alert: IT DIDNT.

**Comment by sleepylessons** [comment]
@ic3dm4ng0 I might suggest this plugin to you, has helped a lot with Book Bans on my server:

https://www.spigotmc.org/threads/antibookban.493243/

It will just prevent the Ban Books from being created (if used properly in tandem with the Paper settings that limit the byte size of books -- you should lower this limit as the default limit is rather high)

It blocks non-ASCII characters from being added to books, which in my experience, is what allows the books to be created in the first place. I'm not saying this is a solution but is a good band-aid for now.

**Comment by e-im** [comment]
If you run a creative server, there are many ways beyond this to crash it or clients. Paper does not restrict creative mode in the way that would be required to prevent this. When running a creative server, it is highly recommended to use plugins to restrict further what can be done in creative mode.
