### ISSUE TITLE
Chat vs Console command arguments mismatch

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#5777]
### Expected behavior

_Player1_ or _Console_ performed command:
```
/tt 1 2  3   4    5     0
````
TestPlugin `onCommand` handler received:
```
arguments: ["1", "2", "3", "4", "5", "0"]
```

### Observed/Actual behavior

_Player1_ performed command:
```
/tt 1 2  3   4    5     0
````
TestPlugin `onCommand` handler received:
```
arguments: ["1", "2", "3", "4", "5", "0"]
```

_Console_ performed command:
```
/tt 1 2  3   4    5     0
````
TestPlugin `onCommand` handler received:
```
arguments: ["1", "2", "", "3", "", "", "4", "", "", "", "5", "", "", "", "", "0"]
```

### Steps/models to reproduce

```java
@Override
public boolean onCommand(CommandSender theSender, Command theCommand, String labelString, String[] arguments) {
	if (theCommand.getName().equalsIgnoreCase("tt")) {
		System.out.println("arguments: [\"" + String.join("\", \"", arguments) + "\"]");
		return true;
	}

	return false;
}
```

Then try to perform `tt` command with more than 1 space between arguments from game chat and server console and see the difference. This problem can break some plugins which do not expect to see empty strings as the argument value, because you can't send an empty argument from a game chat.

### Plugin list

TestPlugin

### Paper version

git-Paper-763 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Prof-Bloodstone** [comment]
It's weird because I swear I had an issue before with executing commands with too many spaces as player, but might remember it wrong since I can't reproduce.

It's also an issue with rcon - it doesn't strip it either.
Confirmed with grakkit:
```js
core.command({
  name: 'tt',
  execute: (player, ...args) => {
    player.sendMessage("Arguments: " + args)
  }
})
```
In game:
```
/tt 1  2   3
Arguments: 1,2,3
```
Console:
```
[10:43:52 INFO]: Prof_Bloodstone issued server command: /tt 1 2 3
> tt 1  2   3
[10:45:12 INFO]: Arguments: 1,,2,,,3
```
RCON:
```
./rcon-cli 'tt 1  2   3'
Arguments: 1,,2,,,3
```

This could be caused by chat processing earlier on, where it squashes duplicate whitespace:
```
I     like     tacos
<Prof_Bloodstone> I like tacos
```

**Comment by molor** [comment]
(same on 1.17.1)
