### ISSUE TITLE
Suggestion for the barrier

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#578]
When the barrier is set to a smaller-than-29999999 coordinate, the world ahead of the barrier is unloaded, in order to improve the processing. (Since I don't need the other part of the world.)

![2017-01-10_11 51 04](https://cloud.githubusercontent.com/assets/9270074/21808594/14640f9c-d72b-11e6-9f4b-4c04b90e0720.png)

**Comment by prplz** [comment]
This has negligible impact on performance, also world borders are able to move on a timer which would make seeing beyond the border somewhat necessary.

**Comment by zachbr** [comment]
The area ahead of the border is loaded the same as any other part of the world. If you have lots of people on the edge of the world, more chunks beyond the border will load. These areas outside the border should be much much cheaper than those inside of it.

As prplz points out, the vanilla world border is designed to move on a timer which makes this sort of behavior useful. This could perhaps be blocked with a plugin, but even then I don't see it being of much use.
