### ISSUE TITLE
MemorySection#getString(path, def) seems to always return def

### ISSUE THREAD

**Issue by RoinujNosde** [PaperMC/Paper#5781]
### Expected behavior

MemorySection#getString(path, def) should return the default only when the path is not set.

### Observed/Actual behavior

MemorySection#getString(path, def) returns the default even when the path is set.

### Steps/models to reproduce

```java
System.out.println("plugin.getConfig().getString(\"items.computer.type\") = " + plugin.getConfig().getString("items.computer.type"));
System.out.println("plugin.getConfig().getString(\"items.computer.type\", \"COMMAND_BLOCK\") = " + plugin.getConfig().getString("items.computer.type", "COMMAND_BLOCK"));
```
Config.yml:
```yml
items:
  computer:
    type: "PLAYER_HEAD"
```

The code and config above produces this:
```
[10:53:33] [Server thread/INFO]: plugin.getConfig().getString("items.computer.type") = PLAYER_HEAD
[10:53:33] [Server thread/INFO]: plugin.getConfig().getString("items.computer.type", "COMMAND_BLOCK") = COMMAND_BLOCK
```

### Plugin list

CryptoMarket, CryptoMining, EconomyX*, Vault

### Paper version

```
> icanhasbukkit
[10:53:40 INFO]: This server is running Paper version git-Paper-768 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-706 (MC: 1.16.5)
```

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Prof-Bloodstone** [comment]
I was unable to reproduce it on latest Paper (768). What you have seems correct though. Will investigate a bit more.
Config:
```yaml
head: "PLAYER_HEAD"
items:
  thing: "PLAYER_HEAD"
  computer:
    type: "PLAYER_HEAD"
```
Commands:
```js
> js core.plugin.getConfig().getString("head", "COMMAND_BLOCK")
[16:42:06 INFO]: "PLAYER_HEAD"
> js core.plugin.getConfig().getString("items.thing", "COMMAND_BLOCK")
[16:42:11 INFO]: "PLAYER_HEAD"
> js core.plugin.getConfig().getString("items.computer.type", "COMMAND_BLOCK")
[16:42:19 INFO]: "PLAYER_HEAD"
> js core.plugin.getConfig().getString("nonexistent", "COMMAND_BLOCK")
[16:42:28 INFO]: "COMMAND_BLOCK"
```

**Comment by Prof-Bloodstone** [comment]
I managed to reproduce it:
```kotlin
    override fun onEnable() {
        this.saveDefaultConfig()
        this.logger.info(this.config.getString("items.computer.type", "COMMAND_BLOCK"))
        this.logger.info(this.config.getString("items.thing", "COMMAND_BLOCK"))
        this.logger.info(this.config.getString("head", "COMMAND_BLOCK"))
    }
```
First startup:
```
[17:01:30 INFO]: [TP] COMMAND_BLOCK
[17:01:30 INFO]: [TP] COMMAND_BLOCK
[17:01:30 INFO]: [TP] COMMAND_BLOCK
```
After `/reload` or restart:
```
[17:01:40 INFO]: [TP] PLAYER_HEAD
[17:01:40 INFO]: [TP] PLAYER_HEAD
[17:01:40 INFO]: [TP] PLAYER_HEAD
```
This looks like the `config.yml` that's in the jar is no longer used as a fallback - and so it doesn't read any value here.

**Comment by RoinujNosde** [comment]
If I save the default config before fetching the values, it's not reproducible, even after a reload.

**Comment by Prof-Bloodstone** [comment]
You mean if you save default config and then try to get values without restarting/reloading, it'll work?
For me it doesn't work until I've either restarted/reloaded or forced config reload with `this.reloadConfig()`.
It seems to be behaving the same way in 1.15 and 1.14 too (checked on Spigot), despite Bukkit documentation claiming that it should work <https://bukkit.fandom.com/wiki/Configuration_API_Reference#Default_Values>
> In the case that a config.yml is missing or incomplete, values will be loaded from included config.yml.

**Comment by RoinujNosde** [comment]
> You mean if you save default config and then try to get values without restarting/reloading, it'll work?

Exactly.

**Comment by Prof-Bloodstone** [comment]
Reported upstream: https://hub.spigotmc.org/jira/browse/SPIGOT-6493

**Comment by RoinujNosde** [comment]
As commented [here](https://hub.spigotmc.org/jira/browse/SPIGOT-6493?focusedCommentId=39115&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-39115), this is the expected behaviour.

**Comment by Kylepoops** [comment]
So use `get(path)?: Default Value` lol

**Comment by RoinujNosde** [comment]
@Kylepoops I don't use Kotlin.
