### ISSUE TITLE
Paper problem with mcfunction

### ISSUE THREAD

**Issue by craftish37** [PaperMC/Paper#5782]
### Expected behavior

mcfunctions executed in less than a second

### Observed/Actual behavior

Just crash the server occasionally

### Steps/models to reproduce

Use a datapack who uses mcfunctions with tasks executed in less than one second

### Plugin list

no

### Paper version

>.... [18:11:08 INFO]: Checking version, please wait...
>.... [18:11:08 INFO]: This server is running Purpur version git-Purpur-1159 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1156 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

_Special note of the original reporter_ : "spigot/paper have a optimization code, and the inferno has a lot of mcfunction running in one second, i guess Paper can not handle all that functions and it just crash!"

For any questions/interrogations, just reply to this issue

For test, you can use the Incendium datapack (not the Paper one, they just deleted what cause the issue) :
https://www.planetminecraft.com/data-pack/incendium-nether-expansion/

**Comment by e-im** [comment]
Could you provide logs of this crash?

**Comment by electronicboy** [comment]
We don't take bug reports from other software, you've also not provided any form of info on the actual issue, i.e. no logs

datapacks in general are not great in many varying ways which can cause issues, especially on servers
