### ISSUE TITLE
Extended API for Bukkit.hidePlayer()

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5787]
### Is your feature request related to a problem?

I would like to hide players from other players without removing the hidden player from tab, say for example there is a dueling arena that is used by multiple players, or in a minigame.

### Describe the solution you'd like.

I would like Bukkit.hidePlayer(boolean removePlayerList), if set to false, the player's tablist packets won't be blocked.

### Describe alternatives you've considered.

Using ProtocoLlib to block outbound entity packets, large performance hit when many players are online and sounds created by vanished players such as from eating aren't blocked like they are in Bukkit.hidePlayer();

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by richardwhateverr** [comment]
https://github.com/PaperMC/Paper/issues/5757
Same Issue…

**Comment by Chew** [comment]
Technically a subsidiary of the above issue, feel free to add to the discussion there as it feels like it'd be under the same umbrella.
