### ISSUE TITLE
Error Saving entity NBT

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5791]
### Expected behavior

The server should be able to store the NBT properly to let a plugin sync inventory etc via mysql in a server network.

### Observed/Actual behavior

When the player leaves an NullPointerException occurs (probably in paper itself)

### Steps/models to reproduce

Let the playerdata being saved

### Plugin list

Mix of own and (big) third party plugins.

### Paper version

1.16.5-775
(with 1.1.6.5-759 everything works fine) 

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Message in logfile: https://pastebin.com/GhJEFVim

**Comment by Proximyst** [comment]
We need the *entire* exception or this will not be fixed.

**Comment by ghost** [comment]
oh, i forgot to copy this:

	at net.minecraft.server.v1_16_R3.Entity.save(Entity.java:1757) ~[patched_1.16.5.jar:git-Paper-775]
	... 12 more

**Comment by Kurumi78** [comment]
Here is a hastebin with the whole error for easy viewing. (I was getting the exact same error) https://bin.bloom.host/quduyoniqu.properties

**Comment by Proximyst** [comment]
Reproducible through removing the origin world of a mob while it's in another world and unloading the chunk.

**Comment by wolflord212312** [comment]
https://mcpaste.io/3e559f6c2bbbb017 (my logs for 1.16.5 papper)

**Comment by e-im** [comment]
This has been fixed in 1.17. 1.16 is now no longer being updated or supported.
