### ISSUE TITLE
Add PlayerOpChangeEvent that triggers when a player's op status changes (i.e. op/de-op)

### ISSUE THREAD

**Issue by rawora-rg** [PaperMC/Paper#5792]
### Is your feature request related to a problem?

Currently, there is no way to know for sure when a player becomes OP.

### Describe the solution you'd like.

Similar to the **PlayerGameModeChangeEvent**, there should also be one that triggers when a player's op status changes.

### Describe alternatives you've considered.

There are only workarounds, like using the **PlayerCommandPreprocessEvent** to see if the command contains "_/op_", or **ServerCommandEvent** to see if the "_op_" command was used by the console.

However, these events do not trigger when using the **player#setOp** method in plugins. 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by BillyGalbreath** [comment]
> However, these events do not trigger when using the player#setOp method in plugins.

General rule of thumb is API doesnt call events, either, so that would still be a problem. (think about `Player#teleport` not firing the `PlayerTeleportEvent`, etc)

**Comment by TheFruxz** [comment]
Personally, I would not use abbreviations and draw attention to the status change, I would more like "PlayerOperatorStateChangeEvent".

**Comment by qixils** [comment]
> (think about `Player#teleport` not firing the `PlayerTeleportEvent`, etc)

that's actually one of few cases where it does call the event :P
![image](https://user-images.githubusercontent.com/13265322/125701184-ef050ba4-f514-4a11-9542-9409661fc649.png)

**Comment by matytyma** [comment]
Any plans on adding this? What workarounds did you use to check for plugin-issued OP changes?
