### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by TitanicFreak** [PaperMC/Paper#58]
I have no idea what your opinion is still on paper 1.8.8, but I'll make this anyway.

I was idling on my server then some idiot randomly suicides tons of times, I thought nothing of it till the server crashes only seconds later.

The crash report would be, http://hastebin.com/okipopamoj.avrasm

I have no idea how to fix this other then blocking the suicide command.

EDIT: Essentials currently handles the /suicide command, but I don't see that being an issue...

**Comment by zachbr** [comment]
We do not currently have plans to support 1.8.8 unless there's some severe issue that pops up.
Thanks anyway :)
