### ISSUE TITLE
Make the only spigot plugins work with paper

### ISSUE THREAD

**Issue by arnon001** [PaperMC/Paper#5801]
### Is your feature request related to a problem?

Kinda,
Cuz when i want to use Only Spigot Plugins, I have do download spigot and cant use paper

### Describe the solution you'd like.

Make it work

### Describe alternatives you've considered.

Move To Spigot

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by e-im** [comment]
Please elaborate. What exactly is not working? And could you provide logs or any other details?

Also if you are meaning this as more of a question, paper aims to be compatible with spigot plugins.

**Comment by e-im** [comment]
Please come to our discord at [discord.gg/papermc](https://discord.gg/papermc) if you need further support regarding this.
