### ISSUE TITLE
Add method to get count of entities of specific type for chunk world

### ISSUE THREAD

**Issue by Shevchik** [PaperMC/Paper#581]
Use case: limiting amount of entities by type for world/chunk.

**Comment by MiniDigger** [comment]
world has a method getEntitiesByClass which allows you to do that.
chunk does not have such a method, but you can call getEntities and filter that array using a stream easily.

**Comment by prplz** [comment]
@MiniDigger the logic in Chunk.getEntities is really not great for being called often though

**Comment by AlfieC** [comment]
Maybe each chunk could have an int array w/ the key being the ordinal of the entity type

**Comment by Brokkonaut** [comment]
Spigot has this
_protected gnu.trove.map.hash.TObjectIntHashMap<Class> entityCount_
per chunk, that contains the amount of entities in the categories monster, animal, water_animal and ambient - making this amounts available in some api might be very usefull for some checks.

**Comment by JanTuck** [comment]
Oh, this is old, but it had the to do tag.

This was already done.

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Chunk.html#getEntities()

**Comment by Laarryy** [comment]
Open for no reason; as mentioned above, this is already done.

**Comment by Brokkonaut** [comment]
This is not done. Those spigot issues just have the same id as this issue, they have nothing to do with this.

**Comment by Laarryy** [comment]
Sorry, my fault for not mentioning this - the poor logic mentioned earlier has been optimized by leaf, hopefully mitigating any need for this issue. See https://github.com/PaperMC/Paper/blob/master/patches/server/0734-Rewrite-entity-bounding-box-lookup-calls.patch#L69-L82
