### ISSUE TITLE
Commands executed by signs via right click not logged in console

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#5828]
### Expected behavior

```
Player issued server command: /warp test
```

### Observed/Actual behavior

Nothing

### Steps/models to reproduce

```
/setblock ^ ^1 ^ minecraft:oak_sign{"Text1":'[{"text":"test","clickEvent":{"action":"run_command","value":"warp test"}}]',"Text2":"","Text3":"","Text4":""}
```

Then right click on sign. Command works perfectly and teleports player (by Essentials plugin), but there's nothing in server console.

### Plugin list

EssentialsX (only for `warp` command, same result with and without it)

### Paper version

git-Paper-777 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Maybe this is upstream/vanilla bug, but I'm not I'm not sure

**Comment by molor** [comment]
It seemed to me that this is configured in `paper.yml`, however, the setting is in `spigot.yml`
```
commands:
  log: true
```
so this isn't Paper bug.. anyway, maybe you can fix it..

**Comment by imDaniX** [comment]
Does it log commands on vanilla?

**Comment by molor** [comment]
> Does it log commands on vanilla?

Hmmm, no. So this is even vanilla bug
