### ISSUE TITLE
1.17 progress appreciation ticket

### ISSUE THREAD

**Issue by jippi** [PaperMC/Paper#5830]
### Is your feature request related to a problem?

Nope.

I just wanted to say `thank you` x 100 for the hard work going on in #5785 - I _really_ do appreciate all the effort y'all put into making Paper support 1.17 at an incredible pace.

Sorry if this ends up as noise for y'all instead, but just wanted to reach out and praise the huge effort going on!

Thank you!

### Describe the solution you'd like.

Nothing, y'all kicking ass already!

### Describe alternatives you've considered.

There is no good alternative to PaperMC

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

Thanks!

**Comment by aurorasmiles** [comment]
Thank you very much for the kind words :)
