### ISSUE TITLE
Generate Tree Block Change Delegate

### ISSUE THREAD

**Issue by alfiejfs** [PaperMC/Paper#5843]
### Expected behavior

The BlockChangeDelegate provided in the method World#generateTree(Location, TreeType, BlockChangeDelegate) does something

### Observed/Actual behavior

The BlockChangeDelegate provided in the method World#generateTree(Location, TreeType, BlockChangeDelegate)

### Steps/models to reproduce

Look at the source code for World#generateTree(Location, TreeType, BlockChangeDelegate)

### Plugin list

N/A

### Paper version

Latest (not fixed in any recent patches)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I would suggest possibly changing the functionality of the BlockChangeDelegate to instead accept blocks after the tree is generated - this would be a lot more user friendly than dealing with block data. However, what do I know; do whatever you smart people think is best!

**Comment by wizjany** [comment]
this was broken in spigot fairly recently (last few months) since bee nests require TE data that can't be captured in blockdata
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/28d72c4bd8c22f568384560459d0d703c2d0fefe
ref https://github.com/EngineHub/WorldEdit/issues/1745

**Comment by alfiejfs** [comment]
Interesting. If it's unfixable in its current state then it should probably be deprecated and a note added to the JavaDoc

**Comment by YHDiamond** [comment]
If you don't have any plugins installed, then how do you even know about this issue?

**Comment by e-im** [comment]
Please include the exact version of paper you are able to reproduce on, even if it is not fixed in future versions. Latest is not a version.

**Comment by alfiejfs** [comment]
> Please include the exact version of paper you are able to reproduce on, even if it is not fixed in future versions. Latest is not a version.

Apologies. git-Paper-674 (PaperMC 1.16.5). Still applies right now after checking source!

**Comment by Owen1212055** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/78d5b35b82dfbb185c505e659887cb539e781b7d

Fixed in upstream commit.

**Comment by wizjany** [comment]
does this re-break bee nests or something then 🤔

**Comment by Owen1212055** [comment]
Seems so, the code is the same.

**Comment by Machine-Maker** [comment]
I think this maybe fixed it? https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/block/CapturedBlockState.java#28 idk

Althought maybe not, thats part of the update method which isnt called anymore.

**Comment by Owen1212055** [comment]
![image](https://user-images.githubusercontent.com/23108066/130365202-73ed4ede-a276-4ace-8a31-f20930eea6dc.png)
It seems that was a different issue? But holy cow that is a weird hack.
