### ISSUE TITLE
Custom NBT Data on items are lost during inventory click events (only in Creative Mode?)

### ISSUE THREAD

**Issue by Yldales** [PaperMC/Paper#5845]
Hi,

### Expected behavior

Items with custom/non-vanilla NBT tags (like `{display":{"skin":"gold_coin"}}}`) should not be lost.

### Observed/Actual behavior

Items with custom/non-vanilla NBT tags (like `{display":{"skin":"gold_coin"}}}`) are lost.

### Steps/models to reproduce

1. Setup a server using [Paper 777](https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/777/downloads/paper-1.16.5-777.jar) for Minecraft 1.16.5.
2. Use `/give @p stick{"display":{"skin":"gold_coin"}}`.
3. On the Minecraft client, use F3+H to enable _Advanced Tooltips_.
4. Open your inventory.
5. Hover the given item. You should see a tooltip with "_NBT: 1 tag(s)_".
7. Do one of the following actions in creative mode.
    * Move the given item to another slot.
    * Duplicate the given item using the middle click.
8. Hover the given item again. The "_NBT: 1 tag(s)_" should be gone.

### Plugin list

None.

### Paper version

This server is running Paper version git-Paper-777 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Thanks.

**Comment by Yldales** [comment]
Maybe related to,

- PaperMC/Paper#3714 (closed due to «_Fixed in Paper-29_»).
- PaperMC/Paper#559

In `paper.yml`, setting `filter-nbt-data-from-spawn-eggs-and-related` from `true` (by default) to `false` don't fix the issue.

**Comment by Proximyst** [comment]
Can't be fixed. Creative mode tells the server what items it wants; it's on the client to know which NBT tags it cares about when doing so.
