### ISSUE TITLE
Operating system is misreported

### ISSUE THREAD

**Issue by LikeToAccess** [PaperMC/Paper#5847]
### Expected behavior

System Info: Java 16 (Java HotSpot(TM) 64-Bit Server VM 16.0.1+9-24) Host: Windows Server 2022 10.0 (amd64)

### Observed/Actual behavior

System Info: Java 16 (Java HotSpot(TM) 64-Bit Server VM 16.0.1+9-24) Host: Windows Server 2019 10.0 (amd64)

### Steps/models to reproduce

Running any PaperMC server on Windows server 2022.

### Plugin list

DeathLocation
floodgate-bukkit
Geyser-Spigot

### Paper version

> version
[02:02:01 INFO]: Checking version, please wait...
[02:02:01 INFO]: This server is running Paper version git-Paper-777 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-748 (MC: 1.16.5)
>

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This is just a minute visual issue. Windows Server 2022 is fairly new, it just displays it as Windows Server 2019 instead.

**Comment by electronicboy** [comment]
These strings are pulled from java, which are pulled from the OS somewhere, not a paper issue
