### ISSUE TITLE
2 mobs summon instead of 1 when using egg spawners in/on water

### ISSUE THREAD

**Issue by hectozul** [PaperMC/Paper#5848]
### Expected behavior

only 1 mob to summon, not 2

### Observed/Actual behavior

2 mobs spawn when you use an egg spawner in water

### Steps/models to reproduce

-hold any mob egg spawner
-use the egg spawner looking to water

### Plugin list

**geyser-spigot**  current latest build
**protocolLib**  Build for 1.17   

### Paper version

Paper version git-Paper-"4c074f2" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Oyplap** [comment]
I am using the same paper.jar (Version 1.17-R0.1-SNAPSHOT) and I cannot reproduce this issue.

**Comment by Proximyst** [comment]
Assigning to @KennyTV.

**Comment by kennytv** [comment]
Can't reproduce

**Comment by hectozul** [comment]
Try with the new water mobs, if you still can't reproduce tomorrow ill upload a video

**Comment by hectozul** [comment]
oh sorry. I will report the issue to geyser, the bug only happens from Bedrock client while using geyser.
