### ISSUE TITLE
Mob death sound is not played (1.17 Experimental)

### ISSUE THREAD

**Issue by Rasmion** [PaperMC/Paper#5850]
### Expected behavior

When I kill a mob, its death sound plays.

### Observed/Actual behavior

When I kill a mob, minecraft:entity.generic.death is played and not the death sound of the given mob.

### Steps/models to reproduce

Kill a mob. (Tested with creeper, chicken, sheep, pig)

### Plugin list

None

### Paper version

git-Paper-"3740db0" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Aurelien30000** [comment]
Can confirm with default circumstances.
_Also, this is indeed a paper issue, not replicable on Vanilla or Spigot._

**Comment by Proximyst** [comment]
Thank you for confirming the bug! Assigning to @KennyTV

**Comment by LethalEthan** [comment]
Can confirm tested in paper and vanilla, vanilla did not produce the generic sound

**Comment by Camotoy** [comment]
Possibly related for the sake of discussion: there was a new entity status created for living entities (status 60) that creates the death "poof" particles.

**Comment by kennytv** [comment]
That's unrelated, already working on the fix (tho I have to fight paperweight first)

**Comment by kennytv** [comment]
Fixed in https://github.com/PaperMC/Paper/commit/3d81d4e5b289a106958bb9d922555b268d54f3b4
