### ISSUE TITLE
1.17: Entity origin not works in alpha builds

### ISSUE THREAD

**Issue by AchiraE** [PaperMC/Paper#5856]
### Expected behavior

All entities should have origin infomation

### Observed/Actual behavior

Most of the entities do not have origin. use `Entity#getOrigin` will return null, `/data get entity @e[...]` have no `Paper.Origin` and `Paper.OriginWorld` fields.

### Steps/models to reproduce

+ drop an item or use spawn egg or use /summon
+ /data get entity 

### Plugin list

No

### Paper version

Tested in both `experimental build` and my own build of the latest commit
`This server is running Paper version git-Paper-"9bebf0b" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)`

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
Does this happen on a new world or upgraded world?

**Comment by AchiraE** [comment]
Upgraded world

-----
Edit: Also tried in a clean 1.17 world with the same results

**Comment by Proximyst** [comment]
Thanks. Assigning to @electronicboy as he just rewrote this patch...
