### ISSUE TITLE
Json components is not supported (1.17)

### ISSUE THREAD

**Issue by hapeshiva** [PaperMC/Paper#5857]
### Expected behavior

Json components is not supported, hover and click events doesnt work.

### Observed/Actual behavior

After i write a message in chat, they translates to chat, but console give a error and hover and click events doesnt work.

### Steps/models to reproduce

![image](https://user-images.githubusercontent.com/59057758/122376630-c05b4280-cf7d-11eb-88dd-47c00a9ade20.png)

### Plugin list

![image](https://user-images.githubusercontent.com/59057758/122376670-ccdf9b00-cf7d-11eb-961d-1469a347fc20.png)

### Paper version

Paper version git-Paper-"3740db0" (1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by kezz** [comment]
Your Chatty plugin needs updating

**Comment by Proximyst** [comment]
Not a Paper issue
