### ISSUE TITLE
chunkLoad - recreateStructures takes a long time. Can this be improved?

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#586]
I have a world that has been around since Minecraft 1.3 (Paper 1032 now) and recreateStructures takes almost the entire 4GHZ core at times. If I recall correctly warmroast pointed towards structure monster population. Is there anything I can do to ease the pain?

P.S.
Sorry if this seems a bit offtopic. I didn't get much help from Spigot forums.

**Comment by aikar** [comment]
This is usually due to chunk generation. Please come on Paper IRC channel and give a timings link and we can help analyze it, but no there's nothing much we can do about that section of code.
