### ISSUE TITLE
1.17 Annotation Processor Relocation

### ISSUE THREAD

**Issue by kev626** [PaperMC/Paper#5864]
### Expected behavior

1.17 builds using NMS on Maven should "just work".

### Observed/Actual behavior

Receive an error at compilation on Maven:

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project *****: Compilation failure
Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider org.bukkit.craftbukkit.v1_17_R1.libs.org.eclipse.sisu.space.SisuIndexAPT6 not found

This is due to the annotation processor definition being relocated in services/javax.annotation.processing.Processor, but the class itself not being relocated.

### Steps/models to reproduce

Install patched_1.17.jar to a maven repository and attempt to build a plugin against it using maven, you will get this error.

### Plugin list

N/A

### Paper version

This server is running Paper version git-Paper-"d76f8e0" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Reference conversation in PaperMC Discord: https://discord.com/channels/289587909051416579/555462289851940864/855272286629396512

**Comment by DenWav** [comment]
This is either an issue in `shadowJar` itself or an issue in our `shadowJar` config or both. Not related to paperweight remapping or reobf - this is a shadow relocation issue.

I'm not an expert on `shadowJar` so I don't know what the fix for this is, would appreciate if someone who knows more about it could take a look.

**Comment by kashike** [comment]
https://github.com/PaperMC/Paper/commit/4f14647c373e4b13f18a617059907a1c15af7a38

**Comment by bluelhf** [comment]
> 
> 
> [4f14647](https://github.com/PaperMC/Paper/commit/4f14647c373e4b13f18a617059907a1c15af7a38)

Seems to have broken again since this, same issue on git-Paper-196 (MC: 1.17.1)

**Comment by AlexProgrammerDE** [comment]
Seems to have broken for me too. :(

**Comment by bluelhf** [comment]
@\kashike Second time's the charm?

**Comment by electronicboy** [comment]
Please refrain from mentioning people, we already get emails for this stuff

**Comment by bluelhf** [comment]
> 
> 
> Please refrain from mentioning people, we already get emails for this stuff

Ah, my bad

**Comment by EmpathyYT** [comment]
when fix
