### ISSUE TITLE
BiomeSource API for World Generators

### ISSUE THREAD

**Issue by dfsek** [PaperMC/Paper#5865]
### Is your feature request related to a problem?

World generators currently must generate biomes during the actual chunk generation, in the `ChunkGenerator#generateChunkData` method. This completely breaks the `shouldGenerateX()` methods when custom biome generation is used, since the Vanilla things enabled by these methods are generated *before* `generateChunkData` is invoked, therefore these Vanilla items are generated where they *would* go, had the terrain been using Vanilla biomes.   

This also introduces a (very minor, though definitely worth mentioning) performance concern, since the Vanilla biome source is generating biomes, which are then immediately thrown out for the custom generator to generate and overwrite its own.

### Describe the solution you'd like.

A new interface, `io.papermc.paper.world.gen.BiomeSource`, which has a `getBiome(int x, int y, int z)` method. This would simply be a delegate to the Vanilla `WorldChunkManager` (this class is incorrectly named by Spigot, Yarn's name is `BiomeSource`, which is more accurate). This class has a single abstract method, which simply returns the biome at any coordinate.

### Describe alternatives you've considered.

Currently, chunk generators must set biomes during generation, which is not only backwards, but it also breaks `shouldGenerateX` methods to generate Vanilla things.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Machine-Maker** [comment]
[Didn't upstream implement this through this?](https://papermc.io/javadocs/paper/1.18/org/bukkit/generator/BiomeProvider.html)

**Comment by Owen1212055** [comment]
As mentioned above, it looks like this was implemented already by upstream.

If however you still feel that there is missing functionality that you would still like to see, feel free to comment and this can be reopened! 😄
