### ISSUE TITLE
[1.17] Entity-AddTo-RemoveFrom-World-Events don't work

### ISSUE THREAD

**Issue by Aurelien30000** [PaperMC/Paper#5871]
### Expected behavior

Events should work as expected and be called on every add or remove.

### Observed/Actual behavior

Remove event seems working, however, add event doesn't work at all.

### Steps/models to reproduce

```java
    @EventHandler
    public void onEntityRemove(EntityRemoveFromWorldEvent event) {
        System.out.println("bye");
    }

    @EventHandler
    public void onEntityAdd(EntityAddToWorldEvent event) {
        System.out.println("hey");
    }
```

![image](https://user-images.githubusercontent.com/43724816/122544630-48e4ec00-d02d-11eb-93e8-34393ac93ac2.png)
All entities saying _"bye"_ have been spawned and killed manually, as you can see, _"hey"_ is never sent.

### Plugin list

Only the test plugin listening to both events.

### Paper version

This server is running Paper version git-Paper-"d76f8e0" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Note: Spigot is experiencing issues getting entities on chunk load event, because this task is done _async_ according to md_5.

**Comment by jpenilla** [comment]
Unable to reproduce using the latest commit from the `dev/1.17` branch.

Test code:

```java
package io.papermc.paper.testplugin;

import com.destroystokyo.paper.event.entity.EntityAddToWorldEvent;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;
import org.checkerframework.checker.nullness.qual.NonNull;

public final class TestPlugin extends JavaPlugin implements Listener {
    private static final Logger LOGGER = LogManager.getLogger();

    @Override
    public void onEnable() {
        this.getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void entityAdd(final @NonNull EntityAddToWorldEvent event) {
        LOGGER.info("Entity added! Location: {}, Type: {}", event.getEntity().getLocation(), event.getEntityType().getKey().asString());
    }
}
```

Log: https://paste.gg/p/anonymous/a7696ed60a7c42f8abffdc45dcfb685b

**Comment by Aurelien30000** [comment]
Maybe the issue has been fixed since the last experimental build (3). Could you try, because I can't really build Paper myself. Thanks and sorry.

**Comment by Aurelien30000** [comment]
Indeed, issue can't be reproduced, thanks for your help, this is probably due to the entity-origin fix :D
