### ISSUE TITLE
Glow Squids Not Spawning

### ISSUE THREAD

**Issue by Seggan** [PaperMC/Paper#5874]
### Expected behavior

Glow squids to spawn

### Observed/Actual behavior

Checking out the new experimental build 3, I could not get a glow squid to spawn. I made sure I was in a perfectly dark area, made sure there was stone on the bottom, tped to y 200, went back down, no glow squid. I was able to replicate it in a singleplayer world on my first try. I tried 4 times in the server, no luck.

### Steps/models to reproduce

Make a perfectly dark area of water, tp to y 200, fly back down, no glow squid.

### Plugin list

none

### Paper version

[16:57:35 INFO]: Checking version, please wait...
[16:57:38 INFO]: This server is running Paper version git-Paper-"d76f8e0" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Error obtaining version information

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Using 1.17 experimental build 3

**Comment by jpenilla** [comment]
![image](https://user-images.githubusercontent.com/11360596/122631697-3e087680-d082-11eb-985a-3cccff4e4e58.png)
unable to reproduce
