### ISSUE TITLE
Block regen of MMOCore don´t work

### ISSUE THREAD

**Issue by 72Xion** [PaperMC/Paper#5875]
### Expected behavior

I was hoping that the customregen function would make that once the ore was mined after the configured seconds it would appear again.

### Observed/Actual behavior

Once the ore has been minced and replaced by the substitute, after the seconds the original does not appear again.

### Steps/models to reproduce

https://pastebin.com/wQjY7igu
1._Put on the folder plugins MMOCore 1.8.0 and MythicLib 1.1.0
2._Run the server
3._Stop the server
4._Config in MMOCore/proffessions/mining.yml the diamond_ore regen for 1000 ticks
5._Run the server
6._Mine the diamond_ore and it's replaced
7._Time passes and it´s not a diamond_ore again

### Plugin list

MMOCore 1.8.0, MMOItems 6.6.0 and MythicLib 1.1.0

### Paper version

[Server] [INFO] This server is running Paper version git-Paper-"d76f8e0" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
[Server] Error obtaining version information

Experimental #3

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
We can't provide support around premium/closed source plugins, according to that, the plugin author forgot to shade a class or something
