### ISSUE TITLE
Holographic Displays not Loading

### ISSUE THREAD

**Issue by Venthari** [PaperMC/Paper#5876]
### Expected behavior

I am not sure if this error is because it's not working with paper or if its because theres something wrong with the plugin developers code, I am reporting this in both places just to make sure.

https://pastebin.com/Jf95NGBL

My discord name is @Venthari#5755. Feel free to DM me ^-^

### Observed/Actual behavior

Short version of the error: Holographic Displays was unable to register custom entities.

### Steps/models to reproduce

Literally just put it on the server and boot it up

### Plugin list

Plugins at this time:

Advanced Achievements
Discord SRV - Build - 1.23.0
Holographic Displays

### Paper version

> paper version
[22:28:50 INFO]: Checking version, please wait...
[22:28:52 INFO]: This server is running Paper version git-Paper-"d76f8e0" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Error obtaining version information

Nothing in console after the "Error obtaining version info"

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Venthari** [comment]
Disregard, I forgot HD had a dependency that wasn't installed yet. Yay noob moment hahah

**Comment by Chew** [comment]
You good?

**Comment by Venthari** [comment]
I hit the closed button by accident sorry

**Comment by Venthari** [comment]
BAH FRIGGIN

**Comment by Venthari** [comment]
So not used to GitHUB

**Comment by DaniFoldi** [comment]
Please stop commenting multiple times per minute, hundreds of people are getting emailed/notified for no good reason.

**Comment by HexedHero** [comment]
Not a Paper issue. You need https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by electronicboy** [comment]
This is likely a paper mapping issue, no reason they should have to work around anything specifically for paper

**Comment by electro2560** [comment]
You need to update to a development build. It was fixed for a 2.4.8 release. https://github.com/filoghost/HolographicDisplays/commit/f5d37f59df1342a80169b3776e2219ce8cdd0987
https://ci.codemc.io/job/filoghost/job/HolographicDisplays

**Comment by DenWav** [comment]
Thanks, will dig into why this field mapping got lost.

**Comment by MiniDigger** [comment]
https://github.com/PaperMC/paperweight/issues/24
