### ISSUE TITLE
[1.17] Broken/incorrect query response

### ISSUE THREAD

**Issue by matthi4s** [PaperMC/Paper#5883]
### Expected behavior

Correct and valid query responses: https://wiki.vg/Query#Response_3

`\00\00\00\00splitnum\00\80\00hostname\00A Minecraft Server\00gametype\00SMP\00game_id\00MINECRAFT\00version\001.17\00plugins\00\00map\00world\00numplayers\000\00maxplayers\0020\00hostport\0025565\00hostip\00172.17.0.2\00\00player_\00\00\00`
(Example response from Vanilla)

### Observed/Actual behavior

An invalid query response, apparently there are too many null bytes around the player list:

`\00\00\00\00splitnum\00\80\00hostname\00A Minecraft Server\00gametype\00SMP\00game_id\00MINECRAFT\00version\001.17\00plugins\00Paper on 1.17-R0.1-SNAPSHOT\00map\00world\00numplayers\000\00maxplayers\0020\00hostport\0025565\00hostip\00172.17.0.2\00\00\00\00\00\00\00\00player_\00\00\00\00\00\00\00\00\00`

### Steps/models to reproduce

Run Paper without any plugins, enable the query in the server.properties and use any library/tool (e.g. https://github.com/Dinnerbone/mcstatus) to query the server.

### Plugin list

No plugins

### Paper version

Paper version git-Paper-"3d43c5e" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by matthi4s** [comment]
Apparently, some bytes are not really readable on GitHub, so I'm attaching the raw query responses here:
[Query responses.zip](https://github.com/PaperMC/Paper/files/6681240/Query.responses.zip)

Edit: Okay and here is a more readable hexdump:
Paper:
```
00000000  00 00 00 00 03 73 70 6c  69 74 6e 75 6d 00 80 00  |.....splitnum...|
00000010  68 6f 73 74 6e 61 6d 65  00 41 20 4d 69 6e 65 63  |hostname.A Minec|
00000020  72 61 66 74 20 53 65 72  76 65 72 00 67 61 6d 65  |raft Server.game|
00000030  74 79 70 65 00 53 4d 50  00 67 61 6d 65 5f 69 64  |type.SMP.game_id|
00000040  00 4d 49 4e 45 43 52 41  46 54 00 76 65 72 73 69  |.MINECRAFT.versi|
00000050  6f 6e 00 31 2e 31 37 00  70 6c 75 67 69 6e 73 00  |on.1.17.plugins.|
00000060  50 61 70 65 72 20 6f 6e  20 31 2e 31 37 2d 52 30  |Paper on 1.17-R0|
00000070  2e 31 2d 53 4e 41 50 53  48 4f 54 00 6d 61 70 00  |.1-SNAPSHOT.map.|
00000080  77 6f 72 6c 64 00 6e 75  6d 70 6c 61 79 65 72 73  |world.numplayers|
00000090  00 30 00 6d 61 78 70 6c  61 79 65 72 73 00 32 30  |.0.maxplayers.20|
000000a0  00 68 6f 73 74 70 6f 72  74 00 32 35 35 36 35 00  |.hostport.25565.|
000000b0  68 6f 73 74 69 70 00 31  37 32 2e 31 37 2e 30 2e  |hostip.172.17.0.|
000000c0  32 00 00 00 00 00 01 00  00 00 70 6c 61 79 65 72  |2.........player|
000000d0  5f 00 00 00 00 00 00 00  00 00                    |_.........|
000000da
```

Vanilla:
```
00000000  00 00 00 00 04 73 70 6c  69 74 6e 75 6d 00 80 00  |.....splitnum...|
00000010  68 6f 73 74 6e 61 6d 65  00 41 20 4d 69 6e 65 63  |hostname.A Minec|
00000020  72 61 66 74 20 53 65 72  76 65 72 00 67 61 6d 65  |raft Server.game|
00000030  74 79 70 65 00 53 4d 50  00 67 61 6d 65 5f 69 64  |type.SMP.game_id|
00000040  00 4d 49 4e 45 43 52 41  46 54 00 76 65 72 73 69  |.MINECRAFT.versi|
00000050  6f 6e 00 31 2e 31 37 00  70 6c 75 67 69 6e 73 00  |on.1.17.plugins.|
00000060  00 6d 61 70 00 77 6f 72  6c 64 00 6e 75 6d 70 6c  |.map.world.numpl|
00000070  61 79 65 72 73 00 30 00  6d 61 78 70 6c 61 79 65  |ayers.0.maxplaye|
00000080  72 73 00 32 30 00 68 6f  73 74 70 6f 72 74 00 32  |rs.20.hostport.2|
00000090  35 35 36 35 00 68 6f 73  74 69 70 00 31 37 32 2e  |5565.hostip.172.|
000000a0  31 37 2e 30 2e 32 00 00  01 70 6c 61 79 65 72 5f  |17.0.2...player_|
000000b0  00 00 00                                          |...|
000000b3
```

**Comment by kashike** [comment]
https://github.com/PaperMC/Paper/commit/ce6610254f61047ec957814426a643138f077979
