### ISSUE TITLE
[1.17] NoSuchMethodError: 'net.minecraft.core.BlockPosition net.minecraft.server.level.WorldServer.getSpawn()'

### ISSUE THREAD

**Issue by Gerrygames** [PaperMC/Paper#5884]
### Expected behavior

WorldServer.getSpawn() exists

### Observed/Actual behavior

WorldServer.getSpawn() does not exist

### Steps/models to reproduce

Use WorldServer.getSpawn()

### Plugin list

Test plugin that uses WorldServer.getSpawn()

### Paper version

git-Paper-"3d43c5e" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Spigot:
https://i.imgur.com/kWIGMjz.png
Paper:
https://i.imgur.com/ft4RaJ9.png

**Comment by qixils** [comment]
the method is now named getSharedSpawnPos (in mojmap code) and was moved up to Level in [Add hand to bucket events.patch](https://github.com/PaperMC/Paper/blob/3d43c5e50077ac7fa1e68cf7a7add0ac77768a61/patches/server/0239-Add-hand-to-bucket-events.patch)

if a plugin needs the world spawn, why not use `org.bukkit.World#getSpawnLocation`? it's literally the same method:
```java
public Location getSpawnLocation() {
    BlockPos spawn = this.world.getSharedSpawnPos();
    return new Location(this, spawn.getX(), spawn.getY(), spawn.getZ(), world.levelData.getSpawnAngle(), 0.0F); // Paper - expose world spawn angle
}
```
and i don't think plugin NMS issues are considered bugs

**Comment by Gerrygames** [comment]
I need a BlockPosition and not a Location. But I guess I will use the Bukkit method then. Thanks
