### ISSUE TITLE
Hitting a TNT Minecart does not trigger EntityKnockbackByEntityEvent

### ISSUE THREAD

**Issue by cksmith51** [PaperMC/Paper#5886]
### Expected behavior

I melee a TNT Minecart with a knockback 2 sword and expect my message listening on EntityKnockbackByEntityEvent to print out the EntityTypes of both #.getEntityType() and #.getHitBy().getEntityType(). (The event should trigger properly.)

### Observed/Actual behavior

No message is printed out because hitting a TNT Minecart (or regular minecart) does not trigger EntityKnockbackByEntityEvent. Also tested with a punch bow on mobs (does trigger) but does not trigger on the Minecart.

### Steps/models to reproduce

Listen on EntityKnockbackByEntityEvent and print a message any time event is fired with the entitytype of the hit entity. Hit a TNT Minecart or regular minecart.

### Plugin list

ApolloUHC (my custom plugin)

### Paper version

git-Paper-"3d43c5e"

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Using a knockback sword better shows the minecart getting knocked back. Spam click the minecart so that it does not break immediately.

**Comment by cksmith51** [comment]
@Chew for some reason limbo removed the tags you added, any reason why it did that?

**Comment by cksmith51** [comment]
Upon further investigation, the event only triggers for LivingEntity. I feel this should be updated to include all entities since all types of Minecart, as well as Fireballs, can take knockback from other types of entities (In these cases, players and arrows)

**Comment by KyGuy2002** [comment]
This is tagged `good first issue`, but also has `needs testing`.  Is this approved or still waiting for input.  Thanks

**Comment by ryantheleach** [comment]
@KyGuy2002 

Needs Testing: It needs someone to confirm that this is a problem, and not a user error.
good first issue: If you manage to confirm it, it's probably a relatively quick fix that will be accepted quickly if it meets code standards.

**Comment by Owen1212055** [comment]
Resolved in https://github.com/PaperMC/Paper/commit/47abd1c50c754f4c56e272d909b9a9f014cffd61
