### ISSUE TITLE
Timings bug?

### ISSUE THREAD

**Issue by NicoNekoDev** [PaperMC/Paper#589]
# Incompatibility (Bug)

### What behaviour is expected:
The server timings.
### What behaviour is observed:
`[15:43:22] [Timings paste thread/INFO]: Preparing Timings Report...
[15:43:22] [Timings paste thread/INFO]: View Timings Report: https://timings.aikar.co/?id=22b3393406504d89a857221ff1ae119a
[15:43:22] [Timings paste thread/INFO]: Timing Response: Compressed Size: 57443
Uncompressed Size: 158044
Raw Upload: https://timings.aikar.co/?id=22b3393406504d89a857221ff1ae119a&raw=1`
404 Not Found :(
### Steps/models to reproduce:
/timings on
wait for 3 minutes
/timings paste | report

### Plugin list:
Plugins (50): GroupManager, PlugMan, FastCraftPlus, PandaWire, SkinsRestorer, TagRegisterLib, Tablist, CoreProtect, Itemizer, WorldEdit, ClearLag, XrayInformer, Votifier, ProtocolLib, LibsDisguises, ChopTree3, EchoPet, SQLibrary, FeatherBoard, mcMMO, ActionAnnouncer, Tim, Vault, SimpleSit, MCMMOXPBar, ChestShop, MobArena, ChestCommands, CraftBay, OpenInv, Essentials, AnimatedNames, TreasureChest, Citizens, EssentialsChat, EssentialsSpawn, SimpleTrading, Denizen, MobCommands, CompatNoCheatPlus, NoCheatPlus, Sentinel, Builder, AuthMe, Elementals, HolographicDisplays, LeaderHeads, Shopkeepers, CombatIndicator, TouchscreenHolograms

### Paper build number:
Paper version git-Paper-1029 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by NicoNekoDev** [comment]
Aparently need 4-5 minutes to update 👎

**Comment by zachbr** [comment]
Shouldn't. Please re-open if this behavior continues.

**Comment by nicuch** [comment]
[14:55:16] [Timings paste thread/INFO]: View Timings Report: https://timings.aikar.co/?id=685f355ba4f84fbea1063a8ce9aa0d89
[14:55:16] [Timings paste thread/INFO]: Timing Response: Compressed Size: 89648
Uncompressed Size: 240882
Raw Upload: https://timings.aikar.co/?id=685f355ba4f84fbea1063a8ce9aa0d89&raw=1

Not Found
The requested URL /prod/d=685f355ba4f84fbea1063a8ce9aa0d89 was not found on this server.
Apache/2.4.7 (Ubuntu) Server at timings.aikar.co Port 443

Paper version git-Paper-1032 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by NicoNekoDev** [comment]
19.01 14:55:16 [Server] INFO Raw Upload: https://timings.aikar.co/d=685f355ba4f84fbea1063a8ce9aa0d89&raw=1
19.01 14:55:16 [Server] INFO Uncompressed Size: 240882
19.01 14:55:16 [Server] INFO Timing Response: Compressed Size: 89648
19.01 14:55:16 [Server] INFO View Timings Report: https://timings.aikar.co/d=685f355ba4f84fbea1063a8ce9aa0d89

I found the problem..
AGH!! I hate Multicraft, aparently multicraft cut off "?i" from the link :@ So is not a bug... sorry
