### ISSUE TITLE
[1.17] 

### ISSUE THREAD

**Issue by Hex27** [PaperMC/Paper#5891]
### Expected behavior

NMS method names in IRegistryCustom should be the same as in spigot

### Observed/Actual behavior

Attempting to use IRegistryCustom.d() (object method, not static) throws a MethodNotFoundException. 

### Steps/models to reproduce

My plugin attempts to call IRegistryCustom.d(). Starting the plugin is enough to reproduce the issue.
The exact lines can be found in the TerraformGenerator source code in this class: https://github.com/Hex27/TerraformGenerator/blob/master/implementation/v1_17_R1/src/main/java/org/terraform/v1_17_R1/NMSChunkGenerator.java#L190#L190

### Plugin list

TerraformGenerator 4.40

### Paper version

git-Paper-"ce66102" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Plugin was compiled with spigot and can run on spigot 1.17 with no issues.

**Comment by electronicboy** [comment]
https://github.com/PaperMC/paperweight/issues/24
