### ISSUE TITLE
[1.17] Server crashing after load world survival 1.16.5 to 1.17

### ISSUE THREAD

**Issue by LowScarlet** [PaperMC/Paper#5895]
### Stack trace

```
https://paste.gg/p/anonymous/fd1469d149f44743aa89cfecc8777ca1
```

### Plugin list

![image](https://user-images.githubusercontent.com/64282946/122663552-72388000-d1c5-11eb-89d7-4c7cda0e51a4.png)

### Actions to reproduce (if known)

1. Place world old 1.16.5 (survival) on  server
2. restart it
3. while load it server get crash with this error
![image](https://user-images.githubusercontent.com/64282946/122663426-9a73af00-d1c4-11eb-9bb4-ee732055ba0f.png)

### Paper version

[05:46:09 INFO]: Checking version, please wait...
[05:46:09 INFO]: This server is running Paper version git-Paper-"ce66102" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are 3 version(s) behind
Previous version: git-Paper-"bc4b23e" (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I already created test, if the world is not the default world `world` everything loads fine even it is not world 1.17 but 1.16.5 unless it is world default `world` 1.16.5 which will be upgraded to 1.17 it will pop up error like this.

**Comment by electronicboy** [comment]
vanilla issue

**Comment by LowScarlet** [comment]
what is vanilla issue

**Comment by boonsboos** [comment]
it's an issue in vanilla minecraft

**Comment by LowScarlet** [comment]
so how to fix it
I need this world dude

**Comment by electronicboy** [comment]
I've already explained this to you on discord multiple times and am not gonna flood peoples emails trying to get the message across again.
