### ISSUE TITLE
[Unverified] Potentially strange chunk generation in 1.17

### ISSUE THREAD

**Issue by DenWav** [PaperMC/Paper#5896]
Haven't tested this, just a report from Discord. Screenshots of generated chunk:

![Screenshot_20210620_121122](https://user-images.githubusercontent.com/1332104/122664996-49cf6800-d16a-11eb-9ae6-c14a1e1c9b3f.jpg)
![Screenshot_20210620_121204](https://user-images.githubusercontent.com/1332104/122664997-49cf6800-d16a-11eb-9dee-2f3b60345b69.jpg)

(Running on Paper server using Geyser)

Seed: -6748693764814306102
Coords: 337,77,133

Someone please  test this on a new Paper 1.17 server without plugins and verify if this is really happening in a clean state.
Not worth even attempting to debug until that is verified.

**Comment by DenWav** [comment]
Sweepy verified the provided seed does not produce these chunks on latest Paper 1.17 server with no plugins and a new world.

![unknown](https://user-images.githubusercontent.com/1332104/122665570-9b2d2680-d16d-11eb-9b58-5aca5669e036.png)

**Comment by fireheart3911** [comment]
Can reproduce, but caused by vanilla minecraft - This is not a paper bug

**Comment by Chew** [comment]
This has been going around for quite a while, likely upgrade corruption. Always take backups 😄
