### ISSUE TITLE
Nether portals in the nether [1.17]

### ISSUE THREAD

**Issue by bun20381** [PaperMC/Paper#5899]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://mcpaste.io/28df26f0c79557b0

### Plugin list

No plugins running on the server.

### Actions to reproduce (if known)

Very strange. Whenever I go into a portal in the nether (for the first time) the server crashes with these errors. The server will REFUSE to boot afterwards.

The strange part is, if I switch to spigot AFTER the crash, boot up the server, then close it again, then boot again through paper, the server will boot perfectly fine, and that particular portal will work perfectly fine.

Note: I know people have reported the same bug as this already, however, the error messages I'm getting seem to be different than what other people get.
### Paper version

![image](https://user-images.githubusercontent.com/86184646/122667681-0a147a80-d182-11eb-8af0-891eb35ab701.png)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
Please don't copy logs from multicraft, it cuts out practically all of the info in your "log"

**Comment by goinsb2000** [comment]
That's where the log starts though with the errors. Before that it's just "20.06 04:32:36 [Server] Startup Done (16.423s)! For help, type "help""

**Comment by goinsb2000** [comment]
[log.txt](https://github.com/PaperMC/Paper/files/6681973/log.txt)

**Comment by kennytv** [comment]
Paste it to https://paste.gg/ please

**Comment by bun20381** [comment]
https://paste.gg/p/anonymous/115a17e8c914454f9761d0c39b860f18

**Comment by bun20381** [comment]
Also I can confirm this happens WITH every portal created in the nether. I tested 5 different portals 1k blocks apart in the nether, and same error everytime.

https://paste.gg/p/anonymous/2c2446edeec54e7bba2b3336dbf1473f - Same errors, but with different portal.

**Comment by connorlaw2151** [comment]
This issue also occurred on a server I operate.

Same steps to reproduce, no plugins

Here is the paste bin of the associated log: https://paste.gg/p/anonymous/5369924852754ec9a71da16058da928f

**Comment by bun20381** [comment]
I would like to contribute something new as of "This server is running Paper version git-Paper-45 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0be7cdb)" and I apologize if this is useless information. However something new occurred with this version (the server still crashes, however now it will boot up fine and let me load in) but now some chunk generation corruption(I'm assuming) occurs after going through the portal in the nether. Also notice how the overworld portal is nowhere in site.
https://paste.gg/p/anonymous/0fef98b964e2450e8318f3ce4f443a79
![2021-06-23_22 07 19](https://user-images.githubusercontent.com/86184646/123191781-bfd81580-d46f-11eb-80ed-e9e75c45a2d7.png)
![2021-06-23_22 07 23](https://user-images.githubusercontent.com/86184646/123191783-c1094280-d46f-11eb-9d85-5436ab2f3738.png)
![2021-06-23_22 07 51](https://user-images.githubusercontent.com/86184646/123191787-c1a1d900-d46f-11eb-965d-118b3ef0cf21.png)

**Comment by electronicboy** [comment]
Duplicate of #5910
