### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#590]
http://pastebin.com/BT6TG2wR
Paper 1031
Plugins: 
![11](https://cloud.githubusercontent.com/assets/14358233/22173847/29906e7e-dfd7-11e6-951c-148b31203f95.png)

**Comment by FunnyCraft** [comment]
http://pastebin.com/NCZsCvax - second crash today

**Comment by zachbr** [comment]
I'm just going to close tickets that you open without the bare minimum information from now on.

**Comment by FunnyCraft** [comment]
http://pastebin.com/zDZGAivT I fell again

**Comment by FunnyCraft** [comment]
http://pastebin.com/ZjHCLyj3 this may be because of this?

**Comment by mikroskeem** [comment]
Given plugin `AdvancedAbilities` is obfuscated (as much as stack trace tells me). Nobody knows what it does exactly (except author(s))

**Comment by FunnyCraft** [comment]
but then what could it be?
