### ISSUE TITLE
Not recognized as a proper API

### ISSUE THREAD

**Issue by Chiharu-Hagihara** [PaperMC/Paper#5900]
### Expected behavior

Correctly recognized as an API

### Observed/Actual behavior

Could not resolve io.papermc.paper:paper-api:1.17-R0.1-SNAPSHOT.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

### Steps/models to reproduce

Write it in build.gradle as described in the readme.

### Plugin list

```gradle
import org.apache.tools.ant.filters.ReplaceTokens

apply plugin: 'java'
apply plugin: 'kotlin'

group = 'com.chiharuhagihara'
version = '1.0'

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url 'https://papermc.io/repo/repository/maven-public/'
    }
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.17-R0.1-SNAPSHOT'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation fileTree(dir: 'lib', include: '*.jar')
}

processResources {
    from(sourceSets.main.resources.srcDirs) {
        filter ReplaceTokens, tokens: [version: version]
    }
}

buildscript {
    ext{
        kotlin_version = '1.5.10'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

### Paper version

```gradle
repositories {
    maven { url "https://papermc.io/repo/repository/maven-public/" }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:1.17-R0.1-SNAPSHOT"
}
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
most cases of this are down to using an outdated version of java, please see the full error message it provides (dependencies need to meet the target version of your builds)

**Comment by Enaium** [comment]
sourceCompatibility = JavaVersion.VERSION_16
targetCompatibility = JavaVersion.VERSION_16

**Comment by Chew** [comment]
This is now [#paper-dev on Discord](https://discord.gg/papermc) territory.
