### ISSUE TITLE
ProtocolLib and packet duplication

### ISSUE THREAD

**Issue by ProfessorTox** [PaperMC/Paper#5901]
### Expected behavior

Using the ProtocolLib API, I am modifying per-player client-bound packets (on block change) to change the appearance of a block for a particular player. In this context, Player A should be sent the changed block as well as chat message confirming this, and Player B should observe no difference at all and should not receive a chat message. This functionality works as expected on the latest Spigot 1.16.5

### Observed/Actual behavior

On the latest Paper 1.16.5, however, sometimes when Player B interacts with the block changed for Player A (e.g., placing or destroying the block at that location), Player B is sent the changed block (unexpected behavior) and Player A is sent the chat message when this happens (expected behavior, but ideally only when Player A interacts with the block to trigger a block update and not Player B).

I assume that this broken functionality may be the result of some patch causing Paper to send duplicate block change packets or to cache client-bound packets and resend them to other players receiving a block change packet at the same location as some sort of optimization.

### Steps/models to reproduce

* [Using my test plugin](https://github.com/ProfessorTox/ProtocolLibTest), have Player A types /fakeblock, interacts with a block, and that block should turn into a redstone block for Player A and Player A only (expected behavior which is currently only observed in Spigot)
* Player A, when interacting with this new redstone-block, should receive a chat message, and the block update packet is modified to still be the redstone block on every block change packet sent to them only. However, Player B cannot see this redstone-block and instead only observes the original server-side version of the block as expected.
* On Paper, when Player B places/breaks the block at the same location as the redstone block for Player A, Player B receives a block change packet only once (interacting again sends the correct server-side block change packet) of this redstone block (unexpected behavior) and Player A still receives the chat message even though the server should not be sending them the block change packet.

### Plugin list

ProtocolLib, ProtocolLibTest

### Paper version

This server is running Paper version git-Paper-"903fa9a33" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

https://github.com/ProfessorTox/ProtocolLibTest is a link to the repo of my test plugin that can demonstrate this unexpected behavior. This same unexpected behavior was also observed in forks of Paper such as Tuinity.

**Comment by KennyTV** [comment]
I don't see how destroying/placing a block is not supposed to send block change packets to all players

**Comment by tahmid-23** [comment]
I see this problem on spigot as well
when sending the block change packet it will reuse the same packet object to send to all other players I believe (and my debugger agrees)
I don't think it should be paper/spigot's responsibility to make a new packet to send to each player just in case protocollib is being used, probably should be something protocollib does

**Comment by ProfessorTox** [comment]
> I see this problem on spigot as well
> when sending the block change packet it will reuse the same packet object to send to all other players I believe (and my debugger agrees)
> I don't think it should be paper/spigot's responsibility to make a new packet to send to each player just in case protocollib is being used, probably should be something protocollib does

I'll have to check on 1.17, but I did see that the issue was only present on Paper (and Paper forks) but _not_ Spigot. Are you using 1.17?

**Comment by tahmid-23** [comment]
retried and it definitely feels like it happens less often on spigot but it still does happen
using spigot latest build (or whatever is on getbukkit for 1.16.5), protocollib 4.7.0, and your plugin

**Comment by Chew** [comment]
> spigot latest build (or whatever is on getbukkit for 1.16.5)

I can guarantee that build is going to be astronomically behind. Please use BuildTools and build a jar there.

**Comment by tahmid-23** [comment]
same problem, even more frequent

**Comment by Owen1212055** [comment]
After being able to reproduce this behavior, I can determine that this is indeed caused by the same packet instance being reused. 
You can see in ChunkHolder,
```java
for (j = 0; j < this.changedBlocksPerSection.length; ++j) {
                ShortSet shortset = this.changedBlocksPerSection[j];

                if (shortset != null) {
                    int k = this.levelHeightAccessor.getSectionYFromSectionIndex(j);
                    SectionPos sectionposition = SectionPos.of(chunk.getPos(), k);

                    if (shortset.size() == 1) {
                        BlockPos blockposition = sectionposition.relativeToBlockPos(shortset.iterator().nextShort());
                        BlockState iblockdata = world.getBlockState(blockposition);

                        this.broadcast(new ClientboundBlockUpdatePacket(blockposition, iblockdata), false);
                        this.broadcastBlockEntityIfNeeded(world, blockposition, iblockdata);
                    } else {
                        LevelChunkSection chunksection = chunk.getSection(j);
                        ClientboundSectionBlocksUpdatePacket packetplayoutmultiblockchange = new ClientboundSectionBlocksUpdatePacket(sectionposition, shortset, chunksection, this.resendLight);

                        this.broadcast(packetplayoutmultiblockchange, false);
                        packetplayoutmultiblockchange.runUpdates((blockposition1, iblockdata1) -> {
                            this.broadcastBlockEntityIfNeeded(world, blockposition1, iblockdata1);
                        });
                    }

                    this.changedBlocksPerSection[j] = null;
                }
            }
```
when a block is broken it will broadcast block changes. Since this shares a packet when it is modified this causes the change to be applied to all players.
Because this is really only an issue if you are modifying packets like this, there is no reason to make a change like this to accommodate packet modification.
