### ISSUE TITLE
No monster is spawning in server

### ISSUE THREAD

**Issue by Kylepoops** [PaperMC/Paper#5902]
### Expected behavior

monster spawn normally in the server

### Observed/Actual behavior

on the latest build of 1.17{build 17) theres literally no monster in the world
our difficulty is hard

timings (to see configuration)
https://timings.aikar.co/?id=91a96007208948a5b7b5af629fbca518

### Steps/models to reproduce

download and run the paper 1.17 #17 build
set difficulty to hard
set time to midnight
then see if the monster are spawning

### Plugin list

Plugins (9): AllMusic*, LuckPerms, PixelMOTD*, Prism, ProtocolLib, QuantumAPI, QuantumSpawn, spark, TPAPro*              

### Paper version

1.17 Build#17

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by HexedHero** [comment]
Timings show that you have monsters on your server, check the regions tab.

**Comment by Kylepoops** [comment]
> Timings show that you have monsters on your server, check the regions tab.

There's few monster and nearly no monster
Shouldn't be the correct behaviour in hard mode

**Comment by Chew** [comment]
Boot up the world in vanilla and see if it's any different, I suppose. Could be an issue for any number of reasons but the issue is vague as is.

**Comment by Kylepoops** [comment]
> Boot up the world in vanilla and see if it's any different, I suppose. Could be an issue for any number of reasons but the issue is vague as is.

It works correctly in vanilla

**Comment by qixils** [comment]
Per your timings, you have some non-default mob spawning settings.
- bukkit.yml - monster spawn limits are set to 53 (default: 70)
- bukkit.yml - ticks per monster spawn is set to 3 (default: 1)
- spigot.yml - mob spawn range is set to 6 (default: 8)

Do you still experience this behavior with these settings on the default?

> Shouldn't be the correct behaviour in hard mode

I don't believe difficulty affects mob spawn rates.

**Comment by Jack1424** [comment]
> I don't believe difficulty affects mob spawn rates.

Difficulty doesn't change mob spawn rates (unless it's peaceful). It only changes the amount of damage that mobs do, behavior when hunger is depleted, and a few other small things.

The Minecraft Wiki explains it [here](https://minecraft.fandom.com/wiki/Difficulty).

**Comment by Kylepoops** [comment]
i just switch back to the default setting
but it's still much less monster than vanilla

**Comment by Jack1424** [comment]
I ran a server on both Paper 1.17#17 and the vanilla 1.17 server jar. I didn't touch anything except for setting the EULA to true and setting the difficulty to hard through the command in-game. There didn't seem to be any difference in the number of mobs spawned at all between the two servers.

I'd recommend looking through your plugins to see if any of them affect monster spawning, maybe try running your Paper server with no plugins.

**Comment by e-im** [comment]
I have also been unable to reproduce this. As Jack said please attempt reproduction without plugins, and beyond that provide more detailed and reproducible steps for this issue. Thank you for your report.
