### ISSUE TITLE
Aikars Timings server stall when running in background

### ISSUE THREAD

**Issue by brwnie** [PaperMC/Paper#5907]
### Stack trace

https://paste.gg/p/anonymous/8ca824fd9047418bad4f16ade85f53c4

### Plugin list

[19:50:43 INFO]: Plugins (18): AntiVPN, CF2, dynmap*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, FarmControl, FreezeBall, Harbor, LogBlock, LuckPerms, LWC, ShadowRealm, UltimateTimber, Vault, War

### Actions to reproduce (if known)

With timings enabled by default the error will eventually appear and stall the server with the shown trace, if you do /timings off the error/crash/unresponsiveness goes away.

There is no frequency or pattern to reproduce, it just happens with timings enabled. The server does eventually recover but the stall is noticed across server as lag

### Paper version

> version
[19:51:18 INFO]: Checking version, please wait...
[19:51:18 INFO]: This server is running Paper version git-Paper-"33d6b6f" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-"ed5100f" (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

/timings off works as a workaround to prevent stacktrace appearing.

**Comment by Proximyst** [comment]
Your server is slow -- simple as that. Not a bug.

**Comment by brwnie** [comment]
@Proximyst I kindly disagree if you mean in the sense of hardware or OS, it is a more than fairly spec'd server.

Closed it is, thanks for the prompt answer.

**Comment by TwoLeggedCat** [comment]
Your server stalled while calling `CraftChunk#getEntities`, which works differently in 1.17 and takes much longer. Whether that is a bug or fixable is another question that is not only related to Timings (even though Timings was calling that function).

**Comment by katekerllenevich** [comment]
Tuinity has fixed this issue in their 1.17 branch if that’s something the paper team wants to take a look at.

**Comment by kennytv** [comment]
Spigot is more than drunk and iterates over all entities in a world in Chunk#getEntities (which Timings calls for all chunks), that might be the cause here.
