### ISSUE TITLE
Bug of CHUNKS [ Paper 1.17-7 ]

### ISSUE THREAD

**Issue by Tutozuz** [PaperMC/Paper#5908]
### Expected behavior

No deberia de pasar esto.

### Observed/Actual behavior

![Captura de pantalla (470)](https://user-images.githubusercontent.com/86204246/122685179-1c64d780-d1c7-11eb-97dd-eb5da06649fa.png)
![2021-06-20_11 55 50](https://user-images.githubusercontent.com/86204246/122685183-1ec73180-d1c7-11eb-9b5d-cd12a16b9e52.png)

Los chunks derrepente dejan de cargar, luego de un tiempo el servidor se congela y empieza a espamear lo que se ve en la imagen de la consola hasta que se apaga. se ve en el bloc de notas que todavía se puede bajar, pues es el error espameandose hasta apagar el servidor

### Steps/models to reproduce

Ocurre aleatoriamente cuando se tiene que cargar un chunk

### Plugin list

No usamos otros plugins solo uno creado por nosotros mismos, no tenemos nada relacionado con los chunks

### Paper version

La actual 1.17-17

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Paper.

**Comment by aurorasmiles** [comment]
We don't speak spanish, please fill out bug reports in english
