### ISSUE TITLE
Issue with server saving world on shutdown

### ISSUE THREAD

**Issue by kennykantisiri** [PaperMC/Paper#5909]
### Full Server Log and jstack:

https://paste.gg/p/anonymous/bf1390535b584c71ae3780b2c2d2eda1

### Plugin list

There were no plugins on the server

### Actions to reproduce (if known)

Unknown.

### Paper version

This server is running Paper version git-Paper-"33d6b6f" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by BC5** [comment]
Experiencing the same issue here.
I find the probability of it getting stuck seems to increase the longer the server's been loaded? It does not consistently happen for me. And can get stuck at different points like here: 
```
[11:53:26 INFO]: Saving players
[11:53:26 INFO]: Saving worlds
[11:53:26 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[11:53:26 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[11:53:27 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
```
Where unlike in yours it gets past the overworld fine and seems to get stuck on the nether?

Got a copy of my jstack as well if having more than one helps 
I'm not on the latest build here though, as I was stopping the server to update it.
[jstack.txt](https://github.com/PaperMC/Paper/files/6686162/jstack.txt)

UPDATE: Have also experienced this issue on the latest build following a crash due to #5910

**Comment by semicolonmystery** [comment]
I have same problem and I really want to know why it is doing this.

**Comment by portigniter** [comment]
I was getting WARN messages related to Votifier a few lines up, but didn't think it would have an effect or be the culprit in my case. Removed the plugin, and it shut down normally. Repeated 5 times. Not sure if that info might help someone. Stack trace from offending WARN has been placed on [pastebin](https://pastebin.com/rXbEM3bU).

**Comment by franxyk** [comment]
Is this problem still happening?

**Comment by paul-maxime** [comment]
Also happened to one of my servers using build 17, but I couldn't manage to reproduce.
No error message at all, just stuck at "Saving chunks for level X".

I don't think plugins have anything to do with it, but just in case:
- CoreProtect, dynmap, OpenInv, WorldEdit, WorldGuard

**Comment by radekklima21** [comment]
This problem is happening to me all the time when I am shutting down the server :/ Just stuck at saving chunks

**Comment by e-im** [comment]
Please only leave a comment if you have new information to add- if you are able to reproduce only react to the initial issue and do not leave a new comment.

**Comment by PureGero** [comment]
This is probably not a good fix, but disabling com.destroystokyo.paper.io.chunk.ChunkTaskManager.cancelChunkLoad appears to have fixed it for me. I hope this helps give anyone a hint towards the cause of the issue.

```
    public void cancelChunkLoad(final int chunkX, final int chunkZ) {
+       if (true) return; // Disable cancelChunkLoad

        this.chunkLoadTasks.compute(IOUtil.getCoordinateKey(chunkX, chunkZ), (final Long keyInMap, final ChunkLoadTask valueInMap) -> {
            if (valueInMap == null) {
                return null;
            }

            if (valueInMap.cancelled) {
                PaperFileIOThread.LOGGER.warn("Task " + valueInMap.toString() + " is already cancelled!");
            }
            valueInMap.cancelled = true;
            if (valueInMap.cancel()) {
                return null;
            }

            return valueInMap;
        });
    }```

**Comment by TwoLeggedCat** [comment]
This information is likely useless in light of the comment above, but I will note that I just encountered the same problem when loading 1.17 chunks on 1.16.5 (accidentally), meaning it's probably not a change in the actual shut down process causing it.
