### ISSUE TITLE
[1.17] Chunk loading/saving hangup

### ISSUE THREAD

**Issue by Tutozuz** [PaperMC/Paper#5910]
### Expected behavior

should not happen

### Observed/Actual behavior

The fragments suddenly stop loading, after a while the server freezes and begins to render what is seen in the console image until it shuts down. In the notepad you can see that it can still go down, as the error spams until the server is shut down.

![2021-06-20_11 55 50](https://user-images.githubusercontent.com/86204246/122685343-f3911200-d1c7-11eb-992a-4bd0b7c840a9.png)

![Captura de pantalla (470)](https://user-images.githubusercontent.com/86204246/122685345-f55ad580-d1c7-11eb-97d0-52abb79c60b1.png)

### Steps/models to reproduce

There are no steps to do this, it is random

### Plugin list

we use our own plugin, it doesn't touch chunks at all

### Paper version

1.17-17 paper

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by theconezone** [comment]
Had this happen twice last night during testing. Thought it was a plugin issue. Player joined and server deadlocked.

I have not been able to reproduce it. I figured it was a plugin issue.

[2021-06-19-33.log](https://github.com/PaperMC/Paper/files/6682964/2021-06-19-33.log)
[2021-06-19-34.log](https://github.com/PaperMC/Paper/files/6682965/2021-06-19-34.log)

**Comment by radekklima21** [comment]
I have the same issue on my both servers. I dont know if it a plugin issue (but this is happening sometimes when someone type /home - so if someone teleports)

https://paste.gg/p/anonymous/19daeefde02f479ea56ef9971d49a98a

**Comment by theconezone** [comment]
Had this happen twice last night during testing. Player joined and server deadlocked.

I have not been able to reproduce it. I figured it was a plugin issue.

[2021-06-19-34.log](https://github.com/PaperMC/Paper/files/6682971/2021-06-19-34.log)
[2021-06-19-33.log](https://github.com/PaperMC/Paper/files/6682972/2021-06-19-33.log)

Has not occurred with spigot.

**Comment by KioProject123** [comment]
+1
I have the same issue
everything is normal in spigot, but not in paper

**Comment by maxspeed3006** [comment]
Same issue here, plugin list: https://pastebin.com/URB7vMcy

**Comment by Tutozuz** [comment]
we hope that this bug will be fixes

**Comment by Tutozuz** [comment]
I just upgraded my server to 1.17-19 i expect that this bug don't reappear 

i will be reporting

**Comment by electronicboy** [comment]
We know this is an issue, we do not need this ticket to be bumped with useless info

**Comment by Tutozuz** [comment]
[2021-06-20-7.log](https://github.com/PaperMC/Paper/files/6683281/2021-06-20-7.log)

We use world-edit

**Comment by BillyGalbreath** [comment]
I found a quick way to reproduce this issue.

Steps to reproduce:
1) Install [Pl3xMap build 139](https://ci.pl3x.net/job/Pl3xMap/139/)
2) Start server
3) Fly around to generate some chunks (the more the better)
4) Run /map fullrender world
5) Wait for it to stall out at 0 CPS
6) Run /map cancelrender world
7) Run /save-all flush
8) Wait for watchdog

Bonus that after watchdog kills it after 60 seconds is it tries to save chunks again and just stalls indefinitely. You'll have to ctrl+c to kill it.

latest.log:
https://paste.gg/p/anonymous/fa059fcd96c041049296152e35c629bb
