### ISSUE TITLE
Disappearing Armor - Books and Quills Issue

### ISSUE THREAD

**Issue by captainbboy** [PaperMC/Paper#5911]
### Expected behavior

Being able to use copy/paste text into a book and not have your armor removed.

### Observed/Actual behavior

Whenever a player copy/pastes text from book and quills ingame, it replaces an armor/offhand/crafting slot and deletes the item that was previously there.

### Steps/models to reproduce

Take a book and quill, copy/paste text into it, then close it. It force places a book and quill into an armor slot, your offhand slot, or your crafting slot and deletes the item.

https://gyazo.com/732c400ec714c7eeb9477205f468e72d

### Plugin list

CoreProtect, DiscordSRV, floodgate, LuckPerms, ProtocolLib, StaffPlus, Themis

### Paper version

[19:05:59 INFO]: This server is running Paper version git-Paper-"33d6b6f" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-"ce66102" (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by TechnicallyCoded** [comment]
We discovered this bug too. I do want to add that is not required to copy paste text into the book for this glitch to work. Just type something new into the book and click done. You now have a duplicated book in your inventory.

This also heavily depends on which slot was used to open the book from. For example: selecting slot 6-9 places the duplicated book in your armor slots whereas slots 1-5 places it in your crafting inventory. 

If you click the item out of your armor, the book in your hand will disappear. If you take the item out of your crafting output slot the book doesn't instantly disappear but needs you to place the boo inside your inventory for it to seemingly update and remove the other one. Logging out without touching the duped book will make it a  permanent item (aka you may now move the book around without the other item disappearing). On the other hand, pulling the book out of the crafting output slot and dropping on the floor bypasses whatever check is removing the duplicated items. The duped books can now be picked up and handled without problem.

Thanks for the great work and I hope this helped!
