### ISSUE TITLE
No mobs spawning

### ISSUE THREAD

**Issue by VirgilGunder** [PaperMC/Paper#5912]
### Expected behavior

Mobs spawning

### Observed/Actual behavior

No mobs spawning

### Steps/models to reproduce

Installed paper, started the server and saw no mobs at all

### Plugin list

Banmanager, bStats, Coreprotect, FInvsee, SuperVanis, WorldEdit, Worldguard

### Paper version

This server is running Paper version git-Paper-"33d6b6f" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-"558be4b" (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

https://timings.aikar.co/?id=cb5ac57877f843d0911ff91efa6830b6

**Comment by e-im** [comment]
Duplicate of #5902
