### ISSUE TITLE
Upgrading Chunk Errrors

### ISSUE THREAD

**Issue by ColdIce1605** [PaperMC/Paper#5914]
### Expected behavior

No Chunk Errors reported.

### Observed/Actual behavior

Errors when upgrading chunks.
https://pastebin.com/ci5uchR0

### Steps/models to reproduce

Load a World from Spigot.(Was a 1.16 world before moving to spigot 1.17

### Plugin list

AutoSaveWorlds
images
LocketteX
LuckPerms
NomobGriefing
RegionClaim
SetHomes
SimpleTPA
SinglePlayerSleep
WorldEdit
worldguard

### Paper version

paper 1.17-18

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
This is likely an issue with your region files being inconsistent, unless somebody can confirm otherwise, this is not an issue with paper but your world
