### ISSUE TITLE
Shulker not teleporting to the nether when opening into a portal block

### ISSUE THREAD

**Issue by Rayouin** [PaperMC/Paper#5915]
### Expected behavior

When the top of a Shulker mob is facing directly towards a portal block, it gets teleportet to the nether as soon as it opens. While opening, the hitbox of the Shulker is expanding to the next block (e.g. the nether portal block).

### Observed/Actual behavior

the hitbox is crossing the portal, but no teleporting happens. 

### Steps/models to reproduce

![makemyshulkerfarmpossibleplz](https://user-images.githubusercontent.com/18271519/122687522-231b3b00-d217-11eb-8566-527e896e58de.png)

### Plugin list

no plugins running on the server

### Paper version

Paper-c89ec40 (MC: 1.17 - Build 18)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by charredvenge** [comment]
I'm also experiencing the same issue. I tested on a Paper 1.17, Vanilla 1.17, and Paper 1.16 (build 778) server with a copy of the same world (to make sure it isn't an issue with portal linking) and the portals worked properly on both Vanilla 1.17 and Paper 1.16.

**Comment by stromne** [comment]
![2021-06-26_11 29 19](https://user-images.githubusercontent.com/86529380/123519730-b4087100-d672-11eb-8d8e-9abe53b77957.png)

I have also confirmed this issue

**Comment by kayvanbree** [comment]
I can confirm the same problem as #5967 with the Shulker farm design of Ray Works.

**Comment by Machine-Maker** [comment]
~~I can also reproduce this on `3162-Spigot-f773da8-b121d3b (MC: 1.17)`~~

Actually ignore me, its because I didn't go though the portal first. They go through just fine once its generated.

**Comment by lynxplay** [comment]
I am trying to recreate the expected result on vanilla, yet I am failing to get the shulker to teleport.
The nether is generated.
Can one of the reporters ensure that this works in vanilla 1.17?

**Comment by Machine-Maker** [comment]
Its more than the nether being generated, the portals have to be linked. It works fine in the latest spigot verison.

It also works fine in Paper with that patch removed all together, so the issue is probably there.

**Comment by lynxplay** [comment]
My portals are linked, I created a world just for that 👍 other entities move through it perfectly fine. So do shulkers when spawned directly in the portal.

**Comment by Machine-Maker** [comment]
Yep, just replicated the correct behavior on completely vanilla server.

**Comment by charredvenge** [comment]
I was able to get the shulker to teleport on a vanilla server. Make sure that you are placing the shulker such that its shell would open and poke through the portal.

**Comment by Machine-Maker** [comment]
Ok, pretty sure I found the actual issue.

**Comment by lynxplay** [comment]
Its the bounding box reuse @Machine-Maker, I had a PR open for that #6010, yet I fail to actually get my shulkers to teleport.
Can you test it on my PR ?

**Comment by stromne** [comment]
Yes, i can confirm on vanilla.  Here is a video of my farm design in vanilla 1.17: https://youtu.be/CPNwlkkH6zU

**Comment by Machine-Maker** [comment]
@lynxplay your fix does in fact work. But I'm not 100% sure its the right way to fix it.

**Comment by lynxplay** [comment]
Thank you for testing @Machine-Maker ❤️ I'll reopen the PR and reviews/suggestions may go there.
At least we have identified the issue.

**Comment by stromne** [comment]
sorry if this is a newb question, but how do we know what version this goes into?  Does the commit mean it's in the latest version (53)?

**Comment by TwoLeggedCat** [comment]
> sorry if this is a newb question, but how do we know what version this goes into? Does the commit mean it's in the latest version (53)?

That commit was not to Paper, but to lynxplay's fork of Paper, which they used on open [a pull request](https://github.com/PaperMC/Paper/pull/6010) to fix the issue (or, fix some related problems). It is not in Paper yet.

**Comment by lynxplay** [comment]
Yeah this issue will be closed once a fix was merged into paper 👍 so just wait for this to close and you should be good.

**Comment by stromne** [comment]
any eta on this ticket?

**Comment by Chew** [comment]
1) not a ticket
2) we have an open PR regarding this which you should be able to track _silently_ unless you have any feedback or suggestions regarding it

**Comment by stromne** [comment]
where can i find a PR?

**Comment by benwoo1110** [comment]
https://github.com/PaperMC/Paper/pull/6010

**Comment by stromne** [comment]
thanks
