### ISSUE TITLE
Entity to have a setGlowingColor method

### ISSUE THREAD

**Issue by Stellrow** [PaperMC/Paper#5916]
### Is your feature request related to a problem?

It's increasingly harder to change the glowing color for a entity without the hard use of nms

### Describe the solution you'd like.

Having a simple method for Entity to change the glow color directly

### Describe alternatives you've considered.

An current alternative is to either use nms with packets or the use of scoreboards(team with specific color wich will change the glow color) wich also needs to use packets to not mess with scoreboards plugins.
Also i noticed Spigot have a parameter for Color when creating a potiontype,however it seems it got removed in newer versions

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Owen1212055** [comment]
NMS? Bukkit has an entire api for scoreboard teams and such.

**Comment by Stellrow** [comment]
> NMS? Bukkit has an entire api for scoreboard teams and such.

` or the use of scoreboards(team with specific color wich will change the glow color) wich also needs to use packets to not mess with scoreboards plugins`

You can use bukkit api for it,however you are going to really affect scoreboards plugins

**Comment by Owen1212055** [comment]
In what ways would scoreboard plugins effect using the bukkit api? Would it be spam applying the same scoreboard?

**Comment by electronicboy** [comment]
Closing, issue is inactive and generally, I don't think that this is even possible without scoreboards
