### ISSUE TITLE
Right-clicking block with stick or other item causes PlayerInteractEvent to fire twice, both times with the same hand

### ISSUE THREAD

**Issue by HoshiKurama** [PaperMC/Paper#5918]
### Expected behavior

Only one PlayerInteractEvent for the main hand

### Observed/Actual behavior

two events fired for the main hand

### Steps/models to reproduce

* Download my small test plugin at https://www.mediafire.com/file/im2u50ymnf450of/EventFiresTwice-1.0-SNAPSHOT.jar/file
* Once the server is started, hold a stick.
* Right click the air. Notice that Console only fires one event of type HAND.
* Right click a block with the stick. Notice that Console fires two events of type HAND.

### Plugin list

Only my small test plugin. Here is the entire code:
```kotlin
class ExamplePlugin : JavaPlugin(), Listener {

    override fun onEnable() {
        server.pluginManager.registerEvents(this, this)
    }

    @EventHandler
    fun onPlayerInteract(event: PlayerInteractEvent) {
        println("Event Fired! \n Action type: ${event.action.name} \n Hand: ${event.hand!!.name}")
    }
}
```

### Paper version

This server is running Paper version git-Paper-"e31ad11" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-"bc4b23e" (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
This has been a long standing issue of which we have 0 control over as its down to how the client sends packets to the server
