### ISSUE TITLE
java.lang.IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by mikroskeem** [PaperMC/Paper#592]
Basically I imported world with Multiverse-Core (world was generated with CleanroomGenerator, and of course it was imported with appropriate configuration) and got this [error](https://paste.nightsnack.cf/raw/zumuwovixa).  
Server crashes after that.

Paper version: `git-Paper-"2a16ff90"`  
Multiverse-Core Version: `2.5-b699` (maybe helps)

// EDIT: also happens on build 1040

**Comment by Brokkonaut** [comment]
this happens when the default chunk generator tries to work with a world where somewhere the highest block is 0...

`int k = random.nextInt(world.getHighestBlockYAt(blockposition.a(i, 0, j)).getY() * 2);`
