### ISSUE TITLE
[1.17] In ChunkLoadEvent event.getChunk().getEntities() is always empty and there is no replacement

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#5921]
### Expected behavior

In 1.16.5 in the ChunkLoadEvent event.getChunk().getEntities() did contain the loaded entities. This is required for plugins that modify the entities in some way after loading them (in my use case modify the AI).

If this is no longer possible in 1.17, there should be some replacement when the Entities are available (something like a ChunkLoadEntitiesEvent?)

### Observed/Actual behavior

There is no way to get the entities from the loaded chunk in 1.17.

### Steps/models to reproduce

Have an event listener for ChunkLoadEvent and query the entities.

### Plugin list

just a test plugin to see the loaded entities

### Paper version

This server is running Paper version git-Paper-"e31ad11" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Paper.

**Comment by qixils** [comment]
duplicate of #5872 i believe?

**Comment by Brokkonaut** [comment]
> duplicate of #5872 i believe?

At least it is probably related. That issue there is in onEnable, I had the issue in ChunkLoadEvent but both might have the same cause.

**Comment by qixils** [comment]
aye you're right, i'd imagine entities should be present on chunk load

**Comment by electronicboy** [comment]
it's the exact same issue, vanilla loads entities separately

**Comment by lynxplay** [comment]
Also duplicate of https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/866/overview to some degree
