### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by TheFruxz** [PaperMC/Paper#5922]
### Expected behavior

Shows the current state of the way of contributing and which commands I need to build and publish code

### Observed/Actual behavior

I think, it shows the 'old' way, but from now on paper uses grade to do that stuff instead of the `paper` file. but the CONTRIBUTING.md file is currently not up to date, which can be confusing

### Steps/models to reproduce

- turn on the browser
- insert "GitHub.com/PaperMC/Paper/"
- Click 'CONTRIBUTING.md'
- Read

### Paper version

Commit: `321ddfea3c18d17e01c571f1504eaeb2e693e053 `

### Info

Issue in the repo, not in the server;
No offense meant, I think this was just overlooked

**Comment by qixils** [comment]
Here's the update from the [Discord](https://discord.gg/papermc)

![image](https://user-images.githubusercontent.com/13265322/122699415-5fe73200-d217-11eb-9b46-494f6695b780.png)
