### ISSUE TITLE
Session lock on Server

### ISSUE THREAD

**Issue by AaronUltima** [PaperMC/Paper#5928]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
1.06 09:48:37 [Server] INFO System Info: Java 16 (Java HotSpot(TM) 64-Bit Server VM 16.0.1+9-24) Host: Linux 4.18.0-240.1.1.el8_3.x86_64 (amd64)
21.06 09:48:37 [Server] INFO Loading libraries, please wait...
21.06 09:48:46 [Multicraft] Received stop command
21.06 09:48:46 [Server] INFO 2021-06-21 09:48:46,101 main WARN Advanced terminal features are not available in this environment
21.06 09:48:50 [Server] INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
21.06 09:48:50 [Server] FATAL Failed to start the minecraft server
21.06 09:48:50 [Server] INFO net.minecraft.util.SessionLock$ExceptionWorldConflict: /./world/session.lock: already locked (possibly by other Minecraft instance?)
21.06 09:48:50 [Server] INFO at net.minecraft.util.SessionLock$ExceptionWorldConflict.a(SessionLock.java:98) ~[patched_1.17.jar:git-Paper-"6dfe049"]
21.06 09:48:50 [Server] INFO at net.minecraft.util.SessionLock.a(SessionLock.java:44) ~[patched_1.17.jar:git-Paper-"6dfe049"]
21.06 09:48:50 [Server] INFO at net.minecraft.world.level.storage.Convertable$ConversionSession.<init>(Convertable.java:330) ~[patched_1.17.jar:git-Paper-"6dfe049"]
21.06 09:48:50 [Server] INFO at net.minecraft.world.level.storage.Convertable.c(Convertable.java:300) ~[patched_1.17.jar:git-Paper-"6dfe049"]
21.06 09:48:50 [Server] INFO at net.minecraft.server.Main.main(Main.java:151) ~[patched_1.17.jar:git-Paper-"6dfe049"]
21.06 09:48:50 [Server] INFO at org.bukkit.craftbukkit.Main.main(Main.java:293) ~[patched_1.17.jar:git-Paper-"6dfe049"]
21.06 09:48:50 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
21.06 09:48:50 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
21.06 09:48:50 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
21.06 09:48:50 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
21.06 09:48:50 [Server] INFO at io.papermc.paperclip.Paperclip.main(Paperclip.java:49) ~[java16.jar:?]
21.06 09:48:51 [Multicraft] Server shut down (stopping)
21.06 09:48:51 [Multicraft] Server stopped

### Plugin list

21.06 09:54:31 [Server] INFO Plugins (24): AntiWorldFly, BanManager, BetterRTP, CoreProtect, CratesPlus, DiamondHunter*, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, LWC, MVdWPlaceholderAPI*, PlaceholderAPI, Rankup, Statz, TAB, TradeShop, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, XPFlyX*

### Actions to reproduce (if known)

If players are entering new generated chunks in the overworld, nether for 1.17 or in the end the server crashes and becomes session locked. Meaning it can not be restarted unless the sesson.lock file is removed from the word,nether, end folders. 

### Paper version

21.06 09:55:10 [Server] INFO This server is running Paper version git-Paper-"6dfe049" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
21.06 09:55:10 [Server] INFO You are 1 version(s) behind
21.06 09:55:10 [Server] INFO Previous version: git-Paper-"33d6b6f" (MC: 1.17)

Used also the newest version and it still keeps crashing the server. 

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
> net.minecraft.util.SessionLock$ExceptionWorldConflict: /./world/session.lock: already locked (possibly by other Minecraft instance?)

another process on the system is locking the file

**Comment by ScuroK** [comment]
i have the same issue and i dont find a way to fix it. when i delete all session.lock files it works. but if i restart the server the problem returns :/ any help?

**Comment by e-im** [comment]
The issue tracker isn't the place for support. Please come by the #paper-help channel of our [discord](https://discord.gg/papermc) or irc.
