### ISSUE TITLE
/help not working properly? (Narrowing down the issue.)

### ISSUE THREAD

**Issue by Linebeck** [PaperMC/Paper#593]
So, I have set this customtext #help with a custom message. I added the alias in commands.yml, and made /help ---> customtext #help. So the problem is, recently it has been reverting to Essentials /help. I thought that commands.yml auto overrides everything by default. I reached out to the people developing EssentialsX to see if they knew a cause. I also, think it is odd that /icanhasbukkit works no problem, and other commands in commands.yml. If you could help me narrow this down or provide an explanation that would be great!

Thanks <3

(I am using the latest build that was released on Jan 23rd, 2017.)

**Comment by TNTUP** [comment]
Hey did you tried

help:
- customtext help

? 

Remove the #, not needed. the # is considered as a comment in YAML.

Also, Essentials lets you custom the help.txt file, no need to use customtext for it ^^ :P

**Comment by electronicboy** [comment]
Essentials command registration is a mess, You probably wanna add a small dummy plugin or something that just registers the help command so essentials doesn't hook it

**Comment by aikar** [comment]
Since this appears to be a request for help and not a paper bug, please join IRC if this is still an issue for you
