### ISSUE TITLE
Configurable keepalive interval

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5930]
### Is your feature request related to a problem?

I want more accurate ping, keepalive every 15 seconds (hard coded) isn't accurate enough for my needs, it should be configurable.

### Describe the solution you'd like.

Paper config option keepalive interval or system property

### Describe alternatives you've considered.

Sending keepalive packets myself and using protocollib to stop the reply before it kicks the player for invalid id

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by kennytv** [comment]
1.17 has ping packets which are definitely better than changing the keepalive interval here, so I would suggest Paper adding API to send those with a unified counter.

**Comment by Janmm14** [comment]
The Ping/Pong packet is processed synchroniously on the client, while Keepalive is processed asnychroniously.
Using Ping/Pong packets would incorporate client lag into the ping measurement.

**Comment by Chew** [comment]
It already is, see the big ol headache-causing paragraph: https://github.com/PaperMC/Paper/issues/895#issuecomment-372175216

**Comment by electronicboy** [comment]
interval is not, timeout is, but this will likely come when I care to redo the networking and then the keepalive stuff, mainly other key goals with that but debating on making it configurable 🤷‍♂️
