### ISSUE TITLE
Cannot invoke "java.util.UUID.getMostSignificantBits()" because "uuid" is null

### ISSUE THREAD

**Issue by masmc05** [PaperMC/Paper#5931]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://paste.gg/p/anonymous/d9bb00462a0e485688c312eb89e4ef1d

### Plugin list

LuckPerms, Multiverse-Core, SkinsRestorer, VoidGenerator

### Actions to reproduce (if known)

it is spaming with that stacktrace, /save-all to force this error

### Paper version

This server is running Paper version git-Paper-"47605b8" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-649 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by masmc05** [comment]
also it is thrown when disconecting

**Comment by MiniDigger** [comment]
this smells like an issue with offline mode

**Comment by masmc05** [comment]
> this smells like an issue with offline mode

online mode is true

**Comment by masmc05** [comment]
updated the version and it looks like the stacktrace changed 
This server is running Paper version git-Paper-"ae95311" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-"47605b8" (MC: 1.17)
https://paste.gg/p/anonymous/af1d1462a3c44b1f99c24b0410fbe217

**Comment by masmc05** [comment]
I looked with debug, when disconecting
https://paste.gg/p/anonymous/e83e8b2572c94941917ce114fc2c1457
the problem is that the origin isn't null, but the originWorld is null, the code checks only origin and works with both of them
Entity.class :
![image](https://user-images.githubusercontent.com/63639746/122909832-43094680-d35e-11eb-9ed9-e3fd8ea8dcbf.png)
