### ISSUE TITLE
ArmorStands teleporting at an offset to their teleportation location

### ISSUE THREAD

**Issue by OakLoaf** [PaperMC/Paper#5939]
### Expected behavior

Armorstands to teleport to a location in relation to the player

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/55620516/122816760-0b06f280-d2cf-11eb-9784-75f375a87cb9.png)

Armorstands appear to be at an offset location to the location they are being teleported to. In the case of this image the armorstand (circled in red) is meant to be under the name tag armorstand (circled in blue). The name tag armorstand is teleporting to the main armorstand meaning it should always be above it (meaning this could potentially just be a visual issue that all players can see). This was all functioning perfectly in previous versions but in 1.17 has started causing this issue. (NOTE: The error does not always occur and seems to be relatively unpredictable as to when it will start being out of line with the  player.)

### Steps/models to reproduce

The two plugins which I have seen effected by this are TAB and ESFollowers (a private plugin of mine) both which teleport armorstands in relation to the player. TAB which uses armorstand packets above the player's head to allow for multiple lines of information under their name. There are never any errors produced by this and it seems to be relatively random as to when this will occur so I don't quite know what else to offer to help reproduce this.

### Plugin list

ActivityRewarder, AncientGates, ArcherPraise, ArmorStandTools, BetterRTP, BossShopPro, Citizens, CitizensHologram*, ClientFPS, DeluxeChat, DeluxeTags, EnchantedBosses, EpicRename, ESFollowers, ESMusicRegions, ESParticles, Essentials, EssentialsSpawn, ESStaffChat-Satellite, ESTrading, ESWelcome, GSit, HolographicDisplays, IllegalStack, LootArrows, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI*, NoteBlockAPI, Notes, PlaceholderAPI, PlayerPoints, PlayerVaults, ProtocolLib, ReportBook, SkillsLibrary, SkyblockNPCs, StructureVoidViewer, Superheroes2, SuperheroesPlusUltra, SuperheroesWorldGuard, TAB, Towny, TownySkillsLibraryAddon, Vault, VoidSpawn, VoidWorld, VotingPlugin, WorldEdit, WorldGuard, WorldGuard-Towny*, WorldGuardEvents

### Paper version

[21:30:40 INFO]: This server is running Paper version git-Paper-"22280c5" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-"33d6b6f" (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by IHaxU** [comment]
I also noticed that armorstands teleport to a difference place than where it is without decimals if u add a .0 to the end

**Comment by e-im** [comment]
I haven't been able to reproduce this, however as you said it has been random for you as to whether it happens or not. Do you happen to have any client mods and have you been able to reproduce this without them?

For @IHaxU - that is expected behaviour.

**Comment by SnickoDeadMC** [comment]
Not sure if this is related but I had been calling getNearbyEntities() at a location to get specific armorstands at locations in 1.16, but when I updated to 1.17 all the locations are saying there are 0 nearby entities.

**Comment by Owen1212055** [comment]
"The two plugins which I have seen effected by this are TAB and ESFollowers (a private plugin of mine) both which teleport armorstands in relation to the player."

This would point towards it being  https://github.com/PaperMC/Paper/pull/7183

Can you check just to make sure that you're teleporting this entity on the first tick of them being spawned?
