### ISSUE TITLE
Error loading the carved world

### ISSUE THREAD

**Issue by Shizuri23** [PaperMC/Paper#5946]
### Expected behavior

Load datapacks normally

### Observed/Actual behavior

> [23:32:26 ERROR]: Feature: Not a JSON object: "wythers:generic/patch_stones_east_3"; Not a JSON object: "wythers:generic/patch_stones_south_2"; Not a JSON object: "minecraft:vines"; Not a JSON object: "minecraft:patch_melon"; Not a JSON object: "minecraft:spring_water"; Not a JSON object: "wythers:desert/oasis_patch_sugar_cane"; Not a JSON object: "minecraft:red_mushroom_normal"; Not a JSON object: "minecraft:brown_mushroom_normal"; Not a JSON object: "minecraft:red_mushroom_swamp"; Not a JSON object: "minecraft:brown_mushroom_swamp"; Not a JSON object: "minecraft:patch_waterlilly"; Not a JSON object: "minecraft:seagrass_swamp"; Not a JSON object: "minecraft:seagrass_swamp"; Not a JSON object: "minecraft:patch_grass_jungle"; Not a JSON object: "wythers:generic/flower_lily_of_the_valley"; Not a JSON object: "wythers:desert/oasis_reeds"; Not a JSON object: "wythers:desert/oasis_vegetation"; Not a JSON object: "minecraft:classic_vines_cave_feature"; Not a JSON object: "minecraft:lush_caves_vegetation"; Not a JSON object: "minecraft:lush_caves_clay"; Not a JSON object: "minecraft:cave_vines"; Not a JSON object: "minecraft:lush_caves_ceiling_vegetation"; Not a JSON object: "minecraft:glow_lichen"
> [23:32:26 ERROR]: Feature: Not a JSON object: "minecraft:seagrass_swamp"; Not a JSON object: "minecraft:vines"; Not a JSON object: "minecraft:patch_melon"; Not a JSON object: "minecraft:spring_water"; Not a JSON object: "wythers:desert/oasis_patch_sugar_cane"; Not a JSON object: "minecraft:red_mushroom_normal"; Not a JSON object: "minecraft:brown_mushroom_normal"; Not a JSON object: "minecraft:patch_waterlilly"; Not a JSON object: "minecraft:patch_grass_jungle"; Not a JSON object: "wythers:generic/flower_lily_of_the_valley"; Not a JSON object: "wythers:jungle/edge_vegetation"; Not a JSON object: "minecraft:glow_lichen"

### Steps/models to reproduce

Load CavesAndCliffsPreview datapacks

### Plugin list

no plugins

### Paper version

1.17

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by MiniDigger** [comment]
isnt that the one thats fixed with 1.17.1?

**Comment by electronicboy** [comment]
outdated datapack? That error looks like the json in the pack itself is in a way which the game itself doesn't like, pretty sure that there's been multiple versions of the preview pack posted of which all aren't compatible with each other

**Comment by electronicboy** [comment]
closing, this is likely either an issue with the version of the datapack you have installed or something else, many others are using the packet without any issues just fine, and there have been a few cases of people seeing similar errors due to outdated packs before
