### ISSUE TITLE
CONTRIBUTING.md is outdated

### ISSUE THREAD

**Issue by Janmm14** [PaperMC/Paper#5949]
It still wants you to use ./paper tool although you changed to gradle

**Comment by Chew** [comment]
No type: documentation label? huh.

**Comment by MiniDigger** [comment]
now there is :)

**Comment by qixils** [comment]
~~Duplicate of #5922? :P~~ well, i suppose this is the main issue now haha

**Comment by TheFruxz** [comment]
#5958

**Comment by NoahvdAa** [comment]
Fixed in #6497?
