### ISSUE TITLE
Exception Ticking World - Crash

### ISSUE THREAD

**Issue by Faxed** [PaperMC/Paper#595]
**Issue Description:**
I was going to report this a bit ago, however, I wanted to test a few more avenues. Our server is presently unable to use versions past **1026**. 

We updated to **1026** and left it a short period before updating again (due to the "THIS IS OUTDATED" thing). As soon as we did, we found that each day the server suffered a minimum of one crash - We'd usually put this down to a plugin, but at the time we hadn't updated any plugins as we'd been working off of the main server and on a test server - So the only change we'd made was indeed to the server version. 

As a test, we tried going forward a version and trying different ones past **1026**, however it still yielded a crash. We backdated to **1026** and we received no crashes for the four days we left it going - I then updated to **1043** and within twenty four hours, the server crashed for the same reason. 

The main reason I've pointed out that we'd updated no plugins is down to the fact that the server hadn't crashed once since it had opened - It wasn't until we updated PaperSpigot that we ran into issues. 

**Plugin List:**
http://pastebin.com/yJa7vTYE

**Crash Logs:**
Whilst we have one for every day, I deleted most of them due to them mainly just being a repetition. 
http://pastebin.com/ZF4uXK3Q - 19th January 2017
http://pastebin.com/a8cSbaFf - 22nd January 2017
http://pastebin.com/1cYBW2dx - 29th January 2017

**Log File:**
http://pastebin.com/2kF17m7v

**Comment by zachbr** [comment]
Only have time to take a quick look at the moment, but I don't see anything blatant. Will try and look again this weekend when I have more time on my hands.

**Comment by SecretlyJealous** [comment]
Here's the crash report I got: https://hastebin.com/lobowadeve.php
Build: 1055
Logs before the crash seem interesting though: https://hastebin.com/manidorapa.md

**Comment by zachbr** [comment]
If this still occurs on 1.12.2 we'll take another look at it.
