### ISSUE TITLE
PlayerInteractEvent not called right clicking without item in hand

### ISSUE THREAD

**Issue by robog-two** [PaperMC/Paper#5951]
### Expected behavior

When you right click air, a PlayerInteractEvent should be called.

### Observed/Actual behavior

PlayerInteractEvent is _only_ called when you right click air with an item in your hand.

### Steps/models to reproduce

Write a simple plugin that handles PlayerInteractEvent, and send the player a message whenever the event is fired. Log on to the server and right click into the air with and without an item.

With item in hand (right click)
![image](https://user-images.githubusercontent.com/77205106/122970758-e6a12980-d353-11eb-886b-ecc371e5fd6b.png)
Without item in hand (right click)
![image](https://user-images.githubusercontent.com/77205106/122970817-f587dc00-d353-11eb-9b0b-ea8305a2ed86.png)

### Plugin list

PlayerInteractTester - [Source code](https://github.com/robog-two/PlayerInteractTester)

### Paper version

`Checking version, please wait...
This server is running Paper version git-Paper-"f110140" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version`

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

[This forum post](https://bukkit.org/threads/playerinteractevent-is-right-click-air-with-not-item-in-hand-not-work-on-purpose.289914/) might be helpful, though it seems outdated.
I think that this *may* be intended behavior, but it still seems like a bug, since event.getItem() is annotated as Nullable, so why not let it be null?
Also, I'm not sure if the client even sends any packets when you right click no item in hand, but it probably does if a check like that exists in the old bukkit code.

**Comment by electronicboy** [comment]
events are only fired in the case where the clients care to send us stuff, this is not one of these cases where it does
