### ISSUE TITLE
Performance hit from using expensive debug method in block entity tick

### ISSUE THREAD

**Issue by PaulBGD** [PaperMC/Paper#5953]
### Timings or Profile link

https://i.imgur.com/tLDVzOh.png

### Description of issue

Apologies for screenshot, but it should be sufficient to see the issue occurs.

The size method in the PaperTickList is marked as debug only, for good reason as it's not very fast and iterates over the entire tick list: https://github.com/PaperMC/Paper/blob/3d43c5e50077ac7fa1e68cf7a7add0ac77768a61/patches/server/0388-Optimise-TickListServer-by-rewriting-it.patch#L664

However it's called when ticking block entities here regardless: https://github.com/PaperMC/Paper/blob/17f71ac87b7967ba203d34f039563a31010f26af/patches/server/0009-Timings-v2.patch#L1652

### Plugin list

None

### Server config files

Default configurations, fresh server

### Paper version

A local clone of f110140

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
Yep, I see the issue. Fixing it now
