### ISSUE TITLE
Skeletons not burning in daylight

### ISSUE THREAD

**Issue by srnyx** [PaperMC/Paper#5960]
### Expected behavior

Skeletons should burn in daylight

### Observed/Actual behavior

Skeletons just chilling like everything is normal smh

### Steps/models to reproduce

1. /time set day
2. /summon skeleton

### Plugin list

No plugins are installed

### Paper version

This server is running Paper version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This is happening to someone else on their server, too. They tested in single-player and skeletons did burn.

**Comment by Machine-Maker** [comment]
Huh, confirmed this. This couldn't have been around for too long right? I mean it would've been noticed earlier.

**Comment by TwoLeggedCat** [comment]
Strangely, they still burn if you use a spawn egg.

**Comment by srnyx** [comment]
> This couldn't have been around for too long right? I mean it would've been noticed earlier.

Well, at least 5 days, as the last 1.16.5 release was 6/16 (but maybe even longer cause the latest release doesn't even touch skeletons) lol

**Comment by TwoLeggedCat** [comment]
This effects even build 4 (first release), but not skeletons spawned with an egg.

**Comment by TwoLeggedCat** [comment]
Unsurprisingly, `Paper.shouldBurnInDay` is set to false on the skeletons that do not burn (those summoned via command).
