### ISSUE TITLE
Upside-down open shulker not triggering pressure plate under it

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5967]
### Expected behavior

Upside-down shulkers trigger pressure plates under them when they open.

### Observed/Actual behavior

In PaperMC, an upside-down shulker will not trigger pressure plates directly beneath it when it opens, unlike in vanilla. This breaks Rays Works' shulker farm (https://www.youtube.com/watch?v=ynvoyDehf1Q) which uses a wooden pressure plate to detect whether a shulker is open or not.

### Steps/models to reproduce

[shulkfarm litematic (extract me).zip](https://github.com/PaperMC/Paper/files/6700449/shulkfarm.litematic.extract.me.zip)

Use this litematic in any PaperMC 1.17 server. Spawn a shulker on top of the wooden pressure plate.

### Plugin list

None.

### Paper version

```
> version
[15:59:39 INFO]: Checking version, please wait...
[15:59:40 INFO]: This server is running Paper version git-Paper-"a7cddc4" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are 2 version(s) behind
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
Duplicate of #5915
