### ISSUE TITLE
Plugin version (4.1 != 4.10) are reported incorrectly

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#5969]
### Expected behavior

```
[2021-06-23 14:18:00 | Server thread] [Ping] Loading TestPlugin v4.10
[2021-06-23 14:18:10 | Server thread] [Ping] Enabling TestPlugin v4.10
/version TestPlugin
[2021-06-23 14:36:37 | Server thread] TestPlugin version 4.10
```

### Observed/Actual behavior

```
[2021-06-23 14:18:00 | Server thread] [Ping] Loading TestPlugin v4.1
[2021-06-23 14:18:10 | Server thread] [Ping] Enabling TestPlugin v4.1
/version TestPlugin
[2021-06-23 14:36:37 | Server thread] TestPlugin version 4.1
```

### Steps/models to reproduce

plugin.yml:
```yml
name: TestPlugin
description: Test plugin
version: 4.10
api-version: 1.16
author: molor
main: molor.plugin.test.TestPlugin
```

### Plugin list

TestPlugin

### Paper version

git-Paper-775 (MC: 1.16.5)

### Agreements

- [ ] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] My version of Minecraft is supported by Paper.

### Other

I can't update to 1.17 builds now, but I think that this is low priority problem and it's probably still not fixed.

In my case: 4.10 means 4 major version and 10 minor (build number). So build №1 from server log isn't the same as build №10 that actually running.

**Comment by Proximyst** [comment]
It's doing it correctly; wrap the version in quotes.

**Comment by molor** [comment]
@Proximyst, oh, thanks! For some reason, it seemed to me that version by default considered as string..

**Comment by Proximyst** [comment]
Yeah, you'd think! Sadly, we can't (or maybe just don't?) define that before SnakeYAML parses it as a float.
