### ISSUE TITLE
Chunk problem or something ...

### ISSUE THREAD

**Issue by rkfsociety** [PaperMC/Paper#5971]
### Stack trace

https://paste.gg/p/anonymous/d668247e8c324d298db928d86cb65ac5

### Plugin list

 LuckPerms, BlueMap, Chunky, GetSpawners, PlaceholderAPI, UltimateAutoRestart, PlugMan, AutoMessages, ChestSort, Clans, ProtocolLib, SkinsRestorer, Themis, AntiSeedCracker, Vault, WorldEdit, Essentials, Scoreboard-revision, HolographicDisplays, WorldGuard, Brewery, Citizens, DiscordSRV, TradeSystem, DeluxeMenus, EssentialsChat, TAB, GSit, CitizensGUI, EssentialsSpawn, CoreProtect, Autorank, Plan

### Actions to reproduce (if known)

I don’t know what’s going on. But this only happens on paper, on spigot everything is fine

### Paper version

git-Paper-43 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: d50cc01)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
logs are incomplete, and likely not a bug, please use the discord for support
