### ISSUE TITLE
Add Entity Visibility API

### ISSUE THREAD

**Issue by Janmm14** [PaperMC/Paper#5973]
### Is your feature request related to a problem?

Right now, per-player entities are done mostly with sending packets. This is a hacky and unreliable way and requires either NMS or ProtocolLib usage and is prone to break with minecraft updates.

### Describe the solution you'd like.

I'd like Paper to expand upon the `Player#hidePlayer` and `Player#showPlayer` methods with new methods `Player#showEntity(Entity)`, `Player#hideEntity(Entity)` and `Player#canSee(Entity)` as well as overloading `World#spawn` methods with a boolean `shownByDefault` and adding method `Entity#setShownByDefault` and `Entity#isShownByDefault`.

### Describe alternatives you've considered.

none

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Malfrador** [comment]
https://github.com/PaperMC/Paper/pull/4722 would have done that, but was closed by the author. Imo the event approach that the PR uses seems more useful to me, as that would allow plugins complete control over how and when an entity is hidden and is easier to implement and maintain. 

I still really like the idea and if no one else does I would PR it myself, but im not really comfortable with Paperweight yet and currently quite busy with other things, so that might take a while.

**Comment by Janmm14** [comment]
I didn't found that PR in my search, but it has some flaws:

- Overshot things with disguises (due to metadata etc), thats best left for LibsDisguises
- Missing API like `Player#isTracking(Entity)`
- No ability to edit tracking without the event.

The possibility of editing tracking only as entity gets into tracking range is looking fairly limited to me.
If used, a plugin would then probably just maintain a Map themself (prone to forgetting to clear on server leave).

I don't see why plugins would want to hide entities spawned by vanilla or other plugins, but those tracking events themself could be added as well if plugins want to listen to changes. (Those events should then trigger with both hide/spawn Player/Entity methods)

**Comment by Janmm14** [comment]
:/

**Comment by Chew** [comment]
Please don't needlessly spam or bump issues...

**Comment by Janmm14** [comment]
I'd like to know if there is anything I can do to speed up those PRs.

**Comment by Proximyst** [comment]
There's nothing. We take this on our own time, and right now availability and/or motivation seem to be at a low. Nothing anyone can do 🤷🏻‍♀️

**Comment by Doc94** [comment]
This is already in upstream not? https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#showEntity(org.bukkit.plugin.Plugin,org.bukkit.entity.Entity)

**Comment by Janmm14** [comment]
> This is already in upstream not? https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#showEntity(org.bukkit.plugin.Plugin,org.bukkit.entity.Entity)

@Doc94 see discussion in https://github.com/PaperMC/Paper/pull/6000

Edit: So far I have not done anything to upstream.

**Comment by Malfrador** [comment]
This has been added by upstream, including the hide-by-default API. Also see the discussion in the PR #6000.
