### ISSUE TITLE
TNT cannot destroy block with datapacks under y 0 

### ISSUE THREAD

**Issue by Kylepoops** [PaperMC/Paper#5974]
### Expected behavior

tnt can destroy block correctly with datapacks under y 0 

### Observed/Actual behavior

no block is destroy but the damage behave correctly

### Steps/models to reproduce

run the latest build (build#43) with datapacks
summon a TNT under y 0

### Plugin list

with datapacks under y 0 

### Paper version

1.17 build#64

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

ive tried to edit the tnt-entity-height-nerf to -64 but its even worse
it couldnt destroy block at any position

**Comment by kashike** [comment]
There is no build 64 of Paper 1.17 yet.

**Comment by Kylepoops** [comment]
> There is no build 64 of Paper 1.17 yet.

Bruh sorry that's typo
Build #43

**Comment by Chew** [comment]
Just smash that "Click to copy" on the `/version` output :3
