### ISSUE TITLE
IO warnings in server log and mob movement is jerky when the player is not moving

### ISSUE THREAD

**Issue by jessegit** [PaperMC/Paper#5982]
### Expected behavior

Smooth movement of mobs when the player is not moving and no IO warnings on the server log.

### Observed/Actual behavior

When player is not moving mouse or moving the player mobs in view will jump (location and animation) every ~1 second. The same time the server log get randomly warnings about IO (not every second/linked to the jumps)

```
[13:31:19 WARN]: [io.netty.channel.epoll.EpollEventLoop] Missed eventfd write (not seen after > 1 second)
[13:31:25 WARN]: [io.netty.channel.epoll.EpollEventLoop] Missed eventfd write (not seen after > 1 second)
[13:31:32 WARN]: [io.netty.channel.epoll.EpollEventLoop] Missed eventfd write (not seen after > 1 second)
```

### Steps/models to reproduce

Login, look at a mob, move mouse or player and mobs start moving smoothly.

### Plugin list

Does not matter. The problem persists with or without plugins

### Paper version

```
This server is running Paper version git-Paper-46 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 9e07703)
```

Triaged the version where it broke; seems to be between 1.16.4 last paper build and 1.16.5 first paper build.

```
openjdk 14 paper  1.16.3-251 works

openjdk 14 paper  1.16.4-416 works

openjdk 14 mojang 1.16.5     works
openjdk 14 paper  1.16.5-427 broken
openjdk 14 paper  1.16.5-778 broken

openjdk 16 mojang 1.17       works
openjdk 16 paper  1.17  -4   broken
openjdk 16 paper  1.17  -46  broken
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

The server is linux-like. That is, the server is running linux binaries but the kernel underneath is not linux. This may make it impossible to reproduce the bug on a vanilla linux. However, the bug cannot be dismissed as runtime environment bug as the mojang server works as intended; some change to the server in paper broke the networking(?) code.

I can provide an empty mc server to login to for a dev if they want to verify the problem but I can't provide shell access, unfortunately.

To me (as a software developer) it looks like the server's send queue is not handled when a tick has been processed, but only when a timeout happens (the IO warning on the log is related somehow? why doesn't it happen every second when the mob movement is jumpy?) or when data is received from a client. It's possible that it's enough for any logged in player to send data (move around) to mask the problem, but I'm unable to verify it alone.

**Comment by electronicboy** [comment]
that error is fired when the epoll selector didn't wake up for a second, not really sure what would have changed between those builds, only real change of note is that we're potentially using a newer version of netty, I do question what OS you're using as this does fall into kernel bounds

**Comment by electronicboy** [comment]
The version of netty that mojang is using, doesn't have that message inside of it;

current:
https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java#L330

mojang ver:
https://github.com/netty/netty/blob/c67a3b0507d847a9f01c886b944ced015245ecc9/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java#L256

Assuming that this is an issue on your end, this is something which should likely be reported to netty

**Comment by jessegit** [comment]
the OS is smartos (illumos/solaris derivative) and its os-virtualized linux environment. The fact that vanilla server works properly and is using the same kernel/epoll/netty stack means in books that paper(/spigot/...) broke it.

Also, 1.16.4+ use the same netty, 4.1.25.Final.

**Comment by electronicboy** [comment]
Paper uses 4.1.65, This is likely a netty/kernel level issue, and we generally have 0 interest in spending time trying to debug deep complex issues inside of niche OSes in niche environments, especially as this concerns native code which accesses the kernel which is out of the bounds of us

**Comment by jessegit** [comment]
> Paper uses 4.1.65, This is likely a netty/kernel level issue, and we generally have 0 interest in spending time trying to debug deep complex issues inside of niche OSes in niche environments, especially as this concerns native code which accesses the kernel which is out of the bounds of us

Paper 1.17 uses netty 4.1.65, but paper 1.16.4 and 1.16.5 use netty 4.1.25 and the code broke in between those. So it has most likely nothing to do with netty itself, only the way it's used. As a proof we have vanilla servers that all work.

**Comment by drunderscore** [comment]
Like said above, it's a niche OS, and I doubt many people have any interest in kernel level issues.

_My opinion: it should implement Unix better._
