### ISSUE TITLE
Add toggleable server stop confirmation via CTRL+C

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#5983]
### Is your feature request related to a problem?

Yes. I have server with 50+ players and already stopped it several times by accident when trying to copy some files from one folder to another without looking at which window is in focus before that.

### Describe the solution you'd like.

Just add an option to enable confirmation with CTRL+C too, e.g.
```
> CTRL+C
Paper: do you want to stop the server? CTRL+C again to confirm
> CTRL+C
Stopping server
```

### Describe alternatives you've considered.

Actually pay attention where I hit CTRL+C

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

This happens on Windows Server host via RDP client

**Comment by aurorasmiles** [comment]
I get incredibly angry every time I try to kill a program/script running in the terminal and it doesn't immediately die screaming when I press CTRL + C

**Comment by electronicboy** [comment]
so many different libraries hijack ctrl-c that this would just be a royale PITA, I'm not sure if this is really viable and I'm not really all that sure of the worth of it

**Comment by Chew** [comment]
Is this a windows problem I'm too mac to understand? Kidding. I don't know your specific situation, but I feel like there are much easier, safer, and friendlier ways to handle it. It should, if implemented, at minimum, be a flag you need to set for it to take effect.

**Comment by DenWav** [comment]
If you're running your server from a bash script I recommend configuring bash with a SIGINT (ctrl-c) handler - known more accurately as a trap. Put this before your Java start command in your script to trap SIGINT and do nothing:

```
trap "" SIGINT
```

This would probably be a nice feature to have built into the server too, but this workaround works well. I always use it if I'm running a server.

**Comment by molor** [comment]
@DenWav, server on Windows Server. And I actively use this keyboard shortcut during server/plugins testing, tuning, debugging. I do not want to disable this feature completely, just want to get rid of accidental clicks. Pressing CTRL+C twice in a row is not that difficult, but it can save us from awkward situations

**Comment by DenWav** [comment]
I'm of the opinion that if this was implemented, the optimal way to do it would be to ignore it completely and require typing `quit`.

**Comment by Proximyst** [comment]
I feel this is hardly an actual issue, let alone one up to us to handle. If you don't want to fuck up, don't keep the terminal prompt open at all; use tmux or whatever works on Windows, or at least minimise it...
