### ISSUE TITLE
SignChangeEvent e.lines(int, Component) not replacing text of sign

### ISSUE THREAD

**Issue by AwesomeDude091** [PaperMC/Paper#5987]
### Expected behavior

I expect the sign to replace the text on the line I indicate

### Observed/Actual behavior

No change occurred

### Steps/models to reproduce

Code that was used to produce this issue:

Note: I have been told multiple times that this code is anything but perfect, however it works and it runs all the way till the printing out of i.

@EventHandler(priority = EventPriority.HIGHEST)
    private void signChange(SignChangeEvent e) {
        System.out.println("Sign Change Event got called!");
        List<Component> lines = e.lines();
        int i = 1;
        for(Component component: lines) {
            if(component.toString().contains("tp")) {
                System.out.println("Tp got found");
                String value = component.toString();
                String[] args = value.split(" ");
                System.out.println(value);
                args[3] = args[3].substring(0, args[3].length() - 2);
                System.out.println(args[1] + args[2] + args[3]);
                Location location = new Location(Bukkit.getWorld("world"),
                        Double.parseDouble(args[1]),
                        Double.parseDouble(args[2]),
                        Double.parseDouble(args[3]));
                Location objectLocation = e.getBlock().getLocation();
                try {
                    sql.setSignData(objectLocation, location);
                } catch (TableException | SQLException tableException) {
                    tableException.printStackTrace();
                }
                final TextComponent text = Component.text()
                        .content("")
                        .build();
                System.out.println(i);
                e.line(i, text);
            }
            i++;
        }
    }

### Plugin list

Alice, BungeeGuard, Citizens, Colored-Signs, Denizen, EssentialsX, EssentialsXSpawn, HolographicDisplay, HolographicExtension, LobbyPlugin(My plugin), LuckPerms, PlaceholderAPI, PlayerHeads, ProtocolLib, SimplePortals, Vault, Viral-SQL-API(My Plugin), WorldEdit, WorldGuard

### Paper version

[22:26:58] [Server thread/INFO]: This server is running Paper version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-597 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I am aware that the ColoredSigns might cause issues, however I have tested the feature by removing the plugin and checking if the issue persists. It does...

Have also used e.setLine with similar effect

**Comment by Prof-Bloodstone** [comment]
Arrays are indexed from 0: https://en.wikipedia.org/wiki/Off-by-one_error

Try putting:
```
tp
here
pls
```

Also, next time please either put your code in codeblocks (three backticks) or use paste site like paste.gg

**Comment by AwesomeDude091** [comment]
Don't the sign columns specifically start at index 1?

**Comment by Prof-Bloodstone** [comment]
1. It's a line/row, not a column. Wrong direction :)
2. You get a `java.util.List`, not `SignLineHolder` or whatever. They are 0 indexed: https://docs.oracle.com/javase/8/docs/api/java/util/List.html
3. If you look at event Javadocs, they same the same thing: https://papermc.io/javadocs/paper/1.16/org/bukkit/event/block/SignChangeEvent.html#line(int)

**Comment by AwesomeDude091** [comment]
It works now thank :)
