### ISSUE TITLE
Configurable minimum mob spawn range

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#599]
With all the configurable mob options now available in paper and spigot combined, it's missing the minimum spawn range to be configurable. Would be nice to experiment with and see if it's possible to reduce mob-spawn-range: even further and have more mobs spawn closer to players, rather than only 24 blocks away which will always be outside the activation range on packed servers.

http://minecraft.gamepedia.com/File:Mob_spawning_ranges.png - the green circle here, 24 blocks. config would have 24 be default and configurable to whatever value, like 4, and mobs can spawn as close as 4 blocks away from players, just an example.

**Comment by zachbr** [comment]
Duplicate of GH-245
