### ISSUE TITLE
end is severly glitched .build 46 . END unplayable!!!!!!

### ISSUE THREAD

**Issue by Aditya14011** [PaperMC/Paper#5996]
### Expected behavior

ability to normally enter the end and load chunks

### Observed/Actual behavior

as soon as a entered end . it lagged and crashed. the few spawn chunks loaded
but nothing else did
the logs r in the paste.gg link
https://paste.gg/p/anonymous/9460ad9f28654ea3af6f416a16bf759a

### Steps/models to reproduce

make endportal
enter end

i tried it on several servers with paper build 46 1.17 
it crashed every time after not responding for 10 sec 

### Plugin list

no plugins 
just the mojang caves data pack

( i dont think that should affect anything as the server  ran smoothly before we entered end. the nether worked fine too)

### Paper version

This server is running Paper version git-Paper-46 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 9e07703)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by jackburkhardt** [comment]
I can't reproduce this at all, even with the caves and cliffs datapack. When you start the server back up, are you able to enter the end again at all? Or will it always crash no matter what?

In addition, the thread dump you posted says in call caps not to report to paper and that it's not a bug or a crash, your server is just not responding. If all of your testing happened on Aternos, it could be something on their end causing your server to lag out. Someone can feel free to correct me if this is actually a bug though.

**Comment by embeddedt** [comment]
I have always found on my (relatively weak) personal machine that generating the end in both 1.16 and 1.17 for the first time often causes a very noticeable lag spike. If Aternos was sufficiently loaded at the time that you were testing this, it's likely that the lag spike became so long that the server watchdog simply stopped the server.

The solution is probably to just pregenerate a 200-block radius in the end at a time when Aternos is less busy.

**Comment by Chew** [comment]
Not entirely sure how end generation is so expensive considering it's nothing... why there's structure lag when they're no structures anywhere near the spawn is beyond me

**Comment by goinsb2000** [comment]
Can confirm this is an issue on the same level as issue #5899, server will lock up and crash when entering the end and will refuse to boot until switching back to spigot/vanilla.

**Comment by TauCu** [comment]
> 
> 
> Not entirely sure how end generation is so expensive considering it's nothing... why there's structure lag when they're no structures anywhere near the spawn is beyond me

Aren't the end pillars structures?

**Comment by Chew** [comment]
Was specifically referring to randomly generated ones (End cities), which only spawn on the end islands. The pillars are the exact same position in every world nowadays I believe?

**Comment by kennytv** [comment]
We still have been unable to reproduce this, so it would be great if you could give us a timings report on the setup you get this issue (so we can get the configuration setup and some other info timings provides).
Also, does this actually hard lockup your server, or does your server tick/log normal messages again at some point after the first 10 second watchdog warning appears (do you see entities moving, can you drop an item or hear place sounds, aka does it "just" lag a lot or fully crash immediately)?

**Comment by embeddedt** [comment]
```
[09:25:01 INFO]: This server is running Paper version git-Paper-46 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 9e07703)
/seed
Seed: [-3014090999035849675]
/tp @s -14 74 64
/setblock ~ ~ ~ end_portal
Changed the block at -14, 73, 64
```

The issue is not 100% reproducible. I ran this sequence of commands the first time and the lag occured. The second time it only lagged for about 2 seconds.

I do find world generation in 1.17 to be much slower than 1.16, but I am using the preview datapack so that might be expected.

When the issue occurs, all ticking seems to freeze and chunks do not load in the End for at least 15 seconds. My server does begin working normally again after that.

I'm trying to reproduce it with Timings running and will attach a report once I do so.

**Comment by embeddedt** [comment]
https://timings.aikar.co/?id=1206f4184dae4917bf91cfc7052a8a85

I'm guessing the "Sync Chunk Load" indicates I've done something very wrong with the configuration. :laughing: I'll investigate that further.

EDIT: `sync-chunk-writes` is set to false in `server.properties`. However, I've noticed `enable: true` is missing from `async-chunks` in `paper.yml`. It is there on my 1.16 server. Do I need to add that?

**Comment by JakeTeeEm** [comment]
I'm having a similar issue on my own server.  Whenever you step through an exit portal, the server either crashes, or leaves you there in "waiting for chunk" forever.  Had to either restart the server, or even get an alt on to teleport myself out of the glitched area.

**Comment by MiniDigger** [comment]
> [11:51:33] [Server thread/INFO]: Scanning for legacy world dragon fight...

can you try to see if you can repro this if you disable the config option for this?

**Comment by embeddedt** [comment]
I set `scan-for-legacy-ender-dragon: false` and I get identical behavior (minus that log message).

**Comment by e-im** [comment]
Are folks still able to reproduce this on current versions? I haven't been able to on either old or new builds including with the caves and cliffs datapack.
