### ISSUE TITLE
worldguard playermoveevent could not pass - only on paper 1.17 build 46

### ISSUE THREAD

**Issue by rczerwiec** [PaperMC/Paper#5997]
### Expected behavior

Do not spam console with logs

### Observed/Actual behavior

Could not pass event PlayerMoveEvent while playing moving, it generates 7mb o log files per minute.
https://paste.gg/p/anonymous/4771a748c8924b86bffaedb7c652422b

### Steps/models to reproduce

- enter the server
- just move

### Plugin list

https://imgur.com/a/Ob0DW20

### Paper version

1.17 build 46

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by rczerwiec** [comment]
error appears at every version of worlguard, also including newest build. It appears only on paperspigot.

**Comment by electronicboy** [comment]
Provide full logs, or at least especially the startup, something caused some classloader (or at least the jar) to close, probably also wanna update ProtocolLib to the latest snapshots, no idea what WGEF is doing there

**Comment by rczerwiec** [comment]
@electronicboy  here is full log file.
https://paste.gg/p/anonymous/44044dce74524971b47b5c7614147a4c
What about WGEF? It works well with spigot

**Comment by electronicboy** [comment]
paper cleans up after stuff a bit better, so running in oddball states is more likely to cause issues

https://paste.gg/p/anonymous/44044dce74524971b47b5c7614147a4c#pastefile1-l450

for example, as I said, in general, you probably wanna work on fixing the several dozen other errors too
