### ISSUE TITLE
git-Paper-"28aacb4" not compatible with Shopkeeper v2.12.0

### ISSUE THREAD

**Issue by stefanofornari** [PaperMC/Paper#6003]
### Expected behavior

The plugin to load and being enabled

### Observed/Actual behavior

[18:42:27] [Server thread/INFO]: [Shopkeepers] Enabling Shopkeepers v2.12.0
[18:42:27] [Server thread/ERROR]: [Shopkeepers] Incompatible server version: Shopkeepers cannot be enabled.

### Steps/models to reproduce

just install the latest stable version to the mentioned version of PaperMC

### Plugin list

Shopkeeper
MemoryViewer

### Paper version

This server is running Paper version git-Paper-47 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: a23eb53)
You are running the latest version
Previous version: git-Paper-"28aacb4" (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
The latest stable version of that plugin doesn't support 1.17, 2 second look indicates you need the alpha which actually does

**Comment by Bilibox** [comment]
@stefanofornari your version of Shopkeepers appears to be outdated. 
Shopkeepers 2.12.0 is for 1.16.5, whereas Shopkeepers 2.13.0 seems to have some 1.17 support.
