### ISSUE TITLE
[1.17] Players cannot be seen

### ISSUE THREAD

**Issue by Taskeren** [PaperMC/Paper#6006]
### Expected behavior

Render players as normal.

### Observed/Actual behavior

Players cannot be seen. Sounds like walking are available. Particles are not. Chest animations are working.

### Steps/models to reproduce

/

### Plugin list

eBackup

### Paper version

This server is running Paper version git-Paper-48 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 23214fa)
You are running the latest version
Previous version: git-Paper-46 (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I'm using Travertine-1.16-191 as proxy.

**Comment by e-im** [comment]
I haven't been able to reproduce this- likely caused by proxy plugins etc. Please come to our [discord](https://discord.gg/papermc) for future support regarding this issue.
