### ISSUE TITLE
Datapack causes server to crash

### ISSUE THREAD

**Issue by Plasman888** [PaperMC/Paper#6007]
### Stack trace
https://paste.gg/p/anonymous/d9ae645231bb419da44192d2a75fafbc

### Plugin list

bettersleep
discordSRV 1.23.0
essentialsx 2.19.0 167dev
floodgate
geyser-spigot
interactive chat 4.0.0.14
interactive chat addon 4.0.0.14
vault
viaversion 4.0.0
luckperms
multiverse core 4.2.2
open inv
placeholder api 2.10.10dev
protocol lib
skin restrorer
tameablefox 2.0.0 snapshot
worldedit 7.2.6 snapshot

### Actions to reproduce (if known)

Install the latest version of paper then install the datapack called Peakstep's Creatures II ,https://www.planetminecraft.com/data-pack/mo-creatures-beta-0-0-1/. Put them on the server then try to run the server, it should crash without running.

### Paper version

1.17-49

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I am using a datapack called Peakstep's Creatures II ,https://www.planetminecraft.com/data-pack/mo-creatures-beta-0-0-1/, which causes the server to crash, i have also noticed that other datapacks are also having errors this only happens on paper and possibly spigot i am not too sure, but vanilla works falwlessly thus its not the datapack's issue.

**Comment by Machine-Maker** [comment]
PLEASE use a paste site for massive stack traces. It just makes it very unreadable and therefore more difficult to help you.

**Comment by Plasman888** [comment]
ok sorry

**Comment by Plasman888** [comment]
Is that what you mean?

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/123516549-9815c700-d694-11eb-9e00-39f73a994298.png)
paper, upper, vanilla, lower

**Comment by Plasman888** [comment]
oshit sry u guys r right it works on single player but not multi for some reason
