### ISSUE TITLE
The server is unable to open due to errors related to "No key dirt_provider in MapLike" Error

### ISSUE THREAD

**Issue by Hivane060** [PaperMC/Paper#6008]
### Stack trace

```
https://pastebin.com/XEb9L4zc <-- by using Paper-1.17 #49
```
I don't know if this could interest you as well, but I got similar errors using spigot:
https://pastebin.com/Unr3sGWb <-- with Spigot (Released 11 of june)

### Plugin list

This issue occurs without plugins as well

### Paper version

Paper-1.17 #49

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Due to those errors I am barely able to open the server without plugins (It consumes 4gb of ram to open). This issue occurred within multiple worlds (In that case the server couldn't just endure it and therefore would crash during its opening).

**Comment by electronicboy** [comment]
vanilla bug, non-issue bar being annoyin spammy.
