### ISSUE TITLE
I seem to lose every water creature (except turtles) after a while.

### ISSUE THREAD

**Issue by NULUSIOS** [PaperMC/Paper#6012]
### Expected behavior

For all water based fauna to remain.

### Observed/Actual behavior

After some time, possibly after exiting a session and going back in, every water creature is lost except turltes and (I think) the old version of squids.

### Steps/models to reproduce

Throw plenty of every kind of sea creature in a closed water area.

### Plugin list

WorldEdit, WorldGuard

### Paper version

1.17-49

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Jack1424** [comment]
I started up a server on default settings and put some aquatic animals into a small area of water and let the game run for around thirty minutes. Aside from the squids all killing themselves, all of the fish were still there even after leaving and re-joining the server and restarting it.

**Comment by e-im** [comment]
It sounds like what you are experiencing here is them despawning, this is intended behaviour. Turtles however do not despawn, hence why you still see them.

If you would like to prevent your fish from despawning, either name them or put them in a bucket.
