### ISSUE TITLE
Hoglins dont appear in overworld when entering a portal

### ISSUE THREAD

**Issue by HyplexMC** [PaperMC/Paper#6013]
### Expected behavior

a Hoglin on the other end shaking for a few sec until it is transformed into a zoglin.

### Observed/Actual behavior

Hoglin enters portal and when you enter the portal there is no Hoglin on the other side.

### Steps/models to reproduce

make portal and send Hoglin thru it 

### Plugin list

CMI
CMILib
CoreProtect
DiscordSRV
PlaceholderAPI
Plan
ProtocolLib
Spartan
UltraCustomizer
UltraPermissions
UltraPunishments
UltraRegions
Vault

### Paper version

This server is running Paper version git-Paper-47 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: a23eb53)
You are 2 version(s) behind
Previous version: git-Paper-46 (MC: 1.17)

I have a player who reported this to me and said it did not work in 1.16.5 either

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
I haven't been able to reproduce this- please try without plugins.

**Comment by nsde** [comment]
I have the same problem! With no plugins.
