### ISSUE TITLE
Villagers throwing huge amounts of bread tp each other and reseting their jobs. 

### ISSUE THREAD

**Issue by acrticsludge** [PaperMC/Paper#6015]
### Expected behavior

Since villagers like to throw food at each other I expected that they would throw only a few bits like 5 to 10 pieces of bread.

### Observed/Actual behavior

found a bug in paper 1.16.5 (atleast i think its one) villagers are throwing ridiculous amounts of bread to each other like its lagged the server a lot  and resetting their jobs so i hope this will be fixed in 1.17 (if its a paper bug)

### Steps/models to reproduce

Happens every time villagers throw food at each other.

### Plugin list

AdvancedHelp, AuctionMaster, AutomaticBroadcast, BuycraftX, Cannons, Citizens, CombatLogX, CoreProtect, CrackedBlocks, CrazyCrates, CustomHeads*, DiscordSRV, DragonFights, dynmap*, Dynmap-Towny, EconomyShopGUI, EpicGuard*, Essentials, EssentialsSpawn, HolographicDisplays, IllegalStack, ItemEvents, Jobs, LockettePro, LuckPerms, mcMMO, MineableSpawners, MineAlerts, Movecraft, Movecraft-Cannons, Movecraft-Combat, Movecraft-Repair, PlaceholderAPI, ProtocolLib, Quests, QuickShop, SiegeWar, SlimeCustomizer, Slimefun, spark, Spartan, StackMob, StatsSB, TAB, TheNewEconomy, Towny, TownyChat, TownyFlight, Vault, ViaVersion, Votifier, VotingPlugin, Wild, WorldBorder, WorldEdit, WorldGuard

### Paper version

This server is running Paper version git-Paper-"b94a99b03" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 300 version(s) behind
Previous version: git-Paper-"407ad043c" (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

![DEC1030E-C53A-4CCE-B1BF-54E4BD9D3F9B](https://user-images.githubusercontent.com/71878505/123532148-533b7000-d728-11eb-9374-c97cb66ce1b0.png)

**Comment by e-im** [comment]
Update, this has been fixed. As it says you are 300 versions behind.

**Comment by Chew** [comment]
>  I am running the latest version of Paper available from papermc.io/downloads.

nope
