### ISSUE TITLE
Requesting the ability to adjust /ver's cached response

### ISSUE THREAD

**Issue by malonnnn** [PaperMC/Paper#602]
**What I'm asking for**
A config option that would allow the user to adjust how frequently "/ver" actually checks for new versions

It's currently set to cache the last response for 6 hours, i.e. you can only check for updates once every 6 hours.

As far as I can tell, the requests simply query github's servers for newer commits, so it shouldn't have any noticeable effects.

Thank you for all your hard work, devs.

**Comment by zachbr** [comment]
Are there really enough updates to justify this?

**Comment by malonnnn** [comment]
Between the updates that paperspigot adds and the updates from upstream, yes I do believe so, _especially_ right when a new update comes out. I play very frequently and it's not uncommon get the idea to do /ver every few hours, except that oh, I can't because I have to wait.

**Comment by prplz** [comment]
Have you considered opening github or the ci?

**Comment by malonnnn** [comment]
man, feels really hostile in here.

Just wanted a shorter timeout for checking for updates.

**Comment by malonnnn** [comment]
yes I have considered them and yes I use them.

Does that mean I am not allowed to ask for this feature if I didn't?

**Comment by zachbr** [comment]
Probably won't be made configurable, may lower it to one or two hours though.
