### ISSUE TITLE
Server sometimes can stuck on "Reloading ResourceManager"

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#6020]
### Expected behavior

The server is starting.

### Observed/Actual behavior

The server is not starting.

### Steps/models to reproduce

This is not the first time I have encountered this. I do not know how to reproduce this. This happens randomly, possibly depending on the phase of the moon :/

It looks like the server thread is waiting for something or another important thread is stuck on something, but I do not know how and where to look at the stack trace. **Right now the server is in this state and still running, so if you can tell me which program can be used to see what its process is doing, I will send you the necessary information to fix this problem.**

This is always looks like this:
![image](https://user-images.githubusercontent.com/19989717/123618660-15664680-d811-11eb-9e4b-e18698ec2ba7.png)
And that's all. Time in now 13:20, CPU load in the task manager is ~1%, the server took up 2 MiB of RAM and just does nothing until it is restarted..

`Listening for transport dt_socket at address: 1023` on the last line: I tried to connect to server via Eclipse Debug, but later disconnected because it did not give me any info :c

### Plugin list

null

### Paper version

I encountered this problem back on versions 1.15 and 1.14, but it happened rarely and I did not think that it would happen again in new versions. Maybe this has already been fixed in 1.17, but I think not.

```
{"currentVersion":"git-Paper-777 (MC: 1.16.5)"}
```

### Agreements

- [ ] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by molor** [comment]
Startup command:

```
java -Xms2G -Xmx2G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dfile.encoding="utf-8" -Xdebug -Xrunjdwp:transport=dt_socket,address=1023,server=y,suspend=n -jar "server.jar" nogui
```

**Comment by Proximyst** [comment]
Run `jstack $pid` where `$pid` is the appropriate number from `jps` and paste the contents into a code block or paste.gg, please.

**Comment by molor** [comment]
I think that this is bad

![image](https://user-images.githubusercontent.com/19989717/123626783-e0aabd00-d819-11eb-8782-1c21b8f747fa.png)

**Comment by molor** [comment]
I caught it

https://paste.gg/p/anonymous/191efa7e74234538a3177f65fe761223

**Comment by molor** [comment]
Same on 1.17.1-133 (eclipse's remote debug connection stack trace, because jps & jstack again reports that `jvm.dll not loaded by target process`)

```
Java HotSpot(TM) 64-Bit Server VM [localhost:1023] (Suspended)	
	Thread [main] (Suspended)	
		Unsafe.park(boolean, long) line: not available [native method]	
		LockSupport.park(Object) line: 211	
		CompletableFuture$Signaller.block() line: 1860	
		ForkJoinPool.managedBlock(ForkJoinPool$ManagedBlocker) line: 3137	
		CompletableFuture<T>.waitingGet(boolean) line: 1894	
		CompletableFuture<T>.get() line: 2068	
		Main.main(OptionSet) line: 192	
		Main.main(String[]) line: 293	
	Daemon Thread [Log4j2-TF-1-AsyncLogger[AsyncContext@2a139a55]-1] (Suspended)	
		Unsafe.park(boolean, long) line: not available [native method]	
		LockSupport.parkNanos(Object, long) line: 252	
		AbstractQueuedSynchronizer$ConditionObject.awaitNanos(long) line: 1661	
		TimeoutBlockingWaitStrategy.waitFor(long, Sequence, Sequence, SequenceBarrier) line: 38	
		ProcessingSequenceBarrier.waitFor(long) line: 56	
		BatchEventProcessor<T>.processEvents() line: 159	
		BatchEventProcessor<T>.run() line: 125	
		Log4jThread(Thread).run() line: 831	
	Daemon Thread [WindowsStreamPump] (Suspended)	
		Kernel32.WaitForSingleObject(long, int) line: not available [native method]	
		WindowsSupport.readConsoleInput(int, int) line: 97	
		JansiWinSysTerminal.processConsoleInput() line: 112	
		JansiWinSysTerminal(AbstractWindowsTerminal).pump() line: 458	
		0x0000000800d0b730.run() line: not available	
		Thread.run() line: 831	
	Daemon Thread [Timer hack thread] (Suspended)	
		Thread.sleep(long) line: not available [native method]	
		SystemUtils$4.run() line: 581	
	Daemon Thread [Worker-Main-1] (Suspended)	
		Unsafe.park(boolean, long) line: not available [native method]	
		LockSupport.park() line: 341	
		AbstractQueuedSynchronizer$ConditionNode.block() line: 505	
		ForkJoinPool.managedBlock(ForkJoinPool$ManagedBlocker) line: 3137	
		AbstractQueuedSynchronizer$ConditionObject.await() line: 1614	
		LinkedBlockingQueue<E>.take() line: 435	
		ThreadPoolExecutor.getTask() line: 1056	
		ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1116	
		ThreadPoolExecutor$Worker.run() line: 630	
		ServerWorkerThread(Thread).run() line: 831	
	Daemon Thread [Worker-Main-2] (Suspended)	
		Unsafe.park(boolean, long) line: not available [native method]	
		LockSupport.park() line: 341	
		AbstractQueuedSynchronizer$ConditionNode.block() line: 505	
		ForkJoinPool.managedBlock(ForkJoinPool$ManagedBlocker) line: 3137	
		AbstractQueuedSynchronizer$ConditionObject.await() line: 1614	
		LinkedBlockingQueue<E>.take() line: 435	
		ThreadPoolExecutor.getTask() line: 1056	
		ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1116	
		ThreadPoolExecutor$Worker.run() line: 630	
		ServerWorkerThread(Thread).run() line: 831	
	Daemon System Thread [Reference Handler] (Suspended)	
		Reference<T>.waitForReferencePendingList() line: not available [native method]	
		Reference<T>.processPendingReferences() line: 243	
		Reference$ReferenceHandler.run() line: 215	
	Daemon System Thread [Finalizer] (Suspended)	
		waiting for: ReferenceQueue$Lock  (id=27)	
		Object.wait(long) line: not available [native method]	
		ReferenceQueue<T>.remove(long) line: 155	
		ReferenceQueue<T>.remove() line: 176	
		Finalizer$FinalizerThread.run() line: 171	
	Daemon System Thread [Signal Dispatcher] (Suspended)	
	Daemon System Thread [Attach Listener] (Suspended)	
	Daemon System Thread [Notification Thread] (Suspended)	
	Daemon System Thread [Common-Cleaner] (Suspended)	
		waiting for: ReferenceQueue$Lock  (id=28)	
		Object.wait(long) line: not available [native method]	
		ReferenceQueue<T>.remove(long) line: 155	
		CleanerImpl.run() line: 140	
		InnocuousThread(Thread).run() line: 831	
		InnocuousThread.run() line: 134	
```

**Comment by stefvanschie** [comment]
Occurs on Paper 1.17.1 build 189 as well. I didn't have any kind of remote debug running. The output from `jstack` and my start script can be found here: https://paste.gg/p/anonymous/f5d4cd939b144d25bfa6239dde3a5e36.

**Comment by stefvanschie** [comment]
Also occurs on Paper 1.17.1 build 196: https://paste.gg/p/anonymous/7cc2e07776a043c699ede3487857ccae.

**Comment by molor** [comment]
Why we can't fix this?

**Comment by electronicboy** [comment]
Well, do you know what causes it?

**Comment by Puremin0rez** [comment]
I've had this occur today during a normal nightly restart, I did a thread dump as well as a heap dump in case anything useful can be figured out from doing a more extensive dive into the state of the server during the deadlock.

Thread dump: https://pastebin.com/raw/8MGREYk3

Heap dump: https://app.treasure.cloud/share/public/f17a6053ab071f20c85a058f229e4e02003f1ea4cd1b957b454897e785a70a61
 (190 MB - Link Password: `zOUAkmYyhp65xqwmHDQtuC3Efon4gh1/xTXBvZeN3Fbwaqg5`)

**Comment by DarkEyeDragon** [comment]
Still happening in `git-Paper-81 (MC: 1.18.1)`

**Comment by ryanyodie12** [comment]
> Still happening in `git-Paper-81 (MC: 1.18.1)`

Can confirm.

**Comment by stefvanschie** [comment]
Was about to comment on this happening on 1.18.1 build 177, but after 3.5 minutes the "Loading 7 recipes" message appeared. I believe I have waited longer than that before my previous comments, but for subsequent commenters, maybe worth at least waiting this long to ensure it's actually stuck and not just very slow (although it being very slow is probably also something that would need to be addressed).

**Comment by electronicboy** [comment]
it's not very slow is my understanding, something internal to the call ends up seemingly borking and thus the thing never completes; I recall kinda seeing some scary potentials when I last looked at it but there's no reliable way to reproduce this especially with the noise of a debugger attached

**Comment by Machine-Maker** [comment]
I will say, it has happened to me once with a debugger attached, but I wasn’t able to quite figure out what was going on.

**Comment by DarkEyeDragon** [comment]
> Was about to comment on this happening on 1.18.1 build 177, but after 3.5 minutes the "Loading 7 recipes" message appeared. I believe I have waited longer than that before my previous comments, but for subsequent commenters, maybe worth at least waiting this long to ensure it's actually stuck and not just very slow (although it being very slow is probably also something that would need to be addressed).

Waiting did nothing in my case. It was on that message for like 40 minutes before i just ended it's suffering.

**Comment by electronicboy** [comment]
yea, it's not slow, if you look at a stack you'll see that any threads for that are long dead, I'm guessing it blows up internally somewhere but we're losing the exception, and so it's just a future which never completes

**Comment by DomiIRL** [comment]
Anything new on this issue? Having the same issue and haven't found any solution or hint what the problem might be caused by.

**Comment by Machine-Maker** [comment]
It shouldn't be happening consistently, if it does, then something else is happening. I very rarely have this happen, and just ctrl+c'ing and then starting again fixes it.

**Comment by electronicboy** [comment]
We still don't have a means of reproducing it in any form of manner which is conducive towards debugging, the logic here is generally a PITA due to how mojang implemented this snake nest which likely means that there is an error being thrown which is lost, just, we have no sane manner of reproducing this to test this

**Comment by DomiIRL** [comment]
> It shouldn't be happening consistently, if it does, then something else is happening. I very rarely have this happen, and just ctrl+c'ing and then starting again fixes it.

CTRL+C fixes it indeed but thats not the greatest solution. Sometimes I would check through all my networks servers and find a few with this excact problem and I just have to manually stop them :/

**Comment by Machine-Maker** [comment]
Was just perusing the issues and noticed this one. I haven't had this happen to me in a **long** time, like many minecraft versions since the last time. It's possible its fixed. Unless someone chimes in that they've had it recently on a newer version, I'll close this in about a week.

**Comment by Warriorrrr** [comment]
About a week later

**Comment by LoyalPineapple** [comment]
Started having this issue in 1.20, still an issue in 1.20.4

`[ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]`

Always seem to hang for 5-10 min, server starts normally after.
