### ISSUE TITLE
[13:36:27 ERROR]: Exception loading structure piece with id minecraft:jigsaw

### ISSUE THREAD

**Issue by MarcusVosper** [PaperMC/Paper#6021]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://pastebin.com/dHrtgDCC

### Plugin list

https://ibb.co/GHdY4Kd

### Paper version

[13:45:41 INFO]: This server is running Paper version git-Paper-55 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: ba7ffd0)
You are running the latest version
Previous version: git-Paper-53 (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

N/A

**Comment by electronicboy** [comment]
Vanilla

**Comment by Strahilchu** [comment]
I have something similar

**Comment by Tarlak333** [comment]
Similar during OhTheDungeon intialization: (paper-1.17.1-109, JAVA 16.0.1)

https://pastebin.com/D5e8tg3W
