### ISSUE TITLE
[1.17] Error on Startup

### ISSUE THREAD

**Issue by Strahilchu** [PaperMC/Paper#6022]
### Expected behavior

No Error

### Observed/Actual behavior

This big error
https://pastebin.com/2Q80bEJC

### Steps/models to reproduce

Not sure if specific to me but just starting the server on 1.17 after updating from 1.16.5

### Plugin list

Plugins (43): AntiXrayHeuristics, AutomatedCrafting, BetterTeams, BettingGames, BottledExp, Brewery, ChestShop, Chunky, ChunkyBorder, CMI, CMIEInjector*, CMILib, CrazyAuctions, CryptoMarket, CustomWings, DualWield*, Elevator, GCoreLegacy, GSit, HeadDatabase, ImageMaps, InventorySaver, Jobs, LuckPerms, MarriageMaster, mcMMO, Minepacks, MiniBoardGames, MobFarmManager, Pl3xMap, ProtocolLib, SpecializedCrates, Spleef*, Stocks*, SurvivalInvisiframes, TempFly, TogglePVP, TryMe, Vault, ViaVersion, Vulcan, WorldEdit, WorldGuard

### Paper version

Paper version git-Paper-55 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: ba7ffd0)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Things seem to work good but this error looks scary and I wanted to make sure it was known I was not able to find another post with it so far

**Comment by electronicboy** [comment]
Vanilla bug, please use the search feature.
