### ISSUE TITLE
Server Crashes and not responding to console commands

### ISSUE THREAD

**Issue by apaar24** [PaperMC/Paper#6023]
### Stack trace

```
https://paste.gg/p/anonymous/e039606c13454c129e6d08a54a99e4c6
```

### Plugin list

1.DiscordSRV
2.Spigot Ping 
3.Advanced Teleport

### Actions to reproduce (if known)

![image](https://user-images.githubusercontent.com/83948393/123680620-8d129080-d866-11eb-9e23-e971197a75c1.png)
I have so many of DiscordSRV notifications like these every hour or 2 .

### Paper version

This server is running Paper version git-Paper-"47605b8" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I have a new startup of cloud hosting company based in India, and I have 2 servers running currently one with 4 core , 8 GB ram and 30 GB of storage  and the other one (clients) running on 2 core and 4 GB ram with 25GB Storage, both the servers are running on paper as paper is the best. My the 4 core server was running on 1.16.5 before and had no issues like this with those specs and as I upgraded the version to 1.17, the server started crashing and when ever I try "list" command in the console it does not respond. Also the same thing is happening with the clients server they have been reporting that the server is crashing again and again and it was working perfectly fine on the 1.16.5 last night before the updated to 1.17. The same thing is happening when I switched to spigot that is the same case when there are 4 to 5 people in the server.

**Comment by electronicboy** [comment]
update. 1.17 is now on the website.

**Comment by apaar24** [comment]
> update. 1.17 is now on the website.

Sir, I m running it on pterodactyl panel .

**Comment by electronicboy** [comment]
You're running an outdated build of 1.17, this has already been fixed

**Comment by apaar24** [comment]
> You're running an outdated build of 1.17, this has already been fixed

ohh okay what about this version
This server is running Paper version git-Paper-55 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: ba7ffd0)
This is from my clients server, is this the latest version sir ?

**Comment by apaar24** [comment]
This server is running Paper version git-Paper-55 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: ba7ffd0)
Still giving problems with this server jar, same issues sir..

**Comment by electronicboy** [comment]
The issue in your original paste has been fixed, there are however similar issues to that which to the untrained eye can look like the exact same issue. Please search the issue tracker for an existing issue or create a new one if one does not exist.

**Comment by apaar24** [comment]
> The issue in your original paste has been fixed, there are however similar issues to that which to the untrained eye can look like the exact same issue. Please search the issue tracker for an existing issue or create a new one if one does not exist.
Where can I find the issue tracker ? I have started both the server with the new server file. Lets see if they crash again or not but I had to give the servers double the ram.

**Comment by electronicboy** [comment]
This is the issue tracker.

Locking this issue, if you need support, please use the discord, messages on here needlessly floods everybody.
