### ISSUE TITLE
#5643 breaks /asw regenworld

### ISSUE THREAD

**Issue by HauserGrim** [PaperMC/Paper#6025]
### Expected behavior

After using /asw regenworld and shutting down the server, region files will be cleared of chunks without claims or deleted if no claims

### Observed/Actual behavior

After using /asw regenworld and shutting down the server, region files are not cleared and caused many identical errors (probably for each region file)
Error: https://pastebin.com/XkDK8SQB

### Steps/models to reproduce

Install autosaveworld fork (link bellow), worldguard, worldedit
/asw regenworld world world/region

ASW fork: https://github.com/HauserGrim/AutoSaveWorld/tree/changes
Jar: https://drive.google.com/file/d/11BVRN6TlVTHQBSSPxBNCVK6Vsz1nlaxH/view?usp=sharing

### Plugin list

AutoSaveWorld*, Essentials, LuckPerms, Vault, WGExtender, WorldEdit, WorldGuard

### Paper version

[22:42:45 INFO]: Checking version, please wait...
[22:42:45 INFO]: This server is running Paper version git-Paper-55 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: ba7ffd0)
You are running the latest version
Previous version: git-Paper-677 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I tried several builds of 1.16.5 and found out that bug appeared in git-Paper-677 (MC: 1.16.5)
Probably, due to some bukkit / craftbukkit patch

**Comment by electronicboy** [comment]
classloaders for plugins are closed on shutdown, meaning that they won't be able to load classes as everything is expected to have closed by then, you'll need to ensure that classes are preloaded for the hook or to do this on startup, this is not behavior we are going to change
