### ISSUE TITLE
add PlayerOperatorStatusChangeEvent 

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6026]
### Is your feature request related to a problem?

No event for player becoming an operator/losing operator status.

### Describe the solution you'd like.

Add PlayerOperatorStatusChangeEvent when an offline player becomes an operator/losing operator status.

### Describe alternatives you've considered.

Checking getOperators() every tick

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by e-im** [comment]
Duplicate of #5792
