### ISSUE TITLE
TreeFeature crash

### ISSUE THREAD

**Issue by natsitarz** [PaperMC/Paper#6028]
### Expected behavior

Chunky just generates world properly.

### Observed/Actual behavior

Chunky crashes server after a while.

### Steps/models to reproduce

1. Get Terra as new world generator.
2. Start server
3. Start chunky
4. Wait (5-10 minutes)
5. Server crashes

### Plugin list

Terra, Chunky

### Paper version

Build #55

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Crash log: https://hastebin.com/wapanopuwo.yaml

**Comment by Chew** [comment]
[00:18:24 ERROR]: This crash report has been saved to: /home/servers/919791/./crash-reports/crash-2021-06-29_00.18.24-server.txt

Can you provide this? We may have a duplicate on our hands.

**Comment by polygorg** [comment]
If anyone needs it, i have error logs from when this occured with me.



I actually removed every cocoa pod from jungle trees but still got the crash. took longer for it to occur tho this time.

Maybe i missed some.

Exception in console: https://pastebin.com/a3XBmyv2
Crash report: https://pastebin.com/kge8nKRa


Edit: 
If you want to reproduce this just get paper 1.17, terra and chunky and generate to ~10000 blocks then enjoy your wall of exceptions.

**Comment by JasonHorkles** [comment]
I've also got this issue with Chunky and Terra, here's my report and logs: https://paste.gg/p/JasonHorkles/9edf161069d74439890b224b4c1d5e62

**Comment by electronicboy** [comment]
Issue here is that chunk generators without leaves will cause a crash when the populator *expects* to have leaves, issue here is that we basically need to work out which populators have this issue and ideally report up to mojang and mitigate this expectation for every tree generator which does this

**Comment by electronicboy** [comment]
or, wait, no, apparently logs?
