### ISSUE TITLE
Strange Client Crash after chunk pre-generation

### ISSUE THREAD

**Issue by NotGolden** [PaperMC/Paper#6029]
### Stack trace

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/28/21 8:38 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at afo.a(SourceFile:128)
	at dkg.a(SourceFile:47)
	at dkr.a(SourceFile:329)
	at dks.a(SourceFile:701)
	at dks.a(SourceFile:349)
	at dzr.a(SourceFile:597)
	at djw.e(SourceFile:1023)
	at djw.e(SourceFile:656)
	at net.minecraft.client.main.Main.main(SourceFile:215)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at afo.a(SourceFile:128)
	at dkg.a(SourceFile:47)
	at dkr.a(SourceFile:329)
	at dks.a(SourceFile:701)
	at dks.a(SourceFile:349)

-- Affected level --
Details:
	All players: 1 total; [dze['GoldenIsCracked'/770, l='ClientLevel', x=-4.50, y=63.00, z=-1.50]]
	Chunk stats: Client Chunk Cache: 529, 78
	Level dimension: minecraft:lobby
	Level spawn location: World: (7,45,-51), Chunk: (at 7,2,13 in 0,-4; contains blocks 0,0,-64 to 15,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 35139 game time, 1098000 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dwl.a(SourceFile:449)
	at djw.c(SourceFile:2183)
	at djw.e(SourceFile:679)
	at net.minecraft.client.main.Main.main(SourceFile:215)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 625726096 bytes (596 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.11, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
```

### Plugin list

Plugins (47): Admin-GUI, AdvancedNMotd, Banstick, BedWars, BuycraftX, ChatColor2, Chunky, ChunkyBorder, CommandPanels, DeluxeHub, DiscordServerConsole*, DiscordSRV, EazyNick, Essentials, ExecutableItems, Factions*, FactionsX, GadgetsMenu, GMusic, GrapplingHook, HolographicDisplays, HolographicExtension, Images, KitPvP, LibsDisguises, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NoCheatPlus, PlaceholderAPI, PlotSquared, ProtocolLib, ServersNPC, SimpleScore, StaffPlus, StaffPlusPlusDiscord, TAB, Themis, Trading*, Vault, VentureChat, ViaBackwards, ViaVersion, WebConsole, WorldEdit, WorldGuard

### Actions to reproduce (if known)

I am unsure of why exactly this crash happens and I cannot find anything on the internet relating as to why it happens, unfortunately.

### Paper version

[03:03:33.844 INFO]: Checking version, please wait...
[03:03:33.923 INFO]: This server is running Paper version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-715 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I am completely unsure of what else I could possibly include. Other than the fact I think it has something to do with simplescore and chunky. I pregenerated a 10k by 10k block square using chunky, which pregenerates chunks, then all of a sudden whenever I load into the server I usually either crash and get that error, or I load in and the scoreboards do not show up at all.

**Comment by electronicboy** [comment]
```
Stacktrace:
	at net.minecraft.util.RewindableStream.a(RewindableStream.java:128)
	at net.minecraft.client.RecipeBookCategories.a(RecipeBookCategories.java:47)
	at net.minecraft.client.color.item.ItemColor.a(ItemColor.java:329)
	at net.minecraft.client.color.item.ItemColors.a(ItemColors.java:701)
	at net.minecraft.client.color.item.ItemColors.a(ItemColors.java:349)
```

replicate without plugins?

**Comment by NotGolden** [comment]
Ummm. Do you want me to reload the server without ANY plugins installed? I do not understand.

**Comment by electronicboy** [comment]
Yes

**Comment by NotGolden** [comment]
Well I know it has something to do with Chunky and SimpleScore. Before I installed chunky and started a pre-gen task, Everything worked as intended. This only started happening as soon as I installed chunky and chunkyborder. Only when I delete my SimpleScore config file and reload the plugin with the default one does it let me join without crashing usually.

**Comment by Alex-mar124** [comment]
It's definitely something to do with either Chunky and/or SimpleScore. as everything was working fine before we installed Chunky,
(im the owner btw not just some random guy commenting lol)

**Comment by e-im** [comment]
This likely isn't a paper issue and this tracker isn't the best place for support as hundreds of folks get emailed for every comment. Please come to our discord at [https://discord.gg/papermc](https://discord.gg/papermc) for future support regarding this issue.
