### ISSUE TITLE
Weird console error?

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6034]
### Stack trace

```
https://paste.gg/p/anonymous/3ab59b9416a84582a35f183ab9caa71e
```

### Plugin list

AdvancedEnchantments, AdvancedPortals, AntiDisconnectSpam,  AutoRestart*, BeastWithdraw, BetterRTP, BlockParticles, BoostedJoin*, ChatSentinel, Chunky, Citizens, CitizensHologram*, CMILib, CommandBlocks, CommunityChest*, CoreProtect, CraftingStore, CrazyAuctions, CrazyCrates, DailyBonus, DeluxeAnnounce, DeluxeMenus, dynmap*, Dynmap-WorldGuard*, EpicRename, EpicSpawners, Essentials, EssentialsChat, EssentialsSpawn, EZRanksPro, FeatherBoard, FlightControl, GSit, Harbor, HeadDatabase, HideAchievements*, HolographicDisplays, HolographicExtension, ItemFilter, Jobs, LeaderHeadsRevamped, LiteBans, LPC, LuckPerms, mcMMO, mcMMOAction, McMMOExtras*, MeteoritesPro, Minepacks, MobEggDrop, MobFarmManager, Multiverse-Core, MyCommand, NightVision*, NoMobGriefing, OpenInv, PlaceholderAPI, PlayerWarps, Playtimes*, PlugMan, PremiumVanish, ProCosmetics, ProtectionStones, ProtocolLib, Quests, QuickShop, ServerListPlus*, ShopGUIPlus, Shopkeepers, spark, SpecializedCrates, STN-Studios-API, TAB, TCPShield, UltimateFishing, Vault, VoidGenerator, VoidSpawn, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldResetPlus*

### Paper version

This server is running Paper version git-Paper-63 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 1d194e5)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
use the search function
