### ISSUE TITLE
Players can't connect to the server 

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6035]
### Expected behavior

Players to connect succesfully to the server

### Observed/Actual behavior

No console erroros:
>.... [09:23:42 INFO]: UUID of player Perdoa is 0300ae1e-8491-3107-b507-5740023339f7
>.... [09:23:42 INFO]: Perdoa lost connection: Disconnected

Player's dissconnect error: 
![image0](https://user-images.githubusercontent.com/44101081/123805906-74cd6080-d8bc-11eb-87c0-c4562862ffc1.jpg)

### Steps/models to reproduce

Very random behaviour, sometimes they can't sometimes they can.

### Plugin list

AdvancedEnchantments, AdvancedPortals, AntiDisconnectSpam, AutoRestart*, BeastWithdraw, BetterRTP, BlockParticles, BoostedJoin*, ChatSentinel, Chunky, Citizens, CitizensHologram*, CMILib, CommandBlocks, CommunityChest*, CoreProtect, CraftingStore, CrazyAuctions, CrazyCrates, DailyBonus, DeluxeAnnounce, DeluxeMenus, dynmap*, Dynmap-WorldGuard*, EpicRename, EpicSpawners, Essentials, EssentialsChat, EssentialsSpawn, EZRanksPro, FeatherBoard, FlightControl, GSit, Harbor, HeadDatabase, HideAchievements*, HolographicDisplays, HolographicExtension, ItemFilter, Jobs, LeaderHeadsRevamped, LiteBans, LPC, LuckPerms, mcMMO, mcMMOAction, McMMOExtras*, MeteoritesPro, Minepacks, MobEggDrop, MobFarmManager, Multiverse-Core, MyCommand, NightVision*, NoMobGriefing, OpenInv, PlaceholderAPI, PlayerWarps, Playtimes*, PlugMan, PremiumVanish, ProCosmetics, ProtectionStones, ProtocolLib, Quests, QuickShop, ServerListPlus*, ShopGUIPlus, Shopkeepers, spark, SpecializedCrates, STN-Studios-API, TAB, TCPShield, UltimateFishing, Vault, VoidGenerator, VoidSpawn, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldResetPlus*

### Paper version

This server is running Paper version git-Paper-63 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 1d194e5)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I'm not sure if this is a paper problem, just wanted to make sure since it wasn't happening before upgrading to 1.17. (Standalone server)

**Comment by Proximyst** [comment]
We can't do much more than assume you've got bad chunks around said player (e.g. a tonne of furnaces in an entire chunk or something along those lines). Reproduce without plugins and send a copy of the affected area/world.

**Comment by ghost** [comment]
I don't think that's the cause, some users after spaming reconnect a lot, could join the server. If it is a bad chunk issue they would never be able to connect.
