### ISSUE TITLE
1.17 not loading saved Entities preventing any new spawning

### ISSUE THREAD

**Issue by AwesomeDude091** [PaperMC/Paper#6038]
### Expected behavior

I expect the world to spawn 1.16.5 entities and it to not block new mob spawning

### Observed/Actual behavior

Well there were no old entities spawned and no new ones either

### Steps/models to reproduce

Load a 1.16.5 world into a 1.17 server

### Plugin list

Multiverse-Core, NashhornPlus, HolographicDisplays, PlotSquared, FastAsyncWorldEdit, CreativeManagement (Custom), Viral-SQL-API (Custom), ProtocolLib, LuckPerms-Bukkit, DiscordSRV, BungeeGuard, Alice, ChatControlRed, BungeeTabListPlus Bukkit Bridge, Multiverse-Portals, Vault

### Paper version

[Server thread/INFO]: This server is running Paper version git-Paper-63 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 1d194e5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

All of the custom plugins are not responsible and the other plugins are running on the latest 1.17 dev builds

**Comment by AwesomeDude091** [comment]
I have no evidence to suggest this, but I think it could be Multiverse Core Plugin as the second server I did this to had similar issues, however a third without Multiverse did not show some Mapping errors or something like that. However that server did not have any entities saved, so I couldn't test :(

**Comment by ghost** [comment]
Hi, I can confirm this issue on my server without any plugins. I tried describing on the discord but mobs are not despawning when you unload chunks or go far away so new ones are not arriving. Hope it helps.

**Comment by ghost** [comment]
STEPS TO REPRODUCE:

1) Spawn enderman in nether
2) Go far away 1 minute
3) Come back -> Mobs are not new generated but the same are at the same place.

PLEASE NOTE : if spectator watches -> everything works fine

ISSUE : BLOCKS SPAWN RATE, farms are dead with mobcap as player spawner mobs per player!!

**Comment by AwesomeDude091** [comment]
I think we are experiencing slightly difference issues, with the same origin. Origin being: Saved Entities not loading.

**Comment by SnickoDeadMC** [comment]
I have an issue that might be similar.
I am using getNearbyEntities() in my plugin and it will return 0 at the location of my armorstands. If I destroy the armorstands, I cannot place any blocks at that location. Although if I /reload the server for some reason the entities are found and return correctly. It's like the entities aren't registered on start although they are registered on /reload.

**Comment by AwesomeDude091** [comment]
Maybe it’s another side effect with the same origin: saved entities not loading on automatic loads (Chunk Loads, World Load) however they load manually (/reload). Seems like either a) somebody forgot to call the method or b) the method is failing during natural processes. Either way this should be fixed!

**Comment by SnickoDeadMC** [comment]
Just did a test and I can't get any entities (even spawned after we updated to 1.17) with Chunk getEntities() on server start.
But if I use /server reload it will find them like normal.
Hope this helps

**Comment by jpenilla** [comment]
> Maybe it’s another side effect with the same origin: saved entities not loading on automatic loads (Chunk Loads, World Load) however they load manually (/reload). Seems like either a) somebody forgot to call the method or b) the method is failing during natural processes. Either way this should be fixed!


> Just did a test and I can't get any entities (even spawned after we updated to 1.17) with Chunk getEntities() on server start.
> But if I use /server reload it will find them like normal.
> Hope this helps

What you are describing sounds like https://github.com/PaperMC/Paper/issues/5872, which is due to behavioral changes by Mojang (chunk and entity storage is now separate).

**Comment by AwesomeDude091** [comment]
If it is that how do we fix it???

**Comment by AwesomeDude091** [comment]
Just checked issue persists on Paper-1.17-69.jar

**Comment by AwesomeDude091** [comment]
Issue persists on Paper-1.17-72.jar

**Comment by AwesomeDude091** [comment]
Issue is resolved in Paper-1.17-75.jar with latest Multiverse Development Builds
