### ISSUE TITLE
Server crash when using world-generation data packs (1.17-R0.1-SNAPSHOT)

### ISSUE THREAD

**Issue by insquared** [PaperMC/Paper#6039]
### Stack trace

```
https://paste.gg/p/anonymous/4b3aa94fe00f42a18b2d2437e2f77c92
```

### Plugin list

none

### Actions to reproduce (if known)

Install these datapacks:
- [William Wythers Overhauled Overworld](https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/)
- [William Wythers' Caves and Cliffs](https://www.planetminecraft.com/data-pack/william-wythers-caves-and-cliffs-add-on-for-overhauled-overworld-1-17/)
- [More Structures for William Wythers' Overhaul](https://www.planetminecraft.com/data-pack/more-structures-add-on-for-william-wythers-overhauled-overworld-1-16-4/)

### Paper version

[14:02:01 INFO]: §f§oChecking version, please wait...
[14:02:01 INFO]: §fThis server is running Paper version git-Paper-64 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 333cc2e)§r
§aYou are running the latest version
![javaw_3dMzrr5V39](https://user-images.githubusercontent.com/74970976/123845820-a6592280-d8e2-11eb-928f-1e1d6c3c8d88.png)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Not really a server-related bug, but as it is a functionality included in base-minecraft, I believe this is worth posting as an issue here.

Cheers!

**Comment by noor-latif** [comment]
According to the dev you can't combine these 2 datapacks yet
William Wythers Overhauled Overworld
William Wythers' Caves and Cliffs

**Comment by jpenilla** [comment]
Are these the only 3 datapacks you have installed? I'm unable to reproduce this using your seed and those 3 datapacks.

**Comment by insquared** [comment]
> Are these the only 3 datapacks you have installed? I'm unable to reproduce this using your seed and those 3 datapacks.


> According to the dev you can't combine these 2 datapacks yet
> William Wythers Overhauled Overworld
> William Wythers' Caves and Cliffs

Ah I have figured it out, it seems there are certain datapacks cause the issue. I thought it was a bug as it was running fine on my local world and on base-spigot test version. Closing.
