### ISSUE TITLE
Drowned copper drops

### ISSUE THREAD

**Issue by Faye-Rhayne** [PaperMC/Paper#6040]
### Expected behavior

So in 1.17, the drowned are supposed to have a 5% chance of dropping copper ingots when the player kills them. 

### Observed/Actual behavior

However, there isn't any copper dropping from them. We've tried kill pits with an actual spawner, going into creative multiple times, spawning at least 100 and killing them, and nothing is dropping copper. 

### Steps/models to reproduce

Kill drowned

### Plugin list

right now, none

### Paper version

Build 64

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by kennytv** [comment]
Deeefinitely not the case. I killed 10 and got an ingot.
