### ISSUE TITLE
Lootable Restocking not emptying old contents

### ISSUE THREAD

**Issue by MissPotato** [PaperMC/Paper#6044]
### Expected behavior

When a loot-able container is opened for a second time the old loot is deleted and the new loot appears. 

### Observed/Actual behavior

Old content is there, items that would fill those slots result in a console message "[Server] WARN Tried to over-fill a container" and the remaining loot is put in valid slots. 

### Steps/models to reproduce

1) Enable lootable restocking
2) Disbale restrict-player-reloot
3) Enable reset-seed-on-fill
4) set min-max to 10s and 20s respectivly 
5) Open chest
6) Close chest
8) Wait 20s 
9) Open chest see old loot and new loot

### Plugin list

Chunkmaster, Essentials, Essentials Chat, Essentials Spawn, Gender, LuckPerms, mcMMO, Placeholder API, PotatoJSONMenu, ProtocolLib, Towny, Vault, VentureChat 

### Paper version

Tested on"
git-Paper-64 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 333cc2e)
git-Paper-65 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 2103ad2)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by lynxplay** [comment]
I can only recreate this if the player does not clear the inventory of the loot chest and not enough slots are available for refilling/filling the loot chest with the loot table the next time the replenish logic is executed.

Concerning there is existing logic to ensure that no existing item in a loot container is overwritten, I would consider this to function as expected.

**Comment by e-im** [comment]
Yes, this is intended behaviour. This setting is not meant to delete peoples items.

**Comment by MissPotato** [comment]
I must be misremembering how this worked in 1.16, thanks for the clarification!
