### ISSUE TITLE
Fox pathfinding loads chunks

### ISSUE THREAD

**Issue by Oscaz** [PaperMC/Paper#6045]
### Timings or Profile link

https://timings.aikar.co/?id=ab3056c8fdee47588e413d86e35317b7

### Description of issue

Foxes seem to load unloaded chunks as part of their pathfinding, and in the process seem to bring the main thread to a standstill for up to 20 seconds at a time.

Electronic said this was likely stalled by light generation, which is what caused such a pause, so this issue is related to
https://github.com/PaperMC/Paper/pull/5863

There is a forum post discussing this issue: https://papermc.io/forums/t/fox-creating-huge-lag/8169

### Plugin list

ClearLag (mostly disabled), CoreProtect, dynmap, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, FeatherBoard, GriefPrevention, GriefPreventionDynmap, LiteBans, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI, PlaceholderAPI, Plugman, ProtocolLib, ServerlistMOTD, Vault, WorldBorder, WorldGuard

### Server config files

Spigot.yml - https://paste.gg/p/anonymous/746a290566c9494fada0a9b670f97a06
Bukkit.yml - https://paste.gg/p/anonymous/aaf6df5d7f974368989e3535ce8d835e
server.properties - https://paste.gg/p/anonymous/f054cd92475b48369aa766e8562e2457

### Paper version

This server is running Paper version git-Paper-56 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 143f381)
You are 10 version(s) behind

(I am aware we are 10 versions behind, no new patches effect this issue)

### Agreements

- [ ] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by DarkArc** [comment]
Suffering from this as well https://spark.lucko.me/w7JKrID5lV

**Comment by Owen1212055** [comment]
The PR that was made to fix this ran into the issue where they were having trouble finding when this would occur.
The most likely "edge case" which was causing this to occur was that this was due to the fox trying to pathfind to 0,0 which has been resolved (https://bugs.mojang.com/browse/MC-198938)

If you are still able to reproduce this issue, please feel free to comment on this and it can be reopened. 😄
