### ISSUE TITLE
Item durability API

### ISSUE THREAD

**Issue by VolanDeMor1** [PaperMC/Paper#6048]
### Is your feature request related to a problem?

Currently, I can't find a working and easy way to change the durability of items and get that durability in the same way. 

### Describe the solution you'd like.

I want to manage the durability of items in ItemStack or ItemMeta, the main thing for me is that it is possible to do it. 

### Describe alternatives you've considered.

I have not tried through sending NMS packets, but perhaps there is such a possibility. 

I tried to do it like this: 
```java
// .setDurability() is deprecated
itemstack.setDurability((short) itemstack.getDurability() - 10);
```
or like this: 
```java
// (Damageable) - org.bukkit.inventory.meta.Damageable
((Damageable) itemstack).setDamage(10);
```
and none of them works. 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by kennytv** [comment]
You have to set the item meta back https://papermc.io/javadocs/paper/1.16/org/bukkit/inventory/ItemStack.html#setItemMeta(org.bukkit.inventory.meta.ItemMeta)
after doing the damageable call (which you have to cast the **ItemMeta** to, not the ItemStack).
