### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by S0M0G** [PaperMC/Paper#6049]
### Is your feature request related to a problem?

I know that you guys have said that you won't be enabling all the bug patches.

### Describe the solution you'd like.

But please do it. It should be optional. I'm planning on changing from paper since i can't use the glitches. The reason I don't want to leave PaperMC is because it has hight performance. You guys want many costumers, right?
Then listen to your costumers and don't tell them you won't add it when I know it is easily possible with a little work.

### Describe alternatives you've considered.

Changing to Spigot

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by e-im** [comment]
See #3854.
