### ISSUE TITLE
Incompatibility with my TNTFlyer plugin ='( 

### ISSUE THREAD

**Issue by TNTUP** [PaperMC/Paper#605]
I use a custom coded plugin to let tnt flying and land on the ground and boom, becomes a block. On contact with redstone the TNT fly as expected and land and explodes into a block (TNT) aswell. But, when I lit two TNT with a flint and steel, I've expected them pushing one at least, but they does nothing. Explodes into a block then the other aswell. There's two videos how what I mean. Sorry my english sucks so I don't know how to explain it properly. Pardon me for using "flv" extension, I've recorded with OBS (not studio) but its playable on modern video player :)

Just saying, this issue isn't so urgent/important, idk where I can fix that issue on my side, idk where to look :S 

### What behaviour is expected:
https://i.qcfb.ca/2017-02-10-0002-47.flv (That'S what I do expect, works nicely on 916.2 (1.10.2)

### What behaviour is observed:
https://i.qcfb.ca/2017-02-10-0006-13.flv (Not expecting this, something changed in 1.11's and 1.11.2 builds which broke the functionality)

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
(See above^^)

### Plugin list:

ViaVersion (does not affect the plugin while testing in 1.10.2 and does not work on 1.11.2) and TNTFlyer (Custom Coded plugin)

### Paper build number:

916.2 ~ 1.10.2 (Works!)
917 ~ 1.11 (Partially)
1055 ~ 1.11.2 (Partially)

I'm bad at java coding so I don't know where to look at, so a commit broke something between 916.2 and 917 (1.11 Update). This issue isn't "important" but help is appreciated what I can do (I'm a java beginner, mostly java noob) xD

**Comment by Tofuus** [comment]
I believe you are looking for `enable-old-tnt-cannon-behaviors: ` in the paper.yml. Just turn it to true to get vanilla tnt behaviour.

**Comment by TNTUP** [comment]
This setting is at false in 1.10.2, so enabling it in 1.11.2 breaks it :/

**Comment by zachbr** [comment]
Have you tested against CraftBukkit and Spigot?

**Comment by TNTUP** [comment]
That's why I switched to Paper since 1.8, TNT Mechanics were better with this plugin. I can give a try on Spigot 1.10.2 and 1.11.2 and expecting not to work.

**Comment by TNTUP** [comment]
1.12-pre2's broke the way this plugin works, was fine with 1.11.2 (using flint and steel still broken) and sometimes the TNT does not fly where it should be (watch the video, I'm so bad at explaining things)

I don't code Java so I don't know what to do (like adding a velocity or somesort of method that can reproduce like it should be in 1.10.2. :( Since I do not know any devs, and my own issue i'll close this issue.

**Comment by TNTUP** [comment]
I've noticed something now, the "knockback" passthrough blocks in 1.10.2, since 1.11 they don't. Sadly I don't code java so I don't know if you guys can help me to let knockback passing through blocks. I tried setVector or setYield they do nothing :(
