### ISSUE TITLE
add option to enable Item duplication on dimension change with hoppers and chest minecarts

### ISSUE THREAD

**Issue by Rabkaleta** [PaperMC/Paper#6053]
### Is your feature request related to a problem?

add
allow-chest-hopper-minecart-portal: bolean

### Describe the solution you'd like.

-

### Describe alternatives you've considered.

-

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other
https://www.spigotmc.org/resources/%E2%98%80-goldendupes-%E2%98%80.91474/

_No response_

**Comment by sulu5890** [comment]
No. See pinned issue.
