### ISSUE TITLE
Shulker does not activate pressure plate

### ISSUE THREAD

**Issue by boardgamezone** [PaperMC/Paper#6054]
### Expected behavior

When a shulker is upside down & 1 block above a pressure plate, the fully opened shell should activate the pressure plate.
![shulker nobug](https://user-images.githubusercontent.com/64791300/124071487-f87c7e00-da71-11eb-9550-6c36edb828f5.png)

### Observed/Actual behavior

A fully opened shell cannot activate the pressure plate.
![shulker bug](https://user-images.githubusercontent.com/64791300/124071057-62e0ee80-da71-11eb-825a-cee10c686a9c.png)

### Steps/models to reproduce

1. Place a shulker a block above a pressure plate, upside down
2. Place a snowgolem 2 blocks away from the shulker
3. After the snowgolem attacks the shulker, its shell will be fully opened
4. Pressure plate will not activate

### Plugin list

No plugin is running

### Paper version

This server is running Paper version git-Paper-68 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: f18dc1e)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by imDaniX** [comment]
Related https://github.com/PaperMC/Paper/pull/6010

**Comment by Machine-Maker** [comment]
Duplicate of #5967

**Comment by ToolReaz** [comment]
UP ! Please fix this so taht we can actually play the game... stop closing issues beacause they are duplicate and then forget to fix it...
