### ISSUE TITLE
Unexpected terrain generation change in the end

### ISSUE THREAD

**Issue by C4K3** [PaperMC/Paper#6055]
### Expected behavior

Terrain generation to remain consistent.

### Observed/Actual behavior

The terrain generation in the end has changed between 1.16.5 build 593 and 594, creating chunk borders between parts of the map generated in each of the two versions.

### Steps/models to reproduce

Start a fresh server on 1.16.5 build 593 (or earlier) and go to anywhere in the end outside the main island (for example 5000 5000.)

Stop the server, and start it again on a newer paper version (I tested on 1.16.5 build 594, 1.16.5 build 779, and 1.17 build 68)

Fly in any direction, you should see chunk borders between the earlier chunks and the newer chunks, as if the seed had changed.

### Plugin list

None

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This is the commit that changed between the two versions https://github.com/PaperMC/Paper/commit/a08be1ec7cfe9a7aa134a073382407c53264fcba

It pulled in this commit https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/9294ebbf051ad7340d7e37265568884439973a4a

# Additional observations

I have not been able to replicate this using spigot.

If you set a seed using `level-seed=` in server.properties, then it doesn't appear to happen.

**Comment by e-im** [comment]
I haven't been able to reproduce this going from 1.16 592 to 1.16 782 or from 1.16 592 to 1.17 110. Is there anything else that needs to be done to reproduce this? or would you be able to provide a world on which this will occur?

**Comment by C4K3** [comment]
With some more testing, it appears to be necessary to delete the world_the_end directory after it's been generated (perhaps to get it to generate with a new seed?)

I.e.

1. Start and stop build 593
2. Delete world_the_end
3. Start build 593, travel somewhere in the end to generate terrain
4. Start build 782, travel further to see chunk borders

I've attached a video showing the issue from scratch.

https://gist.github.com/C4K3/3f706169504fac2c5f89daec78ea05ec/raw/af03126bab21c34492990adb05cdb9543b7b00c7/Screenrecording-2021-07-17_13.50.19.mp4

**Comment by stonar96** [comment]
I have reproduction steps that don't even require updating and it's still an issue in git-Paper-233 (MC: 1.17.1). It's true that git-Paper-594 (MC: 1.16.5) is the first version where this issue occurs. The version git-Paper-593 (MC: 1.16.5) works fine.
Changes by Paper: https://github.com/PaperMC/Paper/commit/a08be1ec7cfe9a7aa134a073382407c53264fcba
Changes by Spigot: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/9294ebbf051ad7340d7e37265568884439973a4a

The issue occurs, when the nether or the end have different seeds as the overworld. Steps to reproduce:

- Start a new server.
- Stop the server.
- Delete world_nether.
- Make sure that no seed is configured in server.properties to generate a random one.
- Start the server.
- Now the nether should have a different seed as the overworld.
- Go to a specific location in the nether and look at the terrain.
- Copy the seed of the nether.
- Load a completely new world (e.g. in singleplayer) with the copied seed.
- Go to the specific location in the nether and compare the terrain.
- The terrain looks different but it shouldn't.

This issue basically (still) breaks all servers with different nether or end seeds.
