### ISSUE TITLE
Players can't close Inventories properly, it keeps refreshing instead even with closeinventory method done

### ISSUE THREAD

**Issue by tehchuanyeow** [PaperMC/Paper#6058]
### Expected behavior

When I click on an Item GUI in an inventory, it's supposed to cancel the event and close the inventory, especially if it were to open a new inventory, the old one would need to close.

### Observed/Actual behavior

When I click on an Item GUI in an inventory, it's supposed to cancel the event and close the inventory, but the Inventory keeps re-opening instead, cause newly opened inventories to overlap with it. Only happened with 1.17 Paper.

### Steps/models to reproduce

InventoryClickEvent
- if (event.getSlot() == 0) {
				player.closeInventory();
}

-Will not close Inventory

### Plugin list

WorldEdit, WorldGuard, Custom Coded Plugin, Multiverse-Core.

### Paper version

This server is running Paper version git-Paper-53 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ad5526)
01.07 22:58:41 [Server] INFO You are 16 version(s) behind
01.07 22:58:41 [Server] INFO Previous version: git-Paper-777 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
the API docs explicitly state not to close inventories in click events, use the scheduler.
