### ISSUE TITLE
Lag every 40 ticks

### ISSUE THREAD

**Issue by JustAlittleWolf** [PaperMC/Paper#6059]
### Timings or Profile link

https://timings.aikar.co/?id=70449b1a905244f0ae0d987097f85ace
https://timings.aikar.co/?id=41db1947638240e18152cc0f6809f501

### Description of issue

Every 40 ticks the server laggs for about 200-500ms. This issue only has occured since a day or so and previously the server had been running fine with the same settings. Render distance is now set to 8 (from 16 no-tick-view-distance) with no performance improvement even though the timings report says it's a chunk loading issue.
The lag starts right after the server start and doesn't stop.
Previously the server has been handling 4+ players fine but now it suddenly lags every 2 seconds with not even a single player online. (The server is not using Aikar's flags because the host prevents it, a total of 4GB ram are installed)

I used spark to see the tick performance (ignoring gc the lag happens precisely every 40 ticks):
![image](https://user-images.githubusercontent.com/54244277/124255930-00e4bf80-db2b-11eb-939f-87f06f24937d.png)

### Plugin list

Plugins (25): AdvancedBan, CoreProtect, DiscordSRV, Essentials, EssentialsAntiBuild, FastAsyncWorldEdit (WorldEdit), Graves, LuckPerms, LWC, LWCTrust, MCInteractive, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, OpenInv, PlaceholderAPI, PlayTime, ProtocolLib, spark, SuperVanish, UltimateFreeze*, Vault, WorldEditSelectionVisualizer, WorldGuard
![image](https://user-images.githubusercontent.com/54244277/124255515-86b43b00-db2a-11eb-864e-33257f90a2d0.png)

### Server config files

https://paste.gg/p/anonymous/646a34fb399148e0b2d736f337bd76e7

### Paper version

This server is running Paper version git-Paper-69 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 882039d)
You are running the latest version
Previous version: git-Paper-66 (MC: 1.17)

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by MiniDigger** [comment]
this just seems like general lag, caused by sync chunk loads.
if you wanna debug those, check "paper syncloadinfo".
there is no bug here.
for further assistance join our discord.

**Comment by JustAlittleWolf** [comment]
The issue was due to the graves plugin which was causing insane lag periodically.
