### ISSUE TITLE
entity-activation-range: not working properly or not strict enough?

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#606]
I've been testing to set the entity-activation-range: to 2, 1 and even 0 for mobs and absolutely all mobs within tracking range still slightly move around, and nearly all of them still attack player from very far away (8+) blocks. Could a strict true/false setting be added to completely disable mob AI so they don't use any cpu at all when outside activation range, and maybe a max range a player can run away from mobs so they deactivate again? If the option is enabled, mob AI would ONLY enable if players get within the activation range, and a second option in paper would be configurable distance from which mob AI turns off again if players move away from mobs, because currently they chase forever and stay activated forever and use cpu until killed or removed by soft/hard despawn range or chunk unload. Currently changing the activation range to low values does very little to help save cpu usage from mobs, still a lot of usage. I tested this with and without a plugin that limits mobs to low values within a players range (for example only 8 mobs can exist near 16 blocks of a player), and with 100> players mob usage is still very high even though there should be less than 1000 active mobs. this is with 64 mobs in bukkit.yml and spawn tick set to 2.

paper 1055

**Comment by aikar** [comment]
it is working as intended. it has an immunity system that lets entities keep their vanilla behavior.

Everything you listed is according to what I want it to do.

I think ultimately, your request is better left to a plugin to do and utilize the built in NoAI flag from Vanilla. Conditionally set it on monsters.

I don't want to add any additional code to EAR that increases EAR's impact to performance, at the detriment to the other 99% of people who would never use it.
