### ISSUE TITLE
[1.17] Bossbars don't update

### ISSUE THREAD

**Issue by zypec** [PaperMC/Paper#6061]
### Expected behavior

Bossbars should update

### Observed/Actual behavior

Bossbars don't update

### Steps/models to reproduce

_I'm using Adventure API_
```java
        BossBar bossBar = data.getBossBar() == null ? BossBar.bossBar(component, 0, BossBar.Color.WHITE, BossBar.Overlay.PROGRESS) : data.getBossBar();
        if (data.getBossBar() == null) {
            data.setBossBar(bossBar);
            getPlayer().showBossBar(bossBar);
        } else {
            data.getBossBar().name(component);
            data.getBossBar().progress(progress);
        }
```

### Plugin list

Only my own plugin

### Paper version

This server is running Paper version git-Paper-69 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 882039d)
You are running the latest version
Previous version: git-AirplanePurpur-8 (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Inxity** [comment]
I can reproduce the issue.

**Comment by zypec** [comment]
And bossbar progress is always %100, never changes

**Comment by BillyGalbreath** [comment]
Can also confirm.

Bukkit API example (works) https://paste.gg/p/anonymous/1de04ce9f9024338a440470a89418225

Adventure API example (broken) https://paste.gg/p/anonymous/40d6276a213c4fc7a8ccf0b886360589

;)
