### ISSUE TITLE
Beacon#setEffectRange not working

### ISSUE THREAD

**Issue by Frogperson** [PaperMC/Paper#6062]
### Expected behavior

Setting a custom range should change the effect radius of the beacon

### Observed/Actual behavior

Beacons keep using their default tier-based range

### Steps/models to reproduce

1. Set a custom range for a beacon with Beacon#setEffectRange
2. Beacon#update (not sure if necessary)
3. Check the range with Beacon#getEffectRange (range appears to be set correctly)
4. Check in-game how far away you are from a beacon when you get the effects, and see it's still the default range.

### Plugin list

Just my Better Beacon Range plugin https://dev.bukkit.org/projects/better-beacon-range which works perfectly in 1.16

### Paper version

This server is running Paper version git-Paper-69 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 882039d)
You are running the latest version
Previous version: git-Tuinity-"7734ef0" (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
Yep, I see the issue here.
