### ISSUE TITLE
Forge

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6064]
### Is your feature request related to a problem?

Because anyone wants it, just noone plays on vanilla (non-minigames) 

### Describe the solution you'd like.

Add forge sup, or gae

### Describe alternatives you've considered.

I dont even know, just add forge :D

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by electronicboy** [comment]
no

**Comment by ghost** [comment]
I am an immature child with no manners.
