### ISSUE TITLE
High usage of ram

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6066]
### Timings or Profile link

https://timings.aikar.co/?id=0ec0d0bfe8d94f5cb2e6cc1763f4a391

### Description of issue

Extreme high usage of ram 👍 

![image](https://user-images.githubusercontent.com/86768261/124318989-ceae7e80-db79-11eb-9f2c-c9819e4fa54e.png)

5 players online good server

### Plugin list

ajStartCommands*, CustomJoinMessages*, CustomText*, DeathBan, EntityDetection, HeartChanger*, LuckPerms, PL-Hide, ProtocolLib, QuantumAPI, QuantumSpawn, TAB, Votifier, VotingPlugin, WooMinecraft

### Server config files

```
Paste configs or paste.gg link here!
```

### Paper version

1.17 69

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
Please use the discord for support, you told java it can use 8G of ram and so it did, this is not an issue.

**Comment by e-im** [comment]
Please come by our discord at https://discord.gg/papermc before making any more issues. Thanks!

**Comment by Chew** [comment]
Finally, high ram usage isn't bad on its own... modern memory collectors are stable enough something something high ram ≠ bad performance, bad performance = bad performance.

**Comment by ghost** [comment]
The thing that is happening is that my server crashes because of high ram usage. All users are kicked and can't log again.

![image](https://user-images.githubusercontent.com/86768261/124322532-e557d400-db7f-11eb-8178-3201c9ee046e.png)

All players are kicked out and we are a few online, as you can see it happening when ram goes above 8GB dedicated

**Comment by electronicboy** [comment]
Please use the discord for support, the issue tracker is not a good place for this as it sends people emails on every message, especially as this is probably just blatent misconfiguration
