### ISSUE TITLE
Cancelling EntityPickupItemEvent doesn't remove items from Villagers

### ISSUE THREAD

**Issue by OmerBenGera** [PaperMC/Paper#6068]
### Expected behavior

When cancelling the EntityPickupItemEvent, villagers should not pick up the item.

### Observed/Actual behavior

It works well when they pickup a new item, however if the item they pickup is modifying another item in the inventory (for example, they have 1 bread and they pick another one), the item is still added (or in other words, the modified item is not reverted as well)

### Steps/models to reproduce

Get a villager with 1 bread in the inventory, drop another bread and check the inventory.
Here is an image of the inventory when the villager tries to pick up a new item:
https://gyazo.com/e1e322a55ae27ff8add97c6e0b54365b

The first line is before the villager tried to pickup the item, the other lines are a few times after he tried to pick it up. He can't pick up more items when the item in the inventory is 64 items.

### Plugin list

A plugin that stops the villagers from picking up items (custom coded, code is shown below)

### Paper version

This server is running Paper version git-Paper-779 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-674 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Cancel pickup event:
```
    @EventHandler
    public void onEntityPickup(EntityPickupItemEvent e){
        if(e.getEntityType() == EntityType.VILLAGER)
            e.setCancelled(true);
    }
```

**Comment by OmerBenGera** [comment]
Forgot to mention that the issue doesn't occur in 1.17, as in 1.17 the inventory is changed only after the event is called, and not before. In 1.16, it's changed before but if the event is cancelled, it's being reverted.

**Comment by Machine-Maker** [comment]
I'm having trouble seeing why this doesn't also affect 1.17? The code surrounding the event looks the same to me.

EDIT: I can reproduce this in 1.17 as well. Issue stems from the copy of the inventory not cloning the itemstacks so that change isn't reverted.

**Comment by OmerBenGera** [comment]
> I'm having trouble seeing why this doesn't also affect 1.17? The code surrounding the event looks the same to me.
> 
> EDIT: I can reproduce this in 1.17 as well. Issue stems from the copy of the inventory not cloning the itemstacks so that change isn't reverted.

My bad, seems to happen on 1.17 as well.
Thanks for looking into that tho
