### ISSUE TITLE
Paper fails to stop processes after shutdown process.

### ISSUE THREAD

**Issue by LemonZup** [PaperMC/Paper#6069]
### Expected behavior

When the stop command is inputted or a crash happens, the server goes through the process of shutting things down and then closes the processes that are running once it finishes. On windows this can result in the window itself closing, on linux with LGSM this can result in the tmux session used for the server being closed. There should be no left over traces in task manager or htop.

### Observed/Actual behavior

The server goes through the process of safely shutting down, but leaves the process running. This leaves the tmux window open or the java window open in win10. There's the log of it having shut down. If you kill the tmux session or close the window for the server, this does not stop it from continuing to run. Processes stay active and utilize resources for what seems to be no reason sometimes. This is shown in Htop; https://i.imgur.com/MrQuYXC.png

### Steps/models to reproduce

For me it is as simple as setting up the jar files and letting the paper server run, and either crashing it intentionally in some easy way or just closing, as the stop command can also be effected.

### Plugin list

This can happen even while not using plugins.
However, my server was actively running
Chunky
ChunkyBorder
CoreProtect
Dynmap
floodgate-spigot
Geyser-spigot
GriefPrevention
LevelledMobs
LuckPerms
MythicMobs
ProtocolLib
Terra
Themis
TradeSystem
WorldEdit-Bukkit
WorldGuard-Bukkit

### Paper version

[04:09:02 INFO]: This server is running Paper version git-Paper-65 (MC: 1.17) (Implementing API version 1.17R0.1 SNAPSHOT) (Git: 2103ad2)
You are 6 version(s) behind
Previous version: git-Paper-55 (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I was told to submit this despite the fact it is for an older version, 65. Since it was fairly recent for the 1.17 branch.
I have included the jstack which was asked for in Discord as well.

https://hastebin.com/fojavagoni.pl

[Jstack6350.txt](https://github.com/PaperMC/Paper/files/6757772/Jstack6350.txt)

**Comment by OopsieWoopsie** [comment]
I'm experiencing the same issue in Paper 1.18.1 (# 197), I start the server normally and when I run the "stop" command, the server goes through the normal shutdown stuff but the server process is still running, I need to press CTRL+C in order to get my command line again.

OS: Ubuntu 20.04 (Desktop)
Java: Temurin 17
