### ISSUE TITLE
Error preventing new logins

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#607]
http://pastebin.com/c1UMRvXG
^this was the first occurrence of the error, then after that it happens for every new login until a server restart

using paperspigot 1055, waterfall 101

I suspect it may have something to do with using paperspigots anti-pushing, then disabling it to use https://github.com/sgtcaze/NametagEdit anti-pushing feature

**Comment by zachbr** [comment]
Nothing here points to this being Paper's fault.
It's not possible for me to rule out bungee or waterfall and how they handle teams, but ultimately the server isn't doing anything that they shouldn't be able to handle.
