### ISSUE TITLE
Configurable keepalive interval

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6074]
### Is your feature request related to a problem?

**I want more accurate ping, keepalive every 15 seconds (hard coded) isn't accurate enough for my needs, it should be configurable.**

### Describe the solution you'd like.

**Paper config option keepalive interval or system property**

### Describe alternatives you've considered.

**Sending keepalive packets myself and using protocollib to stop the reply before it kicks the player for invalid id**

**ping/pong packets will not work since they are delayed clientside (not accurate)**

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by boonsboos** [comment]
duplicate of #5930? you already opened an issue for this 2 weeks ago
