### ISSUE TITLE
Server not starting again using /restart.

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6075]
### Stack trace

```
https://paste.gg/p/anonymous/61c4b47a2ae94d9fa5d3604cb4f9720e
```

### Plugin list

AdvancedEnchantments, AdvancedPortals, AntiDisconnectSpam, AutoRestart*, BeastWithdraw, BetterRTP, BlockParticles, BoostedJoin*, ChatSentinel, Chunky, Citizens, CitizensHologram*, CMILib, CommandBlocks, CommunityChest*, CoreProtect, CraftingStore, CrazyAuctions, CrazyCrates, DailyBonus, DeluxeAnnounce, DeluxeMenus, dynmap*, Dynmap-WorldGuard*, EpicRename, EpicSpawners, Essentials, EssentialsChat, EssentialsSpawn, EZRanksPro, FeatherBoard, FlightControl, GSit, Harbor, HeadDatabase, HideAchievements*, HolographicDisplays, ItemFilter, Jobs, LiteBans, LPC, LuckPerms, mcMMO, McMMOExtras*, MeteoritesPro, Minepacks, MobEggDrop, MobFarmManager, Multiverse-Core, MyCommand, NightVision*, NoMobGriefing, OpenInv, PlaceholderAPI, PlayerWarps, Playtimes*, PlugMan, ProCosmetics, ProtectionStones, Quests, QuickShop, ServerListPlus*, ShopGUIPlus, Shopkeepers, spark, SpecializedCrates, STN-Studios-API, TAB, TCPShield, UltimateFishing, Vault, VoidGenerator, VoidSpawn, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldResetPlus*

### Actions to reproduce (if known)

use /restart

### Paper version

This server is running Paper version git-Paper-71 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ae6dd2)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
Please read spigot's docs on /restart as well as [this gist about how to use it "properly"](https://gist.github.com/Prof-Bloodstone/6367eb4016eaf9d1646a88772cdbbac5). The stack trace you got is because you have debug mode enabled.
