### ISSUE TITLE
Invisibility glitch

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6082]
### Expected behavior

All players are visible to everyone.

### Observed/Actual behavior

All players were invisible, there was no effect on them, there was no plugin that could cause this. The chat was still usable, and everyone could talk. You can see block-breaking effects also

### Steps/models to reproduce

- Get paper 1.16
- Install the plugins: Skript, skript-reflect, skript-yaml, Vixio
- Link it to a bungee cord server (Travertine)
- Set the server to offline-mode
- Have multiple players on the server

### Plugin list

Skript, skript-reflect, skript-yaml, Vixio

### Paper version

This server is running Paper version git-Paper-779 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Paper.

### Other

I had the same issue on another 1.16 server, but with different plugins, this is why I think it is an issue in paper.

**Comment by e-im** [comment]
Travertine is no longer supported, however try disabling tablist rewriting in waterfall.yml. Beyond that, replicate without plugins and come by our [discord](https://discord.gg/papermc) for future support with this issue.
