### ISSUE TITLE
Using world generation plugin causes end portals to be breakable. 

### ISSUE THREAD

**Issue by Evidentsinger14** [PaperMC/Paper#6083]
### Expected behavior

When using a custom world generation plugin *Only tested on [Terra](https://www.spigotmc.org/resources/terra.85151/)*, end portals can be broken by mushrooms, or any block that expands out when sprouting. I expected it the mushroom blocks to be destroyed, leaving the portal blocks in tact. 

### Observed/Actual behavior

the portal blocks were replaced by mushrooms. 

### Steps/models to reproduce

install latest version of paper for 1.16.5, install version 5.3.3-BETA of Terra, (newer version errors on startup), add the world generator option to bukkit.yml, start server, make an end portal, and plant a mushroom a few blocks away. 

### Plugin list

Terra 

### Paper version

This server is running Paper version git-Paper-779 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by MiniDigger** [comment]
why would this be a paper issue?
if a plugin modifies world gen, its their responsibility to make sure to not break vanilla stuff like this, _especially_ since plugin like these hack around our apis in the internals.

**Comment by Ricardo11v** [comment]
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2486677,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by MiniDigger** [comment]
diiiid you just try to XSS github? lol

**Comment by Evidentsinger14** [comment]
I have no idea why it'd be a paper issue. I was referred here, to make an issue for it. Seeing as it was *in the paper discord* that i was told to make an issue here, i did.

**Comment by dfsek** [comment]
>  if a plugin modifies world gen, its their responsibility to make sure to not break vanilla stuff like this, especially since plugin like these hack around our apis in the internals.

Instead of making dubious claims about the stability of our plugin and the extent to which it is well-made, could you do some testing first? We do not access *any* server internals in our Bukkit implementation. Those mushrooms are generated using `org.bukkit.World#generateTree`. I'm assuming the issue is that this method does not check for unbreakable blocks. In that case it would actually be a Paper issue.

**Comment by electronicboy** [comment]
We don't have the time nor ability to deep dive into every single "vanilla doesn't do this but when I have X a plugin installed it works differently"

Minis statement was a general statement that world gen type plugins often mess with their own stuff, and if there is in fact a behavioral difference, it's often up to plugins to deal with, especially as in this region they often mess with server internals


The generateTree method ends up calling into the vanilla gen system to do it's work, it's generally up to plugins to ensure that they're generating in the place they want, I don't think that patching every single tree feature to care about where it's tryna place is viable, from a "not breaking vanilla" perspective and a maintainability perspective
