### ISSUE TITLE
Anti clay mining

### ISSUE THREAD

**Issue by agoniaprivat** [PaperMC/Paper#6086]
### Is your feature request related to a problem?

Please add a way to remove the Clay Mining technique. It's destroying the survival feeling.
https://www.youtube.com/watch?v=Ufkx7j67Unk

### Describe the solution you'd like.

Change the diamond generation somehow.

### Describe alternatives you've considered.

Removing diamonds from the map.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by boonsboos** [comment]
asking a project that aims to improve performance and fix bugs to change vanilla behaviour, wonder how that'll go

**Comment by electronicboy** [comment]
A lot of this stuff just needs more configurable seeds vs having one source of truth, headache is all the patchwork required for that unless mojang does the frameworking for it, defo something we generally want, just, better delivered by mojang :/

**Comment by agoniaprivat** [comment]
> asking a project that aims to improve performance and fix bugs to change vanilla behaviour, wonder how that'll go

This is clearly a bug.

**Comment by HexedHero** [comment]
> > asking a project that aims to improve performance and fix bugs to change vanilla behaviour, wonder how that'll go
> 
> This is clearly a bug.

No, it's not a bug. It's just how the world generation works people are just finally reverse engineering it.

**Comment by Chew** [comment]
I've been told this has been "patched" on 1.17 due to the new world generation, so I don't expect a feature of this size to be ported back.

**Comment by iOshawott** [comment]
There's more than clay, https://www.youtube.com/watch?v=XRk06ih6rBU I see it works with lapis too, welp. Mojang pls :|

**Comment by kayvanbree** [comment]
Imo this is not a bug, just the way world generation works. Also, it has been there since 1.14 according to [this video](https://www.youtube.com/watch?v=MkKSzPi2XTM). In my opinion this is a discovery, like when they found out the best Y level to mine was 11 or that geodes are easy to find by just looking at the ocean floor. 

I think a Spigot plugin would be a more suitable place for a change like this, and I don't know if there's any precedent of changing vanilla world generation in PaperMC.

**Comment by Proximyst** [comment]
There is defiitely precedent for changing how certain features are generated. This is, in my opinion, a beneficial change for SMP servers if placed behind a configuration option. Accepting feature request.

**Comment by D3V1LC0D3R** [comment]
there are several projects that are trying to fix this, here is one of them:
https://github.com/Earthcomputer/SecureSeed

**Comment by e-im** [comment]
https://github.com/PaperMC/Paper/commit/7bd7b188117821656094e1e95d94aa7722cf8f73
