### ISSUE TITLE
Teleporting Issue

### ISSUE THREAD

**Issue by coco0325** [PaperMC/Paper#6090]
### Expected behavior

Player should be teleported to the specified location after being sent to the server.

### Observed/Actual behavior

When player being sent to the server first time after the server start, the player won't be teleported to the specified location. Instead, the player just stay at the location where it left.

A interesting thing is, the issue only occurs when the  player logs in for the first time after the server start.

### Steps/models to reproduce

Start the server and use masuite plugin to teleport to a location in the server. 

### Plugin list

MasuiteCore, MasuiteTeleports, MasuiteWarps, MasuiteHomes

### Paper version

This server is running Paper version git-Paper-"06b0b573d" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Here''s the code of how the teleporting system works.
https://github.com/masagameplay/MaSuiteHomes/blob/master/src/main/java/dev/masa/masuitehomes/bukkit/HomeMessageListener.java

The issue won't happen when using early Paper builds (1.16.5)

**Comment by Fejm** [comment]
Plugin issue

**Comment by coco0325** [comment]
> Plugin issue

The issue won't happen when using early Paper builds (1.16.5)

**Comment by Crousus** [comment]
Try to increase the teleportation delay in the Masuite Plugin config
