### ISSUE TITLE
Massive chunk loading lag on login, vanilla teleportation, etc

### ISSUE THREAD

**Issue by Apprisco** [PaperMC/Paper#6092]
### Timings or Profile link

https://spark.lucko.me/ixyNFg322m

### Description of issue

5-6 players logging in, teleporting, etc will cause massive mspt spikes, over 80 mspt.
Tested on Paper, Tuinity, and Purpur
Tested on 4 machines, set to vd 4
Profile above was a single player logging in, ticks over 10.
Issue seems to be due to chunk loading possibly.

Purpur and Tuinity had identical results.
Machine 1:
Dual xeon x5690, ddr 1333mhz
paper: 1 player 25mspt, 2 players 53mspt, 3 players 76mspt
purpur: 1 player 22mspt, 2 players 51mspt, 3 players 73mspt

Machine 2:
i7 2600, similar class of performance to xeon x5690
nearly identical results.

Machine 3:
AMD 3100, much better single threaded performance
paper: 1 player 18mspt, 2 players 37mspt, 3 players 56mspt
purpur: 1 player 15mspt, 2 players 34mspt, 3 players 53mspt

Machine 4:
Oracle ARM Ampere cloud host, with a sysbench of over 3000 single threaded compared to the xeon's 1015
paper: 1 player 17mspt, 2 players 43mspt, 3 players 67mspt
purpur: 1 player 21mspt, 2 players 38mspt, 3 players 61mspt

All tests were performed with mob-spawning set to false.

### Plugin list

Tested with & without any plugins.
Tested with & without any datapacks.

### Server config files

Bukkit:
settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 4000
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server closed
  minimum-api: none
spawn-limits:
  monsters: 100
  animals: 15
  water-animals: 15
  water-ambient: 15
  ambient: 15
chunk-gc:
  period-in-ticks: 400
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  water-spawns: 1
  water-ambient-spawns: 1
  ambient-spawns: 1
  autosave: 6000
aliases: now-in-commands.yml

Paper:
default paper config.

Spigot:
default spigot config.

### Paper version

Purpur version:
This server is running Purpur version git-Purpur-1251 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: b2fe934 on HEAD)
You are 4 version(s) behind
Previous version: git-Purpur-1247 (MC: 1.17)

Paper version: 
This server is running Paper version git-Paper-79 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) 

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Apprisco** [comment]
Tested the async chunk loading using AsyncPreLoginEvent with a plugin, using sync-load chunks to load before player joins.
MSPT spike is significantly worse, meaning issue is likely not async-chunk loading.

**Comment by Fernas99** [comment]
I have the same problem, a does not depend on the cpu, as it only happens to some people, and no it is not for the connection, we all have at least 60mb download. the problem also does not occur only during login but also during the loading of the chunks so as you go around, and needless to say that with 1 player on the hub with a dedicated i9 9900k it is an async problem, since the main thread is very free.

**Comment by Tsoccerguy3** [comment]
Sounds like the legacy checking of player ID's . Convert the cache or purge all. Goto the Wiki to learn how

**Comment by elpocoburrito** [comment]
> Goto the Wiki to learn how

Haven't found anything in the paper documentation, is that what you refer to as "the wiki"? Google didn't help either. Mind giving a link if possible?

**Comment by Apprisco** [comment]
> Sounds like the legacy checking of player ID's . Convert the cache or purge all. Goto the Wiki to learn how

Definitely not my issue, there's literally 3-5 players maximum on this smp.

**Comment by Apprisco** [comment]
I should clarify, this only happens when the server has restarted or I am teleporting. Issue is reproducible in 1.16.5.
The reason I am convinced this is chunk loading of some kind is that when i relog, issue does not happen at all.

**Comment by Apprisco** [comment]
Solution: this is solved mostly by upgrading the storage solution lol
