### ISSUE TITLE
AsyncPlayerChatEvent causes hover events to not work.

### ISSUE THREAD

**Issue by TauCu** [PaperMC/Paper#6093]
### Expected behavior

As AsyncPlayerChatEvent is called first it shouldn't affect hover events added in AsyncChatEvent.

### Observed/Actual behavior

when AsyncPlayerChatEvent is registered by either itself or another plugin it seems to strip hover events from modified chat messages.

### Steps/models to reproduce

1) The code that is used to reproduce this:
```java
@EventHandler
    public void onChat(AsyncChatEvent e) {
        log("AsyncChatEvent");
        e.message(Component.text("Hover?")
                .hoverEvent(HoverEvent.showText(
                        Component.text("Floaty Text")
                        ))
                );
    }
    
    @EventHandler
    public void thatOtherGuy(AsyncPlayerChatEvent e) {
        log("AsyncPlayerChatEvent");
    }
    
    public static synchronized void log(String m) {
        //what event gets called first? (AsyncPlayerChatEvent)
        System.out.println(m);
    }
```
2) Type something in chat

### Plugin list

The testing plugin

### Paper version

[23:03:14 INFO]: Checking version, please wait...
[23:03:14 INFO]: This server is running Paper version git-Paper-79 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: a831634)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by MiniDigger** [comment]
message is imuutable, you gotta re-set it

**Comment by kezz** [comment]
looking at that code, it is being set properly?

**Comment by MiniDigger** [comment]
urg, missing formatting makes it impossible to see

**Comment by jpenilla** [comment]
This is due to how the legacy renderer works, and there isn't really a good way to fix it without breaking the expected behavior of the legacy chat events.

```java
private static ChatRenderer legacyRenderer(final String format) {
    return (player, displayName, message, recipient) -> PaperAdventure.LEGACY_SECTION_UXRC.deserialize(
        String.format(format, legacyDisplayName((CraftPlayer) player), PaperAdventure.LEGACY_SECTION_UXRC.serialize(message))
    ).replaceText(URL_REPLACEMENT_CONFIG);
}
```

When the legacy event has listeners, the legacy renderer is used to allow for the format set by legacy events to be used.

In your listener for the modern event, you could do something like
```java
AsyncChatEvent event;
event.renderer(ChatRenderer.defaultRenderer());
```
to work around this, but it would obviously discard the format set by legacy events.

One thing we could do, is to use `ChatRenderer.defaultRenderer();` instead of the `legacyRenderer` if legacy events were fired, but the format was never modified. This would solve the issue in your example code, but again if you had a legacy plugin setting a formatter this wouldn't help.

**Comment by TauCu** [comment]
Yep, that fixed it. Cheers.
As far as a better solution goes:
Couldn't you make it so the legacy renderer is only used when a plugin modifies the format, rather than changing it if a plugin merely registers the event?

**Comment by jpenilla** [comment]
Yeah, that would be a possible improvement
> One thing we could do, is to use `ChatRenderer.defaultRenderer();` instead of the `legacyRenderer` if legacy events were fired, but the format was never modified. This would solve the issue in your example code, but again if you had a legacy plugin setting a formatter this wouldn't help.
