### ISSUE TITLE
TNT is updated after relog. 1.17

### ISSUE THREAD

**Issue by Nervaq** [PaperMC/Paper#6094]
### Expected behavior

With feature allow-piston-duplication enabled TNT duplication should work as inteded in Vanilla.

### Observed/Actual behavior

TNT duper works fine until I relog then chunks get updated and so as TNT and it blows up.

### Steps/models to reproduce

1.Assemble regular TNT duping module.
2. Test if it works.
3. Disconnect
4. Then reconnect.

If you won't be able to recreate it. Just try to forceload and unload chunks.
It was tested on #69 #75 #79 builds all with the same behavior.

### Plugin list

![](https://cdn.discordapp.com/attachments/711251759766700034/861962567022018610/unknown.png)

![](https://media.discordapp.net/attachments/711251759766700034/861961085220552724/unknown.png)

### Paper version

Newest installed build #79 tested on 2 servers 

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Whenever you load chunks with TNT duper and then teleport somewhere else. Then teleport back TNT recieves update.
We tested this on 2 different servers with plugins attached on multiple builds including #69 #71 #75 #79

**Comment by Proximyst** [comment]
No support for unsupported options...

**Comment by Eagllus** [comment]
I think it's a bit more complicated than "unsupported option"

Having TNT duplicator enabled, I can move outside of the load area and walk back in without having it getting triggered.

This means entities get loaded without getting updated and once they get updated because you are closer everything is still fine.

But entities that get loaded also get an update right away.
This to me sounds like a lot bigger issue than just the TNT duplicator

**Comment by Eagllus** [comment]
Addition: I tested it with having piston duplication disabled and on loading of the chunk TNT still explodes

**Comment by Proximyst** [comment]
It's more likely that the entity ticks before its chunk does, which might very well be possible as entities and chunks are loaded separately now.

**Comment by Eagllus** [comment]
Thanks for the quick response but wouldn't that qualify as a bug behavior?

This might have nothing to do with the TNT duplicator even though it's getting affected by it.

**Comment by Proximyst** [comment]
Not necessarily. There's no reason an entity shouldn't be ticked before its chunk is loaded as long as the entity doesn't need it.

That being said, I do believe entities should not be added to the world before the chunk is fully read and loaded as we defer this process.

If this is proven to actually be a bug, a new issue is welcome, but I'm not able to check the code for any obvious hints to this right now.

**Comment by Eagllus** [comment]
@Proximyst I created a new issue for this https://github.com/PaperMC/Paper/issues/6168

I don't think it's a high priority bug but I haven't tested many cases with entities being loaded in this way.

**Comment by Eagllus** [comment]
@Nervaq I used the command `/forceload` to keep the chunk loaded and it resolved my problem.
Hopefully this helps you

**Comment by jkoenigschulte** [comment]
I think its very mean how you guys just say: naah, we wont fix that. Many people are dependend on your optimizations, and it would be unfair not to fix that bug, since it cleary is a bug, even though it may not be an intended setting. I can assure you that you are loosing many customers if you continue treating your clients like this! This is also the reson why for example many big servers like Hermitcraft dont use your software. Please reconsider!

**Comment by NoahvdAa** [comment]
> I think its very mean how you guys just say: naah, we wont fix that. Many people are dependend on your optimizations, and it would be unfair not to fix that bug, since it cleary is a bug, even though it may not be an intended setting. I can assure you that you are loosing many customers if you continue treating your clients like this! This is also the reson why for example many big servers like Hermitcraft dont use your software. Please reconsider!

This was already fixed in #6241.

**Comment by jkoenigschulte** [comment]
Oh wow, ok. Thanks for the quick reply! So, if I update my Paper Sever from 1.17 to 1.18.1, my tnt dupers will no longer explode by themselves after time? Or when I reload their chunks?
