### ISSUE TITLE
1.17.1 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [PaperMC/Paper#6095]
### Is your feature request related to a problem?

Minecraft 1.17.1 has been released.

### Describe the solution you'd like.

An update of Paper for 1.17.1.

### Describe alternatives you've considered.

-

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by kennytv** [comment]
We aren't wizards, and we don't need people to tell us a Minecraft update has been released either.

**Comment by TheIntelloBox** [comment]
Sorry for wanting to help you.

**Comment by Proximyst** [comment]
you're welcome
