### ISSUE TITLE
Not loading chunks

### ISSUE THREAD

**Issue by PaulGod** [PaperMC/Paper#6096]
### Expected behavior

I would expect to see the chunks being checked and reloaded

### Observed/Actual behavior

So in the nether (1.17) there were tons of unloaded chunks that if you got into there is no way to get out of.

### Steps/models to reproduce

I am not sure I just went into the nether and the chunks were unloaded.

### Plugin list

floodgate, Geyser-Spigot, PlugMan, ProtocolLib, RAMAutoRestart, Skript, Themis

### Paper version

When I did this the server broke I believe it is [a831634]

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I am not sure what else to say.

**Comment by e-im** [comment]
There isn't really enough here to pursue anything and there are already numerous issues tracking problems like this, just going to call it a duplicate of #5980, #6212 or similar issues.
