### ISSUE TITLE
Enchantments can go past the limit.

### ISSUE THREAD

**Issue by Vulnerab1lity** [PaperMC/Paper#6111]
### Expected behavior

The maximum enchantment size should be 255.

### Observed/Actual behavior

You can go up to 2147483647

### Steps/models to reproduce

/give @p minecraft:netherite_sword{Enchantments:[{id:"sharpness",lvl:2147483647}]}

### Plugin list

A custom plugin that allows you to see NBT data of an item.

### Paper version

[15:36:51 INFO]: Checking version, please wait...
[15:36:51 INFO]: This server is running Paper version git-Paper-85 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b5be382)
You are 1 version(s) behind

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

![image](https://user-images.githubusercontent.com/42952817/124768623-1c8c0380-df39-11eb-94a8-88d6fe083507.png)

It says 255 when hovering over the item, but in reality it's over that.

**Comment by kennytv** [comment]
Doesn't matter, it's always clamped when read or rewritten.
