### ISSUE TITLE
Able to login to multiple Servers on latest release

### ISSUE THREAD

**Issue by Hailey-Ross** [PaperMC/Paper#6114]
### Timings or Profile link

https://timings.aikar.co/?id=cc4435f910544c6e936264a95d89e312

### Description of issue

I was testing the latest release of Paper 1.17.1-86 before moving my server to it. However, when I looked at my 1.17 instance I noticed I had not been logged out like I normally am whenever I join my test server.

### Plugin list

None enabled atm, just running the following datapacks from VanillaTweaks.net:

[file/confetti creepers v2.2.0.zip (world)], 
[file/multiplayer sleep v2.6.1.zip (world)], 
[file/player head drops v1.1.0.zip (world)], 
[file/spectator night vision v1.1.0.zip (world)],
[file/graves v2.8.2.zip (world)], 
[file/elevators v1.0.1.zip (world)], 
[file/timber v2.1.1.zip (world)], 
[file/double shulker shells v1.3.0.zip (world)], 
[file/larger phantoms v1.2.1.zip (world)], 
[file/more mob heads v2.9.1.zip (world)]

### Server config files

https://paste.gg/p/anonymous/caf2d736d6f74a9a82f451add2c0e09f

### Paper version

This server is running Paper version git-Paper-86 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 144e5f7)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Hailey-Ross** [comment]
Here is a video of it in action:
https://www.youtube.com/watch?v=SDlLQYWp6ps

**Comment by kennytv** [comment]
You can login to as many servers as you like simultaneously, that has nothing to do with the server software. The only thing you can't do is join the same backend server twice.
