### ISSUE TITLE
Cloning certain tile entities causes error.

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6122]
### Expected behavior

Cloning tile entities shouldn't cause an error in server log.

### Observed/Actual behavior

When cloning tile entities such as chests, dropper, hopper, the server log shows an error. It's always in the form of:

`[11:37:36] [Server thread/ERROR]: Block at -13, 95, 66 is Block{minecraft:barrier} but has net.minecraft.world.level.block.entity.TileEntityDispenser@4bb80d19. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.`

Above here Dispenser will be replaced by the tile entity name.

### Steps/models to reproduce

1. Place down a chest
2. Use the /clone command to clone the chest to another location.
3. The server log shows an error.

### Plugin list

No plugins are running.

### Paper version

 This server is running Paper version git-Paper-90 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bb44da8)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Looks like a duplicate of #2786, which had been fix by Spigot before. Seems like the issue has returned.

Spigot fix commit:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/75fac431cfc807ccf05629ce4796db958ee112e6

Original Spigot bug report:
https://hub.spigotmc.org/jira/browse/SPIGOT-5472

**Comment by ghost** [comment]
Why I used "certain" in the title is because the error doesn't seem to appear for every tile entity.
(I looked up a list from https://minecraft.fandom.com/wiki/Block_entity)

For example spawners/lecterns/signs/beacons work just fine.

**Comment by Doc94** [comment]
This happen in spigot too...
and dont understand why the type block is `Block{minecraft:barrier}` if (in my case) the replaced block was a chest.
![image](https://user-images.githubusercontent.com/3602279/124936489-99b88680-dfd4-11eb-8d86-69ca2aebbbd3.png)
![image](https://user-images.githubusercontent.com/3602279/124936544-a76e0c00-dfd4-11eb-8221-71f37b2b5bc8.png)

**Comment by Doc94** [comment]
This issue can be close (or wait for the Updated Upstream) because CrafftBukkit commit a fix for this:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/be8d625e3e56184d5b2451fa4a157f6907678166
