### ISSUE TITLE
Random server world generator seed offset variable

### ISSUE THREAD

**Issue by MeowRay** [PaperMC/Paper#6123]
### Is your feature request related to a problem?

Anti SeedCracker e.g:KaptainWutax

### Describe the solution you'd like.

Provide a random offset, modify the vanilla world generator, so that it can anti SeedCracker

### Describe alternatives you've considered.

nothing

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by MeowRay** [comment]
For most survival mode servers default world generator is too dangerous. 
We should modify the calculation method of seed

**Comment by boonsboos** [comment]
already exists, check spigot.yml

**Comment by MeowRay** [comment]
> already exists, check spigot.yml

Which one? Players can still generate the same world as the server locally through seeds

**Comment by MeowRay** [comment]
> already exists, check spigot.yml

Modify the seed settings of spigot.yml can it be Anti SeedCracker?

**Comment by boonsboos** [comment]
_probably_

also, do keep in mind you can edit your comments on github.

**Comment by MeowRay** [comment]
> _probably_
> 
> also, do keep in mind you can edit your comments on github.

My server is running paper 1.17 and unfortunately it is still cracked

**Comment by electronicboy** [comment]
Essentially a duplicate of #6086
