### ISSUE TITLE
Fawe newest 

### ISSUE THREAD

**Issue by zombihunterbonn** [PaperMC/Paper#6124]
### Expected behavior

Not working with fawe newest version, server instant crash 

### Observed/Actual behavior

Fix it pls

### Steps/models to reproduce

.......

### Plugin list

........

### Paper version

..........

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

........

**Comment by e-im** [comment]
For future issues, ensure you have filled out the form correctly with all relevant information such that your issue can be properly looked at. In this case however, report this to FAWE support and if they believe this to be a paper issues, open a new issue.
