### ISSUE TITLE
EnchantedFurnace incompatibility

### ISSUE THREAD

**Issue by Jikoo** [PaperMC/Paper#613]
### What behaviour is expected:
The Efficiency enchantment on furnaces causes EnchantedFurnace to reduce smelting time.
### What behaviour is observed:
Smelting time is reduced, but once the smelt is completed the next does not appear to start until the full 10 seconds for a vanilla smelt have completed or the item in the top of the furnace is changed.

### Steps/models to reproduce:
* Install EnchantedFurnace 1.6.3
* Obtain any enchanted furnace and place it (`/give @p minecraft:furnace 1 0 {ench:[{id:32,lvl:5}]}`)
* Insert fuel and smeltables, observe.

From user reporting the issue: https://www.youtube.com/watch?v=XrgeqPS365g

### Plugin list:
[EnchantedFurnace](https://dev.bukkit.org/projects/enchantedfurnace) 1.6.3

### Paper build number:
1059

### Additional info:
The root of the bug is the patch [fixing furnace cook time](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0073-Fix-Furnace-cook-time-bug.patch)
```Java
this.cookTime -= this.a(this.items.get(0)); // Paper
```
In the event that `cookTimeTotal` has been altered, the value of `cookTime` can become negative. The next smelt then does actually start, but due to the negative `cookTime` does not display until positive.
The line in question should instead be `cookTime -= cookTimeTotal;`. There's no need to "recalculate" (though in vanilla it's currently fixed) `cookTimeTotal`, it's recalculated when the item in slot 0 is changed.

Edit: I've fixed this on my end by correcting negative cook time when encountered, but this should also likely be fixed on yours, if only to prevent useless calculations if Mojang does ever implement materials with other cook durations.

**Comment by zachbr** [comment]
I have just pushed a fix to this to master, in my haste to do so I did not amend the author to you as I intended.

This fix will appear in builds 1061+
Thank you for your detailed report and the suggested fix. We appreciate it.

Apologies for the delay, most of us have been busy with other things as of recent.
Cheers.
