### ISSUE TITLE
clickEvent:action run_command tellraw gives permission error for players

### ISSUE THREAD

**Issue by ikuria** [PaperMC/Paper#6138]
### Expected behavior

the tellraw, when clicked the sign as player

### Observed/Actual behavior

I'm sorry, but you do not have permission to perform this command. 

### Steps/models to reproduce

`/give playername oak_sign{BlockEntityTag:{ Text1:"{\"text\":\"---------------\", \"clickEvent\":{\"action\":\"run_command\",\"value\":\"/tellraw @p [{\\\"text\\\":\\\"test\\\",\\\"color\\\":\\\"yellow\\\",\\\"bold\\\":true},{\\\"text\\\":\\\"\\\\ntest\\\",\\\"color\\\":\\\"white\\\",\\\"bold\\\":false}]\"}}", Text2:'{"text":"test","color":"yellow"}', Text3:'{"text":"test","color":"white"}', Text4:'{"text":"---------------"}'}, display:{Name:'{"text":"Custom Sign"}'}, id:"Sign"}`

### Plugin list

no plugins, testserver

### Paper version

paper-1.17.1-91

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

https://github.com/PaperMC/Paper/commit/648f6078d77876217b90dcea644a4e5c68c2e132

**Comment by Machine-Maker** [comment]
Almost certainly caused by 648f6078d77876217b90dcea644a4e5c68c2e132

**Comment by electronicboy** [comment]
100% caused by that

```java
    public CommandSourceStack createCommandSourceStack(@Nullable ServerPlayer player) {
        String s = player == null ? "Sign" : player.getName().getString();
        Object object = player == null ? new TextComponent("Sign") : player.getDisplayName();

        // CraftBukkit - this
        return new CommandSourceStack(this, Vec3.atCenterOf((Vec3i) this.worldPosition), Vec2.ZERO, (ServerLevel) this.level, 2, s, (Component) object, this.level.getServer(), player);
    }
```
    
is how the server executes it, we basically made it lose the context of the sign being the executor and turned it into the players role

**Comment by Proximyst** [comment]
This is a fairly low priority issue; prefer plugins to handle commands like this (hey, EssentialsX has this!).

**Comment by ikuria** [comment]
thats vanilla, so its priority for us - we have that kind of signs all over the servers to inform the players!
