### ISSUE TITLE
Matchmaking material data in anvils

### ISSUE THREAD

**Issue by GJSteve20** [PaperMC/Paper#6140]
### Expected behavior

Image down

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/44862419/125145718-0cd41100-e12b-11eb-8260-8a280a148015.png)

### Steps/models to reproduce

I don't think they are necesarly

### Plugin list

Nope

### Paper version

1.17 and 1.17.1 too

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
I'm assuming you figured out the issue?
