### ISSUE TITLE
Web links generated from command blocks or broadcast plugins are no longer clickable

### ISSUE THREAD

**Issue by Tsoccerguy3** [PaperMC/Paper#6141]
### Expected behavior

Links in chat , that were generated this way  were clickable in older versions 

### Observed/Actual behavior

Place a command block , put a button on it . use command /say https://google.com . the link is generated in chat but is not clickable ,but pasting the link into the chat  , which is clickable

 I think this may be related to this issue with chat , If you do use plugins , any link that is generated by a broadcast plugin , is also not clickable . None of the broadcast plugins that I tried from the Spigot resources page generate links that are clickable.

This also happens in single player , Maybe stems from a vanilla bug with the command block

### Steps/models to reproduce

Place a command block ,
 put a button on it . 
use command /say https://google.com
click on chat output

### Plugin list

no plugins 

### Paper version

Paper 1.17.1 b96

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
> This also happens in single player , Maybe stems from a vanilla bug with the command block

This behaviour never existed in vanilla, it's from craftbukkit.

**Comment by Machine-Maker** [comment]
Decided internally, that if you want links in chat, its on plugins to provide that functionality
