### ISSUE TITLE
Enderdragon instantly respawns after being slayed and end towers do not respawn

### ISSUE THREAD

**Issue by GerwinVerkerk** [PaperMC/Paper#6143]
### Expected behavior

The enderdragon to die.

### Observed/Actual behavior

The enderdragon is invincible and does not die. When it's health reached 0, it instantly respawns with full health and towers aren't regenerted.

### Steps/models to reproduce

Go to end and try to kill the ender dragon

### Plugin list

BetterBees, BlowableObsidians, BottledExp, BungeeTabListPlus, BuycraftX, ChestCleaner, Chunkmaster, Citizens, CMILib, CombatLogX, CoreProtect, DeathCoordinates, EasyBackup, Essentials, EssentialsGeoIP, EssentialsMysqlStorage, ExtraContexts, Factions, FarmLimiter, floodgate, HolographicDisplays, HorseTpWithMe, IllegalStack, ImageOnMap, InteractiveBooks, KrakenDonations*, LiteBans, LuckPerms, MaSuiteCore, MaSuiteHomes, MaSuitePortals, MaSuiteTeleports, MaSuiteWarps, Matrix, mcMMO, MineSecure*, Multiverse-Core, MyCommand, MysqlPlayerDataBridge, NBTAPI, PacketListenerApi*, PlaceholderAPI, ProCosmetics, ProtocolLib, RandomTeleport, SirBlobmanCore (SirBlobmanAPI, XSeries), SmoothSleep, spark, TradeSystem, UnderWaterTNT, UpgradeableSpawners, Vault, VentureChat, ViaVersion, VillagerOptimiser, VoidGenerator, VotingPlugin, Wild, WildStacker, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, YT-Twitch_Alerts*

### Paper version

[15:44:11 INFO]: Checking version, please wait...
[15:44:11 INFO]: This server is running Paper version git-Paper-97 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d985976)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by lynxplay** [comment]
Cannot reproduce on `git-Paper-"d985976"` (d985976) without any plugins.
Could you attempt to recreate this on a server without plugins potentially modifying papers behaviour ?
