### ISSUE TITLE
Piglin's ignoring initial opening of chests in Bastion Remnants.

### ISSUE THREAD

**Issue by codebycam** [PaperMC/Paper#6144]
### Expected behavior

In Vanilla (1.17.1) if you open a chest near a Piglin it will instantly agro on you (even whilst wearing gold). I haven't been able to properly check any other triggers like breaking gold blocks, but, i'm _fairly_ sure the same thing happened.

### Observed/Actual behavior

Opening a chest (or breaking a gold block(?)) doesn't agro the Piglins on you, however, if you reopen the chest they will agro, so they're ignoring the first action you do. 

### Steps/models to reproduce

- Create a new world on Paper 97
- `/locate` a Bastion Remnant
- Open a chest in proximity of a Piglin.

### Plugin list

- CoreProtect
- GriefPrevention
- LuckPerms
- HeadDatabase
- Multiverse
- EssentialsX

### Paper version

This server is running Paper version git-Paper-97 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d985976) You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I haven't had a chance to reproduce this without plugins (yet), but am happy to do so if required.

**Comment by Machine-Maker** [comment]
I can't replicate this? Maybe I'm doing smth wrong. Go to a bastion (am in creative) find piglin, place down chest, put on gold armor, go into survival. Piglin doesn't agro, I open the chest and then they agro on me.

**Comment by codebycam** [comment]
Nah, that does sound correct. @kennytv and I both noticed it (more than once) and I was confident that the rules of range & line of sight were met when I tested it (more than once), but perhaps I was wrong/wasn't actually in their line of sight.

**Comment by Machine-Maker** [comment]
I was right up in their face when I did it. I didn’t test it with a generated chest that was part of the bastion tho, that might be a difference

**Comment by Owen1212055** [comment]
I tried going to a pre-generated chest and with a piglin that spawned naturally in the bastion, they all seemed to target me just fine.

```java
public static void angerNearbyPiglins(Player player, boolean blockOpen) {
        if (!player.level.paperConfig.piglinsGuardChests) return; // Paper
        List<Piglin> list = player.level.getEntitiesOfClass(Piglin.class, player.getBoundingBox().inflate(16.0D));

        list.stream().filter(PiglinAi::isIdle).filter((entitypiglin) -> {
            return !blockOpen || BehaviorUtils.canSee(entitypiglin, player);
        }).forEach((entitypiglin) -> {
            if (entitypiglin.level.getGameRules().getBoolean(GameRules.RULE_UNIVERSAL_ANGER)) {
                PiglinAi.setAngerTargetToNearestTargetablePlayerIfFound(entitypiglin, player);
            } else {
                PiglinAi.setAngerTarget(entitypiglin, player);
            }

        });
    }
```

This is the code responsible for angering the nearby piglins. Do note, that the ``BehaviorUtils#canSee`` method uses the ``NEAREST_VISIBLE_LIVING_ENTITIES`` memory. So there is a chance that if people use sensor limiters it could be outdated (although this issue was made before that patch went through, so, this probably isn't relevant). Other than that, I am not sure what else could be affecting this.

Is it possible you can check with your plugins in 1.18?

**Comment by Machine-Maker** [comment]
I can't replicate this either in 1.18.1. Will close as cannot reproduce. If someone can reproduce this, it can be re-opened.
