### ISSUE TITLE
Server crashes after a bunch of teleports

### ISSUE THREAD

**Issue by justEli** [PaperMC/Paper#6146]
### Stack trace

https://pastebin.com/ngKdnkzC

I know it says `DO NOT REPORT THIS TO PAPER`, but this has been crashing my server (about 15 times now) since I updated from Paper 1.17 to Paper 1.17.1 earlier today.

### Plugin list

Mostly my own plugins, teleport-commands like /home have this code:

```java
if (!location.getChunk().isLoaded())
{
    location.getChunk().load();
}

instance.getServer().getScheduler().scheduleSyncDelayedTask(instance, () -> player.teleport(location), 1);
```

However I simply tried `player.teleport(location)` too and that can also cause crashes.

### Paper version

```
> version
[18:12:52 INFO]: Checking version, please wait...
[18:12:52 INFO]: This server is running Paper version git-Paper-97 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d985976)
You are running the latest version
Previous version: git-Paper-90 (MC: 1.17.1)
```

Can confirm it also happens on Paper # 90

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Players can just teleport around as it's not with every teleport, but after about 20-50 teleports the server randomly freezes and crashes.

**Comment by kennytv** [comment]
Spamming the server with sync chunk loads is generally a bad idea, use Paper's async teleportation and loading api.
`Location#getChunk()` already loads the chunk fyi, and the tick schedule isn't necessary either.

Otherwise, generally known, no need for another issue about poor sync load performance.

**Comment by justEli** [comment]
As said, I've tried JUST `player.teleport(location)` as well for hours and that still had half of all crashes.

**Comment by kennytv** [comment]
Use async teleportation api. If you need more assistance, you can join our Discord and ask away in the paper-help channel.

**Comment by justEli** [comment]
Still occurs with `PaperLib.teleportAsync(player, location);`

**Comment by TomYaMee** [comment]
Maybe related to #5980
