### ISSUE TITLE
Buckets not stacking.

### ISSUE THREAD

**Issue by Mikgreg** [PaperMC/Paper#615]
### Description of issue:
Despite bucket stacking being enabled in the paper.yml, buckets are not stacking.

### Plugin list:
I have tested this on a server with no plugins and the problem persists. 

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml: https://hastebin.com/bumopisini.coffeescript
paper.yml: https://hastebin.com/omesivalaq.coffeescript
spigot.yml: https://hastebin.com/labidiqaxe.swift

### Paper build number:
Paper 1059

# Incompatibility (Bug)

### What behaviour is expected:
When clicking a filled bucket onto another, they should stack.
### What behaviour is observed:
When clicking a filled bucket onto another, they do not stack.
### Steps/models to reproduce:
Put two lava/milk/water buckets together in your inventory and try to join them.

**Comment by zachbr** [comment]
That feature doesn't exist in 1.11 and hasn't existed in paper for quite some time (it was removed in our 1.9 update).

There's an issue to add it back but it's purely a "if someone gets bored and implements it in a way that feels entirely natural, we'll add it back"

GH-221 for tracking.
