### ISSUE TITLE
People can crash the server with some shuldkers

### ISSUE THREAD

**Issue by domingodc** [PaperMC/Paper#6150]
### Expected behavior

The server running

### Observed/Actual behavior

The server not running

### Steps/models to reproduce

https://youtu.be/Xu6VmQEPJtE

### Plugin list

I don't remember

### Paper version

I downloaded the last version 1 hour before this, not at home and i can't do it

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
You can limit the number of item entities saved in a chunk in paper.yml. Should prevent all those items from sticking around. But you are going to have to do better than “ The server not running”

**Comment by Chew** [comment]
Definitely a very incomplete issue. Please either make a new one completely filled out or edit this and reply.
