### ISSUE TITLE
Configurable feature seeds

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6152]
### Is your feature request related to a problem?

Players are reversing seed with dungeons/endspikes.

### Describe the solution you'd like.

Paper should have a features seed config option

### Describe alternatives you've considered.

None.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

The patch for this is already made https://github.com/pl3xgaming/Purpur/blob/ver/1.17.1/patches/server/0086-Configurable-feature-seed-settings.patch

**Comment by lynxplay** [comment]
#6121 might do the trick 👌

**Comment by ghost** [comment]
based

**Comment by Proximyst** [comment]
Duplicate of #6086
