### ISSUE TITLE
sign clickEvent run_command excuted where player is standing

### ISSUE THREAD

**Issue by SPACEGG** [PaperMC/Paper#6153]
### Expected behavior

the sign disappears when player clicks the sign that has clickevent {"action":"run_command","value":"setblock ~ ~ ~ air"}

### Observed/Actual behavior

the sign does not disappear except when i stand on that sign

### Steps/models to reproduce

1. /give @s minecraft:birch_sign{BlockEntityTag:{Text2:'{"text":"click me", "clickEvent":{"action":"run_command","value":"setblock ~ ~ ~ air"}}'}} 1
2. place the sign
3. click the sign

### Plugin list

no plugins

### Paper version

paper 1.17.1-99

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

https://github.com/PaperMC/Paper/commit/648f6078d77876217b90dcea644a4e5c68c2e132
https://github.com/PaperMC/Paper/issues/6138

**Comment by Machine-Maker** [comment]
Known issue, guess it’s enough of a different issue to not be a duplicate. Should be fixed in #6139
