### ISSUE TITLE
Assign each dimension their own thread

### ISSUE THREAD

**Issue by cyberc3dr** [PaperMC/Paper#6155]
### Is your feature request related to a problem?

Right now, worlds load in single thread, which can cause problems with weak CPUs

### Describe the solution you'd like.

Each dimension need to assign their own thread. I found a solution as a [fabric mod](https://github.com/WearBlackAllDay/DimensionalThreading)

### Describe alternatives you've considered.

None

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by kennytv** [comment]
If it were that easy without breaking the entirety of the Bukkit ecosystem, we'd have done it already. There's no real point to having that as an issue

**Comment by Proximyst** [comment]
Duplicate of #1001 too
