### ISSUE TITLE
NBT: 2tag(s) items are invisible when dropped 1.17

### ISSUE THREAD

**Issue by WizWazWizard** [PaperMC/Paper#6156]
### Expected behavior

When I throw items like a vote key (from VotingPlugin), item renamer (from AdvancedEnchantmens), or anything with NBT: 2tag(s) is invisible when dropped?

I dont think its a plugin issue, but I dont know what else it could be :/

### Observed/Actual behavior

Items are invisible when dropped, however can be picked up.

### Steps/models to reproduce

Items Examples: https://imgur.com/a/QHGrm7B
Preview GIF: https://gyazo.com/fa395498ee0121056505e1eba93a9554

### Plugin list

https://imgur.com/a/bh7OHLX

### Paper version

paper-1.17-68

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
> paper-1.17-68

>  I am running the latest version of Paper available from papermc.io/downloads.

I don't think these two things are compatible with each other.

If the issue still happens after updating to the actual latest version of paper that's available, can you replicate this without plugins?

**Comment by WizWazWizard** [comment]
> > paper-1.17-68
> 
> > I am running the latest version of Paper available from papermc.io/downloads.
> 
> I don't think these two things are compatible with each other.
> 
> If the issue still happens after updating to the actual latest version of paper that's available, can you replicate this without plugins?

Ive updated to the latest Paper, still an issue
![image](https://user-images.githubusercontent.com/68695803/125354709-09739c00-e35c-11eb-9e03-d9899541f5c5.png)
)

**Comment by WizWazWizard** [comment]
> > paper-1.17-68
> 
> > I am running the latest version of Paper available from papermc.io/downloads.
> 
> I don't think these two things are compatible with each other.
> 
> If the issue still happens after updating to the actual latest version of paper that's available, can you replicate this without plugins?

Updated to latest version of paper, still an issue

**Comment by Machine-Maker** [comment]
Did you try replicating this with no plugins like my previous post said?

> If the issue still happens after updating to the actual latest version of paper that's available, can you replicate this without plugins?

**Comment by WizWazWizard** [comment]
Well this only happens to items with nbt 2 tag(s). Which in this case are
plugin based items. It's fine with normal vanilla items.

**Comment by qixils** [comment]
does this occur without optifine/shaders?

**Comment by e-im** [comment]
I haven't been able to reproduce this on the vanilla client- feel free to leave a comment if you are still having trouble with it on the vanilla client. Also know that you can create items like this without plugins via the `/give` command.
