### ISSUE TITLE
Add more memory/brain API

### ISSUE THREAD

**Issue by tahmid-23** [PaperMC/Paper#6162]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

Currently, it is very difficult to interface with an entity's memory and brain.
With Piglins, AI is managed by a static class and it is difficult to even use NMS to modify their behavior.
Events for changes in activities and adding or replacing memories would be useful.
However, I am not sure how viable this is since an entity's brain does not have reference to its owner entity.

### Describe alternatives you've considered.

changes in memory could be simply done from the entity itself rather than the brain, however this seems unviable to change every call to updating activities/memories with new changes / entities being added.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Owen1212055** [comment]
For memory related things are you looking for these methods?
LivingEntity#getMemory()
LivingEntity#setMemory()

And for brain stuff, are you looking for something similar to the goal api we have now? Where basically you can add your own "brain activities" or memories?

**Comment by tahmid-23** [comment]
> For memory related things are you looking for these methods?
> LivingEntity#getMemory()
> LivingEntity#setMemory()
> 
> And for brain stuff, are you looking for something similar to the goal api we have now? Where basically you can add your own "brain activities" or memories?

no, I want to be able to execute something when an entity changes their activity or loses/gains a memory

**Comment by Owen1212055** [comment]
Ah okay, thanks for the clarification!

**Comment by Machine-Maker** [comment]
Would events for those things replace your PR for #6159? I haven’t looked into exactly where that event you added is fired cause I’m on mobile for a few days, but it sounds like that would be redundant with these features added

**Comment by tahmid-23** [comment]
in some part yes but the event has a reason field which we can't have with just memories

**Comment by Machine-Maker** [comment]
Ah ok yep. 

Also, looks like I should rebase #5004 off of this and extend this event to add the inventory holder. Not sure atm how to reconcile that my event takes a collection of entities as the “targeted” players but we’ll see.
