### ISSUE TITLE
The door and water doesn't update unless I move or I move my mouse.

### ISSUE THREAD

**Issue by HumanMelon** [PaperMC/Paper#6164]
### Expected behavior

The water an doors to update immediately without me moving.

### Observed/Actual behavior

https://user-images.githubusercontent.com/87294986/125235622-0ab4b280-e2e3-11eb-91d9-3dcde6787397.mp4

### Steps/models to reproduce

Setup a 1.17 PaperMC Server, with The 1.18 World Generation preview datapack. (This might do it)

### Plugin list

I'm using plugins plasmo voice mod and skins restorer.

### Paper version

[08:21:26 INFO]: This server is running Paper version git-Paper-79 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: a831634)
You are running the latest version
Previous version: git-Paper-778 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by MiniDigger** [comment]
this really seems like a client issue, can you reproduce this on a vanilla client?

**Comment by Chew** [comment]
1) Unsupported version (1.17 is no longer supported, use 1.17.1)
2) You have more plugins than you've described (it appears CMI or a decent plugin is showing you coords on the action bar)
3) Judging by the hitbox working fine ~5-6 second mark, it does look like your client's on some stuff. 
4) We've quite literally had 0 other reports of this, if someone else somehow can reproduce this on a VANILLA client on a server with no plugins, please tell me how.
