### ISSUE TITLE
Armour Disappearing on Death - Paper 1.17.1

### ISSUE THREAD

**Issue by LGNBandit** [PaperMC/Paper#6165]
### Expected behavior

All of our loot dropping onto the ground on death.

### Observed/Actual behavior

All of the loot dropping except the armor you are wearing, for some reason it disappears.

### Steps/models to reproduce

I'm sorry, I'm not sure what to put here... 
sorry

### Plugin list

Plugins List:
 - Coloured Anvils
 - Core Protect
 - DiscordSRV
 - Essentials
 - FastChunkPregenerator
 - FastLeafDecay 
 - LuckPerms
 - MoreMobHeads
 - SpigotPing
 - StaffPlus
 - TAB

### Paper version

This server is running Paper version git-Paper-"648f607" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 648f607)
You are 16 version(s) behind
Previous version: git-Paper-"a831634" (MC: 1.17)

### Agreements

- [ ] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This problem happens to ALL of the players on the server, and it happens every time no matter what the cause of death is. We have tried adding the Graves data pack, and the problem still occurs. The armor disappears regardless of whether or not it has Curse of Vanishing or not.

**Comment by electronicboy** [comment]
>  I am running the latest version of Paper available from papermc.io/downloads.
> You are 16 version(s) behind

Please fill in the issue tracker properly, I've also not heard of this so would suggest updating and testing without plugins
