### ISSUE TITLE
Server thread dump error, it keeps kicking people out

### ISSUE THREAD

**Issue by ItsNotJosh** [PaperMC/Paper#6167]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
[ERROR] .... --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-416 (MC: 1.16.4) ---

[ERROR] .... The server has not responded for 10 seconds! Creating thread dump

[ERROR] .... ------------------------------

[ERROR] .... Server thread dump (Look for plugins here before reporting to Paper!):

[ERROR] .... ------------------------------

[ERROR] .... Current Thread: Server thread

[ERROR] .... PID: 15 | Suspended: false | Native: false | State: RUNNABLE

[ERROR] .... Stack:

[ERROR] .... java.util.function.Predicate.lambda$and$0(Predicate.java:69)

[ERROR] .... java.util.function.Predicate$$Lambda$1561/1300519073.test(Unknown Source)

[ERROR] .... net.minecraft.server.v1_16_R3.Chunk.a(Chunk.java:894)

[ERROR] .... net.minecraft.server.v1_16_R3.World.getEntities(World.java:1097)

[ERROR] .... net.minecraft.server.v1_16_R3.IEntityAccess.c(IEntityAccess.java:64)

[ERROR] .... net.minecraft.server.v1_16_R3.ICombinedAccess.c(SourceFile:22)

[ERROR] .... net.minecraft.server.v1_16_R3.ICollisionAccess.d(ICollisionAccess.java:57)

[ERROR] .... net.minecraft.server.v1_16_R3.ICollisionAccess.b(ICollisionAccess.java:50)

[ERROR] .... net.minecraft.server.v1_16_R3.ICollisionAccess.getCubes(ICollisionAccess.java:37)

[ERROR] .... net.minecraft.server.v1_16_R3.EntityItem.tick(EntityItem.java:86)

[ERROR] .... net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845)

[ERROR] .... net.minecraft.server.v1_16_R3.WorldServer$$Lambda$4551/1216869111.accept(Unknown Source)

[ERROR] .... net.minecraft.server.v1_16_R3.World.a(World.java:887)

[ERROR] .... net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530)

[ERROR] .... net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1355)

[ERROR] .... net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)

[ERROR] .... net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208)

[ERROR] .... net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996)

[ERROR] .... net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)

[ERROR] .... net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3048/145048008.run(Unknown Source)

[ERROR] .... java.lang.Thread.run(Thread.java:748)

[ERROR] .... ------------------------------

[ERROR] .... --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---

[ERROR] .... ------------------------------

[ERROR] .... --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-416 (MC: 1.16.4) ---

[ERROR] .... The server has not responded for 15 seconds! Creating thread dump

[ERROR] .... ------------------------------

[ERROR] .... Server thread dump (Look for plugins here before reporting to Paper!):

[ERROR] .... ------------------------------

[ERROR] .... Current Thread: Server thread

[ERROR] .... PID: 15 | Suspended: false | Native: false | State: RUNNABLE

[ERROR] .... Stack:

[ERROR] .... java.util.function.Predicate.lambda$and$0(Predicate.java:69)

[ERROR] .... java.util.function.Predicate$$Lambda$1561/1300519073.test(Unknown Source)

[ERROR] .... net.minecraft.server.v1_16_R3.Chunk.a(Chunk.java:894)

[ERROR] .... net.minecraft.server.v1_16_R3.World.getEntities(World.java:1097)

[ERROR] .... net.minecraft.server.v1_16_R3.IEntityAccess.c(IEntityAccess.java:64)

[ERROR] .... net.minecraft.server.v1_16_R3.ICombinedAccess.c(SourceFile:22)

[ERROR] .... net.minecraft.server.v1_16_R3.ICollisionAccess.d(ICollisionAccess.java:57)

[ERROR] .... net.minecraft.server.v1_16_R3.ICollisionAccess.b(ICollisionAccess.java:50)

[ERROR] .... net.minecraft.server.v1_16_R3.ICollisionAccess.getCubes(ICollisionAccess.java:37)

[ERROR] .... net.minecraft.server.v1_16_R3.EntityItem.tick(EntityItem.java:86)

[ERROR] .... net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845)

[ERROR] .... net.minecraft.server.v1_16_R3.WorldServer$$Lambda$4551/1216869111.accept(Unknown Source)

[ERROR] .... net.minecraft.server.v1_16_R3.World.a(World.java:887)

[ERROR] .... net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530)

[ERROR] .... net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1355)

[ERROR] .... net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)

[ERROR] .... net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208)

[ERROR] .... net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996)

[ERROR] .... net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)

[ERROR] .... net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3048/145048008.run(Unknown Source)

[ERROR] .... java.lang.Thread.run(Thread.java:748)

### Plugin list

DiscordSRV-Build-1.23.0
EasySetSpawn
UltimateHomes-2.2\
worldedit-bukkit-7.0.1
worldguard-bukkit-7.0.1

### Paper version

[INFO] ....>.... This server is running Paper version git-Paper-416 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

[INFO] .... Checking version, please wait...

[INFO] .... You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
You failed to provide the full log, nor is 1.16.4 supported

**Comment by ItsNotJosh** [comment]
can you explain? i didn't understand much about that.

**Comment by electronicboy** [comment]
You're using an unsupported version of the server, you've also not provided enough of the log file to see what is going on, even if it was an issue

**Comment by ItsNotJosh** [comment]
so what should i do?

**Comment by electronicboy** [comment]
update to a supported version, if you still have issues, provide the full logs, or at least the entire watchdog set of dumps (and a bit before that)

**Comment by ItsNotJosh** [comment]
ok

**Comment by ItsNotJosh** [comment]
so um i already update it, and its still happening.

**Comment by mbax** [comment]
> so um i already update it, and its still happening.

Then do the second part of the instructions given and provide full logs.

**Comment by ItsNotJosh** [comment]
my watchdog is disabled, so i dont have any watchdong logs, so ill provide the full log.

**Comment by ItsNotJosh** [comment]
so a new error just showed up when i restart the server, this is the full error log:
[INFO] .... Preparing level "world"

[INFO] .... Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface

[INFO] .... Preparing start region for dimension minecraft:overworld

[WARNING] .... java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2586 > 2584

[WARNING] .... at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:67)

[WARNING] .... at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:114)

[WARNING] .... at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39)

[WARNING] .... at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105)

[WARNING] .... at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38)

[WARNING] .... java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2586 > 2584

[WARNING] .... at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:67)

[WARNING] .... at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:114)

[WARNING] .... at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:39)

[WARNING] .... at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105)

[WARNING] .... at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38)

[INFO] .... Loaded 0 spawn chunks for world world

[INFO] .... Time elapsed: 429 ms

[INFO] .... Preparing start region for dimension minecraft:the_nether

[INFO] .... Loaded 0 spawn chunks for world world_nether

[INFO] .... Time elapsed: 186 ms

[INFO] .... Preparing start region for dimension minecraft:the_end

[INFO] .... Loaded 0 spawn chunks for world world_the_end

[INFO] .... Time elapsed: 75 ms

[INFO] .... Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)

[WARNING] .... java.lang.Exception: Error occurred detecting class name

[WARNING] .... at co.aikar.timings.MinecraftTimings.lambda$getPluginTaskTimings$0(MinecraftTimings.java:85)

[WARNING] .... at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324)

[WARNING] .... at co.aikar.timings.MinecraftTimings.getPluginTaskTimings(MinecraftTimings.java:75)

[WARNING] .... at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.<init>(CraftTask.java:77)

[WARNING] .... at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.<init>(CraftTask.java:42)

[WARNING] .... at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler$5.<init>(CraftScheduler.java:333)

[WARNING] .... at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.cancelTasks(CraftScheduler.java:313)

[WARNING] .... at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:267)

[WARNING] .... at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)

[WARNING] .... at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)

[WARNING] .... at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)

[WARNING] .... at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384)

[WARNING] .... at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)

[WARNING] .... at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)

[WARNING] .... at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)

[WARNING] .... at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464)

[WARNING] .... at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)

[WARNING] .... at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935)

[WARNING] .... at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)

[WARNING] .... at java.lang.Thread.run(Thread.java:748)

[ERROR] .... Main thread terminated by WatchDog due to hard crash

java.lang.ThreadDeath: null

at java.lang.Thread.stop(Thread.java:853) [?:1.8.0_212]

at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:753) ~[patched_1.16.4.jar:git-Paper-416]

at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:704) ~[patched_1.16.4.jar:git-Paper-416]

at net.minecraft.server.v1_16_R3.MinecraftServer.close(MinecraftServer.java:727) ~[patched_1.16.4.jar:git-Paper-416]

at org.bukkit.craftbukkit.v1_16_R3.util.ServerShutdownThread.run(ServerShutdownThread.java:28) ~[patched_1.16.4.jar:git-Paper-416]

[INFO] .... Stopping server

[INFO] .... Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit

[INFO] .... Saving players

[INFO] .... Saving worlds

[INFO] .... Saving chunks for level 'ServerLevel[world]'/minecraft:overworld

**Comment by ItsNotJosh** [comment]
am i needed to reinstall my paper server?
