### ISSUE TITLE
Entities are added to the world before the chunk is fully read and loaded

### ISSUE THREAD

**Issue by Eagllus** [PaperMC/Paper#6168]
### Expected behavior

Please note that from https://github.com/PaperMC/Paper/issues/6094, I use the TNT duplicator as an example to make it reproducable.

When a chunk has to be loaded entities are loaded before the chunk is fully read and loaded.

### Observed/Actual behavior

The entities are loaded before the chunk is and since I use the TNT duplicator as an example.
The TNT gets triggered while it should not be updated.

### Steps/models to reproduce

Build a TNT duplicator (I know unsupported but it's the easiest thing to build) don't turn it on.

Teleport away until it is unloaded, move back into range of the TNT duplicator and everything is fine.

Teleport away until it's unloaded and teleport back. TNT will explode.

### Plugin list

No plugins

### Paper version

```
This server is running Paper version git-Paper-100 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 70ea1b2)
You are running the latest version
Previous version: git-Paper-99 (MC: 1.17.1)
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
Can you provide a real example of this being the case? E.g. plugin with custom NMS-extending entity?

**Comment by Eagllus** [comment]
Not sure what you mean with real example or plugin with custom NMS-extending entity.

I don't use any plugins, I only run PaperMC and am able to reproduce it using a TNT duplicator.
Since the behavior of it should be the same as any other entity it shouldn't matter much right?

**Comment by Proximyst** [comment]
That still doesn't prove this is the case at all; it may very well be a quirk with only TNT. Please provide some kind of evidence this is the case, for example through custom plugins with entities which log its ticks before chunk loads.

**Comment by babofish** [comment]
Not a server admin just a moderator playing a paper server. we have a few plugins but none (that i know of) that would really interact with the way chunks are loaded. 
We are seeing similar behavior with TNT dupers and forceloading the chunks prevents the issue. 

Before I ran into the tnt issue I also saw a case where a observer looking at string with a villager standing it would seeming fire for no reason and trigger a piston to move a block. It seemed to be happening when the chunk/chunks the villagers were in would load. 
I thought the case would be that the entities were being loaded After the redstone was fully loaded. Causing the string to update and then the observer to detect it.
That might line up with how the TNT duper fires when loaded in that. all the other blocks are loaded in, then the TNT is loaded and sees its next to a powered rail and ignites?

Figured out how to get the list of plugins on our server.
![image](https://user-images.githubusercontent.com/33108844/125497289-0c1ce104-9f7f-48f9-ae57-87846fe83c5c.png)

CoreProtect, WorldEdit and WorldGuard have not been used to do any modifications to blocks anywhere in the world yet. They are there as preventative if we happen to get any bad actors on the server.

**Comment by totorewa** [comment]
Looking into this myself as I've also experienced this, I believe the opposite of what is claimed in this issue is actually happening. Activated detector rail's `tick()` schedules another `tick()` call 20 ticks later, essentially being ticked every 20 ticks. The chunk loads and before the minecart is added to the world, the detector rail is ticked, does not detect the minecart, and proceeds to deactivate. The minecart is then added which activates the detector rail again, block updating the TNT.

This is shown in these logs I outputted:
```
Totorewa joined the game
Totorewa[/127.0.0.1:62925] logged in with entity id 231 at ([world]1065.6410386329703, 96.07213908022685, 964.7864462226881)
[Tick: 18593] PaperTickList: Detector rail at x1073, y92, z967 ticked
[Tick: 18593] Detector rail at x1073, y92, z967 is powered however does not have a minecart
[Tick: 18593] Minecart added at x1073, y92, z967
[Tick: 18594] TNT primed at x1073, y90, z967
[Tick: 18594] Detector rail at x1073, y92, z967 is not powered however has a minecart
[Tick: 18614] PaperTickList: Detector rail at x1073, y92, z967 ticked
[Tick: 18614] Detector at x1073, y92, z967 is powered and has a minecart
```

As for why this does not occur in vanilla, `ServerTickList` has this if statement in the `tick()` method:
```java
if (this.level.isPositionTickingWithEntitiesLoaded(nextticklistentry.pos)) {
```
which makes it so the detector rail isn't ticked until the entities in that chunk are loaded, and I could not find any equivalent used in `PaperTickList`.

When setting the config option `settings.use-optimized-ticklist` to `false` (makes Paper use `ServerTickList` instead of `PaperTickList`), this issue no longer occurs. Here are logs I made showing that:
```
Totorewa joined the game
Totorewa[/127.0.0.1:52409] logged in with entity id 92 at ([world]1064.8956419714052, 96.07213908022685, 966.3879867380116)
[Tick: 18105] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
[Tick: 18106] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
[Tick: 18107] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
[Tick: 18108] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
[Tick: 18108] Minecart added at x1073, y92, z967
[Tick: 18109] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
[Tick: 18110] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
[Tick: 18111] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
[Tick: 18112] ServerTickList: Detector rail at x1073, y92, z967 ticked
[Tick: 18112] Detector at x1073, y92, z967 is powered and has a minecart
[Tick: 18132] ServerTickList: Detector rail at x1073, y92, z967 ticked
[Tick: 18132] Detector at x1073, y92, z967 is powered and has a minecart
```

As shown, the detector rail doesn't get ticked until all the entities (+ minecart) have been loaded.

Hopefully this is helpful input.

**Comment by Nervaq** [comment]
> Looking into this myself as I've also experienced this, I believe the opposite of what is claimed in this issue is actually happening. Activated detector rail's `tick()` schedules another `tick()` call 20 ticks later, essentially being ticked every 20 ticks. The chunk loads and before the minecart is added to the world, the detector rail is ticked, does not detect the minecart, and proceeds to deactivate. The minecart is then added which activates the detector rail again, block updating the TNT.
> 
> This is shown in these logs I outputted:
> 
> ```
> Totorewa joined the game
> Totorewa[/127.0.0.1:62925] logged in with entity id 231 at ([world]1065.6410386329703, 96.07213908022685, 964.7864462226881)
> [Tick: 18593] PaperTickList: Detector rail at x1073, y92, z967 ticked
> [Tick: 18593] Detector rail at x1073, y92, z967 is powered however does not have a minecart
> [Tick: 18593] Minecart added at x1073, y92, z967
> [Tick: 18594] TNT primed at x1073, y90, z967
> [Tick: 18594] Detector rail at x1073, y92, z967 is not powered however has a minecart
> [Tick: 18614] PaperTickList: Detector rail at x1073, y92, z967 ticked
> [Tick: 18614] Detector at x1073, y92, z967 is powered and has a minecart
> ```
> 
> As for why this does not occur in vanilla, `ServerTickList` has this if statement in the `tick()` method:
> 
> ```java
> if (this.level.isPositionTickingWithEntitiesLoaded(nextticklistentry.pos)) {
> ```
> 
> which makes it so the detector rail isn't ticked until the entities in that chunk are loaded, and I could not find any equivalent used in `PaperTickList`.
> 
> When setting the config option `settings.use-optimized-ticklist` to `false` (makes Paper use `ServerTickList` instead of `PaperTickList`), this issue no longer occurs. Here are logs I made showing that:
> 
> ```
> Totorewa joined the game
> Totorewa[/127.0.0.1:52409] logged in with entity id 92 at ([world]1064.8956419714052, 96.07213908022685, 966.3879867380116)
> [Tick: 18105] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
> [Tick: 18106] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
> [Tick: 18107] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
> [Tick: 18108] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
> [Tick: 18108] Minecart added at x1073, y92, z967
> [Tick: 18109] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
> [Tick: 18110] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
> [Tick: 18111] ServerTickList: Detector rail at x1073, y92, z967 NOT ticked - entities not loaded
> [Tick: 18112] ServerTickList: Detector rail at x1073, y92, z967 ticked
> [Tick: 18112] Detector at x1073, y92, z967 is powered and has a minecart
> [Tick: 18132] ServerTickList: Detector rail at x1073, y92, z967 ticked
> [Tick: 18132] Detector at x1073, y92, z967 is powered and has a minecart
> ```
> 
> As shown, the detector rail doesn't get ticked until all the entities (+ minecart) have been loaded.
> 
> Hopefully this is helpful input.

We don't have this config setting available in paper.yml with minecraft 1.17.1. Where did you find that config then?

**Comment by totorewa** [comment]
> We don't have this config setting available in paper.yml with minecraft 1.17.1. Where did you find that config then?

I found it by reading the code. Here is the patch file with that config setting https://github.com/PaperMC/Paper/blob/master/patches/server/0388-Optimise-TickListServer-by-rewriting-it.patch#L54

**Comment by Eagllus** [comment]
So if I add 

```
settings: # already present of course
  use-optimized-ticklist: false
```

 to my config this issue is resolved?

**Comment by L-Restart-Life** [comment]
> So if I add
> 
> ```
> settings: # already present of course
>   use-optimized-ticklist: false
> ```
> 
> to my config this issue is resolved?

yup! tried it myself, zero issues

**Comment by Eagllus** [comment]
Yeah I tested it myself and can also confirm that this is a workaround for this issue

**Comment by Marcelo-Petrucelli** [comment]
A pull request #6191 has been done, but since it intensified the problem they reverted it at #6216. I'm also not using the optimized ticklist, but I think they kindda know what is going on with the PaperTickList.

**Comment by jkoenigschulte** [comment]
So to summarize, i just have to paste this:

settings: # already present of course
  use-optimized-ticklist: false

into the paper.yml file at the botton and my tnt-dupers will no longer explode by themselve?

**Comment by Marcelo-Petrucelli** [comment]
If this is still an issue is questionable. But yeah, this trick should work.
