### ISSUE TITLE
Papermc #100 for MC 1.17.1 not opening at all.

### ISSUE THREAD

**Issue by jonathan-x01** [PaperMC/Paper#6171]
### Expected behavior

Opening up the application and starting the server like normal.

### Observed/Actual behavior

Clicking the paper-1.17.1-100.jar and under a millisecond the loading cursor icon replaces the cursor and in a second returns back, and nothing happens. No logs are logged or crash-reports are logged and jar files are not showing up in task manager. Nothing happens except the cursor loading, which that is probably from windows trying to open it.

Wish I could see even logs of why Windows was unable to open it.

### Steps/models to reproduce

Opening the paper-1.17.1-100.jar

### Plugin list

Dynmap-3.1-beta7-spigot
Multiverse-Core-4.2.2
PlotSquared-Bukkit-4.494
VoidGenerator-1.7.0
worldedit-bukkit-7.2.2-dist

### Paper version

Application not opening up, so cannot copy logs as it does not create any logs or crash-reports.
But the file name should include everything. I did not change the name. The name is paper-1.17.1-100.

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Papermc for MC 1.16.5 works perfectly, but Papermc for MC 1.17.1 does not open up.

**Comment by electronicboy** [comment]
Please use the discord for support, use a bat file to start the server, add PAUSE onto the last line of the bat to keep the window open, may display the actual error

**Comment by jonathan-x01** [comment]
> Please use the discord for support, use a bat file to start the server, add PAUSE onto the last line of the bat to keep the window open, may display the actual error

Why ask for support on Discord? Isn't that a bit biased?

**Comment by e-im** [comment]
You may also ask on irc (#paper-help on irc.esper.net) or [our forums](https://papermc.io), however the issue tracker isn't the place for support.
