### ISSUE TITLE
Cursor moving to middle when clicking opening new hopper

### ISSUE THREAD

**Issue by Thibaut040** [PaperMC/Paper#6172]
### Expected behavior

The cursor should stay where it was.

### Observed/Actual behavior

When clicking it moves to the middle.

### Steps/models to reproduce

1. Create a simple plugin with a InventoryClickEvent.
2. Please a block of obsidian (or any item) in your inventory and place a hopper on the ground.
3. ```
	@EventHandler
	public void onInventoryClick(InventoryClickEvent e) {
		Player p = (Player) e.getWhoClicked();
		if (e.getCurrentItem().getType() == Material.OBSIDIAN) {
			e.setCancelled(true);
			p.openInventory(Bukkit.createInventory(null, InventoryType.HOPPER));
	}

4. Reload or restart your server.
5. Open the hopper and click on the obsidian. You'll see that your cursor moves to the middle of your screen.
*Note: Opening a chest creates the same problem. When clicking in your survival inventory, this problem doesn't occur.

### Plugin list

Self-made one in which the problem occurs;
[worldedit](https://dev.bukkit.org/projects/worldedit).

### Paper version

This server is running Paper version git-Paper-100 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 70ea1b2)

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

No errors in the console.
EDIT: I used the same code in another plugin, in which it works with switching between 2 custom chests (customizable rows).
I am also using vanilla Minecraft. (latest release: 1.17.1)

**Comment by Machine-Maker** [comment]
Are you using the vanilla client? The server doesn’t have control over the cursor location.

**Comment by ExcessiveAmountsOfZombies** [comment]
You're opening a new inventory when you click the obsidian, so internally that closes the inventory, putting your cursor where the crosshair (the middle of the screen) is and then opens a new one

**Comment by Chew** [comment]
Yeah, I've had this before, it's all dependant on how you manage GUIs. I don't know the exact process to avoid this (it's possible, though).

**Comment by HexedHero** [comment]
Related: https://hub.spigotmc.org/jira/browse/SPIGOT-6552

**Comment by Doc94** [comment]
This issue was fixed in CraftBukkit.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/f7f8dce41fcf4f0917c9cb51390797cd36e471d7
