### ISSUE TITLE
[Server thread/ERROR]: Encountered an unexpected exception

### ISSUE THREAD

**Issue by LynxError** [PaperMC/Paper#6173]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://pastebin.pl/view/7d9670c9

### Plugin list

Plugins: { HackedCore v2.71.4* io.th0rgal.hackedcore.Core [Th0rgal], PlaceholderAPI v2.10.9 me.clip.placeholderapi.PlaceholderAPIPlugin [HelpChat], UltimateAutoRestart vBuild 43a dev.norska.uar.UltimateAutoRestart [Norska], AutoSync vBuild 23 com.vagdedes.autosync.Register [Evangelos Dedes @Vagdedes], DisableRecipe v1.1.0 com.mattisadev.disablerecipe.DisableRecipe [Matthew W Wiggins], RHLeafDecay v1.1.2-1.16_R6 eu.raidersheaven.leafdecay.Main.Main [X0R3], NoteBlockAPI v1.6.1-SNAPSHOT com.xxmicloxx.NoteBlockAPI.NoteBlockAPI [xxmicloxx, michidk, koca2000, Luck], LuckPerms v5.3.47 me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin [Luck], OpenInv v4.1.5 com.lishid.openinv.OpenInv [lishid, Jikoo, ShadowRanger], HackedServer v2.80.0* io.th0rgal.hackedserver.Core [Th0rgal], JetsAntiAFKPro v3.4.4 me.jet315.antiafkpro.JetsAntiAFKPro [Jet315], WorldBorder v1.8.7* com.wimbli.WorldBorder.WorldBorder [Brettflan], Votifier v2.7.1 com.vexsoftware.votifier.NuVotifierBukkit [Ichbinjoe, blakeman8192, Kramer, tuxed], SilkSpawners v7.1.0 de.dustplanet.silkspawners.SilkSpawners [xGhOsTkiLLeRx, mushroomhostage], ProtocolLib v4.7.0 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], AnvilColor v1.7.3 fr.fsama.ac.Main [FeitanSama], LibsDisguises v10.0.25 me.libraryaddict.disguise.LibsDisguises [libraryaddict, Byteflux, Navid K.], Giveall v1.1.0* DanPlugins.giveall.Giveall [], AdvancedOreGen v1.6.44-SNAPSHOT xyz.spaceio.AdvancedOreGen.Main [Linus122], ServerRestorer v1.0.37 me.zombie_striker.sr.Main [Zombie_Striker], Vault v1.7.3-b131 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], SystemInfo v1.3.5 studio.thevipershow.systeminfo.SystemInfo [TheViperShow], CrazyCrates v1.10.1-RELEASE me.badbones69.crazycrates.Main [BadBones69], ChatColor2 v1.10.4 com.sulphate.chatcolor2.main.ChatColor [Sulphate], Chunky v1.2.86 org.popcraft.chunky.ChunkyBukkit [pop4959], Shop v1.8.2.6 com.snowgears.shop.Shop [SnowGears], PlayerVaults v4.2.0 com.drtshock.playervaults.PlayerVaults [drtshock, kashike, CmdrKittens], WorldEdit v7.2.4+5723-e3bfc64 com.sk89q.worldedit.bukkit.WorldEditPlugin [], Essentials v2.18.2.0 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, md678685], HeadDatabase v4.13.8 me.arcaniax.hdb.Main [Arcaniax], AutoMessager v3.1 hu.montlikadani.automessager.bukkit.AutoMessager [montlikadani], Citizens v2.0.28-SNAPSHOT (build 2328) net.citizensnpcs.Citizens [fullwall], VotingPlugin v6.4 com.bencodez.votingplugin.VotingPluginMain [BenCodez], AsyncWorldEdit v3.9.1 org.primesoft.asyncworldedit.AsyncWorldEditBukkit [SBPrime], DeluxeMenus v1.13.3-Release com.extendedclip.deluxemenus.DeluxeMenus [extended_clip, Glare], EssentialsChat v2.18.2.0 com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], GriefPrevention v16.17.1-2b69191 me.ryanhamshire.GriefPrevention.GriefPrevention [], Spartan vBuild 417.1 me.vagdedes.spartan.Register [Evangelos Dedes @Vagdedes], AuctionHouse v2.2 com.spawnchunk.auctionhouse.AuctionHouse [klugemonkey], TradePlus v3.81 com.trophonix.tradeplus.TradePlus [Trophonix], SuperLuckyBlock v4.3.0 org.sickskillz.superluckyblock.SuperLuckyBlock [SickSkillz], CommandNPC v1.9.1* me.messageofdeath.commandnpc.CommandNPC [messageofdeath], EssentialsSpawn v2.18.2.0 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], CoreProtect v20.0-rc1 net.coreprotect.CoreProtect [Intelli], Wild v2.29-7da6164 net.poweredbyhate.wildtp.WildTP [LaxWasHere, RoboMWM], PremiumVanish v2.7.0 de.myzelyam.premiumvanish.bukkit.PremiumVanish [MyzelYam], ACNotify vBuild 7* io.github.hakangulgen.acnotify.bukkit.ACNotifyPlugin [HKNGLGN], Plan v5.4 build 1366 com.djrapitops.plan.Plan [AuroraLS3], WildStacker v3.6.0-DEVb142 com.bgsoftware.wildstacker.WildStackerPlugin [Ome_R], JetsMinions v7.2.0 me.jet315.minions.Core [Jet315], SmoothTimber v1.17.1 com.syntaxphoenix.spigot.smoothtimber.SmoothTimber [SyntaxPhoenix IT-Solutions], BungeeTabListPlus v3.4.3 codecrafter47.bungeetablistplus.BukkitPlugin [CodeCrafter47],}

### Actions to reproduce (if known)

server crashes

### Paper version

co v20.0-rc1 on 1.16.5 paper 778, but also does this on 781

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

CoreProtect — Today at 8:55 PM
Probably from an item rollback, but yeah, you'll need to report it to Paper

CoreProtect told me to report this to paper

**Comment by electronicboy** [comment]
This is an upstream "bug", an item was basically modified in an unexpected manner, or stance on this is somewhat iffy as it would be nice to prevent the server from crashing due to stupid issues like these but the surface coverage is somewhat large
