### ISSUE TITLE
Enderpearl

### ISSUE THREAD

**Issue by Eukalp** [PaperMC/Paper#618]
You can teleport witch enderpearl to prohibited area

**Comment by RhvsW** [comment]
k

**Comment by mikroskeem** [comment]
Define __prohibited__ area.

**Comment by zachbr** [comment]
I made a venn diagram to help better track this.

![venn diagram](http://i.imgur.com/8DRVg0P.png)

**Comment by prplz** [comment]
Hey at least he edited it to english
