### ISSUE TITLE
Right-clicking Stonecutter throws 'Index 1 out of bounds for length 1' error in client console

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#6180]
### Expected behavior

No errors in client console.

### Observed/Actual behavior

When you right-click a Stonecutter to use it, throws 'Error executing task on Client'. This does not happen in Single player or vanilla server.

https://pastebin.com/6780TEMK

### Steps/models to reproduce

1. Start a fresh new Paper server
2. Place a Stonecutter
3. Right-click it
4. You can see an error in client console

### Plugin list

None, fresh Paper's setup.

### Paper version

[13:01:22 INFO]: This server is running Paper version git-Paper-103 (MC: 1.17.1)
 (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 990f7da)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Using vanilla client/launcher with no resource packs nor datapacks.

**Comment by Doc94** [comment]
Only happen in Paper, in Vanilla or Spigot this issue not happen. the GUI show correctly, the error is only for client console.
