### ISSUE TITLE
Limited view distance

### ISSUE THREAD

**Issue by NovaPixell** [PaperMC/Paper#6187]
### Expected behavior

Moving around the world, all loaded chunks are immediately downloaded, despite having 16 of render distances on client side

### Observed/Actual behavior

This problem did not exist in 1.16. Where it moves, on the client side it always loads all the chunks it moves into.
In 1.17.1 all chunks are unloaded immediately

Config:
view-distance= 3
no-tick= 5

(also I resetted all server configs)

### Steps/models to reproduce

In 1.17.1:

https://user-images.githubusercontent.com/55632135/125789191-fc153b19-e589-470b-ba36-2a3fae9f39b1.mp4

In 1.16.5

https://user-images.githubusercontent.com/55632135/125790217-477ae8b4-e6e6-469b-a5c8-4ad427d1a804.mp4

### Plugin list

Nothing

### Paper version

git-Paper-104 (MC: 1.17.1)

git-Paper-782 (MC: 1.16.5) 

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by NovaPixell** [comment]
It could be a minecraft vanilla change, which happened in a snapshot:

21w10a: Distance fog is now spherical, and no longer changes based on the view angle.


I would like to ask if it is possible to implement a patch that increases the view of the chunks (as the 1.16), because many servers need a high view of the chunks

**Comment by electronicboy** [comment]
increases the view of the chunks?

I think mojang made some changes to make the game more active towards unloading stuff so I've seen from some comments, I fail to see what the issue is here? Also, are you using optifine?

**Comment by NovaPixell** [comment]
> increases the view of the chunks?
> 
> I think mojang made some changes to make the game more active towards unloading stuff so I've seen from some comments, I fail to see what the issue is here? Also, are you using optifine?

I'm using Optifine. But look, on the first video (1.17) chunks are immediatly unloaded. On 1.16, the second video, on client side all chunks remain loaded.

If I increase the no-tick view distance, the problem still occurs. If I go outside the chunk range of the no-tick, all these chunks are immediately unloaded

**Comment by NovaPixell** [comment]
For example, on a survival server where builders have to see constructions from afar, they can't on 1.17. even if I increase the no-tick value

**Comment by electronicboy** [comment]
Yes, which is normal, chunks unload if you go out of the range of them, I don't see what the issue is there?

optifine also caches chunks so this comparision directly is somewhat moot

**Comment by NovaPixell** [comment]
> Yes, which is normal, chunks unload if you go out of the range of them, I don't see what the issue is there?
> 
> optifine also caches chunks so this comparision directly is somewhat moot

Look the 1.16 video. Same configs values. The chunks outside the no-tick range, are still loaded.

**Comment by electronicboy** [comment]
> For example, on a survival server where builders have to see constructions from afar, they can't on 1.17. even if I increase the no-tick value

Which is literally how optifines offline cache works? if you go outside of the range of a chunk on the server but it's still in your view distance, it will still be rendered

**Comment by NovaPixell** [comment]
Now I have beed tryied without Optifine and the issue still remains

**Comment by electronicboy** [comment]
> 13:58] NovaPixel: perfect, on 1.16 without optifine is the same as 1.17

Not a paper issue, chunks unload when you go out of range of them, Optifine adds a local cache which will keep chunks rendered even after you go outside of the view distance of them, if OF doesn't do this in 1.17, that's an OF issue
