### ISSUE TITLE
Hex color support for the messages in paper.yml

### ISSUE THREAD

**Issue by pianwan** [PaperMC/Paper#6189]
### Is your feature request related to a problem?

The hex color for messages in paper.yml does not work.

### Describe the solution you'd like.

Hex color is already well done in spigot.yml, but not in paper.yml. It's a pity. 
The color code like §#ffffff should work.

### Describe alternatives you've considered.

Parse hex color for the messages in paper.yml.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by electronicboy** [comment]
Spigot doesn't use #, it uses x, with an & before each of those, what messages do not support this as it looks like a chunk of them that I looked at already do?

**Comment by pianwan** [comment]
> Spigot doesn't use #, it uses x, with an & before each of those, what messages do not support this as it looks like a chunk of them that I looked at already do?

Do you mean &xffffff instead of §#ffffff?
Actually, I tried both, §#ffffff works but &xffffff doesn't in spigot.yml.
Both of them do not work in paper.yml.

**Comment by kezz** [comment]
It's `&x&r&r&g&g&b&b` iirc

**Comment by pianwan** [comment]
> It's `&x&r&r&g&g&b&b` iirc

It works, thank you!
