### ISSUE TITLE
New patch creates a reach issue

### ISSUE THREAD

**Issue by ZenIsBestWolf** [PaperMC/Paper#6194]
### Expected behavior

Breaking blocks ~4 away while looking up should break.

### Observed/Actual behavior

Blocks dont break!

### Steps/models to reproduce

Try to break a block high up

### Plugin list

none

### Paper version

This server is running Paper version git-Paper-106 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b41b5b)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Important: I have tested this with Version 105, and the bug is absolutely introduced in #6193, this is a game breaking bug and should be rolled back immediately.

**Comment by Machine-Maker** [comment]
Yep, known issue. Will be fixed in a few minutes.
