### ISSUE TITLE
Block Break Range Restricted Facing Up

### ISSUE THREAD

**Issue by xxbones21xx** [PaperMC/Paper#6196]
### Expected behavior

No block break range restriction.

### Observed/Actual behavior

Only able to break a couple of blocks while facing up.

### Steps/models to reproduce

Loaded clean paper-1.17.1-105.jar server and problem is not present. 

### Plugin list

No plugins on either server tested. Fresh server setup for both 105 & 106 test.

### Paper version

This server is running Paper version git-Paper-106 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b41b5b5)
You are 1 version(s) behind

Latest available at time of testing.

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

First time submitting an issue. Hope this was helpful.

**Comment by Machine-Maker** [comment]
> You are 1 version(s) behind

**Comment by xxbones21xx** [comment]
I pulled the version directly from the website moments before loading into the server and copying that information.... ?

**Comment by electronicboy** [comment]
force refresh the downloads page, you're outdated (caching, woo)

**Comment by xxbones21xx** [comment]
Facepalm...  I didn't realize it was caching bad... I see 107 is live. Thanks!

**Comment by Proximyst** [comment]
Entirely okay! Give us a heads-up if it's still broken. ;)
