### ISSUE TITLE
log4j Error Unable to invoke facotry method in class

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6198]
### Stack trace

```
https://paste.gg/p/anonymous/5a2e3ccd943c4f1f81db9907f2fa4c8e
```

### Plugin list

None

### Actions to reproduce (if known)

Boot server with specs:
`Java`
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode, sharing)

`OS`
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute

`Using`
launch.sh with 777 rights and 777 rights on paper-1.16.5-782.jar
launch.sh content = **screen -S SMPServer java -Xmx1G -jar paper-1.16.5-782.jar**

`Files in root dir`
banned-ips.json      bukkit.yml  commands.yml  help.yml   logs      paper-1.16.5-782.jar  permissions.yml  server.properties  usercache.json        whitelist.json  world_nether
banned-players.json  cache       eula.txt      launch.sh  ops.json  paper.yml             plugins          spigot.yml         version_history.json  world           world_the_end

### Paper version

This server is running Paper version git-Paper-782 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
full console output? last I knew that was generally caused by another exception, generally due to file perms, setting everything as 777 is not a good workaround for a borked up perms setup if that's why your intent is...

**Comment by Chew** [comment]
Account owner no longer exists. As no information has been provided, I'm going to have to close this issue. Thanks anyway, kind stranger.
