### ISSUE TITLE
Invalid block break distance

### ISSUE THREAD

**Issue by NightLife-SG** [PaperMC/Paper#6202]
### Expected behavior

My player get error today after updating to lastest paper build,they just disconnect when breaking block

[Fri, 16. Jul 2021 15:23:01 UTC WARN] DazMaticx tried to break a block 1605.6143978325015 square blocks away from their position
[Fri, 16. Jul 2021 15:23:01 UTC INFO] DazMaticx lost connection: Invalid block break distance

### Observed/Actual behavior

disconnect while breaking block too fast

### Steps/models to reproduce

Breaking block with enchantment haste 3 

### Plugin list

Plugins (53): AdvancedEnchantments, AdvancedMobArena, AdvancedRegionMarket, BetterRTP, ChestSort, Chunky, ChunkyBorder, Citizens, CMI, CMIEInjector*, CMILib, CoreProtect, CraftingStore, DeluxeMenus, Denizen, DiscordSRV, FarmLimiter, GoldenCrates, HolographicDisplays, Insights, Jobs, Lands, LibsDisguises, LuckPerms, LuckyPouches, LumberJack, mcMMO, MiniMOTD, ModelEngine, MorphRedeem, Multiverse-Core, MythicMobs, NexEngine, PL-Hide, PlaceholderAPI, PlayerParticles, ProtocolLib, PyroFishingPro, Quests, QuickShop, ShopGUIPlus, SilkSpawners, TAB, Vault, VoidGenerator, VoteParty, Votifier, WanderingTrades, WorldEdit, WorldGuard, WorldGuardExtraFlags, zAuctionHouse-Discord, zAuctionHouseV3

### Paper version

This server is running Paper version git-Paper-107 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5a9c14b)
You are running the latest version
Previous version: git-Paper-106 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
Update. This has been fixed.

**Comment by e-im** [comment]
Or not, my bad. I see you are on 107 and this should have been fixed there.

**Comment by e-im** [comment]
I have confirmed that this check is now working correctly. This is the intended behaviour, your player is likely using a modified client.

**Comment by NightLife-SG** [comment]
![image](https://user-images.githubusercontent.com/84533050/125982657-70d65661-041b-43da-a1d8-d6abcb514436.png)

he using the original minecraft launcher and no mod except optifine

**Comment by electronicboy** [comment]
No idea if thi sis 100% legit specific, but, there is an issue here
This sounds to be an order of operations thing in some aspects, it's comparing to the players location but the player might be teleported in an unexpected manner? etc

**Comment by TNTUP** [comment]
Can confirm on Build#109.

What I could reproduce: Have a teleport and try breaking the block as fast you can then get kicked

[video](https://i.qcfb.ca/20210717063553.mp4)
