### ISSUE TITLE
1.17.1 - Entities flicker rapidly inside Unloaded Chunks while in Spectator Mode

### ISSUE THREAD

**Issue by Kruize1** [PaperMC/Paper#6208]
### Expected behavior

Entities should be fully unloaded and not seen at all, if the Chunk is unloaded, while in Spectator mode. This is the behavior observed in 1.16 and previous versions of Paper. This is the expected behavior.

(Note: In Vanilla Minecraft the entity will be fully visible if you're within a few blocks of it)

### Observed/Actual behavior

Entities don't seem to fully unload while in Spectator Mode.

### Steps/models to reproduce

1. Ensure you are not in any spawn chunks 
2. Find some entities like an Item Frame or a Sheep
3. Walk over to the entities
4. Use gamerule " /gamerule spectatorsGenerateChunks false "
5. Enter spectator mode " /gamemode spectator "
6. If the Chunk isn't immediately unloaded, Log Out from the server, wait a few seconds, then Log In  (alternatively if you are well versed in the "forceload" command, you can use this to unload all chunks quicker)
7. Observe entities while in Spectator Mode

RESULT
- Entities flicker on and off indefinitely

### Plugin list

Reproduced with 0 plugins installed

### Paper version

This server is running Paper version git-Paper-108 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: a5acf36)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

https://user-images.githubusercontent.com/21042824/126019422-18283e7a-0f12-49a2-a584-4ff78c2f777e.mp4

**Comment by e-im** [comment]
I haven't been able to reproduce this behaviour. Are you on the vanilla client or using mods like optifine? If so, would you be able to try on the vanilla client? If this does persist with the vanilla client, is the same behaviour seen on the vanilla server?

**Comment by Kruize1** [comment]
I was able to reproduce with Optifine Client and Vanilla Client.

I updated my repro steps. Please ensure you are away from spawn chunks and ensure gamerule spectatorsGenerateChunks = false

Also added that you can unload chunks with the "forceload" command, for quicker results.

On a Vanilla Server I noticed the Entity will be fully visible to the player, not flickering, if the player is within a few blocks of the entity.

**Comment by e-im** [comment]
The same behaviour will be seen in vanilla, and really this is more just the gamerule being poorly named than anything- it looks intentional that these chunks will not be loaded. Something more like `spectatorsLoadChunks` would be a more appropriate name. This behaviour will not be seen when there are other players around loading the chunk, or as you said the chunk is forceloaded as in that case a player ticket is irrelevant.

Also reference [MC-157812](https://bugs.mojang.com/browse/MC-157812).

**Comment by Kruize1** [comment]
But this doesn't happen in Paper 1.16 and previous versions, the Entities fully unload, this should behave as it did in previous versions.

I request this be re-opened for further investigation.

I would also request this to be investigated as well for any potential performance issues too.

**Comment by Warriorrrr** [comment]
This issue has gone a bit stale, the spectatorsGenerateChunks gamerule currently doesn't do anything anymore (see #6657), nor is it likely to make a return, so I'll close this.
