### ISSUE TITLE
Lighting Updates Errors 1.8-1.11 

### ISSUE THREAD

**Issue by BladianYT** [PaperMC/Paper#621]
**The following are 'hard suggestions': if you have the information
available to you, you really should put it in the report. Choose one of
the following templates from below that best fits the issue you wish to
report.**

# Incompatibility (Bug)

### Paper build number:
Latest Build: March 3 1.11 Version
Oldest Build: Latest Paper Spigot containing 1.7/1.8 Protocol Hack

### What behaviour is expected:
Everything should be completely dark, with no visible light yet it doesn't. 

### What behaviour is observed:
Light updating not working in certain areas, with anything above 1.7

![2017-03-06_00 21 20](https://cloud.githubusercontent.com/assets/17993103/23592579/75bde666-0203-11e7-8057-62a529e17ef6.png)
![2017-03-06_00 21 28](https://cloud.githubusercontent.com/assets/17993103/23592580/791aedb8-0203-11e7-9d0d-723949096339.png)
![2017-03-06_00 21 14](https://cloud.githubusercontent.com/assets/17993103/23592582/7be86476-0203-11e7-9de2-5bcfa824d04c.png)

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
Worldedit

### Actions to reproduce (if known):
Perform these commands
//cyl bedrock 40
//hsphere bedrock 40

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

![screen shot 2017-03-06 at 00 23 49](https://cloud.githubusercontent.com/assets/17993103/23592569/4dc3d012-0203-11e7-9f83-92c487b32ddc.png)

[All YML's.zip](https://github.com/PaperMC/Paper/files/819851/All.YML.s.zip)

**Comment by sgdc3** [comment]
Older builds are unsupported, i'm sorry

**Comment by 0-x-2-2** [comment]
@sgdc3 he said it happens on the latest too

**Comment by sgdc3** [comment]
Oh, sorry i missed that

**Comment by zachbr** [comment]
Relevant upstream JIRA ticket https://hub.spigotmc.org/jira/browse/SPIGOT-3103

**Comment by Executioner1376** [comment]
Take This And Fix It ! Work For Me 
mv rule doDaylightCycle false world
If You Dont Need Weather
mv rule doWeatherCycle false world

**Comment by zachbr** [comment]
Paper has recently undone several lighting patches added by Spigot that essentially prevent the proper lighting routines from running.

Please let us know if you continue to see this behavior against the latest builds.
