### ISSUE TITLE
Server crashing after updating

### ISSUE THREAD

**Issue by DarkKingKaan** [PaperMC/Paper#6212]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://pastebin.com/6PUAhcgf

### Plugin list

https://i.imgur.com/nbJn7VL.png

### Actions to reproduce (if known)

There is no known way to reproduce this issue.

### Paper version

Latest Paper 1.17.1 (https://i.imgur.com/dhJaq96.png)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by DarkKingKaan** [comment]
The world was generated on 1.16, after updating I generated some extra terrain on 1.17.1 (chunks that were previously not loaded)

**Comment by akdukaan** [comment]
Is this a duplicate of #5980

**Comment by DarkKingKaan** [comment]
> Is this a duplicate of #5980

Might be, seems pretty similar. I've been trying to find plugins causing this with no success. I have tried pretty much everything, which lead me to reporting it to Paper and get it fixed ASAP.

**Comment by DarkKingKaan** [comment]
The server keeps crashing, here's another error: https://pastebin.com/8JKKNP1r
There were some people saying that updating specific plugins would fix the issue, but it didn't

**Comment by electronicboy** [comment]
I don't think it's 5980, for me, it looks like the load task has disappeared or something, is there anything in the earlier logs?

Also, in regards to plugins, I easily spotted two in that trace doing things which can bork the server, loading chunks off the main thread:
> [12:55:15] [Paper Watchdog Thread/ERROR]: 		com.ranull.graves.manager.GraveManager$2.run(GraveManager.java:77)

> [12:55:15] [Paper Watchdog Thread/ERROR]: 		com.loohp.interactionvisualizer.managers.PacketManager.lambda$run$0(PacketManager.java:62)

**Comment by DarkKingKaan** [comment]
What should I be looking for in the earlier logs?

**Comment by DarkKingKaan** [comment]
After removing the plugin mentioned above, the crashes seem to not be happening anymore, but later I still got some stack traces, causing severe TPS drops on the server. Here's one of them: https://pastebin.com/jAAbrPt1

**Comment by DarkKingKaan** [comment]
Got a few more stack traces if they could come in useful:
https://pastebin.com/TEw4eLpV
https://pastebin.com/Eng23yMy
https://pastebin.com/34BuPCE8

Severe TPS drops and entities issues occur as well.

**Comment by e-im** [comment]
Thank you for creating this issue and sorry for the lack of a quicker response, however, many issues related to this have been fixed since this was created, and no new recent reports have been received. If you are still experiencing this issue on 1.17.1, leave a comment.
