### ISSUE TITLE
Incorrect light levels (black areas) on a lot of places

### ISSUE THREAD

**Issue by 0xgrm** [PaperMC/Paper#622]
# Incompatibility (Bug)

### What behaviour is expected:
Correct light levels in shadowed areas.

### What behaviour is observed:
In some places where there are shadows, like under trees, in mountains, caves, etc., light levels are sometimes incorrect, e.g. completely dark.

It happens on random places on all worlds I have tested, but the most prominent case is in the jungle. It's very distractive and annoying because we have to place some torches on these areas for light levels to correct.

These issues _ARE NOT_ happening on vanilla CraftBukkit. It is so annoying that, as of now, we are using CraftBukkit despite the horrendous performance.

Here are 2 images illustrating the bug and showing the differences between vanilla CraftBukkit and Paper Spigot:

_CraftBukkit: correct light levels_
![CraftBukkit](https://i.imgur.com/NM85HOD.jpg)

_Paper Spigot: incorrect light levels_
![Paper Spigot](https://i.imgur.com/0AmSQzg.jpg)

I'm somewhat surprise that more people are not complaining at all.

### Steps/models to reproduce:
You can reproduce this on any world but the best places are the jungle biomes.

There are some variations with the 'random-light-updates' setting:

-  if set to _false_, these errors remain uncorrected if the areas are not torched ;
- if set to _true_, the  errors are corrected if the chunks are unloaded then reloaded, e.g. after reconnecting on the server or by traveling far enough for the chunk to be unloaded.

### Plugin list:
- dynmap
- worldedit
- worldguard
- worldborder

### Paper build number:
git-Paper-1062 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Please copy your paper.yml file here, or to a gist, or somewhere we can see it.

**Comment by 0xgrm** [comment]
Here's my [paper.yml](https://gist.github.com/uryupinsk/c650d4a6a419224482ba1efa878d869e).

**Comment by Executioner1376** [comment]
on spigot.yml
random-light-updates: true

world-settings:
  default:
    verbose: true

view-distance: 5

**Comment by Executioner1376** [comment]
Multiverse-Core take this
delete dynmap if you dont need that
delete worldborder to

Find Multiverse-Core folder end edit worlds.yml
Find Your Worlds and set scale: '4.0' or 4.5
you can allowWeather: 'true' set it false if you dont need Weather

**Comment by 0xgrm** [comment]
I have another test server where I disabled all plugins, and by switching between CraftBukkit and Paper Spigot, the problem is still there.

I need weather so disabling it is not a good solution for me.

Thanks a lot for your help, I appreciate the dedication to your project.

**Comment by Executioner1376** [comment]
Take This And Fix It ! Work For Me
mv rule doDaylightCycle false world
If You Dont Need Weather
mv rule doWeatherCycle false world

**Comment by Moutard3** [comment]
That's not a solution @Executioner1376 ...

**Comment by zachbr** [comment]
Paper has recently undone several lighting patches added by Spigot that essentially prevent the proper lighting routines from running.

Please let us know if you continue to see this behavior against the latest builds.
