### ISSUE TITLE
Paperspigot 1.12.2 (lag/crash server)

### ISSUE THREAD

**Issue by ducdzz61** [PaperMC/Paper#6232]
### Stack trace

https://pastebin.com/q6ecGGP9

### Plugin list

?

### Actions to reproduce (if known)

https://pastebin.com/q6ecGGP9

### Paper version

This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

it's all in the logs, please take a look and fix it for me

**Comment by limbo-app** [comment]
Hey @ducdzz61! You seem to be running an unsupported version (1.12) of Paper.

If you can reproduce this issue with the latest supported version, please [open a new issue](https://github.com/PaperMC/Paper/issues/new) with updated information.
