### ISSUE TITLE
seed block

### ISSUE THREAD

**Issue by NightLife-SG** [PaperMC/Paper#6234]
### Is your feature request related to a problem?

Seed cracker such as https://github.com/KaptainWutax/SeedCracker

player are able to crack the seed without having permission

### Describe the solution you'd like.

Someway to block the hack?

### Describe alternatives you've considered.

i dont know...

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by e-im** [comment]
Duplicate of https://github.com/PaperMC/Paper/issues/6086
