### ISSUE TITLE
Some NavigationAbstract methods are not properly reobfuscated

### ISSUE THREAD

**Issue by datatags** [PaperMC/Paper#6243]
### Expected behavior

All methods in NavigationAbstract to be obfuscated, like how they are on Spigot.
(net.minecraft.world.entity.ai.NavigationAbstract, Mojang mappings call it PathNavigation)

### Observed/Actual behavior

10 overloads of the createPath method are still named.

### Steps/models to reproduce

1. Build Paper
2. Decompile patched jar
3. See net.minecraft.world.entity.ai.NavigationAbstract has non-obfuscated methods
4. Compare to NavigationAbstract in decompiled Spigot

### Plugin list

None

### Paper version

> ver
[09:46:59 INFO]: Checking version, please wait...
[09:46:59 INFO]: This server is running Paper version git-Paper-119 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f25facb)
You are running the latest version
Previous version: git-Paper-112 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
https://github.com/PaperMC/paperweight/issues/24
