### ISSUE TITLE
error cave_spider

### ISSUE THREAD

**Issue by PABLORAGNIzc** [PaperMC/Paper#6250]
### Expected behavior

Cave spiders when attacking should grant poison.

### Observed/Actual behavior

The cave spiders when attacking are not granting poison.

### Steps/models to reproduce

You must go to a cave and find a cave spider spawner or simply give yourself a spawner with the command / give <player> spawner <quantity> and place a cave spider egg on top of the spawner.
After that you must allow yourself to be attacked by these mobs and you will see that the cave spiders do not apply the poison effect to the player.

video: https://www.youtube.com/watch?v=OY1BApzLQEg

### Plugin list

![plugins](https://user-images.githubusercontent.com/84411800/126691094-b0ee4a0a-fcd0-42fc-ab9c-5f3ddc1dc49c.png)

### Paper version

![version](https://user-images.githubusercontent.com/84411800/126691245-f5370e7c-7df9-47a8-a8bb-f79e10d9e404.png)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
What is your game difficulty?

https://minecraft.fandom.com/wiki/Cave_Spider#Poison

Cave spiders only apply poison in normal or hard difficulty

**Comment by PABLORAGNIzc** [comment]
> What is your game difficulty?
> 
> https://minecraft.fandom.com/wiki/Cave_Spider#Poison
> 
> Cave spiders only apply poison in normal or hard difficulty

easy.

**Comment by Machine-Maker** [comment]
Then change the difficulty

**Comment by PABLORAGNIzc** [comment]
> Entonces cambia la dificultad

sorry, if that was it. Thanks for your help!
