### ISSUE TITLE
PlayerPortalEvent fired even when `allow-nether=false`

### ISSUE THREAD

**Issue by benwoo1110** [PaperMC/Paper#6258]
### Expected behavior

The `world_nether` world is loaded but `PlayerPortalEvent` should not be fired when player enters a nether portal.

### Observed/Actual behavior

The `world_nether` world is **not** loaded. However, if I manually load the `world_nether` with WorldCreator through a simple test plugin, PlayerPortalEvent is fired when player enters a nether portal.

### Steps/models to reproduce

1. A fresh install of paper server.
2. Set `allow-nether=false` in server.properties file.
3. Install the test plugin linked below.
4. Create a nether portal and let a player enter it.

### Plugin list

> plugins
[22:09:29 INFO]: Plugins (1): TestPlugin

### Paper version

> version
[22:02:26 INFO]: Checking version, please wait...
[22:02:26 INFO]: This server is running Paper version git-Paper-124 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 170382f)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Code of simple test plugin: https://paste.gg/p/anonymous/36a40dbebfff403d8677ba7cf542c444
File of simple test plugin: [TestPlugin-1.0-SNAPSHOT.zip](https://github.com/PaperMC/Paper/files/6869302/TestPlugin-1.0-SNAPSHOT.zip)

Although tested on 1.17.1, it's likely not 1.17 specific. Its believed that the issue does not occur before paper-1.16.5-664. There is a lengthy discussion at https://github.com/Multiverse/Multiverse-Core/issues/2634 but note I manage to reproduce without mv installed as shown above. 

Not sure if this is an intentional change, but it has definitely caused issues with what people expect `allow-nether` config option does.

**Comment by Proximyst** [comment]
The option isn’t `disable-portals`; don’t make a dimension a portal targets if you don’t want it to fire its events…

**Comment by benwoo1110** [comment]
According to https://minecraft.fandom.com/el/wiki/Server.properties
![](https://cdn.discordapp.com/attachments/333608809119350785/868136670296416297/unknown.png)

 As well as https://docs.spongepowered.org/6.0.0/en-GB/server/getting-started/configuration/server-properties.html
![image](https://user-images.githubusercontent.com/30431861/126796725-217ecf7f-8d86-48d6-80cc-78cf122e8ffd.png)


`allow-nether=false` should disable usage of nether portal. And if nether portal should not work, `PlayerPortalEvent` should logically not be fired as well.

I do appreciate it if you can take some time to look into this issue. 😄

**Comment by kennytv** [comment]
The Minecraft wiki is not official documentation, but in any case, the check for portal logic was manually removed by CB.

**Comment by benwoo1110** [comment]
So the above behaviour change is intended?

**Comment by nicegamer7** [comment]
I do not believe there ever was a check regarding this option. If there was, I can't seem to find it, https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/server/level/EntityPlayer.patch.

I would say this is a bug, but not a Paper one. I'm the one who made the change that made this issue more apparent (it was always an issue). If I fix it upstream, will it be reverted here?

**Comment by Proximyst** [comment]
> [...] If I fix it upstream, will it be reverted here?

No

**Comment by nicegamer7** [comment]
Okay, then off I go.
