### ISSUE TITLE
Server crashes and shuts down

### ISSUE THREAD

**Issue by PABLORAGNIzc** [PaperMC/Paper#6259]
### Stack trace

https://pastebin.pl/view/d7a0539e

### Plugin list

![plugins](https://user-images.githubusercontent.com/84411800/126823014-e6fcbc2b-0c16-4d41-ad79-1bde9e0ed8cd.png)

### Paper version

![version paper](https://user-images.githubusercontent.com/84411800/126823171-42693a9e-5113-49f6-b35c-e400caed249a.png)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by HexedHero** [comment]
Use paste.gg, that link gets blocked by anti-viruses

**Comment by electronicboy** [comment]
Your JVM/Machine is overloaded
