### ISSUE TITLE
Player#setWalkSpeed breaks walk speed

### ISSUE THREAD

**Issue by metabrixkt** [PaperMC/Paper#6263]
### Expected behavior

```java
Player player = Bukkit.getPlayer("l_MrBoom_l"); // my name
float walkSpeed = player.getWalkSpeed();
player.setWalkSpeed(0f);
Bukkit.getScheduler().runTaskLater(this, () -> player.setWalkSpeed(walkSpeed), 20);
```
This code sets walk speed to 0 and sets it back to normal in a second (20 ticks).
It works fine, nothing gets broken.

### Observed/Actual behavior

```java
Player player = Bukkit.getPlayer("l_MrBoom_l"); // my name
float walkSpeed = player.getWalkSpeed();
player.setWalkSpeed(0f);
Bukkit.getScheduler().runTaskLater(this, () -> player.setWalkSpeed(walkSpeed), 20);
```
This code sets walk speed to 0 and sets it back to normal in a second (20 ticks).
It works fine, however if you leave your walk speed gets set to 0 for some reason (NBTExplorer says it's actually 0.0 for some reason). If I remove all plugins, `/stop` and start the server again my walk speed resets to 0, it's now broken forever. I can set it to normal with `/attribute`, but when I rejoin the server it's broken again.

Deleting <player uuid>.dat fixes the issue.

### Steps/models to reproduce

1. Create a small plugin with the code provided above.
2. Trigger this code
3. Rejoin.
4. Your walk speed is now broken even if you remove all plugins.

### Plugin list

Read `Observed/Actual behavior`.

### Paper version

> version
[16:22:10 INFO]: Checking version, please wait...
[16:22:11 INFO]: This server is running Paper version git-Paper-127 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9a0263e)
You are running the latest version
Previous version: git-Purpur-1296 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by kennytv** [comment]
Attributes are permanent, so if you want to reset the value you have to... reset the value, for example on server shutdown/when the player quits.

**Comment by metabrixkt** [comment]
> Attributes are permanent, so if you want to reset the value you have to... reset the value, for example on server shutdown/when the player quits.

@kennytv No, it just resets to 0, it gets fixed if I run `/attribute l_MrBoom_l minecraft:generic.movement_speed base set 0.10000000149011612`, but if I leave it resets.

I can set it to `0` with `/attribute l_MrBoom_l minecraft:generic.movement_speed base set 0.0` and in a second run `/attribute l_MrBoom_l minecraft:generic.movement_speed base set 0.10000000149011612` to restore it to normal, nothing get broken, but with player.setWalkSpeed it doesn't work this way.

**Comment by electronicboy** [comment]
I was playing with this stuff literally day before yesterday and all worked as intended, are you disconnecting between the 0 being set and the other value being set?

reproduce with a minimal test setup, i.e. just that code in a plugin

**Comment by metabrixkt** [comment]
> I was playing with this stuff literally day before yesterday and all worked as intended, are you disconnecting between the 0 being set and the other value being set?
> 
> reproduce with a minimal test setup, i.e. just that code in a plugin

@electronicboy I tested it with this tiny plugin only, I don't have any other plugins and I didn't have them in the server directory I got this bug in. The problem is that:
```
/attribute l_MrBoom_l minecraft:generic.movement_speed base set 0.0
*wait a second*
/attribute l_MrBoom_l minecraft:generic.movement_speed base set 0.10000000149011612
```

```java
Player player = Bukkit.getPlayer("l_MrBoom_l");
float walkSpeed = player.getWalkSpeed();
player.setWalkSpeed(0f);
Bukkit.getScheduler().runTaskLater(this, () -> player.setWalkSpeed(walkSpeed), 20);
```

these things must work the same way, vanilla command way to do this works without bugs, but plugin way with setWalkSpeed breaks movement speed

**Comment by kennytv** [comment]
It doesn't, I just tested with your code only on the latest Paper version. The only way this can possibly break is if you disconnect before the reset code is called a second later.

**Comment by metabrixkt** [comment]
Ok, lemme test again

**Comment by kennytv** [comment]
What is likely to be the issue you're having here is that the attribute command is not the exact same as calling `setWalkSpeed`. The Bukkit method also touches player abilities, which are stored separately. So, if you want to restore what was set by `player.setWalkSpeed(0f);`, you have to call the method again.

**Comment by metabrixkt** [comment]
> What is likely to be the issue you're having here is that the attribute command is not the exact same as calling `setWalkSpeed`. The Bukkit method also touches player abilities, which are stored separately. So, if you want to restore what was set by `player.setWalkSpeed(0f);`, you have to call the method again.

I see what you mean, I understand what I did wrong, sorry for taking your time
