### ISSUE TITLE
[1.16.5] mobs spawning even in lit up areas

### ISSUE THREAD

**Issue by vaniron** [PaperMC/Paper#6274]
### Expected behavior

monsters not spawning in lit up areas

### Observed/Actual behavior

monsters spawning in lit up areas - even 1 block away from torches

### Steps/models to reproduce

Place the torch, wait for the night - monsters still spawning.

### Plugin list

none

### Paper version

1.16.5. #783

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by vaniron** [comment]
maybe something to do with https://bugs.mojang.com/browse/MCPE-49616 ?

**Comment by Machine-Maker** [comment]
The issue you linked is for bedrock.

And I cannot reproduce this on 1.16.5 build 738.

If you can provide additional info that leads to a reproduction, the issue can be reopened. Like if you have any datapacks, or something like that.
