### ISSUE TITLE
Suggestion: "EntityDespawn" or "EntityUnload" event

### ISSUE THREAD

**Issue by jaylawl** [PaperMC/Paper#6280]
### Is your feature request related to a problem?

Sort of. Before 1.17, i used to be able to "check" for entities being unloaded by iterating through chunks which are currently being unloaded, via listening to `ChunkUnloadEvent`. This no longer appears to work reliably and afaik there is no event to handle this with. `EntityRemoveFromWorldEvent` only fires, when the entity is being fully removed from the server, not when the entity is being unloaded.

I would assume that my previous method no longer works, because entities are stored seperately from world data, starting with 1.17.

### Describe the solution you'd like.

A simple informative event that can be used to fetch entities which are about to be unloaded but not removed (that would respawn with chunks being loaded).

### Describe alternatives you've considered.

I tried handling it via `EntityRemoveFromWorldEvent` but that doesn't cut it as per why explained above.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by jaylawl** [comment]
Debugging update: it seems like you can get the entities of an unloading chunk (on the `ChunkUnloadEvent`) still, using the `Chunk#getEntities()` method - although i have not yet been able to confirm the reliability of this. However it does most certainly not do that for the `ChunkLoadEvent`.

**Comment by imDaniX** [comment]
> However it does most certainly not do that for the `ChunkLoadEvent`.

Was it before tho? I was always delaying getting entities for one tick with `Chunk#isLoaded()` check, cuz chunks were clearly not returning all entities on `ChunkLoadEvent`.

**Comment by jaylawl** [comment]
> 
> 
> > However it does most certainly not do that for the `ChunkLoadEvent`.
> 
> Was it before tho? I was always delaying getting entities for one tick with `Chunk#isLoaded()` check, cuz chunks were clearly not returning all entities on `ChunkLoadEvent`.

Welp, i never even thought that far. Prior to 1.17 just getting the entities upon chunk load used to work for me anyway; even without delay. But now we have the `EntityAddToWorld` event which seems to be the non-hacky method anyway. Good input though, thank you!

**Comment by jaylawl** [comment]
I feel stupid. Just tested and figured out that EntityRemoveFromWorldEvent already handles this. Previously i thought that this event was only called when the entity is removed (as in deleted), but it turns out it's fired every time the entity is actually unloaded for any reason, including deletion.
