### ISSUE TITLE
PAPER CRASH

### ISSUE THREAD

**Issue by PABLORAGNIzc** [PaperMC/Paper#6282]
### Stack trace

https://pastebin.pl/view/63fcb64c

### Plugin list

![plugins](https://user-images.githubusercontent.com/84411800/127247141-23422bf8-9796-4a2e-99e9-47f6df75b410.png)

### Actions to reproduce (if known)

Every 5/6 hours the server crashes with this error. This server started in version 1.16 and since we update to version 1.17.1 it crashes and shuts down every day.

### Paper version

![paperversion](https://user-images.githubusercontent.com/84411800/127247291-a9238c9a-d4c0-452b-bb50-a6a5599bcfff.png)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

He has already contacted my host and they tell me that the CPU is high and that is why they cooled it down several times, however this does not solve it and it keeps crashing.
![CPU](https://user-images.githubusercontent.com/84411800/127247372-4f5e8995-e9f8-402a-8a12-6eb3dfcc2d33.png)

**Comment by electronicboy** [comment]
Server crashed likely due to illegal/excessive player movement, there is options in paper.yml to prevent moving into unloaded chunks which can help mitigate this, but, seems like their excessive movement ends up causing too much work for the server to keep up

**Comment by PABLORAGNIzc** [comment]
> Server crashed likely due to illegal/excessive player movement, there is options in paper.yml to prevent moving into unloaded chunks which can help mitigate this, but, seems like their excessive movement ends up causing too much work for the server to keep up

Good. I'm sorry to bother you, I'm probably very busy and my problem is not a priority for you. But, I really have been dragging a lot of problems with my server since I updated to version 1.17.1. Tell me, please, what section are you in to fix this error?

**Comment by electronicboy** [comment]
if you mean, "what section is the config I'm talking about", open paper.yml, ctrl-f "unloaded" and you'll find it, otherwise, I have no idea what you're talking about

**Comment by PABLORAGNIzc** [comment]
prevent-moving-into-unloaded-chunks: true o false?

**Comment by PABLORAGNIzc** [comment]
> si te refieres a "de qué sección es la configuración de la que estoy hablando", abre paper.yml, ctrl-f "descargado" y lo encontrarás, de lo contrario, no tengo idea de lo que estás hablando

This option was already set to "true" and it crashes anyway. What other possible solution can you think of?

**Comment by electronicboy** [comment]
This is not a support thread, please use the discord/IRC/forums for support

**Comment by PABLORAGNIzc** [comment]
I will give the following information to how I got the solution to this problem.
This finding may be useful for all those who get an error on their console with this message "VoxelShape Related Crash"

You must do the following:

PAPER.YML:
prevent-moving-into-unloaded-chunks: false

And then you need to turn on your server with this command

java -Xms2G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs/ -Daikars.new.flags=true -jar paper-1.17.1-137.jar nogui

It is important that you set these values "java -Xms2G -Xmx6G"

I hope it helps you!
