### ISSUE TITLE
API for permission plugins instead of reflectively replacing permissible

### ISSUE THREAD

**Issue by A248** [PaperMC/Paper#6285]
### Is your feature request related to a problem?

Permission plugins often reflect into CraftHumanEntity to access the `perm` field in order to inject their own permissible.

It is generally beneficial to the ecosystem for plugins to use API rather than reflecting into internals.

### Describe the solution you'd like.

The most straightforward solution would be to add the following method to Player and implement it in CraftPlayer/CraftHumanEntity:
```java
void setPermissible(@NonNull Permissible permissible);
```

Ideally, the parameter is Permissible. However, a PermissibleBase-accepting method is still a minimally acceptable solution.

### Describe alternatives you've considered.

Adding a new and alternative permission plugin API is another solution. However, this may deter permission plugins from using this new API if they still wish to maintain compatibility with versions of the Bukkit API lacking this enhanced permission API.

It is easier to write a permission plugin that uses the `setPermissible` method where it exists and reflects into the field where such method does not exist than it is to write a plugin that uses a completely different permission API where such API exists.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

I believe it is theoretically possible to write a basic permission plugin which does not replace the permissible. Nevertheless, this API would be useful for plugins which do choose to replace the permissible in order to support more advanced behavior.

**Comment by Proximyst** [comment]
I honestly dislike the entire permissions API as it stands, but perhaps an ”internal api” (read: `CraftHumanEntity#setPermissible` with no accompanying interface definition) would be acceptable?

**Comment by A248** [comment]
An "internal API" defeats the point of this issue, which is having plugins depend on API methods rather than relying on internals. I'm much more willing to introduce a new permissions API.

If you think the permissions API needs an overhaul, is there a restructure you would like to propose? I agree that Permissible and PermissionAttachment constitute a quite messy API. They remind me of the chat event API: the old model was lacking in API capability which a new and better abstraction ought to replace. The current chat API is well-furbished, despite a couple early deprecations which are minor in importance. With good design, a new permissions API could follow a similar story.

I initially thought against an alternative permissions API because of the reason I elaborated above, its potential for dissuading permission plugins from fully implementing it. However, this is mostly due to my guess as to others' inclinations. Personally, I would find a new permissions API considerably well and I would be supportive of one.

**Comment by Proximyst** [comment]
I’m not entirely sure. I could write up a draft to submit for discussion later today; I need to refamiliarise myself properly with the API as it stands first.

**Comment by electronicboy** [comment]
the defalt perm impl is pretty much a string match based system rather than allowing anything magical or even allowing plugins to just intercept perm checks themselves, which is the important aspect here, plugins want to manage everything themselves so any API replacement which quite simply doesn't allow plugins to just intercept all hasPerm things would basically be a failure, which is where I question where any of this could go, good question would probs be "how does sponge do it", but, afaik they just basically have a built in services manager and a permission interface which plugins implement and toss into the services manager and that's it;

I do know some people who use the current system as-is *aikar*, idk any competent perm plugin these days which doesn't just completely replace the built in
