### ISSUE TITLE
Bukkit#getOfflinePlayers needs a warning

### ISSUE THREAD

**Issue by Xemorr** [PaperMC/Paper#6286]
### Is your feature request related to a problem?

I wrote a plugin that sends a message when people join and it used Bukkit.getOfflinePlayers().length to see how many people had joined before and was doing this every time, but because there was no warning on the method or anything I didn't realise how expensive this was and it was causing lag spikes. I've fixed it now by caching and handling the count myself, but could be good for others in the future.

### Describe the solution you'd like.

Add a comment above Bukkit#getOfflinePlayers explaining that it's very expensive and that it loads all the files from disk yadayada.

### Describe alternatives you've considered.

Hoping users of the API aren't idiots like I was

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Proximyst** [comment]
I like the alternative

**Comment by Camotoy** [comment]
Perhaps deprecate this method and instead create `computeOfflinePlayers`?

**Comment by Doc94** [comment]
how many offline users can cause this lag spikes?

**Comment by electronicboy** [comment]
It reads every .dat file inside of the player data folder, boils down to many factors, OS, filesystem type, etc, etc, etc

**Comment by A248** [comment]
Don't deprecate the method, add the warning to the javadoc as suggested.

That way, if someone makes the same mistake you did, they will at least learn something. Specifically, they will learn to read javadocs.

**Comment by Xemorr** [comment]
> 
> 
> how many offline users can cause this lag spikes?

We have a couple thousand offline users and it became blatantly obvious when using spark tickmonitor. There'd be a like 200ms to 300ms tick.
