### ISSUE TITLE
Change the Gson version to latest

### ISSUE THREAD

**Issue by CodedInfinityFlo** [PaperMC/Paper#6289]
### Is your feature request related to a problem?

Due to the fact that Paper still uses the Gson version 2.8.0 from 2016. This brings me in some plugins again and again errors, which leads to the fact that Gson is simply unusable with Paper.

### Describe the solution you'd like.

I would like to see the version of Gson at Paper changed to 2.8.7 (latest)

### Describe alternatives you've considered.

I always had to build Paper myself and change it myself and to be honest that sucks a little bit

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Machine-Maker** [comment]
> Paper still uses the Gson version 2.8.0 from 2016

“Paper” doesn’t use that version of Gson, Mojang does.

> I always had to build Paper myself and change it myself and to be honest that sucks a little bit

you can shade in the latest gson yourself into your plugin. No need to keep your own fork of paper.

**Comment by CodedInfinityFlo** [comment]
> you can shade in the latest gson yourself into your plugin. No need to keep your own fork of paper

But there are classes which contain the same name and each class can only be loaded once into the classpath.There are some classes which have the same 



> “Paper” doesn’t use that version of Gson, Mojang does.

Yes but paper is able to change it for the paper builds

**Comment by underscore11code** [comment]
> But there are classes which contain the same name and each class can only be loaded once into the classpath.There are some classes which have the same

Shade & relocate your own gson.

**Comment by Machine-Maker** [comment]
> Shade & relocate your own gson

yes, I should’ve included that “relocate” part.

**Comment by Proximyst** [comment]
We are going to stay on par with Mojang for compatibility reasons.
