### ISSUE TITLE
Resetting/Regenerating chunks not working properly

### ISSUE THREAD

**Issue by melinstagibson** [PaperMC/Paper#629]
###  Timings or Profile link:
https://timings.aikar.co/?id=46d3e29885784c59b547a5a09a2ffce8

### Description of issue:
I now tried several ways of chunk regeneration and i get the same result every time. Worldedit //regen messes up villages and nether fortresses and mineshafts (most likely many other things too) aswell as cavespider and blaze spawners get removed.

Same happens with Skript's reset chunk expression 

After that i tried this plugin:
https://www.spigotmc.org/resources/regionerator.12219/
And it still would not generate blazespawners.

As all plugins able to regenerate chunks i know of seem to be broken currently i figured this might be an issue with paper or even spigot?

Sorry if i cant provide any more informations

The configs, plugins and version informations can be found in the timings link

# Suggestion
I dont know if this is a spigot or minecraft issue (i tried with spigot too, same results) but i hope it can be solved here

**Comment by melinstagibson** [comment]
After some more tests i found out that, if you delete the region files only, it will NOT regenerate certain parts of structures. (like spawners, i dont know what else since this is my focus atm, but i guess chests in fortresses too)

So i tried deleting the world/data folder too and this fixed it (fixed in terms of the chunks will properly generate then if i delete the files)

After some reading i would say that those strucutre files in that data folders of each world save if a spawner or other "decorations" in structures (mineshafts, fortress, etc) have already been generated? and thus wont be generated again even if you delete the region files?

So this most likely wont help a plugin that regenerates cerain chunks and wont just delete the region files but i hope its of some help to find the issue.

**Comment by melinstagibson** [comment]
Or is it related to the terrain populated NBT data tag? 

http://minecraft.gamepedia.com/Chunk_format

**Comment by zachbr** [comment]
Many structure definitions are stored separately as NBT data under world/data/*.dat.
For example ```world/data/Mineshaft.dat```

I haven't looked but it seems likely that the game will not create the necessary in-game block representations for these structures if they are already identified in a structure data file.

**Comment by melinstagibson** [comment]
Ok well i hope there is any way you guys can fix this somehow, im just surprised noone has brought this up yet because i use chunk regeneration ALOT on my survival servers...

**Comment by melinstagibson** [comment]
https://www.spigotmc.org/threads/regionerator.92022/page-8#post-2297385

Maybe the infos in thisconversation help a bit

**Comment by Shevchik** [comment]
Yeah, i'm always getting the same question with my autosveworld worldregen feature. But in my case world is regenerated fully, so i can delete them (which i don't do right now).
But they can safely be deleted if you don't plan to change your world generator any time soon. Or if you want to only remove unneded entries here is the format http://minecraft.gamepedia.com/Generated_structures_data_file_format.
Also you can configure the server to do not save structure info, afaik there was such option (This will also speed up saving).

**Comment by aikar** [comment]
This is a vanilla impl detail. The only way to fix this is to add an API to wipe out any structure data registered found for X/Y/Z position.

**Comment by Shevchik** [comment]
API for removing the chunk (instead of regenerating it), and for getting all existing chunks would be good too.

**Comment by melinstagibson** [comment]
So is there any chance we will get a working chunk regeneration method back or is that just not possible to realize anymore? I suppose this or the spigot issue tracker are the only places capable of fixing it?

**Comment by aikar** [comment]
If someone PR'd it and it passed review, I see no reason why we wouldn't pull it. But as for me doing the work, highly unlikely any time soon.

**Comment by melinstagibson** [comment]
Well if anyone is interested, im willing to spend a 100$ on this, i made a thread for a plugin request on spigotmc too but ill happily also spend it if someone is willing to fix the method for paperspigot or spigot and thus make it publicly available.
I know, might be the wrong place for it but im a bit desperate, here is the thread if anyone cares
https://www.spigotmc.org/threads/chunk-regeneration-plugin-skilled.224135/

**Comment by Shevchik** [comment]
The problem is the way how structures should be handled. If we reset the main structure chunk and remove data about it, new structure will be generated, but it may overlap with already existing structure part. Anyway for autosaveworld i'm planning to remove structure only if all chunks inside structure bounding box are removed, so you cat take the code from it when i will finish it.

**Comment by melinstagibson** [comment]
well im not a developer so i cant really judge, everything i heard until now is that it might be doable with nms code and somehow access the data files but how would i know... im just forwarding infos i got somwhere else (which might be worthless)

**Comment by melinstagibson** [comment]
i tried deleting chunks and also the whole structure files which made it regenerate everything but it kinda didnt fit very well with the chunks next to them and the structures themselves seemed kinda "odd" altho that might be my imagination
