### ISSUE TITLE
Piglin spawns low after initial spawning 

### ISSUE THREAD

**Issue by BumbleTree** [PaperMC/Paper#6291]
### Expected behavior

Piglin farms to spawn a constant flow of piglins
Hoglins to spawn a decent amount

### Observed/Actual behavior

After the initially spawned piglins die the spawn rate is terrible.
Players have been complaining about nether mobs spawns been awful forever including hoglins, though no complaints about any mobs not in the nether.

Per player mob spawns is set to True
VD 6
No tick Distance 8
Hard despawn 92

spawn-limits:
  monsters: 42
  animals: 10
  water-animals: 6
  water-ambient: 3
  ambient: 2
chunk-gc:
  period-in-ticks: 400
ticks-per:
  animal-spawns: 400
  monster-spawns: 5
  water-spawns: 100
  water-ambient-spawns: 400
  ambient-spawns: 400

### Steps/models to reproduce

On server restart see a good amount of piglins on the farm.

Agro them for initial group of piglin to die. Suddenly get terrible spawn rates (Even dropping to 0 spawning for a few mins) Literally 0

### Plugin list

Plugins (36): AFKPlus, AFKPlusPrefix, AdvancedTeleport, AnvilColor, ArmorStandTools, AutoMessage, BuycraftX, ColoredSigns, CoordinatesHud, CoreProtect, DeathCoordinates, DiscordSRV, DiscordSRV-Staff-Chat, DropHeads, FarmControl, GSit, Hat, LuckPerms, MyCommand, OnePlayerSleep, OpenInv, Pl3xMap, PlaceholderAPI, Plan, ProtocolLib, ServerUtils, SpectatorMode, SurvivalInvisiframes, SysoutCatcher, TAB, Vault, VentureChat, WorldEdit, WorldGuard, floodgate and spark

### Paper version

I normally use airplane but for spawning issues i have tried tuinity and paper. Same issues.
The build was Build # 124 from paperMC

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by AlessioGr** [comment]
Players have been complaining about low mob spawns on my server as well in 1.17. Setting the monsters: limit to 20 or lower broke all enderman farms.
When you first teleported to the enderman farm, you see two dozen endermen spawning, and then none spawn any more. So somehow, they only spawned when the chunk is loaded. Weird.

Works fine with mob limit 40, but then players are complaining about mobs spawning too often outside of farms (when just walkin around).

Mob farms like these: https://staticg.sportskeeda.com/editor/2021/02/77024-16134300689780-800.jpg won't work no matter the mob spawn limit.

**Comment by Owen1212055** [comment]
There have been significant changes to persistence and how the mob counts have counted thanks to upstream reverting some changes it made to that system.

Do you still find the spawn rates to be lower than normal?

**Comment by lynxplay** [comment]
As no more information on this was provided for now 20 days, I am closing this issue.

If you still experience this issue on latest paper and can provide proper replication steps, feel free to just comment on this issue so we can reopen it :+1:
