### ISSUE TITLE
Invincible Player Bug with Shield

### ISSUE THREAD

**Issue by twk1024** [PaperMC/Paper#6295]
### Expected behavior

When players with shields are not activating the shield, other players should be able to attack that player.

### Observed/Actual behavior

When this bug happens, it is not able to hit that player even though that player didn't activate the shield.

### Steps/models to reproduce

1. Equip shield on the offhand inventory.
2. Right-click to activate the shield. (Keep clicking)
3. Kill that player who has the shield.
4. When that player with a shield dies, the shield keeps being activated even though that player with a shield does not click the right button to activate the shield.
5. When that player with a shield activates the shield himself then that player goes to normal.

### Plugin list

Plugins (11): BlockLocker, CoreProtect, Essentials, floodgate, Geyser-Spigot, gProtector, LuckPerms, MOTD*, OpenInv, ProtocolLib, Themis

### Paper version

This server is running Paper version git-Paper-138 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 7a5025d)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I recorded a video about this bug.
[https://youtu.be/BBeSNlCNXhQ](https://youtu.be/BBeSNlCNXhQ)

**Comment by Strahilchu** [comment]
Can you recreate it without any plugins?

**Comment by Doc94** [comment]
Confrmed but using keepInventory, and tested in spigot then this issue is from spigot.

**Comment by twk1024** [comment]
> Confrmed but using keepInventory, and tested in spigot then this issue is from spigot.

Yes, it happens when using keepinventory, because to make this bug happens, the player should not interact with the item.

So, you mean this is a spigot bug? Should I go to Spigot's github and open an issue?

**Comment by Doc94** [comment]
> > Confrmed but using keepInventory, and tested in spigot then this issue is from spigot.
> 
> Yes, it happens when using keepinventory, because to make this bug happens, the player should not interact with the item.
> 
> So, you mean this is a spigot bug? Should I go to Spigot's github and open an issue?

Yeah in JIRA (of spigot) but i already report this issue when test in spigot using the examples here. https://hub.spigotmc.org/jira/browse/SPIGOT-6682

**Comment by twk1024** [comment]
> Yeah in JIRA (of spigot) but i already report this issue when test in spigot using the examples here. 

Oh okay then we should wait until they fix this bug

**Comment by Doc94** [comment]
Fixed in Craftbukkit https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/e1c96e507f7019e30e353166645d6dbeaa6c1482
