### ISSUE TITLE
PAPER CRASH #2

### ISSUE THREAD

**Issue by PABLORAGNIzc** [PaperMC/Paper#6303]
### Stack trace

https://paste.gg/p/anonymous/18e18f394a5a4b878f49466f12fea76b

### Plugin list

![Uploading plugins.png…]()

### Paper version

![paperversion2](https://user-images.githubusercontent.com/84411800/127752882-bcc62dad-87c7-4c6c-b3bf-db24aa026032.png)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
You keep reporting the exact same issue and generally just straight up ignore what we're saying, given that this is the 3rd time, your access to the issue tracker at this stage is being revoked.
