### ISSUE TITLE
Introduce a slime-spawn-height config option

### ISSUE THREAD

**Issue by baailey** [PaperMC/Paper#6305]
### Is your feature request related to a problem?

Currently, Minecraft Slimes will, by default, only spawn below Y:40. If in a swamp biome, then they can spawn between Y:50-70. This can be fairly annoying, especially when trying to utilise spawners (via spawner related plugins) at a base that is built on the surface level.

### Describe the solution you'd like.

Seeing as there is a `squid-spawn-height` option, I'd like for a new config option that allows server owners to customise what Y level they would like Slimes to spawn.

### Describe alternatives you've considered.

N/A

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by atticus2613** [comment]
I am new

**Comment by Titaniumtown** [comment]
huh?

**Comment by Chew** [comment]
Please don't spam the issue tracker, people get emails for these types of stuff...
