### ISSUE TITLE
Scoreboard Dropped

### ISSUE THREAD

**Issue by GamingRB** [PaperMC/Paper#6307]
### Expected behavior

I was making a vanilla system with a scoreboard that counts the number of times you dropped the item you chose (/scoreboard objectives add test minecraft.droppped:minecraft.lever)

### Observed/Actual behavior

Strangely, when I drop the item, it doesn't add me the point at each drop and stays at a score of 0

### Steps/models to reproduce

We create a scoreboard with the "criteria" minecraft.droppped:minecraft.lever (/scoreboard objectives add test minecraft.dropped:minecraft:lever) then we drop the item as the lever

### Plugin list

![image](https://user-images.githubusercontent.com/33877966/127786203-c2f42860-4153-4751-90e8-86ff1a590e3e.png)

### Paper version

![image](https://user-images.githubusercontent.com/33877966/127786209-322c57a6-e058-45f2-846b-e895aa9ef49c.png)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by NoahvdAa** [comment]
Can reproduce. The issue seems to be caused by [0713-Fix-PlayerDropItemEvent-using-wrong-item.patch](https://github.com/PaperMC/Paper/blob/6e7f9aafd6b7ae5a801e0265a8f9156a83b20aa5/patches/server/0713-Fix-PlayerDropItemEvent-using-wrong-item.patch), as the scoreboard objective works as intended without it.

**Comment by NoahvdAa** [comment]
There seem to be two easy ways of fixing this, dropping patch 0713 (which appears to be no longer needed) or a one line fix as a new patch, I'm not sure which one would be preferred.

The one line fix changes
```java
this.awardStat(Stats.ITEM_DROPPED.get(itemstack1.getItem()), stack.getCount());
```
to
```java
this.awardStat(Stats.ITEM_DROPPED.get(itemstack1.getItem()), itemstack1.getCount());
```

**Comment by Machine-Maker** [comment]
The second option is preferred. Then, the stat will also reflect any changes made to the itemstack count done in the PlayerDropItemEvent.
