### ISSUE TITLE
Boats - bug

### ISSUE THREAD

**Issue by Kazuro10** [PaperMC/Paper#6312]
### Expected behavior

Boat should just be placed on the ground or on the water surface.

### Observed/Actual behavior

All the boats sink in water when someone place it + you can't place boats on the ground.

### Steps/models to reproduce

Try to place boat.

### Plugin list

No plugins

### Paper version

This server is running Paper version git-Paper-151 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6e7f9aa)
You are running the latest version
Previous version: git-Paper-145 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

The bug started today after the server restarted.

**Comment by Absolutus** [comment]
This issue is also affecting my server, running on the same version.
It should be noted that it's possible to place boats on the ground when it's not a full block, such as slabs or carpet.

**Comment by 0Chameleon0** [comment]
I note the boats place OK with paper-1.17.1-149.jar, the dont place on full blocks with paper-1.17.1-150.jar, paper-1.17.1-151.jar, paper-1.17.1-152.jar or paper-1.17.1-153.jar,

**Comment by e-im** [comment]
This hasn't been entirely fixed -  right sunken is y=65.
 ![Image](https://uwu.whats-th.is/6jo7dcS.png)
Image by proximyst.

**Comment by bloodycoffin** [comment]
Players on our server report boats sinking. They can place them on a solid surface and then boat into the water - also if they click fast enough when placing it upon water it is fine. However if you wait a second before clicking the boat will sink with or without you in it.

This server is running Paper version git-Paper-165 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f261419)
You are running the latest version
Previous version: git-Paper-157 (MC: 1.17.1)

Plugins:
![image](https://user-images.githubusercontent.com/78444107/128644137-09f423b4-144b-42e0-9125-1f38a74aba19.png)

Problem started yesterday after server restart (when it automatically updates version)

**Comment by Proximyst** [comment]
We are aware of the issue, please read up a single message.

**Comment by winker2204** [comment]
I am having the same problem, the best solution then would be to use paper-1.17.1-150.jar?

**Comment by RainbowTea** [comment]
> I am having the same problem, the best solution then would be to use paper-1.17.1-150.jar?

149 is the one im using to avoid the boat bug in the meantime. 
Thank you dev team for working hard.

**Comment by Meekness0400** [comment]
![image](https://user-images.githubusercontent.com/89201169/131159466-c9ad1c70-114b-44c4-afbc-1bb6d8be5462.png)

Having this problem with latest paper version

**Comment by HexedHero** [comment]
Tuinity has a fix for this, just wait.

**Comment by e-im** [comment]
7d10cdea0358854138d0d0ada5e74c58c688dea7
