### ISSUE TITLE
Dropped items at high coordinates spawn at the wrong location

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6313]
### Expected behavior

when a block is broken, the item entity should spawn in the centre of the block.

### Observed/Actual behavior

if you are far out eg 12,000,000 blocks then it will spawn at the edge of block or even neighbouring blocks, which means if it's next to a wall it will spawn **into the wall and phase down/up**. This has caused many players with bases at high coordinates **to lose shulker boxes**.

### Steps/models to reproduce

Travel far out, in excess of 12 million blocks for example, place a shulker box down next to a wall, break the shulker, the shulker item will disappear/drop in an abnormal location.

### Plugin list

Tested without any plugins.

### Paper version

This server is running Paper version git-Paper-151 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6e7f9aa)
You are running the latest version
Previous version: git-Paper-133 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

**Video: https://imgur.com/a/l7kneso**

**Comment by e-im** [comment]
Fixed in https://github.com/PaperMC/Paper/commit/80836709e7fd3f63edb6fd8a2b85022ba90b45f7
