### ISSUE TITLE
Block hacks' ability to see player's inventory

### ISSUE THREAD

**Issue by iGabyTM** [PaperMC/Paper#6316]
### Is your feature request related to a problem?

Yes, 2 weeks ago someone reported an user for using a hack (WurstClient) for using an `.invsee` command to see their armor. I know this may not sound like a big deal, but for instance, we have custom enchantments that can be combined in certain ways and require some knowledge about that, people can just _spy_ others and 'steal' their sets.

https://github.com/Wurst-Imperium/Wurst7/blob/7f453e13e44e834b5a3c6a94efeadcd73771cefe/src/main/java/net/wurstclient/commands/InvseeCmd.java#L62

### Describe the solution you'd like.

I actually have no idea how this would be implemented.

### Describe alternatives you've considered.

I was looking for a way to block this with packets but the Open Window packet is not being sent for player inventory.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

![https://i.imgur.com/WQi2Flr.png](https://i.imgur.com/WQi2Flr.png)
You see your inventory but the armor and first slot from hotbar are of the other player's.

**Comment by ghost** [comment]
This data is obtained from entity equipment packets, just use protocollib and strip the lore from the armor pieces + this fix wouldn't be added to paper since it'd break optifine custom item texture packs.

**Comment by imDaniX** [comment]
I don't think that's Paper's scope? It's rather should be built into anticheat.

**Comment by MiniDigger** [comment]
> it'd break optifine custom item texture packs  

how exactly does optifine rely on lore, enchantments or display names of items in other players inventory?

texture packs only ever should use custom model data...

**Comment by Proximyst** [comment]
> > it'd break optifine custom item texture packs
> 
> how exactly does optifine rely on lore, enchantments or display names of items in other players inventory?
> 
> texture packs only ever should use custom model data...

I’ve no idea what kind of cursed setups these folks use, so I think it’d be best to just add a default on option for this to let them continue their lives in peace 🤷🏻‍♀️

**Comment by ghost** [comment]
> > it'd break optifine custom item texture packs
> 
> how exactly does optifine rely on lore, enchantments or display names of items in other players inventory?
> 
> texture packs only ever should use custom model data...

Optifine CIT https://youtu.be/ny5k8-looII

**Comment by MiniDigger** [comment]
> linking to a video instead of documentation.....

anyways, using display name as a identifier is flawed and wrong. custom model data exists for a reason.
