### ISSUE TITLE
Color codes in MOTD in server.properties getting corrupted

### ISSUE THREAD

**Issue by NathanWolf** [PaperMC/Paper#6321]
### Expected behavior

My MOTD stays as I write it, including any color codes

### Observed/Actual behavior

Color characters in the MOTD are getting converted with Ã appended in front.

My MOTD originally used unicode escapes for color chars, e.g.

`motd=\u00A73elMakers \u00A75Local \u00A7eServer`

After this commit:

https://github.com/PaperMC/Paper/commit/0fc6213f9cfc9e492dd5d394bbb587e026bc374b

These characters now get converted to `§` on resart:

`motd=§3elMakers §5Local §eServer`

On every restart thereafter, an additional `Ã` is prepended:

`motd=Â§3elMakers Â§5Local Â§eServer`

These `Â` will pile up continuously with each restart.

I have made sure my server.properties is UTF encoded
```
file -i servers/survival/server.properties 
servers/survival/server.properties: text/plain; charset=utf-8
```

### Steps/models to reproduce

Put an MOTD in server.properties with color codes in it and restart the server a few times.

### Plugin list

Reproduced with 0 plugins.

### Paper version

This server is running Paper version git-Paper-154 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9a74e70)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
OS?

**Comment by NathanWolf** [comment]
My servers run on Ubuntu, which is where I checked file encoding- also reproduced locally on macOS

**Comment by NathanWolf** [comment]
I got the commit I laid blame on by going back to the version before that, the issue is not present in 151

**Comment by Prof-Bloodstone** [comment]
I assume you didn't disable writing the comments? I wonder how adding the stream writer broke it. Looking into it.

**Comment by NathanWolf** [comment]
No, I didn't touch anything. Clearly some kind of encoding issue, sorry for the pain- good luck!
