### ISSUE TITLE
Exclude the dependency on junit or stop declaring json-simple

### ISSUE THREAD

**Issue by A248** [PaperMC/Paper#6324]
### Is your feature request related to a problem?

Transitive JUnit 4 dependencies are an annoying issue when using JUnit 5, because IDEs will auto-complete imports for JUnit 4. In general, it's not helpful to have JUnit 4 on the classpath for projects which use a different test framework than JUnit 4. Test engine auto-detection features in some tools, for example [maven surefire](https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html), make it quite annoying to have multiple test engines on the classpath.

json-simple declares a dependency on junit, which should be in test scope, but isn't due to a mistake on behalf of json-simple. As a result, depending on the paper-api pulls in a dependency on junit. Note that this doesn't happen when depending on upstream, because [paper declares the dependency on json-simple](https://github.com/PaperMC/Paper/blob/f25facb302f6b1dd508c3a2e103f8892e145b638/patches/api/0002-Build-system-changes.patch#L15), whereas upstream does not.

### Describe the solution you'd like.

Any of the two solutions are acceptable:
1. The API stops depending on json-simple.
2. An exclusion is made on json-simple

**Stop depending on json-simple**
json-simple has other issues besides the transitive dependency on junit. It's not actively maintained and hasn't been for a while. New code should not use json-simple. Legacy code can be made to compile against json-simple by declaring the dependency, until the code can be migrated to a different json library such as Gson or Jackson.

**Exclude the transitive dependency on junit**
A dependency exclusion would prevent junit from being resolved in plugins' classpaths. Dependency exclusions are themselves transitive in nature per [the docs](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html).

### Describe alternatives you've considered.

I prefer the first solution, though I acknowledge it will be more disruptive. For plugin source code depending on json-simple, the plugins will cease to compile until the dependency is re-declared. Nevertheless, json-simple is an aging dependency which deserves to be phased out. It's not wise to encourage it in new code.

The second solution works fine and accomplishes the stated objective.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

Output of mvn dependency:tree
```
[INFO] \- io.papermc.paper:paper-api:jar:1.17.1-R0.1-SNAPSHOT:provided
[INFO]    +- commons-lang:commons-lang:jar:2.6:provided
[INFO]    +- com.google.guava:guava:jar:21.0:provided
[INFO]    +- com.google.code.gson:gson:jar:2.8.0:provided
[INFO]    +- net.md-5:bungeecord-chat:jar:1.16-R0.4:provided
[INFO]    +- org.yaml:snakeyaml:jar:1.28:provided
[INFO]    +- com.googlecode.json-simple:json-simple:jar:1.1.1:provided
[INFO]    |  \- junit:junit:jar:4.10:provided
[INFO]    |     \- org.hamcrest:hamcrest-core:jar:1.1:provided
[INFO]    +- it.unimi.dsi:fastutil:jar:8.2.2:provided
[INFO]    +- net.kyori:adventure-api:jar:4.8.1:provided
[INFO]    |  +- net.kyori:adventure-key:jar:4.8.1:provided
[INFO]    |  +- net.kyori:examination-api:jar:1.1.0:provided
[INFO]    |  |  \- org.checkerframework:checker-qual:jar:3.10.0:provided
[INFO]    |  +- net.kyori:examination-string:jar:1.1.0:provided
[INFO]    |  \- org.jetbrains:annotations:jar:21.0.1:provided
[INFO]    +- net.kyori:adventure-text-serializer-gson:jar:4.8.1:provided
[INFO]    +- net.kyori:adventure-text-serializer-legacy:jar:4.8.1:provided
[INFO]    +- net.kyori:adventure-text-serializer-plain:jar:4.8.1:provided
[INFO]    +- org.apache.logging.log4j:log4j-api:jar:2.14.1:provided
[INFO]    +- org.ow2.asm:asm:jar:9.1:provided
[INFO]    \- org.ow2.asm:asm-commons:jar:9.1:provided
[INFO]       +- org.ow2.asm:asm-tree:jar:9.1:provided
[INFO]       \- org.ow2.asm:asm-analysis:jar:9.1:provided
```

**Comment by MiniDigger** [comment]
I think we stumbled upon json-simple before, iirc timings is the only area that use it (?), but since its api, remove it could break plugins, so currently am in favor of excluding the transitive dependency (junit has obviously no point in being in api scope)

maybe we should remove json-simple with the next major update. can we warn plugins that use json-simple without providing it themselves? I guess we can via the class loader? that would provide the smoothest migration experience.

**Comment by Toffikk** [comment]
I think the best solution would be to exclude the junit dependency , it can be done by changing this:

```kotlin
     api("com.googlecode.json-simple:json-simple:1.1.1") // Paper
```
to this:

```kotlin
     api("com.googlecode.json-simple:json-simple:1.1.1") { // Paper
         exclude(group = "junit", module = "junit")
     }
 ```

**Comment by Machine-Maker** [comment]
Fixed in https://github.com/PaperMC/Paper/commit/c0f2385c99b8783a0965acfe699b912108f91f18
