### ISSUE TITLE
\

### ISSUE THREAD

**Issue by ASDF0808** [PaperMC/Paper#6328]
### Expected behavior

Boat_on_cm scores gets increase if we ride boat and move with boat
and i used Item tag to snowball, so it will be change texture

### Observed/Actual behavior

Boat_on_cm scores get increase only i ride boat, but i'm staying
and i used Item tag to snowball, but it didn't work

### Steps/models to reproduce

i don't know

### Plugin list

AutoShutdown, commandsee, CoreProtect, DiscordSRV, M-ClearLag, M-LibraryPlus*, PluginConstructorAPI, ProtocolSupport, QualityArmory, Skript, WorldEdit

### Paper version

This server is running Paper version git-Paper-155 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6226208)
You are 1 version(s) behind
Previous version: git-Paper-134 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

asdf

**Comment by e-im** [comment]
Please fill out the issue form correctly.
