### ISSUE TITLE
Composter dont work like expected with bigger hopper

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6329]
### Expected behavior

If for example 5 items get transported by an hopper that the composter manages them correctly.

### Observed/Actual behavior

If 5 items get pushed into a composter, it go only by 1 row higher, manually with hand it is 5 times faster so I believe the composter registers only 1 and not 5 items.

### Steps/models to reproduce

Hopper connected with a composter
Change paper config setting from 1 item per push to a higher level (the higher the clearer)
Look at the composter 

### Plugin list

No plugin

### Paper version

This server is running Paper version git-Paper-156 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d239eca)
You are running the latest version
Previous version: git-Paper-92 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by NoahvdAa** [comment]
I can reproduce this with Paper and Spigot, this is probably an upstream issue.

**Comment by NoahvdAa** [comment]
Upstream issue has been created: [SPIGOT-6693](https://hub.spigotmc.org/jira/browse/SPIGOT-6693).

**Comment by NoahvdAa** [comment]
When PRing for this, I didn't notice #4838, which will fix this once merged.

**Comment by ghost** [comment]
Yet go only 1 item per tick into the composter and not like hopper in hopper 4 per tick. Is that intended?

**Comment by Machine-Maker** [comment]
Yes, the max stack size of the composter's inventory is 1, so only one will go in at a time.
