### ISSUE TITLE
Shulkers are teleporting out all the time when hit (RayWorks portal based shulker farm)

### ISSUE THREAD

**Issue by KapteniZ** [PaperMC/Paper#6339]
### Expected behavior

The shulker shoots a bullet on the snowman, but it should be catched by the lava. So, the shulker will not lose health. This shulker is used to agro other shulkers (other shulkers duplicate)

### Observed/Actual behavior

The shulker shoots a bullet at the snowman, but it does not get to the lava, instead the bullet will almost directly hit the shulker itselfs what lowers his health. After some shots, the shulker always teleports out.

### Steps/models to reproduce

Explanation: https://www.youtube.com/watch?v=jaC0YUpKlIs (Rayworks video)
Short tutorial: https://www.youtube.com/watch?v=VjysGrDT2QI 
WDL: https://www.mediafire.com/file/vuij9wq1g9695sk/Perfect+shulker+shell+farm+WDL.zip/file

![afbeelding](https://user-images.githubusercontent.com/88513344/128421659-817152f6-a235-48d6-9dd7-a1223a438ae4.png)

### Plugin list

- BetterMsgPlus
- CoreProtect
- WorldBorder

### Paper version

This server is running Paper version git-Paper-155 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6226208)
You are 2 version(s) behind
Previous version: git-Paper-152 (MC: 1.17.1)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by JeremyVyska** [comment]
This farm design relies on two shulkers, both having bullets that interact with lava.   Top shulker does not move, and lava is stationary, so no redstone timings could be affecting that one.  Center shulker is the intended split target, so the lava is double dispensed via an observer chain.  Failure rate for the lava to destroy the bullet for the top sulker is lower than center, but not zero.

I've test run, same Paper version, with a world download from the farm designer.  In vanilla MP, this worked for a 2 hour test run.  With a Paper server, this failed every 10-20 minutes.  One shulker or the other would be hit by a bullet that should have been lava destroyed.

Happy to help narrow this down, please let us know how to help.

**Comment by bcheidemann** [comment]
I tried this farm on Paper 1.17.1 and I had the same issue + the shulker does not interact with the pressure plate or string. Are you having this issue too?

**Comment by JeremyVyska** [comment]
I did, but that was fixed in Paper version 91 (#6010) on July 9th (fixed for me at least).  Double-check you're on at least that version?

**Comment by TheAshenWolf** [comment]
Tried with a different farm design ([video](https://www.youtube.com/watch?v=E1GLGWrrZv0)), in singleplayer the farm ran for about 8 hours without issue; exact copy on Paper server has real issues. Shulkers seem to teleport out more often the less health they have, effectively meaning that shulkers under half health dont seem to replicate at all, which causes the stored shulkers (first get stored first, so they are always the one that got hit by their bullet) to slowly lose all their health and die out.

The wiki does state that "The probability is reduced for shulkers with less than half their health remaining.", however, it seemed like there is no probability at all when on Paper. There were no other shulkers around, so this did not cause any change.

There also might be an issue regarding the state of the shulker, which requires its lid to be open. But I am only guessing there.

**Comment by masterdesky** [comment]
I can also confirm that this isn't working on the latest Paper build. The problem for me is that the center shulker teleports away after some minutes, which doesn't happen on Vanilla.

**Comment by JeremyVyska** [comment]
Same farm design, I tested this out for a longer run now.  If I replace the dispenser/lava combo in the Center area with a piston instead, it works flawlessly.  I've now been running the farm design for 48 hours with no failures, so it's entirely to do with shulker bullet + lava interaction, which can explain how on some systems it could affect either shulker in the farm.

**Comment by D3it7i** [comment]
This may have been fixed, and this farm works well on this version.
`git-Paper-186 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 72ce684)`

**Comment by Owen1212055** [comment]
Because multiple people seem to have claimed this as fixed above, and how generally there was a patch listed in order to resolve this I will be closing this issue.
Due to how sensitive some of these farms are if any weird behavior is still noticed please feel free to comment and this issue will be reopened.

Thanks!
