### ISSUE TITLE
ERROR]: [[STDERR] ]  & WARN]: Nag author(s): 

### ISSUE THREAD

**Issue by vdl19** [PaperMC/Paper#6344]
### Expected behavior

Hello, since a version 150 (I do not know the exact number) I have its error line from Warm when starting the server.
I am currently in Paper 1.17.1 #157

>.... [16:04:43 ERROR]: [[STDERR] ] org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!

>.... [16:04:47 WARN]: Nag author(s): '[Linus122]' of 'DropEdit2' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).

>.... [16:04:58 WARN]: Nag author(s): '[]' of 'ShulkerPacks' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).

>.... [16:04:58 INFO]: [Factions] [STDOUT] [SABER-FACTIONS] - Loaded 1 timers into list!
>.... [16:04:58 WARN]: Nag author(s): '[Olof Larsson, Brett Flannigan, drtshock, ProSavage, DroppingAnvil, Driftay]' of 'Factions' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).

### Observed/Actual behavior

Its errors or warm are in the console during the startup of the server (the server starts randomly, sometimes it freezes but since updates of Paper in relation to the map it is a little better, a little...)

### Steps/models to reproduce

I just think to install the plugins, for the error I do not know it seems that it speaks about Paper just.

### Plugin list

DropEdit2-1.1.40-SNAPSHOT
Multiverse-Core-4.3.1-SNAPSHOT
SaberFactions
ShulkerPacks-1.5.14
Vault
WorldBorder
worldguard-bukkit-7.0.6-SNAPSHOT-dist

### Paper version

git-Paper-155 (MC: 1.17.1)   (I put the 1.17.1 #157 but I see that it displays #155)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by NotMyFault** [comment]
The named plugins are using Sys out calls which paper internally forwards to proper logging. You can talk to the authors of the plugins so they can address it on their end. Once done, Paper stops complaining about it.

**Comment by vdl19** [comment]
ok thanks, I'm going to go and give them the warms.

**Comment by lynxplay** [comment]
When nagging the authors of the plugins about their incorrect usage of `System.out` or `System.err`, please provide them the PR that introduced the warning (https://github.com/PaperMC/Paper/pull/6278). While explaining why the change was made, it is also currently used as a place to discuss this change.

If the plugin authors are already using a logging framework and are still receiving the warning when running their plugin, they should check out that PR as well (for a deep dive into how to link to a proper logger) or, if anything fails, create a new issue in regards to what logger they are using and how paper still considers the logger a problematic `System.out` call 👍
