### ISSUE TITLE
EntityChangeBlockEvent should be called for stripping logs

### ISSUE THREAD

**Issue by richardwhateverr** [PaperMC/Paper#6348]
### Is your feature request related to a problem?

I wan't to make a Listener for stripping wood.

### Describe the solution you'd like.

An LogStripEvent which is activated after a log / wood gets stripped.

### Describe alternatives you've considered.

EntityChangeBlockEvent and then check To.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by NoahvdAa** [comment]
`PlayerInteractEvent` should let you detect this, check if the action is Right Click Block, if `PlayerInteractEvent#getMaterial` is an axe and if `PlayerInteractEvent#getClickedBlock#getType` is a log. 
You might also have to do some null checks.

**Comment by richardwhateverr** [comment]
> `PlayerInteractEvent` should let you detect this, check if the action is Right Click Block, if `PlayerInteractEvent#getMaterial` is an axe and if `PlayerInteractEvent#getClickedBlock#getType` is a log. 
> 
> You might also have to do some null checks.

Yeah, there is no problem to make an alternative but an Event is easier and is may a good feature.

**Comment by Machine-Maker** [comment]
The way I see it, there would be no difference between this event, and an event that only fired when an ore block was broken. It’s totally redundant.

**Comment by richardwhateverr** [comment]
> The way I see it, there would be no difference between this event, and an event that only fired when an ore block was broken. It’s totally redundant. 

Which block else change it's material if you right Click it? That's completely something else.

**Comment by lynxplay** [comment]
> Which block else change it's material if you right Click it? That's completely something else.

The copper block can be waxed by right click, for example.

**Comment by Machine-Maker** [comment]
The outcome is entirely predicable with stripping logs, and messing with copper. Simple logic can check if that is about to happen. Whereas with your other event request, there is a random element that can't be predicted with plugin logic.

**Comment by richardwhateverr** [comment]
Many events can be done through logic. But I think it's a useful Shortcuts.

**Comment by Machine-Maker** [comment]
> But I think it's a useful Shortcuts.

So if someone comes along and says, "I want a CobblestoneBlockBreakEvent because its a useful shortcut and I can't write a simple conditional check in my listener", do we add an event for that too?

**Comment by electronicboy** [comment]
The issue with API is that it needs to be maintained, these hyper specific events do no good in the long term and just create a lot of maintenance debt for something which can already be done in plugins, if there are underlying concepts in the server which might be beneficial to expose, that can be done, but, I don't think that this event adds on anything which can't already be done, at least, not with the existing events defined in the server, if there is a missing event fire, that could be discussed, but, I don't think that this is a solution which solves anything here

**Comment by Machine-Maker** [comment]
Perhaps `EntityChangeBlockEvent` should be fired here, but I'm not sure exactly where that event is meant to be fired as it seems inconsistent (at least with respect to Composters, villagers fire it, but not players)

**Comment by richardwhateverr** [comment]
Maybe add an event#getType which contains the type of the action. Is maybe kinda useful and a good solution.
