### ISSUE TITLE
CompostEvent

### ISSUE THREAD

**Issue by richardwhateverr** [PaperMC/Paper#6349]
### Is your feature request related to a problem?

I wan't an event if a player compost something.

### Describe the solution you'd like.

An PlayerCompostEvent which is triggers if you rightclick the composter. A level method would be amazing.

### Describe alternatives you've considered.

PlayerInteractEvent should may work.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by NoahvdAa** [comment]
`PlayerInteractEvent`, check if the action is right click block and if the material of the clicked block is a composter. You can then use `Block#getBlockData()` and cast it to [Levelled](https://papermc.io/javadocs/paper/1.17/org/bukkit/block/data/Levelled.html), which should let you get the level.
You might also have to do some null checks.

**Comment by Owen1212055** [comment]
![image](https://user-images.githubusercontent.com/23108066/128571581-1922b7b1-05b6-49ae-8875-b0a5d6e24754.png)
The issue here is you basically need to guess this logic to determine if it will actually compost or not. This may be better as an event, as there is a _chance_ it will add to the level or not and also has certain items that can be composted.

**Comment by richardwhateverr** [comment]
> `PlayerInteractEvent`, check if the action is right click block and if the material of the clicked block is a composter. You can then use `Block#getBlockData()` and cast it to [Levelled](https://papermc.io/javadocs/paper/1.17/org/bukkit/block/data/Levelled.html), which should let you get the level.
> 
> You might also have to do some null checks.

I've exactly done this. As the last issue it's useful and much faster than getting playerinteractevent and do some checks. Just a nice feature^^

**Comment by richardwhateverr** [comment]
> ![image](https://user-images.githubusercontent.com/23108066/128571581-1922b7b1-05b6-49ae-8875-b0a5d6e24754.png)
> 
> The issue here is you basically need to guess this logic to determine if it will actually compost or not. This may be better as an event, as there is a _chance_ it will add to the level or not and also has certain items that can be composted.

Yeah, that's a good point, but I think there is no problem to solve this.

**Comment by Machine-Maker** [comment]
Now this event is actually a good idea imo, it’s not simply a “shortcut” for something else. (See my comment on your other event suggestion). Can’t modify the chance of compost success with the interact event so an event here makes sense.

**Comment by richardwhateverr** [comment]
Bonk
