### ISSUE TITLE
Anti-Xray Minimum Block Height is Too High For 1.18 Datapack

### ISSUE THREAD

**Issue by Starmism** [PaperMC/Paper#6350]
### Expected behavior

The Paper Anti-Xray should work from the new minimum of y=-64 to whatever maximum you set in the config, such as y=320 for the new 1.18 world-gen datapack.

### Observed/Actual behavior

Instead, it only works to y=0, and does not obfuscate anything below that level.

### Steps/models to reproduce

Setup a Paper server, install the 1.18 world-gen datapack, turn on Anti-Xray, watch it stop at y=0. It is especially obvious with xray mode 2, since you can see a very sharp line of where it stops adding fake ores.

### Plugin list

None

### Paper version

[23:40:49 INFO]: Checking version, please wait...
[23:40:49 INFO]: This server is running Paper version git-Paper-161 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 23e3a0c)
You are running the latest version
Previous version: git-Paper-137 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by lynxplay** [comment]
I was able to re-create this using `git-Paper-"f261419"`. Similar to the authors statement, engine mode 2 shows very strong evidence for an issue, while I also believe engine mode 1 isn't covering sub-zero chunk sections either.

**Comment by Machine-Maker** [comment]
now, are you sure its the y-level that's causing it, not the fact that deep slate is the primary block at that level?

**Comment by lynxplay** [comment]
Could also very much be the deepslate, tho that would still require an update on the defaults.

To be honest deepslate is probably more likely, I read through the anti X ray source so often, it definitely starts at index 0 of the chunk sections.

**Comment by Machine-Maker** [comment]
I don’t know the first thing about the anti x ray system, but there is a stone preset that might need the deep slate block state added to it.

**Comment by lynxplay** [comment]
Okay, after adding deepslate to the replacement blocks, engine 2 works like a charm:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/32834385/128642495-a0ebab22-5259-4dd2-8770-72309d720b3a.png">
