### ISSUE TITLE
Player teleported back to Y level 257 when logged out above 300

### ISSUE THREAD

**Issue by Lennart99** [PaperMC/Paper#6357]
### Expected behavior

Players should be at the same location when logging in as where they logged out.

### Observed/Actual behavior

When logging out with a position above Y level 300, the player is set back to Y level 257.

### Steps/models to reproduce

1. Log in to the server running paper software (tested on build 165)
2. Go to a location above Y level 300
3. Log out
4. Log back in
5. You will now be at Y level 257

### Plugin list

None

### Paper version

> version
[17:14:01 INFO]: Checking version, please wait...
[17:14:01 INFO]: This server is running Paper version git-Paper-165 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f261419)
You are running the latest version
Previous version: git-Paper-154 (MC: 1.17.1)
>

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This works correctly on the vanilla server

**Comment by Brokkonaut** [comment]
This is the patch causing the issues, should be changed to the world max height + some value or removed. https://github.com/PaperMC/Paper/blob/master/patches/server/0107-Auto-fix-bad-Y-levels-on-player-login.patch

**Comment by Lennart99** [comment]
Any progress on this?

**Comment by lynxplay** [comment]
> Any progress on this?

Well #6358 is kind of in a stale about whether or not a limit at such a low y level is even still needed.

**Comment by Brokkonaut** [comment]
I still have the opinion that the limit should me much higher. Players can fly quite high using an elytra and I see no reason why they should be ported back to the block height limit when relogging. Logging in or moving at high values like 10000 does not cause any issues.

**Comment by Lennart99** [comment]
What was the purpose of the patch when it was added?

**Comment by Brokkonaut** [comment]
The patch comment says "Bring down to a saner Y level if super high, as this can cause the server to crash". But that patch is from 2016 even before elytras could be boosted using rockets. So at that time those high values would be impossible in vanilla minecraft without teleporting. But today they are possible and I could not reproduce any crash or server lag with extreme values.

**Comment by Lennart99** [comment]
I did some more tests in vanilla. Both the server and client seem totally fine logging back in at a high Y-level. Only thing I could find in my testing on vanilla is that I seem to be set back to 20 million when I log out above 20 million. 
It looks like the player position in the playerdata file is just clamped below 20 million. (checked using NBT editor)

Would this patch therefore even be needed at this time?

**Comment by aikar** [comment]
Whether or not Elytras get you there, the question still has to remain how the server handles logging in at such heights, if it still has the issues that was fixed then.

But with the height changes, it likely isn't an issue but just needs to be tested.

**Comment by Lennart99** [comment]
Perhaps I was not fully clear here, I did some tests on vanilla, and found no issues with logging back in at a Y level of 20 million or lower. Above 20 million I was set back to 20 million. This was all on vanilla.

I don't know how else to test this but to log out with a large Y level and see what it does when logging back in. 

If I can do anything to help, please say so.
