### ISSUE TITLE
Shulker pushes the player full block in jittery motion when opened. 

### ISSUE THREAD

**Issue by Sulack** [PaperMC/Paper#6363]
### Expected behavior

Shulker pushes player slightly when opened.

### Observed/Actual behavior

Shulker pushes the player full block in jittery motion when opened. 

### Steps/models to reproduce

1. Put shulker box on wall.
2. Press player against it
3. Open Shulker
4. Youll see janky movement. 

We have rooms that use this motion to push players. Updates broke everything. 

### Plugin list

None

### Paper version

This server is running Tuinity version git-Tuinity-"dc9d19c" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: dc9d19c on HEAD)
You are running the latest version
Previous version: git-Paper-"b32a3b1" (MC: 1.17.1)

That is on our main server. We have used all versions of paper that have the same issue. Though not sure if it is a spigot issue. 

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
"updates broke everything", if this was done in an update, we'd ask you to try to work out what version, we also don't take reports from servers which aren't running our software

**Comment by Sulack** [comment]
Sorry about using tuinity, but we had just changed. This has been an issue since the very first Paper 1.17 release. 

Im sorry I do not have the resources right now to run another server and look into it :( As long as someone is aware this is happening.

**Comment by Machine-Maker** [comment]
I don't see any behavioral differences between vanilla (tested in singleplayer) and paper 1.17.1 build 209. both push the player up 1/2 a block vertically, and 1.1 blocks horizontally. both have a slight jitter to the motion when pushing the player up. no clue if that's something that could be fixed by paper.
