### ISSUE TITLE
"Look for plugins here before reporting to Paper!" crash error does not include any plugins

### ISSUE THREAD

**Issue by panterathehacker** [PaperMC/Paper#6369]
### Stack trace

https://paste.gg/p/anonymous/c4addf34fa5e4059a84b359129dad849

### Plugin list

 Plugins (43): BedWars, BuycraftX, CasinoPlugin, ChestCommands, ChestShop, Citizens, ClearLag, CMILib, CommandNPC*, CoreProtect, Essentials, EssentialsChat, Factions, FastAsyncWorldEdit (WorldEdit), GoldenCrates, HolographicDisplays, Infiniteannouncements, Jobs, LibsDisguises, LuckPerms, MassiveCore, mcMMO, MiniaturePets, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyCommand, MySpawn, NexEngine, PaintballBattle, Parkour, PlaceholderAPI, PlotBorder, PlotSquared, ProtocolLib, SpleefX, SuperVanish, Themis, TNTRun_reloaded, Vault, Votifier, VotingPlugin, WorldGuard

### Paper version

[09.08 16:55:27] [Server] [INFO] This server is running Paper version git-Paper-167 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bfb3d42)
[09.08 16:55:27] [Server] You are running the latest version
[09.08 16:55:27] [Server] Previous versiongit-Paper-166 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This happens at random times of the day, regardless of how many people are online. Each time, it lags the server anywhere from 10-45 seconds, then everyone rubberbands when the lag stops. When it does it 3 or 4 times in the same minute, the server tends to just crash and/or everyone times out and can't reconnect unless I kill the server (not stop--kill) and restart. It has made the server essentially unplayable due to the inconsistency of its performance.

**Comment by electronicboy** [comment]
your server took too long to tick, in general, looks like the entire host/JVM was overloaded, you would generally wanna look into attaching proper monitoring tools to the server such as yourkit, etc, to watch what is going on

**Comment by panterathehacker** [comment]
> your server took too long to tick, in general, looks like the entire host/JVM was overloaded, you would generally wanna look into attaching proper monitoring tools to the server such as yourkit, etc, to watch what is going on

I am using bisec hosting, a hosting site, so I am not able to add programs like yourkit. we don't get to interface with the OS or install other programs.
