### ISSUE TITLE
Strange Startup and End

### ISSUE THREAD

**Issue by Spazzinq** [PaperMC/Paper#637]
Description of issue:
When I start and end my server, I get random errors.

Plugin list:
Unneeded because it happens without plugins

Paper build number:
CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
(Although right after it says "Error obtaining version information")

What behaviour is expected:
No errors upon startup and stop

What behaviour is observed:
Errors upon startup and stop

Link/paste of stack trace:
[(Start server)](https://hastebin.com/sukihopeya.md)
[(End server)](https://hastebin.com/ituhobotor.md)

Sorry If I am a noob I just started using Paper xD

**Comment by mikroskeem** [comment]
> (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Outdated builds aren't supported. Period.

**Comment by Spazzinq** [comment]
I downloaded this version from 
[here](https://ci.destroystokyo.com/job/PaperSpigot/443/)
...

**Comment by zachbr** [comment]
It specifically says that we don't support old versions.

We continue to provide them, but they don't get updates and they don't get support.
