### ISSUE TITLE
Furnace setCookSpeedMultiplier Is Not Working in 1.17

### ISSUE THREAD

**Issue by coco0325** [PaperMC/Paper#6376]
### Expected behavior

Furnace cook speed is adjusted.

### Observed/Actual behavior

Furnace cook speed not changed. (This is working in 1.16)

### Steps/models to reproduce

furnace.setCookSpeedMultiplier(speed)
https://papermc.io/javadocs/paper/1.13/org/bukkit/block/Furnace.html#setCookSpeedMultiplier-double-

### Plugin list

Furnace Accelerator

### Paper version

This server is running Paper version git-Paper-171 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5c65546)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by NoahvdAa** [comment]
Can reproduce with this plugin:

```java
@EventHandler
public void onPlayerInteract(PlayerInteractEvent e) {
    if (e.getAction() != Action.RIGHT_CLICK_BLOCK)
        return;
    if (e.getClickedBlock() == null || !e.getClickedBlock().getType().toString().contains("FURNACE"))
        return;
    Furnace furnace = (Furnace) e.getClickedBlock().getState();
    furnace.setCookSpeedMultiplier(10); // Everything *should* finish in one second, instead of ten.
}
```

**Comment by lynxplay** [comment]
I can also reproduce this, using similar code.
The property is correctly set, the block entity maintains the correct data. Yet it is not applied correctly.

**Comment by NoahvdAa** [comment]
Line 368 in AbstractFurnaceBlockEntity seems to be the culprit, looks like something in the event defaults back:
```java
FurnaceStartSmeltEvent event = new FurnaceStartSmeltEvent(CraftBlock.at(world, pos), source, recipe);
world.getCraftServer().getPluginManager().callEvent(event);

blockEntity.cookingTotalTime = event.getTotalCookTime(); // 368 - It works without this line.
```

**Comment by lynxplay** [comment]
Yea the line defaults to the recipes cooktime, while ignoring the multiplier.

**Comment by NoahvdAa** [comment]
> Yea the line defaults to the recipes cooktime, while ignoring the multiplier.

What would be the best fix here? Adding a new constructor that includes a multiplier (and leaving the old one broken), modifying the existing constructor to apply the multiplier, or calling `FurnaceStartSmeltEvent#setTotalCookTime` just before firing the event? I feel like just modifying the constructor to apply the multiplier (one line fix) is the best solution.

**Comment by lynxplay** [comment]
The cooking time that is exposed by the event should (at least in my opinion) be the one after the multiplier was applied.

This is not a one-line fix tho, the old constructor has to be maintained.

**Comment by NoahvdAa** [comment]
> This is not a one-line fix tho, the old constructor has to be maintained.

I was able to fix this by changing this line in the FurnaceStartSmeltEvent constructor:

```java
-        this.totalCookTime = recipe.getCookingTime();
+        this.totalCookTime = (int) Math.ceil(recipe.getCookingTime() / ((org.bukkit.block.Furnace) furnace.getState()).getCookSpeedMultiplier());
```

~This seems to be the easiest solution.~

EDIT: Just saw your PR, that's probably a better way of doing it.

**Comment by lynxplay** [comment]
I'll add your solution as an alternative so we can throw hands over it on the PR 😂
