### ISSUE TITLE
Conatiner Item Won't Apply Display Name to Inventory Title When Placed

### ISSUE THREAD

**Issue by coco0325** [PaperMC/Paper#6386]
### Expected behavior

When a container item(chest, furnace, etc.) being placed, the tile of its inventory should be the custom name of the item.

### Observed/Actual behavior

The titles of inventories stay the default name.

### Steps/models to reproduce

Rename a container item (chest, furnace, etc.), and place it down.

### Plugin list

None

### Paper version

This server is running Paper version git-Paper-171 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5c65546)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
I'm not sure that that is how that has ever worked?

**Comment by Proximyst** [comment]
> I'm not sure that that is how that has ever worked?

It has with chests at least

**Comment by electronicboy** [comment]
Oh, wait, I mis-remembered, ~~cannot reproduce~~ [wrong test server...]

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/129306334-136ffc12-b59d-4972-9e9a-aa3ab62e7c5e.png)
![image](https://user-images.githubusercontent.com/1228900/129306352-373724fe-d44d-4d25-a9fb-c50fb8f516a8.png)

Cannot reproduce
