### ISSUE TITLE
Baby bees don't grow

### ISSUE THREAD

**Issue by Nervaq** [PaperMC/Paper#6388]
### Expected behavior

Baby bees suppose to grow while inside of placed beehive.

### Observed/Actual behavior

Beehives still contains baby bees after being placed for 20mins.

### Steps/models to reproduce

1. Take Beehive with 3 Baby bees and place it with the front facing into a block so that bees can't escape the hive.
2. Wait for at least 20mins.
3. Break the block in front of the beehive so that bees can exit the hive.

### Plugin list

![](https://cdn.discordapp.com/attachments/711251759766700034/861961085220552724/unknown.png)

### Paper version

#176 build

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by rrvk** [comment]
https://minecraft.fandom.com/wiki/Bee#Breeding
```
However, bees' growth timer and breeding cooldowns are frozen while working in a hive
 ```
 
 So i think this is how is should work?

**Comment by electronicboy** [comment]
This is a spigot change

**Comment by Nervaq** [comment]
> https://minecraft.fandom.com/wiki/Bee#Breeding
> 
> ```
> However, bees' growth timer and breeding cooldowns are frozen while working in a hive
> ```
> 
> So i think this is how is should work?

It was changed during 1.15.2 i think

**Comment by Nervaq** [comment]
In Vanilla it works soo.. not everything from wiki is up to date

**Comment by Nervaq** [comment]
> This is a spigot change

Could it be reverted then? By some config in spigot folder?

**Comment by electronicboy** [comment]
yes, no

**Comment by Machine-Maker** [comment]
> This is a spigot change

Do you recall where or what spigot changed? Just a look at the code, it seems like the age should be updated when a bee is released.

**Comment by lynxplay** [comment]
~Removed prior dumb comment~

@Machine-Maker the code you might be interested in is in `BeehiveBlockEntity line 325`.
If you are interested in the commit: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/062680a826451d77e9b0822b0649809f953be3a0

**Comment by lynxplay** [comment]
Okay, I dug a bit deeper into this.
When the spigot patch was added in 1.15.1 (see comment above) vanilla would actually just take the bee age and add the ticks inside the hive to it, causing bees that were stuck in a hive to amount quite an impressive age.

This however has been changed in 1.16 as now bees actually seem to only age while still a baby. Bees that are an adult when entering the beehive actually become younger, loosing age equal to the ticks in the beehive to a minimum of the age of 0.
The spigot patch is hence not needed post 1.16 but, as it simply limits the maximum amount of ticks added to bees, prevents babies from growing up.

**Comment by Brokkonaut** [comment]
@lynxplay  As far as I can see that patch is not to limit the age of adult bees but to prevent bees from trying to exit every tick when they cannot leave the hive and so take too much cpu time.

It could help to split that integer into two values, one for the exit check (that should not be done every tick when the bee cannot exit) and one for the aging.

**Comment by lynxplay** [comment]
Oh might as well be the case. If only people would write proper commit messages when working on projects 🙃
Yeah you might be right, this would naturally also reset the next exit attempt to half the exit time but indirectly
limits the age progression.

Splitting it into two values might be a very neat idea and should not be very hard concerning that the data for it is already stored in its own class.

Should this be PRd to upstream ?

EDIT0: I opened a respective upstream issue after validating that spigot has the same problems: https://hub.spigotmc.org/jira/browse/SPIGOT-6709. Hopefully they can fix it relatively soon before paper has to implement a fix just to later revert it 👍
