### ISSUE TITLE
Bucket retains NBT Value after Dispenser Dispenses Fish

### ISSUE THREAD

**Issue by miclol** [PaperMC/Paper#6389]
### Expected behavior

I expected the bucket that is still in the dispenser to have the NBT Tags from the Tropical Fish removed.

### Observed/Actual behavior

The bucket in the dispenser retains the NBT Tags from the Tropical Fish.

### Steps/models to reproduce

1. Spawn in a Tropical Fish
2. Capture the Tropical Fish in a Water Bucket (Note that you can't just use a Tropical Fish Bucket from the Creative Inventory as you need the Fish Variant and Health NBT to be stored in the first place)
3. Put said Tropical Fish Bucket in a dispenser and activate the dispenser.
4. The bucket in the dispenser should still have the NBT tags and is not stackable with other non-bugged buckets. (You could see the NBT data better using an NBT Tooltips Mod but that's not required.)

### Plugin list

None

### Paper version

This server is running Paper version git-Paper-176 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8083670)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
Replicated on Paper, not reproducible in vanilla.

EDIT: Reproducible with spigot as well.
