### ISSUE TITLE
Config Reload

### ISSUE THREAD

**Issue by Mikgreg** [PaperMC/Paper#639]
Hi, sorry if this has been posted before.

This something that plays at my mind each time I'm trying to optimize my server, editing things in paper.yml requires that I restart my server multiple times which I can't really do at peak times when server activity is highest and I can see the actual effect of my config changes. Meaning I have to do small tweaks to the config and wait until peak to see if it actually worked rather than doing tweaks in real-time and seeing if it works in real time.

I understand that a few of the settings probably would not work with a real-time reload feature but would it be possible to get a config reload command for some of the settings?

Md_5 recently added this feature into Spigot and it'd be awesome to have it in Paper too.

https://hub.spigotmc.org/jira/browse/SPIGOT-3139

Thanks!

**Comment by zachbr** [comment]
Will be added once we pull upstream, which I am currently holding off on to ensure stability.

Hopefully later this week/end
