### ISSUE TITLE
Server stops randomly 

### ISSUE THREAD

**Issue by EdyMeleon** [PaperMC/Paper#6395]
### Stack trace

https://paste.gg/p/anonymous/2f2f3b9d420746b9a56e8c3bf6c03b05

### Plugin list

![image](https://user-images.githubusercontent.com/67687618/129451428-cf1b1331-6ecc-41b6-9bbf-9fa305e24f18.png)

### Paper version

![image](https://user-images.githubusercontent.com/67687618/129451498-b89e7903-6e1e-4958-a6fc-82b2d5a7652e.png)

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Hello I have a problem with my server. The server randomly shuts down and I get the error below. I will appreciate any help.

I  have a dedicated server with 128 ram and a AMD Ryzen 9 3900.
Also I use waterfall.

.sh script: #!/bin/bash
java -Xms12G -Xmx12G -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dpaper.playerconnection.keepalive=90  -jar server.jar nogui

**Comment by electronicboy** [comment]
As we discussed on discord, that error has literally nothing to do with your server stopping, please use the discord/forums/IRC for support.
