### ISSUE TITLE
Extremely high RAM usage upon starting server

### ISSUE THREAD

**Issue by mind-overflow** [PaperMC/Paper#6396]
### Expected behavior

RAM usage goes up as it's needed, and stays stable without killing the server. It's ok for RAM to be higher in the first few minutes, but this is a huge difference. I come from a 1.16 build where a server with 1.5GB RAM allocated would never go higher than 1GB usage (even during startup). Now, RAM usage (not allocation) goes up to 1.65GB and the server hangs. Allocating 2GB temporarily fixes the issue, because usage goes up to 1.9GB and then comes down to about 300MB after a few minutes.  

### Observed/Actual behavior

The JVM takes all the available RAM until it hangs, unless I give it more than 2GB RAM. If I do, RAM usage gets to 99% and only comes down to ~20% after a few minutes. (This is RAM usage, not allocation; allocation is always near 100% but that's okay).  
  
I'm pretty sure that this is not related to any plugin, because the timings do not report any issue in that matter (given that timings are related to CPU and not RAM, but still, before the update they were never nearly as bad) and using spark's heap dump I don't notice anything particularly bad.
- [timings 1](https://timings.aikar.co/?id=d744bef5b263499f8bc3068f0645f3ff)
- [timings 2](https://timings.aikar.co/?id=4bc3353aa1324d699fe0ea4a23bf9e76)

### Steps/models to reproduce

Create a server using paper-1.17.1-185. Start the server. Observe RAM usage.

### Plugin list

This happens on multiple servers with different configurations. Two examples are:

- AdvancedPortals, FastAsyncWorldEdit (WorldEdit), HolographicDisplays, HubCore, Multiverse-Core, PlugMan, ProtocolSupport, ProtocolSupportStuff, spark, TreysDoubleJump, VoidGenerator, WorldGuard

- CoreProtect, Essentials, EssentialsChat, FastAsyncWorldEdit (WorldEdit), FunPlugin, ImageOnMap, PlugMan, ProtocolSupport, ProtocolSupportStuff, spark, StackMob, TelegramChat*, TreeAssist, WorldGuard

### Paper version

```
This server is running Paper version git-Paper-185 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8d182e8)
You are running the latest version
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by SirYwell** [comment]
Could you do a heap dump with spark?

**Comment by mind-overflow** [comment]
@SirYwell Of course, sending it asap.
Meanwhile, I noticed that a server that previously ran fine with 4GB RAM (and used about 1-2GB), now hangs as soon as it is ready to be joined (when all plugins and worlds have been loaded) and RAM caps at 100%.

**Comment by pedrooct** [comment]
Hi, this may be a dumb question. 
What JVM do you use?

I had similar issues on my server (paper without plugins), but after playing with different JVM i got it down to 1.6GB fixed.

**Comment by ScuroK** [comment]
> Hi, this may be a dumb question.
> What JVM do you use?
> 
> I had similar issues on my server (paper without plugins), but after playing with different JVM i got it down to 1.6GB fixed.

Can you explain in detail what exactly you did to solve it?

**Comment by pedrooct** [comment]
Well i run paper inside a container on a 2 gb, single core server.
I use the following image: adoptopenjdk/openjdk16:alpine-slim.
The image was the best one for me from the variety i've tested.
Ram stays at 1.6GB with 4 players.
