### ISSUE TITLE
Invulnerable Items Still Burn and Despawn Client Side

### ISSUE THREAD

**Issue by DarkArc** [PaperMC/Paper#6399]
### Expected behavior

Invulernable items do not disappear when burned client side.

### Observed/Actual behavior

Invulernable items ignite and the despawn when in a fire block client side.

### Steps/models to reproduce

- Spawn an invulnerable item
- Ignite the block it's in

### Plugin list

Agrum-Creator, ChestShop, CommandBook (with dynamically loaded components), CraftBook, LogBlock, LogBlockQuestioner*, LuckPerms, LWC, MCMailBox, Minequery*, MobArena, Multiverse-Core, Pitfall, ProtocolLib, spark, Vault, VoidGen, WorldEdit, WorldGuard, Ziggy

### Paper version

This server is running Paper version git-Paper-186 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 72ce684)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
Ok, so testing in vanilla singleplayer, the item also disappears, but is still actually there, like if the player moves over to it, itll still be picked up. This behavior is identical to what happens on a Paper server.

Item summoned with 
```
/summon minecraft:item -239.63 64.00 198.50 {Item:{id:"minecraft:stone",Count:1b},Invulnerable:1b}
```

**Comment by Owen1212055** [comment]
Issue tracker for reference: https://bugs.mojang.com/browse/MC-53850

Basically, the client has no way of knowing if the entity is invulnerable or not. 
This affects experience orbs as well.

**Comment by ArchmageInc** [comment]
This is also true if EntityDamageEvent is cancelled for Damage cause of FIRE, FIRE_TICK, and LAVA. Regardless of setting Item.setHealth(5), Item.setVisualFire(false), or Item.setFireTicks(0). 

The item remains invisible, but is able to be picked up.

**Comment by Owen1212055** [comment]
Yea so the health value is handled on the client so sadly it won’t apply correctly when set.

**Comment by kennytv** [comment]
https://bugs.mojang.com/browse/MC-246465
