### ISSUE TITLE
EntityMoveEvent only fires for players if they move in the Y direction

### ISSUE THREAD

**Issue by tastybento** [PaperMC/Paper#6401]
### Expected behavior

I am using this minimal test plugin:

```
public class TestPlugin extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getLogger().info("Test plugin loaded");
        Bukkit.getPluginManager().registerEvents(this, this);
    }


    @EventHandler
    public void onEntityMove(EntityMoveEvent e) {
        if (e.getEntity() instanceof Player) {
            Bukkit.getLogger().info(e.getEventName());
        }
    }

    @EventHandler
    public void onPlayerMove(PlayerMoveEvent e) {
        Bukkit.getLogger().info(e.getEventName());
    }
}
```

As I move my player around, I expect to see both events fire and a log like this:

```
[19:10:01 INFO]: PlayerMoveEvent
[19:10:01 INFO]: EntityMoveEvent
[19:10:01 INFO]: PlayerMoveEvent
[19:10:02 INFO]: EntityMoveEvent
[19:10:02 INFO]: PlayerMoveEvent
[19:10:02 INFO]: EntityMoveEvent
[19:10:02 INFO]: PlayerMoveEvent
[19:10:02 INFO]: EntityMoveEvent
[19:10:02 INFO]: PlayerMoveEvent
[19:10:02 INFO]: EntityMoveEvent
[19:10:02 INFO]: PlayerMoveEvent
[19:10:02 INFO]: EntityMoveEvent
[19:10:02 INFO]: PlayerMoveEvent
[19:10:02 INFO]: EntityMoveEvent
```

### Observed/Actual behavior

What I actually see when the player runs in X or Z directions is:
```
[19:09:58 INFO]: PlayerMoveEvent
[19:09:59 INFO]: PlayerMoveEvent
[19:09:59 INFO]: PlayerMoveEvent
[19:09:59 INFO]: PlayerMoveEvent
[19:09:59 INFO]: PlayerMoveEvent
[19:09:59 INFO]: PlayerMoveEvent
[19:09:59 INFO]: PlayerMoveEvent
[19:09:59 INFO]: PlayerMoveEvent
[19:10:00 INFO]: PlayerMoveEvent
[19:10:00 INFO]: PlayerMoveEvent
[19:10:00 INFO]: PlayerMoveEvent
[19:10:00 INFO]: PlayerMoveEvent
[19:10:00 INFO]: PlayerMoveEvent
[19:10:01 INFO]: PlayerMoveEvent
[19:10:01 INFO]: PlayerMoveEvent
[19:10:01 INFO]: PlayerMoveEvent
[19:10:01 INFO]: PlayerMoveEvent
[19:10:01 INFO]: PlayerMoveEvent
[19:10:01 INFO]: PlayerMoveEvent
[19:10:01 INFO]: PlayerMoveEvent
[19:10:01 INFO]: PlayerMoveEvent
```
The only time EntityMoveEvent fires is if the player shifts in the Y direction, e.g., by dropping or jumping. Then I see both events firing for the duration of the Y movement:
```
[19:10:06 INFO]: EntityMoveEvent
[19:10:06 INFO]: PlayerMoveEvent
[19:10:06 INFO]: EntityMoveEvent
[19:10:06 INFO]: PlayerMoveEvent
[19:10:06 INFO]: EntityMoveEvent
[19:10:06 INFO]: PlayerMoveEvent
[19:10:06 INFO]: EntityMoveEvent
[19:10:06 INFO]: PlayerMoveEvent
[19:10:06 INFO]: EntityMoveEvent
[19:10:06 INFO]: PlayerMoveEvent
```
Further, the event does not fire at all if the player is flying.

### Steps/models to reproduce

[TestPlugin-1.11.1-SNAPSHOT-LOCAL.jar.zip](https://github.com/PaperMC/Paper/files/6987407/TestPlugin-1.11.1-SNAPSHOT-LOCAL.jar.zip)
```
public class TestPlugin extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getLogger().info("Test plugin loaded");
        Bukkit.getPluginManager().registerEvents(this, this);
    }


    @EventHandler
    public void onEntityMove(EntityMoveEvent e) {
        if (e.getEntity() instanceof Player) {
            Bukkit.getLogger().info(e.getEventName());
        }
    }

    @EventHandler
    public void onPlayerMove(PlayerMoveEvent e) {
        Bukkit.getLogger().info(e.getEventName());
    }
}
```

### Plugin list

Just the test plugin.
```
> plugins
[19:21:27 INFO]: Plugins (1): TestPlugin
```

### Paper version

```
> version
[19:17:00 INFO]: Checking version, please wait...
[19:17:00 INFO]: This server is running Paper version git-Paper-186 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 72ce684)
You are running the latest version
Previous version: git-Paper-165 (MC: 1.17.1)
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
Pretty sure it's supposed to intentionally be one or the other, PME is already expensive enough, EME is even more expensive, the separation is supposed to be intentional

**Comment by tastybento** [comment]
I'm happy for it to be one or the other, but even if it is just EME, it only fires if there is Y movement. The test plugin was just to show the contrast between operations. The background here is that I'm trying to track entities moving out of a portal (exiting away). As both players and mobs can use nether portals, I wanted to track both with the same code (it's a single line check). It didn't seem to be working until I put debug in and realized the event only fires if you move in the Y direction. I haven't checked how mobs fire it yet - I was just trying to get it to work for players to start.

**Comment by electronicboy** [comment]
EME should not fire for players to my understanding

**Comment by tastybento** [comment]
Aha, okay, I understand what you mean. In that case, it is firing if you move in the Y, and it shouldn't. Understood. I guess you can fix it either way! :-)

**Comment by CarinaSchoppe** [comment]
but @NoahvdAa shoudnt this still fire for Players cause a Player is an instance of an Entity and therefor there might be some implementations where someone uses this in the code (or so)
Even if its bad code it should still do fine some how.

**Comment by electronicboy** [comment]
There is no way that somebody is relying on the inconsistent behavior here

**Comment by CarinaSchoppe** [comment]
> There is no way that somebody is relying on the inconsistent behavior here

well still. I could use the EME like: instanceof Player player: give the player jumpboost or idk. and else if instanceof HostageMob than add speed or so. so you dont have to implement PME and EME as once

**Comment by electronicboy** [comment]
or you could just use the player jump event, or the move event as intended

**Comment by CarinaSchoppe** [comment]
> or you could just use the player jump event, or the move event as intended

and what if you want to handle the player and any other entity different? therefor you would have to register both events and than you got the costs of EME and PME

**Comment by electronicboy** [comment]
You have the costs of those anyways. We're not going to leave an event not intended to fire here to fire in a highly inconsistent manner when there is an event intended specifically for handling movement for these entities which fires consistently and as expected

**Comment by CarinaSchoppe** [comment]
and how do you guys want to handle this problem? through removing the player fireing this event or through "fixxing" that event fires consitently

**Comment by electronicboy** [comment]
this event is in the completely wrong place for it to ever fire consistently for players given that entity movement and player movements are processed entirely differently in general practice, the unexpected call to this has been filtered
