### ISSUE TITLE
Distributed Computing / Cluster Computing Support

### ISSUE THREAD

**Issue by hilga007** [PaperMC/Paper#6403]
### Is your feature request related to a problem?

I’d like to expand the performance of a Minecraft server running on low end hardware without having to replace the existing hardware. 

### Describe the solution you'd like.

Solution includes the distribution of the various server tasks to multiple devices in the cluster (example: nether on Device 2, end on Device 3, and overworld on Devices 1 and 4). 

ideally this can be both configurable, as well as having an auto-generated option based on the cluster.

1) Same platform support first would be great. (Have a Raspberry Pi that gets bogged down?? Add another!) 

2) Future mixed-platform support ideal. (Have an x86-64 AMD E1-2100 that’s overloaded? Add a Raspberry Pi! Still a bit slow? Throwin that PowerMac G5!) 

Hmmm the G5 may be a stretch - but the others at least make sense 

3) This is scalable 
4) This is unscalable

I can add devices, I can remove devices and the server suffers -0- downtime. 

This also works for updates with rolling reboots of the servers and duties distributed across the cluster while a device reboots. 

### Describe alternatives you've considered.

The alternative would be to buy new hardware: but why not use the hardware sitting around the house, or look into a “modular server option” by starting with 1 Pi and growing?

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by electronicboy** [comment]
This is far beyond the scope of what can be achieved here and would generally require practically re-creating the server from the ground up for this, this basically requires an entirely different manner of application architecture and far beyond the scope of what is achievable without completely destroying the existing ecosystem to produce something actually usable

**Comment by hilga007** [comment]
Understood. Makes sense. So basically escalated from “feature request” to “build new modular server software from ground up request”. 

My bad. Take care and thanks for all the hard work
