### ISSUE TITLE
PaperMC server (1.17.1) gets overloaded and crashes/restarts

### ISSUE THREAD

**Issue by Bassetz** [PaperMC/Paper#6407]
### Stack trace

[https://paste.gg/p/anonymous/de859e1063bf469993f2fdc1a208fb6e](url)

### Plugin list

EssentialsX
EssentialsSpawn
EssentialsChat
Vault
WorldEdit
WorldGuard
LuckPerms

### Paper version

Sorry can't find a way to copy/paste.
Paper version: git-Paper-187 (MC:1.17.1)
API version 1.17.1-R0.1-SNAPSHOT 
Git: 934c694
Previous version: git-Paper-185 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

So I've ran a vanilla server in 1.17 in a docker container for a while and recently decide to upgrade to a PaperMC server to get some essential plugins and better performance overall. We are often between 1and 6 players playing on it with no problems at all until now. Now one and a half week later when I personally play on the server, which is hosted locally on a different machine, the server starts spitting out "Can't keep up" messages with a 5000-9000 ms after the clock. Eventually the server crashes with either a shut down or a restart throwing everyone out with a timed out message. As said the problem seems to only occur when I play. The lagging also seems to affect me the most even though the others eventually get some kick-backs to say. I have tried playing both on the local IP and the public one with no difference. As a note, with the included log file the server did not record my disconnection, only my friend. My initial thoughts is that it could be a memory issue but I've also set a initial memory of 4 GB and a maximum of 8 GB which from my experience should be enough. Thanks in advance for any help.

The server setup:
Mac mini 2011 (I think), Quad core Intel chip, 16 GB DDR3
System: ESXi, running CentOS 7, with the PaperMC server running in a docker container with Java16. 

/Bassetz

**Comment by Proximyst** [comment]
The server is killed before it can crash or shut down properly; make sure you’re not giving it insufficient resources and that you’re not using some OOM killer or the likes.
