### ISSUE TITLE
Zombies when hit by player or snow golem will not spawn reinforcements

### ISSUE THREAD

**Issue by AaronUltima** [PaperMC/Paper#6410]
### Expected behavior

In Minecraft Java edition when player hits a zombie there is a  0–10% chance of them respawning reinforcement zombies to backup there numbers.  Link here: https://minecraft.fandom.com/wiki/Zombie#Reinforcements

### Observed/Actual behavior

In the 1.17.1 Paper server reinforcement zombies are not spawned at all when hit by player or by snow golem or iron golem entities. 

That means any Copper/downed farms designs by Gnembone  don't spawn any reinforcement zombies even at high mobcap and hard gameplay difficulty.

I did check with other players if reinforcements would spawn naturally outside any farm and the rate was 0%

### Steps/models to reproduce

Build a reinforcement chamber as shown here in the drowned/copper farm tutorial:
https://www.youtube.com/watch?v=88cW2YDALYY

We have build the farm high up in the sky and light up all the caves and spawn proofed the area so mobs can only spawn in the chambers. 

### Plugin list

Plugins (26): AntiWorldFly, BanManager, BetterRTP, CoreProtect, CratesPlus, DiamondHunter*, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, LuckPerms, LWC, MVdWPlaceholderAPI*, PlaceholderAPI, ProtocolLib, Rankup, Statz, TAB, TradeShop, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, XPFlyX*

### Paper version

17.08 10:22:38 [Server] INFO Checking version, please wait...
17.08 10:22:38 [Server] INFO This server is running Paper version git-Paper-188 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6dfd1d9)
17.08 10:22:38 [Server] INFO You are running the latest version
17.08 10:22:38 [Server] INFO Previous version: git-Paper-186 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I have set gamerule doMobSpawning on true and this has not been changed ever since starting to run the server on 1.17.1

**Comment by lynxplay** [comment]
On a plugin-less server, using difficulty `hard` (which is required) and the mentioned `doMobSpawning` gamerule set to `true` zombies produced reinforcements.

I did not setup a full farm design (which would greatly improve the spawn chances, as they are all over the place) but even a normal super flat world was able to produce a reinforcement zombie after a while.
Notably, normal zombies average a reinforcement chance of 0.05 (or 5%) and are hence really only able to summon a single reinforcement zombie.

Leader zombies were not included in my test (which have increased reinforcement spawn chances and more health).

Can you reproduce this on latest paper without your plugins and on difficulty hard ?

**Comment by AaronUltima** [comment]
I will try to replicate this situation in a test server. I will say the mobcap is set much higher in our server then the default mobcap is for hostile mobs by default.  Gnembone designed farm seems to work fine in the hermitcraft server (it uses 0 plugins only modpacks the most that don't affect vanilla gameplay).

**Comment by Apprisco** [comment]
> I will try to replicate this situation in a test server. I will say the mobcap is set much higher in our server then the default mobcap is for hostile mobs by default. Gnembone designed farm seems to work fine in the hermitcraft server (it uses 0 plugins only modpacks the most that don't affect vanilla gameplay).

That's fabric. Not paper.

**Comment by lynxplay** [comment]
> I will try to replicate this situation in a test server. I will say the mobcap is set much higher in our server then the default mobcap is for hostile mobs by default. Gnembone designed farm seems to work fine in the hermitcraft server (it uses 0 plugins only modpacks the most that don't affect vanilla gameplay).

Were you able to reproduce this on your local test server ? @AaronUltima

**Comment by Edo-Tenseii** [comment]
I too am running into this same issue on my server.

**Comment by Machine-Maker** [comment]
I cannot replicate this on paper 1.18.1. I built a huge platform in the sky, edited the source to ignore the mobSpawning rule for just trying to spawn reinforcements (so the only mobs that could spawn would be from reinforcements), setup a snow golem and zombie 7 blocks above the platform, and waited, and reinforcements did spawn. So unless someone has specific reproduction steps with no plugins or datapacks, closing this as unable to reproduce.
