### ISSUE TITLE
PlayerBucketFillEvent is called on solid blocks

### ISSUE THREAD

**Issue by OmerBenGera** [PaperMC/Paper#6411]
### Expected behavior

The PlayerBucketFillEvent should be called when filling a bucket with a fluid (water/lava).

### Observed/Actual behavior

The PlayerBucketFillEvent is called when filling a bucket with a fluid, however it's also called when clicking stairs or slabs, even if they are not water-logged. 

### Steps/models to reproduce

Take a bucket and right click on a stairs/slab block, this will cause the event to get fired even if it's not water-logged.

### Plugin list

Not relevant in this case.

### Paper version

This server is running Paper version git-Paper-188 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6dfd1d9)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

It happens on 1.16 as well as 1.17. Not sure about 1.15 or below, I don't think it matters nowadays anyways

**Comment by electronicboy** [comment]
have you tested against spigot?

**Comment by NoahvdAa** [comment]
Can reproduce with Paper and Spigot.

**Comment by electronicboy** [comment]
Yea, I had a peek at the logic, it doesn't care if the block is "full" or not, just that it's an afflicted type here

**Comment by NoahvdAa** [comment]
Is this something Paper should fix or would an upstream PR be better here?

**Comment by electronicboy** [comment]
The parent event implies that it's fired from an *interact*, am not sure that this is a bug and this is easy to filter out from a plugin perspective

**Comment by NoahvdAa** [comment]
The PlayerBucketFillEvent javadoc describes the event as:
> Called when a player fills a bucket

This, IMO implies that the event will be called whenever a bucket is being filled with a liquid.

**Comment by OmerBenGera** [comment]
> 
> 
> The PlayerBucketFillEvent javadoc describes the event as:
> 
> > Called when a player fills a bucket
> 
> This, IMO implies that the event will be called whenever a bucket is being filled with a liquid.

I must to agree with that. It should be called only when a bucket is filled with a liquid, otherwise we would use PlayerInteractEvent and check that the item in the hand of the player is a bucket.
However, due to it being a bug with Spigot as well, should I report it to Spigot instead?
I am sure Paper will fix it faster than Spigot, but if you prefer to report it to Spigot instead, lmk

**Comment by electronicboy** [comment]
Seeing spigots stance on it would "seal the deal", am not really sure that this is a bug given the parent events javadoc, I don't see why it should fire exactly, but, diverging between behavior for something which is otherwise trivial to detect, er...

**Comment by electronicboy** [comment]
Looking back at 1.12.2, this event did not fire for failures, so, this is in fact a bug

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/commit/f2471d20b4b35d932b58eccd9b87877e7b6d58aa

**Comment by NoahvdAa** [comment]
Upstream PR has been made: [CraftBukkit-917](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/917/overview)

EDIT: Looks like this was already fixed in Paper while I was fucking around with Spigot's patch system.

**Comment by NoahvdAa** [comment]
> Upstream PR has been made: [CraftBukkit-917](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/917/overview)

The upstream PR has been merged.
