### ISSUE TITLE
Spigot max-tick-time don't work on paper

### ISSUE THREAD

**Issue by Ielelele29** [PaperMC/Paper#6412]
### Expected behavior

I expected that, even with paper, the max-tick-time.tile spigot config would work correctly.

### Observed/Actual behavior

Currently even if I set the max-tick-time.tile, the hypostation is ignored and exceeds my config.

With PaperMC:
Spigot config: [spigot-config.zip](https://github.com/PaperMC/Paper/files/7000305/spigot-config.zip)
Timings:
![image](https://user-images.githubusercontent.com/76882886/129734869-d86d071e-9a7e-48df-bcdb-5e044fc30e88.png)
https://timings.aikar.co/?id=9ef4a2eca7ab4c95a65c9c3e0cdf879c#timings

With Spigot:
Configs: the same visible in Aikar timings
Timings: 
![image](https://user-images.githubusercontent.com/76882886/129735572-e665cf12-912a-4849-9bd5-ba6183bedba5.png)
https://timings.spigotmc.org/?url=ibaquxavis

### Steps/models to reproduce

Place a big amount of tile entities.
See the tickTileEntity time that exceed config.

### Plugin list

Plugins:
- ArmorStandTools
- Builders-Utilities
- CatAntiChunkBan (CUSTOM)
- CatCore (CUSTOM)
- CatCreativeCore (CUSTOM)
- CatPlayTime (CUSTOM)
- CoreProtect
- FastAsyncWorldEdit (WorldEdit)
- HeadDatabase
- ItemSerializer
- Multiverse-Core
- PermissionEx
- PlaceholderAPI
- PlotSquare
- Plugman
- TAB
- WorldGuard
Some plugins are made by me, but don't modify tile entities

### Paper version

This server is running Paper version git-Paper-188 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6dfd1d9)
You are running the latest version
Previous version: git-Paper-139 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by NoahvdAa** [comment]
Paper [disables this functionality](https://github.com/PaperMC/Paper/blob/6dfd1d9a7188e1571d30132b0e9fde87e60f0fbd/patches/server/0041-Disable-spigot-tick-limiters.patch) and [here's why](https://aikar.co/2015/10/08/spigot-tick-limiter-dont-use-max-tick-time/).
