### ISSUE TITLE
mob-spawn-range greatly affects the mob spawning rate 

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6417]
### Expected behavior

If I set mob-spawn-range to 2, mobs will become denser and the mob spawning rate will be the same as the default value

### Observed/Actual behavior

If I set mob-spawn-range to 2, mobs will become denser but the mob spawning rate will be very slow(the mob spawning rate is only **3%** of the default value. Setting it to 3, 4, or 5 will be faster, but still slow)

### Steps/models to reproduce

1. Set mob-spawn-range to 2
2. Restart the server and kill all the mobs. the mob spawning rate will slow down

### Plugin list

EssentialsX

### Paper version

git-Paper-786 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Paper.

### Other
view-distance is 10

1.12.2 to 1.16.5 have this problem. I have not tested 1.17.1

If it is not a bug, could Paper add an option similar to mob-spawn-range, but does not affect the mob spawning rate?

**Comment by radiant-ai** [comment]
Isn't this expected for such a low spawn range? Mobs cannot spawn closer than 24 blocks to player. So setting that to 2 chunks (32 blocks) greatly reduces the qualifying area available to spawn any mobs.
