### ISSUE TITLE
Re-Add TNT Chunk Loading

### ISSUE THREAD

**Issue by Matthew777k** [PaperMC/Paper#642]
**# Incompatibility (Bug)**

**### What behaviour is expected:**
The TNT should load all the chunks and explode at the bedrock wall.

**### What behaviour is observed:**
8/9 of the shots fired from the cannon the TNT did not load the chunks, only on one occasion did the TNT load the chunks and actually explode at the wall.

**### Steps/models to reproduce:**
https://youtu.be/3v_Wj-pS7dc

**### Plugin list:**

**### Actions to reproduce (if known):**
Stand on the platform of the cannon and shoot the cannon 5 or 6 times with the same amount of power each time. Once you've shot the cannon 5 - 6 times fly down to the end and look to see where the TNT explodes.

**### Paper build number:**
http://i.imgur.com/tvNC5EL.png

**Comment by zachbr** [comment]
TNT doesnt load chunks anymore. The removal of the anti-xray system in 1.9 removed several components we used to do it.

We can investigate re-adding it, but that puts this as purely a feature request, not a bug.

**Comment by imaBASKET** [comment]
+1 to this, I have a working fix for cannoning on 1.12, however tnt being unable to load chunks really hinders its use.

**Comment by imaBASKET** [comment]
Doesnt this mean phase tnt works if tnt doesnt load chunks?

**Comment by zachbr** [comment]
Yes, same as upstream.
Unless that section of code has been changed since I last looked at it (which was around 1.7 anyway).
Paper will do whatever Spigot does when it comes to tnt phase.

**Comment by Laarryy** [comment]
This issue is beyond stale - upstream's methods are our own regarding this topic and this issue will be closed. If there is something further that needs doing regarding TNT and chunks, please open a new issue. Though note, a new issue asking for the same thing with the same information and reasoning won't be considered.
