### ISSUE TITLE
Bug when the player dies when the server starts to close

### ISSUE THREAD

**Issue by ElectronicsBoy2** [PaperMC/Paper#6420]
### Expected behavior

nothing to happen and player to die

### Observed/Actual behavior

the player will be glitched.
he will not be able to respawn
and the only way out is to delete his player data

### Steps/models to reproduce

hi
if you have a player about to die and the server closes at that moment, the player will be glitched.
he will not be able to respawn
and the only way out is to delete his player data

### Plugin list

none

### Paper version

1.17.1

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Brokkonaut** [comment]
Can you upload the player data of a bugged player? That might help to find the issue.

**Comment by NoahvdAa** [comment]
Can't reproduce, I added `Bukkit.shutdown()` to the start (and when that didn't work to the end too) `ServerPlayer#die` and couldn't get into the "glitched state".

**Comment by Chew** [comment]
Please provide the entire Paper version.

Hint: Type `/version` in-game and click to copy!

**Comment by e-im** [comment]
I also can not reproduce this, and it makes no sense without a log or such. Closed due to lack of response. If you have more information feel free to leave a comment and I will reopen.

**Comment by ElectroBoy404NotFound** [comment]
Hello! Actually, that was my old account and i lost it to time. This is actually a fake issue. I was just messing around after getting banned from the discord server
