### ISSUE TITLE
Server doesn't stop properly if EULA is false.

### ISSUE THREAD

**Issue by NoahvdAa** [PaperMC/Paper#6422]
### Expected behavior

When the EULA isn't accepted, the server should print a message about it and shut down.

### Observed/Actual behavior

When the EULA isn't accepted, the server prints a message and stays running.

### Steps/models to reproduce

- Download paper 1.17.1, build 195. 
- Start the server without accepting the EULA.

### Plugin list

None

### Paper version

[15:43:24 INFO]: Checking version, please wait...
[15:43:25 INFO]: This server is running Paper version git-Paper-195 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: fa184f7)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Java Version:
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

JStack: https://paste.gg/p/anonymous/3d49e1fbeefd420a91cd2be122e004e2

**Comment by NoahvdAa** [comment]
Seems to be caused by [this](https://github.com/PaperMC/Paper/commit/4d9b14efa498949f3611fe6bd8fa3bf0b19c2b2e). Can reproduce with build 173, but not with 172.

**Comment by Proximyst** [comment]
Issue is likely the Log4j async appender thread being non-daemon.

**Comment by lynxplay** [comment]
Something that appears to have been fixed in [this](https://github.com/apache/logging-log4j2/commit/e24e2e8901ccfff1b7e6c5b8d40b707bfc91c843#diff-4024f348bc64d36c3d1d1a7ff91e60af17a1369fe21d012ea14b71892af311d8) commit but simply isn't part of the 2.14.1 release of log4j-core used by paper rn.

**Comment by NoahvdAa** [comment]
Log4J Core 2.14.1 seems to be the latest version, do we have to wait for a new release here?

**Comment by lynxplay** [comment]
Well I don't think we will need to wait for a new release to fix this issue as there are workarounds (e.g. what the server already does after the gameloop ends: System#exit) tho obviously it should be a rather high priority to then upgrade to the latest log4j-core once 2.14.2 is released.

EDIT-0: There are probably even better workarounds. I don't know off the top of my head if LogManager#shutdown could also stop the logger. But there is definitely something and if it is falling back to a System#exit call.

**Comment by NoahvdAa** [comment]
> I don't know off the top of my head if LogManager#shutdown could also stop the logger

I tried that but that didn't work.

---

Would I have to put a workaround in [the same patch that caused this issue](https://github.com/PaperMC/Paper/blob/4d9b14efa498949f3611fe6bd8fa3bf0b19c2b2e/patches/server/0224-Use-AsyncAppender-to-keep-logging-IO-off-main-thread.patch)?

**Comment by lynxplay** [comment]
That is probably up to the maintainers. I would probably put it in the same patch as that change is going to be reverted down the line. Introducing a new patch for something we know will be dropped seems pretty meh.

**Comment by NoahvdAa** [comment]
Instantly exiting like this:
```java
Main.LOGGER.info("You need to agree to the EULA in order to run the server. Go to eula.txt for more info.");
System.exit(0); // Paper - Workaround until log4j is updated.
return;
```
doesn't seem to log the EULA message (is the process getting shut down too quickly for the log to flush?)

EDIT: Seems to flush properly when adding `LogManager.shutdown();` before `System.exit(0);`.

**Comment by lynxplay** [comment]
Yeah the user is responsible for flushing the async appender. The LogManager call can do that.

EDIT-0: I did not see your edit XD thanks GitHub 😅
