### ISSUE TITLE
Items merging does not use configured despawn rate to check if item is mergeable

### ISSUE THREAD

**Issue by tomcraft** [PaperMC/Paper#6427]
### Expected behavior

Item merging should use the user configured despawn rate for checking if the entity is mergeable.

### Observed/Actual behavior

Item merging check use the default minecraft value (6000) instead of using `ItemEntity#getDespawnRate()`, so if the despawn rate is configured higher, lets say 12000, items with age > 6000 will not merge anymore.

### Steps/models to reproduce

configure a despawn rate for items higher than 6000 in paper.yml or spigot.yml

### Plugin list

none

### Paper version

thomas@MacBook-Pro-de-Thomas Paper-1-17 % git log -n1
commit 59d449d8807d0fe30ad4cf8536ca1947c3b603ca (HEAD -> master, origin/master, origin/HEAD)
Author: Jason <11360596+jpenilla@users.noreply.github.com>
Date:   Wed Aug 18 13:47:29 2021 -0500

    Set AsyncAppender dispatch thread to be a daemon thread (#6424)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

`ItemEntity#isMergable()` line 265 uses raw 6000 value instead of using the `ItemEntity#getDespawnRate()` method to get the delay

**Comment by NoahvdAa** [comment]
Can reproduce on the latest paper build.

**Comment by lynxplay** [comment]
Can also reproduce on paper 59d449d88.

**Comment by electronicboy** [comment]
it's a line which wasn't changed in spigot and likely has been that way since that line was added to the came or something, don't really need confirmation on this
