### ISSUE TITLE
Issue with De-Opping offline players

### ISSUE THREAD

**Issue by IceString3** [PaperMC/Paper#643]
**The following are 'hard suggestions': if you have the information
available to you, you really should put it in the report. Choose one of
the following templates from below that best fits the issue you wish to
report.**

# Incompatibility (Bug)

### What behaviour is expected:
/deop should deop the player no matter if he is offline or online.
### What behaviour is observed:
The player isn't actually deopped. When deopping a player while he is offline, he is removed from ops.json and the deop message shows. However, when he re-joins, he gets op status and appears again in ops.json
### Steps/models to reproduce:
1. Op yourself
2. Log off
3. Deop yourself from console
4. Rejoin the server
5. You will appear in ops.json and you can still execute op-only commands

### Plugin list:
LuckPerms, antiraildupe, Skript, OpenInv, ClearLag, SkQuery, PandaWire, ConsoleSpamFix, ProtocolLib, Skellett, AAC, SkinsRestorer, skRayFall, FastAsyncWorldEdit, Reloader, MundoSK, LagMonitor, Vault, MaroHub, BungeeTabListPlus, LightAPI, WorldEdit, LargeSk, CityWorld, Essentials, Multiverse-Core, WorldGuard, SkStuff, LockettePro, Umbaska, EssentialsSpawn, GriefPrevention, HawkEye, AuthMe, TuSKe, SharpSK

### Paper build number:
This server is running Paper version git-Paper-1076 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by mikroskeem** [comment]
Can you reproduce this issue without plugins?

**Comment by Phoenix616** [comment]
Can't reproduce it. Are you sure that you don't have an auto-op feature of a plugin enabled? E.g. LuckPerms has such a feature.

**Comment by IceString3** [comment]
Thanks for the suggestions. I tried without plugins and I couldn't reproduce the issue as well. However, I tried adding the plugins one by one until I found the culprit. It was AuthMeReloaded (5.2 Release). I switched to the latest dev version of the plugin and the problem is gone.
