### ISSUE TITLE
Chunk loading ERROR

### ISSUE THREAD

**Issue by rgoth-main** [PaperMC/Paper#6431]
### Expected behavior

It shouldn't send any console errors

### Observed/Actual behavior

Keep giving a console error caused by chunks

### Steps/models to reproduce

- Open server
- Start walk
- Error appears

### Plugin list

![image](https://user-images.githubusercontent.com/68816751/129987582-caa178fa-bc7d-4489-b70d-83406062bd70.png)

### Paper version

![image](https://user-images.githubusercontent.com/68816751/129987717-c74a9b47-1f78-4903-8355-54cb14821695.png)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

The error is this:
https://pastebin.com/t3PDg2PJ

**Comment by electronicboy** [comment]
Well documented vanilla issue, forceUpgrade or ignore it
