### ISSUE TITLE
Merge Config Files

### ISSUE THREAD

**Issue by richardwhateverr** [PaperMC/Paper#6432]
### Is your feature request related to a problem?

There are many config files:
bukkit.yml, paper.yml, spigot.yml….

### Describe the solution you'd like.

Just merge then into one.

### Describe alternatives you've considered.

Just editing.

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Camotoy** [comment]
Pretty sure this is a duplicate of #5344.

**Comment by NotMyFault** [comment]
If we're at it, maybe merge the world folders too.

**Comment by richardwhateverr** [comment]
> Pretty sure this is a duplicate of #5344.

Yes it is, searched for merge, but not for migrating. My bad.
