### ISSUE TITLE
Completely broken portal linking.

### ISSUE THREAD

**Issue by Apprisco** [PaperMC/Paper#6434]
### Expected behavior

You fly through a portal, and you arrive in the nether.
You fly back through the portal, and you are sent to the origin portal.

### Observed/Actual behavior

New portals are created, when there is clearly a linked portal between the two dimensions.
https://streamable.com/0rresc

Additionally, there are issues where a new portal will override existing portal links, and more.
For example, you have an existing nether portal,
but a new portal above the existing portal will override the link.
This is not vanilla or old paper behavior.

### Steps/models to reproduce

https://streamable.com/0rresc

### Plugin list

None.

### Paper version

This server is running Purpur version git-Purpur-1333 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d783ad7 on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-1332 (MC: 1.17.1)

Was told that this is an upstream issue by Purpur devs, from Paper.
Confirmed on latest paper by them.

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
You're not running paper, many of these issues are also a mixture of misconfiguration and oddities which can be seen even in vanilla, there is probably also an open issue for this already

**Comment by Apprisco** [comment]
> You're not running paper, many of these issues are also a mixture of misconfiguration and oddities which can be seen even in vanilla, there is probably also an open issue for this already

Sigh, it was confirmed in latest paper. Just because I tested it on purpur first isn't a valid reason to close it.
+ these are vanilla configs.

**Comment by Apprisco** [comment]
Additionally, there are no open issues for this.

**Comment by electronicboy** [comment]
We don't take bug reports from forks

**Comment by Apprisco** [comment]
> We don't take bug reports from forks

As if the fork is a problem, I clearly mentioned it was an issue on paper as well as purpur.

**Comment by aurorasmiles** [comment]
We do not support forks. If this issue persists on Paper open a bug report when using Paper.

**Comment by electronicboy** [comment]
Then report it while running paper, we do not take bug reports from forks out of principle, especially under "he said she said" aspects, reproduce on paper, provide all relevant information, e.g. including configuration, we're not changing our stance on accepting reports from people running forks
