### ISSUE TITLE
patched_1.17.1.jar Error

### ISSUE THREAD

**Issue by xKsyStudio** [PaperMC/Paper#6435]
### Expected behavior

Fix it

### Observed/Actual behavior

[01:01:17 ERROR]: [[STDERR] ] org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!

### Steps/models to reproduce

Just start the server

### Plugin list

It also happens without any plugins

### Paper version

paper-1.17.1-196

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
You have legacy plugins, as the message states; either get away from those plugins or basically, you're gonna have to live with it
(see the warnings for plugins without an api-version set, or, run /plugins and see those with *'s)

**Comment by xKsyStudio** [comment]
patched_1.17.1.jar is downloaded when paperspigot starts
It is not the plugin I installed

**Comment by Chew** [comment]
You should not be running that, it's to remain in the cache folder.

Additionally, we are called Paper, not PaperSpigot.

**Comment by xKsyStudio** [comment]
I just run paper

**Comment by Chew** [comment]
Regardless, the error you provided has been responded to. If you have further questions please ask on [Discord](https://discord.gg/papermc).

**Comment by electronicboy** [comment]
This error is down to the plugins you have installed, once again, see your logs and it will tell you what plugins where loaded which caused that data to be initialised

**Comment by xKsyStudio** [comment]
Repeat it again. I didn’t install any plugins.

**Comment by Proximyst** [comment]
It literally can’t happen without plugins.

**Comment by electronicboy** [comment]
Please use discord and provide the full logs, etc, enable debug in server.properties for more info
