### ISSUE TITLE
[Feature request] Bring back maven building 

### ISSUE THREAD

**Issue by AffectedArc07** [PaperMC/Paper#6442]
### Is your feature request related to a problem?

I have used spigot for the longest time as a custom server to add my own patches to for custom plugin things (such as public fields on packets to make life easier).

I have wanted to switch to paper for a while, especially due to the chunkloading optimisations here, however I cannot as the build here revolves around gradle, instead of maven, meaning I cannot publish the jars to a private maven repo for the rest of my devs to use. Paper using gradle means that this is not a viable option for me, which is a shame.

### Describe the solution you'd like.

I would like for the build system to have maven as an alternative. I am not saying kill off gradle completely if thats your primary method, but I would like maven as a usable alternative, without having to manually patch in the support myself.

### Describe alternatives you've considered.

- Patching in maven support manually

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

I am aware that this issue is a super minority thing and I am open to suggestions of how to fix this on my side as opposed to having to cause major modifications here. I will gladly accept a solution if theres something simple like a gradle plugin(?) that supports pushing artefacts to a maven repo. 

This is also my first time making a request/question/issue here, so please be constructive in pointing out if/where I have gone wrong. Thanks!

**Comment by e-im** [comment]
You can do this with gradle, please see [their article on the subject](https://docs.gradle.org/current/userguide/publishing_maven.html). This is already done by paper. If you have any questions regarding this or run into trouble implementing it, feel free to come by [our discord](https://discord.gg/papermc) or irc (#paper on espernet)

**Comment by AffectedArc07** [comment]
> You can do this with gradle, please see [their article on the subject](https://docs.gradle.org/current/userguide/publishing_maven.html). This is already done by paper.

Much appreciated. Will look into this.
