### ISSUE TITLE
EnderSignal setDropItem is Inverted

### ISSUE THREAD

**Issue by DarkArc** [PaperMC/Paper#6453]
### Expected behavior

`setDropItem` states that a value of `true` should drop the signal, and `false` should destroy the signal.

### Observed/Actual behavior

The value of `setDropItem` is ignored, and the signal seemingly does whatever it wants.

### Steps/models to reproduce

```
        EnderSignal signal = spawnLoc.getWorld().spawn(spawnLoc, EnderSignal.class);
        signal.setDropItem(false);
```

### Plugin list

Agrum-Creator, ChestShop, CommandBook, CraftBook, LogBlock, LogBlockQuestioner*, LuckPerms, LWC, MCMailBox, Minequery*, MobArena, Multiverse-Core, Pitfall, ProtocolLib, spark, Vault, VoidGen, WorldEdit, WorldGuard, Ziggy

### Paper version

This server is running Paper version git-Paper-186 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 72ce684)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Not using latest version; will retest later I don't see any reason doing so would fix this though.

**Comment by tahmid-23** [comment]
aren't your expected and observed behaviors the same thing

**Comment by DarkArc** [comment]
Sorry, yes I made a mistake in stating the actual behavior. I've since changed the report anyways.

I realized that my case of `setDropItem(true)` resulting in the signal being destroyed was also just wrong/a one off where it did what I wanted. The signal doesn't seem to care and just kind of does what it wants.

**Comment by Machine-Maker** [comment]
You aren't setting the target location **after** setting it to *not* drop items right?  
Like calling EnderSignal#setTargetLocation(Location) and then EnderSignal#setDropItem(false)

**Comment by Machine-Maker** [comment]
I can't reproduce this, I spawned in about 50 of them with
```java
        EnderSignal signal = player.getWorld().spawn(player.getLocation(), EnderSignal.class);
        signal.setDropItem(true);
```
and using breakpoints checked if any didn't drop their items. All of them dropped the item.

**Comment by DarkArc** [comment]
> You aren't setting the target location **after** setting it to *not* drop items right?  
> Like calling EnderSignal#setTargetLocation(Location) and then EnderSignal#setDropItem(false)

I am... Is there a quirk in the JavaDoc about that?

The whole API on EnderSignals has been surprising to me to say the least...

**Comment by lynxplay** [comment]
"When setting a new target location, the getDropItem() resets to a random value and the despawn timer gets set back to 0." 
is part of the [javadoc](https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/EnderSignal.html#setTargetLocation(org.bukkit.Location)).

**Comment by DarkArc** [comment]
That's really dumb IMO, but closing anyways.

**Comment by Machine-Maker** [comment]
> That's really dumb IMO, but closing anyways.

Yeah, the javadoc does mention that. It’s because it uses vanillas method to set the new target position and that includes resetting the drop item bool.
