### ISSUE TITLE
Wither skeleton farm

### ISSUE THREAD

**Issue by Krinios** [PaperMC/Paper#6455]
### Expected behavior

I dont know why my wither skeleton farm is not working I'm not sure if the wither skeleton is attracted to the iron golem I dont know what the problem is cause I'm like 200+ blocks high in the nether waiting for my wither skeleton to come through the nether portal but it just doesn't work I made another replica of the farm in my singleplayer world same seeed same location everything but it still doesn't work I already checked the 128 radius sphere using minihud and everything is fine idk how it is not working for some reason

### Observed/Actual behavior

I dont know

### Steps/models to reproduce

I dont know

### Plugin list

SingleplayerSleep, skinrestorer and worldedit

### Paper version

1.17.1 #165

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

nothing else

**Comment by e-im** [comment]
Please fill out the issue template. This is far too vague to do anything with.
