### ISSUE TITLE
Observers detect saplings advancing their growth stage once and then they stop

### ISSUE THREAD

**Issue by ML98** [PaperMC/Paper#6458]
### Expected behavior

Hi! Observers should be able to detect when a sapling advances its growth stage, even when surrounded by opaque blocks with a redstone lamp on top to give enough light for the sapling to advance the next stage.
It should fire every 8 minutes or so on average, but it can be manually activated using bonemeal.

If my explanation of the expected behavior sounds confusing, I'll attach a link to a [video](https://www.youtube.com/watch?v=OrvPW1rI4Js) made by ilmango that showcases thew contraption I'm mentioning.
![The contraption I'm mentioning](https://user-images.githubusercontent.com/27917575/130329310-054fc457-031e-47e1-a912-c2299b3d98e4.png)

### Observed/Actual behavior

On the server I play on, both in creative and survival (I attach a screen with the paper version), the observer only detects the growth stage advancement, but then it stops receiving block updates from the sapling, even if I bonemeal it.

### Steps/models to reproduce

Just build the contraption I attached in the expected behavior section of this issue and spam bonemeal on the sapling. It should work in vanilla.

### Plugin list

![plugin list](https://user-images.githubusercontent.com/27917575/130330107-b608dbfb-20cb-4ab4-aaab-e7a960ab816e.png)

### Paper version

![paper version](https://user-images.githubusercontent.com/27917575/130329403-22726740-3efb-4517-b36d-0580a355903a.png)

DISCLAIMER: The server I'm playing on doesn't run the latest version of Paper, but going through all the 102 changelogs I haven't seen any mention of this issue, so it may still be affecting newer versions. Also I aked on the Paper Discord and they suggested to write this issue since it sounds like a bug. This is to inform that I checked the "I am running the latest version of Paper available from https://papermc.io/downloads. *" box, even though this isn't the latest version. 

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
Thank you for your detailed report!

**Comment by lynxplay** [comment]
Wow xD 12 seconds too late

**Comment by lynxplay** [comment]
First scan over the source code, the linked video was *somewhat* on the right path.

The server sets the sappling block to `AIR` at the start of the tree generation to allow for the tree to actually grow on the block the sappling used to be. If the tree growth fails, it is replaced with its old state.
This triggers the observer in vanilla.

Upstream however implemented `captureTreeGeneration` which prevents potential tree generation to allow for events etc.
This value however was introduced too far up the stack is and set to true prior to the sappling being replaced by `AIR` / put back and hence catches those modifications which prevents the observer from observing the.
