### ISSUE TITLE
Incompatibility with every other plugin using bStats

### ISSUE THREAD

**Issue by Bastian** [PaperMC/Paper#646]
Hey,
first of all I'm glad to see you decided to switch from McStats to bStats. :-)
However, you made some changes to the original Metrics class which causes other plugins using bStats to not be displayed on the website, if they run on a Paper server.
While McStats takes a "one request per plugin" approach, bStats is only sending "one request per server", which means, that all plugins have to "communicate" together (one plugin collects all the data from the other plugins and sends it to bStats). This is done using Bukkit's ServicesManager, which you unfortunately removed in your modified Metrics class.
What's now happening is, that there are always two requests coming from servers using PaperSpigot (one from your implementation and one from all the other plugins which are using bStats), but bStats' backend only allows one request per server, so the second one get's throttled (= not displayed on the website).

Fixing this issue should be fairly easy: Just readd the relevant code parts you removed:
- https://github.com/BtoBastian/bStats-Metrics/blob/24637b6eb5f549ba9185656eef6029303cc72f5a/bstats-bukkit/src/main/java/org/bstats/Metrics.java#L104-L120
- https://github.com/BtoBastian/bStats-Metrics/blob/24637b6eb5f549ba9185656eef6029303cc72f5a/bstats-bukkit/src/main/java/org/bstats/Metrics.java#L232-L246

These two parts are used to "communicate" with the other plugins and are very important and should not be modified/removed.

**Comment by zachbr** [comment]
Those parts were removed because as a server implementation, we are not a plugin and are not capable of properly registering to the services API. I considered faking it or hacking it up anyway, but decided against it because it just creates a mess.

I'm open to alternate solutions, but integrating the services API is not one of them.

**Comment by Bastian** [comment]
Hmm, I see what's the problem with the Services Manager and I also don't know a good/clean solution.

Maybe an extra category like "Server Implementations" would be a good idea instead of treating it like a Bukkit plugin? What do you think?

**Comment by mikroskeem** [comment]
Making an extra category is way better option imo. :+1:

**Comment by electronicboy** [comment]
Depends on what you mean by "treating it like", noting that as a server we cannot hook into the services API and so we'd still be stuck away from other bstat instances from being seen in the services manager, how would this change the hitting of the limit?

**Comment by Bastian** [comment]
Server implementations would send their stats individually. There would be no need to communicate with the other plugins, as the connection would be throttled per endpoint.
This would be easy to change on my end and would be a clean solution for the problem in my opinion.

**Comment by zachbr** [comment]
That solution sounds fine to me. Let us know if we need to change anything on our end.

**Comment by Bastian** [comment]
Hey,
I just finished creating the new category + a Metrics class which does not cause any conflicts with other bStats plugins. The new class can be found here: https://gist.github.com/Bastian/d74ec19fd8e31a08581be3d49ffdc696
My aim was to make the new category (and Metrics class) as flexible as possible (for the future, where I plan to support pocket edition etc. too), that's why some charts are not included by default (e.g. Java Version). They have to be added manually using custom charts, which I have already done for you (take a look at your bStats account).
This is my recommended way to load the Metrics class:
```java
private void startMetrics() {
    // Get the config file
    File configFile = new File(new File((File) MinecraftServer.getServer().options.valueOf("plugins"), "bStats"), "config.yml");
    YamlConfiguration config = YamlConfiguration.loadConfiguration(configFile);

    // Check if the config file exists
    if (!config.isSet("serverUuid")) {

        // Add default values
        config.addDefault("enabled", true);
        // Every server gets it's unique random id.
        config.addDefault("serverUuid", UUID.randomUUID().toString());
        // Should failed request be logged?
        config.addDefault("logFailedRequests", false);

        // Inform the server owners about bStats
        config.options().header(
                "bStats collects some data for plugin authors like how many servers are using their plugins.\n" +
                "To honor their work, you should not disable it.\n" +
                "This has nearly no effect on the server performance!\n" +
                "Check out https://bStats.org/ to learn more :)"
        ).copyDefaults(true);
        try {
            config.save(configFile);
        } catch (IOException ignored) { }
    }

    // Load the data
    String serverUUID = config.getString("serverUuid");
    boolean logFailedRequests = config.getBoolean("logFailedRequests", false);
    // Only start Metrics, if it's enabled in the config
    if (config.getBoolean("enabled", true)) {
        Metrics metrics = new Metrics("Paper", serverUUID, logFailedRequests, Bukkit.getLogger());

        metrics.addCustomChart(new Metrics.SimplePie("minecraft_version", () -> {
            String minecraftVersion = Bukkit.getVersion();
            minecraftVersion = minecraftVersion.substring(minecraftVersion.indexOf("MC: ") + 4, minecraftVersion.length() - 1);
            return minecraftVersion;
        }));

        metrics.addCustomChart(new Metrics.SingleLineChart("players", () -> Bukkit.getOnlinePlayers().size()));
        metrics.addCustomChart(new Metrics.SimplePie("online_mode", () -> Bukkit.getOnlineMode() ? "online" : "offline"));
        // I don't know how to access the version of your implementation? 
        metrics.addCustomChart(new Metrics.SimplePie("paper_version", () -> "git-Paper-1337"));

        metrics.addCustomChart(new Metrics.DrilldownPie("java_version", () -> {
            Map<String, Map<String, Integer>> map = new HashMap<>();
            String javaVersion = System.getProperty("java.version");
            Map<String, Integer> entry = new HashMap<>();
            entry.put(javaVersion, 1);
            if (javaVersion.startsWith("1.7")) {
                map.put("Java 1.7", entry);
            } else if (javaVersion.startsWith("1.8")) {
                map.put("Java 1.8", entry);
            } else if (javaVersion.startsWith("1.9")) {
                map.put("Java 1.9", entry);
            } else {
                map.put("Other", entry);
            }
            return map;
        }));

    }
}
```
It uses the same config file the other bStats plugins are using as well, because this is also no longer part of the Metrics class.

The stats can be found under the new url https://bstats.org/plugin/server-implementation/Paper
I hope you are fine with this solution :)

**Comment by zachbr** [comment]
Sorry for the delay, I will try to get to this sometime this weekend.

**Comment by zachbr** [comment]
I've switched us over to your new implementation as of the latest builds. Let us know if there's anything else.

Thanks for your help.
