### ISSUE TITLE
Set per-player-mob-spawns to true by default

### ISSUE THREAD

**Issue by EterNityCH** [PaperMC/Paper#6471]
### Is your feature request related to a problem?

With my time spent in the paper-help Discord, I have noticed that a number of people experiencing "no mob" issue due to their lack of understanding on how mob-spawning works in multiplayer server. 

By making per-player-mob-spawns true by default, it should fix a lot of "no mob is spawning" issue people are bringing to Discord help channel while have minimum impacts on majority of the server.

### Describe the solution you'd like.

I'd like to propose that the config option **per-player-mob-spawns to be set to true by default.**

Similar to the argument made for [allow-player-cramming-damage](https://github.com/PaperMC/Paper/pull/5903) to be set false. Despite this behavior will be "no longer vanilla," it is more logical and beneficial for vest majority of the server owners especially those who are new to hosting one themselves.

As far as I know, the only real thing this action will break is "the mob switch" which is already a rather rare mechanic being utilized among the survival servers. 

### Describe alternatives you've considered.

This section is not applicable to my request.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by e-im** [comment]
Mob switches are already effectively broken by default due to https://github.com/PaperMC/Paper/blob/98fa13609982b3ee19928efed96f4d23735ea100/patches/server/0338-Only-count-Natural-Spawned-mobs-towards-natural-spaw.patch, assuming it is working correctly (https://github.com/PaperMC/Paper/issues/6214) and there aren't other major caveats I don't see, this would be a good default improvement.

**Comment by e-im** [comment]
https://github.com/PaperMC/Paper/commit/7d10cdea0358854138d0d0ada5e74c58c688dea7#diff-7b8e57cce5ded927385266eedc836f4f6b9fd809684325e9f48a1e641f3704edR38-R40
