### ISSUE TITLE
`gradlew tasks` does not show tasks, it errors instead

### ISSUE THREAD

**Issue by AffectedArc07** [PaperMC/Paper#6475]
### Expected behavior

A list of tasks that can be run.

### Observed/Actual behavior

An error
![image](https://user-images.githubusercontent.com/25063394/130484636-0c8b492c-980f-48a3-9d84-0e3aea1f6cce.png)

Occurs in both regular cmd and "bash" (Using Git Bash)
![image](https://user-images.githubusercontent.com/25063394/130484722-5d2bdece-b83f-4a49-9fff-aa99688c21fd.png)

### Steps/models to reproduce

Run `gradlew tasks`

### Plugin list

N/A, on repo

### Paper version

Commit hash
```
commit 98fa13609982b3ee19928efed96f4d23735ea100 (HEAD -> master, origin/master, origin/HEAD)
Author: Jake Potrebic <15055071+Machine-Maker@users.noreply.github.com>
Date:   Sun Aug 22 10:22:57 2021 -0700

    Fix CB lib relocation (#6454)
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

If there is a different policy for reporting issues that occur with repo tooling itself, please let me know.

**Comment by e-im** [comment]
you currently must `applyPatches` prior to listing tasks.

**Comment by AffectedArc07** [comment]
> you currently must `applyPatches` prior to listing tasks.

Should I PR a documentation update then to specify this?

**Comment by jpenilla** [comment]
No, this is a bug. Please open an issue at the paperweight repo.

**Comment by AffectedArc07** [comment]
> No, this is a bug. Please open an issue at the paperweight repo.

Done. If the mirrored issue needs the entire thing pasted please let me know.
