### ISSUE TITLE
EntityDeathEvent doesn't cancel for survival player killing an armor stand

### ISSUE THREAD

**Issue by NoahvdAa** [PaperMC/Paper#6476]
### Expected behavior

When a player in survival kills an armour stand, the EntityDeathEvent can be cancelled, so that the armor stand gets to live another day.

### Observed/Actual behavior

When a player in survival kills an armour stand, the EntityDeathEvent is fired, but cancellation doesn't work properly and the armor stand dies. 

### Steps/models to reproduce

1. Make a plugin that listens to the EntityDeathEvent and cancels it.
2. Kill an armor stand in creative.
3. Observe. The event will be fired and cancellation will work.
4. Kill an armor stand in survival.
5. Observe. The event will be fired, but cancellation won't work.

### Plugin list

N/A

### Paper version

This server is running Paper version git-Paper-209 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 98fa136)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by lynxplay** [comment]
I cannot reproduce this whatsoever. Looking at the current implementation of the ArmorStand, the death event should be properly called. Can you please provide more information or validate your setup.

**Comment by NoahvdAa** [comment]
I have no clue how I managed to mess up this report so much (is my memory really that bad?). This should be: EntityDeathEvent doesn't cancel for survival player killing an armor stand. Updated the issue and working on a fix.
