### ISSUE TITLE
Expose underlying block in a moving piston

### ISSUE THREAD

**Issue by Camotoy** [PaperMC/Paper#6479]
### Is your feature request related to a problem?

If accessing the world and finding a moving piston block, there is no way to determine what block is being moved. The only thing the API exposes, from what I tell, is that the block is moving. Wow.

### Describe the solution you'd like.

An API feature to call `getMovingBlock` and return a Block instance of what is being moved.

### Describe alternatives you've considered.

Listening to the piston extend/retract event before the block is moved. 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by lynxplay** [comment]
What exactly are you talking about here? 
Are you listening to an event? In which case the [BlockPistonEvent](https://papermc.io/javadocs/paper/1.17/org/bukkit/event/block/BlockPistonEvent.html) and its child interfaces already provide the blocks moved.

If you are talking about the [PistonHead](https://papermc.io/javadocs/paper/1.17/org/bukkit/block/data/type/PistonHead.html), it is, just like the piston, a child of the [Directional](https://papermc.io/javadocs/paper/1.17/org/bukkit/block/data/Directional.html) interface. Accessing the block infront of it should hence be pretty easy?

Are you trying to get all the blocks that would be moved by a piston if it was to be powered?

**Comment by Camotoy** [comment]
On a retracting piston with a slime block in front, accessing the block in front just returns a moving piston, as the block is in a moving state: 

The output of
```java
Block block = world.getBlockAt(x, y, z); // being a moving piston
return world.getBlockAt(block.getLocation().add(((TechnicalPiston) block.getBlockData()).getFacing().getDirection()));
```

is

`CraftBlock{pos=BlockPosition{x=-1, y=57, z=32},type=MOVING_PISTON,data=Block{minecraft:moving_piston}[facing=up,type=normal],fluid=net.minecraft.world.level.material.FluidTypeEmpty@a451491}`

And trying to get the direction on the second block just returns air.
