### ISSUE TITLE
Create SummonEntityEvent with Entity/Block involved in Spawn

### ISSUE THREAD

**Issue by Doc94** [PaperMC/Paper#6487]
### Is your feature request related to a problem?

Currently i need detect when a entity or dispenser "summon" a entity for griefing... but the entities what can be "summon" are hard to detect in plugins because use shapes (EnderDragon, IronGolem, SnowGolem, Wither) and depend of another rules (difficulty, dimension, spawn, etc)

### Describe the solution you'd like.

A Cancellable event called when a entity or block (dispenser) summon a entity. with the Block or Entity involved in this summon (Nullable)

In teory the entities that can be summon are.

- Ender Dragon (using Ender Crystals)
- Wither (Player Building or with Dispenser)
- IronGolem (Player Building or with Dispenser)
- SnowGolem (Player Building or with Dispenser)

Not sure if is better and extension of CreatureSpawnEvent or a independed Event.

### Describe alternatives you've considered.

The only alternative i see in plugins is use NMS and when any place a block run the Shape and detect if can be the cause for summon and check the rules in vanilla for spawn.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

i try to create this event in Craftbukkit but the entity summon not work the same form in all entities...

For example (based in craftbukkit):

- Wither
In BlockWitherSkull its a method (a) for check shape and summon this method is called in IDispenseBehavior when a Wither Skull is placed then is more easy make a method for add the entity/block involved. for Players in ItemStack is called the static method in BlockWitherSkull for check wither summon.
- IronGolem/SnowGolem
In BlockPumpkinCarved its the method for check but if im not wrong is only called by onPlace and this method not has the entity or block involved
- EnderDragon
In ItemEndCrystal every time a Ender Crystal its placed then check if the world has a battle and check for respawn (if in portal is with 4 ender crystal) and with another methods respawn the dragon because need regenerate the pilars and another things...

**Comment by lynxplay** [comment]
The [CreatureSpawnEvent](https://papermc.io/javadocs/paper/1.17/org/bukkit/event/entity/CreatureSpawnEvent.html) already provides you with the spawn reasons [BUILD_IRONGOLEM](https://papermc.io/javadocs/paper/1.17/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#BUILD_IRONGOLEM),[BUILD_SNOWMAN](https://papermc.io/javadocs/paper/1.17/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#BUILD_SNOWMAN)[BUILD_WITHER](https://papermc.io/javadocs/paper/1.17/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#BUILD_WITHER).

Cancelling the event with those reasons will not cancel the block placement but will maintain the block structure and simply not spawn the entity.

**Comment by Doc94** [comment]
> The [CreatureSpawnEvent](https://papermc.io/javadocs/paper/1.17/org/bukkit/event/entity/CreatureSpawnEvent.html) already provides you with the spawn reasons [BUILD_IRONGOLEM](https://papermc.io/javadocs/paper/1.17/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#BUILD_IRONGOLEM),[BUILD_SNOWMAN](https://papermc.io/javadocs/paper/1.17/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#BUILD_SNOWMAN)[BUILD_WITHER](https://papermc.io/javadocs/paper/1.17/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#BUILD_WITHER).
> 
> Cancelling the event with those reasons will not cancel the block placement but will maintain the block structure and simply not spawn the entity.

Yeah i know this.. but with this event i cant make a audit log for summon, i want people still for example summon withers and this mobs.. but if a specific user try to spawn a wither for griefing i cant know who spawn the wither.. only can have suspicious based in who placed block (wither case) or cant announce who spawn this mob like a event.

**Comment by Amaroq-Clearwater** [comment]
So you intend this to be more of a way to audit activity, and thus figure out who is responsible for doing something very naughty (and therefor, who to give a lump of charcoal for the winter holiday)

**Comment by Doc94** [comment]
> So you intend this to be more of a way to audit activity, and thus figure out who is responsible for doing something very naughty (and therefor, who to give a lump of charcoal for the winter holiday)

yeah xd

Like this.. or for make systems using the "author" of this spawns...
