### ISSUE TITLE
Buried treasure shown on maps are absent

### ISSUE THREAD

**Issue by PapiCapi** [PaperMC/Paper#6499]
### Expected behavior

Buried treasure maps should point to a buried treasure

### Observed/Actual behavior

Buried treasure mars lead to nothing

### Steps/models to reproduce

- Locate a shipwreck
- take a buried treasure map in one of the chests
- try to go where the treasure is supposed to be
- ( for me ) , there isn't any chest

### Plugin list

Multiverse-Core

### Paper version

This server is running Paper version git-Paper-219 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0a6d320)
You are running the latest version
Previous version: git-Paper-209 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
There is an option in paper.yml to configure if structure searches will load chunks (ctrl-f "load", i guess)
