### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by xKsyStudio** [PaperMC/Paper#6506]
### Expected behavior

more stable

### Observed/Actual behavior

server crashed twice in two days

### Steps/models to reproduce

Just run the server and it crashed after a while

### Plugin list

![QQ截图20210827202807](https://user-images.githubusercontent.com/87989105/131127348-969f0add-bf86-4b58-8506-e91bd50c6a34.jpg)

### Paper version

paper-1.17.1-219

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Main thread terminated by WatchDog due to hard crash
I will give you two crashed logs
[log1.txt](https://github.com/PaperMC/Paper/files/7066868/log1.txt)
[log2.txt](https://github.com/PaperMC/Paper/files/7066869/log2.txt)

**Comment by xKsyStudio** [comment]
No crash occurred when I used paper-1.17.1-214.jar

**Comment by Proximyst** [comment]
Can you try again on builds 216 and 217?

The issue here seems to be a chunk load issue; use your RTP plugin and just spam random teleports.

**Comment by xKsyStudio** [comment]
This problem takes several hours to verify if it crashes

**Comment by xKsyStudio** [comment]
I jumped directly from 214 to 219

**Comment by xKsyStudio** [comment]
I just used the 221 version of the paper, and using /rtp will also crash

**Comment by xKsyStudio** [comment]
Using /home(essentialsX) will crash too

**Comment by xKsyStudio** [comment]
[log3.txt](https://github.com/PaperMC/Paper/files/7068193/log3.txt)

**Comment by e-im** [comment]
Duplicate of #6505
