### ISSUE TITLE
Villager trade menu is not closed when unable to trade (Part2)

### ISSUE THREAD

**Issue by andrewkm** [PaperMC/Paper#6510]
### Expected behavior

When villager despawns, trading menu closed.
See: https://github.com/PaperMC/Paper/issues/4313

### Observed/Actual behavior

When villager despawns, trading menu remains open.
See: https://github.com/PaperMC/Paper/issues/4313

### Steps/models to reproduce

https://vimeo.com/592899890

### Plugin list

Discord andrewkm # 0001 on request.

### Paper version

1.16.5 B786

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment]
Could you please upload the video to YouTube or even GitHub itself? I'd rather not make a Vimeo account.

**Comment by andrewkm** [comment]
You don't need a Vimeo account to view the video.

**Comment by Proximyst** [comment]
![image](https://user-images.githubusercontent.com/19861299/131177754-9fff3336-276a-423c-9dce-d6a4a54bb8d3.png)

**Comment by andrewkm** [comment]
Not on my end...

https://i.imgur.com/8kHxAak.png

Weird...

**Comment by electronicboy** [comment]
https://user-images.githubusercontent.com/1228900/131177932-ade6c82c-20fd-4687-89bb-aa3da6e5e4a4.mp4

**Comment by andrewkm** [comment]
I got you, https://www.youtube.com/watch?v=i4EAgx6BbG8
EDIT: Damn you electronicboy.
