### ISSUE TITLE
Player Desync with Nether Portals

### ISSUE THREAD

**Issue by Tencryn** [PaperMC/Paper#6511]
### Expected behavior

Expected player to appear in the portal.

### Observed/Actual behavior

Player appeared some distance away from the portal but did eventually correct itself. With low ping, it is possible to momentarily see yourself in a different location, but this corrects itself far quicker than when witnessing another player.

### Steps/models to reproduce

This issue has occurred on different worlds but I cannot tell you what the conditions are to replicate the issue but only describe what I have noticed. The world spawn is set to `0, 0` on both worlds, with a spawn radius of 0. The player will spawn in the same position each time, and the portal can be placed a maximum of 3 chunks away before the issue is no longer present. It seems to be related to the spawn chunks?

### Plugin list

None

### Paper version

This server is running Paper version git-Paper-222 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 159112e)
You are running the latest version
Previous version: git-Purpur-1335 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I have narrowed down this issue to be Vanilla. I created a bug report with more detail here [https://bugs.mojang.com/browse/MC-235414](https://bugs.mojang.com/browse/MC-235414) in hope that it can be fixed for a later version of Minecraft. I was also advised to create an issue here in hopes that Paper can provide a patch in the meantime.

The issue was first noticed in Paper very early on and is still present with the latest version as of typing this. I tried with Tuinity and Purpur before trying Vanilla. The issue is present in Vanilla, and was not patched by Spigot and forks.

If a video is needed, I can provide one. I will answer any questions too to the best of my ability.

**Comment by embeddedt** [comment]
This sounds related to https://bugs.mojang.com/browse/MC-98153 (despite that bug being marked as fixed).

**Comment by electronicboy** [comment]
Pretty sure that this is a general order of operation issue with how portals work, you're moved to the world before your position is actually set in there, iirc, so for a period of time you actually are in the incorrect place
