### ISSUE TITLE
A Fabric mod containing all of Paper's optimizations

### ISSUE THREAD

**Issue by TechPro424** [PaperMC/Paper#6529]
### Is your feature request related to a problem?

Many people use Paper for their servers, but for cases where they want to do heavy modding, they might choose Fabric or Forge. A Fabric mod with Paper's optimizations would help them a lot.

### Describe the solution you'd like.

A Fabric mod containing all of Paper's optimizations **(without game mechanic changing bugfixes, small or large)**
For example, Starlight (from Tunity) is already a Fabric mod. Similarly, for example, eigencraft redstone could be a mod, along with any other optimizations.

### Describe alternatives you've considered.

I don't have any alternatives.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by electronicboy** [comment]
No, there are many alternatives for fabric performance improvements, and far out of our investment range
