### ISSUE TITLE
/timings on crashes my server

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#654]
# Crash, Stacktrace

### Link/paste of stack trace
https://pastebin.com/YVLWRaJc

### Plugin list:
https://gyazo.com/533b90a46ee2b5f82a330034550915ad
### Actions to reproduce (if known):
/timings on

### Paper build number:
https://gyazo.com/2ed159bd5633a6d9750264eb67406318

# Suggestion

___We love suggestions! Suggestions are fairly unstructured, and will be treated as such___

**Comment by ghost** [comment]
i have just put the latest version of paperspigot (1.11.2) and i still get a crash https://pastebin.com/GA32PGwz

**Comment by mikroskeem** [comment]
Issue is related with [React](https://www.spigotmc.org/resources/react-smart-server-performance.21057/). Please contact with plugin author.

**Comment by aikar** [comment]
It is not our code causing this. as @mikroskeem said, React must fix this.
