### ISSUE TITLE
Replace com.mojang.authlib.GameProfile with player name

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#6549]
### Is your feature request related to a problem?

Partial. Every time my server got attacked by bots, or many players are disconnected, I see a [huge amount of] lines like this in server log:

```
com.mojang.authlib.GameProfile@365e1d6a[id=...,name=ExtraP7385,...] (remote address) lost connection: Reason ...
```

### Describe the solution you'd like.

My suggestion is to replace this line with this (convert com.mojang... to player name):

```
ExtraP7385 (remote address) lost connection: Reason ...
```

Because this can improve the readability of server logs. Upstream ignores this FR for years, but maybe you can make the server better..

Note: UUID of the player is displayed every time in the preceding line (`UUID of player ... is ...`), if someone says that this is required and cannot be removed

### Describe alternatives you've considered.

Use a regex parser and replace these lines in log files to required format..

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

Thanks

**Comment by electronicboy** [comment]
This is not something I see an interest in, we're relying on the GameProfiles toString method, and replacing that call with something else would have a much wider effect than just this specific case, especially as this info is often used for debugging purposes and it's format is pretty standardised and known against automated tooling and such
