### ISSUE TITLE
Get kicked by a Packet processing error

### ISSUE THREAD

**Issue by rrvk** [PaperMC/Paper#6551]
### Stack trace

```
https://paste.gg/p/anonymous/6ca8d9f5b55a4e8c818924e793fa322a
```

### Plugin list

None

### Actions to reproduce (if known)

* Create a new server
* Add the following datapack: https://www.planetminecraft.com/data-pack/blazeandcave-s-advancements-pack-1-12/
* Get a advancement: for example make a iron presure plate
* Get kicked and see the exception in the logging

### Paper version

This server is running Paper version git-Paper-243 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 20903fc)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by EpicnessTwo** [comment]
I too am getting this same error with the latest build of paper and that advancement pack

**Comment by Aurelien30000** [comment]
Confirmed, another log that could help you https://paste.domicraft.fr/bepakajici.css

_May be introduced in this commit https://github.com/PaperMC/Paper/commit/f02d3d89895014b62ec36d1de1ac16fd63a36f40_

**Comment by nekriS** [comment]
Faced the same problem.
I too used this datapack.

My log: https://paste.gg/p/anonymous/9da3e7805ae34d2ab12f9ebade585092
