### ISSUE TITLE
Bundle Interaction Event

### ISSUE THREAD

**Issue by aikiboo** [PaperMC/Paper#6552]
### Is your feature request related to a problem?

I want to create a bundle that accept only one type off item (like ore/fish/mob loot).
But I have to use an InventoryClickEvent with a lot of checks. 

### Describe the solution you'd like.

1. An event that procs when player try to put item inside a bundle (full or not)
2. An event that procs when player take an item form a bundle
3. An event that procs when player dumps all item inside a bundle

### Describe alternatives you've considered.

Use InventoryClickEvent and check if event::getClick is a rightclick and after if event::getCurrentItem is a bundle same with event::getCursor::getType not AIR. And if I cancel the event I have to give back item to player only if bundle isn't full. 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by electronicboy** [comment]
hyper specific events are not viable especially in a manner where they can be cancelled safely, stuff like this would basically just be hyper filtered attempts of the current Inventory events which just creates a lot of complexity maintenance wise as now we have to attempt to maintain all of this filtering, etc, etc - this is not really a goal of the API, especially as this request can easily be extended to literally every other inventory which is just out of scope
