### ISSUE TITLE
Enable GPU acceleration of CPU-intensive processes

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [PaperMC/Paper#6554]
### Is your feature request related to a problem?

Some essential processes in the game can be very CPU-intensive at larger scales (say, running an entire server). Examples include chunk loading and world generation, or processing the flow of "fluid" blocks such as water and lava.

### Describe the solution you'd like.

Using tools like OpenACC and OpenMP, it is possible to make very small modifications to existing multi-threaded code so that it can automatically utilize GPU acceleration whenever it's available. If this is possible to implement, then it might result in a huge increase in performance on servers that happen have access to powerful GPUs, and shouldn't result in a loss of compatibility (or degradation in performance) for any servers without such additional hardware.

However... OpenACC and OpenMP are designed for C++ and Fortran, and require a compatible compiler. I have no idea how well they'd function for platforms such as Java or .NET, which use interpreters and JIT compilers.

Additionally, using OpenACC and the competing OpenMP does require going into the code, and making sure any code that is compatible with (or better yet optimized for) parallel processing is cleanly separated from any code that isn't yet parallelized, a task which does need to be performed by hand... And as I write this, not all of Paper's code is fully ready for parallel processing.

### Describe alternatives you've considered.

CUDA and OpenCL could potentially have much better results in terms of raw performance, but would require writing new code from scratch as opposed to simply modifying existing code, and would also require maintaining two or more separate codebases for CPU compatibility and GPU acceleration. Additionally, CUDA in particular is only usable on Nvidia GPUs. In other words, using either of those two languages probably isn't worth the hassle for something that constantly requires update.

Alternatively, one could just continue relying on multicore CPUs for parallel processing, but the proposed OpenACC implementation wouldn't necessarily take away from any of that. If anything, it's just a logical extension of work that's already being done.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

Free whitepapers for both OpenACC and OpenMP (two very similar but competing solutions) are available for review with some quick internet searches, and Nvidia has even produced an article on their own website regarding the former.

To my understanding, OpenACC and OpenMP, despite competing with eachother, are not mutually incompatible and might be able to be used together. They are also both open-source (to the best of my knowledge, something might have changed since I last looked into this), and if they don't yet support Java (though I'm hopeful that they already do), there is no reason to believe that they would never be able to with a little bit of work.

**Comment by electronicboy** [comment]
The majority of servers do not have the hardware support for this, and much of the process is not easy to do on the GPU, nor is there much interest in basically rewriting the very few areas where this would actually have any gains to take advantage of this

**Comment by Amaroq-Clearwater** [comment]
Well, that was quick... (You closed this in less time than it took for me to write it!)
Wouldn't you at least be willing to look at the OpenACC documentation when you get the opportunity, at the very least for curiosity's sake? It really shouldn't take very long just to read it :(

The whole point of OpenACC is that the only code you would actually need to rewrite is stuff that already needs to be rewritten just to support multi-core processing. Any sections of code which are already optimized for multi-threading, according to what I've read, would only require minimal tweaking to work.

That is, of course, assuming that OpenACC can even be used with Java in its current implementation. If not, then... yeah, maybe this was just a waste of everyone's time after all...

**Comment by electronicboy** [comment]
Not looked at OpenAAC before but this stuff is tossed around every few dozen months, so our inclination to put much effort into discussing it is practically 0, GPU compute is not a trivial aspect and there are many caveats, in order for this, you'd need to pass data over JNI, meaning you have an overhead there, then you send the work over to the GPU and the data, which has an overhead, then you basically sit waiting for the results back (unless you have to poll, not sure how that all works), and then pull the data back, which has overheads

There are very few areas of the codebase which are really suited and could actually offer improvements to justify those overheads, then you'd need to actually design stuff to take advantage over it, the primary real areas of improvements here is pretty much solely the chunk noise generation and maybe other aspects of gen which are heavily "math" based where the GPU excels and you're not tossing data back and forth consistently as these are somewhat isolated areas, but, outside of that, GPU compute does not look all that interesting

The inclination to modify the server to take advantage of this flow, especially given the small % it would actually benefit is minimal, you'd need to modify the server to take advantage of the flow, rewrite the few areas which can actually take advantage of this into C, and then benchmark it and see if it's actually worth it, and then you've got the costs of actually maintaining that logic.

These are all non-trivial efforts in which there is much more work to do elsewhere which can improve performance for the wider community which don't involve incurring massive amounts of maintenance debt.

**Comment by Amaroq-Clearwater** [comment]
That actually makes a lot of sense, and is sad to hear, but also very interesting information nonetheless. (Looks like I have a new rabbit hole to lose myself in.)

Maybe once there's a viable way to transparently and efficiently implement GPU compute in Java, this topic can be revisited. But alas, today is not that day. ☕️

**Comment by Gaming32** [comment]
There are Paper fork(s) that aim to do this. One such example is [SugarcaneMC](https://www.reddit.com/r/admincraft/comments/o6rxfj/new_server_software_on_the_scene_sugarcane/).

**Comment by e-im** [comment]
This is just a claim they have made without even having any real plan. Much like the majority of other claims in that reddit post, there is no implementation.

**Comment by Gaming32** [comment]
Not yet 👀 (honestly not sure if there will be any time remotely soon lol)

**Comment by Amaroq-Clearwater** [comment]
I actually just found a recent article about Java and GPU computing.
https://blogs.oracle.com/javamagazine/programming-the-gpu-in-java

Maybe there's some hope after all.
