### ISSUE TITLE
Chunk and Entity Lag - paper 1.17.1 v249

### ISSUE THREAD

**Issue by tbm00** [PaperMC/Paper#6557]
### Timings or Profile link

https://timings.aikar.co/?id=3845c1bacba74699a8dcc4d98e608710

### Description of issue

Server cannot keep up. From Sep 4, 2021 1:24 PM to Sep 4, 2021 1:41 PM, Minecraft::Full server tick is at 2000% of tick (according to the timings report). I've generated many reports, and they always seem to point towards lag stemming from chunks and entities. 

Currently, the spawn-limits for monsters and animals are 40 and 7, respectively. I have adjusted these limits multiple times to no avail. Also, per-player-mob-spawns is false.

The sudden drop in TPS typically occurs at least 3hrs of the after a server restart. Therefore, I have implemented frequent restarts as a work around.

This has been a problem for a month and I cannot solve it. I have optimized (according to the spigot guide) and optimized again. Any and all help is very much appreciated! I would definitely appreciate your two cents on any issue :)

### Plugin list

Plugins (55): AdvancedHelp, AdvancedPortals, AuctionHouse, AuthMe, BankPlus, bAnnouncer*, BetterRTP, BotSentry*, ChestSort, CMILib, CommandPanels, CommandSigns, CoreProtect, DeluxeCombat, DisplayShops, DropHeads, Economy, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, FarmLimiter, FlyingCarpet, GangsPlus, GriefDefender, Harbor, HarmonyScoreboard, HolographicDisplays, InviteSystem*, Jobs, LootCrate, LuckPerms, MineableSpawners, Multiverse-Core, Multiverse-NetherPortals, OpenInv, PlaceholderAPI, ProtocolLib, ShopGUIPlus, ShopGUIPlus-SellGUI, SignEdit, SkinsRestorer, SuperVanish, TAB, Vault, VeinMiner, ViaBackwards, ViaVersion, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, XProtect*

### Server config files

https://paste.gg/p/anonymous/eb870966ddef45a59486b95ab89c0070

### Paper version

This server is running Paper version git-Paper-249 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6fa1983)
You are running the latest version
Previous version: git-Paper-246 (MC: 1.17.1

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
Please use the discord for support, you're having memory issues
