### ISSUE TITLE
Server crash when player euqpiting armor with enchant "minecraft:"

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6558]
### Stack trace

```
https://paste.gg/p/anonymous/d7ab86091ec14d20922fbbe2ef431617/files/76da774522f8406e9309a42f18c43be5/raw
```

### Plugin list

None

### Actions to reproduce (if known)

/give yourself a armor peice* with enchant "minecraft:" then euqpit it

### Paper version

This server is running Paper version git-Paper-249 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6fa1983)
You are running the latest version
Previous version: git-Paper-1618 (MC: 1.12.2)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
don't use an invalid enchant, am not sure that there is much inclination to bodge this to not cause issues with invalid data, even if MC probs doesn't care

**Comment by ghost** [comment]
Oh yeah it also dosnt work on vannila

**Comment by ghost** [comment]
It kinda seems to rollback the world atleast in my testing

**Comment by NoahvdAa** [comment]
> It kinda seems to rollback the world atleast in my testing

Probably because the server doesn't save the world when crashing.

**Comment by kennytv** [comment]
This is very much a valid issue, since Bukkit is being Bukkit and forbidding namspaced keys that are very much valid by Vanilla standards.
