### ISSUE TITLE
Server crash once a day

### ISSUE THREAD

**Issue by bloggy** [PaperMC/Paper#656]
Server crashes daily once with attached error.
[CRASH.txt](https://github.com/PaperMC/Paper/files/923662/CRASH.txt)

Can you help me to solve it? What is causing this?

**Comment by mikroskeem** [comment]
Seems to be related to [TerrainControl](https://www.spigotmc.org/resources/terraincontrol.2214/) plugin. Contact with plugin author.

**Comment by bloggy** [comment]
Thanks will contact him, but that issues started to happen as of sudden. We did not change configs or updated TerrainControl. Why do you assume it's TerrainControl's fault?

**Comment by mikroskeem** [comment]
Also Paper version is outdated (crash log shows `git-Paper-1064`). Please try with latest version as well

**Comment by electronicboy** [comment]
TerrainControl being in that crash is likely just a coincidence of the matter from the looks of it, these types of crash reports are somewhat highly inaccurate with most actual issues having already occurred and passed after the watchdog times out. (ChunkGen is also one of those expensive operations, which as below...)

It's very easy to throw blame towards a single plugin when you're looking at these reports, when it's another plugin having done a http request on the main thread and timed out just before the watchdog got to it, or a matter of a badly designed plugin taking up more time each time it's triggered and eventually just taking up too much time to trigger the watchdog (and somehow managed to just skim the watchdog grabbing it in the stacktrace)

Worth noting that you have a plugin, that is actually looking for blocks and has in this case actually triggered chunk generation, (which is generally never a good sign, that would imply that the range is too high, or your servers view distance isn't high enough to cope with the range this plugin is using)

```
[16:11:10] [Paper Watchdog Thread/ERROR]: org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:179)
[16:11:10] [Paper Watchdog Thread/ERROR]: org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:213)
[16:11:10] [Paper Watchdog Thread/ERROR]: me.lyria.lyriaskill.skills.battle.rogue.Kick.cast(Kick.java:36)
[16:11:10] [Paper Watchdog Thread/ERROR]: com.sucy.skill.api.player.PlayerData.cast(PlayerData.java:1813)
```

**Comment by zachbr** [comment]
Not an issue with Paper as multiple contributors have mentioned
