### ISSUE TITLE
Composter only rolls once even when hopper-amount is above 1

### ISSUE THREAD

**Issue by gecko10000** [PaperMC/Paper#6561]
### Expected behavior

Each compostable item moved into a composter should contribute to its fill level.

### Observed/Actual behavior

Every move into the hopper only contributes one of that item towards the fill level.

### Steps/models to reproduce

Change `hopper-amount` to 64 in `spigot.yml` and put a hopper on top of a composter. Put a stack of pumpkin pie into the hopper and see that the composter only fills up by 1 level.

### Plugin list

No plugins.

### Paper version

[20:03:28 INFO]: This server is running Paper version git-Paper-249 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6fa1983)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
So this is a bug, but not in the way you think. The composter's internal container only has a max stack size of 1. So increasing the hopper move size to 64 should not roll the composter's thing 64 times, but the hopper should only move 1 at at time.

**Comment by DereC4** [comment]
This is still happening to me ;-;
