### ISSUE TITLE
Wither rose place/spawn event?

### ISSUE THREAD

**Issue by Sneakometer** [PaperMC/Paper#6564]
### Is your feature request related to a problem?

I want to disable wither rose spawning in certain areas, but i can't find any event for that. I tried EntityChangeBlockEvent, BlockFormEvent and EntityBlockFormEvent, but cancelling all of them did not help.

### Describe the solution you'd like.

Either to fire EntityBlockFormEvent or add a flag in entity death event "spawnWitherRose".

### Describe alternatives you've considered.

It would also be possible to add a new event, but not preferable.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Doc94** [comment]
I check wiki/code and the wither roses are not placed when mob die by wither, the roses "drop" then you can check EntityDropItemEvent.

Based in CraftBukkit code too.
![image](https://user-images.githubusercontent.com/3602279/132141053-9bbfa522-85fb-48b2-9753-512b61e86c0e.png)

**Comment by lynxplay** [comment]
The wither rose may be placed into the world if possible: https://github.com/PaperMC/Paper/blob/master/patches/server/0263-Improve-death-events.patch#L166 is a patch that touches this but basically the server attempts to place the wither rose into the world if possible and only drops it if that fails.

See `net.minecraft.world.entity.LivingEntity#createWitherRose(LivingEntity)`.

**Comment by Doc94** [comment]
> The wither rose may be placed into the world if possible: https://github.com/PaperMC/Paper/blob/master/patches/server/0263-Improve-death-events.patch#L166 is a patch that touches this but basically the server attempts to place the wither rose into the world if possible and only drops it if that fails.
> 
> See `net.minecraft.world.entity.LivingEntity#createWitherRose(LivingEntity)`.

:O i see, i dont see this in CB because its not edited in this lines... 

well i try a PR in CB for call the event in this case.
