### ISSUE TITLE
Create a `PersistentDataType` list type that can contain none/many unkeyed tags of the same type

### ISSUE THREAD

**Issue by drunderscore** [PaperMC/Paper#6565]
### Is your feature request related to a problem?

NBT has the concept of a `TAG_List`, which can contain none/many unkeyed tags of the same type. The PDC abstraction is missing such an implementation, and so something such as a list of strings is impossible without a custom type.

### Describe the solution you'd like.

Create a list abstraction that can be used to hold none/many of the same tag type. Implement this in Paper's PDC implementation by virtue of the `TAG_List` NBT tag.

### Describe alternatives you've considered.

Creating a custom data type would work: Serialize this list as a `byte[]`, with the list length, and `length` many of the specified types.

This is cumbersome and should be unnecessary to implement manually, as the primary implementer of PDC (NBT) has a type for this exact purpose.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by lynxplay** [comment]
In regards to this issue, back in 2019 I already attempted to implement an API to represent lists of persistent data types through the API tho sadly the spigot PR was lacking engagement of the spigot community and I really wanted more input on the PR and following API design choices besides md_5's view.

I shipped the PR over to https://github.com/lynxplay/paper/pull/2 as I am unsure whether the general concept of that PR is good enough for being pulled. Additionally, I believe this PR should most likely be shipped towards upstream to at least keep the PDC API persistent in the ecosystem (hanger wen). 

Quick note for anyone looking at this, the source code is from may 2019 and might very well not be up to date with current concepts and standards. 

Should I open a draft PR for this to move discussion there ?
