### ISSUE TITLE
Better Update Folder Implementation

### ISSUE THREAD

**Issue by Xemorr** [PaperMC/Paper#6570]
### Is your feature request related to a problem?

When using the update folder to update plugins, it only replaces a plugin if the file name is the same. This causes issues when trying to follow good convention and have versioned file names.

### Describe the solution you'd like.

 I would instead like it to replace a plugin if the plugin name (as stored in plugin.yml) is the same.

### Describe alternatives you've considered.

Writing the PR myself but I don't think I'd do a good job.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by MiniDigger** [comment]
> "I don't think I'd do a good job"

just give it a try! we are always happy to help, join the #paper-dev channel on discord if you need any assistance and people will be happy to help

**Comment by Xemorr** [comment]
Yeah, alright, I'll give it a go.
