### ISSUE TITLE
require-resource-pack=true will override Player#setResourcePack(String, String, false)

### ISSUE THREAD

**Issue by tahmid-23** [PaperMC/Paper#6571]
### Expected behavior

calling Player#setResourcePack(String, String, false) with require-resource-pack=true in server.properties will let the Player not load the resource pack

### Observed/Actual behavior

the player will be disconnected if they decline the resource pack

### Steps/models to reproduce

set require-resource-pack to true in server.properties
by plugin send a resource pack that is not required to a Player and have them decline the resource pack

### Plugin list

my test plugin

### Paper version

[21:58:46 INFO]: This server is running Paper version git-Paper-251 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5960af9)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

in the serverbound resource pack packet handler, the value of require-resource-pack is used to determine whether or not to kick the player
no information is sent back about the actual request so there isn't a simple way to figure out whether or not the pack should have been actually loaded or not with the setResourcePack parameter
it is a bit confusing to see the server saying the resource pack is optional and then to have it kick you, so maybe the required parameter should be overridden by the value of require-resource-pack in the CraftPlayer implementation

**Comment by Machine-Maker** [comment]
So this is a bit of an annoying issue, When the server gets back from the client a resource pack response, there's no way for the server to know which resource pack its responding to, only what the response is.

**Comment by Owen1212055** [comment]
This issue is generally not possible to fix on paper's end, as the client does not provide the necessary context as to which resource pack was denied/accepted. 

I don't see any feasible way to fix this nicely.
