### ISSUE TITLE
Server spams netty errors until server stops/crashes.

### ISSUE THREAD

**Issue by Impactic48** [PaperMC/Paper#6577]
### Stack trace

```
(Can't post on paste.gg because my logs are too long)
Logs with all plugins installed:
https://mclo.gs/jAzOcVR
https://mclo.gs/GOl9wZw
https://mclo.gs/jh2xF5n
https://mclo.gs/jeA9BVt
https://mclo.gs/Bx6YmtO
https://mclo.gs/3whaVL2
https://mclo.gs/FMk7uar

Log below with the following plugins: CMI, CMILib, Luckperms, Residence, and EventDebugger (Added EventDebugger after this issue started so it's not causing it).
https://mclo.gs/XqvJpLL
```

### Plugin list

AsyncWorldEdit, BetterRTP, BuycraftX, CMI, CMILib, CoreProtect, DiscordSRV, EventDebugger, LuckPerms, MobFarmManager, MythicMobs, PlaceholderAPI, PlayerHeads, Plugman, ProtocolLib, Residence, Shopkeepers, Skript, skript-reflect, TAB, nuVotifier, WorldEdit, WorldGuard

The issue still happens when only the following plugins are installed: CMI, CMILib, LuckPerms, and Residence (Limited to these 4 plugins through deleting plugins until I got down to these 4 and still had errors). I have a link above with the plugins listed above but with EventDebugger installed (EventDebugger isn't causing the issue)

### Actions to reproduce (if known)

`/home
/tpa
/spawn
Keepalive timeout

### Paper version

Paper(250) 1.17.1-R0.1-SNAPSHOT

This issue has persisted throughout the last several builds of Paper that I have tried. I have just updated to the latest build of Paper and will post more logs when the issue happens.

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Actions to reproduce

The things listed in "Actions to reproduce (if known)" above are the most common issues that cause the warning/error. It happens randomly with the things listed. It does NOT happen every time and is very very random so it's impossible to force the issue to reproduce. Following issue that's spammed on my console before it crashes/stops:

[Netty Epoll Server IO #1/WARN]: io.netty.channel.StacklessClosedChannelException
[Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)

This error is shown spammed 5-50k times on some of the logs. I have had this issue since August 1st so I ignored them but it has recently started crashing my server within the past week. I do have to note that it does not crash/stop every time this error happens but a majority of the time.

**Comment by electronicboy** [comment]
Evertime we've seen this exception it's been down to plugins injecting themselves into the networking logic in a manner that prevents the network connection for a user from actually closing

**Comment by Impactic48** [comment]
Any idea what plugins do this out of these four plugins: CMI, CMILib, LuckPerms, and Residence?

**Comment by electronicboy** [comment]
Pretty sure it can't be LP, beyond that, can't really comment on "premium" stuff I've no experience with

**Comment by Impactic48** [comment]
Alright, thanks for the quick reply. I'll bring this over to the CMI github.
