### ISSUE TITLE
Disabling tab-complete setting still allows for tab completion

### ISSUE THREAD

**Issue by deciduous-buffalo** [PaperMC/Paper#6579]
### Expected behavior

When you join a 1.17 server with another version, like 1.12 (using client-side ViaVersion), you should be able to type "/" and when you press tab not be able to see any plugin commands.

### Observed/Actual behavior

When you join a 1.17 server with another version like 1.12 using client-side ViaVersion, you can type "/" and then press tab and see every single command for all of your plugins. I think the issue here is that Mojang changed the way tab-completion is sent to the player from 1.13 onwards, in a separate packet to the user. However, the old packet for 1.12 is still being sent, so older clients on 1.12 will receive the 1.12 packet still and display all the commands to the user. I'm currently solving this issue by using ProtocolLib in my plugin to block the packet from being sent by the server, but this still poses as a security risk for server owners that don't realize this.

### Steps/models to reproduce

Join 1.17 server running latest paper version and nothing else with a Minecraft client from 1.12 or lower. Then type "/" and press tab and you can see all the commands even with tab-complete setting turned entirely off.

### Plugin list

None

### Paper version

Paper Latest Version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by skw359** [comment]
Sounds like a viaversion config, check that tab-complete

**Comment by Fejm** [comment]
Client side mod, not paper issue.

**Comment by electronicboy** [comment]
Protocol hacks are not supported
