### ISSUE TITLE
Since build 232 1.17.1 server experiences Tick Duration server lag when running farms

### ISSUE THREAD

**Issue by bloodycoffin** [PaperMC/Paper#6582]
### Timings or Profile link

https://spark.lucko.me/k3Pah6lRmD / https://timings.aikar.co/?id=53f22e4c2af34febad221e8f78ab1ea3

### Description of issue

Since build 232 (we're now running build 255-1.17.1) we're experiencing additional lag around farms on our server. The Tick Durations will spike to 500-1000 with TPS lag when it is more than a single spike. The farms that are giving issues are:
- A flying machine harvesting dripstone spikes (falling dripstone, flying machine pushes entities into a waterstream that ends up in hoppers into a chest)
- Shulker farm (moving minecarts, redstone lit up, hoppers covered by composters)
- Nether tree farm (warped and crimson tree growing side by side, pushed forward by pistons, exploded by double TNT duplication)
Next to these farms where we have noticed the most lag, even basic pumpkin farms (9x9) with pistons, redstone dust and a single minecart track can cause issues. But also growing trees and not just 2x2 like Dark Oak, Spruce or Jungle, but also when growing 1x1 trees like Azalea that make the server stutter upon growth.

The additional Config options of Tuinity now captured in paper.yml didn't give us a first idea of what could be impacting our farms all of the sudden since before build 232 the tick durations were fine with those same farms.

### Plugin list

Chunky
CoreProtect
DiscordSRV
DynMap
HeadDatabase
LuckPerms
Maintenance
MultiChat
Multiverse-Core
OpenInv
PlaceholderAPI
PremiumVanish
PrometheusExporter
ProtocolLib
Shopkeepers
Spark
TAB
Vault
ViewDistanceTweaks
VoiceChat
WorldEdit
WorldGuard
xAntiAFK

### Server config files

```
https://paste.gg/p/anonymous/ccb491d134c04a6d879c72f7707641b3
```

### Paper version

§fThis server is running Paper version git-Paper-255 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c3d5018)§r
§aYou are running the latest version§r
§7§oPrevious version: git-Paper-251 (MC: 1.17.1)

(from Putty // kubectl exec -it <<minecraft-pod-name>> -- rcon cli // command: version)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

https://github.com/ArchitectSMP/k8s-gitops (our Github)

**Comment by electronicboy** [comment]
Please use the discord for support, I'd also highly suggest using hotspot vs openj9 as there are some performance impacts and incompatibilities with j9. But, your spark and timings report both point to redstone taking a sizable amount of time, from the timings and spark, looks like there is a redstone machine or something taking up a lot of time

**Comment by ChipWolf** [comment]
We've profiled hotspot with aikars against j9 with the equivalent of aikars; j9 performs far better in our environment. Same issue persists with both hotspot & j9, thanks for your pointer regarding redstone machinery, although nothing has changed in that regard other than the tuinity migration.

**Comment by ChipWolf** [comment]
> Please use the discord for support, I'd also highly suggest using hotspot vs openj9 as there are some performance impacts and incompatibilities with j9. But, your spark and timings report both point to redstone taking a sizable amount of time, from the timings and spark, looks like there is a redstone machine or something taking up a lot of time

We've profiled hotspot with aikars against j9 with the equivalent of aikars; j9 performs far better in our environment. Same issue persists with both hotspot & j9, thanks for your pointer regarding redstone machinery, although nothing has changed in that regard other than the tuinity migration. @electronicboy
