### ISSUE TITLE
server crashes when invalid? chest minecart gets killed by void

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6583]
### Stack trace

```
https://paste.gg/p/anonymous/9df8f8b598f5442096ae3c79494d16e6
```

### Plugin list

None

### Actions to reproduce (if known)

run `/give @s minecraft:bat_spawn_egg{EntityTag:{Pos:[0,-64,0],Invisible:1b,Invulnerable:1b,LootTable:"",id:"minecraft:chest_minecart"},display:{Name:'{"text":"load the chunk"}'}}`
then load the chunk where its spawned
you might need to go down to bedrock to load the entity

### Paper version

This server is running Paper version git-Paper-257 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8a2b23a)
You are running the latest version
Previous version: git-Paper-255 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by NoahvdAa** [comment]
Seems to be caused by the same root issue as #6558, invalid namespacedkeys. The fix I suggested in #6559 could probably be expanded to also include a fix for this.

**Comment by lynxplay** [comment]
Yea, I can reproduce this locally. The discussion for this is then the same as in the other issue as well:

> don't use an invalid enchantment, am not sure that there is much inclination to bodge this to not cause issues with invalid data,  even if MC probs doesn't care

As cat layed out in the other issue.

**Comment by Owen1212055** [comment]
This can probably be closed as the fix was pushed a while ago.

**Comment by ghost** [comment]
True.
