### ISSUE TITLE
Player still in server after connection lost

### ISSUE THREAD

**Issue by RuofengX** [PaperMC/Paper#6584]
### Expected behavior

A player, lost connection, and then the server would know the player quit immediately, and remove this player.

### Observed/Actual behavior

In some cases(I don't know how to reproduce, but this happens everyday in players of my server), a player lost connection because of network fault or client fault. Then the server didn't know the connection is already lost and keep the player in server. Other player and mod can attack this player, just like it didn't lost connection.
This could cause: unexpected death, and player would lost everything with doing nothing.

### Steps/models to reproduce

Connect to the server and quit, in some cursed cases, this would happen.
And MAYBE restart client is a sollution.

### Plugin list

AuthMe, bPermissions*, Chairs, ChunkLoader, ClickSort, com.quillinati.safecreeper.NoDestructoCreeper, CoreProtect, DeadChest, DeadlyDisasters, dynmap*, DynmapBannerMarkers, GiantTrees, gMoney*, LockettePro, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, OpenInv, PlaceholderAPI, PlugMan, ProtocolLib, QuickShop, QuickShopDynmap, RetainXP*, SendMeItems, ServerAnnounce*, ServerSigns, Shopkeepers, SitEverywhere, Terra, TimeManager, TreeAssist, Vault, VeinMiner, VoidGenerator, WorldBorder, WorldEdit, XPPlus

### Paper version

> version
[07:20:55 INFO]: Checking version, please wait...
[07:20:57 INFO]: This server is running Paper version git-Paper-783 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 5 version(s) behind
Previous version: git-Paper-777 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Not running the latest build, but this bug happened from the server start (60 days ago maybe)

**Comment by RuofengX** [comment]
It seems like the client close the connection but the server don' t know and wait until timeout then kick the player.

**Comment by electronicboy** [comment]
We can't know that a connection has closed unless we get the signal from the client, the fact that this is not reliable is why networking stuff often has timeouts and "are you alive?" checks when keeping a connection open, not much we can do about this other than reducing the timeout, which, would create more issues
