### ISSUE TITLE
Soul Sand Valley and Warped Forest Spawning Issues

### ISSUE THREAD

**Issue by Tzpi89** [PaperMC/Paper#6594]
### Expected behavior

Since the 1.16 version Mobs in the soul sand valley and warped forest have a unique spawning conditions where mobs can't spawn close to each other so that you only have a mob every 20isch block 
in the soul sand valley that affects the skeletons, ghasts and striders in the warped forest it's only the enderman
So if you bring around 30 striders together in one spot no skeletons or ghasts should spawn in the soul sand valley

### Observed/Actual behavior

the soul sand valley and warped forest mobs don't consider this distance rule. This was also reported back in december of 2020: https://github.com/PaperMC/Paper/issues/4625

### Steps/models to reproduce

put ~35 striders in one spot kill all skeletons and ghasts then see that skeletons and ghasts still spawn besides 35 striders beeing present

### Plugin list

none

### Paper version

paper-1.17.1-257

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Prof-Bloodstone** [comment]
@Tzpi89 Could you try reproducing it on Spigot? I was able to reproduce on Paper and it seems to be working on Spigot, but would be great if you could also confirm.

Did you try reproducing it on Paper with different spawning-changing settings disabled (like per-player-mob-cap etc.)?

**Comment by Machine-Maker** [comment]
For reference, [this is the mechanic](https://minecraft.fandom.com/wiki/Spawn#Spawn_conditions) (find the subsection labelled `Spawn costs`) this is referring to.

**Comment by Machine-Maker** [comment]
@Tzpi89 how exactly are you testing this? If you are doing this with default paper.yml settings and using spawn eggs, that will not produce accurate results. Paper, by default, only counts mobs that are spawned naturally to the mob cap (and that includes the mob charge system). You should enable `count-all-mobs-for-spawning` and try again perhaps.

**Comment by Tzpi89** [comment]
@Prof-Bloodstone okay I tested it on spigot and it's actually a bug on their side. on a vanilla server everything is fine, when there are like ~50 striders no other mob spawned but when I tested the same setup on a spigot server a skeleton could even spawn directly next to the striders only one block distance which shouldn't happening. For the setup I cleared an area so the only point where mobs could spawn was a dirt area at y=0 like this: https://imgur.com/a/eOedrWS
I also tested it with various setting like count-all-mobs-for-spawning and per-player-mobcap but that doesn't really matter when the problem is with spigot

**Comment by Owen1212055** [comment]
Are you still able to reproduce this as of 1.19 on paper?

**Comment by Owen1212055** [comment]
Because there hasn’t been much activity I will be closing this. If you are still able to reproduce this feel free to comment and this issue can be reopened. Thank you!
😊
