### ISSUE TITLE
Paper patch : can't read /c/Users/Steven/Desktop/Paper/work/1.9.4/net/minecraft/server/Block.java: No such file or directory

### ISSUE THREAD

**Issue by Eremmmm** [PaperMC/Paper#6595]
### Expected behavior
Hello,

When I run the ./paper p command for version 1.9.4 I get this error message.
`can't read /c/Users/Steven/Desktop/Paper/work/1.9.4/net/minecraft/server/Block.java: No such file or directory`

### Observed/Actual behavior
![Capture d’écran 2021-09-12 181706](https://user-images.githubusercontent.com/49162612/132995109-0f923d86-80ae-4fee-a85e-77284911fd4c.png)

_No response_

**Comment by NoahvdAa** [comment]
> I am running the latest version of Paper available

> 1.9.4 

*:thonk:*

**Comment by lynxplay** [comment]
1.9 has not been supported for a while now. If you are planning on running a version of paper as outdated as that, you should already have the ability to deep dive into this issue on your own :+1:
