### ISSUE TITLE
Server Chunk Crash Error

### ISSUE THREAD

**Issue by zBombard** [PaperMC/Paper#660]
Sometimes my server crash, problem "chunk", but I don't know which world or what else... Someone can help me?
https://hasteb.in/qadevaregu.avrasm

**Comment by electronicboy** [comment]
We don't support software that is years outdated, your issue is also most likely caused by a plugin doing bad things, or a corrupted map file/bug in the server, in which case you can only pray that region finder might be able to find the issue, otherwise you're mostly on your own.

**Comment by zBombard** [comment]
Such as?
