### ISSUE TITLE
Book edit processing freeze

### ISSUE THREAD

**Issue by Shevchik** [PaperMC/Paper#661]
Moved to an upstream tracker

**Comment by zachbr** [comment]
Confirmed

**Comment by Shevchik** [comment]
Also ItemBookAndAnvil contains a book pages validator that is not needed because book is already validated in the CraftMeta

**Comment by zachbr** [comment]
That comment should be sent upstream, we don't introduce diffs for minor CB code cleanup.
The original issue has also been fixed.
