### ISSUE TITLE
Crash error everytime someone joines happends with multiple people.

### ISSUE THREAD

**Issue by StefvanderMeer** [PaperMC/Paper#662]
# Crash, Stacktrace

### Link/paste of stack trace
Console LOG:
https://pastebin.com/13EGVhBe
Crash Report:
https://pastebin.com/LiACpjBD
Startup LOG:(if needed)
https://pastebin.com/7f8rUuAn

### Plugin list:
http://imgur.com/a/yoKuV
http://imgur.com/a/ylbgS
xD i have alot

### Actions to reproduce (if known):
When a player joins the full server will crash. I don't really know why it just gives me those errors. When I teleported to the last coordinates of that player it crashed the server too. I had to delete my player file to fix the problem that I can join again.

It still happens to a lot of players and I want to fix this.

### Paper build number:
http://imgur.com/a/GEQfV

**Comment by zachbr** [comment]
We don't support 1.8.8 though it appears your map is corrupt.

**Comment by DenWav** [comment]
> ### Plugin list:
> http://imgur.com/a/yoKuV
> http://imgur.com/a/ylbgS
> xD i have alot

![](https://media.giphy.com/media/aZ3LDBs1ExsE8/giphy.gif)
