### ISSUE TITLE
Entity Damage By Arrow Event =)

### ISSUE THREAD

**Issue by NicoNekoDev** [PaperMC/Paper#664]
# Incompatibility (Bug)

### What behaviour is expected:
Entities to not burn when hitted by arrow.
### What behaviour is observed:
Entities burn.
### Steps/models to reproduce:
Cancel "EntityDamageByEntityEvent", get a bow with flame, shot a arrow to a entity. Damage is cancelled, but the flame effect remain.

### Plugin list:
[Server] INFO Plugins (62): GroupManager, PlaceholderAPI, PlugMan, BetterChairs, FastCraftPlus, PandaWire, SkinsRestorer, TagRegisterLib, Elytra, Tablist, CoreProtect, Autocrafter, Itemizer, WorldEdit, ClearLag, ArmorStandEditor, Votifier, ProtocolLib, LibsDisguises, MVdWPlaceholderAPI, ChopTree3, EchoPet, FeatherBoard, mcMMO, ActionAnnouncer, Tim, Vault, SalvageSmelter, SimpleSit, MCMMOXPBar, ChestShop, MobArena, ZHorse, ChestCommands, CraftBay, OpenInv, Essentials, AnimatedNames, XrayInformer, MarriageMaster, Jobs, mcMMOAction, TreasureChest, Citizens, EssentialsChat, MobBooks, EssentialsSpawn, SimpleTrading, Denizen, MobCommands, CompatNoCheatPlus, NoCheatPlus, Sentinel, Builder, AuthMe, HolographicDisplays, LeaderHeads, Shopkeepers, HolographicExtension, CombatIndicator, TouchscreenHolograms, Elementals

### Paper build number:
[Server] INFO This server is running Paper version git-Paper-1082 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Does this occur on Spigot and CraftBukkit as well?

**Comment by electronicboy** [comment]
Only noticed this until it was closed, but the EntityDamage... event is actually fired after the server has already set the entity on the fire. The EntityCombustByEntityEvent should cover that, as well as: ProjectileCollideEvent

**Comment by NicoNekoDev** [comment]
ProjectileCollideEvent? I didn't notice this event.

**Comment by electronicboy** [comment]
ProjectileCollideEvent was added to paper, if you want compat with Spigot/Craftbukkit, use the EntityCombustByEntityEvent and the damage event
