### ISSUE TITLE
Chunk sending floods netty queue delaying other packets

### ISSUE THREAD

**Issue by DominicDV** [PaperMC/Paper#674]
# Performance issue
On my machine, using waterfall and paper it takes (with plugins) from 25 up to 50 seconds from joining to being able to write in chat.  Using spigot and bungee it takes consistently 8 -10 seconds.  
When preloading the spawn it takes about this time till an ingame-picture is visible at all, but at least you can immedeately write. Disabling preloading the spawn results in roughly the same time from login to being able to write, although the time from loginscreen to first ingame-images are as good as with spigot- roughly 7-8 sec. Best value I got with spawn-preloading disabled was 10 sec from login to being able to write in chat, but I think the variable affects the total time behaviour.

**Without plugins** it is about 11-23 seconds with paper/waterfall and 7 seconds with spigot/bungeecord. 

Additional requirement to provoke this issue:  
Use a large view-distance (18), and a world with huge structures as mountains, which results in huge chunk-files , preload the spawn and make sure you get there when joining the server 

If you use a 'normal ' minecraft server with normal view-distance and normal landscape this performance issue is neglible. But when using common terrain-generators as for e.g. 'Epicworldgenerator' from which you get up to 5x larger chunkfiles, it becomes noticeable and quite annoying.

One interesting thing is, that there exists an equal difference in time when switching from waterfall to bungeecord and paper to spigot. Can it be that spigot/bungee uses platform-dependent optimization because it is complied on my machine?
The long loading time is a bug I know for at least a year, but I have tested it recently with the latest
paper version 1091 and waterfall build 106

**How to reproduce:**
load a world with some large structures 
use a huge view-distance (i tested distance: 18) 
make the spawn-chunks preloaded in paper.yml **and teleport yourself to the spawn- location.**

config.yml (waterfall)  https://pastebin.com/5L2bDGNB
spigot.yml    https://pastebin.com/jEEpyApS
paper.yml   https://pastebin.com/4LXhdphZ 
bukkit.yml  https://pastebin.com/ajpL6Wyg
server.properties  https://pastebin.com/4LXhdphZ

Plugins: none

My server
KVM virtualized Intel® Xeon® E5-2680V4 with 8 cores @2,4Ghz)
24 GB Ram 

My computer: 
some weak machine with integrated intel HD3000 graphics and 1GB ram used for Minecraft
Internet bandwith from computer: 1Mb/s average

**Comment by DominicDV** [comment]
found a related issue on waterfall: https://github.com/WaterfallMC/Waterfall/issues/123

**Comment by zachbr** [comment]
Does this occur with just Paper or Paper + Bungeecord? IE take waterfall out of the equation (and note that we do not maintain or develop waterfall, that's a separate group).

**Comment by DominicDV** [comment]
As far as I have tested, Paper + bungeecord, although it is only half as severe as paper + waterfall.
Will test it more thoroughly tonight with paper and paper + bungeecord.

**Comment by DominicDV** [comment]
After running many tests https://pastebin.com/twKRNWjY the initial statement that the Spigot join time is faster than Papers was proven false. In fact, the startup of paper seems to be faster. 
The initial deviation seems to originate from bandwith fluctuations from my wlan.
That being said, there is  the fact that when many chunks are preloaded, player with wlan can experience of up to 60s jointime. after that, everything is fine. It seems to be nothing specific to Paper, as Spigot shows the same behaviour.  Maybe it would be an interesting feature to have the option not to force-fed all loaded chunks in a given area to a client. Something like that an connection is estblished where the client can write, and then more chunks are loaded.

**Comment by DenWav** [comment]
I wouldn't close this yet, since even if it's not specific to Paper it's still a bug which should be fixed.

**Comment by aikar** [comment]
The issue stems from the fact that the chunk sends is flooding the netty queue with so much data, that you cant get chat response packets and such until all of that chunk data finishes being received.

We could try to rate limit chunk ticks in the player chunk map, and if X is already in queue, abort the load until the next tick to try again, staggering the load over more ticks.

**Comment by aikar** [comment]
This is now configurable by "max-chunk-sends-per-tick" world config.


Vanilla default is 81 chunks per world per tick. Reduce to limit how much chunks are sent per tick which is the only way we can solve this issue.
