### ISSUE TITLE
Server Crash every now and then - pls help!

### ISSUE THREAD

**Issue by bloggy** [PaperMC/Paper#675]
Crash Report:
https://hastebin.com/puxudababo.md

[17:30:56] [Server thread/INFO]: This server is running Paper version git-Paper-1081 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Can anybody help? I have removed Terrain Control which I thought was responsible for this. But it wasn't.

We have set our view distance to 4, maybe this could lead to problems? Chunk Iterator trying to check blocks that are in unloaded chunks etc?!

**Comment by zachbr** [comment]
Your server is lagging out, this isn't a bug in Paper.

The watchdog specifically points to ```me.lyria.lyriaskill.skills.battle.rogue.Kick.cast(Kick.java:36)``` eventually triggering chunk generation, but these watchdog reports are not always correct.

Not a ton of advice to give here other than that.

**Comment by bloggy** [comment]
Thanks for your reply!

Why should triggering chunk generation lead to crashes? If this leads to crashes then it IS a paper issue imho.
And how do you know that the server is lagging out?
The crash dump contains many information but we are unable to reproduce the crash with your mentioned line of code.

**Comment by electronicboy** [comment]
It's not specifically chunk generation that is the issue, it's the fact that that plugin is triggering an expensive operation in a way that it doesn't end within a reasonable amount of time, chunk generation is just really expensive which is the icing on the cake for when a plugin doesn't do something to limit its potential impact on the server.

and a watchdog system will only trigger when it hasn't been updated, which occurs every tick, a tick hasn't occurred in x amount of time and has thus triggered the watchdog to fire, indicating that the crash is becaused your server lagged out. (Generally 60 seconds by default from my recollection)
