### ISSUE TITLE
Enderman not attacking endermite

### ISSUE THREAD

**Issue by BoBkiNN** [PaperMC/Paper#6756]
### Expected behavior

Enderman not attack a endermite but this not happening

### Observed/Actual behavior

Enderman dont attack endermite and dont go to he

### Steps/models to reproduce

idk why this is occurred but i know that my exp farm is broken and i tried to rollback it using coreprotect but there were so many endermans and server stop responding. after that i deleted this chunk using Chunky and built it again but its dont work

### Plugin and Datapack List

Plugins (25): AuthMe, BetterSleeping3, ChatEmojis, CoreProtect, dynmap, Geyser-Spigot, GSit, HeadDrop*, InvSee*, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyCommand, PlaceholderAPI, PlayerReport, Playtimes*, PrivateMessages, SkinsRestorer, SurvivalInvisiframes, TAB, TimeManager, ViaVersion, WarningManager*, WorldEdit

There are 4 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/fast leaf decay v2.0.3.zip (world)], [file/dimension-detector-primland (world)]

### Paper version

This server is running Paper version git-Paper-788 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-574 (MC: 1.16.5)

**Comment by ZombieB1309** [comment]
Note that using /summon won't allow enderman to get angry at endermites, you must use an ender pearl

**Comment by e-im** [comment]
Can't reproduce, and this very likely isn't a paper bug. Please try without plugins or come by `#paper-help` on our [discord](https://discord.gg/papermc) for support with this.

**Comment by Hlebuw3k** [comment]
![image](https://user-images.githubusercontent.com/78320892/165878371-a3fecbc3-d3fe-4c95-b1bb-624e509d90cb.png)
happened to me. works absolutely perfectly in singleplayer (literally copy-pasted) sometimes enderman also dont aggro when looked at. is this some kind of aggro limit? To elaborate: on screenshot is shown enderman (on the right) not aggroing to an endermite (on the left) in a minecart. This works flawlessly in singpleplayer, and none of them stand still for more than a second. On a paper server, in contrast, the enderman just stand still like they are acting dumb. However, when the player moves away from the enderman by 6 blocks, (the player is normally bellow the endermite on the left, the screenshot was taken in spectator mode) most of them begin running towards the endermite, only the closest ones continuing to stand still. In this screenshot, after the player moved away 6 blocks, every single one began running towards the endermite. this is NOT a line of sight problem or anything to do with the farm design, as literally the EXACT same thing was copied and pasted into a singpleplayer world and worked without any flaws, without the player requiring to move any amount of blocks from the normal position. The endermite was obtained via ender pearls both on the paper server and in singleplayer. The Minecraft version is 1.18.2
