### ISSUE TITLE
TNT Does not do knockback to projectiles like arrows (Just like in vanilla minecraft).

### ISSUE THREAD

**Issue by Zxchk** [PaperMC/Paper#6770]
### Expected behavior

TNT explosions doing knockback to projectiles just like in Vanilla Minecraft.

### Observed/Actual behavior

TNT does not do knockback to arrows.

### Steps/models to reproduce

Arrows are launched into the air and are knocked by the TNT as a cannon like projectile. This involves timing the slimeblocks and tnt just right so that the tnt knocks the arrows forward when the arrows just reach the area infront of the tnt.

### Plugin and Datapack List

AAC5, AACAdditionPro, ChatItemDisplay, ClearLag, CoreProtect, dynmap*, ElytraDisabler*, EpicWorldGenerator, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, Factions, FastAsyncWorldEdit (WorldEdit), HolographicDisplays, InventoryRollback, LuckPerms, Multiverse-Core, OpenInv, PlaceholderAPI, ProtocolLib, StaffChat, SuperVanish, Sysinfo*, TAB, Vault, Vehicles, ViaBackwards, ViaVersion, WorldBorder, WorldEdit

### Paper version

[Server] INFO This server is running Paper version git-Paper-"e04368045" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Other

TNT just does 0 knockback to suspended or airborne projectiles and just completely fails to move them or alter their position.

**Comment by e-im** [comment]
Duplicate of #5429

**Comment by jpenilla** [comment]
duplicate of https://github.com/PaperMC/Paper/issues/5429

**Comment by Dominik192** [comment]
for some reason vanilla doesn't knockback arrows no more
