### ISSUE TITLE
please, Add cancellable (un)ban(ip) Events

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#678]
Hello. I think everything is clear from the title.
I don't understand why this is not done in a Spigot and I will be glad if at least you make it.

@Zbob750, so what do you think about my proposal to add beautiful explosions?

**Comment by mikroskeem** [comment]
> cancellable (un)ban(ip) Events

Well how those events would be useful?

**Comment by molor** [comment]
@mikroskeem, in my case, if several players with the same IP address is connected to the server, if I ban one of them by name, I need to perform some actions with other players connected from the same IP address.
I could do this using PlayerKickEvent, but the problem is that if I ban a player that is not on the server, I will not be able to perform these actions.

**Comment by molor** [comment]
Support for cancelling this event is not needed for me, but maybe it will be a nice bonus for other developers.
