### ISSUE TITLE
View Distance / No tick View Distance loads +1 additional layers of chunks

### ISSUE THREAD

**Issue by EterNityCH** [PaperMC/Paper#6784]
### Expected behavior

The formula for total chunk loaded is [(View Distance+2)x2 +1]^2

### Observed/Actual behavior

Paper loads one extra layer of chunks on all view distances.

### Steps/models to reproduce

For a view distance of 17 for a single player, a total of [(17+2)x2+1]^2= 1521 but 1681 is loaded.

If we solve the equation in reverse, we can work out that instead of +2 being applied initially, +3 is applied instead.

This holds true for all view distances / no-tick view distances

### Plugin and Datapack List

None.

### Paper version

Build 329

### Other

@Spottedleaf love you <3

**Comment by EterNityCH** [comment]
Fixed Engrish.

**Comment by Spottedleaf** [comment]
@EterNityCH stupid weeb

The problem is an issue from the remapping. Local parameter viewDistance was  changed to watchDistance, and the field viewDistance was read from ChunkMap - of course, viewDistance on ChunkMap is +1 of watchDistance.

**Comment by Spottedleaf** [comment]
Fixed by fc0e6c7e086876cce9676214e726a96dc1be209c
