### ISSUE TITLE
Issue with double chests

### ISSUE THREAD

**Issue by CW-UK** [PaperMC/Paper#6787]
### Expected behavior

For plugins to be able to access double chests correctly.

### Observed/Actual behavior

After updating from build 308 to 333 (via 328 which also has this issue), two plugins I use that interact with double chests are only able to access one half of the chest. The first plugin I use is [Deluxe Sellwands](https://www.spigotmc.org/resources/1-8-1-17-deluxesellwands-need-a-sellwands-plugin-look-no-further.74999/updates) and the other is [Upgradeable Hoppers](https://www.spigotmc.org/resources/upgradeable-hoppers-fast-hopper-plugin-link-containers-item-transfer-suction-filter-1-17-support.69201/updates).

I've reported the issue to the developers of both of the above plugins, and Norska (dev of Deluxe Sellwands) confirms the issue only happens with Paper and not the latest Spigot, so suggests that something has changed since 308.

Both of these issues began happening at exactly the same time after updating from 308. On build 308 these issues did not happen.

### Steps/models to reproduce

Using Deluxe Sellwands, you can only interact with (and sell items from) one half of a double chest at a time.
Using Upgradeable Hoppers, the hoppers can only fill/draw from one side of a double chest.

### Plugin and Datapack List

![Plugins](https://imgur.com/8xVP2da.png)

### Paper version

```
[15:28:50 INFO]: This server is running Paper version git-Paper-333 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c164452)
You are running the latest version
```

### Other

I have spoken to the developers of both plugins, Norska and Angeschossen and reported the issue with them as well, however nothing has changed with the way they access chest inventories.

**Comment by electronicboy** [comment]
Should be fixed with the next upstream update

**Comment by lynxplay** [comment]
Since 72a31751659eeff26349dfa687431da49a91ea64, chests now properly return the expected `CraftInventoryDoubleChest` inventory (even when partially blocked by blocks above).

If I somehow missed an issue in my testing, please leave a comment so we can investigate further :+1:
