### ISSUE TITLE
Bounding box for Villager Entity Activation uses waterActivationRange instead of villagerActivationRange

### ISSUE THREAD

**Issue by Hughp135** [PaperMC/Paper#6797]
### Expected behavior

Villagers should be activated when inside the range set in `world.spigotConfig.villagerActivationRange` around a player in every direction.

This config value is set in `spigot.yml` under `entity-activation-range.villagers`

### Observed/Actual behavior

Villagers are actually activated at the `world.spigotConfig.waterActivationRange` in the North/South direction.

Note: the E/W direction correctly uses the range for villagers. Only the N/S direction is effected

### Steps/models to reproduce

The code pretty much demonstrates the issue, which in my opinion was probably due to someone copy/pasting the line for water animals:

https://github.com/PaperMC/Paper/blob/master/patches/server/0364-Entity-Activation-Range-2.0.patch#L524

However, as I discovered this bug by actually testing it on a server, I will tell you how I reproduced it:

1) Edit `spigot.yml` and set `entity-activation-range.villagers` to 128, and `entity-activation-range.water` to 8. Also set `tick-inactive-villagers` to false, and `wake-up-inactive.villagers-max-per-tick` to 0, and `wake-up-inactive.villagers-every` to something high, and `wake-up-inactive.villagers-for` to 0, to reduce the chances of the villagers being activated by this.
2) In creative mode, create a line of beds with villagers on them, and set the time to night so they sleep.
3) Add a pillager in a minecart, which you will send towards the villagers from outside the activation range (villagers only wake up when activated).
4) Confirm that villagers wake up instantly when greater than 8 blocks away from the villagers in the East/West direciton, and they don't wake up instatly if you are the same distance away either north or south.

You can repeat the above steps but swapping the values of `villagers` and `water`, to see it happening in the opposite directions.

### Plugin and Datapack List

0 plugins

### Paper version

This server is running Tuinity version git-Tuinity-"4c31ea1" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4c31ea1 on HEAD)
You are running the latest version.

I know it's Tuinity and I'm sorry for not testing this on a paper only server, but since the bug presumably exists in the PaperMC code, I thought i'd make an issue here

**Comment by e-im** [comment]
Thank you for the detailed report, unrelated to your issue, however, please note that Tuinity has merged with Paper in 1.17.1 and is no longer receiving updates.
