### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by 1Pootis1** [PaperMC/Paper#6820]
### Expected behavior

an error randomly appears in the console, spam

### Observed/Actual behavior

randomly appear

### Steps/models to reproduce

randomly appear

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/73141732/138555407-6b9b3dba-3ffb-44db-8ffb-6719920b4e07.png)

### Paper version

[15:09:08 INFO]: Checking version, please wait...
[15:09:08 INFO]: This server is running Paper version git-Paper-276 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 1707c10)
You are 73 version(s) behind
Previous version: git-Tuinity-"9f3435b" (MC: 1.16.5)

### Other

![image](https://user-images.githubusercontent.com/73141732/138555390-0f0137ff-ce35-4343-8c48-6fd35cedb2ba.png)
![image](https://user-images.githubusercontent.com/73141732/138555452-d7ff29c5-9489-4559-9234-186f16967285.png)
![image](https://user-images.githubusercontent.com/73141732/138555466-89097406-ad96-4ee1-b75b-6ab567b55985.png)

**Comment by NotMyFault** [comment]
It would help if you a) update and b) provide the full log on a paste service like https://paste.gg/ instead of blurry screenshots from your console.

**Comment by NoahvdAa** [comment]
You are 73 paper versions behind, does this error still show up after updating?

**Comment by e-im** [comment]
Please visit our [discord](https://discord.gg/papermc) for support. The issue tracker isn't the best place and what you have provided is not clear.
