### ISSUE TITLE
On Startup 'Exception in thread "DefaultDispatcher-worker-2" java.lang.NoSuchMethodError:' in console

### ISSUE THREAD

**Issue by InvisibleOneL** [PaperMC/Paper#6822]
### Stack trace

[Sat, 23. Oct 2021 22:13:45 UTC WARN] Exception in thread "DefaultDispatcher-worker-2" java.lang.NoSuchMethodError: 'java.lang.Object kotlinx.coroutines.DelayKt.delay-VtjQ1oo(long, kotlin.coroutines.Continuation)'
[Sat, 23. Oct 2021 22:13:45 UTC WARN] at dev.kord.common.ratelimit.BucketRateLimiter.delayUntilNextInterval(BucketRateLimiter.kt:44)
[Sat, 23. Oct 2021 22:13:45 UTC WARN] at dev.kord.common.ratelimit.BucketRateLimiter.consume(BucketRateLimiter.kt:51)
[Sat, 23. Oct 2021 22:13:45 UTC WARN] at dev.kord.gateway.handler.HandshakeHandler$start$$inlined$on$4.invokeSuspend(Handler.kt:45)
[Sat, 23. Oct 2021 22:13:45 UTC WARN] at dev.kord.gateway.handler.HandshakeHandler$start$$inlined$on$4.invoke(Handler.kt)
[Sat, 23. Oct 2021 22:13:45 UTC WARN] at dev.kord.gateway.handler.HandshakeHandler$start$$inlined$on$4.invoke(Handler.kt)
[Sat, 23. Oct 2021 22:13:45 UTC WARN] at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:134)
[Sat, 23. Oct 2021 22:13:45 UTC WARN] at dev.kord.gateway.handler.HandshakeHandler$start$$inlined$on$3$2.emit(Collect.kt:137)
[Sat, 23. Oct 2021 22:13:45 UTC WARN] at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:341)
[Sat, 23. Oct 2021 22:13:45 UTC WARN] at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt)
[Sat, 23. Oct 2021 22:13:45 UTC WARN] at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[Sat, 23. Oct 2021 22:13:45 UTC WARN] at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[Sat, 23. Oct 2021 22:13:50 UTC WARN] at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[Sat, 23. Oct 2021 22:13:50 UTC WARN] at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[Sat, 23. Oct 2021 22:13:50 UTC WARN] at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[Sat, 23. Oct 2021 22:13:50 UTC WARN] at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

### Plugin and Datapack List

Plugins installed (126): AdvancedEnchantments, AdvancedPortals, AdvancedRegionMarket, AdvancedSets, ArtMap, AuctionHouse, BannerMaker, BedRegen, BetterBowTrails*, BetterConcrete, BetterRTP, BuildBattle, BuycraftX, ChatColor2, ChatManager, ChatReaction, ChestShop, ChestSort, Chunky, Citizens, CleanroomGenerator, ClearLag, ClueScrolls, CMILib, ColoredSigns, CommandNPC*, CoreProtect, CrateReloaded, CrateReloadedNPC*, DailyRewardsPlus, DeathMessages, DeluxeMenus, DeluxeTags*, Denizen, DiscordSRV, dynmap, EditableSign, eGlow, EntityTrackerFixer, EpicRename, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExecutableItems, FarmControl, FartherViewDistance, FastAsyncWorldEdit (WorldEdit), GadgetsMenu, GlobalBans, GlowAPI, Graves, GriefPrevention, GriefPreventionFlags, GSit, GUIShopSpawners, Harbor, HeadDatabase, HoloExtension, HolographicDisplays, HolographicExtension, IllegalStack, ImageMaps, Images, InvisibleItemFrames, Jobs, LagAssist, LeaderHeadsRevamped, LibsDisguises, LiteBans, Lottery, LuckPerms, LumberJack, MarriageMaster, mcMMO, MineableSpawners, Minepacks, MobArena, MorphRedeem, Multiverse-Core, MurderMystery, MyCommand, OldCombatMechanics, PacketListenerApi, PinataParty, PlaceholderAPI, Plan, PlayerParticles, PlayerVaults, PlayerWarps, PowerlessLamps*, ProtocolLib, ProtocolSupport, PvPManager, PyroFishingPro, PyroWelcomes, Rankup, RealisticSeasons, ResourceWorld, SafariNet, SCore, Scoreboard-revision*, ServerRestorer, SheepQuest, Spartan, SuperVanish, TAB, TempFly, Terra, TerraformGenerator, TicketManager, TimeIsMoney, TitleManager, TradeMe, TroddenPath, UltimateAutoRestart, UltimateStatistics, Vault, VentureChat, ViaVersion, VillageDefense, VoteParty, Votifier, VotingPlugin, WorldGuard

### Actions to reproduce (if known)

Updating from PaperMC 1.17.1 #283 to PaperMC 1.17.1 #349

### Paper version

PaperMC 1.17.1 #349

### Other

Occurred after updating PaperMC to latest (#349) from #283. Server works as normal it seems, just the exception that appears in the console during startup. Have now reverted back to #283 and the issue doesn't show up in the console.

**Comment by NotMyFault** [comment]
You have some plugin shading kordlib but not relocating it, sooo we can only guess where it's coming from based on the information you provided.
Please use our [discord](https://discord.gg/papermc) for general mc support. The issue tracker isn't the best place for such unclear issues.

**Comment by lynxplay** [comment]
This error, at least after a few stackoverflow searches seems to be related to kotlin runtime and kotlin compile/transpile differences ([see here](https://stackoverflow.com/questions/67533916/why-is-kotlin-function-name-being-mangled-when-passing-duration/67534171#67534171)).

(also sulu is just too fast)
