### ISSUE TITLE
negative fishing times

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6824]
### Expected behavior

if you have a rod with high lure, or make the fishing times in paper.yml low then you should be able to catch fish

### Observed/Actual behavior

the calculation for fishing time can go negative, causing the fish to never come, this can be from having high lure or changing fishing settings.

FishHook.java
  this.timeUntilLured = Mth.nextInt(this.random, this.minWaitTime, this.maxWaitTime);
  this.timeUntilLured -= (this.applyLure) ? this.lureSpeed * 20 * 5 : 0;

### Steps/models to reproduce

Fishing rod with above vanilla lure  or changing settings in paper.yml or both at once

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-"9472d38" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9472d38)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-"30681cc" (MC: 1.17.1)

**Comment by NoahvdAa** [comment]
According to [the wiki](https://minecraft.fandom.com/wiki/Fishing#Mechanics), this could be considered an intentional game mechanic.
> [...] reduced by 5 seconds per Lure level. The Lure enchantment affects both the minimum and maximum time. If it causes the wait time to be less than 0, a new wait time is generated in the next tick. [...]

EDIT: Would making a config option that prevents negative lure time be a good idea?
