### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by rentexgfx** [PaperMC/Paper#6827]
### Stack trace

```
https://paste.gg/p/anonymous/37c239286c68430e812c7e7b50ce092a
```

### Plugin and Datapack List

https://i.imgur.com/8bzCYDv.png
I can't copy names so here is an screenshot.

### Actions to reproduce (if known)

It happens on startup or random.

### Paper version

This server is running Paper version git-Paper-790 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) (Git: 9472d38)
You are running the latest version
Previous version: git-Paper-790 (MC: 1.16.5)

### Other

i7-4790k 
Using garbage collector by aikar

Allocated 15GB of ram, in startup defined 14GB so 1gb is "free"?
soyoustart dedicated

**Comment by electronicboy** [comment]
1.16.5 is no longer supported, your JVM was stalling in an odd manner too
