### ISSUE TITLE
scary red memory leak

### ISSUE THREAD

**Issue by rentexgfx** [PaperMC/Paper#6840]
### Stack trace

```
https://paste.gg/p/anonymous/e1ad00c749004f44bd8fb10e53cee617
```

### Plugin and Datapack List

Plugins (14): CleanMotD*, CoreProtect, FarmLimiter, LiteBans, LoginSecurity*, LuckPerms, PlaceholderAPI, SkinsRestorer, StaffPlus, TAB, UltimateAutoRestart, UltimateTimber, VillagerOptimiser, WhitelistPlayers

Datapacks (4): Cauldron Concrete, Multiplayer Sleep, PK-Anti Creeper Grief, UnlockAllRecipes.

### Actions to reproduce (if known)

random, when  I'm not expecting.

### Paper version

[06:51:57 INFO]: Checking version, please wait...
[06:51:57 INFO]: This server is running Paper version git-Paper-353 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f2cb9cb)
You are running the latest version

### Other

i7-4790k
5GB in startup parameters, 6GB allocated by docker
soyoustart dedicated

**Comment by electronicboy** [comment]
That's not a memory leak, you likely hit a thread limit or something, if using ptero, check the wings configuration, otherwise, generally ulimits; otherwise, something is spewing threads out, take a look at a jmap, etc
