### ISSUE TITLE
[Please] Add ability to use display names instead of usernames with suggest-player-names-when-null-tab-completions

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#6843]
### Is your feature request related to a problem?

If player has a custom display name changed by one plugin, some another plugins that not have `onTabComplete` handlers and/or just returns `null` instead, can reveal real player names by just pressing a [Tab] after typing of any plugin's command.

### Describe the solution you'd like.

Add `use-display-names-in-tab-completions` or something similar to replace usernames with display names.

### Describe alternatives you've considered.

1/ Rewrite any plugin that doesn't have onTabComplete handler..
2/ Set `suggest-player-names-when-null-tab-completions` to false and lose the convenience
3/ Listen to tab complete packet and replace usernames in it
To be continued..

**Comment by electronicboy** [comment]
Not viable, yea, we can switch it but then you're breaking literally every plugin relying on this typical behaviour of player names being player names; Plugins should just implement their own completions
