### ISSUE TITLE
Strange crashes mentioning PaperLightingQueue$LightingQueue

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#688]
Hi, I just wanted to know if the new "Lighting-Queue.patch" was designed to deal with crashes like the ones I've recently been experiencing on build 1095. In all of these crashes I have the "queue-light-updates: false" and can't really see why the server is crashing.

Crash 1: https://hastebin.com/ovubehecuz.md
Crash 2: https://hastebin.com/atamehiqat.md
Crash 3: https://hastebin.com/osocelesiw.md

**Comment by zachbr** [comment]
Those are not traditional crashes, they are your server lagging out. If the watchdog detects that the server thread has been stuck on a single operation for too long, it will kill the server. When it does this it will dump the stacktraces of all threads. The one we generally care most about is the server thread.

It is not uncommon for these stacktraces to be inaccurate, however it's also not uncommon for them to be correct. Ultimately what you have is a lag issue.

If they are correct, chunk lighting is pushing your server over that threshold which results in watchdog detecting your server as completely lagged out.

If it isn't correct, another heavy operation may be ongoing on the main thread, and the next item up on the main thread is chunk lighting, which is a fairly regular occurrence on most servers.

The lighting queue patch queues chunk lighting updates until the end of the tick and then runs them when able. It could very well help with these issues, but if there's never any free time in the tick, it could also just get starved. In which case, all lighting updates wouldn't occur until the chunk is unloaded anyway.

So it might help, but it also might not.

**Comment by SecretlyJealous** [comment]
Would setting the timeout time to something lower give a more useful crash report?

**Comment by zachbr** [comment]
Not necessarily, the only thing it'd guarantee is that your server will kill itself faster when lagging.

**Comment by SecretlyJealous** [comment]
If lighting does happen to be the issue and I've tried using the lighting queue option but the server still crashes, what's the best solution? I can't really see what I can do about lighting.

**Comment by zachbr** [comment]
Assuming lighting is your issue, which again we cannot with this data, you would have to lessen the impact of updating it.

Most of the time, there's not much you can do about it. However, if a few players are making massive redstone contraptions they can contribute.

But again, none of the data presented here is enough to make that determination.

**Comment by SecretlyJealous** [comment]
I've taken a timings with 200 players on: https://timings.aikar.co/?id=52a5dd2fe4124ba8b11403275138250e

At the moment I see the lighting queue and chunk unloading being an issue but the TPS is fine. Should I take a timings report when a lot more players are on to be able to determine the cause? I was assuming that if the crashes were related to lighting then timings wouldn't really show that info.

Btw, I wanted to see if I would get this crash running regular spigot and I got something similar: https://hastebin.com/budopegero.md
But it doesn't seem to mention lighting unless I'm reading it wrong, if it doesn't mention lighting then is there a different issue going on?

**Comment by electronicboy** [comment]
3 minutes of timings is hardly enough to see what is going on, but can't really see those being all too much of an issue. chunk unloading already is somewhat slow, but the number of times it's actually caused a lag isn't really much of a concern.

The light proccessing queue is also limited to ticking for 45ms for loaded chunks, however; on chunk unloads looks like the whole queue is proccessed without any time restrictions. Not really sure what the advice here is, but it would stand to reason that there is the potential for somebody to queue an asston of light updates which would be proccessed all in one go. This is also somewhat a potentially hot area too, which considering the potential for plugins to do stupid stuff like update check on the main thread, stands to reason that in certain causes, that area can flag up quite easily

**Comment by SecretlyJealous** [comment]
The crash I got when running normal spigot doesn't mention lighting though: https://hastebin.com/budopegero.md so maybe it's not related to lighting? Here's the timings report with around 250 players online: https://timings.aikar.co/?id=43b584bfc3224b78834e9e16c8f24be9 - lighting queue doesn't seem that bad in this report but chunk saving/unloading is showing up high as usual but TPS is fine at 20.

**Comment by electronicboy** [comment]
Your crashes are both located in ticking blocks, either something is occuring before that that pushes it over, or you're somehow ticking a lot of blocks, which I'd be more inclined on the former unless you actually have people loading up a lot of blocks that tick, e.g. redstone

**Comment by SecretlyJealous** [comment]
The majority of redstone items are banned on my server and I also have a redstone tick limiter so I think you're right in the sense that it is likely to be something that is taking place which pushes it over. If I was to automate timings every 3 minutes and the server was to crash, would the most recent timings carry information on the cause?

**Comment by electronicboy** [comment]
Only thing you'd be guaranteed to do is tick off Aikar, if it's just a single tick that the issue occurs on, you'd also stand no chance of it appearing in timings other than upping the timeout and seeing if it shows up on timings as something like a plugin taking a fair chunk of time

**Comment by SecretlyJealous** [comment]
Okay so I guess the only thing I can do is increase the timeout time from 20 to 60 and report back with my findings?
