### ISSUE TITLE
Creeper Lingering Effect Option

### ISSUE THREAD

**Issue by UltraFaceguy** [PaperMC/Paper#689]
I'd like to suggest/request an event or config option to disable the lingering effect from creepers. Right now, they're an absolute chore.

https://hub.spigotmc.org/jira/browse/SPIGOT-3102

**Comment by electronicboy** [comment]
I keep considering creating a PR for this as a configurable option, as I could do with this myself (and it would likely end up on a custom fork if I didn't PR it here anyways), only question is "what should I call the option" ;P

I could also theoretically add an event, however, I feel that the configuration itself is more than enough for most use cases, unless there was some reason and somebody actually wanted it, the work would be somewhat wasteful

**Comment by UltraFaceguy** [comment]
disable-creeper-lingering-effect I guess?

And yeah, the event is the ""better"" option, but honestly every case I can even think of where somebody is going to need it disabled, they'll need it disabled across the board. So you do you ;D

**Comment by electronicboy** [comment]
Closing, PR implementing a configuration option was merged a good while ago.
