### ISSUE TITLE
BlockLeaves getType eating ~82% of all block ticking.

### ISSUE THREAD

**Issue by NachtRaben** [PaperMC/Paper#69]
OS: Linux Debian 7 x64 (Up to latest updates)
Java: Latest
Processor: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
JVM args: -Xmx32G -Xms1G -XX:+UseG1GC -XX:+UseStringDeduplication
Jar: PaperSpigot, Build 465. Latest at the time.

Did some profiling to see where the server was having trouble keeping up.
Only plugin listening to the decay event is worldguard, and it only cancels it. No extra processing beyond that.

Note: This was taken with jProfiler with a 20ms sample time, for 20 minutes.

![timings](https://cloud.githubusercontent.com/assets/4164436/13625497/63acf8a8-e586-11e5-920c-eb975d467fd4.png)

**Comment by zachbr** [comment]
Is this issue still relevant? Getting better, getting worse? Please test on latest and let us know.

**Comment by NachtRaben** [comment]
We straight up replaced the BlockLeaves instance when the server started and disabled all event calls for leaves, but I shall get this retested with the latest and get back to you.

Will test today after most kids get out of school and are on the network. Feels improper to test it at 5am and 20 people on.

**Comment by NachtRaben** [comment]
![10min 10ms sample 60 players](https://cloud.githubusercontent.com/assets/4164436/13713947/8f9699c8-e799-11e5-9597-56f4666003a9.png)

Still relevant, but not its not the event calls taking up all the processing time. No idea what is the underlying cause now. In the loaded chunks on this server there are over 200k+ leaves(Guessing, It is alot and map is a bit too large to transfer and run an mcedit count on, WE would crash iterating through the loaded area.)

**Comment by SecretlyJealous** [comment]
Interesting, you seem to be having a similar issue to me but the only difference is that I'm having trouble with Grass Block: https://github.com/PaperMC/Paper/issues/54

**Comment by NachtRaben** [comment]
Rebumping this due to inactivity, reattached below are the latest timings. This is with the latest Paper #556 with 60+ players online. Reiterating that we are not doing anything special pertaining to leaves in plugins, entirely vanilla handling.

![meow](https://cloud.githubusercontent.com/assets/4164436/13995250/c9d3e73a-f0fe-11e5-8012-7cf741f04ce9.png)

**Comment by zachbr** [comment]
This should no longer be forcing chunks to load, which was the root issue in this ticket. Should be long since resolved.
