### ISSUE TITLE
Paper 1.12 Pre 2!! Spigot released 1.12 pre 2!!

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#694]
:) Please update i wanna reset my server for the 1.12 pre 2

**Comment by MiniDigger** [comment]
just because spigot decided to release snapshot releases which are mostly unstable doesn't mean that paper needs to do it. 
we are all aware that spigot did that and a looking at the changes, but don't take it for granted that the paper team will release a snapshot build.
