### ISSUE TITLE
Server Crash: Exception in server tick loop

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#695]
Paper 1094, no noteworthy plugins. First crash in a month.

Crash log:
https://pastebin.com/tm2X8NTj

What caused it?

**Comment by electronicboy** [comment]
```
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
```
You likely have a plugin that is modifying the world async

**Comment by hurrgurl** [comment]
-edit-

Thank you. Found out what it was. I effed up... nothing to do with paper, it was on my part.

Fixed now. :)
