### ISSUE TITLE
Timings paste crashed server

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#697]
Paper Build: 1102
Crash report: https://hastebin.com/totulenera.sm
Log: https://hastebin.com/emupoxogud.vbs

Not sure why but when I did /timings paste the server crashed, I used it a few times before the crash and it seemed to work fine so I'm not sure why it freaked out.

**Comment by zachbr** [comment]
Is this something you're able to reproduce or was this just a one off oddity? (So we can properly prioritize)

**Comment by SecretlyJealous** [comment]
So far it seems like it was a one off but I've only been using the timings feature for one day. I'll see how it goes from now and report back if it happens again.

**Comment by aikar** [comment]
Sadly also nothing useful in those reports

**Comment by zachbr** [comment]
Closing in favor of #712 which is likely the cause of this, but has more info.
