### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by sgdc3** [PaperMC/Paper#698]
### Link/paste of stack trace
https://pastebin.com/6XZhV9En

### Plugin list:
`Plugins: CrazyCrates, InstantHit, PlugMan, AutoSort, MinecraftItaliaRewards, AutoFiller, LagMonitor, HideStream, CoreProtect, WorldEdit, Replicator, WorldBorder, BuycraftX, ActionHealth, ProtocolLib, Multiverse-Core, NoCheatPlus, LibsDisguises, Shopkeepers, KitPreview, PermissionsEx, FeatherBoard, Vault, ProtocolSupport, ColoredAnvils, TabListReloaded, SimpleRename, HolographicDisplays, WorldGuard, GenerousMobs, MythicMobs, Essentials, LiteBans, EssentialsChat, CraftBook, WGCustomFlags, ArmorStandTools, EnchantsPlus, ObsidianAuctions, CMI, Factions, MythicArtifacts, LockettePro, ServerSigns, EssentialsSpawn, PvPManager, TitleManager, FBasics, ObsidianDestroyer
`
### Paper build number:
git-Paper-1102

**Comment by sgdc3** [comment]
Any help? My server crashes 1/2 times per day with such thread dump..

**Comment by electronicboy** [comment]
The crash report that you've dropped is somewhat unreliable, we have a snapshot of the thread at a certain point, the major cause of crashes in those areas are caused by getCubes having been called with a large value to due a player moving too fast and in general the server having a lot of work to do.

That is also a very hot area and one of the many areas that watchdog may just eventually crap out at easily because of something that happened previously in the tick. e.g. plugins are all allowed to run their tasks at the beginning of a tick

**Comment by sgdc3** [comment]
Ok, any idea how to find out the real cause? Now i downgraded to and older TacoSpigot build, let's see if the problem persists (it was fine some weeks ago).

**Comment by electronicboy** [comment]
General case is to keep your eye on timings and see if there are any anomalies, e.g. plugins/other tasks using excessive amounts of time, especially those that seem to use more and more time as the server is running, as well as attempt to limit the potential for a player to be moving around the map at excessive speeds

**Comment by sgdc3** [comment]
>limit the potential for a player to be moving around the map at excessive speeds

How?

**Comment by sgdc3** [comment]
It crashed again, i'll post some timings asap

**Comment by sgdc3** [comment]
I'm now using latest paper build (git-Paper-1104)

**Comment by sgdc3** [comment]
https://timings.aikar.co/?id=b6d152b416e9496abcbccc2028a7da96

I'll post some longer reports later.

**Comment by sgdc3** [comment]
Longer timings: https://timings.aikar.co/?id=a5eb55c614074f4ba45ab9b44692d5d8

**Comment by sgdc3** [comment]
Today it crashed 8 times ._. Always the same thread dump.

**Comment by electronicboy** [comment]
As I've said, It's likely a player moving around too fast, there isn't all too much we can do. a plugin like NCP might help with attempting to catch out a player who is moving too fast, be weary of having users who have access to commands like /speed that would allow them to travel around at excessive speeds.

**Comment by sgdc3** [comment]
I already use latest build of NCP and in spigot.yml i limited the max entity movement speed to 15 (instead of 2048)

**Comment by sgdc3** [comment]
I just created a plugin using protocollib that logs in console when a player moves by 20 blocks or more in a single packet.

**Comment by sgdc3** [comment]
Another crash (different thread dump: https://hastebin.com/eneboqupuc.md)

**Comment by sgdc3** [comment]
~~Latest MythicMobs build fixed the issue.~~

**Comment by sgdc3** [comment]
It crashed again....

**Comment by zachbr** [comment]
Does removing MythicMobs resolve the issue?

**Comment by sgdc3** [comment]
Yeah, it seems that spigot is missing a NaN velocity check... I'm currently testing a custom build with a check, i'll let you know.

**Comment by PhanaticD** [comment]
i had the same NaN velocity crash with another plugin few months ago, might be worth adding a check in paper?

**Comment by zachbr** [comment]
Paper will warn for this in watchdog crashes as of 1.12.
