### ISSUE TITLE
Restart command not running the batch file until the batch closes

### ISSUE THREAD

**Issue by Articdive** [PaperMC/Paper#699]
Timings or Profile link: I doubt a timing will help you in this situation, however if u would like one then please comment below

**Description of issue:** when a person uses the command /restart from the console or In-Game it will get stuck on saving chunks until you type /stop in the console or "stop" since the slash doesnt work in the console and then it will run the restart script.

**Spigot, Paper, ServerProperties, Bukkit Config:** https://hastebin.com/ixejaqazer.sql

Paper build number: git-Paper-1103 (MC: 1.11.2) (Imeplementing API version 1.11.2-R0.1-SNAPSHOT)

 **What behaviour is expected:** the server to restart

**What behaviour is observed:** the server doesnt restart until you type stop into the console for it to close, 

 **Steps/models to reproduce:** type /restart and this will happen: https://gyazo.com/50305a723361a3667d4a6eb71ff4a072 it stops at saving chunks then if one does type stop into the console it closes, and the script starts

**Plugin list:**
-BuyCraftX
-EssentialsX-2.0.1
-EssentialsXSpawn-2.0.1
-LuckPerms-Bukkit-3.1.45
-ProtocolLib
-Questioner
-ServerListPlus-3.4.7-Universal
-Towny
-TownyChat
-TownyNameUpdater
-Vault
-WorldBorder
-WorldEdit-bukkit-6.1.5
-WorldGuard-6.2

**Actions to reproduce (if known):** type /restart and make the spigot.yml restart script: /something.bat

**Comment by electronicboy** [comment]
I've PR'd a fix to master, which will need porting over to 1.12, however looks like a System.exit call ended up losing it's way while cleaning up that class and some off the odd behaviors
