### ISSUE TITLE
Book Crash fixed?

### ISSUE THREAD

**Issue by xxyeniz** [PaperMC/Paper#701]
So, it looks like there's a guy with some sort of crash on my server, looking through the Logs I found stuff that lead me to books, I quickly googled and found this:

https://www.spigotmc.org/threads/hacked-client-that-freezes-server.235060/#post-2372858

And I'm wondering if this is fixed or will be fixed in a future version.

I'm using "1.8.8 = 443" currently.

**Comment by electronicboy** [comment]
That issue has been fixed in the latest version of paper. There was also a plugin somewhere that will attempt to deal with the issue for those running outdated versions, but you're on your own with that.

**Comment by xxyeniz** [comment]
Dang, okay, thanks for the quick answer.
