### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ItzAntony** [PaperMC/Paper#702]
Latest Build - Updated today
[crash-2017-05-21_13.43.18-server.txt](https://github.com/PaperMC/Paper/files/1017204/crash-2017-05-21_13.43.18-server.txt)

When a user logs in the server crashes.

**Comment by electronicboy** [comment]
~~Running: CraftBukkit version git-Spigot-7d78b81-a867313 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) true
You're running Spigot, not Paper.~~

**Comment by electronicboy** [comment]
Nvm, I somehow apparently had the wrong log file open....

**Comment by Spottedleaf** [comment]
Paper version git-Paper-1104 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Does this happen when anybody logs in? can you replicate this without plugins?

**Comment by ItzAntony** [comment]
There are a couple of users that triggers it.

https://gyazo.com/2ba44e3d0f67d9a3b085189438525d59
Thats a plugin list.

**Comment by electronicboy** [comment]
"Can you replicate this without plugins?" - I mean, remove your plugins from the server and see if you can cause that issue to occur again;

what version of paper did you update from?

**Comment by PhanaticD** [comment]
you might need to make a selection of the area (from a different location!) with worldedit and replace chests with air within view distance of that players login location

**Comment by zachbr** [comment]
If you still see this under 1.12, please let us know. Maybe with a copy of the map region as well.
