### ISSUE TITLE
Chunk Crash? Crash Report SkyBlock Server

### ISSUE THREAD

**Issue by StevenAVC** [PaperMC/Paper#703]
I have a SkyBlock server and spend some time and the server reboots and restarts until I have to go to stope it, I found this error that gives me the paperspigot, check all my plugins and they are well there is no plugin that of no error.

I use paperspigot 1.8.8:
[crash-2017-05-21-4-server.txt](https://github.com/PaperMC/Paper/files/1017374/crash-2017-05-21-4-server.txt)

**Comment by mikroskeem** [comment]
We do not support old versions.

**Comment by StevenAVC** [comment]
What could I do to fix it?

**Comment by electronicboy** [comment]
Check timings, watchdog errors are only thrown when a tick takes too long to process, which is generally down to plugins (however, 99% of cases, watchdog just happens to miss the issue, causing it to not be triggered at the correct time to pinpoint the plugin)

**Comment by TrizzerArts** [comment]
How can I check the timings?

**Comment by TrizzerArts** [comment]
This is the timings: https://timings.aikar.co/?id=793e073aa580463e8a4d1a6a01c65676
