### ISSUE TITLE
Crash on chunk.

### ISSUE THREAD

**Issue by pisaiah** [PaperMC/Paper#706]
# Crash, Stacktrace

### Link/paste of stack trace
https://pastebin.com/QeMmPyJN

### Plugin list:
https://pastebin.com/UKSvgpg8

### Actions to reproduce (if known):
none, just crashes

### Paper build number:
This server is running Paper version git-Paper-1104 (MC: 1.11.2)

**Comment by electronicboy** [comment]
the crash report just appears that the server took too long to tick, general causation of this is due to plugins taking too long to do something which causes the watchdog to tick over the maximum allowed time for a tick and to crash.
