### ISSUE TITLE
PlayerMoveEvent Addons

### ISSUE THREAD

**Issue by aamber2231** [PaperMC/Paper#7067]
### Is your feature request related to a problem?

Nope. i just think it would be easier for developers to check if a player is moving or rotating.

### Describe the solution you'd like.

I'd like for PlayerMoveEvent to have types. such as an enum that has ROTATING or MOVING. I think this would really be useful for developers trying to check if rotating or moving.

### Describe alternatives you've considered.

I've tried using packets but they aren't accurate. (for me at least)

### Other

Thats it.

**Comment by drunderscore** [comment]
You can do this without packets?
Just compare the to and from pitch and yaw. if it hasn't changed, then it's movement. Otherwise it's rotation or both.

Still a good helper though.

**Comment by Rollczi** [comment]
`getFrom()` `getTo()`
you can check cords x y z
`to != from` -> MOVING and optional ROTATING (you can check yaw and pitch)
`to == from` -> ROTATING

**Comment by aamber2231** [comment]
It's mostly for simplicty.

**Comment by e-im** [comment]
I'm not going to outright close this, and I see what you're trying to do here, but it seems pretty meh. To be honest, I don't really see the point at all as you can [already do this](https://papermc.io/javadocs/paper/1.18/org/bukkit/event/player/PlayerMoveEvent.html)

**Comment by tomcraft** [comment]
PlayerMoveEvent already have methods to determine what kind of move is made.

**Comment by e-im** [comment]
yeah this really does not make sense
