### ISSUE TITLE
Glow Squids spawn in odd environements. 

### ISSUE THREAD

**Issue by casperwtf** [PaperMC/Paper#7070]
### Expected behavior

Glow Squids would not randomly spawn 4-5 at a time in village farm water. 

### Observed/Actual behavior

Glow Squids spawn 4-5 at a time in village farm water. 

### Steps/models to reproduce

Create a superflat world.
Find a village with a farm.
Leave the area to allow mobs to spawn.
Come back and ~4/5 Glow Squid's will spawn in a villages farm's water.

### Plugin and Datapack List

None

### Paper version

Build #65

This server is running Paper version git-Paper-65 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 4e355c4)

### Other

Users in the discord suggested that it could be due to a light bug, I placed torches all around the water area and repeated the steps with them being successful.

**Comment by Tsoccerguy3** [comment]
Try build 1.18.1 build 68 https://papermc.io/downloads . if this fixes the issue , please close

**Comment by lynxplay** [comment]
While I can replicate this, this is to be expected. The 1.18 release changed the spawning conditions for a bunch of entities, including the glow squid spawning rules (outlined in https://minecraft.fandom.com/wiki/Java_Edition_21w40a#Mobs).

Glow Squids now simply spawn water under the worlds sea level - 33 blocks, which matches the low water y coords in a flat world.

This hence works as expected according to current vanilla spawning rules.
