### ISSUE TITLE
Random server crashes.

### ISSUE THREAD

**Issue by StefvanderMeer** [PaperMC/Paper#708]
**Link/paste of stack trace**
Console message:
https://pastebin.com/DjdTE47X
Console log message:
https://pastebin.com/X5EgeZyy

**Plugin list:**
http://imgur.com/a/yoKuV
http://imgur.com/a/ylbgS

**Actions to reproduce (if known):**
The server just randomly crashes a few times a week due that console message. When the server crashes the console just stops and ends with the first pastebin. You need to click stop on multicraft to get the server offline because the console is frozen and all players got already disconnected with the default server went offline message. Then in the log of the server a different message is shown in the second pastebin. I have no idea what it causes.

**Paper build number:**
http://imgur.com/a/GEQfV

**Comment by zachbr** [comment]
1.8.8 is not supported. Use an updated version.
