### ISSUE TITLE
Failed connection to server

### ISSUE THREAD

**Issue by witoszekdev** [PaperMC/Paper#709]
### Description of issue:
Can't connect to server

Crash report: https://gist.github.com/taniotanio7/2c8bfc2957bd29414fc1a36f596f61bd

### Plugin list:
LuckPerms, TitleAdvanced, WorldEdit, CapAFK, EasyBackup, SkinsRestorer, Friends3_0, SuperTrails, VoidGenerator, Reloader, CustomHelp, ViaVersion, Vault, Essentials, CutePortals, ProtocolLib, EssentialsProtect, React, EssentialsChat, EssentialsAntiBuild, SuperVanish, EssentialsSpawn, FastLogin, AuthMe

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml: https://gist.github.com/taniotanio7/a60e3b147118f880d8cc480e7524f1c2
spigot.yml: https://gist.github.com/taniotanio7/37738cd64b9a10f8595b54f08cb7299f
paper.yml: https://gist.github.com/taniotanio7/8b15f338a697ebce3f983af3c5dca3ba
server.properties: https://gist.github.com/taniotanio7/2fa109fd53479ba64c13c33a026278ed

### Other helpful links
This is the disconection message I get: https://goo.gl/oY2bjO

### Paper build number:
Latest.
Paper version git-Paper-"04d2d385" (MC: 1.12-pre6) (Implementing API version 1.12-pre6-SNAPSHOT)

**Comment by electronicboy** [comment]
Your issue is caused by ProtocolLib, most likely being outdated.

**Comment by witoszekdev** [comment]
Yup, it fixed the problem. I updated it on every server, except on this one...
Thanks! 😄
