### ISSUE TITLE
Unexpected crashing from 20tps to 0

### ISSUE THREAD

**Issue by RoyalRaid** [PaperMC/Paper#710]
Im having a issue with my server, It seems to go from 20tps with everything stable then out of nowhere it drops to 0 and server crashes. Players are still online but cant type any commands. I managed to find this in the logs just before the crash happened. Not sure if it helps or not

https://pastebin.com/ACVt8aFj

A simple server restart fixes the issue but then it arises again hours later.

This is my current version of PaaperSpigot: 
![image](https://cloud.githubusercontent.com/assets/19232463/26757057/0d78b698-48f4-11e7-8921-aca7ce04fcda.png)

If i could get any assistance it would be greatly appreicated. Thanks!

**Comment by electronicboy** [comment]
From the report it looks like a player is flying too fast, but those types
of report aren't guaranteed to be accurate due to how they work , as well
as the potential of stupid plugins doing stupid things. Beyond that, we
don't support outdated software.

**Comment by RoyalRaid** [comment]
using latest version and still having the issue
Just happened then: https://pastebin.com/AQbYXbaL

**Comment by electronicboy** [comment]
That's still 1.8.8. there is very little that we can do beyond suggesting that you check your plugins to see if they're causing it, or check with people who are able to fly on the server to watch their speed.
