### ISSUE TITLE
PaperMC Problem (Very Bad patch)

### ISSUE THREAD

**Issue by DIDIRUS4** [PaperMC/Paper#7139]
### Timings or Profile link

No plugins and datapacks (Default MC with PaperMC)

### Description of issue

I personally find this patch as useless as possible. For some reason, you limited the kernels at the code level, without even providing functions to manage this from the Paper.yml configs. Now, because of this patch, my server began to crash and lag, because it does not use all my cores / threads for the game, but ONLY 1 thread (judging by the monitoring of top and htop)

### Plugin and Datapack List

No plugins and datapacks (Default MC with PaperMC)

### Server config files

Default server

### Paper version

Latest for 18.Dec.2021

### Other

https://github.com/PaperMC/Paper/blob/master/patches/server/0783-Reduce-worldgen-thread-worker-count-for-low-core-cou.patch

**Comment by jpenilla** [comment]
Use the `Paper.WorkerThreadCount` property to override the worker count, do know that there are very good reasons we make this change however

**Comment by DIDIRUS4** [comment]
Okay, thx
