### ISSUE TITLE
Regular TPS Drops after 20+ Hours of Uptime

### ISSUE THREAD

**Issue by uf0h** [PaperMC/Paper#714]
Server TPS drops after 20+ Hours of Uptime - Haven't been able to pinpoint the issue.

https://timings.aikar.co/?id=e62b7cd86a904ba194b9fc0f6b92f2e3

The following timings report was taken as the TPS dipped below 15.

We are on out 15th Map, this has never happened before. Our Hardware is top-of-the-line and should be sufficient enough to maintain a high TPS as it has in the past.

This happens regularly and I haven't been able to pinpoint the cause of the TPS Drops. I have to restart the server - which fixes the TPS.

Any help would be appreciated.

(Timings report shows - Plugins list as well as Build Number)

**Comment by zachbr** [comment]
Update to a supported version. We do not support 1.8.8 in any capacity.
