### ISSUE TITLE
Weeping Vines crashes server

### ISSUE THREAD

**Issue by NotAlexNoyle** [PaperMC/Paper#7143]
### Stack trace

Crash 1 https://sentry.io/share/issue/f686b93d0eb7499c8a23421ce235fdac/

Crash 2 https://sentry.io/share/issue/1b7e85309fd4415cb3e2e406945bc9b0/

### Plugin and Datapack List

Plugins (37): AdvancedRegionMarket, ArmShopBridge, Celeste, ClearLag, CoreProtect, DiamondBank, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), HolographicDisplays, HorseTpWithMe, KeepDeathDrop, LuckPerms, NBTAPI, NewbsCreative, NoCheatPlus, NoClip*, NoNetherRoof, OldCombatMechanics, OpenInv, Parties, PetMaster, PlaceholderAPI, Playtimes*, ProtocolLib, QuickShop, ServerSigns, TitleManager, Vault, ViaBackwards, ViaPotions, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, WorldGuard

### Actions to reproduce (if known)

Be in the same chunk as weeping vines

### Paper version

[21:03:54 INFO]: This server is running Pufferfish version git-Pufferfish-8 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 844cccb on HEAD)
[21:03:54 INFO]: Received invalid status code (404) from server.
[21:03:54 INFO]: Previous version: git-Pufferfish-7 (MC: 1.17.1)

### Other

The Pufferfish Discord thinks this is a Paper issue and suggested I report this.

**Comment by jpenilla** [comment]
not paper

**Comment by NotAlexNoyle** [comment]
For anyone that stumbles across this, the culprit was purpur. The max limit in purpur.yml for weeping vines, twisting vines, kelp, and cave vines, is 25.
