### ISSUE TITLE
Remove 15 second warning

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#716]
Do you think it would be possible to remove the 15-second warning from startup? I Just think there is no need for this, Maybe make an option in the paper to turn off the reminder.

**Comment by zachbr** [comment]
Will remove from the final 1.11 build before we do 1.12

**Comment by jordanwilliams1** [comment]
@Zbob750 Would also like it to be removed on the 1.12 builds too. No matter what, after a few days you're going to be outdated anyway. I Normally only update if there is a major bug fix or performance improvement

**Comment by zachbr** [comment]
Will not be removed from current tip of master builds. It's already on a 2 week delay. That's more than plenty of time.

**Comment by zachbr** [comment]
It already appears to be disabled on 1.11.2 build 1104 and is set to a generous 14 days on the 1.12 builds. I think we're all good here?
