### ISSUE TITLE
Sea lanterns are generated all over the world

### ISSUE THREAD

**Issue by enlyow** [PaperMC/Paper#717]
Sea lanterns are generated all over the world.
Screenshot: https://prnt.sc/fh85ev

I'm using the latest version of paperspigot

Plugins: https://prnt.sc/fh857v

**Comment by zachbr** [comment]
Latest isn't a version

**Comment by enlyow** [comment]
git-paper-1104 (1.11.2)

**Comment by zachbr** [comment]
In that case you need to test world generation without plugins, then attempt to narrow it down to one.

If it still occurs on **new** worldgen we need to know about it.

**Comment by zachbr** [comment]
If you can reproduce this without plugins on 1.12.1, open a new ticket.
If you can only reproduce it with plugins, you'll have to track down the author and inform them.
