### ISSUE TITLE
Paper completely breaks server restarts on 1.12 

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#721]
Build: 1105 

Everytime my auto restart goes off paper ignores my message like The server will be back up in a moment and changes it to The server is restarting Paper also doesn't fully restart the server.. Not a problem in spigot 1.12

**Comment by zachbr** [comment]
Need more info about what your auto restart does and how it works so we can replicate.

**Comment by Fonzee9** [comment]
Okay so another thing is once the plugin sends the server to restart it doesn't restart and it constantly spams also the server is unjoinable when this happens

Auto save complete spam in console  https://pastebin.com/tCNU8RBn

Plugin: https://www.spigotmc.org/resources/simplerestarttime.24986/

**Comment by Fonzee9** [comment]
Also i am using the Patched-1.12.jar like you told me a long time ago.

**Comment by Fonzee9** [comment]
Not sure if you changed something but this issue also happened on Paper Pre 6 as i said before my message for server restarting is set too "Friendly Survival will be back up in a moment" paper makes it say "The server is restarting" yet it doesn't even restart..

**Comment by electronicboy** [comment]
Okay, so; looks like we missed a fix for an oversight from when we originally tried to make the restart command actually be sane

However, I cannot replicate your issue with the restart message, that worked perfectly fine here without any issues

**Comment by zachbr** [comment]
Please re-test against build 1106 and let us know if this issue continues, thanks.

**Comment by Fonzee9** [comment]
It's fixed thank you so much 👍
