### ISSUE TITLE
Option to disable advancements output in chat - vanilla gamerule does not actually turn it off.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#725]
Waterfall dev 123 (MC 1.12)
Paper dev 1106 (MC 1.12)

Would it be possible to add an option to hard disable all advancements from outputting in chat as players get new achievements? The gamerule ```/gamerule announceAdvancements false``` does not actually seem to disable it. It outputs that it does, but I'm still having new announcements from players popping up here and there.

**Comment by mibby** [comment]
@Zbob750 This was actually just added upstream here https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/53dcd96fa1e2d38d869118ae2019cf9d8769143f#CraftBukkit-Patches/0142-Configurable-Advancement-Disabling.patch so I guess this ticket is turning into an upstream merge request please? <3

**Comment by mibby** [comment]
Aikar with the snipe.
https://github.com/PaperMC/Paper/commit/19e9e0d647b1070dbf38adea314b7249566ef89b

**Comment by mibby** [comment]
Re-opening for separate inquiry. Would it be possible to have an option to disable advancement messages from outputting in chat but keeping advancements enabled? As the gamerule does not seem to fully disable all messages and the spigot setting removes advancements outright. I'd like to keep the advancement feature of 1.12 enabled but disable the spam it produces in chat with lots of players.

**Comment by zachbr** [comment]
For those of us not in-the-loop on what messages that gamerule does or doesn't remove, can you please be more specific?

Which messages is it not removing that you feel it should?

**Comment by Black-Hole** [comment]
CraftBukkit changed game rules so that they are per world. So an op player have to enter each world and disable the game rule there.

The message is sent in AdvancementDataPlayer.grantCriteria()

**Comment by mibby** [comment]
> CraftBukkit changed game rules so that they are per world

I tried setting the gamerule via console and by manually entering each world. Yet I and others still occasionally saw advancement messages, even after restarting the server. So that makes me believe the gamerule itself is non-functional.

> Which messages is it not removing that you feel it should?

Notifications that a player has achieved a specific advancement.

**Comment by electronicboy** [comment]
The gamerule should work fine, the fact that it worked in some worlds kinda confirms that and places a (!!) on if you actually did it for all the worlds or if you somehow managed to miss one.

a config option for this would just feel highly redundant considering the fact that there is already a gamerule for this...

**Comment by mibby** [comment]
> The gamerule should work fine,

But it doesn't, hence this ticket. I set ```/gamerule announceAdvancements false``` in all 3 worlds; world, world_nether, and world_the_end - yet still see the announcements from some players.

**Comment by mibby** [comment]
Updating to Paper 1111 and re-set the ```announceAdvancements false``` gamerule in all worlds. Haven't seen any advancement yet so I'm assuming it may have been a fluke or perhaps a typo in the gamerule I didn't notice at the time since it adds anything typed.

Assuming fixed and will be closing the ticket unless the problem otherwise persists.
