### ISSUE TITLE
Ignored advancement login warning with all advancements disabled.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#726]
Waterfall dev 123 (MC 1.12)
Paper dev 1107 (MC 1.12)

I disabled all advancements in the main spigot config via
```
disabled-advancements:
- '*'
```

However, now I receive this output whenever someone logs in where they had stats for advancements. Would it be possible to hide this verbose when all advancements are disabled?

Warnings on login.
http://paste.ubuntu.com/24815409/

**Comment by electronicboy** [comment]
closing (as I've been meaning to for a while). from my recollection, the advancement data should be removed when the player logs in and their data is saved, I'm highly against providing means to disable warning messages which contain information of what is going on in the server (especially those likely to be disabled and then hide debugging information).
