### ISSUE TITLE
Create Branch for 1.11.2

### ISSUE THREAD

**Issue by ssamjh** [PaperMC/Paper#727]
Just an idea for the project, it would be handy having a 1.11.2 branch, especially if you plan to patch it sometime in the future :)

**Comment by electronicboy** [comment]
paper generally only creates branches when needed (as is proper git practice), otherwise you end up with dormant branches for no real reason, nor is it ever really intend to ever touch base with older versions and is more of a "Well, I guess we'd better..."

**Comment by zachbr** [comment]
Generally I'd agree, but when I merged pre/1.12 into master it didn't really handle it quite how I intended. So I pulled the top of tree hash from Jenkins and made a branch out of it at ver/1.11.2.
