### ISSUE TITLE
Spectator mode grows crops now?

### ISSUE THREAD

**Issue by LogGits** [PaperMC/Paper#730]
I have noticed that in the latest build of paper spigot spectator mode doesn't stop crops from growing. When I was using build 1104 if a player was in spectator mode the chunk wouldn't grow crops (like regular Minecraft). In build 1111 it does grow crops. Is there a setting or something that I need to toggle or is this some sort of bug? I tested it in 1.12 singleplayer and spectator mode still doesn't grow crops.

**Comment by zachbr** [comment]
If this is the case it's a bug.

**Comment by LogGits** [comment]
The same thing happens with spigot 1.12-R0.1. I will keep testing to see if i can find what the issue is.

**Comment by LogGits** [comment]
Mob spawners don't detect spectator players (which is the correct game mechanic) so the crops issue must be a bug.

**Comment by electronicboy** [comment]
Have you tested the vanilla server, there are a few cases where the server might interact differently between a client server and a standalone server, I'll try and have a look sometime into this

**Comment by LogGits** [comment]
Ok so I have tested it on vanilla and farmland doesn't grow when only a spectator is there.

**Comment by zachbr** [comment]
Doesn't appear to happen on 1.12.
Or I'm just really lucky?

**Comment by LogGits** [comment]
I found out what caused this. It was a 1.11 map on a 1.12.2 server. Im pretty sure the generation was messed up. I was wondering why others couldn't reproduce but it is now clear (people were testing on maps generated on 1.12 - 1.12.2). I am not sure if this issue can be fixed (Though I'm not having it anymore). I am worried it may happen on 1.12.2 generated maps running on 1.13 spigot/paperspigot (when it comes out).
