### ISSUE TITLE
max-entity-collisions is present in both Spigot and Paper configs.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#737]
The ```max-entity-collisions: #``` setting is present in both paper and spigot.ymls. Any specific reason?

**Comment by zachbr** [comment]
Spigot dropped their version, regenerate your spigot.yml.

**Comment by hurrgurl** [comment]
Sorry for off topic, but does it matter if my spigot yml was generated around 1.7 Minecraft?

I always thought non existing strings will be ignored and not cause any issues?

**Comment by kashike** [comment]
It's fine. Any new configuration options will be added (with default values), and removed configuration options do no harm.

**Comment by zachbr** [comment]
I generally recommend regenerating your spigot.yml (and even paper.yml) on major Minecraft updates, ie MC 1.11 -> 1.12. Just so you can see what options still exist and are relevant.

However the ones that don't exist will not actually hurt you. It can just be confusing to have all the old ones still hanging around and not actually doing anything, in my opinion :)

**Comment by WonderDave** [comment]
If I compile a new Spigot jar and run it in an empty folder, the generated spigot.yml file does NOT contain a 'max-entity-collisions' entry.  However, if I run a Paper jar (build 1121) in an empty folder, the generated paper.yml and spigot.yml files BOTH contain a 'max-entity-collisions' entry.  Why is that?

**Comment by electronicboy** [comment]
Paper attempts to migrate that config value from spigot for you, due to how paper pulls that value, it does mean that the configuration is also added to spigots config

**Comment by mibby** [comment]
> Spigot dropped their version, regenerate your spigot.yml.

Generating a new spigot.yml and paper.yml on build 1122 does in fact have a ```max-entity-collisions``` setting in spigot.yml. But I guess that is caused by Paper trying to migrate that setting over.

**Comment by zachbr** [comment]
Yeah it is, I forgot it would do that :(
