### ISSUE TITLE
compile issue: "Extracting NMS classes..."

### ISSUE THREAD

**Issue by d9210** [PaperMC/Paper#739]
I'm trying to compile paper. But it failed...

qq350@DKK MINGW64 /z/Users/DKK/Desktop
$ git clone https://github.com/PaperMC/Paper
Cloning into 'Paper'...
remote: Counting objects: 25884, done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 25884 (delta 47), reused 54 (delta 17), pack-reused 25773
Receiving objects: 100% (25884/25884), 8.27 MiB | 452.00 KiB/s, done.
Resolving deltas: 100% (21429/21429), done.

qq350@DKK MINGW64 /z/Users/DKK/Desktop
$ cd paper

qq350@DKK MINGW64 /z/Users/DKK/Desktop/paper (master)
$ ./paper patch
Submodule 'work/BuildData' (https://hub.spigotmc.org/stash/scm/spigot/builddata.git) registered for path 'work/BuildData'
Submodule 'work/Bukkit' (https://hub.spigotmc.org/stash/scm/spigot/bukkit.git) registered for path 'work/Bukkit'
Submodule 'work/CraftBukkit' (https://hub.spigotmc.org/stash/scm/spigot/craftbukkit.git) registered for path 'work/CraftBukkit'
Submodule 'work/Paperclip' (https://github.com/PaperMC/Paperclip.git) registered for path 'work/Paperclip'
Submodule 'work/Spigot' (https://hub.spigotmc.org/stash/scm/spigot/spigot.git) registered for path 'work/Spigot'
Cloning into 'Z:/Users/DKK/Desktop/Paper/work/BuildData'...
Cloning into 'Z:/Users/DKK/Desktop/Paper/work/Bukkit'...
Cloning into 'Z:/Users/DKK/Desktop/Paper/work/CraftBukkit'...
Cloning into 'Z:/Users/DKK/Desktop/Paper/work/Paperclip'...
Cloning into 'Z:/Users/DKK/Desktop/Paper/work/Spigot'...
Submodule path 'work/BuildData': checked out 'ebd264edb506ff3e72e92dd16b1b68c46905972c'
Submodule path 'work/Bukkit': checked out '7b5ab33d620b1d19e00152b4a0d64c160712c3b7'
Submodule path 'work/CraftBukkit': checked out 'ec47e791bda2be9e172e841fbfd50f0e40fcaaf4'
Submodule path 'work/Paperclip': checked out '6dcb3241ca8e69fb8209e54fea507425c508915e'
Submodule path 'work/Spigot': checked out '8cbfc85b6364a7c7be564bb7b1bb19769dbcee77'
Downloading unmapped vanilla jar...
Applying class mappings...
Applying member mappings...
Creating remapped jar...
Installing remapped jar...
Extracting NMS classes...
./scripts/decompile.sh: line 16: jar: command not found
Failed to build Paper

**Comment by electronicboy** [comment]
You need to install the JDK

**Comment by zachbr** [comment]
I assume you're on Windows?
This is where we most commonly see this issue.

By default, the JDK install on Windows does not add the entire JDK toolkit, only a subset. You can fix this by adding the entirety of the JDK to your %PATH% environment variable.

For example the correct path *on my system* is:  D:\Program Files\Java\jdk1.8.0_131\bin

Notice the entire bin directory is in the %PATH%.

**Comment by d9210** [comment]
@Zbob750 Thanks very much. But it failed again....  

http://puu.sh/wielk/b655230393.txt

**Comment by electronicboy** [comment]
please read the bottom of your log file, it tells you exactly what you need to do

**Comment by d9210** [comment]
So sorry  I asked a foolish thing... anyhow thanks

**Comment by electronicboy** [comment]
It's more a case of, the log output will generally give you a massive hint of what went wrong (and so you should properly read it), sometimes it can be something obvious, sometimes it will leave your head puzzled or your mouth screaming, but the log generally includes some form of indication of what went wrong and how screwed you are ;)
