### ISSUE TITLE
Pillagers dismounting from Ravagers who die, dismount into transparent blocks. Ravagers Clipping into blocks, or ignoring spawn conditions. 

### ISSUE THREAD

**Issue by TwoPointInfinity** [PaperMC/Paper#7396]
### Expected behavior

When a ravager dies and the pillager dismounts they would fall directly down where the ravager stands. Ravagers also seem to spawn and clip through blocks then walk through them, spawning in odd places or ignoring most spawn conditions at all. 

### Observed/Actual behavior

Often the pillager who is riding the ravager will dismount similar to the player and go to a side-ways direction, even selecting blocks to stand on that have glass as their feet or their head, or both. They do not seem to care.

### Steps/models to reproduce

Spawn a ravager with a rider within a 1x1x3, boxed in so it does not just walk out through the blocks that it is clipping into. (or similar conditions). 
Kill the ravager.

### Plugin and Datapack List

advamcedarmorstands, antiendermangrief, chunky, coordinatehud, coreprotect, discordsrv, dragoneggdrop, luckperms, placeholderapi, plan, protocollib, sleepmost, supervanish, TAB, vault, venturechat, worldedit, worldgaurd, worldgaurdextraflags

### Paper version

git-paper-152

### Other

I am not my server's admin therefore i cannot just get the latest version of paper and update. The changelogs back to the version that the server is on doesn't mention anything similar to this.  im honestly a bit confused by all this ravager spawning, its hard to tell if the issue is the pillagers getting off to the wrong spot or somehow the ravager is getting their rider to a weird spot by clipping through walls and ignoring their spawn conditions. I'm sorry if this isn't enough information please let me know what i can do for more info.

**Comment by Owen1212055** [comment]
I'm having trouble reproducing this issue, can you provide a world download/video that demonstrates this issue?

Thanks!

**Comment by Owen1212055** [comment]
Please feel free to comment on this issue if you are able to reproduce this and this issue can be reopened.
I will be closing this in the meantime.

Thank you! 😄
