### ISSUE TITLE
max-entity-collisions doesn't work anymore (HUGE lag!)

### ISSUE THREAD

**Issue by Platinteufel** [PaperMC/Paper#74]
Hey,

I'm running a survival server with about 50 players online. The new entity-collision-system is **eating** my CPU, I'm not able to run my server with more then 12 TPS atm. 

I've just tested it with about **450 chicken in a small hole**.

**TPS in 1.8:** 19.7
**TPS in 1.9:** 8.67
Specs: E3-1271v3, Java 8 64 Bit, latest Paper

**Timings:** 
Paper 1.9: http://timings.aikar.co/v2/?id=066e2411eb4f4bfaba252a5daf89a3b8
Spigot 1.9: http://timings.aikar.co/?url=15331416

**94.85%**   218.33%     86.34 s       109.16 ms     369         291.9k     **tickEntity - EntityChicken**
**72.03%**   165.77%     65.56 s        82.89 ms     377         298.1k     **livingEntityAICollision**

I've set max-entity-collisions to 0 and it didn't change anything. I'm not able to run my run my survival server smooth anymore. :/ A fast fix would be awesome!

![2016-03-09_01 13 26](https://cloud.githubusercontent.com/assets/13700636/13639449/12cc6794-e611-11e5-805d-9a3fbc60c59c.png)

**Comment by Puremin0rez** [comment]
Appears to have been fixed in Spigot just a short while ago
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/Spigot/commits/b1c1b55c47e

**Comment by Platinteufel** [comment]
Yes, I've just reported it there ..
