### ISSUE TITLE
Check Condition if player has active action bar

### ISSUE THREAD

**Issue by LowScarlet** [PaperMC/Paper#7420]
### Is your feature request related to a problem?

Yes

### Describe the solution you'd like.

%player%'s has active action bar

### Describe alternatives you've considered.

idk

**Comment by electronicboy** [comment]
The server doesn't track this, nor is there a reliable way to track this

**Comment by LowScarlet** [comment]
> The server doesn't track this, nor is there a reliable way to track this

sad
