### ISSUE TITLE
Crash - Paper #1123 (Minecraft 1.12)

### ISSUE THREAD

**Issue by alexitx** [PaperMC/Paper#745]
**The following are 'hard suggestions': if you have the information
available to you, you really should put it in the report. Choose one of
the following templates from below that best fits the issue you wish to
report.**

# Performance issue
___This section should be used for any report regarding performance issues___

###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real
cause of the issue.___

### Description of issue:
___If applicable___

Issue Description: Server freeze / not responding after some playing with 2 Players. Crash report attached.

### Plugin list:
Plugins: N/A (No Plugins)

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___
### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

# Incompatibility (Bug)

### What behaviour is expected:
___What you expected to see___
### What behaviour is observed:
___What you actually saw___
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

Paper #1123

# Crash, Stacktrace

### Link/paste of stack trace

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Plugin list:
___A list of your plugins___
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

# Suggestion

___We love suggestions! Suggestions are fairly unstructured, and will be treated as such___

**Comment by Black-Hole** [comment]
Someone spawned firework with a very high horizontal velocity.

**Comment by ryans1230** [comment]
I too am having this error. Is there any plugin fix for it?

https://hastebin.com/tecuwofetu.rb

**Comment by Black-Hole** [comment]
Use some plugin to filter creative mode items.
