### ISSUE TITLE
Tnt duplication glitch on 1.12

### ISSUE THREAD

**Issue by melinstagibson** [PaperMC/Paper#749]
https://m.youtube.com/watch?v=havYLoNf4ro

Devastating for a survival world

**Comment by 0-x-2-2** [comment]
this was already reported a long time ago and most players see it as a feature

**Comment by zachbr** [comment]
Slime blocks are a duplication disaster. There are plugins to limit them but ultimately you cannot maintain vanilla behavior in doing so (at least as of yet)

Closing as a duplicate of GH-566
