### ISSUE TITLE
You can get up 3 blocks with elytra.

### ISSUE THREAD

**Issue by axynos** [PaperMC/Paper#75]
To reproduce:
Put elytra on.
Look a bit above the horizontal plane.
Jump
At the peak of the jump enable elytra and keep holding spacebar.
Fall down to ground and get a big enough boost to get up 3 blocks

This bug is present on build 472.
This is not present in vanilla minecraft.

**Comment by zachbr** [comment]
Tested with latest at this time (build 474), cannot reproduce.

**Comment by axynos** [comment]
Just tested with build #474 and it's still possible.
[Here's a gif while I'm at it.](https://gfycat.com/ShoddyFastAfricanelephant)

**Comment by zachbr** [comment]
Thanks to your gif I was just able to reproduce this in latest. Thanks.
I was also able to reproduce this, sparingly, in vanilla 1.9. But it appears as though it's easier in Paper.

**Comment by axynos** [comment]
Glad to be of assistance.

**Comment by axynos** [comment]
Closed by accident.

**Comment by axynos** [comment]
Confirmed to be working in vanilla, will post to their bug tracker aswell.

**Comment by zachbr** [comment]
Because this is working in vanilla, and its sort of an opinion thing, I think we're going to close this and leave it to Mojang and/or plugins to handle.

Thank you for your report :)
