### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Venomous777** [PaperMC/Paper#756]
/version - git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0-1-SNAPSHOT)

`18.06 20:50:42 [Server] ERROR The server has stopped responding! 18.06 20:50:42 [Server] ERROR Please report this to PaperSpigot directly! 18.06 20:50:42 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports 18.06 20:50:42 [Server] ERROR PaperSpigot version: git-PaperSpigot-"4c7641d" (MC: 1.8.8) 18.06 20:50:42 [Server] ERROR ------------------------------ 18.06 20:50:42 [Server] ERROR Server thread dump (Look for plugins here before reporting to PaperSpigot!): 18.06 20:50:42 [Server] ERROR ------------------------------ 18.06 20:50:42 [Server] ERROR Current Thread: Server thread 18.06 20:50:42 [Server] ERROR PID: 16 | Suspended: false | Native: false | State: RUNNABLE 18.06 20:50:42 [Server] ERROR Stack: 18.06 20:50:42 [Server] ERROR com.creeperevents.oggehej.obsidianbreaker.BlockListener.explodeBlock(BlockListener.java:92) 18.06 20:50:42 [Server] ERROR com.creeperevents.oggehej.obsidianbreaker.BlockListener.onEntityExplode(BlockListener.java:51) 18.06 20:50:42 [Server] ERROR sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 18.06 20:50:42 [Server] ERROR sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 18.06 20:50:42 [Server] ERROR sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 18.06 20:50:42 [Server] ERROR java.lang.reflect.Method.invoke(Unknown Source) 18.06 20:50:42 [Server] ERROR org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) 18.06 20:50:42 [Server] ERROR co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) 18.06 20:50:42 [Server] ERROR org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) 18.06 20:50:42 [Server] ERROR org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) 18.06 20:50:42 [Server] ERROR org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) 18.06 20:50:42 [Server] ERROR net.minecraft.server.v1_8_R3.Explosion.a(Explosion.java:201) 18.06 20:50:42 [Server] ERROR net.minecraft.server.v1_8_R3.World.createExplosion(World.java:1917) 18.06 20:50:42 [Server] ERROR net.minecraft.server.v1_8_R3.WorldServer.createExplosion(WorldServer.java:1053) 18.06 20:50:42 [Server] ERROR net.minecraft.server.v1_8_R3.EntityTNTPrimed.explode(EntityTNTPrimed.java:116) 18.06 20:50:42 [Server] ERROR net.minecraft.server.v1_8_R3.EntityTNTPrimed.t_(EntityTNTPrimed.java:87) 18.06 20:50:42 [Server] ERROR net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1650) 18.06 20:50:42 [Server] ERROR net.minecraft.server.v1_8_R3.World.g(World.java:1617) 18.06 20:50:42 [Server] ERROR net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1450) 18.06 20:50:42 [Server] ERROR`

**Comment by zachbr** [comment]
We do not support 1.8.8 in any capacity.
