### ISSUE TITLE
New console color not properly outputting all colored text

### ISSUE THREAD

**Issue by tplacek** [PaperMC/Paper#757]
### Description of issue:
Console output that was previously in color for some plugins now outputs with color codes in-line but not set on output.
New console colors function as expected. Example: (Warnings: yellow, Errors: red)

Observed with AntiWorldDownloader v2.3.1
example:
[02:40:38 INFO]: [AWD] Enabling AWD v2.3.1
[02:40:38 INFO]: ?e[?c?lAntiWorldDownloader?e] ?eAWD has been enabled! (Version: 2.3.1)

Observed with ChatEx v1.6
example:
[03:12:20 INFO]: [?fworld?f] ?6user1?r?7: chat message
[03:12:21 INFO]: user2 was blown up by Creeper
[03:12:30 INFO]: [?fworld?f] ?Duser2?7: wow, invisable creeper

Console Capture showing new colored output functioning, 1 plugin outputting color and 1 plugin not outputting color.
http://imgur.com/UP9XH04

git-Paper-1129 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Are you using a custom log4j config? what OS, is it only specific plugins that are printing out their data like that?

**Comment by tplacek** [comment]
I am not using a custom log4j config. OS is FreeBSD 11 with openjdk 8.1.2.1.13
Currently the only two plugins I've observed exhibiting this behavior are the ones I listed but they are the only ones I ever noticed dumping color to console. Edit: I can plugin version several other plugins and their version information output that includes color codes will also replicate this behavior.

The only plugin I've noticed that actually DOES output color correctly is HorseTpWithMe v2.0.5 when it loads. CodeSnippet:
`getLogger().info("\033[32;1mHorseTpWithMe v" + this.getDescription().getVersion() + " is Enabled and working.\033[0;m");`

AntiWorldDownloader is obfuscated so I can't compare why it doesn't work but HorsepWithMe does.

![image](https://user-images.githubusercontent.com/6787341/27343317-162e8f4a-55a8-11e7-8097-8de23eb79fc8.png)
![image](https://user-images.githubusercontent.com/6787341/27343333-26e09f04-55a8-11e7-93b0-ea174fdf541c.png)

**Comment by stephan-gh** [comment]
It looks a bit like an encoding problem but I cannot reproduce this on Linux (Arch Linux) or Windows. Color output works fine, even with AntiWorldDownloader.

**Comment by tplacek** [comment]
Yes, I just tested in windows as well.

Even base functionality such as the Reload Complete message are showing like this. It was working as expected in build 1110.

I will do some further testing to see if I can isolate why this is happening.

**Comment by tplacek** [comment]
I don't currently have an arch linux testing install. Could you see if you could replicate it in tmux? I've isolated that it my personal issue. Its just odd that whats broken now, worked before. I'm using tmux 2.3_2

**Comment by electronicboy** [comment]
I tested in a fresh freebsd install and got the exact same thing, can't really say much beyond that as I don't use it, just installed a copy to test it

**Comment by tplacek** [comment]
Yes, I isolated it to with tmux which is a terminal multiplexer similar to GNU screen. Could you test with tmux or screen on arch? I'm still downloading for myself.

**Comment by stephan-gh** [comment]
Working fine with tmux 2.5 on Arch Linux, colors are displayed properly.

**Comment by stephan-gh** [comment]
I can reproduce it when using Paper on FreeBSD (even without tmux), will investigate later today what's causing it.

**Comment by stephan-gh** [comment]
As a workaround, running Paper with `-Dfile.encoding=UTF-8` fixes it for me (so it's likely really an encoding problem). On Linux, the problem can be reproduced using `-Dfile.encoding=US-ASCII` which seems to be the default on FreeBSD.
