### ISSUE TITLE
How can I clone about  ver1.11.2 in GIT?

### ISSUE THREAD

**Issue by d9210** [PaperMC/Paper#758]
I try to type  git clone https://github.com/PaperMC/Paper/tree/ver/1.11.2 but it not found 

Cloning into '1.11.2'...
remote: Not Found
fatal: repository 'https://github.com/PaperMC/Paper/tree/ver/1.11.2/' not found

And how to compile work\1.11.2\net\minecraft\server?
I edit the item.java and items.java but I don't know how to compile
Thanks

**Comment by electronicboy** [comment]
```
git clone https://github.com/PaperMC/Paper.git
git checkout ver/1.11.2
```

Beyond that, I'd suggest referring to the contributors guide in order to understand how to use the paper tools script provided

**Comment by d9210** [comment]
@electronicboy Thank you! The contributors guide is CONTRIBUTING.md? I'm a beginner, just try to add a new item in Paper server, like Cauldron. I succeed in test minecraft_server.1.11.2, but it won't work for Paper. I thinks need edit about cache\patched_1.11.2.jar\net\minecraft\server\v1_11_R1\ right?

**Comment by electronicboy** [comment]
Yes, that's the contributor's guide, and no, that is not the place you want to edit. You need to use the paper tool to apply all of the patches, and then you can modify the sources by opening the paper project itself in your IDE as a maven project (there is a parent pom in the main folder that will resolve the server and api projects).

**Comment by Black-Hole** [comment]
For adding custom items you'll have better success with Forge. And please use the forums. This is for issues with Paper, not for development help.

**Comment by w-o-a-h** [comment]
@Black-Hole Cauldron is ded so no plugins
