### ISSUE TITLE
Chestshop disables itself with version 480 of Paper

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#76]
The plugin chestshops doesn't start with version 480 of Paper. With 475 it works fine.

Here the error while the server starts: http://pastebin.com/yeuuii7W

**Comment by kashike** [comment]
You can blame @Techcable for this. #45

**Comment by ghost** [comment]
Anything what I have to do now? Will this be fixed in the future?

**Comment by SecretlyJealous** [comment]
Good to know I'm not the only one having this issue. PlotSquared keeps spamming errors in console related to ASM:
http://pastebin.com/EiKkaxH5

**Comment by zachbr** [comment]
Should be fixed with 752452373def81997c5238464d47e6e7423f26b5 and CI build 481.
Please let us know if it isn't.
