### ISSUE TITLE
/tell issue

### ISSUE THREAD

**Issue by bigsmileling** [PaperMC/Paper#760]
https://github.com/drtshock/Essentials/issues/1285#issuecomment-310041241 <--- THIS

### bukkit.yml, spigot.yml, paper.yml, server.properties
Not need it, still doing it with default config

### Other helpful links
https://github.com/drtshock/Essentials/issues/1285#issuecomment-310041241

### Paper build number:
1130

# Incompatibility (Bug)
https://github.com/drtshock/Essentials/issues/1285#issuecomment-310041241

### What behaviour is expected:
Just a message like /m or /msg, not a whisper

### What behaviour is observed:
Minecraft command its overrading the plugin command

### Steps/models to reproduce:
Just write /tell nick text

### Paper build number:
This server is running Paper version git-Paper-1130 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

Dont have

### Plugin list:
Not need it, happens using essentials as solo plugin

### Actions to reproduce (if known):
Just write /tell nick text

### Paper build number:
1130

# Suggestion
A fix

**Comment by MiniDigger** [comment]
fixed upstream https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/f3356f107465e2b74d353dce8f6daa49231dcc15

**Comment by electronicboy** [comment]
https://i.valaria.pw/1498043724.jpg (Figured I'd test the version on the jenkins just incase: https://i.valaria.pw/1498043941.jpg):
Working fine in the latest paper version due to the change applied by Aikar last night. Paper will update later and pull the upstream changes, but you're doing something weird, it works fine.

**Comment by bigsmileling** [comment]
Thanks, i don't know what i was doing, now its working fine, thanks everyone! and sorry if i did something wrong.
