### ISSUE TITLE
Push based hoppers transfer items too quickly

### ISSUE THREAD

**Issue by lg-Cat73** [PaperMC/Paper#763]
https://youtu.be/nR6Fx0hQQvY
https://github.com/PaperMC/Paper/pull/762

**Comment by 0-x-2-2** [comment]
I see nothing wrong please give more info.

**Comment by lg-Cat73** [comment]
@w-o-a-h Item transfer speed

**Comment by zachbr** [comment]
Confirmed against build 1134.

**Comment by electronicboy** [comment]
Does anybody happen to know a build that this wasn't an issue in, as I've just personally confirmed it against the latest 1.11.2 build?

**Comment by Trigary** [comment]
Unable to reproduce, version: git-Paper-210 (MC: 1.13.1)

**Comment by zachbr** [comment]
Copy pasting from GH-354:

This was a bug in a patch that fundamentally altered how hoppers work. It was not ever confirmed to be present in the base game with that altered hopper functionality disabled.

That patch has been dropped entirely as of 1.13 and is unlikely to come back. Closing as such.
