### ISSUE TITLE
Feature Request: Dont allow players to join while server is shutting down

### ISSUE THREAD

**Issue by BillyGalbreath** [PaperMC/Paper#765]
It would be kind of like the late-bind setting (where late-bind wont let player connect until after the server is fully loaded).

I have quite a number of plugins on my server, and some of them take a while to shutdown (sometimes a shutdown takes 30 seconds). During the shutdown a number of players reconnect, which not only seems to slow the shutdown process but it also gets them in on the server while some plugins are already disabled such as land protections (which is very bad).

I have tried numerous ways to kick players during a shutdown, but plugin event listeners stop listening during a shutdown process, which makes it impossible to kick on join from a plugin during a shutdown. :(

I propose a paper.yml setting to be added to stop players from joining the server once a shutdown has started.

**Comment by zachbr** [comment]
Not even sure this needs to be a setting.

Edit: As in, this should just be fixed and always on.

**Comment by DenWav** [comment]
Please add a "please-crash-on-startup" option.

**Comment by zachbr** [comment]
Added in builds 1142+
