### ISSUE TITLE
Advancements won't stop appearing on global chat

### ISSUE THREAD

**Issue by Castiella** [PaperMC/Paper#768]
I keep turning off advancements in the server config but it keeps appearing on global chat non stop. when i go back into the config after i turn the server on it has reset back to enabled.

Game rule ect is also not fixing this.

Not sure if a paper issue but it didnt happen on the old build of paper i used.

**Comment by FunnyCraft** [comment]
+ also do not turn off

**Comment by Black-Hole** [comment]
Bukkit changes game rules to be per world. So you have an opped player enter each world and change game rules there.

**Comment by kashike** [comment]
#725
Advancements aren't disabled in `server.properties`, you want `/gamerule announceAdvancements false`.
