### ISSUE TITLE
Broken Chests Not Dropping Items 

### ISSUE THREAD

**Issue by TheGreatNaj** [PaperMC/Paper#769]
### Description of issue:
When chests are broken occasionally theres a glitch that makes them not drop its contents. This happens on 2 different servers I manage. With the first server it started happening when we switched from sponge to paper spigot but only when creepers blew up chests. The second server was always on regular spigot but this time we're trying paper and it did happen with creepers again so mob griefing was turned off to prevent that, but now its happening when players break their own chests. The worst part about this bug is Core Protect has a different bug where items are duplicated when rolling back double chests :I 

### Plugin list:
(Overlapping plugins of the 2 servers)
Core Protect
Essentials
Fast Async World Edit
Multiverse Core
Permissions Ex
Vault
World Edit
World Guard

### bukkit.yml, spigot.yml, paper.yml, server.properties
Server 1
bukkit.yml - https://pastebin.com/j0ffiYes
spigot.yml - https://pastebin.com/rwUybZEq
paper.yml - https://pastebin.com/crbPB7mL
server.properties - https://pastebin.com/yvuV5299
Server 2
bukkit.yml - https://pastebin.com/bviE9dh3
spigot.yml - https://pastebin.com/Sgvj6d68
paper.yml - https://pastebin.com/7pbv6FM8
server.properties - https://pastebin.com/7x9WLdWr

### Paper build number:
Server 1: Paper version git-Paper-1125 (MC:1.12) (Implementation API version 1.12-R0.1-SNAPSHOT)
Server 2: Paper version git-Paper-1129 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

### What behaviour is expected:
Items drop lol 

### What behaviour is observed:
No items

### Steps/models to reproduce:
Unsure since its inconsistent, but happened more commonly when chests were broken by creepers and specifically with server 2 we have more lag issues which is the only server this bug has occurred from a player breaking a chest. 

# Suggestion
Love yoself ;L

**Comment by TheGreatNaj** [comment]
Oh, and one of the other managers suggested it might be something with Fast Async World Edit as well with all its lag reducing weirdness

**Comment by zachbr** [comment]
I cannot reproduce this with Paper, it is likely a result of your plugin selections.
You'll have to whittle down what is causing what and either update it or report it to the respective author(s).
