### ISSUE TITLE
Timings not working

### ISSUE THREAD

**Issue by StefvanderMeer** [PaperMC/Paper#770]
Hey,

I am using PaperSpigot 1.8.8

I know support isn't included for this version. But my timings are not working I get a link that is not working. I have no idea if this issue is resolved or maybe I need to use another command since I just used the spigot commands:

/timings on

wait a few mins

/timings paste

And I got a link that didnt work.

**Comment by ghost** [comment]
I had same problem, look at link of your timings, it is a bit broken.

Lets say, your url contains: https://timings.aikar.co/d=XXXXXXXXXXXXXXXXXXXXX
And correct timing contains: https://timings.aikar.co/?id=XXXXXXXXXXXXXXXXXXXXX

See the difference? Add ?i to url and it will work. Have been doing this for time

**Comment by zachbr** [comment]
We do not support 1.8.8 in any capacity.
