### ISSUE TITLE
Unable to fit 4306742 into 3

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#772]
I've got a player named "RollingThunder14" that keeps crashing whenever he joins the server and players near him also crash too. Here's the log: https://hastebin.com/awerosozat.css
The .dat file also seems large for this player: https://www.dropbox.com/s/jfd1o7veam7jvsh/e506fa76-0c65-4635-a67b-d67fede18c84.dat?dl=1
Running paper #1139

**Comment by Brokkonaut** [comment]
He has a chest in his inventory, that contains chests, that contain chests, ...

Secure your server if you want to allow creative mode for untrusted players. You need some plugin that filters BlockStateMeta in InventoryCreativeEvent

**Comment by Spottedleaf** [comment]
The guy has stacks of chests in his inventory filled with other chests filled with other chests...

Clear his inventory and see if that fixes the problem.

**Comment by zachbr** [comment]
This is the same basic problem as https://github.com/PaperMC/Paper/issues/671, and like it, the answer is not so cut and dry that we want to do anything on the server end.
