### ISSUE TITLE
Timings crash

### ISSUE THREAD

**Issue by enlyow** [PaperMC/Paper#773]
Again crashes.

Bukkit.yml: https://pastebin.com/HdhctVVu
Paper.yml: https://pastebin.com/SQ1eWuUu
Server.properties: https://pastebin.com/DK3Ycny0
Spigot.yml: https://pastebin.com/cn9wXKdz

Paper 1143 1.12

![1](https://user-images.githubusercontent.com/29000881/27834365-e2a986c0-6100-11e7-98ee-31592441912f.png)

**Comment by electronicboy** [comment]
You probably have a plugin that is modifying the state of the server async in order to cause that one.

**Comment by enlyow** [comment]
Could this be because of the asynchronous work with the armor stands?

**Comment by electronicboy** [comment]
If you're doing something that involves modifying the entities in a chunk async, yes

**Comment by enlyow** [comment]
Well, in general there is a plugin that simply twists the armor stends so that the animation of the scrolling appears.

**Comment by MiniDigger** [comment]
never touch anything of the bukkit api async if its not advertised to be thread save, especially if it involves entities or blocks.

**Comment by enlyow** [comment]
Can I find out what entity it is and in what chunk does it cause an error?

**Comment by electronicboy** [comment]
It's not a specific entity, it boils down to stupid plugins doing stupid things. Locating the plugin causing these ain't always plain sailing, the easiest method is to remove all plugins and add them back one by one.

**Comment by enlyow** [comment]
But if we transfer the work with these entities into the main thread, then the server will lag. Maybe it's possible to work with the entity asynchronously without this errors?

**Comment by electronicboy** [comment]
No, it's not possible without hurting the performance of the server by spewing new arrays all over the place everytime something wants to touch the entities in a chunk, hence why you're getting the error.

Please understand thread safety before doing stupid stuff async.
