### ISSUE TITLE
SystemClassLoader not URLClassLoader error when trying to start server with Java 9

### ISSUE THREAD

**Issue by malonnnn** [PaperMC/Paper#778]
I know Java 9 isn't supported yet, I'm just throwing this out there when you have a chance.

The error:
Server doesn't start at all and instead displays the error "SystemClassLoader not URLClassLoader" and promptly quits

OS:
Ubuntu 16.04.2

Start parameters:
java -Xms4G -Xmx7G -XX:+UseConcMarkSweepGC -jar spigot.jar

Java version:
Java 9 beta build 176

**Comment by MiniDigger** [comment]
this is most likely a mojang issue
neither minecraft nor the versions of the libs it uses work with java 9 and it will take ages till we see a move to java 9. he just went up to 8 in the latest release....

**Comment by electronicboy** [comment]
That's specifically paperclip that is triggering that message, you could try running the jar in the cache folder and seeing if it works

**Comment by malonnnn** [comment]
@electronicboy 

I'm not sure what you mean, I am aware of the cache folder and the spigot jar and patch jar go in there, but you want me to drag the actual paperclip.jar in there? I normally leave it in my root folder, so do I update my start script to point to the cache folder?

**Comment by electronicboy** [comment]
no, When paperclip runs it will download and patch the vanilla server jar and place the paper jar in the cache folder. either run the patched jar from the folder, or copy it into your server folder and run that.

**Comment by malonnnn** [comment]
@electronicboy 

just so i understand, if I rewrite my startup script to point to ~/server/cache/patched.jar then that's all i need to do? (in order to test your suggestion) - is this correct?

Also, it won't download the jar and patch, so should i install java 8, generate the jar files, and then switch to java 9 and run the patch file? or does the patch need to be generated from an already installed version of 9?

**Comment by electronicboy** [comment]
yes, that is what you'd get it to start, paperclip will patch the jar before it even gets to the message you're saying, so that should be an issue. But beyond that, stop running a version of Java that isn't ready for public consumption yet.

**Comment by malonnnn** [comment]
The reason I am using java 9 is because protocollib, one of the most popular plugins, has recently started using java 9, so I am unable to get the latest updates unless i use java 9

Also, your description doesnt match what happened to me. I habitually delete the cache files and force re-patching fairly often. It does not re-download those files on java9, the error occurs before that, so the only way to do it is to launch from java8 first then switch after the jars have been generated

I will try your method and report back in the next 24 hours

**Comment by electronicboy** [comment]
Protocollib is still building against JDK 8, they have just updated some of the stuff they use to try and support java 9 when it's released.

**Comment by malonnnn** [comment]
@electronicboy 

From the jenkins
"Builds 374 and up contain experimental changes for Java 9"

http://ci.dmulloy2.net/job/ProtocolLib/

**Comment by electronicboy** [comment]
They're still building against 8, not 9, you're more than welcome to check their build files and even build on jdk8 yourself. They are just preparing to be ready when Java 9 is released, there is no reason to be running Java 9 on a server yet.

if you want to use java 9, you're pretty much on your own for any further breakage as java 9 is not ready for public use yet and any breakage would be pretty much guaranteed to be upstream/plugins which are not ready for 9.

**Comment by malonnnn** [comment]
@electronicboy 

Thank you for looking into it, I'm not real sure how to do what you did, so I thank you. I did ask dmulloy2 about it on the discussion section and he said it was best to stick with build #373, but he also didn't really clarify further, it had just seemed that the stopping point was #373 for java8.

I will close this thread. thank you very much. Could you show me where to look to confirm it's running java8? it's not that I don't believe you, I would just like to apply that knowledge to the future so I don't have to make more threads.

Again, thanks man! I feel much better!

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paperclip/issues/4 is the already existing ticket for this issue
also, you can check the pom files inside that project, specifically the modules, and search for 1.8 and you'll see the source/target level.

If you have any further questions, you can ask here: http://irc.spi.gt/iris/?channels=paper so that we aren't flooding people's emails any further.

**Comment by zachbr** [comment]
The ticket tracking Java 9 support in Paperclip has moved to https://github.com/PaperMC/Paperclip/issues/10

**Comment by zachbr** [comment]
I did not intend to re-open this issue.
