### ISSUE TITLE
Light created by lightning strikes does not disappear ever

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#782]
Empty plugins folder. Tested queued light updates true and false.

When lightning strikes it will lit up an area around it along with fire, once this fire fades the light caused by this is stuck in that area forever, and seems like no matter what you do the blocks stay lit up. This is server side and restarts do not make it disappear.

Paper 1145

**Comment by zachbr** [comment]
Cannot reproduce this on any of my servers, plugins or no.

**Comment by ghost** [comment]
This remembers me to the effect of using W.E..
Light source blocks that only dissapear when you place a block right on it. it mostly happens with blocks like glowstone/lava.

**Comment by ghost** [comment]
Is nobody able to reproduce?

It also appears that the lighting in the area is "legitimate" and mobs will not spawn in it. Breaking blocks around it or placing torches and removing them does not remove this ghost lighting.

**Comment by ghost** [comment]
Can you take a screenshot?
What setup are you using? (the config settings etc.)
And how do you spawn the lightning?
I think there is not enough information to solve this problem.

**Comment by ghost** [comment]
Default generated configs on a default type world. Only thing I changed after experiencing this bug was changing queued light updates to true from false, which did not appear to fix or change anything.

The lightning happened naturally in vanilla gameplay.

Here is a picture. https://i.imgur.com/yTWKQ9M.png

Basically blobs of light with no source left all over the world after lightning happens naturally.

**Comment by ghost** [comment]
1. Does the same bug also happen in vanilla, bukkit and or spigot?
2. Can you make a step list for reproduction? (try the list for yourself to check if works!)
Answering these 2 things will hopefully give more detail about the bug.

edit: misreading zetglobs post. removed dumb question. thanks @polkovnikov-ph

**Comment by reverofevil** [comment]
@dodohacker He have just told that the lightning happened naturally. At least make it seem as if you cared for comments.

**Comment by josephworks** [comment]
unload and reload the chunk

**Comment by zachbr** [comment]
Paper has recently undone several lighting patches added by Spigot that essentially prevent the proper lighting routines from running.

Please let us know if you continue to see this behavior against the latest builds.
