### ISSUE TITLE
ASM ClassLoader leaks metaspace memory

### ISSUE THREAD

**Issue by ninja-** [PaperMC/Paper#786]
So, in 1.12 there's this new ASM-based event executor.
I like it though I just found out that it leaks metaspace memory and results in OutOfMemoryError: metaspace when you unregister and re-register listeners X times
(and yes I like to restrict metaspace size to be not more than needed as I run hundreds of JVM instances then this is reasonable).
The reason is that for one PluginClassLoader there is only one GeneratedClassLoader defined, so these unregistered listeners can't be garbage collected.
(no class can be garbage collected if it's classloader is referenced anywhere)
My proposed fix would be to create a new GeneratedClassLoader for each listener instance and make GeneratedClassLoaders weak referenced so something like

    private final ConcurrentMap<Listener, GeneratedClassLoader> loaders = new MapMaker.weakValues().createMap();

thoughts?

Question comes into my mind: how are lambda etc. classes being able to properly unload on GC? 
I saw that happen with -verbose:class.
or things like sun.reflect.generatedmethodaccessor
Maybe this behaviour is when it's from system=null classloader? Or maybe classes from system classloader can't be garbage collected at all...?

**Comment by Brokkonaut** [comment]
It could just use the same generated class name for the same wrapped method. So for every method used as event handler only one class is generated (and reused when reregistering)

**Comment by ninja-** [comment]
smart idea! sounds good to me 😊

**Comment by ninja-** [comment]
EDIT: But won't this break since Listener object is a new instance :/?
And you can't really redefine a class in java without connecting an agent.
Maybe I am missing something and the generated executor is not tied to specific instance?

Like:
registerListener(listener = new MyListener();
unregisterListener(listener);
registerListener(listener = new MyListener());

**Comment by Brokkonaut** [comment]
No, the Listener instance is bound to the EventExecutor when an event is handled, not while creating the EventExecutor.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/plugin/RegisteredListener.java#62

https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0023-Use-ASM-for-event-executors.patch#L145-L150

**Comment by electronicboy** [comment]
Anonymous classes are treated specially to allow for them to be GC'd, ~only the system classloader can define an anonymous class too from all I can see of it.~ [Not sure about this, however; anything can define them through unsafe)

Looking at it (I'm going off memory as I looked at this a few days ago but was too busy to reply), the GeneratedClassLoader used for listener executor is tied to the ClassLoader of the plugin that creates them, I don't think that this PR considered the potential of unregistering and registering listeners all the time.

The only way that I can really think of is to potentially look into what horrors would be needed to use an anonymous class or to store a classloader per listener and remove them when the event is unregistered. the 2nd option is probably the sanest and better one to pull off.

**Comment by Brokkonaut** [comment]
Thats much overhead when you are often registering/unregistering listeners.

Why not just cache the generated class for each method when creating them the first time (Map<Method, Class<EventExecutor>>) and reuse them instead of generating a new class? That would be just a minimal diff, prevents the memory leak and is very fast.

**Comment by electronicboy** [comment]
So, I finally got around to coming back to this (Well, mainly, I spotted a case of this while trying to debug somebodies issues and noticed that I was being hit by this), my only concern with caching the generated asm classes is the fact that it doesn't technically plug the leak, hence why I was trivially (at best) more fond of the per-listener-instance generated classloader, which would provide means for the classloaders to be gc'd along with the generated classes.

caching the asm event executors has downsides and upsides, on the upside, we're saving time by not regenerating them on re-registration of an event handler method, on the flip side, the issue still technically exists, it's just unless you're generating listener classes, you're not going to hit this issue, which I would say is a reasonable compromise, especially as it's a somewhat trivial diff.



```
EventExecutor executor = new co.aikar.timings.TimedEventExecutor(EventExecutor.create(method, eventClass), plugin, method, eventClass); // Spigot // Paper - Use factory method `EventExecutor.create()`
```
would be replaced with:

```
private final Map<Method, EventExecutor> generatedEventExecutors = new java.util.concurrent.ConcurrentHashMap<>();
```


```
EventExecutor asmExecutor = generatedEventExecutors.computeIfAbsent(method, (__ -> EventExecutor.create(method, eventClass)); // Paper
            EventExecutor executor = new co.aikar.timings.TimedEventExecutor(asmExecutor, plugin, method, eventClass); // Spigot // Paper - Use factory method `EventExecutor.create()`
```


I personally believe that plugins that are un/registering listeners are stupid, but needless to say, doesn't matter what I think as plugins are doing that anyway, and the above modification only generates the asm executor once, and is reused for all subsequent registrations, having tested this in a small plugin I slapped together in a few minutes ( https://gist.github.com/electronicboy/e8b7ec6ab2bf4e7ea74c84eedbc080a3 ), I cannot see nor imagine any ill effect of this change beyond the fact that it doesn't really fix the leak but mitigates it

**Comment by ninja-** [comment]
looks good, thank you @electronicboy!

**Comment by ninja-** [comment]
looks good, thank you @electronicboy!
