### ISSUE TITLE
connection-throttle: in bukkit.yml and waterfall does nothing

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#795]
Simply doesn't block reconnecting too quickly any more.

paperclip-1153

**Comment by electronicboy** [comment]
```
// Spigot Start - Automatically set connection throttle for bungee configurations
        if (org.spigotmc.SpigotConfig.bungee) {
            return -1;
        } else {
            return this.configuration.getInt("settings.connection-throttle");
        }
        // Spigot End
```
In the event that bungeecord mode is turned on, the throttle is blatently disabled;

```
if (throttleTracker.containsKey(address) && !"127.0.0.1".equals(address.getHostAddress()) && currentTime - throttleTracker.get(address) < connectionThrottle) {
```
same case if the host address of the person connecting is 127.0.0.1.

basically, craftbukkit/spigot disables the throttle in those two events, otherwise:

![Its alllive](https://i.valaria.pw/170721021132.jpg)

**Comment by ghost** [comment]
Can you test with waterfall? I have nothing that disables the throttling, and it's set to connection_throttle: 4000 in waterfall.yml. It used to work, sometimes recently it stopped. Any player is able to instantly and rapidly reconnect by using two or more game instances.

**Comment by electronicboy** [comment]
This issue tracker is for paper, not waterfall.
