### ISSUE TITLE
[Important] item bug in 1.12 all servers in danger 

### ISSUE THREAD

**Issue by khlfkk** [PaperMC/Paper#799]
[redacted]

**Comment by KurtisAD** [comment]
For now, I suggest canceling all CPacketRecipePlacement until a real fix happens

**Comment by kashike** [comment]
I've removed the description so that this doesn't become well-known before a fix can come out. Thanks for the report.

**Comment by pKalju** [comment]
$$$ Bringing in the money $$$

**Comment by zachbr** [comment]
Closing in favor of private tickets scattered across other trackers.
