### ISSUE TITLE
Probably memory leak

### ISSUE THREAD

**Issue by Xayanix** [PaperMC/Paper#801]
Im using newest PaperSpigot 1.12, my server is getting crashed every 3 hours because of memory out.
There is memory dump:
https://scr.hu/8R9ZO8

**Comment by Xayanix** [comment]
https://scr.hu/GWYvAZ

**Comment by Xayanix** [comment]
NBT crash: https://pastebin.com/Rgv6S5VT

**Comment by itsaphel** [comment]
Can you reproduce without plugins?

**Comment by aikar** [comment]
There was discussion on IRC that the issue was caused by the OP's own plugin doing very bad things with NMS.

OP, if you do reproduce without plugins, open a new issuer.

**Comment by Xayanix** [comment]
Fixed it.
Didn't know that every new EntityPlayers has advancements data on 1.12.

I got another problem, crash every 30 minutes: https://pastebin.com/TSQtCn6C
It is my bad too, or spigot issue?

**Comment by electronicboy** [comment]
watchdog crashes occur when a tick takes too long to complete, this is generally due to plugins taking too long to complete a scheduled task or an event handler that takes too long to complete, very rarely is this type of crash actually triggered by MC itself.
