### ISSUE TITLE
Serious Dup bug

### ISSUE THREAD

**Issue by jordanwilliams1** [PaperMC/Paper#802]
Serious dup bug on the latest build (1155). Also doing on the latest spigot build.

Video:
https://youtu.be/oajgV6yIGAc

Drop an item in your inventory using 'q' then spam the work bench recipe. The bug has been around for a few days. Can take a few trys. Also reported on spigot
https://hub.spigotmc.org/jira/browse/SPIGOT-3451

**Comment by jordanwilliams1** [comment]
This kind of needs to be fixed asap... this is beyond serious.

**Comment by kashike** [comment]
Are you opped on the server?

**Comment by jordanwilliams1** [comment]
@kashike Yes, But we've caught people with full inventories of op stuff and keys and spanwers. It takes a while to do sometimes.

**Comment by FirstReplay** [comment]
v.1155 is also breaking the crafting button functionality on a lot of servers I run. It is a Mojang issue as it's down to the new crafting system.

**Comment by jordanwilliams1** [comment]
Well.. Can we maybe just disable this in the latest build or something for a quick fix :( ?

**Comment by zachbr** [comment]
The system is broken for all non-OPs or people without a specific permission node to allow it.

Breaking the system is the only known solution to the dupe bug.

It will not be altered without good reason (i.e. a true fix)

you can re-enable it by giving players the node, but it will allow your players to dupe again.

**Comment by jordanwilliams1** [comment]
@Zbob750 So this is fixed in the latest version of paper unless people have the minecraft.autocraft permission?

**Comment by zachbr** [comment]
Yes
