### ISSUE TITLE
RecipeBook bug

### ISSUE THREAD

**Issue by DisTrugator** [PaperMC/Paper#804]
When a player (nonOP) try to use recipebook, the items from recipe dissapearing and the item slot from workbench remain empty.
That is happening with the latest devbuild of Paper. With an old build, the problem not exist ...

**Comment by electronicboy** [comment]
Spigot added a permission node for auto-crafting in order to provide a means for server owners to disable the usage of the book: minecraft.autocraft

**Comment by CeIebrimbor** [comment]
@DisTrugator 
Maybe consider keeping the permission off until #805 (the recipe book dupe bug) is resolved.

**Comment by zachbr** [comment]
Disabled as part of a duplication workaround.
This whole mess is being tracked elsewhere.

theres an override permission but I do not recommend it for most servers.
