### ISSUE TITLE
Dupe Bug (update Spigot)

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#805]
Please update to current Spigot to patch this dupe bug on 1.12

https://hub.spigotmc.org/jira/browse/SPIGOT-3451

I see the latest Paper was released a few hours after this was resolved on Spigot, so I have to assume it is not included yet.

**Comment by electronicboy** [comment]
Spigot hasn't patched the issue, they have added a permission node to allow server owners to disable the feature. the issue was marked as resolved under a duplicate.

**Comment by MiniDigger** [comment]
what he is trying to say: the "fix" spigot did is already in paper.

**Comment by CeIebrimbor** [comment]
Is the dupe fixed in Paper after all? Therefore making it safe to give this perm? Or are you saying the permission option is already in Paper (aka the temp fix)?

**Comment by zachbr** [comment]
The temp fix is in Paper, the same one Spigot currently uses.

If you give people the permission node they will be able to use the recipe book feature but also dupe.

If you don’t, they can’t use the recipe book but they can dupe.

Pick your poison.

**Comment by zachbr** [comment]
That should say, if they don’t have the permission, they cannot use the book nor can they dupe. *
