### ISSUE TITLE
Change "Authentication servers are down" message

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#809]
Paper has a few helpful message configurations where Spigot/Bukkit fail to cover (e.g. The kick message when a player is "flying"). This request is the same, but tied to the "unable to connect" message when Mojang's Authentication Servers are down.

**Current default**
"Authentication servers are down. Please try again later, sorry!"
_(this makes players contact the server and tell them their stuff is broken...when in reality it's out of their control and a more descriptive message would prevent that frustration)_

**I would personally make it**
"Mojang's Authentication Servers are currently down. Check here for status: http://xpaw.ru/mcstatus/"

**Comment by willies952002** [comment]
Good Suggestion

**Comment by CeIebrimbor** [comment]
> Good Suggestion, but maybe have it so it is configurable?

That was the request. I posted what I would change it to as an example, but the request is for a configuration option, not a hard set reworded message.

**Comment by phenomax** [comment]
I just had a look at the code of the LoginListener: 
`LoginListener.this.disconnect(new ChatMessage("multiplayer.disconnect.authservers_down", new Object[0]));`
It seems, as normal NMS already uses a config for this message.
Does someone know where to find it? If I'm totally wrong I'll start a PR with a new paper config value for this message.

**Comment by electronicboy** [comment]
That's sending a component which is translatable by the client, meaning that the message will be displayed in the clients configured language as opposed to a hardcoded string as set by the server. Should be pretty easy to implement, however my only concern was retaining the existing behavior, however, from my knowledge and a quick search, you should just be able to place `multiplayer.disconnect.authservers_down` in the default config and it should work fine

**Comment by phenomax** [comment]
Ok. Thanks for the explanation :)

**Comment by kashike** [comment]
https://github.com/PaperMC/Paper/commit/d43da9fc7083e49f628f9a040708d4341534ccea
