### ISSUE TITLE
Bug : Static army of mobs

### ISSUE THREAD

**Issue by aurel85** [PaperMC/Paper#811]
Hi,

I do not know if this bug is linked to PaperSpigot but I'm mostly looking for help to know if anyone has ever seen this.

Since the 1.12, at some places on my maps (maps to be claim via RedProtect or resource maps where there is no protection) some areas loaded by players see the appearance of an army of hostile mobs that are static. They can not move and do not suffer any damage. Commands for kill mobs do not work on these mobs. The only way to remove them is to reboot the server. But they eventually come back when someone loads the area in question. The affected areas have nothing in common.

I regularly update PaperSpigot but nothing changes (at the time of writing this topic I have the 1155). About plugins, I have trouble to know what could cause it, especially that I cannot provoke this bug. Since the beginning of the 1.12 all the plugins you see on the screen are there.

Via the /timings merged these mobs are counted as entities "Player".

My list of plugins : 
A picture to better understand : https://sandbox.fr/images/uploads/original/1501188065.png
And a other picture when it's the most problematic : https://sandbox.fr/images/uploads/original/1501233122.png

Thank you in advance

**Comment by TNTUP** [comment]
Mostly your plugins, I'm on PaperSpigot aswell and I never noticed static mobs^^

**Comment by sgdc3** [comment]
Yeah i remember i had a similar issue on 1.8, but i don't remember the plugin that caused that..

**Comment by electronicboy** [comment]
> Via the /timings merged these mobs are counted as entities "Player".

Definitely a plugin having spawned those, do these entities load when you start the server without any plugins? if so, your best option to remove them is probably to try to use a world editor tool such as mcedit

**Comment by aurel85** [comment]
As long as you do not see them on the server (so at startup especially) the number of entities "Player" in the /timings merged is normal.
This really is from the moment a player loads the affected areas (I do not know why these are those particular areas) that they will appear on the server and as entities "Player" in the /timings merged.
Note that the chunks where these mobs can be found are not regen or other problem.

**Comment by MrPowerGamerBR** [comment]
When I had this issue in my 1.11.2 server it was due to refreshing chunks using the Bukkit API. (I was trying to set blocks via NMS like the good old days™️)

However I didn't see if they shown up in the entity count but your description matches what I had: Entities that didn't move, you couldn't interact with them, butchering them didn't kill them... however idk if they only vanished after restarting, for me it should leave after you switched worlds or relogged.

**Comment by aurel85** [comment]
Even if I set blocks where they are they come back if we remove the blocks and as they are on the surface (although not all the time), this is not good. And if the area is unloaded, they come back directly after my return to the area. As I said above, only the restart will solve the problem temporarily in what I have been able to test.
And despite the restarts since the passage of my server in 1.12 (June 27), they always come back.

**Comment by electronicboy** [comment]
>  And despite the restarts since the passage of my server in 1.12 (June 27), they always come back.

then either the plugin that is placing them in the world is still loaded, or they're actually saved in the world and should be removed using what would probably be a map editing tool such as mcedit.

**Comment by aurel85** [comment]
After a few tests on the plugins that could cause this, I found. This is the SimplePets plugin (with its SimpleAPI dependency). I removed it almost two days ago and more frozen mobs on the horizon. I think the bug comes from a conflict between this plugin and perhaps another one (but which one?) But I intend to change the plugin of the pets on my server because SimplePets does not work correctly on my server.

Thank you all for your help.

**Comment by TNTUP** [comment]
Using EchoPet for 1.12, consider maybe this one :) No issues or whatever :P

**Comment by aurel85** [comment]
It no longer works in 1.12 unfortunately. I just saw a version made by the community. I will test it perhaps, because meanwhile I found another plugin of pets that meets my expectations ;)

**Comment by TNTUP** [comment]
Borlea forked it and it works on my server :)

**Comment by aurel85** [comment]
Good new, thank you for info !

**Comment by TNTUP** [comment]
No problem! 👍
