### ISSUE TITLE
I have a plugin that has a soft-depend but it's loading before the plugin it soft-depends on

### ISSUE THREAD

**Issue by SpaceboiX** [PaperMC/Paper#8130]
### Expected behavior

I have a plugin (SkBee) that has a soft-depend (Skript), SKBee should load before Skript.

### Observed/Actual behavior

I have a plugin (SkBee) that has a soft-depend (Skript), but for some reason SkBee is loading before Skript, therefor SkBee will not load. It appears something is changing load order of plugins.

### Steps/models to reproduce

Just loads SKBee before Skript when booting up the server.

### Plugin and Datapack List

Plugins (74): ajLeaderboards, BendingGUI, BisectHosting, Citizens, CMILib, CoreProtect, eco, EconomyShopGUI, EcoPower, EcoSkills, EnjinMinecraftPlugin, Essentials, EssentialsDiscord, EssentialsGeoIP, EssentialsSpawn, ExcellentCrates, ExtraGear, ExtraHeads, ExtraTools, floodgate, FluffyMachines, FNAmplifications, FoxyMachines, Galactifun, Geyser-Spigot, Graves, GriefPrevention, HoloExtension, HolographicDisplays, InfinityExpansion, InsaneShops, LibsDisguises, Liquid, LiteXpansion, MarriageMaster, MechanicsCore, MobCapturer, Multiverse-Core, Multiverse-Portals, NametagEdit, Networks, NexEngine, PlaceholderAPI, PlayerLands, PlayerParticles, ProjectKorra, ProtocolLib, Residence, ServerListPlus*, SFAdvancements, SimpleMaterialGenerators, SkBee, Skript, Slimefun, SlimefunOreChunks, SlimeTinker, SlimyRepair, SlimyTreeTaps, TARDIS, TARDISChunkGenerator, TranscEndence, UltimateRepairing, UltraEconomy, UltraPermissions, UltraPunishments, VanishNoPacket, Vault, Vehicles, ViaVersion, VotifierPlus, VotingPlugin, WeaponMechanics, WorldEdit, WorldGuard

### Paper version

Paper version git-Paper-58 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
ref this: https://github.com/PaperMC/Paper/issues/5992#issuecomment-878782541

**Comment by Brokkonaut** [comment]
It might be useful if the server would print a warning on startup if there are cyclic soft-dependencies and displays that cycle, as this is most likely unwanted and will cause "random" errors because of the unpredictable load order.

**Comment by electronicboy** [comment]
I think that's gonna make its way into the refactors to the loading system which is going on

**Comment by e-im** [comment]
You can use this [plugin](https://github.com/KittehOrg/SuperLooperSnooper) in order to find dep loops. A built in warning will likely come with paper-native plugins (#8108).
