### ISSUE TITLE
[request] CommandBlockEvent

### ISSUE THREAD

**Issue by Kneesnap** [PaperMC/Paper#817]
It'd be really useful if a CommandBlockEvent could be added that fires whenever a CommandBlock or CommandBlockMinecart executes a command.

Wanted Features:
get/setCommand
is/setCancelled
getExecutor - Returns the Block or Minecart that ran this command.

**Comment by Brokkonaut** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/2c5c611d0c3c198c1ac904e8d64051a8437a8720

**Comment by Kneesnap** [comment]
Haha. 2 days ago. Thanks md_5, look what a fool you've made of me.

**Comment by zachbr** [comment]
👍
