### ISSUE TITLE
Paper breaks Citizens? Steve and Alex skins on every npc

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#824]
I believe this is a Paper issue because LibsDisguises had the same problem with Alex and Steve skins until this commit https://github.com/libraryaddict/LibsDisguises/commit/6306a483e0b9de0b26e16d86e796e4914e50b831.

Citizens hasn't gotten a fix for whatever Paper does i was wondering if you could fix it your side?

Build 1169

![2017-08-01_13 50 56](https://user-images.githubusercontent.com/21323258/28839885-157b0f4c-76c3-11e7-86f8-b63b74dad374.png)

As you see everyone is Steve or Alex..

**Comment by electronicboy** [comment]
Looking at the issue he ~~PR'd~~ commited it for and the responses, the fix that is in that commit isn't really a fix for whatever his issue was, have you tried checking the log file for any errors? does relogging do anything? does running spigot solve the issue? does running an older version of paper solve the issue?

**Comment by Fonzee9** [comment]
On my test server it works with Paper so i guess this is my problem... :(

**Comment by Fonzee9** [comment]
Okay so this is caused by citizens not being uploaded 100% somehow so it didn't have the jarfile for loading skins i reuploaded it and now it works
