### ISSUE TITLE
Sand stacking above barrel y level

### ISSUE THREAD

**Issue by Chris19999** [PaperMC/Paper#825]
**Incompatibility (Bug)**

**What behaviour is expected:**
https://gyazo.com/570992ef8555637567be802062a47dfb
Sand stacks to the y level of the barrel, the rest breaks.
**What behaviour is observed:**
https://gyazo.com/74c2b971a8d3ad29aa5d9e169ae335fd
Sand stacks above the y level of the cannons barrel.
**Steps/models to reproduce:**
Only happens on my server when an existing sand stack is aligned with the barrel slightly lower and more sand than needed is fired. Same with any cannon.
**Plugin list:**
https://gyazo.com/4a41b2e60854078612c7434747114e06
**Paper build number:**
https://gyazo.com/75fd35b5c02bd8a40615ee388fbc6b69’

_This may be due to the server having different game ticks and the slab bust firing upwards. I'm not a very experienced cannoner so please excuse my lack of knowledge._

**Comment by electronicboy** [comment]
We don't support outdated versions

**Comment by Chris19999** [comment]
So how am I supposed to patch this on a 1.8.8 server?

**Comment by MiniDigger** [comment]
You are supposed to do it yourself (paper is open source) or get someone to do it. There is no official support for ancient versions.
