### ISSUE TITLE
Abstract usage of Mojang's auth library in Paper API

### ISSUE THREAD

**Issue by aramperes** [PaperMC/Paper#828]
Hi everyone. 
This [patch (API-0058)](https://github.com/PaperMC/Paper/blob/7962fe6489ba312f2c4da637851b36f0c9dd56a0/Spigot-API-Patches/0058-Profile-Lookup-Events.patch) introduces the use of Mojang's `authlib` library. That library is used by the 'Profile lookup events' API without any abstraction.

Coming from the [Glowstone](https://github.com/GlowstoneMC/Glowstone) project, we would really appreciate it if the Paper API did not depend on Mojang libraries because we have our own clean-room implementation of the authentication system. Our API, [Glowkit](https://github.com/GlowstoneMC/Glowkit), directly depends of Paper API (with our own patches on top of it). Since we do not want to have any Mojang libraries/binaries bundled with our software and APIs, we cannot update our API since that patch, thus blocking us from updating to 1.12.1+.

In my opinion, you could create a new, 'Profile API' for Paper that would be implemented by the Paper server software -- thus removing the library from the API. This would break any plugin currently using the Auth library directly from these events, which is why approval is needed here. I believe an API should not be using platform/version/vendor-specific libraries, because it has not been done before by the Bukkit/Spigot/Paper projects.

I understand developing such an API and a Mojang-authlib implementation would take time, but this is blocking us from future updates (unless we use this Mojang library in our software). I would gladly participate in contributing if this proposal is something you're willing to go forward with.

**Comment by jamierocks** [comment]
Absolutely agree - would be nice for https://github.com/PaperMC/Paper/pull/33 to have been merged.

**Comment by zachbr** [comment]
I agree as well and I believe @electronicboy has also expressed interest.

Regardless of who does the work, I would like to see this changed for 1.13 as it _will_ result in an API breakage.

**Comment by aramperes** [comment]
FYI I am no longer the project lead for Glowstone, so you may contact @mastercoms here instead of myself.

**Comment by aikar** [comment]
I'm fine with the idea if someone does the work. We went this approach because it's simple, it is an API, and saved tremendous amount of time.

Though on other hand, IANAL, but considering this is an open source lib provided for public use, i'm not sure it would compromise the project goals for Glowstone, but I agree abstract is 'safest'.

I am likely one of the only few users, so fine with me.

**Comment by zachbr** [comment]
It is not an open-source lib. It's a viewable-source lib.
We have absolutely no rights to it, as has been confirmed elsewhere by Mojang.

**Comment by aikar** [comment]
Ah ok. thought it was open source (just thought they don't post to github as they don't want to support it)

**Comment by aikar** [comment]
Hi @momothereal we are nearing 1.13, you mentioned helping build a replacement API, is this something you're still able to do? We want to target the switch for 1.13

**Comment by aikar** [comment]
Actually I'm working on this now, I thought of some pretty simple approach to it.

**Comment by aikar** [comment]
As of https://github.com/PaperMC/Paper/commit/71c18fd5c9e3520fd8ebc3029be7a56487c77475 this is now done. Every API using GameProfile now has a replacement PlayerProfile API, so all we will do in 1.13 is drop the GameProfile references/methods and the dependency.

https://github.com/PaperMC/Paper/commit/531981a1cc057ad7c3bf5f95a285aa01922cfb62
https://github.com/PaperMC/Paper/commit/18e3bf685cb0f84832e332422b0584daa0c66f57

So @momothereal you can now update to latest paper and remove them yourself. 

You should be able to add our interface to your existing PlayerProfile class, but properties may be a bit tricker. good luck!
