### ISSUE TITLE
Szerver Crash

### ISSUE THREAD

**Issue by Eror32** [PaperMC/Paper#831]
Hello Andris!
Kérlek majd látogass fel a szerverre,mert valami gond van,mert a szerver mindig újra indul,és senki nem tudja hogy mi ez. Lehet hogy valaki restone.zik,de az is lehet hogy az én Big Capacitatorom csinálja ezt,kérlek üzenj,és csinálj vele valamit,előre is köszönjük!

Üdv:Error32

**Comment by andris155** [comment]
Ez nem ide való. XD

**Comment by electronicboy** [comment]
1. Issues are supposed to be in English
2. We are not going to join your server, nor is this issue tracker for personal support.

**Comment by andris155** [comment]
This is TerrianControl crash and not Paper...

**Comment by Eror32** [comment]
Andris155 tudom,de csak értesíteni szerettelek volna valahogy,de máshogy nem nagyon tudtam megoldani,ez jutott leg elöbb az eszembe. :/
