### ISSUE TITLE
RCON

### ISSUE THREAD

**Issue by Kubus6969** [PaperMC/Paper#832]
Hi, Im making itemshop, and I need RCON to do this. And my question is why I command from skripts doesnt work on paperspigot?
https://pastebin.com/Vazgnuk3
Can you fix it?

**Comment by mikroskeem** [comment]
1) Seems more like an issue related to plugin providing given command
2) `org.bukkit.craftbukkit.v1_8_R3...`, well we do not support older versions in any capacity.

**Comment by Kubus6969** [comment]
But if I want to play with version 1.8? so I cant get support?

**Comment by mikroskeem** [comment]
Exactly! :smile:

**Comment by aikar** [comment]
we dont support below 1.12 and doesnt even look to be paper related, contact plugin author
