### ISSUE TITLE
Server crashes frequently

### ISSUE THREAD

**Issue by airoons** [PaperMC/Paper#834]
So my server after a few amount of hours crashes, I can't find what is the cause of that. Here is the recent crash, actually it even doesn't generate a Crash report, server just stops responding: https://pastebin.com/4Vu4WRD0

Yesterdays logs, they haven't changed at all today: https://timings.aikar.co/?id=c233f67b1e174e5986717c983c23c6cf

I'm using newest PaperSpigot 1.8.8. Please help!

**Comment by zachbr** [comment]
We don’t support 1.8.8 in any capacity.
