### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Behoston** [PaperMC/Paper#836]
# Crash, Stacktrace

### Link/paste of stack trace
https://paste.ofcode.org/hXkHb5nr4JGhqLKdV7cGsG

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit: https://paste.ofcode.org/TpQU3vm4yeLBR6aukzPfD8
spigot: https://paste.ofcode.org/tku3TdyfaYViBHWGkaV2cS
paper: https://paste.ofcode.org/fY3Mur48a2wbbpPpCSzJDx
server: https://paste.ofcode.org/36R4AzsFpeWqkXky8pNHYzp

### Paper build number:
b1170 (I don't have access to console now)

### Plugin list:
```AreaShop.jar
AuthMe-5.3.2.jar
AuthMeBridge-1.6.2.jar
AutoMessage.jar
BungeeTabListPlus_BukkitBridge-2.8.0.jar
ChatEx.jar
citizens-2.0.22-SNAPSHOT.jar
denizen-1.0.2-SNAPSHOT.jar
Essentials-2.x-SNAPSHOT.jar
EssentialsGeoIP-2.x-SNAPSHOT.jar
EssentialsSpawn-2.x-SNAPSHOT.jar
Factions.jar
FastAsyncWorldEdit-bukkit-17.06.09-0f3138e-713-13.0.17.jar
FoundDiamonds.jar
LibelulaLogger.jar
MassiveCore.jar
mcMMO.jar
MobArena.jar
MultiCommand-2.2.1.jar
Multiverse-Core-2.5.jar
Multiverse-NetherPortals-2.5.2-SNAPSHOT.jar
Multiverse-Portals-2.5.1-SNAPSHOT.jar
NoCheatPlus.jar
PermissionsEx-1.23.4.jar
ProtocolLib.jar
PurpleIRC.jar
Quests-2.8.6.jar
SkinsRestorer-v13.1.2.jar
Spectator-1.3.4.jar
Vault.jar
WorldBorder.jar
WorldEdit.jar
worldguard-6.2.1.jar
```

**Comment by electronicboy** [comment]
these types of crash reports are generally unreliable, however it looks like denizen if that report is accurate.
