### ISSUE TITLE
Paper 1173 is busted don't use it!!! 

### ISSUE THREAD

**Issue by Fonzee9** [PaperMC/Paper#838]
Paper 1173 is missing some code that plugins use and is causing errors and crashes!

My estimate is you can't use Paper 1173 for more then 10 minutes it will crash!!

Stick with Paper 1172 until it is solved.

**Comment by DenWav** [comment]
Quality shit right here.

**Comment by Fonzee9** [comment]
This wasn't meant as a joke i had to downgrade to 1172..

**Comment by Fonzee9** [comment]
1173 is broken

**Comment by Deamon5550** [comment]
Then perhaps you should post what the error is.

**Comment by Fonzee9** [comment]
It is messing up a lot of plugins.. and it crashes the server downgrading fixed that problem

**Comment by Fonzee9** [comment]
Something they changed in 1173 messed up Paper and broke it

**Comment by MiniDigger** [comment]
If you want actual help, you need to start posting a stack trace and the affected plugin, else your report is useless
