### ISSUE TITLE
Bad lag with Paper's Lighting Queue and Block#setType

### ISSUE THREAD

**Issue by lucko** [PaperMC/Paper#841]
# Performance issue
The best way for me to describe the issue is to just show you the code I'm using..

Basically, we have a plugin which listens to the `BlockFromToEvent` and detects when cobblestone is generated through the interaction of Lava+Water.

The plugin then randomly changes this block to a certain ore. We've been using the same code for a while (probably at least 1 year), and it has never been an issue until recently. 

Here's the code: https://gist.github.com/lucko/2a30bfff357762f854fec3793f4f31e8

From looking at Timings and running WarmRoast, it seems the issue stems back to the `PaperLightingQueue`.

###  Timings or Profile link:

Here's the profile of the event. 
https://i.imgur.com/djl9rUO.png

I know you specifically request that people don't post screenshots, but I've expanded the nodes as much as is necessary/possible.

I can also provide a timings, but really this just shows the same thing in a less detailed manner. (https://i.imgur.com/XHwkV2d.png)

To put the 33% into perspective, there was probably ~250 players on that instance when I recorded that data. We average around 10-15k chunks loaded at any one time.

### Paper build number:

```
> version
[13:46:52 INFO]: This server is running Paper version git-Paper-1171 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
```

Thanks in advance.

**Comment by lucko** [comment]
I was poking around the `BlockFlowing` class and came across the `BlockFormEvent`, which solves the issue for us. (no clue why the original dev of the plugin didn't use it :P ) 

However, the lag we were experiencing previously I assume is still an issue, despite us using the wrong event.

**Comment by electronicboy** [comment]
from your report, I'm going to guess that you actually have the light queuing mechanism turned off and it's just running modifications as soon as they occur as opposed to queuing them, just as they would in spigot and above.

turning it on would allow the server to actually queue up modifications, however the major advantage of the queue for async lighting modifications was removed a while back, so I don't think there would be all that much of an advantage of doing so, light updates are just kinda slow to the point that if you trigger them a lot, it's going to hurt a lot :/

**Comment by lucko** [comment]
I switched to `BlockFormEvent`. Performance is better, but queueing the lighting updates is still occupying nearly 8% of the tick.

https://i.imgur.com/wRx8XIb.png

You were right, queued lighting updates were disabled, I've set that to true and will let you know if that helps.

Is there a method which will allow me to change the block type without causing a lighting update? If I call `BlockState#update` with physics disabled, for example?

**Comment by aikar** [comment]
There is not a fault in the code, any % you see in the queue is simply percentage that would of been elsewhere in an uncontrolled manner without the queue.

The queue has the capability to limit itself and avoid it being 'as bad' as without the queue.

So it is always recommended to use the queue unless you run into a bug with it (And higher timings is NOT a bug, do not turn off the queue just because timings are higher in it)

**Comment by lucko** [comment]
Yep, understood.

Thanks for your help.
