### ISSUE TITLE
worldborder not changeable

### ISSUE THREAD

**Issue by melinstagibson** [PaperMC/Paper#845]
Im unable to expand the worldborder past the former limit (i was on 1.12 back when i set it) i can make it smaller, but i cant make it larger than what i set it to.
restarting didnt help.
If i do "/worldborder get" it tells me the correct value but its not actually there. 

As you can see in the screenshot i am at 1.000.000 x and z and set the worldborder to 60.000.000 but its till right in my face and i cant get past it. If i do i die and cant place blocks just like its supposed to be.

![2017-08-09_13 38 32](https://user-images.githubusercontent.com/19364770/29120127-3b6e187e-7d09-11e7-8b0c-d9345350e823.png)

**Comment by electronicboy** [comment]
Can you replicate this without any plugins? I've just tested this and cannot seem to replicate this issue on a local server, I do remember there being some issues with it in spigot a while back, but could never replicate the issue to test

**Comment by melinstagibson** [comment]
just forget i was here :/
