### ISSUE TITLE
EntityTracker Crash

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#847]
Paper version git-Paper-1162 (MC: 1.12)
Log: https://hastebin.com/kotiquxela.vbs
Crash report: https://hastebin.com/dohuroluje.sm

Any idea what caused this?

**Comment by electronicboy** [comment]
`java.util.ConcurrentModificationException: null`
something is modifying something in an unsafe manner, most likely a plugin as I can't see anything in there that could cause that from a glance

**Comment by SecretlyJealous** [comment]
Could it be related to this?
https://hastebin.com/tosivedequ.vbs

**Comment by electronicboy** [comment]
well, it sure as heck says that you probably have horrible plugins doing horrible things on your server, so directly related, who knows, a sign that you have something on your server that isn't doing nice things and harming it, yes
