### ISSUE TITLE
Essentials Bed Homes Get Erased with Paper

### ISSUE THREAD

**Issue by BaltimoreCalling** [PaperMC/Paper#85]
Some essentials bed homes (node essentials.home.bed) are unreachable when switching from Spigot to Paper (latest version).

Not sure the reason, but it may be related to https://hub.spigotmc.org/stash/projects/PAPER/repos/paperspigot/browse/Spigot-Server-Patches/0078-SPIGOT-1387-Resolve-bed-issues-on-unloaded-chunks.patch

Current essentials: b6f980aebafc73544595fd04427d229a7e497b21

**Comment by zachbr** [comment]
That patch doesn't even exist in Paper 1.9
edit: and I assume you're running the supported EssentialsX fork not actual Essentials right? Because it's been unsupported by its own authors for some time now.

**Comment by Techcable** [comment]
@vemacs should fix this so peopl stop complaining

**Comment by BaltimoreCalling** [comment]
Found the steps to reproduce the issue, with no plugins. Posted in issue #157
