### ISSUE TITLE
removeTileEntitiesForRemovedChunks Crash

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#851]
Recently had this crash, mentions something about removing tile entities but not entirely sure if it's related: https://hastebin.com/yipusuvehu.php
Log: https://hastebin.com/vusucotayo.sql
Using Paper version git-Paper-1182 (MC: 1.12.1)

**Comment by zachbr** [comment]
Drop to build 1180.

I haven’t looked yet, but I believe I made an incorrect assumption in testing. I’ll fix it later, but rolling back to 1180 will get you up and running until I do.

**Comment by SecretlyJealous** [comment]
Thanks, I'll use 1180 for now.

**Comment by zachbr** [comment]
Build 1184 should fix this issue.
Thanks for the report.
