### ISSUE TITLE
Crash related to Player Chunk or List?

### ISSUE THREAD

**Issue by ryans1230** [PaperMC/Paper#852]
Random crash, didn't see anything useful before it that may have caused it.

https://hastebin.com/ufubufuyoc.rb

**Comment by electronicboy** [comment]
Server overloaded/slow disks?

Looks like the crash was caused as somebody joined and the server was waiting on another thread doing a read before it could log in, could also be a case of something lagged and happened to end up with the watchdog triggering in a spot where there is a bit of work to do.

**Comment by ryans1230** [comment]
I've never had the error before, so I don't think it would have come from a server overload. I just did the update last night to 1.12.1. However, that's the only time I got the error so it could have been a unique problem
