### ISSUE TITLE
Inventorys are filled with books.

### ISSUE THREAD

**Issue by enlyow** [PaperMC/Paper#856]
### Problem:

Absolutely all players inventorys are filled with books. Nothing can be done with books. They are not thrown away and they are on all slots. After rebooting the server, everything is fine. It happens rarely.

![63636](https://user-images.githubusercontent.com/29000881/29417232-294bd668-8371-11e7-9ad6-49860a5441e8.png)

**Comment by enly1337** [comment]
After rebooting the server, everything is fine. It happens rarely.

**Comment by electronicboy** [comment]
This is an issue with ProtocolSupport, https://github.com/ProtocolSupport/ProtocolSupport/issues/632

**Comment by enlyow** [comment]
Ohh.. Sorry to disturb this stupid problem and not bother to search. :/
