### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by CDAGaming** [PaperMC/Paper#857]
When Compiling from Source, i Get this error(Keep in mind this is run from Git Bash with all Requirements)

$ ./paper jar
Downloading unmapped vanilla jar...
Applying class mappings...
Applying member mappings...
Creating remapped jar...
Installing remapped jar...
Extracting NMS classes...
./scripts/decompile.sh: line 16: jar: command not found
Failed to build Paper

**Comment by phenomax** [comment]
What does 
`java -Version` 
show?

**Comment by CDAGaming** [comment]
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by CDAGaming** [comment]
Looked it up, i was missing a PATH Variable to jar.exe, seems to be working now
Will Close this Issue if It goes fully now
