### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SirGorStudio** [PaperMC/Paper#8594]
### Expected behavior

When i start the minecraft server the  commandprompt it crashed and i tryed to uninstall it and reinstall it still crashes

### Observed/Actual behavior

it crashes

### Steps/models to reproduce

idk

### Plugin and Datapack List

none

### Paper version

1.19.2

**Comment by electronicboy** [comment]
Please use the discord for support, check the logs too

**Comment by SirGorStudio** [comment]
bruh ok
