### ISSUE TITLE
Can't invert observer signal / signal shorter than 1 tick

### ISSUE THREAD

**Issue by melinstagibson** [PaperMC/Paper#863]
So i don't know what your guys opinion is about this "possibly intended behaviour" but to me it seems wrong. 
Basically you cant invert an observer block signal because the signal is too short (something less than 1 tick) which works with pistons and repeaters but it wont work with redstone torches. And if you put a repeater behind the observer the signal becomes too long for a T-Flio-Flop.

This thing is really bugging me since i work with redstone alot and it just makes no sense.
I would understand it if you accept it as intended but it would be awesome if you could still add a config option to make them output 1 tick signals like it should be.

here is mojangs bug report https://bugs.mojang.com/browse/MC-107410

**Comment by zachbr** [comment]
Personally I am generally not a fan of tinkering with redstone behavior.
That being said I will mark it as a feature and if anyone wants to make this change, test it, and PR/commit it, they're more than welcome to.

**Comment by Proximyst** [comment]
Fixed by Mojang in MC-107410.
