### ISSUE TITLE
Crash java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#864]
Paper version git-Paper-1186
Crash: https://hastebin.com/nixoduzelu.sm
Log: https://hastebin.com/pobozazebi.sql

**Comment by electronicboy** [comment]
You more than likely have a chunk with too many items in it, shamefully this is a flaw in how minecraft handles chunks and likely won't be fixed unless they do

**Comment by electronicboy** [comment]
Closing, This is a vanilla downfall with chunks that have a large amount of blocks with additional data and really isn't all that much of an issue unless you specifically start shoving a lot of such blocks in there. Not really all that much we can fix here.
