### ISSUE TITLE
issue with using anvil right click the skull

### ISSUE THREAD

**Issue by sleepyr-sa** [PaperMC/Paper#868]
# Incompatibility (Bug)

### What behaviour is expected:
whatever what kind of skull (player/creeper/zombie...etc) should not be removed (In gamemode 1) or become skeleton skull (In gamemode 0)
### What behaviour is observed:
when player using anvil right click the skull, it become a skeleton skull
edit: minecraft singleplayer would drop the skull after placing the anvil same place on skull (gamemode 0)

### Steps/models to reproduce:
https://www.youtube.com/watch?v=am_v4fnHPa0&feature=youtu.be
https://www.youtube.com/watch?v=PChlbyiusCU&feature=youtu.be

### Plugin list:
tested in no plugin environment

### Paper build number:
git-Paper-1196 (MC: 1.12.1)

**Comment by Black-Hole** [comment]
It looks like a skelleton skull for this player only. Just relog to see that it's not changed on the server side.

**Comment by sleepyr-sa** [comment]
update: minecraft singleplayer would drop the skull after placing the anvil same place on skull (gamemode 0)
update 2: become skeleton skull only on worldguard / skyblock  protected area and it changed on the server side (which i guess not paper problem)

**Comment by 0-x-2-2** [comment]
this is a worldguard issue

**Comment by electronicboy** [comment]
The first issue I can replicate in CraftBukkit, more than likely it's just updating the state of the block there without considering what is already there.

as for the latter, another bug in CraftBukkit as it's more than likely not sending the actual block meta back once the placement is cancelled.
