### ISSUE TITLE
Anvil Combining Issues

### ISSUE THREAD

**Issue by MineF** [PaperMC/Paper#869]
# Incompatibility (Bug)

### What behaviour is expected:
Being able to combine enchanted tools/armor in Anvils. 
### What behaviour is observed:
Does not work with STOCK Paperspigot. 
### Steps/models to reproduce:
1. Place down Anvil 
2. Add enchanted books to enchanted tool/armor 
3. The output doesn't include much of the time the enchanted book enchant

### Plugin list:
This was tested with ZERO plugins
### Paper build number:
[19:03:24] [Server thread/INFO]: This server is running Paper version git-Paper-1196 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
# Crash, Stacktrace
no crash or error outputs.

**Comment by electronicboy** [comment]
that just sounds like standard vanilla mechanics, not all items can be enchanted with all books, and some enchants are incompatible with others.

**Comment by MineF** [comment]
Hello, I can confirm that it would not work as it should. As I tested it in creative mode (and my player did outlining this issue).  

For example I cannot add/enchant Protection onto an enchanted armor piece. 
The player cannot add enchants to a fishing rod with efficiency, mending, and luck I think...

**Comment by electronicboy** [comment]
unable to replicate any issues, as before, there are enchantments that are incompatible with other enchantments, more than likely you're trying to use books that are either incompatible with the existing enchants on the item, or are just not compatible with the item in question. This is a vanilla mechanic, not a bug.

**Comment by KeksNino** [comment]
ive had the same issue

**Comment by PedroMPagani** [comment]
> ive had the same issue

If you're in 1.12 this is not supported, if on the latest version I recommend you create an issue report
