### ISSUE TITLE
High Minecraft::Bukkit Scheduler timing

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#87]
With Paper 496 there is a problem that causes the server to use 40% of a tick to calculate something with Minecraft::Bukkit Scheduler after a few hours of server uptime.

Here a screenshot of the timings report (I read that we should keep timings v2 private, is that correct?):
http://i.imgur.com/RbZFIzg.png

**Comment by ghost** [comment]
In the last minute it got even worse: The Minecraft::Bukkit Scheduler task takes now 80ms per tick.

**Comment by zachbr** [comment]
There is no security risk in making it public. Providing just screenshots actually inhibits our ability to help you and/or fix the problem

**Comment by ghost** [comment]
Would appreciate it if the timings could be removed after you got them:

_Removed..._

**Comment by zachbr** [comment]
Why would I do that? No one can help you or properly diagnose this without them, there is zero security risk in leaving them.

**Comment by meytro** [comment]
I have my reasons for it. I will remove the links if the issue is closed.

Hope that we now can find the cause of the problem ;)

**Comment by ghost** [comment]
Issue can be closed, can't find the exact problem. If I got more information I will post a new issue report.
