### ISSUE TITLE
[bug]: duplication glitch

### ISSUE THREAD

**Issue by VulcanoSoftware** [PaperMC/Paper#8704]
### Expected behavior

a duplication glitch

i was crafting in the crafting bench, and i accidentaly picked 30 copper ingots, and putted it back in my inventory very fast, after that there were 60 copper ingots

### Observed/Actual behavior

a duplication glitch

i was crafting in the crafting bench, and i accidentaly picked 30 copper ingots, and putted it back in my inventory very fast, after that there were 60 copper ingots

### Steps/models to reproduce

1) i go to the crafting table
2) i craft some sticks
3) i accidentaly picked some copper out my inventory
4) i putted the copper back in my inventory very fast
6) 30 copper ingot turned into 60 copper ingots

### Plugin and Datapack List

Plugins (62): AdvancedLogger*, AdvancedReplay*, AuctionHouse, BlueBorder, BlueBridgeCore, BlueBridgeGP, BlueMap, BlueMap-Marker, BottledExp, ChestsPlusPlus, Chunky, ChunkyBorder, Citizens, CMILib, ColorPortals, CommandDefender, CommandPanels, CoreProtect, CraftableSaddles, CropClick*, DeathChest, DeathCoordinates, DecentHolograms, DiscordEconomyBridge*, DiscordSRV, DiscordSRVUtils, Drugs, Economy, GriefPrevention, InteractiveChat, InteractiveChatDiscordSrvAddon, ItemBridge, JukeBox, LightAPI, LuckPerms, Multiverse-Core, MyCommand, NetherView, NoteBlockAPI, Nova, OpenInv, PermissionShopZ, PlaceholderAPI, Plan, PlayerNPC, PlugManX (PlugMan), ProtocolLib, PvPManager, QualityArmory, RampenDrills, RealEstate, Recipedia, RightClickHarvest, SalaryManager, SimpleFarts*, SkinsRestorer, SmoothTimber, spark, TabuuCore, UltimateHomes, Vault, Villagerleash

There are 34 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/hostile-safari-nets-v1-1.zip (world)], [file/passive-safari-nets-v1-1.zip (world)], [file/horses-of-rohan-v2-0-1.zip (world)], [file/crossbow-infinity.zip (world)], [file/WASD Libraries V6.9.2.zip (world)], [file/WASD Swords V3.2.3.zip (world)], [file/WASD Crazy Swords V1.1.6.zip (world)], [file/WASD Diamond Swords V1.1.6.zip (world)], [file/WASD Moar Diamonds V1.4.4.zip (world)], [file/WASD Moar Totems V1.4.7.zip (world)], [file/WASD Moar Crossbows V1.3.8.zip (world)], [file/WASD Moar Helmets V1.5.4.zip (world)], [file/WASD Moar Pickaxes V2.1.1.zip (world)], [file/WASD Get All Recipes V1.0.0.zip (world)], [file/WASD Moar Pearls V2.0.6.zip (world)], [file/WASD Redstone Devices V2.1.5.zip (world)], [file/WASD Moar Apples V2.0.7.zip (world)], [file/anti creeper grief v1.1.3.zip (world)], [file/anti enderman grief v1.1.3.zip (world)], [file/armored elytra v1.0.6.zip (world)], [file/coordinates hud v1.2.3.zip (world)], [file/count mob deaths v1.1.3.zip (world)], [file/durability ping v1.1.3.zip (world)], [file/nether portal coords v1.1.3.zip (world)], [file/redstone rotation wrench v1.1.4.zip (world)], [file/silence mobs v1.1.3.zip (world)], [file/terracotta rotation wrench v1.1.4.zip (world)], [file/track raw statistics v1.5.3.zip (world)], [file/track statistics v1.1.4.zip (world)], [file/villager death messages v1.2.4.zip (world)], [file/villager workstation highlights v1.1.3.zip (world)], [file/copper.zip (world)]

### Paper version

20.12 16:26:18 [Server] [INFO] Checking version, please wait...
20.12 16:26:18 [Server] [INFO] Current: git-Purpur-1872 (MC: 1.19.3)*
20.12 16:26:18 [Server] [INFO] Previous: git-Purpur-1845 (MC: 1.19.2)
20.12 16:26:18 [Server] [INFO] * You are 4 version(s) behind
20.12 16:26:18 [Server] [INFO] Download the new version at: https://purpurmc.org/downloads

**Comment by PedroMPagani** [comment]
Replicate the glitch without any plugin in the server

**Comment by electronicboy** [comment]
Not paper, you'd also generally need to reproduce in a clean environment without plugins given how often they can be the cause, security/dupes should also be reported on the discord
