### ISSUE TITLE
Storms do not produce lightning bolt

### ISSUE THREAD

**Issue by ElHacker1000** [PaperMC/Paper#8719]
### Expected behavior

I expected to see lightning bolt every so often when using the /weather thunder command for initialize a storm.

### Observed/Actual behavior

No lightning bolt appears

### Steps/models to reproduce

Just use the /weather thunder command and wait a minute to see if lightning appears.

### Plugin and Datapack List

None

### Paper version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version

### Other

**I Tried**

- Uninstall all plugins
- Use /summon lighting_bolt (works)
- Search in google and the list of bukkit, spigot and paper issues
- check the default configuration of bukkit, spigot and paper
- reinstall the server

**Comment by Owen1212055** [comment]
1.18.2 is no longer supported, please try to see if you can reproduce this latest 1.19.3.

**Comment by ElHacker1000** [comment]
293 / 5.000
Resultados de traducción
Resultado de traducción
I suppose they release a version and after a year it "is no longer supported"? How much do I have to pay per month to change a policy like this?

this doesn't happen in Python, support lasts.

Anyway, I'll edit the post to receive help for 1.19.2 and see if the solution applies to other versions.

**Comment by ElHacker1000** [comment]
Ok! Understand!... Well. Tomorrow test in 1.19.3 and ask for a solution in this version. After, i apply to my version.
