### ISSUE TITLE
[Plugin help] Open chest's inventory sometimes only get the captured inventory snapshot?

### ISSUE THREAD

**Issue by collller** [PaperMC/Paper#880]
long time ago i made a plugin called "void backpack" with paper1.9.4

in this plugin, when player click chestwith itemstack, the chest's world,x,y,z will log to item's lore.
when player right click with this item , plugin will found this chest with "world/x/y/z information" form item's lore ，and open the chest's inventory to player.

it's worked perfect with paper1.9.4/1.10.2/1.11.2

but when i update server to 1.12.1 , lot of player Complain to that they lost item with “void backpack”.

at first i think the reason is unload chunk and i try chunk.load()  before openinventory，and add a task "wait 1 second" ,some boolean like "chest.isPlaced()", "chunk.isLoad()"

but players still lose item .and they can get item from this fake inventory but chest still have it.

i think some of them just get the captured inventory snapshot?

>getBlockInventory
>Inventory getBlockInventory()
> Gets the inventory of the chest block represented by this block state.
> If the chest is a double chest, it returns just the portion of the inventory linked to the half of the chest corresponding to this block state.
> If the block was changed to a different type in the meantime, the returned inventory might no longer be valid.
>###  If this block state is not placed this will return the captured inventory snapshot instead.
  
just need some help  if you not busy, am i do something wrong?

**Comment by electronicboy** [comment]
in 1.12.1 spigot updated the BlockState implementation, methods such as getBlockInventory() will returns a snapshot of the inventory from the blockstate, not the actual inventory; should you wanna modify the inventory you should get the BlockState of the chest and use getBlockInventory() on the snapshot and call update on the snapshot itself.

**Comment by collller** [comment]
thanks 
you mean i should update the chest when snapshot on `InventoryClickEvent` and `InventoryCloseEvent` ?
or i will never get the actual inventory and give up this , find another way to do it？
:-D

**Comment by collller** [comment]
this issue has been fixed by paper #1203，thanks for your hard work！;-)
