### ISSUE TITLE
[Question] Strange timings -> InventoryMoveItemEvent

### ISSUE THREAD

**Issue by ArtNRG** [PaperMC/Paper#885]
# Performance issue
###  Timings or Profile link:
https://timings.aikar.co/?id=ff47a0f6b8a348eea7f055f97f6410b9#plugins

### Description of issue:
Sometimes my server just starting to lag, timings show me above 15% of InventoryMoveItemEvent, TPS become about 10-15. Sometimes i see this problem when i have about 30 online, sometimes 50. Sometimes there is 60 online and all is ok.
After a while all become ok without any reasons.
Please help me to figure out why it is. Is it paper problem or plugins issue? How to fix it?

### Plugin list:
https://pastebin.com/iRg244rd
### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml https://pastebin.com/8QiUB7NE
spigot.yml https://pastebin.com/BCZsb4X1
paper.yml https://pastebin.com/yYgZYvGx
server.properties https://pastebin.com/M0hvy8sL

### Other helpful links
Server is hosted on dedicated OVH hosting
Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz, 8 cores
If i should add here something, i'l add, just ask.

### Paper build number:
git-Paper-1204 (MC: 1.12.1)

**Comment by Shevchik** [comment]
Real this issue, it will explain why

https://github.com/PaperMC/Paper/pull/445

**Comment by NicoNekoDev** [comment]
It's because of ChestShop. Plugin is outdated and uses deprecated/old methods. Find another shop plugin.

**Comment by aikar** [comment]
@nicuch that statement is not true.

There is no problem here, but simply any plugin that makes use of this event will cause performance problems.

However, it is currently the only way to even do protections for chests/hoppers.

The best you can do is see if you can live without the feature chest shop uses that event for, and ask them to make it optional to not register that event if so.
