### ISSUE TITLE
Netty Epoll Server IO ERROR  in 1.12.2 

### ISSUE THREAD

**Issue by khlfkk** [PaperMC/Paper#888]
Build 1207 with Netty Epoll Server IO ERROR in 1.12.2 server.

# Performance issue
spam console

###  Timings or Profile link:
___We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real
cause of the issue.___

### Description of issue:

https://pastebin.com/AbF1XaU2

### bukkit.yml, spigot.yml, paper.yml, server.properties
___Gist/pastebin/hastebin links___
### Other helpful links
___The more information we receive, the quicker and more effective we can be at finding the solution to the
issue.___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

# Incompatibility (Bug)

### What behaviour is expected:
___What you expected to see___
### What behaviour is observed:
___What you actually saw___
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

# Crash, Stacktrace

### Link/paste of stack trace

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Plugin list:
___A list of your plugins___
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

# Suggestion

___We love suggestions! Suggestions are fairly unstructured, and will be treated as such___

**Comment by MiniDigger** [comment]
That's an issue with featherboard, report it to the author.

**Comment by MiniDigger** [comment]
Actually this is a duplicate of #887, update paper to fix the issue

**Comment by khlfkk** [comment]
i will try the latest build. Thanks!
