### ISSUE TITLE
Spawning animals, while disable mob spawn

### ISSUE THREAD

**Issue by Lennyss** [PaperMC/Paper#893]
So i use this paper spigot version(http://scr.hu/1det/3ld9t) i made old school 1.8.8 server thats why i can't run on newest version.(ONLY ONE PLUGIN IN SERVER WHITH THIS CODE)
i made this in plugin:
    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onMobSpawn(CreatureSpawnEvent event) {
        if (event.getSpawnReason() != CreatureSpawnEvent.SpawnReason.CUSTOM) {
            event.setCancelled(true);
        }
    }
animals still spawning
in server properties:
spawn-animals= false
texture-pack=
snooper-enabled=false
hardcore=false
online-mode=false
resource-pack=
pvp=true
difficulty=3
enable-command-block=true
player-idle-timeout=0
gamemode=0
max-players=199999
spawn-monsters= false
animals still spawning
in bukkit.yml
spawn-limits:
  monsters: 0
  animals: 0
  water-animals: 0
  ambient: 0
animals still spawning
what should i do?

**Comment by electronicboy** [comment]
We don't support outdated software, your issue is also most realistically caused by something installed on your server.
