### ISSUE TITLE
absolute paths

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#897]
I have this custom software from @yawkat that allows players to have their own server on my server, and with recent updates I get this error now: https://gyazo.com/d607a01fcf1ad768aa68285767452f91

I believe the issue is somehow related to the servers being run in docker containers, so I am posting an issue here in case it might not be something he can fix in the software, and it only happened as a result of a recent change to paper's patching

**Comment by PhanaticD** [comment]
mikroskeem suggested on IRC just using the patched jar directly which works fine, so this actually isn't too big of a deal

**Comment by DenWav** [comment]
Paperclip issue.
