### ISSUE TITLE
This Looks Like Fatal World Corruption

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#90]
After the server starts, this happens:
http://i.imgur.com/2UQgazA.png

All the plugins and everything loads as normal, but server is unresponsive. Players cannot connect and commands do nothing.

Server was fine after restarting, resetting the End world.

git-Paper-502

**Comment by zachbr** [comment]
There is not a specific cause for us to work with here.

**Comment by hurrgurl** [comment]
Sorry for bringing it back again without much to go on. I had another issue with clean 1.9 end world (same problem as above, something about gateway & enderpearl makes the server unresponsive). I moved the end world to my test server and everything started fine. Could it be because player files are different (test server has no live player files) and existing entities don't connect with players or something? Sorry for being so random, just trying to walk in the dark.

Is there anything I can try to pin point this issue?
