### ISSUE TITLE
Possible bug with plugin signs

### ISSUE THREAD

**Issue by SeruhioX** [PaperMC/Paper#900]
I'd like to ask if the following has happened to anyone else out there.

I'm using the plugin ServerSigns to set signs which let you buy items in exchange of money, so let's say you click on a sign to buy 1 pickaxe and the server takes 200$ from you.

And the plugin MysqlEconomyBank to set signs which let you deposit and withdraw money from a bank. For example, you click on the withdraw sign and the server will take 1000$ from the bank and give it to you.

Everything worked fine until we updated the server spigot version to 1.12.

Since then sometimes when a player spams right click on one of these type of signs they are able to buy the item or withdraw the money 2 or even 3 times with one interaction of the sign. In other words if they spam the sign they might buy 2-3 pickaxes and only get charged once.

Server or player lag seems to make it more easy to happen but this is'nt fully confirmed.

I've already contacted the plugin developers but I'm not sure if this is a bug with their plugins or with the spigot build. If it's the latter then maybe it could occur with other similar plugins like signshop but as far as I know it has'nt happened on my server yet.

No errors show up in the logs.

Plugins
https://i.gyazo.com/c785986d66b7ce019b8b2f15a8c75989.png
https://i.gyazo.com/30e2e9e5ae85a12a196c05303de020a9.png

PaperSpigot #1228

**Comment by electronicboy** [comment]
The fact that the plugin passes them the item when they click the sign infers that the server software is passing the even to the plugin as intended, the fact that the transaction itself is the issue would sound as if your economy plugin is potentially suffering from a race condition which would need to be looked into by the developer.

**Comment by SeruhioX** [comment]
The thing is ServerSigns hasn't been modified for a long time  and it just recently started occuring and it happened too with the MysqlEconomyBank signs so it would be safe to assume the issue has to do with either spigot or essentials which is the economy plugin in this case. And you're saying spigot is passing events properly so that leaves us with the essentials plugin which seems to not sync up opposite events of "taking in" and "giving out" actions.

So youre saying it's the EssentialsX author the one that would have to check this issue?

**Comment by electronicboy** [comment]
the fact that its your eco system in general would state to me that it's whatever is providing your economy, no idea how your mysql eco plugin interacts. this honestly sounds like a concurrency issue in one of the plugins involved, especially if this is more likely to occur when your server itself is lagging.

If somebody is spam clicking signs, then it's on spigot to pass those interact events over, and for your plugins to deal with that as they wish, be that they just handle it as a click on the sign, or if they have some rate limit in order to prevent spamming.

**Comment by SeruhioX** [comment]
Have you changed something since the last updates that may have made these plugins behave like this and therefore the authors would have to update their plugins to accomodate to this? Or is it entirely on their side and no code in paper spigot has been modified that could affect this?

I want to figure this out mainly to know what they have to change on their side to make the signs work properly.

**Comment by electronicboy** [comment]
there is nothing that I am aware of that would cause such behavior, interact events are handled sync, it is impossible for a sync event to execute in such a way that multiple interactions would not be observed in a manner where one starts before the other has completed. (and would see the side-effects of the last method, e.g. the transaction itself having costed the player)

Not really sure there is anything here for us to look into, as this is more than likely on the side of a plugin dealing with concurrency improperly, thus allowing transactions to complete in a way that isn't observed properly across transactions.

**Comment by DrkMatr1984** [comment]
I remember PlayerInteractEntityEvent fires twice now on right or left click,  and you have to check in the event listener whether the click was with mainhand or off-hand before running the code.  My guess is server signs has yet to address this issue.  I think it was introduced in spigot 1.9. Just a heads up.
