### ISSUE TITLE
The console appears Chinese characters causing an exception

### ISSUE THREAD

**Issue by Johnraine** [PaperMC/Paper#901]
When my console loads Chinese messages, he gets stuck
Only the window is jammed and no feedback will be generated
The server is still available and the latest.log view is normal
How can I solve this problem?

**Comment by mikroskeem** [comment]
Screenshot of window being jammed?

**Comment by Johnraine** [comment]
Yes, as long as there is Chinese, it will clog up, but the server is normal

**Comment by electronicboy** [comment]
Please provide a screenshot or more information than "it doesn't work", as it stands you're not providing much for anybody to go off.

**Comment by Johnraine** [comment]
I've just tried and found a strange thing
My PC Win10 64 runtime is normal and can display Chinese characters
But my server, win2012 64, has this problem

**Comment by electronicboy** [comment]
in the meantime I would suggest trying to run the server with `--nojline`, windows 2012 is basically the most broken version of windows ever released in terms of support for software that wants to write text to a console.

**Comment by stephan-gh** [comment]
Cannot reproduce. Works fine for me on Windows Server 2012 (**not** R2) with system locale set to Chinese (Simplified).

![screenshot](https://user-images.githubusercontent.com/3035868/31242796-74fc0174-aa08-11e7-8be4-dc4f017baf20.png)

**Comment by Johnraine** [comment]
The current language used in non Unicode programs
I set up simplified Chinese, but it still doesn't work

**Comment by Johnraine** [comment]
Oddly, other console windows are normal except for Paper1.12.2

**Comment by stephan-gh** [comment]
Hard to tell without more information:

- A screenshot of the problem. I'm still not sure what exactly you mean with "the console gets stuck".
- The code page that is used in the console. Type `chcp` to display it.

**Comment by Johnraine** [comment]
Yes, I changed the code page to 936 and successfully fixed it

**Comment by stephan-gh** [comment]
Alright, in that case you can close the issue. The console implementation in older Windows versions has a lot of bugs, it's possible that it depends on a specific console code page to display certain characters, especially Chinese characters which also require a special font.
