### ISSUE TITLE
Push based hoppers break transfers from hoppers to chest minecarts

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#902]
When setting
>    hopper:
      push-based: true

in the paper.yml, hoppers do not transfer any items to chest minecarts. This does not happen in vanilla or when push-based is set to false.

>This server is running Paper version git-Paper-1230 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by zachbr** [comment]
Duplicate of https://github.com/PaperMC/Paper/issues/354

You basically shouldn't even bother using push-based hoppers at the moment. It has other issues like https://github.com/PaperMC/Paper/issues/763 that just break things.
