### ISSUE TITLE
The new anti-xray doesn't seem to work

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Paper#907]
Using latest paperclip, enabled the anti-xray and i'm using a 1.11 outdated client which manages to bypass it.

Don't really have much else to provide, just didn't replace any blocks and got easily bypassed. Maybe I set it up wrong, is there any documentation on the engine numbers?

**Comment by scrayos** [comment]
No, AFAIK there is no documentation yet. It would be nice to have it (along with some other settings, that were added as of recently) here: http://paper.readthedocs.io/en/paper-1.11/ (Even better: 1.12-Docs)

Regarding the engine modes, I guess it's similar to what orebfuscator did: Engine Mode 1 tries to hide Ores that are covered at all faces with Stone. That means ores, that are not fully covered can still be seen.

Engine Mode 2 "hides" all Ores by converting all Stone Blocks, that are fully covered into random Ores and Air. That makes Engine Mode 2 the more reliable method, most of the time.

**Comment by zachbr** [comment]
Config description
![paper.yml antixray config](https://i.imgur.com/63lwzze.png)

As for it not working with 1.11 clients, that may be a result of whatever protocol system you're using. We tested against 1.12 and that's what we support. We will investigate if there are any issues but cannot guarantee a fix if they're plugin related.

**Comment by Cobwebster** [comment]
Okay, I ran protocolsupport on the 1.12.2 gamemode. Idk if that'd do anything.

**Comment by Cobwebster** [comment]
Okay, after switching engine modes it works fine. This can be marked resolved, not sure how. Do you know if this had the issue what some anti xray stuff has where it makes files huge and puts a lot of strain on the server?

**Comment by zachbr** [comment]
If there's an issue with any engine mode we need to know about it.

**Comment by Cobwebster** [comment]
Well if enginemode 1 turns stuff to stone then its fine, it just wasn't doing well with dungeon chests but seemed to of worked for everything else. I guess double check the defaults on hiding chests with engine1
