### ISSUE TITLE
elytra durability

### ISSUE THREAD

**Issue by jefferyw08** [PaperMC/Paper#909]
this bug is incredibly annoying:

when using elytras, one durability point is lost every second - see this gif https://gyazo.com/4415d0450d6e1d612c68e1efdf137199

i have tried this on my paper test server that has 0 plugins installed and uses the latest build of paper (1234) - it still happened. (the server difficulty does not influence this whatsoever)

**Comment by electronicboy** [comment]
that's by design of vanilla?

**Comment by jefferyw08** [comment]
nope - try it for yourself in full vanilla

**Comment by electronicboy** [comment]
By using you mean 'gliding', right?

if yes, that's vanilla, refer to the vanilla wiki (and I just double checked against vanilla to ensure that the wiki is actually still updated), make sure that on vanilla you're not in creative or something that could change that

if no, please provide reproduction steps

**Comment by jefferyw08** [comment]
mfw
