### ISSUE TITLE
TileEntityChest server crash

### ISSUE THREAD

**Issue by enlyow** [PaperMC/Paper#910]
https://pastebin.com/szf16itV

paperspigot b1234

**Comment by electronicboy** [comment]
The problem with this is basically how Mojang handles chunk loading, I'm really not sure if there is too much we can do here without rewriting how loading of stuff such as TEs occur, or providing some manner to limit the loading of a chain...

**Comment by Black-Hole** [comment]
We could try to have chests not load chunks. If the other chunk is loaded later that other chest could make the double chest complete.

**Comment by aikar** [comment]
This bug looks related to ChunkIOProvider:

```java
        queuedChunk.loader.loadEntities(chunk, queuedChunk.compound.getCompound("Level"), queuedChunk.world);
        chunk.setLastSaved(queuedChunk.provider.world.getTime());
        queuedChunk.provider.chunks.put(ChunkCoordIntPair.a(queuedChunk.x, queuedChunk.z), chunk);
        chunk.addEntities();
```

It may be self referencing itself, because the .put call is after loadEntities, it could get in a loop maybe?

We might be able to just move the .put call up

**Comment by electronicboy** [comment]
potentially, never managed to reproduce this one myself, I always thought it was chests placed in a not so pleasant placement that ended up with a horrible recursive load but never managed to reproduce that as much as I tried. tbh, it would seem likely that what you've highlighted would have the potential to be the issue,

**Comment by Proximyst** [comment]
Given we don't have any reports of issues like this anymore, I'll assume it has been fixed somewhere at some point. Please open a new issue if this is still present.
