### ISSUE TITLE
FishHook.isInOpenWater() only calculated when a "fish" is coming towards the hook

### ISSUE THREAD

**Issue by PainOchoco** [PaperMC/Paper#9131]
### Expected behavior

Should be True only if the hook is in open water otherwise False.

### Observed/Actual behavior

It's true by default and only updates if it's in water and when a "fish" is coming towards the hook (water particles going towards the hook).

### Steps/models to reproduce

Either:
- Cast a fishing rod on the ground or in the air, FishHook.isInOpenWater() is true
- Make a 1x1x1 hole and fill it with water, cast the fishing rod in it, FishHook.isInOpenWater() is true but only become false when a particles are going towards it.

### Plugins
Plugins (8): Essentials, LuckPerms, PlaceholderAPI, PlugMan, ProtocolLib, Towny, TownyChatRemake, Vault

### Datapacks
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
There are no more data packs available

### Paper version

This server is running Paper version git-Paper-510 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bd35d60)
You are running the latest version

**Comment by Doc94** [comment]
hmm maybe the "solution" is copy the check in update to the CraftBukkit method for make in any case you call this the CB check... or only check the NMS `calculateOpenWater` this method handle the block position for check if is in water...
