### ISSUE TITLE
Add SpawnerPreSpawnEvent

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#917]
id like to request this in main paper: https://github.com/TacoSpigot/TacoSpigot/commit/49c277eb5d0ec3775e5afd904456ae3a196ec7dd

actually maybe it should be added for all mob spawns? I think some plugins could greatly reduce ram and resource useage if the mob wasnt loaded first then removed

**Comment by LogGits** [comment]
If this is added could an isNatural boolean be implemented to determine if a mob has spawned in the wild or from a spawner/egg.

**Comment by aikar** [comment]
Per the event documentation, only firing for NATURAL and SPAWNER, since this is primarily performance oriented and these are the only 2 cases that it will matter for.

**Comment by aikar** [comment]
You may also be interested in https://github.com/PaperMC/Paper/commit/6068eb129f880447c0f6d240a70024fa2b219b26
