### ISSUE TITLE
Server is crash

### ISSUE THREAD

**Issue by Etrail** [PaperMC/Paper#924]
https://pastebin.com/Hp2k1XBg

I have eror
Server is crash

**Comment by zachbr** [comment]
Someone sent a specially crafted book to your server in order to lag it out.

This is fixed in modern versions of Paper, we do not support 1.8.8.

**Comment by Etrail** [comment]
in which version is it corrected?
what version do I put on the server

**Comment by electronicboy** [comment]
you put the latest version on your server.
