### ISSUE TITLE
Build support provision [PowerShell]

### ISSUE THREAD

**Issue by Announcement** [PaperMC/Paper#927]
I wrote some PowerShell scripts to duplicate the existing bash scripts, wondering if anyone was interested so I know whether or not I should bother supplying them with a commit/pull request.

**Comment by zachbr** [comment]
We would probably not accept them if PR'd.

The bash scripts we currently use are going to be replaced relatively soon by a gradle based system, so replacing them now doesn't make sense.

Adding a second set of scripts is also probably not a great idea for us from a maintainability perspective.

**Comment by Announcement** [comment]
thanks zbob750, good thing i asked first :)
