### ISSUE TITLE
 build 1250 issue

### ISSUE THREAD

**Issue by khlfkk** [PaperMC/Paper#933]
when update to build 1250, it cause the Skirpt error.
Thanks!
https://paste.md-5.net/taxuguqowe.avrasm

seem that java.lang.NoSuchFieldError: SHEEP_EAT removed by spigot Dev

**Comment by Legoman99573** [comment]
Update skript and let us know if it still occurs. Latest is 2.2-dev32

**Comment by MiniDigger** [comment]
spigot removed the field, we just pinged md in irc about it and he added it back, wait till paper updates. till then you can downgrade paper temporarily.

**Comment by zachbr** [comment]
Should be fixed in 1251+ when it gets done building.
Thanks.
