### ISSUE TITLE
QUESTION: All plugins are working on Paper Spigot ?

### ISSUE THREAD

**Issue by TheIntelloBox** [PaperMC/Paper#934]
Hello !

I'm an user of Spigot.
I wanted to know if all plugins are working on Paper Spigot ?

Thanks ! :D

**Comment by MiniDigger** [comment]
99% will work, just test it.

**Comment by 0-x-2-2** [comment]
more like 99.9%

**Comment by BillyGalbreath** [comment]
all craftbukkit plugins work on spigot, but not all spigot plugins work on craftbukkit. all spigot plugins work on paper, but not all paper plugins work on spigot.

Each fork out adds its own API on top that can be used in excess to the previous, but cannot be used in anything less.

**Comment by mikroskeem** [comment]
There is no need to create an issue for such questions; next time hop into IRC and ask from there instead.

**Comment by electronicboy** [comment]
closing as your question appears to be answered, if you have any questions, please use the IRC or discord, issue trackers spam peoples emails needlessly.
