### ISSUE TITLE
world.refreshChunk() causes lighting engine error sometimes

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#9375]
### Expected behavior

No error

### Observed/Actual behavior

Sometimes this error is thrown, see code below:

[08:41:59 ERROR]: [ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool] Exception thrown from thread 'Tuinity Chunk System Worker #0' in queue 'ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedPoolExecutorImpl@1716be4b'
java.lang.IndexOutOfBoundsException: writerIndex(4346) + minWritableBytes(8) exceeds maxCapacity(4346): UnpooledHeapByteBuf(ridx: 0, widx: 4346, cap: 4346/4346)
        at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:294) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.buffer.AbstractByteBuf.writeLong(AbstractByteBuf.java:1039) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
        at net.minecraft.network.FriendlyByteBuf.writeLong(FriendlyByteBuf.java:1437) ~[?:?]
        at net.minecraft.network.FriendlyByteBuf.writeLongArray(FriendlyByteBuf.java:436) ~[?:?]
        at net.minecraft.world.level.chunk.PalettedContainer$Data.write(PalettedContainer.java:426) ~[?:?]
        at net.minecraft.world.level.chunk.PalettedContainer.write(PalettedContainer.java:245) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunkSection.write(LevelChunkSection.java:288) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.extractChunkData(ClientboundLevelChunkPacketData.java:122) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:55) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:36) ~[paper-1.20.jar:git-Paper-17]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.lambda$refreshChunk$8(CraftWorld.java:524) ~[paper-1.20.jar:git-Paper-17]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.refreshChunk(CraftWorld.java:523) ~[paper-1.20.jar:git-Paper-17]

### Steps/models to reproduce

```
//The justification for not using .setType() is for both client and server performance reasons, as I am modifying millions of //blocks at once, .setType() isn't very good at batching block change packets from my experience. 
//Below is the complete code for full context. This is all done on the main thread.

// Create a set of chunks that are affected by placing blocks.
Set<Pair<Integer, Integer>> affectedChunks = placeBlocks(room, start, box, offset, rotation);
// Re-calculate the light for these chunks and update them to the clients.
relightAndResendChunks(affectedChunks, start.getWorld());

...

// This function is used to place blocks in a specific room, at a specific location,
// inside a box with an offset and a rotation.
private static Set<Pair<Integer, Integer>> placeBlocks(Room room, Location start, BlockVector box, BlockVector offset, Rotation rotation) {
    Set<Pair<Integer, Integer>> affectedChunks = new HashSet<>();
    int index = 0;
    // The code goes through every block inside the box.
    for (int y = 0; y < box.getBlockY(); ++y) {
        for (int x = 0; x < box.getBlockX(); ++x) {
            for (int z = 0; z < box.getBlockZ(); ++z) {
                // It stops when it has placed all blocks for the room.
                if (index > room.getBlocks().size() - 1) {
                    break;
                } else {
                    BlockData data = room.getBlocks().get(index);
                    // If the block is not a structure void or a structure block, it's placed.
                    if (data.getMaterial() != Material.STRUCTURE_VOID && data.getMaterial() != Material.STRUCTURE_BLOCK) {
                        // The block is placed at an absolute position, computed from the box's
                        // position, the block's relative position, and the rotation.
                        double absX = x + offset.getX();
                        double absY = y + offset.getY();
                        double absZ = z + offset.getZ();
                        Location place = start.clone().add(applyRotation(new BlockVector(absX, absY, absZ), rotation));
                        // The chunk in which the block is placed is affected.
                        Pair<Integer, Integer> chunkAffected = Pair.of(place.getBlockX() >> 4, place.getBlockZ() >> 4);
                        data = rotate(data, rotation); // This rotates a block's data based on provided rotation
                        setTypeNative(place, chunkAffected, data);
                        affectedChunks.add(chunkAffected);
                    }
                    index++;
                }
            }
        }
    }
    // Also add all chunks surrounding the chunks that have been affected directly. Or else lighting looks buggy in some cases
    Set<Pair<Integer, Integer>> toAdd = new HashSet<>();
    for (Pair<Integer, Integer> affectedChunk : affectedChunks) {
        for (int x2 = -1; x2 <= 1; ++x2) {
            for (int z2 = -1; z2 <= 1; ++z2) {
                toAdd.add(Pair.of(affectedChunk.fst + x2, affectedChunk.snd + z2));
            }
        }
    }
    affectedChunks.addAll(toAdd);
    return affectedChunks;
}

...

// This function is used to set the type of a block at a location in a native way,
// i.e. without causing block updates or lighting updates.
public static void setTypeNative(Location location, Pair<Integer, Integer> chunkLoc, BlockData data) {
    ServerLevel level = ((CraftWorld) location.getWorld()).getHandle();
    ServerChunkCache cache = level.getChunkSource();
    LevelChunk levelChunk = cache.getChunkAtIfLoadedMainThread(chunkLoc.fst, chunkLoc.snd);
    BlockPos pos = new net.minecraft.core.BlockPos(location.getBlockX(), location.getBlockY(), location.getBlockZ());
    levelChunk.setBlockState(pos, ((CraftBlockData) data).getState(), false, false);
}

...

// This function is used to recalculate the light for a set of chunks and send
// the updated chunks to all clients.
public static void relightAndResendChunks(Set<Pair<Integer, Integer>> chunks, World world) {
    ServerLevel level = ((CraftWorld) world).getHandle();
    java.util.LinkedHashSet<ChunkPos> chunkPos = new LinkedHashSet<>();
    for (Pair<Integer, Integer> chunk : chunks) {
        chunkPos.add(new ChunkPos(chunk.fst, chunk.snd));
    }
    ThreadedLevelLightEngine lightengine = level.getChunkSource().getLightEngine();
    lightengine.relight(chunkPos, chunkPos1 -> world.refreshChunk(chunkPos1.x, chunkPos1.z), num -> { // ERROR OCCURS HERE SOMETIMES, AT WORLD.REFRESHCHUNK()
    });
}
```
### Plugin and Datapack List

Custom plugin

### Paper version

This server is running Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)
You are running the latest version
Previous version: git-Paper-"fa8fa1c" (MC: 1.19.4)

### Other

Some advice to avoid these errors would be helpful if you (understandably) don't think it warrants a fix since I am using unsupported API.

**Comment by electronicboy** [comment]
Please stop submitting issues from unsupported versions of paper
