### ISSUE TITLE
Anvil Item Duplication Glitch?

### ISSUE THREAD

**Issue by AaronStrange3** [PaperMC/Paper#939]
###Description of issue:
Whenever a player uses an anvil to add an enchantment to a piece of armor, repair something, use the anvil for ANYTHING, they get back whatever item they used.

### Plugin list:
![image](https://user-images.githubusercontent.com/29562011/32987452-6f4488f8-ccba-11e7-8c84-28121e57b0c1.png)

### bukkit.yml, spigot.yml, paper.yml, server.properties

bukkit.yml:
https://pastebin.com/krkTYnkZ

spigot.yml:
https://pastebin.com/z9Pxvzqu

server.properties:
https://pastebin.com/7FEZrx2d

### Other helpful links

What shows up when I use an anvil:
https://pastebin.com/ijGD05zJ

### Paper build number:
![image](https://user-images.githubusercontent.com/29562011/32987554-16224a46-ccbd-11e7-8f64-090a0f2bdb78.png)

### What behaviour is expected:

I expected to combine the armor, and enchantment, using the anvil.  Getting back only the item I created.

### What behaviour is observed:

It seems that when I try to combine them, my inventory returns to what it was before I clicked the anvil, the only difference being I kept what I made.  I also noticed that using different methods of clicking made the items re-appear in different ways.  If I shift click the completed item into into my inventory, I not only get that item, but I get the 2 items it took to make it (once I close out of the anvil).  If you simply click, and click again, to move it to a different location, you get back the base to what you repaired/enchanted.  IE: When I enchanted armor with prot. 1, I got back plain armor, in addition to the enchanted armor.

### Steps/models to reproduce:

![anvil glitch](https://user-images.githubusercontent.com/29562011/32987545-f3c07482-ccbc-11e7-8cf4-44252dfeb628.gif)

**Comment by zachbr** [comment]
Cannot reproduce that here, you should probably start sorting through plugins.

**Comment by electronicboy** [comment]
```
Caused by: java.lang.NoSuchFieldError: c
    at net.jordan.vehicles.nms.v1_12_R1.CustomContainerAnvil.b(CustomContainerAnvil.java:314) ~[?:?]
    at net.jordan.vehicles.nms.v1_12_R1.CustomContainerAnvil.shiftClick(CustomContainerAnvil.java:308) ~[?:?]
    at net.minecraft.server.v1_12_R1.Container.a(Container.java:251) ~[paper_spigot_1.12.jar:git-Paper-1261]
```

I'd say it's pretty clear that that plugin is is breaking anvils in the exact manner that you're seeing, it's throwing an exception right in the middle of processing the output, right before the itemstacks in the input are decremented.

**Comment by AaronStrange3** [comment]
Thank you!  I will not go post this problem to the appropriate people.  I found the problem plugin rather quickly.  But I have no idea how craftmoto could mess with anvils like that.
