### ISSUE TITLE
sendSignChange no longer work with 1.20.1 Server

### ISSUE THREAD

**Issue by rudde0** [PaperMC/Paper#9398]
### Expected behavior

Player#sendSignChange works when:
- 1.19.4 server and ViaVersion with 1.20.1 client
- 1.20.1 server and ViaBackwards with 1.19.4 client

Doesn't work when:
- 1.20.1 server and 1.20.1 client

### Observed/Actual behavior

Player#sendSignChange was working versions between 1.15 (maybe older) and 1.19.4.

### Steps/models to reproduce

- Open 1.20.1 client
- Open sign to player
- When player open signs, send some updated lines using Player#sendSignChange

It will work if your server and client isn't 1.20.1 at the same time.

### Plugin and Datapack List

Doesn't related with plugins

### Paper version

git-Paper-45 (MC: 1.20.1)

**Comment by Machine-Maker** [comment]
I'm not able to reproduce what you are talking about, or am doing it wrong. I setup 2 servers, one with 1.19.4 and one 1.20.1. I loaded the same plugin onto both which did this:
```java
@EventHandler
public void onChat(ChatEvent event) {
    final Block block = event.getPlayer().getTargetBlockExact(5);
    if (block != null && block.getState() instanceof Sign sign) {
        event.getPlayer().openSign(sign, Side.FRONT);

        this.getServer().getScheduler().runTaskLater(this, () -> {
            event.getPlayer().sendSignChange(block.getLocation(), List.of(text("Hey there"), empty(), empty(), empty()));
        }, 40L);
    }
}
```

In all cases, typing in chat while looking at a sign opened the sign, and then put text on the sign in the world. In none of the cases did it input text into the sign typing screen, only onto the sign in the world. If I pressed ESC or "Done" without typing anything it cleared the sign.

**Comment by rudde0** [comment]
Please use client side sign block. Client can't read the what's writing on the fake block. You can use this:
```
Material material = Material.OAK_WALL_SIGN;
event.getPlayer().sendBlockChange(block.getLocation(), material.createBlockData());
```

**Comment by rudde0** [comment]
Sorry I just realised it's related with packet changes. Thank you for helping.
