### ISSUE TITLE
TileEntityBeacon is missing a mapping

### ISSUE THREAD

**Issue by MCReverse** [PaperMC/Paper#940]
# Crash, Stacktrace

### Link/paste of stack trace

    
![image](https://user-images.githubusercontent.com/22728556/32989309-10e614dc-cd57-11e7-8fa7-1711fe68d138.png)

### Plugin list:
![image](https://user-images.githubusercontent.com/22728556/32989323-43d19074-cd57-11e7-93c9-64d2a0eaac53.png)

### Actions to reproduce (if known):
When I click the any item in ASkyblock's controlpanel(inventory gui, Can open with /is settings) and bind the "inventory_click" event of CommandHelper, shown above error.

CommandHelper is scripting plugin.

Not showed any error when change the PaperSpigot to Spigot and reproduce this.

### Paper build number:
![image](https://user-images.githubusercontent.com/22728556/32989347-ab2e7d4a-cd57-11e7-9722-38e80b3f2215.png)
This server is running Paper version git-Paper-1258 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Unable to see how this would potentially happen unless you have something that is messing around with the server in an unsupported way. The mapping is registered perfectly fine inside the nms TileEntity class.

if you're able to persistently replicate this, maybe try running the patched jar file from the cache folder as opposed to directly running paperclip, could be some plugin trying to perform some voodoo.

**Comment by aikar** [comment]
Try removing plugins to find when it stops. This is clearly plugins accessing NMS as the source, as if this was the case without plugins, the server wouldn't even work correctly.

**Comment by MCReverse** [comment]
Thanks. It was a plugin problem
