### ISSUE TITLE
Add the ability to disable enderdragon respawning (legacy check)

### ISSUE THREAD

**Issue by krusic22** [PaperMC/Paper#941]
Some setups (like my hub that doesn't allow any mobs to spawn) always keep respawning the dragon even after he is killed. 

Examples I tested (all do the same thing):
Import a world where the dragon was killed.
Allowed spawning of mobs and killed the dragon (worked till restart then just respawns).
If you disable mob spawning after killing him and restarting there will be no dragon just the Dragon Health bar... And you cant remove it since there is no dragon to kill.

Editing the NBT data of the world also doesn't help (in world and world_the_end)...
![image](https://user-images.githubusercontent.com/8352435/33223882-59dffeee-d164-11e7-8caa-b3ebd679602e.png)

This is why I will now ask for a option to disable this check:
Can you please add a option in paper.yml to disable EnderDragon legacy checking or even disable him all together?
Thanks.

**Comment by Black-Hole** [comment]
You could use a plugin to prevent those spawn, like WorldGuard.

**Comment by krusic22** [comment]
It described what happens. The dragon does not spawn in that case but the Health Bar just stays there forever.

**Comment by Brokkonaut** [comment]
Some workaround you can use for this bug: place an end portal block somewhere in the world (near 0,0) and restart the server. If there is at least one end portal block, the server thinks the dragon has already been killed and does not try to start the dragon fight

**Comment by WizzleBear** [comment]
Place an ender portal somewhere and the check always comes true.

**Comment by krusic22** [comment]
Thanks for the bump. But @Brokkonaut already said that.

**Comment by WizzleBear** [comment]
Oh, didn't see that! This should be closed, then.

**Comment by zachbr** [comment]
Added w/ 8f1e26286f946ffe9a3847f50ad122a594d70b55
Builds 1479+
