### ISSUE TITLE
Crash on server initialisation [Solved]

### ISSUE THREAD

**Issue by MrHiwj** [PaperMC/Paper#944]
I Have a completely fresh build of paper spigot, only just cloned, 0 plugins and the server hasn't been able to boot once. -> not sure its a me thing or a paperspigot issue

[crash-2017-11-28_21.15.38-server.txt](https://github.com/PaperMC/Paper/files/1511648/crash-2017-11-28_21.15.38-server.txt)

**Comment by electronicboy** [comment]
Pretty sure that this is one is due to a discrepancy in the JDK when you build with java 9 and run the software in java 8.

**Comment by MrHiwj** [comment]
Okay I’ll try rerunning with java 8 as my MC doesn’t work with java 9 yet... is that also a global problem
