### ISSUE TITLE
Outdated server! I'm still on 1.12.2 problem.

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#945]
Paper Version: 
> This server is running Paper version git-Paper-1268 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Minecraft Version: 1.12.2

When player join a server, it shows "Outdated server! I'm still on 1.12.2".

Please see this:
![1](https://user-images.githubusercontent.com/25248285/33494177-5caaf202-d6fd-11e7-8446-c47426af1bd0.png)
This is really funny. Please checking this. Thank you very much.

**Comment by electronicboy** [comment]
make sure that you're actually running 1.12.2 and not a snapshot version or something, only case you'd see that is something playing with the protocol version (or actually having the wrong client version). Beyond that, general case of replicate without plugins

**Comment by ghost** [comment]
@electronicboy "This server is running Paper version git-Paper-1268 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)".

I'm very sure.

**Comment by ghost** [comment]
I think it's a problem with some plugins, and I'm looking for it.

**Comment by ghost** [comment]
ProtocolSupport.
Yes, this plugin is very interesting. I will deleted it.
