### ISSUE TITLE
SpawnEntityEvent cancellation stacks items in inventory

### ISSUE THREAD

**Issue by baticag** [PaperMC/Paper#946]
It is shown in the video how you can stack items when SpawnEntityEvent is cancelled (flag item-drop: deny is marked in WorldGuard region).
https://www.youtube.com/watch?v=I4icOuizrks

There is a discussion about if that is a WorldGuard or a Spigot bug here:
http://dev.enginehub.org/youtrack/issue/WORLDGUARD-3867

Can you please check this out?

This server is running Paper version git-Paper-1248 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT).
This happens with WorldGuard 6.2.1;84bc322, because that plugin is doing the cancellation of the SpawnEntityEvent.

**Comment by aikar** [comment]
Why is WorldGuard using that event instead of PlayerDropItemEvent? 

That is the wrong event for WG to be using.

Though I Would expect the item to just be lost if that event is cancelled....

**Comment by baticag** [comment]
Maybe because they deny not only player drops, but all the drops.

Is this Spigot's problem and if yes, how can we solve it?

**Comment by aikar** [comment]
Confirmed I see the issue. This has been a bug in CraftBukkit for many years!

Please report this to Spigot, but well see about fixing it in Paper too.

**Comment by baticag** [comment]
Spigot dumped my report... https://i.imgur.com/CLuq17M.png
And I can't switch from PaperSpigot to Spigot just to tell them that I am using Spigot...

**Comment by Phoenix616** [comment]
@baticag if you want to report bugs to Spigot test with either Spigot or CraftBukkit.

**Comment by electronicboy** [comment]
Spigot has fixed a part of this upstream, they've shimmed the issue by adding a check to prevent items being placed in the inventory being blindly added and going over the max stack count, however they've not actually handled placing the item back properly.

Working on a patch to actually handle canceling of this event properly, however, that will have to wait until I have the time to fix a few issues with it, for now just going to merge upstream in.

**Comment by aikar** [comment]
Going to close this as @electronicboy's change is more of a UX improvement.

The "Problem" reported here is fixed.
