### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Leymooo** [PaperMC/Paper#948]
PaperSpigot version git-Paper-1264
Crash - https://pastebin.com/v4Ecqv5M also i had this crash on paper 1244 and 1255
Link to timings with plugins and config settings - https://timings.aikar.co/?id=2753afe587604e2e9871a0e641c43cd3

Other crashes - 151.80.108.152/~slava/mine/crash-reports

**Comment by electronicboy** [comment]
I can say without a doubt that this is going to be caused by plugins. if you can reproduce the crash without plugins, feel free to open a new ticket.
