### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Gemax** [PaperMC/Paper#949]
Crash report

> 04.12 21:42:11 [Server] ERROR The server has stopped responding!
> 04.12 21:42:11 [Server] ERROR Please report this to PaperSpigot directly!
> 04.12 21:42:11 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports
> 04.12 21:42:11 [Server] ERROR PaperSpigot version: git-PaperSpigot-"4c7641d" (MC: 1.8.8)
> 04.12 21:42:11 [Server] ERROR ------------------------------
> 04.12 21:42:11 [Server] ERROR Server thread dump (Look for plugins here before reporting to PaperSpigot!):
> 04.12 21:42:11 [Server] ERROR ------------------------------
> 04.12 21:42:11 [Server] ERROR Current Thread: Server thread
> 04.12 21:42:11 [Server] ERROR PID: 16 | Suspended: false | Native: false | State: RUNNABLE
> 04.12 21:42:11 [Server] ERROR Stack:
> 04.12 21:42:11 [Server] ERROR java.util.regex.Pattern$5.isSatisfiedBy(Pattern.java:5251)
> 04.12 21:42:11 [Server] ERROR java.util.regex.Pattern$5.isSatisfiedBy(Pattern.java:5251)
> 04.12 21:42:11 [Server] ERROR java.util.regex.Pattern$5.isSatisfiedBy(Pattern.java:5251)
> 04.12 21:42:11 [Server] ERROR java.util.regex.Pattern$CharProperty.match(Pattern.java:3776)
> 04.12 21:42:11 [Server] ERROR java.util.regex.Pattern$Curly.match(Pattern.java:4227)
> 04.12 21:42:11 [Server] ERROR java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
> 04.12 21:42:11 [Server] ERROR java.util.regex.Pattern$Branch.match(Pattern.java:4602)
> 04.12 21:42:11 [Server] ERROR java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
> 04.12 21:42:11 [Server] ERROR java.util.regex.Pattern$Branch.match(Pattern.java:4604)
> 04.12 21:42:11 [Server] ERROR java.util.regex.Pattern$Start.match(Pattern.java:3461)
> 04.12 21:42:11 [Server] ERROR java.util.regex.Matcher.search(Matcher.java:1248)
> 04.12 21:42:11 [Server] ERROR java.util.regex.Matcher.find(Matcher.java:637)
> 04.12 21:42:11 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.util.CraftChatMessage$StringMessage.<init>(CraftChatMessage.java:52)
> 04.12 21:42:11 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.util.CraftChatMessage$StringMessage.<init>(CraftChatMessage.java:42)
> 04.12 21:42:11 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.util.CraftChatMessage.fromString(CraftChatMessage.java:136)
> 04.12 21:42:11 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaBook.addPage(CraftMetaBook.java:234)
> 04.12 21:42:11 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaBookSigned.<init>(CraftMetaBookSigned.java:49)
> 04.12 21:42:11 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:329)
> 04.12 21:42:11 [Server] ERROR net.minecraft.server.v1_8_R3.PacketDataSerializer.i(PacketDataSerializer.java:208)

**Comment by electronicboy** [comment]
We don't support 1.8 in any capacity, THis issue also has several dozen other reports on this issue tracker and all over the internet if you actually did some research.
