### ISSUE TITLE
Vertical hopper transferring two items at once

### ISSUE THREAD

**Issue by EvilOlaf** [PaperMC/Paper#950]
# Incompatibility (Bug)

### What behaviour is expected:
Vanilla hopper functionality
### What behaviour is observed:
Hopper always transferring two items at once when stacked vertically
### Steps/models to reproduce:
Stack three or more hoppers vertically
Put a random item stack into the top hopper (tested with wool and cobblestone)
Check hopper to notice two items are transferred at once.

Tested with default spigot.yml and paper.yml
### Plugin list:
No plugins whatsoever, completely stock

### Paper build number:
git-Paper-1269 (MC: 1.12.2)

**Comment by zachbr** [comment]
This is vanilla behavior.
Tested against the vanilla minecraft server version 1.12 using variously stacked numbers of hoppers.

**Comment by EvilOlaf** [comment]
Well, then sorry for bothering. Never thought that it would be vanilla behavior that vertically stacked hoppers transfer two items at once. Weird stuff.

**Comment by zachbr** [comment]
It is weird, I thought it was a bug when I initially glanced through.
Mojang may very well consider this a bug, I certainly would, but we can't fix it without breaking hopper behavior.
Thanks for the report though 👍

**Comment by SpiderRobotMan** [comment]
From testing this is due to the top hopper pushing items into the one below, while at the same time the bottom hopper pulls items out of the hopper above it. You can disable one of them using redstone to notice this. The official bug for this issue has been marked **Works As Intended**. https://bugs.mojang.com/browse/MC-8361

**Comment by EvilOlaf** [comment]
Alright, thank you for the follow up. Still odd ¯\_(ツ)_/¯
