### ISSUE TITLE
Anvil inventories, please fix

### ISSUE THREAD

**Issue by PatrickGerth** [PaperMC/Paper#951]
Hey there,
this is something between a feature request and a bug report.

### Description of issue:
The virtual anvil inventories provided by spigot/paperspigot are non functional.
You can open an inventory, yes, but you can't place items in it or interact with it correctly without using nms, which kinda devalues this part of the api.

Can you fix this? 
As it seems, right now people are using apis provided by third parties like
https://github.com/WesJD/AnvilGUI
but since I'm not a big fan of these since you never know when they will stop supporting them, I would strongly wish of you guys to fix the api.

### Paper build number: git-Paper-1256 (MC: 1.12.2)

# Incompatibility (Bug)

### What behaviour is expected:
- I want to place specific items in anvil-inventory-slots, creating a menulike experience.
### What behaviour is observed:
- no items are placed whatsoever
- clickevents throw null
### Steps/models to reproduce:
- try working with the original api here

### Paper build number:
git-Paper-1256 (MC: 1.12.2)

# Suggestion

Thanks a lot for all your hard work. Perhaps you can make the api even better with this

**Comment by aikar** [comment]
Can you pastebin some code that isn't working?

**Comment by PatrickGerth** [comment]
Sure can do, even the very basics dont work:
https://pastebin.com/MxW1Cqxx
If I try to open this inventory to a player, the player just gets an empty anvil inventory.

**Comment by electronicboy** [comment]
The problem here is that inventories created by Bukkit really have no attachment to an NMS implementation of say, an anvil; Whenever you create an inventory using that API, it just returns a CraftInventoryCustom.

It is doable to make this work and return real implementations, just requires a fair amount of work to allow the inventories to actually work without exploding because the TE they're attached too isn't really in the world. Ontop of that, it's also a bit of a behavior change on the API, which i'm not really sure is ideal this far downstream for this kinda change

**Comment by PatrickGerth** [comment]
You may not be wrong with your arguments but as far as I can see, this is just faulty code in the api. 
Either cut it or make it work, don't you think so too?
If you have better solutions, please share them with us.

**Comment by electronicboy** [comment]
This isn't "faulty code", this is working as craftbukkit currently intends.

the major problems with "fixing" it and making it work as would be ideal, is that there are a lot of changes that would be required;

* This is a complete behavior change of the API, in some cases, e.g. chests, this is mostly a none issue, for stuff like anvils, this is a drastic change in functionality

* Inventories generally rely on their actual block counterpart, e.g. ContainerAnvil makes various interactions with the world to cause damage to the anvil

it's more than likely possible to do, it's just the fact that it's a complete behavior change, would require a reasonable amount of work to pull off and more than likely either require pretty invasive changes to pull off

**Comment by 0-x-2-2** [comment]
Just use nms tbh its not hard to update

**Comment by PatrickGerth** [comment]
The question is, if it isn't worth the work. 
I'm not familiar with the amount of manpower paper could spare for something like this.
Sure I could use the nms but using it always feels kinda hacky.
In addition, menues that would come out of this would be an integral part of my plugin and it always itches to have integral parts running on nms.

**Comment by 0-x-2-2** [comment]
yeah but if you want support for normal spigot or a older version you will need to use nms anyways because the changes wont be there.

**Comment by aikar** [comment]
I'm curious as to why anvils for menus? Are you trying to just let the user type?

**Comment by PatrickGerth** [comment]
Hey there,
yes indeed. I'm trying to take all the plugininteraction out of the chatbox so the user will not have to remember half a dozen commands and just interact with one cohesive menusystem.

**Comment by 0-x-2-2** [comment]
You can also use signs btw but then again this is all done with packets.

**Comment by PatrickGerth** [comment]
and it's nowhere near cohesive

**Comment by aikar** [comment]
Going to close as this isn't something Paper should be trying to resolve, as it requires upstream to make decisions on how this change should occur.
