### ISSUE TITLE
Crash error related to user authentication

### ISSUE THREAD

**Issue by danielgarciagarcia** [PaperMC/Paper#952]
# Crash, Stacktrace

### Link/paste of stack trace 
https://pastebin.com/1zTzLhu6

### Actions to reproduce (if known): 
Unknown

### Paper build number: 
git-Paper-1262

**Comment by electronicboy** [comment]
Your server took too long to tick, and this has nothing to do with user auth. I'd suggest keeping your eyes on timings if you're having further issues.
