### ISSUE TITLE
Lighting Queue Freeze On Chunk Load

### ISSUE THREAD

**Issue by hafarooki** [PaperMC/Paper#953]
In worlds that have some questionable lighting, certain chunks freeze the server when they load. I never had this issue before, but I switched back to plain old spigot for a while, and then I switched back to paper, and now I have issues only when I use paper.

Error: http://prntscr.com/hovvo6

I get this error EVEN IF QUEUE LIGHTING IS OFF. No issue on spigot, just glorious broken lighting. Random light updates are off (sadly).

**Comment by electronicboy** [comment]
In the latest build (https://ci.destroystokyo.com/job/PaperSpigot/1275/), I have brought back spigots broken lighting logic, it was never intended that we'd leave this change in without the async chunk lighting for this long, however, shamefully I haven't had the time to sit down and work out the issues around craftbukkits chunk ticking logic which is causing breakage.

**Comment by hafarooki** [comment]
Thank you!
