### ISSUE TITLE
String Duplication Bug

### ISSUE THREAD

**Issue by underbari7zunderbar** [PaperMC/Paper#9542]
### Expected behavior

paper blocks string duper

### Observed/Actual behavior

string duper works 
![2023-07-28_21 02 09](https://github.com/PaperMC/Paper/assets/129371128/0caf159c-6d02-48ec-a7dc-25669aa61e73)

### Steps/models to reproduce

1.create string duper like this schematic
https://www.mediafire.com/file/efpnyauyhwl3yz1/Unnamed111.litematic/file

2.click on the string with the shears

3.pull the lever

### Plugin and Datapack List

None

### Paper version

\> version
[21:06:41 INFO]: Checking version, please wait...
[21:06:43 INFO]: This server is running Paper version git-Paper-98 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a40e48f)
You are running the latest version

**Comment by Ankit-rajan** [comment]
> ### Expected behavior
> paper blocks string duper
> 
> ### Observed/Actual behavior
> string duper works ![2023-07-28_21 02 09](https://user-images.githubusercontent.com/129371128/256816218-0caf159c-6d02-48ec-a7dc-25669aa61e73.png)
> 
> ### Steps/models to reproduce
> 1.create string duper like this schematic https://www.mediafire.com/file/efpnyauyhwl3yz1/Unnamed111.litematic/file
> 
> 2.click on the string with the shears
> 
> 3.pull the lever
> 
> ### Plugin and Datapack List
> None
> 
> ### Paper version
> > version [21:06:41 INFO]: Checking version, please wait... [21:06:43 INFO]: This server is running Paper version git-Paper-98 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: [a40e48f](https://github.com/PaperMC/Paper/commit/a40e48f3fd95138238d2c6422465d579b7a21e6b)) You are running the latest version
> 
> ### Other
> _No response_

Bro  i have tried all methods but it doesn't work in aternos server please give me some tips and tricks how i can run it

**Comment by Ankit-rajan** [comment]
> 

can i get any reply

**Comment by lynxplay** [comment]
Are you currently trying to ask *how to perform string duplication* on a github issue related to fixing string duplication ?

**Comment by Ankit-rajan** [comment]
> Are you currently trying to ask _how to perform string duplication_ on a github issue related to fixing string duplication ?

shit man sorry 🤯 
i know how to perform  but it doesn't work in paper mc server so that's why I'm here

**Comment by underbari7zunderbar** [comment]
> > ### Expected behavior
> > paper blocks string duper
> > ### Observed/Actual behavior
> > string duper works ![2023-07-28_21 02 09](https://user-images.githubusercontent.com/129371128/256816218-0caf159c-6d02-48ec-a7dc-25669aa61e73.png)
> > ### Steps/models to reproduce
> > 1.create string duper like this schematic https://www.mediafire.com/file/efpnyauyhwl3yz1/Unnamed111.litematic/file
> > 2.click on the string with the shears
> > 3.pull the lever
> > ### Plugin and Datapack List
> > None
> > ### Paper version
> > > version [21:06:41 INFO]: Checking version, please wait... [21:06:43 INFO]: This server is running Paper version git-Paper-98 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: [a40e48f](https://github.com/PaperMC/Paper/commit/a40e48f3fd95138238d2c6422465d579b7a21e6b)) You are running the latest version
> > 
> > 
> > ### Other
> > _No response_
> 
> Bro i have tried all methods but it doesn't work in aternos server please give me some tips and tricks how i can run it

did you click on the string?

**Comment by welove69** [comment]
> > 您目前正在尝试询问如何在与修复字符串重复相关的 github 问题上_执行字符串复制_吗？
> 
> 狗屎人对不起🤯，我知道该怎么做，但它在纸MC服务器中不起作用，所以这就是我在这里的原因


https://github.com/PaperMC/Paper/assets/135555687/a2b7fbec-6c51-4c39-8f17-1cc23909aa73

**Comment by Owen1212055** [comment]
Resolved in https://github.com/PaperMC/Paper/pull/9436
