### ISSUE TITLE
UUID support name change- paperspigot 1.8.8

### ISSUE THREAD

**Issue by wkw030210** [PaperMC/Paper#956]
My players are experiencing a problem in UUIDs, as when they change their name, they lose everything. I have a fix for this as I go into the usercache.json and manually replace their ids, but this is still annoying.

**Comment by electronicboy** [comment]
We don't support 1.8.8 in any capacity; General advice is make sure that your server is configured, e.g. using bungeecord mode behind bungeecord. bearing in mind that UUIDs do NOT change on an online mode server, that either means that you've misconfigured your setup, or you're literally running your server in a mode where UUIDs are generated purely from the users name intentionally.

**Comment by wkw030210** [comment]
It is all configured as that, I have changed to a different version, the issue persists. The server is offline, and I have no idea what is going on, as I am unable to restore player inventories.

**Comment by wkw030210** [comment]
For now, I will use a plugin called OpenInv to manually edit.

**Comment by electronicboy** [comment]
If you mean, you're running an offline mode server, then yea; that's exactly how offline mode servers work.

**Comment by wkw030210** [comment]
The server is offline mode due to it being behind a bungee.

Edit: Nothing I can do to change that.

**Comment by electronicboy** [comment]
Then configure bungeecord mode properly and UUIDs will persist properly, you've more than likely misconfigured it and so bungeecord is not sending UUIDs to the server. Either way, this is outside the realms of Papers issue tracker, you need to read the documentation and configure bungeecord properly.

**Comment by wkw030210** [comment]
I believe that I have it configured properly, already asked BungeeCord support.
