### ISSUE TITLE
Lighting Queue continues to be a massive issue

### ISSUE THREAD

**Issue by 501warhead** [PaperMC/Paper#957]
# Performance issue

So, despite going to the version of Paper that has the reverted lighting changes in #903 our server is currently dying to lighting. Our server staff has been working hard to debunk issues with our code to see if it's related and has even made drastic steps by removing some anti-cheat just because we were spiking down to 5TPS at times.

This is absolute insanity to a point that currently we're having to consider backporting or quite literally switching back to Spigot. I hate to sound condescending when I understand this is stressful but our Players are quite literally fuming for the low performance caused by this lighting update when we switched to Paper for _greater_ performance, not less.

###  Timings or Profile link:
https://timings.aikar.co/?id=5c23c79b4b1d4c23b45f43b7d4d6c121
https://timings.aikar.co/?id=421ba05d636340369adac285f21e317b
https://timings.aikar.co/?id=6f4f8a427974406c9a4ca4917766069b

### Description of issue:
The lighting queue is horridly murdering server TPS. See the timings for proof. We started noticing this when we went to an earlier build and we updated to the latest Paper build last night, since then we have still experienced periodic cold blood murder of our TPS resulting in environments that are completely unplayable for our players. We've tried so much to resolve this manually even writing a small patch to flag chunks as "Already Lit" to avoid lighting updates. This has turned into absolute madness.

### Plugin list:
![javaw_2017-12-22_14-40-09](https://user-images.githubusercontent.com/11152237/34310560-2b34de16-e726-11e7-9e57-a7649d15f1b9.png)
(Many are in house plugins specifically built for the server by our Development Staff, who I am both a part of and have been debugging our code and have found little on our end.)

### bukkit.yml, spigot.yml, paper.yml, server.properties
server.properties: https://hastebin.com/olelatokab.ini
bukkit.yml: https://hastebin.com/melexemoya.coffeescript
spigot.yml: https://hastebin.com/ehebinitoq.coffeescript
paper.yml: https://hastebin.com/ujewazokim.coffeescript

These may be slightly different than what we are currently running because at this very moment we are trying solutions for this problem as best as we possibly can with configuration

### Paper build number: 1283

**Comment by electronicboy** [comment]
You have random light updates turned on inside spigot.yml, meaning that you have disabled spigots behavior that I restored recently.

**Comment by 501warhead** [comment]
We've disabled this now inside our config, we had actually done so before this post I believe but we hadn't restarted our server to let it take effect. We'll respond back and tell you what the results are after a restart, if this works it will save us a lot of stress. Thank you for the fast response time

EDIT: Restart just occurred, 3:43PM EST. We'll be enabling timings and letting it stew for about an hour then we'll put our findings here.

**Comment by 501warhead** [comment]
Lighting queue has resolved itself. Now we're battling with entities but not having lighting queue spikes has helped a lot, thank you!
