### ISSUE TITLE
Just... a crash I guess

### ISSUE THREAD

**Issue by RainOfPain125** [PaperMC/Paper#963]
# Crash, Stacktrace

### Link/paste of stack trace
https://pastebin.com/B13HPQY9
    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Plugin list:
___A list of your plugins___ AutoSave, BlowableObsidians, BookUtils, CFD, Citizens, CombatLogX, CompatNoCheatPlus, CoreProtect, CrazyCrates, Essentials, EssentialsChat, FactionChat, Factions, HolographicDisplays, LuckPerms, MassiveCore, mcMMO, MessageAnnouncer, MobArena, Multiverse-Core, NoCheatPlus, OldCombatMechanics, Orebfuscator4, PaidRanks, PlayerHeads, ProtocolLib, ServerListPlus, ShulkerBlock, SilkSpawners, SuperTrails, Vault, WarningCategories, Wild, WorldEdit
### Actions to reproduce (if known): All I know is from the logs an OP tried to spawn some entity, he isn't online right now to tell me what he did.
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number: git-Paper-1286 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

**Comment by electronicboy** [comment]
Your server took too long to tick, I'd suggest keeping your eyes on timings in order to pick up any potential lag spikes from plugins.
