### ISSUE TITLE
Cannot Update Past Build 1253

### ISSUE THREAD

**Issue by NFRCG** [PaperMC/Paper#965]
Hello, 

I am having difficultly getting the latest versions of Paper on my server, because I cannot update past build 1253. I have tried searching for a similar issue and have not found one, so I am opening an issue here (If there is documentation or another issue on why this happens, please direct me there.)

Basically what happens is that when I start up my server, it hangs when it is, "Preparing start region for level 3 (Seed: )". on any Paper version above 1254. I have tried versions, 1254 1255, 1258, 1270, and 1296 (as numbered on the Jenkins server), all of which have hanged. I have tried a few things already to try and pinpoint the issue. I am thinking about simply moving the most important builds from this world into a new world, and simply deleting the world where the issue might be occurring, but I figured I would open this issue first and see if there is any alternatives I should try. 

I have: 
- Tried moving exact plugin list to another server to see if a plugin was hanging the server (Server did not hang)
- Tried loading in exact copy of the world which has the matching seed on another server (Server did not hang)

Link/paste of stack trace: https://paste.md-5.net/rijaguboqo.vbs
Plugin list: https://i.imgur.com/6uGlkc4.png
Paper build number: 1253
/version output: This server is running Paper version git-Paper-1253 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) You are 43 versions behind.

Any help would be greatly appreciated, as I would like to continue to take advantage of the wonderful server software that you all have created. Thank you. If you need any additional info I can try my best to provide that.

**Comment by Black-Hole** [comment]
Build 1254 added this commit:
https://github.com/PaperMC/Paper/commit/0f2c2749982e55cd496c7a765ddbd1dbc22c904b

What generator settings did you use for this world?

**Comment by NFRCG** [comment]
The world was generated with Multiverse with the following command: "/mv create flatworld2 normal -t flat" which generated a flat world with structures. 

Here is a paste of my worlds.yml from Multiverse if that also helps at all: https://paste.md-5.net/vegesogito.sm

**Comment by aikar** [comment]
@NolanMC im really confused on what could even cause slowdowns there in that.

can you paste output of ls -la flatworld2/data/

also, can you try using VisualVM to debug and get a CPU Sample while its hung (dont start sampling until its hung)

Theres nothing in that code i can see that would make it take a long time/hang.

**Comment by electronicboy** [comment]
Closing due to two weeks and no reply, feel free to bump this issue if you're able to provide the relevant information.
