### ISSUE TITLE
Print helpful warning if 'commands' section is found in paper-plugin.yml

### ISSUE THREAD

**Issue by A248** [PaperMC/Paper#9669]
### Is your feature request related to a problem?

Some developers expect to use the `commands` section in the paper-plugin.yml as they do in the plugin.yml. This is unsupported, which causes calls such as `getCommand("myCommand").setExecutor(someExecutor)` to fail with a NPE.

A NPE does not immediately explain the cause of the bug, namely that the developer expects to use the commands section but the commands section is no longer a feature. So the developer revisits the paper-plugin.yml, checks for typos, checks the code again, recompiles and reruns, and it still doesn't work. Then they maybe read the documentation on Paper plugins one more time, or join the PaperMC discord (as has happened recently) to debug.

### Describe the solution you'd like.

If the commands section is found, print a warning message informing developers it is not available using paper-plugin.yml and programmatic registration is preferred.

It may be worth even throwing an exception and refusing to load the plugin. I can see no other reason to use the commands section if paper-plugin.yml is not in use.

### Describe alternatives you've considered.

Do nothing, and continue to sustain inquiries and support requests on this.

The documentation is already sufficiently prominent, so I see nothing to change there.

**Comment by Leguan16** [comment]
I don't think it should refuse to load the plugin. Either it throws an exception or a warning. 

For me it makes more sense to show a warning than an exception because there is not really a "downside" of the command section existing in `paper-plugin.yml`.

**Comment by MiniDigger** [comment]
I would argue in favor of an error, since the file doesn't fit the schema and its a clear developer error

**Comment by Leguan16** [comment]
but it doesn't break the plugin nor does it have it any notable performance downsides.

**Comment by the456gamer** [comment]
i would say warning in dev env, in case for backwards compatable schema changes (like when folia was added)

**Comment by the456gamer** [comment]
Does node.isVirtual() work? Or similar

**Comment by Leguan16** [comment]
that was the first thing I checked. `isVirtual` always returns true. Wether its in the config or not. 
That's because it just doesn't parse commands. 
The only thing I can think of is to add a new node resolver. 
However i quickly tested it with a check in the `FlattenedResolver` and that doesn't seem to get a `commands` tag either.

**Comment by Leguan16** [comment]
Ok so I did a mistake. I only defined a `commands` tag with no actual commands in it. 
I tested it with a command defined and now it works with `virtual()`! 

The warning is printed very early (Before the Environment log).
