### ISSUE TITLE
Timings enabled in paper config causing crash

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#968]
Paper version git-Paper-1296 (MC: 1.12.2)
Log: https://hastebin.com/bibatutafo.vbs
Crash report: https://hastebin.com/gexizudake.sm

An easy fix at the moment for me is disabling the timings in paper:

timings:
  enabled: false

Just wanted to report this issue though in case anyone else is affected by it.

**Comment by electronicboy** [comment]
This is pretty much 100% going to be guaranteed down to plugins modifying the world async, the size of the tile entity array in a chunk has been modified while the server is getting the tileentities and grabbing their CB wrappers.
