### ISSUE TITLE
Chest doesnt transfer items into a minecart with hopper

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#972]
The transfer of items from a chest into a minecart with hopper is broken. In the single player it works perfectly fine. The test constructions looks like this: https://imgur.com/a/uICSE

Version: 1.12.2 Paperspigiot #1300

>   hopper:
>       push-based: false

> use-hopper-check: false

>  ticks-per:
>       hopper-transfer: 8
>       hopper-check: 1
>     hopper-amount: 1

I will be grateful for any help you can provide :)

**Comment by aikar** [comment]
@TheoRetisch1 cannot reproduce:
https://i.imgur.com/JBNowk4.png

I put those strings in the chest, and was immediately sucked out

**Comment by aikar** [comment]
You likely have a plugin causing this.

**Comment by TheoRetisch1** [comment]
Thank you for the info and sorry for bothering you. I found the issue by removing and adding all plugins. The bug was related to FAWE/Worldedit thats funny because no block was placed with worldedit xD. I deleted the worldedit.jar and used a new one which is automatically created by FAWE. That fixed the issue :)
