### ISSUE TITLE
Worldguard doesnt load

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#975]
Sometimes Worldguard doesnt load at the server start. I believe that this issue is related to PaperSpigiot because I didnt changed anything regarding Worldguard. With sometimes I mean sometimes I can start and stop the server multiple times with no change at all but Worldguard will still enable or disable randomly. I tested it with version 1300 and 1305 here are the logs: 
https://pastebin.com/kvhuUb93
https://pastebin.com/QbM2cbcH
Since Worldguard is very essential I will be grateful for any help you can provide :)

Worldguard version: 6.2.2 - SNAPSHOT: 1710-95b88ea

**Comment by electronicboy** [comment]
Install WorldEdit, as per every plugin on your server complaining that it's not installed.

**Comment by TheoRetisch1** [comment]
Sorry, thanks 👍
