### ISSUE TITLE
Option to disable warning on deprecated recipe API use error spam.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#977]
Paper dev 1305 (Spigot 1.12.2)

Would it be possible to implement an option to _disable_ the warning on deprecated recipe API use? A plugin I use (ArtMap) does not seem to be in any form of active development. With this Paper patch https://github.com/PaperMC/Paper/commit/ece3333123a97990408be5392361e288b63835ba, the plugin is spamming java.lang.Throwable errors 29 times every time the server is started up.

https://paste.ubuntu.com/26149717/

RE: https://github.com/Fupery/ArtMap/issues/65

If not, is there an easy change method or guide I can do to resolve the issue in the plugin?

**Comment by electronicboy** [comment]
providing an option to remove warnings about bad behavior, especially ones which could be blocked in the future, is generally a bad idea, the decision to add this warning message is to inform users of another warning message that not creating recipes with the new method will cause.

This is a pretty trivial fix for all plugins, and just requires passing a NamespacedKey to the recipe they're creating https://hub.spigotmc.org/javadocs/spigot/org/bukkit/NamespacedKey.html
