### ISSUE TITLE
Server Crash (x2)

### ISSUE THREAD

**Issue by TheRealGuru** [PaperMC/Paper#979]
### Description of issue:
Server crashing unexpectedly, both the stack traces below were 15 minutes apart. Their is mention of velocity in the 2nd but the 1st I can't seem to work out why either are breaking. The main minecraft thread is hung on the exact same block of code in both, which I feel like can't be a co-incidence.

### Plugin list:
Mostly custom plugins

### Stack Traces

https://hastebin.com/oyotijosom.md
https://hastebin.com/esepihemob.sql

### Paper build number:
This server is running Paper version git-Paper-8b3c5fbd (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
Both crashes indicate that a player is moving too fast, which ends up with large calls to getCubes() which is a pretty expensive operation.
