### ISSUE TITLE
Simple and absurd, TAB Completion

### ISSUE THREAD

**Issue by DonKolia** [PaperMC/Paper#9795]
### Expected behavior

TAB Completion

### Observed/Actual behavior

TAB Completion

### Steps/models to reproduce

TAB Completion

### Plugin and Datapack List

No mather, it happens without plugins.

### Paper version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-167 (MC: 1.20.1)

### Other

I have been removing and restarting plugins. It is giving failures continuously. And this is the first time I write a bug like this on a server version.
It is very, very rare for this to happen.

**Comment by Machine-Maker** [comment]
Provide the stacktrace/log of the "failures" you are talking about.

**Comment by DonKolia** [comment]
I'll be honest, it's the first time it's happened to me with Paper and on a server-side version. I've been creating servers for 9 years and this is the first time it's happened to me, TAB Completion doesn't work with any plugin.

**Comment by DonKolia** [comment]
Either I have something wrong with the Java version or it's a bug in the .jar server.

**Comment by Leguan16** [comment]
You issue is not helpful. Can you please provide more information? 

What did you observe?
What did you expect?
What plugins do you use while observing it?

The team cannot magically fix a bug with only "Tab completion" as information.
