### ISSUE TITLE
Mob spawning ignoring light levels.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#98]
Getting complaints that mobs are spawning right next to players underground when entire paths are lit up. Mobs spawning right next to a light source. On Paper 518.

Caused by this commit? https://github.com/PaperMC/Paper/commit/7c7f8b83abeab860159293b13089b67f2a4b3d0d

Downgrading to Paper 502, everything is fine. Tested personally in areas that were affected.

**Comment by aikar** [comment]
resolved, missed an inversion
