### ISSUE TITLE
Server crash. (Help Needed)

### ISSUE THREAD

**Issue by keksbg** [PaperMC/Paper#982]
# Crash, Stacktrace
### Link/Paste of the stack trace
https://hastebin.com/ritinizizo.bash
### Plugin list:
ClearLag, PermissionsEx, WorldEdit, AsyncWorldEdit, Vault, Essentials, EssentialsChat, WorldGuard, ProtocolLib, Mango, Notorious, LiteBans
### Actions to reproduce (if known):
Currently unknown. Happens when I join the server or anyone else joins the server.
### Paper build number:
git-paperspigot-a925999
### Extra Information
Happens with whitelist on and off.
Full log of startup, and stop: https://hastebin.com/ofuxodaruw.sql

**Comment by aikar** [comment]
Please update to the latest version to receive support. 1.7 is many years old and has numerous crash bugs.

**Comment by keksbg** [comment]
I am here to create an HCF server, not a survival server.

**Comment by aikar** [comment]
You will need to consult your developer for assistance then. If you do not have one, you will need to find one on the Spigot Services section.

**Comment by 0-x-2-2** [comment]
Well looking it it it says "Insufficient system resources to execute the requested service" after I google translated it lol. it also looks like you have corrupted chests or chunks with chests in them.
