### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#983]
I experienced a server crash and cant find the reason. I am not sure if this very long error is related to Paper and appreciate every help you can provide :)

server.version: git-Paper-1300 (MC: 1.12.2) / 1.12.2-R0.1-SNAPSHOT - Yes I will update now :)
error: https://pastebin.com/KQ63xksD

**Comment by aikar** [comment]
Ultimately, your server ran out of memory:

[18:08:22] [ForkJoinPool-1-worker-2/WARN]: java.io.IOException: Compression error: cannot create header: Allocation error : not enough memory


However, it was all done during A FastAsyncWorldEdit operation, so it is likely the source of the issue.

**Comment by TheoRetisch1** [comment]
Thank you really much :)
