### ISSUE TITLE
Can't load without errors certain plugins.

### ISSUE THREAD

**Issue by xGioChR** [PaperMC/Paper#984]
# Crash, Stacktrace
This error occurs only using MassiveCombat 2.13.6 with Paperspigot.

### Plugin list:
AAC, AACAdditionPro, AnimatedMenuPlus, AnimatedNames, AnimationLib, AuthMe, AuthMeBridge, BetterDrops, ChatControl, Citizens, ConditionalCommands, CrateReloaded, CrazyEnchantments, DeluxeChat, DynamicSigns, EpicWorldGenerator, Essentials, EssentialsAntiBuild, EssentialsExtras, EssentialsMysqlStorage, EssentialsProtect, EssentialsSpawn, eZProtector, EZRanksPro, Factions, FactionWars, FactionWarsCORE, FastAsyncWorldEdit, FastLogin, FeatherBoard, HeadDatabase, HolographicDisplays, HolographicExtension, Jobs, LeaderHeads, LiteBans, LockettePro, LuckPerms, MassiveCombat, MassiveCore, MoneyMobs, MoreTPPlus, Multiverse-Core, MVdWPlaceholderAPI, MythicMobs, NoFlyZone, OnlyProxy, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, ProtocolSupport, ProtocolSupportStuff, ShopGUIPlus, SilkSpawners, SkQuery, skRayFall, Skript, Skungee, SpigotLib, Tab, TitleAdvanced, TradeMe, Vault, VoidSpawn, WorldEdit, WorldGuard.

**Comment by aikar** [comment]
This is not an error, its a warning that a plugin is doing something that it shouldn't.

Please report it to the plugin author so they can fix the issue with their plugin.
