### ISSUE TITLE
Server stopped responding (MC 1.12.2)

### ISSUE THREAD

**Issue by Andre601** [PaperMC/Paper#985]
# Crash, Stacktrace

### Link/paste of stack trace
https://file.properties/paste/iwisoyuhug.sql

### Plugin list:
```
Plugins (37): AdvancedCustomItemAPI, AdvancedCustomMenu, AdvancedModreq, Animatronics,
AntiBotDeluxeEX, ArmorStandTools, AuthMe, BannerBoard, ChatControl, DeluxePlugins,
DiscordSRV, Essentials, EssentialsSpawn, FastAsyncWorldEdit, FastLogin, FeatherBoard,
HeadDatabase, HelpPagePlus, HolographicDisplays, HyperDrive, LuckPerms, MessageMe,
Multiverse-Core, MVdWPlaceholderAPI, OpenTerrainGenerator, PlaceholderAPI, PlugMan,
ProtocolLib, React, ServerListPlus, SkinsRestorer, Vault, ViaBackwards, ViaVersion,
WorldEdit, WorldGuard, Wormholes
```

### Actions to reproduce (if known):
\-
### Paper build number:
git-Paper-1297 (MC 1.12.2)

NOTE: I updated Paperclip after that issue to the newest version, but still posting this here, for safety.

**Comment by electronicboy** [comment]
Your server took too long to tick, this is generally not a bug in the server software but down to issues such as plugins taking too long to process what they need to. I'd suggest keeping your eyes on timings.
