### ISSUE TITLE
These errors causing minor lags, between 3-5 seconds. Causing "timed out" error

### ISSUE THREAD

**Issue by VictoryAndGlory** [PaperMC/Paper#988]
Performance issue: Minor lags like between 3-5 seconds
Timings or Profile link: https://timings.aikar.co/?id=0de35185c4914c5b9b4b6ec29b1aa3b3
Description of issue: I have no idea why or when im getting this error.
Plugin list: https://puu.sh/z73oz/1302b44aa0.png
Other: I suspect from React and ChestShop plugins.
Paper build number: 1.12.2 b1248
What behaviour is expected: Not to see this error ->https://puu.sh/z727U/cd30fa384a.png
What behaviour is observed: Some players timing out when this happens -> https://puu.sh/z727U/cd30fa384a.png and https://puu.sh/z7277/5f6517440a.png
Paper build number: https://puu.sh/z73vl/f5e32cd73a.png
Crash, Stacktrace: https://hastebin.com/edeyidajic.vbs
Link/paste of stack trace: https://hastebin.com/edeyidajic.vbs

**Comment by electronicboy** [comment]
If a plugin is throwing exceptions and causing issues, it's generally a sign that you should remove the plugin and speak to the author.
Please also properly format your issue, We don't need everything on size 200 bold.

**Comment by VictoryAndGlory** [comment]
I wasnt trying to type bold. I just used default format of the editor and If I'm not wrong crash error directly pointing PaperSpigot for returning null value.
