### ISSUE TITLE
Riding custom entities in passenger doesnt fire VehicleMoveEvent

### ISSUE THREAD

**Issue by Legoman99573** [PaperMC/Paper#989]
### What behavior is expected:
When riding a custom entity, its suppose to fire the VehicleMoveEvent when you move and ride a custom entity
### What behavior is observed:
VehicleMoveEvent isnt fired as expected. I have tested using [this plugin](https://www.spigotmc.org/resources/✈️vehicles-no-resourcepacks-needed.12446/), which doesnt fire because of detecting passengers in a vehicle. Note that I don't own this plugin, but serves as a reference of the issue.
### Steps/models to reproduce:
https://youtu.be/IT1AeY__KyA

### Plugin list:
Plugins (70): Announcer, ArmorStandTools, AsyncWorldEdit, AsyncWorldEditInjector, BanManager, BKCommonLib, BlocksHub, BlockVersion, BukkitMemes, BuycraftX, CommandCooldown, CoreProtect, CreativeNbtControl, CustomTab, DiceFurniture, Essentials, EssentialsChat, EssentialsSpawn, ExtraContexts, FunnyDeathMessages, FurnitureLib, FurnitureMaker, HolographicDisplays, HomeGUI, JoinFullServer, LibsDisguises, LightAPI, LuckPerms, MaintenanceMode, MapPainting, Marriage, MiniaturePets, OpenAudioMc, OpenAudioMC_PlotSquared, OpenAudioMcSkript, PlaceholderAPI, PlotSquared, ProtectionLib, ProtocolLib, ProtocolSupport, ProtocolSupportAntiBot, React, Realistic-Swimming, RealTime, SaneEconomy, SharpSK, skDragon, Skellett, SkQuery, skRayFall, Skript, SkStuff, skUtilities, statuecreator, Train_Carts, TrainCartsOA, TuSKe, Umbaska, Vault, Vehicles, Vixio, Votifier, VotingPlugin, WGExtender, Whois, WildSkript, WirelessRedstone, WolvSK, WorldEdit, WorldGuard

### Paper build number:
This server is running Paper version git-Paper-1313 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
The VehicleMoveEvent is fired by the vehicle itself due to how entities move in the server during the tick loop. The plugin you've demonstrated is also more than likely going to be using armor stands as opposed to vehicle entities. This issue should be filed against them.
