### ISSUE TITLE
Skull loopups make server crash

### ISSUE THREAD

**Issue by jiongjionger** [PaperMC/Paper#991]
### Description of issue:
https://paste.ubuntu.com/26463465/
plugin create skull itemstack or block, the server will randomly lose response, and then crash.

### Paper build number:
latest version

# Suggestion
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/9b8bba4e50b071c7feb98105ba8b6003f8f42a5c
May be caused by directly execute sync skull lookups

**Comment by aikar** [comment]
This will always be a risk if the mojang api hangs

It is recommended plug in use the new skull api we added or reflection to set the textures directly without lookup

**Comment by aikar** [comment]
If you need to do skull look up by player name, create the skull async and then give it to the player sync, see https://taskchain.emc.gs

**Comment by jiongjionger** [comment]
Thank you very much for your reply, but unfortunately, some of the plugins I have no way to modify their code (premium or not opensource).

**Comment by aikar** [comment]
@jiongjionger you will have to consult those plugins authors.

This isn't a bug. Stuff is doing exactly as it's told to, and network issues happen.

Before that change, trying to set named base skulls would not work on the first open until the profile was cached.

So its best for plugin authors to cache the head on start, and even better would be to save it to a .yml file once looked up, but the best would be something like this:

https://github.com/TigerHix/Hex-Utils/blob/master/hex/util/Skull.java#L70

Set the texture payload directly on GameProfile (add authlib as a PROVIDED dependency to your plugin)
