### ISSUE TITLE
When the InteractEvent is canceled, The structure_block UI is opened (when clicking on it) !

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#992]
# Incompatibility (Bug)

### What behaviour is expected:
The UI of the Structure Block shouldn't open.

### What behaviour is observed:
It does open.

### Plugin list:
Just my own TestPlugin

### Paper build number:
version 1.12.2-R0.1-SNAPSHOT

**Comment by electronicboy** [comment]
Fixed locally, just pending on #1000

**Comment by electronicboy** [comment]
Should be fixed in https://ci.destroystokyo.com/job/Paper/1324/
